### ISSUE TITLE
[Feature] allow hidden components be clicked.

### ISSUE THREAD

**Issue by hry625** [microsoft/playwright#28346]
Hi,

I am developing an office AddIn with the React framework. I am trying to use Playwright to do the integration test. Unfortunately, all the Office 365's buttons are hidden as well as the UI components of my AddIn. I could locate the UI components with Playwright's locator, but it was not possible for me to interact with either Office 365's button(to open my AddIn, so I have to manually open AddIn) or click the buttons in my AddIn. 

It would be great if you could allow interaction with the hidden components on the web so that it would be much easier for automated testing for Office AddIn development.

**Comment by mxschmitt** [comment]
We have a [`force: true`](https://playwright.dev/docs/api/class-locator#locator-click-option-force) flag which you can pass over when clicking, this might work for you.

Keep in mind, that Playwright is about emulating a user, a user can't click a button which is not visible.

Closing as per above.

**Comment by hry625** [comment]
> We have a [`force: true`](https://playwright.dev/docs/api/class-locator#locator-click-option-force) flag which you can pass over when clicking, this might work for you.
> 
> Keep in mind, that Playwright is about emulating a user, a user can't click a button which is not visible.
> 
> Closing as per above.

Thanks for the quick reply. I have tried out the force:true flag, still could not trigger the click. The strange thing is that the UI components are displayed and accessible on the browser, but still it passed the  expect(locator).toBeHidden() test. Any suggestions?

**Comment by mxschmitt** [comment]
We unfortunately need a clear reproduction in order to look into it.

**Comment by hry625** [comment]
Hi, I have created a demo project in [my repo](https://github.com/hry625/Playwright_excel_addin_demo).

I created a simple test in the example.spec.ts file. 
As the screenshots show,
` await expect(page.getByRole("button").filter({ hasText: "Taskpane" })).toBeHidden()`  the button is located by Playwright, and it is hidden. And when I try to run the `click()` function, it just hangs there.
<img width="1279" alt="截屏2023-11-27 12 30 52" src="https://github.com/microsoft/playwright/assets/10716480/1d3aa383-4bbf-4656-b08e-733b14c1e4e0">
<img width="1286" alt="截屏2023-11-27 12 30 32" src="https://github.com/microsoft/playwright/assets/10716480/421306f9-ce8d-4bde-916f-582cdc1c050b">


To reproduce the result: 
1. clone the [demo repo](https://github.com/hry625/Playwright_excel_addin_demo)
2. run `npm install`
3. open an empty Excel file in [Office 365 web version](https://www.office.com/), copy the file URL, and replace the "'path/To/An Empty Excel file'" with the Excel file URL. 
4. run `npx playwright test --ui `in terminal.
5. select the click Show taskpane button test and run it.
6. the test will pause and let you enter your username and password for your Office 365 account.
7. After your logged into the excel, you need uplpoad the manifest.xml file provided in my repo. (Add-ins-> get Add-ins-> My ADD-INS/MY ORGANIZATION->  UploadMy Add-in(top right side of the pop-up window)->upload the manifest file from your machine). Notice: if you could not find the Add-in after you uploaded the manifest file, you could create a new page in the playwright test chromium environmnet, go to http://localhost:3000/taskpane.html to allow Chromium to access the http content. And then go back to the Excel page and refresh, you should be able to see the show taskpane AddIn same as that in the previous screenshots.
8. After you have the Add-In loaded, you should be able to click it and interact with the Add-In, and if you continue the Playwright test, it should pass the expect.toBehidden test but hanging on the click() function.

If you have any questions, just let me know. 

Thanks a lot for your great help.

**Comment by mxschmitt** [comment]
We are unfortunately not allowed to install custom Addons. Is there another way of reproducing this without of installing that? I otherwise recommend setting the `DEBUG=pw:api` env var to see more logs, or using Inspector / Trace Viewer to debug this issue further.

**Comment by hry625** [comment]
If you could install the Script lab Add-In from the Store(as shown in the screenshot), you could change the example test code to 
`await expect(page.getByRole("button").filter({ hasText: "Ask the Community" })).toBeHidden()`
`await page.getByRole("button").filter({ hasText: "Ask the Community" }).click({ force: true })`
to test it
This add-in has the same behavior.

<img width="692" alt="截屏2023-11-27 15 28 59" src="https://github.com/microsoft/playwright/assets/10716480/89efe6aa-52b8-400a-9d0e-fbf6196d2d7b">

Otherwise, if you cannot install any addin at all, you can test the Add-ins button in the panel
`await expect(page.getByRole("button").filter({ hasText: "Add-ins" })).toBeHidden()`
`await page.getByRole("button").filter({ hasText: "Add-ins" }).click({ force: true })`
The behavior is similar, but the testing scope is deviated in this case.

**Comment by pavelfeldman** [comment]
You can't force a click of invisible element, sorry about the confusion (cc @mxschmitt). Force is to forcing occluded element, but if there is no point to click, click won't happen. Use programmatic click instead: https://playwright.dev/docs/input#programmatic-click

**Comment by hry625** [comment]
> You can't force a click of invisible element, sorry about the confusion (cc @mxschmitt). Force is to forcing occluded element, but if there is no point to click, click won't happen. Use programmatic click instead: https://playwright.dev/docs/input#programmatic-click

I have tried that solution and it doesn't work in this case.

**Comment by hry625** [comment]
It also hangs there.
<img width="1273" alt="截屏2023-11-27 18 29 13" src="https://github.com/microsoft/playwright/assets/10716480/6834d986-5439-4b91-b4a2-a9021db70267">

**Comment by pavelfeldman** [comment]
That's because the button with such text does not exist. You should query it at `getByRole('button', { name: 'Taskpane' })`, but my understanding is that it is not in DOM. You need a button to be in the DOM in order to click it. Hidden check passes because hidden returns true for something that is not in DOM.

**Comment by hry625** [comment]
I am still a little bit confused. The taskpane button is located inside an iframe, but as shown in the screenshot from playwright inspector, the pw could locate the taskpane button (in blue area), which is rendered and displayed, but both click() and dispatchEvent('click') just hangs there.

<img width="1279" alt="截屏2023-11-27 12 30 52" src="https://github.com/microsoft/playwright/assets/10716480/c1d5d294-f353-42bb-b29f-0b7d023bfb90">

**Comment by pavelfeldman** [comment]
I am no longer sure I understand the issue. You are saying "allow hidden components to be clicked". That feature exists and is called programmatic click (dispatchEvent). But now you are saying that the component is in fact visible (highlighted with blue on the screen). So it looks like we are now talking about something different.
- Please adjust the issue title (component is not hidden)
- Provide the lists of steps that you perform along with the expected and actual behavior.
- Attach the test trace (--trace on)

**Comment by hry625** [comment]
The problem is that Playwright is considering a displayed button as a hidden element（since the toBeHidden test passes） and could not interact with it either with click() or dispatchEvent("click").  

To reproduce the problem, please follow my previous comments:


> Hi, I have created a demo project in [my repo](https://github.com/hry625/Playwright_excel_addin_demo).
> 
> I created a simple test in the example.spec.ts file. As the screenshots show, ` await expect(page.getByRole("button").filter({ hasText: "Taskpane" })).toBeHidden()` the button is located by Playwright, and it is hidden. And when I try to run the `click()` function, it just hangs there. <img alt="截屏2023-11-27 12 30 52" width="1279" src="https://private-user-images.githubusercontent.com/10716480/285848860-1d3aa383-4bbf-4656-b08e-733b14c1e4e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNTY3MzAsIm5iZiI6MTcwMTE1NjQzMCwicGF0aCI6Ii8xMDcxNjQ4MC8yODU4NDg4NjAtMWQzYWEzODMtNGJiZi00NjU2LWIwOGUtNzMzYjE0YzFlNGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA3MjcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlMjE1MDZiODZkYzU0YjYwNDU0M2Q1OTVkMjkwMzVmMjUyN2JjNjc4NjBjNzAyNjMyZjVkMDA0NDJjNjI5ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rmv9cn7SeFtCXfG3qonRrcBxWFTqYUpvLcV3PwwEkMw"> <img alt="截屏2023-11-27 12 30 32" width="1286" src="https://private-user-images.githubusercontent.com/10716480/285848870-421306f9-ce8d-4bde-916f-582cdc1c050b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNTY3MzAsIm5iZiI6MTcwMTE1NjQzMCwicGF0aCI6Ii8xMDcxNjQ4MC8yODU4NDg4NzAtNDIxMzA2ZjktY2U4ZC00YmRlLTkxNmYtNTgyY2RjMWMwNTBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA3MjcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkZTdiZjk5Yzc5NTQ5NjkzMWQ0ODc0NTA5OTUyZDVmNDZlYTJhOWU0MzIwMDgxMmJjNmZkYWZjZWY5ZjI3Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZcUJCzedGRYGF4jzI3YmW96qcpspqMpFyJqLUUupCvI">
> 
> To reproduce the result:
> 
> 1. clone the [demo repo](https://github.com/hry625/Playwright_excel_addin_demo)
> 2. run `npm install`
> 3. open an empty Excel file in [Office 365 web version](https://www.office.com/), copy the file URL, and replace the "'path/To/An Empty Excel file'" with the Excel file URL.
> 4. run `npx playwright test --ui `in terminal.
> 5. select the click Show taskpane button test and run it.
> 6. the test will pause and let you enter your username and password for your Office 365 account.
> 7. After your logged into the excel, you need uplpoad the manifest.xml file provided in my repo. (Add-ins-> get Add-ins-> My ADD-INS/MY ORGANIZATION->  UploadMy Add-in(top right side of the pop-up window)->upload the manifest file from your machine). Notice: if you could not find the Add-in after you uploaded the manifest file, you could create a new page in the playwright test chromium environmnet, go to http://localhost:3000/taskpane.html to allow Chromium to access the http content. And then go back to the Excel page and refresh, you should be able to see the show taskpane AddIn same as that in the previous screenshots.
> 8. After you have the Add-In loaded, you should be able to click it and interact with the Add-In, and if you continue the Playwright test, it should pass the expect.toBehidden test but hanging on the click() function.
> 
> If you have any questions, just let me know.
> 
> Thanks a lot for your great help.

I expect  
1.  the `await expect(page.getByRole("button").filter({ hasText: "Taskpane" })).toBeHidden()` test fail, but actually it pass.
2. `await page.getByRole("button").filter({ hasText: "Taskpane" }).click()` or
  `await page.getByRole("button").filter({ hasText: "Taskpane" }).dispatchEvent('click')` should open the taskpane same as a user click the button, but actually it just hangs and waiting for page.getByRole("button").filter({ hasText: "Taskpane" }).

The trace file is here: [dispatchEvent.zip](https://github.com/microsoft/playwright/files/13493324/85c498d2b17d95a12d181819d389986d.zip)

**Comment by pavelfeldman** [comment]
Your elements are in the iframe, the right locator is:

`page.frameLocator('iframe[name="WacFrame_Excel_0"]').getByLabel('Show Taskpane')`

**Comment by hry625** [comment]
It works. Thanks a lot for the great help. Have a nice day.

**Comment by ShiladityaGhosh** [comment]
Hello, I am hitting this issue now with the Excel WebApp now. And found this thread very useful! 

I am using the locator suggested by the pick-locator tool (also mentioned https://github.com/microsoft/playwright/issues/28346#issuecomment-1830827026) 

`page.frameLocator('iframe[name="WacFrame_Excel_0"]').getByLabel('Show Taskpane')`

but still not able to click the button. It seems that the element picked up by the locator _getByLabel_ is always hidden although clearly visible on the UI. Not sure what else to try here, could you please provide some input. Should I switch to a particular playwright version where this used to work?

**Comment by ShiladityaGhosh** [comment]
Hi @pavelfeldman - sorry for the direct tag, is there something else that I might be missing? I was expecting the locator suggested by the pick-locator tool to work as is, but it doesn't seem to work.
