### ISSUE TITLE
[BUG] test can't click the element, but when use codgen it can detect the element.

### ISSUE THREAD

**Issue by hengyu-gary-lin** [microsoft/playwright#28349]
### System info
- Playwright Version: [v1.37.1]
- Operating System: [Ubuntu 20.04 LTS]
- Browser: [Chromium]
- Other info:

### Source code

- [o] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

**Test file (self-contained)**

```js
    async filterStatus(status: string) {
        await this.page.waitForSelector('#shortage_comp_list_status svg');
        await this.page.locator('#shortage_comp_list_status svg').first().click();
        switch (status.toLowerCase()) {
            case 'raised':
                await this.page.locator('[id^="react-select-"][id$="-option-0"]').click(); //raised
                break;
            case 'complete':
                await this.page.locator('[id^="react-select-"][id$="-option-1"]').click(); //complete
                break;
            case 'cancelled':
                await this.page.locator('[id^="react-select-"][id$="-option-2"]').click(); //cancalled
                break;
            case 'on going':
                await this.page.locator('[id^="react-select-"][id$="-option-3"]').click(); //On going
                break;
            default:
                console.error(`Unknown status in filterStatus: ${status}`);
                break;
        }
    }
```

**Steps**
I use codegen to generate locator, but this element I can't click on test  after generate from codegen.
- [Run the codegen]
![image](https://github.com/microsoft/playwright/assets/104434640/89171b72-c208-420a-94c8-3a81c2384835)
![image](https://github.com/microsoft/playwright/assets/104434640/a34ee620-6005-4863-a940-da2333225d9e)

**Expected**

It should be able to click.

[Describe expected behavior]

**Actual**
The result is playwright keeps waiting for the dropdown option.
I have used selectOption, it didn't work for react, so I use click and choose option.
![image](https://github.com/microsoft/playwright/assets/104434640/cd81e637-9419-4b29-8236-d266e8a498c7)

[Describe actual behavior]

**Comment by mxschmitt** [comment]
We unfortunately need a self-contained reproducible in order to triage issues like this. Where we can run the code locally with a repro which is only surfacing the specific issue.

In the meantime I recommend Trace Viewer / Inspector in order to debug issues like this.

Feel free to re-file with more details.
