### ISSUE TITLE
[Question] Nested Locator

### ISSUE THREAD

**Issue by svitlanaduman** [microsoft/playwright#28353]
Hi,

I have a following case. My page contains several groups of data.
Each group has an id, which is used to find this locator. Is it possible to get a list of nested elements in this group which have non empty id, so I can check whether a particular element is a part of this group?

Thank you
Best regards
Svetlana

**Comment by pavelfeldman** [comment]
Could you provide example of your DOM?

**Comment by imartinflores** [comment]
@svitlanaduman if you find the parent element of each group, from there you can find the nested elements using :not([id="]) as a cssSelector. i.e:

#mainGroup > :not([id=""]) or :not([id]) if even the attribute is not there

**Comment by imartinflores** [comment]
@svitlanaduman Not sure if I understood properly, but if I did,  I think if you find the parent element of the group, you can then find the locators using :not in the cssSelector. i.e:

page.locator('#groupId > :not([id=""])')

**Comment by imartinflores** [comment]
@pavelfeldman good to know! may I know why just to understand? is it because the way it looks for the elements in the DOM?

**Comment by pavelfeldman** [comment]
I'd like to see the actual DOM before I respond.

**Comment by imartinflores** [comment]
Thank you! Makes sense, I was testing it with any site , didnt know the structure of it can affect this
![image](https://github.com/microsoft/playwright/assets/17011557/c183feda-915d-482f-be45-50bf5e3cef5a)

**Comment by svitlanaduman** [comment]
Hello,

basically here is a snippet from the DOM.

<div class="Vg8xIcEhoJ1CLHxFl_yO">
<label id="**pd-per-info-lbl**" class="t0oTSnRcZPY3euuKnzRq nfsba14 _3v655f0 _1dihk516 af0oqr4 nfsba10 nfsba10">Personal information</label><div class="JRwzUhywtHkCP5fhVcuK">
<hr class="fh1ttb0 c25fx46 y4EMdnPbHxAH3LxJpdfl">
<div class="Gh1Zt256uvJY52mi5VSB">
<div class="UkZQHb6HrUOr_a_MUiYD">
<div class="_1sdue9r0 _1sdue9ru">
<label id="**pd-id-lbl**" class="wXrTsvgFiAwAzyDGzTbC nfsba14 _3v655f0 _1dihk516 af0oqr4 nfsba10 nfsba10">Patient ID</label>
<label id="**pd-id-val**" class="oGUFYXDelnVlrWofEqAJ nfsba14 _3v655f0 _1dihk516 af0oqr4 nfsba10 nfsba10">29583023</label>
</div>
</div>
<div class="UkZQHb6HrUOr_a_MUiYD">
<div class="_1sdue9r0 _1sdue9ru">
<label id="**pd-name-lbl**" class="wXrTsvgFiAwAzyDGzTbC nfsba14 _3v655f0 _1dihk516 af0oqr4 nfsba10 nfsba10">Name*</label>
<label id="**pd-name-val**" class="oGUFYXDelnVlrWofEqAJ nfsba14 _3v655f0 _1dihk516 af0oqr4 nfsba10 nfsba10">Sophia Rasgoda</label>
</div>
</div>
<div class="wcUBKtAyLflSkXF5qy2k">
<div class="_1sdue9r0 _1sdue9ru">
<label id="**pd-dob-lbl**" class="q5UtbEexCyflI92zdPIW nfsba14 _3v655f0 _1dihk516 af0oqr4 nfsba10 nfsba10">Date of birth*</label>
<label id="**pd-dob-val**" class="y26rVP8w4Ie68li9sboT nfsba14 _3v655f0 _1dihk516 af0oqr4 nfsba10 nfsba10">Invalid Date (NaNy)</label>
</div>
</div>


</div>
</div>
</div>

I've highlighted bold the elements, as you can see the first bold id is the group name and I would like to have all bold elements within this group.

Thank you.
Looking forward to your recommendations.

**Comment by pavelfeldman** [comment]
In your case I would go for the ids right away:

```js
await expect(page.locator('id=pd-name-val')).toHaveText('Sophia Rasgoda');
```

**Comment by pavelfeldman** [comment]
Do you want to check that "Name" and "Sophia Rasgoda" are in the same "group"? How do you intend to use/assert this information?
