### ISSUE TITLE
 Error: browserType.launch: Target page, context or browser has been closed[BUG: 

### ISSUE THREAD

**Issue by vaishalisoni1093** [microsoft/playwright#28350]
### System info
- Playwright Version: 1.40.0
- Operating System: [docker alpine, etc.]
- Browser: [Chromium]
- Other info:
  Logs :
  
    Error: browserType.launch: Target page, context or browser has been closed
    Browser logs:

    <launching> /root/.cache/ms-playwright/chromium-1091/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-hBoBMp --remote-debugging-pipe --no-startup-window
    <launched> pid=10527
    [pid=10527][err] Error relocating /root/.cache/ms-playwright/chromium-1091/chrome-linux/chrome: __mbrlen: symbol not found
    [pid=10527][err] Error relocating /root/.cache/ms-playwright/chromium-1091/chrome-linux/chrome: __sched_cpualloc: symbol not found
    [pid=10527][err] Error relocating /root/.cache/ms-playwright/chromium-1091/chrome-linux/chrome: __sched_cpufree: symbol not found
    [pid=10527][err] Error relocating /root/.cache/ms-playwright/chromium-1091/chrome-linux/chrome: initstate_r: symbol not found
    [pid=10527][err] Error relocating /root/.cache/ms-playwright/chromium-1091/chrome-linux/chrome: random_r: symbol not found

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
  ]
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]

**Actual**

[Describe actual behavior]

**Comment by mattchete** [comment]
Getting this error too 1 time out of 2 since 1.40. I relaunch the test and it works. I launch again and I get the error.

**Comment by mattchete** [comment]
macOS Sonoma 14.1.1 (23B81) here

**Comment by vaishalisoni1093** [comment]
> Closing as per above since Alpine is not supported. See here: https://playwright.dev/docs/intro#system-requirements

Hey it was working fine till last week, suddenly stopped working.
