### ISSUE TITLE
[BUG] Proxy Support on Firefox doesn't work

### ISSUE THREAD

**Issue by SentoxAIO** [microsoft/playwright#2835]
**Context:**
- Playwright Version: ^1.1.0-next.1593824801387 [Playwright-Firefox]
- Operating System: Windows
- Node Version: v14.1.0.
- Browser: Firefox

**Simplified Code Snippet:**
```javascript
let options = {
	headless: true,
};

options.proxy = {
         server: `${ip}:${port}`,
         username: username,
         password: password,
};

let browser = await firefox.launch(options);
```

**Error Description:**

When I try to launch a firefox browser instance with a proxy, I get this following error: 
```
NS_ERROR_PROXY_CONNECTION_REFUSED
====================== page.goto logs ======================
[api] navigating to "<WEBSITE_URL>", waiting until "load"
======================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.))
```

You probably think it's the proxy's fault but my whole team and users tried with different proxys from different services but none worked. So I cant imagine its on the proxy's side.

**Comment by serwer20** [comment]
same here :S
