### ISSUE TITLE
[BUG] Webkit CSS filter not applied on screenshot

### ISSUE THREAD

**Issue by sqrter** [microsoft/playwright#28363]
### System info
- Playwright Version: [v1.40.0]
- Operating System: [macOS 13.6]
- Browser: [WebKit]
- Other info: Apple M1

### Source code

- [x] I provided the exact source code that allows reproducing the issue locally.

There's a problem with the screenshots that I faced using Playwright. I could fix it by adjusting my CSS but I am still posting this here hoping to be fixed. I guess it relates to #13605

**Example HTML**

```html
<html>
<head>
  <style>
    body {
      background: linear-gradient(to left, black 50%, white 50%);
    }

    .rect {
      position: absolute;
      top: 50%;
      left: 50%;
      width: 100px;
      height: 100px;
      /*transform: translate(-50%, -50%); <-- this works fine */ 
      transform: translate3d(-50%, -50%, 0); /* <-- this doesn't */ 
      background: red;
      filter: grayscale(10%) blur(2px) opacity(0.3);
    }

  </style>
</head>
<body>
<div class="rect"></div>
</body>
</html>
```

**Steps**
- Open the HTML example in the WebKit browser
```
npx playwright open -b webkit test.html
```
- Take a screenshot of the HTML example in the WebKit browser
```
npx playwright screenshot --browser "webkit" test.html test.png
```

**Expected**

The screenshot should be the same as displayed in the browser.

<img width="1392" alt="286033063-62ab7eba-caa8-4dd2-9eea-a59ebd8364ce" src="https://github.com/microsoft/playwright/assets/479984/d850a26e-241d-4e09-871a-c5586f4be998">

**Actual**

The screenshot differs. CSS filter is not applied.

![test](https://github.com/microsoft/playwright/assets/479984/4fd2870a-c5f3-4d8b-a985-5563ada20ee5)

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/21620
