### ISSUE TITLE
[Feature] Response validation available in span or text field (Record Now)

### ISSUE THREAD

**Issue by FactohrHirenDobariya** [microsoft/playwright#28376]
I am preparing script using "Record Now" feature.

Once I complete data entry in a submit application form, and post receiving a response from the server we are getting a computed value in a span or text field available in the form, can we validate with recorded mode without typing the script.
Suppose the server response at the time of submit was Success in the span, now we run the test and we would to ensure that span should display Success after submission

We can write minimum JS code to verify the expected value, but is it possible that a non technical person can also verify the expected output available in the page after operation is completed without writing a code?

Example: 
await expect(await page.locator('#ctl00_DefaultContent_dcWages').inputValue()).toBe('1000.00');

This we wrote manually,

**Comment by pavelfeldman** [comment]
Yes, this feature is available in Playwright 1.40. Learn more about it here: https://www.youtube.com/watch?v=mn892dV81_8
