### ISSUE TITLE
[BUG]getByTex axact true not working

### ISSUE THREAD

**Issue by daniavander** [microsoft/playwright#28387]
### System info
- Playwright Version: [v1.40]
- Operating System: [ Windows 11]
- Browser: [All]
- Other info:

### Source code

`const yourLocator = await this.page.getByText(loc, { exact: true }).innerText({ timeout: 5000 })
console.log("deletable case: " + yourLocator)`

but if i use this code:

`const yourLocator = await this.page.getByText(loc).innerText({ timeout: 5000 })
console.log("deletable case: " + yourLocator)`

everything is working

I have more elements and i used exact:true well earlier

**Comment by pavelfeldman** [comment]
It works for me locally. Please use the [BUG] template and make sure you provide a scenario we can reproduce locally.
