### ISSUE TITLE
Add base image arg to Jammy Dockerfile

### ISSUE THREAD

**Issue by markdboyd** [microsoft/playwright#28383]
> Let us know what functionality you'd like to see in Playwright and what your use case is.

I'd like to add a `base_image` ARG to the Jammy Dockerfile. Our use case is that we need all containers running in our CI environment, which includes `playwright:jammy`, to used a hardened base image that we maintain. 

Currently, in order to build the Playwright Jammy Docker image on our custom hardened base image, we would need to maintain our own copy of the Dockerfile just to add a `base_image` ARG. Obviously, this is is not ideal, since over time our copy of the Dockerfile would drift from the upstream and miss out on important things like security fixes or other improvements.

> Do you think others might benefit from this as well?

For anyone else with a need to run Docker images using a hardened base image, yes, I could imagine this change being useful.

For those who don't need this change, the default of building on `ubuntu:jammy` would remain.

**Comment by pavelfeldman** [comment]
Sounds like this is not something we would want to do. The way our containers are built relies on internal scripts that we don't assume you'll be using (look through the dockerfile). What you should do is take your hardened base image, install npm there, install Playwright with npm and run `npx playwright install-with-deps`. That'll give you an image with the browsers installed.

**Comment by markdboyd** [comment]
@pavelfeldman Thanks for the reply!

What are the internal scripts that you're using? Is it this line?

https://github.com/microsoft/playwright/blob/main/utils/docker/Dockerfile.jammy#L31

I ask because our hardened image itself is also based on `ubuntu:jammy`, so for our case I was imagining that changing the base image in your Dockerfile would work rather seamlessly.

I can understand that this might be a niche use case that you don't generally want to support.

**Comment by pavelfeldman** [comment]
Yes, line 31 and alike, they assume that you are building Playwright and are running the right builds scripts in the right environment. We would not want you to depend on the implementation detail, especially if there is a nice layered alternative where you install Playwright and instruct it to install browsers in your docker spec, w/o the dependency on our internals.

**Comment by markdboyd** [comment]
OK. I appreciate the consideration and I'll take your suggestion. Obviously you can close this issue and the associated PR as you see fit. thanks!

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
