### ISSUE TITLE
[Feature] Unable to capture Alert/Confirm popups

### ISSUE THREAD

**Issue by FactohrHirenDobariya** [microsoft/playwright#28392]
I am recording a script using the "Record New" feature. 

While clicking on the button confirm popup comes up using record activity unable to capture the same. for that add the below code manually on a script to handle the confirm popup.

_ // For Confirm Popup handle
  await page.once('dialog', dialog => {
    console.log(dialog.message());
    dialog.accept();
  });
  await page.locator('#ctl00_DefaultContent_btnSaveUp').click();_

is there any way to capture the alert/confirm popups using Recording?

**Comment by pavelfeldman** [comment]
When I record clicking the button that opens a dialog, I see this generated:

```js
  await page.goto('...');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Click' }).click();
```

What is your expectation?

**Comment by FactohrHirenDobariya** [comment]
Same thing I'm doing but dialog-related code does not generate. is there any additional configuration or anything?

Can you share some video links or documentation for the same if you have one?

**Comment by pavelfeldman** [comment]
I run this:

```js
npx playwright codegen "data:text/html,<button onclick=alert(1)>Click</button>"
```
