### ISSUE TITLE
[BUG] The tc is faliling in headless mode.

### ISSUE THREAD

**Issue by vaishalisoni1093** [microsoft/playwright#28398]
### System info
- Playwright Version: [v1.40]
- Operating System: [macOS ]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:
when I run the test using  "npx playwright test --headed"

<img width="836" alt="Screenshot 2023-11-29 at 7 22 11 PM" src="https://github.com/microsoft/playwright/assets/67325336/b191e87a-a4d9-4751-b6ad-94f6be4e6024">

If I run in headless mode :
<img width="1192" alt="Screenshot 2023-11-29 at 7 22 56 PM" src="https://github.com/microsoft/playwright/assets/67325336/df6312cb-9693-4ad4-8a1f-27403bad45a6">

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
  ]
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]

**Actual**

[Describe actual behavior]

**Comment by pavelfeldman** [comment]
Works for me. Please follow the [BUG] issue template to make sure we can reproduce your issue.
