### ISSUE TITLE
[Feature] expect.optional()

### ISSUE THREAD

**Issue by kowalska-m** [microsoft/playwright#28395]
**Description:**
I have the situation where an element of an object may or may not occur. 
In this particular situation I do not care what the value of this element. I thought about using 'expect(value).anything()' but it works only when an element always occurs with any value. 

**Suggested solution:**
I would like to have possibility to compare those objects with pattern object which has defined something like 'expect.optional'.

**Example:** 
In the below case 'Q3' is an optional key and it present in second object and it is not present in third object but newly implemented assertion should passed in both cases.
```
test("Should object meet the pattern", async ({
  }) => {

    const firstObject = {
      "Q1": "value1",
      "Q2": "value2",
      "Q3": expect.optional();
      "Q4": {
        "QQ1": "value4"
      }
    };

    const secondObject = {
      "Q1": "value1",
      "Q2": "value2",
      "Q4": {
        "QQ1": "value4"
      }
    };

    const thirdObject = {
      "Q1": "value1",
      "Q2": "value2",
      "Q3": "value3",
      "Q4": {
        "QQ1": "value4"
      }
    }; 
  expect(secondObject).toEqual(firstObject); // Assertion passed
  expect(thirdObject).toEqual(firstObject); // Assertion passed
  });
```

_I am using the latest version of the Playwright 1.40._

**Comment by pavelfeldman** [comment]
This should solve your use case:

```js
const firstObject = expect.objectContaining({
  "Q1": "value1",
  "Q2": "value2",
  "Q4": {
    "QQ1": "value4"
  }
});
```
