### ISSUE TITLE
[BUG] Adding Script doesn't work

### ISSUE THREAD

**Issue by fawazahmed0** [microsoft/playwright#2839]
**Context:**
- Playwright Version: 1.1.1
- Operating System: Windows 7
- Node version: 12.18.0
- Browser: Chromium

**Code Snippet**

```javascript
var { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
await page.addScriptTag({url: 'https://code.jquery.com/jquery-3.5.1.min.js'})
await page.goto("https://www.example.com/")

value =  await page.evaluate(() => window.jQuery ? 'yes' : 'no');
console.log(value)
  await browser.close();
})().catch(console.error);

```
**Expected Output:**
yes

**Current Output:**
no

**Describe the bug**

Adding Script doesn't work, I even tried, page.addInitScript() option and that too doesn't seem to work for me

Thanks

**Comment by pavelfeldman** [comment]
With `page.addScriptTag`, you add it, but with `page.goto` you navigate to a completely new page that does not have it. Swap those two lines to make it work.

If you need injected script to be there during the page load, you can use `page.addInitScript()` before `page.goto`, but you need to fetch the script manually to pass into it.

**Comment by fawazahmed0** [comment]
@pavelfeldman  Thanks working fine now
