### ISSUE TITLE
[BUG] Playwright performed the action on the element but throws an error afterwards that  waiting for element to be visible, enabled and stable

### ISSUE THREAD

**Issue by lambaabhishek19** [microsoft/playwright#28409]
### System info
- Playwright Version: [v1.37]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [Chromium]
- Other info:

### Source code

identifier: this.lblSalutation = page.locator('[name="salutation"]');

- await this.lblSalutation.click();

**Steps**
- I am facing one flakiness in playwright, sometimes playwright already perform the click or type action on the element which I can verify from the  screenshot captured at he failed step but playwright throws an error. in above example step "await this.lblSalutation.click();" opens a dropdown  but playwright throws an error but when I look on the screenshot where test failed it already clicked on the element. This issue is not specific to a particular element or an application I faced similar behavior for different application and different elements.

locator.click: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator('[name="salutation"]')
  locator resolved to <button type="button" role="combobox" name="salutation" …>…</button>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action

**Comment by pavelfeldman** [comment]
Most likely you have a race condition in your test. We can only help if there is a way for us to reproduce the issue locally. Please follow the [BUG] issue template when filing bug reports.
