### ISSUE TITLE
[BUG] Browser stays open when running in headed mode

### ISSUE THREAD

**Issue by perezdev** [microsoft/playwright#28400]
### System info
- Playwright Version: [v1.40]
- Operating System: [Windows 10]
- Browser: [Chromium]

### Source code

I'm just running the default test in a new installation, which i've attached. If I run the test through the Playwright test extension, the browser stays open after it passes. If I run it headless through the command line, `npx playwright test` the processes close. But headed through the extension, it stays open.

Is there some configuration I need to add?

```
test('has title', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);
});
```
[pw-chrome-not-closing-test.zip](https://github.com/microsoft/playwright/files/13502117/pw-chrome-not-closing-test.zip)

**Comment by pavelfeldman** [comment]
When 'Show browser' setting is toggled in VS Code extension we keep the browser open so that you could inspect the post-run state. Uncheck it to hide the browser. There is no way to run tests in the headed mode via the extension.
