### ISSUE TITLE
[BUG] The test results artifacts trims test name

### ISSUE THREAD

**Issue by anujshah3** [microsoft/playwright#28403]
### System info
Any system
- Playwright Version: [v1.XX]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

**Steps**
- [Run the test]
- [test-result directory is generated]

**Expected**
The tests artifacts should be named after it's test name no matter how long the test folder name is.
`test-results/tests-ui-tests-param1-param2-param3-param4-param5-param6-param7-param8-param9-param10-param11-param12-param13`

**Actual**
The tests artifacts trims the name if the test name is too long, I have test parameters in the test name which makes it a very long string hence it would be helpful if I can preserve the entire test name in the test results.
`test-results/tests-ui-tests-param1-param2-param3-0fcae-ram7-param8-param9-param10-param11-param12-param13`

`0fcae-ram7` was supposed to be `param4-param5-param6-param7`.

**Comment by pavelfeldman** [comment]
Unfortunately all the supported operating systems have the limits on the file path length.
