### ISSUE TITLE
[Feature] gRPC support?

### ISSUE THREAD

**Issue by bootstraponline** [microsoft/playwright#2841]
> Let us know what functionality you'd like to see in Playwright and what is your use case.
> Do you think others might benefit from this as well?

What does the team think about having official gRPC bindings? This would enable Python, Kotlin, etc. to consume the playwright library.

https://github.com/MarketSquare/robotframework-browser/blob/master/protos/playwright.proto

**Comment by mxschmitt** [comment]
There is currency a RPC implementation in development, which will solve exactly these needs. Should be ready in a few releases.
In which languages are you most interested in?

**Comment by bootstraponline** [comment]
Kotlin, Dart

**Comment by pavelfeldman** [comment]
@bootstraponline, those are great languages, but is there any evidence people are interested in writing automated web tests in those? Would appreciate the pointers to the repos, project sizes, etc. Playwright wire won't be standardized for quite some time, so those SDKs will come at a maintenance cost.

**Comment by bootstraponline** [comment]
That’s why I mentioned gRPC. We’d get language support for free.

I’m curious what the vision is for the RPC architecture?

**Comment by bootstraponline** [comment]
Here are the currently supported languages for gRPC. 

- [Swift](https://github.com/grpc/grpc-swift)
- C# / .NET
- C++
- Dart
- Go
- Java
- Kotlin/JVM
- Node.js
- Objective-C
- PHP
- Python
- Ruby
- Web

https://grpc.io/docs/languages/

Java/JavaScript are hugely popular for [test automation](https://applitools.com/blog/language-software-test-automation/). Kotlin is able to use Java librarys, the same is true with Dart and JavaScript. First class support for arbitrary languages via auto generated gRPC bindings would be amazing.

**Comment by pavelfeldman** [comment]
@bootstraponline this topic is a bit more nuanced than generating the bindings.

As I mentioned above, it'll take us some time to arrive at a point where we can standardize our wire. Before that, gRPC is of no use - we can't commit to any of the protos, why generating bindings that won't work...

And more importantly, generated gRPC bindings work fine for the transport layer, but can hardly be used as a user-facing driver API. Playwright assumes certain level of API ergonomics where you can pass a handler in a form of a function / lambda / coroutine, pass arguments into your evaluate without the need to serialize / parse them manually, etc, etc. gRPC does not solve any of that. At the same time, for the transport, we don't need anything as restricting and heavy as gRPC. It is much easier to get our way into all the same languages with just JSON or CBOR.

So I'd encourage to think about this topic in terms of the user stories and prioritize the SDKs where we see the user, not where we can generate the gRPC bindings.

**Comment by bootstraponline** [comment]
Thanks for the info! It sounds like first party gRPC support isn't on the roadmap.
