### ISSUE TITLE
Using getByRow locator with the name option doesn't get all the texts within the row body

### ISSUE THREAD

**Issue by LukemansfieldPAX** [microsoft/playwright#28419]
### System info
- Playwright Version: [v1.40.0]
- Operating System: [Windows 11]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code
Due to security reasons I will be unable to provide the source code files.

![image](https://github.com/microsoft/playwright/assets/90900950/0e80382a-1fea-434d-907b-68a22ccef904)
![image](https://github.com/microsoft/playwright/assets/90900950/171abfe4-fde3-49c9-953a-e3c1a0f56902)

or

**Config file**

import { PlaywrightTestConfig, devices } from '@playwright/test';

const config: PlaywrightTestConfig = {
  testDir: 'tests',
  snapshotDir: 'screenshots',
  retries: 0,
  workers: 4,

  reporter: [
    ['list'],
    ['html', { open: 'never' }],
    ['junit', { outputFile: 'test-results.xml' }],
  ],
  use: {
    viewport: { width: 1920, height: 1080 },
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    ignoreHTTPSErrors: true,
    video: 'retain-on-failure',
  },
  expect: {
    // Other configuration options specific to assertions...
  },
  projects: [
    {
      name: 'E2E-Tests',
      testMatch: ['**/tests/**/*.spec.ts'],
      use: { ...devices['Desktop Chrome'] },
      fullyParallel: false,
      timeout: 60000,
      // Other configuration options specific to user stories...
    },
  ],
};
export default config;

**Test file (self-contained)**

```js
testWithApp('Correct information should be displayed when viewing invoice', async ({ app }) => {
    const invoiceDate = formatDate(new Date());
    await app.steps.logInSteps.login();
    await app.steps.navigationBarSteps.goToPay();

    const actualInvoice = await app.steps.paySteps.whenOnInvoicesGridGetInvoiceByDate(invoiceDate);
    await app.steps.paySteps.goToInvoiceDetails(actualInvoice.invoiceNO);

    await app.steps.paySteps
      .assertInvoiceChargesIsCorrect(companyObj, '£', true);
    await app.steps.paySteps.assertCompanyInformationOnInvoiceIsCorrect(companyObj);
  });

So on the invoice view we have a table with rows, table columns are Description, Quantity, UnitPrice, Total. my rows have a row attribute added and inside the row is divs that have the textContents. When I use the VS Code extension to pick a locator it resolves almost all of the texts within the row but cuts of the last text which is a problem. 

Please note where it fails is trying to find a locator (removed sensitive info from locator) which is: this.page.getByRole('row', name: {'Site 1 Users 2 £1.88 £3.76}. When I pick a locator it resolves to getByRole('row', name: {Site 1 Users 2 £1.88 £), so it removes the last value and I cannot understand why as the text content is in the same row body. I uploaded screenshot of the DOM. 

**Steps**
- [Run the test]
- Step 1 - Get today's date and login.
- Step 2 - navigate to Payment screen.
- Step 3 get invoice number based of today's date and click on invoice within payment grid.
- Step 4- check invoice details and get row texts to make sure costs breakdown are correct by checking visibility of the row locator .
- [...]

**Expected**

Locator I use should get ALL row textContents using the locator I used and I assert the locator is visible. 

**Actual**

Playwright unable to resolve locator because it seems to trim part of the text contents within the row body.

**Comment by pavelfeldman** [comment]
Since row is a visual term defined by the layout/css we can't introduce requested API.

**Comment by LukemansfieldPAX** [comment]
> Since row is a visual term defined by the layout/css we can't introduce requested API.

I understand the locator strategy is based from the layout/css which we control however shouldn't the Playwright API be able to resolve the full texts which are defined in the row body instead of resolving the texts to a certain point?
