### ISSUE TITLE
[BUG] `React.Children.only` in imported component raising error when it should not

### ISSUE THREAD

**Issue by tremby** [microsoft/playwright#28410]
(I wonder if this might be related to #28367 ?)

### System info
- Playwright Version: v1.40.0
- Operating System: Ubuntu 22
- Browser: All
- Other info: playwright/experimental-ct-react 1.40.0, React 18.2.0

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```ts
import { defineConfig, devices } from "@playwright/experimental-ct-react";
import react from "@vitejs/plugin-react";

export default defineConfig({
  testDir: "./src/app/_components",
  snapshotDir: "./__snapshots__",
  timeout: 10 * 1000,
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: "html",
  use: {
    trace: "on-first-retry",
    ctPort: 3100,
    ctViteConfig: {
      plugins: [react()],
    },
  },
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
    {
      name: "firefox",
      use: { ...devices["Desktop Firefox"] },
    },
    {
      name: "webkit",
      use: { ...devices["Desktop Safari"] },
    },
  ],
});
```

**Components file, `components.tsx`**

```tsx
import { Children } from "react";

export const OneChild: React.FC<{
  children: React.ReactElement;
}> = ({ children }) => {
  console.log("OneChild component was given children which stringify as", JSON.stringify(children, null, 4));
  Children.only(children);
  return children;
};

export const OtherComponent: React.FC = () => <p>othercomponent</p>;
```

**Test file**

```tsx
import { test, expect } from "@playwright/experimental-ct-react";

import { OneChild, OtherComponent } from "./components";

test("can pass an HTML element to OneChild", async ({ mount }) => {
  const jsx = <OneChild><p>child</p></OneChild>;
  console.log("Playwright says jsx being passed stringifies to", JSON.stringify(jsx, null, 4));
  const component = await mount(jsx);
  await expect(component).toHaveText("child");
});

test("can pass another component to OneChild", async ({ mount }) => {
  const jsx = <OneChild><OtherComponent /></OneChild>;
  console.log("Playwright says jsx being passed stringifies to", JSON.stringify(jsx, null, 4));
  const component = await mount(jsx);
  await expect(component).toHaveText("othercomponent");
});
```

**Steps**
- Run the tests

**Expected**

- A paragraph is rendered (with "child" in the first case, with "othercomponent" in the second case)
- No console error
- Tests pass
- No errors

**Actual**

- Nothing is rendered
- Tests time out while waiting for the expected text
- Tests emit a console error "React.Children.only expected to receive a single React element child." even though only one child *is* being passed.

In the first case (passing a literal paragraph tag), I get these logs:

```
Playwright says jsx being passed stringifies to {
    "kind": "jsx",
    "type": "_home_bjn_clients_kor_control_loca_loca_nextjs_src_app__components_category_pill_components_tsx_OneChild",
    "props": {},
    "children": [
        {
            "kind": "jsx",
            "type": "p",
            "props": {},
            "children": [
                "child"
            ]
        }
    ]
}
OneChild component was given children which stringify as [
    {
        "type": "p",
        "key": null,
        "ref": null,
        "props": {
            "children": [
                "child"
            ]
        },
        "_owner": null
    }
]
```

In the second case (passing an imported component), I get these logs:

```
Playwright says jsx being passed stringifies to {
    "kind": "jsx",
    "type": "_long_path_ending_with_components_tsx_OneChild",
    "props": {},
    "children": [
        {
            "kind": "jsx",
            "type": "_long_path_ending_with_components_tsx_OtherComponent",
            "props": {},
            "children": []
        }
    ]
}
OneChild component was given children which stringify as [
    {
        "key": null,
        "ref": null,
        "props": {
            "children": []
        },
        "_owner": null
    }
]
```

That final log seems particularly broken -- there's no info there saying which component was meant to be rendered as the child.

**Comment by pavelfeldman** [comment]
Looks unrelated to the properties issue - we don't seem to respect React's contract on passing the _only_ child as a value instead of the array. @sand4rt just in case you are interested in fixing it!

**Comment by tom2drum** [comment]
Hi @pavelfeldman! I'm currently working on updating Playwright in my project from v1.35.1 to v1.40.1. I've encountered an issue with React components that have an optional `children` prop. When I don't provide this prop in my Playwright test, the console log outputs an empty array instead of the expected `undefined` value.

Is this behavior connected to the mentioned bug? Should I open a separate issue?

**Comment by pavelfeldman** [comment]
> Is this behavior connected to the mentioned bug? Should I open a separate issue?

Always safe to file a new issue with a repro so that we could provide a test with the fix.
