### ISSUE TITLE
[Feature] Given a trace file should be able to convert it to a .spec.[jt]s file along with a .har file with the test using routeFromHAR function

### ISSUE THREAD

**Issue by bcowgill** [microsoft/playwright#28416]
### Summary: 

1. Need a playwright command that converts a recorded trace.zip into a .spec.js/ts file and a .har file the .spec. would be set up to use routeFromHAR before running the user recorded tests.
2. Alternatively, in playwright inspector or the associated browser need to be able to save the .har file from that session and have routeFromHAR added to the generated test.

### Motivation
I've been evaluating Playwright to see if it can help to speed up developer integration testing and testers recording accurate bugs and expectations. We work in different release environments and it is a slow process to set up the back end database for a specific journey.

### Purpose
We would like to be able to have the testers use codegen to create a script demonstrating the bug in a test environment.  They can also provide assertions to specify the expected behaviour. At the end of codegen if they could also save the har file for that bug it would be perfect.

Failing that, they then use the trace function to re-run their script which captures a complete record of the bug but I tried extracting the network files from a trace zip and there's no usable har file therein.

Additionally, they can only re-run if the DB state is still good (i.e. account/policy is in the same state after the test).  Otherwise you need to set up two accounts/policies in the same state to do the test and change the test script to use the second policy on the second run)

Another alternative is to use the har recording facility but the tester will have to run through and record the har data first, and then do exactly the same things again when using codegen. This is error prone and suffers the same problem just above by burning the policy the first time.  So the second time the APi requests will be for different policy ID's and would require changing the test code or the har data.

A third option though of is to first record the test with codegen, then add in a routeFromHAR call with update true.  Then run the test normally or generate a trace again.  The routeFromHAR update should generate a har for us from the test, again provided we haven't burned the policy in the database.  But in this case just changing the test to the new policy number before running the generated test should be a simple matter.

Any help or suggestions would be greatly appreciated.

**Comment by pavelfeldman** [comment]
You feature makes sense, but we leave it to the third parties to implement.
