### ISSUE TITLE
[Feature] Add button to update old snapshot with new snapshot

### ISSUE THREAD

**Issue by hai5nguy** [microsoft/playwright#28415]
When doing visual regression testing in UI mode, it would be nice if there's a button to update the snapshot.

Workflow would be as follow:

1. Run `npx playwright test --ui`
2. Click Run all
3. Find all failing visual regression tests, let's assume there's many that failed.
4. Check attachments for each tests.
5. If the actual is correct, but doesn't match the expected, then there should be a button to use the actual as the new expected/master screenshot.

**Comment by dimkin-eu** [comment]
i think this is kinda related to https://github.com/microsoft/playwright/issues/24310

**Comment by stuymedova** [comment]
Hi, @mxschmitt does the tag mean that this issue is being worked on and is currently scheduled to be released in the next release version? It is very much wanted and needed!

**Comment by zinaelnahel89** [comment]
Any updates concerning this ?

**Comment by yury-s** [comment]
We decided to postpone this until we have a more coherent story for VRT. Folding into https://github.com/microsoft/playwright/issues/24310
