### ISSUE TITLE
[Feature] - share data / dynamic variables between tests

### ISSUE THREAD

**Issue by Romarionijim** [microsoft/playwright#28420]
Hello,

I was going through the documentation and I did not find a related subject to this issue or maybe I'm missing something so I would appreciate if you could point me to the correct place in the documentation.

i'm writing API tests, I'm creating a resource with an id that is generated via faker js library, instead of hard coding the id.
I have another test that wants to update the recourse that has this id that was generated by faker, so what I did is created a global variable, and re-assigned the variable to the id of the response after creating the resourse.

I need to use that variable with the same ID in a different test, the problem is I don't see a way to do that since if I use the same variable name it tells me that it is undefined although I am running the tests in serial mode.

is there a way to share data between tests? 

my code:

test.describe.serial('CRUD API tests for the Pet Store API', async () => {
    let petStoreCrudActions: PetStoreCrudActions;
    let petId: number = 10;
    let createdPedtId: number | undefined

    test.beforeEach(async ({ request }) => {
        petStoreCrudActions = new PetStoreCrudActions(request)
    })

    test('create a new pet @PET_STORE', async () => {
        await test.step('create a new pet via post request', async () => {
            let petData = {
                id: Randomizer.getRandomLongNumber(),
                category: {
                    id: Randomizer.getRandomLongNumber(),
                    name: Randomizer.getRandomName()
                },
                name: Randomizer.getDogNameBreed(),
                photoUrls: ['https://ibb.co/wLWCrSX'],
                tags: [
                    {
                        id: Randomizer.getRandomLongNumber(),
                        name: Randomizer.getRandomName(),
                    }
                ],
                status: 'available'
            }
            let response = await petStoreCrudActions.createNewPet(petData)
            let responseBody: Ipet = await response?.json();
            expect(response?.status()).toBe(StatusCode.OK);
            expect(responseBody).toEqual(petData);
            expect(response?.statusText()).toBe('OK');
            createdPedtId = responseBody.id
        })
    })

    test('validate the pet existance', async () => {
        await test.step('validate the pet that was created from previous test now exists', async () => {
            let response = await petStoreCrudActions.getPet(createdPedtId)
            let responseBody: Ipet = await response?.json();
            expect(response).toBeTruthy()
            expect(response?.status()).toBe(StatusCode.OK)
            expect(responseBody.id).toEqual(createdPedtId)
            expect(responseBody.name).toEqual('Shiloh Shepherd')
        })
    })

    as you can see i'm trying to use the createdPetId from the first test in the second test but this results in undefined,  if there is a better way to do. it, I would. appreciate if you could point me to the solution,  thanks!

**Comment by Romarionijim** [comment]
@pavelfeldman it does not work like that when using something like faker though, faker generates data on the fly in the test, this means that the state of the generated data is only saved for the same test only, for example: if im generating a fake name, and the generated name for that test in the current process is "Sami",  and i store that name in a variable, that name will only remain the same (Sami) in the same test,  if I have other tests and use the same variable it will be undefined or generate another new name, it is not a constant data that I have in a ready file that I can call, it will be very helpful if I can take that variable and share it between other tests in the same file at least.

**Comment by pavelfeldman** [comment]
It looks like you are looking for something like [fixtures](https://playwright.dev/docs/test-fixtures) that are defined for a test and can be used to generate names. Overall, among fixtures, access to filesystem, `testInfo.outputPath`, etc, there are a lot of way to achieve what you are requesting.

**Comment by alexkuc** [comment]
@pavelfeldman What about using scoped-based fixtures? It seems it would preserve the value of the fixture between test runs as long as the we share data between tests and not projects, right?
