### ISSUE TITLE
[Feature] Ability to chain assertions

### ISSUE THREAD

**Issue by rsh-ovo** [microsoft/playwright#28436]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

Currently there doesn't appear to be a way to chain assertions. It's a common use case to do multiple checks on an element.

// check that locator contains text and has a certain attribute

The only way to do this currently is to do separate checks
```
const locator = await page.locator('#locator')
expect(locator).toHaveText('This is a test')
expect(locator).toHaveAttribute('type', 'text');
```

It would be  nice to chain these together as 

`expect(locator).toHaveText('This is a test').and.toHaveAttribute('type', 'text');`

This does open up the complexity of implicit waits to apply for each assertion but in most cases could all assertions must be resolved within given/default timeout.

**Comment by pavelfeldman** [comment]
We prefer regular JavaScript / TypeScript constructs.

**Comment by rsh-ovo** [comment]
@pavelfeldman Would you mind elaborating what you mean here? There is already a `.not` operator similar to this and another `and` `or` operators for locators.

```
expect(locator).not.toHaveText('This is a test')
page.getByRole('button').and(page.getByTitle('Subscribe'));
await expect(newEmail.or(dialog)).toBeVisible();
```
