### ISSUE TITLE
[QUESTION] sometimes getting message -Error: Test ended. Browser logs: - in test.afterEach

### ISSUE THREAD

**Issue by mikicymulate** [microsoft/playwright#28432]
playwright sometimes getting message -Error: Test ended. Browser logs: - in test.afterEach .
Is there a reason why?

Playwright Version: "@playwright/test": "1.40.0" 
Google Chrome : Version 119.0.6045.160 
Browser: Operating System: [Windows 11]

`Error: Test ended. Browser logs:

C:\Program Files\Google\Chrome\Application\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --user-data-dir=C:\Users\XXX\AppData\Local\Temp\playwright_chromiumdev_profile-lPctmM --remote-debugging-pipe --no-startup-window pid=6408`

![image](https://github.com/microsoft/playwright/assets/106581694/14f0619e-e45d-4511-987f-591a49cf35e2)

**Comment by Xotabu4** [comment]
It would be only guessing, without looking your test code and post/pre hooks...

**Comment by pavelfeldman** [comment]
You are probably doing something after the test has ended (some event handler does something asynchronously). But we would need exact code to be able to repro.

**Comment by mikicymulate** [comment]
@pavelfeldman 
I only add winston log if the test fail .
and in this test case the test steps passes and it is fail on the after hook with no reason .

![image](https://github.com/microsoft/playwright/assets/106581694/f151073d-340a-40cf-bfd4-86b51ae91ae6)

**Comment by dgozman** [comment]
@mikicymulate Unfortunately, this screenshot does not really help us to reproduce the issue. We have to reproduce the issue locally to be able to debug it. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
