### ISSUE TITLE
[Feature] routeFromHAR header Access-Control-Allow-Origin should be configurable

### ISSUE THREAD

**Issue by bcowgill** [microsoft/playwright#28447]
routeFromHAR header Access-Control-Allow-Origin should be configurable

Let us know what functionality you'd like to see in Playwright and what your use case is.

Our testers can record a har file of a bug in our testing environments with
npx playwright open --save-har
Our developers would like to play that back in their local app but Access-Control-Allow-Origin headers all refer to the test environment hostname and need to refer to the local hostname to work properly.

In playwright we could do something like:

routeFromHAR(... {
   replayOrigin: config.use.baseUrl, // from the playwright config
})

so that when the har file finds the matching response it replaces the offending header with the local host.
A more general solution would allow a callback function to access the headers before they are returned to the browser and make any changes needed.

Do you think others might benefit from this as well?

Any developer would love to be able to take a network capture from any testing environment and replay it locally to debug with a little effort as possible.

Please suggest any alternative features of Playwright which might accomplish this as it's quite new to me.

**Comment by bcowgill** [comment]
Hmmmj, just saw this comment on another thread

 https://github.com/microsoft/playwright/issues/21405#issuecomment-1741979612
where before sending the url to routeFromHAR they munge the URL value to remove datestamps.
is there a similar existing hook where we could modify the headers before returning them to the browser?

**Comment by pavelfeldman** [comment]
The HAR we generate is not suitable for replay and making it so falls outside of the scope for Playwright. It looks like you are using Playwright for non-testing automation scenario.
