### ISSUE TITLE
[BUG] It is possible to start multiple simultaneous trace chunks via tracing.startChunk(), but if either tracing.stopChunk() or tracing.stop() are called, only the latest chunk is saved and others are lost

### ISSUE THREAD

**Issue by ericcjobes** [microsoft/playwright#28442]
### System info
- Playwright Version: 1.39.0
- Operating System: tested on macOS 14.1.1, but likely repros on all
- Browser: tested on Chrome but likely repros on all
- Other info:

I'm trying to understand a bit better how I can generate multiple trace files for various parts of my test.

I understand that the general workflow is
```typescript
1    await page.context().tracing.start();
2    // do some stuff to prepare for subject under test
3    await page.context().tracing.startChunk();
4    // perform actions to validate subject under test
5    await page.context().tracing.stopChunk();
6    
```

What I find interesting about this snippet is that it doesn't require `tracing.stop()`. In fact, if you add `await page.context().tracing.stop();` to line 6, you'll receive  `Error: Must start tracing before stopping`.

This leads me to the conclusion that `tracing.stopChunk()` and `tracing.stop()` stop all active traces or chunks, but only the most recently started trace or trace chunk is saved. The test code snippet below validates this idea. Is this correct?

Ideally, tracing `start()`/`stop() `and `startChunk()`/`stopChunk()` would behave like a stack, allowing the test writer to have fine-grained control of when traces start and stop, and what actions they capture:
```typescript
1    await page.context().tracing.start(); // ideally starts a trace file that will capture everything until tracing.stop() is called
2    // do some stuff to prepare for subject under test
3    await page.context().tracing.startChunk(); // starts a chunk for subject under test
4    // perform actions to validate subject under test
5    await page.context().tracing.stopChunk(); // stops the chunk for the subject under test
6    // do some test cleanup or any other actions
7    await page.context().tracing.stop(); // ideally stops the trace started on line 1
```

Should I stop thinking about traces as a stack, and start assuming that while any chunk can be started at any given time, you can only ever stop the most recent one? In other words,  should tests be written to only record one chunk at a time? 

Another suggestion I have is perhaps instead of a stack, when a chunk is started, a chunk could be uniquely identified by the test writer, so they can decide exactly when to stop which chunk, e.g. 
```typescript
1    await page.context().tracing.start();
2    await page.context().tracing.startChunk( { id: 1234 } );
3    await page.context().tracing.startChunk( { id: 4678 } );
4    await page.context().tracing.stopChunk( { id: 1234 } );
5    await page.context().tracing.stopChunk( { id: 4678 } );
```

If there's any other methods or workarounds to control multiple traces at once, please let me know :)

### Source code

- [✅] I provided exact source code that allows reproducing the issue locally.

**Config file**

```typescript
// playwright.config.ts
export default defineConfig({
  timeout: 360000,
  expect: {
    timeout: 30000,
  },
  fullyParallel: false,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* No retries for current iteration of CJV2 */
  retries: 0,

  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    actionTimeout: 0,
    trace: "on",
    video: "on",
    testIdAttribute: "data-tid",
  },
  globalSetup: "./path/to/global-setup",
  globalTeardown: "./path/to/global-teardown",
});

```

**Test file (self-contained)**

```typescript
import { test, expect, chromium } from "@playwright/test";
const cwd = process.cwd();

test("testing playwright tracing", async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();

  // start tracing, as this is required in order to start chunks
  await context.tracing.start({
    name: "full trace",
    screenshots: true,
    snapshots: true,
  });

  const page = await context.newPage();
  await page.goto("https://playwright.dev");

  // start a chunk before going to docs
  await page.context().tracing.startChunk({
    title: "1st chunk: going to docs",
  });
  console.log("started chunk 1: going to docs");
  await page.getByRole("link", { name: "Docs" }).click();

  // start a new chunk before going to api AND without stopping the first chunk
  await page.context().tracing.startChunk({
    title: "2nd chunk: going to api",
  });
  console.log("started chunk 2");
  await page.getByRole("link", { name: "API", exact: true }).click();

  // stop a chunk. The result will be a trace for only the second chunk (going to api), not the first. We can validate this via the `name` property in the trace.
  await page.context().tracing.stopChunk({ path: `${cwd}/1st-chunk-stop.zip` });
  console.log("stopped chunk twice but we only have the second chunk");

  // here, either of the following will throw an error stating that tracing must be started before stopping it, even though we've "balanced" the startChunk()/stopChunk() and start()/stop() calls
  await page.context().tracing.stopChunk({ path: `${cwd}/2nd-chunk-stop.zip` });
  await page.context().tracing.stop({ path: `${cwd}/full-trace.zip` });
});
```

**Steps**
- [Run the test]. I use vscode's playwright runner extension

**Expected**

if tests can be written to start multiple chunks at the same time, then there should be capability to control which chunk is stopped, such as by treating trace chunks as a stack or uniquely identifying them when they are started and stopped.

**Actual**

- No error is thrown if multiple simultaneous trace chunks are started. However, test writer can only call `stopChunk()` once without starting another chunk, even if multiple chunks were started and stopChunk() was only called once.
- When `stopChunk()` or `stop()` is called after starting multiple simultaneous chunks, only the most recently started chunk is saved, and all tracing is stopped.

**Comment by ericcjobes** [comment]
Got it, thank you for the reply Pavel!
It would be awesome to see this info `Chunks are always serial. If you start one chunk and then start another chunk, the first one will be discarded and the new one will start recording` to the documentation here:
https://playwright.dev/docs/api/class-tracing#tracing-start-chunk

**Comment by pavelfeldman** [comment]
Please feel free to send a PR, note that you'll need to re-generate respective d.ts file via running the build.
