### ISSUE TITLE
[Feature] -  click to stop test run when using vscode playwright extension

### ISSUE THREAD

**Issue by Romarionijim** [microsoft/playwright#28448]
hello, when using the vscode playwright extension to run tests, sometimes when we run into an infinite loop in our code and we have clicked already on the play button of the extension, there is no way to stop it and it could be quit frustrating, unlike in debug, i have a stop button there in debug mode,  I would appreciate if you could add the same to the test runner to stop the test run manually.
thanks.

![image](https://github.com/microsoft/playwright/assets/75387323/0641ae6b-93d5-4545-8f98-6542b3d975cb)

**Comment by pavelfeldman** [comment]
There is a stop button in the Test explorer panel toolbar.

**Comment by Romarionijim** [comment]
@pavelfeldman I don't see any stop button, could you please show me?

**Comment by Romarionijim** [comment]
I would suggest to make it more user friendly in the future @pavelfeldman
