### ISSUE TITLE
[BUG] wrong line numbers in VSCode extension

### ISSUE THREAD

**Issue by gajus** [microsoft/playwright#28454]
### System info
- Playwright Version: 1.40.1
- Operating System: macOS 13.2
- Browser: All
- Other info: N/A
- VSCode Version: 1.84.2
- Playwright Extension version: v1.0.19

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

Private repo.

**Config file**

```js
const config: PlaywrightTestConfig = {};

export default config;
```

**Test file (self-contained)**

Any test.

**Expected**

Expect test actions to align with tests themselves.

**Actual**

As you can see, test actions (those green flags) are not aligned with the `test` function calls.

<img width="2056" alt="Screenshot 2023-12-01 at 11 22 58 AM" src="https://github.com/microsoft/playwright/assets/973543/6fe13f74-1d6c-4208-9d76-92b116ed1d61">

This is not specific to a particular test file. Every test file is affected.

**Additional Context**

* I don't know if related, but we use `moduleResultion` `NodeNext` in our `tsconfig.json`.

**Comment by sheldonj** [comment]
### THIS WORKS:

run the application using Node 21.2.0. 
Then switch node versions to Node 20.0.0
Open VSCode using the command line `code  .`
 
Then debug a test in a spec file using the extension you can the test will work. 
You will also notice that the little green arrow lines up correctly with the tests in the spec file.

the extension will generate this command:
```
/Users/james/.nvm/versions/node/v20.0.0/bin/node ./../../node_modules/.pnpm/@playwright+test@1.40.1/node_modules/@playwright/test/cli.js test -c playwright.config.ts /Users/james/Developer/contra/gaia/apps/contra-web-app/tests/e2e/search-independents/filters/filter-roles\.spec\.ts:46 --headed --repeat-each 1 --retries 0 --timeout 0 --workers 1
```

### THIS DOESN'T WORK

run the application using Node 21.2.0. 
leave the node version to 21.2.0
Open VSCode using the command line `code  .`

Attempt to debug a single test in a spec file.

Playwright will execute this command:

```
/Users/james/.nvm/versions/node/v21.2.0/bin/node ./../../node_modules/.pnpm/@playwright+test@1.40.1/node_modules/@playwright/test/cli.js test -c playwright.config.ts /Users/james/Developer/contra/gaia/apps/contra-web-app/tests/e2e/search-independents/filters/filter-roles\.spec\.ts:45 --headed --repeat-each 1 --retries 0 --timeout 0 --workers 1
```

Will result in a `Error: No tests found`


### ISSUE

With 21.2.0 you can see that playwright is trying to debug a test that exists on line 45 of the spec file. But no test is defined on that line. You can even see the green arrows are misaligned. 

![Screenshot 2023-12-01 at 2 42 27 PM](https://github.com/microsoft/playwright/assets/1539196/6af7cef8-2288-489e-8fa8-1139b08d2f0f)

**Comment by schlenks** [comment]
@pavelfeldman with the additional information shared, does this help? Can this issue be re-opened or does a new issue need to be created?

**Comment by mxschmitt** [comment]
Please re-file, thanks! We usually don’t monitor closed issues
