### ISSUE TITLE
[BUG] C# Trace View Documentation Incorrect

### ISSUE THREAD

**Issue by thatstatsguy** [microsoft/playwright#28473]
### System info
- Playwright Version: [v1.40.0]
- Operating System: Windows 10
- Browser: All
- Other info: PR Available #28472

### Source code

Source code [here](https://playwright.dev/dotnet/docs/trace-viewer-intro#recording-a-trace) is currently incorrect.

**Expected**

The code should compile from the docs

**Actual**

It doesn't compile

**Comment by mxschmitt** [comment]
Fixed, thanks!
