### ISSUE TITLE
[Question] Nested Elements

### ISSUE THREAD

**Issue by svitlanaduman** [microsoft/playwright#28478]
Hi,

this issue is coming from the [Question] Nested Locator #28353

There you can find an example of a DOM in the feed above.

My question is how to find out what ids are in the group with the id pd-per-info-lbl?

so the result should be like a list of locators with ids pd-id-lbl, pd-id-val, pd-name-lbl, etc.

Thank you

**Comment by dgozman** [comment]
@svitlanaduman We recommend using [Test Generator](https://playwright.dev/docs/codegen) to generate a locator for you.

Unfortunately, if you do not provide a full repro that we can run locally, we won't be able to help you. Repro should be self-contained - either a single script or a small repository that we can clone and run a test within.

**Comment by dgozman** [comment]
@svitlanaduman Perhaps something like this?

```ts
await page.locator('#outer-id #inner-id').click();
```

Overall, I'd recommend reading the documentation, for example [this section](https://playwright.dev/docs/locators#matching-inside-a-locator) and the the whole Locators guide, to get familiar with Playwright locators can do.

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
