### ISSUE TITLE
[Feature] Global level delay between all actions

### ISSUE THREAD

**Issue by tubalagopal** [microsoft/playwright#28477]
After completion of an action, before executing the next one, add a configurable delay. This pause should apply universally, creating a smoother and more natural interaction with the browser, effectively minimising glitches without the necessity of specific timeouts.
Lets say there is a page load and a button click in a test. After the page load, a pause should apply before the button click. If there is an action after the button click, the pause should apply before the execution of the subsequent action.

**Comment by Xotabu4** [comment]
You can also use the slowMo option to slow down execution (by N milliseconds per operation)

**Comment by dgozman** [comment]
@tubalagopal We do not consider adding delay as a good practice for testing. When you run your test on CI, any timeouts can lead to flaky tests. Playwright already [auto-waits](https://playwright.dev/docs/actionability) for actions that need it, so adding artificial timeouts is unnecessary. If you have a scenario where auto-waiting does not work, please file an issue by filling in the "Bug Report" template and provide a repro that we can run locally.

**Comment by jhogervorst** [comment]
> When you run your test on CI, any timeouts can lead to flaky tests.

@dgozman Wouldn't this mean that the test itself is not resilient enough?

I would like to run my tests two times on CI — once without timeouts, and once with a timeout before/after each action. That way, we are sure that our tests are resilient, i.e., they don't depend on the fact that they are being executed very fast.
