### ISSUE TITLE
[BUG] import { test as baseTest } from '@playwright/test'; throwing error

### ISSUE THREAD

**Issue by akshayp7** [microsoft/playwright#28481]
### System info
- Playwright Version: [v1.40.1]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:
![Untitled](https://github.com/microsoft/playwright/assets/78036666/92ee35ea-b7f9-47cb-8a62-226e115fe3b7)

### Source code

import { test as baseTest } from '@playwright/test';

**Expected**

Should throw no errors

**Actual**

Throws "Module '"@playwright/test"' has no exported member 'test'. Did you mean to use 'import test from "@playwright/test"' instead?"
error

**Comment by dgozman** [comment]
@akshayp7 We need more information to act on this issue. Could you please provide a full repro that we can run locally? A single line that you provided works for me.

**Comment by akshayp7** [comment]
@dgozman thank you for responding.  This is my repo link 
https://github.com/akshayp7/playwright-typescript-playwright-test

**Comment by dgozman** [comment]
@akshayp7 Thank you for the repro. I checked it out, and I don't get the same error. Perhaps your VSCode is not picking up types? I'd recommend removing `node_modules` and rerunning `npm install`, and then restarting VSCode.

**Comment by akshayp7** [comment]
@dgozman : You are absolutely on point. Your solution worked like charm. Thanks a lot for resolving my query.
