### ISSUE TITLE
[BUG] Video Not Recording (Mac/Chromium)

### ISSUE THREAD

**Issue by jwalkerinterpres** [microsoft/playwright#28486]
### System info
- Playwright Version: **1.40.1** (`"@playwright/test": "^1.40.1"`)
- Operating System: **Mac OS 14.1.2**
- Browser: **Chromium**

### Source code

I just started using Playwright, so my test is extremely simple.  It's literally just:

    test('can login', async ({ page }) => {
        await page.goto('http://localhost:8080');
    });

... so I don't think the test code is the problem.  Also, I had an expanded version of this test, which ran successfully ... but it had the same problem (no video).  The problem occurs with both that "real" test and this super-basic one.

Also here is my `playwright.config.js` (NOTE: This is just stock auto-generated config, except for the `video` part at the end) :

```
defineConfig({
  testDir: './e2e',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    // trace: 'on-first-retry',
    trace: 'on',

    // Record videos of every test
    video: 'on'
  },
```

**Steps**
- Turn on videos in config file
- Run the (one-line) test (in interactive or headless mode)

**Expected**
- Expect to see the video

**Actual** 
- You **do** see other artifacts, eg. `playwright-report/index.html` and `test-results/login.spec.tsx-can-login-local-chromium/trace.zip` ...
- ... but you don't see any generated video files. (also, there is no command-line output; certainly no errors that explain things)

I've looked for other tickets or documentation, but couldn't find any (eg. there is no information on https://playwright.dev/docs/videos which suggests what could be wrong), so I have no idea how to address this.  Any help whatsoever would be appreciated.

Final note: since I'm on a Mac, I assumed this was a permissions issue. So, I explicitly granted screen sharing permissions to the Chromium that Playwright installed (in Library/Caches/etc.).  That didn't help, so then I ran Chromium manually, went to Google Meet, shared my screen, and enabled every permission along the way.

Screen sharing through Chromium _does_ work ... but the videos aren't being generated, for some other reason.

P.S. I also tried running the test through Firefox.  It generated a `login.spec.tsx-can-login-local-firefox/trace.zip` file ... but no video.  This issue appears to be browser-independent.

P.P.S I read online that I could do:

    page.context()?.browser().recordVideo();

but the `browser` I get has no `recordVideo` property, so that must be out of date.  Similarly, I read that I could do:

     console.log(await page.video());

but that logs `null`.  I'm not sure if that's outdated info, or some sign of my video being broken.

**Comment by dgozman** [comment]
@jwalkerinterpres Could you please share the full repro? Could it be that you are launching the browser yourself, or maybe opening a page manually? There is a known issue #14813 that video is only recorder in the built-in `page` provided by the test runner.

**Comment by jwalkerinterpres** [comment]
I've basically provided full repro already, but to reiterate ...

1.  Start with a brand new setup.
2. Turn videos on in the config (I provided my file, but it's a one line difference from the stock one)
3. Create a test that goes to a URL; here's a simple one (or use my original):
```
test('dummy test', async ({ page }) => {
  await page.goto('http://www.google.com');
  await page.locator('textarea[name="q"]').click();
  expect(await page.locator('button')).toBeDefined();
});
```
4. At the command line run `npx playwright test`
5.  See the following output (NOTE: no errors are shown):
```
$ npx playwright test

Running 3 tests using 3 workers
  3 passed (3.8s)

To open last HTML report run:

  npx playwright show-report
```
6. There is no video file:
```
$ ls test-results 
$
```

Again, I'm sure there's _something_ unique to my environment causing this; videos are obviously working for other people.  But with no errors in the terminal, and no suggestions in the docs, I'm not sure what else to report.

**Comment by dgozman** [comment]
@jwalkerinterpres Unfortunately, I was not able to reproduce on MacOS 13.6. Here are my steps:

```sh
mkdir temp && cd temp
npm init playwright@latest
```

Replace `tests/example.spec.ts` with
```ts
test('dummy test', async ({ page }) => {
    await page.goto('http://www.google.com');
    await page.locator('textarea[name="q"]').click();
    expect(await page.locator('button')).toBeDefined();
});
```

Add `video: 'on'` to `playwright.config.ts`.

```sh
$ npx playwright test
Running 3 tests using 3 workers
  3 passed (4.2s)

$ find test-results -name "*.webm" 
test-results/example-dummy-test-webkit/video.webm
test-results/example-dummy-test-firefox/video.webm
test-results/example-dummy-test-chromium/video.webm
```

I am not really sure what's up with your setup. Try adding the following line to your test just to see that your config is read correctly. Other than that, we need to be able to repro the issue.
```ts
test('dummy test', async ({ page, video }) => {
  console.log(video);
});
```

**Comment by jwalkerinterpres** [comment]
I did:

    console.log(video, 'video');

and saw:

    off video

so ... apparently my video is "off"?  But again, my playwright.config.ts file has:

```
  use: {
    screenshot: 'only-on-failure',
    trace: 'on',
    video: 'on'
  },
```

Any thoughts on what I (or my environment) could be doing to change video to `"off"` in-between me turning it on in the config and me running the test?

**Comment by jwalkerinterpres** [comment]
Nevermind, I found the problem: a duplicate config file.  So sorry to have wasted your time, but video is now working perfectly!

Thanks again for your help, and all the great work on Playwright!
