### ISSUE TITLE
[Feature] Control private window (--private-window) in Firefox

### ISSUE THREAD

**Issue by Kuwoshii** [microsoft/playwright#28497]
Hello, I was trying to spawn a private window using the fixfox nightly that comes out of the box when installing playwirght.

* This is a code snippet
```python
import asyncio
from playwright.async_api import async_playwright

args = [
    "--private-window"
]

async def launch_browser_instance():
    async with async_playwright() as p:
        main_browser = await p.firefox.launch(
            args=args,
            headless=False
        )

        await asyncio.sleep(500000)


async def main():
    await launch_browser_instance()


asyncio.get_event_loop().run_until_complete(main())
```

* Screenshot of what you should see:
![image](https://github.com/microsoft/playwright-python/assets/102769991/32d798e0-d076-49b9-b30c-f18ba06bc15f)

It starts by spawning a private window but im unable to control it (as in creating pages, goto, etc.), is there a way or will be a feature in the future to being able to specifically send commands to that window?

**Comment by dgozman** [comment]
@Kuwoshii Unfortunately, controlling the private window falls out of scope of Playwright.
