### ISSUE TITLE
[BUG] Route fulfill with some status codes does not fulfill

### ISSUE THREAD

**Issue by dil-bherendi** [microsoft/playwright#28490]
When handling route like this, some status code (430) does not work in chromium and webkit, status stays -1 in network tab:
```ts
await page.route("**/test429.json", async (route) => {
    await route.fulfill({
      status: 429,
    });
  });
```

### System info
- Playwright Version: [v1.40]
- Operating System: [Windows 11]
- Browser: [Chromium, WebKit]
- Other info: Works in Firefox

### Source code

```ts
import { expect, test } from "@playwright/test";

test("get started link", async ({ page, context }) => {
  await page.setContent(`
  <script>
    async function onClick429() {
      const res = await fetch('http://example.com/test429.json');
      console.log(res);
    }
    async function onClick430() {
      const res = await fetch('http://example.com/test430.json');
      console.log(res);
    }
  </script>
  <button data-testid="429" onclick="onClick429()">Click me</button>
  <button data-testid="430" onclick="onClick430()">Click me</button>
  <div></div>
`);

  await page.route("**/test429.json", async (route) => {
    await route.fulfill({
      status: 429,
    });
  });

  await page.route("**/test430.json", async (route) => {
    await route.fulfill({
      status: 430,
    });
  });

  let hasResult = new Set();

  page.on("request", (request) => {
    console.log("request", request.url());
  });

  page.on("response", (response) => {
    console.log("response", response.url());
    hasResult.add(response.url());
  });

  page.on("requestfailed", (request) => {
    console.log("requestfailed", request.url());
    hasResult.add(request.url());
  });

  page.on("requestfinished", (request) => {
    console.log("requestfinished", request.url());
    hasResult.add(request.url());
  });

  await page.getByTestId("429").click();
  await page.getByTestId("430").click();

  await page.waitForTimeout(1000);

  expect(hasResult.size).toBe(2);
});
```

**Steps**
- [Run the test]
- [See network tab and/or console]

**Expected**

***Firefox*** shows on console that the requests are made and received by more handlers.

request http://example.com/test429.json
response http://example.com/test429.json
requestfinished http://example.com/test429.json
JSHandle@object
request http://example.com/test430.json
JSHandle@object
response http://example.com/test430.json
requestfinished http://example.com/test430.json

**Actual**

Chromium and webkit does not finish or fail status code 430 (429 works, but not the same way).

***Chromium***

request http://example.com/test429.json
Failed to load resource: the server responded with a status of 429 (Too Many Requests)
response http://example.com/test429.json
Response
requestfailed http://example.com/test429.json
request http://example.com/test430.json

***Webkit***

request http://example.com/test429.json
Failed to load resource: the server responded with a status of 429 (Too Many Requests)
response http://example.com/test429.json
requestfinished http://example.com/test429.json
Response
request http://example.com/test430.json

**Comment by dgozman** [comment]
Turns out, Chromium does not allow the 430 status code. Unfortunately, Playwright swallows this error and does not report it, which we should fix.
