### ISSUE TITLE
[BUG] Firefox on linux adds "OS" text to input when pressing "Meta" key

### ISSUE THREAD

**Issue by liamdebeasi** [microsoft/playwright#28495]
### System info
- Playwright Version: v1.40.1
- Operating System: Ubuntu 22.04.3
- Browser: Firefox

Potentially related to https://github.com/microsoft/playwright/issues/9755

### Issue Overview

When pressing the "Meta" key on Firefox/Linux the "OS" string is added to the input. This does not happen on Firefox + macOS/Windows. I've only reproduced this on Linux + GitHub Actions. I'm not sure if this is caused by Playwright or Firefox. If this would be better reported to the Firefox, please let me know and I can do that instead.

### Source code

https://github.com/liamdebeasi/playwright-meta-repro

Test: https://github.com/liamdebeasi/playwright-meta-repro/blob/ee8866c61c8c0b1911b1892882adf30d6210e6d2/tests/example.spec.js#L4-L15

Test Run Example: https://github.com/liamdebeasi/playwright-meta-repro/actions/runs/7103647456/job/19336824001

**Expected**

I expect the "OS" text to not be added to the text input when pressing the "Meta" key on Firefox.

**Actual**

The "OS" text is added to the text input when pressing the "Meta" key on Firefox.

**Comment by aslushnikov** [comment]
@liamdebeasi thanks for reporting; this is indeed an issue on Playwright's side. Fix is being baked.

**Comment by liamdebeasi** [comment]
Thank you!
