### ISSUE TITLE
PlayWright is taking more time to generate the report (html) even though execution completed quicker. Its happening if we execute other than chromium browser.

### ISSUE THREAD

**Issue by ramakotireddye** [microsoft/playwright#28506]
### System info
- Playwright Version: [v1.40]
- Operating System: [Win10, Win11, etc.]
- Browser: [Other than Chromium]
- Other info:

I have executed a simple test that print Hello in console output. As we know, once give the command npx playwright test it starts the execution giving infor in terminal how many tests running and using workers and after completion of execution it shows how many tests passed and then it shows "To open last HTML report run: npx playwright show-report.
Here the issue is, if I choose the browser other than chromium for execution, script getting executed quicker whereas to generate the comment that I mentioned above ""To open last HTML report run: npx playwright show-report" is taking longer time and then completing it. The report shows the test case execution time 2.5s where as total time 35s. 

Its happening other than chromium browsers.

**Comment by dgozman** [comment]
@ramakotireddye Perhaps there is something slow with other browsers in your setup. We need more information to act on this issue. Could you please provide a repro that we can run locally?

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
