### ISSUE TITLE
[BUG] Missing CSS code coverage

### ISSUE THREAD

**Issue by edumserrano** [microsoft/playwright#28510]
### System info
- Playwright Version: [v1.40.1]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

### Source code

1) Clone the [playwright-adventures repo](https://github.com/edumserrano/playwright-adventures) repo.
2) Use your favourite shell to go to `./demos/code-coverage-with-monocart-reporter`.
3) Run `npm i` to install all required npm packages.
4) Run `npm run test` to run the playwright tests.
5) Run `npx monocart show-report tests/test-results/index.html` and browse to the global code coverage at `http://localhost:8090/coverage/index.html` and you should only see CSS code coverage for the `styles.css` file.

**Expected**

The CSS code coverage I get is for the Angular global styles which are added to the page as `<link rel="stylesheet" href="styles.css">` (see the green square on the image below). The CSS code coverage I also want to get is added to the page as `<style type="text/css">...</style>` (see the red square on the image below).

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/2b4f0a30-6df7-49ff-b7de-2a7f0bce8574)

**Actual**

I only get the global `styles.css` file. This is what I get:

![image](https://github.com/cenfun/monocart-reporter/assets/15857357/c647cb86-5680-46a6-b806-c0bb7ff55124)

I'm not getting CSS code coverage for the [src/app/app.component.css](https://github.com/edumserrano/playwright-adventures/blob/temp-1/demos/code-coverage-with-monocart-reporter/src/app/app.component.css) file.

### Further notes

1) If you want to run the app to inspect it you can do so by running `npm start` from the `./demos/code-coverage-with-monocart-reporter` folder.
2) I'm tracking the CSS code coverage using playwright's [startCSSCoverage](https://playwright.dev/docs/api/class-coverage#coverage-start-css-coverage) and [stopCSSCoverage](https://playwright.dev/docs/api/class-coverage#coverage-stop-css-coverage) function. These are being invoked through an automatic fixture defined at [app-fixtures.ts](https://github.com/edumserrano/playwright-adventures/blob/temp-1/demos/code-coverage-with-monocart-reporter/tests/_shared/app-fixtures.ts) and [v8-code-coverage.ts](https://github.com/edumserrano/playwright-adventures/blob/temp-1/demos/code-coverage-with-monocart-reporter/tests/_shared/fixtures/v8-code-coverage.ts).
3) When I debug the test to check what the `stopCSSCoverage` function returns this is what I'm getting:
![image](https://github.com/microsoft/playwright/assets/15857357/d99df301-ad46-4da9-b074-b7ed50deaa31)
Note that in the above image I was only collecting CSS code coverage, that's why it doesn't show any JS code coverage.
4) Looking at the documentation for the `stopCSSCoverage` function it says:
>
> Returns the array of coverage reports for all stylesheets
>
> **NOTE** CSS Coverage doesn't include dynamically injected style tags without sourceURLs.
>

Which I believe is what Angular does to the CSS, it generates style tags but I do believe there's a `sourceURL` for it right? As can be seen on the first image linked on this issue, the expanded style tag contains:
>
> /*# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsic3JjL2FwcC9hcHAuY29tcG9uZW50LmNzcyJdLAogICJzb3VyY2VzQ29udGVudCI6IFsiLnN1Y2Nlc3Mge1xyXG4gIGNvbG9yOiBncmVlbjtcclxufVxyXG4iXSwKICAibWFwcGluZ3MiOiAiO0FBQUEsQ0FBQztBQUNDLFNBQU87QUFDVDsiLAogICJuYW1lcyI6IFtdCn0K */
>

Which when decoded results in:
>
> {
>  "version": 3,
>  "sources": ["src/app/app.component.css"],
>  "sourcesContent": [".success {\r\n  color: green;\r\n}\r\n"],
>  "mappings": ";AAAA,CAAC;AACC,SAAO;AACT;",
>  "names": []
> }
>
 
 Which is why I'd expect this to be able to be tracked by the CSS code coverage functions but perhaps I'm missing something.

**Comment by edumserrano** [comment]
Hi @dgozman, does your comment mean that this scenario might be something you guys can provide support for? What are your thoughts?

**Comment by dgozman** [comment]
@edumserrano It is very unlikely this issue will be prioritized. CSS coverage is not the most used feature in Playwright, and it seems like you can work around this one by adding `/*# sourceURL=..... */` comment at the end of the file.

**Comment by edumserrano** [comment]
I apologise for my lack of knowledge but could you detail your workaround a bit more? Do you mean to say that everything would work fine if instead of `sourceMappingURL` the `style` tag had `sourceURL` ?

Are you suggesting I do that manually somehow after Angular builds the app? The [sourceMap configuration](https://angular.io/guide/workspace-config#source-map-configuration) is set on the `angular.json` and in the [demo app](https://github.com/edumserrano/playwright-adventures/blob/2264f8a9b91f3c7168e6a581549288d140b13c78/demos/code-coverage-with-monocart-reporter/angular.json#L47C17-L47C17) I linked to this issue it's set to `true`. Apart from this configuration I don't see anything that let's me apply the workaround you suggested.

I also tried searching for how to get  `sourceURL` instead of `sourceMappingURL` but couldn't find anything so perhaps I'm searching with incorrect terms.

**Comment by edumserrano** [comment]
Unfortunately I'm not expert enough to figure out a workaround that enables me to apply your suggestion or even to evaluate how feasible it  might be in my scenario with an Angular app. 

I guess I'll keep my finger's crossed for this item to eventually get on the backlog. Thank you @dgozman.

**Comment by cenfun** [comment]
@dgozman we hope `startCSSCoverage` supports `reportAnonymousScripts` option just like `startJSCoverage`
```
await coverage.startCSSCoverage({ reportAnonymousScripts: true }); // not supported yet
await coverage.startJSCoverage({ reportAnonymousScripts: true }); // It has been supported
```
I don't think that user can add `sourceURL` freely, because the style tags could be injected dynamically by the webpack `style-loader` and the CSS comments also could be removed by the `css-loader`.
What are your thoughts?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
