### ISSUE TITLE
[Feature][query] Want to convert the x-www-form-urlencoded into JSON format

### ISSUE THREAD

**Issue by vishalks921** [microsoft/playwright#28518]
We are executing the provided set of APIs that we want to automate but when we are putting the API urls and input parameters, the tests are not executed.

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.

**Comment by vishalks921** [comment]
Want to automate the Token generator API which is in the x-www-form-urlencoded.  writing the code into Playwright with javascript to using the code for token generation, but getting the errors.
