### ISSUE TITLE
Locator.click: Target Closed when trying to make multiple selections on a DevExtreme DropDown

### ISSUE THREAD

**Issue by BrendanSimms8898** [microsoft/playwright#28519]
### System info
- Playwright Version: [v1.40.1]
- Operating System: [Windows]
- Browser: [All]
- Other info:

### Source code

Playwright Test:

test.step("Select Manager and Engineer for Responsible, when R from the RACI options is highlighted, Select the A option from the RACI options and select Quality, Select the C option from the RACI options and select Production, Select the I option from the RACI options and select Warehouse", async () => {

            const Roles = ["Manager", "Engineer", "Quality", "Production", "Warehouse"]

            var run = 1;

            var SelectBar = await page.getByRole('combobox');
            
            var ListContainer = await page.locator('dx-scrollview-content')

            for (var Role of Roles) {
                var SelectBar = await page.getByRole('combobox');
                var RoleSearchBar = await page.getByRole('textbox', { name: 'Search', exact: true });
                var ResponsibleButton = await page.getByLabel('R', { exact: true });
                var AccountableButton = await page.getByLabel('A', { exact: true });
                var ConsultedButton = await page.getByLabel('C', { exact: true });
                var InformedButton = await page.getByLabel('I', { exact: true });

                if (run == 3) {
                    await AccountableButton.click();
                }

                if (run == 4) {
                    await ConsultedButton.click();
                }

                if (run == 5) {
                    await InformedButton.click();
                }

                await SelectBar.click();

                
                const RoleElement = await ListContainer.locator(".dx-item-content dx-list-item-content").filter( {hasText: Role});

                console.log(RoleElement)

                await RoleElement.click();

                run++;
            }

            await expect(SelectBar).toBeVisible();
        })

HTML from Chrome Inspect of Target:
![image](https://github.com/microsoft/playwright/assets/77291876/d8a1fd16-4a39-4477-8b27-08a116dc5e56)

I have attempted to introduce waitFor statements, makes no difference had done it outside a for loop, with a for loop and nothing makes a difference

I have also attempted to introduce timeouts this does not work either

**Steps**
- Run the Test
- Press the SelectBar to open the drop down menu
- Select a Role
- Repeat until it breaks generally on the second or third run

**Expected**

This will select 5 different Roles and assign them to Responsible, Accountable, Consulted and Informed respectively

**Actual**

The test successfully selects the first role and then crashes randomly on the next run on one of the three clicks

**Comment by mxschmitt** [comment]
We need a self-contained reproduction which we can run locally. Please re-file with attaching a test or repo which we can run locally. Thanks!
