### ISSUE TITLE
[BUG] Array.from map is not correctly evaluated in Webkit using playwright-webkit@1.40.1

### ISSUE THREAD

**Issue by ceisele-r** [microsoft/playwright#28520]
### System info
- Playwright Version: `playwright-webkit@1.40.1` from npm
- Operating System: Windows, Ubuntu
- Browser: Webkit
- Other info: I guess it's most likely an issue from Webkit and not the playwright-webkit wrapper but I am not sure. It worked in `playwright-webkit@1.39.0`

### Source code
See below.

**Steps**
- Execute the following code in the Browser console
```javascript
const r = (str, amount) => Array.from(Array(amount)).map(() => str).join('');
r('([a-f0-9]{2})', 3)
```
- Look at the result. Webkit emits an empty string as result whereas Chrome emits the actual string.

**Expected**
This evaluates to
`'([a-f0-9]{2})([a-f0-9]{2})([a-f0-9]{2})'`

**Actual**
Webkit evaluates this to
`""`
whereas Chrome evaluates this to
`'([a-f0-9]{2})([a-f0-9]{2})([a-f0-9]{2})'`

Actually, Webkit even evaluates this
```javascript
Array.from(Array(3)).map(x => "123").join('');
```
to `""`
whereas Chrome evaluates this correctly to `'123123123'`

**Comment by mxschmitt** [comment]
I was able to repro with this on `1.40` but not on `next`:

```ts
import { test, expect } from '@playwright/test';

test('should work', async ({ page, browserName }) => {
  await page.goto('https://playwright.dev/')
  console.log(browserName, await page.evaluate(() => {
    const r = (str, amount) => Array.from(Array(amount)).map(() => str).join('');
    return r('([a-f0-9]{2})', 3);
  }));
});
```
