### ISSUE TITLE
[BUG] page.evaluate fails to return element with Xpath

### ISSUE THREAD

**Issue by AutomationGuru** [microsoft/playwright#28521]
### System info
- Playwright Version: 1.35.1.
- Operating System: MacOS
- Browser: All
- Other info:

### Source code

Example code :

```
const playwright = require('playwright');

(async () => {
  const browser = await playwright.webkit.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://www.example.com/');

  const allElem = await page.evaluate(() => {
        document.evaluate("//h1", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue                  
    });
  console.log(allElem) // Fails to have the element tag
  await browser.close();
})();
```

[Please provide a self-contained example in a form of a snippet, archive or a repository.]

[Repro scenario can't be large or have external dependencies.]

**Steps**
Run the above code and one 

**Expected**

[Describe expected behavior]

Am trying to use page evaluate to run a JS that can get an element from DOM and i can run few video checks on it. For instance 
 `document.evaluate("//video", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.isMuted` Returns true or false and helps me assert the state of the player itself and also any errors on it

But with the current way to run JS using page evaluate this fails to return any element and am unable to get the tag of the element and use any checks on the player. Am unsure why i dont get the DOM element on query?
Also i cannot use locators as they retrun elements that cannot understand https://www.w3schools.com/tags/av_met_pause.asp or any similar commands 

**Actual**

[Describe actual behavior]

**Comment by AutomationGuru** [comment]
> @AutomationGuru You probably need [`evaluateHandle`](https://playwright.dev/docs/api/class-page#page-evaluate-handle). Read more about evaluating [in this doc](https://playwright.dev/docs/evaluating).

tried this, not sure if this is what you suggested? @dgozman and thanks again for helping 


(async () => {
  const browser = await playwright.webkit.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://www.example.com/');

  const head = await page.evaluateHandle('document.evaluate("//h1", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue')
  const allElem = await page.evaluate((head = this.head) => head);
  console.log(allElem) // Fails to have the element tag
  await browser.close();
})();

**Comment by dgozman** [comment]
@AutomationGuru I am afraid that your code snippet does not follow our examples. I'd recommend asking for help from [the community](https://playwright.dev/community/welcome), for example on our Discord server. Closing, as this does not seem like a bug in Playwright.
