### ISSUE TITLE
[BUG] Languages are not used consistently in Workers

### ISSUE THREAD

**Issue by shravan2x** [microsoft/playwright#28531]
### System info
- Playwright Version: v1.40
- Operating System: Windows 11
- Browser: Chrome
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Steps**
- Set `--lang=en-US,en` or `Locale = "en-US,en"` in the browser context options.
- See https://bot.incolumitas.com/#webWorkerNav

**Expected**

Languages are set consistently throughout. The test above checks that the languages array has the same value in web workers and service workers as they are in `navigator.languages` in the main frame context.. But they seem to return the default value of `["en-US"]` rather than `["en-US", "en"]`. Only the `navigator.languages` property in the regular browser window reflects the command argument languages correctly.

**Actual**

They aren't.

**Comment by shravan2x** [comment]
@dgozman I would love to provide repros, but creating a simplified version outside the full project is time consuming for simple issues.

I'm curious what information I haven't provided in my report that you'd need?

**Comment by dgozman** [comment]
@shravan2x Thanks, this is more clear. I see that passing `en-US,en` locale does indeed end up with different values in `navigator.languages` vs in the worker.

**Comment by shravan2x** [comment]
I'm glad you were able to repro it! If it's a simple fix and you're able to guide me, I can put up a PR
