### ISSUE TITLE
[DOCUMENTATION] Fixtures code samples at documentation not correct

### ISSUE THREAD

**Issue by ruimarques** [microsoft/playwright#28532]
### System info
- Playwright Version: v1.37.1

At Fixtures documentation https://playwright.dev/docs/test-fixtures

The examples show something like:

```javascript
const todoPage = new TodoPage(page);
await use(todoPage);
```

I believe it should instead be:

```javascript
const todoPage = new TodoPage(page);
await use(todoPage.page);
```

The examples in documentation actually errors out with Typescript because `TodoPage` is not of type `Page` but `use` function accepts a `Page` parameter.

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue.
