### ISSUE TITLE
Do Playwright stores  a "dev_profile" file?[Question]

### ISSUE THREAD

**Issue by dllmkdir** [microsoft/playwright#2853]
I have seen that in puppeteer there is a problem when you store a lot  of the dev_profile files.
Is there a similar case of trash files in playwright ?

**Comment by aslushnikov** [comment]
> I have seen that in puppeteer there is a problem when you store a lot of the dev_profile files.
> Is there a similar case of trash files in playwright ?

@dllmkdir I don't think so! At least we're unaware of this. Can you share with us what did you see?

**Comment by mxschmitt** [comment]
(I also saw these devprofiles in the temp directory.) for firefox and webkit

**Comment by mxschmitt** [comment]
I also saw these devprofiles in the temp directory. Examples:
- /var/folders/nq/zpr698s164v26n4v45mfkzw80000gq/T/playwright_firefoxdev_profile-k0qMI7
- /var/folders/nq/zpr698s164v26n4v45mfkzw80000gq/T/playwright_webkitdev_profile-0LlHFN
- /var/folders/nq/zpr698s164v26n4v45mfkzw80000gq/T/playwright_chromiumdev_profile-QAuKd1
Not sure if we have to add some cleanup.
cc @aslushnikov
