### ISSUE TITLE
Running Playwright Scripts on Beta WebKit and Firefox

### ISSUE THREAD

**Issue by rohithbb433** [microsoft/playwright#28533]
Hi,

I would like to inquire whether it is possible to execute our Playwright scripts on the beta versions of WebKit and Firefox, similar to how we do for Chrome and Microsoft Edge.

Specifically, I need to know:

Is it possible to run Playwright scripts on beta versions of WebKit and Firefox?
If so, what are the installation commands for beta versions of WebKit and Firefox, similar to the provided examples for Chrome and Microsoft Edge?

Example Installation Commands for Chrome and Microsoft Edge:
```
{
  name: 'Google_Chrome_Beta',
  use: { ...devices['Desktop Chrome'], channel: 'chrome-beta' },
},
{
  name: 'Microsoft_Edge_Beta',
  use: { ...devices['Desktop Edge'], channel: 'msedge-beta' },
},

npx playwright install chrome-beta
npx playwright install msedge-beta

**Comment by dgozman** [comment]
@rohithbb433 What do you mean by "beta version of WebKit"?

You can run `npx playwright install firefox-beta` and pass `channel: 'firefox-beta'`. However, Playwright does not guarantee that everything works there, it is mostly used to spot the issues earlier in the release cycle.

**Comment by rohithbb433** [comment]
Yes, the intention is to identify issues earlier; we have some similar commands for WebKit.

**Comment by dgozman** [comment]
@rohithbb433 Playwright's WebKit approximately matches Safari Technology Preview, so you should already spot issues early enough. There is no support for the official Safari build as of today, see [this doc](https://playwright.dev/docs/browsers#webkit).

**Comment by rohithbb433** [comment]
Thank you @dgozman for sharing this
