### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TheGrimler** [microsoft/playwright#28538]
### System info
Playwright Version: v. 1.31.2
Operating System: Windows 11
Browser: Chrome
Other info:
Tests worked without issue the previous day

Whenever I try to run a playwright test, it immediately fails on any action after the "page.goto("url.com");. Whether it is to click a button, fill in a text box, etc. 
However, if I add "await page.pause()" and then manually continue the test from the playwright inspector, the tests run and complete without issue. 

I've tried adding a .waitForTimeout thinking that maybe the test was moving too quickly (but this wasn't an issue prior with these same tests). It didn't work.

I then created the test below to see if the issue occurs on other web pages. The test below fails once it reaches the click action. 
The test is just to go to google.com, and click on the google image. The test does fine until it reaches the step to click on the google title. If I add the pause, then click to manually continue on the playwright inspector, the test continues and passes. 

// @ts-check
const {test, expect} = require('@playwright/test')

test('First Test',  async ({page}) => {
    await page.goto("https://google.com")
    await expect(page).toHaveTitle("Google")
   //await page.pause();
    await page.getByRole('img', { name: 'Seasonal Holidays 2023' }).click();
 
});

**Steps**
run test from command line (cmd in Terminal in VS Code) using "npx playwright test C:\\filepath\\testname.spec.js --project=chromium --headed" 
Run the test with "await page.pause()" commented out and again with it uncommented, then click on continue test when the playwright inspector pops up

**Expected**

Test clicks on google title image test passes

**Actual**

The test fails and report states test failed at step .click();
Error Displays: 

locator.click: Timeout 20ms exceeded.
=========================== logs ===========================
waiting for getByRole('img', { name: 'Seasonal Holidays 2023' })
  locator resolved to <img width="500" id="hplogo" height="200" data-atf="1…/>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
============================================================

   6 |     await expect(page).toHaveTitle("Google")
   7 |     //await page.pause();
>  8 |     await page.getByRole('img', { name: 'Seasonal Holidays 2023' }).click();
     |                                                                                                             ^
   9 |     
  10 | });

UPDATE: 
I uninstalled and re-installed playwright with the latest version (1.40.1) and it seems to be working. I am unsure what caused the error but till update if I am able to create the error again.

**Comment by dgozman** [comment]
@TheGrimler Looking at the error, it seems like you have a 20 milliseconds timeout configured somewhere, probably in `playwright.config.ts`. That could make many actions fail because they have not finished in 20ms. We recommend to not have an action timeout at all, and rely on the test timeout instead. Let me know whether this helps.

**Comment by faris-git** [comment]
I've the same issue. Is it solved and how? What's the workaround
