### ISSUE TITLE
[BUG] Local trace viewer views zip file as corrupt, even though it isn't

### ISSUE THREAD

**Issue by kenanAlhindi97** [microsoft/playwright#28548]
### System info
- Playwright Version: [v1.40]
- Operating System: [Ubuntu 20]
- Browser: [Chromium]

The _local_ trace viewer can't view this zip file even though it's a valid trace and can be loaded on trace.playwright.dev 

[be7861f5b4c4d0bbd29cf0326dc9c6bc93735781.zip](https://github.com/microsoft/playwright/files/13614296/be7861f5b4c4d0bbd29cf0326dc9c6bc93735781.zip)

**Comment by mxschmitt** [comment]
Closing as per above, feel free to re-file if you still encounter this issue
