### ISSUE TITLE
[Feature]Record videos with low clarity

### ISSUE THREAD

**Issue by guomazha** [microsoft/playwright#28545]
macbook   browser.new_context(record_video_dir="videos") 
 
How can I configure the recorded video to match what I see on my computer

**Comment by guomazha** [comment]
> @guomazha Could you please be more specific? I think recorded videos should already match what you see on your computer.

Use the following code to start recording videos,
`Context=browser.new_ Context (record_video_dir="videos",

Record_ Video_ Size={"width": 1280, "height": 720},

Viewport={"width": 1280, "height": 720})`
It is very clear in the browser, and the video pixels in the recording results are a bit blurry. I tried to find the videoRecorder.js file in the source code and modify some parameters
`Const args=` - loglevel error - f image2pipe avioflags direct - fpsprobesize 0- probessize 32- analyzeduration 0- c: v mjpeg - i -- y - an - r ${fps} - c: v vp8- qmin 0- qmax 50- crf 8- headline real time - speed 8- b: v 1M threads 1- vf pad=${w}: ${h}: 0:0: gray, cry=${w}: ${h}: 0:0 `. split ('');`

The effect has improved slightly, but it has not yet met expectations

Attempted to output each frame of ScreencastFrame in the videoRecorder.js file and found that the quality of the images was not high
`  async _sendFrames() {
    while (this._frameQueue.length) await this._sendFrame(this._frameQueue.shift());
  }
  async _sendFrame(frame) {
    const frameDir = '/Users/guo/work/record';
    const frameFileName = `frame_${Date.now()}.jpg`;
    const framePath = path.join(frameDir, frameFileName);

    // Ensure the directory exists
    await fs.mkdir(frameDir, { recursive: true });

    // Save the frame image to the file
    await fs.writeFile(framePath, frame);

    this._progress.log(`Frame image saved: ${framePath}`);
    return new Promise(f => this._process.stdin.write(frame, f)).then(error => {
      if (error) this._progress.log(`ffmpeg failed to write: ${String(error)}`);
    });
  }`

I hope to open up some parameters to make my recorded videos clearer, just like what I see in a browser

**Comment by guomazha** [comment]
> @guomazha Could you please be more specific? I think recorded videos should already match what you see on your computer.

Use the following code to start recording videos,

`Context=browser.new_ Context (record_video_dir="videos",
Record_ Video_ Size={"width": 1280, "height": 720},
Viewport={"width": 1280, "height": 720})`

It is very clear in the browser, and the video pixels in the recording results are a bit blurry. I tried to find the videoRecorder.js file in the source code and modify some parameters

`Const args=- loglevel error - f image2pipe avioflags direct - fpsprobesize 0- probessize 32- analyzeduration 0- c: v mjpeg - i -- y - an - r ${fps} - c: v vp8- qmin 0- qmax 50- crf 8- headline real time - speed 8- b: v 1M threads 1- vf pad=${w}: ${h}: 0:0: gray, cry=${w}: ${h}: 0:0. split ('');`

The effect has improved slightly, but it has not yet met expectations

Attempted to output each frame of ScreencastFrame in the videoRecorder.js file and found that the quality of the images was not high
 
`  async _sendFrame(frame) {
    const frameDir = '/Users/guo/work/record';
    const frameFileName = `frame_${Date.now()}.jpg`;
    const framePath = path.join(frameDir, frameFileName);

    // Ensure the directory exists
    await fs.mkdir(frameDir, { recursive: true });

    // Save the frame image to the file
    await fs.writeFile(framePath, frame);

    this._progress.log(`Frame image saved: ${framePath}`);
    return new Promise(f => this._process.stdin.write(frame, f)).then(error => {
      if (error) this._progress.log(`ffmpeg failed to write: ${String(error)}`);
    });
  }`

I hope to open up some parameters to make my recorded videos clearer, just like what I see in a browser

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/12056.

Over the past few years we learned that the configured ffmpeg parameters fit well for our end users - video is usually not something we recommend anymore to debug failing tests, they are fine to get an overview about what was happening, but for detailed debugging we have [Trace Viewer](https://playwright.dev/docs/trace-viewer-intro) which is much faster and helpful.

If you have a concrete reproduction which makes the video unusable, feel free to file a new bug report, thanks!
