### ISSUE TITLE
[BUG] Playwright Electron getting "TimeoutError: electron.launch"

### ISSUE THREAD

**Issue by Omikens** [microsoft/playwright#28547]
### System info
- Playwright Version: v1.40
- Operating System: macOS 13.6.1 Ventura
- Browser: Electron desktop app (Figma)
- Other info: Node.js 19.5.0

I have a set of automated tests written in Javascript + Playwright Electron experimental support. Those tests are using Figma desktop app for MacOS. With version of Figma desktop app 116.14.9 and below, those tests were functioning properly. Since version 116.15.4 I am getting "TimeoutError: electron.launch: Timeout 30000ms exceeded" during the "electron.launch()" method.
The app is launched "properly" but it is waiting endlessly for something, the tests do not proceed past the "electron.launch()" even though the app seems to be already fully launched.
I tried various solutions and I am sure that the issue is related to version of the desktop app that I am trying to launch.

Is this specific case and internal issue with Figma desktop app or maybe playwright does not support newest version of electron that Figma might be now using?

I also asked Figma support and I am waiting for their response.

### Source code
I cannot provide source code of my tests but simple launch of Figma desktop app should reproduce the issue.
```
electronApp = await electron.launch({
    executablePath: '/Applications/Figma.app/Contents/MacOS/Figma',
    colorScheme: 'dark',
});
```

**Steps**
- Launch Figma desktop app v116.15.4 with electron.launch method
https://www.figma.com/downloads/

**Expected**

App launches and tests are run.

**Actual**

App launches and the code does not proceed further. Timeout occurs.

**Comment by dgozman** [comment]
@Omikens What's the underlying Electron version? There has been a recent regression with the newest Electron versions, which should be fixed in the next Playwright v1.41 release.

**Comment by Omikens** [comment]
@dgozman From what I was able to found, Figma desktop app version 116.15.4 is using:
- Electron 26.2.4, Chromium 116.0.5845.190, Node.js 18.16.1

**Comment by dgozman** [comment]
@Omikens We fixed a problem for Electron 28+ recently (#28499), so that's probably something else. Unfortunately, I don't think we have enough bandwidth to debug the Figma desktop app right now, so any insights would be appreciated.

**Comment by mxschmitt** [comment]
Closing as per above. Feel free to re-file if you still encounter any issues.

**Comment by Omikens** [comment]
For future readers that might encounter the same issue.

I got response from Figma team, according to them they are having some issues with playwright. But they provided me a workaround that seems to be working properly. Just pass env var FIGMA_TEST and set it to 1 when launching the app. Example code that is working:

```
electronApp = await electron.launch({
    env: { FIGMA_TEST:1 },
    executablePath: '/Applications/Figma.app/Contents/MacOS/Figma',
    colorScheme: 'dark',
});
```

**Comment by qa-gary-parker** [comment]
@Omikens Do you happen to still have that implementation running? I tried it recently and I'm having no luck.

**Comment by Omikens** [comment]
@qa-gary-parker Hey, unfortunately no. That solution stopped working some time ago and I was unable to get any further help from the Figma team. I moved to automating through the browser version of the application, not the desktop.
