### ISSUE TITLE
[Feature] API call with a Client Certificate attached (which is password protected) 

### ISSUE THREAD

**Issue by subhabratapal** [microsoft/playwright#28546]
Functionality : API call with attached certificate. Certificate also has password. 

Our Use case:
We are testing a series of API calls that only returns successful response if we attach a client certificate along with the API call. Certificate is also password protected. Currently we are using playwright but due to the above scenario we also have to bring cypress in the system as it allows these kinds of API calls.

Benefits:
This kinds of API calls are common for secured banking system. I saw the same feature is available in Postman and also in cypress.

It will be good if playwright has this feature.

**Comment by rajkum1** [comment]
I am facing similar issue in my organization (In Bank). Can we have this feature available soon.

**Comment by harshadabagane0511** [comment]
I am also facing same issue..
yes, It will be good if playwright has this feature.

**Comment by dgozman** [comment]
Folding into #13426.
