### ISSUE TITLE
BUG: Getting 'element is outside of the viewport' when running tests on Github CI

### ISSUE THREAD

**Issue by mehul-warhousing1** [microsoft/playwright#28544]
### System info
- Playwright Version: v1.40.1
- Operating System: github action ubuntu latest
- Browser: Chrome
- Application - Nextjs (v14)

<img width="799" alt="Screenshot 2023-12-08 at 12 42 47 PM" src="https://github.com/microsoft/playwright/assets/74590447/2339c3e1-114e-48b8-8486-3dce0940be06">

### Element is outside of the Viewport bug
I don't get any error locally. I'm only getting an error on github actions .I saw similar errors in #3688 and #21192, I tried the solutions and it didn't work. I really don't understand what's the issue here, few weeks back it was working fine and I did not change any playwright configs.

(Note: Recently migrated to app router v14 and since then it's causing this issue)

**Comment by dgozman** [comment]
@mehul-warhousing1 This means Playwright was not able to scroll the element into the viewport. We recommend to [record a trace](https://playwright.dev/docs/trace-viewer-intro) on your CI and then inspect it to figure out the problem.

**Comment by mehul-warhousing1** [comment]
> @mehul-warhousing1 This means Playwright was not able to scroll the element into the viewport. We recommend to [record a trace](https://playwright.dev/docs/trace-viewer-intro) on your CI and then inspect it to figure out the problem.
I tried it already and got a recorded video of the failed test. The page was flickering from it's position to the left and coming back to the position. This was happening in a loop like GIF for 20 secs. So that's why the pointer was unable to locate the button properly and click it. But I am unsure if this was ever reported before, in local trace viewer or browser emulator it never happens.

**Comment by mehul-warhousing1** [comment]
@dgozman , can it be related to this #2576 ?

**Comment by dgozman** [comment]
@mehul-warhousing1 I don't think this is related to #2576. We recommend to record a trace over a video - this way you can inspect actual DOM to try and pinpoint the issue. Unfortunately, here is nothing we can help here with, unless you provide a self-contained repro that we can run locally. If you can, please open a new issue by filling in the "Bug Report" template.

**Comment by vogler** [comment]
There was some regression. Now headless pages will have a smaller viewport (or at least pages won't extend to it) than the one set for the context.
See https://github.com/vogler/free-games-claimer/issues/277#issuecomment-1871300751 for an example.
Now I have to add `await page.setViewportSize(same_as_for_context);` to fix it for headless.
