### ISSUE TITLE
[Feature] Remove the @ tags in the report because the chips show the same information

### ISSUE THREAD

**Issue by siddharth2023** [microsoft/playwright#28553]
<img width="987" alt="Screenshot 2023-12-08 at 1 30 52 PM" src="https://github.com/microsoft/playwright/assets/122398930/fec4222c-f60d-4296-a926-2cb3f66ae5d6">

I see a repetition of tags and chips in the report. Could we have just the chips? Because

1. Chips are more functional and clicking on them filters related tests
2. Without the repetition, a line can have more information about a test title

Eg of what is better:

<img width="501" alt="Screenshot 2023-12-08 at 1 40 28 PM" src="https://github.com/microsoft/playwright/assets/122398930/bc16fd7e-1a10-4bca-b218-20e7d4940368">

The same happens when you click on a test and open the individual test report.

**Comment by dgozman** [comment]
We cannot remove parts of the title and just not show it. However, with the new proposed tags api, tags will not be a part of the title, so the problem will be gone. Folding into #23180.
