### ISSUE TITLE
Clicking on an element only if it is visible

### ISSUE THREAD

**Issue by sundar-ds** [microsoft/playwright#28554]
I want to click on a web element conditionally only if it is visible on the page. I'm trying something like the below but it doesn't seem to work. The only other way I do is using the try - except block but it waits for 30s on the try block which is a lot. 

if page.get_by_label("Address Line 1").is_visible():
       page.get_by_label("Address Line 1").click()

The above wouldn't click on the element as the is_visible does not return true. Is there any better of handling this?

**Comment by dgozman** [comment]
@sundar-ds There is no guaranteed solution to this issue. It looks like the element is not visible at the start, and then it may appear or not. Therefore, you can either decide this by timeout, or by some other means like looking into a network request/response or for an alternative locator.

We do not recommend the timeout approach, but if you use it you probably want [`locator.wait_for`](https://playwright.dev/python/docs/api/class-locator#locator-wait-for) with a custom timeout.

If you have an alternative element that will be shown when "Address Line 1" is not shown, take a look [at this guide](https://playwright.dev/python/docs/locators#matching-one-of-the-two-alternative-locators).

**Comment by sundar-ds** [comment]
I was able to overcome this by adding the statement into the try block and then setting the click timeout to a lower value instead of waiting for the default timeout. Is there a reason why a timeout approach is not recommended?

**Comment by dgozman** [comment]
@sundar-ds Waiting for specific timeouts makes tests inherently flaky on slow hardware. That's why we recommend looking for a more robust solution, like a specific request/response.
