### ISSUE TITLE
[BUG] locator `has` filter not working as expected

### ISSUE THREAD

**Issue by PsiKai** [microsoft/playwright#28556]
### System info
- Playwright Version: 1.40.0
- Operating System: MacOS Sonoma 14.1.2
- Browser: All

### Source code

```js
import { test } from '@playwright/test';

test("should filter by 'has'", async ({ page }) => {
    await page.goto("https://nczdcr.csb.app/");
    const table = page.locator("table");
    const cell = table.getByRole("cell", { name: "Foo", exact: true });
    await cell.click();
    const row = table.locator("tr").filter({ has: cell });
    await row.click();
    const button = row.getByRole("button", { name: "Bar" });
    await button.click();
});
```

Testing against this [codesandbox](https://codesandbox.io/p/sandbox/table-example-for-playwright-nczdcr?file=%2Fsrc%2FApp.js%3A18%2C25)

**Steps**
- Copy paste the above test into your `test/` directory
- Execute test in any browser, headed or non.
- See failure to locate `row` element

**Expected**

Elements can be located by their child elements, as described in the [documentation](https://playwright.dev/docs/locators#filter-by-childdescendant).

**Actual**

```
locator.click: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for locator('table').locator('tr').filter({ has: locator('table').getByRole('cell', { name: 'Foo', exact: true }) })
```

**Comment by refactoreric** [comment]
Hi, (disclaimer: I'm a community member, not a Playwright dev, and only half awake.)

I don't think this is a bug, but more a matter of confusion on a somewhat a confusing feature.
Right now, as you can see in the log, it's trying to find a tr in a table, which has a table inside, with a cell having name 'Foo'.
That's not the structure of the document.

The locators for the `has` filter should be kind of a partial/relative locator.
Right now, the cell locator is pretty absolute `page.locator("table").getByRole("cell", { name: "Foo", exact: true });`
If you would make it just `page.getByRole("cell", { name: "Foo", exact: true });` I think the `cell.click` by itself might sometimes find more than 1 match, but when used inside the `has` filter, it would work better than what you have now.

**Comment by PsiKai** [comment]
> as you can see in the log, it's trying to find a tr in a table, which has a table inside, with a cell having name 'Foo'.
That's not the structure of the document.

If the inner locator would be relative to the locator that is being filtered, then the documentation is sorely lacking to mention that fact.  I do not interpret the log message that way.  There is no mention that it is searching relative to the `tr` element.

> The locators for the has filter should be kind of a partial/relative locator.

The documentation shows fully qualified locators, not relative locators.  Granted they are all on the `page` and not a locator themselves:

```js
await page
    .getByRole('listitem')
    .filter({ has: page.getByRole('heading', { name: 'Product 2' }) })
    .getByRole('button', { name: 'Add to cart' })
    .click();
```

----

>  I think the cell.click by itself might sometimes find more than 1 match

The cell click is purely for debugging purposes, which playwright has no issue finding the one and only match. 

---

> If you would make it just page.getByRole("cell", { name: "Foo", exact: true });

This solution works for my minimal example, but would not work in the actual application I'm testing, which could (and does) have multiple tables with potentially the same accessible name properties, hence my scoping of the cell to the specific table I'm looking at.

**Comment by dgozman** [comment]
@refactoreric is correct - `has` filter accepts a "relative" locator to search inside the outer one. Let me see if we can update the documentation to make it clear.

**Comment by PsiKai** [comment]
> Let me see if we can update the documentation to make it clear.

That would be great, thanks.  I'll close this.
