### ISSUE TITLE
[BUG] Playwright is not able to load is page where javascript is injected based on click event by the application.

### ISSUE THREAD

**Issue by kabdul-incomm** [microsoft/playwright#28555]
### System info
- Playwright Version: 1.40
- Operating System:  Windows 11,
- Browser: Chromium
 
Our Application inject javascript based on click event and using the javascript we display some controls and interact with user.
Here. playwright is not able to inject the javascript.

 

**Expected**

Playwright should be able to inject the javascript.

**Actual**

Playwright is not able to inject [javascript.](![PrivacySettings](https://github.com/microsoft/playwright-dotnet/assets/51454842/a542c615-220d-4eb4-9e75-a79dae823b87))

**Comment by mxschmitt** [comment]
We need a clear reproducible in order to act on it. Please re-file with something we can run locally.
