### ISSUE TITLE
[Question] How to check if element exist without failing the test

### ISSUE THREAD

**Issue by ZhouZhengCarlos** [microsoft/playwright#28557]
Hi! I wanted to achieve this:
```
if ( await page.locator(selector).isVisible() ) {
//do something
}
```
I tried this but it will never enter the if statement because isVisible() will not wait for the element to be visible. Because the timeout parameter is deprecated. Also tried with locator.count() but it is the same problem.

The problem here is because there is a modal that will appear randomly, so there will be times that won't show up, and what im trying to do is:

```
if( modal is visible ) { 
 click the closeBtn to close the modal
}
```

Is there a way to solve this problem? 
Expect wont work because this will fail my test

**Comment by dgozman** [comment]
@ZhouZhengCarlos We strongly recommend making your tests deterministic. For example, disable this modal in your test environment.

You can try/catch `waitFor`, but relying on a hardcoded timeout will usually make your test flaky on CI.
```ts
await page.locator('...').waitFor({ timeout: 5000 }).catch(() => {});
if (await page.locator('...').isVisible()) {
  // ...
}
```

**Comment by har16o** [comment]
I have a similar situation. Some of my tests, those that are positive, create entities on the site, but the negative ones do not and in order for me to reuse test data and not to generate new random values all the time I check before and after the test whether there is a created entity and if so I delete it. And in my situation it turns out any positive test and all the ones following it fail.

```
test.beforeEach(async ({ loginPage, witrinaPage, payPage }) => {
        await loginPage.openPage(routes.loginPage);
        await loginPage.login(registeredUser.email, registeredUser.password);
        await witrinaPage.waitForPageLoaded();
        await witrinaPage.checkThatElementIsVisible(witrinaPage.createWitrinaButton);
        await payPage.openPage(routes.payPage);
        if (await payPage.createdPaymentMethod.isVisible()) {
            await payPage.clickOnDeletePaymentMethodButton();
            await payPage.clickOnConfirmFieldDeleteButton();
            await payPage.reloadPage();
            await payPage.checkThatElementIsNotVisible(payPage.deletePaymentMethodButton);
        }
    });

    test.only('Positive test', async ({ payPage }) => {
        await payPage.clickOnCreatePaymentMethodButton();
        await payPage.checkCashCheckbox();
        await payPage.clickOnChooseButton();
        await payPage.fillPaymentNameInput(payMethodsData.payMethodName);
        await payPage.fillPaymentDescriptionInput(payMethodsData.payMethodDescription);
        await payPage.clickOnSaveButton();
        await payPage.checkThatPaymentMethodExists();
    });
```
It seems that this kind of usage can be quite frequent, is there any solution other than timeouts?

**Comment by ZhouZhengCarlos** [comment]
> @ZhouZhengCarlos We strongly recommend making your tests deterministic. For example, disable this modal in your test environment.
> 
> You can try/catch `waitFor`, but relying on a hardcoded timeout will usually make your test flaky on CI.
> 
> ```ts
> await page.locator('...').waitFor({ timeout: 5000 }).catch(() => {});
> if (await page.locator('...').isVisible()) {
>   // ...
> }
> ```

I understand that deterministic test is a better way to create test, but sometimes the context might be different, in my opinion flexibility is a plus, I will use that solution in my test but it will be incredible if the isVisible() timeout parameter not be deprecated.

Thanks for the quick response!

**Comment by dgozman** [comment]
Action item: explore a way we can help in this scenario.

**Comment by brunojbarros** [comment]
> if (await payPage.createdPaymentMethod.isVisible()) {
>             await payPage.clickOnDeletePaymentMethodButton();
>             await payPage.clickOnConfirmFieldDeleteButton();
>             await payPage.reloadPage();
>             await payPage.checkThatElementIsNotVisible(payPage.deletePaymentMethodButton);

In this scenario, I understand that you have a default user to perform the automated tests, wouldn't it be a good idea to always delete the payment methods after finishing all the tests? So, later it will not be necessary to ask if it exists or not.

Perhaps the following links could be useful:
- https://playwright.dev/docs/test-global-setup-teardown#option-2-configure-globalsetup-and-globalteardown
- https://learn.cypress.io/advanced-cypress-concepts/database-initialization-and-seeding

**Comment by har16o** [comment]
@brunojbarros i have several different types (methods) to make payments, and in order not to create custom data for each type I want to reuse test data (name and description of payment methods). If I don't delete the payment method after each test, then the next test will be inconsistent. In any case, there is no difference between the if conditions before or after the test, because in both cases the test will fail at the moment of searching for the element if it is not found. I think that I will use the API to get around this problem, although this is not exactly what I need in this particular situation.

Anyway, thanks for the help!

**Comment by AndriiFrolov** [comment]
it works for me
if (await postalCode.isVisible({ timeout: 1000 })) {
      await postalCode.fill("12345");
}

**Comment by dgozman** [comment]
To summarize the discussion, Playwright recommends:
- `locator.or()` to handle scenarios where either one or another option is present on the screen. See also #23543.
- `locator.waitFor()` with a timeout when the above method does not work.
- for some usecases, the upcoming #29029 should also help.

If you are experiencing a bug or would like to propose a feature request, please file a new issue and follow the corresponding template. We also recommend to [ask community for help](https://playwright.dev/community/welcome) if you cannot figure out your particular usecase.
