### ISSUE TITLE
[Feature] Give show-trace the --proxy-server option

### ISSUE THREAD

**Issue by rayjlinden** [microsoft/playwright#28563]
I'm using the --proxy-server option of playwright codeine to great effect.  However, I need the proxy server is well to show the traces given where I end up storing them.

However, the show-trace command pf playwright does not appear to have the --proxy-server option.  Can we get added to that command?  Or is there some work around?

**Comment by mxschmitt** [comment]
`show-trace` will show you how the website looked like during the test-execution, it does not make any external requests so not sure for what the http-proxy integration is needed for.

Could you give us more details on what is not working with clear reproduction steps?

**Comment by rayjlinden** [comment]
Sorry, I should have been more clear.  I need when getting the trace by
URL.  “Playwright show-trace https://domain.that needs.proxy”

Ray

**Comment by mxschmitt** [comment]
I see! Thanks for clarifying it.

Inside your normal browser which has the proxy already configured, you can also just navigate to https://trace.playwright.dev (It's a PWA, it does not send your data anywhere) and drop your zip there - would that work for you?

**Comment by mxschmitt** [comment]
Closing as per above. Please re-file for further bug reports / feature requests.
