### ISSUE TITLE
[BUG]Trace file not generated

### ISSUE THREAD

**Issue by sundar-ds** [microsoft/playwright#28565]
When I set the --tracing on flag when i run a pytest test function, i don't see the trace file generated. I had to manually insert the context.tracing.start.. statement when i open up a context. However, there are no problems with other arguments for browsers, headless, slowmo etc. 

Wouldn't tracing get generated automatically using pytest arguments if we open up a browser context?

If the program is erroring out, when should i place the context.tracing.stop statement?

**Comment by mxschmitt** [comment]
Would it be possible to share the code of your tests? `--tracing` as of today only works with the context we create for you. If you create a context yourself, it does not. We have this bug for that: https://github.com/microsoft/playwright-pytest/issues/111

**Comment by sundar-ds** [comment]
Here's the code I have:

_def ValidateAbsPlans(browser:Browser, baseURL, datadict, testScnrID):
    context = set_brwContext(browser, "video/" + testScnrID + "/" + "400_ValidateAbsPlans")
    page = set_Page(context)
    ora_Signin(page, baseURL, datadict["EmpUserID"], datadict["EmpUserPwd"])

    page.get_by_role("link", name="Navigator").click()
    page.get_by_title("Me", exact=True).click()
    page.get_by_role("link", name="Time and Absences").click()
    page.get_by_role("link", name="Absence Balance Review current plan balances and absences taken or requested").click()
    page.wait_for_timeout(5000)
    if page.get_by_text("There's nothing here so far.").is_visible():
        print("There are no absence plans listed for the employee - ", datadict["EmpUserID"])
    else:
        print("There are absence plans available for the employee - ", datadict["EmpUserID"])

    ora_Signout(page)
    context.close()

def set_brwContext(browser:Browser, videopath) -> BrowserContext:
    context = browser.new_context(record_video_dir=videopath, record_video_size={'width': 1500, 'height': 710})
    #context.tracing.start(screenshots=True, snapshots=True)
    return context

def ora_Signout(page:Page):
    page.get_by_role("link", name="Settings and Actions").click()
    page.get_by_role("link", name="Sign Out").click()
    page.wait_for_timeout(3000)
    if page.get_by_role("button", name="Yes").is_visible():
        page.get_by_role("button", name="Yes").click()
    page.get_by_role("button", name="Confirm").click()_

**Comment by shisrafilov** [comment]
The issue is still there
