### ISSUE TITLE
[Feature] Add option to set headers for page.goto (initial page load)

### ISSUE THREAD

**Issue by Meemaw** [microsoft/playwright#28568]
When working with protected environments, one might need to set some special headers on the initial page visit.

Example: https://vercel.com/docs/security/deployment-protection/methods-to-bypass-deployment-protection/protection-bypass-automation

Its possible to somewhat achieve this using the `page.setExtraHTTPHeaders`, but that is in-secure because it sends out these headers "with every request the page initiates.". This might include some third party APIs which results in a leaked token/secret key.

**Comment by hardeep-qa** [comment]
I guess, you can add this in the playwright.config file.
```
/* Base URL to use in actions like `await page.goto('/')`. */
    baseURL: process.env.BASE_URL,
    extraHTTPHeaders: { qaaccess: 'the_value' },
```

**Comment by Meemaw** [comment]
> extraHTTPHeaders

Does this work differently, ~e.g only sending out headers on the `page.goto` requests?

**Comment by StasGrishaevTutu** [comment]
@Meemaw check this one - https://github.com/microsoft/playwright/issues/18605#issuecomment-1306464497

**Comment by Meemaw** [comment]
> @Meemaw check this one - [#18605 (comment)](https://github.com/microsoft/playwright/issues/18605#issuecomment-1306464497)

So basically we could just remove the sensitive header during request interception. While this might work, the solution seems unnecessary complex.

**Comment by mxschmitt** [comment]
I think you need to specify it for every http request if I read [their docs](https://github.com/microsoft/playwright/issues/28568#issue-2034504220) correctly. 

"Modifying requests using `route.fulfill`" should work for that: https://playwright.dev/docs/network#modify-requests

So you can filter there via glob parameters and only add your header once its matches. It would then look something like this:

```ts
await page.route('http://site.com/**/*', route => {
  const headers = route.request().headers();
  headers['your-header'] = 'hello';
  route.continue({ headers });
});
```

**Comment by mxschmitt** [comment]
Closing as per above. Feel free to re-file if you still encounter any issues.

**Comment by Meemaw** [comment]
@mxschmitt mxschmitt I believe I found a bug with `(page|context).route`. This approach works fine generally, but it fails on a server redirect. In that case, headers don't seem to be propagated.

**Comment by mxschmitt** [comment]
Please re-file with more details / a reproduction, thanks!
