### ISSUE TITLE
Get Playwright Report (HTML and Trace) for cucumber tests written in Gherkin instead of cucumber html reports

### ISSUE THREAD

**Issue by sureshgopala** [microsoft/playwright#28562]
Let us know what functionality you'd like to see in Playwright and what your use case is.

Steps:
1. Configure Playwright nodeJS project with cucumber 
2. Write Feature files and step definition using playwright APIs
3. Run cucumber tests 

Actual : Need to use npx cucumber command to execute these feature files and it doesnt generate any playwright report (by default) rather need to use default cucumber report or custom cucumber reports 

Expected: Use npx playwright command to somehow run these feature files and generate playwright reports by default which are more advanced and user friendly when compared to cucumber reports. 

Do you think others might benefit from this as well?
Hopefully yes, who wants to write tests in cucumber and see playwright kind of detailed reports.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/11975.
