### ISSUE TITLE
[question] is there other way to run playwright test besides using npx playwright test

### ISSUE THREAD

**Issue by bodycombathuang** [microsoft/playwright#28573]
I know we can run "npx playwright test" to run playwright test cases.
but when we start many JMeter threads to use OS process sampler to run " npx playwright test",  we find npx command becomes very slow

is there any other way to run playright test  besides using npx playwright test?

**Comment by mxschmitt** [comment]
There is not, are you manually running `npx playwright test` in parallel yourself?

If you experience slow tests, we would love to see a reproduction in order for us to look into it.

Regarding scaling, we recommend scaling Playwright across workers on the same machine using workers: https://playwright.dev/docs/test-parallel

**Comment by bodycombathuang** [comment]
hi @mxschmitt  I just ran one case using npx playwright test --grep tag --project=chromium,  I use 40 jmeter threads to run only one case , but I find the more threads there are, each thread will spend more than to run the only one case

if there is only 1 thread, it takes 5 seconds, but if there are 40 threads, each thread takes 60 seconds, so I want to find quicker ways

**Comment by bodycombathuang** [comment]
can 50 "npx playwright test" run together at same time  consume time as long as 1 "npx playwright test --workers=50 --repeat-each=50"?

**Comment by mxschmitt** [comment]
Yes you can run `npx playwright test` in parallel, make sure to set a different output directory all the time. We as Playwright recommend using workers instead to parallelise things yourself, so you don't need to merge reports manually etc.

Folding into https://github.com/microsoft/playwright/issues/28602#issuecomment-1852716991.
