### ISSUE TITLE
[Question] Why is the config.webServer exiting early? 

### ISSUE THREAD

**Issue by ezg97** [microsoft/playwright#28570]
I'm running E2E tests during github-actions but have been usuccessful so far. When I run `npx playwright test e2e`, it works as intended.
playwright.config.js

    import { defineConfig } from '@playwright/test';
    
    export default defineConfig({
        webServer: {
            command: 'npm run start:staging --silent',
            url: 'http://localhost:3001', 
            timeout: 180 * 1000, 
            reuseExistingServer: !process.env.CI,
        },
          use: {
            baseURL: 'http://localhost:3001/',
          },
        globalSetup: require.resolve('./global-setup'),
        use: {
            // Use the saved storage state for all tests
            storageState: 'storageState.json',
        },
        // Other configurations...
    });

Here's my action file:

    name: Run Playwright Tests on PR
    on:
      pull_request:
        branches:
          - '*'
    
    jobs:
      test:
        timeout-minutes: 5
        runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install --silent

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Determine PR base branch
        id: pr_base_branch
        run: echo "PR_BASE_BRANCH=$(jq -r '.pull_request.base.ref' $GITHUB_EVENT_PATH)" >> $GITHUB_ENV

      - name: Run Playwright tests
        run: |
          if [[ "${{ env.PR_BASE_BRANCH }}" != "main" ]]; then
            npx playwright test e2e
          else
            echo "Skipping tests as the PR base branch is 'main'"
          fi

      - name: Set status checks
        if: ${{ always() }}
        run: |
          if [[ "${{ env.PR_BASE_BRANCH }}" != "main" ]]; then
            npx github-status failure -m "Playwright Tests failed"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

Error within gh-actions:

    Run if [[ "staging" != "main" ]]; then
    playwright.config.js executed
    [WebServer] One of your dependencies, etc. (non important warning about babel plugins..
 

    Error: Timed out waiting [18](<pathname>/job/19504604342#step:7:19)0000ms from config.webServer.

    Error: Process completed with exit code 1.

It fails on the `Run Playwright tests` portion.

I've tried various approaches, but I've been unable to run playwright tests in a github action.

**Comment by mxschmitt** [comment]
The error suggests that its timing out while waiting for the port.

Does the port maybe not match, so its starting e.g. `3000` instead of `3001`?

You can also debug the availability check by setting the `DEBUG=pw:webserver` env var on your CI.

**Comment by mxschmitt** [comment]
Closing as per above. Feel free to re-file if you still encounter any issues.
