### ISSUE TITLE
[Feature] Add grep to config

### ISSUE THREAD

**Issue by patricksmms** [microsoft/playwright#28576]
Currently it's only possible to set grep/grep-invert as an option, on the cli. It would be great if we could set on the configuration, this would allow setting the value dynamically - based on env variables, for ex.

Currently, to achieve this, I'm having to rely on fixtures that skip the test in case it doesn't match the value of an env variable.

**Comment by StasGrishaevTutu** [comment]
It's already there : 
- https://playwright.dev/docs/api/class-testconfig#test-config-grep
- https://playwright.dev/docs/api/class-testconfig#test-config-grep-invert

**Comment by patricksmms** [comment]
This is exactly what I was looking for! I was looking into the documentation in https://playwright.dev/docs/test-configuration and it isn't mentioned there, therefore my request.
