### ISSUE TITLE
[BUG]Global variable changes value in custom reporter function.

### ISSUE THREAD

**Issue by JasKirk70** [microsoft/playwright#28584]
### System info
- Playwright Version: [v1.36]
- Operating System: macOS 14.0
- Browser: [Chromium, WebKit]
- Other info:

I am trying to get a value from global file in test file and custom reporter file. but the value of 

I have a global class file which has a value
export default class GlobalVariables {
   public static readonly uid: string = uuidv4();
}

I am trying to use the value of uid in test file (beforeAll and afterAll function) and custom reporter (onEnd) function
import GlobalVariables from './GlobalVariables';
console.log(GlobalVariables.uidvalue)

But even though its declared as a global readonly variable, the value of the uid changes in custom reporter onEnd function.
Any idea why?

What can I do to get the same value of uid across the whole test run ( test file beforeAll, afterAll functions) and CustomReporter onEnd functions?

**Comment by mxschmitt** [comment]
Custom reporters and test execution happen inside different processes (aka. workers), they can't share any state (like variables) inside JavaScript.

What are you trying to accomplish? Maybe creating a custom reporter is not the best way to implement it. Please share more details with us, thanks!

**Comment by mxschmitt** [comment]
The workers will report the test status back to the main process and we then call the corresponding reporters.
