### ISSUE TITLE
[BUG]Order of code flow from CustomReporter functions to test functions 

### ISSUE THREAD

**Issue by JasKirk70** [microsoft/playwright#28585]
### System info
- Playwright Version: [v1.36]
- Operating System: macOS 14.0
- Browser: [Chromium, WebKit]
- Other info:

### Source code
I have code(api calls) in CustomReporter onBegin function 
Then few more api calls in test.beforeAll function

But I am observing that before the api response comes from onBegin function, the control has already moved to test.beforeAll.

I thought the order of execution would be
onBegin
test.BeforeAll
onTestBegin
test.BeforeEach and so on.
Please let me know if my understanding is wrong and also why the control moves to test.BeforeAll before all calls are completed in onBegin.

**Comment by mxschmitt** [comment]
Playwright reporters in their events will not wait or block test execution has ended/started. This is as designed.

If you want to influence the order, we recommend project dependencies: https://playwright.dev/docs/test-global-setup-teardown#option-1-project-dependencies
