### ISSUE TITLE
Scrapy playwright unlimited scroll isn't working

### ISSUE THREAD

**Issue by AliHassan89** [microsoft/playwright#28581]
I have the following code. It opens up the headless browser and I also see the page getting scrolled but the response object in parse method doesn't have any HTML. When I don't use auto-scrolling this spider works perfectly.

The code is supposed only to extract the product name and product price from this website.

```
import scrapy
import re
from scrapy_playwright.page import PageMethod
from bs4 import BeautifulSoup


def should_abort_request(req):
   if req.resource_type == "image":
     return True
   if req.method.lower() == 'post':
     return True

return False


scrolling_script = """
  const scrolls = 8
  let scrollCount = 0

  // scroll down and then wait for 5s
  const scrollInterval = setInterval(() => {
    window.scrollTo(0, document.body.scrollHeight)
    scrollCount++

    if (scrollCount === numScrolls) {
      clearInterval(scrollInterval)
    }
  }, 5000)
  """


class AuchanSpider(scrapy.Spider):
  name = 'auchan'
  custom_settings = {
    'PLAYWRIGHT_ABORT_REQUEST': should_abort_request
  }
  start_urls = ['https://zakupy.auchan.pl/shop/list/8029?shType=id']

  def start_requests(self):
    for url in self.start_urls:
        yield scrapy.Request(
            url=url,
            callback=self.parse,
            meta={
                "playwright": True,
                "playwright_include_page": True,
                "playwright_page_methods": [
                    PageMethod("wait_for_selector", "._1E5b _2I59 _1wkJ _3YFw igxN _7Zx6 Eb4X _390_"),
                    PageMethod("evaluate", scrolling_script),
                    #PageMethod("wait_for_timeout", 30000),
                    PageMethod("wait_for_selector", "._1E5b _2I59 _1wkJ _3YFw igxN _7Zx6 Eb4X _390_:nth-child(60)")
                ],
            },
            errback=self.close_page,
            cb_kwargs=dict(main_url=url, page_number=0),
        )

async def parse(self, response, main_url, page_number):
    soup = BeautifulSoup(response.text, 'html.parser')
    product_containers = soup.find_all('div', class_='_1E5b _2I59 _1wkJ _3YFw igxN _7Zx6 Eb4X _390_')
    for product_container in product_containers:
        price = product_container.find(class_='_1-UB _1Evs').get_text()
        price = re.sub(r"[\n\t\s]*", "", price)
        yield {
            'productName': product_container.find(class_='_1DGZ').get_text(),
            'price': price
        }

async def close_page(self, failure):
    page = failure.request.meta["playwright_page"]
    await page.close()
```

**Comment by mxschmitt** [comment]
Would it be possible to share some code or the website where you want to do that? This would help a ton in order to provide working code for you. Thanks!

**Comment by AliHassan89** [comment]
Hi,
Thank you for replying. here are the details

The actual div looks like this:
`<div role="progressbar" valuemin="0" valuemax="387" valuenow="200" class="progress-bar" style="width: 100%;"></div>`

Scrapy code as following:
`
import scrapy
from scrapy_playwright.page import PageMethod
from bs4 import BeautifulSoup


class MySpider(scrapy.Spider):
    name = 'mySpider'
    start_urls = ['https://example.com/shop/list/8029?shType=id']

    def start_requests(self):
        for url in self.start_urls:
            yield scrapy.Request(
                url=url,
                callback=self.parse,
                meta={
                    "playwright": True,
                    "playwright_include_page": True,
                    "playwright_page_methods": [
                        PageMethod("wait_for_selector", "class.progressbar, valuenow == valuemax")
                    ]
                },
                errback=self.close_page,
                cb_kwargs=dict(main_url=url, page_number=0),
            )

    async def parse(self, response, main_url, page_number):
        soup = BeautifulSoup(response.text, 'html.parser')
        print(soup)

    async def close_page(self, failure):
        page = failure.request.meta["playwright_page"]
        await page.close()
`

**Comment by mxschmitt** [comment]
This does not look Playwright related, could you provide an example without scrapy, bs4 and only using Playwright like shown here? https://playwright.dev/python/docs/library

**Comment by AliHassan89** [comment]
Hi, I've updated the code and the question

**Comment by mxschmitt** [comment]
The code does still include third-party dependencies. I'm closing it for now since there is no Playwright code in it. Don't hesitate to re-file with a repro which only includes the Python PIP module.
