### ISSUE TITLE
[BUG] Test timeout with browser routing

### ISSUE THREAD

**Issue by linazhangg** [microsoft/playwright#28589]
### System info
- Playwright Version: 1.39
- Operating System: Windows
- Browser: Chromium
- Other info: We tried using Playwright’s ability to route network calls (BrowserContext.route()) to reduce throttling errors. Our approach to routing is to fetch the response from the routed request, and if the request is not throttled, we fulfill the request with the response. If it is throttled, we retry a few times.  It is able to reduce throttling successfully, but we notice an increase in flakiness. The largest error bucket of flaky failures we see is: PlaywrightTimeoutError: Wait timeout after \<XX\>ms.

### Source code
This snippet is added to the beforeEach:
```
await context.route(/^(?!.*(aad|auth|signin|login|Telemetry)).*(management).*$/, async (route, request) => {
    if (!request.isNavigationRequest()) {
        let response = await route.fetch({ timeout: 0 });
        if (response.status() === 429) {
            // Retry after wait ...
        }
        await route.fulfill({
            response
        });
    } else {
        route.continue();
    }
});
```

**Steps**
1. Add the snippet to any test set up in the beforeEach
2. Execute test a couple of times and observe timeout failure

**Expected**
The network routing should only enter the retry block when a throttling error is detected. For any test without throttling errors, it should execute normally without any changes in behavior.
 
**Actual**
Occasionally, tests without throttling failures are timing out when loading or updating pages. This flakiness is observed with the routing and fetching.

**Comment by mxschmitt** [comment]
Thanks for the report! This issue does not follow the bug template, and contains by that not enough information for us to act on it. Feel free to re-file with more details (we need a test file which we can run locally with actual/expected outcome), like code which we can run locally to reproduce it. Thanks for your understanding
