### ISSUE TITLE
Disable third-party cookies

### ISSUE THREAD

**Issue by rohithbb433** [microsoft/playwright#28597]
I just wanted to know if there is a feature to block third-party cookies in Playwright for Chrome.

**Comment by mxschmitt** [comment]
There is no such feature

**Comment by siddharth2023** [comment]
So how can the testing for Chrome's disabling 3rd party cookies be done?

**Comment by igalep** [comment]
Playwright team , is this something which is going to be supported sometime soon ?
As mentioned, google are going to change their third-party cookies support

**Comment by timtnleeProject** [comment]
We need this feature so we can run Playwright tests with browser disabled cookies, to find the impact once Google disable 3rd party cookies for Chrome.

**Comment by jshanii** [comment]
Isn't Playwright already blocking third-party cookies? I have enabled 3rd party cookies in Google test account still I can not send cookies in my API requests in Playwright

**Comment by Slessi** [comment]
It should be possible to achieve this by passing the [`--test-third-party-cookie-phaseout`](https://developers.google.com/privacy-sandbox/3pcd) flag to chromium.

Playwright _should_ then support this by adding the flag to the launch options:

```ts
use: {
  ...devices['Desktop Chrome'],
  launchOptions: {
    args: ['--test-third-party-cookie-phaseout'],
  },
},
```

However, as I mentioned on https://github.com/microsoft/playwright/issues/27886#issuecomment-2061099536 it does not seem to work for some reason 🤷

**Comment by JackSpa89** [comment]
Hi playwright community!

Maybe I am doing something dumb, but for me its not working when adding this to the `playwright.config.ts`
`
                use: {
                tenant,
                locale: getLocale(tenant),
                ...devices['Desktop Chrome'],
                baseURL: baseURL(tenant, platform, environment),
                isMobile: false,
                screenshot: 'only-on-failure',
                launchOptions: {
                    args: ['--test-third-party-cookie-phaseout']
                },
                viewport: { width: 1920, height: 1080 },
`
but when launching a test in debug mode and checking chrome://flags/#test-third-party-cookie-phaseout it still shows disabled for me. Am I doing something wrong? Is it working for other people?

Thanks in advance for any input! :)

**Comment by Slessi** [comment]
@JackSpa89 That is normal. That view will only show the saved/default value, and won't change even if you pass the flag. Try running chromium from CLI with flag and you will see the same:

```
~/Library/Caches/ms-playwright/chromium-1112/chrome-mac/Chromium.app/Contents/MacOS/Chromium --test-third-party-cookie-phaseout
```

**Comment by samuelcm-bflexion** [comment]
> It should be possible to achieve this by passing the [`--test-third-party-cookie-phaseout`](https://developers.google.com/privacy-sandbox/3pcd/prepare/test-for-breakage) flag to chromium.
> 
> Playwright _should_ then support this by adding the flag to the [launch options](https://playwright.dev/docs/api/class-testoptions#test-options-launch-options):
> 
>```ts
> use: {
>   ...devices['Desktop Chrome'],
>   launchOptions: {
>     args: ['--test-third-party-cookie-phaseout'],
>   },
> },
>```

This only half worked for me, I was getting test failures in CI. The Chromium headless shell doesn't appear to support the same set of launch args as the main browser.

To get this to work in all cases you need to [opt in to the Chromium new headless mode](https://playwright.dev/docs/browsers#chromium-new-headless-mode):

```ts
use: {
  ...devices['Desktop Chrome'],
  channel: "chromium",
  launchOptions: {
    args: ['--test-third-party-cookie-phaseout'],
  },
},
```

Hopefully this will save someone else from the multiple days of headaches this has given me
