### ISSUE TITLE
Playwright Firefox browser instances not closing after closing browser context[BUG]

### ISSUE THREAD

**Issue by kaushik-i-b** [microsoft/playwright#2859]
**Context:**
- Playwright Version: [1.0.2]
- Operating System: [ Linux]
- Node version: [e.g. 12.16.3]
- Browser: [e.g. Firefox]

**Describe the bug**
 I was running the playwright automation test in cron job. When ever the first job is completed it is leaving few firefox browser instance running in background and not closing. After running multiple instances. I'm facing memory leak issue.
this is before running a job
![Capture](https://user-images.githubusercontent.com/23352836/86808946-f5d28d00-c098-11ea-9a0f-2546087d892b.PNG)

this is after job is completed
![Capture2](https://user-images.githubusercontent.com/23352836/86809151-2dd9d000-c099-11ea-9e82-f3369d6f16b6.PNG)
.

**Comment by aslushnikov** [comment]
@kaushik-i-b can you please share a reduced script that you run and that leaks browser processes for you?

**Comment by john-tmc** [comment]
In case someone else had the same issue, I was issuing new context (multiple incognito, multiple login)
I had to do browserContext()?.close() before browser.close(), it's not quite explained in the docs, but it is in the source code.
