### ISSUE TITLE
[BUG] Tracing not recording actions inside Electron main process

### ISSUE THREAD

**Issue by maikelohcfg** [microsoft/playwright#28594]
### System info
- Playwright Version: [v1.39]
- Operating System: [macOS 14.1.2]
- Browser: [Chromium]
- Other info:

### Summary
When using Playwright with connectOverCDP and attempting to capture traces with multiple tabs opened in the browser, no actions are recorded in the trace file.

### Source code

```
const browser = await chromium.connectOverCDP(`http://127.0.0.1:9222`);
await browser.contexts()[0].tracing.start({ screenshots: true, snapshots: true, sources: true });

const page = await browser.contexts()[0].newPage();
await page.goto('https://github.com');

const page1 = await browser.contexts()[0].newPage();
await page1.goto('https://www.google.com');

await browser.contexts()[0].tracing.stop({ path: 'file.zip' });

```

**Steps**
- Connect to the existing browser instance using connectOverCDP.
- Enable tracing for the connected browser.
- Interact with elements on different tabs.
- Stop tracing and examine the trace file.

**Expected**

The trace file should have recorded actions, network requests, console, snapshots, screenshots

**Actual**

The trace file contains network requests, console & screenshots but no actions or snapshots.

**Comment by mxschmitt** [comment]
I tried to reproduce, but was not able to, it looked like this which looks expected:

<img width="1284" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/56ba4a33-ba60-4c8e-ae06-61f12350a549">

Could you try out Canary? https://playwright.dev/docs/canary-releases

**Comment by maikelohcfg** [comment]
Hello @mxschmitt,

I apologize for any confusion in my previous message. I realize now that I didn't provide the complete context. While the approach we discussed works in our usual workflow, we've encountered a challenge when implementing it within the main process of an ElectronJS app.

To elaborate, in our ElectronJS app's main process, we employ Playwright to execute tests on the Chrome browser. However, when utilizing tracing during this process, we're facing an issue where the result file lacks information related to actions or source code.

**Comment by mxschmitt** [comment]
If you are using Electron, would the [official Electron integration](https://playwright.dev/docs/api/class-electronapplication) work for you? We need otherwise a full minimal repro in order to triage this further, thanks!

**Comment by mxschmitt** [comment]
Thanks I can repro. Will mark it as p3 collecting feedback for now since Playwright inside Electron is not a priority for now.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
