### ISSUE TITLE
how to wait until table is stable ?

### ISSUE THREAD

**Issue by gunajoker** [microsoft/playwright#28596]
Having a table that contains dynamic rows along with a menu icon and the menu icon opens a popup menu. Since the rows are dynamic when I make a search and click on the menu on that particular row. The playwright is too fast and sometimes the row gets reordered after the menu click and the popup menu is gone. what is the best approach to wait for the row to complete the reordering?

Note: can't use visible assertion on the row number and text combination as the table is huge and other test cases might generate similar data so can't rely on the row number.

![image](https://github.com/microsoft/playwright/assets/21328905/82da6b9f-3dc7-40bb-8573-8e1eb5265127)

**Comment by mxschmitt** [comment]
Playwright is framework / UI agnostic, so there is no generic way of waiting for a table to be stable. Depending on your application you would need to wait for UI [elements to appear](https://playwright.dev/docs/api/class-locator#locator-wait-for) or for [network requests to fulfil](https://playwright.dev/docs/network#network-events) depending on the application.

The generic answer if Playwright is too fast, a user could also run into this problem!

**Comment by gunajoker** [comment]
Thanks for your answers. I'll try out the suggestions

**Comment by yairEO** [comment]
Sometimes its not enough to "wait for UI elements to appear", because they are always there, just their styles are still not stable, and Playwright is taking a screenshot "too fast" during the small timeframe of layout instability.

It is difficult to determine through playwright when does a component had "become stable". 
it's a serious problem.   

Obviously using hard-coded delays is a bad practice

**Comment by feyzagalipzeren** [comment]
I have also the same issue with my table and could not find an effective solution. I have tried lots of things. I am so new in playwright. If you @gunajoker  could find sth, I will be appreciate with your sharing.
