### ISSUE TITLE
Unable to run test scripts in non incognito/normal mode of chrome browser

### ISSUE THREAD

**Issue by tupdikar** [microsoft/playwright#28599]
### System info
- Playwright Version: [v1.XX]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

   [NUnit.Framework.Test, Order(1), Category("Regression")]
    public async Task AccountSearch()
    {

        //    await Playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions { IgnoreAllDefaultArgs =false, Channel = "chromium", ExecutablePath = "C:\\PlaywrightProject\\ESAadminWeb\\chromium\\Application\\chromium.exe" });

        await Playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
        {

            ExecutablePath = "C:\\PlaywrightProject\\ESAadminWeb\\Chrome\\Application\\chrome.exe",
            Channel = "chrome",
            Headless = false,
            // IgnoreAllDefaultArgs= true,
            IgnoreDefaultArgs = new[] { "--disable-extensions" },

            //"--enable-incognito",

        });

        await Page.GotoAsync("https://playwright.dev");

    }

**Steps**
- [Run the test]

**Expected**

Test is run in non incognito mode of chrome browser.

**Actual**

The test is run in the incognito mode of chrome.
If we set IgnoreAllDefaultArgs =true then the browser opens but the required website does not open.

Even tried through the run setting file but in it also has no positive results.

![Capture](https://github.com/microsoft/playwright/assets/86524738/2471e0b0-5cbb-4b10-a29e-90bfcb7fa730)

**Comment by mxschmitt** [comment]
Could you help us to understand why the normal does not work for you? 

It looks indeed like incognito but its actually an in-memory browser profile which behaves like a normal browser tab.

**Comment by tupdikar** [comment]
Hello Mr. Schmitt,

Thank you for your reply.

I'm working on a project (playwright C# in VS studio) in which a website
requires 2FA, and since the browser opens every time in incognito mode, it
requires to be logged in along with 2FA.

To run test scripts without every time log in it requires being in
nonincognito mode.

So is there any way we can run the scripts in non-incognito or normal mode?

I tried Ignoreallargument but it is leading to only opening of browser in
normal mode but the test won't go forward to await Page.GotoAsync("
https://admin-esa.eonslg-qa.com/");

Appreciate your support in this regard.

Thanks & Regards,
Shakeel Tupdikar

**Comment by mxschmitt** [comment]
That makes sense! For that we recommend [launching a persistent context](https://playwright.dev/dotnet/docs/api/class-browsertype#browser-type-launch-persistent-context). You can pass an empty string to the userDataDir, which will create a temporary directory then for you.

**Comment by mxschmitt** [comment]
Closing as per above. Please re-file for further bug reports / feature requests.

**Comment by naveenanimation20** [comment]
You can use chromium.launchPersistentContext() to launch the Chromium browser with a persistent context.
We specify the directory path where the browser data will be stored (in this case, ./reports).
We pass additional options such as channel and headless as needed.

`import { chromium, BrowserContext } from '@playwright/test';

(async () => {
// Launch the browser with a persistent context
const browser: BrowserContext = await chromium.launchPersistentContext('./reports', {
channel: 'chrome',
headless: false
});

const page: Page = await browser.newPage();
await page.goto("https://naveenautomationlabs.com/opencart/index.php?route=account/register");

})();`

**Comment by RenganathanArulmani** [comment]
@naveenanimation20  is there any other soultion to turn off incognito mode while launching the browser like adding any args in config file? currently i am following the method launchPersistentContext().
