### ISSUE TITLE
[BUG]: `SyntaxError: Unexpected token 'with'`

### ISSUE THREAD

**Issue by nichita-pasecinic** [microsoft/playwright#28598]
### System info
- Playwright Version: 1.40.1
- Operating System: Windows 10
- Browser: [All, Chromium, Firefox, WebKit]

My test is importing a file that has such an import:

```ts
import config from './config.json' with {type: 'json'};
```

Background: I have a vite x TS x react project. Inside `package.json` I have explicitly set ESM:

```json
  "type": "module",
```

When I run playwright test, I get following error:

```
> playwright test -c playwright/playwright.config.ts
SyntaxError: Unexpected token 'with'
```

**Comment by nichita-pasecinic** [comment]
Note that `assert` is deprecated already, you should use `with` instead

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by nichita-pasecinic** [comment]
@pavelfeldman this must be closed by an error, the issue is still there, and you've got an closed PR up there (without reason)

**Comment by basslagter** [comment]
I also ran into this issue with 1.44.0 (and 1.44.1 also). Doing import like so:
`import data from '../../data.json' assert { type: 'json' };`

Tried replacing with:
`import data from '../../data.json' with { type: 'json' };`

But same result.

**Comment by slavika** [comment]
I'm facing the same issue. Is there any known workaround? @pavelfeldman @mxschmitt

**Comment by mxschmitt** [comment]
@slavika make sure to update Playwright + update Node.js to the latest versions, then things will work. (assert + with)

**Comment by basslagter** [comment]
> @slavika make sure to update Playwright + update Node.js to the latest versions, then things will work. (assert + with)

I am running node 20.14.0 and Playwright 1.44.1. Getting same issue

**Comment by slavika** [comment]
@basslagter 
Here PW 1.44.0 and node 20.14.0

I found a workaround that works for me. According to below article I created this separate file with sth like a wrapper on ESM import to be able to use require() instead.

Then to import json file I switched from
`import data from '../../data.json' assert { type: 'json' };`
to directly assigning json to a variable with this created require() method
`const data= require('../../data.json');`

https://dev.to/caspergeek/how-to-use-require-in-ecmascript-modules-1l42

**Comment by basslagter** [comment]
Thanks @slavika . I'll give that a go although I'd rather use the recommended method.

**Comment by leosnavratil** [comment]
My solution has been to update node from
v20.8.1 to v20.17.0

Fixed the issue for me.
