### ISSUE TITLE
[BUG] page.set_extra_http_headers is not setting header 

### ISSUE THREAD

**Issue by sdfinn** [microsoft/playwright#28593]
### System info
- Playwright Version: [v1.40.0]
- Operating System: [Windows.]
- Browser: [Chromium]
- Other info: Python 3.11.4

I cannot get page.set_extra_http_headers() to set extra header values
The following code is not returning extra headers.
I would expect to see z-key: z-value pair listed and they are not.

### Source code

```python
from playwright.sync_api import sync_playwright

extra_headers = {
    "z-key": "z-value"
}
def my_function():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False,slow_mo=1000).new_context()
        page = browser.new_page()
        page.set_extra_http_headers(extra_headers)
        response = page.goto(https://www.google.com/)
        # Print all headers from response
        all_headers = response.all_headers()
        print("\nResponse Headers:")
        for key, value in all_headers.items():
            print(f"  {key}: {value}")
        browser.close()

my_function()
```

**Comment by mxschmitt** [comment]
`set_extra_http_headers` will actually only set request headers, not response headers. To set response headers, which your application might read in JavaScript, you can use request interception. See the following example:

```python
from playwright.sync_api import sync_playwright, Route

def my_function():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False,slow_mo=1000).new_context()
        page = browser.new_page()
        page.set_extra_http_headers({
            "z-key": "z-value"
        })
        response = page.goto("https://httpbin.org/headers")
        print("\nRequest Headers:")
        for key, value in response.request.all_headers().items():
            print(f"  {key}: {value}")
        # to set response headers, you can use request interception:
        def _handle(route: Route) -> None:
            response = route.fetch()
            route.fulfill(
                response=response,
                headers={
                    **response.headers,
                    "x-key": "x-value"
                })
        page.route("**/*", _handle)
        response = page.goto("https://httpbin.org/headers")
        print("\nResponse Headers:")
        for key, value in response.all_headers().items():
            print(f"  {key}: {value}")
        browser.close()

my_function()
```

See the first part for adding request headers and the second part for adding response headers. See [here](https://playwright.dev/python/docs/network#modify-responses) for docs. Let us know if that makes it more clear!

**Comment by sdfinn** [comment]
Thanks for the good info.
Yea. My problem was reponse.all_headers() vs response.request.all_headers()
I can see the right headers are being sent now so set_extra_http_headers is working great.
From my project things are working fine with p.webkit.launch or p.firefox.launch but seems to be hanging on p.chromium.launch.
I work on that next. Thanks

**Comment by mxschmitt** [comment]
Closing since the original issue has been fixed/answered.
