### ISSUE TITLE
[BUG]Click event not works when upgrade react16.x to react 18 on Chromium

### ISSUE THREAD

**Issue by Jabbar2010** [microsoft/playwright#28595]
### System info
- Playwright Version: [v1.40.0]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [Chromium]
- Other info:

### Source code

```
test.describe('Test click bug', async () => {
  test('This is a test ', async ({ page }) => {
    await page.goto('https://dsq32p.csb.app/'); // target test url
    await page.locator('#btnTest').waitFor({
      timeout: 60000,
    });
    console.log('ready to click');
    await page.locator('#btnTest').click();
    await expect(page.locator('#title')).toContainText('playwright bug');
  });
});
```
The above code runs based on React 18, playwright can not do the click action success!
target test url: [https://dsq32p.csb.app/](https://dsq32p.csb.app/)
(you can get sandbox source code [here](https://codesandbox.io/p/sandbox/amazing-hamilton-dsq32p?file=%2Fsrc%2FApp.js%3A71%2C11))

but it works on React 16.13.0, you can change the target test url to:[https://wgmg3n.csb.app/]( https://wgmg3n.csb.app/)
(you can get sandbox source code [here](https://codesandbox.io/p/sandbox/react16-click-wgmg3n?file=%2Fsrc%2FApp.js%3A72%2C26))

Notes:
1. if you change the Component "A "  or "B " to be string or number or other no React Component in the sandbox code, it works
2. if you change the button element to be div in the sandbox code, it works
3. it works on Firefox
4. this unexpected behavior is relevant to the custom hook "useHoverOrFocus", please don't try to let me delete it from my project codebase

**Steps**
- Run the test

**Expected**

success

**Actual**

failed

**Comment by mxschmitt** [comment]
smaller repro: https://github.com/mxschmitt/playwright-issue-28595

1. `npm i`
2. `npm run dev`
3. `npx playwright test --project=chromium`

**Comment by Jabbar2010** [comment]
Hi, @mxschmitt @dgozman would you mind telling me what's the root cause for this issue?

**Comment by mxschmitt** [comment]
We were able to reproduce and will look into it in more detail as part of our 1.42 release.

**Comment by Jabbar2010** [comment]
OK, thanks

**Comment by dgozman** [comment]
Spent some time debugging this. Notes:
- Playwright hovers the button which triggers `setIsHovered` which eventually leads to `<B>` being rendered instead of `<A>`.
- However, before React re-renders the internals from `<A>` to `<B>`, Playwright clicks by sending mousedown + mouseup.
- Between mousedown and mouseup, React re-renders from `<A>` to `<B>`.
- Therefore, mousedown arrives at `<A>`, while mouseup arrives at `<B>`. This makes browser to not produce the `click` event not on `<A>`, nor on `<B>`.
Essentially, Playwright behaves like a very fast user, and slow re-rendering from React is not fast enough.

**Comment by dgozman** [comment]
@Jabbar2010 This does not seem like Playwright would or is able to mitigate properly. I'd recommend the following workaround:

```ts
await page.locator('#btnTest').hover();
await page.locator('#btnTest').click();
```

This essentially gives time to React to re-render between the hover and the click. If that's not enough, perhaps adding an explicit delay between the two would be necessary. Let me know whether this helps.

**Comment by dgozman** [comment]
Closing as per above. If you still encounter problems, please file a new issue with a repro.
