### ISSUE TITLE
[question] one question about playwright integration with jmeter

### ISSUE THREAD

**Issue by bodycombathuang** [microsoft/playwright#28602]
we can run a playwright test case multiple times using  npx playwright test --grep tag --repeat-each=40 --workers=40 --project=chromium

after running, in the test report, you can see the number of seconds  **(number_of_seconds)**  that each run takes

In Jmeter, I have a thread group which also has 40 threads, how can playwright be integrated with the jmeter thread group
so that each jmeter thread can be tied with one playwright worker, so that in jmeter report, the response time of each thread is equal to the  **(number_of_seconds)**

**Comment by mxschmitt** [comment]
This issue does not contain a question and is more an open ended discussion. This bug tracker is only for feature requests / bug reports. We as Playwright don't provide a jmeter integration and recommend reaching out to Discord for community support on it which might be more experienced on it.
