### ISSUE TITLE
[Feature] Solid and React non-jsx notation

### ISSUE THREAD

**Issue by sand4rt** [microsoft/playwright#28606]
Support for non JSX notation for Solid and React:

```ts
import { test, expect } from '@playwright/experimental-ct-react';
import Button from '@/components/Button';

test('render props', async ({ mount }) => {
  const component = await mount(Button, {
    props: {
      title: 'Submit',
    },
  });
  await expect(component).toContainText('Submit');
});
```

This makes it easier for component library authors to reuse tests for different frameworks _(related https://github.com/microsoft/playwright/issues/14516)_ as all other framework adapters support the object notation. It also helps when you want to migrate to another UI framework and leave tests unchanged as much as possible. Suggestion was made in: https://github.com/microsoft/playwright/pull/28382#discussion_r1410025299

**Comment by pavelfeldman** [comment]
With the new component detection, we consider .vue, .svelte imports as component imports. For all generic imports, we consider import a component only when it uses JSX notation. This effectively eliminates React & Solid from the list of frameworks that can use object notation.
