### ISSUE TITLE
[Feature] Experimental component testing for astro components

### ISSUE THREAD

**Issue by vitalics** [microsoft/playwright#28618]
Astro provides a way to enable various framework components(React, svelte, vue) - https://docs.astro.build/en/guides/integrations-guide/

Pitfalls: Astro currently does not support any component testing renderer API. See the docs. https://docs.astro.build/en/reference/publish-to-npm/#testing-your-component

This Issue is a placeholder when Astro will be ready for testing.

## **Alternative way:**

you can define the next structure in your Astro page folder:
<img width="368" alt="image" src="https://github.com/microsoft/playwright/assets/8816260/3c92c6f1-b34f-4f83-a793-a5dcc4ee0615">

and program next steps: 

1. start astro dev server - https://playwright.dev/docs/test-webserver
2. open the page: `{url}__fixtures__/{page}`
3. test your page
4. tear down the dev server

I have attached a link to the RFC: https://github.com/withastro/astro/issues/745

**Comment by mxschmitt** [comment]
This is out of scope for Playwright.
