### ISSUE TITLE
[BUG] v1.40.1 is not available in PyPi

### ISSUE THREAD

**Issue by mathew-jithin** [microsoft/playwright#28616]
### System info
- Playwright Version: v1.40.1
- Operating System: All
- Browser: All
- Other info: Version is not available in PyPi to download. Please have a check

### Source code
URL: https://pypi.org/project/playwright/#history

**Steps**
-

**Expected**
-

**Actual**
-

**Comment by mxschmitt** [comment]
Playwright in the different language bindings have different patch version numbers. The release notes for Python are located [here](https://github.com/microsoft/playwright-python/releases). Are you running into an issue which was fixed in a 1.40.1 which is not available in Python yet?

**Comment by mxschmitt** [comment]
Closing as per above. Please re-file for further bug reports / feature requests.
