### ISSUE TITLE
[Feature] the hidden plugin system

### ISSUE THREAD

**Issue by stkevintan** [microsoft/playwright#28615]
Background
https://github.com/microsoft/playwright/pull/13444
https://github.com/microsoft/playwright/pull/13717

It is a great idea to invent the plugin system. As upstream team, we want to share common setup/teardown code for other teams to leverage. Currently we have to force downstream teams creating the global setup and teardown files separately then call our shared functions and reference them in the playwright.config.ts by path

Plugin system would hugely save our energy and code, as we can encapsulate all the common code into a plugin then distribute it without extra instructions

So I wonder why the feature was hidden: [chore: hide plugins for now by pavelfeldman · Pull Request #13908 · microsoft/playwright (github.com)](https://github.com/microsoft/playwright/pull/13908)

I noticed it was hidden not deleted, so any plan to re-expose it? 
And Is it safe to use this hidden api for now?

Thanks

**Comment by mxschmitt** [comment]
> I noticed it was hidden not deleted, so any plan to re-expose it?

There are no plans to expose it as of today.

> And Is it safe to use this hidden api for now?

Playwright has no notion of hidden API, everything which is not documented or exposed can be removed at any point.
