### ISSUE TITLE
[Feature] Ability to retrieve list of tests being run prior to execution

### ISSUE THREAD

**Issue by scotto-at-niche** [microsoft/playwright#28626]
I'm looking to create a global setup/teardown that performs actions based on which tests are being run. In my use case, we're storing visual diff screenshots in an S3 bucket. We have a great number of these, so I'd like to be able to do the following:

1. Interact with the bucket one time in a global setup
2. _Only_ retrieve visual files that will be used in the specific test run. (That is, don't hit S3 if we're not running visual tests, and if we're debugging a single visual test, only grab reference files for that specific test rather than download everything, every time.)

Our visual tests are all tagged with a keyword, so it's easy to distinguish them if you have access to a list of tests about to be run, but that list doesn't appear to be exposed in a way that it can be accessed in a global setup. Would it be possible to expose the list of tests in a particular run in some `readonly` fashion?

**Comment by mxschmitt** [comment]
You can list all the tests with `npx playwright test --list` prior test execution, would that work for you?

Its also possible to specify [custom reporters](https://playwright.dev/docs/test-reporters#custom-reporters) there, in order to process them in a more programmatically way: `npx playwright test --list --reporter=json`.

**Comment by scotto-at-niche** [comment]
That gets me part of the way there. I was experimenting with running `npx playwright test --json --list` as a child process in the global setup, in order to retrieve tests in the right format, but got tripped up when it came to applying additional filters. For example, a workflow like so:

1. User runs from the command line `npx playwright test login --grep=@visual`
2. In the global fixture, we run `npx playwright test login --grep=@visual --list --reporter=json` and then based on the output, something like this would run in the global setup:

```typescript
  await fetchRelevantImagesFromS3(testsBeingRun.filter(test => test.name.includes('@visual')));
```

But I wasn't able to get the args and opts being passed in from the command line in order to do that, since those appear to only be part of the `FullConfigInternal` class.

A custom reporter might end up being the way we go, but I was hoping to avoid going that route since what we're trying to accomplish isn't really a reporting concern.

**Comment by mxschmitt** [comment]
Instead of doing this in global setup, I recommend the following:

1. Create a wrapper script, like run-tests.sh
2. Accept there optional parameters which get passed over to `npx playwright test` like filter, grep etc.
3. Inside the script, you do two things:
    a) run --list to get all the tests and then fetch the files from S3. There you pass the run-tests.sh parameters.
    b) run the command without --list to trigger the actual test run. There you pass the run-tests.sh parameters as well. 

Would something like that work for you?

**Comment by scotto-at-niche** [comment]
Yes and no. I can visualize that solution, but it seems limiting. I was very much trying to avoid reliance on external scripts, or getting away from just using Playwright's command line functionality. (Also trying to avoid having to fully rework how we're retrieving images from the cloud, for that matter, haha.) Is there a good reason not to make the metadata for a full test run accessible prior to execution of the tests?

**Comment by mxschmitt** [comment]
I marked my comments above as outdated, after having a discussion with the team we think using auto test fixtures would be a better way of doing it. Auto worker fixtures are the same as beforeAll/afterAll just in a more reusable form, so you can use these fixtures in multiple test files.

Something like that should work:

```ts
import { test as base } from '@playwright/test';

export const test = base.extend<{ saveLogs: void }>({
  downloadVrtFiles: [async ({}, use, testInfo) => {
   
    // download the VRT files, testInfo should contain information about the file and names etcs. (testInfo.file) 
    await use();

  }, { auto: true, scope: 'test' }],
});

export { expect } from '@playwright/test';
```

See [here](https://playwright.dev/docs/test-fixtures#automatic-fixtures) for the docs. The difference between test and worker fixtures are that test fixtures will run for every test and worker fixtures will only run for each worker.

Let us know if that works for you!

**Comment by scotto-at-niche** [comment]
This suggestion would help us reduce some of the boilerplate we were looking to avoid, so it would definitely be progress. The only sticking point I've got left is that I'm trying to reduce the number of times I'm making separate requests to S3 to download images. For context, the Playwright tests for our platform include ~500 visual diff tests, and I'd like to avoid so many individual requests creating a new client for each test when we're running the full suite (which is what I believe would happen in this scenario). That was the original thinking behind wanting to analyze the contents of a test run before it happens.

That said, we're not at a crazy scale yet so this might be manageable for us

**Comment by mxschmitt** [comment]
Awesome, let us know how the above works for you!

In the meantime / future I recommend to file a new Feature Request, which is like: Allow external snapshots to S3/Azure Blob storage.

I think we haven't seen such a PR, but thats something which might be useful for at a larger scale. So instead of providing APIs to do it yourself, allow it natively inside Playwright.

**Comment by sudharsan-selvaraj** [comment]
I was also looking for a similar solution and end up building one. refer to https://github.com/sudharsan-selvaraj/playshot

**What it covers:**

1. **Support for Multiple Cloud Storage Options**: Currently, the library supports uploading screenshots to Amazon S3 and SFTP servers. However, it can be easily adapted to work with other cloud storage providers.
2. **Automatic Screenshot Upload**: Screenshots are automatically uploaded to the remote server if there are test failures, eliminating the need to save them to version control.
3. **Screenshot Updates**: Users have the ability to individually update screenshots when there are changes in the UI.
4. **Flexible Validation**: The library provides methods for validating visual regressions for both entire pages and individual web elements.
5. **Support for Soft Assertions**: Built-in support for soft assertions is included, allowing the test suite to continue running even if a soft assertion fails, without interrupting the execution of subsequent test steps.

**Comment by danielbellmas** [comment]
This worked perfectly for me:
`npx playwright test --list --reporter=dot > tests.txt`
