### ISSUE TITLE
[BUG] When expect is execute from installable node module, the its printed outside of the step it was executed at the bottom of the html report.

### ISSUE THREAD

**Issue by alexanderdevm** [microsoft/playwright#28625]
### System info
- Playwright Version: v1.40.0
- Operating System: Ubuntu 22.04/Cent7/Etc...
- Browser: Chromium
- Other info:

### Source code
https://github.com/AleksStijelja/playwright-test

**Prereq**
1. [Node.js](https://nodejs.org/en/download) - 16.16.0 or higher
2. yarn - 1.22.19 or higher

**Steps**
1. Clone repo https://github.com/AleksStijelja/playwright-test
2. Change to this directory: `cd ~/playwright-test/playwright`
3. Install all required packages: `yarn install`
4. Install Playwright: `npx playwright install`
5. `npx playwright test`
6. `npx playwright show-report`

**Expected**
- Open index.html report, the expect print line SHOULD appear below the step where is was executed
```
- Before Hooks
- page.goto(https://playwright.dev/)— test-1.spec.ts:5
- Step #1: Validate Playwright Header— test-1.spec.ts:7
     - Playwright header is not visible— test-1.spec.ts:11
     - Playwright header is not visible(header h1)— test-1.spec.ts:11
- Step #2: Validate Playwright Highlighted Title— test-1.spec.ts:14
     - locator.innerText(header h1 span)— ../node_modules/helper/dist/helper.js:56
     - Expected title: Playwright , got Playwright .(header h1 span)— ../node_modules/helper/dist/helper.js:57
- After Hooks
```

**Actual**
- open index.html report, the expect print line does NOT appear below the step where is was executed
```
- Before Hooks
- page.goto(https://playwright.dev/)— test-1.spec.ts:5
- Step #1: Validate Playwright Header— test-1.spec.ts:7
     - Playwright header is not visible— test-1.spec.ts:11
     - Playwright header is not visible(header h1)— test-1.spec.ts:11
- Step #2: Validate Playwright Highlighted Title— test-1.spec.ts:14
     - locator.innerText(header h1 span)— ../node_modules/helper/dist/helper.js:56
- Expected title: Playwright , got Playwright .— ../node_modules/helper/dist/helper.js:57
- Expected title: Playwright , got Playwright .(header h1 span)— ../node_modules/helper/dist/helper.js:57
- After Hooks
```

[Describe actual behavior]
When expect is added to an install-able node module, for code sharing across playwright projects, then they are executed the expect line in html reports are not attached to the step that executes them, instead they appear below all steps, this causes html reports to be unreadable as all of the expects for all of the steps appear at the bottom of the report, right before after hooks.

**Comment by mxschmitt** [comment]
If you set the helper tsconfig target to `"target": "ES2017",` or higher, it seems to work, would that work for you?

**Comment by mxschmitt** [comment]
did you rebuild? [This](https://github.com/mxschmitt/playwright-test-1) is my repository with which I tried it, I had to make some changes to make it work with [these](https://github.com/mxschmitt/playwright-test-1/commit/30f9c94ed4301b0cc85eaab734da7cbacfd3a0cc) changes.

**Comment by alexanderdevm** [comment]
@mxschmitt 
I will add more details in regards to our setup to give more context:
- The way we use helpers is that they are located in their own repo, which are then build by cd/ci process and then published into our internal package repository and then installed by adding .npmrc with package repo details and then adding @helpers/{helper-name} to package.json of our playwright project which is a separate repo.

By going over the changes, I noticed that only one copy of @playwright/test was used. I was able to modify our example helper package.json and remove `@playwright/test`, add `// @ts-nocheck` at the top of helper.ts to allow yarn build to run after which running the test and viewing the html report produced the correct results. 
However since `@playwright/test` is no longer available in helpers package.json then linter/tsc/vscode/code completion complain on helper.ts that the package is missing.

Is there any ways to get html reported to work by keeping `@playwright/test` in the installable helper package to prevent disabling `linter/tsc/yarn build` error?

**Comment by mxschmitt** [comment]
Moving `@playwright/test` to peerDependencies in the helper package should make it work when it gets distributed inside node_modules in the end. This should continue to make your linting etc. happy. Could you try out that?

**Comment by alexanderdevm** [comment]
@mxschmitt that did work.

Here is a summary of all changes:
- Add playwright to peerDependency
- Add install-peers package to devDependency ( needs to install peer deps )
- Upgrade yarn 1.22.21 ( lower version does not in stall peer deps )
- update tsconfig target to ES2017

Thank you!
