### ISSUE TITLE
[BUG] Unexpected proxy download behaviour (npmrc `proxy` used but npmrc `noproxy` ignored)

### ISSUE THREAD

**Issue by tomaspetrusek-ext43791** [microsoft/playwright#28620]
### System info
- Playwright Version: [v1.40.1]
- Operating System: macOS 13.5
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

I had the same issue as https://github.com/microsoft/playwright/issues/20863
To debug I used `npx playwright install chromium --dry-run` (with a specific PLAYWRIGHT_DOWNLOAD_HOST=https://xxx)
This shows the URL and path where to store it... both were fine. Using `wget` the download worked... but not via the installer. After some debugging (in `node_modules/playwright-core/lib/server/registry/browserFetcher.js` in function `downloadBrowserWithProgressBar` set `_debugLogger.debugLogger = console;`) I have found out based on the output
```
install -- response status code: 407
Error [ERR_SOCKET_CLOSED]: Socket is closed
```
that the status code 407 (not originally in the log) is proxy authentication error. But I wasn't aware of using a proxy, as my env was clean (no proxy env vars).
Later I've realized, that in my global `.npmrc` I do have both `proxy` and `noproxy` fields... so the proxy was coming probably from here, but the noproxy (for the download domain) was ignored by the installer.

**Steps**
- add proxy and noproxy to .npmrc
- watch the installer to use the proxy, even though the domain is listed in the noproxy

**Expected**

if the domain is in `noproxy`, it should not use proxy

**Actual**

proxy is used

**Comment by mxschmitt** [comment]
I tried the following which works for me, what are you doing different?

```init
proxy=http://fakeproxy.com
no_proxy=playwright.azureedge.net,playwright-akamai.azureedge.net,playwright-verizon.azureedge.net
```

See [here](https://github.com/Rob--W/proxy-from-env?tab=readme-ov-file#no_proxy) for the no_proxy spec.

**Comment by tomaspetrusek-ext43791** [comment]
It seems we are using `noproxy` instead of `no_proxy` in our `.npmrc` file... so this caused the issue :-\

It is related to https://github.com/Rob--W/proxy-from-env/pull/19 ... so once that is merged I guess we will be fine :-)

I've tried what you wrote, it does work perfectly fine with the underline (in `.npmrc`)... and it also works with `NO_PROXY=*` on the CLI... so we can use that for now.

Thank you! You can "park this" as waiting for [Rob--W/proxy-from-env/pull/19](https://github.com/Rob--W/proxy-from-env/pull/19) or even close it, whichever makes more sense.

**Comment by mxschmitt** [comment]
Closing then, thanks!
