### ISSUE TITLE
[BUG]playwright.ps1 install fails with found assembly but missing required assets

### ISSUE THREAD

**Issue by david-grandfield** [microsoft/playwright#28631]
### System info
- Playwright Version: [v1.40]
- Operating System: Windows 11
- Browser: n/a
- Other info: env var for NODE_EXTRA_CA_CERTS            C:\netskope-cabundle.pem cert exists and is installed at the defined location
- 

### Source code
using strictly the example in the install instructions from site for .net

![image](https://github.com/microsoft/playwright/assets/148503882/9aa20aad-1018-4ccf-8589-ac68bdbef0ab)

**Steps**
NUnit
MSTest
dotnet new nunit -n PlaywrightTests
cd PlaywrightTests

Install the necessary Playwright dependencies:
NUnit
MSTest
dotnet add package Microsoft.Playwright.NUnit

Build the project so the playwright.ps1 is available inside the bin directory:
dotnet build

Install required browsers by replacing netX with the actual output folder name, e.g. net6.0:
pwsh bin/Debug/netX/playwright.ps1 install

fails as described

**Expected**

Installs browsers 

**Actual**

Microsoft.Playwright assembly was found, but is missing required assets. Please ensure to build your project before running Playwright tool.

**Comment by david-grandfield** [comment]
I've tried the same for .net7.0 and .net6.0 with the exact same results.

**Comment by mxschmitt** [comment]
I was able to reproduce it with 1.40.0. This should be fixed with 1.41.0 which gets released in a few weeks.

In the meantime I recommend to remove the special characters from your folder name.

**Comment by david-grandfield** [comment]
@mxschmitt Thanks for the update.  I will try that and look forward to the update.
