### ISSUE TITLE
Change User-Agent header to a custom value for all requests going through chromium

### ISSUE THREAD

**Issue by sruthii38** [microsoft/playwright#28638]
I am trying to manually intercept requests to add a custom header using axios Client. But for some reason headers are not getting displayed in chromium when I debug. So, I am planning to see if I can add a custom header for all the requests. Can some one help me direct through the steps to change User-Agent header for all requests.

**Comment by mxschmitt** [comment]
Changing the userAgent globally with @playwright/test does not require manual request interception. You can do it by adjusting your `plawright.config.ts` see [here](https://playwright.dev/docs/api/class-testoptions#test-options-user-agent). Have you tried that approach?

**Comment by mxschmitt** [comment]
Closing as per above. Please re-file for further bug reports / feature requests.
