### ISSUE TITLE
[BUG] Loss of app rebuild when using UI mode

### ISSUE THREAD

**Issue by edumserrano** [microsoft/playwright#28632]
### System info
- Playwright Version: [v1.40.1]
- Operating System: [Windows 10]
- Browser: [All]

### Source code

Clone the [temp-5 tag](https://github.com/edumserrano/playwright-adventures/tree/temp-5) from the [edumserrano/playwright-adventures repo](edumserrano/playwright-adventures).

**Steps**
- After cloning the above repo, go to [/demos/code-coverage-with-monocart-reporter/](https://github.com/edumserrano/playwright-adventures/blob/temp-5/demos/code-coverage-with-monocart-reporter/README.md) and run `npm i` to restore the npm packages.
- Run `npx playwright test --ui` to launch the Playwright UI mode.
- Make a change to the `title` variable of the [/demos/code-coverage-with-monocart-reporter/src/app/app.component.ts](https://github.com/edumserrano/playwright-adventures/blob/4426966805cbc9b09c7413e01e60a059b44072c7/demos/code-coverage-with-monocart-reporter/src/app/app.component.ts#L14) and notice on the output of the Playwright UI that the app is rebuild. For instance, change the `title` to `code-coverage-with-monocart-reporter-1`.
- Run all the `screenshot` test on all 3 browsers. The tests should now fail and flag the difference as expected.
- Make another change to the `title` variable of the [/demos/code-coverage-with-monocart-reporter/src/app/app.component.ts](https://github.com/edumserrano/playwright-adventures/blob/4426966805cbc9b09c7413e01e60a059b44072c7/demos/code-coverage-with-monocart-reporter/src/app/app.component.ts#L14) and notice on the output of the Playwright UI that the app is **NOT** rebuilt. For instance, change the `title` to `code-coverage-with-monocart-reporter-2`.

You can see the above behaviour  demoed below:

![ui-mode-bug](https://github.com/microsoft/playwright/assets/15857357/6cc88124-65b4-4b41-9f33-538c2f39389b)

Note how the app rebuild is always triggered as expected on code change except after I've run the `screenshot` test on all 3 browsers and it failed. Because the app stops compiling on code change, you can see that on the last test run I had changed the `title` variable to `code-coverage-with-monocart-reporter555` but in the `actual` image was still showing that as `code-coverage-with-monocart-reporter2`.

**Expected**

The app should always rebuild on any change.

**Actual**

After the tests fail the app stops rebuilding on app changes.

### Other notes

- The bug only seems to happen when the `screenshot` test fails. As you can see on the `gif` above, when the `screenshot` test completes successfully, the app rebuild on code change behaviour is not affected.
- I sometimes was able to cause this bug even without running a failed `screenshot` test on all 3 browsers. Sometimes I could reproduce it running just on one browser but running on all 3 browsers was the only  deterministic way I found to reproduce.
- The repo used to reproduce the bug contains two other apps where I **can NOT** reproduce the problem:
  - [/demos/code-coverage-with-istanbul-via-webpack-babel-plugin/](https://github.com/edumserrano/playwright-adventures/blob/temp-5/demos/code-coverage-with-istanbul-via-webpack-babel-plugin/README.md): similar app and tests as the `/demos/code-coverage-with-monocart-reporter/` where the bug is present except that this one uses an `html` reporter whilst the app with the bug uses the [monocart-reporter](https://github.com/cenfun/monocart-reporter) reporter. This might be completely unrelated but thought it would be worth to mention.
  - [/demos/docker](https://github.com/edumserrano/playwright-adventures/blob/temp-5/demos/docker/README.md): similar app as the other two but runs the tests, including UI mode, via docker.

**Comment by edumserrano** [comment]
Example of losing app rebuild when running on a single browser, I've chosen to demo it on `chromium` but I've been able to replicate this issue by doing the same but on the other browsers. It's just not deterministic as opposed to the steps/gif shown on the description of this issue where the `screenshot` test is executed across the 3 browsers. 

When running only on one browser, sometimes the issue is triggered at the first code change, sometimes it takes several code changes. In the demo below, note how at the end the app rebuild stops being triggered in the end, when I change the `title` variable to `code-coverage-with-monocart-reporter5` or to `code-coverage-with-monocart-reporter888`. 

![ui-mode-bug-2](https://github.com/microsoft/playwright/assets/15857357/4d2dde70-d12c-439f-8990-1d879a9a005b)

**Comment by mxschmitt** [comment]
Most likely Angular in your case is watching too many files/directories and thinks that when we write e.g. stuff in our test-results or playwright-report directory that its Angular related. There should be an option inside your Angular dev server to exclude certain directories in their watch mode. That might do the trick already.

Might be related to https://github.com/angular/angular-cli/issues/26644

I would try adding some logs in the code pointers here https://github.com/angular/angular-cli/issues/26644#issuecomment-1855256730 to find out why it got rebuild. Since this is Angular specific, we cannot help much there unfortunately!

**Comment by edumserrano** [comment]
Since it sometimes works as expected and sometimes doesn't I thought I'd share it here to hear your thoughts and see if it was Playwright related by any chance.

Thank you for taking a look @mxschmitt. I'll close this for now and I'll consider reopen if I get more info.

**Comment by mirobo** [comment]
> Most likely Angular in your case is watching too many files/directories and thinks that when we write e.g. stuff in our test-results or playwright-report directory that its Angular related. There should be an option inside your Angular dev server to exclude certain directories in their watch mode. That might do the trick already.
> 
> Might be related to [angular/angular-cli#26644](https://github.com/angular/angular-cli/issues/26644)
> 
> I would try adding some logs in the code pointers here [angular/angular-cli#26644 (comment)](https://github.com/angular/angular-cli/issues/26644#issuecomment-1855256730) to find out why it got rebuild. Since this is Angular specific, we cannot help much there unfortunately!

@mxschmitt After the hints from Alan I found out that it was indeed Tailwind (and my wrong configuration).

Tailwind is really limited with the param "content". Also some Code Coverage plugins for Cypress also generate HTML-files and Tailwind will pick these up and trigger a rebuild (via Webpack or also ESBuild), if not somehow excluded with some magic that I don't know of.. yet.

At least you can add a customWebpackConfig to your project.json/angular.json where you can add more specific ignores. But at later point you will migrate to ESBuild and have the same problem with Tailwind again..

**Comment by edumserrano** [comment]
I did another test:

1) start the app with `npm start` 
2) start the UI mode with `npx playwright test --ui`
3) because the `playwright.config.ts` has `webServer.reuseExistingServer` is set to true then the UI mode doesn't have to start the app and uses the app I started on step 1.
4) make a change on the `title` variable and notice the app is rebuild.
5) run the `screenshot` tests in the UI mode on all 3 browsers.
6) the tests fail because of the change done on step 4
7) change again the `title` variable and now the app is **NOT rebuild**.

I guess this is another way of showing this is unrelated with Playwright UI mode and perhaps some weird interaction with Angular's file watcher and the generated files from Playwright+monocart-reporter when tests fails...

**Comment by edumserrano** [comment]
As a workaround, if I set the Playwright's `outputDir` and the output dir for the `monocart-reporter` to be `/test-results` instead of `test/test-results` then Angular's file watcher doesn't detect any file change when Playwright or the `monocart-reporter` generate files.

I don't know how to exclude files/folders from Angular's file watcher when using the new esbuild+vite bundler so I'll stay with the workaround for now.

I'll move this issue to Angular's repo. 

Thank you both.

**Comment by edumserrano** [comment]
Seems to be related with angular/angular-cli#26633. See [this comment](https://github.com/angular/angular-cli/issues/26633#issuecomment-1858037467).
