### ISSUE TITLE
[HELP ME] Tests keep failed due to timeout or target closed

### ISSUE THREAD

**Issue by thangkieu** [microsoft/playwright#28647]
### System info
- Playwright Version: 1.39.0
- Operating System: macOS 13.2
- Browser: Chromium
- Other info:

### Source code

Please find my test script here (it's not working, just contains my scripts)
https://codesandbox.io/p/sandbox/playwright-test-f5fg4n

**Steps**
- Run the `test.describe` 

**Expected**

All test cases must be successfully executed

**Actual**

It's unstable, sometimes a few test cases succeed, sometimes not. If I run an individual test, it works well. However, when I ran the whole group of tests, some failed, and some succeeded (The error was also different each time, either `Target closed` or `Timeout`)

- Have you guys run more than 100 tests all at once? Does it consistently succeed all the time?

Thank you very much!

**Comment by mxschmitt** [comment]
This issue does not contain a self-contained reproduction. Feel free to re-file with a link to a repository or snippet which we can run locally. This helps us a ton in order to triage issues like this. Thanks for your understanding!
