### ISSUE TITLE
Are there any AI enabled features coming up in Playwright?

### ISSUE THREAD

**Issue by sundar-ds** [microsoft/playwright#28646]
Wanted to know any planned AI capabilities are coming up in Playwright that will be useful for automated testing. Not sure what I can expect but just wanted to ask.

**Comment by pavelfeldman** [comment]
Thank you for your interest in the project. We are always looking for the ideas around the GPT integration with the test automation. If you have ideas about the AI-aided features, please file them using the feature template and describe the feature, associated scenarios and suggested approach to the implementation!
