### ISSUE TITLE
WebGL Renderer on WebKit Browser

### ISSUE THREAD

**Issue by newohkla** [microsoft/playwright#2864]
Currently the default [WebGL unmasked renderer](https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_debug_renderer_info) property for each of the browsers is the following:

Chromium: Google SwiftShader
Firefox: null
WebKit: Apple GPU

The Chromium and Firefox values are consistent with that of a headless (non-human operable) browser.
The WebKit result matches the result from iPhones (human-operable) when in headless mode. 

WebGL renderer information is routinely used for debugging:
http://codeflow.org/entries/2016/feb/10/webgl_debug_renderer_info-extension-survey-results/

Is the dev team open to replacing the value returned from this extension to something unique to indicate that the browser is operating in headless mode? For example, "Apple Software Renderer" is used by Apple Emulators to distinguish it from a true Apple GPU.

Screenshots from headless mode on webglreport.com are attached.

![example-chromium](https://user-images.githubusercontent.com/64391173/86849761-da8d6080-c04b-11ea-8ac2-d7cfae1d73a1.png)
![example-firefox](https://user-images.githubusercontent.com/64391173/86849770-de20e780-c04b-11ea-87c6-fe84f6d0c1f6.png)
![example-webkit](https://user-images.githubusercontent.com/64391173/86849773-deb97e00-c04b-11ea-9205-80dac5039e45.png)

**Comment by aslushnikov** [comment]
(+cc @yury-s who has a better understanding on what's going on here)

**Comment by yury-s** [comment]
@newohkla are you only concerned about headless mode or would like to see a different value in headful browser as well? What do you think would be an appropriate value for headless webkit?

**Comment by newohkla** [comment]
I believe the headful version has access to and uses the GPU, so I am only concerned about the headless browser. I think an appropriate value for the headless webkit browser would be "Playwright Software Renderer" to indicate the true rendering engine of the browser.

**Comment by aslushnikov** [comment]
> For example, "Apple Software Renderer" is used by Apple Emulators to distinguish it from a true Apple GPU.

Very convincing argument.

**Comment by newohkla** [comment]
Is there an update on this issue?

**Comment by yury-s** [comment]
@newohkla sorry for the silence, we'd like to resolve this issue one way or the other. Given that Playwright itself doesn't change the underlying WebGL implementation in WebKit I'm hesitant rewriting current values with something playwright-specific. Would it make sense to return actual underlying strings that we get from the platform (and not override them inside WebKit) in case of Playwright? E.g. on my Linux box it would be
```
VMware, Inc.
llvmpipe (LLVM 10.0.0, 256 bits)
```
instead of
```
Apple Inc.
Apple GPU
```

**Comment by newohkla** [comment]
@yury-s It would make sense to return the underlying string instead of "Apple Inc."/"Apple GPU" in all cases.
