### ISSUE TITLE
[BUG] Failed expect() after test.fail() does not close browsers for parameterized tests until all tests are done.

### ISSUE THREAD

**Issue by super-brian** [microsoft/playwright#28648]
### System info
- Playwright Version:  1.40.1
- Operating System: Windows 10
- Browser: Chromium
- Other info: using VSCode Version: 1.85.0 (user setup)

### Source code

```ts
for (let i = 0; i < 4; i++) {
        test.only(`Develop: does context close when scenario fails ${i}/ 4`, async ({ browser }) => {
	        const page = await browser.newPage();
	        await page.goto('http://google.com')
	        const page2 = await browser.newPage();
	        await page2.goto('http://bing.com')
        
	        test.fail();
	        expect(1).toBe(0);
        
	        await page.close();
	        await page2.close();
        });
}
```
**Steps**
- [Run the test]

**Expected**

For each scenario: two browsers show up then both are closed.

**Actual**

For each sceanrio: two browsers show up then nothing is closed. 
At the end of the fourth scenario, all eight browsers are closed.

**Comment by mxschmitt** [comment]
This is expected, if you launch your context (what browse.newPage does internally) yourself, then you need to close the context afterwards. This means something like that:

```ts
for (let i = 0; i < 4; i++) {
	test.only(`Develop: does context close when scenario fails ${i}/ 4`, async ({ browser }) => {
		try {
			const page = await browser.newPage();
			await page.goto('http://google.com')
			const page2 = await browser.newPage();
			await page2.goto('http://bing.com')

			test.fail();
			expect(1).toBe(0);
		} finally {
			await page.close();
			await page2.close();
		}
	});
}
```

**Comment by super-brian** [comment]
Thank you for the quick answer, but also interesting to see that if two lines of 'await page.goto()' are removed, then they work as "expected" - I mean, two browsers are closed after each test. Is this also 'as expected'? Why does going to a specific url make the difference?
