### ISSUE TITLE
[BUG] All screen comparisons for the entire test shown within tab Attachments, although I have gone into details of a test step

### ISSUE THREAD

**Issue by NikkTod** [microsoft/playwright#28644]
### System info
- Playwright Version: [v1.40.1]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:
- 
**Steps**
I have a test with multiple steps that do visual comparison. 
I set on purpose multiple visual comparison steps to fail. 
When I open the Traces viewer within the Attachment tab I can see all of the failed visual comparison attachments, which is ok.
Then I open and go into details of a single failed step that has visual comparison action.

**Expected**

I expect to see the visual comparison attachment only for that single step. 

Should be similar behavior as with the Network calls, we should see only the events for that step when we are in details of it. 

**Actual**

Although I have gone into details of a test step I still see all attachments for the entire test.

**Comment by mxschmitt** [comment]
We unfortunately need a clear reproduction in order to triage issues like this. Feel free to re-file with attaching a test file or a few test files in form of a repository. This would help us a ton in order to debug issues like this. Thanks for your understanding!
