### ISSUE TITLE
[REGRESSION]: WebKit crashes in docker when using HTTP proxy starting from 1.38.0

### ISSUE THREAD

**Issue by lobachpavel** [microsoft/playwright#28643]
**Context:**
- GOOD Playwright Version: 1.37.1
- BAD Playwright Version: 1.38.0+
- Operating System: Linux (docker amd64)
- Extra: in our CI we don't have direct connection to internet, so we are using http_proxy & https_proxy environment variables in playwirght tests (our tests are running in docker containers), but starting from 1.38.0 WebKit crashes when trying to navigate to any page (other browser work fine). However tests are working when running locally without using proxy, but we can not avoid proxy in our CI

**Code Snippet**
Any simple test can be used, for example:
```javascript
import { test, expect } from '@playwright/test';

test('has title', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  await expect(page).toHaveTitle(/Playwright/);
});
```

I've prepared docker-compose.yaml with proxy container which helps reproducing the problem:
```yaml
version: "3"

services:  
  proxy:
    image: monokal/tinyproxy
    stop_grace_period: 0s
    command:
      - ANY
    expose:
      - "8888"
  playwright-test:
    image: mcr.microsoft.com/playwright:v${PW_VERSION:-1.40.1}
    working_dir: /root
    command:
      - bash
      - -c      
      - npm install playwright@${PW_VERSION:-1.40.1} @playwright/test@${PW_VERSION:-1.40.1} && npx playwright test --browser ${PW_BROWSER:-webkit}
    environment:
      DEBUG:
      http_proxy: http://proxy:8888
      https_proxy: http://proxy:8888
    volumes:
      - ./sample.test.js:/root/sample.test.js
    depends_on:
      - proxy
```
save the test into file `sample.test.js` and put it next to `docker-compose.yaml`

this works:
`DEBUG='pw:test:protocol' PW_VERSION=1.37.1 docker compose up --exit-code-from playwright-test`
but this doesn't (actually any image version after 1.37.1 fails):
`DEBUG='pw:test:protocol' PW_VERSION=1.38.0 docker compose up --exit-code-from playwright-test`
Here is the log excerpt
```
2023-12-14T09:08:08.672Z pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"testEnd","params":{"testId":"794e161f9090ba4cb624-56b9bfe0136066ab90b2","duration":642,"status":"failed","errors":[{"message":"page.goto: WebKit encountered an internal error\n=========================== logs ===========================\nnavigating to \"https://playwright.dev/\", waiting until \"load\"\n============================================================","stack":"Error: page.goto: WebKit encountered an internal error\n=========================== logs ===========================\nnavigating to \"https://playwright.dev/\", waiting until \"load\"\n============================================================\n    at /root/sample.test.js:4:14"}],"expectedStatus":"passed","annotations":[],"timeout":30000}}}
  ✘  1 [webkit] › sample.test.js:3:5 › has title (642ms)
2023-12-14T09:08:08.676Z pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"method":"done","params":{"fatalErrors":[],"skipTestsDueToSetupFailure":[]}}}
2023-12-14T09:08:08.677Z pw:test:protocol SEND ► {"method":"__stop__"}
2023-12-14T09:08:08.677Z pw:test:protocol ◀ RECV {"method":"__dispatch__","params":{"id":1}}
2023-12-14T09:08:08.677Z pw:test:protocol ◀ RECV {"method":"__env_produced__","params":[["TEST_WORKER_INDEX","0"],["TEST_PARALLEL_INDEX","0"],["TEST_ARTIFACTS_DIR","/root/test-results/.playwright-artifacts-0"]]}


  1) [webkit] › sample.test.js:3:5 › has title ─────────────────────────────────────────────────────

    Error: page.goto: WebKit encountered an internal error
    =========================== logs ===========================
    navigating to "https://playwright.dev/", waiting until "load"
    ============================================================

      2 |
      3 | test('has title', async ({ page }) => {
    > 4 |   await page.goto('https://playwright.dev/');
        |              ^
      5 |
      6 |   // Expect a title "to contain" a substring.
      7 |   await expect(page).toHaveTitle(/Playwright/);

        at /root/sample.test.js:4:14

  1 failed
    [webkit] › sample.test.js:3:5 › has title ──────────────────────────────────────────────────────
```

**Describe the bug**

webkit doesn't work via http_proxy in playwright docker image starting from version 1.38.0

**Comment by mxschmitt** [comment]
Instead of setting the proxy through env, have you considered setting it in the config?

This seems to work for me: https://playwright.dev/docs/api/class-testoptions#test-options-proxy

**Comment by lobachpavel** [comment]
Hi @mxschmitt 
Unfortunately we can not. Our CI environment is much more complex than just running single test inside single docker container. Actually we have a browser farm running browsers inside k8s pods (something similar to Moon). And we are providing the jobs with remote websocket URL which in turn is used in Playwright tests. When you connect remotely you can not setup proxy via Playwright config right? Second cons about that method - we don't want giving our CI users control over the proxy settings - because it's also a little more complex than just a single corporate proxy (actually each browser pod runs its own sidecar envoy proxy container which routes requests either directly or via upstream proxy)

setting http_proxy is also supported and documented way for minibrowser, why all of a sudden it stopped working?

**Comment by mxschmitt** [comment]
That makes sense! We'll investigate, I can repro and have a stack trace that the Network Process is crashing.

**Comment by mxschmitt** [comment]
The fix for that should be in canary in around 24-48 hours: https://playwright.dev/docs/canary-releases
