### ISSUE TITLE
[BUG]playwright._impl._api_types.Error: Browser closed.

### ISSUE THREAD

**Issue by Clowne1** [microsoft/playwright#28640]
### System info
- Playwright Version: [v1.22]
- Operating System: [Windows 10]
- Browser: [Chromium 102.0.5005.115]
- Other info:

### Source code
    browser = playwright.chromium.launch_persistent_context(headless=False,executable_path = 'C:\Users\Admin\Desktop\Chrome\chrome.exe',user_data_dir=__USER_DATE_DIR_PATH__ )

### Report
when i run the above code, i get the error:playwright._impl._api_types.Error: Browser closed. playwright v1.22.0 seems not supprt Chromium v102.0.5005.115.

**Comment by Clowne1** [comment]
chrome 102.0.5005.115

**Comment by mxschmitt** [comment]
Closing as per above. Please re-file for further bug reports / feature requests.
