### ISSUE TITLE
[BUG] List reporter Gitlab CI/CD results hightlight

### ISSUE THREAD

**Issue by pysho161** [microsoft/playwright#28641]
### System info
- Playwright Version with no highlight: v1.40.0-1.40.1
- Playwright Version with highlight: v1.39.0
- Operating System: Ubuntu 20.04 LTS
- Browser: All
- Other info: GitLab Enterprise Edition [v16.2.3-ee](https://gitlab.com/gitlab-org/gitlab/-/tags/v16.2.3-ee), gitlab-runner 14.1.0, Docker image: mcr.microsoft.com/playwright:v1.40.0-focal or mcr.microsoft.com/playwright:v1.40.1-focal

### Source code

Issue can be reproduced with any test.

**Steps**
- Run the job
- Check the job output

**Expected**

Results should be highlighted:
![изображение](https://github.com/microsoft/playwright/assets/88162251/92012525-c654-499f-b8c8-b4d7a94d862e)
![изображение](https://github.com/microsoft/playwright/assets/88162251/7cd8afed-fee9-4cab-a166-a5d52ff968e4)
![изображение](https://github.com/microsoft/playwright/assets/88162251/b075cba7-c71d-4007-8840-7c91ec7dee01)

**Actual**

Results are not highlighted:
![изображение](https://github.com/microsoft/playwright/assets/88162251/1c690e1c-4dc4-4ba5-8ee4-347adca839db)
![изображение](https://github.com/microsoft/playwright/assets/88162251/b6e955a0-f618-4984-b04d-208147a69334)
![изображение](https://github.com/microsoft/playwright/assets/88162251/b4bbae3a-7b05-421a-947f-8849c386ca18)

**Details**
I see no issue for the same Node.js version running through PowerShell 5.1 in Windows 10:
![изображение](https://github.com/microsoft/playwright/assets/88162251/28679958-4686-4041-b937-eb72b12f43d3)
![изображение](https://github.com/microsoft/playwright/assets/88162251/4797be3a-de14-4526-a5fd-d13aa25a3d74)
![изображение](https://github.com/microsoft/playwright/assets/88162251/1e7de041-9dc8-4b46-8c00-6ffbb7f5813c)

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/28260.

This comment will help you: https://github.com/microsoft/playwright/issues/28260#issuecomment-1828820114
