### ISSUE TITLE
[BUG] On pytest-playwrigh when try modify response route.fulfill(status=500) request on browser freeze on pending status

### ISSUE THREAD

**Issue by Eldar-Adzhiev** [microsoft/playwright#28651]
### System info
- Playwright Version: [pytest-playwright=0.4.3]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium(115.0.5790.75), Firefox, WebKit]
- Other info:

### Source code

from playwright.sync_api import sync_playwright

```python
def test___():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        context = browser.new_context()
        page = context.new_page()
        api_request_context = context.request
        page.goto("https://www.demoblaze.com/")
        context.route("https://api.demoblaze.com/entries", lambda route: route.fulfill(status=500))
        page.reload()  # theese step must made thise https://api.demoblaze.com/entries endpoint statuscode = 500
       # but its became 500 after execute  'api_request_context.get("https://api.demoblaze.com/entries")'

```

**Steps**
- [Run the test]
- [Run routing]
- [Send  response throw browser]
- 

**Expected**

"need_url" endpoint sends 500 status code

**Actual**

response stay on pending status, 500 status code returned after executing:
api_request_context = context.request
api_request_context.post("need_url")

**Comment by mxschmitt** [comment]
Could you provide us a full repro which we can run locally?

**Comment by Eldar-Adzhiev** [comment]
I updated code, please just copy  and you will see that entries endpoint freeze on pending status after reload page

**Comment by mxschmitt** [comment]
Could you elaborate on how you see that it freezes? Do you set a breakpoint() or attach a debugger?

If I set a `page.pause()` and then open DevTools, it does not hang for me.

**Comment by Eldar-Adzhiev** [comment]
Yes, I used debugger, my bad. Thank you very much
