### ISSUE TITLE
[Feature] Implement `Response.dispose` akin to `APIResponse.dispose`.

### ISSUE THREAD

**Issue by michaeleveringham** [microsoft/playwright#28657]
**Let us know what functionality you'd like to see in Playwright and what your use case is.**

Currently we can handle caching on a per-response level for `APIResponse` objects, but not for `Response` objects. It seems that the underlying object can be disposed using a private method; `Response._impl_obj._dispose()` deletes and removes the object from `BrowserContext._impl_obj.objects`. However I'm not sure how wise or effective it is to use this directly.

Example:
```
import asyncio

from playwright.async_api import async_playwright


async def main():
    playwright = await async_playwright().start()
    browser = await playwright.chromium.launch()
    context = await browser.new_context()
    page = await context.new_page()

    response = await context.request.get("https://github.com")
    # APIResponse, works as expected.
    await response.dispose()

    response = await page.goto("https://github.com")
    
    # Would raise an AttributeError.
    # await response.dispose()

    # Works, but unclear how safe. Mapped object still exists, too.
    response._impl_obj._dispose()

asyncio.run(main())
```

**Do you think others might benefit from this as well?**

Yes. This gives consistency to the models across the project and is especially helpful when handling intercepted responses.

**Comment by michaeleveringham** [comment]
You probably already realised this since you tagged this `browser-firefox` but just to share: I ran this with Chromium and did not hit the issue at all, can see memory being freed and it never exceeds ~600MB.
![image](https://github.com/microsoft/playwright/assets/36551116/13e2c93d-6c29-4129-bf0d-66a50d513a7a)

I did try testing with webkit, too, but it gives many intermittent errors before finally stopping at `playwright._impl._errors.Error: Page crashed`.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
