### ISSUE TITLE
[BUG] testInfo.config typing is not of the TestConfig class

### ISSUE THREAD

**Issue by jarydpeloton** [microsoft/playwright#28655]
### System info
- Playwright Version: v1.40.1
- Operating System: macOS 14.1.1
- Browser: Chromium

### Source code

The data available through `testInfo` in an automatic feature I am writing does not include a `config` key that conforms to the `TestConfig` class stated in the docs https://playwright.dev/docs/api/class-testinfo#test-info-config

Printing out the keys of the `config` object shows the following:
```
configFile,rootDir,forbidOnly,fullyParallel,globalSetup,globalTeardown,globalTimeout,grep,grepInvert,maxFailures,metadata,preserveOutput,reporter,reportSlowTests,quiet,projects,shard,updateSnapshots,version,workers,webServer
```

Specifically I am looking for `retries`, which is stated in my playwright.config.json file. If I edit the retries in that file then that is reflected when running the tests, so the test is definitely adhering to what I'm putting there 

Here is the automatic fixture being used. I also tried accessing the config through `testInfo` in a test and it also returned just the above keys
```
import { test as base } from '@playwright/test';

export const test = base.extend<{ setRetryTag: void }>({
  setRetryTag: [
    // eslint-disable-next-line no-empty-pattern
    async ({}, use: () => void, testInfo: any) => {
      console.log(`Config retries: ${Object.keys(testInfo.config).join()}`);
      await use();
    },
    { auto: true },
  ],
});
export { expect } from '@playwright/test';
```

**Steps**
- Add the above fixture, or log out testInfo.config from within a test

**Expected**

- The config matches the TestInfo typing and contains the `retries` key

**Actual**

- The config does not match the TestInfo typing and does not contain the `retries` key

**Comment by mxschmitt** [comment]
While this (documentation is wrong) is true, we consider the config type you can access via TestInfo.config a "resolved" config. So the retries option has already propagated down to the individual project entries.

you can access it via:

```ts
console.log(test.info().project.retries, testInfo.retry)
```

would that work for you?

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
