### ISSUE TITLE
[BUG] Playwright ct does not render <input> element

### ISSUE THREAD

**Issue by lukaskoeller** [microsoft/playwright#28666]
### System info
- Playwright Version: v1.40.1
- Operating System: macOS 14.2
- Browser: All

### Source code

`Input.spec.tsx`
```tsx
import { expect, test } from '@playwright/experimental-ct-react';

test.use({ viewport: { width: 500, height: 500 } });

test.describe('Input', () => {
  test('should be able to type text and have text as value', async ({
    mount,
  }) => {
    const TEST_STRING = 'Ein Apache in der Patsche!';
    const component = await mount(<input type="text" value={TEST_STRING} />);
    await expect(component).toHaveValue(TEST_STRING);
  });
});
```

Alternatively, please refer to the [reproduction repo](https://github.com/lukaskoeller/playwright-ct-input-reproduction).

**Steps**
- Run the test
- See error `expect.toHaveValue: Error: Not an input element`
- `<input />` element does not render at all.
- If you replace the mounted element, e.g. with a `<h2>Moin</h2>` it renders fine.

![Playwright Trace Viewer not rendering input element](https://github.com/microsoft/playwright/assets/10390627/1814892e-8f28-4af5-919c-1813aa65cec7)

**Expected**

Renders the `<input type="text" value={TEST_STRING} />` as any other html element.

**Actual**

Renders nothing at all.

** References **

- Similar issue: https://github.com/microsoft/playwright/issues/28566

**Comment by mxschmitt** [comment]
Could you try canary? https://playwright.dev/docs/canary-releases

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
