### ISSUE TITLE
[BUG] issues with electron app launch with executable path with exe file

### ISSUE THREAD

**Issue by aravinduser01** [microsoft/playwright#28669]
### System info
- Playwright Version: [v1.40]
- Operating System: [Windows 10]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

I tried to open an electron app exe file and able to launch it successfully.  But traces were showing blank. and video recording was also not working.

let electronApp: ElectronApplication;
        let firstWindow: Page;
        electronApp = await electron.launch({
            executablePath: 'C:\\Program Files (x86)\\test\\mysamplefile.exe',
            recordVideo: { dir: 'playwright-report',size: {
                width: 1280,
                height: 720,
              }, },
        });
        firstWindow = await electronApp.firstWindow();

![image](https://github.com/microsoft/playwright/assets/113510049/5fb9a5fb-9674-4de8-a40b-5ff852dd0d90)

```[tasklist]
### Tasks
```

**Comment by mxschmitt** [comment]
We unfortunately need a reproduction which we can run locally in order to debug issues like that. Feel free to re-file with a reproducible, thanks!

**Comment by Muskansa1n1** [comment]
Error: electron.launch: Process failed to launch!, 
I am getting this error when trying to launch the window with an executable path.

**Comment by gtrrz-victor** [comment]
I am having a similar behaviour. If I set `executablePath` to where electron is installed, it kind of works.
Something like:
```js
electron.launch({
                args: ['./dist/myapp/.webpack/main'], 
                executablePath: './node_modules/electron/dist/electron.exe',
            })
```

Side effect of that, inside my electron app:
```js
process.resourcesPath // Returns the resources relative to the electron bin instead of my app's resource folder
```
I am expecting something like: `......../dist/myapp/resources`
but getting: `node_modules/electron/dist/resources`

**Comment by gtrrz-victor** [comment]
Ignore my previous comment. On my side, the problem was caused by the FusesPlugin configuration I used to package the Electron app with electron-forge. Some of those flags make Playwright incapable of communicating with the app. As a result, you get an error like: 
`Error: electron.launch: Process failed to launch!, `

If any of the following flags are different, Playwright won't work:
```       
 new FusesPlugin({
            version: FuseVersion.V1,
            [FuseV1Options.RunAsNode]: true, //  false -> won't work
            [FuseV1Options.OnlyLoadAppFromAsar]: false, // true -> won't work
            [FuseV1Options.EnableNodeOptionsEnvironmentVariable]: true, // false -> won't work
            [FuseV1Options.EnableNodeCliInspectArguments]: true, // false -> won't work
            [FuseV1Options.EnableCookieEncryption]: false, // true -> won't work
        }),
```

**Comment by baparham** [comment]
For those arriving via search, at least with electron 39, I was able to roll back some of these settings and found the only one that seems to prevent playwright from connecting is `EnableNodeCliInspectArguments` needs to be `true`

Playwrights docs also mention this as the only requirement, so it's good that is aligned.
