### ISSUE TITLE
[BUG] (round 2) Cannot fill input of type "number"

### ISSUE THREAD

**Issue by Chromeshades** [microsoft/playwright#28671]
### System info
- Playwright Version: [v1.39.0]
- Operating System: [All]]
- Browser: [All]
- Other info:

### Source code

```    
        async editMxRecord( name: string, domain: string, priority: number): Promise<void> {
        await this.priorityField.fill(priority);
        await this.destinationField.fill(name.concat(".", domain));
        // await this.destinationField.fill(`${name}.${domain}`);
        await this.saveRecordButton.click();
    }
```

Error: 
Argument of type 'number' is not assignable to parameter of type 'string'.ts(2345)
(parameter) priority: number

**Expected**

You should be able to use string|number with fill()

**Actual**

Only string works:

```
playwright-core/types/types.d.ts
...
  fill(value: string, options?: {
...
```

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/16660.
