### ISSUE TITLE
[BUG] GET method does not populate request cookies from the context.

### ISSUE THREAD

**Issue by har16o** [microsoft/playwright#28684]
### System info
- Playwright Version: [v1.40.1]
- Operating System: [Windows 11]
- Browser: [Chromium]

Hello, I'm trying to execute a get method in my test and I expect the method to use cookies from context automatically, but it doesn't. Before calling the get method I explicitly check that the cookie exists in the context (and it does), but the method itself does not work as if the cookie does not exist. Am I doing something wrong or maybe I need to explicitly specify cookies in the request?

`await loginPage.openPage(routes.loginPage);
 await loginPage.login(registeredUser.email, registeredUser.password);
 await witrinaPage.waitForPageLoaded();
 await witrinaPage.checkThatElementIsVisible(witrinaPage.createWitrinaButton);
 await payPage.openPage(routes.payPage);
 
 const cookies = await page.context().cookies();
 const access_token = await cookies.find(c => c.name == 'access_token')?.value;
 console.log(await access_token);
 const response = await request.get(url, {
            headers: {
                "X-Account": "58",  
            },          
        });`

**Comment by mxschmitt** [comment]
Instead of using the `request` fixture which is [not connected, aka. isolated](https://playwright.dev/docs/test-fixtures#built-in-fixtures) to the context you should use `page.context().request().get` and then it should work.

**Comment by har16o** [comment]
@mxschmitt thanks, that works!
