### ISSUE TITLE
[BUG] `toContainText` should work with `<script type="application/ld+json">`

### ISSUE THREAD

**Issue by stefanprobst** [microsoft/playwright#28688]
### System info
- Playwright Version: 1.40.1
- Operating System: Ubuntu 22.04
- Browser: All
- Other info:

### Source code

https://github.com/stefanprobst/issue-playwright-jsonld

**Steps**
- clone [repo](https://github.com/stefanprobst/issue-playwright-jsonld) and run `pnpm install`
- run tests with `pnpm run test`

**Expected**

using `toContainText` or `toHaveText` with `<script type="application/ld+json">` should work

**Actual**

currently, [this assertion](https://github.com/stefanprobst/issue-playwright-jsonld/blob/main/tests/app.test.ts#L17) fails, because `toContainText` returns an empty string

interestingly, it *does* work with the `useInnerText` option of `toContainText`, see [this assertion](https://github.com/stefanprobst/issue-playwright-jsonld/blob/main/tests/app.test.ts#L13-L15) -- not sure if this is actually expected behavior or a bug?

**Comment by yury-s** [comment]
In the spirit of testing [user-visible](https://playwright.dev/docs/best-practices#test-user-visible-behavior) behavior, `toHaveText` assertion is not expected to work with `script` tags. It inadvertently works with userInnerText option today but we discourage such use cases and don't support them.
