### ISSUE TITLE
[Feature] probe for tests with .only without running any tests

### ISSUE THREAD

**Issue by mstepin** [microsoft/playwright#28689]
The `--forbid-only` feature is great. However...

When our tests run in CI we first spin up a full stack locally which serves as the target test environment. This can take from 5 to 10 minutes to complete.

If a developer/tester accidentally leaves `.only` in a test, we do not find out that this is the case until the tests are executed. By this point we have spent CI resources and time spinning up the stack.

Would it be possible to leverage the already existing code that you use to detect `.only`, and have a command line option that can be run, which eventually results in a non-zero exit code if it fails, without yet attempting to run any tests.

That way we can:
1. run the `.only` scan.
  -> if fails: break off the tests here
  -> if pass: continue with the next command in CI
2. spin up the stack
3. Execute the tests as normal

possible suggestion `npx playwright test --check-forbid-only` or similar

**Comment by yury-s** [comment]
This already works today if you use [project dependencies](https://playwright.dev/docs/test-global-setup-teardown#option-1-project-dependencies), playwright will only run necessary dependencies and it will perform forbid-only check before running any tests. In case of [global setup](https://playwright.dev/docs/test-global-setup-teardown#option-2-configure-globalsetup-and-globalteardown) you could even generate tests in your global setup script, so we cannot make it work. But if you must use global setup, as a mitigation you can run `npx playwright test --list --forbid-only` before running tests to cheaply ensure there is no stray `.only`.

**Comment by mstepin** [comment]
For those looking to do a similar thing (FYI):
The first 2 suggestions from @yury-s above were not really viable options for us. 
running `npx playwright test --list --forbid-only` did exactly what we needed and exits with a non-zero exit code.
we did `npm test -- --list --forbid-only 1>/dev/null || handleDotOnlyError` (bash) So that it suppresses the output if all is good, otherwise run a function to handle the error with whichever additional output we want.
