### ISSUE TITLE
How can I ignore domain in HAR files? [Feature]

### ISSUE THREAD

**Issue by dalv-happy** [microsoft/playwright#28693]
Hi!
When I develop tests, I do it on a dev server with a DEV domain, since there is debugging. When my tests are ready, they are run in CI on another TESTING domain. But the tests fail because the domain of the dev server was written in the HAR files. How can I ignore the domain when writing and reading HAR files?

**Comment by yury-s** [comment]
`routeFromHAR` takes [`url`](https://playwright.dev/docs/api/class-browsercontext#browser-context-route-from-har-option-url) parameter which you can use to restrict which URLs are routed from the har. See examples from [our guide](https://playwright.dev/docs/mock#recording-a-har-file). Will that work for you?

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
