### ISSUE TITLE
[BUG] Copy from clipboard on ubuntu doesnt work

### ISSUE THREAD

**Issue by xsoft7** [microsoft/playwright#28691]
### System info
- Playwright Version: [v1.39]
- Operating System: [Ubuntu 20, macOS 143. etc.]
- Browser: [Chromium]
- Other info: Python 3.12 +pytest

### Source code
```
   def copy_from_clipboard(self) -> str:
        if os_type == 'posix':
            keyboard = 'Meta'
        else:
            keyboard = 'Control'
        self.element.click()
        self.element.focus()
        self.element.page.keyboard.press(f"{keyboard}+A")
        self.element.page.keyboard.press(f"{keyboard}+C")
        data = self.element.page.evaluate_handle('navigator.clipboard.readText()')
        return data.json_value()
```
The pytest run on CI (ubuntu):

```
text_value = self.saml_page.saml_logout_url_textbox().copy_from_clipboard()
>       assert fields[
                   'samlLoginUrl'] == text_value, f"Expected to be {fields['samlLoginUrl']} but received {text_value}"
E       AssertionError: Expected to be http://localhost.com/ but received 
E       assert 'http://localhost.com/' == ''
E         + http://localhost.com/
tests/authentication/saml_ui_test.py:42: AssertionError
=========================== short test summary info ============================
FAILED tests/authentication/saml_ui_test.py::TestSamlUi::test_enter_saml_fields_verified_they_saved[chromium] - AssertionError: Expected to be http://localhost.com/ but received 
=================== 1 failed, 4 passed in 175.74s (0:02:55) ====================

```

**Steps**
I have this code snippet, which basically copies to clipboard and then return a value.

In a local machine, Macos 14.3 (Apple M1) , it works as expected, and the assertion passes

I tried to do "if/else" and to change the key's to "Control". still doesn't work.

* of course I've enabled the context with permissions (and as said above, works on Mac)

Expected :(works as expected in Mac)
 assert 'http://localhost.com/' == 'http://localhost.com/'

Actual (In linux)

 assert 'http://localhost.com/' == ''

**Comment by yury-s** [comment]
Did you grant `clipboard-read` permission to the page? Can you share complete test please? Support for this varies across browsers/platforms as reflected by [this test](https://github.com/microsoft/playwright/blob/6b178d22e23d38a48fd9a805acef473c3a405b0e/tests/library/permissions.spec.ts#L156-L158).

**Comment by xsoft7** [comment]
> Did you grant `clipboard-read` permission to the page? Can you share complete test please? Support for this varies across browsers/platforms as reflected by [this test](https://github.com/microsoft/playwright/blob/6b178d22e23d38a48fd9a805acef473c3a405b0e/tests/library/permissions.spec.ts#L156-L158).

Hey,

Yes, of course. as noted above, in local computing env (MacOs) it works perfectly.

I cant really post the code here (as its too big), but here is also the attached conftest.py that uses the code (and works in macos..)

`@pytest.fixture(scope="function")
def context(
        browser: Browser, browser_context_args: Dict, browser_name, video_path, request
) -> Generator[BrowserContext, None, None]:
    context = browser.new_context(**browser_context_args)
    context.grant_permissions(["clipboard-read", "clipboard-write"])
    current_failed_tests = request.session.testsfailed
    context.tracing.start(screenshots=True, snapshots=True, sources=True)
    yield context
    current_video_name = context.current_video_name
    current_video_path = os.path.join(video_path, current_video_name)
    file_name = f'{request.session.items[0].name}_{browser_name}{datetime.now().strftime("%d_%m_%Y_%H_%M_%S")}'
    updated_video_path = os.path.join(video_path,
                                      f'{file_name}.webm')
    context.tracing.stop(path=f'./debug/traces/trace_{file_name}.zip')
    context.close()
    os.rename(current_video_path, updated_video_path)`

**Comment by yury-s** [comment]
Try running with latest (1.40) playwright and if it still fails please share a minimal self-contained repro that we could run locally.

The following example works just fine in Chromium in our 1.40.0 docker image:

```js
import { test, expect } from '@playwright/test';

test('should select all and copy', async ({ page }) => {
  await page.goto('https://example.com');
  await page.setContent('<input></input>');
  await page.context().grantPermissions(['clipboard-read']);
  const element = page.locator('input');
  await element.fill('some text');
  await element.click();
  await element.focus();
  await page.keyboard.press('Control+A');
  await page.keyboard.press('Control+C');
  const text = await page.evaluate(() => navigator.clipboard.readText());
  expect(text).toBe('some text');
});
```

**Comment by xsoft7** [comment]
Hi. Thanks for the reply. I will update, as i cannot quickly change  the version because we've reached the download limit in docker repo, and now the versions are in our local repo.

I will need to compile a new version , and will update ASAP.

Thanks.

**Comment by yury-s** [comment]
We need more information to act on this report. If it still doesn't work, please file a new one and link to this issue when you get back to it!
