### ISSUE TITLE
[BUG] addInitScript doesn't work on browser restart with last session tabs

### ISSUE THREAD

**Issue by koalex** [microsoft/playwright#28692]
### System info
- Playwright Core Version: 1.40.1
- Operating System: MacOS ARM Ventura 13.1 (+ Windows tested)
- Browser: All
- Other info:

```js
import { existsSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { chromium } from 'playwright-core';

main();

async function main() {
  const userDataDir = join(tmpdir(), 'playwrightUserDataDir');

  if (!existsSync(userDataDir)) mkdirSync(userDataDir);

  const chromeCtx = await chromium.launchPersistentContext(
    userDataDir,
    {
      headless: false,
      executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
      args: [
        '--no-first-run',
        '--restore-last-session',
      ],
    }
  );

  chromeCtx.on('page', (page) => {
    page.addInitScript(`;Math.random = () => 123;`);
    page.evaluate(`;Math.random = () => 123;`);
  });

  await chromeCtx.addInitScript(`;Math.random = () => 123;`);
}
```

[Repository](https://github.com/koalex/playwright-bug-example) with example

**Steps**
- `npm start`
- in browser open any page
- close browser (script)
- open browser again (`npm start`)
- open **console** in **DevTools**
- type in console `Math.random();`

**Expected**
123

**Actual**
0.37760765247169414 // any random number

But if I will open new tab or reload current then initial script evaluate correctly and `Math.random()` will return 123.

**Comment by yury-s** [comment]
Supporting `--restore-last-session` is out of scope for Playwright. Use custom browser args at your own risk, as some of them may break Playwright functionality.
