### ISSUE TITLE
[BUG] PDFs not loading in UI Mode

### ISSUE THREAD

**Issue by aarahmanqa** [microsoft/playwright#28694]
### System info
- Playwright Version: [v1.40.1]
- Operating System: [macOS 13.6]
- Browser: [Chromium]
- Other info:

### Source code

Github repo : https://github.com/aarahmanqa/PlaywrightPDF (`main` branch)

**Problem Statement:**
Am trying to do Visual Comparison on PDFs.

**What did I do?**
I made a html page with an iframe. In Playwright test, I opened that html page and just modified the src attibute of iframe using page.evaluate.

**What is the issue?**
The test case is working fine without UI mode. In UI Mode, the PDFs are not loading making it fail with blank screen.

**Steps**
- npx playwright test --ui
- Run the "Same PDF Comparison" test case

**Expected**

The image comparison test case should pass.

**Actual**

The test case is failing with actual image as blank screen only in UI mode.

![image](https://github.com/microsoft/playwright/assets/6194278/b1093fb6-a73f-439c-b49d-1e9b55d1b2c9)

**Comment by yury-s** [comment]
The example you linked fails to install for me, can you fix that? Also I noticed that the test starts chromium in headless mode while PDFs are only rendered in headed, so this is not expected to work even without --ui mode. Another problem is that waitForTimeout may be racy.

If you want to compare PDFs then using something like PDF.js for rendering could provide more consistent results.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
