### ISSUE TITLE
[BUG] Playwright warm up time for just opening browser is nearly 20 seconds 

### ISSUE THREAD

**Issue by nson03101993** [microsoft/playwright#28707]
### System info
- Playwright Version: [v1.40.1]
- Operating System: [Windows 10]
- Browser: Chrome, Edge, Firefox, Webkit (newest support version of Playwright)
- Other info:

**Steps**
- Run test case with Playwright extension in Vs Code

**Expected**

Warm-up time for starting browser should be minimal (1-4 seconds) same as previous version of Playwright

**Actual**

It takes nearly 20 seconds just to open browser. This is crazily long (see attached videos)

https://github.com/microsoft/playwright/assets/46323783/dea5e9f9-3e9c-4315-a2dd-894500db6f75

**Comment by yury-s** [comment]
Since this is something you are observing across all browsers, it's likely has something to do with your machine. Can you look at the task manager and see what is eating CPU? Do you have an antivirus running on the machine? What's the minimal example where this occurs?

**Comment by nnson0310** [comment]
No. The environment I run has no antivirus, I run on the same machine and no task are eating the CPU or else. Okay, let me try more and confirm back.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue if you have more information indicating that this is a bug in Playwright rather than an issue with your machine.
