### ISSUE TITLE
[BUG] MaxListenersExceededWarning: Possible EventEmitter - broken node 20

### ISSUE THREAD

**Issue by boldt** [microsoft/playwright#28713]
### System info

- Playwright Version: v1.40.0
- Operating System: Docker Images: Docker images created after this commit (https://github.com/microsoft/playwright/commit/841bb92049ba6030f81ce6a1fa792012340cee95) are affected, e.g.
    - `mcr.microsoft.com/playwright:v1.40.0@sha256:9dcc823ba14151eecb81eedb3a0abcb4fac942ae7fa9c9f96fdfcc7f5db9d239`

### Issue

The docker images create the following errors. when you run `npm` behind a corporate proxy:

![image](https://github.com/microsoft/playwright/assets/750793/ed8dbd47-2a34-436a-ad1f-f0e2cffc2d6e)

This issue is known and fixed in node 20:

* https://github.com/npm/cli/issues/6763
* https://github.com/nodejs/node/issues/50376

### Solution

Please update to the newest node 20 version in the docker image, were this issue is fixed.

[EDIT] Seems to work with the current image `mcr.microsoft.com/playwright:v1.40.1`

**Comment by yury-s** [comment]
This should already be fixed in the future releases as we pull latest Node.js 20.x version when building the images.

**Comment by k1w1m8** [comment]
I tried doing a workaround for this,

```
npm config set proxy $HTTP_PROXY
npm config set https-proxy $HTTP_PROXY
```

I found that NO_PROXY still works as usual.

I wanted to use 1.40.1, but seems it is only partially released, npm and docker is available, but not java / maven?
