### ISSUE TITLE
[BUG] CSS imports in CommonJS cause Playwright to throw SyntaxErrors when tests are executed

### ISSUE THREAD

**Issue by lastnamevega** [microsoft/playwright#28719]
### System info
- Playwright Version: v1.40.1
- Operating System: macOS 13.5.1
- Browser: All
- Other info: this appears to be a partial defect in https://github.com/microsoft/playwright/issues/24580 / https://github.com/microsoft/playwright/pull/26626. The removal of CSS imports is wrapped in an `!isModule` `if`. Should CSS imports instead be removed unconditionally?

### Source code

The following JavaScript code results in a `Syntax Error` around the `./styles.css` `require` when executed:

```js
const { test } = require("@playwright/test");
const styles = require("./styles.css");

test("should work", async ({ page }) => {
  await page.goto("https://google.com");
});
```

Meanwhile, this JavaScript executes successfully:

```js
import { test } from "@playwright/test";
import styles from "./styles.css";

test("should work", async ({ page }) => {
  await page.goto("https://google.com");
});
```

Similarly, the latter code sample executes successfully when run as TypeScript.

**Steps**
- Run the CommonJS code sample above (using `npx playwright test` or similar).

**Expected**

The test executes successfully, similar to when running the second code sample above as either JavaScript or TypeScript:

```sh
$ npx playwright test test.spec.ts

Running 1 test using 1 worker

  ✓  1 test.spec.ts:4:5 › should work (1.3s)

  1 passed (1.9s)
```

**Actual**

A `SyntaxError` is thrown and no tests are found:

```sh
$ npx playwright test test.spec.js
SyntaxError: Unexpected token '{'

   at test.spec.js:2

  1 | const { test } = require("@playwright/test");
> 2 | const styles = require("./styles.css");
    |                ^
  3 |
  4 | test("should work", async ({ page }) => {
  5 |   await page.goto("https://google.com");

    at Object.<anonymous> (~/playwright-css-test/test.spec.js:2:16)
Error: No tests found
```

**Comment by yury-s** [comment]
Requiring css is not supported. Using esm import for css files is quite common in the bundlers, so we made a special case for that. There are no plans to do this for require.
