### ISSUE TITLE
[BUG] Multiple Reporters Not Working Correctly

### ISSUE THREAD

**Issue by cod3rLP** [microsoft/playwright#28718]
### System info
- Playwright Version: [v1.40.1]
- Operating System: [macOS 14.1.2]
- Browser: [Chromium]
- Other info: VSCode with Playwright extension [v1.0.20]

### Source code

playwright.config.ts file snippet:
```
const config: PlaywrightTestConfig = {
  reporter: [['html'], ['./graphite-reporter.ts']],
  };
```

graphite-reporter.ts file:
```import type { Reporter, TestCase, TestResult } from '@playwright/test/reporter';
import net from 'net';
class CustomReporter implements Reporter {
  private socket: net.Socket;
  private graphiteHost = ‘graphite URL goes here';
  private graphitePort = 'port number goes here';
  private metricList: string[] = [];
  constructor() {
    this.socket = net.createConnection(this.graphitePort, this.graphiteHost);
  }
  onTestEnd(test: TestCase, result: TestResult) {
    const metricName = `hosted-graphite-key-goes-here.playwright.${test.title}.${result.status}`;
    const metricValue = 1;
    const timestamp = Math.floor(Date.now() / 1000);
    this.metricList.push(`${metricName} ${metricValue} ${timestamp}`);
  }
  onEnd() {
    this.metricList.forEach((metric) => {
      this.sendMetric(metric);
    });
    // Close the connection
    this.socket.end();
  }
  private sendMetric(metric: string) {
    this.socket.write(`${metric}\n`);
  }
}
export default CustomReporter;
```

**Steps**
- Run any e2e test. Can be passing/failing, does not matter.

**Expected**
- Results show up under the Test Results tab in VS Code
- Metrics send to Hosted Graphite (as configured in the graphite-reporter.ts file)

**Actual**
- When using multiple reporters typed as `reporter: [['html'], ['./graphite-reporter.ts']],` in the playwright config file, the Test Results tab is now blank in VS Code. 
![image](https://github.com/microsoft/playwright/assets/154354911/e00e75a2-400f-4c87-a942-3ba50a3e0ed8)
- The metrics do upload correctly from the graphite-reporter file as expected.

If it's running in Bitbucket Pipelines, normally using `reporter: 'html',` as the only reporter will give us details about the test results. Listing both reporters omits the details and looks like this, which is not helpful for anyone seeing why their build failed
![image](https://github.com/microsoft/playwright/assets/154354911/1d49c50d-a016-438e-98ff-720780ab07a2)

**Comment by cod3rLP** [comment]
[This may actually be the same issue](https://github.com/microsoft/playwright/issues/18945#issuecomment-1322734486) I'm describing. I will try the suggested 'fixes'.

**Comment by yury-s** [comment]
Please try that. If it doesn't work, please provide a self-contained minimal repro that we could run locally. I tried with the reporter you mentioned above, but I could still see the same output in the console as before.

**Comment by cod3rLP** [comment]
```
printsToStdio() {
    return false;
  }
```

this worked. thank you!
