### ISSUE TITLE
[BUG] .goto() not appending string to the end of baseURL

### ISSUE THREAD

**Issue by CalvinGocMMLLC** [microsoft/playwright#28715]
### System info
- Playwright Version: [v1.40]
- Operating System: macOS14.2
- Browser: All
- Other info:
When calling `Browser.newContext()` in a fixture file it doesn't seem to apply the config supplied in the config file
### Source code\
Playwright config file
```
    use: {
        baseURL: getTestHost(),
        acceptDownloads: true
    },
```
Fixture file
```
    const browserContextOptions: BrowserContextOptions = createBrowserContextOptions(contextOptions)
    const context = await browser.newContext(browserContextOptions)


export function createBrowserContextOptions(contextOptions: UserContext = {}): BrowserContextOptions {
    const options: BrowserContextOptions = {}
    if (contextOptions.device) {
        _.assign(options, { ...devices[contextOptions.device] })
    }
    return options
}
```
test file
```
    public async goToRandomRoom(): Promise<void> {
        await this.baseLocator.page().goto("/randomroom")
    }
```
[We will only be able to work on the issues that we can reproduce.]

[Please provide a self-contained example in a form of a snippet, archive or a repository.]

[Repro scenario can't be large or have external dependencies.]

**Steps**
- run test with a page.goto("/some_page") call

**Expected**

Appends the string added in the .goto function to the end of the baseURL that is in the config file

**Actual**

attempts to navigate directly to the "/some_page" string and fails with invalid url

**Comment by yury-s** [comment]
`getTestHost()` probably returns an empty string. If it's not the case please provide a self-contained minimal repro that we could run locally.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue and provide a repro if it doesn't work.
