### ISSUE TITLE
[QUESTION] Is Playwright using locator strategies in waterfall to identify elements?

### ISSUE THREAD

**Issue by CosminGramada** [microsoft/playwright#28717]
### System info
- Playwright Version: microsoftcr/playwright:v1.38.0-jammy
- Operating System: Playwright Docker image
- Browser: Chromium
- Other info: Pipeline running headless

We have a couple of flaky tests with the error below:

```
Error: locator.waitFor: Error: strict mode violation: locator('app-filter-side-drawer').locator('mat-select[formcontrolname=\'dimension\'] .mat-mdc-select-arrow') resolved to 2 elements:
        1) <div class="mat-mdc-select-arrow ng-tns-c3393473648-7…>…</div> aka locator('#mat-select-16 div').nth(3)
        2) <div class="mat-mdc-select-arrow ng-tns-c3393473648-8…>…</div> aka getByRole('combobox', { name: 'Dimension' }).locator('div').nth(3)
    =========================== logs ===========================
    waiting for locator('app-filter-side-drawer').locator('mat-select[formcontrolname=\'dimension\'] .mat-mdc-select-arrow')
    ============================================================
```

Before going and investigating/changing locators, I would like to clarify the following thing:
- does Playwright try to identify elements on the page through multiple strategies? e.g. if `app-filter-side-drawer mat-select[formcontrolname='dimension'] .mat-mdc-select-arrow` fails will it try to identify through `getByRole` as well?

Asking this because we're not currently `getByRole` anywhere in our code base.

**Comment by yury-s** [comment]
The underlying implementation of locator() and getByRole() is the same. Both of them are strict, you can read more about strictness here: https://playwright.dev/docs/locators#strictness

**Comment by CosminGramada** [comment]
@yury-s 
Thanks for the reply.

I'm familiar with the fact that locator strategies are strict in Playwright. 
What I'm not familiar with and I fail to understand is why and how is Playwright trying to identify an element in DOM using `getByRole` when I provide a `locator`?

I do not have anywhere in my code an element identified using `getByRole` so I'm not sure where 2) in the error is coming from and how to interpret it (considering that 1) in the error is using `locator`).

Is it just to serve as an example for the identification of elements maybe?

I cannot reproduce these error while running locally, only in CI. So as a follow question if I may, is there a way to bind to this strict mode violation error so that I can print the HTML and ask the developers for help in investigation?
