### ISSUE TITLE
[BUG] Getting "No X11 DISPLAY variable was set, but this program performed an operation which requires it."

### ISSUE THREAD

**Issue by SergeyVinickiy** [microsoft/playwright#28711]
### System info
- Playwright Version: [v1.40]
- Operating System: [ Ubuntu 20.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code
java code

**Steps**
I want to run the code in a container. 

My docker file now looks like this:

```dockerfile
FROM mcr.microsoft.com/playwright:v1.40.0-jammy

# Update packages and install necessary tools
RUN apt-get update && \
    apt-get install -y wget openjdk-11-jdk

# Set up Maven version 3.9.6
ENV MAVEN_VERSION=3.9.6
ENV MAVEN_HOME=/opt/maven

# Download and install Maven
RUN wget -q "https://dlcdn.apache.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz" -O /tmp/apache-maven.tar.gz && \
    tar xf /tmp/apache-maven.tar.gz -C /opt/ && \
    ln -s /opt/apache-maven-$MAVEN_VERSION $MAVEN_HOME && \
    rm -f /tmp/apache-maven.tar.gz

# Add Maven binaries to PATH
ENV PATH=$MAVEN_HOME/bin:$PATH

# Copy your settings.xml file
COPY settings.xml $MAVEN_HOME/conf/settings.xml


# Verify Maven installation
RUN mvn -version


WORKDIR /app

COPY . .

CMD ["mvn", "clean", "compile", "test"]`

```

**Expected**

Test will run

**Actual**

Getting "No X11 DISPLAY variable was set, but this program performed an operation which requires it."

**Comment by yury-s** [comment]
Can you share the test which is failing? It looks like you are trying to launch a browser in headed mode when there is no X server on the machine, you should run in headless mode to avoid that.

**Comment by SergeyVinickiy** [comment]
I have this place where it sets headless param, but it is set to "true" so should be headless i believe
![image](https://github.com/microsoft/playwright/assets/37349791/7a8f0553-c7c0-41f8-a0a1-76d84912a717)

**Comment by SergeyVinickiy** [comment]
Maybe a more general question - should I do something special to run the test in docker? It is headless now and running fine on local machine

**Comment by yury-s** [comment]
> Maybe a more general question - should I do something special to run the test in docker?

No special actions are required, it should just run as long as all dependencies are installed (which is the case when you use our docker image).

Could it be that your java program that calls Playwright tries to show some UI? This would require an X server. You can try to mitigate that by running the program under `xvfb`.

**Comment by SergeyVinickiy** [comment]
I've been attempting to add Xvfb to my Docker setup all day without success.
 Could you please provide an example of how to do it?
I haven't seen tries in the code.

**Comment by yury-s** [comment]
> Could you please provide an example of how to do it?

Sure, our docker image already contains xvfb, so you can just run something like this:

```bash
xvfb-run mvn compile exec:java -Dexec.mainClass=org.example.PageScreenshot
```

But like I said you don't need it when running playwright in headless mode. What about this question above:
"Could it be that your java program that calls Playwright tries to show some UI?"

**Comment by SergeyVinickiy** [comment]
Thank you. When tried to run with xvfb got error 
![image](https://github.com/microsoft/playwright/assets/37349791/594af1a7-cc38-437c-a05e-1bb7ddac2820)

**Comment by SergeyVinickiy** [comment]
I have also good news! I've identified a spot that's likely calling the X server. After commenting it out, I managed to run the container! This part wasn't added by me, so I'm hoping that by commenting it, nothing else will break.

![image](https://github.com/microsoft/playwright/assets/37349791/e16d3fbc-8efb-4812-af1c-f28dfdfe6f67)

**Comment by yury-s** [comment]
Closing per the comment above, feel free to open a new issue if it still doesn't work.
