### ISSUE TITLE
[BUG] Seeing Loading the Tests on Playwright UI though the tests are mentioned in the proper folder

### ISSUE THREAD

**Issue by vinaybudihal** [microsoft/playwright#28720]
### System info
- Playwright Version: [1.40.1]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

![image](https://github.com/microsoft/playwright/assets/131458526/04abfe2e-cf52-4a90-a2f9-e2f71aeeb334)

Config File:

![image](https://github.com/microsoft/playwright/assets/131458526/a92a777d-83e5-46ea-83b1-a6aa3af3ec4d)

Prerequisites:

- Playwright is hosted in Cloud and hosted it Kubernetes cluster (Trying to Open Playwright UI as an Application)

**Steps**
- Open the playwright UI
- Observe the UI

**Expected**
All Tests should be loaded for execution

**Actual**

Tests are not loaded and seeing always 'Loading...' (Refer the Image pasted)

**Comment by yury-s** [comment]
Can you provide more details on how you run playwright and how we can reproduce it? Can it be reproduced with a docker container?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
