### ISSUE TITLE
Grouping tests using annotations results in command error

### ISSUE THREAD

**Issue by talk2sreenu** [microsoft/playwright#28724]
While running group tests in Visual Studio terminal as per the documentation in Annotations sections, I have received below error messages.
Command : `npx playwright test myLocalTests.spec.ts --grep @smokeTest`
Error: `error: option '-g, --grep <grep>' argument missing`

Command : `npx playwright test myLocalTests.spec.ts --grep-invert @smokeTest`
Error: `error: option '-gv, --grep-invert <grep>' argument missing`

Whereas enclosing the tag value within quotes triggered the tests as expected. Not sure if it needs to be updated in the docs or requires a fix, so submitting an issue for the recommendations. If it is as simple as updating the docs, I can contribute a PR to address this.

**Comment by yury-s** [comment]
Which operating system are you on? Perhaps the terminal treats ` @smokeTest` as a variable reference and replaces it with its value which is empty?

**Comment by talk2sreenu** [comment]
I am on Windows 11. Looks like you are right. The terminal considers any value followed by '@' as variable & returns error. Tried with below commands & works fine. 
`npx playwright test myLocalTests.spec.ts --grep smokeTest`
`npx playwright test myLocalTests.spec.ts --g smokeTest`

So it needs to be updated in docs as it is kind of misleading?

**Comment by iamsdbhosale** [comment]
npx playwright test myLocalTests.spec.ts --grep smokeTest
Excellent Solution. It works for me.
