### ISSUE TITLE
[NEED INFO] Playwright is not making calls to the backend endpoints

### ISSUE THREAD

**Issue by nativanando** [microsoft/playwright#28738]
Hi guys. I'm trying to play with playwright in order to start using it on my app but I'm not able to make calls to my backend. Basically the endpoints that I call are returning status -1 with an unknown-x content-type and the body response shows _"Response body is not available for this request."_ 

![Screenshot 2023-12-20 at 10 06 43](https://github.com/microsoft/playwright/assets/13206713/92c55d88-3b0e-40ff-b577-59382bccf422)

Here is my playwright config file as well:

```javascript
module.exports = defineConfig({
  testDir: './e2e-pw',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    baseURL: 'http://127.0.0.1:3000',
    trace: 'on-first-retry'
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] }
    },

    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] }
    },

    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] }
    }
})
```

I have checked my logs and the request is not even reaching the backend. Do you guys have any idea of what is happening here? Since I'm new using the tool was wondering if there is a configuration missing.

### System info
- Playwright Version: [v1.40.1]
- Operating System: [macOS]
- Browser: [All, Chromium, Firefox, WebKit]

**Comment by yury-s** [comment]
This doesn't sound like a bug in playwright, if you think it is, please file a new issue with a repro that we could run locally. You can use our [community resources](https://playwright.dev/community/welcome#community-discord) to ask for general help.
