### ISSUE TITLE
[BUG]Although the number of tests is high, the tests always run with 1 worker when the workers parameter is defined in playwright.config

### ISSUE THREAD

**Issue by yusufozturk-turib** [microsoft/playwright#28735]
### System info
- Playwright Version: 1.40.1
- Operating System: Windows 10
- Browser: Chrome

**Playwright.config.ts**

```
import { devices } from "@playwright/test"
import { configEnv } from './config/config'
import { defineConfig } from '@playwright/test'

export default defineConfig({
  workers: 5,
  timeout: 50 * 1000,
  expect: {
    timeout: 20 * 1000
  },
  reporter: process.env.CI ? 'blob' : [['html', { outputFolder: 'report' }]],
  use: {
    headless: true,
    baseURL: configEnv.baseURL,
    actionTimeout: 20000,
    navigationTimeout: 20000,
    ignoreHTTPSErrors: true,
  },
  projects: [
    {
      name: 'setup',
      testMatch: /login.spec\.ts/,
    },
    {

      name: "chrome",
      use: {
        ...devices["Desktop Chrome"],
        launchOptions: {
          args: ["--disable-web-security", "--no-sandbox"],

        },
        storageState: 'fixtures/asset/state.json'
      },
      dependencies: ['setup'],
    }
  ],
});
```
pacakge.json;

```
{
  "name": "bs_project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "api:staging": "cross-env ENV=8 PARAM=api npx playwright test --grep-invert login.spec.ts"
  
  },
  "keywords": [],
  "author": "test_user",
  "license": "ISC",
  "devDependencies": {
    "@playwright/test": "^1.40.1"
  },
  "dependencies": {
    "@faker-js/faker": "^8.0.2",
    "@openapitools/openapi-generator-cli": "^2.7.0",
    "axios": "^1.4.0",
    "cross-env": "^7.0.3",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^4.2.0"
  }
}
```

I have 2 spec files, one for setup and the other one for test. In my spec file for test, I have 110 test steps. If I define fullyParallel:true mode and not define workers(e.g workers: 5) parameter in playwright.config, it automatically run 110 tests with 8 workers. 

But when I remove fullParallel from the config and just say workers:5, it continues to run with 1 worker.When workers is defined, it always runs 110 tests with 1 worker.Why does it always run with 1 worker when workers parameter is defined and the number of tests is high. Is there a bug here?

It seems like I have never encountered such a thing before.If it is not a bug, how can I run with more workers by defining workers parameter without the need to use fullParallel mode?

**Comment by gofr** [comment]
This is exactly what [`fullyParallel`](https://playwright.dev/docs/api/class-testproject#test-project-fully-parallel) is for:

> By default, **test files** are run in parallel. Tests in a single file are run in order, in the same worker process.

With `fullyParallel: false`, tests within a spec are not parallelized. You'll be able to use, at most, as many workers as there are specs. That's *one*, in your case, if I understood that correctly. With `fullyParallel: true`, the tests within the same spec can also be parallelized across workers, so you can have more of them.

It is possible to both set `fullyParallel: true` and set `workers` to a specific number to use a specific number of parallel workers.

**Comment by yury-s** [comment]
As mentioned in the previous comment, this is working as intended. `--workers` specifies max number of test workers playwright can spawn. By default tests from the same file run on one worker and override that with fullyParallel or by splitting the tests into multiple files. You can find more information about how Playwright uses workers to parallelize execution on [this page](https://playwright.dev/docs/test-parallel#introduction).
