### ISSUE TITLE
[BUG] Type of BrowserContextOptions['storageState'] might a bit too harsh

### ISSUE THREAD

**Issue by justnewbee** [microsoft/playwright#28731]
### System info
- Playwright Version: v1.40.1
- Operating System: No need
- Browser: No need
- Other info: Using TS 5.3.3

### Source code

In `playwright.config.ts` I want to setup context for all test cases, this is part of it:

```ts
import {
  defineConfig
} from '@playwright/test';

export default defineConfig({
  use: {
    baseURL: 'http://127.0.0.1:3000',
    contextOptions: {
      storageState: {
        cookies: [{
          name: 'cookie_name',
          value: 'cookie_value',
          domain: '127.0.0.1',
          path: '/'
        }]
      }
    }
  }
});
```
 
Although it runs well, TS is NOT happy with it.

It is because the definition of `BrowserContextOptions['storageState']` is too harsh:

```ts
storageState?: string | {
    cookies: Array<{
      name: string;
      value: string;
      domain: string;
      path: string;
      expires: number;
      httpOnly: boolean;
      secure: boolean;
      sameSite: "Strict"|"Lax"|"None";
    }>;
    origins: Array<{
      origin: string;
      localStorage: Array<{
        name: string;
        value: string;
      }>;
    }>;
  };
```

I think both `cookies` and `origins` can be optional, as I did not set `origins` in my configuration, but it worked in JS.

As for Cookie, only `name`、`value`、`domain` might be required, others are optional.

So the type definition can be:

```ts
storageState?: string | {
    cookies?: Array<{
      name: string;
      value: string;
      domain: string;
      path?: string;
      expires?: number;
      httpOnly?: boolean;
      secure?: boolean;
      sameSite?: "Strict"|"Lax"|"None";
    }>;
    origins?: Array<{
      origin: string;
      localStorage: Array<{
        name: string;
        value: string;
      }>;
    }>;
  };
```

**Steps**

Just check inline error hint on IDE, will see `TS2769: No overload matches this call.`

**Expected**

TS be happy.

**Actual**

TS NOT happy.

**Comment by justnewbee** [comment]
Somehow I cannot upload image, but the problem is quite easy to reproduce.

**Comment by yury-s** [comment]
This is working as intended. The field is not expected to be constructed manually, you can use [`context.storageState()`](https://playwright.dev/docs/api/class-browsercontext#browser-context-storage-state) to get value of right type. You can add cookies one by one manually using more lax [addCookie](https://playwright.dev/docs/api/class-browsercontext#browser-context-add-cookies) method.
