### ISSUE TITLE
[NEED INFO]: Running component tests with playwright v1.40 using docker image on Mac

### ISSUE THREAD

**Issue by bharat7gupta** [microsoft/playwright#28736]
**Context:**
- GOOD Playwright Version: [1.30]
- BAD Playwright Version: [1.40]
- Operating System: [Mac]
- Extra: [Mac M1]

**Describe the bug**

I am using playwright v1.30 to run component tests on Mac using docker image. I had set `PLAYWRIGHT_DOCKER` to `"true"` as a flag for the integration between playwright and docker (as mentioned in this [PR description](https://github.com/microsoft/playwright/pull/17377)). I am currently trying to upgrade to v1.40 but I don't see that flag being consumed anymore.

I was looking at the source code of v1.30 and could see files like [docker](https://github.com/microsoft/playwright/blob/release-1.30/packages/playwright-core/src/containers/docker.ts), [dockerApi](https://github.com/microsoft/playwright/blob/release-1.30/packages/playwright-core/src/containers/dockerApi.ts), [dockerPlugin](https://github.com/microsoft/playwright/blob/release-1.30/packages/playwright-test/src/plugins/dockerPlugin.ts) but these seem to be removed in v1.40.

I am not sure how I can ensure that my tests are run on an ubuntu docker image (in Mac). Is this still possible? How can I make this work?

**Comment by yury-s** [comment]
Experimental docker command has never been released and was [removed](https://github.com/microsoft/playwright/pull/20676). You can still run our docker images and [run docker](https://playwright.dev/docs/docker#run-the-image) commands directly.
