### ISSUE TITLE
[BUG] expect.configure timeout does not apply to expect.poll

### ISSUE THREAD

**Issue by aldeed** [microsoft/playwright#28744]
### System info
- Playwright Version: v1.40.1
- Operating System: All
- Browser: n/a

### Source code

```
import { expect } from "@playwright/test";

// Create a custom expect with 10s timeout
const customExpect = expect.configure({ timeout: 10000 });

// This fails because it actually logs
// "Timeout 5000ms exceeded while waiting on the predicate"
await expect(
  customExpect
    .poll(async () => {
      return true;
    })
    .toBe(false),
).rejects.toThrow(/Timeout 10000ms exceeded/);
```

**Steps**
- Run the code and notice that the assertion fails. Here's [a codesandbox link](https://codesandbox.io/p/devbox/pw-expect-poll-timeout-issue-rsfkt9?file=%2Findex.mjs%3A12%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqe3hczs00073b6hlopmmq6b%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqe3hczs00023b6hr60jd0ot%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqe3hczs00043b6hyl5z6icz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqe3hczs00063b6htet2ppto%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqe3hczs00023b6hr60jd0ot%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqe3hczr00013b6hqhcpdoio%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqe3lm4p00023b6h4iistpsb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Findex.mjs%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqe3hczs00023b6hr60jd0ot%2522%252C%2522activeTabId%2522%253A%2522clqe3lm4p00023b6h4iistpsb%2522%257D%252C%2522clqe3hczs00063b6htet2ppto%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqe3hczs00053b6hsjk0m2gp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A8080%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clqe3hczs00063b6htet2ppto%2522%252C%2522activeTabId%2522%253A%2522clqe3hczs00053b6hsjk0m2gp%2522%257D%252C%2522clqe3hczs00043b6hyl5z6icz%2522%253A%257B%2522id%2522%253A%2522clqe3hczs00043b6hyl5z6icz%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqe3hczs00033b6hrq8j9dvp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqe3hczs00033b6hrq8j9dvp%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) where you can try it.

**Expected**

The timeout of 10s should be respected, and the error message should say "Timeout 10000ms exceeded..."

The [docs](https://playwright.dev/docs/test-assertions#expectpoll) do not explicitly say this should work, but `expect.configure` is immediately before this section in the docs so it seems to imply it. Also, [this PR](https://github.com/microsoft/playwright/issues/21630) _does_ explicitly say it should work.

**Actual**

The built-in default timeout of 5s is used, and the error message says "Timeout 5000ms exceeded..."

**Comment by aldeed** [comment]
Actually, it doesn't appear to work for `toPass` either.

```js
await expect(
  customExpect(async () => {
    expect(true).toBe(false);
  }).toPass(),
).rejects.toThrow(/Timeout 10000ms exceeded/);
```

This one waits for way more than 10s by default.

**Comment by yury-s** [comment]
Looks like you are missing await in your original example, this test passes for me:

```js

import { test, expect } from '@playwright/test';

const customExpect = expect.configure({
  timeout: 700
})

test('test', async ({ page }) => {
  await expect(customExpect.poll(async () => { 
    return false;
  }).toBe(true)).rejects.toThrowError('Timeout 700ms exceeded');
});
```

**Comment by yury-s** [comment]
``toPass()` is different in that it is supposed to contain a bunch of `expect`s in its callback, each of which can timeout and respects custom expect timeout, so you can only pass a custom timeout to toPass directly if you like or just rely on the test timeout. We'll update the docs to mention this.

**Comment by aldeed** [comment]
@yury-s Thanks for your comments. I do have the `await` in the codesandbox so that isn't the issue. I didn't try your example yet, but I'm guessing the difference must be because you are using `test` from  `@playwright/test`. I'm using regular Jest and would expect it to work either way.

**Comment by aldeed** [comment]
`toPass` never timing out doesn't seem like great default behavior either, especially if it isn't configurable. I actually found this issue because I was attempting to give `toPass` a sane default in a setup file because it was running for many minutes sometimes. The test itself timing out is the only thing that resolves the stuck state.

**Comment by aldeed** [comment]
@yury-s Your docs PR closed this but the original issue I reported isn't fixed.
