### ISSUE TITLE
[BUG] No option to reset sorting in UI Mode in Network tab (+ sorting indicator missing when changing tab and going back to Network )

### ISSUE THREAD

**Issue by jaktestowac** [microsoft/playwright#28746]
![obraz](https://github.com/microsoft/playwright/assets/72373858/8e7d9f84-272d-4836-883f-44439eb1f715)

### System info
- Playwright Version: [v1.40.1]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

### Source code
```
import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  await expect(page.locator('h1')).toContainText('Playwright enables reliable end-to-end testing for modern web apps.');
});
```

**Steps**
- Run test in UI Mode
- Go to Network tab
- Sort by any column 
- Try to RESET sorting (not possible)
- go to other tab than Network
- go back to Network tab

**Expected**
Sorting is reset to execution order (default)
i.e. reset icon next to Dock to right icon

**Actual**
There is no option to reset sorting.
When coming back from other tab to sorted Network tab the sorting indicator is missing
Time column has no label (is that intended?).

**Comment by pavelfeldman** [comment]
When you say "reset sorting", do you mean sort by the first column?

**Comment by jaktestowac** [comment]
Regarding "reset sorting" I wish to see request presented as were populated (i.e. when you open Network tab first time - requests are presented this way)
In Chrome Dev Tools in Network there is Waterfall tab and it is the default sorting. 
In UI Mode maybe some timestamp can be reference (as new column), or request time to allow sorting by request start time (what is default behavior in Waterfall column).

**Comment by pavelfeldman** [comment]
> Regarding "reset sorting" I wish to see request presented as were populated (i.e. when you open Network tab first time - requests are presented this way)

That would be the first column in our case.

**Comment by dgozman** [comment]
You should be able to click the "Start" column once 1.42 is released.
