### ISSUE TITLE
[BUG] Error: Screenshot comparison failed

### ISSUE THREAD

**Issue by mrrinatino** [microsoft/playwright#28741]
### System info
- Playwright Version: [v1.40.1]
- Operating System: [macOS 13.2]
- Browser: [Chromium]

Hi! We often encounter a problem, can you tell me if it already has a solution?
When using tests with screenshot comparison, await expect(page.locator).toHaveScreenshot('blabla.png'); if the autotest is run locally on the computer, it succeeds, but if the same test is run in gitlab, it crashes with a similar error:
Error: Screenshot comparison failed: Expected an image 646px by 169px, received 646px by 168px.
or more pixels
Error: Screenshot comparison failed: Expected an image 480px by 222px, received 480px by 194px. 

Which parameter can ignore this error, because both screenshots are valid for us

**Comment by yury-s** [comment]
Your CI environment is different from local one, it's probably a linux box while your local machine is a mac. The rendering is very sensitive to the host environment (and even to whether your mac has power adapter plugged in or not), it may be that on the CI machine the page uses different fonts too. To make the visual tests reproducible we recommend generating expectations on the same machine where you run the tests. There is a also a bunch of [options](https://playwright.dev/docs/api/class-pageassertions#page-assertions-to-have-screenshot-2) that allow make toHaveScreenshot less strict, you can toy with those.

Folding this issue into https://github.com/microsoft/playwright/issues/8161
