### ISSUE TITLE
[Feature] Enable background page access of browser extension in Firefox

### ISSUE THREAD

**Issue by mukunduashok** [microsoft/playwright#2874]
Let us know what functionality you'd like to see in Playwright and what is your use case.
It would be great, if we can access the background page of the browser extension as like in Chrome (https://playwright.dev/#version=v1.2.0&path=docs%2Fapi.md&q=working-with-chrome-extensions). 

Do you think others might benefit from this as well?
Currently automation developers use web-sockets or other work around to enable communication between automation scripts and the browser extensions. This feature will enable many automation developers who work with browser extension to use same APIs to communicate with the background page of the extension.

**Comment by dbjorge** [comment]
We would love to use this for testing [Accessibility Insights for Web](https://github.com/microsoft/accessibility-insights-web)!

**Comment by radicleart** [comment]
Really useful for decentralised apps using crypto wallet software like Joule, Meta Mask and Blockstack Connect!

**Comment by pavelfeldman** [comment]
Support for extensions and bg pages is outside of the scope of Playwright. Is there a way to convert those great extensions into the code that works via Playwright? Playwright is more powerful than extensions in terms of accessing the page content and runtime, so all the a11y and performance auditing can be performed via Playwright interfaces as well.

**Comment by dbjorge** [comment]
> the a11y and performance auditing can be performed via Playwright interfaces as well.

To clarify, I am a developer of the Accessibility Insights for Web extension looking to write end to end tests of our extension; I'm not looking to use the extension to audit a different product under test.

> Support for extensions and bg pages is outside of the scope of Playwright.

Playwright [explicitly documents how to use it to test extensions in Chromium](https://playwright.dev/#version=v1.5.2&path=docs%2Fapi.md&q=working-with-chrome-extensions) and even [provides a specific ChromiumBrowserContext API for accessing backgroundPages](https://playwright.dev/#version=v1.5.2&path=docs%2Fapi.md&q=chromiumbrowsercontextbackgroundpages). Are you saying that we should expect that functionality to go away or become deprecated? Or that it's in-scope for Chromium but not Firefox? The latter feels confusing; "Support for all browsers" is the top bullet point on Playwright's [Why Playwright?](https://playwright.dev/#version=v1.5.2&path=docs%2Fwhy-playwright.md&q=) page, it feels very inconsistent for there are browser features that are in-scope for some browsers and out-of-scope for others.

> Is there a way to convert those great extensions into the code that works via Playwright?

As an extension developer, coercing our extension code to run outside of the context of a browser extension is a valuable methodology for some tests (eg, unit tests), but not for the kind of tests that I would want to use a browser automation tool like Playwright for! The *primary value* that Playwright adds for our testing is *being able to test in the context that a user will see it*.

**Comment by shirshak55** [comment]
I think extension is valuable because we can test if page doesn't break with popular extension like ublock etc.  Is there way to change default from extension off to extension on from our side?

**Comment by Saranya-v60** [comment]
@mukunduashok , I am an automation developer for browser extension using Puppeteer. As Puppeteer works for only Chromium browser.So I want to move my code to PlayWrite and checking for extensions support across browsers.

With Chromium browser , PlayWrite works well with extensions. I want the same support for firefox as well. Is it possible ? Please help me out.

**Comment by mukunduashok** [comment]
> @mukunduashok , I am an automation developer for browser extension using Puppeteer. As Puppeteer works for only Chromium browser.So I want to move my code to PlayWrite and checking for extensions support across browsers.
> 
> With Chromium browser , PlayWrite works well with extensions. I want the same support for firefox as well. Is it possible ? Please help me out.

@Saranya-v60 Currently playwright does not support 'Browser Extension' communication. This ticket is raised as a feature request to enable "Background Pages" support in Firefox too. In case if you're looking for workaround, you can try out the steps mentioned by @aslushnikov in https://github.com/microsoft/playwright/issues/2644

**Comment by pavelfeldman** [comment]
@dbjorge: you make a fair point. Our priority is the cross-browser web. Extensions are not a part of the web though, they are largely vendor-specific and hence are not a priority for us. The reason Chromium extensions support is there is organic. While working on Chrome DevTools, we designed all of its infrastructure, including the support for extensions. So for us, picking it up in Playwright was super-easy. Matching it in Firefox on the other hand is a substantial effort that is challenging to prioritize.

We are happy to help reviewing the patches and driving it forward if someone wants to pick it up in the Firefox land.

**Comment by frank-dspeed** [comment]
I am working on that kind of interop at present but for the mean while i have a proposal that is playwright related:

shim the extension API so that it works in a normal opened playwright page that is not a real background page but who cares as long as the code runs and that would be maintainable as it is a 1:1 in most browsers the extension API it self matches while manifests and install pathes are the problems

we can connect the background page to any other page and even fire the events that a extension would get as we have the same events in playwright when we open pages.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
