### ISSUE TITLE
[Feature] Support Firefox with Selenium Grid

### ISSUE THREAD

**Issue by shemeshx** [microsoft/playwright#28750]
Hey,

Is there any way to support Firefox on Selenium Grid? 
If not, is there a workaround how it can be supported?
Anyway, is there an equivalent way to run tests with Playwright on a platform that shows the tests on dockers in live like Selenium Grid that will support all browsers?

Thanks!

**Comment by yury-s** [comment]
Playwright connects to the browser running on Selenium Grid over CDP, so only Chromium-based browsers are supported. You can use [Playwright Testing Service](https://azure.microsoft.com/en-us/products/playwright-testing/) to run browsers in the cloud or you can use a CI such as GitHub Actions to orchestrate Playwright runs across multiple platforms/browsers.

Closing this request as there are no plans to extend experimental Selenium Grid support to include Firefox.
