### ISSUE TITLE
[Question] Expected output of trace files into specified trace_dir

### ISSUE THREAD

**Issue by lstuartfry** [microsoft/playwright#28751]
Hello! I'm unsure if this is a bug or expected behavior, so I'm opening a general question here.

What is the expected output format for trace files, when specifying the `name` property on the trace? I'm following the API docs [here](https://playwright.dev/python/docs/api/class-tracing#tracing-start-option-name).

![image](https://github.com/microsoft/playwright-python/assets/14063740/60489cd0-e6aa-4940-acee-f0c494231497)

I've specified a `trace_dir` upon launching the browser, and that directory looks to be created fine. However, rather than `.zip` files for each trace, I see separate `.network` and `.trace` files, along with a `/resources` folder.

![image](https://github.com/microsoft/playwright-python/assets/14063740/016ea995-87d9-4c25-9e87-230e129333a6)

**Comment by yury-s** [comment]
You don't need to specify the name, it's only used for intermediate files. What you need is [`path`](https://playwright.dev/python/docs/api/class-tracing#tracing-stop-option-path) in the `stop()` method. We'll update the docs.

**Comment by lstuartfry** [comment]
@yury-s thanks so much for the clarification!
