### ISSUE TITLE
[Feature] Allow to set different default timeouts for expect and expect.soft assertion

### ISSUE THREAD

**Issue by AdamOakman** [microsoft/playwright#28753]
My use case is that I usually prefer to set shorter timeouts for expect.soft than for regular expect assertions to avoid tests with many expect.soft assertions and their possible mass failures to last forever. It would be handy to be able to set a global default timeout for all expect and optionally for expect.soft in playwright config file. The suggested logic behind it should be as follows: in case expect.soft default timeout is not set - it should respect the expect default timeout. That's it.

**Comment by AdamOakman** [comment]
It might be worth to consider this issue along with my other feature request https://github.com/microsoft/playwright/issues/23191 and create separate config entities for expect and expect.soft - to better control timeouts and screenshot behaviors for both in separation.

**Comment by yury-s** [comment]
Just to clarify, you can already set [expect timeout](https://playwright.dev/docs/test-timeouts#set-expect-timeout-in-the-config) in the config today, so you suggest we have another option for `expect.soft`?

**Comment by AdamOakman** [comment]
Yes, exactly. Right now I have default timeout set for all assertions and every time I call expect.soft assertions I need to manually set different timeout to all of them for the reason I described in the original post. It would be much more covenient to set this timeout once for all soft assertions across the project in global config which would be different than default timeout for all non-soft expects.

**Comment by Az8th** [comment]
This is already feasible by [configuring a custom expect config](https://playwright.dev/docs/test-assertions#expectconfigure).
```typescript
//Declaration
const slowerSoftExpect = expect.configure({ timeout: 12000, soft: true });
//Usage
await slowerSoftExpect(locator).toHaveText('Login');
```
But I have to admit that adding a way to set it in the global config file just as the classical expect would be more convenient.
Example:
```typescript
//playwright.config.ts
import { defineConfig } from '@playwright/test';

export default defineConfig({
  softExpect: {
    timeout: 12000,
    toMatchSnapshot: {
      maxDiffPixels: 20,
    },
  },
});
```

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
