### ISSUE TITLE
[BUG] Enable download and usage of OpenH264 and Widevine plugins

### ISSUE THREAD

**Issue by fiberAIO** [microsoft/playwright#2875]
**Context:**
- Playwright Version: [1.2.0]
- Operating System: [Windows]
- Node version: [13.10.1]
- Browser: [Firefox]

**Code Snippet**
``` javascript
const browser = await firefox.launch({
        headless: false,
        args: [`-height=${height}`, `-width=${width}`],
        ignoreDefaultArgs: ["--mute-audio"],
        firefoxUserPrefs:{
            "media.gmp-manager.updateEnabled":true
        }
    });
```

**Describe the bug**
Hi. Playwright is awesome. However, I tried to make use of the streaming application which uses DRM content and "media.gmp-manager.updateEnabled":false is preventing the browser from downloading the plugin.
I can change that manually from the browser's about:config and everything works fine but with following code and using userDataDir (as workaround from previous issues) it remains set to false. I tried changing other prefs with firefoxUserPrefs and it works but I'm stuck with this one for several hours. Help would be much appreciated.

> Update: I used newest Chrome Canary, setting executablePath and it worked. Would be great to use firefox though.

**Comment by aslushnikov** [comment]
@SaulGDev can you please help with a link to the DRM content you try to load, so that we can reproduce this locally?

**Comment by Shinoby92** [comment]
still not working. its also not working on webkit linux. But does work on osx webkit launch from playwright

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.

**Comment by Maadtin** [comment]
> **Context:**
> 
> * Playwright Version: [1.2.0]
> * Operating System: [Windows]
> * Node version: [13.10.1]
> * Browser: [Firefox]
> 
> **Code Snippet**
> 
> ```js
> const browser = await firefox.launch({
>         headless: false,
>         args: [`-height=${height}`, `-width=${width}`],
>         ignoreDefaultArgs: ["--mute-audio"],
>         firefoxUserPrefs:{
>             "media.gmp-manager.updateEnabled":true
>         }
>     });
> ```
> 
> **Describe the bug** Hi. Playwright is awesome. However, I tried to make use of the streaming application which uses DRM content and "media.gmp-manager.updateEnabled":false is preventing the browser from downloading the plugin. I can change that manually from the browser's about:config and everything works fine but with following code and using userDataDir (as workaround from previous issues) it remains set to false. I tried changing other prefs with firefoxUserPrefs and it works but I'm stuck with this one for several hours. Help would be much appreciated.
> 
> > Update: I used newest Chrome Canary, setting executablePath and it worked. Would be great to use firefox though.

Hey, how did you get chrome to stream widevine? I can't get to get it working. firefox works fine thought.
