### ISSUE TITLE
[BUG] Windows WebKit doesn't have WebAssembly

### ISSUE THREAD

**Issue by myobie** [microsoft/playwright#2876]
**Context:**
- Playwright Version: 1.1.1
- Operating System: Windows
- Node version: 14.4.0
- Browser: WebKit
- Extra: Process running inside GitHub Actions; code running in a ServiceWorker context.

**Code Snippet**

```javascript
(async function () {
  const response = await fetch(url)
  const bytes = await response.arrayBuffer()
  const module = await WebAssembly.compile(bytes)
  return module
})()
```

**Describe the bug**

Throws an `Error` with the message `Can't find variable: WebAssembly`. Code works on Linux WebKit and macOS WebKit – `WebAssembly` is found.

**Comment by aslushnikov** [comment]
@myobie Yes, there's no webassembly indeed. We have a summary table on what's in there and what's not for every platform:

https://github.com/microsoft/playwright/blob/master/docs/development/webkit.md

I don't think this is something that'll change in near future. +cc @yury-s to make sure I understand it right.

**Comment by yury-s** [comment]
WebAssembly is currently disabled in WebKit Windows port upstream. I don't think anyone is actively working on enabling it there so it will likely be missing in WebKit Windows in the near future.

**Comment by myobie** [comment]
Gah, I missed that feature table. Thanks for the link and info. 🙇

**Comment by ericoporto** [comment]
> WebAssembly is currently disabled in WebKit Windows port upstream.

Is this still the state in 2023?

**Comment by trusktr** [comment]
> Is this still the state in 2023?

Yes indeed, I just tried. `WebAssembly` is still missing in Windows Webkit.

**Comment by fujii** [comment]
upstream WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=222315
Contributions are welcome.

**Comment by ericoporto** [comment]
Erh, curious, should playwright's WebKit in macOS have WebAssembly?

**Comment by iangrunert** [comment]
WebAssembly is now enabled on the Windows port for WebKit: https://github.com/WebKit/WebKit/pull/18184

Note that this is just the low level interpreter, neither of the JIT tiers are enabled yet. This means it'll run significantly slower than other platforms for now, until the BBQ and / or OMG JIT tiers are enabled.

**Comment by DrMueller** [comment]
@iangrunert Sorry for the question, but how do I get the newest version with Windows WASM WebKit to work? According to https://playwright.dev/dotnet/docs/browsers, PlayWright.NET decides, which version of WebKit to use, isn't it?

**Comment by DrMueller** [comment]
> @iangrunert Sorry for the question, but how do I get the newest version with Windows WASM WebKit to work? According to https://playwright.dev/dotnet/docs/browsers, PlayWright.NET decides, which version of WebKit to use, isn't it? Does your comment above mean, that it is technically ready but not yet released?

**Comment by iangrunert** [comment]
@DrMueller Unfortunately JIT was disabled on the Windows port in May due to https://bugs.webkit.org/show_bug.cgi?id=273854, and JIT is (currently) required in order to generate entry thunks to use the WebAssembly interpreter.

I'm currently working on getting JIT + WebAssembly re-enabled, I can comment on this thread when that happens.

**Comment by DrMueller** [comment]
@iangrunert Thank you for the status update, yes it would be grat if you could leave a comment so i get pinged, when this is supposed to work.

**Comment by DrMuellerAtNoser** [comment]
@iangrunert Any news on  this topic by chance?

**Comment by iangrunert** [comment]
The Windows port supports WASM from Playwright v1.49 onwards (released last year). I checked today with Playwright version: 1.57.0, webkit-2227 and can confirm it's still working:

<img width="3840" height="2088" alt="Image" src="https://github.com/user-attachments/assets/ae3df499-2586-4790-a59f-33b29834773b" />
<img width="3840" height="2088" alt="Image" src="https://github.com/user-attachments/assets/608c961c-1b2e-4c15-866b-42ad0b304e7f" />

Sorry I missed replying back on this issue when this was released last year - I linked this issue to the Playwright folks to follow up on, but it must've been missed as the issue was already marked as completed.

**Comment by DrMueller** [comment]
> The Windows port supports WASM from Playwright v1.49 onwards (released last year). I checked today with Playwright version: 1.57.0, webkit-2227 and can confirm it's still working:
> 
> <img alt="Image" width="2000" height="2000" src="https://private-user-images.githubusercontent.com/2259495/518751937-ae3df499-2586-4790-a59f-33b29834773b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQwOTU5OTcsIm5iZiI6MTc2NDA5NTY5NywicGF0aCI6Ii8yMjU5NDk1LzUxODc1MTkzNy1hZTNkZjQ5OS0yNTg2LTQ3OTAtYTU5Zi0zM2IyOTgzNDc3M2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTExMjVUMTgzNDU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDhjNDY2NDc1NTY2MzJhMjM3MDIxZjllZTUzM2UxYmVkZTRiNWNhNjNiYWI0YWYwMWQzNWUxNzlkOTMxMzgxOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.oQtTSkHAjqy0HpBWoq27xqogvxj70NuFrwV-1l3xN0A"> <img alt="Image" width="2000" height="2000" src="https://private-user-images.githubusercontent.com/2259495/518751939-608c961c-1b2e-4c15-866b-42ad0b304e7f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQwOTU5OTcsIm5iZiI6MTc2NDA5NTY5NywicGF0aCI6Ii8yMjU5NDk1LzUxODc1MTkzOS02MDhjOTYxYy0xYjJlLTRjMTUtODY2Yi00MmFkMGIzMDRlN2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTExMjVUMTgzNDU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDI3YzFhNTA2YjYwMzM3Nzc2OTFkMTQ3ZDMwODZhYTA1ZmU2ZWQ1OGZjN2M4NjliNTRkM2QwMTc0MDk3ZTkwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-_rMR1LAKqtX47IAsrtQcWS1IQVMF65WcUp4kY1JNFA">
> Sorry I missed replying back on this issue when this was released last year - I linked this issue to the Playwright folks to follow up on, but it must've been missed as the issue was already marked as completed.

Thank you very much!
