### ISSUE TITLE
[BUG] goBack() not working for webkit

### ISSUE THREAD

**Issue by rickie-duan** [microsoft/playwright#28769]
### System info
- Playwright Version: [latest]
- Operating System: [macOS 13.2]
- Browser: [WebKit]
- Other info:

### Source code

```js
test('@test ', async ({ page }) => {
    await page.goto('https://phoenix-integration.aws.mapquest.com/search/new%20york%20downtown%20pizza', { waitUntil: "domcontentloaded" });
    await page.waitForTimeout(10000);

    await page.waitForSelector('#marker-0', { state: 'visible' });
    await page.click('#marker-0');
    const firstUrl = page.url();
    await page.waitForTimeout(2000);

    await page.waitForSelector('#marker-1', { state: 'visible' });
    await page.click('#marker-1');
    await page.waitForTimeout(2000);
    const secondUrl = page.url();
    await page.waitForTimeout(2000);

    expect(firstUrl).not.toEqual(secondUrl);

    await page.goBack({waitUntil: "domcontentloaded"});
    await page.waitForTimeout(2000);

    const urlAfterBack = page.url();
    await page.waitForTimeout(2000);
    expect(urlAfterBack).toEqual(firstUrl);
  });
```

**Steps**
- [Run the test]
- [...]

**Expected**

goBack() not working

**Actual**

[Describe actual behavior]

**Comment by yury-s** [comment]
I cannot reproduce it locally. Your test is full of waitForTimeout calls which may well make it flaky depending on the environment. Please follow our best practices and use [web assertions](https://playwright.dev/docs/best-practices#use-web-first-assertions) such as [`toHaveUrl()`](https://playwright.dev/docs/api/class-pageassertions#page-assertions-to-have-url) to ensure that you wait until the page gets into desired state.
