### ISSUE TITLE
[Feature] Allow direct interaction with the application after a test run is completed (Like Cypress)

### ISSUE THREAD

**Issue by dudewad** [microsoft/playwright#28773]
We are in the midst of switching a large enterprise project from Cypress to Playwright.

Playwright offers a bunch of stuff that Cypress doesn't, and overall I'm fairly happy with it.

There is, however, one major drawback that significantly reduces my efficiency as I develop tests: Cypress gives the ability to run in headed mode, and when a test has completed, you can still interact with the application - network interceptors still function, etc, allowing test data to still be available.

I didn't realize until after I started writing Playwright tests how incredibly powerful this is. The ability to directly interact with your still-running application after a failed test run to inspect application state, see console logs, look at source data right in the browser, etc, is incredibly useful.

I've done many hours of digging over the last couple months to try to figure out how to enable this with Playwright and the closest I can get is very cumbersome debug breakpoints, wait statements (i.e. promises with long timeouts), or just sufficing for screenshots in UI mode, and none of these methods actually provide the functionality I want, anyways.

If Playwright were to enable the ability for the application to continue running after a text excution, I'd sing its praises from the rooftops; unfortunately in its current form developing with it is actually much more painful than developing with Cypress, despite it feeling more powerful. While we can achieve more with it in the long run, it does currently extend my development time because I spend much, much more time trying to figure out exactly how things are acting.

It's very useful to be in the test paradigm of being able to spin up an empty test simply for the purpose of having API request stubs that return mocked data.

Hopefully this makes sense. Happy to elaborate if needed.

**Comment by yury-s** [comment]
You can use ["Show Browsers"](https://playwright.dev/docs/getting-started-vscode#run-tests-and-show-browsers) option in our VS Code extension. Would that work?

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
