### ISSUE TITLE
[BUG] SVG with <p> node does not render

### ISSUE THREAD

**Issue by SethFalco** [microsoft/playwright#28778]
### System info
- Playwright Version: [v1.40.1]
- Operating System: Debian Testing
- Browser: Chromium
- Other info:

### Source code

https://gist.github.com/SethFalco/0596d81677752c68d1310efe92dbdd25

**Steps**
Run `setContent` where `original` is the SVG string from the gist above.

```js
const fs = require('fs');
const { chromium } = require('playwright');
const { PNG } = require('pngjs');

// …
const original = ""; // read SVG content

const browser = await chromium.launch();
const context = await browser.newContext({ javaScriptEnabled: false });
const page = await context.newPage();

await page.setContent(original);

const originalBuffer = await page.screenshot({
  omitBackground: true,
  clip: { x: 0, y: 0, width, height },
});

const originalPng = PNG.sync.read(originalBuffer);

await fs.promises.writeFile("out.png", PNG.sync.write(originalPng));
await browser.close();
```

**Expected**

It should render the same as it would if I were to run `page.goto('file://path/to/svg');` or when I paste the same SVG contents in Chromium.

**Actual**

Nothing renders.

---

I've noticed that it's tied to do `<p></p>` in the SVG document. When that node is removed, everything works again. The `<p>` tag seems to stop the SVG from rendering.

**Comment by KTibow** [comment]
This may be an issue with how this renders it as HTML. When I do
```
document.write(`...svg contents`)
```
in `about:blank`'s JS console, the SVG parsing stops upon the `p` tag too.

---

I wonder if this works as a data URL? (use the syntax `data:image/svg+xml;utf8,[...url encoded data]`)

**Comment by SethFalco** [comment]
> ```
> document.write(`...svg contents`)
> ```

Ahh, I didn't try that. The documentation for `Page#setContent` does state it uses `document#write` internally, though, so that makes sense. I guess this is reproducible in Chromium then.

> I wonder if this works as a data URL? (use the syntax data:image/svg+xml;utf8,[...url encoded data])

I tried that workaround already, but in `Page#goto` it leads to errors for large SVGs.

**Comment by KTibow** [comment]
Does this also not work?
```js
setContent(`<img src="[data url]" width="960" height="720"/><style>body{margin:0}</style>`)
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
