### ISSUE TITLE
[Feature] A special locator to visually locate an element

### ISSUE THREAD

**Issue by idxn** [microsoft/playwright#2877]
**Let us know what functionality you'd like to see in Playwright and what is your use case.**
A special locator to visually locate an element.

In taiko, browser automation library by thoughtwork, you could locate element visually like the following:
`click(checkbox(near("Username")))`

Taiko calls it proximity locator
Refer: https://docs.taiko.dev/#smart-selectors

This locator will reduce the flakiness of the script and the maintenance cost because the locator doesn't rely on html structure that may be changed from time to time. Even we can assign data-testid attribute but this is very useful in some cases as well.

**Do you think others might benefit from this as well?**
Yes, it is.

**Comment by mxschmitt** [comment]
Have you seen already the selector documentation? Text, css, xpath, shadow dom selectors are available: https://playwright.dev/#version=v1.2.0&path=docs%2Fselectors.md&q=

Does this fit for your needs?

A feature for highlighting a certain dom node will be tracked here: #2747

**Comment by idxn** [comment]
Yes, I have seen it and it still doesn't fit my need.
BTW, thanks for pointing #2747. That is also useful.

**Comment by idxn** [comment]
@mxschmitt Another use case I can think of is for web scrapping that we need to rely on html structure/attribute if there is no id/data-testid assigned. The maintenance cost for that script will be really high if we need to rely on css/xpath on this case.

**Comment by klctrl** [comment]
I'd also love to see "proximity selectors" (as the Taiko team calls them) added to the Playwright API. They'd make "black box" testing (i.e. purely from the point of view of the end user w/o any insight into the application's technical details (DOM, CSS, etc.)) become a reality. 

They've been recently added to Selenium as well, see [here](https://www.selenium.dev/documentation/en/getting_started_with_webdriver/locating_elements/#relative-locators). (They call it "relative locators".)

For me, they would be most useful in locating/selecting an element via text selector if there are several elements with the same text on a page. Currently, the text selector would simply return the first found element which may not be the one intended to select. With proximity selectors, however, one could much better specify which particular element one is interested in.

**Comment by klctrl** [comment]
I am currently in the midst of evaluating a handful (4, actually) of E2E test automation tools for my team, among them Taiko and Playwright. I've started with Taiko and my experience so far with those proximity selectors (see link in this thread's initial post) is simply splendid: I can create entire e2e tests in full black-box mode, meaning that I use only information I see on the tested web page w/o having to inspect the page's html code in any way. This makes creating and maintaining e2e tests a real breeze, with pretty low efforts. It's a pure pleasure, really. 👍 

@pavelfeldman @mxschmitt @aslushnikov @yury-s @JoelEinbinder If you guys haven't done so yet you really ought to check this out yourselves! :) I am convinced that the day you do this you'll put those proximity selectors on Playwright's roadmap. I hope you take note.

**Comment by klctrl** [comment]
@pavelfeldman @mxschmitt @aslushnikov @yury-s @JoelEinbinder @arjun27 Given that ThoughtWorks will cease supporting Taiko (I'd say best-in-class regarding smart/proximity selectors) by the end of this year and that from 2021 on Taiko will be a fully community-managed open source project (see [here](https://github.com/getgauge/taiko/issues/1470)), now would be a good time (re)contemplating about adding such smart selectors to Playwright as well (or, as an interim solution, explain in more detail how Taiko's selector engines can be successfully registered and used in Playwright -- see #3667). Sorry for making such a noise about it, it's just that by my own experience with Taiko, it makes creating and maintaining e2e tests a pure joy.

**Comment by roughsoft** [comment]
very great feature, the selenium 4 will implement these friendly selector

**Comment by jfgreffier** [comment]
I'm willing to initiate a selector engine that implements relative selectors.

I was planning to make use of Playwright's chaining like this. What do you think of this syntax ?
```
page.click(`text=Login >> taiko=toRightOf Home`)
```


@idxn @roughsoft Do you think relative selectors fits your requirements ? i.e. toLeftOf, toRightOf, above, below, near
Or it should do more ?

By the way, I'm **Jeff** on Playwright's Slack. Feel free to drop me a message there

**Comment by klhex** [comment]
@jfgreffier That would be awesome! IMHO the mentioned relative selectors (also called proximity selectors, see for example https://docs.taiko.dev/api/reference/) would perfectly fit the requirements.

Regarding the syntax you should have a look at @pavelfeldman's [comment](https://github.com/microsoft/playwright/issues/3667#issuecomment-684192158) in a duplicate issue in which he gives an example for a corresponding syntax.

**Comment by idxn** [comment]
@jfgreffier That covers everything I need.

**Comment by falcon030** [comment]
@jfgreffier If you can implement the relative/proximity selectors, like the ones that Taiko supports, than this would be great.

**Comment by roughsoft** [comment]
@jfgreffier thank you!

**Comment by roughsoft** [comment]
@jfgreffier I would like these:
page.click(`taiko=link('Sign In',near("Home"),toLeftOf("Sign Out"))`);

**Comment by jfgreffier** [comment]
Please check the first version of Playwright relative selector ! It allows you to select an element by its relative position to another one
https://www.npmjs.com/package/playwright-relative-selector

It's in early phase. My goal at the moment is to get feedback on it, so don't hesitate to drop an issue [here](https://github.com/jfgreffier/playwright-relative-selector/issues)

@roughsoft I created an issue to discuss specifically of the syntax https://github.com/jfgreffier/playwright-relative-selector/issues/1

**Comment by pavelfeldman** [comment]
@jfgreffier : I looked at your repo, great job! Is there a way to pass selector into the `page.click`? We discourage getting a handle and then performing an action on it since this effectively disables rhe auto-waiting logic.

**Comment by jfgreffier** [comment]
@pavelfeldman That was my first approach, to create a custom selector engine. However, I faced some issues:
-  When using chaining, it will call my selector `query()` multiple times. Ideally I wanted to know all candidates nodes to select the closest one
- I found out that selectors are executed in the browser's context and so it is not possible to use a selector from a custom selector engine...

It's better to don't reinvent the wheel and reusing Playwright selectors is ideal. Do you think there is a workaround or a better way to don't interfere with the auto-wait logic ?

**Comment by idxn** [comment]
@pavelfeldman Good news? Will this be included in playwright?

**Comment by pavelfeldman** [comment]
Will launch in 1.8
