### ISSUE TITLE
[Feature] installer on Windows On ARM

### ISSUE THREAD

**Issue by shirubei** [microsoft/playwright#28785]
Hello, I tried to install this library(playwright-1.40.0-py3-none-win_amd64.whl) on a raspberry pi running windows 10 , Python 3.11.0 
but ended with "not a supported wheel"
Any hints ? Appreciate your advice. Thank you.

C:\Users\Roby123\Downloads>pip install playwright-1.40.0-py3-none-win_amd64.whl
ERROR: playwright-1.40.0-py3-none-win_amd64.whl is not a supported wheel on this platform.

C:\Users\Roby123>python
Python 3.11.0 (main, Oct 24 2022, 18:15:22) [MSC v.1933 64 bit (ARM64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

C:\Users\Roby123\Downloads>pip debug  install playwright-1.40.0-py3-none-win_amd64.whl --verbose
WARNING: This command is only meant for debugging. Do not use this with automation for parsing and getting these details, since the output and options of this command may change without notice.
pip version: pip 23.3.2 from C:\Users\Roby123\Python311-arm64\Lib\site-packages\pip (python 3.11)
sys.version: 3.11.0 (main, Oct 24 2022, 18:15:22) [MSC v.1933 64 bit (ARM64)]
sys.executable: C:\Users\Roby123\Python311-arm64\python.exe
sys.getdefaultencoding: utf-8
sys.getfilesystemencoding: utf-8
locale.getpreferredencoding: cp936
sys.platform: win32
sys.implementation:
  name: cpython
'cert' config value: Not specified
REQUESTS_CA_BUNDLE: None
CURL_CA_BUNDLE: None
pip._vendor.certifi.where(): C:\Users\Roby123\Python311-arm64\Lib\site-packages\pip\_vendor\certifi\cacert.pem
pip._vendor.DEBUNDLED: False
vendored library versions:
  CacheControl==0.13.1
  colorama==0.4.6
  distlib==0.3.6
  distro==1.8.0
  msgpack==1.0.5
  packaging==21.3
  platformdirs==3.8.1
  pyparsing==3.1.0
  pyproject-hooks==1.0.0
  requests==2.31.0
  certifi==2023.07.22
  chardet==5.1.0
  idna==3.4
  urllib3==1.26.17
  rich==13.4.2 (Unable to locate actual module version, using vendor.txt specified version)
  pygments==2.15.1
  typing_extensions==4.7.1 (Unable to locate actual module version, using vendor.txt specified version)
  resolvelib==1.0.1
  setuptools==68.0.0 (Unable to locate actual module version, using vendor.txt specified version)
  six==1.16.0
  tenacity==8.2.2 (Unable to locate actual module version, using vendor.txt specified version)
  tomli==2.0.1
  truststore==0.8.0
  webencodings==0.5.1 (Unable to locate actual module version, using vendor.txt specified version)
Compatible tags: 39
  cp311-cp311-win_arm64
  cp311-abi3-win_arm64
  cp311-none-win_arm64
  cp310-abi3-win_arm64
  cp39-abi3-win_arm64
  cp38-abi3-win_arm64
  cp37-abi3-win_arm64
  cp36-abi3-win_arm64
  cp35-abi3-win_arm64
  cp34-abi3-win_arm64
  cp33-abi3-win_arm64
  cp32-abi3-win_arm64
  py311-none-win_arm64
  py3-none-win_arm64
  py310-none-win_arm64
  py39-none-win_arm64
  py38-none-win_arm64
  py37-none-win_arm64
  py36-none-win_arm64
  py35-none-win_arm64
  py34-none-win_arm64
  py33-none-win_arm64
  py32-none-win_arm64
  py31-none-win_arm64
  py30-none-win_arm64
  cp311-none-any
  py311-none-any
  py3-none-any
  py310-none-any
  py39-none-any
  py38-none-any
  py37-none-any
  py36-none-any
  py35-none-any
  py34-none-any
  py33-none-any
  py32-none-any
  py31-none-any
  py30-none-any

**Comment by pavelfeldman** [comment]
Playwright on Windows on ARM is not supported.
