### ISSUE TITLE
[QUESTION] I can't change the download directory

### ISSUE THREAD

**Issue by MRS888888** [microsoft/playwright#28782]
### System info
- Playwright Version: [v1.39]
- Operating System: [Windows 11]
- Browser: [Chromium Incognito]
- Other info:
Testing the content of an generated CSV file with an expected CV file

The downloaded file is stored in C:\Users\........\AppData\Local\Temp\playwright-artifacts-[random]\[random file name]

So I try to change the download location but can't seem to fix it..

I managed to get a python script to take the file from the random generated TEMP location and copy it and rename it to the location I want it to be, but I refuse to accept this work around

I tried:
### Source code
*** Variables ***
${custom_download_directory}   ${EXECDIR}${/}test${/}Downloaded_merged_output${/}

Starting my test case with:
Configure Downloads Path
    Set Global Variable    ${custom_download_directory}
    
    and tried writing a python library and use it:
    
    Set Custom Download Directory    ${EXECDIR}${/}test${/}Downloaded_merged_output
    ${custom_download_directory}=    Get Custom Download Directory
    New Page    ${SERVER}
 
The test is running in incognito, hopefully someone knows how to solve this issue?

Thanks in advance

**Comment by python012** [comment]
Use custom user profile might be one option, you can create a sperate user profile for Chrome, and change the download location within this profile, and use this user profile in your test code.

![image](https://github.com/microsoft/playwright/assets/2948441/30a75f08-01d9-44fa-8ea2-1ae172091511)

The TypeScript code would be
```
import { test, BrowserContext, Page, chromium } from "@playwright/test";

let context: BrowserContext;
let page: Page;

test("user profile demo test", async ({}) => {
  // the custom user profile directory 'Profile 2' is put under D:/profiles
  context = await chromium.launchPersistentContext('D:/profiles', {args: ['--profile-directory=Profile 2']});
  page = await context.newPage();
  // open the application link
  await page.goto("https://www.file.com/yourfile.zip");
});

```

https://playwright.dev/docs/api/class-browsertype#browser-type-launch-persistent-context

**Comment by yury-s** [comment]
You can pass [`dowloadsPath`](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-persistent-context-option-downloads-path) option when creating the context. But better yet, use [`Download.saveAs`](https://playwright.dev/docs/api/class-download#download-save-as) to specify exact location and file name.

**Comment by MRS888888** [comment]
> You can pass [`dowloadsPath`](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-persistent-context-option-downloads-path) option when creating the context. But better yet, use [`Download.saveAs`](https://playwright.dev/docs/api/class-download#download-save-as) to specify exact location and file name.

I am using Robotframework and **await download.saveAs('/path/to/save/at/' + download.suggestedFilename());** is  not recognized

**Comment by yury-s** [comment]
I can't tell anything about that framework, you should ask on their support forum.

**Comment by MRS888888** [comment]
Fair point. Do you have an example where you set the downloadpath option when setting the context? I am really struggling to figure this out. Thanks for the earlier responses.
