### ISSUE TITLE
[BUG] cannot see $lib with sveltekit2

### ISSUE THREAD

**Issue by ivanafanasyeu** [microsoft/playwright#28781]
### System info
- Playwright Version: ^1.40.1
- Operating System: macOS last
- Browser: [All]
- Other info:
```json
	"@playwright/test": "^1.40.1",
		"@sveltejs/adapter-auto": "^3.0.0",
		"@sveltejs/adapter-cloudflare": "^3.0.0",
		"@sveltejs/kit": "^2.0.0",
		"@sveltejs/vite-plugin-svelte": "^3.0.0",
```

### Source code

```
import { expect, test } from '@playwright/test';
import {
	BTN_LOCALIZATION_CLOSE_TEST_ID,
	FB_LANG,
	LOCALIZATION_ICON_TEST_ID,
	LOCALIZATION_HINT_TEST_ID
} from '$lib/constants/localization';

test.describe('URL for langugage & region', () => {
	test('empty language and region do fallbacks', async ({ page }) => {
		await page.goto('/');
		await expect(page.locator('html')).toHaveAttribute('lang', FB_LANG);
	});
```

**Steps**
- install sveltekit 2 and playwright
- try to run any test importing contstants from the $lib folder, in ui they are not visible in just test run it says that cannot find $lib

**Expected**

- working tests

**Actual**

- it's not working

**Comment by WhyAsh5114** [comment]
I fixed it by adding a tsconfig.json in the tests folder
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "baseUrl": "../.svelte-kit"
  }
}
```

**Comment by ivanafanasyeu** [comment]
> I fixed it by adding a tsconfig.json in the tests folder
> 
> ```
> {
>   "extends": "../tsconfig.json",
>   "compilerOptions": {
>     "baseUrl": "../.svelte-kit"
>   }
> }
> ```

working

**Comment by dummdidumm** [comment]
I thought that playwright added support for aliases without a baseUrl, so that shouldn't be necessary to fix this.

**Comment by WhyAsh5114** [comment]
> I thought that playwright added support for aliases without a baseUrl, so that shouldn't be necessary to fix this.

I agree this shouldn't be necessary, but playwright doesn't run without errors unless I use this. 
VSCode doesn't put out any errors though.

**Comment by gschulze** [comment]
Hi! I tried the workaround suggested by @ivanafanasyeu, but this only works if the imported module does not in turn import a module from `$lib`.

**Comment by hamadycisse** [comment]
> I fixed it by adding a tsconfig.json in the tests folder
> 
> ```
> {
>   "extends": "../tsconfig.json",
>   "compilerOptions": {
>     "baseUrl": "../.svelte-kit"
>   }
> }
> ```

It works only if you do not import svelte files, otherwise you errors about unexpected tokens
```
/work/src/routes/+page.svelte: Unexpected token, expected "}" (12:25)
```
