### ISSUE TITLE
[BUG] toHaveURL validation not working in headless mode

### ISSUE THREAD

**Issue by FragosoThiago** [microsoft/playwright#28789]
### System info
- Playwright Version: [v1.40.1]
- Operating System: [Windows 11]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

```js
await page.getByText('Imprimir').click()

 const pagePromise = context.waitForEvent('page');
 await page.getByRole('link', { name: 'Guia de Reparação' }).click();

 const newPage = await pagePromise;
 await newPage.waitForLoadState();
 expect(newPage).toHaveURL(/guia/,url);
```

**Steps**
- I am simplily running this code in headless and it fails. It works on the browser.

Any suggestion?

**Actual**
Error: page.waitForLoadState: Test timeout of 200000ms exceeded.
    at tests\MM\CriarGuiaMM.spec.js:21:17

[Describe actual behavior]

**Comment by python012** [comment]
it looks your test stopped at the line of `await newPage.waitForLoadState();`, it didn't reach the code `expect(newPage).toHaveURL(/guia/,url);`, and you may need add `await` before using toHaveURL, see example in https://playwright.dev/docs/api/class-pageassertions#page-assertions-to-have-url

**Comment by FragosoThiago** [comment]
Hi,
Thanks for answering!

It's still not working. The issue now seems to be different:
Error: page.waitForLoadState: Test timeout of 200000ms exceeded.
    at tests\MM\CriarGuiaMM.spec.js:21:17

Execution log

"networkidle" event fired

**Comment by FragosoThiago** [comment]
Hi,
I added the await in all tests that I need to asset the URL and it keeps failing. This is the main assertion on my tests, so I can´t move on without it.
I've been searching around but couldn't find anything helpfull. You guys are my last shot =/

**Comment by yury-s** [comment]
> It's still not working. The issue now seems to be different:
Error: page.waitForLoadState: Test timeout of 200000ms exceeded.
at tests\MM\CriarGuiaMM.spec.js:21:17

Looks like some expectation is not met. Please follow our [debugging guide](https://playwright.dev/docs/running-tests) to troubleshoot the failure. If you think this is a bug in Playwright, please provide a self-contained repro that we could run locally.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
