### ISSUE TITLE
[BUG] Unable to execute js on v1.40 

### ISSUE THREAD

**Issue by atif87** [microsoft/playwright#28788]
### System info
- Playwright Version: [v1.40]
- Operating System: [Windows.]
- Browser: [ Chromium]
- Other info:

### Source code

using var playwright = await Playwright.CreateAsync();
var chrome= playwright.Chromium;
var browser = await chrome.LaunchAsync(new() { Headless = false });
var page = await browser.NewPageAsync();
await page.GotoAsync("https://www.bing.com/maps?FORM=Z9LH2&cp=35.687418%7E139.741974&lvl=11.0");
await page.Locator(".directionsIcon").ClickAsync();
await page.Locator("//*[@data-tag=\"watermarkInput\"]").First.FillAsync("coffee");
await page.Locator("//*[@data-tag=\"watermarkInput\"]").Last.FillAsync("pizza");
var script = "alert(\"Hello\")";

await page.EvaluateHandleAsync(script);
Thread.Sleep(1000);
await browser.CloseAsync();

[Please provide a self-contained example in a form of a snippet, archive or a repository.]

[Repro scenario can't be large or have external dependencies.]

**Steps**
- [Run the test]
- 

**Expected**
Ideally Alert should come

[Describe expected behavior]
I want to run some javascript code via EvaluateAsync or EvaluateHandleAsync
**Actual**

[Describe actual behavior]
Js code is not getting executed. How ever if we keep  EvaluateAsync  and EvaluateHandleAsync Then js code is getting executed.

**Comment by pavelfeldman** [comment]
> Js code is not getting executed. How ever if we keep EvaluateAsync and EvaluateHandleAsync Then js code is getting executed.

Could you elaborate on what this means?

**Comment by mxschmitt** [comment]
We need more information in order to look into issues like this. Feel free to re-file with more details, thanks!
