### ISSUE TITLE
How can i bypass the prompt at the end of tests that says in order to view last report run npx playwright show-report

### ISSUE THREAD

**Issue by irtezakhan** [microsoft/playwright#28794]
actually i am running my tests from a cron job for my remote URL.
I am sending my report to amazon s3 and also sending a slack notification for summary of results.
I dont want the test process to halt at the end waiting for user input to view last report or pressing ctrl+c and then y to exit out of the process since the tests are being run from a cron job.

**Comment by pavelfeldman** [comment]
https://playwright.dev/docs/test-reporters#html-reporter

Are you looking for open: never?
