### ISSUE TITLE
[Feature] add recording of the setup phase

### ISSUE THREAD

**Issue by Danieliverant** [microsoft/playwright#28793]
### System info
- Playwright Version: [v1.36.0] -  @nx/playwright 17.2.6
- Operating System: [Ubuntu 20, macOS 13.6]
- Browser: [Chromium]
- Other info:

### Source code

Same as your auth documentation: https://playwright.dev/docs/auth#moderate-one-account-per-parallel-worker

**Steps**
- create setup that will create an account in some site.
- use this setup (by importing "test & except" from it) and add a test that will fail.
- the trace/video only shows the test that failed without the setup phase.

**Expected**

To see the trace/video from the setup phase until the test failed.
For example, I might fail login because I had an issue in the registration but I wouldn't know about it.

**Actual**

Only the test.

**Comment by pavelfeldman** [comment]
> use this setup (by importing "test & except" from it) and add a test that will fail.

I'm not sure what this means.

When using project dependencies, setup entries are essentially tests. So they get their own traces. These setup tests run in different process than the tests. So if there are 100 setups and 1 test, you essentially get 101 traces. 100 of them run before your test runs. It sounds like you would want to see all 101 traces as a part of the test failure in this case, which does not sound like a scalable solution.

**Comment by Danieliverant** [comment]
> > use this setup (by importing "test & except" from it) and add a test that will fail.
> 
> I'm not sure what this means.
> 
> When using project dependencies, setup entries are essentially tests. So they get their own traces. These setup tests run in different process than the tests. So if there are 100 setups and 1 test, you essentially get 101 traces. 100 of them run before your test runs. It sounds like you would want to see all 101 traces as a part of the test failure in this case, which does not sound like a scalable solution.

the "import" part is what stated here: https://playwright.dev/docs/test-global-setup-teardown#capturing-trace-of-failures-during-global-setup in the second code exmaple

but I found a solution to my issue with: https://playwright.dev/docs/test-global-setup-teardown#capturing-trace-of-failures-during-global-setup

so closing this thread. thanks
