### ISSUE TITLE
[BUG] Merging configs (`defineConfig(c1, c2)`) sets empty arrays even on the nullable fields and it leads to an unexpected behavior

### ISSUE THREAD

**Issue by whitphx** [microsoft/playwright#28795]
### System info
- Playwright Version: 1.40.1
- Operating System: macOS 14.0
- Browser: Chromium Engine Version 120.0.6099.129
- Other info: -

### Source code

**Steps**
- Init a project with `npm init playwright@latest`.
- Update `playwright.config.ts` as below:
  ```ts
  import { defineConfig } from '@playwright/test';
  
  export default defineConfig({
    testDir: './tests',
  }, {});
  ```
- Run test with `npx playwright test` -> You will see no tests are found (`Error: No tests found`).

**Expected**

Tests are found and executed as
```sh
$ npx playwright test

Running 2 tests using 1 worker

  ✓  1 example.spec.ts:3:5 › has title (538ms)
  ✓  2 example.spec.ts:10:5 › get started link (436ms)

  2 passed (1.6s)
```
(This result can be achieved with the following `playwright.config.ts` with doesn't merge configs
```ts
import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
});
```
)

**Actual**

```sh
$ npx playwright test
Error: No tests found
```

This is because `defineConfig(c1, c2)` returns a config object whose `.projects` is `[]`, but not `undefined` as below.
```sh
❯ node
Welcome to Node.js v20.10.0.
Type ".help" for more information.
> const { defineConfig } = require("@playwright/test");
undefined
> defineConfig({}, {})
{
  expect: {},
  use: {},
  webServer: [],
  projects: [],
  [Symbol(defineConfigWasUsed)]: true
}
```
with these impl:
https://github.com/microsoft/playwright/blob/2d5488d8e31dcd3f04dbefc9e7d4f1c4b25fc8bc/packages/playwright/src/common/configLoader.ts#L34-L53
https://github.com/microsoft/playwright/blob/2d5488d8e31dcd3f04dbefc9e7d4f1c4b25fc8bc/packages/playwright/src/common/configLoader.ts#L62-L80

**Comment by yury-s** [comment]
This was fixed by https://github.com/microsoft/playwright/pull/28224 and will be released in 1.41. You can try it by installing @playwright/test@next
