### ISSUE TITLE
[Question] download.saveAs() does not automatically deleted downloaded file

### ISSUE THREAD

**Issue by kaku0225** [microsoft/playwright#28802]
Hi

I referred to the following URL https://playwright.dev/docs/api/class-download and implemented the following code.

```
  const downloadPromise = page.waitForEvent('download');
  await page.getByText('test_file').click();
  const download = await downloadPromise;

  await download.saveAs('src/static/' + download.suggestedFilename());

  expect(await download.path('src/static/test_file_folder.zip')).toBeTruthy();
 ``` 

Although it mentions All the downloaded files belonging to the browser context are deleted when the browser context is closed, when I run npx playwright test, the zip are still present locally and are not automatically deleted.

Additionally, using download.delete() does not work. Could you please tell me what might be wrong with the code?

**Comment by pavelfeldman** [comment]
It is unclear what your scenario is and what you expect to be deleted and when. Please provide full scenario we could follow/reproduce.

**Comment by kaku0225** [comment]
Sorry, I didn't describe it clearly.

-Scenario
When I access this URL https://stagingwin.smartstudy.tw/latest_news/23, I can see the file named 'test_zip_folder.zip.' Clicking on 'test_zip_folder.zip' allows to download it

-Spec
```
test('download the attachment when it exists', async ({ page }) => {
  await page.route('**/users/sessions/check_authorization', async route => {
    const jsonResponse = { success: false };
    const headers = {
      'Content-Type': 'application/json',
    };
    route.fulfill({
      status: 200,
      headers,
      body: JSON.stringify(jsonResponse),
    });
  });

  await page.route('**/articles/1?category=latest_news', async route => {
    const jsonResponse = {
      success: true,
      article: { title: 'test_latest_news', content: '<p>test_for_latest_news</p>', publish_date: '2023/12/21', attachment: 'https://winnerchoose.blob.core.windows.net/test/test_zip_folder.zip', attachment_name: 'test_file'}
    };
    const headers = {
      'Content-Type': 'application/json',
    };
    route.fulfill({
      status: 200,
      headers,
      body: JSON.stringify(jsonResponse),
    });
  });

  await page.goto('https://stagingwin.smartstudy.tw/latest_news/1');

  const downloadPromise = page.waitForEvent('download');
  await page.getByText('test_file').click();
  const download = await downloadPromise;

  await download.saveAs('src/static/' + download.suggestedFilename());

  expect(await download.path('src/static/test_file_folder.zip')).toBeTruthy();
});
```

I separately mocked `**/users/sessions/check_authorization` and `**/articles/1?category=latest_news` in my test. The test result matches my final expectation, as written in expect(await download.path('src/static/test_file_folder.zip')).toBeTruthy();, indicating a successful download. Moreover, as per my code await download.saveAs('src/static/' + download.suggestedFilename());, the download is saved in the 'src/static' directory. See the image below

### after run test
![截圖 2023-12-29 下午3 50 07](https://github.com/microsoft/playwright/assets/73519567/bbfd1965-4063-473e-a854-acdb94257556)

But I saw the following statement on this website `https://playwright.dev/docs/downloads`: 'Downloaded files are deleted when the browser context that produced them is closed.' Therefore, I would like to ask why the downloaded files are not automatically deleted after the test is completed.

Thank you for taking the time to read.

**Comment by pavelfeldman** [comment]
`Downloaded files are deleted when the browser context that produced them is closed.` refers to the downloaded artifacts that are saved into the artifacts folder, before you call saveAs. Calling save as persists them at the location you provide and does not delete them from that location after the context is closed.

**Comment by kaku0225** [comment]
Thank you for your explanation. I'll give it another try. Appreciate it!
