### ISSUE TITLE
[REGRESSION]: Tests on ["iPhone 13"] became unstable after updating to 1.40

### ISSUE THREAD

**Issue by sleepmac** [microsoft/playwright#28801]
**Context:**
- GOOD Playwright Version: 1.38
- BAD Playwright Version: 1.40
- Operating System: Ubuntu 22.04.3 LTS x86_64
- Extra: node v20.5.1

**Describe the bug**

Hi.
I am using 3 projects
...devices["Desktop Chrome"]]
...devices["iPhone 13"].
...devices["LG Optimus L70"]]

After updating from 1.38 to 1.40 version, all the tests of ...devices["iPhone 13"] became unstable, many errors and crashes.
I attach examples of several errors. They are simple and straightforward, but when rolling back to 1.38 the tests work stably.

1. Call log:
  - Waiting for locator('#tabpanel-personal-data') to be visible

2. Call log:
  - navigating to "myurl", waiting until "load"

3. Browser logs:
<launching> /home/sleepman/.cache/ms-playwright/webkit-1944/pw_run.sh --inspector-pipe --headless --no-startup-window
<launched> pid=139098
[pid=139098][err] /home/sleepman/.cache/ms-playwright/webkit-1944/pw_run.sh: строка 24: 139104 Убито WEBKIT_FORCE_COMPLEX_TEXT="1" "$MINIBROWSER" "$@"
[pid=139098] <process did exit: exitCode=137, signal=null>
[pid=139098] starting temporary directories cleanup
[pid=139098] finished temporary directories cleanup
Call log:
  - waiting for locator('[type=\'success\']').locator('button')
  - locator resolved to <button class="css-ki43zh eyv3yyn4">…</button>
  - attempting click action
  - waiting for element to be visible, enabled and stable
  - element is not stable - waiting...

4. Browser logs:

<launching> /home/sleepman/.cache/ms-playwright/webkit-1944/pw_run.sh --inspector-pipe --headless --no-startup-window
<launched> pid=134248
[pid=134248][err] WARNING: trying to load platform resource 'missingImage'
[pid=134248][err] /home/sleepman/.cache/ms-playwright/webkit-1944/pw_run.sh: строка 24: 134260 Убито              WEBKIT_FORCE_COMPLEX_TEXT="1" "$MINIBROWSER" "$@"
[pid=134248] <process did exit: exitCode=137, signal=null>
[pid=134248] starting temporary directories cleanup
[pid=134248] finished temporary directories cleanup
Call log:
  - waiting for locator('[type=\'success\']').locator('button')

**Comment by pavelfeldman** [comment]
We would need to be able to reproduce these failures locally. Also, if you could give it a try with @playwright/test@next (our nightly version), it would help to know if it is already fixed or not.

**Comment by mxschmitt** [comment]
Fee free to re-file with more details.

**Comment by sleepmac** [comment]
@mxschmitt Hi. 
I tried to reproduce the latest version of npm install -D @playwright/test@next tests on the phone 13 and they also behave unstable.
I tried again on 1.39, the tests also failed there.
Very strange behavior, I repeat, but at 1.38 there are no problems.

**Comment by mxschmitt** [comment]
@sleepmac, we need a self-contained reproducible which we can run locally in order to look into an issue like this. Would it be possible to share one with us? If you are not able to provide it over GitHub, you can also pin me on [Discord](https://aka.ms/playwright/discord).
