### ISSUE TITLE
page.route in hooks?

### ISSUE THREAD

**Issue by msmith1114** [microsoft/playwright#28806]
Pretty simple question: If I need to mock a page request/response a bunch of times for different tests...can I do that in the hook? IE: Does the "hook" code stay with the test (IE: variables/context/etc...) or does it run and then move onto the test block code without incorporating it (If that makes sense)

Im trying to think of the best way to "Always handle" a request/response mocked on a certain page. Normally I would put this in a PoM class but that doesn't feel correct since it feels test specific.

Thanks

**Comment by pavelfeldman** [comment]
beforeEach hook runs before each test and has the test's page fixture that you can route / handle. beforeAll hook runs before all tests and does not have test's page.

**Comment by msmith1114** [comment]
@pavelfeldman I guess I should've been more specific. If I add a route to a beforeEach hook....will the subsequent tests have access to that "route" that was set up or no?

**Comment by pavelfeldman** [comment]
beforeEach is a part of the test, it is a function that is called before the test body is executed. It receives the same instances of the fixtures as the test function. So if you set up page routes in beforeEach they will work in the test.
