### ISSUE TITLE
[Feature] Locator constructor/validator

### ISSUE THREAD

**Issue by sundar-ds** [microsoft/playwright#28809]
It will help if there's some kind of a locator validator feature where when we construct the locator manually, it can verify if it is getting correctly identified on the page. Very similar to the find feature in the 'Inspect' page of the browser. Will help in constructing locators where the pre-generated locator in codegen does not work by default.

**Comment by pavelfeldman** [comment]
What does 'it can verify if it is getting correctly identified on the page' mean? Could you give an example?

**Comment by sundar-ds** [comment]
For e.g., let's say there's an input field labeled 'Name' in the web page.

A validator feature where when we type the locator manually like page.get_by_role("textbox", name='Name'), it should automatically highlight the matching elements on the page. 

The above is a very simple example but there are cases where the delivered locator from 'codegen' wouldn't work so we may have to construct the locator by looking into the DOM of the web page. A common example is to locate a specific cell in a table within the page. Having such a validator feature will help us code such locators efficiently with the assurance it will work.

**Comment by pavelfeldman** [comment]
> A validator feature where when we type the locator manually like page.get_by_role("textbox", name='Name'), it should automatically highlight the matching elements on the page.

This exact feature already exists in both codegen and VS Code extension.

**Comment by sundar-ds** [comment]
Since I use playwright-python, the VS code extension wouldn't work for me. But can you pls guide me on how to use this in codegen? I only see a pick locator option but don't find an option where I can write the locator that can be validated on the UI.

**Comment by pavelfeldman** [comment]
Uncheck record and type in the Locator window.

![Screenshot from 2024-01-08 10-46-36](https://github.com/microsoft/playwright/assets/883973/3e746d6e-01ba-488c-8aec-78d4c5bc60f7)

**Comment by sundar-ds** [comment]
Excellent. Never knew this existed. Thanks!
