### ISSUE TITLE
[BUG] Step timeout is not being respected

### ISSUE THREAD

**Issue by Tallyb** [microsoft/playwright#28805]
### System info
- Playwright Version: [v1.40.1]
- Operating System: [MacOS 13+]
- Browser: All
- Other info: node 20.10 (if it matters)

### Source code
![Screenshot 2023-12-28 at 13 25 31](https://github.com/microsoft/playwright/assets/7386255/3c245387-73ce-43d3-be4e-77cd18dfce8a)

This is basically the default test, just added the line for a non existing selector with a large timeout. 
```
test('get started link', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  await page.waitForSelector('not-exist', {timeout: 90000}); // this line was 
});
```

**Steps**
- [Run the test]

**Expected**

Test to fail in 90s

**Actual**

test fails as in the image with 30s timeout, ignoring the 90s timeout specified in the line.

**Comment by pavelfeldman** [comment]
Your entire test has a timeout of 30 seconds. So your whole test timed out. See https://playwright.dev/docs/test-timeouts
