### ISSUE TITLE
[BUG] Stopping the loop after the fourth element

### ISSUE THREAD

**Issue by pawel747** [microsoft/playwright#28815]
### System info
- Playwright Version: 1.38.0
- Operating System: macOS Ventura 13.6
- Browser: Chromium
- Other info:

### Source code

`        List<Locator> elements = Set.page.locator("//span[@class='action action-delete ico ico-trash cart-product-remove']").all();

        for (Locator li : elements){
            li.click();
            Set.page.locator("//button[@class='action-primary action-accept']").click();`

I have a problem with the operation of for loops, including foreach and while. My job is to remove items from my shopping cart in the store. This requires clicking the trash icon and confirming in the popup window. The loop in the code below always executes four times. If there are more than four products in the cart, only four will be removed, the rest will remain. In "pure" selenium there is no such problem. Please help.

**Comment by pavelfeldman** [comment]
When you run

`Set.page.locator("//span[@Class='action action-delete ico ico-trash cart-product-remove']").all();`

you get following locators in your array:

```
//span[@Class='action action-delete ico ico-trash cart-product-remove.nth(0)
//span[@Class='action action-delete ico ico-trash cart-product-remove.nth(1)
//span[@Class='action action-delete ico ico-trash cart-product-remove.nth(2)
```
...

I.e. those locators point to slots in the element list. Once you start removing the elements, all these locators become wrong. I.e. second starts pointing to the third element, etc. You should either remove them in the reverse order, or always remove the .first() element w/o calling .all() at all, until the list becomes empty.

**Comment by mxschmitt** [comment]
Closing as per above. Please re-file for further questions.
