### ISSUE TITLE
[BUG] firefox playwright bot detection

### ISSUE THREAD

**Issue by lasmono99** [microsoft/playwright#28818]
When I open browser inside AppData\Local\ms-playwright and test one by one, why on firefox its show as playwright https://i.gyazo.com/1bfa2fe4d01411c4e65303aee52adf89.png

link to test : https://fingerprint.com/products/bot-detection/

But other browser, webkit its show as webdriver and chromium have very good result clean detection, please correct if this is indeed an error.

Thanks

**Comment by pavelfeldman** [comment]
I don't see any bugs here.
