### ISSUE TITLE
Playwright execution on Jenkins (without docker)

### ISSUE THREAD

**Issue by omershitrit** [microsoft/playwright#28819]
I've searching online for a tutorial explaining how to run Playwright (Java) in Jenkins pipeline, without a docker. Every tutorial, blog or stackoverflow branch led me to use a docker.

I keep getting the following error:
java.lang.RuntimeException: Failed to create driver

Caused by:
java.lang.RuntimeException: Failed to install browsers, exit code: 1

Is it even possible? (Playwright version 1.40).

Thanks!

**Comment by pavelfeldman** [comment]
That would be a Jenkins question as I am sure Playwright is working locally for you.
