### ISSUE TITLE
[QUESTION] How do I find the injected javascript from add_init_script in chromium?

### ISSUE THREAD

**Issue by epicwhale** [microsoft/playwright#28812]
When I add javascript via add_init_script to a chromium browser context, how do I find the piece of code injected in the chrome developer tools? I am trying to debug a syntax/logic error in my init script - but I can't seem to find a way to debug / view the trace it in chromium. Any tips / pointers? Thanks in advance!

For example:

```
await context2.add_init_script("""(data => {
  console.log('fooo') // <-- i don't see this in the console log, nor can I find this code in the chrome developer tools anywhere
})('""" + session_storage + """')
""")
```

I'm using https://playwright.dev/python/docs/api/class-page#page-add-init-script with python

**Comment by pavelfeldman** [comment]
I would declare a global function FOO in the snippet, and then call inspect(FOO) in the DevTools console.

**Comment by lcrespilho** [comment]
@epicwhale, I was using this same syntax for a long time, but now it seams kind of buggy, and I have to start using the `script` argument instead of giving the string argument as the first (and only) argument.

**Comment by epicwhale** [comment]
@lcrespilho sorry I didn't follow what's buggy between using it as a direct first argument vs using the script argument?

@pavelfeldman that's a good hack. Thanks for the shout.

**Comment by mxschmitt** [comment]
Closing since its answered. Please re-file for further questions.
