### ISSUE TITLE
Custom logger not working while connecting over CDP

### ISSUE THREAD

**Issue by maikelohcfg** [microsoft/playwright#28813]
### System info
- Playwright Version: [v1.39]
- Operating System: [macOS 14.1.2]
- Browser: [Chromium]
- Other info:

### Source code
```
import { Browser, chromium } from 'playwright';
let browser:Browser;

async function start(){

    browser = await chromium.connectOverCDP(`http://127.0.0.1:9222`,{
        logger: {
          isEnabled: (name, severity) => true,
          log: (name, severity, message, args) => console.log(`playwright console -> ${name}:${severity}: ${message} ${args.join(' ')}`),
        }
      });

    const page = await browser.contexts()[0].newPage();

    try{
        await page.goto('https://github.com');
        await new Promise(resolve => setTimeout(resolve, 2000));

        // removing await to throw error to catch in playwright logger sink
        page.goto('https://www.google.com');
        const closeIcon = page.locator('aside#msg-overlay .msg-overlay-bubble-header li-icon[type="chevron-down"]');
        await closeIcon.count();

    }
    catch(e){
        console.log(e);
    }
}

start();
```

**Steps**
- Connect to the existing browser instance using connectOverCDP providing a logger sink
- Perform any action to trigger error that should be logged by Playwright

**Expected**
We should see in the console logs from playwright

**Actual**

None logs from playwright

**Comment by mxschmitt** [comment]
As per the [docs](https://playwright.dev/docs/api/class-browsertype#browser-type-connect-over-cdp), there is no such option as `logger` on connectOverCDP, thats why its not working.

We recommend [`// @ts-check`](https://www.typescriptlang.org/docs/handbook/intro-to-js-ts.html#ts-check) so you see such errors in your IDE, e.g. VSCode.

See [here](https://playwright.dev/docs/debug) for the options you have available when debugging tests. Would that work for you? Trace Viewer is usually our recommendation when debugging tests.

**Comment by maikelohcfg** [comment]
Sorry but based on the doc there is one `logger` option available for `connectOverCDP`
![image](https://github.com/microsoft/playwright/assets/939605/6e3e2bc9-27be-4473-b07a-2bcd1ceca2c6)

**Comment by mxschmitt** [comment]
You are right, sorry I was too quick! It's indeed a bug, I created a fix for it here https://github.com/microsoft/playwright/issues/28813.
