### ISSUE TITLE
[QUESTION] Playwright/Java: POST multipart with different content types

### ISSUE THREAD

**Issue by napervomay** [microsoft/playwright#28811]
### System info
- Playwright Version: [v1.35]
- Other info: Java 17

### Question ###
Dear all, I have an endpoint which requires multipart/form-data with different content types. One of them is json payload, another one is an excel file.
How these types should be provided?
I've searched across documentation for java version, but there only an example without separate content-types is provided.
I've tried to write a test as in source code below but have different errors from server:

- when uncommenting `headers.put("Content-Type", "multipart/form-data"`, I receive "Internal server error: the request was rejected because no multipart boundary was found"
- if keeping it commented as advised in #20249, the server responds with "Internal server error: Content-Type 'application/octet-stream' is not supported"
- if replacing `data.set("file", Paths.get("src/test/resources/model_templates/ComponentsFromExcel.xlsx"))` with `data.set("file", new FilePayload("someFile.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            Files.readAllBytes(Paths.get("someFile.xlsx"))))` - still getting the same message with "Internal server error: Content-Type 'application/octet-stream' is not supported"

Looks like json part is accepted, but the problem is in the file part.
Please advise how to fix the issue and provide all required content-types correctly for such case.
Thanks in advance!

### Source code

```java
var playwright = Playwright.create();
final var headers = new HashMap<String, String>();
headers.put("accept", "application/json");
headers.put("authorization", "Basic dGVzdDpwYXNzd29yZA==");
// headers.put("Content-Type", "multipart/form-data");

var context = playwright.request().newContext(
    new APIRequest.NewContextOptions()
        .setBaseURL("http://some.url/")
        .setExtraHTTPHeaders(headers)
);

var requestOptions = RequestOptions.create();
var data = FormData.create()
    .set("textValue", "someString") //this one should be application/json
    .set("file", Paths.get("someFile.xlsx")); //this one should be excel file type

requestOptions.setMultipart(data); 
var response = context.post("endpointPath", requestOptions);
```

**Curl request/response example from this endpoint:**

```bash
curl -X 'POST' \
  'https://some/url' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic ' \
  -H 'Content-Type: multipart/form-data' \
  -F 'textValue=someString;type=application/json' \
  -F 'file=@someFile.xlsx;type=application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
```

**Comment by mxschmitt** [comment]
Sorry for the late reply. 

> headers.put("Content-Type", "multipart/form-data"

this does not need to be specified, if you are doing setMultipart, we already set the header for you. See also https://github.com/microsoft/playwright/issues/20249#issuecomment-1400821062.

From a small investigation the cURL request creates the following:

```
--------------------------DBZuup29PgHZR47x52lwdO
Content-Disposition: form-data; name="textValue"
Content-Type: application/json

someString
--------------------------DBZuup29PgHZR47x52lwdO
Content-Disposition: form-data; name="file"; filename="foo.txt"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

test123

--------------------------DBZuup29PgHZR47x52lwdO--
```

note: there is an application/json header in the Content-Disposition part without fileName, while we we create the following:

```
------WebKitFormBoundaryjwObfIcYA8XPgduy
content-disposition: form-data; name="textValue"; filename=""
content-type: application/json

someString
------WebKitFormBoundaryjwObfIcYA8XPgduy
content-disposition: form-data; name="file"; filename="myfile.xlsx"
content-type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

this is test
------WebKitFormBoundaryjwObfIcYA8XPgduy--
```

So either you don't have the application/json header attached or an empty filename. 

```java
package org.example;

import com.microsoft.playwright.*;
import java.nio.file.Paths;
import com.microsoft.playwright.APIRequest;
import com.microsoft.playwright.APIRequestContext;
import com.microsoft.playwright.Playwright;
import com.microsoft.playwright.options.RequestOptions;
import com.microsoft.playwright.options.FilePayload;
import com.microsoft.playwright.options.FormData;
import java.nio.charset.StandardCharsets;

import java.util.HashMap;
import java.util.Map;

public class Test {
  public static void main(String[] args) {
    try (Playwright playwright = Playwright.create()) {
      var context = playwright.request().newContext();

      var requestOptions = RequestOptions.create();
      var data = FormData.create()
          .set("textValue",  new FilePayload("", "application/json", "someString".getBytes(StandardCharsets.UTF_8)))
          .set("file", new FilePayload("myfile.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "this is test".getBytes(StandardCharsets.UTF_8)));

      requestOptions.setMultipart(data); 
      var response = context.post("https://httpbin.org/post", requestOptions);
      System.out.println(response.text());
    }
  }
}

```

From our side I think we should not put a fileName there if none is supplied.

Could you try if the code above works for you? Http request body wise it looks very similar now!

**Comment by napervomay** [comment]
@mxschmitt thanks, it worked!
I would never have guessed that simple string body should be sent as a file payload as well.
Could you please add this example to documentation for future reference?
