### ISSUE TITLE
[Feature] Can we have toHaveScreenshot() to be used in global-teardown

### ISSUE THREAD

**Issue by Vivek-Kini** [microsoft/playwright#28827]
Let us know what functionality you'd like to see in Playwright and what your use case is.
There are some image comparisons that are done at the end of all tests in `global teardown`, or I would like to know a way to make sure I can run some scenarios at the end of test suite?

Do you think others might benefit from this as well? 
Yes

![image](https://github.com/microsoft/playwright/assets/106667767/30265d63-14e2-432b-899b-63de83f4588a)

**Comment by mxschmitt** [comment]
If you are using project dependencies rather than globalTeardown it should just work: https://playwright.dev/docs/test-global-setup-teardown#teardown

**Comment by mxschmitt** [comment]
Closing as per above.
