### ISSUE TITLE
[BUG] unable to login into application 

### ISSUE THREAD

**Issue by VenkatRavali** [microsoft/playwright#28828]
### System info
- Playwright Version: [v1.XX]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

[We will only be able to work on the issues that we can reproduce.]

[Please provide a self-contained example in a form of a snippet, archive or a repository.]

[Repro scenario can't be large or have external dependencies.]

**Steps**
- [Run the test]
Able to login into  application 

[Describe actual behavior
After entering the username and password, clicking the signon button 
But not navigating the home page
But it's shows a sign on button clicks successful

**Comment by mxschmitt** [comment]
This issue does not contain any repro, so closing by that. Please follow the issue template, thanks!

**Comment by VenkatRavali** [comment]
Ok
