### ISSUE TITLE
[BUG]Unable to login application 

### ISSUE THREAD

**Issue by VenkatRavali** [microsoft/playwright#28832]
### System info
- Playwright Version: [v10.2.5]
- Operating System: [Windows]
- Browser: [Chromium, Firefox, WebKit]
- Other info:

### Source code

Const { test, expect } = require('@playwright/test')

test('padmin homepage', async ({page}) => {

await page.goto('https://pp-prompt-apps.kp.org/padmin/#/login')
await page.getByRole('button', { name: 'login' }).click();
await page.getByPlaceholder('National user ID').fill('××××');
await page.getByPlaceholder('Password').click()
await Page.getByPlaceholder('password').fill('××××')
await page.getByRole('link', { name: 'Sign On' }).click();

[Please provide a self-contained example in a form of a snippet, archive or a repository.]

[Repro scenario can't be large or have external dependencies.]

**Steps**
-Run test 

npx playwright test

**Expected**

[Describe expected behavior]
able to login into application
**Actual**

[Describe actual behavior]
not able to login into application

**Comment by mxschmitt** [comment]
This reproduction involves external sites which are not reachable for us. We need a self-contained reproduction in order to triage issues like this. Please follow the bug issue template.
