### ISSUE TITLE
[BUG][JENKINS][SHARDING][REPORT]When running on Jenkins CI with sharing, the reports are getting overridden and we are not getting the correct merged report

### ISSUE THREAD

**Issue by CkumarGitHub** [microsoft/playwright#28837]
### System info
- Playwright Version: [v1.40]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info: CI Jenkins

### Source code

Jenkins Pipeline Script

```Jenkinsfile
/* groovylint-disable CompileStatic, DuplicateMapLiteral, DuplicateNumberLiteral, DuplicateStringLiteral, GStringExpressionWithinString, LineLength, MethodReturnTypeRequired, NestedBlockDepth, NoDef, SpaceAroundOperator, UnnecessaryParenthesesForMethodCallWithClosure, VariableTypeRequired */
pipeline {
    agent any
    parameters {
        string(name: 'SHARDS', defaultValue: '2', description: 'How many shards should we use? (enter number, job will fail with string')
    }
    options {
        ansiColor('xterm')
    }
    stages {
        stage('Playwright Tests') {
            steps {
                script {
                    doDynamicParallelTestSteps()
                    mergeShardReportFiles()
                }
            }
        }
        stage('Publish Report') {
            steps {
                unstash 'htmlreport'
                publishHTML(target : [
                allowMissing: false,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'playwright-report',
                reportFiles: 'index.html',
                reportName: 'PlaywrightReport',
                reportTitles: 'Playwright_Report'
        ]
      )
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}

def doDynamicParallelTestSteps() {
    tests = [:]
    int totalShards = Integer.parseInt(params.SHARDS)
    for (i = 0; i < totalShards; i++) {
        def shardNum = "${i + 1}"
        tests["${shardNum}"] = {
            node {
                stage("Shard #${shardNum}") {
                    docker.image('mcr.microsoft.com/playwright:v1.40.0-focal').inside {
                        git branch: 'feature/xyz',
                            credentialsId: 'xxxx',
                            url: 'git utl'
                        echo "\033[34m***** Installing playwright\033[0m \033[36mand\033[0m \033[35mnode modules dependencies! for shard = ${shardNum} *****\033[0m"
                        sh '''
                            npm ci
                            '''
                        catchError {
                            echo "\033[34m***** Running\033[0m \033[36mPlaywright\033[0m \033[35mTests! on shard = ${shardNum} *****\033[0m"
                            sh "npx playwright test --shard ${shardNum}/${totalShards}"
                            sh 'ls -lrta'
                            sh 'find blob-report -type f'
                        }
                        stash includes: 'blob-report/*', name: "shard${shardNum}"
                    }
                }
            }
        }
    }
    parallel tests
}
def mergeShardReportFiles() {
    node {
        stage('Merge Reports') {
                    docker.image('mcr.microsoft.com/playwright:v1.40.0-focal').inside {
                        git branch: 'feature/xyz',
                            credentialsId: 'xxxx',
                            url: 'git url'
                        echo '\033[34m***** Installing playwright\033[0m \033[36mand\033[0m \033[35mnode modules dependencies for merge report build! *****\033[0m'
                        sh '''
                            npm ci
                            '''
                        catchError {
                            doUnstashShards()
                            echo '\033[34m***** Merging\033[0m \033[36mshards\033[0m \033[35mreports! *****\033[0m'
                            sh 'npx playwright merge-reports --reporter html all-blob-reports'
                            archiveArtifacts artifacts: 'all-blob-reports/*', allowEmptyArchive: false
                            archiveArtifacts artifacts: 'playwright-report/*', allowEmptyArchive: false
                            stash includes: 'playwright-report/index.html', name: 'htmlreport'
                        }
                    }
        }
    }
}
def doUnstashShards() {
    sh 'rm -rf all-blob-reports'
    sh 'mkdir -p all-blob-reports'
    int totalShards = Integer.parseInt(params.SHARDS)
    for (i = 0; i < totalShards; i++) {
        unstash "shard${i+1}"
    }
    archiveArtifacts artifacts: 'blob-report/*', allowEmptyArchive: false
    sh 'mv -v blob-report/* all-blob-reports/'
    sh 'ls -lrta'
    sh 'find all-blob-reports -type f'
}
```
Error on CI:

I try to move the report from blob-report to all-blob-reports
<img width="1389" alt="Screenshot 2024-01-03 at 12 41 10 AM" src="https://github.com/microsoft/playwright/assets/34965254/c8cc2635-d3b4-486a-9973-b98ce39b19b3">
FIrst run is passed but other parallel runs fails to find the report file
mv -v blob-report/report-2.zip all-blob-reports/report-shard2.zip
mv: cannot stat 'blob-report/report-2.zip': No such file or directory
script returned exit code 1

**Comment by mxschmitt** [comment]
This looks like a Jenkins configuration issue, I'd try moving the mv blob-reports into the unstash:

     for (i = 0; i < totalShards; i++) {
         unstash "shard${i+1}"
         mv blob-reports/* all-blob-reports
     }

Does unstash override the previous blob-reports directory?

**Comment by CkumarGitHub** [comment]
@mxschmitt I tried that as well.
If I use only 2 shards then it works fine every time. But if I hav more than 2 then the report is getting overridden.
Example
Shard 1 finishes 1st then report1 is generated
Shard 3 finished before Shard 2, then report3 is there in both blob report folder for Shard 2 &3
How Playwright is handling the sharing report generation i.e If Shard 3 finishes before 2 then report name will be report 3 or 2 ?

**Comment by MindaugasMateika** [comment]
If reports are overwritten that means your shards are using same workspace somehow? Do you even need sharding in such case? 

I'm using Jenkins with shards myself with no problems. Each shard creates a separate workspace, after run report is stashed.
```
stash includes: "blob-report/report-*.zip", name: "report-${SHARD}"
```

After all shards are finished, reports are unstashed and then merged.
```
            unstash 'report-1'
            unstash 'report-2'
            unstash 'report-3'
            ...
            
           sh 'pnpm playwright merge-reports --config=merge.config.ts ./blob-report'
```

I'm using fully declarative pipeline.

**Comment by CkumarGitHub** [comment]
@MindaugasMateika I also think the workspace is shared.
How are you handling the dynamic creation os shards? OR you have hardcoded the no of shards you want to use like 3 or 4?
Could you share your fully declarative pipeline like the template ?

**Comment by mxschmitt** [comment]
@MindaugasMateika are you interested in [contributing](https://github.com/microsoft/playwright/blob/main/docs/src/test-sharding-js.md) a Jenkins matrix example to our docs which will merge the reports in the end?

**Comment by MindaugasMateika** [comment]
I'm not creating shards dynamically, it's hardcoded. It has little to no downsides for me. The stripped down pipeline is below. Merge config is probably optional, it just has different reporters but in general I'm not changing anything related to blob reports.

@mxschmitt I'll think about it but I'm not really keen on doing that. There are a lot of variables when it comes to Jenkins - declarative vs scripted, whether docker is setup, stashing, plugins, etc. It is very unlikely that example pipeline would work out of the box for anyone.

```
pipeline {
  agent any
  environment {
    MAX_SHARDS = '6'
  }
  stages {
    stage('Parallel tests') {
      parallel {
        stage('Run tests in shard 1') {
          agent {
            docker {
              label 'some machine label'
              image 'pw docker image'
            }
          }
          environment {
            SHARD = '1'
          }
          steps {
            script {
              sh "npx playwright test --shard=${SHARD}/${env.MAX_SHARDS}"
            }
          }
          post {
            always {
              stash includes: "blob-report/report-*.zip", name: "report-${SHARD}"
            }
          }
        }
        stage('Run tests in shard 2') {
          // another shard
        }
      }
    }
    stage('Merge & archive reports') {
      steps {
          catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
            unstash 'report-1'
            // unstash other reports from shards

            script {
              sh 'npx playwright merge-reports --config=merge.config.ts ./blob-report'
            }
          }
      }
    }
  }
}
```

**Comment by mxschmitt** [comment]
cool, feel free to send a PR. I saw this, which looked promising: https://www.jenkins.io/doc/book/pipeline/syntax/#declarative-matrix

**Comment by zubairmd0214** [comment]
@MindaugasMateika Could you please help me with this, I have tried with above but still latest shard report is replacing old shard report.
pipeline {
    agent any
    environment {
        MAX_SHARDS = '2'
    }

    stages {

        stage('Checkout Code') {
            steps {
                git(
                    branch: 'XXXXXXX',
                    credentialsId: 'your-gitlab-credential-id',
                    url: 'https://gitlab.com/XXXXXXX.git'
                )
            }
        }

        stage('Install Dependencies') {
            steps {
                bat '''
                    cd "%WORKSPACE%"
                    npm install
                    npx playwright install
                '''
            }
        }

        stage('Parallel tests') {
            parallel {

                stage('Run tests in shard 1') {
                    environment {
                        SHARD = '1'
                    }
                    steps {
                        script {
                            bat "npx env-cmd -e qa5 playwright test --shard=${SHARD}/${env.MAX_SHARDS} --reporter=blob --output=blob-report-shard1"
                        }
                    }
                    post {
                        always {
                            stash includes: "blob-report-shard1/**", name: "report-1"
                        }
                    }
                }

                stage('Run tests in shard 2') {
                    environment {
                        SHARD = '2'
                    }
                    steps {
                        script {
                            bat "npx env-cmd -e qa5 playwright test --shard=${SHARD}/${env.MAX_SHARDS} --reporter=blob --output=blob-report-shard2"
                        }
                    }
                    post {
                        always {
                            stash includes: "blob-report-shard2/**", name: "report-2"
                        }
                    }
                }

            }
        }

        stage('Merge & archive reports') {
            steps {
                catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                    // Unstash all shards
                    unstash 'report-1'
                    unstash 'report-2'

                    script {
                        // Merge blob reports into HTML in a single folder
                        bat 'npx playwright merge-reports blob-report-shard1 blob-report-shard2 --reporter=html --output=playwright-report'
                    }
                }
            }
        }

        stage('Archive Final HTML Report') {
            steps {
                archiveArtifacts artifacts: 'playwright-report/**', fingerprint: true
            }
        }

    }
}
