### ISSUE TITLE
[BUG]_ Getting " PrintDeps.exe Bad image" pop-ups while running tests from terminal using ibm_db package with Playwright with JavaScript

### ISSUE THREAD

**Issue by 54995610** [microsoft/playwright#28846]
System info
Playwright Version: v.1.40.1, JavaScript
Operating System: Windows 11 Enterprise 64, Version 10.0.19045 Build 19045
Browser: All (for example: Chromium version 
Node version: v.18.19.0
ibm_db v.3.2.1 (https://www.npmjs.com/package/ibm_db)

We are using Playwright with Javascript for our UI automation where we are also establishing a connection to IBM Data base by using following two :-

  var ibmdb = require('ibm_db')
  const open = util.promisify(ibmdb.open)

When I am executing the script I am getting 8 different PrintDeps.exe bad image pop-ops where I have to close all those 8 pop-ups manually and that's when the execution is starting.

We are using version :- "@playwright/test": "^1.40.1".

Note:- I did placed the " var ibmdb = require('ibm_db')" inside the function and I was able to execute the script without any issues. Actual issue comes when I execute my test scripts in Parallel or sequentially, first test script will get executed successfully and as soon second test script starts, we are seeing following 8 pop-ups.

Observation :- When we do npx playwright install on my machine it is downloading "chromium-1091" folder in "C:\Users\Userid\AppData\Local\ms-playwright" folder where I think it is causing the issue.

![image](https://github.com/microsoft/playwright/assets/104173297/f801cf93-ae65-4cd0-bd7b-23ccf7d08f94)

![image](https://github.com/microsoft/playwright/assets/104173297/81052d03-59c1-4186-8bed-7f517930ff23)

![image](https://github.com/microsoft/playwright/assets/104173297/9b71c4db-e829-4cf7-be63-40a9ad106de8)

![image](https://github.com/microsoft/playwright/assets/104173297/293f9604-f84b-463b-b61e-2f3a8b9b37fb)

![image](https://github.com/microsoft/playwright/assets/104173297/81dfa3ed-7e36-4a94-a5b8-f479c5548fed)

![image](https://github.com/microsoft/playwright/assets/104173297/1ce21bf7-f9d8-4dac-963b-52fe3617b165)

![image](https://github.com/microsoft/playwright/assets/104173297/1ad84c4a-9d77-49b4-96c5-ac66ea448eef)

Any help is much appreciated.

**Comment by mxschmitt** [comment]
ibm_db is a native Node.js module, after they load the bindings here:

https://github.com/ibmdb/node-ibm_db/blob/0e14011fb3cc60157348bf49870352e5eac6dc1e/lib/odbc.js#L57

it stops working. I recommend filing an issue in [their repository](https://github.com/ibmdb/node-ibm_db/issues), maybe they immediately know whats going on, since they seem to be doing a lot of things in their native (CPP) part: https://github.com/ibmdb/node-ibm_db/tree/master/src which break us.

**Comment by 54995610** [comment]
Thank You, 

I created bug under node/ibm_db repository :-

https://github.com/ibmdb/node-ibm_db/issues/974
