### ISSUE TITLE
Chaining filter has inconsistent results

### ISSUE THREAD

**Issue by jcrans13** [microsoft/playwright#28845]
### System info
- Playwright Version: 1.40.1
- Operating System: Windows 10
- Browser: Chromium

Error: locator.click: Error: strict mode violation: locator('a').filter({ has: locator('//img[@src="assets/images/16x16/yellow.png"]') }).locator('a') resolved to 30 elements:
    1) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Some Name and Info' }).locator('a')
    2) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Some Name and Info' }).locator('a')
    3) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Some Name and Info' }).locator('a')
    4) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Some Name and Info' }).locator('a')
    5) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Some Name and Info' }).locator('a')
    6) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Some Name and Info' }).locator('a')
    7) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Some Name and Info' }).locator('a')
    8) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Some Name and Info' }).locator('a')
    9) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Some Name and Info' }).locator('a')
    10) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Some Name and Info' }).locator('a')
    ...

Call log:
  - waiting for locator('a').filter({ has: locator('//img[@src="assets/images/16x16/yellow.png"]') }).locator('a')

Code snippet:
`await page.locator('a').filter({ hasText: firstLast }).filter({ has: page.locator('//img[@src="assets/images/16x16/yellow.png"]')}).locator('a').click({ button: 'right' });`

I am attempting to right click an element on the page with a specific name AND has a specific image. The error that I am sometimes getting seems to ignore the first filter in the line of code. Is chaining filters not best practice? I have tried multiple workarounds for this selector, including adding a name parameter to the first 'a' selector. Nothing I have done seems to work consistently.

**Expected**
The snippet of code should consistently work or not work

**Actual**
The snippet of code works about 70% of the time

**Comment by mxschmitt** [comment]
This issue is not following the bug template, please re-file with following the bug template so we can run it locally with clear reproduction steps. Thanks for your understanding.
