### ISSUE TITLE
[BUG] getByRole("heading") can't match name from input value contents

### ISSUE THREAD

**Issue by WestonThayer** [microsoft/playwright#28848]
### System info
- Playwright Version: v1.40.1
- Operating System: All
- Browser: Chromium
- Other info:

### Source code

```js
test("heading should be located", async ({ page }) => {
  await page.setContent(`
<h1>
  <input type="text" value="Foo bar">
</h1>
  `);

  await expect(page.getByRole("heading", { name: "Foo bar" })).toBeVisible();
  // Fails to locate
});
```

**Steps**
- Run the test code

**Expected**

The `<h1>` should be located successfully. Chromium DevTools Accessibility inspector shows that the `<h1>`'s accName is `"Foo bar":

<img width="234" alt="image" src="https://github.com/microsoft/playwright/assets/709153/af878d50-be4b-47c1-882b-cca347fc9006">

**Actual**

Fails to locate.

### Notes

`getByRole` *is* able to locate headings that get their accNames from content (ex: `<h1><a href="#">Foo bar</a></h1>` locates with `page.getByRole("heading", { name: "Foo bar" })` successfully.

Is Playwright actually consulting Chromium's accessibility tree for `getByRole`?

edit: I understand better now, no Playwright is not using [CDP's Accessibility Domain](https://chromedevtools.github.io/devtools-protocol/tot/Accessibility/). It's [roleSelectorEngine](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/injected/roleSelectorEngine.ts) is an injected script, working entirely in JS/DOM land attempting to mimic the browser's own accessibility tree computations.

I guess that makes sense, certainly more x-browser friendly. But sure seems like a tough job to match the browser 1:1, accessibility computations are so dang complicated (and often evolving). This approach also may provide a slight false sense of security as it could successfully locate an element that the browser actually botched the accessibility calc for (due to regression or quirk).

I'd be great if it was possible to [extend selectors](https://playwright.dev/docs/extensibility) with a **non** injected engine.

**Comment by WestonThayer** [comment]
Noting the relevant spec: https://www.w3.org/TR/accname/#mapping_additional_nd_te step 2.E:

> E. Otherwise, if the current node is a control embedded within the label (e.g. the label element in HTML or any element directly referenced by aria-labelledby) for another [widget](https://www.w3.org/TR/accname/#dfn-widget), where the user can adjust the embedded control's value, then include the embedded control as part of the text alternative in the following manner:
> - If the embedded control has role [textbox](https://www.w3.org/TR/wai-aria/#textbox), return its **value**.

**Comment by dgozman** [comment]
Investigation notes:

- Step 2E says "embedded within a label", which is not the case here.
- However, all browsers report "Foo bar" as a accessible name.
- `dom-accessibility-api` has a special case for this, against the spec: https://github.com/eps1lon/dom-accessibility-api/blob/main/sources/accessible-name-and-description.ts#L611-L614

**Comment by WestonThayer** [comment]
Thank you!
