### ISSUE TITLE
[BUG] outputFile option with blob reporter is not working

### ISSUE THREAD

**Issue by marcusNumminen** [microsoft/playwright#28841]
### System info
- Playwright Version: v1.40.1
- Operating System: windows 10
- Browser: All
- Other info:

__outputFile__ option with blob reporter is not working. It seems like outputFile  is ignored. If this was solved then we could quite easily merge reports from multiple playwright runs. A work around for this s to use outputDir option like this: 
```
['blob', {outputDir: `blob-report/blob_${Date.now()}`}]
```
but then we have to run a script that will copy and renamed these zip files to a folder so we can run the merge tool for creating the report. 
One of the reason why we want to use this is that we can run different projects with different amount of workers since this is not currently supported.

### Source code
playwright.conf.ts
```
import { defineConfig, devices } from '@playwright/test';
export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: [
    ['html'], 
    ['list'],
    ['blob', {outputFile: `blob-report/blob_${Date.now()}.zip`}]
  ],
  use: {
    trace: 'on-first-retry',
  },
  projects: [
    {
      name: 'chromium1',
      use: { ...devices['Desktop Chrome'] },
      testMatch: 'example1.spec.ts',
    },
    {
      name: 'chromium2',
      use: { ...devices['Desktop Chrome'] },
      testMatch: 'example2.spec.ts',
    },
  ],
});
```
example1.spec.ts
```
import { test, expect } from '@playwright/test';

test('has title', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);
});
```
example2.spec.ts
```
import { test, expect } from '@playwright/test';

test('get started link', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Click the get started link.
  await page.getByRole('link', { name: 'Get started' }).click();

  // Expects page to have a heading with the name of Installation.
  await expect(page.getByRole('heading', { name: 'Installation' })).toBeVisible();
});

```

**Steps**
Run the test from commandline like this:
`npx playwright test --project=chromium1 --workers 4 && npx playwright test --project=chromium2 --workers 1`

**Expected**
the outputFile option should be respected and we should have two zip files in the 'blob-report' folder named similar to these: _blob_1704269268681.zip_ and _blob_1704269350013.zip_

**Actual**
the outputFile is ignored and the we only get one report.zip file (guessing default behavior blob report)

**Comment by mxschmitt** [comment]
There is no such option as `outputFile`, only `outputDir` as of today as per the [docs](https://playwright.dev/docs/test-reporters#blob-reporter).

In the next release we'll add `fileName` as an option (https://github.com/microsoft/playwright/pull/28525) which seems to work for your use-case.

**Comment by marcusNumminen** [comment]
Cool!! Then I'll wait for the next release then. Thanks!!!

**Comment by mxschmitt** [comment]
Closing by that, in the meantime if wanted, you can try out Canary: https://playwright.dev/docs/canary-releases

(might be more unstable than the current stable)

**Comment by marcusNumminen** [comment]
@mxschmitt I tries the Canary version but I still only get one file...
In the conf file I added this:
['blob', {fileName: `blob_${Date.now()}.zip`}]

I think the folder is delete every run so if this is the design this wont work for me

**Comment by mxschmitt** [comment]
Would copying the blobs into a shared folder work for you? Something like `mv blob-report/* all-blobs`

I can bring it up later in the team meeting if it does not. So far our contract was that the blob-report directory always contained the blob of the last test run, hence we deleted it. Similar things we do for html-report or test-results directory.

**Comment by marcusNumminen** [comment]
I can of course run it like this:
```
npx playwright test --project=chromium1 --workers 4 && mv blob-report/* all-blobs && npx playwright test --project=chromium2 --workers 1 && mv blob-report/* all-blobs
```
but I don't think thats a pretty solution. I could perhaps also look into if I could create a reporter that this for me

**Comment by mxschmitt** [comment]
What is the reason in the first place that you are running it manually sequentially and then merging?

Looks like [project dependencies](https://playwright.dev/docs/test-projects#dependencies) would work well for you, then you don't have to merge at all.

**Comment by marcusNumminen** [comment]
My main reason is to run different projects with different amount of workers and currently this isn't supported. So this is more of a "workaround" approach for that problem :) 
In my case I have a set of "destructive tests" that I can only run with 1 worker. I also have an another project where I use both api and UI tests. For the api test (the majority of the tests) I want to run with 10 workers while the UI test I can only use 2 workers

**Comment by mprykhodko** [comment]
> What is the reason in the first place that you are running it manually sequentially and then merging?
> 
> Looks like [project dependencies](https://playwright.dev/docs/test-projects#dependencies) would work well for you, then you don't have to merge at all.

@mxschmitt Our Team is exactly in the same boat. We have multiple projects (must have in our setup) that need to run in sequence and all tests on projects need to be executed in parallel. We can't use dependencies since if at least one test fails in dependency, project, that depends on it, will be skipped.
The issue we have is blob reports being replaced after every run. Would be great to have sort of retention logic. I know we can move them after each run, it's just maybe Playwright will have some native support for multiple blob reports' retention in the same folder?
Thanks!
