### ISSUE TITLE
scrollIntoView

### ISSUE THREAD

**Issue by githublin8888** [microsoft/playwright#28842]
The element is down at the page, almost at the buttom. I have tried approaches but none of them can bring the element to the viewport. Approach 1 and 2 brings to the the same position as in the attached picture 1. Approach 3 scrollIntoViewIfNeeded does not work at all in this case. The target element is in picture 2. Thanks in advance. 
 
import type { Page, Locator } from '@playwright/test';

export class AllProductsPage {
    private readonly startOrder: Locator;
    constructor(public readonly page: Page) {
        this.startOrder = this.page.getByTestId('start-order-button');
    }
 async selectVägkartanraster() {

Approach 1:
          await this.page.evaluate(() => {
             window.scrollBy(0, 30000);
         });
         await this.page.getByRole('img', { name: 'Vägkartan raster' }).click(); 

Approach 2:      const elementHandle = await this.page.locator('img[role="img"][alt="Vägkartan raster"]');
  
          await this.page.evaluate(() => {
              window.scrollTo(0, document.body.scrollHeight);
          });
          await this.page.waitForTimeout(1000);
  
          while (true) {
              const boundingBox = await elementHandle.boundingBox();
              const isElementVisible = boundingBox !== null && boundingBox.y >= 0;
  
              if (isElementVisible) {
                  break;
              }
              await this.page.evaluate(() => {
                  window.scrollBy(0, 5000);
              });
              await this.page.waitForTimeout(1000);
          }
  
           Click on the element
          await elementHandle.click(); 
Approach 3:
        const elementHandle = this.page.getByRole('img', { name: 'Vägkartan raster' });
        await elementHandle.scrollIntoViewIfNeeded;
        await elementHandle.click();}

//Approach  1 and 2 gets to this position
![Skärmbild (35)](https://github.com/microsoft/playwright/assets/117076811/f2193446-3157-4700-80eb-c1bed57bee19)

//the target element is here
![Skärmbild (36)](https://github.com/microsoft/playwright/assets/117076811/defe1798-e27c-4907-9550-4370fd5dd447)

**Comment by mxschmitt** [comment]
Playwright does automatically scroll for clicks, fills etc. why do you want to scroll manually?

Approach 3 does not work, because you are not evaluating the function, it should be this instead:

    await elementHandle.scrollIntoViewIfNeeded();

nit: its not called an elementHandle, its called a Locator.

Approach 2 does not work, because elements also have boundingBox which are not in the current viewport.

**Comment by githublin8888** [comment]
> Playwright does automatically scroll for clicks, fills etc. why do you want to scroll manually?
> 
> Approach 3 does not work, because you are not evaluating the function, it should be this instead:
> 
> ```
> await elementHandle.scrollIntoViewIfNeeded();
> ```
> 
> nit: its not called an elementHandle, its called a Locator.
> 
> Approach 2 does not work, because elements also have boundingBox which are not in the current viewport.

**Comment by githublin8888** [comment]
> Playwright does automatically scroll for clicks, fills etc. why do you want to scroll manually?
> 
> Approach 3 does not work, because you are not evaluating the function, it should be this instead:
> 
> ```
> await elementHandle.scrollIntoViewIfNeeded();
> ```
> 
> nit: its not called an elementHandle, its called a Locator.
> 
> Approach 2 does not work, because elements also have boundingBox which are not in the current viewport.

It does not  automatically scroll for clicks if there's a long list and the element sits at the buttom of the page
