### ISSUE TITLE
[Feature] Export the type signatures for utils from playwright-core 

### ISSUE THREAD

**Issue by Dombo** [microsoft/playwright#28855]
> Let us know what functionality you'd like to see in Playwright and what your use case is.

I'd like to use the methods from playwright-core in my playwright tests in select situations, but the type definitions for most of these methods used throughout playwright itself are seemingly not exported. 

For instance I'd like to use waitForResponse in the form that takes a callback and leverage the [urlMatches fn](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/utils/network.ts#L119C17-L119C27) directly, see example below.

This could well be my misconfiguration of my tsconfig or project but I'm unable to import this or any helper without type signatures whilst also using the `tsconfig.json` [suggested in the docs](https://playwright.dev/docs/test-typescript#manually-compile-tests-with-typescript).

```typescript
import { urlMatches } from "playwright-core"

const appDeletionResponse = this.page.waitForResponse(response => {
        // desired: urlMatches(baseUrl, response.url(), `**/secrets/*/organizations/*/projects/*/apps/${name}`) && response.request().method() === "DELETE"
        response.url().includes(`/apps/${name}`) && response.request().method() === "DELETE"
    }
);
```
 
> Do you think others might benefit from this as well?

I searched the tracker and I'm the first to ask, so it's hard to say AFAICT. Might just be me. I appreciate there's a balance between stability guarantees for the API you publish for consumption and agility to change utilities used throughout the project. In this case, the concept of using glob matchers for the URL in `waitForResponse` 'leaks' out into test implementation when using the first form of waitForResponse so I'd appreciate the ability to use the same glob matchers for URLs when using the function in it's second form (without having to reimplement the same logic that's in playwright-core).

Thank you for your efforts on this project, it's incredibly flexible.

**Comment by mxschmitt** [comment]
We consider urlMatches an implementation details, hence its not exported. We recommend for now using a glob library from NPM or using RegExp to match your URL string to your liking.
