### ISSUE TITLE
Playwright spawn unknown error seen at dotnet playwright

### ISSUE THREAD

**Issue by DipakTated** [microsoft/playwright#28858]
While application tries to launch playwright, following error is seen:

 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Playwright.Transport.Connection.<InnerSendMessageToServerAsync>d__40`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Playwright.Transport.Connection.<WrapApiCallAsync>d__50`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Playwright.Core.BrowserType.<LaunchAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Fluke.Core.Local.Library.GraphScreenshot.<RetrieveGraphs>d__2.MoveNext()**spawn UNKNOWN**
Call log:
  - <launching> C:\Users\DT-st\AppData\Local\ms-playwright\chromium-1091\chrome-win\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=C:\Users\DT~1\AppData\Local\Temp\playwright_chromiumdev_profile-y3UGmP --remote-debugging-pipe --no-startup-window

**Comment by DipakTated** [comment]
i could notice in call log, that somehow playwright is trying to access 2 profiles in my machine
DT-st(as seen in 1 st line of call log)  and DT-1 (as seen in last line of call log). why is that?

**Comment by mxschmitt** [comment]
Could you provide us clear reproduction steps?

Does the `C:\Users\DT-st\AppData\Local\ms-playwright\chromium-1091\chrome-win\chrome.exe` file exist?

Did you [install the browsers](https://playwright.dev/dotnet/docs/browsers#install-browsers) before with the DT-st user?

**Comment by DipakTated** [comment]
Yes, browsers are installed and available

**Comment by mxschmitt** [comment]
Does your system maybe have a special anti virus / policies in place which prevents Playwright from starting the browser?

**Comment by DipakTated** [comment]
No nothing as such

**Comment by mxschmitt** [comment]
Could you share a minimal self-contained reproducible with us? Does this reproduce with just [a script](https://playwright.dev/dotnet/docs/library) or just our [nunit/mstest integration](https://playwright.dev/dotnet/docs/writing-tests)?

**Comment by DipakTated** [comment]
This is the code of line 

 using var playwright = await Playwright.CreateAsync().ConfigureAwait(false);

 // Open a new instance of the Google Chrome browser in headless mode
 await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions { Headless = true }).ConfigureAwait(false);
 _logger.Information("Playwright launched chromium");
 const int SM_CXSCREEN = 0;
 const int SM_CYSCREEN = 1;

 // Get the screen resolution
 int screenWidth = GetSystemMetrics(SM_CXSCREEN);
 int screenHeight = GetSystemMetrics(SM_CYSCREEN);
 // Create a new page in the browser
 var page = await browser.NewPageAsync(new BrowserNewPageOptions
 {
     ViewportSize = new ViewportSize { Width = screenWidth, Height = screenHeight },
 }).ConfigureAwait(false);

 await page.SetContentAsync(result).ConfigureAwait(false);

**Comment by mxschmitt** [comment]
Looks fine, usually this error means that an anti malware program does intercept the start of the Playwright browsers and prevents it from running. This ends up in `spawn: UNKOWN`.

See e.g. https://stackoverflow.com/a/72716568/6512681

Is your device inside a special corp-network? Are there policies applied? Can you confirm with your local IT if there are special anti-virus programs on your system - maybe they prevent it from running.

**Comment by dgozman** [comment]
Closing as per above.
