### ISSUE TITLE
[BUG] Libs not found on the host for java application

### ISSUE THREAD

**Issue by dishask99** [microsoft/playwright#28854]
Hi all, can someone please guide me how can I run install-deps command for java application... I am trying to use playwright to capture screenshots.
I have imported java dependency like below -
<img width="464" alt="image" src="https://github.com/microsoft/playwright/assets/40157092/e0102e19-acf2-4a52-b1d5-3cb884b4378b">

Things are working on my local system which is mac.
I am containerising my application, facing below issue there while taking the screenshot using java code-
<img width="476" alt="image" src="https://github.com/microsoft/playwright/assets/40157092/2944931f-30b5-479d-85d3-2f2d7339d8ba">

The base image of my docker application is java based

**Comment by dishask99** [comment]
Hi @mxschmitt , could you please guide how can I use the command -
`mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install-deps"`
in my dockerfile,

it's simple in case of node using npx command

**Comment by mxschmitt** [comment]
If you bundle your Java application with Maven, this should just work. What kind of build tooling / dependency management tooling are you using?

**Comment by dishask99** [comment]
I can execute the command `mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install-deps"`

But I am creating a multistage dockerfile, one stage is building the jar and other is for runtime and the mvn exec command run at build time only.... it is getting difficult to copy libs from one stage to other

Can you suggest someway for this?

**Comment by mxschmitt** [comment]
[Maven](https://playwright.dev/java/docs/browsers#install-system-dependencies) is unfortunately the only way as of today to install the system dependencies. So creating a multi stage Docker image without Maven means its not possible to install all the required dependencies with our recommended way.

What you could do instead, but a bit more complex:

1. `mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install-deps --dry-run" &> install_deps.sh` (note the `--dry-run`)
2. move the file to the last Docker image in your multi stage build
3. execute the file there, which will also install the browser dependencies.
