### ISSUE TITLE
[BUG] Tests with brackets in name are not run by grep

### ISSUE THREAD

**Issue by TheCPAKA** [microsoft/playwright#28869]
### System info
- Playwright Version: [v1.40.1]
- Operating System: [macOS 13.2, Jenkins]
- Browser: [not related]
- Other info:

If test name has brackets in name - grep will not work for this test. 
Grep works if escape brackets \\(name\\)
Test works correctly if run it without grep

### Source code

https://github.com/TheCPAKA/pw-grep-with-brackets

**Steps**
- [Run "npm run list"]
- [Look on test names - one of them includes scopes in name]
- [Run "npm run test"]
- [2 tests run]
- [Run "npm run test-grep"]
- [Result: No tests found]

**Expected**

Tests with scopes in name are run by grep

**Actual**
Error: No tests found
Tests with scopes in name are not run by grep

**Comment by mxschmitt** [comment]
The value which gets passed over to grep is interpreted as a regular expression as per [here](https://playwright.dev/docs/test-cli#reference).

You need to escape brackets, e.g. `npx playwright test --list --grep "Login \(link\)"`
