### ISSUE TITLE
[Feature] please make it easier to fix npx playwright install issues

### ISSUE THREAD

**Issue by vid** [microsoft/playwright#28866]
I'm on Ubuntu, and occasionally run into this. It happens infrequently enough that I have to piece it together again every time, so it's frustrating and wastes time. I am not using playwright tests. Can you provide more hints to the user?  We would feel the <3.

    "playwright": "^1.40.1"

```
$ rm -rf node_modules/ package-lock.json /home/vid/.nvm/versions/node/v18.18.0/bin/playwright /home/vid/.cache/ms-playwright/ ~/.cache/google-chrome/ ~/.cache/mozilla/

$ npm i; npx playwright install --with-deps --force 

$ npm run test

┌─────────────────────────────────────────────────────────────────────────┐
│ Looks like Playwright Test or Playwright was just installed or updated. │
│ Please run the following command to download new browsers:              │
│                                                                         │
│     npx playwright install                                              │
│                                                                         │
│ <3 Playwright Team                                                      │
└─────────────────────────────────────────────────────────────────────────┘

```

)-:

**Comment by mxschmitt** [comment]
We totally agree that this should not happen! We have not heard of a problem like this before. Do you maybe have multiple playwright versions in your project? Could you check that in your package.json?

Looks like you are deleting Playwright from your public bin directory, do you have it maybe installed globally and locally at the same time and have a version difference there? I would try to uninstall your global playwright installation then. You can do `npm ls -g` to see the global installed packages and uninstall it via `npm uninstall -g playwright`

**Comment by vid** [comment]
The project doesn't have any playwright deps, a package it does, does. There's no global playwright. 

I think I know what the problem is; The depended package uses 1.39. I guess `npx playwright install` will always install the latest (1.40). In order to prevent confusion for what I'd think is a fairly ordinary condition, it would have to look in any current package.json and either install for the found version, or give a helpful error message.

**Comment by mxschmitt** [comment]
`npx playwright install` (npx behavior) will look into your `node_modules` and use the local playwright if exists. Since you have a dependency which depends on it, it should use that specific version.

Can you share reproduction steps?

I'm curious about why you did ` rm -rf /home/vid/.nvm/versions/node/v18.18.0/bin/playwright` since this is essentially part of the global playwright which might be there.

**Comment by vid** [comment]
I did that `rm` because I was so lost I `located`ed all instances of playwright on my system and removed them. (-:
I upgraded that library, I've been trying to reproduce but can't. It seems like it wants to lurk in the dark. I can close this issue if there's no way to properly resolve it.
