### ISSUE TITLE
[FEATURE] Allow URLSearchParams and string for APIRequestContext.fetch

### ISSUE THREAD

**Issue by Xotabu4** [microsoft/playwright#28863]
For `APIRequestContext.fetch` - currently supported type for `params` is `params?: { [key: string]: string|number|boolean; };`

This blocks ability to send valid requests like 

```
curl -X 'GET' \
  'https://swagger-petstore-demo.onrender.com/api/pet/findByStatus?status=available&status=pending&status=sold' \
  -H 'accept: application/json'
```

Because it is impossible to specify `params` object as ```{ status:  'available', status:  'pending', status:  'sold', }```

Please allow to pass simple `string` and built-in object `URLSearchParams` - https://nodejs.org/api/url.html#class-urlsearchparams to be as an option for `APIRequestContext.fetch` request, which will allow to construct complex params for requests.

**Comment by VadimMentorQA** [comment]
+1

**Comment by rmarinsky** [comment]
+1

**Comment by spruban** [comment]
+1

**Comment by msalnikov** [comment]
+1

**Comment by syeikhanugrah** [comment]
Any plan to implement this soon?
