### ISSUE TITLE
[BUG] How can I open a select element and use keyboard commands to navigate through options.

### ISSUE THREAD

**Issue by sholtby-yilu** [microsoft/playwright#28860]
### System info
- Playwright Version: 1.39.0
- Operating System: macOS 14.2.1
- Browser: Chromium

### Source code
The Select HTML:
```
           <select data-testid="currency" name="currency">
              <option selected value="USD">USD</option>
              <option value="GBP">GBP</option>
              <option value="CHF">CHF</option>
              <option value="EUR">EUR</option>
            </select>
```
The Test:
```
  test('checks if currency is selected on pressing tab', async ({ page }) => {
    const element = page.getByTestId('currency');
    await element.click();
    await element.press('ArrowDown');
    await element.press('ArrowDown');
    await element.press('ArrowDown');
    await element.press('Enter');
    await expect(element).toHaveValue('EUR');
  });
```

**Steps**
- Add Select HTML to environment for testing.
- Run the test

**Expected**

Select dropdown will be opened. Down arrow key will go through 3 options. Enter will select the 4th option. Test will expect to have EUR.

**Actual**

Select dropdown isn't open. Keyboard events do not go through the options and entering doesn't select the 4th option EUR.

**Comment by mxschmitt** [comment]
A select element is a native element, hence you cannot interact with the keyboard on it. We recommend using [selectOption](https://playwright.dev/docs/api/class-locator#locator-select-option) instead for it, its an API to interact with select elements.
