### ISSUE TITLE
[BUG] page.context().waitForEvent('page') isn't working 

### ISSUE THREAD

**Issue by brism17** [microsoft/playwright#28871]
`###` System info
- Playwright Version: [v1.40.1]
- Operating System:  Windows 11
- Browser:  Chromium
- Other info:
This happens while waiting for a new page to open after hitting a focused link on the page.
Doesn't happen locally, only in our pipelines 

### Source code

        const [newPage] = await Promise.all([
            page.context().waitForEvent('page'),
           page.keyboard.press('Enter');
        ]);

**Steps**
- [Run the test]
- [...]

**Expected**
The statement will return a newPage and that the promise all statement will complete successfully. 

**Actual**

The statement hangs waiting for the event page to happen.

**Comment by mxschmitt** [comment]
Closing for now as per offline discussion.

**Comment by ValeriiaKalchuk** [comment]
still repros on the Version 1.51.0

**Comment by chbaefront** [comment]
When I press the button, it stops waiting for the page to change. How do I fix this?
