### ISSUE TITLE
Build commercial testing applications on top of playwright?

### ISSUE THREAD

**Issue by sundar-ds** [microsoft/playwright#28879]
Asking a question very similar to selenium, where there are commercial applications built on top of it? Wanted to understand what kind of license restrictions prevail to do this on top of playwright and any other relevant details.

**Comment by mxschmitt** [comment]
Playwright is a OSS project, see [here](https://github.com/microsoft/playwright/blob/main/LICENSE) for the license. This should answer the questions regarding limitations etc.
