### ISSUE TITLE
[BUG]use playwright open electron app the server report can't find module?

### ISSUE THREAD

**Issue by SnoopCorleone** [microsoft/playwright#28872]
### System info
- Playwright Version: @playwright/test": "^1.30.0
- Operating System: [windows11]
- Browser: [electron 22.3.13]
- Other info:

Why does opening the Electron app work normally, but when I try to open it using Playwright, it reports an error? The funny thing is, when I refresh the window, it runs normally.

### Source code

[Run the test]
····
  async initApp(){
     this.electronApp = await _electron.launch(
          {executablePath: "D:\\software\\EasiCapsule\\EasiCapsule\\EasiCapsule.exe"});
      // Get the first window that the app opens, wait if necessary.
      await this.electronApp.waitForEvent("window",{timeout:this.actionTimeOut});
      await this.listenWindows()
      console.log("init capsule app server")
  }
····

[server report erro code ]

```
import { getLogger } from '@src/common/utils/log';
import { LoggerSentryNameSpace } from '@src/plugins/sentry/types';
const win32Api = require(winUtil.replace('/@fs/', ''));
`````

The win32Api file is called 'winUtils.ddb632b6.node

<img width="984" alt="errorcode" src="https://github.com/microsoft/playwright/assets/57624560/c5700db1-a1a9-45a2-8c88-f25dee3cc4d4">

**Comment by mxschmitt** [comment]
Would it be possible to share a minimal self contained reproducible? Otherwise we are unfortunately not able to triage this issue further.

**Comment by SnoopCorleone** [comment]
Ok，The download URL for the app is https://capsule.seewo.com. Thank you

**Comment by SnoopCorleone** [comment]
thanks ,we try to package the demo and replace you later

**Comment by mxschmitt** [comment]
I'll close it in the meantime as part of the triage process. Feel free to re-file with a repro, thanks!
