### ISSUE TITLE
[Feature]Arch Linux need its dependencies installation

### ISSUE THREAD

**Issue by abdulbadii** [microsoft/playwright#28889]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

How to install OS dependencies on Arch as by using this cannot work

`
$ sudo npx playwright install-deps
`

Any workaround maybe...
And as I'm very noob, asking:
What are deefinitively the shortcoming or differences if OS dependencies for playwright installed or not ?
Thanks

**Comment by pavelfeldman** [comment]
Playwright does not support Arch Linux. Folding into https://github.com/microsoft/playwright/issues/26482
