### ISSUE TITLE
The mobile device setting is not taking effect.

### ISSUE THREAD

**Issue by ml4725** [microsoft/playwright#28886]
The canvas drawing board on the web page requires a mobile H5 environment to perform drawing. I have set the device to "iPhone" using Python Playwright. However, when executing mouse click and move operations, even though the webpage size is set to the mobile dimensions, the browser still recognizes them as operations in a non-mobile mode, causing the canvas drawing board to be unable to draw. In reality, the mouse click and move operations are effective, and their traces are visible. Could you please advise on how to correctly set the browser to a mobile H5 environment?

**Comment by mxschmitt** [comment]
We unfortunately need clear reproduction instructions in order to look into issues like this. Please re-file and follow the issue (bug) template, which is essential for us to triage issues efficiently.
