### ISSUE TITLE
[BUG] Components mounted in test.extend are not picked up for bundling

### ISSUE THREAD

**Issue by beorn** [microsoft/playwright#28883]
### System info
- Playwright Version:
  - "@playwright/experimental-ct-react": "^1.40.1"
  - "@playwright/test": "^1.40.1"
- Operating System: macOS 14.2.1 (only tested)
- Browser: Chromium (only tested)
- Other info: component testing

### Source code

```ts
/*
 * extend-test.tsx
 */
import { MyComponent } from "./MyComponent"
import { test as baseTest } from "@playwright/experimental-ct-react"

export const test = baseTest.extend({
  mycomp: async ({ mount }, use) => {
    const comp = await mount(<MyComponent />)
    await use(comp)
  })
})

/*
 * test-suite.spec.ts
 */
import { test } from "./extend-test"

test("breaks", async ({ mycomp }) => { /* ... */ })
```

**Steps**
- run the test

**Expected**

`MyComponent` is picked up and bundled.

**Actual**

I get `Error: Error: Unregistered component`

Is there another way I should prepare component mount fixtures?

Can I manually register components?

**Comment by mxschmitt** [comment]
This should be fixed in https://playwright.dev/docs/canary-releases and gets released with the next Playwright version.
