### ISSUE TITLE
[BUG] Meta+A doesn't select all on Windows

### ISSUE THREAD

**Issue by goodwin64** [microsoft/playwright#28887]
### System info
- Playwright Version: [v1.35.1]
- Operating System: [Windows 11]
- Browser: [All]
- Other info: tested on MacOS, it works properly

### Source code

- playground link: https://try.playwright.tech/?l=javascript&s=hfeaevx
- jsfiddle link: https://jsfiddle.net/frwLh2dn/1/

**Steps**
- enter text into field 1
- enter text into field 2
- focus on field 1
- press Meta+A (should select all text)
- press Backspace
- repeat several times

**Expected**

text is deleted, field becomes empty, only the new text remains:
![image](https://github.com/microsoft/playwright/assets/10671879/418d949e-e581-454f-a630-5ca9a71927ea)

**Actual**

only the last character is deleted, the new text is concatenated to the old one:
![image](https://github.com/microsoft/playwright/assets/10671879/97b90f90-3af0-4b22-b126-24012feb02b4)

**Comment by dgozman** [comment]
@goodwin64 Well, on Windows you select with Ctrl+A. Have you tried that?

**Comment by goodwin64** [comment]
I haven't, I just thought the `Meta` is a platform-agnostic meta-key 🤔 

So, would you recommend specifying a different key combination based on the OS? @dgozman

**Comment by dgozman** [comment]
@goodwin64 Yes, for now you have to use a different key combination based on the OS. See #12168 for a feature request to improve this.
