### ISSUE TITLE
[BUG] toEqual Gives Nonsensical Error Message

### ISSUE THREAD

**Issue by jwalkerinterpres** [microsoft/playwright#28884]
### System info
- Playwright Version: ^1.40.1
- Operating System: macOS 14.2.1
- Browser: Chromium (and presumably All)
- Other info:

### Source code

HTML:
`<div>Hi&nbsp;</div>`

Javascript:
`expect(page.locator('div').textContent).toEqual('Hi ')`

Failure Message:
Expected: "Hi "
Received: "Hi "

**Steps**
-  Run a test with the provided Javascript against a page with the provided HTML

**Expected**

The error message makes sense.

**Actual**

`"Hi "` and `"Hi "` are the same string, so they should be equal and the test should pass.  A failure message with two of the same string is nonsense.

Now look, I know there are already like fifty tickets about `nbsp;`, and if it was as simple as just doing `text.replaceAll('&nbsp'
, ' ')` you'd have fixed it already and made a million users cry out in joy.

So, to be clear, I'm not asking for you to solve this (evidently) massive problem of `&nbsp;` => ` `.  What I am asking for is for the failure message to make sense.

It should instead show:

Expected: "Hi "
Received: "Hi`&nbsp;`"

Or:

Expected: "Hi "
Received: "Hi*SOME WACKINESS WE CAN'T PARSE!*"

Or _something_ that makes sense.  `expect(anything).toEqual(anything)` should never, in any testing libarary in existence, produce the same actual and expected message.

If it's going to do so, because it's just impossible to avoid having the expected match the received, you should just throw the whole message out and instead throw one to the effect of "this function was unable to display a proper failure message (this often happens when the HTML contains entities such as `&nbsp;`)".

That would be much more helpful to a user then the current "your test failed because X didn't equal Y ... oh and BTW, X = Y".

**Comment by pavelfeldman** [comment]
While we are fixing it, note that the construct you are using is an anti-pattern. You should use the web assertions instead:

```js
await expect(page.locator('div')).toHaveText('Hi ');
```

in addition to making your test resilient to timing races, it'll normalize and trim the whitespace.

**Comment by jwalkerinterpres** [comment]
Just to explain, this code is part of a custom expectation ("this thing is number-like, if you remove commas and periods").

Or, actually, it's for two of them: one takes a raw string, and the other takes an element (which then uses the raw string one on its contents).

To make that work, the raw string one needs to operate independently of the element one, which means it can't rely on locators.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by jwalkerinterpres** [comment]
Closed as "won't fix", not completed :(
