### ISSUE TITLE
[Feature]release train order

### ISSUE THREAD

**Issue by roughsoft** [microsoft/playwright#2889]
As we know，chromium is the mainstream browser(opera +edge+chrome)!
We can release some feature(for example:video,snapshotter,drag'n drop),these feature is very ready in chromium.
It must not be ready for all browser.

**Comment by roughsoft** [comment]
Not all web app must support all browser.

**Comment by roughsoft** [comment]
Some web app can support mainstream browser.

**Comment by shirshak55** [comment]
firefox is major browser tbh.

**Comment by aslushnikov** [comment]
> It must not be ready for all browser.

@roughsoft We have a high bar to release all API's across all browsers, and so far it worked out. We like this approach because a single API is easy for our clients to consume and maintain.
