### ISSUE TITLE
[Question] In Microsoft.Playwright.Core class AssertionsBase casts in constructor ILocator  to Locator that prevents me from using my decorator that implements ILocator

### ISSUE THREAD

**Issue by katsiaryna-firsava** [microsoft/playwright#28897]
public AssertionsBase(**ILocator actual**, bool isNot)
    {
        ActualLocator = (**Locator**)actual;
        IsNot = isNot;
    }

    protected bool IsNot { get; private set; }

    internal **Locator** ActualLocator { get; private set; }

Why do you have casting to object instead of using reference link?
I have decorator for locator which implements ILocator, but because of this casting I can not use it, but I think I should if tou takes ILocator as parameter in constructor.

And in this case you class does not follow Dependency Inversion Principle from SOLID.

**Comment by mxschmitt** [comment]
Our interfaces are not intended to be implemented in user-land. We use them only for adding documentation on top of our implementation classes.

So this is outside of the scope for Playwright.
