### ISSUE TITLE
[Feature] - Key Shortcuts for Playwright UI Test Runner

### ISSUE THREAD

**Issue by Manuel-Suarez-Abascal** [microsoft/playwright#28899]
**Summary**:
Introduce keyboard shortcuts for common actions in the Playwright UI test runner to enhance developer productivity and streamline the test execution process.

**Feature Request**:
As a user of Playwright, I would like the ability to use keyboard shortcuts to perform the following actions within the UI test runner:

1. **Stop Current Test Run**: A shortcut to immediately stop the execution of the currently running test(s).
2. **Run Tests**: A shortcut to start running tests without the need to click through the UI.
3. **Refresh Tests**: A shortcut to refresh the list of tests or the test state, useful for when tests have been added or modified.

**Proposed Shortcuts**:
- Stop Current Test Run: `Ctrl/Cmd + S`
- Run Tests: `Ctrl/Cmd + R`
- Refresh Tests: `Ctrl/Cmd + U`

**Benefits**:
- **Increased Productivity**: Users can manage their test executions quicker and more efficiently.
- **Enhanced Usability**: Reduces the reliance on mouse navigation, streamlining the workflow.
- **Consistency**: Brings Playwright's UI in line with other development tools that utilize keyboard shortcuts for common actions.

**Comment by dev-jonghoonpark** [comment]
`Ctrl/Cmd + S` : currently, used for save
`Ctrl/Cmd + R` : currently, used for refresh

I think other shortcut will be needed

**Comment by dev-jonghoonpark** [comment]
Can I create a feature and PR?

**Comment by dev-jonghoonpark** [comment]
I made PR https://github.com/microsoft/playwright/pull/29868 for this feature. can you review this PR? thanks! 🙇
@pavelfeldman

**Comment by injae-kim** [comment]
Awesome feature! can't wait to use this feature :)
