### ISSUE TITLE
[BUG] Check "webServer" readiness with a HEAD request, not GET

### ISSUE THREAD

**Issue by kettanaito** [microsoft/playwright#28893]
### System info
- Playwright Version: 1.40.1
- Operating System: macOS 14.2.1 (irrelevant)
- Browser: Chromium (irrelevant)
- Other info: This is a Playwright implementation issue/suggestion

### Source code

[We will only be able to work on the issues that we can reproduce.]

First, imagine an app that fetches data server-side on the `/` route. Something as simple as:

```js
import express from 'express'

const app = express()

app.get('/', async (req, res) => {
  // This is needed for the app to serve the index route.
  const data = await fetch('https://example.com').then(res => res.text()
  res.send(data)
})

app.listen(4000)
```

```js
// playwright.config.js
import { defineConfig } from '@playwright/test'

const localUrl = 'http://localhost:4000'

export default defineConfig({
  testDir: './test',
  webServer: {
    command: 'pnpm dev',
    url: 'http://localhost:4000',
    reuseExistingServer: true,
  },
})
```

```js
// test/index.test.js
test('goes to the page', async ({ page }) => {
  await page.goto('http://localhost:4000/')
})
```

The issue is that Playwright will perform a `GET http://localhost:4000` request to verify that the app is running. Now, I have the means to affect the server-side traffic (the `GET https://example.com/` request) from the test. In fact, that's what I want to do. But that won't ever happen because in order to affect the traffic, the test must run, and the test requires the index route to be served, which requires the `example.com` request to be controlled—you see what I mean.

**Expected**

Playwright does a `HEAD http://localhost:4000` request to verify that the app spawned by `webServer.command` at `webServer.url` is running. HEAD already indicates that the resource is available. Moreover, in this scenario, Playwright would trigger the `GET /`, which triggers `GET https://example.com/`, which results in excessive and redundant network communication just to know if the app's server is up.

> There's a much [better solution](https://github.com/microsoft/playwright/issues/28893) than introducing a `HEAD` request. 

**Actual**

Playwright does a `GET http://localhost:4000` request, which I find to be incorrect.

**Comment by kettanaito** [comment]
This can be solved by adding `method: 'HEAD'` to the request that verifies the status code behind the spawned application:

https://github.com/microsoft/playwright/blob/28875fa60867a1460a046de9b6c02e110a7c1e15/packages/playwright/src/plugins/webServerPlugin.ts#L171

**Comment by christoph-fricke** [comment]
We have ran into the described problem in the past as well with a Remix application and backend services, which we mock with MSW and instantiate through test fixtures. The webServer option triggered our Remix app to make calls to the backend services without them being mocked, which caused test runs to fail.

We have avoided this problem by specifying the `port` instead of the `url` in the `webServer` options. I guess the port is checked through operating system calls instead of network calls. See: https://playwright.dev/docs/api/class-testconfig#test-config-web-server

However, while it worked for us, I am sure there are situations where checking the port is not enough and pinging the URL is required to make sure the web-server is ready.

**Comment by kettanaito** [comment]
Thank you for the suggestion, @christoph-fricke! If Playwright checks the port that way, it may as well be the solution to my particular problem. 

Overall, the issue with the initial `GET /` request having external network dependencies is precisely what I'm trying to address in MSW. But for that, the testing framework mustn't trigger those routes until MSW is ready.

**Comment by kettanaito** [comment]
## Why using `HEAD` is still a bad idea

Swapping `GET` with `HEAD` won't really solve any problems. Modern server frameworks often fallback to a `GET` request handler if an explicit `HEAD` hasn't been specified (Express and Remix, to name a few). This means that even when making a `HEAD` request, Playwright will still be triggering potential network requests in the app. That's wrong.

## What to use instead

Instead, I think Playwright should only try to establish a network connection using the `net` module in Node.js.

```js
import net from 'node:net'

const connection = net.connect(port, maybeHost, callback)
```

As soon as the connection is established, the application is running. Playwright doesn't have to make any requests to the application to confirm that. 

@ pavelfeldman, what do you think about this proposal? I can open a pull request with this if the team agrees on the direction here. I do think we need to fix Playwright triggering network requests, that's definitely not right.

**Comment by kettanaito** [comment]
I wrote a tiny package that relies on `net.connect()` to check whether the application is running at a given port/url: [`until-connected`](https://github.com/kettanaito/until-connected). If you consider this an issue, I'd propose we try that package in Playwright and see whether it satisfies the existing test cases. I suspect it will. Playwright shouldn't care what's served at the root, only that the application is running.

**Comment by pavelfeldman** [comment]
So we tried to do HEAD and got an immediate pushback, so reverted. We can't measure how much HEAD vs GET saves (in most cases HEAD will trigger the get handler on the server). But we do know that HEAD is sometimes disabled.

**Comment by kettanaito** [comment]
@pavelfeldman, have you got a chance to look at [my eventual suggestion for this](https://github.com/microsoft/playwright/issues/28893#issuecomment-1895864635)? Neither GET nor HEAD requests are actually right. This isn't a big deal but I hope you reconsider and have a socket-based confirmation here to prevent Playwright from hitting any endpoints on the app just to know if it's running.

**Comment by kettanaito** [comment]
Any chance to reconsider this, using `net.connect()` instead? That fulfills the promise Playwright needs to check if the app is running without having to make actual requests. 

@pavelfeldman, do you have any links to read about the pushback on the adoption of HEAD?
