### ISSUE TITLE
[BUG]tests are failing for firefox browser in docker container

### ISSUE THREAD

**Issue by niyazhashmi1105** [microsoft/playwright#28896]
### System info
- Playwright Version: [v1.40.1]
- Operating System: [ Ubuntu 20]
- Browser: [Firefox]
- Other info:
- Docker image: mcr.microsoft.com/playwright:v1.40.0-jammy

### Source code

[We will only be able to work on the issues that we can reproduce.]
when we try to execute tests in parallel mode using github action workflow in docker container using the 1.40.0-jammy latest version the test are failing only in firefox browser where as passed in webkit and chrome browsers.

![image](https://github.com/microsoft/playwright/assets/107019981/0754cd7e-2e6b-4a28-b19b-0fca5d59466f)

![image](https://github.com/microsoft/playwright/assets/107019981/2d71646f-46fc-47a9-a887-146bd9ff21ea)

![image](https://github.com/microsoft/playwright/assets/107019981/85b17c0c-2667-4bda-8a08-f0298b8a1369)

![image](https://github.com/microsoft/playwright/assets/107019981/987261cf-7bb5-4e46-bdb5-a50b90d2bf6c)

![image](https://github.com/microsoft/playwright/assets/107019981/61c5cc72-d590-4f15-984d-6c647648489e)

![image](https://github.com/microsoft/playwright/assets/107019981/7b7ab976-d76d-40b2-80f8-afddc902870b)

![image](https://github.com/microsoft/playwright/assets/107019981/6f134c84-f3b7-461d-9fde-adafd51d38c0)

**Steps**
npx playwright test

**Expected**

All executed tests should work in all browsers in parallel mode with out any issue.

**Actual**

tests are failing in firefox browser

**Comment by mxschmitt** [comment]
While we reiterate on this issue in our team, to find a better long term solution, a workaround for this would be to set the $HOME environment variable. Like here in [this workflow](https://playwright.dev/docs/ci-intro#via-containers).

**Comment by niyazhashmi1105** [comment]
thanks @mxschmitt ,it worked after setting $HOME variable and executed successfully in firefox browsers too

![image](https://github.com/microsoft/playwright/assets/107019981/c56f3a68-b8f5-4c62-9eeb-049fd542a78f)

![image](https://github.com/microsoft/playwright/assets/107019981/29b074a9-f466-42a9-88af-3e4729a58830)

![image](https://github.com/microsoft/playwright/assets/107019981/d9a612db-c512-4526-9e8d-62eee6bcf84d)
