### ISSUE TITLE
[Feature] page.waitForSelector("td.value:contains('111222')")  

### ISSUE THREAD

**Issue by osmenia** [microsoft/playwright#2890]
Hi Team, 

does Playwright support contains(text)?
 
Element:
<td class="value">111222</td>

Function:
await page.waitForSelector("td.value:contains('111222')")

Error: 
UnhandledPromiseRejectionWarning: Error: Evaluation failed: DOMException: Failed to execute 'querySelectorAll' on 'Document': 'td.value:contains('108779')' is not a valid selector.

any workaround? 

tnx a lot

**Comment by arjun27** [comment]
@osmenia, the built-in text selector can check for contains. Did you try something like `page.waitForSelector('text=111222')`? Learn more about selectors in the link below. 

https://playwright.dev/#version=v1.2.0&section=selector-engines

**Comment by osmenia** [comment]
Hi Arjun27,

Sorry can you pls tell me what i am doing wrong:

This is code: 

```
const Location = "123456";
await page.waitForSelector("text=`${Location}`")
```

waitForSelector does not work. 
thanks a lot

**Comment by mxschmitt** [comment]
> Hi Arjun27,
> 
> Sorry can you pls tell me what i am doing wrong:
> 
> This is code:
> 
> ```
> const Location = "123456";
> await page.waitForSelector("text=`${Location}`")
> ```
> 
> waitForSelector does not work.
> thanks a lot

Seems like you've a typo in your selector, it should be:

```js
const Location = "123456";
// for if it contains the location
await page.waitForSelector(`text=${Location}`)
// or an exact match
await page.waitForSelector(`text="${Location}"`)
```

For more information, see [here](https://playwright.dev/#version=v1.2.0&path=docs%2Fselectors.md&q=selector-engines) for the selector engines and [here](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/template_strings) for JavaScript template strings.
