### ISSUE TITLE
[Feature] Separate Network logs when working with two contexts

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#28903]
Let us know what functionality you'd like to see in Playwright and what your use case is.

Currently, if you are working with two contexts then in the trace file, there is no way to identify which network request is part of which context. Wondering if there is a way to identify that.

<img width="906" alt="Screenshot 2024-01-08 at 2 26 36 PM" src="https://github.com/microsoft/playwright/assets/22205721/ed6896df-a073-476b-ab1c-a319b0cb9fa4">

Do you think others might benefit from this as well?

**Comment by vladkrasn** [comment]
Yes, would be nice to set up an alias for custom APIRequestContext and BrowserContext.
Network tab is hard to work with when using multiple contexts.

**Comment by pbarhyl** [comment]
That will be so handy feature! Generally finding info form different context in test actions, logs or timeline is quite hard - wish to have switch/label/outline to focus traces on given context❤️

**Comment by AndriiFrolov** [comment]
yes, please implement this! it is really hard to analyse failure when you have multiple contexts
