### ISSUE TITLE
[BUG] Playwright in docker stops working after release of the new version

### ISSUE THREAD

**Issue by CyborTronik** [microsoft/playwright#28902]
### System info
- Playwright Version: [v1.39.0]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [ Chromium]
- Other info:

When the release of v1.40.0 happened the docker version of the v1.39 stopped working.
For some reason, it detects in real time that a new release happened and it tries to search the chromium binaries for v1.40 while being in a docker version of v1.39.

the version of v1.40 cannot be used in my project due to SDK 8 *while prev one is on .NET 6.

A workaround that can be used is to run `playwright install` again inside the container, which makes the whole idea of having an official container less favorable (and it is not a true immutable environment, which is sad).
This means legacy projects in a few years cannot be tested with a specific version of the docker container, and become unmaintainable.

**Comment by MindaugasMateika** [comment]
You need playwright and docker image version to be the same. It sounds like you don't lock your playwright dependency and it's upgraded automatically and thus you get the error you mentioned.

**Comment by CyborTronik** [comment]
Many thanks, for quick reaction, I mentioned specific version, which means
to be tagged image.

**Comment by mxschmitt** [comment]
Can you give us the exact Docker image version and csproj file you are using? Maybe even a small repro repository which you can share with us so we can reproduce the error locally? This would help a ton in order to triage this issue more efficiently, thanks!
