### ISSUE TITLE
[Help Needed]How I can capture a response for same api call until it has retuned a valid response?

### ISSUE THREAD

**Issue by debasisj** [microsoft/playwright#28908]
**This is not a bug/issue - but need some help** 

Here is my code snippet 

```
 await page.route('**/?operationName=xxxxx=**', async route => {
      const response = await route.fetch({)
      json = await response.json()
    //some code 
  await route.fulfill({ response, json })
    })
```

However this service can send back error as response body (but status code is OK/200)  and then app will call the same end point to get data back - app does few retries 

So how I can wait until let's say response.json() does not contains error as text?

**Comment by dgozman** [comment]
@debasisj I do not really understand the issue. If the app does some retries, what exactly do you want to achieve? Please be as detailed as you can.

**Comment by debasisj** [comment]
> @debasisj I do not really understand the issue. If the app does some retries, what exactly do you want to achieve? Please be as detailed as you can.

@dgozman  here is what goes behind app service calls (for this specific scenario)
1. app calls this end point 1st time
2. backend may return a response containing something like this `{data{error:"some error msg"}}` but with status as 200
3. app then call the end point again 
4. now with a correct response
Now with the above code snippet, we captured the first response and moved on. However I would like to skip the responses that contains `error` in response until getting a valid response.

Then use the captured valid response to do various mocking, validation etc. 

Hope this helps

**Comment by dgozman** [comment]
> Now with the above code snippet, we captured the first response and moved on. However I would like to skip the responses that contains error in response until getting a valid response.

From what I understand, the `route()` above will be called twice, since the app retries the fetch. The first time it will get the error and return that error to the page. The second time it will get the successful response and return that to the page. Why doesn't that work for you? Why would you like to wait somewhere?

**Comment by debasisj** [comment]
> > Now with the above code snippet, we captured the first response and moved on. However I would like to skip the responses that contains error in response until getting a valid response.
> 
> From what I understand, the `route()` above will be called twice, since the app retries the fetch. The first time it will get the error and return that error to the page. The second time it will get the successful response and return that to the page. Why doesn't that work for you? Why would you like to wait somewhere?

i think i am missing a imp point as route will be called each time when url pattern matches. So as such i can play around with response json and add some check for skipping the first error one 
Thanks for clarification
