### ISSUE TITLE
[BUG] Filmstrip is not scrollable so impossible to view all browser contexts when you have more than 4 in a single test

### ISSUE THREAD

**Issue by rssfrncs** [microsoft/playwright#28918]
### System info
- Playwright Version: [v1.40.1]
- Operating System: MacOS
- Browser: Chromium
- Other info:

### Source code

**Steps**
- spawn 5+ browser contexts in a single test
- view trace where you can only see ~4 contexts in the filmstrip and not able to scroll

**Expected**
- spawn 5+ browser contexts in a single test
- open trace where you can only see all contexts in the filmstrip by scrolling

**Comment by mxschmitt** [comment]
This should be fixed in the next release.


Could you try http://trace.playwright.dev/next/?

**Comment by rssfrncs** [comment]
Hi yes it is thanks

**Comment by dgozman** [comment]
Closing as per above.
