### ISSUE TITLE
Playwright dragAndDrop highlights some part of the page in WebKit browser

### ISSUE THREAD

**Issue by jayashrees310** [microsoft/playwright#28919]
I am working on an automation where I need to drag an element and drop to the destination location. But happens while dragging it highlights some part of the page and dropping to the destination location though drag and drop of corresponding element works fine but it highlights the page in WebKit browser. This affects the next operation. How to handle this

```[tasklist]
### Tasks
```

**Comment by dgozman** [comment]
We need more information to act on this issue. Could you please provide a repro that we can run locally?

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
