### ISSUE TITLE
[BUG] if I use context.newPage and loop after it, tracing don't work

### ISSUE THREAD

**Issue by sustainjane98** [microsoft/playwright#28914]
### System info
- Playwright Version: [1.40.1](https://www.npmjs.com/package/playwright/v/1.40.1)
- Operating System: macOS 13.6
- Browser: All
- Other info:

### Source code

```typescript

test("Example tracing issue", async ({context, page}) => {

  const anchors = page.locator("a").all();

  const newPage = await context.newPage();

  for(const anchor of anchors) {
     // Do something here and it will not exist in trace viewer later
   }
})

```
**Steps**
- Run the test
- Open trace viewer
- See there is a part of execution missing

**Expected**

New Pages should be logged to

**Actual**

New Pages aren't logged in trace viewer

**Comment by dgozman** [comment]
@sustainjane98 You have to await the `.all()` call. The code as written in the snippet tries to iterate over a Promise, not an array.

```ts
// Note await here.
const anchors = await page.locator("a").all();
```

**Comment by sustainjane98** [comment]
@dgozman dgozman  Yeah I forgot to add that in the example, the actual issue was that the code on new page never got executed. It is okay. It works just my code didn't.
