### ISSUE TITLE
[Question] Re-using auth cookies between projects?

### ISSUE THREAD

**Issue by msmith1114** [microsoft/playwright#28916]
So im running into an odd issue, and I think I know what's going on but want to confirm if there is a way to fix this. Essentially I have 2 projects in my config. One is for a QA version of the site im testing, one is for a Staging site. The tests that run are the same but they essentially just have different baseURL's. So my config is set up like so:

```
   {
      name: "qa-setup",
      testMatch: /.*\.setup\.ts/,
      use: {
        ...devices["Desktop Chrome"],
        baseURL:
          "https://qa-site.com",
      },
    },
    {
      name: "staging-setup",
      testMatch: /.*\.setup\.ts/,
      use: {
        ...devices["Desktop Chrome"],
        baseURL:
          "https://staging-site.com",
      },
    },
    {
      name: "QA Project",
      use: {
        ...devices["Desktop Chrome"],
        baseURL:
          "https://qa-site.com",
      },
      dependencies: ["qa-setup"],
    },
    {
      name: "Staging Project",
      use: {
        ...devices["Desktop Chrome"],
        baseURL:
          "https://staging-site.com",
      },
      dependencies: ["staging-setup"],
    },
```

Pretty simple, and the setup file is simple doing a login and saving the cookies into an `.admin.json` file.

So this works just fine when I run the project SEPARATELY. IE: If I do `npx playwright test --project="Staging Project" or --project="QA Project" it works. However if I try to run both it starts to fail and I can see whats happening: It'll go through the QA project first and do the setup and everything just fine but it'll then start doing the staging tests to but NOT re-do the setup dependency (Since it's a new site it has new cookies/login/auth that are needed) so it fails.

Is it failing to do that because the `auth.json` file already exists? How should I handle this? or do I need to the run the projects in separate commands?
Thanks!

**Comment by dgozman** [comment]
> Is it failing to do that because the auth.json file already exists?

Yeah, I guess both setup projects use the same file? You should make it a different file depending on a project. Either check the value of `baseURL` fixture, or directly `test.info().project.name`:

```ts
// auth.setup.ts

import { test as setup, expect } from '@playwright/test';

setup('authenticate', async ({ page, baseURL }) => {
  const isQA = baseURL.includes('qa-site');
  const authFile = isQA ? 'playwright/.auth/qa.json' : 'playwright/.auth/staging.json';

  await page.goto('/');
  // ...
  await page.context().storageState({ path: authFile });
});
```

Let me know whether this helps.

**Comment by msmith1114** [comment]
Can you set the authfile in the project config? IE: Like Project A: use qa-auth.json, Project B: use staging-auth.json? and then I would have a setup file for each project?

**Comment by dgozman** [comment]
@msmith1114 Yes, you can, but it is [somewhat involved](https://playwright.dev/docs/test-parameterize#parameterized-projects). Note that you probably already set `storageState` in the config for test projects, but for setup projects it's not as convenient.

Overall, going with a custom option `env: 'qa' | 'staging'` can help in multiple ways: calculate `auth.json`, make `baseURL` a fixture that depends on this `env` instead of copying it multiple times, etc.

**Comment by msmith1114** [comment]
@dgozman Why couldn't I just set in each project config something like this:

```
use: {
    storageState: 'qa-storage-state.json',
  },
```

and in the other project

```
use: {
    storageState: 'staging-storage-state.json',
  },
```

and then just make 2 separate "setup" files and set their dependencies as such. Would that not work?

Also do you mind expanding the fixture option you are talking about. Im not super familiar with making my own fixture.

**Comment by msmith1114** [comment]
I ended up trying the above and it worked just fine. I just created 2 setup files, and set the correct storageState in each project in the configuration file. When running both projects it used the correct authfile. I can see where you could run into issues if there were different types of users (or way more than 1 storageState needed) but for now this seemed to work ok.
