### ISSUE TITLE
[BUG] Fixture with a faked clock and sinon.js does not work

### ISSUE THREAD

**Issue by timbicker** [microsoft/playwright#28917]
I need a way to control time in my tests. I stumbled on this issue https://github.com/microsoft/playwright/issues/6347#issuecomment-965887758 which is the solution for the problem recommended by the playwright team.
I tried to put this solution into a fixture, and it does not work. I don't understand why. Maybe there is an obvious conceptional mistake. 
It surprises me that the approach with `test.beforeEach` works, but it doesn't work with the fixture approach.
Is this a bug or a conceptional mistake?

### System info
- Playwright Version: [v1.40.1]

### Source code

```ts
// addClock.ts
import {BrowserContext} from "@playwright/test"
import path from "path"
import fs from "fs"

export async function addClock(context: BrowserContext) {
  // todo change path as necessary
  const dir = path.join(__dirname, '../../../..', 'node_modules/sinon/pkg/sinon.js')
  if (!fs.existsSync(dir)) throw Error("sinon.js does not exist")
  await context.addInitScript({
    path: dir,
  })
  await context.addInitScript(() => {
    // @ts-ignore
    window.__clock = sinon.useFakeTimers();
  });
}
```

```ts
// clockTest.ts

import {Page, expect} from "@playwright/test"

export async function clockTest(page: Page) {
  // Implement a small time on the page
  await page.setContent(`
    <h1>UTC Time: <x-time></x-time></h1>
    <script>
      const time = document.querySelector('x-time');
      (function renderLoop() {
        const date = new Date();
        time.textContent = [date.getUTCHours(), date.getUTCMinutes(), date.getUTCSeconds()]
          .map(number => String(number).padStart(2, '0'))
          .join(':');
        setTimeout(renderLoop, 1000);
      })();
    </script>
  `);

  // Ensure controlled time
  await expect(page.locator('x-time')).toHaveText('00:00:00');
  await page.evaluate(() => window.__clock.tick(1000));
  await expect(page.locator('x-time')).toHaveText('00:00:01');
}

```

```ts
// beforeEach.spec.ts
import {test, expect} from "@playwright/test"
import {addClock} from "./addClock"
import {clockTest} from "./clockTest"

test.beforeEach(async ({ context }) => {
  addClock(context)
});

test('beforeEach', async ({ page }) => {
  clockTest(page)
});
```

```ts
// fixture.spec.ts
import { test as base } from '@playwright/test';
import {addClock} from "./addClock"
import {clockTest} from "./clockTest"

// Declare the types of your fixtures.
type MyFixtures = {
  fakeTimer: {};
};

const test = base.extend<MyFixtures>({
  fakeTimer: async ({ context}, use) => {
    await addClock(context)
    await use({});
  },
});

test('fixture', async ({ page, fakeTimer }) => {
  clockTest(page)
});
```

**Steps**
- `npm install sinon`
- run tests

**Expected**

both tests should pass

**Actual**

Only `beforeEach` passes. `sinon` does not seem to have an effect in the fixture case.

**Comment by dgozman** [comment]
@timbicker Since you specify the `page` fixture before the `fakeTimer` fixture in the test signature, the page is created before fake timers are initialized. This is a very subtle distinction from the `beforeEach` case where the order is obvious.

I see four possible solutions for you:
- Use `beforeEach` 😄 
- Make sure `fakeTimer` comes before `page` in every test.
- Override the default `context` fixture to install the fake timer. Note this will affect all tests that use the extended version of the `test` object.
- Introduce something like `pageWithFakeTimer` fixture that takes the default `page` and sets up sinon inside this single page. Use this fixture instead of `page` when fake timers are needed.

Let me know whether that helps.

**Comment by timbicker** [comment]
@dgozman thanks for your thoughtful reply!

Uh I didn't know that the order of destructuring matters. Good to know :)
I will probably go with a mix of point 2 and 4.
