### ISSUE TITLE
[BUG] Test run fails if the 'Show Browser' checkbox is not checked.

### ISSUE THREAD

**Issue by SSShooter** [microsoft/playwright#28928]
### System info
- Playwright Version: [v1.40.1]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info: Playwright Test for VSCode v1.0.20

### Source code

```ts
test('Remove Node', async ({ page }) => {
  const topic = 'child-topic'
  await page.getByText(topic).click({
    force: true,
  })
  await page.keyboard.press('Delete')
  expect(await page.getByText(topic)).toBeHidden()
})
```

**Steps**
- Run the test (Disabled Show browser)
![image](https://github.com/microsoft/playwright/assets/13051472/2df4c584-7583-473b-9848-2d8e7ce85925)

- Run the test (Enabled Show browser)
![image](https://github.com/microsoft/playwright/assets/13051472/b15968a9-848c-427c-b1e6-764beaa7f99d)

**Expected**

Pass test if the 'Show Browser' checkbox is not checked.

**Actual**

The behavior is different in those two situations.

**Comment by dgozman** [comment]
@SSShooter I guess without "Show Browser" your test runs in headless mode, and probably faster. Most likely, there is  an issue with the test. For example, the last line should be
```ts
await expect(page.getByText(topic)).toBeHidden()
```
instead of
```ts
expect(await page.getByText(topic)).toBeHidden()
```

If you could provide a repro that we can run locally, we'll be able to look into the issue. Otherwise, that's the best I can help with.

**Comment by SSShooter** [comment]
Thank you! The problem is solved with await expect(page.getByText(topic)).toBeHidden(). I suppose `expect` is a synchronous function, Sorry 😂
