### ISSUE TITLE
[Feature] Indicator to know where the clicks are happening when tracing is not ON

### ISSUE THREAD

**Issue by sundar-ds** [microsoft/playwright#28927]
I would like to have the feature on the recorded video to capture the click points to know where it is clicking on the web page. Many times, business users use these videos to review how the transaction went. Owing to the speed of execution, tracking the transactions becomes difficult. I know this is available in trace viewer. But would like to have this available as a general feature in the recorded video.

**Comment by dgozman** [comment]
Folding into #1374.
