### ISSUE TITLE
PW test runner issue

### ISSUE THREAD

**Issue by MPRaiden** [microsoft/playwright#28925]
### System info
- Playwright Version: [v1.40.1]
- Operating System: [Mac OS]
- Browser: [All]
- Playwright test runner issue

**Steps to reproduce**
1. Delete a file or any other export that you use somewhere else in your test suite (or you can add an import that does not exist)
2. Using the Visual studio code test runner extension run any test

**Expected**
Test fails because we are requiring a module that does not exist, e.g. we get an error like below
`Error: Cannot find module '../data/gtmt-toh-impression-constants'`

**Actual**
Test executes as if there is no issue. What's interesting is that if you run a test through the terminal then you get the expected error.

**Comment by dgozman** [comment]
We need more information to act on this issue. Could you please provide a repro that we can run locally?

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
