### ISSUE TITLE
[BUG] Run test arrows in vscode editor misaligned with tests on NodeJS 21

### ISSUE THREAD

**Issue by extremegf** [microsoft/playwright#28933]
**Context:**
- Playwright Version: 1.40.1
- Operating System: Linux Ubuntu 20.04
- Node.js version: 21.4.0
- Visual Studio Code version: 1.85.1
- Playwright for VSCode extension version: 1.0.20
- Browser: All

**Describe the bug**
The run arrows are not alligned with tests. This is from the repro:

![image](https://github.com/microsoft/playwright/assets/1788593/f5f9d587-df32-4626-b365-44dce2b39532)

It gets worse on bigger tests:

![image](https://github.com/microsoft/playwright/assets/1788593/bff33bc1-e28c-4df8-ad11-348019f43350)

Moreover run-under-cursor shortcuts also seem affected.

I've verified that this is not caused by other vscode extensions, by using extension bisect.

I've prepared a miniml repro. Really minimal - I can't make this go away no matter what I do.

https://github.com/extremegf/playwright-repro-20240110

**Comment by dgozman** [comment]
Looks good on my computer with VSCode 1.85.1, extension v1.0.20. Something's wrong with your environment, but I'm not really sure what to recommend.

<img width="476" alt="Screenshot 2024-01-10 at 11 26 08 AM" src="https://github.com/microsoft/playwright/assets/9881434/0141bc90-994f-42a4-b2f1-b8eed3331e4b">

**Comment by extremegf** [comment]
I can also upload the vm somewhere if that's helpful.

**Comment by dgozman** [comment]
@extremegf Thank you for persisting 😄  I did not notice that you use Node 21, I am able to repro now. This seems to have the same underlying issue as #28732, which should be fixed by #28526 in the next release. For now, I recommend to downgrade to Node 20. Let me know whether that helps.

**Comment by extremegf** [comment]
I can confirm that downgrading to node 20 fixes the issue. Thank you for the assistance. Hope this gets fixed soon. 👍

**Comment by dgozman** [comment]
Great, folding into #28732.
