### ISSUE TITLE
[BUG] Playwright Junit xml report not created when using config env toggle in CI

### ISSUE THREAD

**Issue by JenH11** [microsoft/playwright#28930]
### System info
- Playwright Version: v1.40
- Operating System: Windows 11
- Browser: Chromium
- Other info:

When running Playwright tests in the release pipeline I'm expecting a junit xml file to be created so that it can be published but it is not. Instead the html report is created which is what is configured for local. The statement isn't being respected. Using the same report type (with property) outside of the ternary statement works fine but we want to guard against us humans setting the wrong reporter type in CI so we'd rather have it working in the ternary. I've followed the guide here for 'Reporters on CI' https://playwright.dev/docs/test-reporters & although I'm doing it slightly different it looks as though it should work fine.

I can easily recreate with the repo & pipeline I have so hopefully this is sufficient but please let me know if you need any more information.

```
  reporter: [
    process.env.CI
    ? ["junit", { outputFile: "test-results.xml" }]
    : ["html", { outputFolder: "html-report", open: "never" }]
  ],
```

**Steps**
- Set Playwright.config file to have the above ternary statement
- Run a test in devops using a release pipeline
- Check what reports are created on the build machine

To see it working simply change playwright.config to have the following instead:

```
reporter: [[ "junit", { outputFile: "test-results.xml" }]],
```

**Expected**
When running in CI using an azure devops release pipeline a junit xml report is created

**Actual**
An html report - the behaviour expected when running locally - is created instead of the junit xml file and the xml file cannot be found to be published in devops

**Comment by dgozman** [comment]
@JenH11 Perhaps your CI pipeline does not set the `CI` environment variable? I'd recommend double-checking the CI docs to see what environment variables are set.

**Comment by JenH11** [comment]
Hi there!

Sorry, I should have mentioned that I've already tried that.. Though I'm not 100% if I'm doing it correctly.

Here is our run cmd. I've tried specifying CI as true both before & after "npx playwright test". Like this:

```
"NPMScriptName": "set CI=true&&<other_env_vars>npx playwright test --grep <ourTestTags>",
```

```
"NPMScriptName": "<other_env_vars>npx playwright test set CI=true --grep <ourTestTags>",
```

Am I on the right lines or does this need to be done another way?

When you say double-check the CI docs, do you mean playwright CI docs or Azure DevOps docs? Happy to check either just want to be sure

**Comment by JenH11** [comment]
All sorted - it was the env var & when I set it in devops itself it worked fine. Thanks for your help!
