### ISSUE TITLE
[Feature] Hide sensitive data in traces

### ISSUE THREAD

**Issue by frankaigner** [microsoft/playwright#28934]
Currently, sensitive data is displayed in traces, be it screenshots, passwords, etc. In order to protect the data and not make it visible to everyone who has access to the results of the Playwright test, it could be protected with a password. In the playwright config you could define that traces are created and provided with a password. The password is then requested when opening with the trace viewer and the trace is readable. This could also be used as a transition solution for https://github.com/microsoft/playwright/issues/19992

**Comment by dgozman** [comment]
@frankaigner I don't think Playwright is the best place to implement password protection. I'd recommend setting up security features at the place where you host the report and other test artifacts, with proper access control and all other necessities. This falls out of scope for Playwright project.
