### ISSUE TITLE
Filtering on multiple criteria has inconsistent results

### ISSUE THREAD

**Issue by jcrans13** [microsoft/playwright#28931]
### System info
- Playwright Version: 1.40.1
- Operating System: Windows 10
- Browser: Chromium

### Source code

[We will only be able to work on the issues that we can reproduce.]

[Please provide a self-contained example in a form of a snippet, archive or a repository.]

[Repro scenario can't be large or have external dependencies.]

Site HTML:
![image](https://github.com/microsoft/playwright/assets/107000743/0e49c63b-3516-42d6-927b-d6c3b1ef6043)

PlayWright code:
`await page.locator('a').filter({ hasText: `${firstLast}`, has: page.locator('//img[@src="assets/images/16x16/yellow.png"]') }).locator('a').click({ button: 'right' });`

**Steps**
- [Run the test]
- [...]

**Expected**

Filtering on multiple criteria should either work 100% of the time or 0% of the time. I am seeing that it is working inconsistently.

**Actual**

Output from report:

```
Error: locator.click: Error: strict mode violation: locator('a').filter({ has: locator('//img[@src="assets/images/16x16/yellow.png"]') }).locator('a') resolved to 23 elements:
    1) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Cory Mccullough $69.' }).locator('a')
    2) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'James CondonNew$234.00Metlife' }).locator('a')
    3) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Marian Harrison $0 UPDATE INS' }).locator('a')
    4) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Jennifer Leonard$6,392.007140' }).locator('a')
    5) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Raaj Bora$210.00Appt confirmed' }).locator('a')
    6) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Ronnie Carver$' }).locator('a')
    7) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Angela CameronNew$234.00UHC' }).locator('a')
    8) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Raaj Bora$144.00ORHYG ADLPX' }).locator('a')
    9) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Antonio Patrick$283.16ORHYG' }).locator('a')
    10) <a title="" data-html="true" data-toggle="tooltip" …>…</a> aka locator('a').filter({ hasText: 'Josulin MeadowsNew$240.' }).locator('a')
    ...

Call log:
  - waiting for locator('a').filter({ has: locator('//img[@src="assets/images/16x16/yellow.png"]') }).locator('a')


  66 |         } while (await page.locator('a').filter({ hasText: `${firstLast}`, has: page.locator('//img[@src="assets/images/16x16/yellow.png"]') }).locator('a').isVisible() === true);
  67 |       };
> 68 |       await page.locator('a').filter({ hasText: `${firstLast}`, has: page.locator('//img[@src="assets/images/16x16/yellow.png"]') }).locator('a').click({ button: 'right' });
     |                                                                                                                                                   ^
  69 |       await page.locator('//li[@data-ik="1"]', { hasText: 'Check-In' }).first().hover();
  70 |       await page.locator('//li[@data-ik="1_0"]', { hasText: 'Arrived' }).first().click();
  71 |       await patientPage.spinner();

    at C:\Users\A092037\PlayWright\New folder\aspendental-epms-smoke\src\tests\smoke\clinical\locking.test.ts:68:147
    at C:\Users\A092037\PlayWright\New folder\aspendental-epms-smoke\src\tests\smoke\clinical\locking.test.ts:60:5

```

**Comment by dgozman** [comment]
@jcrans13 From the error message, my guess would be that `firstLast` is an empty string, and so many items match your locator. That said, we can only work on the issues that we can reproduce, so you would need to include a self-contained repro that we can run locally.

**Comment by jcrans13** [comment]
I don't know if I would be able to provide repo files since this is a private site with customer info. I don't think there is an issue with the empty string, but of course I can't prove that right now since our QA site is down. Would Playwright behave that way by ignoring that piece of the code if the string was empty? `waiting for locator('a').filter({ has: locator('//img[@src="assets/images/16x16/yellow.png"]') }).locator('a')`. Can we keep this open for a day or 2 until I can verify the empty string theory?
