### ISSUE TITLE
[Feature] Allow to extend built-in reporters implementation

### ISSUE THREAD

**Issue by AdamOakman** [microsoft/playwright#28945]
Currently there is a way to create a custom reporter which is ok if you want to a create new reporter from scratch. I like the way list reporter prints information and would like to keep it but I would like to be able to print some additional debug information under the stack trace for each failed test case that is printed in the end of test execution.

If I go with custom reporter onTestEnd or onExit method and print some information in there it intersects with built-in list reporter in unreadable way. Or if I am missing something - is there any way to modify the way how list reporter prints information?

**Comment by dgozman** [comment]
@AdamOakman There is no way to modify built-in reporters. However, we are open source, so you can always look at what [list reporter](https://github.com/microsoft/playwright/blob/main/packages/playwright/src/reporters/list.ts) is doing and do something similar in your own reporter.
