### ISSUE TITLE
[Feature] Add a unique per-run ID and make it accessible inside test fixtures

### ISSUE THREAD

**Issue by MrJohz** [microsoft/playwright#28941]
## Background

I have a series of tests that each use a unique starting state.  Currently, for each test, I generate these states by creating a new folder that looks roughly like this: (`/TESTS/${RUN_ID}/title/of/test/as/a/path/${browserName}` -- i.e. a new blank state is created for each browser, for each test, and for each overall run.  This is set up in a fixture using the `.extend` mechanism.

The title of the test and the browser name are fairly easy to set up.  However, I don't think there is any run ID exposed to the tests.  This is also discussed in #15073, where the suggested answer is to generate a run ID in the `globalSetup` file, and store it in an environment variable that can be accessed inside each test.  Up until now, this is what I've been doing -- I generate a timestamp and store it in `process.env`.

~~However, this no longer works when using the `dependencies` system for global setup recommended [here](https://playwright.dev/docs/test-global-setup-teardown#option-1-project-dependencies).  (I'm using these project dependencies because the other method doesn't seem to work with ESM/Typescript.)  The problem, as far as I can tell, is that because the setup file runs in a different child process to the tests, the environment variables aren't shared between the different tests.~~

EDIT: it turns out that that wasn't true, I just wasn't running the global setup function correctly.  The environment variables are shared correctly.  However, I still think this would be a useful feature.

## Feature

It would be useful if `TestInfo` included a field like `runStartTime` or `runId` (or both), that I could use to identify different runs with.

* `runStartTime` may be slightly simpler, and has the advantage that it is sortable (in the sense that I can then navigate my `TESTS` folder and see which tests I ran last).  However, it also isn't technically an ID, as two runs could conceivably start at the same time.
* `runId` would be more explicitly a unique ID for each run, but I'd imagine this would be generated as a UUID or similar, in which case it would be more difficult to sort runs in terms of age.  (For me, this is a very useful property of my current system.)

Possibly, it makes sense to add both for their different use cases.

**Comment by dgozman** [comment]
@MrJohz Thank you for the issue! This does not seem to be a common-enough request to justify an API for it. You can always generate a unique id to your liking at the start of the run. Doing it in the setup is perfectly fine. You can also do it in the config if you'd like:

```ts
// playwright.config.ts
import { defineConfig } from '@playwright/test';

process.env.RUN_ID = process.env.RUN_ID || (new Date().toISOString());

export default defineConfig({ ... });
```

Let me know whether it works for you.

**Comment by dgozman** [comment]
Closing as per above. If you still encounter problems, please file a new issue with a repro and link to this one.
