### ISSUE TITLE
innerText method returns text that is not even visible on UI

### ISSUE THREAD

**Issue by v84a** [microsoft/playwright#28955]
### System info
- Playwright Version: [v1.21.0]
- Operating System: [All]
- Browser: [Chromium]
- Other info:

### Source code

Please look at steps below. Source code is currently not possible to share as it is a non-public application. However if explanation is not clear enough, I will attempt to provide more information.

**Steps**
- Review following html
```
<td __playwright_target__="after@call@390" style="">
  <span>N/A</span>
  <span class="sr-only">Not Applicable</span>
</td>
```
- When we issue innerText on `<td>` element, it returns `N/A Not Applicable`. However, on UI, only `N/A` is visible and `Not Applicable` is hidden meant only for screen readers.
- `sr-only` is a very common class used only for screen-readers and usually not visible on UI. If there is any alternate way of extracting only visible text from HTML page, please help with it.

**Expected**
`N/A` should be returned

**Actual**
`N/A Not Applicable` is being returned

**Comment by dgozman** [comment]
@v84a Playwright follows the web spec and uses the [`innerText` property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText) of the element. I don't think the spec is going to change, and so Playwright will not be changing the behavior either.

**Comment by v84a** [comment]
@dgozman I understand. Is there any alternate way community is aware of?
