### ISSUE TITLE
[BUG] Element Inside 0 Opacity Element Counts as Visible

### ISSUE THREAD

**Issue by jwalkerinterpres** [microsoft/playwright#28954]
### System info
- Playwright Version: ^1.40.1
- Operating System: macOS 14.2.1
- Browser: Chromium (and presumably All)
- Other info:

### Source code

**HTML:**

`<div style="opacity: 0; transform: translateY(1.93193px) translateZ(0px);"><section class="_container_1j3il_1 EditIntegration-module-formField _vertical_1j3il_46"><label class="_label_1j3il_8">Integration name *</label><div class="_container_1o1oi_1 _fullWidth_1o1oi_36 _medium_1o1oi_18"><input __playwright_target__="call@63" type="text" name="name" class="_input_1o1oi_39" value="Test Notional Integration - DELETE ME!"></div></section></div>`

**Simplified (Relevant Parts Only) HTML:**

`<div style="opacity: 0; transform: translateY(1.93193px) translateZ(0px);"><input name="name" ></div>`

**Test Code:**

`expect(locator('[name="name"]')).toBeVisible();`

![Screenshot 2024-01-11 at 9 29 19 AM](https://github.com/microsoft/playwright/assets/152227747/13e25e60-e2b5-4e6d-b446-b87c7dfaf97f)

**Steps**
- [Run the test]

**Expected**

Expect the toBeVisible assertion to fail because the element is inside an `opacity: 0` element

**Actual**

Playwright happily passes the line and continues the test

**NOTE:** I'm honestly not sure what I need to provide to provide a full repro here.  Providing one feels like an impossible requirement: you can't possibly expect everyone to provide their entire applications (plus relevant test files) ... right?  Fundamentally I would think all you need is the test code, and HTML to be tested ... just in a desired format?

Do you have a sandbox, clone-able Git repo, or any other sort of template that users can copy (and paste in HTML/JS like the above) to create a reproducible case in the format you desire?

**Comment by jwalkerinterpres** [comment]
I did a little further testing, and something doesn't add up.  Per the MDN:

>When opacity value is set to 0 , the element and all of its children are not visible

>opacity applies to the element as a whole, including its contents, even though the value is not inherited by child elements. Thus, the element and its children all have the same opacity relative to the element's background, even if they have different opacities relative to one another.

However, the calculated opacity of the input _is_ `1`, not `0`:

    window.getComputedStyle(playwright.$('[name="name"]:visible')).getPropertyValue("opacity"); // '1'

Even though the parent's calculated opacity _is_ 0, as expected:

     window.getComputedStyle(playwright.$('[style="opacity: 0; transform: translateY(1.93193px) translateZ(0px);"]:visible')).getPropertyValue("opacity"); // '0'

So, if Playwright is using `window.getComputedStyle` for its `:visible` check it makes sense why it would see this element as "visible". I would have thought the browser calculations would include parent opacity, but perhaps Playwright's visibility checker needs to check ancestor visibility (separately)?

**Comment by dgozman** [comment]
Playwright does not check opacity of the element when determining visibility. From [the documentation](https://playwright.dev/docs/actionability#visible):

> Element is considered visible when it has non-empty bounding box and does not have `visibility:hidden` computed style. Note that elements of zero size or with `display:none` are not considered visible.

Note that the `opacity: 0` element is still visible to assistive technology tools like a screen reader. I would recommend to hide the element in some other way, e.g. `display: none`, or add `aria-hidden=true` attribute to it.

**Comment by jwalkerinterpres** [comment]
Ah, that helps a lot.  Might I suggest adding a sentence to that documentation (eg. in bold below) ... if only to save you from errant bug reports in the future:

> Element is considered visible when it has non-empty bounding box and does not have visibility:hidden computed style. Note that elements of zero size or with display:none are not considered visible.  **Also note that the CSS `opacity` style has no impact on visibility (even `opacity: 0` elements are still visible to assistive technologies, eg. screen readers, so they are still visible to some users).**

**Comment by jwalkerinterpres** [comment]
![https://miro.medium.com/v2/resize:fit:1400/0*C-cPP9D2MIyeexAT.gif](https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_300,h_172/https://intelligent-information.blog/wp-content/uploads/2017/12/celebration.gif)
