### ISSUE TITLE
[Question] Capturing a screenshot in between a long press delay

### ISSUE THREAD

**Issue by nickofthyme** [microsoft/playwright#28956]
I stumbled upon #12841 in the past attempting to take a screenshot during a long press. Then using `@playwright/test@1.23.0`, the code below worked. The idea being, the [`page.mouse.click`](https://playwright.dev/docs/api/class-mouse#mouse-click) function waits to resolve until the delay is complete but I need to skip this wait to capture the screenshot.

```ts
if (options?.delay) {
  // need to skip await to resolve early and capture delay
  void page.mouse.click(x, y, options);
} else {
  await page.mouse.click(x, y, options);
}
```

But since updating to `@playwright/test@1.40.1` I get this error...

```
Error: mouse.click: Test ended.
    at ../page_objects/common.ts:304
  302 |       if (options?.delay) {
  303 |         // need to skip await to resolve early and capture delay
> 304 |         void page.mouse.click(x, y, options);
      |                         ^
  305 |       } else {
  306 |         await page.mouse.click(x, y, options);
  307 |       }
```

I managed to archive the same affect with the code below...

```ts
if (options?.delay) {
  await page.mouse.move(x, y);
  await page.mouse.down();
} else {
  await page.mouse.click(x, y, options);
}
```

But I wondered if there is a better way to do this.

**Comment by dgozman** [comment]
@nickofthyme You should always await async Playwright methods instead of prefixing them with `void`. This way you can be sure the test will not end prematurely. The `move` + `down` method is a great way to hold down the mouse. Don't forget to call `mouse.up()` at some point though 😄

**Comment by nickofthyme** [comment]
Thanks @dgozman, I agree with that, and yes I need to add the `mouse.up`.
