### ISSUE TITLE
[Feature] Parallel Execution at spec/test files

### ISSUE THREAD

**Issue by kjadhav-wk** [microsoft/playwright#28964]
It would be good if we have parallel execution at spec/test file level. Currently, in parallel mode tests are running in multiple worker node for the same test file. So, we are facing some challenges while running same test file tests in different worker node because common data shared within test.

We should have some other mode which we have in TestNG for classes, tests, methods, instance

**Comment by JonahKK** [comment]
Set `fullyParallel` to false in your config. That will result in Playwright running tests parallel on file level.

**Comment by dgozman** [comment]
Also, take a look at the [parallelism guide](https://playwright.dev/docs/test-parallel) for more options.

**Comment by kjadhav-wk** [comment]
Thank You, It is working.
