### ISSUE TITLE
[Feature] Create flag to make screenshot of only the visible part of the locator

### ISSUE THREAD

**Issue by nikolay-yavorovskiy** [microsoft/playwright#28963]
It's possible right now to pass the locator into `await expect().toHaveScreenshot()`, however, if the locator's height or width is bigger than its visible part, then something like that will happen:<details>
  <summary>example</summary>
<img src="https://github.com/microsoft/playwright/assets/89914399/24a55f16-27b8-4b9c-bbc7-8470868bf262">
</details>

playwright will make a screenshot of the whole locator, including its hidden part.
It would be helpful to have a flag, something like `trimVisiblePart: true`, that will automatically trim only a visible part of the screenshot. Right now something similar is possible via the `clip` flag, you can calculate the visible part of the locator yourself and pass it to `clip`, but it isn't very convenient, to say the least.

**Comment by dgozman** [comment]
@nikolay-yavorovskiy I'd recommend to take a screenshot of the scrollable container that clips the element. Usually, you would want to see the whole element, but it looks like in your case something clips the element in some unusual way. Let me know whether screenshotting a different element works for you.

**Comment by nikolay-yavorovskiy** [comment]
> @nikolay-yavorovskiy I'd recommend to take a screenshot of the scrollable container that clips the element. Usually, you would want to see the whole element, but it looks like in your case something clips the element in some unusual way. Let me know whether screenshotting a different element works for you.

I don't think that there is anything unusual, to be honest
it is a card with a long table
the grey part at the bottom is the bottom of the screen, the table goes beyond that
![image](https://github.com/microsoft/playwright/assets/89914399/e50ca1df-aef0-40cd-a99f-4834af90e3ea)

**Comment by dgozman** [comment]
@nikolay-yavorovskiy Is there a way you could share a repro with us? We would like to understand the issue you would like to solve by proposing a new feature. Otherwise, it's very unlikely that the feature will be implemented, when we don't understand the usecase for it.

**Comment by dgozman** [comment]
@nikolay-yavorovskiy Here is a workaround:

```ts
const box = await page.locator('#element-to-screenshot').boundingBox();
await expect(page).toHaveScreenshot({ clip: box });
```

Let me know whether that helps.
