### ISSUE TITLE
[Documentation] Clarification on Navigations page

### ISSUE THREAD

**Issue by Tigatok** [microsoft/playwright#28977]
The "[Navigations](https://playwright.dev/docs/navigations#hydration)" page has some details around "When is the page loaded", and "Hydration". I noticed that it says if using page.goto it will wait for the page to load and then continue:

>For the scenario above, Playwright will wait for the text to become visible, will wait for the rest of the actionability checks to pass for that element, and will click it.
>Playwright operates as a very fast user - the moment it sees the button, it clicks it. In the general case, you don't need to worry about whether all the resources loaded, etc.

Is it worth adding in this section, or in the Hydration section below that you can also use page.waitForURL? Or, if using a framework like React/MUI, how would you implement this correctly?

>The right fix for this issue is to make sure that all the interactive controls are disabled until after the hydration, when the page is fully functional.

TIA

**Comment by mxschmitt** [comment]
Our docs try to be framework agnostic. Under the ["waiting for a navigation" ](https://playwright.dev/docs/navigations#waiting-for-navigation)section we are already giving them an example for `waitForURL` - is this what would you recommend adding?

Hydration usually does not get solved with waitForURL from my experience, since you are already on the right URL, but the element is still badly hydrated - thats what this page is about.

**Comment by Tigatok** [comment]
I will admit I didn't see that section, likely because I read the "if navigating to more than one page" and then stopped processing. In my case, it _did_ solve my problem with respects to the hydration, but I am also not entirely sure I have the best rendering/hydration strategy...

In my case, I had a button (coming from MUI if that matters) that has a submit:

```
              <Button variant="outlined" type={'submit'}>
                {loading && <CircularProgress size={24} />}
                {!loading && 'Apply!'}
              </Button>
```

and my playwright test here is doing the click. In the Playwright UI, it passes, but in the command line (because it goes very fast), the test failed.
```
  await page.getByRole('button', { name: 'Apply!' }).click()
```

**Comment by mxschmitt** [comment]
For buttons ideally they are all disabled while they hydrate and show a loading spinner as well.

**Comment by Tigatok** [comment]
Could you elaborate on how you would mark them disabled until hydration is completed? I'm assuming it depends on the framework that is being used? And then I'd have to add some sort of event listener to then flip the state? Is that the general idea?

Appreciate the help

**Comment by mxschmitt** [comment]
>  I'm assuming it depends on the framework that is being used?

Exactly, this is the general idea on how hydration should work. So the fast user like e.g. Playwright can't click on a button which is not ready yet. It should visually not be clickable and accessibility wise not be clickable.

**Comment by mxschmitt** [comment]
Closing as per above for now since this is not a concrete bug / feature report.
