### ISSUE TITLE
[Feature]When listing all test cases, mark whether the use case is skip or not

### ISSUE THREAD

**Issue by jiawen94** [microsoft/playwright#28979]
Hi, playwright developers.
When I use command line `npx playwright test ***  --project ***   --list` or vscode TEST EXPOLOER to list all cases, It shows all cases, whether skipped or not
Is it better to show all cases, **mark the case skip or not? Group it by skip or not.**

my  code snippet:
```
test(`my test `, async ({ context }) => {
    test.skip(skipTest, 'skip the test case when skipTest is true');
      ...
```

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/28709.
