### ISSUE TITLE
Playwright WebServer can deliver json payloads?

### ISSUE THREAD

**Issue by filepi** [microsoft/playwright#28972]
Hey Folks,

I'm creating UI tests and I don't want to call any external API.
I notice playwright comes with a webserver which I think it could be a solution for that, but I didn't find any documentation about it.
Is that possible using playwright webserver to create some endpoints and specify the payload that should be delivered when requests hit those endpoints?

**Comment by dgozman** [comment]
@filepi Take a look at [this guide](https://playwright.dev/docs/mock).

**Comment by mxschmitt** [comment]
See also here for mocking the network: https://playwright.dev/docs/network#network-mocking

**Comment by mxschmitt** [comment]
Closing as per above.
