### ISSUE TITLE
[Feature]Collect the logs from the servers under test

### ISSUE THREAD

**Issue by jiawen94** [microsoft/playwright#28980]
When the test is running, playwright only receives the logs of its own.Is it possible to collect the logs from the servers？
I know a lot of servers have rsyslog services that can transfer local logs over udp to other servers.
If Playwright has a function to receive the logs and show it (as text attachments) on the html report,It will be  helpful to analyze the failed cases.

**Comment by cenfun** [comment]
```
webServer: {
        stdout: 'pipe',
        stderr: 'pipe'
}
```
see https://playwright.dev/docs/api/class-testconfig#test-config-web-server

**Comment by mxschmitt** [comment]
If you set them to `pipe` as per above, webServer logs will end up in the reporter API as [`onStdOut`](https://playwright.dev/docs/api/class-reporter#reporter-on-std-out) and [`onStdErr`](https://playwright.dev/docs/api/class-reporter#reporter-on-std-err) - would that work for you? There you can e.g. stream or send them anywhere based on your needs.

**Comment by mxschmitt** [comment]
Closing as per above.
