### ISSUE TITLE
[BUG]The mobile mode setting in Playwright is not taking effect.

### ISSUE THREAD

**Issue by ml4725** [microsoft/playwright#28989]
### System info
- Playwright Version: [v1.40]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:
After switching from Selenium to Playwright, I encountered a scenario where Playwright couldn't handle it. The product includes a canvas drawing board that can only be used for drawing on mobile devices. In Playwright, I switched the browser to mobile mode, but it only changed the page size. However, when I inspected window.navigator, I noticed that userAgentData.mobile remained false. This prevented me from performing operations on the canvas drawing board. In contrast, when I used Selenium and set mobileEmulation, window.navigator.userAgentData.mobile was true, allowing me to interact with the canvas drawing board as expected. I would like to know if this limitation is specific to Playwright's lack of support for this mobile device scenario or if there are other settings that need to be configured.
### Source code
    with sync_playwright() as playwright:
        iphone = playwright.devices["iPhone 12 Pro"]
        browser = playwright.chromium.launch(headless=False)
        context = browser.new_context(**iphone)
        page=context.new_page()
        page.goto("https://twitter.com/playwrightweb")

**Steps**
- [Running the test]
- [Browser appears for one second]
- [Open the developer mode by pressing F12 and check the navigator.userAgentData.mobile property in the console.]

**Expected**
When setting the device to mobile mode, not only the browser window size changes, but also the desired outcome is for the actual userAgentData.mobile property to be changed to true.

**Actual**
Even though you have set the device in Playwright, it seems that only the browser window size is changing to match the mobile mode, while the browser's mobile property (userAgentData.mobile) remains false.

![image](https://github.com/microsoft/playwright/assets/155813188/e0982371-7240-4d2e-9202-6060c2e4398f)

**Comment by mxschmitt** [comment]
Investigation: As of today we don't emulate [`window.navigator.userAgentData.mobile`](https://caniuse.com/mdn-api_navigator_useragentdata). CDP seems to expose it via [`Emulation.UserAgentMetadata`](https://vanilla.aslushnikov.com/?Emulation.UserAgentMetadata) on `Emulation.setUserAgentOverride`.

**Comment by rio-ap** [comment]
hi team, it seem this issue still happen on latest playwright version (v1.41.xx). when we use mobile emulation on chromium based. sometimes page will still show the desktop view (this behaviour is not happen on webkit based)

**Comment by mxschmitt** [comment]
Hi, the change is not released yet. You can try Canary in the meantime: https://playwright.dev/docs/canary-releases

We recommend filing a new issue @rio-ap with more details.

**Comment by ml4725** [comment]
Could you please find out when is this fix expected to be officially released?

**Comment by ml4725** [comment]
Could you please find out when is this fix expected to be officially released?

**Comment by mxschmitt** [comment]
We unfortunately can't give any eats on specific release dates. I recommend subscribing to our releases: 
<img width="668" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/3d100df7-8959-4e25-8ee7-6fdfacb01350">

**Comment by rio-ap** [comment]
hi @mxschmitt is this fix already included in v 1.42.0 that released 2 days ago?

**Comment by mxschmitt** [comment]
Yes. If it doesn't work, feel free to re-file.

**Comment by rio-ap** [comment]
hi @mxschmitt it still happen ya, still failed on chromium on latest release version

**Comment by mxschmitt** [comment]
Which Playwright version are you using? I tried the following and it works for me:

<img width="894" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/83ce63fa-4beb-45c6-839c-552c6825009c">

```py
from playwright.sync_api import sync_playwright

with sync_playwright() as playwright:
    iphone = playwright.devices["iPhone 12 Pro"]
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context(**iphone)
    page=context.new_page()
    page.goto("https://twitter.com/playwrightweb")
    page.pause()

```

**Comment by rio-ap** [comment]
v1.42.1 and canary i believe 1.42.30 alpha not sure as i revert again to latest when failed try. change by config file 
```
{
      name: 'Mobile',
      use: {
        ...devices['Pixel 5']
      },
    },
```

and the test itself run on headless mode. is it only work on headed mode or is there any specific chrome setting to be parsed ya for headless run to make mobile emulation work in chrome?

**Comment by mxschmitt** [comment]
Could you file a new issue? It worked for me with v1.42

**Comment by ml4725** [comment]
Hello,
In the latest version of Playwright (1.42), when the browser is set to mobile mode and the navigator.userAgentData.mobile is enabled, I am experiencing an issue while simulating signature functionality on a canvas element. When I press the left mouse button and move the mouse, no strokes are being generated on the canvas. This canvas functionality works correctly when the browser is in mobile mode using Selenium's ActionChains to simulate mouse movements.

I can provide you with an access URL to the page in question. If you are able to open and access it, could you please check if this issue is a bug in Playwright or if there is an error in my code? If the token for the URL has expired and you are unable to access it, I can provide a new URL. It's important to detect strokes on this canvas page before proceeding to the next step, which involves submitting the signature. I have been struggling with this issue for a while, and I would greatly appreciate your guidance. Thank you.

The code is as follows:
from playwright.sync_api import sync_playwright

with sync_playwright() as playwright:
    iphone = playwright.devices["iPhone 12 Pro"]
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context(**iphone)
    context.grant_permissions(['camera', 'microphone'])
    page = context.new_page()
    page.goto(
        "https://yc-h5-test15.hrfax.cn/ccip/sign/#/?query=eyJ3YXRlck5vIjoiMTc2NTQxMDQ0NDM5Njk5NDU2MCIsInNpZ25Ub2tlbiI6ImJlYXJlciBleUpoYkdjaU9pSlNVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKd2FHOXVaU0k2Ym5Wc2JDd2lkWE5sY2w5dVlXMWxJam9pTVRnek1EQXdNREF3TURFaUxDSnlaWE5sZEZCaGMzTlhiM0prSWpwbVlXeHpaU3dpYzJOdmNHVWlPbHNpWVd4c0lsMHNJbk5wYm1kc1pVeHZaMmx1SWpwdWRXeHNMQ0psZUhBaU9qRTNNVEF3TWpreE1UTXNJblI1Y0dVaU9uc2lkbUZzZFdVaU9pSnViMjVsWDNWelpYSWlMQ0owWlhoMElqb2k2WjJlNTdPNzU3dWY1NVNvNW9pM0lpd2ljbTlzWlZSNWNHVWlPaUlpTENKaWRYTnBibVZ6YzFSNWNHVWlPaUlpZlN3aWRYTmxja2xrSWpveE9ETXdNREF3TURBd01Td2lhblJwSWpvaWRDMTFUM1pyT0RablVGZEliWG96TFZSWlZsOHlVemxqUWt4Vklpd2lkWE5sY2tOdlpHVWlPbTUxYkd3c0ltTnNhV1Z1ZEY5cFpDSTZJbU5qYVhBdFpuSnZiblJsYm1RaUxDSjFjMlZ5Ym1GdFpTSTZJakU0TXpBd01EQXdNREF4SW4wLldnTlFKeVJ1dWRBeXRyOUtFSnBxeEJfelpiay1nRVlnTFgyXzU1ZFQxWldCSmw5V3d6RjFyYXNVQnFxcjU3ZmRKUmpneHdWQTZRcEhqTjNoXzlJczBUdUQydU5fMlhHMDA1a3VQblQySDI0WXdSWHhtcm1CczktUmd0dnZ2cHdaQWthcXN1MXljWVo3Ri16djNIUVRUcU1majIzLWxXU3BGZEJWR05iSGZFTEx4VkhEVlFoR0ZsZFpEczlqdGhKVEszNElKSURvblFYUWNWbmFqMkxXLXR1OGRFTEt1TmxnRk9JOVlGR2tORWFjOFZ4aHliU0Z2UXBrYkwxTHBKX3VyREVMR2ttcXNjUmhFblN0YlZFWGxncFdYaEJVSDhBenpfejRyUlZvTlppTFF4aDh4NmdLYklPRGlTRkRIeHRrNjRQNXpXU3d2QzloMmROX0l1SmVrdyIsImJhY2tVcmwiOiJodHRwczovL3ljLWg1LXRlc3QxNS5ocmZheC5jbi9jY2lwLyMvcGFnZXMvaW5kZXgvaW5kZXg%2FdXVpZD0wZjI0NjQ4ZS01MTkyLTQ3YTEtODAzZi02NWE5ODEwZjIxMDQiLCJzdWNjZXNzVXJsIjoiaHR0cHM6Ly95Yy1oNS10ZXN0MTUuaHJmYXguY24vY2NpcC8jL3BhZ2VzL3NlbGZBcHBseS9yZXN1bHQvaW5kZXg%2FcmVzdWx0PXRydWUmc291cmNlPXNpZ25hdHVyZSIsImZhaWxlZFVybCI6Imh0dHBzOi8veWMtaDUtdGVzdDE1LmhyZmF4LmNuL2NjaXAvIy9wYWdlcy9teU9yZGVyUGFnZS9pbmRleD9mbGFnPWhpc3RvcnlPcmRlciZmcm9tPXNpZ24ifQ%3D%3D")
    page.wait_for_load_state("load")
    page.locator("//uni-view[@class='btns-box']").click()
    page.wait_for_timeout(3000)
    page.locator("//uni-button").click()
    canvas = page.locator("#canvas")
    canvas_box = canvas.bounding_box()
    center_x = canvas_box['x'] + canvas_box['width'] / 2
    center_y = canvas_box['y'] + canvas_box['height'] / 2
    page.mouse.move(center_x, center_y)
    page.mouse.down(button="left")
    page.mouse.move(center_x, center_y + 100)
    page.mouse.up()
    page.wait_for_timeout(100000)

**Comment by Detrous** [comment]
@mxschmitt could you please try with headless=True ?
I can reproduce this issue in headless mode with this website: https://hillary.ua/maska-dlya-volos/naturalnaya-maska-dlya-vosstanovleniya-volos-hillary-bamboo-hair-mask/
With headless=False everything works like a charm

**Comment by mxschmitt** [comment]
We added a test for it here which passes for headless, see line 140: https://github.com/microsoft/playwright/blob/bc83d7084c17a0b787c30b3c874e7a35a5576042/tests/library/browsercontext-user-agent.spec.ts#L129-L143

So maybe its a different issue? Please file a new issue with exact reproduction steps. Thanks!
