### ISSUE TITLE
[BUG]: Tests failing in normal mode but passing in ui mode

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [microsoft/playwright#28990]
### System info
- Playwright Version: "@playwright/test": "^1.40.1",
- Operating System: Windows 11
- Browser: Windows 11, Ubuntu latest
- Other info: Does not work local and in GH Actions with the latest Ubuntu version

### Source code

https://github.com/The-Creative-Programming-Group/Weather-App

If you run the tests in the normal mode you get these errors for MS Edge, Firefox, Chromium and Mobile Chrome:  

```
                                     6) [Microsoft Edge] › email.test.ts:28:1 › contact form ──────────────────────────────────────────
@weatherio/e2e-web-tests:dev:test: 
@weatherio/e2e-web-tests:dev:test:     Error: elementHandle.isVisible: Test ended.
@weatherio/e2e-web-tests:dev:test:     Call log:
@weatherio/e2e-web-tests:dev:test:       -   checking visibility of locator(':scope')
@weatherio/e2e-web-tests:dev:test:
@weatherio/e2e-web-tests:dev:test:
@weatherio/e2e-web-tests:dev:test:       33 |   // Check the toast
@weatherio/e2e-web-tests:dev:test:       34 |   expect(
@weatherio/e2e-web-tests:dev:test:     > 35 |     (await page.waitForSelector('li[data-type="success"]')).isVisible(),
@weatherio/e2e-web-tests:dev:test:          |                                                             ^
@weatherio/e2e-web-tests:dev:test:       36 |   ).toBeTruthy();
@weatherio/e2e-web-tests:dev:test:       37 | });
@weatherio/e2e-web-tests:dev:test:       38 |
@weatherio/e2e-web-tests:dev:test:
@weatherio/e2e-web-tests:dev:test:         at F:\programming-projects\Weather-App\packages\e2e-web-tests\tests\email.test.ts:35:61
@weatherio/e2e-web-tests:dev:test:
```

But if you select every browser in the UI mode and run the test all are passing

**Steps**
- Setup the project (ig only pnpm I)
- Run pnpm dev
- Run turbo dev:test/turbo dev:test:ui

**Expected**

All tests are passing

**Actual**

I get the error from above

**Comment by FleetAdmiralJakob** [comment]
GH Action: https://github.com/The-Creative-Programming-Group/Weather-App/actions/runs/7531888515/job/20501425505

**Comment by viraxslot** [comment]
@FleetAdmiralJakob Hi, I'd suggest to use this API method https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-be-visible

I guess ui mode just has a small delay that's because your check passes. The problem could be that `isVisible` method doesn't wait the state. Please try to change your statement like this:
```javascript
await expect(page.locator('li[data-type="success"]')).toBeVisible();
```
Will it work?
You can also specify a custom timeout for this method if element takes more time to appear than usual.
