### ISSUE TITLE
[BUG] node:events:492 throw er; Error: write EPIPE

### ISSUE THREAD

**Issue by ruiguoamz** [microsoft/playwright#28999]
### System info
- Playwright Version: v1.40.0
- Operating System: Linux
- Browser: Chromium
- Other info:
Code is running in AKS (Azure Kubernetes Service)

### Source code
Sorry, actually not sure if this is a bug or a question.
But our test cases can run into this very same issue from time to time.
Please check below screenshot.

<img width="916" alt="image" src="https://github.com/microsoft/playwright/assets/48600426/1cc08682-545d-47bf-8021-94cc50da9e3c">

**Steps**
- [Run the test]
- [...]

**Expected**

Program runs normally

**Actual**

Uncatchable error force exit the running program

**Comment by mxschmitt** [comment]
This looks unexpected but we need a reproduction in order to look into issues like this. Please re-file with a repro, thanks!
