### ISSUE TITLE
[BUG] Close the background browser when closing the UI interface

### ISSUE THREAD

**Issue by jindameias** [microsoft/playwright#28996]
### System info
- Playwright Version: [v1.40.0]
- Operating System: [Windows 10]
- Browser: [Chromium]
- Other info:

```python
def main():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        context = browser.new_context()

        page = context.new_page()
        page.goto("https://example.com")

        browser.on('disconnected', lambda: print('browser disconnected'))

        try:
            while True:
                # do some others
                pass
        except KeyboardInterrupt:
            pass
        finally:
            context.close()
            browser.close()

if __name__ == "__main__":
    main()
```

**Expected**

In some cases, operators may accidentally click on the 'x' button of the UI interface. I want to capture the event when they close the UI interface, but 'disconnected' doesn't seem to work. What method should I use to achieve this?

**Actual**

The UI interface has been closed, but the browser without the UI interface still runs in the background. I want to close the background browser simultaneously with the UI interface.

**Comment by mxschmitt** [comment]
The reason for that is that inside the `while True` loop with the pass the main thread stays busy, this does not allow Playwright to emit the close events. If you rewrite it using `page.wait_for_time(1000)` instead, it will work. Note:`time.sleep(1)` is also not an options, see [here](https://playwright.dev/python/docs/library#timesleep-leads-to-outdated-state).

Alternatively, you can use the async version and use `asyncio.sleep`.

Would that work for you?

**Comment by jindameias** [comment]
> The reason for that is that inside the `while True` loop with the pass the main thread stays busy, this does not allow Playwright to emit the close events. If you rewrite it using `page.wait_for_time(1000)` instead, it will work. Note:`time.sleep(1)` is also not an options, see [here](https://playwright.dev/python/docs/library#timesleep-leads-to-outdated-state).
> 
> Alternatively, you can use the async version and use `asyncio.sleep`.
> 
> This will then emit:
> 
> ```
> page.on("close", lambda: print("closing the page"))
> ```
> 
> Would that work for you?

No, it is not work. There is no output in the console.

**Comment by mxschmitt** [comment]
This works for me:

```python
from playwright.sync_api import sync_playwright

def main():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        context = browser.new_context()

        page = context.new_page()
        page.goto("https://example.com")

        page.on('close', lambda: print('page close'))

        try:
            while True:
                # do some others
                page.wait_for_timeout(1000)
        except KeyboardInterrupt:
            pass
        finally:
            context.close()
            browser.close()

if __name__ == "__main__":
    main()
```

**Comment by jindameias** [comment]
> This works for me:
> 
> ```python
> from playwright.sync_api import sync_playwright
> 
> def main():
>     with sync_playwright() as p:
>         browser = p.chromium.launch(headless=False)
>         context = browser.new_context()
> 
>         page = context.new_page()
>         page.goto("https://example.com")
> 
>         page.on('close', lambda: print('page close'))
> 
>         try:
>             while True:
>                 # do some others
>                 page.wait_for_timeout(100)
>         except KeyboardInterrupt:
>             pass
>         finally:
>             context.close()
>             browser.close()
> 
> if __name__ == "__main__":
>     main()
> ```

Oh, thank you. This works, I misunderstood the meaning.
