### ISSUE TITLE
Cant apply WebKit diff ontop of current base revision

### ISSUE THREAD

**Issue by MoeBazziGIT** [microsoft/playwright#28998]
In my WebKit repo, my base revision is `3facd67e2518ff15efe1b6cda0810e4c76e9c482`, the same as the [latest Playwright release](https://github.com/microsoft/playwright/blob/v1.40.1/browser_patches/webkit/UPSTREAM_CONFIG.sh). 

I am doing `git apply path/to/bootstrap.diff` but I am getting this error, for many files:
`
error: patch failed: Source/JavaScriptCore/inspector/agents/InspectorRuntimeAgent.cpp:191
error: Source/JavaScriptCore/inspector/agents/InspectorRuntimeAgent.cpp: patch does not apply
`

I even tried `git apply --index --whitespace=nowarn ~/Working/PW-WebKit-diff/bootstrap.diff`, which I saw from the docs at  https://github.com/microsoft/playwright/tree/v1.6.2/browser_patches.

**Comment by mxschmitt** [comment]
Works for me!

```
git clone https://github.com/WebKit/WebKit
cd WebKit
# pick from here: https://github.com/microsoft/playwright/blob/main/browser_patches/webkit/UPSTREAM_CONFIG.sh
git checkout -b bootstrap bc0bc692bc9e368bbd9d530322db73b374cd6268
curl -O https://raw.githubusercontent.com/microsoft/playwright/main/browser_patches/webkit/patches/bootstrap.diff
git apply --whitespace=nowarn bootstrap.diff
echo $0
```

**Comment by MoeBazziGIT** [comment]
okay, ill try this one out, thanks a ton!
it seems i was using the wrong base revision, from the 1.40.1 tagged release
