### ISSUE TITLE
[Question]Second Websocket connection in a page

### ISSUE THREAD

**Issue by krishnak** [microsoft/playwright#28997]
This is more of an implmentation question. I have a page which connects to a websocket server on page load.

I am able to handle the websocket connection on the website with Playwright in JAVA using the following pseudo code
```
public static void main()
{
//some code
            page.onWebSocket(ws->{
                test(ws);
            });    

//some code
}
public void test(WebSocket ws)
    {
        System.out.println("Websocket Opened "+ws.url());
        ws.onFrameSent(ws1160454->{frameSent(ws1160454);});
        ws.onFrameReceived(ws1160455->{processData(ws1160455);});
    }
    
```

However on the same page, when a button is clicked a new second websocket connection to a different URL is triggered. I am able to click the button and the browser is showing the data from the second websocket, however the new websocket connection is not triggering the test method again. I even duplicated the handler method.

```
public static void main()
{
        //some code
            page.onWebSocket(ws->{
                test(ws);
            });    

// some code
page.onWebSocket(ws2->{
                test2(ws2);
            });    
}
public void test2(WebSocket ws2)
    {
        System.out.println("Websocket Opened "+ws2.url());
        ws.onFrameSent(ws1160464->{frameSent(ws1160464);});
        ws.onFrameReceived(ws1160465->{processData(ws1160465);});
    }

```
What am I missing?

**Comment by mxschmitt** [comment]
`onWebSocket` should emit all the WebSocket connections on the page which are emitted after the website created them.

Would it be possible to share a repro?

**Comment by krishnak** [comment]
onWebSocket method is capturing the first websocket connection that was opened by the website which hits a url ws1.xyz.com. The first websocket is NEVER closed. After the page loads a button press sends a HTTPS upgrade request to the server to upgrade the HTTP request into websocket, this is sent to ws2.xyz.com I am attaching the second websocket request captured via Wireshark. The first websocket upgrade request is exactly similar to this one except the host field.
![Screenshot from 2024-01-14 20-08-31](https://github.com/microsoft/playwright/assets/1259447/98f812b6-aee4-4bf8-ba6e-58305594e31a)

**Comment by krishnak** [comment]
Unfortunately the webserver in question is not accessible without a login and it is a third party server. Hence it will be impossible to run the code from your setup.

But when a new HTTP request is sent for upgrade to ws1.xyz.com, is it possible that it is still using the same websocket connection previously established?

The hosts ws.xyz.com and ws1.xyz.com both resolve to the same IP addresses as they both sit behind cloudflare.

**Comment by mxschmitt** [comment]
> is it possible that it is still using the same websocket connection previously established?

if its a new http request which is a upgrade request, it will end up in a new WebSocket connection, so this sounds unlikely to me.

Cloudflare should also not play a role here.

I'll close it for now since we don't have a repro. Feel free to re-file if you have something you can share with us, since we otherwise can't act on it. Thanks for your understanding!
