### ISSUE TITLE
Playwright is taking more time to terminate the execution even after test completed

### ISSUE THREAD

**Issue by ddeogharkar** [microsoft/playwright#29002]
### System info
- Playwright Version: [v1.40]
- Operating System: [Windows 10]
- Browser: [Chrome]
- Other info: Language JAVA 
- JDK version 17

### Source code

```
package com.mc.theHubPlaywright;

import com.microsoft.playwright.*;
import com.microsoft.playwright.options.AriaRole;

import java.util.regex.Pattern;

public class TestClass {

    public static void main(String[] args) {
        try (Playwright playwright = Playwright.create()) {
            Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions()
                    .setHeadless(false)
                    .setChannel("chrome")
            );

            Page page = browser.newPage(new Browser.NewPageOptions().setViewportSize(1920,1200)
            );
            page.setDefaultTimeout(60000);
            page.navigate("https://www.google.com/flights?hl=en#flt=");
	    page.close();            
            browser.close();

        }


    }
}
```

**Steps**
Executed from Intellij IDE
**Expected**

Test status should get completed as soon as the test passes or fails.

**Actual**

Test termination take longer time to get completed after test case passes.

**Comment by mxschmitt** [comment]
We are unfortunately familiar with the Intellij IDE nor we have access to it. Would it be possible to share reproduction steps without it?

**Comment by ddeogharkar** [comment]
Steps would be 
1. Create a JAVA project 
2. Create a class naming <TestClass>
3. Add below code to it
`public static void main(String[] args) {
        try (Playwright playwright = Playwright.create()) {
            Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions()
                    .setHeadless(false)
                    .setChannel("chrome")
            );

            Page page = browser.newPage(new Browser.NewPageOptions().setViewportSize(1920,1200)
            );
            page.setDefaultTimeout(60000);
            page.navigate("https://www.google.com/flights?hl=en#flt=");
	    page.close();            
            browser.close();

        }


    }`

4. Execute the test case
5. Verify the termination of the test case

Expected : Test case should complete once it is Passed / Failed 

Actual : Test case taking time to terminate after Passed / Failed

**Comment by mxschmitt** [comment]
Does this also reproduce with normal Chromium (no channel specified)?

Most likely this is caused by Enterprise policies which are applied on your machine, you can see them when you navigate to `chrome://policy/` - are there some?

**Comment by ddeogharkar** [comment]
Hi @mxschmitt, Might be policies are causing this, do you know any specific policy which may cause this issue or do I need to check logs to get the policy? I will try to run this in my local system to verify this issue?

**Comment by mxschmitt** [comment]
Are there policies listed when navigating to `chrome://policy` with your normal Google Chrome browser? Which ones are listed? 

A bunch of policies could be the cause for this - there is unfortunately no way of ignoring these policies, nor finding out which one is causing it (except speculation) and testing on an environment without Enterprise policies applied.

**Comment by ddeogharkar** [comment]
There are multiple policies listed, I share these policies with you due to security reasons, I will try this on my local system and let you know the behaviour.
