### ISSUE TITLE
Masked controls input data is not captured in playwright while creating a new record.

### ISSUE THREAD

**Issue by dthota-infor** [microsoft/playwright#29000]
### System info
- Playwright Version: [v1.40]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info : 
   When recording the masked controls for numeric fields, input data is not captured. It is creating a click method instead of a fill method, as shown below :
   
 Generated code : await page.getByTestId('amount-input').click();

Expected code : await page.getByTestId('amount-input').fill('4300');

**Comment by mxschmitt** [comment]
We need a clear reproduction in order to look into issues like this. Please re-file providing us exact steps to reproduce your reported issues. Thanks for your understanding!
