### ISSUE TITLE
[BUG] Locator.Click is not working as expected, even though Playwright reports success

### ISSUE THREAD

**Issue by snair7274** [microsoft/playwright#29008]
### System info
- Playwright Version: [v1.40.1]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

### Source code
 await page.locator('button:has-text("Change User")').click();

**Issue Description:**

I am facing an issue with clicking a button after filling details in a form. The button is located inside a form, but all other elements are added in a navigation-list. The button is in the footer <div>. After filling mandatory details, the button appears to be enabled, and in the trace log, the click action is reported as completed. However, the expected functionality is not working.

**Expected**
Should Click on the element and the form changes update successfully. 
**Actual**
Click not worked, but in report and trace log it is showing as clicked.
Playwright trace log: 
_**locator:
locator('button:has-text("Change User")')
strict:
true
LOG
waiting for locator('button:has-text("Change User")')
locator resolved to <button type="submit" .....…</button>
attempting click action
waiting for element to be visible, enabled and stable
element is visible, enabled and stable
scrolling into view if needed
done scrolling
performing click action
click action done
waiting for scheduled navigations to finish
navigations have finished**_

**Additional Info:**

The button is located inside a form.
All other elements are added in a navigation-list.
The button is in the footer <div>.
The button appears enabled after filling mandatory details.
The navigation-list is inside a scrollable section( footer not included here)

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
