### ISSUE TITLE
How to build and run the Playwright webkit embedder project in Xcode

### ISSUE THREAD

**Issue by MoeBazziGIT** [microsoft/playwright#29005]
Hello, I am trying to run the `Playwright.xcodeproj` located in `browser_patches/webkit/embedder/Playwright/Playwright.xcodeproj`, but I am getting the 2 following errors in xcode:

<img width="267" alt="Screenshot 2024-01-16 at 13 02 23" src="https://github.com/microsoft/playwright/assets/39361312/eec9c102-892d-4b08-bc1e-1d7674df47ca">

The first one is regarding the embedded WebKit framework. I have built the Playwright WebKit binaries succusfully using the WebKit base revision and applying the bootsrap.diff, but I am not sure how to embed them in this project. 

For the second error I have no idea where that file is :thinking:

**Comment by mxschmitt** [comment]
This is outside of the scope for Playwright, as per [here](https://github.com/microsoft/playwright/issues/28976#issuecomment-1894077608).

**Comment by MoeBazziGIT** [comment]
I understand. What if one would like to make contributions to Playwright/WebKit?

**Comment by mxschmitt** [comment]
You should copy the embedder folder into `webkit/Tools/Playwright` and everything should work. The embedder is not intended to be opened inside the browser_patches directory.

In general we don't accept contributions to our WebKit patches diff. All contributions should go directly to https://github.com/webkit/webkit.
