### ISSUE TITLE
[BUG] Compatibility Issues with Patch Application on Firefox Build

### ISSUE THREAD

**Issue by yb-cs** [microsoft/playwright#29018]
### System info
- Playwright Version: v1.41
- Operating System: Linux Ubuntu 22.03 LTS
- Browser: Firefox
- Other info: Issues with applying patch

### Source code

Unfortunately, a self-contained example is not applicable in this scenario as the issue arises during the build process of the Firefox browser itself.

**Steps**
- Clone the `gecko-dev` repository.
  ```
  git clone https://github.com/mozilla/gecko-dev
  cd gecko-dev
  ```
- Checkout the `release` branch and then the specific commit:
  ```
  git checkout release
  git checkout 7ab3cc0103090dd7bfa02e072a529b9fc784ab4e
  ```
- Create a new branch from this commit:
  ```
  git checkout -b bootstrap 7ab3cc0103090dd7bfa02e072a529b9fc784ab4e
  ```
- Download the `bootstrap.diff` patch from the Playwright repository.
  ```
  curl -O https://raw.githubusercontent.com/microsoft/playwright/main/browser_patches/firefox/patches/bootstrap.diff
  ```
- Apply the patch using `git apply --whitespace=nowarn`:
  ```
  git apply --whitespace=nowarn bootstrap.diff
  ```

**Expected**

The patch should apply cleanly to the specified version of the Firefox source code without any errors.

**Actual**

Encountered multiple errors indicating that the patch does not apply to several files, leading to a failure in the build process. Example errors include:

error: patch failed: accessible/base/NotificationController.h:244
error: accessible/base/NotificationController.h: patch does not apply
...
(more error messages)

@mxschmitt

**Comment by mxschmitt** [comment]
```
git clone https://github.com/mozilla/gecko-dev
cd gecko-dev
# pick from here: https://github.com/microsoft/playwright/blob/main/browser_patches/firefox/UPSTREAM_CONFIG.sh
git checkout -b bootstrap 7ab3cc0103090dd7bfa02e072a529b9fc784ab4e
curl -O https://raw.githubusercontent.com/microsoft/playwright/main/browser_patches/firefox/patches/bootstrap.diff
git apply --whitespace=nowarn bootstrap.diff
echo $0
```

Works for me!

**Comment by yb-cs** [comment]
Oh now it works, that's weird. I did the same thing before :( Thanks a lot <3. Also, what are all these files in the directory for the patch does not seem like they were used:

* `juggler`
* `patches`
* `preferences`

Could you please clarify their purposes? Thank you!

**Comment by yb-cs** [comment]
> Oh now it works, that's weird. I did the same thing before :( Thanks a lot <3. Also, what are all these files in the directory for the patch does not seem like they were used:
> 
> * `juggler`
> * `patches`
> * `preferences`
> 
> Could you please clarify their purposes? Thank you!

Do I need to save them in the gecko-dev directory as well before building or what exactly should be done?

**Comment by yb-cs** [comment]
> ```
> git clone https://github.com/mozilla/gecko-dev
> cd gecko-dev
> # pick from here: https://github.com/microsoft/playwright/blob/main/browser_patches/firefox/UPSTREAM_CONFIG.sh
> git checkout -b bootstrap 7ab3cc0103090dd7bfa02e072a529b9fc784ab4e
> curl -O https://raw.githubusercontent.com/microsoft/playwright/main/browser_patches/firefox/patches/bootstrap.diff
> git apply --whitespace=nowarn bootstrap.diff
> echo $0
> ```
> 
> Works for me!

incase someone faces this issue in the future make sure you stash the git changes using `git stash` before applying the patch 🤓

**Comment by yb-cs** [comment]
# 🚀 Building Firefox Playwright Version from Scratch 🚀

Let's consolidate all the learning on how to build the Firefox Playwright version from scratch.

## Step 1: Setting up the Environment 🛠️

First of all, get started with the base of building. Learn how to get the tools and environment needed to make the build from the [Firefox Source Docs](https://firefox-source-docs.mozilla.org/setup/index.html).

## Step 2: Cloning the Repository 📂

Once you're done with that, clone the `gecko-dev` repository into a new folder. Here is the flow:

```bash
git clone https://github.com/mozilla/gecko-dev
cd gecko-dev
git checkout -b bootstrap 7ab3cc0103090dd7bfa02e072a529b9fc784ab4e
curl -O https://raw.githubusercontent.com/microsoft/playwright/main/browser_patches/firefox/patches/bootstrap.diff
git apply --whitespace=nowarn bootstrap.diff
echo $0
```

> ⚠️ Please note that `7ab3cc0103090dd7bfa02e072a529b9fc784ab4e` is the current build that is used. Since the release of this comment, you have to retrieve the latest version of the build from the [Playwright's UPSTREAM_CONFIG.sh](https://github.com/microsoft/playwright/blob/main/browser_patches/firefox/UPSTREAM_CONFIG.sh). This is what you will find inside of that file:

```bash
REMOTE_URL="https://github.com/mozilla/gecko-dev"
BASE_BRANCH="release"
BASE_REVISION="7ab3cc0103090dd7bfa02e072a529b9fc784ab4e"
```

## Step 3: Applying the Patch 🩹

After you apply the patch, you have to download all the corresponding tools that come with the patch and place them in the directory. Get all files from the [Playwright's Firefox patches](https://github.com/microsoft/playwright/tree/main/browser_patches/firefox) and place them inside the `gecko-dev` folder.

## Step 4: Building the Project 🏗️

Now just go ahead and do `./mach build`.

## Closing Thoughts 🎉

That's it! You've successfully built the Firefox Playwright version from scratch. Give yourself a pat on the back and go celebrate! 🎉🎉🎉

**Comment by yb-cs** [comment]
> # 🚀 Building Firefox Playwright Version from Scratch 🚀
> Let's consolidate all the learning on how to build the Firefox Playwright version from scratch.
> 
> ## Step 1: Setting up the Environment 🛠️
> First of all, get started with the base of building. Learn how to get the tools and environment needed to make the build from the [Firefox Source Docs](https://firefox-source-docs.mozilla.org/setup/index.html).
> 
> ## Step 2: Cloning the Repository 📂
> Once you're done with that, clone the `gecko-dev` repository into a new folder. Here is the flow:
> 
> ```shell
> git clone https://github.com/mozilla/gecko-dev
> cd gecko-dev
> git checkout -b bootstrap 7ab3cc0103090dd7bfa02e072a529b9fc784ab4e
> curl -O https://raw.githubusercontent.com/microsoft/playwright/main/browser_patches/firefox/patches/bootstrap.diff
> git apply --whitespace=nowarn bootstrap.diff
> echo $0
> ```
> 
> > ⚠️ Please note that `7ab3cc0103090dd7bfa02e072a529b9fc784ab4e` is the current build that is used. Since the release of this comment, you have to retrieve the latest version of the build from the [Playwright's UPSTREAM_CONFIG.sh](https://github.com/microsoft/playwright/blob/main/browser_patches/firefox/UPSTREAM_CONFIG.sh). This is what you will find inside of that file:
> 
> ```shell
> REMOTE_URL="https://github.com/mozilla/gecko-dev"
> BASE_BRANCH="release"
> BASE_REVISION="7ab3cc0103090dd7bfa02e072a529b9fc784ab4e"
> ```
> 
> ## Step 3: Applying the Patch 🩹
> After you apply the patch, you have to download all the corresponding tools that come with the patch and place them in the directory. Get all files from the [Playwright's Firefox patches](https://github.com/microsoft/playwright/tree/main/browser_patches/firefox) and place them inside the `gecko-dev` folder.
> 
> ## Step 4: Building the Project 🏗️
> Now just go ahead and do `./mach build`.
> 
> ## Closing Thoughts 🎉
> That's it! You've successfully built the Firefox Playwright version from scratch. Give yourself a pat on the back and go celebrate! 🎉🎉🎉

Last step is that you actually need to place the preferences in their right place!

Place the ```00-playwright-prefs.js``` in the folder ```gecko-dev/browser/defaults/preferences/``` and the ```playwright.cfg``` in ```gecko-dev```
