### ISSUE TITLE
Not able to download Playwright Binaries for mac after updating to version 1.40.1

### ISSUE THREAD

**Issue by umangm99** [microsoft/playwright#29017]
Hi Team,

I'm not able to download playwright binaries for chrome, webkit or firefox after updating my playwright version from 1.26.1 to 1.40.1 from net.azureedge.playwright.

Please tell us from where we can download binaries of browsers to use playwright

**Comment by mxschmitt** [comment]
Please re-file with exact steps on how to reproduce your issue, expected and actual by following the bug template. Thanks for your understanding.
