### ISSUE TITLE
[BUG] React component tests not passing Date prop values

### ISSUE THREAD

**Issue by leiit** [microsoft/playwright#29027]
### System info
- Playwright Version: `v1.41.0`, `1.42.0-alpha-jan-17-2024`
- Operating System: All
- Browser: All
- Other info: Works with v1.40.1 and below

### Source code

```tsx
const TestComponent = ({ date }: { date: Date }) => {
  console.log('date', date);

  return <span>{date.toLocaleDateString()}</span>;
};

export default TestComponent;

```

```tsx
import { expect, test } from '@playwright/experimental-ct-react';
import TestComponent from './TestComponent';

test('can pass a Date object to the component', async ({ mount, page }) => {
  await mount(<TestComponent date={new Date('2000-06-01')} />);
  await expect(page.getByText('2000')).toBeInViewport();
});

```

**Steps**
- Run the test

**Expected**

Component renders, `Date` objects were passed from the runner to the browser environment prior to v1.41.0.

<img width="593" alt="Screenshot 2024-01-17 at 21 16 10" src="https://github.com/microsoft/playwright/assets/3333374/a8a07957-5e5a-4c53-ba18-43d847832604">

**Actual**

Empty object is passed from the runner.

<img width="555" alt="Screenshot 2024-01-17 at 20 59 53" src="https://github.com/microsoft/playwright/assets/3333374/3e69bd7c-a806-49e3-a641-ec8e35d8d3c1">

**Comment by mxschmitt** [comment]
I can repro on ToT. Thanks for filing and providing the great test-case!
