### ISSUE TITLE
[BUG] Drag and drop from cross domain iframe to parent works manually but not programatically

### ISSUE THREAD

**Issue by aalexgabi** [microsoft/playwright#29022]
### System info
- Playwright Version: v1.40.1
- Operating System: Windows 11
- Browser: Chromium

### Source code

Here's a simplified code snippet that demonstrates the problem. The code simulates a drag-and-drop operation from an iframe to a parent frame:
```
  await page.pause();
  await page.mouse.move(200, 200); // From inside iframe
  await page.mouse.down();
  await page.mouse.move(400, 400); // To somewhere in the parent frame
  await page.mouse.up();
```

**Steps**
Drag and drop something from an iframe on one domain 
Drag and drop works during the page.pause() if done manually.
But when done programatically it does not work.

**Expected**

Drag and drop to work normally when global mouse coordinate based low level actions are used. Basically it works if done manually so the expectation here is that using page.mouse.*() helpers it should work the same way. If I drag and drop from the iframe to the iframe itself it seems to work normally as well. The issue seems to happen when leaving the iframe although not 💯sure.

**Actual**

The drag operation starts normally, even highlighting the drop zones, but the iframe appears to freeze as soon as the mouse leaves its area with the dragged item. This results in the highlighted drop zones remaining in the 'active' state.

**Comment by mxschmitt** [comment]
Would it be possible to share a reproduction with us?
