### ISSUE TITLE
[BUG] process.env.USERNAME cannot be set in .env file

### ISSUE THREAD

**Issue by katejou** [microsoft/playwright#29030]
### System info
- Playwright Version: [v 1.40.1]
- Operating System: [ Windows 11]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info: 

### Steps

When I follow the instructions here

https://playwright.dev/docs/test-parameterize#passing-environment-variables

I made a .env file, and input: 'USERNAME="me"' as it suggested.

but instead of getting 'me' when running: 'process.env.USERNAME'

I got my laptop's username.

And after I changed the .env file to 'NAME="me"', and ran 'process.env.NAME'

Everything got back to normal.

I got 'me' from .env file and by 'process.env.NAME'.

### Conclusion

So, I think .env should ban the setting of  USERNAME.

Please change your example on https://playwright.dev/docs/test-parameterize#passing-environment-variables

And warn users about this thing could happen.

**Comment by mxschmitt** [comment]
Looks not like an issue on our side, its already filed in the dotenv repository: https://github.com/microsoft/playwright/issues/29030

Maybe we can change the example value in the meantime.

**Comment by mxschmitt** [comment]
Workaround: `require('dotenv').config({ override: true })`

**Comment by katejou** [comment]
Thank you very much. I am so happy to contribute!

**Comment by EmmyGod1** [comment]
It seems that mac OS does not allow process.env.(anything User) to override the mac as User.

Everything worked fine, the moment I changed my DB_Username key on dotenv file to just Name.
