### ISSUE TITLE
Is component testing meant to be experimental?

### ISSUE THREAD

**Issue by mercmobily** [microsoft/playwright#29037]
In this page:

https://playwright.dev/docs/test-components

It still shows the component testing as "experimental".

I am trying to push PlayWright to become the default testing suite for Vue (https://github.com/vuejs/docs/issues/2639#issuecomment-1891187699).

Do you guys have plans mark the component testing side as "final" rather than "Experimental"?

**Comment by mxschmitt** [comment]
We unfortunately can't commit on a specific time frame, but I can confirm that we are working on it! So yes, we definitely have plans!
