### ISSUE TITLE
[BUG] Playwright/Chrome copy and paste is not working in headless mode

### ISSUE THREAD

**Issue by lampewebdev** [microsoft/playwright#29038]
### System info
- Playwright Version: [ALL]
- Operating System: [All]
- Browser: [Chromium]
- Other info:

### Source code
A repo with the source code and a GitHub workflow 
https://github.com/lampewebdev/playwright-chrome-custom-copy-and-paste-error

error output:
https://github.com/lampewebdev/playwright-chrome-custom-copy-and-paste-error/actions/runs/7567772442/job/20607586952#step:7:98

Source code of the copy and paste:
https://github.com/lampewebdev/playwright-chrome-custom-copy-and-paste-error/blob/6aa843ccb6dbc76776c169b37184065930494b0b/src/routes/%2Bpage.svelte#L17C3-L17C3

Source code of the tests:
https://github.com/lampewebdev/playwright-chrome-custom-copy-and-paste-error/blob/6aa843ccb6dbc76776c169b37184065930494b0b/tests/test.ts#L3

**Steps**
- git clone git@github.com:lampewebdev/playwright-chrome-custom-copy-and-paste-error.git
- cd playwright-chrome-custom-copy-and-paste-error
- pnpm install
- pnpm run test:integration

**Expected**
in headless mode:
The correct text should be pasted into the textarea and the tests should pass.

**Actual**
The textarea is empty and the test fail in headless mode only.
The tests pass in headed mode.

**Additional information**

- https://developer.chrome.com/blog/web-custom-formats-for-the-async-clipboard-api

**Comment by lampewebdev** [comment]
Update: after downgrading chrome to 112.0.5577.0 (Developer Build) (arm64) the tests are passing.

**Comment by StanislavGrishaev** [comment]
Have you tried https://playwright.dev/docs/api/class-browsercontext#browser-context-grant-permissions ? 
`await context.grantPermissions(['clipboard-write']);`
works for me in chromium headless.

**Comment by mxschmitt** [comment]
Great discovery with the good and bad version, this helps us a lot in order to bisect Chrome.

So its about the `custom copy and paste should work` tests? I tried testing it on macOS and Linux but they were always failing for me, also with Chrome 112 which is Playwright 1.32.

**Comment by lampewebdev** [comment]
> Great discovery with the good and bad version, this helps us a lot in order to bisect Chrome.
> 
> So its about the `custom copy and paste should work` tests? I tried testing it on macOS and Linux but they were always failing for me, also with Chrome 112 which is Playwright 1.32.

also to make 1 of the 2 projects pass you simply need to run:
```
pnpm run test:integration --headed
```

The moment playwright runs in headed mode everything works fine.

'chromiumNewHeadless' will always fail since  in the config headless is forced

**Comment by lampewebdev** [comment]
Update: I found another interesting thing:
![image](https://github.com/microsoft/playwright/assets/44268468/b6f7cfbb-28a6-46cb-93cb-a16cb0cb334b)
What you can see here is the list of items types on for one item from the cilpboard. In the cases were the test passes you can see 2 entries and in the test cases were it does not pass you can only see 1 entry in the array.

Not sure if this helps because even if the custom data on the clipboard is there then it is an empty array.

**Comment by mxschmitt** [comment]
I bisected down to:

https://chromium.googlesource.com/chromium/src/+log/06e192db284d6c50f8f9bd08068cda4e706a4f4b..bcb44eca3346049069a905f72d0a3d9aa9939230

Good https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac_Arm/1102237/ cr 28 06e192db284d6c50f8f9bd08068cda4e706a4f4b
 
Bad https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac_Arm/1102274/ cr 30 bcb44eca3346049069a905f72d0a3d9aa9939230

**Comment by lampewebdev** [comment]
@mxschmitt it looks like a fix will land in chrome 122.
 https://chromium-review.googlesource.com/c/chromium/src/+/5092547

I checked it and it is a partial fix for this. now it works with custom web formats but plain text is not working. I'm investigating it further.

**Comment by mxschmitt** [comment]
Note: If you want to test a very recent version (like max 3 days old), you can try:

```
pnpm install @playwright/test@next
pnpm exec playwright install chromium-tip-of-tree
put "channel: 'chromium-tip-of-tree'" into your package.json
```

**Comment by myshov** [comment]
We have the same issue, but copy/paste in headless mode on Linux works ok and don't work on macOS.
Playwright version is 1.40.1

**Comment by lampewebdev** [comment]
The chromium guys have marked it as resolved with the latest chromium version but for me its still not working.

https://bugs.chromium.org/p/chromium/issues/detail?id=1519407#c12

**Comment by mxschmitt** [comment]
I can confirm the Chromium upstream fix works. Takes probably 1-2 months until it reaches Beta. In the meantime I recommend tip-of-tree via Canary (should be there in around 12-24h):

```diff
diff --git a/playwright.config.ts b/playwright.config.ts
index bf8046c..f31beff 100644
--- a/playwright.config.ts
+++ b/playwright.config.ts
@@ -15,6 +15,9 @@ const config: PlaywrightTestConfig = {
             name: 'chromium',
             use: {
                 ...devices['Desktop Chrome'],
+                launchOptions: {
+                    channel: "chromium-tip-of-tree"
+                },
             },
         },
         {
@@ -24,6 +27,7 @@ const config: PlaywrightTestConfig = {
                 ...devices['Desktop Chrome'],
                 launchOptions: {
                     args: ['--headless=new'],
+                    channel: "chromium-tip-of-tree"
                 },
             },
         },
```
