### ISSUE TITLE
[BUG] All the elements are hidden even if the locators are well define

### ISSUE THREAD

**Issue by CatalinCaila** [microsoft/playwright#29036]
### System info
- Playwright Version: [V: 1.41.0]
- Operating System: [Windows 10 Enterprise.]
- Browser: [Chromium, Firefox, WebKit]
- Other info:
- Angular: [Version 17]

![Fail to find the element](https://github.com/microsoft/playwright/assets/31596918/1fd1aa7b-2233-4afe-a5d7-f4d1ff54d1a3)
![Element on UI](https://github.com/microsoft/playwright/assets/31596918/9b20af80-ac84-4cb8-bb95-917aca33f558)
![Button Click Timeout exceeded](https://github.com/microsoft/playwright/assets/31596918/d97c2138-0cbc-4d48-ae6f-fefffacefd55)
![Inspector for element ](https://github.com/microsoft/playwright/assets/31596918/d62c3ed6-3c4d-4ec1-aeef-ac1a8381cec8)

### Source code

[tiriopt.zip](https://github.com/microsoft/playwright/files/13974183/tiriopt.zip)\

**Steps**
- Take the locator using command:  npx playwright codegen
- Run the tests in the browsers: Chromium, Firefox, WebKit
- Set waiting time to load all the elements
- Check if button "Creation date Desc" is visible 
- Check if on button "Creation date Desc" click method can be executed
- I don't have any CSS display:none and visibility: hidden 

- Also if I am trying to click on another element "collapse" is not working
- Was used an ID to be sure that the element is unique

![Collapse click](https://github.com/microsoft/playwright/assets/31596918/9cc0a872-f038-4d7d-bba9-33c88f20b863)
![Collapse button hidden](https://github.com/microsoft/playwright/assets/31596918/5eaae1b0-52bf-459e-b376-2477f611bb87)

**Expected**
Elements to be visible and to can click on them. 

**Actual**
Elements are not visible and click is not possible.

**Comment by CatalinCaila** [comment]
Was because of defining a page = await browser.newpage() after removing this from tests it works

**Comment by mxschmitt** [comment]
This issue contains a too large reproducible. Unfortunately, we don't have time to debug a project this large with a website that massive. If you have a reduced test case, we can take a look. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Ideally with a single test file. Thanks for your understanding!
