### ISSUE TITLE
[BUG] When open tab "About Google Chrome" user see message "An Error occurred. Error Code 9"

### ISSUE THREAD

**Issue by OlegRomaniuck** [microsoft/playwright#29042]
### System info
- Playwright Version: [v1.41.1]
- Operating System: [ macOS 12.7.2]
- Browser: [Chromium]
- Other info:
node version:  v16.10.0
npm version: 7.24.0
### Source code

Install playwright using command: 
npm install @playwright/test@1.41.0 --save --no-audit
I run tests using this command: 
npx playwright install && playwright test --config=tests/example/playwright.config.js tests/example/specs

<img width="1507" alt="Screenshot 2024-01-18 at 13 40 59" src="https://github.com/microsoft/playwright/assets/11087838/b13e2bbc-ecd6-46c2-95d7-a3e23dccfff2">

**Expected**
Display like standart chrome browser

**Actual**
Error display for user

**Comment by mxschmitt** [comment]
The error is because updating via Chromium itself is not supported. Updating browsers works only via npx playwright install / updating Playwright itself, see [here](https://playwright.dev/docs/browsers).

**Comment by OlegRomaniuck** [comment]
> The error is because updating via Chromium itself is not supported. Updating browsers works only via npx playwright install / updating Playwright itself, see [here](https://playwright.dev/docs/browsers).

Sorry, looks like I don't clearly understand how to right interpret your answer . Playwright is a latest = 1.41.0, before running tests  I run command of course:  npx playwright install.

**Comment by mxschmitt** [comment]
Yes, but the screenshot you are referring to is from the Chromium Updater which is unable to update itself.

What are your expectations? The error you are seeing is expected from our side - since updates happen via npx playwright install and not via Chromium itself.
