### ISSUE TITLE
[Feature] Allow global timeout config for expect.toPass

### ISSUE THREAD

**Issue by sarah-gelt** [microsoft/playwright#29041]
When using `expect.toPass` we have to pass a timeout value to each call and it's easy to forget. If the assertion fails, the runner has to wait for the overall test timeout (in our config this is 2 mins) before it will fail and potentially retry the test. Almost all our tests which use it have the same value, with only a small number that are set a little longer.

A global config value for `expect.toPass` would allow tests to fail more quickly should a specific value not be provided in a test, but could also be overridden at the suite, test or individual call level where more flexibility is required.

**Comment by mxschmitt** [comment]
Sounds like https://github.com/microsoft/playwright/pull/28231 which we'll release as part of 1.42. I either recommend waiting or trying https://playwright.dev/docs/canary-releases for now if you want to give the Beta version a try!
