### ISSUE TITLE
[BUG] Detect if application is running via Playwright

### ISSUE THREAD

**Issue by sjmc11** [microsoft/playwright#29045]
When running my application via Playwright tests I would like to disable axios cache adapter. 
This prevent my tests from correctly awaiting `this.page.waitForResponse(...)` because the requests only fire once and results in a failure.

I am using a globalSetup script where trying to set either an `.env` or `window` variable.

```
async function globalSetup () {
  window.playwright = true
  process.env.PLAYWRIGHT = 'TRUE'
  // Rest of setup
}
```

Inside a misc file within my SPA I'd like to be able to do something like the following:

```
if (process.env.PLAYWRIGHT || window.playwright) {
   console.log('is playwright')
   this.http.defaults.adapter = null
} else {
   console.log('is NOT playwright')
}
```
I've can't find in the docs how to set or detect if my application is being run by playwright tests. Could anyone advise?

I have seen this discussion which does work, but this means declaring a `beforeEach` on all my test files. I would prefer to do this once globally.
 https://github.com/microsoft/playwright/issues/19584

Thanks

**Comment by mxschmitt** [comment]
For that you can e.g use [`context.addInitScript`](https://playwright.dev/docs/api/class-browsercontext#browser-context-add-init-script) and define a global variable inside your tests which your cache adapter is reading

In the Playwright world this would mean e.g.

```ts
beforeEach(({ context }) => {
  await context.addInitScript(() => window.IS_PLAYWRIGHT = true);
})
```

globalSetup runs in Node.js while you want code which runs inside the browser, so that your web-application is aware of it.

So yes, this is exactly what https://github.com/microsoft/playwright/issues/19584 is recommending. If you want to have this re-usable you can do e.g. this:

```ts
// baseTest.ts
import { test as baseTest } from '@playwright/test';

export const test = baseTest.extend({
    context: async ({ context }, use) => {
        await context.addInitScript(() => {
            window.isUnderTest = true;
        });
        await use(context);
    }
});

export { expect } from '@playwright/test';
```

and

```ts
import { test, expect } from './baseTest';
```

Every test instance would have this applied then.

**Comment by sjmc11** [comment]
Legend, thank you @mxschmitt - will give this a try.

**Comment by mxschmitt** [comment]
Closing as per above then!

**Comment by vtsvetkov-splunk** [comment]
For everyone else who come to solve the same issue, use [navigate.webdriver](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/webdriver) property. You don't need to set anything from playwright

**Comment by tsvetkovv** [comment]
For everyone else who come to solve the same issue, use [navigate.webdriver](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/webdriver) property. You don't need to set anything from playwright

**Comment by pishoyg** [comment]
[`navigate.webdriver`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/webdriver) doesn't work for me, for some reason. It's `undefined`!
