### ISSUE TITLE
[Feature] Readonly discussion

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#29059]
Let us know what functionality you'd like to see in Playwright and what your use case is.

I know that it was decided to close the discussion tab since there was not much interaction. But I think it had great tips/suggestions to the questions that were answered and I use to look at them to make my tests robust. Would love to see a readonly version back again if it is possible.

Thanks.

**Comment by mxschmitt** [comment]
GitHub as of today does not offer read-only discussions. So we unfortunately can't do that as of today!
