### ISSUE TITLE
[BUG] on playwright-ct-react update() of a mounted component ignores beforeMount 

### ISSUE THREAD

**Issue by steschi** [microsoft/playwright#29058]
### System info
- Playwright Version: v1.41.0
- Operating System: All
- Browser: All

### Source code

```tsx
// ./number-input.ct.tsx

test("number-input-demo", async ({ mount }) => {
  let state = 1;
  const onChange = (e) => (state = e);

  // NumberInput depends on a React Context injected by beforeMount hook in playwright/index.tsx
  const component = await mount(<NumberInput value={state} onChange={onChange} />);

  const inputField = component.locator("input");

  await inputField.fill("5");
  await inputField.evaluate((e) => e.blur());
  await expect(state).toEqual(5);

  state = 7;

  // This fails the test
  await component.update(<NumberInput value={state} onChange={onChange} />);

  await expect(inputField).toHaveValue("7");
});

```

```tsx
// ./playwright/index.tsx

export type HooksConfig = {};

beforeMount<HooksConfig>(async ({ App }) => {
  return (
    <SomeReactContextProvider>
      <App />
    </SomeReactContextProvider>
  );
});

```

**Steps**
- Run the above test

**Expected**

When the component is updated the beforeMount hooks are reapplied to keep any required context in place

**Actual**

Because of the way `window.playwrightUpdate` is [implemented](https://github.com/microsoft/playwright/blob/b7d22b64e8c56eb83e0d631a46d93d5ee1c25544/packages/playwright-ct-react/registerSource.mjs#L81) the hooks are not applied and the test fails because the `NumberInput` depends on a context which is now missing

**Possible Fix**

Updating `window.playwrightUpdate` as follows works for me, though I am not sure about any other effects this might have or how to handle the hooksConfig property.

```tsx
window.playwrightUpdate = async (rootElement, component) => {
  if (component.kind !== 'jsx')
    throw new Error('Object mount notation is not supported');

  await __pwResolveComponent(component);
  const root = __pwRootRegistry.get(rootElement);
  if (root === undefined)
    throw new Error('Component was not mounted');

  let App = () => __pwRender(component);
  for (const hook of window.__pw_hooks_before_mount || []) {
    const wrapper = await hook({ App });
    if (wrapper)
      App = () => wrapper;
  }
  root.render(App());
};
```

**Comment by sand4rt** [comment]
@steschi looks like you're right about the problem and the solution!

**Comment by pavelfeldman** [comment]
Not quite wrt the solution, we don't want to call the root.render on update and we only want to call beforeMount once, before we mount. I have a fix and working on the test for it.
