### ISSUE TITLE
Not able to install browser dependencies for the firefox and webkit over the RHEL runners for playwright

### ISSUE THREAD

**Issue by gahlawat-87** [microsoft/playwright#29060]
### System info
- Playwright Version: v1.40
- Operating System: RHEL 
- Browser: Firefox, WebKit

### Source code
 we tried to execute the automation scripts on RHEL runners via the github actions over firefox and webkit.
While executing we got error related to the browsers and given the command to install the firefox and webkit drivers 

**Firefox**:  on github its showing errors as to install below dependency: 
	 Please install them with the following command:      
          sudo yarn playwright install-deps     
    Alternatively, use apt:       
  sudo apt-get install libdbus-glib-1-2  
 
error we got while executing on RHEL server 

unable to locate package libdbus-glib-1-2

**webkit** : on Github it shows errors as below 

Host system is missing dependencies to run browsers.  
      Missing libraries:                                    
          libicudata.so.66                                  
          libicui18n.so.66                                  
          libicuuc.so.66                                    
          libwoff2dec.so.1.0.2                              
          libharfbuzz-icu.so.0                              
          libjpeg.so.8                                      
          libwebp.so.6                                      
          libenchant-2.so.2                                 
          libsecret-1.so.0                                  
          libhyphen.so.0                                    
          libXt.so.6                                        
          libflite.so.1                                     
          libflite_usenglish.so.1                           
          libflite_cmu_grapheme_lang.so.1                   
          libflite_cmu_grapheme_lex.so.1                    
          libflite_cmu_indic_lang.so.1                      
          libflite_cmu_indic_lex.so.1                       
          libflite_cmulex.so.1                              
          libflite_cmu_time_awb.so.1                        
          libflite_cmu_us_awb.so.1                          
          libflite_cmu_us_kal16.so.1                        
          libflite_cmu_us_kal.so.1                          
          libflite_cmu_us_rms.so.1                          
          libflite_cmu_us_slt.so.1                          
          libpcre.so.3                                      
          libffi.so.7                                       
          libx264.so

when we tried to install these dependencies we got same error while installing these dependencies.

**Comment by mxschmitt** [comment]
RHEL is not supported as per the system requirements: https://playwright.dev/docs/intro#system-requirements

We recommend our Docker Container if your host is unsupported: https://playwright.dev/docs/ci-intro#via-containers
