### ISSUE TITLE
Is there a way to locate adjacent locators just like how it is in Selenium?

### ISSUE THREAD

**Issue by sundar-ds** [microsoft/playwright#29064]
Suppose I have a check box and a text next to it and I want to locate the check box that appears before or after the text, is it possible to be done in Playwright?

**Comment by SoniaKaudjhis** [comment]
@sundar-ds you can check this on playwrigth : https://playwright.dev/docs/other-locators#css-matching-elements-based-on-layout

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
