### ISSUE TITLE
[BUG] teardown project is run before the tests

### ISSUE THREAD

**Issue by dorfsmay** [microsoft/playwright#29068]
### System info
- Playwright Version: 1.41.0
- node: v20.11.0
- tsc: Version 4.8.4
- Operating System: Fedora release 38
- Browser: Chromium

### Source code
playwright.config.ts is the one generated by `npx playwright init`, with this modification where I add a global setup and teardown, and the dependencies:

```
projects: [
  {   
    name: 'setup',
    testMatch: /global\.setup\.ts/,
    teardown: 'teardown',
  },
  {   
    name: 'teardown',
    testMatch: /global\.teardown\.ts/,
  },  
  {
    name: 'chromium',
    use: { ...devices['Desktop Chrome'] },
    dependencies: ['setup'],
  },  

  {   
    name: 'firefox',
    use: { ...devices['Desktop Firefox'] },
    dependencies: ['setup'],
  },
```

The tests are the ones generated by `init`. `tests/global.setup.ts`:
```
console.log("H E L L O !")
```

`tests/global.teardown.ts`:
```
console.log("B Y E")
```

**Steps**
- `npx playwright test --project=chromium`

**Expected**
```
H E L L O !

Running 2 tests using 2 workers
  2 passed (5.3s)

B Y E
```

**Actual**
```
H E L L O !
B Y E

Running 2 tests using 2 workers
  2 passed (5.3s)
```

**Additional notes**
This is not just a console output/buffer issue. This is minimum example to test the issue, but in the original work, the global setup project use an API to add users and the global teardown project use the same API to delete those users. When looking at the backend log, I can see that the users are added, the users are then removed, and finally the login attempts are made, but fail since the users have now been deleted.

Is there a way to trace the project priorities to try to understand why teardown is run before the tests?

**Comment by dorfsmay** [comment]
This is solved, I added using `test()` in my setup and teardown and it works. My new tests/global.teardown.ts:
```
import { test } from '@playwright/test'

test('test A', async ({ page }) => {
console.log("B Y E")
})
```

I wish this was mentioned in the documentation.

**Comment by mxschmitt** [comment]
Playwright has two ways of doing setup/teardown see here: https://playwright.dev/docs/test-global-setup-teardown

In your case you are doing option 1, which is the new / preferred way of doing it. If you have any concrete docs suggestions, let us know!

**Comment by dorfsmay** [comment]
In the doc, I would:

- add wording to the fact that those scripts cannot be simple ts/js scripts, that they **require** to use the Playwright APIs and at the minimum the `test()` API.
- make the example much simpler. The given example feels more like documentation for the StorageState API. Possibly something as simple as I used in https://github.com/microsoft/playwright/issues/29068#issuecomment-1900988944
- Document StorageState and APIRequestContext separately
