### ISSUE TITLE
[BUG] Coverage types incorrect

### ISSUE THREAD

**Issue by LarsDenBakker** [microsoft/playwright#2906]
**Context:**
- Playwright Version: v1.2.0
- Operating System: Mac
- Node version: 14.1.0
- Browser: Chromium

The types for test coverage are missing some values.

[`JSCoverageEntry`](https://github.com/microsoft/playwright/blob/a91ec9a15d3ed5dccf61e1128dfb8d503a47b6c5/src/types.ts#L150) is missing `scriptId` from v8's [`ScriptCoverage`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/inspector.d.ts#L1546) as well as [`isBlockCoverage`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/inspector.d.ts#L1540). Both these are present in the actual output.

**Comment by ruppysuppy** [comment]
I would like to work on this issue. I would to add the `isBlockCoverage` field. But could you tell me what I need to do about the `ScriptCoverage`?

**Comment by mxschmitt** [comment]
It would be then something like that @ruppysuppy. He references to the ScriptCoverage type, because we have mostly the same so you can orient on that.
```ts
export type JSCoverageEntry = {
  url: string,
  scriptId: string,
  source?: string,
  functions: {
    functionName: string,
    ranges: JSRange[],
    isBlockCoverage: bool
  }[]
};
```

**Comment by ruppysuppy** [comment]
Thanks a lot @mxschmitt
