### ISSUE TITLE
[Feature/Bug] Stream viewport

### ISSUE THREAD

**Issue by lolouthefox** [microsoft/playwright#29085]
Is there a way to stream viewport because i tried taking screenshots, it doesn't work. Then I tried:
```
this.video = await this.page.video();
const videoFrame = await this.video.screenshot({ type: "png" });
const videoData = base64.encode(videoFrame);
```

But page.video() evaluates to null for some reason...

**Comment by yury-s** [comment]
Try following [this guide](https://playwright.dev/docs/videos) to capture the video using Playwright Test config. If you want to manually record the video, you can use [page.video()](https://playwright.dev/docs/api/class-page#page-video) API along with context parameter [recordVideo](https://playwright.dev/docs/api/class-browser#browser-new-context-option-record-video).

But we actually recommend [recording traces](https://playwright.dev/docs/trace-viewer-intro) over the video. As they allow to inspect the DOM after the test has finished and contain a lot of useful debug info.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
