### ISSUE TITLE
[Feature] Electron complete support

### ISSUE THREAD

**Issue by aravind250298** [microsoft/playwright#29082]
Hello team, 

I just wanted know that is there anyway that we can get full electron support in playwright?

As it's in experimental stage from past few years. And many people are using electron apps now a days.

So it would be bifacial if we get electron app support as soon as possible.

**Comment by yury-s** [comment]
There are no current plans to take electron support out of experimental. With that said, if you need particular functionality feel free to open a feature requests for that and we'll try to address it.
