### ISSUE TITLE
[Feature] Debugging support in Remote Browser

### ISSUE THREAD

**Issue by llamabytes** [microsoft/playwright#29086]
Right now if I run a test in a remote browser using ws connection, passing a --debug flag doesn't seem to help debug the test. It simply doesn't open the playwright inspector. Any suggestions or alternatives?

My remote browser is running at

```
    connectOptions: {
      wsEndpoint: 'ws://localhost:64431',
    },
```
I am trying this out since my code is in remote machine and through this I want to run tests in my local machine. While with this I can do that, but debugging of tests doesn't work.

**Comment by yury-s** [comment]
Can you tell us a bit more about your setup where you have tests running remotely but with a local browser, is it some codepsaces setup?

If you run "remote" browser in headed mode, `--debug` options will not work, but the inspector should show up on the local machine if you do `page.pause()`, will that work for you?

**Comment by llamabytes** [comment]
We use cloud dev environment to which we ssh. Now since devs would need to debug tests in a browser, I thought I could use the local machine to establish a ws connection with the remote machine and run tests in local machine. 
Can you help me with why --debug flag doesn't work? I am able to kick off the inspector in local machine from my remote machine by overriding `debugEnv` to 1 in `packages/playwright-core/src/utils/debug.ts`. But I am unable to find out how that gets set to 1 in general and why the --debug flag isn't reflected.

**Comment by yury-s** [comment]
> Can you help me with why --debug flag doesn't work? I am able to kick off the inspector in local machine from my remote machine by overriding debugEnv to 1 in packages/playwright-core/src/utils/debug.ts. 

Playwright doesn't propagate `PWDEBUG` to the remote machine, so it only affects processes on the same machine where you run the tests. This is an implementation detail though.

How do you launch local browser which you connect to from the cloud? You may be able to just set `PWDEBUG=1` environment variable on the machine where you launch the browser.

**Comment by llamabytes** [comment]
I am launching the browser using chromium.launchServer in a server.mjs
script. That then listens to the ws port.

// server.mjsconst { chromium } = ***@***.***/test');const
server = await chromium.launchServer({ headless: false
});console.log(server.wsEndpoint())


Is there no way to propagate PWDEBUG flag to the machine where my browser
is running?

**Comment by llamabytes** [comment]
I am launching the browser using chromium.launchServer in a server.mjs
script. That then listens to the ws port.

```
// server.mjs
const { chromium } = ***@***.***/test');const
server = await chromium.launchServer({ headless: false
});console.log(server.wsEndpoint())
```

Is there no way to propagate PWDEBUG flag to the machine where my browser
is running?

**Comment by llamabytes** [comment]
> You may be able to just set PWDEBUG=1 environment variable on the machine where you launch the browser.
Where do I set PWDEBUG=1? Setting it in process.env doesn't see to work

**Comment by llamabytes** [comment]
Can I pass some meta data to my Playwright Server through the ws connection that could help toggling the PWDEBUG flag

**Comment by yury-s** [comment]
> Is there no way to propagate PWDEBUG flag to the machine where my browser
is running?

No, you launch the browser before connecting to it, so you need a separate channel to pass the env. If you run your server as follows it will launch the inspector too:

```sh
PWDEBUG=1 node server.mjs
```

> Can I pass some meta data to my Playwright Server through the ws connection that could help toggling the PWDEBUG flag though in my local I can always do PWDEBUG=1 yarn start pwt-server

Yes, see above.

> the inspector should show up on the local machine if you do page.pause(), will that work for you?

This is the recommended way to open the inspector in the middle of a test.

**Comment by llamabytes** [comment]
Hi 
`PWDEBUG=1 node server.mjs` opens the debugger on my local machine but the inspector doesn't show the test file source for the test I am running on my remote machine. Could you help how to fix that.
