### ISSUE TITLE
Playwright not able to locate video element 

### ISSUE THREAD

**Issue by craitose** [microsoft/playwright#29088]
System info
Playwright Version: [v1.40.1]
Operating System: [Windows 11]
Browser: [All, Chromium, Firefox, WebKit]
Other info: typescript

Source code

```html
<!DOCTYPE html>
<html>
<body>

<h1>The video element</h1>
<div id="video" class="parent" style:"z-index: 0; overflow: hidden">
<div class="video_component"></div>
<video id="video-live" playsinline width="320" height="240" controls autoplay loop>
  <source src="https://www.w3schools.com/tags/movie.mp4">
  
  Your browser does not support the video tag.
</video>
</div>
</body>
</html>
``` 

I have tried to access the properties of video-child-live by declaring the locator with the below selectors:

```typescript
import { test, expect, type Page } from '@playwright/test';

test('w3schools video element within div',async ({page}) =>{
   await page.goto('https://craitose.w3spaces.com/videoComponentWithinDiv.html');

   
   await page.frameLocator('iframe[name="iframeResult"]').locator('video').waitFor();
   const isRightVid = (await page.frameLocator('iframe[name="iframeResult"]').locator('video').evaluate((video) => video.id)).toString();
   await page.pause();

   console.log(isRightVid);
``` 

Steps

[Run the test]

Expected

Expect playwright to find the video element

Actual

Error: locator.waitFor: Test timeout of 30000ms exceeded.
    Call log:
      - waiting for frameLocator('iframe[name="iframeResult"]').locator('video') to be visible

**Comment by craitose** [comment]
Is it because the parent div has the attribute of overflow: hidden?

**Comment by mxschmitt** [comment]
Would it be possible to share a reproduction with us which we can run locally? I tried to reproduce as part of https://github.com/microsoft/playwright/issues/29084#issuecomment-1902082718 and was not able to.

A code snippet we can run locally is essential for us in order to triage an issue efficiently, otherwise we are not able to act on it. Thanks your understanding!

**Comment by craitose** [comment]
Sure I have created a code snippet in w3schools just for this issue, hopefully you can access it. I have also added complete yet simple test code in typescript.

**Comment by mxschmitt** [comment]
You don't have an iframe on your page, in your scenario, the following would work:

```ts
test('w3schools video element within div',async ({page}) =>{
   await page.goto('https://craitose.w3spaces.com/videoComponentWithinDiv.html');
   await page.locator('video').waitFor();
   const isRightVid = await page.locator('video').evaluate((video) => video.id);
   console.log(isRightVid);
});
```

**Comment by craitose** [comment]
Thanks mxschmitt, I was a bit confused as your previous example source code did not have an iframe either but your test worked. I have however figured out my issue with my original code, the element was indeed not seen because it was not loading in chromium. After updated and tried the test in firefox, the video element was found. Thank you for your time and patience, you can go ahead and close this issue.
