### ISSUE TITLE
[BUG] canvas.toBlob() returns wrong image type on Ubuntu OS and Webkit browser

### ISSUE THREAD

**Issue by DontGiveAFck** [microsoft/playwright#29097]
### System info
- Playwright Version: [v1.41]
- Operating System: [Ubuntu]
- Browser: [WebKit]

### Source code

```
import { expect, test } from '@playwright/test';

test.describe('Canvas to blob result type check', async () => {
  test('Canvas to blob result type check @screen-all', async ({ page }) => {
    const imageType = await page.evaluate(async () => {
      const canvas = document.createElement('canvas');

      canvas.width = 100;
      canvas.height = 100;

      const getImageType = () =>
        new Promise((resolve) => {
          canvas.toBlob((ret) => {
            resolve(ret?.type);
          }, 'image/jpeg');
        });

      return await getImageType();
    });

    expect(imageType).toEqual('image/jpeg');
  });
});
```

**Steps**
1. Run code above

**Expected**

imageType equals 'image/jpeg' and test was passed

**Actual**

imageType equals 'image/png' and test wasn't passed

[Describe actual behavior]
For some reason when converting canvas to blob with image/jpeg type, actual converted image has image/png type. Reproduced inside container with **mcr.microsoft.com/playwright:v1.41.1-jammy** image in Webkit browser.

**Comment by mxschmitt** [comment]
Investigation: Most likely its this upstream bug: https://bugs.webkit.org/show_bug.cgi?id=180352

It passes in headed (GTK).

**Comment by yury-s** [comment]
Yes, this is WebKit WPE specific.
