### ISSUE TITLE
[Question] PlywrightTest vs Playwright vs Playwright-Core

### ISSUE THREAD

**Issue by jaktestowac** [microsoft/playwright#29092]
What are main differences and usage scenarios for Playwright packages: PlywrightTest vs Playwright vs Playwright-Core

There is some explanation in docs https://playwright.dev/docs/library but I wonder how it refers to fact that `@plywright/test` package looks like proxy to `playwright` package.

Additionally docs contains very limited information about Playwright-Core https://playwright.dev/docs/release-notes#%EF%B8%8F-breaking-changes

**Comment by yury-s** [comment]
You normally do not use `playwright-core` directly, it's just an implementation detail. The package is shared by other playwright packages intended to be consumed by the clients.
`@playwright/test` - this is the default choice when you want to run web tests with playwright
`playwright` - maybe you choice if you don't need test runner but want to use [playwright library](https://playwright.dev/docs/library). In the new projects you can simply use @playwright/test instead, playwright package is there for historical reasons.

> There is some explanation in docs https://playwright.dev/docs/library but I wonder how it refers to fact that `@plywright/test` package looks like proxy to `playwright` package.
> 

This is just an implementation detail. It may change in the future and this is not something that affects the clients.

**Comment by snehilshah** [comment]
I do not have any use case of the playwright test suite, yet I should install `@playwright/test` and just not use the test suite? or is it still better to install `playwright` package
