### ISSUE TITLE
[BUG] Download file not working as expected

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#29091]
### System info
- Playwright Version: [v1.40]
- Operating System: Mac
- Browser: Chromium
- Other info:

### Source code
Hi, I am trying to click on a link to download the file but it is failing due to network issue. Is there something I am missing? I tried the same download code on a sample site and it worked. I will try to work on a self-contained repo. But just wanted to post it here to see if I am missing something very common step.

**Steps**
```
const downloadPromise = this.page.waitForEvent('download');
await this.page.getByRole('link', { name: 'Download' }).click();
const download = await downloadPromise;
await download.saveAs('./' + download.suggestedFilename());
```
- [Run the test]

**Expected**
File is downloaded

**Actual**
The following error is displayed
<img width="324" alt="Screenshot 2024-01-21 at 11 35 07 PM" src="https://github.com/microsoft/playwright/assets/22205721/5aaf88a4-1005-4b9c-993b-d0f11bbab8a4">
<img width="512" alt="Screenshot 2024-01-21 at 11 35 19 PM" src="https://github.com/microsoft/playwright/assets/22205721/47db16ac-3807-4db6-9789-29bf88feff71">

**Comment by yury-s** [comment]
It's hard to tell without a repro. If the download started and you got the event, `saveAs` call should just wait until the download is finished. Perhaps the server interrupts the transfer or there is some other network issue. Does it work in the browser without Playwright?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by kinopop** [comment]
> It's hard to tell without a repro. If the download started and you got the event, `saveAs` call should just wait until the download is finished. Perhaps the server interrupts the transfer or there is some other network issue. Does it work in the browser without Playwright?

YES,it work in the browser without Playwright
