### ISSUE TITLE
[BUG]: TypeScript error with using test.extend 

### ISSUE THREAD

**Issue by BlackySoul** [microsoft/playwright#29098]
### System info
- Playwright Version: 1.41.1
- Operating System: macOS 13.5.1
- Browser: -
- Other info: 

### Source code

Hi! I'm trying to use [test.extend](https://playwright.dev/docs/api/class-test#test-extend) in the following way:

```
import { test as base } from "@playwright/experimental-ct-react";

export type Options = { defaultItem: string };

// Extend basic test by providing a "defaultItem" option and a "todoPage" fixture.
export const test = base.extend<Options>({
  // Define an option and provide a default value.
  // We can later override it in the config.
  defaultItem: ["Do stuff", { option: true }],
});
```

However, I'm receiving a TypeScript error:

<img width="858" alt="image" src="https://github.com/microsoft/playwright/assets/7431217/5a340540-5929-4928-96d8-4d89b3d8ddd5">

Here's the repo: https://github.com/BlackySoul/playwright-test

**Steps**
- Clone the repo
- Execute the folowwing commands:
  - `cd playwright-test`
  - `npm install` 
  - `lint:types`

**Expected**

No error present 

**Actual**

<img width="743" alt="image" src="https://github.com/microsoft/playwright/assets/7431217/20c3005f-be37-465e-98af-0ac577f48be7">

- related #29070

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/27509
