### ISSUE TITLE
Tests not using configuration; headed mode and ignoring timeouts

### ISSUE THREAD

**Issue by ander-murane** [microsoft/playwright#29108]
### System info
- Version 1.40.1
- MacOS 14.2.1 (23C71)
- Browser: Chromium
- Other info:

### Source code
File: playwright.config.js, stored at top level
```
module.exports = defineConfig({
  globalTimeout: 140 * 60 * 1000,
  timeout: 10 * 60 * 1000,
  expect: {
      timeout: 10 * 2000,
  },
  testDir: './tests/specs',
  fullyParallel: false,
  retries: process.env.CI ? 0 : 0,
  workers: process.env.CI ? 1 : 1,
  use: {
    headless: true,
    screenshot : "only-on-failure",
    video : "retain-on-failure",
    actionTimeout : 20000,
    navigationTimeout : 90000,
  },
```
**Steps**
`npx playwright test my-test.spec.js`

**Expected**
- Browser runs headless
- Test and beforeAll timeouts should equal 600000 ms. 

**Actual**
TEST ERROR:
   - `"beforeAll" hook timeout of 30000ms exceeded.`
   - Tests run headed (tests run in browser). I have also tried not specifying `headed` and it still always runs headless

**Comment by yury-s** [comment]
Could it be that a different config gets picked up? Can you share full repro so that we could try it locally?

**Comment by ander-murane** [comment]
I have been talking to the team and it sounds like someone may have hidden a configuration somewhere else. Let me dig into this. Thank you for the quick response

**Comment by yury-s** [comment]
Ok, closing this issue. If it still fails and you think this is a playwright bug please file a new bug and provide a minimal self-contained project that we could run locally to reproduce the problem.
