### ISSUE TITLE
[question] sharding, peoject dependencies and session files - how do these interact?

### ISSUE THREAD

**Issue by osdiab** [microsoft/playwright#29102]
Hi, the auth docs talk about using project dependencies alongside saving a file to store the session and restore it in individual tests. This is fine, but when you add in sharding in an environment like GitHub Actions, it seems like if one shard ran code for the auth project, then how would another shard running the dependent test project have access to that session file? Would the auth dependency project run on each worker multiple times or something? Unclear to me how exactly these features interact, if anyone has a clearer mental model that would be helpful. Thanks!

**Comment by yury-s** [comment]
Sharding follows the same rules as described [here in the docs](https://playwright.dev/docs/test-projects#test-filtering), i.e. if some tests in a shard belong to a project that has dependencies, all those dependencies will run before the tests in the shard. The sharding only applies to the deepest tests/projects in the dependency chain.

**Comment by osdiab** [comment]
That makes sense, would be good to mention that in the Sharding page/the Authentication page since there wasn't any direct mention of how it would behave, and it seems mystical that it "just works" even when I know that GitHub Actions runners don't share a filesystem. Makes sense that those dependency projects would just be run as many times as there are shards.
