### ISSUE TITLE
need targetFilter similar puppeteer

### ISSUE THREAD

**Issue by idhil23** [microsoft/playwright#29110]
in puppeteer there is a targetFilter at launch, how to implement it for playwright

`const browser = await puppeteer.launch({
    targetFilter: (target) => !!target.url(),
    ignoreHTTPSErrors: true,
    headless: false,
});`

**Comment by yury-s** [comment]
There is no such api in playwright. Could you describe what you are trying to achieve and what is missing in the current Playwright APIs?

**Comment by dgtlmoon** [comment]
@idhil23 it would really help if people explained themselves more when reporting an issue, since you've closed the issue and had someone donate time to look into it, care to tell us what it is you solved and what is it you are trying todo with `targetFilter` exactly?
