### ISSUE TITLE
[BUG] Playwright selection option does not select multiples when they have the same text

### ISSUE THREAD

**Issue by autovaton** [microsoft/playwright#29127]
### System info
- Playwright Version: [v10.1.0]
- Operating System: [Windows 11]
- Browser: [All]
- Other info:

The selectOption method does not select multiple items if those items have the same text even if the select is set to "multiple."

**Steps**

Given this select in HTML:

```
<select name="resources" multiple="multiple" >
   <option id="1">red</option>
   <option id="2">red</option>
   <option id="3">red</option>
   <option id="4">blue</option>
</select>
```

and calling selectOption with the value 'red' like so:

`locator.selectOption('red');`
or
`locator.selectOption(['red']);`

**Expected**

Expect all 'red' options to be selected

**Actual**

Only the first 'red' option is selected

**Comment by yury-s** [comment]
You can select by index or value instead to disambiguate your choice:
```js
  await page.locator('select').selectOption([{index: 0}, {index: 1}, {index: 2}]);
```
or by value:
```js
  await page.setContent(`<select name="resources" multiple="multiple" >
  <option value="1">red</option>
  <option value="2">red</option>
  <option value="3">red</option>
  <option value="4">blue</option>
</select>`);
  await page.locator('select').selectOption([{value: '1'}, {value: '1'}, {value: '2'}]);
```
Would that work?

**Comment by autovaton** [comment]
Thanks for the reply.

Yes, that is what I am having to do, but it is a headache as I have to get
all the options that match my text then get all their indexes, then build
an array of [{index: #}, {index: #}] and pass that into the selector.  Much
easier to just pass in 'red.'

Please fix.

Thank you.

**Comment by autovaton** [comment]
This is still a defect. Has this been entered as a defect to be fixed?
