### ISSUE TITLE
[BUG] `sec-ch-ua` still not included when headless

### ISSUE THREAD

**Issue by jamesbraza** [microsoft/playwright#29139]
### System info

- Playwright Version: 1.41.0
- Operating System: macOS 13.5.2
- Browser: Chromium 121.0.6167.57
- Other info: Python 3.11.7

### Source code

```python
from contextlib import closing

from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    # 1. Headless
    with closing(p.chromium.launch()) as browser, closing(
        browser.new_context(
            user_agent=(
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"
                " (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
            ),
            record_har_path="headless.har",
        )
    ) as context:
        response_headless = context.new_page().goto(url="https://www.malacards.org/")
    # 2. Headed
    with closing(p.chromium.launch(headless=False)) as browser, closing(
        browser.new_context(record_har_path="headed.har")
    ) as context:
        response_headed = context.new_page().goto(url="https://www.malacards.org/")
```

**Steps**

Compare the two HAR files, and we see the headed HAR's first request has the below headers, whereas the headless HAR's first request does not:

```json
            { "name": "sec-ch-ua", "value": "\"Chromium\";v=\"121\", \"Not A(Brand\";v=\"99\"" },
            { "name": "sec-ch-ua-mobile", "value": "?0" },
            { "name": "sec-ch-ua-platform", "value": "\"macOS\"" },
```

https://github.com/microsoft/playwright/issues/6900 linked https://bugs.chromium.org/p/chromium/issues/detail?id=1212793, which was closed recently. I would like to revive this issue with the desired resolution is `sec-ch-ua` showing up in headless mode. Thank you in advance!

Relates to https://github.com/microsoft/playwright/issues/6900

**Comment by yury-s** [comment]
This is similar to https://github.com/microsoft/playwright/issues/28989 and should be fixed by https://github.com/microsoft/playwright/pull/29159.
