### ISSUE TITLE
[BUG] page.waitForFunction with async callback passed even if callback return falsy

### ISSUE THREAD

**Issue by Mikiri1337** [microsoft/playwright#29132]
### System info
- Playwright Version: [v1.41.1]
- Operating System: [macOS 13.4]
- Browser: [All]

### Source code

```typescript
import { test } from '@playwright/test';

test('test async waitForFunction', async ({ page }) => {
  await page.waitForFunction(async () => false);
});
```

**Steps**
- Run the test

**Expected**

Test failed because of timeout exceeded (like with this code)
```typescript
test('test waitForFunction', async ({ page }) => {
  await page.waitForFunction(() => false);
});
```

**Actual**

Test passed

**Comment by yury-s** [comment]
The predicate is supposed to by sync by design. If you have an async condition you can use [`page.evaluate()`](https://playwright.dev/docs/api/class-page#page-evaluate) which will auto-wait for the returned promise to resolve.  Is there a real world use case where you need this?

**Comment by Mikiri1337** [comment]
Thanks for answer, @yury-s! I have following situation:
```typescript
await page.exposeFunction('somePredicateForDataLayer', somePredicateForDataLayer);
// i need to wait until somePredicateForDataLayer return true or fail because of timeout exceeded
await page.waitForFunction(async () => {
  return window.somePredicateForDataLayer(window.dataLayer);
});
```
I think page.evaluate() is not what i looking for because it will auto-wait only once not depending of truthiness of result.

**Comment by yury-s** [comment]
If the predicate is evaluated in Node.js then you may be better off with [expect.poll](https://playwright.dev/docs/test-assertions#expectpoll), would that work?

If not, you can always make eval wait for the condition to become true:

```js
    page.evaluate(async () => {
      const start = Date.now();
      while (Date.now() - start < 3_000) {
        if (await window.somePredicateForDataLayer(window.dataLayer))
          return true;
        await new Promise(resolve => setTimeout(resolve, 100));
      }
      return false;
    });
```
Would that work?

**Comment by Mikiri1337** [comment]
@yury-s, yes, it works. Thanks for help!
