### ISSUE TITLE
Faster (?) waitForElement function

### ISSUE THREAD

**Issue by mindplay-dk** [microsoft/playwright#29146]
This is just an idea/suggestion, not an issue or even a feature request.

*(you don't have an open Discussions tab, and the Discord doesn't have a chat either and appears to be for self help only...?)*

Just wanted to share something interesting:

https://gist.github.com/mindplay-dk/d2c25eb96fb707a4749e08666e8aea31

It's a "hack", using native CSS selectors to notify me when a selector matches - it should be near real-time, and (in the project where I used it) appears to add no noticeable overhead, which every other approach (MutationObserver etc.) definitely did.

I have no idea if this would work in a headless Playwright browser context or not - but presumably, the CSS engine and everything else is actually running, for the sake of testing (for example) CSS animation events, despite not rendering any pixels?

If so, this approach might speed up testing - it's difficult to say. I can't think of any practical way to benchmark something like this. Other than perhaps running a very large test suite with plenty of waiting and compare the before/after.

Just wanted to share, as this might could significantly speed up tests. If you don't care, feel free to just close this issue!

Cheers 🙂

**Comment by yury-s** [comment]
Thanks for sharing this. We usually recommend web assertions for scenarios like this. E.g. [toBeVisible](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-be-visible) will wait for given locator to become visible, we didn't receive feedback of it being slow, so I'm going to close this report for now but maybe one day we'll adopt your approach.
