### ISSUE TITLE
[BUG] White page when opening test steps in html report

### ISSUE THREAD

**Issue by lbarkan** [microsoft/playwright#29149]
### System info
- Playwright Version: [v1.41]
- Operating System: [macOS 14.2.1]
- Browser: [Chromium, Firefox, I guess all]
- Other info:

### Source code
[playwright-report.zip](https://github.com/microsoft/playwright/files/14038453/playwright-report.zip)

**Steps**
Open the attached report - it shows all tests as expected: 
<img width="1488" alt="image" src="https://github.com/microsoft/playwright/assets/22418231/5f065683-cb3c-42be-af3a-ccfb9db2c97d">

However, when you try to open the tests steps of any of those tests, you'll get a blank page.
<img width="1506" alt="image" src="https://github.com/microsoft/playwright/assets/22418231/2ba90295-6b25-41e7-8fa4-92621115ae54">

In console, there is error: 
`Uncaught (in promise) Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

**Comment by yury-s** [comment]
Can you share the tests that produce such report?

**Comment by yury-s** [comment]
Can you also try if it still happens on 1.41.1?

**Comment by pavelfeldman** [comment]
I think it'll happen  on 1.41.1 as well, let me look into it.

**Comment by pavelfeldman** [comment]
The issue is the following annotation you added to a test: 

```js
testInfo.annotations.push({"type":"Service versions","description":{}});
```

We only support string annotations, typescript should have reported it as an error.

**Comment by lbarkan** [comment]
thanks a lot for your quick help, I've changed to string and everything worked like a charm!
