### ISSUE TITLE
Locating a parent element

### ISSUE THREAD

**Issue by ruttiekaratie** [microsoft/playwright#29143]
I want a better way to traverse to a parent element. I'd rather not use XPaths.
Something like .locator('foo').parent() would be perfect.

**Comment by ltsuda** [comment]
You could do something with `.filter()` to find element (parent) with child element, instead of finding an element then finding its parent.


https://playwright.dev/docs/other-locators#parent-element-locator

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/23718, please upvote that issue.

**Comment by Hyzyr** [comment]
xpath locator works for it 

`paragraph.locator('..')`
