### ISSUE TITLE
[BUG]Codegen not working for some elements e.g. simple button or link clicks (.NET & MSTest)

### ISSUE THREAD

**Issue by Preacher856** [microsoft/playwright#29147]
### System info
- Playwright Version: Microsoft.Playwright.MSTest" Version="1.41.1" & Playwright Test for VSCode v1.0.21
- Operating System: Windows 11
- Browser: Chromium (MSEdge & Chrome)
- Other info: Visual Studio code v1.85.2

### Source code

```csharp
using System.Reflection.Metadata.Ecma335;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.Playwright;
using Microsoft.Playwright.MSTest;
using Microsoft.VisualStudio.TestTools.UnitTesting;
namespace PlaywrightTests;
[TestClass]
public class WeatherCheck : PageTest
{
    [TestInitialize]
    public async Task TestInitialize()
    {
         await Context.Tracing.StartAsync(new()
        {
            Title = TestContext.TestName,
            Screenshots = true,
            Snapshots = true,
            Sources = true
        });
    }
    [TestCleanup]
    public async Task TestCleanup()
    {
        // This will produce e.g.: bin/Debug/net8.0/playwright-traces/PlaywrightTests.UnitTest1.zip
        await Context.Tracing.StopAsync(new()
        {
            Path = Path.Combine(
                Environment.CurrentDirectory,
                "playwright-traces",
                $"{TestContext.FullyQualifiedTestClassName}.zip"
            )
        });
    }
    [TestMethod]
    public async Task BBCWeather()
    {
        await Page.GotoAsync("https://www.bbc.co.uk"); 
        await Expect(Page.GetByRole(AriaRole.Button, new() { Name = "Yes, I agree" })).ToBeVisibleAsync(); 
        await Page.GetByRole(AriaRole.Button, new() {Name = "Yes, I agree"}).ClickAsync(); //not produced by codegen

        await Page.GetByTestId("header-content").GetByRole(AriaRole.Link, new() { Name = "Weather" }).ClickAsync(); //not generated by codegen

        //await Page.GetByPlaceholder("Enter a town, city or UK").ClickAsync();
        await Page.GetByPlaceholder("Enter a town, city or UK").FillAsync("Norwich");
        await Page.GetByPlaceholder("Enter a town, city or UK").PressAsync("Enter");
        await Page.GetByRole(AriaRole.Link, new() {Name = "Norwich, Norfolk"}).ClickAsync();

        await Expect(Page.GetByTestId("location").GetByRole(AriaRole.Heading, new() {Name = "Norwich"})).ToBeVisibleAsync();
        await Page.GetByRole(AriaRole.Link, new() { Name = "Thurs" }).ClickAsync(); //not generated by codegen
    }
} 
```

**Steps**
- Launch codegen from terminal - pwsh bin/Debug/net8.0/playwright.ps1 codegen
- Navgiate to https://www.bbc.co.uk
- Click Yes, I agree to clear cookie notification
- Click Weather link

[Describe expected behavior]
Codegen to capture each step and generate appropriate code

**Actual**
Codegen fails to generate code for some elements.
Pick locator is able to identify all fields

[Describe actual behavior]
Some lines of code are generated correctly, some are not resulting in manual editing.
I experience the same behaviour when interacting with D365 CRM BPF stages, and Command Bar, however SiteMap and Entity related actions are generated correctly

In addition to this as it may be related;
_Show Trace Viewer_ does not appear to function from the VSCode GUI
_Record New_ does not appear to function from the VSCode GUI, therefore I am unable to launch the interactive gui code generator
![image](https://github.com/microsoft/playwright/assets/42450367/a5c470b7-c0d0-45d9-aaa6-7449a1a23517)

**Comment by yury-s** [comment]
This should be fixed in 1.41.2
