### ISSUE TITLE
[Feature] pass variables from Setup prolject to Test and Teardown projects

### ISSUE THREAD

**Issue by forelock7** [microsoft/playwright#29141]
Setup project creates some variable and then uses it in main test and then in teardown. I didn’t find any way except ENV variable to handle this. Does some functionality exist in playwright?

**Comment by yury-s** [comment]
Environment variables and file are the two recommended ways for passing data between interdependent projects.

Closing as there are no immediate plans to provide more extended support for this.

**Comment by NikkTod** [comment]
We can pass at runtime the value of the needed variable to an env. variable. ->   process.env.TOKEN = body.data.accessToken;
