### ISSUE TITLE
[BUG] Playwright Stack trace shows wrong line number for failure if importing certain packages

### ISSUE THREAD

**Issue by mastrzyz** [microsoft/playwright#29157]
### System info
- Playwright Version: 1.41
- Operating System: Windows 11
- Browser: All
- Other info: Node v16.20.2

#### example.spec.ts
```.ts
import { test } from "@playwright/test";



require("appium-windows-driver");













test("Basic Test", () => {
  throw new Error("Will fail");
});
```

#### Package.json
```.json
{
  "name": "playwright_sandbox",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {},
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@playwright/test": "^1.41.1",
    "appium-windows-driver": "1.19.1"
  }
}

````

**Steps**
- [Run the test]

**Expected**
I would expect line `8` to be the line we have a failure
![image](https://github.com/microsoft/playwright/assets/37447884/6c351e0e-786d-4c34-b0a7-915f7de92837)

**Actual**
Looks like the whitespace confuses playwright with the import? we have it on line `6`

Note this is a wacky repro but it's the smallest I could do that is portable, we don't actually have tests like this :)

![image](https://github.com/microsoft/playwright/assets/37447884/81a6c327-0a7b-4b5e-b1a5-8f81b164bfbe)

Commenting out the require shows "Expected" results again : 

![image](https://github.com/microsoft/playwright/assets/37447884/d99452e2-ab56-484c-813f-fab2b3d34c27)

Removing all new lines and we still have the weird line count issue : 

![image](https://github.com/microsoft/playwright/assets/37447884/22705fe8-d405-471b-b74f-18da522e8b06)

**Comment by yury-s** [comment]
Hmm, wasn't able to reproduce it on linux with node 18 or 16. This is the project that I used https://github.com/yury-s/bug-29157. Let me try on Windows too.

**Comment by mastrzyz** [comment]
I can't either, I wonder if its due to me making this repro as small as possible but Playwright still using the same compilation cache?

**Comment by yury-s** [comment]
There is a chance that something got stuck somewhere (node_modules?). Does it reproduce with the original project on a fresh checkout?

**Comment by mxschmitt** [comment]
I can repro.

The wrong `source-map-support` package gets picked up:

https://github.com/appium/appium-windows-driver/blob/53f9603cb8d8a54fc39a6dfcc5b7b239cd9f2afa/package.json#L64

They also internally do a lot of `require("source-map-support/register")`. It also depends on the `asyncbox` package, which does the same hence its not working.

**Comment by mxschmitt** [comment]
Workaround: Put `require('source-map-support').install = () => {}` into your `playwright.config.ts` in line 1.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by leszek86** [comment]
We had similar problem and resolved it by adding `"sourceMap": true` to tsconfig.json file. Npm install might be required afterwards.
