### ISSUE TITLE
[REGRESSION]: Spotify DRM Playback Fails after v1.27.1

### ISSUE THREAD

**Issue by Vinyzu** [microsoft/playwright#29151]
**Context:**
- GOOD Playwright Version: <1.27.1
- BAD Playwright Version: >1.27.1
- Operating System: Windows, All
- Browser: Chromium/Firefox
- Extra: Spotify Account Required

**Issue**
Since Playwright v1.28, a playwright browser cannot play spotify drm content.
The error are not dependent on a browserdriver or real chrome/chromium/firefox browser (both fail).
The Console gives this error-output (on chromium):
```
Uncaught (in promise) EMEError: No supported keysystem was found.
Uncaught (in promise) PlaybackError: No supported keysystem was found.
Uncaught (in promise) PlayerAPIClientError: No such device.
```

### Source code
Playwright >1.27.1 fails
```py
import asyncio

from playwright.async_api import async_playwright

async def run(playwright):
    chromium = playwright.chromium # or .firefox / Bothfail
    browser = await chromium.launch(headless=False)
    page = await browser.new_page()
    await page.goto("https://open.spotify.com/playlist/37i9dQZF1DX7QOv5kjbU68")

    # Login to Spotify Account and attempt to play

    await page.wait_for_timeout(1000000)
    await browser.close()

async def main():
    async with async_playwright() as playwright:
        await run(playwright)
asyncio.run(main())
```

**Comment by yury-s** [comment]
Playwright doesn't do anything specific for DRM support, so it's likely that something has changed in the browsers. You may have better luck with using vendor browsers like [Chrome or Edge](https://playwright.dev/docs/browsers#google-chrome--microsoft-edge) to have DRM support. It seems to be [an issue](https://stackoverflow.com/questions/67708146/spotify-web-sdk-error-emeerror-no-supported-keysystems-was-found) with recent chrome versions.

Closing this bug as there is no action item on Playwright end.

**Comment by Vinyzu** [comment]
As i described in the issue, ive also tested genuine vendor browsers.
Using Playwright v1.41.1 & Playwrights aproved Chrome (Beta) Version v121.0.6167.85: 
``doesnt work`.
Using Playwright v1.27.1& Playwrights aproved Chrome (Beta) Version v121.0.6167.85:
`does work.`

It is a issue in playwright, not in the browser.
Therefore it is a Playwright Regression. Please reopen @yury-s

**Comment by Vinyzu** [comment]
Doubled tested matching your explanation with Chrome v98.0.4695.0 from [Official Release Version](https://github.com/microsoft/playwright/releases/tag/v1.17.1)
(Downloaded Historic Version for Windows x64 from 98.0.4695.0)

Using Playwright v1.41.1 & Playwrights aproved Chromium Version v98.0.4695.0:
`doesnt work`.
Using Playwright v1.27.1& Playwrights aproved Chromium Version v98.0.4695.0:
`doesnt work`.

To be honest i cant explain this behaviour. 
Note that passing `--disable-component-update` into ignore_default_args as describe in [#22894](https://github.com/microsoft/playwright/issues/22894) didnt help with any version.

**Comment by Vinyzu** [comment]
Solved:
Using Real Chrome and passing `--disable-component-update`:
```py
    browser = await chromium.launch(headless=False,
                                    executable_path=r"...\chrome.exe",
                                    ignore_default_args=["--disable-component-update"])
```

Could swear i have tried this but now it works...

**Comment by DvaKompota** [comment]
For all future visitors, who are fortunate to find this ticket — for me just using 
```
    launchOptions: {
      channel: 'chrome',
    }
```
instead of `chromium` was enough to fix the issue.

@Vinyzu thank you, man — you saved my day!
