### ISSUE TITLE
[Feature] Docs improvement: Locator assertions return Promise

### ISSUE THREAD

**Issue by galaxyblur** [microsoft/playwright#29152]
Something that caused me some frustration is that I couldn't figure out why my locator assertions weren't respecting the default timeout. The error return was that the assertion timed out, but it would exit immediately. This was very misleading.

One key piece of this was learning that the locator assertions return a Promise, which is unlike generic assertions. This is not called out in the API docs, and you have to look closely at the code examples for the locator assertions to realize it. The return type for these assertions should be explicit, and it also perhaps deserves a separate callout in the guide.

Thanks.

**Comment by yury-s** [comment]
Checkout our tip of the day in the beginning of the [1.40 release video](https://playwright.dev/docs/release-notes#version-140), it explains how to lint your code to catch floating promises which would help in this case too. All our examples contain `await` before the assertions which puts enough stress on the fact that these APIs are async.

**Comment by galaxyblur** [comment]
Ok, but as a *_new_* Playwright user, the docs are the #1 source for my information. I wasn't aware of any release videos and wouldn't be looking there for API documentation.

I also don't look at code examples to determine the interface of an object. Examples are nice to clarify usage, but should not replace proper documentation of return values. So, no, the examples do not put enough stress on the async nature of these particular assertions (which differ from all other assertions).

I'm providing this feedback as a new Playwright user who was confused (and wasted quite a bit of time) because something was not sufficiently documented. If you're just going to tell me (the user) that I was _holding the device incorrectly_, I'm not going to bother reporting things anymore 🤷‍♂️

**Comment by ltsuda** [comment]
> Something that caused me some frustration is that I couldn't figure out why my locator assertions weren't respecting the default timeout. The error return was that the assertion timed out, but it would exit immediately. This was very misleading.
> 
> One key piece of this was learning that the locator assertions return a Promise, which is unlike generic assertions. This is not called out in the API docs, and you have to look closely at the code examples for the locator assertions to realize it. The return type for these assertions should be explicit, and it also perhaps deserves a separate callout in the guide.
> 
> Thanks.

From `One key piece of this was learning that the locator assertions return a Promise`, what link of the documentation are you referencing here? If you have a specific link and it's actually missing information, maybe they can improve. But mostly, the documentation is very detailed.

The following link mentions that Playwright includes web-specific matchers (assertions) and they are `async`.
https://playwright.dev/docs/test-assertions <br /> <br />

This section here says "retrying assertions are async, so you must `await` them"
https://playwright.dev/docs/test-assertions#auto-retrying-assertions <br /> <br />

The API for `LocatorAssertions` doesn't specifically says they are `async` but from the links above that shows the documentation for the assertions matchers itself and from the `await` we are able to tell that they are `async`. As `async/await` are Javascript features and not Playwright's.
https://playwright.dev/docs/api/class-locatorassertions  <br /> <br />

`The return type for these assertions should be explicit,`
And for this specific phrase above, like `await expect(page.locator('.status')).toHaveText('Submitted');` doesn't return anything, they do the assertion action.  <br /> <br />

As for `GenericAssertions`, they are not `async` as they are most if not all of them from Jest or Jest like code.
https://playwright.dev/docs/api/class-genericassertions

**Comment by galaxyblur** [comment]
@ltsuda thanks for at least asking what could be improved. @yury-s I apologize for coming off a little harsh, I was frustrated, as I'm sure all developers have experienced before.

I simply want to relay my experience as an end user of your product. It was very hard to figure out that these specific assertions return Promises, which is different than the other assertions. Yes, it is mentioned that they are "async" in the "test-assertions" document—however, **if I am having an issue with a function, I go to the API document for that function**. I believe that document should explicitly mention Promises as the return value, and not rely on the example code and the other document (that I didn't stumble upon) to communicate this.

So, this is the document that needs return types explicitly defined (in the same manner as arguments and options):
https://playwright.dev/docs/api/class-locatorassertions

**Comment by yury-s** [comment]
We discussed a few solutions to this in a team meeting but didn't like any of them. It feels like just adding Promise<void> to the end of the methods documentation will not help much. Ideally your IDE/linter should help catch such floating promises. Since this is a first report like this, I'm going to leave it open to see if there are more complaints about/ideas of how the difference between playwright's async web assertions and jest expect's sync ones could be better explained.

**Comment by galaxyblur** [comment]
Part of documenting an API is documenting the return value, even if it's obvious to some people. I've never encountered a formal API doc that didn't include return values—just like the name of the function and the parameters are documented—unless it was a mistake. The question is, why _wouldn't_ you document the return value? Does it get in the way?

Devs should not be relying on their IDE to be the source of truth for a 3rd party library.

>  It feels like just adding Promise to the end of the methods documentation will not help much.

And yet, that would've helped me exactly, which is why I opened this issue.
