### ISSUE TITLE
[Feature] CPU and Network throttling

### ISSUE THREAD

**Issue by siddharth2023** [microsoft/playwright#29155]
I saw [this](https://github.com/microsoft/playwright/issues/19883) and [this](https://github.com/microsoft/playwright/issues/8622) but they were a year old.

Is it possible to throttle network and cpu now?

Need this feature to test the stability of the app on low power mobile devices.

**Comment by yury-s** [comment]
There were no changes in this area recently. You can try use raw CDP as described in [this comment](https://github.com/microsoft/playwright/issues/6038#issuecomment-812521882). Folding this into 
 https://github.com/microsoft/playwright/issues/8622

**Comment by siddharth2023** [comment]
Wonderful. It works. Thank you!!

**Comment by nsacerdote** [comment]
```
    const context = page.context();
    const cdpSession = await context.newCDPSession(page);
    await cdpSession.send("Emulation.setCPUThrottlingRate", { rate: 12 });
```

Adding example of cpu throttling in case anyone finds it useful
