### ISSUE TITLE
[REGRESSION]: Unable to import module in file imported by playwright.config.ts

### ISSUE THREAD

**Issue by Naoto-Ida** [microsoft/playwright#29166]
**Context:**
- GOOD Playwright Version: 1.33.0
- BAD Playwright Version: 1.34.0
- Operating System: MacOS 12.5.1 
- Extra:

**Code Snippet**
```javascript
import { type FullProject, test as base } from '@playwright/test';
import CodeOwners from 'codeowners';
```

**Describe the bug**

Prior to `1.34.0`, we could import modules within files which are imported by `playwright.config.ts`.
With `1.34.0`, this seems to be no longer possible as we get the error below:

```
SyntaxError: Invalid or unexpected token

   at ../playwright-config/fixtures.ts:4

  2 |
  3 | import { type FullProject, test as base } from '@playwright/test';
> 4 | import CodeOwners from 'codeowners';
```

We use [codeowners](https://www.npmjs.com/package/codeowners) to append metadata to our tests to notify teams of test failures for which they're responsible for.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
