### ISSUE TITLE
[Feature]  Memory Overload Issue in Web Crawling Application with Playwright

### ISSUE THREAD

**Issue by wojtekKrol** [microsoft/playwright#29163]
Dear Development Team,

I am encountering a significant challenge with our web crawling application that utilizes Playwright. The core issue pertains to excessive memory consumption leading to system instability. 

The application's primary function is to perform web crawling in headless mode. It successfully processes a considerable number of websites (approximately 1000-1500) before encountering performance degradation. Post this threshold, the application experiences a drastic slowdown, ultimately culminating in a freeze. This has necessitated a complete system reboot, as the application becomes unresponsive.

Detailed Workflow:
1. Initiate the crawling process by opening a website in headless mode.
2. Execute the designated business logic and crawling operations.
3. Conclude each session by closing the website. I believe this also includes terminating the browser process, as the application uses Crawlee.
4. This process repeats for each website.

A critical observation is the memory usage reported by Playwright. Logs indicate that memory consumption reaches 400%, translating to roughly 800MB. This is a clear indication of resource overutilization, leading to the aforementioned issues.

The objective of this request is to explore potential strategies to optimize memory usage without restarting the entire application. Any insights or suggestions on memory management techniques, code optimizations, or best practices in this context would be immensely beneficial.

Thank you for your attention to this matter.

Best regards

**Comment by bba2022** [comment]
I also experienced a memory leak after running for more than 8 hours

**Comment by yury-s** [comment]
> I believe this also includes terminating the browser process, as the application uses Crawlee.

If you close the browser, Playwright will normally free up all resources associated with it. If not, please provide a repro where it's not happening and we'll have a look. Closing the browser and cleaning up local references to it should be sufficient to avoid memory leaks.

> A critical observation is the memory usage reported by Playwright. Logs indicate that memory consumption reaches 400%, translating to roughly 800MB. This is a clear indication of resource overutilization, leading to the aforementioned issues.

I assume you are talking about Node.js memory footprint. Try using [Node.js heap profiler](https://nodejs.org/en/guides/diagnostics/memory/using-heap-profiler) to see where the memory goes.

If you believe this is a Playwright bug, please provide a repro that we could run locally to reproduce the issue.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
