### ISSUE TITLE
[BUG] The `project` data doesn't seem to include `use` information when using a `merge-reports` workflow

### ISSUE THREAD

**Issue by devpow112** [microsoft/playwright#29174]
### System info

- Playwright Version: v1.41.1
- Operating System: All
- Browser: All

### Source code

Source code is available at https://github.com/devpow112/playwright-bugs.

**Steps**

 - Check out code
 - `npm i`
 - `npm run normal-project-use`
 - observe no issues and a bunch of logs of `'use' not empty object`
 - `npm run issue-project-use`
 - observe error is emitted due to `use` result being an empty object
   - `Error in reporter Error: 'use' is empty object`

**Expected**

This works without emitting any errors in both a normal execution and the `merge-reports` workflow.

**Actual**

Emits an error when using the `merge-reports` workflow due to the `project` data not including `use` information (always returns empty object).

### Notes

Related to #29173 as it's in the same reporters. My use case here is that I have a custom reporter that wants to know this information for tracking purposes. This seems to be simply that the [`TeleReporterEmitter` doesn't encode this information](https://github.com/microsoft/playwright/blob/main/packages/playwright/src/reporters/teleEmitter.ts#L163-L182) and the [`TeleReporterReceiver` doesn't parse it](https://github.com/microsoft/playwright/blob/main/packages/playwright/src/isomorphic/teleReceiver.ts#L351). This looks like it can be fixed by changing 2 lines to encode/decode this information.

`teleEmitter.ts`
```diff
    const report: JsonProject = {
      id: getProjectId(project),
      metadata: project.metadata,
      name: project.name,
      outputDir: this._relativePath(project.outputDir),
      repeatEach: project.repeatEach,
      retries: project.retries,
      testDir: this._relativePath(project.testDir),
      testIgnore: serializeRegexPatterns(project.testIgnore),
      testMatch: serializeRegexPatterns(project.testMatch),
      timeout: project.timeout,
      suites: suite.suites.map(fileSuite => {
        return this._serializeSuite(fileSuite);
      }),
      grep: serializeRegexPatterns(project.grep),
      grepInvert: serializeRegexPatterns(project.grepInvert || []),
      dependencies: project.dependencies,
      snapshotDir: this._relativePath(project.snapshotDir),
      teardown: project.teardown,
+     use: project.use || {}
    };
```

`teleReceiver.ts`
```diff
  private _parseProject(project: JsonProject): TeleFullProject {
    return {
      __projectId: project.id,
      metadata: project.metadata,
      name: project.name,
      outputDir: this._absolutePath(project.outputDir),
      repeatEach: project.repeatEach,
      retries: project.retries,
      testDir: this._absolutePath(project.testDir),
      testIgnore: parseRegexPatterns(project.testIgnore),
      testMatch: parseRegexPatterns(project.testMatch),
      timeout: project.timeout,
      grep: parseRegexPatterns(project.grep) as RegExp[],
      grepInvert: parseRegexPatterns(project.grepInvert) as RegExp[],
      dependencies: project.dependencies,
      teardown: project.teardown,
      snapshotDir: this._absolutePath(project.snapshotDir),
-     use: {},
+     use: project.use || {}
    };
  }
```

**Comment by yury-s** [comment]
We cannot serialize `project.use` as it may contain random fields including methods and instances of custom classes that we wouldn't be able to deserialize in the merger. As a workaround you can use [`project.metadata`](https://playwright.dev/docs/api/class-testproject#test-project-metadata) to pass some data to the reporter.

**Comment by devpow112** [comment]
> We cannot serialize project.use as it may contain random fields including methods and instances of custom classes that we wouldn't be able to deserialize in the merger

Are we not able to serialize the3 subset of data that isn't random? It looks like this is done for a number of id's? Just curious what data isn't serializable The `use` section looks like it's mainly supposed to be sourced from the `devices` array.

**Comment by devpow112** [comment]
It does look like that type ([`TestOptions`](https://playwright.dev/docs/api/class-testoptions)) is heftier than I originally thought. Are there any alternative way to get launcher options outside of sourcing it from the project.use data? I did a cursory look but didn't see any in the output from the blob reporter. I'm not against using the [project.metadata](https://playwright.dev/docs/api/class-testproject#test-project-metadata) it would just be nice to be able to source that daya from the execution information vs having to add it manually in needed places.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
