### ISSUE TITLE
playwright传递环境变量到selenium grid

### ISSUE THREAD

**Issue by sw-git555** [microsoft/playwright#29184]
SELENIUM_REMOTE_URL=http://<selenium-hub-ip>:4444 pytest --browser chromium

此命令是不是只支持linux
windows环境下的cmd窗口，如何支持

**Comment by mxschmitt** [comment]
We unfortunately can only triage issues if they are written in english and are following one of the issue templates. Feel free to re-file with more information, thank you for your understanding!
