### ISSUE TITLE
[Feature] Add readIntoBuffer() method to download class, 

### ISSUE THREAD

**Issue by Terence625** [microsoft/playwright#29186]
I want to attach download directly to `test.info` instead of saving to `path` then attach `path` to `test.info` as `test.info.attach` can attach Buffer. I saw there's a method `readIntoBuffer()` in `Artifact`, and `Download` have access to `Artifact` method like `createReadStream()`. 

https://github.com/microsoft/playwright/blob/38bc7a183556c797f2e3b7799a23f1e696b10068/packages/playwright-core/src/client/download.ts#L59-L61

Wonder if can put `readIntoBuffer()` method in `Download` like below:
```
async readIntoBuffer(): Promise<Buffer> {
    return await this._artifact.readIntoBuffer();
  }
```

**Comment by yury-s** [comment]
Given that reading Stream into a Buffer is pretty straightforward

```js
function readableToBuffer(readable) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    readable.on('data', chunk => chunks.push(chunk));
    readable.on('error', reject);
    readable.on('end', () => resolve(Buffer.concat(chunks)));
  });
}
```
we'd rather keep the API surface smaller.

Keeping this request open to see if there is enough interest in this feature.

**Comment by pavelfeldman** [comment]
I would not recommend embedding the blobs into the report unless you know they are tiny. Playwright is optimized to work with the attachment files since it allows for more efficient report retrieval and processing.

**Comment by Terence625** [comment]
Hi, @pavelfeldman , can I have a question here: do you mean saving the downloaded file to path then attach path to report is more efficient than reading downloaded file to stream then convert to Buffer then attach Buffer to report. I also want to optimize the work and try to understand more about how it works, thanks

**Comment by pirate** [comment]
Is there any equivalent to `download.readIntoBuffer()` in playwright-python?
