### ISSUE TITLE
[QUESTION] Run tests in debug mode in a devcontainer using VSCode extension

### ISSUE THREAD

**Issue by aoj2** [microsoft/playwright#29188]
Currently exploring using devcontainers for our tests,  unfortunately i'm facing an issue with debugging the tests inside the container using the PW VSCode extension, since it passes the "--headed" arg in the node command it fails with: `Looks like you launched a headed browser without having a XServer running. Set either 'headless: true' or use 'xvfb-run <your-playwright-app>' before running Playwright.`

I assume that the launch command in the extension is non-configurable (at least haven't found a way to do it), so can't remove the "headed" arg. I have tried to launch a XServer as part of starting the container, then run the tests but did not get Playwright to detect it...

So my question is basically, what would be your recommendation on how to get the VSCode extension debug to work in a devcontainer? 

Thanks in adance!

**Comment by yury-s** [comment]
> I assume that the launch command in the extension is non-configurable (at least haven't found a way to do it), so can't remove the "headed" arg.

Correct. It's not configurable as of today. Usually if one debugs a test they need to see what's going on in the browser, is not the case here?

> I have tried to launch a XServer as part of starting the container, then run the tests but did not get Playwright to detect it...

This should work, but you probably need to configure X forwarding to your local machine to see the browser or connect vith VNC.

**Comment by aoj2** [comment]
Nah, we just want to be able to put breakpoints at this stage! Got it working by launching the XServer when starting the container, which solves that use-case. Closing the issue!

**Comment by skylerbala** [comment]
@aoj2 Could you a bit more in detail how you launched XServer in the devcontainer to debug using the Test Explorer?
