### ISSUE TITLE
[BUG] Scripts that generate tests cannot run in playwright extension for VSCode

### ISSUE THREAD

**Issue by msftreigstad** [microsoft/playwright#29197]
### System info
- Playwright Version: 1.41.1
- Operating System: Windows 11
- Browser: Edge
- Other info:
The provided code contains a test that works with the extension and ones that don't.  An additional issue that arises from this setup is, when you run `npx playwright test --list` the console generates file locations that do not match the junit xml file locations that get created from the command.

### Source code
Small repo with reproduced error:
https://github.com/msftreigstad/playwright_test_builder_bug

**Steps**
Open the repo in VSCode with the Playwright VSCode extension.  Attempt to run one of the tests.

**Expected**
Test should run and pass

**Actual**
Receive an error:
Selected test is outside of the Default Profile (config). Please make sure you select relevant Playwright projects in the "Select Configuration…" drop down located next to Run / Debug Tests toolbar buttons.

**Comment by pavelfeldman** [comment]
Should be fixed on ToT
