### ISSUE TITLE
[REGRESSION]: client-provided arguments to electron is at the end of argv list

### ISSUE THREAD

**Issue by Maddobun** [microsoft/playwright#29198]
We used to have this PR #16782 which addresses this issue #16614.
It looks like this change was lost over the course of a few commits on the same file.

**Comment by yury-s** [comment]
This regressed in https://github.com/microsoft/playwright/pull/18804.

**Comment by yury-s** [comment]
@Maddobun what arguments do you see before yours? Looking at the code, it seems that most of the time it should be just your custom args but sometimes on linux --no-sanbox could appear first, is that what you observe?

**Comment by Maddobun** [comment]
> @Maddobun what arguments do you see before yours? Looking at the code, it seems that most of the time it should be just your custom args but sometimes on linux --no-sanbox could appear first, is that what you observe? Also which playwright version are you using?

I'm on 1.41.1 and in `process.argv` I'm seeing both `--inspect=0` and `--remote-debugging-port=0` between the executable path and my provided args.
