### ISSUE TITLE
[BUG]Playwright attempts auto login for InPrivate & InCognito browser sessions

### ISSUE THREAD

**Issue by Preacher856** [microsoft/playwright#29194]
### System info
Playwright Version: Microsoft.Playwright.MSTest" Version="1.41.1" & Playwright Test for VSCode v1.0.21
Operating System: Windows 11
Browser: Chromium (MSEdge & Chrome)
Other info: Visual Studio code v1.85.2

I'm not sure if this is a true bug, or whether I'm not able to find something in the solution configuration or missing a .runsettings line. The scenario here is to use a different user in which to execute the tests.

Simply running a test to navigate to Dynamics365 CRM URL, the browser attempts auto-login for the current user session, as opposed to be presented with the normal login workflow starting with input username.

This is for an OOB installation of PW, I have done nothing in terms of authentication configuration or code, however I expected the InPrivate browser session not to pick up my username and attempt login

```
await Page.GotoAsync("https://<companyidentifier>.crm11.dynamics.com/");
```

[Describe expected behavior]
To be presented with the standard Microsoft login workflow, starting with entering a username. 

I do not believe this is browser policy settings because if I manually launch an InPrivate session, and navigate to the same URL, it asks me to input my username

[Describe actual behavior]
The browser attempts auto login for the current user session, as opposed to be presented with the normal login workflow starting with input username.

I have checked this in Chrome and MSEdge, both operate in the same way

**Comment by yury-s** [comment]
> I have checked this in Chrome and MSEdge, both operate in the same way

This sounds like some policy setting. Does it also happen with bundled chromium binaries? Can you share the code of your test where this is happening? If you create a context via NewContextAsync it won't contain any data from the previous sessions, so you are either using a persistent context or something in your environment affects the login flow.

**Comment by Preacher856** [comment]
Thanks @yury-s 

A snippet from our ContextTest as follows;
```
[TestClass]
public class ContextTest : BrowserTest
{
    public IBrowserContext Context { get; private set; }

    [TestInitialize]
    public async Task ContextSetup()
    {
        Context = await NewContextAsync(ContextOptions()).ConfigureAwait(continueOnCapturedContext: false);
    }

    public virtual BrowserNewContextOptions ContextOptions()
    {
        return new BrowserNewContextOptions
        {
            Locale = "en-US",
            ColorScheme = ColorScheme.Light
        };
    }
}

```


The following is a snippet from a sample test we created, which triggers auto login when hitting the D365 URL, however if we navigate manually to the same URL inPrivate, it does not attempt auto login, so I do not believe this is policy.

```

using System.Reflection.Metadata.Ecma335;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.Playwright;
using Microsoft.Playwright.MSTest;
using Microsoft.VisualStudio.TestTools.UnitTesting;
namespace PlaywrightTests;
[TestClass]
public class D365_GridsWithViews : PageTest
{
    [TestInitialize]
    public async Task TestInitialize()
    {
         await Context.Tracing.StartAsync(new()
        {
            Title = TestContext.TestName,
            Screenshots = true,
            Snapshots = true,
            Sources = true
        });
    }
    [TestCleanup]
    public async Task TestCleanup()
    {
        // This will produce e.g.: bin/Debug/net8.0/playwright-traces/PlaywrightTests.UnitTest1.zip
        await Context.Tracing.StopAsync(new()
        {
            Path = Path.Combine(
                Environment.CurrentDirectory,
                "playwright-traces",
                $"{TestContext.FullyQualifiedTestClassName}.zip"
            )
        });
    }
    [TestMethod]
    public async Task D365_InteractGridsWithViews()
    {
        await Page.GotoAsync("https://<identifier_removed>.crm11.dynamics.com/");
        
```        


The installation method I used was per the PW .NET instructions with MSTest > https://playwright.dev/dotnet/docs/intro

thanks,

**Comment by yury-s** [comment]
> Does it also happen with bundled chromium binaries?

From what you describe, you launch manually Chrome/Edge with incognito tab but with existing user profile. Playwright, on the other hand, creates ephemeral contexts which are essentially contexts in fresh user profiles. This would explain the difference in the behavior. This is something that is affected by the policies/other settings on your machine, there is not much we can do about on the playwright end.

You can try passing `--auth-server-allowlist="*"` option as a workaround as described in https://github.com/microsoft/playwright/issues/15367.

Folding this issue into https://github.com/microsoft/playwright/issues/15367.
