### ISSUE TITLE
[Feature ]Make 'ExposeFunctionAsync' to be able to add functions inside existing object

### ISSUE THREAD

**Issue by alimtolman** [microsoft/playwright#29195]
Hey there.
Please make 'ExposeFunctionAsync' to be able to add functions inside existing object. Currently it adds only to window. But I would like it to be available in others objects too. For example I have an instance of some custom class, which have a callback field inside. If I want to set some native c# function to that callback field, I will not be able to.

**Comment by yury-s** [comment]
You can assign the the function to your object by evaluating corresponding javascript snippet:

```charp

        await page.ExposeFunctionAsync("myfunction", (string input) =>
        {
            return "Hello";
        });
        await page.EvaluateAsync("window.myobject.callback = window.myfunction;");
```
