### ISSUE TITLE
[Feature] Future plans for mobile automation?

### ISSUE THREAD

**Issue by deonxxx** [microsoft/playwright#29201]
Hello, im kinda curious if playwright team have a plans to reach out and create some sort of mobile automation framework?
Are there any plans to compete in mobile automation with such frameworks like Appium/Detox/Espresso? 

Thanks for your commitment to the community :)

**Comment by yury-s** [comment]
No current plans. Folding this request into https://github.com/microsoft/playwright/issues/1122
