### ISSUE TITLE
[Feature] - Enable Self-Sustaining Reports in Blobs

### ISSUE THREAD

**Issue by OSnuszka** [microsoft/playwright#29217]
**Problem**
Currently, our CI/CD pipeline generates reports at two levels – an overall report after blob merging and particle reports at the blob generation level. While this provides a quicker view of the reports, it results in larger artifacts. This is a big problem for me because in my CI/CD I have to save space for artifacts. To pass a file to the next stage I have to save it as an artifact - now I have blob/shard files and the report itself. Which takes 2x more space.

**Observation:**

I've noticed that the playwright report can be generated at the individual shard level, containing compressed files necessary for report generation. It would be beneficial to generate this report by default or allow it as an option during blob generation.

**Proposal:**

Adjust the default behavior to generate playwright reports at the shard level during blob generation.
Introduce a report parameter to enable/disable this feature based on user preferences.

**Comment by pavelfeldman** [comment]
What is the disk limit that you are hitting?

**Comment by OSnuszka** [comment]
Our CI/CD has a 500 mb limit on the size of artifacts.

We have several thousand tests any screenshots and trace files are limited.
