### ISSUE TITLE
[BUG] Component testing: vscode extension doesn't work ("Please install Playwright Test via running `npm i --save-dev @playwright/test`")

### ISSUE THREAD

**Issue by nag5000** [microsoft/playwright#29211]
### System info
- Playwright Test for VSCode: v1.0.21
- Playwright Version: v1.41
- Operating System: macOS

### Source code

package.json:
```
  "devDependencies": {
    "@playwright/experimental-ct-vue2": "^1.41.1",
```

**Expected**

Extension works, in Test Explorer I see my Playwright component tests

**Actual**

Extension shows the error "Please install Playwright Test via running `npm i --save-dev @playwright/test`", in Test Explorer I don't see my Playwright component tests.

**Details**

Installing `@playwright/test` helped, but this dependency is redundant (until I only use component testing); The extension should check for presence of `@playwright/experimental-*` packages as well.

https://github.com/microsoft/playwright-vscode/blob/c380e6f95dea75f33281bae3ae1bf2e82f88e61f/src/playwrightTest.ts#L67-L70

**Comment by mxschmitt** [comment]
Investigation notes: We should fallback to playwright/cli.js
