### ISSUE TITLE
[BUG] selectOption Bug

### ISSUE THREAD

**Issue by imstefan13** [microsoft/playwright#2921]
**Context:**
- Playwright Version: [@1.2.0]
- Operating System: [Mac]
- Node version: [12.14]
- Browser: [Chromium]

**Code Snippet**

`await page.selectOption('#ShipAddress_State', {label:this.info.state}`

**Describe the bug**

Hi. I am trying to use selectOption on a drop down choice. To interact with it manually, you click on the drop down which pops up a list of states to select and you select the state you want. When I attempt to run this code on it, it only selects a designated state 30 percent of a time. Playwright usually runs through the action quickly and does not select the state. Any ideas?

**Comment by pavelfeldman** [comment]
Hard to diagnose your problem without seeing the DOM!
