### ISSUE TITLE
[BUG] Plugins for `ctviteConfig` aren't used for ReactJS Playwright components tests

### ISSUE THREAD

**Issue by vhuseinova-msft** [microsoft/playwright#29225]
My team wants to start using ReactJS Playwright Components testing library. We use babel plugins for code processing and removing part of features that should be excluded from beta/stable releases. Because of this, tests needs to follow the same logic as we want to be able to test components that might not be included in other releases.
I was able to use babel plugins to `ctviteConfig` with React Playwright Components testing library. But the plugins are used only for the files that are tested, not for the test files (<name>.spec.tsx) themselves. So the tests files aren't processed by the plugins specified in `ctviteConfig` at all.

### System info
- Playwright Version: "@playwright/experimental-ct-react": "^1.41.1"
- Operating System: macOS 14.3
- Browser: All
- Other info:

### Source code
Please see [this repo](https://github.com/vhuseinova-msft/babel-plugin-playwright-components-demo) and README for it.

**Steps**
- Run the tests for a stable flavor as described in the README for [the repo](https://github.com/vhuseinova-msft/babel-plugin-playwright-components-demo)

**Expected**

The tests ts files can be processed by the same babel plugins as the code (as the output js files from ts ones should be processed in the same way as the project files).

**Actual**

The tests files are processed separately and don't use plugins specified in `ctviteConfig`.

**Comment by pavelfeldman** [comment]
> But the plugins are used only for the files that are tested, not for the test files (.spec.tsx) themselves.

That is working as intended, test files do not run in the browser, are not a subject to Vite bundling.

**Comment by vhuseinova-msft** [comment]
Hi @pavelfeldman! 
Is there a way how I can apply the babel plugin to the tests (as the tests files still needs to be processed and to be translated from TS to JS)?

**Comment by vhuseinova-msft** [comment]
` Playwright will take care of it under the hood. `
It is what I want to be able to configure in the similar way it's configured for bundling. Currently, TestComponent (in the demo app) differes for beta and stable builds which result in different bundle js files. 
Basically, for stable it looks like:
![image](https://github.com/microsoft/playwright/assets/98852890/9409866c-2aed-4e66-8b2b-a55409ea4007)
For beta, it looks like:
![image](https://github.com/microsoft/playwright/assets/98852890/51975c95-a9c1-4fca-9b92-f5ec0f82e335)
which results in the different UI. This is done by using the babel plugin I mentioned earlier. 
The Components tests library is able to create correct bundles during building (because I've added `ctviteConfig`). But I can't configure which tests should be skipped for the `stable` run because the code that is tested in some tests doesn't exist for the `stable` bundle (there is no`with beta features` text in `TestComponent` for the stable bundle file).
![image](https://github.com/microsoft/playwright/assets/98852890/eb98f3cd-4ca5-4927-97bb-c96973e61fe3)

Please check `TestComponent.spec.tsx` for more details.

**Comment by pavelfeldman** [comment]
You can either add a test parameter as described here: https://playwright.dev/docs/test-parameterize or use test tags as in here: https://playwright.dev/docs/test-annotations#tag-tests. That way you can have the tests that run only in prod, only in beta, or in both. With the fixture parameters you would be able to do conditional blocks in the tests so that you could test something only in beta, while the rest of that test would apply to both.

**Comment by vhuseinova-msft** [comment]
Thanks for fast responses and sharing the links! I'll check them out and reopen the issue in case I have more questions
