### ISSUE TITLE
[Feature] locator for getting an element's description

### ISSUE THREAD

**Issue by stchristian** [microsoft/playwright#29223]
I would like to reopen #18332 as this feature hasn't been added. 

There's an element that is described by an other element and I would like write a test in a way so the test remains user accessible. Kent gave the example of an input that is described by another element that potentially shows validation messages. I've had the same problem.

I am pasting his example here:
> Here's what I have to do now:
> ```
> const subjectDescriptionId = await page
>  .getByRole('textbox', {name: /subject/i})
>  .getAttribute('aria-describedby')
> await expect(page.locator(`id=${subjectDescriptionId}`)).toHaveText(/required/i)
>```
> Here's what I'd like to be able to do:
> ```
> const subjectDescription = await page
>   .getByRole('textbox', {name: /subject/i})
>   .getDescription()
>  await expect(subjectDescription).toHaveText(/required/i)`
>
>  const subjectDescription = await page
>   .getByRole('textbox', {name: /subject/i})
>   .getDescription()
>  await expect(subjectDescription).toHaveText(/required/i)
> ```

I see two solutions here:
1. `getDescription` locator that would query the element that has the description
2. A matcher similar to `jest-dom`'s `toHaveAccessibleDescription`.

**Comment by pavelfeldman** [comment]
Folding into reopened https://github.com/microsoft/playwright/issues/18332 for more context.

**Comment by stchristian** [comment]
@pavelfeldman 
I would be happy to implement this feature this week as I am a kind of a newbie in the realm of open source. It's just I wanted to make sure this is still relevant and get some feedback on the solutions I proposed. In addition, I welcome any advice or tips

**Comment by pavelfeldman** [comment]
Closing as folded
