### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by paigusov** [microsoft/playwright#29220]
### System info
- Playwright Version: [v1.4]
- Operating System: [Windows 10.]
- Browser: [Chromium]
- Other info:

### Source code
 I set different context sizes - on purpose, so that the page does not appear in full, but scrolls. I use the code and Fullpage = true, but the screenshot is **only of the visible part of the page**. How can I fix it?

```
from helpers.variables import LoginPageVariables as lpv
from helpers.pages.loginpage import LoginPage
import re
from playwright.sync_api import expect


def test_login(sigma_env, browser):
    browser, context, page = browser
    login_page = LoginPage(sigma_env.cloud, page)
    login_page.login(lpv.email, lpv.password)
    page.wait_for_timeout(5000)
    page.screenshot(path="screenshot.png", full_page=True)
    expect(page).to_have_url(re.compile("dashboard"))
```

**Comment by pavelfeldman** [comment]
Depending on the size of the page and the available resources / GPU, full page screenshots can be trimmed. If you believe this to not be the reason, please provide exact steps we could follow with the exact page your are taking the screenshot of.

**Comment by pavelfeldman** [comment]
Closing as non-actionable due to the lack of repro. Please open a new bug if you manage to create a repro we can use.
