### ISSUE TITLE
[Feature] beforeEach/fixtures, but executed even for skipped tests

### ISSUE THREAD

**Issue by throw5way** [microsoft/playwright#29229]
There is no way to execute code for every test, even those defined with `test.skip('', () => {})`.

This is required in order to customize reporting for skipped tests. For other tests it can be done using a fixture or with `beforeEach` hook, but skipped tests execute neither of those, and no customization, such as assigning labels in Allure dependent on test location, is possible.

**Comment by throw5way** [comment]
[Previous discussion](https://github.com/microsoft/playwright/issues/18372) asked to refile issue if persists. It does.

**Comment by pavelfeldman** [comment]
Depending on whether you want the test body (along with the fixtures and ability to add annotations) to run for the skipped tests, or not run for the skipped tests, you should use one of the strategies:

1) to run the test body, declare the test as test('foo', { ... }). Then call test.skip() inside the test, after you added the annotations.

2) to not run the test body, declare the test as test.skip()

Does this address your issue?

**Comment by throw5way** [comment]
Not at all, sorry.

The problem is exactly that we have to use `test.skip();` inside of the test, and that's not the first thing developer does. Everyone skips the test itself. Worse, it isn't even feasible to make a linter rule for it, because of `.extend`.

While I managed to partially and precariously handle it by proxying reporter and duplicating the label logic there, it doesn't solve the problem either, because, unlike fixtures, there is no way to annotate the singular test itself with extra data on how it should be reported.

What I'm asking is literally an ability to run some code on the test itself that is not affected by its `expectedStatus`.

An `{ always: true }` (similar to `{ scope: 'worker' }` or `{ auto: true }`) flag for a fixture would be the best option.

**Comment by pavelfeldman** [comment]
It sounds like I did not understand the issue then. Could you provide the exact snippet that I can run locally, along with your expectations and the description of the actual behavior that you are seeing?

**Comment by throw5way** [comment]
```
import { test as base } from '@playwright/test';
import { allure } from 'allure-playwright';

const modifyLabels = [
  async ({ }, use, testInfo) => {
    allure.layer('system');
    await use();
  },
  { auto: true },
]

const test = base.extend({
  modifyLabels,
});

test.skip('foo', () => {
  // this test isn't at system layer, because it's skipped
});

test('foo', () => {
  test.skip();
  // this test is at system layer, but developers don't write it this way
});
```

**Comment by throw5way** [comment]
@dgozman @pavelfeldman This issue might have been accidentally closed. Linked solution doesn't solve the problem.

If we were to use annotations instead of fixtures here, it'd take several extra lines of code _per every test in repository_.

I don't see how that might make the code any more readable compared to calling `test.skip();`.

**Comment by Thomas-Haider** [comment]
Hey @dgozman , @pavelfeldman , we would exactly have the same use case as described by @throw5way. We currently have all teams specify the test metadata like author, ticket, app, etc. in the test.use block, and then have an auto-test fixture to read those properties, verify them, and set them as annotations to pass to our custom reporters. 

Sadly, this does not work for skipped tests. As discussed above, the auto fixture body will not get executed, and therefore, we are missing all the metadata information for skipped tests, which is not really good. 

The perfect solution for us would be exactly what @throw5way described [here](https://github.com/microsoft/playwright/issues/29229#issuecomment-1921221023). So, to have a fixture option "always" that gets executed no matter the test resolution. Copy of the proposed solution:
```ts
const modifyLabels = [
  async ({ }, use, testInfo) => {
    allure.layer('system');
    await use();
  },
  { always: true },
]

test.skip('foo', () => {
  // fixture was executed, body of the test wasn't
}); 
```
