### ISSUE TITLE
[BUG] Unable to autotranslate page with Firefox

### ISSUE THREAD

**Issue by sandyboxy** [microsoft/playwright#29232]
### System info
- Playwright Version: v1.40.0
- Operating System: Ubuntu 20.04
- Browser: Firefox
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```python
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.firefox.launch_persistent_context(user_data_dir='./firefox_data', headless=False, slow_mo=50, firefox_user_prefs={"browser.translations.automaticallyPopup":True, "browser.translations.enable": True})
    page = browser.new_page()
    page.goto("https://playwright.dev/")
    browser.close()
```

**Steps**
- run the script above

**Expected**

I wish to enable Firefox auto-translate feature

**Actual**

- `page = browser.new_page()` open a new browser page (a total of 2);
- no translation is done.

Otherwise, is it possibile to use Chrome for this purpose?

**Comment by pavelfeldman** [comment]
Auto-translate is a native capability of the Firefox browser, it is not a part of the web platform and is hence outside of Playwright control and scope.
