### ISSUE TITLE
[Feature] Stacktrace in Debugger Mode

### ISSUE THREAD

**Issue by Jaguar20100** [microsoft/playwright#29236]
I have an easy function here as a reuseableComponent to click a button (Which i call in test scripts)

  async clickButton(name: string) {
    await this.getByRole('button', {name}).click();
  }

snippet of script:
await vorsorgemodellPage.clickButton('Abbbrechen'); (there is a typo in the button name to showcase)

With running the script with the debugger (playwright:debug) you just get a timeout without stack trace pointing to the reuseableComponent file and you don't get the Stacktrace with the action/step in the script where it actually fails unlike in headless mode  (playwright:test)

debugger mode:

![image](https://github.com/microsoft/playwright/assets/98572131/02509b66-8e0f-4dab-9b2b-1e106d3f2f14)

Headlless mode:

![image](https://github.com/microsoft/playwright/assets/98572131/597d0988-c04e-4cb0-b1e1-2d1a23a266c8)

can you please also add the stacktrace option in debug mode?
I think this is really helpfull for debugging and others for sure will benefit from this as well

**Comment by pavelfeldman** [comment]
You should 'box' your helper function as stated here: https://playwright.dev/docs/release-notes#hide-implementation-details-box-test-steps

**Comment by Jaguar20100** [comment]
Thank you fro the answer..i don't use this test.step() in my helper. You can see in the debugger mode there is only one source and it pounts to the helper file

![image](https://github.com/microsoft/playwright/assets/98572131/642e6339-bfdf-4b5d-b682-7296ae15520b)

unlike in headles mode ..there is two sources where as the second one points to the failed test step in the script where the error actually occures

![image](https://github.com/microsoft/playwright/assets/98572131/f542e1c0-b3f3-40fd-ae2a-2d9f01f67852)

![image](https://github.com/microsoft/playwright/assets/98572131/bb6942a3-aef6-4b08-8a95-c0099880a366)

**Comment by pavelfeldman** [comment]
Yes, so you should use `test.step` to achieve your goal of boxing.

**Comment by pavelfeldman** [comment]
Closing as per above

**Comment by Jaguar20100** [comment]
Ok thank you for the reply and the tipp :)
