### ISSUE TITLE
[Question] Can't get the login form for fantrax.com to submit

### ISSUE THREAD

**Issue by Brade** [microsoft/playwright#2924]
I'm currently trying to submit this form with playwright: https://www.fantrax.com/login
I'm able to fill the email and password fields, but the following line doesn't work:
```
await page.click('form button[type=submit]', {force: true});
```
With or without the "force: true" setting, the form does not submit.
I also put the following 2 lines after to debug:
```
await page.waitForTimeout(3000);
await page.screenshot({path: 'files/screenshot.png'});
```

The login form is still shown and no form submission has happened.
I even tried setting the "page.click" selector to the other 3 elements on the button, but nothing changes.

I think this site is built on Angular, and the forms are definitely weird.
Can anyone please assist? Can someone get the form to submit (regardless of whether the login is invalid or not)?
Thanks!

**Comment by aslushnikov** [comment]
@Brade indeed. The website is interesting: unless you accept the cookies prompt or scroll up-down, the button is not clickable. We unfortunately don't understand that: (+cc @dgozman)

I'd recommend clicking the `Dismiss` button in the very beginning of your automation. The following worked for me:
```js
const {chromium} = require('playwright');

(async () => {
  const browser = await chromium.launch({headless: false,});
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://www.fantrax.com/login');
  await page.click('text=Dismiss');
  await page.fill('[formcontrolname=email]', 'thisemailprobablydoesnotexist@gmail.com');
  await page.fill('[formcontrolname=password]', 'foobar');
  await page.click('button[type=submit]');
})();
```

**Comment by aslushnikov** [comment]
In fact, the `page.click` timeouts because it fails to click the button since it's overlayed with the cookies dialog. Works as expected!

**Comment by Brade** [comment]
Thanks, that worked! Weird because you don't need to dismiss that box when submitting the form IRL, but whatever!
