### ISSUE TITLE
[Feature] Support for SWC platform

### ISSUE THREAD

**Issue by 403-html** [microsoft/playwright#29254]
Hi, I'm asking, are there plans to add support for [SWC](https://swc.rs/)? SWC is renowned for its speed and efficiency, compiling code much faster than traditional compilers like Babel, and with better memory management. Integrating SWC into Playwright could dramatically reduce test setup times, leading to faster development cycles and improved productivity.

**Comment by pavelfeldman** [comment]
Transpiled tests are cached, so interactive flow has no penalty. On CI/CD first compilation will take a second, which is not comparable to the overall e2e test run. So the ROI for this migration is not convincing.
