### ISSUE TITLE
[Feature] Pass source test file information in playwright inspector

### ISSUE THREAD

**Issue by llamabytes** [microsoft/playwright#29257]
We use cloud dev environment to which we ssh. Now since devs would need to debug tests in a browser, I thought I could use the local machine to establish a ws connection with the remote machine and run tests in local machine.
my local machine script is
```// server.mjs
const { chromium } = ***@***.***/test');const
server = await chromium.launchServer({ headless: false
});console.log(server.wsEndpoint())
```
and i run it using 
```
PWDEBUG=1 node server.mjs
```
This open up the browser and inspector on my local machine while running test from remote machine. But the inspector doesn't show the source test file.
It says `No source file found` and doesn't show the content. Though I can click through the test

**Comment by pavelfeldman** [comment]
That's because the source file is on another machine, I don't think we are going to prioritize this narrow use case.

**Comment by llamabytes** [comment]
Is there a way to make it work and get the source file?

**Comment by pavelfeldman** [comment]
Inspector will attempt opening the file with that name on the host machine, so if the sources are there they will be picked up. It won't however be sending sources from one machine to another.

**Comment by llamabytes** [comment]
Does it look for the complete path? Is it way to hook into that path so
that I can have the file temporarily look present in local machine.

**Comment by pavelfeldman** [comment]
I don't think we support something like this.

**Comment by pavelfeldman** [comment]
Closing as per above
