### ISSUE TITLE
[BUG]Changing Project in VSCode it doesn't influence for tests visibility in Test Explorer

### ISSUE THREAD

**Issue by dawidkwiecien** [microsoft/playwright#29251]
**Context:**
- Playwright Version: 1.41.1
- Operating System: Windows 11
- Node.js version:20.8.0
- Visual Studio Code version: 1.85.2
- Playwright for VSCode extension version: 1.0.21
- Browser: All
- Extra: [any specific details about your environment]

**Code Snippet**

import { defineConfig, devices } from '@playwright/test';

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// require('dotenv').config();

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
  /* Run tests in files in parallel */
  fullyParallel: false,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: 1,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: [['./my-awesome-reporter.ts'],['blob'],['html']],
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://127.0.0.1:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
    browserName: 'chromium',
    channel:'chrome'
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'default'
    },
    {
      name: 'change',
      grep: /change_tc\d\d\d.spec.ts/,
      testDir: './tests/suites/change/',
    },
    {
      name: 'asset',
      grep: /asset_tc\d\d\d.spec.ts/,
      testDir: './tests/suites/asset/',
    },
    
  ],
});

**Describe the bug**

I've 3 projects setuped in playwright.config.ts.
While i was changed project in Test Explorer, the list of availible test in Test Explorer is not change even if in project i have grep and TestDir changed.

If i tried run from command line, reporter is informing me that i dont have tests --------->That correct behaviour
But if i try same from test explorer it didnt filter list of tests and present all tests.

**Comment by dawidkwiecien** [comment]
![Screenshot 2024-01-31 090027](https://github.com/microsoft/playwright/assets/2427085/84c1902e-0c41-48f5-a86a-2ee510041a9c)

![Screenshot 2024-01-31 085922](https://github.com/microsoft/playwright/assets/2427085/7bd5b06e-7751-485c-a14e-ed61f66c38e6)

![Screenshot 2024-01-31 085819](https://github.com/microsoft/playwright/assets/2427085/04b7e2b8-e893-4a4e-83ae-9c7532676cb6)

![Screenshot 2024-01-31 085819](https://github.com/microsoft/playwright/assets/2427085/64c59ada-3bfc-4dbd-b163-7ce90e943137)

**Comment by pavelfeldman** [comment]
Test explorer shows all the tests unconditionally, the project that you select is a "run" configuration. I.e. that's what runs when you press the Run button.

**Comment by dawidkwiecien** [comment]
Thanks Pavel for yours clarification.
Maybe it’s worth to add that feature ?
Or it’s intentional to show all tests?

**Comment by pavelfeldman** [comment]
That's how VS Code Test Explorer is designed. It asks providers for tests and for list of configurations. We aren't even supposed to know which configuration is currently selected. Think about profiles as "how you run tests" not "which tests you run". The mapping of this model to Playwright projects is not exact, but is more or less the best we could find.

**Comment by dawidkwiecien** [comment]
Thanks Pavel this fully clarifying my thoughts
