### ISSUE TITLE
[BUG]Codegen mode can not recode the slide action

### ISSUE THREAD

**Issue by heham** [microsoft/playwright#29252]
### System info
- Playwright Version: [v1.41.1]
- Operating System: [Windows 11]
- Browser: [ Firefox]
- Other info:
When i recode some actions ,the slide action can not be recoded(it recode a click),and the handler element very hard to slide ,maybe try 10 times then make it.

**Comment by pavelfeldman** [comment]
Are you talking about drag'n'drop or a range input element?

**Comment by heham** [comment]
> Are you talking about drag'n'drop or a range input element?
I think no.

Just this page,
https://tpass.hubei.chinatax.gov.cn:8443/#/login?redirect_uri=https%3A%2F%2Fetax.hubei.chinatax.gov.cn%2Fportal%2Flogin-web%2Fapi%2Fthird%2Fsso%2Flogin%2Fredirect&client_id=y852fe37d8e24d46ae8923fcd5yee6ac&response_type=code&state=test
and this page have another problem ,do not use playwright ,both firefox,edge and chromium can load it ,but if use playwright edge and chromium can not load it ,firefox can do it.

**Comment by pavelfeldman** [comment]
I'm not sure what "slide action" on that page you are referring to.

**Comment by heham** [comment]
> I'm not sure what "slide action" on that page you are referring to.

![1706839758148(1)](https://github.com/microsoft/playwright/assets/7487454/d11fa6e9-3036-4a70-bdea-547d41a6de01)
This one.

**Comment by pavelfeldman** [comment]
I can't see it when I open the URL. In either case, this feature does not seem to exist in Playwright. Please use the Feature template to file a request!
