### ISSUE TITLE
[BUG] Show `yarn` instead of `npx` in show-trace error message

### ISSUE THREAD

**Issue by guido-visser** [microsoft/playwright#29258]
### System info
- Playwright Version: [v1.41.1]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

**Steps**
- Run a test in a yarn environment

**Expected**

The log message on test fail should be: `yarn playwright show-trace "test-results\page-01 - appointments-Create-chromium\trace.zip"`

Maybe a solution would be that when a `yarn.lock` file is found, it shows `yarn` instead of `npx`.

**Actual**

It prints: `npx playwright show-trace "test-results\page-01 - appointments-Create-chromium\trace.zip"`

**Comment by pavelfeldman** [comment]
Looking at the lock file looks like too much hassle, also won't work without the lock file. If yarn allows detecting it explicitly, we can follow up with a fix. For now marking it as non-actionable.

**Comment by pavelfeldman** [comment]
Same here, that's why we can't act on the issue. Closing as non-actionable.
