### ISSUE TITLE
[Question] Trace report has a blue dot instead of a red dot for a click action

### ISSUE THREAD

**Issue by siddharth2023** [microsoft/playwright#29263]
<img width="216" alt="Screenshot 2024-01-31 at 10 39 29 AM" src="https://github.com/microsoft/playwright/assets/122398930/d8e32b0c-bdb5-4d0f-9f5a-3baf1cd7bcef">

In the trace report a click used to have a red dot. Now it is blue. Is there any setting to change this? Red was much easier to quickly spot the click area and blue is not as simple.

**Comment by dgozman** [comment]
@siddharth2023 Blue dot means that recorded click position in absolute coordinates does not match the center of the clicked element, likely due to a difference between the test runner and the trace viewer operating systems.

I'll update the UI to make this clear.

**Comment by siddharth2023** [comment]
Thank you. Btw, this was on macOS.
