### ISSUE TITLE
[Feature] Versioned Docker files with browsers

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#2926]
Docker files for Playwright should be versioned with Playwright versions and come with the browsers pre-installed. Rationale:

- Docker files are potentially updated every time Playwright is updated due to the browser dependencies
- It does not make sense to download browsers from within the library, because it only adds work for the users that have to deal with the environment variables and cache the browsers.
- We should also provide per-vendor images out of the box

@aslushnikov, wdyt?

Actions:
- [x] version docker images similarly to playwright releases
- [x] bake browsers into docker images
- [ ] release per-vendor docker images

**Comment by DJ-Glock** [comment]
Very good point.
At the moment we have to make our internal dockerfile for this.

Also it would be great to have a yarn installed as requested here:
https://github.com/microsoft/playwright/issues/3108

Putting our dockerfile here, probably it will save some time for anybody.
```
FROM mcr.microsoft.com/playwright:bionic

USER root

RUN  apt-get update \
   && apt-get install -y sudo \
   && usermod -aG sudo pwuser \
   && echo "pwuser ALL=(ALL) NOPASSWD: ALL" | tee -a /etc/sudoers \
   && apt-get install -y gnupg2 \
   && apt-get install -y wget --no-install-recommends \
   && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
   && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
   && apt update \
   && apt install yarn \
   && yarn add playwright-chromium@1.2.1
   
USER pwuser
```

**Comment by aslushnikov** [comment]
With v1.3.0, we'll publish `mcr.microsoft.com/playwright:v1.3.0` as well that will help browsers baked in.
We'll start publishing per-vendor browser images since next release.

**Comment by aslushnikov** [comment]
So far:
- we publish ubuntu-bionic (18.04) images
- starting with `v1.5` we will publish ubuntu-focal (20.04) images as well

The per-vendor docker images haven't been requested much. Closing this for now.
