### ISSUE TITLE
[BUG] --host only supported for show-report, not normal test

### ISSUE THREAD

**Issue by netmindz** [microsoft/playwright#29262]
### System info
- Playwright Version: [v1.41.1]
- Operating System: [All]
- Other info:

**Steps**
- try and run playwright test --host 0.0.0.0

**Expected**
report to be accessible on 0.0.0.0 

**Actual**
unknown option --host

This item https://github.com/microsoft/playwright/pull/18517 allows for --host and port to be used when show-report is called, but if you are just using playwright test, where it shows the report at the end automatically, you get unknown option for --host

**Comment by pavelfeldman** [comment]
You should configure it as

```
reporter: [['html', { host: '...' }]],
```

**Comment by pavelfeldman** [comment]
Closing as per above.

**Comment by netmindz** [comment]
You can configure as described, but why not allow the command like arguement to be passed to "test" as well as "show-report"
