### ISSUE TITLE
[Feature] call codegen from node.js

### ISSUE THREAD

**Issue by vid** [microsoft/playwright#29270]
I'd like to be able to do this: `const testCode = await codegen(startingPage, session, languageEncoder);`

This would make it easy for myself or other developers to tie it into different workflow or transformation.

Thanks!

**Comment by vid** [comment]
Related, I see there are a lot of requests for custom language encodings [eg](https://github.com/microsoft/playwright/blob/aff6cf3c83d5567ec2c662eebdc246090df39982/packages/playwright-core/src/server/recorder/javascript.ts), I would also like to have this ability so I can work directly with the intermediate representation.

**Comment by pavelfeldman** [comment]
This falls outside of scope for Playwright.
