### ISSUE TITLE
[BUG] Clicking on a button is not working when there is a hidden button with the same selector before it.

### ISSUE THREAD

**Issue by stijnvanderlaan** [microsoft/playwright#2927]
**Context:**
- Playwright Version: 1.2.0
- Operating System: Mac
- Node version: v12.6.0
- Browser: Chromium
- Extra: Jest

**Code Snippet**

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.click('text=Log in')
})();
```

**Describe the bug**
When there are 2 button on the page with text "Log in", but 1 is visible and the other is not, it waits for the first selected button to become visible instead of clicking the visible one.

**Comment by dgozman** [comment]
Thank you for the issue, @stijnvanderlaan.

This is working as expected - Playwright waits for the first button to become visible. If you would like to click the second button, please come up with a selector that points exactly to the button to click at. This will prevent flaky tests/scripts in the future. A common technique is to use some attribute, for example `<button data-testid='login'>` and click it with `page.click('data-testid=login')`.

See #2203 for a longer discussion and #2370 for a different proposal.

**Comment by stijnvanderlaan** [comment]
I encountered this issue 4 times in the last 2 days, in different situations, and your workaround is not that easy to implement because most of the time it's the same element, only one is hidden. Calling `click` will just not working even though there is a element on the page with the selector, very frustrating (and strange) behaviour if you ask me.

**Comment by arjun27** [comment]
Thanks for the feedback, @stijnvanderlaan. Is there any way to distinguish the elements? Perhaps you could localize the search for this button by [combining selectors](https://playwright.dev/#version=v1.2.0&path=docs%2Fselectors.md&q=): `page.click('nav >> text=Log in')`

It would be useful to know why `data-testid` wouldn't work in this case. Every app is different, and understanding your scenario will help us shape the API. Thanks!
