### ISSUE TITLE
[Feature] Webserver config for projects

### ISSUE THREAD

**Issue by AkimaLunar** [microsoft/playwright#29273]
A feature that allows the user to configure a webserver per project, like so:

```ts
import { defineConfig } from '@playwright/test';

export default defineConfig({
  timeout: 60000, // Timeout is shared between all tests.
  projects: [
    {
      name: 'app-e2e',
      testMatch: /.*.e2e.ts/,
      use: {
        baseURL: 'http://127.0.0.1:5173',
      },
      webServer: {
        command: 'npm run dev',
        url: 'http://127.0.0.1:5173',
        reuseExistingServer: !process.env.CI,
      },
    },
    {
      name: 'storybook',
      testMatch: /.*.spec.ts/,
      use: {
        baseURL: 'http://127.0.0.1:6006',
      },
      webServer: {
        command: 'npm run storybook',
        url: 'http://127.0.0.1:6006',
        reuseExistingServer: !process.env.CI,
      },
    },
  ],
});
```

In this case I have an app and I have a local Storybook for presentational components used in that app. I am trying to configure Playwright to have two different projects: one for the app itself and one for stories (visual regression). I couldn’t find any options to have different web server config for projects. I see you can run multiple servers, but ideally I only start the server that is right for the project (app server vs Storybook server).

_Does anyone have suggestions on how to set this up currently? Or do you think there is a better way to do this?_

**Comment by pavelfeldman** [comment]
Did you consider creating two config files? Your projects seem to share very little (if anything), so it looks like they could be two independent configs.

**Comment by AkimaLunar** [comment]
That would solve the issue 👍 Thanks!
