### ISSUE TITLE
[BUG] Possible Regression with locator.click()

### ISSUE THREAD

**Issue by LadaVarga** [microsoft/playwright#29276]
### System info
- Playwright Version: [v1.41.1]
- Operating System: [ Windows 11, ]
- Browser: [Chromium ]
- Other info:

### Source code
```typescript
 await itemMaterialCostCell.scrollIntoViewIfNeeded(); //it was added for sure, but the locator was always visible
 await itemMaterialCostCell.click(); // this one is executed but in real it doesn't clicked
  //await page.getByRole('cell', { name: '$' }).locator('div').first().click();
console.log('jmeno polozky: ' + itemMaterialCostCell);
await page.locator('role=textbox').fill('10');
await page.keyboard.press('Enter');
```

[Please provide a self-contained example in a form of a snippet, archive or a repository.]

[Repro scenario can't be large or have external dependencies.]

**Steps**
1. Have locator to non-standard element for clicking.
2. Try to click to that locator by locator.click()

**Investigation/Info**
- I am pretty sure it was working in some previous version of Playwright.
- I am implementing some function to parse pretty big table with clicking inside the table and filling the data to the table.
- I am almost 100% sure that clicks worked couple months ago, unfortunately I don't remember in which version of Playwright, it was definitely around beginning of the year. I was able to revert to 1.40.1 but looks same. Maybe there is problem with Chromium I don't really know.
- If I debug it once it clicked and once not.
- Can be problem with that tooltip? We did some refactoring for these columns, but as I said sometimes it clicks properly.
- We have some old tests in protractor and the Selenium Click works properly in similar locators.
- I saw around couple of "bugs" with similar problem, but in my case Playwright thinks that he clicked, because if I click manually during the test the fill works and sometimes it clicked properly.

**Expected**

Playwright should click. It looks like the cursor is up to the locator but it doesn't click at all. 

**Actual**
I was able to click to the locator, but only when another step occurs after click.
I was able to click in debug mode once from two columns.
![2024-01-31 23_58_21-bid-board-final spec ts - esticom-frontend - Visual Studio Code](https://github.com/microsoft/playwright/assets/22859476/3d9eb134-a383-42a1-adff-e2b0cba552c8)
![2024-02-01 00_01_32-Estimating - Chromium](https://github.com/microsoft/playwright/assets/22859476/5cbba40f-4e21-4673-a0f8-2e136031b89d)
![2024-01-31 23_48_12-Estimating - Chromium](https://github.com/microsoft/playwright/assets/22859476/b8d1c457-bc87-42c2-99c1-1e6d2c05a812)
![2024-01-31 23_46_16-Estimating - Chromium](https://github.com/microsoft/playwright/assets/22859476/41240da1-0a45-43cf-acc2-79a2baa08603)
![2024-01-31 23_44_23-Estimating - Chromium](https://github.com/microsoft/playwright/assets/22859476/8f0a26a6-bc10-4eaf-9f34-74d5742de011)

If necessary I am able to zoom/team to investigate the issue. I am UTC+1

**Comment by pavelfeldman** [comment]
We require self-contained minimal repro scenarios in a form of a snipped, archive or a repository for bugs so that we could reproduce them locally and fix.

**Comment by LadaVarga** [comment]
Do you have some email or secure storage where I can send the test.  I've already prepared something. Thanks

**Comment by pavelfeldman** [comment]
Repro should not contain sensitive information, so you should be able to attach it to this issue.

**Comment by LadaVarga** [comment]
Hello,
I hope you will be able to repro with these. If not I am able to give login/password to our staging by some secure channel.
There is test.
There is part of the page.
There is log from the test.
[console.log](https://github.com/microsoft/playwright/files/14128489/console.log)
[page.txt](https://github.com/microsoft/playwright/files/14128497/page.txt)
[playwright.spec.ts.txt](https://github.com/microsoft/playwright/files/14128528/playwright.spec.ts.txt)

**Comment by pavelfeldman** [comment]
This isn't something I can reproduce. I should be able to fetch a small repo (or a zip file) and run `npx playwright test` on it. Should have a handful of elements and a single click call in the test. That would make it a repro.

**Comment by pavelfeldman** [comment]
The thread is getting long and there is no actionable repro available. Closing as non-actionable.

**Comment by LadaVarga** [comment]
Hello,
Our application is pretty big and I don't know how to extract only that particular page to check that. I provided whole test which doesn't need anything more than our app. I tried to extract that page to single-page HTML but it misses some scripts and these elements are not clickable at all. Because of that I offered you to environment which can be used for that test. I can provide video if you want.

Never mind I was able to workaround that by adding `.hover()`/`click()` action before `click()`. Maybe `.click()` has problem with wait for tooltip (dis)appears and click on that tooltip instead of element. If you would like to investigate more deeply, please let me know I am always willing to help.
