### ISSUE TITLE
Setup fails and in turn fails Github action

### ISSUE THREAD

**Issue by OrrinGradwell** [microsoft/playwright#29285]
Action.yml:

`
name: CI

on:
  push:
    branches: [ "env_setup" ]
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
`
 
 Results in:
 
 `Run npm ci
npm ERR! code EUSAGE
npm ERR! 
npm ERR! The `npm ci` command can only install with an existing package-lock.json or
npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
npm ERR! later to generate a package-lock.json file, then try again.
npm ERR! 
npm ERR! Clean install a project
npm ERR! 
npm ERR! Usage:
npm ERR! npm ci
npm ERR! 
npm ERR! Options:
npm ERR! [--install-strategy <hoisted|nested|shallow|linked>] [--legacy-bundling]
npm ERR! [--global-style] [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
npm ERR! [--include <prod|dev|optional|peer> [--include <prod|dev|optional|peer> ...]]
npm ERR! [--strict-peer-deps] [--foreground-scripts] [--ignore-scripts] [--no-audit]
npm ERR! [--no-bin-links] [--no-fund] [--dry-run]
npm ERR! [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
npm ERR! [-ws|--workspaces] [--include-workspace-root] [--install-links]
npm ERR! 
npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
npm ERR! 
npm ERR! Run "npm help ci" for more info

npm ERR! A complete log of this run can be found in: /home/runner/.npm/_logs/202[4](https://github.com/OrrinGradwell/rf-automation/actions/runs/7737286720/job/21095996423#step:4:5)-02-01T0[6](https://github.com/OrrinGradwell/rf-automation/actions/runs/7737286720/job/21095996423#step:4:7)_3[8](https://github.com/OrrinGradwell/rf-automation/actions/runs/7737286720/job/21095996423#step:4:9)_21_6[9](https://github.com/OrrinGradwell/rf-automation/actions/runs/7737286720/job/21095996423#step:4:10)9Z-debug-0.log
Error: Process completed with exit code 1.`

The step in question is "Install dependencies"
`run: npm ci`

**Comment by pavelfeldman** [comment]
The error you're encountering during the "Install dependencies" step of your GitHub Actions workflow is related to the npm ci command, this has nothing to do with Playwright. This command is specifically designed for continuous integration systems and expects a package-lock.json file to be present in the repository. The error message indicates that such a file is either missing or not compatible. Please refer to the command documentation to address the issue.
