### ISSUE TITLE
[BUG] fixutre with worker scope will mess execution test executions in serial mode

### ISSUE THREAD

**Issue by Terence625** [microsoft/playwright#29282]
### System info
- Playwright Version: [v1.41.1]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

### Source code

```
// testFixture.ts

import test, { Page } from "@playwright/test";

export const scopedWorkerTests = test.extend<
  { scopedWorkerPage: Page },
  { scopedWorkerTest: string }
>({
  scopedWorkerTest: [
    async ({}, use) => {
      await use("test");
    },
    { scope: "worker" },
  ],
  scopedWorkerPage: async ({ page }, use) => {
    await use(page);
  },
});
```
```
// test.spec.ts

import test from "@playwright/test";
import { scopedWorkerTests } from "./testFixture";

test.describe("test serial test", () => {
  test.describe.configure({ mode: "serial" });
  test("test 1", async ({ page }) => {
    await page.goto("https://playwright.dev");
    throw new Error("Not implemented");
  });
  test("test 2", async ({ page }) => {
    await page.goto("https://playwright.dev");
  });
  scopedWorkerTests("test 3", async ({ scopedWorkerPage}) => {
    await scopedWorkerPage.goto("https://playwright.dev");
    throw new Error("Not implemented");
  });
});

```

**Steps**
- Run the group test in test.describe in serial mode

**Expected**

Test 1 failed, test 2 and test 3 should be skipped

**Actual**

![image](https://github.com/microsoft/playwright/assets/46805148/12384756-f435-4e6d-9f28-d7ccfbdecdb8)
Test 1 and Test 3 failled, Test 2 was skipped first then passed in the retry (I didn't set any retries)
And the html report shows blank in the first run and pass in retry for test 2
![image](https://github.com/microsoft/playwright/assets/46805148/7b8c1110-3f2b-4cbc-b30f-2688401db351)

Now make test 3 pass: 
```
// test.spec.ts

import test from "@playwright/test";
import { scopedWorkerTests } from "./testFixture";

test.describe("test serial test", () => {
  test.describe.configure({ mode: "serial" });
  test("test 1", async ({ page }) => {
    await page.goto("https://playwright.dev");
    throw new Error("Not implemented");
  });
  test("test 2", async ({ page }) => {
    await page.goto("https://playwright.dev");
  });
  scopedWorkerTests("test 3", async ({ scopedWorkerPage}) => {
    await scopedWorkerPage.goto("https://playwright.dev");
    throw new Error("Not implemented");
  });
});

```
**Expected**

Test 1 failed, test 2 and test 3 should be skipped

**Actual**
![image](https://github.com/microsoft/playwright/assets/46805148/ee40fd13-75c3-4dd6-94ec-9c097a6d2fee)
Test 1 failed, test 2 skipped, test 3 passed

This should have something to do with the fixture with the property with worker scope, although the property with worker scope is not used in the test. When I remove the property with worker scope, everything is back to normal.

**Comment by pavelfeldman** [comment]
You can't serialize tests from different families (different fixture sets).

**Comment by Terence625** [comment]
> You can't serialize tests from different families (different fixture sets).

@pavelfeldman thanks for responding. If this not allowed. I'm trying to test end to end of 2 applications: 1 app create a submission record and the other app receive the app, the two tests need to be run sequentially (I put page setup, baseUrl, storagestate in fixture to make the test easier to manage). What would you recommend, except using project dependency as one failure in app 1 tests will skip the whole tests for app 2, thanks

**Comment by pavelfeldman** [comment]
I would create a single test with multiple contexts: https://playwright.dev/docs/browser-contexts#multiple-contexts-in-a-single-test. I would not use the serial mode and would structure my test as a sequence of steps.

**Comment by Terence625** [comment]
> I would create a single test with multiple contexts: https://playwright.dev/docs/browser-contexts#multiple-contexts-in-a-single-test. I would not use the serial mode and would structure my test as a sequence of steps.

Thanks, I'll give it a try
