### ISSUE TITLE
[BUG] Custom expect message is not displayed in report when using async in fixture

### ISSUE THREAD

**Issue by michael-yelnikov** [microsoft/playwright#29289]
### System info
- Playwright Version:[ v1.41.1](https://github.com/microsoft/playwright/releases/tag/v1.41.1)
 

### Source code

```
import { test, expect } from "./test";

test("has title", async ({ page }) => {
  await page.goto("https://playwright.dev/");
  await expect(page, "Check titlte").toHaveTitle(/Playwright/);
});

```

test.ts: 
```
import { test as base } from "@playwright/test";

export const test = base.extend<{ allureFixture: void }>({
  allureFixture: [
    async ({}, use) => {
      await test.step("Allure fixture description", async () => {
        // ... 
        await use();
      });
    },
    { auto: true },
  ],
});
export { expect } from "@playwright/test";

```

**Steps to Reproduce**:

1. Create an asynchronous step within a fixture using test.step.
2. Define a test that includes a custom message in expect.
3. Execute the test with Allure reporting enabled.

**Expected Result**:
The custom message inside the test should be displayed in the report as an individual step.

**Actual Result**:
The custom message is not displayed in the report.

![image](https://github.com/microsoft/playwright/assets/16642847/8a380289-2c40-4fd8-af4d-057e3b2a70c0)

It was happened after: https://github.com/microsoft/playwright/issues/28528 

Why need to use asynchronous code in a fixture is a rhetorical question 😄

**Comment by ekaterinakuchmistova** [comment]
By the way, “goto” is not displayed also

**Comment by pavelfeldman** [comment]
They are all available under the Before Hooks.

Here is how fixtures work:
```js
  allureFixture: async ({}, use) => {
    // this code runs before test for setup
    await use(); // <-- test runs inside this call
    // this code runs after test for tear down
  }
```

and the report looks like this:
![image](https://github.com/microsoft/playwright/assets/883973/a556317d-0482-458d-83c0-1a742e17c09d)

You'll see two entries for the `allureFixture`, one is before the test and another is after.

When you wrap use() with a step:
```js
  allureFixture: [
    async ({}, use) => {
      await test.step("Allure fixture description", async () => {
        await use();
      });
    },
```

You give reporter an impossible task to show before and after separately, but at the same time to show them under the same step. Playwright falls back to attributing the entire step to where it was called and places it in its entirety to under before hooks.

You probably don't need the step as fixtures get automatic steps generated already as seen on the screenshot. But if you want a synthetic entry you can always do something like this:

```js
    async ({}, use) => {
      expect(true, 'Setting up allure').toBeTruthy();
      await use();
      expect(true, 'Tearing down allure').toBeTruthy();
    },
```

**Comment by pavelfeldman** [comment]
Closing as per above

**Comment by Sayan751** [comment]
I have a setup where I am using mocha as test runner to run the playwright tests (it is sort of an old setup). However, I am using playwright assertions. When I am using custom message with playwright `expect`, the message is not reported (I am using a mocha spec reporter) in the console. Can this be worked around in some way?

**Comment by Sayan751** [comment]
I think that the issue lies here in `ExpectMetaInfoProxyHandler#get`: https://github.com/microsoft/playwright/blob/7ce4f88a5bc9e315e56d103e7c3f05a0988445ef/packages/playwright/src/matchers/expect.ts#L338-L339

In my case, the `testInfo` is `null` and thus the custom message gets ignored.
