### ISSUE TITLE
[Feature] Reporting TestCases with TestSteps used in Test

### ISSUE THREAD

**Issue by dawidkwiecien** [microsoft/playwright#29286]
Hi,
Regarding to documentation there is CLI  option 'npx playwright test --list', and this print list of test cases titles thats fine.
But I'm looking to print as well with Test steps titles.

Currently class 'TestCase' dont have that kind of information or maybe i dont see this.

Could you add/tell me how to from TestCase get Steps title?

Thanks and regards.

**Comment by pavelfeldman** [comment]
You can only print steps if you are running the tests, you can't print steps in the --list mode. You can configure select reporters to print steps (html reporter will print steps by default).

**Comment by dawidkwiecien** [comment]
Sure Pavel got it, but i need feature to print test with steps without run.

**Comment by pavelfeldman** [comment]
Printing steps without running the tests is not feasible. Closing as won't fix.
