### ISSUE TITLE
[BUG] Playwright cannot work with NextJS server actions

### ISSUE THREAD

**Issue by JohnSmith0602** [microsoft/playwright#29288]
### System info
- Playwright Version: v1.41.1
- Operating System: macOS 14.3
- Browser: Chromium
- Other info:
- NextJS Version: v14.1.0

### Source code

The following logic is inside a client component, and it will call **getInfo**, which is a server action in a separate server actions file starting with 'use server'.
```js
// login.tsx
'use client'
function onClick() {
  console.log('get called in Playwright UI mode when the button is clicked');
  actions.getInfo();
  console.log('NOT executed here...')
}

// actions.ts
'use server'
export async function getInfo() {
  redirect('/another-page');
}
```

**Steps**
Click the button to trigger the onClick function.

**Expected**

The logic inside server action getInfo should be called(redirect to another page) in Playwright UI mode.

**Actual**

onClick function gets called, while getInfo is not in Playwright UI mode.

**Comment by JohnSmith0602** [comment]
UPDATE: since I'm not sure if server actions console log will be logged in playwright console, I just changed to return a value directly from getInfo, and log that value in onClick to see if getInfo is called. And it turns out the flow will hang on server action, the following console log inside onClick is not executed.

**Comment by pavelfeldman** [comment]
Playwright is an e2e testing framework, it will test everything that you can open in the browser as a user. Your expectations of how Next.js SSR works might be off, the code that runs on the server will run and log on the server. You can't "return value" statement is also confusing. Closing this as not a bug as we know that Playwright works with Next.JS. If you have a concrete example where Playwright refuses to test a page created with Next.js please file an issue with the complete self-contained repro that we can run locally.

**Comment by JohnSmith0602** [comment]
@pavelfeldman Thanks for your quick reply and good suggestion.

I've made a minimum demo: https://github.com/JohnSmith0602/playwright-with-server-actions-demo

I change the logic to see if server actions works by redirecting page in server actions. And it does get success for playwright tests!

However, I find another case wondering if it's a playwright bug or just I'm new to the tool.
For normal redirect, playwright UI will show the redirect page;
However, for redirect inside server actions, playwright UI will be blank, even if it can waitFor the url and get the right element.

![playwright-with-normal-redirect](https://github.com/microsoft/playwright/assets/2628052/e81b0e3d-b76b-4be9-899e-6fc8a4731186)
![playwright-with-server-actions-redirect](https://github.com/microsoft/playwright/assets/2628052/505d0295-c301-4932-921f-f0f33558ed0f)

**Comment by danielantelo** [comment]
> @pavelfeldman Thanks for your quick reply and good suggestion.
> 
> I've made a minimum demo: https://github.com/JohnSmith0602/playwright-with-server-actions-demo
> 
> I change the logic to see if server actions works by redirecting page in server actions. And it does get success for playwright tests!
> 
> However, I find another case wondering if it's a playwright bug or just I'm new to the tool. For normal redirect, playwright UI will show the redirect page; However, for redirect inside server actions, playwright UI will be blank, even if it can waitFor the url and get the right element.
> 
> ![playwright-with-normal-redirect](https://private-user-images.githubusercontent.com/2628052/301712812-e81b0e3d-b76b-4be9-899e-6fc8a4731186.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NjY4NTIsIm5iZiI6MTcxOTU2NjU1MiwicGF0aCI6Ii8yNjI4MDUyLzMwMTcxMjgxMi1lODFiMGUzZC1iNzZiLTRiZTktODk5ZS02ZmM4YTQ3MzExODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjhUMDkyMjMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTk3NWNjNDY0ZjAwNGU5ZmFlNmEwOWM5NTdiMDI2OGFiZmQ1ZmU3NWFhYTExZmQzZDJmYjMxYzgzOWRmMzJhOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cXG-pp9Cysiyy75bn-13rnNBvnDrgDigot_vtB46c6Q) ![playwright-with-server-actions-redirect](https://private-user-images.githubusercontent.com/2628052/301712825-505d0295-c301-4932-921f-f0f33558ed0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NjY4NTIsIm5iZiI6MTcxOTU2NjU1MiwicGF0aCI6Ii8yNjI4MDUyLzMwMTcxMjgyNS01MDVkMDI5NS1jMzAxLTQ5MzItOTIxZi1mMGYzMzU1OGVkMGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjhUMDkyMjMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjgwMzI0NjQyMzFiYmFmYzg0ZDkyZWE0YzliMjNhY2NmZTczYzZiMzMxN2ZhMTEwZjJkNDhhZGFkZTlhMTk2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LvJJ_yN5t4L9cVV9eUeRN98HQ6-H7mSR-AJzO3gchEk)

Having the same issue, did you find a solution?

**Comment by anthony-bernardo** [comment]
Why this issue is closed ? 

The bug is still present

**Comment by SamuelGarrattNZPost** [comment]
I noticed what looked similar to this and what fixed it for me was having assertions on my expect statements. When I did not have an 'await' on statement like

expect(element).toBeVisible()

then I saw that the trace viewer was not showing the HTML on the screen. Not sure if this affects this scenario but others might see this same behaviour if they do not use an 'await'
