### ISSUE TITLE
[Feature] Show Custom Annotations with colors (as similar to annotations marked with @annotation-name)

### ISSUE THREAD

**Issue by PramodKumarYadav** [microsoft/playwright#29298]
### Use case: 

Annotations are typically meta-data that is most useful when it is available to the user upfront  on the summary page, without having to go into details of each test. For example, if there are 50 tests and I have annotated 5 of them as "bug" with test changed to test.fail() all of them will show green as long as that bug is not fixed but if I can see the "bug" in colour on top of report, I can still see which ones are still not fixed. 

### Current behaviour:
Currently if a test is marked with @annotation-name it would show up on the report with a color (as shown below).
<img width="625" alt="Screenshot 2024-02-01 at 21 15 40" src="https://github.com/microsoft/playwright/assets/11694972/2adaece3-72f4-4223-880d-93dd19feb581">

However, if a test is marked with a custom annotation using " test.info().annotations.push" the annotation is not shown on the report summary and there is no color tag as the previous case.
<img width="408" alt="Screenshot 2024-02-01 at 21 18 06" src="https://github.com/microsoft/playwright/assets/11694972/5a08ae59-d37f-4cb6-9cf2-ca8da023b155">
but is hidden inside the test (as shown below)
<img width="381" alt="Screenshot 2024-02-01 at 21 18 29" src="https://github.com/microsoft/playwright/assets/11694972/7559b1d3-c4c2-4d62-8b38-07a7c7c12797">

### Desired behaviour  
Show custom annotation on the top summary page together with a unique colour code - as it is done for annotations marked with @annotation-name syntax. 

P.S: Since marking annotations with @annotation-name is error prone, I prefer the "test.info().annotations.push" method to set custom annotations that are then available to all tests in the project. However, these custom annotations does not show up on the summary page and are hidden behind tests which creates the compromise that I mentioned in this ticket. 
Idea is to see if we can get the benefit of both these cases in the project.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
