### ISSUE TITLE
[BUG] login.microsoftonline.com is pre-populating my account information from AAD joined device

### ISSUE THREAD

**Issue by dirthsj** [microsoft/playwright#29297]
### System info
- Playwright Version: 1.41.1
- Operating System: Windows 10 Enterprise
- Browser: 'Desktop Chrome'
- Other info:

The device is connected to an on-prem AD domain, and my AAD account is signed in. Chrome normally skips to MFA screen when not in incognito mode. Manually launching an incognito mode browser (via CLI `C:\..\ms-playwright\chromium-1097\chrome-win\chrome.exe --incognito`) does not skip the MFA screen.

### Source code

Code generated using playwrite CLI with no modifications except to navigate to my website.

**Steps**
- Run the generated sample code configured to navigate to a site protected by MSAL login (specifically using `MsalGuard` from `@azure/msal-angular` if it matters)

**Expected**

When my website redirects to `login.microsoftonline.com` I am presented with a blank username field, as it is when I manually launch a new Chromium incognito-mode instance

**Actual**

When my website redirects to `login.microsoftonline.com` the username and password steps are skipped, and it goes straight to MFA screen, as if it was not in incognito mode.

**Comment by pavelfeldman** [comment]
https://github.com/microsoft/playwright/issues/15367#issuecomment-1175615559 should help you.

**Comment by dirthsj** [comment]
> [#15367 (comment)](https://github.com/microsoft/playwright/issues/15367#issuecomment-1175615559) should help you.

I just tried this and it did not affect anything, unfortunately I still have the same issue.

**Comment by dirthsj** [comment]
Update: got it to work.

Note for future users: Put the launchOptions in the individual project configuration, not in the top-level `use` of the config. This will not work if you put it there.
