### ISSUE TITLE
[BUG] Error: t.parse: Host system is missing dependencies!

### ISSUE THREAD

**Issue by Srii-Mv** [microsoft/playwright#29295]
### System info
- Playwright Version: [v1.41.1]
- Operating System: Windows 11
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

Just sample example test

**Steps**
-Just run  "npx playwright codegen"

**Expected**

Should work as expected for above command
**Actual**

getting below error.

Error: t.parse: Host system is missing dependencies!

Full list of missing libraries:
    chrome_elf.dll

**Comment by pavelfeldman** [comment]
Works for me (and thousands of users). Please make sure you follow the installation steps here: https://playwright.dev/docs/intro

**Comment by Srii-Mv** [comment]
Hey i have been following the exact steps and could see those dependacies in the folder but am still getting error. any leads could be helpful to make it work this

**Comment by pavelfeldman** [comment]
We can't treat this as a bug report since there is no repro, for community questions you can try asking help at our Discord (https://aka.ms/playwright/discord).
