### ISSUE TITLE
[BUG] Not able to "grep" pick "custom annotated" tests from command line for running.

### ISSUE THREAD

**Issue by PramodKumarYadav** [microsoft/playwright#29300]
### System info
- Playwright Version: [Version 1.40.1]
- Operating System: [Tested on macOS 12.5 but I think it may exist for All OS'es ]
- Browser: [All]
- Other info:

### Source code

```
test('user profile', async ({ page }) => {
  test.info().annotations.push({
    type: 'bug',
    description: 'https://github.com/microsoft/playwright/issues/<some-issue>',
  });
  console.log("dummy test to test annotations");
});
```

**Steps**
- Run the test using either: `npx playwright test --grep @bug` OR `npx playwright test --grep bug` 

**Expected**
- Annotation should be picked up and test should run. 

**Actual**
In both cases, I get output as:
`Error: No tests found`

### Sidenote:
If I run the same test from IDE, we can clearly see that test is annotated.
<img width="821" alt="Screenshot 2024-02-01 at 22 11 09" src="https://github.com/microsoft/playwright/assets/11694972/d9135dd2-ccda-49db-b949-1162ada7bb4f">

**Comment by pavelfeldman** [comment]
--grep only works against the test title, annotations are not a test title and there is no way to filter tests by annotations. To collect annotations in tests, all tests should run, which defeats the purpose of filtering.

**Comment by PramodKumarYadav** [comment]
> --grep only works against the test title, annotations are not a test title and there is no way to filter tests by annotations. To collect annotations in tests, all tests should run, which defeats the purpose of filtering.

Thanks for the explanation @pavelfeldman . This explains the current behaviour. 

Just curious though; In junit5, we can create custom annotations that can be pointed to target tests against them. Could there be another solution using which something similar can be achieved in PlayWright? I am a bit new to PlayWright so still trying to figure what is possible or not possible here.
