### ISSUE TITLE
[BUG] Install instructions fail when using bun (create script uses npm instead of bun)

### ISSUE THREAD

**Issue by jsonMartin** [microsoft/playwright#29301]
I'm trying to set up Playwright in my NextJS 14 project (which is built using a bun monorepo). 

Unfortunately, the initial install step is failing when using `bun` because the install script tries to use `npm` package manager instead of `bun`. This is completely failing in a monorepo setup, because `npm` can't handle it. But even if the install step initially did work installiing via `npm`, then I'm assuming it still wouldn't correctly work with bun's lockfile as it's using a different package manager. 

### System info
- Playwright Version: [v1.41.2]
- Operating System: MacOS
- Browser: N/A
- Other info: N/A

### Source code
```bash
bun create playwright

Getting started with writing end-to-end tests with Playwright:
Initializing project in '.'
✔ Where to put your end-to-end tests? · tests
✔ Add a GitHub Actions workflow? (y/N) · false
✔ Install Playwright browsers (can be done manually via 'npx playwright install')? (Y/n) · true
Installing Playwright Test (npm install --save-dev @playwright/test)…
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:../../packages/backend-api
```

**Steps**
`bun create playwright`

**Expected**
Install script works and uses `bun` instead of `npm`

**Actual**
Install Script fails because it's using the wrong package manager

**Comment by pavelfeldman** [comment]
Bun is not supported by Playwright.

**Comment by jsonMartin** [comment]
Hey @pavelfeldman , from what I see it appears that the blocking issues preventing `bun` from working were closed as resolved 2 weeks ago: https://github.com/oven-sh/bun/issues/4751

I just did some more testing and was able to get this working with `bun` successfully. The hard part was just getting it installed: `yarn install` also failed for me because it didn't like the `bun` monorepo, but `pnpm install` worked to create the initial files - I just discarded the lockfile afterwards. 

Now calling via the `bun` cli, the sample tests work just fine for me:
```bash
bun run test:browser
$ playwright test

Running 6 tests using 6 workers
  6 passed (4.0s)

To open last HTML report run:

  npx playwright show-report
```
I don't really care if it's using `npx` or `bunx` under the hood to be honest, I just want to be able to do e2e testing inside of projects using the `bun` cli. 

Would you reconsider marking this as complete until there is a better solution? Even if `bun` has no plans to be officially supported, at least putting some documentation on the website would be helpful 🙏🏼
