### ISSUE TITLE
[Bug]: ScrollIntoViewIfNeededAsync() implementation for dotnet does unexpected actionability check breaking its operation

### ISSUE THREAD

**Issue by vkudley** [microsoft/playwright#29307]
### Version

1.41.2

### Steps to reproduce

Dotnet code, explicit use:
`await element.ScrollIntoViewIfNeededAsync();`

### Expected behavior

I expect an element to be scrolled into a view to become Visible after checking that it is Stable

### Actual behavior

    System.TimeoutException: Timeout 29999.977ms exceeded.
Call log:
  -   waiting for element to be stable
  -   element is stable
  -   element is not displayed, retrying in 0ms
  -   waiting for element to be stable
  -   element is stable
  -   element is not displayed, retrying in 50ms
...

### Additional context

According to https://playwright.dev/dotnet/docs/actionability this method should only check for Stable and ignore Visible, which makes sense for elements that need to be scrolled into view.
Somehow it makes unnecessary check for Visible and times out

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    Memory: 15.46 GB / 31.61 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Bash: 5.1.16 - C:\WINDOWS\system32\bash.EXE
```

**Comment by pavelfeldman** [comment]
Playwright allows scrolling element into view only if it has a layout object (display is not none). When element has display: none, browser does not know where to scroll to. We need to update our docs and require visibility on scrolling to avoid this ambiguity.

**Comment by vkudley** [comment]
Thanks for the prompt and actionable reply!
There is no explicit Displayed column in actionability table and I confused it with Visible.
Actual problem was with Locator pointing at the match in a wrong section of the DOM while I was looking at the "correct" one.
