### ISSUE TITLE
[REGRESSION]: Wrong enum value when imported from another file

### ISSUE THREAD

**Issue by ritz078** [microsoft/playwright#29302]
I am doing react component testing

**Context:**
- GOOD Playwright Version: 1.41.0
- BAD Playwright Version: 1.41.2
- Operating System: [e.g. Windows, Linux or Mac]: Mac
- Extra: [any specific details about your environment]

**Code Snippet**

```js
// CreateSignature.types.ts

 export enum ALLOWED_TABS {
  DRAW = "DRAW",
  TYPE = "TYPE",
  IMAGE = "IMAGE",
}
```

```js
// x.spec.tsx
import { ALLOWED_TABS } from "../CreateSignature.types";

console.log(ALLOWED_TABS);

// This gives
// {
//  __pw_type: 'importRef',
//  id: 'recipes_src_components_CreateSignature_CreateSignature_types_ts_ALLOWED_TABS'
// }
```

When we define `ALLOWED_TABS` in other file and import it,

**Comment by pavelfeldman** [comment]
> import { ALLOWED_TABS } from "../CreateSignature.types";

Playwright is struggling with non-standard file extension. It sounds like you are importing types information only, would it make sense to import types only?

```js
import type { ALLOWED_TABS } from "../CreateSignature.types";
```

**Comment by ritz078** [comment]
@pavelfeldman I am importing from `CreateSignature.types.ts`. I believe it is standard TS extension ?

> It sounds like you are importing types information only, would it make sense to import types only?

I am actually using the values in the file. So just importing the type won't help in this case.

**Comment by rahulkherajani** [comment]
@pavelfeldman I am facing similar issues importing constants and other components when running component tests in 1.41.2.

import {Component} from ./path;

// This gives
// {
//  __pw_type: 'importRef',
//  id: 'absolute_path_of_the_component'
// }

Could you provide an explaination for failure, if we need to change the way we import components. Thanks
