### ISSUE TITLE
[Feature]: Dedicated workers per project

### ISSUE THREAD

**Issue by VaasRamsay** [microsoft/playwright#29317]
### 🚀 Feature Request

Workers can be configured per project and they are dedicated to tests only for that project. 

### Motivation

This will complement the use of worker-scoped usecases (like worker fixtures) if you know deterministically the set of tests that will be run on those workers. 

### Pitch

This needs to setup as part of the TestProject config, hence it makes sense to be part of the Playwright core.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/21970
