### ISSUE TITLE
[Feature]: Like the browser's console in debug mode.

### ISSUE THREAD

**Issue by heham** [microsoft/playwright#29313]
### 🚀 Feature Request

Like the browser's console in debug mode,i can input or modify something  to debug setp bu step.Now in debug mode just look,sometimes it jammed i can do nothing to fix it.

### Motivation

Like the browser's console in debug mode,i can input or modify something  to debug setp bu step.Now in debug mode just look,sometimes it jammed i can do nothing to fix it.

### Pitch

Like the browser's console in debug mode,i can input or modify something  to debug setp bu step.Now in debug mode just look,sometimes it jammed i can do nothing to fix it.

**Comment by pavelfeldman** [comment]
Please follow the feature template to answer the required questions.
