### ISSUE TITLE
[Feature]: Expose action types recorded by Playwright

### ISSUE THREAD

**Issue by macalinao** [microsoft/playwright#29324]
### 🚀 Feature Request

Expose the actions recorded via JSONL as a separate package.

### Motivation

The types here are useful:

https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/recorder/recorderActions.ts

The following code generator will generate them:

https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/recorder/jsonl.ts

It would be useful to be able to import these actions in a different library.

### Pitch

Code sharing

**Comment by pavelfeldman** [comment]
It is unclear why end users will benefit from this, what the scenarios are where this functionality is used and why it can't be implemented by the third party modules.
