### ISSUE TITLE
[BUG]Playwright Test for VS Code, Record new function can not set browser and viewport-size

### ISSUE THREAD

**Issue by zhao50632** [microsoft/playwright#29346]
As shown in the title, when using Playwright Test for VS Code, I wanted to use another browser (such as msedge) for recording when using the Record new feature, but I couldn't find a place to set it up. The default resolution is too small. I wanted to increase it, but I couldn't find a place to set it.
I tried to add settings in the settings. json file of VS Code, but it didn't work.
The following is what I have set up:
"playwright.env": {
        "browser":"Desktop Edge",
        "channel":"msedge",
        "viewport-size":{
            "width": 1920, 
            "height": 1040
        }
    }
Looking forward to your reply, thank you in advance.

**Comment by zhao50632** [comment]
If I use the command line to start it, it works fine. npx playwright codegen --channel=msedge --viewport-size=1920,1040

**Comment by dgozman** [comment]
@zhao50632 Please file a new issue by following the "Bug Report" template.

**Comment by mxschmitt** [comment]
See also my response in https://github.com/microsoft/playwright-vscode/issues/410#issuecomment-1926588042.

**Comment by michaelwowro** [comment]
@mxschmitt Would love to see your response, because I have the exact same issue. Where has the Issue tab gone in playwright-vscode repo?

**Comment by mxschmitt** [comment]
We prefer to keep triaging issues in this repository, hence we disabled issues in the `playwright-vscode` repository. I aligned it how we do it in create-playwright (keep issues enabled and disable issue creation).
