### ISSUE TITLE
[Feature]: reduce docker image size

### ISSUE THREAD

**Issue by iridescentGray** [microsoft/playwright#29356]
### 🚀 Feature Request

For now docker image contain three browser,  The total size of the image is approximately 2GB.
I only use Chromium.
Is there a plan to provide an image that only includes Chromium to reduce image size.

### Example

docker pull smallest image

### Motivation

reduce docker image size

**Comment by dgozman** [comment]
@iridescentGray You can always build a docker image with just the browser you need, please follow [this section in the docs](https://playwright.dev/docs/docker#build-the-image). Let me know whether that works for you.

**Comment by iridescentGray** [comment]
it's worked.
Node.js Docker Integrations is The most complete
Other language documents like ‘python' ,'java','.Net'  are missing  about this.
I read python doc,  it's make  me Issues .

Fortunately, I found that the documentation will be supplemented in a subsequent version.
https://github.com/microsoft/playwright/pull/28994

That's all. Thank you.

**Comment by iridescentGray** [comment]
maybe be  'java' '.Net'  doc can also complete this .😄

**Comment by iridescentGray** [comment]
I don't have any other questions, I think this issue can be closed.
