### ISSUE TITLE
In monorepos, the "Please install Playwright Test" warning appears even though it's already installed

### ISSUE THREAD

**Issue by oscarhermoso** [microsoft/playwright#29358]
## Steps to reproduce

With `ms-playwright.playwright` extension version  "v1.0.21", create a pnpm monorepo with the following layout:

```sh
/package.json         # does not mention "@playwright/test"
/pnpm-lock.yaml       # Lists all workspace dependencies, including "@playwright/test": "^1.39.0"
/sites/frontend/package.json  # "@playwright/test": "^1.39.0" installed here in "devDependencies"
/sites/frontend/node_modules/@playwright/test/... # install path
```

## Expected

No warning to be displayed

## Actual

Warning displayed

![Screenshot from 2024-02-05 11-26-24](https://github.com/microsoft/playwright-vscode/assets/23239955/cead5b3a-ed3e-4697-9d9c-8e0659a4fd56)

(Possibly fixed by https://github.com/microsoft/playwright-vscode/pull/407, which doesn't appear to be released yet?)

**Comment by mxschmitt** [comment]
Re:

> (Possibly fixed by https://github.com/microsoft/playwright-vscode/pull/407, which doesn't appear to be released yet?)

We just released a new version which includes this fix. Does it still not work for you?

**Comment by oscarhermoso** [comment]
Not using PNP and no `pnp.cjs`

Would be happy to provide a full repro rep, but I am no longer seeing issue on `v1.0.22` :slightly_smiling_face: 

Closing as resolved
