### ISSUE TITLE
[Bug]: Pressing F5 doesn't reload the page on the browser

### ISSUE THREAD

**Issue by autTestUser** [microsoft/playwright#29362]
### Version

1.40.1

### Steps to reproduce

await page.keyboard.press('F5');

### Expected behavior

Browser page should reload

### Actual behavior

Browser page doesn't reload. I tried on chrome, firefox, edge

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1265U
    Memory: 12.43 GB / 31.44 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.84.2 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.2.15 - C:\Program Files\Git\usr\bin\bash.EXE
  npmPackages:
    @playwright/test: latest => 1.40.1
```

**Comment by dgozman** [comment]
@autTestUser Playwright controls the web page, but not the browser UI shortcuts like F5. You can use `page.reload()` to reload the page.
