### ISSUE TITLE
[Bug]: Playwright UI window rendering glitch

### ISSUE THREAD

**Issue by sjmc11** [microsoft/playwright#29363]
### Version

1.39.0 & 1.41.2

### Steps to reproduce

Launching playwright UI on windows 10 results in a window with glitchy and unusable appearance. Tried maximising, minimising, moving window to different monitor & relaunching.

![image](https://github.com/microsoft/playwright/assets/16296680/000d8ced-1760-42c1-ab27-8c9baa10f59e)

`npx playwright test --ui`

### Expected behavior

Window should be render properly

### Actual behavior

Window loads a glitched layout

### Additional context

When clicking and dragging the window around the screen it displays properly, but when released it goes back to the glitched appearance.

Works fine on some other windows machines and my mac os.

### Environment

```shell
Windows 10
```

**Comment by dgozman** [comment]
@sjmc11 This does not look like a Playwright failure, but rather something's wrong with your setup. I don't think we can help you with that, sorry.

**Comment by aadilaltaf** [comment]
I am also facing the same issue

**Comment by vivekrpatel8** [comment]
I am also facing same issue with Win 11. I was running test from my WSL and it opens browser window which was rendering oddly...

**Comment by KyGuy2002** [comment]
Seeing the same thing here on windows 11 with WSL.

Restarting the computer fixed it for me.
