### ISSUE TITLE
[Docs]: Assertions - custom "error" message

### ISSUE THREAD

**Issue by mstepin** [microsoft/playwright#29378]
### Page(s)

https://playwright.dev/docs/test-assertions#custom-expect-message

### Description

Perhaps this is actually a bug in the HTML reporter as opposed to a gap in the documentation, however I'll start with it being a doco issue first and we can convert to bug if required.

Playwrights expect assertion provide a 2nd argument `messageOrOptions` to which the user can supply a "custom error message" according to the documentation.

My understanding of what an "error message" is, would be that it is some text displayed if it errors or fails. Indeed if it does actually fail you WILL see the custom error message in the terminal output. And no terminal output if it passes.

The HTML report, on the other hand, behaves slightly differently.

So to provide an example one might be:
```
const responseCode = 200;
expect(responseCode, "Incorrect response code").toBe(200);
```

I would interpret that as: if the assertion fails, spit out error text, otherwise do not.

In the HTML report, if you do an assertion as per above, and the assertion does **not** fail, the report will have:

> ✅  Incorrect response code ../file/located/here.ts

This reads rather strangely for something that has passed. So in essence it is not a custom "error" message.

So is the documentation wrong here and should be updated to just be "custom message" (omitting "error") , or, is this indeed a bug in the HTML report which should actually not show the error message?

**Comment by dgozman** [comment]
@mstepin Thank you for the issue! Custom message is indeed just a message, not an error message. The docs are incorrect calling it an error message. You should phrase it to provide more context for the expect, for example `user name should be visible` or `should suggest to buy the same item again`. I'll update the docs to make this clear.

**Comment by mstepin** [comment]
Thank you for your prompt response @dgozman . I will update our code accordingly.
