### ISSUE TITLE
[Docs / Question]: Waiting for Angular

### ISSUE THREAD

**Issue by bshostak** [microsoft/playwright#29389]
### Page(s)

https://playwright.dev/docs/protractor#polyfilling-waitforangular

### Description

I referenced the attached documentation in regards to an issue I am seeing in Angular where the 'load' and 'domcontentloaded' events are fired but there are still elements on the page that are not visible because of microtasks not being completed. This causes playwright to fail the click actions. 
To get around this I normally use the waitForLoadState('networkidle'), however the documentation mentions it is discouraged and can be flaky since network calls happen frequently with reporting calls to gtm, etc. I've even tried waiting for the locators to be visible, enabled, etc.
Using the polyfill waitForAngular I can get the test to work but the function takes 8 seconds to evaluate. At that time the buttons are loaded in so I cannot verify that the script worked or it just finished and the buttons are there now so the test can click it.

Wondering if anyone has seen other similar behavior and how they handled it? I know https://angular.io/api/core/NgZone#onStable would be nice to evaluate but it doesn't look like we can do that either.

**Comment by dgozman** [comment]
@bshostak This does not look a documentation issue, but rather a question. If you have a specific documentation improvement in mind, please explain what exactly you would like to see changed.

The issue tracker is reserved for bug reports and feature requests. For anything else, such as questions or getting help, please see:
- [The Playwright documentation](https://playwright.dev/)
- [Our Discord server](https://aka.ms/playwright/discord)
