### ISSUE TITLE
[Bug]: WebKit encountered an internal error

### ISSUE THREAD

**Issue by pcace** [microsoft/playwright#29381]
### Version

1.41.2

### Steps to reproduce

1. install playwrite by ```yarn create playwright``` on Linux PopOS 22.04 LTS
2. test the example test: ```playwright test```
3. 
![image](https://github.com/microsoft/playwright/assets/1011875/ad7c8678-c4a4-45e2-a901-710230370eb5)

### Expected behavior

Expected: successfull tests like in the documentation

### Actual behavior

webkit fails with: 

```Error: page.goto: WebKit encountered an internal error
Call log:
  - navigating to "https://playwright.dev/", waiting until "load"


  2 |
  3 | test('has title', async ({ page }) => {
> 4 |   await page.goto('https://playwright.dev/');
    |              ^
  5 |
  6 |   // Expect a title "to contain" a substring.
  7 |   await expect(page).toHaveTitle(/Playwright/);

    at /home/johannes/git/RW_NEW/frontendTests/example.spec.ts:4:14
``` 

### Environment

```shell
System:
    OS: Linux 6.6 Pop!_OS 22.04 LTS
    Memory: 39.43 GB / 62.53 GB
    Container: Yes
  Binaries:
    Node: 18.17.1 - /usr/bin/node
    Yarn: 3.2.3 - /usr/bin/yarn
    npm: 10.3.0 - /usr/bin/npm
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
```

**Comment by dgozman** [comment]
@pcace There is probably something wrong on your system. Note that `Pop!_OS` is [not officially supported](https://playwright.dev/docs/intro#system-requirements). Given such a short description without a full error message, I cannot even speculate what did go wrong.

I'd recommend to troubleshoot yourself: try to run the browser manually, gather `DEBUG=pw:browser` logs, search for similar errors or [ask the community](https://playwright.dev/community/welcome). Unfortunately, we cannot troubleshoot for you, so closing the issue.
