### ISSUE TITLE
[Bug]: Cannot open ui or run tests with chromium - Error: browserType.launch: Target page, context or browser has been closed

### ISSUE THREAD

**Issue by jtibbit** [microsoft/playwright#29399]
### Version

1.41.2

### Steps to reproduce

similar to issue https://github.com/microsoft/playwright/issues/28500

System info
Playwright Version: 1.41.2
Operating System: Mac
Node.js version: v20.3.0
Browser: Chromium
Reproduces: always

Source code
Just installed Playwright and I'm using the test files, haven't made any changes (demo-todo-app.spec.ts and example.spec.ts)

Steps
When running `npx playwright test --ui`, I'm getting the following: 
ProtocolError: Protocol error (Browser.getVersion): Internal server error, session closed.

When running`npx playwright test`, I'm getting errors on all Chromium test runs. Firefox and Webkit work fine. 

### Expected behavior

Can use UI mode, tests pass in chrome

### Actual behavior

`Error: browserType.launch: Target page, context or browser has been closed
Browser logs:

<launching> /Users/myUser/Library/Caches/ms-playwright/chromium-1097/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --enable-use-zoom-for-dsf=false --use-angle --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/var/folders/0_/kqkw512574d2xn91pntrmkmr0000gn/T/playwright_chromiumdev_profile-IhHsV9 --remote-debugging-pipe --no-startup-window
<launched> pid=28962
Call log:
  - <launching> /Users/myUser/Library/Caches/ms-playwright/chromium-1097/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --enable-use-zoom-for-dsf=false --use-angle --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/var/folders/0_/kqkw512574d2xn91pntrmkmr0000gn/T/playwright_chromiumdev_profile-IhHsV9 --remote-debugging-pipe --no-startup-window
  - <launched> pid=28962`

### Additional context

I've tried `npx playwright install --with-deps chromium`, `npx playwright install` and the most recent canary release to no avail. Cypress runs with Chrome work fine, so doesn't seem to be a firewall issue. I've tried using version 1.40.1, which worked fine on January 3 when I first installed Playwright, but does not seem to be working any more either.

### Environment

```shell
System:
    OS: macOS 14.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.27 GB / 16.00 GB
  Binaries:
    Node: 20.3.0 - /usr/local/bin/node
    npm: 9.6.7 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.41.2 => 1.41.2 
    playwright: ^1.41.2 => 1.41.2
```

**Comment by dgozman** [comment]
@jtibbit Thank you for the issue. It seems like something's wrong on your computer, so that it cannot run Chromium. Perhaps some corporate policies?

I'd recommend running with `DEBUG=pw:browser` environment variable - maybe there's something useful in the logs.
```sh
DBEUG=pw:browser npx playwright test
```

That said, the chances that we can fix your environment are very slim.

**Comment by abrowne2** [comment]
Still getting this, but don't have steps for repro. :|

**Comment by kdevcse** [comment]
Seeing this issue as well for Playwright Chromium 1097

**Comment by nayanmarlin** [comment]
@dgozman - it is still persist. - https://github.com/microsoft/playwright/issues/29952

**Comment by kdevcse** [comment]
Reverting back to playwright version 1.39.0 which uses playwright chromium 1084 fixes the issue for me. I don't know why but would be nice to get this fixed. Not sure why this issue is closed everyone at my company is experiencing this.

**Comment by mxschmitt** [comment]
Would it be possible to:

1. Set the `DEBUG=pw:browser` env var and try to run a Playwright test? This should give some more debug output.
2. Try to run Chromium manually, the location of the executable is reported when the error happens, alternatively its located around here: /Users/$USER/Library/Caches/ms-playwright/chromium-<version>/chrome-mac/Chromium.app/

This would help us a ton in order to get more debug output and debug this issue further since we have not seen many bug reports around this issue.

**Comment by kdevcse** [comment]
> @kdevcse Would it be possible to:
> 
> 1. Set the `DEBUG=pw:browser` env var and try to run a Playwright test? This should give some more debug output.
> 2. Try to run Chromium manually, the location of the executable is reported when the error happens, alternatively its located around here: /Users/$USER/Library/Caches/ms-playwright/chromium-/chrome-mac/Chromium.app/
> 
> This would help us a ton in order to get more debug output and debug this issue further since we have not seen many bug reports around this issue.

1. Sure thing I've attached a debug log for a test here:
[debug.txt](https://github.com/microsoft/playwright/files/14619125/debug.txt)

2. I see now this issue is listed for MacOS, but we are currently seeing this issue with Windows (it's all we use here). But here are the logs I have for that I think. Let me know if this isn't the right file: 
[debug.log](https://github.com/microsoft/playwright/files/14619149/debug.log)

**Comment by mxschmitt** [comment]
This looks different to the original issue - do you mind uploading a self-contained minimal reproducible to GitHub where we could take a look? / run it locally? Does this happen for any new Playwright project or only in your specific repository?

**Comment by kdevcse** [comment]
> This looks different to the original issue - do you mind uploading a self-contained minimal reproducible to GitHub where we could take a look? / run it locally? Does this happen for any new Playwright project or only in your specific repository?

I'm not sure what you mean by `self-contained minimal reproducible to GitHub` but sure I don't mind at all! 😆Just let me know what you need. Whatever can help us get on the latest version again. 

I haven't tried a new repo but it definitely happens on our specific repository. I've tried to hunt it down but the farthest I've been able to get is it's something specific with this version of chromium +playwright and the code.

**Comment by mxschmitt** [comment]
yeah ideally something which we can `git clone`, `npm install` and do `npx playwright test` to observe the error.

**Comment by kdevcse** [comment]
> yeah ideally something which we can `git clone`, `npm install` and do `npx playwright test` to observe the error.

Oh hmm well it's a private repo. Not sure how quick I would be able to spin up something small and isolated. Is there anything I can run to help debug this issue?

**Comment by mxschmitt** [comment]
Unfortunately not, besides the environment variable.

**Comment by kdevcse** [comment]
From what I can tell, it may be related to the `APIRequestContext` being included in a wrapper class that is instantiated in the `beforeAll()` and then referenced in a test. Is that a valid use case? It fails any time the `APIRequestContext`'s `post` method is referenced within a test.

**Comment by mxschmitt** [comment]
Sounds like a duplicate of https://github.com/microsoft/playwright/issues/29260

**Comment by kdevcse** [comment]
> Sounds like a duplicate of https://github.com/microsoft/playwright/issues/29260

Hmmm yeah I think you're right actually

**Comment by mxschmitt** [comment]
Folding into it

**Comment by smartoryu** [comment]
Seems like it's a caching issue. Just delete this directory `/Users/myUser/Library/Caches/ms-playwright/` and try to run the test again. Works on my case.

**Comment by osvaguillen** [comment]
Just for future reference in case it's helpful for somebody else, at least what @smartoryu suggested worked for me
> Seems like it's a caching issue. Just delete this directory /Users/myUser/Library/Caches/ms-playwright/ and try to run the test again. Works on my case.

**Comment by john-persson-polestar** [comment]
I'm not convinced that  this is a cache issue. `/Users/myUser/Library/Caches/ms-playwright` seams to be where installed browsers are stored.
If I delete the `ms-playwright" folder, then Chrome start when running `playwright test --ui` as expected. However, this introduces a different error inte Playwright console:
![Image](https://github.com/user-attachments/assets/babe597c-0ddd-48e5-9e42-8a756499a6ee)

Following this up by running `npx playwright install`, adds the file which is missing in the error message form the Playwright console, but when trying to run `playwright test --ui` once again gives me the same error message as OP.

**Comment by fullstackzach** [comment]
This started happening for me after I upgraded to Mac OS Sequoia 15.0.1 - deleting the cache directory as @smartoryu fixed it for me

**Comment by john-persson-polestar** [comment]
@fullstackzach , yeah I'm on Sequoia 15.0.1 as well. I haven't been using the UI command until now, so unfortunately I've got nothing to compare with. It makes me wonder if there's anything wrong with the Chromium binary (~//Library/Caches/ms-playwright/chromium-1134/chrome-mac/Chromium.app/Contents/MacOS/Chromium) under Sequoia, but on the other hand the tests are working when running without the ui flag.

**Comment by john-persson-polestar** [comment]
Found the solution int this thread/comment: https://github.com/microsoft/playwright/issues/31064#issuecomment-2138905093

**Comment by Cloud11PL** [comment]
> Found the solution to my problem in this thread/comment: [#31064 (comment)](https://github.com/microsoft/playwright/issues/31064#issuecomment-2138905093)

I don't have that env variable in `.zshrc` and I still get that error :/

**Comment by YevhenTarasenko** [comment]
Hi!
The same problem on @playwright/test": "^1.53.1

I tried deleting the folder /Users/myUser/Library/Caches/ms-playwright and then reinstalling Playwright, but it didn't help.

`ProtocolError: Protocol error (Browser.getVersion): Internal server error, session closed.
    at \node_modules\playwright-core\lib\server\chromium\crConnection.js:116:57
    at new Promise (<anonymous>)
    at CRSession.send (\node_modules\playwright-core\lib\server\chromium\crConnection.js:115:12)
    at Function.connect (\node_modules\playwright-core\lib\server\chromium\crBrowser.js:77:35)
    at Chromium.connectToTransport (\node_modules\playwright-core\lib\server\chromium\chromium.js:126:47)
    at Chromium._innerLaunch (\node_modules\playwright-core\lib\server\browserType.js:154:32)
    at Chromium._innerLaunchWithRetries (\node_modules\playwright-core\lib\server\browserType.js:117:14)
    at \node_modules\playwright-core\lib\server\browserType.js:107:24
    at ProgressController.run (\node_modules\playwright-core\lib\server\progress.js:80:22)
    at Chromium.launchPersistentContext (\node_modules\playwright-core\lib\server\browserType.js:98:21)
    at launchApp (\node_modules\playwright-core\lib\server\launchApp.js:54:19)
    at openTraceViewerApp (\node_modules\playwright-core\lib\server\trace\viewer\traceViewer.js:150:29)
    at \node_modules\playwright\lib\runner\testServer.js:398:20    
    at innerRunTestServer (\node_modules\playwright\lib\runner\testServer.js:436:5)
    at Object.runUIMode (\node_modules\playwright\lib\runner\testServer.js:392:10)
    at runTests (\node_modules\playwright\lib\program.js:171:21)   
    at t.<anonymous> (\node_modules\playwright\lib\program.js:57:7) {
  type: 'closed',
  method: 'Browser.getVersion',
  logs: '\n' +
    '<launching> \\ms-playwright\\chromium-1179\\chrome-win\\chrome.exe --disable-field-trial-config --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=AcceptCHFrame,AutoExpandDetailsElement,AvoidUnnecessaryBeforeUnloadCheckSync,CertificateTransparencyComponentUpdater,DestroyProfileOnBrowserClose,DialMediaRouteProvider,ExtensionManifestV2Disabled,GlobalMediaControls,HttpsUpgrades,ImprovedCookieControls,LazyFrameLoading,LensOverlay,MediaRouter,PaintHolding,ThirdPartyStoragePartitioning,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --unsafely-disable-devtools-self-xss-warnings --no-sandbox --app=data:text/html, --window-size=1280,800 --test-type= --user-data-dir=\\playwright_chromiumdev_profile-3IYgX7 --remote-debugging-pipe about:blank\n' +        
    '<launched> pid=25572'
}`

**Comment by ggarabedian** [comment]
I was having the exact same issue with a completely new Playwright project running on a a Hyper-V Windows Server 2022 virtual machine. Running `npx playwright test --ui-host=0.0.0.0` as described in their docs (https://playwright.dev/docs/test-ui-mode#docker--github-codespaces) seems to resolve the problem. At least it did for me.

**Comment by ccoralliPrivate** [comment]
Hello The same problem on @playwright/test": "^1.53.1 as well

**Comment by vchirikov** [comment]
Yes, for me the last working version is 1.52.x, I've checked and still broken with 1.54.
Browser just crashed in Browser.getVersion call .
interesting that `npx playwright open https://google.com` works fine, but `playwright test --ui` doesn't work even on empty project:


```bash
❯ ls

        Directory: Q:\code\vchirikov\tmp\pw


  node_modules          package-lock.json    package.json

❯ cat .\package.json
                    {
  "name": "pw",
  "version": "1.0.0",
  "description": "",
  "license": "ISC",
  "author": "",
  "type": "commonjs",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "@playwright/test": "^1.54.0"
  }
}
❯ npx playwright test --ui
ProtocolError: Protocol error (Browser.getVersion): Internal server error, session closed.
    at Q:\code\vchirikov\tmp\pw\node_modules\playwright-core\lib\server\chromium\crConnection.js:116:57
    at new Promise (<anonymous>)
    at CRSession.send (Q:\code\vchirikov\tmp\pw\node_modules\playwright-core\lib\server\chromium\crConnection.js:115:12)
    at CRBrowser.connect (Q:\code\vchirikov\tmp\pw\node_modules\playwright-core\lib\server\chromium\crBrowser.js:77:35)
    at Chromium.connectToTransport (Q:\code\vchirikov\tmp\pw\node_modules\playwright-core\lib\server\chromium\chromium.js:120:47)
    at Chromium._innerLaunch (Q:\code\vchirikov\tmp\pw\node_modules\playwright-core\lib\server\browserType.js:130:46)
    at async Chromium._innerLaunchWithRetries (Q:\code\vchirikov\tmp\pw\node_modules\playwright-core\lib\server\browserType.js:93:14)
    at async Chromium.launchPersistentContext (Q:\code\vchirikov\tmp\pw\node_modules\playwright-core\lib\server\browserType.js:85:21)
    at async ProgressController.run (Q:\code\vchirikov\tmp\pw\node_modules\playwright-core\lib\server\progress.js:139:41)
    at async launchApp (Q:\code\vchirikov\tmp\pw\node_modules\playwright-core\lib\server\launchApp.js:56:19) {
  type: 'closed',
  method: 'Browser.getVersion',
  logs: '\n' +
    '<launching> C:\\Users\\<username>\\AppData\\Local\\ms-playwright\\chromium-1181\\chrome-win\\chrome.exe --disable-field-trial-config --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=AcceptCHFrame,AutoExpandDetailsElement,AvoidUnnecessaryBeforeUnloadCheckSync,CertificateTransparencyComponentUpdater,DestroyProfileOnBrowserClose,DialMediaRouteProvider,ExtensionManifestV2Disabled,GlobalMediaControls,HttpsUpgrades,ImprovedCookieControls,LazyFrameLoading,LensOverlay,MediaRouter,PaintHolding,ThirdPartyStoragePartitioning,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --unsafely-disable-devtools-self-xss-warnings --edge-skip-compat-layer-relaunch --no-sandbox --app=data:text/html, --window-size=1280,800 --test-type= --user-data-dir=C:\\Users\\<username>\\AppData\\Local\\Temp\\playwright_chromiumdev_profile-GLuvpV --remote-debugging-pipe about:blank\n' +
    '<launched> pid=107600'
}
```

@mxschmitt reopen this please, because it's much simpler to find

**Comment by bartstcv** [comment]
Have a similar error when running a Storybook's test runner that uses Playwright under the hood:

<img width="1617" height="93" alt="Image" src="https://github.com/user-attachments/assets/9fceccf6-1f7f-4671-bbf6-b86e8ceea4d5" />

And downgrading `playwright` to `1.52` solves the issue.

**Comment by bigcakes** [comment]
I am getting the issue on 1.52.0 on Windows, but it appears to be only if I run it from a console opened with "Run as Administrator"

**Comment by vvedmedera** [comment]
> I am getting the issue on 1.52.0 on Windows, but it appears to be only if I run it from a console opened with "Run as Administrator"

Yes, same here, if a terminal is launched with elevated rights - errors out, only works if provide --ui-host=0.0.0.0, if as normal user - all ok.

**Comment by bigcakes** [comment]
> > I am getting the issue on 1.52.0 on Windows, but it appears to be only if I run it from a console opened with "Run as Administrator"
> 
> Yes, same here, if a terminal is launched with elevated rights - errors out, only works if provide --ui-host=0.0.0.0, if as normal user - all ok.

I opened a new issue this morning around this exact case: https://github.com/microsoft/playwright/issues/36714

**Comment by ccoralliPrivate** [comment]
👍

**Comment by eleinsabel** [comment]
> > I am getting the issue on 1.52.0 on Windows, but it appears to be only if I run it from a console opened with "Run as Administrator"
> 
> Yes, same here, if a terminal is launched with elevated rights - errors out, only works if provide --ui-host=0.0.0.0, if as normal user - all ok.

Same as mine. Error happens when running as administrator. However, this works npx playwright test --ui-host=0.0.0.0
