### ISSUE TITLE
[Bug]: Downloaded file format is different than the manually downloaded one.

### ISSUE THREAD

**Issue by Snehaveeranna** [microsoft/playwright#29396]
### Version

1.35.1

### Steps to reproduce

when we download any file using playwright java, it is having lock icon and even the extension is also different.

### Expected behavior

it should download with original file extension

### Actual behavior

downloading with different extension and path is also different

### Environment

```shell
Windows 10
```

**Comment by dgozman** [comment]
@Snehaveeranna Unfortunately, I cannot reproduce the issue without any code snippet to run. I'd recommend reading the [downloads guide](https://playwright.dev/java/docs/downloads) or [ask the community](https://playwright.dev/java/community/welcome) any questions you have.

If you still believe there is a bug in Playwright, please file a new issue by filling in the "Bug Report" template and providing exact repro steps and code.
