### ISSUE TITLE
[Feature]: Allow direct comparison between two screenshots in a single run

### ISSUE THREAD

**Issue by michaelschufi** [microsoft/playwright#29394]
### 🚀 Feature Request

Playwright should allow a direct comparison of two screenshots in a single test/run.

### Example

```ts
test("screenshot check", async ({ page }) => {
  await page.goto("https://prod.playwright.dev");
  const screenshotCurrentVersion = await page.screenshot({ fullPage: true });
  
  await page.goto(
    "https://preview.playwright.dev"
  );
  const screenshotNextVersion = await page.screenshot({ fullPage: true });

  // compare screenshots 
  await expect(screenshotNextVersion).toBeScreenshot(screenshotCurrentVersion);
});
```

### Motivation

While critical user journeys can be checked using interactive actions, it is more difficult to test design changes. Especially if changes could potentially affect multiple components.
 
When a new version of a website is about to be published, we currently check manually if the changes don't affect an existing page/component's design in an unintended way. For simplicity, this is done by comparing a preview deployment with the current production deployment. Setting up a whole testing environment for a smaller project, is more often than not, more costly than doing it manually. However, we would save some time and be more precise by using playwright to help us spot differences.   

This feature would allow us to create simple diffs between two versions of a website or of a component, making it easier to spot unintended changes that a new version would introduce, without needing to store a base version of the components/pages we would like to compare to.

**Comment by dgozman** [comment]
Thank you for the thorough explanation! Folding into #18937.

**Comment by michaelschufi** [comment]
Thank you. Sorry for missing that! 🙈
