### ISSUE TITLE
[Bug]: 'Error: Tracing has been already started' with 'retain-on-failure' set in component tests

### ISSUE THREAD

**Issue by CkSned** [microsoft/playwright#29395]
### Version

1.41.2

### Steps to reproduce

**Steps:**

1. Download the attached minimal reproduction zip file.
2. Install dependencies with `pnpm install`.
3. Run the tests with `pnpm test`.

[ct-trace-bug.zip](https://github.com/microsoft/playwright/files/14193963/ct-trace-bug.zip)

### Expected behavior

All tests in the minimal reproduction zip should execute & pass with the trace set to `retain-on-failure` in `playwright.config.ts`. If a test fails for a valid reason then Playwright should retain the trace files.

### Actual behavior

Some tests will fail with the output `Error: Tracing has been already started`.

### Additional context

The issue is more prevalent the more tests/test files you have. If you set trace to `off` or `on`, all of the tests will pass. Additionally, with `trace: off` Playwright will still record traces when run via the UI.

### Environment

```shell
System:
    OS: macOS 14.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.25 GB / 16.00 GB
  Binaries:
    Node: 18.18.2 - ~/.asdf/installs/nodejs/18.18.2/bin/node
    npm: 10.2.5 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.15.1 - /opt/homebrew/bin/pnpm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/experimental-ct-react: 1.41.2 => 1.41.2
```

**Comment by CkSned** [comment]
Hey, thanks for replying.

Upgrading to the canary version fixes the issue on my side as well. I look forward to the v1.42 release!

**Comment by dgozman** [comment]
Thank you for confirming, closing this now.
