### ISSUE TITLE
[Bug]: expect(page).toHaveScreenshot generates image at 1600px by 2690px but fails when ran again as it expects 1600px by 2768px

### ISSUE THREAD

**Issue by ezrover** [microsoft/playwright#29391]
### Version

1.41.2

### Steps to reproduce

`import { test, expect } from "@playwright/test";
import { hideElements, hideOneTrust, timeout } from "../../../helpers.js";

let env = process.env.ENV_VAR;
const threshold = Number(process.env.THRESHOLD ? process.env.THRESHOLD : 0.0001);

const fullPage = true;
const locales = ['', 'fr-ca/', 'en-ca/', 'ar-sa/', 'de-ch/', 'de-de/', 'fr-ch/', 'nb-no/', 'nl-nl/'];

locales.forEach((locale) => { 
  test(`${env}/${locale}request-test-drive`, async ({ page }) => {
    if (!fullPage ) {
      await page.setViewportSize({width: 1280, height: 2836}, false);
    }
    await page.goto(process.env.TEST_TARGET + `/${locale}request-test-drive`);
    await page.waitForLoadState("networkidle");
    if (process.env.POPUP_MODAL) {
      await page.getByRole("button", { name: "×" }).click();
    }
    await hideOneTrust(page);
    await expect(page).toHaveScreenshot({
      fullPage: fullPage,
      maxDiffPixelRatio: threshold,
    });
  });
});`

### Expected behavior

When the same test is run the 2nd time from the same Macbook , it should expect the same size as the previous run which saved the image to local drive.

### Actual behavior

When the same test is run the 2nd time from the same Macbook , it errors out with:   Expected an image 1600px by 2768px, received 1600px by 2690px. 482693 pixels (ratio 0.11 of all image pixels) are different.

### Environment

```shell
System:
    OS: macOS 14.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 10.05 GB / 64.00 GB
  Binaries:
    Node: 18.17.1 - /usr/local/opt/node@18/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.6.7 - /usr/local/opt/node@18/bin/npm
    pnpm: 6.11.0 - /usr/local/bin/pnpm
    bun: 1.0.3 - ~/.bun/bin/bun
  IDEs:
    VSCode: 1.86.0 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.41.2 => 1.41.2 
    playwright: ^1.41.2 => 1.41.2
```

**Comment by dgozman** [comment]
@ezrover Unfortunately, I cannot run your snippet because it is missing the web page being tested.

That said, why do you think there is a bug in Playwright? Perhaps your page renders differently during two test runs? Did you compare the screenshots? Please provide more details, otherwise I'll have to close this issue as non-actionable.

**Comment by dgozman** [comment]
Closing as per above. If you still encounter problems, please file a new issue with a repro and link to this one.

**Comment by rkmsnc** [comment]
Hi @ezrover 
This could help https://github.com/microsoft/playwright/issues/31592#issuecomment-2361010102
