### ISSUE TITLE
[Feature]: Codegeneration - add the possibility to prefer ids or custom attributes as selectors

### ISSUE THREAD

**Issue by Bjego** [microsoft/playwright#29400]
### 🚀 Feature Request

Hey guys,
the codegeneration generates selectors for all the elements on the displayed web page. Those selectors usually don't use the id nor custom attributes to identitfy the elements.
Maybe it's possible to add a flag to the codegeneration cli to prefer ids or a specific attribute as selector in the generated code.

### Example

Maybe a codegen call could use an optional flag like selector
```
npx playwright codegen --selector id demo.playwright.dev/todomvc
npx playwright codegen --selector data-id demo.playwright.dev/todomvc
```

and then the preferred selector in the gernerated code should be the data-id attribute or the normal id attribute.

### Motivation

Many testers I've spoken with come from selenium and they are trained to use technical ids. The argumentation is, that the test should be reliable on a language independent way. As the normal generated selectors focus on labels , placeholders and texts. These tests are more process oriented then user oriented, but they would love the power of quickly generating the necessary selectors for their process.

**Comment by dgozman** [comment]
@Bjego You can already do the following:

```sh
npx playwright codegen --test-id-attribute=data-id
```

Let me know whether this works for you.

**Comment by dgozman** [comment]
Closing as per above. If you still encounter problems, please file a new issue with a repro and link to this one.

**Comment by esther-86** [comment]
Seems like https://github.com/microsoft/playwright/issues/9015 is similar to this. --test-id-attribute seems to take in 1 id to override, not a list, correct?
