### ISSUE TITLE
[Feature]: add "run test"-icon next to the test-header line when sticky scroll is enabled

### ISSUE THREAD

**Issue by sweidac** [microsoft/playwright#29404]
### 🚀 Feature Request

1. enable sticky scroll in the text editor
2. be in a test file
3. scroll up a longer test
4. try to run the test you are currently writing from within the text-editor

[Screencast from 2024-02-07 21-23-17.webm](https://github.com/microsoft/playwright/assets/17548832/85e5c57e-9d3d-4eef-8b76-54cd069b6470)

_I'm aware that this feature might be out of scope of playwright and be in-scope of vscode_

### Motivation

If that Icon would be in the sticky scroll, one could run all tests that are currently visible in the editor.

**Comment by dgozman** [comment]
@sweidac Thank you for the issue! 

> I'm aware that this feature might be out of scope of playwright and be in-scope of vscode

You are exactly right. This UI is provided by VSCode itself, not Playwright. Would you like to file an issue at https://github.com/microsoft/vscode?

**Comment by sweidac** [comment]
Thanks for your guidance!
