### ISSUE TITLE
[Bug]: Tests are failing randomly with only Webkit browser 

### ISSUE THREAD

**Issue by emnabennahia** [microsoft/playwright#29413]
### Version

1.41.0 also tested with 1.38.0

### Steps to reproduce

We have our project with Playwright working from more one year with webkit/firefox/chrome browsers but from last week tests are failing randomly only with **webkit browser**, we tried to change front-end dependencies, playwright version, resources, gitlab-runners but always same issue.
Also we tried to run the tests in the pipelines that were passing last month but they are failing now.
We tried with playwright version that is working before (1.38), also the latest one (1.41) and same issue.
This is the configuration of browsers that we have (with cucumber):
`import {
  chromium,
  ChromiumBrowser,
  firefox,
  FirefoxBrowser,
  webkit,
  WebKitBrowser,
  ConsoleMessage,
} from '@playwright/test';
let browser: ChromiumBrowser | FirefoxBrowser | WebKitBrowser;
BeforeAll(async function () {
  const browsers: any = {
    chrome: chromium,
    firefox,
    webkit,
  };
  browser = await browsers[config.browser].launch(config.browserOptions);
});
After(async function (this: CustomWorld, { result }: ITestCaseHookParameter) {
  if (result) {
    await this.attach(
      'Browser:' +
      this.page?.context().browser()?.browserType().name() +
      ' Version: ' +
      this.page?.context().browser()?.version(),
    );
    await this.attach(
      `Status: ${result?.status}. Duration:${result.duration?.seconds}s`,
    );
`

### Expected behavior

Expected: Tests with Webkit browser should work correctly 

### Actual behavior

Actual: Only Tests with webkit browser are failing (firefox and chrome are working good)

### Environment

```shell
Playwright Version: v1.41+ v1.38
cucumber: 8.5.2
Operating System: Mac 14.3
node v18.14.0
Browser: WebKit
```

**Comment by dgozman** [comment]
@emnabennahia I am not able to reproduce the issue, because you did not provide any runnable repro. Please file a new issue by filling in the "Bug Report" template and thoroughly answer the questions, including a self-contained repro that we can run.
