### ISSUE TITLE
[BUG] Configure projects/browsers for VS Code that's different from `playwright.config.ts`

### ISSUE THREAD

**Issue by peterbe** [microsoft/playwright#29419]
We run Playwright in three ways:

1. In CI (GitHub Actions)
2. On the terminal `npm run playwright-test`
3. In VS Code (using the little play icon in the left margin)

In CI and in `npm run playwright-test` I can control the browsers by supplying `playwright test --project=...THIS...`. But in VS Code I get *all* projects. When iterating on something, it's inconvenient to have all browsers start up. I might just want `Google Chrome`. 

Perhaps it's more of a **feature request** that I'm able to control the projects from within the VS Code extension.

**Comment by llheylen** [comment]
In the Playwright extension for vscode, you can select the default project at the top, or simply choose the project for which you want to run the tests. Maybe this is what you are looking for?

![image](https://github.com/microsoft/playwright/assets/44919287/c43f5861-93f7-47fa-a598-8efa39c399b9)

**Comment by peterbe** [comment]
Yeah that totally worked! 
I was just blind :) (in my defense, it was a bit small)

Thanks!
