### ISSUE TITLE
[Docs]: Fixtures + Storage State

### ISSUE THREAD

**Issue by shubhijain106** [microsoft/playwright#29411]
### Page(s)

https://playwright.dev/docs/auth#testing-multiple-roles-with-pom-fixtures
https://playwright.dev/docs/test-fixtures
https://playwright.dev/docs/pom

### Description

I want to E2E test a scenario where admin sends a survey and expect user to answer survey all in 1 single test. 

I want to write a fixture which uses different page when signed in using different auth tokens(I have saved storage states for each of these). How to go about it?

Rough algo is

```
class Fixture1{
goto(page){
this.page = page; //this seems wrong, I should be using POM but I don't know how to
}
sendSurvey(){}
}
class Fixture2{
goto(page){
this.page = page;
}
answerSurvey(){}
}

```
```
export const test = base.extend<CustomTestFixture>({
fixture1: async ({}, use) => {
    await use(new Fixture1());
  },
fixture2: async ({}, use) => {
    await use(new Fixture2());
  },
})

```

```
//test file
test.beforeEach(async ({ browser },testInfo) => {
  adminContext = await browser.newContext({ storageState: adminURL });
  adminPage = await adminContext.newPage();
  userContext = await browser.newContext({ storageState: userURL });
  userPage = await userContext.newPage();
});
test.afterEach(async({},testInfo)=>{
    await adminContext.close();
    await userContext.close();
});

test({fixture1,fixture2})=>{
test.step(send)=>{
fixture1.goto(adminPage)
fixture1.send()
}
test.step(answer)=>{
fixture2.goto(userPage)
fixture2.answer()
}
}
```

Is this correct or is there any other way to pass in different storage states in fixtures? Also, how does fixture help with isolation here? I am a little confused on advantage of fixture. Can I use POM to initialize page for each different storageState?
Any suggestions/updated documentation on working with storageState & fixtures+POM would be appreciated

I saw this https://playwright.dev/docs/auth#testing-multiple-roles-with-pom-fixtures
Is there any other way to create UserPage fixture dynamically for 6 different storage state than to define for each storage state a new fixture? 

```
// Declare the types of your fixtures.
type MyFixtures = {
  adminPage: AdminPage;
  userPage: UserPage;
};

export * from '@playwright/test';
export const test = base.extend<MyFixtures>({
  adminPage: async ({ browser }, use) => {
    const context = await browser.newContext({ storageState: 'playwright/.auth/admin.json' });
    const adminPage = new AdminPage(await context.newPage());
    await use(adminPage);
    await context.close();
  },
  userPage: async ({ browser }, use) => {
    const context = await browser.newContext({ storageState: 'playwright/.auth/user.json' });
    const userPage = new UserPage(await context.newPage());
    await use(userPage);
    await context.close();
  },
});
```

And how do I use those POM fixtures in my fixture1 and fixture2 in same test. How to know that call fixture1 with a page signed in as admin and fixture2 with a page signed as user.
```
// Import test with our new fixtures.
import { test, expect } from '../playwright/fixtures';

// Use adminPage and userPage fixtures in the test.
test('admin and user', async ({ adminPage, userPage }) => {
  // ... interact with both adminPage and userPage ...
  await expect(adminPage.greeting).toHaveText('Welcome, Admin');
  await expect(userPage.greeting).toHaveText('Welcome, User');
});
```

**Comment by dgozman** [comment]
@shubhijain106 Unfortunately, I do not follow your questions. It seems like you went along this guide https://playwright.dev/docs/auth#testing-multiple-roles-with-pom-fixtures, which is the intended way.

If you have any specific suggestions for improving docs, please explain them here.
If you believe there is a bug in Playwright, please file a new issue by filling in the "Bug Report" template.

The issue tracker is reserved for bug reports and feature requests. For anything else, such as questions or getting help, please see:
- [The Playwright documentation](https://playwright.dev/)
- [Our Discord server](https://aka.ms/playwright/discord)
