### ISSUE TITLE
Function to add product to cart with api does not work without storageState, it work fine in cypress can you help me 

### ISSUE THREAD

**Issue by ayoubfadel** [microsoft/playwright#29420]
i have a function to login via api so when i need to be logged in some scenarios i just call the function, it does not work only if i use storageState, i have the same function. in cypress project and it work fine why here not :

`static async addProductToCart(page, request, SKU, name, language, devise){
        await request.post('/INTERSHOP/web/WFS/TEST-${name}-Site/${language}/-/${devise}/ViewQuickorder-Dispatch', {
            form: {
              ['SKU_${SKU}']: SKU,
              ['Quantity_${SKU}']: 1,
              addToCart: 'addToCart',
              ignoreErrorProducts: true,
              ajax: true,
              ajaxLayer: true,
              ordredSkus: SKU
            }
        })
    }`

**Comment by dgozman** [comment]
This issue tracker is reserved for bug reports and feature requests.

For anything else, such as questions or getting help, please see:

- [The Playwright documentation](https://playwright.dev/)
- [Our Discord server](https://aka.ms/playwright/discord)
