### ISSUE TITLE
[Bug]: Parallel tests with multiple storage states flaky

### ISSUE THREAD

**Issue by shubhijain106** [microsoft/playwright#29428]
### Version

1.41.1

### Steps to reproduce

Hello everyone, 
I am new to playwright and I recently wrote a bunch of tests which uses multiple user storage states. I have scenarios where a single test is using multiple roles together(https://playwright.dev/docs/auth#testing-multiple-roles-together).

As I am scaling the number of tests, I am noticing flakiness and "Target closed" error often. I updated my playwright config to use 1 _worker_ and _fullyParallel_ to false.

Is the issue related to parallelism? Individually the test passes but together they sometimes fail.
Can the below solution be used to scale my tests.? But can I test 2 roles together in one test using this approach?
https://playwright.dev/docs/test-parallel#isolate-test-data-between-parallel-workers

```
import { test } from '../../fixtures/CustomTestFixture';
import { adminURL, user1URL} from '../../auth';
import { BrowserContext, Page } from '@playwright/test';

let adminPage:Page;
let userPage: Page;
let adminContext: BrowserContext;
let userContext: BrowserContext;

test.beforeEach(async ({ browser }) => {
  adminContext = await browser.newContext({ storageState: adminURL });
  adminPage = await adminContext.newPage();
  userContext = await browser.newContext({ storageState: `$user1URL` });
  userPage = await userContext.newPage();
});

test.afterEach(async()=>{
    await adminContext.close();
    await userContext.close();
});

test('provide feedback ', async ({ browserName, sendPulse, pulseUtilities }, testInfo) => {
  await test.step('Send Pulse', async () => {
      //send pulse using user1 context
    await sendPulse.setUser(userContext,userPage);
    await sendPulse.send();
  });

  await test.step('Provide Feedback-step1', async () => {
    await adminPage.goto('/');
    await adminPage
        .getByRole('button', {
          name: 'Get started',
        })
        .last()
        .click();
      });

    await test.step('Provide Feedback-answer', async () => {
      await adminPage.getByRole('button', { name: 'Get Started' }).click();
      const nextButtonElement = adminPage.getByRole('button', { name: 'Next' });
      while (await nextButtonElement.isVisible()) {
        await nextButtonElement.click();
      }
      await adminPage.getByRole('button', { name: 'Submit answers' }).click();
      await softExpect(adminPage.getByText('You must answer at least 1')).toBeVisible();
....
    });
});

test('generate report', async ({ browserName, sendPulse, pulseUtilities }, testInfo) => {
  await test.step('Send Pulse', async () => {
      //send pulse using user1 context
    await sendPulse.setUser(userContext,userPage);
    await sendPulse.send();
  });

  await test.step('generate report-step1`, async () => {
    await adminPage.goto('/');
    await adminPage
        .getByRole('button', {
          name: 'Get Report',
        })
        .last()
        .click();
      });
....
});


```

### Expected behavior

I expect to see successful parallel and fast test runs

### Actual behavior

Tests are running fine only if I use 1 worker

### Environment

```shell
@playwright/test -> latest
```

**Comment by mxschmitt** [comment]
>  I am noticing flakiness and "Target closed" error often. I

Could you share the full error with us? Do you have a stack trace where the error appears?

Usually this happens when you have a missing await in a method. Do you [lint your tests](https://playwright.dev/docs/best-practices#lint-your-tests)?

**Comment by mxschmitt** [comment]
Closing in the meantime until we got a full reproduction. Feel free to re-file with attaching something we can run locally. Thanks for your understanding!
