### ISSUE TITLE
[Feature] Switch between tabs in same context

### ISSUE THREAD

**Issue by sublimator** [microsoft/playwright#2942]
See closed and languishing [QUESTION]: 
https://github.com/microsoft/playwright/issues/1443#issuecomment-634413611

I want to test an extension and in puppeteer we can use page.bringToFront() to focus a given tab.
The extension binds to the document [visibilitychange](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event) event in the content script

**Comment by 12masta** [comment]
@sublimator As a workaround I am closing tabs which are not under the test. Had same case with extension.

**Comment by aslushnikov** [comment]
As of Playwright v1.3.0, there's now [`page.bringToFront()`](https://playwright.dev/#version=v1.3.0&path=docs%2Fapi.md&q=pagebringtofront)

Hope it helps!

**Comment by sublimator** [comment]
@aslushnikov  

Awesome!
