### ISSUE TITLE
[Bug]: Playwright Should Never Fail Silently: It Should Always Report Why a Test Stopped

### ISSUE THREAD

**Issue by jwalkerinterpres** [microsoft/playwright#29426]
### Version

1.40.1

### Steps to reproduce

This is a general issue (not specific to any test/code).

### Expected behavior

When playwright exits, the user should *always* see some sort of explanation why.  They should never see a screen like this one:
<img width="1487" alt="image" src="https://github.com/microsoft/playwright/assets/152227747/a12c2446-3ceb-45c2-8851-f212491b9e35">

NOTE: Every other tab is similarly empty, except for the Source tab, which just shows the test itself:
<img width="1494" alt="image" src="https://github.com/microsoft/playwright/assets/152227747/c784e443-5668-4ae9-b93a-417e45cc1602">

### Actual behavior

You see a screen like the above.

Look, Playwright knows why it stopped running 100% of the time, right?  There's no reason why it shouldn't report that reason 100% of the time also.  Ideally every test failure should have _some_ explanatory text in the Errors tab, but if not there then at least in some other tab.

Of course, in these situations Playwright doesn't have an obvious error, so it can't show a lot of info ... but it should still be able to say "the test ran too long and exceeded the timeout", or "a promise didn't finish in a beforeEach" or _something_ that conveys why it stopped running.

### Additional context

Obviously, the specific reason this is happening has to do with my test code, but the issue I'm trying to raise is not specific to my code.  It shouldn't matter what the test code is:  the test runner always knows why its exiting, so I'm simply requesting that it always surface that information.

### Environment

```shell
System:
    OS: macOS 14.3
    Memory: 53.08 MB / 32.00 GB
  Binaries:
    Node: 21.2.0 - /usr/local/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by rkhomi** [comment]
Yeah, UI runner does not show typeError from TS, you will be able to see error if you only run in terminal, that's strange

**Comment by jwalkerinterpres** [comment]
Unfortunately the issue was a bit of Heisenbug originally (ie. it only occurred some of the time, unreliably), and it's not happening now.

However, I am running `@playwright/test@next`, and I'll report back if I see the issue again. If I don't, I think the ticket can be safely closed.

**Comment by mxschmitt** [comment]
Great, don't hesitate to re-file, since we usually don't monitor closed issues.
