### ISSUE TITLE
Hi My api test is failing see my code attached belowScreenshot 2024-02-09 at 8.20.50 PM Screenshot 2024-02-09 at 8.27.16 PM

### ISSUE THREAD

**Issue by testeranupam** [microsoft/playwright#29435]
### Please do not submit this issue.

- [X] I understand

**Comment by testeranupam** [comment]
Hi Api test is failing, i have created a class that will contain all the crud operation and using it in another class.

helper class
import { request, expect, APIResponse } from "@playwright/test";

const BASE_URL = "https://jsonplaceholder.typicode.com";
export class ApiHelper {
  private apiContext: any;

  /**
   * The constructor function initializes a new context for the API.
   * @param {any} apiContext - The `apiContext` parameter is an object that represents the context of an
   * API. It is used to store and manage information related to the API, such as authentication
   * credentials, request headers, and other configuration settings.
   */
  constructor(apiContext: any) {
    this.apiContext = apiContext.newContext();
  }

  async invokeGetApi(endPoint: string, statusCode: number = 200) {
    let response;
    try {
      console.log(`Making GET request to  endPoint:  ${BASE_URL}${endPoint}`);
      response = await this.apiContext.get(`${BASE_URL}${endPoint}`);
      expect(response.status()).toBe(statusCode);
      return await response.json();
    } catch (error) {
      return error;
    }
  }

![Uploading Screenshot 2024-02-09 at 8.27.16 PM.png…]()

**Comment by dgozman** [comment]
This issue tracker is reserved for bug reports and feature requests.

For anything else, such as questions or getting help, please see:
- [The Playwright documentation](https://playwright.dev/)
- [Our Discord server](https://aka.ms/playwright/discord)
