### ISSUE TITLE
[Bug]: Matching inside a locator returns page elements if  selector contains pipe symbol

### ISSUE THREAD

**Issue by yuhymuk** [microsoft/playwright#29436]
### Version

1.40

### Steps to reproduce

STR:
1. Search element that has inner elements
2. Serach element inside element from step 1. For example 

```
elements = search_context.locator("//*[.='Sold Out'] | //*[text()='Sold Out']").all()
len(elements)
out: 2
```

If I perform the same code but execute each selector separately, it returns the correct result

```
search_context.locator("//*[.='Sold Out']").all()
Out[8]: []

search_context.locator("//*[text()='Sold Out']").all()
Out[9]: []

search_context.locator('//*[.="Sold Out" or text()="Sold Out"]').all()
Out[15]: []

```

### Expected behavior

Matching inside a locator must be performed in Loctor context

### Actual behavior

the presence of the pipe symbol in the locator template is causing incorrect results during the inner search in the Locator object

### Environment

```shell
System:
  Mac OS
Python 3.11
playwright 1.40
```

**Comment by dgozman** [comment]
@yuhymuk Please provide a self-contained repro that I can run, including the web page that you are testing. We will not be able to work on this bug report without a repro scenario.

**Comment by mxschmitt** [comment]
Closing as per above, please re-file with a repro.
