### ISSUE TITLE
[Feature]: Is there a way to verify return an api request response time and size?

### ISSUE THREAD

**Issue by darshandp007** [microsoft/playwright#29449]
### 🚀 Feature Request

I am currently conducting API testing using Playwright with the request module. My objective is to validate both the API **response time** and **response size**. However, there is currently no default option available in the request module for this purpose.

### Motivation

The proposal aims to enhance Playwright by addressing current limitations and introducing features that improve functionality and user experience, ultimately aligning with the project's goals. The motivation is to elevate Playwright's performance and usability.

**Comment by mxschmitt** [comment]
There is a feature request for API response time: https://github.com/microsoft/playwright/issues/19621

Do you mean with size the body size?
