### ISSUE TITLE
[Bug]: page evaluate returns undefined for a specific site

### ISSUE THREAD

**Issue by reginaldl** [microsoft/playwright#29440]
### Version

1.41.2

### Steps to reproduce

1. Clone https://github.com/reginaldl/playwright-bug
2. npm install
3. npx playwright test

### Expected behavior

page.evaluate should return `42`.

### Actual behavior

page.evaluate consistently returns `undefined` on all browsers.

### Additional context

page.evaluate returns an unexpected value exclusively when browsing a specific website (see test case for exact address).

### Environment

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 32.35 GB / 64.00 GB
  Binaries:
    Node: 21.4.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - /opt/homebrew/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.41.2 => 1.41.2
```

**Comment by dgozman** [comment]
Investigation notes: this is due to `window.eval` being overwritten.

**Comment by ZooDoo4U** [comment]
There a bug in the repro code...

Should be:
 var res = await page.evaluate( async() => 41 + 1)

As you have it, you are evaluating a string?

**Comment by reginaldl** [comment]
Have you actually tried replacing with a function? It also fails.
Given that the site overwrites `window.eval`, I'm ok closing this as won't fix.

**Comment by ZooDoo4U** [comment]
Yes, i did and it worked.  But while i ran again my own site and the evaluate worked just fine. Can't help if a rouge site is overwriting stuff, not really a PW issue...

**Comment by mxschmitt** [comment]
If a site is overriding `globalThis.eval` we unfortunately can't do much from the Playwright side. Closing as a won't fix.
