### ISSUE TITLE
[Feature]: Expose more matcher functionality to custom matchers

### ISSUE THREAD

**Issue by emilong** [microsoft/playwright#29444]
### 🚀 Feature Request

It would be nice to have the following available to custom matchers to have closer parity with builtins:
1. The current `testInfo` instance.
2. A documented type for `this` (looks like [ExpectMatcherState](https://github.com/microsoft/playwright/blob/61b88a851dac002ee7dd95bdc61b31b48f576171/packages/playwright/types/test.d.ts#L6958-L6962) is close and exported, but [ExpectMatcherContext](https://github.com/microsoft/playwright/blob/61b88a851dac002ee7dd95bdc61b31b48f576171/packages/playwright/src/common/expectBundle.ts#L18) appears to be used internally?)
3. The [SnapshotHelper class](https://github.com/microsoft/playwright/blob/61b88a851dac002ee7dd95bdc61b31b48f576171/packages/playwright/src/matchers/toMatchSnapshot.ts#L74)

### Example

In my case, I'm hoping to write a snapshot matcher for PDFs that can take advantage of the existing snapshotting infrastructure built into Playwright.

### Motivation

`testInfo` is useful for getting the fully realized configuration of Playwright at runtime such as the `outputDir` and I think we need it to instantiate a `SnapshotHelper` instance as well? Having a documented `this` type for the matchers would also just help with typing/discoverability.

**Comment by dgozman** [comment]
@emilong Thank you for the issue!

> The current testInfo instance.

You can get it with [`test.info()`](https://playwright.dev/docs/api/class-test#test-info).

> A documented type for this

`ExpectMatcherState` is the right type. Do not pay attention to our internal types - you should rely on the public types only. Internal types are changed often and are not stable.

> The SnapshotHelper class

This one will definitely not be exposed through the public API. Feel free to copy it to your own code though, Playwright is open source 😄

**Comment by emilong** [comment]
Thanks for the fast response, @dgozman!

> > The SnapshotHelper class
>
> This one will definitely not be exposed through the public API. Feel free to copy it to your own code though, Playwright is open source 😄

My matcher is effectively similar just to calling `expect(...).toMatchSnapshot()` in a loop several times, so in my mind it seemed like a good chance for composition, but I'll go with your suggestion 😄
