### ISSUE TITLE
[Bug]: Component Testing - Unable to access elements mounted in React Portal

### ISSUE THREAD

**Issue by RajeshBatth** [microsoft/playwright#29447]
### Version

1.41.2

### Steps to reproduce

Example steps
1. Clone my repo at https://github.com/RajeshBatth/playwright-react-portals
2. yarn install && yarn test-ct
3. Click on test `normal mode` and test passes
4. Click on test `portal mode` and test fails

### Expected behavior

Tests `normal mode` and `portal mode` runs same logic, its just portal mode mounts Todo form inside a react's `createPortal()`

### Actual behavior

Not able to locate any elements that are mounted inside the form

### Environment

```shell
System:
    OS: macOS 14.3.1
    Memory: 105.05 MB / 16.00 GB
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.2/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by mxschmitt** [comment]
The problem is that `component` is a relative Locator of the element which got mounted. If the element mounts things outside of the actual component, it won't find it. Workaround would be to use the `page` instance:

```ts
test('portal mode', async ({ mount, page }) => {
  await mount(<App />);
  await page.getByRole('button', { name: 'Add Todo via Portal' }).click();
  await expect(page.getByPlaceholder('Enter Todo')).toBeVisible()
  await page.getByPlaceholder('Enter Todo').fill("Learn Playwright")
  await page.getByRole('button', {name: 'submit'}).click()
  await expect(page.getByText("Learn Playwright")).toBeVisible()
});
```

I'll keep this issue open for now in order to evaluate with the team, if we want to change this default.
