### ISSUE TITLE
[Bug]: Dragging text selections does not work in Chrome or Webkit

### ISSUE THREAD

**Issue by alexreardon** [microsoft/playwright#29466]
### Version

1.30.0

### Steps to reproduce

```ts
// Assumes you have a drop target setup to accept text selection dropping

import { expect, Page, test } from '@playwright/test';

test('dragging text selection', async ({ page }) => {
    await page.goto(`${exampleUrl}`);

    const dropTarget = page.locator('[data-testid="drop-target"]');
    const text = page.locator('[data-testid="text"]');
    const data = await text.innerText();

    await text.selectText();
    await text.dragTo(dropTarget);

    await expect(dropTarget).toContainText(data);
  });
```

### Expected behavior

When dragging a text selection, the text selection should be dragged.

### Actual behavior

In Firefox, the text selection is dragged. However, in Chrome and Webkit the text selection is not dragged.

### Additional context

Strangely, the above test passes for Chrome and Webkit when in debug mode (`--debug`). Which makes me think this is a timing issue.

I tried reimplementing `dragTo` using lower level commands (eg `page.mouse.move` etc) but I ran into the same problem.

### Environment

```shell
Playwright Version: [1.30.0]
Operating System: [macOS@14.2.1]
Browser: [Chrome, Webkit]
```

**Comment by mxschmitt** [comment]
The snippet you provided does not contain a self-contained reproduction. In order for us to triage an issue, we need a code snippet which we can run locally. Please re-file by following the issue template. Thanks for your understanding!

The Playwright version you are using is also very old - we recommend staying up to date.
