### ISSUE TITLE
[Bug]: webServer not able to find self-signed certificate in certificate chain when using url option

### ISSUE THREAD

**Issue by JohnMarsden24** [microsoft/playwright#29475]
### Version

1.41.1

### Steps to reproduce

1. Clone https://github.com/JohnMarsden24/playwright-bug
2. Run `npx playwright test`  -> tests will pass
3. In `playwright.config.ts` uncomment the `url` in the `webServer` options and comment out `port`
4. Run `DEBUG=pw:webserver npx playwright test` -> startup will fail with `Error while checking if https://127.0.0.1:3000/ is available: self-signed certificate in certificate chain`

### Expected behavior

I expect playwright to pick up the HTTPs certificate regardless if I use `url` or `port` setting in `webServer`

### Actual behavior

When using `url` it can not locate the HTTPs certificate and will timeout. Using `port` works just fine. This also has the knock on effect that we can't use the `PLAYWRIGHT_TEST_BASE_URL` environment variable because that gets overwritten [here](https://github.com/microsoft/playwright/blob/ff4191335d7d483673328ce93a4af4284f67c8ee/packages/playwright/src/plugins/webServerPlugin.ts#L191) as we're using the `port` option.

### Additional context

[I am using Nexts experimental HTTPs for local development](https://nextjs.org/docs/app/api-reference/next-cli#https-for-local-development)

### Environment

```shell
System:
    OS: macOS 14.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 79.95 MB / 16.00 GB
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    pnpm: 8.14.3 - ~/.nvm/versions/node/v18.17.0/bin/pnpm
  IDEs:
    VSCode: 1.85.2 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.41.2 => 1.41.2
```

**Comment by mxschmitt** [comment]
Looks like your repository is private. We have an option to ignore HTTPS errors for the webServer option. It would look like this:

```ts
import { defineConfig } from '@playwright/test';

export default defineConfig({
  webServer: {
    command: 'npm run start',
    url: 'http://127.0.0.1:3000',
    reuseExistingServer: !process.env.CI,
    stdout: 'ignore',
    stderr: 'pipe',

    ignoreHTTPSErrors: true,
  },
});
```

I took this opportunity to improve our doc a bit more, since this option was not really visible. https://github.com/microsoft/playwright/pull/29490

**Comment by JohnMarsden24** [comment]
> ```ts
> ignoreHTTPSErrors: true,
> ```

Ah thank you @mxschmitt that's done it, and sorry I made my repo public and just tried it. Thank you for updating the docs too!
