### ISSUE TITLE
How to check the accessibility of an element with nth

### ISSUE THREAD

**Issue by jiz17043** [microsoft/playwright#29480]
I have an element in the page using locator like this 
page.locator('div.container').nth(1)
I wonder how could I check the accessibility of such element using include

- [X] I understand

**Comment by mxschmitt** [comment]
We recommend using axe for that: https://playwright.dev/docs/accessibility-testing

What specific feature are you looking for?

**Comment by mxschmitt** [comment]
Sounds more like a bug report for the `@axe-core/playwright` library than to us. I recommend filing it at https://github.com/dequelabs/axe-core-npm for further assistance.
