### ISSUE TITLE
[Bug]: page.evaluate shows websocket as a empty object in window object.

### ISSUE THREAD

**Issue by MehmetCanBOZ** [microsoft/playwright#29497]
### Version

1.41.2

### Steps to reproduce

In my source code, I register the WebSocket to the window object, then I want to get the WebSocket object with the playwright page.evaluate function. But this object comes as an empty object, not as a WebSocket.

**//source code**
```
const PLAYWRIGHT_LIVE_MAP_SOCKET_URL = 'ws://localhost:4040';

const connectws =() => {
  const liveSocket = new WebSocket(
     isPlaywrightEnv ? 
      PLAYWRIGHT_LIVE_MAP_SOCKET_URL :
       config.liveSocketUrl
    );

   window.liveSocket = liveSocket;

   liveSocket.onmessage = (event) => {
      setState(JSON.parse(event.data));
   };
   liveSocket.on("close", () => {
        console.log("the client has connected");
    });
    liveSocket.onerror = function () {
        console.log("Some Error occurred")
    }
  window.abc={a:1,b:2,c:3}
}
```

// webscoket-server for mocking message

```
const WebSocketServer = require('ws');
 
const wss = new WebSocketServer.Server({ port: 4040 })

wss.on("connection", ws => {
    ws.on("message", data => {
       ws.send(JSON.stringfy(data))
    });

    ws.onerror = function () {
        console.log("Some Error occurred")
    }
});
```

**// playwright code**

```
 test('should render map and markers location correct', async ({ page }) => {
    const liveSocket = await page.evaluate('window.liveSocket');
    const abc = await page.evaluate('window.abc');

    console.log('liveSocket :', liveSocket); // {}
    console.log('abc :', abc); // {a:1,b:2,c:3}

    /* use liveSocket for the mocking
     liveSocket.send({
      type:"type",
      data: data
     })
    */
    
  });
```

Why does it happen, if I add the object to the window it gives the correct result. But When I add Websocket to the window, it gives me an empty object. I will use window.liveSocket to send socket messages to mock the WebSocket with run WebSocket-server from outside the source code.

### Expected behavior

page.evaluate gives correct WebSocket object in window.

### Actual behavior

page.evaluate gives the correct empty object in window.

### Environment

```shell
System:
   Playwright Version: [v1.41.2]
   Operating System: [macOS 14.1.1]
   Browser: [Chromium]
```

**Comment by mxschmitt** [comment]
This is expected. You are trying to serialise a class (WebSocket instance) from the browser to Node.js - this won't work.

What you can do instead if you want to get the WebSocket messages from inside the page into your Node.js world, you can expose a function and call this from your browser JavaScript: https://playwright.dev/docs/api/class-browsercontext#browser-context-expose-function

See here for more information: https://playwright.dev/docs/evaluating

**Comment by mxschmitt** [comment]
You can do e.g.:

```ts
await page.addInitScript(()=> {
  window.Playwright = true;
});
```

**Comment by MehmetCanBOZ** [comment]
Thanks for your support.
