### ISSUE TITLE
[Feature]: Ability to add custom html report names

### ISSUE THREAD

**Issue by cctui-dev** [microsoft/playwright#29496]
### 🚀 Feature Request

Having the ability to define a custom file name for a junit xml report for a test run is very powerful, especially when chaining test runs or adding a timestamp.
By having an existing directory and then renaming the file with each test run, it allows us easily collate (and then merge) multiple junit test reports into one report.

The ability to create custom file names for the html report (other than index.html) would be just as powerful.
We are able to create custom directory names, but would like to create a directory of historical reports.

We would like a new feature where it is possible to add a custom file name (such as a timestamp) on the html report in a similar manner to the junit xml report.

### Example

`reporter: [['html', { outputFile: 'my-html-report.html' }]],`

Or 

``reporter: [['html', { outputFolder: 'custom-reports', outputFile: `${timeStamp}.html` }]],``

### Motivation

Being able to use a custom filename for the html report will allow us to create a directory of historical reports based on variables such as time, date, test run etc.

**Comment by mxschmitt** [comment]
A HTML Report is does not only contain a single html file, it (can) also contain traces and other resources like videos, screenshots etc. which are added during a test-run.

If you want to merge different test-results, we recommend this: https://playwright.dev/docs/test-sharding#merge-reports-cli

If you want to have reports with history, we recommend storing a separate HTML report directory in each folder.

Would that work for you?

**Comment by cctui-dev** [comment]
I think it might yes. Thanks so much!
