### ISSUE TITLE
[Bug]: Clipboard permissions in Chrome not working unless set in defaultConfig

### ISSUE THREAD

**Issue by zuzanna-maria** [microsoft/playwright#29509]
### Version

1.40.0

### Steps to reproduce

Ran into a problem while testing copy/paste functionality in Chrome. When running Playwright tests with Browserstack, on the Browserstack version of Chrome, copy/paste works correctly. However, copy/paste does not work when running Playwright locally. I have tried to set the appropriate permissions in the following ways:

- In `projects`:

```
name: "chrome@latest:OSX Ventura",
      use: {
        permissions: ["clipboard-read", "clipboard-write", "notifications"],
        contextOptions: {
          locale: 'en-GB',
          permissions: ['clipboard-read', 'clipboard-write']
        },
        locale: 'en-GB',
      },

```

- When instantiating the context:

```
  context = await browser.newContext(testInfo.project.use, { permissions: ["clipboard-read", "clipboard-write"] });

```

- Granting context permissions:

```
  await context.grantPermissions(["clipboard-read", "clipboard-write"] )

````

However, it seems to only work when set in `defineConfig`. This is not feasible in my use case, as I also run tests on Firefox, and when the permissions are set for all tests by default, an error appears as FF does not use those permissions.

### Expected behavior

Setting clipboard permissions in `projects` or when instantiating context in the test file should work for 

### Actual behavior

Setting permissions for Chrome doesn't work unless done in `defineConfig`.

### Environment

```shell
System:
    OS: macOS 12.7.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 183.16 MB / 8.00 GB
  Binaries:
    Node: 21.2.0 - ~/node_modules/.bin/node
    npm: 9.5.0 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.40.0 => 1.40.0 
    playwright-core: 1.33 => 1.33.0
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template / we need a clear reproduction in order to look at issues like that. Self-contained with actual/excepted outcomes. Please re-file, thanks for your understanding.
