### ISSUE TITLE
[Feature]: UI Mode - ability to go up and down the stack trace in the source tab (feature parity with trace viewer)

### ISSUE THREAD

**Issue by gal-checksum** [microsoft/playwright#29500]
### 🚀 Feature Request

In the trace viewer, in the source tab, I can go up and down the stack trace to view the source of different functions.

![CleanShot 2024-02-14 at 15 52 34](https://github.com/microsoft/playwright/assets/114691635/e6b26838-5282-4fb9-b97e-f2447c6b2772)

However, this feature is not available in UI mode:
![CleanShot 2024-02-14 at 15 53 51](https://github.com/microsoft/playwright/assets/114691635/93e8736f-d246-42c3-b31b-4e0d09e533e3)

Can we implement it?

### Example

When a function fails, you can explore the source of the full stack. Maybe the error comes from a higher level function

### Motivation

Easier to debug tests + feature parity with trace viewer

**Comment by mxschmitt** [comment]
I can reproduce, looks like a bug.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/29558, looks intentional.
