### ISSUE TITLE
[Bug]: Error: test file "childTest.spec.ts" should not import test file "parentTest.spec.ts"

### ISSUE THREAD

**Issue by zakwear** [microsoft/playwright#29502]
### Version

1.41.2

### Steps to reproduce

Test fixtures that depend on each other in a linear chain work as expected, but generate import errors when running npx playwright test and UI Mode.

Reproduction:

1. Clone this codesandbox: https://codesandbox.io/p/devbox/young-sun-fmn754
2. cd to testing, run npx playwright test --ui-port=8080 --ui-host=0.0.0.0
3. Click on the step2.spec.ts and step3.spec.ts in UI mode.
4. See these errors:

![Screenshot from 2024-02-14 17-20-06](https://github.com/microsoft/playwright/assets/55545774/e9d34b1e-10dd-4f33-9d33-935d2fdd1d3f)
![Screenshot from 2024-02-14 17-20-21](https://github.com/microsoft/playwright/assets/55545774/61f9ae1a-1d57-4043-a668-8c7068664ff4)

Or run outside of ui mode.

EDIT: Screenshots were wrong.

### Expected behavior

I expected no import errors.

### Actual behavior

Import errors on test fixtures that work as expected.

### Environment

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 21.65 GB / 62.50 GB
    Container: Yes
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.11.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.41.2 => 1.41.2
```

**Comment by zakwear** [comment]
Maybe test fixtures aren't meant to be chained this way, but it is convenient. The client can mutate state in the fixture, inheriting the state left off from parent test fixtures, and let the test function only do evaluation.

We currently have to have a separate class TestActions.ts is colocated with each spec.ts, that manually runs the functions of parent tests for each spec, outside of fixtures. 

So:
step1.spec.ts
TestActions1.ts contains functions for all actions that change state for the step1.spec.ts 
step2.spec.ts
TestActions2.ts //runs TestActions1.runAll()
step3.spec.ts
TestActions3.ts //runs TestActions2.runAll()

Using fixtures directly is easier to maintain.

**Comment by mxschmitt** [comment]
You need to move the fixtures out into their own separate file to make it work, this is by design: https://github.com/mxschmitt/pw-issue-29502/commit/bc453fd7e180290d7d442e21c237aef23728d31f

Would that work for you? Note, that this does not influence / create dependencies between tests, only fixtures.

**Comment by zakwear** [comment]
Yes, that works!

I did try that, but wasn't sure why a separate fixture.ts file was acceptable, and the other configuration not.

Thank you!!
