### ISSUE TITLE
[Question] How to add a base implementation for custom config option

### ISSUE THREAD

**Issue by rkhomi** [microsoft/playwright#29508]
### Please do not submit this issue.

- [X] I understand

**Comment by rkhomi** [comment]
I want to console log custom mailUrl option in each test, but getting an error, is there a way to do this

`Fixture "mailUrl" references itself, but does not have a base implementation.
"Cannot read properties of null (reading 'settings')"
`

```
export const test = base.extend<Fixtures & CustomConfigOptions>({
	mailUrl: [
		async ({ mailUrl }, use) => {
			console.log(mailUrl);
			process.env.MAIL_URL = `${mailUrl}`;
			await use(mailUrl);
		},
		{ option: true },
	]
})
```

```
projects: [
		{
			name: 'local',
			use: {
				...devices['Desktop Chrome'],
				isMobile: false,
				viewport: { width: 1920, height: 1080 },
			},
		}]
```

**Comment by mxschmitt** [comment]
Please use a bug template to provide a self-contained reproduction. Thank you.
