### ISSUE TITLE
[Docs]: Section "Getting Code" in Contributing docs is missing some steps

### ISSUE THREAD

**Issue by JonahKK** [microsoft/playwright#29518]
### Page(s)

https://github.com/microsoft/playwright/blob/main/CONTRIBUTING.md#getting-code

### Description

I wanted to try to run the Playwright repo locally to test some settings. I was following the Contributing docs, but despite doing precisely as described in "Getting Code" section I cannot run the project.
I'm using:
```
node: v16.15.1
npm: 9.3.0
```
According to docs that should be alright.
Issue is with building. I get an error:
```
playwright % npm run build

> playwright-internal@1.42.0-next build
> node utils/build/build.js

==== Running npm ci --save=false --fund=false --audit=false in /Users/jonah/Developer/original_playwright/playwright/tests/playwright-test/stable-test-runner
npm ERR! code ERR_FS_EISDIR
npm ERR! syscall rm
npm ERR! path /Users/jonah/Developer/original_playwright/playwright/tests/playwright-test/stable-test-runner/node_modules/.bin
npm ERR! errno 21
npm ERR! Path is a directory: rm returned EISDIR (is a directory) /Users/jonah/Developer/original_playwright/playwright/tests/playwright-test/stable-test-runner/node_modules/.bin
```

**Comment by mxschmitt** [comment]
We run all our tests on Windows see here: https://github.com/microsoft/playwright/actions/runs/7921356763/job/21626478146

These steps look the same from a brief look. Have you done `npm ci` before?

Also I'd try updating to Node.js 20, which is the latest LTS.

**Comment by JonahKK** [comment]
I was testing on MacOS, but I have tried with updated node (18) and I was able to setup the environment. Added PR with small adjustment in the docs: https://github.com/microsoft/playwright/pull/29547
