### ISSUE TITLE
[Bug]: Playwright disregarding the value 0 when filling in the field with value 02/2029

### ISSUE THREAD

**Issue by thiagosouza10** [microsoft/playwright#29511]
### Version

1.41.2

### Steps to reproduce

Repository is private to the company

### Expected behavior

It is expected that the PW does not remove the 0 when sending to the API

### Actual behavior

Could you help me, I have a problem filling out an imput field, visually the field is filled out correctly, with a value of 02/2029, but when clicking on the unlock button, the API request is removing the value 0, sending the date as 2/2029 generating an error in the test.

It is important to mention that this scenario only occurs in Playwright, testing manually in the browser or with another framework, this scenario does not occur. I created the same test with Cypress and it didn't generate the error.
When the test opens the login screen, I paused it, and manually following the browser that was opened, it gave the same error.

Screen element
<input aria-invalid="false" autocomplete="off" placeholder="mm/yyyy" type="text" class="MuiOutlinedInput-input MuiInputBase-input MuiInputBase-inputSizeSmall MuiInputBase-inputAdornedEnd css-b52kj1" value="" id="mui-7">

API request log
{"cvv":"xxx","pin":"xxx","card_expiration_date":"2/2029"}

Response
{
  "code": 40456,
  "description": "Invalid date",
  "error": true
}

Information
Playwright Version: 1.41.2
Browser: Any error occurs
![tela](https://github.com/microsoft/playwright/assets/141513753/de497a32-edf3-4c3f-956b-bb83ac7a83f4)
![script](https://github.com/microsoft/playwright/assets/141513753/23dd17de-b1b8-4dae-8b70-4201c6370345)

### Environment

```shell
Windows 11, Node: 16.16.0
```

**Comment by mxschmitt** [comment]
We can unfortunately triage only issues with a self-contained minimal reproduction. Please re-file with clear reproductions steps as per the issue template. Thanks for your understanding.
