### ISSUE TITLE
[Bug]: VSCode plugin doesn't execute worker specific fixture

### ISSUE THREAD

**Issue by dsmeltz** [microsoft/playwright#29510]
### Version

1.41.2

### Steps to reproduce

- Create a worker fixture for authentication like the one in the documentation.
- Run a test from the Playwright Test for VSCode plugin

### Expected behavior

I expect that the worker authentication fixture would be run at the beginning of the group of tests requested to be run via the Playwright Test for VSCode plugin.

### Actual behavior

The worker fixture is not being run.

### Additional context

The worker fixture is run as expected when executing the tests via the command line.

### Environment

```shell
System: Windows Server 2022
Playwright Test for VSCode (ms-playwright.playwright): 1.0.22
Node: 18.7.1
```

**Comment by mxschmitt** [comment]
I tried the following and it works for me, what am I doing different? Can you provide a self-contained reproduction?

```ts
import { test as base, expect } from '@playwright/test';

export const test = base.extend<{}, { account: void }>({
  account: [async ({ }, use, workerInfo) => {
    console.log('hello')
    await use();
  }, { scope: 'worker' }],
});

test('has title', async ({ page, account }) => {
  await page.goto('https://playwright.dev/');

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);
});

test('get started link', async ({ page, account }) => {
  await page.goto('https://playwright.dev/');

  // Click the get started link.
  await page.getByRole('link', { name: 'Get started' }).click();

  // Expects page to have a heading with the name of Installation.
  await expect(page.getByRole('heading', { name: 'Installation' })).toBeVisible();
});

```
