### ISSUE TITLE
[Bug]: Exit code 0 when crashes with out of memory error

### ISSUE THREAD

**Issue by lpk3nny** [microsoft/playwright#29528]
### Version

1.41.2

### Steps to reproduce

Run any big enough test suite with memory limit

```
NODE_OPTIONS='--max-old-space-size=200' playwright test -c playwright-ct.config.ts
echo $?
```

### Expected behavior

Crashes with exit code 133

### Actual behavior

Crashes with exit code 0

### Environment

```shell
macOS 14.3.1 arm64
node v16.17.1

@playwright/experimental-ct-react  1.41.2
@playwright/test 1.41.2
```

**Comment by mxschmitt** [comment]
We need clear reproduction in order to look into issues like this. We run our Playwright tests with @playwright/test which is "big" and has over 3500 tests, so this happens in some specific edge-case. Please re-file, thanks for your understanding.
