### ISSUE TITLE
[Bug]: SetExtraHttpHeaders overwrites some header requests

### ISSUE THREAD

**Issue by ZhouZhengCarlos** [microsoft/playwright#29521]
### Version

 1.38.0

### Steps to reproduce

I tried this approaches:
Using playwright.config.js
`
  projects: [
    {
      name: 'noUserAgent',
      use: { ...devices['Desktop Chrome'], extraHTTPHeaders: {'x-px-access-token' : 'someToken'} },
    },
`
Also setting it up on page:
`
await page.setExtraHTTPHeaders({'x-px-access-token' : 'someToken'});
`

### Expected behavior

Header must be added as a new header
![image](https://github.com/microsoft/playwright/assets/38266008/0a4049cc-e299-4de0-a778-4496d7295364)

### Actual behavior

The custom header overrides some network requests
![image](https://github.com/microsoft/playwright/assets/38266008/553d427d-86fe-4c72-a413-2398c4bdeda6)

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
    Memory: 2.76 GB / 15.69 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.85.2 - C:\Users\czhou\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.38.0 => 1.38.0
    playwright: ^1.37.1 => 1.38.0
```

**Comment by yury-s** [comment]
Please provide a self-contained repro that we could run locally to see the problem.

**Comment by yury-s** [comment]
Please file a new bug with a repro.
