### ISSUE TITLE
[Bug]: Permissions not set when using `channels` for Chromium browsers

### ISSUE THREAD

**Issue by dacloutier-logmein** [microsoft/playwright#29527]
### Version

1.40.1

### Steps to reproduce

1- create a browser fixture, worker scoped

```Typescript
browser: [async ({ }, use, =>{
            let browser
            // reproduced with `chrome` / `chrome-beta`
            browser = await chromium.launch({ channel: 'msedge' })    
            await use(browser)
        },
        { scope: 'worker' },
    ]
```

Create context worker fixture:
```Typescript
workerContext: [
      async ({ browser }, use) => {
          const permissions = ['camera', 'microphone', 'clipboard-read']
    browser.newContext({
            storageState: 'storageState.json',
            permissions,
          })
          
      await use(workerContext)
      await workerContext.close()
    },
    { scope: 'worker', auto: true },
    ],
```

Then open a page and navigate in HEADLESS mode to any place that would require those permissions. (In our case it's a WebRTC app)

### Expected behavior

Should behave like using the default `chromium` channel (as if not provided)

### Actual behavior

The website / app will not be able to access the required permissions.

excerpt form the console log if we try to access our WebRTC app:

```
ERROR Error: Uncaught (in promise): Error: Failed to obtain device permissions
Error: Failed to obtain device permissions
    at t.BrowserDevicePermissionManager._acquirePermissions
```

### Additional context

I reproduced with channels other than `msedge` => `chrome` and `chrome-beta`  were also suffering from this issue.

### Environment

```shell
System: 
 Mac OS: 14.2.1 (23C71)

Node:
21.6.1

pnpm:
8.15.1

Playwright:
1.40.1
```

**Comment by yury-s** [comment]
I cannot reproduce it with simple example:

```js
import { expect, test, chromium } from "@playwright/test";

test("context permission", async ({ }) => {
  const browser = await chromium.launch({ channel: 'msedge', headless: false});
  const permissions = ['camera', 'microphone', 'clipboard-read']
  const context = await browser.newContext({permissions});
  const page = await context.newPage();
  await page.goto('https://www.w3schools.com/html/html5_geolocation.asp');
});
```

Please attach a self-contained repro that we could run locally to reproduce your issue.

**Comment by dacloutier-logmein** [comment]
Have you tried in headless mode ?

now that I come to think of it, it needed to be in headless mode to occur

**Comment by yury-s** [comment]
Works fine in headless too:

```js
test("context permission", async ({ }) => {
  const browser = await chromium.launch({ channel: 'msedge' });
  const permissions = ['camera', 'microphone', 'clipboard-read']
  const context = await browser.newContext({permissions});
  const page = await context.newPage();
  await page.goto('https://webrtc.github.io/samples/src/content/getusermedia/gum/');
  await page.getByRole('button', { name: 'Open camera' }).click();
});
```

Please share complete repro that we could run locally, we cannot act on this report without a repro.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
