### ISSUE TITLE
[Bug]:azure pipeline says "no tests found" for playwright typescripts but works fine locally 

### ISSUE THREAD

**Issue by dude0071** [microsoft/playwright#29542]
### Version

1.41.2

### Steps to reproduce

1.node install 
2. npm install -D @playwright/test@latest
3. setup the pipeline with the tests to be executed 
4. create the test file withe name sampleTest.spec.ts
5. folder path as follows for test -> src/sample.test/tests/sampleTest.spec.ts

### Expected behavior

running azure pipeline should detect the test and run the playwright tests 

### Actual behavior

Error: Playwright Test did not expect test() to be called here.
Most common reasons include:
- You are calling test() in a configuration file.
- You are calling test() in a file that is imported by the configuration file.
- You have two different versions of @playwright/test. This usually happens
  when one of the dependencies in your package.json depends on @playwright/test.

   at src/sample.test/tests/sample.spec.ts:3

  1 | import { test, expect } from '@playwright/test';
  2 |
> 3 | test('sample sql validation', async () => {
    |     ^
  4 |   // Test logic here
  5 |   // Ensure to connect to the database and execute your queries
  6 |

### Additional context

trigger:
- main

pool:
  name: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18'
  displayName: 'Install Node.js'
    
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(System.DefaultWorkingDirectory)/src/sample.test/'

- script: |
    npm install -D @playwright/test@latest
  displayName: 'Install Playwright'

- script: |
    npx playwright test
  displayName: 'Run Tests'
     
- publish: $(System.DefaultWorkingDirectory)/src/sample.test/tests/sampleTest.spec.ts
  artifact: playwright-report
  condition: always()

below is the playwright.config.ts

import { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  // Test files location
  testDir: './tests', // Path to the directory containing your test files
  
  // Other configuration options...
};

export default config;

sampleTest.spec.ts

import { test, expect } from '@playwright/test';

test('sql validation', async () => {
  // Test logic here
  // Ensure to connect to the database and execute your queries
  
  // Example:
  // await sql.connect(sqlConfig);
  // const output = await sql.query(selectQuery);
  
  // Assertions using expect()
  // Example:
  // expect(output.recordset[0].Process_Status).toEqual('E55');
  console.log("test try");
});

### Environment

```shell
Playwright Version: 1.41
Operating System: Ubuntu
Node.js version: v18.12.1
```

**Comment by gskierk** [comment]
1. Run `npm ci` in root directory.
2. Then run `npx playwright install --with-deps` to install browsers and its dependencies.
3. The run your tests with `npx playwright test`.

**Comment by mxschmitt** [comment]
Have you tried following the official getting-started? https://playwright.dev/docs/intro

**Comment by dude0071** [comment]
> 1. Run `npm ci` in root directory.
> 2. Then run `npx playwright install --with-deps` to install browsers and its dependencies.
> 3. The run your tests with `npx playwright test`.

i tried this but still see the same error 

trigger:
- main

pool:
  name: ubuntu-latest-publix

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20'
  displayName: 'Install Node.js'

- script: |
    npm config set registry "https://pkgrepo.publix.com/repository/npm-group/"
    npm ci
  displayName: 'npm ci'
  workingDirectory: '$(System.DefaultWorkingDirectory)src/sample.test/tests/'

- script: |
    npx playwright install --with-deps
  displayName: 'Install Playwright Dependencies'
  workingDirectory: '$(System.DefaultWorkingDirectory)src/sample.test/tests/'

- script: |
    npx playwright test
  displayName: 'Run Tests'
     
- publish: $(System.DefaultWorkingDirectory)src/sample.test/tests/
  artifact: playwright-report
  # always create the artifact, this is useful for debugging failed tests
  condition: always()


**error**

npm WARN exec The following package was not found and will be installed: playwright@1.41.2
Error: Playwright Test did not expect test() to be called here.
Most common reasons include:
- You are calling test() in a configuration file.
- You are calling test() in a file that is imported by the configuration file.
- You have two different versions of @playwright/test. This usually happens
  when one of the dependencies in your package.json depends on @playwright/test.

   at src/sample.test//tests/samplTest.spec.ts:3

  1 | import { test, expect } from '@playwright/test';
  2 |
> 3 | test('test trial', async () => {
    |     ^
  4 |   // Test logic here
  5 |   // Ensure to connect to the database and execute your queries
  6 |   

    at TestTypeImpl._currentSuite (/agent/_work/1/s/)/src/sample.test/node_modules/playwright/lib/common/testType.js:71:13)
    at TestTypeImpl._createTest (/agent/_work/1/s/)/src/sample.test/node_modules/playwright/lib/common/testType.js:77:24)
    at /agent/_work/1/s/)/src/sample.test/node_modules/playwright/lib/transform/transform.js:246:12
    at Object.<anonymous> (/agent/_work/1/s/)/src/sample.test/tests/sampleTest.spec.ts:3:5)
Error: No tests found

**Comment by dude0071** [comment]
> Have you tried following the official getting-started? https://playwright.dev/docs/intro

yes this works locally for me perfectly fine only via piipelize it says no tests found

**Comment by dude0071** [comment]
alternatively i tried using npm ci instead of npm install and i run into this error 

npm ERR! The `npm ci` command can only install with an existing package-lock.json or
npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
npm ERR! later to generate a package-lock.json file, then try again.
npm ERR! 

here is the pipeline for the above error i received . 

trigger:
- main

pool:
  name: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18'
  displayName: 'Install Node.js'
- script: npm ci
  displayName: 'npm ci'
- script: npx playwright install --with-deps
  displayName: 'Install Playwright browsers'
- script: npx playwright test
  displayName: 'Run Playwright tests'
  env:
    CI: 'true'

**Comment by gskierk** [comment]
You have misconfigured `testDir` in your `playwright.config.ts`.

**Comment by dude0071** [comment]
> You have misconfigured `testDir` in your `playwright.config.ts`.

so what should the directory path be for my project if the repo structure for example is like 
src/project/playwright/tests/sampleTest.spec.ts 
what should the playwright.config.ts test directory path look like ? 
  testDir: 'src/project/playwright/tests/,'  ??

**Comment by gskierk** [comment]
Could you just put a link to your repository?

**Comment by dude0071** [comment]
https://github.com/dude0071/playwright/tree/main/sampleTest

**Comment by dude0071** [comment]
@gskierk  this is the error im receiving on azure pipeline now with the repo shared

Error: Playwright Test did not expect test() to be called here.
Most common reasons include:
- You are calling test() in a configuration file.
- You are calling test() in a file that is imported by the configuration file.
- You have two different versions of @playwright/test. This usually happens
  when one of the dependencies in your package.json depends on @playwright/test.

   at src/sampleTests/tests/example.spec.ts:3

  1 | import { test, expect } from '@playwright/test';
  2 |
> 3 | test('has title', async ({ page }) => {
    |     ^
  4 |   await page.goto('https://playwright.dev/');
  5 |
  6 |   // Expect a title "to contain" a substring.

**Comment by dude0071** [comment]
any idea why i might still seeing these errors , they are the stock files directly from the example installed scripts . i diddnt change even single logic ,it all works fine in local but not in pipeline .

**Comment by dude0071** [comment]
issue is resolved closing the thread. thanks for support . 

here is the working pipeline i had to use . i was usiing incorrect directory command in task rather i had to use this . 

trigger:
- main

pool:
  name: ubuntu-latest
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18'
  displayName: 'Install Node.js'
- script: |
    cd src/projectsample/sampleTests/tests
    npm ci
    npx playwright install --with-deps
    npx playwright test
  displayName: 'Run Playwright Tests'
  env:
    CI: 'true'
