### ISSUE TITLE
[Question] Why doesn't filter() work narrowing the Locator?

### ISSUE THREAD

**Issue by cortosi** [microsoft/playwright#29546]
Hello guys!

I can't publish the code, but i wrote this html file that replicate the scenario: https://jsfiddle.net/3t5xqsgy/

Or this is a temporary page: https://coral-nanci-88.tiiny.site/

If you run this test (i used vscode with Live Server extension):

```
test('test-sidebar', async ({ page }) => {
    await page.goto("[http://127.0.0.1:5500/index.html"](http://127.0.0.1:5500/index.html%22))
    const site = new Site(page)
    await site.sidebar.clickLevOneItem("Lev1 item - 1")
})
```

using those Classes:
```

class Site {
    private readonly page: Page
    public readonly sidebar: SideBar

    constructor(page: Page) {
        this.page = page
        this.sidebar = new SideBar(this.page.locator(".sidebar"))
    }
}

class SideBar {
    public readonly baseNode: Locator

    constructor(baseNode: Locator) {
        this.baseNode = baseNode;
    }

    public async clickLevOneItem(name: string) {
        await this.baseNode.locator(".side-item_lev1")
            .filter({ has: this.baseNode.locator(".lev1-header", { hasText: name }) })
            .click()
    }
}
```

I don't understand if this is a bug or what.. but it's like the filter() method does not work.. 
But, if you pass the entire page to SideBar:
```

class Site {
    private readonly page: Page
    public readonly sidebar: SideBar

    constructor(page: Page) {
        this.page = page
        this.sidebar = new SideBar(page)
    }
}

class SideBar {
    public readonly baseNode: Page

    constructor(baseNode: Page) {
        this.baseNode = baseNode;
    }

     ...
}
```

The filter works and find the DOM object, then click it. 
But why if i narrow the class using Locator, without passing the entire page, it stops working? I don't get it.

If aynone can solve this enigma for me, it'd be appriciated.
Thank you 😄

**Comment by mxschmitt** [comment]
**Investigation:**

```ts
playwright.locator('.sidebar').locator('.side-item_lev1').filter({
  has: playwright.locator('.lev1-header', { hasText: 'Lev1 item - 2' })  
}).elements
```

returns 2 elements. While filtering with `has` should filter one out. Using `hasText` makes it work:

```ts
playwright.locator('.sidebar').locator('.side-item_lev1').filter({
  hasText: 'Lev1 item - 2',  
}).elements
```

**Comment by cortosi** [comment]
Hello Max,
Thank you for the answer.

> **Investigation:**
> 
> ```ts
> playwright.locator('.sidebar').locator('.side-item_lev1').filter({
>   has: playwright.locator('.lev1-header', { hasText: 'Lev1 item - 2' })  
> }).elements
> ```
> 
> returns 2 elements. While filtering with `has` should filter one out. Using `hasText` makes it work:

Why does this query return 2 elements? There is only one item named 'Lev1 item - 2' with class '.lev1-header'.

**Comment by mxschmitt** [comment]
In the console-api there was a bug, I created a patch in #29563 to fix it. For the normal usage, it works fine for me:

```ts
it('should work', async ({ page, server }) => {
  await page.goto('file:///Users/maxschmitt/Developer/playwright/test.html');
  console.log(await page.locator('.sidebar').locator('.side-item_lev1').filter({
    has: page.locator('.lev1-header', { hasText: 'Lev1 item - 2' })
  }).count());
});
```

Is the selector I'm using different to the one you are using?

**Comment by cortosi** [comment]
Yes it works with page, but why it doesn't if you save the sidebar subtree in a constant?

```
await page.goto('https://coral-nanci-88.tiiny.site/');

const sidebar: Locator = page.locator('.sidebar')

console.log(await sidebar.locator('.side-item_lev1').filter({
    has: sidebar.locator('.lev1-header', { hasText: 'Lev1 item - 2' })
}).count());
```
What's the difference with using the entire page? I don't get it

**Comment by mxschmitt** [comment]
Closing as per above.
