### ISSUE TITLE
[Feature]: add matcher .toContainURL()

### ISSUE THREAD

**Issue by OlegsHanins** [microsoft/playwright#29543]
### 🚀 Feature Request

we want to check current url contains specific sub string. It could be “toContainURL” matcher. 

### Example

Usage as
await expect(page).toContainURL(‘anything’);

So we can use it instead of “toHaveURL” with regular expresion.

### Motivation

We implemented such custom matcher internally and named it toContainURL so we use it and we think its looks better than toHaveURL with regular expression if we want to check substring.

When you read code it much esier to read than regular expression with toHaveURL.

We could try contribute into playwright if you think it worth it.

**Comment by gskierk** [comment]
If it is only your preference, then you can just add a custom matcher to your code.

- https://playwright.dev/docs/test-assertions#add-custom-matchers-using-expectextend

**Comment by OlegsHanins** [comment]
> If it is only your preference, then you can just add a custom matcher to your code.
> 
> * https://playwright.dev/docs/test-assertions#add-custom-matchers-using-expectextend

Yes I know its only our preference and its suggestion. Yes we already do it on our level. That what I said initially in Motivation section.

Its almost same thing as `await expect(locator).toContainText()` and `await expect(locator).toHaveText()` when we can use method more explicit way. It more nice to have.
