### ISSUE TITLE
[Feature]:  Custom  the HTML report to show graph & legend for pass/fail/skip/flaky tests

### ISSUE THREAD

**Issue by nitzanRescana** [microsoft/playwright#29552]
### 🚀 Feature Request

Will be a good idea to have the option to add graph (pie/chart/line .. ) to the HTML report.  it's not suppose to be big develop and it can make it a lot easier for managers to view the HTML coming with the playwright.  

### Example

then like in other reports in the playwright.config.ts you can add graph:true/false  , type:pie/line/chart etc.. 

### Motivation

as of now we use allure for the automation developers and HTML for Managers, then we need to run another JS on the HTML to generate this graph.   with this feature the HTML can be more powerfull for managers to view without need to use 3rd party.

**Comment by mxschmitt** [comment]
Could you elaborate a bit more into what kind of graph you are interested in? Do you want to see how many % of the tests were failing / passing etc.?

**Comment by AlexK-ai** [comment]
Adding my upvoting regarding this one. 
To see a similar PIE charts report - will be a great idea.
Something like that:
![image](https://github.com/microsoft/playwright/assets/158454548/cce5d159-ba8b-4695-a89e-5f868debb3c4)

**Comment by nitzanRescana** [comment]
And add the legend too :
![Screenshot 2024-02-19 at 10 36 47](https://github.com/microsoft/playwright/assets/135516467/5ef5b63d-eae9-4926-8485-a751d7f81186)

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/27786
