### ISSUE TITLE
[Bug]: Unable to do actions in Firefox browser using JavaScript playwright

### ISSUE THREAD

**Issue by manojkumar3101** [microsoft/playwright#29556]
### Version

1.41.2

### Steps to reproduce

I have been working on an automation project using Playwright JavaScript with the Cucumber framework. I've encountered an issue where I am unable to proceed with the "fill" action in the Firefox browser, while the same script runs correctly in Chrome and Edge browsers.

### Expected behavior

I expect to fill the field correctly.

### Actual behavior

A  fill action is not working fine  

### Additional context

await pageFixture.page.locator("//input[@formcontrolname='min_quantum']").fill(minQuantumValue1);

### Environment

```shell
OS: windows11 

Binaries:
  Node: 20.9.0
  npm: 10.2.0
npmPackages:
  @playwright/test: 1.41.2
```

**Comment by mxschmitt** [comment]
We need clear reproduction steps in order to look into issues like this. Please re-file with a self-contained minimal reproduction. Thanks for your understanding!
