### ISSUE TITLE
[Bug]: Playwright: Missing official support for Fedora - Incorrect fallback message and dependency handling

### ISSUE THREAD

**Issue by khaimed** [microsoft/playwright#29559]
### Version

1.41.2

### 1. System Setup:
- **Fedora version:** 39
- **Playwright version:** 1.41.2
- **Installed Playwright using:** `npm init playwright`
### 2. Test Execution:
- **Ran the following command:** `npx playwright test`
- **Observed the following error message:**
```bash
Error: browserType.launch:
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libicudata.so.66                                 ║
║     libicui18n.so.66                                 ║
║     libicuuc.so.66                                   ║
║     libjpeg.so.8                                     ║
║     libwebp.so.6                                     ║
║     libflite.so.1                                    ║
║     libflite_usenglish.so.1                          ║
║     libflite_cmu_grapheme_lang.so.1                  ║
║     libflite_cmu_grapheme_lex.so.1                   ║
║     libflite_cmu_indic_lang.so.1                     ║
║     libflite_cmu_indic_lex.so.1                      ║
║     libflite_cmulex.so.1                             ║
║     libflite_cmu_time_awb.so.1                       ║
║     libflite_cmu_us_awb.so.1                         ║
║     libflite_cmu_us_kal16.so.1                       ║
║     libflite_cmu_us_kal.so.1                         ║
║     libflite_cmu_us_rms.so.1                         ║
║     libflite_cmu_us_slt.so.1                         ║
║     libpcre.so.3                                     ║
║     libffi.so.7                                      ║
╚══════════════════════════════════════════════════════╝
```
### 3. Dependency Installation Attempt:

- **Ran the following command:** `npx playwright install-deps`
- **Encountered an error:** `Failed to install browser dependencies`
### 4. Playwright Installation Attempt:

- **Ran the following command:** `npx playwright install`
- **Observed multiple warnings:** `BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.`

### Expected behavior

- Playwright should launch the requested browsers (webkit, chromium, etc.) without encountering any missing dependency errors.
- Playwright tests should execute successfully on my Fedora system.

### Actual behavior

- Playwright fails to launch browsers due to missing libraries.
- The error message lists specific missing libraries needed for browser functionality.
- Attempting to install dependencies manually or through `npx playwright install-deps` fails.
- Installing Playwright with `npx playwright install` triggers warnings about using an unsupported fallback build.

### Additional context

- I understand that Fedora is not officially supported by Playwright, but I wanted to see if it could still be used with some effort.
- I did not create any custom code for this test; I only used the basic structure generated by npm init playwright.
- I am hoping to contribute to improving Playwright's compatibility with Fedora or at least provide guidance for other users facing similar issues.

### Environment

```shell
System:
    OS: Linux 6.7 Fedora Linux 39 (Cinnamon)
    CPU: (8) x64 Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz
    Memory: 8.01 GB / 15.53 GB
    Container: Yes
  Binaries:
    Node: 20.10.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.2.3 - /usr/bin/npm
  IDEs:
    VSCode: 1.86.2 - /usr/bin/code
  Languages:
    Bash: 5.2.26 - /usr/bin/bash
```

**Comment by ALRubinger** [comment]
Ran into same issue tonight - appreciate y'all, maintainers. Would be great to get this in Fedora.

**Comment by wencan** [comment]
Firefox can be installed on Fedora 40.

**Comment by Forceres** [comment]
> Firefox can be installed on Fedora 40.

How it can be installed for playwright?

**Comment by wwk-github** [comment]
I've used:

```
sudo dnf install -y \
    libicu \
    libjpeg-turbo \
    libwebp \
    flite \
    pcre \
    libffi
```

The 'playwright install' complains but seems to be working (try runnng `playwright codegen https://www.nasa.gov/`)

```
playwright install        
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
Playwright Host validation warning: 
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libicudata.so.66                                 ║
║     libicui18n.so.66                                 ║
║     libicuuc.so.66                                   ║
║     libjpeg.so.8                                     ║
║     libwebp.so.6                                     ║
║     libpcre.so.3                                     ║
║     libffi.so.7                                      ║
╚══════════════════════════════════════════════════════╝
```

**Comment by Etherdrake** [comment]
> playwright codegen https://www.nasa.gov/

Can confirm this works on Fedora release 41 (Forty One).

**Comment by pskopek** [comment]
Here is the complete setup for [Fedora 41](https://gist.github.com/pskopek/de9d79cf0511839dd5c97703be5cc624)

**Comment by jeppester** [comment]
Disappointing that only debian based linuxes are supported. "Major investment" or not, such an investment should not be an issue for a company the size of MS.

This lack of support really sours me on using playwright.

**Comment by AviVahl** [comment]
@mxschmitt with Fedora 42 now being available in WSL2, perhaps now would be a good time to reconsider? :)

**Comment by khaimed** [comment]
Just a question, does this mean it's available in Fedora 42 and not just in WSL logically?

**Comment by AviVahl** [comment]
@khaimed Chromium and Firefox work ootb when playwright is used in Fedora 42. WebKit does not.

Users can now install Fedora 42 in WSL2 for those still using Windows, so maybe now Microsoft might consider officially supporting Fedora in playwright. That's what I meant.

**Comment by khaimed** [comment]
@AviVahl Thanks for the great work! Chromium and Firefox run perfectly on Fedora 42 after system upgrade, but WebKit still needs manual fixes. As a Fedora user (not using Windows), it would be awesome to see Fedora fully supported like Debian/Ubuntu — especially for WebKit. It’s so close to perfect!
Thanks again! 🙏🏻

**Comment by AviVahl** [comment]
@khaimed I cannot take credit for this useful project. I'm just another Fedora user asking Microsoft to reconsider. I agree it's close to getting there. 👍

**Comment by khaimed** [comment]
Big thanks legend 🙏🏻
I know it's challenging but for the future of this project it can be possible 🤠.

**Comment by tokisuno** [comment]
> [@AviVahl](https://github.com/AviVahl) Thanks for the great work! Chromium and Firefox run perfectly on Fedora 42 after system upgrade, but WebKit still needs manual fixes. As a Fedora user (not using Windows), it would be awesome to see Fedora fully supported like Debian/Ubuntu — especially for WebKit. It’s so close to perfect! Thanks again! 🙏🏻

How is it working for you? I installed it recently for FullStackOpen and it isn't loading my webpage, basically at all. If I go to errors, it just shows a highlight with nothing else. My tests are only passing/rendering VERY differently between firefox and chromium despite that not being the expected behaviour. :/

I will further expand by showing how broken it is for me.

<img width="760" height="777" alt="Image" src="https://github.com/user-attachments/assets/78cf30e2-6f98-4899-a0fe-5a4b692e3c9c" />

This is the right click context menu for me. I cannot open "Errors" as it will lead to it crashing.

**Comment by trane77** [comment]
> [@khaimed](https://github.com/khaimed) Chromium and Firefox work ootb when playwright is used in Fedora 42. WebKit does not.

I'm using Fedora 42 and getting this error:

```
❯ pnpx playwright install
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
You are using a frozen webkit browser which does not receive updates anymore on ubuntu20.04-x64. Please update to the latest version of your operating system to test up-to-date browsers.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
Playwright Host validation warning: 
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libicudata.so.66                                 ║
║     libicui18n.so.66                                 ║
║     libicuuc.so.66                                   ║
║     libjpeg.so.8                                     ║
║     libwebp.so.6                                     ║
║     libffi.so.7                                      ║
║     libx264.so                                       ║
╚══════════════════════════════════════════════════════╝
```

As suggested by another user, I installed the missing deps, but these versions are too old, maybe because it's falling back to ubuntu20.04-x64?

**Comment by adworacz** [comment]
Just reporting in that I have the playwright example (which is setup when Playwright is first installed) working just fine on Fedora 42 with 3 notes:

1. I did *not* run the `install-deps` step at installation. Didn't want the install running sudo commands on my behalf.
2. I manually installed `libicu74` using `sudo dnf install libicu74`. I likely had other dependencies already installed from other work I've done, so I'm not sure what else Playwright requires that I already had.
3. I disabled the `webkit` project in the `playwright.config.ts` file, since that seems to be the only browser that fails due to a missing `libjpeg-turbo8` dependency (even though `libjpeg-turbo` is installed).

Both headless and headed test runs succeeded just fine.

I've only messed around with it for about 10 minutes, but everything (aside from Webkit) seems to be working fine.

**Comment by AviVahl** [comment]
> Just reporting in that I have the playwright example (which is setup when Playwright is first installed) working just fine on Fedora 42 with 3 notes:
> 
>     1. I did _not_ run the `install-deps` step at installation. Didn't want the install running sudo commands on my behalf.
> 
>     2. I manually installed `libicu74` using `sudo dnf install libicu74`. I likely had other dependencies already installed from other work I've done, so I'm not sure what else Playwright requires that I already had.
> 
>     3. I disabled the `webkit` project in the `playwright.config.ts` file, since that seems to be the only browser that fails due to a missing `libjpeg-turbo8` dependency (even though `libjpeg-turbo` is installed).
> 
> 
> Both headless and headed test runs succeeded just fine.
> 
> I've only messed around with it for about 10 minutes, but everything (aside from Webkit) seems to be working fine.

webkit is the only browser that doesn't work OOTB due to missing libs. The rest (chromium and firefox) work fine, even without installing `libicu74`. True for Fedora 43 as well.

**Comment by puzanov** [comment]
Having the same issue on Fedora. Still getting this errors no matter what libraries I install via dnf on my machine. 
```
uv run playwright install 
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
You are using a frozen webkit browser which does not receive updates anymore on ubuntu20.04-x64. Please update to the latest version of your operating system to test up-to-date browsers.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
Playwright Host validation warning: 
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libicudata.so.66                                 ║
║     libicui18n.so.66                                 ║
║     libicuuc.so.66                                   ║
║     libjpeg.so.8                                     ║
║     libwebp.so.6                                     ║
║     libffi.so.7                                      ║
║     libx264.so                                       ║
╚══════════════════════════════════════════════════════╝
```

I've followed the suggestion above from @wwk-github and tested with the command `uv run playwright codegen https://www.nasa.gov/` - works well. Then I've tried to run my tests again and found this error: 
```
ERROR tests/e2e/test_admin_access.py::test_admin_access_success[chromium] - _pickle.PicklingError: Can't pickle local object <function LiveServer.start.<locals>.worker at 0x7f98f7924a90>
ERROR tests/e2e/test_admin_access.py::test_admin_access_denied_operator[chromium] - _pickle.PicklingError: Can't pickle local object <function LiveServer.start.<locals>.worker at 0x7f98f754df30>
ERROR tests/e2e/test_admin_access.py::test_admin_access_denied_anonymous[chromium] - _pickle.PicklingError: Can't pickle local object <function LiveServer.start.<locals>.worker at 0x7f98f73cb3d0>
ERROR tests/e2e/test_admin_access.py::test_admin_routes_security_scan[chromium] - _pickle.PicklingError: Can't pickle local object <function LiveServer.start.<locals>.worker at 0x7f98f72789e0>
```

Need to share that the same test suite works well with no playwright installation and running errors on both Debin 13 and the latest Arch Linux. This error happening only on Fedora 43. 

So googling this error with pickling local objects I've found this fix if you are using pytest for running playwright tests 
```python
import multiprocessing
import pytest

try:
    multiprocessing.set_start_method("fork", force=True)
except RuntimeError:
    pass
```

So again, installation is still in a semi broken phase but the tests with small fixes works well on Fefora. Not sure the relevance of this topic but hope it helps somebody digging the same issue with Playwright+Fedora43

**Comment by yshngg** [comment]
On Fedora Linux 43, **WebKit** is not working properly.

You can comment out the WebKit project in the _playwright.config.ts_ file to disable the **WebKit** browser or use `--browser` option to specify browser.

**Comment by agabor** [comment]
After manually installing the dependencies it works fine on Fedora 43 (within toolbox), using Chromium

**Comment by Giwayume** [comment]
Well, you have solidified my disinterest in using this software.

**Comment by ashstashem** [comment]
I would have loved to use playwrite on my system running fedora, but I guess i will stick to what works and use Puppeteer

**Comment by u5r0** [comment]
Fedora 36 and later, you must manually install system dependencies
```sh
sudo dnf install -y \
  nss \
  atk \
  at-spi2-atk \
  gtk3 \
  alsa-lib \
  libdrm \
  libxkbcommon \
  libXcomposite \
  libXdamage \
  libXrandr \
  mesa-libgbm \
  libXScrnSaver
```
```sh
npx playwright install chromium
```

**Comment by AviVahl** [comment]
> Fedora 36 and later, you must manually install system dependencies
> 
> sudo dnf install -y \
>   nss \
>   atk \
>   at-spi2-atk \
>   gtk3 \
>   alsa-lib \
>   libdrm \
>   libxkbcommon \
>   libXcomposite \
>   libXdamage \
>   libXrandr \
>   mesa-libgbm \
>   libXScrnSaver
> 
> npx playwright install chromium

that's not entirely correct.
on Fedora 43 (latest release atm), both Chromium and Firefox work **out-of-the-box**, without needing to install any additional system dependencies.
webkit doesn't.

**Comment by ivankorn** [comment]
For fedora 44 you need to install following packages
- [libicu74](https://kojipkgs.fedoraproject.org//packages/libicu74/74.2/3.fc43/x86_64/libicu74-74.2-3.fc43.x86_64.rpm) - note, the lower version, not the most recent coming by default.
- for the  `gstreamer` the rpm fusion packages are needed:
```
sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-44.noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-44.noarch.rpm

sudo dnf install gstreamer1-plugins-good gstreamer1-plugins-bad-free gstreamer1-plugins-bad-freeworld gstreamer1-plugins-ugly gstreamer1-plugins-ugly-free gstreamer1-plugin-libav
```
- for the `libjpeg-turbo8` it actually wants `libjpeg.so.8`
I had that one provided by `nsight-systems-2026.1.3-2026.1.3.243_261337792075v0-0.x86_64` coming from `cuda-fedora44-x86_64` nvidia's repo. So I just simlinked the lib with
```
ln -s /opt/nvidia/nsight-systems/2026.1.3/host-linux-x64/libjpeg.so.8 /usr/lib64/libjpeg.so.8
```
And now I can run tests on all browsers including mobile and desktop safari, chrome and firefox.

I hope that helps and it's a shame that the bug is closed, as adding just a few lines to setup readme is not so hard... 
What is hard is figuring out that yourself been left without any support from the main stream.
