### ISSUE TITLE
[Bug]: ERR_H2_OR_QUIC_REQUIRED for large multipart requests in app

### ISSUE THREAD

**Issue by Josef-Reichardt** [microsoft/playwright#29553]
### Version

1.41.1

### Steps to reproduce

1. clone repo https://github.com/Josef-Reichardt/playwright_upload_error_demo
2. run `yarn && yarn playwright install`
3. run `yarn dev` to start the demo app
4. open a second terminal and run `yarn test:e2e --headed` to start the test

### Expected behavior

The app should be able to send the same requests in the automated playwright test as it does in manual tests.

### Actual behavior

The app doesn't send the request and in the browser console I got the error `ERR_H2_OR_QUIC_REQUIRED`.

### Additional context

The app works fine if i use it manually. The error only occurs if playwright controlls the browser.

I have also tested it with the browser from playwright (`~/.cache/ms-playwright/chromium-1097/chrome-linux/chrome`) and it works for manually tests with the same test files.

<img width="275" alt="screenshot" src="https://github.com/microsoft/playwright/assets/1203740/2cdcb12d-4b21-4bd3-be59-07fb1a2de87c">

### Environment

```shell
System:
  OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
  CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900HX
  Memory: 60.43 GB / 62.65 GB
  Container: Yes
Binaries:
  Node: 20.8.0 - ~/.nvm/versions/node/v20.8.0/bin/node
  Yarn: 1.22.19 - ~/.nvm/versions/node/v20.8.0/bin/yarn
  npm: 10.4.0 - ~/.nvm/versions/node/v20.8.0/bin/npm
IDEs:
  VSCode: 1.86.2 - /mnt/c/Users/reichardt/AppData/Local/Programs/Microsoft VS Code/bin/code
Languages:
  Bash: 5.0.17 - /usr/bin/bash
```

**Comment by yury-s** [comment]
The test you provided passes for me locally. [These lines](https://github.com/Josef-Reichardt/playwright_upload_error_demo/blob/356b3b244775e9e3fa55c3fcca42b653fada7a6b/e2e/vue.spec.ts#L24-L27)  where you delete the files after a random timeout while the browser may still be working on them look wrong to me.

**Comment by Josef-Reichardt** [comment]
Grml... Yes, you're right. I'm really sorry. I had a `page.pause()` before the `save` button click and then I always reached the three second timeout and the files was removed.

I will rewrite my test to remove the files afterwards and not in an async timeout function but I have already tested it with these lines commented out and it works.

Thanks for the hint!
