### ISSUE TITLE
[Bug]: `.toBeVisible({visible: false})` negates both conditions (visible and attached)

### ISSUE THREAD

**Issue by mikestopcontinues** [microsoft/playwright#29555]
### Version

1.41.1

### Steps to reproduce

```ts
expect(
  page.locator('.neverathing')
).toBeVisible({visible: false}); 
```

### Expected behavior

According to the [docs](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-be-visible), `.toBeVisible` has two properties. It tests that the locator has an element that is _attached_ AND _visible_.

However, when you set `{visible: false}`, it doesn't only negate the _visible_ check. It also negates the _attached_ check. This is not indicated in the docs.

I expect the test to assert that the element is attached AND NOT visible. After all, `.toBeHidden()` already tests for NOT visible OR NOT attached.

### Actual behavior

Currently, `.toBeVisible({visible: false})` is identical to `.toBeHidden()` and is contrary to the documentation.

### Additional context

I think that either the docs should be updated or the the behavior should be fixed.

### Environment

```shell
System:
    OS: macOS 14.2.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 17.68 GB / 96.00 GB
  Binaries:
    Node: 18.19.0 - ~/Library/Caches/fnm_multishells/17515_1708276455264/bin/node
    Yarn: 1.22.21 - ~/Library/Caches/fnm_multishells/17515_1708276455264/bin/yarn
    npm: 10.3.0 - ~/Library/Caches/fnm_multishells/17515_1708276455264/bin/npm
    pnpm: 8.13.1 - ~/Library/pnpm/pnpm
    bun: 1.0.26 - /opt/homebrew/bin/bun
  IDEs:
    VSCode: 1.86.2 - /usr/local/bin/code
  Languages:
    Bash: 5.2.26 - /opt/homebrew/bin/bash
  npmPackages:
    @playwright/test: 1.41.2 => 1.41.2 
    playwright: 1.41.2 => 1.41.2
```

**Comment by alexkurochka5** [comment]
and what about not.toBeVisible() is it the same as toBeHidden() as well?
also I think the topic starter is right about docs incorrectness since when I google 
'playwright toBeVisible({visible:false}) vs toBeHidden'
or
'playwright not.toBeVisible vs toBeHidden'
Gemini wrongly, as pointed here, describes that toBeVisible({visible:false}) and not.toBeVisible requires element to be present in DOM
