### ISSUE TITLE
[Bug]: WebKit hangs on permission pop-up to sending notifications

### ISSUE THREAD

**Issue by jczekaj3** [microsoft/playwright#29561]
### Version

1.41.2

### Steps to reproduce

Write any test for a page asking the user to send notifications and run the test in WebKit.

![safari-notifications-popup-on-www onet pl](https://github.com/microsoft/playwright/assets/137402374/43bf9cc3-75cc-4adb-ada0-6238f5664cfc)

### Expected behavior

Playwright automatically calls `await dialog.dismiss()`.

### Actual behavior

The test hangs.

### Environment

```shell
System:
  OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
  CPU: (8) x64 Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz
  Memory: 11.80 GB / 15.36 GB
  Container: Yes
Binaries:
  Node: 20.9.0 - /opt/sdk/node_20.9.0.1_x86_64/bin/node
  npm: 10.1.0 - /opt/sdk/node_20.9.0.1_x86_64/bin/npm
  bun: 1.0.26 - ~/.bun/bin/bun
Languages:
  Bash: 5.0.17 - /usr/bin/bash
npmPackages:
  @playwright/test: 1.41.2 => 1.41.2
  playwright: 1.41.2 => 1.41.2
```

**Comment by jczekaj3** [comment]
Note that

```js
page.on('dialog', async dialog => {
    console.log(dialog.message());
    await dialog.dismiss();
  });
```

does not work, while

```js
await context.grantPermissions(['notifications’])
```

throws an exception…

**Comment by jczekaj3** [comment]
It looks like `'notifications'` is not supported on WebKit:

https://github.com/microsoft/playwright/blob/31bd58f8f3cee1ece4838331f7614128a5581cab/packages/playwright-core/src/server/webkit/wkPage.ts#L1171-L1174

**Comment by mxschmitt** [comment]
Could you provide us a minimal reproducible? For me it says:

<img width="312" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/e0d2978d-94b3-409f-848b-3bce17cc37e3">

Maybe your site is using a different API.

**Comment by jczekaj3** [comment]
@mxschmitt You are right! It looks like the `window.safari.pushNotification.requestPermission()` is called

**Comment by jczekaj3** [comment]
I found call of `window.safari.pushNotification.requestPermission` somewhere in the minified JavaScript files on the page, but in WebKit used by Playwright `window.safari.pushNotification` is `undefined`. I need to check why the test hangs. Sorry for the lack of details
