### ISSUE TITLE
[Bug]: Next build of project very slow when run via VSCode extension and `webServer` configuration

### ISSUE THREAD

**Issue by tocaherge** [microsoft/playwright#29562]
### Version

1.41.2

### Steps to reproduce

1. Clone repo https://github.com/fullyherge/slow-playwright-repro
2. `npm install`
3. Run tests via `playwright-vscode` extension via Debug
4. Notice that the build gets stuck on "Collecting build traces ..." for a long time
5. Compare with a `npm run start:ci` run from terminal, or `npm run test`, which will be a lot faster

### Expected behavior

I expect the tests being run via the extension to be the same as tests being run from the terminal.

### Actual behavior

Tests run via the vscode extension take a long time to build the next application, which delays everything.

### Environment

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 71.11 MB / 16.00 GB
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v18.18.2/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.9.2 - ~/Library/pnpm/pnpm
  IDEs:
    VSCode: 1.86.1 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.41.2 => 1.41.2
```

**Comment by yury-s** [comment]
There is no 'test' script in the package and no playwright dependency.

**Comment by tocaherge** [comment]
@yury-s 
Forgot to push changes, sorry. Up now

**Comment by yury-s** [comment]
Running in debug mode disables some optimizations in v8 which may well result in slower execution. Performance of running from terminal is comparable to 'Run Test' not 'Debug Test'. Try changing your config like the following to disable debugging of the server:

```js
  webServer: {
    command: "time npm run start:ci",
    url: "http://127.0.0.1:6464",
    reuseExistingServer: false,
    timeout: 120 * 1000,
    env: {
      NODE_OPTIONS: '',
    }
  },
```

Does this make it faster?

**Comment by tocaherge** [comment]
That does make it faster. Thanks!
