### ISSUE TITLE
[Feature]: Allow passing optional URL to context.newPage()

### ISSUE THREAD

**Issue by tbrockman** [microsoft/playwright#29566]
### 🚀 Feature Request

Allow passing an optional (to preserve backwards compatibility) string URL as an argument to `context.newPage()` which would allow creating a new tab _without_ `about:blank` in navigation history and without needing a separate call to `page.goto()` afterwards. 

### Example

```javascript
const page = await context.newPage('https://example.com') // don't need to call to `.goto()`
// optionally, since we might want a mechanism the inspect the page response beyond any errors thrown (not sure if necessary)
const response = page.getResponse()
```

### Motivation

I have an extension that has different behavior based off of whether a received tab update event is a new tab being created (and navigating to a URL), or whether a tab update is an existing tab navigating to a new URL. Because the default behavior for `context.newPage()` [seems to be to create a tab to `about:blank` first](https://github.com/microsoft/playwright/blob/31bd58f8f3cee1ece4838331f7614128a5581cab/packages/playwright-core/src/server/chromium/crBrowser.ts#L375), I'm not able to test the first scenario (at least, not without some workaround--still learning what's available in Playwright).

This would also reduce two common function calls (for `context.newPage()` and then `page.goto()`), into one.

Would be happy to work on this if the feature would be accepted as described.

**Comment by yury-s** [comment]
> Because the default behavior for `context.newPage()` [seems to be to create a tab to `about:blank` first](https://github.com/microsoft/playwright/blob/31bd58f8f3cee1ece4838331f7614128a5581cab/packages/playwright-core/src/server/chromium/crBrowser.ts#L375), I'm not able to test the first scenario (at least, not without some workaround--still learning what's available in Playwright).

This is consistent with user<->browser interaction, the user first opens a new tab and then types in the url. The only case it is different is when a new tab is opened by existing page, e.g. when the user clicks on a link with `target=_blank`. Both of these cases are supported in playwright, you can listen to the new pages via [`context.on('page')`](https://playwright.dev/docs/api/class-browsercontext#browser-context-event-page) or [`page.on('popup')`](https://playwright.dev/docs/api/class-page#page-event-popup). Do these `page` events not work in your scenario?

**Comment by yury-s** [comment]
Closing this request as we are not planning to change the `newPage()` api.

**Comment by yury-s** [comment]
> Or when the user right-clicks a link and selects "Open in New Tab", or selects "Open in New Window", or uses a shortcut like middle mouse clicking...

All of these scenarios can be performed by executing Ctrl+click, Shift+click etc using Locator.click() with [modifiers](https://playwright.dev/docs/api/class-locator#locator-click-option-modifiers). You can listen for the new pages using the events I mentioned above.

**Comment by tbrockman** [comment]
Okay, I can see how that can be could be used to satisfy some of the state that I'm wanting to test, thanks for the link to the doc.

Is there anything similarly available to simulate the event of restoring a browser session? I would assume that this would also be equivalent to opening many pages and directly navigating to a given URL.

**Comment by rhyek** [comment]
This affects cases where a user clicks on a link in a different application than the browser, like a mail client.
