### ISSUE TITLE
[Bug]: Hover state triggers focus-visible style instead of true hover

### ISSUE THREAD

**Issue by michallbanas** [microsoft/playwright#29575]
### Version

1.41.2

### Steps to reproduce

1. Clone my repository: https://github.com/michallbanas/playwright-hover-example
2. npm install
3. npx playwright test --ui
4. Check the hover state step

### Expected behavior

Hovering over a element should trigger hover state. In the case from repository, the share button should be displayed on the right side of card. (see screenshots below)

### Actual behavior

Hovering over a card (in my case) applies a blue outline as if the card is focused. Compared to states in Chrome dev tool. 

### Additional context

Screenshots:

This is how it looks in PW test. 
![pw-test](https://github.com/microsoft/playwright/assets/63734693/872d3f15-4fe6-47a0-8b38-87b2ed7eaa98)

Focus-visible state in Chrome dev tool. 
![focus-visible](https://github.com/microsoft/playwright/assets/63734693/0c664ab1-629d-42a2-9360-b19b7ba9d47b)

Hover state in Chrome dev tool. 
![hover](https://github.com/microsoft/playwright/assets/63734693/5eafe3f9-fb4f-4020-a09b-d65f7a7946d3)

### Environment

```shell
System:
    OS: macOS 14.3
    CPU: (8) arm64 Apple M1 Pro
    Memory: 141.11 MB / 16.00 GB
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    bun: 1.0.26 - ~/.bun/bin/bun
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.41.2 => 1.41.2
```

**Comment by yury-s** [comment]
The element's blue border on the snapshot is Playwright Trace Viewer's highlight of the element on which the action was performed, there is also a red dot showing position of the cursor. The style of the highlight that Playwright uses (`style.outline = '2px solid #006ab1';`) in this particular cases is very similar to what you page has when the element is clicked. We can probably do something smart to avoid such style clashes or allow to hide highlight of the active element in the trace viewer, so far this is the first case where we see such problem though.

**Comment by yury-s** [comment]
We could draw the background highlight with a higher z-index.

**Comment by michallbanas** [comment]
@yury-s thank you for the answer 👍🏼  Different highlight style would be helpful. However, it also gives me a different result in the test (using hover) than in real interaction (or using :hover in dev tool). I don't get this share button circle (see screenshot) in PW. So I'm curious if the performed action in PW is somehow different compared to eg. :hover in chrome dev tool. 

![hover-card](https://github.com/microsoft/playwright/assets/63734693/3f660d25-b2b1-4296-ae20-dca70f568c4e)

**Comment by yury-s** [comment]
> So I'm curious if the performed action in PW is somehow different compared to eg. :hover in chrome dev tool.

Yes. Playwright moves mouse over the element which not only triggers :hover pseudo class but also triggers all DOM mouse events. The share image is added by javascript.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
