### ISSUE TITLE
[Bug]: some data returns empty object in window object

### ISSUE THREAD

**Issue by ahmadalasaad** [microsoft/playwright#29577]
### Version

latest

### Steps to reproduce

I get a window object using playwright typescript
this.page.evaluate(() => window.fbsads)
some data returns correct values like
fbsads.getZone()
but when I try to get a value that have initial value new Map()
it returns {}
fbsads.adSlots

### Expected behavior

I expected to get map has values 

### Actual behavior

{} empty object

### Additional context

I wait for load everything this.page.pause() and make sure we have the data by opening the dev tools manually and check the values I saw them , the data have correct values

### Environment

```shell
System:
mac os
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
