### ISSUE TITLE
implementation confusion about setting/retrieving _callbacks when send/receive event messages to/from CDP Server

### ISSUE THREAD

**Issue by davexiaostan** [microsoft/playwright#29571]
Sorry for ask here, pls feel free to move to more proper place

I am exploring one way to create an emulator(similar to weinre) of CDP Server for remote testing, and test with Playwright, while finding an interesting question about Playwright implementation, 

why field _callbacks in CRSession in [CRConnection.ts](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/chromium/crConnection.ts#L147) seems visible sometimes and invisible sometimes?
I tested with connectOverCDP

the below the logs I added, 
the main points are,  

ids(2,3,15) in _callbacks seem in one stack, 

while ids(4-14, 16) in _callbacks seem in another stack(these callbacks are set up after receiving attachedToTarget event), 

and these 2 stacks can not see each other

why is that? how does it work this way? but they both share the id generator, [_rawSend](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/chromium/crConnection.ts#L59)

the test with my CDP emulator is even worse, Playwright could receive results for methods, but the ids from 4-14 disappear completely from _callbacks and get [errors](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/chromium/crConnection.ts#L168), so suspending because can not resolve the promises.

I send Target.attachedToTarget from CDP Server when setAutoAttach is called(sync way).

Can someone from Playwright pls help?

Thanks very much

@pavelfeldman , noticed you did some work around these, can you pls share some ideas at your convenience?

SEND ► {"id":1,"method":"Browser.getVersion"}
(processid=86148)set _callbacks with id=1
(processid=86148)_callback has k=1
◀ RECV {"id":1,"result":{"protocolVersion":"1.3","product":"Chrome/121.0.6167.184","revision":"@057a8ae7deb3374d0f1b04b36304d236f0136188","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","jsVersion":"12.1.285.28"}}
(processid=86148)checking id=1
(processid=86148)_callback has k=1
delete id=1 from _callbacks
SEND ► {"id":2,"method":"Target.setAutoAttach","params":{"autoAttach":true,"waitForDebuggerOnStart":true,"flatten":true}}
(processid=86148)set _callbacks with id=2
(processid=86148)_callback has k=2
SEND ► {"id":3,"method":"Browser.setDownloadBehavior","params":{"behavior":"allowAndName","downloadPath":"/var/folders/p3/hb48kxq55sg7qks5d8p5qjnr0000gp/T/playwright-artifacts-riNtir","eventsEnabled":true}}
(processid=86148)set _callbacks with id=3
(processid=86148)_callback has k=2
(processid=86148)_callback has k=3
◀ RECV {"method":"Target.attachedToTarget","params":{"sessionId":"4E1C6867CFAC3FAAB27888605FA73913","targetInfo":{"targetId":"E121B54E11A02DF57F51B60A5F6DE639","type":"page","title":"test","url":"file:///Users/davexiao/work/repos/chii/test/demo.html","attached":true,"canAccessOpener":false,"browserContextId":"986EBE099263070145E03F05D9E38958"},"waitingForDebugger":false}}
(processid=86148)checking id=undefined
(processid=86148)_callback has k=2
(processid=86148)_callback has k=3
SEND ► {"id":4,"method":"Page.enable","sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)set _callbacks with id=4
(processid=86148)_callback has k=4
SEND ► {"id":5,"method":"Page.getFrameTree","sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)set _callbacks with id=5
(processid=86148)_callback has k=4
(processid=86148)_callback has k=5
SEND ► {"id":6,"method":"Log.enable","params":{},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)set _callbacks with id=6
(processid=86148)_callback has k=4
(processid=86148)_callback has k=5
(processid=86148)_callback has k=6
SEND ► {"id":7,"method":"Page.setLifecycleEventsEnabled","params":{"enabled":true},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)set _callbacks with id=7
(processid=86148)_callback has k=4
(processid=86148)_callback has k=5
(processid=86148)_callback has k=6
(processid=86148)_callback has k=7
SEND ► {"id":8,"method":"Runtime.enable","params":{},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)set _callbacks with id=8
(processid=86148)_callback has k=4
(processid=86148)_callback has k=5
(processid=86148)_callback has k=6
(processid=86148)_callback has k=7
(processid=86148)_callback has k=8
SEND ► {"id":9,"method":"Page.addScriptToEvaluateOnNewDocument","params":{"source":"","worldName":"__playwright_utility_world__"},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)set _callbacks with id=9
(processid=86148)_callback has k=4
(processid=86148)_callback has k=5
(processid=86148)_callback has k=6
(processid=86148)_callback has k=7
(processid=86148)_callback has k=8
(processid=86148)_callback has k=9
SEND ► {"id":10,"method":"Network.enable","sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)set _callbacks with id=10
(processid=86148)_callback has k=4
(processid=86148)_callback has k=5
(processid=86148)_callback has k=6
(processid=86148)_callback has k=7
(processid=86148)_callback has k=8
(processid=86148)_callback has k=9
(processid=86148)_callback has k=10
SEND ► {"id":11,"method":"Target.setAutoAttach","params":{"autoAttach":true,"waitForDebuggerOnStart":true,"flatten":true},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)set _callbacks with id=11
(processid=86148)_callback has k=4
(processid=86148)_callback has k=5
(processid=86148)_callback has k=6
(processid=86148)_callback has k=7
(processid=86148)_callback has k=8
(processid=86148)_callback has k=9
(processid=86148)_callback has k=10
(processid=86148)_callback has k=11
SEND ► {"id":12,"method":"Emulation.setFocusEmulationEnabled","params":{"enabled":true},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)set _callbacks with id=12
(processid=86148)_callback has k=4
(processid=86148)_callback has k=5
(processid=86148)_callback has k=6
(processid=86148)_callback has k=7
(processid=86148)_callback has k=8
(processid=86148)_callback has k=9
(processid=86148)_callback has k=10
(processid=86148)_callback has k=11
(processid=86148)_callback has k=12
SEND ► {"id":13,"method":"Emulation.setEmulatedMedia","params":{"media":"","features":[{"name":"prefers-color-scheme","value":"light"},{"name":"prefers-reduced-motion","value":"no-preference"},{"name":"forced-colors","value":"none"}]},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)set _callbacks with id=13
(processid=86148)_callback has k=4
(processid=86148)_callback has k=5
(processid=86148)_callback has k=6
(processid=86148)_callback has k=7
(processid=86148)_callback has k=8
(processid=86148)_callback has k=9
(processid=86148)_callback has k=10
(processid=86148)_callback has k=11
(processid=86148)_callback has k=12
(processid=86148)_callback has k=13
SEND ► {"id":14,"method":"Runtime.runIfWaitingForDebugger","sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)set _callbacks with id=14
(processid=86148)_callback has k=4
(processid=86148)_callback has k=5
(processid=86148)_callback has k=6
(processid=86148)_callback has k=7
(processid=86148)_callback has k=8
(processid=86148)_callback has k=9
(processid=86148)_callback has k=10
(processid=86148)_callback has k=11
(processid=86148)_callback has k=12
(processid=86148)_callback has k=13
(processid=86148)_callback has k=14
◀ RECV {"id":2,"result":{}}
(processid=86148)checking id=2
(processid=86148)_callback has k=2
(processid=86148)_callback has k=3
delete id=2 from _callbacks
SEND ► {"id":15,"method":"Target.getTargetInfo"}
(processid=86148)set _callbacks with id=15
(processid=86148)_callback has k=3
(processid=86148)_callback has k=15
◀ RECV {"id":3,"result":{}}
(processid=86148)checking id=3
(processid=86148)_callback has k=3
(processid=86148)_callback has k=15
delete id=3 from _callbacks
◀ RECV {"id":4,"result":{},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)checking id=4
(processid=86148)_callback has k=4
(processid=86148)_callback has k=5
(processid=86148)_callback has k=6
(processid=86148)_callback has k=7
(processid=86148)_callback has k=8
(processid=86148)_callback has k=9
(processid=86148)_callback has k=10
(processid=86148)_callback has k=11
(processid=86148)_callback has k=12
(processid=86148)_callback has k=13
(processid=86148)_callback has k=14
delete id=4 from _callbacks
◀ RECV {"id":5,"result":{"frameTree":{"frame":{"id":"E121B54E11A02DF57F51B60A5F6DE639","loaderId":"236784B5BF017403914072280D3818E7","url":"file:///Users/davexiao/work/repos/chii/test/demo.html","domainAndRegistry":"","securityOrigin":"file://","mimeType":"text/html","adFrameStatus":{"adFrameType":"none"},"secureContextType":"Secure","crossOriginIsolatedContextType":"NotIsolated","gatedAPIFeatures":[]}}},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)checking id=5
(processid=86148)_callback has k=5
(processid=86148)_callback has k=6
(processid=86148)_callback has k=7
(processid=86148)_callback has k=8
(processid=86148)_callback has k=9
(processid=86148)_callback has k=10
(processid=86148)_callback has k=11
(processid=86148)_callback has k=12
(processid=86148)_callback has k=13
(processid=86148)_callback has k=14
delete id=5 from _callbacks
SEND ► {"id":16,"method":"Page.createIsolatedWorld","params":{"frameId":"E121B54E11A02DF57F51B60A5F6DE639","grantUniveralAccess":true,"worldName":"__playwright_utility_world__"},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)set _callbacks with id=16
(processid=86148)_callback has k=6
(processid=86148)_callback has k=7
(processid=86148)_callback has k=8
(processid=86148)_callback has k=9
(processid=86148)_callback has k=10
(processid=86148)_callback has k=11
(processid=86148)_callback has k=12
(processid=86148)_callback has k=13
(processid=86148)_callback has k=14
(processid=86148)_callback has k=16
◀ RECV {"method":"Log.entryAdded","params":{"entry":{"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1708383594323.067,"url":"http://localhost:9222/scripts/launcher.js","networkRequestId":"85591.3"}},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)checking id=undefined
(processid=86148)_callback has k=6
(processid=86148)_callback has k=7
(processid=86148)_callback has k=8
(processid=86148)_callback has k=9
(processid=86148)_callback has k=10
(processid=86148)_callback has k=11
(processid=86148)_callback has k=12
(processid=86148)_callback has k=13
(processid=86148)_callback has k=14
(processid=86148)_callback has k=16
◀ RECV {"id":6,"result":{},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)checking id=6
(processid=86148)_callback has k=6
(processid=86148)_callback has k=7
(processid=86148)_callback has k=8
(processid=86148)_callback has k=9
(processid=86148)_callback has k=10
(processid=86148)_callback has k=11
(processid=86148)_callback has k=12
(processid=86148)_callback has k=13
(processid=86148)_callback has k=14
(processid=86148)_callback has k=16
delete id=6 from _callbacks
◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"E121B54E11A02DF57F51B60A5F6DE639","loaderId":"236784B5BF017403914072280D3818E7","name":"commit","timestamp":112339.480991},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)checking id=undefined
(processid=86148)_callback has k=7
(processid=86148)_callback has k=8
(processid=86148)_callback has k=9
(processid=86148)_callback has k=10
(processid=86148)_callback has k=11
(processid=86148)_callback has k=12
(processid=86148)_callback has k=13
(processid=86148)_callback has k=14
(processid=86148)_callback has k=16
◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"E121B54E11A02DF57F51B60A5F6DE639","loaderId":"236784B5BF017403914072280D3818E7","name":"DOMContentLoaded","timestamp":112339.490131},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)checking id=undefined
(processid=86148)_callback has k=7
(processid=86148)_callback has k=8
(processid=86148)_callback has k=9
(processid=86148)_callback has k=10
(processid=86148)_callback has k=11
(processid=86148)_callback has k=12
(processid=86148)_callback has k=13
(processid=86148)_callback has k=14
(processid=86148)_callback has k=16
◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"E121B54E11A02DF57F51B60A5F6DE639","loaderId":"236784B5BF017403914072280D3818E7","name":"load","timestamp":112339.490728},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)checking id=undefined
(processid=86148)_callback has k=7
(processid=86148)_callback has k=8
(processid=86148)_callback has k=9
(processid=86148)_callback has k=10
(processid=86148)_callback has k=11
(processid=86148)_callback has k=12
(processid=86148)_callback has k=13
(processid=86148)_callback has k=14
(processid=86148)_callback has k=16
◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"E121B54E11A02DF57F51B60A5F6DE639","loaderId":"236784B5BF017403914072280D3818E7","name":"networkAlmostIdle","timestamp":112339.490652},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)checking id=undefined
(processid=86148)_callback has k=7
(processid=86148)_callback has k=8
(processid=86148)_callback has k=9
(processid=86148)_callback has k=10
(processid=86148)_callback has k=11
(processid=86148)_callback has k=12
(processid=86148)_callback has k=13
(processid=86148)_callback has k=14
(processid=86148)_callback has k=16
◀ RECV {"method":"Page.lifecycleEvent","params":{"frameId":"E121B54E11A02DF57F51B60A5F6DE639","loaderId":"236784B5BF017403914072280D3818E7","name":"networkIdle","timestamp":112339.490652},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)checking id=undefined
(processid=86148)_callback has k=7
(processid=86148)_callback has k=8
(processid=86148)_callback has k=9
(processid=86148)_callback has k=10
(processid=86148)_callback has k=11
(processid=86148)_callback has k=12
(processid=86148)_callback has k=13
(processid=86148)_callback has k=14
(processid=86148)_callback has k=16
◀ RECV {"id":7,"result":{},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)checking id=7
(processid=86148)_callback has k=7
(processid=86148)_callback has k=8
(processid=86148)_callback has k=9
(processid=86148)_callback has k=10
(processid=86148)_callback has k=11
(processid=86148)_callback has k=12
(processid=86148)_callback has k=13
(processid=86148)_callback has k=14
(processid=86148)_callback has k=16
delete id=7 from _callbacks
◀ RECV {"method":"Runtime.executionContextCreated","params":{"context":{"id":1,"origin":"file://","name":"","uniqueId":"1255229065041202058.814605036165557828","auxData":{"isDefault":true,"type":"default","frameId":"E121B54E11A02DF57F51B60A5F6DE639"}}},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)checking id=undefined
(processid=86148)_callback has k=8
(processid=86148)_callback has k=9
(processid=86148)_callback has k=10
(processid=86148)_callback has k=11
(processid=86148)_callback has k=12
(processid=86148)_callback has k=13
(processid=86148)_callback has k=14
(processid=86148)_callback has k=16
◀ RECV {"id":8,"result":{},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)checking id=8
(processid=86148)_callback has k=8
(processid=86148)_callback has k=9
(processid=86148)_callback has k=10
(processid=86148)_callback has k=11
(processid=86148)_callback has k=12
(processid=86148)_callback has k=13
(processid=86148)_callback has k=14
(processid=86148)_callback has k=16
delete id=8 from _callbacks
◀ RECV {"id":9,"result":{"identifier":"1"},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)checking id=9
(processid=86148)_callback has k=9
(processid=86148)_callback has k=10
(processid=86148)_callback has k=11
(processid=86148)_callback has k=12
(processid=86148)_callback has k=13
(processid=86148)_callback has k=14
(processid=86148)_callback has k=16
delete id=9 from _callbacks
◀ RECV {"id":10,"result":{},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)checking id=10
(processid=86148)_callback has k=10
(processid=86148)_callback has k=11
(processid=86148)_callback has k=12
(processid=86148)_callback has k=13
(processid=86148)_callback has k=14
(processid=86148)_callback has k=16
delete id=10 from _callbacks
◀ RECV {"id":11,"result":{},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)checking id=11
(processid=86148)_callback has k=11
(processid=86148)_callback has k=12
(processid=86148)_callback has k=13
(processid=86148)_callback has k=14
(processid=86148)_callback has k=16
delete id=11 from _callbacks
◀ RECV {"id":12,"result":{},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)checking id=12
(processid=86148)_callback has k=12
(processid=86148)_callback has k=13
(processid=86148)_callback has k=14
(processid=86148)_callback has k=16
delete id=12 from _callbacks
◀ RECV {"id":13,"result":{},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)checking id=13
(processid=86148)_callback has k=13
(processid=86148)_callback has k=14
(processid=86148)_callback has k=16
delete id=13 from _callbacks
◀ RECV {"id":14,"result":{},"sessionId":"4E1C6867CFAC3FAAB27888605FA73913"}
(processid=86148)checking id=14
(processid=86148)_callback has k=14
(processid=86148)_callback has k=16
delete id=14 from _callbacks
◀ RECV {"id":15,"result":{"targetInfo":{"targetId":"a1cdb418-ebf9-4490-b04c-00bc357619e3","type":"browser","title":"","url":"","attached":true,"canAccessOpener":false}}}
(processid=86148)checking id=15
(processid=86148)_callback has k=15
delete id=15 from _callbacks
setting callbacks:3,message:{"id":3,"guid":"browser-context@8f5455ffa0e275b307010e0655e1dd9e","method":"setDefaultTimeoutNoReply","params":{"timeout":0}}
setting callbacks:4,message:{"id":4,"guid":"browser-context@8f5455ffa0e275b307010e0655e1dd9e","method":"setDefaultNavigationTimeoutNoReply","params":{"timeout":0}}
Waiting for the debugger to disconnect...

**Comment by mxschmitt** [comment]
This does not look like a Playwright bug. This bug tracker is for Playwright bug reports / feature requests only. I recommending [StackOverflow](https://stackoverflow.com/questions/tagged/playwright) or [Discord](https://aka.ms/playwright/discord) for things like this.
