### ISSUE TITLE
[Bug]: page goto hang in website

### ISSUE THREAD

**Issue by fancy45daddy** [microsoft/playwright#29572]
### Version

1.38.0

### Steps to reproduce

```
import * as playwright from 'playwright-chromium'
import path from 'path'
import {promises as fs} from 'fs'
import os from 'os'

const tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'tmp')) 
const context = await playwright.chromium.launchPersistentContext(tmp, {channel:'chrome', args:['--disable-blink-features=AutomationControlled', '--start-maximized'], headless:false, viewport:null})//default_args https://github.com/microsoft/playwright/blob/5faf6f9e69c2148e94c81675fb636eb31a02b5e7/src%2Fserver%2Fchromium%2Fchromium.ts#L78
const page = await context.newPage()
context.setDefaultTimeout(0)
await page.goto('https://improvingfortune.com/fun-facts-about-lemons-and-its-health-benefits')//'https://kiiky.com/fully-funded-scholarships-apply-now'
```
I have two website 'https://improvingfortune.com/fun-facts-about-lemons-and-its-health-benefits' and 'https://kiiky.com/fully-funded-scholarships-apply-now' but in await page.goto both of them hang and never finish. So I can not do other test inside this two website. Any idea how to make the page.goto finish so I can do other test in the website?

### Expected behavior

page goto finish and to the next step

### Actual behavior

page goto hang

### Environment

```shell
node: v21.2.0
npm: 10.2.3
```

**Comment by mxschmitt** [comment]
I can't repro. `page.goto` completes for me. The window stays open because you did not close the context, so a `context.close()` will also close the browser for me.

Could you try on latest Playwright? And provide us logs when setting the `DEBUG=pw:api` env var?

**Comment by yury-s** [comment]
Is it reproducible with bundled Chromium (i.e. without `channel: 'chrome'`) ?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
