### ISSUE TITLE
[Docs]: Python documentation starting point is confusing

### ISSUE THREAD

**Issue by simonw** [microsoft/playwright#29579]
### Page(s)

https://playwright.dev/python/docs/intro is the page you get if you start on https://playwright.dev/python/ and click the "docs" link - but it's not actually documentation, it's documentation for `pytest-playwright`.

https://playwright.dev/python/docs/library is a better starting point.

### Description

This came up in a comment on Hacker News: https://news.ycombinator.com/item?id=39442273#39443071

**Comment by fireattack** [comment]
I agree. To me it's not even about what the tool is for, more about the flow of a doc/tutorial, and how intuitive it is.

For any lib, naturally (new) users want to learn about what the lib actually does before *using* it in the tests, even if that's the ultimate goal. Learning about how to use the tool in pytest before the tool itself sounds backwards.

**Comment by mxschmitt** [comment]
> The simplest way of addressing this would be to add a paragraph of text at the top of https://playwright.dev/python/docs/intro that specifically links to https://playwright.dev/python/docs/library as the place to learn about using Playwright Python outside of testing.

This sounds good from our side, happy to accept a PR for that.

**Comment by simonw** [comment]
Opened a PR here:
- https://github.com/microsoft/playwright/pull/29590

**Comment by mxschmitt** [comment]
Addressed by https://github.com/microsoft/playwright/pull/29590. Thanks!
