### ISSUE TITLE
[Bug]: Issue with copying file while downloading

### ISSUE THREAD

**Issue by BykovAndrii** [microsoft/playwright#29597]
### Version

1.41.2

### Steps to reproduce

1. Go to page where file can be downloaded
2. Start downloading
3. Save file to custom path using await download.SaveAsAsync(pathToSave)

### Expected behavior

File is present in proper folder.

### Actual behavior

Error is present:
EPERM: operation not permitted, copyfile 'tempPlaywrightFIlePath' -> 'CustomPath'

### Additional context

Downloaded file is present in Playwright folder with .file extention.
P.S. While debugging after clicking "Show in folder" link in Chrome, in Downloads section , nothing's happened. Folder is not opened.
For downloading used both ways: 1) await Page.RunAndWaitForDownloadAsync, 2) basic from docs var waitForDownloadTask = Page.WaitForDownloadAsync, var download = await waitForDownloadTask.
In both cases issue is raised in line await download.SaveAsAsync(pathToSave);

### Environment

```shell
Windows 10 Enterprise 22H2
Playwright Version 1.41.2
C# language with Playwright.NUnit
Browser Chrome, incognito(default) mode
```

**Comment by yury-s** [comment]
Looks like your app is lacking permissions to write into the specified path. If you thin this is a playwright bug, please provide a repro that we could run locally.

**Comment by yury-s** [comment]
> So, which app according to your thoughts has lack of permission?

The one that is built with playwright library and runs the test.

> I can't provide a repo as it's a commercial project.

Unfortunately we cannot act on this without a repro.
