### ISSUE TITLE
[Bug]:  I could not see the playwright extension after installing

### ISSUE THREAD

**Issue by muhammadowais22** [microsoft/playwright#29598]
### Version

v1.0.22

### Steps to reproduce

I was working with the playwright tests and everything was perfectly working. The very next day, I opened the VS Code to run playwright tests but I couldn't see the extension down below even after it is installed and globally available. I didn't done anything with it, I reinstalled the VS Code but still seeing the same issue, kindly do assist me in this as I'm currently working on my playwright tests, please fix this ASAP. 
![image](https://github.com/microsoft/playwright/assets/147746129/f73444e0-3928-43f3-943e-034546bc685b)

### Expected behavior

I should see the extension right under the extension logo.

### Actual behavior

I couldn't see the extension right under the extension logo.

### Environment

```shell
Windows 11
```

**Comment by yury-s** [comment]
Did you try reinstalling the extension? It's likely a problem with VS code updates which is outside of Playwright's control.

**Comment by muhammadowais22** [comment]
Yes, I did. I reinstall the extension 20, 30 times. Reinstalled the VS Code 10, 15 times.

**Comment by yury-s** [comment]
It could be that the Testing icon is hidden on your sidebar, you can try and show it via the context menu:

<img width="831" alt="image" src="https://github.com/microsoft/playwright/assets/9798949/c427dcf0-b238-4196-9241-d670a31575fc">

**Comment by muhammadowais22** [comment]
![image](https://github.com/microsoft/playwright/assets/147746129/6487f2a4-1c3a-4934-b7ec-db954bd9d795)
Unfortunately I couldn't see it here as well.

**Comment by muhammadowais22** [comment]
I tried everything but nothing worked. So, I removed  the code folder and uninstalled the vs code one last time. After I reinstalled the vs code, it finally worked. Thanks for your help.

**Comment by jovi5513** [comment]
منم نتونستم ببینمش

در تاریخ پنجشنبه ۲۲ فوریهٔ ۲۰۲۴،‏ ۲۱:۳۸ muhammadowais22 <
***@***.***> نوشت:
