### ISSUE TITLE
[Bug]: different rendering for a variable font and a regular font in the pipeline

### ISSUE THREAD

**Issue by dartess** [microsoft/playwright#29596]
### Version

1.41.2

### Steps to reproduce

1. Take content from https://stackblitz.com/edit/stackblitz-starters-1swb8q?file=index.html 
2. Publish content for tests somewhere
3. Make screenshot in CI with playwright (chromium)
```
  await page.setViewportSize({ width: 768, height: 1024 });
  await page.goto(<...>);
  await page.screenshot({ path: `_screenshot_.png`, fullPage: true });
```

### Expected behavior

Blocks with regular font and variable font are (almost) the same.

### Actual behavior

Blocks with regular font and variable font are very different.

### Additional context

Here are two screenshots. One was made locally (there is practically no difference), the second was made in CI.
![_screenshot_chromium_local](https://github.com/microsoft/playwright/assets/15047511/4bc2a867-779f-4177-87dc-6dfaf07d6b06)
![_screenshot_chromium_ci](https://github.com/microsoft/playwright/assets/15047511/c4b7a733-6f26-448f-a0c1-188b3e1f85bb)

Context: I changed the regular font to a variable one, and half of my screenshot tests failed. However, with manual visual comparison there are no changes. It turns out that screenshots when using a variable font do not show the real state.

### Environment

```shell
image: mcr.microsoft.com/playwright:v1.41.1-jammy
```
```

**Comment by yury-s** [comment]
There is some difference in the font rendering on different platforms. What is the bug?

**Comment by dartess** [comment]
Of course, different platforms render fonts differently.

But I don’t compare platforms with each other. I'm comparing the rendering of two variants (variable and non-variable) of the same font within the same platform.

Let's do it again. There are three blocks in the screenshots: one in regular Inter font. The second variable Inter font. The third contains an overlay of the first two to show the difference between them. I repeat once again - I took each screenshot on a separate platform, I do not compare platforms with each other.

Let's take all the platforms available to me:

Windows 11 (21H2), chromium: rendering of variable and non-variable fonts is 99.99% identical.
<img width="927" alt="win" src="https://github.com/microsoft/playwright/assets/15047511/e766b7bf-1e80-4bb8-b71d-0f80fba15f0d">

Linux Mint (21.3), chromium: rendering of variable and non-variable fonts is 99.99% identical.
![lin](https://github.com/microsoft/playwright/assets/15047511/46b4dbaa-0d2a-41ba-a1f8-360b955ca216)

macOS 14.2.1 (23C71), chromium: rendering of variable and non-variable fonts is again 99.99% identical.
<img width="771" alt="mac" src="https://github.com/microsoft/playwright/assets/15047511/3d24277d-8df2-4494-83ba-a828289f1cfd">

mcr.microsoft.com/playwright:v1.41.1-jammy, chromium: the rendering of variable and non-variable fonts is completely different, the distances between letters in the variable font are highly distorted and do not resemble any of the real physical platforms.
![_screenshot_](https://github.com/microsoft/playwright/assets/15047511/a189d7b7-d99e-4b9c-89d8-3875cc7bc4f5)

If both blocks were distorted (relative to other platforms) - ok, this could just be attributed to the fact that different platforms render fonts differently.

But the essence of the problem is that here, within the same platform, fonts are rendered differently. I'm guessing this is because one font is variable and the other is not. Perhaps they are rendered by different packages? And the package that draws the variable font doesn't seem to do its job. I'm not sure how this works at a low level, so I did the best I could - provide a description of the problem. Thank you!

**Comment by yury-s** [comment]
> But the essence of the problem is that here, within the same platform, fonts are rendered differently. I'm guessing this is because one font is variable and the other is not.

Not sure why you think they should be rendered identically.

> Perhaps they are rendered by different packages? 

Could be. This is a part of browser implementation and Playwright has no influence on it.

Closing this report as it doesn't seem to be a bug in Playwright but rather a specific of the browser implementation.

**Comment by dartess** [comment]
> why you think they should be rendered identically

a) because it's the same font
b) because they DO it identically on all other platforms on the same browser

I agree that this is not a problem with the `playwright` itself.

Most likely this is a problem with the image `mcr.microsoft.com/playwright:v1.41.1-jammy`. But it seems this is still a related area of responsibility. Therefore, I would be grateful if, instead of simply closing issue, you would suggest where I should turn with it next.

**Comment by koesper** [comment]
Did you ever find a workaround @dartess?
I'm running into similar issues, and am trying to solve it by forcing my browsers to disable all fancy font rendering.
but this seems like a hacky workaround.

**Comment by dartess** [comment]
@koesper Sorry, I can't recall details. But in my case it wasn't playwright-related problem (I was wrong above).
