### ISSUE TITLE
[Bug]: Evaluating Canvas context returning empty object

### ISSUE THREAD

**Issue by ubalensi-yoobic** [microsoft/playwright#29594]
### Version

1.41.2

### Steps to reproduce

Add a canvas element on a page, connect playwright on it for testing and 
in the test file, declare a const ctx where
```
const canvas = component.locator('canvas');
const ctx = await canvas.evaluate((el: HTMLCanvasElement) => el.getContext('2d'));
console.log(ctx)
```

### Expected behavior

ctx returning an object of type CanvasRenderingContext2D with all the relative attribute
<img width="360" alt="image" src="https://github.com/microsoft/playwright/assets/42937044/3674e05d-cc0f-4346-8e95-c99499fcc553">

### Actual behavior

ctx returning empty object "{}"

### Environment

```shell
System:
    OS: macOS 14.1.1
    Memory: 5.54 GB / 64.00 GB
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    npm: 7.24.2 - ~/Documents/dev/repo/node_modules/.bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

As a side node, returning the bounding via getBoundingClientRect is returning the expected DOMRect object
=> `await canvas.evaluate(el => el.getBoundingClientRect())` => works

**Comment by yury-s** [comment]
This is working as intended, the result is serialized similar to [JSON.stringify()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description) and then restored in the Node.js context. 2d context serializes to '{}' by JSON.stringify().

**Comment by ubalensi-yoobic** [comment]
can you elaborate more about this, i mean therefore, how do i get the data from a code perspective, and how is that different from evaluating getBoundingClientRect() which you get not serialized ?

**Comment by Tallyb** [comment]
For anyone hitting this in the future, evaluate the specific property you need: 
```
const lineCap = await canvas.evaluate((el: HTMLCanvasElement) => el.getContext('2d').lineCap);
```
This should work with stingify.
