### ISSUE TITLE
[Feature]: provide docker image containing microsoft edge

### ISSUE THREAD

**Issue by thbley** [microsoft/playwright#29600]
### 🚀 Feature Request

Offer a separate docker image containing microsoft-edge-stable (+chrome, firefox and webkit).

### Example

Currently I use this Dockerfile to add edge, but I would prefer to have an official pre-built image which is regularly updated and maintained:

```
FROM mcr.microsoft.com/playwright:v1.41.2-jammy

RUN npx -y playwright install msedge \
    && apt-get clean \
    && rm -rf /tmp/* /var/lib/apt/lists/* /var/cache/apt/archives/* ~/.npm/
```

### Motivation

Several reports are listing microsoft edge with +/- 5%. So it's worth to have automated tests running with it.

**Comment by yury-s** [comment]
You can always install what you need on top of the open source image as you do. There are no plans to provide images with vendor browsers.
