### ISSUE TITLE
[Bug]: Reporter uses `outputFolder` instead of `outputDir`

### ISSUE THREAD

**Issue by eddiemonge** [microsoft/playwright#29603]
### Version

1.41.2

### Steps to reproduce

1. Install Playwright in a project
2. Modify the playwright config file to include `reporter: [['html', { outputFolder: 'my-report' }]],`

### Expected behavior

The config option for the directory to output reports for should be named `outputDir` to match other config options, which all seem to use `dir` instead of `folder`

### Actual behavior

The option uses `outputFolder`

### Additional context

Having consistent config options makes it easier to work with. If every other config option calls a directory `dir` except one, which calls it `folder` it is confusing.

Proposal: deprecate the `outputFolder` config option and introduce `outputDir` that is a duplicate option but takes precedence if both are used. Eventually, remove the deprecated option.

### Environment

```shell
Any
```

**Comment by yury-s** [comment]
This is indeed an oversight that the naming differs from other places. But this ship has sailed, given that the option is well documented, the types unambiguously specify the name and and widespread adoption without issues, there's insufficient justification to disrupt existing workflows and deprecate it. Without deprecation introducing a new one would only add confusion, so I don't think we are going to change this.
