### ISSUE TITLE
[Bug]: Cannot set per-context proxy when connecting to chrome over CDP

### ISSUE THREAD

**Issue by val1tine** [microsoft/playwright#29607]
### Version

1.41.2

### Steps to reproduce

Launch Chrome in a docker container with the following args

```
                "--headless",
		"--disable-gpu",
		"--remote-debugging-address=0.0.0.0",
		"--remote-debugging-port=9222",
		"--no-sandbox",
		"--proxy-server=http://localhost:9999",
```

Execute the following Kotlin (java) playwright code:

```
val playwright = Playwright.create()
val browserType = playwright.chromium()
val browser = browserType.connectOverCDP("http://localhost:9222")
val proxy = Proxy("http://localhost:3001")
val newContextOptions = NewContextOptions().setProxy(proxy)
val context = browser.newContext(newContextOptions)
val page = context.newPage()
page.setDefaultTimeout(30000.0)
page.navigate("https://somepage.com")
```

### Expected behavior

I expect to be able to connect to https://somepage.com (or another given URL) through the proxy at localhost:3001

### Actual behavior

following playwright error is thrown

```
com.microsoft.playwright.PlaywrightException: Error {
  message='net::ERR_PROXY_CONNECTION_FAILED at https://somepage.com
  name='Error
  stack='Error: net::ERR_PROXY_CONNECTION_FAILED at https://somepage.com
    at FrameSession._navigate (/private/var/folders/wj/mh6z__rj3txd_sprzr7k5c880000gn/T/playwright-java-5996977792542135501/package/lib/server/chromium/crPage.js:512:35)
    at async Frame._gotoAction (/private/var/folders/wj/mh6z__rj3txd_sprzr7k5c880000gn/T/playwright-java-5996977792542135501/package/lib/server/frames.js:534:28)
}
```

### Environment

```Text
- Operating System: MacOS Sonoma
- CPU: Intel
- Browser: Chromium
```

**Comment by yury-s** [comment]
I cannot reproduce it without docker. I assume the tests are running on the host machine and connect to the browser in the docker. Could it be that `localhost:3001` is running on the host system and the browser in docker cannot reach it or the proxy cannot reach `https://somepage.com`? Looks like a problem with the docker network setup, if you think this is a Playwright bug please share a repro that we could run locally.

**Comment by val1tine** [comment]
Were you able to launch Chrome w/o a docker container, and it worked?  I am currently trying to launch chrome outside of docker w/ those settings.  Can you share how you did that?

**Comment by yury-s** [comment]
> Were you able to launch Chrome w/o a docker container, and it worked?

`/Users/yurys/Library/Caches/ms-playwright/chromium-1103/chrome-mac/Chromium.app/Contents/MacOS/Chromium --headless --remote-debugging-port=9222 --no-sandbox --proxy-server=http://localhost:9999 --remote-debugging-address=0.0.0.0`

**Comment by val1tine** [comment]
That worked.  It must be something w/ my docker setup or how I'm launching google-chrome inside it.  Thank you.
