### ISSUE TITLE
[Feature]: Use test tags at project level

### ISSUE THREAD

**Issue by costa-collibra** [microsoft/playwright#29609]
### 🚀 Feature Request

Currently, we're facing a use case where we need to execute a set of smoke tests first, and if they pass, proceed to run our P0 tests. However, we're encountering an issue with the available options. The testMatch property doesn't suffice for our needs because we have a mixture of different tags within the same test files.

Here's a snippet of our current configuration:

```typescript
 {
      name: 'Smoke Tests',
      dependencies: ['Create Admin User'],
      testMatch: /\/smoke\/[^/]+\.ts$/,
      use: {
        ...devices['Desktop Chrome'],
      },
    },
    {
      name: 'P0 Tests',
      dependencies: ['Smoke Tests'],
      testMatch: /\/p0\/[^/]+\.ts$/,
      use: {
        ...devices['Desktop Chrome'],
      },
    },
```

As you can see, we've attempted to segregate tests based on their file location, but this approach would require significant effort in splitting all the tests by tag and duplicating files, which isn't ideal.

### Example

What we propose is the ability to configure each project to specify which tags we'd like to use, allowing for more flexibility and efficiency in managing our tests.

```typescript
projects: [   
    {
      name: 'Smoke Tests',
      dependencies: ['Create Admin User'],
      testTags: ["@smoke"],
      use: {
        ...devices['Desktop Chrome'],
      },
    },
    {
      name: 'P0 Tests',
      dependencies: ['Smoke Tests'],
      testTags: ["@p0"],
      use: {
        ...devices['Desktop Chrome'],
      },
    },
  ],
```

### Motivation

Implementing the proposed solution would indeed leverage the full potential of the projects feature in Playwright. It would significantly enhance flexibility by enabling us to manage test tags at the project level, thus optimising test organisation and execution.

This enhancement aligns perfectly with our goals of maximising efficiency and making the most out of Playwright's capabilities.

Thank you for considering this proposal. Let's work together to implement this feature and unlock its benefits for our testing workflow.

**Comment by yury-s** [comment]
Can you use [test tags ](https://playwright.dev/docs/test-annotations#tag-tests) and filter by them either via command line --grep option or by setting [project.grep](https://playwright.dev/docs/api/class-testproject#test-project-grep). Would that work?

We are also introducing a [new syntax](https://playwright.dev/docs/next/test-annotations#tag-tests) for tagging tests in 1.42.

**Comment by costa-collibra** [comment]
Iv seen the docs for the new tagging stuff which is exciting.

Are you saying there is a way to trigger certain tests in a single by grep.

Here is an example of our tests

```typescript
import test from '@fixtures/iam/iamBaseFixture';

test.describe('Some test suite', async () => {
  test('@smoke This is a smoke test', async ({ page }) => {
    // a smoke test
  });

  test('@p0 This is a p0 test', async ({ page }) => {
    // a po test
  });
});
```

The above is in a single file and we have many files like this but i want the smoke tests to run as part of smoke project and p0 tests to run as part of p0 project in a single run.

Would this new tagging feature help achieve this?

**Comment by costa-collibra** [comment]
I understand exactly what you mean now and this is fantastic

```typescript
{
      name: 'smoke',
      dependencies: ['Create Admin User'],
      grep: /@smoke/,
      use: {
        ...devices['Desktop Chrome'],
      },
    },
    {
      name: 'po',
      dependencies: ['smoke'],
      grep: /@p0/,
      use: {
        ...devices['Desktop Chrome'],
      },
    },
```

Thanks for highlighting this great feature

**Comment by viktorgagaleski** [comment]
I was amazed by this as well, it is really great and allows us to have project dependencies based on test levels using tags, which with proper setup is like having small pipeline within Playwright.. 🤯 🚀 
Thanks @yury-s!

**Comment by costa-collibra** [comment]
@yury-s will this grep still work when the new tagging feature is released?

As we will be moving the tags out of the test titles and into the new tags section

**Comment by yury-s** [comment]
> @yury-s will this grep still work when the new tagging feature is released?

Yes, it will. Full backwards compatibility. It's going to be a different syntax, but filter is the same grep.
