### ISSUE TITLE
[Bug]: `test.skip` with a callback is not invoked when trying to access a custom fixture

### ISSUE THREAD

**Issue by joeyorlando** [microsoft/playwright#29608]
### Version

1.41.1

### Steps to reproduce

I have my custom fixtures defined as such:
```tsx
// fixtures.ts
import { test as base, Fixtures } from '@playwright/test';

interface TestFixtures extends Fixtures {
  currentGrafanaVersion: string;
}

export * from '@playwright/test';
export const test = base.extend<TestFixtures>({
  currentGrafanaVersion: ({}, use) => use('9.0.0'), // 
});
```

This 👇 works, the `test.skip` executes as expected, I see the log message in my console + the tests in the file are skipped:
```tsx
import semver from 'semver';
import { test, expect } from '../fixtures';

test.skip(({ browserName }) => {
  console.log('INSIDE SKIP', browserName);
  return semver.lt('9.0.0', '10.0.0'); // I'd like to access the currentGrafanaVersion fixture here
}, 'Insights is only available in Grafana 10.0.0 and above');

test.describe('Insights', () => {
  // my tests...
});
```

This 👇  does not work, `test.skip` doesn't seem to be executed at all. I don't see the logged message and the tests are executed:
```tsx
import semver from 'semver';
import { test, expect } from '../fixtures';

test.skip(({ browserName, currentGrafanaVersion }) => {
  console.log('INSIDE SKIP', browserName, currentGrafanaVersion);
  return semver.lt(currentGrafanaVersion, '10.0.0');
}, 'Insights is only available in Grafana 10.0.0 and above');

test.describe('Insights', () => {
  // my tests...
});
```

### Expected behavior

I would expect all tests in the file to be skipped when using `test.skip` with a custom fixture

### Actual behavior

The tests are run as the `test.skip` is never invoked

### Additional context

The [docs](https://playwright.dev/docs/test-annotations#conditionally-skip-a-group-of-tests) on this are very brief and don't list this as something to avoid.

### Environment

```shell
System:
  OS: macOS 14.3
  CPU: (10) arm64 Apple M1 Pro
  Memory: 36.03 MB / 16.00 GB
Binaries:
  Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
  Yarn: 1.22.21 - /opt/homebrew/bin/yarn
  npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
IDEs:
  VSCode: 1.86.1 - /opt/homebrew/bin/code
Languages:
  Bash: 3.2.57 - /bin/bash
npmPackages:
  @playwright/test: ^1.41.0 => 1.41.2
```

**Comment by yury-s** [comment]
I cannot reproduce it with this project https://github.com/yury-s/bug-29608. Can you share full repro?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
