### ISSUE TITLE
[Feature]: Playwright option so that playwright fails if there are typescript issues in the playwright files

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [microsoft/playwright#29618]
### 🚀 Feature Request

Playwright is (very) lenient for typescript compilation issues it seems.
Although for most projects this is probably the preferred option, we have a large test file codebase and would prefer to be more strict. Maybe this could be solved with an option in playwright.config.ts?

### Example

<img width="754" alt="image" src="https://github.com/microsoft/playwright/assets/1098243/8202c563-457b-45e9-a2c0-cac8b0280e7b">

### Motivation

A code testing library that "hides" issues in test code quality is suboptimal IMO.

**Comment by yury-s** [comment]
As a workaround you can [manually ](https://playwright.dev/docs/test-typescript#manually-compile-tests-with-typescript) call typescript compiler before running tests to catch the errors.
