### ISSUE TITLE
[Bug]: Proxy configuration is not used for an APIRequest within globalSetup

### ISSUE THREAD

**Issue by JayAshton** [microsoft/playwright#29611]
### Version

1.41.2

### Steps to reproduce

1. Add a proxy server to the playwright configuration along with globalSetup
```
const config: PlaywrightTestConfig = {
  ...
  globalSetup: require.resolve(__dirname + '/global-setup.ts'),
  use: {
    ...
    proxy: { server: "http://proxy-server:8888" },
  },
```

2. In globalSetup, create an API request

```
async function globalSetup() {
  const context = await request.newContext();
  const response = await context.delete("<url>")
  expect(response.status()).toBe(204);
}
```

3. When running a test, the globalSetup assertion fails as the API request was blocked. Notably because the proxy was not used.

### Expected behavior

I would expect that the proxy URL defined within the playwright configuration would be used for any API requests within globalSetup

### Actual behavior

The proxy does not get used for API requests within globalSetup and as a result, the request fails. 

### Additional context

I am slightly unclear whether this behaviour is actually supported, but https://playwright.dev/docs/network#http-proxy suggests that the proxy configuration is used globally so I would expect it to also be used in globalSetup?

Adding a proxy to the request itself resolves this issue however:

```
async function globalSetup() {
  const context = await request.newContext({ proxy: { server: '<proxy-url>'  } });
  const response = await context.delete('<url>')
  expect(response.status()).toBe(204);
}
```

Also where an API request is made as part of the `test` the proxy then gets used as expected. 

### Environment

```shell
❯ npx envinfo --preset playwright

  System:
    OS: macOS 14.3.1
    Memory: 97.30 MB / 32.00 GB
  Binaries:
    Node: 16.20.2 - /usr/local/opt/node@16/bin/node
    npm: 8.16.0 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by yury-s** [comment]
It is expected behavior in globalSetup. You are completely on your own there and should pass all the options manually. If you want to use fixtures and config, you can use [project dependencies](https://playwright.dev/docs/test-global-setup-teardown#option-1-project-dependencies) to define global setup project, it will pick up all the settings.
