### ISSUE TITLE
[Feature]: `post.on("response", handler)` for multiple XHR requests

### ISSUE THREAD

**Issue by major** [microsoft/playwright#29626]
### 🚀 Feature Request

I have a site I need to test that does something like this:

1. Loads up an HTML page with an empty table
2. Makes an XHR request for JSON data immediately to load content into the table
3. Sleeps for 30-60 seconds
4. Makes another XHR request to get JSON to update the table
5. Repeats the sleep/XHR request loop forever

I'm able to use `page.on("response", handler)` method to catch the first XHR request when the page loads it for the first time, but I can't catch any of the ones after that first one. I've tried a basic loop with a `sleep()` and re-running `page.on("response", ...)` in there, but none of the subsequent XHR requests are intercepted. 😭

### Example

Ideally, there would be a way to catch subsequent XHR requests _after the page has fully loaded_. I could refresh the page and force the first request to run again, but that doesn't test the subsequent XHR requests without a reload.

### Motivation

This would make it easier to test repeated XHR requests that happen after the initial page load.

**Comment by yury-s** [comment]
`page.on("response", handler)` should be emitted for all XHRs not only the first one. Can you share a repro where this does not happen?

**Comment by yury-s** [comment]
Closing per the response above, please open a new issue with a reproduction  if it doesn't work.
