### ISSUE TITLE
[Feature]: Possibility to get context information during usage of APIRequestContext

### ISSUE THREAD

**Issue by MichalFidor** [microsoft/playwright#29625]
### 🚀 Feature Request

Once the APIRequestContext is established, we'll be able to access the context configuration within the test flow. This includes retrieving pre-set headers for requests, for instance or any other entries which can be set [here](https://playwright.dev/docs/api/class-apirequest#api-request-new-context).

### Example

Once the new context is established as shown below:
```TS
const userContext = request.newContext({
            baseURL: <someUrl>,
            extraHTTPHeaders: {
                Authorization: `Bearer ${token}`,
                accept: 'application/json, text/plain, */*',
            },
        });
```

We'll have the ability to invoke something like:
```TS
userContext.getContextConfiguration();
```

With this capability, we can retrieve all the data that has been set. By accessing this data, we can verify the token details and subsequently develop custom methods to refresh the token if necessary. This could involve either creating a new context or potentially updating the current one.

### Motivation

The APIRequestContext currently has limited access to retrieve default data utilized during request methods such as GET, POST, PUT, etc. While we can access all data provided by the response including headers, body, status, code, etc., there's currently no provision to retrieve data already set within the context itself once it's created. This limitation poses challenges, particularly when the token used for requests expires. Handling this with a single context may be manageable with custom logic for refresh, but it becomes more complex when dealing with multiple users in the same tests execution flow.

**Comment by yury-s** [comment]
You can save the configuration that was used to create APIRequestContext in a variable and read it later. Oh you could even wrap it in a [fixture](https://playwright.dev/docs/test-fixtures#creating-a-fixture). Would that work?

> Handling this with a single context may be manageable with custom logic for refresh, but it becomes more complex when dealing with multiple users in the same tests execution flow.

Can you elaborate on this problem? What is the example test where you deal with multiple users, does it reuse the same APIRequestContext instance or different?

**Comment by MichalFidor** [comment]
>You can save the configuration that was used to create APIRequestContext in a variable and read it later.

What kind of variable? process.env?

>Oh you could even wrap it in a [fixture](https://playwright.dev/docs/test-fixtures#creating-a-fixture). Would that work?

Im already doing the initialization in fixture files. I have something like this:

```TS
const contextTests = base.extend<Context>({
    userAContext: async ({}, use) => {
        await use(await ContextFactory.getContextForUser(users.userA));
    },
    userBContext: async ({}, use) => {
        await use(await ContextFactory.getContextForUser(users.userB));
    },
...
```

And in there I have around 8 different users. Then, this fixture file is extended by services fixture file:

```TS
const test = base.extend<Services>({
    someServiceUserA: async ({ userAContext }, use) => {
        use(new SomeService(userAContext));
    },
```

Thanks to this, in the test itself I have already a created userContext with the particular service that I would like to interact with. The particular service class itself, extends `BaseService` class which contains the base request method, which is wrapped by different custom things.

Because of this kind of configuration, I don't really know what user is currently sending the request, cause in the `BaseService` class I'm passing the context which is already created in the fixture file and using it to perform the requests. 
The only place that I can use, to regenerate token is the `BaseService` class itself. That's why I was writing, that I'm using multiple users, cause in one test I can use at least two of them. And once I'll execute all of the tests at once, all contexts are created, so saving it to the variable will be a quite hard I think.

But, during writing this message, one solution comes to my mind. I could save the token somewhere (but where...? process.env is the only solution?), then read it in baseService and decode it, cause it's Bearer, so it should contains the data that I need. Then, reading it I should have the user data and expiration time. 🤔

**Comment by yury-s** [comment]
> What kind of variable? process.env?

What I had in mind was a JavaScript variable. You could create a map from the context to the params it was created with and then lookup the params or even store the params as a custom field:

```js
const userParam = Symbol('userParam');

const contextTests = base.extend<{
  userAContext: APIRequestContext,
  userForContext: (context: APIRequestContext) => string
}>({
  userForContext: async ({}, use) => {
    await use((context: any) => context[userParam]);
  },

  userAContext: async ({}, use) => {
      const context = await ContextFactory.getContextForUser(users.userA);
      context[userParam] = users.userA;
      await use(context);
  },
});

contextTests("🖥️  some test", async ({ userForContext, userAContext }) => {
  const user = await userForContext(userAContext);
  console.log(user);
});
```

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.

**Comment by MichalFidor** [comment]
Ok, I've did it differently, by wrapping default context by my custom. I'll leave here how I did it, if someone will be interested:

```TS
private static getCustomContextObject(context: APIRequestContext, token: string, expires_in: string, username: string): CustomAPIRequest {
 const newContext = {
             token,
             expires_in: moment(expires_in, 'X'),
             username,
             ...context,
         };

         return Object.setPrototypeOf(newContext, Object.getPrototypeOf(context));
     }
```

And this solution is the best I could do in my implementation.
Anyway thanks @yury-s for the hints.
