### ISSUE TITLE
[Feature]: options support for BrowserContext.newPage 🙏

### ISSUE THREAD

**Issue by jsupa** [microsoft/playwright#29621]
### 🚀 Feature Request

It would be possible to add the same options as in Browser.newPage() to BrowserContext.newPage() ?

### Example

from:
https://github.com/microsoft/playwright/blob/50e7d8ca7a922a21d2d1167ea393d22b5653bfdc/packages/playwright-core/src/client/browser.ts#L99

to:
https://github.com/microsoft/playwright/blob/50e7d8ca7a922a21d2d1167ea393d22b5653bfdc/packages/playwright-core/src/client/browserContext.ts#L250

### Motivation

Support also for PersistentContext 🙏

**Comment by yury-s** [comment]
[`browser.newPage`](https://playwright.dev/docs/api/class-browser#browser-new-page) to `browser.newContext` followed by `context.newPage`. We are not planning to support per page constructor options.
