### ISSUE TITLE
[Bug]: :not() pseudo-class isn't being handled properly

### ISSUE THREAD

**Issue by BryceBarbara** [microsoft/playwright#29628]
### Version

1.41.2

### Steps to reproduce

```ts
await page.evaluate(() => {
  window.document.write(
    '<img> <img src> <img src=""> <img src="https://picsum.photos/id/1/200/300">',
  )
})
await expect(page.locator('img')).toHaveCount(4)
await expect(page.locator('img[src]')).toHaveCount(3)
await expect(page.locator('img:not([src])')).toHaveCount(1)
await expect(page.locator('img:not([src=""])')).toHaveCount(1) // this fails
```

### Expected behavior

I expect the selector excluding elements with empty `src` attributes to actually exclude elements.

### Actual behavior

The assertion times out due to it matching 2 elements.

### Additional context

For some reason, the UI shows no matches when the locator is set to `locator('img:not([src=""])')`

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900HK
    Memory: 12.70 GB / 31.68 GB
  Binaries:
    Node: 18.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 4.0.2 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.86.2 - C:\Users\BryceBarbara\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.1.16 - C:\Windows\system32\bash.EXE
```

**Comment by yury-s** [comment]
This is consistent with what `document.querySelectorAll('img:not([src=""])')` returns. There are 2 image tags that have empty `src` attribute: ` <img src>`,  `<img src="">` and two other elements that don't, so `page.locator('img:not([src=""])')` return 2 elements which is working as intended.

**Comment by BryceBarbara** [comment]
Thank you for the clarification! Sorry to have it be a dud :\
