### ISSUE TITLE
[Feature] Allow test run to continue execution if a test.step() fails (#14584)

### ISSUE THREAD

**Issue by jmaschle** [microsoft/playwright#29632]
### 🚀 Feature Request

I have a smoketest which looks at 140 pages on my website.  my website requires a login with mfa.  One test, 420 steps.  Works great if all the pages are responsive.  Occasionally, a page in the middle will hang.  
**_It should NOT fail the remaining steps._**  How do I do this (without making each page a separate test)?

### Example

If the page doesnt come up in 30 seconds, I just want to make a note (Im screenshotting) and move on.  30 seconds max - regardless of the page.

### Motivation

I have a smoketest which looks at 140 pages on my website. Works great if all the pages are responsive.  Occasionally, a page in the middle will hang, preventing me from fully assessing the site.

**Comment by ltsuda** [comment]
Do you think mixing `test.step` with `expect.soft` works for you? If it doesn't work inside the `.step`, maybe return a value from the `.step` callback and soft assert this return value (see the "Details" section below the `.step` API doc).

https://playwright.dev/docs/api/class-test#test-step

https://playwright.dev/docs/best-practices#use-soft-assertions
https://playwright.dev/docs/test-assertions#soft-assertions

**Comment by pavelfeldman** [comment]
This does not look like either a feature request or a bug report. I'd say try/catch should solve your issue.
