### ISSUE TITLE
[Bug]: FireFox does not waitForRequest

### ISSUE THREAD

**Issue by HunteRoi** [microsoft/playwright#29635]
### Version

1.41.2

### Steps to reproduce

1. clone my repo https://github.com/HunteRoi/playwright-firefox-waitforrequest
2. yarn install
3. yarn test
4. you should see the error

### Expected behavior

All tests pass

### Actual behavior

The tests run on the FireFox browser fail (whether it is locally or in GitHub Actions)

![local test suite run](https://github.com/microsoft/playwright/assets/32441291/2ebb77ac-edec-42ab-9b32-197eccf4f549)
![remote test suite run](https://github.com/microsoft/playwright/assets/32441291/202ceaf7-ab56-44f8-b7dd-f229b4289641)

### Additional context

I took a look at existing (or closed) issues and the closest one I could find is #11390. Unfortunately, the global story and the chosen answer that lead to close the issue does not suit me in the sense that I have no need for caching in my context (nor am I requesting an image for what it is worth).

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
    Memory: 20.19 GB / 31.92 GB
  Binaries:
    Node: 20.11.1 - H:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - H:\Program Files\nodejs\yarn.CMD
    npm: 10.2.4 - H:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.86.2 - H:\Program Files\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.2.15 - C:\Program Files\Git\usr\bin\bash.EXE
```

**Comment by pavelfeldman** [comment]
There is no network request being made to your URL as it has a mailto: non-network schema. There is no such network URL and hence there is no such network request.

**Comment by HunteRoi** [comment]
> There is no network request being made to your URL as it has a mailto: non-network schema. There is no such network URL and hence there is no such network request.

Don’t you think there should be something made to address the problem here though? Like a note in the documentation… 😅

Also why does it work for some but not all browsers? Do you have an idea on how I could find my way to check that the action is executed ?
