### ISSUE TITLE
[Bug]: trace 'on-first-retry' causes waitForNavigation to fail

### ISSUE THREAD

**Issue by 3rg1s** [microsoft/playwright#29653]
### Version

1.41.2

### Steps to reproduce

* Clone https://github.com/quran/quran.com-frontend-next
* Follow readme to run server.
* Run `npm run tests:integration language-selector.spec.ts` to run only the failing tests
* See output

### Expected behavior

* I expected the waitForNavigation to actually wait and pass the test

### Actual behavior

* waitForNavigation does not wait, and tests fail

### Additional context

* This is not an issue with the deprecated waitForNavigation, I have also tried it with waitForURL
* If you change trace to `trace: 'on'` or `trace: 'retain-on-failure'` the spec file will run correctly.
 

### Environment

```shell
System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.36 GB / 32.00 GB
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
  IDEs:
    VSCode: 1.86.2 - /usr/local/bin/code
  Languages:
    Bash: 5.2.15 - /opt/homebrew/bin/bash
  npmPackages:
    @playwright/test: ^1.41.2 => 1.41.2
```

**Comment by 3rg1s** [comment]
The issue occurs even if I use `waitForURL` isn't there a difference between them? Is `frame.waitForURL` something special compared to the other two?

**Comment by pavelfeldman** [comment]
In this case we need exact steps and a minimal repro - yours does not look minimal. We are looking for a repo with a single test that demonstrates how on-first-retry is breaking things. Otherwise our guess is as good as yours.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
