### ISSUE TITLE
[Bug]: Webkit tests became unstable after upgrade from 1.34.3 to 1.41.2 

### ISSUE THREAD

**Issue by igorMondu** [microsoft/playwright#29661]
### Version

1.41.2

### Steps to reproduce

Unfortunately, I can not make any reproduction here, because I am not sure how to trigger this. It happens randomly.

Since the upgrade from 1.34.3 to 1.41.2, I have been getting random failures with Webkit when running inside the git workflow. When I run locally on my Mac OS, everything is fine. We use `focal` image in the workflow. The errors I see are this:

```
Error: locator.click: Test timeout of 30000ms exceeded.
Call log:
  - waiting for getByTestId('open-banking-verify-button')
  -   locator resolved to <button type="button" class="chakra-button css-ehuep2" d…>…</button>
  - attempting click action
  -   waiting for element to be visible, enabled and stable
```

```
Error: locator.click: Test timeout of 30000ms exceeded.
Call log:
  - waiting for getByTestId('wizard-cancel-process-continue-button')
  -   locator resolved to <button type="button" class="chakra-button css-144fyym" …>…</button>
  - attempting click action
  -   waiting for element to be visible, enabled and stable
  -     element is not stable - waiting...
`````

Everything works fine in other browsers, and even in WebKit locally, but not inside the Git Workflow. Any ideas?

### Expected behavior

I expect tests to pass using Webkit as they did in 1.34.3

### Actual behavior

Tests randomly fail with the locator unable to find elements in the WebKit.

### Environment

```shell
mcr.microsoft.com/playwright:v1.41.2-focal
```

**Comment by pavelfeldman** [comment]
There is nothing we can do without the repro since WebKit is passing all our tests. Timeout usually means there is a race condition in the test and upgrading (that updates WebKit) can surface those races. We see that all the time and that is why we ask for a repro that we can run locally.

**Comment by igorMondu** [comment]
But, there is no problem locally. Works perfectly fine. It only starts to fail when I run it on GitHub workflow using playwright:v1.41.2-focal image.

I am not even sure how to make repro. I would have to make something, run on the workflow, hope it will fail.

Also, it's interesting that when I download report from workflow, element which PlayWright can not find is clearly visible in the screen shot.

**Comment by tjs-intel** [comment]
I'm experiencing a very similar issue which appears to be isolated to version 1.41.2:
https://github.com/sigopt/sigopt-server/actions/runs/8055582917/job/22002769299#step:5:3752

sigopt-server with playwright 1.41.2 with failing tests: https://github.com/sigopt/sigopt-server/pull/535

sigopt-server with playwright 1.40.0 seems to be unaffected by this regression: https://github.com/sigopt/sigopt-server/pull/536

**Comment by pavelfeldman** [comment]
> Also, it's interesting that when I download report from workflow, element which PlayWright can not find is clearly visible in the screen shot.

That does not contradict the log's `element is not stable - waiting...`. Seems like probing element's position yields different results, so Playwright times out waiting for the element to be stable. Without additional information our guess is unfortunately as good as yours.

**Comment by igorMondu** [comment]
I'll see if I can come up with some repro, but I am not optimistic. There must be a bug in playwright. I'll try to narrow down exact version of Playwright when this started to happen.

Locally, every browser works.
On the workflow, playwright:v1.41.2-focal, Chrome and Firefox passes, WebKit fails. I don't see how can something be wrong in my tests.

**Comment by NSeydoux** [comment]
Hi @igorMondu , @pavelfeldman. 
I have experienced somewhat similar regressions when upgrading playwright from 1.37.0 to 1.41.2. In particular, a cookie that used to be set is no longer available. An example of passing run is available in https://github.com/inrupt/typescript-sdk-tools/actions/runs/8068045929, and the same run fails in https://github.com/inrupt/typescript-sdk-tools/actions/runs/8067954358.

The specific problem is not quite the same as the one initially reported in the issue, so I'm happy to open a separate issue to keep the discussion isolated and more focused, but it does seem there have been some regressions on Webkit support in the latest playwright versions.

**Comment by pavelfeldman** [comment]
Please file an issue per use case! Repro is a key, if you could not repro it, it might be a different (more complex) issue.

**Comment by pavelfeldman** [comment]
We would need exact steps to follow in order to address this. It includes the code snippet that we can run locally to demonstrate the problem.

**Comment by Quasarman** [comment]
i have exactly the same issue
