### ISSUE TITLE
[Feature]: Filter request by the phrase in a network tab

### ISSUE THREAD

**Issue by dz1dz1on** [microsoft/playwright#29677]
### 🚀 Feature Request

I think it would be nice to have filter request input in networks tab similar like we have for example in chrome dev tools.
<img width="626" alt="image" src="https://github.com/microsoft/playwright/assets/62831238/8841e358-ba9a-4e0a-9e65-6e1965e311c2">

### Example

It is pretty common for me to wait for request to do some job and sometimes I need to skim over the list of request to check if this is an error or request did not appear at all. Since I know the name or part of the searching phrase I wish to filter out all of the things that are not interested for me at this time. 

BTW. I know we can decrease range of time but still it would be much quicker to even check how many times this request occurs in perspective of the full test etc.

### Motivation

This solution should decrease time needed for searching/debugging needed information, especially in the everday maintenance work.

**Comment by mxschmitt** [comment]
This seems implemented by https://github.com/microsoft/playwright/pull/31956.
