### ISSUE TITLE
[Feature]: Page Object Generator as part of the Recorder or as a Page Crawler

### ISSUE THREAD

**Issue by autom8ion** [microsoft/playwright#29673]
### 🚀 Feature Request

Currently the recorder works well to capture locators on the fly.  But when you build an automation framework you are then tasked with copying recorded locators into different POM pages   This is a painful manual process that is ripe for an automated solution.   It would be fantastic if the playwright recorder had the ability to generate page objects on the fly either by recording into them or by a web crawler that crawls through the site and capturing locators on each page.  Some care would need to be taken to separate out items that exist across multiple pages. i.e. Headers/Footers Menus etc...

### Example

A smart POM Generator tool could generate the POM on the fly and capture all of the important locators.  It could be done by clicking on the desired items or by a smart web crawler.    It would generate the top part of the POM like this:  import { expect, type Locator, type Page } from '@playwright/test';

export class PlaywrightDevPage {
  readonly page: Page;
  readonly getStartedLink: Locator;
  readonly gettingStartedHeader: Locator;
  readonly pomLink: Locator;
  readonly tocList: Locator;

  constructor(page: Page) {
    this.page = page;
    this.getStartedLink = page.locator('a', { hasText: 'Get started' });
    this.gettingStartedHeader = page.locator('h1', { hasText: 'Installation' });
    this.pomLink = page.locator('li', {
      hasText: 'Guides',
    }).locator('a', {
      hasText: 'Page Object Model',
    });
    this.tocList = page.locator('article div.markdown ul > li > a');
  }

### Motivation

Adding a POM generator type functionality would differentiate Playwright from other tools.  The recording is helpful for newbies who want to learn and generate locators but when it comes to maturing the tests into a maintainable automation framework the value of recording diminishes.

**Comment by pavelfeldman** [comment]
This sounds like an interesting feature, but it goes outside of the scope for Playwright. Detecting when to switch between POM classes and how to name elements is no fun and having just one POM is no different than not having it. So we'll leave this for the third parties!
