### ISSUE TITLE
[Bug]: Don't abort test run if _any_ project has tests

### ISSUE THREAD

**Issue by mikestopcontinues** [microsoft/playwright#29680]
### Version

1.41.1

### Steps to reproduce

1. Create a "container" project with no tests and dependency projects with tests.
2. Run the project `npx playwright test --project container`
3. ERROR! The run will abort `Error: No tests found`
4. Run again allowing no tests `nm playwright test --project cross-browser --pass-with-no-tests`
5. ERROR! No tests will run, including those from dependency projects

Here's a sample project config:

```ts
export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: {...devices['Desktop Chrome']},
    },
    {
      name: 'firefox',
      use: {...devices['Desktop Firefox']},
    },
    {
      name: 'webkit',
      use: {...devices['Desktop Safari']},
    },
    {
      name: 'container',
      testIgnore: '**/*',
      dependencies: ['chromium', 'firefox', 'webkit'],
    }
  ],
});
```

### Expected behavior

If _any_ project triggered by the run has tests, the process should not abort. This should not require `--pass-with-no-tests`.

### Actual behavior

There is no way to make these tests run without creating a "dummy" test file for these container projects.

### Environment

```shell
System:
    OS: macOS 14.2.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 3.56 GB / 96.00 GB
  Binaries:
    Node: 20.11.0 - ~/Library/Caches/fnm_multishells/43585_1708944229189/bin/node
    npm: 10.2.4 - ~/Library/Caches/fnm_multishells/43585_1708944229189/bin/npm
    pnpm: 8.13.1 - ~/Library/pnpm/pnpm
    bun: 1.0.26 - /opt/homebrew/bin/bun
  IDEs:
    VSCode: 1.86.2 - /usr/local/bin/code
  Languages:
    Bash: 5.2.26 - /opt/homebrew/bin/bash
  npmPackages:
    @playwright/test: 1.41.1 => 1.41.1 
    playwright: 1.41.1 => 1.41.1
```

**Comment by pavelfeldman** [comment]
The semantics of the dependencies is strict: only run dependencies if there is at least one test that needs them. That is compatible with filtering, where if no tests are matching the filter, respective dependencies are not run.

**Comment by mikestopcontinues** [comment]
I see. Thanks. In that case, can you recommend anything better than keeping an empty test around for intentionally empty projects?
