### ISSUE TITLE
[Bug]: page-leaks.spec.ts is failing on webview2 headed bot

### ISSUE THREAD

**Issue by yury-s** [microsoft/playwright#29695]
### Version

tot

### Steps to reproduce

https://devops.playwright.dev/flakiness.html#filter_spec=page-leaks.spec&branch=main&timestamp=1709057794907

### Expected behavior

Test passes.

### Actual behavior

https://devops.playwright.dev/flakiness.html#filter_spec=page-leaks.spec&branch=main&timestamp=1709057794907

### Environment

```shell
https://github.com/microsoft/playwright/actions/runs/8068188212/job/22040340027
```

**Comment by mxschmitt** [comment]
Good:
- https://github.com/microsoft/playwright/actions/runs/7980833764/job/21791308588
- Image: windows-2022
- Version: 20240211.1.0
- Included Software: https://github.com/actions/runner-images/blob/win22/20240211.1/images/windows/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20240211.1
- a023cd1f5723b88e064a914449049b6b56842769

Bad:
- https://github.com/microsoft/playwright/actions/runs/7991471961/job/21822693919
- Version: 20240218.2.0
- Included Software: https://github.com/actions/runner-images/blob/win22/20240218.2/images/windows/Windows2022-Readme.md
- Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20240218.2
- 7c9ca0c7ef94199e9a998301c2043191396143d3
