### ISSUE TITLE
[Feature]: Add eventListener for APIRequestContext

### ISSUE THREAD

**Issue by xXDIOCANDE175Xx** [microsoft/playwright#29699]
### 🚀 Feature Request

Its possible implement an enventListener for APIRequestContext like the one that already exists for BrowserContext or Page that allow us to handle event in easy way when we are testing API.

### Example

For example i need to use this event listener like 
`await myApiContext.on('request'(req:Request)=>{//my code that will be executed every  time my test do a request})`

### Motivation

I think this feature, in my situation where i orchestrate playwright by cucumber and i split my methods that call the API in different class that i call in my step-definition, can be very useful to attach, foreach step i do, the request data for example the URL and Method.
Now the only way i've to do it it's for each function, in addition to the parameters I already return, also return the URL of the request made but for a very huge project this solution will make me crazy.

**Comment by pavelfeldman** [comment]
> Its possible implement an enventListener for APIRequestContext like the one that already exists for BrowserContext or Page that allow us to handle event in easy way when we are testing API.

We only have event handlers for the events triggered by the browser. In your case, it seems like you want to listen to the event that you generate yourself when calling our API. In order to keep the layering of the system sound, you should generate event handlers as a part of the code that you generate for invoking Playwright APIs.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
