### ISSUE TITLE
[Bug]: Webkit 17.4 (playwright build v1967) on Windows fails to load flutter page 

### ISSUE THREAD

**Issue by SageEdwardKlapatiuk** [microsoft/playwright#29693]
### Version

1.41.2

### Steps to reproduce

Using Webkit 17.4 (playwright build v1967) with Playwright 1.41.2

1. At the terminal, execute: `playwright open https://flutter.github.io/samples/web/material_3_demo/ --browser webkit`

### Expected behavior

Webkit launches and the page is rendered.

### Actual behavior

On Windows, webkit launches but the page is not rendered and webkit stops responding.  (Note that firefox and chromium behave as expected on Windows, and all three browsers behave as expected in Linux and Mac.)

### Environment

```shell
- Operating System: [Windows 10 22H2]
- CPU: [x64]
- Browser: [WebKit]
```

**Comment by ZhouZhengCarlos** [comment]
Hi Im experimenting the same issue, we are running our test cases on Chromium and Webkit and there are flaky test cases for Webkit, common error: Target closed 

It crashes for:
- await page.waitForEvent('page');
- await page.waitForURL(/page-3/);
- await locator('selector').click();

**Comment by yury-s** [comment]
Opened upstream bug: https://bugs.webkit.org/show_bug.cgi?id=270882

**Comment by ZhouZhengCarlos** [comment]
> Opened upstream bug: https://bugs.webkit.org/show_bug.cgi?id=270882

So it's webkit having the problem then?

**Comment by mxschmitt** [comment]
I can confirm that this is fixed. Should be available in the next release or [Canary](https://playwright.dev/docs/canary-releases).
