### ISSUE TITLE
[Bug]: Code under `test.describe` is executed, when it shouldnt

### ISSUE THREAD

**Issue by dimkin-eu** [microsoft/playwright#29691]
### Version

1.41.1

### Steps to reproduce

run test

file test1.spec.ts
```js
import { test } from '@playwright/test'

test.describe.fixme("describe", () => {
    console.log("shouldn't be visible 1")

    test.beforeAll(async ()=>{
        console.log("shouldn't be visible 2")
    })

    test.beforeEach(async ()=>{
        console.log("shouldn't be visible 3")
    })

    test.afterEach(async ()=>{
        console.log("shouldn't be visible 4")
    })

    test.afterAll(async ()=>{
        console.log("shouldn't be visible 5")
    })

    test("short spec", async ({page}) => {
        console.log("shouldn't be visible 6")
        await page.goto('https://playwright.dev/');
    })
})

```

file test2.spec.ts
```js
import { test } from '@playwright/test'

test.describe.only("describe 2", () => {
    test("short spec 2", async ({page}) => {
        await page.goto('https://playwright.dev/');
    })
})

```

### Expected behavior

no console messages appeared

### Actual behavior

1st console message is there, so the code just under `describe` is executed.
code  in `test.*` is fine - not executed

this is sad, as some variables/initializations for test are done there - eating some processor time, memory and so on

### Additional context

having or not `.only` in 2nd spec doesn't mean anything next code is executed in both cases

```js
    console.log("shouldn't be visible 1")
```

So cases
- code is executed if spec is marked as `fixme` or `skip` 
- code is executed when spec should NOT run ( doesnt have `.only` inside ) ( having or not `fixme` or `skip` )

### Environment

```shell
System:
    OS: macOS 14.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 321.30 MB / 32.00 GB
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    npm: 10.1.0 - /usr/local/bin/npm
    pnpm: 8.9.0 - /usr/local/bin/pnpm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.41.1 => 1.41.1
```

**Comment by pavelfeldman** [comment]
We must run describe body to discover the tests in that block. Running or not, the report must include them annotated as fixme.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
