### ISSUE TITLE
[Feature]: Extend project testMatch property to allow execution of tests published in npm packages

### ISSUE THREAD

**Issue by Thomas-Haider** [microsoft/playwright#29705]
### 🚀 Feature Request

Hey, 
we have the usecase, that we own a shared testing library that is consumed by multiple teams in their own repository. We have a login project that runs 1 login test, which logs in and writes the auth credentials in a storage file, which is then consumed by all other projects. This workflow is identical for all repositories that consume our shared library. To avoid code duplication and having a central point for that logic, we would appreciate if we could publish the login test, so that other repositories can just add the project to their playwright.config.ts file and are good to go without adding a test themselves.
### Example

``` typescript
projects: [
    { name: 'setup', testMatch: '@organisation/shared-library/src/login.spec.ts' }, // login.spec.ts file is located in the "@organisation/shared-library" package
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], viewport: viewportSize, storageState: authFile },
      dependencies: ['setup'],
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'], viewport: viewportSize, storageState: authFile },
      dependencies: ['setup'],
    },
  ],
```

### Motivation

It will allow organizations, with multiple repositories, to share tests, between repositories, which would result in better ownership of test crucial code, reduce code duplication, and allow repositories to start writing tests, without having to think about the basic setup.

**Comment by pavelfeldman** [comment]
There is no established convention on sharing the "executable" TypeScript code using npm packages. Typically NPM is used to share the binaries in a form of compiled JavaScript. Following this logic, the simplest workaround would be to create a library that performs the setup in a utility module, transpile this library using conventional methods (esbuild, rollup, tsc) and deploy it as npm module. Then every client project would create a login.spec.ts file that imports utility functions from that library and executes them.
