### ISSUE TITLE
[Bug]: Pirate error since v1.42 with cucumber

### ISSUE THREAD

**Issue by cchantep** [microsoft/playwright#29703]
### Version

1.42.0

### Steps to reproduce

Upgrade an existing code base with following dependencies.

```json
    "@cucumber/cucumber": "10.3.1",
    "@cucumber/gherkin": "28.0.0",
    "@cucumber/gherkin-streams": "5.0.1",
    "@playwright/test": "1.41.2", <--------
    "playwright-bdd": "5.7.1",
    "ts-node": "10.9.2",
    "typescript": "5.3.3"
```

### Expected behavior

No error/no regression

### Actual behavior

All tests failed with following error:

```
Error: [Pirates] A hook returned a non-string, or nothing at all! This is a violation of intergalactic law!
```

### Environment

```shell
OSX (sonoma/Apple Silicon) or Linux
```

**Comment by pavelfeldman** [comment]
We would need a self-contained repro to act on the issue.

**Comment by pavelfeldman** [comment]
Closing as per above. Please open a new issue in case you find a problem with Playwright!

**Comment by cchantep** [comment]
Seems so
