### ISSUE TITLE
[Bug]: Playwright tests does not run chromium tests on ubuntu18.04-x64

### ISSUE THREAD

**Issue by acanyasar** [microsoft/playwright#29702]
### Version

1.42.0

### Steps to reproduce

Before running my tests on the jenkins server that I have I am running these commands everytime that I run my tests. 
`npm install
npx playwright install
npm install -D @playwright/test@latest
npx playwright test -g @"$test" --project="$Environment"`

I am not using a pipeline so thats why I am doing that. Before the 1.42.0 release everything was working fine and I was able to run the tests. However with the latest release I am not able to run the tests on my Jenkins machinary. 

### Expected behavior

To see that tests are running on jenkins

### Actual behavior

`fixed 2 of 2 vulnerabilities in 200 scanned packages
+ npx playwright install
Failed to install browsers
Error: ERROR: Playwright does not support chromium on ubuntu18.04-x64
Build step 'Execute shell' marked build as failure`

### Environment

```shell
ubuntu18.04-x64
1.42.0
```

**Comment by Smrtnyk** [comment]
https://github.com/microsoft/playwright/releases/tag/v1.42.0#:~:text=Ubuntu%2018%20is%20not%20supported%20anymore

**Comment by pavelfeldman** [comment]
Modern browsers no longer compile on Ubuntu 18, so we are moving on.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
