### ISSUE TITLE
[Feature]: allow visual comparison to compare screenshoots on different OS

### ISSUE THREAD

**Issue by jansepke** [microsoft/playwright#29713]
### 🚀 Feature Request

We want to use playwright as a visual comparison tool using `.toHaveScreenshot()`.

But we have developers using different operating systems, so if one developer is creating a new screenshot it will not be picked up when the test is executed by a developer with a different operating system.

Would it be possible to allow either to disable the operating system suffix (e.g. `-linux`) or more flexible: allow to configure the complete file name?

(We know that the comparison on different operating systems could fail, but this can be fixed using the `pixelmatch` options)

### Example

```typescript
export default defineConfig({
  expect: {
    toHaveScreenshot: { 
      osSuffix: false
    },
  },
});
```

### Motivation

Using playwright for visual comparison testing on multiple different operating systems

**Comment by pavelfeldman** [comment]
> (We know that the comparison on different operating systems could fail, but this can be fixed using the pixelmatch options)

It most certainly can not be fixed with pixelmatch or any other image comparison utility, unless your app is pure HTML Canvas. So you can save your time and not go there.

> Would it be possible to allow either to disable the operating system suffix (e.g. -linux) or more flexible: allow to configure the complete file name?

It is possible, but for purposes different than attempting to compare screenshots taken on different OSs:

https://playwright.dev/docs/api/class-testproject#test-project-snapshot-path-template

**Comment by jansepke** [comment]
> > (We know that the comparison on different operating systems could fail, but this can be fixed using the pixelmatch options)
> 
> It most certainly can not be fixed with pixelmatch or any other image comparison utility, unless your app is pure HTML Canvas. So you can save your time and not go there.

We are currently using [loki](https://github.com/oblador/loki) for visual testing and it is also using pixelmatch and by setting a threshold we have been able to have no false positives between Linux and Mac.

> > Would it be possible to allow either to disable the operating system suffix (e.g. -linux) or more flexible: allow to configure the complete file name?
> 
> It is possible, but for purposes different than attempting to compare screenshots taken on different OSs:
> 
> https://playwright.dev/docs/api/class-testproject#test-project-snapshot-path-template

ah ok, thank you. I did not found that, maybe it could be linked here https://playwright.dev/docs/test-snapshots
