### ISSUE TITLE
[Internal] Jest runner limitations / adoption blockers

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#2971]
- [x] No incremental progress
    https://github.com/facebook/jest/issues/6616
    open since Jul 4, 2018, positive signals, pending PRs
- [x] No configurable thresholds - all e2e tests are red/slow
    https://github.com/facebook/jest/issues/7220
    open since Oct 19, 2018, no signals from maintainers
- [ ] No way to skip tests programmatically based on the environment
    https://github.com/facebook/jest/issues/7245
    closed as won't fix, no positive signals from maintainers
- [ ] Specify whether to run only focused tests or all tests
  - Most of the time, I'd like to run just one test, not one test in one file and all other files
  - At the same time, I don't want to skip test runs if I accidentally commit `it.only`
- [ ] Pass different values to a test function, depending on command line options
- [ ] Dynamically add command line options
- [ ] Control focusing and skipping of tests based on the command line option
- [ ] Jest runs workers proactively, will run 40 workers even if there are 4 tests

**Comment by sauravhiremath** [comment]
Jest has now included the incremental progress feature in its 26.2.0 release 🎉 (supported only with `jest-circus` as the runner)

Ref: https://github.com/facebook/jest/pull/10227

**Comment by aslushnikov** [comment]
This is no longer applicable since we switched off jest.
