### ISSUE TITLE
[Bug]: /test-results subdirectories exceeds the default Windows pathname limit

### ISSUE THREAD

**Issue by chekrd** [microsoft/playwright#29719]
### Version

1.41.2

### Steps to reproduce

Create tests with long test name (at least 100 characters) and expect a snapshot.
Run Playwright in a directory with at least 60 characters long pathname.

### Expected behavior

There is a way to customize the `outputDir` subdirectories name patter.
Or PW lowers the 100 characters cap.

### Actual behavior

PW creates a subdirectory for each test run. The directory name length seems to be capped to 100 + suffix. Another 100 for the screenshot itself. It means, that it is easy to reach 257 characters Windows filename limit:
`C: / some / directories / ... / test-results / 100 characters long test directory name / 100 characters long test file name`

### Additional context

Is there a way to customize the subdirectory name pattern? 
If not, can it be added? Something like this (example):

`outputDir: string | ((testInfo: TestInfo) => string)`

### Environment

```shell
Windows
```

**Comment by yury-s** [comment]
@chekrd can you try to increase MAX_PATH as described in [this document](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later)? We can probably trim to less than 100 characters but there is still a chance the same 260 chars limit will be exceeded if there are more directories.

**Comment by yury-s** [comment]
> Is there a way to disable implicit test-results write and force PW to give us the buffer?

No, the screenshot matcher writes the screenshots into the files right away, it doesn't send them around as buffers.
