### ISSUE TITLE
[Bug]: Error: page.screenshot: Test ended.

### ISSUE THREAD

**Issue by rkhomi** [microsoft/playwright#29718]
### Version

1.42.0

### Steps to reproduce

```
test.only('test', async ({ page }) => {
	page.on('console', async () => {
		await page.screenshot();
	});
	await page.evaluate(() => {
		return new Promise(resolve => {
			setTimeout(() => {
				console.log('hello', 5, { foo: 'bar' });
				resolve('Console log executed');
			}, 1000);
		});
	});
	await page.goto('https://playwright.dev/docs/ci-intro', { waitUntil: 'commit' });
	await page.evaluate(() =>
		console.log('hello', 5, { foo: 'bar' }, 'hello', 5, { foo: 'bar' }, 'hello', 5, { foo: 'bar' }, 'hello', 5, {
			foo: 'bar',
		})
	);
	await page.evaluate(() =>
		console.log('hello', 5, { foo: 'bar' }, 'hello', 5, { foo: 'bar' }, 'hello', 5, { foo: 'bar' }, 'hello', 5, {
			foo: 'bar',
		})
	);
	await page.evaluate(() =>
		console.log('hello', 5, { foo: 'bar' }, 'hello', 5, { foo: 'bar' }, 'hello', 5, { foo: 'bar' }, 'hello', 5, {
			foo: 'bar',
		})
	);
	await page.evaluate(() =>
		console.log('hello', 5, { foo: 'bar' }, 'hello', 5, { foo: 'bar' }, 'hello', 5, { foo: 'bar' }, 'hello', 5, {
			foo: 'bar',
		})
	);
	await page.evaluate(() => {
		return new Promise(resolve => {
			setTimeout(() => {
				console.log('hello', 5, { foo: 'bar' });
				resolve('Console log executed');
			}, 300);
		});
	});
});
```
1. Run the following test with `--debug` mode
2. When the browser is open, set Network to `Slow 3g`
3. Run the test

### Expected behavior

My idea is when console errors occur, take a screenshot and attach it to report, however there are cases when test fails like this, when console error could occur at the end of test or smth similar

### Actual behavior

Test should wait for screenshot to complete

### Environment

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 415.48 MB / 32.00 GB
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.11.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
  IDEs:
    VSCode: 1.86.2 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.40.0 => 1.42.0
```

**Comment by pavelfeldman** [comment]
When the test ends, we close the page (and sometimes browser), so you can't take a screenshot. In your example the test literally ended before the event was dispatched.

This would be a best effort implementation of your feature:

```
const screenshotPromises = new Set();
page.on('console', async () => {
  screenshotPromises.add(page.screenshot().catch(() => {});
});
// ...
// test body
// ...
await Promise.all([...screenshotPromises])
```

**Comment by rkhomi** [comment]
> When the test ends, we close the page (and sometimes browser), so you can't take a screenshot. In your example the test literally ended before the event was dispatched.
> 
> This would be a best effort implementation of your feature:
> 
> ```
> const screenshotPromises = new Set();
> page.on('console', async () => {
>   screenshotPromises.add(page.screenshot().catch(() => {});
> });
> // ...
> // test body
> // ...
> await Promise.all([...screenshotPromises])
> ```

How can I implement it if I override page in my test?

```
export const test = base.extend<Fixtures, CustomConfigOptions>({
	
	page: async ({ page }, use, testInfo) => {

		page.on('console', async message => {
			

				const screenshot = await page.screenshot({
					fullPage: true,
				});
				await testInfo.attach('screenshot', { body: screenshot, contentType: 'image/png' });
				
			
		});

		await use(page);
	},
	
});
```

**Comment by pavelfeldman** [comment]
Responding to this is outside of the scope for fixing Playwright bugs, but with message above you should be able to make it work.
