### ISSUE TITLE
[Bug]: Error: No tests can be executed after update to 1.42.0 ("Playwright did not expect ... to be called here)

### ISSUE THREAD

**Issue by hschn** [microsoft/playwright#29712]
### Version

1.42.0

### Steps to reproduce

- I've updated from 1.41.2 to 1.42.0.
- whatever I do when I try to execute via cmd line, I get

```
Error: Playwright Test did not expect test.beforeEach() to be called here.
Most common reasons include:
- You are calling test.beforeEach() in a configuration file.
- You are calling test.beforeEach() in a file that is imported by the configuration file.
- You have two different versions of @playwright/test. This usually happens
  when one of the dependencies in your package.json depends on @playwright/test.
```

- when I switch back to 1.41.2, everything works like a charm
- do I switch to 1.42.0, it doesn't work

### Expected behavior

- test execution should work in 1.42.0 as well as in 1.41.2 before

### Actual behavior

- `Error: Playwright Test did not expect test.beforeEach() to be called here.`

### Additional context

any idea? 

### Environment

```shell
System: Ubuntu 22
Node 20.9.0
npm 10.1.0
npmPackages:
    "@playwright/test": "^1.42.0"
```

**Comment by pavelfeldman** [comment]
We fixed a bug that allowed using different test instances when defining tests and hooks. Could you provide a full repro if you think this is a bug?

**Comment by Doug-Bowen** [comment]
same issue for me.

**Comment by rkhomi** [comment]
run yarn playwright install
or checkout your cache on CI or node_modules

**Comment by Doug-Bowen** [comment]
fixed for me 

`- You have two different versions of @playwright/test. This usually happens
  when one of the dependencies in your package.json depends on @playwright/test.`

**Comment by hschn** [comment]
for some reason, my yarn.lock looked like this:

`"playwright-core@npm:1.41.2, playwright-core@npm:^1.42.0":
...`

I cleaned that up and now it works. thank you for your support!

**Comment by jwalkerinterpres** [comment]
Why doesn't Playwright report this?

Playwright knows what version of the library it's dealing with, correct?  When it sees a Playwright module with a different version it should throw a "You have two versions of Playwright" error right then and there ... instead of providing an obscure error that requires you to come here to understand it?
