### ISSUE TITLE
[Bug]: Playwright - PostgreSQL connection issue

### ISSUE THREAD

**Issue by roopeshgoud** [microsoft/playwright#29723]
### Version

1.41.2

### Steps to reproduce

import BasePage from './basePage'
import { baseUrl } from '../config'
import fs from 'fs'
import {Membership_Link,FirstMemLink,MemName,ProfileTab,CorrespondanceTab_Profile,EditBtn_Profile,EditBtn_Profile1,SaveBtn} from '../pageobjects/membershipPage'
import { expect } from '@playwright/test'
const testData = JSON.parse(fs.readFileSync(`./data/users.json`, `utf-8`))
import {Client} from 'pg'

class DataBase extends BasePage {
	constructor(page) {
		super(page)
	}
	//const {Client} = require('pg')
	
	async DBConfig(){
    host: "localhost";
    user: "XXXXXX";
    port: 5432; //Please insert your valid port form your PostgreSQL DB
    password: "XXX"; // Your password
    database: "XXXXXX" // Your name of database
	}

	async executeQuery2(query)
	{
		const client = new Client(this.DBConfig)
		await client.connect()
		await this.wait()
		const result = await client.query(query)
		await this.wait()
		console.log(result.rowCount)
		await client.end();
	
	}
	async executeQuery(ery) {
		const client = new Client(this.DBConfig);
		try {
		  await client.connect();
		  const result = await client.query(ery);
		  console.log(result.rows);
		} catch (error) {
		  console.error("Error in connection/executing query:", error);
		} finally {
		  await client.end().catch((error) => {
			console.error("Error ending client connection:", error);
		  });
		}
	  };
}
export default DataBase

### Expected behavior

As per UI validation, I need to query data from database and compare it against UI. Always fails with below errors:

### Actual behavior

PostgreSQL connection should be successful and data returned, which can be utilized for further automation

Error in connection/executing query: AggregateError:
at internalConnectMultiple (node:net:1116:18)
at afterConnectMultiple (node:net:1680:7) {
code: 'ECONNREFUSED',
[errors]: [
Error: connect ECONNREFUSED 127.0.0.1:5432
at createConnectionError (node:net:1643:14)
at afterConnectMultiple (node:net:1673:16) {
errno: -4078,
code: 'ECONNREFUSED',
syscall: 'connect',
address: '127.0.0.1',
port: 5432
},
Error: connect ECONNREFUSED ::1:5432
at createConnectionError (node:net:1643:14)
at afterConnectMultiple (node:net:1673:16) {
errno: -4078,
code: 'ECONNREFUSED',
syscall: 'connect',
address: '::1',
port: 5432
}
]
}

### Additional context

- I tried a connection of Oracle SQL Developer client and it was successful.
- Installed Third Party Extension on Oracle SQL Developer and able to connect/query to PostgreSQL same connection details, as mentioned in ticket.

### Environment

```shell
Windows 10 Business
npm 10.2.4
node v21.6.1
```

**Comment by pavelfeldman** [comment]
Please follow the template to submit a minimal repro that we can run locally. Also, you issue does not look related to Playwright.
