### ISSUE TITLE
[Bug]: uploaded file with file chooser ,memory increased at the second uploading

### ISSUE THREAD

**Issue by FrankRecord** [microsoft/playwright#29733]
### Version

1.39.0

### Steps to reproduce

1. use stateJson of the context to bypass the login step
2. goto the "https://creator.douyin.com/"
3. goto the "https://creator.douyin.com/creator-micro/content/upload"
4. upload file script:
 the releaseFIle should be a video, the video size should be 35mb ~ 110mb
```
with page.expect_file_chooser() as fc_info:
            page.locator("label").click()
            print('点击上传按钮')
            file_chooser = fc_info.value
            print('等待塞入视频文件')
            file_chooser.set_files(files=releaseFile)
            print("已选择视频",releaseFile)
```

 
5. then close page, close context, close the browser 
6. and repeat the process above

7.result in k8s:
the process was kill while it was running at second time, bcause the memory usage is more than 8GB
![img_v3_028h_a3409636-a632-4173-b98d-6b1fc8122bfg](https://github.com/microsoft/playwright/assets/29450131/d369fa9c-02a5-44bd-8a02-770e002c4511)
![img_v3_028h_523485c9-74d1-48c6-9b86-9b0e484ef00g](https://github.com/microsoft/playwright/assets/29450131/c7b1668f-312f-413e-a3b4-ab6de44440c7)

### Expected behavior

I expect it should be able to upload videos over and over again

### Actual behavior

it stops at the second time, and becomes 

### Environment

```shell
Playwright Version: 1.39.0
Operating System: Linux
Python version: 3.9.6
Browser: chromium
server: 4core 8GB
```

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/29730
