### ISSUE TITLE
[Bug]: Error: No tests found. Make sure that arguments are regular expressions matching test files. You may need to escape symbols like "$" or "*" and quote the arguments.  I am Getting this error whenever I run my code. Can anyone tell me how to fix it.

### ISSUE THREAD

**Issue by SyntheticMonitoring** [microsoft/playwright#29737]
### Version

Version 1.41.0

### Steps to reproduce

I am assigning token value in a variable and passing that value in subsequent request , but getting error-
const { test, request } = require('@playwright/test');

let accessToken = 'eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiQTI1NktXIn0.sk-nNrUYtS9u01DnLqxEXU_wgyv_g6eeiFbMmInHOEmYtTB61JEfBQ.EOdLmmJ28qCpyFqC0BvYRA.UkpOTu6oZi9bDjwIKeVeD8JQy8gwLh6KxO1LWiLv1DX37Nw5loFaQOVdnMN7T5DuqZz_K7PYEhOK1YwVLxUCAlUyE-bbgp2BH_aon0b1K-spPteV9efJ9B2YLUk52352RrpRXqNLTJWT3yApX3XXX7ZHdjou4ZJb5lX-Nex6ZDf072Lys5_kKjZmtinqy6C-IecI3nzFMq6i4LMHqtWT4q-NOIlDM3pT6aWwlI92X00ap13Z5p8bBYwxr4CQ3hB3z1R7oPujkg1_W20lIqOWaKvMMWJyAEd6iJWlmV7cW8is9wR1bMtTIB_VtnRZky-Qhfzj2QnGnU8Yn8MpQnd_Lic40ILJ5ByfNh8nxU1ZV_EAqW7Rsal920zlsg6BlTi-UHzRaYpHugGFMRrCMNqpzCUyvjM2Mc4WZExIM1oAsdTsiPrFEsQX8ZKLsSYcAiW5Ghv9sI1OkCJ6aeNcB4e6pwt6UmHr5Y0MSxFTxb5lsOJYZJDbaKyLHRy7cbgRR3FSurbedBoby4JLydWKXE6UIdXAMgJ22-mnD8cfAISa_GT7RB41GwAM7JDOfTOi9c1Z.DyDDsJCYYAwqtf7NA2QNFA'; // Define a variable to store the access token

test('Fetch QA API Token', async ({ request }) => {
  try {
    const apiUrl = 'api/endpoint';
    const customHeaders = {
      'X-IBM-Client-Id': '405a72ce-8a6e-4da0-9393-986f0174af04',
      'Authorization': 'Basic QVQxMDg1NlQxOmNlcFRhbjV5',
    };

    const response = await request.get(apiUrl, { headers: customHeaders });
    console.log('Status Code:', response.status());

    const responseBody = JSON.parse(await response.text());
    accessToken = responseBody.access_token; // Store the access token in the variable
    console.log('Access Token:', accessToken);

  } catch (error) {
    console.error('Error fetching API token:', error);
  }
});

test('Leaves Visualization QA6', async ({ request }) => {
  try {
    const apiUrl = 'api/endpiont';
    const customHeaders = {
      'X-IBM-Client-Id': '405a72ce-8a6e-4da0-9393-986f0174af04',
      'Authorization': `Bearer ${accessToken}`,
    
    };

    const response = await request.get(apiUrl, { headers: customHeaders });
    console.log('Status Code:', response.status());

    const responseBody = JSON.parse(await response.text());
    console.log('Response Body:', responseBody);

  } catch (error) {
    console.error('Error fetching API token:', error);
  }
});

### Expected behavior

This is failing as the accesstoken is not getting passed in variable ${accesstoken}

### Actual behavior

Error: No tests found. Make sure that arguments are regular expressions matching test files. You may need to escape symbols like "$" or "*" and quote the arguments.

### Environment

```shell
System:
    OS: Windows *********
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-1245U
    Memory: 1.75 GB / 15.69 GB
  Binaries:
    Node: 21.0.0 - C:\Program Files\Node.js 21.0.0\node.EXE
    npm: 10.2.0 - C:\Program Files\Node.js 21.0.0\npm.CMD
  IDEs:
    VSCode: 1.87.0 - C:\Users\bsingh236\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD     
  npmPackages:
    @playwright/test: ^1.41.0 => 1.41.0
```

**Comment by pavelfeldman** [comment]
Please follow the issue template when filing the bugs. We require the minimal repro in a form of a repo for cases like this.
