### ISSUE TITLE
[Bug]: Element is not attached to the DOM only on Webkit and Mobile Safari

### ISSUE THREAD

**Issue by GuiMoraesDev** [microsoft/playwright#29735]
### Version

1.42.0

### Steps to reproduce

1. Clone my repository https://github.com/GuiMoraesDev/my-portfolio/tree/homolog
2. install the dependencies using `pnpm i`;
3. Run the playwright test suite which is throwing the error `pnpm test:e2e -g "Email form"`;

### Expected behavior

The playwright will run the selected test suite in all projects, and all tests pass. 

### Actual behavior

The playwright will run the selected test suite in all projects, but only the `WebKit` and `Mobile Safari` will fail.

### Environment

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 151.42 MB / 16.00 GB
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.11.1/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 8.15.1 - /opt/homebrew/bin/pnpm
  IDEs:
    VSCode: 1.86.2 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.42.0 => 1.42.0
```

**Comment by pavelfeldman** [comment]
We aren't in the business of debugging customers' tests. If you suspect there is a bug in Playwright, please follow the issue template and provide a **minimal** repro.
