### ISSUE TITLE
[Feature]: Is there any way to duplicate a tab with a right-click on the tab bar (Chrome and Edge)

### ISSUE THREAD

**Issue by riteshV5** [microsoft/playwright#29741]
### 🚀 Feature Request

I tried using- 
_await page.click(1,1, { button: 'right' });_ but still it is not able to right click on tab bar and clicking on page instead for all possible coordinates.
Is there a way playwright can duplicate the tab with right-click on the tab bar ?

### Motivation

I have this requirement where we want to test if user duplicates the tab by using browser's User Interface.

**Comment by pavelfeldman** [comment]
Interacting with the browser UI is out of scope for playwright. But you can create a new page and navigate it to the same URL to achieve the same behavior.
