### ISSUE TITLE
[Regression]: Playwright CT CLI scripts fail due to broken initializePlugin import

### ISSUE THREAD

**Issue by jan-molak** [microsoft/playwright#29746]
### Last Good Version

1.41.2

### First Bad Version

1.42.0

### Steps to reproduce

```
mkdir example && cd example
npm init --yes
npm install --save-dev @playwright/experimental-ct-react17@1.42.0
npx pw-react17 --version
``` 

1. Create a new Node project
2. Install any of the following Playwright CT packages:
  - @playwright/experimental-ct-vue
  - @playwright/experimental-ct-vue2
  - @playwright/experimental-ct-solid
  - @playwright/experimental-ct-svelte
  - @playwright/experimental-ct-react17
3. Run PLaywright via their dedicated CLI script, e.g. `npx pw-react17 --version`
4. Notice type error:

```
example/node_modules/@playwright/experimental-ct-react17/cli.js:21
initializePlugin(_framework);
^

TypeError: initializePlugin is not a function
```

### Expected behavior

`cli.js` files in Playwright CT packages should import `initializePlugin` from the correct location, or use an alternative initialisation mechanism since the function seems to have been removed altogether in Playwright 1.42.0

### Actual behavior

The affected CLI scripts seem to be:
- [packages/playwright-ct-vue/cli.js](https://github.com/microsoft/playwright/blob/0da29959fa1274b352f34b19f22a8a3cfdd70bbe/packages/playwright-ct-vue/cli.js#L18)
- [packages/playwright-ct-vue2/cli.js](https://github.com/microsoft/playwright/blob/0da29959fa1274b352f34b19f22a8a3cfdd70bbe/packages/playwright-ct-vue2/cli.js#L18)
- [packages/playwright-ct-solid/cli.js](https://github.com/microsoft/playwright/blob/0da29959fa1274b352f34b19f22a8a3cfdd70bbe/packages/playwright-ct-solid/cli.js#L18)
- [packages/playwright-ct-svelte/cli.js](https://github.com/microsoft/playwright/blob/0da29959fa1274b352f34b19f22a8a3cfdd70bbe/packages/playwright-ct-svelte/cli.js#L18)
- [packages/playwright-ct-react17/cli.js](https://github.com/microsoft/playwright/blob/0da29959fa1274b352f34b19f22a8a3cfdd70bbe/packages/playwright-ct-react17/cli.js#L18)

### Environment

```shell
System:
    OS: macOS 14.3.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 43.20 GB / 96.00 GB
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 8.15.3 - ~/.nvm/versions/node/v20.11.1/bin/pnpm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/experimental-ct-react17: ^1.42.0 => 1.42.0
```

**Comment by pavelfeldman** [comment]
Ouch, scheduling for 1.42.1
