### ISSUE TITLE
[Bug]: Use test.only() to identify test cases, why other test cases will also be executed

### ISSUE THREAD

**Issue by Airpy** [microsoft/playwright#29757]
### Version

1.41.1

### Steps to reproduce

// playwright.config.ts
```json
{
      name: "abnormalDeveloper",
      testMatch: /test-register-developer\.spec\.ts/,
    },
    {
      name: "normalDeveloper", 
      testMatch: [/test-edit-developer\.spec\.ts/, "./**/tests/app/**.*.spec.ts"],
    },
```

in test-edit-developer.spec.ts，use test.only() to focuse run this test case

use npx playwright test --project abnormalDeveloper normalDeveloper，Why are the test cases in test-register-developer.spec.ts still run?

### Expected behavior

Only run test cases marked test.only in the test-edit-developer.spec.ts file

### Actual behavior

test-register-developer.spec.ts still run

### Environment

```shell
macos
nodejs:v20.10.0
playwright:1.41.1
```

**Comment by pavelfeldman** [comment]
Works for me:

~/tmp/142$ npx playwright test --project abnormalDeveloper normalDeveloper

Running 1 test using 1 worker

  ✓  1 [normalDeveloper] › test-edit-developer.spec.ts:3:6 › edit-developer (206ms)

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
