### ISSUE TITLE
[Question] Can releases specifically indicate the MacOS version compatibility

### ISSUE THREAD

**Issue by mwallace72** [microsoft/playwright#2975]
Looks like everything past v0.11.1 is not compatible with Sierra, which is fine, but it would be helpful if that was indicated in the version numbers. Had to spend 20min crawling back from latest today to find one that was compatible, and the general README just says "MacOS ✅ " so it's unclear what versions are supported.

Thank you!

**Comment by arjun27** [comment]
Thanks for the feedback @mwallace72! System requirements are [listed here](https://playwright.dev/#version=v1.2.1&path=docs%2Fintro.md&q=system-requirements), but we can do a better job at it. Curious to know – are you using the playwright.dev website?
