### ISSUE TITLE
[Feature]: support synchronous test.step

### ISSUE THREAD

**Issue by alvaromartmart** [microsoft/playwright#29759]
### 🚀 Feature Request

The `test.step` function is very useful to improve readability of reports, e.g. by wrapping Page Object Model's methods with an informative `test.step` explaining what it does.

However, the currently `test.step` can only return a `Promise`. Would be nice to have a synchronous version of it.

### Example

```ts
class TodoPage {
    // [...]
   getLocatorForTask(contents: string): Locator {
     return test.step(`[TodoPage] get locator for task containing "${contents}" in either name or description`, () => {
       return this.page.locator('.task-item').filter({ has: / * some other complex locators */});
     });
   }
}
```

### Motivation

Leverage `test.step` in context where we don't need / want asynchronous code.

**Comment by pavelfeldman** [comment]
It is unlikely that we make steps for sync operations since e2e tests are inherently async and there is an await workaround. Closing as out of scope for Playwright.

Btw, `this.page.locator('.task-item').filter({ has: / * some other complex locators */})` isn't really "getting" the locator, it just builds a selector string in memory for this locator.

**Comment by alvaromartmart** [comment]
> It is unlikely that we make steps for sync operations since e2e tests are inherently async and there is an await workaround. Closing as out of scope for Playwright.
> 

Fair enough. I was actually wondering, while writing the issue, if a synchronous `test.step` could actually break functionality in reporter(s), for instance. It was a QoL ask anyway.

> Btw, `this.page.locator('.task-item').filter({ has: / * some other complex locators */})` isn't really "getting" the locator, it just builds a selector string in memory for this locator.

I understand how Playwright locators work 😄 - I don't see what's wrong with my statement or example code, the method _does_ return a `Locator`. It just encapsulates the logic inside a POM method so the person developing the test doesn't need to remember how to build that specific locator.

This is what I would normally do, with the -supported- async `tes.step`
```ts
// POM
class TodoPage {
    // [...]
   getLocatorForTask(contents: string): Promise<Locator> {
     return test.step(`[TodoPage] get locator for task containing "${contents}" in either name or description`, () => {
       return this.page.locator('.task-item').filter({ has: / * some other complex locators */});
     });
   }
}
// test
await expect(todoPage.getLocatorForTask('foo')).toBeVisible();
```
