### ISSUE TITLE
[Bug]: Trace viewer online says everything remains in local, we upload our trace

### ISSUE THREAD

**Issue by gauravkhuraana** [microsoft/playwright#29761]
### Version

https://trace.playwright.dev/

### Steps to reproduce

Example steps (replace with your own):
1. Goto https://trace.playwright.dev/

and observe the message on the screen 

### Expected behavior

It should not say that it opens locally as we are uploading on a server

### Actual behavior

The message say it will open locally 

![image](https://github.com/microsoft/playwright-dotnet/assets/15048211/48895b3b-4dad-4a1e-9129-ce4fbd05717b)

### Environment

```Text
- online in the browser
```

**Comment by pavelfeldman** [comment]
This label refers to the "Select file" button, which does not upload the trace to server. If you are uploading the trace to server and then provide users with a lint to that trace, the label won't be visible once the trace opens.

**Comment by gauravkhuraana** [comment]
> This label refers to the "Select file" button, which does not upload the trace to server. If you are uploading the trace to server and then provide users with a lint to that trace, the label won't be visible once the trace opens.

Can you explain further what exactly do you mean in a little detail..

if i have a trace file abc.zip and to see it, if i click on **Select file** button and select the abc.zip from my local system

Then it will be uploaded on a server @ https://trace.playwright.dev/ and i will see it in browser.

So how can we say that abc.zip was opened locally as it works on internet on the server of https://trace.playwright.dev/

**Comment by MindaugasMateika** [comment]
> https://trace.playwright.dev/

https://trace.playwright.dev/ is a PWA, it doesn't need to upload trace to server to render it and it doesn't. When you select a file do you see any network requests that sends your zip somewhere else?

**Comment by gauravkhuraana** [comment]
> > https://trace.playwright.dev/
> 
> https://trace.playwright.dev/ is a PWA, it doesn't need to upload trace to server to render it and it doesn't. When you select a file do you see any network requests that sends your zip somewhere else?

i see these,, so all these happen in the browser ?

![image](https://github.com/microsoft/playwright/assets/15048211/2e6915a8-6e3f-4624-bfd3-3ff72fa97372)
