### ISSUE TITLE
[Internal]: Deprecate config.rootDir, pass empty string into the merger.

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#29768]
Deprecate config.rootDir as it has no semantics post-merge.

**Comment by yury-s** [comment]
Discussion notes:
- document `FullConfig`
  - split FullConfig to TestFullConfig, FullConfig
- stop serializing top level config fields, move them to the project level instead
- switch local reporters code to use only project level fields
- introduce `configName` property (set globally, available on `FullProject` only)
- introduce explicit global `rootDir` which will be replaced by `configName` in the final reports
