### ISSUE TITLE
Failed test cases related 

### ISSUE THREAD

**Issue by farukh43** [microsoft/playwright#29786]
### Please do not submit this issue.

- [x] I understand

**Comment by farukh43** [comment]
I have 500 test cases in regression suite of automation, in stage of deployment i found 50 test cases are failed due to application and coding issues in test script. Now i have application team fixed the issue and i also modified the test script. How can i run the only failed test cases?

**Comment by dgozman** [comment]
The issue tracker is reserved for bug reports and feature requests.

For anything else, such as questions or getting help, please see:
- [The Playwright documentation](https://playwright.dev/)
- [Our Discord server](https://aka.ms/playwright/discord)
