### ISSUE TITLE
[Regression]: Сomponent tests fail when using a component with the same name and the same relative path

### ISSUE THREAD

**Issue by GarrySh** [microsoft/playwright#29787]
### Last Good Version

v1.41.2

### First Bad Version

v1.42.0

### Steps to reproduce

first components test
import { Component } from '../Components.tsx'

other components test import other wrapper from relative path with same name
import { Component } from '../Components.tsx'

Or try my playground
```
git clone https://github.com/GarrySh/pw-import-problem
npm ci
npm run test-ct
```

### Expected behavior

For both components the tests must pass successfully

### Actual behavior

Сomponent tests fail when using a different wrappers with the same name and the same relative path. In file `.cache/metainfo.json` uses id `__Component_Component` and its contain only relative parts of file name. And in second test playwright uses build result for first test

### Environment

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 84.91 MB / 16.00 GB
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    pnpm: 8.3.0 - /opt/homebrew/bin/pnpm
  IDEs:
    VSCode: 1.86.2 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/experimental-ct-react: ^1.42.0 => 1.42.0
```

**Comment by mxschmitt** [comment]
I can verify this will be fixed in v1.43.

You can either wait for 1.43 or [use Canary](https://playwright.dev/docs/canary-releases).
