### ISSUE TITLE
[Bug]: blob URL scheme on Chromium, feature disparity with Firefox

### ISSUE THREAD

**Issue by andrisi** [microsoft/playwright#29788]
### Version

1.41

### Steps to reproduce

A system I need to interact with opens a new browser tab instead of downloading a PDF in Chromium. It's not a direct linke but a JS call probably. In Firefox a download event generated. The URL scheme of the new tab is "blob:", so I'd assume it is a download. Unfortunately there is no way to save the tab's content (a PDF actually) to a file as you can save the contents of a download event. It's a closed system, so I can not provide an URL, but would be happy to assist, screenshare, etc.

### Expected behavior

Treat blob: url scheme as download as you do in Firefox. Feature disparity.

### Actual behavior

In Firefox: download event triggered, in Chomium, a new tab opened, but no event.

### Environment

```shell
npx envinfo --preset playwright does not run on Windows

it's Node 20.10 on Windows 10
```

**Comment by dgozman** [comment]
@andrisi I think Chromium handles the blob url correctly. [Here is an example from MDN](https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications#example_using_object_urls_to_display_pdf). Are you running in headed mode? Chromium has different pdf support in headed vs headless, so try your luck in both modes.

Overall, this is a browser behavior that Playwright is not changing, so I don't think we should do anything about it.

**Comment by dgozman** [comment]
Closing as per above. If you still encounter problems, please file a new issue with a repro and link to this one.

**Comment by andrisi** [comment]
thanks @dgozman
