### ISSUE TITLE
[Question] Playwright and TypeScript

### ISSUE THREAD

**Issue by randomactions** [microsoft/playwright#2978]
Hello,

I am sorry for asking such a stupid question, but is there an example of tests written with Playwright in TS? I would really appreciate sharing this.

**Comment by arjun27** [comment]
Thanks @randomactions. All examples in our docs will work in TypeScript (since it is a superset of JS). Are you looking for something in particular?

**Comment by randomactions** [comment]
Hi Arjun,

I am new to TS and would like to see how people implement page object model with TS. I am also wondering how to run TS tests with Mocha or Jest. Do I have to compile them to JS first?

**Comment by randomactions** [comment]
One of the things I am struggling with is which type "page" should be assigned.

When it is an object, then I get **"property "goto" does not exist on type object":**

```
class mainPage {
    constructor(public page: object) {
        this.page = page;
    }

    public async navigateTo(pageURL: string): Promise<void> {
        await this.page.goto(BASE_URL + pageURL);
       };
```

**Comment by mxschmitt** [comment]
> One of the things I am struggling with is which type "page" should be assigned.
> 
> When it is an object, then I get **"property "goto" does not exist on type object":**
> 
> ```
> class mainPage {
>     constructor(public page: object) {
>         this.page = page;
>     }
> 
>     public async navigateTo(pageURL: string): Promise<void> {
>         await this.page.goto(BASE_URL + pageURL);
>        };
> ```

Playwright provides types for you which you can use:

```
import type { Browser, Page, BrowserContext } from 'playwright' // or -chromium etc.
```

**Comment by randomactions** [comment]
Max, thanks a lot! This helps!

Another thing that I might have missed in the documentation is -- does TS need to be compiled to JS with tsc first, or Playwright can manage running TS without compiling?

**Comment by mxschmitt** [comment]
> Max, thanks a lot! This helps!
> 
> Another thing that I might have missed in the documentation is -- does TS need to be compiled to JS with tsc first, or Playwright can manage running TS without compiling?

Playwright is a library which is written in TypeScript and provides a JavaScript bundle and optional types which Node and your editor like Visual Studio Code can consume. So if you write JavaScript and use type annotations by JSDoc, then you don't need to compile it with `tsc`.
But if you are writing TypeScript, it seems like you do, then you need `tsc` or [`ts-node`](https://github.com/TypeStrong/ts-node) to compile your TypeScript first to JavaScript and run it then afterwards.

**Comment by randomactions** [comment]
Thanks a lot!
