### ISSUE TITLE
[Bug]: The VSCode Playwright plugin mentions in the doc that a user can run tests in parallel using Testing explorer. However I didnt find it to work on my VScode machine. 

### ISSUE THREAD

**Issue by PramodKumarYadav** [microsoft/playwright#29782]
### Version

10.2.4

### Setup:
- Keep option to fullyParallel: true, in `playwright.config.ts` file.

### Steps A:
- Run multiple tests from VSCode UI (either Testing explorer or from the test class run options).

### Steps B:
- For comparison, run multiple tests also from terminal. Example command I used for test:
- `npx playwright test --grep="@payment-service" --project=chromium --headed`

### Steps A:
- Multiple browsers (5) should launch as per machines available cores (default is half of available cores). In my case, I expect 5 browsers to launch. System details given below. 

### Steps B:
- Multiple browsers (5) should launch as per machines available cores (default is half of available cores).

### Steps A:
Runs test in series. One at a time. 

### Steps B:
When run from terminal, launches 5 browsers.

### Additional context

Reference about running multiple tests from VSCode is here: https://github.com/microsoft/playwright-vscode?tab=readme-ov-file#run-multiple-tests

### Environment

```shell
### VSCode:
Version: 1.86.2 (Universal)

### Playwright plugin details:

More Info
Published
2021-08-17, 15:06:11
Last released
2024-02-08, 19:35:53
Last updated
2024-02-08, 20:54:41
Identifier
ms-playwright.playwright
```

### System details (MAC)
```
Hardware Overview:
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,2
  Chip:	Apple M1 Max
  Total Number of Cores:	10 (8 performance and 2 efficiency)
  Memory:	64 GB
  System Firmware Version:	7459.141.1
  OS Loader Version:	7459.141.1
```
```

**Comment by dgozman** [comment]
@PramodKumarYadav Are you running with "Show browser" checkbox on? This option disables parallelism, since it is meant for debugging purposes. If you uncheck it, the tests will be run exactly the same way as from the command line.

If the above does not work, please share a repro that we can run locally. Otherwise, it's unlikely we'll be able to help you.

> Version
> 10.2.4

This does not look like a version of Playwright, VSCode or Playwright Extension. Perhaps you mean something else?

**Comment by PramodKumarYadav** [comment]
Thanks @dgozman. You are right. I was indeed running with browser option checked. This explains.

A question: I am not sure if this is already mentioned in the docs? If not, maybe worth mentioning there?

**Comment by dgozman** [comment]
@PramodKumarYadav Thank you for the suggestion. We'll see whether we can improve the docs in this area. Given that your problem is resolved, I'll close the issue. Feel free to open a new one if you run into more problems.

**Comment by PramodKumarYadav** [comment]
Sure. Thanks @dgozman :-)
