### ISSUE TITLE
[Feature]: Expose project id to reporter api

### ISSUE THREAD

**Issue by vitalets** [microsoft/playwright#29783]
### 🚀 Feature Request

In my custom reporter I'm trying to group test runs by project. I use the following way to get the project of test:
```ts
 onTestEnd(test: TestCase, result: TestResult) {
    const project = test.parent.project();
    console.log(project?.id);
 }
```
But there is no property `id` of the project:
```
Property 'id' does not exist on type 'FullProject<{}, {}>'.
```
Although in the Playwright codebase I see that projectId is [passed to json reporter](https://github.com/microsoft/playwright/blob/d5d4f591f35970f48ffe82bfc5c9e117660d7f0f/packages/playwright/src/reporters/json.ts#L95). Also I've found that `project.id` was added to reporter apis here https://github.com/microsoft/playwright/pull/17346/files but now it is removed.

I've ended up with generating project id as JSON stringify of all project fields:
```ts
const projectId = JSON.stringify(test.parent.project());
```
but I think it's not very reliable as depends on fields order.

It would be useful to have project id in reporter apis (or have any other way to identify projects).

### Motivation

It will provide more opportunities for custom reporting.

**Comment by dgozman** [comment]
@vitalets What do you expect from such an id? I don't think we can guarantee consistency of ids over time, so it is not very useful to expose a project id in the API. You can always use `config.projects.indexOf(project)` as an id, or just auto-generate an id for each project and have a `Map<FullProject, string>`.

**Comment by vitalets** [comment]
@dgozman I need project id only for runtime data manipulation, so `Map<FullProject, string>` works fine! Thanks for the suggestion.
The only question - is it guaranteed that `test.parent.project()` will always return the same instance of project object?

**Comment by dgozman** [comment]
> The only question - is it guaranteed that test.parent.project() will always return the same instance of project object?

I think so! If that's not the case, file an issue 😄
