### ISSUE TITLE
[Feature]: To allow Api Request to take csv, Jpeg files as input payload in data.

### ISSUE THREAD

**Issue by VenilThegn** [microsoft/playwright#29797]
### 🚀 Feature Request

To allow Api Request to take csv, Jpeg files as input payload in data. My Api request accepts a csv file as payload data, But i'm not able to pass the file in payload using playwright

### Example

My Api request accepts a csv file as payload data, But i'm not able to pass the file in payload using playwright, It will be use-full for other Api requests like update profile picture which will get payload as jpeg.

### Motivation

My Api request accepts a csv file as payload data, But i'm not able to pass the file in payload using playwright. this is the reason for my proposal

**Comment by dgozman** [comment]
This is already possible with the `multipart` option. Take a look [at the docs](https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-fetch), there is a nice example of sending files.
