### ISSUE TITLE
[Feature]: Expose test tags in test info.

### ISSUE THREAD

**Issue by bockstaller** [microsoft/playwright#29793]
### 🚀 Feature Request

I would like read-only access to the test tags in my fixtures.
Currently, only annotations are exposed.

### Motivation

I am preparing the migration of a large e2e testing setup to playwright. 
The biggest pain points we are facing at the moment are:

- running only necessary tests in CI
- linking features and test implementation

I would like to achieve this via tags that could look like this: 

- `@feature:{feature_id}` -> this test tests feature with the given id
- `@view:{path}` -> this test touches this view

These tags need some enforcement to be useful. So I have implemented an automatic fixture ensuring that each tag type is present in each tests title path. 
Guaranteeing that all tests are tagged with both tag types.

This is not possible when tags are specified via the details object of a test. 
It isn't exposed in the testInfo object

**Comment by ZooDoo4U** [comment]
I'm wondering to be complete.  I'm thinking about two related issues. 

**First suggestion**: 
1.)  Listing tests.
     -list    --  as it works to day no tag info...
     -listTags   --  implies the list of test as we have today but w/Tags  See the test name  but then a list of tags associated with the tests...
     
-list
     testName1
     testName2
     testName3
     
-listTags 
     testName1
         tag1, tag2, someOtherTag
     testName2
         en, deskTop, mobile
     testName3
         <no line if no tags, blank line...>  

**Second Suggestion**.
     Filtering grep'ing based on tags, separately from the test names. From reading the help it appears the -grep will filter by test names and tags, mainly by assuming the @Value is used for the tag name.  Might assert clearner/clearer If there was a separate -grepTag no need for the "@" in the "@Value".   Also depending on the shell used '@' is particularly a pain for some...   Well unless there is a tag prefix character users may change?  Or better yet having the grepTag option to only grep tag values, no need for the '@' in the tag names as searching for test names and tags are not overloaded by one search criteria...  Might be me but having two grep command line options just seems cleaner and more deterministic...  Glad to open another issue for these but seems all related... Just let me know...
