### ISSUE TITLE
[BUG] FF - launchPersistentContext

### ISSUE THREAD

**Issue by ruslanx3m** [microsoft/playwright#2979]
![Снимок экрана (82)](https://user-images.githubusercontent.com/24808164/87704199-b5fc5b80-c7a4-11ea-906e-70c3c133fbc4.png)
**Context:**
- Playwright Version: [1.2.1]
- Operating System: [Windows]
- Node version: [12]
- Browser: [Firefox]

**Codet**

```javascript
const { firefox } = require("playwright");
const path = require("path");
const fs = require("fs-extra");

(async () => {
    const ff_profile = path.join(__dirname, '/profile');
    await fs.ensureDir(ff_profile);

    const browserContext = await firefox.launchPersistentContext(ff_profile, {
        headless: false,     
        viewport: null
    });
    
    const page = await browserContext.newPage();
    await page.goto('http://example.com');

    await page.waitForTimeout(10000);
    await browserContext.close();
})();
```

**Describe the bug**

Hi, with Firefox browser, this code is opening 2 browsers if I use `const page = await browserContext.newPage()`, or is opening 1 browser if is use `const page = browserContext.pages()[0]`, but in my case page.close will close browser  ..  so every opened page is a new Browser ... if I add to option `locale: 'de-DE'` - opens 3 browsers ...

**Comment by aslushnikov** [comment]
Hey @ruslanx3m, 

So what doesn't work? Is it purely aesthetics that bother you?

**Comment by ruslanx3m** [comment]
> 
> 
> Hey @ruslanx3m,
> 
> So what doesn't work? Is it purely aesthetics that bother you?

I can close 1 browser and work on second ... why I need 1 browser ? but ..

if u say, ok ... 8GB or 16GB ram -  Is it purely aesthetics that bother you??

**Comment by aslushnikov** [comment]
> if u say, ok ... 8GB or 16GB ram - Is it purely aesthetics that bother you??

@ruslanx3m since we talk about browser **windows**, not browsers, the memory overhead should be negligible. Especially if you keep the first page empty.

Do you have any measurements that show that extra page consumes 8GB of ram?

**Comment by ruslanx3m** [comment]
> > if u say, ok ... 8GB or 16GB ram - Is it purely aesthetics that bother you??
> 
> @ruslanx3m since we talk about browser **windows**, not browsers, the memory overhead should be negligible. Especially if you keep the first page empty.
> 
> Do you have any measurements that show that extra page consumes 8GB of ram?

**Comment by ruslanx3m** [comment]
> Do you have any measurements that show that extra page consumes 8GB of ram?

yes, have ... why u just not test code to see what is problem, is just double use memory, normal 180MB, but this code use 340MB (**await browserContext..pages()[0]** vs **await browserContext.newPage()**) ... why newPage (tab) open new browser window ? 

firefox.launchPersistentContext - open 1 browser window (is normal)
browserContext.newPage() - open another browser window (is not normal, must open 1 tab in this browser)

so its memory leak .. but if I open 10 tests or more my pc memory will end .. but if you say '_Is it purely aesthetics_' will go back to puppeteer (purely aesthetics) ...
