### ISSUE TITLE
[Feature]: Possibility to set up channel on .spec file level

### ISSUE THREAD

**Issue by OSnuszka** [microsoft/playwright#29805]
### 🚀 Feature Request

I currently tried to set the channel parameter at the .spec level of the file. Using for example test.use {channel: 'chrome'} at the file level. Unfortunately it only works from the configuration file level. In my case, I have a group of tests that need specifically this browser (we use the author's video player) which does not work on playwright chromium. It would be great if there was such a possibility to modify the channel only for a few tests.

### Example

```
test('example', async ({ page }) => {
  test.use({channel: 'chrome'});
[...]
});
```

### Motivation

Currently, I have to define a separate project in the configuration file (uses unique tags, for tests that are supposed to use true chrome) but I find it too complicated.

**Comment by dgozman** [comment]
@OSnuszka You can do a top-level call in the file, so separate the tests you need to run in `chrome` into a separate file:

```ts
// test-in-chrome.spec.ts

import { test } from '@playwright/test';

test.use({ channel: 'chrome' });

test('example 1', async ({ page }) => {
  // ...
});

test('example 2', async ({ page }) => {
  // ...
});
```

Let me know whether this works for you.

**Comment by OSnuszka** [comment]
@dgozman Thank you, looks like it's working, but now I have another problem, - in my CI/CD I'm using a lot of project/test profiles. 
I want to provide condition, once _browserName_ is _'chromium'_ switch channel on chrome.
But to get _browserType_ variable I need to initialize any test:
 
 ```
 test('example 1', async ({ page, browserName }) => {
  // ...
});
 ```
 But using this way to get _browserName_ it's to late set up channel. I also didn't want to set up env variable

**Comment by dgozman** [comment]
@OSnuszka If you want to always run your chromium tests with `channel: 'chrome'`, we recommend doing so in the config.

For more flexibility, you can [override the `channel` option](https://playwright.dev/docs/test-fixtures#overriding-fixtures) with a function. It is similar to defining your own fixtures, see [this guide](https://playwright.dev/docs/test-fixtures).

```ts
import { test as base } from '@playwright/test';

export const test = base.extend({
  channel: async ({ browserName }, use) => {
    await use(browserName === 'chromium' ? 'chrome' : undefined);
  },
});
```

Let me know whether this helps.

**Comment by dgozman** [comment]
Closing as per above. If you still encounter problems, please file a new issue with a repro and link to this one.
