### ISSUE TITLE
[Feature]: intercept network and add delay for request to complete

### ISSUE THREAD

**Issue by yooouuri** [microsoft/playwright#29818]
### 🚀 Feature Request

There is no way, to make an intercepted network call wait for a delay.

### Example

Proposed option `delay`

```typescript
await context.route(/establishments\?distribution=1/, async route => {
 // do stuff

  await route.continue()
}, { delay: 500 })
```

### Motivation

The API we're using is kinda fast when using dummy data. Im trying to `expect` something before the API call completes.

To archive this (without the example) is:

```typescript
function delay(ms = 1000) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms)
  })
}

await context.route(/establishments\?distribution=1/, async route => {
  await delay(500)

  await route.continue()
})
```

But this feels kinda meh

**Comment by dgozman** [comment]
Folding into #8622.
