### ISSUE TITLE
[Feature]: Locators (selectors)

### ISSUE THREAD

**Issue by theinexorable** [microsoft/playwright#29810]
### 🚀 Feature Request

Please, follow the example set by over-a-decade developed Selenium, as well as BeautifulSoup, to be able to call a specific tag, class, etc. as a selector, because a simple .locator('class name') does not work straight forward.
Say, extend the page.locator() functionality with page.locator(class='classname'); page.locator('button', class='button-name') [python oriented] 

### Example

page.locator(class='classname'); 
page.locator('button', class='button-name')

### Motivation

intuition about selecting the accurate and unique html tags

**Comment by dgozman** [comment]
@theinexorable I am not sure I understand correctly, but it seems like you want to locate by class name? Playwright supports [CSS selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_selectors) as they are ubiquitous on the web.

```ts
page.locator(".classname")
page.locator("button.button-name")
```

Let me know whether this works for you.
