### ISSUE TITLE
[Feature]: Python support

### ISSUE THREAD

**Issue by simakuutio** [microsoft/playwright#29829]
### 🚀 Feature Request

Right now, Playwright Test for VSCode doesn't support Python at all. Do you have any plans to add support for it in near future?

### Motivation

I never wanted to study typescript so using Python would be more practical for me.

**Comment by dgozman** [comment]
@simakuutio Playwright has its own test runner for Node.js and so it ships a VSCode extension for it. However, for Python [we recommend using Pytest](https://playwright.dev/python/docs/intro), so any VSCode extension that supports Pytest will do the trick. Let me know whether that works for you.

**Comment by mxschmitt** [comment]
See also here: https://code.visualstudio.com/docs/python/testing

Closing by that.
