### ISSUE TITLE
[Feature]: Target Filter Support

### ISSUE THREAD

**Issue by GuiKlesseMiranda** [microsoft/playwright#29832]
### 🚀 Feature Request

When working with Puppeteer, which communicates with browsers using the Chrome DevTools Protocol (CDP), a targetFilter can be used to filter targets based on specific criteria, such as resource type, name, or other attributes. This can be crucial when dealing with multiple frames, iframes, or execution contexts and you want to interact only with certain elements.

### Example

Adding a callback function to the launch or connect options, which returns a boolean value, provides a dynamic way to decide whether a target should be attached or not. This callback acts as a filter, enabling developers to programmatically determine the attachment of various targets based on custom logic:

```
  targetFilter: (target) => {
      return target.url() == "www.microsoft.com" ;
    }
```

### Motivation

Implementing a feature that provides granular control over targeting specific frames or execution contexts in a tool like Playwright would not only expand its capabilities but also offer developers a more powerful and adaptable tool for web automation, application testing, and data scraping. Here's how this functionality could enhance Playwright:

### **Granular Automation**

**Refined Control:** By enabling specific target filtering, developers can achieve more precise control over which parts of the page to interact with, especially in complex websites with numerous iframes or dynamic content.
**Contextual Interactions:** It allows for scripts that adapt and respond to different contexts within the same page, enabling automations that can differentiate between various frames or sections of a web application.

### **Efficiency and Performance**

**Resource Optimization:** Avoids running scripts in unnecessary parts of the page, conserving resources and enhancing the automation performance.
**Targeted Automation:** Focuses automation on relevant elements, reducing execution time and increasing the effectiveness of testing or automation scripts.

### **Enhanced Testing**

**Comprehensive Testing:** Facilitates writing test cases that cover more complex scenarios, especially in Single Page Applications (SPAs) that utilize multiple frames or dynamic components.
**Increased Code Coverage:** Enables testing specific parts of an application without navigating through the entire interface, which can help improve test coverage efficiently.

### **Usability and Flexibility**

**Customizable Scripts:** Offers developers the flexibility to create tailored scripts that adjust to the dynamic content of the page or changes in the page layout.
**Simplified Integration:** Eases integration with other tools and testing frameworks, as it allows more directed and controlled interaction with the web page.

### **Security**

**Safe Automation:** Allows automations to run in a controlled environment, where only specified frames or contexts are manipulated, minimizing the risk of unintended interactions with the page content.

Enhancing Playwright with such targeted filtering and control capabilities would provide a sophisticated approach to automating, testing, and interacting with modern web applications, catering to a wide range of use cases from simple automations to complex end-to-end testing scenarios.

**Comment by dgozman** [comment]
@GuiKlesseMiranda Could you please be more specific, for example provide a real-world example with an actual page url and playwright script where you would use the proposed feature?

Given your description, I think Playwright gives you all the capabilities you need to only interact with a part of a page. Therefore, specific examples would definitely help with understanding your proposal.

**Comment by GuiKlesseMiranda** [comment]
`targetFilter: (target) => {
      var type = target.type();
     return !!target.url() || type == "tab";
    }
`
    
In puppeteer I usually do this to change the behavior of CDP when performing tasks that use captchas, and in this case, the challenge becomes valid. to avoid some evals inside Workers.
