### ISSUE TITLE
[Bug]: Reporter API returns different project instances in merge-reports mode

### ISSUE THREAD

**Issue by vitalets** [microsoft/playwright#29841]
### Version

1.42

### Steps to reproduce

Clone repo https://github.com/vitalets/playwright-issues/tree/inconsistent-project-in-merge-reports and follow instructions in the readme.

### Expected behavior

I expect that `test.parent.project()` will return the same project object instance.

### Actual behavior

Actually `test.parent.project()` returns different object instances for the same project.

### Additional context

It's a continuation of the discussion in https://github.com/microsoft/playwright/issues/29783

### Environment

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 84.42 MB / 16.00 GB
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 7.27.1 - ~/Library/pnpm/pnpm
  IDEs:
    VSCode: 1.87.0 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.42.1 => 1.42.1
```

**Comment by dgozman** [comment]
@vitalets Indeed! Merger creates different projects for reports from different shards. For now, I'd recommend to disambiguate projects by their name - that's what html reporter does. We'll try to document our approach and maybe make some changes to make custom reporters easier to implement.

**Comment by vitalets** [comment]
> For now, I'd recommend to disambiguate projects by their name

@dgozman will do, thanks!

> We'll try to document our approach and maybe make some changes to make custom reporters easier to implement.

That would be great! Maybe make project name required and unique? I've tried the following code and it's allowed now:
```ts
export default defineConfig({
  projects: [
    {
      use: { ...devices['Desktop Chrome'] },
    },
    {
      use: { ...devices['Desktop Firefox'] },
    },
});
```
