### ISSUE TITLE
[Bug]: Firefox - Windows SSO not working when preference enabled (network.http.windows-sso.enabled)

### ISSUE THREAD

**Issue by AndrewRiggs-Atkins** [microsoft/playwright#29844]
### Version

1.42.1

### Steps to reproduce

1. Configure Playwright to use Firefox with SSO setting enabled.

```ts
projects: [
    {
      name: "Firefox",
      use: {
        browserName: "firefox",
        launchOptions: {
          firefoxUserPrefs: {
            "network.http.windows-sso.enabled": true,
          },
        },
      },
    },
```

2. Create a simple Playwright test to go to `https://login.microsoftonline.com/` to verify that the Windows SSO is working correctly, the account should be logged in or selectable if working.

```ts
import { test } from "@playwright/test";

test("Microsoft SSO", async ({ page }) => {

  // Go to Microsoft SSO sign-in page and wait for page to load
  await page.goto("https://login.microsoftonline.com/", {
    waitUntil: "domcontentloaded",
  });

  // Wait for long time to allow user to check about:config and security settings.
  await page.waitForTimeout(999999999);
}
```

3. When the test runs and `https://login.microsoftonline.com/` loads, if SSO is working correctly then the account should automatically be logged in or if multiple accounts exist there should be an option to select one of.

4. Go to `about:preferences#privacy`, the setting `Allow Windows single sign-on for Microsoft, work, and school accounts` should be enabled.

5. Go to `about:config` and search for `network.http.windows-sso.enabled`, it should be set to true.

### Expected behavior

1. Following navigation to `https://login.microsoftonline.com/`, if only one account is setup the user should be logged in automatically and redirected to `https://office.com`.

![selenium-firefox-sso](https://github.com/microsoft/playwright/assets/90264926/39c9ea56-350d-4d22-8cfb-ced150bc1bbc)

Note: The above working example screen recording has been achieved by using Python Selenium and the Geckodriover (see Python code below to replicate).

```py
import time
from selenium import webdriver
from selenium.webdriver.firefox.options import Options

# Set Firefox SSO preference
opts = Options()
opts.set_preference("network.http.windows-sso.enabled", True)

# Launch Firefox webdriver with SSO option
driver = webdriver.Firefox(options=opts)

# Navigate to Microsoft SSO login
driver.get("https://login.microsoftonline.com/")

# Wait for long time to allow user to check about:config and security settings.
time.sleep(999999)
```

### Actual behavior

1. Following navigation to `https://login.microsoftonline.com/` there is no automatic SSO login or accounts available for selection.

![image](https://github.com/microsoft/playwright/assets/90264926/56175fd4-b317-4e98-862d-db0600a7ad3a)

2. Additionally when you manually proceed through the login process, the device does not meet management compliance policy (this does not occur with Selenium or manual launching of Firefox).

![image](https://github.com/microsoft/playwright/assets/90264926/e241a9ea-ecae-4439-9f95-0667cd90661c)

3. Checking `about:preferences#privacy` it can be seen that the SSO setting is enabled.

![image](https://github.com/microsoft/playwright/assets/90264926/634766a5-5175-4f9f-b848-86c57ba4ca42)

4. Checking `about:config` it can be seen that the preference is enabled as per the Playwright Firefox configuration.

![image](https://github.com/microsoft/playwright/assets/90264926/0258cd46-d980-4eeb-a300-2dd8f8a081d8)

### Additional context

1. Manually launching the Firefox executable installed by Playwright (located at `AppData\Local\ms-playwright\firefox-1440\firefox` on Windows) the SSO works as expected when the preference is enabled. 

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 10.71 GB / 31.88 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.85.2 - C:\Users\<USER>\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 4.4.19 - C:\WINDOWS\system32\bash.EXE
  npmPackages:
    @playwright/test: ^1.42.1 => 1.42.1
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by brnbtt** [comment]
I don't understand how this got closed without any solution, I still have this issue

**Comment by freijon** [comment]
For anyone reading this, make sure you took [this ](https://github.com/mozilla/multi-account-containers/wiki/Frequently-asked-questions#enable-windows-sso-in-a-specific-container) into account (sso only works in the default container by default), it was the issue for me. In the GIF of the original issue, it doesn't look like a container was used though.

**Comment by dbelyaev** [comment]
@freijon Thanks a lot for posting this information! It was exactly mine issue and it helped me to fix this!

For everyone trying to find solution (apparently, the wiki page linked above has been removed), here is the link: https://bugzilla.mozilla.org/show_bug.cgi?id=1836016

Quote from there on how to fix this issue (enable SSO in containers manually): 

> [!TIP]
> - Get the container ID - this is available in containers.json in your Firefox profile directory, in a key called `userContextId` (47001 for example)
> - In `about:config`:
>   - create a boolean key `network.http.windows-sso.container-enabled.CONTAINERID`, where `CONTAINERID` is from step 1. 
>   - Set this key to `true`
> - Enjoy Windows SSO working in the given container!
