### ISSUE TITLE
[Feature]: Improve source (code) reports

### ISSUE THREAD

**Issue by 403-html** [microsoft/playwright#29859]
### 🚀 Feature Request

Enhance the debugging experience in testing by including not only the source code of the failed tests (which can be methods from another file, which makes it hard to debug) but also the specific lines within the **test files** where these failures were triggered.

### Motivation

Debugging tests is hard because our setup spreads out methods into different helper files (not in one test file), making it tricky to find where a problem starts in the actual test file. Right now, when something goes wrong, we only see where the error happened in a method, but not where in the test file it got called. This makes fixing errors slow and frustrating. We need clearer error reports that show exactly where in the test file each error comes from, so we can quickly understand and fix the issues.

**Comment by dgozman** [comment]
@403-html Are you talking about terminal, html report, trace or something else? Could you please attach the example output that does not work for you? I think we include the full stack trace at most places, so you should be able to see where the code was called from.

**Comment by mxschmitt** [comment]
Closing as per above, feel free to re-file.
