### ISSUE TITLE
[Bug]: Selecting wrong nested Locator element if selector contains pipe symbol

### ISSUE THREAD

**Issue by yuhymuk** [microsoft/playwright#29852]
### Version

1.39

### Steps to reproduce

open https://playwright.dev/python/docs/api/class-playwright

execute 
```
>> driver.page.locator('//a[text()="Classes"]/../..').locator('//a[text()="Browser"] | //a[text()="Playwright"]').all_text_contents()
>> ['Playwright', 'Browser']

```

### Expected behavior

The expression should return ['Browser'] because

```
>>driver.page.locator('//a[text()="Classes"]/../..').locator('//a[text()="Browser"]').all_text_contents()
>>['Browser']

```
and 
```
>> driver.page.locator('//a[text()="Classes"]/../..').locator('//a[text()="Playwright"]').all_text_contents()
>> []

```
so 
```

>> driver.page.locator('//a[text()="Classes"]/../..').locator('//a[text()="Browser"] | //a[text()="Playwright"]').all_text_contents()
should returns
>> ['Browser']


```
### Actual behavior

['Playwright', 'Browser']

### Environment

```Text
- Operating System: [MacOS]
- Browser: [Chromium, ]
- Python Version: [3.11]
```

**Comment by dgozman** [comment]
@yuhymuk XPath `//a[text()="Playwright"]` starts from the document root. If you would like a relative XPath, you should start it with `.//` instead. Playwright does that for you for simple XPath expressions, but not for the complex one with the `|`.

So, try the following and let me know whether that helps.
```py
driver.page.locator('//a[text()="Classes"]/../..').locator('xpath=.//a[text()="Browser"] | .//a[text()="Playwright"]').all_text_contents()
```

**Comment by dgozman** [comment]
@yuhymuk Thank you for the suggestions, we'll see what we can do to the documentation. I'll close this issue since there are no behavior changes planned. Feel free to open new issues if you encounter more problems.
