### ISSUE TITLE
[Feature]: Description formatting rule

### ISSUE THREAD

**Issue by reyrodrigez** [microsoft/playwright#29860]
### 🚀 Feature Request

- I'm looking for a rule where I can define what format descriptions should follow. Ideally I would provide a regex that all descriptions get tested against.

### Example

For example I'd like all descriptions to be a complete sentence (starts with a capital letter and ends with a full stop).
I provide the following regex: `/^[A-Z].*\.$/`
```
  type Vehicle {
    """
    id
    """
    id: ID!
    """
    Top speed of the vehicle.
    """
    topSpeed: Int
    """
    x
    """
    type: VehicleType
  }
```

Running the formatting rule on the type above would output:
- description of "id" doesn't satisfy the formatting rule `/^[A-Z].*\.$/`
- description of "topSpeed" doesn't satisfy the formatting rule `/^[A-Z].*\.$/`- 
- description of "type" doesn't satisfy the formatting rule `/^[A-Z].*\.$/`- 

### Motivation

Uniform description formatting for better readability.

**Comment by dgozman** [comment]
@reyrodrigez Are you sure you have filed the issue at the right repository? Playwright does not format any descriptions, so I am not really sure what you are talking about.

**Comment by reyrodrigez** [comment]
I'm so sorry @dgozman this meant to be raised against a different repo. Closing now
