### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by MikaTsur** [microsoft/playwright#29867]
### Version

1.34.0

### Steps to reproduce

VPN 

### Expected behavior

Iterate over all csv values and treat them the same

### Actual behavior

1. Loop over csv values and compare them with the UI (locator)
2. Playwrite having difficulties locating the last values in the loop/csv:
e.g.
csv:
ID,Price,Organic,Color
1,1.5,TRUE,Red
2,0.5,FALSE,Yellow
3,0.75,TRUE,Orange

loop:
    def extract_headers_from_csv(self, csv_file_path):
        with open(csv_file_path, 'r') as file:
            csv_reader = csv.reader(file)
            headers = next(csv_reader)  # next = the first csv row
            return headers

    def verify_headers(self, csv_file_path):
        expected_headers = self.extract_headers_from_csv(csv_file_path)
        for header in expected_headers:
            locator = self.page.get_by_role("columnheader", name=header)
            expect(locator).to_be_visible()
            expect(locator).to_have_count(1)
            
          In this Example as in other csv I used, It is not finding the Color although it is there(In page.pause/debug mode it works..)

### Environment

```shell
def verify_headers(self, csv_file_path):
        expected_headers = self.extract_headers_from_csv(csv_file_path)
        for header in expected_headers:
            if header == "xxx":
                continue
            locator = self.page.get_by_role("columnheader", name=header)
>           expect(locator).to_be_visible(timeout=50000)
E           AssertionError: Locator expected to be visible
E           Actual value: None 
E           Call log:
E           LocatorAssertions.to_be_visible with timeout 50000ms
E           waiting for get_by_role("columnheader", name="Color")

page_objects/Common/Panels/DataPanel/DataPanelInstance.py:51: AssertionError
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
