### ISSUE TITLE
[Bug]: Skipped test has weird 0 in report 

### ISSUE THREAD

**Issue by dimkin-eu** [microsoft/playwright#29861]
### Version

1.42.1

### Steps to reproduce

open report of skipped test
<img width="572" alt="Screenshot 2024-03-08 at 19 03 54" src="https://github.com/microsoft/playwright/assets/7899764/d9724d26-9fdf-45f4-acb5-e8bca941513e">

### Expected behavior

There could be either `0s` or nothing

### Actual behavior

`0` which scares a bit

### Environment

```shell
System:
    OS: macOS 14.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 6.49 GB / 32.00 GB
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    npm: 10.1.0 - /usr/local/bin/npm
    pnpm: 8.9.0 - /usr/local/bin/pnpm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by shriphad-rao** [comment]
Hi!
I'll work on this 
Can you please assign it to me?
