### ISSUE TITLE
[Feature]: Make it possible to run the report and trace on a subpath

### ISSUE THREAD

**Issue by mastoj** [microsoft/playwright#29866]
### 🚀 Feature Request

When running the reports it would be good to host them under a sub path, right now it seems like they have to run from the root. This would make it possible to serve multiple reports from one application.

### Example

The way I want to use this is to upload reports to azure blob storage, but I want to add them to a folder or multiple different container and then have an application on the outside that will list all reports and serve them by reading from the blob storage and serve the files.

It almost works except for the traces. The link to the trace is from the "root" and doesn't take into account where the application is running.

Example on local machine:
* Everything is located in local folder `/reports/sub-path`. That is, that folder contains the `index.html`, the `data` folder and the `trace` folder.
* The overall report works fine
* Clicking trace links to `/reports/trace`, the sub-path is removed and so it can't run.

### Motivation

I want to create a test overview application where I also can see historical reports and not just the latest one.

**Comment by mxschmitt** [comment]
I tried to reproduce it, but was not able to. Could you help me having reproduction steps?

1. Create some report
2. `npx http-server .` in some parent directory
3. Navigate to e.g. http://127.0.0.1:8080/Developer/playwright/playwright-report/
4. Click on the trace from the html report

They get resolved correctly for me.

Looks similar to https://github.com/microsoft/playwright/issues/23788.

**Comment by mastoj** [comment]
I have solved it now, but from what it looked like before I solved it the links to the trace didn't respect the parent folders. Could have been related to how I did it in nextjs. If you don't want to look at it further this can be closed from my perspective.
