### ISSUE TITLE
[BUG] middle-clicking link to open in new tab breaks response.body()

### ISSUE THREAD

**Issue by evilscheme** [microsoft/playwright#2987]
**Context:**
- Playwright Version: [1.2.0]
- Operating System: [Mac & LInux]
- Node version: [14.5.0]
- Browser: [Chromium]

**Code Snippet**

Code to reproduce issue:

```javascript
import * as pw from "playwright-chromium";

async function main() {
  let b = await pw.chromium.launch({ headless: true });

  let c = await b.newContext();
  let p = await c.newPage();

  c.route("**", (route) => {
    console.log("request: ", route.request().url());
    route
      .request()
      .response()
      .then((r) => {
        console.log("response: ", r?.url());

        r?.body()
          .then((b) => {
            console.log("body: ", b);
          })
          .catch((err) => {
            console.log("got error: ", err);
          });
      });
    route.continue();
  });

  await p.goto("https://happy-carson-d839d2.netlify.app/5/a.html");

  let links = await p.$$("a");

  for (let i = 0; i < links.length; i++) {
    // This works OK, but is a little gross
    await links[i].evaluate((e) => {
      e.setAttribute("target", "_new");
    });
    await links[i].click({ button: "left" });

    // This causes a CDP protocol error when trying to read response body
    await links[i].click({ button: "middle" });
  }
}

main();
```

**Describe the bug**

When clicking multiple links from a page, it's really handy to be able to open them in a new tab, so the click context still exists when you want to click the i-th link. Sending the "middle" mouse button modifier to the click() function seems to be the cleanest/easiest way to get this behavior, but it causes response.body() to error on the initial resource. The error message is: `Protocol error (Network.getResponseBody): No resource with given identifier foundError`.

I think I found a workaround, where I manually call setAttribute() on the link and set the "target" to "_blank", which has the desired behavior, but this is not very clean, and may have unintended consequences.

Thanks!

**Comment by dgozman** [comment]
@evilscheme, thank you for the issue - I can reproduce it.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
