### ISSUE TITLE
[Feature]: Add the "Update snapshots" checkbox to the Visual Studio Code extension.

### ISSUE THREAD

**Issue by yakitama5** [microsoft/playwright#29871]
### 🚀 Feature Request

In the "Test Explorer" pane of Visual Studio Code, there is a checkbox option for PlayWright's "Show browser". There is no "Update snapshots" checkbox option. Could you please add it?

### Motivation

I want to run a test from the "Test Explorer" pane and have it attached to the debugger, with the snapshot update option specified.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/16970
