### ISSUE TITLE
[Bug]: Html with emoji "🎟" not converting to pdf.

### ISSUE THREAD

**Issue by Visheshmongia** [microsoft/playwright#29888]
### Version

1.41.2

### Steps to reproduce

Pass this zip file to playwright to convert the html to pdf using chromium in headless mode. 

### Expected behavior

Expected behaviour is that the html (zip) converts to pdf. Earlier versions of playwright gave the expected output pdf as attached here. The version 1.41.2 is giving errors for the same. 
[Playwright_earlier_version_output.pdf](https://github.com/microsoft/playwright/files/14568836/Playwright_earlier_version_output.pdf)

### Actual behavior

The html containing specific emoji "🎟" gives **Protocol Error** and printing fails.
[Playwright_Error_withEmoji.zip](https://github.com/microsoft/playwright/files/14568813/Playwright_Error_withEmoji.zip)

### Environment

```shell
System:
    OS: macOS 14.3
    CPU: (10) x64 Apple M1 Max
    Memory: 686.81 MB / 32.00 GB
  Binaries:
    Node: 14.18.2 - /usr/local/bin/node
    npm: 6.14.15 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by mxschmitt** [comment]
I tried to create a pdf doing the following but it was working for me in headless and headed. What am I doing different?

```ts
import { chromium } from 'playwright';

(async () => {
  const browser = await chromium.launch({ headless: true});
  const context = await browser.newContext();
  const page = await context.newPage();

  await page.goto('file:///Users/max/Downloads/Playwright_Error_withEmoji/index.html')
  await page.pdf({ path: 'screenshot.pdf' });

  await context.close();
  await browser.close();
})();
```

`Protocol Error` sounds like a bug, we need clear reproduction steps in order to look into issues like this, otherwise we can't act. Thanks for your understanding.

**Comment by mxschmitt** [comment]
Closing as per above. Feel free to re-file / provide more details.
