### ISSUE TITLE
[Feature]: create-playwright --test-dir option

### ISSUE THREAD

**Issue by karlhorky** [microsoft/playwright#29891]
### 🚀 Feature Request

Allow for specifying `testDir` non-interactively with [`create-playwright`](https://github.com/microsoft/create-playwright), eg:

```bash
$ pnpm create playwright --test-dir=playwright
# This will create and use the test directory `playwright` and skip the following question:
# ? Where to put your end-to-end tests? ›
```

This should have no effect on component testing.

### Example

See above

### Motivation

Currently it's not possible to pass a custom `testDir` in non-interactively

### Implementation

A prerequisite to enable the behavior of skipping prompts when options are passed in:

- #29894

Setting the option would need to be changed here:

1. https://github.com/microsoft/create-playwright/blob/22a512b263d1130cdfcd9963b9c228dccaa29a6d/src/generator.ts#L79-L91
2. https://github.com/microsoft/create-playwright/blob/22a512b263d1130cdfcd9963b9c228dccaa29a6d/src/generator.ts#L118-L123

Another interesting part of the code is [the options list](https://github.com/microsoft/create-playwright/blob/22a512b263d1130cdfcd9963b9c228dccaa29a6d/src/cli.ts#L49-L63): 

```ts
Usage: npx create-playwright@latest [options] [rootDir]
    Available options are:
      --help: print this message
      --browser=<name>: browsers to use in default config (default: 'chromium,firefox,webkit')
      --no-browsers: do not download browsers (can be done manually via 'npx playwright install')
      --install-deps: install dependencies (default: false)
      --next: install @next version of Playwright
      --beta: install @beta version of Playwright
      --ct: install Playwright Component testing
      --quiet: do not ask for interactive input prompts
      --gha: install GitHub Actions
      --lang=<js>: language to use (default: 'TypeScript'. Potential values: 'js', 'TypeScript')
```

### Related

- #29893
- #29894

**Comment by karlhorky** [comment]
## Workaround

It seems like [there's an undocumented environment variable `TEST_OPTIONS` which can be set to a JSON string](https://github.com/microsoft/create-playwright/blob/22a512b263d1130cdfcd9963b9c228dccaa29a6d/src/generator.ts#L79-L81):

```ts
  private async _askQuestions(): Promise<PromptOptions> {
    if (process.env.TEST_OPTIONS)
      return JSON.parse(process.env.TEST_OPTIONS);
```

So probably this can be used to pass `testDir` and all other options (on non-Windows, in a less ergonomic way):

```bash
TEST_OPTIONS='{"installGitHubActions": true, "language": "TypeScript", "installPlaywrightDependencies": false, "testDir": "playwright", "framework": undefined, "installPlaywrightBrowsers": true}' pnpm create playwright
```

**Comment by mxschmitt** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

**Comment by karlhorky** [comment]
@mxschmitt oh, that's disappointing. It's a pretty simple option (very few lines of code), and won't introduce too much maintenance overhead. Not sure why the PR is not accepted.
