### ISSUE TITLE
[Feature]: create-playwright: --quiet by default if all required CLI flags passed

### ISSUE THREAD

**Issue by karlhorky** [microsoft/playwright#29894]
### 🚀 Feature Request

If a user specifies a [`create-playwright`](https://github.com/microsoft/create-playwright) option (eg. `--no-browsers`), `create-playwright` should use this option value and skip the interactive question.

This effectively makes the `create-playwright` behavior the same as setting the `--quiet` option, if users pass all required options (see below, from [the options list](https://github.com/microsoft/create-playwright/blob/22a512b263d1130cdfcd9963b9c228dccaa29a6d/src/cli.ts#L49-L63)): 

```ts
Usage: npx create-playwright@latest [options] [rootDir]
    Available options are:
      ...
      --quiet: do not ask for interactive input prompts
```

### Implementation

`enquirer` supports skipping prompts in the prompt options if certain criteria is met: 

- https://github.com/enquirer/enquirer/issues/364#issuecomment-1991338065

### Example

```bash
$ pnpm create playwright --test-dir=test --lang=ts --browsers
# This will set custom options non-interactively and skip the interactive prompts
```

The example above requires the `create-playwright` flags `--test-dir` and `--browsers`, which are feature requests here:

- https://github.com/microsoft/playwright/issues/29891
- #29893

### Motivation

This will cause the `create-playwright` behavior to match intuitive behavior of other well-known CLIs in the JS/TS ecosystem

### Alternatives Considered

Use the verbose, undocumented [environment variable `TEST_OPTIONS` which can be set to a JSON string](https://github.com/microsoft/create-playwright/blob/22a512b263d1130cdfcd9963b9c228dccaa29a6d/src/generator.ts#L79-L81):

```bash
TEST_OPTIONS='{"installGitHubActions": true, "language": "TypeScript", "installPlaywrightDependencies": false, "testDir": "playwright", "installPlaywrightBrowsers": true}' pnpm create playwright
```

### Related

- #29891
- #29893

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
