### ISSUE TITLE
[Bug]: Some sites assume that a scraper is running and block certain access

### ISSUE THREAD

**Issue by darshandp007** [microsoft/playwright#29895]
### Version

1.42.1

### Steps to reproduce

When I run the test on the Playwright, site assuming it's a scrapper, it seemed to be blocking further requests. Some systems such as cloudfare and other thinks it as scrapper or some outsider system and restrict us from programmatic access. 

However, the same actions try in different browsers as following: 
- Not working in playwright - Chromium, Webkit
- Working in playwright - Firefox
- Working in normal browser - Chrome

Is anyone know how to make it work this things with playwright?

### Expected behavior

It should work same in all browser. I mean it should work in chromium and webkit.

### Actual behavior

While running test case some site blocking request in chromium, webkit browser of playwright. And seems like different behaviour as compare to other browser during execution.

### Environment

```shell
Node: 16.16.0
```

**Comment by mxschmitt** [comment]
Playwright is for end-to-end testing where we require the user to own the site - hence anti-spam protection etc. should be disabled.

Closing by that.
