### ISSUE TITLE
[Feature]: create-playwright --browsers option

### ISSUE THREAD

**Issue by karlhorky** [microsoft/playwright#29893]
### 🚀 Feature Request

Allow for specifying `installPlaywrightBrowsers` non-interactively with [`create-playwright`](https://github.com/microsoft/create-playwright), eg:

```bash
$ pnpm create playwright --browsers
# This will install Playwright browsers and skip the following question:
# ? Install Playwright browsers (can be done manually via `pnpm exec playwright install`)? ›
```

### Example

See above

### Motivation

Currently it's not possible to pass a `true` value for `installPlaywrightBrowsers` alone, without specifying other options

The closest thing is the `--quiet` option (see below, from [the options list](https://github.com/microsoft/create-playwright/blob/22a512b263d1130cdfcd9963b9c228dccaa29a6d/src/cli.ts#L49-L63)): 

```ts
Usage: npx create-playwright@latest [options] [rootDir]
    Available options are:
      ...
      --quiet: do not ask for interactive input prompts
```

However, this also sets other options at the same time, and disables any interactive prompts, both of which may be undesirable side effects.

### Implementation

A prerequisite to enable the behavior of skipping prompts when options are passed in:

- #29894

### Related

- #29891
- #29894

**Comment by karlhorky** [comment]
## Workaround

It seems like [there's an undocumented environment variable `TEST_OPTIONS` which can be set to a JSON string](https://github.com/microsoft/create-playwright/blob/22a512b263d1130cdfcd9963b9c228dccaa29a6d/src/generator.ts#L79-L81):

```ts
  private async _askQuestions(): Promise<PromptOptions> {
    if (process.env.TEST_OPTIONS)
      return JSON.parse(process.env.TEST_OPTIONS);
```

So probably this can be used to pass `installPlaywrightBrowsers` and all other options (on non-Windows, in a less ergonomic way):

```bash
TEST_OPTIONS='{"installGitHubActions": true, "language": "TypeScript", "installPlaywrightDependencies": true, "testDir": "playwright", "installPlaywrightBrowsers": true}' pnpm create playwright
```

**Comment by mxschmitt** [comment]
What is your use-case for it? `TEST_OPTIONS` is only for internal tests so its an undocumented option which is subject for change.

**Comment by karlhorky** [comment]
> What is your use-case for it?

I want to be able to run the `pnpm create playwright` command non-interactively, without it asking me questions. This is for teaching beginners to create and write end to end tests. (also the motivation for all of the other feature requests I added at #29891 #29894 #29896)

**Comment by mxschmitt** [comment]
Is this for some kind of workshop I assume? Sounds like a GitHub template/boilerplate repository would fit better there instead of increasing the scope of the API for create-playwright. This also reduces the risk of failure in the future, when we e.g. change the way create-playwright works, change the output, introduce a new major API version etc.

**Comment by karlhorky** [comment]
@mxschmitt it's not only for this use case - I would also just like this + expect this as a user of the CLI

All of these feature requests could probably fit into a PR of about 20-30 lines, most of these feature are already built in the existing setup of the CLI. In my opinion, I don't think this introduces new complexity or maintenance burden.

**Comment by karlhorky** [comment]
@mxschmitt they are programming courses including web development bootcamps (our teaching style is to use tools and the options they provide, not provide some preconfigured starter). But I think maybe that is putting too much emphasis on the courses / teaching aspect anyway.

It's not only about the use case of the bootcamps and other courses we provide - I would also just personally expect this as a CLI user who has experienced many UX flows with different CLIs:

1. Options should be able to be passed via the CLI
2. Options passed via the CLI make it so that the interactive questions disappear

I think this is a pretty common pattern and helps users to experience less surprise with CLI behavior.

All of these feature requests could probably fit into a PR of about 20-30 lines, and most of the functionality that these features require are already built in the existing setup of the CLI. In my opinion, I don't think this introduces new complexity or maintenance burden.

**Comment by karlhorky** [comment]
What I mean to suggest is a flag to non-interactively mirror is the functionality of answering "Yes" (true) to this question in an interactive TTY prompt:

```
? Install Playwright browsers (can be done manually via `pnpm exec playwright install`)? ›
```

(accepting the default browsers, without having to answer Yes to this question)

As a user, I would want to "just use the default browsers Playwright installs when answering yes", not have to remember a list of different browsers to keep in my flags list.

**Comment by mxschmitt** [comment]
Ah I see, so --browsers is confusing, it should be `--install-browsers` not `--browser` which is for selecting which browser to use. Feel free to create a PR for it.

**Comment by karlhorky** [comment]
> Ah I see, so `--browsers` is confusing, it should be `--install-browsers` not `--browser` which is for selecting which browser to use

I agree the name I proposed above is confusing - I proposed it for API symmetry / consistency / discoverability with the `--no-browsers` flag.

Maybe to maintain this symmetry, the new PR could also add a new alias for `--no-browsers` called `--no-install-browsers`

So after the PR, we would have:

- `--no-browsers` and `--no-install-browsers` (aliases)
- `--install-browsers`

We could also consider dropping the `--no-browsers` flag, but that would be a breaking change

**Comment by karlhorky** [comment]
The more I think about it, the more I think it's better to maintain the symmetry of my original proposal `--browsers` (so that it's discoverable for users that they can run `--no-browsers` and `--browsers`)

**Comment by karlhorky** [comment]
@mxschmitt I opened a PR with a demo of my suggested approach, including:

1. a demo of the `--browsers` flag
2. a consolidation of the options to avoid the string literal union type and the help message from getting out of sync
3. a check to make sure that both of a boolean options pair are not passed

- https://github.com/microsoft/create-playwright/pull/119

This PR depends on another smaller PR, in which I return `0` as a status code from the `--help` option:

- https://github.com/microsoft/create-playwright/pull/118

**Comment by mxschmitt** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

**Comment by karlhorky** [comment]
@mxschmitt too bad, it's disappointing that small features are not considered in different ways. It's discouraging to my motivation, as a community member who wants to contribute.
