### ISSUE TITLE
[Bug]: Playwright ct-core type defs not aligned with exported API

### ISSUE THREAD

**Issue by jan-molak** [microsoft/playwright#29903]
### Version

1.42.1

### Steps to reproduce

As per our conversation at #29879, Playwright ct-core 1.42.1 type definitions are misaligned with the exported constants.
This affects custom component testing integrations that need to suppress TypeScript import error TS2305.

As you can see below, `playwright-ct-core/index.js` exports:

https://github.com/microsoft/playwright/blob/7f6f17d1c343f88400c498fd1c3defbd7f420056/packages/playwright-ct-core/index.js#L42

while the type definitions are missing the `test` const:

https://github.com/microsoft/playwright/blob/7f6f17d1c343f88400c498fd1c3defbd7f420056/packages/playwright-ct-core/index.d.ts#L48

### Expected behavior

`index.d.ts` should export the `test` const to allow for integrating custom component testing integrations with ct-core 

### Actual behavior

```ts
import { 
  defineConfig,                           // works fine
  devices,
  expect,
  
  // @ts-expect-error TS2305
  test as componentTest                   // requires a ts-expect-error
} from '@playwright/experimental-ct-core';
```

### Additional context

We've built a custom Playwright CT integration to enable testing web components while the official Playwright integration is not available yet.

### Environment

```shell
System:
    OS: macOS 14.4
    CPU: (12) arm64 Apple M2 Max
    Memory: 53.28 GB / 96.00 GB
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 8.15.3 - ~/.nvm/versions/node/v20.11.1/bin/pnpm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    playwright-core: 1.42.1 => 1.42.1
```

**Comment by pavelfeldman** [comment]
We don't expect users to depend on @playwright/experimental-ct-core - it is experimental.

**Comment by jan-molak** [comment]
Hey @pavelfeldman and thanks for getting back to me. I appreciate CT is experimental, but is there any reason why the type definitions should not be in sync with the JavaScript code, or is it just a simple omission that could be fixed by https://github.com/microsoft/playwright/pull/29879?

**Comment by pavelfeldman** [comment]
> I'd expect that integrations like https://github.com/sand4rt/playwright-ct-angular or https://github.com/sand4rt/playwright-ct-web by @sand4rt would need to rely on those APIs and follow the pattern your team has established to support Playwright 1.42 until official Playwright support is available.

The reality is that we are going to break these apis and these packages on a regular basis.

> Or is there a different recommended path for integration libraries and frameworks building on Playwright?

The only recommended way is depending @playwright/test public and documented APIs. Everything else is experimental. We can probably make index.js blank in @playwright/experiemental-ct-core to send a stronger signal. We will import test from @playwright/experiemental-ct-core/internal or something similar.

**Comment by jan-molak** [comment]
> We will import test from @playwright/experiemental-ct-core/internal or something similar

Makes sense

> The reality is that we are going to break these apis and these packages on a regular basis.

Is there, perhaps, any rough timeline around when Playwright CT APIs will stabilise and the module will no longer be experimental?
