### ISSUE TITLE
[Bug]: Api request context is disposed after beforeAll hook completion

### ISSUE THREAD

**Issue by hubesal** [microsoft/playwright#29905]
### Version

1.42.1

### Steps to reproduce

1. Clone repo: _https://github.com/hubesal/playwright.bug_
2. npm install
3. npx playwright install --with-deps
4. npx playwright test

### Expected behavior

_beforeAll_, _beforeEach_, test and _afterEach_ are run successfully

### Actual behavior

    Error: apiRequestContext.get: Target page, context or browser has been closed

       at ..\api\base.api.client.ts:9

       7 |
       8 |   protected async get(url: string): Promise<any> {
    >  9 |     const response = await this.request.get(url, {
         |                                         ^
      10 |       headers: {
      11 |         //'Authorization': `Bearer qwwertyuiuiyrt`
      12 |       },

        at ApiClient.get (C:\solutions\playwright.bug\api\base.api.client.ts:9:41)
        at ApiClient.getPlanets (C:\solutions\playwright.bug\api\api.client.ts:20:33)
        at C:\solutions\playwright.bug\tests\example.spec.ts:16:19

### Additional context

seems apiClient object gets disposed in _beforeAll_ hook and cannot be used in remaining hooks. This behaviour is different from the one in 1.39 version - the last one this code was working.

### Environment

```shell
System:
Windows 10 with latest update KB5033052
Binaries:
- Node 20.11.1
- npm v 10.2.4
```

**Comment by mxschmitt** [comment]
The `request` fixture which you are using is a `test` fixture. So you get it per test. It's getting used in `beforeAll` so it will work in the first test, but for the second test it has the disposed APIRequestContext from the first test.

You should instead change it to a `beforeEach` in line 8 and then it will work.

**Comment by hubesal** [comment]
Wouldn't it work out in a way below:
 `apiClient = new ApiClient(reuqest)` is defined in line 10 and set in `apiClient` variable in line 5, so it can be reused in `beforeEach` ?
It worked like this in 1.39. As an additional step, you can rollback to 1.39 and see it working.

**Comment by mxschmitt** [comment]
I see, folding into https://github.com/microsoft/playwright/issues/29260

The workaround in the meantime would be beforeAll -> beforeEach.
