### ISSUE TITLE
[Feature]: Mock post without HAR

### ISSUE THREAD

**Issue by FanilZarip** [microsoft/playwright#29917]
### 🚀 Feature Request

Ability to Mock body and response a post request

### Example

The form is filled out and a request is sent to the server.
Then we get the answer 200.
But we need to check the app when the response with status 500(or another) from the server.

Therefore, we need to mock the server response with status 500 and its body so that the app can check the server error.

Now this can be mocked on HAR mocks. But they are tied to the browser version and app address, so they need to be changed frequently.

Maybe it can be mocked right now with another ways?

### Motivation

There will be a unique opportunity to mock post requests. Tests will become more stable, simpler and without connection to the browser and har files.

**Comment by mxschmitt** [comment]
Playwright supports network mocking out of the box, see here:

- https://playwright.dev/docs/network#network-mocking
- https://playwright.dev/docs/network#handle-requests

This should work for your sceneario.
