### ISSUE TITLE
[Bug]: False positive pipeline when using retries in serial mode 

### ISSUE THREAD

**Issue by BeeMargarida** [microsoft/playwright#29922]
### Version

1.42.1

### Steps to reproduce

Repo here: https://github.com/BeeMargarida/playwright-serial-retries-bug

You can see the issue in the [pipeline](https://github.com/BeeMargarida/playwright-serial-retries-bug/actions/runs/8266118282/job/22613372136), in the `Run Playwright tests` step.

Basically, the issue happens in serial mode, where if different tests fail on retries, it will skip not run certain tests and mark the run as successful. 

Simple example of 4 tests and 1 retry:

**first run:**
passes
fails
skips
skips

**1st retry:**
fails
skips
skips
skips

The run ends with 2 flaky tests, 2 skipped tests and marked as successful. This is not successful, it's a false positive since it didn't run all tests.

### Expected behavior

The pipeline fails if it doesn't run all tests in a retry, in serial mode.

### Actual behavior

The pipeline shows as successful even though some tests were not executed.

### Additional context

I'm open to contributing a solution for this, just want feedback on this bug first.

I know serial mode is not recommended, but the use case for this really requires serial mode since it's an offline first PWA that does a big setup on first launch, so it's not useful to launch a new isolated context for each test.

### Environment

```shell
System:
  OS: Linux 6.7 EndeavourOS
  CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
  Memory: 15.79 GB / 31.27 GB
  Container: Yes
Binaries:
  Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
  Yarn: 1.22.21 - ~/.nvm/versions/node/v18.19.0/bin/yarn
  npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
IDEs:
  VSCode: 1.87.2 - /usr/bin/code
Languages:
  Bash: 5.2.26 - /usr/bin/bash
npmPackages:
  @playwright/test: 1.42.1 => 1.42.1
```

**Comment by scottfwalter** [comment]
@BeeMargarida I think this is the same as https://github.com/microsoft/playwright/issues/28322

**Comment by BeeMargarida** [comment]
> @BeeMargarida I think this is the same as #28322

You're right, I don't know how I missed that one. Well, if it helps, now there's another repo with reproduction of the issue.
I definitely consider this a bug, the CI shouldn't pass if some tests were skipped (if they were not explicitly set to be skipped).

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/28322
