### ISSUE TITLE
Does playwright support testing in different versions of each browsers ? Eg: For Mozilla Firefox, is it possible to test in firefox versions 100.0, 120.0, latest etc

### ISSUE THREAD

**Issue by manacy-keyvalue** [microsoft/playwright#29920]
### Please do not submit this issue.

- [X] I understand

**Comment by mxschmitt** [comment]
We recommend testing in the latest version of the browsers by using the latest Playwright version, since thats the version the users are using. Browser vendors force users to use the latest version.

**Comment by manacy-keyvalue** [comment]
@mxschmitt  Is there any way to test on different versions though ?
I agree that ideally, users should be using latest version of browsers. But they could still be using older versions. It would be useful to detect bugs early.
I want to make sure that the tests are running successfully atleast 3 versions behind the latest version in different browser. Just wondering if you guys support any such feature.

**Comment by mxschmitt** [comment]
You can use e.g. Stable Browser channels: https://playwright.dev/docs/browsers#defaults or use 1-2 older Playwright versions.

**Comment by manacy-keyvalue** [comment]
Thank you very much @mxschmitt
