### ISSUE TITLE
[Bug]: opening a new window from current page, closing it and uploading a file with filechooser raises an error with firefox

### ISSUE THREAD

**Issue by ntraut** [microsoft/playwright#29923]
### Version

1.42.1

### Steps to reproduce

1. Clone my repo at https://github.com/ntraut/playwright-filechooser-example
2. npm install
3. npx playwright test
4. You should see the error come up

### Expected behavior

all the tests should pass

### Actual behavior

the test passes on chromium and webkit but not on firefox

### Additional context

the reported error is:
Error: fileChooser.setFiles: Protocol error (Page.describeNode): error in channel "content::9/10/3": exception while running method "describeNode" in namespace "page": frame.domWindow() is undefined _describeNode@chrome://juggler/content/content/PageAgent.js:417:30
_onMessageInternal@chrome://juggler/content/SimpleChannel.js:237:37
_onMessage@chrome://juggler/content/SimpleChannel.js:194:12
bindToActor/actor.receiveMessage@chrome://juggler/content/SimpleChannel.js:39:44

    at fileChooser.setFiles: Protocol error (/playwright-filechooser-example/Page.describeNode): error in channel "content::9/10/3": exception while running method "describeNode" in namespace "page": frame.domWindow() is undefined _describeNode@chrome:/juggler/content/content/PageAgent.js:417:30)
    at /playwright-filechooser-example/_onMessageInternal@chrome:/juggler/content/SimpleChannel.js:237:37
    at /playwright-filechooser-example/_onMessage@chrome:/juggler/content/SimpleChannel.js:194:12
    at /playwright-filechooser-example/bindToActor/actor.receiveMessage@chrome:/juggler/content/SimpleChannel.js:39:44
    at /playwright-filechooser-example/tests/upload.spec.js:19:21

maybe it is linked to #19114. i also noticed that the bug doesn't appear with playwright v1.26.1.

### Environment

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 227.59 MB / 32.00 GB
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
  Languages:
    Bash: 5.1.16 - /opt/homebrew/bin/bash
  npmPackages:
    @playwright/test: ^1.42.1 => 1.42.1
```

**Comment by mxschmitt** [comment]
I can repro, thanks for the great repro!

**Comment by mxschmitt** [comment]
Should be fixed after https://github.com/microsoft/playwright/pull/30950
