### ISSUE TITLE
[Bug]: "Go to file" button opens VSCode when my default text editor for `.ts` files is VSCode - Insiders

### ISSUE THREAD

**Issue by baptisteArno** [microsoft/playwright#29934]
### Version

1.41.2

### Steps to reproduce

- Make VSCode - Insiders your default editor for `.ts` files
- Write a test
- Run the Playwright UI
- Click on the "Go to file" button

### Expected behavior

VSCode Insiders should open

### Actual behavior

VSCode opens

### Environment

```shell
System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 809.78 MB / 16.00 GB
  Binaries:
    Node: 20.8.1 - ~/Library/Caches/fnm_multishells/1706_1710406391151/bin/node
    npm: 10.1.0 - ~/Library/Caches/fnm_multishells/1706_1710406391151/bin/npm
    pnpm: 8.15.4 - /opt/homebrew/bin/pnpm
    bun: 1.0.26 - ~/.bun/bin/bun
  IDEs:
    VSCode: 1.87.2 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.41.2 => 1.41.2
```

**Comment by mxschmitt** [comment]
Investigation: We open it [here](https://github.com/microsoft/playwright/blob/914208c567addd4ba985a5decd37b05e15128cd0/packages/playwright/src/runner/uiMode.ts#L96). While not everyone has js/ts file extensions configured to open in vscode, it looks like there is no way for us to find out if we should open it in code or code-insiders.

(Without introducing a new open/setting). I'll mark it as a feature request, so we could in the future select the editor in which UI Mode should open files.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/22158
