### ISSUE TITLE
[Bug]: Executable doesn't exist at /home/runner/.cache/ms-playwright/chromium-1105/chrome-linux/chrome

### ISSUE THREAD

**Issue by DCamaraLopez** [microsoft/playwright#29930]
### Version

1.41.1

### Steps to reproduce

- Creating YML to execute into Git Hub Action.
- Installing the playwright dependencies
- Missing Chromium version for Linux

Package.json
![image](https://github.com/microsoft/playwright/assets/115648761/c6ef3164-0aca-4b4a-a74b-3c0e12d8ee90)

YML file:
![image](https://github.com/microsoft/playwright/assets/115648761/7250c82f-3596-4449-9436-0b88b73f5598)

Installing Browsers:
![image](https://github.com/microsoft/playwright/assets/115648761/6b63420c-34c6-427e-a622-512dbd00576d)

Browsers installed:
![image](https://github.com/microsoft/playwright/assets/115648761/4d627d56-af62-4fb4-bdf4-b6add0ad4fa8)

Error:
![image](https://github.com/microsoft/playwright/assets/115648761/e17116b9-ed13-44f0-ac9a-9ca5991cc02f)

### Expected behavior

Chromium should be executed smoothly

### Actual behavior

I can see the versions downloaded are different that the one is looking for BrowserType for linux version

### Environment

```shell
System:
OS: Windows 10
CPU: x-64
Binaries: 
Node: 20.10.0
npm: 10.0.0
npmPackages:
@cucumber/cucumber: 9.5.1
@playwright/test: 1.41.1
```

**Comment by mxschmitt** [comment]
Looks like your project does depend on multiple Playwright versions. It downloads `1097` while your tests wants to run `1105`. We strongly recommend only depend on `@playwriht/test` in your package.json. Remove the `playwright` entry there. Also you don't need to list them twice as a dependency and devDependency, once is enough.
