### ISSUE TITLE
[BUG] Downloads not working properly when browser is launched with launchPersistentContext

### ISSUE THREAD

**Issue by VikramTiwari** [microsoft/playwright#2993]
**Context:**
- Playwright Version: 1.2.1
- Operating System: Mac
- Node version: ~12
- Browser: Chromium

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium} = require('playwright');

(async () => {
  const context = await chromium.launchPersistentContext('./udd', {
    headless: false,
    acceptDownloads: true
  });
  const page = await context.newPage()
  await page.goto(`https://support.spatialkey.com/spatialkey-sample-csv-data/`)
  await page.click(`//html/body/div[1]/div[2]/section/article/div[1]/h5[1]/a`)
})();
```

**Describe the bug**

After running the script, I was expecting the downloaded file to be usable but seems like the file was downloaded as a random UUID filename and without any filetype value.

Sample:
<img width="693" alt="Screen Shot 2020-07-16 at 7 58 44 PM" src="https://user-images.githubusercontent.com/1330677/87743874-d0cbd180-c79e-11ea-916d-9e22216433e1.png">

Expected:
<img width="695" alt="Screen Shot 2020-07-16 at 7 58 54 PM" src="https://user-images.githubusercontent.com/1330677/87743880-d5908580-c79e-11ea-988f-7085a15706c6.png">

**Comment by mxschmitt** [comment]
For what do you need the file name? You can use the [`suggestFilename()`](https://playwright.dev/#version=v1.2.1&path=docs%2Fapi.md&q=downloadsuggestedfilename) method to get the original file name in the code.

Or do you plan to use Playwright and that the user will interact with it and check e.g. the downloaded files? We are curious to find more about your use case!

**Comment by VikramTiwari** [comment]
Hey @mxschmitt Thanks for the suggestion. I like the modularity that playwright provides.

For me it's the second use case you described where a user is interacting with the browser opened by playwright. In this case, my script doesn't really know if user is starting a download.

**Comment by aslushnikov** [comment]
> For me it's the second use case you described where a user is interacting with the browser opened by playwright. In this case, my script doesn't really know if user is starting a download.

@VikramTiwari we currently focus on testing and explicitly don't support this scenario. I'll close this since there are no plans to address this.

**Comment by VikramTiwari** [comment]
I understand @aslushnikov. 

Do you think a workaround could be to listen on `page.on('download')` event on all the pages and then on each download use `suggestFilename()` method. I am hoping that it would result in normal file downloads. Am I thinking correctly here?
