### ISSUE TITLE
[Feature] Implement Network Throttling

### ISSUE THREAD

**Issue by FanilZarip** [microsoft/playwright#29935]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

_Originally posted by @pavelfeldman in https://github.com/microsoft/playwright/issues/8622#issuecomment-1284845091_

**Comment by mxschmitt** [comment]
Folding back into https://github.com/microsoft/playwright/issues/8622#issuecomment-1284845091.

If you are still interested in the feature, we recommend upvoting the closed issue instead.

**Comment by mbUSC** [comment]
This would be very useful
