### ISSUE TITLE
[Bug]: Incorrectly zoomed in timeline previews of Webkit traces

### ISSUE THREAD

**Issue by nbaldzhiev** [microsoft/playwright#29943]
### Version

1.37.1

### Steps to reproduce

1. (Optional) Clone https://github.com/nbaldzhiev/playwright-webkit-trace-zoom-bug.
2. Ask to be a collaborator; then either open a PR or manually trigger the workflow.
3. Open the GitHub Actions workflow execution and download the report, which is uploaded as an artifact.
4. Load the report's trace in a trace viewer.
5. Hover over the timeline.

### Expected behavior

The little popup, which appears with the preview of the map, is centred correctly.

### Actual behavior

The little popup, which appears with the preview of the map, is NOT centred correctly - it is overly zoomed in 

### Environment

```shell
GitHub Actions runner `ubuntu-latest`.
```

**Comment by mxschmitt** [comment]
Could you verify if the issue reproduces on the latest Playwright version? 1.42.1 as of today.

**Comment by nbaldzhiev** [comment]
> Could you verify if the issue reproduces on the latest Playwright version? 1.42.1 as of today.

I just tried with `"@playwright/test": "^1.42.1",` and it worked:

[711d1c68af1ed955f04fe026b8af7ce01bb8fcc6.zip](https://github.com/microsoft/playwright/files/14613814/711d1c68af1ed955f04fe026b8af7ce01bb8fcc6.zip)

I am not a fan of updating to the latest versions right away, though. @mxschmitt Can you point me out to an earlier version where this is also fixed, or it was fixed just now? And also, does your proposal hint that you don't plan on fixing that for `1.37.x` versions?

**Comment by mxschmitt** [comment]
Awesome. We strongly recommend staying [up to date](https://playwright.dev/docs/best-practices#keep-your-playwright-dependency-up-to-date) with the latest version in order to test the actual browser versions your customers are using.
