### ISSUE TITLE
[Question] Is there a way to set startingUrl

### ISSUE THREAD

**Issue by VikramTiwari** [microsoft/playwright#2994]
The aim is to replace about:blank page with some other page.

I am expecting something like the sample here: https://github.com/GoogleChrome/chrome-launcher#launching-chrome

**Comment by aslushnikov** [comment]
> Is there a way to set startingUrl

@VikramTiwari there's no way - we currently hard-code `about:blank` there. Can you share more details why this doesn't work? Is it for better aesthetics?

P.S. For a regular `browserType.launch()`, there's no starting page, so I assume this question applies to `browserType.launchPersistentContext()`.

**Comment by VikramTiwari** [comment]
Hey @aslushnikov! Yes, it was with `launchPersistentContext`. The major reason is aesthetics. It would be even better if that extra tab was never created.

**Comment by aslushnikov** [comment]
> The major reason is aesthetics. It would be even better if that extra tab was never created.

@VikramTiwari This doesn't really work for persistent context, and there are no plans to support this scenario at the moment. The best I can suggest is using `page.goto` to navigate the initial page there.

**Comment by VikramTiwari** [comment]
Ah! I understand. The suggested solution should work. I will try and report back on the status.
