### ISSUE TITLE
[Bug]: confusing error message on double dispose()

### ISSUE THREAD

**Issue by WestonThayer** [microsoft/playwright#29945]
### Version

1.42.1

### Steps to reproduce

```js
import { test } from "@playwright/test";

test("Attempt double dispose", async ({ page }) => {
  await page.goto("https://example.com/");
  const h = await page.evaluateHandle("document.activeElement");
  h.dispose();
  h.dispose();
});
```

1. Run the above test

### Expected behavior

An error message that suggests .dispose() can't be called twice. It might be nice if it didn't close/crash the browser as well.

### Actual behavior

Error on the 2nd call is: `Error: elementHandle.dispose: Target page, context or browser has been closed`.

### Additional context

We hit this in a less obvious way. We also have a `h.asElement()` call, and were keeping references to both the JSHandle and the ElementHandle. Hit this when calling `ElementHandle.dispose()` and `JSHandle.dispose()` on the same underlying handle.

### Environment

```shell
System:
    OS: macOS 14.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 87.92 MB / 16.00 GB
  Binaries:
    Node: 18.18.2 - /opt/homebrew/opt/node@18/bin/node
    npm: 9.8.1 - /opt/homebrew/opt/node@18/bin/npm
  IDEs:
    VSCode: 1.85.1 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.42.1 => 1.42.1
```

**Comment by mxschmitt** [comment]
You are not awaiting dispose(), have you tried awaiting it? `await h.dispose()`

**Comment by WestonThayer** [comment]
Oops! I didn't realize that returned a Promise. Thanks for the link. No change in results when adding `await` though.

```
Error: elementHandle.dispose: Target page, context or browser has been closed

   9 |   const h = await page.evaluateHandle("document.activeElement");
  10 |   await h.dispose();
> 11 |   await h.dispose();
     |           ^
  12 |   await page.goto("https://assistivlabs.com");
  13 | });
  14 |
```
