### ISSUE TITLE
[Feature]: Automated testing for native mobile apps

### ISSUE THREAD

**Issue by hikayati** [microsoft/playwright#29948]
### 🚀 Feature Request

I read somewhere about Playwright initiatives to cover mobile apps natively built. what is the progress on this? Actually I am trying to unify the test process for web and mobile using a unified test cases written in Gherkin style.

### Motivation

Adopt Gherkin style for tests creation, and maybe reuse the same test cases built for web to run the same tests on mobile apps.

**Comment by ltsuda** [comment]
Please, see the information I've found related to your request (I'm not from Playwright team).

BDD Feature Request Issue:
https://github.com/microsoft/playwright/issues/11975

Alternatives:
https://github.com/serenity-js/serenity-js-cucumber-playwright-template
https://github.com/Tallyb/cucumber-playwright

There are multiple issues relative to native mobile testing but all redirects to this main one:
https://github.com/microsoft/playwright/issues/1122

Android/Web Experimental - https://playwright.dev/docs/api/class-android

**Comment by mxschmitt** [comment]
Closing as per above. Playwright is focusing on Web Automation as of today. For Cucumber integrations, see above.
