### ISSUE TITLE
[Question] Is it possible to customize both user-data-dir and websocket port

### ISSUE THREAD

**Issue by VikramTiwari** [microsoft/playwright#2995]
Use case:
The goal is to launch a browser on server that's always up. I want to ensure that I can sign in to that browser and it will retain my credentials. Even after I restart my VM, the browser will retain all the user preferences, cookies etc. The way to achieve this would be to use both `wsEndpoint` and `userDataDir`.

From what I have understood:
- use `launchPersistentContext` to launch with `userDataDir` but it doesn't allow `wsEndpoint`
- use `launchServer` to launch with `wsEndpoint` but it doesn't allow `userDataDir`

I tried using websocket port with `launchPersistentContext` but the code crashes with following error log of timeout:

```
TimeoutError: Timeout 10000ms exceeded during browserType.launchPersistentContext.
[1] app: [browser] <launched> pid=75403
[1] app: [browser] 
[1] app: [browser] DevTools listening on ws://127.0.0.1:45555/devtools/browser/f44a1f4d-ce74-4965-b8e3-bb0546bd46d2
[1] app: [browser] [75403:50179:0716/205303.955435:ERROR:ssl_client_socket_impl.cc(959)] handshake failed; returned -1, SSL error code 1, net_error -202
```

Is there a way to achieve my use case with Playwright?

**Comment by VikramTiwari** [comment]
After some more digging through the code I found this env variable `PLAYWRIGHT_CHROMIUM_DEBUG_PORT`. I can use it to set a port during `chromium.launchPersistentContext` and the browser does launch with websocket port as well as `userDataDirectory`.

``` js
// PLAYWRIGHT_CHROMIUM_DEBUG_PORT=12345 parent.js
const { chromium } = require("playwright");

(async () => {
	const context = await chromium.launchPersistentContext(`./udd`, {
		headless: false,
	});
	const page = await context.newPage();
	await page.goto("https://google.com");
})();

```

At this point, I can use the `webSocketDebuggerUrl` from `localhost:12345/json/version` to connect to the browser. But from this browser, I can't get the existing contexts and can only create new incognito contexts.

```js
// node child.js
const { chromium } = require("playwright");

(async () => {
	const browser = await chromium.connect({
		// replace with webSocketDebuggerUrl from localhost:12345/json/version
		wsEndpoint: `ws://localhost:12345/devtools/browser/489bad93-902d-4f2d-b8ad-0be5868d9313`,
	});
	console.log("browser", browser); // CRBrowser instance
	const contexts = browser.contexts();
	console.log("contexts", contexts); // []
})();
```

This defeats the use case that I am trying to achieve.

I have time to contribute a fix but I don't fully understand why browser server instances don't have access to the pre-existing contexts and why are they limited to just incognito contexts. These seems like design decisions and I am sure they are valid ones.

I am hoping that we can add another way to connect. Something like `chromium.launchPersistentContextServer` which:
- enables usage of user's data directory
- connects using websocket port
- allows new connections through websocket port/URL
- can utilize both normal and incognito contexts
- can see and use existing contexts for the connected browser

Any pointers on where to look for design docs or how to achieve this would be really helpful and much appreciated. Thanks folks!

**Comment by gilles-yvetot** [comment]
@dgozman any news on that? I'd love to have this feature as well and I am ready to help too :)

**Comment by dgozman** [comment]
This is not our current priority, so no progress just yet. We would like to make non-persistent contexts equally good by providing means to save/restore the state you'd like to be persisted.

**Comment by rinogo** [comment]
I'd love this functionality, as well. At the moment, it seems like we need to choose between having a user directory and only being able to automate from a single process OR not have a user directory but be able to automate from multiple processes simultaneously. An upgrade as described in this issue would allow us to use a user directory from multiple processes, right?

**Comment by rinogo** [comment]
Also, in the interest of sharing use cases:

The `wsEndpoint` functionality mentioned by @VikramTiwari would be nice. However, for our use case, it's not strictly necessary (or even desirable, as it complicates things).

We would simply like to be able to start two separate playwright processes that use the same directory. Ideally, Playwright would detect that the requested context is already active in an existing Chromium process and connect to it automatically.

**Comment by rinogo** [comment]
Just in case it helps others, I found a workaround which is more work but probably ends up being more performant. In short, here's how it works:

1. Start a `browserServer` and save the resulting `wsEndpoint` into a file. (I've "automated" this step with a recurring cron jobs that will automatically restart the server if it crashes for some reason)
2. Modify scripts to read the `wsEndpoint` from the file and connect to the already-running server.

Still, I think the "default" behavior of Playwright should be to allow connecting to the same user directory from multiple processes. If that's a limitation of Chromium, then I think sane "default" behavior would be for Playwright to simply connect to the already-running instance instead of trying to start a new one (and failing).

Regardless, I hope this workaround helps someone out there! If your use case is similar to mine, this is likely more performant, anyway, since we just start the browser one time instead of starting it for every script execution (or, even worse, having multiple "full instances" of Chromium running at the same time).

**Comment by pavelfeldman** [comment]
You can now pass --remote-debugging-port as an argument and use connectOverCDP.

**Comment by bjwktcsnzh** [comment]
Whether there is a Firefox solution, thank you very much ! QAQ

**Comment by akvadrako** [comment]
This does not seem like a very good solution. It only works with Chrome and the docs state about connectOverCDP:

> This connection is significantly lower fidelity than the Playwright protocol connection via [browserType.connect()](https://playwright.dev/docs/api/class-browsertype#browser-type-connect)

**Comment by kqvanity** [comment]
@VikramTiwari 
Did you manage to solve [Contexts issue](https://github.com/microsoft/playwright/issues/2992)?
