### ISSUE TITLE
[Bug]: Playwright VS Code plugin is unable to detect my test cases

### ISSUE THREAD

**Issue by akshayp7** [microsoft/playwright#29950]
### Version

1.42.0

### Steps to reproduce

1 Clone the framework (https://github.com/akshayp7/playwright-typescript-playwright-test.git)
2. Run npm install
3. Install Playwright VS Code Plugin
4. Navigate to Playwright plugin tab

### Expected behavior

All the test cases must be listed

### Actual behavior

The tab is empty

### Additional context

1. I tried changing name to test cases from .test.ts to spec.ts, still its not working.
2. Tried proving tests in "testdir" under playwright.config.ts taht didnt work.
Got the above suggestion from discord channel
Looks like something to do with the way we configure env variable.

### Environment

```shell
OS : Win 11
```

**Comment by bc-rajesh** [comment]
I guess your playwright.config.ts needs to be updated to specify the [tests directory](https://playwright.dev/docs/test-configuration). Then the tests will be detected. 

` testDir: 'tests',`

**Comment by mxschmitt** [comment]
This is because your project requires an external environment to be set in order to function. We recommend using e.g. a fallback value or setting it like this in the `.vscode/settings.json` file.

```json
{
    "playwright.env": {
        "npm_config_ENV": "qa"
    }
}
```

**Comment by akshayp7** [comment]
Thank @mxschmitt for your response and suggestion. Actually my requirement was that use should be able to pass the config value in command line itself so had taken this approach

**Comment by mxschmitt** [comment]
Supporting extra command-line arguments is not supported (was never). Closing as per above with the described workaround. Alternative would be e.g. using dotenv.

**Comment by akshayp7** [comment]
Sure thanks a lot for your suggestion settings.json is working out.

**Comment by akshayp7** [comment]
> I guess your playwright.config.ts needs to be updated to specify the [tests directory](https://playwright.dev/docs/test-configuration). Then the tests will be detected.
> 
> ` testDir: 'tests',`
settings.json worked for me
