### ISSUE TITLE
[Feature]: Clear http request headers on page.goto() redirects

### ISSUE THREAD

**Issue by duartmig** [microsoft/playwright#29957]
### 🚀 Feature Request

Implement a mechanism within the page.goto() method to allow users to remove or specify alternative HTTP headers in case of redirects.

Enable users to dynamically set headers for subsequent requests following redirects, ensuring flexibility and control.

### Motivation

During testing scenarios involving redirects in Playwright, maintaining control over HTTP headers becomes challenging. Currently, when mocking API responses with a redirect by setting one request header to then navigate using page.goto(), the same headers from the initial request persist making my test fail on page.goto() with too many redirects. 

This limitation inhibits the ability to stop redirects and set alternative HTTP headers within page.goto()

**Comment by yury-s** [comment]
Playwright does not support interception of redirects, but you can easily overcome this limitation by intercepting original request and mocking the response as described in [this doc](https://playwright.dev/docs/network#modify-responses). You can make `fetch` not follow redirect and instead return the first response by setting [`maxRedirects`](https://playwright.dev/docs/api/class-route#route-fetch-option-max-redirects) to `0`. Thereafter you can send redirected request with modified headers.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.

**Comment by duartmig** [comment]
Thank you for the response. Instead of using page.goto(), I used request.get() with the maxRedirects option set to 0. This allowed me to assert the response status code and redirect URL using expect(response.headers().location).toBe('whatever').
