### ISSUE TITLE
[BUG] failing to set geolocation on Chromium

### ISSUE THREAD

**Issue by ragog** [microsoft/playwright#2996]
**Context:**
- Playwright Version: 1.2.1
- Operating System: Mac
- Node version: 13.13.0
- Browser: Chromium

**Code Snippet**
```javascript
const {chromium} = require('playwright');
(async () => {
    const browser = await chromium.launch();
    
	const url = 'https://developers.google.com/maps/documentation/javascript/examples/map-geolocation';
	const context = await browser.newContext();
		
	await context.grantPermissions(['geolocation']);
        await context.setGeolocation({latitude: 40.593471, longitude: -74.089574});
	
	const page = await context.newPage();
	await page.goto(url);
        await page.screenshot({ path: 'test.png' })
	await browser.close()
})()
```

**Describe the bug**
The above script sets geolocation and navigates to a page with a map. It seems to work perfectly on WebKit, while it doesn't work on Chromium, which reports that "The Geolocation service failed."

![Screenshot 2020-07-17 at 10 07 08](https://user-images.githubusercontent.com/12794903/87763765-92bdc480-c815-11ea-97a9-e57d9380a948.png)

The browser console also reports the following: `Failed to load resource: the server responded with a status of 503 (Service Unavailable)`

**Comment by mxschmitt** [comment]
Hi,

this is not related to Playwright, its related to their site. I also receive this error when I'm using my normal Chrome:

![image](https://user-images.githubusercontent.com/17984549/87780061-32874c80-c82e-11ea-92b9-df36c334dead.png)

You can try to use this to test if your geolocation emulation works: https://mylocation.org/

**Comment by aslushnikov** [comment]
Indeed, the https://developers.google.com/maps/documentation/javascript/examples/map-geolocation doesn't work for me in Chrome.
