### ISSUE TITLE
[Bug]: If test title is parameterized (data coming from array) then that test will be executed in the last

### ISSUE THREAD

**Issue by VeronicaVerno** [microsoft/playwright#29975]
### Version

1.41.2

### Steps to reproduce

- I have declared three describe blocks, in 3rd describe block I have added three tests named AAA, BBB and CCC
- I have parameterized test AAA and taking the data from the string array 
- After execution, you can see test "AAA" block executed in last

<img width="638" alt="Playwright1" src="https://github.com/microsoft/playwright/assets/163816416/e520e1d7-e6af-4b1b-a3d7-2e2766c68e06">

- If I parameterized test AAA and took the data from string variable not from string array then it is working fine as expected

<img width="612" alt="Playwright3" src="https://github.com/microsoft/playwright/assets/163816416/5b32f6cf-33e1-4526-a38b-f81ad887fbc9">

- If I removed parameter data.servicesActivityName[0] from test execution working as expected

<img width="580" alt="Playwright2" src="https://github.com/microsoft/playwright/assets/163816416/81da0c38-615d-42fc-9828-078828ce1ff0">

### Expected behavior

Testcases should be executed as per order I have written the tests

### Actual behavior

If data is coming from string[] then it will run in the last, it will not follow the order of execution

### Environment

```shell
Window 10
```

**Comment by mxschmitt** [comment]
See the error message in the first screenshot:

> "Test not found in the worker process. Make sure test tile does not change."

Make sure that your test titles are always the same and are not changing during the test execution. Closing since this is working as intented.
