### ISSUE TITLE
[Feature]: Allow changing of FFMPEG args

### ISSUE THREAD

**Issue by martinalderson** [microsoft/playwright#29973]
### 🚀 Feature Request

Right now ffmpeg args are hardcoded with no way to override:

_const args = `-loglevel error -f image2pipe -avioflags direct -fpsprobesize 0 -probesize 32 -analyzeduration 0 -c:v mjpeg -i - -y -an -r ${fps} -c:v vp8 -qmin 0 -qmax 50 -crf 8 -deadline realtime -speed 8 -b:v 1M -threads 1 -vf pad=${w}:${h}:0:0:gray,crop=${w}:${h}:0:0`.split(' ');_

We would like the ability to change this string that is passed into playwright somehow for more flexibility.

Please note that playwright isn't just used for classic "e2e testing". People use it for all sorts of things, including making documentation videos automatically and other use cases. 

### Example

Two main use cases:

1) we'd like to increase the number of threads that video creation uses so it is faster. This is by far the slowest part of our tests (ffmpeg transcoding). We want to show users test results as quickly as possible in our UI - this is *not* the same as running more in parallel. We have a web dashboard where people can create tests and then get results back. The video is important for this. But enabling video is very slow because of the transcoding process.

2) Changing quality and codecs, etc. People may want higher (or lower) quality video or to use different codecs, for example av1 or h265 with higher efficiency. If they are creating documentation videos automatically people may want to use much higher quality video at the expense of speed (though this can be combated with more threads or even gpu encoding)

### Motivation

It will make tests with videos far faster if we can use multiple threads. As many people point out in various tickets, this is very slow and scales badly with test length.

It will allow people to create smaller video more efficient video files if they require, or very high quality videos if they desire.

I do not think the defaults should be changed from what they are - just some way to change the args string would be incredibly useful. 

There is a general feeling I got that test speed isn't that important as you can just parallelise them. However, in some cases like ours where we have a web dashboard for less technical users to make tests, getting the tests back quickly is important.

**Comment by yury-s** [comment]
`ffmpeg` is an implementation detail and is only used with Chromium, hence we are not planning to surface it in Playwright APIs. Having said that, Playwright is an open source project and you are free to change the arguments of the call to your liking. Also we recommend using [tracing](https://playwright.dev/docs/trace-viewer-intro) instead of video for better debugging experience as in addition to the picture it records DOM snapshots and more.
