### ISSUE TITLE
[Feature]: Build as Single Executable Application

### ISSUE THREAD

**Issue by duncangroenewald** [microsoft/playwright#29979]
### 🚀 Feature Request

We would like to build  the playwright test as an installable application so that it can be installed and run on an IoT Device running windows as a single application - it doesn't need to be a single file but the tests and the dependencies need to be installed by and msi file.

### Example

Our IoT Devices have other devices connected via ports (usb/serial) and we want to be able to run a test suit on each device to verify the correct functioning of the configured devices.  

We would therefor like to package up the Playwright test suit as can installable application so that it can be easily installed and uninstalled on the devices.

### Motivation

This will allow test suites to be run on devices in the field to validate the configuration.

**Comment by yury-s** [comment]
This is a niche use case which is out of scope for core Playwright. With that said, Playwright is an open source project, so you can build the installer on top of it. If there is anything missing in the current API that prevents you from creating such installer we could consider extending the APIs. Feel free to open issues/send PRs for that if needed.
