### ISSUE TITLE
[BUG] WebKit zooms page out

### ISSUE THREAD

**Issue by creage** [microsoft/playwright#2997]
**Context:**
- Playwright Version: 1.2.1
- Operating System: Windows 10 Enterprise, 2004, 19041.388
- Node version: v14.5.0
- Browser: WebKit
- Extra: 4K monitor with 200% zoom set in display settings

**Code Snippet**

```javascript
const { webkit } = require('playwright');

(async () => {
  const browser = await webkit.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('http://google.com/');
})();
```

**Description**

Try to click around. Sometimes (very often) a huge black borders appear around the page, and there is no way to make it look normal.

![image](https://user-images.githubusercontent.com/910967/87784221-2d2e0000-c836-11ea-960e-943e38a1d003.png)

**Comment by fujii** [comment]
Playwright disables high DPI support only in UI process while specifying DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2 in web process. 
https://trac.webkit.org/browser/webkit/trunk/Source/WebKit/WebProcess/win/WebProcessMainWin.cpp#L45
