### ISSUE TITLE
[Bug]: JUnit report contains invalid character in logs

### ISSUE THREAD

**Issue by cherrygithub1805** [microsoft/playwright#29978]
### Version

1.41.1

### Steps to reproduce

1. Run a suit of UI playwrights tests
2. Generate the junit.xml report

### Expected behavior

The junit.xml report should be generated!

### Actual behavior

The generated file throws an error: " This page contains the following errors:
error on line 7 at column 91: invalid character in attribute value
Below is a rendering of the page up to the first error."

Here you find the part of playwrights logs that were added to the junit.xml report :
![InvalidChar_junitReport](https://github.com/microsoft/playwright/assets/117629643/d6fd07a8-b992-471b-820f-ec4893d35634)

### Additional context

Is there a way to exclude special characters from Playwright logs when utilizing a JUnit reporter?

### Environment

Playwright Version: 1.41.1
Operating System: Windows
Node.js version: 18.17.1

**Comment by yury-s** [comment]
Can you share a full repro so that we could run it locally?

**Comment by cherrygithub1805** [comment]
It's confidential and I'm not able to share a full repro

**Comment by shasank01** [comment]
Can you recreate the issue seperately from what you're working on!

**Comment by yury-s** [comment]
Try to extract relevant code into a separate project. We cannot act on this without a reproduction.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
