### ISSUE TITLE
[Bug]: In the mobile environment, the canvas cannot generate strokes or traces.

### ISSUE THREAD

**Issue by ml4725** [microsoft/playwright#29972]
### Version

1.42

### Steps to reproduce

We have a page with contract signing that includes a canvas for handwritten signatures where you can draw a digital signature. The signature canvas works properly on mobile devices, and you can sign on the canvas when the page is switched to the mobile environment using manual F12. However, we are currently attempting to write an automated test, but we are unable to draw the signature, and the signature stroke is not displayed correctly on the canvas.
Refer to the example.

    from playwright.sync_api import sync_playwright
    with sync_playwright() as playwright:
        iphone = playwright.devices["iPhone 12 Pro"]
        browser = playwright.chromium.launch(headless=False)
        context = browser.new_context(**iphone)
        context.grant_permissions(['camera', 'microphone'])
        page = context.new_page()
        page.goto("https://yc-h5-test15.hrfax.cn/ccip/sign/#/?query=eyJ3YXRlck5vIjoiMTc2NTQxMDQ0NDM5Njk5NDU2MCIsInNpZ25Ub2tlbiI6ImJlYXJlciBleUpoYkdjaU9pSlNVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKd2FHOXVaU0k2Ym5Wc2JDd2lkWE5sY2w5dVlXMWxJam9pTVRnek1EQXdNREF3TURFaUxDSnlaWE5sZEZCaGMzTlhiM0prSWpwbVlXeHpaU3dpYzJOdmNHVWlPbHNpWVd4c0lsMHNJbk5wYm1kc1pVeHZaMmx1SWpwdWRXeHNMQ0psZUhBaU9qRTNNVEF3TWpreE1UTXNJblI1Y0dVaU9uc2lkbUZzZFdVaU9pSnViMjVsWDNWelpYSWlMQ0owWlhoMElqb2k2WjJlNTdPNzU3dWY1NVNvNW9pM0lpd2ljbTlzWlZSNWNHVWlPaUlpTENKaWRYTnBibVZ6YzFSNWNHVWlPaUlpZlN3aWRYTmxja2xrSWpveE9ETXdNREF3TURBd01Td2lhblJwSWpvaWRDMTFUM1pyT0RablVGZEliWG96TFZSWlZsOHlVemxqUWt4Vklpd2lkWE5sY2tOdlpHVWlPbTUxYkd3c0ltTnNhV1Z1ZEY5cFpDSTZJbU5qYVhBdFpuSnZiblJsYm1RaUxDSjFjMlZ5Ym1GdFpTSTZJakU0TXpBd01EQXdNREF4SW4wLldnTlFKeVJ1dWRBeXRyOUtFSnBxeEJfelpiay1nRVlnTFgyXzU1ZFQxWldCSmw5V3d6RjFyYXNVQnFxcjU3ZmRKUmpneHdWQTZRcEhqTjNoXzlJczBUdUQydU5fMlhHMDA1a3VQblQySDI0WXdSWHhtcm1CczktUmd0dnZ2cHdaQWthcXN1MXljWVo3Ri16djNIUVRUcU1majIzLWxXU3BGZEJWR05iSGZFTEx4VkhEVlFoR0ZsZFpEczlqdGhKVEszNElKSURvblFYUWNWbmFqMkxXLXR1OGRFTEt1TmxnRk9JOVlGR2tORWFjOFZ4aHliU0Z2UXBrYkwxTHBKX3VyREVMR2ttcXNjUmhFblN0YlZFWGxncFdYaEJVSDhBenpfejRyUlZvTlppTFF4aDh4NmdLYklPRGlTRkRIeHRrNjRQNXpXU3d2QzloMmROX0l1SmVrdyIsImJhY2tVcmwiOiJodHRwczovL3ljLWg1LXRlc3QxNS5ocmZheC5jbi9jY2lwLyMvcGFnZXMvaW5kZXgvaW5kZXg%2FdXVpZD0wZjI0NjQ4ZS01MTkyLTQ3YTEtODAzZi02NWE5ODEwZjIxMDQiLCJzdWNjZXNzVXJsIjoiaHR0cHM6Ly95Yy1oNS10ZXN0MTUuaHJmYXguY24vY2NpcC8jL3BhZ2VzL3NlbGZBcHBseS9yZXN1bHQvaW5kZXg%2FcmVzdWx0PXRydWUmc291cmNlPXNpZ25hdHVyZSIsImZhaWxlZFVybCI6Imh0dHBzOi8veWMtaDUtdGVzdDE1LmhyZmF4LmNuL2NjaXAvIy9wYWdlcy9teU9yZGVyUGFnZS9pbmRleD9mbGFnPWhpc3RvcnlPcmRlciZmcm9tPXNpZ24ifQ%3D%3D")
        page.locator("//uni-view[@Class='btns-box']").click()
        page.wait_for_timeout(3000)
        page.locator("//uni-button").click()
        canvas = page.locator("#canvas")
        canvas_box = canvas.bounding_box()
        center_x = canvas_box['x'] + canvas_box['width'] / 2
        center_y = canvas_box['y'] + canvas_box['height'] / 2
        page.mouse.move(center_x, center_y)
        page.mouse.down()
        page.mouse.move(center_x, center_y + 150)
        page.mouse.up()
        page.pause()

### Expected behavior

When moving the mouse on the canvas signature board, strokes can be generated and displayed.

### Actual behavior

When moving the mouse to the center position of the canvas board, pressing the left mouse button and moving the mouse downwards,The code is executing correctly, but does not draw anything on the canvas board

### Environment

```shell
Playwright Version: [v1.42.0]
Operating System: [win11]
Browser: [Chromium]
Other info:
```

**Comment by yury-s** [comment]
Looks like there is a bug in the click handler, I see the following exception in the DevTools console and same exception is thrown if I manually try to do the same mouse action on the canvas:

<img width="634" alt="image" src="https://github.com/microsoft/playwright/assets/9798949/d9291578-6f78-4a7f-9f94-40e55c61a540">

If you think this is a Playwright bug we'll need a reduced reproduction.

**Comment by ml4725** [comment]
No, because this canvas requires operation in a mobile environment. You can try manually switching the page to mobile mode in the console or using CTRL+SHIFT+M, and then manually operate the canvas. The strokes should be displayed correctly in this case. Additionally, we have previously used Selenium, and it worked fine for operating the canvas. The error you mentioned would occur if you try to operate it in a non-mobile environment.

**Comment by yury-s** [comment]
Apparently in some cases Chromium triggers font update which interferes with the capturing screenshots. Most likely it is because of [this code](https://source.chromium.org/chromium/chromium/src/+/main:content/browser/devtools/protocol/page_handler.cc;l=971-978;drc=b1fe1c29f4a0d9843fac4a58871ada313ab9dca6?q=pagehandler::capturescreenshot&ss=chromium). The behavior is flaky.

**Comment by yury-s** [comment]
Investigation notes: after unsuccessful screenshot browser requests the fonts again:

```
request finished https://tempo.fit/fonts/Moderat/Moderat-Medium.woff2
request finished https://tempo.fit/fonts/Moderat/Moderat-Regular.woff2
request finished https://tempo.fit/fonts/Moderat/Moderat-Regular.woff2
request finished https://tempo.fit/fonts/Moderat/Moderat-Medium.woff2
request finished https://tempo.fit/fonts/Moderat/Moderat-Regular.woff2
request finished https://tempo.fit/fonts/Moderat/Moderat-Medium.woff2
request finished https://tempo.fit/fonts/Moderat/Moderat-Bold.woff2
will screenshot
{
  format: 'png',
  quality: undefined,
  clip: { x: 0, y: 0, width: 1280, height: 3622, scale: 1 },
  captureBeyondViewport: true
}
request finished https://tempo.fit/fonts/Moderat/Moderat-Regular.woff2
request finished https://tempo.fit/fonts/Moderat/Moderat-Medium.woff2
```
We didn't see such requests in DevTools though.

This was from the following test:

```js
import { test, expect } from '@playwright/test';
import { Page } from "@playwright/test";

export const delay = (ms: number) =>
  new Promise((resolve) => setTimeout(resolve, ms));

test.setTimeout(180000);
test('capture screenshot', async ({ page }) => {
  page.on('requestfinished', (request) => {
    if (request.url().includes('fonts/Moderat'))
      console.log('request finished', request.url());
  });
  await page.goto(`https://tempo.fit`, {
    waitUntil: "networkidle",
  });

  await page.evaluate(() => document.fonts.ready);
  await delay(10000);
  await page.keyboard.down('Escape');
  await page.keyboard.down('Escape');
  await page.keyboard.down('Escape');
  await delay(1000);

  await page.evaluate(() => document.fonts.ready);

  console.log('will screenshot');
  await expect(page).toHaveScreenshot({
    fullPage: true,
    animations: 'allow',
    caret: 'initial',
    scale: 'device',
  });
  console.log('did screenshot');
});
```

**Comment by yury-s** [comment]
What you are looking for here is support for touch events and swipe gestures. We currently support only [tap](https://playwright.dev/docs/api/class-touchscreen#touchscreen-tap) which is not enough to draw a signature. Folding this request into https://github.com/microsoft/playwright/issues/2903, please upvote it instead.
