### ISSUE TITLE
[Bug]: parallelization (--workers=N) does not work when running specific project (--project=xxx)

### ISSUE THREAD

**Issue by younesjallouli** [microsoft/playwright#29974]
### Version

1.41.2

### Steps to reproduce

Run npx playwright with the arguments --workers=N and --project=xxx

### Expected behavior

The command should start as many workers as specified (N)

### Actual behavior

Only 1 worker starts. 
If I remove the --project argument, then N workers start

### Environment

```shell
System: mac os
playwright: 1.41.2
```

**Comment by mxschmitt** [comment]
Do you have `fullyParallel: true` inside your config? By default Playwright parallelises via files, so if you only have one file, there can be only a maximum of one worker. See here: https://playwright.dev/docs/test-parallel

Can you provide us a minimal reproducible?

**Comment by younesjallouli** [comment]
Sure thing! 

https://github.com/younesjallouli/playwright-bug

`yarn`

`npx playwright install chromium`

`npx playwright test --workers=2 --project=integration-tests`

Result: 

```
Running 2 tests using 1 worker
  2 passed (3.1s)

To open last HTML report run:

  npx playwright show-report
```

**Comment by mxschmitt** [comment]
Yeah this is the assumption which I had. You are running 1 project with 1 file with `fullyParallel: false` (default). This will only parallelise on a file level. If you set it to `true`, it will spawn 2 workers. Put this inside your config, and then it works:

     fullyParallel: true,

See here: https://playwright.dev/docs/test-parallel#parallelize-tests-in-a-single-file

**Comment by younesjallouli** [comment]
Thx @mxschmitt
