### ISSUE TITLE
[Bug]: `--use-gl=egl` launchOption enables hardware acceleration till v1.28.0, from 1.29.0-1.42.0 it does not enable

### ISSUE THREAD

**Issue by ThisIsAnshulVerma** [microsoft/playwright#29980]
### Version

1.42.0

### Steps to reproduce

In the `playwright.config.js` file, mention `--use-gl=egl` as launch options. 

### Expected behavior

It should enable hardware acceleration

### Actual behavior

It does NOT enable hardware acceleration

### Additional context

This flag works till v1.28 in my case. 
From v1.29-v.1.42, it does not enable hardware acceleration.

**P.S. I did not change the code, installed different versions of @playwright/test and ran tests**

### Environment

```shell
System:
  0S: MacOS Sonoma 14.3.1
  CPU: Apple M2 (8)
Binaries:
  Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node 
  npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
  npmPackages:
    @playwright/test: 1.42.0
```

**Comment by yury-s** [comment]
This is a Chromium flag, Playwright has no control over that. Please file an issue at https://crbug.com/ or see if it's already covered by an existing one (https://issues.chromium.org/issues?q=--use-gl%3Degl).

**Comment by yury-s** [comment]
[This comment](https://issues.chromium.org/issues/40230909#comment4) seems relevant.
