### ISSUE TITLE
[Bug]: Test execution order is not same in HTML report as visible in terminal if we define nested describe block

### ISSUE THREAD

**Issue by VeronicaVerno** [microsoft/playwright#29984]
### Version

1.41.2

### Steps to reproduce

I have declared three describe blocks and execution is working fine and visible in order in terminal but not in HTML report

![image](https://github.com/microsoft/playwright/assets/163816416/2c483803-44d4-40f7-b451-5741402a1cc3)

![image](https://github.com/microsoft/playwright/assets/163816416/f1ac000f-1124-4511-bd81-5380d0944267)

### Expected behavior

The report should be show the same test execution order

### Actual behavior

If I have multiple nested describe block, insider describe block tests result are visible first then outer describe block tests (refer to above screenshot)

### Environment

```shell
window 10
```

**Comment by yury-s** [comment]
HTML report currently shows `describe` suites [before](https://github.com/microsoft/playwright/blob/70e6cdac5753b0d5e89864fcdc65d130d39c06f9/packages/playwright/src/reporters/html.ts#L346-L347) any tests at same level.

**Comment by yury-s** [comment]
Note: we could expose Suite/Test.kind and Suite.entries.
