### ISSUE TITLE
[Feature]: Show browser functionality with container development environment

### ISSUE THREAD

**Issue by jjarvela** [microsoft/playwright#29985]
### 🚀 Feature Request

Currently there is no easy way to setup browser or record at cursor features in container development environment.

### Example

Easy installation procedure to avoid "Looks like you launched a headed browser without having a XServer running." error message.

### Motivation

Usability.

**Comment by yury-s** [comment]
This already works in GitHub Codespaces out of the box with automatic [port forwarding](https://docs.github.com/en/codespaces/developing-in-a-codespace/forwarding-ports-in-your-codespace#about-forwarded-ports). If you install Playwright Extension and navigate to noVNC page, you can record at the cursor. If you are using different environment, you may need to do extra steps to setup X server/client to see the browser.

**Comment by alisterscott** [comment]
@yury-s 

> If you install Playwright Extension and navigate to noVNC page, you can record at the cursor. 

Can you expand on this a little bit please? Is noVNC built into the extension? What port do we forward to access it? Thanks
