### ISSUE TITLE
[Feature]: Flag to run only tests/test files that have `toHaveScreenshot` within them

### ISSUE THREAD

**Issue by kkortes** [microsoft/playwright#29986]
### 🚀 Feature Request

It would be nice to be able to pass a flag, like `--update-snapshots`. Mabye something like: `--filter-has-snapshots`.

### Example

`yarn playwright test --update-snapshots --filter-has-snapshots`

or only:

`yarn playwright test --filter-has-snapshots`

### Motivation

I often find myself having to run _all tests_ when I want to generate new snapshots, even though only a few tests / test files have them. With the projects and their extensive e2e-testing that I got on my hands a lot of time is eaten up by the facts that all tests have to finish before new snapshots are generated.

Very often I target specific files for this purpose, i.e:
`yarn playwright test somefilename.spec.ts --update-snapshots`

But sometimes this ends up being a fiddly game of "guessing what snapshots needs to be updated".

Say you make a change to a websites logo (that is visible on all snapshots) and you are sure that you want all snapshots to update. In situations like this it would be wonderful to have this functionality.

**Comment by yury-s** [comment]
You can consider [adding a tag ](https://playwright.dev/docs/test-annotations#tag-tests) to the tests that use screenshots and then filter based on that. Would that work?

**Comment by yury-s** [comment]
Discussed this in a team meeting today, we recommend marking your VRT tests with a tag and then use it as filter.

**Comment by kkortes** [comment]
This is a fine solution, thanks.
