### ISSUE TITLE
Desktop Application- Playwright support

### ISSUE THREAD

**Issue by aktayyala** [microsoft/playwright#29998]
### Please do not submit this issue.

- [X] I understand

**Comment by aktayyala** [comment]
Hi, I'm analyzing this tool capabilities and wanted to know if Playwright support Desktop applications integrated with Dynamics D365 F&O applications. 
I seen that it support electron but we have the desktop application with dynamics integrated.
Appreciate if someone can help me out here.

Thanks

**Comment by yury-s** [comment]
As long as the application allows to connect over CDP you may be able to automate it with playwright. There is no direct support though. See our documentation for [WebView2 automation](https://playwright.dev/docs/webview2) to get more insight into how it might work.

For questions please use our [discord channel](https://playwright.dev/community/welcome#community-discord) and other community resources.
