### ISSUE TITLE
[Bug]: not getting all DEBUG=pw:api calls into the Logger

### ISSUE THREAD

**Issue by TesterrA** [microsoft/playwright#29997]
### Version

1.42.1

### Steps to reproduce

Logger: {
      isEnabled: (name) => name === 'api',
      log: (name, severity, message) => console.log(message),
    },

### Expected behavior

 pw:api   performing click action +2ms
  pw:api   click action done +4ms
  pw:api   waiting for scheduled navigations to finish +0ms
  pw:api   navigations have finished +0ms
  pw:api <= locator.click succeeded +1ms
  pw:api => page.waitForURL started +1ms

### Actual behavior

28305 api info => browserContext.newPage started
28305 api info <= browserContext.newPage succeeded
28305 api info => page.goto started
28305 api info <= page.goto succeeded
28305 api info => page.close started
28305 api info <= page.close succeeded

### Additional context

The verbosity of logs generated does not change regardless of what I set as the name (protocol, api, browser).

### Environment

```shell
System:
    OS: ubuntu
    Memory: 16.00 GB
  Binaries:
    Node: 20
    npm: 10
```

**Comment by mxschmitt** [comment]
Probably similar to https://github.com/microsoft/playwright/issues/6465

**Comment by yury-s** [comment]
This is the log I'm getting for the snippet below. It is less detailed than pw:api but contains all the API calls. 

```
=> browser.newContext started
<= browser.newContext succeeded
=> browserContext.newPage started
<= browserContext.newPage succeeded
=> page.goto started
<= page.goto succeeded
=> locator.click started
<= locator.click succeeded
=> locator.click started
<= locator.click succeeded
=> browser.close started
<= browser.close succeeded
```

Snippet:
```js
import { chromium, devices, expect, test } from '@playwright/test';

const browser = await chromium.launch({
  logger: {
    isEnabled: name => name === 'api',
    log: (name, severity, message) => console.log(message)
  }
});

const context = await browser.newContext();
const page = await context.newPage();
await page.goto('https://playwright.dev/');
await page.getByRole('link', { name: 'Docs' }).click();
await page.getByRole('link', { name: 'How to install Playwright' }).click();
await browser.close();
```

There are no plans to add more details into the logger calls. We recommend you use tracing for offline debugging, it will contain DOM snapshots and other useful information in addition to the pure logs.

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/6465

**Comment by TesterrA** [comment]
If the logs and trace are on the same machine, you are correct. However, what would happen if I ran my team's debug logs all from a central logging server?
