### ISSUE TITLE
[Bug]: Okta integration is returning error when playwright executed in docker

### ISSUE THREAD

**Issue by denys-iaremenko** [microsoft/playwright#30002]
### Version

1.42.1

### Steps to reproduce

1. Login via OKTA to required resource  

### Expected behavior

User is logged in. 

https://<domain>.okta.com/login/token/redirect?stateToken=<token> returns 200 status code 

### Actual behavior

User get an error. 
https://<domain>.okta.com/login/token/redirect?stateToken=<token> returns 302 status code 

<img width="919" alt="Screenshot 2024-03-19 at 20 26 38" src="https://github.com/microsoft/playwright/assets/84392142/b4960295-9c0f-4899-9752-9c6002fa723f">
URL

### Additional context

1.42.1 woks fine on local MAC OS run
1.41.2 in docker works as expected

Looks like issue occurs only in combination of playwright 1.42.1 and docker image 

### Environment

```shell
System:
- Docker based on mcr.microsoft.com/playwright:v1.42.1-jammy
```

**Comment by denys-iaremenko** [comment]
Downgrade to @playwright/test to 1.41.2 from 1.42.1 solves the issue for runs in docker.

**Comment by denys-iaremenko** [comment]
Issue also relevant for `@playwright/test 1.42.0 `

**Comment by mxschmitt** [comment]
Looks like https://github.com/microsoft/playwright/issues/29925

Can you share a repro with us which we can run locally?

**Comment by denys-iaremenko** [comment]
@mxschmitt yes, my issue exactly like #29925. Our service is internal and can be accessed only via vpn, so unfortunately it is not an option to repro it outside of VPN. I think we can close this issue and link it to #29925
