### ISSUE TITLE
Playwright Test Explorer ignores playwright.config file after Playwright update

### ISSUE THREAD

**Issue by vmomryk** [microsoft/playwright#30006]
### Please do not submit this issue.

- [X] I understand

**Comment by vmomryk** [comment]
After Playwright was updated to v.1.42 all tests which are running with Playwright Test Explorer are failing because playwright.config file is ignored. The same is if to run tests with a green arrow icon near the tests.
If to run all those tests from console - all pass. Has anyone experienced this?

**Comment by yury-s** [comment]
Please follow the `Bug` template and provide a reproducible example so that we can take an action on your report.
