### ISSUE TITLE
[Bug][Question]: "message": "First argument must use the object destructuring pattern: _a"

### ISSUE THREAD

**Issue by bshostak** [microsoft/playwright#30007]
### Version

1.42.1

### Steps to reproduce
Unfortunately I don't have a repo you can clone right now because this is internal code and all that. So i'm hoping by providing enough context I can get on the right path. Otherwise, I can try to extract everything and throw it in a repo.

I have a function that creates fixtures for our POM classes like this:

```ts
export function buildFixtures(fixtureClasses: Record<string, FixtureClassType>) {
  return Object.entries(fixtureClasses).reduce(
    (acc, [name, FixtureClass]) => ({
      // Spread the accumulator to include all properties added in previous iterations
      ...acc,
      // Add a new property with the key being the fixture name and the value being
      // an async function that creates an instance of the class and registers it for cleanup
      [name]: async ({ page }, use) => {
        const fixtureInstance = new FixtureClass(page);
        await use(fixtureInstance);
      },
    }),
    // Start with an empty object as the initial value of the accumulator
    {}
  );
}
```

and what I pass into it is something like:

```ts
//FIXTURES.ts
// MyFixtures maps keys of fixtureClasses to instance types of corresponding classes.
type MyFixtures = {
  [K in keyof typeof fixtureClasses]: InstanceType<(typeof fixtureClasses)[K]>;
};

const fixtureClasses = {
  ssoLoginPage: LoginPage,
  ssoSuccessPage: SuccessPage,
  ssoNewPasswordPage: NewPasswordPage,
  ssoForgotPasswordPage: ForgotPasswordPage
};

const fixtures = buildFixtures(fixtureClasses);
export const test = base.extend<MyFixtures>(fixtures);
```
then in my test file I can do something like this:

```ts
import { test } from '@external/package';

test.describe('Forgot page tests', () => {
  // not using authenticated state
  test.use({ storageState: undefined });

//pass in the actual POM class here vs page
  test.beforeEach(async ({ ssoLoginPage }) => {
    await ssoLoginPage.get(environment);
    await ssoLoginPage.forgotCreds.click();
  });

  test('verify page loads', async ({
    page,
    ssoForgotPage,
  }) => {
    await expect(ssoForgotPage.loadedItem).toBeVisible()
  });
```

This used to work fine but am now getting an error (this links to the FIXTURES.ts file i posted above):
```json
{
  "message": "First argument must use the object destructuring pattern: _a",
  "location": {
    "file": "pathToFixturesFile/Fixtures.ts",
    "line": 14,
    "column": 26
  }
}
```

Is this built incorrectly in order for playwright to build/use it?

### Expected behavior

The fixtures work as expected when passed into test blocks.

### Actual behavior

the bug happens:
```json
{
  "message": "First argument must use the object destructuring pattern: _a",
  "location": {
    "file": "pathToFixturesFile/Fixtures.ts",
    "line": 14,
    "column": 26
  }
}
```

### Additional context

We create our POM classes and the fixture utility above in an internal npm package that we build and publish and bring into our automation codebases. I don't believe this has anything to do with it since we build it with the same playwright version, etc. But can provide more context on this if needed outside of the ticket.

### Environment

```shell
System:
    OS: macOS 14.4
    CPU: (10) x64 Apple M1 Max
    Memory: 327.49 MB / 64.00 GB
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 6.11.0 - ~/.nvm/versions/node/v16.14.2/bin/pnpm
  IDEs:
    VSCode: 1.87.2 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.42.1 => 1.42.1
```

**Comment by yury-s** [comment]
> Unfortunately I don't have a repo you can clone right now because this is internal code and all that. So i'm hoping by providing enough context I can get on the right path. Otherwise, I can try to extract everything and throw it in a repo.

The code looks fine, can you share complete reproduction?

> We create our POM classes and the fixture utility above in an internal npm package that we build and publish and bring into our automation codebases. 

It may have something to do with how the npm package is built. I assume the package contains compiled javascript not typescript source code of the fixtures? It's hard to tell where the error comes from without full example.

**Comment by bshostak** [comment]
@yury-s thank you for taking a look. I was able to create two repos to mimic what we do. I've added you as a collaborator to both of them: abmissue and abmissuetest.

abmissue has the same setup as our internal package with regards to building the package. 

abmissuetest I have setup to mimic how the package would look when brought into the repo. You can open node_modules and find the package "@package" with a folder called automation and in that folder is the built contents from abmissue (i manually copied them in there since i can't actually publish it but it is the same thing). I am able to duplicate the error this way.

Let me know if you have any issue cloning/reproducing. Just run npx playwright test in the abmissuetest file to get the error:
![image](https://github.com/microsoft/playwright/assets/60523456/342798db-0c09-4f2e-9dfb-44f6c5aecc58)

**Comment by yury-s** [comment]
The `buildFixtures` is compiled with some old EcmaScript target version (ES5 ?) and it results in a code that changed the signature of `[name]: async ({ page }, use) => {` to 

```js
        [name]: (_a, use_1) => __awaiter(this, [_a, use_1], void 0, function* ({ page }, use) {
            const fixtureInstance = new FixtureClass(page);
            yield use(fixtureInstance);
        }) })), 
```

Which lost `{ page }` destructuring construct. Try compiling `@package/automation` with ESNext as target.

**Comment by bshostak** [comment]
I'm so confused how this happened because one day it was working and the next not. Either way, I will update our tsconfig accordingly because it does now work when compiling at esnext. 
@yury-s thank you for your help with this one.
