### ISSUE TITLE
[Internal] for the jest portion of the tests, we should handle sigint.

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#3001]

**Comment by rwoll** [comment]
+1: I rebased some work off of main which pulled in the new runners. I ran `npm run test` without realizing it would run all the tests—including the headful tests. I tried to stop it with a sigint, but ultimately had to force quit the terminal.

**Comment by JoelEinbinder** [comment]
This is mostly fixed, although there a few tests which launch their own browsers that will still leak zombies if interrupted.

**Comment by aslushnikov** [comment]
Jest is gone from our tests!
