### ISSUE TITLE
[Docs]: Please add executing methods using yarn instead of npx

### ISSUE THREAD

**Issue by 2gn** [microsoft/playwright#30012]
### Page(s)

[Running the example test](https://playwright.dev/docs/intro#running-the-example-test)

[Running the example test in UI mode](https://playwright.dev/docs/intro#running-the-example-test-in-ui-mode)

### Description

These pages introduces commands that use `npx`, but for yarn users, it is not appropriate and executing those commands in vain may put them into unknown errors.

For example, `npx playwright test` should be `yarn run playwright test` .

**Comment by moghadam53** [comment]
I

**Comment by yury-s** [comment]
Feel free to send a PR to add other package manager examples similar to https://playwright.dev/docs/intro#installing-playwright

**Comment by atmnk** [comment]
@yury-s I haven't scanned documentation to check this discrepancy on every other page. Only fixed the mentioned pages on this issue with above PR.
