### ISSUE TITLE
[Feature]: Add tag in the TestInfo

### ISSUE THREAD

**Issue by aldys33** [microsoft/playwright#30034]
### 🚀 Feature Request

As we know, Playwright are now supports to place tag in a dedicated place, which is `details` section. 

![image](https://github.com/microsoft/playwright/assets/139728284/009e8467-c4bf-4e6e-bcd0-cb2ec435bf3f)

The problem is, since tag is no longer part of test case title, it's hard to identify what tag does the test case have from the hook like `beforeEach`, `beforeAll`, etc

### Example

![image](https://github.com/microsoft/playwright/assets/139728284/3476a4b5-b574-445b-8cb9-e3ebf99d22bc)

### Motivation

This one is required to support new tagging system of the Playwright

**Comment by mxschmitt** [comment]
Looks like already implemented in https://github.com/microsoft/playwright/pull/29794.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
