### ISSUE TITLE
[Bug]: route_from_har replay failed, chrome warning "net::ERR_FAILED", unable to replay

### ISSUE THREAD

**Issue by lk236225128** [microsoft/playwright#30036]
### Version

Playwright Version: [v1.39.0]
Operating System: [macOS 13.4]
Browser: [Chromium]
Other info:

### Steps to reproduce

Example steps (replace with your own):
my code:
```
# route_from_har_demo.py
from playwright.sync_api import sync_playwright
import re

with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)

    browser_context = browser.new_context(**p.devices["iPhone 11 Pro"])

    page = browser_context.new_page()

    page.route_from_har("./har/route_from_har_data.har", url=re.compile(r".*8891.com.tw/api/.*"), update=False)

    page.goto("https://m.8891.com.tw/")
    page.wait_for_timeout(2000)

    browser_context.close()
```
1. Recording a HAR file,Method route_from_har() , set update=Ture
2. python route_from_har_demo.py , Recording a HAR file.(Har data has been recorded successfully)
3. Replaying from HAR , Method route_from_har() , set update=False
4. python route_from_har_demo.py , Replaying from HAR
5. chrome replay error
![截屏2024-03-06 16 20 04](https://github.com/microsoft/playwright-python/assets/43338050/376ea57f-70f3-4f8b-adbc-44f78c6afe12)

### Expected behavior

From my har file, get the response

### Actual behavior

1. Chrome console show : GET https://www.8891.com.tw/api/v4/common/statistics?type%5B%5D=deal&api=6.4&device_id=63689348-680d-19eb-cc83-7151a1c11823-a net::ERR_FAILED
2. All my recorded API dosn't get response from har file
request detail:
![image](https://github.com/microsoft/playwright-python/assets/43338050/9f073cbc-3921-4166-b158-ffdbb9e564c1)

### Additional context

I want to mock some data through the recorded har file, thereby improving the scene coverage of my web automation.

### Environment

```Text
- Operating System: [macOS 13.4 (22F66)]
- CPU: [M2]
- Browser: [Chromium]
- Python Version: [3.9.18]
- Other info:
```

**Comment by yury-s** [comment]
You can implement all the described logic in a custom [request interceptor](https://playwright.dev/docs/network#handle-requests) today, it would essentially be a HAR replay tailored to your use case. Routing from har requests whose parameters have changed since the har was recorded is not supported today. There is an open request for that.

Folding this into https://github.com/microsoft/playwright/issues/29190
