### ISSUE TITLE
[Bug]: the testInfo.attach with body doesn't work with junit report

### ISSUE THREAD

**Issue by jgreffe** [microsoft/playwright#30044]
### Version

1.42.1

### Steps to reproduce

Execute the `body` playwright example https://playwright.dev/docs/api/class-testinfo#test-info-attach using `--reporter=junit`.

```
import { test, expect } from '@playwright/test';

test('basic test', async ({ page }, testInfo) => {
  await page.goto('https://playwright.dev');
  const screenshot = await page.screenshot();
  await testInfo.attach('screenshot', { body: screenshot, contentType: 'image/png' });
});
```

### Expected behavior

The `screenshot.png` should be attached in the report.

### Actual behavior

No screenshot is attached.

### Environment

```shell
System:
    OS: macOS 14.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 104.11 MB / 32.00 GB
  Binaries:
    Node: 19.3.0 - ~/.nvm/versions/node/v19.3.0/bin/node
    Yarn: 3.2.4 - ~/.nvm/versions/node/v19.3.0/bin/yarn
    npm: 9.2.0 - ~/.nvm/versions/node/v19.3.0/bin/npm
    pnpm: 7.30.0 - ~/.nvm/versions/node/v19.3.0/bin/pnpm
  Languages:
    Bash: 5.2.0 - /opt/homebrew/bin/bash
```

**Comment by yury-s** [comment]
Only attachments with file path are currently supported by junit report (see https://github.com/microsoft/playwright/pull/22624), you can change the code to:

```js
  const path = 'screenshot.png';
  await page.screenshot({path});
  await testInfo.attach('screenshot', { path });
```

Would that work for you?

**Comment by jgreffe** [comment]
This doesn't work because `path` (for whatever reason) always adds a sha: https://github.com/microsoft/playwright/blob/35db70ea1da73237446280a29cb610b55403e544/packages/playwright/src/util.ts#L262

See

**Comment by yury-s** [comment]
There is no attachment name in the JUnit format.
