### ISSUE TITLE
[Bug]: Cannot Press Shift+Tab

### ISSUE THREAD

**Issue by russellpollock** [microsoft/playwright#30041]
### Version

1.42.1

### Steps to reproduce

Find the element you want to interact with, focus on it and press Shift & Tab
I've tried this using the id (which worked in the previous Java tests) and I've used the recorder to see what Playwright chose to use, which is the below example.
```
await page.getByRole('link', { name: 'Name' }).focus()
await page.getByRole('link', { name: 'Name' }).press('Shift+Tab')
```

Observe error
```
Error: locator.press: Test timeout of 5000ms exceeded.
Call log:
  - waiting for getByRole('link', { name: 'Name' })
  -   locator resolved to <a href="/example" data-v-ea6fb346="" data-v-b48de27…>…</a>
  - elementHandle.press("Shift+Tab")
```

### Expected behavior

await expect(theSkipLinkPill).toBeFocused()

### Actual behavior

Test times out

### Additional context

I'm testing the 'skip link' functionality. Shift+Tab on the second element of the page, to show the Skip Link pill, and assert it's visible etc.

I've tried doing (Shift) and the test fails because the wrong element is focused. So it seems specific to the combination Shift+Tab

### Environment

```shell
System:
    OS: macOS 14.4
    CPU: (12) x64 Apple M2 Pro
    Memory: 12.29 MB / 16.00 GB
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
  Languages:
    Bash: 5.2.15 - /usr/local/bin/bash
  npmPackages:
    @playwright/test: ^1.42.1 => 1.41.2
```

**Comment by yury-s** [comment]
Can you share full reproduction? I tried with the following test and it works fine:

```js
test('test', async ({ page }) => {
  await page.goto('https://github.com/microsoft/playwright/issues/30041');
  await page.getByRole('button', { name: 'edited' }).focus();
  await expect(page.getByRole('button', { name: 'edited' })).toBeFocused();
  await page.getByRole('button', { name: 'edited' }).press('Shift+Tab');
  await expect(page.locator('#issue-2200817661-permalink')).toBeFocused();
});

```

**Comment by russellpollock** [comment]
Yeah sure. Test is:
```
  test('Tab and Press Enter on Skip Link works as expected', async ({ headerTop, page }) => {
    await headerTop.tabOnSkipLink() <-- it does not get past here
    await expect(headerTop.skipLink).toBeFocused()

    await headerTop.pressEnterOnSkipLink()

    await expect(headerTop.skipLink).not.toBeFocused()
    expect(page.locator('*:focus')).not.toBeNull()
  })
```

Then in the headerTop (it used to be just the locator.press but I've added extras in to try and get it working)
```
  async tabOnSkipLink () {
    const locator = this.page.locator('#the locator')
    await locator.waitFor()
    await locator.focus()
    await this.page.getByRole('link', { name: 'Name' }).press('Shift+Tab')
  }
```

It times out with the red arrow pointing at the `}).press`
Like I say, if I use different key presses, it continues through the test - for example:
```
   async pressEnterOnSkipLink () {
    await this.page.locator('#the skip link locator').focus()
    await this.page.locator('#the skip link locator').press('Enter')
  }
```

**Comment by yury-s** [comment]
We cannot debug partial snippets that point to some POMs. As you can see the basic example above works just fine, so it may well be that the code of the app does something weird. If you think this is a bug in Playwright please provide a reproduction that we could run locally to see the problem.

**Comment by russellpollock** [comment]
Ok that makes sense. I can reproduce on production but I'll leave it as is for now since it works in your example and like you said it's probably something to do with the app anyway. It works manually so at least we know it does work.
