### ISSUE TITLE
[Docs]: Outdate of page https://playwright.dev/docs/api/class-test

### ISSUE THREAD

**Issue by minhphong306** [microsoft/playwright#30059]
### Page(s)

https://playwright.dev/docs/api/class-test

### Description

I think this one does not work for the new version. Should be removed from the documentation.
```
test(title, details, body)
```

Currently, I'm using
```
"@playwright/test": "^1.41.2"
```

Should change to 

```
import { defineConfig } from '@playwright/test';

export default defineConfig({
     use: {
       // config here...
     },
   });
```

**Comment by yury-s** [comment]
The new signature was actually introduced in 1.42, you should [update](https://playwright.dev/docs/browsers#update-playwright-regularly) your playwright.

**Comment by minhphong306** [comment]
@yury-s Do you think we should add note that the form introduced from version `^1.42`?
```
test(title, details, body)
```

For me, when I read the documentation, I see the text `Added in: v1.10` and I understand that it must be work in `v1.41`

![image](https://github.com/microsoft/playwright/assets/19796136/d3284382-8299-4200-bc7c-7ca17d83604d)
