### ISSUE TITLE
[Bug]: Popup Content Not Displayed in Chrome/Chromium with Java Playwright Despite Configuration

### ISSUE THREAD

**Issue by Sanclk** [microsoft/playwright#30055]
### Version

1.37.0

### Steps to reproduce

We are experiencing an issue where popup content fails to display in Chrome/Chromium browsers when using a pure Java Pw framework or our internally developed Playwright (Pw) Java wrapper framework. The popup content successfully displays without errors in Chrome when tested with the pure Python Playwright framework and in Firefox with the Java Playwright framework using following configurations.

BrowserContext context = browser.newContext(new Browser.NewContextOptions()
                .setIgnoreHTTPSErrors(true).
                setBypassCSP(true).
                setExtraHTTPHeaders(Collections.singletonMap("Content-Security-Policy", "frame-ancestors 'self' URL")));

### Expected behavior

The popup content should be displayed without any errors, similar to how it behaves in Firefox with the specified Java configuration and in Chrome when using the pure Python Playwright framework without any configurations.

### Actual behavior

The popup content is not displayed in Chrome/Chromium browsers with the specified configuration. However, it displays correctly in Firefox with the same Java configuration and in Chrome with the pure Python Playwright framework without any configurations.
![MicrosoftTeams-image](https://github.com/microsoft/playwright/assets/106805907/9fe6e9b8-e84a-489a-ae00-23c7f0578a08)

### Additional context

- Following [this issue](https://github.com/microsoft/playwright/issues/27989), the above steps were tried out.
- This issue specifically arises with Chrome/Chromium browsers; no similar issue is observed with Firefox.
- The problem persists even after configuring to the browser versions worked for pure Python Pw framework [116.0.5845.82], Playwright configurations, and ensuring that the environment is consistent across different tests.

### Environment

```shell
Browser: Chrome/Chromium 116.0.5845.82
Operating System: Windows 10
Java Version: 11
```

**Comment by yury-s** [comment]
>  in Chrome with the pure Python Playwright framework without any configurations.

Doe it work with the default configuration in java? The underlying browser instrumentation is the same in java and python, so if it works in one language it should work in the other too with the same parameters.

Please share a reproduction so that we can try it locally.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
