### ISSUE TITLE
[Bug]: VS Code : Test -> TEST EXPLORER Not displaying test projects defined with config.ts files other than 'playwright.config.ts'

### ISSUE THREAD

**Issue by Jibin-E-Paul** [microsoft/playwright#30052]
### Version

1.42

### Steps to reproduce

Step 1: Create multiple config.ts files such as e2e.config.ts, api.config.ts etc.
Step 2: Add test projects within the different config files.
Step 3:Navigate to VS code's TEST EXPLORER

### Expected behavior

I expected to see my different tests displayed in the TEST EXPLORER

### Actual behavior

Getting a message "No test have been found."

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 7.29 GB / 15.75 GB
  Binaries:
    Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.87.2 - C:\Users\name\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.42.1 => 1.42.1
    playwright: ^1.42.1 => 1.42.1
```

**Comment by mxschmitt** [comment]
This is expected, we only look at `**/*playwright*.config.{ts,js,mjs}`. So you could name it e.g. api.playwright.config.ts

**Comment by Jibin-E-Paul** [comment]
Thanks, works fine when I re-named it as suggested. Closing the issue.
