### ISSUE TITLE
[Bug]: chromium Error: browserType.launch: spawn EPERM

### ISSUE THREAD

**Issue by aniketicloud** [microsoft/playwright#30058]
### Version

1.42.1

### Steps to reproduce

Node 20.9.0
1. run this in terminal->npm create vite@latest --template react-swc-ts
2. run this in terminal-> npm init playwright@latest
3. select all default options like install browsers location etc
4. npx playwright test

### Expected behavior

I expect to run test on chromium with default instructions

### Actual behavior

1) [chromium] › example.spec.ts:3:1 › has title ──────────────────────────────────────────────────

    Error: browserType.launch: spawn EPERM
Call log:
      - <launching> C:\Users\aniket.pandharabale\AppData\Local\ms-playwright\chromium-1105\chrome-win\chrome.exe 
--disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache 
--disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages 
--disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=C:\Users\ANIKET~1.PAN\AppData\Local\Temp\playwright_chromiumdev_profile-Z2TfjL --remote-debugging-pipe --no-startup-window
<img width="960" alt="Screenshot 2024-03-22 222112" src="https://github.com/microsoft/playwright/assets/54700318/5d2cad75-0d5c-4cc2-8e80-a7e44829b5bc">

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 4.65 GB / 15.75 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.87.2 - C:\Users\aniket.pandharabale\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.2.15 - C:\Users\aniket.pandharabale\AppData\Local\Programs\Git\usr\bin\bash.EXE
  npmPackages:
    @playwright/test: ^1.42.1 => 1.42.1
```

**Comment by aniketicloud** [comment]
The same error happens to me when I run `npm init playwright@latest` in an empty folder. Playwright asks me to select TS or JS. I select TS. But chromium is failing, other browsers can run tests.

**Comment by aniketicloud** [comment]
Also, this is a company laptop. One can suggest me like if there are any policies that I should check to run this.
We are choosing Playwright for E2E and component testing.

**Comment by yury-s** [comment]
> The same error happens to me when I run `npm init playwright@latest` in an empty folder.

It definitely has something to do with the corp policies/antimalware running on your computer. Are you able to launch Chromium from the logged location manually?

**Comment by aniketicloud** [comment]
> > The same error happens to me when I run `npm init playwright@latest` in an empty folder.
> 
> It definitely has something to do with the corp policies/antimalware running on your computer. Are you able to launch Chromium from the logged location manually?

Do you mean open the location and open the chromium browser?

**Comment by yury-s** [comment]
I mean launching `C:\Users\aniket.pandharabale\AppData\Local\ms-playwright\chromium-1105\chrome-win\chrome.exe` (with `--user-data-dir=` pointing to an empty dir, so that it starts with a fresh profile).

**Comment by Sanjeewahsp** [comment]
Hi, I am having same issue with latest node/playwright.

$ npx playwright test 
Running 1 test using 1 worker
  1) [Mobile Chrome] › login.spec.ts:10:5 › Success login test ─────────────────────────────────
    Error: browserType.launch: spawn EPERM
    Call log:
      - <launching> C:\Users\xxxxxxxxxx\AppData\Local\ms-playwright\chromium-1105\chrome-win\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update 
--no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen 
--headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=C:\Users\XXXX~1.SAM\AppData\Local\Temp\playwright_chromiumdev_profile-OkGFpy --remote-debugging-pipe --no-startup-window


  1 failed
    [Mobile Chrome] › login.spec.ts:10:5 › Success login test ──────────────────────────────────

To open last HTML report run:

  npx playwright show-report

$ node -v
v20.11.1

$ npx @playwright/test --version
Version 1.42.1

![1711450693055blob](https://github.com/microsoft/playwright/assets/31409058/e2774fc4-d71f-4b93-acd5-667226bb326c)
![1711450563061blob](https://github.com/microsoft/playwright/assets/31409058/7594b766-751b-4375-914e-9d37a5547547)

**Comment by pavelfeldman** [comment]
@Sanjeewahsp same question to you: https://github.com/microsoft/playwright/issues/30058#issuecomment-2015610215

**Comment by Sanjeewahsp** [comment]
Is this issue(Error: browserType.launch: spawn EPERM) related to permission problem? Or existing chrome browser version issue.
I have latest chrome 123.0.6312.59

**Comment by pavelfeldman** [comment]
@Sanjeewahsp so your organization won't let Playwright run Chromium installation on your machine. There isn't much we can do about it.

**Comment by Sanjeewahsp** [comment]
@pavelfeldman, Thank you for the update....

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by aniketicloud** [comment]
I also checked. The issue seems to be related with only Company laptop. Some policy I think is restricting the browser. I checked it with 3 different company laptops and 2 personal laptops. 
I think there should be a proper guide on how to use Docker for E2E, component testing, report generation using shards.

**Comment by aniketicloud** [comment]
At least we have a record for next developers.
