### ISSUE TITLE
Utilizing default Playwright config values through Artillery

### ISSUE THREAD

**Issue by sruthii38** [microsoft/playwright#30050]
I have default headers that are configured in playwright.config.ts and it worked when running playwright test. When I call the same playwright test through artillery, it is not working.

This default config is specific to header.
I tried specifying config in different sections

config:
  engines:
    playwright:
      contextOptions:
        extraHTTPHeaders:
          User-Agent: '****'
 I have also tried setting at artillery default as well    

config:
  http:
    defaults:
      headers:
        User-Agent: "*****"
None of these options worked.

Can you suggest a way to make this work?

**Comment by yury-s** [comment]
This doesn't seem to be a Playwright bug or feature request. Please use [community](https://playwright.dev/community/welcome) resources for general questions.
