### ISSUE TITLE
[Bug]: Error: strict mode violation when using _or (with .locator())... resolved to 2 elements ?

### ISSUE THREAD

**Issue by epicwhale** [microsoft/playwright#30069]
### Version

1.42.0

### Steps to reproduce

(I have simplified the scenario below to try make it more explainable)

I have a page with an iframe. Inside the iframe I have two divs with id #a and #b which are attached to the DOM, but may be visible or hidden. I am trying to write code that waits till one of the two are visible, before proceeding.

```python
my_iframe = page.frame_locator('iframe[title*="foo"]')
a_locator = my_iframe.locator("#a")
b_locator = my_iframe.locator("#b")

await a_locator.is_visible(), await b_locator.is_visible() # <------ this returns False, True
```

But when I do this...

```python
await expect(a_locator.or_(b_locator)).to_be_visible(timeout=3000)
```

I get the following error:
```
Error: Error: strict mode violation: 
locator("#a).or_(frame_locator("iframe[title...").locator("#b")) resolved to 2 
elements:
    1) <div id="a"></div> aka locator("#a")
    2) <div id="b" role="alert">…</div> aka locator("#b")
```

But if I run
```
await a.count(), await b.count()  # <---  returns (1, 1) - which confirms there's just one element per locator
```

Is this working as intended?

### Expected behavior

if either a_locator or b_locator are is_visible() i'd expect the _or condition to succeed. It should work even if both are visible.

### Actual behavior

I get a strict mode violation: saying it resolved to 2 elements.

locator("#a).or_(frame_locator("iframe[title...").locator("#b")) resolved to 2 
elements:

### Environment

```Text
- Operating System: Mac
- Browser: [Firefox]
- Python Version: [3.12]
```

**Comment by yury-s** [comment]
> struggling with the mental model of how _or and .first operate in your example. 

Locators are [strict](https://playwright.dev/docs/locators#strictness) meaning that calling any action/assertion will throw if it resolves to more than one element. In your case `a_locator.or_(b_locator)` resolves to 2 `div`s which violates the condition. Calling [first](https://playwright.dev/docs/api/class-locator#locator-first) or [nth](https://playwright.dev/docs/api/class-locator#locator-nth) is one way to narrow it down to a single element if there are multiple matches. If you don't care which of the elements and whether both of them are visible then `.first` is a good choice.
