### ISSUE TITLE
How to avoid the CDP dection ?

### ISSUE THREAD

**Issue by peaceyourself** [microsoft/playwright#30074]
How to pass the detection from:
https://www.browserscan.net/bot-detection

can not pass the CDP: Chrome DevTools Protocol Detection

```
def test_dectect(browser_context):
    new_page = browser_context.new_page()
    new_page.goto("https://www.browserscan.net/bot-detection")
    print(new_page.title())
    time.sleep(10) # sleep 10 to see the detection result
    browser_context.close()
```

**Comment by yury-s** [comment]
Playwright's primary focus is on e2e testing, stealth mode is out of scope.

**Comment by tdRPA** [comment]
acturally this site only detect console.debug, just replace this function with a empty one do nothing is ok

**Comment by feeops** [comment]
> acturally this site only detect console.debug, just replace this function with a empty one do nothing is ok

Can you give me some code?

**Comment by tdRPA** [comment]
邮件已收到，通常我在1～2天内回复。如有急事，请直接电话联系 ----我的微信 haijun-data
