### ISSUE TITLE
Getting  Error: apiRequestContext.post: unable to verify the first certificate

### ISSUE THREAD

**Issue by vishalks921** [microsoft/playwright#30073]
### Please do not submit this issue.

- [X] I understand
```[tasklist]
### Tasks
```

**Comment by vishalks921** [comment]
Getting this error while test execution of playwright script in Typescript/javascript

here is the code and the terminal response.
PS C:\projects\playwright_test> npx playwright test tests/post.spec.js

Running 1 test using 1 worker
  1) post.spec.js:8:2 › calling post request ───────────────────────────────────────────────────────

    Error: apiRequestContext.post: unable to verify the first certificate
    Call log:
      - → POST https://reqres.in/api/user
      -   user-agent: Playwright/1.42.1 (x64; windows 10.0) node/20.11
      -   accept: /
      -   accept-encoding: gzip,deflate,br
      -   content-type: application/json
      -   content-length: 46


       8 |  test('calling post request',async({request})=>{
       9 |     var baseurl = properties.get("testbaseurl")
    > 10 |             const response = await request.post(baseurl+'/user',{
         |                                            ^
      11 |              data:{
      12 |                 name:'morpheus',
      13 |                 job:'developer',

        at C:\projects\playwright_test\tests\post.spec.js:10:44

  1 failed
    post.spec.js:8:2 › calling post request ────────────────────────────────────────────────────────

  Serving HTML report at http://localhost:63046. Press Ctrl+C to quit

**Comment by yury-s** [comment]
This is a certificate configuration issue on the webserver, see [this post](https://stackoverflow.com/a/60020493). You can try setting  [ignoreHTTPSErrors](https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-get-option-ignore-https-errors) to silence the errors.

If you think this is a bug in Playwright, please follow the bug template and provide reproduction steps.
