### ISSUE TITLE
[Docs]: Incomprehensible sentence

### ISSUE THREAD

**Issue by oliver-gramberg** [microsoft/playwright#30086]
### Page(s)

https://playwright.dev/docs/codegen?utm_source=tldrwebdev

### Description

The sentence in the "Introduction" section, "If the generator finds multiple elements matching the locator, it will improve the locator to make it resilient that uniquely identify the target element," seems wrong to me, beginning at "that." Please review.

**Comment by pavelfeldman** [comment]
Please feel free to send a PR.
