### ISSUE TITLE
Firefox(nightly) not working in headed mode.

### ISSUE THREAD

**Issue by jjs-gobinath** [microsoft/playwright#30087]
This is Hook's code

    [Binding]
    public class Hooks
    {
        public static IBrowser Browser { get; set; }
        public IPage Page { get; set; } = null!;
       

        [BeforeTestRun]
        public static async Task BeforeTestRun()
        {
            var builder = new ContainerBuilder();
            // Register Scenario Context dependencies
            builder.RegisterInstance(new ScenarioContextData());
            // Register other dependencies if needed
            _container = builder.Build();

            var playwright = await Playwright.CreateAsync();
            var browserOptions = ConfigurationService.GetWebSettings();
            BrowserTypeLaunchOptions typeLaunchOptions = new BrowserTypeLaunchOptions
            {
                Headless = browserOptions.HeadLess,
                SlowMo = browserOptions.SlowMo,
            };
            var browserType = browserOptions.BrowserType switch
            {
                "chromium" => playwright.Chromium,
                "firefox" => playwright.Firefox,
                "webkit" => playwright.Webkit,
                _ => playwright.Chromium,
            };

            Browser = await browserType.LaunchAsync(typeLaunchOptions);
        }

        [BeforeScenario]
        public async Task BeforeScenario()
        {
            BrowserNewContextOptions browserContextOption = new BrowserNewContextOptions
            {
                Locale = "en-US",
            };

            var browserContext = await Browser.NewContextAsync(browserContextOption);

            Page = await browserContext.NewPageAsync();

            // Set the page in the Scenario Context for screenshot purpose
            _scenarioContext.Set(Page, "CurrentPage");
        }

       
        [AfterScenario]
        public async Task AfterScenario()
        {
            if (Page != null)
            {
                await Page.CloseAsync();
            }
        }

        [AfterTestRun]
        public static async Task AfterTestRun()
        {
            if (Browser != null)
            {
                await Browser.CloseAsync();
                await Browser.DisposeAsync();
            }
            _container.Dispose();
        }
    }
}

I'm sending the browser type from appsetting file.
{
  "webSettings": {
    "browserType": "firefox", //chromium - firefox - webkit
    "Headless": false,
    "SlowMo": 4000,
  }
}

All browsers (Chromium, Webkit, msEdge(UsingChannel) are also working fine.
But Firefox is launching a nightly browser but it hangs in the below line and does not proceed further

 **var browserContext = await Browser.NewContextAsync(browserContextOption);**

**Comment by pavelfeldman** [comment]
Please follow the BUG template to share a scenario we can reproduce locally.
