### ISSUE TITLE
Access Denied while launching codegen or while running a script

### ISSUE THREAD

**Issue by sundar-ds** [microsoft/playwright#30099]
### Version

1.40

### Steps to reproduce

Steps:

```
Microsoft Windows [Version 10.0.22631.3296]
(c) Microsoft Corporation. All rights reserved.

C:\Users\102709>playwright codegen google.com
Access is denied.

C:\Users\102709>
```

### Expected behavior

Would like to see codegen launched

### Actual behavior

Getting 'Access Denied' error

### Additional context

It was all running fine until there were patch updates done today in our company. I would like to understand what I need to say to my company's IT team in order to allow access back to playwright.

### Environment

```Text
- Operating System: [Ubuntu 22.04]
- CPU: [arm64]
- Browser: [All, Chromium, Firefox, WebKit]
- Python Version: [3.12]
- Other info:
```

**Comment by pavelfeldman** [comment]
You should always use and run local installations of Playwright in the environment where Playwright is installed. Looks like you are trying to run some global Playwright installation.

**Comment by sundar-ds** [comment]
Hello - Playwright is installed in local user directory under C:\Users\<My UserID>\AppData\Local\Programs\Python\Python311\Lib\site-packages directory. This was working fine until yesterday when some patches were deployed. Trying to figure out what could be the reason that is preventing this working anymore.

**Comment by pavelfeldman** [comment]
This would be a python environment issue, does not seem to be related to Playwright in this case.

**Comment by sundar-ds** [comment]
It turned out to be an issue with the new Symantec security patch that was applied on all of our laptops that was preventing execution of scripts. Once the security policy was updated, it got resolved.
