### ISSUE TITLE
[Bug]: Playwright installs a Chromium version that's not ahead of mainstream branded Chrome

### ISSUE THREAD

**Issue by tszynalski** [microsoft/playwright#30096]
### Version

1.42.1

### Steps to reproduce

1. Install Playwright extension for VS Code.
2. Install Playwright from VS Code.
3. Check version of Chromium installed in AppData\Local\ms-playwright\

### Expected behavior

I expected to see a Chromium version 124 or higher.
The stable channel version of Chrome on my PC is 123.0.6312.59.

### Actual behavior

Playwright installed Chromium 123.0.6312.4, which is actually slightly lower than the current stable Chrome version.

### Additional context

The Playwright documentation repeatedly states that the bundled Chromium version is ahead of current mainstream versions of Chrome and Edge.

Example quotes:

https://playwright.dev/docs/browsers#when-to-use-google-chrome--microsoft-edge-and-when-not-to
> Using the default Playwright configuration with the latest Chromium is a good idea most of the time. Since Playwright is ahead of Stable channels for the browsers, it gives peace of mind that the upcoming Google Chrome or Microsoft Edge releases won't break your site. You catch breakage early and have a lot of time to fix it before the official Chrome update.

https://playwright.dev/docs/browsers#chromium

> For Google Chrome, Microsoft Edge and other Chromium-based browsers, by default, Playwright uses open source Chromium builds. Since the Chromium project is ahead of the branded browsers, when the world is on Google Chrome N, Playwright already supports Chromium N+1 that will be released in Google Chrome and Microsoft Edge a few weeks later.

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700K
    Memory: 23.17 GB / 31.79 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.87.2 - C:\Users\Tomasz\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.42.1 => 1.42.1
```

**Comment by pavelfeldman** [comment]
At the time of the release, 1.42 was ahead of the Stable channel. Chrome 123 went stable last week: https://chromiumdash.appspot.com/schedule. When Playwright 1.43 releases it'll also be ahead of Chrome stable.

**Comment by tszynalski** [comment]
The documentation states that "it gives peace of mind that the upcoming Google Chrome or Microsoft Edge releases won't break your site". If your interpretation of "ahead of stable" is "ahead of stable **at the precise moment a new Playwright version is released**", then I'm afraid it doesn't give developers any peace of mind. I am using the latest Playwright version and an upcoming Chrome release **could** still break my site. Please make sure Playwright uses newer Chromium versions or change the documentation to remove the promises you are making.
