### ISSUE TITLE
[Feature]: browserContext.clearHttpCache()

### ISSUE THREAD

**Issue by subpardaemon** [microsoft/playwright#30098]
### 🚀 Feature Request

Right now there is no way to clear the HTTP (network) cache, so any aggressively cached items become stale and might interfere with testing.

### Example

We've hit a problem where part of the application we're testing is utilizing aggressive http caching on some important data, and part of our test is to change some of that data -- so subsequent tests fail because the cached data is in-place. Tried the suggested `page.route('**', route => route.continue());` fix but that just failed spectacularly. Honestly, a clear network cache management function should be a part of browser interactions.

### Motivation

It will allow clearing HTTP cache at crucial moments, preventing stale data from interfering with tests.

**Comment by pavelfeldman** [comment]
Could you provide a complete scenario that would demonstrate the issue?

**Comment by subpardaemon** [comment]
Ok, here's the current scenario.

We're testing an LTI tool that integrates with Instructure's Canvas LMS (https://github.com/instructure/canvas-lms). Part of our test requires testing in Canvas. First we need to create a seed course. Another part of the test requires recreating the LTI tool integration which changes the tool's integration ID. Finally yet another part of the test requires going to the course assets, clicking on a context menu and choosing an option that comes from the LTI tool thus bears its integration ID.

I have created an optimization path that checks if the instance being tested has the correct seed course already and if so it forgoes deleting the current one and creating a new one. However, that introduced failures to the test, and since I'm close to the Canvas developers we quickly identified the root cause of the issue.

What happens is that the course metadata (that contains stuff like LTI tool integration IDs, which is crucial for our test workflows) is sent from the Canvas server with a long (almost hour-long) cache instruction header (HTTP protocol level caching). So consequently, if I don't delete the course, the associated metadata remains in the cache, but in the meantime I change the LTI tool integration so the ID that was cached with the previous metadata, and whenever I want to refer to the LTI tool I get an incorrect ID error.

So right now I cannot use the optimization which would spare about 3 minutes from a test run, which is significant. If I could clear the browser cache, the stale metadata would not interfere.

**Comment by subpardaemon** [comment]
What I tried so far:
- change the order of LTI tool provision and course integrity checker, but the long cache persists across test runs (when using the test on a local machine; in Jenkins of course the previous cache is discarded along with the container it ran in);
- tried the route hack (adding routes disables the HTTP caching) but it caused a hang in a certain part of the test.

What I've been thinking about: using route, but detecting long cache times in response headers and rewriting them.

But this all just tries remedying a seriously lacking functionality which should be a given for a browser-based testing solution.

**Comment by pavelfeldman** [comment]
What would really help is describing it in Playwright + HTTP terms, that way we would be able to act and add a test for the issue. For example, "I have two tests that run in the same worker (and reuse the same browser). Despite running in two different browser contexts, first test populates the disk cache and the send test is picking the resource from cache, although it is supposed to receive different data". Is that the scenario? Hows does your backed know which test runs, is it supposed to return new response every time? If so, why is caching aggressive?

We need a reduced test case that we can add into our test suite so that we could address and fix it. Without understanding your scenario we can't act on it.

**Comment by subpardaemon** [comment]
Ok, we might be talking about a different thing here, but since there is not a lot of documentation about it, I might be wrong in some of my assumptions.

1. Playwright uses actual browser engines which respect HTTP cache headers, ie. if the response specifies that this response should be cached for 15 minutes, the browser would keep the cached version in its cache for 15 minutes and when the tested webpage would ask for the same resource (say, via XHR or fetch) it would serve the cached version instead of the actual resource. Is this correct?
2. When running a test, the page property has a browser property which is a new instance of the browser, but a new instance in the sense like a new window or a new tab; it still holds the same non-session cookies, same local storage, etc, _and most importantly_ the HTTP cache, so the state persists from the last run as long as the filesystem that supports the browser is intact. Is this correct? Or is a new browser instance a clean slate? The HTTP cache persisting across tests does not seem to suggest that.
3. When specifying a new incognito browser for a test, none of the stored items from the "normal" browser instances would be present, but it would have its own cache, cookie, local storage etc instance, right? So if we were to peruse the incognito browser in subsequent tests, it would also persist with the cache?
4. Canvas's official solution for the cache problem is to turn on developer mode and tick the "Disable cache" on the Network tab, or emptying the cache. Is there any way to do either of these in Playwright that does not involve serious hacking? (Like trying to delete state files.)

As for a simple enough scenario, I would suggest this:

1. Have a simple backend/frontend app. The backend would have two calls: PUT /number?<N>, GET /number. Once a PUT is called, it stores the number in persistent state. Once a GET is called, return the stored number with a 5-minute cache instruction header. The frontend would have two buttons, one called STORE which would have a number input besides, and a RETRIEVE button with a span next to it that is supposed to show the retrieved number.
2. Do this: a) STORE 5, b) RETRIEVE, c) assert span has 5 as content, d) STORE 10, e) RETRIEVE, f) assert span has 10 as content, g) wait 5 minutes, h) RETRIEVE, i) assert span has 10 for content.
3. If the HTTP caching works as supposed to in a browser, f) should fail as the RETRIEVE should fetch the result from the HTTP cache which would still have 5; and i) should complete as now the cache would be cleared so the current result would be retrieved from the backend.

If we had cache expunge, we could call it before e) and thus f) should pass.

**Comment by pavelfeldman** [comment]
I'm sorry, I still can't make sense of it. 

> We need a reduced test case that we can add into our test suite so that we could address and fix it.

^^ this would be the key to resolving the issue.

**Comment by subpardaemon** [comment]
I can't think of a more reduced test case than what I provided. The main issue is that the browsers (at least Chromium) respect HTTP caching but provide no methods to expunge the HTTP cache. And if a tested website/app uses agressive caching that can cause problems if the test changes something that is cached by the target site/app.

In normal life this does not present an issue as what I change during the test rarely gets changed, so caching is more than warrented for it.

> I have two tests that run in the same worker (and reuse the same browser).
Correct.
> Despite running in two different browser contexts
I'm not sure about this. I'm running tests in sequence. I'm not sure the context is different. I'm most definitely not creating new windows/tabs. But I'm running test cases in sequential order one after another.
> first test populates the disk cache and the send test is picking the resource from cache, although it is supposed to receive different data
It's a bit more complex than that, that's why I provided the test case with a backend/frontend stuff. 

I'm not _directly_ fetching something that should not be served from the cache, the _webpage's XHR/fetch_ does. 

As I said, there are some course-related metadata that Canvas supplies for the frontend via AJAX calls and sets a long caching header on such replies because it's an expensive operation to collect that metadata. During the test I'm first checking something on the course page so it will do the AJAX call and store the response in the cache. _Then_  I'm changing something that has an effect on this metadata. And _then_ I have to go back to the course page, but due to the AJAX response being served from the cache rather than from the actual tested site it will have incorrect IDs there which break my test in the next step. The order is sadly mandatory.

This is why I posted a feature request to be able to either clear the HTTP cache of the browser or to have something to the effect of Disable Cache (in dev mode's network tab) in Playwright. If I had that, then before I go back to the course page the second time I could clear the HTTP cache thus the metadata AJAX fetch would serve me fresh (and valid) data.

**Comment by pavelfeldman** [comment]
I think we have a misunderstanding. When I say:

> We need a reduced test case that we can add into our test suite so that we could address and fix it. Without understanding your scenario we can't act on it.

What I mean is a test file that demonstrates the issue or desired behavior. We'll then insert the following snippet there and investigate why the cache is still used. Without the test case, we can't proceed with the investigation.

```js
await page.route('**', route => route.continue());
```

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
