### ISSUE TITLE
[Feature]: Access `testInfo` in custom matchers

### ISSUE THREAD

**Issue by SUSAltd** [microsoft/playwright#30101]
### 🚀 Feature Request

Much like how you can access `testInfo` as a parameter in custom fixtures, I would like to be able to access `testInfo` in custom matchers.

### Example

In my specific use-case I'm writing a matcher that, on failure, I'd like to attach a file to the test report. I'd love to be able to use `testInfo.attach()` for attaching files or `testInfo.outputhPath()` for managing temporary files, but there doesn't seem to be any way to access these from a matcher, besides importing it as a parameter which just feels excessive and wrong.

### Motivation

`testInfo` provides great use in writing tests and custom fixtures. It would be wonderful to bring all of its utility into custom matchers as well.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
