### ISSUE TITLE
[Bug]: toHaveScreenshot does not honor maxDiffPixelRatio or maxDiffPixels

### ISSUE THREAD

**Issue by DavidHudlow** [microsoft/playwright#30112]
### Version

1.42.1

### Steps to reproduce

1. Write a test using line `expect(page).toHaveScreenshot({ maxDiffPixelRatio: 0.05 });`
2. Run test with a screenshot that varies by, say, 0.02 pixels

### Expected behavior

Test passes

### Actual behavior

Test fails reporting the correct number of pixel and pixel ratio variation that is below the set thresholds

### Additional context

Workaround is `expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.05 });` which works as expected.

Adding `maxDiffPixels` does not help.

### Environment

```shell
System:
    OS: macOS 13.6.4
    CPU: (12) arm64 Apple M2 Max
    Memory: 12.34 GB / 64.00 GB
  Binaries:
    Node: 18.19.1 - ~/.volta/tools/image/node/18.19.1/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.19.4 - ~/.volta/tools/image/npm/8.19.4/bin/npm
  IDEs:
    VSCode: 1.87.2 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.42.1 => 1.42.1 
    playwright: 1.42.1 => 1.42.1 
    playwright-core: 1.42.1 => 1.42.1
```

**Comment by pavelfeldman** [comment]
Please use the BUG template to file something we can reproduce.

**Comment by DavidHudlow** [comment]
@pavelfeldman I'm afraid I don't understand what you mean. I used the bug template. Did I fill something out incorrectly?

**Comment by rkmsnc** [comment]
Hi @DavidHudlow 
This could help https://github.com/microsoft/playwright/issues/31592#issuecomment-2361010102
