### ISSUE TITLE
[Feature]: Emulate `navigator.cookieEnabled` false, to test When Cookies are disabled for the Website

### ISSUE THREAD

**Issue by nitzanashi** [microsoft/playwright#30115]
### 🚀 Feature Request

To Test the scenario where Cookies are disabled for the Website, we would like to have the option to disable cookies for the `navigator` object of the `window`.

### Example

In Cypress it would work like the following: 
```js
cy.visit('/login', {
    onBeforeLoad(win) {
        cy.stub(win.navigator, 'cookieEnabled', false);
    },
});
```

### Motivation

We are migrating from Cypress to Playwright, and currently, we want to test the behaviour of our WebApp when Cookies are disabled.

**Comment by nitzanashi** [comment]
@pavelfeldman Thanks a lot, that did the trick for us

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
