### ISSUE TITLE
[Bug]: Chromium page.goto() takes 20+s in Gitlab CI / Docker

### ISSUE THREAD

**Issue by voobel** [microsoft/playwright#30117]
### Version

1.41.1

### Steps to reproduce

1. In Gitlab CI use image `playwright:v1.41.1-jammy`
2. Run tests with Chromium: `DEBUG=pw:api CI=true npx playwright test --project=chromium --trace on`
3. Observe trace: `npx playwright show-trace /path/to/trace.zip`

### Expected behavior

Initial page load is quick

### Actual behavior

Initial page load takes 20+ seconds, after which it is as fast as supposed to:
`pw:api   "commit" event fired +20s`
![Screenshot 2024-03-26 at 12 04 43](https://github.com/microsoft/playwright/assets/8283862/4a912b42-f15f-4b42-9dea-2aa522163a7b)

### Additional context

* Doesn't happen locally within same Docker image
* Tried various Chromium launch options (no effect), for ex. `--disable-dev-shm-usage`; `--no-sandbox`; `--use-gl=egl`; `--disable-extensions`; `--disable-gpu`; ..
* Tried removing tracing/videos/screenshots (no effect)
* Tried giving container more CPU and memory (no effect)
* Firefox tests run fast within same container

### Environment

```shell
System:
    OS: Linux 6.3 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (6) arm64 unknown
    Memory: 6.70 GB / 7.67 GB
    Container: Yes
  Binaries:
    Node: 20.11.0 - /usr/bin/node
    Yarn: 1.22.21 - /usr/bin/yarn
    npm: 10.2.4 - /usr/bin/npm
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.41.1 => 1.41.1
```

**Comment by pavelfeldman** [comment]
I don't think we can act on this issue, especially given that it works for you on local Docker. Probably makes sense to redirect this to GitLab, maybe they have some profiling tools that would explain the difference in behavior.
