### ISSUE TITLE
[Bug]: `window.chrome` undefined when running headlessly

### ISSUE THREAD

**Issue by alectrocute** [microsoft/playwright#30133]
### Version

1.42.1

### Steps to reproduce

1. Write a basic test that evaluates `window.chrome`, run it with `devices['Desktop Chrome']` as a project
2. Run aforementioned test in Browser (eg. "Show browser" selected), observe value of `window.chrome`
3. Run aforementioned test in Trace Viewer, observe value of `window.chrome`

### Expected behavior

`window.chrome` should be defined in any Chromium-based test, whether in the Trace Viewer or Browser.

### Actual behavior

`window.chrome` is undefined when running headless (eg. Trace Viewer or on CI).

### Additional context

Many web apps check `window.chrome` to determine if the browser is Chrome or not. Currently, we have to manually handle this in an `addInitScript`, eg:

```
await page.addInitScript(() => {
  window.chrome = window.chrome ?? {
    loadTimes: () => ({}),
    csi: () => ({}),
  };
});
```

Feels hacky and definitely not ideal. Yes, I know this may be a Headless Chrome bug, but in my opinion we should still fix this behavior in Playwright for a better developer experience instead of waiting for a fix on Chrome's end.

### Environment

```shell
System:
    OS: macOS 14.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 450.70 MB / 32.00 GB
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  IDEs:
    VSCode: 1.87.2 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by pavelfeldman** [comment]
Does this mean your web app will only open in Chrome?

**Comment by alectrocute** [comment]
> Does this mean your web app will only open in Chrome?

@pavelfeldman Hmm? No, but that's besides the point. 😅 `window.chrome` should be defined on both headless/non-headless Chrome. A lot of apps use `window.chrome` to check if the user's browser is Chrome or not.

**Comment by pavelfeldman** [comment]
It does and it does not:

I understand that different behavior between headless and headed is suboptimal. You can try mitigating it using [headless=new](https://playwright.dev/docs/chrome-extensions#headless-mode) which is a built-in Chrome mode that tries to align headless behavior with Chrome. It can be good and bad - it is slower, it respects policies, etc. But in your case it could mitigate your use case.

Having said that, browser detection (and UA parsing) is strongly discouraged within the web community. It was deemed bad for more than a decade and the consensus was that feature detection should be used instead. Searching the terms "browser detection", "UA parsing" and "feature detection" will yield some good results. As a cross-browser testing framework, we endorse the feature detection as it allows for more reliable cross-browser operation.

**Comment by pavelfeldman** [comment]
I'll close this as not planned since we don't think web should depend on window.chrome.
