### ISSUE TITLE
[Docs]: NPM install of browsers doesn't seem to work

### ISSUE THREAD

**Issue by shanegray** [microsoft/playwright#30132]
### Page(s)

https://playwright.dev/docs/library

### Description

According to the docs you can install browsers entirely through NPM install scripts.

e.g:
```
# Alternatively, add packages that will download a browser upon npm install
npm i -D @playwright/browser-chromium @playwright/browser-firefox @playwright/browser-webkit
```

This doesn't seem to be the case - you have to run npx playwright install

**Comment by pavelfeldman** [comment]
`npm i -D @playwright/browser-chromium` installs the browser for me. It does not install it if the package has already been installed though. The idea behind those packages is that they are used on the CI and no one is deleting the browsers behind its back.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by shanegray** [comment]
When I run `npx playwright uninstall --all`

Then install playwright through npm packages only - I get the following message:

<img width="678" alt="image" src="https://github.com/microsoft/playwright/assets/3775293/a826fba0-89fa-4b75-ba37-dcfb8c070921">

Tried on multiple machines and on docker containers also.
