### ISSUE TITLE
Documentation for Visual Comparison is not available for JAVA.

### ISSUE THREAD

**Issue by KrushnaMa** [microsoft/playwright#30145]
### Page(s)

Documentation for Visual Comparison is not available for JAVA.

### Description

1) Go to "https://playwright.dev/docs/test-snapshots" and verify that documentation for Visual Comparison is available for Node.js.
2) Now click on chevron button to select the JAVA.
3) You could see that documentation is not available.

From the below image, please note that I selected language as JAVA, but it is not displaying it.
<img width="950" alt="VisualCompare" src="https://github.com/microsoft/playwright/assets/157467775/7c3bf309-35e6-4a05-bec4-91f3d555df7f">

**Comment by pavelfeldman** [comment]
This part of the documentation belongs to @playwright/test, which is a Node.js test runner. We don't have our own Java test runners, so supporting visual testing is deferred to the third party.
