### ISSUE TITLE
[Feature]:  Add support to merge the JSON results report 

### ISSUE THREAD

**Issue by costa-collibra** [microsoft/playwright#30143]
### 🚀 Feature Request

In our Jenkins pipelines, we currently run with 4 shards and for each shard when the tests have finished we process the results.json file and send those logs to elastic search. This is mostly fine for all our test level logs however as each shard contributes to the overall build, we are finding it really hard to consolidate build level logs that we can send to elastic search as all of the shards are isolated.

Example 1:

Shard 1 - Pass
Shard 2 - Pass
Shard 3 - Fail
Shard 4 - Pass

Build Status - Fail

Example 2:

Shard 1 - Pass
Shard 2 - Pass
Shard 3 - Pass
Shard 4 - Pass

Build Status - Pass

### Example

It would be great if you could consolidate the json results for each shard into a single json file that has the overall build level information in it. Like you do for the HTML report.

<img width="946" alt="image" src="https://github.com/microsoft/playwright/assets/118260471/15b89f32-eb2d-4e0f-8266-e45e1fba0eee">

This would significantly reduce the complexity in our Grafana dashboards which is not the correct place to calculate Build Passing Percentage

### Motivation

This feature will no doubt make Playwright more powerful for teams that run large scale tests with lots of shards.

**Comment by pavelfeldman** [comment]
Please refer to the sharding documentation https://playwright.dev/docs/test-sharding#merge-reports-cli. Search for merging reports there.

**Comment by costa-collibra** [comment]
@pavelfeldman I have looked here but I do not see any support for merging JSON.

Can you tell me if this is possible?

**Comment by costa-collibra** [comment]
```
➜  playwright git:(DEV-84959/fix-update-tests) ✗ npx playwright merge-reports --reporter=json ./blob-reports-all
Error: No report files found in /Users/costa.giannakopoulos/Workspace/e2e-tests/playwright/blob-reports-all
```

I have 2 json files in this directory. 1 for shard

playwright/blob-reports-all/result1.json
playwright/blob-reports-all/result2.json

**Comment by pavelfeldman** [comment]
You should follow the doc and replace --reporter=html with --reporter=json

**Comment by costa-collibra** [comment]
Thank you trying it now

**Comment by alectrocute** [comment]
> You should follow the doc and replace --reporter=html with --reporter=json

Doesn't work for me, @pavelfeldman. I get the following error:

```bash
Error: No report files found in /Users/alec/Desktop/<root>/frontend/all-json-reports
```

I have confirmed that there's reports in that directory:

```bash
ls /Users/alec/Desktop/<root>/frontend/all-json-reports
json-report-1.json json-report-2.json json-report-3.json json-report-4.json
```

**Comment by nicolas-besnard** [comment]
Same issue here

```bash
tree all-json-reports
all-json-reports
├── json-report-main-app-1.zip
├── json-report-main-app-2.zip
├── json-report-main-app-3.zip
└── json-report-main-app-4.zip
```

When running `npx playwright merge-reports --reporter json ./all-json-reports`, I have the error `Error: No configure events found`

**Comment by twalshOG** [comment]
> Same issue here
> 
> tree all-json-reports
> all-json-reports
> ├── json-report-main-app-1.zip
> ├── json-report-main-app-2.zip
> ├── json-report-main-app-3.zip
> └── json-report-main-app-4.zip
> When running `npx playwright merge-reports --reporter json ./all-json-reports`, I have the error `Error: No configure events found`
@nicolas-besnard 
Looks like 1.53.1 release fixes this
