### ISSUE TITLE
[Bug]: A full-page screenshot does not capture the website properly because the window resizes to a width and height of 1px.

### ISSUE THREAD

**Issue by kamilms21** [microsoft/playwright#30149]
### Version

1.42.1

### Steps to reproduce

1. Go to any webpage
2. Capture full-screenshot

### Expected behavior

Playwright should not resize window to 1px width and 1px width.

### Actual behavior

Playwright resizes the window to 1px just before taking the screenshot, and then back to the given viewport dimensions. Is this expected behavior? Because of this, some webpages are not being properly captured in the screenshot.

I am debugging this issue using the following code

```javascript
await page.evaluate(() => {
    window.addEventListener("resize", function () {
      console.log("Window resize", {
        height: window.innerHeight,
        width: window.innerWidth
      });
    });
  });

  const screenshot = await page.screenshot({
    fullPage: true,
    captureBeyondViewport: true,
  });
```

The logged output:
```
Window resize
 } height: 1, width: 1 }
{ height: 1080, width: 1440 }
```

This is a webpage where this problem appears.

https://www.tui.co.uk/destinations/bookaccommodation?dp=t&price=pp&tab=overview&multiSelect=true&greatDealDiscount=0&units[]=951830:HOTEL&fc=n&duration=7&productCode=951830&pkg=1307466982/3/668/7&tra_o=Ae49d184078e4a5ece117bdff6280aeb8&tra_i=Ae49d184078e4a5ece117bdff6280aeb8&brandType=T&bb=AI&rmbb=AI&rmtp=DD01&airports[]=LGW&noOfAdults=2&noOfChildren=0&rmpc=1|2|0|0|0|&when=30-10-2024&packageId=951830TZZN002117301600000001730246400000EK1617308512000001730937600000EK2191DD011307466982/3/668/7

### Environment

```shell
System:
    OS: macOS 14.1.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 37.69 MB / 16.00 GB
  Binaries:
    Node: 16.0.0 - ~/.nodenv/versions/16.0.0/bin/node
    Yarn: 1.22.17 - ~/.nodenv/versions/16.0.0/bin/yarn
    npm: 7.10.0 - ~/.nodenv/versions/16.0.0/bin/npm
  IDEs:
    VSCode: 1.87.2 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    playwright: ^1.42.1 => 1.42.1 
    playwright-extra: ^4.3.6 => 4.3.6
```

**Comment by pavelfeldman** [comment]
I can only see one resize log.

![image](https://github.com/microsoft/playwright/assets/883973/ef93ebe2-4918-4f08-964f-4e69101180e0)


Btw, Playwright does not support the captureBeyondViewport option.

**Comment by kamilms21** [comment]
@pavelfeldman thanks for checking.

I investigated further, and it still happens for me (tested on macOS and additionally in a Docker environment). It does not happen every single time, so you might want to take a screenshot a few times to reproduce.

I have also tested it on https://try.playwright.tech/?l=javascript&s=4nfgzrp, but I slightly modified the code so it does not console log window resizes but instead prepends a new paragraph to the <body> element (console logs are not visible within this playground). Issue also happen here (see a top of the screenshot)

<img width="1750" alt="Screenshot 2024-03-27 at 19 05 07" src="https://github.com/microsoft/playwright/assets/25887313/de9b6a1b-e62a-4a23-9861-4fe15cffeaca">

**Comment by kamilms21** [comment]
It looks like this is an issue related to Chromium, which complicates things a bit.
https://issues.chromium.org/issues/40256133

I can reproduce this when taking a screenshot in the dev tools.

<img width="1770" alt="Screenshot 2024-03-27 at 21 35 12" src="https://github.com/microsoft/playwright/assets/25887313/d17d670d-7a91-4ab7-b283-22c18293c833">


> It is a little tricky copying code from your screenshot. Please follow the BUG template to provide reproduction that we can use locally.

I have attached a code in the first post, but essentially the default "full-page" screenshot causes issues

**Comment by pavelfeldman** [comment]
Please refer to the BUG template and provide the repro scenario we can run locally.
