### ISSUE TITLE
[Bug]: Twitter can not post images or videos

### ISSUE THREAD

**Issue by Louis24** [microsoft/playwright#30144]
### Version

1.41.2

### Steps to reproduce

```
import time
from playwright.sync_api import Playwright, sync_playwright


def post(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False, proxy={"server": "http://127.0.0.1:7890"})
    context = browser.new_context(viewport={"width": 1600, "height": 900}, storage_state="auth1.json")
    page = context.new_page()
    page.goto("https://twitter.com/")
    page.get_by_test_id("AppTabBar_Profile_Link").click()
    page.get_by_test_id("SideNav_NewTweet_Button").click()
    page.get_by_role("textbox", name="Post text").click()
    page.get_by_role("textbox", name="Post text").fill("hi")

    upload_button = page.locator('input[data-testid="fileInput"]')
    upload_button.set_input_files("C:\Zero\Python\PlayWright\hi.png")
    time.sleep(2)
    page.get_by_test_id("tweetButton").click()
    context.close()
    browser.close()


if __name__ == '__main__':
    with sync_playwright() as playwright:
        post(playwright)

```

### Expected behavior

click post button and exit

### Actual behavior

![image](https://github.com/microsoft/playwright/assets/18719360/d705f6de-6850-4fa2-9175-20cfe2fb90ce)

Finally, the picture was uploaded (not sent), but it didn't seem to be sent. After terminating at this screen, the program exited. The mechanism for Twitter is upload a photo here , and  wait until the picture is completely loaded [button is gray and cannot be clicked], Should I add waiting time here?

### Environment

```shell
- Operating System: Win10
- CPU: Intel(R)Core(TM) i7-10870H CPU @ 2.20GHz(16 CPUs),~2.2GHz
- Browser: Chromium
- Python Version: [3.11]
- Other info: None
```

**Comment by Louis24** [comment]
Btw, is there a method in codegen that turn the code into "locator" not "get_by_role..get_by_test_id" stuff like that?

**Comment by Louis24** [comment]
PS, I can sucessfully submit the text now

**Comment by pavelfeldman** [comment]
Does not look like a bug.

**Comment by Louis24** [comment]
> Does not look like a bug.

How should I solve that?
