### ISSUE TITLE
[Bug]: UI mode filtering by tag does not work for explicit tags

### ISSUE THREAD

**Issue by marshmn** [microsoft/playwright#30146]
### Version

1.41.2

### Steps to reproduce

1. Create a test with an explicitly defined tag (not in the test name)

```typescript
test("my test", { tag: [ "@foo"}, async ({ page }) => { //... });
```

2. Open Playwright in UI mode
3. Enter the tag name in the filter box: `@foo`

### Expected behavior

I expect to see the tagged test.

### Actual behavior

Tagged test is not shown.

### Additional context

Tags mentioned in the test name work as expected.

### Environment

```shell
System:
  OS: Linux 5.11 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 12.91 GB / 31.00 GB
  Container: Yes
Binaries:
  Node: 20.11.1 - /usr/bin/node
  Yarn: 1.22.21 - /usr/bin/yarn
  npm: 10.2.4 - /usr/bin/npm
Languages:
  Bash: 5.1.16 - /usr/bin/bash
npmPackages:
  @playwright/test: 1.42.1 => 1.42.1
```

**Comment by pavelfeldman** [comment]
This was fixed, should be a part of 1.43.
