### ISSUE TITLE
[Feature]: add channel argument to `executablePath`

### ISSUE THREAD

**Issue by Le0Developer** [microsoft/playwright#30158]
### 🚀 Feature Request

Currently it's not possible to use [`.executablePath()`](https://playwright.dev/docs/api/class-browsertype#browser-type-executable-path) to get the path for [channels](https://playwright.dev/docs/browsers#google-chrome--microsoft-edge).

### Example

```js
const executablePath = pw.chromium.executablePath({ channel: "chrome" });
```

### Motivation

I want to start the browser in a way that is not currently possible with playwright and then connect playwright via CDP to it.
Currently there's no way to get the executablePath for chrome/edge, so I'd need to reimplement all the logic playwright already has.

**Comment by Le0Developer** [comment]
This should be relatively trivial to add here:
https://github.com/microsoft/playwright/blob/ffffb81c3b935b7c9c8b310f51e2fa1fdd522843/packages/playwright-core/src/server/browserType.ts#L56-L58

Something along the lines of:
```ts
  executablePath(options?: { channel: string }): string {
    return registry.findExecutable(options?.channel || this._name).executablePath(this.attribution.playwright.options.sdkLanguage) || '';
  }
```

**Comment by pavelfeldman** [comment]
This falls outside of the scope for Playwright project. You can use other packages to discover browser paths.
