### ISSUE TITLE
[Bug]: Fullscreen video not being honored on any platform for Chromium and Chrome - Firefox works

### ISSUE THREAD

**Issue by apkatsikas** [microsoft/playwright#30152]
### Version

1.42.1

### Steps to reproduce

1. Clone repo at https://github.com/apkatsikas/playwright-fullscreen-headless-bug
2. `npm install`
3. `npx playwright install`
4. `npx playwright test`

### Expected behavior

`should show a different bounding box size` should pass for every platform, indicating the fullscreen is being honored.

### Actual behavior

Bounding box does not change for Chromium or Branded Chrome.

### Additional context

In addition to double-click, I have tested with keyboard shortcuts (e.g. `f` key) and fullscreen buttons, to the same effect.

### Environment

```shell
System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 3.14 GB / 32.00 GB
  Binaries:
    Node: 20.11.0 - ~/.volta/tools/image/node/20.11.0/bin/node
    npm: 10.2.4 - ~/.volta/tools/image/node/20.11.0/bin/npm
    pnpm: 7.26.3 - ~/.volta/tools/image/pnpm/7.26.3/bin/pnpm
  IDEs:
    VSCode: 1.87.2 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.42.1 => 1.42.1
```

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/27598
