### ISSUE TITLE
[Bug]: In Jenkis when i am generating report  and sending to email the screenshot and video is not coming properly

### ISSUE THREAD

**Issue by priya-acko** [microsoft/playwright#30155]
### Version

1.41.1

### Steps to reproduce

<img width="1440" alt="Screenshot 2024-03-28 at 1 32 16 AM" src="https://github.com/microsoft/playwright/assets/101645382/e69b6fca-a214-4eab-9226-6a3fb53ff915">

### Expected behavior

the attached video and scrrenshot should be visible

### Actual behavior

it is not attached properly

### Environment

```shell
Mac apple M1 chip
node js
```

**Comment by pavelfeldman** [comment]
It sounds like you are trying to send html report over an email. This is not trivial task, embedding rich content in an email along with the media artifacts is not trivial and in case of video might be even non-feasible. This falls outside of the scope of Playwright - we only generate the report to you.
