### ISSUE TITLE
[Bug]: Can't use electron env vars in github actions for ubuntu

### ISSUE THREAD

**Issue by roco1234** [microsoft/playwright#30154]
### Version

1.41.1

### Steps to reproduce

Cannot use env vars in ubuntu-latest runner for github actions.

> Error: electron.launch: Process failed to launch!

`  
const electronApp = await _electron.launch({
    args,
    env: {
      EXTENSION_MODE: "PLAYWRIGHT",
    }
  });
  `

This works locally on mac and for macos-latest and windows-latest runners in github actions. Is there anything else that can be done to set the env vars?

### Expected behavior

Env vars used in all operating systems

### Actual behavior

Cannot use env vars in ubuntu-latest runner for github actions.

> Error: electron.launch: Process failed to launch!

### Environment

```shell
github actions - ubuntu-latest
```

**Comment by pavelfeldman** [comment]
Does it run Ok without the environment variable? Where is this variable used?

**Comment by mxschmitt** [comment]
Have you tried extending the env?

    const electronApp = await _electron.launch({ args, env: { ...process.env, EXTENSION_MODE: "PLAYWRIGHT", } });

**Comment by pavelfeldman** [comment]
> Yeah it runs fine without the env var. The var is used in the code to check if a playwright test is running so that I can mock a response from child_process.spawn

Sounds like Playwright won't work with mocking child_process.spawn as it uses it as well.

**Comment by pavelfeldman** [comment]
Closing is per above, it sounds like what you are doing is incompatible with Playwright.
