### ISSUE TITLE
[Bug]: Playwright opens several popup conhost windows when running in Windows

### ISSUE THREAD

**Issue by ruifigueira** [microsoft/playwright#30163]
### Version

1.43.0-beta-1711554436000

### Steps to reproduce

- create a new playwright test using the beta version:

```
mkdir pw-test-beta
cd pw-test-beta
npx create-playwright@latest --browser=chromium --install-deps --beta --quiet
```
- run the tests

```
npx playwright test
```

### Expected behavior

Should run without opening popup conhost windows

### Actual behavior

Running the test will open lots of popup conhost windows:

https://github.com/microsoft/playwright/assets/1374559/61fbdc2d-8cb0-4b56-b0d4-39e95ad7c9a2

In process explorer:

![image](https://github.com/microsoft/playwright/assets/1374559/6d94fd22-9c8a-4943-a346-e47168710f68)

### Additional context

It appears to be a chrome problem. If I change the `node_modules/playwright-core/browsers.json` to use the `123.0.6312.4` version:

```
    {
      "name": "chromium",
      "revision": "1105",
      "installByDefault": true,
      "browserVersion": "123.0.6312.4"
    },
``` 

it works as expected.

### Environment

```shell
System:
  OS: Windows 11 10.0.22631
  CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  Memory: 5.24 GB / 31.74 GB
Binaries:
  Node: 18.16.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
  npm: 9.7.1 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
  pnpm: 8.15.4 - ~\AppData\Local\pnpm\pnpm.EXE
IDEs:
  VSCode: 1.87.2 - C:\Users\rui.figueira\scoop\apps\vscode\current\bin\code.CMD   
npmPackages:
  @playwright/test: ^1.43.0-beta-1711554436000 => 1.43.0-beta-1711554436000
```

**Comment by mxschmitt** [comment]
This is fixed on latest Beta https://github.com/microsoft/playwright/commit/62d4dc9ebb19099882a19cc3279276bdf6ba653d and Canary https://github.com/microsoft/playwright/pull/30235 (might take a day to be released).

Thank you @ruifigueira!
