### ISSUE TITLE
[Bug]: Cannot create a string longer than 0x1fffffe8 characters

### ISSUE THREAD

**Issue by kuldeep-lnxct** [microsoft/playwright#30161]
### Version

1.42.0

### Steps to reproduce

Steps
1. install on ubunutu 22.04 
2. pip install pytest-playwright==1.42.0
3. generate pdf file more then 512 MB file size.
4. You should see the error come up

### Expected behavior

its must work with big file size. so i expected to manage inbuilt by library if file size is bigger.

### Actual behavior

its not generating if file size is bigger

### Environment

```Text
- Operating System: [Ubuntu 22.04]
- CPU: [x86_64]
- Browser: [Chromium, WebKit]
- Python Version: [3.8.10]
- Other info:
```

**Comment by pavelfeldman** [comment]
I don't think we'll be fixing this, let's say you are hitting the Playwright limit.

**Comment by buecherlstefan** [comment]
Is there any change of fixing that issue?
