### ISSUE TITLE
[Question]: Is there any way to handle unexpected crasher modals which can appear at any given time during the automation run ?

### ISSUE THREAD

**Issue by devmasonn** [microsoft/playwright#30169]
**Context:**

Playwright Version: 1.33
Operating System: Mac
Node.js version: v18.17.1
Browser: WebKit
Extra: NA

**Description:**
In our product implementation, whenever a unexpected server/ui issue occurs, a crasher modal is seen on the screen inside a iframe. When such a modal appears on the screen, the automated test stalls execution and basically just hangs up there and the error message we get at end of test run is  “Test timedout in random (10000) ms” . Is there any way to detect the presence of this crasher modal on the screen based on the fact that the test gets stuck in execution there.
Any other way we can detect random/unhandled modals on the screen using playwright?

**Questions:**
- How to handle unexpected crasher modals seen on the page, which will help to unblock paused execution ?
- Do I need to setup a code to handle unexpected crasher modals on the global level(means in the config file) or test file level ?

**Comment by pavelfeldman** [comment]
This is not the right place to file questions.
