### ISSUE TITLE
[Feature]: pass custom data to Reporter API

### ISSUE THREAD

**Issue by vitalets** [microsoft/playwright#30179]
### 🚀 Feature Request

I have a custom reporter and I want to pass some data to this reporter from test runtime. The data is specific for this reporter so I want it to be invisible in any other reporters.

### Example

I think about adding `.metadata / .reporterData` property to `testInfo`:
```ts
testInfo.metadata = /* some data */
```
And then in the reporter API:
```ts
  onTestEnd(test: TestCase, result: TestResult) {
    console.log(result.metadata);
  }
```

### Motivation

This feature allows to build richer reporters without impacting other reporters.

I need it for `playwright-bdd` project. To build Cucumber reports I pass bdd steps metadata as a special attachment named `__bddData`. After reading this data I hide this attachment from the Cucumber report. But there is a downside: if user generates both Playwright HTML and Cucumber reports, the first one will still show this weird `__bddData` attachment.

**Comment by vitalets** [comment]
> We can probably keep it simple and not render attachments that start with "_". You'll use the attachments in the form of _bddData_name. Open to a PR.

We can't be sure that all third-party reporters will follow this convention... Maybe introduce `hidden` flag for attachment to make it more explicit?

**Comment by vitalets** [comment]
@pavelfeldman 
Another option I've just discovered - [testProject.metadata](https://playwright.dev/docs/api/class-testproject#test-project-metadata). This is exactly what I need, but on the project level.

I can use it in the runtime:
```ts
testInfo.project.metadata[testInfo.testId] = { foo: 'bar' };
```
Is it reliable way? Or `testProject.metadata` is assumed to be only statically defined in the config?

**Comment by seosmmbusiness** [comment]
There is an annotations array in testInfo. You can push your data there like
```
 test.info().annotations.push({
            type: "performance",
            description: average.toString(),
        });
```

and then get it in reporter 
```
onTestEnd(test: TestCase, result: TestResult) {
 console.log(test.annotations)
}
```

**Comment by vitalets** [comment]
> There is an annotations array in testInfo. You can push your data there like

Yes. But you will get these annotations visible in the html reporter. 
The main goal of this issue is to pass custom data without affecting other reporters ui.

**Comment by hfc-mjzink** [comment]
I too am attempting to output information from the custom reporter, specifically to the jUnilt XML file using something like this: testInfo.annotations.push({ type: 'step', description: step.title });

**Comment by vitalets** [comment]
Just want to demo how ugly current HTML report looks when we pass custom data via annotations.
![image](https://github.com/microsoft/playwright/assets/1473072/dd8e09cd-93cd-4b16-a312-610e11f6e1fc)

@pavelfeldman I'm ready to create pull-request if approach is agreed. What we can do:
1. don't render **attachments** started with "_"
2. don't render **annotations** started with "_"
3. don't render both
4. provide explicit flag `hidden: true` for hidden attachments/annotations

What do you think?

**Comment by servohatred** [comment]
Bump to this feature, serializing data to send it to the reporter affects all the other reporters.
