### ISSUE TITLE
[Bug]: webkit crashed in youtube.com

### ISSUE THREAD

**Issue by lenjoy** [microsoft/playwright#30174]
### Version

1.17.0-rc1

### Steps to reproduce

command line:
```
playwright codegen -b webkit youtube.com
```

webkit crashed, got

```
page.goto: Navigation failed because page crashed!
=========================== logs ===========================
navigating to "http://youtube.com/", waiting until "load"
============================================================
    at openPage (/opt/homebrew/lib/python3.11/site-packages/playwright/driver/package/lib/cli/cli.js:397:16) {
  name: 'Error'
}
```

btw, it's working in some other website such as google.com

### Expected behavior

should be able to render the page

### Actual behavior

webkit browser crashed

### Environment

```shell
Apple M1, 16G
Mac OS: 13.5.2 (22G91)
```

**Comment by mxschmitt** [comment]
Your Playwright version looks very old! Have you tried a more recent Playwright version?

See here: https://pypi.org/project/playwright/

**Comment by lenjoy** [comment]
upgraded to Version 1.42.0, it's working now. thanks
