### ISSUE TITLE
[Question] Wait for last response from same API

### ISSUE THREAD

**Issue by alejavaz** [microsoft/playwright#30177]
Hello. 

I have a process in which when I'm clicking on a button.. a random # of responses comes from the same API (graphql) If I use the page.waitForResponse(URL) it waits for the first one and continues. 

Since the rest are not performed yet and the components are not loaded on screen, the test fails. 

Is there a way to be able to wait for the last response instead of the first one it gets?

**Comment by pavelfeldman** [comment]
Please use other means for asking questions as documented (Discord)
