### ISSUE TITLE
"Your browser is not currently supported"

### ISSUE THREAD

**Issue by Sweetbabooo** [microsoft/playwright#30173]
I'm attempting to use Playwright to automatically change my stream information on Twitch, Kick, and YouTube. When I attempt to log in, it raises an error saying the browser is not currently supported. I've tried changing the user agent and launching from the chrome channel of chromium. Why is this, and how can I fix it?

**Comment by Sweetbabooo** [comment]
![Screenshot_2024-03-28_145936](https://github.com/microsoft/playwright/assets/74666030/34657046-7d5c-4776-a73c-744eee17f40a)

**Comment by pavelfeldman** [comment]
They think (rightfully?) that you are scraping, so they won't let you open the page.

**Comment by Sweetbabooo** [comment]
> They think (rightfully?) that you are scraping, so they won't let you open the page.

There’s no workaround for this? I’m not trying to scrape, I want to change my stream title on twitch/kick/YouTube. I’d use the APIs for this, but kick hasn't released a public API that allows you to change stream titles yet

**Comment by Merbuz** [comment]
Someone help, I have the same problem

**Comment by TheLovinator1** [comment]
@Merbuz @Sweetbabooo

Try with this fork instead, it worked for me:
https://github.com/kaliiiiiiiiii/undetected-playwright-python

**Comment by damosull** [comment]
Any updates on this one?
