### ISSUE TITLE
[Feature]: get elements by given x, y

### ISSUE THREAD

**Issue by lenjoy** [microsoft/playwright#30176]
### 🚀 Feature Request

given the point (x, y) on the browser, return the elements (nested by layers) in that specific point.
similar as `Inspect` in debug tool.

### Motivation

With this feature, it will be able to know how the page is rendered on the browser, such as top, bottom, central, corners, etc.

There seems to be no alternative functions to achieve this.

**Comment by pavelfeldman** [comment]
Lacking example, motivation is not compelling either.
