### ISSUE TITLE
[Bug]: Debug using line number is not working

### ISSUE THREAD

**Issue by SamratJD** [microsoft/playwright#30180]
### Version

1.41.2

### Steps to reproduce

I've a file named UIBasicsTest.spec.js
And when I try to run the below command to open the debug mode, it throws an error
npx playwright test UIBasicsTest.spec.js:4

Error:
Error: No tests found.
Make sure that arguments are regular expressions matching test files.
You may need to escape symbols like "$" or "*" and quote the arguments.

### Expected behavior

I expect the debug functionality to work for specific lines as well just as mentioned in the official documentation.

### Actual behavior

Error:
Error: No tests found.
Make sure that arguments are regular expressions matching test files.
You may need to escape symbols like "$" or "*" and quote the arguments.

### Environment

```shell
System: Windows 10
@playwright/test: 1.41.2
```

**Comment by pavelfeldman** [comment]
This works for me, please follow the BUG template to file something we can reproduce locally.

**Comment by SamratJD** [comment]
@pavelfeldman can you please share the a sample test file and the corresponding command using line number and --debug. 
I've tried without using the line number in the command and it works fine.
It fails only when the line number is added.
