### ISSUE TITLE
[Bug]: Annotations from previous attempts not shown in HTML report

### ISSUE THREAD

**Issue by marshmn** [microsoft/playwright#30188]
### Version

1.42.1

### Steps to reproduce

If you have a test that has a dynamic annotation (one where the description changes on each test run) and then view the HTML report from a failed run with retries, only the annotation from the final run is shown.

1. Create a test that has a dynamic annotation
2. Make the test fail
3. Run the test with retries enabled

Minimal example using a timestamp for the annotation:

```typescript
test(
    "my test",
    {
        annotation: {
            type: "current-time",
            description: new Date().toString(),
        },
    },
    async ({ page }) => {
        await page.goto("/");
        await expect(page.getByText("MISSING TEXT")).toBeVisible();
    },
);
```

### Expected behavior

The HTML report should show annotations from each of the retries.

### Actual behavior

The HTML report shows only annotations captured during the final retry.

![Screenshot from 2024-03-31 09-48-38](https://github.com/microsoft/playwright/assets/4307033/6239009a-c8f4-4c3b-8192-9de0863bf086)

Perhaps the 'Annotations' block should be within the tabs for each attempts, instead of being above them?

### Environment

```shell
System:
  OS: Linux 5.11 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 11.87 GB / 31.00 GB
  Container: Yes
Binaries:
  Node: 20.11.1 - /usr/bin/node
  Yarn: 1.22.21 - /usr/bin/yarn
  npm: 10.2.4 - /usr/bin/npm
Languages:
  Bash: 5.1.16 - /usr/bin/bash
npmPackages:
  @playwright/test: 1.42.1 => 1.42.1
```

**Comment by dgozman** [comment]
@marshmn We do not expect annotations to change between runs, especially static annotations inside the test declaration. I'd recommend to use attachments instead - these are shown separately for each retry. Let me know whether that works for you.

**Comment by marshmn** [comment]
@dgozman: thanks for the response. I don't think that attachments are ideal, since I believe these would only be shown to me when the test fails (e.g. in the trace in CI)? Really I'd like to have access to this information for each run.

I've worked around it for now by using `test.step()` from within the fixture where I'm adding the annotation:
```typescript
test.step('my annotation: value', () => { //... });
```

At least this allows me to find and view it in the HTML report - but it does feel like a bit of a hack to me...

**Comment by dgozman** [comment]
>  I don't think that attachments are ideal, since I believe these would only be shown to me when the test fails (e.g. in the trace in CI)?

Attachments are available for all runs. You can see them in the html report at the bottom. So perhaps they would actually work for you?

<img width="1001" alt="Screenshot 2024-04-02 at 7 46 21 AM" src="https://github.com/microsoft/playwright/assets/9881434/95ed6f36-5a2e-4940-bf18-fa6a39896f53">

---

> At least this allows me to find and view it in the HTML report - but it does feel like a bit of a hack to me...

That's a clever workaround, but I agree it feels weird 😄

**Comment by marshmn** [comment]
Ah, my apologies - I'd not realised that attachments show up on each run in the HTML report. I've just tested it that way and it's working fine, so yes, that's a better workaround than what I'd done... so yeah, I can live with that.

Thanks for the suggestion.

**Comment by dgozman** [comment]
Given the workaround, I'll close this issue. If you still encounter problems, please file a new issue with a repro and we'll happily take a look.
