### ISSUE TITLE
[Bug]: waitForResponse is not merging URL when using predicate

### ISSUE THREAD

**Issue by msmith1114** [microsoft/playwright#30181]
### Version

1.42.1

### Steps to reproduce

When using `page.waitForResponse` with a predicate such as below:

```
const responsePromise = page.waitForResponse(response =>
      response.url() === 'https://some.url.com/settings/1000' && response.status() === 200
    );
```
It seems to be working just fine. However if I do this:

```
const responsePromise = page.waitForResponse(response =>
      response.url() === '/settings/1000' && response.status() === 200
    );
```

and my `baseUrl` is set to: `https://some.url.com/` It will not work. Maybe this is intended? Since breaking out the `response.url` is expecting the entire url? FWIW It does work if I do `response.url() === (baseUrl + '/settings/1000')` for example.

### Expected behavior

I would expect that the `response.url` should be merged similar to if you use it without a predicate

### Actual behavior

`response.url` does not merge baseUrl when used with a predicate

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i7-12800HX
    Memory: 20.17 GB / 31.70 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.5 - ~\AppData\Roaming\npm\pnpm.CMD
  npmPackages:
    @playwright/test: ^1.42.1 => 1.42.1
```

**Comment by pavelfeldman** [comment]
`response.url()` returns a string, it will always contain absolute URL - it can't contain a different value based on the baseURL setting - everything will fall apart then.
