### ISSUE TITLE
[Docs]: Add Github Topics "end-to-end-testing" to improve Github "SEO"

### ISSUE THREAD

**Issue by chimurai** [microsoft/playwright#30187]
### Page(s)

Improve Playwright visibility on https://github.com/explore page.

Currently Playwright is not listed:

<img width="650" alt="image" src="https://github.com/microsoft/playwright/assets/655241/3d371f7d-1cae-4d28-86b8-0abea45332e2">

Following the link will lead to this page:
https://github.com/topics/end-to-end-testing

### Description

Suggestion: Add `end-to-end-testing` topic to improve Github "SEO"

<img width="335" alt="image" src="https://github.com/microsoft/playwright/assets/655241/228f56a8-7242-45b6-a69d-26334d6fa87d">

**Comment by mxschmitt** [comment]
done!
