### ISSUE TITLE
[Bug]: execution time for custom fixtures not properly shown in UI mode

### ISSUE THREAD

**Issue by cgutierrezpa** [microsoft/playwright#30197]
### Version

1.42.1

### Steps to reproduce

I have the following fixtures configured for my Playwright project:

```javascript
import {
  apiTest,
  auth0Test,
  companiesTest,
  domTest,
  integrationsTest,
  sessionTest,
  usersTest,
} from '@monorepo/playwright/fixtures';

export * from '@playwright/test';
export const test = mergeTests(
  extendedTest,
  auth0Test,
  domTest,
  sessionTest,
  apiTest,
  usersTest,
  companiesTest,
  integrationsTest
);
```

Each fixture has a different purpose, which can be either perform a request to our server API, and external API like Auth0 or to perform an insert in the app DB via direct connection. Here is an example of the implementations of one of those fixtures:

```javascript
import { PlaywrightExtendedTestArgs } from '@monorepo/playwright/types';
import { mergeTests } from '@playwright/test';
import { CompanyType, Prisma } from '@prisma/client';
import { APIFixture, apiTest } from './api';
import { StateFixture, stateTest } from './state';
import { UsersFixture, usersTest } from './users';
import {
  createCompany,
  CreateCompanyArgs,
} from './utils/db/create-company-data';

type APICreateCompanyInput = {
  name: string;
  country?: string;
  website?: string;
  companyTypes?: CompanyType[];
};

export class CompaniesFixture {
  private readonly state: StateFixture;
  private readonly api: APIFixture;
  private readonly users: UsersFixture;

  constructor({
    state,
    api,
    users,
  }: Pick<MergedTestArgs, 'state' | 'api' | 'users'>) {
    this.state = state;
    this.users = users;
    this.api = api;
  }

  async apiCreateCompany({
    name,
    country = 'USA',
    website,
    companyTypes,
  }: APICreateCompanyInput) {
    const response = await this.api.requestToAuthenticatedAPI({
      path: 'companies/logged-user',
      method: 'POST',
      data: {
        name,
        website: website ?? `${name}.com`,
        annualRecurringRevenue: 'bucket-1',
        state: 'AZ',
        country,
        productType: 'financing',
        companyTypes,
      },
    });
    const company = await response.json();
    await this.state.setCompanyId(company.id);

    await this.users.apiUpdateUser({
      firstName: name,
      lastName: name,
    });
    return company;
  }

  async createCompany(company: CreateCompanyArgs['company']) {
    return createCompany(null, { company });
  }
}

const mergedTest = mergeTests(stateTest, apiTest, usersTest);

type MergedTestArgs = PlaywrightExtendedTestArgs<typeof mergedTest>;

export const companiesTest = mergedTest.extend<{ companies: CompaniesFixture }>(
  {
    // We are forced to do object destructuring here because of https://github.com/microsoft/playwright/issues/14590#issuecomment-1911734641
    companies: async ({ state, api, users }, use) =>
      use(new CompaniesFixture({ state, api, users })),
  }
);
```

And here would be an example of the `before` hook:
```
    test.beforeEach(async ({ api, companies, integrations }) => {
      companyName = `cypress-${new Date().getTime()}`;
      await api.authenticateRequests({
        username: usernameExisting,
        password,
      });
      await companies.apiCreateCompany({ name: companyName });
      await integrations.skipIntegrations();
    });
```

### Expected behavior

Ideally we should see the elapsed time in each of the fixture steps

### Actual behavior

As you can see in the image below, you can see the total elapsed time for a hook (in this case is a `beforeAll` hook), but when you unfold the details of each step it shows `0 ms` for every custom fixture function that is executed, but then it shows the actual calls to the built-in fixtures sequentially. 

<img width="320" alt="image" src="https://github.com/microsoft/playwright/assets/20757456/6ab17f62-0e01-4453-b2a1-bf17d24b23a2">

### Additional context

Additionally, for those fixtures that perform actions that do not use built-in fixtures under the hood, e.g: an insert over the DB with direct connection, then it won't show any execution time information whatsoever. Is there a decorator or wrapper we can use so that we can know both the function name of the fixture that we are using and the time it took to execute such fixture?

<img width="311" alt="image" src="https://github.com/microsoft/playwright/assets/20757456/7e08fd9a-4165-414f-845c-b8f582197fee">

Something like this:
```
fixture: api.authenticateRequests .................. 1.2s

fixture: companies.apiCreateCompany .......... 2.2s

fixture: integrations.skipIntegrations ............. 800ms
```

Instead of:
```
fixture: api ..................................................... 0ms

fixture: companies ......................................... 0ms

fixture: integrations ....................................... 0ms
```

### Environment

```shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 205.94 MB / 16.00 GB
  Binaries:
    Node: 20.8.0 - ~/.asdf/installs/nodejs/20.8.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/20.8.0/.npm/bin/yarn
    npm: 10.1.0 - ~/.asdf/plugins/nodejs/shims/npm
  IDEs:
    VSCode: 1.87.2 - /Applications/Visual Studio Code.app/Contents/Resources/app/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.42.1 => 1.42.1
```

**Comment by dgozman** [comment]
@cgutierrezpa If I understand the issue correctly, you'd expect calls like `apiResponse.json` to be inside a fixture that made the call? If so, we would love to fix it, but we need a repro that we can run locally. Unfortunately, your snippet cannot be run as is, so please share a repro that we can actually run.

Alternatively, give it a try with a [canary release](https://playwright.dev/docs/canary-releases) - perhaps it's already fixed?

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
