### ISSUE TITLE
Codegen generates locator that violates strict mode 

### ISSUE THREAD

**Issue by ApurvaMisra** [microsoft/playwright#30191]
### Version

1.42.0

### Steps to reproduce

1. Find the generated test in repository https://github.com/ApurvaMisra/playwright-issue/tree/main
2. Find the requirements

### Expected behavior

I expect it to find unique locators

### Actual behavior

The test generated by codegen gives the below error, when I used _first_ with the locator, it went into a loop, opening the dropdown and scrolling but never completing the steps.

`playwright._impl._errors.Error: Error: strict mode violation: locator("#client-table-1078866").get_by_text("Applied") resolved to 2 elements:
    1) <span class="multiselect__single">Applied</span> aka locator("#client-table-1078866").get_by_text("Applied").first
    2) <span>Applied</span> aka locator("#client-table-1078866 ul").get_by_text("Applied")`

### Additional context

`    await page.locator(".status-cell > .multiselect-container > .multiselect > .multiselect__select").first.click()
    await page.locator("#client-table-1078866").get_by_text("Applied").first.click()`

### Environment

```shell
Playwright Version: 1.42.0
Operating System: Mac
Browser: Chromium (but likely affects others as well)
Language: Python
```

**Comment by dgozman** [comment]
@ApurvaMisra We need the steps to reproduce the issue. In this case, please share the page url and the actions you took while recording with a Codegen.

**Comment by ApurvaMisra** [comment]
@dgozman It is an internal application, I can send you the login details and pageurl in a personal dm if that works?

**Comment by dgozman** [comment]
@ApurvaMisra We need a public repro, sorry.

**Comment by ApurvaMisra** [comment]
Hmm, let me see if I can reproduce it in a public repo.

**Comment by mxschmitt** [comment]
I'll close it for not as part of the triage process. Don't hesitate to re-file with a new repro.
