### ISSUE TITLE
[Feature]: How to avoid the browser reloading ?

### ISSUE THREAD

**Issue by c0sc0s** [microsoft/playwright#30195]
### 🚀 Feature Request

During my development process, I've encountered an efficiency issue. Every time I make changes to the code and expect a hot reload, Playwright seems to restart the browser instance and re-execute the entire test workflow from the beginning. This significantly slows down my development cycle. I'm wondering if there's any way to avoid this behavior, for instance, 

### Example

null

### Motivation

null

**Comment by dgozman** [comment]
This issue tracker is reserved for bug reports and feature requests.

For anything else, such as questions or getting help, please see:
- [The Playwright documentation](https://playwright.dev/)
- [Our Discord server](https://aka.ms/playwright/discord)
