### ISSUE TITLE
[Feature]: cencellation of waiting for element state or sending options for not write oporetions to trace records

### ISSUE THREAD

**Issue by avidor2507** [microsoft/playwright#30193]
### 🚀 Feature Request

some way to send cencelation token for assertion or element state waiting
other option is to send option to not write operations to records like click or get text

### Example

send cencellation token to a function
or send with operation options object bool for not write to record

### Motivation

In my project I want to wait for a component state to be as expected.
the component have couple of elements inside and I want to wait for all of them to be at a specific state at the same time.
the state is not consistent and the elements can changed (for example one of the buton is enabled but can be disabled untill the state is as expected and return to be enabled agian at the end.
if I wait for that button to be enabled the wait is finished before the other elements finished to check and in the end when all the other finished the test is passed becouse of that even if the button is now disabled agian.

I have 2 options here, or to make a wjile loop that every millisecond i fetch the state of the button and compare to the final state that i expect (this will make every fetch to be write in the record and this is not necesery for me there) or to create a logic to wait for the button to be enabled and when passed to check if disabled with the remain timeout, and when I see that all of them passed to stop the disabled wait with cencellation token or other option (prefered option)

**Comment by dgozman** [comment]
@avidor2507 I don't think we'll be able to make a nice API to help with this. If you need a guarantee that all buttons are in the same state simultaneously, and you cannot tolerate any race conditions, you'll have to check them synchronously in the page by using `page.evaluate()`.

However, depending on the behavior of your page, perhaps you can just expect all the conditions once, and then all the conditions again for the second time? This way you'll cover elements that went enabled and then back to disabled. However, this will not cover elements randomly changing their state multiple times.

**Comment by dgozman** [comment]
Closing as per above. If you encounter other problems, please file a new issue by filling the "Bug Report" template.
