### ISSUE TITLE
[Bug]: "PlaywrightException: Event" when taking screenshot and generating PDF when deployed on Ubuntu 20.04 LTS.

### ISSUE THREAD

**Issue by LapinskasL** [microsoft/playwright#30201]
### Version

1.42.0

### Steps to reproduce

Will add minimal reproduction once I finish making it.

1. Create an .NET 8 MVC app with Playwright that downloads a PDF of a page.
2. Run the app in Ubuntu 22.04.
3. Install any dependencies if you get an error.
4. Run the app again.
5. Try to download the PDF file.
6. You should get an exception 'Microsoft.Playwright.PlaywrightException: Event'.

### Expected behavior

The PDF file should download.

### Actual behavior

An exception is thrown `Microsoft.Playwright.PlaywrightException: Event`.

### Additional context

The PDF file does download just fine on a Windows machine.

### Environment

```shell
System:
	OS: Linux 6.5 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
	CPU: (2) x64 Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
	Memory: 205.00 MB / 427.27 MB
	Container: Yes
Binaries:
	Node: 12.22.9 - /usr/bin/node
	npm: 8.5.1 - /usr/bin/npm
Languages:
	Bash: 5.1.16 - /usr/bin/bash
```

**Comment by LapinskasL** [comment]
The issue was with how I added the CSS tags. I used the `Url` parameter of `PageAddStyleTagOptions` which worked on Windows but not Ubuntu. Switching to the Path property that starts with `wwwroot/` solved it. Works both on Windows and Ubuntu.

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro.
