### ISSUE TITLE
[Feature]: Running multiple test files through CLI

### ISSUE THREAD

**Issue by 403-html** [microsoft/playwright#30209]
### 🚀 Feature Request

I'd love to have ability for passing to the Playwright multiple test files and running them. Not only test directories. For now it's not possible, and only is ran the first one from list (if test file is passed).

### Example

It would be nice if command like:

`yarn playwright test path/to/test1.ts path/to/nested/test2.ts --shard 1/2` 

or similar (for example with commas?), would run tests `path/to/test1.ts` and `path/to/nested/test2.ts` in one go

### Motivation

Honestly? Needed for project to reduce CI time, by rerunning just flaky tests gathered after test run. I tried to find answers on your [Discord](https://discord.com/channels/807756831384403968/1217103520067752027/1217103520067752027), and [Stackoverflow](https://stackoverflow.com/questions/78152316/how-to-pass-multiple-file-to-be-ran-in-playwright), but didn't find anything I could stick up with.

**Comment by dgozman** [comment]
@403-html You can already pass multiple paths to the CLI, and Playwright will interpret them as a filter. Most likely, passing `--shard 1/2` only runs half of the tests though, so you'd think it only runs the first file. I'd recommend not passing `--shard` in this case. See documentation to [find out more about the CLI](https://playwright.dev/docs/test-cli#reference).

**Comment by 403-html** [comment]
Hi! Thanks for answer. Do you mean that part? 

![](https://github.com/microsoft/playwright/assets/57900160/1d2c74fb-548b-4ed3-a649-7cebcc6982f5)

afaik it's only for directories, and doesn't work for specific files.  
  
About shards, I also tried that, to remove it (reference in Discord), but it picked up not all files, but this time the last one in line :thinking:.

**Comment by dgozman** [comment]
> afaik it's only for directories, and doesn't work for specific files.

Nope, it works for files as well.

> About shards, I also tried that, to remove it (reference in Discord), but it picked up not all files, but this time the last one in line

That sounds like a bug. Could you please provide a full repro that we can run locally? Ideally, file a new issue by filling in the "Bug Report" template. Unfortunately, we won't be able to address the bug without a repro.

**Comment by 403-html** [comment]
I can try to make reproduction repo for it – and I understand that, so I'm closing the issue, and if I'll make one, I'll do a follow-up bug report.
