### ISSUE TITLE
[Feature]: Serial Mode , capture accessibility results for each test() which executes on different pages

### ISSUE THREAD

**Issue by mallikabhat99** [microsoft/playwright#30219]
### 🚀 Feature Request

[Feature]: Serial Mode , we would love to have the capability to capture accessibility results for each test() which executes on different pages

### Example

We have a requirement of executing tests serially one after other
Each test() corresponding to a page/screen of the application has validations for that particular screen , we are wanting to have accessibility check as well 

### Motivation

Accessibility results are very well captured in parallel mode , where as serial mode is not supported
Kindly let me know if there is already a way to do this

**Comment by dgozman** [comment]
@mallikabhat99 Did you follow the [accessibility testing guide](https://playwright.dev/docs/accessibility-testing)? Could you please share a repro that we can run locally that exhibits the issue? Otherwise, we are unlikely to be able to address it.

**Comment by mallikabhat99** [comment]
[dgozman](https://github.com/dgozman) Yes, i did follow 
all the test methods have {page} as param like  -- >
test('should not have any automatically detectable accessibility issues', async ({ page }) => {

where as when we configure a test file to run in serial mode which looks like below
test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();
});

test.afterAll(async () => {
    await page.close();
});

test.describe('Sim E2E', () => {
    test('should pick the bottles primary stain, mordant', async () => {

all the test methods do not have {page} as param
AxeBuilder({ page }) needs to have {page} param , is there a way to get this working in serial mode

**Comment by dgozman** [comment]
@mallikabhat99 Thanks, I see what you mean. In serial mode, don't write `{ page }` argument for the test, but still pass `{ page }` to the `AxeBuilder`. Here is an example, let me know whether it helps:

```ts
import { test, expect, Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

let page: Page;

test.beforeAll(async ({ browser }) => {
  page = await browser.newPage();
});

test.afterAll(async () => {
  await page.close();
});

test('should not have any automatically detectable accessibility issues', async () => {
  await page.goto('https://your-site.com/');
  const accessibilityScanResults = await new AxeBuilder({ page }).analyze();
  expect(accessibilityScanResults.violations).toEqual([]);
});
```

**Comment by mallikabhat99** [comment]
@dgozman getting issue with browser context each time in the above way which you mentioned.

Below link has the sample test which i want to exec in serial mode.. 1st test() works fine , 2nd one opens in new browser tab as i'm passing {page} param to it.
https://github.com/mallikabhat99/playwrigh-mb/blob/main/tests/photosynthesis.spec.ts

Kindly check and let me know if there is any better way/support accessibility testing in serial mode

**Comment by dgozman** [comment]
@mallikabhat99 In your test, I don't see `beforeAll` and `afterAll` from the [reusing page guide](https://playwright.dev/docs/test-retries#reuse-single-page-between-tests). You should follow that guide, and pass the local variable page to the `AxeBuilder`, and everything should work.

Let me close this issue, since there is no action item for Playwright here. If you have more questions or need help, please see:
- [The Playwright documentation](https://playwright.dev/)
- [Our Discord server](https://aka.ms/playwright/discord)
