### ISSUE TITLE
[Feature]: BiDi - Playwright with Webdriver BiDi protocol

### ISSUE THREAD

**Issue by kiruba07** [microsoft/playwright#30237]
### 🚀 Feature Request

Hi Team,

Currently, Playwright use the CDP protocol to connect and interact with Chrome and Edge browsers.

But, as per the new w3c standards, most of the browsers have now enabled the Webdriver BiDi protocol to allow the automation tools to connect and interact with browsers.

So,  Is the any plan in the Playwright pipeline to enable Webdriver BiDi protocol through Playwright ?

This clarity will help most of the organisations to consider as part of the tooling strategies.

### Motivation

To align with w3c new protocol, and helps the organisations to consider this as part of their tooling strategies.

**Comment by pavelfeldman** [comment]
We consider the communication protocol that Playwright uses to be its implementation detail. If you have a feature request to Playwright, please describe it and we will be happy to consider implementing it.

**Comment by marcosvfranco** [comment]
> We consider the communication protocol that Playwright uses to be its implementation detail. If you have a feature request to Playwright, please describe it and we will be happy to consider implementing it.

@pavelfeldman sorry but your reply is not clear and not answering properly what was asked, can you be more direct and clear?

**Comment by chenmichaelc** [comment]
@pavelfeldman For context, it looks like Firefox is aiming to deprecate Chrome DevTools Protocol support by the end of 2024: https://fxdx.dev/deprecating-cdp-support-in-firefox-embracing-the-future-with-webdriver-bidi/

If there's a business-facing feature request to define, it may be to provide future-facing continuation of the ability for Playwright to execute tests in Firefox.

(If there is some other way to achieve this goal without implementing WebDriver BiDi in Playwright, that may be acceptable too. However, I wasn't able to find any official documentation about this myself.)

**Comment by marcosvfranco** [comment]
@chenmichaelc That's the point, Firefox will be the first of all browsers that are making this switch, but it's possible that all of them will change to the new protocol (I have questions about if Chrome will also because they created the CDP, but still, they are supporting BiDi and may change their protocol in the future)

**Comment by MindaugasMateika** [comment]
As far as I know Playwright does not use CDP for Firefox and instead uses patched Firefox and Juggler so this change from Firefox might not have an impact at all. Other than that, Pavel is also creator of CDP and I'm sure whole team is on top of newest developments in browser engineering.

**Comment by marcosvfranco** [comment]
@MindaugasMateika I'm sure Pavels is a top engineer, I just reopened the thread because the response he gave was not 100% clear and the news from Firefox are newer them the last reply he gave :)

**Comment by chenmichaelc** [comment]
>  I'm sure Pavels is a top engineer, I just reopened the thread because the response he gave was not 100% clear and the news from Firefox are newer them the last reply he gave :)

Same, and no offense intended from my part. I just wanted to try to keep the info here as self-contained as possible to prevent misunderstandings in the conversation.

Also, thank you to @MindaugasMateika for the additional info!

**Comment by khmyznikov** [comment]
Patched browsers binaries is not cool thing. I see folks drops playwright because of no BiDi support.

**Comment by syradar** [comment]
Yeah supporting BiDi seems much better than patching binaries.

**Comment by MindaugasMateika** [comment]
> Yeah supporting BiDi seems much better than patching binaries.

Patching binaries > losing some Playwright features

**Comment by bharathmuppa** [comment]
I do vouch for the people who wants to know the future roadmap of playwright whether it is going in direction of webdriver BiDi or keep using CDP or atleast a dedicated page for comparison or rational reasoning on why it is not .

As it is being adopted at bigger organization it is very difficult to propose something that is as cool as playwright without these details.

**Comment by amardeep2006** [comment]
Looks like BiDi support is under evaluation. A great news indeed as I seen multiple pull requests https://github.com/microsoft/playwright/pulls?q=bidi

**Comment by rmacklin** [comment]
Also want to add a link to the issue that tracks current BiDi support (for anyone that ends up on this thread first):
- https://github.com/microsoft/playwright/issues/32577
