### ISSUE TITLE
[Docs]: Add a note to the Docker page concerning special characters

### ISSUE THREAD

**Issue by HardworkingSlacker** [microsoft/playwright#30245]
### Page(s)

https://playwright.dev/docs/docker
https://playwright.dev/docs/docker#run-the-image

### Description

When simply running the provided playwright image, the Linux `locale` will be set to `POSIX`.
This will cause issues with certain special characters (like §), Umlauts (ä,ö,ü) and accented characters (è,â,ç).
You won't be able to write them out in the command line and when copying files containing such characters in their filenames or contents, they will be escaped with number codes or blanks which is a problem if you need them within your tests..
My solution to this was to create a Dockerfile and adding `ENV LANG=C.UTF-8` so that these characters can be used and displayed properly.

The problem and a possible solution should be noted at the appropriate place in the documentation.

Reproduction:
Run the latest image (currently v1.42.1).
Then, try to type `touch Bei§piel.txt` - it won't work properly for the §-character
You can also try to create that file on your host system and copy it to the container.
When you perform ls in the container, it should look like this: `'Bei'$'\302\247''piel.txt'`

**Comment by mxschmitt** [comment]
Similar to https://github.com/microsoft/playwright/issues/28642

**Comment by HardworkingSlacker** [comment]
Yes, the Bug was also reported in this issue: #22576 
The underlying problem is rather obscure and requires a lot of searching before figuring it out.
Simply noting it in the documentation could spare others a few headaches.
