### ISSUE TITLE
[Bug]: experimental-ct-core breaking change - unable to programatically run bin via  cli.js since v1.42

### ISSUE THREAD

**Issue by Hotell** [microsoft/playwright#30241]
### Version

1.42.1

### Steps to reproduce

- clone and checkout https://github.com/Hotell/fluentui-contrib/tree/deps/playwright-bump
- `yarn`
- `yarn nx run react-draggable-dialog:component-test --skip-nx-cache`

### Expected behavior

`cli` public api was removed in this PR https://github.com/microsoft/playwright/pull/29131/files#diff-10c9d090eb66259c24ce7584a9600afe7368ae206b88922c4ce890ca90919b00L22

This api was the only way how to execute playwright for component test programatically https://github.com/microsoft/fluentui-contrib/blob/main/packages/nx-plugin/src/executors/playwright/executor.ts#L117

This API is correctly present within `@playwright/test` package https://unpkg.com/browse/@playwright/test@1.41.2/package.json

This is a breaking change which ideally should be reverted or officially document how to run component test binary programatically and unify it with playwright/test if possible.

### Actual behavior

`./cli` API endpoint was removed from `experimental-ct-core` = breaking change

### Environment

```shell
System:
    OS: macOS 14.4.1
    Memory: 81.77 MB / 64.00 GB
  Binaries:
    Node: 18.19.1 - /opt/homebrew/opt/node@18/bin/node
    Yarn: 1.23.34 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - /opt/homebrew/opt/node@18/bin/npm
    bun: 1.0.2 - ~/.bun/bin/bun
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by dgozman** [comment]
@Hotell Playwright does not consider this to be an API. In fact, the whole `@playwright/experimental-ct-core` package is an implementation detail that you should not rely upon. All the packages intended to be used directly include a cli entrypoint, for example `@playwright/test` or `@playwright/experimental-ct-react`. Note that the exact cli entrypoint file may be changed at any moment, so it's better to read it from the `package.json`, similarly to what `npm` does. Let me know whether that helps.

**Comment by dgozman** [comment]
Closing as per above. If you still encounter problems, please file a new issue by filling in the "Bug Report" template and link to this one.
