### ISSUE TITLE
[Feature]: Button to approve or disapprove changes to screenshots in visual regression tests 

### ISSUE THREAD

**Issue by zinaelnahel89** [microsoft/playwright#30244]
### 🚀 Feature Request

We need a button to approve/disapprove changes that occur to screenshots when the visual regression tests fail. Also a way to not save the screenshots to the repo but rather to AWS S3 bucket or so. 

### Motivation

The playwright visual regression framework is not fully automated yet and needs some new features to decrease the amount of manual work when running and maintaining the tests

**Comment by dgozman** [comment]
See #28415, #28005, #24310 and #14883.

**Comment by zinaelnahel89** [comment]
@dogzman does this mean it was implemented already ?
