### ISSUE TITLE
[Feature]: Add the tags information into the JUnit report

### ISSUE THREAD

**Issue by TheCPAKA** [microsoft/playwright#30256]
### 🚀 Feature Request

Add the tags information into the JUnit report

### Example

Tests below have tags "@defect:product" and "@defect:framework". 
Test reporter is JUnit

```
import { test, expect } from '@playwright/test';

test.describe("xfail: ", () => {
  test("Xfail product issue with tag", {
    tag: ["@defect:product"],
    annotation: [{ type: "fail", description: "https://some-link.net/browse/QA-1" }]
  }, () => {
    expect(true).toBeFalsy();
  });

  test("Xfail framework issue with tag", {
    tag: ["@defect:framework"],
    annotation: [{ type: "fail", description: "https://some-link.net/browse/QA-2" }]
  }, () => {
    expect(true).toBeFalsy();
  });

});
```

XML output has now info about tags:
```<testsuites id="" name="" tests="2" failures="0" skipped="0" errors="0" time="0.20235399999999998">
<testsuite name="example.spec.ts" timestamp="2024-04-04T17:48:01.365Z" hostname="chromium" tests="2" failures="0" skipped="0" time="0.02" errors="0">
<testcase name="xfail:  › Xfail product issue with tag" classname="example.spec.ts" time="0.01">
<properties>
<property name="fail" value="https://some-link.net/browse/QA-1">
</property>
</properties>
</testcase>
<testcase name="xfail:  › Xfail framework issue with tag" classname="example.spec.ts" time="0.01">
<properties>
<property name="fail" value="https://some-link.net/browse/QA-2">
</property>
</properties>
</testcase>
</testsuite>
</testsuites>```

### Motivation

The main idea is to modify the appearance of xfailed tests in the final report based on the types of issues: @defect:product or @defect:framework. Previously, we achieved this by using tags in test titles and parsing the final JUnit report.

However, in the newest version of Playwright, tags can now be moved to a separate section, but this information is not displayed in the JUnit result.xml.

Could you please integrate the tags information into the JUnit report?

**Comment by dgozman** [comment]
@TheCPAKA How do you intend to consume the tags from the produced xml? There are many dialects of junit xml format, so we have to be careful and understand how it's going to be used.

**Comment by TheCPAKA** [comment]
@dgozman Let me explain our workflow:

1. A parent job is created on Jenkins (running on Kubernetes).
2. This job gathers a list of all tests to be executed based on the project and using grep.
3. Each test runs on a separate child pod.
4. Each test generates a default JUnitResult.xml.
5. Before sending the XML report to TestMo, it is parsed to add correct links to test artifacts (such as traces and videos) and to apply xfail filtering.
6. Each report sent to TestMo

Previously, we utilized tags in test titles. However, this approach proved challenging with [TestMo](https://www.testmo.com/) because it uses test titles as linking attributes. Altering test titles, such as adding or removing tags, caused issues with linking test results. We filtered xfailed tests based on tags from test titles. However, the latest Playwright version has no information about tags in the JUnit results.
This is a code that parses xml
```
const fs = require("fs");
const xml2js = require("xml2js");
const xpath = require("xml2js-xpath");
const regexQuery = /\[\[ATTACHMENT\|(.*?)\]\]/g;
const testResultXmlPath = "test-results/jUnitResults.xml";
const gcpUrl =
  `https://storage.cloud.google.com/${process.env.TESTMO_SOURCE}/` +
  `${process.env.JOB_NAME}/build-${process.env.BUILD_NUMBER}/${process.env.TEST_TITLE}/`;

fs.readFile(testResultXmlPath, "utf-8", async (err, contents) => {
  if (err) {
    console.log(err);
    return;
  }

  // Changes links to test artifacts in JUnitReport.xml
  const xmlWithCorrectLinks = contents.replace(
    regexQuery,
    (match, attachmentPath) => `[[ATTACHMENT|${gcpUrl}${attachmentPath}]]`,
  );

  // Mark failed tests with annotation test.fail() as failed in testmo results.
  xml2js.parseString(xmlWithCorrectLinks, async (parseErr, result) => {
    if (parseErr) {
      console.error("Failed parsing XML:", parseErr);
      return;
    }
    if (process.env.PRODUCT_TESTING === "true") {
      const matches = xpath.find(result, "//testcase");

      for (const testCase of matches) {
        if (testCase.properties) {
          const tag = testCase.properties[0].property;
          if (tag.some((property) => property.$.name === "fail") && !testCase.failure) {
            const failureMessage = tag[0].$.value;
            const failureAttributes = {
              $: {
                message: "Test failed",
                type: "FAILURE",
              },
              _: failureMessage ? failureMessage : "Test failed, please recheck and add jira ticket",
            };
            testCase.failure = [failureAttributes];
          }
        }
      }
    }

    const builder = new xml2js.Builder({
      headless: true,
      renderOpts: { pretty: true },
    });
    const finalXml = builder.buildObject(result);

    fs.writeFile(testResultXmlPath, finalXml, (err) => {
      if (err) {
        console.log(err);
      } else {
        console.log("New XML file with correct links is saved");
      }
    });
  });
});
```

Essentially, there are no specific requirements on how tags should be processed into XML. We will parse them regardless =)

**Comment by dgozman** [comment]
@TheCPAKA Thank you for the explanation. We'll see about the optimal way to expose the tags. As a workaround for now, I'd recommend copying the [junit reporter](https://github.com/microsoft/playwright/blob/main/packages/playwright/src/reporters/junit.ts) and using a modified version of it as a custom reporter. Perhaps it would be even easier if you merge it with the post-processor right away.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
