### ISSUE TITLE
[Bug]: Test steps show the decorator's path & line instead of the decorated function

### ISSUE THREAD

**Issue by bdcarr** [microsoft/playwright#30259]
### Version

1.40.1 (but I checked the release notes and didn't see anything about this)

### Steps to reproduce

1. Create a decorator function [as suggested in the docs](https://playwright.dev/docs/api/class-test#test-step)
2. Write a function and and tag it with the decorator
3. Use the function in a Playwright test
4. Check the HTML report

### Expected behavior

In the Test Steps section of the report, you see the location of the decorated function, since that's where you'd want to look for the test code.

### Actual behavior

The test steps show the location of the decorator function, which in my case is tucked away in a helper module:

![image](https://github.com/microsoft/playwright/assets/1940488/dd0b0c82-131b-4791-800e-52de5a2feb29)

The bottom row is a test step defined by calling test.step() explicitly, rather than using the decorator.

### Additional context

You can still get the actual locations by expanding the step and looking at the individual steps, so it's not too bad.

### Environment

```shell
System:
    OS: macOS 14.4
    CPU: (12) arm64 Apple M2 Pro
    Memory: 78.81 MB / 32.00 GB
  Binaries:
    Node: 16.20.2 - ~/Library/Caches/fnm_multishells/2475_1712029196581/bin/node
    npm: 8.19.4 - ~/Library/Caches/fnm_multishells/2475_1712029196581/bin/npm
  IDEs:
    VSCode: 1.88.0 - /usr/local/bin/code
  Languages:
    Bash: 5.2.26 - /opt/homebrew/bin/bash
  npmPackages:
    @playwright/test: ^1.40.1 => 1.40.1
```

**Comment by dgozman** [comment]
@bdcarr Look at the "Boxing" section in the same doc - by passing the `box: true` option you'll see the location of the callsite.

```ts
function boxedStep(target: Function, context: ClassMethodDecoratorContext) {
  return function replacementMethod(...args: any) {
    const name = this.constructor.name + '.' + (context.name as string);
    return test.step(name, async () => {
      return await target.call(this, ...args);
    }, { box: true });  // Note the "box" option here.
  };
}
```

Let me know whether this helps.

**Comment by bdcarr** [comment]
Thanks @dgozman, that has solved my issue. But it doesn't seem to match the behaviour described in the documentation for `box: true`. Unless I'm totally misreading this, the docs say that option controls whether the code preview in the Error section shows you the exact call that failed, or the boxed step:

![image](https://github.com/microsoft/playwright/assets/1940488/980bbb1e-6349-48d6-9388-d4599508b8c2)

When I set `box: true`, the code preview still shows the exact call that failed, but the Test Steps now show the exact call line instead of the boxed step line.

**Comment by mxschmitt** [comment]
I tried to reproduce, but was not able to. When I execute the following, I get the following code preview, which is the boxed version:

```ts
import { test, Page } from '@playwright/test';

function boxedStep(target: Function, context: ClassMethodDecoratorContext) {
  return function replacementMethod(...args: any) {
    const name = this.constructor.name + '.' + (context.name as string);
    return test.step(name, async () => {
      return await target.call(this, ...args);
    }, { box: true });  // Note the "box" option here.
  };
}

class LoginPage {
  constructor(readonly page: Page) {}

  @boxedStep
  async login() {
   throw new Error("foo")
  }
}

test('example', async ({ page }) => {
  const loginPage = new LoginPage(page);
  await loginPage.login();  // <-- Error will be reported on this line.
});

```

<img width="1132" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/42b47e98-cd7d-4574-a56d-a249825729ad">

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it still doesn't work.
