### ISSUE TITLE
[internal] some page-click tests are flaky on Firefox

### ISSUE THREAD

**Issue by dgozman** [microsoft/playwright#30255]
Dashboard links:
- [`page/page-click.spec.ts:848 - should not hang when frame is detached`](https://devops.playwright.dev/flakiness.html#branch=release-1.43&show_flaky=true&test_parameter_filters=%5B%5B%22platform%22%2C%5B%5B%22Darwin+14.3+arm64%22%2C%22exclude%22%5D%2C%5B%22Darwin+14.4+arm64%22%2C%22exclude%22%5D%2C%5B%22Darwin+14.2+arm64%22%2C%22exclude%22%5D%2C%5B%22Darwin+13.6+arm64%22%2C%22exclude%22%5D%5D%5D%5D)
- [`page/elementhandle-wait-for-element-state.spec.ts:117 - should wait for stable position`](https://devops.playwright.dev/flakiness.html#branch=release-1.43&show_flaky=true&test_parameter_filters=%5B%5B%22platform%22%2C%5B%5B%22Darwin+14.3+arm64%22%2C%22exclude%22%5D%2C%5B%22Darwin+14.4+arm64%22%2C%22exclude%22%5D%2C%5B%22Darwin+14.2+arm64%22%2C%22exclude%22%5D%2C%5B%22Darwin+13.6+arm64%22%2C%22exclude%22%5D%5D%5D%5D).

**Comment by aslushnikov** [comment]
The `page/page-click.spec.ts:848 - should not hang when frame is detached` has been the same flaky as a year before:
https://devops.playwright.dev/flakiness.html#test_parameter_filters=%5B%5B%22browserName%22%2C%5B%5B%22firefox%22%2C%22include%22%5D%5D%5D%5D&timestamp=1680418740000

Same for the other one: https://devops.playwright.dev/flakiness.html#branch=release-1.43&show_flaky=true&test_parameter_filters=%5B%5B%22platform%22%2C%5B%5B%22Darwin+14.3+arm64%22%2C%22exclude%22%5D%2C%5B%22Darwin+14.4+arm64%22%2C%22exclude%22%5D%2C%5B%22Darwin+14.2+arm64%22%2C%22exclude%22%5D%2C%5B%22Darwin+13.6+arm64%22%2C%22exclude%22%5D%5D%5D%2C%5B%22browserName%22%2C%5B%5B%22firefox%22%2C%22include%22%5D%5D%5D%5D&timestamp=1680418740000

So at the very least, these are not regressions.
