### ISSUE TITLE
[Feature]: expose Frame Ids

### ISSUE THREAD

**Issue by himat** [microsoft/playwright#30261]
### 🚀 Feature Request

Why does playwright not expose a unique frame ID on the Frame object?

There is a unique ID for every Frame that is exposed in the CDP 
- https://chromedevtools.github.io/devtools-protocol/tot/Page/#type-Frame
- https://chromedevtools.github.io/devtools-protocol/tot/Page/#type-FrameId

So why does Playwright not expose this?
I need a way to distinguish frames and track them across time, so using just the `.name()` property is not sufficient since two frames could have the same name, and the names can change over time. 

Puppeteer at least has an internal variable _id that you can use there too ([source](https://github.com/puppeteer/puppeteer/issues/2368))

Electron also exposes the frame ID

### Motivation

Impossible to uniquely identify frames right now

**Comment by dgozman** [comment]
@himat ID is an internal implementation detail. You can always create a `Map<Frame, number>` or use a symbol and lazily auto-generate ID for each frame.

```ts
const idMap = new Map<Frame, number>();
function getFrameId(frame: Frame) {
  if (!idMap.has(frame))
    idMap.set(frame, idMap.size + 1);
  return idMap.get(frame)!;
}
```

**Comment by himat** [comment]
I also noticed that playwright has an internal only `guid` field. Is that also stable, or are the `guid` assigned to each instance and therefore wouldn't work? In other words, are these `guid`s, a unique UI on the _reference_ or on the actual underlying value?

**Comment by dgozman** [comment]
@himat `Frame` object is always the same for the same frame. `guid` is a part of the `Frame` object, but since it's an internal implementation detail, it might disappear at any moment as well.

**Comment by himat** [comment]
@dgozman, ok so using `Frame` makes sense for that

But I have another usecase, where I need to reach into the CDP to listen for events since playwright does not expose these
```
  const cdpClient = await page.context().newCDPSession(page)
  await cdpClient.send("DOM.enable")
  await cdpClient.send("Network.enable")

  cdpClient.on("Network.requestWillBeSent", onNavigationStart)
```
```
  function onNavigationStart(params: Protocol.Network.RequestWillBeSentEvent) {
    const frames = page.frames()
    const navigationFrameId = params.frameId
    const isMainFrame = frames.find((frame) => frame.<ID??> === navigationFrameId) !== -1
    if (!isMainFrame) return
    ...
}
```

As you can see, I want to detect the navigation start for a page, and the RequestWillBeSentEvent gives me back a `frameId`, and I want to only run this algorithm on the main frame, but I can't do that here since you don't expose the frame ID.
Also, just wanted to check, but the frame object `guid` is entirely different from the actual Frame's ID right? Was wondering if I could even use the `guid` here even if temporarily even though its internal

**Comment by dgozman** [comment]
@himat Interoperating with CDP is not a goal for Playwright. The use of CDP is an implementation detail. If you'd like to work with CDP directly, feel free to retrieve the frame tree over CDP and call any protocol methods you'd like. Note that Playwright does not guarantee that it won't break after you call some CDP methods, so use it at your own risk.

> Also, just wanted to check, but the frame object guid is entirely different from the actual Frame's ID right?

Yes, `guid` is a separate randomly generated id.

**Comment by dgozman** [comment]
Closing as per above. If you encounter more problems, please file a new issue by filling in the "Bug Report" template.
