### ISSUE TITLE
[Feature]: Do not retry test marked with test.fail if it has passed(not failing anymore)

### ISSUE THREAD

**Issue by sergtimosh** [microsoft/playwright#30266]
### 🚀 Feature Request

Retrying the tests with reported bugs that started to pass seems redundand.
<img width="1414" alt="image" src="https://github.com/microsoft/playwright/assets/26712442/5f6db748-50a5-472c-8da5-49fab1e99436">
So i suggest 2 variants:
1. do not retry by default, if they've passed in red then it's fine.
2. add property in playwright config

### Motivation

It'll potentially make tests runs with multiple 'test.fail' tests faster especially on the dynamic development testing environments.

**Comment by dgozman** [comment]
@sergtimosh It seems like there is no difference between a regular test and `test.fail` in terms of retries. The `test.fail` test might have passed unexpectedly due to a flake, so retry is in order. Is there any strong reason for the opposite behavior?

**Comment by mxschmitt** [comment]
Closing as per above as part of the triage process. Feel free to re-file for further questions.
