### ISSUE TITLE
[Feature]: Show the Test Annotation in the Merged Report Even Though the Test are Being Skipped

### ISSUE THREAD

**Issue by aldys33** [microsoft/playwright#30260]
### 🚀 Feature Request

I just notice that if my test got skipped, the annotation is missing from the report. This only happen when I use merge-report, which is I'm utilizing sharding.
![image](https://github.com/microsoft/playwright/assets/139728284/72d3cd55-56de-4d90-a579-2cf067573269)

----

I think it's better to have annotation still got attached in the report, despite the test being success, failed, or even skipped as well for the merged report.

### Example

Condition when the test got skipped

![image](https://github.com/microsoft/playwright/assets/139728284/1f1a70cc-6cb5-4c35-84f7-a7b3269864a7)

Condition when the test is failed/success

![image](https://github.com/microsoft/playwright/assets/139728284/98a7deff-9ae1-474d-b96e-c0105dc83699)

### Motivation

I believe there are user that utilize annotation for several purpose. Like for me, it is a place to store Test ID that connects with the AIO. So it's important to preserve the annoation in the report regardless of how the test execution is going

**Comment by aldys33** [comment]
yeah, will create a repo to demonstrate on that one

**Comment by aldys33** [comment]
Please refer to the following repo https://github.com/aldys33/Playwright.Annotation.Demo/actions
I did create a sample run with and without sharding. Please note that when using sharding, the annotation is not showing

**Comment by dgozman** [comment]
@aldys33 Thank you for the repro, I can see the bug now.

---

Investigation notes: a test is skipped in one of the shards and there is no `onTestEnd` event in the blob reporter that contains annotations.
