### ISSUE TITLE
[Bug]: VSCode Playwright Extension broken gutter

### ISSUE THREAD

**Issue by roberteles** [microsoft/playwright#30265]
### Version

1.37.1

### Steps to reproduce

1. Install VSCode 1.88
2. Install Playwright VSCode plugin - https://github.com/microsoft/playwright-vscode
3. Go to an existing Playwright test in your codebase, observe gutter Play buttons on the wrong lines

### Expected behavior

I would expect the gutter lines to be positioned correctly.

### Actual behavior

The Gutter Play buttons are on wrong lines:

<img width="679" alt="Screenshot 2024-04-05 at 2 04 31 pm" src="https://github.com/microsoft/playwright/assets/826074/ba52ceca-b90a-4213-b92e-54e9501785bd">

### Additional context

This issue shows up in the location of error messages as well.

### Environment

```shell
System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 146.09 MB / 32.00 GB
  Binaries:
    Node: 21.7.1 - ~/.nvm/versions/node/v21.7.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v21.7.1/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v21.7.1/bin/npm
    pnpm: 7.14.2 - /opt/homebrew/bin/pnpm
  IDEs:
    VSCode: 1.88.0 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.37.1 => 1.37.1
```

**Comment by dgozman** [comment]
@roberteles Could you please share a repo that exhibits this behavior? We have to be able to reproduce the issue in order to fix it.

**Comment by mxschmitt** [comment]
Could you try the following, this might work for you: https://github.com/microsoft/playwright/issues/29157#issuecomment-1915000626

**Comment by mxschmitt** [comment]
Thats unfortunate! If you can provide a repro, we can take a look! Otherwise we are unfortunately not able to act on it.

**Comment by mxschmitt** [comment]
Closing as per above Please re-file with a repro, thanks!

**Comment by roberteles** [comment]
For future reference - it had to do with Node v21. Downgrading to Node v20 solved the issue for us.
