### ISSUE TITLE
[Bug]: Cannot Install Playwright extension in VS Code (version 1.48.2) on MacOS (Sonoma Version 14.3)

### ISSUE THREAD

**Issue by LynnJing** [microsoft/playwright#30277]
### Version

version 1.0.22

### Steps to reproduce

1. Open VS Code 
2. Find Playwright Test for VSCode in Extension 
3. Click Install button 

### Expected behavior

Can Install Playwright Test for VSCode in macOS successfully. 

### Actual behavior

Cannot Install it 
<img width="1323" alt="Screenshot 2024-04-07 at 10 44 49" src="https://github.com/microsoft/playwright/assets/4716762/7b1a0618-26ec-4fa6-8934-0c578705fa6c">

### Environment

```shell
Environment Details as below 
VS Code Version : version 1.48.2
MacOS Version: Sonoma Version 14.3
```

**Comment by mxschmitt** [comment]
Have you tried updating VSCode? The latest version is 1.88: https://code.visualstudio.com/download

**Comment by mxschmitt** [comment]
Closing as per above.
