### ISSUE TITLE
Always get error when trying to run tests against webview2

### ISSUE THREAD

**Issue by hager-yousri** [microsoft/playwright#30280]
i use this as mentioned in official document

 const { playwright, chromium } = require('playwright');
const browser = await playwright.chromium.connectOverCDP('http://localhost:9992');
 const context = browser.contexts()[0];
 const page = context.pages()[0];

but got this error
Cannot read properties of undefined (reading 'chromium')

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
