### ISSUE TITLE
[Bug]: locator.toString() outputs the same locator twice

### ISSUE THREAD

**Issue by qk5** [microsoft/playwright#30281]
### Version

1.43.0

### Steps to reproduce

What I am trying to do is:
I have 2 saveButton locators on same page, they both have same name, one in iframe, the other is not.

I need to do something different for each locator, and here is my code snippet for this task:
```
if ( saveButton.toString().includes('frameLocator') ) {
// do something
}
else {
// do something else
}
```

Here is my saveButton in iframe, and when I tried to print this in string format, result was displayed 2 times.

```
let saveButton= page.frameLocator('iframe').getByRole('button', { name: 'Save', exact: true });
console.log(saveButton.toString());
```

### Expected behavior

Expected locator to be printed once:

`frameLocator('iframe').getByRole('button', { name: 'Save', exact: true })`

### Actual behavior

Expected locator was printed twice:
```
frameLocator('iframe').getByRole('button', { name: 'Save', exact: true })
frameLocator('iframe').getByRole('button', { name: 'Save', exact: true })
```

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 12.59 GB / 31.69 GB
  Binaries:
    Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.4.0 - C:\demo\node_modules\.bin\npm.CMD
  npmPackages:
    @playwright/test: ^1.43.0 => 1.43.0
```

**Comment by mxschmitt** [comment]
I tried to reproduce but was not able to, maybe you have the `console.log` twice? Could you maybe share your `playwright.config.ts`?

```typescript
it('repro, async ({ page }) => {
  const saveButton = page.frameLocator('iframe').getByRole('button', { name: 'Save', exact: true });
  console.log(saveButton.toString());
});
```
