### ISSUE TITLE
[Bug]: UI is stuck on pending and only outputs "Unable to read D:\Work\<spec folder>" 

### ISSUE THREAD

**Issue by Southclaws** [microsoft/playwright#30294]
### Version

1.42.1

### Steps to reproduce

This appears to be happening only on Windows at the moment, but with any setup.

### Expected behavior

I expect the tests to run.

### Actual behavior

The UI hangs with no output on any tab until eventually you see "Unable to read D:\<path to spec folder>" and the Actions tab shows "Pending".

### Additional context

The same codebase seems to work okay on a Mac, and there are no platform-specific modules being loaded, it's all just plain javascript.

I did also search for the phrase "Unable to read" in issues, Stackoverflow and the docs but nothing relevant appears so I've had to open an issue.

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 8.91 GB / 31.90 GB
  Binaries:
    Node: 21.6.2 - ~\AppData\Local\fnm_multishells\31908_1712589638085\node.EXE
    Yarn: 1.22.19 - D:\Work\node_modules\.bin\yarn.CMD
    npm: 10.2.4 - D:\Work\node_modules\.bin\npm.CMD
    pnpm: 8.15.4 - D:\Work\node_modules\.bin\pnpm.CMD
    bun: 1.1.0 - ~\AppData\Local\Microsoft\WinGet\Links\bun.EXE
  IDEs:
    VSCode: 1.87.2 - C:\Users\southclaws\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!

**Comment by Southclaws** [comment]
I filled in the form on GitHub, is that not the template? As for reproduction, this appears to just happen on any setup, so just run the tutorial on Windows on an empty codebase.
