### ISSUE TITLE
[Bug]: Invalid http status code or phrase (chromium)

### ISSUE THREAD

**Issue by nucleartux** [microsoft/playwright#30292]
### Version

1.43.0

### Steps to reproduce

1. Create test with following code
``` 
   await page.route("**/api/foo/bar", (route) =>
      route.fulfill({
        status: 420,
        json: {
          error: "error",
          message: "foo",
        },
      }),
    );
```
2. Run this test (chromium in my case)

### Expected behavior

Route should be fulfilled successfully

### Actual behavior

Invalid http status code or phrase

### Additional context

I have backend (which I don't control) which uses 420 status code in specific scenarios.
However, I can't test my frontend app with such code.
Is there any plans to allow use this status code in future?
As I figured it out this problem exists only in chromium, in firefox everything is good. Therefore, I suppose it actually problem in chromium itself, but I decided to leave issue open anyway.

### Environment

```shell
System:
    OS: macOS 14.4.1
    Memory: 440.83 MB / 16.00 GB
  Binaries:
    Node: 20.11.0 - /usr/local/bin/node
    Yarn: 3.2.0 - /usr/local/bin/yarn
    npm: 10.5.0 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    playwright-teamcity-reporter: ^0.2.0 => 0.2.0
```

**Comment by mxschmitt** [comment]
Chrome is strict about status codes you are using. We recommend using well-known status codes.
