### ISSUE TITLE
[Bug]: "Your Firefox profile cannot be loaded. It may be missing or inaccessible" error when launching firefox

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#30302]
### Version

1.43.0

### Steps to reproduce

1. launch firefox with playwright:
    ```js
    const { firefox } = require('playwright')
    
    ;(async () => {
        await firefox.launch({ headless: false }) // when headless is true, it just hangs instead, presumably the error is still occuring but not being displayed
    })()
    ```

### Expected behavior

firefox launches

### Actual behavior

![image](https://github.com/microsoft/playwright/assets/57028336/480adc8c-f05f-47c7-9811-eec113e7f626)

the following errors are logged to the console:
```
browserType.launch: Target page, context or browser has been closed
Browser logs:

<launching> C:\Users\user\AppData\Local\ms-playwright\firefox-1447\firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\user\AppData\Local\Temp\playwright_firefoxdev_profile-hoSZmN -juggler-pipe -silent
<launched> pid=52048
[pid=52048][err] JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 84: Error: Can't find profile directory.
[pid=52048][err] JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 84: Error: Can't find profile directory.
[pid=52048][err] JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 84: Error: Can't find profile directory.
[pid=52048][err] JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 84: Error: Can't find profile directory.
[pid=52048][err] JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 84: Error: Can't find profile directory.
[pid=52048][err] JavaScript error: resource://gre/modules/XULStore.sys.mjs, line 84: Error: Can't find profile directory.
[pid=52048][err] [ERROR webrender_bindings::program_cache] shader-cache: Shader disk cache is not supported
[pid=52048][out] Crash Annotation GraphicsCriticalError: |[G0][GFX1-]: shader-cache: Shader disk cache is not supported (t=5.42334) [GFX1-]: shader-cache: Shader disk cache is not supported
[pid=52048] <process did exit: exitCode=1, signal=null>
[pid=52048] starting temporary directories cleanup
```

i checked for the `C:\Users\user\AppData\Local\Temp\playwright_firefoxdev_profile-hoSZmN` directory and it exists, but it's empty.

### Additional context

i'm on a work PC with group policies and stuff. unfortunately i don't know all the details but here's what i do know:

- the installation of firefox that i normally use (separate to the one playwright uses) says it's managed by my organization:
   ![image](https://github.com/microsoft/playwright/assets/57028336/fc992727-2814-4fec-9781-dde4dda8385d)

  i assume this is also the case with the version that playwright uses, since chrome works the same way.
- here are the policy settings (which i can't change):
  <details><summary>Details</summary>
  <p>
  
  ![image](https://github.com/microsoft/playwright/assets/57028336/8237b33f-34e4-4d45-9371-321eea269dd8)
  
  </p>
  </details> 
- it happens to everyone else at work too, but not on my home PC, which is why i think it may be something to do with these policies

### Environment

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11500H @ 2.90GHz
    Memory: 5.38 GB / 31.20 GB
  Binaries:
    Node: 21.5.0 - ~\AppData\Roaming\node\node.EXE
    npm: 10.2.4 - ~\AppData\Roaming\node\npm.CMD
    bun: 1.0.35 - ~\.bun\bin\bun.EXE
  IDEs:
    VSCode: 1.87.2 - C:\Users\user\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.1.16 - C:\WINDOWS\system32\bash.EXE
  npmPackages:
    @playwright/test: ^1.43.0 => 1.43.0
    playwright: ^1.43.0 => 1.43.0
    playwright-core: ^1.43.0 => 1.43.0
```

**Comment by mxschmitt** [comment]
Are you able to launch `C:\Users\user\AppData\Local\ms-playwright\firefox-1447\firefox\firefox.exe` manually?

Are you able to launch the following?

```
C:\Users\user\AppData\Local\ms-playwright\firefox-1447\firefox\firefox.exe -profile C:\Users\user\AppData\Local\Temp\playwright_firefoxdev_profile-hoSZmN 
```

The `DisableProfileFresh` policy sounds related.

**Comment by DetachHead** [comment]
nope, same error on both commands ("Your Firefox profile cannot be loaded. It may be missing or inaccessible").

it turns out i'm able to disable the policies in the registry (by deleting/renaming `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Mozilla\Firefox`) and verified that they're no longer active in my user installation of firefox:

![image](https://github.com/microsoft/playwright/assets/57028336/5f4e8622-8f8d-4bc6-99b5-2e91f3361d18)

but the issue still persists, so maybe it's not the policies?

**Comment by mxschmitt** [comment]
Do you have a special anti-virus on your system? Might be related to the profile service [not able to start](https://github.com/mozilla/gecko-dev/blob/f602853ba8d55ba157e2a74d9b571615f6ed97b8/toolkit/xre/nsAppRunner.cpp#L4873). If so, I'd try disabling it and see if you are able to launch Firefox without it.

**Comment by DetachHead** [comment]
it might be an antivirus thing. it seems intermittent because now it's launching just fine with playwright. next time it happens, i'll try and get more information. thanks

**Comment by mxschmitt** [comment]
Cool, closing in the meantime.

**Comment by DetachHead** [comment]
so it turns out there's something installed on these work PCs that block access to firefox's `profiles.ini` which was causing this issue. as far as i can tell there's no way to configure it because the file name is hardcoded in firefox itself, so i wrote this python script that patches playwright's version of firefox to instead look for a different file (it doesn't actually need to exist). this seems to have fixed the problem:

```py
from pathlib import Path

from playwright.sync_api import sync_playwright

with sync_playwright() as pw:
    install_dir = Path(pw.firefox.executable_path).parent
    file_to_patch = install_dir / "xul.dll"
    print(f"patching playwright firefox installation at {install_dir}")
    file_to_patch.write_bytes(
        file_to_patch.read_bytes().replace(b"profiles.ini\x00", b"profilez.ini\x00")
    )
```
