### ISSUE TITLE
[Bug]: Can't dispatch events on document or window objects

### ISSUE THREAD

**Issue by MikeDabrowski** [microsoft/playwright#30303]
### Version

1.42.1

### Steps to reproduce

In my app i added event listeners with console logs for dragenter event. Also my app's logic acts on document:dragenter. 

The test:  
```
await page.evaluate(() => {
      document.dispatchEvent(new Event('dragenter'));
      window.dispatchEvent(new Event('dragenter'));
    })
```

### Expected behavior

In console logs I expect to see listener logs and my apps logic should be triggered

### Actual behavior

Nothing happens.

### Additional context

I also tried evaluateHandle - same result.

### Environment

```shell
System:                                                  
    OS: Windows 10 10.0.19044                              
    CPU: (16) x64 Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
    Memory: 7.76 GB / 31.88 GB                             
  Binaries:                                                
    Node: 21.0.0 - C:\Program Files\nodejs\node.EXE        
    npm: 10.2.0 - C:\Program Files\nodejs\npm.CMD          
  Languages:
    Bash: 5.0.17 - C:\Windows\system32\bash.EXE
  npmPackages:
    @playwright/test: ^1.42.1 => 1.42.1
```

**Comment by mxschmitt** [comment]
Works for me!

```ts
test('should dispatch wheel events @smoke', async ({ page }) => {
  page.on('console', msg => console.log(msg.text()));
  await page.goto('https://example.com');
  await page.evaluate(() => {
    document.addEventListener('dragenter', event => console.log('dragenter was fired!'));
    document.dispatchEvent(new Event('dragenter'));
    window.dispatchEvent(new Event('dragenter'));
  });
});
```

Maybe Playwright fires your events too early and your application is not listening on the events yet?

**Comment by mxschmitt** [comment]
Browsers require focus for specific actions, when evaluating JavaScript, this means that such things need to be done manually.

Sounds like we can close it?

**Comment by MikeDabrowski** [comment]
Yes we can. Thank you.
Might be worth adding a hint in the "file upload" section

**Comment by MikeDabrowski** [comment]
@mxschmitt 
I think I hit similar issue. I was trying to set local storage item and have my app listen for storage events. Playwright sets the local storage item fine but the event is never fired. And it does not matter if I set it before or after clicking anything on the page.

```ts
    await loggedInPage.locator('body').focus();
    await loggedInPage.evaluate(() => {
      const current = JSON.parse(localStorage.getItem('appState') || '{}');
      localStorage.setItem('appState', JSON.stringify({ ...current, hideFlow: true }));
    });
```

Do you have any idea what it could be this time?
