### ISSUE TITLE
[Bug]: My site is not able to login on Webkit although Chromium & Firefox are working smoothly

### ISSUE THREAD

**Issue by danghung-30385** [microsoft/playwright#30305]
### Version

Playwright 1.43

### Steps to reproduce

- Login function is run on 3 browsers (Chromium, Firefox, and Webkit)

### Expected behavior

 login function can works smoothly on Webkit

### Actual behavior

1. The login function is FAILED only on Webkit
2. The login function is PASSED on Chomium & Firefox

### Additional context

[trace (24).zip](https://github.com/microsoft/playwright/files/14916883/trace.24.zip)
[f10688cca915ec36251a6cea0258938d26be9f0f.webm](https://github.com/microsoft/playwright/assets/56102603/33c04c2f-e388-4453-883a-994b9066a3fd)

### Environment

1. Playwright Version: 1.43
2. Operating System: Ubuntu 22.04 LTS (Jammy Jellyfish).

**Comment by mxschmitt** [comment]
When I'm running it in WebKit, I'm getting:

```
Info: The current domain is not authorized for OAuth operations. This will prevent signInWithPopup, signInWithRedirect, linkWithPopup and linkWithRedirect from working. Add your domain (development-webapp-common-flow-auth.eks.csp.scrum-dev.com) to the OAuth redirect domains list in the Firebase console -> Authentication -> Settings -> Authorized domains tab.
```

Could you confirm that your domain is listed there?

**Comment by danghung-30385** [comment]
Hi mxschmitt,
Thanks for your reply quickly.

I would like add more info, This test case run well with Webkit on Windows and only got failed on CI & Ubuntu. I tried with many approaches such as: clear cookie, route... But the script always failed on CI & Ubuntu

**Comment by ReactiveWarrior** [comment]
Webkit Mobile failing on Linux Docker container is well known problem:
1. https://github.com/microsoft/playwright/issues/10183
2. https://github.com/microsoft/playwright/issues/11101
3. https://github.com/microsoft/playwright/issues/23573

Recently, I stumbled upon this as well, my test was failing only on Mobile Safari and only on GitHub CI where Linux Docker container is used. I couldn't solve this issue as others also didn't. Unfortunately I had to disable the test for this browser.

**Comment by mxschmitt** [comment]
Was able to find out the root-cause, its related to cookie parsing. Created a minimal reproduction here: https://github.com/microsoft/playwright/pull/30323

Regarding a workaround for now, you could e.g. login via the API, this would not test the login-flow anymore on WebKit, but you could do it conditionally until we have fixed it. Something like this:

```ts
it('your-test', async ({ page, browserName }) => {
  if (browserName === "webkit" && process.platform === "linux") {
    await page.request.post('https://development-webapp-common-flow-auth.eks.csp.scrum-dev.com/api/auth/signin', {
      data: {
        email: "yen.vo+5@c2c-techhub.io",
        password: "Aa123456@",
        role: "customer",
      }
    })
    await page.getByTestId('customer-login-email').fill('yen.vo+5@c2c-techhub.io');
  } else {
    await page.goto('https://development-webapp-common-flow-auth.eks.csp.scrum-dev.com/login?role=customer');
    await page.getByTestId('customer-login-email').fill('yen.vo+5@c2c-techhub.io');
    await page.getByTestId('customer-login-password').fill('Aa123456@');
    await page.getByTestId('customer-login-button').click()
  }
  // ...
});
```

(Marking the comment above as off-topic, since its not related)

**Comment by danghung-30385** [comment]
Hi mxschmitt,

Thanks for your support & comment. Could you help me to share the plan for release 1.44?

**Comment by mxschmitt** [comment]
Since this bug is fairly involved and not in Playwright itself (in a dependency of WebKit) we cannot commit on any eta. I recommend either the workaround for now or run your tests on macOS until its fixed.

**Comment by danghung-30385** [comment]
Many thanks mxschmitt

**Comment by makssora** [comment]
I reproduced same problem on the webkit, it works perfectly locally, but when launched in a container, the test fails when logging  (v1.44.0)

**Comment by mxschmitt** [comment]
Note: This requires a new release of libsoup: https://gitlab.gnome.org/GNOME/libsoup/-/tags
