### ISSUE TITLE
[Bug]: Playwright 1.43.0 UI mode clears results after tests finished executing

### ISSUE THREAD

**Issue by ReactiveWarrior** [microsoft/playwright#30319]
### Version

1.43.0

### Steps to reproduce

Steps to reproduce:
1. Clone my repo at https://github.com/ReactiveWarrior/playwright-ui-bug
2. npm install
3. npx playwright test --ui
4. Run all tests (F5)
5. See the tests finished executing
6. After ~1 sec. see the test results disappear (UI mode goes to IDLE state as if you just opened it)

### Expected behavior

I expect to see the test results so that I could click on each test and see the logs, snapshots etc. Similarly what the trace viewer provides. I expect test results to preserve until I run the tests again or close the UI viewer.

### Actual behavior

The bug is that after ~1 sec. since the tests finished executing, the test results disappear, the UI mode goes to IDLE state as if you just opened it.

### Additional context

This bug happened right after I upgraded the Playwright version to 1.43.0.

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz      
    Memory: 4.19 GB / 11.91 GB
Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD   
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
IDEs:
    VSCode: 1.88.0 - D:\Programs\Microsoft VS Code\bin\code.CMD
npmPackages:
    @playwright/test: ^1.43.0 => 1.43.0
```

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/30300.
