### ISSUE TITLE
[Feature]: Add opportunity to set custom test-id without describing new browser and context

### ISSUE THREAD

**Issue by mascala** [microsoft/playwright#30311]
### 🚀 Feature Request

Currently in Playwright in Python, setting custom test-IDs requires defining a new browser and context. It means for example that I need to write my own handler of launch attributes such as "headed" " slow-mo" etc. And when I want to make traces it even more complicated.

The proposed feature should let me set up test is from fixture. 

### Example

Code just to add ids and use some attributes 
@pytest.fixture(scope='class')
def playwright_context(pytestconfig, playwright: Playwright):
    playwright.selectors.set_test_id_attribute('custom-id')
    browser = playwright.chromium.launch(
        headless=not pytestconfig.option.headed,
        slow_mo=pytestconfig.option.slowmo
    )
    context = browser.new_context()
    yield context
    context.close()
    browser.close()

### Motivation

The proposed feature should simplify this process by allowing the direct assignment of custom test-IDs.

**Comment by mxschmitt** [comment]
Something like this should work as of today, would that work for you?

```python
@pytest.fixture(scope="session", autouse=True)
def _auto_set_testid(playwright: Playwright):
    playwright.selectors.set_test_id_attribute("data-testid123")
```

testID can be configured without a page/context/browser instance.

**Comment by mxschmitt** [comment]
Closing for now as per above. Feel free to re-file if it doesn't work for you.
