### ISSUE TITLE
[Feature]: "evaluating" mode (failed + ignored)

### ISSUE THREAD

**Issue by Danieliverant** [microsoft/playwright#30318]
### 🚀 Feature Request

I want to write a test and put it on "evaluating" mode - which means the test will run but if it fails it will be marked as failed + ignored, so it won't fail the whole run.

Then I can monitor the test for X time, and if I see it's stable I can remove the evaluating mode.

### Example

`test.evaluate(...)` (like test.skip/test.fixme etc...)

### Motivation

The test can pass once for the dev who created it, and then they will merge it, but when the whole company running those tests repeatedly it may fail a lot (flaky).

With the "evaluating" mode we can see the results of these tests but they will not fail the pipeline.

**Comment by mxschmitt** [comment]
What do you mean with "so it won't fail the whole run."? Playwright will already continue to run other tests if only some test failed. Are you using serial mode?

**Comment by Danieliverant** [comment]
> What do you mean with "so it won't fail the whole run."? Playwright will already continue to run other tests if only some test failed. Are you using serial mode?

It would but it will fail the pipeline (github actions) - test on "evaluating" mode should not fail the pipeline.

**Comment by mxschmitt** [comment]
Its not recommended to check anything into source-control which is not "stable" - so instead of: "check something unstable into source control which is optional to pass" we would recommend to "create a PR with your test, run it maybe multiple times and then merge it in, so you see if its failing or not in your main branch".

Having the suggested approach you proposed would result in a optional tests which would bring no value and might be forgotten. If you still want it, you could do something like this, to make them not fail:

```ts
test('foobar', async({ page }) => {
  try {
    // ... your test
  catch (error) {
    // "Evaluate mode"
    console.error(error). 
  }
});
```

**Comment by Danieliverant** [comment]
> Its not recommended to check anything into source-control which is not "stable" - so instead of: "check something unstable into source control which is optional to pass" we would recommend to "create a PR with your test, run it maybe multiple times and then merge it in, so you see if its failing or not in your main branch".
> 
> Having the suggested approach you proposed would result in a optional tests which would bring no value and might be forgotten. If you still want it, you could do something like this, to make them not fail:
> 
> ```ts
> test('foobar', async({ page }) => {
>   try {
>     // ... your test
>   catch (error) {
>     // "Evaluate mode"
>     console.error(error). 
>   }
> });
> ```

Thank you for the suggestion

I did what you suggested, but a test wrapped in try-catch + the test has a beforeEach - still breaking the pipeline?

**Comment by Danieliverant** [comment]
I think this is the problamatic code:

```
  rejectOnTimeout(timeout: number, message: string) {
    if (!timeout)
      return;
    const { promise, dispose } = waitForTimeout(timeout);
    this._rejectOn(promise.then(() => { throw new TimeoutError(message); }), dispose);
  }
```

you first execute the code (promise.then) and then throwing the TimeoutError without anything that can catch it.
@mxschmitt

**Comment by Danieliverant** [comment]
@mxschmitt can you please see my comments above?
