### ISSUE TITLE
[Bug]: HTML report create sub-step out of the previous step

### ISSUE THREAD

**Issue by Hansanto** [microsoft/playwright#30322]
### Version

1.43.0

### Steps to reproduce

```ts
test('my test'), async () => {
await test.step('step 1', async () => {
      let counter = 0

      await expect(async () => {
        await test.step('step 1.1 with counter: '+ counter, async () => {

        })
        counter++;
        expect(counter).toBe(2);
      }).toPass()

      await test.step('step 1.2', async () => {
        await test.step('step 1.3', async () => {
        })
      })
    })
})
```

### Expected behavior

In the HTML report, when the previous code is executed, the steps created into the `expect(..).toPass()` (named **step 1.1**) must be nested into the **step 1** like **step 1.2** and **step 1.3**, and not at the same level than **step 1**

### Actual behavior

In the HTML report, when the previous code is executed, the steps created into the `expect(..).toPass()` method is not nested into the previous `test.step`
![image](https://github.com/microsoft/playwright/assets/73109509/00994a81-84e0-4bc3-8ce4-d60ccb55e628)

### Environment

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12800H
    Memory: 18.32 GB / 31.03 GB
    Container: Yes
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
  IDEs:
    VSCode: 1.88.0 - /usr/bin/code
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    @playwright/test: 1.43.0 => 1.43.0
```

**Comment by yury-s** [comment]
It regressed somewhere between 1.40 and 1.41. https://github.com/microsoft/playwright/commit/eeb9e06d5ebbca5431e8f709c5ee492f1be970f2 is likely the culprit.
