### ISSUE TITLE
Webkit for Mac and Windows showinf differente results

### ISSUE THREAD

**Issue by CesarPortalTR** [microsoft/playwright#30325]
### Version

Version 1.41.0

### Steps to reproduce

If test page is opened in Webkit browser:
1. On mac system
2. On Windows system

### Expected behavior

1. Page should be opened with no problem
2. Page should be opened with no problem

### Actual behavior

1. Page is opened with no problem
2. Browser is opened but leave page in blank

### Additional context

I run several test cases in webkit and a lot of them work good. Only few work weird if I use mac or windows. Should I add something else to configuration? As some people on the team work with windows and others with mac, windows can throw false fails (when testing is executed in webkit)

### Environment

```shell
System:
    OS: macOS 14.3
    CPU: (12) arm64 Apple M3 Pro
    Memory: 5.70 GB / 36.00 GB
  Binaries:
    Node: 20.12.1 - /usr/local/bin/node
    npm: 10.5.0 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.41.0 => 1.41.0
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
