### ISSUE TITLE
[Question] HARs name pattern

### ISSUE THREAD

**Issue by AlexcastroDev** [microsoft/playwright#30333]
Hello yall,

I would like to know if it is possible to have names of [Http archives](https://playwright.dev/docs/mock#mocking-with-har-files) based on the name of the test, or something similar, instead of a random name.

The case in point is that, for example, I have a page with 200 tests, and now I have enabled mocking with HARs. In these flows, I want to update only 10 tests where my changes have an impact.

Even if I keep them in a folder just for 'inventory', I can't tell which tests I need to delete, because when updating the HTTP archive, it generates others, so I can't maintain consistency between the number of tests and the number of Archives.

In the end, I have to delete the entire folder and generate everything again.

The expected behavior would be similar to VCR from Rails (https://github.com/vcr/vcr) where the name of the spec and the path generates a fixed name, and I can update just 1 or N specs using VCR=new_episodes or VCR=all.

Thanks for the help, appreciate it.

**Comment by mxschmitt** [comment]
You could do something like this, would that work for you?

```ts
import { test, Page } from '@playwright/test';
import path from 'node:path';

test('records or updates the HAR file', async ({ page }) => {
  await page.routeFromHAR(generateHarName(), {
    url: '*/**/api/v1/fruits',
    update: true,
  });

});

function generateHarName() {
  const [specName, ...parts] = test.info().titlePath;
  return path.join(__dirname, `${specName.replace(/\.(test|spec)\.ts/, '-hars')}`, parts.join('-').replace(/ /g, '-'), 'har.har');
}
```

this would give you a har folder for each test.

**Comment by AlexcastroDev** [comment]
> You could do something like this, would that work for you?
> 
> ```ts
> import { test, Page } from '@playwright/test';
> import path from 'node:path';
> 
> test('records or updates the HAR file', async ({ page }) => {
>   await page.routeFromHAR(generateHarName(), {
>     url: '*/**/api/v1/fruits',
>     update: true,
>   });
> 
> });
> 
> function generateHarName() {
>   const [specName, ...parts] = test.info().titlePath;
>   return path.join(__dirname, `${specName.replace(/\.(test|spec)\.ts/, '-hars')}`, parts.join('-').replace(/ /g, '-'), 'har.har');
> }
> ```
> 
> this would give you a har folder for each test.

Yep ! This work, and create a folder with har and the requests.

Also, i face multiple files, for only 3 specs

<img width="280" alt="image" src="https://github.com/microsoft/playwright/assets/10711649/ae86897c-18d6-41b0-a980-6ef355eee09b">

To solve this i update the options with `updateContent: 'embed'`

<img width="209" alt="image" src="https://github.com/microsoft/playwright/assets/10711649/dee5a3e6-425a-4add-9b9d-f14b7295bc8c">

and this works like charm!

Thanks for helping me ! <3
