### ISSUE TITLE
[Bug]: Issues with Protocol error (Page.navigate), page.goto: does not work 

### ISSUE THREAD

**Issue by litserkovna** [microsoft/playwright#30336]
### Version

1.43.0

### Steps to reproduce

export default class MainPage{
    constructor(page){
        this._page = page
        this._signupButton = page.locator('.hero-descriptor_btn.btn.btn-primary');
    }
    async navigate(){
        await this._page.goto("") ---- here it fails
    }
 
 Issue: 
 
 Error: page.goto: Protocol error (Page.navigate): Cannot navigate to invalid URL
    Call log:
      - navigating to "", waiting until "load"
      

In the playwright config file, I entered the base URL with the HTTP credentials and it worked fine earlier, and now without any updates it randomly stopped working. 

Like this (fake data): 
use: {
    headless: false,
    baseURL: 'https://example.com/',
    httpCredentials: {
      username: 'user',
      password: 'pass'
    },

### Expected behavior

Page navigates to the baseURL mentioned in the playwright config file (worked before).

### Actual behavior

Error: page.goto: Protocol error (Page.navigate): Cannot navigate to invalid URL
    Call log:
      - navigating to "", waiting until "load"

### Environment

```shell
MacOS Ventura 13.5
├── @playwright/test@1.43.0
└── @types/node@20.12.4
```

**Comment by mxschmitt** [comment]
Invalid URL usually means that no baseURL was configured. Maybe you set the baseURL to null/undefined somewhere else?

We need more information to act on it, are you able to provide us a reproduction repository?
