### ISSUE TITLE
[Bug]: Performance issue with yarn pnp

### ISSUE THREAD

**Issue by gwen1230** [microsoft/playwright#30341]
### Version

1.43.0

### Steps to reproduce

- Clone reproduction : https://github.com/gwen1230/playwright-performance-issue
- run yarn install
- run yarn playwright test

### Expected behavior

Tests are executed in a similar time to a repo without the pnp linker

### Actual behavior

Tests take 6 times longer to run than with a node-module linker. yarn plarywright test --ui also take a lot of time.

### Additional context

The repo is created with the yarn create playwright command. The only change I made is to switch to the berry version and activate the pnp linker. By editing the yarnrc.yml file and switching back to node-module linker, times become reasonable again.

- yarn test playwright with pnp : 36 seconds
- without pnp : 6 seconds

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
    Memory: 9.91 GB / 31.64 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 4.1.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.88.0 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.2.21 - C:\Program Files\Git\usr\bin\bash.EXE
```

**Comment by Jennypopping** [comment]
❤️

**Comment by mxschmitt** [comment]
It seems like Yarn with PNP mode is slower. There is no action item for Playwright here.

I recommend filing an issue against Yarn.

**Comment by gwen1230** [comment]
Could you tell me what makes playwright so long with yarn pnp so I can direct my issue on Yarn?
