### ISSUE TITLE
[Bug]: Headless mode behavior is different than UI mode

### ISSUE THREAD

**Issue by colinblaise** [microsoft/playwright#30345]
### Version

@1.42.1

### Steps to reproduce

The following code works when I run `yarn playwright --ui` but does not work when I run `yarn playwright`.

```ts
test.describe("desktop", () => {
  test.use({ viewport: { width: 1280, height: 800 } });

  test("sidebar is open on desktop by deafult", async ({ page }) => {
    await page.goto("/", { waitUntil: "domcontentloaded" });
    const body = page.locator("body");
    expect(body).toHaveClass(/im-sidebar-show/);
  });
});
```

```
   Error: expect(locator).toHaveClass(expected)

    Locator: locator('body')
    Expected pattern: /im-sidebar-show/
    Received string:  ""
    Call log:
      - expect.toHaveClass with timeout 5000ms
      - waiting for locator('body')
```

![image](https://github.com/microsoft/playwright/assets/6540262/0cbd6496-76a1-45cd-82fe-c1585b5df315)

What is happening differently in UI mode that allows the test to succeed?

### Expected behavior

The test should pass without --ui

### Actual behavior

Testing without --ui fails

### Environment

```shell
System:
 Windows 11

@playwright/test@1.42.1
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
