### ISSUE TITLE
[Bug]:  Authenticate with API request problems.

### ISSUE THREAD

**Issue by ViktorMakTorwend** [microsoft/playwright#30358]
### Version

1.41.2

### Steps to reproduce

1. Authenticating in UI mode finished successfully. In .json file there is an information.
2. Authenticate with API request finished fail. In .json file no information.

### Expected behavior

In. json file usefull information.

### Actual behavior

In. json file no information.

### Environment

```shell
Environment: Windows 10, Google Chrome Version 123.0.6312.105 (Official Build) (64-bit)
```

**Comment by ViktorMakTorwend** [comment]
Please, help me. I did as in documentation:
```
setup('authenticate', async ({ request, page }) => {
   await request.post("https://backendstaging...", {
     form: {
       'email': "admin@gmail.com",
       'password': "12345"
     }
   })
   request.storageState({ path: "playwright/.auth/admin.json" });
})
```
And after that I got:
```
{
  "cookies": [],
  "origins": []
}
```

**Comment by yury-s** [comment]
Please provide complete reproduction so that we could try it locally.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
