### ISSUE TITLE
[Feature]: Fixed masked element size

### ISSUE THREAD

**Issue by khanbhai89** [microsoft/playwright#30352]
### 🚀 Feature Request

We should have fixed masked element size, because currently when we have dynamic data it fluctuates mask size and tends to fail.

### Motivation

We have alot of test for a page which has dynamic fields on the page and where we need to mask them to exclude them but because width might be dynamic it fails in comparison.

**Comment by mxschmitt** [comment]
Do you want to mask elements for screenshots? Like toHaveScreenshot?

Could you give an example of whats not working as of today?

You can specify your own [stylePath option](https://playwright.dev/docs/api/class-pageassertions#page-assertions-to-have-screenshot-1-option-style-path), which is a CSS which gets loaded before the screenshot gets taken. Also some code would help us, so we can understand better of what feature you are looking for.

**Comment by yury-s** [comment]
> * screenshot of embedded PDF (which is a single iframe, so masking a variable part of the PDF is not possible)

Do you want to mask a region in the pdf? You can already mask entire iframe element with the iframe, does it not work for you because the iframe may have variable size?

**Comment by Exoow** [comment]
Yes, mask a region in the PDF. The entire PDF viewer is a single <embed> element within an <iframe>.

**Comment by yury-s** [comment]
@khanbhai89 for the variable size elements you can supply custom [CSS styles](https://playwright.dev/docs/api/class-pageassertions#page-assertions-to-have-screenshot-1-option-style-path) as Max suggested that would set a predictable width/height as well as their display style (transparency, color etc) of the elements independent of their content.

> Yes, mask a region in the PDF. The entire PDF viewer is a single <embed> element within an <iframe>.

Masking within PDFs and screenshotting PDFs in general is out of scope for playwright, we'd recommend you mask the entire iframe element in such case to avoid flakiness. For rendering PDFs running something like pdf.js may be a better option.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
