### ISSUE TITLE
[Bug]: DEBUG=pw:webserver no longer works (regression)

### ISSUE THREAD

**Issue by EvgenyOrekhov** [microsoft/playwright#30360]
### Version

1.43.1

### Steps to reproduce

1. Add `webserver` configuration with `reuseExistingServer: true` to `playwright.config.ts`
2. Run `DEBUG=pw:webserver playwright test --ui`

### Expected behavior

Should see debug messages from web server, e. g.

```
  pw:webserver HTTP HEAD: https://example.com/ +0ms
  pw:webserver HTTP Status: 200 +912ms
  pw:webserver WebServer is already available +1ms
  pw:webserver Waiting for availability... +0ms
  pw:webserver HTTP HEAD: https://example.com/ +0ms
  pw:webserver HTTP Status: 200 +647ms
  pw:webserver WebServer available +2ms
```

### Actual behavior

No debug messages

### Additional context

It used to work in 1.42.0

### Environment

```shell
System:
    OS: macOS 14.4.1
    Memory: 2.55 GB / 32.00 GB
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by yury-s** [comment]
The output now goes to the UI mode console:

<img width="388" alt="image" src="https://github.com/microsoft/playwright/assets/9798949/04de8fe0-be10-499f-9f95-9140b3a8d4dc">

**Comment by EvgenyOrekhov** [comment]
Oh, good to know! Thanks! Closing the issue.
