### ISSUE TITLE
[Bug]: Viewing tests with -UI

### ISSUE THREAD

**Issue by Bart90PL** [microsoft/playwright#30369]
### Version

1.43

### Steps to reproduce

1. I enter the module - UI
2. I run the tests with the 'play' button

### Expected behavior

The entire test flow should be visible and I should be able to review each step in turn

### Actual behavior

The test flow is visible for a few seconds and then the whole thing is restarted to the state before the test was performed.

### Environment

```shell
windows 11 ent
node-v 18.16.1
```

**Comment by mxschmitt** [comment]
On which exact version are you? A similar bug was fixed in v1.43.1.

**Comment by Bart90PL** [comment]
I had a 1.43.0 version. In fact, in 1.43.1 there is no problem. Thanks.
