### ISSUE TITLE
Can't get more workers to run - Playwright

### ISSUE THREAD

**Issue by Nickkolean2793** [microsoft/playwright#30370]
PS C:\...\Testing> npx playwright test --workers 3
Error: test file "login.spec.ts" should not import test file "helperBase.spec.ts"

   at login.spec.ts:1

> 1 | import {Page, expect, Locator} from '@playwright/test';
    | ^
  2 | import { HelperBase } from './helperBase.spec';
  3 |
  4 | export class NavigationPage extends HelperBase{

**Comment by Nickkolean2793** [comment]
helperBase.spec.ts content:

import { Page } from "@playwright/test";

export class HelperBase {
    readonly page: Page
    constructor(page:Page) {
        this.page = page
    }

    async waitForNumberOfSeconds(timeInSeconds: number){
        await this.page.waitForTimeout(timeInSeconds * 1000)
    }

}

**Comment by mxschmitt** [comment]
You need to rename `helperBase.spec.ts` to `helperBase.ts` and then things should work.

**Comment by Nickkolean2793** [comment]
thanks a lot, it works!
