### ISSUE TITLE
[Bug]: Since v1.43, "Error: Error: browserType.launch: Executable doesn't exist"

### ISSUE THREAD

**Issue by Progi1984** [microsoft/playwright#30371]
### Version

1.43.1

### Steps to reproduce

* Setup Node 16 
![image](https://github.com/microsoft/playwright/assets/1533248/386af6e2-d5a3-4041-af30-e168ef595886)
* Install playwright 1.43.1
* Install only one browser 
  *  `npx playwright install chromium --with-deps`
  * ![image](https://github.com/microsoft/playwright/assets/1533248/4865f857-21ad-4891-9986-36a26c961f7f)
* The browser doesn't use the good version
   ![image](https://github.com/microsoft/playwright/assets/1533248/0888098e-981e-49c4-a870-b1522c401e81)

### Expected behavior

The browser use the good version

### Actual behavior

The browser doesn't use the good version
   ![image](https://github.com/microsoft/playwright/assets/1533248/0888098e-981e-49c4-a870-b1522c401e81)

### Additional context

No problem with version < 1.43.0

Sample : https://github.com/PrestaShop/PrestaShop/actions/runs/8686046219/job/23816738826?pr=35914

### Environment

```shell
Github Actions : 
Current runner version: '2.315.0'
Operating System
  Ubuntu
  22.04.4
  LTS
Runner Image
  Image: ubuntu-22.04
  Version: 20240407.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240407.1/images/ubuntu/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240407.1
Runner Image Provisioner
  2.0.361.1
```

**Comment by mxschmitt** [comment]
Your project depends on multiple versions of Playwright, see [here](https://github.com/PrestaShop/PrestaShop/blob/51764a8a54404d2fcda153eb9c89a0c6910b79ff/tests/UI/package-lock.json#L444).

We recommend to only depend a single time on it. In this case `@prestashop-core/ui-testing` depends already on it, so you can just remove `playwright` [here](https://github.com/PrestaShop/PrestaShop/blob/51764a8a54404d2fcda153eb9c89a0c6910b79ff/tests/UI/package.json#L127) and do `npm install/ci` and Playwright will be available.

**Comment by Progi1984** [comment]
Thanks @mxschmitt. I'm so stupid. I forget it. Sorry for the lost time.
