### ISSUE TITLE
[Feature]: Allow page to listen for custom events `page.on(CUSTOM_EVENT, () =>`

### ISSUE THREAD

**Issue by khiga8** [microsoft/playwright#30376]
### 🚀 Feature Request

It would be useful if we could expose custom events emitted within the javascript environment, and listen for it in the playwright test environment. Currently, Playwright supports a [limited list of events](https://playwright.dev/docs/api/class-page#events), and they don't fit my needs.

### Motivation

After each hard and soft navigation, I'd like to run some code (specifically an accessibility scan) to grab information about the page I'm on and generate a report. The part I'm stuck on is listening for a soft nav event.

I did hack some code together, and have something working:

```ts
await page.exposeFunction('runScan', () => {
  await runAccessibilityReport(page) // conducts test and writes my results to a CSV
})
```

```ts
await page.addInitScript(() => {
  document.addEventListener(MY_SOFT_NAV_EVENT, async () => {
    await (window as any).runScan()
  })
})
```

However, the problem I'm running into is that the test will continue to execute and run assertions. Though we're awaiting `runScan`, it is running in the context of the Javascript environment so our test environment has no way of knowing about it. My `runAccessibilityReport` includes things like resizing the page (and resizing it back), which affects test assertions that continue to run in the test environment, without waiting for the report to finish.

Being able to do something like:

```ts
page.on(ANY_CUSTOM_EVENT, () => async () => {
  await runAccessibilityReport(page) // conducts test and writes my results to a CSV
})
```
seems like a much cleaner and a more intuitive way to achieve what I'm trying to do.

**Comment by yury-s** [comment]
You can achieve this today by adding custom event listeners in the page context and calling a binding to handle the event in Node:

```js
  await page.exposeFunction('handleEvent', event => {
    console.log('handling: ' + event.name);
  });
  await page.evaluate(() => {
    window.addEventListener('click', () => (window as any).handleEvent({ name: 'click' }));
  });
  await page.mouse.click(50, 50);
```
will that work?

**Comment by khiga8** [comment]
Hi @yury-s!  I appreciate the quick follow-up. The setup I have described in my issue description seems very similar to what you're suggesting. The problem I'm running into is:

* The function that is being exposed via `page.exposeFunction` is an asynchronous function, and the playwright test environment has no awareness of when this gets called or finishes.
* I don't want the playwright tests to continue to execute while this asynchronous call is being made. Even if I'm awaiting my call, it doesn't matter because this `await` is happening inside of the page's javascript, rather than in the test environment.

**Comment by yury-s** [comment]
> The function that is being exposed via page.exposeFunction is an asynchronous function, and the playwright test environment has no awareness of when this gets called or finishes.

DOM events are also dispatched synchronously and won't block on the async calls.

> I don't want the playwright tests to continue to execute while this asynchronous call is being made. Even if I'm awaiting my call, it doesn't matter because this await is happening inside of the page's javascript, rather than in the test environment.

If you want the tests to wait for a certain condition, you  can await for a promise in the test and wait for the condition (e.g. that there are no active `runAccessibilityReport` calls). This will be specific to the code of your tests though, something along these lines:

```js
  const handlers: Promise<void>[] = [];
  await page.exposeFunction('handleEvent', async event => {
    let resolve;
    const promise = new Promise<void>(r => resolve = r);
    handlers.push(promise);
    await runAccessibilityReport(page); // you async call here
    resolve();
    handlers.splice(handlers.indexOf(promise), 1);
    console.log('handling: ' + event.name);
  });
  await page.evaluate(() => {
    window.addEventListener('click', () => (window as any).handleEvent({ name: 'click' }));
  });
  // interact with the page
  await Promise.all(handlers); // wait for reports to finish
  // run the rest of your test
```

**Comment by khiga8** [comment]
@yury-s Ah I see. I am not sure I can do that. I'm currently extending the page behavior using a fixture because I want this report running automatically on every test:

```.ts
  page: async ({page}, use) => {
     // essentially all the code to attach handlers on the page
     use(page)
     ...
})
```
Then I use this `page` fixture in my tests:

```.ts
 test('Some test', async ({page}) => {
  await page.goto(someUrl)
  ...
})
```
I think the promise approach only work if all this code was moved into each test and I manually place the `await Promise.all(handlers)`.

Is there a way for me to achieve this within my page fixture, and avoid manually adding promises to each of my tests?

**Comment by yury-s** [comment]
> Is there a way for me to achieve this within my page fixture, and avoid manually adding promises to each of my tests?

You could expose another fixture that would ensure that all reports are complete:

```js
test('Some test', async ({page, waitForReports}) => {
  await page.goto(someUrl)
  ...
  await waitForReports();
   ...
})
```

that way you could reuse original fixture without duplicating the code.

Closing this request as there are existing workarounds.
