### ISSUE TITLE
Can't get parallel running for multiple tests in same file - Playwright

### ISSUE THREAD

**Issue by Nickkolean2793** [microsoft/playwright#30372]
### Please do not submit this issue.

- [ ] I understand

**Comment by Nickkolean2793** [comment]
Hello,

I am using this template in my spec file:


test.describe.configure({mode:'parallel'});

test.describe('test suite',()=>{
    
test.beforeEach(async ({page}) => {

    const pm = new NavPage(page)
    await pm.layout('login','password')

})


test('name', async ({page}) => {
    const ticket = new TickPage(page)
    await ticket.a('text')
    await ticket.b('text')
    await ticket.c('text')
    await ticket.d('text')
...
  


Config file includes:

  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 1,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 3 : 3,


However when I am running the spec file which contains 3 tests, by just clicking on Run button, I can see on terminal:
Running 3 tests using 1 worker

If I am trying to use npx playwright test --workers 3
it seems to run 3 tests using 3 workers


Can you suggest pls what am I missing in my spec file or configs , so file can run with 3 workers just from run click?
Thank you
Best regards

**Comment by yury-s** [comment]
Doesn't sound like a bug or feature request, please use our [community resources](https://playwright.dev/community/welcome) for general questions. If you think this is a bug in Playwright, please open a new issue and follow the bug template.
