### ISSUE TITLE
[Question] Why is 'setDownloadBehavior' required for connect_over_cdp? Any workaround?

### ISSUE THREAD

**Issue by LFMM-33** [microsoft/playwright#30383]
Hello to all,

Sorry to bother here with a question. I added the same question in Discord but after a week, noone has answered so I'm trying luck here. Sorry for the spam.

I'm working on developing tests E2E for a web desktop application that uses Qt as  its base for UI. The Qt version we are deploying uses Chromium v108.0.5359.71  as browser and we've successfully developed tests using ChromeDriver+Selenium but we are interested on transitioning to Playwright.

The issue we are having, also stated in the following comment in Github (https://github.com/microsoft/playwright/issues/10927#issuecomment-1534222212) is that for some reason we aren't able to connect over CDP because the 'Browser.setDownloadBehavior' request is failing (file node_modules/playwright-core/lib/server/chromium/crBrowser.js -> _initialize function)

```
if (this._browser.options.name !== 'electron' && this._browser.options.name !== 'clank' && this._options.acceptDownloads !== 'internal-browser-default') {
      promises.push(this._browser._session.send('Browser.setDownloadBehavior', {
        behavior: this._options.acceptDownloads === 'accept' ? 'allowAndName' : 'deny',
        browserContextId: this._browserContextId,
        downloadPath: this._browser.options.downloadsPath,
        eventsEnabled: true
      }));
    }
```

I enter this condition because our browser seems to have this._options.acceptDownloads = 'accept'. Before, if you see the comment linked above, the only restrictions were electron and clank.

If I comment this CDP request, Playwright is able to connect and my tests work as expected. 

So, my question would be why is this a requirement and if anyone knows any workaround / a way to set Chromium browser's "acceptDownloads" option to the expected value "internal-browser-default" so I can overpass this?

Thank you for reading 

- [X] I understand

**Comment by mxschmitt** [comment]
Filed upstream bug: https://github.com/chromiumembedded/cef/issues/3684
Filed upstream PR: https://bitbucket.org/chromiumembedded/cef/pull-requests/748

**Comment by dgozman** [comment]
Closing in favor of https://github.com/chromiumembedded/cef/issues/3684, since there is no action item on Playwright side.

**Comment by mxschmitt** [comment]
@LFMM-33 would that work for you? https://github.com/chromiumembedded/cef/issues/3684#issuecomment-2075545934

Since the CEF Alloy mode is deprecated and gets removed soon the solution above seems to work as of today.

**Comment by mxschmitt** [comment]
@LFMM-33 CEF can be launched in two modes. Alloy which is deprecated and gets removed from CEF soon and native Chrome mode. The native Chrome mode. Depending on your implementation, it might be `--enable-chrome-runtime` or `CefSettings.chrome_runtime = true`.

And yes, it requires a recent CEF I think.

**Comment by LFMM-33** [comment]
@mxschmitt Thank you for the clarification. I'll look into it with a C++ dev. 

Any indication / any check that could confirm if "Chrome runtime" is indeed enabled? 
Anything I could check in the Devtools? Just looking to get more info.

**Comment by mxschmitt** [comment]
I'm unfortunately not very familiar with CEF, this might be helpful: https://github.com/chromiumembedded/cef/issues/3685
