### ISSUE TITLE
[Bug]: Arch Linux & your OS is not officially supported by Playwright

### ISSUE THREAD

**Issue by sharma-shray** [microsoft/playwright#30393]
### Version

1.43.1

### Steps to reproduce

npm install playwright@latest

### Expected behavior

The problem is solved by logging in as a super user and use 
npx playwright install --with-deps

### Actual behavior

Installation error 

### Additional context

BEWARE: your OS is not officially supported by Playwright; installing dependencies for ubuntu20.04-x64 as a fallback.

sh: line 1: apt-get: command not found
Failed to install browsers
Error: Installation process exited with code: 127
Error: Command failed: npx playwright install --with-deps
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)

### Environment

```shell
System:
    OS: Linux 6.5 Manjaro Linux
    CPU: (4) x64 AMD Ryzen
    Memory: 3.92 GB / 7.70 GB
    Container: Yes
  Binaries:
    Node: 21.6.2 - /usr/bin/node
    Yarn: 1.22.21 - /usr/bin/yarn
    npm: 10.5.2 - /usr/bin/npm
  IDEs:
    VSCode: 1.87.0 - /usr/bin/code
  Languages:
    Bash: 5.2.26 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.43.1 => 1.43.1
```

**Comment by yury-s** [comment]
Only Ubuntu and Debian distributions are officially supported, see [system requirements](https://playwright.dev/docs/intro#system-requirements). Folding into https://github.com/microsoft/playwright/issues/8100

**Comment by kuchaguangjie** [comment]
I'm using linux mint mate, which is based on ubuntu 24.04, and get error:
> BEWARE: your OS is not officially supported by Playwright; 

Anyway to make the cmd think I'm using ubuntu, and go ahead to install ?

**Comment by kuchaguangjie** [comment]
> I'm using linux mint mate, which is based on ubuntu 24.04, and get error:
> 
> > BEWARE: your OS is not officially supported by Playwright;
> 
> Anyway to make the cmd think I'm using ubuntu, and go ahead to install ?

Ohh, seems the install succeed, it just given warning.
