### ISSUE TITLE
[Bug]: Missing projects/tests when using multiple projects (folders) from 1.43.x

### ISSUE THREAD

**Issue by andrzej-hanusek-tg** [microsoft/playwright#30396]
### Version

1.43.1

### Steps to reproduce

1. Folder structure:

<img width="634" alt="Screenshot 2024-04-17 at 13 21 37" src="https://github.com/microsoft/playwright/assets/125553790/25dd723c-8abe-4843-aacf-285eac883c1a">

2. Playwright config:

```
export default defineConfig({
  ...
  /* Configure projects for major browsers */
  projects: [
    // all tests except send money
    {
      name: 'setup',
      testDir: './utils',
      testMatch: /auth.setup\.ts/,
    },
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['setup'],
      testDir: './tests/all-tests',
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
      dependencies: ['setup'],
      testDir: './tests/all-tests',
    },
    // send money tests
    {
      name: 'send-money-setup',
      testDir: './utils',
      testMatch: /send-money-auth.setup\.ts/,
    },
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['send-money-setup'],
      testDir: './tests/send-money-tests',
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
      dependencies: ['send-money-setup'],
      testDir: './tests/send-money-tests',
    },
    ...
```    

### Expected behavior

In previous version (1.42.1) UI mode / tests runner has all tests grouped by projects:

<img width="254" alt="Screenshot 2024-04-17 at 13 19 53" src="https://github.com/microsoft/playwright/assets/125553790/3340ba74-ce72-4be2-b04d-02de51426d54">

### Actual behavior

In latest version (1.43.1) UI mode / tests runner contains only one folder, set unique name for project doesn't change anything.

<img width="256" alt="Screenshot 2024-04-17 at 13 18 18" src="https://github.com/microsoft/playwright/assets/125553790/c8437738-ca0c-4f74-801a-caf9e72e9e8a">

### Environment

```shell
System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 82.56 MB / 32.00 GB
  Binaries:
    Node: 19.7.0 - ~/.nvm/versions/node/v19.7.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.7.0/bin/yarn
    npm: 9.6.1 - ~/.nvm/versions/node/v19.7.0/bin/npm
    pnpm: 8.15.7 - /opt/homebrew/bin/pnpm
    bun: 1.0.19 - ~/.bun/bin/bun
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by yury-s** [comment]
This has something to do with the projects with clashing names, I can reproduce it with this https://github.com/yury-s/bug-30396 but not with unique names https://github.com/yury-s/bug-30396/tree/unique-project-names. It is a regression in 1.43.
