### ISSUE TITLE
[Bug]: Windows: Error with emoji in filename: `Error: ENOENT: no such file or directory, access`

### ISSUE THREAD

**Issue by m4r71n** [microsoft/playwright#30398]
### Version

1.43.1

### Steps to reproduce

1. `git clone https://github.com/m4r71n/playwright-windows-emoji.git`
2. `npm i`
3. `npx playwright test`

### Expected behavior

No error

### Actual behavior

```
Error: ENOENT: no such file or directory, access

Error: locator.setInputFiles: Test ended.
```

### Additional context

With Playwright 1.42.1 there is no error.

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900K
    Memory: 29.55 GB / 63.63 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @playwright/test: 1.43.1 => 1.43.1
```

**Comment by yury-s** [comment]
This is a node.js problem, see https://github.com/microsoft/playwright/issues/29606 and https://github.com/microsoft/playwright/issues/29606#issuecomment-1968027319 in particular. It's already fixed in Node 21 but they are not backporting the fix.

**Comment by m4r71n** [comment]
Thanks, but do you have any idea why it is working with Playwright 1.42.1 without changing the node.js version?

**Comment by m4r71n** [comment]
Strange but I can confirm, that there is no error with node.js 21.7.3.
