### ISSUE TITLE
[Bug]: @tags added using new syntax as per v1.42 is not shown in UI mode

### ISSUE THREAD

**Issue by vijayravindran90** [microsoft/playwright#30394]
### Version

v1.42.1

### Steps to reproduce

- Created a new spec file with following code snippet
```
import { Browser, expect, test} from '@playwright/test';
test.describe('Browse Page Test',()=>{
  
    const consoleErrors: Error[] = [];
    const pageErrorListener = (error: Error) => consoleErrors.push(error);
    test.beforeEach(async ({ page,context }) => {
        page.on(`pageerror`, pageErrorListener);
    });
        // Listen for any errors in the response or console    
test('Navigate to Browser page',{tag:['@browse']},async({page,request})=>{
    await page.goto('https://google.com');
});
  // Clean up any listeners
  test.afterEach(async ({ page }) => {
    page.removeListener(`pageerror`, pageErrorListener);
  });
});
```

- In the UI mode the added test is shown, whereas filter by the @browser tags returns no result and the tags are not shown next to the test
- Whereas the @tags where shown if we use the older approach of adding tags next to description

### Expected behavior

I should be able to filter the test by tags and the test should be returned in results on UI mode
I should be able to see the @tags next to the test on UI mode

### Actual behavior

![image](https://github.com/microsoft/playwright/assets/108650169/d81e0212-d9a3-42e0-87c9-f2e2b5c33a65)

### Additional context

Code Snippet

![image](https://github.com/microsoft/playwright/assets/108650169/35fd8ea1-ec35-403f-bb4f-ea4b0e9ef371)

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12800H
    Memory: 1.60 GB / 15.69 GB
  Binaries:
    Node: 18.19.0 - ~\Downloads\node-v18.19.0-win-x64 (1)\node-v18.19.0-win-x64\node.EXE
    npm: 10.2.3 - ~\Downloads\node-v18.19.0-win-x64 (1)\node-v18.19.0-win-x64\npm.CMD
  IDEs:
    VSCode: 1.88.0 - C:\Users\Vijay.Ravindran\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.42.0 => 1.42.1
    playwright: ^1.17.2 => 1.42.1
    playwright-fluent: 1.39.0 => 1.39.0
    playwright-lighthouse: ^2.2.2 => 2.2.2
```

**Comment by mxschmitt** [comment]
You need to update to v1.43.1 for this feature.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
