### ISSUE TITLE
[Bug]: Intermittent Timeout Errors with Playwright's page.goto Function in Visual Regression Tests

### ISSUE THREAD

**Issue by KunalOjha** [microsoft/playwright#30406]
Playwright version: 1.43.1

We are encountering sporadic timeout errors during the execution of our visual regression tests, which are implemented using Playwright. The issue arises specifically when the page.goto() function is invoked. This function is responsible for navigating to a specific page and then waiting for the 'DOMContentLoaded' event to be fired. (I've tried omitting this waitUntil value and increasing the timeout as well which also yield the same error).

It's important to note that we utilize a wsEndpoint to establish a WebSocket connection to the LambdaTest Cloud Server, which allows us to run a local instance of our application and capture screenshots to its server. ([ref](https://www.lambdatest.com/support/docs/playwright-visual-regression/)):

```
  const browser = await chromium.connect({
    wsEndpoint: `wss://cdp.lambdatest.com/playwright`,
  });
  const page = await browser.newPage();

    await page.setViewportSize({ width, height });
    await page.goto(url, { waitUntil: 'domcontentloaded', timeout: 600000 });
```

The error message is as follows:

```
page.goto: net::ERR_TIMED_OUT at http://localhost.some-example.com
Call log:
  - navigating to "http://localhost.some-example.com", waiting until "domcontentloaded"
  ...
  name: 'Error'
}
```

The page loads fine when accessed through a browser, suggesting that the issue might be related to the test environment or the way Playwright handles page navigation. Not sure why this times out almost instantaneously.. any suggestions would be appreciated.

Edit: I've tried adding `DEBUG=pw:protocol ` env variable, but i don't get any logs

**Comment by yury-s** [comment]
> It's important to note that we utilize a wsEndpoint to establish a WebSocket connection to the LambdaTest Cloud Server, which allows us to run a local instance of our application and capture screenshots to its server. ([ref](https://www.lambdatest.com/support/docs/playwright-visual-regression/)):

Sounds like a network issue on that service. Does it reproduce with local browser? If you think this is a playwright bug, please follow our bug template and provide a reproduction which we could run locally to see the issue.

**Comment by yury-s** [comment]
> If you think this is a playwright bug, please follow our bug template and provide a reproduction which we could run locally to see the issue.

^^ we need a reproduction
