### ISSUE TITLE
Chromium unable to play videos

### ISSUE THREAD

**Issue by kero990** [microsoft/playwright#30409]
Hi, it's an honor to come across this project. I'm using an arm64 Linux device, and my system version is limited to Debian 10. The Chromium you compiled is one of the few I could find that runs on my device. However, it can't play any online videos on my device. Some websites prompt that the browser is not supported, or that the HTML5 player is not supported, etc. This shouldn't happen with Chromium. Additionally, there's Chromium v83 from the Debian 10 repository and the latest version installed via Snap on my device, and neither of them has this issue. Is this a compilation issue or am I doing something wrong? This is just a zip archive, so I should be able to run it directly or execute the .sh file, right?

**Comment by yury-s** [comment]
Our [minimal](https://playwright.dev/docs/intro#system-requirements) supported Debian version is 11. So this is out of scope for the project.

Note also, that open source build we ship doesn't include proprietary codecs (e.g. h.264) that may be required to play the video, to use them you'll need a vendor build such as MS Edge or Google Chrome.

>  This is just a zip archive, so I should be able to run it directly or execute the .sh file, right?

No. There are some binary dependencies that may not be met on older systems.

**Comment by kero990** [comment]
> Our [minimal](https://playwright.dev/docs/intro#system-requirements) supported Debian version is 11. So this is out of scope for the project.我们支持的最低Debian版本是11。所以这超出了项目的范围。
> 
> Note also, that open source build we ship doesn't include proprietary codecs (e.g. h.264) that may be required to play the video, to use them you'll need a vendor build such as MS Edge or Google Chrome.另请注意，我们提供的开源版本不包括播放视频所需的专有编解码器（例如h.264），要使用它们，您需要一个供应商版本，如MS Edge或Google Chrome。
> 
> > This is just a zip archive, so I should be able to run it directly or execute the .sh file, right?这只是一个zip压缩包，所以我应该能够直接运行它或执行. sh文件，对吗？
> 
> No. There are some binary dependencies that may not be met on older systems.号有些二进制依赖性在旧系统上可能无法满足。

Oh, I haven't encountered binary issues. It's quite common, I often have to recompile various things to avoid problems with too low GLIBC versions. That's why I was thrilled to find your Chromium. But unfortunately, it's incomplete. Surprisingly, Firefox can play videos just fine, and it seems your compilation strategy for these two browsers is inconsistent.

Furthermore, it's evident that there are no commercial versions of Chrome and Edge on arm64 Linux. Since you're a Microsoft project, you don't even have Edge on arm64. So Chromium is my only choice. But getting the latest version isn't easy.

Anyway, thank you for your response.
