### ISSUE TITLE
[Feature]: pytest-playwright - auto slow down considering cpu load

### ISSUE THREAD

**Issue by andreabisello** [microsoft/playwright#30401]
### 🚀 Feature Request

generally in large test suites you will use pytest-xdist to parallelize test executions.
let's suppose you are using playwright for browser testing (so not api testing).
webpage could be so heavy if full of heavy javascript or huge html load.
for sure, you could decrease the number of executors,
but maybe your testsuite is a mixed api - webpages so you would like to rush full speed if the system can handle that or slow down if it's too much loaded, to avoid flakyness.
Also, even using a single executor, even without using xdist, some parts of the website under test can be so heavy to makes your execution flaky.
I was thinking maybe it could be possible to take advantages of the playwright slow-mo https://playwright.dev/python/docs/test-runners#configure-slow-mo to be activated at runtime when the average system load (cpu load) is high for too much time. for detecting average system load i would use psutil to check something like psutil.cpu_percent every some seconds, and then adapt the slow-mo increasing the "slow" if cpu load is high and reducing if it is low.

what do you think about that?

### Example

pytest --auto-slow-down 

#every some seconds 

actual_slow_down = 0

if cpu load > 90 in the latest 5 seconds
actual_slow_down = 100
else
actual_slow_down  = 0

### Motivation

this should reduce flakyness that can occur when system is too much overloaded

**Comment by yury-s** [comment]
> for sure, you could decrease the number of executors,

Yes, this is the recommended way.

> but maybe your testsuite is a mixed api - webpages so you would like to rush full speed if the system can handle that or slow down if it's too much loaded, to avoid flakyness.

There is an open feature request for this https://github.com/microsoft/playwright/issues/21970

> Also, even using a single executor, even without using xdist, some parts of the website under test can be so heavy to makes your execution flaky.

In that case you should either add more resources to the server or increase the timeouts in the test.

Closing as there is an open feature request tracking a part of this request and alternative solutions for the rest.
