### ISSUE TITLE
[Bug]: Results of test run in UI Mode disappear after short delay with "Did not run" message

### ISSUE THREAD

**Issue by karlhorky** [microsoft/playwright#30404]
### Version

1.43.0

### Steps to reproduce

1. Run a test using UI mode (`playwright test --ui`)
2. After test errors or is successful, the results disappear with the message "Did not run" 💥

https://github.com/microsoft/playwright/assets/1935696/49e9ae86-0ebb-4625-a10c-901e109270c4

### Expected behavior

The test results shouldn't be cleared / disappear

### Actual behavior

The test results disappear

### Environment

```shell
System:
    OS: macOS 14.4.1
    Memory: 138.88 MB / 16.00 GB
  Binaries:
    Node: 20.12.2 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.5.2 - /opt/homebrew/bin/npm
    pnpm: 9.0.2 - /opt/homebrew/bin/pnpm
    bun: 1.1.4 - /opt/homebrew/bin/bun
  Languages:
    Bash: 5.2.0 - /opt/homebrew/bin/bash
```

**Comment by karlhorky** [comment]
Oh, looks like @dtokarczyk reported this same issue over in https://github.com/microsoft/playwright/issues/30339 and @mxschmitt fixed in https://github.com/microsoft/playwright/pull/30312 🙌

I can confirm that `@playwright/test@1.43.1` fixes the issue for us.

Closing

**Comment by VisualFinesse** [comment]
I'd like to open this ticket back up since I'm getting this exact error in 9.6.7

**Comment by TobiasMende** [comment]
I have the same issue with Playwright 1.46.0. – Can you reopen this issue @karlhorky or shall we create a new issue?

**Comment by TobiasMende** [comment]
Update: I found the reason for this behaviour by running the suit without the `--ui` flag. In my case, I had a duplicate test name. This error leads to this behaviour without any warning/notification.

**Comment by karlhorky** [comment]
@TobiasMende can you confirm that it is the exact same behavior that is shown in the video?

Eg.

1. Test runs
2. Results are shown
3. Results disappear after short delay
4. "Did not run" message is shown

If you could create a video confirming this for 1.46.0 (eg. with [Loom](https://www.loom.com/) or [ScreenToGif (Windows only)](https://www.screentogif.com/) [Kap (macOS only)](https://getkap.co/)) and post it here (make sure to show the version number and the behavior), then I can reopen.

**Comment by TobiasMende** [comment]
@karlhorky sure thing. I have recorded a small video to demo this (in the audio I explain it, as well)


https://github.com/user-attachments/assets/dc7bfdf0-e8d3-4998-b942-1690f79de69f

If you want a minimal example:
1. Create a suite inside a file that has two tests with the same name.
2. Create other tests in the file

The behavior with Playwright UI for me is: After I ran the suite with the duplicate name in it, I get the above behaviour. After that, no other tests can be executed.

Hope this helps. :-)

**Comment by karlhorky** [comment]
Nice, thanks for taking the video - it's pretty close to the behavior!

It's missing the key points 2. "Results are shown" and 3. "Results disappear after short delay" though - so probably good to open a separate issue for that.

**Comment by TobiasMende** [comment]
Ah you are right. Here is the new issue: https://github.com/microsoft/playwright/issues/32093

**Comment by WarrenMfg** [comment]
Duplicate browsers in the config's `projects` array will also demonstrate similar behavior.

**Comment by El-Burro** [comment]
I managed to get the same issue as originally stated: run a test, see some steps being taken, then all steps are cleared and the test ends in "Did not run".

Can you please reopen this @karlhorky ?

https://github.com/user-attachments/assets/7436bb03-7f66-4b04-b701-9d92d6d967a9

**Comment by karlhorky** [comment]
@El-Burro I cannot reproduce on my side with newer Playwright versions, and I don't know your environment.

I guess probably best for you to open a new issue?
