### ISSUE TITLE
[Bug]: CLI --grep does not accept more arguments separated by whitespace

### ISSUE THREAD

**Issue by pawelgolder** [microsoft/playwright#30413]
### Version

1.43.0

### Steps to reproduce

1. Two test files testFile1.spec.ts and testFile2.spec.ts
2. Try to run all or list tests with --grep option: 
npx playwright test --list --grep testFile1 testFile2

### Expected behavior

I expect to all test from testFile1 and testFile2 to be run or listed

### Actual behavior

Error: No tests found.
Make sure that arguments are regular expressions matching test files.
You may need to escape symbols like "$" or "*" and quote the arguments.
Listing tests:
Total: 0 tests in 0 files

### Additional context

Documentation says:
"The regular expression will be tested against the string that consists of the test file name, test.describe titles if any, test title and all test tags, **separated by spaces,** e.g. my-test.spec.ts my-suite my-test @smoke." 
https://playwright.dev/docs/test-cli

### Environment

```shell
System:
  OS: Windows 11 10.0.22631
  CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
  Memory: 2.73 GB / 15.64 GB
Binaries:
  Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
  Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
  npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
IDEs:
  VSCode: 1.88.1
Languages:
    Bash: 5.0.17 - C:\WINDOWS\system32\bash.EXE
  npmPackages:
    @playwright/test: ^1.43.1 => 1.43.1 
    playwright: ^1.43.1 => 1.43.1
```

**Comment by pawelgolder** [comment]
the same with --grep-invert opt

**Comment by yury-s** [comment]
`--grep` matches test titles, if you need to match file names, you can pass them directly:

```sh
npx playwright test --list testFile1 testFile2
```

With grep to pass alternative options you can use `|`, see [this doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Disjunction):

```sh
npx playwright test --list  --grep 'check|should click'
```
