### ISSUE TITLE
[Bug]: click animations blocks the click action 

### ISSUE THREAD

**Issue by HamzaMiz** [microsoft/playwright#30427]
### Version

1.43

### Steps to reproduce

clone my repo : https://github.com/HamzaMiz/PlaywrightBug.git
node install 
launch test test mb2-1073 
check the trace 

### Expected behavior

the button loard more  should be clicked 

### Actual behavior

only the animation of click is happening 
check the trace 

### Additional context

[trace.zip](https://github.com/microsoft/playwright/files/15040868/trace.zip)

### Environment

```shell
System:
    OS: macOS 14.1
    CPU: (8) arm64 Apple M3
    Memory: 51.77 MB / 16.00 GB
  Binaries:
    Node: 20.10.0 - /usr/local/bin/node
    npm: 10.5.0 - /usr/local/bin/npm
    pnpm: 9.0.4 - /usr/local/bin/pnpm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.43.1 => 1.43.1
```

**Comment by yury-s** [comment]
This is a bug in the app. Playwright clicks on the visible element, but apparently it does not have event handlers yet. This is a [hydration problem](https://playwright.dev/docs/navigations#hydration) and this would be an issue for a very fast user (or slow machine) too. Changing the code like this makes the test pass:

```diff
diff --git a/tests/pages/consumption/consumption-page.ts b/tests/pages/consumption/consumption-page.ts
index 617b1e8..11e23ee 100644
--- a/tests/pages/consumption/consumption-page.ts
+++ b/tests/pages/consumption/consumption-page.ts
@@ -75,7 +75,9 @@ export async function clickOnLoadMoreTransactionsUntilFullListIsOpen() {
     console.log('The "Load More" button is Hidden .');
   } else {
     while (!(await loadMoreTransactionButton().isHidden())) {
+      await new Promise(f => setTimeout(f, 1000));
       await click(loadMoreTransactionButton(), { force: true, delay: 500, button: 'left', timeout: 2000 });
+      await new Promise(f => setTimeout(f, 1000));
     }
   }
   await expectElementToBeHidden(loadMoreTransactionButton());
```

you need to fix the app (preferred as it would fix the user facing bug) or update the test to wait for the event handlers to be added before clicking.

**Comment by HamzaMiz** [comment]
thanks for the solution and the insight
