### ISSUE TITLE
[Feature]: ability to remove function exposed through exposeBinding

### ISSUE THREAD

**Issue by Mattwmaster58** [microsoft/playwright#30422]
### 🚀 Feature Request

puppeteer has this feature which we would find useful:
 - https://pptr.dev/api/puppeteer.page.removeexposedfunction
 - https://github.com/puppeteer/puppeteer/issues/10223

### Example

- when a function is no longer desired to be exposed on the web page

### Motivation

It is a bit tedious to write workarounds for this shortcoming, and would be pretty convenient to have such a functionality in the API. This would bring parity with other event listener APIs in Playwright, eg Page.on, which allows removing event listeners with Page.off

**Comment by yury-s** [comment]
We recommend creating a new context when you no longer need the bindings. For edge cases you can always disable the bindings via if conditions in their code. Closing as there are no plans to add such API.

Related https://github.com/microsoft/playwright/issues/17836
