### ISSUE TITLE
[Bug]: addLocatorHandler blocks

### ISSUE THREAD

**Issue by ruifigueira** [microsoft/playwright#30424]
### Version

1.43.1

### Steps to reproduce

Run the following test:

```ts
test("play wordle", async ({ page }) => {
    page.addLocatorHandler(page.getByRole('heading', { name: 'How To Play' }), async () => {
        await page.getByLabel('Close').click();
    });

    await page.goto('https://www.nytimes.com/games/wordle/index.html');
    await page.getByTestId('Play').click();
    for (const letter of 'salet')
        await page.locator(`[data-key=${letter}]`).click();
});
```

### Expected behavior

It should close the help dialog and type **SALET**

### Actual behavior

It closes the help dialog and blocks, not typing any letter. I'm attaching the captured trace:

[trace.zip](https://github.com/microsoft/playwright/files/15031223/trace.zip)

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 11.32 GB / 31.74 GB
  Binaries:
    Node: 18.16.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    npm: 9.7.1 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
    pnpm: 8.15.4 - ~\AppData\Local\pnpm\pnpm.EXE
  IDEs:
    VSCode: 1.88.1 - C:\Users\rui.figueira\scoop\apps\vscode\current\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.43.1 => 1.43.1
```

**Comment by ruifigueira** [comment]
I missed an `await`. New version of the test:

```js
```ts
test("play wordle", async ({ page }) => {
    await page.addLocatorHandler(page.getByRole('heading', { name: 'How To Play' }), async () => {
        await page.getByLabel('Close').click();
    });

    await page.goto('https://www.nytimes.com/games/wordle/index.html');
    await page.getByTestId('Play').click();
    for (const letter of 'salet')
        await page.locator(`[data-key=${letter}]`).click();
});
```

And still failing, but keeps failing. Trace: 
[trace_v2.zip](https://github.com/microsoft/playwright/files/15031286/trace_v2.zip)

**Comment by ruifigueira** [comment]
Ok, I figured it out. The callback was being called twice because clicking the Close button was not closing the dialog immediately.

To fix it, I have to wait for the locator to disappear:

```js
test('play wordle', async ({ page }) => {
  await page.addLocatorHandler(page.getByRole('heading', { name: 'How To Play' }), async () => {
    await page.getByLabel('Close').click();
    await page.getByRole('heading', { name: 'How To Play' }).waitFor({ state: 'hidden' });
  });

  await page.goto('https://www.nytimes.com/games/wordle/index.html');
  await page.getByTestId('Play').click();
  for (const letter of 'salet')
    await page.locator(`[data-key=${letter}]`).click();
});
```

**Comment by cyrus-afshari** [comment]
> Ok, I figured it out. The callback was being called twice because clicking the Close button was not closing the dialog immediately.
> 
> To fix it, I have to wait for the locator to disappear:
> 
> ```js
> test('play wordle', async ({ page }) => {
>   await page.addLocatorHandler(page.getByRole('heading', { name: 'How To Play' }), async () => {
>     await page.getByLabel('Close').click();
>     await page.getByRole('heading', { name: 'How To Play' }).waitFor({ state: 'hidden' });
>   });
> 
>   await page.goto('https://www.nytimes.com/games/wordle/index.html');
>   await page.getByTestId('Play').click();
>   for (const letter of 'salet')
>     await page.locator(`[data-key=${letter}]`).click();
> });
> ```
> 
> This pattern happens a lot due to fadeout animations. Maybe it would be worth to add a paragraph explaining this in the documentation.

You spared me a lot of time and frustration! Thanks for sharing this, I was having the same issue and adding the `waitFor({ state: 'hidden' })` solved it for me. Playwright's documentation on `addLocatorHandler()` should include your suggestion!

**Comment by dgozman** [comment]
@cyrus-afshari Implicit `waitFor` at the end is now the default behavior of `addLocatorHandler()`. If that does not work for you, could you please file a new issue by filling in the "Bug Report" template and provide a repro?

**Comment by cyrus-afshari** [comment]
> @cyrus-afshari Implicit `waitFor` at the end is now the default behavior of `addLocatorHandler()`. If that does not work for you, could you please file a new issue by filling in the "Bug Report" template and provide a repro?

I am on version 1.43.1, so I believe I don't have that new default behavior
