### ISSUE TITLE
Unable to Enable Sandbox for Chromium on Ubuntu 22.04

### ISSUE THREAD

**Issue by amirfarzamnia** [microsoft/playwright#30439]
I'm encountering issues trying to enable sandboxing for Chromium on Ubuntu 22.04. It's displaying the following error message:

```
Chromium sandboxing failed!
================================
To workaround sandboxing issues, do either of the following:
  - (preferred): Configure environment to support sandboxing: https://playwright.dev/docs/troubleshooting
  - (alternative): Launch Chromium without sandbox using 'chromiumSandbox: false' option
================================
```

I need sandboxing for security reasons, but I'm unable to get it working on Ubuntu.

**Comment by yury-s** [comment]
This doesn't sound like a bug or feature request, please use our [community resources](https://playwright.dev/community/welcome) for general questions. If you think this is a bug in Playwright, please open a new issue and follow the bug template.
