### ISSUE TITLE
[Docs]: Playwright Troubleshooting

### ISSUE THREAD

**Issue by amirfarzamnia** [microsoft/playwright#30446]
### Page(s)

https://playwright.dev/docs/troubleshooting

### Description

When using the sandboxing feature on Ubuntu, it returns the below error message:

```plaintext
Chromium sandboxing failed!
================================
To workaround sandboxing issues, do either of the following:
  - (preferred): Configure environment to support sandboxing: https://playwright.dev/docs/troubleshooting
  - (alternative): Launch Chromium without sandbox using 'chromiumSandbox: false' option
================================
```

Which links to an invalid address.

**Comment by amirfarzamnia** [comment]
BTW, can anyone help me fix the issue with sandboxing on Ubuntu?

**Comment by yury-s** [comment]
That page was deprecated and removed in https://github.com/microsoft/playwright/pull/23454, we should update the error message.
