### ISSUE TITLE
[Feature]: SnapshotTab UI polish

### ISSUE THREAD

**Issue by chenshuichao** [microsoft/playwright#30450]
### 🚀 Feature Request

make the SnapshotTab more like browser navigation !
now is :
<img width="782" alt="Screen Shot 2024-04-20 at 21 20 28" src="https://github.com/microsoft/playwright/assets/77186544/4c315ac1-beb5-4b8d-8bed-9d78acc8f04a">

suggestion is:
<img width="973" alt="Screen Shot 2024-04-20 at 21 28 37" src="https://github.com/microsoft/playwright/assets/77186544/bc4302e4-94c1-46c9-a63c-d6da9076ec92">

### Motivation

make the SnapshotTab more like browser navigation !

**Comment by pavelfeldman** [comment]
This won't work too nice for our mobile scenarios. The window frame that you see has a ratio matching the emulated one during testing and fitting controls there will compromise their UX.
