### ISSUE TITLE
[Feature]: Add Configuration Option to Mark Test Suite as Failed When Containing Flaky Tests

### ISSUE THREAD

**Issue by TomerBin** [microsoft/playwright#30457]
### Feature Description
Currently, Playwright supports a "retries" configuration where tests that initially fail but subsequently pass are marked as "flaky". When such flaky tests exist, the overall test suite is considered successful. I propose adding a configuration option that allows marking the entire test suite as failed if it contains any flaky tests.

### Proposed Solution
Introduce a new configuration parameter, such as `failOnFlakyTests`, which when set to `true`, will cause the entire test suite to fail if any tests are marked as flaky. This will help teams differentiate between suites with consistent test failures and those with flaky tests, promoting more robust testing practices.

### Impact
This enhancement will allow developers and QA teams to enforce stricter quality controls by treating flaky tests as critical errors, ensuring that they receive immediate attention.

Thank you for considering this feature.

### Example

```json
{
  "failOnFlakyTests": true,
  "retries": 2
}
```

### Motivation

This feature would be beneficial for maintaining high code quality in continuous integration (CI) environments. By enabling this option, teams can ensure that flaky tests are highlighted and addressed promptly, rather than allowing them to degrade the reliability of the test suite over time.

**Comment by anudeepreddy** [comment]
Hey @pavelfeldman, I would like to take this up. This would be my first contribution to this project. Can you please point me in the right direction to help me get started on this.

**Comment by TomerBin** [comment]
Thank you @Joe-Hendley! Highly appreciated
