### ISSUE TITLE
[Feature]: why not just ignore the event to make our recording continued

### ISSUE THREAD

**Issue by chenshuichao** [microsoft/playwright#30451]
### 🚀 Feature Request

When I must drag the element to verify the human, the codegen just make me broken ,
why not just ignore the event to make our recording continued

### Motivation

<img width="556" alt="Screen Shot 2024-04-20 at 21 51 26" src="https://github.com/microsoft/playwright/assets/77186544/4b9f5db4-256c-4781-8d94-8e7c87e1c647">

**Comment by pavelfeldman** [comment]
The answer to this question is that if we ignore it, we won't be able to replay it. And we'd like to have a good ration of replay-able scenarios recorded with the codegen.

**Comment by chensce** [comment]
so，we must support the codegen for drag n drop in recorder.

**Comment by chensce** [comment]
We can codegen for dragto the same as codegen for assert visibility.
the interaction is :
1)click the icon "dragto" 
2)popup the dialog (include src locator and dest locator)
3)click src locator,then selecting the drag element
4)click dest locator,then selecting the destion element

**Comment by chensce** [comment]
not so perfect,but it just work
@pavelfeldman
