### ISSUE TITLE
[Regression]: Missing requests on trace file using page.Context.Tracing.StartAsync 

### ISSUE THREAD

**Issue by ChristianPla-Ascensus** [microsoft/playwright#30460]
### Last Good Version

1.42.0

### First Bad Version

1.43.0

### Steps to reproduce

Reference the issue closed
[https://github.com/microsoft/playwright/issues/30397](https://github.com/microsoft/playwright/issues/30397

Review the trace differences on this comment: 
Trace differences: [https://github.com/microsoft/playwright/issues/30397#issuecomment-2070088778](https://github.com/microsoft/playwright/issues/30397#issuecomment-2070088778)

The method used are:
```
public static async Task StartNetworkTrace(IPage page, string filePath)
        {          
            await page.Context.Tracing.StartAsync(new TracingStartOptions
            {
                Screenshots = false,
                Snapshots = false,

            });
        }

        public static async Task StopNetworkTrace(IPage page, string filePath)
        {
            var context = page.Context;

            if (File.Exists(filePath))
            {
                File.Delete(filePath);
            }

            await context.Tracing.StopAsync(new()
            {
                Path = filePath
            });
        })
```

### Expected behavior

The requests with initiatior other are not kept in the trace file anymore.

### Actual behavior

The trace works as in previous version (up to 1.42.0)

### Environment

```shell
Windows 11 Playwright / C#
from 1.42.0 to 1.43.0
```

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/30397
