### ISSUE TITLE
[BUG] Browser doesnt get installed on Windows Server

### ISSUE THREAD

**Issue by SentoxAIO** [microsoft/playwright#3046]
**Context:**
- Playwright Version: "^1.2.1"
- Operating System: Windows Server
- Node version: v14.1.0.
- Browser: Firefox
- Extra: Installed via installed packed with electron-builder

**Error**
`(intermediate value) is not iterable` when starting browser instance

**Describe the bug**
When installing and running it locally everything works but once you try to run in on a Google Windows Server, it throws that error which basically says that no browser is intalled.

**Comment by aslushnikov** [comment]
@SentoxAIO how do I reproduce this? Can you lead me with a step-by-step description to reproduce this?

**Comment by SentoxAIO** [comment]
We're using playwright (playwright-firefox) in an electron app, when people use our app (packaged with electron-builder with playwright unpacked) on a windows server, playwright throws the "(intermediate value) is not iterable" error.

How to reproduce:

1. Open a Windows Server
2. Install playwright-firefox
3. Try to run it

**Comment by aslushnikov** [comment]
@SentoxAIO the essence of the problem seems to be in the playwright is packaged with electron-builder. Can you share more details on this?

**Comment by SentoxAIO** [comment]
There is not much more to say about it. Playwright is kept unpacked and the `PLAYWRIGHT_BROWSERS_PATH` is set to 0
![image](https://user-images.githubusercontent.com/57367608/88176917-4cf36880-cc28-11ea-96b6-f62869b8a1c2.png)

**Comment by aslushnikov** [comment]
@SentoxAIO Well, if `PLAYWRIGHT_BROWSERS_PATH` is set to 0, then browsers won't get downloaded - that's expected. What's not working then?

> Let me know what kind of details you are looking for.

I have no experience with `electron-builder` and I've never dealt with packaging playwright there. I'll appreciate detailed steps on what should I do to repro things!

**Comment by dgozman** [comment]
Referencing #2539 for more context.

**Comment by SentoxAIO** [comment]
> I'll appreciate detailed steps on what I should do to repro things!

Its pretty easy to repro that. First you need an electron app which uses playwright-firefox (not as a window for the app, it should start a nightly session).  Then you add this to your package.json: 
`"build": {
  "appId": "your.id",
		"win": {
			"target": "nsis",
			"asar": true,
			"asarUnpack": [
				"node_modules/playwright-firefox/.local-browsers/**/*"
			]
		},
}` and then you just need to run `npm run electron-builder`.
To be honest I am not sure how to reproduce the error then since I never got it myself. But according to users it happened on Windows Servers but sometimes also locally.
