### ISSUE TITLE
[Bug]: codegen doesn't work well with some CSP directives 

### ISSUE THREAD

**Issue by ruifigueira** [microsoft/playwright#30469]
### Version

1.43.1

### Steps to reproduce

Run:

```
 npx playwright codegen https://content-security-policy.com/browser-test
```

### Expected behavior

Should display embedded toolbar in the recorded page, as well as properly highlight the elements. 

### Actual behavior

Toolbar is not shown and highlight position is wrong

### Additional context

PR #30366 is a fix proposal for the detected issues with inline styles and icon data URLs that can violate CSP directives 

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 9.59 GB / 31.74 GB
  Binaries:
    Node: 20.12.2 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    npm: 10.5.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
    pnpm: 8.15.4 - ~\AppData\Local\pnpm\pnpm.EXE
  IDEs:
    VSCode: 1.88.1 - C:\Users\rui.figueira\scoop\apps\vscode\current\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.43.1 => 1.43.1
```

**Comment by pavelfeldman** [comment]
Marking this a closed as I landed your PR https://github.com/microsoft/playwright/pull/30366, thanks!
