### ISSUE TITLE
Config time out is skipped for multiple tests running in parallel

### ISSUE THREAD

**Issue by Nickkolean2793** [microsoft/playwright#30477]
### Please do not submit this issue.

- [ ] I understand

**Comment by Nickkolean2793** [comment]
Hi

can you help me please correctly set the time out for tests when running multiple tests

my config settings:
export default defineConfig({
  timeout: 300000,

  /* Run tests in files in parallel */
  fullyParallel: true,

  
    // Opt out of parallel tests on CI.
  workers: process.env.CI ? 5 : undefined,



however when I run tests using
npx playwright test --headed


i got an error for each test:
 Test timeout of 30000ms exceeded.

looks like it considers only the default time out





thank you

Best regards!

**Comment by pavelfeldman** [comment]
Please use the BUG template if you think there is a bug in Playwright.
