### ISSUE TITLE
[Bug]: extra http headers are not sent with websocket connections on chromium and webkit browsers

### ISSUE THREAD

**Issue by I-Preetham** [microsoft/playwright#30472]
### Version

v1.43.1

### Steps to reproduce

1)Create a testcase by setting additional HTTP headers:
`test.use({ extraHTTPHeaders: { <token>:<token value>} })`

2)Write the actual testcase:
test("Demo of websocket issue", async({page}) =>{
    await page.goto("https://app.gosandy.io/");
})
3)Run this testcase from vs code and debug the browser.
4)Check the network tab for any websocket connection and go through it's request headers

### Expected behavior

When we inspect the request headers for the websocket connection we should ideally see the extraHTTPHeaders that was set in the testcase as an additional header.

### Actual behavior

The extra HTTP header is not being set in websocket connection. However, for all other HTTP requests we see the extra header being present.

### Additional context

This issue has already been mentioned in here : https://github.com/microsoft/playwright/issues/28948 .
I also see the fix being suggested in the comments. It would be great if we can have this fix being available in the upcoming release.

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 17.11 GB / 31.75 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE       
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.88.1 - C:\Users\prb\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.0.17 - C:\WINDOWS\system32\bash.EXE
  npmPackages:
    @playwright/test: ^1.43.1 => 1.43.1
```

**Comment by vEpiphyte** [comment]
I don't know why the original issue #28948 was closed by @pavelfeldman . It's still a valid bug and has divergent behaviors between browsers as documented by @mxschmitt. I'm still waiting for it to be resolved.

**Comment by pavelfeldman** [comment]
Folding into the restored https://github.com/microsoft/playwright/issues/28948

**Comment by vEpiphyte** [comment]
Thank you Pavel!
