### ISSUE TITLE
[Feature]: Configurable `networkidle` timeout (other than hard-coded 500ms)

### ISSUE THREAD

**Issue by ccll** [microsoft/playwright#30479]
### 🚀 Feature Request

Let user be able to configure the timeout of `networkidle`, instead of the hard-coded 500ms.

### Motivation

Similar feature requests have been rejected several times due to unclear use case in the history.
- #7856
- #22661

I think I may have a clear and valid use case worth discussing.

We are developing a to-B malicious detection software, that when given an URL, it opens the URL and detects if the page contains malicious content: password phishing input, downloadable trojan or virus, QR-code that leads to a malicious site, etc.

Since we don't control these sites like in end-to-end testing, we can't wait for a specific locator.
I think the most viable solution is `networkidle`, with a configurable timeout.

Any thoughts? Appreciated!

**Comment by pavelfeldman** [comment]
We strongly discourage the use of `networkidle`. It is inherently flaky, buy design, so your scripts are guaranteed to flake or break. It might be not obvious, but you can only use `networkidle` if you control the page and should never use it on a page from the wild. When you control the page you can make assumptions regarding its network organization, while on the real world pages you can't rely on anything. Every other real world page will have a long poll for ads, so networkidle will never occur. Or will have load / web vitals optimizations that would trigger networkidle before the page is loaded, etc etc.

There is no universal way to detect when the page is loaded. Search engines handle it with some success, exploring SEO will give some clue on how. Web vitals will give some interesting signals that can also be used. Virtual clock and other techniques are also worth exploring.

**Comment by ccll** [comment]
@pavelfeldman Thanks very much for your explanation and guidance. I will research the topics you mentioned.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
