### ISSUE TITLE
[Bug]: Anonymous describe is rendered in HTML report

### ISSUE THREAD

**Issue by vitalets** [microsoft/playwright#30475]
### Version

1.43.0

### Steps to reproduce

Please, follow the instructions in the readme: https://github.com/vitalets/playwright-issues/tree/anonymous-describe

### Expected behavior

HTML report does not render empty describe: `my suite › my test`

### Actual behavior

HTML report renders empty describe:
<img width="50%" src="https://github.com/microsoft/playwright/assets/1473072/b236689c-8cb4-40e1-88de-b9ea931c7e40">

### Environment

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 76.83 MB / 16.00 GB
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 7.27.1 - ~/Library/pnpm/pnpm
  IDEs:
    VSCode: 1.88.1 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.43.0 => 1.43.0
```

**Comment by dev-jonghoonpark** [comment]
Can I Contribute?
