### ISSUE TITLE
[Bug]: Config time out is skipped for multiple tests running in parallel

### ISSUE THREAD

**Issue by Nickkolean2793** [microsoft/playwright#30485]
### Version

latest

### Steps to reproduce

Hi

can you help me please correctly set the time out for tests when running multiple tests

my config settings:
export default defineConfig({
timeout: 300000,

/* Run tests in files in parallel */
fullyParallel: true,

// Opt out of parallel tests on CI.
workers: process.env.CI ? 5 : undefined,

however when I run tests using
npx playwright test --headed

i got an error for each test:
Test timeout of 30000ms exceeded.

looks like it considers only the default time out of 30 seconds, instead of config set time out of 300 seconds ...

could you suggest pls what i missed?

thank you

Best regards!

### Expected behavior

300 000 s time out

### Actual behavior

pls check

### Environment

```shell
windows, Chrome browser
```

**Comment by pavelfeldman** [comment]
Please use the bug template to file something we can reproduce.
