### ISSUE TITLE
[Bug]: Unable to see the websocket requests in the network tab of firefox browser

### ISSUE THREAD

**Issue by I-Preetham** [microsoft/playwright#30498]
### Version

v1.43.1

### Steps to reproduce

1)Create the following testcase : 
`test("Websocket issue testing", async({page}) =>{
    await page.goto("https://app.gosandy.io/");
})`

2)Run the following testcase with firefox browser through vs code. (Make sure to check the checkbox for "Show Browser").

3)Inspect the network tab of the firefox browser for any websocket connections.

### Expected behavior

The websocket requests are displayed in the network tab of the firefox browser.

### Actual behavior

The websocket requests cannot be seen in the network tab of the firefox browser, can be seen in chromium though.

Chromium browser:
![Chromium](https://github.com/microsoft/playwright/assets/167841289/5ffacf15-3376-4a8f-9762-b5639c002783)
Firefox browser:
![Firefox](https://github.com/microsoft/playwright/assets/167841289/1eee6728-8d45-443f-b22c-81fcec77cad1)

### Additional context

Though these requests cannot be seen, the application works without any issues. Meaning, the requests are being sent in the background but just cannot be seen in the network tab.

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 14.41 GB / 31.75 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.88.1 - C:\Users\prb\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.0.17 - C:\WINDOWS\system32\bash.EXE
  npmPackages:
    @playwright/test: ^1.43.1 => 1.43.1
```

**Comment by pavelfeldman** [comment]
This looks like something you want to bring up with Firefox team. I'm opening that page in FF and see no WS in their network panel.

**Comment by I-Preetham** [comment]
I do see the websocket request in the normal firefox browser. These requests are not seen when the firefox browser is launched from playwright.
![image](https://github.com/microsoft/playwright/assets/167841289/64222dde-5e7a-4e02-af6a-274fecbb101e)

**Comment by pavelfeldman** [comment]
Yep, I can repro, was opening using npx playwright out of habit.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by mbimbij** [comment]
I'm uping the issue, if that could help it move forward.

**Comment by sbounmy** [comment]
having the exat same issue. up too
