### ISSUE TITLE
[Bug]: "WebSocket error: connect ETIMEDOUT 127.0.0.1:53052" error when attempting to run tests with the vscode extension

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#30496]
### Version

1.43.1

### Steps to reproduce

1. run `npm init playwright@1.43.1`
2. run `code .`
3. install the Playwright Test for VSCode extension
4. click Help > Toggle Developer Tools, then open the console
5. in the test explorer, click debug on one of the tests

### Expected behavior

test runs

### Actual behavior

the test hangs forever with no output in the vscode output terminal or debug console:

![image](https://github.com/microsoft/playwright/assets/57028336/83cee1fc-28af-45ec-b162-336d7247fa35)
![image](https://github.com/microsoft/playwright/assets/57028336/60948fac-f24d-400a-8404-2c78f0bee6a0)

the following error is present in the devtools console:

> [ms-playwright.playwright]WebSocket error: connect ETIMEDOUT 127.0.0.1:53052

![image](https://github.com/microsoft/playwright/assets/57028336/13de82e3-095a-49bd-8be5-d1abb7640d5d)

### Environment

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11500H @ 2.90GHz
    Memory: 7.51 GB / 31.20 GB
  Binaries:
    Node: 21.5.0 - ~\AppData\Roaming\node\node.EXE
    npm: 10.2.4 - ~\AppData\Roaming\node\npm.CMD
    bun: 1.0.35 - ~\.bun\bin\bun.EXE
  IDEs:
    VSCode: 1.88.1 - C:\Users\user\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.1.16 - C:\WINDOWS\system32\bash.EXE
  npmPackages:
    @playwright/test: ^1.43.1 => 1.43.1
```

**Comment by pavelfeldman** [comment]
It works for me on a fresh dev box:

```
  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD EPYC 7763 64-Core Processor
    Memory: 54.44 GB / 63.95 GB
  Binaries:
    Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.88.1 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.43.1 => 1.43.1
```

Could it be that you did not allow it to use the network connection?

**Comment by DetachHead** [comment]
i didn't do anything like that, but it's a work PC so maybe a group policy or firewall or something is interfering with it. any advice on how i can narrow down exactly what's going on?

**Comment by pavelfeldman** [comment]
Not really, being able to reproduce it would help, we have not seen this happening to other users.
