### ISSUE TITLE
Soft click/input

### ISSUE THREAD

**Issue by dgozman** [microsoft/playwright#305]
We should investigate precise click/input targeting based on "node + offset". Available options:
- Make existing way more robust (various scrollIntoView/waitForIdle/etc improvements).
- Soft click implemented entirely in the renderer process.
- Something in the middle: trigger the whole input pipeline, but precisely position in the renderer (might run into input routing issues in the browser?).

**Comment by pavelfeldman** [comment]
We are punting this for now
