### ISSUE TITLE
[Bug]: Failure to install playwright with dependencies on ubuntu 22.04 - E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease' is no longer signed.

### ISSUE THREAD

**Issue by pauldruce** [microsoft/playwright#30502]
### Version

1.43.0

### Steps to reproduce

Steps which are failing:
On ubuntu-latest in github actions:
* Install playwright for Python
* python3 -m playwright install --with-deps

Can probably reproduce on any ubuntu-22.04 machine, but I can't test. 

### Expected behavior

For dependencies to be installed - no errors. 

### Actual behavior

Installing dependencies...
Switching to root user to install dependencies...
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [[14](https://github.com/mathworks/matlab-proxy/actions/runs/8814136865/job/24193725093#step:7:15)2 B]
Get:6 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
Err:6 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Hit:2 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:5 http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease
Hit:7 https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu jammy InRelease
Reading package lists...
E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease' is no longer signed.
Failed to install browsers
Error: Installation process exited with code: 100
Error: Process completed with exit code 1.

### Environment

```shell
On github actions. You can see the failures here: https://github.com/mathworks/matlab-proxy/actions/runs/8814136865/job/24193725093
```

**Comment by vitorleonel** [comment]
I'm also having the same error.

![image](https://github.com/microsoft/playwright/assets/15618005/bb202036-2206-42b0-b794-ae328a88992e)

**Comment by aseggemu-yoc** [comment]
We are also now facing the same issue.

I believe the paths are not updated in then npm module to use the new path `Release` instead of old path `InRelease`

![image](https://github.com/microsoft/playwright/assets/115168363/cc145dc8-fbdb-4921-96c1-6d5f3806575a)

**Comment by alvaromartmart** [comment]
Facing this problem as well

**Comment by pntgoswami18** [comment]
Facing the same issue when trying to install this on our github actions ubuntu instances. Looks like this is similar to other code signing problems microsoft has had with other repos' upodates of theirs
E.g.: https://github.com/microsoft/vscode/issues/135797

Could we get someone to look into this and get this fixed?
@pavelfeldman

**Comment by mxschmitt** [comment]
Folding into https://github.com/actions/runner-images/issues/9733

**Comment by pntgoswami18** [comment]
This issue is resolved for us now, it seems.
Our github actions are working fine now
