### ISSUE TITLE
[Feature]: Option to run only failed cases from the previous run

### ISSUE THREAD

**Issue by Rusinas** [microsoft/playwright#30506]
### 🚀 Feature Request

It would be wonderful to have an option to run only those tests that are failed from the previous run.

### Example

Here is a little workaround for it
https://playwrightsolutions.com/whats-the-easiest-way-to-only-re-run-failures-after-the-playwright-test-is-finished/

### Motivation

It will same a lot of time I guess. Rerunning each failed test manually or rerun everything is not ideal

**Comment by unlikelyzero** [comment]
This is implementing this feature request https://github.com/microsoft/playwright/issues/10500
