### ISSUE TITLE
[Feature]: Extend IsVisibleAsync functionality to retry for a certain period of time

### ISSUE THREAD

**Issue by socaciumugurel** [microsoft/playwright#30500]
### 🚀 Feature Request

When you navigate to a certain website, usually, the GDPR and cookies popups take some time to be fully loaded, and they are loaded after the ("load" | "domcontentloaded") events are triggered. Sometimes they don't even appear because they have been accepted before. 

Therefore a polling mechanism would be helpful in this scenario, to check every couple of milliseconds for a certain period of time (timeout) for an ILocator.

As I am new to the playwright, feel free to come up with better ideas (maybe having this mechanism in the click method).

### Example

```
//this method will retry every 200 millisends to find the element for 3000 milliseconds. The moment the element is loaded and visible it will return true. If timeout is reached and the element is not visible, it will return false.

ILocator.IsVisibleAsync(retryInterval: 200, timeout: 3000)
```

### Motivation

This feature will improve the performance of the library by avoiding unnecessary timeouts.

**Comment by pavelfeldman** [comment]
You don't need to do anything in Playwright. Just start working with the locators and Playwright will only interact when them when they are actionable. See https://playwright.dev/docs/actionability.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
