### ISSUE TITLE
[Bug]: Custom matcher marks as passed but custom matcher inner assertion is failed

### ISSUE THREAD

**Issue by Nck1969** [microsoft/playwright#30501]
### Version

1.43.1 (latest)

### Steps to reproduce

I add simple example in [sandbox](https://codesandbox.io/p/devbox/mfknwz?file=%2Fsrc%2Fplaywright%2Ftest.spec.ts%3A10%2C13&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvdldsts00063b6iyc1vki22%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvdldsts00023b6i2grkjf0m%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvdldsts00043b6iajvwuztd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvdldsts00053b6in47mhpb8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvdldsts00023b6i2grkjf0m%2522%253A%257B%2522id%2522%253A%2522clvdldsts00023b6i2grkjf0m%2522%252C%2522activeTabId%2522%253A%2522clvdls6y500ao3b6i07c6e3fd%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvdldsts00013b6iwgf77g60%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fplaywright%252Ftest.spec.ts%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A10%252C%2522startColumn%2522%253A13%252C%2522endLineNumber%2522%253A10%252C%2522endColumn%2522%253A13%257D%255D%252C%2522id%2522%253A%2522clvdls6y500ao3b6i07c6e3fd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clvdldsts00053b6in47mhpb8%2522%253A%257B%2522id%2522%253A%2522clvdldsts00053b6in47mhpb8%2522%252C%2522activeTabId%2522%253A%2522clvdn3xzt001b3b6i3gem5hna%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522clvdn3xzt001b3b6i3gem5hna%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clvdldsts00043b6iajvwuztd%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvdldsts00033b6i7d3z18hx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clvdldte1000cdaf80idr0r1z%2522%257D%255D%252C%2522id%2522%253A%2522clvdldsts00043b6iajvwuztd%2522%252C%2522activeTabId%2522%253A%2522clvdldsts00033b6i7d3z18hx%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Fork this example and run tests via "yarn playwright test"

In our project it looks like:
 <img width="1009" alt="image" src="https://github.com/microsoft/playwright/assets/56834272/dc769da7-b40a-4132-b438-bb789437ec07">
One step fails but tests marks as passsed: 
<img width="985" alt="image" src="https://github.com/microsoft/playwright/assets/56834272/05409a29-82bc-4b08-8368-7ca8d4af1395">

### Expected behavior

I expected to see that the custom matcher failed

### Actual behavior

All is passed

### Environment

```shell
System:
    OS: macOS 14.4.1
    Memory: 2.94 GB / 64.00 GB
  Binaries:
    Node: 20.10.0 - /usr/local/bin/node
    Yarn: 4.1.1 - /opt/homebrew/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by pavelfeldman** [comment]
Move `pass = true;` down a couple of lines.
