### ISSUE TITLE
[Bug]: Missing libraries for webkit browsers (libwoff2dec.so)

### ISSUE THREAD

**Issue by adamchemiawppl** [microsoft/playwright#30538]
### Version

1.43.1

### Steps to reproduce

1. Run github action - test on webkit browsers

### Expected behavior

I expect test to run

### Actual behavior

I get an error while loading shared libraries: libwoff2dec.so.1.0.2: cannot open shared object file: No such file or directory

### Additional context

 Error: browserType.launch: Target page, context or browser has been closed
    Browser logs:

    <launching> /home/runner/.cache/ms-playwright/webkit-1992/pw_run.sh --inspector-pipe --headless --no-startup-window
    <launched> pid=2054
    [pid=2054][err] /home/runner/.cache/ms-playwright/webkit-1992/minibrowser-wpe/bin/MiniBrowser: error while loading shared libraries: libwoff2dec.so.1.0.2: cannot open shared object file: No such file or directory
    [pid=2054] <process did exit: exitCode=127, signal=null>
    [pid=2054] starting temporary directories cleanup
    Call log:
      - <launching> /home/runner/.cache/ms-playwright/webkit-1992/pw_run.sh --inspector-pipe --headless --no-startup-window
      - <launched> pid=2054
      - [pid=2054][err] /home/runner/.cache/ms-playwright/webkit-1992/minibrowser-wpe/bin/MiniBrowser: error while loading shared libraries: libwoff2dec.so.1.0.2: cannot open shared object file: No such file or directory
      - [pid=2054] <process did exit: exitCode=127, signal=null>
      - [pid=2054] starting temporary directories cleanup

### Environment

```shell
System:
  OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
  CPU: (8) arm64
Binaries:
  Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
  npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
npmPackages:
  @playwright/test: 1.43.1 => 1.43.1
```

**Comment by pavelfeldman** [comment]
You probably forgot to install the native dependencies. Please complete the template in full and provide repro that we can try locally if you think this is a bug in Playwright.

**Comment by adamchemiawppl** [comment]
Is it really expected of users of your github action to install dependencies by themselves? I was under the impression the whole point of providing github actions we can use in workflows to be "ready to use" rather than "well, do it yourself".

**Comment by adamchemiawppl** [comment]
Plus, you have closed my previous commit in actual github action repository with link to file my bug in general playwright repository. I never claimed it is playwright issue, I claimed it is github action issue - that's why I filed it there. It is slightly frustrating that you personally directed me here just to say "It's not playwright issue, go away" after I took time to fill in all the details you require in the form.

**Comment by andrewlor** [comment]
This issue diminishes a lot of the value in caching playwright as `npx playwright install-deps webkit` can still take multiple minutes. Is it possible to fix the "WebKit dependencies that lay outside the cache" by either:
- Moving them into `~/.cache/ms-playwright`
- Sharing the dependency locations so we can manually add them to the github actions cache

**Comment by ironboy** [comment]
If you use a matrix to split your job into three - at least you will save some serious execution time on two out of your three jobs (chromium and firefox). 

But it would be nice to be able to cache webkit as well. :) 

I guess you could manually work out the dependency locations, and then cache, but it would be better if the Playwright team fixed this.

**Comment by ironboy** [comment]
+ off-topic: for some reason: webkit is so flaky in my tests that I can run all tests in a small PWA (that preloads everything) with no delays whatsoever, except when it comes to webkit that fails on clicks and page reloads if I don't use delays around 100 ms.

Here's a comparison of run times (with selenium with Chrome thrown in for good measure):

![speed-comparison](https://pvt23-kyh.lms.nodehill.se/uploads/videos/2021-05-18T15-38-54/speed-playwright-selenium.png)
