### ISSUE TITLE
[Feature]: Skip remaining tests after failure of first test

### ISSUE THREAD

**Issue by MatthewIceland** [microsoft/playwright#30545]
### 🚀 Feature Request

An easy command to add to a script that enables all remaining tests to be skipped if the first test has failed

### Example

I am testing a website. My first test is to confirm that the page has loaded. Subsequent tests involve updating personal details, navigating the site etc.

If the website hasn't loaded in the first test, I do not want the remaining tests to run. I would assume that all of the tests will fail and don't want to be waiting for them to timeout before they fail.

### Motivation

If the user is running a suite of tests it will save a significant amount of time by simply notifying them that the first test has failed and, therefore, this issue should be investigated before any further testing is executed. It saves the user looking through failed test results when they only need to identify the one central issue identified in the first test.

**Comment by pavelfeldman** [comment]
You can achieve this by using [project dependencies](https://playwright.dev/docs/test-projects#dependencies). Load your page in the 'smoke' project and if it won't pass, the other projects that depend on it won't run.
