### ISSUE TITLE
[Feature]: Make "respectGitIgnore" a configurable parameter

### ISSUE THREAD

**Issue by BrianMar** [microsoft/playwright#30553]
### 🚀 Feature Request

Add the ability to override the default value for the currently internal "respectGitIgnore" project value in the config file. 

I'm willing to make the change if there is agreement on the feature.

### Example

```typescript
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  // Look for test files in the "tests" directory, relative to this configuration file.
  testDir: 'tests',

  // Run all tests in parallel.
  fullyParallel: true,

  // Should the .gitignore file be used to filter out tests
  respectGitIgnore: false
  
  
```

### Motivation

I just spent about 25 hours trying to debug why my tests weren't being run. I generate my test files dynamically, since I'm using Playwright to drive another test runner that is a web app, and with the original implementation in Puppeteer we found that breaking the tests into subgroups was a huge performance win. 

Since these test files are dynamically generated, they are added to the .gitignore so that any failure to clean them up (test runner crash) doesn't cause the file to get added to the repo by mistake.

In porting to Playwright, I didn't add an explicit "testDir", mostly because we didn't have one with Playwright. 

This combination led to Playwright not seeing the generated test files. And every time I changed the name of the generated files, I'd update the .gitignore, so the problem was bizarre to debug to say the least. It appeared like there was some kind of a cache issue.

**Comment by BrianMar** [comment]
There are issues with this picking up "node_modules". However, if I set "testDir" to be the root of my project then I'd be explicitly setting a "testDir" and I'd pick up "node_modules" anyway. So, in that case, I'd likely want to explicitly turn on "respectGitIgnore". I think there's a good case for exposing this.

**Comment by BrianMar** [comment]
Here's the Issue where I was debugging this: 
https://github.com/microsoft/playwright/issues/30443

**Comment by pavelfeldman** [comment]
@BrianMar would you be willing to send a PR?

**Comment by BrianMar** [comment]
Have not had the time to go back and implement this yet.
