### ISSUE TITLE
[Feature]: Have an option to launch UI mode, Inspector or TraceViewer in different browsers.

### ISSUE THREAD

**Issue by NikkTod** [microsoft/playwright#30561]
### 🚀 Feature Request

When we have some company extentions and other restrictions on the chromium broswers than very frequently I am getting some errors like "Status Access Violation" or the broswer just crashes. 
For running the tests I can choose different browsers (like Webkit or Firefox) and avoid such problems, but when it comes to UI mode, Inspector and TraceViewer they always start with chromium browser per default. 

Is it possible to add the possibility of picking browser when trying to launch UI mode, Inspector or TraceViewer?

### Example

One option could be in the playwright config file, where we can have someting like: 

```
export default defineConfig({
 tools: { ...devices['Desktop Safari'] },
})
```

or we take the browser that is choosen for running the tests.

That would help when we launch those UI tools from VS code or when using page.pause()

Another option is when we use command line:

`npx playwright test --debug --browser 'webkit'`

`npx playwright test --ui --browser 'webkit'`

### Motivation

This feature would allow us to use the GUI tools when for some reason we have chromium browser issues in our system set up.

**Comment by pavelfeldman** [comment]
> When we have some company extentions and other restrictions on the chromium broswers than very frequently I am getting some errors like "Status Access Violation" or the broswer just crashes.

Make sure you run `npx playwright install`. This will install chromium, not chrome, which will not respect your policy extensions and restrictions. If you can't run chromium on your system, it is unlikely that you'll be able to use Playwright in full.

As a workaround, you can already open trace viewer and UI mode in any browser:

```
$ npx playwright show-trace --help
  -b, --browser <browserType>  browser to use, one of cr, chromium, ff, firefox, wk, webkit (default: "chromium")
  -h, --host <host>            Host to serve trace on; specifying this option opens trace in a browser tab
  -p, --port <port>            Port to serve trace on, 0 for any free port; specifying this option opens trace in a browser tab
```

$ npx playwright test --help
  --ui                         Run tests in interactive UI mode
  --ui-host <host>             Host to serve UI on; specifying this option opens UI in a browser tab
  --ui-port <port>             Port to serve UI on, 0 for any free port; specifying this option opens UI in a browser tab
```

inspector will only open using Chromium though.

**Comment by NikkTod** [comment]
Hi @pavelfeldman, can we reopen the ticket, I tried opening UI mode with webkit and firefox, but it is not working, it opens UI mode always with chromium.

 `npx playwright test --ui --browser webkit`
