### ISSUE TITLE
[Bug]: Chromium browsers does not respect locale option (no use of Accept-Language header) for WebSocket connections

### ISSUE THREAD

**Issue by apinnau** [microsoft/playwright#30568]
### Version

1.43.0

### Steps to reproduce

1. Clone my repo at [https://github.com/apinnau/playwright-dotnet-chromium-issue-with-websockets/tree/main](https://github.com/apinnau/playwright-dotnet-chromium-issue-with-websockets/tree/main)
2. To run E2E test cases follow instructions on [README.md](https://github.com/apinnau/playwright-dotnet-chromium-issue-with-websockets/tree/main)
3. 1 of 4 [test cases](https://github.com/apinnau/playwright-dotnet-chromium-issue-with-websockets/blob/main/src/dotnetDemo.E2ETests/LanguageTests.cs) will fail and shows the defect (missing Accept-Language header while switch from HTTP to websocket connection between client and server)

### Expected behavior

- Chromium and Firefox are respecting the localized context during whole test run
  - on first load of website via HTTP request
  - on later performed switch from HTTP to websocket (GET request with Upgrade: websocket header)
- Website is loaded with correct language via HTTP and websocket
- All 4 E2E test cases passes

### Actual behavior

- Firefox:
  - The two test cases with Firefox passes as expected (Accept-Language header is respected all the time)
- Chromium:
  - Chromium respects the localized context as the Accept-Language header is sent while website is loaded via HTTP
  - Chromium DOES NOT respect the localized context as the Accept-Language header is missing when Blazor application requests the switch to websocket (GET request with Upgrade: websocket header)
  - One test case with Chromium still passes (as English is requested and English is default language > so missing Accept-Language header doesn't influence the test result)
  - Second test case with Chromium fails where German is requested via Accept-Language header:
    - Website is first loaded in German via HTTP
    - After a short time website switches to websocket and is loaded again with English as default language

### Additional context

- Using web-application with a real Chrome browser doesn't show this behavior. Here is the Accept-Language header also in place during the switch from HTTP to websocket. So seems to be specific to Chromium in Playwright.
- Behavior could be reproduced with Windows 11 and with Ubuntu 22.04 (WSL)
- Network details (HTTP header details) is given on [README.md](https://github.com/apinnau/playwright-dotnet-chromium-issue-with-websockets/tree/main)
- Could be related to this Bug in Playwright (Node.js): [[BUG] Emulation of locale doesn't affect the "accept-language" request header value in WebSocket connection on chromium browsers. #13919](https://github.com/microsoft/playwright/issues/13919)

### Environment

```Text
- Operating System: [Windows 11 (10.0.22631)] or [Ubuntu 22.04 via WSL]
- CPU: [x86]
- Browser: [Chromium > failing, Firefox > passing, Chrome > passing]
- .NET Version: [net8.0] [Blazor server-side rendering]
- Playwright .NET: 1.43.0
```

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/13919 - looks like the same.

**Comment by apinnau** [comment]
@mxschmitt: Is the implementation of the browser (Chromium, Firefox etc.) the same for Playwright Node.js and .NET?
As #13919 is open for 2 years now - do you see any chance that this will be fixed?
