### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by DHelmcke-Tiplu** [microsoft/playwright#30562]
### Version

1.43.1

### Steps to reproduce

Start tests with
`npx playwright test --ui --update-snapshots`

### Expected behavior

Snapshots of executed tests in UI-Mode getting updated.

### Actual behavior

Snapshots of executed tests in UI-Mode are not getting updated. Tests fails because ob Snapshot Comparison.

### Additional context

In Version 1.42.1 it was possible to update snapshots by executing tests in UI-Mode.

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 6.20 GB / 31.68 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.88.1 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.43.1 => 1.43.1
```

**Comment by pavelfeldman** [comment]
Please use BUG template to file something we can reproduce locally!
