### ISSUE TITLE
[Bug]: [GUI] Locator Code Generator improper escaping and inverted frame order

### ISSUE THREAD

**Issue by pmarinfaptic** [microsoft/playwright#30569]
### Version

1.43.0

### Steps to reproduce

I have this structure which is a big iframe, inside of it there is a frame which contains the element the I needed to interact with 

![image](https://github.com/microsoft/playwright-dotnet/assets/168195243/d18f6703-cca0-446c-8411-5d36473dce0d)

I used the code generator tool, and from what I can work out not only did it do an incorect escaping of the numerical id , but it set the frame locators in the wrong order. 
FrameLocator("[id=\"\\33 50004_10\"]").FrameLocator("iframe[name=\"flow\"]").GetByRole(AriaRole.Row, new() { Name = "+ Applications", Exact = true }).Locator("font"

*also noticed that it used the iframe name even though it had an unique id.

This is what I tried  and worked: 
  FrameLocator("[id=\"flow\"]").FrameLocator("[id=\"350004_10\"]").GetByRole(AriaRole.Row, new() { Name = "+ Applications", Exact = true }).Locator("font")

I also tried the Locator Generator tool for other elements similar to this and the frames were generated in the same way every time. 

### Expected behavior

To generate the proper locator

### Actual behavior

It generated the frames in the inverted order and did not escape properly 

### Environment

```Text
- Operating System: [Windows 11]
- CPU: [arm64]
- Browser: [ Chromium]
- .NET Version (TFM): [net8.0]

```

**Comment by pavelfeldman** [comment]
Please use BUG template to file something we can reproduce locally.
