### ISSUE TITLE
[Bug]: Not possible to specify custom test-id on codegen

### ISSUE THREAD

**Issue by pfteter** [microsoft/playwright#30560]
### Version

1.43.1

### Steps to reproduce

1. playwright codegen **--config playwright.config.ts** playwright.config.ts http://localhost:3333/
2. playwright codegen **--testIdAttribute='data-test-cusom'** playwright.config.ts playwright.config.ts http://localhost:3333/

### Expected behavior

It should be possible to pass a custom playwright configuration or have an option to specify testIdAttribute directlly in the command.
It works when the VS Code extension is used see: 
https://github.com/microsoft/playwright-vscode/blob/7e5ae71534f981c2441f9287b283ddc949b614c0/src/reusedBrowser.ts#L311C57-L311C76

Its an amazing feature of the codegen to create locators automatically when a custom test id is specified

### Actual behavior

config and testid gets ignored 

### Additional context

Document how config / testId can be configured if already exists, if not implement it - works in vscode but it's useless in webstorm - the recorder can only be triggered trough the commandline

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 13th Gen Intel(R) Core(TM) i7-1365U
    Memory: 11.00 GB / 31.35 GB
  Binaries:
    Node: 20.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.87.2 - C:\appl\scoop\apps\vscode\current\bin\code.CMD
  Languages:
    Bash: 5.1.16 - C:\windows\system32\bash.EXE
  npmPackages:
    @playwright/test: ^1.43.1 => 1.43.1
```

**Comment by pavelfeldman** [comment]
```
$ npx playwright codegen --help
...
--test-id-attribute <attributeName>  use the specified attribute to generate data test ID selectors
```
