### ISSUE TITLE
[Bug]: Redirected from another domain to my domain then perform click event page crashed!!

### ISSUE THREAD

**Issue by rekhaaum** [microsoft/playwright#30564]
### Version

1.40.1

### Steps to reproduce

await this.page.click('a[data-pw="login"]');
await this.page.goto('www.anotherdomain.com');
await this.page.performLogin();
await this.page.goto('www.mydomain.com');
await this.page.click('a[data-pw="adPost"]')

### Expected behavior

Page should redirect to adPost page but getting page crashed. I thought it becuase of two different domain redirection.Please help me.

### Actual behavior

Getting page crashed. Gah. you have crashed.

### Environment

```shell
Operating System: ubuntu
Browser: mozzila
```

**Comment by pavelfeldman** [comment]
Please use BUG template to file something we can reproduce locally!
