### ISSUE TITLE
[Question] Is the library doing hard reload on page.reload() ?

### ISSUE THREAD

**Issue by s-patompong** [microsoft/playwright#3056]
Hi,

I'm wondering whether the library is doing hard reload when I call page.reload()? I tried to loop refresh one of the website and it doesn't change the content of the page while it should (ie. the server return different HTML).

Thank you!

**Comment by aslushnikov** [comment]
> I'm wondering whether the library is doing hard reload when I call page.reload()? 

@s-patompong no, it doesn't do hard-reload - the reload will use the cache. You can create a new context and load page there to emulate the "hard reload".

**Comment by s-patompong** [comment]
I see, thanks for the quick reply!

**Comment by LazioKarisma** [comment]
Hi @s-patompong and @aslushnikov ,

can you explain more how perform hard load using JAVA playwright.
Since I have try using Keyboard Action but still not performing Hard Reload.

Thank you
