### ISSUE TITLE
[Bug]: HIght CPU usage  when using chromium

### ISSUE THREAD

**Issue by ludonghai715** [microsoft/playwright#30586]
### Version

1.43.0

### Steps to reproduce

HIght CPU usage  when using chromium 
![high cpu usage](https://github.com/microsoft/playwright/assets/740845/4bc9c6a6-c057-4cfd-a66b-9526c2dd37f0)

It cost 128 seconds when just open new_page

### Expected behavior

more faster

### Actual behavior

tooo  slow

### Environment

```shell
Python:3.11
Playwright:1.4.3
Chromium 124.0.6367.29 (playwright build v1112)
```

**Comment by dgozman** [comment]
@ludonghai715 Something's indeed slow on your computer. Unfortunately, this issue does not help us to reproduce the bug, so we won't be able to help you. Perhaps your computer is just too busy?
