### ISSUE TITLE
[Feature]:  consider to invoke  `Emulation.setEmitTouchEventsForMouse` for `isMobile:true` devices

### ISSUE THREAD

**Issue by PupilTong** [microsoft/playwright#30582]
### 🚀 Feature Request

https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setEmitTouchEventsForMouse

```javascript
it('should work on scroll container', async ({ page, server }) => {
  const client = await page.context().newCDPSession(page);
  await page.setContent(`<div id="container" style="width: 500px; height: 500px; overflow-y:scroll;"><div style="width:100%; height:200%;"></div></div>`);
  await client.send('Emulation.setEmitTouchEventsForMouse',{"enabled":true,"configuration":"mobile"});
  await client.send('Input.emulateTouchFromMouseEvent',{type: 'mousePressed',button: 'left',x: 100,y:200,});
  await client.send('Input.emulateTouchFromMouseEvent',{type: 'mouseMoved',button: 'left',x: 100,y:100,});
  await client.send('Input.emulateTouchFromMouseEvent',{type: 'mouseReleased',button: 'left',x: 100,y:100,});
  expect(await page.$eval('#container', e => e.scrollTop)).toBeGreaterThan(0);
});
```

### Motivation

For mobile gesture emulation, it could help developer to mock touchscreen gesture

**Comment by dgozman** [comment]
@PupilTong Could you please explain your usecase in more details? We would like to understand the problem to be solved, before jumping into possible solutions.

**Comment by PupilTong** [comment]
> @PupilTong Could you please explain your usecase in more details? We would like to understand the problem to be solved, before jumping into possible solutions.

#2903 

It may help to emulate more touchscreen gesture.

**Comment by PupilTong** [comment]
Expose the dispatchTouch related CDP methods may help too I guess

**Comment by dgozman** [comment]
@PupilTong So, are you after testing touch gestures? Then we should close this in favor of #2903. If you have a different scenario in mind, please explain in more details.

**Comment by PupilTong** [comment]
> @PupilTong So, are you after testing touch gestures? Then we should close this in favor of #2903. If you have a different scenario in mind, please explain in more details.

Closed.
