### ISSUE TITLE
[Feature]: Add APIs to handle open shadow DOMs

### ISSUE THREAD

**Issue by RenderMichael** [microsoft/playwright#30597]
### 🚀 Feature Request

We would like to be able to access open shadow DOMs while using XPaths.

### Example

``` csharp
public ILocator GetLocatorFromShadowDOM(IPage page, string shadowHost,  string pathToTarget)
{
    return page.ShadowDOMLocator(shadowHost).Locator(pathToTarget);
}
```

### Motivation

There are dedicated APIs to handling iFrames, including [`Page.FrameLocator`](https://playwright.dev/dotnet/docs/api/class-page#page-frame-locator), as well as [`Locator.ContentFrame`](https://playwright.dev/dotnet/docs/api/class-locator#locator-content-frame) and [`FrameLocator.Owner`](https://playwright.dev/dotnet/docs/api/class-framelocator#frame-locator-owner) in the latest release.

However, we cannot reach shadow DOMs with these or any other APIs, while using XPaths. This is unfortunate, as we rely heavily on XPaths in our UI testing suite. A recent change in our UI put many of our elements behind a shadow DOM, and our test suite cannot currently cope.

In JavaScript, you can reach into a shadow DOM with the `shadowHost` property, and query within the shadow DOM from there. I am not versed enough in Playwright to know if this is a viable solution, given an XPath to the shadow host element, and an XPath into the target element itself.

If there are no plans to add shadow DOM support (I can understand that position, since this only affects XPaths), is there a decent workaround that we know of? It would be a great help.

Thanks for considering.

**Comment by dgozman** [comment]
@RenderMichael Take a look at [alternative methods for locating elements](https://playwright.dev/dotnet/docs/locators). Pretty much any other method except for XPath [already works across open shadow roots](https://playwright.dev/dotnet/docs/locators#locate-in-shadow-dom).

We strongly recommend avoiding XPath in favor of user-visible locators like `GetByRole()`. Therefore, I don't think we'll be adding support for shadow dom in XPath locators.

---

If you really need XPath with manual shadow dom query, I'd recommend to [register a custom selector engine](https://playwright.dev/dotnet/docs/extensibility#custom-selector-engines) that would query XPath in the shadow root. Something [like this](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/injected/xpathSelectorEngine.ts#L19), but querying inside `root.shadowRoot`.

In this case the API would be:

```csharp
page.Locator("xpath=//path/to/shadow/host").Locator("shadow-xpath=./path/to/target/from/the/shadow/root")
```

**Comment by RenderMichael** [comment]
@dgozman Thanks for the swift response and the workaround tip!

**Comment by RenderMichael** [comment]
For posterity, this is the engine I wrote, which works for my case:

```csharp
playwright.Selectors.RegisterAsync("xpath-shadow", new()
{
    ContentScript = true,
    Script =
    """
    {
        queryAll(root, selector) {
        if (selector.startsWith('/') && root.nodeType !== Node.DOCUMENT_NODE) {
            selector = '.' + selector;
        }

        const result = [];
        const document = root.ownerDocument || root;
        if (!document)
            return result;

        if (!root.shadowRoot) {
            return result; // if there's no shadow root, no error. just "not exists".
        }

        const firstElementInShadow = root.shadowRoot.querySelector("*");

        const selectorFromParent = '../' + selector;

        const it = document.evaluate(selectorFromParent, firstElementInShadow, null, XPathResult.ORDERED_NODE_ITERATOR_TYPE);
        for (let node = it.iterateNext(); node; node = it.iterateNext()) {
            if (node.nodeType === Node.ELEMENT_NODE)
            result.push(node);
        }
        return result;
        }
    }
    """,
});
```
