### ISSUE TITLE
[Bug]: UI mode is showing tags as pill and as text

### ISSUE THREAD

**Issue by siddharth2023** [microsoft/playwright#30606]
### Version

1.43

### Steps to reproduce

Not sure if this is a bug or by design:
- Open UI mode
- Search/Scroll to any test with a tag

If this is by design, some explanation could be useful.

### Expected behavior

Only the tag pill should show.

### Actual behavior

Tag pill + text is displayed.

UI mode:

<img width="757" alt="Screenshot 2024-04-30 at 10 11 37 AM" src="https://github.com/microsoft/playwright/assets/122398930/d5685aab-c5e5-4525-bbde-e442ea0978c8">

Code:

<img width="429" alt="Screenshot 2024-04-30 at 10 19 30 AM" src="https://github.com/microsoft/playwright/assets/122398930/fdfc4090-21c0-4781-9b78-cf70ca0bd68b">

### Environment

```shell
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 248.23 MB / 32.00 GB
  Binaries:
    Node: 21.7.1 - /usr/local/bin/node
    npm: 10.5.0 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.43.1 => 1.43.1 
    playwright: ^1.43.1 => 1.43.1
```

**Comment by dgozman** [comment]
@siddharth2023 This is by design. UI mode shows the test title, and also test tags. In this case, the tag comes from a title.

**Comment by siddharth2023** [comment]
Thanks @dgozman
