### ISSUE TITLE
[Bug]: testIdAttribute via config does not take effect in `globalSetup` function

### ISSUE THREAD

**Issue by dcaldastp** [microsoft/playwright#30605]
### Version

1.43.1

### Steps to reproduce

1. Configure a test id attribute
```js
import { defineConfig } from '@playwright/test';

export default defineConfig({
  use: {
    testIdAttribute: 'pw-test-id',
  },
});
```
2. Create a test that uses `page.getByTestId(...)`
3. Use `page.getByTestId(...)` in [globalSetup function](https://playwright.dev/docs/test-global-setup-teardown#option-2-configure-globalsetup-and-globalteardown) (probably the same happens for the teardown function)

### Expected behavior

`page.getByTestId(...)` works seamlessly across setup/teardown functions and specs.

### Actual behavior

I need to execute

```js
import { selectors } from '@playwright/test'
selectors.setTestIdAttribute('pw-test-id')
```

In order for the selector to work as expected.

### Environment

```shell
System:
    OS: macOS 14.4.1
    Memory: 185.98 MB / 16.00 GB
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by dgozman** [comment]
This is working as expected. If you would like your setup to be affected by the config, use [project dependencies](https://playwright.dev/docs/test-global-setup-teardown#option-1-project-dependencies) instead.

I'll try updating the docs to make this clear.
