### ISSUE TITLE
[Bug]: ADO Pipeline JUnit Report not showing attachments, however the logs show [[ATTACHMENT|filename]]

### ISSUE THREAD

**Issue by justinteixeira** [microsoft/playwright#30608]
### Version

1.43.1

### Steps to reproduce

1. Setup a playwright project on Git
2. Create an Azure DevOps pipeline with the project
3. Create a PublishTestResults@2 test reporter task using JUnit:
    - \- task: PublishTestResults@2
      displayName: 'Publish test results'
      inputs:
        searchFolder: 'test-results'
        testResultsFormat: 'JUnit'
        testResultsFiles: 'junit-results.xml'
        mergeTestResults: true
        testRunTitle: 'Playwright End-to-End Tests'
      condition: succeededOrFailed() 
4. In playwright.config.ts, add 
    - "reporter: [['junit', { outputFile: 'test-results/junit-results.xml' }]]" See https://playwright.dev/docs/ci#uploading-playwright-report-folder-with-azure-pipelines
    - "use: {
        trace: 'on-first-retry',
        screenshot: 'only-on-failure',
        video: 'retain-on-failure'
      },
5. Run the ADO pipeline with a failing test
6. View the test result
7. Navigate to the Attachments tab of a failed test
![image](https://github.com/microsoft/playwright/assets/165214711/129f82ee-3ebe-4b5a-b5f1-40732601745f)

### Expected behavior

According to this Microsoft dev blog article: https://devblogs.microsoft.com/devops/junit-attachments-support-for-publish-test-results/, attachments such as screenshots, videos and traces should be visible in the test report.
![image](https://github.com/microsoft/playwright/assets/165214711/f72048fa-ff37-4adb-a677-a88ff8ffbeaf)

### Actual behavior

Only the output log file is visible in the attachments of a failed test case. However, we can still see the [[ATTACHMENT|filename]] in the logs.
![image](https://github.com/microsoft/playwright/assets/165214711/d88f316c-b6e5-4139-b566-7bf74d7beb4e)

### Environment

```shell
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1
    Memory: 68.30 MB / 8.00 GB
  Binaries:
    Node: 22.0.0 - /usr/local/bin/node
    npm: 10.5.1 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.43.1 => 1.43.1 
    playwright: ^1.43.1 => 1.43.1
```

**Comment by justinteixeira** [comment]
@dgozman Thank you for the reply. Unfortunately the solution did not work so I opened an issue with Azure DevOps.

**Comment by dgozman** [comment]
@justinteixeira Sounds good. I'll close this issue for now, but let us know if there would be new information and we should take a look.
