### ISSUE TITLE
[Question] Gmail login fails

### ISSUE THREAD

**Issue by Pooort** [microsoft/playwright#3060]
Gmail login results with "This browser or app may not be secure" window.

The last Chromium version.
Headless is false.

Any suggestions?

Thanks a lot.

**Comment by aslushnikov** [comment]
Looks like GMail doesn't like the browser being automated.

There are numerous ways for websites to detect automation, and evading these checks falls outside of the Playwright project scope, so I'll close this. But there are multiple resources available on-line.

**Comment by searleser97** [comment]
@aslushnikov Could you list any of those "resources"? please

**Comment by iammrtndev** [comment]
This seems to work for me:
```js
const browser = await playwright.chromium.launch({
  ignoreDefaultArgs: ['--disable-component-extensions-with-background-pages']
})
```

**Comment by xbaha** [comment]
@worldomonation Firefox did not work for me, can you share the code, please?

**Comment by worldomonation** [comment]
> @worldomonation Firefox did not work for me, can you share the code, please?

It's still working on the code I wrote for my company project. Nothing special done other than to spin up Firefox in place of Chromium in Playwright.

The E2E test that implements this is [here](https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/specs/authentication/authentication__google.ts).

**Comment by cdoky** [comment]
Any update?
I have the same problem。

**Comment by kevinpiac** [comment]
Same problem here ✋ 

I have tried to use the Firefox browser exported by Playwright Core, but it does not seem to work either.

**Comment by teavert** [comment]
Try firefox directly from playwright without puppeteer-extra & playwright-extra

**Comment by kriiv** [comment]
You can also open a real Chrome browser with remote debugging enabled - then connect to that port to run your code.

Example on MacOS: `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222`


Then: `const browser = await chromium.connectOverCDP('http://localhost:9222');`

**Comment by Thapelo365** [comment]
@kevinpiac 
Did you manage to solve the issue?
