### ISSUE TITLE
[Docs]: Running ui mode docs incomplete

### ISSUE THREAD

**Issue by surfmuggle** [microsoft/playwright#30602]
### Abstract

To the page [UI Mode](https://playwright.dev/docs/next/test-ui-mode) add a section pre-conditions

 - upgrade to the latest supported node versions (this includes minor updates)
 - update the installed browsers 

### Details

On [UI Mode](https://playwright.dev/docs/next/test-ui-mode) the following is written as the first step

```bash
npx playwright test --ui
```
So with playwright version 1.43.1 i did this

1. Go to a folder `cd C:\playwright\`
2. Create a directory `mkdir ui-mode`
3. run `npx playwright test --ui`

Running the above returns `error: unknown option '--ui'`. Since my folder was empty i did this

 1. Run `C:\playwright\ui-mode>npm init playwright@latest` see output below
 2. Run `npx playwright test --ui`

This returns

```bash
TypeError [ERR_INVALID_ARG_TYPE]: The "parentURL" argument must be of 
type string or an instance of URL. Received an instance of Object
    at new NodeError (node:internal/errors:405:5)
    at throwIfInvalidParentURL (node:internal/modules/esm/resolve:937:11)
    at Hooks.resolve (node:internal/modules/esm/hooks:241:5)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:337:35)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:220:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:307:34)
    at Hooks.register (node:internal/modules/esm/hooks:138:51)
    at MessagePort.handleMessage (node:internal/modules/esm/worker:168:24)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
This could be related to #30217: in that issue the cause seems to be an older node version. On my box `node --version`  returns v20.7.0. 

After updating to node v20.11.1 running `npx playwright test` returns: `Error: browserType.launch: Executable doesn't exist ...`

```bash
C:\...>npx playwright test
Running 6 tests using 3 workers
  1) [chromium] › example.spec.ts:3:5 › has title ──────────────────────────────────────────────────
    Error: browserType.launch: Executable doesn't exist 
    at %userprofile%\AppData\Local\ms-playwright\chromium-1112\chrome-win\chrome.exe  
  2) ...
```

So i did run `npx playwright install` to get the latest browser versions. This finally fixed all errors and i was able to run `npx playwright test --ui` without errors.

### Output of `npm init playwright@latest`

This was the output of `npm init playwright@latest`
```bash
Need to install the following packages:
create-playwright@1.17.132
Ok to proceed? (y) y
Getting started with writing end-to-end tests with Playwright:
Initializing project in '.'
√ Do you want to use TypeScript or JavaScript? · TypeScript
√ Where to put your end-to-end tests? · tests
√ Add a GitHub Actions workflow? (y/N) · false
√ Install Playwright browsers (can be done manually via 'npx playwright install')? (Y/n) · false
Initializing NPM project (npm init -y)…
Wrote to C:\playwright\ui-mode\package.json:

{
  "name": "ui-mode",  "version": "1.0.0",  "description": "",  "main": "index.js",
  "scripts": {    "test": "echo \"Error: no test specified\" && exit 1"  },
  "keywords": [],  "author": "", "license": "ISC"
}

Installing Playwright Test (npm install --save-dev @playwright/test)…

added 3 packages, and audited 4 packages in 2s

found 0 vulnerabilities
Installing Types (npm install --save-dev @types/node)…

added 2 packages, and audited 6 packages in 2s

found 0 vulnerabilities
Writing playwright.config.ts.
Writing tests\example.spec.ts.
Writing tests-examples\demo-todo-app.spec.ts.
Writing package.json.
✔ Success! Created a Playwright Test project at C:\playwright\ui-mode\
```

### Description

To the page [UI Mode](https://playwright.dev/docs/next/test-ui-mode) add a section pre-conditions

 - upgrade to the latest supported node versions (this includes minor updates)
 - update the installed browsers

**Comment by dgozman** [comment]
@surfmuggle We assume you followed the [Getting Started](https://playwright.dev/docs/next/intro) guide before diving into the UI mode. Unfortunately, we cannot repeat the getting started guide on every documentation page - that would be unpractical.

**Comment by dgozman** [comment]
Closing as per above.
