### ISSUE TITLE
Using storageState in the general use config does not work - but works in the projects array

### ISSUE THREAD

**Issue by TimGuendel** [microsoft/playwright#30603]
Depending on where I define the storageState, the file is not written, see the comments:

utils.ts:

`export const STORAGE_STATE_FILE = './tests/e2e/storageState.json';`

playwright.config.ts:
```
export default defineConfig({
  
    use: {      
        storageState: STORAGE_STATE_FILE, // <-- This does not work, leads to "file not found error"
    },
    projects: [
        // Setup {...},
        {
            name: 'chromium',
            use: {
                ...devices['Desktop Chrome'],
                storageState: STORAGE_STATE_FILE, // <-- This works
            },
        },
    ],
});
```
Any ideas? 🤔

**Comment by dgozman** [comment]
@TimGuendel Is this a bug? Please follow the "Bug Report" template and provide a repro that we can run locally. Alternatively, [look at the documentation](https://playwright.dev/java/docs/auth).
