### ISSUE TITLE
[Feature]: Add tracing class in page like puppeteer

### ISSUE THREAD

**Issue by pan-alexey** [microsoft/playwright#30612]
### 🚀 Feature Request

Add tracing class in page like puppeteer. 

### Example

Documentation avalible [here](https://pptr.dev/api/puppeteer.tracing). 
```
await page.tracing.start({path: 'trace.json'});
await page.goto('https://www.google.com');
await page.tracing.stop();
```

### Motivation

I create tools for analyse perfomance metrics. And in puppeteer i have tracing class in page. For my case, it realy help create reports.

**Comment by dgozman** [comment]
@pan-alexey Thank you for the issue! You are probably looking for Chromium Tracing, which is available through [`browser.startTracing()`](https://playwright.dev/docs/api/class-browser#browser-start-tracing).

**Comment by pan-alexey** [comment]
@dgozman Yes, that suits me completely but it does not work on me.

I have error: Cannot read properties of null (reading 'startTracing');

Example usage
`
 const context = await chromium.launchPersistentContext('/home/user/userDataDir', {});
 const browser = context.browser()
 const page = await context.newPage();

    await context.tracing.start({
        screenshots: true,
        snapshots: true,
        sources: true,
    });

    await browser.startTracing(page, { path: '/home/user/record/trace.json' })
    await page.goto("https://apple.com", { waitUntil: "networkidle" });
    await page.goto("https://github.com", { waitUntil: "networkidle" });
    await browser.stopTracing();
`

**Comment by dgozman** [comment]
@pan-alexey Unfortunately, this feature is not compatible with `launchPersistentContext()`, because persistent context's `browser()` returns null.
