### ISSUE TITLE
[Feature]: Add option to filter Locators by visibility

### ISSUE THREAD

**Issue by rob4629** [microsoft/playwright#30615]
### 🚀 Feature Request

TestCafe has an option to filter elements by their visibility, either using [.filterVisible](https://testcafe.io/documentation/402751/reference/test-api/selector/filtervisible) or using `with` (their version of `filter`) [visibilityCheck](https://testcafe.io/documentation/402743/reference/test-api/selector/with#optionsvisibilitycheck).

It would be great to have something similar with Playwright, to help keep tests stable

### Example

```js
const myVisibleButton = page.getByRole('button', { name: 'My Button' }).filterVisible();
```

Can be used to target hidden elements too, by specifying `visible: false` for the filter method:

```js
const myHiddenButton = page.getByRole('button', { name: 'My Button' }).filter({ visible: false });
await expect(myHiddenButton).toBeHidden();
```

### Motivation

We have some elements which are named the same (e.g. `submit` button), and it will make the tests more readable than using `.nth(x)`... especially since we have a lot of variations of the same page, and `x` could change depending on the variation

**Comment by dgozman** [comment]
@rob4629 Take a look at [this documentation page](https://playwright.dev/docs/locators#matching-only-visible-elements).

**Comment by mxschmitt** [comment]
Closing as per above.
