### ISSUE TITLE
[Feature]: Playwright support on rocky linux

### ISSUE THREAD

**Issue by prc1234** [microsoft/playwright#30622]
### 🚀 Feature Request

Currently playwright is supported on Debian 11, Debian 12, Ubuntu 20.04 or Ubuntu 22.04.
With rocky Linux gaining popularity across the globe, will playwright be supported on it as well?

### Example

Currently on installing playwright on rocky linux following message is displayed:
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.

In our organization rocky linux would be the officially used OS , hence we would need support for playwright on rocky linux

### Motivation

As rocky linux OS is gaining popularity due to it being stable, secure and cost effective. organizations are now looking upon rocky linux as the alternative to RHEL hence playwright support on rocky linux would help with usage.

**Comment by dgozman** [comment]
@prc1234 There are no plans for the official support. Do `ubuntu20.04-x64` binaries work on Rocky linux? I assume it does not.

Take a look at #9199. There are some solutions that might work for you, for example [this one](https://github.com/microsoft/playwright/issues/9199#issuecomment-1932309873).

Perhaps some other officially supported binary might work for you? We have [a mapping](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/utils/hostPlatform.ts#L65-L92) from some linux distributions to supported browser binaries, so if there is one you can use, we are open to add a mapping for rocky linux as well.

**Comment by mxschmitt** [comment]
(There is also https://github.com/microsoft/playwright/issues/26482 which we recommend for unsupported OSes.)

**Comment by prc1234** [comment]
Thank you for the response. Am trying to get a rocky linux with the
required packages and check which option will work. Will revert back on
this thread when there is some update.

Thanks
Puja

**Comment by prc1234** [comment]
Hi Gozman,

                 Could you please help with the mapping for rockylinux8.
Playwright python is missing multiple libraries due to which it is kind of
unusable. Could you please suggest a way forward here.

We are using this OS:
NAME="Rocky Linux"
VERSION="8.9 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.9 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"

Thanks in advance
Puja

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
