### ISSUE TITLE
Query regarding a piece of code

### ISSUE THREAD

**Issue by priyanka-vuddemari** [microsoft/playwright#30642]
I had query regarding below piece of code i have seen in some repositories for Playwright API 

`const res = await this.request[method](endpoint, requestOptions); `
I searched the whole documentation and did not understand how above code is equivalent to 
`await request.get(url,options);`

**Comment by masthandev** [comment]
first line of code is just snippet of request function or prototype. actual code is in second line.
in first line they mentioned how to use the method:
await request.get(url/endpoint, options);
await request.post(url,body)
like that we can use

**Comment by dgozman** [comment]
Closing as per above.

Note that issue tracker is reserved for bug reports and feature requests. In the future, please ask questions in [Our Discord server](https://aka.ms/playwright/discord), or look at [The Playwright documentation](https://playwright.dev/).
