### ISSUE TITLE
[Bug]: Intermittent Undetermined Error [IP: 185.125.190.36 80] when running `npx playwright install --with-deps` on CI

### ISSUE THREAD

**Issue by anandtiwari1** [microsoft/playwright#30640]
### Version

v1.43.1

### Steps to reproduce

Using Playwright CLI to download and install playwright and browsers in GitHub CI

Example step:
`run: npx playwright install --with-deps`

### Expected behavior

Should download and install libraries and browsers successfully.

### Actual behavior

Run npx playwright install --with-deps
Installing dependencies...
Switching to root user to install dependencies...
Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:1 https://packagecloud.io/github/git-lfs/ubuntu focal InRelease [28.0 kB]
Get:3 http://ppa.launchpad.net/git-core/ppa/ubuntu focal InRelease [23.8 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
Get:5 https://packagecloud.io/github/git-lfs/ubuntu focal/main amd64 Packages [3690 B]
Get:6 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [1201 kB]
Get:7 http://ppa.launchpad.net/git-core/ppa/ubuntu focal/main amd64 Packages [3176 B]
Get:8 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [3595 kB]
Get:9 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [29.8 kB]
Get:10 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [3536 kB]
Get:11 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:12 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:13 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1275 kB]
Get:14 http://archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [33.4 kB]
Get:15 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
Get:16 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [177 kB]
Get:17 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [4069 kB]
Get:18 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [32.5 kB]
Get:19 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1497 kB]
Get:20 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [3686 kB]
Get:21 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [55.2 kB]
Get:22 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [28.6 kB]
Fetched 31.2 MB in 54s (575 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
libatomic1 is already the newest version (10.5.0-1ubuntu1~20.04).
libatomic1 set to manually installed.
libdbus-1-3 is already the newest version (1.12.16-2ubuntu2.3).
libdbus-1-3 set to manually installed.
libglib2.0-0 is already the newest version (2.64.6-1~ubuntu20.04.6).
libglib2.0-0 set to manually installed.
libicu66 is already the newest version (66.1-2ubuntu2.1).
The following additional packages will be installed:
  adwaita-icon-theme dictionaries-common emacsen-common fontconfig
  fontconfig-config fonts-ubuntu gtk-update-icon-cache hicolor-icon-theme
  humanity-icon-theme hunspell-en-us libaom0 libasound2-data libaspell15
  libass9 libasyncns0 libatk1.0-data libavahi-client3 libavahi-common-data
  libavahi-common3 libavc1394-0 libavcodec58 libavdevice58 libavfilter7
  libavformat58 libavresample4 libavutil56 libbluray2 libbs2b0 libcaca0
  libcdio-cdda2 libcdio-paranoia2 libcdio18 libchromaprint1 libcodec2-0.9
  libcolord2 libdatrie1 libdc1394-22 libdrm-amdgpu1 libdrm-common
  libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libegl-mesa0 libfftw3-double3
  libflac8 libfontenc1 libfribidi0 libgdk-pixbuf2.0-common libgl1-mesa-dri
  libglapi-mesa libglvnd0 libglx-mesa0 libglx0 libgme0 libgraphite2-3 libgsm1
  libgtk-3-common libhunspell-1.7-0 libice6 libiec61883-0 libjack-jackd2-0
  libjbig0 libjpeg8 libjson-glib-1.0-0 libjson-glib-1.0-common liblcms2-2
  liblilv-0-0 libllvm12 libmp3lame0 libmpg123-0 libmysofa1 libnorm1 libogg0
  libopenal-data libopenal1 libopenmpt0 libpciaccess0 libpgm-5.2-0
  libpixman-1-0 libpostproc55 libpulse0 libraw1394-11 librest-0.7-0 librsvg2-2
  librsvg2-common librubberband2 libsamplerate0 libsdl2-2.0-0 libsecret-common
  libserd-0-0 libshine3 libslang2 libsm6 libsnappy1v5 libsndfile1 libsndio7.0
  libsodium23 libsord-0-0 libsoup-gnome2.4-1 libsoxr0 libspeex1 libsratom-0-0
  libssh-gcrypt-4 libswresample3 libswscale5 libtext-iconv-perl libthai-data
  libthai0 libtheora0 libtiff5 libtwolame0 libusb-1.0-0 libva-drm2 libva-x11-2
  libva2 libvdpau1 libvidstab1.1 libvorbis0a libvorbisenc2 libvorbisfile3
  libvulkan1 libwavpack1 libwayland-cursor0 libwebpmux3 libwrap0 libx11-data
  libx265-179 libxau6 libxaw7 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0
  libxcb-present0 libxcb-render0 libxcb-shape0 libxcb-sync1 libxcb-xfixes0
  libxdmcp6 libxfont2 libxinerama1 libxkbfile1 libxmu6 libxmuu1 libxpm4
  libxss1 libxv1 libxvidcore4 libxxf86vm1 libzmq5 libzvbi-common libzvbi0
  ocl-icd-libopencl1 ubuntu-mono x11-common x11-xkb-utils xauth
  xfonts-encodings xfonts-utils xkb-data xserver-common
Suggested packages:
  ispell | aspell | hunspell wordlist ffmpeg-doc hunspell
  openoffice.org-hunspell | openoffice.org-core libasound2-plugins alsa-utils
  aspell libbluray-bdj colord cups-common libenchant-2-voikko
  libenchant-voikko libfftw3-bin libfftw3-dev gvfs jackd2 liblcms2-utils
  libportaudio2 opus-tools pciutils pulseaudio libraw1394-doc librsvg2-bin
Get:192 http://archive.ubuntu.com/ubuntu focal/universe amd64 libenchant1c2a amd64 1.6.0-11.3build1 [64.7 kB]
Get:193 http://archive.ubuntu.com/ubuntu focal/main amd64 libepoxy0 amd64 1.5.4-1 [191 kB]
Get:194 http://archive.ubuntu.com/ubuntu focal/main amd64 libevent-2.1-7 amd64 2.1.11-stable-1 [138 kB]
Get:195 http://archive.ubuntu.com/ubuntu focal/main amd64 libfontenc1 amd64 1:1.1.4-0ubuntu1 [14.0 kB]
Get:196 http://archive.ubuntu.com/ubuntu focal/main amd64 libjson-glib-1.0-common all 1.4.4-2ubuntu2 [3468 B]
Get:197 http://archive.ubuntu.com/ubuntu focal/main amd64 libjson-glib-1.0-0 amd64 1.4.4-2ubuntu2 [59.4 kB]
Get:198 http://archive.ubuntu.com/ubuntu focal/main amd64 libsoup-gnome2.4-1 amd64 2.70.0-1 [6136 B]
Get:199 http://archive.ubuntu.com/ubuntu focal/main amd64 librest-0.7-0 amd64 0.8.1-1 [32.2 kB]
Get:200 http://archive.ubuntu.com/ubuntu focal/main amd64 libxcomposite1 amd64 1:0.4.5-1 [6976 B]
Get:201 http://archive.ubuntu.com/ubuntu focal/main amd64 libxdamage1 amd64 1:1.1.5-2 [6996 B]
Get:202 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libgtk-3-common all 3.24.20-0ubuntu1.1 [234 kB]
Get:203 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libgtk-3-0 amd64 3.24.20-0ubuntu1.1 [2620 kB]
Get:204 http://archive.ubuntu.com/ubuntu focal/main amd64 libgudev-1.0-0 amd64 1:233-1 [14.0 kB]
Get:205 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libharfbuzz-icu0 amd64 2.6.4-1ubuntu4.2 [5580 B]
Get:206 http://archive.ubuntu.com/ubuntu focal/main amd64 libhyphen0 amd64 2.8.8-7 [27.0 kB]
Get:207 http://archive.ubuntu.com/ubuntu focal/main amd64 libice6 amd64 2:1.0.10-0ubuntu1 [41.0 kB]
Get:208 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libnghttp2-14 amd64 1.40.0-1ubuntu0.3 [79.9 kB]
Get:209 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libnotify4 amd64 0.7.9-1ubuntu3.20.04.2 [19.5 kB]
Get:210 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libnspr4 amd64 2:4.35-0ubuntu0.20.04.1 [108 kB]
Get:211 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libnss3 amd64 2:3.98-0ubuntu0.20.04.2 [1391 kB]
Get:212 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libsecret-common all 0.20.4-0ubuntu1 [3940 B]
Get:213 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libsecret-1-0 amd64 0.20.4-0ubuntu1 [110 kB]
Get:214 http://archive.ubuntu.com/ubuntu focal/main amd64 libsm6 amd64 2:1.2.3-1 [16.1 kB]
Get:215 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libwebpdemux2 amd64 0.6.1-2ubuntu0.20.04.3 [9560 B]
Get:216 http://archive.ubuntu.com/ubuntu focal/main amd64 libwoff1 amd64 1.0.2-1build2 [42.0 kB]
Get:217 http://archive.ubuntu.com/ubuntu focal/main amd64 libxt6 amd64 1:1.1.5-1 [160 kB]
Get:218 http://archive.ubuntu.com/ubuntu focal/main amd64 libxmu6 amd64 2:1.1.3-0ubuntu1 [45.8 kB]
Get:219 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libxpm4 amd64 1:3.5.12-1ubuntu0.20.04.2 [34.9 kB]
Get:220 http://archive.ubuntu.com/ubuntu focal/main amd64 libxaw7 amd64 2:1.0.13-1 [173 kB]
Get:221 http://archive.ubuntu.com/ubuntu focal/main amd64 libxfont2 amd64 1:2.0.3-1 [91.7 kB]
Get:222 http://archive.ubuntu.com/ubuntu focal/main amd64 libxkbfile1 amd64 1:1.1.0-1 [65.3 kB]
Get:223 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libxslt1.1 amd64 1.1.34-4ubuntu0.20.04.1 [151 kB]
Get:224 http://archive.ubuntu.com/ubuntu focal/main amd64 libxtst6 amd64 2:1.2.3-1 [12.8 kB]
Get:225 http://archive.ubuntu.com/ubuntu focal/universe amd64 ttf-ubuntu-font-family all 1:0.83-4ubuntu1 [10.2 kB]
Get:226 http://archive.ubuntu.com/ubuntu focal/main amd64 ttf-unifont all 1:12.0.01-2 [3137 kB]
Get:227 http://archive.ubuntu.com/ubuntu focal/main amd64 x11-xkb-utils amd64 7.7+5 [158 kB]
Get:228 http://archive.ubuntu.com/ubuntu focal/main amd64 xfonts-encodings all 1:1.0.5-0ubuntu1 [573 kB]
Get:229 http://archive.ubuntu.com/ubuntu focal/main amd64 xfonts-utils amd64 1:7.7+6 [91.5 kB]
Get:230 http://archive.ubuntu.com/ubuntu focal/universe amd64 xfonts-cyrillic all 1:1.0.4 [387 kB]
Get:231 http://archive.ubuntu.com/ubuntu focal/main amd64 xfonts-scalable all 1:1.0.3-1.1 [304 kB]
Get:232 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 xserver-common all 2:1.20.13-1ubuntu1~20.04.17 [27.8 kB]
Get:233 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 xvfb amd64 2:1.20.13-1ubuntu1~20.04.17 [781 kB]
Get:234 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libegl1 amd64 1.3.2-1~ubuntu0.20.04.2 [31.9 kB]
Get:235 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libevdev2 amd64 1.9.0+dfsg-1ubuntu0.2 [31.6 kB]
Get:236 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libgles2 amd64 1.3.2-1~ubuntu0.20.04.2 [15.6 kB]
Get:237 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libopengl0 amd64 1.3.2-1~ubuntu0.20.04.2 [29.2 kB]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/d/dictionaries-common/dictionaries-common_1.28.1_all.deb  Undetermined Error [IP: 185.125.190.36 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Fetched 122 MB in 60s (2023 kB/s)
Failed to install browsers
Error: Installation process exited with code: 100
Error: Process completed with exit code 1.

### Environment

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (8) x64 AMD EPYC 7R13 Processor
    Container: Yes
  Binaries:
    Node: 18.20.2 - /opt/hostedtoolcache/node/18.20.2/x64/bin/node
    npm: 10.5.0 - /opt/hostedtoolcache/node/18.20.2/x64/bin/npm
  Languages:
    Bash: 5.0.17 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.43.1 => 1.43.1 
    playwright-json-summary-reporter: ^1.0.1 => 1.0.1 
    playwright-merge-html-reports: ^0.2.8 => 0.2.8 
    playwright-merge-summary-json-reports: ^1.0.4 => 1.0.4
```

**Comment by dgozman** [comment]
@anandtiwari1 Well, it seems like connections from your computer to `http://archive.ubuntu.com/ubuntu` have some issues. Not sure we can help with that.

**Comment by mxschmitt** [comment]
Closing as per above, since this looks like a transient network issue rather than a Playwright bug.
