### ISSUE TITLE
[Bug]: Cookies not saving

### ISSUE THREAD

**Issue by iamtheyammer** [microsoft/playwright#30666]
### Version

1.43.1

### Steps to reproduce

```js
// create a context
const myContext = await browser.newContext({
  ...someParams,
  // viewport: {
  //   width: 2560,
  //   height: 1440,
  // },
});

// add some cookies
await myContext.addCookies([
  {
    name: "TEST_COOKIE",
    value: "here_is_a_cookie_value",
    domain: ".google.com",
    sameSite: "None",
    path: "/",
    expires: 1746450794, // ~may 2025, far beyond possible current expiration
  },
]);

// request the cookies back
console.log(await myContext.cookies());
// -> []
```

### Expected behavior

I expected to get the cookie that I added back when logging the output of `myContext.cookies()`.

### Actual behavior

`console.log(await myContext.cookies())` just logs `[]`, even though a cookie was added earlier

### Environment

```shell
System:
    OS: macOS 13.6.3
    CPU: (12) arm64 Apple M2 Max
    Memory: 492.34 MB / 32.00 GB
  Binaries:
    Node: 18.14.2 - /private/var/folders/__/wmx110r167n_6tv7d4l6c3cr0000gn/T/xfs-1e2908a0/node
    Yarn: 4.1.0 - /private/var/folders/__/wmx110r167n_6tv7d4l6c3cr0000gn/T/xfs-1e2908a0/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
  IDEs:
    VSCode: 1.88.0 - /opt/homebrew/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by mxschmitt** [comment]
Browsers don't accept `SameSite=None;secure=false` anymore. You either need to do `SameSite=Lax;secure=false` or `SameSite=None;secure=true`.

See here: https://developers.google.com/search/blog/2020/01/get-ready-for-new-samesitenone-secure

**Comment by iamtheyammer** [comment]
Thanks for your help, Max! I completely forgot about this, and it totally makes sense; the browser just ignores the cookies as it would with a `set-cookie` header. Would a warning for this scenario be good to add to Playwright?
