### ISSUE TITLE
[Feature]: support test.fail.only

### ISSUE THREAD

**Issue by vitalets** [microsoft/playwright#30662]
### 🚀 Feature Request

Support `test.fail.only()` to be able to focus on failing test.

### Example

Imagine I have two tests and 1st is expected to fail:
```ts
test.fail('my test', async ({ page }) => {
  throw new Error('foo')
});

test('my test 2', async ({ page }) => {
  // pass
});
```
If for some reason 1st test does not fail, I'd like to focus on it with adding `.only` to the test function. But nether of the following works:
```
test.fail.only('my test', async ({ page }) => { ... }
test.only.fail('my test', async ({ page }) => { ... }
```
Error:
```
TypeError: test.fail.only is not a function
```
**Note:**
If I use `test.fail()` inside test body, it works:
```ts
test.only('my test', async ({ page }) => {
  test.fail();
  throw new Error('foo')
});
```

### Motivation

I'd like to be able to focus on expectedly-failing tests as well as I can on passing tests.

**Comment by pengooseDev** [comment]
@dgozman 
I’m working on a solution for this issue, but I think it might take some time. :)

1. Do you think `only.fail` is necessary? If you'd like, I try to add it.

**Comment by dgozman** [comment]
@pengooseDev `.only` is always the last one, so we don't need `only.fail`. However, `fail.only` should be fine.
