### ISSUE TITLE
[Bug]: Playwright logged click success, but button remained un-clicked in the app.

### ISSUE THREAD

**Issue by jaganvenkat** [microsoft/playwright#30670]
### Version

1.43.1

### Steps to reproduce

1. click the button and expect a drawer is opened 
2. See that the button was not clicked but it logged as success
<img width="1468" alt="image" src="https://github.com/microsoft/playwright/assets/68076500/c5d8da95-0335-4798-bfda-a4231d381645">

### Expected behavior

Button should be clicked and the drawer should be opened

### Actual behavior

Click action logged as success in playwright but button was not clicked 
<img width="1468" alt="image" src="https://github.com/microsoft/playwright/assets/68076500/c5d8da95-0335-4798-bfda-a4231d381645">

### Additional context

Things we have tried
1. Different locator
2. Force click 
3. Wait until page loads

### Environment

```shell
System:
    OS: macOS 14.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 67.14 MB / 18.00 GB
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.36.2 => 1.43.1
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
