### ISSUE TITLE
[Feature]: Rust bindings

### ISSUE THREAD

**Issue by searleser97** [microsoft/playwright#30675]
### 🚀 Feature Request

Could you add rust bindings in the same you are doing for Python, Java, .NET, ...

### Example

Like other bindings you have created

### Motivation

As rust is increasing popularity and usage across big organizations, including Microsoft itself, would be awesome to have bindings to code applications that use playwright to control the browser.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/18266#issuecomment-1289390428

**Comment by searleser97** [comment]
Could you point us in the right direction, on how to write such bindings with Rust ?

**Comment by padamson** [comment]
See https://github.com/padamson/playwright-rust and https://crates.io/crates/playwright-rs. Would love to get feedback from the community.
