### ISSUE TITLE
[Bug]: [Node.js] Videos are not loaded in the Google Chrome Browser when tests is executed in Docker Container

### ISSUE THREAD

**Issue by tklepacki** [microsoft/playwright#30674]
### Version

1.42.0

### Steps to reproduce

- You can reproduce the error when you run the playwright tests that opens the following page: https://app.signalocean.com/tanker/howtos
- You need to login first: https://app.signalocean.com/Account/Login
- Test is run in Google Chrome Browser in the docker container: mcr.microsoft.com/playwright:v1.42.0

### Expected behavior

When the following page https://app.signalocean.com/tanker/howtos is loaded during test execution in docker container - Google Chrome Browser all videos should also be loaded correctly: 
![image](https://github.com/microsoft/playwright/assets/12895225/4ddb03ac-24de-401e-9747-c440e404b8ab)

### Actual behavior

Videos are not loaded and the following error is displayed on the screen: "The video playback was aborted due to a corruption problem or because the video used features your browser did not support" when test is executed in Google Chrome and Playwright Docker Container.

In the browsers web console you can see the following errors:

[11:48:20.289] error: videojs: 2.3.11.2 (CODE:541065219 undefined) presentationWorkflowResolved: Failed to create source buffer for stream audio, codec audio/mp4;codecs="mp4a.40.2" [object Object]

[11:48:20.350] error: azureHtml5JS: videoElementAdapter: Failed to add SourceBuffer to MediaSource: NotSupportedError: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('audio/mp4;codecs="mp4a.40.2"') is unsupported.

![Zrzut ekranu 2024-05-6 o 17 49 09](https://github.com/microsoft/playwright/assets/12895225/db24b832-89d6-4f62-9085-89f76800a193)

### Additional context

- The issue occurs only when test execution is performed in docker container - mcr.microsoft.com/playwright:v1.42.0
- Outside docker videos are loaded correctly during test execution. 

### Environment

```shell
Playwright Docker Image:
    mcr.microsoft.com/playwright:v1.42.0

System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 28.70 MB / 16.00 GB

Binaries:
    Node: 21.7.3 - /opt/homebrew/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - /opt/homebrew/bin/npm
    pnpm: 8.15.3 - /opt/homebrew/bin/pnpm

Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by mxschmitt** [comment]
We unfortunately have no login for sites like this - would it be possible to provide a repro which we can run locally or where no login is necessary?

Also this might be relevant for you:

- https://playwright.dev/docs/ci#docker
- Also you might want to run your Docker container with `--gpus all`
