### ISSUE TITLE
[Docs]: Use of Playwright.Net and the Test UI

### ISSUE THREAD

**Issue by goofballLogic** [microsoft/playwright#30692]
### Page(s)

https://playwright.dev/docs/next/test-ui-mode

### Description

There's no indication here if the Test UI can be used with dotnet tests. Is there some switch or something?

Discord link: https://discord.com/channels/807756831384403968/1237392637460217938

**Comment by mxschmitt** [comment]
This is not possible as of today. There are two kind of docs, the docs you are referring the docs are the Node.js docs, for the .NET docs see here: https://playwright.dev/dotnet
