### ISSUE TITLE
[Feature]: trace viewer ui polish suggestion 

### ISSUE THREAD

**Issue by chenshuichao** [microsoft/playwright#30691]
### 🚀 Feature Request

Maybe we can reference the reflect 's viewer, the viewer is :

https://github.com/microsoft/playwright/assets/77186544/c3cacda8-6b78-4abd-a482-04d76a39cba1

### Example

https://app.reflect.run/tests/140026/runs/9304901

### Motivation

make the view more awesome

**Comment by mxschmitt** [comment]
This looks like a third-party tool Playwright is not affiliated with. If you have concrete feature requests / design proposals for our trace-viewer, feel free to file a concrete feature request. Thank you.
