### ISSUE TITLE
[Bug]: Mac M3 - UI Mode has to be reopened several times in order to interact with tests or buttons

### ISSUE THREAD

**Issue by itz4blitz** [microsoft/playwright#30707]
### Version

1.43.0

### Steps to reproduce

1. Issue exists in any playwright project on m3 macbook
2. Sometimes when opening the playwright UI mode, the buttons and other elements require me to click 2-3+ times to select an item
3. If I close and restart UI mode, it eventually goes away

### Expected behavior

I open Playwright UI mode and I can interact with all elements

### Actual behavior

Sometimes I have to click 2-3+ times on an element to interact with it - but more often than not, I have to close and reopen the UI mode repeatedly until this behavior disappears.

### Environment

```shell
System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 114.52 MB / 18.00 GB
  Binaries:
    Node: 21.7.2 - ~/.nvm/versions/node/v21.7.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v21.7.2/bin/npm
  IDEs:
    VSCode: 0.33.1 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.43.0 => 1.43.0
```

**Comment by itz4blitz** [comment]
A video was too large to upload. Here's a link to the issue where you can see more clearly the problem:

https://drive.google.com/file/d/1Bx0T4mQcAeOg6nFpad1W9l98eF4CtFnC/view?usp=sharing

**Comment by mxschmitt** [comment]
Looks weird! Could you try updating to v1.44.0? 

This also happens when you create a new project like its done in the [getting started](https://playwright.dev/)?

**Comment by itz4blitz** [comment]
> Looks weird! Could you try updating to v1.44.0?
> 
> This also happens when you create a new project like its done in the [getting started](https://playwright.dev/)?

Thanks for the response. I've updated my project to 1.44.0. 

I also took your suggestion and created a new project and I am seeing the same issue.

https://drive.google.com/file/d/1QkVEcirSJ0RTKgCETKmgTg9knmWcG-sZ/view?usp=sharing

My only solution is to close and re-open UI mode until the elements can be interacted with as expected.

**Comment by yury-s** [comment]
This interaction is very sluggish, does Activity Monitor or DevTools on the UI mode page show anything interesting?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by FaizanMostafa** [comment]
It takes all the memory available in my system and usage a large swap. My system has crashed once. I use m3 with 18gb ram.
