### ISSUE TITLE
[Bug]: Firefox tests in macos 14 time out / take a long time

### ISSUE THREAD

**Issue by canstand** [microsoft/playwright#30705]
### Version

1.44.0

### Steps to reproduce

Refer https://github.com/microsoft/playwright/actions/runs/8973892628

- All jobs of firefox in macos-14 (macos-latest) timeout after 1h30m
- Jobs of firefox in macos-12(or macos-13) only took about 30m

 (another proof: https://github.com/canstand/playwright-go/actions/runs/8999400053/job/24721476663 )

### Expected behavior

The test job takes similar time under different macos versions.

### Actual behavior

Test job in macos-14(firefox) timeout.

### Environment

```shell
OS: macos 14
Browser: firefox
playwright: v1.44.0
```

**Comment by mxschmitt** [comment]
Looking at the recent commits, it always times out.

**Comment by aslushnikov** [comment]
Turns out Firefox was timing out on macos-14 since the test bots were introduced: https://github.com/microsoft/playwright/commit/4affcdef71624e9c0982f9eb5be19c7e4d2251ab

**Comment by aslushnikov** [comment]
This seems to be an issue with Apple Silicon virtualization + Firefox.
* Upstream bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1897892
* Detailed repro: https://github.com/aslushnikov/macos-14-firefox-super-slow/tree/main

**Comment by mxschmitt** [comment]
Note: We temporarily mitigated it for now by continuing to use macOS Intel for our testing infrastructure in order to not loose any test coverage.

**Comment by aslushnikov** [comment]
Note: this seems to be fixed with the latest Firefox Beta 128

**Comment by mxschmitt** [comment]
This seems to affect some feature which is not yet enabled on Firefox Stable.

**Comment by juliandescottes** [comment]
FWIW, Firefox had a sandboxing issue with GitHub action arm64 workers (same symptoms, 5s per tab opening) which was fixed in Firefox 129 (https://bugzilla.mozilla.org/show_bug.cgi?id=1893921)

**Comment by dgozman** [comment]
After the roll to Firefox 130, Playwright's own bots are back to normal again. Thanks to the Firefox team for fixing the issue!
