### ISSUE TITLE
[Bug]: Second page of a new tab is not interactive

### ISSUE THREAD

**Issue by semin-narmi** [microsoft/playwright#30717]
### Version

1.32.2

### Steps to reproduce

I'm having trouble trying to finish end to end after opening a new tab.

The following is what I included to open a new tab and assert the url of new tab, close the current page, and return the newTab so I can use it for the next pages in the flow.

```
  async openNewTab(context) {
    ...
    await nextButton.click();

    // opens a new tab
    const pagePromise = context.waitForEvent("page");
    const newTab = await pagePromise;
    await newTab.waitForLoadState();
    await expect(newTab).toHaveURL(
      `/newTabUrl`
    );

    await this.page.close();
    return newTab;
}
```

And in my test spec file, this is how I use the newTab

```
test(`e2e`, async ({ page, context }) => {
    const newTab = await openNewTab(
      context,
    );
    const firstPageAfterNewTab = new FirstPage(newTab);
    const secondPageAfterNewTab = new SecondPage(newTab);

    // this first page is interactive and works as expected
    await firstPageAfterNewTab.assertPage();
    
    // this second page after new tab is flaky. It would work maybe 1/4 times and fails the rest
    await secondPageAfterNewTab.assertPage();
  });
```

// secondPage.js
```
 class SecondPage {
  constructor(page: Page) {
    this.page = page;
  }
  async assertPage() {
    const radioButton = this.page.locator(button)
    await radioButton.click()
  }
}
```

### Expected behavior

I expect the second page to be interactive like the first page after the new tab

### Actual behavior

I encounter `Error: locator.evaluate: Test ended.` or `Error: locator.waitFor: Target page, context or browser has been closed` errors. 

### Additional context

My speculation is that the newTab that I'm returning is only interactive for `/newTabUrl` page. Should I try creating a new context for the playwright page if I want to interact with `/newTabUrl-secondPage`?

### Environment

```shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M2
    Memory: 63.88 MB / 16.00 GB
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
  IDEs:
    VSCode: 1.72.2 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.40.0-alpha-nov-15-2023 => 1.40.0-alpha-nov-15-2023 
    playwright: 1.32.2 => 1.32.2 
    playwright-expect: ^0.1.2 => 0.1.2
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
