### ISSUE TITLE
[Bug]: getByRole not finding items inside New Look dynamics dialogs

### ISSUE THREAD

**Issue by stevenebutler** [microsoft/playwright#30722]
### Version

1.44.0

### Steps to reproduce

1. Clone repo https://github.com/stevenebutler/playwright-getbyrole-dialog
2. npm i
3. npx playwright install chromium
4. npx playwright test

Note that step 4 is also achievable by running the example.spec.js test case in VS Code Playwright extension

### Expected behavior

I expect playwright to find the buttons inside the popup dialog by accessibility roles.

I would also like to be able to identify the dialog by accessibility role, but it seems like it is not visible in the accessbility tree.

### Actual behavior

Unable to find any items inside the dialog by accessibility roles/names. This is despite the button showing up in the dev tools as having accessibility role and name as per screenshot below. 

Unclear why the dialog is not in the accessibility tree with the New Look in Dynamics 365. When using old look, the getByRole for dialogs and buttons within the dialog work as expected. The browser indicates the element with [role=dialog] is being hidden from the accessibility tree, so may have something to do with why other elements are not being found inside it.

```js
  await expect(page.locator('[role=dialog]')).toBeVisible() // This finds the dialog
  await expect(page.locator('[role=dialog]').getByText('Ignore and save', { exact: true })).toBeVisible() // This finds the dialog button

  // But these items do not find items in the dialog
  await expect(page.getByRole('heading', { name: 'Duplicate records found' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Ignore and save' })).toBeVisible()

  // Would be good to find the dialog by its accessibility role (however, it appears to be invisible in the tree)
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('dialog', { name: 'Duplicate records found' }).getByRole('button', { name: 'Ignore and save' })).toBeVisible()
```

![image](https://github.com/microsoft/playwright/assets/16790181/65f69619-0b1a-4bc8-937c-ba25a25d4737)

### Additional context

Note the static HTML is an anonymized capture from a dynamics 365 test system. I also tried Playwright 1.40.0 and observe same behaviour.

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 3.80 GB / 15.65 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 4.0.2 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.0 - C:\Program Files\nodejs\pnpm.CMD
    bun: 1.1.3 - ~\.bun\bin\bun.EXE
  IDEs:
    VSCode: 1.89.0 - C:\Users\sebut\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.2.21
  npmPackages:
    @playwright/test: ^1.44.0 => 1.44.0
```

**Comment by mxschmitt** [comment]
There is `aria-hidden=true` on an ancestor element, hence the heading is not considered visible:

![image](https://github.com/microsoft/playwright/assets/17984549/d9521475-1e21-4360-ae18-ab86d82eed29)

Removing it, makes it work: 

      await page.locator('#shell-container').evaluate((e) => e.removeAttribute("aria-hidden"))

**Comment by stevenebutler** [comment]
The more I look at this the more I think it's actually an issue with MS Dynamics 365 new look rendering.

The element (CSS=#shell-container) has aria-hidden="true" property. If I remove this the accessibility tree looks more like what I'd expect.

**Comment by stevenebutler** [comment]
Closing this as I have implemented workaround for now and reported this issue to dynamics.
