### ISSUE TITLE
[Bug]: Playwright UI Mode Closes Without Reporting Test Results

### ISSUE THREAD

**Issue by jwalkerinterpres** [microsoft/playwright#30729]
### Version

1.43.0

### Steps to reproduce

1. Run a test inside the "UI Mode" test runner
2. Test fails
3. There's no explanation of why: no failure message or any other output whatsoever

### Expected behavior

It doesn't matter whether a test passes, fails, or times out: it should *always* report the results after.

### Actual behavior

No results were reported

https://github.com/microsoft/playwright/assets/152227747/e8a5f35a-06e1-4d18-bcae-1c8e76ff88a3

That output at the end was:

```

    > 325 |   await expect(priorityIcon).toHaveCSS('fill', PRIORITY_ICON_COLORS[i]);
          |                              ^
      326 |
      327 |   // Each tab should have numeric text
      328 |   await expectToHaveNumericText(tab);

        at expectValidAssociatedThreatElementTab (/Users/jeremywalker/new-ui/interpres-new-ui/e2e/src/dataList/dataListExpectations.ts:325:30)

    Error: Test ended.

    Error: ENOENT: no such file or directory, open '/Users/jeremywalker/new-ui/interpres-new-ui/e2e/test-results/.playwright-artifacts-0/58ba7d6422ad39b41530945866d86262.zip'

  1 failed
    [chromium] › campaign.spec.ts:153:7 › A campaign with a reference › should display properly 

```

It seems likely this line is responsible:

>    Error: ENOENT: no such file or directory, open '/Users/jeremywalker/new-ui/interpres-new-ui/e2e/test-results/.playwright-artifacts-0/58ba7d6422ad39b41530945866d86262.zip'

### Additional context

I tried changing the test (eg. to a simple `throw new Error()`); didn't help.

I tried removing my `test-results` folder, in case old/garbage results were to blame; didn't help

I tried removing `node_modules` and reinstalling all my packages; didn't help.

Also, as a side note, this is probably a continuation of https://github.com/microsoft/playwright/issues/29426

### Environment

```shell
System:
    OS: macOS 14.4.1
    Memory: 2.36 GB / 32.00 GB
  Binaries:
    Node: 21.2.0 - /usr/local/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    playwright: ^1.44.0 => 1.44.0
```

**Comment by jwalkerinterpres** [comment]
If it helps, I _think_ the problem was an unterminated and un-awaited `expect` statement, something to the effect of:

    expect(foo);

**Comment by yury-s** [comment]
Please try with Playwright 1.44 and if it still reproduces please share a reproduction example.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by jwalkerinterpres** [comment]
The problem is, if I give you more info, you won't fix this problem: you'll fix the problem I give you info for.  This literally has happened already once before in https://github.com/microsoft/playwright/issues/29426.

To put it generally, my goal for this ticket was to have you add a try/catch, not prevent a specific exception from being thrown.
