### ISSUE TITLE
[Feature]: CLI command set for serial and parallel test execution to run a set of tests with a single worker and set of tests with multiple workers in a single test run 

### ISSUE THREAD

**Issue by LukemansfieldPAX** [microsoft/playwright#30727]
### 🚀 Feature Request

Playwright is currently missing the functionality on the CLI to support hybrid test suites which include set of tests that can only be run in serial and set of tests which can be run in parallel of each other within a single test execution.

It would be fantastic if Playwright provided such command where we can set which tests can be run only with one worker and set of tests which can be run with multiple workers but all in a single test run so when it comes to generating the final test report results, it includes all information for all tests no matter the worker configuration  is in a single playwright HTML report. 

### Example

This feature can be used with developers/testers who have test suites which have a mixture of tests that can be run only in serial and rest of the tests that can be run in parallel but in order to achieve maxmium test performance efficiency they allocate the worker configuration required to the set of tests which can then run all of the tests in a single test run reducing the complexity of the final test results generated as it is now executed in a single test execution (avoids merging test results from subsequent test runs).

### Motivation

The motivation for this proposal was from the Playwright Live event that happened today that I attended and a similar question was asked around this I believe from a viewer called "Vitor" which highlighted the exact requirements I also desire from Playwright to provide a solution when running test suites which include a mixture of tests to be executed in serial and tests to be executed in parallel to be executed in a single test run.

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/21970
