### ISSUE TITLE
[Bug]: Unable to run chrome in k8s with seccomp_profile.json in v1.39.0 and up

### ISSUE THREAD

**Issue by Gidgidonihah** [microsoft/playwright#30738]
### Version

1.44.0 (1.39.0 and newer)

### Steps to reproduce

1. Standup up a Kubernetes cluster with the [playwright-supplied seccomp_profile.json](https://github.com/microsoft/playwright/blob/main/utils/docker/seccomp_profile.json) pre-loaded [on the host node](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-seccomp-profile-for-a-container)
2. Run a pod using the seccomp_profile.json and a vanilla playwright docker image (see config below)
3. In the pod's shell, run chrome:

```bash
/ms-playwright/chromium-1084/chrome-linux/chrome
```

### Expected behavior

Because the pod is running in an environment without X, you should see the following messages:

```
[9:27:0509/230116.190455:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[9:9:0509/230116.191268:ERROR:ozone_platform_x11.cc(244)] Missing X server or $DISPLAY
[9:9:0509/230116.191287:ERROR:env.cc(258)] The platform failed to initialize.  Exiting.
```

### Actual behavior

Chrome fails to launch with an error:

```
[FATAL:pkey.cc(40)] Check failed: PkeyMprotect(address, (size + (partition_alloc::internal::SystemPageSize() - 1)) & (~(partition_alloc::internal::SystemPageSize() - 1)), 0x1 | 0x2, pkey) == 0. : Operation not permitted (1)
#00 0x561e26dafae2  (/ms-playwright/chromium-1084/chrome-linux/chrome+0x3c9bae2)
#01 0x561e26dafcd9  (/ms-playwright/chromium-1084/chrome-linux/chrome+0x3c9bcd9)
#02 0x561e26dc12a1  (/ms-playwright/chromium-1084/chrome-linux/chrome+0x3cad2a1)
#03 0x561e26dc12f3  (/ms-playwright/chromium-1084/chrome-linux/chrome+0x3cad2f3)
#04 0x561e26dbbaa1  (/ms-playwright/chromium-1084/chrome-linux/chrome+0x3ca7aa1)
#05 0x561e26db54b5  (/ms-playwright/chromium-1084/chrome-linux/chrome+0x3ca14b5)
#06 0x561e2d661af0  (/ms-playwright/chromium-1084/chrome-linux/chrome+0xa54daf0)
#07 0x561e2d65c837  (/ms-playwright/chromium-1084/chrome-linux/chrome+0xa548837)
#08 0x561e2a8e8e40  (/ms-playwright/chromium-1084/chrome-linux/chrome+0x77d4e40)
#09 0x561e2a8e6eb0  (/ms-playwright/chromium-1084/chrome-linux/chrome+0x77d2eb0)
#10 0x561e2a8e727d  (/ms-playwright/chromium-1084/chrome-linux/chrome+0x77d327d)
#11 0x561e26d6431b  (/ms-playwright/chromium-1084/chrome-linux/chrome+0x3c5031b)
[FATAL:pkey.cc(40)] Check failed: PkeyMprotect(address, (size + (partition_alloc::internal::SystemPageSize() - 1)) & (~(partition_alloc::internal::SystemPageSize() - 1)), 0x1 | 0x2, pkey) == 0. : Operation not permitted (1)
#00 0x556ea5116ae2  (/ms-playwright/chromium-1084/chrome-linux/chrome+0x3c9bae2)
#01 0x556ea5116cd9  (/ms-playwright/chromium-1084/chrome-linux/chrome+0x3c9bcd9)
#02 0x556ea51282a1  (/ms-playwright/chromium-1084/chrome-linux/chrome+0x3cad2a1)
#03 0x556ea51282f3  (/ms-playwright/chromium-1084/chrome-linux/chrome+0x3cad2f3)
#04 0x556ea5122aa1  (/ms-playwright/chromium-1084/chrome-linux/chrome+0x3ca7aa1)
#05 0x556ea511c4b5  (/ms-playwright/chromium-1084/chrome-linux/chrome+0x3ca14b5)
#06 0x556eab9c8af0  (/ms-playwright/chromium-1084/chrome-linux/chrome+0xa54daf0)
#07 0x556eab9c3837  (/ms-playwright/chromium-1084/chrome-linux/chrome+0xa548837)
#08 0x556ea8c4fe40  (/ms-playwright/chromium-1084/chrome-linux/chrome+0x77d4e40)
#09 0x556ea8c4deb0  (/ms-playwright/chromium-1084/chrome-linux/chrome+0x77d2eb0)
#10 0x556ea8c4e27d  (/ms-playwright/chromium-1084/chrome-linux/chrome+0x77d327d)
#11 0x556ea50cb31b  (/ms-playwright/chromium-1084/chrome-linux/chrome+0x3c5031b)
#12 0x7ff404701d90  (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#12 0x7f930770fd90  (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
[167:167:0509/225935.759399:FATAL:zygote_host_impl_linux.cc(201)] Check failed: ReceiveFixedMessage(fds[0], kZygoteBootMessage, sizeof(kZygoteBootMessage), &boot_pid). : No such file or directory (2)
#0 0x55f36523f882 base::debug::CollectStackTrace()
#1 0x55f36522c083 base::debug::StackTrace::StackTrace()
#2 0x55f365186723 logging::LogMessage::~LogMessage()
#3 0x55f365187568 logging::ErrnoLogMessage::~ErrnoLogMessage()
#4 0x55f36518758e logging::ErrnoLogMessage::~ErrnoLogMessage()
#5 0x55f36516ed67 logging::CheckError::~CheckError()
#6 0x55f3638183a1 content::ZygoteHostImpl::LaunchZygote()
#7 0x55f3645af1b0 content::(anonymous namespace)::LaunchZygoteHelper()
#8 0x55f362ea3605 content::ZygoteCommunication::Init()
#9 0x55f361ee890f content::CreateGenericZygote()
#10 0x55f3645ae44b content::ContentMainRunnerImpl::Initialize()
#11 0x55f3645abeb0 content::RunContentProcess()
#12 0x55f3645ac27d content::ContentMain()
#13 0x55f360a2931b ChromeMain
#14 0x7f6d2d2d3d90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
#15 0x7f6d2d2d3e40 __libc_start_main
#16 0x55f360a2902a _start
Crash keys:
  "num-switches" = "0"
  "osarch" = "x86_64"
  "pid" = "167"
  "ptype" = "browser"

[0509/225935.960068:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[0509/225935.960102:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
Trace/breakpoint trap (core dumped)
```

### Additional context

We discovered this when updating from playwright v1.37.0. We have previously been running playwright successfully with the supplied seccomp_profile.json applied. This started failing with v1.39.0. We tested each newer version as well.

When running any of the affected versions *without* the seccomp_profile.json applied, chrome runs fine.
It feels like a newer version of chrome now requires a syscall that was not previously required, and this not allowed. We have not narrowed it down to *which* syscall that may be.

> [!NOTE]
> Running it locally via docker with the same seccomp_profile seems to work just fine.
> ```
> docker run -it --rm --ipc=host --user pwuser --security-opt seccomp=seccomp_profile.json mcr.microsoft.com/playwright:v1.44.0-jammy /bin/bash
> ```

### Environment

This was tested with K8s Version: `v1.27.11-eks-b9c9ed7`.

As long as you run on a node with the supplied seccomp_profile.json installed, this can be replicated using a basic pod from the following yaml:

```shell
apiVersion: v1
kind: Pod
metadata:
  name: playwright-mwe
spec:
  containers:
    - name: playwright-mwe
      image: mcr.microsoft.com/playwright/python:v1.44.0-jammy
      imagePullPolicy: IfNotPresent
      command:
        - sleep
        - '3600'
      securityContext:
        runAsUser: 1000
  securityContext:
    seccompProfile:
      localhostProfile: profiles/seccomp_profile.json
      type: Localhost
```

**Comment by yury-s** [comment]
> Running it locally via docker with the same seccomp_profile seems to work just fine.

We recommend you ask k8s experts as the problem is specific to it.

**Comment by Gidgidonihah** [comment]
I'm not expecting to get tech support here. So to answer with "ask k8s experts" is fine in that regard.

I suppose the problem is caused by following [the playwright documentation for scraping in docker](https://playwright.dev/python/docs/docker#crawling-and-scraping), and expecting it to work for k8s which it previously did and, IMO, is not an unreasonable expectation. Perhaps if the seccomp_profile.json is going to be supplied by the project, but isn't expected to work in k8s, it would be helpful to have a message stating as much.

In any case, the newer versions of chromium shipped with playwright started working again in k8s when modifying the seccomp_profile.json to allow [`pkey_mprotect`](https://man7.org/linux/man-pages/man2/pkey_mprotect.2.html):

```json
{
  "comment": "Allow pkey_mprotect for memory protection key operations. This is required for versions of chromium targeted with playwright from v.1.39.0",
  "names": [
    "pkey_mprotect"
  ],
  "action": "SCMP_ACT_ALLOW",
  "args": [],
  "includes": {},
  "excludes": {}
}
```

**Comment by azasypkin** [comment]
> In any case, for anyone that might come across this in the future, the newer versions of chromium shipped with playwright started working again in k8s when modifying the seccomp_profile.json to allow [pkey_mprotect](https://man7.org/linux/man-pages/man2/pkey_mprotect.2.html):

++, in case it helps anyone, there are also several other issues with the [seccomp_profile.json](https://github.com/microsoft/playwright/blob/main/utils/docker/seccomp_profile.json) suggested in [the docs](https://playwright.dev/docs/docker) that I have just encountered with the latest kernel (e.g., `openat2 fsmount:fscontext:proc/thread-self/fd/: function not implemented`). This is because it is based on a fairly old default seccomp profile. I have switched to [a much more recent version](https://github.com/moby/profiles/blob/main/seccomp/default.json) from the Moby profiles repository as the base seccomp profile for my containers to resolve this.
