### ISSUE TITLE
[Feature]: The equivalent of cy.intercept, listening for requests, in order to use data from them

### ISSUE THREAD

**Issue by OSnuszka** [microsoft/playwright#30740]
### 🚀 Feature Request

When rewriting the playwright tests from cypress, the biggest problem I had was the lack of _cy.intercept_. 
I currently have a workaround in playwright but it works very un-expectantly

```
export async function interceptResponse(searchString: string, page: Page) {
  const responsePromise = page.waitForResponse(
    (response) =>
      response.url().includes(searchString),
    { timeout: 60000 },
  );

  return responsePromise;
}
```
And example of use 

```
let responsePromise = interceptResponse(`dataRequest.json`, page);
await page.goto(`/`);
let body = await (await responsePromise).text();
expect(responseBody).not.toBeNull();
```

I have more advanced uses of this function because I process json objects there, but the idea is the same -> intercept before the action that triggers the request -> action -> analyze data from the request.
I know about `page.route` -> but I don't know if I can use it in the context of listening and possibly returning data later on

### Example

*The `dataRequest.json` appears during the page load

```
let request = page.intercept('dataRequest.json);
await page.goto('/');
await expect(request.body()).not.toBeNull();
```

### Motivation

Easier process of rewriting automation from Cypress, more flexible automation

**Comment by yury-s** [comment]
> I know about page.route -> but I don't know if I can use it in the context of listening and possibly returning data later on

Yes, you can. See this document: https://playwright.dev/docs/release-notes#response-interception You can fetch response, analyze it and then fulfill original request with it. Does this work for you?

**Comment by yury-s** [comment]
Can you explain then what is not working for your scenario in the following code?

```js
    const responsePromise = page.waitForResponse('**/dataRequest.json');
    await page.goto('/');
    const response = await responsePromise;
    const data = await response.json();
    expect(data).toBeTruthy();
    // analyze the data and interact with the page
```

**Comment by OSnuszka** [comment]
Assertion is unstable because I am checking a request that has quite a large request - And playwright sometimes pulls it out too “fast” as the JSON is unprocessed.

**Comment by OSnuszka** [comment]
I rewrote the function that listens for requests and noticed that the tests work a little better (the ones that wait for requests). But I have a feeling that I'm not doing it optimally.

Just as I described `waitForRequest` itself, it doesn't wait for the body to be processed to the end in my case.

```
export async function interceptResponse(searchString: string, page: Page) {
  const response = page.waitForResponse(
    (response) =>
      response.url().includes(searchString) &&
      response.status() === 200 &&
      response.body() !== null &&
      response.request().failure() === null,
    { timeout: 30000 },
  );
  return response;
}
```

**Comment by mxschmitt** [comment]
> And playwright sometimes pulls it out too “fast” as the JSON is unprocessed.

could you elaborate on that?

We need a reproduction which we can run locally in order to act on issues like that. Most likely there is a race somewhere, so looking at code is essential for us. Would it be possible to share a small test, ideally with expected and actual outcome?

**Comment by OSnuszka** [comment]
It's hard for me to find an adequate JSON example(Our JSON loads within half a second as part of the page opening.), but concept of the test looks as follows:

```
import { test, expect } from '@playwright/test';

for (let i = 0; i < 10; i++) {
test('demo JSON' + i, async ({ page }) => {
  let promise = page.waitForResponse(
    (response) =>
      response.url().includes('feed_content?') &&
      response.status() === 200 &&
      response.body() !== null &&
      response.request().failure() === null,
    { timeout: 30000 },
  );

  await page.goto('https://dev.to/playwright');
  const response = await promise;
  const responseBody = JSON.parse(await response.text());
  let totalCount = responseBody["result"].length;
  expect(totalCount).toBeGreaterThan(0);
});
}


```

I looped the test to try to induce instability described as a topic of this task, but it works stably here.
Test in my case is failing at ` const responseBody = JSON.parse(await response.text());`. 
![image](https://github.com/microsoft/playwright/assets/78599192/24fb8857-a12e-4666-9cb4-191c54c29a86)

Once I try review trace (in case of test failing due instability) with to check request body in network tab I can see:

![image](https://github.com/microsoft/playwright/assets/78599192/11b83fcd-1d26-481b-ab88-060edb2b1c54)


This test passes completely randomly, depending on whether the body manages to generate in time

**Comment by mxschmitt** [comment]
Usually this error happens when you try to access a response body of a request which was from a previous navigation. Browsers like Chromium will clean them up from their memory in order to save memory and give you this error. What might work is the following:

```ts
import { test, expect } from '@playwright/test';

for (let i = 0; i < 10; i++) {
  test(`demo JSON + ${i}`, async ({ page }) => {
    let resolveResponse = null;
    const waitForSpecificResponse = new Promise(resolve => resolveResponse = resolve);
    page.on('response', async response => {
      if (response.url().includes('feed_content?'))
        resolveResponse(await response.json());
    });
    await page.goto('https://dev.to/playwright');
    const responseBody = await waitForSpecificResponse;
    const totalCount = responseBody['result'].length;
    expect(totalCount).toBeGreaterThan(0);
  });
}
```

Alternatively try to delay the second navigation if possible.

**Comment by OSnuszka** [comment]
This solution works, but requires some refactoring on the side of my tests. As if there would be a dedicated function in playwright for this I would be happy.

**Comment by yury-s** [comment]
Closing as the problem has been resolved and there are no planned changes on playwright side.
