### ISSUE TITLE
[BUG] Wait for function ignores timeout option

### ISSUE THREAD

**Issue by arjun27** [microsoft/playwright#3074]
**Context:**
- Playwright Version: 1.2.1 and 1.2.0-next.1595364665021
- Operating System: Mac
- Node version: 14
- Browser: All

**Code Snippet**

```javascript
const {firefox} = require("playwright");

(async () => {
  const browser = await firefox.launch();
  const context = await browser.newContext()
  const page = await context.newPage();
  await page.waitForFunction(() => false, { timeout: 2000 })
  await page.screenshot({ path: `example.png` });
  await browser.close();
})();
```

**Describe the bug**

`page.waitForFunction` is not resolved in 2 seconds. Bug copied over from [this slack message](https://playwright.slack.com/archives/CSUHZPVLM/p1595337859491400). cc @xylix

**Comment by dgozman** [comment]
`page.waitForFunction()` takes a [second argument](https://playwright.dev/#version=v1.2.1&path=docs%2Fapi.md&q=pagewaitforfunctionpagefunction-arg-options) `arg` that is passed to the function. In this example, `{ timeout: 2000 }` is passed to the `() => false` function. Options (including a timeout) is a third parameter, so just pass any dummy value for the `arg`:

```js
await page.waitForFunction(() => false, 42, { timeout: 2000 });
```
