### ISSUE TITLE
[Feature]: Make CodeGen able to continue with the existing test

### ISSUE THREAD

**Issue by Kurina11** [microsoft/playwright#30742]
### 🚀 Feature Request

I would like to get a feature for codegen where you will be able to use already automated test as argument/make codegen able to connect to an existing browser from last test run and codegen will start recording from the point where the test is finished. In our project there are long tests 7-10 minutes automated and this will help me to save a lot of time while continuing in automation of the tests.

### Motivation

It will be easier for people to make longer tests.

**Comment by yury-s** [comment]
You can use ['Record at Cursor'](https://playwright.dev/docs/getting-started-vscode#record-at-cursor) feature of our VS Code extension for that, it will modify existing test in place.

Closing this issue as we are not planning to implement this in standalone codegen.

**Comment by FloMaetschke** [comment]
Is there any way, to replay the test i want to extend? Imagine a web formular with 8 pages, you record page1, customize it, add validations in code, and when you click on record at cursor for the test codegen of page2, it will show you an empty browser without the prior input data. Everything has to be put back in the fields by hand, until you can really continue. Seems a bit useless to me.

**Comment by FloMaetschke** [comment]
> Is there any way, to replay the test i want to extend? Imagine a web formular with 8 pages, you record page1, customize it, add validations in code, and when you click on record at cursor for the test codegen of page2, it will show you an empty browser without the prior input data. Everything has to be put back in the fields by hand, until you can really continue. Seems a bit useless to me.

Found a solution, but a single function like "continue record at cursor" would be much better.

Solution:
https://github.com/microsoft/playwright/issues/28571#issuecomment-1849299551
