### ISSUE TITLE
[Feature]: Support configuring playwright.config searching in playwright-vscode 

### ISSUE THREAD

**Issue by wattsbn** [microsoft/playwright#30744]
### 🚀 Feature Request

For very large multi-package projects, the vscode extension takes a long time to search for playwright test files (> 5 minutes). However, this code be helped by modifying the query that is being used to search for these files. 

It looks like it currently searches the entire workspace for playwright.config files.
https://github.com/microsoft/playwright-vscode/blob/355923aed7d72ed40a439e390b3bf356d4ef9685/src/extension.ts#L259

A extension setting that could allow for modifying this search could help large projects improve the search performance of the extension.

Another option would be to give the user the ability to force refresh specific sections in the tree view of the test explorer. This would let us update the explorer without needed to wait for a full refresh when a new test is added.

### Example

Just having a static list of directories where the tests (or config files) can be found would work for my specific cases. 

### Motivation

The test explorer in the extension is quite slow to load the tests in large workspaces making it frustrating to use.

**Comment by yury-s** [comment]
> For very large multi-package projects, the vscode extension takes a long time to search for playwright test files (> 5 minutes). 

This sounds very long indeed. Have you tried running `npx playwright test` for such project and see if it works faster? It could be that requiring the source files takes significant time. If the problem is with the search of config, could you share an example project?

**Comment by wattsbn** [comment]
Unfortunately, the projects that I work with are all private so I can't share them.
Running individual tests via console commands works well as they target the exact test.

**Comment by mxschmitt** [comment]
What kind of files does your repository contain? Would e.g. ignoring gitignore help you?

Might be a bit advanced, but have you tried to run the [extension](https://github.com/microsoft/playwright-vscode) locally in debug mode to figure out of that specific line is causing the delay?

Could you try version `1.1.1` which we just released? Its a rewrite of a lot of internals, just to double check that this version is still causing trouble for your setup. Thanks!

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
