### ISSUE TITLE
Error: No tests found

### ISSUE THREAD

**Issue by srikanthathikari** [microsoft/playwright#30768]
### Version

1.44.0

### Steps to reproduce

"I attempted to run Playwright tests using the **npx playwright test** command, and my tests executed successfully. However, after moving the **playwright.config.ts** file to a folder structured as conf/playwright.config.ts, I consistently received a 'no test found' error."
Below is the code that is causing the problem. 

"scripts": {
    **"smoke": "npx playwright test -c conf/playwright.config.ts",**

### Expected behavior

I expect the tests to run, like how they if the config file is in the root of the project

### Actual behavior

Error : No tests found

### Environment

```shell
Mac Book Pro Sonoma
```

**Comment by mxschmitt** [comment]
You need to adjust [testDir](https://playwright.dev/docs/api/class-testconfig#test-config-test-dir) in such kind of scenarios:

```ts
import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: '../tests',
});
```

**Comment by srikanthathikari** [comment]
I am using **testMatch: ['/specs/smoke/tests/*.spec.ts']**, which works fine when the playwright.config.ts is at the root level.

**Comment by mxschmitt** [comment]
Yes, this is because testDir is by default the directory where the playwright.config file is located. In your case you would have to change it to e.g.

```ts
import path from 'path'
import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: path.join(__dirname, '..'),
});
```

**Comment by sathikari** [comment]
My issue has been resolved with the provided solution. Thank you. This can be closed
