### ISSUE TITLE
[Bug]: ECONNRESET (masked) downloading browsers

### ISSUE THREAD

**Issue by pluby** [microsoft/playwright#30761]
### Version

1.31.2 to latest

### Steps to reproduce

Output shown below was created with 1.31.2 but the same bug occurs in the latest version although logs may differ. Note that both `wget` and `curl` work just fine for the download of `https://playwright.azureedge.net/builds/chromium/1048/chromium-linux.zip`.

I was unable to rule out Fedora Silverblue and mobile internet as a possible contributing factor to this behaviour.

Run `npm exec --no -- playwright-core install --with-deps chromium` on a slow internet connection (pre-download messages removed):

```
  pw:install downloading Chromium 111.0.5563.19 (playwright build v1048) - attempt #1 +0ms
Downloading Chromium 111.0.5563.19 (playwright build v1048) from https://playwright.azureedge.net/builds/chromium/1048/chromium-linux.zip
  pw:install running download: +167ms
  pw:install -- from url: https://playwright.azureedge.net/builds/chromium/1048/chromium-linux.zip +0ms
  pw:install -- to location: /tmp/playwright-download-chromium-debian11-1048.zip +0ms
  pw:install -- response status code: 200 +568ms
  pw:install -- total bytes: 150732736 +6ms
143.7 Mb [====================] 99% 0.2s  pw:install SUCCESS downloading Chromium 111.0.5563.19 (playwright build v1048) +26s
  pw:install extracting archive +1ms
  pw:install -- zip: /tmp/playwright-download-chromium-debian11-1048.zip +1ms
  pw:install -- location: /ms-playwright/chromium-1048 +0ms
  pw:install FAILED installation Chromium 111.0.5563.19 (playwright build v1048) with error: Error: end of central directory record signature not found +22ms
Failed to install browsers
Error: Failed to download Chromium 111.0.5563.19 (playwright build v1048), caused by
Error: end of central directory record signature not found
    at /ms-playwright-agent/node_modules/playwright-core/lib/zipBundleImpl.js:1:24033
    at /ms-playwright-agent/node_modules/playwright-core/lib/zipBundleImpl.js:1:31712
    at /ms-playwright-agent/node_modules/playwright-core/lib/zipBundleImpl.js:1:17288
    at FSReqCallback.wrapper [as oncomplete] (node:fs:684:5)
```

Removing the line that deletes the temporary file allows it to be inspected. I found it was truncated. I also invoked `oopDownloadMain.js` manually and got different truncation lengths each time.

Adding `response.on("error", err => console.log(err));` to `oopDownloadMain.js` shows an `ECONNRESET`. As this is not caught and used for promise rejection, the process terminates without the promise resolving or rejecting, making the child process appear to exit successfully as all events and IO are completed.

Adding `Connection: 'keep-alive'` to the headers in `oopDownloadMain.js` seems to fix the issue.

### Expected behavior

Should just download and install without error like I can with `wget` or `curl`.

### Actual behavior

The download is truncated.

On later versions there are multiple attempts that seem to end the same. This is worse because it downloads a lot of data without succeeding.

### Additional context

I tested this on Fedora 40 server using a cloud provider and there is no problem. The fault occurs on Fedora 40 Silverblue workstation running a container with either docker or podman (same error) on a mobile network with 30Mbps speed.

I was able to reproduce the download fault using a short node script against the CDN which fails every time without the keep-alive header.

```
"use strict";

const http = require('https');
const fs = require('fs');

const file = fs.createWriteStream("chrome.zip");
const request = http.get("https://playwright.azureedge.net/builds/chromium/1048/chromium-linux.zip", { headers: {
    Connection: 'keep-alive' // FIX
  }}, function(response) {
   response.pipe(file);
   response.on("end", () => { console.log("response.end"); });
   response.on("close", () => { console.log("response.close"); });
   response.on("error", (e) => { console.log("response.error", e); });

   file.on("end", () => { console.log("file.end"); });
   file.on("close", () => { console.log("file.close"); });
   file.on("error", (e) => { console.log("file.error", e); });

   // after download completed close filestream
   file.on("finish", () => {
       file.close();
       console.log("Download Completed");
   });
});
```

### Environment

```shell
System:
    OS: Linux 6.8 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
    Memory: 4.01 GB / 7.61 GB
    Container: Yes
  Binaries:
    Node: 18.18.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
  Languages:
    Bash: 5.1.4 - /bin/bash
  npmPackages:
    playwright-core: ^1.31.2 => 1.31.2
```

**Comment by pluby** [comment]
Update: It appears to happen only on my mobile internet. Moving to a (slower) fixed-line internet resolves the problem. Tested multiple times over last half hour. Not clear why this should be an issue but if adding the keep-alive header makes it more robust on mobile broadband networks then perhaps that's still worth doing?

**Comment by Exoow** [comment]
Added info, we have a similar issue (it worked 5 days ago). Our C# solution runs the Playwright install script post-build, and we get the following error. This is **blocking** our daily E2E tests.

![image](https://github.com/microsoft/playwright/assets/18096566/de8619ac-28a7-4aaa-bd35-6a8ac3d1d77c)

**Comment by mxschmitt** [comment]
@pluby this looks like the same as https://github.com/microsoft/playwright/issues/28329#issuecomment-1827412436 - are you using [three.co.uk](https://www.three.co.uk/)?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
