### ISSUE TITLE
[Bug]: SyntaxError: Unexpected token 'with'

### ISSUE THREAD

**Issue by MyrZiKus** [microsoft/playwright#30764]
### Version

1.44.0

### Steps to reproduce

1. Create a test with JSON import like this 
import data from './dataObject.json' assert { type: 'json' };
2. Run the test

### Expected behavior

The test has passed successfully

### Actual behavior

Error happend
"SyntaxError: Unexpected token 'with'"
Error: No tests found.
Make sure that arguments are regular expressions matching test files.
You may need to escape symbols like "$" or "*" and quote the arguments.

I rolled back to a previous version (1.43.1), and it works there.

### Additional context

playwrignht.config.ts
`import { defineConfig, devices } from '@playwright/test';
import * as dotenv from 'dotenv';

dotenv.config();

export default defineConfig({
    timeout: 450 * 1000,
    expect: {
        timeout: 5000,
        toHaveScreenshot: {
            threshold: 0.3,
            maxDiffPixels: 10,
        },
    },
    globalSetup: './global/globalSetup',
    fullyParallel: true,
    forbidOnly: !!process.env['CI'],
    retries: process.env['CI'] ? 1 : 0,
    reporter: process.env['CI'] ? 'dot' : 'list',
    use: {
        baseURL: process.env['PLAYWRIGHT_TEST_BASE_URL'],
        actionTimeout: 10000,
        trace: 'retain-on-failure',
        ignoreHTTPSErrors: true,
        storageState: 'global/storageState.json',
    },
    projects: [
        {
            name: 'chromium',
            use: {
                ...devices['Desktop Chrome'],
                viewport: {
                    width: 1920,
                    height: 1080,
                },
            },
        },
    ],
});`

tsconfig.json
`{
    "extends": "../../tsconfig.base.json",
    "files": [],
    "include": [],
    "compilerOptions": {
        "forceConsistentCasingInFileNames": true,
        "strict": true,
        "noImplicitOverride": true,
        "noPropertyAccessFromIndexSignature": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "resolveJsonModule": true,
        "esModuleInterop": true
    },
    "angularCompilerOptions": {
        "strictInjectionParameters": true,
        "strictInputAccessModifiers": true,
        "strictTemplates": true
    }
}`

### Environment

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 15.66 GB / 31.91 GB
  Binaries:
    Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.89.1 - C:\Users\myrzi\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.1.16
  npmPackages:
    @playwright/test: 1.44.0 => 1.44.0
    playwright-teamcity-reporter: 0.2.1 => 0.2.1
```

**Comment by MyrZiKus** [comment]
I couldn't find adequate solutions to this problem

**Comment by mxschmitt** [comment]
I was able to reproduce on Node.js 18 but not on Node.js 20.

Caused by https://github.com/microsoft/playwright/pull/30482.

Looks like they let [V8 parse](https://babeljs.io/docs/babel-plugin-syntax-import-attributes#deprecatedassertsyntax) it rather than transform it.

Also as per [here](https://babeljs.io/docs/v8-migration#babelplugin-syntax-import-assertions):

> Please migrate to @babel/plugin-syntax-import-attributes ([#15536](https://github.com/babel/babel/pull/15536)). After you replace the plugin, you should search and replace the following patterns in your codebase:

**Comment by mxschmitt** [comment]
Playwright only supports the latest 18.X, 20.X, 22.X releases, we recommend updating e.g. 18.20 or 20.13. Updating to these versions fixes that issue.
