### ISSUE TITLE
[Docs]: a small typo in documentation

### ISSUE THREAD

**Issue by HRanjan-11** [microsoft/playwright#30762]
### Page(s)

https://playwright.dev/docs/release-notes#:~:text=expect.toPass.inervals

### Description

expect.toPass.inervals. this text should be expect.toPass.intervals. there is a typo in word intervals.

**Comment by mxschmitt** [comment]
Looks like already fixed in https://github.com/microsoft/playwright/pull/30647 - docs get updated only when a new stable release happens.
