### ISSUE TITLE
[Docs]: Second example has a wrong function 

### ISSUE THREAD

**Issue by kgendig** [microsoft/playwright#30777]
### Page(s)

https://playwright.dev/docs/release-notes#version-144

![image](https://github.com/microsoft/playwright/assets/15123436/924db774-46ba-4906-9935-746cdf0f2259)

### Description

Second example has a wrong function 

is toHaveAccessibleName
should be toHaveAccessibleDescription

**Comment by mxschmitt** [comment]
Looks like already fixed by https://github.com/microsoft/playwright/pull/30672.
