### ISSUE TITLE
[Bug]: Shows blank screen in UI Mode

### ISSUE THREAD

**Issue by arthur1993-code** [microsoft/playwright#30772]
### Version

1.44.0

### Steps to reproduce

1. Freshly installed playwright
2. Start a local server(example: localhost:4300/)
3. write a simple one-two step test like 
page.goto('localhost:4300')
page.some_locator.click()
4. Run the test in ui mode

### Expected behavior

it should open ui mode window and show test results as it is described in playwright dosumentation

### Actual behavior

the ui mode window opens and shows that tests passed, but showing blank page with no steps and any info at all

### Environment

```shell
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 87.42 MB / 16.00 GB
Binaries:
    Node: 22.0.0 - /opt/homebrew/bin/node
    npm: 10.7.0 - /opt/homebrew/bin/npm
Languages:
    Bash: 3.2.57 - /bin/bash
npmPackages:
    @playwright/test: ^1.44.0 => 1.44.0 
IDE:
    Webstorm
Browsers:
    All
```

**Comment by mxschmitt** [comment]
I tried the following which works for me:

```ts
import { expect, test } from "@playwright/test"

test("test", async ({ page }) => {
    await page.goto('https://example.com')
    await page.getByRole('link', { name: 'More information...' }).click()
});
```

Which version does `npx playwright --version` give you? Just to confirm that the latest version is installed.

Does it reproduce on a fresh project created via `npm init playwright new-project`?

**Comment by arthur1993-code** [comment]
As mentioned in the bug ticket, the version is 1.44.0
It is a new project
I cloned a repository from my playwright coach from udemy, did nom start to
up the server, and took the url
Localhost:<some_number>
May be it’s an issue with webstorm only?
Did you try to repro it on webstorm?

**Comment by arthur1993-code** [comment]
I noticed that i’m not the only person to have this issue, and similar
issue was opened and closed without fixing the problem.
If it could help, we can schedule a call and look directly on my project so
that we could debug the problem

**Comment by yury-s** [comment]
Closing per the response above. We need to be able to reproduce the problem to make this report actionable.
