### ISSUE TITLE
[Regression]: "Error: route.fulfill: Protocol error (Fetch.fulfillRequest): Invalid http status code or phrase", with valid 419 code.

### ISSUE THREAD

**Issue by kurkle** [microsoft/playwright#30773]
### Last Good Version

1.40.1

### First Bad Version

1.43.1

### Steps to reproduce

```ts
            // fake expired token response
            await page.route(
                '*/**/api/*',
                (route) => {
                    route.fulfill({
                        status: 419,
                        headers: {
                            'Access-Control-Allow-Origin': '*',
                        },
                        body: 'fake',
                    })
                },
                { times: 1 }
            )
```

### Expected behavior

I expect 419 to be a valid status code (some API's return that and we need to be able to test the case)

### Actual behavior

419 is said to be invalid.

### Environment

```shell
System:
    OS: macOS 14.4.1
    Memory: 6.82 GB / 32.00 GB
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
  Languages:
    Bash: 5.2.26 - /opt/homebrew/bin/bash
```

**Comment by mxschmitt** [comment]
In previous versions this wasn't working either, it resulted in a silent catch, when looking at the debug logs:

>   pw:protocol SEND ► {"id":29,"method":"Fetch.fulfillRequest","params":{"requestId":"interception-job-1.0","responseCode":419,"responseHeaders":[{"name":"content-length","value":"4"}],"body":"ZmFrZQ=="},"sessionId":"24A02879199C3AF17A072D712F8E7922"} +4ms
>  pw:protocol ◀ RECV {"id":29,"error":{"code":-32602,"message":"Invalid http status code or phrase"},"sessionId":"24A02879199C3AF17A072D712F8E7922"} +0ms

This means, there was no error surfaced to the user and the request also never got fulfilled successfully with 419 status code. As per [Wikipedia](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes), 419 is no valid status code.

Since this wasn't working before either, this seems not a regression but a limitation?

**Comment by kurkle** [comment]
As per the [Hypertext Transfer Protocol (HTTP) Status Code Registry](https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml), 419 is valid but unassigned.

But you are correct, it did not work before either (and the test in question does not test what it should, duh)

**Comment by yury-s** [comment]
Is there a reason you want to fulfill with unsupported error code?

**Comment by kurkle** [comment]
Sure there is, I want to mock actual API reaponse, which has status 419 (for expired token), in this case.
