### ISSUE TITLE
[Bug]: Using astro:db I'm unable to load package with scheme astro:

### ISSUE THREAD

**Issue by nicolascochin** [microsoft/playwright#30784]
### Version

1.44.0

### Steps to reproduce

within a `setup db` project 
```typescript
[...]
projects: [
  {
    name: "setup db",
    testMatch: /global\.setup\.ts/,
  },
  {
    name: "chromium",
    use: { ...devices["Desktop Chrome"] },
    dependencies: ["setup db"],
  },
]
[...]
```
I have this `global.setup.ts` file: 
```typescript
import { test as setup } from "@playwright/test";
import { db, User } from "astro:db";

setup("Init users", async ({}) => {
  const users = await db.select().from(User);
});
```

### Expected behavior

The users to be loaded

### Actual behavior

the following error occurs:
`Error: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. Received protocol 'astro:'`

### Environment

```shell
System:
    OS: Linux 6.8 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1270P
    Memory: 27.28 GB / 46.75 GB
    Container: Yes
  Binaries:
    Node: 21.6.2 - ~/.anyenv/envs/nodenv/versions/21.6.2/bin/node
    npm: 10.2.4 - ~/.anyenv/envs/nodenv/versions/21.6.2/bin/npm
  IDEs:
    VSCode: 1.89.1 - /usr/local/bin/code
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.44.0 => 1.44.0
```

**Comment by mxschmitt** [comment]
I tried `require("astro:db")` inside Node.js and it doesn't work either - so maybe since it doesn't work with a normal Node.js script it doesn't work with Playwright?

**Comment by nicolascochin** [comment]
Yeah maybe.. Thank you for your investigation. I'm closing this issue since it doesn't sounds like a playwright's issue.
