### ISSUE TITLE
[Bug]: When try to open with -ui-port

### ISSUE THREAD

**Issue by alp148** [microsoft/playwright#30794]
### Version

1.44.0

### Steps to reproduce

1 - In debian 12
2  - create folder and init playwright proyect inside with: npm init playwright@latest
3 - run: npx playwright test --ui-port=8080 --ui-host=0.0.0.0
4 - browser page open as blank and in inspector console shows errors to access to uiMode.webmanifest

### Expected behavior

open de ui interface with test suites

### Actual behavior

browser page open as blank and in inspector console shows errors to access to uiMode.webmanifest

### Environment

```shell
System:
    OS: Linux 6.5 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 5.67 GB / 15.50 GB
    Container: Yes
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
    bun: 1.0.29 - ~/.bun/bin/bun
  IDEs:
    VSCode: 1.86.2 - /usr/bin/code
  Languages:
    Bash: 5.2.15 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.44.0 => 1.44.0
```

**Comment by yury-s** [comment]
> 4 - browser page open as blank and in inspector console shows errors to access to uiMode.webmanifest

Do you access within the system or remotely? If it's a remote system, make sure that port forwarding is configured correctly. I was not able to reproduce it locally or with github codespaces.

**Comment by alp148** [comment]
Locally and remotelly

**Comment by yury-s** [comment]
> Locally and remotely

Weird. It's likely some peculiar configuration on your system. Are you able to start it locally with explicit ip `npx playwright test --ui-port=8080 --ui-host=127.0.0.1` ? We can't help with this without being able to reproduce the problem.

**Comment by alp148** [comment]
The steps i follow are in the issue description:

i seed you screen shots:

![image](https://github.com/microsoft/playwright/assets/55721793/eec18a84-b456-467c-9102-b5136e7037d2)
![image](https://github.com/microsoft/playwright/assets/55721793/6e752687-b3e1-4845-ba8b-f429525e36a6)
![image](https://github.com/microsoft/playwright/assets/55721793/25a440f9-5d23-457f-ac94-1cda06a6e6a5)

**Comment by yury-s** [comment]
Can you try opening the same page in incognito mode/different browser and see if it works there? It might have something to do with your browser config.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
