### ISSUE TITLE
ms-playwright does not detect tests in test explorer in vscode

### ISSUE THREAD

**Issue by rushi-alation** [microsoft/playwright#30803]
Type: <b>Bug</b>

Install extension with latest vscode and extension

Extension version: 1.1.1
VS Code version: Code 1.89.1 (Universal) (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:24.611Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|8, 5, 5|
|Memory (System)|32.00GB (1.64GB free)|
|Process Argv|--crash-reporter-id a341c1bf-be8b-40bc-a28a-29c69bb7d082|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31018788
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31043157
a69g1124:31046351
pythonprc:31039816
dwnewjupyter:31046869

```

</details>

**Comment by siddharth2023** [comment]
Can confirm reverting to a previous version of the extension solves this issue.

Multiple issues being:

1. Play button not showing up but then realized had to check the project in the sidebar
2. Sometimes have to restart VSCode because the test doesn't stop even if the browser is quit (headed mode)

**Comment by philipfong** [comment]
I'm seeing this too. I had to select all of the unselected 'projects' in the testing tab. This is going to cause a lot of confusion for those just starting out with the extension.

**Comment by pavelfeldman** [comment]
This should be addressed now. Please see https://github.com/microsoft/playwright/issues/30882 for more details.

**Comment by zomars** [comment]
Downgrading to `v1.0.22` worked for me. `v1.1.7` doesn't find neither my project config files nor my tests which use a custom `testMatch: /.*\.e2e\.tsx?/` property.

**Comment by mxschmitt** [comment]
@zomars please file a separate issue, happy to look into it. Make sure you have the projects selected in the Testing tab under the Playwright section, see https://github.com/microsoft/playwright/issues/30882 for more details.
