### ISSUE TITLE
[Question] Does `fit` shortcut still work with the jest tests?

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#3080]
The [`fit` shortcut](https://github.com/microsoft/playwright/blob/master/CONTRIBUTING.md#running--writing-tests) was super helpful when contributing new tests. I can't seem to get it to work any more after rebasing on the latest code. Does the new Jest test runner activated with `npm run test` still respect it?

**Comment by rwoll** [comment]
Oh, it looks like Jest's [default behavior is to only respect it per-file](https://stackoverflow.com/questions/44446626/run-only-one-test-with-jest) where as the old test runner respected it globally.

In other words, before if I added a `fit` in `download.test.js` and ran `npm run test` only that one test would get executed (i.e. tests in network.test.js, etc. would not get run). Now, even if I put a `fit` in `download.jest.js` all the other test files get executed.

What's the best way to simulate the old behavior?

**Comment by aslushnikov** [comment]
> Oh, it looks like Jest's default behavior is to only respect it per-file where as the old test runner respected it globally.

@rwoll: yeah that's a pity. The best way to run a single test with jest is to use `it.only` + `npx jest <filename>`
