### ISSUE TITLE
[Bug]: Playwright Test for VSCode stop button no longer works

### ISSUE THREAD

**Issue by murathptest** [microsoft/playwright#30808]
### Version

1.44

### Steps to reproduce

I'm not able to stop a debug test using the square stop button.

### Expected behavior

I expect to stop the playwright debug session but it is not stopping

### Actual behavior

Can only stop test runs by exiting and reentering VSCode

### Additional context

It was working fine before upgrade to the latest playwright

### Environment

```shell
System:
OS: Windows 10 10.0.11763
CPU: (2) x64 Intel(R) Xeon(R) Platinum 8180 CPU @2.50 GHz
Memory: 3.14 GB / 8.00 GB
Binaries Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
npn: 10.5.2 - C:\Program Files\node.js\npm.CMD
IDEs:
 VSCode: 1.89.1 
npmPackages
 @playwright/test: ^1.44.0 -> 1.44.00
playwright ^1.44.0 -> 1.44.0
playwright-core: ^1.43 => 1.43.0
```

**Comment by uandco** [comment]
I reckon there's more issues and they are all related to extension v1.1.1, like infinite loading of tests when trying to expand them:

<img width="489" alt="image" src="https://github.com/microsoft/playwright/assets/26996169/0005bd46-0c65-4365-87d3-202c4b7d6e78">

Downgrading to 1.0.22 resolves the issue

**Comment by markgva** [comment]
Having lots of problems with 1.1.1 as well including this one. Rolling back to 1.0.22 resolved it for me as well.

**Comment by nickwhitney-zoopla** [comment]
I too was having the same issue and downgrade to 1.0.22 as mentioned above resolved, thank you.

**Comment by kajetanarab** [comment]
> Having lots of problems with 1.1.1 as well including this one. Rolling back to 1.0.22 resolved it for me as well.

@markgva can you tell me how to rollback to 1.0.22 ? 🙃

**Comment by uandco** [comment]
> @markgva can you tell me how to rollback to 1.0.22 ? 🙃

Go to the list of extensions, find the Playwright one, click the cog in the bottom right corner and select "Install another versions"

**Comment by kajetanarab** [comment]
> > @markgva can you tell me how to rollback to 1.0.22 ? 🙃
> 
> Go to the list of extensions, find the Playwright one, click the cog in the bottom right corner and select "Install another version..."

Thanks dude !

**Comment by jtgober** [comment]
Just validated that on my end as well. Thanks for this

**Comment by murathptest** [comment]
I want to thank all of you for verifying that this is an issue with the Playwright Test for VSCode and going back to 1.0.22 will make it more stable.

**Comment by murathptest** [comment]
I want to thank all of you for verifying that this is an issue with the VSCode extension, Playwright Test for VSCode, and going back to 1.0.22 will make it more stable.
