### ISSUE TITLE
[Bug]: Playwright Test for VSCode duplicates run information i bottom right table

### ISSUE THREAD

**Issue by dawidkwiecien** [microsoft/playwright#30815]
### Version

1.44

### Steps to reproduce

1. In Test Explorer right click on single test
2. Run test
3. On the Test result, right bottom part you will have duplicated information of run

### Expected behavior

I expect to single run should be presented single time, to get better orientation when test started/stopped working etc.

### Actual behavior

Actually single run is presented twice in Test Results, bottom right tab (i don't know how its called this tab, but its on bottom right)

### Additional context

![image](https://github.com/microsoft/playwright/assets/2427085/afbef59c-dd08-4a1e-b2ec-66af91002cc6)

### Environment

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
    Memory: 5.81 GB / 15.71 GB
  Binaries:
    Node: 20.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.89.1 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.44.0 => 1.44.0
```

**Comment by pavelfeldman** [comment]
Depends on https://github.com/microsoft/vscode/issues/213182

**Comment by pavelfeldman** [comment]
Depends on https://github.com/microsoft/vscode/issues/223550

**Comment by mxschmitt** [comment]
Depends on https://github.com/microsoft/vscode/issues/232923
