### ISSUE TITLE
[Bug]: Setting slow_mo between 340-1000 will cause the content of the drop-down box to display as empty.

### ISSUE THREAD

**Issue by 406722575** [microsoft/playwright#30813]
### Version

1.43.0

### Steps to reproduce

。

### Expected behavior

The content of the drop-down box can be displayed normally.

### Actual behavior

Configure slow_mo under the root directory conftest.py:
@pytest.fixture(scope="session")
def browser_type_launch_args(browser_type_launch_args) -> Dict:
      return {
          "channel": "chrome",
          "headless": False,
          "args": [
              '--start-maximized',
              '--disable-features=BlockInsecurePrivateNetworkRequests',
          ],
          "slow_mo": 500,
          **browser_type_launch_args,
      }

Test Code：

  def review_comment(self):
      with allure.step(f"Approval Comments"):
            self.locator_sideButton.click()
            self.locator_common_phrase.wait_for(state='visible')
            self.locator_common_phrase.click()
            self.agree.click()
            self.locator_submit_action.click()
            self.page.wait_for_timeout(4000)
            self.locator_submit_action.wait_for(state='detached')

After running, the drop-down box displays as empty.
![PixPin_2024-05-15_09-59-16](https://github.com/microsoft/playwright/assets/39303693/b665068b-b60a-486b-8a09-4d80f257b5ee)

1、When setting slow_mo below 340, the drop-down box can be displayed, but when submitting the form, the test case shows it as passed, however, the form does not actually get submitted successfully.
2、When setting slow_mo to 1100, the display is normal and the form can be submitted successfully.

### Additional context

。

### Environment

```shell
System:
    OS: win10
python:3.9.0
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
