### ISSUE TITLE
[Bug]: vscode extension defaults should show all projects

### ISSUE THREAD

**Issue by callpraths** [microsoft/playwright#30811]
### Note from maintainers

There were some significant changes in the latest release of the VS Code Extension.
If you have problems with running tests, selecting projects and configuration,
running setup projects etc. after upgrading to the the recent version of the extension,
please read our [FAQ](https://github.com/microsoft/playwright/issues/30882).

---

### Version

v1.1.1

### Steps to reproduce

- Open a project with playwright tests in vscode. There might need to be multiple playwright projects in the repo to reproduce this bug (unsure).
- Update https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright from pre-v1.1.1 to v1.1.1.
- Observe that the test explorer no longer lists any playwright tests.

### Expected behavior

v1.1.1 shipped the feature to be able to select the playwright projects to execute, and the test explorer now only shows the projects that are selected.

Prior to v1.1.1, all projects were shown in test explorer. I expected the list of tests shown to not change as I did not take any action to remove tests / projects.

### Actual behavior

By default, my relevant projects were not selected (a dummy project that doesn't have many tests happened to be selected) and I had to figure out where to go select the project I care about.

### Additional context

I love the ability to select projects. The problem here is with sensible defaults - coming into v1.1.1 I expected that I don't have to take any action to be able to continue seeing the tests that I did previously.

### Environment

```shell
System:
    OS: Windows 10 10.0.REDACTED
    Memory: 34.58 GB / 63.59 GB
  Binaries:
    Node: 20.13.1 - REDACTED
    Yarn: 1.22.10 - REDACTED
    npm: 10.5.2 - REDACTED
  Languages:
    Bash: 5.1.16
```

**Comment by Phoenixmatrix** [comment]
We hit the same issue, and it happened as we onboarded an engineer who hadn't used playwright before, leading to much co fusion.

Worse, we have a setup test, and that's the one that got selected by default, so we only had a single test.

I echo that comment. They should all be selected by default. It doesn't just impact the vs code extension: the playwright UI has the same behavior.

**Comment by yury-s** [comment]
### Note from maintainers

There were some significant changes in the latest release of the VS Code Extension.
If you have problems with running tests, selecting projects and configuration,
running setup projects etc. after upgrading to the the recent version of the extension,
please read our [FAQ](https://github.com/microsoft/playwright/issues/30882).

If the FAQ does not resolve your issue, please file a new bug.

**Comment by callpraths** [comment]
Thank you for the super-de-duper turnaround time on this!
