### ISSUE TITLE
[Feature]: Hovering over the filmstrip panel

### ISSUE THREAD

**Issue by chensce** [microsoft/playwright#30814]
### 🚀 Feature Request

Hovering over the filmstrip panel(00:00-00:05)，
Hovering over the action panel(00:06-00:11).
To create a unified user experience across all our panels.
Why not reuse the  picture in snapshot panel when hovering over the filmstrip panel

### Example

<img width="994" alt="Screen Shot 2024-05-15 at 09 50 58" src="https://github.com/microsoft/playwright/assets/93559562/b7768e03-f936-4811-8eae-b35a343c6349">

### Motivation

To create a unified user experience across all our panels.

**Comment by chensce** [comment]
https://github.com/microsoft/playwright/assets/93559562/ec9bce65-8214-43bf-a51a-877b7790a4ea

**Comment by yury-s** [comment]
What is your request?

**Comment by chenshuichao** [comment]
https://github.com/microsoft/playwright/assets/77186544/4d96c052-7abc-43c9-8bf3-a5b376451711

**Comment by chenshuichao** [comment]
make the filmstrip the same as the microsoft's clipchamp

**Comment by chenshuichao** [comment]
@yury-s @mxschmitt

**Comment by pavelfeldman** [comment]
There are more filmstrip frames than snapshots, so this would be misleading - you would click on a frame, but there won't be a snapshot.
