### ISSUE TITLE
[Bug]: .env file bypassed in debug mode 1.1.1

### ISSUE THREAD

**Issue by Fuut2000** [microsoft/playwright#30821]
### Version

1.1.1

### Steps to reproduce

log process.env in a test
start the test in normal mode: variables from .env are logged
start the test in debug mode: variables from .env are not logged (it worked in previous versions)

### Expected behavior

variables from .env are logged in debug mode

### Actual behavior

variables from .env are not logged

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 3.92 GB / 15.60 GB
  Binaries:
    Node: 20.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.89.1 - C:\Users\user\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 4.4.20 - C:\WINDOWS\system32\bash.EXE
  npmPackages:
    @playwright/test: ^1.43.1 => 1.44.0
    playwright: 1.43 => 1.44.0
```

**Comment by pavelfeldman** [comment]
How / where do you load the .env variables?

**Comment by Fuut2000** [comment]
with globalSetup.js and the dotenv package:

import { config as _config } from "dotenv";

function globalSetup() {
    _config({
        path: ".env",
        override: true,
    });
}

export default globalSetup;
