### ISSUE TITLE
Video testing is not working on playwright

### ISSUE THREAD

**Issue by subhakswain** [microsoft/playwright#30823]

**Comment by subhakswain** [comment]
I was trying to test a video which exist in a page. Let say it is playing or not. Controlled volume, Paused and again play it.But when trying to record it it is giving Internal error and video itself is not getting displayed when it is opening in record window.
Screen shot attached for same.
![image](https://github.com/microsoft/playwright/assets/81154669/dccc3dcc-c2b7-46c3-b914-99d52693b364)

**Comment by mxschmitt** [comment]
Have you tried using a [stable channel](https://playwright.dev/docs/browsers#media-codecs) like Google Chrome or Microsoft Edge? Only these browsers have the proprietary media codecs to play certain videos.

**Comment by subhakswain** [comment]
Yes I am using Google Chrome. And video is cloudflare video..

**Comment by yury-s** [comment]
If you want to report a bug, please file a new issue and follow our bug template, in particular provide a reproduction example and exact steps to reproduce.
