### ISSUE TITLE
[Bug]: 1.44.0 automatically closes the browser on test end (even with reuseBrower:true)

### ISSUE THREAD

**Issue by GuillaumeRoche** [microsoft/playwright#30828]
### Version

1.44.0

### Steps to reproduce

1. Use playwright 1.44.0
2. Create any test 
3. Set `"playwright.reuseBrowser": true,` 
4. Run it within VSC using the playwright extension
5. Wait for the end, the browser should remain open (works on 1.43.1, not on 1.44.0)

### Expected behavior

The browser (chromium) should remain open once the test ends

### Actual behavior

The browser (chromium) closes itself when the test end

### Additional context

I've tried to add some page.pause() or tiemouts to keep the browser alive as long as possible but this doesn't seem to have any impact. 

### Environment

```shell
System:
    OS: macOS 14.1.1
    Memory: 78.97 MB / 16.00 GB
  Binaries:
    Node: 22.1.0 - ~/.nvm/versions/node/v22.1.0/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v22.1.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by mxschmitt** [comment]
Do you have `video` enabled? This might be a duplicate of https://github.com/microsoft/playwright/issues/30779.

**Comment by GuillaumeRoche** [comment]
> Do you have `video` enabled? This might be a duplicate of #30779.

I did have 
`video: 'retain-on-failure',` 
This appears to be a duplicate as removing the video on local env did "fix"
