### ISSUE TITLE
[Feature]: Trace viewer: When using multiple browsers, I would like to see which browser is making which HTTP request

### ISSUE THREAD

**Issue by acanyasar** [microsoft/playwright#30822]
### 🚀 Feature Request

Right now when I use trace viewer for my tests, I can see the the network request that are made with a list. However for test cases that requires multiple browsers there is no way to distinguish for which browser is making what request. For a solution proposal, writing the browser name, next to the HTTP request would solve it. 

<img width="1684" alt="Screenshot 2024-05-15 at 14 17 29" src="https://github.com/microsoft/playwright/assets/71007923/2575e80a-155e-4f45-b736-f9da79ad3313">
 

### Example

It would help users to understand which browser is making which HTTP request and console logs.

For example in the network section add a new column called "browser name" and display it there. 

### Motivation

It would be beneficial for companies who are using multiple browser instances to test a product.

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/28903
