### ISSUE TITLE
[Bug]: Test info attached in html report in wrong format 

### ISSUE THREAD

**Issue by priyanka-vuddemari** [microsoft/playwright#30831]
### Version

1.44.0

### Steps to reproduce

Unable in reproduce in my local. Happening in company's machine 

### Expected behavior

Status code and response body from `test.info`should be attached properly to html report 

### Actual behavior

Status code and response body from `test.info` are having some formatting issues. Some alphanumeric code is attached  instead like below

Status code 
���rä����
Response
���rä���

### Additional context

code which I added  to attach the `test.info` 

```
 test.afterEach('attach test information', async( {} , testInfo) => {

    testInfo.attach("status code",  {body :  await response.status().toString() ?? {}, contentType : "text/plain"})
    testInfo.attach("Response",  {body :  JSON.stringify(await response.json()) ?? {}, contentType : "application/json"})
  
  } )
```

### Environment

```shell
System : Windows 11 

npm version : 9.6.7
node version : 18.17.1

playwright version : 1.44.0
```

**Comment by yury-s** [comment]
> Unable in reproduce in my local. Happening in company's machine

We need a reproduction to make this report actionable. Please file a new bug report once you have a repro.
