### ISSUE TITLE
[Bug]: Updated to Playwright Test for VSCode v1.1.1 and all test except one dissappeared from Test Explorer view

### ISSUE THREAD

**Issue by JohanAndreVisma** [microsoft/playwright#30839]
### Note from maintainers

There were some significant changes in the latest release of the VS Code Extension.
If you have problems with running tests, selecting projects and configuration,
running setup projects etc. after upgrading to the the recent version of the extension,
please read our [FAQ](https://github.com/microsoft/playwright/issues/30882).

---
### Version

v1.1.1

### Steps to reproduce

Upgrade to 1.1.1 some tests are gone

### Expected behavior

All test should show in Test Explorer after update

### Actual behavior

All but one of my test spec file's tests dissappeared from Test Explorer after I updated to v1.1.1
Downgraded to v1.0.22 and then all tests appeared again.
Before that i tried to restart VS Code but that had no effect

### Environment

```shell
Windows 10 Pro

Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz   2.30 GHz

Visual Studio Code 1.89.1
```

**Comment by seanmcne** [comment]
Thanks for the comment - I have this same issue, when I selected the correct config file then no tests would show up (at all), what I eventually realized is, I wasn't pressing the "OK" button in the setting to save the change 🤦‍♂️
![image](https://github.com/microsoft/playwright/assets/2292260/e3b4d37a-ac15-4b3f-b464-b0b707532db0)

**Comment by JohanAndreVisma** [comment]
@yury-s No I only have one playwright.config.ts file and I don't see a cog wheel to change anything. Probably because I just have one file.

**Comment by JohanAndreVisma** [comment]
The only thing shown in test explorer when using v1.1.1 is a setup. All normal tests are missing.

**Comment by Pasalc** [comment]
![image](https://github.com/microsoft/playwright/assets/43461852/61a10eb1-ab19-43e3-aeab-ac1883a5a50c)
Had same problem, you probably got your projects disabled by default. Check if at bottom of Testing side panel all your projects are enabled.

**Comment by JohanAndreVisma** [comment]
@Pasalc Thanks a lot! I was not aware that you could select to only see some tests, I'm quite new to using Playwright.
After selecting all my projects I can now see all my tests again.

**Comment by JohanAndreVisma** [comment]
So maybe this issue could be closed or maybe you can consider it a small usability bug that projects was disabled during update because it could probably confuse more noobs than me :-)

**Comment by Pasalc** [comment]
You are welcome, also seems like it's the same issue as https://github.com/microsoft/playwright/issues/30811

**Comment by Pasalc** [comment]
I agree with that

> So maybe this issue could be closed or maybe you can consider it a small usability bug that projects was disabled during update because it could probably confuse more noobs than me :-)

+1

**Comment by yury-s** [comment]
### Note from maintainers

There were some significant changes in the latest release of the VS Code Extension.
If you have problems with running tests, selecting projects and configuration,
running setup projects etc. after upgrading to the the recent version of the extension,
please read our [FAQ](https://github.com/microsoft/playwright/issues/30882).

If the FAQ does not resolve your issue, please file a new bug.
