### ISSUE TITLE
[Bug]: Unable to view the right context on Traces and Videos

### ISSUE THREAD

**Issue by gianhub16** [microsoft/playwright#30837]
### Version

1.44.0

### Steps to reproduce

Run via cmd line "SimpleTest" on https://github.com/gianhub16/simpletest repository
npx playwright test -g "SampleTest" --workers=3
Compare the traces and videos across browsers

### Expected behavior

Trace and Video should be recorded on the right context.

### Actual behavior

When I run the test, when the test changes the context, the right context has not been recorded. Specifically, in the trace the screens remain the same as in the old context and the video continues for the duration of the test but gets stuck on the context I closed!
It happens only on FIREFOX (Nightly 125.0.1 (64-bit))

### Additional context

It happens only on FIREFOX (Nightly 125.0.1 (64-bit))

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz      
    Memory: 3.22 GB / 15.75 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.1 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.89.1 - C:\Users\user\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.44.0 => 1.44.0
```

**Comment by dgozman** [comment]
Investigation notes:
- `nsScreencastService` operates on `nsIWidget` that corresponds to a window. Therefore, two tabs from the same window only capture the currently visible tab. There is no easy fix for this one, needs investigation.
- `nsScreencastService::Session::Stop()` calls `StopCapture()` which stops capturing for the whole window. With two tabs in a window, this stops capture in both pages when one of them closes, which is undesirable.
- The proposed fix for the previous issue is to introduce `webrtc::VideoCaptureModuleEx::StartCaptureCounted()` and `webrtc::VideoCaptureModuleEx::StopCaptureCounted()` that will increment/decrement a counter and call `StartCapture()`/`StopCapture()` respectively.
