### ISSUE TITLE
[Regression]: Playwright Test for VSCode can't find *.spec.ts files

### ISSUE THREAD

**Issue by lgkula** [microsoft/playwright#30843]
### Note from maintainers

There were some significant changes in the latest release of the VS Code Extension.
If you have problems with running tests, selecting projects and configuration,
running setup projects etc. after upgrading to the the recent version of the extension,
please read our [FAQ](https://github.com/microsoft/playwright/issues/30882).

---

### Last Good Version

Playwright Test for VSCode v.1.0.22

### First Bad Version

Playwright Test for VSCode v.1.1.1

### Steps to reproduce

IDE: VS Code
in playwright.config.ts add additional 'setup' project:
`projects: [
    {
      name: "setup",
      testMatch: /.*setup.ts/,
    },
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'],
        storageState: 'playwright/.auth/user.json'  
       },
      dependencies: ["setup"],
    },
]`

Playwrights tests in folder .\tests\
in files:
setup.ts
*.spec.ts

### Expected behavior

On the left-hand side of each setup-test and each regular test, a play button should be displayed to start the test in question.
The Test Explorer tab should display the names of setup tests and regular tests 

The plugin 'Playwright Test for VSCode v.1.0.22' correctly displayed all items for setup tests and regular tests

### Actual behavior

After updating to 'Playwright Test for VSCode v.1.1.1'.
The play button is displayed next to the setup-test. The play button does not display for regular tests.

Only setup tests are displayed in the test explorer. No regular tests are displayed.

### Additional context

Downgrade to 'Playwright Test for VSCode v.1.0.22' resolves the problem.
I can run all tests: setup tests and regular tests from the command line without using the Playwright Test for VSCode plug-in.

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1265U
    Memory: 17.77 GB / 31.69 GB
  Binaries:
    Node: 22.0.0 - C:\Programy\nodejs\node.EXE
    npm: 10.6.0 - C:\Programowanie\Repozytoria\masspayments\masspayments.automatic-tests\node_modules\.bin\npm.CMD
  IDEs:
    VSCode: 1.89.1 - C:\Programy\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.6.1 => 1.6.1
```

**Comment by lgkula** [comment]
I don't see here other projects than setup:
![Screenshot_41](https://github.com/microsoft/playwright/assets/85414318/d4b091e2-c730-41bc-a077-49ddb96fc669)

**Comment by gvaatstra** [comment]
Selecting the projects was the solution for me, but I think many people will run into this issue as it (apparently) only selects the first or only the setup and not your other projects. 
If this is the case, I'd say selecting all projects by default should be the solution

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/30803

**Comment by lgkula** [comment]
> ![image](https://private-user-images.githubusercontent.com/140422039/331169692-2ceaac08-f28d-445a-91bd-d11841385b44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4Nzc3NTMsIm5iZiI6MTcxNTg3NzQ1MywicGF0aCI6Ii8xNDA0MjIwMzkvMzMxMTY5NjkyLTJjZWFhYzA4LWYyOGQtNDQ1YS05MWJkLWQxMTg0MTM4NWI0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQxNjM3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDRjYzVmYWViMzRmOTIwZjRmY2Y2NzdiN2FjZjU0MzhiMGZjZGY3YWVkZGNkN2Y2Y2RlNWMyYjdkNTZkYTZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n-8RxHQVMKoLDrJ6CAQJ7VBMsQF7WBoVmcUVQJw1-EE) Are your projects selected?

You are right it is a feature not an bug. Even when I got the hint to select all projects I found it hard to find because I couldn't remember that the project was called Chrome. 
I agree with yury-s that a much better solution would be to select all projects by default.

**Comment by lucasxavierlucas** [comment]
I cant see the "projects" option, could some one help me to clarify it ?
![image](https://github.com/microsoft/playwright/assets/86451070/a29b4183-b414-413b-b163-97e3cff3a1da)

**Comment by lgkula** [comment]
It is new feature in plugin v. 1.1.1 
I read somewhere that in previous versions it was possible to set the project in the plugin configuration file.

**Comment by yury-s** [comment]
### Note from maintainers

There were some significant changes in the latest release of the VS Code Extension.
If you have problems with running tests, selecting projects and configuration,
running setup projects etc. after upgrading to the the recent version of the extension,
please read our [FAQ](https://github.com/microsoft/playwright/issues/30882).

If the FAQ does not resolve your issue, please file a new bug.
