### ISSUE TITLE
[Regression]: Forever running state

### ISSUE THREAD

**Issue by mkendallmcintosh** [microsoft/playwright#30849]
### Last Good Version

v1.41 and v1.42

### First Bad Version

v1.44.0

## Description
If you place a breakpoint in the code, and initiate debug on the test in the extension then you can get into a state where the extension says the test is running forever if you stop debugging, and you can't start new tests in the extension.

## Steps
1. clone https://github.com/mkendallmcintosh/playwright_bug/tree/main
2. place a breakpoint in vscode at line 14 in example.spec.ts test file which is inside the "get started link" test
3. open the playwright extension, and use the "Debug Test" button on the parent or the test to begin running the test
4. allow the test to run to the break point, and then use the vscode stop button to quit the test
5. note that you will get into a state of "0/0" tests running forever in the "TEST EXPLORER" section of the extension
6. note that the "Cancel Test Run" square button at the top of the extension does not help
7. note that you cannot run any tests in this state using the "Run Test" or "Debug Test" buttons in the extension 
8. note that vscode will have to be restarted to clear this state

![2024-05-16 09_21_49-example spec ts - playwright_bug - Visual Studio Code](https://github.com/microsoft/playwright/assets/34907353/bc3311c3-b5a3-40c1-bee9-01d22d904665)

### Expected behavior

If I stop the test using the vscode red sqaure debug stop button, then the browser closes and the test returns to a stopped state in the vscode extension

### Actual behavior

Stopping the test using the stop button in vscode debugger puts the extension into a forever running state, and no new tests can be ran until vsode is closed and reopened.  In this case I am NOT using the "Cancel Test Run" button in the extension.  I am stopping using the red square stop button in vscode debug mode.

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i7-1360P
    Memory: 18.99 GB / 31.64 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.89.1 - C:\Users\kmcintosh\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.2.26 - C:\Program Files\Git\usr\bin\bash.EXE
  npmPackages:
    @playwright/test: ^1.44.0 => 1.44.0
```

**Comment by yury-s** [comment]
This is the same as https://github.com/microsoft/playwright/issues/30808 and should be fixed in the next update of the extension.
