### ISSUE TITLE
[Bug]: Expect timeout is not used for locators

### ISSUE THREAD

**Issue by sayers24** [microsoft/playwright#30852]
### Version

1.43.1

### Steps to reproduce

My teams tests are reaching the test run timeout (config.timeout) on specific actions where it would make more sense to use the expect timeout (config.expect.timeout).

Given a config:
```
const config: PlaywrightTestConfig = {
  timeout: 3 * 60 * 1000,
  expect: { timeout: 2 * 1000 },
  ...
};
```
And a test with many interactions:
```
await page.getByLabel('Field 1').fill('Foo');
await page.getByLabel('Field 2').fill('Bar');
await page.getByRole('button', { name: 'Submit' }).click();
```

### Expected behavior

If "Field 2" is not visible/interactable, I would expect the test to error out after config.expect.timeout (2 seconds in this example)

### Actual behavior

If "Field 2" is not visible on the UI, the test will wait for the full config.timeout (3 minutes in this example)

### Additional context

We have set our config.timeout to a long time because we have long running tests (this is due to having to create a item before testing edit on that item as to maintain idempotency). So lowering the test run timeout would guarantee a failure even when things are healthy.

I realize we can add an `await expect(page.getByLabel('Field [#]')).toBeEditable();` before each `fill()` command, but this would double the number of lines and increase the dev effort for test authoring.

As we are scale out our tests, the test runs become exceedingly long when the results are delayed by a single locator (who's presence should be able to be determined within the config.expect.timeout range)

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 23.62 GB / 63.69 GB
  Binaries:
    Node: 20.11.1 - \Program Files\nodejs\node.EXE
    npm: 10.2.4 - \Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.89.1 - \AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: 1.43.1 => 1.43.1
```

**Comment by yury-s** [comment]
You can set [`actionTimeout`](https://playwright.dev/docs/test-timeouts#advanced-low-level-timeouts) option in [the config](https://playwright.dev/docs/api/class-testoptions#test-options-action-timeout).
