### ISSUE TITLE
[Bug]: slowMo option not slowing down commands

### ISSUE THREAD

**Issue by basickarl** [microsoft/playwright#30850]
### Version

1.43.1

### Steps to reproduce

launch options object (file: playwright-component-testing.config.ts):
```
    launchOptions: {
      // 1
      args: ['--start-maximized'],
      slowMo: 2000,
    },
```
command run:
`npx --no playwright test -c playwright-component-testing.config.ts audit --workers 1 --project='chromium' --trace='on' --ui`

Result in UI:

<img width="1538" alt="image" src="https://github.com/microsoft/playwright/assets/10507098/f225ab45-39a5-4d0c-be94-0a2c0cd36b4b">

### Expected behavior

Every playwright command slows down by 2000ms (e.g. `page.exposeFunction` etc.) .

### Actual behavior

Only the before hooks seems to slow down by 2000ms.

### Additional context

using @playwright/experimental-ct-react

Been reading https://playwright.dev/docs/debug#headed-mode and I'm seeming to follow what it says or?

### Environment

```shell
npx envinfo --preset playwright

  System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 5.98 GB / 64.00 GB
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 4.0.2 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by yury-s** [comment]
Only "user actions" are slowed down, see [this list](https://github.com/microsoft/playwright/blob/2734a0534256ffde6bd8dc8d27581c7dd26fe2a6/packages/playwright-core/src/protocol/debug.ts#L20-L64).

**Comment by basickarl** [comment]
> Only "user actions" are slowed down, see [this list](https://github.com/microsoft/playwright/blob/2734a0534256ffde6bd8dc8d27581c7dd26fe2a6/packages/playwright-core/src/protocol/debug.ts#L20-L64).

That is interesting! We are using a locator click event:
<img width="559" alt="image" src="https://github.com/microsoft/playwright/assets/10507098/4f3c5afd-984e-42fe-ac5b-c44a4bd6941c">

We are triggering this via the following command: `await page.getByTestId('ndl-drawer-close-button').click();`

Would this not constitute as being a "user action"?

**Comment by mfplunet** [comment]
Same issue, click is obviously a user action, and is not being slowed down.
