### ISSUE TITLE
[Bug]: Playwright ts/js method isDisabled() doesnot work as expected

### ISSUE THREAD

**Issue by nirmalprojects1988** [microsoft/playwright#30872]
### Version

1.44.0

### Steps to reproduce

Here is the code i.e. repro steps, in the current code, it clicks the next button even when it is disabled.

here is the URL https://demo.seleniumeasy.com/table-sort-search-demo.html 

This URL contains a web table having pagination with buttons previous and next.

```js
import { test } from "playwright/test";


test('Verify data pagination and enabled', async({page}) => {
    await page.goto('https://demo.seleniumeasy.com/table-sort-search-demo.html')
    async function countRowsOnPage() {
        const rows = await page.locator('#example tbody tr');
        const rowCount = await rows.count();
        console.log(`Rows on current page: ${rowCount}`);
        return rowCount;
    }
     let totalRowCount = 0;
    let hasNextPage = true;
    while (hasNextPage) {
        const currentPageCount = await countRowsOnPage();
        totalRowCount += currentPageCount;

        // Check if the next button is enabled
        const nextButton = await page.locator('#example_next')
        const isDisabled = await nextButton.isDisabled()
        if (isDisabled) {
            hasNextPage = false;
        } else {
            await nextButton.click();
            await page.waitForTimeout(1000); // Wait for table to update
        }
    }

    console.log(`Total row count across all pages: ${totalRowCount}`);
});
```

Here is similar kind of issue was raised and discussed in stackoverflow
https://stackoverflow.com/questions/68360209/unable-to-get-isdisabled-to-work-in-playwright

Discord discussion
https://discord.com/channels/807756831384403968/1054804523652231198/threads/1240934047295869009

### Expected behavior

isDisabled() should return false when button is enabled and vice versa.

### Actual behavior

isDisabled() method doesn't find if the element is in disabled state.

### Environment

```shell
System:
Mac Ventura 13.0.1
```

**Comment by yury-s** [comment]
By definition from https://playwright.dev/docs/actionability#enabled: "Element is considered enabled unless it is a <button>, <select>, <input> or <textarea> with a disabled property.". In you page the "Next" button is an `<a>` element with css class 'disabled' which is considered enabled according to the definition:

<img width="657" alt="image" src="https://github.com/microsoft/playwright/assets/9798949/06c5a0ae-00b8-419c-8aaf-f2b4d2b411c4">

You can replace you check with a custom code like this:

```js
        const isDisabled = (await nextButton.getAttribute('class'))?.includes('disabled');
```
