### ISSUE TITLE
[Bug]: The simple script test does not running in DEBUG mode in last version.

### ISSUE THREAD

**Issue by AlexandreBartie** [microsoft/playwright#30888]
### Version

1.44.0

### Steps to reproduce

1. Clone my repository (https://github.com/AlexandreBartie/html-view)
2. Open the tree test (left side) and view all scripts test available to run;
3. Try to run one script using DEBUG option.

The executions will fail and show this message:

> ***Error: Playwright Test did not expect test.describe() to be called here.***
> Most common reasons include:
> - You are calling test.describe() in a configuration file.
> - You are calling test.describe() in a file that is imported by the configuration file.
> - You have two different versions of @playwright/test. This usually happens
>   when one of the dependencies in your package.json depends on @playwright/test.
>     at TestTypeImpl._currentSuite (c:\DEVOPS\year-2024\study\html\html-view\node_modules\playwright\lib\common\testType.js:71:13)
>     at TestTypeImpl._describe (c:\DEVOPS\year-2024\study\html\html-view\node_modules\playwright\lib\common\testType.js:104:24)
>     at Function.describe (c:\DEVOPS\year-2024\study\html\html-view\node_modules\playwright\lib\transform\transform.js:256:12)
>     at Object.<anonymous> (c:\DEVOPS\year-2024\study\html\html-view\test\example.test.ts:3:6)

### Expected behavior

If a expected that DEBUG execution runs the same way with last version 1.1.2.

_**This issue does not happening in RUN mode, only DEBUG mode.**_

### Actual behavior

I expected that DEBUG execution runs the same way with last version 1.1.2.
![Playwright-vscode-extension-issue](https://github.com/microsoft/playwright/assets/56951490/e802f6cb-2058-4700-b6ee-d5e4ab2725c3)

### Additional context

**When I downgraded the version to 1.1.2 all my test scripts backed to works fine.**

There are a problem in this last version launched [1.1.3]

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
    Memory: 2.79 GB / 15.70 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.1 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.89.1 - C:\Users\barti\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.44.0 => 1.44.0
```

**Comment by mxschmitt** [comment]
Could you try the v1.1.3 extension update we released?

**Comment by AlexandreBartie** [comment]
v1.1.4 works fine!

Thank you!

**Comment by LakshmiVenkates** [comment]
which version you mean here, am also facing same issue- 

 "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {},
  "keywords": [],
  "author": "",
  "type": "module",
  "license": "ISC",
  "dependencies": {
    "@playwright/test": "^1.48.2",
    "@types/node": "^22.8.7",
    "fs-extra": "^11.2.0",
    "node": "^22.11.0",
    "node-rsa": "^1.1.1",
    "node.js": "^0.0.1-security",
    "npm": "^10.9.0",
    "prettier": "^3.3.3"
  }
