### ISSUE TITLE
[Bug]: Debugger is getting hanged while debugging through playwright extension

### ISSUE THREAD

**Issue by sat1591** [microsoft/playwright#30883]
### Version

1.1.2

### Steps to reproduce

1. Create a sample tests in playwright TS
2. Put a debugger on any line
3. go to playwright extension
4. select any test
5. click on debug to running the tests in debug mode

### Expected behavior

Expected the tests should start initiating the browser and hit the break point which I can debug.

### Actual behavior

After clicking the debug button the tests are not running anything. The debugger is just hanged like I showed in screenshot.
When downgraded my extension version to 1.0.22 the debugging is running as expected. This problem I have noticed in 1.1.1 and 1.1.2

![image](https://github.com/microsoft/playwright/assets/64651715/2511a319-daaf-4f26-8448-e2c9b812f8f3)

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 AMD EPYC 7763 64-Core Processor
    Memory: 4.90 GB / 15.95 GB
  Binaries:
    Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.88.1 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.43.1 => 1.43.1
```

**Comment by mxschmitt** [comment]
Please retry in v1.1.3 which we just released.

**Comment by mxschmitt** [comment]
Please retry in v1.1.4 which we just released.

**Comment by HarneyTester** [comment]
Hi, we have the same issue in v1.1.4

**Comment by pavelfeldman** [comment]
We can't reproduce this issue. We need exact steps to be able to reproduce: exact project repo or a zip file, exact steps to follow.

**Comment by HarneyTester** [comment]
I'll see what I can put together. I actually think its the same as https://github.com/microsoft/playwright/issues/30743 although this is closed.

**Comment by mxschmitt** [comment]
@HarneyTester, could you try v1.1.5?

**Comment by HarneyTester** [comment]
Yes all working for me now. Thanks!
