### ISSUE TITLE
[Bug]: The timeout error encountering when trying to take a screenshot with extended args for chromium --disable-blink-features=AutomationControlled

### ISSUE THREAD

**Issue by mhersim** [microsoft/playwright#30892]
### Version

0.4.4

### Steps to reproduce

Create a simple script to login to gmail with args
args = ['--disable-blink-features=AutomationControlled']
sign in and after user is signed in call command in script
page.screenshot()

### Expected behavior

screenshot taken successfully

### Actual behavior

E           playwright._impl._errors.TimeoutError: Page.screenshot: Timeout 30000ms exceeded.
E           Call log:
E           taking page screenshot
E             - waiting for fonts to load...

### Environment

```Text
- Operating System: [macOS 13.0]
- Chip: [Apple M2 Pro]
- Browser: [Chromium]
- Python Version: [3.12.3]
- Other info:
```

**Comment by Act0r1** [comment]
> We don't support use cases where Chrome is getting additional command line flags passed. These are at your own risk.

I don't pass any flag, but i also got this error, for example in version 1.41.1 everything works fine
