### ISSUE TITLE
[Bug]: browser.close cause test information to disappear in UI mode

### ISSUE THREAD

**Issue by tmasa** [microsoft/playwright#30894]
### Version

1.44.0

### Steps to reproduce

Create a very simple test that does not use any fixture, but creates a browser instance in the test case.

```typescript
test('Sample Test with browser.close', async () => {
        const browser = await chromium.launch();
        const page = await browser.newPage();
        await page.goto("https://playwright.dev");
        await browser.close();
    });
``` 

Execute the test in UI mode (npx playwright test --ui)

### Expected behavior

Test should be successful, test information (including screenshot, timeline, logs, etc.) should be visible in UI mode.

### Actual behavior

As soon as browser.close is called, test information is gone.

![image](https://github.com/microsoft/playwright/assets/2428458/62de8e82-13b6-4592-8078-617c0703fcda)

### Additional context

It works fine when using page.close instead of browser.close

![image](https://github.com/microsoft/playwright/assets/2428458/78887d5c-f96f-4648-a4ea-db74c82f47e8)

Discord post: https://discord.com/channels/807756831384403968/1240014510593413120

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-13800H
    Memory: 15.39 GB / 31.69 GB
  Binaries:
    Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.89.1 - C:\Users\<me>\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.44.0 => 1.44.0
```

**Comment by pavelfeldman** [comment]
browser.close is not a graceful exit, so you should call await page.close() (or context.close()) before the test ends.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
