### ISSUE TITLE
[Feature]: Add Support for bypassCSP option in browserType.launch

### ISSUE THREAD

**Issue by fawazahmed0** [microsoft/playwright#30897]
### 🚀 Feature Request

Support `browserType.launch({bypassCSP : true})`

### Example

```
chromium.launch({bypassCSP : true})
```

### Motivation

`bypassCSP` option is already available for:
```
chromium.launchPersistentContext({"./datadir", bypassCSP : true})
browser.newContext({bypassCSP : true})
browser.newPage({bypassCSP : true})
```
but not available for `chromium.launch({})`

**Comment by pavelfeldman** [comment]
It is a context-level option, so it is passed when creating the context, including on chromium
