### ISSUE TITLE
[Feature]:  Search option in network tab of trace

### ISSUE THREAD

**Issue by YashSC1** [microsoft/playwright#30893]
### 🚀 Feature Request

Currently if we want to search response of a particular api call in the network tab of trace , we need to scroll through all the requests to find the right one. Can there be a search field which can filter api call on the basis of search text. Something similar to chrome network tab.

### Example

<img width="360" alt="Screenshot 2024-05-18 at 8 57 40 PM" src="https://github.com/microsoft/playwright/assets/104764732/b6d0793b-61ee-4956-a8f0-059f9d60edd0">

Adding a filter option similar to chrome network tab in trace network tab.

### Motivation

If any particular test case failed and user want to look for responses of api calls on that particular screen , they have to either filter that section in timeline or scroll through the complete list of network calls. If user already knows the api endpoint they are looking for , they can easily do a partial text search and search the particular api call and look for the response.

**Comment by marshmn** [comment]
Agree - this would be useful.

**Comment by MarkusJLechner** [comment]
I was about to write the same request.

In the example below, there are 400 requests, with almost all having no value (resources, 3rd party requests). Finding the one request which fails is cumbersome, and a filter would instantly solve this issue.
![Example](https://github.com/microsoft/playwright/assets/48199873/72e0f357-e8e8-4ecc-a073-a13fa7978fb8)

Additionally, it would be beneficial to see `!ok` requests directly in the tab.
![Tab with !ok Requests](https://github.com/microsoft/playwright/assets/48199873/0d114ae3-b306-4b0a-9660-79d96c3ec505)

Does anyone know what the "Route" column does? The [documentation](https://playwright.dev/docs/trace-viewer#network) does not explain this. Additionally, it always seems to be empty.

---

Sentry handles filtering well:
![Sentry Filtering](https://github.com/microsoft/playwright/assets/48199873/c7e78ed2-9606-4898-8092-b1db956f12db)
![Sentry Filtering 2](https://github.com/microsoft/playwright/assets/48199873/f3e7fae9-fe1f-40ff-8653-2fbc877a0065)

A nice feature is that the filter list grows with the various requests, showing fewer filters for fewer requests.
![Growing Filter List](https://github.com/microsoft/playwright/assets/48199873/3dbf5a8a-5235-45a0-a74a-06b61bb91ccd)

**Comment by mxschmitt** [comment]
This seems implemented in [v1.47.0](https://github.com/microsoft/playwright/releases/tag/v1.47.0) - if you still miss something there, please file a separate feature request, thanks!
