### ISSUE TITLE
[Docs]: Documentation for `--grep` command line argument gives incorrect string used for matching

### ISSUE THREAD

**Issue by marshmn** [microsoft/playwright#30895]
### Page(s)

https://playwright.dev/docs/test-cli#reference

### Description

The documentation for `--grep` states this regarding the string that is used for matching:
"The regular expression will be tested against the string that consists of the test file name, `test.describe` titles if any, test title and all test tags, separated by spaces, e.g. `my-test.spec.ts my-suite my-test @smoke`."

In reality, from my own testing, it appears that the string used to match against also includes the project name.

For example, this fails to match:
```
--grep "^mytestfile.spec.ts\smy\stest$"
```

Whereas, this does match:
```
--grep "^chromium\smytestfile.spec.ts\smy\stest$"
```

This makes a difference if you are trying to match on the whole string in order to avoid potential sub-string matches.

**Comment by marshmn** [comment]
FYI: this issue came to light through discussion in a Discord thread: https://discord.com/channels/807756831384403968/1241331291425869844

**Comment by pavelfeldman** [comment]
Would you be interested in sending a PR?

**Comment by marshmn** [comment]
Yes, sure - will do.
