### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ramam-v** [microsoft/playwright#30900]
### Version

Playwright Test for VSCode version 1.14

### Steps to reproduce

1. On VSCode please update the extenstion Playwright Test for VSCode to version 1.1.4
2. Try executing your existing tests and iif your project uses a Global Setup then you will notice that Global Setup is not triggered

### Expected behavior

Global Setup should be executed before your test execution starts

### Actual behavior

Global Setup is skipped and test execution is started

### Additional context

Reverted my add-in to v1.0.22 and able to execute the tests with GlobalSetup

### Environment

```shell
Windows 10
Chrome Browser
TypeScript
```

**Comment by mxschmitt** [comment]
Inside your code there is a `commonFuncs.goto();` which you don't await which is causing such behaviour. We recommend TypeScript in combination with [this ESLint plugin](https://playwright.dev/docs/best-practices#lint-your-tests) in order to prevent such issues.
