### ISSUE TITLE
[Bug]: Error closing browser

### ISSUE THREAD

**Issue by utibeabasi6** [microsoft/playwright#30902]
### Version

1.44.0

### Steps to reproduce

Run the following code within a lambda function using the [chromium layer](https://github.com/Sparticuz/chromium)
```javascript
const browser = await playwright.launch({
    args: [...chromium.args, '--enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb'],
    executablePath: await chromium.executablePath(),
  });
  const page = await browser.newPage({ bypassCSP: true, colorScheme: 'dark' });

  await page.setViewportSize(defaultViewport);

  await page.route('**', (route) => {
   # Do something
  });

  await page.goto(your-url);

  const screenshotBuffer = await page.screenshot();

  await page.unrouteAll({ behavior: 'wait' });

  await page.close();

  await browser.close();
```

### Expected behavior

The screenshot is created successfully

### Actual behavior

An error occurs when calling browser.close()

![image](https://github.com/microsoft/playwright/assets/66149718/e5237816-6ff6-4b49-8fae-83ddee4bde3b)

### Environment

```shell
Environment is AWS lambda
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!

(no imports, undefined variables etc.)
