### ISSUE TITLE
[Bug]: Playwright not working and not showing run icons inside the VSCODE(1.89.1) editor. 

### ISSUE THREAD

**Issue by Balakumar777** [microsoft/playwright#30909]
### Version

1.1.1 and above

### Steps to reproduce

Install the playwright version above 1.1.1 with VSCODE version 1.89.1

### Expected behavior

Should show the test execution icons and should work as expected. 

### Actual behavior

It is not show the test cases in the Playwright extension treeView and throws the error like below 
![image](https://github.com/microsoft/playwright/assets/45594347/ddeabbc0-0c79-4b2f-b91c-7c51b4076f31)

### Environment

```shell
Windows 10.0.19045
Vscode 1.89.1
Chormium 120.0.6099.291
Electron 28.2.8
Node JS 18.18.2
```

**Comment by mxschmitt** [comment]
Which Playwright version are you using? Could you provide us your repository structure? Does it happen with a [newly created project](https://playwright.dev/docs/intro)?

**Comment by Balakumar777** [comment]
> Which Playwright version are you using? Could you provide us your repository structure? Does it happen with a [newly created project](https://playwright.dev/docs/intro)?

@mxschmitt This happened in the existing project, Not a newly created one.  I've attached the sample below, But it is working perfectly on version 1.0.22
![image](https://github.com/microsoft/playwright/assets/45594347/8e3f0876-ba16-4c62-9271-93f0b05ed260)

**Comment by x-typo** [comment]
Am getting the same thing. Had to reinstall to 1.0.22 version to get it to work.

**Comment by pavelfeldman** [comment]
What are your Playwright and VSCode extension versions?

**Comment by Balakumar777** [comment]
> What are your Playwright and VSCode extension versions?

@pavelfeldman My Vscode version is 1.89.1 and the Playwright version is 1.1.4. FYI) This issue is happens in all previous versions of recent playwright updates. 

- 1.1.1
- 1.1.2
- 1.1.3
- 1.1.4

![image](https://github.com/microsoft/playwright/assets/45594347/73de9eac-5b66-4b73-88c4-e235bde926ee)
![image](https://github.com/microsoft/playwright/assets/45594347/d9ea2919-9aaa-4335-bd9b-80395cdf25b6)

**Comment by mxschmitt** [comment]
Which Playwright (NPM) version are you using?

does it happen in a new project?

could you share an example project with us, if not?

**Comment by Balakumar777** [comment]
@mxschmitt I think after I update the playwright version into 1.44.0 then it starts working, the thing is in my existing project I am using some older version of playwright, so after I updated the playwright vscode extension it is not working properly.  

1) I think we can fix this issue by update the playwright to latest version globally and update the extension to latest version of 1.1.5. 
2) Upgrade the playwright version in the existing playwright test project, from older version into newer version and update the extension to latest version will solve the issue.

**Comment by mxschmitt** [comment]
@x-typo we need a reproduction and more details in order to act on it. Would it be possible to share your repository with us? Does this happen on a [newly created Playwright project](https://playwright.dev/docs/intro)?

**Comment by mathieu-fournier** [comment]
I had the same problem with 1.33.0. 
**Updating to 1.44.0 fixed the issue.** 

All the issues I had before : 
Red : The test does not show up in the test explorer. 
When I hit the debug button (Green), Two tests are started (Blue), And it goes on forever (Pink), I must close VSCode for it to end.  
In Yellow : note I only have one playwright config. I've seen errors with multiple config before.
![image](https://github.com/microsoft/playwright/assets/82905333/3948b6ee-8e6d-425f-aa50-8447adef30f4)

Hope it helps resolving the issue. Keep up the good work. playwright is great (: !

**Comment by pavelfeldman** [comment]
These should be fixed in the latest extension. Please file a new issue for any outstanding problems!
