### ISSUE TITLE
[Bug]: Exception when using functions (tests are run in a infinite loop)

### ISSUE THREAD

**Issue by ydkL** [microsoft/playwright#30905]
### Version

1.43.1

### Steps to reproduce

1. Clone my repo https://github.com/ydkL/playwrightExamples.git
2. npm install
3. npx playwright test ./tests/exercise_1.spec.js
4. You should see the error come up

### Expected behavior

I expected test run without any error.

### Actual behavior

I use a function call like a pre condition in my test(exercise_1.spec.js). All steps are run, After steps finished, test run is starting again and a bug happened. 

### Additional context

When I write this case without using extra function (exercise_1_man.spec.js), no error occurs.

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    Memory: 5.32 GB / 15.35 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
```

**Comment by mxschmitt** [comment]
Inside your code there is a `commonFuncs.goto();` which you don't await which is causing such behaviour. We recommend TypeScript in combination with [this ESLint plugin](https://playwright.dev/docs/best-practices#lint-your-tests) in order to prevent such issues.
