### ISSUE TITLE
[Feature]: need a feature where we can execute datadriven testcases

### ISSUE THREAD

**Issue by krishnasravani** [microsoft/playwright#30906]
### 🚀 Feature Request

currently in playwright, we are able to execute just a single entry of testdata for a given test. But need a feature where we can execute multiple entries of testdata for the same test-analogous to dataprovider annotation in testng

### Motivation

a single spec file can be used only for a single usecase of testdata. To cover all the cases, we need a robust framework which supports datadriven testing

**Comment by pavelfeldman** [comment]
Please be more specific, provide exact examples, motivation, code, context. It is unclear what you are asking for.
