### ISSUE TITLE
[Bug]: Can't stop a test that is running, tests never stop running

### ISSUE THREAD

**Issue by andermoranPro** [microsoft/playwright#30919]
### Version

1.1.4

### Steps to reproduce

1. yarn
2. start local server (yarn start ...)
3. Try to run a test or stop one

### Expected behavior

Test runs or test canrls

### Actual behavior

Test runs forever and cannot be stopped with cancel button

### Additional context

I am an engineer at Microsoft if you have more questions or what to see a live repro.
andermoran@microsoft.com

### Environment

```shell
Windows devbox
```

**Comment by pavelfeldman** [comment]
Please follow the BUG issue template to file something we can reproduce. Thanks!
