### ISSUE TITLE
[Docs]: Add a section on how to access root element that locator matched

### ISSUE THREAD

**Issue by Deanozk** [microsoft/playwright#30914]
### Page(s)

I have been reading the documentation and running playwright script in debugger trying to figure out a very basic thing. I want to know what is the underlying html element that a given locator matched up to.  For example lets say I am matching some headings on a page.  Ie first_heading = page.get_by_role("heading", name="Introduction")  and second_heading = page.get_by_role("heading", name="Details")   I should be able to easily look up if the root element that the locator matched up to was h1, h2, h3 etc.  How do I get this?   It's not clear from the documentation. inner_html() yields <locator ...> not the <h1 ...> and the element object is not well enough documented to see how to pull out h1 as the element for example. Now I realize that the goal of locators is to abstract these things like h1, h2 etc but I need to know the type of the element it matched up with so I can check if its a heading or a subheading etc.   

### Description

Document clearly how to access all information about the base elment that a given locator matched on the page.  Was it h1, h2, p etc.  Clearly indicate how to get this. Do we need to generate string of html elements? How? is there a way to get elment type? etc.  Please document this. ANd in the meantime I need to know how to do this.

**Comment by Deanozk** [comment]
It seems that the locator must have this information? But where is it????

**Comment by pavelfeldman** [comment]
https://playwright.dev/docs/api/class-locator#locator-evaluate - this should help.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
