### ISSUE TITLE
[Feature]: some tests require multiple browsers and some do not

### ISSUE THREAD

**Issue by asdf23** [microsoft/playwright#30911]
### 🚀 Feature Request

I would like to be able to runa suite of tests, and have some of them only run in a single browser other might use all available browsers.

### Example

Testing for JavaScript bugs vs testing an API

### Motivation

My tests are divided up by how I want to run them, not the data I want to get out.

**Comment by pavelfeldman** [comment]
It is the easiest to put all tests that require only single browser into a separate file or a project. Then either only run this project using one browser, or skip all but one browser in that file.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by asdf23** [comment]
And then what.. Merge up my test results, making sure I get the screenshots , annotations, videos etc.....??
