### ISSUE TITLE
[Feature]: Different environments have a different number of machines

### ISSUE THREAD

**Issue by asdf23** [microsoft/playwright#30917]
### 🚀 Feature Request

My local dev environment has one setup, dev another, QA and prod also. I have a different different numbers on of servers and supporting servers to the with this. Playwright doesn't deal with that well.

### Motivation

I want to support multiple ama complex environments

**Comment by pavelfeldman** [comment]
Unclear what you mean.

**Comment by asdf23** [comment]
Playwright works great when you have 1 dev 1 qa and 1 prod machine to test.
But when you have 6 address lookup system in prod 2 in qa, 1 in dev....
