### ISSUE TITLE
[BUG]- Trying to get expect-playwright to work

### ISSUE THREAD

**Issue by ajaykhobragade** [microsoft/playwright#3092]
Expecting someone to respond this issue below, originally opened for jest -playwright but no one respond yet there>>

https://github.com/playwright-community/jest-playwright/issues/232

**Comment by arjun27** [comment]
Thanks @ajaykhobragade. Can you share examples of assertions in your tests? We won't be able to help with expect-playwright, but can check if your scenario is covered by Playwright directly.

We have an [assertions guide](https://playwright.dev/#version=v1.2.1&path=docs%2Fassertions.md&q=), in case that helps.

**Comment by mxschmitt** [comment]
Hi @ajaykhobragade it seems like `expect-playwright` is not installed correctly. Try to move the `setupFilesAfterEnv` option over to your Jest configuration.

**Comment by ajaykhobragade** [comment]
Perfect, that works fine! Thanks @mxschmitt 
@arjun27 , i would try that assertions at some point soon as well, Thanks for reply again.
