### ISSUE TITLE
[Bug]: Video testing is not working on playwright

### ISSUE THREAD

**Issue by subhakswain** [microsoft/playwright#30929]
### Version

1.44.0

### Steps to reproduce

Step 1-
Navigate to any page which has cloudflare video. example :-
https://www.cloudflare.com/en-gb/lp/pg-stream-single-platform/?utm_medium=cpc&utm_source=google&utm_campaign=2023-q4-acq-gbl-developers-st-ge-general-paygo_mlt_all_g_search_bg_exp__dev&utm_content=stream&gad_source=1&gclid=EAIaIQobChMI3-m9k7aehgMVk8NMAh03nA4gEAAYASAAEgI5nvD_BwE&gclsrc=aw.ds
2)  In right side you can see one video is present..
3) Let say I am clicking play button,then doing pause,controlled volume and it is working. Same needs to automate in playwright
4) Click playwright recording option
5) One new window will open. Paste the url. example: https://www.cloudflare.com/en-gb/lp/pg-stream-single-platform/?utm_medium=cpc&utm_source=google&utm_campaign=2023-q4-acq-gbl-developers-st-ge-general-paygo_mlt_all_g_search_bg_exp__dev&utm_content=stream&gad_source=1&gclid=EAIaIQobChMI3-m9k7aehgMVk8NMAh03nA4gEAAYASAAEgI5nvD_BwE&gclsrc=aw.ds

### Expected behavior

Expected Result: With playwright I can do play,pause, volume control how I am doing manually.

### Actual behavior

Actual Result: Video which is present it is showing internal error occured. More detail attached in screenshot.
<img width="940" alt="error_cloudflare" src="https://github.com/microsoft/playwright/assets/81154669/a7c62fea-b9a9-416f-beea-bd13e36fc033">

### Environment

```shell
Window 64 bit. Browser:- Chrome
```

**Comment by pavelfeldman** [comment]
The video control does not load for me, gives me "unknown error" as on the screenshot below.
<img width="575" alt="Screenshot 2024-05-21 at 8 41 11 AM" src="https://github.com/microsoft/playwright/assets/883973/ebea4516-ad8b-42c4-ae4c-1cddf2ddc3b6">

 Cloudflare is also known for blocking requests from the automation browsers. Do you have another repro?
