### ISSUE TITLE
[Feature]: retry a fail request

### ISSUE THREAD

**Issue by tqobqbq** [microsoft/playwright#30928]
### 🚀 Feature Request

Goal: I want to rety a failed request,with a proxy or just fulfill a default response

### Example

```

def requestfailed_callback(request):
    retry(request)
page.on('requestfailed',requestfailed_callback)
```

**Comment by pavelfeldman** [comment]
Sounds like you are listening to the page requests and some of them fail, and you want to retry them. You are only observing what browser is doing here, you can't tell browser to retry a request and to use the outcome of the new retry in its logic.
