### ISSUE TITLE
[Feature]: record and run in codegen inspector

### ISSUE THREAD

**Issue by chensce** [microsoft/playwright#30921]
### 🚀 Feature Request

As we know the codegen can not record every action now.for example drag ,hover,
so when I authoring the test script through the recording ,when the inspector can not work I want to pause the recording the inspector,I can manually write the action,then I can run this action through the inspector,after the running this action I can continue the recording.

### Example

![image](https://github.com/microsoft/playwright/assets/93559562/64baafe8-5c8d-47f9-aeab-60f516aae0e7)

<img width="566" alt="Screen Shot 2024-05-16 at 09 57 20" src="https://github.com/microsoft/playwright/assets/93559562/4bf9d511-edd6-4733-8e43-929753dfd284">

### Motivation

when I authoring the test script through the recording,i have a continue experience.

**Comment by pavelfeldman** [comment]
You can do that if you install our Playwright VSCode Extension.
