### ISSUE TITLE
[Feature]: supports switching to another application to handle popup issues.

### ISSUE THREAD

**Issue by 406722575** [microsoft/playwright#30925]
### 🚀 Feature Request

After installing a third-party Office plugin, a popup window from the plugin appears when submitting a form. Conventional popup handling methods are unable to close this popup window; it requires switching to the application of the popup. At present, there seems to be no method in Playwright to switch between applications.

### Motivation

Hoping to switch to the third-party application to address the popup issue.

**Comment by pavelfeldman** [comment]
That's outside of the scope for Playwright.
