### ISSUE TITLE
[Feature]: Last-failed parameter and .last-run.json as combination of each blob-report

### ISSUE THREAD

**Issue by OSnuszka** [microsoft/playwright#30924]
### 🚀 Feature Request

Is it possible to set a mode where .last-run works by merging blobs? This arises somewhat from the construction of my CI/CD - I would like to rerun tests in the context of the entire test suite (after merging blobs).
In my setup, each test node/blob generates its own .last-run file in the artifacts, and after moving to the next stage, the blobs are merged, but only the `.last-run.json` file from the last blob remains. I could adjust the CI/CD to add a timestamp to each `.last-run` file  and then combine the `"failedTests": [].` keys. However, I'm wondering if there's a way to organize this on the Playwright side.

### Example

It seems to me that it would work as follows: 
when I have the parameter `--shard=${CI_NODE_INDEX}/${CI_NODE_TOTAL}` set.
`.last-run.json` files have an analogous checksum added as for a dedicated `blob-report` file. And later when merging the blobs with the merge-reports command, a single `.last-run.json` file is created that is a combination of all these blob-runs.

### Motivation

It seems to me that the problem may be more widespread with the increasing use of the --last-failed function

**Comment by pavelfeldman** [comment]
.last-run is only intended to be used with the inner loop scenario (local development). If you need something similar for CI/CD, a small reporter that collects test results, per shard or post-merge would be a better way. Then you would re-run these tests by file/line if needed.

**Comment by OSnuszka** [comment]
Currently I have already solved this with a script that merges .last run files from bloobs, then this file is used within a dedicated job that runs the test with the `-last-failed` parameter

**Comment by 2Fake** [comment]
@OSnuszka Could you share your script to merge?

**Comment by OSnuszka** [comment]
> @OSnuszka Could you share your script to merge?
Sure,
as a first step, every automation test shard should have a unique name for its .last-run.json file:

`mv test-results/.last-run.json test-results/.last-run-${CI_NODE_INDEX}$(date +"%H%M%S.%6N").json`

Next, I have a dedicated step to merge all .last-run*.json files into one master file. This step executes the following bash script:

```
#!/bin/bash

directory="./test-results"
output_file="$directory/.last-run.json"

echo '{"status": "passed", "failedTests": []}' > "$output_file"

all_failed_tests=()

for file in "$directory"/.last-run*.json; do
  echo "Processing file: $file"
  failedTests=$(jq -r '.failedTests[]?' "$file")

  for test in $failedTests; do
    all_failed_tests+=("$test")
  done
done

if [ ${#all_failed_tests[@]} -ne 0 ]; then
  jq --argjson tests "$(printf '%s\n' "${all_failed_tests[@]}" | jq -R . | jq -s .)" '.status = "failed" | .failedTests = $tests' "$output_file" > "${output_file}.tmp" && mv "${output_file}.tmp" "$output_file"
else
  echo '{"status": "passed", "failedTests": []}' > "$output_file"
fi

echo "Aggregated failed tests saved to $output_file"
```
After that, I can use:
```
npx playwright test --last-failed --shard=${CI_NODE_INDEX}/${CI_NODE_TOTAL}
```
to execute all failed tests from previous stages.

**Comment by raja28april** [comment]
But `mv test-results/.last-run.json test-results/.last-run-${CI_NODE_INDEX}$(date +"%H%M%S.%6N").json` will make the job to success state right?

I see a step `Downloading previous test reuslts` and says downloading previous test result from job: <previous jobId> where it is storing the test-result?

**Comment by 2Fake** [comment]
I don't have access to my ci code within the next 2 weeks, but as far as I remember I do this move in the after_script section of gitlab ci so it is executed no matter what the test result ist
