### ISSUE TITLE
How to set UI scaling to 2x?

### ISSUE THREAD

**Issue by skhaz** [microsoft/playwright#30933]
### Please do not submit this issue.

- [X] I understand

**Comment by skhaz** [comment]
I am using a machine who runs in 4K, and when I open Plawright, it is small, because I use UI scaling 200% and it opens at 100%.

How to launch Playwright with 200% UI scaling?

**Comment by StanislavGrishaev** [comment]
asfaik because of browser zoom is not officially supported (https://github.com/microsoft/playwright/issues/2497) you could do like this `await page.evaluate("document.body.style.zoom=2.0")`

**Comment by skhaz** [comment]
Why the issue was closed?
