### ISSUE TITLE
[Feature]: Intercept multipart requests

### ISSUE THREAD

**Issue by cserby** [microsoft/playwright#30932]
### 🚀 Feature Request

I'm testing a Web Application that's interacting with a GraphQL backend implementing [Graphql-uploads](https://github.com/jaydenseric/graphql-multipart-request-spec).

I'm trying to use Playwright's request interception functionality, but I have no means to intercept the request body in case if `Content-Type: multipart/form-data` is set.

All [`Request.postData*`](https://playwright.dev/docs/api/class-request#request-post-data) seem to return `null`.

### Example

```
      await page.route(/gowish.com\/graphql/, async (route) => {
        const contentType = route.request().headers()["content-type"];

        if (contentType === null) {
          throw new Error("contentType is null");
        } else if (contentType.includes("multipart/form-data")) {
          console.error('graphql upload?');
 
          // FIX: I'm having the problem here, I have no means to read the request's body
  
          await route.abort();
        } else if (contentType.includes("application/json")) {
          const query = route.request().postData();

          if (query === null) {
            throw new Error("query is null");
          }

          await route.fulfill({
            status: 200,
            body: await backendMock.query(
              JSON.parse(query) as {
                operationName: string;
                query: string;
                variables?: Record<string, unknown>;
              },
            ),
          });
        } else {
          throw new Error(`Unexpected request content-type: ${contentType}`);
        }
      });
 ```

### Motivation

After https://github.com/microsoft/playwright/issues/28070 Playwright supports _sending_ the kind of multipart requests that allows us testing our Graphql-uploads enabled API. It'd be nice if we could use Playwright for testing the frontends _consuming_ this same API.

**Comment by pavelfeldman** [comment]
> All [Request.postData*](https://playwright.dev/docs/api/class-request#request-post-data) seem to return null

Could you provide a self-contained example that we could use to reproduce and fix this? Also, could you try `npm i @playwright/test@next` as there was a fix for the post data recently.

**Comment by cserby** [comment]
@pavelfeldman Please find a test case illustrating this issue in https://github.com/microsoft/playwright/pull/30960.

**Comment by cserby** [comment]
@pavelfeldman 
The idea in my test case was to _mimic_ the behavior of our Web App integrating https://github.com/jaydenseric/apollo-upload-client by using `request.post`, having a multipart body.

(The real-world test case for me is filling a form having a file upload field, and then intercepting, and asserting on the GraphQL request being made when I click on Submit).

If I read your comment right, is `context.request.post` not supposed to be intercepted by `context.route`?
In that case I'm looking for help on how to provide a minimal reproduction example.

I'd need to host a web application along the lines of https://github.com/jaydenseric/apollo-upload-examples, and use that in my test case for Playwright? :thinking:

**Comment by cserby** [comment]
OK, replaced `context.request.post` with `page.evaluate(() => fetch)`. And the test now passes. I rest my case.
