### ISSUE TITLE
[Bug]: Snapshot Path is Unexpectedly Auto-Shortened

### ISSUE THREAD

**Issue by gwendolyngoetz** [microsoft/playwright#30947]
### Version

1.44.0

### Steps to reproduce

1. Clone https://github.com/gwendolyngoetz/playwright-path-naming
2. Start the simple web server `node server.js`

To view previous behavior

1. cd playwright-v1.42.1
2. npm install
3. npx playwright install chromium
4. npx playwright test
5. You will see a failed snapshot image compare, expected.
6. Look at the paths for attachments 2 and 3

To view the changed behavior do the same steps as above, but go into the playwright-v1.43.0 directory.

This occurs starting on v1.43.0 and later.

### Expected behavior

Prior image path was something like this:

`tmp/test-output/example-lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit-sed-do-eiusmod-tempor-incididunt/example_test/one-two-three-four-actual.png`

### Actual behavior

On v1.43.0 or later (including next) the path and file name have changed. Part of the path is now replaced with `fcf62` in this example and the file name has been merged with what used to be an additional directory.

`tmp/test-output/example-lorem-ipsum-dolor--fcf62-o-eiusmod-tempor-incididunt/example-test-one-two-three-four-actual.png`

### Additional context

I don't actually care about the full path naming per se. What I need the original format for is to be able to do the following:
- Copy the updated version of the image into a folder along with it's test name path. Example: `updated_images/example_text/one-two-three-four.png`
- Take the original, diff, and updated versions and stitch them together into a single file. This was something Jest was doing before we migrated to the Playwright runner and folks wanted to keep it since it can be quicker than always getting an artifact from github and running the trace viewer.

I can code around the shortened path, but at the point where in the global teardown when I do the image juggling I don't have any info to work with except the path when trying to determine how to change `example-test-one-two-three-four-actual.png` into `example_text/one-two-three-four.png`.

### Environment

```shell
System:
    OS: Linux 6.8 Ubuntu 24.04 LTS 24.04 LTS (Noble Numbat)
    CPU: (32) x64 AMD Ryzen 9 7950X3D 16-Core Processor
    Memory: 40.47 GB / 62.02 GB
    Container: Yes
  Binaries:
    Node: 22.0.0 - ~/.config/nvm/versions/node/v22.0.0/bin/node
    npm: 10.5.1 - ~/.config/nvm/versions/node/v22.0.0/bin/npm
  IDEs:
    VSCode: 1.89.1 - /usr/bin/code
  Languages:
    Bash: 5.2.21 - /usr/bin/bash
  npmPackages:
    @playwright/test: 1.43.0 => 1.43.0
```

**Comment by pavelfeldman** [comment]
It sounds like there is a feature request implied, could you be more explicit about the feature you are requesting? Note that there are snapshotPathTemplates available in Playwright and you can access all the exact attachment names from the test report (either by means of API or by means of JSON report). All the file manipulations should be pretty straightforward with those, but knowing exact request would help verifying it.

**Comment by mxschmitt** [comment]
Sounds related to https://github.com/microsoft/playwright/issues/30693.

**Comment by gwendolyngoetz** [comment]
@pavelfeldman I completely forgot about json being a report type. Using this solved my problem. Thanks!
