### ISSUE TITLE
[Bug]: Playwright Unable to access and delete Leads on Dynamics 365

### ISSUE THREAD

**Issue by Mukund1302** [microsoft/playwright#30944]
### Version

Version 1.44.0

### Steps to reproduce

I am trying to access leads created on Microsoft Dynamics 365 CRM and then delete them.  

There are 2 tests running, 1 which is creating a lead, and 1 which is Accessing dynamics and creating the newly created lead.  

Playwright is having problems with accessing those newly created leads. 

It is also CRITICAL that only the newly created lead is accessed and deleted, As I do not want to delete any other important data.  

To reproduce/verify the bug, Follow the steps,
1. Open Dynamics 365, go under Lead management on the left hand side.
2. Click on lead, and create a new lead, add some name example(Automated Test) and save the lead.
3. Refresh the Lead tab and verify that the Automated Test lead has been created.
4. Using codegen, quickly create a short playwright script that logs directly into the Lead tab in dynamics, and tries to click on the newly created lead.

I have tried multiple ways to access the lead link and have not been successful. 

<img width="858" alt="Delete lead screenshot" src="https://github.com/microsoft/playwright/assets/114633964/96167b52-d3ca-463b-b441-894c5cf3bf6d">

1. Accessing it by clicking the gridcell.  
const gridCell = await page.waitForSelector('text=Automated Test');  
await gridCell.click(); 
 
2. Accessing it by click on the label.  
await page.getByLabel('Automated Test').first().click();  
await page.getByLabel('Delete').click() 
 
3. Accessing it by getByRole.  
await page.getByRole('link', { name: 'Automated Test' }).click();  
await page.getByRole('menuitem', { name: 'Delete' }).click();  
await page.waitForTimeout(2000); 
await page.getByRole('button', { name: 'Delete' }).click(); 

### Expected behavior

I want Playwright to open up the newly created lead in Dynamics and delete it.

### Actual behavior

Test times out, and playwright cannot click on the newly created lead.

### Additional context

<img width="1490" alt="HTML" src="https://github.com/microsoft/playwright/assets/114633964/40cd2419-294a-4997-b4ee-2351934b082a">

### Environment

```shell
.
```

**Comment by pavelfeldman** [comment]
We can only work on the issues that we can reproduce, please follow the issue template to file something we can repro locally!
