### ISSUE TITLE
[Bug]: Tests fail to load in VS Code Test Explorer

### ISSUE THREAD

**Issue by NickDareOtivo** [microsoft/playwright#30956]
### Version

1.44.0

### Steps to reproduce

![Kapture 2024-05-22 at 21 51 53](https://github.com/microsoft/playwright/assets/134894598/73e72828-10e4-4e85-bcea-fc3d539f1d73)

Steps:
1. Upgrade to playwright 1.44.0
2. Refresh test explorer 
3. Tests fail to load
4. Downgrade to playwright 1.44.0
5. Tests load successfully

### Expected behavior

Tests should appear in Test Explorer pane.

### Actual behavior

Tests failed to load in test explorer pane.

### Additional context

It appears that it's failing to loan the .env file correctly, which results in an error and the tests are not loaded into the test explorer.

### Environment

```shell
System:
MacOS Sonoma version 14.0
Apple M2
```

**Comment by pavelfeldman** [comment]
Please follow the BUG template to file something we can reproduce locally!
