### ISSUE TITLE
[Bug]:  test explorer still shows tests from config after deselecting config

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/playwright#30965]
### Version

1.44

### Steps to reproduce

create a new playwright project and inside it create another one so you have a monorepo style with two configs
select both configs so you can see both tests
deselect one config

### Expected behavior

you shouldn't see the tests from config not selected

### Actual behavior

tests from both configs are visible in test explorer

### Additional context

if you press reload it does remove the tests from the explorer

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.50 GB / 64.00 GB
  Binaries:
    Node: 20.11.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 8.5.0 - /usr/local/bin/pnpm
  IDEs:
    VSCode: 1.89.1 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.44.0 => 1.44.0
```

**Comment by dgozman** [comment]
Fixed upstream in VSCode.
