### ISSUE TITLE
[Bug]: VS code Playwright Test for VSCode extension test runner ignores setup project from playwright.config.js

### ISSUE THREAD

**Issue by spooks7er** [microsoft/playwright#30967]
### Version

1.44

### Steps to reproduce

1. Use latest Playwright - 1.44
2. Use Latest Playwright Test for VSCode - 1.1.5

3. Create a setup project config in `playwright.config.js` that is a dependency of normal chromium execution project like so: 

>   projects: [
    {
      name: 'setup',
      testMatch: /..*\.setup\.ts/
    },
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
      dependencies: ['setup'],
      },
}

* Add an appropriate setup function in a `*.setup.ts` file that is expected to run before the main test.

4. In the test explorer or in the text editor gutter click the run button of the test

### Expected behavior

Expect to have the setup execute first then the test.

### Actual behavior

Actual: the test executes, and the setup is ignored

### Additional context

The last version of the extension that is currently not having this problem with latest PW (1.44) is v1.0.22, from 3 months ago.
Setup and Test are successfully executed with the npx command.
### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
    Memory: 11.28 GB / 31.71 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.89.1 - C:\Users\*\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.1.16 - C:\Windows\system32\bash.EXE
```

**Comment by pavelfeldman** [comment]
Take a look at this FAQ, it should help: https://github.com/microsoft/playwright/issues/30882

**Comment by spooks7er** [comment]
This is not related to global setup as described in the article. The problem as I observe it, is related to dependency project not being executed before the dependant project in this case like so:
![image](https://github.com/microsoft/playwright/assets/9903304/463b4db1-b2dc-42ef-a644-3a524a7aea3f)

auth test file is called test.auth.ts.

Basically the same example but removed the word setup from the equation. This configuration is and was working with the older version of the VS code extension.

**Comment by pavelfeldman** [comment]
Here is a screenshot of that doc, are you saying your `auth` is checked and is not running?

<img width="933" alt="Screenshot 2024-05-23 at 7 40 13 AM" src="https://github.com/microsoft/playwright/assets/883973/042841ad-97ad-40d5-9ce9-fa08851c7825">

**Comment by spooks7er** [comment]
I see now, I did not had this checked. Not having these checkbox options before and didn't notice them added. Always assumed it will run by default as it did.

Thank you.
