### ISSUE TITLE
[Feature]: SlowMo for everything

### ISSUE THREAD

**Issue by basickarl** [microsoft/playwright#30963]
### 🚀 Feature Request

Would like slowMo to slow down every single command or be able to accept a list of commands it shall affect (not only user actions).

### Example

Just like the currently implemented slowMo but will affect every Playwright command.

### Motivation

So the reason I would like this is that we currently have code where we have mutation observers in the code (hence multi threads and race conditions). Our code shall not in anyway interfere in a test hence we cannot manually set `page.waitForTimeout` in-between every command in a test (hence why we are using mutation observers).

The issue is, is that Playwright is so fast some of the commands in the mutation observer callback cannot finish with the DOM that triggered the mutation observer, the DOM changes and we get a non wanted outcome. We do know how long these mutation observer callback operations take and simple waits would be enough.

Unless there is a way to pause playwright with some sort of promise from the mutation observer (or playwright.eval) in the browser code, a slowMo on every command would be suffice to cover our use case.

Let me know if you have questions or need anything.

**Comment by pavelfeldman** [comment]
You should absolutely not use either slowMo or waitForTimeout for that. Everyone is using mutation observers, and it is never in the way of testing, if the test is following the best practices. Playwright will ensure elements are actionable prior to interacting with them, it'll wait for them to be. If your app is in the state where Playwright interacts with the element and element is not ready, same will happen to your users on the slow mobile connections.
