### ISSUE TITLE
[Feature]: UI mode - display text attachments as text, not links

### ISSUE THREAD

**Issue by MartinPilny** [microsoft/playwright#30976]
### 🚀 Feature Request

I propose an enhancement to the UI mode of Playwright where text attachments (such as logs, plain text files, or text-based output) are displayed directly within the UI rather than as links that need to be clicked to view the content.

### Example

When running tests in UI mode, any text attachments generated by the tests would automatically be displayed in an expandable/collapsible section within the UI. This would allow users to quickly view relevant logs or output without the need to download and open separate files. For instance, if a test generates a log file as part of its output, the content of the log file would be displayed directly below the test result, allowing for quick review and debugging.

Current state
![image](https://github.com/microsoft/playwright/assets/45488285/a0a3c7d5-c6df-4314-8881-26fd4b2b5484)

Possible solution
![image](https://github.com/microsoft/playwright/assets/45488285/3d7c3e2c-99f1-4eb6-bf2b-955db5116abc)

### Motivation

This feature would improve the usability and efficiency of the Playwright UI mode by reducing the number of steps needed to access important information. Currently, users must click on links to download text attachments, which can be cumbersome and time-consuming, especially when dealing with multiple files or large logs. By displaying text attachments directly within the UI, users can more quickly identify and diagnose issues, leading to faster development and debugging cycles. This improvement aligns with the goal of making Playwright a more user-friendly and powerful tool for end-to-end testing.

**Comment by alvaromartmart** [comment]
I'd like to work on this as a first contribution. I think I know where to start

**Comment by barbados-clemens** [comment]
This would be an awesome enhancement, could this also include the built-in generate html report as well? 
the stdout logs already show as text inline, but when I attach a text log file I have to download the zip file (same within the UI mode).
