### ISSUE TITLE
[Feature]: Requesting for a feature to add playwright test.steps related execution results and attachments to junit reporter & Xray-App/playwright-junit-reporter

### ISSUE THREAD

**Issue by LahiruMadhawa2020** [microsoft/playwright#30973]
### 🚀 Feature Request

Requesting for a feature to add playwright test.steps related execution results and attachments to junit reporter & Xray-App/playwright-junit-reporter (https://github.com/Xray-App/playwright-junit-reporter)

### Example

This feature will be able to update the test steps wise results where the current implementation only provides support to import overall test exeution results & evidences globally.

### Motivation

Since other tools doesn't have test.step feature to have a 1:1 mapping with the test steps from the test management tool, if this feature is available playwright will be the only tool with the feature & the value of having test.steps will return a considerable ROI.

**Comment by pavelfeldman** [comment]
junit does not have the means of representing the steps and it already links the attachments as allowed by the spec. [https://github.com/Xray-App](https://github.com/Xray-App/playwright-junit-reporter) is outside of the scope of Playwright, it is a third party module, please file it against their repository.

**Comment by LahiruMadhawa2020** [comment]
That makes sense. Thank you Pavel for the quick response in no time. Will raise a ticket with the [XRAY](https://github.com/Xray-App/playwright-junit-reporter) team.
