### ISSUE TITLE
[Feature]: retry-mechanism for API request incase failure due to ECONNRESET 

### ISSUE THREAD

**Issue by Pavan-niva** [microsoft/playwright#30978]
### 🚀 Feature Request

ECONNRESET might happen due to connectivity issues. As multiple executions are happening through API calls, sometimes randomly playwright through ECONNRESET error.  I used my logic of retrying using try-catch apiContext.post/get, the error object is undefined on ECONNRESET occurs. It would be nice playwright threw the error.statuscode as  ECONNRESET / provided an option to retry the API

    let retryCount = 0;
    let maxRetries = 3;
    while (retryCount < maxRetries) {
      try {
        const Response = await apiContext.get(URL, {
          headers: {
            'Connection': 'keep-alive',
            'Authorization': SessionToken,
            'Content-Type': 'application/json',
          },
          timeout: 0,
          failOnStatusCode: true
        });
        await Response.json();
      }
     } catch (error) {
        console.log(error); 
        if (error.code.toString().includes("ECONNRESET")) {
          retryCount++;
          console.log(`Connection reset. Retrying... (${retryCount}/${maxRetries})`);
          continue;
        } else {
          throw error;
        }
      }

### Motivation

This feature will help API Automation better,reliable & saves the time of retrigger of entire automation suite

**Comment by StanislavGrishaev** [comment]
have you tried the retry logic from the function [expect.poll](https://playwright.dev/docs/test-assertions#expectpoll) ?

**Comment by Pavan-niva** [comment]
Yes, I did it. No luck.  
Axios provides this type of capability in the market.
https://www.npmjs.com/package/axios-retry

**Comment by pavelfeldman** [comment]
Could you share more about your use case? Are you testing an API that is allowed to cause ECONNRESET? I.e. it is allowed for the server to abruptly close the connection and it should lead to a passing test?

**Comment by Pavan-niva** [comment]
To Run UI tests, as a prerequisite, I need to setup the data via API, When the tests are running in Container, ECONNRESET starts happening, the server is not closing any connection.

**Comment by pavelfeldman** [comment]
ECONNRESET (Connection reset by peer): A connection was forcibly closed by a peer. This normally results from a loss of the connection on the remote socket due to a timeout or reboot.

**Comment by Pavan-niva** [comment]
different combinations like timeout: 900000, timeout:0. but still same error  apiRequestContext.post: read ECONNRESET

**Comment by Pavan-niva** [comment]
@pavelfeldman Thank you for accepting this enhancement.
