### ISSUE TITLE
[Feature]: Hide `route.*` calls from test traces / reports

### ISSUE THREAD

**Issue by chrissantamaria** [microsoft/playwright#30970]
### 🚀 Feature Request

In tests, it can often be useful to use `page.route` to globally intercept page requests (say, blocking requests matching a certain pattern) using `route.continue()` or `route.abort()`:
```ts
await page.route('**/*', (route) => {
  if (someCondition) {
    return route.abort();
  }
  return route.continue();
});
```

However, this results in many steps being included in test traces / reports which can make it tricky to spot other, more explicit steps from test logic.

Example trace, where the left sidebar is filled with lots of `route.continue` calls:

<img width="959" alt="Screenshot 2024-05-22 at 7 04 54 PM" src="https://github.com/microsoft/playwright/assets/24602724/5846052f-3477-4501-a082-6c7cfbf68334">

In reports, this generally isn't as significant given that adjacent calls will be grouped together:

<img width="916" alt="Screenshot 2024-05-22 at 7 09 55 PM" src="https://github.com/microsoft/playwright/assets/24602724/091d089d-9afc-4e13-a2da-cd2ec572bd7f">

However, if a test flips between allowing and rejecting requests it can get a bit noisy:

<img width="394" alt="Screenshot 2024-05-22 at 7 03 36 PM" src="https://github.com/microsoft/playwright/assets/24602724/15a732b2-e209-4a11-b965-a2f5b0ecc265">

Ideally, it would be nice if these could be hidden. That could take the form of:
- an opt-in toggle on the trace / report UI
- a test configuration option
- an option on `route` methods themselves, indicating that they should be hidden

This is similar to #28482, though I see that issue was closed since there was no reproduction provided. I think test reports could be improved, but I'm particularly interested in improvements to the trace viewer where adjacent `route.*` calls are not grouped together.

Happy to provide a formal reproduction, but I was able to create the first two screenshots with this simple test:
```ts
import { test } from '@playwright/test';

test('example', async ({ page }) => {
  await page.route('**/*', (route) => {
    return route.continue();
  });

  await page.goto('https://playwright.dev/');
});
```

### Motivation

In longer tests, there can often be hundreds of network requests which fill the UI (particularly for traces) and make it tricky to find steps related to actual test assertions. If Playwright supported hiding these (even if temporarily), it could make test reports much simpler to parse.

**Comment by chrissantamaria** [comment]
#31726 looks really nice! Will try it out once the next alpha is published.

I wonder if there's a way for route actions to be hidden by default when opening traces. For my use case, there are many engineers interacting with traces that might not realize the setting exists - it would be nice to give them a sensible default for our project where route actions aren't relevant. Similarly, even for those who do know about the setting it's a bit tedious to have to navigate through and update on each trace load.

Might it make sense to have a default setting option defined in the Playwright config? Generated traces could honor that setting and pass it as the default value to `useSetting`.

Completely understand if there's hesitation in adding more config fields - just bringing up as food for thought. If we go that route, I'm also happy to help contribute.

**Comment by dgozman** [comment]
@chrissantamaria The setting should persist between trace viewer launches, so you will need to only toggle it once.

**Comment by chrissantamaria** [comment]
Oh, nice, missed that bit in `useSetting`. I suppose that address the second concern of needing toggle on each load, but folks will still need to know the setting exists. Not a _huge_ deal though, and maybe not worth the overhead of extending the Playwright config schema.

Thanks for working on this!

**Comment by dgozman** [comment]
Trace Viewer / UI mode change has landed, moving this issue to the html report.

**Comment by kvnschlndt** [comment]
@pavelfeldman when is this feature also expected to be available for html report?

**Comment by kvnschlndt** [comment]
> @pavelfeldman when is this feature also expected to be available for html report? We have a highly noisy and hardly readable test report because of a lot of modifcation to requests/responses.

@pavelfeldman ?

**Comment by samSam-0** [comment]
is this gonna be available for html report and allure report? @dgozman @pavelfeldman @mxschmitt

**Comment by dgozman** [comment]
Should be addressed by #32723.

**Comment by kvnschlndt** [comment]
@dgozman @pavelfeldman 
Still it can noisy the test report.

`const response = route.fetch()`

`response.json()` -> is creating a step in test report

**Comment by skoch13** [comment]
@dgozman sorry for the ping, but should I create a separate issue for html report pollution?
