### ISSUE TITLE
[Bug]: there is no way to use a test filter matching exact test

### ISSUE THREAD

**Issue by epszaw** [microsoft/playwright#30984]
### Version

1.44.1

### Steps to reproduce

1. Clone [repo](https://github.com/epszaw/playwright-test-filter-bug)
2. Install dependencies
3. Run `npm t` script to see, that all the tests running, not only `o.spec.js`
4. Run `npm run test:foo` to run only `foo.spec.js` test

### Expected behavior

I want to run only `o.spec.js` using `o.spec.js:3` test filter, not all the matched files I have in the project

### Actual behavior

`playwright test o.spec.js:3` runs all tests matched by `o.spec.js:3` pattern and there is no way to run exact test file

### Additional context

<img width="1728" alt="image" src="https://github.com/microsoft/playwright/assets/13414205/a697187c-ab50-4eaa-8bc8-78f730ce02ec">

### Environment

```shell
System:
  OS: macOS 14.1.1 23B81 arm64
  CPU: Apple M1 Pro
Binaries:
  Node: v20.9.0 – ~/.asdf/shims/node
  npm: 10.4.0 – ~/.asdf/shims/npm
npmPackages:
  @playwright/test: 1.44.1
```

**Comment by pavelfeldman** [comment]
How about the one below?
```
playwright test /o.spec.js:3
```

**Comment by epszaw** [comment]
Yeah, it works. Thank you!
