### ISSUE TITLE
[Bug]: No Tests found error when trying to debug the tests

### ISSUE THREAD

**Issue by sat1591** [microsoft/playwright#30985]
### Version

1.1.5

### Steps to reproduce

1. Create a parametrized test like below example

```
const people = ['Alice', 'Bob'];
for (const name of people) {
  test(`testing with ${name}`, async () => {
    // ...
  });
}
```
2. Go to VS code extension and trigger parameterized test in debug mode

### Expected behavior

Expected to see browser should instantiate the tests based on test data we provided.

### Actual behavior

1. When I trigger the run test in debug mode from VS extension Then I am getting below error.

> Error: No tests found.
Make sure that arguments are regular expressions matching test files.
You may need to escape symbols like "$" or "*" and quote the arguments.
2. Test results output also shows

>  *  The test run did not record any output. 

**Note**: If I run the tests in normal mode or any non-parameterized tests is working as expected. The problem is only running parameterized tests in debug mode.

![image](https://github.com/microsoft/playwright/assets/64651715/f7438e07-d487-4853-96f7-7d45b7bd57db)

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 AMD EPYC 7763 64-Core Processor
    Memory: 3.90 GB / 15.95 GB
  Binaries:
    Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.88.1 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.43.1 => 1.43.1
```

**Comment by pavelfeldman** [comment]
It works for me just fine. Please use a BUG template to provide a use case we can repro.
