### ISSUE TITLE
[Feature]: Can it support perfect timings salary?

### ISSUE THREAD

**Issue by wanliofficial** [microsoft/playwright#30997]
### 🚀 Feature Request

[Chrome DevTools HAR Entry](https://github.com/ChromeDevTools/devtools-frontend/blob/main/front_end/models/har/Log.ts)

Can **createHarEntry** in the **playwright-core\lib\server\har\harTracer.js** file be reimplemented using **Entry** in **front_end/models/har/Log.ts**?

#### Current

```json
{
  "timings": {
    "dns": -1,
    "connect": -1,
    "ssl": -1,
    "send": 0,
    "wait": 84.307,
    "receive": 3.733
  }
}
```

The current problem is that there is no blocked field and send is hard-coded to 0.

#### Expect

```json
{
  "timings": {
    "blocked": -1,
    "dns": -1,
    "ssl": -1,
    "connect": -1,
    "send": 0,
    "wait": 0,
    "receive": 0,
    "_blocked_queueing": -1,
    "_blocked_proxy": -1
  }
}
```

### Motivation

I want more complete HAR information to facilitate the analysis of HAR timing relationships.

Thanks!

**Comment by pavelfeldman** [comment]
> Can createHarEntry in the playwright-core\lib\server\har\harTracer.js file be reimplemented using Entry in front_end/models/har/Log.ts?

No, it can't. We are the same people that implemented it in Chrome 14 years ago btw.

Here is the actual spec: http://www.softwareishard.com/blog/har-12-spec/

Blocked is optional, so we don't provide it. Send is 0 because it is loosely defined as "Time required to send HTTP request to the server."

What's your use case?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
