### ISSUE TITLE
[Bug]: Trace viewer shows wrong request body

### ISSUE THREAD

**Issue by zilia-gmethot** [microsoft/playwright#30992]
### Version

1.44.1

### Steps to reproduce

1. Clone my repo at https://github.com/zilia-gmethot/reproduce-playwright-traceviewer-bug
2. Install dependencies with `npm install`
3. Launch tests with `npx playwright test`. The only test should fail.
4. Open the test's trace with `npx playwright show-trace test-results/example-has-visible-header-chromium/trace.zip`
5. In trace viewer, open the `Network` tab
6. Click on the first network call, with the name `log`. You should see that the request body is `{"message":"Starting test with title \"has visible header\""}`
7. Click on the second network call, with the name `localhost:8080`. You should see that the request body is also `{"message":"Starting test with title \"has visible header\""}`, even though it should have contained no body.

### Expected behavior

When viewing network calls in trace viewer, I would expect each network call inspection to contain the proper request body.

### Actual behavior

When viewing network calls in trace viewer, it seems that the body of the request made using a new context, inside a custom test fixture, is considered as the request body of the request made to load the page during the test.

### Additional context

In my experience, it doesn't matter if the network call goes to a URL with a different origin (in my demo, all requests are made to `http://localhost:8080`).

It also happens when we run multiple tests.

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 7730U with Radeon Graphics
    Memory: 9.02 GB / 15.28 GB
    Container: Yes
  Binaries:
    Node: 20.12.0 - ~/.nvm/versions/node/v20.12.0/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.0/bin/npm
  IDEs:
    VSCode: 1.89.1 - /home/gabriel/.vscode-server/bin/dc96b837cf6bb4af9cd736aa3af08cf8279f7685/bin/remote-cli/code
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.44.1 => 1.44.1
```

**Comment by pavelfeldman** [comment]
These are the ones I see:
![image](https://github.com/microsoft/playwright/assets/883973/978790ca-044e-4a65-b333-0392043a4bb7)

![image](https://github.com/microsoft/playwright/assets/883973/bd61e86a-dacf-45dd-886d-cb2e0df24291)

Those look good to me. Could you share a trace file where you are observing this issue?

**Comment by zilia-gmethot** [comment]
@pavelfeldman Thank you so much for the quick reply! I apologize if I wasn't clear, but you need to look at the Request body in the **Request**, as opposed to the **Body** tab.

Here is a video showing the issue, along with the trace you requested.

https://www.youtube.com/watch?v=ppbH_06IHI8

[trace.zip](https://github.com/microsoft/playwright/files/15436488/trace.zip)

**Comment by zilia-gmethot** [comment]
@pavelfeldman Wow that was quick, thank you very much!
