### ISSUE TITLE
[Bug]: Project dependencies not run unless dependency project is selected when running tests in VS Code

### ISSUE THREAD

**Issue by j6r** [microsoft/playwright#30996]
### Version

1.44.1

### Steps to reproduce

1. Clone the example repository: https://github.com/j6r/PlaywrightExtensionBugRepro)
2. `yarn install` and `yarn playwright install` as usual
4. Install the Playwright extension version 1.0.22
5. Go to the VS Code test tab. 
6. From the dropdown menu, select the chromium project and run the test
    Expected: the chromium and setup projects are run
    Actual: as expected
7. Update the extension (currently 1.1.6) and restart
8. In the list of projects select Chromium
9. Run the test
    Expected: the chromium and setup projects are run **because the chromium project depends on setup**
    Actual: only the chromium project runs

### Expected behavior

The setup project is always run before the chromium project **because the chromium project has a dependency on setup defined in `playwright.config.ts`** even if setup is not selected in the extension's project list

### Actual behavior

In 1.0.22 both are run as expected
In 1.1.6 only chromium is run

### Additional context

![image](https://github.com/microsoft/playwright/assets/32883148/2b9ff1f8-372b-4827-8add-54a9de490cf8)

![image](https://github.com/microsoft/playwright/assets/32883148/8f64ceb0-3c4f-4a27-8c73-4dcd58df809c)

<img width="331" alt="image" src="https://github.com/microsoft/playwright/assets/32883148/31dbf892-5e6d-4c0b-87a7-2f2813eb9455">

### Environment

```shell
System:
    OS: macOS 14.4.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 7.76 GB / 32.00 GB
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.13.1/bin/yarn
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.44.1 => 1.44.1
```

**Comment by pavelfeldman** [comment]
That is the new behavior, if you want it to behave as in 1.0.22, keep it checked. See more at https://github.com/microsoft/playwright/issues/30882
