### ISSUE TITLE
[Feature]: Support optGroup parameter in Locator.selectOption method

### ISSUE THREAD

**Issue by viraxslot** [microsoft/playwright#31006]
### 🚀 Feature Request

We have `select` with `optGroup`-s like in this example https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup

I suggest to add option `optionGroup` to this method
https://playwright.dev/docs/api/class-locator#locator-select-option

to allow to select option from the specific group.

### Example

```typescript
{
  // current logic allows to select an option by text
  element.selectOption('blue');

  // suggested logic allows to select an option by text from a group
  element.selectOption('blue', { optionGroup: 'favoriteColors' });
}
```

### Motivation

Currently there is no possibility to choose the correct option from the group and it adds difficulties during the test framework development. Looks like it should be supported in Playwright API.

**Comment by pavelfeldman** [comment]
I don't think we need an option, but we should make sure you can select a nested item by the title or value.
