### ISSUE TITLE
[Bug]: Submit button is not getting enabled after filling a login form

### ISSUE THREAD

**Issue by Seenivasababu** [microsoft/playwright#31003]
### Version

1.41.1

### Steps to reproduce

I am testing a login functionality where user need to fill two fields and then the login button enables for further process.
I am using the fill() command to perform the operation. Text has been entered by playwright correctly but it is not enabling the OK button.
![image](https://github.com/microsoft/playwright/assets/120184836/2c07b745-3cc8-4169-9650-74d00ae765dc)

When I debug this manually using playwright inspector, still the OK button is not enabled unless I manually type something.

### Expected behavior

Disable button should automatically getting enable after filling all the mandatory details.

### Actual behavior

I am testing a login functionality where use need to fill two fields and then the login button enables for further process.
I am using the fill() command to perform the operation. Text has been entered by playwright correctly but it is not enabling the submit button.

### Environment

```shell
locator resolved to <button ng-click="ad.ok()" disabled="disabled" class="bt…>OK</button>
attempting click action
waiting for element to be visible, enabled and stable
```

**Comment by pavelfeldman** [comment]
Sounds like your page has a bug, most likely https://playwright.dev/docs/navigations#hydration
