### ISSUE TITLE
[Question] Add 'retain-on-failure' option to .net 

### ISSUE THREAD

**Issue by AQuarton** [microsoft/playwright#31002]
### Please do not submit this issue.

- [x] I understand

**Comment by AQuarton** [comment]
node.js according to the documenation [https://playwright.dev/docs/test-use-options] has a feature  retain-on-failure which would be very useful but it does not appear to have been implemented for .net or other languages. Do we have any plans to implement this for .net

**Comment by mxschmitt** [comment]
Does something like this work for you? https://playwright.dev/dotnet/docs/trace-viewer#run-trace-only-on-failure

**Comment by AQuarton** [comment]
Hi, 

Thanks as a workaround I guess but not as good as having the specific option retain-on-failure which is available in node.js
Just as an aside is there a reason that a lot of functionality / documentation gets added to node.js but not the other languages ?

**Comment by mxschmitt** [comment]
Tracing as of today is a manual step. For having it automated, I'll fold it into https://github.com/microsoft/playwright-dotnet/issues/2214.
