### ISSUE TITLE
[Bug]: OffscreenCanvas in Webworker missing for Webkit in GithubActions

### ISSUE THREAD

**Issue by Theiaz** [microsoft/playwright#31004]
### Version

1.44.0

### Steps to reproduce

1. Clone my repo at: https://github.com/Theiaz/playwright-bug-webkit (or at least have a look at the [pipeline](https://github.com/Theiaz/playwright-bug-webkit/actions) and download the artifact)
2. Run `npm i`
3. Run tests locally `npm run test` --> Success
4. Deploy project with github actions  --> test failure
5. Open "Run actions/upload-artifact@v4" job and find the link to download the artifact (playwright report)
6. Unzip the report and open it with `npx playwright show-report ~/Downloads/playwright-report`
7. Open the trace file for webkit and have a look at the console log

### Expected behavior

All three major browser testcases should pass successfully

### Actual behavior

Webkit testcase fails with Console Error `Unhandled Promise Rejection: ReferenceError: Can't find variable: OffscreenCanvas`

![Screenshot 2024-05-24 at 12 05 57](https://github.com/microsoft/playwright/assets/9378662/795009d3-4e1c-4cb9-a519-5cbcea2e7734)

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M2 Pro
    Memory: 1.92 GB / 32.00 GB
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 9.0.6 - /opt/homebrew/bin/pnpm
  IDEs:
    VSCode: 1.89.1 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.44.0 => 1.44.0
```

**Comment by bc-lee** [comment]
OffscreenCanvas support within Web Workers is currently disabled in WebKit for platforms other than Apple's.

While WebKit developers enabled OffscreenCanvas in Web Workers through the [b32d7b9f1487e0c5bcd836a8dda7cc5fc44485a6](https://github.com/WebKit/WebKit/commit/b32d7b9f1487e0c5bcd836a8dda7cc5fc44485a6) commit, [Source/cmake/OptionsGTK.cmake](https://github.com/WebKit/WebKit/blob/9c1f32d066a46ee839adef4a79364938a81036ac/Source/cmake/OptionsGTK.cmake#L133) explicitly disables it for the GTK+(linux) platform. The same is true for the Windows port.

To address this inconsistency, it's recommended to submit a bug report to [WebKit](https://bugs.webkit.org) requesting that OffscreenCanvas functionality be enabled in Web Workers for platforms beyond Apple's.

**Comment by yury-s** [comment]
Should be fixed with recent WebKit roll https://github.com/microsoft/playwright/pull/31103
