### ISSUE TITLE
[Bug]: Linux WebKit missing support for WebRTC

### ISSUE THREAD

**Issue by bc-lee** [microsoft/playwright#31016]
### Version

1.44.1

### Steps to reproduce

1. Clone https://github.com/web-platform-tests/wpt.
2. Setup wpt (see instructions at [here](https://web-platform-tests.org/running-tests/from-local-system.html)).
3. Run wpt with the following command:

`$ ./wpt run --log-wptreport=report-webkit.json  --binary $HOME/.cache/ms-playwright/webkit-2003/minibrowser-gtk/bin/MiniBrowser webkitgtk_minibrowser webrtc/`

### Expected behavior

Since WebKit supports WebRTC, and based on the public test results at [https://wpt.fyi/results/webrtc](https://wpt.fyi/results/webrtc), we expect many tests to pass.

### Actual behavior

Almost every test fails with the following error:

`ReferenceError: Can't find variable: RTCPeerConnection`

### Additional context

You can run other browsers to test wpt coverage. For example, a similar command for Chromium with good coverage is:

`$ ./wpt run --log-wptreport=report-chromium.json  --binary $HOME/.cache/ms-playwright/chromium-1117/chrome-linux/chrome chromium webrtc/`

### Environment

```shell
System:
    OS: Linux 6.8 Fedora Linux 40 (Workstation Edition)
    CPU: (20) x64
    Memory: 51.15 GB / 62.58 GB
    Container: Yes
  Binaries:
    Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
  IDEs:
    VSCode: 1.89.1 - /usr/bin/code
  Languages:
    Bash: 5.2.26 - /usr/bin/bash
```

**Comment by yury-s** [comment]
WebKit support for different web features varies between platforms. Core features are usually equally supported across all platforms, but they are not always identical on different platforms, e.g. there each platform uses its own network stack.  The more niche a feature is, the higher chance it is supported only partially or not supported at all on some OSes (e.g. Web Assembly on Windows until recently). WebRTC, in particular, is heavily dependent on the underlying platform and some tests (including upstream) that pass on macOS may be skipped on Linux. 

Merging this report into https://github.com/microsoft/playwright/issues/2973 which tracks WebRTC testing in WebKit.
