### ISSUE TITLE
[Bug]: `create-playwright` doesn't show a version number

### ISSUE THREAD

**Issue by karlhorky** [microsoft/playwright#31020]
### Version

1.44.1

### Steps to reproduce

1. Run `pnpm create playwright`
2. Observe that the version number of `create-playwright` is not in the output (although the version number of the installed version of `@playwright/test` is shown)

### Expected behavior

`create-playwright` includes a header with its version number:

```diff
➜  a pnpm create playwright

.../18fb5cc8e41-395e                     |   +1 +
.../18fb5cc8e41-395e                     | Progress: resolved 1, reused 1, downloaded 0, added 1, done

+create-playwright v1.17.132

Getting started with writing end-to-end tests with Playwright:
Initializing project in '.'
✔ Do you want to use TypeScript or JavaScript? · TypeScript
✔ Where to put your end-to-end tests? · tests
✔ Add a GitHub Actions workflow? (y/N) · false
✔ Install Playwright browsers (can be done manually via 'pnpm exec playwright install')? (Y/n) · true
Installing Playwright Test (pnpm add --save-dev @playwright/test)…
Packages: +4
 ++++
Progress: resolved 4, reused 4, downloaded 0, added 4, done

devDependencies:
 + @playwright/test 1.44.1

Done in 1.2s
Installing Types (pnpm add --save-dev @types/node)…
Packages: +2
 ++
Progress: resolved 6, reused 6, downloaded 0, added 2, done

devDependencies:
 + @types/node 20.12.12

Done in 497ms
Writing playwright.config.ts.
Writing tests/example.spec.ts.
Writing tests-examples/demo-todo-app.spec.ts.
Writing package.json.
Downloading browsers (pnpm exec playwright install)…
Removing unused browser at /Users/k/Library/Caches/ms-playwright/chromium-1105
Removing unused browser at /Users/k/Library/Caches/ms-playwright/firefox-1440
Removing unused browser at /Users/k/Library/Caches/ms-playwright/webkit-1983
Downloading Chromium 125.0.6422.26 (playwright build v1117) from https://playwright.azureedge.net/builds/chromium/1117/chromium-mac-arm64.zip
134.6 MiB [====================] 100% 0.0s
Chromium 125.0.6422.26 (playwright build v1117) downloaded to /Users/k/Library/Caches/ms-playwright/chromium-1117
Downloading Firefox 125.0.1 (playwright build v1449) from https://playwright.azureedge.net/builds/firefox/1449/firefox-mac-13-arm64.zip
77.8 MiB [====================] 100% 0.0s
Firefox 125.0.1 (playwright build v1449) downloaded to /Users/k/Library/Caches/ms-playwright/firefox-1449
Downloading Webkit 17.4 (playwright build v2003) from https://playwright.azureedge.net/builds/webkit/2003/webkit-mac-14-arm64.zip
66.3 MiB [====================] 100% 0.0s
Webkit 17.4 (playwright build v2003) downloaded to /Users/k/Library/Caches/ms-playwright/webkit-2003
✔ Success! Created a Playwright Test project at /Users/k/p/a

Inside that directory, you can run several commands:

  pnpm exec playwright test
    Runs the end-to-end tests.

  pnpm exec playwright test --ui
    Starts the interactive UI mode.

  pnpm exec playwright test --project=chromium
    Runs the tests only on Desktop Chrome.

  pnpm exec playwright test example
    Runs the tests in a specific file.

  pnpm exec playwright test --debug
    Runs the tests in debug mode.

  pnpm exec playwright codegen
    Auto generate tests with Codegen.

We suggest that you begin by typing:

    pnpm exec playwright test

And check out the following files:
  - ./tests/example.spec.ts - Example end-to-end test
  - ./tests-examples/demo-todo-app.spec.ts - Demo Todo App end-to-end tests
  - ./playwright.config.ts - Playwright Test configuration

Visit https://playwright.dev/docs/intro for more information. ✨

Happy hacking! 🎭
```

### Actual behavior

`create-playwright` does not show a header with the package name or the version (it does show the version of the installed version of `@playwright/test`, but this version may not be the same as the version of `create-playwright`)

```
➜  a pnpm create playwright

.../18fb5cc8e41-395e                     |   +1 +
.../18fb5cc8e41-395e                     | Progress: resolved 1, reused 1, downloaded 0, added 1, done

create-playwright v1.44.1

Getting started with writing end-to-end tests with Playwright:
Initializing project in '.'
✔ Do you want to use TypeScript or JavaScript? · TypeScript
✔ Where to put your end-to-end tests? · tests
✔ Add a GitHub Actions workflow? (y/N) · false
✔ Install Playwright browsers (can be done manually via 'pnpm exec playwright install')? (Y/n) · true
Installing Playwright Test (pnpm add --save-dev @playwright/test)…
Packages: +4
++++
Progress: resolved 4, reused 4, downloaded 0, added 4, done

devDependencies:
+ @playwright/test 1.44.1

Done in 1.2s
Installing Types (pnpm add --save-dev @types/node)…
Packages: +2
++
Progress: resolved 6, reused 6, downloaded 0, added 2, done

devDependencies:
+ @types/node 20.12.12

Done in 497ms
Writing playwright.config.ts.
Writing tests/example.spec.ts.
Writing tests-examples/demo-todo-app.spec.ts.
Writing package.json.
Downloading browsers (pnpm exec playwright install)…
Removing unused browser at /Users/k/Library/Caches/ms-playwright/chromium-1105
Removing unused browser at /Users/k/Library/Caches/ms-playwright/firefox-1440
Removing unused browser at /Users/k/Library/Caches/ms-playwright/webkit-1983
Downloading Chromium 125.0.6422.26 (playwright build v1117) from https://playwright.azureedge.net/builds/chromium/1117/chromium-mac-arm64.zip
134.6 MiB [====================] 100% 0.0s
Chromium 125.0.6422.26 (playwright build v1117) downloaded to /Users/k/Library/Caches/ms-playwright/chromium-1117
Downloading Firefox 125.0.1 (playwright build v1449) from https://playwright.azureedge.net/builds/firefox/1449/firefox-mac-13-arm64.zip
77.8 MiB [====================] 100% 0.0s
Firefox 125.0.1 (playwright build v1449) downloaded to /Users/k/Library/Caches/ms-playwright/firefox-1449
Downloading Webkit 17.4 (playwright build v2003) from https://playwright.azureedge.net/builds/webkit/2003/webkit-mac-14-arm64.zip
66.3 MiB [====================] 100% 0.0s
Webkit 17.4 (playwright build v2003) downloaded to /Users/k/Library/Caches/ms-playwright/webkit-2003
✔ Success! Created a Playwright Test project at /Users/k/p/a

Inside that directory, you can run several commands:

  pnpm exec playwright test
    Runs the end-to-end tests.

  pnpm exec playwright test --ui
    Starts the interactive UI mode.

  pnpm exec playwright test --project=chromium
    Runs the tests only on Desktop Chrome.

  pnpm exec playwright test example
    Runs the tests in a specific file.

  pnpm exec playwright test --debug
    Runs the tests in debug mode.

  pnpm exec playwright codegen
    Auto generate tests with Codegen.

We suggest that you begin by typing:

    pnpm exec playwright test

And check out the following files:
  - ./tests/example.spec.ts - Example end-to-end test
  - ./tests-examples/demo-todo-app.spec.ts - Demo Todo App end-to-end tests
  - ./playwright.config.ts - Playwright Test configuration

Visit https://playwright.dev/docs/intro for more information. ✨

Happy hacking! 🎭
```

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 83.81 MB / 16.00 GB
  Binaries:
    Node: 20.13.1 - /opt/homebrew/bin/node
    npm: 10.5.2 - /opt/homebrew/bin/npm
    pnpm: 9.1.2 - /opt/homebrew/bin/pnpm
    bun: 1.1.4 - /opt/homebrew/bin/bun
  IDEs:
    VSCode: 1.89.1 - /opt/homebrew/bin/code
  Languages:
    Bash: 5.2.0 - /opt/homebrew/bin/bash
  npmPackages:
    @playwright/test: ^1.44.1 => 1.44.1
```

**Comment by karlhorky** [comment]
> its not relevant to the user which create-playwright version they are using

To me as a user, I would argue it's very important to know what version of `create-playwright` I'm using, especially if I'm waiting for a change to be published, and want to know if my package manager has the updated version (finding the version of a `create-x` tool is not straightforward for users, so printing it is very helpful).

**Comment by mxschmitt** [comment]
We expect users to **always** run the latest version of create-playwright, hence we have the `@latest` everywhere. Yarn does it do automatically. For pnpm, it looks like they cache very aggressively, even when adding `@latest`. So if there is a flag we can add on pnpm side, happy to add it. (we are following what create-react-app does). Other than that, we try to avoid adding additional output to create-playwright, since it already prints a lot of information to the user. Thanks for your understanding.

**Comment by karlhorky** [comment]
> we try to avoid adding additional output to create-playwright

Understood, I would also tend towards being very careful with adding lines here. I do think that 1 extra line with this valuable information is worth it, but if `create-playwright` should always be latest versions and old versions are deprecated (as I think I'm understanding that you are suggesting), then it should be less of an issue.

> We expect users to **always** run the latest version of create-playwright

I'm understanding that `create-playwright` should be always the latest version and that old versions are deprecated.

This seems to fit with the philosophy from the browser ecosystem of "evergreen" - where browsers include mechanisms to automate being on the latest version.

In this case, I could see an "evergreen" alternative to printing the `create-playwright` version to be:

1. Automating publishing of [the `main` branch](https://github.com/microsoft/create-playwright/tree/main) to avoid [feature which are merged but not yet published](https://github.com/microsoft/create-playwright/pull/116#issuecomment-2132296140)
2. [Some flag (if it exists) to enable pnpm to always get the latest version](https://github.com/microsoft/playwright/issues/31020#issuecomment-2144971681) (I thought that `@latest` already achieved that, but maybe there is some caching I'm not aware of)
   - Alternative: Add a check in `create-playwright` to check for the latest version and refuse to run

@mxschmitt if you agree with 1 above, I can create a new issue for this.

**Comment by mxschmitt** [comment]
> Automating publishing of [the create-playwright main branch](https://github.com/microsoft/create-playwright/tree/main) to avoid https://github.com/microsoft/create-playwright/pull/116#issuecomment-2132296140

We prefer to control the release process so automating the publishing is not going to happen.

> Some flag (if it exists) to enable pnpm to always get the latest version (I thought that @latest already achieved that, but maybe there is some caching I'm not aware of)

That would be great to fix! Let's file an issue in the pnpm repository?

> Alternative: Add a check in create-playwright to check for the latest version and refuse to run with older versions

We prefer to fix pnpm since NPM and Yarn is installing the latest version (without caching).

There seems to be no action item for Playwright, so closing this.
