### ISSUE TITLE
[Docs]: PW API documentation - Add more details and example section for multipart/formData request

### ISSUE THREAD

**Issue by rjayaraman1** [microsoft/playwright#31025]
### Page(s)

This is based on my discord community question/discussion on PW - API testing with formData issue
[](https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-post)

### Description

**Details**

1. Referred to this link for multipart example: https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-post
2. Used PW version - "@playwright/test": "^1.44.1" for this test
3. The examples provided in the above PW documentation is for form and multipart not for **formData**
4. **Enhancement request for documentation 1**: Please add examples for formData  and multipart
5. Also noticed PW is using its own implementation of **formData**
6**. Enhancement request for documentation 2:** Please mention PW uses its own `formData `implementation and we should not install and import formData 
7. Here is the example code snippet. Please feel free to update accordingly 

As you can see from my community discussion with **"refactoreric"**, below code snippet(example) is working fine after commenting out "import FormData from 'form-data'"; 

```
import { test } from '@playwright/test';
import fs from 'fs';
//import FormData from 'form-data'; This conflicts with PW formdata per PW discord community conversation.  Need to use PW defuult formData
const ServiceEndpoint: string = 'https://a.com/b/c';
const apikey: string = 'sfsdsdfs';
const requestId: string = 'aaaaa';
const token: string = '43534534534543'; 

test('Hello world', async ({request}) => {
    const payloadData = fs.readFileSync('../testassets/Payload.json');
    const payLoadFile = new File([payloadData], 'Payload.json', { type: 'text/javascript'});
    const formData = new FormData();
    formData.append('payload', payLoadFile);
    
    const response = await request.post(`${ServiceEndpoint}/senditemyy`, {
          headers: {
             "x-api-key": apikey,
             "x-request-id": requestId,
             "Authorization": "Bearer " + token,
          },
          multipart: formData
       });
});

```

**Comment by mxschmitt** [comment]
> Please add examples for formData and multipart

We added an example at the end for it, is this something you were looking for?

<img width="976" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/e4378b7d-1ea0-426f-b405-5e4d2d30c23d">

>  Please mention PW uses its own formData implementation and we should not install and import formData

Playwright almost never relies on third-party libraries - I think starting to mention that feature X does not require library Y isn't a principal we should start to follow.

**Comment by dgozman** [comment]
Closing as per above. If you still think there is missing documentation, please file a new issue and explain in more details what exactly you would like to see.
