### ISSUE TITLE
[Bug]: `create-playwright` adds duplicate .gitignore entries

### ISSUE THREAD

**Issue by karlhorky** [microsoft/playwright#31021]
### Version

1.44.1

### Steps to reproduce

1. Ensure that your `.gitignore` contains the following
   ```txt
   /test-results/
   /playwright-report/
   /blob-report/
   /playwright/.cache/
   ```
2. Run `pnpm create playwright`
3. Observe duplicate entries for `/test-results/`, `/playwright-report/`, `/blob-report/`, `/playwright/.cache/`

### Expected behavior

`create-playwright` doesn't add duplicate entries to `.gitignore`

### Actual behavior

`create-playwright` adds duplicate entries to `.gitignore`

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 83.81 MB / 16.00 GB
  Binaries:
    Node: 20.13.1 - /opt/homebrew/bin/node
    npm: 10.5.2 - /opt/homebrew/bin/npm
    pnpm: 9.1.2 - /opt/homebrew/bin/pnpm
    bun: 1.1.4 - /opt/homebrew/bin/bun
  IDEs:
    VSCode: 1.89.1 - /opt/homebrew/bin/code
  Languages:
    Bash: 5.2.0 - /opt/homebrew/bin/bash
  npmPackages:
    @playwright/test: ^1.44.1 => 1.44.1
```

**Comment by DerTimonius** [comment]
Opened a PR that fixes this issue: https://github.com/microsoft/create-playwright/pull/122

**Comment by gskierk** [comment]
@mxschmitt Can we close this ticket as the pull request is already merged?

**Comment by karlhorky** [comment]
@gskierk maybe we should wait for a release of `create-playwright`? Even though the PR was merged on July 8, the latest release [`create-playwright@1.17.133`](https://github.com/microsoft/create-playwright/releases/tag/v1.17.133) was released on June 20.

Judging by the release history, probably it will be this next release:

- [`create-playwright@1.17.134`](https://github.com/microsoft/create-playwright/releases/tag/v1.17.134)
