### ISSUE TITLE
[Bug]: Cannot get project name with VSCode extension 1.1.1-1.1.6

### ISSUE THREAD

**Issue by Zeggo** [microsoft/playwright#31031]
### Version

1.1.6

### Steps to reproduce

In global-setup.ts file, we have retrieved the current project name for distinguishing projects that need login and those that do not (e.g. data preparations, tools).

```
function getCurrentProjectName() {
  const projectArg = process.argv.find(arg => arg.includes('--project='));
  const projectName = projectArg.split('=')[1];
  return projectName;
}
```

projectName is then compared in `async function globalSetup(config: FullConfig){ ... }` to an array of project names that require login.

### Expected behavior

Getting the project name works similarly from CLI and VSCode.

### Actual behavior

When running tests/global setup from VSCode UI, execution fails to following error:

```
TypeError: Cannot read properties of undefined (reading 'split')

   at ..\global-setup.ts:51

  49 | function getCurrentProjectName() {
  50 |   const projectArg = process.argv.find(arg => arg.includes('--project='));
> 51 |   const projectName = projectArg.split('=')[1];
     |                                  ^
  52 |   return projectName;
  53 | }
  54 |
```

Running tests from the CLI works like before.

### Additional context

Workaround 1: Rolling back to v.1.0.22 of the extension
Workaround 2: Removing the problematic function and letting all projects do the unnecessary logins, causing longer times for some projects.

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i7-1360P
    Memory: 17.26 GB / 31.68 GB
  Binaries:
    Node: 20.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.89.1 - C:\Users\USER\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.2.26 - C:\Program Files\Git\usr\bin\bash.EXE
  npmPackages:
    @playwright/test: ^1.44.0 => 1.44.0
```

**Comment by mxschmitt** [comment]
While this was working in previous versions, we never considered it part of our public API. It was probably not working in UI Mode either. We recommend project dependencies it, see [here](https://playwright.dev/docs/test-global-setup-teardown#introduction) for the difference between global setup and project dependencies. I hope that helps and makes the dependencies / don't execute unnecessary code more robust.
