### ISSUE TITLE
[Bug]: (regression) VSCode Extension only detects testDir from one project

### ISSUE THREAD

**Issue by sunker** [microsoft/playwright#31032]
### Version

>1.1.1

### Steps to reproduce

1. In the Playwright config, add multiple project that use their own `testDir`. 
<details>
  <summary>I've used the following project configuration:</summary>

```json
projects: [
    {
      name: 'authenticate',
      testDir: './src/auth',
      testMatch: [/.*auth\.setup\.ts/],
    },
    {
      name: 'createUserAndAuthenticate',
      testDir: './src/auth',
      testMatch: [/.*auth\.setup\.ts/],
      use: {
        user: {
          user: 'viewer',
          password: 'password',
          role: 'Viewer',
        },
      },
    },
    {
      name: 'admin',
      testDir: './tests/as-admin-user',
      use: {
        ...devices['Desktop Chrome'],
        storageState: 'playwright/.auth/admin.json',
      },
      dependencies: ['authenticate'],
    },
    {
      name: 'viewer',
      testDir: './tests/as-viewer-user',
      use: {
        ...devices['Desktop Chrome'],
        storageState: 'playwright/.auth/viewer.json',
      },
      dependencies: ['createUserAndAuthenticate'],
    },
  ],

```
</details>

2. Open the Test explorer in vs code to see the list of detected test files. 

### Expected behavior

I expect test files from different projects (using different `testDir`) to appear in the Test explorer. 

### Actual behavior

Since the release of Playwright vscode [v1.1.1](https://github.com/microsoft/playwright-vscode/releases/tag/v1.1.1), Test explorer only list tests from one of the projects. This used to work perfectly fine in [1.0.22](https://github.com/microsoft/playwright-vscode/releases/tag/v1.0.22). 

| v1.0.22    | v1.1.1 |
| -------- | ------- |
| ![Screenshot 2024-05-27 at 13 53 11](https://github.com/microsoft/playwright/assets/2388950/b6ec6bc4-2b48-4005-8967-688924ecd6dc) | ![Screenshot 2024-05-27 at 13 54 33](https://github.com/microsoft/playwright/assets/2388950/dfe86606-7c92-430e-8c1a-375ee673ff5f) |

### Environment

```shell
System:
    OS: macOS 14.5
    Memory: 751.03 MB / 32.00 GB
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 4.2.2 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by mxschmitt** [comment]
Have you selected the other project? See here: https://github.com/microsoft/playwright/issues/30882

Note: 1.1.1 is not the latest version, we recommend using the latest version which is as of today v1.1.6.

**Comment by sunker** [comment]
> Have you selected the other project? See here: #30882

What do you mean? 

>Note: 1.1.1 is not the latest version, we recommend using the latest version which is as of today v1.1.6.

Yep - same issue appear on all versions since 1.1.1 (including 1.1.6).

**Comment by sunker** [comment]
Oh yes that was the problem. Can't believe I missed this. Sorry!
