### ISSUE TITLE
[Bug]: Tests don't run with regular expression pattern if they are also marked with tags

### ISSUE THREAD

**Issue by Viktor-Pylypenko** [microsoft/playwright#31036]
### Version

1.43.1

### Steps to reproduce

Steps to reproduce:
1. clone my repo at https://github.com/Viktor-Pylypenko/playwright-issue-tags
2. run npm install
3. run npx playwright test       
4. pay attention to the number of running tests

### Expected behavior

Output:
```
Running 2 tests using 2 workers
[chromium] › ui/example.spec.ts:3:5 › First test
First test executed
[chromium] › ui/example.spec.ts:8:5 › Second test
Second test executed
``` 

### Actual behavior

Output:
```
Running 1 test using 1 worker
[chromium] › ui/example.spec.ts:8:5 › Second test
Second test executed
``` 

### Additional context

In my project I need to filter my tests using tags and a regular expression with array of tests. First one option is for running tests and second one for selective reran failed/passed tests. I perform reran using Allure report which generates regular expression with array of tests. The example with format of regular expression is shown in my repo.

### Environment

```shell
Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.1.0 - /usr/local/bin/npm
  IDEs:
    VSCode: 1.87.0 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.43.1 => 1.43.1
```

**Comment by mxschmitt** [comment]
`grep` also contains the tags, hence filtering with `$` which matches the end of the string doesn't work.

If you change 

    /\sui\/example\.spec\.ts First test$/,

to 

    /\sui\/example\.spec\.ts First test/,

it should work - would that work for you?

I created a PR to fix the docs: https://github.com/microsoft/playwright/pull/31042

**Comment by Viktor-Pylypenko** [comment]
Yes, it works, thanks!
