### ISSUE TITLE
Upload file contains spaces

### ISSUE THREAD

**Issue by nguyentai3012** [microsoft/playwright#31043]
I have a problem with uploading files that contain spaces. Here is my code:
async uploadFile(filepath: string): Promise<void> {
    await this.driveTab.click();
    // Construct absolute path using relative path
    const filePath = path.resolve(path.dirname(__dirname), filepath);
    console.log(filePath);
    // Start waiting for file chooser before clicking. Note no await.
    const fileChooserPromise = this.page.waitForEvent("filechooser");
    await this.uploadButton.click();
    const fileChooser = await fileChooserPromise;
    await fileChooser.setFiles(filePath);
  }

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
