### ISSUE TITLE
[Feature]: Adding retries support for .net 

### ISSUE THREAD

**Issue by ertiusmeo** [microsoft/playwright#31067]
### 🚀 Feature Request

There is no retry tests feature for .net yet.
Test retries are a way to automatically re-run a test when it fails. This is useful when a test is flaky and fails intermittently.

### Motivation

I need it for my techstack:
Specflow + Playwright and parallel runs

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright-dotnet/issues/2316
