### ISSUE TITLE
[Bug]: My codegen do not shows the add assertion or rec menu

### ISSUE THREAD

**Issue by lucasxavierlucas** [microsoft/playwright#31072]
### Version

Playwright: 1.39.0
Playwright Test for VSCode: v1.1.6

### Steps to reproduce

1. Click on the 'Test' icon from the 'Playwright Test for VSCode' extension 
2. Click on the 'Record new' option

### Expected behavior

The Playwright Inspector should be open with all the codegen menus 

### Actual behavior

Only the Chromium is opened without codegen menu

video demo:
 https://jam.dev/c/119e1f23-4f7d-4fc6-85f6-ba05c9134534

### Additional context

my testDir: './tests', 

also, there is no options inside the 'projects' option in the Playwright Test for VSCode extension
even if I have it:

 projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1680, height: 900 }
      }
    } 

but no tests are found in the extension 

### Environment

```shell
System:
    OS: macOS 14.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 2.91 GB / 32.00 GB
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.39 => 1.39.0
```

**Comment by lucasxavierlucas** [comment]
Updating the playwright to the last version ( "@playwright/test": "^1.44.1",) resolved the codegen menu + Playwright Inpector to be displayed


UUnfortunately I still can't use the 'Record at cursor' because the extension do not recognize my tests, even have a correct dir and a correct 'Projects'

**Comment by dgozman** [comment]
We need more information to act on this issue. Could you please provide a repro that we can run locally?

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
