### ISSUE TITLE
[Feature]: Add a way to specify `installInstruction` alongside `executablePath`

### ISSUE THREAD

**Issue by Andarist** [microsoft/playwright#31070]
### 🚀 Feature Request

It would be great if `launchOptions` could accept an extra property like `installInstruction`

### Motivation

At the moment, Playwright throws a pretty generic message when the `executablePath` can't be found:
https://github.com/microsoft/playwright/blob/a11a6d987433674b2121f849ae485111833e4d8f/packages/playwright-core/src/server/browserType.ts#L175-L176

That is different from the error message that is thrown when the browser can't be found in the registry:
https://github.com/microsoft/playwright/blob/a11a6d987433674b2121f849ae485111833e4d8f/packages/playwright-core/src/server/registry/index.ts#L381-L400

We'd like to suggest users how they can install our browser at Replay (`npx replayio install`). It would also be nice if that first error message would get wrapped in an ASCII box like the second one.

I can work on this - if you'd only express an interest in this feature.

**Comment by dgozman** [comment]
@Andarist I don't think we'll introduce this option because it will never get enough support from our users.

Zooming out a little, I'd recommend to wrap Playwright instead of relying on options like this one or some other minor details that Playwright might not get right for your usecase. There are many ways to wrap Playwright, for example a fully custom API, or just an alternative `launch()` method, or overriding the `browser`/`context` fixture. Let me know what you think about this, and feel free to ask questions.

**Comment by Andarist** [comment]
Thanks for the answer! We are considering creating a wrapper around Playwright but we aim to improve "let's try it out" experience with that. For long-term usage, we think that requiring people to use the wrapper might be a real blocker. It's easier to get people on board when they can drop in an extra plugin than when they'd have to switch the tool entirely (even if that tool would be a drop-in replacement).

As to the alternative `launch` method - I didn't quite consider it, is it something we can try to supply using the config alone (or a fixture)? 

Overriding the browser/context fixtures is an option but ideally, we'd like to only augment the existing behavior with some minor adjustments (yes, I know, easier said than done 😉 ). I'm not sure if we could override them while importing the existing implementation from Playwright. I'll recheck this.

**Comment by dgozman** [comment]
> As to the alternative `launch` method - I didn't quite consider it, is it something we can try to supply using the config alone (or a fixture)?

Not in the config, but you can provide anything as a fixture. Note that users will have to call `launch()` manually in this case, which is not what they usually do in Playwright.

> Overriding the browser/context fixtures is an option but ideally, we'd like to only augment the existing behavior with some minor adjustments (yes, I know, easier said than done 😉 ). I'm not sure if we could override them while importing the existing implementation from Playwright. I'll recheck this.

Let us know how it goes.

**Comment by Andarist** [comment]
I'll close this feature request for now - thanks for the pointers!
