### ISSUE TITLE
[Question] How can I remove cookie EU law popup ?

### ISSUE THREAD

**Issue by Distil62** [microsoft/playwright#3107]
Hello ! 
I want to make a automatic screenshot program but I have a annoying EU cookie popup on my screenshot. How i can remove these in Playwright ? 

I try this solution but it don't work T_T

```ts
const browser = await playwright.firefox.launch({
   headless: true,
   firefoxUserPrefs: {
    "network.cookie.cookieBehavior": 2
   }
});
```
Thank !

**Comment by mxschmitt** [comment]
There is no generic solution for that since the cookie popups are different from website to website.
In general you can automate it by pressing the "Accept" button on the page, that should work.

Duplicate of #2566

**Comment by fynn-grab** [comment]
I built a library for this: [ai-dont-care-about-cookies](https://github.com/fynn-grab/AI-Dont-Care-About-Cookies). It uses 15,000+ rules from the "I Still Don't Care About Cookies" extension, ported to Playwright.

```js
const { blockCookieDialogs } = require('ai-dont-care-about-cookies');
await blockCookieDialogs(page);
await page.goto('https://example.com');
```
