### ISSUE TITLE
[Feature]: Dynamic load balancing - reallocate unstarted tests from busy workers to idle ones.

### ISSUE THREAD

**Issue by 4Tel-SteveM** [microsoft/playwright#31078]
### 🚀 Feature Request

This feature would reallocate unstarted tests from busy workers to idle ones.

### Example

If a worker has finished all of its allocated tests, rather than sitting idle it should do an unstarted test that has been allocated to another worker who is busy executing some other test.

### Motivation
I often run executions as I need to know how changes I have made affect other tests before putting up a PR, the sooner I get my results the sooner I can move onto another task. 
I want my test executions to be quicker without having to rearrange spec files or manage test tags.
I can see on the Allure Reports Timeline that the last worker to finish will complete several tests after all other workers finish their tests. It would be nice to see these idle workers pick up the slack.

![2024-05-30 14_26_29-Allure Docker Service UI](https://github.com/microsoft/playwright/assets/80795916/182dd4b7-4e6f-4bce-99d0-1bd01a5ae3ba)

**Comment by 4Tel-SteveM** [comment]
For reference, 
The long running tests have already been optomised as much as feasible.
These tests are all one after the other in the spec to keep things organised.
There are not enough of these long running tests to justify their own spec file.

**Comment by dgozman** [comment]
@4Tel-SteveM Playwright does already allocate tests to the worker that is available. I guess you are running tests without `fullyParallel: true` option set, so Playwright runs all tests from a single file in a single worker, as explained [in the docs](https://playwright.dev/docs/test-parallel). If that is not the case, we would love to see a repro to debug and fix the issue.

**Comment by dgozman** [comment]
Closing as per above. If you find a bug, please file a new issue using the "Bug Report" template.
