### ISSUE TITLE
[Feature]: Toggled to set cwd as from workspace folder or from config folder for vscode extension

### ISSUE THREAD

**Issue by redjohnzarra** [microsoft/playwright#31073]
### 🚀 Feature Request

I appreciate the setup with selectable configurations, especially since we're using a monorepo (kudos to you all). The thing that I don't like, however, is setting the cwd in the opened workspace - in our case, root of the project (both in run debug and run test). This causes environment configurations from the root to be used, and as our project setup is done inside the project folder (as it should be), it leads to issues. Although this can be fixed by opening a workspace only in my project folder, I also have dependencies and utilities to update outside of it. What would be nice is if there's a toggle to choose which cwd to use (workspace or config folder). I have actually cloned the git repo and manually compiled a .vsix file, which I am using until this is fixed. I hope you can address this, as I want to have an updated extension with the cool features you are developing. You're doing some great things guys and I can't thank you enough 💙

### Example

Option to select which cwd to use (workspace folder or the config folder) 

### Motivation

It will solve the issues of people who are in a monorepo, like in our case, where each team has their specific project/s and all the configs are located in each proj folder

**Comment by redjohnzarra** [comment]
![Screenshot_2024-05-29-20-25-16-871_app rvx android youtube-edit](https://github.com/microsoft/playwright/assets/14845199/4ab69369-539b-4cd2-aff7-10fd530ad94b)

**Comment by dgozman** [comment]
Please see the `Q: My working directory is now workspace folder. Why?` section in this Q&A: https://github.com/microsoft/playwright/issues/30882.
