### ISSUE TITLE
[Bug]: Playwright VSCODE extension is not displayed

### ISSUE THREAD

**Issue by Romarionijim** [microsoft/playwright#31081]
### Version

1.29.0

### Steps to reproduce

* private repo
* in my current company - the testing blocks of playwright are customized to make it similar to jest in order to make it easy for developers that write unit test with jest to make all testing frameworks similar

example:

consts.ts file:

```
export const it = test;
export const beforeAll = it.beforeAll;
export const afterAll = it.afterAll;
```

test structure example:

```
describe.serial.only('create manual matching program', () => {
  //classes reference here
  beforeAll(async ({ browser }) => {
   // class instantiations here
  });

  afterAll(async () => {
    await page.close();
  });

  it('should navigate to Experts tab successfully', async () => {
  // tests go here


  })

```

the problem is that the extension does not recognize the test and does not display the play button near the "it" , even if I switch to "test" it still does not display the extension, tried to disabled and enable, uninstall and install but it does not seem to display.

note that the it extends test so it should recognize it anyways.

### Expected behavior

Playwright extension should be displayed in spec files in test blocks

### Actual behavior

Extension does not show up / not displayed at all. - even after disabling and enabling / uninstall and install.

### Environment

```shell
macOS Ventura 13.6.5
playwright version 1.29.0
```

**Comment by dgozman** [comment]
@Romarionijim In this case we will need a full repro from you, so that we can run it locally and fix the issue. Unfortunately, the two short snippets you shared are not a repro.

**Comment by Romarionijim** [comment]
@dgozman unfortunately I cannot share the repo because it is private for organisation - can tell me what you need so I can maybe share more?

**Comment by dgozman** [comment]
@Romarionijim We need something that we can run that exhibits the problem. If you can narrow down your repo to something you can share and that still shows the problem - that's exactly what we need.

**Comment by Romarionijim** [comment]
@dgozman to be honest I don't see a reason for it not to work and I tried investigating and can't seem to understand

package.json version:

```
 "@playwright/test": "^1.44.1",
```

browser config:

```
import { devices } from '@playwright/test';

export function getBrowsersToRunOn() {
  const browsers = {
    chromium: {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        headless: process.env.HEADLESS !== 'false',
        contextOptions: {
          permissions: [ 'clipboard-read', 'clipboard-write' ]
        }
      }
    },

    firefox: {
      name: 'firefox',
      use: {
        ...devices['Desktop Firefox'],
        contextOptions: {
          permissions: [ 'geolocation' ]
        }
      }
    },

    webkit: {
      name: 'webkit',
      use: {
        ...devices['Desktop Safari'],
        contextOptions: {
          permissions: [ 'geolocation' ]
        }
      }
    },

    /* mobile viewports */

    mobileChrome: {
      name: 'Mobile Chrome',
      use: {
        ...devices['Pixel 5']
      }
    },

    mobileSafari: {
      name: 'Mobile Safari',
      use: {
        ...devices['iPhone 12']
      }
    },

    /* branded browsers. */
    edge: {
      name: 'Microsoft Edge',
      use: {
        channel: 'msedge',
        headless: false

      }
    },
    chrome: {
      name: 'Google Chrome',
      use: {
        channel: 'chrome'
      }
    }
  };

  const definedBrowsers = process.env.BROWSERS ?
    process.env.BROWSERS.split(',') :
    [];

  const runOnBrowsers = definedBrowsers
    .map((browser) => browsers[browser])
    .filter((browser) => browser);

  return runOnBrowsers.length === 0 ?
    [
      ...runOnBrowsers,
      browsers.chromium,
      browsers.firefox,
      browsers.webkit
    ] :
    runOnBrowsers;
}

```

playwright config

```
import { PlaywrightTestConfig } from '@playwright/test';

import { getBrowsersToRunOn } from './browsers-selector';

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// require('dotenv').config();

/**
 * See https://playwright.dev/docs/test-configuration.
 */
const config: PlaywrightTestConfig = {
  globalSetup: require.resolve('./global-setup'),
  testDir: './tests/critical-tests',
  /* Maximum time one test can run for. */
  timeout: 120 * 1000,
  globalTimeout: 60 * 60 * 1000,
  expect: {
    /**
     * Maximum time expect() should wait for the condition to be met.
     * For example in `await expect(locator).toHaveText();`
     */
    timeout: 45 * 1000
  },
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ?
    (process.env.RETRIES ? +process.env.RETRIES : 2) :
    0,
  /* Opt out of parallel tests on CI. */
  // eslint-disable-next-line no-undefined
  workers: process.env.CI ?
    (process.env.WORKERS ? +process.env.WORKERS : 4) :
    (process.env.WORKERS ? +process.env.WORKERS : 1),
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: [
    ['html', { open: 'never', outputFolder: '../playwright-report/' }],
    ['list'],
    ['json', { outputFile: '../playwright-report/critical-tests-test-results.json' }]
  ],
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
    actionTimeout: 50 * 1000,
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://localhost:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    testIdAttribute: 'data-test-id',

    /* Record Videos on failed tests */
    video: 'retain-on-failure',
    launchOptions: {
      slowMo: 650,
    }
  },

  /* Configure projects for major browsers */
  projects: getBrowsersToRunOn(),
  metadata: {
    testGroup: 'critical'
  },

  /* Folder for test artifacts such as screenshots, videos, traces, etc. */
  outputDir: '../test-results/'

  /* Run your local dev server before starting the tests */
  // webServer: {
  //   command: 'npm run start',
  //   port: 3000,
  // },
};

export default config;

```


consts file for customisation:

```
import { test } from '@playwright/test';
export const DELAY = 1000;
export const describe = test.describe;
export const it = test;
export const beforeAll = it.beforeAll;
export const afterAll = it.afterAll;
export const activateLongerBeforeAll = () => test.setTimeout(240000);
```


test example with "test":

```
import { test } from '@playwright/test'

test.describe('', async () => {



  test.beforeEach('', async ({ page }) => {
    await page.goto('https://www.google.com')
  })

  test('test navigagion', async ({ page }) => {
    const currentUrl = page.url();
    expect(currentUrl).toContain('google.com');
  })
})
```

example with "it"
```
import { beforeAll, describe, it } from "@gs-consts";
import { Page } from "@playwright/test";


describe('test', async () => {
  let page: Page



  beforeAll(async ({ browser }) => {
    page = await browser.newPage();
    await page.goto('https://www.google.com')
  })

  it('should navigate to google', async() => {
    const currentUrl = page.url();
    expect(currentUrl).toContain('google.com')
  })
})
```


I updated version to latest.
I restarted extensions (disable and enable, uninstall and install, quit vscode and open multiple times)

the extension is not showing at all and I can't seem to figure out the problem!

![image](https://github.com/microsoft/playwright/assets/75387323/df0f2bbb-1040-4d92-9735-76d2287cd8a3)

**Comment by mxschmitt** [comment]
The `@gs-consts` part looks suspicious! Could you try if it works if you create a project [from scratch](https://playwright.dev/docs/intro) following our docs?

Also a bunch of code snippets are hard for us to reproduce - we need something which we can clone locally. Thanks for your understanding.

**Comment by Romarionijim** [comment]
@mxschmitt the gs-consts file is an index.ts file generated by barrelsby
```
/**
 * @file Automatically generated by barrelsby.
 */
export * from './consts';
export * from './index 2';
```
 I have managed to create a new project that has the same test from scratch with the same setup and there it works fine.
this is the local repo with the same setup => []( https://github.com/Romarionijim/playwright-extension-issue)
I just can't seem to figure out why the extension is not displaying in my current job vscode, I don't see any indication for it not to work since I tried everything.

**Comment by dgozman** [comment]
@Romarionijim I have tried your repository on macOS 13.6.7, playwright 1.44.1, vscode 1.89.1 and playwright vscode extension 1.1.6. Everything works for me - tests are visible in the test tree, play button appears next to each test in the source file, I can run the tests, etc.

However, I noticed some strange things in the repo that might be a problem:
- `index.ts` includes `export * from "./tests/example.spec";` You should not import anything from the spec files, this can mess up with test locations. Since spec files are not exporting anything, there is no need to import them.
- `playwright.config.ts` is fully commented-out. You probably do not want that.

**Comment by Romarionijim** [comment]
@dgozman Yeah I did these changes but forgot to push them to the repo.
do you know or have an indication why the extension is not displaying at my workplace in this case? because it is basically the same setup but with real projects.

**Comment by mxschmitt** [comment]
I tried your repository as well and it was working fine for me. Could you confirm if you have the project selected in the Playwright section?

<img width="307" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/f4a0fe9d-692c-4854-802b-500bdd256183">

**Comment by Romarionijim** [comment]
yes the project is selected 
![image](https://github.com/microsoft/playwright/assets/75387323/2274d8ce-c243-4984-ade6-e9c8babff564)
