### ISSUE TITLE
[Feature]: Multi-select tests in VS code extension

### ISSUE THREAD

**Issue by Vivek-Kini** [microsoft/playwright#31082]
### 🚀 Feature Request

Multi-select test in VS code extension: When there are multiple tests under a describe block and there are a list of tests displayed in extension. We should possibly give options to select and run only few tests (scenario when we have some failures and not all) among all for debugging/retrying manually.

### Example

This would potentially be used by dev to debug and run only a few set of tests among all that are shown under a particular group (describe block)

### Motivation

I would help debugging and better reporting/feedback for extension based feature

**Comment by dgozman** [comment]
@Vivek-Kini The UI is controlled by VSCode itself, not Playwright. Therefore you should file such issues at https://github.com/microsoft/vscode instead.
