### ISSUE TITLE
[Bug]: CodeceptJS - Playwright - Jenkins : Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by MariaAvramescu26** [microsoft/playwright#31085]
### Version

1.44

### Steps to reproduce

I am trying to run my CodeceptJS tests with Playwright in Jenkins (Linux machine) and I get an error that I cannot reproduce locally.

```
TypeError: Cannot read properties of undefined (reading 'toString')
    at Playwright.fillField (node_modules/codeceptjs/lib/helper/Playwright.js:1728:25)
```

My Jenkins file contains the following:

 `      steps {
                script {
                    try {
                        sh """
                            cd '${JOB_BASE_NAME}'
                            npx playwright install --with-deps chromium
                            npm install
                        """
                    } catch (Exception e) {
                        echo "Error installing dependencies: ${e}"
                        // You can choose to proceed or fail the build based on the severity of the issue
                    }
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    sh """
                       cd '${JOB_BASE_NAME}'
                        echo "Running tests with CodeceptJS and Playwright"
                        npx playwright --version
                        npx codeceptjs info
                        npx codeceptjs run --steps --grep "@PRE" --verbose --reporter mochawesome
                    """
                }
            }`

Let me know if you have any idea on what it can be wrong. thank you!

### Expected behavior

I should be able to run my tests.

### Actual behavior

TypeError: Cannot read properties of undefined (reading 'toString')
    at Playwright.fillField (node_modules/codeceptjs/lib/helper/Playwright.js:1728:25)

### Environment

```shell
codeceptVersion:  "3.6.2"
nodeInfo:  20.10.0
osInfo:  Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
cpuInfo:  (2) x64 AMD EPYC 7571
playwright: 1.44.0
```

**Comment by mxschmitt** [comment]
This looks like a bug in codeceptjs, I recommend filing it there: https://github.com/codeceptjs/CodeceptJS

**Comment by MariaAvramescu26** [comment]
indeed, actually, the main problem is not Jenkins is not able to load my CodeceptJS config. No idea why
```
 npx codeceptjs run --steps --grep @PRE --verbose --reporter mochawesome
Error: Can not load config from /var/jenkins_home/workspace/QA/FLP Front Automation/codecept.config.js or /var/jenkins_home/workspace/QA/FLP Front Automation/codecept.conf.js or /var/jenkins_home/workspace/QA/FLP Front Automation/codecept.js or /var/jenkins_home/workspace/QA/FLP Front Automation/codecept.config.ts or /var/jenkins_home/workspace/QA/FLP Front Automation/codecept.conf.ts
```
