### ISSUE TITLE
How to delete cookies for Electron Application?

### ISSUE THREAD

**Issue by drilon241** [microsoft/playwright#31084]
### Please do not submit this issue.

- [X] I understand
```[tasklist]
### Tasks
```

**Comment by drilon241** [comment]
Since playwright [version 1.43](https://playwright.dev/docs/release-notes#version-143) now there is a way to delete cookies by providing name, path etc

**However** when trying to use the [browserContext.clearCookies()](https://playwright.dev/docs/api/class-browsercontext#browser-context-clear-cookies), the command fires and succeeds according to logs  but the user of the Electron Application remains logged in.

Logs 
```
pw:api => browserContext.clearCookies started +13ms
pw:api <= browserContext.clearCookies succeeded +36ms
```

Context:

Playwright Version: 1.44.0
Operating System: Ubuntu 22.04.04LTS
Browser: Electron (v29)

**Comment by mxschmitt** [comment]
I tried the following which works for me:

```ts
test('should click the button', async ({ newWindow, server }) => {
  const window = await newWindow();
  await window.context().addCookies([{ url: server.EMPTY_PAGE, name: 'foo', value: 'bar' }]);
  console.log(await window.context().cookies());
  await window.context().clearCookies({ name: 'foo' });
  console.log(await window.context().cookies());
});
```

could you please re-file and follow the bug template? This helps us a ton in order to triage issues like that, thanks!

**Comment by drilon241** [comment]
Thank you for the speedy response :pray: 
Issue raised here https://github.com/microsoft/playwright/issues/31092
