### ISSUE TITLE
[Bug]: machine hangs while executing Playwright script via Selenium server 4

### ISSUE THREAD

**Issue by rpraveen91** [microsoft/playwright#31099]
### Version

1.42.0

### Steps to reproduce

1. Set up selenium server 4 standalone 
2. Trigger playwright script to execute via Selenium server
3. Make the test fail

### Expected behavior

I expect machine to up and running without any impact due to execution 

### Actual behavior

Machine hangs after the failure 

### Environment

```shell
System:
OS: Windows 10 10.0.19045
CPU: (2) x64 Intel(R) Xeon(R) Gold 6150 CPU @ 2.70GHz
Memory: 3.55 GB / 12.00 GB

Binaries:
Node: 16.20.0
nom: 8.19.4
pnpm: 6.20.4

IDEs:
Viscode: 1.82.1

Language:
Bash: 4.4.23

npmPackages:
@playwright/test: 1.42.0
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
