### ISSUE TITLE
[Question] Add PID to pw logs

### ISSUE THREAD

**Issue by DJ-Glock** [microsoft/playwright#3109]
Hey guys.
Is it possible to add a nodejs process id into your traces?
In my tests I used the following pattern: PID_${process.pid}, probably not the best, but it really helps.
Any chance for this to be implemented?

Background:
I'm asking because I use mocha (latest version) with PW in **parallel** mode. Mocha runs it's test files in parallel and all processes write their logs to output. So it's very hard to understand what process wrote a particular line.
Previously mocha did not support parallel execution and I used mocha-parallel-tests framework. It worked fine, every process wrote it's own log and only after finish, all logs were pushed in output. So it looked like this:

PID_1 Tests started
PID_1 Some playwright logs
PID_1 Tests finished
PID_2 Tests started
PID_2 Some playwright logs
PID_2 Tests finished
PID_3 Tests started
PID_3 Some playwright logs
PID_3 Tests finished

Now it looks like this (but without PIDs for PW logs):
PID_1 Tests started
PID_1 Some playwright logs
PID_2 Tests started
PID_2 Some playwright logs
PID_1 Some playwright logs
PID_2 Some playwright logs
PID_1 Some playwright logs
PID_2 Some playwright logs
PID_2 Tests finished
PID_1 Tests finished

**Comment by JoelEinbinder** [comment]
I don't think this is a feature we'd want to support directly in playwright. Ideally mocha would split your logs by the test that generated them. However I think you can solve your issue today using the [Logger API](https://playwright.dev/#version=v1.2.1&path=docs%2Fapi.md&q=class-logger).

```js
  const browser = await chromium.launch({
    logger: {
      isEnabled: (name, severity) => true,
      log: (name, severity, message, args) => console.log(`${process.pid} ${name} ${message}`)
    }
  });
```

**Comment by DJ-Glock** [comment]
@JoelEinbinder thanks for your answer. I tried to setup logger and almost succeeded. The only thing left is execution time. I'll be happy if you can give me another hint.

I would like to have almost the same message as I got with pw:api enabled:
```
  pw:api => page.type started +5ms
  pw:api waiting for selector "#password-field" [] +1ms

```
Now I got:
```
DEBUG PID_21228 Fri, 31 Jul 2020 09:12:27 GMT: api:info => page.type started
DEBUG PID_21228 Fri, 31 Jul 2020 09:12:27 GMT: api:info waiting for selector "#password-field"
```

So how to add execution time to the end of line? Tried to find it in pw source, but was unable to :(

```
logger: {
    isEnabled: name => name === 'api',
    log: (name, severity, message) =>
      console.log(
        `DEBUG PID_${process.pid} ${new Date().toUTCString()}: ${name}:${severity} ${message}`
      ),
  },
```
