### ISSUE TITLE
Dotenv file not loading in 1.44

### ISSUE THREAD

**Issue by truthanb** [microsoft/playwright#31107]
I am having an issue with 1.44 not loading the dotenv file. When go back to previous versions the dotenv loads. When I update to 1.44.1 the dotenv does not load. No other code changes. 

In the playwright.config.ts file the following has worked for previous versions.

```
import { defineConfig, devices } from '@playwright/test';
import dotenv from 'dotenv';

dotenv.config({ path: '.env', override: true });
```

I tried to search to see if there was anything else related and open, but not seeing anything. What other information can I provide to help make this a better question?

**Comment by dgozman** [comment]
@truthanb Playwright should not affect `dotenv` operations, but perhaps there is a bug? You should provide a full repro, ideally a small repository on github, along with instructions of how to reproduce the issue, for example cli commands that you run.

**Comment by truthanb** [comment]
> @truthanb Playwright should not affect `dotenv` operations, but perhaps there is a bug? You should provide a full repro, ideally a small repository on github, along with instructions of how to reproduce the issue, for example cli commands that you run.

Thanks. It may take me a day or so to get things together on that end.

**Comment by truthanb** [comment]
When I tried to replicate this on a different machine with a new project it worked. Going to close this, thanks.
