### ISSUE TITLE
[Bug]: page.route block requests when using sync_playwright

### ISSUE THREAD

**Issue by zhoudaqiang** [microsoft/playwright#31101]
### Version

1.44.0

### Steps to reproduce

```Python
import time
from playwright.sync_api import sync_playwright
def intercept_request(route, request):
    print(request)
    route.continue_()
with sync_playwright() as p:
    browser =p.chromium.launch(headless=False)
    page =  browser.new_page()
    page.route('**/*',intercept_request)
    page.goto('https://www.google.com')
    page.fill('textarea[name="q"]','playwright')
    page.keyboard.press('Enter')
    time.sleep(10)
```
### Expected behavior

 route not block request when  press 'enter' , because i  call the  function of continue_

### Actual behavior

when  press 'enter', the requests is block

but when i use async_playwright，It looks normal！

please help! thx!

### Environment

```shell
python :3.8
playwright: 1.44.0
```

**Comment by dgozman** [comment]
@zhoudaqiang Instead of `time.sleep(10)`, call `page.wait_for_timeout(10000)`. Sleeping blocks a synchronous program.

**Comment by zhoudaqiang** [comment]
thanks you very much!
