### ISSUE TITLE
[Feature]: Report - Annotations - Modify description behavior when using URLs

### ISSUE THREAD

**Issue by brunojbarros** [microsoft/playwright#31118]
### 🚀 Feature Request

When the description has only an url it is shown as a link, but when there is more text (not only an url), the url has not the <a> tag

### Example

**Current behavior**:
Example 1:
```
        annotation: [
            { type: 'related issues', description: 'https://github.com/microsoft/playwright/issues/23180' },
            { type: 'more info', description: 'read https://playwright.dev/docs/intro and https://playwright.dev/docs/api/class-playwright' },
        ],
```
![image](https://github.com/microsoft/playwright/assets/12484408/86dd7554-6c3b-4c92-83a3-ae2fb094babc)

Example 2:
```
        annotation: [
            { type: 'related issues', description: 'https://github.com/microsoft/playwright/issues/23180, https://github.com/microsoft/playwright/issues/23181' },
        ],
```
![image](https://github.com/microsoft/playwright/assets/12484408/9227a82c-180f-44bd-8fc9-41e711790329)

**Expected behavior**:
Example 1:
![image](https://github.com/microsoft/playwright/assets/12484408/f904fbc3-ddd5-40c1-ba59-978133321ea2)

Example 2:
Keep the ", " instead of joining it with href `https://github.com/microsoft/playwright/issues/23180, https://github.com/microsoft/playwright/issues/23181`
![image](https://github.com/microsoft/playwright/assets/12484408/381c46cd-41db-4dbf-bd4e-34be1b1f758b)

### Motivation

Improve usability of annotations.

**Comment by Joe-Hendley** [comment]
I can have a go at this one. Looks like it'll involve updating the logic in `renderAnnotationDescription()`.

**Comment by mxschmitt** [comment]
Fixes by https://github.com/microsoft/playwright/pull/31521
