### ISSUE TITLE
Read records from AG Grid using Playwright

### ISSUE THREAD

**Issue by lijachandran** [microsoft/playwright#31115]
Are there any inbuilt libraries or third-party libraries available to read content from AG Grid in Playwright.

**Comment by dgozman** [comment]
This issue tracker is reserved for bug reports and feature requests.

For anything else, such as questions or getting help, please see:
- [The Playwright documentation](https://playwright.dev/)
- [Our Discord server](https://aka.ms/playwright/discord)
