### ISSUE TITLE
[Bug]: When loading `storageState` the extension don't loads in the chromium browser

### ISSUE THREAD

**Issue by TusharSoni014** [microsoft/playwright#31129]
### Version

1.44.1

### Steps to reproduce

1. Clone this repo, https://github.com/TusharSoni014/playwright-plasmo-gh-action
2. install the packages with `pnpm i`
3. First uncomment the code inside `auth.setup.ts`, paste your gmail id and pass in the placeholders.
4. run the test with `npx playwright test --headed`
5. a file called `user.json` will be created inside `playwright/.auth/user.json`
6. now you can comment the code inside `auth.setup.ts` again, we will use that `user.json` file to bypass the login from now on.

### Expected behavior

So if i use the extended test function from `fixtures.ts` the session will not load from the `user.json` file but the extension will load, and if we use the test fucntion from "@playwright/test" the session will load but the extension will not.

What i need is i want to load the google session from the `user.json` file, tried configuring the `playwright.config.ts` file to have `--launchOptions` but the extension just dont loads when the storagestate loads, is it a bug or im missing something?

### Actual behavior

When the extension loads, the storagestate dont loads, and when the storage state loads, the extension dont loads

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 11.13 GB / 31.71 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.2 - C:\Program Files\nodejs\pnpm.CMD
  IDEs:
    VSCode: 1.89.1 - C:\Users\tusha\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.1.16 - C:\Windows\system32\bash.EXE
  npmPackages:
    @playwright/test: ^1.44.1 => 1.44.1
    playwright: ^1.44.1 => 1.44.1
    playwright-extra: ^4.3.6 => 4.3.6
```

**Comment by mxschmitt** [comment]
I didn't run your reproducible yet, but it looks like since you are using persistent context and launch it by that manually, the launchOptions from the use section in your config don't get considered. We have a feature request for that already: https://github.com/microsoft/playwright/issues/31108

**Comment by TusharSoni014** [comment]
so loading the extension along with persistent session is not yet inside playwright?
