### ISSUE TITLE
[Docs]: typo: "it's" should be "its"

### ISSUE THREAD

**Issue by ggorlen** [microsoft/playwright#31125]
### Page(s)

- https://playwright.dev/docs/api/class-frame#frame-get-by-role
- https://playwright.dev/docs/api/class-page#page-get-by-role
- https://playwright.dev/docs/api/class-locator#locator-get-by-role
- https://playwright.dev/docs/api/class-framelocator#frame-locator-get-by-role

### Description

"it's" should be "its" in https://playwright.dev/docs/api/class-framelocator#frame-locator-get-by-role and other similar pages.

**Comment by mxschmitt** [comment]
While we appreciate docs fixes it does not reason the generated footprint in terms of CI status check as of today. See https://github.com/microsoft/playwright/pull/31126. Thanks for your understanding.
