### ISSUE TITLE
[Docs]: `echo "\nplaywright/.auth" >> .gitignore` is incorrect for Bash

### ISSUE THREAD

**Issue by ggorlen** [microsoft/playwright#31122]
### Page(s)

https://playwright.dev/docs/auth

### Description

The command listed in [Core Concepts](https://playwright.dev/docs/auth#core-concepts) is incorrect for Bash:

```bash
mkdir -p playwright/.auth
echo "\nplaywright/.auth" >> .gitignore
```

The file this creates contains literally `\nplaywright/.auth` rather than expected `playwright/.auth`.

The correct version is

```bash
mkdir -p playwright/.auth
echo "playwright/.auth" >> .gitignore
```

**Comment by mxschmitt** [comment]
Which OS are you using? I tried it on macOS and Linux and it works for me there. Having the `\n` there seems useful.

**Comment by ggorlen** [comment]
@mxschmitt Ah, I should have mentioned that--I'm on Ubuntu 22.04. I don't have a Mac, but I'm a bit surprised it's different for you.

```
$ bash --version
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
$ mkdir -p playwright/.auth
$ echo "\nplaywright/.auth" >> .gitignore
$ cat .gitignore
\nplaywright/.auth
```

**Comment by mxschmitt** [comment]
I can reproduce on Ubuntu but not on macOS - interesting!

**Comment by mxschmitt** [comment]
Looks like it should be:

    echo $'\nplaywright/.auth' >> .gitignore

instead, as per https://unix.stackexchange.com/a/191696

**Comment by ggorlen** [comment]
That works for me, I'll update my PR.

I wonder if `printf "playwright/.auth" >> .gitignore` might be feasible too.
