### ISSUE TITLE
[Bug]: getByRole with combobox and name does not work

### ISSUE THREAD

**Issue by jdgarvey** [microsoft/playwright#31135]
### Version

1.44.1

### Steps to reproduce

1. Clone repo at https://github.com/jdgarvey/combobox-reproduction
2. Follow README instructions to install, run, and test

### Expected behavior

I expect `page.getByRole('combobox', {name: 'some-name'})` to work.

### Actual behavior

Using `page.getByRole('combobox')` without a name works, but as soon as I add a name that is obviously present on the element, playwright is no longer able to locate the element.

### Additional context

**Works:**
```typescript
test('combobox', async ({ page }) => {
  await page.goto('http://localhost:3000');

  await expect(page.getByRole('combobox')).toHaveValue('cybertruck');
});
```

**Does not work:**
```typescript
test('combobox with name', async ({ page }) => {
  await page.goto('http://localhost:3000');

  await expect(page.getByRole('combobox', {name: 'vehicles'})).toHaveValue('cybertruck');
});
```

**HTML:**
```html
<select name="vehicles" id="vehicles">
  <option value="cybertruck">Tesla Cybertruck</option>
  <option value="plaid">Tesla Plaid</option>
  <option value="three">Tesla Three</option>
</select>
```

**Broken test result:**
![image](https://github.com/microsoft/playwright/assets/1544557/23c45b2c-6232-47ca-9b25-e3e49b3e3e45)

**Codegen (possibly related?):**
![image](https://github.com/microsoft/playwright/assets/1544557/f8d9aaa2-6c10-4600-9775-4b2e8713e3d0)

### Environment

```shell
System:
  OS: macOS 14.5
  CPU: (10) arm64 Apple M1 Pro
  Memory: 125.42 MB / 16.00 GB
Binaries:
  Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
  Yarn: 1.22.22 - /opt/homebrew/bin/yarn
  npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
  pnpm: 8.10.5 - /opt/homebrew/bin/pnpm
  bun: 1.0.25 - ~/.bun/bin/bun
IDEs:
  VSCode: 1.89.1 - /opt/homebrew/bin/code
Languages:
  Bash: 3.2.57 - /bin/bash
npmPackages:
  @playwright/test: ^1.44.1 => 1.44.1
```

**Comment by dgozman** [comment]
@jdgarvey Thank you for the issue!

I looked at the repro, and the combobox in question does not have an [accessible name](https://w3c.github.io/accname/#dfn-accessible-name). Note that accessible name is not computed based on the `name` attribute. If you would like to make this combobox accessible, set an `aria-label` attribute instead.

You can check the accessible name during development in the Accessibility pane in Chrome DevTools:
<img width="632" alt="accessibility pane" src="https://github.com/microsoft/playwright/assets/9881434/81a34d4f-bc9e-489d-aebf-25fa38ff76c0">

**Comment by jdgarvey** [comment]
I see! This works, thank you!
