### ISSUE TITLE
[Bug]: Trace network start time shows end time instead of actual start time

### ISSUE THREAD

**Issue by chris13524** [microsoft/playwright#31133]
### Version

1.44.1

### Steps to reproduce

1. Clone my repo: https://github.com/chris13524/playwright-trace-network-start-bug
2. `npm run dev`
3. `npx playwright test --ui`
4. Run the test
5. You should see that the network request is initiated somewhere before the 1s mark, and the response received about 1s later. E.g.:
    <img width="239" alt="Screenshot 2024-06-03 at 16 50 01" src="https://github.com/microsoft/playwright/assets/1979423/9dec60a2-763d-43a7-9b14-3f4d0ccd2e7c">
6. However if you look at the network tab, it claims the network request started after the 1s mark:
    <img width="828" alt="Screenshot 2024-06-03 at 16 51 09" src="https://github.com/microsoft/playwright/assets/1979423/c70d6998-2a44-4f80-aa5e-9eb65458295f">

### Expected behavior

Start time of the network request should match the start time in the console

### Actual behavior

Start time is the time that the network request finished

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M2
    Memory: 46.19 MB / 24.00 GB
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.11.1/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 9.1.2 - /opt/homebrew/bin/pnpm
  IDEs:
    VSCode: 1.89.1 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.44.1 => 1.44.1
```

**Comment by mxschmitt** [comment]
I can repro.
