### ISSUE TITLE
[Bug]: WebKit Build (v2003): Spreading class instances causes result not to be a plain object (but instances of the original class)

### ISSUE THREAD

**Issue by Llois41** [microsoft/playwright#31132]
### Version

1.44.1

### Steps to reproduce

1. Install Playwright 1.44.x
2. Intstall WebKit via `playwright install`
3. Start the Playwright WebKit by running `playwright wk`
4. type the following snippet into the console

- `class Test {field1 = 'foo'}`
- `const t1 = {...new Test()}`
- `t1 instanceof Test` \\ -> resolves to `true`.

### Expected behavior

I expect to see the spread operator behave the same in the new WebKit (JavaScriptCore) version as in the other JavaScript engines and like in the previous WebKit version.

### Actual behavior

After updating Playwright to v1.44 we found that our website broke. After analyzing the problem, we found out that the issue is that WebKit now handles the spread operator different from previous versions. Unfortunately I could not find out the exact version Playwright is using, but we installed Bun@1.1.12 (which also uses JavaScriptCore) and it has the same bug.

In v8 (11.3.244.8-node.23 for Node 20.14.0 and 12.4.254.14-node.12 for Node 22.2.0) or SpiderMonkey (Firefox@125.0.1) for example this code snippet resolves to `false`, since `t1` is a plain object instead of a class.

We think this is a bug in WebKit/JavaScriptCore but the reproduction was very difficult for a few reasons. It would be helpful if there is a simple way to tell which WebKit build version you are running. 

Maybe you know how to debug this better, maybe isolated from Playwright to find the causing issue.

### Additional context

I also tried Playwright v1.45.0-alpha-2024-06-03 which has WebKit build v2016 but the issue still appears.

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 693.36 MB / 32.00 GB
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    Yarn: 4.2.2 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
```

**Comment by mxschmitt** [comment]
Great repro!

---

**Bisect notes:**

Playwright WebKit revision 1996 good
Playwright WebKit revision 1997 bad

Playwright diff: https://github.com/microsoft/playwright-browsers/commit/0dd276d38578ea6055baa5e2b568417d2349abdc

WebKit upstream diff: https://github.com/webkit/webkit/compare/cd9be0fded51cea4c2c3a7c9a21d6b4d341df09d...91f787886ac542eb4148d991b629c028f389f0cf

Might be related to https://github.com/WebKit/WebKit/commit/804d44f89619bfae3e5e2e21a07669b1fb320d57.

Let me file it upstream.

**Comment by mxschmitt** [comment]
Closing since it has been fixed upstream.
