### ISSUE TITLE
[Feature]: To add the failure screenshot into the report folder

### ISSUE THREAD

**Issue by hari-prasad1** [microsoft/playwright#31146]
### 🚀 Feature Request

Currently I've a custom setup for html reports such that it creates a new folder on every run. It's as below

reporter: [['html', { outputFolder: 'playwright-report/report-' + new Date().toISOString().replace(/[:.]/g, '-') }]]

Is there a way to add the failure screenshot to the same path?

### Motivation

To consolidate run reports/screenshots in same place for easier debugging

**Comment by mxschmitt** [comment]
> Is there a way to add the failure screenshot to the same path?

If you have set [`screenshot: 'only-on-failure'`](https://playwright.dev/docs/api/class-testoptions#test-options-screenshot) screenshots get generated during the test run and put into the HTML report.

If you have custom files which you want to attach, see [here](https://playwright.dev/docs/api/class-testinfo#test-info-attach).

**Comment by hari-prasad1** [comment]
cool, thanks
