### ISSUE TITLE
[Bug]: VS-Code plugin restarts multiple time with multiple browsers

### ISSUE THREAD

**Issue by nirus** [microsoft/playwright#31150]
### Version

v1.1.6

### Steps to reproduce

1. Mono Repo project
2. Create a simple multiple project with different browsers ( Webkit and Chrome ) via playwright config
3. Execute a testcase from the plugin

### Expected behavior

1. Should not open multiple browser and window
2. Should stope the process when stop button is pressed.

### Actual behavior

1. Opens multiple browser and window in loop
2. Runner continuously keeps running the playwright process even if stopped

### Additional context

Version 1.0.22 works perfectly

### Environment

```shell
OS: MAC OS v 12.5.1
NodeJs v20
VS code Version: 1.89.1 (Universal)
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
