### ISSUE TITLE
[Feature]: apiBaseURL

### ISSUE THREAD

**Issue by eveltman-twinfield** [microsoft/playwright#31166]
### 🚀 Feature Request

Hi, next to the baseURL I would like to have an apiBaseURL test option.

### Example

Most of the times
for page.goto() ideally we want to use paths relative to the login URL
for page.route() we want to use paths relative to the (REST) API URL
for page.waitForURL() we want to use paths relative to the application URL
for page.waitForRequest() or page.waitForResponse() we want to use paths relative to the (REST) API URL
for API requests we want to use paths relative to the (REST) API URL

The first (login) case is a bit an exception because our tests spend most of the time on the application URL.
So I only listed it for completeness sake. 

Having the distinction between baseURL and apiBaseURL would already be a great improvement.

### Motivation

Having a separation between API base URL and frontend base URL would enable us to use relative URLs in most places.
It's more readable and maintainable than URLs with string interpolation and environment variables.

I created this issue separate from https://github.com/microsoft/playwright/issues/23738 because that other issue is only speaking about using the API base URL for API testing.

**Comment by mxschmitt** [comment]
I think this is highly specific to the environment of your application - so splitting it up would be opinionated and would not work for everyone. Some customers have even multiple backends on different URL paths. We would instead recommend using e.g. a constant for one which is less commonly used. You can also use glob pattern matching to avoid a full URL at all in some APIs e.g. waitFor or route.

It's also possible to override the base URL for whole describe or files see [here](https://playwright.dev/docs/test-use-options#:~:text=You%20can%20override%20options%20for%20a%20specific%20test%20file%20by%20using%20the%20test.use()%20method%20and%20passing%20in%20the%20options.%20For%20example%20to%20run%20tests%20with%20the%20French%20locale%20for%20a%20specific%20test%3A).
