### ISSUE TITLE
[Bug]: await page.screenshot({ path: "forIndividuals.png", fullPage: true });  is not capturing the latest stats from the stats bar

### ISSUE THREAD

**Issue by Feroza22** [microsoft/playwright#31160]
### Version

Version 1.44.1

### Steps to reproduce

```ts
test.describe("For- Individuals page", () => {
  
  test.beforeEach(async ({ page }) => {
   
    
    await page.goto(
      "https://hingehealth.com/for-individuals/?experience=inc_massage2",
      { waitUntil: "networkidle" }
    );
    await page.waitForTimeout(5000);
  });
  
  test("Full-contact us page visual test on contact us URL", async ({
    page
  }) => {
    // Navigate to the custom URL.
    test.setTimeout(100000);
      let supportPage = Growth.supportPage(page);
   
    const acceptCookiesButtonSelector = "button#onetrust-accept-btn-handler"; // Update this with the actual selector from your page

    try {
      await page.waitForSelector(acceptCookiesButtonSelector, {
        timeout: 5000,
      });
      await page.click(acceptCookiesButtonSelector);
    } catch (error) {
      console.log("Accept Cookies button not found or not clickable:", error);
    }
    // Ensure the page is fully rendered and scroll to the bottom.
    await page.evaluate(() => {
      window.scrollTo(0, document.body.scrollHeight);
      return new Promise((resolve) => setTimeout(resolve, 2000));
    });

    // Scroll back to top to ensure complete capture.
    await page.evaluate(() => {
      window.scrollTo(0, 0);
      return new Promise((resolve) => setTimeout(resolve, 1000));
    });

    await supportPage.stats.waitFor({ state: "visible" });
 
    await supportPage.stats.screenshot({path: "stats.png" });
    await page.waitForTimeout(10000);

    await page.screenshot({ path: "forIndividuals.png", fullPage: true ,timeout:5000});

  });
});
```

### Expected behavior

A complete page should be captured with the latest stats values

![image](https://github.com/microsoft/playwright/assets/70381448/3ad3253b-b442-4294-a40a-8c27ad7139b5)

### Actual behavior

I see nav bar is captured some where in the middle of the page and the stats value is not taken as latest
<img width="1512" alt="Screenshot 2024-06-05 at 11 46 21 AM" src="https://github.com/microsoft/playwright/assets/70381448/5431c17a-e06b-4701-b4a2-07411cc06fe4">

### Environment

```shell
System:
  OS:   VENTURA 13.4(22F66)

Binaries:
  Node: v18.18.0 - 
  npm: 9.8.1
npmPackages:
  @playwright/test: 1.41.1 => 1.41.1

VS code:1.89.1
```

**Comment by ivan-krupskyi** [comment]
I believe that's how "Full page screenshot" functionality works in chrome. If you run "Capture full size screenshot" command from your browser you"ll see same issue. So that's rather a Chrome bug, not Playwright. I have the same issue.

**Comment by mxschmitt** [comment]
Looks like the page you are trying to make a screenshot of is taking a long time to finish rendering. There is unfortunately not a universal way of waiting until the rendering of web pages has finished - since it might be different for every web app out there in the internet. I would recommend to connect with your engineering team to e.g. find an element which gets rendered last for [which you could wait](https://playwright.dev/docs/api/class-locator#locator-wait-for) which is a common approach to solve that. 

Since this is not a Playwright bug, I'm going to close it for now.

**Comment by ivan-krupskyi** [comment]
It's not about how long the page loads, his page has loaded already. It's rather about "how" Chromium performs full-page screenshot. It skews CSS in a way that it brakes the logic of your sticky elements. There's no easy workaround for that for now
