### ISSUE TITLE
[Bug]: @Tags - bug or feature?

### ISSUE THREAD

**Issue by cctui-dev** [microsoft/playwright#31168]
### Version

1.44.1

### Steps to reproduce

Add tags to your tests using the new method:
 ```
test('test full report', {
  tag: ['@tag1', '@tag2', '@hello @this @is @tag3']
  }, async ({ page }) => {
    // ...
});
```

run test:
`npx playwright test -g @this`

### Expected behavior

I would expect it not to run as multiple tags are added to one array position

### Actual behavior

It works!

### Additional context

I wouldn't expect this to be valid for tags based on the docs example showing tags needing to be defined in an array if more than one is used.

Its not a bad thing that it runs for me but it may affect others. If it is a feature could the docs be updated to reflect?

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M3 Pro
    Memory: 5.78 GB / 36.00 GB
  Binaries:
    Node: 21.6.0 - ~/.nvm/versions/node/v21.6.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v21.6.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.44.1 => 1.44.1
```

**Comment by mxschmitt** [comment]
We recommend specifying tags separately, otherwise UI Mode, VSCode won't treat them as individual tags and you'll lack filter support there.
