### ISSUE TITLE
[Docs]: Page Hydration examples

### ISSUE THREAD

**Issue by msmith1114** [microsoft/playwright#31179]
### Page(s)

https://playwright.dev/docs/navigations#hydration

### Description

So I think this page does a good job of explaining what hydration is, but I think this would be a good place for some examples?

Maybe some techniques or things a person "should" be doing? or an example of what is happening? Since I think i've ran into this problem with newer front-end frameworks. What type of events should one be waiting for/etc...?

Right now i've been using network requests to wait for to step around this issue. But is there other events that are common that these frameworks may use that we can wait for?

Thanks!

**Comment by mxschmitt** [comment]
In most of the cases the issue is in the app rather than a bug in the end-to-end test. We recommend fixing it in the web app instead.
