### ISSUE TITLE
[Feature]:  Remote Browser Control via API

### ISSUE THREAD

**Issue by KSemenenko** [microsoft/playwright#31178]
### 🚀 Feature Request

Connecting to a remote browser can be very useful. For instance, if I have a browser running on a virtual machine, I need a way to connect to it. It would be great to use an API to connect to that machine and control the browser from my computer, as if it were running locally.

### Example

Remote connection, remove browser control. Remove view. like  I use browser operating on a virtual machine with a Japanese language in OS, and I need to do automation on it, take some screenshot, press some buttons.

### Motivation

I have a lot of workers that control the browser on my virtual machines, and every time I need to do authorization or save cookies, but sometimes it happens that I need exactly one browser for one user. and so I would know that somewhere there is a browser running and I can use it from other machines.

**Comment by mxschmitt** [comment]
Playwright already offers running browsers remotely in the library:

- server: https://playwright.dev/docs/api/class-browsertype#browser-type-launch-server
- client: https://playwright.dev/docs/api/class-browsertype#browser-type-connect

And you can also use it inside the test-runner as well: https://github.com/microsoft/playwright/issues/26482

Not sure if I understand your use-case entirely. If this is about combining manual interaction with automated Playwright end-to-end testing, this is not something we recommend/support.

**Comment by KSemenenko** [comment]
It’s about some stable environment where I can run tests. 
but it keeps my cookies, state and etc. 
your examples looks exactly as I looking for! 
thanks a lot!

**Comment by mxschmitt** [comment]
If its about keeping cookies/state we recommend following our [auth guide](https://playwright.dev/docs/auth). Closing by that.
