### ISSUE TITLE
[Bug]: --tag not working

### ISSUE THREAD

**Issue by cctui-dev** [microsoft/playwright#31170]
### Version

1.44.1

### Steps to reproduce

Run a test in cli:

`npx playwright test --tag @tag1`

### Expected behavior

Only tests that have a tag of `@tag1` to run.

As mentioned in docs https://playwright.dev/docs/test-cli

<img width="819" alt="image" src="https://github.com/microsoft/playwright/assets/152899343/1ec1a524-d01a-4157-80a4-43d5d7cd8e41">

### Actual behavior

The test didn't run and was given an error of

`error: unknown option '--tag'`

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M3 Pro
    Memory: 5.78 GB / 36.00 GB
  Binaries:
    Node: 21.6.0 - ~/.nvm/versions/node/v21.6.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v21.6.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.44.1 => 1.44.1
```

**Comment by mxschmitt** [comment]
This was a bug in the docs, we fixed it already as part of https://github.com/microsoft/playwright/pull/31041. This flag does not exist.
