### ISSUE TITLE
[Feature]: Sample steps for wrapper class library similar to one in selenium

### ISSUE THREAD

**Issue by srk-3009** [microsoft/playwright#31172]
### 🚀 Feature Request

Sample steps for wrapper class library similar to one in selenium. Where we can define a certain wrapper class for common actions like click, check, selecting value from dropdown etc

in typescript playwright

### Example

https://www.ontestautomation.com/using-wrapper-methods-for-better-error-handling-in-selenium/

### Motivation

Automatically failing the test whenever a specific error occurs by including an Assert.Fail();
Restoring or recreating specific conditions or a specific application state after an error occurs to prepare for the next test (e.g. ending the current user session)
Automatically restarting a test in case of a specific error

**Comment by mxschmitt** [comment]
Playwright code in the end is just JavaScript or the language binding you are using. So in JavaScript you can extract common code into classes, functions or use POM. You can [box them](https://playwright.dev/docs/api/class-test#test-step:~:text=%7D)%3B-,Boxing,-When%20something%20inside) to get better error messages as well.

Defaults like timeouts are commonly put into the central Playwright config file. 

Have you tried these approaches?

**Comment by srk-3009** [comment]
Could you please guide me with any sample project please if possible? it would be helpful.

**Comment by mxschmitt** [comment]
You mean for POM? See this guide: https://playwright.dev/docs/pom

**Comment by mxschmitt** [comment]
Closing as per above for now. For further questions, we recommend Discord.
