### ISSUE TITLE
[Bug]: Chrome - clicking on three dots - crashed 

### ISSUE THREAD

**Issue by SathishKumarBackiam** [microsoft/playwright#31176]
### Version

1.44.0

### Steps to reproduce

java - chrome latest (google juice - dependency injection pattern)
launch a test in debug mode
click on the three dots in the chrome browser

### Expected behavior

chrome's options for three dots should be displayed

### Actual behavior

chrome crashed

### Environment

```shell
Windows 11
Java
```

**Comment by mxschmitt** [comment]
Do you mean the profile icon in the top right?

Looks like a duplicate of https://github.com/microsoft/playwright/issues/30955.

**Comment by SathishKumarBackiam** [comment]
oh yeah, Thanks !
