### ISSUE TITLE
[Feature]: Properly support WebKit's feature flags switching CLI argument

### ISSUE THREAD

**Issue by oprypkhantc** [microsoft/playwright#31185]
### 🚀 Feature Request

This is a follow up to #31161 and partly #17368.

Currently, running WebKit from Playwright does not support the `--features` CLI argument that the GTK and WPE versions of WebKit support:

https://github.com/WebKit/WebKit/blob/main/Tools/MiniBrowser/gtk/main.c#L384
https://github.com/WebKit/WebKit/blob/main/Tools/MiniBrowser/wpe/main.cpp#L76

These arguments allow enabling or disabling specific parts of WebKit hidden behind feature flags. One example of such feature is ITP (or intelligent tracking prevention, or cross-site tracking prevention), which *can* be disabled using `----features=IsThirdPartyCookieBlockingDisabled` on a regular build of WebKit's MiniBrowser for GTK/WPE.

If you try to do the same with Playwright's `launchOptions.args` configuration, it seems to always be ignored:

```javascript
launchOptions: {
    args: ["--features=IsThirdPartyCookieBlockingDisabled"],
},
```

Although this flag is **not** supported on the MiniBrowser build for Mac, supporting it for GTK/WPE would already be a lot, and expanding support to Mac wouldn't be a huge problem.

Please see the motivation below.

### Motivation

In our case, the motivation is to disable the ITP. The reasoning is this:

We have frontend of a web app running on `home.something.loc` domain, and an API running on `api.something.loc` locally and on CI. Whenever a user (being on `home.something.loc`) authenticates through an endpoint on `api.something.loc`, the API sets a refresh token cookie on the `.something.loc` domain, meaning both `home` and `api` subdomains *should* have access to it and *should* be sending it alongside the requests.

In reality, this doesn't happen. WebKit treats `home.something.loc` and `api.something.loc` as cross-site requests, so the ITP is blocking the cookies and the refresh token is not sent. 

Interestingly, if you change the TLD of both domains from `.loc` to `.com`, it starts working correctly. WebKit would now treats those requests as cross-origin, not cross-site, and a refresh token cookie would get sent too.

This is because WebKit treats ALL non-public TLD names (like `.loc`, `.local`, `.localhost` and other TLDs regularly used for development) as different sites, even when they share a common second level domain. `api.something.loc` and `home.something.loc` are two different, unrelated websites for WebKit, while `api.something.com` and `home.something.com` are both a single `something.com` website with different subdomains.

Which is why we want to disable ITP for WebKit when running tests. In regular Safari (outside tests), this can be done by going into Settings -> Feature flags and checking the "Disable ITP" feature flag option, which fixes the issue. With WebKit and Playwright, there's no option to allow doing that.

We're aware of the possible consequences, but this is a long standing problem that can hardly be addressed without either Playwright's or WebKit's help. Looking at #17368, it doesn't seem like anything ITP related is going to be accepted into Playwright, and looking at https://bugs.webkit.org/show_bug.cgi?id=254991, it doesn't seem like this is going to get fixed in WebKit either.

The proposed solution (allowing arbitrary feature flags to be enabled/disabled) allows not only the ITP to be enabled/disabled, but other features as well which may be caused by additions to WebKit in the future. It's a generalized solution that will be helpful to developers even after the ITP issues are resolved.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/17368 - (we use this issue to track disabling feature across all 3 OSes).

**Comment by oprypkhantc** [comment]
@mxschmitt Doesn't that issue apply to just ITP? Because although addressing this issue would allow disabling ITP, it's not the only use case for it

**Comment by ellemedit** [comment]
I agree with @oprypkhantc This suggestion is proposing different area rather than just ITP. @mxschmitt Can you reopen this? So we can control feature flag of Safari for testing.

<img width="948" alt="Image" src="https://github.com/user-attachments/assets/39c3de90-d84c-477e-852f-f8f495f79f9c" />
