### ISSUE TITLE
[Bug]:  Version 1.44.1 Error occuring while using command npx playwright test in Vscode

### ISSUE THREAD

**Issue by ramyasravz** [microsoft/playwright#31194]
### Version

1.44.1

### Steps to reproduce

1. Open visual Studio and open folder playwright and playwright_ext which is created by me
2. Open terminal->new terminal-->npx playwright test
3. Error occuring like Running 6 tests using 6 workers
  1) [webkit] › example.spec.js:4:1 › has title ────────────────────────────────────────────────────

    Error: browserContext.newPage: Target page, context or browser has been closed

  2) [webkit] › example.spec.js:11:1 › get started link ────────────────────────────────────────────

    Error: browserContext.newPage: Target page, context or browser has been closed

  2 failed
    [webkit] › example.spec.js:4:1 › has title ─────────────────────────────────────────────────────
    [webkit] › example.spec.js:11:1 › get started link ─────────────────────────────────────────────
  4 passed (9.0s)

### Expected behavior

All browsers should pass

### Actual behavior

Running 6 tests using 6 workers
  1) [webkit] › example.spec.js:4:1 › has title ────────────────────────────────────────────────────

    Error: browserContext.newPage: Target page, context or browser has been closed

  2) [webkit] › example.spec.js:11:1 › get started link ────────────────────────────────────────────

    Error: browserContext.newPage: Target page, context or browser has been closed

  2 failed
    [webkit] › example.spec.js:4:1 › has title ─────────────────────────────────────────────────────
    [webkit] › example.spec.js:11:1 › get started link ─────────────────────────────────────────────
  4 passed (9.0s)

### Environment

```shell
Windows 32,
```

**Comment by mxschmitt** [comment]
Is Windows 32 a 32 bit version of Windows? We don't support that, only 64bit is supported.

**Comment by ramyasravz** [comment]
its windows 62.


[image: image.png]

**Comment by mxschmitt** [comment]
Could you try setting the following environment variable before you run your tests? That might yield debug output:

```
$Env:DEBUG="pw:browser"
npx playwright test
```

or when using Batch:

```
set DEBUG=pw:browser
npx playwright test
```

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
