### ISSUE TITLE
[Bug]: Getting white screen on test video/trace

### ISSUE THREAD

**Issue by lexihill1** [microsoft/playwright#31195]
### Version

1.33.0

### Steps to reproduce

sometimes the test is failed once it starts for unknown reason, and the video and trace display white screen.

![image](https://github.com/microsoft/playwright/assets/141853803/9da29336-ecdd-449b-9b8b-f69b5c8395ba)

![image](https://github.com/microsoft/playwright/assets/141853803/7f3155b6-4bae-45e7-97c9-4ee543a2aef7)

### Expected behavior

test should start and if fails for real reason, the video and trace should be informative

### Actual behavior

test doesn't start to run well, so the trace and video are broken

### Environment

```shell
@playwright/test: 1.33.0
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!

We also recommend using the latest version of Playwright.
