### ISSUE TITLE
[Bug]: Playwright Trace Viewer not loading UI when used via WebView2

### ISSUE THREAD

**Issue by kimberly-microsoft** [microsoft/playwright#31209]
### Version

^1.43.1

### Steps to reproduce

1. Run the test using the following WebView2 setup [sandbox.zip](https://github.com/user-attachments/files/15742275/sandbox.zip)
3. Open the trace file
4. It should look something like the attached trace file
[trace.zip](https://github.com/user-attachments/files/15742228/trace.zip)

### Expected behavior

I expect to see HTML/UI in the trace file that shows what is happening when the test is running. 

### Actual behavior

The images in the trace file are blank and nothing is shown
![image](https://github.com/microsoft/playwright/assets/143560248/cd0196e5-5aaa-4e9f-a89b-3eb562c840d4)

### Environment

```shell
System:
    OS: Windows 10 10.0.22631
    Memory: 11.55 GB / 31.83 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE  
    Yarn: 1.23.19 - ~\AppData\Roaming\npm\yarn.CMD    
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
```

**Comment by yury-s** [comment]
Could you extract relevant bits from the App and provide a complete reproduction that we could run locally (the app + tests)? You can start with our [test app](https://github.com/microsoft/playwright/tree/main/tests/webview2/webview2-app)  and see if the problem reproduces with it.

**Comment by yury-s** [comment]
Closing as it was discussed in the internal teams chat. Let's start with a new issue if there is new actionable information about the problem.
