### ISSUE TITLE
[Regression]: Incorrect reading of `.env` file in Playwright version 1.44.1 and Playwright Test for VSCode version 1.1.6

### ISSUE THREAD

**Issue by kosteklvp** [microsoft/playwright#31201]
### Last Good Version

1.43.1

### First Bad Version

1.44.1

### Steps to reproduce

I have a `dotenv.config();` line in `playwright.config.ts` file. It reads environmental variables from `.env` file located in the same folder as `playwright.config.ts` file. I use [dotenv](https://www.npmjs.com/package/dotenv) for this.

My project structure looks like this:
"D:\Workspace\BS1B-Specs\playwright-tests\playwright.config.ts"

Before, this line `dotenv.config();` was looking for `.env` file in "D:\Workspace\BS1B-Specs\playwright-tests\.env", which was correct.
But since upgrading to Playwright 1.44.1 and "Playwright Test for VSCode" v1.1.6, it is looking for `.env` file in "D:\Workspace\BS1B-Specs\.env", so one folder up. There is no `.env` file, so I can't run tests.

### Expected behavior

`dotenv.config();` looks for `.env` file in playwright project catalog (where `playwright.config.ts` is located).

### Actual behavior

`dotenv.config();` looks for `.env` file in main project catalog (where `playwright.config.ts` is located).

### Additional context

This is also related to "Playwright Test for VSCode" extension. This problem occurs on v1.1.6. Works good on 1.0.22 version.

When I run tests from command line, it works correctly.

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12800H
    Memory: 10.14 GB / 31.69 GB
  Binaries:
    Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.5 - ~\AppData\Roaming\npm\pnpm.CMD
  IDEs:
    VSCode: 1.90.0 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.1.16 - C:\Windows\system32\bash.EXE
  npmPackages:
    @playwright/test: ^1.40.0 => 1.44.1
```

**Comment by mxschmitt** [comment]
Looks like this is the same as answered here: https://github.com/microsoft/playwright/issues/30882#:~:text=Q%3A%20My%20working%20directory%20is%20now%20workspace%20folder.%20Why%3F

We updated our documentation to reflect that in the docs / create-playwright, since reading files via the cwd not recommended.

**Comment by kosteklvp** [comment]
Thank you. It looks like this helped. Issue can be closed.
