### ISSUE TITLE
[Questions]gmail.com: This browser or app may not be secure. 

### ISSUE THREAD

**Issue by cdoky** [microsoft/playwright#31212]
```ts
const context = await chromium.launchPersistentContext(cacheDirPath, {
        headless: false,
        args: browserArgs,
        ignoreDefaultArgs: [
            `--enable-automation`
        ]
    });

let page = await context.newPage();
await page.goto("https://www.gmail.com");
```
![image](https://github.com/microsoft/playwright/assets/626401/e4c79310-1478-4b15-9804-4bdff0a2a40e)

**Comment by yury-s** [comment]
This doesn't sound like a bug or feature request, please use our [community resources](https://playwright.dev/community/welcome) for general questions. If you think this is a bug in Playwright, please open a new issue and follow the bug template.
