### ISSUE TITLE
[While Runing Test in ADO with chrome]:  net::ERR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by LuckySearchingForSmile** [microsoft/playwright#31216]
### Version

1.42.1

### Steps to reproduce

When I am runing the tests for my-company application. 
I am getting Error for only chromium. If run with different browsers Tests are Passed.
Error I am getting :  **net::ERR_HTTP2_PROTOCOL_ERROR**
In the report I am seeing Just White Blank page. Browser Not even opening.

### Expected behavior

chrome is not working.

### Actual behavior

Browser should open.

### Additional context

![error_Http](https://github.com/microsoft/playwright/assets/172153149/74b71e32-b230-48d6-b6df-3731d5f836eb)

### Environment

```shell
ubuntu-latest
node 22.1.0 x64
"@playwright/test": "^1.42.1"
```

**Comment by yury-s** [comment]
Please follow our bug template and provide a minimal self-contained reproduction that we could run locally to reproduce the problem, otherwise we can't take any action on this.

**Comment by LuckySearchingForSmile** [comment]
@yury-s  Would you like to know what info you need

**Comment by yury-s** [comment]
We need it a reproduction example that we could run locally to see the problem. But I was able to accidentally reproduce it with simple navigation in headless browser to https://www.adidas.com/. Folding this into https://github.com/microsoft/playwright/issues/31216
