### ISSUE TITLE
[Feature]: PageGotoOptions.Timeout should support any kind of errors

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [microsoft/playwright#31211]
### 🚀 Feature Request

I was getting intermittent errors when calling Page.GotoAsync after 1 sec, even I specified 30sec timeout in PageGotoOptions.
Error Message:Initialization method PlayWright.Tests..OpenPage threw exception. Microsoft.Playwright.PlaywrightException: net::ERR_CONNECTION_REFUSED at http://localhost:8080/
- navigating to "http://localhost:8080/", waiting until "load".

ChatGPT suggested “Although the timeout setting helps with waiting for the page to load, it won’t help if the connection cannot be established initially. You might want to add some retry logic to handle intermittent connection issues.”
I’ve introduced suggested by ChatGpt retry workaround, but it will be better, if it will be supported out of the box.

### Example

During timeout period connection errors should be retried like the following : 

  ```
/// <summary>
    /// Although the timeout setting helps with waiting for the page to load, it won't help if the connection cannot be established initially
    /// We have intermittent Microsoft.Playwright.PlaywrightException: net::ERR_CONNECTION_REFUSED at http://localhost:8080/
    /// </summary>
    /// <param name="baseUrl"></param>
    /// <returns></returns>
    private async Task OpenPageWithRetries(string baseUrl)
    {
        var navigationOptions = new PageGotoOptions
        {
            //WaitUntilState.Load, which waits for the entire page to load
            //WaitUntilState.DOMContentLoaded(waits until the DOM content is loaded) and WaitUntilState.NetworkIdle(waits until there are no network requests for at least 500ms).
            WaitUntil = WaitUntilState.Load,
            Timeout = 10000 // Set the timeout in milliseconds, default is 30 seconds
        };

        int maxRetries = 5;
        int retryCount = 0;
        while (retryCount < maxRetries)
        {
            try
            {
                // Navigate to the URL with the specified options
                await Page.GotoAsync(baseUrl, navigationOptions);
                break; // Exit the loop if successful
            }
            catch (Exception ex)
            {
                retryCount++;
                if (retryCount == maxRetries)
                {
                    TestContext.WriteLine($"Max retries reached. Unable to connect. {ex}");
                    throw;
                }
                var secondsDelay = retryCount;
                TestContext.WriteLine($"Retry {retryCount}/{maxRetries} failed. Retrying in {secondsDelay} second... {ex}");
                await Task.Delay(secondsDelay * 1000); // Wait before retrying
            }
        }
}
```

### Motivation

No need to implement retry manually.

**Comment by mxschmitt** [comment]
Playwright retries actions and expects but its intentional that goto does not retry. We recommend waiting for your web app to start before you run your tests on them. Using e.g. [wait-on](https://www.npmjs.com/package/wait-on) or similar in .NET.

Closing for now, since we don't plan to implement something like this.
