### ISSUE TITLE
[QUESTION] Chromium versions are mismatched in docker, leading to launch failures

### ISSUE THREAD

**Issue by hinzed1127** [microsoft/playwright#3122]
**Context:**
I was getting a browser launch failure when trying to run within a Docker container.

The displayed error said`Error: Failed to launch browser: Error: spawn /home/pwuser/.cache/ms-playwright/chromium-782078/chrome-linux/chrome ENOENT`

Taking a closer look, I found that `chromium-790602` was the version in my `/home/pwuser/.cach/ms-playwright/` directory
#3087 led me to try modifying my dockerfile to this, using the `dev` tag instead of `bionic`:

```dockerfile
FROM mcr.microsoft.com/playwright:dev

COPY . /src/project

WORKDIR /src/project

USER root

RUN npm install

USER pwuser
```

and updating my `package.json` dependencies to use `playwright@next` instead of `"^1.2.0"`:

```json
"dependencies": {
    "expect-playwright": "^0.2.5",
    "jest": "^25.1.0",
    "jest-playwright-preset": "^1.2.1",
    "playwright": "next" 
  }
```

for some reason npm install was only working with the root user for `playwright@next`. 

**Question**

Is there a way to make chromium versions match using the more stable releases? Specifically, I'd like to just use `FROM mcr.microsoft.com/playwright:dev` and `playwright@latest`, but I was not having any success figuring that out.

**Comment by aslushnikov** [comment]
> Is there a way to make chromium versions match using the more stable releases? Specifically, I'd like to just use FROM mcr.microsoft.com/playwright:dev and playwright@latest, but I was not having any success figuring that out.

@hinzed1127 We're half-way through finalizing our docker story. With the 1.3 release, we will start versioning our docker images. So if you use `playwright 1.3`, you'll be able to do `FROM mcr.microsoft.com/playwright:v1.3.0-bionic`.

Note though that you'll have to pin your playwright version in `package.json` and update docker image version simultaneously with Playwright version.

> for some reason npm install was only working with the root user for playwright@next.

Can you clarify this? This sounds like something unexpected to me.

**Comment by hinzed1127** [comment]
@aslushnikov Thanks for clarifying! I'll keep an eye out for the version updates, that should be much easier to keep sync.

As far as the second part, I'm seeing permissions issues when trying to install playwright in docker when running as `pwuser`. This is the error output from `npm install`:

```
npm WARN checkPermissions Missing write access to /src/project/node_modules/playwright
npm WARN checkPermissions Missing write access to /src/project/node_modules/playwright/node_modules
npm WARN checkPermissions Missing write access to /src/project/node_modules
npm WARN va-sso-smoketests@0.0.1 No repository field.

npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /src/project/node_modules/playwright
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/src/project/node_modules/playwright'
npm ERR!  [Error: EACCES: permission denied, access '/src/project/node_modules/playwright'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/src/project/node_modules/playwright'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
```

Strangely, I'm only seeing this error when attempting to install `playwright@^1.2.0`, but no issues arise with `playwright@next`. In any case, switching to root in the dockerfile before installing solved that issue (i.e., installing `playwright@^1.2.0).

```dockerfile

USER root

RUN npm install

USER pwuser
```

**Comment by aslushnikov** [comment]
> As far as the second part, I'm seeing permissions issues when trying to install playwright in docker when running as pwuser. This is the error output from npm install:

@hinzed1127  Could it be due to the `copy` command that happens under root? You can actually `chown` files in docker when copying them:

```dockerfile
COPY --chown=pwuser . /src/project
```

**Comment by isudilovskiy** [comment]
So.. it's been a while, any news about images versioning?

**Comment by arjunattam** [comment]
Hi @isudilovskiy – docker images are now versioned. For example, you can use `mcr.microsoft.com/playwright:v1.5.2-bionic` for current latest based on Ubuntu 18.04 (Bionic). All [available tags are here](https://mcr.microsoft.com/v2/playwright/tags/list).

I'll close this issue since it's stale. Please feel free to open a new issue if we're missing anything!
