### ISSUE TITLE
Want  to understand how codegen works ?

### ISSUE THREAD

**Issue by mechandan** [microsoft/playwright#31226]
### Please do not submit this issue.

- [X] I understand

**Comment by mechandan** [comment]
Does codegen uses any LLM to generate / identify locators?
Are they storing the generated scripts / data to their servers ? 

Can someone plz help me understanding , how does codegen works.

thanks!

**Comment by mxschmitt** [comment]
Codegen is **not** talking to any servers and **not** using LLMs. It's fully open source, just algorithms to identify the best locator and some code generation boilerplate.

See here:

- https://github.com/microsoft/playwright/tree/main/packages/recorder
- https://github.com/microsoft/playwright/blob/701a405bdfd8e9bfe61dd4ee6b0b91e6fff6c89e/packages/playwright-core/src/server/injected/selectorGenerator.ts
