### ISSUE TITLE
[Bug]: `navigator.appVersion` is hardcoded, always returns Windows NT

### ISSUE THREAD

**Issue by napsta32** [microsoft/playwright#31238]
### Version

1.44.1

### Steps to reproduce

1. Create a basic test for macOS and add a `page.pause()`:

```ts
test('Check google', async ({page}) => {
    await page.goto('https://www.google.com');
    await page.pause();
});
```

2. Run the test using `npx playwright test --headed`
3. When the test gets paused, open the dev console and evaluate `navigator.appVersion`

### Expected behavior

I see `Macintosh` in my `appVersion`:

```ts
'5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36'
```

### Actual behavior

My `appVersion` says `Windows NT`:

```ts
'5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.26 Safari/537.36'
```

### Additional context

We need this because our old website uses this `appVersion` to check if it is macOS or not.

### Environment

```shell
System:
    OS: macOS 14.4.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 340.67 MB / 16.00 GB
  Binaries:
    Node: 20.6.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 10.5.0 - /usr/local/bin/npm
  IDEs:
    VSCode: 1.89.1 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.44.1 => 1.44.1 
    playwright: ^1.44.1 => 1.44.1 
    playwright-core: ^1.44.1 => 1.44.1
```

**Comment by napsta32** [comment]
There is an old issue related to this:

https://github.com/microsoft/playwright/pull/8406

**Comment by yury-s** [comment]
You can always provide custom `userAgent` string in [the config](https://playwright.dev/docs/api/class-testoptions#test-options-user-agent) and it will change `appVersion` too, e.g. the following will set it to Mac:

```js
import { test, expect, type Page } from '@playwright/test';

test.use({
  userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.26 Safari/537.36',
})

test('test', async ({ page }) => {
  await page.goto('https://example.com');
  console.log(await page.evaluate(() => navigator.appVersion)); 
  console.log(await page.evaluate(() => navigator.platform)); 
});
```
Would this work for your scenario?

**Comment by napsta32** [comment]
Yes, thanks! I added it in my `playwright.config.ts` and it works fine.
I will probably add some logic: `process.platform === 'darwin' ? 'macintosh' : 'Windows NT'` or something like that.

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/8216
