### ISSUE TITLE
by using chromium.connect always browser.contexts() are empty

### ISSUE THREAD

**Issue by mrhappyheart** [microsoft/playwright#31234]
### Please do not submit this issue.

- [x] I understand

**Comment by mrhappyheart** [comment]
Hi guys
i'm trying to have access to default context which is connected to launchServer() command
but i tried many different ways when make new connection i can not have access to any other contexts and it's empty!

**Comment by yury-s** [comment]
This doesn't sound like a bug or feature request, please use our [community resources](https://playwright.dev/community/welcome) for general questions. If you think this is a bug in Playwright, please open a new issue and follow the bug template.
