### ISSUE TITLE
[Bug]: Codegen can't record `selectOption` on Windows Edge

### ISSUE THREAD

**Issue by mtsmfm** [microsoft/playwright#31248]
### Version

1.44.1

### Steps to reproduce

1. Run `npx playwright codegen --channel msedge https://html-preview.github.io/?url=https://gist.githubusercontent.com/mtsmfm/0e4d7c72231f3d6ab444d0aa6a878b18/raw/a4642d1b35555746419fffac64b877d76d699cdd/select.html` on PowerShell
2. Select an option

### Expected behavior

All `selectOption` operations should be recorded

### Actual behavior

Nothing is recorded.

https://github.com/microsoft/playwright/assets/1796864/36e40eb6-5ea8-4027-81fc-4b97b9a7500c

### Additional context

If we move mouse quickly to avoid focusing on any elements other than options, we can record the event it seems.
Especially we need to avoid putting the cursor on this space.

![image](https://github.com/microsoft/playwright/assets/1796864/8efa6041-21fe-4c3a-9e91-23b41b2c2b4c)

By using cursor keys it's also recorded.

With Chrome/Chromium, if we move mouse outside of the menu the operation isn't recorded.

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 2.01 GB / 31.84 GB
  Binaries:
    Node: 20.14.0 - ~\AppData\Local\fnm_multishells\9052_1718098056641\node.EXE
    npm: 10.7.0 - ~\AppData\Local\fnm_multishells\9052_1718098056641\npm.CMD
  IDEs:
    VSCode: 1.90.0 - C:\Users\fumia\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.0.17 - C:\WINDOWS\system32\bash.EXE
```

**Comment by ruifigueira** [comment]
I was able to reproduce the error in Edge. It seems to be sending the wrong CSS selector for select fields, as you can see in the debug:

![image](https://github.com/microsoft/playwright/assets/1374559/db10a9d3-c8ff-4916-8eb4-baea3292cc5f)

I bumped into a similar problem some months ago:

https://github.com/microsoft/playwright/pull/29087#discussion_r1472003583
