### ISSUE TITLE
How to read value from browser appData?

### ISSUE THREAD

**Issue by daniavander** [microsoft/playwright#31246]
What do you suggest to eveluate a webapp value?

I want to add 'appData.NewForumSearchEnabled' and i need this's value true or false?

thanks in davance

**Comment by yury-s** [comment]
This doesn't sound like a bug or feature request, please use our [community resources](https://playwright.dev/community/welcome) for general questions. If you think this is a bug in Playwright, please open a new issue and follow the bug template.
