### ISSUE TITLE
[Bug]: When browser is launched with "start-maximised" option, viewport is set as null and video recording enabled, recorded video is displayed only in the upper half of the screen. 

### ISSUE THREAD

**Issue by akila0791** [microsoft/playwright#31242]
### Version

1.44.0

### Steps to reproduce

1. Enable video recording.
2. Start browser with "--start-maximised" option.
3. Set viewport as null.
4. Run the test case.

### Expected behavior

Video recorded should be fit the entire screen.

### Actual behavior

Recorded video is displayed only on the upper half of the screen. Screenshot attached. In the screenshot, upper half where white screen is displayed shows the video recorded. Lower part shown in grey is empty.

![video proof](https://github.com/microsoft/playwright/assets/3743940/a6115f30-5d22-4307-9fbe-adb5c339eafc)

### Environment

```shell
TESTNG, PLAYWRIGHT, JAVA
```

**Comment by yury-s** [comment]
Playwright doesn't provide any guarantees when browsers are launched with custom command line flags. Folding this request into https://github.com/microsoft/playwright/issues/1086

**Comment by gladykov** [comment]
Since using new headless I am able to reproduce this issue not in full screen mode. @yury-s Please reconsider reopening or if needed I can report as a separate issue.

Env: Linux, X11, XFCE, Arch

Launching Chromium:
```
export async function launchChromium(): Promise<Browser> {
    const environment = getEnvironmentConfigSync();
    const launchOptions = ['--disable-site-isolation-trials'];

    if (environment.HEADLESS) {
        launchOptions.push('--headless=new');
    }

    return chromium.launch({
        headless: false,
        args: launchOptions,
    });
}
```

Launching new window:

```
export async function getBrowserPage(browser: Browser) {

    const options: BrowserContextOptions = {
        recordVideo: {
            dir: testConfig.videosFolder,
        },
    };

    const context = await browser.newContext(options);
    context.setDefaultTimeout(testConfig.DEFAULT_TIMEOUT);
    await context.grantPermissions(['clipboard-read', 'clipboard-write']);
    return context.newPage();
}
```

Parts of video is grey:
![Image](https://github.com/user-attachments/assets/c318f57a-cdf0-4b40-b781-e4f0c8404f9e)

**Comment by alescinskis** [comment]
> Since using new headless I am able to reproduce this issue not in full screen mode. [@yury-s](https://github.com/yury-s) Please reconsider reopening or if needed I can report as a separate issue.
I'm having the same issue, images in trace's timeline missing same bottom part as the grey part in the video.
