### ISSUE TITLE
[Http_2 Protocal error]: 

### ISSUE THREAD

**Issue by LuckySearchingForSmile** [microsoft/playwright#31240]
### Version

1.42.1

### Steps to reproduce

I'm trying to execute the below script in my local as it working expected and when i tried to execute in azure pipeline with Headless mode in chromium browser as it is failing and throwing an error like **Error: page.goto: net::ERR_HTTP2_PROTOCOL_ERROR** at https://www.costco.com/

Note: tests are running fine with the Firefox and webkit browser 

code snippet:
const { test, expect } = require('@playwright/test');

test.describe('Base Test Demo', () => {
    test('@smoke sing in to castco Page', async ({ page }) => {
        await page.goto("https://www.costco.com/");
        await page.locator("//a[@id='header_sign_in']").click();
        await page.locator("//input[@id='signInName']").fill("xxxx@gmail.com");
        await page.locator("//input[@id='password']").fill("xxxxx@345");
        await page.locator("//button[@id='next']").click();
    });
});

### Expected behavior

I should be able to run the tests without any issue in chromium browser

### Actual behavior

azure pipeline with Headless mode in chromium browser as it is failing and throwing an error like **Error: page.goto: net::ERR_HTTP2_PROTOCOL_ERROR**

### Additional context

I have tried with disabling the http and user agent options but i don't see issue resolved

  args: ['--disable-http2'],
['user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.141 Safari/537.36"']

### Environment

```shell
ubuntu-latest
node 22.1.0 x64
"@playwright/test": "^1.42.1"
```

**Comment by yury-s** [comment]
Can you confirm if it happens only in headless Chromium?

**Comment by LuckySearchingForSmile** [comment]
@yury-s My bad this happing while running in chrome in pipeline. Neither Headed or headless is not working. But other browser working fine.

**Comment by yury-s** [comment]
Filed https://issues.chromium.org/u/1/issues/346565332 upstream

**Comment by yury-s** [comment]
> @yury-s My bad this happing while running in chrome in pipeline. Neither Headed or headless is not working.

Does pass locally for you?

**Comment by LuckySearchingForSmile** [comment]
Yes it is

**Comment by LuckySearchingForSmile** [comment]
> > @yury-s My bad this happing while running in chrome in pipeline. Neither Headed or headless is not working.
> 
> Does pass locally for you?

yes it is

**Comment by yury-s** [comment]
This is odd, could be some combination of bot detection on the servers and network configuration in the pipeline. We cannot affect this is on our end, let's see if there are interesting findings in the upstream report.

**Comment by yury-s** [comment]
So it seems that both costco.com and adidas.com use Akamai CDN and their [WAF](https://www.akamai.com/glossary/what-is-a-waf) kicks in resulting in such errors. You can try manually setting headers to mimic headed chromium more closely. Closing this report as for testing we recommend using trusted sites or disable the protection in the testing environment.

**Comment by LuckySearchingForSmile** [comment]
> So it seems that both costco.com and adidas.com use Akamai CDN and their [WAF](https://www.akamai.com/glossary/what-is-a-waf) kicks in resulting in such errors. You can try manually setting headers to mimic headed chromium more closely. Closing this report as for testing we recommend using trusted sites or disable the protection in the testing environment.

So here, Do I need provide any any proxy here or any other solution ?

**Comment by yury-s** [comment]
Bypassing bot protection is outside of Playwright scope. You need to consult other resources (related to scraping) for that.

**Comment by LuckySearchingForSmile** [comment]
> Bypassing bot protection is outside of Playwright scope. You need to consult other resources (related to scraping) for that.

Thank you @yury-s  for Help.

**Comment by DanielStoica85** [comment]
> > Bypassing bot protection is outside of Playwright scope. You need to consult other resources (related to scraping) for that.
> 
> Thank you @yury-s for Help.

Were you able to find a solution?
