### ISSUE TITLE
Does Playwright support Opera browser?

### ISSUE THREAD

**Issue by DzmitrySatsishur** [microsoft/playwright#31253]
I am using Playwright (1.44.0) framework for web testing. 
Does this framework support Opera browser?
I have tried using the latest Opera browser version (110.0.5130.66) at the moment (also tried Opera developer 125.0.6420.3)  and several older versions , but it doesn't seem to be working with Playwright.

```
Browser = await Playwright.Chromium.LaunchAsync(
    new BrowserTypeLaunchOptions 
    {
        Args = new[] { "--start-maximized" },
        Headless = false,
        ExecutablePath = "C:\\Users\\{Username}\\AppData\\Local\\Programs\\Opera\\opera.exe"
    });

var contextOptions = new BrowserNewContextOptions { ViewportSize = ViewportSize.NoViewport };
var browserContext = await Browser.NewContextAsync(contextOptions);

BrowserPage = await browserContext.NewPageAsync();
BrowserPage.SetDefaultTimeout(3000);

await BrowserPage.GotoAsync(TestsConstants.TestWebsiteUrl);
```

"ExecutablePath" parameter works correctly for Chrome and MS Edge browsers. 
"Browser" object will be null in this code above and nothing happens. If I add "IgnoreAllDefaultArgs" parameter  with "true" value to "BrowserTypeLaunchOptions"  then Opera browser will be launched, but "Browser" object still will be null.
The same thing happens if I call "LaunchPersistentContextAsync()" method instead "LaunchAsync()" method for "Chromium" object.

**Comment by yury-s** [comment]
Playwright does not officially support Opera browser (in addition to open source Chromium, we test with [MS Edge and Google Chrome](https://playwright.dev/docs/browsers#google-chrome--microsoft-edge)). In theory it should work with any Chromium-based browser as long as provides the same CDP and remote debugging APIs as original Chromium.

It [looks like](https://github.com/microsoft/playwright/issues/21812#issuecomment-1477430138) Opera's remote debugging protocol diverged from Chromium. You can address the question to Opera maintainers.

**Comment by glebbovski** [comment]
Hello, @yury-s 

Could you please tell me what the current official status of Opera browser support in Playwright is?

We want to implement testing in Opera for our project. At the moment, the only information available online is from discussions dating back to 2024 (and earlier), where the integration is described as unstable or unofficial (by specifying the `executablePath` for Chromium).

Has anything changed in this regard recently? Are there any built-in mechanisms or recommendations for reliably running tests in Opera?

Thanks in advance for your reply!
