### ISSUE TITLE
[Bug]: Codegen freezes 

### ISSUE THREAD

**Issue by Shaun-Regan** [microsoft/playwright#31254]
### Version

1.44.1

### Steps to reproduce

Start codegen from the vs code extension or via a terminal window and browser freezes in under a min and unable to complete recording.  Tried on two different machine, one machine had a complete fresh install of NPM, VScode and playwright (Only has the playwright extension on this machine) and same issue as my normal work laptop codegen browser freezes.

When the codegen browser freezes the laptop fan is working overtime even though the cpu is under 50% and memory usage holding steady at around 60%.

### Expected behavior

Used codegen tool in the past no issue. really useful tool that now is unusable as unable to finish recording a test

### Actual behavior

Start codegen from the vs code extension or via a terminal window and browser freezes and unable to complete recording.  Tried on two different machine, one machine had a complete fresh install of NPM, VScode and playwright (Only has the playwright extension on this machine) and same issue as my normal work laptop codegen browser freezes.

When the codegen browser freezes the laptop fan is working overtime even though the cpu is under 50% and memory usage holding steady at around 60%.

### Additional context

Start codegen from the vs code extension or via a terminal window and browsers freezes and unable to complete recording.  Tried on two different machine, one machine had a complete fresh install of NPM, VScode and playwright (Only has the playwright extension on this machine) and same issue as my normal work laptop codegen browser freezes.

When the codegen browser freezes the laptop fan is working overtime even though the cpu is under 50% and memory usage holding steady at around 60%.

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 5.79 GB / 15.61 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.90.0 - C:\Users\shaun.regan\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.44.1 => 1.44.1

PS C:\Dev\Access Applause\Automation> npx envinfo --preset playwright
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
   
  System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 5.79 GB / 15.61 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.90.0 - C:\Users\shaun.regan\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.44.1 => 1.44.1
```

**Comment by yury-s** [comment]
Can you describe exact steps you take, so that we can try to reproduce it?

**Comment by Shaun-Regan** [comment]
I've not been able to replicate on your simple tasks website, the codegen install I have works fine and I can use all the tooling as per the generating tests content on your site.  The issue is codegen is freezing on our more complex app, in less than a minute, when attempting to use the codegen tools on something more complex (Iframes, modals, searches) like our app.  The only rep steps I have involve using codegen on our app.  What further steps can be taken investigate without access to our app?  thanks

**Comment by Shaun-Regan** [comment]
Hi Yury

In addition to my reply via GitHub, I've now got permission to give a named individual access to a test copy of our app.  I could then provide replication steps for you to attempt to use the codegen tools on our app to replicate the issue we're experiencing.  I need confirmation of a direct email address to send username, password and URL, plus the rep steps as these would need to be kept off of the public domain bug record.  Also happy to do a teams call to demonstrate the issue/replication steps on our app if that helps.

Thanks

Shaun

From: Yury Semikhatsky ***@***.***>
Sent: Tuesday, June 11, 2024 7:13 PM
To: microsoft/playwright ***@***.***>
Cc: Shaun Regan ***@***.***>; Author ***@***.***>
Subject: #External# Re: [microsoft/playwright] [Bug]: Codegen freezes (Issue #31254)


Can you describe exact steps you take, so that we can try to reproduce it?

-

**Comment by yury-s** [comment]
@Shaun-Regan you can send the instructions to the email in GitHub profile. We don't do teams calls, sorry.

**Comment by Shaun-Regan** [comment]
Hi Yury.  I've sent an email to your profile email address.  Once I get a reply to that email I can send over account details and rep steps to that account.  Thanks a lot.

**Comment by yury-s** [comment]
I replied to your email. 

> The only rep steps I have involve using codegen on our app. What further steps can be taken to investigate without access to our app?

I'll try to reproduce the issue once you share the credentials, but if there is nothing obvious it's very likely we'll need you to extract a minimal reproduction from your app to work on this problem.

**Comment by Shaun-Regan** [comment]
Hi Yury

I've sent over credentials and rep steps to your email.  Thanks

**Comment by yury-s** [comment]
@Shaun-Regan we were able to reproduce the problem, thanks.
