### ISSUE TITLE
[Bug]: Wrong PDF Paper Sizes Calculation

### ISSUE THREAD

**Issue by raubv0gel** [microsoft/playwright#31263]
### Version

1.44.0

### Steps to reproduce

A0 to A6 page sizes are provided by bad roundings to inch in [https://github.com/microsoft/playwright/blob/384eed65eaccc0267952294b04219ff2f3dc8b3d/packages/playwright-core/src/server/chromium/crPdf.ts#L23](https://github.com/microsoft/playwright/blob/384eed65eaccc0267952294b04219ff2f3dc8b3d/packages/playwright-core/src/server/chromium/crPdf.ts#L23) and maybe bad calculations in [https://github.com/microsoft/playwright/blob/384eed65eaccc0267952294b04219ff2f3dc8b3d/packages/playwright-core/src/server/chromium/crPdf.ts#L44](https://github.com/microsoft/playwright/blob/384eed65eaccc0267952294b04219ff2f3dc8b3d/packages/playwright-core/src/server/chromium/crPdf.ts#L44)

E. g. for A4 it results to
![grafik](https://github.com/microsoft/playwright/assets/9824146/8288ce40-cc93-4805-8289-48eb9f7e5e7e)

### Expected behavior

Exact PDF page sizes for A0 to A6. E. g. 210 mm x 297 mm for A4.

### Actual behavior

Badly rounded PDF page sizes for A0 to A6 resulting inaccurate page sizes. E. g. 210,2 mm x 297,3 mm for A4.

### Additional context

Workaround with better approximations (using CSS pixel, because they are not converted by `convertPrintParameterToInches()`:
```c#
/// <summary>
/// Fixes DIN format strings like A4.
/// Because of wrong calculations and inch size in https://github.com/microsoft/playwright/blob/384eed65eaccc0267952294b04219ff2f3dc8b3d/packages/playwright-core/src/server/chromium/crPdf.ts
/// for A0, A1, …, we need to fix it by mapping to CSS pixel (96 PPI).
/// </summary>
/// <param name="pagePdfOptions"></param>
private static void FixFormat(PagePdfOptions pagePdfOptions)
{
    switch (pagePdfOptions.Format)
    {
        case "A0":
            pagePdfOptions.Format = null;
            pagePdfOptions.Width = "3178px";
            pagePdfOptions.Height = "4493px";
            break;
        case "A1":
            pagePdfOptions.Format = null;
            pagePdfOptions.Width = "2245px";
            pagePdfOptions.Height = "3178px";
            break;
        case "A2":
            pagePdfOptions.Format = null;
            pagePdfOptions.Width = "1587px";
            pagePdfOptions.Height = "2245px";
            break;
        case "A3":
            pagePdfOptions.Format = null;
            pagePdfOptions.Width = "1122px";
            pagePdfOptions.Height = "1587px";
            break;
        case "A4":
            pagePdfOptions.Format = null;
            pagePdfOptions.Width = "793px";
            pagePdfOptions.Height = "1122px";
            break;
        case "A5":
            pagePdfOptions.Format = null;
            pagePdfOptions.Width = "559px";
            pagePdfOptions.Height = "793px";
            break;
        case "A6":
            pagePdfOptions.Format = null;
            pagePdfOptions.Width = "397px";
            pagePdfOptions.Height = "560px";
            break;
    }
}
``` 

### Environment

```shell
Windows 11 x64
.NET 8, C#
Microsoft.Playwright 1.44.0
Using Chromium in Playwright
```

**Comment by yury-s** [comment]
Looks like e.g. A4 size may have slightly different dimensions in inches depending on the source. Ours currently hardcoded to 8.27 x 11.7 but other options are possible to. I don't think we can satisfy all, so your approach is the way to go if you need precise dimensions.

**Comment by raubv0gel** [comment]
@yury-s, according to [Overview of ISO paper sizes](https://w.wiki/3oHY) the inch values are rounded values. I guess, the A formates are defined in mm, not in inch. Therefore rounding to more decimal places is a way to go. E. g. round 210 mm to 8.2677 inch (instead of 8.27 inch).

Or do the Playwright webbrowser accept mm instead of inches, too?

**Comment by yury-s** [comment]
According to https://playwright.dev/python/docs/api/class-page#page-pdf:

<img width="187" alt="image" src="https://github.com/microsoft/playwright/assets/9798949/e0eca4ec-ac06-495c-bded-3b5ad7710216">

**Comment by raubv0gel** [comment]
But, it’s internally always converted to inch: [(https://github.com/microsoft/playwright/blob/384eed65eaccc0267952294b04219ff2f3dc8b3d/packages/playwright-core/src/server/chromium/crPdf.ts#L44)](https://github.com/microsoft/playwright/blob/384eed65eaccc0267952294b04219ff2f3dc8b3d/packages/playwright-core/src/server/chromium/crPdf.ts#L44)
