### ISSUE TITLE
E2E are failing in GH Actions after upgrading to Playwright version 1.44.1 but they are passing in my local using 1.44.1

### ISSUE THREAD

**Issue by Iiqra** [microsoft/playwright#31276]
### Please do not submit this issue.

- [ ] I understand

**Comment by Iiqra** [comment]
<img width="1196" alt="GH Actions-1" src="https://github.com/microsoft/playwright/assets/14182666/82143874-2537-4b33-a5ea-b07ffe06d517">
<img width="950" alt="package json" src="https://github.com/microsoft/playwright/assets/14182666/68aef48f-0986-4216-bd28-6a257c192a68">
<img width="685" alt="yaml-file" src="https://github.com/microsoft/playwright/assets/14182666/d3da656a-6c52-4b00-8fba-868fb23a5995">

**Comment by yury-s** [comment]
Make sure you run on [supported linux](https://playwright.dev/docs/intro#system-requirements) distribution and install required [system dependencies](https://playwright.dev/docs/browsers#install-system-dependencies).

This doesn't sound like a bug or feature request, please use our [community resources](https://playwright.dev/community/welcome) for general questions. If you think this is a bug in Playwright, please open a new issue and follow the bug template.
