### ISSUE TITLE
[Bug]: Minor test name displaying issue in HTML report

### ISSUE THREAD

**Issue by AdamOakman** [microsoft/playwright#31287]
### Version

1.43.1

### Steps to reproduce

Using empty test.describe blocks for additional test seperation within the same suite like below:
```ts
test.describe('Example suite', { tag: ['@test1', '@test2', '@test3', '@test4'] }, () => {
    test.describe(() => {
        test('Do something nice', { tag: ['@test5'] }, async ({ page }): Promise<void> => {
            //...
        });
    });
});
```

causes minor issue in displaying full test name in HTML report:
![image](https://github.com/microsoft/playwright/assets/43219983/45c040f2-dbbf-49f7-89c4-b0d520af3c02)

### Expected behavior

There is no additional ">" char in reports for each **empty** test.describe block added

### Actual behavior

![image](https://github.com/microsoft/playwright/assets/43219983/e388d08a-8cdd-4062-8aba-3157363e357c)

### Environment

```shell
Playwright 1.43.1
```

**Comment by yury-s** [comment]
This is fixed on tip of tree by https://github.com/microsoft/playwright/pull/30621 and will be released in 1.45
