### ISSUE TITLE
[Bug]: Keyboard events should refresh between tests

### ISSUE THREAD

**Issue by callumquirky** [microsoft/playwright#31296]
### Version

1.37.1

### Steps to reproduce

1. Have a spec file featuring suite of tests.
1. Write one test that presses "ctrl" down. (page.keyboard.down("Control")
2. Assert that the expected behaviour happens with this test and passes successfully
3. Write a test that follows the previous test that does an action such as clicking to navigate to a page in the app (no CTRL specified in this test)
4. Find a new tab is opened to the desired location instead of navigating within the same tab, presumably as a result of the "ctrl" event from the previous test still being held down

### Expected behavior

I expect keyboard events to be "reset" between tests as each test should be an individual instance.

### Actual behavior

Pressing "ctrl" down on one test results in it still being held down in the next test in the suite. Resulting in needing to explicitly press ctrl up

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900H
    Memory: 11.59 GB / 31.64 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.89.1
```

**Comment by yury-s** [comment]
Do you reuse a page between tests? Please share a reproduction that we could run locally.

I cannot reproduce it with this code:

```js
import { test, expect, type Page } from '@playwright/test';

test.describe.configure({ mode: 'serial' });

test('test one', async ({ page }) => {
  await page.goto('https://example.com');
  await page.keyboard.down('Meta');
});

test('test', async ({ page }) => {
  await page.goto('https://example.com');
  // await page.keyboard.down('Meta');
  await page.on('console', msg => console.log('\n\nPAGE LOG:', msg.text(), '\n\n'));
  await page.evaluate(() => {
    document.body.addEventListener('click', e => {
      console.log('click', e.getModifierState('Meta'));
    });
  });
  await page.locator('h1').click();
});
```

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
