### ISSUE TITLE
[Bug]: UI Mode doesn't show stderr or stdout of webServers

### ISSUE THREAD

**Issue by karlhorky** [microsoft/playwright#31300]
### Version

1.44.1

### Steps to reproduce

1. Configure `webServer[0].stdout` to be `'pipe'`
2. Use either `throw new Error('abc')` and `console.log('def')` in server files ran by `webServer` in `playwright.config.ts`
3. Observe that there is no feedback in either the UI or in the terminal that anything has gone wrong, but all tests are missing ("No tests", see screenshot below)

![Screenshot 2024-06-13 at 20 18 00](https://github.com/microsoft/playwright/assets/1935696/d71dee2e-264c-48a4-afeb-ee8a732b8c0e)

Terminal:

```bash
➜  repro-playwright-ui-mode-missing-stderr-stdout git:(main) ✗ pnpm playwright test --ui
(nothing shown here, no stderr or stdout)
```

### Reproduction Repo

Reproduction: https://github.com/karlhorky/repro-playwright-ui-mode-missing-stderr-stdout

Run `pnpm install` and `pnpm test` to see the behavior.

### Expected behavior

1. `stderr` and `stdout` are shown in the terminal
2. An error message (maybe a modal overlay?) is displayed in the UI

### Actual behavior

No observable errors anywhere (unless you start non-UI mode)

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 92.28 MB / 16.00 GB
  Binaries:
    Node: 20.13.1 - /opt/homebrew/bin/node
    npm: 10.5.2 - /opt/homebrew/bin/npm
    pnpm: 9.3.0 - /opt/homebrew/bin/pnpm
    bun: 1.1.4 - /opt/homebrew/bin/bun
  IDEs:
    VSCode: 1.90.1 - /opt/homebrew/bin/code
  Languages:
    Bash: 5.2.0 - /opt/homebrew/bin/bash
  npmPackages:
    @playwright/test: ^1.44.1 => 1.44.1
```

**Comment by dlmr** [comment]
I still see this issue on **v1.46** in my project and the same goes for the reproduction repo above. Is there something specific that needs to be done to enable WebServer output in UI mode now @pavelfeldman?

**Comment by karlhorky** [comment]
I am also experiencing the same thing with `playwright@1.46.0` - no reporting, either in the UI or in the terminal, when the server crashes:

![Screenshot 2024-08-09 at 13 12 13](https://github.com/user-attachments/assets/3079baa1-db06-4e2c-934d-aafaa6503676)


```bash
$ yarn playwright test --ui
yarn run v1.22.22
$ /Users/k/p/project/node_modules/.bin/playwright test --ui
^C
$
```

`playwright.config.ts`

```ts
  webServer: [
    {
      command: 'yarn start-server',
      port: 3000,
      stdout: 'pipe',
      stderr: 'pipe',
    },
    {
      command: 'yarn start-api',
      port: 3010,
      stdout: 'pipe',
      stderr: 'pipe',
    },
  ],
```

@pavelfeldman can we reopen this issue?

**Comment by karlhorky** [comment]
Oh wait, I think I found it - it's a bit hidden, under this "Toggle output - ^`" button:

![Screenshot 2024-08-09 at 13 19 45](https://github.com/user-attachments/assets/95e3a06f-1499-455c-94f6-1b720ee5a4f9)

**Comment by karlhorky** [comment]
@pavelfeldman @dgozman since this is not very discoverable, what do you think about automatically switching to this panel if there is an error?

I can open a new issue if that is desired.

**Comment by dlmr** [comment]
Ah, that was quite hidden indeed.

Should it not also be printed to the console of the running process when using `pipe` however? Similar to what you get when running without ui mode.

| UI Mode | Not UI Mode |
| - | - |
| <img width="536" alt="image" src="https://github.com/user-attachments/assets/288910a9-5d79-4572-9dd8-88cf00798bbb"> | <img width="942" alt="image" src="https://github.com/user-attachments/assets/19c4750e-cf21-424c-b804-7fba75ad7e39"> |

**Comment by karlhorky** [comment]
@dlmr yeah that sounds good to me too - could you open a new issue for that?

**Comment by dlmr** [comment]
@karlhorky I will give @pavelfeldman a chance to look at this conversation and potentially reopen the issue as I think it still is correct. If preferred let's open a new issue 👍

**Comment by clepet** [comment]
I am having the same issue, but I don't even see output in that hidden "Toggle output" view.
In the terminal neither. I only see the UI with "Loading ..." in the test list for ~ 1 minute until the server started and the tests get shown.
When I start the same npm script without `ui: true` the webserver output gets printed into the terminal.

I am using `@playwright/test@1.44.1` and starting playwright via `nx@17.2.8`.

**Comment by karlhorky** [comment]
@clepet you're using an old version, check the messages above for the version where it was released.

**Comment by clepet** [comment]
@karlhorky my bad, with the currently latest version `1.46.1` I can see the web server outputs in the "Toggle output" view just like the others.

**Comment by karlhorky** [comment]
> @pavelfeldman @dgozman since this is not very discoverable, what do you think about automatically switching to this panel if there is an error?
> 
> I can open a new issue if that is desired.

I opened a new issue for automatically switching to the Output tab:

- https://github.com/microsoft/playwright/issues/32368
