### ISSUE TITLE
[Bug] [Reproducable]: File upload (multipart) not working when routing is enabled

### ISSUE THREAD

**Issue by younes-zeboudj** [microsoft/playwright#31310]
### Version

1.41.2

### Steps to reproduce

Use this code:

```
const playwright = require("playwright");

(async () => {
    const browser= await playwright.chromium.launch({headless:false})
    const context = await browser.newContext()
    const page = await context.newPage()
    await page.route("**/*", route =>  route.continue())
    await page.goto("https://png2jpg.com/")
})();
```

File upaload doesn't work. Comment the routing instruction, file upload works fine.

### Expected behavior

I expect file upload to work with and without routing.

### Actual behavior

File upload (maybe all multipart requests) doesn't work if routing is enabled.

### Environment

```shell
Tested on Windows 11 & Ubuntu.
```

**Comment by yury-s** [comment]
It seems to be fixed in tip-of-tree, can you confirm that it doesn't reproduce with `npm i @playwright/test@next` ?

**Comment by younes-zeboudj** [comment]
Indeed, it is fixed, thanks!
