### ISSUE TITLE
[Bug]: Trying to silently download files using the provided links for Desktop app but facing issues

### ISSUE THREAD

**Issue by ahadghouri** [microsoft/playwright#31318]
### Version

1.44.1

### Code
 

        public async downloadFile(fileUrl: string, fileName : string = "", moveToPermanentLocation : boolean): Promise<string> {
        return new Promise(async (resolve, reject) => {

            let localFilePath : string = "";

            await Driver.forkNewBrowserInstance();
            await Driver.setContent(`<a href="${fileUrl}">download</a>`);
            let filePath = await Driver.downloadFile("a");
            if (moveToPermanentLocation){
                localFilePath = FileService.joinPath([Helper.getDownloadsPath(),fileName]);
                await FileService.copyFile(filePath, localFilePath);
            }            
            else{
                localFilePath = filePath;
            }
            await Driver.quitNewBrowserInstance();
            return resolve(localFilePath);
        });
    }

    static async downloadFile(downloadLocator : string) : Promise<string> {        
        const [ download ] = await Promise.all([
           this.getPage().waitForEvent('download'),
           this.getPage().click(downloadLocator)
        ]);
    
       return await download.path();       
    }

### Expected behavior

I'm calling downloadFile function in a loop so that I can download multiple files on a specified local directory. I expect all the files to be downloaded on the given path using DownloadFile function without confirming the directory in which my file is getting saved.

### Actual behavior

It is working perfectly for my Web app, however, when I'm using the same function to test my Desktop version of the same app, it is getting stuck inside the Promise of Driver.downloadFile( ) and displaying the dialog box which confirms the directory in which our file is getting saved, eventually, getting timed out. 
![Screenshot 2024-06-14 181813](https://github.com/microsoft/playwright/assets/76509605/25d700fc-7600-46a8-ad2a-2055396b06c2)

### Additional context

I've tried to save media using fs library for the Desktop app but I'm facing NET ABORTED error. Would appreciate someone looking into this!

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (28) x64 Intel(R) Core(TM) i7-14700K
    Memory: 19.63 GB / 31.77 GB
  Binaries:
    Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.90.0
```

**Comment by yury-s** [comment]
We need to be able to reproduce the problem to make this report actionable. Please share a full minimal reproducible example which we could run locally.

> It is working perfectly for my Web app, however, when I'm using the same function to test my Desktop version of the same app, it is getting stuck ...

What do you mean by "Desktop version", is it an Electron App?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
