### ISSUE TITLE
[Bug]: Trace Viewer in VSCode is not updated after multiple tests complete

### ISSUE THREAD

**Issue by ruifigueira** [microsoft/playwright#31314]
### Version

1.44.1

### Steps to reproduce

- Create a playwright test with:
```bash
npm init playwright@latest --yes -- --quiet --browser=chromium
```
- Open it in VSCode
- Ensure **Show trace viewer** is checked
- In **Test Explorer** run `example.spec.ts` (it's important that it the two nested tests run, as the error only occurs when multiple tests are launched at the same time)
- In trace viewer, open the developer tools
- Check **Console**

### Expected behavior

I should not get any errors there

### Actual behavior

It starts throwing these errors non-srop:

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at sw.bundle.js:3:69565
    at async ua.entryNames (sw.bundle.js:3:69735)
    at async Kr.load (sw.bundle.js:3:6248)
    at async ha (sw.bundle.js:3:70782)
    at async pa (sw.bundle.js:3:71876)
````

![image](https://github.com/microsoft/playwright/assets/1374559/9c0056d8-ffc1-4b69-ae7c-01fe003c440f)

- Those errors only stop when another test item is selected in the tree

You may need to relaunch tests a few times to reproduce, because it's a stochastic error. In my case at least, it happens almost every time (maybe 9 in 10).

### Additional context

Looking into **Network**, it's still trying to get the live version of the trace, that is, the `.json` trace file instead of the zipped one:

![image](https://github.com/microsoft/playwright/assets/1374559/c8118d67-e115-416d-b926-bf7322c6aabd)

Apparently VSCode is not notifying trace viewer that the test is completed and it should show the zipped file instead.

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 8.28 GB / 31.74 GB
  Binaries:
    Node: 20.12.2 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    Yarn: 1.22.22 - ~\scoop\apps\nvm\current\nodejs\nodejs\yarn.CMD
    npm: 10.5.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
    pnpm: 8.15.4 - ~\AppData\Local\pnpm\pnpm.EXE
  IDEs:
    VSCode: 1.90.0 - C:\Users\rui.figueira\scoop\apps\vscode\current\bin\code.CMD
  npmPackages:
    @playwright/test: file:../playwright/packages/playwright-test => 1.45.0-next
```

**Comment by ruifigueira** [comment]
I found the problem: trace viewer was not updated once its running test completes. I left a patch in https://github.com/microsoft/playwright-vscode/pull/483 (

**Comment by yury-s** [comment]
Is there a user-visible problem except for the error messages in the console?

**Comment by ruifigueira** [comment]
It keeps the last version of the live trace, which sometimes is not the final trace
