### ISSUE TITLE
[Bug]: STOP button does not work does

### ISSUE THREAD

**Issue by Ozge-Buyuktorun** [microsoft/playwright#31313]
### Version

v1.1.7

### Steps to reproduce

When using the addon in VS code, we can start the tests but we cannot stop them, they freeze. The stop process does not work.

### Expected behavior

I expect to see to stop after clicking the stop button.

### Actual behavior

Stop button is not working completely.

### Additional context

VS Code version 
![image](https://github.com/microsoft/playwright/assets/74399824/0a7b3134-6ad6-42f6-975e-3ee3284d905c)

### Environment

```shell
System Windows 10
node --version: v22.2.0
npm -- version: 10.7.0
```

**Comment by NikkTod** [comment]
Same problem also for me, but I was having two playwright.config files and selection only one seems to fix this stopping issue.

**Comment by yury-s** [comment]
Can you provide exact reproduction steps along with the project where it happens, so that we could repeat it locally?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
