### ISSUE TITLE
[Feature]: add `expect(page).toBeResponsive()` to `PageAssertions`

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/playwright#31320]
### 🚀 Feature Request

It'd be nice if there was a way to assert that a page is responsive, i.e, not frozen.

### Example

```ts
import { title } from '@/app/matrix';
import { expect, test } from '@playwright/test';

test('that the page is responsive after starting to process complex input', async ({ page }) => {
  const input_textarea = page.getByTitle(title);
  await page.goto('http://localhost:3000/');
  await input_textarea.fill('[[1,10,7,10,14,20],[2,12,6,10,1,10],[3,5,6,7,4,2],[4,3,1,1,2,10]]');
  expect(page).toBeResponsive();
});
```

### Motivation

There can be times in production where some user action causes a page to freeze or be unresponsive.

It'd be nice if we could reproduce that behavior in a testing environment, and add assertions to make sure our code doesn't cause that behavior.

**Comment by hamirmahal** [comment]
This could maybe go under https://playwright.dev/docs/api/class-pageassertions.

**Comment by hamirmahal** [comment]
I tried

```ts
import { title } from '@/app/matrix';
import { expect, test } from '@playwright/test';

test('the page is responsive after starting to process large input', async ({ page }) => {
  const input_textarea = page.getByTitle(title);
  await page.goto('http://localhost:3000/');
  await input_textarea.waitFor();
  await input_textarea.fill('[[1,10,7,10,14,20],[2,12,6,10,1,10],[3,5,6,7,4,2],[4,3,1,1,2,10],[3,40,5,20,20,10]]');
  await expect(input_textarea).toBeEditable();
});
```

But this test passes, whereas if I tried doing this in production the page would hang for a while, and freeze for even longer for certain text input.

**Comment by yury-s** [comment]
Can you just simulate the same actions that you do manually to check if the page is responsive and measure that they take reasonable time? E.g. try to [fill](https://playwright.dev/docs/api/class-locator#locator-fill) another text field on the page and check that it doesn't time out, would that work?

**Comment by hamirmahal** [comment]
Hmm... That doesn't seem to work.

```ts
import { title } from '@/app/matrix';
import { expect, test } from '@playwright/test';

test('the page is responsive after starting to process large input', async ({ page }) => {
  const input_textarea = page.getByTitle(title);
  await page.goto('http://localhost:3000/');
  await input_textarea.waitFor();
  await input_textarea.fill('[[8, 3, 1, 9, 5, 4, 6, 0, 2, 7], [4, 2, 8, 6, 0, 7, 3, 1, 9, 5], [7, 6, 0, 2, 8, 1, 5, 9, 4, 3], [1, 5, 9, 3, 7, 6, 8, 2, 0, 4], [6, 0, 4, 5, 3, 9, 7, 8, 1, 2], [9, 1, 5, 4, 2, 0, 3, 7, 6, 8], [2, 7, 3, 8, 4, 5, 9, 6, 0, 1], [3, 9, 2, 0, 1, 8, 4, 5, 7, 6], [5, 4, 6, 7, 9, 2, 1, 3, 8, 0], [0, 8, 7, 1, 6, 3, 2, 4, 5, 9]]');
  await expect(input_textarea).toBeEditable();
  await input_textarea.fill('[[0]]');
});
```

**Comment by hamirmahal** [comment]
If I enter that input on the page in production, I get this alert from the browser after the page freezes.

![image](https://github.com/microsoft/playwright/assets/43425812/83628c7d-54e2-4af5-b52f-fe39540ec626)

It would be nice if I could assert that this doesn't happen in a test environment.

**Comment by hamirmahal** [comment]
If it helps, [https://max-matrix-path.vercel.app/](https://max-matrix-path.vercel.app/?utm_source=playwright31230) is the page that freezes in production with this input

```
[[8, 3, 1, 9, 5, 4, 6, 0, 2, 7], [4, 2, 8, 6, 0, 7, 3, 1, 9, 5], [7, 6, 0, 2, 8, 1, 5, 9, 4, 3], [1, 5, 9, 3, 7, 6, 8, 2, 0, 4], [6, 0, 4, 5, 3, 9, 7, 8, 1, 2], [9, 1, 5, 4, 2, 0, 3, 7, 6, 8], [2, 7, 3, 8, 4, 5, 9, 6, 0, 1], [3, 9, 2, 0, 1, 8, 4, 5, 7, 6], [5, 4, 6, 7, 9, 2, 1, 3, 8, 0], [0, 8, 7, 1, 6, 3, 2, 4, 5, 9]]
```

**Comment by yury-s** [comment]
> But this test passes, whereas if I tried doing this in production the page would hang for a while, and freeze for even longer for certain text input.

The test seems to be missing ['accept'](https://playwright.dev/docs/api/class-dialog#dialog-accept) call for the dialog (by default the dialogs are [dismissed](https://playwright.dev/docs/api/class-dialog)) without which the app doesn't run the expensive computations. Once I added it, the test times out on the first `fill` method call which is basically due to the page being in the tight loop and unresponsive:

```js
import { expect, test } from '@playwright/test';

test('the page is responsive after starting to process large input', async ({ page }) => {
  await page.goto('https://max-matrix-path.vercel.app/');
  const input_textarea = await page.getByPlaceholder('[[1,0,7,0,0,0],[2,0,6,0,1,0');
  page.on('dialog', async dialog => dialog.accept())
  await input_textarea.fill('[[8, 3, 1, 9, 5, 4, 6, 0, 2, 7], [4, 2, 8, 6, 0, 7, 3, 1, 9, 5], [7, 6, 0, 2, 8, 1, 5, 9, 4, 3], [1, 5, 9, 3, 7, 6, 8, 2, 0, 4], [6, 0, 4, 5, 3, 9, 7, 8, 1, 2], [9, 1, 5, 4, 2, 0, 3, 7, 6, 8], [2, 7, 3, 8, 4, 5, 9, 6, 0, 1], [3, 9, 2, 0, 1, 8, 4, 5, 7, 6], [5, 4, 6, 7, 9, 2, 1, 3, 8, 0], [0, 8, 7, 1, 6, 3, 2, 4, 5, 9]]');
  await expect(input_textarea).toBeEditable();
  await input_textarea.fill('[[0]]');
});
```

In any case, if the page is in a tight loop (which causes the unresponsive dialog), Playwright assertions and actions will also be blocked and should time out. We recommend testing user visible behavior, in this case inability to complete an action/web assertion within allocated time would indicate a problem with the page such as (but not limited to) it being unresponsive. You can also instrument your page and measure performance of an action that is known to be computation heavy (fill in this test).

Closing this request as we recommend using user actions to test that the page is usable from the user's stand point.

**Comment by hamirmahal** [comment]
Thanks for the detailed response.

> You can also instrument your page and measure performance of an action that is known to be computation heavy (fill in this test).

Is there a way to do this within Playwright?
