### ISSUE TITLE
[Feature]: A way to prevent _target blank new pages from even being opened in the first place

### ISSUE THREAD

**Issue by himat** [microsoft/playwright#31322]
### 🚀 Feature Request

If I have a link element on a page with `_target="blank"`, I want to be able to prevent that link from being opened in a new page. 
I instead want to load that future url in the current page instead (effectively disabling the _target blank functionality).

### Doesn't work - popup 
I know I can use the `popup` event
```
page.on('popup', async popup => {
  await popup.waitForLoadState();
  console.log(await popup.title());
  const newUrl = popup.url();
  popup.close();
});
```
but that's not correct, because when that popup event happens, the new page is already opened! so I have to manually close the new page. This is not ideal because even opening a url could cause some mutation somewhere by the page making an API call on open. So I don't want to open the page once in the new tab, and then set the url again in my original page. 

### Doesn't work - router
Even using the `context.route` function doesn't work because I found that even if I do `route.abort()`, a new tab in the browser window has actually already opened! (the new page just won't load since I did .abort() of course)

```
    const onNewPageOpenedOnClick = (route: playwright.Route, request: playwright.Request) => {
      if (request.isNavigationRequest()) {
          const newUrl = request.url();
          console.log("is navigation request")
          console.log("route new url: ", newUrl)
          route.abort()
          return
      }

      route.continue()
    }
    await view.browserView.context().route("**/*", onNewPageOpenedOnClick)
    // <perform click on page>
```

Other issue with this is that I need to listen for the event on the /entire/ context, and so if some other page also is navigating too at the same time, this function would see that new page here too. So if I did this, is there even some way to associate the new `request` with the originating page of the `_target="blank"` at all?

---

I could also manually modify the DOM elements to remove target blank, but I don't think modifying the DOM is a good idea since the page's JS may be depending on that attr existing. 

### Electron comparison 
In electron, you can do this and it will prevent new tabs from being opened
```
const createDefaultNewWindowHandler =
  (browserView: BrowserView) =>
  (
    details: Electron.HandlerDetails,
  ):
    | {
        action: "deny"
      }
    | {
        action: "allow"
        outlivesOpener?: boolean | undefined
        overrideBrowserWindowOptions?: Electron.BrowserWindowConstructorOptions | undefined
      } => {
    if (details.disposition === "foreground-tab") {
      browserView.webContents.loadURL(details.url) // load in the current view! instead of in a new tab
      return { action: "deny" }
    }
    return { action: "allow" }
  }
```

```
    browserView.webContents.setWindowOpenHandler(createDefaultNewWindowHandler(browserView))
```

So I want some equivalent to this in playwright.

### Motivation

This is a common thing that people would want during testing.

**Comment by dgozman** [comment]
@himat I'd recommend to remove all `_target=blank` attributes manually:

```ts
await page.locator('a').evaluateAll(elements => {
  for (const a of elements)
    a.removeAttribute('_target');
});
```

Let me know whether this helps.

**Comment by dgozman** [comment]
Closing as per above. If you still encounter problems, please file a new issue and link to this one.
