### ISSUE TITLE
[Bug]: UI Mode - 1 minute very slow at start of ui mode due to watcher watching excessive files (esp. on windows)

### ISSUE THREAD

**Issue by lukpsaxo** [microsoft/playwright#31337]
### Version

1.44.1

### Steps to reproduce

we have a test directory that encompasses a few packages so each package has node_modules in it.

We start UI mode and there is 1 minute of slowness where the ui is responsive but the test server is not - you click to start a test and nothing happens.

### Expected behavior

UI Mode is fast

### Actual behavior

N/A See additional context

### Additional context

This code:
https://github.com/microsoft/playwright/blob/main/packages/playwright/src/fsWatcher.ts#L55

Does not work in windows, so all node_modules are watched.

When I debug the path seperator is `\\` but the path passed to the function is actually unix style.

Further even if it did work, it watches all the sub directories of node_modules since it forces a path seperator on the end.

Instead of the function, adding `'**/node_modules/**` works and I believe from the docs will work on all platforms.

Secondly... You do not pass the test ignore directories from options into the watcher. This would help us by ignoring some other packages. e.g. We have a backend directory with a nuget folder that is very large.

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 38.38 GB / 63.78 GB
  Binaries:
    Node: 20.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 4.3.0 - c:\npmprefix\yarn.CMD
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.90.1 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  npmPackages:
    playwright: 1.46.0-alpha-2024-06-17 => 1.46.0-alpha-2024-06-17
```

**Comment by lukpsaxo** [comment]
I looked into using the test ignore within the watcher and I couldn't get a nice translation to what chokidar expects from playwright testIgnore, so if that's implemented I think it would have to be a function that then uses the code within projectUtils to work out if playwright expects the path to be ignored, so a bigger change. Let me know if this is something you are interested in supporting but only through a contribution and I can have a go at it.

**Comment by dgozman** [comment]
Thank you for fixing this!

> I looked into using the test ignore within the watcher and I couldn't get a nice translation to what chokidar expects from playwright testIgnore, so if that's implemented I think it would have to be a function that then uses the code within projectUtils to work out if playwright expects the path to be ignored, so a bigger change. Let me know if this is something you are interested in supporting but only through a contribution and I can have a go at it.

This is something we would like to support if possible, unless it turns out to be really hard. If you'd like to contribute, that would be wonderful! In this case, please file a new issue to track it.

**Comment by lukeapage** [comment]
@johnstonphilip windows was not ignoring node modules where as Mac was working. The fix was to use Unix (&mac) separators even on windows.

That being said as I mentioned, playwright is watching all other files so if for instance the root has a massive amount of files in it (excluding node modules) then this issue can occur.

I would verify by changing the playwright root to a folder with just a few test files in - if playwright gets fast then it is likely down to file matching or watching. Are you running the latest version of playwright ?

**Comment by johnstonphilip** [comment]
Apologies for not providing my version. I am on v1.45.3.

Deleting the bulk of my files didn't seem to make a difference so it must be something else.

For what it's worth, I switched to make my playwright tests run inside a docker container (using `--ui-port` and `--ui-host`), and now the UI Mode app loads in a couple seconds, as opposed to a minute+. That's with the same number of files in the project, including several node_modules directories, as it's a monorepo.

Either way, that seems to have resolved it for me. I appreciate your response!
