### ISSUE TITLE
[Bug]: Playwright Java - Element click does not work while running the tests. 

### ISSUE THREAD

**Issue by JaspinderKaur09** [microsoft/playwright#31330]
### Version

1.44.0

### Steps to reproduce

Playwright ignores the click of the element being failed, and moves to next step execution.
The same works fine while debugging. Interestingly, the element highlights as its being hovered upon, but does not click. 

page.locator("button[title='Close'][class='icon-cancel']").click();

### Expected behavior

Element should be clicked

### Actual behavior

Element not being clicked, instead hovered upon while running the tests

### Additional context

- There is only one element in the DOM.

### Environment

```shell
Windows
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
