### ISSUE TITLE
[Docs]: Playwright webkit screenshot configuration

### ISSUE THREAD

**Issue by napsta32** [microsoft/playwright#31345]
### Page(s)

https://playwright.dev/docs/next/browsers#webkit
https://playwright.dev/docs/next/test-snapshots

### Description

Please clarify if webkit can be configured to enable/disable a "retina display emulation".
By default, when taking screenshots using WebKit on a macOS, it takes the screenshots as if it was a retina display (twice as much resolution compared to other browsers). I don't know if this is configurable or if this comes from webkit itself.

**Comment by dgozman** [comment]
@napsta32 Are you using `await expect(page).toHaveScreenshot()` assertion? I believe that this assertion [defaults to non-retina screenshots](https://playwright.dev/docs/api/class-pageassertions#page-assertions-to-have-screenshot-2-option-scale). If that's not the case, we would love to see a repro to debug it.

**Comment by napsta32** [comment]
@dgozman I used this to test snapshots and got the "scaled" screenshots in webkit:

```
import { test, expect } from '@playwright/test';

test('button snapshot', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  const getStartedButton = page.getByText('Get started');
  const screenshot = await getStartedButton.screenshot({
      type: 'png'
  });
  expect(screenshot).toMatchSnapshot();
});
```

To create the project I used `npm init playwright@latest`.
To run the test: `npx playwright test --update-snapshots`

Snapshots generated:

* Chromium: 177× 52
* Firefox: 178 × 52
* WebKit: 354 × 104

System info:

```sh
$ npx envinfo --preset playwright

  System:
    OS: macOS 14.4.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 605.48 MB / 16.00 GB
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
  IDEs:
    VSCode: 1.90.1 - /usr/local/bin/code
  Languages:
    Bash: 5.2.26 - /usr/local/bin/bash
  npmPackages:
    @playwright/test: ^1.44.1 => 1.44.1 
```

**Comment by napsta32** [comment]
Using `toHaveScreenshot` effectively uses a different scale factor:

![image](https://github.com/microsoft/playwright/assets/26403251/93054f66-bb30-40ce-983b-3cc23ea2903f)

**Comment by dgozman** [comment]
@napsta32 Pass the [`scale: 'css'` option](https://playwright.dev/docs/api/class-elementhandle#element-handle-screenshot-option-scale) when taking a screenshot. Or better yet, use `toHaveScreenshot()` assertion instead. This way, you'll always get css-scaled screenshots.

**Comment by napsta32** [comment]
I am a bit confused with the description of `scale: 'device'`:

```
Using "device" option will produce a single pixel per each device pixel, so screenshots of high-dpi devices will be twice as large or even larger.
```

It says that screenshots of "high-dpi devices" will be twice as large. However my macMini is connected to a regular non-retina display. Why would the screenshots be larger then?

I wonder if the `scale: 'css'` will capture browser rendering bugs (that the "device" option is currently capturing). For example, I noticed that Chrome has some bugs related to clipping text if the `div` is just the right size (with `overflow: hidden`) and other browsers don't have that clipping issue. I could try this on my own in any case.

Thanks for the suggestion!

**Comment by dgozman** [comment]
> It says that screenshots of "high-dpi devices" will be twice as large. However my macMini is connected to a regular non-retina display. Why would the screenshots be larger then?

You are probably running with `devices['Desktop Safari']` in your config, and this emulates high-dpi by default by setting `deviceScaleFactor: 2` option.

> I wonder if the `scale: 'css'` will capture browser rendering bugs (that the "device" option is currently capturing). For example, I noticed that Chrome has some bugs related to clipping text if the `div` is just the right size (with `overflow: hidden`) and other browsers don't have that clipping issue. I could try this on my own in any case.

There should be no difference except for the lower-resolution screenshot.

**Comment by dgozman** [comment]
Closing as there is no action item for Playwright here. If you still encounter problems, please file a new issue.
