### ISSUE TITLE
Receiving following error message "AxiosError: Request failed with status code 401" on request

### ISSUE THREAD

**Issue by jcrans13** [microsoft/playwright#31342]
I am using playwright with JavaScript/Typescript
version: 10.8.1

I have 2 methods, 1 in which I am getting the auth token in order to make the next api call
I think I have the syntax wrong somewhere but I have no idea where. I am doing pretty much what I am doing in the previous api call except I am importing parts of an api array (which works fine in other api calls).

`let apiURL = process.env.API_URL;
let token: any;

async get_token(): Promise<void> {
    axios({
      method: 'post',
      url: apiURL + apis.authenticate,
      data: {
        username: 'string',
        password: 'string',
        apiKey: 'string'
      }
    }).then(async function (response) {
      token = response.data.token;
      expect(response.status).toBe(200);
    });
  }

  async cancel_appointment(): Promise<void> {
    axios({
      method: 'put',
      url: apiURL + apis.cancel[0] + accountNumber + apis.cancel[1] + appointmentNumber + apis.cancel[2],
      headers: {
        'Authorization': `Bearer ${token}`
      }
    }).then(async function (response) {
      console.log(response.data);
      console.log(response.status);
      console.log(response.statusText);
      console.log(response.headers);
      console.log(response.config);
      expect(response.status).toBe(200);
    });
  }`

**Error:** AxiosError: Request failed with status code 401

Any help would be greatly appreciated!!

**Comment by dgozman** [comment]
This issue tracker is reserved for bug reports and feature requests.

For anything else, such as questions or getting help, please see:
- [The Playwright documentation](https://playwright.dev/)
- [Our Discord server](https://aka.ms/playwright/discord)
