### ISSUE TITLE
URL redirection issue

### ISSUE THREAD

**Issue by ashwithpoojary98** [microsoft/playwright#31363]
### Please do not submit this issue.

- [X] I understand

**Comment by ashwithpoojary98** [comment]
After entering the normal URL it should redirect to another URL automatically.

**Comment by dgozman** [comment]
This issue tracker is reserved for bug reports and feature requests.

For anything else, such as questions or getting help, please see:
- [The Playwright documentation](https://playwright.dev/)
- [Our Discord server](https://aka.ms/playwright/discord)
