### ISSUE TITLE
Support for Chrome Browser Account Login

### ISSUE THREAD

**Issue by Dolov** [microsoft/playwright#31379]
### 🚀 Feature Request

Hi Playwright team,

I would like to request a feature to support logging into a Chrome browser account directly through Playwright. This feature would be very useful for automating tasks that require a Google account to be signed in.

### Motivation

A method to programmatically sign into a Google account within a Playwright script, similar to how we handle form-based logins.

**Comment by dgozman** [comment]
@Dolov Thank you for the issue! Unfortunately, this is not going to happen. Playwright automates web pages, so everything within the tab, but not the browser UI.
