### ISSUE TITLE
Is it possible to paunch playwright with a specific version of Chromium? The latest version of browser is 126 however the test url works on browser versions 119 and below.

### ISSUE THREAD

**Issue by MahalakshmiSagar** [microsoft/playwright#31378]
### Please do not submit this issue.

- [X] I understand

**Comment by dgozman** [comment]
This issue tracker is reserved for bug reports and feature requests.

For anything else, such as questions or getting help, please see:
- [The Playwright documentation](https://playwright.dev/)
- [Our Discord server](https://aka.ms/playwright/discord)
