### ISSUE TITLE
[Feature]: Copy cUrl in Network tab - UI Mode/Trace report

### ISSUE THREAD

**Issue by Dinh246** [microsoft/playwright#31388]
### 🚀 Feature Request

Hi team,
So after running the test I found that it will be more convenient to be able to copy cUrl of failed API request on  Network tab and send to dev for further investigation just like what I can do on browser's Network tab.
This will save so much time and effort to reproduce, please consider this.
Best regards,
![image](https://github.com/microsoft/playwright/assets/71114633/558c356e-7a81-4bf6-9990-4d40ec520332)

### Example

Just similar to copy cURL on browser's Network tab

### Motivation

It's easy and quick to copy the failed API and send to dev for investigation further.

**Comment by mxschmitt** [comment]
Looks like https://github.com/microsoft/playwright/issues/30082

**Comment by dgozman** [comment]
Closing in favor of #30082.
