### ISSUE TITLE
[Feature]: Playwright masking with configurable zIndex.

### ISSUE THREAD

**Issue by sarthakpant77** [microsoft/playwright#31392]
## Problem Statement
If we have a modal in a website and we need to mask it, we are not able to, as zIndex for the masking part is not configurable.

## Feature Request
Their should be a parameter that can be used to configure the mask zindex, in main playwright config and also individual mask too.

### Example

`expect page.locator().tohaveScreenshot(... , maskIndex:'123')`

This will allow the masking part to set a zIndex to it

### Motivation

In my company while wright some visual test i was not able to use mask. that is the reason i want it to get implemented

**Comment by dgozman** [comment]
Closing as a duplicate of #19002. See [this comment](https://github.com/microsoft/playwright/issues/19002#issuecomment-2038248859) for a solution.
