### ISSUE TITLE
[Feature]: Drag and drop from one page to another page

### ISSUE THREAD

**Issue by RajeshKumarMahto** [microsoft/playwright#31397]
### 🚀 Feature Request

Hi I am trying to do drag and drop from one page to another page it is not working. 

Can anyone help how to perform drag and drop operation from one monitor to another monitor. I have 2 monitor setup and my app opens in both monitors with 2 chrome pages, one in each monitor. Now my action item is I need to perform  drag from one monitor chrome instance window and dropping in another monitor chrome instance window.

There is already a feature an GitHub issue was created but somehow it got closed. 
https://github.com/microsoft/playwright/issues/16247

### Motivation

It's will be a great feature for multi screen automation

**Comment by jpkgithub** [comment]
This is important feature in modern web application. Must need support in Playwright.

**Comment by dgozman** [comment]
I've reopened #16247, so merging this one into it.
