### ISSUE TITLE
cannot open playwright chromium browser in bundle app bulit by pyinstaller

### ISSUE THREAD

**Issue by oungsi2000** [microsoft/playwright#31402]
`Hello`

When I run an app I built with pyinstaller, my playwright chromium browser doesn't work. But when I run python file, it works very normally.

When I ran executable file in content/MacOS, and looked at the console, I couldn't find any traceback or logs related to playwright.

Playwright runs on substhread that inherit Qrunnable from the Pyside6 library, not on the main thread.

Here's the code

from playwright.sync_api import sync_playwright

```
class App():
  def __init__(self) -> None:
    self.playwright = sync_playwright().start()
    self.browser = self.playwright.chromium.launch(headless=False)
    self.context = self.browser.new_context(viewport={"width": 300, "height": 300},)
  
   def stop(self):
          if self.browser:
              self.browser.close()
          if self.playwright:
              self.playwright.stop()
App()
...
```

The following is the pyinstaller build code

pyinstaller --windowed --add-data "/Users/jung-yongjun/Desktop/판매추적기/naver.svg:naver.svg" --noupx --noconfirm App.py

Is it not compatible with pyinstaller itself or is there a problem?
Thanks

```[tasklist]
### Tasks
```

**Comment by dgozman** [comment]
@oungsi2000 Playwright does not support pyinstaller.

**Comment by oungsi2000** [comment]
@dgozman then what tool should i use to build a bundle? does playwright support nuitka?

**Comment by dgozman** [comment]
@oungsi2000 Playwright does not officially support bundling, so we cannot recommend any bundling tool.
