### ISSUE TITLE
[Feature]make automation life more good!

### ISSUE THREAD

**Issue by roughsoft** [microsoft/playwright#3140]
https://gauge.org/2019/08/21/how-taiko-compares-to-other-browser-automation-tools/
@arjun27

**Comment by roughsoft** [comment]
1)should change only when there is a change in functionality. A change in the structure of a web page should not impact a test validating functional correctness.

However, most browser automation tools create tests that are hard to maintain. That’s because they use locators like XPath, ID's, CSS selectors to identify and perform actions on web page elements.

**Comment by roughsoft** [comment]
2)Stacktrace, Screenshot, Highlight element on action, Video recording, Step by step playback, Debug from devtools console, Other options in test runner

**Comment by aslushnikov** [comment]
Thank you @roughsoft! We're constantly thinking and discussing most of the things you mentioned here. We'll see if these ideas will actually shape into a good product story.
