### ISSUE TITLE
Playwright route.fetch: Test ended error

### ISSUE THREAD

**Issue by bageeshlal** [microsoft/playwright#31412]
### Please do not submit this issue.

- [ ] I understand
```[tasklist]
### Tasks
```

**Comment by bageeshlal** [comment]
In my SPA, I am using page.route() to intercept an api request. Ex: /core
The same api is getting called multiple times when I move across the pages and finally, test fails with a message route.fetch: Test ended error.
From the traces, I could understand that when the api is called first time, it is getting fulfilled, but the second time, before it gets fulfilled, test completes. 
I had given an explicit wait for couple of seconds at the end of the test solves the problem, but is there any better solution?

**Comment by mxschmitt** [comment]
You need to add [`await page.unrouteAll({ behavior: 'ignoreErrors' })`](https://playwright.dev/docs/api/class-page#page-unroute-all) at the end of your test or afterEach, then it should not yield to errors anymore.

**Comment by dgozman** [comment]
This issue tracker is reserved for bug reports and feature requests.

For anything else, such as questions or getting help, please see:
- [The Playwright documentation](https://playwright.dev/)
- [Our Discord server](https://aka.ms/playwright/discord)
