### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by monicaswimbird** [microsoft/playwright#31429]
### 🚀 Feature Request

Support to launch and interact with an android apk through playwright framework

### Motivation

We're currently leveraging the Playwright framework for web automation and are looking to expand its capabilities to include mobile automation. While we can interact with mobile browsers, we're exploring methods to interact directly with Android APK files.

**Comment by pavelfeldman** [comment]
There is some experimental support for that https://playwright.dev/docs/api/class-androiddevice, please file more specific requests if you have any.
