### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PushkarajAwad2** [microsoft/playwright#3142]
**Context:**
- Playwright Version: 1.2.1
- Operating System: Windows
- Node version: 10.15.1
- Browser: Chromium

**Code Snippet**

```js
 async handleTestEvent(event) {
        if (event.name === 'test_done' && event.test.errors.length > 0) {
            const snapshotPath = `${this.screenshotPath}/${ event.test.parent.name.replace(/\W/g, '-')}_${event.test.name.replace(/\W/g, '-')}` + '_';
            await this.global.page.screenshot({
                path: !!process.env.device ? `${snapshotPath}_${process.env.device}` + '.jpeg' : snapshotPath + '.jpeg',
                fullPage: true,
                type: "jpeg",
            });
        }
    }
```

**Describe the bug**

To capture screenshot for failed testcases we added custom environment logic  but it is showing blank screenshots.
We have investigated and found, to capture screenshots custom environment is accessing global page instance and we are creating new browser instance for each test case. 

To resolve this we used global browser instance, but whenever test cases are failed for some reason or after finishing execution global browser instance itself is getting closed and other test cases are not running. 

Also How can we capture screenshot of failed testcases for new browser instance.

Can someone help us to resolve this issue.

**Comment by aslushnikov** [comment]
> Also How can we capture screenshot of failed testcases for new browser instance.

@PushkarajAwad2 this will be covered by our upcoming testrunner: please take a look at https://github.com/microsoft/playwright/issues/3552

This exact functionality has just landed:  https://github.com/microsoft/playwright/pull/3556
