### ISSUE TITLE
[Bug]: PDF Preview is not working on webkit

### ISSUE THREAD

**Issue by Ransely-Nigrel** [microsoft/playwright#31430]
### Version

1.42.1

### Steps to reproduce

Run any Test case which requires PDF preview and content validation for webkit browser

### Expected behavior

PDF should be preview on clicking on it

### Actual behavior

PDF is not previewed and blank PDF is displayed for webkit browser

### Additional context

It worked with firefox with below launch options

name: 'firefox',
            use: {
                ...devices['Desktop Firefox'],
                storageState: 'tests/.auth/user.json',
                launchOptions: {
                    firefoxUserPrefs: {
                        "pdfjs.disabled": false,
                    }
                }
            },
            dependencies: ['setup']     

### Environment

```shell
System
OS: Windows 11
Node: version 16
```

**Comment by pavelfeldman** [comment]
PDF preview is not a part of WebContent, rather a Safari plugin. It is outside of scope for Playwright testing.

**Comment by fujii** [comment]
I don't know what ENABLE_PDFJS is. But, GTK and WPE ports enable it.
https://github.com/WebKit/WebKit/blob/3fcd2236523c0c65609407eed1ff48fd0f7e12b9/Source/cmake/OptionsGTK.cmake#L93

**Comment by pavelfeldman** [comment]
> I don't know what ENABLE_PDFJS is. But, GTK and WPE ports enable it.

There isn't much we can test / validate about the pdf viewer.

**Comment by mxschmitt** [comment]
I think we'd much rather prefer that pdfs trigger downloads, like WK/FF are already doing as per https://github.com/microsoft/playwright/issues/7822.

**Comment by Ransely-Nigrel** [comment]
> I don't know what ENABLE_PDFJS is. But, GTK and WPE ports enable it. https://github.com/WebKit/WebKit/blob/3fcd2236523c0c65609407eed1ff48fd0f7e12b9/Source/cmake/OptionsGTK.cmake#L93

How can we add it in the config for enabling it like we have done for forefox above ?

**Comment by pavelfeldman** [comment]
> How can we add it in the config for enabling in webkit , like we have done for forefox above ?

There is no such config in Playwright.
