### ISSUE TITLE
expect() false positive

### ISSUE THREAD

**Issue by igor-martins-ugowork** [microsoft/playwright#31449]
I have faced instabilities during my tests. For example, I find elements and then make assertions that should fail, but they all pass. I used the same component and made some nonsense assertions:

      const userPateTitle = page.getByTestId(/userPageTitle/);
      await expect(userPateTitle).toHaveText('Utilisateur'); this is ok.
      await expect(userPateTitle).toHaveText('543ut934u932311#$%#'); it should fail, but it pass.
      await expect(userPateTitle).toHaveText('');  it should fail, but it pass.

      const inputByPlaceholder = page.locator('input[placeholder="Rechercher Utilisateur"]');
      await expect(inputByPlaceholder).toHaveCount(1); it is ok.
      await expect(inputByPlaceholder).toBeVisible(); it is ok
      await expect(inputByPlaceholder).toHaveCount(-111); it should fail, but it pass.
      await expect(inputByPlaceholder).toHaveCount(0); it should fail, but it pass.
      await expect(inputByPlaceholder).toHaveCount(4555); it should fail, but it pass.
      await expect(inputByPlaceholder).not.toBeVisible(); it should fail, but it pass.

It doesn't seem reliable when testing components.

_Originally posted by @igor-martins-ugowork in https://github.com/microsoft/playwright/issues/19542#issuecomment-2191869790_

**Comment by mxschmitt** [comment]
I'll close it in the meantime. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
