### ISSUE TITLE
[Question] clarify in docs what click timeout option waits for

### ISSUE THREAD

**Issue by terion-name** [microsoft/playwright#3144]
It is unclear, what `elementHandle.click({timeout: 30000})` actually does (what it waits for).

So, what it does?) And can this be clarified in documentation?

PS
Also it is unclear what happens, if action fails actionability tests. Will it throw error? Or just nothing will happen? If latter then how to actually understand was click performed or not?

**Comment by DJ-Glock** [comment]
Same for `page.waitForSelector()`

It seems that by default it waits for selector to be visible. But should be documented.

**Comment by dgozman** [comment]
Folks, what is your documentation source? I would like all the options to be clear, but I have to know where do you look for the documentation and how? I hope that all information is somewhere in the docs, it's just hard to navigate there, so I am asking about your process to understand it better.

Meanwhile, [`waitForSelector`](https://playwright.dev/#version=v1.2.1&path=docs%2Fapi.md&q=pagewaitforselectorselector-options) does "wait for the selector to satisfy state option (either appear/disappear from dom, or become visible/hidden)". Visible is the default state.

Here is a doc about [actionability](https://playwright.dev/#version=v1.2.1&path=docs%2Factionability.md&q=). Actions should throw `TimeoutError` if actionability checks do not pass during the designated timeout.

Generally, if Playwright does not throw an error, you can safely assume that it did successfully perform the action - clicked, navigated, took a screenshot, etc.

**Comment by DJ-Glock** [comment]
@dgozman I use search on the playwright.dev website for actual version and read the description :)

Well... my apologies for waitForSelector. I don't know how, but I missed this:
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/26511191/88593618-808b2400-d068-11ea-9c87-430f16cff35f.png">

**Comment by terion-name** [comment]
@dgozman `waitForSelector` is documented clearly, `click` — not. 
does it wait for something to happen after click? or it waits element to be clickable? or what?

**Comment by dgozman** [comment]
The docs situation should be better due to recent changes like #3255 and #3374. Any feedback is welcome!

**Comment by terion-name** [comment]
@dgozman thank you!
