### ISSUE TITLE
[Bug]: timeout error message missing required data

### ISSUE THREAD

**Issue by dvirblev** [microsoft/playwright#31448]
### Version

1.45.0

### Steps to reproduce

1) clone my repo - https://github.com/dvirblev/playwright-tests.git
2) cd playwright-no-trace
3) nx e2e e2e --trace on
4) npx playwright show-trace ./e2e/playwright-report/example-has-title-chromium/trace.zip

(the test will fail)

### Expected behavior

to see in the error message for the waitForReponse function the url of the failed request or a link to the request itself

### Actual behavior

in the error message there is no refrence which request had the timeout
![Screenshot 2024-06-26 at 16 52 31](https://github.com/microsoft/playwright/assets/100562615/04876563-90fb-43c9-a9e1-07fc1be29c4e)

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 49.75 MB / 16.00 GB
  Binaries:
    Node: 18.10.0 - ~/.nvm/versions/node/v18.10.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.10.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ~1.45.0 => 1.42.1
```

**Comment by pavelfeldman** [comment]
The one in example.spec.ts:4 as stated by the previous line in that message?

**Comment by dvirblev** [comment]
@pavelfeldman i'm sorry but i didn't understand the question, can you clarify more?

**Comment by pavelfeldman** [comment]
> in the error message there is no refrence which request had the timeout

No requests had timeout, the Test time out of 30000 was exceeded while waiting for `page.waitForResponse` on line example.spec:4.

**Comment by dvirblev** [comment]
@pavelfeldman oh you mean that it shows for the error what line in the spec it refers to?

**Comment by pavelfeldman** [comment]
Yes, also that's the only thing we can provide - we don't know which URL you timed out waiting for in this case.

**Comment by dvirblev** [comment]
ok, i'll close this than
