### ISSUE TITLE
[Feature]: Add configuration key to run only tests that have been modified via git

### ISSUE THREAD

**Issue by Romarionijim** [microsoft/playwright#31450]
### 🚀 Feature Request

Today, in order to run specific tests in playwright, we have a few options, we have `.only ` to run single files, and we have the option to tag tests @tag followed by --grep command.
what I would like to see is similar to Jest,  to have the option when I type `npx playwright test`, to only run the test files that I have modified in git (staged changes), becaause sometimes if I'm doing a fix on 10 specific files, and I wanna only run these files in parallel or together, I need to tag them and then run them together but then I need to delete that tag because I did it for fixing tests.
it would be awesome to add a config key to the playwright.config.ts file that I could specify to only run what I modify exactly just like in Jest framework.

### Example

```
const config: PlaywrightTestConfig = {
  globalSetup: require.resolve('./global-setup'),
  testDir: './tests/critical-tests',
  timeout: 2 * 120 * 1000,
  globalTimeout: 2 * 60 * 60 * 1000,
  expect: {
    timeout: 45 * 1000
  },
  fullyParallel: true,
  **runModifiedTestFiles: true,** // something like this

```

### Motivation

if you have a large test framework with 1000+ tests and a lot of test files, and I wanna added/modified a few tests files and I wanna run them to see if they did not break but I don't wanna run one file at a time, I wanna be able to run all of these tests that have been modified in git without me having to manually tag or extra complicated configuration,  only by a single key in the config this can be achieved.

**Comment by pavelfeldman** [comment]
Folding into: https://github.com/microsoft/playwright/issues/15075
