### ISSUE TITLE
How to compare two .png images with different size using playwright with typescript?

### ISSUE THREAD

**Issue by Akhourisharma** [microsoft/playwright#31452]
### 🚀 Feature Request

How to compare two .png images with different size , which is in project directory using playwright with typescript?

scenario is-
-i have uploaded one .webp i.e. image1 file into browser
-converted that .webp file to png using sharp
-i have then downloaded that file from link in browser as image2(note- cannot take screenshot because another image like some logo is embedded over it)
-both image1 & image2 are saved in project directory

question - how i can compare these two files image1 & image2 to make sure that both are same to make my test pass?

### Motivation

if we have this documented , it will really help in multiple visual testing

**Comment by pavelfeldman** [comment]
Please don't ask questions here, read the template.

**Comment by Akhourisharma** [comment]
Hi Team,

 I need help on comparing 2 .png images in project directory using
playwright with typescript -
My case is -

1.i have uploaded one .webp image  Image1 from my project directory (it
supports only .webp image)
2.converted this .webp into png using sharp
3.i have download that file from browser as image2 and stored into my
project directory (note- cannot take screenshot because logo is embedded
over this image)

4.both image 1& image2 are in my project directory

Question is- how to compare these two images to make sure that both are
same to make my test pass?

Thank you,
Alisha
