### ISSUE TITLE
[Feature]: All jump after click some buttons in the 'snapshot' area of ui mode 

### ISSUE THREAD

**Issue by HawtinZeng** [microsoft/playwright#31464]
### 🚀 Feature Request

![image](https://github.com/microsoft/playwright/assets/73981739/8fa29103-b229-482c-ab25-f20c4a84d4ff)
Hi, I love the locator feature, but recently I found it's a little wired that I can't get locator in some other page that the auto test havn't browsed, I wish I can pick any locators in all pages .

### Motivation

Better experience.

**Comment by pavelfeldman** [comment]
I am not sure how the title of the issue is related to the description. What jumps?

**Comment by HawtinZeng** [comment]
Sorry for my wired title.

**Comment by pavelfeldman** [comment]
I see. Trace Viewer contains snapshots rather than the live page. It needs no server, it uses resources from the trace. There are no resources for the page you want to jump to, so it is not feasible. You can use `npx playwright codegen` for that though.
