### ISSUE TITLE
[Bug]: Playwright 1.45.0 raises an error ENOENT: no such file or directory, open '/path/to/test-results/.playwright-artifacts-0/hash.zip' with Electron

### ISSUE THREAD

**Issue by mtsmfm** [microsoft/playwright#31473]
### Version

1.45.0

### Steps to reproduce

1. Clone my repo https://github.com/mtsmfm/electron-playwright-with-trace-issue
2. cd pw-145
3. npm install
4. npx playwright test test.spec.ts --trace on

### Expected behavior

```
Running 1 test using 1 worker

  ✓  1 test.spec.ts:15:1 › should work (651ms)

  1 passed (1.4s)
```

### Actual behavior

```
Running 1 test using 1 worker

  ✘  1 test.spec.ts:15:1 › should work (415ms)


  1) test.spec.ts:15:1 › should work ───────────────────────────────────────────────────────────────

    Error: ENOENT: no such file or directory, open '/home/mtsmfm/ghq/github.com/mtsmfm/electron-playwright-example/pw-145/test-results/.playwright-artifacts-0/7e647ec48523e8dd0434626c5a1420a7.zip'

  1 failed
    test.spec.ts:15:1 › should work ────────────────────────────────────────────────────────────────
```

### Additional context

Perhaps the error is thrown by `await app.close();` as I don't see any error if I remove the line.

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 11.28 GB / 15.54 GB
    Container: Yes
  Binaries:
    Node: 20.13.1 - ~/.local/share/mise/installs/node/20/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.8.0 - ~/.local/share/mise/installs/node/20/bin/npm
  IDEs:
    VSCode: 1.90.2 - /home/mtsmfm/.vscode-server/bin/5437499feb04f7a586f677b155b039bc2b3669eb/bin/remote-cli/code
  Languages:
    Bash: 5.0.17 - /usr/bin/bash
```

**Comment by arnaud-lacroix-lm** [comment]
@mtsmfm Do you still have the issue after the update 1.45.1 ?
I still have the same issue on my side on my own project

**Comment by mxschmitt** [comment]
I tried to reproduce with the repository above and 1.45.1 fixes the issue for that. Maybe you issue is different or you didn't update?

**Comment by mtsmfm** [comment]
I don't see the error but it seems now it doesn't capture screenshots/snapshots with Electron for some reason.

**Comment by arnaud-lacroix-lm** [comment]
I tested the repo with 1.45.1 and it works well, yes. Sorry I think my issue seems not related to Electron specifically, but to a global issue :
- When executing a test which takes 20 seconds to be executed, everything works well, but after the 20 seconds of exectuion, before closing, playwright is creating the trace, and it takes the 20 sec of execution + 30 seconds after until the global timeout which is 50 seconds.  : 
![image](https://github.com/microsoft/playwright/assets/127093431/b1e25040-cbb4-494b-b643-efd09fc0fe09)

So my issue is more about the time creation of the trace, which takes too much time compared to the execution time.
