### ISSUE TITLE
how to use the custom expect message in playwright 1.43.1 with cucumber 9.5.1

### ISSUE THREAD

**Issue by Patiljw1** [microsoft/playwright#31479]
Please suggest how to use the custom expect message with cucumber

**Comment by Patiljw1** [comment]
https://playwright.dev/docs/test-assertions#custom-expect-message
I referred the above document, but it's not working the output result . 

expect(eventData.app_name,"app_name not defined as expected").toBe("bbc_web234");

o/p:
 Error: expect(received).toBe(expected) // Object.is equality

**Comment by pavelfeldman** [comment]
Playwright does not support cucumber, please refer to the solution provider you are using.
