### ISSUE TITLE
[Feature]: Extend codegen languages using plugins

### ISSUE THREAD

**Issue by carlosalberto** [microsoft/playwright#31483]
### 🚀 Feature Request

There is currently an external project (in the playwright-community organization) that adds support for Golang. And it seems this is not a priority for the core Playwright team, and hence no out-of-the-box codegen support for Golang can be added, it would be great to expose a way to expand languages support (via external dependencies, of course).

### Example

npx playwright codegen --target golang

### Motivation

Be able to use the fabulous Playwright codegen functionality from Golang land.

**Comment by carlosalberto** [comment]
Probably related to https://github.com/microsoft/playwright/issues/28474

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/28474
