### ISSUE TITLE
[Bug]: Timeout in Playwright Config Applies to Entire Test Instead of Each Step

### ISSUE THREAD

**Issue by ISanjeevKumar** [microsoft/playwright#31484]
### Version

1.38

### Steps to reproduce

I have set up a timeout in the Playwright config file for 30 seconds. In my test, I am using test.step(). If the first step exceeds the 30-second timeout in execution, the entire test is closed immediately without waiting for another 30 seconds for an element for the next step. This behavior implies that the 30-second timeout is applied to the whole test rather than each step. Ideally, the global timeout should be 30 seconds for each action.

For example, if I have a long-running test that lasts for 3 minutes and I set a 1-minute timeout in the config, the test stops immediately after 1 minute with an error saying "page context is closed."

Steps to reproduce :
1. Set up a Playwright project with the following configuration:
```
export default defineConfig ({
  timeout: 60 * 1000 
});
```
2. Create a test with multiple steps, where one of the steps intentionally exceeds the timeout duration:
```
test('long running test', async ({ page }) => {
  await test.step('Step 1: Long step', async () => {
    await page.waitForTimeout(70000); // Exceeds the 1-minute timeout
  });

  await test.step('Step 2: Should not reach here', async () => {
    // This moment it executes the goto method , will get an error saying page getting Context closed 
    await page.goto('https://example.com');
  });
});
```

### Expected behavior

Each step should adhere to the configured timeout independently. If the timeout is set to 1 minute, each action in the step should be allowed to wait for up to 1 minute.

### Actual behavior

The entire test stops after the first step exceeds the 1-minute timeout, without allowing subsequent steps to run.

### Environment

```shell
Playwright version - 1.38 
OS - Mac 14.5
```

**Comment by pavelfeldman** [comment]
That's not the Playwright contract. Our contract is that the test has a time budget and when it is exceeded, the test is interrupted.
