### ISSUE TITLE
[Docs]: /docs/dialogs - add note that page.on() should only be called once

### ISSUE THREAD

**Issue by JorensM** [microsoft/playwright#31488]
### Page(s)

https://playwright.dev/docs/dialogs

### Description

On this page, it is a bit confusing (at least personally) and unclear that the `page.on('dialog', dialog => dialog.accept());` should only be called once. It was my impression that it should be called each time before a dialog appears. After some Googling, it seems that if you want to have a custom handler before each dialog, you should use `page.once()` instead. So my suggestion is to add a note stating that `page.on()` should only be called once and that if you want to use a different handler for each dialog, `page.once` should be used instead.

**Comment by mxschmitt** [comment]
Our Node.js port assumes familiarity with EventEmitter pattern in Node.js.
