### ISSUE TITLE
[Feature]: .Webp image support

### ISSUE THREAD

**Issue by Akhourisharma** [microsoft/playwright#31497]
### 🚀 Feature Request

I am trying to capture the image locator screenshots in .webp format it's giving me error -

Error:locator.screenhot:path: unsupported mime type "image/webp"

My locator is - 
Page.locator('img['src="[https://xyz.abc.com/testing.webp"]'). screenshot({path: 'mywork.webp'});

### Motivation

it will help to automate the pages which supports only .webp images

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/22984

Are you using webp for visual regression testing or what is your use-case?

**Comment by Akhourisharma** [comment]
hi @mxschmitt  I am using webp for visual testing.

My usecase is-

1.i have uploaded one .webp image to my browser page ( Image1) from my project directory (it supports only .webp image)
2.i have to save  that file from browser as image2 and stored into my project directory(but getting error as it is not supporting .webp format)
3.compare both image 1& image2 (which are in my project directory ) to make sure that image which i have uploaded is successfully reflecting)
