### ISSUE TITLE
[Feature]: Ability to overwrite test results of html reports after rerun

### ISSUE THREAD

**Issue by gokulsam07** [microsoft/playwright#31490]
### 🚀 Feature Request

Currently, when a user reruns failed test cases, the existing index.html file is deleted and written again, and the new report only includes the results of the rerun. It would be beneficial to have the option to merge the results of reruns into the original report, overwriting the status of the initial runs. This feature might also be useful in sharding scenarios, where rerun of tests distributed across multiple machines if that's possible? By overwriting the results, we can avoid duplicated test results and provide a more comprehensive report

### Example

Consider a scenario where the first E2E run of 100 tests produces 90 passed, 5 failed, and 5 skipped tests. Upon rerunning the failed tests, it's possible that some or all of the previously failed tests may pass, indicating that there was no actual issue with the code. In this case, it would be highly beneficial to merge the results of the rerun into the original report, overwrite the status of the initial runs

### Motivation

This feature would simplify the process of generating reports for reruns, eliminating the need for external reporters or wrappers. It would also provide a more accurate representation of test results, as users could see the updated status of tests that were previously failed

**Comment by mxschmitt** [comment]
We provide a merge utility for merging reports. Inner-loop and CI-friendly reporters. This seems like something in the middle which we are unlikely to prioritise. Thanks for your understanding.
