### ISSUE TITLE
[Bug]: UI Mode and Trace Files missing recorded data but contain action history

### ISSUE THREAD

**Issue by itz4blitz** [microsoft/playwright#31505]
### Version

1.45.0

### Steps to reproduce

1. Run any test which will fail (headless or headed)
2. Open the trace file or if in UI mode check the top of the UI
3. The browser window is missing from the trace/UI mode. The actions menu still contains all of the actions. If we click an action, we see nothing in the browser.

![image](https://github.com/microsoft/playwright/assets/60281870/f017ff08-d103-4336-97df-c46f48376c32)

![image](https://github.com/microsoft/playwright/assets/60281870/0b3d294c-0b16-4cc0-bf51-9baa0e77c21e)

### Expected behavior

When I run a test, once it fails, I expect to see the browsers and when I click on an action, I expect to see that replayed in the browser.

### Actual behavior

My browser is empty in UI mode and the top menu which shows the timeline is empty. The same issue exists in the trace file.

### Additional context

I tried deleting and reinstalling node_modules

### Environment

```shell
Mac OS M3 Apple Silicon
Latest Playwright
Node.js 21.7.2
Yarn package manager
```

**Comment by mxschmitt** [comment]
We need something which we can run locally - are you able to provide us a zip or a small Git repository which surfaces the problem?

**Comment by itz4blitz** [comment]
[Archive.zip](https://github.com/user-attachments/files/16067395/Archive.zip)

My apologies, I meant to include this. Here you are.

**Comment by itz4blitz** [comment]
[html-reporter.zip](https://github.com/user-attachments/files/16070453/html-reporter.zip)

Here's one of the generated trace files. I modified an assertion to cause this test to fail and as you can see in the report, there's no data outside of the actions.

**Comment by mxschmitt** [comment]
Have you tried disabling video and only enabling tracing?

```txt
    video: 'on',
    contextOptions: {
      recordVideo: {
        dir: 'test-results/videos/'
      }
    }
```

**Comment by itz4blitz** [comment]
> Have you tried disabling video and only enabling tracing?
> 
> ```
>     video: 'on',
>     contextOptions: {
>       recordVideo: {
>         dir: 'test-results/videos/'
>       }
>     }
> ```

I will test this and report back. Thanks for the suggestion.

**Comment by mxschmitt** [comment]
This might be fixed in our Canary builds, could you try them? https://playwright.dev/docs/canary-releases

**Comment by itz4blitz** [comment]
> > Have you tried disabling video and only enabling tracing?
> > ```
> >     video: 'on',
> >     contextOptions: {
> >       recordVideo: {
> >         dir: 'test-results/videos/'
> >       }
> >     }
> > ```
> 
> I will test this and report back. Thanks for the suggestion.

Sorry for the delay, I had vacation last week and forgot to report back on this before leaving. I did try this and it didn't resolve my issue.



> This might be fixed in our Canary builds, could you try them? https://playwright.dev/docs/canary-releases

This seems to have fixed it :) Thank you for the suggestion. Should I stay on Canary or switch back once it is fully released?

**Comment by dgozman** [comment]
@itz4blitz Could you please try the `@beta` version as well? We would like to release a patch version that fixes this issue, but would love for you to verify it fixes your problem. Once we release it, you can switch to the release version instead of a canary version.

```sh
npm install -D @playwright/test@beta
npx playwright install
npx playwrigh test
```

**Comment by pavelfeldman** [comment]
The patch has been released.
