### ISSUE TITLE
[Bug]: Video not loading via playwright, its loading when opened locally

### ISSUE THREAD

**Issue by abhishek-lambda** [microsoft/playwright#31517]
### Version

"1.44.0"

### Steps to reproduce

Visit website : ctv.ca
Run any video , observe the video runs.

Now I wrote a playwright test to test the website, but no video frames are loaded and thus nothing plays.

### Expected behavior

Video should run via playwright test too.

### Actual behavior

No frames are loaded.

### Additional context

   Playwright Test Code:
   ```
   await page.goto('https://www.ctv.ca/');
    await page.mouse.wheel(0, 1000);
    await page.waitForSelector('text="Trending Throwback Series"');
    await page.click('text="Trending Throwback Series"');
    // await page.getByRole('link', { name: 'Watch Latest Episode' }).click();
    await page.waitForSelector('[data-testid="list"] >> xpath=/div[1]');
    await page.click('[data-testid="list"] >> xpath=/div[1]');
    await page.waitForSelector('text="Play S1 E1"');
    await page.click('text="Play S1 E1"');
    await page.waitForSelector('[data-testid="videoplayer"]');
    await page.click('[data-testid="videoplayer"]');
```

### Environment

```shell
System:
OS : Windows 10
Browser :Chrome-125
```

**Comment by mxschmitt** [comment]
Probably this website is using proprietary video codecs, so you need to use either Google Chrome or Microsoft Edge, see [here](https://playwright.dev/docs/browsers#media-codecs).

Have you tried that? See [here](https://playwright.dev/docs/browsers#google-chrome--microsoft-edge) on a how to.

**Comment by abhishek-lambda** [comment]
Yes tried it doesn't work, I tried with chrome, edge, pw-firefox and windows and mac machines, the video doesnt load. Can you please reproduce the error at your end and confirm if its a playwright-issue?

**Comment by mxschmitt** [comment]
I'm unfortunately not able to reproduce, see: 

<img width="608" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/f34a69ea-e458-47f8-a82e-5c8885ff71f3">

**Comment by abhishek-lambda** [comment]
please use the below code in your playwright.config.js file and retry, or you can use VPN and set location to Canada:
```
 use: {
    geolocation: { longitude:106.3468, latitude: 56.1304 },
    permissions: ['geolocation'],
  },
 ```

**Comment by mxschmitt** [comment]
I unfortunately have no access to a VPN, so this issue is unfortunately not actionable for us. We recommend reaching out to the site / the engineers in order to find out why its not working. Errors in the DevTools might reason about it, why they don't show the player.

**Comment by abhishek-lambda** [comment]
did you try with geolocation? you are quite quick to close an issue before its completed

**Comment by mxschmitt** [comment]
Yes, unfortunately didn't help. They detect it by the IP probably.

**Comment by abhishek-lambda** [comment]
cool thank you for your help
