### ISSUE TITLE
[Bug]: Context with and without Proxy

### ISSUE THREAD

**Issue by drRobertDev** [microsoft/playwright#31519]
### Version

latest

### Steps to reproduce

look like is not possible create at same time context with and without proxies

var _playwright = await Playwright.CreateAsync();
var _browser = await _playwright.Chromium.LaunchAsync( new BrowserTypeLaunchOptions() Proxy = new Proxy { Server = "http://per-context" }});

var contextwithProxy = await _browser.NewContextAsync(new {Proxy = new Proxy() { Server = "192... :8888" }); //Work
var contextwithoutProxy =  await _browser.NewContextAsync(new {Proxy = null ); //Not Work

### Expected behavior

should be work with and without proxies setup at same time

### Actual behavior

work only if all use proxies or all not use proxies

### Environment

```shell
last version
```

**Comment by mxschmitt** [comment]
If you are on Windows, this is not possible, due to an upstream Chromium bug: https://github.com/microsoft/playwright/issues/17252

We recommend launching two Browsers as a workaround.

**Comment by humancompilers** [comment]
related; on firefox, when I do two contexts, each with a different proxy, the last proxy ends up overriding the first context's on page navigation. Any idea of why?

**Comment by mxschmitt** [comment]
> related; on firefox, when I do two contexts, each with a different proxy, the last proxy ends up overriding the first context's on page navigation. Any idea of why?

Sounds like a different bug - please file a separate issue with more details. Thank you.

**Comment by humancompilers** [comment]
https://github.com/microsoft/playwright/issues/31525

**Comment by mxschmitt** [comment]
Closing as per https://github.com/microsoft/playwright/issues/31519#issuecomment-2204334561. For Windows we recommend multiple browsers for now while we fix https://github.com/microsoft/playwright/issues/17252.
