### ISSUE TITLE
[Bug]: Proxy per context override on firefox

### ISSUE THREAD

**Issue by humancompilers** [microsoft/playwright#31525]
### Version

1.41.2

### Steps to reproduce

- Start two browser contexts, and set two different proxies.
- First result on each context is ok, and proxies are different. Then navigate on the first context to another page, and you'll see the proxy now is the last proxy that was set (it's overriden)

```
const ctx1 = browser.newContext({ proxy: p1});
const ctx2 = browser.newContext({ proxy: p2});
...
```

My hunch is that it's a firefox issue of sharing http channels? or some global variable replaced there. When I debug playwright itself, it shows that even on page navigation events, when it requests getProxyInfo, it shows the correctly associated proxy for  each context. It seems firefox is replacing the config using the latest set value.

### Expected behavior

If we have an option to set a proxy per context, then each context should keep that proxy for the entirety of its lifecycle, isolated.

### Actual behavior

Multiple contexts with multiple proxies end up using the latest proxy set

### Environment

```shell
System:
    OS: macOS 14.4.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 543.23 MB / 8.00 GB
  Binaries:
    Node: 20.11.1 - /usr/local/bin/node
    Yarn: 1.22.21 - ~/gecko-dev/node_modules/.bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
    bun: 1.0.29 - ~/.bun/bin/bun
  IDEs:
    VSCode: 1.90.1 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    playwright: ^1.44.1 => 1.44.1
    playwright-core: ^1.44.1 => 1.44.1
```

**Comment by mxschmitt** [comment]
Would it be possible to provide a reproduction which we can run locally? I tried a simple setup and it was working.

**Comment by humancompilers** [comment]
Ok, I did some more debugging. What's happening is, when the proxy chooses a random IP dependent on the username, the browser or juggler will not have it saved to make a new proxied request (since it's already auth'ed?). 

https://github.com/microsoft/playwright/blob/main/browser_patches/firefox/juggler/NetworkObserver.js#L605 is not `newProxyInfoWithAuth` and https://github.com/mozilla/gecko-dev/blob/master/netwerk/base/nsProtocolProxyService.cpp#L1699

**Comment by mxschmitt** [comment]
We'd love to look into it! But first we need a minimal reproduction, ideally a test which we can add [here](https://github.com/microsoft/playwright/blob/main/tests/library/browsercontext-proxy.spec.ts) or [here](https://github.com/microsoft/playwright/blob/main/tests/library/proxy.spec.ts).

**Comment by humancompilers** [comment]
Ok, so you can try something like this:

```
it('should isolate proxy credentials between contexts on navigation', async ({ contextFactory, server, browserName, proxyServer }) => {
  proxyServer.forwardTo(server.PORT);
  let auth;
  proxyServer.setAuthHandler(req => {
    auth = req.headers['proxy-authorization'];
    req.headers['forward-for'] = auth;
    return !!auth;
  });
  
    const context1 = await contextFactory({
      proxy: { server: `localhost:${proxyServer.PORT}`, username: 'user1', password: 'secret1' }
    });
    const page1 = await context1.newPage();
    await page1.goto('http://non-existent.com/target.html');
    expect(auth).toBe('Basic ' + Buffer.from('user1:secret1').toString('base64'));
    expect(await page1.title()).toBe('Served by the proxy');
    // await context1.close();
    
    const context2 = await contextFactory({
      proxy: { server: `localhost:${proxyServer.PORT}`, username: 'user2', password: 'secret2' }
    });
    const page2 = await context2.newPage();
    await page2.goto('http://non-existent.com/target.html');
    expect(await page2.title()).toBe('Served by the proxy 2');

    await page1.goto('http://non-existent.com/target.html');
    expect(await page1.title()).toBe('Served by the proxy');

});
```

but to reproduce the proxy behavior, you'll need to patch the proxy server:

```

it.beforeEach(({ server }) => {
  server.setRoute('/target.html', async (req, res) => {
    if (req.headers.for === 'secret2') {
      res.end('<html><title>Served by the proxy 2</title></html>');
      return
    }
        res.end('<html><title>Served by the proxy</title></html>');
  });
});
```

on tests/third_party/proxy/index.ts:

```
	if (req.headers['proxy-authorization']) {
	  const pass = atob(req.headers['proxy-authorization'].split('Basic ')[1]).split(':')[1]
	  headers.for = pass;
	}
```

The idea is that the proxy chooses a new IP based on a username/pass. So we just want to pass along which client we're proxying for, and serve "Served by proxy1" or "Served by proxy2" to see the output. 

As you'll see on the test, after the two isolated contexts are created and correctly show "proxy1" and "proxy2", we try to revisit context1 on the page and it should still show "proxy1", but instead it's overriden and shows "proxy2"

**Comment by humancompilers** [comment]
```
Running 3 tests using 3 workers
  1) [firefox-library] › library/browsercontext-proxy.spec.ts:326:3 › should isolate proxy credentials between contexts on navigation 

    Error: expect(received).toBe(expected) // Object.is equality

    Expected: "Served by the proxy"
    Received: "Served by the proxy 2"
```

**Comment by humancompilers** [comment]
brilliant! thank you. (hint: did some more digging, may have to do with auth caching)
