### ISSUE TITLE
Could not drag and drop on webkit

### ISSUE THREAD

**Issue by tienletesting** [microsoft/playwright#31523]
**Could not drag and drop** a web element in our website on **Webkit** browser that included in Playwright package. I tried both manually and automatically using Playwright Typescript test script. 
It works fine on other browsers: chromium, firefox, Microsoft Edge.

I tried to drag and drop manually on Safari browser on my Mac Mini and it works fine. My Safari version is 16.3.

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!

**Comment by davidAtInleague** [comment]
Same here on chrome. I don't get any dragover events on the window at all, `locator.dragTo` only seems to fire mousemove events.
