### ISSUE TITLE
[Bug]: clip is not in screenshot options.  

### ISSUE THREAD

**Issue by Huseyinaltas1** [microsoft/playwright#31538]
### Version

1.45.1

### Steps to reproduce

1. 1. Set up framework of Typescript/cucumberjs/playwright
2. 2. Take screenshot of current page with options
3. I want to take a screenshot with a clip dimensions. Looks like screenshot function does not have 'clip' option.
 await logo.screenshot({
        path: process.env.SCREENSHOT_PATH + '/receipts/barcode' + world.barcodeId + '.png',
        clip: {
            x: 600,
            y: (bounding_box.height - bounding_box.y) / 1.1957,
            width: bounding_box.width,
            height: newHeight,
        },
        omitBackground: true,
    });
Looks like clip is not an option in screenshot while documentation says it is

### Expected behavior

 I want to take a screenshot with a clip dimensions. Looks like screenshot function does not have 'clip' option.
 await logo.screenshot({
        path: process.env.SCREENSHOT_PATH + '/receipts/barcode' + world.barcodeId + '.png',
        clip: {
            x: 600,
            y: (bounding_box.height - bounding_box.y) / 1.1957,
            width: bounding_box.width,
            height: newHeight,
        },
        omitBackground: true,
    });

### Actual behavior

Looks like clip is not an option in screenshot while documentation says it is

### Additional context

<img width="1188" alt="Screenshot 2024-07-03 at 8 53 20 AM" src="https://github.com/microsoft/playwright/assets/91209940/475d04d0-8111-43d1-b906-49b194e45208">

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M2 Pro
    Memory: 84.69 MB / 16.00 GB
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    npm: 10.7.0 - /usr/local/bin/npm
    pnpm: 8.12.1 - /usr/local/bin/pnpm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.45.1 => 1.45.1
```

**Comment by mxschmitt** [comment]
The `clip` option is currently only exposed to [`page.screenshot`](https://playwright.dev/docs/api/class-page#page-screenshot-option-clip) - so it sounds like a feature request if you want to only get a partial clip of an element you are making a screenshot of.
