### ISSUE TITLE
[Bug]: Could not drag and drop on Webkit 

### ISSUE THREAD

**Issue by tienletesting** [microsoft/playwright#31539]
### Version

1.45.1

### Steps to reproduce

1. Open Playwright Webkit by adding "await page.waitForTimeout(120000);" into the 'has title' test in example.spec.ts file. Then run that test by the "npx playwright test -g 'has title' --project=webkit --headed" command. 
2. When the webkit browser stops at the "await page.waitForTimeout(120000);", open new webkit window.
3. Go to: https://ui.vision/demo/webtest/dragdrop/
4. Try to drag the list items over the dustbin, and drop them to have the bin eat the item on Webkit.

### Expected behavior

The list items is dragged and dropped into the dustbin successfully as same as the way it works on other browsers like chromium, edge, firefox.

### Actual behavior

The list items is NOT dragged and dropped into the dustbin on Webkit.

### Additional context

*Also, I tried another drag and drop example website (https://www.w3schools.com/html/html5_draganddrop.asp) and my unpublished web project, both manually and with Playwright Typescript test scripts, drag and drop not working in all cases.

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 42.66 GB / 63.71 GB
  Binaries:
    Node: 22.3.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.90.2 - C:\Users\tile\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.2.26 - C:\Windows\system32\bash.EXE
  npmPackages:
    @playwright/test: ^1.45.1 => 1.45.1
```

**Comment by mxschmitt** [comment]
The following works for me, could you give us a test which is not working for you?

```
test('my test', async ({ page }) => {
  await page.goto('https://ui.vision/demo/webtest/dragdrop/')
  await page.getByRole('link', { name: 'two' }).dragTo(page.locator('#bin'));
  await page.waitForTimeout(-1)
});
```

**Comment by tienletesting** [comment]
Thank you for your reply.

Yea, the test you posted works for me too. But Drag and drop on our web project is not working on Webkit. In Console window, it shows the **_"TypeError: undefined is not an object (evaluating 'b.length')"_** error. Drag and drop is working well on Chrome, Edge and Firefox, and I dont see that error in Console window. Our project is not released yet, so I could not give you the website and automation code, but I think I can do a screen share if you want.
