### ISSUE TITLE
[Feature]: Add to TestStep, field with status of run like it is in TestResult and TestCAse

### ISSUE THREAD

**Issue by dawidkwiecien** [microsoft/playwright#31533]
### 🚀 Feature Request

I've tried to implement custom reporter. And i would like to use in in method onStepEnd status of step (passed, failed, timeouted) etc.

### Example

interface TestStep {
......

  status: "passed"|"failed"|"timedOut"|"skipped"|"interrupted";
......

}

### Motivation

Its not possible to get state of step in custom reported

**Comment by dawidkwiecien** [comment]
Using TestResults field , status in onStepEnd still return "Skipped" doesn't matter in which state test finishes

**Comment by mxschmitt** [comment]
We expose the [`error` property](https://playwright.dev/docs/api/class-teststep#test-step-error) which should help you to reason about what happened with a specific step. 

Could you provide us a reproduction (as code) what you'd like to observe from a test which is not as of today?

**Comment by dawidkwiecien** [comment]
Hi @mxschmitt my proposal is to add to TestStep property status
![image](https://github.com/microsoft/playwright/assets/2427085/e83d102b-f5fd-463d-ba7e-ce16c2596258)

`import type {
  FullConfig,
  FullResult,
  Reporter,
  Suite,
  TestCase,
  TestResult,
  TestStep,
} from "@playwright/test/reporter";
import { format } from "date-fns";
import { Logger, ILogObj } from "tslog";

/**
 * @see https://playwright.dev/docs/test-reporters#custom-reporters
 */
class StandardRun implements Reporter {
  log: Logger<ILogObj>;
  constructor() {
    this.log = new Logger({ prettyLogTemplate: "{{rawIsoStr}} --> " });
  }
  onBegin(config: FullConfig, suite: Suite) {
    let message = `Starting the run for project '${suite.project.name}' with ${suite.allTests().length} test`;
    if (suite.allTests.length > 1) message += "s";
    this.log.info(message);
  }

  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  onTestBegin(test: TestCase, result: TestResult) {
    this.log.info(`   Starting test '$={test.title}'`);
  }

  onStepBegin(test: TestCase, result: TestResult, step: TestStep): void {
    if (step.category == "test.step") this.log.info(`       Starting step '${step.title}'`);
  }

  onStepEnd?(test: TestCase, result: TestResult, step: TestStep): void {
    if (step.category == "test.step") {
      this.log.info(`       Finished step '$={step.title}' at '${this.formatDuration(step.duration)}''`);
    }
  }

  onTestEnd(test: TestCase, result: TestResult) {
    this.log.info(
      `   Finished test '$={test.title}' at '${this.formatDuration(result.duration)}' with result '${result.status}'`,
    );
  }

  onEnd(result: FullResult) {
    this.log.info(`Finished the run: ${result.status} with duration '${this.formatDuration(result.duration)}'`);
  }

  formatDuration(value: number) {
    const d = new Date(value);
    return format(d, "mm:ss.SSS");
  }
}

export default StandardRun;
`

**Comment by mxschmitt** [comment]
Yes I understand that, but why does looking at the `error` property not work for you? We internally don't have the notion a status on a TestStep - so ideally you look at the `error` property and make your reasoning from there. If there is no error, it passed, if there is one and its TimeoutError its a timeout, etc.

**Comment by mxschmitt** [comment]
Closing as per above - we recommend looking at the [`error`](https://playwright.dev/docs/api/class-teststep#test-step-error) property for now.
