### ISSUE TITLE
how to wait after sorting ?

### ISSUE THREAD

**Issue by srikanthathikari** [microsoft/playwright#31543]
### Version

1.44.1

### Steps to reproduce

 I am landing on a page that has multiple tiles and performing a click on one of the sort options (ascending or descending). I have to click the first item after sort. However, the click happens even before the new list is displayed. waitForTimeout works. Are there any better ways to handle this scenario ? 
 
  await this.page.locator(`span:has-text("ascending")`).click()
   await this.page.locator('firstItem').first().click

### Expected behavior

Expected to wait until the new order is displayed and click upon the change in url. 

### Actual behavior

Click is being performed before the new list is displayed. 

### Environment

```shell
Mac
```

**Comment by mxschmitt** [comment]
We recommend asserting the table structure or parts of it after you have clicked. e.g.

```ts
await expect(page.getByRole('listitem').first()).toHaveText('AAAAAA')
```

You need to find the selector of the first/second cell and then assert a value of it.

**Comment by mxschmitt** [comment]
closing as per above.
