### ISSUE TITLE
[Bug]: Version 1.45 via docker not available but documentation is updated 

### ISSUE THREAD

**Issue by gauravkhuraana** [microsoft/playwright#31549]
### Version

1.45 docker jammy

### Steps to reproduce

The command is updated at all documentation, but when i try to pull i cannot as its not present on official site.

    docker pull mcr.microsoft.com/playwright/dotnet:v1.45.0-jammy

### Expected behavior

it should be uploaded first and then documentaiton should be updated

### Actual behavior

it should be uploaded first and then documentation should be updated

### Additional context

![image](https://github.com/microsoft/playwright/assets/15048211/564acf8d-351f-4483-a322-0819daeab869)

### Environment

```shell
Docker pull image latest version not available
```

**Comment by mxschmitt** [comment]
Should be fixed!
