### ISSUE TITLE
[Feature]: Install option to prune browser that are older than the installed one

### ISSUE THREAD

**Issue by thiagodp** [microsoft/playwright#31546]
### 🚀 Feature Request

Having an option such as `--prune` to prune old browser versions.

### Example

Example:
`playwright install chromium --prune`

would install the latest Chromium version and then remove older versions.

### Motivation

- It would reduce the disc size occuped by older browser versions significativelly;
- Developers would not have to remove older browser versions manually.

**Comment by mxschmitt** [comment]
Playwright internally keeps track of which browser revision is used in which npm project. If there aren't any usages anymore, we prune them and remove them from the system after you install the new revisions. So in your case, most likely they are still referenced in other projects.

For us to triage this further, we need reproduction steps, it could totally be a bug on our side! Ideally the reproduction steps start from removing [ms-playwright](https://playwright.dev/docs/browsers#managing-browser-binaries), then create a project with an older Playwright version and updating it etc.

**Comment by thiagodp** [comment]
Hello @mxschmitt, that's probably the case you mentioned.
I'll close this Issue since it's a Feature Request, and open a new one in case of a bug.
Thank you!
