### ISSUE TITLE
[Bug]: Not able to test maximizing browser window via f11.

### ISSUE THREAD

**Issue by ZooDoo4U** [microsoft/playwright#31545]
### Version

1.45.1

### Steps to reproduce

```
test('test youtube full screen', async ({ page }) =>
{ 
    await page.goto('https://www.youtube.com/'); 
    await page.locator('body').press('F11');    
   // Would expect the browser fullscreen with no menu visible
   // but it appears the f11 press does nothing. 
    await page.pause();
});
```

### Expected behavior

Pressing f11 as a user without PW, the browser window goes full screen and no menus...

### Actual behavior

Appears nothing happens when F11 is press, one can now manually set the focus in browser PW started pres f11 and brows rem[works as expected, seems like the f11 key is just eaten and nothing is performed 

### Additional context

My main intention is the ability to test the responsiveness/page layout when full screen or not.   As a user in either Chrome/Firefox one can press F11 for a full screen (removed menus too).  

As a hack i can do this (but the window menu bars remain, not really full screen, doesn't seem to be at (0,0).

   let screenData = await page.evaluate(() =>
    {
        let sizeData = {height: window.screen.height, width: window.screen.width};
        window.resizeTo( sizeData.height, sizeData.width );
        window.moveTo(0,0);
        return sizeData; 
    });

### Environment

```shell
System: 
     Win 10
     AMD 5950x x64
Binaries:
    Node: v20.10.0
    Npm: 10.8.1
npmPackages:
     "@playwright/test": "^1.45.1"
```

**Comment by mxschmitt** [comment]
Thank you for the issue! Unfortunately, this is not going to happen. Playwright automates web pages, so everything within the tab, but not the browser UI.

**Comment by ZooDoo4U** [comment]
I'm not sure why PW should be filtering out F11?  If not automating the browser with PW when a user presses f11 the browser will response and maximize the browser...  Not sure why f11 is filtered out and not passed on...
