### ISSUE TITLE
[Bug]: Redirect after Azure Entra / AAD - B2C Login fails  with dotnet / Docker in Azure dev ops pipeline

### ISSUE THREAD

**Issue by gauravkhuraana** [microsoft/playwright#31548]
### Version

1.45 ( via docker jammy)

### Steps to reproduce

**Steps to reproduce**

Create a Blazor Server app with activated azure ad authentication as described [here](https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-blazor-server) 
or 
Pick up any app which has B2C Enabled 

Try to do a login via playwright in docker dotnet

### Expected behavior

Redirect to the home page of the application after validation via B2C

### Actual behavior

it never lands on the home page and system fails with expect etc error as home page never came
IN traces I can see after sign in button is pressed home page never loads

all the cases where we are validating just home page works well 

### Additional context

The problem is similar as shown here but our is with 1.45 docker / dotnet 

https://github.com/microsoft/playwright-dotnet/issues/2884

### Environment

```shell
System:
 Containerized Docker 

 pool:
   vmImage: 'ubuntu-latest'
 container: mcr.microsoft.com/playwright/dotnet:v1.45.0-jammy

Test run ok in local machine without docker without any issue but in docker container in azure dev ops pipeline it fails with error as actual application page does not load and fails in B2C
```

**Comment by mxschmitt** [comment]
I'm unfortunately not able to create a app registration in our tenant (due to compliance) / have a test entra directory available. Would it be possible to share a deployed setup somewhere which we can use? Ideally something we just run with `dotnet test`?

**Comment by yury-s** [comment]
We need a local reproduction that clearly demonstrates there is a bug in Playwright. It may well be a problem with the CI configuration/network access etc, we cannot help with that. We cannot take any action based on provided information, feel free to file another bug once you have a repro that we can run locally.
