### ISSUE TITLE
[Bug]: Webkit `Error: browserType.connect: Target page, context or browser has been closed`

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/playwright#31558]
### Version

1.45.1

### Steps to reproduce

1. Clone https://github.com/hamirmahal/error-browsertype-playwright
2. npm install
3. npx playwright test --project=webkit
4. You should see this error come up.
```
  2) [webkit] › example.spec.ts:3:5 › has title ────────────────────────────────────────────────────

    Error: page.goto: WebKit encountered an internal error
    Call log:
      - navigating to "https://playwright.dev/", waiting until "load"
```

### Expected behavior

`npx playwright test --project=webkit`

and

`npx playwright test --project=webkit --debug`

should run without issue.

### Actual behavior

`npx playwright test --project=webkit`

and

`npx playwright test --project=webkit --debug`

both fail.

`npx playwright test --project=webkit --debug`

fails with

```
    Error: browserType.launch: Target page, context or browser has been closed
    Browser logs:

    <launching> /home/hamir/.cache/ms-playwright/webkit-2035/pw_run.sh --inspector-pipe --no-startup-window
    <launched> pid=54275
    [pid=54275][err] /home/hamir/.cache/ms-playwright/webkit-2035/minibrowser-gtk/bin/MiniBrowser: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE
```

### Environment

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 11.41 GB / 31.03 GB
    Container: Yes
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 9.4.0 - ~/.nvm/versions/node/v20.9.0/bin/pnpm
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.45.1 => 1.45.1
```

**Comment by mxschmitt** [comment]
Are you by any chance running it from VSCode installed via Snap? Or something installed via Snap? Looks like it tries to load a library via snap and fails, probably with a version mismatch:

```
[pid=54275][err] /home/hamir/.cache/ms-playwright/webkit-2035/minibrowser-gtk/bin/MiniBrowser: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE
```

See e.g. https://github.com/microsoft/playwright/issues/30676#issuecomment-2099630269 or https://github.com/microsoft/playwright/issues/23899#issuecomment-1614580778

I think workarounds are to install VSCode via the deb package or try e.g. `GDK_BACKEND=x11` which might work as well.

**Comment by hamirmahal** [comment]
> Are you by any chance running it from VSCode installed via Snap? Or something installed via Snap? Looks like it tries to load a library via snap and fails
> 

I am!

```
Version: 1.91.0
Commit: ea1445cc7016315d0f5728f8e8b12a45dc0a7286
Date: 2024-07-01T18:52:41.959Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.5.0-41-generic snap
```

> I think workarounds are to install VSCode via the deb package or try e.g. `GDK_BACKEND=x11` which might work as well.

Do you mean running this command?

```
GDK_BACKEND=x11 npx playwright test --project=webkit --debug
```

That failed with a similar error.

```
$  GDK_BACKEND=x11 npx playwright test --project=webkit --debug

Running 1 test using 1 worker
  1) [webkit] › authentication.spec.ts:3:12 › the page redirects to http://localhost:3000/test/reporting/packages after logging in 

    Error: browserType.launch: Target page, context or browser has been closed
    Browser logs:

    <launching> /home/hamir/.cache/ms-playwright/webkit-2035/pw_run.sh --inspector-pipe --no-startup-window
    <launched> pid=96657
    [pid=96657][err] /home/hamir/.cache/ms-playwright/webkit-2035/minibrowser-gtk/bin/MiniBrowser: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE
```

**Comment by mxschmitt** [comment]
Have you tried it outside in a normal terminal? (Not vscode).

**Comment by hamirmahal** [comment]
Oh, that's interesting.

```
npx playwright test --project=webkit --debug
```

works without issue if I try it inside a normal terminal.

**Comment by mxschmitt** [comment]
Sounds like a VSCode bug then / how they distribute it via snap, since they put probably their snap libraries / LD_PRELOADs into this Terminal. We recommend installing VSCode via deb. I'll close it for now, since I don't see how we can act on it, thanks!

**Comment by hamirmahal** [comment]
You're welcome! Thank you for your help.
