### ISSUE TITLE
[Feature]: More granular setup dependencies

### ISSUE THREAD

**Issue by glenjamin** [microsoft/playwright#31555]
### 🚀 Feature Request

It'd be great if there was a way to have only the relevant setup steps run when running a single test

### Motivation

Our test suite has a number of different users we log in as, as different users are in different states.

We have a `setup` project which logs into these various users and stores a different `storageState` for each. Our main tests then depend on the setup project as recommended in the authentication docs

However, when running a single test on the CLI, we still have to run all of the setup tests for each user - even though the test we're running only uses 1 or 2 of those

**Comment by mxschmitt** [comment]
Do your test files map to the users they need?

**Comment by glenjamin** [comment]
> Do your test files map to the users they need? For that you could create multiple setup projects and depend on them. 

It's also that the individual tests in the main project that vary in which dependency they need too

I suppose I could split up the projects so that all tests which need each user are in their own project, but that seems like a bunch of work to create and then maintain

**Comment by mxschmitt** [comment]
For that we'd recommend something like [this](https://playwright.dev/docs/auth#moderate-one-account-per-parallel-worker). So inside your test / ideally fixture, you log in and persist it to disk / write the storageState file on the file system.

Ideally in combination with something like [this](https://www.npmjs.com/package/proper-lockfile), so that multiple workers don't break each-other.

**Comment by glenjamin** [comment]
Ah ok, so something where each test that wants an auth session takes a lock on the file and does the login step, so that whichever one gets there first does the work, and the others just read it?

Is that a recipe that would be worth putting in the docs?

Is it an important enough pattern that it should be considered for core in some manner?

**Comment by mxschmitt** [comment]
> Ah ok, so something where each test that wants an auth session takes a lock on the file and does the login step, so that whichever one gets there first does the work, and the others just read it?

Yes, it depends on the scenario / implementation.

> Is that a recipe that would be worth putting in the docs?
