### ISSUE TITLE
[Feature]: Allow calling .pdf on a Frame instead of only the Page

### ISSUE THREAD

**Issue by JCQuintas** [microsoft/playwright#31553]
### 🚀 Feature Request

I would like to call `.pdf()` on a `Frame` object. Not only the parent page.

### Example

```ts
await page.frame('MyPrintFrame').pdf({ path: "my-frame.pdf" })
```

### Motivation

You can call `iframe.contentWindow.print()` so you should also be able to call `.pdf()` from playwright. 

My current use-case is that I build an iframe with only the content that should be printed, attach it to the doc, and call `.print()` on it. So instead of printing the entire page, its only the elements I deem necessary. Eg: When printing a table.

In the end, I want to make sure that the iframe is being correctly setup and that the preview will show only the necessary elements. I then check the generated PDFs against each-other to prevent regression.

**Comment by mxschmitt** [comment]
This is outside of the scope for Playwright - Playwright does not consider printing a PDF as a core feature.

**Comment by JCQuintas** [comment]
Hi @mxschmitt can you elaborate? 

This API is already implemented https://playwright.dev/docs/api/class-page#page-pdf

My request is for extending the pdf generation from the Page into the Frame
