### ISSUE TITLE
[Bug]: doubled test result messages when running one test using vscode extension

### ISSUE THREAD

**Issue by Den-dp** [microsoft/playwright#31556]
### Version

1.45.1

### Steps to reproduce

1. `npm init playwright@latest`
2. `code .`
3. open generated `tests/example.spec.ts`
4. click Run button

### Expected behavior

Only one spinner/test result message should be displayed

### Actual behavior

https://github.com/microsoft/playwright/assets/1770529/c6e91b2d-5b64-452e-9864-afefebd6e78b

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 AMD EPYC 7763 64-Core Processor
    Memory: 18.77 GB / 31.95 GB
  Binaries:
    Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.91.0 - C:\Users\denis\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.45.1 => 1.45.1
```

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/30815
