### ISSUE TITLE
[Docs]: Mouse move coordinates are unclear

### ISSUE THREAD

**Issue by glenjamin** [microsoft/playwright#31567]
### Page(s)

https://playwright.dev/docs/api/class-mouse#mouse-move

### Description

It's unclear from the documents whether `mouse.move()` takes absolute or relative coordinates

In practice it seems to be absolute. It would be helpful to note how to move relative to the current position too

**Comment by mxschmitt** [comment]
They are always relative to the top left of your page / page main frame in CSS pixels.

**Comment by glenjamin** [comment]
Did the docs get updated on this? I raised this as a docs bug because I thought the mouse docs should make this clearer.

**Comment by mxschmitt** [comment]
Updated in https://github.com/microsoft/playwright/pull/31606.
