### ISSUE TITLE
[Feature]: The Clock should have a function to get the time.

### ISSUE THREAD

**Issue by CalebMacdonaldBlack** [microsoft/playwright#31574]
### 🚀 Feature Request

The [Clock](https://playwright.dev/docs/api/class-clock#methods) should have a function to _get_ the time.

### Example

```ts
await page.clock.getTime();
```

### Motivation

Fetching Date.now() is annoying.

**Comment by pavelfeldman** [comment]
Could you share your use case?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
