### ISSUE TITLE
[Bug]: Exception on 204 response

### ISSUE THREAD

**Issue by elacuesta** [microsoft/playwright#31570]
### Version

1.44.1

### Steps to reproduce

Execute the following script:
```javascript
// no_content.js
const { chromium, firefox } = require('playwright');

(async () => {
  const browser = await chromium.launch();
//   const browser = await firefox.launch();
  const page = await browser.newPage();
  await page.goto('https://httpbin.org/status/204', { waitUntil: 'networkidle' });
  await browser.close();
})();
```

```
$ node no_content.js
```

### Expected behavior

I would expect the script to finish without errors.

### Actual behavior

The script fails to navigate to the page.

Chromium error:
```
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.goto: net::ERR_ABORTED at https://httpbin.org/status/204
Call log:
  - navigating to "https://httpbin.org/status/204", waiting until "networkidle"

    at /home/.../no_content.js:7:14 {
  name: 'Error'
}
```

Firefox error:
```
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.goto: NS_BINDING_ABORTED
Call log:
  - navigating to "https://httpbin.org/status/204", waiting until "networkidle"

    at /home/.../no_content.js:7:14 {
  name: 'Error'
}

```

### Additional context

* Same behavior with all values of `waitUntil`.
* Seems to be the same as https://github.com/microsoft/playwright/issues/26897

### Environment

```shell
System:
    OS: Linux 6.5 Linux Mint 21.3 (Virginia)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12600K
    Memory: 19.82 GB / 31.11 GB
    Container: Yes
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
  IDEs:
    VSCode: 1.90.2 - /usr/bin/code
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    playwright: 1.44 => 1.44.1
```

**Comment by mxschmitt** [comment]
When you navigate with your normal Google Chrome to `https://httpbin.org/status/204` it also doesn't "accept" the navigation, so I think it seems to work as expected here. Imagine your are on some URL, you navigate to `https://httpbin.org/status/204` then Chromium will stay on this URL like nothing happens.

I recommend to filter e.g. this error out.

**Comment by elacuesta** [comment]
Thank you @mxschmitt for your prompt reply. The exceptions seem to come directly from the browsers so I guess it makes sense for Playwright to just rely them to the user.

I'm closing the issue now but I'll leave what's probably a support question, so feel free to disregard it.

I'm trying to tell apart the case when a `Page.goto` call _only_ triggers a download, i.e. there is no response other than the download. This scenario also throws an exception, however while Firefox and Webkit include a nice "Download is starting" message in it, with Chromium it's the same `page.goto: net::ERR_ABORTED at (URL)` message. Is there a way I can tell a download response from a 204 response (or any other kind of response that might trigger the `net::ERR_ABORTED` exception), other than listening to the `response` event and check for the status code? I'm trying to do it in a general way, without hardcoding the 204 check. I could also listen to the `download` event and consider it as "not a download" if the waiting times out, but that could introduce some unnecessary waiting. I hope this makes sense, thanks for your time.
