### ISSUE TITLE
[Playright config file ]

### ISSUE THREAD

**Issue by montrealtt** [microsoft/playwright#31583]
### Please do not submit this issue.

- [x] I understand

**Comment by montrealtt** [comment]
In my playwright config file, I added a bracket of projects configuration, and I found the test cases disappeared from the test lab extension window, and then I commented the project section out, and then they came back! So I assumed that the project configuration conflicted with something with a playwright extension.

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
