### ISSUE TITLE
[Feature]: Allow users to set different timeouts for different browsers

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/playwright#31582]
### 🚀 Feature Request

It'd be nice if users could set specific timeouts for specific browsers.

### Example

Building off of https://playwright.dev/docs/api/class-test#test-set-timeout...

```ts
import { SECONDS, test } from "@playwright/test";

test('very slow test', async ({ page }) => {
  // The strings in `projects` are ideally type-checked.
  test.setTimeout(60, SECONDS, { projects: ['Mobile Safari', 'firefox', 'chromium'] });
  // Leave the default `timeout` of 30 seconds for the remaining `projects` tested,
  // in this case `webkit` and `Google Chrome`.
});
```

### Motivation

For whatever reason, one of our tests takes 48 s to run on `chromium`,  53 s to run on `firefox`, and only 27 s to run on `webkit` and 26 s to run on `Google Chome`.

It'd be nice if there was a fine-grained approach to setting timeouts, so that we could keep a stricter 30 second time limit for browsers that complete the test more quickly, like `Google Chrome` and `webkit`, while not unnecessarily failing tests for browsers that take a bit longer to finish for whatever reason.

```
  Slow test file: [Mobile Safari] › authentication.spec.ts (1.0m)
  Slow test file: [firefox] › authentication.spec.ts (53.2s)
  Slow test file: [chromium] › authentication.spec.ts (48.0s)
  Slow test file: [webkit] › authentication.spec.ts (27.1s)
  Slow test file: [Google Chrome] › authentication.spec.ts (26.2s)
```

**Comment by mxschmitt** [comment]
You can increase the timeout per project like this:

```ts
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
    },

    {
      name: 'firefox',
      use: {
        ...devices['Desktop Firefox'],
      },
      timeout: 60_000,
    },

    {
      name: 'webkit',
      use: {
        ...devices['Desktop Safari'],
      },
    },
```

would that work for you?

Yo can also get it during runtime via `test.info().project.name`, so you can only call it for specific projects.

**Comment by hamirmahal** [comment]
Ah, that works! I wasn't aware we could set a `timeout` on an item in `projects`. Thanks for the code snippet.
