### ISSUE TITLE
[Bug]: Playwright cannot receive correct content in CustomEvent

### ISSUE THREAD

**Issue by huchenlei** [microsoft/playwright#31580]
### Version

1.45.1

### Steps to reproduce

Run following test

```typescript
  test("Emit event", async ({ page }) => {
    const event = await page.evaluate(() => {
      return new Promise<CustomEvent>((resolve) => {
        document.addEventListener(
          "custom-event",
          (e) => resolve(e as CustomEvent),
          { once: true }
        );

        document.dispatchEvent(new CustomEvent("custom-event", { detail: { foo: "bar" } }));
      });
    });

    expect(event.detail).toEqual({ foo: "bar" });
  });
```

The test listens for a CustomEvent with detail, but the event object returned by playwright does not have any content. The event object actually returned is `{isTrusted: false}`

### Expected behavior

Test should pass

### Actual behavior

  1) [chromium] › litegraphEvent.spec.ts:25:3 › Canvas Event › Emit event ──────────────────────────

    Error: expect(received).toEqual(expected) // deep equality

    Expected: {"foo": "bar"}
    Received: undefined

      36 |     });
      37 |
    > 38 |     expect(event.detail).toEqual({ foo: "bar" });
         |                          ^
      39 |   });
      40 | });
      41 |

        at d:\ComfyUI_frontend\browser_tests\litegraphEvent.spec.ts:38:26

  1 failed
    [chromium] › litegraphEvent.spec.ts:25:3 › Canvas Event › Emit event ───────────────────────────

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 9.87 GB / 31.93 GB
  Binaries:
    Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.90.2 - C:\Users\hcl\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.44.1 => 1.45.1
```

**Comment by mxschmitt** [comment]
Serialising complex objects [between the browser and Node.js is best effort](https://playwright.dev/docs/evaluating), we recommend passing simple data structures only, in your case just the detail object:

```
 (e) => resolve((e as CustomEvent).detail),
```

would that work for you?

**Comment by mxschmitt** [comment]
Closing as per above.

**Comment by mindriven** [comment]
Hey there,
I'm having same issue - I am not able to trigger a CustomEvent. with properly initialized `detail` property. In my case I am using a web-component that reacts on custom events, when I do `element?.dispatchEvent('fatalError', { detail: { test: 'test' } });` in my test code, correct event gets triggered, but it when I print it out to console (with `console.log('fatal error', ev);` in the handler) I just see this:
![image](https://github.com/user-attachments/assets/1eb598fe-9439-479c-9f77-25cfe589a9b8)

I've googled for hours and have not found a way to trigger a custom event, that I would need for my test.
@mxschmitt is there any way to trigger such event? Would be awesome if you could point me to the relevant documentation.

**Comment by mindriven** [comment]
for now managed to workaround it with:
```typescript
const issueCustomEvent = async (page: Page, selector: string, type: string, eventData: object) => {
  const data = { selector, type, eventData };
  await page.evaluate(({ selector, type, eventData }) => {
    const el = document.querySelector(selector);
    el?.dispatchEvent(new CustomEvent(type, eventData));
  }, data);
};
```
