### ISSUE TITLE
[Bug]:  await page.goto('https://api.whatsapp.com/send?phone=2348120897343&text=i%20have%20voted') always timeout

### ISSUE THREAD

**Issue by fancy45daddy** [microsoft/playwright#31589]
### Version

playwright-chromium@1.40.0

### Steps to reproduce

const browser = await playwright.chromium.connect({wsEndpoint:`...`}) 
const context = await browser.newContext({viewport:null})
//context.setDefaultTimeout(0)
const page = await context.newPage()
await page.goto('https://api.whatsapp.com/send?phone=2348120897343&text=i%20have%20voted')
always get page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://api.whatsapp.com/send?phone=2348120897343&text=i%20have%20voted", waiting until "load"
it seems that the javascript in 'https://api.whatsapp.com/send?phone=2348120897343&text=i%20have%20voted' will send an request to whatsapp://send?phone=2348120897343&text=i%20have%20voted which cause load event always fail.

I want to know how to bypass the request to whatsapp://send?phone=2348120897343&text=i%20have%20voted is load event can fire.

### Expected behavior

await page.goto('https://api.whatsapp.com/send?phone=2348120897343&text=i%20have%20voted') can finish and I can run the next command.

### Actual behavior

  - navigating to "https://api.whatsapp.com/send?phone=2348120897343&text=i%20have%20voted", waiting until "load" Timeout 30000ms exceeded

### Environment

```shell
linux jammy
```

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/11014.

Handling native URLs is not possible as of today.
