### ISSUE TITLE
[Bug]: Test-specific 'video' config not working.

### ISSUE THREAD

**Issue by JorensM** [microsoft/playwright#31581]
### Version

1.45.0

### Steps to reproduce

[playwright-video-not-saved.zip](https://github.com/user-attachments/files/16118951/playwright-video-not-saved.zip)

1. Download an unzip attached example project
2. Run the test using `npm run test`

### Expected behavior

The video for the test should be recorded and saved in the `test-results` folder since `video: 'on'` was specified in `defineConfig` of the test.

### Actual behavior

Video doesn't get recorded/saved.

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx
    Memory: 1.97 GB / 7.81 GB
  Binaries:
    Node: 20.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.91.0 - C:\Users\lucky\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.45.0 => 1.45.0
```

**Comment by mxschmitt** [comment]
Calling `defineConfig` inside a test is not supported, you need to use [test.use](https://playwright.dev/docs/api/class-test#test-use):

```ts
import { test, expect } from '@playwright/test';

test.use({ video: "on" })

test(`test 1`, async ({ page, browser }) => {
  await page.goto('https://example.com')
  await page.goto('https://github.com')
  await page.goto('https://facebook.com')
});
```

Usually you configure trace/video on a project level, hence we have `defineConfig` examples inside the docs.
