### ISSUE TITLE
[Feature]: Cucumber support

### ISSUE THREAD

**Issue by Jay-alffie** [microsoft/playwright#31599]
### 🚀 Feature Request

A gherkin supported framework will be great option in playwright. I currently integrated cucumber with playwright and it's awesome. But still, some of the features are missing due to playwright test runner. (example : tohavescreenshot, soft assertions)

### Example

In WebDriverIO there is framework option in webdriverIO config file. We can choose cucumber with that. Gherkin support is very familiar in market. Also, BDD framework is understandable by non-technical persons too. 

### Motivation

I got this idea from WebDriverIO. It is similar like playwright in config, installation. I can also see many playwright users using cucumber framework with playwright.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/11975
