### ISSUE TITLE
[Feature]: Add "always" option to fixtures

### ISSUE THREAD

**Issue by Thomas-Haider** [microsoft/playwright#31605]
### 🚀 Feature Request

Originates from: https://github.com/microsoft/playwright/issues/29229

We currently have all teams specify metadata information such as author, ticket, app, tags in the `test.use({...})` block, in the following way:
```typescript
test.use({
  author: Author.SOME_AUTHOR,
  ticket: 'TICKET-1234',
  app: APPS.SOME_APP,
  tags: ['some-tag'],
});
```

This has the great benefit, that it is not needed to specify the information for each test, in case it is the same, because it re-uses the information for each test in the same file, until a new `test.use` block is specified. 

Sadly, we have the issue with this implementation that skipped tests are not reported because the auto test-scoped fixture, in which we pick up, validate, and send the metadata to our custom reporters, is not executed. 

how our auto test-scoped fixture looks like:
```typescript
  metaDataHandler: [
    async ({ page, app, author, ticket, tags, userRole, logger, browser }, use, testInfo) => {

      // do some validation & attach it to the metadata.json via `testInfo.attach(...`
      await use(); // execute test
    },
    { auto: true, scope: 'test' },
  ],
```

Therefore, I would like to request a new fixture option that allows running the fixture no matter the test result. Thanks already in advance for your efforts!

### Usage:
```typescript
import { test as base } from '@playwright/test';

type CustomFixtures = {
  metaDataHandler: void;
};
type CustomOptions = {
  author: string;
};

const test = base.extend<CustomOptions & CustomFixtures>({
  author: undefined,
  metaDataHandler: [
    async ({ author }, use, testInfo) => {
      if (!author) {
        throw Error('Please specify an author for the test');
      }
      console.info(`Test Author: ${author}`);
      await testInfo.attach('metadata.json', { body: JSON.stringify({ author: author }) });
      await use();
    },
    { scope: 'test', auto: true, always: true }, // <- new option "always: true" which means that it will always executed no matter if the test was skipped or not
  ],
});

test.use({ author: 'max.mustermann' });

test('tryout', async ({ page }) => {
  await page.goto('https://playwright.dev/docs');
  // Expected output: Test Author: max.mustermann
});

test.skip('skiped tryout', async ({ page }) => {
  await page.goto('https://playwright.dev/docs');
  // Expected output: Test Author: max.mustermann
});

```

### Motivation

Especially in bigger companies with platform products, where teams have their own repositories for their app, it is important to have insights into the health/maturity of the app in order to instrument the correct quality gates that prevent or allow a new release of the app in production.

One thing that is important for such a quality gate, is to have an overview of all the tests in a central place that shows what features/pages are tested in a certain version of the app or, even more importantly, what features are not tested for that app because the tests are skipped (or no tests exist at all) and could potentially cause an app failure in production.

Therefore, it is important to also send the metadata information for skipped tests to ensure that the people responsible for new app releases are aware.

**Comment by mxschmitt** [comment]
For that we recommend to put `test.skip()` inside your test body.

**Comment by yury-s** [comment]
> Therefore, it is important to also send the metadata information for skipped tests to ensure that the people responsible for new app releases are aware.

For uploading test results and stats about skipped tests you can also employ our [reporter API](https://playwright.dev/docs/test-reporters#custom-reporters).

**Comment by Thomas-Haider** [comment]
@mxschmitt  But that is not the "logical" way of skipping a test for developer, I mean, lets assume you have a test that you want to skip for what ever reason and it is common practice to just use `test.skip('testname...`. instead of adding the test.skip inside the test. So why not add it, as the developer would not be affected by such a change and it would bring a lot more possibilities to get insights. 

@yury-s as said, we have a custom reporter, but since our metadata validation takes place in the auto fixture, we don't have access to it in the reporter for skipped tests.

**Comment by Thomas-Haider** [comment]
but, i would be also happy, in case you can think of any other possibilitie, that won't change how devs are specifiying their metadata and would allow us to validate it and access it in the custom reporter. :)
