### ISSUE TITLE
[Bug]: CSS nesting selector not working

### ISSUE THREAD

**Issue by basslagter** [microsoft/playwright#31607]
### Version

1.45

### Steps to reproduce

Create a simple (React) application. 

Add some basic css (using [nesting selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Nesting_selector)) in the head of the html, like:
```
<style>
      .foo {
        color: red;

        &.bar {
          color: green;
        }
      }
 </style>
```

Run the application and see the CSS working correctly.

Now, run the application inside Playwright and see &.bar being transformed to &amp.bar, making the css broken.

### Expected behavior

I expect Playwright to leave the & as is.

### Actual behavior

Playwright converts the & to &amp

### Environment

```shell
Latest versions of playwright, chrome, etc. Running on mac
```

**Comment by basslagter** [comment]
Sure. I can reproduce it by following these steps:

1. Create a scaffold vite app:
`npm create vite@latest pw-repro -- --template react-ts`
2. inside the created folder run npm install
3. Install playwright:
`npm init playwright@latest`
4. Add a style block containing a nesting selector to the head of index.html in the root of the folder:
```
<style>
      .foo {
        color: green;

        &.bar {
          color: red;
        }
      }
    </style>
```
5. Let app.jsx return the corresponding HTML:
```
 return (
    <>
      <div className="foo">A</div>
      <div className="foo bar">B</div>
    </>
  );
```
6. run the app:
`npm run dev`
7. See a green A and a red B
8. Build the project:
`npm run build`
9. Run preview server:
`npm run preview` 
(note that the A is still green and the b red on this output)
10. Adjust the default test to point to the preview server
```
test("has title", async ({ page }) => {
  await page.goto("http://localhost:4173/");

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);
});
```
11. Run playwright:
`playwright test --ui`
11. Run the default test 
12. See in the output a green A and a green B
13. When inspecting the document, in the style section of the head see:
```
      .foo {
        color: green;

        &amp;.bar {
          color: red;
        }
      }
```

**Comment by mxschmitt** [comment]
Awesome repro!

Investigation: Looks like the problem is in our snapshot rendering logic here: https://github.com/microsoft/playwright/blob/f374f8db38c8ab1fe9674a1839bd9fdbc5023842/packages/trace-viewer/src/snapshotRenderer.ts#L56

We probably should not escape styles.
