### ISSUE TITLE
[Feature]: Add space between texts get from `all_text_contents`

### ISSUE THREAD

**Issue by thangckt** [microsoft/playwright#31604]
### 🚀 Feature Request

Dear Developers, 

I wonder if there is a way to add space between texts get from the method `.all_text_contents`

Example:
```html
<div>
    <p>Some text 1</p>
    <p>Some text 2</p>
</div>
```
When apply method `.all_text_contents` to `div`
The current playwright gives "Some text 1.Some text 2"

Expectation: "Some text 1. Some text 2" or "Some text 1. \nSome text 2"

### Motivation

.

**Comment by mxschmitt** [comment]
allTextContents returns a `string[]` - so you can do e.g. `(await page.getByRole('link').allTextContents()).join(' ')`.

**Comment by thangckt** [comment]
hi @mxschmitt 

Thank you so much for your guide.
For so reason, my locator contains some elements inside, and the `allTextContents` is apply on parent element.
As my previous example, I cannot select <p> tag, but <div> tag. 

Thank

**Comment by mxschmitt** [comment]
This is what we do inside:

```ts
await page.locator('...').evaluateAll('ee => ee.map(e => e.innerText)');
```

Since your use-case seem to fall outside of the norm, I recommend to adjust this code to your liking so it works for you. In your case maybe instead of using `innerText` inside, going manually over the `children` and concatenate them.

**Comment by thangckt** [comment]
@mxschmitt Thank you for your help.
