### ISSUE TITLE
[Bug]: Trace is not showing any screenshots nor test name

### ISSUE THREAD

**Issue by FitTech961** [microsoft/playwright#31613]
### Version

1.45.0

### Steps to reproduce

Here's my Playwright config:

```
const config: PlaywrightTestConfig = {
  testDir: './',
  timeout: 60 * 1000,
  globalTimeout: 40 * 60 * 1000,
  expect: {
    timeout: process.env.CI ? 10000 : 15000,
  },
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: 2,
  workers: 1,
  reporter,
  use: {
    actionTimeout: 0,
    baseURL: process.env.BASE_URL || 'http://localhost:3000',

    trace: 'on-all-retries',
  }
}
```

Steps to reproduce:

1. Run a test suite from the CLI and make sure that one of the tests will fail
2. Run ` yarn playwright show-report` to show the report
3. Download the `trace` of the failing test from the first retry
4. Open https://trace.playwright.dev/ and drag and drop the downloaded trace into it

### Expected behavior

After following the above steps:
I should be able to see the test suite and test name along with screenshots

![Screenshot 2024-07-09 at 3 54 04 PM](https://github.com/microsoft/playwright/assets/74727995/9cfd1f1c-1f90-42da-b22e-978e49a3895c)

### Actual behavior

After I updated Playwright to `1.45.0` the trace viewer no longer shows the test name nor any screenshots
![Screenshot 2024-07-09 at 3 55 35 PM](https://github.com/microsoft/playwright/assets/74727995/74d44945-2434-49c0-a558-e1d3d5228192)

### Environment

```shell
System:
    OS: macOS 14.5
    Memory: 43.69 MB / 16.00 GB
  Binaries:
    Node: 20.11.0 - ~/.asdf/installs/nodejs/20.11.0/bin/node
    Yarn: 3.2.4 - ~/.asdf/installs/nodejs/20.11.0/bin/yarn
    npm: 10.2.4 - ~/.asdf/plugins/nodejs/shims/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by mxschmitt** [comment]
Are you creating the context yourself? We recently discovered a regression in v1.45.0 around this area. Would it be possible to test with our [Canary release](https://playwright.dev/docs/canary-releases) - while we issue v1.45.1?

**Comment by FitTech961** [comment]
@mxschmitt Yes I am creating the context in each test suite. I tried the Canary release, and it worked. When can we expect the official release to be available?

**Comment by mxschmitt** [comment]
@FitTech961 could you re-try on our @beta? We are about to release 1.45.2 and would like to have it confirmed again.

**Comment by FitTech961** [comment]
@mxschmitt I tested the @beta version, and it seems to be working as expected.
