### ISSUE TITLE
[Feature]: Add response delay to route requests

### ISSUE THREAD

**Issue by russelporosky** [microsoft/playwright#31631]
### 🚀 Feature Request

An ability to delay responses (not requests) from an API call.

### Example

```typescript
await route.fulfill({
    response,
    delay: 500, // wait n milliseconds before responding
});
```

### Motivation

We have a test where a race condition is possible when responses are received out of order (from the same endpoint, only difference is in the request payload). I need a test to watch for that. Cypress has a `setDelay()` method in its request interceptor which worked perfectly, and something that performs the same function in Playwright would be great.

**Comment by yury-s** [comment]
You can achieve that via a regular `setTimeout`:

```js
    const response = await route.fetch();
    await new Promise(f => setTimeout(f, 500));
    await route.fulfill({
      response,
    });
```
 will that work?

**Comment by russelporosky** [comment]
I've been trying that, but there's some subtle difference between how Playwright handles the test and how Cypress does it.

In our app, we've got a group of observables that use `mergeMap` - currently, if a response is returned from the server out of order (eg. 1st request is the last received), the user sees the wrong data. If we switch to `concatMap` or `switchMap`, the problem disappears (for different reasons, but both do the job).

So in Cypress, I would just introduce a delay of 500ms to the first call to ensure it was last to respond, and the test would fail with `mergeMap` but pass for the other two.

With Playwright, the test fails no matter which operator is in use.

**Comment by yury-s** [comment]
You can fetch all responses first and then fulfill original requests with them in any order you like with arbitrary delays between the responses(using setTimeout). Delaying just one response by arbitrary time is just one edge case.

**Comment by russelporosky** [comment]
It might be an edge case, but ensuring an early API call responds after a later one is the exact test I need to show the problem.

Can you illustrate what you mean? My test is currently setup like so:

```typescript
const rows = await page.locator('.data-row');
for (let index = 0; index < 4; index++) { // only send 4 requests in total
  await page.route('https://some.api?client=42', async route => {
    if (index === 0) { // delay the first response
      const response = await route.fetch();
      await new Promise(f => setTimeout(f, 500));
      await route.fulfill({ response });
    }
  });
  await rows.nth(index).locator('.check-icon').click(); // trigger an API call
}
```

**Comment by russelporosky** [comment]
I think I just realized what I was doing, and it's pretty obvious now that I see it!

If `index` wasn't `0` then I wasn't fulfilling the request! The fulfill line needs to be outside the `if...then` statement :D

Okay, it works as expected now. No new feature needed (although having the easy-to-use syntactic sugar would be convenient).
