### ISSUE TITLE
[Bug]: Unable to test share screen by chromium

### ISSUE THREAD

**Issue by milad2golnia** [microsoft/playwright#31636]
### Version

Version 1.45.1

### Steps to reproduce

I want to test screen sharing by playwright and chromium. I have a code snippet which works in Mac OS perfectly but in Linux and docker image `mcr.microsoft.com/playwright:v1.45.1-jammy` get an identical error which seems it's because of wrong binary of chromium.
Here is my minimal code:
```
async function testPlaywright() {
  try {
    console.log('I started');
    const browser = await chromium.launch({
      headless: false,
      args: [
        '--use-fake-ui-for-media-stream',
        // '--use-fake-device-for-media-stream',
        '--allow-http-screen-capture',
        '--enable-usermedia-screen-capturing',
        '--auto-select-desktop-capture-source=Entire screen',
      ],
    });
    console.log('browser launched');
    const context = await browser.newContext();
    const page = await context.newPage();
    page.on('console', (message) => {
      console.log(message.text());
    });
    page.on('pageerror', (err) => {
      console.log('page error:', err);
    });
    console.log('Got a new page');
    await page.goto('http://localhost:3000');
    console.log('Site loaded');
    await page.click('#root > button:nth-child(1)');
    console.log('Page clicked.');
    page.on('download', async (donwload: Download) => {
          const path = await donwload.path();
          const name = await donwload.suggestedFilename();
          const url = donwload.url();
          console.log(name, path, url);
          donwload.saveAs(`${process.env.DIR}-localhost-${name}`);
        });
  } catch (error) {
    console.error(error);
  }
}
testPlaywright() 
```
The http://localhost:3000 is a simple front-end which is trying to share screen using `navigator.mediaDevices.getDisplayMedia` API and then start recording and downloading display (You can ignore downloading and recording part because the error occurs when I try to share screen). This front-end doesn't have any problem because without playwright and by official versions of Firefox and Chromium it's working without any problem.

The given code faces problem both in my Linux OS and Docker, here I paste my commands to test it into a docker container:
```
$ docker run -v ./:/app --network host -it mcr.microsoft.com/playwright:v1.45.1-jammy /bin/bash
```
Then inside docker container, I run following command:
```
# xvfb-run  --auto-servernum --server-num=1 --server-args='-screen 0, 1920x1080x24' npm run start:dev
```

Another information: If we uncomment `'--use-fake-device-for-media-stream'` argument, it's working again but with a fake video.

### Expected behavior

I should see following logs:
```
I started
browser launched
Got a new page
[vite] connecting...
[vite] connected.
Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
Site loaded
Page clicked.
DATA_AVAILABLE
DATA_AVAILABLE
prefix-.10087.webm /tmp/playwright-artifacts-XXXXXXRCw7Fu/cf6f37c8-d290-4cfe-8db1-dbe4ab86af0c blob:http://localhost:3000/151dcbb4-2563-4abf-a3f3-caf48401c145
prefix-.10096.webm /tmp/playwright-artifacts-XXXXXXRCw7Fu/cfc66fca-c997-4f90-a559-d635b8954813 blob:http://localhost:3000/d447c5f5-af80-47cc-ab02-1e6c5bc8704f
DATA_AVAILABLE
prefix-.15090.webm /tmp/playwright-artifacts-XXXXXXRCw7Fu/d8999611-5f93-4eeb-b7ff-2870a3d86db6 blob:http://localhost:3000/9b6d18a9-6e48-41a6-98d4-eaac6c674f7c
DATA_AVAILABLE
prefix-.20103.webm /tmp/playwright-artifacts-XXXXXXRCw7Fu/72afccce-cb96-4e4d-82b0-c87aeb6a6de6 blob:http://localhost:3000/4f4141c6-1320-4e23-b4d5-aa52788c695b
```

Note: Some of output like `[vita] ...` and `Download the React...` comes from browser console.

### Actual behavior

Here is what I see:
```
I started
browser launched
Got a new page
[vite] connecting...
[vite] connected.
%cDownload the React DevTools for a better development experience: https://reactjs.org/link/react-devtools font-weight:bold
Site loaded
Page clicked.
page error: [DOMException: Could not start video source]
```
I think this is because of wrong underlying browser version because the browser which is installed with Mac OS works perfectly

### Environment

```shell
Since I'm running inside docker, I executed `npx envinfo --preset playwright` inside docker container and here is result:

# npx envinfo --preset playwright
Need to install the following packages:
envinfo@7.13.0
Ok to proceed? (y) y

  System:
    OS: Linux 6.1 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
    Memory: 6.70 GB / 15.54 GB
    Container: Yes
  Binaries:
    Node: 20.15.0 - /usr/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.7.0 - /usr/bin/npm
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    playwright: ^1.45.1 => 1.45.1 

```
```

**Comment by yury-s** [comment]
> Then inside docker container, I run following command:

It may well be that screen capture doesn't work in Chromium under `xvfb`. You can try running without it on linux. Unfortunately, this is a rare scenario that is not a priority for Playwright. We recommend using Chromium mechanisms for such tests, e.g. fake media sources. Playwright fully relies on Chromium support of fake/live media streams in testing scenarios.

Closing as we don't have plans to support testing with live screen share.

**Comment by shyampatadia** [comment]
@milad2golnia can you tell me how did you got it working with firefox? I am getting the same error in firefox
