### ISSUE TITLE
[Feature]: Ability to extend playwright.config.ts instead of overwriting the current config 

### ISSUE THREAD

**Issue by kimberly-microsoft** [microsoft/playwright#31635]
### 🚀 Feature Request

It would be great if there was a method/way to extend the config file instead of overwriting it using test.use(). 

### Example

For example: 

Currently, my playwright.config.ts has the following configurations in the launch options:
```
launchOptions: {
    proxy: { server: "per-context" },
},
```

For a specific test, I want to pass in a browser argument like this:
```
test.use({launchOptions: {
    args: ["--crash-test"],
});

```
However, this overrides the existing launchOptions provided in the config file. As a result, I have to restate the proxy like this: 
```
test.use({launchOptions: {
    proxy: { server: "per-context" },
    args: ["--crash-test"],
});
```

### Motivation

The motivation behind this request is to pass in browser arguments for specific tests. Having this feature will make it a lot easier to customize the config file to fit for each test case.

**Comment by yury-s** [comment]
You can import original config and apply the overrides to the original parameters, something like this:

```js
import config from '../playwright.config';

test.use({
    launchOptions: {
        ...config.use?.launchOptions,
        headless: false,
    }
})
```
Would that work for you?

**Comment by yury-s** [comment]
You can also extract common options into a base structure and import them both in the config and in the overrides.

**Comment by kimberly-microsoft** [comment]
unfortunately, we do not want to access the general config.use but the project's config.use 
for example our config has projects listed like this:
```
projects: [
  {
     name: browserSetup,
     use: {
        launchOptions: {
           proxy: { server: "per-context" }
        }
     }
  }
  ...
];
```

Ideally, we would want to be able to access the project's launchOptions and fill that in appropriately. Is that currently possible?

**Comment by yury-s** [comment]
Since `launchOption` is just a built-in [fixture](https://playwright.dev/docs/test-fixtures), you can access current project via [test.info().project](https://playwright.dev/docs/api/class-testinfo#test-info-project), but you'll need to [override](https://playwright.dev/docs/test-fixtures#overriding-fixtures) the fixture with a function:

```js
test.use({
  launchOptions: async ({ launchOptions }, use) => {
      console.log('info', test.info().project.name);
      await use({
        ...launchOptions,
        headless: false
      });
  }
});
```
