### ISSUE TITLE
azure ad autentication

### ISSUE THREAD

**Issue by kovacsdongo** [microsoft/playwright#31643]
hi all,

A wrote a pre request sript in postman
`if (!pm.environment.get("ACCESS_TOKEN") || Date.now() >= pm.environment.get("ACCESS_TOKEN_EXPIRES"))
{

    console.log(pm.environment.get("AZURE_CLIENT_ID"));
    console.log(pm.environment.get("AZURE_CLIENT_SECRET"));
    console.log(pm.environment.get("AZURE_TARGET_SCOPE"));

    pm.sendRequest({
        url: 'https://login.microsoftonline.com/' + pm.environment.get("AZURE_TENANT_ID") + '/oauth2/v2.0/token',
        method: 'POST',
        header: 'Content-Type: multipart/form-data',
        body: {
            mode: 'formdata',
            formdata: [ 
                {key: "grant_type", value: "client_credentials", disabled: false},
                {key: "client_id", value: pm.environment.get("AZURE_CLIENT_ID"), disabled: false},
                {key: "client_secret", value: pm.environment.get("AZURE_CLIENT_SECRET"), disabled: false},
                {key: "scope", value: pm.environment.get("AZURE_TARGET_SCOPE"), disabled: false},
            ]
        }
    }, function (err, res) {
        if (err)
        {
            console.log(err);
        }
        else
        {
            let json = res.json();
            pm.environment.set("ACCESS_TOKEN", json.access_token);
            pm.environment.set("ACCESS_TOKEN_EXPIRES", Date.now() + json.expires_in * 1000);
        }
    });
}`

it works fine
and i tried to adapt into playwright
my authHelper file
```
`import { Page } from 'playwright';
import fetch from 'node-fetch';

function getEnvVariable(key: string): string {
  const value = process.env[key];
  if (!value) {
    throw new Error(`Environment variable ${key} is not defined`);
  }
  return value;
}

export async function getAccessToken(): Promise<string> {
  const tenantId = getEnvVariable('AZURE_TENANT_ID');
  const clientId = getEnvVariable('AZURE_CLIENT_ID');
  const clientSecret = getEnvVariable('AZURE_CLIENT_SECRET');
  const scope = getEnvVariable('AZURE_SCOPE');

  const url = `https://login.microsoftonline.com/${tenantId}/oauth2/v2.0/token`;

  const params = new URLSearchParams();
  params.append('client_id', clientId);
  params.append('scope', scope);
  params.append('client_secret', clientSecret);
  params.append('grant_type', 'client_credentials');

  const response = await fetch(url, {
    method: 'POST',
    body: params,
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
    },
  });

  const data = await response.json();
  return data.access_token;
}

export async function loginWithToken(page: Page, accessToken: string) {
  const tenantId = getEnvVariable('AZURE_TENANT_ID');

  await page.pause();
  await page.goto(`https://login.microsoftonline.com/${tenantId}/oauth2/v2.0/token`);

  // Simulate login by setting the token in local storage or cookies
  await page.evaluate((token) => {
    localStorage.setItem('access_token', token);
  }, accessToken);

  // Reload or navigate to ensure the app picks up the token
  await page.reload();
}
```
`
my test file
```
`import { test, expect } from '@playwright/test';
import { getAccessToken, loginWithToken } from './authHelper.js';

test.only('simple login test user', {tag: ['@profile', '@smoke']}, async ({page}) => {
  const accessToken = await getAccessToken();

  await loginWithToken(page, accessToken);

  // Perform your test actions here
  await page.screenshot({ path: 'screenshot.png' }); // Example action
});
```
`
and i have an env file with data
but when i want to run i get this error
> playwright test --config=playwright.config.ts --project=login --workers=1 --headed --grep @db

(node:18340) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: No tests found

(node:18340) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

have anybody a suggestion how should i fix it

**Comment by yury-s** [comment]
That's probably because you use `multipart/form-data` in one case and `application/x-www-form-urlencoded` in the other. You can try using Playwright [APIRequestContext.post](https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-post) with [multipart](https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-post-option-multipart) parameter.

Closing as this is not a Playwright bug or feature request, please use our [community resources](https://playwright.dev/community/welcome) for general questions. If you think this is a bug in Playwright, please open a new issue and follow the bug template.
