### ISSUE TITLE
[Bug]: Reporter list print step broken on version 1.45.1

### ISSUE THREAD

**Issue by AnishSDET1** [microsoft/playwright#31647]
### Version

1.45.1

### Steps to reproduce

The following playwright config

`printSteps: true` for `reporter list` does not print out the steps anymore when upgrading playwright to the latest version v1.45.1

The steps were being printed out within the console with Playwright Version: 1.39, so somewhere in between version 1.39 & 1.45.1 has caused this regression. 

I am unable to upgrade playwright version due to this issue.

### Expected behavior

`printSteps: true` for `reporter list` should print out the steps 

### Actual behavior

`printSteps: true` for `reporter list` does not print out the steps 

### Environment

```shell
MacOS
node v20.11.0
npm 10.2.4
@playwright/test: 1.45.1
```

**Comment by yury-s** [comment]
I cannot reproduce it locally. We recently changed how Playwright detects if it is attached to a TTY terminal and the steps are only printed in TTY. In some CI the check may return false but you can override it by specifying [`PLAYWRIGHT_FORCE_TTY=1`](https://playwright.dev/docs/test-reporters#list-reporter). Does that help?

**Comment by AnishSDET1** [comment]
Thank for the speedy response 

So Version 1.39, with `printSteps: true for reporter list` without setting `PLAYWRIGHT_FORCE_TTY=1`
     1.4 As a user, I ... › .... (33ms)
     2.6 As a user, I › ...(27ms)
     8.5 As a user, I ... › .. (1.2s)

Now with the latest version v1.45.1

no output `without` setting `PLAYWRIGHT_FORCE_TTY=1`

with `setting` `PLAYWRIGHT_FORCE_TTY=1` it looks better

     4.3 `…`XXXX Text
     5.2 `…`XXXX Text
     5.3 …XXXX Text
     8.6 …XXXX Text
     8.7 …XXXX Text

The issue I am having with this setup is that the complete text is not displayed and the beginning is replaced with `…` whether terminal is maximised or not

**Comment by yury-s** [comment]
The terminal width is determined automatically with a fallback to 100 characters. Looks like in your setup it doesn't work as expected. You can override the terminal with path specifying it as PLAYWRIGHT_FORCE_TTY value, e.g. the following will set it to 150 chars: `PLAYWRIGHT_FORCE_TTY=150`. Will that work?

> The issue I am having with this setup is that the complete text is not displayed and the beginning is replaced with … whether terminal is maximised or not

I thought it was happening on CI, but it sounds like you experience it locally. I cannot reproduce it in standard macos terminal, what is the environment where it happens?

**Comment by AnishSDET1** [comment]
So I am trying to get it to work locally, once locally works, then should work in CI.

By setting `PLAYWRIGHT_FORCE_TTY=150` or `PLAYWRIGHT_FORCE_TTY=1`, the following screenshot indicates what is being displayed on my MacOS Terminal (locally)

![Screenshot 2024-07-11 at 19 16 54](https://github.com/microsoft/playwright/assets/147388500/ce3eaec1-b1ce-4733-9517-879e11ab8cf4)

So, as you can see from the screenshot the following step 2.8 and 2.9 is truncated with `...` and not displaying the full information.

Like I have said previously, this has been working with version 1.39 without setting `PLAYWRIGHT_FORCE_TTY` but I can live with that by setting this with version 1.45.1, but wish to see the full text as the screenshot shows.

**Comment by AnishSDET1** [comment]
Ok, that works, thanks a lot.  The docs indicate that this value is either true or false, but yes also accepts an integer.  As a side note, after upgrading to Playwright to 1.45.1, I am experiencing some flakiness with the the automated tests.  But anyway, this issue can be closed.  Thanks.

**Comment by AnishSDET1** [comment]
Related to this issue using Playwright version 1.45.1 which I've noticed

When initialising PLAYWRIGHT_FORCE_TTY to 500, the steps information is being printed out twice/duplicated with VS Code (MacOS) and GHA (ubuntu)

```
2.14 As a user, I press X
2.14 As a user, I press X
1.13 As a user, I press Y
1.13 As a user, I press Y
```

On MacOS Terminal, the information is only being printed out once as expected such as

```
2.14 As a user, I press X
1.13 As a user, I press Y
```
Can this be revisited please or shall I open a new bug for this issue ?
