### ISSUE TITLE
[Feature]: add .closeTo() method to find the locator closest to another one

### ISSUE THREAD

**Issue by remorses** [microsoft/playwright#31651]
### 🚀 Feature Request

There is a very common workflow I find myself doing with Playwright: get the locator of an element close to another one.

Currently the best way to do that is by knowing the common parent to both elements:

```ts
const parent = await page
    .locator('fieldset')
    .filter({ hasText: 'Authorized JavaScript origins' })
await parent.getByLabel('Add URI').click()
```

But this is not very easy to write because you need to know the parent locator so that the other element is also a child of it.

It would be great if there was an API to get a locator closest to another one.

```ts
await parent
    .getByLabel('Add URI')
    .closeTo(page.getByText('Authorized JavaScript origins'))
    .click()
```

### Example

```ts
await parent
    .getByLabel('Add URI')
    .closeTo(page.getByText('Authorized JavaScript origins'))
    .click()
```

### Motivation

I think it's possible to do this with a selector using `:near` but I usually try to avoid using complex selectors, having a method `.closeTo` would be great

**Comment by remorses** [comment]
Now that I think about it an alternative would be `.below` or `.above`, `.rightOf` and `.leftOf`

**Comment by yury-s** [comment]
You can already use [layout based](https://playwright.dev/docs/other-locators#css-matching-elements-based-on-layout) locators. 

There is also open request for parent/child/sibling locators: https://github.com/microsoft/playwright/issues/23718, folding this request into it.
