### ISSUE TITLE
[Bug]: Cannot fill to input[type=number] type

### ISSUE THREAD

**Issue by Huseyinaltas1** [microsoft/playwright#31669]
### Version

1.45.1 

### Steps to reproduce

```
 const elementHandle: ElementHandle<SVGElement | HTMLElement> | null = await world?.page.$('xpath=' + selector);
 await elementHandle!.fill(query, { force: true });
```

```
Error
       Attachment (image/png)
       elementHandle.fill: Error: Cannot type text into input[type=number]
       Call log:
         -   fill("£20")
         - attempting fill action
```
       
![Screenshot 2024-07-12 at 2 01 05 PM](https://github.com/user-attachments/assets/dc65847f-7d61-40b3-b410-f8ab45c35e35)

### Expected behavior

Expected to fill in input[type=number]

### Actual behavior

Error
       Attachment (image/png)
       elementHandle.fill: Error: Cannot type text into input[type=number]
       Call log:
         -   fill("£20")
         - attempting fill action

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M2 Pro
    Memory: 86.58 MB / 16.00 GB
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    npm: 10.7.0 - /usr/local/bin/npm
    pnpm: 8.12.1 - /usr/local/bin/pnpm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.45.1 => 1.45.1
```

**Comment by yury-s** [comment]
"£" is not a digit, so the method throws. Please provide a full self-contained reproduction which we could run locally if you think this is a Playwright bug.

**Comment by Huseyinaltas1** [comment]
Ahh that's right. I am on migration from puppeteer. It was accepting like this in puppeteer but playwright not. I think regardless input type we should fill values via playwright.

**Comment by Huseyinaltas1** [comment]
@yury-s  Ahh that's right. I am on migration from puppeteer. It was accepting like this in puppeteer but playwright not. I think regardless input type we should fill values via playwright, may be it should be.

**Comment by dgozman** [comment]
@Huseyinaltas1 It is impossible to set value to `£20` for the `<input type=number>`. Even if you assign the value with `input.value = '£20'`, it will be validated by the browser and cleared. Instead, you should call `locator.fill('20')` and your website will nicely show it as `$20`.

Closing as there is no action item for Playwright here.
