### ISSUE TITLE
[BUG] cannot click button in iframe if the iframe is not in view

### ISSUE THREAD

**Issue by joost2076** [microsoft/playwright#3166]
**Context:**
- Playwright Version: playwright@1.2.1
- Operating System: ubuntu 20.04
- Node version:  v10.19.0
- Browser: only tried chromium

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
   const browser = await playwright.chromium.launch({headless:false, })
 
  const context = await browser.newContext({viewport:{width:1920, height:600}})
  // const context = await browser.newContext({viewport:{width:1920, height:1080}})
  // increasing the height solves the problem 

  const page = await context.newPage()
  await page.goto('https://www.w3schools.com/html/html_iframe.asp')
  const frame = page.frames()[1]
  const button = await frame.$('#sncmp-banner-btn-learnmore')
 
  await button.click()
  await browser.close()
})()
```

**Describe the bug**
the page displays an iframe with a cookie consent button. Problem is that with the default screen heights, the button in the iframe is not visible and cannot be clicked. 
It seems that playwright tries to scroll the iframe to make the button appear, but not the page. Without scrolling the page, the button will not appear. Playwright logs the following several times before failing

(this might be a weird example because the button is also on the mainpage with the same id)
```
retrying elementHandle.click action
[api]   waiting for element to be visible, enabled and not moving
[api]   element is visible, enabled and does not move
[api]   scrolling into view if needed
[api]   done scrolling
[api]   element is outside of the viewport
```

**Comment by aslushnikov** [comment]
Yes, this is a known Chromium bug. We have a failing test for this already: https://github.com/microsoft/playwright/blob/51ce47f30f5eb7a5c431ec515f74d89a2fdabd9a/test/click.jest.js#L300-L309

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.

**Comment by NayeemJohnY** [comment]
@pavelfeldman and @aslushnikov
Is this issue got resolved ? I am facing this issue on below context:
Playwright Version: playwright@1.27.1
Operating System: Windows 10
Node version: v16.13.0
Browser: Chromium

In webkit & firefox it is working
