### ISSUE TITLE
[Bug]: click timeout set explicitly to 0 is ignored in favor of global timeout

### ISSUE THREAD

**Issue by fungairino** [microsoft/playwright#31671]
### Version

1.44.1

### Steps to reproduce

Set a global `actionTimeout` for your project in the playwright config.

Set the timeout value for a click action in a test to `<locator>.click({ timeout: 0 });

Observe that it uses the global defined value, rather than 0.

### Expected behavior

The click action should not have a timeout.

### Actual behavior

The click action follows the global timeout even though it is explicitly set to 0.

### Additional context

See:
https://github.com/pixiebrix/pixiebrix-extension/pull/8823/files

_No response_

### Environment

```shell
System:
    OS: macOS 14.5
    Memory: 72.89 MB / 16.00 GB
  Binaries:
    Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.5.1/bin/yarn
    npm: 10.2.5 - ~/.nvm/versions/node/v20.5.1/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by yury-s** [comment]
Can you share a reproduction example, so that we could try it locally?

I tried the following:
```js
import {expect, test} from '@playwright/test';

test.use({
  actionTimeout: 1000,
})

test('test', async ({page}) => {
    await page.goto('https://playwright.dev/');
    await page.locator('text=Get Started1').click({ timeout: 0 });
});
```
When calling `.click({ timeout: 0 });` the action is running until the test times out (configured via [TestConfig.timeout](https://playwright.dev/docs/api/class-testconfig#test-config-timeout)). If I call `.click();` instead, there action times out after 1000ms, i.e. the global actionTimeout.

**Comment by fungairino** [comment]
After reviewing [the docs again](https://playwright.dev/docs/api/class-testoptions#test-options-action-timeout), I realize that I have misunderstood what the value of 0 means for timeout. I had wrongly assumed that `0` would mean no retry, rather than no limit in the case where you define it within the test. Maybe you could consider updating the main test timeout page with information on what `0` means for a timeout value.

It would be nice to be able to distinguish the two for cases where we want to specifically not retry a locator expectation, for example when we want an outer `expect().toPass` to handle the retries.

I guess instead I should use a non-retrying assertion like `expect(await locator.textContent()).toBe("someText")` in this case to explicitly avoid retry behavior.
