### ISSUE TITLE
[Feature]: use globs, not regex.

### ISSUE THREAD

**Issue by Pomax** [microsoft/playwright#31684]
### 🚀 Feature Request

```
Error: No tests found.
Make sure that arguments are regular expressions matching test files.
You may need to escape symbols like "$" or "*" and quote the arguments.
```

"...sorry, what? Regex? Who in their right mind expects to need to write _regex_??"

### Motivation

We have globs, we don't need regex. If I need all JS files in `src/test` no matter how deeply nested, I write `src/test/**/*.js` and done, that glob will expand into all the files in question.

Using regex is, if you'll pardon the expression, _bonkers_.

**Comment by dgozman** [comment]
@Pomax Thank you for the issue! We do agree that using glob in this particular place is a better choice. However, we are not going to change that to avoid breaking existing users. Sorry for the inconvenience!

**Comment by Pomax** [comment]
Why? Just schedule it for the next major release, that's literally what major releases are for. That's the _whole point_ of semver.

**Comment by dgozman** [comment]
@Pomax Thank you for the suggestion! We are not planning v2 in the short-to-medium term, and we'll come back to this and similar issues once we do.

**Comment by Pomax** [comment]
Fair enough. Sorry to hear, as a testing framework bumping major versions feels like it should be happening a lot (looking at you, Jest) but that's your project's decision to make.
