### ISSUE TITLE
[Feature]: Access fixtures  from custom matchers

### ISSUE THREAD

**Issue by Tallyb** [microsoft/playwright#31682]
### 🚀 Feature Request

Access fixtures (e.g. page, context or custom fixtures) from custom matchers 

### Example

```
export const expect = baseExpect.extend({
  async toMatchPageValue(locator: Locator, options?: { timeout?: number }) {
    const assertionName = 'toMatchPageValue';
    let pass: boolean;
    let matcherResult: any;
    try {
  //******     
     const someValue = await page.evaluate(...)
// *****
      await baseExpect(locator).toHaveAttribute('data-id', String(someValue), options);
      pass = true;
    } catch (e: any) {
      matcherResult = e.matcherResult;
      pass = false;
    }

    const message = ...

    return {
      message,
      pass,
      name: assertionName,
      expected,
      actual: matcherResult?.actual,
    };
  },
});
```

### Motivation

We are storing events data on the page, and I would like to check that an event was called with specific data. 
So the assertion will be something like 
```
await expect('eventName').wasLastCalledWithData({...});
```

The implementation will be: 
```
export const expect = baseExpect.extend({
  async wasLastBeenCalledWith(eventName: string, expectedData: any) {
   await page.evaluate(...) // How can I access page without passing as parameter? 
   // rest of implementation
```

Or maybe it is already accessible, and I just do not know how...

**Comment by Tallyb** [comment]
For now I hacked it by doing the following: 

In a fixture that is creating this structure I attached the page to testInfo
```
// inside a previous fixture
      const testInfo = baseTest.info();      testInfo['page'] = page;
```
And then I accessed it in a similar way in my expect. 

I am not really proud of it 😛

**Comment by dgozman** [comment]
@Tallyb This is a design choice - custom matchers are decoupled from the fixtures and cannot access them. That's why we have `expect(page).toHaveScreenshot()` and not just `expect().toHaveScreenshot()`.

The opposite is possible - you can have a fixture that uses a custom matcher. Perhaps you should implement a fixture like `assertEventWasLastCalledWith: (eventName: string, expectedData: any) => void` and call it in the test?

**Comment by Tallyb** [comment]
OK, I understand. 
I did have a fixture like the one you mentioned, but I thought an expect would look nicer.

**Comment by dgozman** [comment]
> I did have a fixture like the one you mentioned, but I thought an expect would look nicer.

I agree that a custom matcher would look nicer. However, that's the design choice we made, and I don't see us changing it. Thank you for filing the issue! Closing as non-actionable, unfortunately.
