### ISSUE TITLE
[Docs]: basic example errors out

### ISSUE THREAD

**Issue by Pomax** [microsoft/playwright#31683]
### Page(s)

README.md

### Description

The basic example shows the following code:

```js
import { test } from '@playwright/test';

test('Page Screenshot', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  await page.screenshot({ path: `example.png` });
});
```

However, if I run `npm install @playwright/test`, then run `npx playwright install`, and then `node test.js` where that file only contains the content specified by the readme, node errors out going:

```
C:\Users\Mike\Documents\Git\released\custom-file-tree>node  test\test.js    
C:\Users\Mike\Documents\Git\released\custom-file-tree\node_modules\playwright\lib\common\testType.js:71
      throw new Error([`Playwright Test did not expect ${title} to be called here.`, `Most common reasons include:`, `- You are calling ${title} in a configuration file.`, `- You are calling ${title} in a file that is imported by the configuration file.`, `- You have two different versions of @playwright/test. This usually happens`, `  when one of the dependencies in your package.json depends on @playwright/test.`].join('\n'));
            ^

Error: Playwright Test did not expect test() to be called here.
Most common reasons include:
- You are calling test() in a configuration file.
- You are calling test() in a file that is imported by the configuration file.
- You have two different versions of @playwright/test. This usually happens
  when one of the dependencies in your package.json depends on @playwright/test.
    at TestTypeImpl._currentSuite (C:\Users\Mike\Documents\Git\released\custom-file-tree\node_modules\playwright\lib\common\testType.js:71:13)
    at TestTypeImpl._createTest (C:\Users\Mike\Documents\Git\released\custom-file-tree\node_modules\playwright\lib\common\testType.js:80:24)
    at C:\Users\Mike\Documents\Git\released\custom-file-tree\node_modules\playwright\lib\transform\transform.js:256:12
    at file:///C:/Users/Mike/Documents/Git/released/custom-file-tree/test/test.js:3:1
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.11.0
```

Also note that if you're going to tell people what the likely cause is: just check for them and tell them whether that _is_ the cause or not. You can trivially exec `npm list --all` and then check the output to see if there are multiple (not-deduped) entries for `@playwright/test` for the user, so you can _tell_ them whether there's a conflict or not.

(in this case, there isn't, this is a new project dir with playwright and nothing else)

**Comment by dgozman** [comment]
@Pomax I'd recommend to read the ["Getting Starting" guide](https://playwright.dev/docs/intro) and things like this will be clear. Thank you for filing the issue!

**Comment by Pomax** [comment]
That's not how README's work though. They show the basics, with working examples, and if you need to read a different doc first, then the README does not show enough. If someone needs to make sure the code is in a specifically named filed, in a specific directory, then you add that as lead-in to the example code in the README.

**Comment by dgozman** [comment]
@Pomax Thank you for the suggestion!

Right above the examples the README says:

> To learn how to run these Playwright Test examples, check out our [getting started docs](https://playwright.dev/docs/intro).

I don't think we want to copy the whole Getting Started guide into the README. We expect all of our users to go to https://playwright.dev/ to learn about Playwright.

I'll close this issue since there is no action item for Playwright.
