### ISSUE TITLE
[Bug]: page.route invalid when matching URL

### ISSUE THREAD

**Issue by ak47yui** [microsoft/playwright#31680]
v1.45.1

### Steps to reproduce
````
def route_PlayDeal(route):
    print('route_PlayDeal')
    response = route.fetch() 
    print(response.text())
    route.fulfill(response=response) 
    return

page.route('**/PlayDeal.do?*',route_PlayDeal) 
page.goto('https://www.xxx-test.com/PlayDeal.do?1CYB91O9DoRRR+cibfLTKDeKnzrvA95mwEwUPPFf8O/ZtIlNasUcdKcKmr1mtKmXERyIHSq6oiB29x/vj78LhoBP4o0661PwVaqC5H6Rytk=')
````

### Expected behavior

Expected function route_PlayDeal be called

### Actual behavior

But nothing happened

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz
    Memory: 8.38 GB / 15.95 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.91.1 - C:\Users\lsxy\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
```

**Comment by dgozman** [comment]
@ak47yui We have to reproduce this issue locally to be able to debug it. Unfortunately, I cannot reproduce with the snippet above, because the url does not open anything. Could you please provide a full repro?

**Comment by pavelfeldman** [comment]
We would need exact steps to follow in order to address this. It includes the code snippet that we can run locally to demonstrate the problem.
