### ISSUE TITLE
[Bug]: Generated Playwright locator is not unique

### ISSUE THREAD

**Issue by fabianboth** [microsoft/playwright#31695]
### Version

1.45

### Steps to reproduce

On the website https://rausch-bettenhaus.de/, generate a locator for the href (associated with the star image) of the Haustex Star price at the center of the page (see images).

![image](https://github.com/user-attachments/assets/44b59c99-48f9-40e4-a630-f8869fc6a58a)
![image](https://github.com/user-attachments/assets/f8ce835b-7710-4a4a-b22a-ac802e84223d)

Then using this locator in a playwright test or similar:
```
await page.goto("https://rausch-bettenhaus.de/");
await page.waitForLoadState();

const locator = page.getByRole("link", { name: "Bild Haustexstar" });
await locator.click();
```

### Expected behavior

Correctly clicks the previously located element

### Actual behavior

Results in non-unique locator error

```
Error: locator.click: Error: strict mode violation: getByRole('link', { name: 'Bild Haustexstar' }) resolved to 2 elements:
1) <a tabindex="0" href="[https://rausch-bettenhaus.de/…>…](https://rausch-bettenhaus.de/%E2%80%A6%3E%E2%80%A6) aka getByRole('link', { name: 'Bild Haustexstar 2020 vorbildliche Neupositionierung' })
2) <a href="[https://rausch-bettenhaus.de/2020/01/haust…>…](https://rausch-bettenhaus.de/2020/01/haust%E2%80%A6%3E%E2%80%A6) aka getByRole('link', { name: 'Bild Haustexstar 2020', exact: true })
```

The initially proposed locator should have apparently been `getByRole('link', { name: 'Bild Haustexstar 2020', exact: true }` since both elements contain the text Bild Haustexstar.

### Environment

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
    Memory: 18.95 GB / 31.05 GB
    Container: Yes
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 9.0.6 - ~/.nvm/versions/node/v20.9.0/bin/pnpm
  IDEs:
    VSCode: 1.90.1 - /snap/bin/code
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  # playwright managed by pnpm
```

**Comment by dgozman** [comment]
@fabianboth It looks like `getByRole('link', { name: 'Haustex Star' })` is unique, but `page.getByRole("link", { name: "Bild Haustexstar" })` is not. The following snippet works for me, but the one you've shared above doesn't.

```ts
  await page.goto("https://rausch-bettenhaus.de/");
  await page.getByRole('link', { name: 'Haustex Star' }).click();
```

I'd recommend to `generateLocator()` for the `Bild Haustexstar` as well, instead of creating one manually. Let me know whether that helps.

**Comment by fabianboth** [comment]
Thank you for pointing that out! 
The locator `getByRole('link', { name: 'Bild Haustexstar' })` was actually obtained from an older playwright version, and I did not notice the difference to the now correct locator that I get with the `generateLocator` function in the current playwright version.
