### ISSUE TITLE
[I'm facing screen resolution issue on the server how i can fix that issue so i will have same screen size as on server screen size.]

### ISSUE THREAD

**Issue by ramprakashyadav** [microsoft/playwright#31704]
### Please do not submit this issue.

- [X] I understand

**Comment by ramprakashyadav** [comment]
![home_page1](https://github.com/user-attachments/assets/7b9f427f-3ba9-45f4-8a5e-0b566c28e48a)
i attached the screenshot for my server. i want same screen size as server. can anyone help me with this.

**Comment by dgozman** [comment]
This issue tracker is reserved for bug reports and feature requests.

For anything else, such as questions or getting help, please see:
- [The Playwright documentation](https://playwright.dev/)
- [Our Discord server](https://aka.ms/playwright/discord)
