### ISSUE TITLE
[Feature]: Ability to View Trace Diffs on Snapshots for Visual Testing

### ISSUE THREAD

**Issue by udaypatel1** [microsoft/playwright#31716]
### 🚀 Feature Request

Playwright Version: `^1.28.1`

When using visual tests to compare a new snapshot with an existing snapshot, the default (auto-generated)`/test-results` folder only contains `{...}-actual.png` and `{...}-expected.png` when a particular test fails. These images are shown when a user runs `npx playwright show-report` and views the failed visual test.

I would like the ability to also view the trace diff of both images and see exactly what the difference was between the actual and expected images. I am struggling to see minor differences between the actual and expected images and having a `{...}-diff.png` file would be very informative to solve that issue.

### Example

![image](https://github.com/user-attachments/assets/4f695edc-6683-4ed9-be17-27196cf5c242)

There would be an additional file in `/test-results` which would show the diff between the actual image and the expected image, clearly highlighting the change that occurred.

![image](https://github.com/user-attachments/assets/9cf5c9c6-d596-460f-be0a-f774bd0dd41c)

For instance, there would be another column here showing the diff of both images, not just the actual and expected images.

### Motivation

Users will be able to quickly identify minor changes in two images which made the test fail instead of having to carefully sift through the actual and expected images given in the `/test-results` folder.

**Comment by dgozman** [comment]
@udaypatel1 Playwright does already generate the `-diff` image when comparing two screenshots. If that's not the case for you, could you please provide a repro that we can run locally that shows the problem?

**Comment by udaypatel1** [comment]
@dgozman - could you please provide a link on the Playwright Docs where it describes this feature? I am unable to find it.

Thank you!

**Comment by dgozman** [comment]
@udaypatel1 There is no documentation page that is dedicated specifically to the diff. [Here is an example](https://playwright.dev/docs/test-ui-mode#attachments) in the UI mode guide that shows Actual, Expected and Diff. Basically, diff is generated by default when screenshot does not match, you don't need to enable any feature for this.

**Comment by udaypatel1** [comment]
@dgozman - It looks like you already made the exact change that I need @ https://github.com/microsoft/playwright/pull/20208

I have full page screenshots that, because of some UI change, have different dimensions which is why the current version of Playwright is not showing me the `diff` in `test-results/`.

It looks like I will have to upgrade my version of Playwright.

Thank you very much!

**Comment by dgozman** [comment]
@udaypatel1 Yep, that makes sense. Happy upgrading!
