### ISSUE TITLE
[Feature]: Expose server/recorder in playwright-core

### ISSUE THREAD

**Issue by craigmulligan** [microsoft/playwright#31713]
### 🚀 Feature Request

I'm currently building out an alternative code-generator which is driven by LLM's I'm constructing an actions log very similar to [recorderActions](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/recorder/recorderActions.ts) and then hoping to feed it into to one of the [code generators](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/recorder/codeGenerator.ts) to generate tests. 

Unfortunately playwright-core doesn't export the code/types from that module.

### Example

Ideally i'd like to do something like: 

```javascript
import { Action, JavaScriptLanguageGenerator } from 'playwright-core'

const actions: Action[] = generateMyActions()
const languageGenerator = new JavascriptLanguageGenerator(false)

// generate code. 
const output = actions.map(languageGenerator.generateAction)
```

### Motivation

This would allow better of the existing playwright code.

**Comment by dgozman** [comment]
@craigmulligan Playwright is open source, so I'd recommend to copy code generator files and modify them to your liking. Playwright is not going to expose code generator as an API. Thank you for filing the issue!
