### ISSUE TITLE
[Bug]: playwright execute timeout error under ARM architecture server

### ISSUE THREAD

**Issue by kewinchq** [microsoft/playwright#31719]
### Version

1.21.1 1.3x 1.4x

### Steps to reproduce

1）arm架构服务器里，直接在Ubuntu基础镜像里，安装playwright
FROM hub.mingyuanyun.com/tools/ecc:ubuntu-jdk8
RUN bash && source /etc/profile &&  apt-get install libxkbcommon-dev libgbm-dev -y  
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
RUN source ~/.bashrc &&  nvm install 20 && npx -y playwright@1.44.0 install 

2）创建一个脚本文件tests/foo.spec.js

const { test, expect } = require('@playwright/test');

test('basic test', async ({ page }) => {
  await page.goto('https://www.baidu.com');
  await expect(page).toHaveTitle('百度一下，你就知道');
});

3）安装好后执行测试，然后执行命令npx playwright test，执行超时

<img width="1491" alt="image" src="https://github.com/user-attachments/assets/fbda9f6f-9f8f-41b1-9848-e8a32c6de009">

主要错误是操作系统页大小问题，x86下正常使用，arm下有问题，当前的arm服务器是64k页大小
[FATAL:partition_root.cc(964)] Check failed: (internal::SystemPageSize() == (size_t{1} << 12)) || (internal::SystemPageSize() == (size_t{1} << 14))

### Expected behavior

npx playwright test能验证通过
<img width="872" alt="image" src="https://github.com/user-attachments/assets/db3adc9e-c2d2-4f9c-b34a-d590cf546699">

### Actual behavior

<img width="1336" alt="image" src="https://github.com/user-attachments/assets/453c5252-1408-4aa7-9dbf-d9fbcfe4aa57">

[FATAL:partition_root.cc(964)] Check failed: (internal::SystemPageSize() == (size_t{1} << 12)) || (internal::SystemPageSize() == (size_t{1} << 14))

### Environment

```shell
4.19.90-2110.8.0.0119.oe1.aarch64 #1 SMP Wed Oct 27 10:35:51 UTC 2021 aarch64 GNU/Linux
```

**Comment by dgozman** [comment]
This is an upstream Chromium issue: https://issues.chromium.org/issues/328286661. I'll close this one since there is no action item for Playwright here. Thank you for filing!
