### ISSUE TITLE
[Bug]: 'Page.screenshot: Target crashed' error occurred occasionally when taking screenshots with page

### ISSUE THREAD

**Issue by 9nehS** [microsoft/playwright#31720]
### Version

1.45.0

### Steps to reproduce

In our daily usage with Python, we created 4 threads in our main thread, each thread creates its own playwright related browser, context and page with a member function like following:
<img width="870" alt="Screenshot 2024-07-17 at 15 35 09" src="https://github.com/user-attachments/assets/0a14699c-efd6-4624-a8b2-9a6e5feccee8">
`# self._tl is threading.local() object`
`# Currently we only use Chromium`

Each thread will login our WEB site and then wait for maximum 3 hours. And there is a WEB API which will decide which thread to process user request when called. During processing user request, some sceenshots will be taken using page.screenshot().

### Expected behavior

Most of the time, page.screenshot() worked fine.

### Actual behavior

Sometimes, page.screenshot() failed with following error:
`Page.screenshot: Target crashed
Call log:
taking page screenshot`

### Environment

```shell
System:
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.19045 Build 19045
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Manufacturer	Intel(R) Client Systems
System Model	NUC11PAHi7
System Type	x64-based PC
System SKU	RNUC11PAHi7000
Processor	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, 2803 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Intel Corp. PATGL357.0041.2021.0811.1505, 2021-08-11
SMBIOS Version	3.3
Embedded Controller Version	3.03
BIOS Mode	UEFI
BaseBoard Manufacturer	Intel Corporation
BaseBoard Product	NUC11PABi7
BaseBoard Version	K90104-305
Platform Role	Desktop
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	China
Hardware Abstraction Layer	Version = "10.0.19041.3636"
User Name	Not Available
Time Zone	China Standard Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.6 GB
Available Physical Memory	3.74 GB
Total Virtual Memory	29.2 GB
Available Virtual Memory	4.59 GB
Page File Space	13.6 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	On
Virtualization-based security	Not enabled
Device Encryption Support	Elevation Required to View
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes


Python:
3.11.2
```

**Comment by 9nehS** [comment]
Just add more comments, at first, we encountered the same issue with https://github.com/microsoft/playwright/issues/28995, after upgrading playwright from 1.44.0, to 1.45.0, the hanging issue was gone. But it looked like a new issue happened which is not blocking, for it only caused screenshot failure.

**Comment by dgozman** [comment]
@9nehS Well, the browser crashes while rendering your page. I don't think there is much Playwright can do here.

If you run with `DEBUG=pw:browser` environment variable and see a useful stack trace there, we can file an upstream issue against Chromium.

**Comment by 9nehS** [comment]
After I changed browser from Chromium to Edge, the browser crashing issue didn't happen anymore:
`self._tl.browser = self._tl.playwright.chromium.launch(channel='msedge', headless=False, args=['--start-maximized'])`
