### ISSUE TITLE
[Bug]: Reporter don't display correct test location with dynamically created tests.

### ISSUE THREAD

**Issue by floriangosse** [microsoft/playwright#31722]
### Version

1.45.2

### Steps to reproduce

1. Create helper file that contains parameterized test cases:

```ts
// helpers.ts
export function testPageLoading(path: string) {
	test('should load page successfully', async ({ page }) => {
        const response = await page.goto(path);
        expect(response?.status()).toBe(200);
        expect(response?.ok()).toBe(true);
    });
}
```

2. Create test case
```ts
// AboutPage.spec.ts
import { testPageLoading } from './helpers';

describe('AboutPage', () => {
	testPageLoading('/about/');
});
```

3. Run the test

### Expected behavior

The reporter should print `About.spec.ts` as the location of the test.

```txt
AboutPage.spec.ts › AboutPage › should load page successfully
```

It might be necessary to drop the line and column information as it might not be possible to give a precise location.

### Actual behavior

The reporter prints `helpers.ts` as location of the test.

```txt
helpers.ts:3:9 › AboutPage › should load page successfully
```

### Additional context

The location where the file path is "assembled": https://github.com/microsoft/playwright/blob/e11c0c0cbb177fbf4fd208f181b99ba5f6109f9e/packages/playwright/src/reporters/base.ts#L411-L413

It might be possible to travel up the parents/suites to get the title of the suite with the type `file` and use the path of the suite instead of the location of the test case.

### Environment

```shell
System:
  OS: macOS 14.5
  CPU: (10) arm64 Apple M1 Max
  Memory: 738.06 MB / 64.00 GB
Binaries:
  Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
  Yarn: 1.22.22 - ~/.nvm/versions/node/v18.20.2/bin/yarn
  npm: 10.8.1 - ~/.nvm/versions/node/v18.20.2/bin/npm
IDEs:
  VSCode: 1.91.1 - /Applications/Visual Studio Code.app/Contents/Resources/app/bin/code
Languages:
  Bash: 3.2.57 - /bin/bash
npmPackages:
  @playwright/test: 1.45.2 => 1.45.2
```

**Comment by dgozman** [comment]
@floriangosse We do not recommend to wrap the `test()` function for this exact reason. We have iterated on this topic a while ago, and I don't think we'll change the behavior now to avoid breaking existing users.

We recommend using [test fixtures](https://playwright.dev/docs/test-fixtures) or calling a helper function from inside the test.

**Comment by floriangosse** [comment]
Thanks for you quick feedback. Didn't thought about the fixtures and I'm not sure if it would be the right solution as it is quite verbose in case you have not only create one test case but multiple ones with a function.

In case you reconsidering this topic, I would be happy to help you.
