### ISSUE TITLE
Is there a way to keep testInfo.annotations.push in the report with the test failed when the beforeEach block fails?

### ISSUE THREAD

**Issue by josego1984** [microsoft/playwright#31731]
### Please do not submit this issue.

- [X] I understand

**Comment by josego1984** [comment]
I use Xray to manage my tests and I use the testInfo.annotations.push to add the test ID and then link the results. I found out that if the beforeEach block fails, then in the report the test won't have the test ID:

Example of a test with the annotation:

```
test('Edit an upload lookup', { tag: ['@high', '@WT-341'] },
        async ({ page, lookupManagementPage, lookupEditionPage,
                   notifications, lookupsHelpers }, testInfo) => {
        testInfo.annotations.push({type: 'test_key', description: 'WT-341'});
```

The report would be something like this:

```
<testcase name="Tests that call the API to prepare data › Edit an upload lookup" classname="dataSearch/lookupManagement/lookupManagement.spec.js" time="62.36">
<failure message="lookupManagement.spec.js:163:9 Edit an upload lookup" type="FAILURE">
<![CDATA[  [Google Chrome] › dataSearch/lookupManagement/lookupManagement.spec.js:163:9 › Tests that call the API to prepare data › Edit an upload lookup 
```

Instead of something like this:

```
<testcase name="Tests that depend on lomana and lookups-api in the environment › Lookup deleted after creation fails" classname="dataSearch/lookupManagement/lookupManagement.spec.js" time="36.097">
<properties>
<property name="test_key" value="WT-809">
</property>
</properties>
```

Is there a way fix this?

**Comment by dgozman** [comment]
Take a look [at the documentation](https://playwright.dev/docs/test-annotations#annotate-tests) for annotating tests.

---

This issue tracker is reserved for bug reports and feature requests.
For anything else, such as questions or getting help, please see:
- [The Playwright documentation](https://playwright.dev/)
- [Our Discord server](https://aka.ms/playwright/discord)
