### ISSUE TITLE
[Bug]:  Running Playwright in NextJS Docker

### ISSUE THREAD

**Issue by hassanedelbi** [microsoft/playwright#31746]
### Version

1.45.1

### Steps to reproduce

1. Build Docker
`docker build --no-cache -t plrt-next .`
2. Run Docker
`docker run -p 3000:3000 plrt-next`
3. POST @ http://localhost:3000/news/api/title (using postman) OR go to http://localhost:3000/news/en and press get title

### Expected behavior

I expect playwright to be called and send the title 

### Actual behavior

i get this error 
 ✓ Ready in 29ms
Error: browserType.launch: Executable doesn't exist at /nonexistent/.cache/ms-playwright/firefox-1454/firefox/firefox
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
    at p (/app/.next/server/app/api/title/route.js:1:533)
    
    
    there is 2 issues : 
    1. why is it checking /nonexistent ? 
    2. the Executable doesn't exist even if path hardcoded to /root

### Environment

```shell
System:
  OS: Linux Debian GNU/Linux 11 (bullseye)
  CPU: (8) arm64
Binaries:
  Node: 20.15.1 - /usr/local/bin/node
  npm: 10.7.0 - /usr/local/bin/npm
npmPackages:
  playwright: 1.45.1
```

**Comment by hassanedelbi** [comment]
Some references i tried:
https://github.com/microsoft/playwright/issues/30371
https://github.com/microsoft/playwright/issues/29960
by @mxschmitt

**Comment by mxschmitt** [comment]
The issue in this case was that you were installing the browsers as `root` but you were running Playwright as a different user. So for that you can either install browser as the specific user or install them as `root` and use the env below to point them into a shared directory. Looking at the following makes it work for me:

```diff
diff --git a/Dockerfile b/Dockerfile
index 2f56421..97395a1 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -7,12 +7,6 @@ FROM base AS deps
 # Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
 # TODO: Check if this might node be needed for non alpine images
 RUN apt-get update && apt-get install -y libc6
-# Install Firefox dependencies - Playwright
-RUN apt-get update && apt-get install -y --no-install-recommends \
-    libdbus-glib-1-2 \
-    libxt6 \
-    libpci-dev
-
 
 WORKDIR /app
 
@@ -32,9 +26,6 @@ WORKDIR /app
 COPY --from=deps /app/node_modules ./node_modules
 COPY . .
 
-# Install Playwright with all necessary dependencies
-RUN npx -y playwright@1.45.1 install --with-deps firefox
-
 # Next.js collects completely anonymous telemetry data about general usage.
 # Learn more here: https://nextjs.org/telemetry
 # Uncomment the following line in case you want to disable telemetry during the build.
@@ -56,7 +47,7 @@ ENV NODE_ENV production
 # ENV NEXT_TELEMETRY_DISABLED 1
 
 RUN addgroup --system --gid 1001 nodejs
-RUN adduser --system --uid 1001 nextjs
+RUN adduser --uid 1001 nextjs --disabled-password --gecos "" --ingroup nodejs
 
 COPY --from=builder /app/public ./public
 
@@ -69,6 +60,9 @@ RUN chown nextjs:nodejs .next
 COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
 COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
 
+ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
+RUN npx -y playwright@1.45.0 install --with-deps firefox && \
+    chown -R nextjs:nodejs /ms-playwright
 
 USER nextjs
 ```

I also had to give your user a home directory, since thats what browsers need to work with.

**Comment by hassanedelbi** [comment]
> The issue in this case was that you were installing the browsers as `root` but you were running Playwright as a different user. So for that you can either install browser as the specific user or install them as `root` and use the env below to point them into a shared directory. Looking at the following makes it work for me:
> 
> ```diff
> diff --git a/Dockerfile b/Dockerfile
> index 2f56421..97395a1 100644
> --- a/Dockerfile
> +++ b/Dockerfile
> @@ -7,12 +7,6 @@ FROM base AS deps
>  # Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
>  # TODO: Check if this might node be needed for non alpine images
>  RUN apt-get update && apt-get install -y libc6
> -# Install Firefox dependencies - Playwright
> -RUN apt-get update && apt-get install -y --no-install-recommends \
> -    libdbus-glib-1-2 \
> -    libxt6 \
> -    libpci-dev
> -
>  
>  WORKDIR /app
>  
> @@ -32,9 +26,6 @@ WORKDIR /app
>  COPY --from=deps /app/node_modules ./node_modules
>  COPY . .
>  
> -# Install Playwright with all necessary dependencies
> -RUN npx -y playwright@1.45.1 install --with-deps firefox
> -
>  # Next.js collects completely anonymous telemetry data about general usage.
>  # Learn more here: https://nextjs.org/telemetry
>  # Uncomment the following line in case you want to disable telemetry during the build.
> @@ -56,7 +47,7 @@ ENV NODE_ENV production
>  # ENV NEXT_TELEMETRY_DISABLED 1
>  
>  RUN addgroup --system --gid 1001 nodejs
> -RUN adduser --system --uid 1001 nextjs
> +RUN adduser --uid 1001 nextjs --disabled-password --gecos "" --ingroup nodejs
>  
>  COPY --from=builder /app/public ./public
>  
> @@ -69,6 +60,9 @@ RUN chown nextjs:nodejs .next
>  COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
>  COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
>  
> +ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
> +RUN npx -y playwright@1.45.0 install --with-deps firefox && \
> +    chown -R nextjs:nodejs /ms-playwright
>  
>  USER nextjs
> ```
> 
> I also had to give your user a home directory, since thats what browsers need to work with.


Thank you, 
I figured it out earlier by using the whole docker image like this:

```diff
- FROM base AS runner
+ FROM mcr.microsoft.com/playwright:v1.45.1-jammy AS runner
```
but using only the firefox is more convenient
