### ISSUE TITLE
[Docs]: Show how to share `yarn`, `npm`, `npx playwright` installations to save compute and time

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/playwright#31744]
### Page(s)

https://playwright.dev/docs/test-sharding

### Description

I've been checking out test sharding and it looks really interesting, but I noticed there's a lot of repeated work between different jobs.

It'd be nice if all shards could use the same installation, for example, both for `yarn` or `npm`, and `npx playwright install --with-deps`, to reduce computation.

That'd cut develop times for quicker feedback, and reduce costs.

**Comment by hamirmahal** [comment]
For example, each of the 4 shards at https://github.com/hamirmahal/test-playwright-sharding/actions/runs/9982451674/job/27588193201 take over 30 seconds to repeat the same `npx playwright install --with-deps` step.

It'd be nice if we could do that step once, and each shard could use the same installation to avoid repeated work.

**Comment by dgozman** [comment]
@hamirmahal This heavily depends on your CI. For GitHub, you are probably looking for [something like this](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows)?

**Comment by hamirmahal** [comment]
[setup-node](https://github.com/actions/setup-node#caching-global-packages-data) looks promising for caching `yarn` and `npm install`.

I think it'd be useful if the docs had a working example that cached all installations, including `npx playwright install --with-deps`.

**Comment by mxschmitt** [comment]
"--with-deps" installs operating system dependencies, they are unfortunately uncacheable see [here](https://playwright.dev/docs/ci#caching-browsers).

**Comment by deyjoy** [comment]
@mxschmitt @yury-s Could you please review this pull request? I have added documentation on sharing Playwright installations to reduce redundant work and save computation time as per issue #31744. Thank you!

**Comment by mxschmitt** [comment]
Closing as per https://github.com/microsoft/playwright/pull/31787#discussion_r1685677124 and https://github.com/microsoft/playwright/issues/31744#issuecomment-2238603993.
