### ISSUE TITLE
[Feature]: Get the current UserAgent

### ISSUE THREAD

**Issue by 304NotModified** [microsoft/playwright#31743]
### 🚀 Feature Request

We can set the useragent, but we can't get the current user-agent without Page.Evaluate.

Brower.UserAgent or BrowserContext.UserAgent property would be great. 

### Motivation

I like to replace "HeadlessChrome" with "Chrome" in the user agent as the web application firewall (WAF) blocks the HeadlessChrome requests.

**Comment by dgozman** [comment]
@304NotModified As you correctly pointed out, `Page.Evaluate('navigator.userAgent')` is the way to get the current user agent. I don't think exposing a dedicated API for that is justified.

**Comment by 304NotModified** [comment]
Well the problem is that we need to start first the browser and create a page, isn't? That makes it a slow start and it sounds like a work around?

**Comment by mxschmitt** [comment]
Playwright by default uses the use-agent of the underlying browser if you don't specify one, so there seems no way of doing this technically without starting the browser. e.g. if you use Chrome, it will use Google Chrome's UA. If you specify one in the context options, then it uses this one / its also available via the fixtures.

**Comment by mxschmitt** [comment]
Closing as per above.
