### ISSUE TITLE
[BUG] Network.emulateNetworkConditions' wasn't found

### ISSUE THREAD

**Issue by DJ-Glock** [microsoft/playwright#3175]
**Context:**
- Playwright Version: 1.2.1
- Operating System: Windows
- Node version: 12.16.2
- Browser: Chromium (85.0.4182.0)

**Code Snippet**
```
    const session = await browser.newBrowserCDPSession();

    await session.send('Network.emulateNetworkConditions', {
      offline: false,
      downloadThroughput: (25 * 1024) / 8,
      uploadThroughput: (5 * 1024) / 8,
      latency: 1000,
    });
    await session.detach();
```

**Description**
I tried to emulate network conditions in both headful and headless modes, but got an error:
```
Protocol error (Network.emulateNetworkConditions): 'Network.emulateNetworkConditions' wasn't found' details='Protocol error (Network.emulateNetworkConditions): 'Network.emulateNetworkConditions' wasn't foundError: 
    at D:\...\e2e\node_modules\playwright-chromium\lib\chromium\crConnection.js:131:63
    at new Promise (<anonymous>)
    at CRSession.send (node_modules\playwright-chromium\lib\chromium\crConnection.js:130:16)
    at CRSession.send (node_modules\playwright-chromium\lib\helper.js:79:31)
    at MainPage.emulateNetworkThrottling (src\Pages\General\BasePageObject.ts:165:19)
    at Context.<anonymous> (src\Tests\...\....e2e.ts:17:5)' captureStandardOutput='true' flowId='1140'
```

What's wrong here? It could be related to https://github.com/microsoft/playwright/issues/2311 but not sure.

**One more thing**
By the way, when I tried to create CDP session using browser context:
`const session = await page.context().newCDPSession(page);
`

I got:
`Property 'newCDPSession' does not exist on type 'BrowserContext'.ts(2339)
`

Is it obsolete method?
https://playwright.dev/#version=v1.2.1&path=docs%2Fapi.md&q=chromiumbrowsercontextnewcdpsessionpage

**Comment by aslushnikov** [comment]
> I tried to emulate network conditions in both headful and headless modes, but got an error:

@DJ-Glock This will return you a *browser* session, where's network domain is actually on the *page* session.  Please read the [getting started with chrome devtools protocol](https://github.com/aslushnikov/getting-started-with-cdp) for details. 

> By the way, when I tried to create CDP session using browser context:

The following worked just fine for me (in JS though, not in TS):

```js
const {firefox, chromium, webkit} = require('.');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  const session = await context.newCDPSession(page);
  await browser.close();
})();
```

**Comment by JoelEinbinder** [comment]
> EDITED: it looks like we have missing types for the `newCDPSession` method on the context. +cc @JoelEinbinder

We decided that users have to cast to ChromiumBrowserContext in order to get those types.

**Comment by DJ-Glock** [comment]
@aslushnikov @JoelEinbinder thanks for clarification. ChromiumBrowserContext worked for me fine.
