### ISSUE TITLE
[Bug]: Combine Playwright Test plugin with multiple environments 

### ISSUE THREAD

**Issue by mareru** [microsoft/playwright#31753]
### Version

1.45.2

### Steps to reproduce

Does this issue occur when all extensions are disabled?: Yes/No

VS Code Version: 1.91.1
OS Version: Windows 11
Steps to Reproduce:
I followed these guidelines:
https://chatgpt.com/share/3f4321a4-b060-4b31-b66d-f41f837205cf

But NODE_ENV variable is undefined no matter what I do.

Can you please help? It seems like it is not being passed to the plugin with the launch.json configuration for some reason

### Expected behavior

I would like to be able to choose the launch config with the appropriate environment and just click the play button from the Playwright Test plugin and have my tests run on according env.

### Actual behavior

NODE_ENV variable is undefined no matter what I do and therefor the according .env.staging file is not loaded

### Additional context

Sorry if this is not the right place to ask the question, but maybe you could guide me in the right direction

### Environment

```shell
VS Code Version: 1.91.1
OS Version: Windows 11
```

**Comment by dgozman** [comment]
@mareru You are probably [looking for this](https://github.com/microsoft/playwright/issues/28031#issuecomment-1802780613). In the future, please ask questions on our discord server instead.

---

This issue tracker is reserved for bug reports and feature requests.

For anything else, such as questions or getting help, please see:
- [The Playwright documentation](https://playwright.dev/)
- [Our Discord server](https://aka.ms/playwright/discord)

**Comment by mareru** [comment]
Yes, this helped, thanks. Sorry for reaching out here, I did go to Discord but wasn't that lucky. I guess I will need to do my search better the next time in the issues you have here on GitHub :) 
Apologizes once again and thanks for helping
