### ISSUE TITLE
[Bug]: how to get the host window size in playwright

### ISSUE THREAD

**Issue by fancy45daddy** [microsoft/playwright#31758]
### Version

1.41.1

### Steps to reproduce

```
const browser = await chromium.launch({
    headless: false,
    args: ["--start-maximized"],
});
const context = await browser.newContext({ viewport: null });
const page = await context.newPage();
```

now i want to get the host window size in pixel.
i try page.viewportsize() but it give null

### Expected behavior

give me the host window size in pixel.

### Actual behavior

null

### Environment

```shell
jammy
```

**Comment by dgozman** [comment]
@fancy45daddy You can try `page.evaluate('window.outerWidth')`.

Note that this issue tracker is reserved for bug reports and feature requests.

For anything else, such as questions or getting help, please see:
- [The Playwright documentation](https://playwright.dev/)
- [Our Discord server](https://aka.ms/playwright/discord)
