### ISSUE TITLE
build docker image exception with utils/docker/build.sh

### ISSUE THREAD

**Issue by longzhijian** [microsoft/playwright#31770]
### Please do not submit this issue.

- [X] I understand

**Comment by longzhijian** [comment]
<img width="957" alt="image" src="https://github.com/user-attachments/assets/832c7442-cf84-4028-ad7d-b5e94c364f39">
branch: release-1.45

**Comment by mxschmitt** [comment]
Did you run `npm ci && npm run build` before?
