### ISSUE TITLE
[Feature]: Codegen for branded browsers

### ISSUE THREAD

**Issue by mohan388** [microsoft/playwright#31783]
### 🚀 Feature Request

We are not allowed to use non branded browsers in our organization, the allowed ones are Chrome/MS Edge/Safari. Can we use CodeGen feature to record tests on Edge or Chrome? 

### Example

This would help developers to perform all the automation within available browsers on their machines so the setup would be really quick.

### Motivation

It will avoid strong dependency on Chromium, lot of companies the chromium is not approved as it's not a branded browser.

**Comment by mxschmitt** [comment]
In the terminal you can do

    npx playwright codegen --channel chrome

For VSCode, you need to run a test first, then codegen works with the open browser. To make it work directly, it depends on https://github.com/microsoft/playwright/issues/26777.

**Comment by mohan388** [comment]
Thanks for answering this
