### ISSUE TITLE
[Bug]: playwright fails to print child window title

### ISSUE THREAD

**Issue by nirmalprojects1988** [microsoft/playwright#31788]
### Version

1.45.1

### Steps to reproduce

Here I am providing the code that I used to print the child window title. My code intention is to print the child window title and once the playwright closes the child window then I need to make sure I am at the parent window.
test('working with new popup window', async({page}) => {
    
  await page.goto('https://rahulshettyacademy.com/AutomationPractice/');
  console.log(await page.title());
  
  const [page1Promise] =await Promise.all([ page.waitForEvent('popup'),
  page.getByRole('button', { name: 'Open Window' }).click()]);
  const page1 = await page1Promise;
  await page1.getByRole('link', { name: 'Access all our Courses' }).click();
 console.log(page1.title);
 page1.close();
  await page.locator('label').filter({ hasText: 'Radio1' }).getByRole('radio').check();
console.log(page.title);
page.close();

});
Note:- This code I've generated using the playwright code gen recorder,I searched on the internet and found to use the browser context and page to work with popup window but i relied to go with the recorder.I just modified the code to print the titles in console.

> 

### Expected behavior

I expect to see the child window title.

### Actual behavior

I dont see the child window title

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 195.27 MB / 8.00 GB
  Binaries:
    Node: 20.14.0 - /usr/local/bin/node
    npm: 10.7.0 - /usr/local/bin/npm
  IDEs:
    VSCode: 1.91.0 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.45.1 => 1.45.1
browser Chromium 1124
```

**Comment by mxschmitt** [comment]
Make sure to await Promises and see here for the docs [for popups](https://playwright.dev/docs/pages#handling-popups). The correct code would be:

```ts
test('working with new popup window', async ({ page }) => {
  await page.goto('https://rahulshettyacademy.com/AutomationPractice/');
  console.log(await page.title());
  await page.getByRole('button', { name: 'Open Window' }).click();
  const page1Promise = page.waitForEvent('popup');
  const page1 = await page1Promise;
  await page1.getByRole('link', { name: 'Access all our Courses' }).click();
  console.log(await page1.title());
  await page.locator('label').filter({ hasText: 'Radio1' }).getByRole('radio').check();
  console.log(await page.title());
});
```

You also don't have to close any pages which are in the default browser context.

**Comment by nirmalprojects1988** [comment]
Thanks for the reply there were two mistakes in my code,one await and title() that i missed .
