### ISSUE TITLE
[Feature]: Is it possible to use system node version for Playwright Java/Python/C#.net 

### ISSUE THREAD

**Issue by mohan388** [microsoft/playwright#31784]
### 🚀 Feature Request

We are not allowed to use node version other than the one installed on development machine, hence we need an option to use locally installed node for all Playwright Language flavours.

### Example

This would help us using approved node binaries

### Motivation

Playwright will be confirmed to enterprise security standards.

**Comment by pavelfeldman** [comment]
Could you share more information on your system purpose and setup?

**Comment by mohan388** [comment]
We allowed to use approved nodejs version only, it's a security violation if we use any other version of the nodejs exe is bundled  playwright dependencies.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
