### ISSUE TITLE
[Feature]: Change the keyboard API to return Promise<this>

### ISSUE THREAD

**Issue by trajano** [microsoft/playwright#31791]
### 🚀 Feature Request

Presently the keyboard operations return `Promise<void>`.  Can it be modified to return `Promise<this>` or `Promise<Keyboard>`  so we can do something like a chain if we wanted

### Example

This is from my post in https://stackoverflow.com/questions/78777386/how-do-i-avoid-then-or-repeated-await-when-chaining-promises-in-typescript  but due to the limitations of typescript my concept would be

```typescript
await page.keyboard.type("username")
  .then((k)=>k.press("Tab"))
  .then((k)=>k.type("password"))
  .then((k)=>k.press("Tab"))
```

### Motivation

It's just to avoid too much repeated code and allow better visualization of how certain groups code code would work together.  That is to avoid

```typescript
await page.keyboard.type("username");
await page.keyboard.press("Tab"));
await page.keyboard.type("password");
await page.keyboard.press("Tab"));
```

**Comment by pavelfeldman** [comment]
Chained APIs are discouraged in our API model.

**Comment by trajano** [comment]
OK FWIW https://stackoverflow.com/a/78777606/242042 shows how it could be done.  It's nice to be able to write tests like this

```typescript
    await myPage
      .type(programName)
      .tab()
      .type(shortName)
      .tab()
      .type(description)
      .tab()
      .type(fee)
      .enter();
```
