### ISSUE TITLE
[Feature]: Provide simplified keyboard API for `tab` and `enter`

### ISSUE THREAD

**Issue by trajano** [microsoft/playwright#31792]
### 🚀 Feature Request

Provide aliases for `tab` and `enter` on the `Keyboard` class.

### Example

Variant of https://github.com/microsoft/playwright/issues/31791

```typescript
await page.keyboard.type("username");
await page.keyboard.tab();
await page.keyboard.type("password");
await page.keyboard.tab();
await page.keyboard.enter();
````

### Motivation

When doing data entry, most people would tab between fields and press `enter` to submit the form.  Though testing on Playwright like this is slow, it is still useful to verifying that tab order is working as expected.

In addition if we had this along with https://github.com/microsoft/playwright/issues/31791 we'd be able to write code as

```typescript
await page.keyboard.type("username")
  .then((k)=>k.tab())
  .then((k)=>k.type("password"))
  .then((k)=>k.tab())
  .then((k)=>k.enter())
```

At present the workaround is to create a domain wrapper like the one I posted in https://stackoverflow.com/questions/78777386/how-do-i-avoid-then-or-repeated-await-when-chaining-promises-in-typescript
```typescript
import { Locator, Page } from "@playwright/test";
class SimplePage {
  constructor(private readonly page: Page) {}
  async type(text: string): Promise<this> {
    await this.page.keyboard.type(text);
    return this;
  }
  async tab(): Promise<this> {
    await this.page.keyboard.press("Tab");
    return this;
  }  
  async enter(): Promise<this> {
    await this.page.keyboard.press("Enter");
    return this;
  }  
}
```

**Comment by pavelfeldman** [comment]
You should not use `type` as it is deprecated. https://playwright.dev/docs/api/class-locator#locator-type Your code should be:

```js
await page.getByRole('input', 'username').fill('username');
await page.getByRole('input', 'password').fill('password');
await page.getByRole('submit').click();
```

**Comment by trajano** [comment]
If that gets deprecated then how would people ensure `tab` order is working as expected?
