### ISSUE TITLE
[Feature]: record network traffic when `codegen`

### ISSUE THREAD

**Issue by cheungseol** [microsoft/playwright#31809]
### 🚀 Feature Request

Is it possible to record all network traffic when using playwright `codegen`?

Record all network requests and responses on pages during `codegen`.

and replay the testcase using the recorded network traffic.

### Motivation

replay the testcase using the recorded network traffic.

**Comment by pavelfeldman** [comment]
Replaying a site based on the network recording is a non-trivial project that requires substantial investment. It falls outside of scope for Playwright at this point.

**Comment by cheungseol** [comment]
> Replaying a site based on the network recording is a non-trivial project that requires substantial investment. It falls outside of scope for Playwright at this point.

I found the  codegen `saveHar` options and `routeFromHAR `  API , can they be useful in these situations ?
