### ISSUE TITLE
[Bug]: The test doesn't fail when comparing screenshots by toHaveScreenshot, provided that the page is actually different

### ISSUE THREAD

**Issue by StanislavGrishaev** [microsoft/playwright#31819]
### Version

1.45.3

### Steps to reproduce

- clone repo https://github.com/StanislavGrishaev/pw-to-have-screenshot-bug
- run `npx playwright test`

### Expected behavior

I expect a test crash and a screenshot with a diff something like this (because it's obvious that there is a difference between the screenshot and the actual page):
![image](https://github.com/user-attachments/assets/b328603e-ea00-4dc4-aa74-fb9bdaa89870)

### Actual behavior

Tests pass successfully

### Additional context

I prepared a version of the application where I caught this problem via both a static HTML page via the SingleFile Chrome plugin (if that matters). The problem is also reproduced on the builded and deployed application.
The problem was also reproduced in Docker on the image `playwright:v1.45.2-focal`

### Environment

```shell
System:
  OS: macOS 14.5
  CPU: (8) arm64 Apple M1 Pro
  Memory: 65.06 MB / 16.00 GB
Binaries:
  Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
  Yarn: 1.22.21 - /opt/homebrew/bin/yarn
  npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
  pnpm: 8.12.1 - ~/Library/pnpm/pnpm
  bun: 1.0.2 - ~/.bun/bin/bun
Languages:
  Bash: 3.2.57 - /bin/bash
npmPackages:
  @playwright/test: ^1.45.3 => 1.45.3
```

**Comment by pavelfeldman** [comment]
Tests pass for me with your expectations, I don't see a massive red diff.

**Comment by StanislavGrishaev** [comment]
@pavelfeldman but there must be a diff. you can look at the screenshot and the html page and you will see that in fact the background color in the html page is different - #FFFFFF in the html and #F2F2F7 in the screenshot.

**Comment by pavelfeldman** [comment]
default pixelmatch settings are probably tolerating the difference.

**Comment by StanislavGrishaev** [comment]
Are there any recommendations for changing the settings at the Playwright level so that pixelmatch detects this diff?

**Comment by StanislavGrishaev** [comment]
figured it out. For those who encounter a similar problem, this in playwright.config.ts should help:
```
    expect: {
        toHaveScreenshot: {
            threshold: 0,
        },
    },
```
because default `threshold` value is 0.2
