### ISSUE TITLE
[Feature] - Ability for global teardown to wait until the reporter generates the report

### ISSUE THREAD

**Issue by IrfanSyed-PSC** [microsoft/playwright#31821]
As a playwright user, I would like to perform global teardown after my reporters have generated the reports. If I do not have the ability to wait for the reports to be generated, I should at least have some context of the results of the test. Having ability to wait until the reports are generated is the right choice. Frameworks like pytest does that. So we should be able to do the same out of the box with playwright.

To upload the results separately after the execution is an effort and sometimes we want to upload to reporting servers which allow us to use some plugins or REST API's to publish to their services. Its does not make it easy to run as a separate step as we define lot of variables from the test.

Is there a way to do that currently in playwright ?

**Comment by pavelfeldman** [comment]
Teardown errors are included into the report. If your teardown is post-report, you should run it as a separate executable after running tests.

**Comment by IrfanSyed-PSC** [comment]
Thank you Pavel. In that case, I see the only option is to extend the Reporter and create a custom reporter and evaulate the generated report. Do you think its a viable solution on a long run ?

**Comment by pavelfeldman** [comment]
That would probably work, but I would not do that - reporters are for reporting. As I mentioned above, if you have a teardown phase outside of the scope of Playwright reporters, you should perform and report on it separately. I.e. as a separate step in your CI/CD.

**Comment by IrfanSyed-PSC** [comment]
Thank you. I will think of that approach.
