### ISSUE TITLE
[Bug]: Screenshots Hang in Headless Deterministic Mode

### ISSUE THREAD

**Issue by Fihy** [microsoft/playwright#31829]
### Version

10.2.3

### Steps to reproduce

```
const browser: ChromiumBrowser = await playwright.chromium.launch({
    headless: true,
    args: [
      //"--disable-web-security",
      "--deterministic-mode",
      //"--hide-scrollbars",
      //"--disable-partial-raster",
      //"--js-flags=--random-seed=11572934977", //
      //"--enable-automation", //
      //"--silent-debugger-extension-api", //
      //"--log-level=0", //
      //"--use-gl=egl",
    ],

...etc    

  let viewport = page.viewportSize();
  console.log(viewport);
  if (!viewport) throw "No viewport";
  const { width, height } = viewport;
  return await page.screenshot({
    animations: "disabled",
    type: "jpeg",
    clip: {
      x: 0,
      y: 0,
      width,
      height,
    },
    quality: 20,
    caret: "hide",
    scale: "css",
    timeout: 120000,
  }); // this hangs
```

Screenshots then taken of pages produced from contexts are subject to hang. 

### Expected behavior

I expect the screenshot to be taken. If I remove the deterministic mode option, the screenshot is taken as normal.

### Actual behavior

The screenshot hangs and times out. It stops at `loaded styles`

### Environment

```shell
Hung on Windows 11 & Ubuntu
```

**Comment by pavelfeldman** [comment]
If you touch `args`, you are on your own!

**Comment by mitar** [comment]
I also hit this issue while trying to achieve deterministic rendering. `--deterministic-mode` implies `--enable-begin-frame-control` plus `--run-all-compositor-stages-before-draw`, so the compositor only draws when the client drives frames over `HeadlessExperimental.beginFrame`. Playwright never does that, so no frames are produced: screenshots hang, and the actionability check (which needs two consecutive frames with the same box) never passes.

I am now trying with:

```
  "--force-color-profile=srgb",
  "--disable-partial-raster",
  "--disable-gpu",
  "--disable-threaded-animation",
  "--disable-checker-imaging",
```
