### ISSUE TITLE
Blocking browser binaries urls 

### ISSUE THREAD

**Issue by mohan388** [microsoft/playwright#31839]
### 🚀 Feature Request

Our security team wanted to block all CDN urls of browser binaries (chromium,Firefox/WebKit/ffmpeg), is there any impact on Playwright features?

### Example

This will prevent downloading softwares from internet.
https://playwright.azureedge.net/builds
https://playwright-akamai.azureedge.net/builds
https://playwright-verizon.azureedge.net/builds

### Motivation

Every developers in compliance with corporate security policy

**Comment by dgozman** [comment]
@mohan388 Playwright only downloads binaries during the `npx playwright install` command. After that, it will never reach to the CDN. Take a look at [downloading browsers from an alternative location](https://playwright.dev/docs/browsers#download-from-artifact-repository) and [downloading browsers through a proxy](https://playwright.dev/docs/browsers#install-behind-a-firewall-or-a-proxy), it might be useful in your case.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
