### ISSUE TITLE
[Feature]: Set browser zoom

### ISSUE THREAD

**Issue by arieluchka-bse** [microsoft/playwright#31836]
### 🚀 Feature Request

We have a method for setting the viewport(window size), but we dont have a built in method to set browser zoom.

Currently, there are two methods (i could find) that can "simulate" browser zoom, but are **very** flunky and at some occasions dont work at all.
1) page.evaluate("document.body.style.zoom=1.25")
2) page.evaluate("document.body.style.transform = 'scale(1.25)'")

both options do achive zooming into the page, but it breaks other playwright capabilities (like clicking on elements).

another thing is that not every website is addapting to these modifications (meaning that a web page will addapt itself when the browser is zoomed manually (ctrl +/ctrl -/ctrl mouse-scroll), but wont addapt themselves when modifying the code (like in the options above)).

maybe its worth checking if the browsers (chrome/firefox/webkit) have the option to control the zoom of the browser itself (and not through js code modifications)

### Example

page.set_zoom_scale(scale=<int>)

### Motivation

1) many people use their browser zoom when navigating the web, and many websites have difficulties addapting to different zoom scales. having a built in, working method to set different zoom scales to **the page/browsers level**, will make it possible for QA and Devs to test their product better.
2) many laptops are defaulting to a specifc screen scale (125%/150%) which, in turn, also affects the browser scale (which can severly impact browser experience). As far as i know, there is no way to set screen scale for linux headless machines. having playwright be cable of setting zoom (at least on the browser level), will make it possible testing applications for laptop users.
![image](https://github.com/user-attachments/assets/50ff1e7d-b794-4f71-b06e-846155452271)

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/2497, please upvote that issue instead.
