### ISSUE TITLE
[Feature] Support raw headers

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright#3184]
We pass headers around as objects. But this doesn't work when you have multiple headers with the same name and different values. We should have an API that supports this.

**Comment by pavelfeldman** [comment]
First of all, thank you for filing this issue. We appreciate your input, in many ways Playwright is based on it. This particular feature request didn't get enough stars for us to prioritize the work on it and hence is being closed. We are a relatively small team and we need to prioritize aggressively to deliver support and new features to you.
