### ISSUE TITLE
[Docs]: Closing all contexts also disconnects the entire browser

### ISSUE THREAD

**Issue by himat** [microsoft/playwright#31849]
### Page(s)

https://playwright.dev/docs/api/class-browsercontext#browser-context-close

### Description

```

  console.log("isconnected: ", remoteBrowser.isConnected()) // true 
  await Promise.all(
    remoteBrowser.contexts().map(async (context) => {
       try {
         await context.close()
         console.log("closed context")
       } catch (err) {
         logger.error("[connectAndInitNewBrowser] Error closing context" + (err as Error).message, {
           err,
         })
       }
    }),
  )
  console.log("all contexts closed")
  console.log("isconnected: ", remoteBrowser.isConnected()) // false 
```

When I run this code, isConnected() ends up being false after all the contexts are closed!

The close documentation says that the default context can't be closed anyway, so this seems like very strange behavior. Closing all the contexts shouldn't disconnect the browser.

**Comment by pavelfeldman** [comment]
Please provide full repro that we can run locally.

**Comment by pavelfeldman** [comment]
We would need exact steps to follow in order to address this. It includes the code snippet that we can run locally to demonstrate the problem.
