### ISSUE TITLE
Unable to use Test.use() at individual test level

### ISSUE THREAD

**Issue by Ransely-Nigrel** [microsoft/playwright#31853]
### Version

1.42.1

### Steps to reproduce

I have a describe block containing 5 test cases , I want to run 2 test cases in headed mode and rest in headless mode within same describe block .
I tried using test.use() but it works at describle block level and not at individual level

### Expected behavior

test.use() should work at individual test level

### Actual behavior

test.use() dosent work at individual test level

below error:
Cannot use({ headless }) in a describe group, because it forces a new worker.
Make it top-level in the test file or put in the configuration file.

   at events.spec.ts:421

  419 |     });
  420 |
> 421 |     test.use({ headless: false });
      |          ^
  422 |     test('VOPS-TC-1995:Contract(quick test) @EAT-356 @VOPS-TC-1995', { tag: ['@prod', '@regression'], }, async ({ eventsContractingPage }) => {        
  423 |         await eventsContractingPage.navigateToContractingTab();
  424 |         await eventsContractingPage.verifyCreateContract();

### Environment

```shell
Windows 11
```

**Comment by kasperpeulen** [comment]
It would be interesting if you could attach `use` like this:

```tsx
test('some test', async ({ fixture }) => {
  // test
}).use({
  fixture: 'some fixture'
})
```

**Comment by Ransely-Nigrel** [comment]
> ```tsx
> .use({
>   fixture: 'some fixture'
> })
> ```

We cannot .use in void

**Comment by kasperpeulen** [comment]
> We cannot .use in void

I know, just suggesting an idea.

I found out that this does work:

```tsx
test.extend({ fixture: 'some fixture' })('some test', async ({ fixture }) => {
  // test
});
```

On runtime it works, but it gives TS errors. And of course is also quite ugly.

**Comment by pavelfeldman** [comment]
The original issue refers to the `Cannot use({ headless }) in a describe group, because it forces a new worker` error. For the fixtures that force new workers (run browsers in a different mode), this will remain to be a hard limitation. You can't have headed and headless tests in the same file.

As for the .use on a test level, please use anonymous describes to wrap those tests and define `use`. As use refers to the scope and is not chained, that's the only way we'll support it.

**Comment by kasperpeulen** [comment]
@pavelfeldman 
Can you comment if this is expected to work:
```ts
test.extend({ viewport: someViewport })('some test', async ({ fixture }) => {
  // test
});
```

it does work, but it gives TS errors
