### ISSUE TITLE
[Feature]: option to set a timeout in the playwright library, not only the test-runner

### ISSUE THREAD

**Issue by DerZyklop** [microsoft/playwright#31860]
### 🚀 Feature Request

I can specify the timeout for a specific action like:

```ts
….expect(locatorResult).toBeDisabled({timeout: 1234})
```

or in the `playwright.config.ts` like:

```ts
import { defineConfig } from '@playwright/test';

export default defineConfig({
	expect: {
		/** Timeout for each test in milliseconds. */
		timeout: 1234,
	},
});
```

My project uses the library integrated in some gherkin/cucumber setup, but not the playwright test-runner. I’d like to have the possibility to set a global timeout default. The option to define a action-based timeout which overwrites the global timeout would still remain. 

### Example

Sorry, i’m not too experienced/familiar with the library. Possibly just something like:

```ts
import { Then, When } from '@cucumber/cucumber';
import { test } from '@playwright/test';

test.timeoutDefault = 1234;

Then('I expect the checkbox {string} to be checked', async function(this : CustomWorld, checkboxLabel : string, sectionHeader : string) {
	const checkboxLocator = this.page.getByRole('checkbox').filter({hasText: checkboxLabel});
	await test.expect(checkboxLocator).toBeChecked(/* {timeout: 1234} <= not necessary anymore */);
});
```

### Motivation

Currently we write a global const with our default timeout and try to remember to pass it as `{timeout: globalDefaultTimeout}` to every action but that can easily be forgotten and would not give any error.

**Comment by pavelfeldman** [comment]
This would be out of scope for Playwright. Also note that you are using test.expect from playwright outside of @playwright/test at your own risk. It can stop working at any moment.
