### ISSUE TITLE
[internal] improve react code in UI mode, trace viewer and html report 

### ISSUE THREAD

**Issue by dgozman** [microsoft/playwright#31863]
Some ideas:
- [x] introduce something like `clsx` for easier class names;
- [x] use react `context` to avoid passing many constant props around;
- [x] improve settings binding between `localStorage` and `useState()`;
- [ ] ...

**Comment by mxschmitt** [comment]
Would be probably also great to migrate away from [ReactDOM.render](https://github.com/search?q=repo%3Amicrosoft%2Fplaywright%20%2FReactDOM.render%2F&type=code) to [`createRoot`](https://react.dev/reference/react-dom/render) - since the `render` method is deprecated.

**Comment by Skn0tt** [comment]
We've refactored some of the React code, introduced `clsx`, and updated all our React properties to use concurrent rendering. Considering this done!

**Comment by mxschmitt** [comment]
Great work!
