### ISSUE TITLE
Unable to launch the browser on aws lambda even though the browser launch works fine on same image of docker on local machine

### ISSUE THREAD

**Issue by shriyashfinov8** [microsoft/playwright#31870]
### Please do not submit this issue.

- [X] I understand

**Comment by shriyashfinov8** [comment]
Here is my browser launch configuration

        async with async_playwright() as playwright:
            browser_path = find_chromium_path()
            executable_path = f"{browser_path}/chrome-linux/chrome"
            # Local development
            if not os.path.exists(executable_path):
                executable_path = None

            browser = await playwright.chromium.launch(headless=True,
                                                       executable_path=executable_path,
                                                       args=[
                                                           "--no-sandbox",
                                                           "--disable-setuid-sandbox",
                                                           "--disable-dev-shm-usage",
                                                           "--disable-accelerated-2d-canvas",
                                                           "--disable-gpu",
                                                           "--single-process",
                                                           "--no-zygote",
                                                           "--disable-audio-output",
                                                           "--disable-software-rasterizer",
                                                           "--disable-webgl",
                                                           "--disable-web-security",
                                                           "--disable-features=LazyFrameLoading",
                                                           "--disable-features=IsolateOrigins",
                                                           "--disable-background-networking"
                                                       ]
                                                       )
 I am receiving error message as follows : 
 playwright._impl._errors.TargetClosedError: Browser.new_page: Target page, context or browser has been closed
 
The browser launch was working fine!! until this week

**Comment by pavelfeldman** [comment]
AWS Lambda operation is outside of scope for Playwright.
