### ISSUE TITLE
[Feature]: WaitForCondition Should Return Result As Boolean 

### ISSUE THREAD

**Issue by chik145** [microsoft/playwright#31878]
### 🚀 Feature Request

[Feature]: WaitForCondition Should Return Result As Boolean 

### Example

boolean enableStatus = page.waitForCondition(()->locator::isEnabled)

### Motivation

At The End of We Can Return the Result of The Waited Condition

**Comment by pavelfeldman** [comment]
Sorry, I understood nothing about this request. Please be thorough and follow the template next time you file it.
