### ISSUE TITLE
[Feature] Prefer visible elements

### ISSUE THREAD

**Issue by celeryclub** [microsoft/playwright#3187]
Hey team. This could be either a feature request or a bug report. I'm sticking with the former since it may be intentional.

Right now if you have two or more elements matching a selector on the page, Playwright will always prefer the first one. In my opinion, it would be more intuitive if Playwright preferred visible elements to invisible ones. This more closely matches the behavior of a human user. I know this could introduce some complexity (i.e., how long to wait, if at all, for the first element to become visible if there's a second visible element on the page). But I thought I'd mention it since it felt unnatural when I ran into it today. Here's a demo of what I mean.

```js
const { chromium } = require('playwright-chromium');

(async () => {
  const browser = await chromium.launch({
    headless: false,
  });

  const page = await browser.newPage();

  await page.goto('https://xuggr.csb.app', { waitUntil: 'networkidle' });
  await page.click('.link');

  // The code times out here waiting for the first .link to become visible,
  // even though there's another .link visible the whole time

  await page.waitForTimeout(1000);

  await browser.close();
})();
```

Thank you for your consideration!

**Comment by dgozman** [comment]
This is indeed a feature that aims to cover dynamic pages and fight flakiness. We might introduce something like this, but it would be an explicit opt-in.

Ideally, we would like the user to always identify the click target uniquely, for example by using text selector. As an alternative, would something like `page.click('.link #2')` work? This way it still points to the exact element, although using the ordinal is unfortunate, and we can make sure we click the link once it's ready to be clicked.

Also, see #2370 for additional use cases.

**Comment by celeryclub** [comment]
Thanks for the reply! I don't think `page.click('.link #2')` would be better imo, since the goal I had in mind is to make the tests as simple as possible to write. That being said, I completely understand your point about there being other existing ways to work around this issue (like more specific selectors). I'm glad to see you're exploring more flexibility in selector usage.

I'm ok with closing this if you think that makes sense.

**Comment by dgozman** [comment]
I've updated #2370 with some ideas, let me close this one in favor of #2370.
