### ISSUE TITLE
 page.selectOption: TypeError: element.tagName.toUpperCase is not a function

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#31886]
On my page, I have 2 dropdown and 2 text box. Im trying to select value from the dropdown but seeing this error ` page.selectOption: TypeError: element.tagName.toUpperCase is not a function` Can someone please help?

      `await page.selectOption(Tables.TablePages.createNewTagSourceTable(1), sourceValue);`

**Comment by pavelfeldman** [comment]
Could you provide the part of the dom / html and the selector? Looks like a Playwright bug.

**Comment by gauravgandhi1315** [comment]
@pavelfeldman  Selector - `[class='col-md-6 pad-0-l']:nth-child(${index})>div>div>select`

![Screenshot 2024-07-26 at 4 18 55 PM](https://github.com/user-attachments/assets/fb710b17-65db-4e02-a46a-32d542f27bcc)

**Comment by gauravgandhi1315** [comment]
@pavelfeldman can you please help?
