### ISSUE TITLE
[Bug]: `getByLabel` only matches element labelled by first label found when `id` is repeated

### ISSUE THREAD

**Issue by datwaft** [microsoft/playwright#31880]
### Version

1.45.2

### Steps to reproduce

1. Create a local file with the following html code:
    ```html
    <!doctype html>
    <html lang="en">
      <head>
        <title>Playwright's getByLabel issue</title>
      </head>
      <body>
        <div id="card">
          <label for="input">Product</label>
          <input type="text" id="input" />
        </div>
        <div id="card">
          <label for="input">Product</label>
          <input type="text" id="input" />
        </div>
      </body>
    </html>
    ```
2. Open the html file using `playwright open` (i.e. `playwright open file.html`).
3. Open developer tools and in the console execute `playwright.getByLabel("Product")`.

<img width="1394" alt="image" src="https://github.com/user-attachments/assets/dae8bfab-ad31-4ccd-ae40-f01b5ec3f4db">

### Expected behavior

I would expect the `playwright.getByLabel("Product")` locator to match all the inputs with a label with that text.

### Actual behavior

The `playwright.getByLabel("Product")` locator only matches the first input.

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 103.95 MB / 16.00 GB
  Binaries:
    Node: 20.12.2 - ~/.asdf/installs/nodejs/20.12.2/bin/node
    Yarn: 1.22.22 - ~/.asdf/installs/nodejs/20.12.2/bin/yarn
    npm: 10.8.1 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 9.6.0 - ~/.asdf/installs/nodejs/20.12.2/bin/pnpm
    bun: 1.1.4 - ~/.asdf/installs/nodejs/20.12.2/bin/bun
  Languages:
    Bash: 5.2.26 - /opt/homebrew/bin/bash
```

**Comment by datwaft** [comment]
Possibly related to #31881.

**Comment by pavelfeldman** [comment]
Both labels in your DOM are pointing to the first input, so your query uniquely identifies the single input

**Comment by datwaft** [comment]
Thank you for your answer! I understand now the behaviour!
