### ISSUE TITLE
Is there a way to turn off videos on any specs in a certain folder?

### ISSUE THREAD

**Issue by awhisler** [microsoft/playwright#31883]
### Please do not submit this issue.
- [X] I understand

For instance, I have a slew of API tests that don't need a video to retain on failure and they all live in a folder structure I can capture
![image](https://github.com/user-attachments/assets/40749fcf-59c4-4df2-af9e-271844bfb7c0)

**Comment by pavelfeldman** [comment]
Either create a separate project for your api tests (recommended) or disable video in every file using test.use({ video: undefined })

**Comment by awhisler** [comment]
@pavelfeldman What do you mean exactly by "project"? I have a separate folder, can I have two playwright.config.ts one for each folder?

**Comment by awhisler** [comment]
@pavelfeldman I tried adding `test.use({ video: undefined })` and it did not work
![image](https://github.com/user-attachments/assets/5dcaf082-e51d-4956-99fa-26794ce1116b)
![image](https://github.com/user-attachments/assets/06183eb6-0e5f-4856-9644-c6277188c9d7)
