### ISSUE TITLE
[Docs]: Manual installation steps

### ISSUE THREAD

**Issue by reuse-ay** [microsoft/playwright#31887]
### Page(s)

https://playwright.dev/docs/intro

### Description

The current documentation does not provide instructions for manually installing playwright. The "npm init" command probably includes "npm install", but my project has broken dependencies so "npm init" never succeeds. Having instructions for manually installing it would make it easier to use playwright if we are having problems.

**Comment by pavelfeldman** [comment]
Playwright does not have installation steps. But you should fix your project.
