### ISSUE TITLE
[Bug]: `getByRole` doesn't match properly with multiple exact labels with the same `id`

### ISSUE THREAD

**Issue by datwaft** [microsoft/playwright#31881]
### Version

1.45.2

### Steps to reproduce

1. Create a local file with the following html code:
    ```html
    <!doctype html>
    <html lang="en">
      <head>
        <title>Playwright's getByRole issue</title>
      </head>
      <body>
        <div id="card">
          <label for="input">Product</label>
          <input role="combobox" type="text" id="input" />
        </div>
        <div id="card">
          <label for="input">Product</label>
          <input role="combobox" type="text" id="input" />
        </div>
      </body>
    </html>
    ```
3. Open the html file using `playwright open` (i.e. `playwright open file.html`).
4. Open developer tools and in the console execute `playwright.getByRole("combobox", { name: "Product" })`.

    <img width="1394" alt="image" src="https://github.com/user-attachments/assets/1409f7c7-54dc-40db-b5d0-687f6fdc4f68">

6. In the console execute also `playwright.getByRole("combobox", { name: "Product", exact: true })`.

    
    <img width="1394" alt="image" src="https://github.com/user-attachments/assets/193a6ddc-7976-41df-b025-9eda4e9e93f8">

### Expected behavior

I would expect `playwright.getByRole("combobox", { name: "Product" })` and `playwright.getByRole("combobox", { name: "Product", exact: true })` to match both inputs.

### Actual behavior

The following locator only matched the first input (just like in #31880):

```
playwright.getByRole("combobox", { name: "Product" })
```

The following locator didn't match any input:

```
playwright.getByRole("combobox", { name: "Product", exact: true })
```

### Additional context

Fun fact, if I delete the second `#card` it would work as expected:

<img width="1394" alt="image" src="https://github.com/user-attachments/assets/44f15368-3eff-447f-98ce-4715cc815ad7">

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 103.95 MB / 16.00 GB
  Binaries:
    Node: 20.12.2 - ~/.asdf/installs/nodejs/20.12.2/bin/node
    Yarn: 1.22.22 - ~/.asdf/installs/nodejs/20.12.2/bin/yarn
    npm: 10.8.1 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 9.6.0 - ~/.asdf/installs/nodejs/20.12.2/bin/pnpm
    bun: 1.1.4 - ~/.asdf/installs/nodejs/20.12.2/bin/bun
  Languages:
    Bash: 5.2.26 - /opt/homebrew/bin/bash
```

**Comment by datwaft** [comment]
Possibly related to #31880.

**Comment by pavelfeldman** [comment]
> The following locator only matched the first input 

Same reason here, only one input has accessible name "Product"

> The following locator didn't match any input:

Accessible name of your input is "Product Product" as per spec, can validate through the Accessibility pane in devtools, so exact yields no results.

**Comment by datwaft** [comment]
Thank you for your answer! I understand now the behaviour!
