### ISSUE TITLE
[Feature]: Get the current actived page.

### ISSUE THREAD

**Issue by heham** [microsoft/playwright#31890]
### 🚀 Feature Request

Some times i wount the script paused and the same time user open close an change some pages,while user input something then get the current actived page and continue.

### Example
```
def run(playwright: Playwright) -> None:
    browser = playwright.firefox.launch(headless=False, args=['--start-maximized'])
    page = context.new_page()
    page.goto("url")
    #user open close change some pages
    while True:
        print("1")
        print("2")
        print("3")
        user_input = input()
        if user_input == "1":
            cuurent_actived_page="How to get this?"
            print("cuurent_actived_page.title()")
```

### Motivation

If have a get the current actived page method,maybe its usefull.Some times maybe the link open in the new page ,but some times its not,if use this method maybe quick

**Comment by pavelfeldman** [comment]
There is no such thing as active page in Playwright.

**Comment by jiridanek** [comment]
Even worse, every page in Playwright is "active", because Playwright does

https://github.com/microsoft/playwright/blob/6c8c0db530ee44c2ce44a3f26f3daeebccce18a2/packages/playwright-core/src/server/chromium/crPage.ts#L525

so the usual approach with `document.visibilityState` would report every page as `'visible'`:

```typescript
async function findVisiblePage(context: BrowserContext): Promise<Page> {
    // NOTE: not to use .filter() with async predicates
    for (const page of context.pages()) {
        const isVisible = await page.evaluate(() => document.visibilityState === 'visible');
        if (isVisible) {
            return page;
        }
    }
    throw new Error('No visible page found');
}
```

**Comment by tanhh326** [comment]
There is no page switch event in the context either, and the `Page` does not have a key. Even though it was obtained through CDP, there is no way to relate them. 😔

**Comment by tanhh326** [comment]
[https://chromedevtools.github.io/devtools-protocol/](url)
```
const res = await net.fetch(`http://${cdp_addr}/json/list`);
//  The order here changes every time the tab is switched.
const currentPage = (await res.json())[0];
for (const page of browser.pages()) {
    const session = await browser.newCDPSession(page)
    const {targetInfo} = await session.send('Target.getTargetInfo')
    if (currentPage.id === targetInfo.targetId) {
        await page.bringToFront();
    }
}
```

**Comment by sebastiancarlos** [comment]
Here's a working way to detect the active tab, using a tiny helper browser extension which can be auto-loaded. It works on both Chrome and Firefox (the latter with some workarounds needed to install the extension, see linked README)

[playwright-active-page-extension](https://github.com/sebastiancarlos/beachpatrol/tree/cf8b917b8dd586177b3780708efc8b1fdac2513c/playwright-active-page-extension)
