### ISSUE TITLE
[Bug]:When trying to automate adding link to quill editor the popup disappeared after clicking on ql link button however it is working fine in normal way

### ISSUE THREAD

**Issue by MrGeek14** [microsoft/playwright#31892]
### Version

1.44.1

### Steps to reproduce

Automate browser with a page has a quill editor
Open quill editor
Click on add link button

### Expected behavior

Can automate adding link in the popup normally

### Actual behavior

popup disappeared after clicking on ql link button

attached a video
Note: wait sometime in script before clicking to adjust screen recorder

https://github.com/user-attachments/assets/dcb988f2-6d02-4d79-a2f6-b112d808ad10

### Environment

```shell
OS: Windows 11
Browser: Edge, Chrome
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
