### ISSUE TITLE
[Feature]: toHaveProperty() with multiple acceptable expected values

### ISSUE THREAD

**Issue by cyrus-afshari** [microsoft/playwright#31902]
### 🚀 Feature Request

I would like to be able to use toHaveProperty() method in a way where I can pass it multiple expected values, where the assertion passes if the actual value equals one of the multiple expected values. Something like this:

`expect(respBody).toHaveProperty('data.inventoryProducts.data[0].daysOnHand', expect.any(Number).or(null));`

Where respBody is a JSON response that has a value for data.inventoryProducts.data[0].daysOnHand that might be a number, or might be null, but should not be any value other than those 2.

### Motivation

I am using Playwright for API testing, and have many scenarios where I want to assert that a field value in an API response is one of a certain type (number, boolean, string, etc) OR null.

**Comment by mxschmitt** [comment]
Playwright uses the Expect library in order to provide base matches. It looks like they don't support it. You could do something like this:

```ts
const value = respBody.data.inventoryProducts.data[0].daysOnHand;
expect(value === null || typeof value === 'number').toBe(true);
```

I recommend to either use this workaround or [create a custom expect matcher](https://playwright.dev/docs/test-assertions#add-custom-matchers-using-expectextend) like this:

```ts
import { expect as baseExpect } from '@playwright/test';

export const expect = baseExpect.extend({
  toBeNumberOrNull(received) {
    const pass = received === null || typeof received === 'number';
    const message = pass
      ? () =>
          this.utils.matcherHint('toBeNumberOrNull', undefined, undefined, { isNot: this.isNot }) +
          '\n\n' +
          `Expected: ${this.isNot ? 'not ' : ''}to be number or null\n` +
          `Received: ${this.utils.printReceived(received)}`
      : () =>
          this.utils.matcherHint('toBeNumberOrNull', undefined, undefined, { isNot: this.isNot }) +
          '\n\n' +
          `Expected: ${this.isNot ? 'not ' : ''}to be number or null\n` +
          `Received: ${this.utils.printReceived(received)}`;

    return {
      message,
      pass,
    };
  },
});

test('daysOnHand is a number or null', () => {
  const value = respBody.data.inventoryProducts.data[0].daysOnHand;
  expect(value).toBeNumberOrNull();
});
```

or file a feature request [upstream](https://github.com/jestjs/jest) for them to support it inside `toHaveProperty`.

**Comment by cyrus-afshari** [comment]
Thank you @mxschmitt, I've decided I'll just use your workaround.
