### ISSUE TITLE
[Bug] issue with client certificates

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#31906]
@mxschmitt Thank you for quick reply and a great suggestion. After PFX conversion it now works in the API call case.

Unfortunately I still have no luck in the web page authentication scenario. It seems like it just ignores the certificate. Here is the code:

```typescript
import { test, expect } from '@playwright/test';

const originUrl = "https://example.com";

test.use({
  clientCertificates: [
    {
      origin: originUrl,
      pfxPath: 'certificate.p12',
      passphrase: 'password',
    },
],
});

test('test', async ({ page }) => {
  await page.goto(originUrl);
  await expect(page.getByText('No required SSL certificate')).toBeFalsy();
});
```

where `example.com` is in my code our testing domain without URL path (no ending slash).

The page in browser always ends up with "No required SSL certificate" error. Only typo in pfxPath fails earlier with "Error: ENOENT: no such file or directory".

_Originally posted by @okraus-ari in https://github.com/microsoft/playwright/issues/1799#issuecomment-2257082240_

**Comment by mxschmitt** [comment]
Hey @okraus-ari, I created this issue here so we don't send notifications in the other issue. Its unfortunate that its not working for you!

Could you set the `DEBUG=pw:client-certificates` env var and run the tests? That might yield more helpful output.

Could you tell us more about the website / technology the website uses for client-certificates? We need to make sure that these are TLS client certificates and not e.g. using [smart cards](https://github.com/microsoft/playwright/issues/1799#issuecomment-2253690072) technology. Its probably hard to share a repro from your side, but I'd appreciate any input on the tech stack / authentication part. Thanks!

**Comment by mxschmitt** [comment]
Is your website by any chance running on port 443? Then https://github.com/microsoft/playwright/issues/31906 should fix it.

**Comment by okraus-ari** [comment]
@mxschmitt I can confirm that our site is running on port 443. I can also confirm, that the latest beta release fixes the problem. Thank you very much.

**Comment by mxschmitt** [comment]
Awesome news!

**Comment by BenMcLean** [comment]
Forgive me for my ignorance of how Playwright is developed and maintained, but is this new feature of client certificates planned to be made available in the Python and C# versions of Playwright also? If so, when?

**Comment by mxschmitt** [comment]
@BenMcClean Client Certificates are available across all the languages including .NET [see here](https://playwright.dev/dotnet/docs/release-notes#tls-client-certificates). These two fixes from this issue are not available in .NET yet, we'll make them available there probably on Monday.

**Comment by bakoppad** [comment]
@Deepika1313Adactin  how to do it on the mac machines?
