### ISSUE TITLE
[Feature]: Add baseArtifactURL to reporter configuration

### ISSUE THREAD

**Issue by cviebrock** [microsoft/playwright#31919]
### 🚀 Feature Request

We've set up our Playwright tests to run in our CI pipeline (Jenkins, but I don't think that's relevant to my suggestion).  With a failing test, I get a message like the following:

```
attachment #1: screenshot (image/png) ──────────────────────────────────────────────────────────

test-results/my-test/test-failed-1.png

────────────────────────────────────────────────────────────────────────────────────────────────
```

What I was hoping to do was to turn that path into a clickable link, by prepending the base URL of where we are storing our test artifacts.  i.e. something like:

```
attachment #1: screenshot (image/png) ──────────────────────────────────────────────────────────

http://jenkins:8080/some/path/to/artifacts/test-results/my-test/test-failed-1.png

────────────────────────────────────────────────────────────────────────────────────────────────
```

We use the `list` reporter and, asking on Discord, it seems there isn't a way to prepend that `http://jenkins:8080/some/path/to/artifacts/` string to the output.  So my suggestion is an addition to the configuration, so that one could do:

```ts
export default defineConfig({
  reporter: [['list', { baseArtifactURL: 'http://jenkins:8080/some/path/to/artifacts/' }]],
});
```

I imagine this could apply to other reporters as well.

### Example

Update the configuration options so you can do:

```ts
export default defineConfig({
  reporter: [['list', { baseArtifactURL: 'http://jenkins:8080/some/path/to/artifacts/' }]],
});
```

If that option has a value, it is prepended to the path of any attachments/artifacts that are output in the report.

If that option is not set (the proposed default), nothing is prepended, and just the path is displayed (i.e. current behaviour).

### Motivation

This change would make it easier to view artifacts (e.g. screenshots, video files, etc.) in a CI environment.  Viewing the test report would display direct links to the artifact files (which should also be clickable, depending on the CI tool/env).  Currently, you need to copy the relative path from the report file, manually prepend the URL, and then paste that link into a browser.

**Comment by mxschmitt** [comment]
This looks like something specific to your CI provider. Some CI providers may require URL parameters, fragments, suffixes etc. So we are hesitant about adding a new option to that.

We recommend for that either using our [HTML reporter](https://playwright.dev/docs/test-reporters#html-reporter), which provides a "browsable" test results experience including tracing and screenshot comparison support or forking the list reporter, so you have your own.

**Comment by yury-s** [comment]
Closing per the response above.

**Comment by kubajmarek** [comment]
If possible, I'd want to revisit this. We have a repository with `/frontend` and `/backend` paths, which is also reflected in the artifacts from corresponding jobs. So at the end of the pipeline, when I'm using `merge-reports`, I'm inside `frontend` directory:
```
pnpm playwright merge-reports --reporter junit ./e2e-blobs-smoke
```
However the root path, that's also artifacted, is `/frontend/e2e-blobs-smoke`. Since playwright is not aware of it, the produced attachment URL omits the `/frontend/` prefix, so the file is not found.

Yes, we could could switch to HTML reporter which provides `PLAYWRIGHT_HTML_ATTACHMENTS_BASE_URL`, but then we'll miss the GitLab integration with JUnit. Forking JUnit reporter just for that feels like overkill.
