### ISSUE TITLE
[Bug]: It seems that Playwright is missing some initial requests

### ISSUE THREAD

**Issue by ondal1997** [microsoft/playwright#31923]
### Version

1.45.3

### Steps to reproduce

1. Relaunch a Chrome instance with --remote-debugging-port=9222 (e.g., `"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" --remote-debugging-port=9222`).
2. Run a Playwright app with the following code:
```javascript
const { chromium } = require('playwright');

(async () => {
  const broswer = await chromium.connectOverCDP("http://localhost:9222");
  const [context] = broswer.contexts();

  context.route('https://www.google.com/', (route) => {
    route.abort();
  });
})();
```
3. Access https://www.google.com/ via a terminal (e.g., `"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" https://www.google.com/`).

### Expected behavior

Expected result:
The Google page does not appear.

### Actual behavior

Actual result:
The Google page appears.

### Additional context

I’m using Playwright well. It’s an amazing tool.
I hope the minor issue I’ve discovered gets resolved. Thank you.

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 473.22 MB / 32.00 GB
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  IDEs:
    VSCode: 1.90.2 - /opt/homebrew/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    playwright: ^1.45.3 => 1.45.3
```

**Comment by mxschmitt** [comment]
This seems outside of the scope for Playwright. Playwright targets primarily windows which are created either by the page or by Playwright API itself. Since we are not going to prioritise this, I'll close it for now
