### ISSUE TITLE
[Feature]: Getting graphical representation of overall test execution in the default html report  

### ISSUE THREAD

**Issue by Sooraj797** [microsoft/playwright#31926]
### 🚀 Feature Request

Can we get a pie chart view also added in the existing html report?

### Example

This feature gives a good overview and can be used during management level meetings as they won't be interested in detailed report. So, if this is integrated in the existing html report, the report can be used anywhere easily.

### Motivation

This will make playwright less dependent on third-party reporting tools. And for the testers using the playwright would be easier setup to get such a good report easily without any extra installations.

**Comment by mxschmitt** [comment]
Do you mind going into a bit more detail what kind of data the pie-chart should visualise? Do you want to see in it the passed/failed/skipped tests?

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/30887, please upvote that bug instead.
