### ISSUE TITLE
[Bug]: Console.warn from playwright context shows in red in the UI

### ISSUE THREAD

**Issue by unphased** [microsoft/playwright#31921]
### Version

1.45.3

### Steps to reproduce

Within a test, have the code 

```
  console.log('log');
  console.warn('warn');
  console.error('error');
```

### Expected behavior

Expect warn bgcolor and icon to be yellow and not red. 

### Actual behavior

<img width="148" alt="image" src="https://github.com/user-attachments/assets/991d30a1-9c4b-4412-9fae-1f1ba5179c99">

### Additional context

Issue unaffected by code run in browser context: 

```
  await page.evaluate(() => {
    console.log('log');
    console.warn('warn');
    console.error('error');
  });
```

<img width="181" alt="image" src="https://github.com/user-attachments/assets/23d9fd79-80b5-42f0-bdf6-a5d669a72fa6">

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 298.02 MB / 64.00 GB
  Binaries:
    Node: 22.4.1 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 10.8.1 - /opt/homebrew/bin/npm
    pnpm: 8.14.0 - /opt/homebrew/bin/pnpm
    bun: 1.0.18 - ~/.bun/bin/bun
  Languages:
    Bash: 5.1.16 - /opt/homebrew/bin/bash
  npmPackages:
    @playwright/test: ^1.44.1 => 1.45.3
```

**Comment by mxschmitt** [comment]
In the browser we know its warn/log/error. In Node.js, we don't and show log as transparent and warn/error as red. So this is working as expected as of today.

**Comment by unphased** [comment]
I think I understand what you're saying. It is interesting that sniffing the output streams is the approach taken. I think I saw some Logger facilities provided by playwright. But that seems like just a way to get access to logging done on internal processes and typically would be sent here to console methods. 

Now I wonder... maybe I could somehow run playwright tests from node.js attached to chrome debugger and see if the logs would render nicely in **there**.

**Comment by mxschmitt** [comment]
While I was looking at it, internally Node.js colours the console.warn calls if `isTTY` is true. Since our workers are not in TTY mode, they won't get coloured. So yeah ideally we make it work, but with the current design it seems hard to implement.

**Comment by unphased** [comment]
I am exploring for my use case a way to factor my playwright tests in such a way that i can both launch them directly from node (for benefits like closer integration with other test launch flow from wider app, and for ability to peek at console output "properly" in the devtools), while also allowing them to launch from a standard playwright test context to get all of the streamlined playwright UI and test runner features. 

Yes I had discovered it was somewhere in node version 21 that when running in a TTY, console.warn wraps all output in yellow and console.error wraps all output in red. I actually have kind of a bone to pick with this behavior because it causes bad output whenever you use any colors in your console warns and errors... 

The best workaround for that that I know is to simply establish a convention where all your logs begin with a color clearing escape code to bring everything back to the way it was before.

**Comment by unphased** [comment]
> While I was looking at it, internally Node.js colours the console.warn calls if `isTTY` is true. Since our workers are not in TTY mode, they won't get coloured. So yeah ideally we make it work, but with the current design it seems hard to implement.

But I have questions... 

- if the way that the playwright UI renders console logs is done via sniffing the output streams, why is this UI able to make a differentiation between logging out multiple lines in separate calls to console.log and logging the same content joined by newlines in a single console log? Only by timing and how chunks arrive to the event handler?

- I also noticed that I am able to call console.table from the playwright side (not target browser side) and get some sort of attempt at drawing a table: 
<img width="508" alt="image" src="https://github.com/user-attachments/assets/f30e93e5-1ed8-415a-9652-bf09b2534360">

... Ah, okay, this actually supports what you stated, which is that playwright slurps the table built out of box drawing glyphs by node.js for a terminal, parses that (dropping some repeated spaces, notably) and spits it out in the UI. This makes it look stupid but it does a good job revealing what's going on under the hood. 

Now... if such a layer exists to populate the UI's display of the log based on what the node process is spitting out to the stdout/stderr, then maybe we could easily add an API which I could use to do logging from the playwright test code so that the console could be more fully featured?
