### ISSUE TITLE
[Bug]:  VS Code extension doesn't find config files.

### ISSUE THREAD

**Issue by zomars** [microsoft/playwright#31936]
### Version
 1.1.7

### Steps to reproduce

Have a monorepo with a `playwright.config.ts`file  on the root with a custom `testMatch` like `/.*\.e2e\.tsx?/ `.

Take notice of the projects section and also the "Toggle Playwright configs" command.

### Expected behavior

"Toggle Playwright configs" command should display the "playwright.config.ts" file.

The project section should display projects.

### Actual behavior

Both config and projects are empty.

Here's proof that v1.0.22 shows tests properly:

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/138a01f1-3b7d-43b4-95d2-86a8b439a81e">

Here's the same view with v1.1.7:

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/3e292096-0f69-481a-8ed8-e3168f8dc6ef">

Here's the "Toggle Playwright configs" command as described in #30882:

<img width="1202" alt="image" src="https://github.com/user-attachments/assets/f6f17b91-7a0a-4d8e-93f0-44bf7d227ca0">

### Additional context

Downgrading to v1.0.22 display projects and find tests with the custom suffix correctly.

VS Code 

> Downgrading to v1.0.22 worked for me. v1.1.7 doesn't find neither my project config files nor my tests which use a custom testMatch: /.*\.e2e\.tsx?/ property.

> _Originally posted by @zomars in https://github.com/microsoft/playwright/issues/30803#issuecomment-2261300218_

> @zomars please file a separate issue, happy to look into it. Make sure you have the projects selected in the Testing tab under the Playwright section, see https://github.com/microsoft/playwright/issues/30882 for more details.

> _Originally posted by @mxschmitt in https://github.com/microsoft/playwright/issues/30803#issuecomment-2261347569_

Adding to the title, I assume because the config file cannot be found, the projects section was completely empty. Only downgrading to `v1.0.22` worked again.

**Comment by mxschmitt** [comment]
Hi! Do you mind sharing your project structure with us? How is your config named? Which Playwright version are you using?

**Comment by zomars** [comment]
> Hi! Do you mind sharing your project structure with us? How is your config named? Which Playwright version are you using?

Updating the issue as we speak.

**Comment by zomars** [comment]
Also our mono-repo is open source so you can try latest VS Code with the playwright v.1.1.7 extension.

Just clone it and see how it doesn't display any projects nor config files. 

https://github.com/calcom/cal.com/blob/main/playwright.config.ts

**Comment by zomars** [comment]
Tried v1.1.1 and doesn't show any configs nor projects either. Only v1.0.22 gives the correct behavior.

**Comment by mxschmitt** [comment]
I tried it with the repository, if you reload the projects, so you get: 

<img width="583" alt="image" src="https://github.com/user-attachments/assets/585f5f88-14fb-454a-ba33-00cec1aa6670">

We recommend using a recent version of Playwright, e.g. 1.45 which is latest nowadays. Since you want to test the browser versions your users are using, see [here](https://playwright.dev/docs/browsers#update-playwright-regularly).

**Comment by zomars** [comment]
Odd. I didn't got that notice. Will try upgrading and report back.

**Comment by zomars** [comment]
Ok. Upgrading both playwright and extension to latest seems to have solved it. I still need to check if there are breaking changes in tests. Thanks again.

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/5576503e-58ca-4a80-acfa-ff6414de003d">

**Comment by mxschmitt** [comment]
Since 1.31 -> 1.45 is a big bump, I recommend reading over https://playwright.dev/docs/release-notes to see if there were any breaking changes / deprecations.
