### ISSUE TITLE
[Bug]: globalSetup not running before tests start

### ISSUE THREAD

**Issue by jensenld** [microsoft/playwright#31966]
### Version

v1.1.7

### Steps to reproduce

1. Setup globalSetup in auth.setup.ts
2. Add globalSetup() in playwright.config.ts as follows:
  globalSetup: require.resolve("./playwrightTests/auth.setup.ts")
3. Click on green test arrow to run tests

### Expected behavior

I expect to see the globalSetup run first, then the tests execute...the order is as follows:  playwright.config.ts starts a webserver, then globalSetup is supposed to run, open a browser on localhost, log into the app, then save the storageStage to a user.json file in the /playwright folder/.auth folder. The tests run after using the user.json data for authentication.

### Actual behavior

The globalSetup does not run first using the Playwright Test for VSCode extension green start arrows. The tests fail because the user.json is not created first.

### Additional context

The globalSetup will run first if I execute in the terminal using "npx playwright test", and the tests will successfully run and pass.
It is only broken when I run the tests using the green start arrows from the Playwright Test for VSCode extension.

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M2 Pro
    Memory: 2.58 GB / 32.00 GB
  Binaries:
    Node: 20.13.0 - ~/.nvm/versions/node/v20.13.0/bin/node
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.0/bin/npm
  IDEs:
    VSCode: 1.91.1 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.45.3 => 1.45.3
```

**Comment by mxschmitt** [comment]
`globalSetup` should run automatically when using VSCode. Would it be possible to provide a repro?

> Setup globalSetup in auth.setup.ts

This sounds suspicious, how do you run/setup it there?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
