### ISSUE TITLE
[Bug]: Network requests stuck in "Download is starting" when using devices.

### ISSUE THREAD

**Issue by dobladov** [microsoft/playwright#31989]
### Version

1.45.3

### Steps to reproduce

When running the test with a [device](https://playwright.dev/docs/emulation#devices) like `...devices["iPhone 14"]` or `..devices["Kindle Fire HDX"]` the test get stuck on the first navigation with `page.goto(url)`, with the message **"Download is starting"** and fails.

This happens while running the test on a GitHub runner, I wasn't able to re-create the issue locally on Mac, the runner is using Debian

Running the same tests with `...devices["Desktop Chrome"]` or any of the Android devices works as expected.

<img width="663" alt="Screenshot 2024-08-02 at 11 47 10" src="https://github.com/user-attachments/assets/8b5d1a5c-6acd-4c70-bdef-88edc98c0d55">

### Expected behavior

The navigation should continue and not fail with "Download is starting"

### Actual behavior

Any initial navigation request is stuck pending and causes the test to fail.

### Environment

```shell
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    Memory: 12.90 GB / 16.00 GB
    Container: Yes
  Binaries:
    Node: 22.2.0 - /opt/hostedtoolcache/node/22.2.0/x64/bin/node
    npm: 10.7.0 - /opt/hostedtoolcache/node/22.2.0/x64/bin/npm
  Languages:
    Bash: 5.1.4 - /bin/bash
  npmPackages:
    playwright: 1.45.3 => 1.45.3
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
