### ISSUE TITLE
[Bug]: Identifier 'QueryClientProvider' has already been declared

### ISSUE THREAD

**Issue by tkfmed** [microsoft/playwright#31982]
### Version

1.45.3

### Steps to reproduce

https://github.com/tkfmed/playwright-ct-react-query-reproduction
Just run playwright tests

### Expected behavior

Expected no issues while testing with provider added

### Actual behavior

When no provider set, there is an error in the browser's console, saying, that there is no queryClientProvider set. When I add such provider, `Identifier 'QueryClientProvider' has already been declared` error displays

### Environment

```shell
node: v18.20.2
npm: v10.5.0
```

**Comment by sand4rt** [comment]
Hi @tkfmed, using a class as a prop is not supported. You could define React providers, such as `<QueryClientProvider>`, within the `beforeMount` hook: [Playwright documentation on hooks](https://playwright.dev/docs/test-components#hooks). Alternatively, you could also use a [wrapper or story component](https://playwright.dev/docs/test-components#test-stories), but i would stick with the `beforeMount` hook here.

It would be helpful if a more descriptive error message was provided in such cases

**Comment by tkfmed** [comment]
Hi! Thanks for the response
Actually, there is no difference for me whether I initialize the provider via `beforeMount` or `mount`. As I understood you correctly, the real problem is QueryClient class passed to the prop. Unfortunately, I'm not able to initialize the provider without it. I don't see the documentation to be helpful in this case, or am I missing something?

**Comment by sand4rt** [comment]
@tkfmed could you try the example below? _(make sure you're on playwright 1.46.0 to use MSW + PW)_:

```ts
// playwright/index.ts
import React from "react";
import "../src/App.css";
import "../src/index.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { beforeMount } from '@playwright/experimental-ct-react/hooks';
import App from '../src/App';

beforeMount(async () => {
    const queryClient = new QueryClient();
    return (
        <QueryClientProvider client={queryClient}>
          <App />
        </QueryClientProvider>
    )
});
```

```tsx
// App.e2m.test.tsx
import { test, expect } from "@playwright/experimental-ct-react";
import App from "./App";
import { http, HttpResponse } from 'msw';

test("should work", async ({ router, mount }) => {
  await router.use(http.get('/api/test', async () => {
    return HttpResponse.json(1337);
  }));
  const component = await mount(<App />);
  await expect(component).toContainText("1337");
});
```

**Comment by tkfmed** [comment]
Working! So what's the idea behind mounting things into playwright's index.tsx?

**Comment by sand4rt** [comment]
Great! `playwright/index.tsx` is the place where global setup of your app takes place, it's kind of similar to your [main.tsx](https://github.com/tkfmed/playwright-ct-react-query-reproduction/blob/64106697593c73c7d6dd844de743ed5a679b7b43/src/main.tsx#L1-L15), but then for testing :)
