### ISSUE TITLE
[Feature]: Set response delay in har mocks

### ISSUE THREAD

**Issue by Zver64** [microsoft/playwright#31983]
### 🚀 Feature Request

When playwright records mocks in har I see that the prop `wait` is always -1 like so:
```
"timings": { "send": -1, "wait": -1, "receive": 1.388 }
```
Here is how I record har:
```
await oxy.page.routeFromHAR(
        path.resolve(__dirname, "har/test1.har"),
        {
            url: "https://example.com/**/*",
            updateContent: "embed",
            update: true,
        },
    );
```
And when I run my tests using these mocks those mocked requests take much less time than actual requests. Even if I manually change `wait` prop to 1000ms - it does not affect my mocked requests duration.

I tried to use page.route to add delay for my requests, but it seems like in this case those requests are not being mocked with my har files. Here is how I used page.route:
```
await oxy.page.routeFromHAR(
        path.resolve(__dirname, "har/test1.har"),
        {
            url: "https://example.com/**/*",
            updateContent: "embed",
            update: false,
        },
    );

await oxy.page.route("https://example.com/**/*", async (route) => {
        await new Promise((resolve) => setTimeout(resolve, 1000)); // Delay
         // This will make an actual network request, even if the request
         // should have been served from the HAR file
        await route.continue()
    });
```

### Example

- Har files have proper values in `wait` prop when recorded
- requests mocked with har files simulate response delay according to the `wait` prop in corresponding har mock

### Motivation

The ability to set response wait time allows to make mocked requests to their real examples in order to recreate some bugs that don't happen 100% of time.
Also according to the [documentation](http://www.softwareishard.com/blog/har-12-spec/) "The send, wait and receive timings are not optional and must have non-negative values"

**Comment by yury-s** [comment]
> When playwright records mocks in har I see that the prop wait is always -1 like so:

There is a bug in our documentation, default [`updateMode`](https://playwright.dev/docs/api/class-page#page-route-from-har-option-update-mode) is actually `minimal` which is why the timing data is not saved. I'll update the documentation. You can change the mode to have the values recorded:

```js
  await page.routeFromHAR(
    path.resolve(__dirname, "test1.har"),
    {
        url: "https://playwright.dev/**/*",
        updateMode: "full",
        updateContent: "embed",
        update: true,
    },
  );
```

> And when I run my tests using these mocks those mocked requests take much less time than actual requests. Even if I manually change wait prop to 1000ms - it does not affect my mocked requests duration.

This is by design. Replay from HAR is not trying to emulate original network timing, it will try to replay from the log as fast as possible. If you need such precise control over the replay, you'd better off writing custom route handlers and routing from the log manually.

> I tried to use page.route to add delay for my requests, but it seems like in this case those requests are not being mocked with my har files. Here is how I used page.route:

Works for me locally. `page.route` handlers are invoked in the reverse order as they were registered, the delay before `route.continue()` should result in slower request fulfillment. Please share complete example if it doesn't work.

**Comment by Zver64** [comment]
> Works for me locally. page.route handlers are invoked in the reverse order as they were registered, the delay before route.continue() should result in slower request fulfillment. Please share complete example if it doesn't work.

You're right, it does make the request slower, but it makes the actual request to the server instead of filling request from the mocks I have recorded with `routeFromHAR`

**Comment by yury-s** [comment]
> You're right, it does make the request slower, but it makes the actual request to the server instead of filling request from the mocks I have recorded with routeFromHAR as I mentioned above.

You need to use `route.fallback()` instead of `route.continue()` in order to other handlers to be invoked. `route.continue()` will send the request to the network.
