### ISSUE TITLE
playwright python how to implement custom retry  

### ISSUE THREAD

**Issue by zqxyus** [microsoft/playwright#31996]
The following code is i found,    

await expect(async () => {
    await page.locator('button').click();
    await expect(page.locator('div')).toBeVisible();
    }).toPass();

i want to implement it with python as follows

expect(sync () => {
    page.click("//button[@name='sign or log in'");
    page.locator('//input[@id="password"]').to_be_visible();
    }).to_pass();

however, syntax error is outputed

expect(sync () => {
           ^^^^^^^^^
SyntaxError: expression cannot contain assignment, perhaps you meant "=="?

how to fix it ?

Thanks

**Comment by mxschmitt** [comment]
In Python all our assertions automatically retry: https://playwright.dev/python/docs/test-assertions automatically - that should work for you most likely. There is no `toPass` in Python as of today.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
