### ISSUE TITLE
[Feature]: Any defined plans for component testing?

### ISSUE THREAD

**Issue by tar-aldev** [microsoft/playwright#31995]
### 🚀 Feature Request

From what I can see in the docs https://playwright.dev/docs/test-components this feature is still experimental. Are there any plans / estimated release date of full feature? Some points which might be nice to have (or document):
1. Testing with next.js
2. stubbing modules in component tests (like `cy.stub()` or `jest.mock()`)

### Motivation

Currently playwright can be used for e2e tests and is working great, but component tests are only available in cypress. The maintenance is therefore more convoluted, cause there is a need to support running tests with different frameworks.

**Comment by Az8th** [comment]
Angular component testing support PR has not been merged yet, so I guess it would at least require it and be proven stable for enough time to exit its experimental phase

**Comment by yury-s** [comment]
There is no concrete date of going out of experimental yet. Even though component testing has been in a pretty good state for a while, there are still missing features and possibility of breaking changes.

If you find a particular feature missing please follow the feature request template and provide detailed explanation with examples. For general questions please use our [community resources](https://playwright.dev/community/welcome) such as discord channel.
