### ISSUE TITLE
[Bug]: Page.goto: Target page, context or browser has been closed

### ISSUE THREAD

**Issue by shriyashfinov8** [microsoft/playwright#31994]
### Version

1.43.0

### Steps to reproduce

This type of issue is very hard to reproduce. 
Develop a script to navigate to https://lsusports.net/sports/mb/roster/ website using following configuration.
Disclaimer : My system only works with playwright 1.43.0 so upgrading to latest versions has given me timeout scenarios.

                async with async_playwright() as playwright:
            browser_path = find_chromium_path()
            executable_path = f"{browser_path}/chrome-linux/chrome"
            # Local development
            if not os.path.exists(executable_path):
                executable_path = None

            browser = await playwright.chromium.launch(headless=True,
                                                       executable_path=executable_path,
                                                       args=[
                                                           "--no-sandbox",
                                                           "--disable-setuid-sandbox",
                                                           "--disable-dev-shm-usage",
                                                           "--disable-accelerated-2d-canvas",
                                                           "--disable-gpu",
                                                           "--single-process",
                                                           "--no-zygote",
                                                           "--disable-audio-output",
                                                           "--disable-software-rasterizer",
                                                           "--disable-webgl",
                                                           "--disable-web-security",
                                                           "--disable-features=LazyFrameLoading",
                                                           "--disable-features=IsolateOrigins",
                                                           "--disable-background-networking"
                                                       ]
                                                       )
            await page.goto("https://lsusports.net/sports/mb/roster/")
            
The page fails to navigate to this website when deployed the code on aws lambda. Why is that so?

### Expected behavior

I expect the page to navigate to the page without any issue as it does for the other type of urls

### Actual behavior

playwright._impl._errors.TargetClosedError: Page.goto: Target page, context or browser has been closed

### Environment

```shell
System:                                                                                                                  
    OS: Debian GNU/Linux 12 (bookworm)                                                        
CPU: (16) x86_64 – 64-bit x86                                                                                           
    Memory: 4096MB                                                                                           
    Container: Yes                                                                                                                                                                                                  
python libraries:                                                                                                             
    playwright==1.43.0
```

**Comment by mxschmitt** [comment]
Playwright only supports the latest version and we need a reproduction in order to debug issues like this. Setting the `DEBUG=pw:browser` env var, might yield helpful debug output. Also AWS Lambda most likely runs on Amazon Linux, which is not supported, as per [here](https://playwright.dev/docs/intro#system-requirements).

**Comment by yury-s** [comment]
Closing per the response above.

**Comment by JP-2000** [comment]
Why you doubt Shriyash Saar
