### ISSUE TITLE
playwright Openfin

### ISSUE THREAD

**Issue by janagar-john** [microsoft/playwright#31997]
How to automate openfin playwright

**Comment by Az8th** [comment]
Hello,

If you want some guidance, you should try to open a thread in the [Official Playwright Community Discord Server](https://discord.gg/invite/playwright) `help-playwright` channel

Also, please search if someone already posted something similar before opening an issue, having doublons does not help.
Please consider removing this issue or at least closing it or tagging it as a question ;)

Regarding your question, you should find answers here #6936

**Comment by yury-s** [comment]
This doesn't sound like a bug or feature request, please use our [community resources](https://playwright.dev/community/welcome) for general questions. If you think this is a bug in Playwright, please open a new issue and follow the bug template.
