### ISSUE TITLE
[Bug]: const context = await browser.newContext({   locale: 'de-DE',   timezoneId: 'Europe/Berlin', });

### ISSUE THREAD

**Issue by fancy45daddy** [microsoft/playwright#32001]
### Version

1.41.1

### Steps to reproduce

i try to change the chrome timezone from utc to berlin, the system timezone is utc.

const context = await browser.newContext({
  locale: 'de-DE',
  timezoneId: 'Europe/Berlin',
});

but when i
await page.goto(chrome://history)
all the timestamp still in utc. 

how to change all the timestamp to berlin timezone in playwright？ if playwright can not do the job. what i should do to change the timestamp？

### Expected behavior

timestamp in chrome://history should match timezoneid

### Actual behavior

timestamp in chrome://history not change

### Environment

```shell
jammy
```

**Comment by mxschmitt** [comment]
`chrome://history` is not part of the Web platform. Do you mind providing us an example on the web platform that does not get updated when using these settings and what your expectations is? Ideally some JavaScript or http header which is still "bad".

e.g. `new Date` or `Intl.DateTimeFormat` should use it.

**Comment by fancy45daddy** [comment]
My requirement is to change the timestamp of chrome history (from UTC to Berlin timezone). I do not care what the web platform is. That is not my requirement. If playwright can not provide such feature. What I can do to change the timestamp of chrome history

**Comment by mxschmitt** [comment]
Could you elaborate on your testing scenario?

**Comment by yury-s** [comment]
Please share complete example that demonstrates the problem, so that we could run it locally.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
