### ISSUE TITLE
[Bug]: VSCode extension not honoring test location path

### ISSUE THREAD

**Issue by brianshostak** [microsoft/playwright#32017]
### Version

1.46.0 (happens on older versions too)

### Steps to reproduce

1. Clone https://github.com/bshostak/vspw
2. Notice that the automation is actually inside a folder called test-automation
3. cd to that folder location and run install commands
4. run the tests from terminal and notice that the AuthStates folder it created from the test context was stored in the proper path (within test-automation folder)
![Screenshot 2024-08-05 at 3 48 35 PM](https://github.com/user-attachments/assets/e7d6ed35-fdb1-4e94-8f74-0c793140e147)
5. Now run the same test but from the Playwright test runner extension. You will see that the AuthStates folder gets put at the root of the repo vs the root of the test-automation folder as designated.
![Screenshot 2024-08-05 at 3 47 52 PM](https://github.com/user-attachments/assets/70d9601b-8249-4d40-bb85-cc0b20f7e30d)

### Expected behavior

I am running the VSCode extension version 1.1.7. This does not happen on older versions like 1.0.20. We should expect that the extension mimics the same behavior as the command line. I should be able to run the test from the extension and it honors the pathing as if we were in the test-automation directory.

### Actual behavior

The auth states pathing gets put in an incorrect place which makes it so we cannot use the extension.

### Additional context

Our automation lives in our development code repositories as its own folder entity (as the repo I posted shows). That way automation for that specific repo follows it. I'm hoping that I'm either missing a setup step with the new playwright extensions or something but it seems like not expected behavior.

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 20.11 GB / 64.00 GB
  Binaries:
    Node: 18.20.4 - ~/.nvm/versions/node/v18.20.4/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v18.20.4/bin/npm
  IDEs:
    VSCode: 1.92.0 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.46.0 => 1.46.0
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by yury-s** [comment]
That behavior have changed, the `cwd` is currently set to `workspaceFolder` when running the tests. To avoid such problems we recommend you use absolute paths (e.g. by resolving it relative to `__dirname`), so that the tests run reliably regardless of the test runner invocation directory.

**Comment by brianshostak** [comment]
@yury-s Something like this seems to work. Thanks, I will make the changes.
```typescript
const storagePath = path.resolve(__dirname, '../Auth-States/path.json');
 await page.context().storageState({ path: storagePath });
```
