### ISSUE TITLE
[Feature]: Network Tab Search

### ISSUE THREAD

**Issue by Douglasgomes027** [microsoft/playwright#32019]
### 🚀 Feature Request

Network Tab Search on Trace Viewer

### Example

There are some scenarios where we have a lot of requests in the network tab. It would be awesome to be able to search. Therefore, I would like to add a search bar to enable searching in the network tab.

### Motivation

Highlight specific scenarios where numerous network requests make it difficult to manage and analyze data.

**Comment by yury-s** [comment]
Can you provide a bit more details about the scenarios you have in mind and why does filtering by time (either manually selecting time frame or by clicking on an action) not work ?

**Comment by yury-s** [comment]
This was addressed in https://github.com/microsoft/playwright/pull/31956/

**Comment by Douglasgomes027** [comment]
yes! That was my ideia! Thanks @yury-s
