### ISSUE TITLE
[Regression]: Error: electron.launch: Process failed to launch  when use vscode extension run electron tests

### ISSUE THREAD

**Issue by lqd1434** [microsoft/playwright#32027]
### Last Good Version

1.43.1

### First Bad Version

1.44

### Steps to reproduce

use vscode extension run electron test

### Expected behavior

can start electron app

### Actual behavior

Error: electron.launch: Process failed to launch!

## DEBUG=pw:browser  log:
```
pw:browser <ws connecting> ws://localhost:38233/88654cb976b9732f93fdfad7415f68d8 +0ms
pw:browser <ws connected> ws://localhost:38233/88654cb976b9732f93fdfad7415f68d8 +12ms
 pw:browser <launching> /test/node_modules/electron/dist/electron -r /test/node_modules/@playwright/test/node_modules/playwright-core/lib/server/electron/loader.js --inspect=0 --remote-debugging-port=0 /test/lib/backend/electron-main.js +5s
  pw:browser <launched> pid=167817 +2ms
  pw:browser [pid=167817][err] /test/node_modules/electron/dist/electron: bad option: --remote-debugging-port=0 +13ms
  pw:browser <ws disconnecting> ws://localhost:38233/88654cb976b9732f93fdfad7415f68d8 +12ms
  pw:browser [pid=167817] <process did exit: exitCode=9, signal=null> +0ms
  pw:browser [pid=167817] starting temporary directories cleanup +1ms
  pw:browser [pid=167817] finished temporary directories cleanup +2ms
  pw:browser <ws disconnected> ws://localhost:38233/88654cb976b9732f93fdfad7415f68d8 code=1005 reason= +3ms
```

I noticed current extension use workspace as cwd, i think this error was caused by that, but i don't know how to solve this, i had try use absolute path to specify electron main.js, but it don't work.

and when i run tests in terminal, it's work.

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    Memory: 10.05 GB / 15.54 GB
    Container: Yes
  Binaries:
    Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
    Yarn: 1.22.22 - /mnt/c/Program Files/nodejs/yarn
    npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
```

**Comment by yury-s** [comment]
> I noticed current extension use workspace as cwd, 

I you are talking about VSCode extension, then yes, it uses workspace folder as cwd and it did change around v1.44. Please use absolute path to avoid such problems, you can do something like `path.resolve(__dirname, '../relative/path/main.js');`. If it doesn't work, please provide a reproduction that we could run locally.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
