### ISSUE TITLE
[Bug]: html to converted pdf in internal refrence link not working in google drive pdf viewer

### ISSUE THREAD

**Issue by lnxct** [microsoft/playwright#32028]
### Version

1.46

### Steps to reproduce

1. create any html internal reference page clickable html code
2. convert html to PDF
3. open PDF in google drive PDF viewer. - click on internal reference will not work. and it will work on any other PDF viewer like adobe PDF viewer

### Expected behavior

i expected to internal reference clickable work on google drive PDF viewer

### Actual behavior

internal refrence clickable not working

### Environment

```shell
System: Linux ubuntu-4gb-hel1-1 6.8.0-39-generic #39-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 21:49:14 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Node: 18
```

**Comment by yury-s** [comment]
If the pdf is rendered as html by google drive, Playwright should be able to click on them as any other hyperlink. If it's rendered as e.g. `<embed>` element, then it is tracked by https://github.com/microsoft/playwright/issues/14988. Please share a reproduction that we could run locally to see the problem.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
