### ISSUE TITLE
[Bug]: could not access/interact with the chrome app launched by playwright using chromium.launchPersistentContext

### ISSUE THREAD

**Issue by karthigairajab** [microsoft/playwright#32048]
### Version

1.45.3

### Steps to reproduce

1. clone my repo https://github.com/karthigairajab/playwrightPoc.git
2. run npx playwright test --project=GoogleChrome

Due to security and privacy reasons the app is not pushed to the github account.

The problem is the Playwright can open the chrome app and a browser window using chromium.launchPersistentContext.

Playwright can identify and interact with the browser window, but it could not find the chrome app that is opened. 
Tried give wait, loop for certain number of times nothing worked. 
I can see the app is opened and fully loaded but somehow the playwright could not identify it

### Code

```
const { test, expect } = require('@playwright/test');
const { chromium } = require('playwright');

test('try flow', async () => {
    const browserContext = await chromium.launchPersistentContext('', {
        headless: false,
        ignoreDefaultArgs: ['--enable-automation'],
        args: [
            '--disable-extensions-except=dist',
            '--load-and-launch-app=dist'
        ]
    });

    //Wait for the new page (app window) to be created
    let appPage;
    for (let i = 0; i < 10; i++) {
        const pages = browserContext.pages();
        console.log("Outside trying for the time : " + i + " page length : " + pages.length)
        if (pages.length > 1) {
            console.log("trying for the time : " + i + " page length : " + pages.length)
            appPage = pages[pages.length - 1];
            break;
        }
        await new Promise(resolve => setTimeout(resolve, 8000)); // wait 500ms before checking again
    }

    if (!appPage) {
        console.log('App page not found.');
        await browserContext.close();
        return;
    }
    await appPage.pause();

    // Now you can interact with the appPage
    await appPage.waitForLoadState('domcontentloaded'); // Ensure the app is loaded
    console.log('App page found and loaded.');
    await appPage.pause();
})
```

### Expected behavior

Playwright should be able to identify the app that is opened using chromium.launchPersistentContext. 
if it could idenitfy then I can store that as a new page variable and proceed with the next interaction steps.

### Actual behavior

The app is opened together with the browser without any issues, but playwright can identify only the chrome window and not the app.

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics
    Memory: 12.44 GB / 31.37 GB
  Binaries:
    Node: 20.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.92.0 - C:\Users\Users\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
```

**Comment by yury-s** [comment]
We don't support Chrome Apps. Also they are deprecated and according to the note on [this page](https://developer.chrome.com/docs/apps/migration) stopped working since Chrome 112.

**Comment by karthigairajab** [comment]
@yury-s thanks for the response.
We wanted to rebuild the chrome apps to Progressive Web app or Isolated Web App, does playwrigth support the automation of these? 
(We wanted to go for one tools policy within the organization that will replace Selenium.)
