### ISSUE TITLE
[Bug]: Array with more than one entry is not propagated from fixture method

### ISSUE THREAD

**Issue by Lazar-Adrian** [microsoft/playwright#32046]
### Version

1.46

### Steps to reproduce

1. Clone: https://github.com/Lazar-Adrian/fixtureArray
2. npm i
3. npx playwright test

### Expected behavior

The object sent as a parameter on test.use() will keep it's same structure when called in a fixture method.

### Actual behavior

The property that has an {}[] type with more than one entry, will be set as {}[0] instead of {}[]

### Environment

```shell
System:
  OS: macOS Sonoma 14.5
  CPU: Apple M1 Pro
Binaries:
  Node: v20.9.0
  npm: 10.1.0
npmPackages:
  @playwright/test: 1.46.0
```

**Comment by yury-s** [comment]
Same as https://github.com/microsoft/playwright/issues/32033

**Comment by dgozman** [comment]
Merging into #32033.
