### ISSUE TITLE
[Feature]: easy way to access parent locator having child container 

### ISSUE THREAD

**Issue by Abubaker0001** [microsoft/playwright#32069]
### 🚀 Feature Request

it will helpfull like if I want to access child of parent I can easily access like '[parentLocator >> childLocator] to access child with parent we have a method like this in which dont have to use filter type function I research alot in documentation but there is not a easy and suitable method to access child with parent 

### Example

It will helpful I have very huge project like I want to run  almost 500 test cases in pipeline and I am currently have a situation where I want to access parent with child locator and I have to use loop and it is very time taking if I used loop in this i have to measure everything so that it not taking time because I have to reduce the time of running pipeline 

### Motivation

when I researched in this topic there were a lot questions about this and everyone using filter function or using loops so it is very helpful for everyone if there is any easy way you can introduce it

**Comment by yury-s** [comment]
Sorry, I can't parse your request. Can you give an example of the html, what element you want to query, your current locator and a new syntax of how you think it could work better?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
