### ISSUE TITLE
[Feature] Export network as HAR

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#3206]
Filing based on the request on Slack.

**Comment by VikramTiwari** [comment]
Hey @pavelfeldman I took a peek at [CDP](https://chromedevtools.github.io/devtools-protocol/) and couldn't find anything that relates to this. Any ideas on how you would get about doing this? I would love to contribute but would need some guidance.

Thanks!

**Comment by Bnaya** [comment]
@VikramTiwari as playwright is not based on CDP,
The the most cross browser implementation would be based on playwright network events
https://playwright.dev/#version=v1.4.2&path=docs%2Fapi.md&q=event-request

Another option would be to somehow leverage the internal har record mechanism of the various browsers

**Comment by pavelfeldman** [comment]
This is now implemented.
