### ISSUE TITLE
Test Logs in Gitlab are All White (Used to be Red for Failed, Green Check for Passed)

### ISSUE THREAD

**Issue by ryramos** [microsoft/playwright#32062]
We have upgraded from Playwright 1.37.1 to 1.46.0. We run our tests in Gitlab and after updating, our test logs in Gitlab are all in white font regardless of the result. Prior to the upgrade, tests that have Passed have green checkmark (it's now a white checkmark) while those that Failed are written in red (all white now too).

Before (1.37.1):
![image](https://github.com/user-attachments/assets/876698f2-a3a8-4aa6-b174-363cda96a4f5)

After (1.46.0):
![image](https://github.com/user-attachments/assets/ffa6808a-ec86-4c30-a8aa-87bdec13b1c1)

- [ ] I understand

**Comment by yury-s** [comment]
The reporter prints colored output only if  TTY terminal is detected. The check may fail on CI in some cases, if you want to override the behavior and have the reporters produce colored output, set `PLAYWRIGHT_FORCE_TTY` environment variables to control [the reporter](https://playwright.dev/docs/test-reporters#list-reporter) behavior.

**Comment by ryramos** [comment]
I just learned from another thread that this is apparently an intended change in behavior. I will try your suggestion (or maybe the FORCE_COLOR: 1 as suggested on another thread), thank you.
