### ISSUE TITLE
[Bug]: Skipped test due to beforeAll hook failed should be list as failed test in last run report

### ISSUE THREAD

**Issue by sonnguyenduc** [microsoft/playwright#32061]
### Version

1.4.5.1

### Steps to reproduce

Run a test with beforeAll hook always failed
```
test.beforeAll(async () => {
  expect(false).toBe(true);
});

test('First test will be failed due to beforeAll fail', async () => {
  expect(false).toBe(true);
});

test('Second test will be skipped but should be list as failed in "test-results/.last-run.json" report', async () => {
  expect(false).toBe(true);
});
```

### Expected behavior

The skipped test (due to beforeAll hook failed) should be list in failed test in "test-results/.last-run.json" report.
{
  "status": "failed",
  "failedTests": [
    "86d42566d3dc621e3269-49fc9d3b64ce18213494",
    "86d42566d3dc621e3269-3518ffacec00af422944"
  ]
}

### Actual behavior

Only first failed test is list in failed test
{
  "status": "failed",
  "failedTests": [
    "86d42566d3dc621e3269-49fc9d3b64ce18213494"
  ]
}

### Additional context

We try to re-run failed test only and observe that if test is skipped due to beforeAll hook fails, it will not run in our re-run CI job.

### Environment

```shell
System:
    OS: macOS 14.5
    Memory: 165.66 MB / 32.00 GB
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.19.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by sonnguyenduc** [comment]
We temporary fix this by patch the `ok()` function of class TestCase with
```
   ok() {
     const status = this.outcome();
-    return status === 'expected' || status === 'flaky' || status === 'skipped';
+    // check if test has annotations type 'skip'
+    const hasSkipAnnotation = this.annotations.some(annotation => annotation.type === 'skip');
+    return status === 'expected' || status === 'flaky' || (status === 'skipped' && hasSkipAnnotation);
   }
```

**Comment by yury-s** [comment]
We consider fixtures a part of the test runner, if a fixture fails then it is akin to a bug in the test runner, i.e. you cannot trust the test results before it is addressed. In such cases you can pick any test, run it and work on the fixture error until it's resolved. After the issue is resolved it's ok to rerun whole suite and check if there are failures, this should not be a common case.
