### ISSUE TITLE
[Bug]: --only-changed flag and project dependencies

### ISSUE THREAD

**Issue by andreicherechesbyx** [microsoft/playwright#32070]
### Version

1.46.0

### Steps to reproduce

1. Create a repo with multiple projects
2. Add dependencies to the project
3. Modify some of the test files
4. Run test with --only-changed flag

### Expected behavior

The dependencies are run before the actual modified tests.

### Actual behavior

Only the modified test are run, which fail without the dependencies.

### Additional context

I have multiple projects with a login setup as dependency

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 15.41 MB / 16.00 GB
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.40.1 => 1.46.0
```

**Comment by Skn0tt** [comment]
Hi Andrei! Thanks for reporting the issue. I'm having trouble reproducing this on my end. Could you provide me with a reproduction repository, as the issue form requested?

**Comment by andreicherechesbyx** [comment]
Repo: https://github.com/boatyardx/playwright-crossbrowser/tree/only-changed

I added a `console.log()` statement:

![image](https://github.com/user-attachments/assets/08a98e46-c7ec-4545-80ec-b549a8328524)

While the change to `console.log()` was detected, the setup dependency was not updated:

![image](https://github.com/user-attachments/assets/19cbb072-987c-47eb-9d37-4868ad32634b)

Also, is it intended for the entire test file to run instead of only the modified test?

**Comment by Skn0tt** [comment]
Thanks, that helps reproducing! I'll look into writing a fix.

> Also, is it intended for the entire test file to run instead of only the modified test?

Yes, that's intended.
