### ISSUE TITLE
How to set --proxy-header in browser using playwright api

### ISSUE THREAD

**Issue by ThatYodaCoder** [microsoft/playwright#32071]
In curl we use --proxy-header, so that the header will be used by proxy server only for authentication or routing the request thro prxy server. This header will not be sent in http request further
 
e.g: the request will routed thro proxy server, only if the PROXY_HDR_NAME is provided in proxy-header.

curl -v  --include  --proxy http://myproxy:8888  --proxy-header "PROXY_HDR_NAME: VALUE" <URL> 

 How to do it in browser using playwright API? i.e. add HTTP headers meant specifically for an HTTP or HTTPS proxy server
 
 I tried using page.setExtraHTTPHeaders, but it did not work.

**Comment by yury-s** [comment]
You can also try using [route.continue](https://playwright.dev/docs/network#modify-requests) to add additional headers.

This doesn't sound like a bug or feature request, please use our [community resources](https://playwright.dev/community/welcome) for general questions. If you think this is a bug in Playwright, please open a new issue and follow the bug template.

**Comment by ThatYodaCoder** [comment]
> You can also try using [route.continue](https://playwright.dev/docs/network#modify-requests) to add additional headers.
> 
> This doesn't sound like a bug or feature request, please use our [community resources](https://playwright.dev/community/welcome) for general questions. If you think this is a bug in Playwright, please open a new issue and follow the bug template.

@yury-s This can be a new feature request.

I don't understand How route will help in this case?  

Routing provides the capability to modify network requests that are made by any page in the browser context. 

My point is how can we add a header that is only meant for proxy server and will not be sent to the target server.
In curl command we specify this using --proxy-header.

But in play I don't see any way to do it using setExtraHeaders or route methods.

**Comment by yury-s** [comment]
Custom proxy headers are not supported in Playwright, only those that are sent with the web requests.
