### ISSUE TITLE
[Documentation]: document how to install playwright for pnpm

### ISSUE THREAD

**Issue by david-morris** [microsoft/playwright#32072]
### 🚀 Feature Request

When reading https://github.com/microsoft/playwright/issues/15369 it appeared that installing on a pnpm project was not possible.

`pnpm dlx playwright install` doesn't work.  It runs, but the system dependencies are not found by the runner later.

This is a problem because we like to avoid problems with our packaging due to incompatible package managers by using `"preinstall": "npx only-allow pnpm",`.

### Example

`npx` would be replaced with `pnpm dlx` in github actions workflows which need to update global playwright dependencies.

### Motivation

This will make it easier to set up Playwright dependencies in CI while using best-practice package management safeguards.
This will make it easier to cache Playwright code in CI.

**Comment by yury-s** [comment]
> `pnpm dlx playwright install` doesn't work. It runs, but the system dependencies are not found by the runner later.

If by 'system dependencies' you mean browser dependencies then you need to [pass](https://playwright.dev/docs/ci#introduction) `--with-deps` option. Can you describe exact steps you are doing and what's not working, preferably with the code of the minimal project.

**Comment by david-morris** [comment]
Thanks for the fast follow up! I figured out how to get this running:
1. install playwright as a direct dependency or add it to a `public-hoist-pattern` in your .npmrc
2. `pnpm exec playwright install-deps`
3. `pnpm exec playwright install`

`dlx` doesn't work, but that doesn't matter since the use case is covered.  I would like to see it documented better, though.

**Comment by yury-s** [comment]
> When I said it 'doesn't work' I meant that running playwright tests after that causes the tests to fail with a message telling me that I need to playwright install, not playwright install-deps.

What was the message and how would you like to improve it?

**Comment by mirao** [comment]
Note sure what a correct way is, but we install browsers + dependencies this way, e.g.:
```bash
# Update Playwright
$ pnpm update playwright@1.46

# Install browsers and dependencies
$ pnpm playwright install --with-deps
```

Tested on Ubuntu 24.04
It corresponds with https://playwright.dev/docs/intro#updating-playwright.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
