### ISSUE TITLE
[Regression]: v1.45.1: Google login not working on the new version

### ISSUE THREAD

**Issue by RuanAlesi** [microsoft/playwright#32081]
### Last Good Version

1.44.0

### First Bad Version

1.45.1

### Steps to reproduce

1. Using Playwright with Firefox (or using directly the built 1458 from v1.45.1)
2. Access www.google.com/account (or any website that uses Google Login as user authenticator)
3. Add the user email and click on 'Next'

### Expected behavior

The password should be visible

### Actual behavior

The browser looks tagged as unsafe, not allowing to continue.

### Additional context

It was working on the previous 1.44.0v (Firefox built 1449)

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 12.78 GB / 31.85 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Bash: 5.2.21 - C:\Program Files\Git\bin\bash.EXE
```

**Comment by yury-s** [comment]
Looks like Google doesn't want the web page to be used from a browser controlled by automation tools. It didn't work in Chromium either in 1.44. Stealth mode is not a priority for Playwright as our primary focus is on testing use cases.

**Comment by RuanAlesi** [comment]
> Looks like Google doesn't want the web page to be used from a browser controlled by automation tools. It didn't work in Chromium either in 1.44. Stealth mode is not a priority for Playwright as our primary focus is on testing use cases.

But it's not exactly Google, is it? It works using Firefox in 1.44, but not in 1.45
