### ISSUE TITLE
[Feature]: Allow ffmpeg binary path to be set

### ISSUE THREAD

**Issue by chronotc** [microsoft/playwright#32091]
### 🚀 Feature Request

There are certain use cases where we would like to set the `ffmpeg` binary path similar to how we can set the executablePath for Chromium.

### Example

This would enable us to specify the ffmpeg path when Playwright is used in environments such as AWS Lambda. 
It enables video recording via Playwright on AWS Lambda.

### Motivation

This extends what is currently capable of with Playwright on AWS Lambda.

**Comment by yury-s** [comment]
You can consider a workaround with creating a symlink as described in https://github.com/microsoft/playwright/issues/6491#issuecomment-838532534

Folding into https://github.com/microsoft/playwright/issues/6491
