### ISSUE TITLE
[Bug]: Intermittent "Object doesn't exist" error in playwright.

### ISSUE THREAD

**Issue by Visheshmongia** [microsoft/playwright#32090]
### Version

1.45.0

### Steps to reproduce

**Context**:
We are utilizing Playwright to convert HTML to PDF within our application. The process involves opening Chromium in headless mode and executing the print command. However, the process is intermittently failing with an "Object doesn't exist:" error specifically for the following URL whereas it works fine for rest of the URL's: 
	• URL: https://www.zeposia.com/content/commercial/us/zeposiadtc/en/understanding-uc.desktop.html?q0=dt&q1=di-s&q2=&q3=on&q4=r&q5=rfi&q6=ho&q7=ngb

**Error Message:**
Object doesn't exist: handle@1604d210c20d62d16f1f0cb2b77563d5

**Code Snippet:**

```java
private void initBrowser() {

        try (Playwright playwright = Playwright.create()) {
            BrowserType chromium = playwright.chromium();

            BrowserType.LaunchOptions browserLaunchOptions = new BrowserType.LaunchOptions();
            Browser browser = chromium.launch(setBrowserExecutable(browserLaunchOptions));
            browser.close();
        }
    }
PlaywrightObjects playwrightObjects = new PlaywrightObjects();
playwrightObjects = chromiumBrowser.getPlaywrightObjects(html2PDFOptions.getBrowserOptions(), playwrightObjects);
page.navigate(Request.getInput());
Page.PdfOptions pagePdfOptions = getPDFOptions(printOptions, outputFilePath);
page.pdf(pagePdfOptions);
if (Objects.nonNull(page))
    page.close();
if (Objects.nonNull(browserContext))
    browserContext.close();
if (Objects.nonNull(browser))
    browser.close();
if (Objects.nonNull(playwright))
    playwright.close();
```

**Issue:**
The error occurs intermittently. Our investigation suggests that the Playwright object (likely the Page or Browser) is being closed or invalidated before the print command completes, disrupting our PDF generation process.

**Environment:**

Playwright Version: 1.45.0
Chromium Version: 126.0.6478.126
Operating System: macOS 14.3
CPU: (10) x64 Apple M1 Max
Memory: 32.00 GB

**Steps to Reproduce:**

Run the provided code snippet to convert the specified URL to PDF.
Observe the error occurring intermittently, approximately every other attempt.
Expected Behavior:
The PDF should be generated consistently without encountering the "Object doesn't exist:" error.

### Expected behavior

The Pdf should be generated without breaking the flow and throwing the error "Object doesn't exist"

### Actual behavior

It breaks the flow with error "Object doesn't exist". And it does not return output pdf.

### Environment

```shell
**Environment:**

Playwright Version: 1.45.0
Chromium Version: 126.0.6478.126
Operating System: macOS 14.3
CPU: (10) x64 Apple M1 Max
Memory: 32.00 GB
```

**Comment by yury-s** [comment]
We need complete reproduction to run it locally and see the problem, can you provide one?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
