### ISSUE TITLE
[Bug]: Unknown "Secureplaywright-set-cookie-separator" prefix inside Set-Cookie from api response breaks tests on webkit

### ISSUE THREAD

**Issue by AnnoDomine** [microsoft/playwright#32099]
### Version

1.45.2

### Steps to reproduce

Create django backend with cookie auth.
Create a reactjs frontend to call cogin to get cookie auth token from backend.
Create a test to login with webkit environment.
Login will failed.

As i then manuel tested the login and checked the network log i figgured out as the Response header Set-Cookie does have the cookies inside but the access_token get prefiexed with "Secureplaywright-set-cookie-separator.
![image](https://github.com/user-attachments/assets/2876b766-06c7-4b3c-8d7b-bef05935bc53)

Login on chromium and firefox environments are running without problems.

### Expected behavior

The prefix should not crash the cookies from backend.

### Actual behavior

No login and further testing on webkit possible.

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 1.99 GB / 15.62 GB
    Container: Yes
  Binaries:
    Node: 20.15.1 - /usr/local/bin/node
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 9.6.0 - /usr/local/bin/pnpm
  IDEs:
    VSCode: 1.92.1 - /XXXXXXXXXX/eaa41d57266683296de7d118f574d0c2652e1fc4/bin/remote-cli/code
  Languages:
    Bash: 5.0.17 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.36.0 => 1.45.2
```

**Comment by yury-s** [comment]
The steps are too vague and require knowledge of a few specific frameworks. Can you please distill the steps into a minimal reproduction and share the code with us, so that we could run it locally and see the problem?

**Comment by AnnoDomine** [comment]
@yury-s 
Sure. Please give me a few days. I will create a simular repo.
