### ISSUE TITLE
[Bug]: Playwright UI – Duplicate Test Name leads to odd behavior (disappearing tests, playwright hanging) 

### ISSUE THREAD

**Issue by TobiasMende** [microsoft/playwright#32093]
### Version

1.46.0

### Steps to reproduce

1. Create a suite in a file.
2. Add two tests with the same name to them.
3. Add other tests in the file outside that suit.
4. Execute the suite in the file via Playwright UI

### Expected behavior

- Playwright UI should throw an error for the duplicate test name like it does without the `--ui` flag

### Actual behavior

- Playwright UI shows the duplicate test only once
- After executing the test, it is shown as not executed
- Executing other tests after this happens leads to them not being executed

Here is a screen recording to demonstrate and explain this behaviour:

https://github.com/user-attachments/assets/5f7a14c2-099e-4da5-aa22-7c5e496c94d6

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 5.32 GB / 64.00 GB
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.10.0/bin/yarn
    npm: 10.3.0 - ~/.nvm/versions/node/v20.10.0/bin/npm
  Languages:
    Bash: 5.2.26 - /opt/homebrew/bin/bash
  npmPackages:
    @playwright/test: ^1.46.0 => 1.46.0
```

**Comment by yury-s** [comment]
Duplicate test names are not allowed. If you run them in terminal you'll see the error, you can also see it in UI mode if you toggle output (<img width="50" alt="image" src="https://github.com/user-attachments/assets/67a3612c-f932-4f86-8be4-131680a336cb">). With that said, we should show the error clearly in the UI.

**Comment by WarrenMfg** [comment]
Duplicate browsers in the config's `projects` array will also demonstrate similar behavior.
