### ISSUE TITLE
[Feature]: Make classes that claim to extend EventEmitter do so in their type definition

### ISSUE THREAD

**Issue by gofr** [microsoft/playwright#32097]
### 🚀 Feature Request

I was just in a position where I wanted to use `Page.listenerCount()` to avoid adding multiple identical event listeners.

[The documentation](https://playwright.dev/docs/api/class-page) says:

> The Page class emits various events (described below) which can be handled using any of Node's native [`EventEmitter`](https://nodejs.org/api/events.html#events_class_eventemitter) methods, such as `on`, `once` or `removeListener`.

But [the type definition for the Page interface](https://github.com/microsoft/playwright/blob/236a8ac2ac00fe90701bdc3d6c36e840033c5a8e/packages/playwright-core/types/types.d.ts#L75) doesn't have `extends EventEmitter`. It only mentions `- extends: [EventEmitter]` in the jsdoc comment.

Is this on purpose? Could this interface (and other interfaces that extend EventEmitter) be changed to `extends EventEmitter` so I can use other EventEmitter methods without this being a type error?

I see some code for handling this here: https://github.com/microsoft/playwright/blob/9b3e0e5667ab52b5b750b732a9ec6367602dc5df/utils/generate_types/index.js#L224
but this code is never called for this class and a few others because they're in `utils/generate_types/overrides.d.ts`.

### Motivation

Ease usage with TypeScript.

**Comment by yury-s** [comment]
> But [the type definition for the Page interface](https://github.com/microsoft/playwright/blob/236a8ac2ac00fe90701bdc3d6c36e840033c5a8e/packages/playwright-core/types/types.d.ts#L75) doesn't have `extends EventEmitter`. It only mentions `- extends: [EventEmitter]` in the jsdoc comment.

This is a bug. I'll update the docs. We don't want to commit to supporting full EventEmitter API, only the basic add/remove listener methods.
