### ISSUE TITLE
[Bug]: UI Mode restart doesn't restart server with `reuseExistingServer: false`

### ISSUE THREAD

**Issue by karlhorky** [microsoft/playwright#32103]
### Version

1.46.0

### Steps to reproduce

1. Make sure you have `reuseExistingServer: false` configured (this is the default if unconfigured in `playwright.config.ts`)
2. Start [Playwright UI Mode](https://playwright.dev/docs/test-ui-mode#errors) with `playwright test --ui`
3. Wait for server to start
4. Click on the "Reload" button (screenshot below)
   ![Screenshot 2024-08-09 at 19 23 28](https://github.com/user-attachments/assets/2a39c47f-b6df-4e11-a3cb-53689853e0fa)
5. Click on the "Toggle Output" button (screenshot below)
   ![Screenshot 2024-08-09 at 19 32 49](https://github.com/user-attachments/assets/155cb7b9-0c99-488c-8f8e-a9f7204ba688)
6. Observe the "already used" error message(s)
   ```
   $ NODE_ENV=test yarn start
   [WebServer] Listening at http://localhost:3000
   warning package.json: No license field
   $ NODE_ENV=test yarn start
   warning package.json: No license field
   [WebServer] Listening at http://localhost:3010
   [WebServer] GET /icons/icon-48x48.png?v=dad84ffd6565cb5f517328c25c456b99 302 3.466 ms - 28
   [WebServer] GET /login 200 2.570 ms - 460184

   Error: http://localhost:3000 is already used, make sure that nothing is running on the port/url or set reuseExistingServer:true in config.webServer.

   Error: http://localhost:3000 is already used, make sure that nothing is running on the port/url or set reuseExistingServer:true in config.webServer.
   ```
   
   ![Screenshot 2024-08-09 at 19 16 14](https://github.com/user-attachments/assets/f524c054-c5f3-47eb-beb1-78a7e2ba6cd9)

Alternative step 4 (after macOS system sleep):

4. Sleep the macOS system (apple menu -> Sleep) and re-wake. Click on "Reload the page" link in the "UI Mode disconnected" screen:
   ![Screenshot 2024-08-09 at 19 17 33](https://github.com/user-attachments/assets/c36d0cc6-7248-45b2-97b9-d627b76bb01d)   

### Expected behavior

Servers are also restarted when clicking on "Reload" button or "Reload the page" if `reuseExistingServer: false`

### Actual behavior

Servers are not restarted when clicking on "Reload" button or "Reload the page" if `reuseExistingServer: false`, leading to "already used" errors described above

### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M1
    Memory: 70.97 MB / 16.00 GB
  Binaries:
    Node: 20.15.0 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - /opt/homebrew/bin/npm
    bun: 1.1.21 - /opt/homebrew/bin/bun
  IDEs:
    VSCode: 1.92.1 - /opt/homebrew/bin/code
  Languages:
    Bash: 5.2.0 - /opt/homebrew/bin/bash
```

**Comment by karlhorky** [comment]
Thanks for #32263 🙌 

I can confirm that [`@playwright/test@1.47.0`](https://github.com/microsoft/playwright/releases/tag/v1.47.0) no longer has the buggy behavior 🎉

**Comment by the-ult** [comment]
Using `1.47.2` and Nx, it is still really flaky.

The playwright does not seem to be able to properly start the dev-server.

(don't know if it is related, or if it should be a new issue)

```
Node           : 20.17.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.8.3

nx                 : 19.8.2
@nx/js             : 19.8.2
@nx/jest           : 19.8.2
@nx/linter         : 19.8.2
@nx/eslint         : 19.8.2
@nx/workspace      : 19.8.2
@nx/angular        : 19.8.2
@nx/cypress        : 19.8.2
@nx/devkit         : 19.8.2
@nx/eslint-plugin  : 19.8.2
@nx/playwright     : 19.8.2
@nx/storybook      : 19.8.2
@nrwl/tao          : 19.8.2
@nx/vite           : 19.8.2
@nx/web            : 19.8.2
@nx/webpack        : 19.8.2
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
@nx/eslint/plugin
@nx/jest/plugin
---------------------------------------
Community plugins:
@compodoc/compodoc         : 1.1.25
@ng-bootstrap/ng-bootstrap : 17.0.1
@ngrx/operators            : 18.0.2
@ngrx/signals              : 18.0.2
@storybook/angular         : 8.3.3
@testing-library/angular   : 17.3.1
ng-mocks                   : 14.13.1
ngxtension                 : 4.0.0
```
