### ISSUE TITLE
[Feature]: Add a warning message: Do not use TEMP or TMP environment variables, as they may cause browser installation failure.

### ISSUE THREAD

**Issue by barpit40** [microsoft/playwright#32105]
### 🚀 Feature Request

When a user defines the TEMP or TMP environment variable, it could potentially lead to the failure of the "npx playwright install" command.

 This scenario arises due to the fact that the path for the downloaded file is determined within the "[packages/playwright-core/src/server/registry/browserFetcher.ts](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/registry/browserFetcher.ts)" using the following line of code:

`const zipPath = path.join(os.tmpdir(), downloadFileName);`

Upon examining "os.tmpdir()" in "[node/lib/os](https://github.com/nodejs/node/blob/main/lib/os.js)", it can be seen that the path is determined as:

`path = process.env.TMPDIR ||
           process.env.TMP ||
           process.env.TEMP ||
           '/tmp';`

Therefore, if a user sets and defines the TMP or TEMP environment variable during a CI build, it could potentially trigger the "npx playwright install" command to fail. The error message that is displayed in such scenarios is:
[Error: ENOENT: no such file or directory, open '${temp}/playwright-download-chromium-ubuntu22.04-x64-1097.zip'] 

This error message is not only vague, but also challenging to debug. 
 
 Feature request: It would be beneficial to add a more explicit warning message in case of failure, indicating that the use of TMP and TEMP environment variables could potentially cause the "npx playwright install" command to fail. This would provide a clearer understanding of the issue and facilitate easier debugging.

### Motivation

I wasted lot of time debugging the reason for failure in CI build, the reason for failure is not obvious in this situation and a warning message.

**Comment by yury-s** [comment]
Can you explain what was the error that had you perplexed and what were the steps that led to it? `TMPDIR` and the other too are standard ways to specify alternative location of a temporary directory on unix systems. If one overrides them, they should be aware of the consequences. Playwright works fine if launched with custom temp dirs. Perhaps the directory was cleaned up under your feet or didn't have enough disk space? Would be helpful to see complete scenario.

**Comment by pavelfeldman** [comment]
I'll close it as per above. We need a temporary location for our files and overriding system values will invalid values will break many things, including Playwright.
