### ISSUE TITLE
[Bug]: Inconstant user agent setting

### ISSUE THREAD

**Issue by twalshOG** [microsoft/playwright#32106]
### Version

1.46.0

### Steps to reproduce

1. Clone https://github.com/twalshOG/PlaywrightBug on a Mac
2. Run tests `yarn && yarn test`
3. Note "User agent GLOBAL SETUP:" values all show Macintosh and "User agent IN TEST:" show Windows NT

Or just look at this run
https://github.com/twalshOG/PlaywrightBug/actions/runs/10325743021/job/28587967987#step:6:101

### Expected behavior

1. I would expect to see Macintosh (not Windows NT) as my use agent when running on a Mac.
2. I would expect to get the same use agent settings if I programmatically launch a browser or when the test launches the browser.

### Actual behavior

When I launch the browser using the chromium.launch or firefox.launch command on a Mac I get:
Mozilla/5.0 (**Macintosh**; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
or
 Mozilla/5.0 (**Macintosh**; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0

However when the browser is launched via a test I get:
Mozilla/5.0 (**Windows NT** 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.6613.18 Safari/537.36
or
Mozilla/5.0 (**Windows NT** 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0

### Additional context

Simple repository for reproducing the issue:
https://github.com/twalshOG/PlaywrightBug

Why I care:
I was trying to use [routeFromHAR](https://playwright.dev/docs/mock#recording-a-har-file) in global setup to save off some larger files and [use them](https://playwright.dev/docs/mock#replaying-from-har) for some of my slower tests.  However this did not work as the HAR captures has Mac user agent information and the test runs are looking for Windows NT.

### Environment

```shell
System:
  macos-latest: https://github.com/actions/runner-images/blob/macos-14-arm64/20240805.3/images/macos/macos-14-arm64-Readme.md
```

**Comment by yury-s** [comment]
This is working as intended, `globalSetup.ts` [doesn't pick up](https://github.com/microsoft/playwright/issues/14895) fixtures and settings from the config file. You are fully responsible for creating and configuring the browser there. If you want the browser to be launched with right user-agent, put the logic into a [setup project](https://playwright.dev/docs/next/test-global-setup-teardown#option-1-project-dependencies) add it as a dependency, this is our recommended way of creating global setup.

**Comment by twalshOG** [comment]
@yury-s 
I think adding the context as to why I care may have confused he issue.
The bug is that Playwright is setting user agent data claiming to be running on Windows NT 10, when it is not.
*Funny thing is that I actually get the correct values in my global setup.
I hope you will reconsider opening this bug.

If you would prefer, I could open a new bug that just focuses on the wrong OS/hardware getting in put into the user session.
