### ISSUE TITLE
Text explorer stuck on loading

### ISSUE THREAD

**Issue by jessica-dennis** [microsoft/playwright#32100]
Type: <b>Bug</b>

The test explorer is stuck on loading and this never resolves. I don't know what caused it but I think it started when I was using the debugger and working with a test that had previously been set to test.fail(). Restarting vs code, restarting my machine, editing the playwright config file haven't resolved the problem.
Steps to repro:
1. View test explorer
Actual: 'Loading' is displayed and never resolves. It's not possible to view or run any tests from the tree, and projects aren't displayed in the playwright section.
Expected: The test tree is displayed and the projects section is populated with checkboxes for each project in playwright config

![Screen Shot 2024-08-09 at 16 21 49 PM](https://github.com/user-attachments/assets/cbcd389c-98e3-4da0-adc6-8eac59c4193d)

Extension version: 1.1.7
VS Code version: Code 1.92.0 (Universal) (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|14, 33, 19|
|Memory (System)|16.00GB (0.53GB free)|
|Process Argv|--crash-reporter-id 8c7247b4-8409-40ff-b6a4-ae628c87c384|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718

```

</details>

**Comment by yury-s** [comment]
Can you share code of the project where it happens, so that we could try it locally? Does it happen on a fresh setup on another machine?

**Comment by yury-s** [comment]
Can you also do `cmd-shift-p -> Search Show Logs -> Extension Host` and see if there are any errors in the extension logs?

**Comment by jessica-dennis** [comment]
Hi Yury

Thanks for getting back to me. Unfortunately I can't share the code as it's in a private (work) repo but I'll ask one of my colleagues to try pulling the code on Monday and see if they get the same issue. I'm expecting that they won't because it was working fine for me previously and it doesn't seem to be related to a code change.
The logs are as follows:

**Comment by jessica-dennis** [comment]
Also, my colleague has now pulled the branch and the test explorer loaded with no issues.

**Comment by jessica-dennis** [comment]
UPDATE: Just upgraded to 1.46 and it's fixed. Fantastic timing 🎉 
Thanks again Yury

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
