### ISSUE TITLE
[Feature]: Converting JSHandle/ElementHandle to/from CDP backendNodeId/nodeId

### ISSUE THREAD

**Issue by moyix** [microsoft/playwright#32114]
### 🚀 Feature Request

The basic feature I'm requesting is some way to go back and forth between the high-level ElementHandle/JSHandle types and the low-level CDP identifiers like backendNodeId and RemoteObject/objectId. This would be helpful for being able to access some of the more advanced features of CDP while still enjoying the benefits of Playwright's higher-level APIs.

A possible interface might be something like:
- ElementHandle.getNodeId()
- ElementHandle.getBackendNodeId()
- ElementHandle.fromNodeId(nodeId: string)
- ElementHandle.fromBackendNodeId(backendNodeId: string)

### Example

This would be helpful for my current use case, which is trying to map the accessibility tree back to the corresponding DOM node (if any). The underlying CDP `Accessibility.getFullAXTree` provides a `backendNodeId`, but (as far as I can tell) there's no way to go from that to an ElementHandle I can use with the rest of Playwright.

I'd like to be able to write something like:

```ts
const cdpSession = await page.context().newCDPSession(page)
const axTree = await cdpSession.send('Accessibility.getFullAXTree')
for (const node of axTree) {
    if (!node.backendNodeId) {
        continue
    }
    const elem = await ElementHandle.fromBackendNodeId(node.backendNodeId)
    // Now we can use the element with the rest of Playwright
}
```

(As a side note, for this specific use case Puppeteer recently did gain the ability to directly access the DOM element for an AccessibilityTree node: https://github.com/puppeteer/puppeteer/pull/12233)

### Motivation

Particularly since Accessibility.snapshot() is now deprecated (https://github.com/microsoft/playwright/issues/16159), the only option is to use the lower-level CDP interface (as suggested in [this comment](https://github.com/microsoft/playwright/issues/16159#issuecomment-1209743311)). But that isn't very useful if the objects you get back from CDP can't be used with the rest of Playwright. Providing an interface for moving back and forth between CDP<->Playwright would bridge this gap and make CDPSession much more useful.

**Comment by pavelfeldman** [comment]
I edited the misleading comment, sorry about the confusion. You should not rely upon the Chromium internal a11y tree for anything at all. Use DOM-based conformant library like the one from Deque instead. Trying to consume raw CDP pushes you off the well-lit path into the unsupported niche.
