### ISSUE TITLE
Execution Time Per Line of Code Not Displayed Anymore in IntelliJ/Aqua IDE?

### ISSUE THREAD

**Issue by ryramos** [microsoft/playwright#32119]
I am using IntelliJ and Aqua IDE's and I remember in the past seeing the execution time per line code which looks like the below image (Note: I only copied the image from [23504](https://github.com/microsoft/playwright/issues/23504). I know it's a VS Code screenshot; but I just want to more clearly point out what I'm referring to.)
![image](https://github.com/user-attachments/assets/d19af0b8-1840-4663-b5f1-b345b6c3072e)

The only similar issue I can find is  [23504](https://github.com/microsoft/playwright/issues/23504) (where I got the screenshot above) - but this seems to be resolved already in 1.35 (a VS Code fix only?). Also,  [23504](https://github.com/microsoft/playwright/issues/23504) still displays the execution - just not consistent. In my case, execution time is not getting displayed anymore at all. I encountered this issue in 1.37. I upgraded to 1.46 but still not showing up.

- [ ] I understand

**Comment by pavelfeldman** [comment]
This tracker is for Playwrigh issues, please file yours against the Aqua IDE bug tracker.

**Comment by ryramos** [comment]
I thought it could be a Playwright issue because something similar happened in VS Code and was addressed on the Playwright side.

**Comment by ryramos** [comment]
> This tracker is for Playwright issues, please file yours against the Aqua IDE bug tracker.

I thought it could be a Playwright issue because something similar happened in VS Code and was addressed on the Playwright side.
