### ISSUE TITLE
[Bug]: target is closed error when running multiple spec files

### ISSUE THREAD

**Issue by tanyatech301** [microsoft/playwright#32113]
### Version

1.46

### Steps to reproduce

Running multiple spec files and everytime a new spec file is launched target is already closed even when there is no browser close option. 

Happens when on 1 worker only.

### Expected behavior

Test suites should continue to work. 

### Actual behavior

Target, browser or context is closed error message. 

### Environment

```shell
Mac and Chrome headless
```

**Comment by tanyatech301** [comment]
Let me know if more details are needed.

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
