### ISSUE TITLE
How to execute script?

### ISSUE THREAD

**Issue by Kikey-y** [microsoft/playwright#3212]
In puppeteer I can just use page.evaluate(), is it possible to do it in playwright too?

**Comment by mxschmitt** [comment]
Yep you can. Here you can see an example:

```js
// @ts-check
const playwright = require("playwright");

(async () => {
  const browser = await playwright.chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  console.log(await page.evaluate(() => window.navigator.userAgent))
  await browser.close();
})();
```
Or directly in your browser here: https://try.playwright.tech/?s=kgbgr
And documentation for it you can find here: https://playwright.dev/#version=v1.2.1&path=docs%2Fapi.md&q=pageevaluatepagefunction-arg

**Comment by Kikey-y** [comment]
Thank you mxschmitt, I got another question. How do you interecept requests? I tried page.setRequestInterception(true) but it says it's not a function.

**Comment by arjun27** [comment]
Hi @kikey-y, you can refer to [the network guide](https://playwright.dev/#version=v1.2.1&path=docs%2Fnetwork.md&q=handle-requests). Playwright relies on a `page.route` method. Let me know if you think there are any gaps in the docs.
