### ISSUE TITLE
[Feature]: Playwright Beta/Canary Test for VS Code

### ISSUE THREAD

**Issue by BenMcLean** [microsoft/playwright#32123]
### 🚀 Feature Request

Currently, the install process in the Playwright Test for VS Code extension has the `latest` version of Playwright hard-coded [on this line here](https://github.com/microsoft/playwright-vscode/blob/d21186f14c6b8a28eed1780ba69e546cbbdeaa97/src/installer.ts#L70).

I propose to provide some option for the user to choose other versions of Playwright such as `next` instead of `latest` if they want.

The option should include an appropriate warning that there are higher risks associated with beta software and that using the stable version is recommended.

### Motivation

This would let Playwright Test for VS Code extension users take advantage of new features in Playwright `next` / Beta / Canary releases and provide feedback on them or to specify a specific version string.

**Comment by pavelfeldman** [comment]
Thanks for filing this. It seems like this is a niche use case and given that there is a simple work-around of running 
```
npm i --save-dev @playwright/test@next
```
in vscode terminal, I'm closing it as out of scope.
