### ISSUE TITLE
[Bug]: Playwright Test for VSCode not always running global setup

### ISSUE THREAD

**Issue by twalshOG** [microsoft/playwright#32121]
### Version

1.46.0

### Steps to reproduce

1. Install VS Code and add the [Playwright Test for VSCode](https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright) extension.
2. Clone https://github.com/twalshOG/PlaywrightBug
3. Run the test (this project only has one test for simplicity sake) from the Playwright test explorer
![image](https://github.com/user-attachments/assets/388515e6-69a1-4c9b-aa92-f266ee14c1ba) <br>_Note that global setup ran_  <br>
![image](https://github.com/user-attachments/assets/980e2caf-8b4b-430a-8341-23f3cd46c781)
4. Run the test again via the test explorer 
![image](https://github.com/user-attachments/assets/9a8bfb18-3434-4489-9b2b-b9acbf6c6358) <br>
_Note that global setup did not run_

### Expected behavior

I would expect global setup to run each time I run 

### Actual behavior

Global setup not running on subsequent runs when tests are run via the Playwright test extension for VS Code.

### Additional context

**Work arounds**
1. Close and reopen VS Code
2. Manually trigger "Run global teardown"
![image](https://github.com/user-attachments/assets/267d58a2-dde9-4441-866a-8b36b233b6b3) <br>This makes it so the next run will run global setup, but runs after that will continue to skip global setup.

**Thoughts**
1. This look something was intentionally done
   1. If I am using my own [test web service](https://playwright.dev/docs/test-webserver) it stays up between runs
   2. The SETUP section of the TESTING: PLAYWRIGHT  VSCode bar disables Run global setup and enables Run global teardown.
2. Within many contexts this would work great, however it gets really unpleasant when trying to update/debug global setup

**Recommendations**
1. Document when global setup/teardown should be/will be executed when using VSCode
2. Add a setting that allows users to decide if they want to use the same global setup between test runs
![image](https://github.com/user-attachments/assets/3d861307-1b4b-499b-ac2e-296bb7093880)

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 195.63 MB / 32.00 GB
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
  IDEs:
    VSCode: 1.92.0 - /opt/homebrew/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.46.0 => 1.46.0 
  Test extension:
    Playwright Test for VSCode: v1.1.7
```

**Comment by twalshOG** [comment]
Looks like this is likely related to #32103

**Comment by pavelfeldman** [comment]
A setting makes sense to me.

**Comment by Charles-Gagnon** [comment]
Would such a setting also result in globalTeardown being ran after each test run? Right now it seems like it's never ran, which means you can end up with stale state that isn't cleaned up.
