### ISSUE TITLE
[Bug]: Incorrect user agent

### ISSUE THREAD

**Issue by twalshOG** [microsoft/playwright#32138]
### Version

1.46.0

### Steps to reproduce

1. Clone https://github.com/twalshOG/PlaywrightBug on a Mac
2. Run tests `yarn && yarn test`
3. Note "User agent IN TEST:" show Windows NT

### Expected behavior

I would expect to see Macintosh (not Windows NT) as my use agent when running on a Mac.

### Actual behavior

However when the browser is launched via a test I get:
Mozilla/5.0 (**Windows NT** 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.6613.18 Safari/537.36
or
Mozilla/5.0 (**Windows NT** 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0

### Additional context

When I directly launch a browser 
```
  const browserChrome = await chromium.launch();
  const browserFireFox = await firefox.launch();
```
I get the correct 
```
Mozilla/5.0 (**Macintosh**; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
 Mozilla/5.0 (**Macintosh**; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0
```
user agent values.

### Environment

```shell
System:
  macos-latest: https://github.com/actions/runner-images/blob/macos-14-arm64/20240805.3/images/macos/macos-14-arm64-Readme.md
```

**Comment by pavelfeldman** [comment]
When you say `use: { ...devices['Desktop Chrome'] }` in your config, we read the settings from the device library and initialize Playwright with them. One of the properties in these settings is `userAgent`. For Desktop Chrome, it is set to be Windows NT by default to be most representative. Similarly, it is set to macOS for Safari.

This allows running tests out of the box on affordable Linux VMs while emulating and testing Windows NT user experience. If you'd like to set Macintosh to be a default, override it in config:

```js
use: {
  ...devices['Desktop Chrome'],
  userAgent: 'Foo',
}
```
