### ISSUE TITLE
[Feature]: Add current page URL to Playwright screenshots and videos (eg. render the mock browser chrome)

### ISSUE THREAD

**Issue by karlhorky** [microsoft/playwright#32153]
### 🚀 Feature Request

Include the current page URL in the screenshots and videos produced when Playwright encounters a failure.

This would achieve parity with [Cypress](https://docs.cypress.io/guides/guides/screenshots-and-videos), which includes the URL in screenshots and videos produced on failure:

![66207355-3db42600-e6bb-11e9-9874-f6c56ace94bd](https://github.com/user-attachments/assets/b392a712-e05a-4f2f-b01b-b8d18a41c517)

![Screenshot 2024-08-14 at 12 23 47](https://github.com/user-attachments/assets/39293366-061d-4c0c-af2a-b5fcae098983)

### Example

In the Playwright UI, a mock browser chrome is rendered in the preview panel (the three colored dots, the page URL and the hamburger menu):

![Screenshot 2024-08-14 at 12 11 17](https://github.com/user-attachments/assets/e0635668-d952-4bfd-abbf-7f46d5c9de2d)

This is not present in the screenshots and videos taken during failure:

![Screenshot 2024-08-14 at 12 11 51](https://github.com/user-attachments/assets/4313cdd4-1434-424d-9764-035b66c0c0f9)

### Motivation

If the URL was visible in screenshots and videos taken on failure, it would greatly assist in debugging failing tests.

**Comment by pavelfeldman** [comment]
We encourage using trace viewer instead of using videos and screenshots. Videos and screenshots are a legacy feature, we don't want to promote those via adding more features.

**Comment by karlhorky** [comment]
Interesting, TIL about the [Trace Viewer GUI](https://playwright.dev/docs/trace-viewer) 🤔

Closing...
