### ISSUE TITLE
How can I open a full-screen browser in playwright codegen mode？

### ISSUE THREAD

**Issue by tanzhuo81** [microsoft/playwright#32165]
### Please do not submit this issue.

- [X] I understand
```[tasklist]
### Tasks
```

**Comment by tanzhuo81** [comment]
I have tried using the --viewport-size parameter, but the browser that opens is not truly full-screen. How should I proceed?

**Comment by dloreto** [comment]
Same here, i would like to have a resizable window, not a fixed width/height
