### ISSUE TITLE
[Feature]: Docker image for Node 22 or change Node from 20 to 22

### ISSUE THREAD

**Issue by lukaselmer** [microsoft/playwright#32177]
### 🚀 Feature Request

Release a Docker image built with Node 22 and describe it's usage here: <https://playwright.dev/docs/docker>

### Example

E.g. `docker pull mcr.microsoft.com/playwright:v1.46.0-jammy-22`, or change the default from 20 to 22.

### Motivation

The current docker images <https://github.com/microsoft/playwright/tree/main/utils/docker> are based on Node 20. With Node 22 LTS around the corner, and with issues / workaround which work only on Node 22 like <https://github.com/microsoft/playwright/issues/23662#issuecomment-2276416857>, it would be helpful to have a Docker image built with Node 22.

**Comment by pavelfeldman** [comment]
Our docker images are aligned with Node LTS. Marking for 1.47 to track in case Node 22 makes it to LTS.

**Comment by mxschmitt** [comment]
Note: Node.js 22 will enter long-term support (LTS) in October - until then we'll move this issue forward to the next release.

**Comment by dimkin-eu** [comment]
i found this a great idea - postfix node version ( at least for 1 release )
I.e. having
- mcr.microsoft.com/playwright:v1.48.0-jammy ( with node 20 )
- mcr.microsoft.com/playwright:v1.48.0-jammy-22 ( with node 22 )

moving to  `mcr.microsoft.com/playwright:v1.49.0-jammy`  with 22 only

**Comment by grafjo** [comment]
[node 22](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V22.md#22.11.0) was announced today to be the current lts version, so it would be awesome to bump the docker images to node 22

**Comment by Baloche** [comment]
Now that this is merged, when will the node 22 image be published to the microsoft artifact registry 🙂 ?

**Comment by mxschmitt** [comment]
> Now that this is merged, when will the node 22 image be published to the microsoft artifact registry 🙂 ?

As part of the next Playwright release.

**Comment by cbovis** [comment]
For posterity since it wasn't explicitly stated here, version 1.49+ is what you'll need for Node 22 🙂
