### ISSUE TITLE
[Bug]: --only-changed between concurrent branches

### ISSUE THREAD

**Issue by Skn0tt** [microsoft/playwright#32176]
### Version

latest

### Steps to reproduce

Consider this repository, with `B` being checked out:

```
	 o---o---o---B
	/
---o---1---o---o---o---A
```

Run `npx playwright test --only-changed=A`.

### Expected behavior

Only commits between `1` and `B` are taken into account for only-changed, because those are the commits of the `B` feature.

### Actual behavior

It also executes takes all commits between `1` and `A` into account.

### Additional context

The problems is that in https://github.com/microsoft/playwright/blob/a28f51a0f31b9499849c481b3658d0985b223c06/packages/playwright/src/runner/vcs.ts#L42-L43, we run `git diff` with `A...B`. Instead, we should use the [merge base](https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-merge-base.html) to resolve `1` based on `HEAD` and `A`, and then `git diff 1...B`.

### Environment

```shell
irrelevant
```

**Comment by pavelfeldman** [comment]
My expectation is to match `git diff with A...B` in this case as it gives me precise control over the behavior. Diffing against the merge base implicitly takes away the flexibility of A...B.

**Comment by Skn0tt** [comment]
We always compare against `HEAD`, so I don't think that flexibility exists in the first place.
