### ISSUE TITLE
[Feature]: Negate option for .toHaveScreenshot()

### ISSUE THREAD

**Issue by cctui-dev** [microsoft/playwright#32171]
### 🚀 Feature Request

Hi folks,

Being able to check screenshots during a test is very helpful. 

I'm testing a carousel and I want to assert that it has changed frame after clicking a button.

This is my code 

```
await expect(this.carousel).toHaveScreenshot(); // Take a screenshot of my element
await this.button.click(); // Click the button to carousel it onwards
await expect(this.carousel).not.toHaveScreenshot(); // Compare screenshot to the previous one
```

However, I want to assert that the screenshots are different and it seems by adding the `.not`  it fails with this error

`Error: A snapshot doesn't exist at blah/foo/presence-2-chromium-darwin.png, matchers using ".not" won't write them automatically.`

It would be great to have an option to check that an image **_has_** changed or the option to use a `.not`

### Example

```
await expect(this.carousel).toHaveScreenshot(); // Take a screenshot of my element
await this.button.click(); // Click the button to carousel it onwards
await expect(this.carousel).not.toHaveScreenshot(); // Assert with .not
```

or 

```
await expect(this.carousel).toHaveScreenshot(); // Take a screenshot of my element
await this.button.click(); // Click the button to carousel it onwards
await expect(this.carousel).toHaveScreenshot({ negate: true }); // Assert with new option
```

### Motivation

This would provide more flexibility to screenshot testing and remove the requirement to roll your own screenshot comparison functionality with pixelmatch which is already employed within Playwright for it's functionality.

Cheers!

**Comment by pavelfeldman** [comment]
We don't know which image to generate for `not`. In fact, we could probably just generate a 1px x 1px white dot as that image and claim that we did the job. The real solution is to pass the same name into your `toHaveScreenshot` call twice. Then we'll generate it during the first check.
