### ISSUE TITLE
[Bug]: `--only-changed` with no tests found should have exit code 0

### ISSUE THREAD

**Issue by Skn0tt** [microsoft/playwright#32180]
### Version

latest

### Steps to reproduce

Run with `--only-changed` if there are no tests. 

### Expected behavior

`No tests found` is printed, and it exits with exit code 0.

### Actual behavior

`No tests found` is printed, and it exits with exit code 1.

### Additional context

If folks want to use `--only-changed` in automation, then exit code 0 is a sane default.

### Environment

```shell
irrelevant
```

**Comment by gskierk** [comment]
It works the same without `--only-changed` flag and it seems to be intended. To exit with success, use `--pass-with-no-tests` flag.
