### ISSUE TITLE
[Bug]: Not able to install playwright, browsers failing to download

### ISSUE THREAD

**Issue by anand24816** [microsoft/playwright#32186]
### Version

1.38.1

### Steps to reproduce

npx playwright install
failing with below error

Error: Download failed: server returned code 409 body '﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>PublicAccessNotPermitted</Code><Message>Public access is not permitted on this storage account.
RequestId:560a1f8c-601e-008f-2e72-eff2a5000000
Time:2024-08-16T00:23:32.1928057Z</Message></Error>'. URL: https://playwright.azureedge.net/builds/chromium/1080/chromium-win64.zip

### Expected behavior

download was working till few moments ago.

### Actual behavior

browsers download are failing with 409 error.

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900HK
    Memory: 46.76 GB / 63.68 GB
  Binaries:
    Node: 20.16.0 - ~\AppData\Local\fnm_multishells\14728_1723764581365\node.EXE
    npm: 10.8.2 - ~\AppData\Local\fnm_multishells\14728_1723764581365\npm.CMD
  IDEs:
    VSCode: 1.92.1 - C:\Users\adubey\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.2.26 - C:\Users\adubey\AppData\Local\Programs\Git\usr\bin\bash.EXE
  npmPackages:
    @playwright/test: 1.38.1 => 1.38.1
    playwright: 1.38.1 => 1.38.1
```

**Comment by sjlevens** [comment]
I believe azureedge.net is down? https://downforeveryoneorjustme.com/playwright.azureedge.net?proto=https

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/32185
