### ISSUE TITLE
[Bug]: beforeAll and afterAll

### ISSUE THREAD

**Issue by Yasin1907** [microsoft/playwright#32195]
### Version

v1.46.0

### Steps to reproduce

While beforeAll and afterAll should run at the beginning and end of the test plan, they run after each faulty scenario.
![16-08-2024 16-40-36](https://github.com/user-attachments/assets/e656a4b2-e5d8-48c2-bdc4-f95a0cfbd053)

### Expected behavior

beforeAll and afterAll must run at the beginning and end of the test plan.

### Actual behavior

beforeAll and afterAll work after every faulty scenario.

### Environment

```shell
{
  "name": "playwright-project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "play:test": "npx playwright test",
    "play:debug": "npx playwright test --debug",
    "report": "npx playwright show-report",
    "test-s": "npx playwright test -g @sorting",
    "test-l": "npx playwright test -g @login",
    "test-c": "npx playwright test -g @cart"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/monikakonieczna/playwright-project.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/monikakonieczna/playwright-project/issues"
  },
  "homepage": "https://github.com/monikakonieczna/playwright-project#readme",
  "devDependencies": {
    "@playwright/test": "^1.46.0",
    "@types/faker": "^6.6.9",
    "@types/jest": "^29.2.4",
    "faker": "^5.5.3",
    "jest": "29.3.1",
    "ts-jest": "29.0.3"
  },
  "jest": {
    "transform": {
      "^.+\\.tsx?$": "ts-jest"
    },
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ],
    "testTimeout": 120000
  },
  "dependencies": {
    "jest-cli": "^29.3.1"
  }
}
```

**Comment by pavelfeldman** [comment]
As per out docs at https://playwright.dev/docs/api/class-test#test-after-all 

"Declares an afterAll hook that is executed once per worker after all tests."

Every time a test fails, the worker in which it was executed is considered compromised and is destroyed. New worker will be created and will run before/after to initialize the testing process.
