### ISSUE TITLE
[Bug]: HTML Test Report does not show Skipped tests under All

### ISSUE THREAD

**Issue by dsmeltz** [microsoft/playwright#32193]
### Version

1.44.1

### Steps to reproduce

Conditionally skip tests via test.skip inside of a test.describe.  (This allows a group of tests to be skipped.)

### Expected behavior

I would expect to see the skipped steps in the HTML Reporter while looking at the All option.

### Actual behavior

The skipped tests are only visible while looking at the Skipped option.

### Environment

```shell
System:
  OS: Windows 10 10.0.20348
  CPU: (48) x64 Intel(R) Xeon(R) Silver 4310 CPU @ 2.10GHz
  Memory: 1.45 TB / 1.50 TB
Binaries:
  Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
  npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
IDEs:
  VSCode: 1.92.2 - C:\Users\dsmeltz\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
Languages:
  Bash: 5.1.16 - C:\Windows\system32\bash.EXE
npmPackages:
  @playwright/test: ^1.44.1 => 1.44.1
```

<img width="596" alt="All" src="https://github.com/user-attachments/assets/46dfc950-fec3-404f-a1c9-6e093796ebce">
<img width="591" alt="skipped" src="https://github.com/user-attachments/assets/0c6fe07d-5fc4-45fb-ab4e-d93f5c3b80df">

**Comment by pavelfeldman** [comment]
That was an intentional (arguable) change to the UX. Users perceive skipped tests as not important, hence wanted them out of the way under All.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
