### ISSUE TITLE
[Feature]: Support HTML report file name customization

### ISSUE THREAD

**Issue by ilorwork** [microsoft/playwright#32198]
### 🚀 Feature Request

Support user-customization for the HTML report file name.

### Example

Code Example:
```
import { defineConfig } from '@playwright/test';

export default defineConfig({
  reporter: [
    [
      "html",
      {
        fileName: "test-results.html", // Currently not supported
        outputFile: "myFile.html", // Currently not supported
      },
    ],
});
```

Important to mention these arguments already being supported in other reporters such as `json` and `junit`:
```
import { defineConfig } from '@playwright/test';

export default defineConfig({
  reporter: [
    ['json', {  outputFile: 'test-results.json' }] // Supported
  ],
});
```

### Motivation

This will allow customization and clearance for users, rather than the general `index.html` default name.

**Comment by pavelfeldman** [comment]
HTML report is a folder, not a file, so you should specify outputFolder: https://playwright.dev/docs/test-reporters#html-reporter

**Comment by ilorwork** [comment]
@pavelfeldman
The file still could be renamed, I've already created the code that supports it, please reopen this feature request, I'll open a PR and link it to this issue.
If you still have rejects I would love to hear.
