### ISSUE TITLE
[Bug]: Playwright extension does not recognize the tests anymore

### ISSUE THREAD

**Issue by AlexDorha** [microsoft/playwright#32199]
### Version

playwright@1.46.0

### Steps to reproduce

Playwright extension is not able to recognize the tests anymore

VS Code version: 1.92.2
Playwright version: 1.46.0
Playwright extension version: latest 

Given: Tests were created in tests folder
           playwright.config.ts is configured to find the tests in './tests'
When: I go to Testing tab in order to run the tests
Then: I should see the tests there and be able to run them
Actual bug: No tests are displayed, "Install additional test extensions.." button is displayed
                   Into "projects" zone there is nothing displayed for check/uncheck
                   
Into playwright.config.ts i have 2 projects, chromium and edge
If i want to run from cmd everything is ok, playwright is working, parameters are working
Everything is ok from cmd, only from this extension is not working anymore

I think last updates of VSCode or Playwright are the problems but I am not sure
I have tried to install again the playwright, restart VS, clean cache, reinstall VSCode
Also I have created a new project with playwright from scratch, adding the extension and it was not working also
So is not working for new and old projects of mine

<img width="885" alt="Screenshot 2024-08-16 180428" src="https://github.com/user-attachments/assets/914d3893-513a-43c7-9947-abf602b5916e">

### Expected behavior

Playwright extension is not able to recognize the tests anymore

VS Code version: 1.92.2
Playwright version: 1.46.0
Playwright extension version: latest 

Given: Tests were created in tests folder
           playwright.config.ts is configured to find the tests in './tests'
When: I go to Testing tab in order to run the tests
Then: I should see the tests there and be able to run them
Actual bug: No tests are displayed, "Install additional test extensions.." button is displayed
                   Into "projects" zone there is nothing displayed for check/uncheck
                   
Into playwright.config.ts i have 2 projects, chromium and edge
If i want to run from cmd everything is ok, playwright is working, parameters are working
Everything is ok from cmd, only from this extension is not working anymore

I think last updates of VSCode or Playwright are the problems but I am not sure
I have tried to install again the playwright, restart VS, clean cache, reinstall VSCode
Also I have created a new project with playwright from scratch, adding the extension and it was not working also
So is not working for new and old projects of mine

<img width="885" alt="Screenshot 2024-08-16 180428" src="https://github.com/user-attachments/assets/914d3893-513a-43c7-9947-abf602b5916e">

### Actual behavior

Playwright extension is not able to recognize the tests anymore

VS Code version: 1.92.2
Playwright version: 1.46.0
Playwright extension version: latest 

Given: Tests were created in tests folder
           playwright.config.ts is configured to find the tests in './tests'
When: I go to Testing tab in order to run the tests
Then: I should see the tests there and be able to run them
Actual bug: No tests are displayed, "Install additional test extensions.." button is displayed
                   Into "projects" zone there is nothing displayed for check/uncheck
                   
Into playwright.config.ts i have 2 projects, chromium and edge
If i want to run from cmd everything is ok, playwright is working, parameters are working
Everything is ok from cmd, only from this extension is not working anymore

I think last updates of VSCode or Playwright are the problems but I am not sure
I have tried to install again the playwright, restart VS, clean cache, reinstall VSCode
Also I have created a new project with playwright from scratch, adding the extension and it was not working also
So is not working for new and old projects of mine

<img width="885" alt="Screenshot 2024-08-16 180428" src="https://github.com/user-attachments/assets/914d3893-513a-43c7-9947-abf602b5916e">

### Environment

```shell
System:
   OS: Linux komey-dell 5.15.0-118-generic #128-Ubuntu SMP Fri Jul 5 09:28:59 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
   CPU: x86_64. 12 CPUs.Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz

Binaries:
- npm 10.8.2
- node v22.6.0
- playwright 1.46.0
- VS Code 1.92.1 eaa41d57266683296de7d118f574d0c2652e1fc4 x64
- Playwright VS Code Extension 1.1.7
```

**Comment by AlexDorha** [comment]
I have found another bug report with this problem
I have tried everything from here and nothing is working
https://github.com/microsoft/playwright/issues/32183

**Comment by pavelfeldman** [comment]
Could you follow the issue template and file a repro? We can't reproduce screenshots.

**Comment by pavelfeldman** [comment]
Sorry, our policy is clear - please follow the issue template so that we could act on the issue.
