### ISSUE TITLE
[Bug]: older test using playwright 1.43.1 no longer works

### ISSUE THREAD

**Issue by rgl** [microsoft/playwright#32206]
### Version

1.44.1

### Steps to reproduce

1. clone https://github.com/rgl/terraform-keycloak
2. enter the working directory `cd terraform-keycloak`
3. checkout the tested commit `git checkout 1179f1b1eab58381cbb52789d7ad73bed4db1176`
4. execute `docker compose --profile example-csharp-public-device build`
5. execute `docker compose --profile example-csharp-public-device run example-csharp-public-device-test`

### Expected behavior

I expected it to find chromium-1112, which is what ships with the container:

```console
$ docker run --rm -it mcr.microsoft.com/playwright:v1.43.1
Unable to find image 'mcr.microsoft.com/playwright:v1.43.1' locally
v1.43.1: Pulling from playwright
23828d760c7b: Pull complete 
aec0fdba0895: Pull complete 
97c23b74936c: Pull complete 
ae30868a8312: Pull complete 
Digest: sha256:c5ac43242674b2ae56bf2c91aaee3b188f2ffdb7b242c11ffeeeea6e994fd7b3
Status: Downloaded newer image for mcr.microsoft.com/playwright:v1.43.1
root@0e3b2e07d040:/# ll /ms-playwright/
total 32
drwxrwxrwx 7 root root 4096 Apr 12 18:41 ./
drwxr-xr-x 1 root root 4096 Aug 17 12:53 ../
-rwxrwxrwx 1 root root   98 Apr 12 18:40 .docker-info*
drwxrwxrwx 2 root root 4096 Apr 12 18:41 .links/
drwxrwxrwx 3 root root 4096 Apr 12 18:41 chromium-1112/
drwxrwxrwx 2 root root 4096 Apr 12 18:41 ffmpeg-1009/
drwxrwxrwx 3 root root 4096 Apr 12 18:41 firefox-1447/
drwxrwxrwx 4 root root 4096 Apr 12 18:41 webkit-1992/
root@0e3b2e07d040:/# 
```

### Actual behavior

It tried to use chromium-1129 instead of chromium-1112 (the version that actually ships in the used container):

```
Running 1 test using 1 worker

  ✘  1 [main] › main.spec.ts:6:5 › main (8ms)


  1) [main] › main.spec.ts:6:5 › main ──────────────────────────────────────────────────────────────

    Error: browserType.launch: Executable doesn't exist at /ms-playwright/chromium-1129/chrome-linux/chrome
    ╔══════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just updated to 1.46.1. ║
    ║ Please update docker image as well.                                  ║
    ║ -  current: mcr.microsoft.com/playwright:v1.43.1-jammy               ║
    ║ - required: mcr.microsoft.com/playwright:v1.46.1-jammy               ║
    ║                                                                      ║
    ║ <3 Playwright Team                                                   ║
    ╚══════════════════════════════════════════════════════════════════════╝

 
```

### Additional context

this also happens with later playwright versions, so I'm a bit puzzled as why this is happening.

AFAICT, I'm using the same version in the [docker image](https://github.com/rgl/terraform-keycloak/blob/1179f1b1eab58381cbb52789d7ad73bed4db1176/clients/example-csharp-public-device-test/Dockerfile), in [package.json](https://github.com/rgl/terraform-keycloak/blob/1179f1b1eab58381cbb52789d7ad73bed4db1176/clients/example-csharp-public-device-test/package.json), and [package-lock.json](https://github.com/rgl/terraform-keycloak/blob/1179f1b1eab58381cbb52789d7ad73bed4db1176/clients/example-csharp-public-device-test/package-lock.json), so why is this happening?

### Environment

```shell
n/a
```

**Comment by g-drouard** [comment]
Same here

**Comment by Skn0tt** [comment]
Hi! I've taken a look at your repo, and I agree that it's surprising to see Playwright 1.46.1 being executed. All places I could see refer to 1.43.1. Could it be possible that you're running `npm install` somewhere, and that's doing the upgrade? You could also try running `npm ls @playwright/test` to see where the package is resolved from.

If the issue still persists, please provide us with a more minimal reproduction. Happy to take another look then.
