### ISSUE TITLE
[Docs]: Confusing documentation about code coverage

### ISSUE THREAD

**Issue by alex-vukov** [microsoft/playwright#32216]
### Page(s)

https://playwright.dev/docs/next/api/class-coverage

### Description

The example on the page shows a single test and how coverage reporting is started in the beginning and stopped at the end of the test. It's unclear how to use the code coverage start and stop functions for a group of more than one tests which is almost always the case when we need coverage. I need information how to start the coverage reporting before all tests and stop the reporting after all the tests have passed. Or is coverage supposed to be started and stopped on every test?

**Comment by Skn0tt** [comment]
Hey Alex! This page contains API docs for a chromium-only coverage API. You're right that it doesn't provide guidance on how to set up coverage for your project - we don't have a great place for that in the docs, yet. In the meantime you can refer to https://github.com/microsoft/playwright/issues/7030.
