### ISSUE TITLE
[Feature]: Allow traces in test-results folder to have custom file extension e.g. `.pwtrace.zip`

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#32226]
### 🚀 Feature Request

Instead of using `.zip` use `.pwtrace.zip` as a file extension for trace files.

### Example

`trace.zip` -> `trace.pwtrace.zip`

or

`trace-1.zip` -> `trace-1.pwtrace.zip`

### Motivation

We like to identify trace files in our `test-results/` folder better. This is for a custom AzDO extension we are writing where we see a list files and would like to offer first-party Trace Viewer support.

HTML report doesn't work for us, since we use TRX file format in order to put the data back into AzDO. 

Note: This originates from the internal ODSP team.

**Comment by Skn0tt** [comment]
Hey ross, thanks for the pointer! We discussed this in our team meeting and agree that we don't want to break those users. Gonna revert.

**Comment by dgozman** [comment]
Closing as not planned.
