### ISSUE TITLE
[Bug]: Type Inference Issue in Playwright 1.46.1 with base.extend

### ISSUE THREAD

**Issue by lukasstransky** [microsoft/playwright#32229]
### Version

1.46.1

### Steps to reproduce

After upgrading to Playwright version `1.46.1`, TypeScript fails to infer the type of objects created using base.extend from the `@playwright/experimental-ct-react package`. This issue was not present in version `1.45.3`, where the same code worked without any type inference problems.

1. Install Playwright version 1.46.1.
2. Create a TypeScript file with the following content:

``` typescript
import { test as base } from '@playwright/experimental-ct-react';
import { Locator } from '@playwright/test';

interface BaseTestTryoutOption {
  author: string;
}

export type TryoutFixture = {
  iframe: Locator;
};

export const componentTest = base.extend<BaseTestTryoutOption & TryoutFixture>({
  author: undefined,
  iframe: () => {
    console.info('test');
  },
});
```

3. Compile the TypeScript file.

### Expected behavior

The TypeScript compiler should successfully infer the type of componentTest without requiring an explicit type annotation, as it did in Playwright version 1.45.3.

### Actual behavior

``` typescript
error TS2742: The inferred type of 'componentTest' cannot be named without a reference to '.pnpm/@playwright+experimental-ct-core@1.46.1_@types+node@20.9.0/node_modules/@playwright/experimental-ct-core'. This is likely not portable. A type annotation is necessary.
```

### Additional context

- Downgrading to Playwright version `1.45.3` resolves the issue.
- Explicit type annotations and type aliases do not resolve the issue in version `1.46.1`.
- The issue arises specifically when using the @playwright/experimental-ct-react and  `@playwright/experimental-ct-react17` package.

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
    Memory: 33.75 GB / 63.20 GB
  Binaries:
    Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.1 - ~\AppData\Roaming\npm\npm.CMD
    pnpm: 9.0.6 - ~\AppData\Roaming\npm\pnpm.CMD
  IDEs:
    VSCode: 1.92.2 - C:\Users\lukas.stransky\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.0.17 - C:\WINDOWS\system32\bash.EXE
```

**Comment by Skn0tt** [comment]
hi! the file compiled just right for me on TypeScript `5.5.4`. Could you try upgrading TypeScript to see if that fixes it?

**Comment by lukasstransky** [comment]
Hey, I already use the Typescript version `5.5.4`

**Comment by Skn0tt** [comment]
Could you provide a minimal reproduction repo? That'd help me understand what's going on there.

**Comment by lukasstransky** [comment]
Here is the repo -> https://github.com/lukasstransky/playwright-tryout/tree/main

I found out the issue is pnpm, if I install the packages with pnpm I get the issue but if I remove the pnpm setup and just use npm install it works.

**Comment by lukasstransky** [comment]
Thanks for the info. However, turning off the declarations isn’t a viable solution since it’s an npm package that gets published.

**Comment by Skn0tt** [comment]
> However, turning off the declarations isn’t a viable solution since it’s an npm package that gets published.

Are you publishing the Playwright test files as part of the package? If not, maybe you can use a separate tsconfig file for the test files.

**Comment by lukasstransky** [comment]
When I also add this dependency `"@playwright/experimental-ct-core": "1.46.1",` its working.
