### ISSUE TITLE
[Bug]: Playwright extension does not recognize the tests from a new project

### ISSUE THREAD

**Issue by AlexDorha** [microsoft/playwright#32221]
### Version

1.46.1

### Steps to reproduce

1. clone https://github.com/AlexDorha/Proba
2. create new project
3. npm init -y
4. npm init playwright@latest
   Use typescript => install browsers => put tests into ./tests
5. Install Playwright Extension
6. run tests from cmd with npx playwright test => passed

### Expected behavior

I expect to see the tests in Playwright extension based on the fact that is a simple template provided by install process

### Actual behavior

No tests are displayed in Playwright extension
Nothing is loading for determine the tests
I did not make any modification from install process
"Install additional test execution" button is displayed
No tests have been found in this workspace yet.

<img width="635" alt="Screenshot 2024-08-19 160604" src="https://github.com/user-attachments/assets/de3244e7-aa48-4faa-95ff-d5205ac4adbd">

<img width="394" alt="Screenshot 2024-08-19 160658" src="https://github.com/user-attachments/assets/7ec75b7a-bd0c-49d5-bcde-eac7ef50ed11">

<img width="632" alt="Screenshot 2024-08-19 160725" src="https://github.com/user-attachments/assets/4e83e1ee-df9c-4f2d-943d-6f93debe9773">

### Additional context

I left the install setup as it is, I just created a new project, install the extension and it was not working

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 9 4900HS with Radeon Graphics
    Memory: 6.63 GB / 15.42 GB
  Binaries:
    Node: 21.6.2 - ~\AppData\Roaming\npm\node.CMD
    npm: 10.8.2 - ~\AppData\Roaming\npm\npm.CMD
  npmPackages:
    @playwright/test: ^1.46.1 => 1.46.1
```

**Comment by AlexDorha** [comment]
I have latest version of VSCode installed

**Comment by pavelfeldman** [comment]
Environment info you provided does not include VS Code installation, do you know why?

**Comment by AlexDorha** [comment]
> Environment info you provided does not include VS Code installation, do you know why?

Version: 1.92.2 (user setup)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by Skn0tt** [comment]
Looking at your first screenshot, I can see a warning message in the bottom right that says `Please install Playwright Test via running 'npm i --save-dev @playwright/test\'`. That makes me think that the Playwright dependency is missing locally. Could you try running `npm install`?

**Comment by AlexDorha** [comment]
> Looking at your first screenshot, I can see a warning message in the bottom right that says `Please install Playwright Test via running 'npm i --save-dev @playwright/test\'`. That makes me think that the Playwright dependency is missing locally. Could you try running `npm install`?

yes, nothing is happening
I have made this multiple times
i click on refresh button from extension and the same message

**Comment by pavelfeldman** [comment]
Unfortunately, we can't reproduce this locally, so we can't act on the issue.

**Comment by znamm9guesty** [comment]
Faced such an issue in Cursor. It was fixed by updating the node version.  There was an issue with Cursor using an old node version
