### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by pratiekg** [microsoft/playwright#32220]
### Version

1.45.2

### Steps to reproduce

Go to Playwright.config.js 

import { PlaywrightTestConfig, defineConfig } from "@playwright/test";

error : Internal error: unable to connect to the test serverplaywrigh

npm 8.19.4     node v22.6.0

### Expected behavior

should not throw any error.
Done all possible steps to fix this issue

### Actual behavior

Not able to run tests file and options also not visible.

### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 924.14 MB / 32.00 GB
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    npm: 10.8.1 - ~/workspace/strings-frontend/node_modules/.bin/npm
  IDEs:
    VSCode: 1.92.2 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.45.2 => 1.45.2 
    playwright: 1.45.1 => 1.45.1
```

**Comment by Skn0tt** [comment]
Hi! It's hard to reproduce based on the provided instructions. Could you provide us with a reproduction repository, and the command you're trying to execute?

Also, the version of Node you mention under "Steps to reproduce" is different than the one listed in your environment. Could you verify which of the two versions is being used?

Thanks!

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
