### ISSUE TITLE
[Bug]: Firefox page.goto fails with PR_CONNECT_RESET_ERROR error code

### ISSUE THREAD

**Issue by abhijeetyaduwanshi** [microsoft/playwright#32239]
### Version

1.44.1

### Steps to reproduce

Use Case
1. Select a subscription (this will send an email to verify and activate the account)
2. Open email helper and click the activate link (navigate to set password page)
3. Fails to load the set password page

### Expected behavior

The set password page should be loaded and the next step should execute correctly

### Actual behavior

Times out, fails and an error screen is displayed

Error
```
Error: page.goto: Test timeout of 600000ms exceeded.

> 196672 |     await this.page.goto(url, {
         |                     ^
  196673 |       waitUntil: "domcontentloaded"
  196674 |     });
```

Screen
<img width="1282" alt="Screenshot 2024-08-20 at 5 16 52 PM" src="https://github.com/user-attachments/assets/a44c394e-9c2e-47ad-b10f-a7f886cb71d5">

### Additional context

This issue is intermittent and is specific to Firefox, and is working on Chrome.

### Environment

```shell
Firefox (Nightly) version: 125.0.1
Playwright version: 1.44.1
Node version: v18.18.2
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
