### ISSUE TITLE
[Feature]: Locator Alias

### ISSUE THREAD

**Issue by LinkPovilas** [microsoft/playwright#32246]
### 🚀 Feature Request

Allow the assignment of aliases to locators to improve the readability of test reports.

### Example

As locator method:
```javascript
page.getByRole('button', { name: 'Save' }).alias('Save button');

// Alternatively
page.getByRole('button', { name: 'Save' }).describe('Save button');
page.getByRole('button', { name: 'Save' }).describedAs('Save button');
```

Usage:
```javascript
const saveButton = page.getByRole('button', { name: 'Save' }).alias('Save button');
await saveButton.click();
```

### Motivation

It would enhance the readability of test reports for stakeholders, including business analysts, project managers, product owners or clients.

**Currently without aliases:**
![current](https://github.com/user-attachments/assets/bc24ee49-6bf4-49fd-a95c-f62b118db3bb)

**With aliases:**
![enhanced](https://github.com/user-attachments/assets/7ff54dbe-22db-4041-b2cc-4faeae0c92ab)

**Comment by Skn0tt** [comment]
Hi! Take a look at [test.step](https://playwright.dev/docs/next/api/class-test#test-step). Let me know wether that helps your usecase!

**Comment by Skn0tt** [comment]
Thanks for elaborating. Generally speaking, neither steps nor (potential) aliases will be a good way of hiding sensitive credentials. Even if the report doesn't visibly show the sensitive information, it will most likely still contain it in some internal representation. The only right solution here is to use less sensitive credentials.

For other usecases, we believe that `test.step` is sufficient.
