### ISSUE TITLE
is there any place to set click retry internal or number of attempts

### ISSUE THREAD

**Issue by bodycombathuang** [microsoft/playwright#32242]
Hi everyone,
I am using playwright+typescript, I have a locator. in my code, I have a statement
locator.click(),  if the locator cannot be found, I can see some errors like
retrying click action, attempt #218
      -   waiting 500ms
      -   waiting for element to be visible, enabled and stable
      -   element is not enabled
it retries more than 200 times at interval 500ms

is there any place to set the retry interval such as 2s (not 500ms) or set the max number of retries for click?

**Comment by Skn0tt** [comment]
Hi! There's no way of modifying the retry interval for `locator.click()` or setting the max number of retries. You can lower the timeout though, see https://playwright.dev/docs/actionability for more info.
