### ISSUE TITLE
Getting a random 'Invalid login' error while trying to log in using the Microsoft login while running the test.

### ISSUE THREAD

**Issue by balajitoverto** [microsoft/playwright#32249]
### Version

1.46.0

### Steps to reproduce

In global-setup.ts file by giving headless as true getting a Microsoft login as an invalid login
browser = await chromium.launch({ headless: true });
    context = await browser.newContext();
    const page = await context.newPage();

### Expected behavior

By giving headless as false the console we got
csrapp@0.0.0 e2e
> playwright test

Navigated to http://localhost:4200
Login button clicked and new window opened
Trying to find input with placeholder: someone@example.com
Found input placeholder: someone@example.com
Email filled
Password filled
Sign in button clicked
Yes button clicked
New window fully loaded
Authentication state saved

### Actual behavior

> csrapp@0.0.0 e2e
> playwright test

Navigated to http://localhost:4200
Login button clicked and new window opened
Trying to find input with placeholder: someone@example.com
Input with placeholder someone@example.com not found, trying next
Trying to find input with placeholder: Email, phone, or Skype
Input with placeholder Email, phone, or Skype not found, trying next
Trying to find input with placeholder: someone@example.com
Input with placeholder someone@example.com not found, trying next
Error: Error: Input field with the expected placeholders not found   

### Additional context

We are facing this error randomly; sometimes it works in the silent test.
I’ve attached the repo link; you can access the project from there, run it locally to reproduce the bug, and make any necessary corrections.
https://github.com/balajitoverto/playwright-sample.git

I previously reported a bug related to this issue
Bug link: https://github.com/microsoft/playwright/issues/32034

### Environment

```shell
OS: Windows
- Node.js Version: 20.14.11
- Playwright Version: 1.46.0
```

**Comment by Skn0tt** [comment]
Hi! I had a quick look at the trace file in your repo, and it looks to me that something doesn't work on your site. Do you expect Playwright to do something specific? What's the bug in Playwright in your opinion? If you could provide a more minimal repro, that'd be great for us to look into it.

**Comment by balajitoverto** [comment]
Playwright can't be able to find the placeholder of Microsoft login popup
i attached the trace zip file for your reference  
[trace.zip](https://github.com/user-attachments/files/16711589/trace.zip)
i got a error as like 
`Navigated to http://localhost:4200
Login button clicked and new window opened
Trying to find input with placeholder: someone@example.com
Input with placeholder someone@example.com not found, trying next
Trying to find input with placeholder: Email, phone, or Skype
Input with placeholder Email, phone, or Skype not found, trying next     
Trying to find input with placeholder: Email address or phone number     
Input with placeholder Email address or phone number not found, trying next
Error: Error: Input field with the expected placeholders not found
    at waitForInputField (C:\Users\balajitirupathi\Documents\GitHub\playwright-sample\src\app\e2e\utils\global-setup.ts:18:9)
    at globalSetup (C:\Users\balajitirupathi\Documents\GitHub\playwright-sample\src\app\e2e\utils\global-setup.ts:53:31)
    at Object.setup (C:\Users\balajitirupathi\Documents\GitHub\playwright-sample\node_modules\playwright\lib\runner\tasks.js:173:39)
    at taskLoop (C:\Users\balajitirupathi\Documents\GitHub\playwright-sample\node_modules\playwright\lib\runner\taskRunner.js:81:11)
    at TaskRunner.runDeferCleanup (C:\Users\balajitirupathi\Documents\GitHub\playwright-sample\node_modules\playwright\lib\runner\taskRunner.js:98:5)
    at TaskRunner.run (C:\Users\balajitirupathi\Documents\GitHub\playwright-sample\node_modules\playwright\lib\runner\taskRunner.js:53:9)
    at Runner.runAllTests (C:\Users\balajitirupathi\Documents\GitHub\playwright-sample\node_modules\playwright\lib\runner\runner.js:73:24)        
    at runTests (C:\Users\balajitirupathi\Documents\GitHub\playwright-sample\node_modules\playwright\lib\program.js:210:85)
    at t.<anonymous> (C:\Users\balajitirupathi\Documents\GitHub\playwright-sample\node_modules\playwright\lib\program.js:54:7)
Error: Invalid login!

   at ..\utils\global-setup.ts:97

   95 |     }
   96 |     if (browser) await browser.close(); // Ensure the browser is Error: Invalid login!

   at ..\utils\global-setup.ts:97

 `
 
![36](https://github.com/user-attachments/assets/767dee27-4b88-4b52-b3c1-157736f7bf6e)

**Comment by Skn0tt** [comment]
Most likely, there's something going wrong in your code. We don't provide debugging assistance, but here's some tips:

- try `getByPlaceholder(...).waitFor()`
- try debugging with `page.pause()`
- try simplifying this by moving it from global setup into a test

I'll go ahead and close the issue because it doesn't seem like there's something wrong with Playwright. If you do end up  finding a bug, please file a new issue and i'm happy to take another look.

**Comment by balajitoverto** [comment]
```
import { chromium, FullConfig, Page } from '@playwright/test';

const user_email = 'balajibalaji.tirupathi@toverto.com' || '';
const user_password = "Toverto@2023" || '';

const placeholders = ['someone@example.com', 'Email, phone, or Skype', 'Email address or phone number'];

async function waitForInputField(page: Page, placeholders: string[], timeout = 60000) {
  for (const placeholder of placeholders) {
    try {
      console.log(`Trying to find input with placeholder: ${placeholder}`);
      await page.waitForSelector(`input[placeholder="${placeholder}"]`, { timeout });
      return placeholder; // Return the placeholder that was found
    } catch (error) {
      console.log(`Input with placeholder ${placeholder} not found, trying next`);
    }
  }
  throw new Error('Input field with the expected placeholders not found');
}

async function globalSetup(config: FullConfig) {
  let browser;
  let context;
  let newWindow: Page;

  try {
    // Launch browser in headless mode
    browser = await chromium.launch({ headless: false });
    context = await browser.newContext();

    // Start tracing
    await context.tracing.start({ screenshots: true, snapshots: true });

    const page = await context.newPage();

    const baseURL = config.projects[0].use.baseURL ?? '';
  
    // Navigate to the URL
    await page.goto(baseURL);
    console.log(`Navigated to ${baseURL}`);
  
    // Wait for the login button and click it
    const [newPage] = await Promise.all([
      context.waitForEvent('page'),
      page.getByRole('button', { name: 'Login' }).click()
    ]);
    console.log('Login button clicked and new window opened');
  
    newWindow = newPage;
    await newWindow.waitForLoadState('domcontentloaded');

    // Determine the input placeholder based on the environment
    const input_placeholder = await waitForInputField(newWindow, placeholders);
    console.log(`Found input placeholder: ${input_placeholder}`);
    
    // Wait for the input field to be visible and interact with it
    await newWindow.getByPlaceholder(input_placeholder).click();
    await newWindow.getByPlaceholder(input_placeholder).fill(user_email);
    console.log('Email filled');
  
    // Wait for the "Next" button and click it
    await newWindow.getByRole('button', { name: 'Next' }).click();
  
    // Wait for the password field to be visible and interact with it
    await newWindow.getByPlaceholder('Password').click();
    await newWindow.getByPlaceholder('Password').fill(user_password);
    console.log('Password filled');
  
    // Wait for the "Sign in" button and click it
    await newWindow.getByRole('button', { name: 'Sign in' }).click();
    console.log('Sign in button clicked');
  
    // Wait for the "Yes" button and click it
    await newWindow.getByRole('button', { name: 'Yes' }).click();
    console.log('Yes button clicked');
  
    // Wait for the page to fully load
    await newWindow.waitForLoadState('load');
    console.log('New window fully loaded');
  
    // Save the authentication state
    await context.storageState({ path: 'e2e/auth.json' });
    console.log('Authentication state saved');
  
    // Stop tracing and save the trace file
    await context.tracing.stop({ path: 'e2e/trace.zip' });
  
    // Close the browser
    await browser.close();
  } catch (err) {
    console.log('Error:', err);
    if (context) {
      // Stop tracing and save the trace file in case of error
      await context.tracing.stop({ path: 'e2e/trace.zip' });
    }
    if (browser) await browser.close(); // Ensure the browser is closed on error
    throw new Error('Invalid login!');
  }
}

export default globalSetup;

```
in the above global setup file, we used `getByPlaceholder(...)`
