### ISSUE TITLE
[Bug]: --last-failed command not running skipped and broken test cases from the last build

### ISSUE THREAD

**Issue by amit-saini-tx** [microsoft/playwright#32254]
### Version

1.44.1

### Steps to reproduce

Have some results where you have failed, skipped and broken(timeout) test cases then try to run npx playwright test --last-failed and see how many test cases ran.

### Expected behavior

--last-failed should run all the failed, skipped and broken test cases from the previous build

### Actual behavior

--last-failed only running test cases having status failed but not running skipped and broken test cases

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 13th Gen Intel(R) Core(TM) i7-1355U
    Memory: 2.26 GB / 15.68 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.3.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.92.0 - C:\Users\amit\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.44.1 => 1.44.1
    playwright: ^1.44.1 => 1.44.1
```

**Comment by Skn0tt** [comment]
Hi! Not running skipped tests is per design, but we should be running timeouted test cases. Could you provide us with a reproduction case for what you're seeing so we can investigate?

**Comment by Skn0tt** [comment]
I went ahead and closed. If you come up with a repro, please open another issue!
