### ISSUE TITLE
[Bug]: 1.46.0 breaks waitForLoadState within route requests

### ISSUE THREAD

**Issue by pschroeder89** [microsoft/playwright#32253]
### Version

1.46.1

### Steps to reproduce

1. Add this method:
```
export async function addHeader(page: Page): Promise<void> {
    // Intercept requests and modify headers for all requests to domains
    await page.route('**/*', async (route, request) => {
      const url = new URL(request.url());
      const canaryHeader = {
        'canary-env': 'true',
      };
      // Merge canary header with original headers
      const originalHeaders = request.headers();
      const modifiedHeaders = {
        ...originalHeaders,
        ...canaryHeader,
      };
      await route.continue({ headers: modifiedHeaders });
    });
  }
}
```
Add a fixture that overrides page by calling the above method:
```
import { Page } from '@playwright/test';
import { addHeader } from '../helpers/commonFunctions';

export const pageOverride = async ({ page }: { page: Page }, use: (page: Page) => Promise<void>) => {
  await addHeader(page);
  await use(page);
};
```

In 1.45.3, the above works fine.
In 1.46.0+, the above fails on any `waitForLoadState('networkidle');` or `waitForLoadState('domcontentloaded');` call

### Expected behavior

I expect waitForLoadState to wait for the state and proceed.

### Actual behavior

waitForLoadState times out. It only registers that the "load" event fired.

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 86.53 MB / 32.00 GB
  Binaries:
    Node: 20.11.1 - ~/.asdf/installs/nodejs/20.11.1/bin/node
    npm: 10.2.4 - ~/.asdf/plugins/nodejs/shims/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.45.3 => 1.45.3
```

**Comment by Skn0tt** [comment]
I don't see `waitForLoadState` being called in the example code you provided. Could you please provide a full reproduction repo, so we can look at what's happening?

**Comment by pschroeder89** [comment]
@Skn0tt here's a better repro example:

```
import { test as Base } from '@playwright/test';

export const test = Base.extend({
    page: async ({ page }, use) => {
        page.route('**/*', async (route) => {
            await route.continue();
        })
        await use(page);
    }
});

test('break routes', async ({ page }) => {
    await page.goto('https://regain.us');
    
    const settingsButton = page.getByTestId('cookie-settings-button')
    const acceptAllButton = page.getByTestId('cookie-allow-all');

    await settingsButton.click();
    await acceptAllButton.click();
    await page.reload({ waitUntil: 'networkidle' });
});
```

I think that maybe we're triggering the reload while a network request is still being made due to the `acceptAllButton` being clicked, which is causing it to hang.
We see this consistently in a few places in our framework with 1.46.0 and 1.46.1, but none at all with 1.45.3. The above example also passes on 1.45.3.

**Comment by Skn0tt** [comment]
Thanks for the repro, that helped! We took a look and saw this in the trace:

<img width="1382" alt="Screenshot 2024-08-23 at 12 44 54" src="https://github.com/user-attachments/assets/ec308d09-ca41-43d9-afce-0c03d78dee2b">

The page performs a request to `https://events.betterhelp.com/com.snowplowanalytics.snowplow/tp2` that never finishes, so the `networkidle` event isn't triggered. This happens both with and without `page.route`. This is a good illustration as to why `networkidle` is discouraged. We'd recommend to remove it from your script.

**Comment by pschroeder89** [comment]
@Skn0tt Maybe you have a network policy that is blocking that URL, but it definitely goes through on my end. The test works fine without the route override, and only fails when I use it.
I've attached my trace, I hope that helps with debugging.
We do have a ticket to migrate off of `networkidle` in these scenarios, but as I said before, this also happens in some cases with `domcontentloaded`. Getting a repro of that that's easily accessible by your team will be much more difficult though, since the only places I see it are within logged-in flows. So hopefully the below trace can help pinpoint the route issue. 

[trace (19).zip](https://github.com/user-attachments/files/16731037/trace.19.zip)

**Comment by Skn0tt** [comment]
Thanks for the trace! I can see a request to `https://z.betterhelp.com/cdn-cgi/zaraz/t` that never finishes:
<img width="1549" alt="Screenshot 2024-08-28 at 08 21 13" src="https://github.com/user-attachments/assets/139e2ae9-c956-49e4-bfe8-392726bf5622">

That's what prevents `networkidle` from triggering. The issue with `domcontentloaded` sounds separate, please open another issue with a reproduction case for that once you're able to reproduce.
