### ISSUE TITLE
[Bug]: Test report says "undefined" when a promise is rejected inside expect.poll

### ISSUE THREAD

**Issue by bdcarr** [microsoft/playwright#32256]
### Version

1.46.1

### Steps to reproduce

1. Clone this sample repo https://github.com/bdcarr/playwright-poll-covers-error
2. `npm install && npm run test`

You can remove axios and just `return Promise.reject({ some: 'object', or: 'other' })` inside expect.poll, but I included the request & interceptor to explain our use case.

### Expected behavior

The test report prints the whole error object, same as happens when the error occurs outside of `expect.poll`.

### Actual behavior

The error printed in the report just says "undefined":
```
  1) test.spec.ts:19:5 › issue happens when request is inside expect.poll ──────────────────────────

    undefined

      20 |     await expect.poll(async () => {
      21 |         return request.get('https://www.fwoeifhwefwf.com/efhjio2wfhejilfuhwf');
    > 22 |     }).toMatchObject({ something: 'idk' });
         |        ^
      23 | });
      24 |
      25 | test('issue does not happen when request is outside expect.poll', async () => {

        at /Users/brycecarr/dev/src/my/playwright-poll-covers-error/test.spec.ts:22:8
```

### Additional context

In our actual repo, the report says "undefined: undefined". Not sure why it just says "undefined" once in the repro. Our real repo's on 1.40.1, maybe that's why.

### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 78.86 MB / 32.00 GB
  Binaries:
    Node: 20.15.1 - ~/.local/state/fnm_multishells/77311_1724290084305/bin/node
    npm: 10.7.0 - ~/.local/state/fnm_multishells/77311_1724290084305/bin/npm
  IDEs:
    VSCode: 1.92.2 - /usr/local/bin/code
  Languages:
    Bash: 5.2.32 - /opt/homebrew/bin/bash
  npmPackages:
    @playwright/test: ^1.46.1 => 1.46.1
```

**Comment by Skn0tt** [comment]
Thanks, can reproduce! We'll look into it.
