### ISSUE TITLE
[Bug]: Confirmation Dialog within page frame not handled in Playwright

### ISSUE THREAD

**Issue by kjadhav-wk** [microsoft/playwright#32267]
### Version

1.45.3

### Steps to reproduce

Confirmation dialog box is not populating when we change the value from the dropdown. I have attached the screenshot of the page. Actually, this is old legacy page where dialogs are embedded in the page not at browser level. Below is the code snippet which I use to handle-
const waitForDialog = page.waitForEvent('dialog');
await usersUi.goToUserPage(testData.user.code);
await usersUi.profile.userTypeSelect.selectOption({ label: data.userType });
const confirmDialog = await waitForDialog ;
expect(confirmDialog.message()).toBe(testData.expectedWarningMessage);

### Expected behavior

Confirmation dialog should be handled and dialog message should be correct
![Dialog](https://github.com/user-attachments/assets/fbe76ec6-eb4d-407b-9c97-7c876679b7c5)
.

### Actual behavior

Confirmation dialog is not appearing.

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 11.85 GB / 31.78 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.92.0 - C:\Users\krishnakant.jadhav\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.2.15 - C:\windows\system32\bash.EXE
  npmPackages:
    @playwright/test: ^1.45.3 => 1.45.3
```

**Comment by Skn0tt** [comment]
Hi Krishnakant! Could you provide us with a reproduction repo so we can take a look at it ourselves?

**Comment by Skn0tt** [comment]
On a second thought: You're waiting for the "dialog" event, but that's about dialogs at browser level.

Instead of waiting for the dialog to pop up, you can assert that it has the correct contents using `expect(page.getByText(testData.expectedWarningMessage)).toBeVisible();`.

Let me know if that helped!

**Comment by kjadhav-wk** [comment]
It is real time application code. It cannot be share outside the organization. Just to tell you the issue when we select value from drop down then confirmation dialog is not popping up. And it is within classic frame not browser level.

**Comment by Skn0tt** [comment]
The confirmation dialog not popping up when it should sounds like a bug within your application, not within Playwright. Have you given `expect(...).toBeVisible()` a try?

**Comment by kjadhav-wk** [comment]
Yes. Tried it is not working. Manually, when we change then confirmation dialog is popping but when we try via Playwright it is not working. I have attached some screenshot. Maybe that will help you.

![image](https://github.com/user-attachments/assets/945833b5-fa77-4f5c-a39c-62509ece5c52)
![image](https://github.com/user-attachments/assets/56c41bdf-b007-4aed-aacc-0d709aee1386)

**Comment by Skn0tt** [comment]
You can also try generating code for this using `codegen`: https://playwright.dev/docs/codegen#running-codegen

**Comment by Skn0tt** [comment]
I'll go ahead and close. If you think you found another bug, feel free to open another issue an provide a repro :D
