### ISSUE TITLE
[Feature]: Display the contents of `JSHandle@object` logs in the trace viewer

### ISSUE THREAD

**Issue by chris13524** [microsoft/playwright#32277]
### 🚀 Feature Request

Display the contents of `JSHandle@object` logs in the trace viewer

### Motivation

We use these a lot for logging but we can't see the contents of what's happening to help debug test failures.

<img width="203" alt="Screenshot 2024-08-22 at 10 00 49" src="https://github.com/user-attachments/assets/a08b6173-094b-4e31-8294-08341f689292">

**Comment by Skn0tt** [comment]
I'll go ahead and close. Feel free to create another issue and elaborate on the questions above if you still believe that Playwright should have this feature.

**Comment by chris13524** [comment]
We are logging objects like `console.log({ abc: 123 })` or `console.log({ someObj })`. Use case is it's easier than building a string
