### ISSUE TITLE
[Feature]: HTML reporter: preview html attachments

### ISSUE THREAD

**Issue by davidenke** [microsoft/playwright#32281]
### 🚀 Feature Request

Right now the generated html reporter provides an inline preview of attachments for `text/*` as string.
It would be nice to have rendered html for `text/html` instead.

### Example

We use [axe](https://github.com/dequelabs/axe-core) for accessibility testing in playwright.
The resulting report is appended to the `TestInfo` as attachment.

Reports are deployed internally to be shared with non-technical personnel.
The plain text preview of the html report is barely human readable and the need of downloading and opening the file locally is inconvenient.

### Motivation

It would allow to customize and extend the generated report. Using the existing attachment 
features, the changes needed are minimal.

Images and videos are previewed already.

This feature could also be opt-in with a feature flag:

```ts
const body = `<h4>Report</h4>...`;
testInfo.attach('report.html', { body, contentType: 'text/html', preview: true })
```

or a separate property allowing different contents for preview and download:

```ts
const body = `<h1>Report</h1>...`;
const preview = `<h4>Report Preview</h4>...`;
testInfo.attach('report.html', { body, contentType: 'text/html', preview })
```

_If wanted, I'd volunteer to draft a PR. 😊_

**Comment by Rohittater255** [comment]
It would be great if playwright can support reporting like extent report and allure report.
I would be happy to help there

**Comment by alionatudan** [comment]
Voting for this. Struggling currently with the same issue.

**Comment by cctui-dev** [comment]
+1 for this
