### ISSUE TITLE
[Feature] `text=` selector to match <input type="text" placeholder="This is placeholder">

### ISSUE THREAD

**Issue by mrudulp** [microsoft/playwright#3228]
In my opinion one should also consider "placeholder" when searching an element(input) by text. This is because most of the inputs can be identified by placeholders when it does not have a value. Becomes very useful if one needs to fill Text based on input's placeholder. So test code will look as follows
Element: `<input type="text" placeholder="This is placeholder">`
Code: `await page.fill(text="This is placeholder", "new value")`

**Comment by mxschmitt** [comment]
You could achieve that with the following code too, does this fit for your needs?
```js
await page.fill('[placeholder="This is placeholder"]', "new value")
```
Since `placeholder` is a DOM attribute. If you use it very often in your application, we would recommend to create a custom selector engine which would make something like that possible (no need for the brackets): `await page.fill('placeholder="This is placeholder"', "new value")`

**Comment by mrudulp** [comment]
Agree this would be solved by using `[placeholder="This is placeholder"]` but that introduces unnecessary need to add an attribute which essentially is a text on input till it has been added an explicit value. I do not think this needs a separate selector engine as it is one more case of different places for HTMLInputElement to find text. Something similar to this https://github.com/microsoft/playwright/issues/1427 where value attribute is searched under text selector engine, but this time needed for placeholder. I hope this makes it clear

**Comment by dgozman** [comment]
This makes sense. The only question is whether to match placeholder when there is some text in the input?
- If we don't, that would mean the previous selector does not work anymore after calling `fill()` which is not ideal.
- If we do, then we'll get matches for the text that is not on the page anymore, because browser does not render placeholder for non-empty input, which is also not ideal.

Given that, perhaps leaving it explicit is the best? There would be no surprises, even though you'll have to write `[placeholder="text"]`.

**Comment by mrudulp** [comment]
Hmm, if someone is requesting a placeholder when value is already there entered in the input box, we are talking about an invalid request from text selector engine perspective. To me Text selector engine is WYSIWYG. So at that point user must request for Value in the input box and not placeholder. As at that point I cannot see placeholder text. Mind you placeholder is still valid for css or xpath SE(s)

**Comment by dgozman** [comment]
> So at that point user must request for Value in the input box and not placeholder.

We do not currently match by value as well. If we do, should we match any kind of text that browser shows? What if there is a `date` input and it shows differently depending on your locale settings? What if browser shows `Jan` when you entered date in a numeric format, e.g. `01/01/01`? Or a `range` input - should we match its value, even if it is shown as a slider? I am hesitant to define strict rules here. That does not mean it's impossible, but it requires thorough thinking through many possible usecases.

**Comment by mrudulp** [comment]
yep DatePicker, Range are going to be tricky, otherwise input text value can be compared, in my opinion

**Comment by klctrl** [comment]
@mrudulp Another nice way of selecting input elements that only have a placeholder text in them -- or which are even completely empty -- would be by referencing the text around (usually above it or left to it) them, i.e. the text that usually describes the content of the input element (e.g. "Name", "Street", ...) to be filled out. 

Such a feature has been suggested in #2877.

Maybe something like `await page.fill('below="Name"', "Smith")` ?

**Comment by klhex** [comment]
Just wanted to highlight a similar feature request and discussion that recently took place for the Taiko test automation library: https://github.com/getgauge/taiko/issues/1624. Maybe the same approach would make sense in Playwright as well?

Also, maybe it would help supporting the feedback collection process if this issue's title was rephrased a bit to make it read less technical? E.g., "Make text-based selectors also work with placeholder input texts" or something like that...

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
