### ISSUE TITLE
[Feature]: Customized Report

### ISSUE THREAD

**Issue by Rohittater255** [microsoft/playwright#32298]
### 🚀 Feature Request

In  Automation Framework using Playwright we are adding third party libraries for reporting like extent report or allureReport
I would like to similar suggest to create feature in Playwright for reporting.
This would be helpful

### Motivation

Playwright currently does not have any mechanism to generate custmozed reports like allure/extent report
So most of Automation Engineer need to write custom code for reporting which is quite waste of time
We can provide inbuilt support for reporting in Playwright to overcome this issue

**Comment by yury-s** [comment]
Playwright exposes [reporter API](https://playwright.dev/docs/test-reporters#custom-reporters) that can be employed to extend it with custom reporters. Is it not working for you scenario? Can you provide some examples on what is currently lacking?

**Comment by Rohittater255** [comment]
Reporter API is only for Node.js?

**Comment by dgozman** [comment]
@Rohittater255 That's right. Playwright has its own test runner for Node.js with custom reporters support. For other languages, check whether your test runner of choice supports custom reporters - most of them actually do.
