### ISSUE TITLE
[Question] loop through, click & Download Files

### ISSUE THREAD

**Issue by osmenia** [microsoft/playwright#3229]
I'm having some troubles in trying to get PLW to loop through elements on a page and click them and download files, save to bufffer. 

`const { chromium } = require("playwright");
const fs = require("fs");

(async () => {
  const browser = await chromium.launch({ headless: false });
  const crContext = await browser.newContext({ acceptDownloads: true });
  const page = await crContext.newPage();
  await page.goto(
    "https://file-examples.com/index.php/sample-documents-download/sample-xls-download/"
  );

  const handles = await page.$$("#table-files td.text-right.file-link");

  for (num in handles) {
    const [download] = await Promise.all([
      page.waitForEvent("download"), // wait for download to start
      num.click("a.btn")
    ]);
    const path = await download.path();
    fs.readFile(path, function (err, data) {
      if (err) throw err;
      console.log(data);
    });
  }

  await page.close();
  await browser.close();
})();`

is num elementHandle?
i am getting Error "TypeError: num.click is not a function".

I am downloading File (write on disk ) and then read file to buffer. Is there any better way to write file to buffer. 
what is download.createReadStream();? is it possible with download.createReadStream(); create buffer?

tnx a lot

**Comment by pavelfeldman** [comment]
You should replace `for (num in handles)` with `for (num of handles)`.

**Comment by pavelfeldman** [comment]
Reading from file to buffer is fine, createReadStream is reading from the same file.

**Comment by osmenia** [comment]
Tnx a lot
