### ISSUE TITLE
[Bug]: Storagestate is not working in GithubActions

### ISSUE THREAD

**Issue by marloncabracaGL** [microsoft/playwright#32302]
### Version

1.44.1

### Description

I followed the instructions from official documentation about authentication using storage state https://playwright.dev/docs/auth
 It works on my Mac machine locally nevertheless on the linux instance of github actions even though the state is saved in the json file, the state is not loaded so my test fails because pages are in login. 

### Expected behavior

Pages should load for a couple seconds and then load the homepage. 

### Actual behavior

Context is load with the storage state but it is not being translated to the browser page instead it loads with login.
Again it works on mac

### Additional context

**auth.setup.ts**
```
setup("authenticate", async ({ page }) => {
  await page.goto(`${process.env.BASE_URL}`);
  const loginPage = new LoginPage(page);
  await loginPage.logIn();
  await page.waitForTimeout(3000);
  await page.context().storageState({ path: authFile });
  // const data = await readFile(authFile, "utf-8");
  // console.log("Context after login");
  // console.log(data);
// this prints correctly the data
});

```

**playwright.config.ts**
```
  projects: [
    // Setup project
    { name: "setup", testMatch: /.*\.setup\.ts/ },
    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
        storageState: "playwright/.auth/user.json",
        bypassCSP: true,
      },
      dependencies: ["setup"],
    },
```

I have tried loading again the context in beforeeach, and using test.use but that didnt worked
I compared the storage/json file on different parts of the execution and it is working fine. The values are correct

### Environment

```shell
Github Action
Operating System
  Ubuntu
  22.04.4
  LTS
```

**Comment by bhushantbn** [comment]
what the exact error u got using github actions?

**Comment by marloncabracaGL** [comment]
> what the exact error u got in github actions?
I dont have an error in the execution but the browser does not load with the state

**Comment by yury-s** [comment]
How do you know it's the browser not loading in right state? You can [read cookies](https://playwright.dev/docs/api/class-browsercontext#browser-context-cookies) from the context on GHA and check that it contains all expected values. If it's still not working, we need a full repro.

**Comment by marloncabracaGL** [comment]
> How do you know it's the browser not loading in right state? You can [read cookies](https://playwright.dev/docs/api/class-browsercontext#browser-context-cookies) from the context on GHA and check that it contains all expected values. If it's still not working, we need a full repro.

Hey @yury-s  As you can see the cookies are here
![image](https://github.com/user-attachments/assets/13a37276-4711-484f-a228-c00db8db1352)

![image](https://github.com/user-attachments/assets/db77f76b-f08d-4fe4-9930-eb6a06940851)

**Comment by yury-s** [comment]
> Hey @yury-s As you can see the cookies are here

Nice, thanks for confirming, try recording a trace and see what is sent to the server over the network and what they respond and if there is any discrepancies with the local behavior. Something must be different between your local setup and GHA. To take an action on this report, we need a full reproduction example which we could run ourselves and see the problem.

**Comment by marloncabracaGL** [comment]
thanks @yury-s tomorrow I will try the trace and add the sample report

**Comment by marloncabracaGL** [comment]
After looking into traces, I noticed a request that was not using the correct env variable on CI. So this is not a bug. Thanks anyway.
