### ISSUE TITLE
[Bug]: Run Select Configuration Not Showing Any Browsers

### ISSUE THREAD

**Issue by conradwt** [microsoft/playwright#32315]
### Version

1.46.1

### Steps to reproduce

1. git clone https://github.com/conradwt/playwright-test
2. open project
3. click the example.spec.ts file
4. Reveal in Test Explorer
5. Click Select Configuration...
6. No browser options are listed for selection

### Expected behavior

I expected to see the following within VSCode:

![Screenshot 2024-08-25 at 4 49 46 AM](https://github.com/user-attachments/assets/c69cf4f8-59d9-4643-950a-6beeda10364a)

### Actual behavior

I see the following within VSCode:

![Screenshot 2024-08-25 at 4 51 45 AM](https://github.com/user-attachments/assets/1f9204b4-4c77-4810-8f80-e1810d4d43db)

### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 13.48 GB / 64.00 GB
  Binaries:
    Node: 20.16.0 - ~/.asdf/shims/node
    Yarn: 1.22.22 - /opt/local/bin/yarn
    npm: 9.9.3 - ~/.asdf/shims/npm
  IDEs:
    VSCode: 1.92.2 - /usr/local/bin/code
  Languages:
    Bash: 5.2.32 - /opt/local/bin/bash
  npmPackages:
    @playwright/test: ^1.46.1 => 1.46.1
```

**Comment by dgozman** [comment]
Closing as per above.
