### ISSUE TITLE
[internal] [playwright-test] › babel.spec.ts:135:5 › should not transform external is failing

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#32311]
Good Node.js version: 22.6.0
Bad Node.js version: 22.7.0

repro: 

```
nvm install 22.7.0
npm run ttest babel.spec.ts:135:5
```

Workaround: `export NODE_OPTIONS="--no-experimental-detect-module"`

Changelog: https://github.com/nodejs/node/releases/tag/v22.7.0#:~:text=Module%20syntax%20detection%20is%20now%20enabled%20by%20default.

**Comment by dgozman** [comment]
Filed upstream issue https://github.com/nodejs/node/issues/54861.

**Comment by mxschmitt** [comment]
This is fixed and we updated the expectation in https://github.com/microsoft/playwright/pull/32695.
