### ISSUE TITLE
[Bug]: Incorrect Output is received

### ISSUE THREAD

**Issue by NarenQE** [microsoft/playwright#32312]
### Version

10.8.1

### Steps to reproduce

I ran the below code:
```js
import { test, expect } from '@playwright/test';

test.beforeAll(async () => {
    console.log("This is beforeAll hook...")

})

test.afterAll(async () => {
    console.log("This is afterAll hook...")

})

test.beforeEach(async () => {
    console.log("This is beforeEach hook...")

})

test.afterEach(async () => {
    console.log("This is afterEach hook...")

})

test.describe('Group 1', () => {

    test('Test 1', async ({ page }) => {
        console.log('This is Test 1...')

    })

    test('Test 2', async ({ page }) => {
        console.log('This is Test 2...')

    })

})

test.describe.only('Group 2', () => {

    test('Test 3', async ({ page }) => {
        console.log('This is Test 3...')

    })

    test('Test 4', async ({ page }) => {
        console.log('This is Test 4...')

    })

})
```
### Expected behavior

This is beforeAll hook...       // Executed once before all tests
This is beforeEach hook...      // Executed before each test in Group 2
This is Test 3...               // First test in Group 2
This is afterEach hook...       // Executed after Test 3
This is beforeEach hook...      // Executed before Test 4
This is Test 4...               // Second test in Group 2
This is afterEach hook...       // Executed after Test 4
This is afterAll hook...        // Executed once after all tests

### Actual behavior

Running 2 tests using 2 workers
[chromium] › Grouping.spec.js:39:9 › Group 2 › Test 3
This is beforeAll hook...
This is beforeEach hook...
[chromium] › Grouping.spec.js:44:9 › Group 2 › Test 4
This is beforeAll hook...
This is beforeEach hook...
This is Test 4...
This is beforeEach hook...
[chromium] › Grouping.spec.js:44:9 › Group 2 › Test 4
This is beforeAll hook...
This is beforeEach hook...
This is Test 4...
[chromium] › Grouping.spec.js:44:9 › Group 2 › Test 4
This is beforeAll hook...
This is beforeEach hook...
This is Test 4...
This is beforeAll hook...
This is beforeEach hook...
This is Test 4...
This is beforeEach hook...
This is Test 4...
This is Test 4...
[chromium] › Grouping.spec.js:39:9 › Group 2 › Test 3
[chromium] › Grouping.spec.js:39:9 › Group 2 › Test 3
This is Test 3...
This is afterEach hook...
This is afterAll hook...
[chromium] › Grouping.spec.js:44:9 › Group 2 › Test 4
This is afterEach hook...
This is afterAll hook...
  2 passed (4.6s)
This is afterEach hook...
This is afterAll hook...
  2 passed (4.6s)

To open last HTML report run:

  npx playwright show-report

PS C:\Users\Naren\PlaywrightAutomation>

This is afterEach hook...
This is afterAll hook...
  2 passed (4.6s)

To open last HTML report run:

  npx playwright show-report

PS C:\Users\Naren\PlaywrightAutomation>

This is afterEach hook...
This is afterAll hook...
  2 passed (4.6s)

To open last HTML report run:

  npx playwright show-report

PS C:\Users\Naren\PlaywrightAutomation>

This is afterEach hook...
This is afterAll hook...
  2 passed (4.6s)

To open last HTML report run:

  npx playwright show-report

PS C:\Users\Naren\PlaywrightAutomation>
This is afterEach hook...
This is afterAll hook...
  2 passed (4.6s)

To open last HTML report run:

  npx playwright show-report
This is afterEach hook...
This is afterAll hook...
  2 passed (4.6s)

To open last HTML report run:
This is afterEach hook...
This is afterAll hook...
  2 passed (4.6s)
This is afterAll hook...
  2 passed (4.6s)
  2 passed (4.6s)

To open last HTML report run:

  npx playwright show-report

### Additional context

I am getting incorrect output continuously. If I made any mistake kindly revert back

### Environment

```shell
PS C:\Users\Naren\PlaywrightAutomation> npx envinfo --preset playwright
npm error code ENOENT
npm error syscall lstat
npm error path C:\Users\Naren\AppData\Roaming\npm
npm error errno -4058
npm error enoent ENOENT: no such file or directory, lstat 'C:\Users\Naren\AppData\Roaming\npm'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: C:\Users\Naren\AppData\Local\npm-cache\_logs\2024-08-24T14_12_14_572Z-debug-0.log
```

**Comment by yury-s** [comment]
Your tests are running [in parallel](https://playwright.dev/docs/test-parallel) on 2 workers, which is why before/afterAll are run on each of them. You can pass [`--workers=1`](https://playwright.dev/docs/test-parallel#disable-parallelism) to run them sequentially. If you just want all tests in a file to not run in parallel, you can set [fullyParallel](https://playwright.dev/docs/api/class-testconfig#test-config-fully-parallel) to false.

**Comment by NarenQE** [comment]
Thanks for the clarification. You can go ahead and close the bug


Regards,
Narendra Kumar D
