### ISSUE TITLE
[Question] Chorimium is lauched but unable to navigate to url as it just says about:blank

### ISSUE THREAD

**Issue by sreekanthjkprojects** [microsoft/playwright#3232]
Hi team,

Since couple of days now I have problem in navigating through my application on Chromium. Script launches chromium but does not put the url on the address bar, so it does remain at about:blank for long time. But same code working fine on other browsers.

browser = await playwright1.chromium.launch({headless:false});
    context = await browser.newContext();
    page = await context.newPage();
    await page.goto("https://xxxxxx"); // does not put PAGE_URL on address bar and launched browser will just //show about:blank

**Comment by pavelfeldman** [comment]
Does real Chrome browser open this url? The best would be to test with Chrome Canary. It might well be that Chrome no longer loads your page due to TLS or something.

**Comment by DJ-Glock** [comment]
It looks like mine issue: https://github.com/microsoft/playwright/issues/3148

Reboot of PC helped me. But it will be nice if you get browser logs by setting: `DEBUG=pw:browser` as it was recommended by @yury-s.

**Comment by aslushnikov** [comment]
> It looks like mine issue: #3148

@DJ-Glock Hard to say without more details here...

Closing this particular issue since the discussion with OP has stalled.
