### ISSUE TITLE
Locate and extract value of an element based on class name when the class has multiple parent div/class

### ISSUE THREAD

**Issue by senugu01** [microsoft/playwright#32329]
Example :  job title from Dice jobs board (https://www.dice.com/) " Test Manager - CCAR/CECL  "
![image](https://github.com/user-attachments/assets/50725cb1-ac5b-4776-b27a-b7b7832450fd)

Trying to replicate what has been done in the below article but with Dice.com as jobs board. 
https://www.roborabbit.com/blog/web-scraping-with-playwright-in-python/

Tried 
job_card = await page.locator("dhi-search-card").all()
job_element = card.locator("a")
job_title = job_element.inner_html()
as the code in the article is working for that particular jobs board, but didn't work for Dice. Maybe not using the correct locator. Please suggest.
```[tasklist]
### Tasks
```

**Comment by yury-s** [comment]
This doesn't sound like a bug or feature request, please use our [community resources](https://playwright.dev/community/welcome) for general questions. If you think this is a bug in Playwright, please open a new issue and follow the bug template.
