### ISSUE TITLE
[Question] Why upload a file larger then 50Mb is forbidden when upgrading to v1.40.0, I was using launchPersistentContext(), with options:  channel: 'chrome'. 

### ISSUE THREAD

**Issue by Iris-Chen** [microsoft/playwright#32320]
### Please do not submit this issue.

- [X] I understand

**Comment by yury-s** [comment]
This doesn't sound like a bug or feature request, please use our [community resources](https://playwright.dev/community/welcome) for general questions. If you think this is a bug in Playwright, please open a new issue and follow the bug template.
