### ISSUE TITLE
[Bug]: Unable to launch Chrome and Firefox in Incognito mode

### ISSUE THREAD

**Issue by IamRanjeetSingh** [microsoft/playwright#32321]
### Version

1.46.0

### Steps to reproduce

I'm using the below code to launch Chrome and Firefox in Incognito mode. But I cannot see the **incognito icon** on the top right corner. 

```
using Microsoft.Playwright;

using IPlaywright playwright = await Playwright.CreateAsync();
await using IBrowser browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions()
{
    Headless = false,
    Channel = "chrome",
});
IBrowserContext browserContext = await browser.NewContextAsync();
IPage page = await browserContext.NewPageAsync();
Console.WriteLine("end");
```

### Expected behavior

I expect the Chrome and Firefox browser to open in Incognito mode with the **incognito icon** on the side.

![image](https://github.com/user-attachments/assets/448bfebe-8f4d-4e93-8edb-ce734d8bd38f)

### Actual behavior

The browser is getting launched without **incognito icon** on the side.

![image](https://github.com/user-attachments/assets/0eb9f3a1-64cf-40bd-bb46-5183e26d5a06)

### Environment

```shell
OS: Windows 11
Programming Language: C#
NuGet Package: 1.46.0
```

**Comment by yury-s** [comment]
Playwright creates the context which is not persisted on the disk, but it behaves similar to regular context which is why you don't see the icon. If you see any unexpected behavior of the page, please provide a repro.

**Comment by mhabsaoui** [comment]
OK.
I am testing our Chrome Extension and came to the test case where the Extension si Allowed to run in Icognito mode.
 
Now the thing I am wondering is, if PW is already running in Isolated/Icognito context, how is it possible to have the tested Extension working with "Allow in Icognito" setting disabled (in chrome extensions details page...) **by default** during testing 🤔 ?

<img width="710" height="99" alt="Image" src="https://github.com/user-attachments/assets/289ad2ce-5bde-4d79-9af4-d5f24aabe49c" />

PS: Our Extension manifest.json has the  `"incognito": "spanning",`

Thanks for your enlightenment.
