### ISSUE TITLE
[Bug]: Playwright UI crashes with "Out of Memory"

### ISSUE THREAD

**Issue by chrispelzer76** [microsoft/playwright#32336]
### Version

1.46.1

### Steps to reproduce

* have a complex website to test 
* have a testcase with 100+ test.step(...) inside and 100+ of expect and actions inside of these - in my current case, the metadata tab says: Counts - pages: 1, actions: 387, events: 223
* run the test
* after completion click and/or hover through the actions tree - it will switch through the numberous snapshots of the website on the right side
* eventually the whole Plawright UI window crashes with an "Out of Memory" Error Message.

With any test of this size it is 100% reproducible within 10 seconds of browsing through the snapshots.
![image](https://github.com/user-attachments/assets/190618dd-5c45-42cb-a53e-f9527333831c)
![Anmerkung 2024-08-27 121156](https://github.com/user-attachments/assets/0286470f-d5a4-416b-84ee-7cc832d9d4b2)

### Expected behavior

no crash

### Actual behavior

crash!

### Additional context

Is there a way to reduce the memory footprint of playwright? We want to use it on non-dev notebooks with only 16 GB RAM, but that seems to be impossible with our scenario. 

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    Memory: 5.09 GB / 31.69 GB
  Binaries:
    Node: 20.11.0 - ~\scoop\apps\nodejs-lts\current\node.EXE
    Yarn: 4.3.1 - ~\scoop\apps\nodejs-lts\current\bin\yarn.CMD
    npm: 10.2.4 - ~\scoop\apps\nodejs-lts\current\npm.CMD
```

**Comment by chrispelzer76** [comment]
Yes, it reproduces with the trace viewer as well. 
I can send you our trace.zip. Is there a way to do that non-public?

**Comment by Skn0tt** [comment]
Sure thing. Send it over to simonknott at microsoft com and i'll take a look.

**Comment by Skn0tt** [comment]
Thanks, I received the trace and can repro the crash on my end. @yury-s i've forwarded it to so you can also take a look. I'll investigate what exactly is leading to the crash and what we can do to prevent it.

**Comment by Skn0tt** [comment]
We found a memory leak in our code. Gonna work on a fix.

**Comment by ScarletMcLearn** [comment]
Its still occurring in : "@playwright/test": "1.49.1",

**Comment by Skn0tt** [comment]
That's a pretty old version. If it's also occuring in `1.53.0`, file another bug.

**Comment by ScarletMcLearn** [comment]
Thank you for your response. @Skn0tt I have reported another : [https://github.com/microsoft/playwright/issues/36337](https://github.com/microsoft/playwright/issues/36337)
