### ISSUE TITLE
[BUG] IP:PORT Proxy doesnt work on playwright-firefox

### ISSUE THREAD

**Issue by SentoxAIO** [microsoft/playwright#3233]
- Playwright Version: ^1.2.1
- Operating System: Windows
- Node.js version: v14.1.0.
- Browser: Firefox

**Code Snippet**
```javascript
options.proxy = {
	server: "<port>:<ip>",
};

await firefox.launch(options)
```
Orginal Error:
![image](https://user-images.githubusercontent.com/57367608/88946588-b9591200-d28f-11ea-9042-8763041dec78.png)
It seems like that ip:port proxies don't work with playwright-firefox.

When you put http:// before it the browser starts, but throws
this error:
![image](https://user-images.githubusercontent.com/57367608/88946691-d68de080-d28f-11ea-86e4-ec0f4c8ddae2.png)

**Comment by aslushnikov** [comment]
@SentoxAIO the following works for me (with my personal proxy):

```js
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await firefox.launch({
    headless: false,
    proxy: {
      server: 'http://40.112.209.181:3128',
      username: process.env.PROXY_USERNAME,
      password: process.env.PROXY_PASSWORD,
    },
  });
  const page = await browser.newPage();
  await page.goto('https://example.com');
})();
```

**Comment by SentoxAIO** [comment]
@aslushnikov  I am talking about proxies without an authentication (password & username).

**Comment by FoonkG** [comment]
Indeed, proxies with user:pass authentication work well on playwright-firefox but proxies without user:pass authentication don't.

**Comment by aslushnikov** [comment]
@SentoxAIO, @FoonkG: I tried with a local [charles proxy](https://www.charlesproxy.com/) running on `localhost:8888` - worked fine:

The script with playwright `v1.3.0`: 

```js
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await firefox.launch({
    headless: false,
    proxy: {
      server: 'http://127.0.0.1:8888'
    },
  });
  const page = await browser.newPage();
  await page.goto('https://example.com');
})();
```

Any more details to help me reproduce this?

**Comment by aslushnikov** [comment]
FYI: current `playwright@next` has a new proxy implementation for Firefox, so please give it a try - maybe it'll fix things on your end
