### ISSUE TITLE
[Please read the message below] Can we run the playwright test and see the test report in docker container. ( like dagger)

### ISSUE THREAD

**Issue by GeitRavi** [microsoft/playwright#32335]
### Please do not submit this issue.

- [X] I understand

**Comment by GeitRavi** [comment]
Is there a way to integrate the Dagger ci/cd tool to run the playwright UI test and export the output test report.

**Comment by yury-s** [comment]
This doesn't sound like a bug or feature request, please use our [community resources](https://playwright.dev/community/welcome) for general questions. If you think this is a bug in Playwright, please open a new issue and follow the bug template.
