### ISSUE TITLE
[Bug]: VSCode extension "Play" button won't render for wrapper utilities

### ISSUE THREAD

**Issue by ahmednkhan24** [microsoft/playwright#32344]
### Version

Playwright: 1.44.1, VSCode Extension: 1.1.7

### Steps to reproduce

![image](https://github.com/user-attachments/assets/0cfb22e9-ed90-4a9d-88e4-34b6c3dbd848)

![image](https://github.com/user-attachments/assets/e65fd949-c87e-422a-9912-d457bc7c308c)

Create a wrapper function around the `test` utility:

`wrapper.ts`
```typescript
import { test, expect } from '@playwright/test';

export function testWrapper(
  title: string,
  testFunction: (page: Page) => Promise<void>
) {
  test.describe(title, () => {
    test('scenario 1', async ({ page }) => {
      // scenario 1
      // ...
      await testFunction(page);
    });

    test('scenario 2', async ({ page }) => {
      // scenario 2
      // ...
      await testFunction(page);
    });
  });
}
``` 

Consume the wrapper in a test:

`test.playwright.ts`
```typescript
import { testWrapper } from './testWrapper';

testWrapper('Testing the example @e2e', async (page) => {
  await expect(page.getByTestId('example')).toBeVisible();
});
```

### Expected behavior

To have the VSCode Playwright extension recognize the `test.playwright.ts` file as a test and then render the "Play" button next to it.

![image](https://github.com/user-attachments/assets/4728a92b-6244-4a6b-aba8-f6099ca9873a)

### Actual behavior

No play button is rendered.

![image](https://github.com/user-attachments/assets/27bfefc5-5556-482f-9235-c4d27dbcb436)

### Environment

```shell
System:
    OS: Windows 10 10.0.22631
    Memory: 31.84 GB / 63.66 GB
  Binaries:
    Node: 18.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.3.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    playwright-msw: ^2.2.1 => 2.2.1
```

**Comment by yury-s** [comment]
This is working as intended, you can find the play button in the gutter of `testWrapper.ts` where `test` is called. You can also see and run all the tests in the test tree of the extension. Showing tests at the location of the wrapping function is not supported. If you want to share some functionality between the tests, the recommended approach is to use [fixtures](https://playwright.dev/docs/test-fixtures).
