### ISSUE TITLE
[Bug]: unexpected expect.extend behaviour

### ISSUE THREAD

**Issue by LeviticusMB** [microsoft/playwright#32340]
### Version

1.46.1

### Steps to reproduce

1. Clone https://github.com/LeviticusMB/toHaveText-with-arrays
2. `npm i && npm exec playwright test`

### Expected behavior

1. I expected `expect.extend()` to return a new function with the extensions available, without side-effects.
2. I also expected being able to call the original `expect` function from an extension without infinite recursion.

### Actual behavior

1. `expect.extend()` modifies the `expect` export from `@playwright/test` globally.
2. Because of (1) there is no way to call and re-use the original assertion function if I want to extend it to a new kind of object under test, so the extension ends up calling itself until the the code crashes.

### Additional context

Some background: We have this Playwright-inspired library [@onslip/automation](https://github.com/Onslip/automation) that can be used to automate Android and iOS devices (including Android emulators) with an API that is similar to the Playwright Library (`Page`, `Locator` etc). We use it to automate POS hardware (Point of Sale/Piece of ****—take your pick).

I wanted to add assertions for *our* version of `Locator` and to make the library integrate more or less seamlessly with Playwright Test, I'd like to use the same names (like `toHaveText()`). This turned out not only to not work, it also broke loads of existing tests that didn't even touch the result of `baseExpect.extend()`.

### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 995.13 MB / 32.00 GB
  Binaries:
    Node: 22.5.1 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.8.2 - /opt/homebrew/bin/npm
    pnpm: 9.7.0 - /opt/homebrew/bin/pnpm
  IDEs:
    VSCode: 1.92.2 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.46.1 => 1.46.1
```

**Comment by yury-s** [comment]
As a workaround you can save original matchers before extending the expect and later call them from your implementation:

```js
const originalToHaveText = (baseExpect as any).toHaveText; 

const dateExpect = baseExpect.extend({
  async toHaveText(this: ExpectMatcherState, date: Date, expected: string | RegExp, options?: { ignoreCase?: boolean, timeout?: number }): Promise<MatcherReturnType> {
...
      } else {
        originalToHaveText.call(baseExpect(date as Locator), expected, options);
      }
...
  },
});
```

would that work for your scenario?

**Comment by LeviticusMB** [comment]
I can't get that to work either ... `originalToHaveText` is ` (...u)=>new i(!1,...u)` which seems to return an `AsymmetricMatcher` when called:

```js
i {
  '$$typeof': Symbol(jest.asymmetricMatcher),
  sample: [ [ 'Node.js', 'Python', 'Java', '.NET' ], undefined ],
  inverse: false
}
```

Not sure what to do with this object? Need to build a `MatcherReturnType` from that somehow.

(I also tried to save `(baseExpect({}) as any).toHaveText`, but it seems the dummy `value` is captured so I can't provide the actual `Locator` when calling it later.)

**Comment by Skn0tt** [comment]
> 🚨 The below is only applicable if you're building a library on top of Playwright and are OK with using non-public things. Don't use this if you're using Playwright directly to write tests. 🚨

I think you won't be able to get to Playwright's matcher implementation from the outside. If you're fine with depending on a private API, you could do this:

```diff
diff --git a/tests/example.spec.ts b/tests/example.spec.ts
index 0cbbc12..ce5a2de 100644
--- a/tests/example.spec.ts
+++ b/tests/example.spec.ts
@@ -1,5 +1,8 @@
 import { test, expect } from '@playwright/test';
-import { expect as baseExpect, ExpectMatcherState, Locator, MatcherReturnType } from '@playwright/test';
+import { expect as baseExpect, ExpectMatcherState, MatcherReturnType } from '@playwright/test';
+
+// not part of Playwright's public API - could break in future versions!
+const { toHaveText } = require("playwright/lib/matchers/matchers");
 
 const dateExpect = baseExpect.extend({
   async toHaveText(this: ExpectMatcherState, date: Date, expected: string | RegExp, options?: { ignoreCase?: boolean, timeout?: number }): Promise<MatcherReturnType> {
@@ -11,7 +14,7 @@ const dateExpect = baseExpect.extend({
           baseExpect(date.toISOString()).toBe(expected);
         }
       } else {
-        baseExpect(date as Locator).toHaveText(expected, options);
+        toHaveText.call(this, date, expected, options);
       }
 
       return { pass: true, message: () => 'Date is correct' };

```

This passes the tests on my machine. It comes with the downsides of relying on a private API though. Since `expect` is part of our public API, I don't see any major changes to this - but we might move the file location around in random releases or change something about the implementation or, or, or. So depending on this is not the most straight-forward. You mention you're building a library on top of Playwright, so this hacky solution might be fine for your usecase.

**Comment by Skn0tt** [comment]
Happy to hear you solved your problem. As you can see, I deleted my comment with the recommendation because I really don't want anybody who doesn't understand the consequences of importing a private package to see it. But you seem to be aware of that, so have fun! :D I'll close the issue.
