### ISSUE TITLE
[Feature]: ZoomIn ZoomOut feature while scripts are running in headed mode

### ISSUE THREAD

**Issue by KAjayGoutham** [microsoft/playwright#32352]
### 🚀 Feature Request

expected : please provide a commands to set zoom level of web browser so that user can set the size in individual scripts it self 

actual : right now to do that we have to change the view ports but that is not much feasible 

### Example

after login i want to zoom in or zoom out of a specific page

### Motivation

in some scenarios like we apps supports only 85% of zoom level and in that level of zoom level only users can work else other may face resolution issue,

Note : to overcome resolution issues it would be better if we have this in track 
thank you in advance.

**Comment by Skn0tt** [comment]
You can set the zoom level today using the `document.body.style.zoom` DOM property, as outlined in https://stackoverflow.com/questions/69973429/how-can-we-achieve-browser-zoom-in-and-zoom-out-in-playwright. Does that work for you?

**Comment by yury-s** [comment]
Updating `style.zoom` will address some scenarios, like changing page layout, but playwright actions will not work properly at the moment. Folding this request into https://github.com/microsoft/playwright/issues/2497, please upvote that issue instead.

**Comment by KAjayGoutham** [comment]
> You can set the zoom level today using the `document.body.style.zoom` DOM property, as outlined in https://stackoverflow.com/questions/69973429/how-can-we-achieve-browser-zoom-in-and-zoom-out-in-playwright. Does that work for you?

No as @yury-s mentioned this code is not working properly, it is zooming out but not that stable it popping in and out the screen
