### ISSUE TITLE
[Feature]: method signature in the Documentation

### ISSUE THREAD

**Issue by grdamico** [microsoft/playwright#32353]
### 🚀 Feature Request

Sometimes it's a little bit tricky to understand the example because there is no method signature: https://playwright.dev/docs/api/class-locator . Please, is it possible to add them in the Documentation?

### Motivation

Sometimes from the example, it is not clear whether it is a different option or another parameter.

**Comment by Skn0tt** [comment]
Hi Grazia 👋 I can see method signatures for all of the class methods of `Locator`. What method specifically are you missing a signature for? If it's for `page.locator`, you can find that here: https://playwright.dev/docs/api/class-page#page-locator.

**Comment by grdamico** [comment]
Hi Simon! I happened to see this: "https://playwright.dev/docs/api/class-locator#locator-set-checked", I didn't think to look under the page (https://playwright.dev/docs/api/class-page#page-set-checked). Page seems better to me. Thank you.

**Comment by Skn0tt** [comment]
Alright, thanks! I can see method signatures on both links you shared. Does that mean we can close the issue?

**Comment by grdamico** [comment]
I think is still chaotic and I disagree you can see the method signatures in both pages:

`await page.getByRole('checkbox').setChecked(true);` in locator page (This is an example).

`await page.setChecked(selector, checked);
await page.setChecked(selector, checked, options);` in page page (This is a method signature).

For the reader, it appears chaotic, and the documentation is very well done. It's a shame not to have a refactoring and not to align the writing style.

However, I understand that there is a lot of work and this is not a priority, so we can close the conversation.
