### ISSUE TITLE
[Bug]: Page.route does not intercept web worker requests

### ISSUE THREAD

**Issue by iustinpericica** [microsoft/playwright#32355]
### Version

1.43.1

### Steps to reproduce

1. Have a web application with few web workers that performs http requests
2. Add `await page.route("**/*", route => {
      console.log("Intercepted:", route.request().url());
      return route.continue();
    });` at the beggining of the test
3. Http requests initiated by web workers are not catched

Or see the repro repo I created - https://github.com/iustinpericica/repro_pw_web_workers

### Expected behavior

I would expect to see those web worker requests.

### Actual behavior

I can not see web worker requests.

### Environment

```shell
Windows, Browser Tests
```

**Comment by iustinpericica** [comment]
Repro: https://github.com/iustinpericica/repro_pw_web_workers

**Comment by Skn0tt** [comment]
Thanks for the repro! This is interesting. It seems to work fine for Webkit and Firefox, but not for Chromium:

```bash
❯ npx playwright test

Running 3 tests using 3 workers
[chromium] › example.spec.ts:3:5 › has title
Intercepted: http://localhost:3000/browser-sync/socket.io/?EIO=4&transport=polling&t=P6TgL9K&sid=ZmkUOqVAdPgLLx8bAAAC
Intercepted: http://localhost:3000/browser-sync/socket.io/?EIO=4&transport=polling&t=P6TgL9N&sid=ZmkUOqVAdPgLLx8bAAAC
Intercepted: https://jsonplaceholder.typicode.com/posts/1
[webkit] › example.spec.ts:3:5 › has title
Intercepted: http://localhost:3000/browser-sync/socket.io/?EIO=4&transport=polling&t=P6TgLGo&sid=pFuMyW7mZ9rfbhbRAAAE
Intercepted: http://localhost:3000/browser-sync/socket.io/?EIO=4&transport=polling&t=P6TgLGq&sid=pFuMyW7mZ9rfbhbRAAAE
Intercepted: https://jsonplaceholder.typicode.com/posts/1
Intercepted: https://jsonplaceholder.typicode.com/todos/1
Intercepted: https://jsonplaceholder.typicode.com/todos/1
[firefox] › example.spec.ts:3:5 › has title
Intercepted: http://localhost:3000/browser-sync/socket.io/?EIO=4&transport=polling&t=P6TgLhL&sid=AGDaVChmvMU86TeiAAAG
Intercepted: http://localhost:3000/browser-sync/socket.io/?EIO=4&transport=polling&t=P6TgLhL.0&sid=AGDaVChmvMU86TeiAAAG
Intercepted: https://jsonplaceholder.typicode.com/posts/1
Intercepted: https://jsonplaceholder.typicode.com/todos/1
Intercepted: https://jsonplaceholder.typicode.com/todos/1
  3 passed (4.0s)
```

This looks very similar to https://github.com/microsoft/playwright/issues/4487. @yury-s could you take a look?

**Comment by yury-s** [comment]
There is a bug in Chromium, when interception is enabled after the worker has been created, the worker requests are not properly intercepted. As a workaround you can call `page.route` earlier.

**Comment by yury-s** [comment]
Filed upstream issue https://issues.chromium.org/u/1/issues/364987731

**Comment by dgozman** [comment]
Upstream change proposed: https://chromium-review.googlesource.com/c/chromium/src/+/5873385

**Comment by dgozman** [comment]
Upstream fix landed, [merged to 130](https://chromium-review.googlesource.com/c/chromium/src/+/5892793), hopefully gets into the next Chromium roll.

**Comment by andermoranPro** [comment]
@dgozman is there a way for us to have a guess on the fix being available. Not looking for an exact date but a time frame hopefully
