### ISSUE TITLE
[Bug]: In Github actions tests are running with headed mode chrome and we have set config headless: true 

### ISSUE THREAD

**Issue by sakkukasetty** [microsoft/playwright#32361]
### Version

Version "@playwright/test": "^1.32.2", and 1.46

### Steps to reproduce

We are trying to run tests on Github CI/CD but we are facing this issue
previously on master in the playwright config headless was set to false but we modified to true now we are getting this issue, Any suggestion or fix will be very useful 
Please find the playwright config details 
![image](https://github.com/user-attachments/assets/6f4ab175-afb2-46d0-9769-125b5b390624)
Package json file 
![image](https://github.com/user-attachments/assets/aab62777-c077-4a15-8959-0b7512ce6c4c)

### Expected behavior

I expect tests run on Headless mode 

### Actual behavior

Tests are running on headed mode (chrome)

### Environment

```shell
Github actions 
Node: 18.8.2
```

**Comment by yury-s** [comment]
Make sure you don't pass '--headed' as a command line argument to `npx playwright test` and don't have something like `test.use({ headless: false })` in your tests. Please share full repro if it still doesn't work.

**Comment by sakkukasetty** [comment]
we use playwright config and healdless is always true and no tags in the command line we use npx playwright test

**Comment by yury-s** [comment]
Unfortunately, we cannot take any action on this without being able to reproduce the problem. So far it sounds like a problem with your configuration. Feel free to file a new bug once you can provide a reproduction which we could run locally.

**Comment by sakkukasetty** [comment]
when we generate reports there is browser type in the reports 
we do have Selenium java tests and Plywright tests in the same repo , not sure will that impact anything 
our directory structure is 
![image](https://github.com/user-attachments/assets/01460caf-4238-446f-aa28-13586379573d)

![image](https://github.com/user-attachments/assets/b54fc2c9-8c12-4186-b703-1af74cf99991)
