### ISSUE TITLE
[Bug]: NTLM Authentication Credentials ignored?

### ISSUE THREAD

**Issue by julewingchun** [microsoft/playwright#32360]
### Version

1.38.1

### Steps to reproduce

Our company is using NTLM as the way to go for login.
I am currently implementing some playwright tests and have a couple of test users that I would like to authenticate while running the tests.

Scenario:
Lets imagine i have a user with username: test and password: test.
When the application is opened in chrome (if there is no current Windows user), then the following browser Popup will come:
![image](https://github.com/user-attachments/assets/65961a21-d92a-42be-9135-43b548e1c99e)

The playwright.config.ts that i am using, looks like this (part of it):
`export default defineConfig({ .... use: { httpCredentials: {username: 'test', password: 'test'} }, projects: [ { name: 'chrome', use: { channel: 'chrome' launchOptions: { args: [ '--disable-web-security', '--auth-negotiate-delegate-whitelist=*.xxx.com', '--auth-server-whitelist=*.xxx.com', '--search-engine-choice-country', ], }, }, }, ] })`

### Expected behavior

The test user is logged in in the browser and executing the tests in that scop

### Actual behavior

My default Windows user is logged in in the browser and executing the tests in that scope

### Environment

```shell
System: Windows 10 Enterprise  x64-based processor
Version: "@playwright/test": "1.38.1",
Angular: 15
```

**Comment by yury-s** [comment]
HttpCredentials are only used for [Basic](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#basic) authentication scheme. NTLM authentication is not supported at the moment. Folding this request into https://github.com/microsoft/playwright/issues/17881
