### ISSUE TITLE
[Bug]: Low discoverability of `webServer` errors in UI Mode Output

### ISSUE THREAD

**Issue by karlhorky** [microsoft/playwright#32368]
### Version

1.46.1

### Steps to reproduce

1. Configure `webServer[0].command` to something that will throw an error (eg. `exit 1` or something more realistic like the reproduction link below)
2. Observe that there is no feedback in either the UI or in the terminal that anything has gone wrong, but all tests are missing ("No tests" message) and "No errors" in the Errors tab, see screenshot below

![356570173-3079baa1-db06-4e2c-934d-aafaa6503676](https://github.com/user-attachments/assets/46532860-599b-4765-b315-545a77237104)

Since @pavelfeldman's PR https://github.com/microsoft/playwright/pull/31824, there is a separate tab which shows the `stdout` and `stderr`, but [this is pretty hidden](https://github.com/microsoft/playwright/issues/31300#issuecomment-2277726618) - multiple users reported that it's hard to find, in that issue and offline

### Reproduction Repo

Reproduction: https://github.com/karlhorky/repro-playwright-ui-mode-missing-stderr-stdout

### Expected behavior

When a `webServer` process exits with a non-zero exit code, Playwright UI Mode switches automatically to the "Output" tab to show the error

### Actual behavior

When a `webServer` process exits with a non-zero exit code, no feedback is shown to the user, and "No tests" appears

It's up to the user to find out that there is [a hidden "Output" tab](https://github.com/microsoft/playwright/issues/31300#issuecomment-2277726618) which shows the errors

### Additional context

Originally, there was no way to see the `stdout` and `stderr` of the web servers:

- https://github.com/microsoft/playwright/issues/31300

But `stdout` and `stderr` are shown in the output panel in `1.46.0` after this PR:

- https://github.com/microsoft/playwright/pull/31824

### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M1
    Memory: 38.27 MB / 16.00 GB
  Binaries:
    Node: 20.15.0 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - /opt/homebrew/bin/npm
    bun: 1.1.25 - /opt/homebrew/bin/bun
  IDEs:
    VSCode: 1.92.2 - /opt/homebrew/bin/code
  Languages:
    Bash: 5.2.0 - /opt/homebrew/bin/bash
```

**Comment by Skn0tt** [comment]
One thing we could do here is to show a little warning dot on the output toggle button if there's errors in the output. That'd bring attention to the output button, not just for `webServer` errors but for any errors in the UI mode output.

**Comment by dlmr** [comment]
@Skn0tt Is it not possible to also output to the terminal? Saying this as I don't see that #32392 closes this issue. The dessired solution for my use case would make it work like it does in non UI mode as exemplified in this comment: https://github.com/microsoft/playwright/issues/31300#issuecomment-2277774311

**Comment by Skn0tt** [comment]
UI mode outputs the web server output just like the CLI, but it outputs it to the output tab in the UI. That tab is hard to discover though, and we'd like to fix that.

https://github.com/microsoft/playwright/pull/32392 is a subtle change, but it's hopefully enough to guide the users attention towards the output tab if it contains errors. This also applies to webserver errors.

**Comment by karlhorky** [comment]
@Skn0tt thanks for PR #32392! Looking forward to trying this out in the next Playwright release, assuming that it will be the next minor:

- [`@playwright/test@1.48.0`](https://github.com/microsoft/playwright/releases/tag/v1.48.0)

**Comment by Skn0tt** [comment]
Yes, it's gonna be in the next minor!

**Comment by karlhorky** [comment]
Finally found some time to circle back around to this, and I can confirm that [`@playwright/test@1.48.2`](https://github.com/microsoft/playwright/releases/tag/v1.48.2) is displaying the red dot 🎉

![Image](https://github.com/user-attachments/assets/c3c06832-ecea-4be4-954a-7dd9e0e07aab)
