### ISSUE TITLE
[Feature]: Allow TLS Client Certificates with proxy servers

### ISSUE THREAD

**Issue by kequach** [microsoft/playwright#32370]
### 🚀 Feature Request

In Playwright version 1.46, support for TLS Client Certificates was added. However, this feature does not work with Proxy Servers as per the documentation:

> Using Client Certificates in combination with Proxy Servers is not supported.
> [https://playwright.dev/java/docs/api/class-apirequest#api-request-new-context](url)

### Motivation

We are using Playwright in our company. Our laptops are within the company network, which requires the use of proxies. We can't use the TLS Client Certificates locally, making this feature unusable for us. Our current workaround is to use RestAssured, since proxy servers are supported there.

**Comment by ilorwork** [comment]
This is unfortunate, I was waiting for this feature to be created for a full year, and then it's not working for me because I'm using `proxy`

**Comment by mxschmitt** [comment]
> Is this even possible? I do not think there is a way to make a proxy use a client certificate.

I don't believe the feature is about that - I think its about making the actual client certificates connection through a proxy. In the case of a http proxy, there is only encrypted TLS getting shovelled through it and in case of socks, TCP. And these connections do the actual client certificates handshake.

cc @ilorwork is that how you imagine it?

**Comment by mxschmitt** [comment]
This should be fixed and be available in Canary tomorrow: https://playwright.dev/docs/canary-releases
