### ISSUE TITLE
[Feature]: Build command for `webServer` entries?

### ISSUE THREAD

**Issue by karlhorky** [microsoft/playwright#32371]
### 🚀 Feature Request

A new `webServer[number].buildCommand` config string (optional) which would be run before `webServer[number].command`

### Example

```ts
const config: PlaywrightTestConfig = {
  webServer: [ 
    {
      buildCommand: 'pnpm website build',
      command: 'pnpm website start',
      env: {
        PLAYWRIGHT: 'true',
      },
      port: 3000,
      stdout: 'pipe',
    },
    {
      buildCommand: 'pnpm api build',
      command: 'pnpm api start',
      env: {
        PLAYWRIGHT: 'true',
      },
      port: 3010,
      stdout: 'pipe',
    },
  ],
```

### Motivation

This would allow Playwright to manage more of the setup dependencies of apps to be tested, such as:

- Automatically setting environment variables for the build such as `PLAYWRIGHT='true'` https://github.com/microsoft/playwright/issues/32356

### Prior art

[`build` command option](https://github.com/cypress-io/github-action#build-app) for Cypress GitHub Action

### Alternatives Considered

Use [the boolean `AND` (`&&` operator) option](https://github.com/microsoft/playwright/issues/32356#issuecomment-2317032511) recommended by @Skn0tt 

```ts
const config: PlaywrightTestConfig = {
  webServer: [ 
    {
      command: 'pnpm website build && pnpm website start',
      env: {
        PLAYWRIGHT: 'true',
      },
      port: 3000,
      stdout: 'pipe',
    },
    {
      command: 'pnpm api build && pnpm api start',
      env: {
        PLAYWRIGHT: 'true',
      },
      port: 3010,
      stdout: 'pipe',
    },
  ],
```

**Comment by yury-s** [comment]
> ### Alternatives Considered

You can also add a custom command to `scripts` in package.json. There are enough solutions already to make the command do more work before actually starting the server. Closing the issue as we are not planning to implement this.

**Comment by karlhorky** [comment]
> Closing the issue as we are not planning to implement this.

Ok, thanks for the first consideration. As time goes on, maybe there becomes a stronger reason or additional reasons to implement a separate field.

> You can also add a custom command to `scripts` in package.json

This is not always a great option for duplication - eg. in the case that you want to be able to identify the Playwright environment to disable features such as reCAPTCHA Playwright doesn't support.

Eg this example here:

> `package.json`
> 
> ```json
> {
>   "scripts": {
>     "test": "PLAYWRIGHT=true pnpm build-1 && pnpm build-2 && yarn fusion playwright test --ui"
>   }
> }
> ```
> 
> However, `PLAYWRIGHT='true'` doesn't make its way to the `build-2` step

So if `package.json` scripts (npm scripts) are used, then the `PLAYWRIGHT=true` needs to be duplicated for every step, across every service which uses Playwright:

```json
{
  "scripts": {
    "test": "PLAYWRIGHT=true pnpm build-1 && PLAYWRIGHT=true pnpm build-2 && yarn fusion playwright test --ui"
  }
}
```

So moving the build scripts inside of the control of Playwright is desirable (probably should be the single recommended option, instead of using npm scripts).

Actually, if the Playwright team would publicly document a single recommendation for how to run Playwright-aware build scripts, that would go a long way to developing a battle-tested, robust solution.

Source: https://github.com/microsoft/playwright/issues/32356#issuecomment-2316901598
