### ISSUE TITLE
[Feature]: Switch automatically to UI Mode Output after 300ms delay of "Loading..."

### ISSUE THREAD

**Issue by karlhorky** [microsoft/playwright#32374]
### 🚀 Feature Request

If a server start command in `webServer[number].command` takes longer than 300ms to execute:

1. Switch to [the UI Mode "Output" tab](https://github.com/microsoft/playwright/issues/31300#issuecomment-2277726618) to show users what is happening.
2. After the server is available, switch back to the regular test runner view

Similar to:

- https://github.com/microsoft/playwright/issues/32368

### Example

If a `webServer[number].command` takes longer than 300ms to execute (eg. slow servers or [running a build command before a start command](https://github.com/microsoft/playwright/issues/32356#issuecomment-2317032511)), currently users will see this "Loading..." message without seeing context of what is going on:

![Screenshot 2024-08-29 at 12 34 42](https://github.com/user-attachments/assets/cf8878d4-c0c2-41c2-b064-afe87b52d568)

With this feature, any script that doesn't start immediately would show the webServer output (`stderr` shown by default, `stdout` shown when `stdout: 'pipe'` configured):

![Screenshot 2024-08-29 at 12 41 31](https://github.com/user-attachments/assets/568a11ef-f985-4e3b-9974-46a16d9e508d)

### Motivation

To reduce the low-information "Loading..." limbo state in the UI Mode, and attempt to improve users' perceptions of transparency and robustness of Playwright.

**Comment by pavelfeldman** [comment]
Switching panels under user's cursor would be a strong UX anti-pattern.

**Comment by karlhorky** [comment]
Hmm, agreed that there shouldn't be too much unexpected switching, but:

1. Within 300ms, I think existing UX research will say that users will perceive this as part of the loading sequence, especially if no other UI would appear during this time
2. An alternative is to instead switch immediately (start UI Mode in that tab) if there's a worry that users will notice this 300ms and react badly somehow
