### ISSUE TITLE
[Bug]: POST request executed as GET after redirect.

### ISSUE THREAD

**Issue by NikkTod** [microsoft/playwright#32380]
### Version

1.46.1

### Steps to reproduce

Unfortunatelly I dont have repo to share because of company policy, but hope screenshots and explanation will be helpful. 

Precondition:
I have a login test that stores the session, so that I can execute API requests with the stored cookie.
File with stored session is created -> login-session.json
I have a normal POST request that I want to execute. 

Steps: 
I start the test with the API POST request
Then it checks if user is authorised
Then we are redirected
Once it get that we are authorised and we have valid cookie
It execute again our request, but this time as GET request.

![image](https://github.com/user-attachments/assets/b5104e3e-0037-4c47-8fee-a039defe79a9)

### Expected behavior

Expected:
POST request to be executed as POST again after validation checks and redirects have happened.

### Actual behavior

POST request executed as GET without the request body, after redirection happens to validate authorisation.

Error 405 - Method Not Allowed

### Additional context

First try of the post request:
![image](https://github.com/user-attachments/assets/108d6ca1-a2d5-4b98-96dc-e22be7323adf)

Post request executed as GET after redirect

![image](https://github.com/user-attachments/assets/c42f8b8b-ca89-4b15-bdca-6aaeacebc94e)

### Environment

```shell
System:
  OS: Windows 10 10.0.19045
  CPU: (8) x64 Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
  Memory: 18.53 GB / 32.00 GB
Binaries:
  Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
  npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
IDEs:
  VSCode: 1.89.1 - C:\Program Files\Microsoft VS Code\bin\code.CMD
Languages:
  Bash: 4.4.23 - C:\Program Files\Git\usr\bin\bash.EXE
npmPackages:
  @playwright/test: ^1.46.1 => 1.46.1
  playwright-bdd: ^6.4.0 => 6.4.0
```

**Comment by yury-s** [comment]
This works by the spec, see step 12.1 in https://fetch.spec.whatwg.org/#http-redirect-fetch and is consistent with the browsers behavior. You can always set [`maxRedirects=0`](https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-fetch-option-max-redirects) to handle redirects manually and preserve the method if you need to.
