### ISSUE TITLE
[Bug]:  VSCode does not stop testing process while debugging playwright config

### ISSUE THREAD

**Issue by skamansam** [microsoft/playwright#32387]
### Version

1.46.1

### Steps to reproduce

1. create a new project: `npm init playwright@latest new-project`
  a. use typescript (not sure if that matters)
2. open project in vscode
3. install the playwright extension
4. add a debugger breakpoint in VSCode to the line in `playwright.config.ts` that is `export default defineConfig({`
5. run the tests in debug mode
6. stop the debug process by using the debug toolbar

### Expected behavior

the tests to stop so I can run the tests again

### Actual behavior

The test processes do not stop. The output os `ps` confirms it. After killing the processes, the test/debug panel in VSCode still soins as if the tests were still running.

### Additional context

I am using VSCode Insiders - 
```
Version: 1.93.0-insider
Commit: 36e4ddb4dbdf5d41bbeedfce2db4834085de2b87
Date: 2024-08-23T06:45:56.108Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Linux x64 6.10.6-200.fc40.x86_64
```

### Environment

```shell
System:
    OS: Linux 6.10 Fedora Linux 40 (Workstation Edition)
    CPU: (16) x64 AMD Ryzen 9 6900HX with Radeon Graphics
    Memory: 20.79 GB / 30.60 GB
    Container: Yes
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
    pnpm: 9.5.0 - ~/.nvm/versions/node/v20.15.1/bin/pnpm
  Languages:
    Bash: 5.2.26 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.46.1 => 1.46.1
```

**Comment by Skn0tt** [comment]
Thanks for the report! I'm able to reproduce. I believe what's happening is that the VS Code debugger detaches, but the debugged process continues to be halted on the breakpoint. I'll see what we can do to fix this.

**Comment by mxschmitt** [comment]
This got reverted since it caused https://github.com/microsoft/playwright/issues/32710
