### ISSUE TITLE
[Bug]: Wrong view port on mobile platform

### ISSUE THREAD

**Issue by justgh001** [microsoft/playwright#32406]
### Version

1.46.1

### Steps to reproduce

run the tests on mobile device, such as iPhone 14

### Expected behavior

desktop view port is loading on mobile emulator

### Actual behavior

mobile view port should load
![image](https://github.com/user-attachments/assets/2c42febe-fa2f-49e7-8938-eb42bcd72db3)

### Additional context

this issue is happening on Webkit (iOS devices) and when running on latest Playwright version

### Environment

```shell
Playwright/@test -> 1.46.1
```

**Comment by mkawumba** [comment]
I have the same on my machine - it's only in debug mode and makes it unusable. The UI mode looks good. The same repo run on Mac works fine.

**Comment by dgozman** [comment]
We need more information to act on this issue. Could you please provide a repro that we can run locally, including your test, config and any related files?

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.

**Comment by harryfinn101** [comment]
I have a similar issue to this

https://github.com/microsoft/playwright/issues/34188#issue-2765310660
