### ISSUE TITLE
File download Not working with Playwright on Selenium Grid

### ISSUE THREAD

**Issue by Rohittater255** [microsoft/playwright#32403]
### Please do not submit this issue.

- [X] I understand

**Comment by Rohittater255** [comment]
I have scenario where I want to perform Download file with Playwright on Selenium Grid.

I checked with Selenium Grid VNC, that I am getting --> 'Failed - Download Error' in Chrome Browser on clicking download

Refer Java Code and Docker-compose.yaml file at my github project: https://github.com/Rohittater255/PlaywrightDownloadIssue/tree/main

I tried same scenario with Selenium on Selenium Grid and it worked for me

**Comment by dgozman** [comment]
This issue tracker is reserved for bug reports and feature requests.

For anything else, such as questions or getting help, please see:
- [The Playwright documentation](https://playwright.dev/)
- [Our Discord server](https://aka.ms/playwright/discord)

**Comment by Rohittater255** [comment]
Hi @dgozman  
This is issue only. I would request your team to atleast check once
