### ISSUE TITLE
[Feature]: Playwright Test for VSCode need support other test files in addition to .spec.ts

### ISSUE THREAD

**Issue by RuslKoval** [microsoft/playwright#32410]
### 🚀 Feature Request

For now Playwright Test for VSCode supports only .spec.ts files
It would be good to have a possibility to add support for other test file extensions.
It could be a configurable option.

### Example

We have different types of tests in one project, like integration/system/e2e/etc. And we keep different types of tests in files with various extensions.

### Motivation

Now in test explorer we can only see tests from .spec.ts files.
We would like to have a possibility to see other tests in test explorer.

**Comment by dgozman** [comment]
Take a look at the [`testMatch` property](https://playwright.dev/docs/api/class-testconfig#test-config-test-match) in your configuration file. You can configure Playwright to recognize any files you'd like as tests. Let me know whether that helps.

**Comment by RuslKoval** [comment]
yes, it helps. Thanks!
