### ISSUE TITLE
[Bug]: Unable to get the page clicked from the history of chrome blank page

### ISSUE THREAD

**Issue by fanksy** [microsoft/playwright#32416]
### Version

1.45.2

### Steps to reproduce

Chrome Version 127.0.6533.100
Opening the chrome browser with --remote-debugging-port=9222, then calling the connectOverCDP to connect the browser.

Listening the event that open new pages, as shown below:
```
context.on("page", (page) => { console.log(page.url()) });
```

Last, clicking the links from the history of chrome blank page

### Expected behavior

I expect to see the url of the new page from the logs.

### Actual behavior

Nothing can be seen, no events are triggered.

Even by calling "context.pages()", I cannot get the newly opened page, but I can see through chrome://inspect/#devices

<img width="935" alt="Screenshot 2024-09-03 at 14 41 27" src="https://github.com/user-attachments/assets/c6cad5d1-ed0f-498c-b2eb-a45f240afb01">

### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M1
    Memory: 65.66 MB / 16.00 GB
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.14.0/bin/yarn
    npm: 10.8.1 - ~/.nvm/versions/node/v20.14.0/bin/npm
    pnpm: 9.6.0 - ~/.nvm/versions/node/v20.14.0/bin/pnpm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.45.2 => 1.45.2 
    playwright: 1.45.2 => 1.45.2
```

**Comment by mxschmitt** [comment]
This seems outside of the scope for Playwright. Testing `chrome://new-tab-page/` is not something we aim to automate.
