### ISSUE TITLE
[Feature]: video start/stop methods without closing page/context

### ISSUE THREAD

**Issue by xsoft7** [microsoft/playwright#32424]
### 🚀 Feature Request

would be nice to have the same api methods as do traces work :

### Example

traces.start
traces.stop

for videos:
video.start
video.stop

### Motivation

Our infra is based on Python + Pytest. 

I create global context (session scope) , which there I create new browser+page/context.

The tests themselves are ordered via classes (suite)-> methods (tests).

Ex:

class TestLogin:

   def test1_correct_login():
       do something -> should pass
       
    def test2_incorrect_login():
              do something -> should fail
              
    def test1_correct_login():
       do something -> should pass
       
       .
       .
       .
       
       
       
So in current scenario, I'm able **only to create traces per method** (test1,test2,test3) 

but the video will be 1 full video (test1+test2+test3..) , and then i need manually search within the video, (+AND this is huge file size of all the class!)

**Comment by dgozman** [comment]
Merging into #28183.
