### ISSUE TITLE
[Bug]: Download from azureedge incredibly slow

### ISSUE THREAD

**Issue by la-magra** [microsoft/playwright#32438]
### Version

1.46.1

### Steps to reproduce

```
$ yarn playwright install
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
Downloading Chromium 128.0.6613.18 (playwright build v1129) from https://playwright.azureedge.net/builds/chromium/1129/chromium-linux.zip
162.8 MiB [===                 ] 12% 5743.0s

# or

$ curl -O https://playwright.azureedge.net/builds/chromium/1129/chromium-linux.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  6  162M    6 9999k    0     0  27222      0  1:44:29  0:06:16  1:38:13 22534

```

### Expected behavior

A download that does not take two hours.

### Actual behavior

Wow, much speed, I guess I'll wait two hours for CI to complete.

### Additional context

Reproducible from multiple remote machines from Mexico and Colombia, at least one University impacted.

### Environment

```shell
System:
    OS: Linux 6.6 Arch Linux
    Memory: 5.29 GB / 15.55 GB
    Container: Yes
  Binaries:
    Node: 20.17.0 - ~/.node/bin/node
    Yarn: 4.4.1 - ~/.node/bin/yarn
    npm: 10.8.2 - ~/.node/bin/npm
  Languages:
    Bash: 5.2.32 - /usr/bin/bash
  npmPackages:
    playwright: 1.46.1 => 1.46.1
```

**Comment by pavelfeldman** [comment]
where are you located and how ling does it typically take you to download a regular browser?

**Comment by la-magra** [comment]
This is contract work.

`playwright install` is being run from a development machine VM I connect to remotely, that is located in some site of a Mexican university (never even seen it).

A normal download speed for a browser (63MB) in that machine is 13s :

```
$ curl -Ol 'https://download-installer.cdn.mozilla.net/pub/firefox/releases/130.0/win64/en-US/Firefox%20Setup%20130.0.exe'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 63.4M  100 63.4M    0     0  4972k      0  0:00:13  0:00:13 --:--:-- 12.4M
```

**Comment by pavelfeldman** [comment]
Sounds like they are deliberately throttling the Azure CDNs, not much we can do about it.

**Comment by la-magra** [comment]
I'll contact their network guys in once it's morning in that hemisphere.
But it's strange, I've already replicated the download throttling in 4 different networks, in two different countries.

Perhaps same firewall appliance or security lists?

**Comment by mxschmitt** [comment]
We are in the process of migrating to a different CDN infrastructure, could you try the following?

    PLAYWRIGHT_DOWNLOAD_HOST=https://playwright.azureedge.net/download/playwright npx playwright install

(even tho it still looks like azureedge, it redirects to something else)

**Comment by la-magra** [comment]
That seems to work.

**Comment by mxschmitt** [comment]
I'll consider this as done for now since we implemented it on our `main` branch. We target v1.50 with the global rollout for it.
