### ISSUE TITLE
headed mode

### ISSUE THREAD

**Issue by kapurrb11** [microsoft/playwright#32435]
### Version

playwright version v1.1.7

### Steps to reproduce

Steps working on Dynamics 365 company website, to automate a test.
Ran the codegen and it gave me this line.
//await page.frameLocator('iframe[title="Main Content"]').locator('#blree').first().click();
on running the debug 
i was able to see this work.

in headed mode however it threw an error.

So instead i replaced the code with the following block of code again it worked in the debug mode picked the right combo box , and although it passed in the headed mode it picked the datepicker instead of the combo box ?

Is there a

let workspace_dropdown = page.frameLocator('iframe[title="Main Content"]').locator('#blree');

  await workspace_dropdown.click();

  await page.waitForTimeout(10_000);

  page.keyboard.press('ArrowDown');

  await page.waitForTimeout(10_000);

  await workspace_dropdown.click();

  await page.waitForTimeout(10_000);

//await page.frameLocator('iframe[title="Main Content"]').locator('#blree').first().click();

### Expected behavior

I expected the same behaviour in headed as it exhibited in debug namely that it would select the combo box option 

### Actual behavior

Ran the codegen and it gave me this line. the locator of the code is in a frame
//await page.frameLocator('iframe[title="Main Content"]').locator('#blree').first().click();
on running the debug 
i was able to see this work.

in headed mode however it threw an error.

So instead i replaced the code with the following block of code again it worked in the debug mode picked the right combo box , and although it passed in the headed mode it picked the datepicker instead of the combo box ?

### Additional context

i am unsure of why it is exhibiting the strange behaviour i will need to finish filling in the page to see if it has selected the necessary when it saves the page in non headed and debug mode.

### Environment

```shell
System: windows 11

node version npm -v 
vscodeusersetup x64 -1.92.2
```

**Comment by pavelfeldman** [comment]
If you think this is a Playwright bug, please follow the BUG template to file something we can reproduce locally. If you need help with your test, try asking for help on Discord.

**Comment by kapurrb11** [comment]
Idid follow the bug template

**Comment by kapurrb11** [comment]
Hi Pavel,

Think it is something you could have replicated to be fair it is to do with
selectoption not working on a combobox  in headed mode yet it works in
debug mode ? try it on any combobox microsoft auther both dynamics 365 and
playwright.

i had thought you guys might be interested but clearly i wasted my time ...

its fine as filling that particular combo, is not critical to what i am
doing
Kindest Regards
Rajesh
