### ISSUE TITLE
[Feature]: CA validation

### ISSUE THREAD

**Issue by lubomsky** [microsoft/playwright#32444]
### 🚀 Feature Request

As a QA, I would like to reflect the real use of the application as best as possible, also validation of CA during `setClientCertificates` would be appreciated (with the full 'Certificate Hierarchy').

### Example

# ACTUAL:
![image](https://github.com/user-attachments/assets/742cf3cc-605f-4ea2-a3e5-b7e617837388)
---
![image](https://github.com/user-attachments/assets/86f5acb6-7110-4c8c-8778-563c0cdd8a38)
---
![image](https://github.com/user-attachments/assets/64cdd7f8-26e6-4715-8a39-71483943bce5)
---
![image](https://github.com/user-attachments/assets/3a4fb780-59ae-411c-9cf8-40b0cd113b83)
---
# EXPECTED:
![image](https://github.com/user-attachments/assets/25e0dddf-9b87-4add-925b-54ad92fa353f)
---
![Zrzut ekranu 2024-08-23 100202](https://github.com/user-attachments/assets/e77c06b7-5596-4c2d-8ab7-2ceebb8e4761)
---
![Zrzut ekranu 2024-08-23 100316](https://github.com/user-attachments/assets/80063c57-1332-4473-9707-516173bddea7)
---
![image](https://github.com/user-attachments/assets/01088054-08c6-4256-9356-6fef828c841d)
---
![Zrzut ekranu 2024-08-23 100702](https://github.com/user-attachments/assets/9eeaf288-4d28-40b6-b7de-4351b8470569)
---
![Zrzut ekranu 2024-08-23 095530](https://github.com/user-attachments/assets/f3329116-c477-44dc-ab3a-853442082c2e)

### Motivation

The application I am working on does not behave correctly when CA is not approved (This make me unable to use pw when the certificate is provided, and I really need to do that).
I think I am not the only one who has this problem, so the use of pw would increase after implementing this feature.
Ignoring https errors when supplying a client certificate does not sound very elegant.

**Comment by pavelfeldman** [comment]
> The application I am working on does not behave correctly when CA is not approved

Could you elaborate how it knows it is not approved? Should be approved!

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
