### ISSUE TITLE
[Docs]: please add dates on release notes

### ISSUE THREAD

**Issue by Huge** [microsoft/playwright#32446]
### Page(s)

https://playwright.dev/docs/release-notes

### Description

seeing some release date(time) on each individual release like https://playwright.dev/docs/release-notes#version-146 would definitely help.

**Comment by mxschmitt** [comment]
We have exact dates on [GitHub](https://github.com/microsoft/playwright/releases) - even better, on [NPM](https://www.npmjs.com/package/@playwright/test) - would that work for you?

**Comment by dgozman** [comment]
Closing as per above.
