### ISSUE TITLE
[Bug]: viewport from playwright.config.js is not honored.

### ISSUE THREAD

**Issue by sbulusu** [microsoft/playwright#32454]
### Version

1.41.1

### Steps to reproduce

1. npm init playwright@latest
Choose Javascipt and leave the rest of the values as default. You would see the following.

> `Initializing project in '.'

> √ Do you want to use TypeScript or JavaScript? · JavaScript
> √ Where to put your end-to-end tests? · tests
> √ Add a GitHub Actions workflow? (y/N) · false
> √ Install Playwright browsers (can be done manually via 'npx playwright install')? (Y/n) · true
> Initializing NPM project (npm init -y)…
> Wrote to ...`

2. Inside playwright.config.js, add viewport. 

> `  use: {
>     trace: 'on-first-retry',
>     viewport: {
>       width: 1281,
>       height: 720,
>     },
>   },`

3. Have this inside example.spec.js

> `// @ts-check
> const { test, expect } = require('@playwright/test');
> 
> test('has title', async ({ page }) => {
>   await page.goto('https://playwright.dev/');
> 
>   // Expect a title "to contain" a substring.
>   await expect(page).toHaveTitle(/Playwright/);
> 
>   const viewportSize = await page.evaluate(() => ({
>     width: window.innerWidth,
>     height: window.innerHeight
>   }))
>   console.log('Viewport Size:', viewportSize);
> });
> `

4. npx playwright test --project=chromium
It would print the following.

> `PS C:\repos\playwright2> npx playwright test --project=chromium                                                                               
> 
> Running 1 test using 1 worker
> [chromium] › example.spec.js:4:1 › has title
> Viewport Size: { width: 1280, height: 720 } 
>   1 passed (8.1s)
> 
> To open last HTML report run:
> 
>   npx playwright show-report `

### Expected behavior

Viewport Size: { width: 1281, height: 720 } 

### Actual behavior

Viewport Size: { width: 1280, height: 720 } 

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 14.70 GB / 31.69 GB
  Binaries:
    Node: 20.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.92.2 - C:\Users\sbulusu1\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.46.1 => 1.46.1
```

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/32413
