### ISSUE TITLE
[Bug]: VSCode extension Watch mode not working (MacOS)

### ISSUE THREAD

**Issue by TesterrA** [microsoft/playwright#32464]
### Version

1.46.1

### Steps to reproduce

I am encountering the same issue with the VSCode extension's Watch mode not working on my MacOS setup. Unfortunately, like the original author, it's quite challenging for me to share our repository due to its complexity and internal constraints. I see that this thread is currently closed, but I wanted to highlight that this problem still persists for others. If there’s any additional debug information or steps I can provide that might help without sharing the repo, please let me know. It would be great to have this functionality working, as it would be very valuable for our team.

### Expected behavior

When Watch mode is enabled for a test in the VSCode extension, any changes made to the test specification files should automatically trigger the tests to run again.

### Actual behavior

When Watch mode is enabled for a test in the VSCode extension, making changes to a test specification file does not trigger the tests to run automatically

### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 70.52 MB / 16.00 GB
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.46.1 => 1.46.1 
    playwright-lighthouse: ^4.0.0 => 4.0.0
```

**Comment by TesterrA** [comment]
##[[[Bug]: VSCode extension Watch mode not working (MacOS)](https://github.com/microsoft/playwright/issues/30951#top)
#30951 ](url)

**Comment by pavelfeldman** [comment]
This work for us and in the tests, so in order to act on the issue we need exact steps to follow.

**Comment by TesterrA** [comment]
I discovered that the problem seems to be related to the package-lock.json file. When the package-lock.json is already present in the repository and I run npm install, the playwright extension's Watch mode does not work as expected and doesn't trigger tests on file changes.

However, if I clone the project without the package-lock.json file and then run npm install to generate a fresh package-lock.json, the Watch mode works correctly and automatically triggers tests upon changes.

If you have any thoughts on why this might be happening or any advice on how to resolve it more cleanly, I'd appreciate it!
