### ISSUE TITLE
[Bug]: logPolitely logs on stdout

### ISSUE THREAD

**Issue by achingbrain** [microsoft/playwright#32487]
### Version

1.47.0

### Steps to reproduce

Run playwright on a platform without browsers installed.

The [logPolitely function in browserFetch.ts](https://github.com/microsoft/playwright/blob/ed303208b3750ac9662894fbeb5d655ae21b3f9c/packages/playwright-core/src/server/registry/browserFetcher.ts#L120) logs using `console.log` which causes output on stdout.

It should use `console.warn` or `console.error` to log to stderr instead as it can interfere with the output of the script being run.

### Expected behavior

Playwright informational logging on stderr

### Actual behavior

Playwright informational logging on stdout

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 133.58 MB / 64.00 GB
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.12.2/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.6.0 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
  IDEs:
    VSCode: 1.92.0 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by pavelfeldman** [comment]
> It should use console.warn or console.error to log to stderr instead as it can interfere with the output of the script being run.

The script being run here can only be `npx playwright install`, could you share more about your use case? What is the other output?

**Comment by achingbrain** [comment]
> The script being run here can only be npx playwright install

That's correct.

> could you share more about your use case? What is the other output?

I'm using `playwright` to run some code in a headless browser which logs results to stdout.  The output from the browser is then parsed and acted upon.

Because `playwright` logs to stdout instead of stderr I have to handle the playwright output separately.  An upgrade to playwright could also cause new logging which might break my program if it arrives formatted differently, or if it's different in some other way that I cannot predict.

In general* `stdout` should be used for program output, `stderr` should be used for everything else - informational logging, diagnostics, debug output, etc.

I think messages like "I'm going to install a browser", "I'm downloading it now", etc, fall under the latter category so belong on stderr and not stdout.

----

\* = "In general" is quite subjective, here are some references that discuss when to use stdout vs stderr:

 - https://www.mehulkar.com/blog/2017/11/stdout-vs-stderr/
 - https://retrocomputing.stackexchange.com/questions/11499/what-was-the-point-of-separating-stdout-and-stderr
 - https://www.ibm.com/docs/en/aix/7.1?topic=redirection-standard-input-standard-output-standard-error-files
 - https://en.wikipedia.org/wiki/Standard_streams#Standard_error_(stderr)
 - https://www2.dmst.aueb.gr/dds/blog/20131211/index.html

**Comment by achingbrain** [comment]
> npx playwright install is a cli tool... so it outputs to the stdout as a user would expect

That's true, unfortunately logPolitely is used during regular execution too, not just during `npx playwright install`.

I just saw this during a test run:

```
Removing unused browser at /Users/alex/Library/Caches/ms-playwright/chromium-1133
Downloading Chromium 129.0.6668.29 (playwright build v1134) from https://playwright.azureedge.net/builds/chromium/1134/chromium-mac-arm64.zip
139 MiB [====================] 100% 0.0s
Chromium 129.0.6668.29 (playwright build v1134) downloaded to /Users/alex/Library/Caches/ms-playwright/chromium-1134
```

This uses `logPolitely`:

**Comment by dgozman** [comment]
> I just saw this during a test run:

Could you please share a repro for this? I don't think playwright should download browsers during test execution.

**Comment by achingbrain** [comment]
I think I've got to the bottom of this.  We're using [playwright-test](https://www.npmjs.com/package/playwright-test) as it's a really simple way to just run a script in many different browsers headlessly and does nice things like installing missing browsers if required.

It uses the `Registry` from `playwright-core` to install browsers so that's why it appears during a test run.

> I don't think playwright should download browsers during test execution.

That's a shame, it's really useful to not have to worry about this stuff.

I'm going to close this since it's not using the tool in the way the authors intend it to be used, though it'd still be nice to have an option on the API to control the logging output.
