### ISSUE TITLE
[Bug]: @playwright/test 1.47.0 broken for tsconfig alias imports

### ISSUE THREAD

**Issue by stevensacks** [microsoft/playwright#32485]
### Version

1.47.0

### Steps to reproduce

I updated to 1.47.0 and now my playwright tests are complaining:

```
Error: Cannot find package '~' imported from /Users/me/project/.playwright/e2e/things.spec.ts
```

It's a remix project and remix uses `~` as the prefix, which is set in the tsconfig.

This was working just fine in the previous version. Something is broken now.
```ts
import {expect, test} from '@playwright/test';
import languages from '~/languages';

test('things can be created, updated, and deleted', async ({browser}) => {
  const context = await browser.newContext({
    extraHTTPHeaders: {
      'Accept-Language': 'en',
    },
  });
  await context.clearCookies();
  const page = await context.newPage();
  await page.goto('/things');
  await expect(page).toHaveURL('/things');
  await expect(page).toHaveTitle(languages.en.pages.things.meta.title);
  await expect(page.getByTitle(/Thing/)).toHaveCount(2);

  await context.close();
});
```

### Expected behavior

Expect playwright to honor the tsconfig alias.

### Actual behavior

Complains that it can't find a package.

Rolling back to `1.46.1` fixes the issue.

### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 86.02 MB / 16.00 GB
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    npm: 10.8.3 - ~/.nvm/versions/node/v20.17.0/bin/npm
    bun: 1.0.18 - ~/.bun/bin/bun
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.47.0 => 1.47.0
```

**Comment by dgozman** [comment]
@stevensacks Could you please share a full repro? We need the project structure and tsconfig.json to make sure we understand your setup.

**Comment by nickdbush** [comment]
This looks like a duplicate of #32480, which has a reproduction

**Comment by stevensacks** [comment]
Since it’s a duplicate, I’ll close this one.
