### ISSUE TITLE
[Regression]: `tsconfig.json`'s `compilerOptions.paths` no longer working in 1.47

### ISSUE THREAD

**Issue by mrmckeb** [microsoft/playwright#32480]
### Version

1.47.0

### Steps to reproduce

1. Add paths to `tsconfig.json`
    ```
    {
      "compilerOptions": {
        "paths": {
          "#/*": ["./src/*"]
        }
      }
    }
    ```
2. Import something using that path, i.e. `#/utils/my-util`.

### Expected behavior

This worked as expected in 1.46.

### Actual behavior

Error:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '#/utils/my-util' imported from <path>/tests/my-test.ts
```

### Additional context

I assume this is related to the `tsconfig` option in 1.47, but didn't dig into the issue yet sorry.

### Environment

```shell
System:
  OS: macOS 14.6.1
  CPU: (8) arm64 Apple M3
  Memory: 256.58 MB / 24.00 GB
Binaries:
  Node: 20.14.0 - ~/.local/state/fnm_multishells/35649_1725599073952/bin/node
  npm: 10.7.0 - ~/.local/state/fnm_multishells/35649_1725599073952/bin/npm
  pnpm: 9.9.0 - ~/.local/state/fnm_multishells/35649_1725599073952/bin/pnpm
IDEs:
  VSCode: 1.93.0 - /usr/local/bin/code
Languages:
  Bash: 3.2.57 - /bin/bash
```

**Comment by dgozman** [comment]
@mrmckeb Could you please share a full repro? We need the project structure, package.json and tsconfig.json at least to make sure we understand your setup.

**Comment by nickdbush** [comment]
It looks like importing `/package/index` as `/package` is causing the problem. Cutting down my repro, will be with you in a few moments!

**Comment by rkhomi** [comment]
![Screenshot 2024-09-06 at 17 20 07](https://github.com/user-attachments/assets/8508c197-8551-40bb-b2f7-3f692e5a6c8c)
same here

**Comment by mrmckeb** [comment]
Sorry I didn't supply a repro @dgozman - thanks @nickdbush for beating me to it!
