### ISSUE TITLE
[Bug]: Default GitHub Action says ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "playwright" not found

### ISSUE THREAD

**Issue by zeekrey** [microsoft/playwright#32503]
### Version

1.47.0

### Steps to reproduce

1. Call `pnpm create playwright` and choose to add a GitHub Action.
2. Push the repo to GitHub.

### Expected behavior

The tests at least run.

### Actual behavior

The tests aren't even started, since the following error occurs during dependency installation:

```
Run pnpm exec playwright install --with-deps
ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "playwright" not found
```

### Additional context

After the first fail I switched to the official pnpm docs and used the following step to install pnpm:

```
- name: Install pnpm
  uses: pnpm/action-setup@v4
  with:
    version: 9
```

Doesn't work either.

### Environment

```shell
playwright.yml:


name: Playwright Tests
on:
  pull_request:
    branches: [main, dev]
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm exec playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
```
```

**Comment by pavelfeldman** [comment]
Sounds like pnpm issue https://github.com/pnpm/pnpm/issues/4146. Use npx?

**Comment by zeekrey** [comment]
Yeah, it seems like there are some weird things happening with the pnpm exec command especially in a workspace environment. `npx` is doing fine, but I also managed to fix it with `pnpm` by running everything from the workspace root and adding a filter to the playwright install and test command.

```
pnpm --filter <package> exec playwright install --with-deps
pnpm --filter <package> exec playwright test
```
