### ISSUE TITLE
[Feature]: Request to Enhance Request Fixture with route Functionality

### ISSUE THREAD

**Issue by hardeep-qa** [microsoft/playwright#32528]
### 🚀 Feature Request

Hi team, As playwright is getting popular in API testing, Could we please consider adding the route function to the request fixture? This enhancement would streamline our ability to mock API responses during API testing. By incorporating this feature, we can develop and test our API endpoints even if the server is not yet available.

### Example

import { test, expect } from '@playwright/test';

test('mock GraphQL response using request fixture', async ({ request }) => {
  // Intercept the GraphQL request and provide a mock response
  await request.route('**/graphql', route => {
    const response = {
      data: {
        person: {
          name: 'John Doe',
          age: 30
        }
      }
    };
    route.fulfill({
      contentType: 'application/json',
      body: JSON.stringify(response)
    });
  });

  const response = await request.post('/graphql', {
    data: {
      query: '{ person { name age } }'
    }
  });

  const responseBody = await response.json();
  expect(responseBody.data.person.name).toBe('John Doe');
  expect(responseBody.data.person.age).toBe(30);
});

### Motivation

By incorporating the route function, we can easily mock API responses. This allows us to develop and test our API endpoints even if the server is not yet available, ensuring continuous progress without dependency on server readiness.

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
