### ISSUE TITLE
[Bug]: chromium.launch() implicitly invoke '--no-startup-window' to browser

### ISSUE THREAD

**Issue by Fredida** [microsoft/playwright#32539]
### Version

playwright-core 1.46.1 in node.js

### Steps to reproduce

Launch external chromium browser with gui via following:

```typescript
const browser = await chromium.launch(
        {
            channel: 'chrome',
            chromiumSandbox: true,
            executablePath: 'C:\\xxx\\chrome.exe',
            headless: false,
            args: [
                '--no-default-browser-check',
                '--disable-infobars',
                '--incognito',
            ]
        }
);
```

### Expected behavior

Launch browser with gui(window) as headless has already been set `false`.

### Actual behavior

The chromium browser was launched (process found, user data directory created) but no gui.

### Additional context

If launch same chromium executeable with same options but using .launchPersistentContext():

```typescript
const browser = await chromium.launchPersistentContext(
        'C:\\xxx\\userdata',
        {
            channel: 'chrome',
            chromiumSandbox: true,
            executablePath: 'C:\\xxx\\chrome.exe',
            headless: false,
            args: [
                '--no-default-browser-check',
                '--disable-infobars',
                '--incognito',
            ],
)
```
Browser window appears properly.

By adding `DEBUG=pw:*` as verbose:

Using .launch():
```
 pw:browser <launching> C:\xxx\chrome.exe --disable-field-trial-config --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding,PlzDedicatedWorker --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --unsafely-disable-devtools-self-xss-warnings --no-default-browser-check --disable-infobars --incognito --user-data-dir=C:\yyy\playwright_chromiumdev_profile-XXXXXX --remote-debugging-pipe --no-startup-window +0ms
```

Using .launchPersistentContext():
```
  pw:browser <launching> C:\xxx\chrome.exe --disable-field-trial-config --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding,PlzDedicatedWorker --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --unsafely-disable-devtools-self-xss-warnings --no-default-browser-check --disable-infobars --incognito --user-data-dir=C:\yyy\userdata --remote-debugging-pipe about:blank +0ms
```

The differene seems to be ` --no-startup-window`  in .launch().

BTW: May I suggest to add a feature that sets chromium user data directory in .lauch()? Althrough .launchPersistentContext() did this the .newContext() not existed in the launch browser. If we head to .launch(), the user data directory is always C:\AppData\Local\Temp\playwright-xxx , which is not easy to cleanup.

### Environment

```shell
System: Windows 10 19044
Node: v20.12.2
```

**Comment by dgozman** [comment]
@Fredida This is by design. Launching a browser does not mean automatically opening a page. That's unless you launch a persistent context, where browsers mandate a default page being opened. If don't want a persistent context, you can use a combination of `launch()` + `newPage()`. Let me know whether that helps.

**Comment by Fredida** [comment]
@dgozman, thanks for the explanation—it makes sense. However, it seems that there's no way to manually set the user data directory with `.launch()`. While Playwright usually cleans up temporary data, there are instances where it might persist. Could you please consider adding the ability to specify the user data directory in `.launch()`? Thank you in advance!

**Comment by dgozman** [comment]
@Fredida When you `launch()`, the browser does not actually persist any data in the `userDataDir`. Some of the browsers create default files there because that's how they operate. I don't think we'll add the `userDataDir` to `launch()` because it contradicts the purpose of the method.

If you have a repro case where the temporary directory persists, please file a separate bug and we'll happily look into it.

**Comment by mxschmitt** [comment]
Closing as per above.
