### ISSUE TITLE
Is there any support for opening traces in trace.playwright.dev with postMessage API ?

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#32538]
### Please do not submit this issue.

- [X] I understand

**Comment by dgozman** [comment]
This issue tracker is reserved for bug reports and feature requests.

For anything else, such as questions or getting help, please see:
- [The Playwright documentation](https://playwright.dev/)
- [Our Discord server](https://aka.ms/playwright/discord)
