### ISSUE TITLE
[Feature]: Add ability to mask sensitive data by regex in page.goto() method

### ISSUE THREAD

**Issue by KaterynaBuhaichuk** [microsoft/playwright#32545]
### 🚀 Feature Request

Add ability to mask sensitive data by regex in [page.goto() method ](https://playwright.dev/docs/api/class-frame#frame-goto)

### Example

page.goto('https://example.somedomain.com/?jwt=********') 

### Motivation

Increase security, decrease the probability of data leakage

**Comment by Kranael** [comment]
Just use env data here? So process.env.jwt for example. Not possible?

**Comment by VolodymyrTysovskyi13** [comment]
> Just use env data here? So process.env.jwt for example. Not possible?

would this prevent the JWT to be logged in a unmasked type?

**Comment by dgozman** [comment]
Duplicate of #31728.
