### ISSUE TITLE
[Feature]: allow disabling colors in debug reporter

### ISSUE THREAD

**Issue by rmuir** [microsoft/playwright#32543]
### 🚀 Feature Request

I use jenkins CI with built in `list` and `junit` reporters.
To improve debugging test flakes, i set `DEBUG=pw:api,pw:browser`

It would be wonderful to have an explicit way to disable colors for the debug output.
I tried various hacks around this, even setting variables such as `DEBUG_FILE=/dev/stderr`, but this fails with ENXIO due to the way that node opens the file. I was hoping this would engage the color-filtering here: https://github.com/microsoft/playwright/blob/b5d968fa0e3acb052de4eab5952f6efb668d9111/packages/playwright-core/src/utils/debugLogger.ts#L40-L44

### Motivation

CI logs are filled with ansi colors with no way to disable them.
I don't give playwright process a TTY (runs via docker) but the debugging logs are still colored.
Unfortunately, NO_COLOR environment variable is not respected: https://no-color.org/

It makes it extremely difficult to debug tests from:
* jenkins "Test Report" (/testReport). This displays the output from the `junit` reporter for a particular test (e.g. the one that failed) and is the most intuitive and fast way to triage a failing test. Unfortunately all the debug output shows as ansi escapes.
* full jenkins logfiles. We have a lot of tests and scrolling with the built-in console can be frustrating.

**Comment by dgozman** [comment]
@rmuir We are using the [debug package](https://www.npmjs.com/package/debug) that suggests `DEBUG_COLORS=false` environment variable. Let me know whether that helps.

**Comment by rmuir** [comment]
@dgozman thank you for responding. I set `DEBUG_COLORS`, and it seems not to respect it: e.g. `pw:api` log messages are some still in cyan color and `pw:browser` is very dark.

```
 # enable playwright debugging logs
 ENV DEBUG=pw:api,pw:browser
+# disable debugger colors
+ENV DEBUG_COLORS=false
```

I did find a partial workaround looking more into the sources: for the `junit` reporter if I set `stripANSIControlSequences: true` then it strips all ansi including debug output, which solves my problem for one of the reporters.

unfortunately the `line` reporter doesn't seem to have such an option: any ideas on other things I could try?

I don't know typescript at all really, I'm just a CI/CD guy who deals with testing stuff across many programming languages. Would there be any appetite for respecting `NO_COLOR` environment variable as described in https://no-color.org/ ? It works with popular packages such as `npm` and `python` and really helps save time in these situations: I have looked thru plenty of typescript sources today and searched for things like `process.env` across whole codebase trying to figure out how to solve this.

**Comment by rmuir** [comment]
Just as a guess, i think high-level the issue making it impossible to disable colors with these env vars, might be that they seem to get overridden by some sources to "force color":
https://github.com/microsoft/playwright/blob/356517cddbd8f71946065da19b3f7a64b5d0c4df/packages/playwright/src/plugins/webServerPlugin.ts#L42-L43

(maybe this code is not relevant, I'm not sure what I'm looking at)

npm `debug` package docs lead me to https://www.npmjs.com/package/supports-color which says:
> The use of FORCE_COLOR overrides all other color support checks.

**Comment by mxschmitt** [comment]
Unrelated to this behaviour around colours. You are using this environment variable to debug test flakes. The environment variable is not intended to be used for that / doesn't give you the best user experience. Have you considered [Trace Viewer](https://playwright.dev/docs/trace-viewer-intro) in order to debug your failing tests?

**Comment by rmuir** [comment]
In case anyone else struggles with disabling color like this, I did figure out a very-ugly workaround for the line reporter using `sed` to scrub out the colors:
```
set -exo pipefail; ...
docker-compose exec browser-tests xvfb-run -s '-screen 0 1920x1080x24' npx playwright test | sed 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g'
```

combined with the `stripANSIControlSequences: true` in the junit reporter, both reporters now work in jenkins without having to 'decrypt' the ANSI escapes.

**Comment by rmuir** [comment]
Thank you @dgozman ! With playwright 1.48, I just set `DEBUG_COLORS=false` in environment and removed all hacks and it works.
