### ISSUE TITLE
Test info attached in html report in wrong format

### ISSUE THREAD

**Issue by priyanka-vuddemari** [microsoft/playwright#32555]
### Version

1.43.1

### Steps to reproduce

This issue is similar to [Issue 30831](https://github.com/microsoft/playwright/issues/30831) . 
1)Clone repo https://github.com/priyanka-vuddemari/playwright-api-demo
2) test case  present in this path `playwright-api-demo/blob/main/tests/api.spec.ts`
3) Run test case `test info demo`

### Expected behavior

Status code and response body from test.info should be attached properly to html report

### Actual behavior

![IMG_20240911_142931433~2](https://github.com/user-attachments/assets/21472b51-5f6b-4eee-b6d6-74591397adb9)

Response Body
���rӛ��-

### Additional context

Used below code to attach  json to report
`testInfo.attach('Response Body', {body : responseBody, contentType : 'application/json'})`

### Environment

```shell
System:
    OS: Linux 6.5 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (2) x64 AMD EPYC 7763 64-Core Processor
    Memory: 5.11 GB / 7.74 GB
    Container: Yes
  Binaries:
    Node: 20.16.0 - ~/nvm/current/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.8.1 - ~/nvm/current/bin/npm
    pnpm: 9.7.1 - ~/nvm/current/bin/pnpm
  IDEs:
    VSCode: 1.93.0 - /vscode/bin/linux-x64/4849ca9bdf9666755eb463db297b69e5385090e3/bin/remote-cli/code
  Languages:
    Bash: 5.0.17 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.43.1 => 1.43.1 
    playwright: ^1.43.1 => 1.43.1
```

**Comment by dgozman** [comment]
@priyanka-vuddemari Attachment `body` must be a string or a Buffer, as [stated in the docs](https://playwright.dev/docs/api/class-testinfo#test-info-attach-option-body). You are attaching a json object instead. I'd recommend attaching the original json string. Let me know whether that helps.

**Comment by priyanka-vuddemari** [comment]
Hi @dgozman 
I tried with {body : await response.body() , content type: 'application/json'}
Below is the way it attaches . Any way we can format it to print it like a proper json 
![Uploading IMG_20240911_200835078~3.jpg…]()

Not sure if u are able to see the image .. but it doesn't format the  response.body()  while attaching

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
