### ISSUE TITLE
[Bug]: symbolic link issues

### ISSUE THREAD

**Issue by sdeshpande** [microsoft/playwright#32559]
### Version

Latest 

### Steps to reproduce

We are running into an issue because of how python is installed in our shared environment .
We have symbolic link for the disk drive located inside another shared drive. 
When we install Playwright, it somehow maintains the actual path / drive letter of the symbolic link and playwright fails to launch. 
Is there any way to avoid it?

### Expected behavior

Playwright doesn’t even show help menu 

### Actual behavior

node:fs:2771
      const out = binding.lstat(pathModule.toNamespacedPath(base), false, undefined, true /* throwIfNoEntry */);
                          ^

Error: ENOENT: no such file or directory, lstat 'K:\'
    at Object.realpathSync (node:fs:2771:27)
    at toRealPath (node:internal/modules/helpers:58:13)
    at Module._findPath (node:internal/modules/cjs/loader:698:22)
    at resolveMainPath (node:internal/modules/run_main:35:23)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:160:24)
    at node:internal/main/run_main_module:28:49 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'K:\\'
}

Node.js v20.16.0

### Environment

```Text
- Operating System: [Windows Server 2019, Windows 10, Windows 11]
- CPU: [x86-64]
- Python Version: [3.12]
```

**Comment by dgozman** [comment]
@sdeshpande Could you please be more detailed in your explanation? Please tell us exactly what do you symlink, in which location you install playwright and how do you run it.

**Comment by sdeshpande** [comment]
Hi @dgozman .. please see below for additional details.
We have a need to have a shared python environment. This is stored on our File Server and served to users via "Windows DFS"
On the actual file server, we have multiple drives. 
The python environment is installed using miniconda installer on Drive K in folder "pyprod" and a symbolic link is created for this folder in another directory stored on drive F.
This is how we activate the environment when we want to use it. 
```
F:\shares\miniconda\condabin\activate pyprod
Once activated we can run all binaries installed in this environment
```

We install various packages to this python environment such as Pandas, numpy, selenium, etc. and haven't really experienced any issues. 
Happy to provide additional details if needed.

**Comment by dgozman** [comment]
@sdeshpande I am not really sure how to help you. I doubt we'll be able to recreate the kind of setup you've got to reproduce the issue and work on a fix. I'd encourage you to dig deeper, see where playwright unpacked the underlying `node.exe` and its internal javascript source, and experiment with running things. I can keep this issue open so that we can communicate, but it's unlikely we can figure out the problem ourselves.

**Comment by sdeshpande** [comment]
Thank you @dgozman 
I will try to dig deeper to find out what might be causing it.
