### ISSUE TITLE
[Bug]: exposeFunction() is not exposing function as expected

### ISSUE THREAD

**Issue by marcosvfranco** [microsoft/playwright#32564]
### Version

1.45.1

### Steps to reproduce

Here is my code, just copy, paste, execute

```
import { expect, test } from '@playwright/test';

function disp(text: string) {
    console.log(text);
}
test.describe('Exposing', () => {
    test('Testing', async ({ page }) => {
        await page.goto('https://playwright.dev');
        await page.waitForLoadState('networkidle');

        await page.exposeFunction('dispatchConsoleLog', disp);
        await page.evaluate(async () => {
            dispatchConsoleLog('teste');
        });
    });
});
```

### Expected behavior

I expect to have the function called or listed when trying to do this through the Browser Console, I'm in a specific test here that I need to access the exposed function and it does not works, like in the example I'm giving

### Actual behavior

When accessing the browser and going to the console, trying to access the function expose, here is what we have:

```
window.dispatchConsoleLog('test')
Promise {<pending>}
window.dispatchConsoleLog()
Promise {<pending>}
window.dispatchConsoleLog()
Promise {<pending>}
dispatchConsoleLog
(...args) => {
    const me = globalThis[bindingName];
    if (needsHandle && args.slice(1).some(arg => arg !== undefined)) throw new Error(`exposeBindingHandle supports a single argument, ${args.len…
dispatchConsoleLog()
Promise {<pending>}
```

![Screenshot 2024-09-11 at 17 44 36](https://github.com/user-attachments/assets/274e2aff-c3fa-48d1-a14c-cc490a08a232)

### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 62.38 MB / 16.00 GB
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    npm: 10.8.1 - /usr/local/bin/npm
  IDEs:
    VSCode: 1.92.2 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.47.0 => 1.47.0 
    playwright: ^1.47.0 => 1.47.0
```

**Comment by dgozman** [comment]
@marcosvfranco `exposeFunction()` exposes a function that runs in Node.js environment whenever you call the exposed name in the page. So in this case, when calling `window.dispatchConsoleLog('test')`, you should see the log in your terminal, or wherever you run the test from.

If you'd like to inject a function into the page, that runs in the page itself, you can just use `evaluate`. Then, calling it from the DevTools console will log inside the page, visible in DevTools.
```ts
await page.evaluate(() => {
  window.dispatchConsoleLog = function disp(text) {
    console.log(text);
  };
});
```

Let me know whether that helps.

**Comment by marcosvfranco** [comment]
> @marcosvfranco `exposeFunction()` exposes a function that runs in Node.js environment whenever you call the exposed name in the page. So in this case, when calling `window.dispatchConsoleLog('test')`, you should see the log in your terminal, or wherever you run the test from.
> 
> If you'd like to inject a function into the page, that runs in the page itself, you can just use `evaluate`. Then, calling it from the DevTools console will log inside the page, visible in DevTools.
> 
> ```ts
> await page.evaluate(() => {
>   window.dispatchConsoleLog = function disp(text) {
>     console.log(text);
>   };
> });
> ```
> 
> Let me know whether that helps.

Thanks for the reply @dgozman , however as I showed you, when I run `window.dispatchConsoleLog('test')`, the response is Promise {<pending>}. Why this is happening?

I know that the `evaluate()` example you gave works, but I want to use the exposeFunction + evaluate in my code to encapsulate my functions and parametrize them later

**Comment by dgozman** [comment]
> when I run window.dispatchConsoleLog('test'), the response is Promise {<pending>}. Why this is happening?

Because any exposed function returns a promise. You can `await` that promise to receive the result of the `disp` function that you've exposed, which would be `undefined` in your case.

> I know that the evaluate() example you gave works, but I want to use the exposeFunction + evaluate in my code to encapsulate my functions and parametrize them later

I'm not sure I understand this. I think there is no bug in how Playwright works, which I tried to explain above. Do you have any specific questions? If you still believe there is a bug, please provide a repro. The one you provided works for me as expected.

**Comment by marcosvfranco** [comment]
@dgozman got it, it might be not a bug, I maybe misunderstood the behavior of `exposeFunction()`

Basically, in my test here, I need to execute a function after the page is loaded to change the UI of a part of the page, pointing to a componentID, like this

`function changeUI(componentID) {...}`
so my objective is to expose this function into the browser like that

`await sharedPage.exposeFunction('dispatchChangeUI', changeUI);`

and later on use on evaluate like this:
```
            await sharedPage.evaluate(() => {
                dispatchChangeUI('1234');
            });
```

If I do this, I don't have any result on browser, however, if I do the `sharedPage.evaluate()` declaring the funcion inside it, it works! like this:
```
await sharedPage.evaluate(() => {
                function dispatchChangeUI(componentID) {
                             (...)
                }
                dispatchChangeUI('1234');
            });
```

If it's the expected behavior please comment and close it, thanks for all the attention and support

**Comment by marcosvfranco** [comment]
Please refer to this bug https://github.com/microsoft/playwright/issues/13637
It's kind of similar, but in my case when I try to access the function exposed, it throws 
```
dispatchConsoleLog
(...args) => {
    const me = globalThis[bindingName];
    if (needsHandle && args.slice(1).some(arg => arg !== undefined)) throw new Error(`exposeBindingHandle supports a single argument, ${args.len…
```

**Comment by dgozman** [comment]
@marcosvfranco I see what you need. The easiest way is to evaluate that function instead of exposing.

```ts
// you can pass a single argument as well
function doSomeThingsInThePage(foo: string) {
  // do what you need here:
  document.body.classList.add(foo);
}

test('Testing', async ({ page }) => {
  await page.goto('https://playwright.dev');

  // evaluate the function, optionally passing an argument
  await page.evaluate(doSomeThingsInThePage, 'under-test-class-name');
});
```

**Comment by marcosvfranco** [comment]
Thanks a lot @dgozman for teaching me, I will close this as it's not a bug. It worked here
