### ISSUE TITLE
How to handle browser-based pop-ups in Playwright, such as the screen sharing selection pop-up in Chrome?

### ISSUE THREAD

**Issue by ravindra-LL** [microsoft/playwright#32585]
### Please do not submit this issue.

- [X] I understand

**Comment by dgozman** [comment]
This issue tracker is reserved for bug reports and feature requests.

For anything else, such as questions or getting help, please see:
- [The Playwright documentation](https://playwright.dev/)
- [Our Discord server](https://aka.ms/playwright/discord)
