### ISSUE TITLE
[Bug]: Auth0 + Playwright storage state does not work for more than 1 test

### ISSUE THREAD

**Issue by vishvan92** [microsoft/playwright#32594]
### Version

1.47.0

### Steps to reproduce

Our application uses auth0 with MFA. When I run the tests, the storage state file is being created and the first test is running as expected, however the subsequent test in the spec file is prompting me to login again. In the tests I am simply doing a goto(url) and asserting an element on the the home page of our application. Doing the same in both the tests. 

Also tried test.use({ storageState: require.resolve('../storage.json') })

Tested with github and it works fine. I also created a brand new project to triage the issue with no luck.

The refresh token rotation is enabled in auth0 and I increased the time of it, still doesnt help. . Below is the config and global setup. 

```
import { defineConfig, devices } from '@playwright/test';
export default defineConfig({
  globalSetup: require.resolve('./global-setup.ts'),
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    baseURL: 'https://test.com', //dummy url
    storageState: 'storage.json',
    trace: 'on-first-retry',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },

    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },

    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
  ],
});

```

```
async function globalSetup(config: FullConfig) {
  const { baseURL, storageState } = config.projects[0].use;
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.goto(baseURL!);
  await page.getByRole("button", { name: "name", exact: true }).click();
  await page.fill("#username", "test");
  await page.fill("#password", "test");
  await page.getByRole("button", { name: "name", exact: true }).click();
    let code = await generateOTP("secret");
    await page.getByLabel("test").fill(code);
    await page.getByRole("button", { name: "test" }).click();
    await page.waitForSelector("#test" );
  await page.context().storageState({ path: storageState as string });
  await browser.close();
}
export default globalSetup;
```

### Expected behavior

Expect all the tests to use the storage state and not prompt to login.

### Actual behavior

The first test in the spec file works fine, while the second test prompts to login rather than using the storage state.

### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 119.45 MB / 16.00 GB
  Binaries:
    Node: 18.20.4 - ~/.nvm/versions/node/v18.20.4/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v18.20.4/bin/npm
    pnpm: 8.6.7 - /usr/local/bin/pnpm
  IDEs:
    VSCode: 1.92.2 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.47.0 => 1.47.0
```

**Comment by migueldlt10** [comment]
According to the docs: If the path provided to storageState() is a relative path, then it is resolved relative to current working directory. Ensure that you are accessing the correct file path in your playwright config file. Also, I encountered issues where playwright was attempting to access the storageState.json file prematurely, a workaround is to use a boolean value checking if the file exists using FS module. 

ex: const foundStorageState = fs.existsSync('storageState.json');

**Comment by vandanak-allegion** [comment]
I included the check and also I had debugged by simply plugging in absolute path, havent resolved the issue

**Comment by vandanak-allegion** [comment]
I have also tried beforeEach, again it works for the first test and again the second test is prompting to login

test.beforeEach(async () => {
   const browser = await chromium.launch();
   const context = await browser.newContext({ storageState: 'absolute/path/to/json' });
   page = await context.newPage();
   await page.goto("/");
  });

**Comment by vandanak-allegion** [comment]
I am also logging the cookies within each test which works fine
const cookies = await page.context().cookies();
console.log(`cookies: ${JSON.stringify(cookies, null, 2)}`);

**Comment by dgozman** [comment]
@vishvan92 Could you please provide a full repro that we can run locally? Unfortunately, the dummy url `https://test.com` or the `generateOTP` function that is not defined anywhere, do not allow us to reproduce the issue.

**Comment by ksvvandana** [comment]
> @vishvan92 Could you please provide a full repro that we can run locally? Unfortunately, the dummy url `https://test.com` or the `generateOTP` function that is not defined anywhere, do not allow us to reproduce the issue.

This is from an testing an internal application. Using the below for generateOTP, where the secret is from deciphering the QR code from an authenticator app.

import * as speakeasy from 'speakeasy';

async function generateOTP(secret: string) {
    return speakeasy.totp({
      secret: secret,
      encoding: 'base32',
    });
  }

**Comment by mxschmitt** [comment]
We unfortunately need a self-contained reproduction, which we can run locally to reproduce your issue. Ideally something with expected and actual. Otherwise we can't act on it. Thanks for your understanding!

**Comment by mxschmitt** [comment]
Closing as per above - feel free to get back to us if you have a reproduction which you can share. Thanks for your understanding!

**Comment by emad-ms** [comment]
I think this is closed but I found my solution for this issue. I noticed that Auth0 is refreshing token on every page load and it stores again in the cookies, meaning we need to store cookie state into the Playwright storage state after each test. this is why I created a fixture that always run an afterEach hook to restore the cookies:
```
import { test as base } from "@playwright/test";

const test = base.extend({});

test.afterEach(async ({ page }) => {
  await page.context().storageState({ path: "playwright/.auth/user.json" });
});

export { test };
export { expect } from "@playwright/test";

```

and using the exported `test` instead of the original "@playwright/test" in tests

**Comment by kalon-senra** [comment]
I'm still having this issue, have you been able to resolve it in chromium?

**Comment by emad-ms** [comment]
I used `fixtures` to fix this issue and it works well. The thing is that we need to set the storage at the beginning and keep updating it at the end of each test case as the refresh token is getting updated on each page load. I have also considered multiple workers, so I store auth states per worker.
Here is what I have done in a nutshell:
```
import { test as baseTest } from "@playwright/test";
import fs from "fs";
import path from "path";

export * from "@playwright/test";
export const test = baseTest.extend<
  { afterEachTest: void }, // test scope fixture
  { workerStorageState: string } // worker scope fixture
>({
  // Use the same storage state for all tests in this worker.
  storageState: ({ workerStorageState }, use) => use(workerStorageState),

  // Authenticate once per worker with a worker-scoped fixture.
  workerStorageState: [
    async ({ browser }, use) => {
      // Use parallelIndex as a unique identifier for each worker.
      const id = test.info().parallelIndex;
      const fileName = path.resolve(
        test.info().project.outputDir,
        `.auth/worker-${id}.json`
      );

      if (fs.existsSync(fileName)) {
        // Reuse existing authentication state if any.
        await use(fileName);
        return;
      }

      // Important: make sure we authenticate in a clean environment by unsetting storage state.
       const page = await browser.newPage({ storageState: undefined });


      // Start of authentication step
      // ....
      // ....
      // End of authentication step

      // Save the storage state to a file for reuse in other tests.
      // This file will be used by the worker scope fixture.
      await page.context().storageState({ path: fileName });
      await page.close();
      await use(fileName);
    },
    { scope: "worker" }
  ],

  // Save the storage state after each test because of auth0 refresh token
  afterEachTest: [
    async ({ page }, use) => {
      await use();
      // Any code after `await use()` will run after each test.
      const id = test.info().parallelIndex;
      const fileName = path.resolve(
        test.info().project.outputDir,
        `.auth/worker-${id}.json`
      );
      // Save the storage state after each test.
      await page.context().storageState({ path: fileName });
    },
    { auto: true, scope: "test" } // Automatically run after each test
  ]
});
```

**Comment by Chaitanya045** [comment]
@emad-ms updating storage state on every test run works fine. But if we have a logout in a test then the session storage state will be updated and the login is gone. 
Lets say we have multiple roles where in a test case we want to logout and login into another user role, then the session gets updated to the other role which is not desired. 
These are the limitations I'm facing.
