### ISSUE TITLE
[Feature]: Extend toHaveAccessibleName() to accept an array of expected accessible names

### ISSUE THREAD

**Issue by aahlenst** [microsoft/playwright#32593]
### 🚀 Feature Request

It would be great if `toHaveAccessibleName()` would work as `toHaveText()` and accept an array of expected accessible names, not only a single string or regular expression. In other words, `expected: string | RegExp` should be changed to `expected: string | RegExp | (string | RegExp)[]`. 

### Example

With an Excel-like table where the columns are named A, B, ..., and the rows are named 1, 2, ..., asserting the entire table at once would look something like that:

```TypeScript
await expect(page.getByRole("row")).toHaveAccessibleName([
    "Cell A1 Cell B1 Cell C1",
    "Cell A2 Cell B2 Cell C2",
    "Cell A3 Cell B3 Cell C3",
]);
```

### Motivation

To assert the entire table with the current version of `toHaveAccessibleName()`, I have to write more lines that make the test harder to read:

```TypeScript
const rows = [
    "Cell A1 Cell B1 Cell C1",
    "Cell A2 Cell B2 Cell C2",
    "Cell A3 Cell B3 Cell C3",
];
await expect(page.getByRole("row")).toHaveCount(rows.length);
for (let i = 0; i < rows.length; i++) {
    await expect(page.getByRole("row").nth(i)).toHaveAccessibleName(rows[i]);
}
```

Furthermore, I think it would align nicely with existing assertions that have that capability, for example, `toHaveText()`.

**Comment by aahlenst** [comment]
Would a PR be considered at this stage?

**Comment by dgozman** [comment]
@aahlenst @aairiian Have you folks considered `toMatchAriaSnapshot()` instead?

```ts
await expect(page.getByRole('table')).toMatchAriaSnapshot(`
  - table
    - row "Cell A1 Cell B1 Cell C1"
    - row "Cell A2 Cell B2 Cell C2"
    - row "Cell A3 Cell B3 Cell C3"
`);
```

With the above, you can assert [accessible names, roles and structure](https://playwright.dev/docs/aria-snapshots), all in one go.

We are evaluating whether this request would be better fulfilled through other means, before releasing a new API. Let me know what you think.

**Comment by aairiian** [comment]
Hey @dgozman 👋🏻

Thanks for the suggestion!

Honestly, I haven’t worked with `toMatchAriaSnapshot()` in tests yet, but the idea makes sense to me. This method allows us to verify not just the content of elements but also their position in the UI. I see the value in this approach, and it feels like a more solid and comprehensive solution.

**Comment by dgozman** [comment]
@aairiian We are thinking about reverting the array notation for v1.50 after the API review. We'd like to focus more on aria snapshots, so please try that out and give us any feedback. If there turns out to be an important usecase that cannot be addressed with aria snapshots, we'll be happy to reapply the change again.

**Comment by aahlenst** [comment]
I haven't been able to spend a lot of time with ARIA snapshots, but so far it does not suit my needs, whereas `toHaveAccessibleName()` with an array does.

(1) It's YAML. Comparing to JavaScript or TypeScript, it's a pain to get it right, especially in a project that uses tabs for indentation. IntelliJ isn't a help, so far, and Playwright's error messages aren't that helpful, either.

(2) It's not super discoverable. I'm coming from React Testing Library, so `toHaveAccessibleName()` is somewhat close. I wasn't aware that `toMatchAriaSnapshot()` exists and that it might help me accomplish what I want. Furthermore, I like it when my E2E tests at least somewhat resemble my component tests that are written with React Testing Library. With ARIA snapshots, it's no longer the case.

(3) My biggest problem is that ARIA snapshots do not work well with selectors that match multiple elements. That is something that I use a lot. Instead, I have to match against a container and somehow ignore everything I do not care about (at least in that particular test) or change the HTML to make it disappear. Some examples that do not work well with ARIA snapshots:

* Go to https://jdkcomparison.com/, select Version > 11, assert that "Dragonwell 11 EE", "Dragonwell 11 SE", "Corretto 11", and so on are displayed.
* Go to https://jdkcomparison.com/, select Version > 11, select Vendors > Azul, check "Show differences only", assert that Properties > Virtual Machine, Garbage Collectors > CMS | G1 | Parallel | Serial | Shenandoah | Z | Custom GCs, and so on are displayed (only the titles, I do not care about the yes/no values in this particular test).

Debugging with such a large table is hell because the diffs are so large that they are useless.

Matching is verbose:

```
await expect(page.getByRole("grid")).toMatchAriaSnapshot(`
  - grid "Comparison table":
    - row "JDK names"
    - rowgroup "Properties":
      - row:
        - rowheader "Feature Version"
      - row:
        - rowheader "Virtual Machine"
      - row:
        - rowheader "Class Libraries"
`)
```

While the partial matching is nice (I can omit the heading and the button in the rowgroup), it might shadow potential problems, for example, unwanted elements.

I do not insist on having `toHaveAccessibleName(expected: string | RegExp | (string | RegExp)[])`. But considering that working with selectors that match multiple elements is common I find it weird that there are methods that accept an array while others do not. `toHaveAccessibleName()` is only one example of many. If it were possible to write a custom matcher to solve the problem I'd done so. But as far as I can see, it is impossible because it would require changes in places that cannot be extended.
