### ISSUE TITLE
[Feature]: codegen support for launchPersistentContext

### ISSUE THREAD

**Issue by DevRCRun** [microsoft/playwright#32608]
### 🚀 Feature Request

Within code I can do the follow to accommodate internal policy restrictions around incognito mode and sso with entra.

The options available to codegen  --load-storage and --save-storage don't seem to behave in the same way, creating for me an incognito browser not compatible with internal policy.

`const userDataDir = path.join(__dirname, 'playwright-user-data')`

    const browser = await chromium.launchPersistentContext(userDataDir, {
        channel: 'msedge',
        headless: false
    })

### Example

Provide a simple method for non technical business analysts to record tests, logging in with SSO without having to scaffold as described at https://playwright.dev/docs/auth#multi-factor-authentication

### Motivation

Support conditional access policies under entra that may be in place

**Comment by dgozman** [comment]
@DevRCRun Thank you for the issue!
- Could you please explain the proposed workflow in more details?
- Do you expect some data to be retained in the `userDataDir`? Are you going to use that data?
- Why exactly the isolated context created by default in codegen does not work for you?
- What are the "internal policy restrictions" we are talking about? Note that playwright does not aim to work in an environment with browser policies in place, as [explained in the docs](https://playwright.dev/docs/browsers#google-chrome--microsoft-edge).

**Comment by mxschmitt** [comment]
You can trigger codegen via [`page.pause()`](https://playwright.dev/docs/api/class-page#page-pause) which we explain the 
["codegen with custom setup"](https://playwright.dev/docs/codegen#record-using-custom-setup) doc - have you tried this? This should allow you to use Codegen with any profile you specify, custom args etc.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
