### ISSUE TITLE
[Feature]: Create a setNetworkThrottling method inside the BrowserContext or Page classes

### ISSUE THREAD

**Issue by QAComet** [microsoft/playwright#32618]
### 🚀 Feature Request

In chrome devtools (and any chromium browser), there is an option in the network tools to throttle network requests. This functionality exposes an interface to either disable network requests entirely, or throttle them.

#### Relevant docs
* https://developer.chrome.com/docs/devtools/settings/throttling/
* https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-emulateNetworkConditions
* https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-disable (may not be relevant)
* https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-enable (may not be relevant)

#### Screenshots

**Toggle the network requests/create a new profile**
![open_network_throttling_profile](https://github.com/user-attachments/assets/7cf160a7-b91f-415e-9741-90b7acc75ab6)

**Options available when creating a new network profile**
![new_network_throttling_profile](https://github.com/user-attachments/assets/9d5ce872-bae7-40e2-85f3-b57df198786b)

### Example

Here's a few API calls to consider:

#### setNetworkThrottling API
```ts
// Sets a network throttling profile for all contexts launched from a specific browser
browser.setNetworkThrottling({
    offline: false, // [OPTIONAL] true/false defaults to false
    latency: 100, // [OPTIONAL] 100 ms defaults to 0
    downloadThroughput: 100 * 1024, // [OPTIONAL] 100 KB/s, defaults to -1 for no limit
    uploadThroughput: 50 * 1024, // [OPTIONAL] 50 KB/s, defaults to -1 for no limit
    connectionType: 'wifi', // [OPTIONAL] , values can be: none, cellular2g, cellular3g, cellular4g, bluetooth, ethernet, wifi, wimax, other, defaults to undefined
    packetLoss: 10, // [OPTIONAL] 10%, defaults to 0
    packetQueueLength: 100, // [OPTIONAL] max 100 packets, defaults to 0
    packetReordering: false // [OPTIONAL] true/false defaults to false
})

// Sets a network throttling profile for all pages launched in a specific context
context.setNetworkThrottling({
    // same opts
})

// Sets a network throttling profile for all URLs accessed using a specific page.
page.setNetworkThrottling({
    // same opts
})

interface NetworkThrottlingOpts {
    offline: false, // [OPTIONAL] true/false defaults to false
    latency: 100, // [OPTIONAL] 100 ms defaults to 0
    downloadThroughput: 100 * 1024, // [OPTIONAL] 100 KB/s, defaults to -1 for no limit
    uploadThroughput: 50 * 1024, // [OPTIONAL] 50 KB/s, defaults to -1 for no limit
    connectionType: 'wifi', // [OPTIONAL] , values can be: none, cellular2g, cellular3g, cellular4g, bluetooth, ethernet, wifi, wimax, other, defaults to undefined
    packetLoss: 10, // [OPTIONAL] 10%, defaults to 0
    packetQueueLength: 100, // [OPTIONAL] max 100 packets, defaults to 0
    packetReordering: false 
}
```

Note `context` network throttling settings override the `browser` throttling settings, and similarly `page`  network throttling settings override both the `context` and `browser` throttling settings.

##### Relevant typescript interfaces

```ts
interface NetworkThrottlingOptions {
    offline?: boolean;
    latency?: number;
    downloadThroughput?: number;
    uploadThroughput?: number;
    connectionType?: 'none' | 'cellular2g' | 'cellular3g' | 'cellular4g' | 'bluetooth' | 'ethernet' | 'wifi' | 'wimax' | 'other';
    packetLoss?: number;
    packetQueueLength?: number;
    packetReordering?: boolean;
}

const defaultNetworkThrottlingOptions: NetworkThrottlingOptions = {
    offline: false,
    latency: 0,
    downloadThroughput: -1,
    uploadThroughput: -1,
    connectionType: undefined,
    packetLoss: 0,
    packetQueueLength: 0,
    packetReordering: false,
};

function setNetworkThrottling(options: NetworkThrottlingOptions) {
    return { ...defaultNetworkThrottlingOptions, ...options };
}
```

#### Enable/disable network APIs

```ts
browser.disableNetwork()
browser.enableNetwork()

context.disableNetwork()
context.enableNetwork()

page.disableNetwork()
page.enableNetwork()
```

note these are can just be proxies for `setNetworkThrottling({ offline: true/false })`

### Motivation

Having these two states/functionality are very helpful for testing certain features. For example:

1. It's useful if you want to fuzz a web application and make sure a user can continue their workflow if their network breaks at certain points.
2. It's useful for ensuring specific UI actions are triggered when the network breaks
3. It helps with making sure changes to the UI are reflected back into the application once a user regains access to their network. Think about an application using CRDTs and supports offline mode. Setting that up currently is a bit of a pain/I'd rather not intercept network requests and instead use the native APIs provided by CDP.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/8622
