### ISSUE TITLE
[Bug]: VSCode locator highlighting does not work when using the test step decorator

### ISSUE THREAD

**Issue by inadaze** [microsoft/playwright#32619]
### Version

1.43.1

### Steps to reproduce

Using VSCode and the Playwright extension version 1.1.7

1. Create a page object model class for any given web page.  Make sure to include locator properties for elements in the page.
2. Create a method in the page object model class.  It does need to do anything.
3. Create the test step decorator as outlined [here](https://playwright.dev/docs/api/class-test#test-step) in the Playwright docs
4. Decorate the method in you page object model class.
5. Open a browser using the VSCode extension testing side panel button "Pick Locator"
6. navigate to the relevant webpage that the page object model class was built for
7. select the locator property with your mouse.

### Expected behavior

The extension should have highlighted the relevant web element that is associated to the page object model locator property

### Actual behavior

The web element was not highlighted.

### Additional context

Note: if you remove the step decorator from the page object model method, the issue no longer appears.  

### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 116.98 MB / 32.00 GB
  Binaries:
    Node: 20.8.0 - ~/.local/share/mise/installs/node/20.8.0/bin/node
    Yarn: 1.22.22 - ~/.yarn/bin/yarn
    npm: 10.1.0 - ~/.local/share/mise/installs/node/20.8.0/bin/npm
  IDEs:
    VSCode: 1.93.1 - /usr/local/bin/code
  Languages:
    Bash: 5.2.26 - /opt/homebrew/bin/bash
  npmPackages:
    @playwright/test: 1.43 => 1.43.1 
    playwright: 1.43 => 1.43.1
```

**Comment by mxschmitt** [comment]
Would it be possible to share concrete code with us instead of giving us instead of giving us instructions on how to construct the code?

**Comment by mxschmitt** [comment]
I can repro - looking into it!

**Comment by mxschmitt** [comment]
This should be fixed in our [Beta version](https://github.com/microsoft/playwright-vscode/wiki) of the extension.
