### ISSUE TITLE
[Question] Channels download.delete and download.createReadStream

### ISSUE THREAD

**Issue by kblok** [microsoft/playwright#3262]
I realized that [download.delete](https://github.com/microsoft/playwright/blob/master/src/rpc/client/download.ts#L62) is using a channel to delete the file. I thought that it would make sense if we'd have a remote server. The file would be in the server, not in the client.

But then I found that [download.createReadStream](https://github.com/microsoft/playwright/blob/master/src/rpc/client/download.ts#L53) is solving everything on the client-side. I think this is quite inconsistent. Or we address everything on the server (getting ready for a remote server), or we solve file manipulation on the client.

**Comment by kblok** [comment]
Thoughts @pavelfeldman?

**Comment by aslushnikov** [comment]
@kblok feel free to ping us on slack :-) I'll close the issue here.

**Comment by dgozman** [comment]
With #3634, we now have:
- download.path works locally and throws in remote scenario;
- download.delete always deletes on the server;
- download.createReadStream streams bytes from the local file or remote server;
- download.saveAs copies a file when running locally or uses saveAsStream to stream bytes from remote server to save locally.

Feel free to ask more questions.
