### ISSUE TITLE
[Feature]: Export classes of internal reporters

### ISSUE THREAD

**Issue by effektsvk** [microsoft/playwright#32639]
### 🚀 Feature Request

Could you please export all the classes of internal reporters, including the `BaseReporter`? We would like to extend existing reporters without the need to implement everything from scratch. Currently, we are making this available by patching package.json to allow the following exports:
```diff
+    “./lib/reporters/base”: “./lib/reporters/base.js”,
```

### Motivation

We intend to reuse the existing implementation of reporters.

**Comment by mxschmitt** [comment]
We consider them an implementation detail - so the functions etc. can change any time. We recommend copying them if you are interested in them.
