### ISSUE TITLE
[Bug]: Playwright Test for VS Code - launching tests with play button behaves different from command line

### ISSUE THREAD

**Issue by cc-julmer** [microsoft/playwright#32644]
### Version

1.40.1

### Steps to reproduce

Run a test using the play button provided by the test runner. Then run the same test using the command line. The test errors when started by the play button. However, running the test by the command line works. Curious what the command that the test runner uses to start a test as something is different between the two methods. I am also using an electron app wrapper, and it is specifically failing on closing that electron app in a 'after every' test block.

### Expected behavior

Play button to call up tests functions identically to using the command line

### Actual behavior

Playwright test for VS code runs tests differently somehow than command line

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 18.51 GB / 31.88 GB
  Binaries:
    Node: 20.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.93.1 - C:\Users\usernamehere\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.47.1 => 1.47.1
    playwright: ^1.47.1 => 1.47.1
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
