### ISSUE TITLE
[Feature]: Export globals

### ISSUE THREAD

**Issue by effektsvk** [microsoft/playwright#32640]
### 🚀 Feature Request

Could you please export the globals?
Currently, we are making this available by patching package.json to allow the following exports:
```diff
+    “./lib/common/globals”: “./lib/common/globals.js”,
```

### Motivation

We would like access `CurrentTestInfo` in reusable code without the need to drill this information from the test.

**Comment by mxschmitt** [comment]
You can call

    import { test, expect } from '@playwright/test';
    ....
    console.log(test.info())

During your test execution, which gives you access to the TestInfo. 

Would that work for you?

**Comment by effektsvk** [comment]
Yes, that would work, thank you!
