### ISSUE TITLE
[Feature] page.getAttribute('value') confuses people

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#3265]
**Situation**:
For users who are migrating from Selenium over to Playwright it might be confusing that we handle the element attributes in the `getAttribute()` method strictly and returning by that only element attributes. For them it might be logical that it returns properties too. I agree on that.

**Selenium**:
Selenium solves this by trying to get the property first and using the attributes as a fallback, see here:

https://github.com/SeleniumHQ/selenium/blob/941dc9c6b2e2aa4f701c1b72be8de03d4b7e996a/java/client/src/org/openqa/selenium/WebElement.java#L96-L130

**Possible solutions**:
Since Pavel proposed to not modify the `getAttribute()` method since it would then work differently what the name says, I would maybe add a helper function to it. Usage could look like as follows:

```js
page.getElementValue("#foo", "value") // not sure about a better function name
```

**Example**
See the following example which works on Selenium but not on Playwright once you migrate over to Playwright: https://try.playwright.tech/?s=27y84

- https://playwright.slack.com/archives/CSUHZPVLM/p1624437685395400

**Comment by pavelfeldman** [comment]
I'd say your expectations are broken, but it does not mean this is not a migration problem. We could warn the user that they want evaluate(e => e.value) when they get missing value attribute on an input/textarea. We could also introduce `inputValue()` next to `tectContent` for convenience.

**Comment by mxschmitt** [comment]
> I'd say your expectations are broken, but it does not mean this is not a migration problem. We could warn the user that they want `evaluate(e => e.value)` when they get missing `value` attribute on an input/textarea. We could also introduce `inputValue()` next to `tectContent` for convenience.

Let's see how many users will face into that issue and then add the suggested feature like a warning and a inputValue() function e.g.

**Comment by niyarlatotep** [comment]
Faced the same issue, solved by ```await page.$eval('input[type=\"email\"]', el => el.value)``` but as i understand it doesn't wait for element am I wrong?

**Comment by mxschmitt** [comment]
@niyarlatotep you are right, $eval etc. does not wait for the [actionability checks](https://playwright.dev/#version=v1.6.1&path=docs%2Factionability.md&q=).

**Comment by niyarlatotep** [comment]
@mxschmitt so it's not equivalent to textConten, it would be better to have a method with the same behaviour imho, but it's not so critical though

**Comment by pavelfeldman** [comment]
Thank you for reporting this issue and providing comments to those that might be facing a similar problem. I am now closing this as a part of the triage, please feel free to file a new issue with additional details. Given the limited resource and a lot of requests, we need to fulfill most popular requests and at the same time keep our issue database manageable.

**Comment by rinogo** [comment]
For those needing an example of how to do this, check this updated sandbox:

https://try.playwright.tech/?s=t5tfy46

**Comment by mxschmitt** [comment]
Feedback from Slack:

```
Thanks. It's funny that the github issues talk about this as a migration problem for people coming from selenium. I definitely see the problem there if Selenium tries to get the property and then fallsback to the attribute. However, I have no experience with Selenium and this is still confusing to me.

This should definitely be documented on this page: https://playwright.dev/python/docs/input as well as probably this page: https://playwright.dev/python/docs/core-concepts#execution-contexts-playwright-and-browser and this page: https://playwright.dev/python/docs/api/class-page#page-get-attribute

There should probably also be a dedicated getproperty method to go along with getattribute

oh and probably this page: https://playwright.dev/python/docs/assertions
```

**Comment by typetetris** [comment]
I was trying to get the `readyState` property of an `video` element. The following worked for me

    const remoteVideo = page.locator('video.remote');
    const readyState = await remoteVideo.evaluate(e => (e as HTMLVideoElement).readyState);
