### ISSUE TITLE
[Bug]: Playwright Service - Running playwright tests in headless mode taking either more similar time as running them in headed mode.

### ISSUE THREAD

**Issue by tusharnaresh** [microsoft/playwright#32668]
### Version

1.40.1

### Steps to reproduce

I have trace reports of both the runs and the size of them is around 1 Gb. They contain sensitive information, so please guide me to where and how I can share the traces.

### Expected behavior

We are running around 400 tests with 20 workers using the playwright service. We were running the tests in headed mode and the execution time of the tests was coming around 12-15 minutes. On switching to headless mode, we expected a drop in the execution time but it either comes similar or higher compared to the headed mode.

### Actual behavior

The execution time is coming similar or higher in headless mode as compared to running tests in headed mode.

### Additional context

Config options
`timeout: 90 * 1000,
    fullyParallel: true,
    forbidOnly: false,
    retries: 2,
    workers: 20,
    use: {
        trace: 'off',
        headless: false,
    }
`

### Environment

```shell
Trigger point: Github CI
```

**Comment by mxschmitt** [comment]
Are you referring to [Microsoft Playwright Testing Service](https://azure.microsoft.com/products/playwright-testing)? They have a dedicated support channel [here](https://github.com/microsoft/playwright-testing-service).

**Comment by mxschmitt** [comment]
Closing as per above.
