### ISSUE TITLE
[Regression]: Fixture with an array of objects passed in, reads only the first object

### ISSUE THREAD

**Issue by kosteklvp** [microsoft/playwright#32667]
### Last Good Version

1.45

### First Bad Version

1.46, 1.47

### Steps to reproduce

After upgrading to Playwright 1.47 from 1.45, I discovered that the behavior of using a fixture accepting array of objects changed.

I have prepared a simplified example that illustrates this situation.

```
import { test as baseTest } from '@playwright/test';

const test = baseTest.extend<{
    array: any[];
}>({});

test.use({
    array: [{ foo: '1' }, { foo: '2' }],
});

test('Example test', ({ array }) => {
    console.log(array);
});
```

### Expected behavior

When running this code on Playwright 1.45 it prints:
`[ { foo: '1' }, { foo: '2' } ]`

### Actual behavior

When running this code on Playwright 1.46 it prints:
`{ foo: '1' }`

### Additional context

It used to work before, so it looks like a regression to me. When using e.g. array of numbers, it works as expected.

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12800H
    Memory: 4.97 GB / 31.69 GB
  Binaries:
    Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.5 - ~\AppData\Roaming\npm\pnpm.CMD
  IDEs:
    VSCode: 1.91.1 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: 1.46.0 => 1.46.0
```

**Comment by mxschmitt** [comment]
Wrapping the array into an additional array should fix it, see [these docs](https://playwright.dev/docs/test-fixtures#:~:text=Array%20as%20an%20option%20value). We documented it as a potentially breaking change in the [release notes](https://github.com/microsoft/playwright/releases/tag/v1.46.0#:~:text=Possibly%20breaking%20change).

Relates https://github.com/microsoft/playwright/issues/32033

**Comment by kosteklvp** [comment]
Ok, we will do it like this.

Do you know if this will be changed in the future, or will it stay like this?

**Comment by mxschmitt** [comment]
We don't have plans to change it again.

**Comment by NagRock** [comment]
@mxschmitt any reason behind this? 

Having some extra wrappers and options objects based on the array content looks like very unstable API.

**Comment by cdevos-purse** [comment]
Seconding what @NagRock said, i think the type needs to be updated to make this explicit in intellisense. 

As of right now, if you pass an array, typescript will be fine with it. If you wrap the option in an Array<>, the types get all messed up in the fixture.

**Comment by kosteklvp** [comment]
This is not obvious, and without reading documentation it can be problematic.

**Comment by tessawiedmann** [comment]
Also agreed, its not clear

**Comment by Verm1n** [comment]
Hi there, open issue please, i spent almost all day to understand why my tests is not working :)
