### ISSUE TITLE
[Bug]: Playwright Errors not respecting ts ignore rules

### ISSUE THREAD

**Issue by jwilliams-met** [microsoft/playwright#32679]
### Version

1.47.0

### Steps to reproduce

Assign variables as any without reference is causing my playwright tests to fail. Even though they compile correctly via webpack.DefinePlugin

### Expected behavior

I expect to ignore playwright errors using // @ts-expect-error

### Actual behavior

ReferenceError causing failed tests
![image](https://github.com/user-attachments/assets/618fcca0-c1d2-4fc2-8a4b-63d8a6553ef6)

### Environment

```shell
WSL: 10.4
Yarn: 4.4.0
Typescript: 5.5.3
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
