### ISSUE TITLE
Not able to enable hardware acceleration in playwright or when integrating playwright with browserstack 

### ISSUE THREAD

**Issue by Amansaxena001** [microsoft/playwright#32678]
I am integrating browserstack into my playwright project for a webgl based canvas app. I can't get my head around on how to enabled hardware acceleration on browserstack browser or via playwright so that the webGL application can run.

Do you have any idea how I can achieve the same ?

**Comment by mxschmitt** [comment]
This sounds like an issue with Browserstack, I recommend reaching out to them.
