### ISSUE TITLE
[Bug]: “Playwright Test for VSCode” extension. and testIdAttribute: 'testlabel'

### ISSUE THREAD

**Issue by Mickael-BL** [microsoft/playwright#32681]
### Version

Version 1.47.0-alpha-2024-08-29

### Steps to reproduce

I use Playwright with Visual Code and the “Playwright Test for VSCode” extension.
The extension's recorder and locator functionality ignores the testIdAttribute: 'testlabel' parameter in the playwright.config.js file.

### Expected behavior

Whereas npx playwright codegen --test-id-attribute=“testlabel” works fine using the test-id-attribute as a priority

### Actual behavior

The extension ignores the testIdAttribute: 'testlabel' parameter in the playwright.config.js file.

### Additional context

Extension version: Playwright Test for VSCode v1.1.7

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 43.86 GB / 63.67 GB
  Binaries:
    Node: 20.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.3 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.93.1 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.47.0-alpha-2024-08-29 => 1.47.0-alpha-2024-08-29
```

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/26777 - please upvote it there.
