### ISSUE TITLE
[Feature]: Fail after all tests failure percent

### ISSUE THREAD

**Issue by vim-daniel** [microsoft/playwright#32690]
### 🚀 Feature Request

In the test configurations add a property `abandonAfterFailuresPercentage`
When a test fails we should check if the sum of already failed tests pass this percentage in such a case we should not continue running more tests and instead finish the test run with the already failed tests results.

Test retries should not be counted, meaning  text X failed and after 2 retries it kept failing - it should be counted as 1 failure.
also if test Y failed and after 2 retries it passed - it should not count as a failure

### Motivation

The motivation for this is to fail fast - usually when you have many tests and a bunch of them fail it's because of a common issue, in which case waiting for the full test run & retries can be very time consuming and not helpful.

**Comment by mxschmitt** [comment]
Playwright has `--max-failures=123` where you can specify that. In the next Playwright version it doesn't include retries anymore. So I guess the feature request could be about supporting percentage in this CLI option?

(when talking about CLI option I also mean config option)

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
