### ISSUE TITLE
[Question] Mouse smooth scroll

### ISSUE THREAD

**Issue by heyt0ny** [microsoft/playwright#3269]
Hi!

I need to smoothly scroll the page, to make element visible. Currently there 2 options, but they have downsides:
1) `elem.scrollIntoViewIfNeeded()` - which is not smooth at all
2) `page.keyboard.press("ArrowDown")` - I can call it many time (so scrolling become "smooth)" and wait until bounding box of element is within the viewport. But I have problems with inputs, because if mouse hovers an input and you press "ArrowDown" - it select inputs instead of scrolling

Is there any way to scroll mouse smoothly?

**Comment by aslushnikov** [comment]
There's no way currently; but it'll be solved with the mouse wheel support that's tracked with #1115
