### ISSUE TITLE
[Feature]: Support for the user given filename during download.

### ISSUE THREAD

**Issue by fmrahman** [microsoft/playwright#32692]
### 🚀 Feature Request

When downloading the files in Playwright the filenames are in UUID format instead of the application suggested filename. I referred to the issue [7464](https://github.com/microsoft/playwright/issues/7464), where it was mentioned that this is an expected behavior. 
Is it possible to override this behavior using the [ignoreDefaultArgs](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-persistent-context-option-ignore-default-args) option. Something like _ignoreDefaultArgs: ['--downloadUniqueFileName']_.

In my case my playwright test script takes the responsibility of the uniqueness of filenames in the directory.

### Example

Example: ignoreDefaultArgs: ['--downloadUniqueFileName'].

### Motivation

The filenames are important to confirm whether the specific file got downloaded. The uniqueness of the filenames are handled by the applications itself. I feel it would be better if there is an option to override the default functionality of files saving as UUID.

**Comment by mxschmitt** [comment]
You can receive the real file name by calling `download.suggestedFileName()` see [this guide](https://playwright.dev/docs/downloads). This allows you to confirm it via the code inside a test - would that work for you?

**Comment by fmrahman** [comment]
Thanks @mxschmitt for the suggestion but that doesn't work for my requirement. Let me explain my use-case and the code-base in detail.
Actually we are a Synthetic Monitoring team where we capture HAR and screenshots for every click action.

We are using Chrome browser and we have our own Chrome plugin that monitors the test executions. This plugin dumps the HAR and screenshots during the respective click actions. During the dump we propose a unique filename (nano timestamp) in a different folder for every execution. We use [chrome.downloads.download ](https://developer.chrome.com/docs/extensions/reference/api/downloads#method-download)API for dumping. The problem is even though we are suggesting a filename the files are saved with UUID, without the extensions.

After execution we have another piece of code that parse HAR files as per its filename having extension .har and also uses the filename (timestamp) for the ordering of the visited pages. We also uses the screenshot files having extension .jpg.

Now all the filenames are in UUID format we don't know the file type from filename.

It would be great helpful for our team if you can provide the feature to ignore the default behavior of saving the files in UUID with the option _ignoreDefaultArgs: ['--downloadUniqueFileName']_.

Thanks.

**Comment by mxschmitt** [comment]
How do you invoke Playwright? Looks like you can just do the following and it should work for you?

```ts
page.on('download', download => download.saveAs(path.join(__dirname, 'downloads', download.suggestedFilename())));
```

**Comment by fmrahman** [comment]
Yes, I have tried that option too. 

The browser is launched as part of test in the playwright script.
`test('example test', async ({ page }) `

The files which I am persisting using the  chrome.downloads.download  API are not triggering the page.on('download') event.

Thanks.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/19885.

**Comment by fmrahman** [comment]
I have tried your suggestion as mentioned [#19885 (comment)](https://github.com/microsoft/playwright/issues/19885#issuecomment-1377977454). But it didn't worked completely. Now I can see the extensions in the file name. But the file name is still UUID. Earlier there were no extensions in the file name.

My use-case is I am dumping the HAR file as part of a plugin code not from the application download file. My plugin job is to dump a HAR whenever there is a click happened as part of the test execution. For the HAR download plugin code I am using the API chrome.downloads.download.

Can you please suggest any other alternative for this issue.

Thanks.
