### ISSUE TITLE
[internal]: vscode debugging is broken in unreleased version

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#32710]
Not possible to debug todomvc after https://github.com/microsoft/playwright-vscode/commit/4328be9555ecfe8a241e1ed3480e5e2b1866c9cf

Repro: Set a breakpoint in `should allow me to add todo items` and try to debug it.

**Comment by mxschmitt** [comment]
Note:

```
      this._vscode.debug.onDidTerminateDebugSession(() => {
        debugEnd.cancel()
      });
```
is getting called and causing the debugging session to end.

**Comment by Skn0tt** [comment]
Whew, good job catching this! I've investigated and it seems that our main debug run spawns multiple "debug sessions" underneath. The child process that's used to evaluate the config gets its own "debug session", and as it sucessfully closes the session calls `onDidTerminateDebugSession`. I'll see if we can limit this to only listen for the main debug run.

**Comment by Skn0tt** [comment]
Here's another attempt: https://github.com/microsoft/playwright-vscode/pull/537
