### ISSUE TITLE
[Bug]: Limited view in Body on Network tab in trace viewer

### ISSUE THREAD

**Issue by AntonKlepik-orca** [microsoft/playwright#32725]
### Version

1.47.1

### Steps to reproduce

There is a limited view when trying to review response body in trace viewer with no possibility to scale/extend it

### Expected behavior

Expected full content block view

### Actual behavior

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/086d8df7-4b60-4829-a991-eba8806be565">
There is no way to change/extend body value

### Environment

```shell
macOs Sonoma 14.6.1 
pw 1.47.1
```

**Comment by mxschmitt** [comment]
We had a similar issue filed in https://github.com/microsoft/playwright/issues/32552 but we fixed it in 1.47.1.

What does `npx playwright --version` give you?

I tried to reproduce it but for me it was working as expected.

**Comment by AntonKlepik-orca** [comment]
my bad, sorry
1.47.0
issue can be closed
