### ISSUE TITLE
[Bug]: Base URL mentioned in the config is not picking in the globalSetup.ts file

### ISSUE THREAD

**Issue by iamakhildabral** [microsoft/playwright#32727]
### Version

playwright@1.47.1

### Steps to reproduce

1. Mention your baseUrl in the config file.
2. Create a globalSetup file
3. use the base url in the globalSetup file by page.goto('/');
4. Run your rest of the test

### Expected behavior

once set up in the config file globalSetup should pickup the base url.

### Actual behavior

it is not picking the baseurl which force you to hardcode it.

### Environment

```shell
System:
Windows 11
Browser:
Latest npx playwright install chromium
```

**Comment by mxschmitt** [comment]
This is expected, the globalSetup doesn't take anything from the playwright.config into consideration for its launch/context options. We recommend [project dependencies](https://playwright.dev/docs/test-global-setup-teardown) instead, which are the successor of globalSetup. They don't suffer from this limitation.
