### ISSUE TITLE
[Bug]:  setting sources: false in trace config does not prevent source recording

### ISSUE THREAD

**Issue by ibrocodes7** [microsoft/playwright#32745]
### Version

1.46.0

### Steps to reproduce

1. Set up Playwright configuration in TypeScript with the following trace options:
```
{
    trace: 'on',
    sources: false,
    attachments: false,
    screenshots: true,
    snapshots: true
}
```
2. Run a Playwright test with this configuration.
3. Open the generated trace output after the test run.
4. Check if source files are being recorded.

### Expected behavior

No source files should be recorded in the trace when sources: false is specified in the configuration.
All other options (attachments: false, screenshots: true, snapshots: true) should work as expected.

### Actual behavior

Source files are still being recorded despite setting sources: false.
Other options (attachments, screenshots, snapshots) behave as expected and follow the configuration properly.

### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.18 GB / 16.00 GB
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 7.6.0 - ~/thoughtspot/node_modules/.bin/pnpm
  IDEs:
    VSCode: 1.93.1 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.46.0 => 1.46.0
```

**Comment by mxschmitt** [comment]
While I was able to reproduce the behaviour, it seems to work as expected:

- When having `sources: false` we don't include them in the trace - but we will try to open the local file directly if its available. If you run the Trace Viewer locally, the files are available and we show them.
- When having `sources: true` we include a copy of the source file into the trace.zip

So when you try to open the trace.zip on https://trace.playwright.dev it won't show any sources if you set `sources: false`.

**Comment by mxschmitt** [comment]
Closing as per above.
