### ISSUE TITLE
[Feature]: Adding tag to test from fixture

### ISSUE THREAD

**Issue by cthlo** [microsoft/playwright#32747]
### 🚀 Feature Request

Is there any way to specify tag(s) in a fixture which will be applied to the tests that consume the fixture?

I assume that #30286 was denied because tags need to be computed without running the tests (including the fixtures).

But in this case, I'm thinking something like

```typescript
export const test = base.extend<AxeFixture>({
  makeAxeBuilder: async ({ page }, use, testInfo) => {
    const makeAxeBuilder = () => new AxeBuilder({ page })
        .withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'])
        .exclude('#commonly-reused-element-with-known-issue');

    await use(makeAxeBuilder);
  }
}, { tag: '@a11y' });
```
(notice the second argument for `extend`)

which I think will allow the tags to be captured before any test is run.

### Motivation

I have a set of a11y tests, and they all consume the a11y fixture.
Instead of adding `@a11y` to each test individually, it'd be nice if I can specify the tag(s) that should be added to tests from the fixture definition.
The tagging would allow me to run just these tests - `npx playwright test --grep @a11y`

**Comment by yury-s** [comment]
> I assume that https://github.com/microsoft/playwright/issues/30286 was denied because tags need to be computed without running the tests (including the fixtures).

Sounds like dynamic annotations suggested in that issue would work in your scenario. Can you elaborate on why they don't meet your requirements?

**Comment by cthlo** [comment]
> > I assume that #30286 was denied because tags need to be computed without running the tests (including the fixtures).
> 
> Sounds like dynamic annotations suggested in that issue would work in your scenario. Can you elaborate on why they don't meet your requirements?

I would like to be able to run just these tests - `npx playwright test --grep @a11y`
(Added this info to the request) Thanks!

**Comment by yury-s** [comment]
This is not gonna work, the fixtures are evaluated at the test execution time where as filtering is done before running any tests. The closest you can do is to call `test.skip()` dynamically from beforeEach for the tests that you don't want to run.

**Comment by cthlo** [comment]
> This is not gonna work, the fixtures are evaluated at the test execution time where as filtering is done before running any tests. The closest you can do is to call `test.skip()` dynamically from beforeEach for the tests that you don't want to run.

@yury-s
Could you please kindly explain how tags are applied for regular tests, e.g. `test.describe('dashboard', { tag: '@a11y' }, ...)`?
If a fixture can be defined as follow: (which is the feature request)
```typescript
export const test = base.extend<AxeFixture>({
  makeAxeBuilder: async ({ page }, use, testInfo) => {
    ...
  }
}, { tag: '@a11y' }); // note this additional option
```

Is this `{ tag: '@a11y' }` option (doesn't currently exist) not available before test execution? cc @mxschmitt
