### ISSUE TITLE
[Feature]: Ability to type in the address bar

### ISSUE THREAD

**Issue by mdmower** [microsoft/playwright#32754]
### 🚀 Feature Request

I would appreciate the ability to type into the address bar.

From https://github.com/microsoft/playwright/issues/15126, I understand this is currently not possible and seems out of scope. The author of that issue never got back to the question about use case. This would help test implementations of the [omnibox API](https://developer.chrome.com/docs/extensions/reference/api/omnibox) in Edge, Chrome, and Firefox extensions.

Even if exposing suggest results is deemed out of scope, the ability to send `keyword some text[enter]`, where `keyword` is the [keyword that triggers an extension](https://developer.chrome.com/docs/extensions/reference/api/omnibox#manifest) (defined in the manifest) and `some text` is the text to be handled by [`onInputEntered`](https://developer.chrome.com/docs/extensions/reference/api/omnibox#event-onInputEntered), would help extension developers test basic functionality.

### Example

```js
await browser.addressBar.type('doi 10.1000/182');
await browser.addressBar.press('Enter');
```

### Motivation

This would enable more complete testing of extensions for Edge, Chrome, and Firefox. For example, in my [doi-resolver project](https://github.com/mdmower/doi-resolver/tree/dev/tests), there is currently no way to test omnibox API usage.

**Comment by yury-s** [comment]
As Omnibox is not a part of the web platform, Playwright does not support it and we are not planning to work on it at the moment.

Support for firefox extensions is tracked in https://github.com/microsoft/playwright/issues/7297

**Comment by mdmower** [comment]
@yury-s - for what it's worth, omnibox is included in [w3c/webextensions](https://github.com/w3c/webextensions) interfaces: [interfaces/chromium/chrome-common-extensions-api/omnibox.json](https://github.com/w3c/webextensions/blob/main/interfaces/chromium/chrome-common-extensions-api/omnibox.json). Playwright is one of the very few options extension developers have for testing extensions (the other being manual pairing of puppeteer with a testing framework like jest or mocha), so I hope the team will keep an open mind about supporting this neglected community.
