### ISSUE TITLE
[Feature]: Ability to respond to optional permission requests

### ISSUE THREAD

**Issue by mdmower** [microsoft/playwright#32755]
### 🚀 Feature Request

I would appreciate the ability to confirm or reject optional permission requests in extensions for Edge, Chrome, and Firefox.

Extension developers are encouraged to request only necessary permissions, and to make use of the [permissions API](https://developer.chrome.com/docs/extensions/reference/api/permissions) for optional permissions so that end users have a chance to review the rationale for a permission request. It is not possible to respond to these permissions requests in Playwright.

### Example

`await browser.permissionsDialog.confirm();`
or
`await browser.permissionsDialog.reject();`

### Motivation

This would enable more complete testing of extensions for Edge, Chrome, and Firefox. For example, in my [doi-resolver project](https://github.com/mdmower/doi-resolver/tree/dev/tests), I have to make all permissions required before testing, leaving a lot of code related to optional permissions handling untested.

**Comment by yury-s** [comment]
Playwright focuses on testing web platform features and optional permission requests from extensions is out of scope. Closing this report as we are not planning to work on it.
