### ISSUE TITLE
[Feature]: Add  Locator selectorOrLocator: string|Locator support to FrameLocator

### ISSUE THREAD

**Issue by Makavelic** [microsoft/playwright#32766]
### 🚀 Feature Request

Page -> Locator got support for selectorOrLocator: string|Locator. I would like to request for FrameLocator to receive the same support.

### Example

I have page classes that need to work in an iframe and non iframe environment depending on context. To do this I have a getPage function that returns either Page or FrameLocator. The page class functions will then use getPage() instead of Page directly. In order for this to work, I need FrameLocator to work the same way.

### Motivation

This will help Page Object Model work in both iframe and non iframe contexts.

**Comment by yury-s** [comment]
[`FrameLocator.locator`](https://playwright.dev/docs/api/class-framelocator#frame-locator-locator) already accepts `Locator` as argument. If you mean support of `Locator` parameter in `Page.locator` method, it doesn't make sense as it is equivalent to using the `Locator` that you'd pass as a parameter. Can you clarify the request? A code example would be helpful.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
