### ISSUE TITLE
How to Maintain Existing HAR Files and Generate New HAR Files for Additional Tests in same spec?

### ISSUE THREAD

**Issue by abhishekrawat26** [microsoft/playwright#32767]
Hi Playwright Community,

I have a set of existing tests for which I have already recorded HAR files. Now, I want to add more tests to the same test spec file and generate new HAR files for these additional tests without affecting the existing recorded HAR files.

I am looking for an approach to:

1. Maintain my existing recorded HAR files.
2. Generate and record new HAR files for the additional tests.
3. Ensure that the new HAR files do not overwrite the existing ones unless there are changes.

**Comment by yury-s** [comment]
This doesn't sound like a bug or feature request, please use our [community resources](https://playwright.dev/community/welcome) for general questions. If you think this is a bug in Playwright, please open a new issue and follow the bug template.
