### ISSUE TITLE
[Feature]: Ability to exclude a specific PROJECT from your REPORT without the need for using Custom Reporting

### ISSUE THREAD

**Issue by MatthewIceland** [microsoft/playwright#32763]
### 🚀 Feature Request

The ability to configure a project e.g. a Smoke test, TestData creation, so that it does not appear in or affect Test Results. The ability to include/exclude a project from test reporting should be easy to update within the project in the playwright.config.ts file

![image](https://github.com/user-attachments/assets/18f223eb-41c2-4e82-8e97-f12dd7c443f7)

### Example

I am testing an application where I need to create some Test Data prior to the tests being executed. It involves creating items matching 4 of one type, 4 of another, and 3 of another.

This process is run prior to the Playwright tests and the .spec.ts files are run as if they were tests, but I do not want to include them in the results. In a run of 112 tests, it means 11 don't tell us anything, and this skews the figures.

The main recommendation I get is to 'skip' the tests, but the Test Data is essential for the other tests, so this is not a possibility.

In the HTML reporter, the tests are tagged as per their project 'testData'. If there was a way to remove these particular tests from the final results, that would be much appreciated.

In the attached image, I have added what a new 'reportResults' on/off feature might look like:

![image](https://github.com/user-attachments/assets/cbb61652-5eb4-42d8-ac32-28e37e07b3d8)

### Motivation

This will enable Playwright users to deliver more appropriate test results. Without this feature, if a user has 100 tests, and 10 are simply for generating data, then the user is reporting 100/100 tests have passed, when only 90/100 actually contain proper assertions/criteria.
It would also be a much quicker solution than the 'custom reporter' option, which takes much longer to set up and tailor to your needs.

**Comment by yury-s** [comment]
If you don't want to see the tests as part of the test run, you can have a separate playwright test run prior to running the tests, so that the test data is generated first and then other tests run, would that work?

```
npx playwright test --project=generate-test-data
npx playwright test --project=actual-tests
```

**Comment by yury-s** [comment]
Another option would be to use globalSetup for generating data or just use something outside of the test harness to generate the test data. In Playwright anything marked as a test is a test and will end up in the test report as a test.
