### ISSUE TITLE
[Regression]: Intl.DateTimeFormat().resolvedOptions().locale doesn't work as expected on latest playwright browsers

### ISSUE THREAD

**Issue by vishalshrm539** [microsoft/playwright#32781]
### Last Good Version

NA

### First Bad Version

latest

Basically with any @Playwright/test version, with the latest browsers(installed using `npx playwright install`)

### Steps to reproduce

1. Install the latest playwright browsers using: `npx playwright install`
2. Execute `Intl.DateTimeFormat().resolvedOptions().locale` on the console, it doesn't work as expected.

### Expected behavior

Execute `Intl.DateTimeFormat().resolvedOptions().locale` on the console, it doesn't work as expected. It should return 'en-GB' for me but returns 'en-US' rather. This used to work fine with the older browsers.

### Actual behavior

`Intl.DateTimeFormat().resolvedOptions().locale` should return 'en-GB' which is what my Chrome browser returns.

### Environment

```shell
OS: MAC
```

**Comment by yury-s** [comment]
Please follow our bug template and share a reproducible example which we could run locally. I was not able to reproduce the issue with the following test:

```js
import { expect, test } from '@playwright/test';

test.use({ locale: 'en-GB' });

test('locale', async ({ page }) => {
  expect(await page.evaluate(() => Intl.DateTimeFormat().resolvedOptions().locale)).toBe('en-GB');
});

```

**Comment by vishalshrm539** [comment]
@yury-s My concern was if I run a playwright test in Chromium browser then the `Intl.DateTimeFormat().resolvedOptions().locale` API doesn't return `en-GB`(but return en-US rather) which is what I expect as my Chrome browser returns that.

I don't want to set the `locale` using test.use({ locale: 'en-GB' });.
