### ISSUE TITLE
[Bug]: Directory import is not supported resolving ES modules imported from..

### ISSUE THREAD

**Issue by Luk-z** [microsoft/playwright#32780]
### Version

1.46.1

### Steps to reproduce

Run npx playwright test when use imports like: "import Stack from '@mui/material/Stack'"

### Expected behavior

To run test without error and to resolve import normally

### Actual behavior

When I run npx playwright test I get this error: Directory import 'C:\Users\mirnesz\Desktop\Projekti\frontend-dev\node_modules@mui\material\Stack' is not supported resolving ES modules imported from C:\Users\mirnesz\Desktop\Projekti\frontend-dev\src\components\custom-datagrid\enhanced-datagrid-container.tsx

### Additional context

This issue is a dumb copy of https://github.com/microsoft/playwright/issues/32205 because it isn't fixed

### Environment

```shell
"@playwright/test": "^1.42.1",
"playwright": "^1.46.1",
```

**Comment by yury-s** [comment]
Please share a minimal reproduction project, so that we could repeat the problem locally.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
