### ISSUE TITLE
[Feature]: Make ssim-cie94 a separate package

### ISSUE THREAD

**Issue by keaukraine** [microsoft/playwright#32785]
### 🚀 Feature Request

Can you please make `ssim-cie94` image comparator a standalone npm package so we can use it with an older version of playwright?
It is very time-consuming for us to migrate to the latest version but we could benefit from this comparator.

### Motivation

It is very time-consuming for us to migrate to the latest version but we could benefit from this comparator.

**Comment by yury-s** [comment]
This is out of scope for Playwright. With that said, Playwright is an open source project and you are welcome to create a separate project and copy the comparator code over there.
