### ISSUE TITLE
[Bug]: component.update remove slot default value

### ISSUE THREAD

**Issue by Hai-San** [microsoft/playwright#32809]
### Version

1.47.2

### Steps to reproduce

```
import { test, expect } from '@playwright/experimental-ct-vue';

import XAlert from '@base/components/XAlert/XAlert.vue';

const testSlots = {
  default: 'New Slot Value',
};

test(`should render XAlert`, async ({ mount }) => {
  const component = await mount(XAlert, {
    slots: testSlots,
  });

  await component.update({
    slots: testSlots,
  });

  await expect(component).toHaveScreenshot(`name.png`, { animations: 'allow' });
});
```
![image](https://github.com/user-attachments/assets/94d7dd71-3a61-4388-a33d-fdce4634a0de)

### Expected behavior

I expect the default slot to remain with the passed value when being rendered and not lose this value when updating the component.

The screenshot should look like this:
![image](https://github.com/user-attachments/assets/b7bccaea-60f5-4c38-a0db-90c0a7f54f25)

### Actual behavior

Currently, if the component's update function is used, whether to change props or slots, the value passed in the default slot is removed.

The screenshot shouldn't look like this:
![image](https://github.com/user-attachments/assets/702b7788-005a-480b-bbf2-5350a74bba9e)

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 27.53 GB / 31.30 GB
    Container: Yes
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
    pnpm: 9.6.0 - ~/.nvm/versions/node/v20.17.0/bin/pnpm
  Languages:
    Bash: 5.0.17 - /usr/bin/bash
  npmPackages:
    @playwright/experimental-ct-vue: ^1.47.2 => 1.47.2
```

**Comment by yury-s** [comment]
Can you share complete repro, so that we could run it locally?

**Comment by Hai-San** [comment]
> Can you share complete repro, so that we could run it locally?

@yury-s Yes, I Can.

[vue3-playwright.zip](https://github.com/user-attachments/files/17137941/vue3-playwright.zip)
