### ISSUE TITLE
[Feature]: Pause function on Clock API

### ISSUE THREAD

**Issue by edmorrish** [microsoft/playwright#32807]
### 🚀 Feature Request

A `pause` function on the [Clock API](https://playwright.dev/docs/api/class-clock) that freezes the `Date` and all timers without jumping forwards in time.

### Example

For example, when testing that a behaviour occurs exactly 5s after a key event.
  
```
await page.clock.install()
// Carry out some activity that relies on unpaused timers
await page.clock.pause()

await dispatchKeyEvent()

await page.clock.runFor(4999)

await expect(behaviourNotToHaveOccurred)

await page.clock.runFor(1)

await expect(behaviourToHaveOccurred)
```

### Motivation

Currently to pause the Clock API we need to use the `pauseAt` API. This can be cumbersome because we may not be concerned with the exact value of the Date, and want to pause instantly rather than at some point in the future.

**Comment by yury-s** [comment]
Is there a reason you cannot do `await page.clock.pauseAt(new Date())` ?

**Comment by edmorrish** [comment]
I'd thought about doing that but I'd assumed that that would be using the host time, and not the time inside the chrome environment. In some of our tests we've set the system time to a time different to the host time, then done some work without pausing timers, then would like to pause the timers when we've entered a certain part of our app, when we don't know the current system time that's being reported by the clock API `Date` mocks.

e.g. I would expect the following
```
await page.clock.setSystemTime(new Date('1970-01-01T00:00:00'))

// Do some initial work with running timers and elapsing time to get into the correct state of the app

await page.clock.pauseAt(new Date())
```
to jump me to today's date and then pause, which is not necessarily what I'd like, but I don't know how much time has elapsed since I set the system time.

Thanks very much for getting back to me, I'll give it a go and see if it works the way I expect or solved the problem.

**Comment by yury-s** [comment]
> to jump me to today's date and then pause, which is not necessarily what I'd like, but I don't know how much time has elapsed since I set the system time.

You test is in full control of what the time is in the page after it called `setSystemTime`, so you can keep track of it in the test and then call `pauseAt` with the right value.

**Comment by edmorrish** [comment]
Oh interesting, I think I'd misunderstood the difference between `setFixedTime` and `setSystemTime`. Does `setSystemTime` also pause the timers? Or is the suggestion here to do something like:

```
const initialRealTime = new Date()
const initialTestTime = new Date('1970-01-01T00:00:00')
await page.clock.setSystemTime(initialTestTime)

// Do initial work

const elapsedTime = new Date() - initialRealTime
await page.clock.pauseAt(new Date(initialTestTime.getTime() + elapsedTime)) 
```

Trying that out and it does seem to do the trick! But it's a pretty cumbersome way to do it compared to just having a `pause` API. I'm happy to close this request as this way to do it works for our use case, but just for my personal interest, was `pauseAt` chosen over `pause` for any specific reasons? 
Thanks again for your help
