### ISSUE TITLE
[Feature]: Ability to manage test annotations in the reporter

### ISSUE THREAD

**Issue by nukhtarov** [microsoft/playwright#32806]
### 🚀 Feature Request

There is a need to manage tests through the API, for example, to mark a test as skip and to be able to add such an annotation or skip() method in the reporter.

If now in onBegin, onTestBegin add annotation type: 'skip' to the test, it doesn't help. Found it in packages/playwright/src/common/suiteUtils.ts:78, but as I understand it, it will only work if the annotation was originally like that

### Example

```typescript
class MyReporter implements Reporter {
	skippedTests: { title: string, description: string }[] = [];
	skippedTestTitles: string[] = [];

	async onBegin(config: FullConfig, suite: Suite) {
		this.skippedTests = await fetch('https://localhost:8080/skippedTests');
		this.skippedTestTitles = this.skippedTests.map((test) => test.title);
	}

	onTestBegin(test: TestCase, result: TestResult) {
		if (this.skippedTestTitles.includes(test.title)) {
			test.skip()
			// or
			test.skip(skippedTests.find((test) => test.title === test.title)?.description);
			// or
			test.annotations.push({ type: 'skip', description: skippedTests.find((test) => test.title === test.title)?.description });
		}
	}
}

```

### Motivation

This will add the ability to manage tests in a flexible way

**Comment by yury-s** [comment]
Reporter sounds like a wrong place for modifying test execution order and set of running tests. You can use an [auto fixture](https://playwright.dev/docs/test-fixtures#automatic-fixtures) that would run before each test and conditionally mark it as skipped:

```js
import { test as base } from '@playwright/test';

export const test = base.extend<{ maybeSkip: void }>({
  maybeSkip: [async ({}, use, testInfo) => {
    if (shouldSkipTest(testInfo.title))
      testInfo.skip();
    await use();
  }, { auto: true }],
});
```
would this work for you?

**Comment by nukhtarov** [comment]
Yes, it works. Thanks!
