### ISSUE TITLE
[Bug]: Playwright doesn't show the Google Extension plugin when launching the browser after loading the plugin

### ISSUE THREAD

**Issue by rt-zhl** [microsoft/playwright#32800]
### Version

1.47.0

### Steps to reproduce

        String absolutePath = "";
        Playwright playwright = Playwright.create();
        Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions()
                .setArgs(new ArrayList<String>() {{
                    add("--enable-automation");
                    add("--no-sandbox");
                    add("--enable-logging");
                    add("--disable-gpu");
                    add("--start-maximized");
                    add("--disable-blink-features=AutomationControlled");
                    add("--load-extension=" + absolutePath);
                    add("--disable-extensions-except=" + absolutePath);
                }})
                .setHeadless(false)
        );
        BrowserContext browserContext = browser.newContext();
        Page page = browserContext.newPage();

![image](https://github.com/user-attachments/assets/8289b098-7341-4190-9e84-ec4fab9c3c42)

But when I click on the browser ''Open New Window'' (ctrl+n) is when I find that the extension plugin has been loaded. But the newly opened window is not in the browserContext.
![image](https://github.com/user-attachments/assets/2637b52c-9af8-4a28-8ce4-5101fa380a88)

### Expected behavior

![image](https://github.com/user-attachments/assets/ae354af3-e45e-4a2c-8ad0-4a43e256b5a1)

### Actual behavior

via BrowserContext browserContext = browser.newContext(); Page page = browserContext.newPage(); the created browser page will not load the extension plugin and will not take effect

### Environment

```shell
System :windows11
Java: jdk1.8
Playwright:1.47.0
```

**Comment by mxschmitt** [comment]
For extension testing we recommend [launchPersistentContext](https://playwright.dev/java/docs/api/class-browsertype#browser-type-launch-persistent-context) - there extensions are working. You'll get a context back instead of a browser compared to launch. You can pass an empty string as the path and we'll create a user-data-dir for you.
