### ISSUE TITLE
[Bug]: The first cases for each suite have failed when running reusable page structure in POM

### ISSUE THREAD

**Issue by erayyagiz** [microsoft/playwright#32819]
### Version

1.47.2

### Steps to reproduce

https://github.com/erayyagiz/pom-singlepagerunning

You can clone the demo project and reproduce the issue.

### Expected behavior

All test cases should be run for each suite.

### Actual behavior

The first test cases for each suite have failed.
<img width="950" alt="Failed_screenshot" src="https://github.com/user-attachments/assets/fa048bd7-b11a-4112-a64f-75ce5817291d">

### Additional context

Based on our real project requirements, we configured the POM with the reusable page structure. 

In BasePage, we initialize the pages and configure beforeAll and afterAll hooks to open and close the browsers. (I would expect the browser should be open once, then all test cases run, and then the browser closed at the end even if any test case failed). These hooks should work only for once.

In BaseTest, we set beforeEach(to redirect the URL for each test case) and afterEach(to cleanup test data). These hooks should work for each test case.

Apparently, there must be something wrong with this design, please guide me on how to handle this problem.

### Environment

```shell
System:
 OS: Windows 10 Enterprise
 RAM: 32.0 GB
```

**Comment by yury-s** [comment]
This is working as expected because  baseTest.{beforeAll/afterAll} are instantiated only first time you import BasePage.ts in a test file. So beforeAll/afterAll hooks will run before/after all tests in `test1.test.ts` and by the time test2.test.ts runs the page will be closed. To avoid that you can create the context and page in [worker-scoped fixtures](https://playwright.dev/docs/test-fixtures#worker-scoped-fixtures).

```js
import { test as baseTest, BrowserContext, type Page } from "@playwright/test";

import { LoginPage } from "./LoginPage.ts";
import { HomePage } from "./HomePage.ts";

interface PageObjects {
    loginPage: LoginPage;
    homePage: HomePage;
}

interface WorkerFixtures {
    workerContext: BrowserContext;
    workerPage: Page;
}

const test = baseTest.extend<PageObjects, WorkerFixtures>({
    loginPage: async ({ workerPage, workerContext }, use) => {
        await use(new LoginPage(workerPage, workerContext));
    },
    homePage: async ({ workerPage, workerContext }, use) => {
        await use(new HomePage(workerPage, workerContext));
    },
    workerContext: [async ({ browser }, use) => {
        const context = await browser.newContext();
        await use(context);
        await context.close();
    }, { scope: 'worker' }],
    workerPage: [async ({ workerContext }, use) => {
        const page = await workerContext.newPage();
        await use(page);
        await page.close();
    }, { scope: 'worker' }]
});

export default test;
```

Would that work for you?

**Comment by yury-s** [comment]
Closing as we are not planning to change the behavior at the moment and recommend using fixtures instead. See also our docs recommendation for global [beforeEach](https://playwright.dev/docs/test-fixtures#adding-global-beforeeachaftereach-hooks) and global [beforeAll](https://playwright.dev/docs/test-fixtures#adding-global-beforeallafterall-hooks) hooks. You can find more detailed explanation of the behavior in this comment: https://github.com/microsoft/playwright/issues/27058#issuecomment-1718039082

**Comment by erayyagiz** [comment]
Hi @yury-s , thanks for getting back to me. May I ask how to use BaseTest hooks in your design? I need to use **page** in BaseTest after we initialized that in BasePage. Because we are planning to add new before/after steps in time. In my design I was using **export page** in BasePage.

**Comment by yury-s** [comment]
`workerPage` fixture will be available in BaseTest.ts too, so you similarly declare auto fixtures for before each action:

```js
import ui from "../src/pages/BasePage.ts";
import api from "../src/api/BaseApi.ts";

import { mergeTests } from '@playwright/test';

const baseTest = mergeTests(ui, api);

const test = baseTest.extend<{ navigateBeforeEach: void }>({
    navigateBeforeEach: [async ({ workerPage }, use) => {
        await workerPage.goto("https://playwright.dev/");
        await workerPage.waitForLoadState("domcontentloaded");
        await use();
    }, { auto: true }]
});

// export default and name export so spec files can use it 
export default test;
export const expect = test.expect;
```

**Comment by erayyagiz** [comment]
Hi @yury-s , thanks for helping. It worked but I want to ask how to use page objects at the auto fixture worker level.

`import ui from "../src/pages/BasePage.ts";
import api from "../src/api/BaseApi.ts";

import { mergeTests } from '@playwright/test';

const baseTest = mergeTests(ui, api);

const test = baseTest.extend<{ forEachTest: void }, { forEachWorker: void }>({
  forEachTest: [async ({ workerPage }, use) => {
    console.log("beforeEach in BaseTest");
    await workerPage.goto("https://playwright.dev/");
    await workerPage.waitForLoadState("domcontentloaded");
    await use();
    console.log("afterEach in BaseTest");
  }, { auto: true }],
  forEachWorker: [async ({<I WANT TO DECLARE ANY PAGE OR API OBJECT OVER HERE>}, use) => {
    await use();
    valApis.apiTest();  <<<<<<<<<<<<<<<<<<<<<<<<<
    // This code runs after all the tests in the worker process.
    console.log("afterAll in BaseTest");
  }, { scope: 'worker', auto: true }]  // automatically starts for every worker.
});

// export default and name export so spec files can use it 
export default test;
export const expect = test.expect;`
