### ISSUE TITLE
[Bug]: Playwright throws Function not exposed error if another process connects via `connectOverCDP`

### ISSUE THREAD

**Issue by mtsmfm** [microsoft/playwright#32821]
### Version

1.47.2

### Steps to reproduce

1. Clone https://github.com/mtsmfm/playwright-binding-bug
2. npm install
3. node foo.mjs

### Expected behavior

I expect to not see `Error: Function "hello" is not exposed` message on terminal

### Actual behavior

I see `Error: Function "hello" is not exposed` message on terminal

### Additional context

It seems it's neccessary to be connected from another process to reproduce this issue.

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 10.54 GB / 15.54 GB
    Container: Yes
  Binaries:
    Node: 20.17.0 - ~/.local/share/mise/installs/node/20/bin/node
    npm: 10.8.2 - ~/.local/share/mise/installs/node/20/bin/npm
  IDEs:
    VSCode: 1.93.1 - /home/mtsmfm/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/bin/remote-cli/code
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    playwright: ^1.47.2 => 1.47.2
```

**Comment by yury-s** [comment]
`Runtime.bindingCall` CDP event is broadcast to all connections and only one of them is aware of the binding, the other one throws. We can probably ignore unknown bindings instead of throwing.

**Comment by yury-s** [comment]
Discussed this in the meeting. This is out of scope for Playwright which is not designed to work with multiple Playwright sessions connected to the same browser, they will conflict in more places even if we fix it here. Closing as we are not planning to work on this.
