### ISSUE TITLE
[Regression]: Incorrect value in case pass list of objects as args to fixture

### ISSUE THREAD

**Issue by fanrita** [microsoft/playwright#32831]
### Last Good Version

1.44.1

### First Bad Version

1.47.1

### Steps to reproduce

1. Clone https://github.com/fanrita/issue.git
2. npm i
3. npx playwright test --project=chromium -g T-1

### Expected behavior

test should pass

and in fixture arg should be 
e.g. 
 [{username: 'admin1', role: 'admin'}, {username: 'admin2', role: 'moderator'}];

### Actual behavior

test failed

and in fixture arg is {username: 'admin1', role: 'admin'}

### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M1
    Memory: 134.19 MB / 16.00 GB
  Binaries:
    Node: 20.5.1 - ~/Library/Caches/fnm_multishells/29083_1727356474480/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.8.0 - ~/Library/Caches/fnm_multishells/29083_1727356474480/bin/npm
    pnpm: 8.9.0 - ~/Library/Caches/fnm_multishells/29083_1727356474480/bin/pnpm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.47.2 => 1.47.2
```

**Comment by fanrita** [comment]
fixture is
`
import { test as base } from '@playwright/test';

export interface AdminUser {
  username: string;
  role: string;
}

type APITestOptions = {
  adminUsers: AdminUser[] | [];
  createUsersWithRole: AdminUser[];
};

export const test = base.extend<APITestOptions>({
  adminUsers: [],

  createUsersWithRole: async ({ adminUsers }, use) => {
    const createdUsers = [];

    await use(adminUsers);
  },
});

`

test is 

`
import { test } from '../fixtures/testFixture';
import {expect} from "@playwright/test";


test.describe('Args to fixtures', () => {
  const adminUsers= [{username: 'admin1', role: 'admin'}, {username: 'admin2', role: 'moderator'}];

  test.use({adminUsers});
  test('T-1: should pass list of objects', async ({ page, createUsersWithRole }) => {
    expect (createUsersWithRole).toBe(adminUsers);
  });

});`

**Comment by mxschmitt** [comment]
Wrapping the array into an additional array should fix it, see [these docs](https://playwright.dev/docs/test-fixtures#:~:text=Array%20as%20an%20option%20value). We documented it as a potentially breaking change in the [release notes](https://github.com/microsoft/playwright/releases/tag/v1.46.0#:~:text=Possibly%20breaking%20change).

Let us know if it works for you and apologies for the breakage!

Relates https://github.com/microsoft/playwright/issues/32033

**Comment by fanrita** [comment]
@mxschmitt  thanks it works now, Sorry 🙏
