### ISSUE TITLE
[Bug]: Page.screenshot: Timeout 30000ms exceeded

### ISSUE THREAD

**Issue by jolly-xw** [microsoft/playwright#32849]
### Version

1.46.0

### Steps to reproduce

The screenshot() function waits for elements like fonts to load before taking a screenshot. If the elements load too slowly, it can directly cause my screenshot to timeout and fail. I don't want to set it by infinitely increasing the timeout time. Is there a way for me to take a screenshot immediately without waiting for some loading items?

### Expected behavior

Take screenshots without waiting for loading items, capture immediately; or capture screenshots immediately when the timeout is reached, so even if there is an error, I can still get the screenshot.

### Actual behavior

Page.screenshot: Timeout 30000ms exceeded

### Environment

```Text
- Operating System: [Ubuntu 22.04]
- CPU: [intel]
- Browser: [Chromium]
- Python Version: [3.11]
- Other info:
```

**Comment by yury-s** [comment]
Please share a reproduction that we could run locally to see and debug the issue.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
