### ISSUE TITLE
[internal]: screenshot instead of snapshot polishing

### ISSUE THREAD

**Issue by Skn0tt** [microsoft/playwright#32847]
Before we ship "screenshot instead of snapshot", let's smooth out the rough edges.

- [ ] attempt to select text causes image drag-n-drop - https://github.com/microsoft/playwright/pull/33089
- [ ] click target is misplaced
- [ ] discoverability: add a hint inside canvas in DOM snapshot - https://github.com/microsoft/playwright/pull/33092
- [x] #33115

**Comment by mxschmitt** [comment]
FYI, reverted patches:

- https://github.com/microsoft/playwright/pull/32905
- https://github.com/microsoft/playwright/pull/32832

**Comment by Skn0tt** [comment]
I've opened three PRs for this, and broke the fourth item out into its own exploration subissue.
