### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by zhanglijie123** [microsoft/playwright#32848]
### Version

1.44.0

### Steps to reproduce

following is my example,but page not action or happen exception of 'Element is outside of the viewport' when click next page-button. （remark:please use china-area proxy)

 public static void main(String[] args) {
        List<String> arg = ListUtil.toList(
                "--disable-blink-features=AutomationControlled"

        );
        try (Playwright playwright = Playwright.create();

             Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions()
                     .setHeadless(false).setArgs(arg))
        ) {

            BrowserContext context = browser.newContext();

            Page page = context.newPage();
            page.navigate("https://www.yhfund.com.cn/main/annuity/pensionprod/baqrgg/index.shtml");
            Locator locator = page.locator("xpath=" + "//*[@id="next_page"]").first();
            Locator.ClickOptions clickOptions = new Locator.ClickOptions();
            clickOptions.setButton(MouseButton.LEFT);
            clickOptions.setClickCount(1);
            clickOptions.setTimeout(10000);
            clickOptions.setForce(true);
            locator.click(clickOptions);

            Thread.sleep(10000000);

        } catch (InterruptedException e) {
            e.printStackTrace();
        }

### Expected behavior

expect to next page(page 2)
![2](https://github.com/user-attachments/assets/c0e49a13-3a6f-470e-86ef-855395893bab)

### Actual behavior

No response, still on the homepage。
![image](https://github.com/user-attachments/assets/91183b4b-52ed-4734-ba9a-5de0b91f1294)
![Uploading 1.png…]()

### Environment

```shell
System:
  os:win10
  playwright-version:1.44.0
```

**Comment by yury-s** [comment]
Looks like some bot protection kicks in on the server, I'm getting 'Failed to load resource: the server responded with a status of 521 ()' when running this code. Try recording a trace to debug what's going on. If you think this is a bug in playwright, please file a new issue and attach a self-contained reproduction that wouldn't depend on the behavior of third-party servers.

**Comment by zhanglijie123** [comment]
ok,thanks for your reply
