### ISSUE TITLE
[Bug]: generateLocator depends on timing to not produce locators that violate strict mode

### ISSUE THREAD

**Issue by RunOrVeith** [microsoft/playwright#32852]
### Version

1.47.2

### Steps to reproduce

minimal reproducer: https://github.com/RunOrVeith/tsxPlaywrightBug/blob/main/bug-locator-generation.ts

Instructions:
1. `git clone git@github.com:RunOrVeith/tsxPlaywrightBug.git`
2. `cd tsxPlaywrightBug`
3. `npm i`
4. `PWDEBUG=console npx tsx bug-locator-generation.ts ` or open the reproducer in vscode, there is a launch file that starts it

### Expected behavior

I would expect the locator generation to produce a locator that does not violate strict mode in both cases, not depending on whether one button or not is not displayed.

### Actual behavior

depending on whether one of the buttons has `display: none`, we get a locator that matches both buttons or only one of them.

### Additional context

This creates an issue with the following flow (we use playwright to generate test cases with AI for an arbitrary page at octomind):

0. There is a page that has a 2 buttons that look the same to playwright. One of them gets a style `display: none` set after a small amount of compute time / loading. It does not have this style from the beginning. We do not control the code of this page.
1. We find a locator to click the button and save that locator. Because this is a slow-ish process, we always get the case where the style has already loaded, so in this case `getByRole("button", {name: "Agree to all"})` 
2. Later, we want to run a test using this locator. We open the page and now do `await page.getByRole("button", {name: "Agree to all"}).click()`. If the style of the invisible button has not yet loaded when this is first called, we  get a strict mode violation error in a flaky way depending on load times.

If you can not reproduce it with my script, set the timeout a bit higher than 50ms in line 77.

I am not sure whether this is intended behavior or not, but it feels wrong and I could also not find any documentation for the behavior that elements that are not displayed are not taken into consideration for locator.ACTION (like click, fill etc.) and generateLocator (although I am aware that generateLocator is officially only available with `PWDEBUG=console`).
In fact, I only found [this](https://playwright.dev/docs/locators#matching-only-visible-elements) documentation, that point more into the direction that you actively need to enable a visibility check instead.

So I would like to achieve the following:
1. Get an option to not ignore invisible elements when generating a locator
2. Improve the documentation

If 1. is not an option, I guess I will have to retry any strict mode violations. 

### Environment

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i9-13900H
    Memory: 48.09 GB / 62.44 GB
    Container: Yes
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    npm: 10.8.1 - ~/.nvm/versions/node/v20.14.0/bin/npm
    pnpm: 9.4.0 - ~/.nvm/versions/node/v20.14.0/bin/pnpm
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    playwright: ^1.47.2 => 1.47.2
```

**Comment by yury-s** [comment]
The locator generator acts based on the current state of the page, it doesn't know if one of currently invisible elements will become visible or a new element matching same locator is going to be added by javascript later (or the order of elements may change etc.). If you know that the locator is not going to be unique, you can call the generator when the page is in appropriate state or you can always alternate the result to be more resilient to changes in the page.

Closing this issue as not planned.

**Comment by RunOrVeith** [comment]
I understand that it's not planned to address the timing issues on your side, but I would like to at least get some documentation about the fact that all locators ignore invisible elements completely.

To me it is also surprising that the following page

```HTML
<div>
    <button
        name="senddata"
        style="display: none;"
        >
        <span>Agree to all</span>
    </button>
    <button
        name="senddata"
    >
        <span>Agree to all</span>
    </button>
</div>
```

with this locator call `page.getByRole('button', { name: 'Agree to all' }).click()` does **not** raise a strict mode violation.
Especially since there is a [special section in the documentation ](https://playwright.dev/docs/locators#matching-only-visible-elements) that is telling you exactly the opposite should be the case. This seems very inconsistent to me.
