### ISSUE TITLE
[Bug]: Some web elements are not displayed when using viewport parameters

### ISSUE THREAD

**Issue by chintalJN** [microsoft/playwright#32856]
### Version

1.46.1

### Steps to reproduce

1.  Open website https://app.jobnimbus.com manually
2. Check chatbox icon on bottom right corner
3. Open same website using playwright trace viewer/ browser
4. Check chatbox icon

### Expected behavior

Chatbox icon should be visible

### Actual behavior

Chatbox icon is not visible

### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 64.64 MB / 36.00 GB
  Binaries:
    Node: 20.15.1 - /usr/local/bin/node
    npm: 10.7.0 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.46.1 => 1.46.1 

chintal@Chintals-MacBook-Pro lionAutomation % npx envinfo --preset playwright

  System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 87.58 MB / 36.00 GB
  Binaries:
    Node: 20.15.1 - /usr/local/bin/node
    npm: 10.7.0 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.46.1 => 1.46.1
```

**Comment by yury-s** [comment]
I cannot reproduce it with the following test, looks like the web site may add it with a delay or not add at all at its discretion. Can also be that some bot protection kicks-in. If you think this is a playwright bug, can you share a self-contained repro that we could run locally?

```js
import { expect, test } from "@playwright/test";

test("Test", async ({ page }) => {
  await page.goto('https://app.jobnimbus.com');
  await new Promise(() => {})
});
```

**Comment by chintalJN** [comment]
Here is the self-contained repo:  https://github.com/chintalJN/my-playwright-project
The settings I am using are : 
{
      name: 'Google Chrome',
      use: { ...devices['Desktop Chrome'], channel: 'chrome',
        viewport: { width: 1920, height: 1080 }, 
      },
    },

**Comment by yury-s** [comment]
The test is passing for me locally:
![image](https://github.com/user-attachments/assets/3f3c78c0-4c87-481a-8f36-7b2785a33440)

Like I said there maybe a race condition (in which case waiting for the element to show up might help) or site behavior changes depending on whether the client browser is controlled by automation or some other condition. To rule out those scenarios and have reliable repro, I asked for a self-contained example, i.e. the one that includes the web app too rather than goes to a page in the internet. Could you provide that? Otherwise we can't seem to reproduce it.

**Comment by chintalJN** [comment]
I am sharing the local recording here: https://share.zight.com/bLuvq2n4
I am sure the issue is not about racing condition. This does not happen with Selenium when I set viewport: { width: 1920, height: 1080 } for the test browser. I am QA Engineer at JobNimbus and testing the website in the example. The issue does not happen when I  have launchOptions: {
          args: ["--start-maximized"]
        } in playwright.config.ts

**Comment by yury-s** [comment]
Try recording a [trace](https://playwright.dev/docs/trace-viewer-intro#recording-a-trace) to debug why it's not showing up. I trust you that it may be reproducible in you environment, but we need to be able to repeat it locally to see the bug and so far the following test passes 10 times out of 10:

```js
import { test, expect } from '@playwright/test';

test('get started', async ({ page }) => {
  await page.goto('https://app.jobnimbus.com');
  await (expect(page.locator(`[data-test-id='chat-widget-iframe']`)).toBeVisible());
  await page.screenshot({ path: `screenshot.png` });
});
```

**Comment by Skn0tt** [comment]
I'll go ahead and close this for housekeeping purposes. If you come up with a trace or (even better) a repro, feel free to open another issue!
