### ISSUE TITLE
[Bug]: Test timeout - 'AfterEach' hook time isn't included in the test timeout.

### ISSUE THREAD

**Issue by Nck1969** [microsoft/playwright#32851]
### Version

latest

### Steps to reproduce

I try reproduce bug in the code sandbox:
https://codesandbox.io/p/devbox/timeout-bug-mfknwz

### Expected behavior

Test is failed cause: beforeEach time + test time + afterEach time is more that I set (800 + 9_000 + 9_900 > 10_000)

### Actual behavior

Test is passed

### Additional context

Doc:
<img width="975" alt="image" src="https://github.com/user-attachments/assets/158fd4fb-a103-425d-9e3b-d82dd89d2f7b">

### Environment

```shell
System:
    OS: macOS 15.0
    Memory: 1.83 GB / 64.00 GB
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    Yarn: 4.1.1 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
  Languages:
    Bash: 5.2.37 - /opt/homebrew/bin/bash
```

**Comment by yury-s** [comment]
Can reproduce it with the following snippet:

```js
import { expect, test } from "@playwright/test";

test.setTimeout(2_000);

test.describe("Timeout test", () => {
  test.beforeEach(async ({page}, testInfo) => {
    console.log(testInfo.timeout);
  });

  test.afterEach(async ({page}) => {
    await page.waitForTimeout(3_000);
  });

  test("someTest", async ({page}) => {
  });
});

```
