### ISSUE TITLE
[Docs]: Getting started - VS Code

### ISSUE THREAD

**Issue by mattias-m-andersson** [microsoft/playwright#32861]
### Page(s)

- [Getting started - VS Code](https://playwright.dev/docs/getting-started-vscode)

### The problem
On the page [getting started vscode](https://playwright.dev/docs/getting-started-vscode) the "getting started" is brought to an immediate halt on "Install Playwright" with the following error message in VS Code Terminal.

`PS C:\Dev\Playwright> npm init playwright@latest --yes -- --quiet --browser=chromium --browser=firefox --browser=webkit --gha
npm: The term 'npm' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

Nowhere is it mentioned the need for the package manager NPM, or how to install it.

### How I got into it...
After listening to [this](https://open.spotify.com/episode/0RJIFMnIsuV228NgGmQoKN?si=d644b32a4997425b) episode of podcast .NET Rocks, where it is mentioned that "... give it 7 minutes and try it out", I was so exited to get started.

### Description

Clearly state the dependencies and guide me through the process of getting there.
Also how to trouble shoot common errors would be nice.

**Comment by vladkrasn** [comment]
Npm is a Node.js thing.
For .NET, see this https://playwright.dev/dotnet/docs/intro

**Comment by Skn0tt** [comment]
Right, the VS Code Extension is only meant for usage with Node.js Playwright. I'll see what we can do to make this more clear.

**Comment by mattias-m-andersson** [comment]
> Npm is a Node.js thing. <img alt="image" width="1036" src="https://private-user-images.githubusercontent.com/28753668/371760133-8b47a2c8-171d-4f3c-81c6-f1054355a37a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NzYxNjQsIm5iZiI6MTcyNzY3NTg2NCwicGF0aCI6Ii8yODc1MzY2OC8zNzE3NjAxMzMtOGI0N2EyYzgtMTcxZC00ZjNjLTgxYzYtZjEwNTQzNTVhMzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDA1NTc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMWNjMjE3ZWE3N2U2NGY5YjI0NjgyNDg1YmRmODcxMzM3YmNiZTBiYTZmNGFmYWY3ZmQ2MTE4OTY0ZTVhMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.u3LYQQHuEdSuyKY5mzUIJp8p1RhRXCgWKOYGfObnZ90">
> 
> For .NET, see this https://playwright.dev/dotnet/docs/intro

Since I am more comfortable in C# anyways I will give the .NET getting started guide a go.

**Comment by Skn0tt** [comment]
We've also added a paragraph to the VS Code guide pointing out that it's for Node.js. Hope that helps future visitors!
