### ISSUE TITLE
[Docs]: Adding Theatron to third-party reporter showcase

### ISSUE THREAD

**Issue by GhadimiR** [microsoft/playwright#32866]
### Page(s)

https://github.com/microsoft/playwright/blob/main/docs/src/test-reporters-js.md

### Description

I have created a service for storing Playwright results and attachments, it has a reporter available from NPM that I would like to add to the third-party reporter showcase in the Playwright docs.

**Comment by Skn0tt** [comment]
Closing as per https://github.com/microsoft/playwright/pull/32867#issuecomment-2385673229.
