### ISSUE TITLE
[Bug]: Playwright ui is not showing any tests

### ISSUE THREAD

**Issue by andradabuzatu** [microsoft/playwright#32874]
### Version

1.47.2

### Steps to reproduce

1. Open the terminal in Visual Studio Code.
2. Run the command below:
npx playwright test --ui

### Expected behavior

Tests result should show in the Playwright ui.

### Actual behavior

Playwright ui is not showing any tests.
![image](https://github.com/user-attachments/assets/909cc847-b3a6-45a4-a6c3-aa5015e32fa8)

### Environment

```shell
System:

    OS: Windows 10 enterprise

    Memory: 16GB

  Binaries:

    Node: 20.17.0

    npm: 10.8.3
```

**Comment by the-ult** [comment]
https://github.com/microsoft/playwright/issues/32103#issuecomment-2383031111 might be related

**Comment by Skn0tt** [comment]
Hi! Please follow the bug report template and provide a minimal reproduction case.

**Comment by andradabuzatu** [comment]
Steps to reproduce
 
Using all default Settings in in playwright.config.ts
 
Start Playwright UI Mode with playwright test --ui
 
Wait 2 minutes
 
Expected Behaviour:
Tests show up in the UI and can be run
 
Actual Results:
No tests load in the UI
In VSC, we can observe the following error:
![image](https://github.com/user-attachments/assets/3829b1ab-6a6e-4fa0-b5f1-8a4530aad197)

 
Testing setup:
 
System:
OS: Windows 10 enterprise
Memory: 16GB
Binaries:
 Node: 20.17.0
 npm: 10.8.3
 Playwright version : 1.47.2

**Comment by Skn0tt** [comment]
Sorry, that's not enough information for me to reproduce what you're seeing. Could you start a new playwright project (see https://playwright.dev/docs/intro#installing-playwright), make the minimum changes necessary to get to the bug you're seeing, and send me a ZIP or Github link of the project?

**Comment by oceaan-pendharkar-razr** [comment]
Something similar happened to me and I was able to resolve it by clicking the "all" of Projects: all, after which the option to select my folders with the tests within appeared.
