### ISSUE TITLE
Equivalent of Puppeteer page.evaluateOnNewDocument(pageFunction[, ...args])

### ISSUE THREAD

**Issue by seongsikk** [microsoft/playwright#3288]
Is there already an equivalent of `page.evaluateOnNewDocument(pageFunction[, ...args]) from Puppeteer. Seems like this would be very useful.

**Comment by mxschmitt** [comment]
In Playwright we call it "addInitScript": https://playwright.dev/#path=docs%2Fapi.md&q=pageaddinitscriptscript-arg

**Comment by seongsikk** [comment]
Got it, thank you!
