### ISSUE TITLE
[Feature]: Add Official Playwright Logo SVG to Project Assets

### ISSUE THREAD

**Issue by UzaeirAzhar** [microsoft/playwright#32888]
### 🚀 Feature Request

I’m requesting the addition of an official Playwright logo in SVG format to the project assets. This would allow the community to use the logo in badges, documentation, articles, and third-party tools, ensuring consistency and brand recognition.

Currently, there isn’t an official SVG logo available for Playwright, which makes it difficult to create high-quality assets such as badges (like those on GitHub or for third-party tools). By providing an official SVG, the Playwright brand will be better represented across the web.

I’ve created a reference version of the Playwright SVG [here](https://gist.github.com/UzaeirAzhar/a03851c32cfb9edbbb7fb55a318c3bd8), but it would be great to have an official one directly from the team.

I kindly request that you review the provided SVG logo. If it meets your standards, it would be fantastic if you could:

- Host the logo on an official branding or press kit page within the Playwright repository, or
- Provide an alternative source URL that Simple Icons or 3rd Party tools can reference when adding Playwright to their collection.

### Example

Here’s an example of how an SVG logo can be used:

- GitHub ReadMe badges (e.g. ![cypress](https://img.shields.io/badge/-cypress-%23E5E5E5?style=for-the-badge&logo=cypress&logoColor=058a5e))
- In Simple Icons for generating badges with Playwright's logo.
- Playwright documentation, articles, blog posts, and other online resources.

Having an official logo ensures consistency in branding and helps community members represent Playwright correctly in their projects and tools.

### Motivation

This request stems from the need for a consistent and official Playwright logo in various community-driven assets, such as badges, documentation, and third-party integrations.

An SVG logo would allow for high-quality visuals at any scale, improving the Playwright ecosystem by providing a standardized logo for tools like [shields.io](https://shields.io/) and [Simple Icons](https://simpleicons.org/), where other popular frameworks and libraries already have their logos.

Once the official SVG is available, I will submit a PR to [Simple Icons](https://simpleicons.org/) to add the Playwright logo, making it easier for the community to generate badges and other assets with the logo.

Thank you for considering this request!

**Comment by Skn0tt** [comment]
Hey Uzair! You're free to use the SVG logo from the https://playwright.dev website. You can also find the file here: https://github.com/microsoft/playwright.dev/blob/main/static/img/playwright-logo.svg

Let me know if that helps!

**Comment by UzaeirAzhar** [comment]
thanks @Skn0tt

**Comment by UzaeirAzhar** [comment]
It seems that simple icons received notification from Microsoft's legal team regarding the inclusion of their brands/products. The only brands/products simple-icons can include without any edits are:

Power Platform
Dynamics 365
Microsoft 365
Azure

@all so thats why playwright logo can't be used in simple-icons or any third party tools
