### ISSUE TITLE
[Bug]: Unable to Locate SVG(Scalable Vector Graphics) Icon Element

### ISSUE THREAD

**Issue by ManthanTagad** [microsoft/playwright#32887]
### Version

1.32.0

### Steps to reproduce

It's confidential, so I can't provide a repository. However, I can explain the issue. I am working on an automation suite for a front-end UI using Playwright with Java. In that automation, I am unable to locate an HTML element, specifically an 'svg'. I'm encountering an error that says, "Error: Node is not an HTMLElement."

Attaching screenshot which illustrating the issue:
![Issue](https://github.com/user-attachments/assets/82d8c901-4749-435a-928f-d00a49ac375d)

### Expected behavior

When attempting to locate the 'svg' HTML element using Playwright, the automation should successfully identify the element and allow to interact with it (e.g., click, hover, or retrieve its properties).

### Actual behavior

The automation encounters an error message: "Error: Node is not an HTMLElement," indicating that the 'svg' element is not being recognized as a valid HTML element by the Playwright.

### Environment

- Operating System: [Fedora 39]
-  Browser: [All]
-  Java Version: [22.0.2]
-  Maven Version: [Apache maven 3.9.1]

**Comment by mxschmitt** [comment]
Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!

We recommend also running Playwright on the latest available version and on [supported systems](https://playwright.dev/java/docs/intro#system-requirements).
