### ISSUE TITLE
[Bug]: cdpsession.on() seems not work.

### ISSUE THREAD

**Issue by xiahan4956** [microsoft/playwright#32890]
### Version

playwright-1.47.0

### Steps to reproduce

there is  the official quick start:

    client = page.context.new_cdp_session(page)
    client.send("Animation.enable")
    client.on("Animation.animationCreated", lambda: print("animation created!"))
    response = client.send("Animation.getPlaybackRate")
    print("playback rate is " + str(response["playbackRate"]))
    client.send("Animation.setPlaybackRate", {
        "playbackRate": response["playbackRate"] / 2
    })

When I run these code. I still not see the result of lambda: print("animation created!")
this is my browser browser = playwright.chromium.launch(headless=False)
I expect I should see it.
![image](https://github.com/user-attachments/assets/9b832c61-ff13-4352-8fdb-41556dde9348)

### Expected behavior

I expect to see "animation created!"

### Actual behavior

 "animation created!" not show

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 7.17 GB / 31.84 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - ~\node_modules\.bin\npm.CMD
  IDEs:
    VSCode: 1.93.0 - C:\Users\xiahan\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
```

**Comment by Skn0tt** [comment]
It doesn't look like your page is navigated to any website. It needs to be a site with CSS Animations, otherwise there won't be any `animationCreated` events.

**Comment by xiahan4956** [comment]
![image](https://github.com/user-attachments/assets/e4590d4a-89b2-4409-a980-84cf094a0d11)
I add page.goto().
But there was still not  "animation created!"

**Comment by xiahan4956** [comment]
> It doesn't look like your page is navigated to any website. It needs to be a site with CSS Animations, otherwise there won't be any `animationCreated` events.
![image](https://github.com/user-attachments/assets/e4590d4a-89b2-4409-a980-84cf094a0d11)
I add page.goto().
But there was still not  "animation created!"

**Comment by Skn0tt** [comment]
Baidu.com doesn't have any CSS Animations. You can see that the "Animations" Tab of Chrome Developer Tools is empty:
<img width="1597" alt="Screenshot 2024-10-01 at 10 09 38" src="https://github.com/user-attachments/assets/4df0ee60-9d0c-419d-aeba-4c1a93a6d396">


Try visiting https://scroll-driven-animations.style/ instead.

**Comment by xiahan4956** [comment]
Thanks your advice. It is so strange. 
 "animation created!" would show when I go to  "https://scroll-driven-animations.style/" **secondly**
I have tested many websites. The result were same.

I expect cllient.on() should drectly shows result.
The fact  I need to use  page.goto() twice. 

![image](https://github.com/user-attachments/assets/f3db886c-98ac-49be-9770-5a09c776336f)
![image](https://github.com/user-attachments/assets/9d50125a-1f7e-4c60-a832-8728fc0eafe0)

**Comment by Skn0tt** [comment]
> I expect cllient.on() should drectly shows result.

`client.on` registers a listener for the `Animation.animationCreated` event. It will only show the result once that event happens, so that won't happen directly.

> "animation created!" would show when I go to "https://scroll-driven-animations.style/" secondly

Try removing the first `page.goto`, it should still work. I suspect that it's important that `Animation.enable` is executed before the page is opened.

**Comment by Skn0tt** [comment]
Sounds like your problems are alleviated then. I'll go ahead and close the issue :)

**Comment by xiahan4956** [comment]
You are right. It works.
