### ISSUE TITLE
[Bug]: Unable to turn off GeoLocation or block a given website from accessing the GeoLocation feature.

### ISSUE THREAD

**Issue by garry-edmonds** [microsoft/playwright#32891]
### Version

1.47.0

### Steps to reproduce

See discord thread:

https://discord.com/channels/807756831384403968/1242830844641677446/threads/1288148746189668447

Not able to disable GeoLocation on C#, also not able to click Block on the GeoLocation popup window.

### Expected behavior

Need ability to click the popup block button, or a do not grant access feature

### Actual behavior

GeoLocation still finds the browser location.

### Environment

```Text
C# 2022
Windows 11.

In development environment currently.
```

**Comment by mxschmitt** [comment]
Looks similar to https://github.com/microsoft/playwright/issues/18964 - we recommend specifying `'--deny-permission-prompts'` as an arg when you launch the browser. Are you using the library or Microsoft.Playwright.{NUnit,MSTest}? There you need to put it into the runsettings file.

**Comment by garry-edmonds** [comment]
Ok, found that instead of using the run settings as suggested, I've done it like this.

var browser = await Playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions { Headless = true, Args = new List<string>{ "--deny-permission-prompts" }  });

Thanks @mxschmitt for the pointer.
