### ISSUE TITLE
[Feature]: specify junit test properties by env variable

### ISSUE THREAD

**Issue by udarrr** [microsoft/playwright#32918]
### 🚀 Feature Request

There is only one way to set up properties for junit report in annotation it should be done for each suite/test separately but also make sense to set up it globally for all tests cases by env variable

### Example

process.env.PLAYWRIGHT_JUNIT_PROPERTIES = "dd_tags[arh]=x64,platfrom=beta"

then in junit xml it'll be added as usual to each run's test cases additionally to were set in test annotation

implementation here
https://github.com/microsoft/playwright/pull/32886

### Motivation

make it easy to setup and maintain for all test cases if needed

**Comment by mxschmitt** [comment]
In your proposed PR you add the annotations on the test level. You could archive this already today with an ['auto fixture'](https://playwright.dev/docs/test-fixtures#automatic-fixtures) which gets executed for every test.

```ts
// baseTest.ts
import { test as base } from '@playwright/test';

export const test = base.extend<{ addCustomTestAnnotations: void }>({
  addCustomTestAnnotations: [async ({}, use) => {
    test.info().annotations.push({ type: 'foo', description: 'bar' });
    await use();
  }, { auto: true }],
});
export { expect } from '@playwright/test';
```

```ts
// foo.spec.ts
import { test } from './baseTest';

test('should do ...', async ({ page }) => {
  // Test code here
});
```

would that work for you? It would generate the same junit xml file. If you want to control it via environment variables you could do:

```ts
// baseTest.ts
import { test as base } from '@playwright/test';

export const test = base.extend<{ addCustomTestAnnotations: void }>({
  addCustomTestAnnotations: [async ({}, use) => {
    test.info().annotations.push({ type: 'hostOS', description: process.env.HOST_OS });
    await use();
  }, { auto: true }],
});
export { expect } from '@playwright/test';
```

**Comment by udarrr** [comment]
> In your proposed PR you add the annotations on the test level. You could archive this already today with an ['auto fixture'](https://playwright.dev/docs/test-fixtures#automatic-fixtures) which gets executed for every test.
> 
> // baseTest.ts
> import { test as base } from '@playwright/test';
> 
> export const test = base.extend<{ addCustomTestAnnotations: void }>({
>   addCustomTestAnnotations: [async ({}, use) => {
>     test.info().annotations.push({ type: 'foo', description: 'bar' });
>     await use();
>   }, { auto: true }],
> });
> export { expect } from '@playwright/test';
> // foo.spec.ts
> import { test } from './baseTest';
> 
> test('should do ...', async ({ page }) => {
>   // Test code here
> });
> would that work for you? It would generate the same junit xml file. If you want to control it via environment variables you could do:
> 
> // baseTest.ts
> import { test as base } from '@playwright/test';
> 
> export const test = base.extend<{ addCustomTestAnnotations: void }>({
>   addCustomTestAnnotations: [async ({}, use) => {
>     test.info().annotations.push({ type: 'hostOS', description: process.env.HOST_OS });
>     await use();
>   }, { auto: true }],
> });
> export { expect } from '@playwright/test';

Hi @mxschmitt oh yes that's exactly what's needed Thanks for the great example!
