### ISSUE TITLE
[internal] line highlights in docs are broken

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#32921]
Source: https://github.com/microsoft/playwright/blob/b01dd556975d2b41efcb71c482d996cf258eb190/docs/src/ci.md?plain=1#L418

Code pointers:

- https://github.com/microsoft/playwright/blob/3b86a9c0e44314aee07d71d50449545329466774/utils/markdown.js#L167
- https://github.com/microsoft/playwright/blob/3b86a9c0e44314aee07d71d50449545329466774/utils/markdown.js#L329

Grepping for `\{\d+-\d+\}` reveals only one usage - maybe we just remove it?

**Comment by Skn0tt** [comment]
Let's make sure this gets fixed, this could be useful in the future.
