### ISSUE TITLE
[Feature]: Dynamic tags in runtime

### ISSUE THREAD

**Issue by JanLechvar** [microsoft/playwright#32925]
### 🚀 Feature Request

Implementation of Dynamic tags in runtime.
Allow users to push tags to the reporter when a condition described in the test is met.

### Example

  if (errorLogs.length > 0) {
   testInfo.annotations.push({
      type: "WARNING - Console Errors detected",
      description: "Check for console errors in the test",
    });
      testInfo.tags.push("@console-error");
  }

### Motivation

Imagine a test suite with over 100 tests. 
In each test, user wants to check if any errors appear in the browser console during the test execution without affecting the test results. If an error occurs in any test, user pushes this error, say in the form of an annotation, to the Playwright reporter.

The person reviewing the report after all tests have been executed has to expand each test result individually to see if a console error occurred during that specific test.

Dynamic tags in runtime would solve this problem, and the person reviewing the report wouldn’t have to open each test result because tests with console errors would be tagged.

This would save time and make the report more organized, as it would be immediately clear which tests to review for console errors thanks to the runtime tags.

**Comment by Skn0tt** [comment]
Dynamic tags wouldn't work with `--grep "@tag"`, so I think that'd add undue confusion. As you explain, it's already possible to dynamically push an annotation. Reporters are free to display these annotations however they like. If you're using the HTML reporter, we could look into making annotations searchable. What reporter are you using?

**Comment by JanLechvar** [comment]
Correct, such a tag wouldn't work with the --grep "@tag",
but I have couple of ideas, ordered according to my personal preferences:

1. Besides annotations and tags, introduce a third method, such as Note/Sticker/Badge which will behave similarly to tags in terms of display in the report but can be added dynamically to the report.

2. Annotation ‘Type’ can be displayed similarly to a tag (ideally, user can choose which type/annotation to display like a tag). For example:
{
    "annotation": {
        "type": "This-is-annotation-type",
        "description": "This is description",
        "displayTypeAsTag": true,
    }
}

![001 2024-10-02 15 24 47](https://github.com/user-attachments/assets/adbccc29-6e99-4f14-a4f7-310c2cc081e4)

3. Introduction of a filter for annotations, as you mentioned.

I am using the HTML reporter.

**Comment by Skn0tt** [comment]
> Introduction of a filter for annotations, as you mentioned.

I've looked at the source code, and it turns out we already have annotation filters! Couldn't find docs for it, though. Until we add docs, you can filter for annotation existence with the `annot:this-is-annotation-type` filter. If you also want to filter for the annotation description, use `annot:type=description`. I'm adding another test to our codebase in https://github.com/microsoft/playwright/pull/32931, so we can ensure it stays this way!

**Comment by JanLechvar** [comment]
Thank you, this is a very helpful workaround. 

Are you considering implementing some of the features I mentioned earlier? It would be beneficial and more user friendly to be able to use dynamic notes, badges, or annotations in the form of tag-like elements.

Regarding the search for annotations functionality, I encountered some issues:

1. When the annotation type contains more than one word, let’s say “This is annotation type,” “annot:This is annotation type” won’t filter results with this annotation. The same applies to the description. I have to use only one word from that string to properly filter the desired test result. Are annotations supposed to be one word only?

2. There is a formatting issue when I use /n for a new line. It is not accepted by either the type or description, and annotations in the result look glued to one another. It would be great to allow /n so the annotation can be formatted as the user desires.

![001 2024-10-04 08 39 42](https://github.com/user-attachments/assets/318e1e11-c679-44cd-872a-1a465fe43729)

expected result:
![001 2024-10-04 08 41 55](https://github.com/user-attachments/assets/f8e12eaa-bdbc-47ef-97d3-1af17ad88f42)

actual result:
![001 2024-10-04 08 41 26](https://github.com/user-attachments/assets/ac6bcdc2-dc70-4f9d-b1fc-d7dbf00c6bb7)

**Comment by Skn0tt** [comment]
I've opened a PR to fix the newline rendering. For filtering tags with whitespaces, try wrapping your search term in quotes: `annot:"WARNING - Console errors detected"`.

With these two combined, are you able to solve your usecase using annotations?

**Comment by JanLechvar** [comment]
I tested it using quotes and it's working, thank you.

Your understanding is correct, but since you asked, having some basic custom style options for annotation type and description would be beneficial for better organization. Options like text color, font style, and font size would be especially useful, particularly the color.

**Comment by Skn0tt** [comment]
> having some basic custom style options for annotation type and description would be beneficial for better organization

That's fair. I'll go ahead and close this feature request. Please open another one for annotation styling!
