### ISSUE TITLE
[Bug]: Sharding not working as expected

### ISSUE THREAD

**Issue by maxuai** [microsoft/playwright#32922]
### Version

1.47.2

### Steps to reproduce

1. clone my repo at https://github.com/maxuai/playwright-sharding
2. trigger a new workflow run or check out my latest workflow run at https://github.com/maxuai/playwright-sharding/actions/runs/11142293754 

### Expected behavior

- the first shard runs all tests from `shard1.spec.ts` file
- the second shard runs all tests from `shard2.spec.ts` file

### Actual behavior

- the first shard runs all tests
- the second shard runs no tests

### Additional context

This only happens when the number of tests in one file is different than in the other one.

### Environment

```shell
System:
    OS: Linux 6.8 Linux Mint 21.2 (Victoria)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1270P
    Memory: 31.72 GB / 46.76 GB
    Container: Yes
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 10.8.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
  IDEs:
    VSCode: 1.93.1 - /snap/bin/code
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.47.2 => 1.47.2
```

**Comment by Skn0tt** [comment]
Hi! Thanks for the repro. It's about three tests, which I don't think is a good example for sharding. Were you also able to observe this with more tests? If yes, could you update the repro to show that it also happens with more?

**Comment by maxuai** [comment]
@Skn0tt Sure, I've added some more tests and now there 5 files which and 5 shards but the tests only get executed in 3 shards and 2 don't run any tests (running the 13 tests in 3 workers). [WF run](https://github.com/maxuai/playwright-sharding/actions/runs/11149088590)
What confuses me even more is when I run the same tests but using the `workers` parallelism option it works as expected. Meaning each worker running all the tests of a single file. [WF run](https://github.com/maxuai/playwright-sharding/actions/runs/11149088609)

**Comment by mxschmitt** [comment]
I see that you don't set `fullyParallel: true` in your config which we [recommend](https://playwright.dev/docs/test-parallel#parallelize-tests-in-a-single-file) - are you doing this intentionally?

**Comment by maxuai** [comment]
@mxschmitt I added the `fullyParallel: true` option now as well, but it doesn't fix the issue. Now one file get's executed twice (see this [run](https://github.com/maxuai/playwright-sharding/actions/runs/11174840589). In our real world project this wouldn't also be an option as the test inside each file cannot be run in parallel. Also from the documentation it doesn't read like a mandatory option to make sharding work:

> By default, tests in a single file are run in order. If you have many independent tests in a single file, you might want to run them in parallel with [test.describe.configure()](https://playwright.dev/docs/api/class-test#test-describe-configure).

**Comment by Skn0tt** [comment]
> Sure, I've added some more tests and now there are 5 files and 5 shards but the tests only get executed in 3 shards and 2 don't run any tests (running the 13 tests in 3 workers).

Thanks for updating! 5 files, 5 shards and 13 tests still isn't the kind of size we optimise our sharding for. At that amount of tests, execution speed won't really suffer no matter wether 3 or 5 shards are utilised.
Can you also repro this for 5 files, 5 shards and 130 tests? That'd be a setup we care about.

**Comment by maxuai** [comment]
I generated 129 (dumb) tests and split them into 5 files, where the first file will contain 5% of all tests, the second 10%, the third  20% the forth 30% and the fifth 35% and ran them with and without `fullyParallel` option. Here are my results:


- with `fullyParallel` set to `true` [run](https://github.com/maxuai/playwright-sharding/actions/runs/11210239631)
  - first shard 26 tests 
  - second shard 26 tests
  - third shard 26 tests
  - forth shard 26 tests
  - fifth shard 25 tests
- with `fullyParallel` set to `false` [run](https://github.com/maxuai/playwright-sharding/actions/runs/11210294357)
  - first shard 45 tests
  - second shard 39 tests
  - third shard 0 tests
  - forth shard 45 tests
  - fifth shard 0 tests

For `fullyParallel` set to `true` I see the algorithm tries to run the same number of tests on every shard. For the second case it seems to try the same but as it can only split by file the largest number of tests in a file defines the number of tests per shard which will lead to some shard running 0 tests and other aggregating multiple files. I think it would be really nice if there would be a way how to configure this, so either the algorithm for `fullyParallel` set to `false` just splits by file or in a combination with an additional config flag this would be achievable.

Some more context why we would like to use sharding:
In our real world scenario the number of tests is something that is not a good indicator for doing sharding but the tests are group logically and some take much longer that others, so having them split by file gives us the most control to share the load between all shards. Currently we get this by using `workers` but this doesn't scale well as it means we have to have one large node in the CI which can run multiple tests in parallel.

**Comment by pavelfeldman** [comment]
We encourage users to use fullyParallel to work around the poorly balanced test files. Scheduling is hard and we don't want to expose controls we won't be able to maintain in the future.

**Comment by maxuai** [comment]
@pavelfeldman I see, so it seems this is at all not a bug but "works as designed". I think it would be beneficial for other if this would be part of the documentation, so the scheduling differences when using `fullyParallel` or not and that sharding should mainly be used with this option enabled.

**Comment by pavelfeldman** [comment]
Updating the docs sounds like a good idea.
