### ISSUE TITLE
[Bug]: MSedge browser not installing, dependent on repo that has no current release file

### ISSUE THREAD

**Issue by christopher-r-doucet** [microsoft/playwright#32936]
### Version

1.47.2

### Steps to reproduce

1. run `npx playwright install msedge` in your playwright directory

### Expected behavior

Microsoft Edge should be installed

### Actual behavior

Err:12 https://ppa.launchpadcontent.net/maarten-baert/simplescreenrecorder/ubuntu noble Release
  404  Not Found [IP: 185.125.190.80 443]

E: The repository 'https://ppa.launchpadcontent.net/maarten-baert/simplescreenrecorder/ubuntu noble Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

microsoft-edge-stable: command not found
Failed to install browsers
Error: Failed to install msedge

### Additional context

http://ppa.launchpadcontent.net/maarten-baert/simplescreenrecorder/ubuntu/dists/ is the required distro to install the browser, however the author hasn't provided a file for `Noble` (current release). The Playwright docs say Ubuntu 24.04 is supported (Noble)

### Environment

```shell
System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
    Memory: 24.21 GB / 31.01 GB
    Container: Yes
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
  IDEs:
    VSCode: 1.93.1 - /usr/bin/code
  Languages:
    Bash: 5.2.21 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.47.2 => 1.47.2 
    playwright: ^1.44.1 => 1.47.2 
    playwright-slack-report: ^1.1.57 => 1.1.57
```

**Comment by Skn0tt** [comment]
Hi Chris, thanks for the report. I'm having trouble reproducing this. Here's what i'm doing:

1. create a fresh `ubuntu 24.04` instance on Azure
2. `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh` to get NVM
3. `nvm install 20.14.0` to install your version of Node.js
4. `npx playwright install msedge`

Everything works fine, I end up with `Microsoft Edge 129.0.2792.79`. Here's my env info for comparison:

```
  System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
    Memory: 7.10 GB / 7.75 GB
    Container: Yes
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
  Languages:
    Bash: 5.2.21 - /usr/bin/bash
  npmPackages:
    playwright: ^1.47.2 => 1.47.2 
```

I see that you have VS Code on your machine, so i'm assuming it's your Dev Box and not a blank CI instance. Maybe you have some local APT repository configs that interfere with the Playwright install? Please provide me with repro steps that start from a blank ubuntu install, so we can get to the bottom of this.

**Comment by mxschmitt** [comment]
this does not look like a Playwright issue.

These two lines suggest that your source lists are broken and resulting in errors:

```
Err:12 https://ppa.launchpadcontent.net/maarten-baert/simplescreenrecorder/ubuntu noble Release
404 Not Found [IP: 185.125.190.80 443]

E: The repository 'https://ppa.launchpadcontent.net/maarten-baert/simplescreenrecorder/ubuntu noble Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

I suggest you to either remove / consult the support of simplescreenrecorder.
