### ISSUE TITLE
[Feature] take implicit xpath if selector starts with .. (dot dot)

### ISSUE THREAD

**Issue by Snooz82** [microsoft/playwright#3293]
With the awesome selectors of Playwright it is now possible to use css or text and be able to select a parent node at the same time. 

``"login" >> xpath=../input`` 
It would be nice to have ``..`` as a start of a selector automatically being interpreted as xpath.

``"login" >> ../input`` 

Depending on my test object it is often the case that it is necessary to navigate up in the dom. This would make the selectors much more readable. 

Regards
René

**Comment by mxschmitt** [comment]
Hi, we implemented it already in #3239 which will be available in the next release. (next few days).

Thanks for the suggestion!

**Comment by aslushnikov** [comment]
This should be working fine in Playwright v1.3.0
