### ISSUE TITLE
[Feature]: Allow to use page after a test failed

### ISSUE THREAD

**Issue by bijela-gora** [microsoft/playwright#32946]
### 🚀 Feature Request

Is there a possibility to add a configuration to use page instance in `afterEach` hooks in same way, with same possibilities as in `test` callbacks?

### Example

```typescript
import { test, expect, type Page } from '@playwright/test';

test.beforeEach(async ({ page }) => {
  await page.goto('https://demo.playwright.dev/todomvc');
});

const TODO_ITEMS = [
  'buy some cheese',
  'feed the cat',
  'book a doctors appointment'
] as const;

async function addTodoItem(page: Page, description: string) {
  const newTodo = page.getByPlaceholder('What needs to be done?');
  await newTodo.fill(description);
  await newTodo.press('Enter');
}

async function removeTodoItem(page: Page, description: string) {
  const todoItemDescriptionElement = page.getByTestId('todo-title').filter({hasText: description});
  const todoItemElement = page.getByTestId('todo-item').filter({ has: todoItemDescriptionElement });
  todoItemElement.hover();
  const deleteButtonElement = todoItemElement.locator('css=[aria-label="Delete"]');
  deleteButtonElement.click();
}




// HERE: this is what I want do:
test.afterEach(async ({page}) => {
  for (const description of TODO_ITEMS) {
    await removeTodoItem(page, description)
  }
})





test.describe('New Todo', () => {
  test('should allow me to add todo items', async ({ page }) => {
    await addTodoItem(page, TODO_ITEMS[0]);
    await expect(page.getByTestId('todo-title')).toHaveText([
      TODO_ITEMS[0]
    ]);

    await addTodoItem(page, TODO_ITEMS[1]);
    await expect(page.getByTestId('todo-title')).toHaveText([
      TODO_ITEMS[0],
      TODO_ITEMS[1]
    ]);

    await addTodoItem(page, TODO_ITEMS[2]);
    await expect(page.getByTestId('todo-title')).toHaveText([
      TODO_ITEMS[0],
      TODO_ITEMS[1],
      TODO_ITEMS[2]
    ]);
  });
});

```

### Motivation

Such systems cannot be created and destroyed arbitrarily because it is expensive. In such systems, you want to selectively add the required state, perform checks, and delete the added state. This seems to be how testers test in a production environment. With care.

Is it doable? Is it a good idea? WDYT?

**Comment by Skn0tt** [comment]
Hi Bijela! `afterEach` is executed both after a successful test or a failure. If you're seeing something different, please open a bug report.

My understanding is that you're looking for a way to clean up test state after a test. You should also take a look at Fixtures, which is Playwright's recommended alternative to `beforeEach` and `afterEach`. The `todoPage` fixture in https://playwright.dev/docs/test-fixtures#creating-a-fixture is a good example of how that works.
