### ISSUE TITLE
[Questions] does Playwright support Tray from Electron (without BrowserWindow)? 

### ISSUE THREAD

**Issue by phananhtruc98** [microsoft/playwright#32941]
Hi everyone, I was researching the possibilities of writing an e2e for my tray application. But I don't see any documentation mentioned about the Tray alone.

**Comment by Skn0tt** [comment]
Tray is about the system notification bar, which lives outside of Electron's browser context. Playwright is about browser automation, we have no means of automating system-level UI. Playwright is the wrong tool for testing a Tray application.
