### ISSUE TITLE
[Bug]: InjectedScript.expectHitTarget returns wrong result

### ISSUE THREAD

**Issue by RunOrVeith** [microsoft/playwright#32957]
### Version

1.47.2

### Steps to reproduce

0. Copy the following code into `file.html`
```HTML
<html>

<head>
    <style>
        .outer {
            line-height: 1.5;
            white-space: nowrap;
            box-sizing: border-box;
            background: none;
            display: inline-flex;
            border: 0;
            margin: 0;
            padding: 0;
            position: relative;
            text-decoration: none;
            width: fit-content;
            pointer-events: none;
        }

        input {
            white-space: nowrap;
            box-sizing: border-box;
            appearance: none;
            cursor: pointer;
            height: 100%;
            width: 100%;
            margin: 0;
            opacity: 0;
            padding: 0;
            pointer-events: all;
            position: absolute;
        }

        .inner {
            white-space: nowrap;
            pointer-events: auto;
            box-sizing: border-box;
            align-items: center;
            cursor: pointer;
            display: flex;
            height: 36px;
            justify-content: center;
        }
    </style>


</head>

<body>
    <span class="outer">
        <input aria-labelledby="content" type="radio" checked="">
        <span id="content" class="inner">test</span>
    </span>
</body>

</html>

```

1. Open a chrome instance where you have [InjectedScript.expectHitTarget](https://github.com/microsoft/playwright/blob/895be9f8de4b1fe06d839370a95ed8464365ac7d/packages/playwright-core/src/server/injected/injectedScript.ts#L785]) available 
(You probably internally have something easier to do that than what I do, so I am not going to go into details here). I create it like this:
```TS
  const injectedScript = new InjectedScript(
    window,
    false,
    "javascript",
    "data-testid",
    0,
    "chromium",
    []
  );
  window.octomind.injectedScript = injectedScript;
```
)

2. Now in the resulting window open the html file.
It just contains a radio button with a span that is used as a label (only via `aria-labelledby`). 
I removed all the styling to keep the example small, but in essence it is placed so clicking it checks the invisible radio button, but there is a custom style so it looks like the span has been selected.
Here is an image of it with styling just so you understand how this is actually used:
![image](https://github.com/user-attachments/assets/e65dd4c6-f18a-43f3-b681-49cb6642ea2f)

3. Open the chrome dev tools in the Console tab and paste the following code (adjusted to however you access the `InjectedScript` instance):
```TS
const spanInQuestion = document.querySelector("#content");
let chromeResult; let expectHitTargetResult;
document.onmousemove = (e) => {
   chromeResult = document.elementsFromPoint(e.x, e.y);
   expectHitTargetResult = injectedScript.expectHitTarget({x: e.x, y: e.y}, spanInQuestion);
}
```

4. Add 2 live expression for `chromeResult` and `expectHitTargetResult` and move your mouse over the letters "test" of the page

See also this screenshot for what it should look like:
![image](https://github.com/user-attachments/assets/06567b8b-cfb8-4544-a667-89334e87053d)

### Expected behavior

I expect to see `"done"` appearing in the live expression when I move my mouse over the words "test", meaning that the span element was indeed hit.

### Actual behavior

I see `{hitTargetDescription: '<input checked type="radio" aria-labelledby="content"/>'}`, meaning that the expected hit target of the span was not found and it hit the input element instead.

### Additional context

Observe that chrome returns the span in `elementsFromPoint` as expected, but it is not in the first position.
I suspect that this is either because the span is not nested inside the input, or there is another bug similar to the one that is already handled with a comment about `Workaround webkit but where first two elements are swapped`.
I am not sure about that

### Environment

```shell
System:
    OS: Linux 6.8 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i9-13900H
    Memory: 46.37 GB / 62.45 GB
    Container: Yes
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    npm: 10.8.1 - ~/.nvm/versions/node/v20.14.0/bin/npm
    pnpm: 9.11.0 - ~/.nvm/versions/node/v20.14.0/bin/pnpm
  IDEs:
    VSCode: 1.94.0 - /snap/bin/code
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    @playwright/test: 1.47.2 => 1.47.2 
    playwright-core: 1.47.2 => 1.47.2
```

**Comment by pavelfeldman** [comment]
Any chance for a user-land repro for this? Some broken click or hover or something?

**Comment by pavelfeldman** [comment]
I ran your snippet and input does indeed intercept the pointer events. If you add a listener to your span, it won't be triggered upon the click.

**Comment by dgozman** [comment]
Closing as per above. If you still think there is a bug in Playwright, please file a new issue by filling in the "Bug Report" template and link to this one.
