### ISSUE TITLE
[Bug]: AudioWorkletNode ReferenceError in Webkit during Remote Test Runs

### ISSUE THREAD

**Issue by TesterrA** [microsoft/playwright#32975]
### Version

1.47.2

### Steps to reproduce

run test in remote machine by using wsconnect for AudioWorkletNode involved application.

 

### Expected behavior

When running tests in the WebKit browser remotely, the test should execute without triggering reference errors for AudioWorkletNode

### Actual behavior

During remote runs, WebKit logs the following errors:

[Page Error] - ReferenceError: Can't find variable: AudioWorkletNode

This behaviour is only observed when the tests are executed remotely (headless). Locally (headless and headed), the WebKit browser does not produce this error.

### Additional context

The issue seems to be specific to remote test environments using WebKit. There are no issues with Chrome or Firefox in the same environment.
This might be related to how WebKit handles certain APIs like AudioWorkletNode

chatgpt:

The errors you're encountering in WebKit:

ReferenceError: Can't find variable: AudioWorkletNode
are caused by missing or unsupported variables or objects. Here’s an explanation of each and how to address them:

1. ReferenceError: Can't find variable: AudioWorkletNode
What is AudioWorkletNode?
AudioWorkletNode is a part of the Web Audio API and is used to process audio in real-time on the browser's audio rendering thread. It’s mainly used for advanced audio applications, such as creating sound effects or handling audio streams.

Why this error occurs:
WebKit browser (Safari or Playwright's WebKit) may not fully support AudioWorkletNode depending on the version, platform, or specific environment (e.g., headless testing in Playwright). This object might not be implemented in certain WebKit builds, especially in headless or automation environments like Playwright.

### Environment

```shell
System:
    OS: macOS 14.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 193.11 MB / 16.00 GB
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.46.1 => 1.47.2 
    playwright-lighthouse: ^4.0.0 => 4.0.0
```

**Comment by pavelfeldman** [comment]
Please follow our BUG template to file something we can reproduce. It is unclear what "remotely" means in your context as well. Issues that don't follow the templates are closed according to the process we use internally.

**Comment by mxschmitt** [comment]
Do you mean with locally that you run them on your mac and with Remote you run them on Linux?

**Comment by TesterrA** [comment]
yes

**Comment by TesterrA** [comment]
@pavelfeldman  Thank you for the feedback. I did follow the bug template and mentioned using wsconnect in the "Steps to Reproduce" section, which explains the remote connection. If there's any part that’s unclear, I’d be happy to provide more details. I value the process, but your response made me feel a bit discouraged about filing issues when I encounter problems. I just wanted to inform you about the problem I'm facing and bring it to your attention, but I also respect your internal process, so I understand if you decide to close the issue. Of course, you are free to close or manage the issue in any way you see fit—this is your space, and I fully respect that.

Thank you for your time and consideration.
