### ISSUE TITLE
[Bug]: /usr/bin/env: ‘node’: Text file busy

### ISSUE THREAD

**Issue by stramel** [microsoft/playwright#32972]
### Version

1.47.2

### Steps to reproduce

Using the 1.47.2-noble docker image, run a node command

### Expected behavior

node related commands run

### Actual behavior

/usr/bin/env: ‘node’: Text file busy

### Additional context

related issues:
- https://github.com/nodejs/docker-node/issues/1912
- https://github.com/nodejs/node/issues/53051

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (32) x64 Intel(R) Xeon(R) CPU @ 2.30GHz
    Memory: 110.60 GB / 117.93 GB
    Container: Yes
  Binaries:
    Node: 20.17.0 - /usr/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.8.2 - /usr/bin/npm
  Languages:
    Bash: 5.2.21 - /usr/bin/bash
  npmPackages:
    @playwright/test: 1.47.2 => 1.47.2 
    playwright: 1.47.2 => 1.47.2 
    playwright-core: 1.47.2 => 1.47.2
```

**Comment by pavelfeldman** [comment]
Sounds like your host kernel is affected by a bug that you link to.

**Comment by dgozman** [comment]
Closing as per above. There's nothing to fix on the Playwright side.
