### ISSUE TITLE
[Bug]: Playwright with browserstack

### ISSUE THREAD

**Issue by srikanthathikari** [microsoft/playwright#32977]
### Version

1.44.0

### Steps to reproduce

I am using Playwright with TypeScript and BrowserStack as a cloud service to execute tests on a remote machine. Within my spec file, I have a single test.describe block that contains multiple tests, each representing a part of a broader scenario. In BrowserStack, as soon as the first test passes, the overall test is marked as passed, even though the subsequent tests in the spec continue to run until completion. My goal is to report a single pass or fail status for the entire spec only after all the tests within it have finished executing. Is there a way to achieve this ?

### Expected behavior

I want a test to be in a pass bucket or failed bucket of browserstack only upon completion of the spec file consisting only one test.describe within that having multiple tests. 

### Actual behavior

I want a test to be in a pass bucket or failed bucket of browserstack only upon completion of the spec file consisting only one test.describe within that having multiple tests. 

### Environment

```shell
Mac OS
```

**Comment by mxschmitt** [comment]
Sounds like an issue which should get filed against the BrowserStack issue tracker / support.
