### ISSUE TITLE
[Docs]: Parallel setup doesn't mention how to configure web servers

### ISSUE THREAD

**Issue by KieranP** [microsoft/playwright#32978]
### Page(s)

https://playwright.dev/docs/test-parallel
https://playwright.dev/docs/test-webserver

### Description

The current parallel documentation dosen't mention how to configure multiple web servers.

My use case:
* I want to parallel my tests using four workers
* Each worker needs it's own webserver, which in turn will use its own database
* Current docs show how to setup multiple web servers, but not how to link them to a worker

Current resulty:
* All parallelized tests are hitting the same base url
* My tests include a data reset action to isolate tests
* Therefore, tests are failing because they are tripping up over each other

Expected:
* Should be able to specify which web server belongs to which worker index
* That way, each worker has their own server/database, and won't conflict

**Comment by pavelfeldman** [comment]
You should use worker fixtures if you want to scope your resources to workers:
- https://playwright.dev/docs/test-parallel#isolate-test-data-between-parallel-workers 
- https://playwright.dev/docs/auth#moderate-one-account-per-parallel-worker
