### ISSUE TITLE
[Feature]: Display spec file line when calling POM actions

### ISSUE THREAD

**Issue by Manuel-Suarez-Abascal** [microsoft/playwright#32979]
### 🚀 Feature Request

When using Playwright with the Page Object Model (POM) pattern, actions are typically defined within page object files and then imported into spec/test files. Currently, the Playwright Trace Viewer only displays the line in the page object file where an action is declared, rather than the line in the spec file where the action is actually called. This makes it difficult to trace the execution flow of tests directly from the spec files, which is where test logic is orchestrated.

**Proposed Enhancement:**

Modify the Trace Viewer to display both the location in the spec file where a page object action is called and the location in the page object file where the action is defined. This would provide a more intuitive understanding of the test execution flow, especially for those utilizing the POM pattern.

**Current Behavior:**

- The Trace Viewer shows the action `login()` and points to its definition in `loginPage.js`.
- It does not show the line in `login.spec.js` where `loginPage.login()` is called.

**Desired Behavior:**

- The Trace Viewer should display the line in `login.spec.js` where `loginPage.login()` is invoked.
- It can optionally provide a link or reference to the action's definition in `loginPage.js`.

### Example

**Example Scenario:**

1. **Page Object File (loginPage.js):**

   ```javascript
   class LoginPage {
     constructor(page) {
       this.page = page;
     }

     async login(username, password) {
       await this.page.fill('#username', username);
       await this.page.fill('#password', password);
       await this.page.click('#submit');
     }
   }

   module.exports = LoginPage;
   ```

2. **Spec File (login.spec.js):**

   ```javascript
   const { test } = require('@playwright/test');
   const LoginPage = require('./loginPage');

   test('User can log in', async ({ page }) => {
     const loginPage = new LoginPage(page);
     await loginPage.login('user1', 'password123');
   });
   ```

### Motivation

- **Improved Traceability:** Easier to follow the test execution flow from the spec files.
- **Enhanced Debugging:** Quicker identification of issues in test logic.
- **Developer Efficiency:** Reduces time spent navigating between files to understand test behavior.

**Comment by pavelfeldman** [comment]
https://playwright.dev/docs/api/class-test#test-step:~:text=%7D)%3B-,Boxing,-When%20something%20inside
