### ISSUE TITLE
[Feature]: typesafe / generic matchers

### ISSUE THREAD

**Issue by sand4rt** [microsoft/playwright#32986]
### 🚀 Feature Request

Is it possible for `toMatchObject` and similar functions to be type-safe and accept a generic like jest/vitest?

### Example

```ts
import type { UpdateDto } from '@my/generated-api-client';

expect(request).toMatchObject<UpdateDTO>({ id: '1337', status: 'DRAFT' })
```

### Motivation

I am generating DTO types from an OpenAPI/rest spec using [Orval](https://orval.dev/overview) to keep backend and frontend types in sync. When i regenerate the DTOs, I want my IDE to immediately highlight any failing tests/changed types, without needing to run them manually.

**Comment by ruifigueira** [comment]
I opened PR #33035 with a proposal for generic `toMatchObject` and `toStrictEqual` matchers.

I left tests as `fixme` because they rely on `stable-test-runner`.

**Comment by dgozman** [comment]
@sand4rt If you generate the following, would it work for you as well?

```ts
import type { UpdateDto } from '@my/generated-api-client';

expect(request).toMatchObject({ id: '1337', status: 'DRAFT' } satisfies UpdateDTO);
```

I *think* this could solve your problem more generally, not relying on any third-party library like Playwright to check your types. Let me know what you think.

**Comment by sand4rt** [comment]
@dgozman Ah, i hadn't considered using `satisfies`, but that works too. I think i actually prefer it over the generic approach

**Comment by ruifigueira** [comment]
That settles this then. I'll close my PR
