### ISSUE TITLE
[Feature]: Abstract binding types with non-static methods

### ISSUE THREAD

**Issue by Code-Chops** [microsoft/playwright#32998]
### 🚀 Feature Request

Why can abstract binding types only have `static` binding methods? This is a huge drawback.

Is there a good reason why this is not supported? If there is none, can I create a PR for it?

### Example

```
public abstract class FeatureSteps
{
    protected abstract string NaveMenuResourceName { get; }
    protected abstract string FeatureMainPageRoute { get; }

    [When(@"the user goes to the feature main page")]
    public Task WhenTheUserGoesToFeatureMainPage()
    {
        return this.Page.ClickAsync($"#{NavMenu.GetId(this.NavMenuResourceName)}");
    }

    [Then(@"the user should be on the feature main page")]
    public void ThenTheUserShouldBeOnTheFeatureMainPage()
    {
        this.Page.Url.Should().StartWith($"{TestHooks.RootUri}{this.FeatureMainPageRoute}");
    }
}
```

### Motivation

A class containing base steps is a great way to abstract away repeating logic.

**Comment by pavelfeldman** [comment]
I am not sure I understand the request, could you elaborate, provide examples?

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
