### ISSUE TITLE
[Feature]: Make HTML report test results easier to navigate

### ISSUE THREAD

**Issue by mskelton** [microsoft/playwright#32995]
### 🚀 Feature Request

Currently, in the HTML reports, there are some gaps in the clickable links where clicking a test result will not actually open it. We can improve this with some small CSS changes to make the entire result clickable to go to the test.

In the below screenshots, only the DOM nodes highlighted are clickable, so clicking in the large whitespace to the right will not navigate to the test results.

<img width="1053" alt="image" src="https://github.com/user-attachments/assets/219167ed-7cbc-4af7-b64d-6a3311a7f3a2">

<img width="1035" alt="image" src="https://github.com/user-attachments/assets/9e85542d-2b89-4a2a-8de1-9b4bb5bbd670">

### Motivation

Should make it easier to navigate Playwright HTML reports which my company uses heavily.

**Comment by pavelfeldman** [comment]
I'd say we are well within the accepted accessible guidelines in terms of click target sizes. Does https://github.com/microsoft/playwright/issues look any different to you or does it also suffer from the same issue? What OS are you on? Could you check which font is picked for rendering (DevTools / Styles / Computed Styles).

**Comment by mskelton** [comment]
I would agree that it's acceptable as far as minimum accessibility requirements, it's more about the convenience of it. Having a larger click target makes it easier and there isn't much in the way of downside in my opinion.

**Comment by pavelfeldman** [comment]
There are downsides - apart from clicking the row, users select and copy the test title, they select location and reveal it in their IDEs. In general I would say that we follow the best practices with the present hit targets. Also, our PR acceptance criteria is much higher than the lack of downside, we try to only land changes that meaningfully improve experience of majority of the users and regress nobody.

I'll close this one as not planned!
