### ISSUE TITLE
[Bug]: UI and Timeline wiped away even when any test is passed or failed both are not working hence debugging is not possible.

### ISSUE THREAD

**Issue by HarshitaSri22** [microsoft/playwright#32999]
### Version

1.47.2

### Steps to reproduce

UI,Timeline,and even logs are not visible .
![Screenshot 2024-10-08 115718](https://github.com/user-attachments/assets/5048d6e5-c39b-4546-ba95-fee3cf44be28)

### Expected behavior

Everything should be visible in UI,Timeline and console logs.
It's your own example file only nothing from my side.

### Actual behavior

Not working properly with UI, Timeline and Console logs.

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 6.88 GB / 15.79 GB
  Binaries:
    Node: 20.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.3 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.94.0 - C:\Users\hsrivastava\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.47.2 => 1.47.2
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
