### ISSUE TITLE
[Bug]: Pending Requests When Using page.route() to Intercept API Calls in Playwright in debug mode

### ISSUE THREAD

**Issue by hamzahamidi** [microsoft/playwright#33013]
### Version

1.46.1

### Steps to reproduce

I’m attempting to intercept the login API request in my Playwright test using page.route(). However, when I add the route interception for the API, other network requests in the browser start staying pending. This issue occurs only when the route interception is active and I have a breakpoint in the test I'm waiting on. Requests get stuck even if the breakpoint is in a different part of the code, unrelated to the route handler.

Interestingly, when I release the breakpoint, the requests and proceed as expected along with the tests.

Here is the relevant code snippet:

Here is the relevant code snippet:
```typescript
export async function injectDeviceId(page: Page, email?: string): Promise<void> {
  await page.route('**/api/login', async (route, request) => {
    console.log('Intercepted request:', request.url());
    await route.continue();  // Continue with the request as normal
  });
}
```

The issue happens only when this interception is added, even though await route.continue() is being called to let the request proceed. Without this route interception, all requests work as expected, but with it, requests, including the one I want to intercept, stay pending indefinitely when I hit a breakpoint during testing.

Steps to Reproduce:

1. Add a route to intercept requests to the /api/login endpoint in Playwright.
2. Run a test that successfully hits the login API and has other requests on the page.
3. Set a breakpoint after the login request is successful.
4. Observe that the login request is successful, but the next requests remain pending in the browser's Network tab.
5. I notice that the requests I trigger manually in the browser are also pending.
6. This occurs only when the route interception is active and a debugging breakpoint is active.
7. When I release the breakpoint, the pending requests proceed normally along with the rests of the tests.
8. When I commented the entire page.route() code, the requests didn't hang even though I was in a breakpoint.

### Expected behavior

The requests shouldn't not hang when debugging and waiting in active breakpoint when using page.route()

### Actual behavior

Requests hanging when debugging with playwright and using page.route

### Environment

```shell
System:
    OS: macOS 14.7
    CPU: (10) arm64 Apple M1 Max
    Memory: 416.70 MB / 32.00 GB
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
  IDEs:
    VSCode: 1.93.0 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.46.1 => 1.46.1 
    playwright-bdd: ^7.1.0 => 7.1.0
```

**Comment by pavelfeldman** [comment]
> Requests get stuck even if the breakpoint is in a different part of the code, unrelated to the route handler.

JavaScript is single-threaded. When you are on a breakpoint, the world stops.

**Comment by hamzahamidi** [comment]
Unless the page.route() is using the same thread

**Comment by hamzahamidi** [comment]
Note to anyone encountering this issue:

It can be confusing, but when you add a page.route() block in Playwright, even if you are targeting a specific route, all network requests in the browser can hang while debugging—especially if you're paused at a breakpoint, even if it's unrelated to the route being tracked.

So, if you're debugging and notice that your requests are hanging, double-check if you have any page.route() code in your test. This happens because the request interception likely runs on the same thread, which might affect concurrency and the order of requests. While this is intended for better control, it can be tricky to understand at first.
