### ISSUE TITLE
[Bug]: EvaluateAsync silently fails on some webpages, but not others

### ISSUE THREAD

**Issue by shravan2x** [microsoft/playwright#33015]
### Version

1.47.0

### Steps to reproduce

Use this code
```c#
IPlaywright playwright = await Playwright.CreateAsync();
BrowserTypeLaunchOptions options = new BrowserTypeLaunchOptions()
{
    Channel = "chrome",
    Headless = false
};
IBrowser browser = await playwright.Chromium.LaunchAsync(options);

IPage page = await browser.NewPageAsync();
await page.GotoAsync("https://taplink.at/en/tariffs/");
await page.WaitForLoadStateAsync(LoadState.Load);

string? res = await page.MainFrame.EvaluateAsync<string?>("'test'");
Console.WriteLine(res);
```

### Expected behavior

The printed value is `test`, as expected, on most websites (try `https://example.com` for instance), but returns null on other domains like `https://taplink.at/en/tariffs/`. Since the script has no more logic in it besides a simple return value, I'd expect it to work always, even if the page rewrites some JS types or hasn't loaded yet.

### Actual behavior

On some domains, the call to EvaluateAsync returns `null`.

### Environment

```Text
- Operating System: Windows 11
- CPU: x64
- Browser: Chrome
- .NET Version (TFM): net8.0
- Other info:
```

**Comment by mxschmitt** [comment]
The website seems overriding `window.eval`

**Comment by shravan2x** [comment]
That's interesting. IMO the fix here might be either 1) Using a different mechanism to ensure EvaluateAsync always works or 2) Documenting that Playwright uses window.eval under the hood so users can watch out for it. Thoughts?

**Comment by pavelfeldman** [comment]
Overriding eval is such a bad act that I would not account for or document it.

**Comment by shravan2x** [comment]
@pavelfeldman While I agree with you wholeheartedly, the domain in question is not under my control. How would you recommend proceeding with using Playwright in the wild, if it isn't able to handle variability in them?
