### ISSUE TITLE
[Feature] Permission (Notification, Geolocation, etc.) Event

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#3301]
I'd like to test that a site requests for user's geolocation and notification permissions at the appropriate time. Can you please add an API that could be used like the following:

```js
context.on('permissions', async (permission) => {
    const name == permission.name();
    if (name === 'geolocation') {
        await permission.allow();
    } else if (name === 'notification'){
         await permission.deny();      
    }
    // ignore others
})
```

**Comment by pavelfeldman** [comment]
Setting expectations: great request, I wanted the same thing, but requires substantial amount of work in all browsers.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.

**Comment by Hoodognik** [comment]
+

**Comment by TomasHubelbauer** [comment]
Looks like this is somewhat there now.

My test:

```typescript
import { test } from '@playwright/test';

test('has title', async ({ page }) => {
  await page.goto(`file://${__dirname}/../index.html`);

  page.on('console', msg => console.log(msg.text()));

  page.on('dialog', async dialog => {
    console.log(dialog.type(), dialog.message());
    await dialog.accept();
  });

  await page.context().grantPermissions(['notifications']);
  await page.click('button');
  //expect(await page.evaluate(() => Notification.permission)).toBe('granted');
  await page.locator('body.shown').waitFor();
});
```

My page's script:
```
const button = document.querySelector('button');

button.addEventListener('click', async () => {
  alert('test');

  console.log('requesting');
  const notificationPermission = await Notification.requestPermission();
  console.log('requested', notificationPermission, Notification.permission);
  const notification = new Notification('test');
  notification.onshow = () => {
    document.body.classList.toggle('shown', true);
    console.log('shown');
  }

  console.log('notification', notification);
});
```

When running headless, this gets stuck waiting for the notification's `show` event. It eventually times out. The notification is never shown. The test fails.

When running headed (or as I prefer, headful), the `show` event gets invoked but no actual notifications appears. Even when I tack on a timeout at the end of the test to give the notification time to appear, it never does. The test passes.

**Comment by TomasHubelbauer** [comment]
@pavelfeldman @dgozman @aslushnikov could this please be reopened so it can be triaged again and the current status clarified? As per my prior comment I believe things have changed since the status of notifications was originally clarified on this issue by Pavel.

**Comment by aslushnikov** [comment]
@TomasHubelbauer please file a new issue! This way we'll triage it accordingly. It'll also help a lot if you summarize what changed and why you think there's something to be done.
