### ISSUE TITLE
[Regression]: `snapshotPathTemplate` seems to have a character limitation

### ISSUE THREAD

**Issue by Llois41** [microsoft/playwright#33010]
### Last Good Version

1.45.3

### First Bad Version

1.47.2

### Steps to reproduce

We have the follwing entry in our `playwright.config.ts` file:

`snapshotPathTemplate: 'ui-tests/single-page-tests/{testFilePath}-snapshots/{arg}-{projectName}-{platform}{ext}'`

This configures the path of the screenshot in the report.

### Expected behavior

I expect to see the same paths in the report after the update from `1.45.3` to `1.47.2`

### Actual behavior

In some cases (I guess when the actual path becomes to long) playwright replaces some characters (in the `{arg}` part of the path) with a hash(?), e.g. after the update, the path is
`"ui-tests/single-page-tests/testFilePath-snapshots/random-test-name-from-the-tes-3cff4-s-wayyyyyyy-tooooo-long-webkit-linux.png"`

when before it was 

`"ui-tests/single-page-tests/testFilePath-snapshots/random-test-name-from-the-testcase1-which-is-wayyyyyyy-tooooo-long-webkit-linux.png"`

I haven't found anything related in the docs or the release notes

### Additional context

I did not test any versions in between because we have a very large setup which would take some time. However I hope whit the description is it easy answer if it is a regression or an undocumented feature/change.

Also we are upgrading to v1.47.2 without the jammy -> noble update

### Environment

```shell
System:
    OS: macOS 15.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.64 GB / 32.00 GB
  Binaries:
    Node: 20.17.0 - /opt/homebrew/opt/node@20/bin/node
    Yarn: 4.3.0 - /opt/homebrew/bin/yarn
    npm: 10.8.2 - /opt/homebrew/opt/node@20/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by pavelfeldman** [comment]
> after the update, the path is
"ui-tests/single-page-tests/testFilePath-snapshots/random-test-name-from-the-tes-3cff4-s-wayyyyyyy-tooooo-long-webkit-linux.png"

Which path? Expected, actual, under test-results? Why do you think it is different, any test output suggesting this? Could you follow the BUG template to provide something we can repro?

**Comment by Llois41** [comment]
I can try to make a simple repro tomorrow. The actual path of the screenshots in the test report now includes a hash in the middle.

**Comment by pavelfeldman** [comment]
If that is `actual`, then things are as expected, the name we generate is an implementation detail in Playwright. Your report will link to it correctly, but you can't assume the name.

**Comment by Llois41** [comment]
@pavelfeldman Ah alright, I read this thread again and now I understand what you are saying. We expected the path in the report to be the same as the `snapshotPathTemplate` which only seems to be the path where the tests look for the screenshots to compare to. We used it to update our screenshots on changes which now leads into a mismatch.

I'll close this bug, thanks for clarifying.
