### ISSUE TITLE
[Bug]: Missing explicit waits cause an issue with a UI automation

### ISSUE THREAD

**Issue by aikram96** [microsoft/playwright#33012]
### Version

1.47.1

### Steps to reproduce

**Description:**
I am experiencing an issue when automating a button click for the "Add location" button. When the automation clicks the button, a prompt is returned stating that I have reached the allowed limit for locations. However, this behavior does not occur when I manually perform the same action; the prompt does not appear in manual tests.

After investigating with the development team, we suspect this might be a timing issue. I haven’t found a reliable way to implement an explicit wait or intercept the relevant endpoint that returns this assertion.

I am wondering if it’s possible to enable more flexible explicit or implicit waits, similar to a time.sleep(1). Currently, I am using the following command to force a wait, but it doesn’t seem to resolve the issue: `await page.waitForTimeout(3000);`

Is there a better approach to handle this kind of situation, or is this a known issue with how Playwright manages timing?

**Steps**
Enter to specific URL
Login with the credentials
Click on "add location button" --> the endpoint by default responds True for limit reached, the endpoint takes 750ms to finish the response to False
I have some other steps which are blocked bc the prompt of limit reached is displayed 
<img width="674" alt="image" src="https://github.com/user-attachments/assets/ff792821-f7a0-4e97-8534-60511411a45b">

Thank you for your help!

### Expected behavior

I expected to find a way to way for a specific time - in this case 1 second if is need it or more. In oher way, could be great to intercept endpoint calls (POST/intercept) so I will be able to control the real response of the endpoint and continue with the UI automation. 

### Actual behavior

Not able to control explicit waits. 

### Environment

```shell
System:
    OS: macOS 15.0.1
    CPU: (8) arm64 Apple M2
    Memory: 66.72 MB / 8.00 GB
  Binaries:
    Node: 22.6.0 - /usr/local/bin/node
    npm: 10.8.2 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.47.1 => 1.47.1
```

**Comment by pavelfeldman** [comment]
I don't see a bug in Playwright in this report.
- Note that you are missing `await` in your snippet before `page.waitForTimeout`, that's why it does not wait
- You should **never** use the `waitForTimeout` in a test, if you do, your test will fail due to flakiness all the time
- You can intercept and wait for endpoint calls: https://playwright.dev/docs/network#network-events, but you should not need to in this case
- It is likely that our app has a hydration issue, i.e. there is a bug in your web app. See https://playwright.dev/docs/navigations#hydration
