### ISSUE TITLE
[Feature]: Add custom project level fixtures from the config file

### ISSUE THREAD

**Issue by twk3** [microsoft/playwright#33016]
### 🚀 Feature Request

Adding the ability to define new fixtures from the config file, attaching these to the project suite. WIthout needing to extend `test`.

- Unlike `use` which allows you to override any option type fixture, add a `fixtures` which allows registering new fixtures to the exiting TestImpl.
- Useful for when you want to set a global beforeEach/afterEach, and need the testInfo class.

### Example

```
import { devices, PlaywrightTestConfig } from "@playwright/test";

const config: PlaywrightTestConfig = {
  retries: 0,
  workers: 1,

  timeout: 60000,
  fullyParallel: true,

  expect: {
    timeout: 500,
  },

  use: {
    // actionTimeout: 0,
    // screenshot: "only-on-failure",
    // video: "retry-with-video",
    // trace: "on",
  },

  projects: [
    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
      },
      fixtures: {
         myCoolFixture: [async ({}, use, testInfo) => {
            process.stdout.write(`before ${testInfo.title}`);
            await use({});
            process.stdout.write(`after ${testInfo.title}`);
        }, {auto: true}]
      },
    },
  ],
  outputDir: "test-results/",
};

export default config;


```

### Motivation

This would allow the addition of new fixtures without the test files needing to be updated with new imports for different test implemenations.

Making the adding of third party fixtures, or even the sharing fixture examples easier. As fixtures could be easily imported in the config file and added to the project.

This would also help promote the use of custom fixtures, as the barrier to entry for incorporating your own custom fixture is less.

**Comment by pavelfeldman** [comment]
test.extend would be the way to go here, we don't need another way of doing the same thing. I would also encourage you to keep your config as declarative as possible for better maintainability.
