### ISSUE TITLE
[Bug]: Locator.ScrollIntoViewIfNeeded or page.mouse.down() are not working without --headed flag

### ISSUE THREAD

**Issue by garg-shubham** [microsoft/playwright#33018]
### Version

1.44

### Steps to reproduce

1. Pick a test in which you need to scroll down to select the row 
2. Use either locator.scrollIntoViewIfNeeeded or page.mouse.down() to scroll down
3. Run the test with --headed flag. This should pass
4. Run the test without 'headed' flag and the tests fails because playwright could scroll down. 

### Expected behavior

I expect playwright to be able to scroll down the page even without --headed flag

### Actual behavior

The test doesn't error out on scrolling action but instead tries to select the locator and times out then. 

### Environment

OS: Windows 11
Browser: chrome driver

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
