### ISSUE TITLE
intro.mdx Version in pom.xml is wrong

### ISSUE THREAD

**Issue by cbromberg** [microsoft/playwright#33028]
[playwright.dev](https://github.com/microsoft/playwright.dev/tree/main)/[java](https://github.com/microsoft/playwright.dev/tree/main/java)/[docs](https://github.com/microsoft/playwright.dev/tree/main/java/docs)
/intro.mdx 

Version in the pom.xml is v1.47.0 but should be 1.47.0 instead. Seems to be generated by some tool/script

**Comment by mxschmitt** [comment]
I can observe it on https://playwright.dev/java/docs/intro#usage

**Comment by cbromberg** [comment]
Exactly - that is the 'public' URL - I reported the source path in the docs repo
