### ISSUE TITLE
[Bug]: 1.48.0 missing chromium-bidi dependency

### ISSUE THREAD

**Issue by halljus** [microsoft/playwright#33031]
### Version

1.48.0

### Steps to reproduce

1. Clone my repo at https://github.com/halljus/playwright-1.48.0-repro
2. npm install
3. npx playwright install
4. npm run dev
5. Browse to http://localhost:5173

Observe in the server console that the ~bundler~ compiler (esbuild) cannot resolve `chromium-bidi`.

### Expected behavior

It should just work (either by not requiring a devDependencies library, promoting it to dependencies, or updating documentation with further instructions).

**This error does not occur in playwright v1.47.2, the latest version prior to v1.48.0.**

### Actual behavior

```
✘ [ERROR] Could not resolve "chromium-bidi/lib/cjs/bidiMapper/BidiMapper"

    node_modules/playwright-core/lib/server/bidi/bidiOverCdp.js:7:49:
      7 │ var bidiMapper = _interopRequireWildcard(require("chromium-bidi/lib/cjs/bidiMapper/BidiMapper"));
        ╵                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "chromium-bidi/lib/cjs/bidiMapper/BidiMapper" as external to exclude it from
  the bundle, which will remove this error and leave the unresolved path in the bundle. You can also
  surround this "require" call with a try/catch block to handle this failure at run-time instead of
  bundle-time.

✘ [ERROR] Could not resolve "chromium-bidi/lib/cjs/cdp/CdpConnection"

    node_modules/playwright-core/lib/server/bidi/bidiOverCdp.js:8:56:
      8 │ var bidiCdpConnection = _interopRequireWildcard(require("chromium-bidi/lib/cjs/cdp/CdpConnection"));
        ╵                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "chromium-bidi/lib/cjs/cdp/CdpConnection" as external to exclude it from the
  bundle, which will remove this error and leave the unresolved path in the bundle. You can also
  surround this "require" call with a try/catch block to handle this failure at run-time instead of
  bundle-time.

11:01:44 AM [vite] error while updating dependencies:
Error: Build failed with 2 errors:
node_modules/playwright-core/lib/server/bidi/bidiOverCdp.js:7:49: ERROR: Could not resolve "chromium-bidi/lib/cjs/bidiMapper/BidiMapper"
node_modules/playwright-core/lib/server/bidi/bidiOverCdp.js:8:56: ERROR: Could not resolve "chromium-bidi/lib/cjs/cdp/CdpConnection"
    at failureErrorWithLog (C:\Users\user\dev\playwright-1.48.0-repro\node_modules\vite\node_modules\esbuild\lib\main.js:1472:15)
    at C:\Users\user\dev\playwright-1.48.0-repro\node_modules\vite\node_modules\esbuild\lib\main.js:945:25
    at C:\Users\user\dev\playwright-1.48.0-repro\node_modules\vite\node_modules\esbuild\lib\main.js:1353:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Additional context

The repro is a fresh Remix project, but it's a Vite issue.

Relevant code:

- https://github.com/microsoft/playwright/blob/bc30cc795e7a9f148039de77dd790cf44097450e/packages/playwright-core/src/server/bidi/bidiChromium.ts#L40
- https://github.com/microsoft/playwright/blob/bc30cc795e7a9f148039de77dd790cf44097450e/packages/playwright-core/src/server/bidi/bidiOverCdp.ts#L17

### Environment

```
System:
  OS: Windows 10 10.0.19045
  CPU: (12) x64 13th Gen Intel(R) Core(TM) i5-1345U
  Memory: 38.74 GB / 63.64 GB
Binaries:
  Node: 20.17.0 - ~\AppData\Local\nvs\default\node.EXE
  npm: 10.8.2 - ~\AppData\Local\nvs\default\npm.CMD
IDEs:
  VSCode: 1.94.1 - C:\Users\user\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
Languages:
  Bash: 5.1.16 - C:\WINDOWS\system32\bash.EXE
npmPackages:
  playwright: 1.48.0 => 1.48.0 
```

**Comment by pavelfeldman** [comment]
I don't think playwright is ready to be bundled, what is your use case?

**Comment by halljus** [comment]
> I don't think playwright is ready to be bundled, what is your use case?

I might've misspoken by calling it a bundler, as I don't think it's bundling in this context.

The use case is using Playwright on the server in a Remix app (could be Next.js or any other modern web framework) . It's been working fine like this for as long as I can remember, it just stopped with 1.48.0 yesterday. :P

There's a comment right above the offending import:

```
// Chrome doesn't support Bidi, we create Bidi over CDP which is used by Chrome driver.
// bidiOverCdp depends on chromium-bidi which we only have in devDependencies, so
// we load bidiOverCdp dynamically.
const bidiTransport = await require('./bidiOverCdp').connectBidiOverCdp(transport); 
```

Dynamically imported or not, wouldn't bidiOverCdp's dependencies (`chromium-bidi`) need to be installed in consuming projects? Unless maybe there's a check elsewhere in the calling code to only load bidiChromium.ts if developing locally within the Playwright project, but if there is - it doesn't appear to be working.

**Comment by pavelfeldman** [comment]
As long as the method is not called (which it isn't), it shouldn't be an issue. Sounds like the next bundler pre-processes the code and pulls requires to the top level.

```js
  override async connectToTransport(transport: ConnectionTransport, options: BrowserOptions): Promise<BidiBrowser> {
    // Chrome doesn't support Bidi, we create Bidi over CDP which is used by Chrome driver.
    // bidiOverCdp depends on chromium-bidi which we only have in devDependencies, so
    // we load bidiOverCdp dynamically.
    const bidiTransport = await require('./bidiOverCdp').connectBidiOverCdp(transport);
    (transport as any)[kBidiOverCdpWrapper] = bidiTransport;
    return BidiBrowser.connect(this.attribution.playwright, bidiTransport, options);
  }
```

**Comment by mxschmitt** [comment]
Marking `chromium-bidi` as [external](https://esbuild.github.io/api/#external) in ESBuild might make it work.

**Comment by pavelfeldman** [comment]
Closing as per above. Not sure if it is worth bringing up with the esbuild / vite folks to let them know that they could do a better job at detecting playwright as a server-side only import.

**Comment by markledwich2** [comment]
`bun build` also has the same error with `1.48` but not `1.47`. I'm pre-compiling a typescript project to run in a container. I think this is normal?

```
7 | var bidiMapper = _interopRequireWildcard(require("chromium-bidi/lib/cjs/bidiMapper/BidiMapper"));
                                                     ^
error: Could not resolve: "chromium-bidi/lib/cjs/bidiMapper/BidiMapper". Maybe you need to "bun install"?
    at /home/mark/code/forecast/node_modules/playwright-core/lib/server/bidi/bidiOverCdp.js:7:50
```

**Comment by maxmckenzie** [comment]
So i'm seeing this same issue when trying to build a Nuxt3 (3.13.2) app with [`ssr: true`](https://nuxt.com/docs/guide/concepts/rendering#universal-rendering). I set the optimizeDeps, as suggested in the [comment above](https://github.com/microsoft/playwright/issues/33031#issuecomment-2405403388)  but it still errors.

I mitigated this by downgrading and pinning the exact version 1.47.2 in my package.json `"@playwright/test": "1.47.2"`

However, what really confuses me is that this error comes up when i run the build `nuxt build`. Why is playwright involved in that at all? this is bundling my frontend code as a universal app so why the test framework? 

The only place playwright is called inside my code base is the test files (excluded and added to .nuxtignore just in case). and in the npm test script. So... why is it attempting to bundle playwright?

**Comment by AllanOricil** [comment]
@halljus 
Im seeing this issue when using vitest, which use vite, however I can't configure its server to exclude chromium-bidi like you did

![Image](https://github.com/user-attachments/assets/a279d055-6f25-412b-8209-8344a309c39a)


![Image](https://github.com/user-attachments/assets/5b5c339f-ea3b-4fba-920f-41c84b5b5efd)


I'm using vitest "browser" feature with `playwright`
https://vitest.dev/guide/browser/#examples

This is my vitest.worspace.mjs

```js
import { defineWorkspace } from "vitest/config";
import * as path from "path";

export default defineWorkspace([
  {
    resolve: {
      alias: {
        "@": path.resolve(__dirname, "./src"),
        "@/nodes": path.resolve(__dirname, "./src/nodes"),
      },
    },
    test: {
      name: "unit",
      include: ["test/unit/nodes/**/*.{test,spec}.js"],
      globals: true,
      environment: "node",
      reporters: ["html"],
      coverage: {
        enabled: true,
        provider: "istanbul",
        reportsDirectory: "./coverage",
        reporter: ["html"],
      },
    },
  },
  {
    test: {
      name: "browser",
      include: ["test/browser/**/*.{test,spec}.js"],
      browser: {
        provider: "playwright",
        enabled: true,
        name: "chromium",
      },
      globalSetup: "./global-setup.mjs",
    },
  },
]);
```

my `global-setup.mjs` is just starting another application in the background, and has nothing to do with this error, so I'm not posting it here.

dev dependencies
```js
"@vitest/browser": "^2.1.4",
"playwright": "^1.48.2",
"vitest": "^2.1.4",
```

I also had to run `npx playwright install` to download browsers, which was a recommended command playwright itself showed on the terminal.

**Comment by AllanOricil** [comment]
Downgrading to 1.47.2 got rid of this issue.

**Comment by ffxsam** [comment]
This issue also affects [SST](https://sst.dev/). Pinning at 1.47.2 fixed it.

**Comment by halljus** [comment]
@AllanOricil Yeah, I don't know. I still think Microsoft needs to revisit the change in 1.48.0 rather than claiming all the different build tools in the ecosystem are wrong, but what do I know? They're smarter than I. 🙂

**Comment by adamdehaven** [comment]
I can confirm the bug was introduced in [version `1.48.0`](https://github.com/microsoft/playwright/releases/tag/v1.48.0)

@pavelfeldman (or team) Is it possible to please reopen this issue? The integration within a Vite ecosystem (in my case, Nuxt) is completely broken as defining `optimizeDeps` and `externals` still results in the same error when running the `build` step:

```shell
Cannot resolve "chromium-bidi/lib/cjs/bidiMapper/BidiMapper"
```

**Comment by ffxsam** [comment]
Genuine question that I hope the maintainers don't take the wrong way, but: do people test releases before publishing them? How did this make it into the wild?

**Comment by alexcroox** [comment]
Resolved this in Nuxt 3 config with:

```
nitro: {
  rollupConfig: {
    external: ['playwright-core'],
  },
```

**Comment by adamdehaven** [comment]
> Resolved this in Nuxt 3 config with:
> 
> ```
> nitro: {
>   rollupConfig: {
>     external: ['playwright-core'],
>   },
> ```

This doesn’t work for me; starts complaining about missing dependencies, `fs`, etc.

**Comment by abcirta** [comment]
Why is this closed ? bug still present in 1.49.0.

**Comment by adamdehaven** [comment]
> Closing as per above. Not sure if it is worth bringing up with the esbuild / vite folks to let them know that they could do a better job at detecting playwright as a server-side only import.

@pavelfeldman is this the end of the story? I've tried externalizing [as described above](https://github.com/microsoft/playwright/issues/33031#issuecomment-2525655565) as well as `optimizeDeps` but there doesn't appear to be a way around this when utilizing Vite.

**Comment by zach-betz-hln** [comment]
For what it's worth, our team has been bundling playwright for some time now. We use express + playwright to run a pdf-service (you give it an html string, it gives you a pdf). 

Here are some files for reference if it helps. We use yarn as package manager, so adapt to your needs. 

We use esbuild to bundle to cjs. Plus the change of `chromium-bidi` marked as external as [mentioned](https://github.com/microsoft/playwright/issues/33031#issuecomment-2404366111) above. 

<details>
<summary>esbuild.config.mjs</summary>

```js
import fs from 'node:fs';
import * as esbuild from 'esbuild';

// Only create source maps for our code. See https://github.com/nodejs/node/issues/41541#issuecomment-1457485140
const excludeVendorFromSourceMapPlugin = {
  name: 'excludeVendorFromSourceMapPlugin',
  setup(build) {
    const emptySourceMapAsBase64 = Buffer.from(JSON.stringify({ version: 3, sources: [''], mappings: 'A' })).toString(
      'base64'
    );
    build.onLoad({ filter: /node_modules.+\.(js|ts)$/ }, (args) => {
      return {
        contents: `${fs.readFileSync(args.path, 'utf8')}\n//# sourceMappingURL=data:application/json;base64,${emptySourceMapAsBase64}`,
        loader: 'default'
      };
    });
  }
};

console.log('Bundling code');

await esbuild.build({
  logLevel: 'info',
  plugins: [excludeVendorFromSourceMapPlugin],
  external: [
    './chromium/appIcon.png',
    './loader',
    // see https://github.com/microsoft/playwright/issues/33031#issuecomment-2404366111
    'chromium-bidi'
  ],
  entryPoints: ['./src/index.ts'],
  bundle: true,
  sourcemap: 'linked',
  sourcesContent: false, // omit the original source code. We only need sensible stack traces. See https://esbuild.github.io/api/#sources-content
  platform: 'node',
  format: 'cjs', // must correspond to the type field in package.json
  outfile: './dist/index.cjs'
});
```

</details>

<details>
<summary>Dockerfile</summary>

```dockerfile
# For all available image tags, see:
# https://mcr.microsoft.com/en-us/product/playwright/tags
ARG PLAYWRIGHT_IMAGE=mcr.microsoft.com/playwright:v1.50.0-noble

# hadolint ignore=DL3006
FROM ${PLAYWRIGHT_IMAGE} AS builder

ARG NODE_ENV=production

WORKDIR /home/pwuser/app

# Enable yarn
RUN corepack enable

COPY . .

# Install packages, do production build, run unit tests
RUN yarn install \
  && yarn build \
  && yarn test

# hadolint ignore=DL3006
FROM ${PLAYWRIGHT_IMAGE} AS final

WORKDIR /home/pwuser/app

ENV NODE_ENV=production
ENV TZ=America/New_York

# Tini is a container init system
# See https://github.com/krallin/tini
RUN apt-get update && \
  apt-get -y --no-install-recommends install tini=0.* && \
  rm -rf /var/lib/apt/lists/* && \
  apt-get clean

USER pwuser

# Only copy needed files
COPY --from=builder --chown=pwuser:pwuser /home/pwuser/app/dist /home/pwuser/app/dist

EXPOSE 4006

ENTRYPOINT [ "tini", "--" ]

CMD [ "node", "--enable-source-maps", "/home/pwuser/app/dist/index.cjs" ]
```

</details>

**Comment by coaxial** [comment]
This is still a problem, reverting to v1.47.2 fixes the issue for now.

**Comment by EthanQuarry** [comment]
This is still a problem using SST v2 reverting to 1.47.2 fixes the issue.

**Comment by StephenHaney** [comment]
Ran into this when using `bun build` to bundle for a docker file

For future searchers, since nobody gave an explicit bun fix yet, here is one way to get around it with bun:
`bun build **your build settings** --external electron --external chromium-bidi",`

**Comment by zach-betz-hln** [comment]
Bundle-related item: https://github.com/microsoft/playwright/issues/35479

**Comment by mediafreakch** [comment]
> Use the below at your own risk. We no longer bundle Playwright in our projects.

It would be very kind of you to let us know what you do instead... Do you install playwright in the docker image right away?

**Comment by zach-betz-hln** [comment]
Hi @mediafreakch our setup has some complexity that is irrelevant for this. 

But I created a [minimal repro](https://github.com/zach-betz-hln/mre-playwright-node-no-bundle) that shows the gist of how we do it. Basically:

- Use multi-stage builds for docker
- Create the production dependencies in one stage
- Use tsc to compile/build in another stage
- In the final stage, only copy the production dependencies and build output from the previous stages

**Comment by Alixhan** [comment]
I got same error on playwright  latest version v1.56.1,  And  use  `npm install chromium-bidi` fixed it.

**Comment by TheJaredWilcurt** [comment]
This worked for me:

`vite.config.js`

```js
import { defineConfig } from 'vite';

export default defineConfig({
  build: {
    rollupOptions: {
      external: [
        'playwright',
        'playwright-core'
      ]
    }
  },
  optimizeDeps: {
    exclude: ['chromium-bidi']
  }
});
```

**Comment by JaKeenan0922** [comment]
I was also experiencing this issue, but have since fixed it without changing vite config or downgrading that package (using 1.56.1). 

The root of the problem was that an import statement was causing vite to detect `playwright` (and eventually `playwright-core`) , which in our environment was causing vite to attempt to bundle them in advance. The issue with pre-bundling these dependencies is that the runtime dependency for `chromium-bidi`  looks on disk _immediately_ for that package, in its own (myPackage's) dependencies. Because we are using `pnpm` and we don't have `chromium-bidi` declared as a dependency, vite can't find it.


To show the problem more directly...
```typescript
// myPackage/tests/steps.ts or some other custom playwright testing file
import { createBdd } from 'playwright'

interface Foo {
  bar: string
}
```
If you then import that interface elsewhere, into a file that vite wants to build, i.e.
```vue
// myPackage/someFile.vue
<script setup lang="ts">
  import { Foo } from './tests/steps.ts' // Vite will go to the steps file, see the import from playwright at the top, and try to pre-bundle it.
 ...
</script>
```

The solution for us was to move an interface which was causing vite to see imports from playwright. I would imagine the same would apply to any other import statement which ultimately causes vite to detect playwright. In the above example, moving the `Foo` interface from the `steps.ts` file into say `myPackage/types.ts`, and then importing it from that `types.ts` into your `steps.ts` file would not trigger vite to see playwright.
