### ISSUE TITLE
couldn't locate on next button and click in this website, what should I do?

### ISSUE THREAD

**Issue by cobaltautomationdev** [microsoft/playwright#33058]
### Please do not submit this issue.

- [x] I understand

**Comment by cobaltautomationdev** [comment]
https://commerce.spscommerce.com/fulfillment/transactions/list/ , can any guys try to use playwright to locate next button after input email address. 
```
async def run(playwright: Playwright) -> None:
      browser = await playwright.chromium.launch(headless=False)
      context = await browser.new_context()
      page = await context.new_page()
      await page.goto("https://commerce.spscommerce.com/fulfillment/transactions/list/")
   
      await page.get_by_label("Email Address").fill("xxxx@test.com")
      await page.get_by_label("Remember Me").check()
      await page.get_by_role("button", name="Next").click() 
```

**Comment by johnnygerard** [comment]
Playwright has features to help locate elements on the page (see [Generating locators](https://playwright.dev/docs/codegen#generating-locators)).

**Comment by johnnygerard** [comment]
It's hard to help you without knowing what your issue is.

Do you have an error message?

**Comment by johnnygerard** [comment]
I just realized that you used the "Questions and Help 💬" template to submit an issue. You are not supposed to do that. Also, using multiple accounts is also not ideal for communication.

Good luck!

**Comment by yonglee7015** [comment]
Apologies, I forgot to switch accounts. I'm reaching out for assistance with an issue I'm encountering: despite using the provided code, I'm unable to click the 'Next' button. I would greatly appreciate any help with this matter. The code is provided by code gen.When run,it does not work as expected.You can test with the website,you will get my point.

**Comment by pavelfeldman** [comment]
Does not look like a bug report or a feature request, closing

**Comment by cobaltautomationdev** [comment]
Please don't close this just yet. You can try entering a dummy email address and then click the 'Next' button. The key is to ensure that you're able to proceed by clicking 'Next.' If you encounter any issues, it might be a bug with Playwright. Let's verify this step to confirm. Have you tried it already? Please don't overlook this important point.

**Comment by cobaltautomationdev** [comment]
add await page.wait_for_load_state() before next button solve this issue
