### ISSUE TITLE
[Regression]: Inspector not showing recorded steps

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#33052]
### Last Good Version

1.47.2

### First Bad Version

1.48.0

### Steps to reproduce

```
import { test, expect } from "@playwright/test";

test.only("has title", async ({ page }) => {
  await page.goto("https://playwright.dev/");

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);
});
```

- Run the above test using `npx playwright test --debug`
- Step through `page.goto` step of the step
- Click "Record" button on the inspector
- Now click around the website.

### Expected behavior

The recorded steps should be generated in the inspector

### Actual behavior

The recorded steps are not generated in the inspector.

https://github.com/user-attachments/assets/7ec62407-a299-407b-b777-fe93be3ecffe

### Additional context

Tried this in a fresh project using `npm init playwright@latest`

### Environment

System:
    OS: macOS 15.0
    CPU: (12) arm64 Apple M3 Pro
    Memory: 1.18 GB / 36.00 GB
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
  IDEs:
    VSCode: 1.94.0 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.48.0 => 1.48.0

**Comment by pavelfeldman** [comment]
While we are fixing this, select a different language back and forth.
