### ISSUE TITLE
[Regression]: Playwright tests failing with timeout on page.goto after multiple redirections in Docker images > 1.42.1 in CI environment

### ISSUE THREAD

**Issue by rakesh25** [microsoft/playwright#33056]
### Last Good Version

1.42.1

### First Bad Version

1.43.1

## Description

Our end-to-end integration tests using Playwright are failing in our CI environment (CircleCI) when using Docker images of Playwright versions greater than 1.42.1. The issue occurs during the authentication step, which involves multiple redirections.

## Current Behavior

- Tests run successfully with Playwright Docker images up to and including version 1.42.1.
- With Playwright Docker images version 1.43.1 and above, all tests fail due to a timeout on `page.goto`.
- The `page.goto` directive times out after 30000ms when attempting to navigate to the webpage after multiple redirections. I have tried increasing timeouts, but it still did not help.

## Expected Behavior

The tests should successfully navigate through the authentication process, including multiple redirections, without timing out, as it happens with versions <= 1.42.1

## Actual behavior

- Tests run successfully with Playwright Docker images up to and including version 1.42.1.
- With Playwright Docker images version 1.43.1 and above, all tests fail due to a timeout on `page.goto`.
- The `page.goto` directive times out after 30000ms when attempting to navigate to the webpage after multiple redirections.

## Steps to Reproduce

1. Set up a Playwright test suite that includes an authentication step with multiple redirections.
2. Run the tests using a Playwright Docker image version 1.42.1 or earlier (tests pass while performing auth).
3. Run the same tests using a Playwright Docker image version 1.43.1 or later (tests fail while performing auth).

## Questions

1. Are there any known issues or changes in Playwright versions > 1.42.1 related to handling multiple redirections?
2. Are there any recommended best practices for handling authentication with multiple redirections in newer Playwright versions?

Any assistance or insights into this issue would be greatly appreciated. Thank you!

### Additional context

- We have verified that there are no connectivity issues to the internal auth endpoint.
- DNS resolution and network connectivity checks have been added to the CircleCI config and pass successfully.
- The issue seems to be specific to the authentication process and the handling of multiple redirections in newer Playwright versions.

### Environment

System information:
 Server Version: 18.09.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
 Cgroup Driver: cgroupfs
 Kernel Version: 5.4.0-1101-aws
 Operating System: Ubuntu 18.04.6 LTS
 OSType: linux
 Architecture: x86_64

Starting container ****/microsoft-remote/playwright:v1.42.1-focal
  image cache not found on this host, downloading ****/microsoft-remote/playwright:v1.42.1-focal
v1.42.1-focal: Pulling from microsoft-remote/playwright
3c67549075b6: Pull complete 
8ebadfa11d09: Pull complete 
1c09ec141080: Pull complete 
f010283f57f1: Pull complete 
Digest: sha256:0c44a93f50ae181849b83d0f71c18b45c400ff990df16c269a8fbdc2470cfeff
Status: Downloaded newer image for ****/microsoft-remote/playwright:v1.42.1-focal
****/microsoft-remote/playwright:v1.42.1-focal:
  using image ****/microsoft-remote/playwright@sha256:0c44a93f50ae181849b83d0f71c18b45c400ff990df16c269a8fbdc2470cfeff
  pull stats: download 686MiB in 4.151s (165.2MiB/s), extract 685.9MiB in 12.32s (55.67MiB/s)
  time to create container: 16.102s
Time to upload agent and config: 816.55431ms
Time to start containers: 361.399225ms

**Comment by pavelfeldman** [comment]
We can't act on this issue based on the description alone. Please file an issue that we can reproduce locally.
