### ISSUE TITLE
[Question] Test timeout of 30000ms exceeded in WebKit with Playwright.

### ISSUE THREAD

**Issue by bbchuoo** [microsoft/playwright#33055]
Node Version：20.18.0
Operating system：Windows 10
 "@playwright/test": "^1.48.0",

I created a project using Vue's official Quick Start with `npm create vue@latest`.
For e2e testing, I chose Playwright and initialized it using `npm init playwright@latest`.
In theplaywright.config.ts  , I set `testDir: './tests',`.
When I run `npx playwright test --ui`, it works fine in Chromium and Firefox, but I encounter an error in WebKit.
 
```
Test timeout of 30000ms exceeded.
@
example.spec.ts:4
Error: page.goto: Test timeout of 30000ms exceeded.
Call log:
  - navigating to "[https://playwright.dev/"](https://playwright.dev/%22), waiting until "load"
```
 
Here is my test script `tests/example.spec.ts`
 
```
import { test, expect } from '@playwright/test';
 
test('has title', async ({ page }) => {
  await page.goto('[https://playwright.dev/');](https://playwright.dev/%27);)
 
  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);
});
 
test('get started link', async ({ page }) => {
  await page.goto('[https://playwright.dev/');](https://playwright.dev/%27);)
 
  // Click the get started link.
  await page.getByRole('link', { name: 'Get started' }).click();
 
  // Expects page to have a heading with the name of Installation.
  await expect(page.getByRole('heading', { name: 'Installation' })).toBeVisible();
});
 
```

As mentioned above, I didn't make any code modifications and only used the official example. However, it doesn't work in WebKit. Please help me. Thank you.

I checked the ms-playwright folder and confirmed that there is a webkit-2083 folder.

**Comment by bbchuoo** [comment]
Node Version：20.18.0
Operating system：Windows 10
 
I created a project using Vue's official Quick Start with `npm create vue@latest`.
For e2e testing, I chose Playwright and initialized it using `npm init playwright@latest`.
In theplaywright.config.ts  , I set `testDir: './tests',`.
When I run `npx playwright test --ui`, it works fine in Chromium and Firefox, but I encounter an error in WebKit.
 
```
Test timeout of 30000ms exceeded.
@
example.spec.ts:4
Error: page.goto: Test timeout of 30000ms exceeded.
Call log:
  - navigating to "[https://playwright.dev/"](https://playwright.dev/%22), waiting until "load"
```
 
Here is my test script `tests/example.spec.ts`
 
```
import { test, expect } from '@playwright/test';
 
test('has title', async ({ page }) => {
  await page.goto('[https://playwright.dev/');](https://playwright.dev/%27);)
 
  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);
});
 
test('get started link', async ({ page }) => {
  await page.goto('[https://playwright.dev/');](https://playwright.dev/%27);)
 
  // Click the get started link.
  await page.getByRole('link', { name: 'Get started' }).click();
 
  // Expects page to have a heading with the name of Installation.
  await expect(page.getByRole('heading', { name: 'Installation' })).toBeVisible();
});
 
```

As mentioned above, I didn't make any code modifications and only used the official example. However, it doesn't work in WebKit. Please help me. Thank you.

**Comment by pavelfeldman** [comment]
Does not look like a bug report or a feature request, closing

**Comment by bbchuoo** [comment]
> Does not look like a bug report or a feature request, closing

I found the issue. Setting up a proxy resolved it. If anyone else is facing the same problem, check if your network requires a proxy.
 Thank you.
