### ISSUE TITLE
[BUG] Docs for version=master broken (Missing Sidebar Content)

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#3305]
## master (https://playwright.dev/#version=master)

<img width="937" alt="Screen Shot 2020-08-05 at 10 33 02 AM" src="https://user-images.githubusercontent.com/11915034/89444814-21cc4700-d707-11ea-8029-8d5404092f02.png">

## 1.2.1 (https://playwright.dev/#version=v1.2.1)

<img width="864" alt="Screen Shot 2020-08-05 at 10 32 54 AM" src="https://user-images.githubusercontent.com/11915034/89444797-1c6efc80-d707-11ea-98a5-b1ff1a56063e.png">

**Comment by arjun27** [comment]
Should be fixed now (might need a hard reload as we updated the site): https://playwright.dev/#version=master

**Comment by rwoll** [comment]
Thanks @arjun27! It took a hard reload. New styling looks nice! ✨ 👀
