### ISSUE TITLE
[Feature]: Ability define basic api sanitizing

### ISSUE THREAD

**Issue by twalshOG** [microsoft/playwright#33069]
### 🚀 Feature Request

It would be to be able to set some basic trace sanitization rules.
The trace files are awesome, but some of the header data can be a security concern.

### Example

What configuring this may look like in the playwright.config.ts
```ts
    /* 
    Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer 
    If retries are set capture trace on first retry, otherwise just retain on failure
    */
    trace: retryNumber > 0 ? 'on-first-retry' : 'retain-on-failure',

    // Headers to sanitize in trace
    // There may be a better implementation, but this gets the idea across
    traceHeadersSanatisation: [
      'auth',
      'token',
      'jwt',
      'api-key',
      'basic',
      'cookie',
      'set-cookie',
    ],

```

What this would look like in the trace viewer 
![Image](https://github.com/user-attachments/assets/c957a3b8-12c3-4d56-b19c-b7da61c0d188)

Very bad/hack code that shows how this could be done in the [recorder](https://github.com/microsoft/playwright/blob/e4b0d5e6dd05d774c4d7dea239d7dc20571c083b/packages/playwright-core/src/server/trace/recorder/tracing.ts#L407) code
``` js
  onEntryFinished(entry) {
    this._pendingHarEntries.delete(entry);
    // Get these from the playwright.config.ts somehow
    // Sensitive header values
    for (const headerKey in entry.request?.headers) {
      const keyName = entry.request.headers[headerKey].name;
      if (this._sensitiveKeys.includes(keyName.toLowerCase())) {
        entry.request.headers[headerKey] = { name: keyName, value: '**********' };
      }
    }

    for (const headerKey in entry.response?.headers) {
      const keyName = entry.response.headers[headerKey].name;
      if (this._sensitiveKeys.includes(keyName.toLowerCase())) {
        entry.response.headers[headerKey] = { name: keyName, value: '**********' };
      }
    }

    const event = {
      type: 'resource-snapshot',
      snapshot: entry
    };
    const visited = visitTraceEvent(event, this._state.networkSha1s);
    this._fs.appendFile(this._state.networkFile, JSON.stringify(visited) + '\n', true /* flush */);
  }
```

### Motivation

Reduce security risk

**Comment by pavelfeldman** [comment]
It is nearly impossible to sanitize the trace to remove sensitive data - it can be present in headers, payloads, exist in some form in DOM, etc. It can be plain or encoded (base64, etc). Any generic means of trace sanitization would be compromising the user, so we strongly suggest that the level of access to the trace should match that of the access to the secrets used during the testing process.
