### ISSUE TITLE
[Feature]: Ability to pause logging

### ISSUE THREAD

**Issue by twalshOG** [microsoft/playwright#33068]
### 🚀 Feature Request

Would be nice to be able to disable logging for a short time when dealing with especially sensitive data.

### Example

Not 100% about the ideal implementation, but something like this would be nice

``` ts
  test('Simple example test', {tag: TAGS.EXAMPLE2}, async ({page, context}) => {
    await page.goto('https://https://playwright.dev/FAKELOGIN');
    await page.getByTestId('userName').fill('Ted');

    ///// *** Something like this *** //////
    context.logging.pause(); // Pause logging to avoid logging the password
    await page.getByLabel('password').fill('secret-password');
    context.logging.unpause(); // Start capturing logs again
    ///// *** Something like this *** //////

    await page.getByLabel('loginButton').click();
    await expect(page).toHaveURL(
      `https://https://playwright.dev/FAKE/HomePage.html`,
    );
  });
```

What this may look like the HTML report
![Image](https://github.com/user-attachments/assets/86f56afc-65a1-4f92-92dd-ed152d2617f3)

### Motivation

Reduce risk of leaking credentials or other sensitive data.

**Comment by Nav-2d** [comment]
Related: https://github.com/microsoft/playwright/issues/19992

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/33069
