### ISSUE TITLE
[BUG] Browser.version is missing from the types.d.ts

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#3306]

**Comment by pavelfeldman** [comment]
Also, BrowserType is a template in types.d.ts

**Comment by dgozman** [comment]
> Also, BrowserType is a template in types.d.ts

That was on purpose, so that `chromium.launch()` yields a `ChromiumBrowser`.

**Comment by JoelEinbinder** [comment]
@pavelfeldman this was just not rebuilding the types right?
