### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by sathikari** [microsoft/playwright#33072]
### Version

1.44.1

### Steps to reproduce

I am using Playwright with TypeScript. Within my spec file, I have a single test.describe that contains multiple tests, each representing a part of a broader scenario. In playwright, as soon as the first test passes, the overall test is marked as passed, even though the subsequent tests in the spec continue to run until completion. My goal is to have a test pass or fail status for the entire spec only after all the tests within the describe have finished executing. Is there a way to achieve this ?

### Expected behavior

To have have the test either pass or fail upon completion of all the tests within a describe of a single spec file.

### Actual behavior

Reports for every test within a describe

### Environment

Mac book pro and CI

**Comment by pavelfeldman** [comment]
There is no such feature. You could stop using serial mode (which is discouraged) and migrate to test steps instead of serial tests. Then you would have just one test that either passes or fails.
