### ISSUE TITLE
[Bug]: Headed mode doesn't work with UI mode

### ISSUE THREAD

**Issue by hmayak-im** [microsoft/playwright#33084]
### Version

1.48.0

### Steps to reproduce

Run test with '--ui --headed' options
Observe the run 

### Expected behavior

Browser should be opened with headed mode, like in previous versions.
https://github.com/user-attachments/assets/410c5002-a90e-4ff1-8a7b-485919b8eff1

### Actual behavior

The browser does not appear when running tests in UI mode, even though headed mode is enabled.
https://github.com/user-attachments/assets/f7acedb9-adeb-407f-9606-6f5ce5950dba

### Environment

  System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-1235U
    Memory: 15.23 GB / 31.69 GB
  Binaries:
    Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 4.3.0 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Bash: 5.1.16 - C:\WINDOWS\system32\bash.EXE
  Playwright - version 1.48.0

also checked in
 
OS: Mac 13.5.1
Playwright Version: 1.48.0
Node.js Version: v20.14.0

**Comment by dmcweeney** [comment]
+1
