### ISSUE TITLE
[Bug]: --grep '@tagged' behaves differently for single test and groups when including trailing whitespaces

### ISSUE THREAD

**Issue by tziegler-tud** [microsoft/playwright#33090]
### Version

1.47.1

### Steps to reproduce

1. Annotate a single test with some tag `'@tagged'`
`test('Singe test', { tag: '@tagged' }, async ({ page }) => { ... })`

2. Annotate a group of tests with the same tag` '@tagged'`
`test.describe("TestGroup", { tag: '@tagged' }, ()=> { test("groupMember1", async ({ page }) => { ... })   })`

4. run `npx playwright test --grep '@tagged'` --> All tests run as expected

5. run `npx playwright test --grep '@tagged '` (note the trailing whitespace) --> unexpected behaviour

### Expected behavior

The expected behaviour when using quoted strings` '@tagged ' ` including whitespaces with --grep is not documented, but I expect that either **all** tests or **none** of the tests are run.

### Actual behavior

The group of tests with tag `'@tagged'` will be run, whilst the single test with tag `'@tagged'` will not be run.

### Environment

System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (16) x64 AMD Ryzen 7 8845HS w/ Radeon 780M Graphics
    Memory: 50.82 GB / 60.62 GB
    Container: Yes
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
  Languages:
    Bash: 5.2.21 - /bin/bash
  npmPackages:
    @playwright/test: ^1.48.0 => 1.47.1 
    playwright-slack-report: ^1.1.82 => 1.1.85

**Comment by dgozman** [comment]
As explained [in the docs](https://playwright.dev/docs/test-cli#reference):

> The regular expression will be tested against the string that consists of the project name, test file name, test.describe titles if any, test title and all test tags, separated by spaces, e.g. `chromium my-test.spec.ts my-suite my-test @smoke`

In this example, the standalone test will be something like `chromium example.spec.ts Singe test @tagged`, while the test inside a describe would be `chromium example.spec.ts TestGroup @tagged groupMember1`. Therefore, the former does not match `@tagged ` with a space, while the latter does.

Let me know whether the above helps.

**Comment by zaferduydu** [comment]
Hi @dgozman , i have two tests cases.

first one:
test('first test case', { tag: ['@store-operations', '@brand', '@4814'] }, async ({  }) => {});

second one:
test('second test case', { tag: ['@store-operations', '@store', '@4944'] }, async ({  }) => {});

I want to run tests tagged as @store. When I use the following command, 2 tests are running, but only 1 scenario is marked as @store.

npx playwright test --grep @store

**Comment by dgozman** [comment]
@zaferduydu Similarly, the grep regular expression `@store` equally matches the both tests, because each of them has `@store-operations` tag as a part of the full title. I'd recommend to not use tags that start with another tag.

**Comment by zaferduydu** [comment]
@dgozman is there any way to run scenarios only marked as **@store**?

**Comment by tziegler-tud** [comment]
> As explained [in the docs](https://playwright.dev/docs/test-cli#reference):
> 
> > The regular expression will be tested against the string that consists of the project name, test file name, test.describe titles if any, test title and all test tags, separated by spaces, e.g. `chromium my-test.spec.ts my-suite my-test @smoke`
> 
> In this example, the standalone test will be something like `chromium example.spec.ts Singe test @tagged`, while the test inside a describe would be `chromium example.spec.ts TestGroup @tagged groupMember1`. Therefore, the former does not match `@tagged ` with a space, while the latter does.
> 
> Let me know whether the above helps.

Thanks for your answer, @dgozman ! That explains it nicely.

**Comment by dgozman** [comment]
> [@dgozman](https://github.com/dgozman) is there any way to run scenarios only marked as **@store**?

Not a generic one. Try coming up with a regex that would match `@store` but not `@store-operations`. Something like `npx playwright test --grep "/@store[^-]/"`

Closing this issue since there is no action item for Playwright.
