### ISSUE TITLE
[Bug]: Set array data directly to fixture property does not work on 1.48 ( and 1.47, 1.46)

### ISSUE THREAD

**Issue by toannguyen83** [microsoft/playwright#33103]
### Version

1.48

### Steps to reproduce

Fixture file: `example-fixture.ts`
```ts
import { test as base } from '@playwright/test';

const arrayData = [
    { name: 'Alice', age: 25 },
    { name: 'Bob', age: 30 },
    { name: 'Charlie', age: 35 },
]

type TestFixture = {
    jsonArray: typeof arrayData
}

export const test = base.extend<TestFixture>({
    // BUG - setting array data directly to fixture property does not work
    // it takes the object of the first array element
    jsonArray: arrayData
})
```
Test file: `example.spec.ts`
```ts
import {test} from './example-fixture'
import { expect } from '@playwright/test';

test('test', async ({ jsonArray  }) => {
  console.log(jsonArray)
  expect(Array.isArray(jsonArray)).toBeTruthy()
});
```

On the fixture file, I set a fixture array data directly to the property instead of `await use()`, and this is no longer working on 1.48, 1.47, 1.46. Currently it's taking the first object in the array data and assign it as fixture data instead of using the entire array.

When I fall back to 1.45.3 version, this behavior is working correctly.

**Replication**
I have the following sample test project will fail on version 1.48. 
[playwright-bug-array-data.zip](https://github.com/user-attachments/files/17369924/playwright-bug-array-data.zip)

### Expected behavior

Screenshot version **1.45.3** showing all array data stored in variable

![Image](https://github.com/user-attachments/assets/31739297-0dde-4777-adac-8afbb72b9d60)

### Actual behavior

Screenshot version **1.48** showing json array variable only show as one object

![Image](https://github.com/user-attachments/assets/001de924-97ca-40d0-937a-7e32467c026d)

### Additional context

**Workaround**
Use `await use()` instead of assigning data directly to the to the fixture property.

```ts
export const test = base.extend<TestFixture>({
    jsonArray: async ({}, use) => {
      await use(arrayData)
    }
})
```

### Environment

System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 16.11 GB / 31.92 GB
  Binaries:
    Node: 20.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.94.2 - C:\Users\toan\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.45.3 => 1.45.3

**Comment by mxschmitt** [comment]
This was a breaking change in v1.46.0 - see [here](https://github.com/microsoft/playwright/releases#:~:text=Possibly%20breaking%20change) for the release notes / a workaround.

**Comment by toannguyen83** [comment]
Thank you @mxschmitt I'll check out the workaround and close the issue.
