### ISSUE TITLE
[BUG] Website throws exception before rendering

### ISSUE THREAD

**Issue by mrkev** [microsoft/playwright#3310]
**Context:**
- Browser: Chrome, macOS 10.15.5 (19F101)

**Describe the bug**

I'm trying to learn more about playwright, but I'm having a hard time since the website shows a blank page when I try to load it. The error:

```
Uncaught (in promise) TypeError: Cannot read property 'map' of null
    at L._initialize (main.js:19)
    at async Function.create (main.js:19)
    at /async https:/playwright.dev/main.js:39
```

<img width="1564" alt="Screen Shot 2020-08-05 at 2 29 45 PM" src="https://user-images.githubusercontent.com/1285131/89455674-4be23100-d728-11ea-9d71-1c9fcc466cff.png">

**Comment by arjun27** [comment]
@mrkev, thanks for reporting. The docs download content from github, and it looks like the github API failed in this case. Would it be possible for you to show the devtools network tab to help confirm?

cc @aslushnikov

**Comment by mxschmitt** [comment]
FYI: I experienced also some CORS issues on the site from time to time over the past few months. Very randomly.

**Comment by mrkev** [comment]
Ah, I can't repo anymore. Now it's consistently working. Good news, but unfortunate for debugging.

**Comment by arjun27** [comment]
Thanks for checking. I’ve created #3318 for a long term fix
