### ISSUE TITLE
[Feature]: Change uuid naming in data folder for trace

### ISSUE THREAD

**Issue by yusufozturk-via** [microsoft/playwright#33116]
### 🚀 Feature Request

![Image](https://github.com/user-attachments/assets/379df2e2-785f-4cf5-939d-ca220a3e967b)

In the playwright.config.ts file, when trace: 'retain-on-failure' is set, after downloading the report in GitHub, the errors are saved under the data folder with names based on UUIDs. Wouldn’t it make more sense to use test names instead of UUIDs? This way, I could directly identify which error belongs to which test. For example, if I only want to check one out of 20 errors, I currently have to open each one to find it. Using test names would make this process much easier.Or there ia an option for this?

### Motivation

Using test names would make this process much easier

**Comment by dgozman** [comment]
@yusufozturk-via The internals of html report are not meant for manual consumption. I'd recommend opening the report and then clicking on the trace icon for the test you are interested in. Let me know whether that works for you. If not, please explain why in details.

**Comment by yusufozturk-via** [comment]
@dgozman Yes, you’re right, but you mean when running it locally. After running the tests on GitHub and downloading the report as an artifact, when I open the HTML report and click on the trace icon, I get a warning like in the screenshot. I can only see the trace by going to https://trace.playwright.dev/, clicking ‘Select File’, and choosing one of the errors under the data folder. However, since the UUIDs are used, I can’t understand which error belongs to which case.
![Image](https://github.com/user-attachments/assets/3dac0dc2-3ff9-43d8-b161-3fb1b74f5497)

**Comment by dgozman** [comment]
You should open the report locally with `npx playwright show-report`. See [this doc](https://playwright.dev/docs/ci-intro#viewing-the-html-report) for more details. Let me know whether that helps.

**Comment by yusufozturk-via** [comment]
@dgozman  thanks got it now.We can close
