### ISSUE TITLE
[Feature]: Toggle button feature

### ISSUE THREAD

**Issue by ermi1968** [microsoft/playwright#33118]
### 🚀 Feature Request

I am testin an application in Chrome. In the beigning it was a button and we have change the button to be a Toggle button. My old test are failing and when i try to rewright my test I couldnt find and support i Playwright frame work. This is a great help if you add this feature.

Thank you
Ermias

### Example

It is going to be more in mobile application and in web browser. Playwright have many support for Radio, checkbox, scrolling... but Toggle button is missing. 

### Motivation

Playwright have many support for Radio, checkbox, scrolling... but Toggle button is missing.

**Comment by dgozman** [comment]
We need more information to act on this issue. There is no such thing as a native "toggle button", so perhaps you should just click? Could you please provide a repro that we can run locally?

**Comment by manimovassagh** [comment]
You can already handle toggle buttons in Playwright using the existing click() method, combined with checking the button’s state using attributes like aria-pressed or checked. Here’s an example of how you can rewrite your test for a toggle button:

```
const toggleButton = page.locator(’#toggleButton’);
const isToggledOn = await toggleButton.getAttribute(‘aria-pressed’);
await toggleButton.click();
const isToggledAfterClick = await toggleButton.getAttribute(‘aria-pressed’);
```

**Comment by manimovassagh** [comment]
> ### 🚀 Feature Request
> I am testin an application in Chrome. In the beigning it was a button and we have change the button to be a Toggle button. My old test are failing and when i try to rewright my test I couldnt find and support i Playwright frame work. This is a great help if you add this feature.
> 
> Thank you Ermias
> 
> ### Example
> It is going to be more in mobile application and in web browser. Playwright have many support for Radio, checkbox, scrolling... but Toggle button is missing.
> 
> ### Motivation
> Playwright have many support for Radio, checkbox, scrolling... but Toggle button is missing.

You can already handle toggle buttons in Playwright using the existing click() method, combined with checking the button’s state using attributes like aria-pressed or checked. Here’s an example of how you can rewrite your test for a toggle button:

```
const toggleButton = page.locator(’#toggleButton’);
const isToggledOn = await toggleButton.getAttribute(‘aria-pressed’);
await toggleButton.click();
const isToggledAfterClick = await toggleButton.getAttribute(‘aria-pressed’);
```

**Comment by manimovassagh** [comment]
@ermi1968 
You can already handle toggle buttons in Playwright using the existing click() method, combined with checking the button’s state using attributes like aria-pressed or checked. Here’s an example of how you can rewrite your test for a toggle button:

```
const toggleButton = page.locator(’#toggleButton’);
const isToggledOn = await toggleButton.getAttribute(‘aria-pressed’);
await toggleButton.click();
const isToggledAfterClick = await toggleButton.getAttribute(‘aria-pressed’);
```

**Comment by ermi1968** [comment]
@manimovassagh Thank you for your tips and I adapt my code as you suggested and it is working fine .
