### ISSUE TITLE
[BUG] config.webServer cannot start newer versions of Storybook using Ubuntu agent inside Azure pipelines

### ISSUE THREAD

**Issue by natalia-gurevich** [microsoft/playwright#33126]
**Problem:**

config.webServer cannot start Storybook version 7+ using Ubuntu Azure pipeline, but it works with Windows agents in Azure pipelines or when Storybook version is lower than 7

**Context:**

1. config.webServer is set to start Storybook to run the tests against it later

```
const config = {
	...
	webServer: {
		command: 'npx pnpm run start',
		url: 'http://localhost:6006/',
		timeout: 120000,
	}
...
};

where 'npx pnpm run start' is set to start storybook ("start": "pnpm storybook")
``` 

2. Fail Storybook version: **7+**
3. Fail environment: Azure cloud pipelines, **Ubuntu** agent
4. "playwright": "^1.45.3", "@playwright/test": "^1.45.3",
5. Node.js v18.20.4 (tried other versions too, didn't help)

**Description:** 

We used to be running the project with Azure pipelines, using Ubuntu agent, and it was all working fine until we updated Storybook to version 7 (and higher). After the update, our Azure Ubuntu agent started returning the error below. 

We're able to run it with Azure pipelines, using Windows. Locally it works fine for Windows and MacOS, unfortunately there is no possibility to test Ubuntu now.

**Error**:
```
[WebServer] /home/vsts/work/1/s/node_modules/.pnpm/storybook@8.2.6_@babel+preset-env@7.25.0_@babel+core@7.24.9_/node_modules/storybook/bin/index.cjs:23
  throw error;
  ^

Error: spawn none ENOENT
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at __node_internal_errnoException (node:internal/errors:623:12)
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:290:12)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn none',
  path: 'none',
  spawnargs: [ 'http://localhost:6006/' ]
}

Node.js v18.20.4
Error: Process from config.webServer was not able to start. Exit code: 7
```

Any help/suggestions would be greatly appreciated, sorry in advance if this is not a Playwright issue and I'm supposed to reach out to Storybook

**Comment by dgozman** [comment]
I think this is a Storybook issue. It looks like it tries to open the url, probably in the browser, and fails to do so. Looks similar to https://github.com/storybookjs/storybook/issues/24191 on the first glance. I'd recommend to try your luck on the storybook issue tracker. Thank you for filing!

**Comment by natalia-gurevich** [comment]
Thank you very much for the suggestion @dgozman , we were able to use the solution from [the bug](https://github.com/storybookjs/storybook/issues/24191) you referred me to.
Specifically for the playwright situation in our project the solution would look like:

```
install [kentcdodds/cross-env](https://github.com/kentcdodds/cross-env),
and make the playwright script look something like:

"testPlaywright": "cross-env BROWSER=true playwright test"
```
