### ISSUE TITLE
[Docs]: Is documentation available as a pdf file?

### ISSUE THREAD

**Issue by Tony20221** [microsoft/playwright#33129]
### Page(s)

Is documentation available as a pdf file?
I would like to read it on an ereader like the Kindle.

### Description

Is documentation available as a pdf file?
I would like to read it on an ereader like the Kindle.

**Comment by dgozman** [comment]
@Tony20221 The documentation is only available online on [playwright.dev](https://playwright.dev/). Sorry for the inconvenience!
