### ISSUE TITLE
[Feature]: Enable WebKit to Launch Maximized or Custom Viewports at Top-Right Corner

### ISSUE THREAD

**Issue by SparshKesari** [microsoft/playwright#33135]
### 🚀 Feature Request

Enable WebKit browsers to launch with a **maximized viewport** or a **custom viewport size** positioned at the **top-right corner** of the screen, preventing them from opening at random X and Y coordinates. This issue occurs both when using the `--start-maximized` argument and when setting a custom viewport size, leading to unpredictable window placements. This behavior contrasts with Chrome, Chromium-based browsers (e.g. Edge), and Firefox, which handle maximized and custom viewports correctly.

### Example

Current Behavior:
The WebKit browser opens with a maximized viewport or a specified custom size but appears at varying X and Y coordinates across runs.

Webkit:
![Image](https://github.com/user-attachments/assets/33953306-7b1c-460a-9593-78f8630c015f)

### Motivation

This feature will address inconsistencies in WebKit browser launches. In visual and UI regression testing, random positioning can skew test results or interfere with screenshots. This enhancement will be helpful for automated workflows and cloud-based testing infrastructure and will provide us with consistent and seamless results across the board.

**Comment by dgozman** [comment]
Merging into #4046 as a "launch maximized" request.
