### ISSUE TITLE
How to make "runDevServer" run for @playwright/experimental-ct-vue?

### ISSUE THREAD

**Issue by azollai** [microsoft/playwright#33134]
When I use @playwright/experimental-ct-vue, before running the tests it builds the whole project.
I can see in the implementation that if the devServer was running for , then it wouldn't make the build.
My question is how to trigger the runDevServer method before running the tests? Possibly from another command? It would make testing much faster for me. Meaning https://github.com/microsoft/playwright/blob/main/packages/playwright-ct-core/src/vitePlugin.ts#L79

P.s. It is not really an issue but a question. Excuse me if I created on the wrong platform.

**Comment by dgozman** [comment]
@azollai Try running `npx playwright dev-server -c playwright-ct.config.ts`. Let me know whether that helps.

**Comment by azollai** [comment]
@dgozman Yes that is exactly what I am looking for, thank you!
