### ISSUE TITLE
[Feature]: Label screenshots made in playwright with test file name

### ISSUE THREAD

**Issue by mastrzyz** [microsoft/playwright#33143]
### 🚀 Feature Request

Append the sanitized test name to the automatic screenshot mechanism of Playwright.

Why?

Currently the names are very generic and cause conflicts in CI/CD Systems like Azure Devops when we have multiple jobs failing with the same generic name:

![Image](https://github.com/user-attachments/assets/a7f5be1d-c40b-4706-89af-adc997ff73ed)

It's also not very clear which number responds to which testcase when we are able to upload:

![Image](https://github.com/user-attachments/assets/0e855faf-ed2d-4635-bc32-d73981ce0d3a)

### Example

Fix!

Added the sanitized file name, a good example of how this looks like are the fixed unit tests :

![Image](https://github.com/user-attachments/assets/4f1bc264-a4fa-47bd-8c69-efd2b54c0e60)

This will allow us to find the artifact easier and not conflict in CI/CD systems like in Azure Devops

### Motivation

This is purely a CI/CD Improvement for Playwright integration for us, we have a massively parallel system running hundreds of tests across multiple shards

**Comment by dgozman** [comment]
@mastrzyz Thank you for filing the issue!

Don't you have the same problem with traces, all named `trace.zip`? It seems like the better solution is to update your reporter to include the test name in any attachments it generates, since these are presented as a plain list, not grouped by test.

**Comment by mastrzyz** [comment]
Sorry @dgozman , I'm not using any custom reporter and relying on the existing Playwright reporters which are outputting trace.zip and screenshot1.png.

**Comment by dgozman** [comment]
@mastrzyz In this case, why do you only focus on the screenshots? I'd think that `trace.zip` would be equally important. Do I miss something?

If I understand correctly, you are using `junit` reporter that is uploaded to Azure DevOps [through this task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-test-results-v2), don't you? Perhaps we can improve that part instead? Why does it not show the full attachment path? Reading [this post](https://devblogs.microsoft.com/devops/junit-attachments-support-for-publish-test-results/), I would think the full attachment path that already includes test path could be shown. Not to mentioning that it's a part of the specific test output.

**Comment by mastrzyz** [comment]
You know to tell you the truth, why don't I see this failure for trace.zip!

![Image](https://github.com/user-attachments/assets/bc7cff0e-8d4b-46f8-af19-e21a2c132dd5)


Could it be that trace.zip is only one? we have retries enabled so I wonder if we take screenshots in first attempt and then seccond also takes and collides

**Comment by dgozman** [comment]
@mastrzyz Perhaps you should set both `trace` and `screenshot` to `'on-first-retry'`?

**Comment by mastrzyz** [comment]
We do not enable retries in this pipeline unfortunately

**Comment by mastrzyz** [comment]
: { trace: "on-first-retry", video: "on-first-retry" }), yeah we have that already

**Comment by dgozman** [comment]
> ```
>   : { trace: "on-first-retry", video: "on-first-retry" }), yeah we have that already
> ```

Sorry, I do not quite understand. The snippet does not show the `screenshot` setting. I *think* that if you set it to `on-first-retry` similarly to trace/video, your warnings will disappear. Could you please check that?

**Comment by mastrzyz** [comment]
@dgozman , I don't think that is possible -> ![Image](https://github.com/user-attachments/assets/b3a02410-2727-4a18-9c6a-ff4536538bf4)


but I Get what you mean, this would solve it

**Comment by dgozman** [comment]
@mastrzyz Indeed, my mistake. I think we can introduce `screenshot: 'on-first-failure'` mode that would limit the total number of screenshots per test to one, and most likely fix your issue.

**Comment by mxschmitt** [comment]
Linking https://github.com/microsoft/playwright/issues/30701

**Comment by mastrzyz** [comment]
Yep @dgozman  , appreciate this and sorry for the confusion hah!
