### ISSUE TITLE
[Bug]: Type functionality is flaky it doesn't type the exact text

### ISSUE THREAD

**Issue by Sonal220692** [microsoft/playwright#33149]
### Version

1.48.1

### Steps to reproduce

Was trying to setup our mobile testing with appetize/playwright
await session.type(email). doesn't type correctly on the simulator which is failing our tests. 

The functionality is very flaky

Tests are running on appetize device iPhone 14 pro max

### Expected behavior

I expect to see same email typed on simulator as passed to type()

### Actual behavior

Cannot type the exact email address. few letters are missed while typing

### Environment

System:
    OS: macOS 14.7
    CPU: (10) arm64 Apple M2 Pro
    Memory: 1.94 GB / 32.00 GB
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    npm: 9.5.0 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.48.1 => 1.48.1

**Comment by dgozman** [comment]
We need more information to act on this issue. Could you please provide a repro that we can run locally?

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
