### ISSUE TITLE
[Docs]: Request::resourceType can return `images` on Firefox

### ISSUE THREAD

**Issue by phil294** [microsoft/playwright#33148]
### Page(s)

https://playwright.dev/docs/api/class-request#request-resource-type

### Description

The listing only mentions `image`, but on Firefox (only), HTML like

```html
<picture><source><img src="http://localhost:5982/my/image/xyz.png"></picture>
```
results in the resourceType `images` instead.

**Comment by dgozman** [comment]
Thank you for the issue, I can repro. We should make sure it's an `image` on Firefox.

```ts
page.on('request', request => {
  console.log(request.resourceType(), request.url());
});

await page.setContent(`<picture><source><img src="https://www.wikipedia.org/portal/wikipedia.org/assets/img/Wikipedia-logo-v2@2x.png"></source></picture>`);
```
