### ISSUE TITLE
[Feature]: websocket messages in network trace

### ISSUE THREAD

**Issue by Georgegriff** [microsoft/playwright#33154]
### 🚀 Feature Request

With the recent release of websocket interception, would it be possible too consider parity with chrome dev tools in the playwright network trace for web sockets.

Chrome captures all messages sent and received in a websocket request 

### Example

Debugging end to end test that rely on websockets for example missing messages, failed connections etc

### Motivation

It will round out the network trace report to capture pretty much everything network tab in chrome does

**Comment by mxschmitt** [comment]
sounds like https://github.com/microsoft/playwright/issues/27346
