### ISSUE TITLE
[Bug]: Playwright debugger only shows recorded code for library under certain condition

### ISSUE THREAD

**Issue by bekzodu** [microsoft/playwright#33152]
### Version

1.48.1

### Steps to reproduce

I run `npx playwright test ./tests/hooks-and-group.spec.js --headed --project chromium`

This is my code for hooks-and-group.spec.js, which is simply to open a page and pause (to open debugger):
```
import {test, expect} from '@playwright/test'

test('Testing with hooks and groups', async({ page }) => {

    await page.goto('https://demo.applitools.com/');
    await page.pause();
})
```
Now, when the page is open and the debugger is displayed, I click `record` button and click on stuff on the page. However, when clicking `record` to stop recording, the debugger does not update with the generated code. Yet, I figured if I switch `target` from `library` to any other one - the code debugger updates and show the code for the actions that I took. And, when I switch the `target` back to `library` the generated code is shown. 

In simple words, the generated code is only shown when I switch back an fourth between `target` and not immideately after stopping recording.

### Expected behavior

I expect the code to be generated immideately after I click stop recording on the debugger.

### Actual behavior

The code is not shown/debugger is not updated with the recorded code.

### Environment

  System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 574.13 MB / 16.00 GB
  Binaries:
    Node: 22.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v21.2.0/bin/yarn
    npm: 10.0.0 - /opt/homebrew/bin/npm
  IDEs:
    VSCode: 0.40.4 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.48.0 => 1.48.0

**Comment by mxschmitt** [comment]
Closing as per above. Feel free to re-file if this issue is still happening, thanks!

**Comment by bekzodu** [comment]
Nope, it's fixed tnx!
