### ISSUE TITLE
[Bug]: Current changes in main broke the Trace Viewer

### ISSUE THREAD

**Issue by Snooz82** [microsoft/playwright#33178]
### Version

Development

### Steps to reproduce

Open Trace viewer that is create by the tests of tests/library/trace-viewer.spec.ts

I am currently implementing groups for tracing.
And the actions tree in trace viewer has been changed from `<div role="listitem" class="list-view-entry">` to `<div role="treeitem" aria-selected="false"><div class="tree-view-entry">`.

That does cause a wrong rendering.

### Expected behavior

This is how it should look like:
![Image](https://github.com/user-attachments/assets/8bcd5666-7c86-47ee-9c7d-384ac796abc7)

i think the changed div with the role `treeitem` also shall have the class `tree-view-entry`. Not the child.

### Actual behavior

This is how it looks
![Image](https://github.com/user-attachments/assets/e9c957c5-e4d5-44bd-b412-89cf99ba80cb)

![Image](https://github.com/user-attachments/assets/67238c51-23d8-4447-aa22-4211694e0359)

### Environment

irrelevant

**Comment by Snooz82** [comment]
Ping @pavelfeldman 😉

**Comment by pavelfeldman** [comment]
Hey, thanks for the heads up. I'm reworking the list into tree for better a11y here and I think flex: none is missing on the treeitem. I have a large change that should include this fix along the way: https://github.com/microsoft/playwright/pull/33169.

**Comment by Snooz82** [comment]
yea. saw the changes, because my tests for PR #33081 were failing after rebase.

i saw that it seems to be caused by your last changes to the action tree. 
thats why i pinged you.

**Comment by mxschmitt** [comment]
The fix should be available on NPM and available on https://trace.playwright.dev/next/.

Please re-file / ping me if you want to re-open!
