### ISSUE TITLE
[Bug]: Channing locators does not work when using getByRole on elements that has aria-owns attribute

### ISSUE THREAD

**Issue by gdferreira-philips** [microsoft/playwright#33179]
### Version

1.48.1

### Steps to reproduce

The application to validate this scenario should have a child element that does not belongs to the parent element in the DOM. It is only displayed in the accessibility tree as the child element due to the usage of the `aria-owns` attribute that makes it behaves like a DOM child, but only for accessibility purposes.

#### Example

```html
<div class="combo js-select">
  <div role="group" aria-owns="listbox1" aria-labelledby="combo1-label">
    <div id="combo1-label" class="combo-label">Favorite Fruit</div>
    <div aria-controls="listbox1" aria-expanded="false" aria-haspopup="listbox" aria-labelledby="combo1-label" id="combo1" class="combo-input" role="combobox" tabindex="0"></div>
  </div>
  <div class="combo-menu" role="listbox" id="listbox1" aria-labelledby="combo1-label" tabindex="-1"></div>
</div>
```

> The above code is based on [combobox W3C](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/). But the issue will happens on any other element that uses aria-owns attribute.

#### Test

1) Select the `group` element.

```js
const group = page.getByRole('group', { name: 'Favorite Fruit' });
```

2) Select the `combobox` element inside the `group` and click on it.

```js
const combobox = group.getByRole('combobox');
await combobox.click();
```

3) Try to select the `listbox` element inside the `group`.

```js
const listbox = group.getByRole('listbox');
```

### Expected behavior

1) The element that has `role="group"` will be mapped on the `group` variable.

2) The element that has `role="combobox"` will receive a click.

3) The element that has `role="listbox"` should be mapped on the `listbox` variable.

> If the `listbox` is appended inside the `group` DOM, then the playwright tool can find the `listbox` as a child of this `group`. On the same way, the playwright tool should be able to find the `listbox` inside the `group` even when it does not belongs to the parent element in the DOM as it is using `aria-owns` to make it available in the parent accessibility tree.

### Actual behavior

1) The element that has `role="group"` will be mapped on the `group` variable.

2) The element that has `role="combobox"` will receive a click.

> In this case, the `combobox` is a child of the `group` in the application DOM.

![Image](https://github.com/user-attachments/assets/b341f9ff-3d6e-4bf7-a6e8-d0f3a5759a95)

3) The element that has `role="listbox"` can not be found as child of the element that has `role="group"`.

> In this case, the `listbox` is not a child of the `group` in the application DOM.

![Image](https://github.com/user-attachments/assets/5b4dfec8-577d-4748-91ed-81d96b0da83b)

### Environment

System:
  OS: Windows 11 10.0.22631
  CPU: (8) x64 Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz
  Memory: 3.50 GB / 15.76 GB
Binaries:
  Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
  npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
IDEs:
  VSCode: 1.94.2 - C:\Users\320114149\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
Languages:
  Bash: 5.2.15 - C:\Program Files\Git\usr\bin\bash.EXE
npmPackages:
  @playwright/test: ^1.48.1 => 1.48.1
  playwright: ^1.48.1 => 1.48.1

**Comment by mxschmitt** [comment]
A more minimal reproduction seems to be:

```ts
it('should work', async ({ page, server }) => {
  await page.setContent(`
    <div>
      <div role="group" aria-owns="input1" aria-labelledby="combo1-label">
        <div id="combo1-label">Favorite Fruit</div>
      </div>
      <button type="button" id="input1" aria-controls="listbox1">Click me</button>
    </div>
  `);
  await page.getByRole('group', { name: 'Favorite Fruit' }).getByRole('button').click();
});
```
