### ISSUE TITLE
[Bug]: Playwright behaves in a different manner when headless + Desktop safari

### ISSUE THREAD

**Issue by txomin55** [microsoft/playwright#33185]
### Version

1.48.0

### Steps to reproduce

1. Clone this repo https://github.com/txomin55/playwright-error-reproduction/tree/main/vue-project
2. run `pnpm install`
3. run `pnpm run test:e2e`
4. tests will fail for webkit
5. change `headless` attr to false in `playwright.config.js` 
6. tests will pass

### Expected behavior

I expect the same behaviour when headdless

### Actual behavior

Headless runs lead into unexpected errors

### Environment

  System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics
    Memory: 16.49 GB / 62.21 GB
    Container: Yes
  Binaries:
    Node: 20.12.1 - ~/.nvm/versions/node/v20.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.12.1/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.1/bin/npm
    pnpm: 9.1.4 - ~/.nvm/versions/node/v20.12.1/bin/pnpm
    bun: 1.0.25 - ~/.bun/bin/bun
  Languages:
    Bash: 5.2.21 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.48.0 => 1.48.1 

**MORE INFO
Headless mode renderes the following when using the UI (WRONG)
![Image](https://github.com/user-attachments/assets/daa4a9cd-ced6-4efe-8ea6-3cee521030a9)

While non headless displays the following (CORRECT) 
![Image](https://github.com/user-attachments/assets/fb6d8add-3b59-41fb-a74f-684331480db3)

**Comment by malikabakhtiyorova** [comment]
#All tests passed with and without headless mode
having followed the instructions, tests passed for all 3 browsers with headless mode true and false

##Version
1.48.0

##Environment
MacOS 15.0 (24A335)

Binaries:
Node: v22.3.0
npm: 10.8.1 
pnpm: 9.12.2
@playwright/test: ^1.48.0

**Comment by txomin55** [comment]
updating node and pnpm versions worked!! thanx!!

**Comment by txomin55** [comment]
updating node and pnpm didn't work for me

**Comment by txomin55** [comment]
You are right... i didnt reproduce it in the CI... so i guess si something weird happening in my local env.

I guess this cam be closed
