### ISSUE TITLE
[Bug]: Playwright report showing waitForResponse logs outside test step

### ISSUE THREAD

**Issue by anandtiwari1** [microsoft/playwright#33186]
### Version

v1.48.1

### Steps to reproduce

Example Steps
1. Clone repo at https://github.com/anandtiwari1/playwright-issue.git
2. npm install
3. npx playwright test
4. verify the playwright report

### Expected behavior

waitForResponse logs `response.text` should display instead test.step
working on playwright version: [v1.46.1](https://github.com/microsoft/playwright/releases/tag/v1.46.1)
![Image](https://github.com/user-attachments/assets/3feb025d-d0a6-4e73-be6a-e7c28a771b56)

### Actual behavior

`response.text` showing outside test.step:
![Image](https://github.com/user-attachments/assets/636bdc3c-b7c8-4356-b3e5-4dff0098e72f)

### Environment

System:
    OS: macOS 15.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.69 GB / 32.00 GB
  Binaries:
    Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.15.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.48.1 => 1.48.1

**Comment by mxschmitt** [comment]
I can repro. Good: 1.46, Bad: 1.47, its probably: https://github.com/microsoft/playwright/pull/31990
