### ISSUE TITLE
[Bug]: Chrome tab and inspector not closing after terminating session in terminal

### ISSUE THREAD

**Issue by romankhomitskyi** [microsoft/playwright#33197]
### Version

1.47.1

### Steps to reproduce

1. Run npx playwright test crawler.spec.ts --debug
2. When chrome tab is opened with pw inspector, do Control + C in terminal to terminate and close chrome tab and inspector

### Expected behavior

Chrome tab and the inspector should be closed

### Actual behavior

Chrome tab and inspector not closed, next runs of `npx playwright test crawler.spec.ts --debug ` multiplying chrome tab and inspector

### Additional context

in 1.46.0 PW version everything is ok

### Environment

 System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 182.75 MB / 32.00 GB
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.15.1/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
  IDEs:
    VSCode: 1.92.2 - /usr/local/bin/code
  Languages:
    Bash: 5.2.15 - /opt/homebrew/bin/bash
  npmPackages:
    @playwright/test: 1.47.1 => 1.47.1

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
