### ISSUE TITLE
No web server for UI mode

### ISSUE THREAD

**Issue by bhubavenski** [microsoft/playwright#33190]
### Page(s)

https://playwright.dev/docs/test-webserver

### Description

You have to add that you can't use webServer option in playwright.config in UI mode. So if somebody tries to run `playwright test --ui` with configured  webServer option, he should know that this option is not available in this mode.

**Comment by mxschmitt** [comment]
UI Mode will also start the WebServer, if its not working for you, please re-file using the "bug" template.
