### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by bhubavenski** [microsoft/playwright#33191]
### Version

1.48.1

### Steps to reproduce

add web server option to playwright.config and try to execute `playwright test` and you will see that the server starts running and tests are also starting in the same time but before the server is fully loaded and ready

### Expected behavior

it should waits for the server to become ready for requests

### Actual behavior

it doesn't waits for the server to become ready for requests

### Environment

  System:
    OS: Windows 10 10.0.19045
    CPU: (6) x64 Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz
    Memory: 7.67 GB / 15.94 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.3 - ~\AppData\Roaming\npm\pnpm.CMD
  IDEs:
    VSCode: 1.94.2 - C:\Users\bobkata75\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.48.1 => 1.48.1

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
