### ISSUE TITLE
[Bug]: Chrome tab and inspector not closing after terminating session in terminal

### ISSUE THREAD

**Issue by romankhomitskyi** [microsoft/playwright#33204]
### Version

1.47.1

### Steps to reproduce

https://github.com/user-attachments/assets/b95f9c9d-5569-4c06-83f8-dc9c6fe8d392

### Expected behavior

Chrome tab and the inspector should be closed when using Сontrol + C in terminal

### Actual behavior

Chrome tab and inspector not closed, next runs of your tests` npx playwright test crawler.spec.ts --debug ` multiplying chrome tab and inspector

### Additional context

in 1.46.0 PW version everything is ok

### Environment

OS: macOS 14.6.1
CPU: (10) arm64 Apple M1 Max
Memory: 182.75 MB / 32.00 GB
Binaries:
Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
Yarn: 1.22.22 - ~/.nvm/versions/node/v20.15.1/bin/yarn
npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
IDEs:
VSCode: 1.92.2 - /usr/local/bin/code
Languages:
Bash: 5.2.15 - /opt/homebrew/bin/bash
npmPackages:
@playwright/test: 1.47.1 => 1.47.1

**Comment by mxschmitt** [comment]
I unfortunately can't reproduce - does this happen on a new project you create with `npm init playwright@latest`?

**Comment by romankhomitskyi** [comment]
> I unfortunately can't reproduce - does this happen on a new project you create with `npm init playwright@latest`?

I tried `npm init playwright@latest` clean project, and found out that it has smth to do with  `screenshot: 'only-on-failure'` in config
once you add it, you cannot terminate debug mode

**Comment by romankhomitskyi** [comment]
![Image](https://github.com/user-attachments/assets/f39b12aa-1912-46ac-81e9-e36887935a9a)
![Image](https://github.com/user-attachments/assets/cb117efc-bee9-43cc-a1cc-e6525ed87df0)

**Comment by romankhomitskyi** [comment]
It eventually closes, but not immediately as it without screenshot option, it takes some time to close

**Comment by mxschmitt** [comment]
Sorry to hear! For us its really hard to debug issues like this which we can't reproduce.

Could you try it with a normal Terminal instead of the IDE terminal?

Otherwise I would recommend bisecting (checking which versions is the exact daily one which was the last good / bad one which was working from our [Canary builds](https://www.npmjs.com/package/@playwright/test?activeTab=versions).

Does it also happen if you set `trace` to `off`? So if you update Playwright to v1.49 which is the latest version and set `screenshot` to `off` its also good?

**Comment by romankhomitskyi** [comment]
> Sorry to hear! For us its really hard to debug issues like this which we can't reproduce.
> 
> Could you try it with a normal Terminal instead of the IDE terminal?
> 
> Otherwise I would recommend bisecting (checking which versions is the exact daily one which was the last good / bad one which was working from our [Canary builds](https://www.npmjs.com/package/@playwright/test?activeTab=versions).
> 
> Does it also happen if you set `trace` to `off`? So if you update Playwright to v1.49 which is the latest version and set `screenshot` to `off` its also good?


The last good version: 1.46.1
Bad version: 1.47.0, 147.1, 1.48.0

I am using clean `npm init playwright@latest project`, nothing more

Does it also happen if you set trace to off - yes

https://github.com/user-attachments/assets/31f6e55b-929e-4ad2-a5dd-f2deae1789d9

**Comment by mxschmitt** [comment]
I can reproduce, thank you!
