### ISSUE TITLE
[Feature]: cleanup for authentication with API using worker fixtures

### ISSUE THREAD

**Issue by Danieliverant** [microsoft/playwright#33202]
### 🚀 Feature Request

Add an option to hook to the "worker cleanup" step to send a "remove company" request to the BE.

We combine the "moderate" approach with the "api" approach:

https://playwright.dev/docs/auth#authenticate-with-api-request
https://playwright.dev/docs/auth#moderate-one-account-per-parallel-worker

So we know when to "create" a new company - `fileName` (from the example above) don't exist.

But we need also the option to "remove" a company if there is no more tests on this worker.

### Example

maybe as a fixture same as workerStorageState:

```
workerStorageStateCleanup: [
   async ({ }, use, workerInfo) => {
          const id = test.info().parallelIndex;
          const fileName = path.resolve(test.info().project.outputDir, `.auth/${id}.json`);

          if (more-tests-on-the-same-worker) {
             // Reuse existing authentication state if any. - use(fileName); or without use.
          } else {
             // Send api to remove the previous company. - use(undefined); or without use.
         }
   },
   {
      scope: 'worker'
   }
]
```

### Motivation

Seems like you can handle authentication cleanup on a global scope but not per-worker.

**Comment by mxschmitt** [comment]
You can use a worker auto fixture for that:

```ts
import { test as base } from '@playwright/test';

export const test = base.extend<{}, { afeterAll: void }>({
  afeterAll: [async ({}, use) => {
    await use();
    console.log('do your cleanups here')
  }, { auto: true, scope: 'worker' }],
});
export { expect } from '@playwright/test';
```

See here: https://playwright.dev/docs/test-fixtures#automatic-fixtures

Everything after the `use` gets executed when the worker shuts down.

Would that work for you?

**Comment by Danieliverant** [comment]
> You can use a worker auto fixture for that:
> 
> import { test as base } from '@playwright/test';
> 
> export const test = base.extend<{}, { afeterAll: void }>({
>   afeterAll: [async ({}, use) => {
>     await use();
>     console.log('do your cleanups here')
>   }, { auto: true, scope: 'worker' }],
> });
> export { expect } from '@playwright/test';
> See here: https://playwright.dev/docs/test-fixtures#automatic-fixtures
> 
> Everything after the `use` gets executed when the worker shuts down.
> 
> Would that work for you?

didn't known that! will try that, thanks!
