### ISSUE TITLE
[Feature] Emulate reduced motion media query

### ISSUE THREAD

**Issue by LarsDenBakker** [microsoft/playwright#3320]
Puppeteer allows emulating the reduced motion media query: https://github.com/puppeteer/puppeteer/blob/v5.2.1/docs/api.md#pageemulatemediafeaturesfeatures

It would be great if we can support this in playwright as well. It's widely supported in browsers: https://caniuse.com/#feat=prefers-reduced-motion

**Comment by pavelfeldman** [comment]
Could you help us prioritizing this? Does it come from a customer or is it a feature parity request?

**Comment by LarsDenBakker** [comment]
It's about feature parity. It's same story as https://github.com/microsoft/playwright/issues/3321 - we offer bindings for emulating media features from tests, using both puppeteer and playwright. Right now we throw an error when trying to emulate reduced motion when running tests with playwright.

**Comment by RyKilleen** [comment]
This would be incredibly useful for testing purposes. For accessibility purposes, we disable all animations based the `prefers-reduced-motion` media query.

Being able to set it to avoid fragile tests would save a bunch of time overall!

**Comment by evanleck** [comment]
FWIW I'd like to be able to emulate this media query so I don't have to wait for animations to end in my tests. Of course something like https://github.com/microsoft/playwright/issues/4055 would help as well but without either I'm just doing arbitrary `page.waitForTimeout`s all over the place haha
