### ISSUE TITLE
[Bug]: Playwright Test: Electron Apps - errors on Run Test mode

### ISSUE THREAD

**Issue by midleman** [microsoft/playwright#33209]
### Version

1.48.1

### Steps to reproduce

Requirements: must have Playwright Test vscode plugin installed.

1. Clone my repo at: [https://github.com/midleman/play-button-repro](https://github.com/midleman/play-button-repro)
2. Run `yarn`
3. Run test via command line: `npx playwright test`
4. Verify test runs without error - PASS
5. Click on Tests Explorer > `Debug Test` button
7. Verify test runs without error - PASS
8. Click on Tests Explorer > `Run Test` button
9. Verify test runs without error - FAIL, electron is unable to launch
```
    Error: Process failed to launch!

    Error: electron.launch: Process failed to launch!
```

### Expected behavior

For electron apps, I should be able to launch/run tests via any of the following options:
* command line
* run test mode (playwright test plugin)
* debug test mode (playwright test plugin)

### Actual behavior

I'm unable to run tests with `Run Test` play button for Electron apps specifically.

### Environment

  System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 254.59 MB / 36.00 GB
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
  IDEs:
    VSCode: 1.94.2 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.48.1 => 1.48.1

**Comment by midleman** [comment]
Well that was amazing... thank you for the prompt fix! ❤

**Comment by mxschmitt** [comment]
If you want to use the Beta with the fix, see [here](https://github.com/microsoft/playwright-vscode/wiki).

**Comment by midleman** [comment]
> If you want to use the Beta with the fix, see [here](https://github.com/microsoft/playwright-vscode/wiki).

Confirmed the fix works. 🚀 Thanks again!

**Comment by ShaMan123** [comment]
+1 on [github actions](https://github.com/ShaMan123/Deepnest/actions/runs/12087970031/job/33710525079?pr=1) and after trying to use [electron fuses](https://github.com/ShaMan123/Deepnest/actions/runs/12088041274/job/33710734414?pr=1) with no success
Tried the suggested xvfb-run as well as the mentioned issue with [`nodeCliInspect`](https://playwright.dev/docs/api/class-electron`)
and after [installing beta](https://github.com/ShaMan123/Deepnest/actions/runs/12088084836/job/33710869610?pr=1).

Is this ticket the same bug? Should mine be resolved as well?
