### ISSUE TITLE
[BUG] PWA crashes with "Aw, Snap!" (Trace Viewer)

### ISSUE THREAD

**Issue by uzairasa** [microsoft/playwright#33219]
Hello,

My tests are running fine in headless and headed mode but whenever, i try to open the generated traces, the PWA crashes and I have no logs expect the "Aw snap" Chrome screen.
In the Trace Viewer, the crashes seem to occur when tracer runs for sometime let's say 10 minutes

I have noticed that my CPU load goes quite high in UI mode so I guess it is performance related.

System info
Playwright Version: [v1.48.1]
Operating System: [macOS 14.7]
Browser: [Chromium]

Screenshot : ![Image](https://github.com/user-attachments/assets/a94ac0d4-f69e-4297-98d9-e00adbecf693)

**Config file**

````
const { defineConfig, devices } = require("@playwright/test");
const dotenv = require("dotenv");

// Load the correct .env file based on the environment
const ENV = process.env.ENV || "stage"; // Default to 'stage' if ENV is not set
dotenv.config({ path: `.env.${ENV}` });

module.exports = defineConfig({
  testDir: "./tests/e2e",
  retries: 0,
  timeout: 10 * 60 * 1000,
  fullyParallel: true,
  workers: 5,
  globalSetup: require.resolve("./global-setup"),
  globalTeardown: require.resolve("./global-teardown"),
  expect: {
    timeout: 15 * 1000,
  },
  reporter: [
    ["json", { outputFile: "tests/ctrf/ctrf-report.json" }],
    ["list"],
    ["allure-playwright"],
  ],
  use: {
    baseURL: process.env.BASE_URL, // Use the baseURL from the environment
    trace: "on",
    headless: true,
    screenshot: "only-on-failure",
    video: "retain-on-failure",
    ignoreHTTPSErrors: true,
    actionTimeout: 80 * 1000,
    navigationTimeout: 30 * 1000,
  }
});

**Comment by mxschmitt** [comment]
Thanks for filing, we have a suspicion on whats causing it. After we fixed it in our Canary we'll get back to you so you can test it out and see if it helps. No action needed from your side for now. Thanks!

**Comment by dgozman** [comment]
Merging into #33086.
