### ISSUE TITLE
[Regression]: VSCode runner arguments stripped

### ISSUE THREAD

**Issue by rahul-sharma-uipath** [microsoft/playwright#33215]
### Last Good Version

1.43.1

### First Bad Version

1.44.0

## Current Version (v1.48.1)

1. `npx playwright init`
2. create `global-setup.ts` and enable in playwright.config.ts with content 
```
export default function (config: FullConfig) {
    console.log(process.argv);

    return config;
}
```
3. outputs 
```
Running global setup if any…
[
  '/Users/rahul/.nvm/versions/node/v18.20.4/bin/node',
  '/Users/rahul/uipath/playwright/node_modules/@playwright/test/cli.js',
  'test-server',
  '-c',
  '/Users/rahul/uipath/playwright/playwright.config.ts'
]
```

## Last Working Version (v1.43.1)
1. `npx playwright init`
2. create `global-setup.ts` with same content as above
3. outputs 
```
[
  '/Users/rahul/.nvm/versions/node/v18.20.4/bin/node',
  '/Users/rahul/uipath/playwright/node_modules/@playwright/test/cli.js',
  'test',
  '-c',
  'playwright.config.ts',
  '--project=chromium',
  '--repeat-each=1',
  '--retries=0',
  '--headed',
  '--workers=1',
  '--trace=off',
  '/Users/rahul/uipath/playwright/tests/example\\.spec\\.ts:3'
]
```

### Expected behavior

I expect the arguments while calling the script to remain the same

### Actual behavior

The playwright CLI arguments do not include arguments such as 
```
  '--project=chromium',
  '--repeat-each=1',
  '--retries=0',
  '--headed',
  '--workers=1',
  '--trace=off',
```

### Additional context

Currently, our `global-setup` script parses the given arguments to set some specific parameters in the `process.env` that can later be accessed by the tests.

With this change, we are unable to upgrade our playwright version, and its unclear why this change is needed. 

Alternatively, if there's some other way the arguments are exposed, that can work too.

### Environment

  System:
    OS: macOS 14.7
    CPU: (10) arm64 Apple M1 Pro
    Memory: 331.67 MB / 32.00 GB
  Binaries:
    Node: 18.20.4 - ~/.nvm/versions/node/v18.20.4/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v18.20.4/bin/npm
  IDEs:
    VSCode: 1.93.1 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.43.1 => 1.43.1 / 1.48.1 => 1.48.1

**Comment by mxschmitt** [comment]
We internally changed the way how tests are getting executed when using the VSCode extension. In what arguments are you interested in? Could you elaborate how you use them?

**Comment by mxschmitt** [comment]
I see - We didn't consider this a use-case we support. Looks like using project dependencies would work better for you: https://playwright.dev/docs/test-global-setup-teardown#option-1-project-dependencies

In order to communicate between the projects (setup an actual test project), you can also set environment variables or write to a file.

Would that work for you? So the idea is to have 3 setup projects and 3 test projects. You could parameterize the setup or test project with custom options in order to give them custom values for the runs: https://playwright.dev/docs/test-parameterize#parameterized-projects

**Comment by rahul-sharma-uipath** [comment]
there's several issues with that IMO -
1. we already have several project setup dependencies that do different things and use the secrets provided by `global-setup.ts` (thru env vars). For this purpose, we deliberately disable running the setup project dependencies when using the vscode test runner and ask developers to run it once before iterating on their tests because waiting on the setup for each test run would be cumbersome and unnecessary
2. the setup project dependencies doesn't scale well just for env variables - I gave several envs as an example, but in reality we actually have something like the below
![Image](https://github.com/user-attachments/assets/894f7b0a-21c9-4e9c-a534-34d97c0ffcc0)
we'll be adding several more envs in the future as we build different types of environments. For each of these we'd have to setup a setup project (~10 setup projects) and then essentially duplicate most of the same code in all of them. With the introduction of new secrets per env as well, we'd have to go and add one to each of the setup projects as well which is not ideal

would it be difficult to expose project in any way? It would massively simplify our setup and keep it fairly minimal - i.e. if its possible to expose some sort of process.env.PLAYWRIGHT_PROJECT or similar?

**Comment by mxschmitt** [comment]
Are all these environments running the same set of tests?

Are you interested running multiple environment tests at the same time?

Usually what customers are doing is putting their environment name [inside a `.env`](https://playwright.dev/docs/test-parameterize#env-files) file which then gets automatically loaded in the config and you can look at it in the global setup/tests.

This would end up that you have a single project in vscode and use the .env file to change the environment. The same experience applies when using UI Mode or when running the tests via the CLI.

**Comment by rahul-sharma-uipath** [comment]
but how would that work with the VSCode extension version of the runner? The current developer experience is very smooth since they just have to select an environment and it just works, with this approach, a developer has to update a value (which isn't strongly typed) within the .env file to switch.

also, to your other question, we do enable multiple environments at the same time, which renders something like the below - ![Image](https://github.com/user-attachments/assets/35d8bb71-9290-4cc6-b557-5387ffb5fd97)

this way, you can easily target different environments with the same tests with the click of several buttons from the extension

IMO the extension should be the "all-in-one" runner tool for playwright tests (and already was this way for a while) - I don't see why it can't continue to be like that just with a presumably small fix. 

I'm happy to contribute as well but I want to understand if this is even an acceptable change to expose the project and if not, what are the objections against it.

**Comment by mxschmitt** [comment]
I had a chat with a colleague about it. While project dependencies offer a verbose way, using a worker fixture which e.g. fetches a secret would be the recommended way. A worker fixture would only get executed once in a worker and provides you an easy way of accessing the project name.

Have you considered that approach?

See here for the implementation: https://playwright.dev/docs/test-fixtures#worker-scoped-fixtures

Instead of 'account' you could call it 'password' and remove the 'page' fixture from the snippet.

To read the project name, you can do:
  

    console.log(test.info().project.name)

Using parameterized projects allows you to pass more options from the config into the worker: https://playwright.dev/docs/test-parameterize#parameterized-projects

**Comment by rahul-sharma-uipath** [comment]
this also works but also feels like a less than ideal workaround for several reasons
- we'd have to refactor all tests to use the exported `test` and exported `expect`, not the worst but cumbersome for ~100 tests
- every test file needs to use the exported one or risk not working for some reason or other
- if a test incorrectly imports `test` from `@playwright/test` it may fail for unknown/unclear reasons to a dev with little context

the above can be solved with several things, e.g. script to replace all `test` imports, and a lint rule to prevent importing `test` from playwright/test but this all seems overkill just to get the VSCode test runner working again. 

on the flip side, the playwright runner just needs to export an env var or a CLI param and this situation can be resolved for any consumer of this project without needing to add all this boilerplate

**Comment by mxschmitt** [comment]
We don't plan on exposing the cli options in the globalSetup. I'll close it then as per above, since the worker fixtures seem to work for your use-case.

Its a common practice to have own fixtures, since it gives you flexibility of extending Playwright. In theory its not a big problem if you forget using them, since you don't have access to the 'password' fixture in this case above and TypeScript and runtime would throw/show an error.

**Comment by rahul-sharma-uipath** [comment]
okay, given that this won't actually be resolved, I opened the following PR https://github.com/microsoft/playwright-vscode/pull/548 against the vscode repo

if you can accept minimally sending the information over, I can work with that to `patch-package` the listener on our local setup to get this to work, which is preferable to reworking the entire set up we have.

the `params` argument is unused in the `runGlobalSetup` function within this project as shown in the above PR, so it shouldn't cause any regressions
