### ISSUE TITLE
[BUG] Unable to select the phx-menu-item in dropdown using Playwright in Java

### ISSUE THREAD

**Issue by komalagrawal1991** [microsoft/playwright#33217]
The Dom Structure:

//<div class="phx-dropdown-content ng-star-inserted">
   
   <phx-menu role="menu" tabindex="0" class="phx-list ng-star-inserted">
      
      <phx-menu-item role="menuitem" tabindex="-2" class="phx-list-item phx-content-heading phx-list-item-disabled ng-star-inserted">
         <div class="phx-list-item-main">
            <span tabindex="-1" class="phx-list-item-container">
               Vehicles
            </span>
         </div>
      </phx-menu-item>
      
      <phx-menu-item role="menuitem" tabindex="-2" class="phx-list-item ng-star-inserted">
         <div class="phx-list-item-main">
            <span tabindex="-1" class="phx-list-item-container">
               
               <div class="phx-item-wrapper">
                  
                  <span class="phx-typeahead-item-content">
                     <span class="phx-item-title"><strong class="highlighted">BB-20241022105033849</strong></span>
         </div>
      </phx-menu-item>
      
   </phx-menu>
   
</div>//

Xpath Used: //*[@id='cdk-overlay-3']//phx-menu-item//*[contains(normalize-space(text()) , 'BB-20241022105033849')]//parent::*[contains(@class,'phx-item-title')]

tried with multiple paths but no luck.

I am able to find the xpath, but not sure why playwright is not selecting the value from dropdown

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
