### ISSUE TITLE
[Bug]: Webkit (Safari) fails playwright tests execution  in custom docker image.

### ISSUE THREAD

**Issue by AksCA** [microsoft/playwright#33227]
### Version

1.48.0

### Steps to reproduce

Base Image:  jenkins/inbound-agent:latest

Included playwright version: npx -y playwright@1.48.0 install --with-deps

Error on running tests: ![Image](https://github.com/user-attachments/assets/1b2d3f4b-243e-427a-ad59-ce4450211118)

### Expected behavior

Playwright dependencies required must be present as we are already running 

npx -y playwright@1.48.0 install --with-deps

### Actual behavior

Error on running platwright tests.

pw:browser (MiniBrowser:887): CRITICAL : WebKitWebView is-controlled-by-automation set but automation is not allowed in this context, falling back to default session. 

### Additional context

![Image](https://github.com/user-attachments/assets/ccd8ebe5-66cf-4626-9baf-b2ed52c8fffa)

### Environment

Attached the Containers details above.

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding! 

> pw:browser (MiniBrowser:887): CRITICAL : WebKitWebView is-controlled-by-automation set but automation is not allowed in this context, falling back to default session.

This is an unrelated warning. We need more information to act on issues like this.
