### ISSUE TITLE
Preventing FOUT prior calling screenshot

### ISSUE THREAD

**Issue by Ne-Ne** [microsoft/playwright#3322]
Hi All,

When calling `.screenshot()` I seem to be capturing the page prior font face being fully rendered (very prevalent in firefox headless). It is not a CDN font and loaded via a react package.

The font is being downloaded, this is validated using `page.on("response", ...)` I also have `waitUntil: "networkidle0"` configured.

To overcome this I have added `{ slowMo: 1000 }`, however not ideal.

I was hoping to use [FontFaceSet](https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet) with the [check method](https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/check) but I cannot access `document` as it returns `undefined`.

Currently, the docs don't seem to cover font/asset loading from what I can tell. Are there any suggestions or better ways of working to ensure better screenshots?

Thanks 👍🏻

**Comment by arjun27** [comment]
Hi @ne-ne, I'm curious to know how you use FontFaceSet to see why `document` is undefined. Couple of ideas:

1. Would `page.waitForResponse` ([docs](https://playwright.dev/#version=v1.2.1&path=docs%2Fapi.md&q=pagewaitforresponseurlorpredicate-options)) work? You can wait for the font to be downloaded.
2. You could try `page.waitForFunction` ([docs](https://playwright.dev/#version=v1.2.1&path=docs%2Fapi.md&q=pagewaitforfunctionpagefunction-arg-options)) and use FontFaceSet
```js
await page.waitForFunction(() => document.fonts.check("12px courier"));
```

Thanks for the suggestion on docs!

**Comment by Ne-Ne** [comment]
Hey @arjun27,

Thanks for getting back, I did get it working with `eval`. However, `waitForFunction` is a much better fit!

Thanks 👍
