### ISSUE TITLE
[Bug]: ClientCertificate, 1.48v, Chrome 130,  PopUp still displayed with the specific browser context

### ISSUE THREAD

**Issue by KatNapierala** [microsoft/playwright#33230]
### Version

1.48

### Steps to reproduce

**Test Case:** Run the simple isga login test with the client certificate in the config file as specified in 1.47.

* Chrom Version **130**
* Playwright **1.48.**
* port 443

**1 trial:**

_Config:_ 
headless: false
browserName: 'chromium',
channel: 'chrome',
chrome policy for auto select certificate: **not set**
clientCertificate: added to config

_Result:_ certificate selection pop up is being displayed. No logs under: pw:client-certificates 

**2 trial:**

_Config:_ 
headless: false
browserName: 'chromium',
channel: 'chrome',
chrome policy for auto select certificate: **set**
clientCertificate: added to config

_Result:_ certificate is selected automatically, test pass. No logs under pw:client-certificates .

**3 trial:**

_Config:_ 
headless: **true**
browserName: 'chromium',
channel: 'chrome',
chrome policy for auto select certificate: **set**
clientCertificate: added to config

_Result:_ ;No client certificate provided'. No logs under pw:client-certificates .

****4 trial: - without chrome channel**

_Config:_ 
headless: **true**
browserName: 'chromium',
chrome policy for auto select certificate: **set**
clientCertificate: added to config

_Result:_ ;No client certificate provided'. 
pw:client-certificates logs: 
Browser -> Proxy
Proxy -> Target
**ALPN error: Client network socket disconnected before secure TLS connection was established**
....
Browser -> Proxy <url> chooses ALPN http/1.1
**error when connecting to target: Client network socket disconnected before secure TLS connection was establoshed**

The browser context picks up the certificate,  because when I change path or insert incorrect password playwright throws error about path/password, so I assume it is being somehow picked up. But then the pop up is still being displayed on login ( choose the certificate).  

**Playwright config:**
```

import { defineConfig } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chrome',
      use: {
         video: 'on',
         screenshot: 'on',
         browserName: 'chromium',
         channel: 'chrome',

        clientCertificates: [{
          origin: 'https://....',
          pfxPath: 'pfxPath...'
          passphrase: 'password...',
        }],
      },
    },
  ]
});
```

### Expected behavior

The pop up to choose client certificate is not displayed. User is logged in. 

### Actual behavior

Pop up is still visible. Even if there is only 1 cert to select.

### Additional context

I also tried with pem and key insetad of pfx Path but same result. pop up is still displayed.

### Environment

node: 20.17.0
npx: 10.8.2
playwright: 1.48
OS: windows
chrome: 130

**Comment by mxschmitt** [comment]
I see that you are sometimes mentioning Playwright v1.47 and sometimes v1.48 - which one are you using? Could you try with v1.48?

It's known, that if you are using a channel like Google Chrome, Enterprise policies might affect the behaviour and break things, see [here](https://playwright.dev/docs/browsers#google-chrome--microsoft-edge). So we should aim to make things work without a channel.

 Is your environment using a proxy by any chance? That might be necessary to make things work - depends on your IT. If required, you need to specify it. [This](https://superuser.com/questions/346372/how-do-i-know-what-proxy-server-im-using) might help to find out if you are using a system proxy.

**Comment by KatNapierala** [comment]
Thank you for quick response. I am using 1.48.
None of the steps from the instructions to get the proxy worked for me but I know there is a proxy. Will it work with the proxy applied?

**Comment by mxschmitt** [comment]
That's most likely the cause yes, you need to set the proxy like this:


```

import { defineConfig } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chrome',
      use: {
         video: 'on',
         screenshot: 'on',
         browserName: 'chromium',
         channel: 'chrome',

        clientCertificates: [{
          origin: 'https://....',
          pfxPath: 'pfxPath...'
          passphrase: 'password...',
        }],

        proxy: {
          server: 'http://123.123.123.123'
        }
      },
    },
  ]
});
```

See here for the proxy documentation: https://playwright.dev/docs/network#http-proxy

**Comment by KatNapierala** [comment]
Thank you Max, Do we know which security algorithm are supported? i.e SHA-1 ?

**Comment by mxschmitt** [comment]
I'd refer here to Node.js and OpenSSL which its using under the hood, you probably mean ciphers:

- `node -e 'console.log(process.versions.openssl)'`
- https://docs.openssl.org/3.0/man1/openssl-enc/#supported-ciphers

This is outside of the control of Playwright, since we rely on Node.js there. Is it working tho?

**Comment by KatNapierala** [comment]
It works locally, but when I switch to pipeline/ Ubuntu image it's throwing error. "Error when connecting to target: Client network socket disconnected before secure TLS connection was established" also "ALPN error: Client network..."

Same parameters as in main message. It's not the playwright image it's custom from company's container registry.

**Comment by mxschmitt** [comment]
> It works locally,

Awesome, with the proxy it works now?

> but when I switch to pipeline/ Ubuntu image it's throwing error

Maybe there is a different proxy required inside the Docker image?

> It's not the playwright image it's custom from company's container registry.

That should not matter from my understanding. Just make sure you are using a recent Node.js version, e.g. 20.X or 22.X (18.X works as well)

**Comment by Skn0tt** [comment]
Closing as inactive.
