### ISSUE TITLE
[BUG] Docs link from GitHub repo redirects to empty Table of contents with footer at the middle of the page

### ISSUE THREAD

**Issue by 12masta** [microsoft/playwright#3323]
**Context:**
```
- Playwright Version: Readme at master
```

**Describe the bug**

**Browsers:**
- Chrome Version 84.0.4147.105 (Official Build) (64-bit)
- Safari Version 13.1.2 (15609.3.5.1.3)

**Steps:**
1. Go to: https://github.com/microsoft/playwright
2. Click Documentation link 

**Result:**
- user redirected to: https://playwright.dev/#?path=docs/README.md
- empty table of contents
- footer displayed at the middle of the page

**Expected results:**
- user redirected to: https://playwright.dev/#?path=docs/README.md
- meaningful table of contents
- footer displayed at the bottom of the page ;)

**Comment by 12masta** [comment]
Created PR with fix I believe: https://github.com/microsoft/playwright/pull/3324

**Comment by arjun27** [comment]
Thanks for the fix!
