### ISSUE TITLE
[Bug]: playwright tests do not show in test tab in vscode when I throw an error if environment variable is not set

### ISSUE THREAD

**Issue by nikhilwaichal** [microsoft/playwright#33248]
### Version

1.48.0

### Steps to reproduce

Issue Description:
Playwright tests do not appear in the Test Explorer section of the Playwright VSCode extension when an error is thrown in the playwright.config.ts file due to a missing environment variable. For example, when checking if the PRODUCT environment variable is set, an error is thrown if it's missing, which causes the Test Explorer to not display the tests.

Steps to Reproduce:
1. Open a Playwright project in VSCode.
2. In the playwright.config.ts file, add a check for an environment variable (e.g., PRODUCT):

```
if (!process.env.PRODUCT) {
  throw new Error(`Product is not specified in .env file`);
}
```
![Image](https://github.com/user-attachments/assets/1a4c292f-3cd1-4d89-a7d3-809cc836e851)

3. Attempt to view the Playwright tests in the Test Explorer section of VSCode.
Test doesnot get loaded in test explorer section of vscode.

4. Set the environment variable in the VSCode settings, e.g.:
json
```
"playwright.env": {
    "PRODUCT": "My product"
}
```
5. Refresh the Test Explorer.
The tests will now appear as expected.
![Image](https://github.com/user-attachments/assets/be0b1d6c-e5e4-4961-90fd-2265b7a63d2a)

### Expected behavior

I expect to see test in test explorer when I throw error if environment variable is not set

### Actual behavior

Test are not shown in test explorer

### Environment

npx envinfo --system --binaries --browsers --npmPackages playwright

  System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 1.18 GB / 7.87 GB
  Binaries:

nikhi@Nikhil MINGW64 /c/NikhilWaichal/Github/PlaywrightCodes/PlaywrightTutorials/PlaywrightTutorials (main)
$ npx envinfo --preset playwright

  System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 1.24 GB / 7.87 GB
  Binaries:
    Node: 20.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.93.1 - C:\Users\nikhi\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.2.26 - C:\Program Files\Git\usr\bin\bash.EXE
  npmPackages:
    @playwright/test: ^1.45.3 => 1.45.3

**Comment by mxschmitt** [comment]
This is expected. We load the config first and then the tests based on the config. If an error is happening in the config we can't load the tests.

(An alternative to env in the settings would be using dotenv https://playwright.dev/docs/test-parameterize#env-files)

**Comment by nikhilwaichal** [comment]
Yes I am using dotenv, but when I want to throw an error if variable is not set. 
it shows error that environment variable is not set even if environment variable exists in dot env file.
Please refer screenshot in description

**Comment by nikhilwaichal** [comment]
Yes I am using dotenv, but when I want to throw an error if variable is not set. 
it shows error that environment variable is not set even if environment variable exists in dot env file.
Please refer screenshot in description

**Comment by mxschmitt** [comment]
You need to uncomment the line 18/19 in your config and put it before you use the env vars, see [here](https://playwright.dev/docs/test-parameterize#env-files).
