### ISSUE TITLE
[Bug]: Playwright does not update 'expires' field in cookie

### ISSUE THREAD

**Issue by pavelkostyurin** [microsoft/playwright#33246]
### Version

1.48.1

### Steps to reproduce

I'm not able to provide a repository because tests are written for a specific Internet router web-gui.

I set up authorization in playwright like so:
```
...
  await setup.step('Login and save storage state', async () => {
    await loginPage.login()
    await context.storageState({ path: 'playwright/.auth/user.json' })
  })
```

After that user.json is populated with cookies:
```
"cookies": [
    {
      "name": "TUENZAACVPYHTERL",
      "value": "QBURLKXIYTQUYQBJ",
      "domain": "172.16.99.55",
      "path": "/",
      "expires": 1732277780,
      "httpOnly": false,
      "secure": false,
      "sameSite": "Strict"
    }
...
```
`expires` is pointing to a +300 seconds in future.

### Expected behavior

When running tests, I expect playwright to maintain the session, so it's not lost after ~5 minutes of testing.
When I work with the router using chromium browser (manually), I can check session storage in its developer console, and with every action that I perform on a page I can see that `expires` value gets correctly updated.

### Actual behavior

Tests are no longer authenticated after ~5 minutes of testing. On test reports screenshots I can see login page instead of actual pages.
`context().cookies()` becomes empty.
Everything was working great before out team made these changes for router backend.

Could you please suggest a solution for this issue?

### Environment

  System:
    OS: Linux 6.8 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 9.82 GB / 15.41 GB
    Container: Yes
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.2.5 - /usr/local/bin/npm
  IDEs:
    VSCode: 1.94.2 - /snap/bin/code
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.48.1 => 1.48.1 
    playwright-slack-report: ^1.1.81 => 1.1.88

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
