### ISSUE TITLE
[Bug]: Test reporter shows screenshot from previous successful test in failed test due to unclosed manually created page

### ISSUE THREAD

**Issue by romankhomitskyi** [microsoft/playwright#33247]
### Version

1.48.1

### Steps to reproduce

1. Create a new project with npm init playwright@latest
2. Create two spec files `example-1.spec.ts` and `example-2.spec.ts`
3. Add this code to `example-1.spec.ts`
```
import {test, expect, Page} from '@playwright/test';

test.describe('First', () => {
  let page: Page
test('first test', async ({ browser }) => {
  page = await browser.newPage()
  await page.goto('https://playwright.dev/');

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);
});
})
```
4. Add this code to `example-2.spec.ts`

```
import {expect, test} from "@playwright/test";
test.describe('Second', () => {
    test('second test', async ({page}) => {
        await page.goto('https://playwright.dev/');

        // Expect a title "to contain" a substring.
        await expect(page).toHaveTitle(/Google/);
    });
})
```

5. Set  `workers: 1,` in  `playwright.config.ts`
6. Run the tests `npx playwright test --project=chromium example-1.spec.ts example-2.spec.ts` - make sure `example-1.spec.ts` runs first

### Expected behavior

Test reporter  should not show screenshots in failed tests from the other successful tests where the manually created page is not closed

### Actual behavior

Test reporter shows screenshots from successful tests where the manually created page is not closed which run before failed one

### Additional context

The bug was in older versions as well, 1.45, 1.46, 1.47

![Image](https://github.com/user-attachments/assets/dd5d56ee-c837-4389-8d9d-fc6f25d369f9)
![Image](https://github.com/user-attachments/assets/d1905b0f-877a-49b8-9691-ee656a1a0d29)
![Image](https://github.com/user-attachments/assets/a29ce933-6e0c-4792-a2a1-a472643cf8a6)

### Environment

System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 64.48 MB / 32.00 GB
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.15.1/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
  IDEs:
    VSCode: 1.94.2 - /usr/local/bin/code
  Languages:
    Bash: 5.2.15 - /opt/homebrew/bin/bash
  npmPackages:
    @playwright/test: 1.48.1 => 1.48.1

**Comment by romankhomitskyi** [comment]
> Why don't you close the page? If you want to keep re-using the page we recommend closing it in afterAll see [here](https://playwright.dev/docs/test-retries#reuse-single-page-between-tests).

I could, but  I though that might be useful to fix, not that critical I think

**Comment by mxschmitt** [comment]
We strongly recommend closing pages when you don't need them anymore.
