### ISSUE TITLE
[Bug]: Slow the very first "cold" test start

### ISSUE THREAD

**Issue by romankhomitskyi** [microsoft/playwright#33251]
### Version

1.48.1

### Steps to reproduce

After I turn on my laptop and then run a test for the first time, the very first run after turning on the laptop is the longest, while all subsequent ones are faster. I guess it’s caching or something like that.
I won’t be able to share a reproducible example.
But I can share the profiles I generated during the first and subsequent runs

I hope they will help.

The very first run
[runner.json](https://github.com/user-attachments/files/17495665/runner.json)
[worker-0.json](https://github.com/user-attachments/files/17495666/worker-0.json)

After the first run
[runner.json](https://github.com/user-attachments/files/17495667/runner.json)
[worker-0.json](https://github.com/user-attachments/files/17495668/worker-0.json)

### Expected behavior

I would like the first test run to be as fast as the subsequent test runs

### Actual behavior

The very first "cold" test run is slow

### Environment

System:
OS: macOS 14.6.1
CPU: (10) arm64 Apple M1 Max
Memory: 750.73 MB / 32.00 GB
Binaries:
Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
Yarn: 1.22.22 - ~/.nvm/versions/node/v20.15.1/bin/yarn
npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
IDEs:
VSCode: 1.94.2 - /usr/local/bin/code
Languages:
Bash: 5.2.15 - /opt/homebrew/bin/bash
npmPackages:
@playwright/test: 1.48.1 => 1.48.1

**Comment by mxschmitt** [comment]
We need unfortunately more information to act on bug reports like this. Looks like you are using network interception and tracing which might impact performance. Not sure if you are using video, thats also something which slows things down.

We can't act on bug reports like this, feel free to re-file with a reproduction and following the bug template, thank you.
