### ISSUE TITLE
firefox.launch() doesn't work, it closes with exitCode=0 soon after the launch.

### ISSUE THREAD

**Issue by sajjadh** [microsoft/playwright#33253]
### Please do not submit this issue.

- [ ] I understand

**Comment by sajjadh** [comment]
```
 const  firefoxPath = 'C:\\Program Files\\Mozilla Firefox\\firefox.exe';
  const browser = await firefox.launch({
    headless: false,
    executablePath: firefoxPath, // Use the path to the user-installed Firefox,
  });

  const context = await browser.newContext();
  const page = await context.newPage();
```


Error: browserType.launch: Target page, context or browser has been closed
Browser logs:

<launching> C:\Program Files\Mozilla Firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\User\AppData\Local\Temp\playwright_firefoxdev_profile-nPLnmF -juggler-pipe -silent
<launched> pid=25164
[pid=25164] <process did exit: exitCode=0, signal=null>
[pid=25164] starting temporary directories cleanup
Call log:
  - <launching> C:\Program Files\Mozilla Firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\User\AppData\Local\Temp\playwright_firefoxdev_profile-nPLnmF -juggler-pipe -silent
  - <launched> pid=25164
  - [pid=25164] <process did exit: exitCode=0, signal=null>
  - [pid=25164] starting temporary directories cleanup


  76 |
  77 |   // Launch the user-installed Firefox browser
> 78 |   const browser = await firefox.launch({
     |                                 ^
  79 |     headless: false,
  80 |     executablePath: firefoxPath, // Use the path to the user-installed Firefox,
  81 |   });

**Comment by mxschmitt** [comment]
This is expected. Playwright only works with our builds of WebKit and Firefox. See here: https://playwright.dev/docs/browsers#firefox
