### ISSUE TITLE
[Feature]: Include device name and version in test results

### ISSUE THREAD

**Issue by abinpa** [microsoft/playwright#33263]
### 🚀 Feature Request

It would be helpful to identify the device details from test results with the addition for fields for device name and version. Currently the project name only available in results, so including device name e.g. Desktop Chrome, Desktop Edge would be useful.

### Example

Currently the project name only available in results, so including device name e.g. Desktop Chrome, Desktop Edge would be useful.

![Image](https://github.com/user-attachments/assets/d495b0f6-c8b7-47f2-8fb7-177997aec28e)

In the below json test results additional parameters for device name and version
![Image](https://github.com/user-attachments/assets/02faf906-a0c4-4c34-aff6-290c02717073)

### Motivation

Better reporting with information of device details and version also use the reporter json files for generating other custom reports.

**Comment by mxschmitt** [comment]
We recommend putting the Device Name as a project name if you are interested to see it inside the report. Would that work for you?

**Comment by aneeshbaby** [comment]
Having the ability to get the browser version as string is going to help us a lot as it will help us producing the results automatically with all the information especially for test summary report.

**Comment by mxschmitt** [comment]
Browser version is something which you need to obtain during the runtime, you could add it with an annotation:

```ts
test.beforeEach(async ({ browser }) => {
  test.info().annotations.push({
    type: 'browser-version',
    description: browser.version(),
  })
});
```

This will be then available in your json report.

**Comment by abinpa** [comment]
> We recommend putting the Device Name as a project name if you are interested to see it inside the report. Would that work for you?

We are using that already but somehow not getting what we are expecting. We have a custom reporter which uses the test results json file to create report where we would like to get with browser name and version.

**Comment by mxschmitt** [comment]
Did you rename `Mobile Chrome` to `Pixel 5`? We need more information, please elaborate why its not working, share your config etc.

As per above, if you want to access the browser version inside the json report, you can do https://github.com/microsoft/playwright/issues/33263#issuecomment-2434845617.

**Comment by abinpa** [comment]
> Did you rename `Mobile Chrome` to `Pixel 5`? We need more information, please elaborate why its not working, share your config etc.
> 
> As per above, if you want to access the browser version inside the json report, you can do [#33263 (comment)](https://github.com/microsoft/playwright/issues/33263#issuecomment-2434845617).

Here is the screenshot of config file. We have two different projects with Firefox browser hence replacing the project name with device name will have issues in reporting. In the config file, full and compact names used for different UI config in the application.

![Image](https://github.com/user-attachments/assets/a648ff69-79ff-43ba-9577-2a0d8f04d416)

**Comment by mxschmitt** [comment]
You can also attach custom metadata to your projects like this:

```
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
      metadata: {
        device: 'Desktop Chrome',
      }
    },

    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
      metadata: {
        device: 'Desktop Firefox',
      }
    },

    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
      metadata: {
        device: 'Desktop Safari',
      }
    },
```

this metadata will also be available in the json report. For browser version, you need to rely on annotations.

**Comment by mxschmitt** [comment]
Closing as per above.

**Comment by abinpa** [comment]
Tried below but the metadata part getting added once under the project block but not under each tests

 projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
      metadata: {
        device: 'Desktop Chrome',
      }
    },

Similar to how project name appearing in each test result block
![Image](https://github.com/user-attachments/assets/8a6032ce-3e3c-4a5b-b076-29cb70073d7e)

**Comment by mxschmitt** [comment]
This is expected, when looping over the projects/tests you can manually back-reference the meta-data to each test-case - Why does this not work for you?

**Comment by abinpa** [comment]
Thanks for the follow up, got another way for fetching it by adding the browser and browse name. This info got added to report as well.

```
test(
  "ABC-123-1 This is a sample test",
  {
    tag: ["@AllBrowsers"],
  },
  async ({ page, browser, browserName }) => {
    test.info().annotations.push({
      type: "browser",
      description: `${browserName} ${browser.version()}`,
    });
  }
); 
```

![Image](https://github.com/user-attachments/assets/4ed7ce71-fdb5-46ac-95f0-cd272844fca3)
