### ISSUE TITLE
[Feature] Apply context routes prior to context creation

### ISSUE THREAD

**Issue by evandigby** [microsoft/playwright#3326]
I would like to be able to apply routes to a context prior to creating it, so that they are there on first load.

For example:
```typescript
        const context = await chromium.launchPersistentContext(
            path.join(__dirname, "temp"),
            {
                executablePath: getEdgePath(),
                devtools: true,
                headless: false
            });
```

This code loads a new tab page, which loads a service worker, before I am able to start adding `context.route` specs.

I would like to be able to intercept the new tab page network calls, including the service worker's calls. If I simply re-navigate to the new tab page as a work around it will intercept non-sw calls but the service worker is already loaded and therefore doesn't have the new context routes.

Example UX:

```typescript
        const context = await chromium.newPersistentContext(
            path.join(__dirname, "temp"),
            {
                executablePath: getEdgePath(),
                devtools: true,
                headless: false
            });

       context.route(...);
       context.route(...);
       context.route(...);
 
       await context.launch();
```

**Comment by JoelEinbinder** [comment]
This sounds like a valid feature request for your use case, but it seems like an incredibly specific use case. It seems like it would only matter if you want to launch a persistent context and do things with the new tab page.

The code you provide doesn't load the new tab page for me, it instead loads about:blank. Are you specifying extra launch options, such as `ignoreDefaultArgs`?

I would expect to see something like 
```js
const {chromium} = require('.');
const path = require('path');
chromium.launchPersistentContext(path.join(__dirname, 'temp'), {
  headless: false,
  executablePath: getEdgePath(),
}).then(async context => {
  const [page] = await context.pages();
  console.log(await page.url()); // about:blank
  await context.route(...);
  await page.goto('edge://newtab');
});
```

**Comment by evandigby** [comment]
Let me confirm it's loading the new tab page. I may have been conflating this issue with the fact that (I didn't realize at the time) you can't service worker requests in general. This may have been a red herring.

**Comment by JoelEinbinder** [comment]
It's not pretty, but you could try to disable service workers before loading your page:

```js
await context.addInitScript(() => {
  navigator.serviceWorker.register = () => new Promise(() => void 0);
});
await page.goto('edge://newtab');
```

**Comment by evandigby** [comment]
@JoelEinbinder that workaround seems to work well. I confirmed it was actually loading about:blank and not the NTP so I was incorrect.

Given that, this ultimately comes down to being a dupe of https://github.com/microsoft/playwright/issues/1090 as what I really need is a way to route the service worker requests rather than disabling them.
