### ISSUE TITLE
[Feature]: Ability to check chained locators via UI mode

### ISSUE THREAD

**Issue by Cporter97** [microsoft/playwright#33278]
### 🚀 Feature Request

When in UI mode, i want the ability to chain locators in the locator section to verify i’m pointing at the correct element/s

### Example

getByRole(‘main’).locator(‘//dd’) 

Hightlighting the specific elements this locator points to

### Motivation

Easier debugging and script writing. 

More maintainable page object models

**Comment by mxschmitt** [comment]
What do you mean with the ability to chain them?

You can already put them into the Locator tab and it should resolve chained locators / resolve them.

Looking at:

![Image](https://github.com/user-attachments/assets/dbecb094-240b-46a2-950c-a07280c6ee27)

**Comment by Cporter97** [comment]
Thanks, for some reason this wasn't working for me yesterday.
