### ISSUE TITLE
[Bug]:  Cant select option with a trailing space

### ISSUE THREAD

**Issue by paulgueltekin** [microsoft/playwright#33288]
### Version

1.42.0

### Steps to reproduce

consider the following testcase: ( needs pytest-playwright installed ) 

```
from playwright.sync_api import Page


def test_selection_with_trailing_splace(page: Page) -> None:
    page.set_content(
        """
        <html><body>
        <select id="test" name="test">

            <option value="1"A></option>
            <option value="2">A </option>

        </select>
        </body>
        </html>
        """
    )

    selection = page.locator("#test")

    # this works
    selection.select_option(label="A")

    # this does not work, runs into timeout
    selection.select_option("A ")

```

### Expected behavior

expected that the second select_option does select this option

### Actual behavior

select_option runs into a timeout

### Environment

- Operating System: [Debian 11]
- CPU: [arm64]
- Browser: [Chromium]
- Python Version: [3.12]

**Comment by mxschmitt** [comment]
Playwright matches against `<option>` element `.label` which is equal to what the user facing label attribute is. Looking at it, its trimmed:

![Image](https://github.com/user-attachments/assets/4e591592-299e-40c8-95d9-6316624e03a6)

Why can't you select by 'value' or 'index' in this case?

**Comment by paulgueltekin** [comment]
Thanks for the reply. So its basically because of HTML whitespace removal in the rendered options label.

I have been able to modify the options text for the affected options, as this whitespace was because of a ill formated template anyways ( adding something like " (default) " to an option, note the whitespaces ) . 

For my usecase i cant use values as they may be different between test runs as the data is created / dropped resulting in different keys ( used as values ) . Index works but need adoption in the tests if new options are added that shifts the index.
