### ISSUE TITLE
The VSCode extension does not recognize playwright.config.js in node_modules folder

### ISSUE THREAD

**Issue by PeterMa9621** [microsoft/playwright#33286]
### Please do not submit this issue.

- [x] I understand

**Comment by PeterMa9621** [comment]
My playwright.config.js file lives in one of dependency's package under the node_modules/package.

I tried to update the  following in settings.json:

  "playwright.env": {
        "testConfigFile":  path to the node_modules playwright config
    }.

But it didn't work.

I also tried setting up https://playwright.dev/docs/getting-started-vscode#multiple-configurations, but it's unable to find the playwright.config.js inside node_modules. 

Any suggestion is appropriated. Thanks in advanced. ❤

**Comment by mxschmitt** [comment]
This is expected, we recommend moving the playwright.config.js out of node_modules.
