### ISSUE TITLE
[Feature]: Adding vscode extension Italian language support

### ISSUE THREAD

**Issue by siteriaitaliana** [microsoft/playwright#33289]
### 🚀 Feature Request

Considering is missing will do a quick fork Pr to add the italian language translation support 

### Motivation

some of my colleagues only speak Italian :-)

**Comment by mxschmitt** [comment]
Appreciate the interest! Feel free to create a PR, the relevant files are:

- https://github.com/microsoft/playwright-vscode/tree/main/l10n
- https://github.com/microsoft/playwright-vscode/blob/6284d0776c7dbe8e8dfb914bddd5bc752c9d6629/package.nls.zh-CN.json#L4

**Comment by siteriaitaliana** [comment]
> Appreciate the interest! Feel free to create a PR, the relevant files are:
> 
> * https://github.com/microsoft/playwright-vscode/tree/main/l10n
> * https://github.com/microsoft/playwright-vscode/blob/6284d0776c7dbe8e8dfb914bddd5bc752c9d6629/package.nls.zh-CN.json#L4

https://github.com/microsoft/playwright-vscode/pull/549

here it is @mxschmitt ..
