### ISSUE TITLE
[Bug]: Lack of clarity in the recommended approach to handling `page.eval` override in the wild

### ISSUE THREAD

**Issue by shravan2x** [microsoft/playwright#33282]
### Version

1.47.0

### Steps to reproduce

Use this code

```
IPlaywright playwright = await Playwright.CreateAsync();
BrowserTypeLaunchOptions options = new BrowserTypeLaunchOptions()
{
    Channel = "chrome",
    Headless = false
};
IBrowser browser = await playwright.Chromium.LaunchAsync(options);

IPage page = await browser.NewPageAsync();
await page.GotoAsync("https://taplink.at/en/tariffs/");
await page.WaitForLoadStateAsync(LoadState.Load);

string? res = await page.MainFrame.EvaluateAsync<string?>("'test'");
Console.WriteLine(res);
```

### Expected behavior

@pavelfeldman mentioned in https://github.com/microsoft/playwright/issues/33015#issuecomment-2401036089 that this behavior is expected. However, the answer doesn't solve a real-world problem - if this behavior is expected, then I'm curious to learn Playwright's recommended approach to it.

### Actual behavior

On some domains, the call to EvaluateAsync returns null. This behavior is not documented anywhere, and no workaround is suggested.

### Additional context

This issue is a direct follow-up to https://github.com/microsoft/playwright/issues/33015, as it was closed before discussion was complete.

@pavelfeldman I assume Playwright is working toward being the best browser automation platform - if this is the case, does it make sense to 1. ignore real-world problems, and 2. blackhole their issue reports with a single line of justification?

### Environment

- Operating System: Windows 11
- CPU: x64
- Browser: Chrome
- .NET Version (TFM): net8.0
- Other info:

**Comment by mxschmitt** [comment]
Playwright targets end-to-end testing which assumes that you control the websites you want to automate. Overriding `globalThis.eval` means that the website essentially breaks any custom JavaScript which gets put into it, which includes extensions and is a very bad practise. Closing by that.
