### ISSUE TITLE
[Bug]: Message of custom matcher is not displayed

### ISSUE THREAD

**Issue by rokbjc** [microsoft/playwright#33293]
### Version

1.48.1

### Steps to reproduce

Clone https://github.com/rokbjc/playwright-custom-matcher-message-bug
Run `npm i`
Run `npm run test`
Wait for tests results to open in browser

### Expected behavior

Message `this message is expected to be shown in report` is expected.
``` typescript
// test.spec.ts
import { expect as expectBase, test, MatcherReturnType } from '@playwright/test';

const expect = expectBase.extend({
  toHaveCustomMessage: (receiver: any):MatcherReturnType => {
    return {
      pass: true,
      message: () => 'this message is expected to be shown in report',
    };
  }
});


test('test', async () => {
  expect(true).toHaveCustomMessage();
});

```

### Actual behavior

Message `expect.toHaveCustomMessage` is shown
![Image](https://github.com/user-attachments/assets/3aa16280-dedf-473d-bdc2-de587069f009)

### Environment

  System:
    OS: Windows 11 10.0.26100
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 15.58 GB / 31.76 GB
  Binaries:
    Node: 23.0.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 4.5.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 0.42.3 - c:\Users\rok\AppData\Local\Programs\cursor\resources\app\bin\code.CMD
  Languages:
    Bash: 5.2.21 - C:\WINDOWS\system32\bash.EXE
  npmPackages:
    @playwright/test: ^1.48.1 => 1.48.1

**Comment by ShoomanKhatri** [comment]
Can you plz assign this task to me?

**Comment by Skn0tt** [comment]
Hi! Playwright doesn't have a concept of matcher messages, it only has a concept of errors.  See the `TestStep` type for reference: https://playwright.dev/docs/api/class-teststep.

I'll update our docs to reflect that if a matcher returns `{ passed: true }`, then `message` will be ignored. 

If you want to show a message in the report, consider using attachments: https://playwright.dev/docs/api/class-testinfo#test-info-attach

**Comment by mxschmitt** [comment]
Its expected that the message is not shown when the expect is passing.

**Comment by rokbjc** [comment]
Thank you for rapid response. 

Technically I understand what you are saying but, in some cases customized messages would give more sense than just matcher name, specially if messages works with existing matchers. I have also one more reason "against" using testInfo. I want to attach message to the sepecific step. Attachemnts are useful and we are using it, but for files, images, etc. In the other words, somehow I would like to audit steps I am doing for testing with specific data, and, because some assertions are reused a lot, custom matcher sounds good solution. Like in Jest.

Even more concrete example. For API calls I am using `fetch`. Is I understand, it is not supported by Playwright, so I wanted to write my own, which is even more adopted to my scenario. There is an example code:
``` typescript
import jestExpect from 'expect/build/matchers';

export type thisType = ReturnType<PlaywrightExpect<CustomMatcherReturnType> | JestExpect>;
export type Result = Pick<CustomMatcherReturnType, 'pass' | 'message' | 'name'>;

export function toHaveStatus(this: thisType, received: Response, expectedStatus: number) {
  const url = new URL(received.url);
  const jestResult = jestExpect.toBe.call({ ...this, customTesters: [] }, received.status, expectedStatus) as Result;

  return {
    pass: jestResult.pass,
    message: jestResult.pass
      ? () => `expected '${url.pathname}' not to have status ${expectedStatus}`
      : () => `expected '${url.pathname}' to have status ${expectedStatus}, but got ${received.status}`,
  };
}
```

So, the main goal is, when writing assertions in test and interpreting the results, to be as readable as possible also for non testers.
