### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by ancacor** [microsoft/playwright#33294]
### Version

1.48.1

### Steps to reproduce

1. Run the npx command to sun tests
2. The failed one are saved in test/results
3. Run again the tests

### Expected behavior

User should be able to run the test suite

### Actual behavior

After approx. 5 minutes, user receives error: 
"Error: EPERM: operation not permitted, rmdir [...]" - the place where the project is saved 
After deleting the tests/results and executing npx run command again, suite tests is triggered

### Environment

System: Windows 10 Enterprise
Version: 22H2
"devDependencies": {
    "@playwright/test": "^1.48.1",
    "@types/node": "^20.11.5",
    "allure-commandline": "^2.18.1",
    "allure-playwright": "^2.11.1",
    "cross-env": "^7.0.3",
    "dotenv": "^16.3.2",
    "moment": "^2.30.1",
    "playwright": "^1.41.2",
    "prettier": "^3.2.4"
  }

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
