### ISSUE TITLE
[Feature]: Download files by default/suggested name

### ISSUE THREAD

**Issue by bobweasel** [microsoft/playwright#33305]
### 🚀 Feature Request

I use Playwright to partially automate my tasks but sometimes I need to navigate manually to get to the info I require. As such, I need to download files manually as well, but there doesn't seem to be a way to save those files as their default names.

I know if the download is started from the script, I might be able to use suggested_filename, but in this case, I am triggering the download manually.

Can you add a global override to name all files by their default or suggested names instead of a GUID?

### Motivation

Keep file extensions and names so they are more readable.

**Comment by Skn0tt** [comment]
To save a download into a user-readable filename and directory, we recommend using ['Download.saveAs()'](https://playwright.dev/docs/api/class-download#download-save-as).

**Comment by bobweasel** [comment]
I am downloading the files manually in this case, so I won't be able to access those methods.

**Comment by Skn0tt** [comment]
Sorry, looks like I closed prematurely. Gonna reopen.

I'm not sure what "downloading manually" mean? Could you elaborate?

**Comment by bobweasel** [comment]
I mean using the playwright browser like you would on a regular browser, type in websites and right click save as kind of stuff.

**Comment by Skn0tt** [comment]
Interesting! How are you opening up the Playwright browser then? And could you elaborate why you use the Playwright browser instead of a regular one?

**Comment by bobweasel** [comment]
Just opening it normally and put it on wait, by input or sleep. It can automate all the things I need done up to that point, and also part of development, automate until that point and figure out what to do next.

**Comment by bobweasel** [comment]
> This falls out side of the scope for Playwright.

Is there not a setting I could change to make it download with filenames intact by default?
