### ISSUE TITLE
[Bug]: Electron - multiple traces attached to a test in report

### ISSUE THREAD

**Issue by midleman** [microsoft/playwright#33303]
### Version

1.48.1

### Steps to reproduce

1. Clone my repo at https://github.com/midleman/play-button-repro
2. Run `yarn` to install deps
3. Run `npx playwright test`
4. Run `npx playwright show-report`
5. View report and notice that tracing is there and working, but what is this other rogue `trace.zip`?. If I drop into trace viewer, it's blank screens, etc. 
![Image](https://github.com/user-attachments/assets/3da72357-7d79-41aa-ad73-7cb7abe5c386)
![Image](https://github.com/user-attachments/assets/220ebdc2-a708-4c12-9085-c82f87c923e9)

### Expected behavior

I expect to see one trace report per test.

### Actual behavior

I'm seeing two (1 relevant, 1 invalid), I can't figure out where this extra one is coming from.

### Environment

  System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 99.05 MB / 36.00 GB
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
  IDEs:
    VSCode: 1.94.2 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.48.1 => 1.48.1

**Comment by Skn0tt** [comment]
Hey Marie! Hope you had a good weekend.

The superfluous trace is started automatically by Playwright at the beginning of a test run, because in `playwright.config.ts` you set `use.trace: "on"`. That option is respected by Playwright's builtin browser fixtures, but not by the electron instance you spin up in the test.

Turn `use.trace: "on"` into `"off"`, that will remove the unneeded trace.

**Comment by midleman** [comment]
Good morning @Skn0tt! Thanks for the reply.

So, I have updated my repo and turned tracing `off` and I have two tests in there now (`electron.spec.ts`, `browser.spec.ts`) which are both manually starting/stopping tracing.

If I run `npx playwright test`, tracing looks great and as expected. 

If I run `npx playwright test --debug`, tracing looks great and as expected. 

If I go to the **Test Explorer** and run `Debug Test` at the root, tracing looks great and as expected.

If I go to the **Test Explorer** and run `Run Test` at the root, I get a tracing error on the browser spec.
`Error: Tracing has been already started`

Where and how is this extra tracing starting? I have it `off` in my config. I would expect I should have consistent tracing behavior regardless of how start the test run.

**Comment by Skn0tt** [comment]
Hmm, not sure what's happening there. Could you provide me with a reproduction repo so I can take a look myself?

**Comment by Skn0tt** [comment]
Ah, I see you've updated the repo. Taking a look now.

**Comment by Skn0tt** [comment]
Do you happen to have "Show trace viewer" enabled? Disabling that fixes it for me.

![Image](https://github.com/user-attachments/assets/93b8abb2-67c7-40f0-8412-b40a17e31f01)

**Comment by midleman** [comment]
Oh wow, yep that was it! Thank you for figuring that out. I'm guessing having that checked shouldn't break the tracing the way it currently does, right?

**Comment by Skn0tt** [comment]
Good to hear that unchecking helps!

Browser tests aren't expected to manually set up tracing, since the Playwright test runner does all of that plumbing. So I think everything's working as intended.

**Comment by midleman** [comment]
> Good to hear that unchecking helps!
> 
> Browser tests aren't expected to manually set up tracing, since the Playwright test runner does all of that plumbing. So I think everything's working as intended.

I'd agree, however, it works via command line w/o issue. Also, there might be cases where people need to manually control their tracing (like me).
