### ISSUE TITLE
[Bug]: waitForRequest is timed out only in Webkit.

### ISSUE THREAD

**Issue by semanticist21** [microsoft/playwright#33318]
### Version

1.48.2

### Steps to reproduce

I'm making simple test that chekcs whether network request is made for each search input.
Like, typing 's' will make a network call with query param 's'.

```typescript
test('search-consecutive-network-call-test', async ({page}) => {
    await page.goto(baseUrl, {
      waitUntil: 'load',
    });

    const inputContainer = page.locator('div[role="search"]');
    const inputEl = inputContainer.locator('input[type="search"]');

    const targetEndPoint = 'api/tech/newsroom/list';
    const inputValue = 'test';

    let curValue = '';

    const promises = [...inputValue].map(async (v) => {
      await inputEl.fill(v);
      curValue += v;

      const req = await page.waitForRequest((req) => {
        const apiUrl = req.url();
        if (!apiUrl.includes(targetEndPoint)) return false;

        const urlParsed = new URL(apiUrl);
        const queryParam = urlParsed.searchParams.get('query');

        if (!queryParam) return false;

        return true;
      });

      expect(req).not.toBeUndefined();
    });

    for (const promise of promises) {
      await promise;
      await page.waitForTimeout(200);
    }
  });
});
```
As you see below of the image, only in 'webkit' environment there is an network timeout error.
I guess it is somehow Webkit error. can u check it?

![Image](https://github.com/user-attachments/assets/ff9cfed2-740d-4d38-9027-25595743b4d5)

### Expected behavior

ALL tests are successful.

### Actual behavior

'Webkit' test fails every time.

### Additional context

My platwright.config.ts files is as below.

import {defineConfig, devices} from '@playwright/test';

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// import dotenv from 'dotenv';
// import path from 'path';
// dotenv.config({ path: path.resolve(__dirname, '.env') });

const baseURL = 'http://localhost:3000/tech';

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
  testDir: './tests',
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 4 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: 'html',
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    baseURL,

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: {...devices['Desktop Chrome']},
    },

    {
      name: 'firefox',
      use: {...devices['Desktop Firefox']},
    },

    {
      name: 'webkit',
      use: {...devices['Desktop Safari']},
    },

    /* Test against mobile viewports. */
    // {
    //   name: 'Mobile Chrome',
    //   use: { ...devices['Pixel 5'] },
    // },
    // {
    //   name: 'Mobile Safari',
    //   use: { ...devices['iPhone 12'] },
    // },

    /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: { ...devices['Desktop Edge'], channel: 'msedge' },
    // },
    // {
    //   name: 'Google Chrome',
    //   use: { ...devices['Desktop Chrome'], channel: 'chrome' },
    // },
  ],

  /* Run your local dev server before starting the tests */
  webServer: {
    command: 'pnpm dev',
    url: baseURL,
    timeout: 60 * 1000,
    reuseExistingServer: !process.env.CI,
  },
});

### Environment

  System:
    OS: macOS 14.4
    CPU: (12) arm64 Apple M3 Pro
    Memory: 7.57 GB / 36.00 GB
  Binaries:
    Node: 22.8.0 - /opt/homebrew/bin/node
    npm: 10.8.2 - /opt/homebrew/bin/npm
    pnpm: 9.9.0 - /opt/homebrew/bin/pnpm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.48.2 => 1.48.2 
    playwright: ^1.48.2 => 1.48.2

**Comment by Skn0tt** [comment]
Hi! Please provide us with a complete minimal reproduction case, so we can take a look at your problem on our machines.

**Comment by semanticist21** [comment]
> Hi! Try beginning the `waitForRequest` before filling the element:
> 
> const reqPromise = page.waitForRequest(...)
> await inputEl.fill()
> const req = await reqPromise;
> It looks like the `inputEl.fill` call immediately triggers the network request, and then `waitForRequest` happens _after_ the request is already sent off. You can fix this by registering the `waitForRequest` before triggering the request. Chromium and Firefox could just behave a little differently than Webkit here.
> 
> If that doesn't help, please provide us with a complete minimal reproduction case, so we can take a look at your problem on our machines.

Wow! that solution is what I have never been thinking of.
I fixed the code according to your solution and it worked well.

I guess webkit network call is a bit faster than other browsers, resulting missing some network calls.

Thank you for the help.
