### ISSUE TITLE
[Bug]: Significant Performance Discrepancy Between WebKit and Chrome in Playwright Tests

### ISSUE THREAD

**Issue by OSnuszka** [microsoft/playwright#33319]
### Version

1.48.2

### Steps to reproduce

1. Create or use an existing suite of tests that run efficiently on Chrome. Examples could include tests involving multiple types of assertion i.e `waitForVisible()`.
2. Configure the tests to run sequentially on both Chrome and WebKit, keeping all other settings (e.g., selectors, waits) the same.
3. Measure the total execution time for each suite separately on Chrome and WebKit.

### Expected behavior

The execution time on WebKit should be comparable to Chrome, with only minor, manageable performance differences. WebKit should not require significant additional time for test scenarios that involve straightforward navigation, form interactions, or dynamic content manipulation.

### Actual behavior

Tests on WebKit take considerably longer than on Chrome across the board. This issue is observed even in tests with minimal complexity, such as basic UI interactions and assertions. In some cases, WebKit takes up to twice as long to complete the same tests that run efficiently on Chrome.
Additionally, the longer the test duration, the more pronounced the performance discrepancy becomes.

### Additional context

What might be the underlying cause of this performance difference? I’ve noticed several GitHub threads discussing WebKit performance issues, with mentions of various potential factors. Are there any plans to further optimize WebKit performance in future Playwright updates?

### Environment

Playwright version: 1.48.
OS: Linux (Docker Image with Ubuntu 24.04) and Windows (Locally)
Node.js version: 20.1
Browsers Tested: Chromium, WebKit

**Comment by Skn0tt** [comment]
Hey, hope you had a good weekend! What you're reporting sounds very similar to https://github.com/microsoft/playwright/issues/18119. What helped them was to change their tracing and video settings: https://github.com/microsoft/playwright/issues/18119#issuecomment-1370734489
Could you give that a try? If that doesn't fix it, please provide us with a reproduction case. Also, can you observe this performance difference only locally, or also on CI? How's the performance difference on Linux?

**Comment by OSnuszka** [comment]
Hey, @Skn0tt hope your weekend was great too! Thanks for the quick response.

I don’t currently use tracing or video in my setup, so neither setting seems to be affecting the test times. As for the performance difference, I’m seeing it both locally and on CI; it’s actually more pronounced on CI due to the larger volume of tests running concurrently. On average, the tests take around twice as long to complete on WebKit compared to Chrome, and this impact compounds with longer test scenarios.

Are there any additional configurations or optimizations that might improve WebKit performance in this context? The issue’s visibility on CI makes it challenging to maintain consistent test cycle times, so any further insights would be really helpful!

Thanks again for looking into this!

**Comment by Skn0tt** [comment]
Would it be possible that you provide is with the implementation of one of your tests, so we can take a look ourselves if we spot something? Maybe there's a specific feature your website uses that slows down things on our Webkit build more than on our Chromium.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
