### ISSUE TITLE
[Feature]: Add CLI option to output the number and names of --only-changed tests without running them

### ISSUE THREAD

**Issue by viktorgagaleski** [microsoft/playwright#33324]
### 🚀 Feature Request

Hello playwright team, 

I have just implemented --only-changed in our GitHub Actions workflow, and it works pretty well. However, while working on this I noticed that there is a space for optimization. Often, after the --only-changed upgrade, we update and run several tests, but our workflow will still run tests on 4 shards, as they are statically defined. Sometimes, we run tests only in three shards and we spin one agent basically for nothing. So I wanted to ask if it is possible to provide us with some cli tool that will output the amount of --only-changed tests and their names, so that we can dynamically set the number of shards that we run on as part of a workflow step.

Thanks!

### Example

npx playwright test --only-changed-status

It outputs number of tests that will run with the --only-changed run and their names.

### Motivation

This will help reducing our workflow costs, as we can dynamically set the matrix with shards and use less shards if low number of tests are affected by the change. In some cases this can even speed up the whole workflow.

**Comment by Skn0tt** [comment]
Hey Viktor! Hope you had a good weekend.

`npx playwright test --only-changed --list` should output changed tests, would that help you?

**Comment by viktorgagaleski** [comment]
Hello @Skn0tt thanks for the quick response. I will try it out and will get back to you with feedback by the end of this week!

**Comment by mxschmitt** [comment]
I'll close it in the meantime since the issues has been resolved. If you have further questions, feel free to re-file. Thanks!
