### ISSUE TITLE
[Bug]: TypeError: playwright.clear is not a function

### ISSUE THREAD

**Issue by p3droml** [microsoft/playwright#33333]
### Version

1.47.2

### Steps to reproduce

Example:
```
const browser = await chromium.launch();
const context = await browser.newContext();
const page = await context.newPage();
await page.goto('http://example.com');

const h1 = await page.locator("xpath=//h1");
await h1.highlight();

await page.evaluate(() => {
  playwright.clear();
});
```
Running Playwright in Debug Mode:

`PWDEBUG=console node test.js`

### Expected behavior

Clear existing highlights.

### Actual behavior

Error:
`page.evaluate: TypeError: playwright.clear is not a function`

### Additional context

Following the example for playwright.generateLocator(handle) [here](https://github.com/microsoft/playwright/issues/13900), I want to clear existing highlights.

Documentation: [https://playwright.bootcss.com/python/docs/debug](https://playwright.bootcss.com/python/docs/debug)

### Environment

System:
    OS: Linux 5.15 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (12) arm64 unknown
    Memory: 2.53 GB / 7.63 GB
    Container: Yes
  Binaries:
    Node: 18.20.4 - ~/.nvm/versions/node/v18.20.4/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v18.20.4/bin/npm
  IDEs:
    VSCode: 1.93.1 - /home/pedro/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/bin/remote-cli/code
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.46.0 => 1.47.2 
    playwright: ^1.45.3 => 1.47.2

**Comment by Skn0tt** [comment]
Hi Pedro! I'm afraid there's no such thing as `playwright.clear()`, so this is expected. I also can't find anything about `clear` in the issue you're linking. Could you elaborate on what you're looking to achieve?

**Comment by p3droml** [comment]
Hi Skn0tt, sorry, I forgot to add the link to the [documentation ](https://playwright.bootcss.com/python/docs/debug)(edited issue).

```
Use the playwright API
playwright.$(selector): Highlight the first occurrence of the selector. This reflects how page.$ would see the page.
playwright.$$(selector): Highlight all occurrences of the selector. This reflects how page.$$ would see the page.
playwright.inspect(selector): Inspect the selector in the Elements panel.
**playwright.clear(): Clear existing highlights.**
```
However, I now realize that it's a different domain (unofficial?) that points to version 1.8.0. I'm confused.

**Comment by Skn0tt** [comment]
Yeah, that's an unofficial mirror of the docs, and it's very very outdated.

`playwright.clear()` doesn't exist anymore. `highlight()` is meant for debugging only (see [docs on that](https://playwright.dev/docs/api/class-locator#locator-highlight) , so there's no programmatic way of clearing them.

Could you elaborate on what you're trying to achieve? Maybe there's a different feature within in Playwright that could help.

**Comment by yury-s** [comment]
Closing per the response above.
