### ISSUE TITLE
[Bug]:  Test Execution Timeout and Auto Fixture Hook Parallel Execution Causing False Failures

### ISSUE THREAD

**Issue by ani-sh-z** [microsoft/playwright#33345]
### Version

1.48.0

### Steps to reproduce

**STR:**
- Set a timeout for the test
- Run the test with an auto fixture that contains an after hook to clean up data once the test is complete
- Observe that the test fails with a timeout error, and the after hook starts execution while the test is still running
- As the after hook clears data used in the test, observe that the test fails with misleading error messages related to missing data

### Expected behavior

The after hook should only start once the test has fully completed its execution, including cases where the test fails due to a timeout. This ensures that data used in the test is not deleted prematurely, avoiding false failures and ensuring accurate error messages.

### Actual behavior

The after hook initiates execution parallel to the test, resulting in data being cleaned before the test has finished, causing misleading failures due to missing data that was removed prematurely.

### Additional context

This issue blocks accurate debugging as the error messages do not reflect the actual test failure cause.

![Image](https://github.com/user-attachments/assets/dd9a74e7-5bf4-4b9c-9281-b9c641dd9d16)

### Environment

Playwright Version: 1.48.0
Node.js Version: v20.14.0
OS: Mac 13.5.1

**Comment by Skn0tt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
