### ISSUE TITLE
[Bug]: project.grepInvert in playwright.config.ts does not seem to work

### ISSUE THREAD

**Issue by AurelienKun** [microsoft/playwright#33340]
### Version

1.48.x

### Steps to reproduce

Setup a project like this under `playwright.config.ts` : 
```
export default playwrightConfig({
    testDir: './tests',
    projects: [
        {
            name: 'setup',
            testMatch: '**/*.setup.ts',
        },
        {
            name: 'desktop',
            testMatch: ['**/*.test.ts'],
            testIgnore: ['**/*.setup.ts'],
            grepInvert: /@mobile-only|@desktop-tobefixed/,
            dependencies: ['setup'],
        },
        {
            name: 'mobile',
            testMatch: ['**/*.test.ts'],
            testIgnore: ['**/*.setup.ts'],
            grepInvert: /@desktop-only|@mobile-tobefixed/,
            use: {
                ...devices['iPhone SE'],
            },
            dependencies: ['setup'],
        },
    ...
  ]
})
```
Properties `testMatch` and `testIgnore` seem to work properly. But as for the `grepInvert`  it does not seem to exclude the relevant tags.

### Expected behavior

Running `npx playwright test --project=mobile` must not run the following existing tests :
```
test('should not run by mobile', { tag: ['@desktop-only'] }, async ({ page }) => {
  ... 
});

test('nor this one', { tag: ['@mobile-tobefixed'] }, async ({ page }) => {
  ...
});
```

### Actual behavior

Running `npx playwright test --project=mobile` those tests are running but should not because of the grepInvert with regex matching the test's tags:
```
test('should not run by mobile', { tag: ['@desktop-only'] }, async ({ page }) => {
  ... 
});

test('nor this one', { tag: ['@mobile-tobefixed'] }, async ({ page }) => {
  ...
});
```

### Environment

  System:
    OS: Linux 6.12 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 7840HS w/ Radeon 780M Graphics
    Memory: 51.38 GB / 58.66 GB
    Container: Yes
  Binaries:
    Node: 20.16.0 - ~/.config/nvm/versions/node/v20.16.0/bin/node
    npm: 10.8.1 - ~/.config/nvm/versions/node/v20.16.0/bin/npm
    pnpm: 8.15.5 - ~/.local/share/pnpm/pnpm
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.48.2 => 1.48.2

**Comment by Skn0tt** [comment]
Hi! I'm having trouble reproducing this. In my tests, everything's working as expected. Could you please provide a reproduction repo that I can use to run those commands on my end?

**Comment by AurelienKun** [comment]
Humm I've created a side project and it works properly. I should have missed something in my project.
Let's close this ticket for now.
