### ISSUE TITLE
[Bug]: Can't attach failed video to report when use Certificate in fixture

### ISSUE THREAD

**Issue by tomekniemiec** [microsoft/playwright#33346]
### Version

1.48.1

### Steps to reproduce

Sorry but I can't upload my repo to link  because use cert.

Here is my example;

I d like to extend my fixture or use as new fixture

 
```
import { test as base } from '@fixtures/base.page.fixture';

export const testWithCert = base.extend({
  page: async ({ browser }, use) => {
    const context = await browser.newContext({
      clientCertificates: [
        {
          origin: 'https://shop-test.xxx.pl/cart',
          certPath: process.env.CERT_CERT_PATH,
          keyPath: process.env.CERT_KEY_PATH,
          passphrase: process.env.CERT_PASSPHRASE,
        },
      ],
    });
    const page = await context.newPage();
    await use(page);
  },
});
```

when use clientCertificates in fixture during the test fail , video is not attached to report.

when add 
`recordVideo: {
    dir: 'test-results/videos',  
  },`

video is also not attached to report

### Expected behavior

I should add video to report when use clientCertificates as fixture

### Actual behavior

It's not possible to  add video to report when use clientCertificates as fixture

### Environment

System : ubuntu

**Comment by Skn0tt** [comment]
Hi! Could you try reproducing this in a blank Playwright project? It's hard to debug this on our end without something we can execute.

**Comment by tomekniemiec** [comment]
I need cert and website where will be possible to use …
Do You have any idea how to find example website and cert?

**Comment by Skn0tt** [comment]
On a closer look, I think the problem might be that you're overriding the `page` fixture. Try passing client certificates in your project config instead: https://playwright.dev/docs/api/class-testoptions#test-options-client-certificates

**Comment by tomekniemiec** [comment]
Yes, I know, but I want to use certificates in fixture, not in global config project.

**Comment by Skn0tt** [comment]
The reason video doesn't work is that video is only auto-configured for Playwright's builtin `page` fixture. You could rewire all of this yourself, but that's lots of brittle code. Let's think of a different solution. Anything you pass into `config.use`, you can also override as a normal fixture. Would this work for you?

```ts
import { test as base } from '@fixtures/base.page.fixture';

export const testWithCert = base.extend({
  clientCertificates: [{
      origin: 'https://example.com',
      certPath: './cert.pem',
      keyPath: './key.pem',
      passphrase: 'mysecretpassword',
  }]
});
```

**Comment by Skn0tt** [comment]
Or, even simpler:

```ts
import { test } from '@fixtures/base.page.fixture';

test.use({
  clientCertificates: [{
         origin: 'https://shop-test.xxx.pl/cart',
          certPath: process.env.CERT_CERT_PATH,
          keyPath: process.env.CERT_KEY_PATH,
          passphrase: process.env.CERT_PASSPHRASE,
  }]
})
```

**Comment by tomekniemiec** [comment]
> Or, even simpler:
> 
> import { test } from '@fixtures/base.page.fixture';
> 
> test.use({
>   clientCertificates: [{
>          origin: 'https://shop-test.xxx.pl/cart',
>           certPath: process.env.CERT_CERT_PATH,
>           keyPath: process.env.CERT_KEY_PATH,
>           passphrase: process.env.CERT_PASSPHRASE,
>   }]
> })

when use this, get: 
"Error: No tests found"

**Comment by tomekniemiec** [comment]
> The reason video doesn't work is that video is only auto-configured for Playwright's builtin `page` fixture. You could rewire all of this yourself, but that's lots of brittle code. Let's think of a different solution. Anything you pass into `config.use`, you can also override as a normal fixture. Would this work for you?
> 
> import { test as base } from '@fixtures/base.page.fixture';
> 
> export const testWithCert = base.extend({
>   clientCertificates: [{
>          origin: 'https://shop-test.xxx.pl/cart',
>           certPath: process.env.CERT_CERT_PATH,
>           keyPath: process.env.CERT_KEY_PATH,
>           passphrase: process.env.CERT_PASSPHRASE,
>   }]
> });


when use this get:

`The expected type comes from property 'clientCertificates' which is declared here on type 'Fixtures<{ clientCertificates: [{ origin: string; certPath: string; keyPath: string; passphrase: string; }]; }, { clientCertificates: unknown; }, PlaywrightTestArgs & PlaywrightTestOptions & { ...; }, PlaywrightWorkerArgs & PlaywrightWorkerOptions>'`

clientCertificates is underline

**Comment by Skn0tt** [comment]
If you want to set `clientCertificates` only for one test file, I recommend going with the `test.use` example I shared.

> when use this, get:
"Error: No tests found"

This sounds unrelated. If you think it's a bug, please open a separate issue and provide a reproduction repository.

**Comment by tomekniemiec** [comment]
@Skn0tt to Your information : 
when use 
test.use
failed video is attached to report

when use fixture
failed video is NOT attached to report

IMO is bug
I will try reproduce this on test env and send example
