### ISSUE TITLE
[Feature]: `playwright` should add entries to `.gitignore` in sorted order

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/playwright#33357]
### 🚀 Feature Request

`playwright` should add entries to `.gitignore` in sorted order.

That is, it'd be nice if it added

```
/blob-report/
/playwright-report/
/playwright/.cache/
/test-results/
node_modules/
```

instead of

```
node_modules/
/test-results/
/playwright-report/
/blob-report/
/playwright/.cache/
```

### Motivation

This change would make the entries Playwright adds to a `.gitignore` file cleaner and a bit more readable.

**Comment by Skn0tt** [comment]
Closing as per https://github.com/microsoft/create-playwright/pull/133#issuecomment-2446065791
