### ISSUE TITLE
[Feature]: Debugging "NodeJS Worker" failures

### ISSUE THREAD

**Issue by mastrzyz** [microsoft/playwright#33351]
### 🚀 Feature Request

We need more debugging possibility for when a worker dies/fails. 

Can we include the stack trace?
Can we include this worker failure in the Junit/Test results so we can gather more data on it?

### Example

We had a test run fail with the below, I'm not sure what we can do in our system to fix it? 

```
Error: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues


Failed worker ran 4 tests
```

### Motivation

Improving reliability in our CI/CD system, this is a rare occurrence but something we would like to understand better.

**Comment by Skn0tt** [comment]
Playwright hides internal stacktraces for brevity. This usually helps, but in your case it's detrimental. Set `PWDEBUGIMPL=1` to disable this.

**Comment by mxschmitt** [comment]
Which Node.js version are you on? We saw a similar error in our tests a couple of months ago which was fixed in a minor Node.js release.

**Comment by mastrzyz** [comment]
Yes that probably is the same, Node 20, I remember we having a similar issue in an unrelated step in our CI/CD. I'll enable verbose logging and get to the bottom, of this . thank you!
