### ISSUE TITLE
[Bug]: trace > networt > PATCH method type DONT show request body / data

### ISSUE THREAD

**Issue by mikicymulate** [microsoft/playwright#33359]
### Version

1.48.2

### Steps to reproduce

in Application/playwright.config.ts use :`
trace: "on"

go to any URL that contains any PATCH method with body 

### Expected behavior

trace > networt 
PATCH  should also contain the body of the request like in POST request

### Actual behavior

PATCH  don't record the body 

### Additional context

in the trace i missing 

![Image](https://github.com/user-attachments/assets/265456a3-ffa0-437b-ace1-d94e32cd7ef1)

i can see it in chrome DevTools 
![Image](https://github.com/user-attachments/assets/212f206b-609c-4e66-a944-47b9746840ab)

![Image](https://github.com/user-attachments/assets/410da044-9ea0-4b96-aec8-ca5a436ce2a1)

### Environment

System:
  OS: win 10 / 11
Binaries:
  Node: 20.9.0
  npm: 10.8.3
npmPackages:
  @playwright/test: 1.48.2

**Comment by Skn0tt** [comment]
This sounds like a bug. Could you provide us with a minimal repro of this, so we can take a look?

**Comment by mikicymulate** [comment]
It works on another site. closing
