### ISSUE TITLE
[BUG] generated pdf internal page reference Click is not working on Google drive pdf viewer

### ISSUE THREAD

**Issue by lnxct** [microsoft/playwright#33358]
using your library we are generating PDF file.
inside file we have set internal page reference for jump on each page from index. but its only not working on google drive PDF viewer.
other PDF viewer like adobe PDF viewer is working fine.

so i think as per compatible with google drive PDF viewer at generate PDF time might be something need to miss.

Thanks
Dipen

**Comment by Skn0tt** [comment]
Sounds like a bug in the Google Drive PDF viewer. Feel free to open another issue that follows the bug report template if you found a specific thing that Playwright is doing wrong here. Also, take a look at the `tagged` option to see if anything changed: https://playwright.dev/docs/api/class-page#page-pdf-option-tagged
