### ISSUE TITLE
[Bug]: TypeError: (0 , _expectBundle.EXPECTED_COLOR) is not a function on expect.toHaveValue()

### ISSUE THREAD

**Issue by pascalknupper** [microsoft/playwright#33360]
### Version

1.48.2

### Steps to reproduce

await expect(selector1).toHaveValue(value1); // success
await expect(selector2).toHaveValue(value2); // fails with TypeError: (0 , _expectBundle.EXPECTED_COLOR) is not a function
await expect(selector3).toHaveValue(value3); // fails with TypeError: (0 , _expectBundle.EXPECTED_COLOR) is not a function
await expect(selector4).toHaveValue(value4); // success

### Expected behavior

Assertions for toHaveValue are not failing with TypeError: (0 , _expectBundle.EXPECTED_COLOR) is not a function

### Actual behavior

Some assertions with toHaveValue are failing with TypeError: (0 , _expectBundle.EXPECTED_COLOR) is not a function, some others are successful

### Environment

  System:
    OS: macOS 15.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.98 GB / 32.00 GB
  Binaries:
    Node: 20.11.0 - ~/.asdf/installs/nodejs/20.11.0/bin/node
    npm: 10.2.4 - ~/.asdf/plugins/nodejs/shims/npm
  IDEs:
    VSCode: 1.95.0 - /opt/homebrew/bin/code
  Languages:
    Bash: 5.2.37 - /opt/homebrew/bin/bash
  npmPackages:
    @playwright/test: ^1.48.2 => 1.48.2

**Comment by Skn0tt** [comment]
Interesting! Could you share a reproduction repository with us? There must be something specific to your project that makes this happen.

**Comment by pascalknupper** [comment]
had an issue in my test setup. Passed undefined to toHaveValue(), which was causing the exception

**Comment by nsacerdote** [comment]
I've just faced the same issue, I was passing a number instead of a string to `toHaveText`.
Adding it here to help others 😄
