### ISSUE TITLE
[Bug]: Click function returns to the caller but state in the browser does not react to click

### ISSUE THREAD

**Issue by vmachacek** [microsoft/playwright#33367]
### Version

1.44.0

### Steps to reproduce

This is tricky because it cannot be reproduced outside corporate codebase. 

I call "Click" on the element and Playwright returns to the caller but state on the screen does not change (it should navigate to different screen). It seems to be race condition of some sort, because there is overlay being displayed on the screen. 

the overlay in question has set and all bellow objects including the button
```
pointer-events: none
```

when I override this by another css directive it starts to work. 

### Expected behavior

My expectation is playwright either throws exception or waits and execute or waits to the timeout and I don't have to introduce any hack

### Actual behavior

When Call method is being called nothing happens - no state in the browser is updated and Playwright is continuing execution

### Environment

 System:
    OS: Windows 11 10.0.26100
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
    Memory: 14.41 GB / 63.88 GB
  Binaries:
    Node: 22.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.94.2 - C:\Users\vmach\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.1.16 - C:\Windows\system32\bash.EXE

**Comment by Skn0tt** [comment]
From what you're saying, it sounds like you've found a bug in your application. If you believe it's a bug in Playwright, please provide us with a reproduction case. Maybe you can try to rebuild the button / overlay structure with the CSS properties in some raw HTML?

**Comment by Skn0tt** [comment]
Between Playwright clicking and the click arriving at your handler, there might be something entirely different that prevents it. For example an overlay with `pointer-events: none` that's absorbing all the clicks. Have you tried what happens in your test if you remove that overlay, in case that's possible?

**Comment by vmachacek** [comment]
yes, there is a overlay and once I remove the `pointer-events: none` with `!important` on all elements than it starts to work. However that makes whole bunch of other tests to fail because buttons are being clicked when UI is not ready for it. 
Please allow me one other question: If there is overlay with `pointer-events: none` that is absorbing a click shouldn't PW report failure to click (or wait for overlay to disappear)?

**Comment by Skn0tt** [comment]
> If there is overlay with pointer-events: none that is absorbing a click shouldn't PW report failure to click (or wait for overlay to disappear)?

Absolutely, yes - if Playwright is clicking an unclickable button instead of reporting afailure, that's a bug and we'd like to see if we can fix it. So if you could provide a reproduction, that'd be much appreciated.

**Comment by vmachacek** [comment]
here is the repo https://github.com/vmachacek/playwright-click-issue 

let me describe my though process. 

there is webserver which servers index.html - that is "system under test". Inside this HTML file there after random delay (0-200ms) button is made non clickable via `pointer-events: none`. If the button is clicked successfully the element is shown on a screen. If the button is clicked by PW and the element is in fact not shown on screen than its considered bug. 

On a playwright side there are steps
- click button
- check for visibility

if click succeeds (control flow continues) and element is not visible it throws `SuccessException` which means the bug was reproduced. In my understanding this should not happen. I believe it has something to do with `LocatorClickOptions {Delay = 100 }` which I didn't pay attention before and my QAs use in their tests. I believe that is what causing the issue. 

The repro script might need couple passes (it runs in infinite loop) to hit the sweet spot when timing is just right, stars align and its able to reproduce the bug.

**Comment by pavelfeldman** [comment]
Sorry about the delay, I guess no one wants to build the app locally and run it. I guess you could have a simple 5-liner in HTML instead that would do the same thing?

**Comment by vmachacek** [comment]
@pavelfeldman either take it or leave it, I fixed the issue in my tests by not using delay. The gist is when there is a delay, the .Click() call (when disabled is added inside this delay window) function call still succeeds (which might be by design). Feel free to close

**Comment by dgozman** [comment]
Closing as per above.
