### ISSUE TITLE
[Feature]: FreeBSD Support

### ISSUE THREAD

**Issue by nxjosephofficial** [microsoft/playwright#33368]
### 🚀 Feature Request

It would be good if `playwright` was supporting FreeBSD because I was going to port (porting means packaging a program for FreeBSD) a program about LLMs and `playwright` was the dependency that i couldn't port to FreeBSD. I have ported all other dependencies for that program. You may think that there is not a lot of demand for this feature but I think all projects -at least open-source ones- should support every OS. Thanks in advance.

### Example

I would port programs like [Integuru](https://github.com/Integuru-AI/Integuru) for FreeBSD if I could port `playwright` for FreeBSD and a lot of programs that require `playwright`.

### Motivation

It would be a better project if it were supporting every OS, at least FreeBSD.

**Comment by Skn0tt** [comment]
There are no plans of supporting FreeBSD, see https://github.com/microsoft/playwright/issues/20330.

**Comment by alvar-freude** [comment]
playwright runs on FreeBSD, and I've been using it for several years. However, you have to build it yourself using npm.
A port would still be very useful!

**Comment by mischif** [comment]
@alvar-freude Are you running the browsers on FreeBSD or just controlling them? I'm trying to get Chromium set up but I keep getting errors when I try to download/install the browser.

**Comment by sporkman** [comment]
There is now a port, FWIW… but it's also so sad to see how minimal the changes are to build this on FreeBSD:

https://github.com/freebsd/freebsd-ports/tree/main/www/py-playwright/files

**Comment by alvar-freude** [comment]
> [@alvar-freude](https://github.com/alvar-freude) Are you running the browsers on FreeBSD or just controlling them? I'm trying to get Chromium set up but I keep getting errors when I try to download/install the browser.

sorry for late answer, @mischif: in my case the browser runs fully headless on FreeBSD and playwright controls the browser, both running (in the same) jails.
As @sporkman mentioned: there is a port/package and this is the easiest way to use it.
