### ISSUE TITLE
[Bug]: Wrong test running in parallel within the same file. 

### ISSUE THREAD

**Issue by cha-hin** [microsoft/playwright#33363]
### Version

1.48.2

### Steps to reproduce

**Context**

I have 4 tests in the same file:
```
- A (describe)
  - A1
  - A2
- B
- C
```
A1 and A2 are set to run in parallel under the same "describe".

**Repro steps**

1. Clone my repo at https://github.com/cha-hin/playwright-repro/tree/main
2. Run `npm install`
3. Run `npm run test:ui`
4. Inside the UI mode unfold all tests
5. Click the "Run all" button (the topmost one)
6. You notice that A1, A2 and B run in parallel.

(The same problem occurs in CI mode by running `npm run test`, though it is easier to see it in UI mode).

### Expected behavior

I expect that A1 and A2 run in parallel, then B, then C. 

As follows.

![Image](https://github.com/user-attachments/assets/17be141a-14a6-46f6-a4d7-7ad14b59330d)

### Actual behavior

A1, A2 and B run in parallel while they shouldn't.

### Environment

  System:
    OS: macOS 15.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 67.78 MB / 16.00 GB
  Binaries:
    Node: 20.18.0 - ~/.nvm/versions/node/v20.18.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.9.0 - ~/.nvm/versions/node/v20.18.0/bin/npm
    pnpm: 9.12.2 - ~/Library/pnpm/pnpm
    bun: 1.0.26 - ~/.bun/bin/bun
  IDEs:
    VSCode: 1.94.2 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.48.2 => 1.48.2

**Comment by Skn0tt** [comment]
Playwright uses multiple workers to run your tests, and is working as intended here. The first worker executes tests A1 and A2 in parallel, the second worker starts with B and then continues to C. Could you elaborate on why you think it should be different?

**Comment by anderson1041** [comment]
According to your test example, perform this implementation. In this code, "B" will wait until "A1" and "A2" have finished before starting execution. "C" will be executed right after "B".

``` import { test } from "@playwright/test";

let aCompleted = false;

test.describe("A: Runs children in parallel", () => {
  test.describe.configure({ mode: "parallel" });

  test("A1", async ({ page }) => {
    await page.waitForTimeout(3000);
    console.log("A1");
  });

  test("A2", async ({ page }) => {
    await page.waitForTimeout(3000);
    console.log("A2");
  });

  test.afterAll(() => {
    aCompleted = true;
  });
});

test("B: Should run after 'A' but runs in parallel with 'A'", async ({ page }) => {
  while (!aCompleted) {
    await new Promise(resolve => setTimeout(resolve, 100));
  }
  await page.waitForTimeout(3000);
  console.log("B");
}); ```

**Comment by yury-s** [comment]
The following part of your test code
```js
test.describe("A: Runs children in parallel", () => {
  test.describe.configure({ mode: "parallel" });
```
makes all the tests from describe run in parallel with each other and other tests in the file, so you end up having A1 and A2 running in parallel, and the rest of the tests in the same file running in default mode but in parallel to A1 and A2. Overall there are 3 workers, running:
w1 - A1
w2 - A2
w3 - B, C.

**Comment by cha-hin** [comment]
@yury-s Thank you for your explanation. 

> makes all the tests from describe run in parallel with each other <ins>and other tests in the file</ins>

IMO, considering the aforementioned code, the fact that it makes the tests in the describe runs in parallel along with other tests in the file is highly confusing.

I would assume the statement `test.describe.configure({ mode: "parallel" })` within the describe to orchestrate the workers in a way that would achieve the following execution:

w1 - A1
w2 - A2
--- wait until A1 and A2 finish ---
w1 - B
w1 - C

If this is not the intended behavior, what is the way to achieve it?
