### ISSUE TITLE
[Bug] When using routeWebSocket, sometimes it works, but sometimes it doesn't work

### ISSUE THREAD

**Issue by milliwonkim** [microsoft/playwright#33374]
when i try to mock websocket as i saw in routeWebsocket introduction video on youtube using routeWebSocket in React, then it sometimes works..
![Image](https://github.com/user-attachments/assets/cca8d709-5170-41f0-934a-b7cac397a4f5)

but when i try one more time, then it doesn't work
![Image](https://github.com/user-attachments/assets/f62fc42b-727c-435f-85cc-e27d28fc413d)

i think it's about timing to mock websocket
how can i guarantee to mock websocket like waitForResponse or something?

and can i get solutions for additional mocking websocket solution with not using routeWebsocket?

thanks.

**Comment by Skn0tt** [comment]
Hey @milliwonkim! I'm afraid you didn't follow our bug report template. If you believe there's a bug, please open another issue and include the requested details. A repro is crucial for us to investigate purported bugs. Also, while I like how your screenshot shows test + execution side by side - but please please please don't make any maintainer manually type out code from a screenshot. Paste it into the issue.

> and can i get solutions for additional mocking websocket solution with not using routeWebsocket?

Please open a feature request with your specific usecase for that.
