### ISSUE TITLE
[Bug]: Can't send a websocket message though WebSocketRoute on demand

### ISSUE THREAD

**Issue by Remi-Avec-Un-I** [microsoft/playwright#33370]
### Version

1.48.0

### Steps to reproduce

When you try to send a message though a websocket you are mocking, using the [WebSocketRoute](https://playwright.dev/python/docs/api/class-websocketroute) not in on_message, like in this exemple (i pick this website because you don't need to log in to get a websocket) : 
```py
from playwright.sync_api import sync_playwright, WebSocketRoute
from threading import Thread

def handler(ws: WebSocketRoute):
    ws.connect_to_server()
    Thread(target=send_dummy, args=(ws,)).start()
    ws.on_message(lambda message: ws.send(message))

def send_dummy(ws: WebSocketRoute):
    while True:
        ws.send(input("Enter a message to send: ")) # Here you can send any message you want

p = sync_playwright().start()
context = p.chromium.launch(headless=False)
page = context.new_page()
page.goto("https://www.tradingview.com/markets/") # random page with a websocket used
page.route_web_socket("wss://data.tradingview.com/socket.io/websocket?from=markets%2F&date=2024_10_30-20_24", handler) # you might need to change the end after date=...
page.reload() # for any reason the websocket isn't loaded on the first time
page.wait_for_event("close", timeout=0) # do not let the window close
```

### Expected behavior

I expect a message to be sent though the websocket

### Actual behavior

But it crashes, and do not send the message.

### Additional context

Here is the full error message: 
`
RuntimeError: no running event loop
C:\Users\me\AppData\Local\Programs\Python\Python313\Lib\threading.py:1043: RuntimeWarning: coroutine '_create_task_and_ignore_exception.<locals>._ignore_exception' was never awaited
  self._invoke_excepthook(self)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\me\AppData\Local\Programs\Python\Python313\Lib\threading.py:1043: RuntimeWarning: coroutine 'Channel.send' was never awaited
  self._invoke_excepthook(self)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
`

### Environment

System:
  OS: Windows 10
  CPU: AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx     2.60 GHz
Binaries:
  Python: 3.13.0
  Playwright: 1.48.0

**Comment by Skn0tt** [comment]
Thanks for the nice repro! It seems that our `sync_api` implementation of `WebSocketRoute` isn't properly handling coroutines. Other classes use `self._sync` to do this, but this one doesn't: https://github.com/microsoft/playwright-python/blob/9d6adda814d080b3fa09e96103dc53d7b51bf8f4/playwright/sync_api/_generated.py#L1215

From a first look, it seems that we can get our generator to emit `self._sync` by making [`network.py > WebSocketRoute#send`](https://github.com/microsoft/playwright-python/blob/9d6adda814d080b3fa09e96103dc53d7b51bf8f4/playwright/_impl/_network.py#L674) asynchronous. I'm not sure what that means for `_create_task_and_ignore_exception` though. @mxschmitt could you take a look? I'm happy to make the necessary changes if you point me the right way.

**Comment by mxschmitt** [comment]
Playwright is not thread-safe, its not possible to share a Playwright instance across threads, see [here](https://playwright.dev/python/docs/library#threading).

**Comment by Remi-Avec-Un-I** [comment]
But then is there a way to send a message whenever we want ?

**Comment by mxschmitt** [comment]
You could restructure it a bit like the following:

```python
from typing import Optional
from playwright.sync_api import sync_playwright, WebSocketRoute
from threading import Thread

ws_route: Optional[WebSocketRoute] = None

def handler(ws: WebSocketRoute):
    ws.connect_to_server()
    global ws_route
    ws_route = ws
    ws.on_message(lambda message: ws.send(message))

p = sync_playwright().start()
context = p.chromium.launch(headless=False)
page = context.new_page()
page.route_web_socket("wss://echo.websocket.org/", handler) # you might need to change the end after date=...
page.goto("https://echo.websocket.org/.ws") # random page with a websocket used

while not ws_route:
    print("Waiting for websocket to be connected...")
    page.wait_for_timeout(100)
print("Websocket connected!")

while True:
    value = input("Enter a message to send: ")
    ws_route.send(value) # Here you can send any message you want
    page.wait_for_timeout(100)
```

`input()` is a bit of a tricky one with Playwright, since it would stall the entire event loop. This leads to known issues / limitations, see [here](https://playwright.dev/python/docs/library#timesleep-leads-to-outdated-state) (same issue like `time.sleep`). So ideally I would recommend asyncio with https://pypi.org/project/aioconsole/. This would look like this, then you don't need the `wait_for_timeout(100)`.

```python
import asyncio

import aioconsole
from playwright.async_api import async_playwright, WebSocketRoute

async def main():
    ws_route_future: asyncio.Future[WebSocketRoute] = asyncio.Future()

    def handler(ws: WebSocketRoute):
        ws.connect_to_server()
        ws_route_future.set_result(ws)
        ws.on_message(lambda message: ws.send(f"Received in Playwright and redirecting back: {message}"))

    p = await async_playwright().start()
    context = await p.chromium.launch(headless=False)
    page = await context.new_page()
    await page.route_web_socket("wss://echo.websocket.org/", handler) # you might need to change the end after date=...
    await page.goto("https://echo.websocket.org/.ws") # random page with a websocket used

    print("Waiting for websocket to be connected...")
    ws_route = await ws_route_future
    print("Websocket connected!")

    while True:
        value = await aioconsole.ainput("Enter a message to send: ")
        ws_route.send(value) # Here you can send any message you want

asyncio.run(main())

```
