### ISSUE TITLE
[Docs]: Document how to run with branded browsers such as Chrome outside test scenarios

### ISSUE THREAD

**Issue by SamStephens** [microsoft/playwright#33372]
### Page(s)

https://playwright.dev/python/docs/next/library
https://playwright.dev/python/docs/next/browsers
https://playwright.dev/python/docs/next/api/class-browsertype
https://playwright.dev/python/docs/next/api/class-playwright

### Description

There is no documentation I can find of how to specify a branded browser such as Chrome outside of a testing scenario, when starting Playwright in the style:

```
with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
```

https://playwright.dev/python/docs/next/library documents the basics, but does not make it clear how to use a branded browser.

https://playwright.dev/python/docs/next/browsers documents how to install branded browsers such Chrome. It also documents the flags to pass to test runs to use Chrome. But it does not document how outside tests.

https://playwright.dev/python/docs/next/api/class-browsertype and https://playwright.dev/python/docs/next/api/class-playwright both deal with chromium/firefox/webkit, but not a branded browser.

**Comment by Skn0tt** [comment]
It's documented here, on the `launch` call: https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch-option-channel

`p.chromium.launch(channel="chrome")`

If you're using an IDE, you should probably also see it in the docstrings. Does that solve your question?

**Comment by SamStephens** [comment]
That's what I was looking for, thanks. Would you consider linking to that from https://playwright.dev/python/docs/browsers#google-chrome--microsoft-edge, I had trouble finding it.
