### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "parentURL" argument must be of type string or an instance of URL.

### ISSUE THREAD

**Issue by valery-lavrik** [microsoft/playwright#33391]
### Version

1.48.2

### Steps to reproduce

npm playwright test

### Expected behavior

Testing will begin

### Actual behavior

TypeError [ERR_INVALID_ARG_TYPE]: The "parentURL" argument must be of type string or an instance of URL.

### Additional context

I got an error. I am using node version 20.6.1
. It is not possible to update node js due to the strict security policy in the company. Critical vulnerabilities have been found in the latest version of node js.  

In any case, I think that node js version 20.6.1 is not so old that it should not be supported. Is it possible to release a fix?

### Environment

win 10.
nodejs 20.6.1
playwright 1.48.2

**Comment by mxschmitt** [comment]
Only the latest 18.X, 20.X, 22.X versions are supported as of today. We recommend updating.
