### ISSUE TITLE
[Feature]: Provide error stack-traces evaluating source-maps

### ISSUE THREAD

**Issue by MiladSadinam** [microsoft/playwright#33398]
### 🚀 Feature Request

Playwright documentation (https://playwright.dev/docs/api/class-consolemessage) recommends the following code to retrieve console errors:
```typescript
page.on('console', msg => {
  if (msg.type() === 'error')
    console.log(`Error text: "${msg.text()}"`);
})
``` 

We use this to create a simple trace for failed tests on our CI system. Our CI system uses minefield builds but with generated source maps. Still, `msg.text()` ignores any source maps, making the stack trace useless. It would be very helpful if Playwright provided stack traces that already took source maps into account.

### Motivation

Provide meaningful stack traces in CI systems that use minified builds because of performance considerations.

**Comment by yury-s** [comment]
This is something you need to address in the web app/its build configuration or implement on top of Playwright. Playwright doesn't do anything specific for the messages in the web page in browser.

**Comment by vctqs1anz** [comment]
Hi @yury-s  I know this issue has been closed for a while, but I’m also looking for something similar.

Even though the application provides source maps, I can only see the mapped error traces in the Playwright Chrome while running tests locally. 

However, this information isn’t stored in Playwright traces, which makes it quite difficult for us to trace errors when tests are running in CI.
