### ISSUE TITLE
[Feature]: Add `Locator.not`

### ISSUE THREAD

**Issue by ruifigueira** [microsoft/playwright#33394]
### 🚀 Feature Request

I propose a new function `Locator.not` to complement `Locator.and` and  `Locator.or`.

### Example

In the following test, if I want to obtain the `div` element that is not a button:

```ts
test('filter', async ({ page }) => {
  await page.setContent(`
    <div role="button">button</div>
    <div>generic</div>
  `);
  await expect(page.locator('div').not(page.getByRole('button'))).toHaveCount(1);
});
```

### Motivation

`:not` CSS pseudo-class only supports CSS selectors, so it's not possible to use it with more advanced locators.

Besides, having `Locator.and` for intersections, `Locator.or` for union, it makes sense to have `Locator.not` for differences and therefore cover more set operations.

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/14136, please upvote that issue instead.

**Comment by ruifigueira** [comment]
Ok, thanks, I searched for a similar one but apparently not with the right keywords.
