### ISSUE TITLE
A big thank you!

### ISSUE THREAD

**Issue by osmenia** [microsoft/playwright#3339]
Hi,

I want to thank you for developing Playwright, a wonderful library.

The library is great, but the library wouldn’t be so good if it didn’t have amazing support. When we have a problem, in a short period of time someone answers our questions and helps us. I really appreciate that.

I really like that the voice of the user is heard and the user suggestion is taken into consideration and implemented.

I am very grateful for your development and support.

**A big thank you to all contributors!**

 @pavelfeldman @mxschmitt @dgozman @aslushnikov @arjun27 @yury-s @rwoll @kblok .....

**Comment by arjun27** [comment]
Thank you for the kind words, @osmenia. I'm glad that we could help :). I'll close this issue for now – appreciate that you filed it.
