### ISSUE TITLE
How to create 'Browser' CDP session with persistent context?

### ISSUE THREAD

**Issue by MoeBazziGIT** [microsoft/playwright#33405]
Hello all. Normally, you can get a 'Browser' CDP session object by using Playwright's `Browser.newBrowserCDPSession()`. However, it is not possible to get the Browser object for a persistent context. This is because, for persistent contexts, calls to `Context.browser()` return `null` (idk why). So, my question is, is there another way to get the Browser object of a persistent context, or is there another way to create a 'Browser' CDP session in Playwright?

**Comment by yury-s** [comment]
This doesn't sound like a bug or feature request, please use our [community resources](https://playwright.dev/community/welcome) for general questions. If you think this is a bug in Playwright, please open a new issue and follow the bug template.
