### ISSUE TITLE
Difficulty Automating Key Press for Fn + Arrow Down Key in Test Cases

### ISSUE THREAD

**Issue by akshayakunduru** [microsoft/playwright#33418]
We are facing challenges automating test cases that require the combination of the Fn key and the Arrow Down key. On macOS, we attempted to simulate Fn + Arrow Down as the 'End' key. We tried to press fn key keyboard.press, keyboard.down, and keyboard.up functions, but we are not successful. We tried several methods using Playwright’s keyboard.press, keyboard.down, and keyboard.up functions to emulate this key press sequence. Despite these efforts across different platforms (macOS and others like Linux), the Fn key is not registering properly during automation, and the intended functionality is not achieved. Multiple attempts to resolve this issue have been unsuccessful so far. Added a code snippet for reference
if (process.platform === "darwin") {
            // macOS: fn + down arrow is represented as 'End'
            // await page.keyboard.press('End');
            await page.keyboard.down('Fn');
            await page.keyboard.press('ArrowDown');
            await page.keyboard.up('Fn'); // Release Fn key
        } 
else {
            // Fallback for other platforms if necessary (Linux, etc.)
            await page.keyboard.down('Shift'); 
            await page.keyboard.press('ArrowDown'); // Simulate Shift+down arrow
            await page.keyboard.up('Shift');
        }

**Comment by yury-s** [comment]
`Fn+ArrowDown` generates `PageDown` key event on macOS (key code = 34)
`Fn+ArrowUp` generates `PageUp` key event on macOS (key code = 33)

You can do  
```ts
  await page.keyboard.press('PageDown');
  await page.keyboard.press('PageUp');
```
