### ISSUE TITLE
[Bug]: Attachments disappeared from azure pipeline

### ISSUE THREAD

**Issue by ashevchenkosps** [microsoft/playwright#33415]
### Version

v1.46.1-noble

### Steps to reproduce

Hello! I've updated the playwright version from 1.29 to 1.46, and now I don't see the attachments, only zero state. I see all results in my Azure artifacts but can't determine why the attachments disappeared.

My azure-pipeline.yml task is the same as here: https://github.com/microsoft/azure-pipelines-tasks/issues/19815
    - task: PublishTestResults@2
      displayName: 'Publish test results'
      inputs:
        testResultsFiles: '**/*.xml'
        searchFolder: '$(Build.ArtifactStagingDirectory)/results/reports/'

When I roll back to 1.29, it works. 

**Also**, it started to add hash in the middle of the long test names inside results-e2e-raw. 

### Expected behavior

I can see the attachments in the azure pipeline => tests => attachments => *the list with the attachments*

### Actual behavior

I see zero state in the Attachments sub-tab, but my artifact has all required folders, reports, and screenshots;

### Environment

playwright: 1.46.1
docker image: mcr.microsoft.com/playwright:v1.46.1-noble
node: 16.20.2 OR 20
reporter: JUnit

**Comment by yury-s** [comment]
Please follow the our bug template and provide a minimal self-contained project that we could run locally to reproduce the problem. We cannot tell what your code does and what could have broken without a repro.

**Comment by ashevchenkosps** [comment]
Hello, @yury-s! It will be hard to create a self-contained project to reproduce this bug, but I hope that part of my yml file can help. It work on playwright  1.29, but doesn't on playwright 1.46
```    steps:
    - task: DownloadBuildArtifacts@1
      displayName: 'Download test results artifacts'
      continueOnError: true
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'results'
        downloadPath: '$(Build.ArtifactStagingDirectory)'
        itemPattern: |
          **
          !results/auth/**
    - task: PublishTestResults@2
      displayName: 'Publish test results'
      inputs:
        testResultsFiles: '**/*.xml'
        searchFolder: '$(Build.ArtifactStagingDirectory)/results/reports/'
    - task: TestingInspector@1
      displayName: 'Publish log files and failed test screenshots'
      inputs:
        screenshotsFolder: '$(Build.ArtifactStagingDirectory)/results/screenshots'
        logsFolder: '$(Build.ArtifactStagingDirectory)/results/logs'```

**Comment by yury-s** [comment]
> 1)file names have been changed: Some hash appears in the middle of the name of files.

They did change after this PR https://github.com/microsoft/playwright/pull/29725. The output file name is an implementation detail, if your pipeline relies on them, you should update the code. Attachment names stay intact.

> 2) JUnit reporter has different attachment paths

This an effect of the change mentioned above.

You are probably affected by this bug fix in the attachment path resolution: https://github.com/microsoft/playwright/pull/27024, note that it is now `../../results-e2e-<...>` where it was `results-e2e-<...>`. This likely confuses your CI configuration.

Does this help?

**Comment by ashevchenkosps** [comment]
I found out that after updating to 1.46 from 1.29, it change my screenshot names in the screenshot folder: 
``` 
1.29
SPS_ArchiveDocs Not_archived_if_server_unavailable.png
1.46
SPS_ tests_DocActions_Archi_a94c8_hived_if_server_unavailable.png 
```

**Comment by yury-s** [comment]
>  but now it includes folder names:

See my previous comment about path resolution change, it's probably an effect of that.

If you think there is a bug in Playwright, please share a minimal reproduction which we could run locally. It's hard to tell where the paths you mention come from without seeing the source code.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
