### ISSUE TITLE
[Feature]: Add timestamp to all error messages for failed expectations

### ISSUE THREAD

**Issue by ryanrosello-og** [microsoft/playwright#33412]
### 🚀 Feature Request

I would like to add the following timestamp to all error messages for failed assertions

### Example

![Image](https://github.com/user-attachments/assets/db238c40-5053-4d69-a287-9089ffd78005)
![Image](https://github.com/user-attachments/assets/4263ba77-bb7a-4496-ad3d-eb694053a5cc)
![Image](https://github.com/user-attachments/assets/fe454845-4dcc-4258-95ec-d6b35a6da73b)

### Motivation

Currently is its quite annoying to figure out the exact time a test fails.

**Comment by yury-s** [comment]
Can you elaborate on why you want to see the timestamp in the output? There is already a timestamp on the report itself and displaying the time in every test would clutter the UI.
