### ISSUE TITLE
How to handle multiple tabs in Page Object Model with fixtures

### ISSUE THREAD

**Issue by qaitive** [microsoft/playwright#33410]
### Please do not submit this issue.

- [x] I understand

**Comment by qaitive** [comment]
I need to click button on the first page and then to open new tab and continue with testing.  

type MyFixtures = {
    page1: Page1
    page2: Page2

}

export const test = base.extend<MyFixtures>({
    page1: async ({ page }, use) => {
        await use(new Page1(page))
    },

    page2: async ({ page }, use) => {

        await use(new Page2(page))
    },
  

})

when I call functions from pages from test  it doesnt work . If  I create instances in tests from pom/page1 pom/page2 it works. So it works without using fixtures

**Comment by yury-s** [comment]
This doesn't sound like a bug or feature request, please use our [community resources](https://playwright.dev/community/welcome) for general questions. If you think this is a bug in Playwright, please open a new issue and follow the bug template.

**Comment by qaitive** [comment]
It's not a bug its just tricky to handle this.
Could someone help me with this?
