### ISSUE TITLE
[Bug]: toMatchSnapshot does not strip trailing newline from text snapshot

### ISSUE THREAD

**Issue by karlhorky** [microsoft/playwright#33416]
### Version

1.48.2

### Steps to reproduce

1. Create a text based snapshot following a process similar to [the "Non-image snapshots" docs section](https://playwright.dev/docs/test-snapshots#non-image-snapshots)
2. Observe passing Playwright test
3. Open and save snapshot in editor which adds trailing newline in file (eg. GitHub file editor or VS Code with trailing newline settings)
4. 💥 Observe that the Playwright test no longer passes

Also, attempts to remove the trailing line using the same editor will likely fail, without changing settings.

### Expected behavior

`.toMatchSnapshot()` with a text snapshot is not sensitive to trailing newline in snapshot file

### Actual behavior

`.toMatchSnapshot()` with a text snapshot is sensitive to trailing newline in snapshot file

### Implementation suggestion

Maybe the snapshot can be forced to always have a trailing newline, so that there does not need to be any new newline stripping.

### Additional context

- @spcoder opened an issue which goes in a slightly similar direction in June 2023, but not with the same conclusions #23690

### Alternatives considered

Avoiding manually updating snapshots would avoid the problem, but quick manual edits to snapshots is a nice option to have.

### Environment

```
  System:
    OS: macOS 15.1
    CPU: (8) arm64 Apple M1
    Memory: 106.84 MB / 16.00 GB
  Binaries:
    Node: 20.18.0 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.8.2 - /opt/homebrew/bin/npm
    bun: 1.1.30 - /opt/homebrew/bin/bun
  IDEs:
    VSCode: 1.95.1 - /opt/homebrew/bin/code
  Languages:
    Bash: 5.2.0 - /opt/homebrew/bin/bash
```

**Comment by yury-s** [comment]
This is working as intended, Playwright does not change the buffer it compares to the snapshot. If you want to strip off trailing whitespaces you can call `.trim()` on the string that you pass to `expect()`.  The whitespaces are normalized by web assertions such as [`toHaveText()`](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-have-text) and `toContainText`, you can those instead.

**Comment by karlhorky** [comment]
I agree on a few points: 

1. Making alterations to the buffer is an unusual exception to make
2. Accepting one type of alteration may prompt requests for other types of alterations
3. From a software "purity" perspective, it seems impure

I actually avoided reporting this issue a few times because of this.

But I think the downsides, inconsistencies and further details outweigh this:

4. Calling `.trim()` on the string passed to `expect()` was my first workaround too, but it is actually the opposite change to what is needed. Since there is an extra newline added to the snapshot by various common tools while editing, actually the workaround is to \*add\* a newline to the string passed to `expect()`, which is counterintuitive, as we both just demonstrated.
5. Other widely-adopted text snapshot formats like the Jest snapshot format do not have problems with trailing newlines 
6. It is a Unix convention to write files with trailing newlines

So actually what I'm asking for is for Playwright to consider interoperability of its snapshot format, either: 

A. Simpler: Add a newline to the `expect()` string by default before comparing it with the file
B. Adopt and replicate the widely-adopted, battle-tested Jest snapshot format (also used by Vitest)

**Comment by karlhorky** [comment]
## Workaround (interoperable Playwright snapshot test)

Add a newline to your string passed to `expect()` before calling `.toMatchSnapshot()`:

```ts
import { test, expect } from '@playwright/test';

test('example test', async ({ page }) => {
  await page.goto('https://playwright.dev');
  expect(await page.textContent('.hero__title') + '\n').toMatchSnapshot('hero.txt');
});
```
