### ISSUE TITLE
When I use webkit  as the mobile browser, the website is loading as in desktop mode.But When I tries it with chromium its working as expected.

### ISSUE THREAD

**Issue by rajaduraip2** [microsoft/playwright#33411]
### Please do not submit this issue.

- [x] I understand

**Comment by rajaduraip2** [comment]
Please try the below code-   `const {test,expect,devices, chromium,webkit}=require('@playwright/test');

const device= devices['iPhone 13'];
test('Hadle Alerts',async()=>{
const browser=await webkit.launch();
const context= await browser.newContext({
    ...device
});

const page= await context.newPage();

    await page.goto('https://tutorialsninja.com/demo/');
  
await page.pause();
  page.on('dialog',async dialog=>{
        expect(dialog.message()).toContain('Press a button!');
        console.log(dialog.message());
        dialog.accept();
    })
    await page.locator('div button#confirmBtn').click();
await page.waitForTimeout(5000);

})`

**Comment by yury-s** [comment]
This doesn't sound like a bug or feature request, please use our [community resources](https://playwright.dev/community/welcome) for general questions. If you think this is a bug in Playwright, please open a new issue and follow the bug template.
