### ISSUE TITLE
[Bug]: Memory leak with UI mode (macOS)

### ISSUE THREAD

**Issue by notngan** [microsoft/playwright#33424]
### Version

1.48.2

### Steps to reproduce

1. Run tests with `npx playwright test --ui`
2. The UI mode is unable to start
3. Observe Activity Monitor, you should see the memory usage increases rapidly as many "node" processes started

### Expected behavior

 Playwright UI mode should start and display the UI without rapid increase in memory usage.

### Actual behavior

The Playwright UI mode fails to start. Open Activity Monitor and observe the processes. There is a rapid increase in memory usage as multiple "node" processes start. The computer may become unresponsive high memory consumption.

### Additional context

Related to a closed issue https://github.com/microsoft/playwright/issues/33086

### Environment

System:
  OS: macOS Sonoma 14.7
  Chip: Apple M1 Pro
  Memory: 14.84 GB / 16 GB
Binaries:
  Node: 16.10
  pnpm: 7.33.6
IDEs:
  WebStorm 2024.2.4
npmPackages:
  @playwright/test: ^1.48.2 => 1.48.2

**Comment by siddharth2023** [comment]
I keep seeing https://github.com/microsoft/playwright/issues/33086 on 1.48.2 as well.

Has been happening quite a bit the last 3-4 days

**Comment by yury-s** [comment]
@notngan I cannot reproduce it. Note that Node 16 is [no longer supported](https://playwright.dev/docs/intro#system-requirements). Please try with newer Node, if the problem persists please share a project where it happens, so that we could reproduce it locally.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by ScarletMcLearn** [comment]
Facing similar issue: https://github.com/microsoft/playwright/issues/36337

**Comment by ScarletMcLearn** [comment]
@notngan @siddharth2023  please do give it a look and suggest if you faced your issue under similar conditions!

**Comment by siddharth2023** [comment]
I haven't faced this recently.

**Comment by ScarletMcLearn** [comment]
I have been facing it persistently for long tests
