### ISSUE TITLE
How to write E2E test where baseURL is not fixed, it needs to run on jenkins parameter.

### ISSUE THREAD

**Issue by kotharismeet-nfd** [microsoft/playwright#33421]
### Please do not submit this issue.

- [x] I understand

**Comment by kotharismeet-nfd** [comment]
For eg we have two branches feat/dev-a and feat/dev-b, than in current CI/CD pipline https://feat-dev-a.apps.provo-staging.myorderbox.com and https://feat-dev-b.apps.provo-staging.myorderbox.com are build & deployed, than how to write test which runs in jenkins pipline as stage everytime respective ones are triggered to build.

**Comment by yury-s** [comment]
This doesn't sound like a bug or feature request, please use our [community resources](https://playwright.dev/community/welcome) for general questions. If you think this is a bug in Playwright, please open a new issue and follow the bug template.
