### ISSUE TITLE
[Regression]: Playwright VSCode Extension fails to use playwright folder as root

### ISSUE THREAD

**Issue by anupamck** [microsoft/playwright#33435]
### Last Good Version

1.43.1

### First Bad Version

1.44.0

## To reproduce:

1. Clone the repository: https://github.com/anupamck/playwright-regression-example 

#### The `apps/playwright` folder is considered the root of the project (default behaviour):

2.  Install dependencies with `pnpm i` (you might need to do this in the apps/playwright folder) -> 1.43.1 should be installed
3.  Run one of the example tests by using the UI via the VSCode Playwright Extension

Expected: Due to line 6 of the file playwright.config.ts, the following log should appear in the console: AllYourBaseAreBelongToUs

Actual: Said log appears in the console

#### The monorepo root is considered the root of the project (regression):

2.  Change the playwright version to 1.44.0 in the apps/playwright/package.json file
3.  Delete all node_modules folders in the monorepo
4.  Clear the pnpm store with `pnpm store prune`
5.  Install dependencies with `pnpm i` (you might need to do this in the apps/playwright folder) -> 1.44.1 should be installed
6.  Run one of the example tests by using the UI via the VSCode Playwright Extension

Expected: Due to line 6 of the file playwright.config.ts, the following log should appear in the console: `AllYourBaseAreBelongToUs`

Actual: The log `undefined` appears in the console

#### To fix this, you need to change the env path in the playwright.config.ts file to the monorepo root (fix).

7.  Change the env path in the playwright.config.ts file to the monorepo root: `dotenv.config({ path: "apps/playwright/.env" });`
8.  Run one of the example tests by using the UI via the VSCode Playwright Extension

Expected: Due to line 6 of the file playwright.config.ts, the following log should appear in the console: `AllYourBaseAreBelongToUs`

Actual: Said log appears in the console

### Expected behavior

In a monorepo setup, I continue to expect that the VSCode Extension automatically considers the `apps/playwright`folder, where the Playwright config file is found, to be the root for execution. 

### Actual behavior

The monorepo root is considered to be the root for execution. 

### Additional context

Note: This problem occurs only with the VSCode Extension UI execution and not with CLI execution. I have also not added any other configuration to my VSCode Extension, for example, via `settings.json`. I found a workaround to this problem by defining a `project.code-workspace` folder and opening the project from the right workspace for Playwright. 

### Environment

  System:
    OS: macOS 15.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 27.60 GB / 64.00 GB
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 9.12.3 - ~/.nvm/versions/node/v20.11.1/bin/pnpm
  IDEs:
    VSCode: 1.95.1 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.43.1 => 1.44.0

**Comment by yury-s** [comment]
The `cwd` did indeed change under VSCode extension a few releases ago to behave similar to `npx playwright test` (in the workspace root directory). You should change your config to not depend on `cwd`:

```ts
dotenv.config({
  path: path.join(__dirname, '.env')
});
```

**Comment by anupamck** [comment]
@yury-s - Thank you for the quick feedback. That makes sense. 

I couldn't find this change anywhere in the Release Notes. Is that normal? Or did I overlook something?

**Comment by fregante** [comment]
This change doesn't really make sense to me. All the paths in `package/playwright.config.ts` are relative to the config file, why would it be different for cwd? I've been using `import 'dotenv/config'` to load `$pwd/.env` globally, now VSC breaks this pattern.

[Monorepo](https://nx.dev/blog/introducing-playwright-support-for-nx) [tools](https://turborepo.com/docs/guides/tools/playwright) suggest having a playwright.config.ts file per project and running `playwright test` from within the project, not from root.
