### ISSUE TITLE
[Bug]: Playwright test arguments are ignored when running npm scripts in Powershell on Node v22

### ISSUE THREAD

**Issue by brk9394** [microsoft/playwright#33437]
### Version

1.48.2

### Steps to reproduce

1. Create a new default Playwright example project (https://playwright.dev/docs/intro#installing-playwright)
1. In `package.json`, add a test script to run playwright test
    ```
    "scripts": {
        "test": "playwright test"
    },
    ```
1. In Powershell, run the test script
    ```
    npm run test -- --list
    ```

### Expected behavior

- The arguments following "--" should be passed to Playwright
- The tests should be listed (and not run) as they are in Node v20

```
PS C:\git\pw-demo9> nvm use 20.18.0
Now using node v20.18.0 (64-bit)
PS C:\git\pw-demo9> npm run test -- --list

> pw-demo9@1.0.0 test
> playwright test --list

Listing tests:
  [chromium] › example.spec.ts:3:5 › has title
  [chromium] › example.spec.ts:10:5 › get started link
Total: 2 tests in 1 file
```

### Actual behavior

- All arguments following "--" are ignored
- The tests are run instead of being listed

```
PS C:\git\pw-demo9> nvm use 22.11.0
Now using node v22.11.0 (64-bit)
PS C:\git\pw-demo9> npm run test -- --list

> pw-demo9@1.0.0 test
> playwright test


Running 2 tests using 2 workers
  2 passed (3.1s)
```

### Environment

```
  System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 13.66 GB / 31.73 GB
  Binaries:
    Node: 22.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.95.1 - C:\Users\<REDACTED>\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.48.2 => 1.48.2
```

**Comment by mxschmitt** [comment]
In PowerShell you need to do:

     npm run test "--" --list

Without the quotes, PowerShell would interpret the `--` as its own operator rather than passing it to npm as an argument. 

Does this work for you?

**Comment by brk9394** [comment]
@mxschmitt yes, the quoted  "--" works in Node v22! Thanks!

In Node v20 it works without having the quotes.
E.g. 
```
npm run test -- --list
```

**Comment by mxschmitt** [comment]
Looks like its this upstream bug: https://github.com/npm/cli/issues/7375

**Comment by brk9394** [comment]
Thanks Max.
Yeah that's definitely the same bug. In case anyone else finds this thread, another workarounds are to use a triple-dash, or a double-double dash, like so:
```
npm test --- --list
npm test -- -- --list
```
