### ISSUE TITLE
Playwright component testing doesnot work with yarn pnp

### ISSUE THREAD

**Issue by pan-alexey** [microsoft/playwright#33445]
### Please do not submit this issue.

- [x] I understand

**Comment by pan-alexey** [comment]
Running 3 tests using 3 workers
Error: @vitejs/plugin-react tried to access vite (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
Required package: vite (via "vite/package.json")

In yarnrc.yaml:
  "@vitejs/plugin-react@*":
    peerDependencies:
      "vite": "*"

**Comment by yury-s** [comment]
This doesn't sound like a bug or feature request, please use our [community resources](https://playwright.dev/community/welcome) for general questions. If you think this is a bug in Playwright, please open a new issue and follow the bug template.
