### ISSUE TITLE
[Bug]: Expect error message is visible despite of test passed

### ISSUE THREAD

**Issue by Aroot42** [microsoft/playwright#33447]
### Version

1.48.2

### Steps to reproduce

```
import { expect, test } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('https://www.bing.com/');
    await page.waitForTimeout(5000);

    expect(await page.locator('#bLogo').getAttribute('aria-label'), 'Incorrect aria-label').toEqual(
        'Welcome to Bing Search'
    );
});
```

### Expected behavior

Expect error message 'Incorrect aria-label' is not displayed in the report is test passed.

### Actual behavior

Expect error message is visible despite of test passed
![Image](https://github.com/user-attachments/assets/ff2a0033-8881-476b-a3ef-93147fd9a6b2)

### Environment

  System:
    OS: Windows 11 10.0.22621
    Memory: 2.52 GB / 15.95 GB
  Binaries:
    Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.95.0 - C:\Users\1aroo\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.48.2 => 1.48.2

**Comment by yury-s** [comment]
This is working as expected, see [this page](https://playwright.dev/docs/test-assertions#custom-expect-message): "This message will be shown in reporters, both for passing and failing expects, providing more context about the assertion."

You can rephrase the message to describe expected result when the test passes:
```js
 expect(await page.locator('#bLogo').getAttribute('aria-label'), 'aria-label should be correct').toEqual(
        'Welcome to Bing Search'
    );
```
