### ISSUE TITLE
[Question] Is there a way to get NodeId from an elementHandle?

### ISSUE THREAD

**Issue by VikramTiwari** [microsoft/playwright#3345]
NodeId: https://chromedevtools.github.io/devtools-protocol/tot/DOM/#type-NodeId

Goal: I am trying to force a pseudo state on a DOM node using https://chromedevtools.github.io/devtools-protocol/tot/CSS/#method-forcePseudoState

NOTE: Using CDP to get nodeId doesn't work because the node in question is inside a cross-origin iframe

**Comment by aslushnikov** [comment]
I don't think there's a good way.. But #3347 should help! Let me close this as dupe.
