### ISSUE TITLE
[BUG] Goto fails to navigate to Power Platform App Id

### ISSUE THREAD

**Issue by dickinsonr** [microsoft/playwright#33452]
When using playwright goto() MS Power Platform fails to navigate to the appid of a power app.  This worked fine for months until recently but now drops at the Power platform app gateway page and has to be redirected to the app by a click.  Using the URL manually in the browser works fine.
The code is very simple and just uses baseUrl and a goto('/'):

  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    baseURL: process.env.TEST_URL ?? 'https://<env>.crm11.dynamics.com/main.aspx?forceUCI=1&appid=<id>',
  },

Code with workaround to complete navigation:

export async function redirectToPCG(page) {
    await page.goto('/')
    try {
        await page.frameLocator('iframe[title="AppLandingPage"]').getByLabel('Property & Compensation').click()
    } catch (error) {
        console.log("Not on the Power Apps page?")
    }
}

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
