### ISSUE TITLE
[BUG]Test execution hangs in random

### ISSUE THREAD

**Issue by vrknetha** [microsoft/playwright#3346]
**Context:**
- Playwright Version: 1.3.0
- Operating System: Ubuntu 18
- Node.js version: 12.x
- Browser: Chromium

Since playwright 1.2 the execution hangs in random and does not proceed in the bitbucket pipeline. But, it works fine with version 1.0.2. I thought it might be due to some dependencies or memory issues with CI/CD. I tried everything possible, Using a custom-built docker image with all the dependencies mentioned in the official docker image. Now, i am much confident that it is something wrong with the version itself.

When i downgrade the playwright to 1.0.2. It works flawless. I am giving a [link ](https://drive.google.com/file/d/1f_ws1CGUMa226DSzS9q1WaRjs1D_5nkL/view?usp=sharing)of the logs generated with pw:* and one more build with pw:api . I need this to be fixed. Just struck on 1.0.2 and cannot update further. Please look into it.
[pipelineLog-3987.txt](https://github.com/microsoft/playwright/files/5042774/pipelineLog-3987.txt)

Is it possible to add more logging to know the issue?. Even jest won't timeout the test case. I suggest you to run the test cases once in Bitbucket using playwright image.

Using:

"jest": "26.0.1",
"jest-playwright-preset": "^1.3.0",
"playwright": "^1.3.0",
"playwright-core": "^1.3.0"

**jest.config.js**
```javascript
module.exports = {
	verbose: true,
	globals: {
		'ts-jest': {
			tsConfig: './tsconfig.test.json'
		}
	},
	preset: 'jest-playwright-preset',
	transform: {
		'^.+\\.ts$': 'ts-jest'
	},
	testMatch: ['**/playwright/e2e/**/*.test.ts'],
	reporters: [
		'default',
		[
			'jest-junit',
			{
				outputDirectory: './test-reports',
				outputName: 'results.xml',
				usePathForSuiteName: true,
				classNameTemplate: '{classname}-{title}'
			}
		],
		['@vrknetha/jest-testrail', {project_id: '1', suite_id: '1'}]
	],
	testRunner: 'jest-circus/runner',
	testEnvironment: './customEnvironment.js',
	testTimeout: 100000,
	setupFilesAfterEnv: ['expect-playwright']
};
```
**jest-playwright.config.js**
```javascript
// https://github.com/mmarkelov/jest-playwright/#configuration
module.exports = {
	launchOptions: {
		headless: true,
		ignoreDefaultArgs: ['--disable-extensions'],
		args: [
			'--no-sandbox',
			'--disable-setuid-sandbox',
			'--disable-dev-shm-usage',
			'--ignore-certificate-errors',
			'--unsafely-treat-insecure-origin-as-secure=https://localhost:4200/',
			'--disable-notifications'
		]
	},
	contextOptions: {
		ignoreHTTPSErrors: true
	},
	browsers: ['chromium']
};
```
**customenvironment.js**
```javascript
const PlaywrightEnvironment = require('jest-playwright-preset/lib/PlaywrightEnvironment').default;
const {saveVideo} = require('playwright-video');

class CustomEnvironment extends PlaywrightEnvironment {
	async setup() {
		await super.setup();
		// Your setup
	}

	async teardown() {
		// Your teardown
		await super.teardown();
	}

	async handleTestEvent(event, state) {
		if (event.name === 'test_start') {
			const parentName = event.test.parent.name.replace(/\W/g, '-');
			const specName = event.test.name.replace(/\W/g, '-');
			await saveVideo(this.global.page, `${process.cwd()}/playwright/videos/${parentName}_${specName}.mp4`);
		}

		if (event.name === 'test_done' && event.test.errors.length > 0) {
			const parentName = event.test.parent.name.replace(/\W/g, '-');
			const specName = event.test.name.replace(/\W/g, '-');
			await this.global.page.screenshot({
				path: `${process.cwd()}/playwright/screenshots/${parentName}_${specName}.png`
			});
		}
	}
}

module.exports = CustomEnvironment;
```

**Comment by dgozman** [comment]
Thank you for the logs! I looked at them:
- `pipelineLog-3987.txt` seems to *not* be stuck. At least from the logs, every Playwright api call has finished, the last one being `page.click('a[role="button"]')`.
- `pipelineLog-3988.txt` is stuck waiting for `xpath=//button[@name='__CONFIRM__']` selector on `https://www.facebook.com/v6.0/dialog/oauth?....` (there are many query params in that url). Page navigated there after a `page.click("xpath=//button[@id='loginbutton']")`. It seems like authentication did not work for some reason, or perhaps you've got a different oauth page from facebook auth, not the one you've expected?
