### ISSUE TITLE
[Feature]: Allow to set a custom step name for a custom matcher

### ISSUE THREAD

**Issue by raythurnvoid** [microsoft/playwright#33464]
### 🚀 Feature Request

Currently returning a `name` from a custom matcher doesn't seems to have any effect and using test.step inside a custom matcher cause the step name to be duplicated.

Allow any of this 2 ways to set a custom step name

### Example

In this case i'm trying to use both the `name` and the `test.step` to accomplish this but only with partial success.

```ts
export const expect = expectBase.extend({
  toMatchTextSnapshot: toMatchTextSnapshot,
});

async function toMatchTextSnapshot(
    this: ExpectMatcherState,
    received: string,
    snapshotFileName: E2e.TextSnapshotFileName,
  ) {
    const name = `${assertionName(this, toMatchTextSnapshot.name)}: "${snapshotFileName}"`;

    return await test.step(
      name,
      async () => {
        let pass: boolean;
        let matcherResult: MatcherResult | undefined = undefined;

        try {
          if (this.isNot) {
            await expectBaseConfigured(received ?? '').not.toMatchSnapshot(snapshotFileName);
          } else {
            await expectBaseConfigured(received ?? '').toMatchSnapshot(snapshotFileName);
          }

          pass = true;
        } catch (e: any) {
          matcherResult = e.matcherResult;
          pass = false;
        }

        const message = () => (matcherResult ? matcherResult.message : '');

        return make<MatcherReturnType>({
          name,
          message,
          pass: this.isNot ? !pass : pass,
          expected: matcherResult?.expected,
          actual: matcherResult?.actual,
          timeout: this.timeout,
        });
      },
      {},
    );
  }
```

```
await expect('xxx').toMatchTextSnapshot('test.txt');
```

![Image](https://github.com/user-attachments/assets/73c1fc8a-dbd9-43c9-ae55-0932bb087871)

### Motivation

Improve trace for custom matchers

**Comment by yury-s** [comment]
The name is captured before the the matcher is called. This way we can e.g. show it in the report, even if the matcher hangs and the execution is terminated with an unrelated error. You can declare multiple matchers with different function names to differentiate between them in the report, but we don't support dynamic names that depend on the matcher result.  Closing the issue as there are no plans to change this behavior.

**Comment by raythurnvoid** [comment]
You could at least provide an API that accept a name parameter and the function of the matcher, the name could also be a function that receives in input the same arguments of the matcher and it should return a string
