### ISSUE TITLE
Does playwright.chromium.launch_persistent_context() not support launching a context as a mobile device? Is there a solution that allows for both?

### ISSUE THREAD

**Issue by lzmsomuch** [microsoft/playwright#33469]
### Please do not submit this issue.

- [x] I understand

**Comment by yury-s** [comment]
This doesn't sound like a bug or feature request, please use our [community resources](https://playwright.dev/community/welcome) for general questions. If you think this is a bug in Playwright, please open a new issue and follow the bug template.
