### ISSUE TITLE
[Bug]: Getting error as Exception noted: Locator.select_option: Target page, context or browser has been closed while selecting dropdown

### ISSUE THREAD

**Issue by surbhiD** [microsoft/playwright#33471]
### Version

1.48.0

### Steps to reproduce

Login into the application
and clicking on dropdown on home page

Actual Result : unable to select dropdown and error is coming that- Unable to select value BELARUS from the element role.Exception noted: Locator.select_option: Target page, context or browser has been closed.

Note: when i run it again using stored cookies then it run successfully.but for the first time its always giving this error

### Expected behavior

Should be able to select the dropdown each time even when cookies are not available after successful authentication

### Actual behavior

Actual Result : unable to select dropdown and error is coming that- Unable to select value BELARUS from the element role.Exception noted: Locator.select_option: Target page, context or browser has been closed.

### Additional context

Using cookies to authenticate .

### Environment

 System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 3.12 GB / 15.84 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.95.1 - C:\Users\dhsu3001\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD

**Comment by yury-s** [comment]
The page probably navigates while you are selecting an option from the list. Try recording a [trace](https://playwright.dev/docs/trace-viewer-intro#recording-a-trace) to see the state of the page when you are selecting the option. If you think it's a bug in Playwright, please share a minimal repro that we could run locally.

**Comment by yury-s** [comment]
We need a minimal reproduction that we could run locally to make this report actionable. Please file a new one and link to this issue when you get back to it!
