### ISSUE TITLE
[Feature]: timeout option for test.step

### ISSUE THREAD

**Issue by HardworkingSlacker** [microsoft/playwright#33475]
### 🚀 Feature Request

A new timeout option for test.step.
Optionally, step timeouts can be configured to be independant from the test timeout (like fixture timeouts).

### Example

```typescript
const timeoutFirstStep = 60_000;
const timeoutSecondStep = 30_000;
const timeoutExtra = 10_000;
test.setTimeout(timeoutExtra, {separateStepTimeouts: true})
test(`Steps with individual time limits`, async () => {
  await test.step(`abort test if this step takes longer than ${timeoutFirstStep} milliseconds`, async () => {
  // Do something that should not take more than 60 seconds to complete
  }, {timeout: timeoutFirstStep})
  await test.step(`abort test if this step takes longer than ${timeoutSecondStep} milliseconds`, async () => {
  // Do something else that should not take more than 30 seconds to complete
  }, {timeout: timeoutSecondStep})
})
// Even though it has a timeout of 10 seconds, test runs for up to 90 seconds because of separateStepTimeouts: true
```

### Motivation

We have test cases where different steps aren't supposed to take more than x seconds to complete.
They belong to the same test case, so splitting them up into individual tests is very cumbersome.
expect.toPass is the goto workaround but then you need to dynamically adjust the test.setTimeout value when using dynamic timeout values and it looks kind of ugly.
```typescript
const timeoutFirstStep = 60_000;
const timeoutSecondStep = 30_000;
const timeoutExtra = 10_000;
test.setTimeout((timeoutFirstStep+timeoutSecondStep+timeoutExtra));
test(`Steps with individual time limits`, async () => {
  await test.step(`abort test if this step takes longer than ${timeoutFirstStep} milliseconds`, async () => {
    await expect(/*Operation limited to 60 seconds*/).toPass({timeout: timeoutFirstStep, intervals: []})
  })
  await test.step('abort test if this step takes longer than ${timeoutSecondStep} milliseconds', async () => {
    await expect(/*Operation limited to 30 seconds*/).toPass({timeout: timeoutSecondStep, intervals: []})
  })
})
```
A timeout option for test.step would be prettier and simpler to use.

**Comment by msorens** [comment]
Be aware that the `separateStepTimeouts` option in the example of this feature request was NOT part of the implementation, which is unfortunate. Without that, the **total** test timeout is still governed by the `test.setTimeout(timeoutExtra)`, meaning the test will fail after 10 seconds. For the example to work, we need:
```
test.setTimeout(timeoutExtra + timeoutFirstStep + timeoutSecondStep)
```
...which is rather cumbersome and high maintenance for any but the most trivial test.
