### ISSUE TITLE
[Feature]: Please add expect(locator).not.toExist()

### ISSUE THREAD

**Issue by cbradthompson** [microsoft/playwright#33478]
### 🚀 Feature Request

When a modal is closed and I want to assert it no longer exists in dom I have to do this:

expect(page.locator('element').count()).toBeGreaterThan(0)

Can we have something added which is essentially this?

expect(locator).toExist()
expect(locator).not.toExist()

### Motivation

It seems logical to have this assertion type as in some cases the expect().not.toBeVisible() won't work as the element is gone from DOM. There is a work around but would be nice :)

**Comment by ruifigueira** [comment]
`toBeVisible` / `toBeHidden` also handle the case where element is not attached to the DOM

In https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-be-hidden

> Ensures that [Locator](https://playwright.dev/docs/api/class-locator) either does not resolve to any DOM node, or resolves to a [non-visible](https://playwright.dev/docs/actionability#visible) one.

**Comment by yury-s** [comment]
In addition to the comment above, both of the following
```
  await expect(locator).toBeHidden();
  expect(locator).toHaveCount(0);
```
work for the element not in the DOM tree.
For visibility you can use `toBeVisible`
