### ISSUE TITLE
[Feature]: Execute test cases based on test cases history

### ISSUE THREAD

**Issue by Naveenkumar-selvam** [microsoft/playwright#33473]
### 🚀 Feature Request

Need to execute the test cases based on the execution history. Test cases should execute based on the failure count in the descending order.

Once each test case execution completed, store the execution status, test case name and failure count in the DB.
In next execution same test case failed, updated the failure count to 2 likewise we have to follow for each test case and each execution.
The result stored in DB with help of afterEach block.

We can keep one flag "smartTestExecution" in .env file.
If the flag "smartTestExecution" is enabled, it should fetch the test cases from DB in the descending order of failure count and execute the test cases based on the descending order of failure count i.e. which test case has more failure count it should execute first then next based on the failure count.

If the flag "smartTestExecution" is disabled, it should execute normally as like now.

### Example

**test1.spec.js**

test('testcase1', async ({ page }) => {
  // logic for test case 1
});

test('testcase2', async ({ page}) => {
  // logic for test case 2
});

**test2.spec.js**

test('testcase3', async ({ page }) => {
  // logic for test case 3
});

test('testcase4', async ({ page}) => {
  // logic for test case 4
});

**DB results:**
TestcaseName - Status - Failurecount
testcase1 - failed - 3
testcase2 - passed - 0
testcase3 - failed - 5
testcase4 - passed - 0

Based on the above results once "smartTestExecution" is enabled, it should execute the test cases in the following order
testcase3
testcase1
testcase2
testcase4

Explanation: testcase3 has more failure count so its executed first then testcase1 also have some failure count less than previous one.
Then testcase2 & testcase4 it has 0 failure count

### Motivation

Some of test cases around some functionality is frequently getting failed. But during our normal execution it may execute in any place like starting or middle or end based on spec file alphabetical order.
If I have some good amount of cases, I have stay some time to check that execution status.

Suppose if playwright support smart test execution feature, it will make testers life more easier. Frequently changed functionality or corner areas we can find in the starting of execution and we can get some clarification quickly. 
Also it will make playwright unique in the market as well.

I appreciate your time and assistance with this issue. If you need any further details or clarification on my end, I’m happy to provide them.
Looking forward to your guidance on how to resolve this. 
Thank you in advance for your support!!!

**Comment by yury-s** [comment]
Folding this into https://github.com/microsoft/playwright/issues/27723, we might consider adding a way to change test order. Another related request is https://github.com/microsoft/playwright/issues/9297
