### ISSUE TITLE
[Bug]: Strange behavior when setting useAgent for webkit

### ISSUE THREAD

**Issue by loggerhead** [microsoft/playwright#33488]
### Version

1.48.2

### Steps to reproduce

1. Clone my repo at https://github.com/loggerhead/bug-monaco-webkit.git
2. `npm install && npm run dev`.
3. Set a breakpoint on line 6 in `./e2e/tests/example.spec.js`. Debug the test using vscode and click on line 2 of monaco-editor.
4. Remove `userAgent` from `./playwright.config.js` and try step 3 again.

### Expected behavior

Clicking on line 2 of monaco-editor will change the position of the cursor whether it's the first time or the second time running.

### Actual behavior

The position of the cursor will not change in the first time, but it changes as expected in the second time.

### Additional context

[_No response_
](https://github.com/user-attachments/assets/9ba75992-2a21-4735-bb87-9692097b1d8a)

### Environment

  System:
    OS: macOS 14.7.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 139.25 MB / 36.00 GB
  Binaries:
    Node: 22.10.0 - /opt/homebrew/bin/node
    npm: 10.9.0 - /opt/homebrew/bin/npm
    pnpm: 9.12.3 - ~/Library/pnpm/pnpm
  IDEs:
    VSCode: 1.95.1 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.48.2 => 1.48.2

**Comment by yury-s** [comment]
From what I see you change user agent to a non-existing value, it affects behavior of a complex web app in an unexpected way. What is the request for Playwright? If you believe this is a Playwright bug, please reduce the use case to a project that we could reason about, otherwise it appears to be just the way monaco editor handles such user agent string.

**Comment by loggerhead** [comment]
@yury-s Thanks! I have been trapped in the problem for days. After your mention, I try to change it to a valid value and everything works as expected now. It should be related to Monaco editor.
