### ISSUE TITLE
Issue related to execution or debugged with extension in visual code

### ISSUE THREAD

**Issue by Ecubillo56995** [microsoft/playwright#33495]
Currently, when I need to make a debug or execute my test cases and for any reason the tests failed in the console show a successfully result when this is incorrect.
Step to reproduce:

1. Execute or debugged any test as you know this should be failed.
2. Verify that in the console show a test case with the successfully result.

Evidence:
![Image](https://github.com/user-attachments/assets/c46b7f10-6385-4304-973a-32bbda5d0cb1)

Expected behaviour:

In the console should be show the correct status of the tests

**Comment by yury-s** [comment]
Can you share a minimal example where it happens? It works fine with a simple test for me:

![Image](https://github.com/user-attachments/assets/686506a2-0514-4075-9dc0-58e462e0d021)

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
