### ISSUE TITLE
[Bug]: Playwright fullpage screenshot doesn't output all page elements

### ISSUE THREAD

**Issue by javierlatorrep** [microsoft/playwright#33506]
### Version

1.48.0

### Steps to reproduce

I'm finding an issue with Playwright related to screenshots. I'm trying to take full-page screenshots of Bing (in my case). Before taking the screenshot I'm doing some scrolling to force all kind of answers and elements appear in the Bing page, but depending where was the last position of the scroll, some elements in the page that appear in the screenshot and some elements that don't. When taking a full page screenshot I guess everything should appear. I've done some testing outside of playwright, using browser extensions like [GoFullPage](https://microsoftedge.microsoft.com/addons/detail/gofullpage-full-page-sc/hfaciehifhdcgoolaejkoncjciicbemc?refid=bingshortanswersdownload) ([github](https://github.com/mrcoles/full-page-screen-capture-chrome-extension)) and [FireShot](https://getfireshot.com/) and those take screenshot with all elements in the Bing page.

I'm posting some images in this message so you can see examples of what I mean.
**Playwright taken screenshot without scrolling and missing bottom elements: playwright-fullpage-spiderman-no-scroll.jpeg**
![Image](https://github.com/user-attachments/assets/12e2b2df-085c-4a83-ada2-9d26e0b1da16)

**Playwright taken screenshot scrolling to bottom and missing elements: playwright-fullpage-spiderman-scroll-to-bottom.jpeg**
![Image](https://github.com/user-attachments/assets/a9c75691-6d7a-4bda-b03f-e037d380b8a1)

**Gofullpage browser extension example screenshot. Expected result: gofullpage-fullpage-spiderman.png**
![Image](https://github.com/user-attachments/assets/3c1070e2-4176-4440-b348-bf1cc8eb3367)

I've also noticed that when returning the image in PNG format it works a bit better:
**Playwright taken screenshot missing elements PNG: playwright-fullpage-spiderman-no-scroll.png**
![Image](https://github.com/user-attachments/assets/bbed1058-af18-42c2-ad8e-b81eaeceb01c)

You can reproduce the behavior with this sample code:

Call the endpoint with url:
```
{
    "url": "https://www.bing.com:443/search?q=spiderman&cc=US&setlang=EN"
}
```

```
[HttpPost]
[Route("ScreenshotTest")]
public async Task<IActionResult> ScreenshotTest(
    [FromBody] ScreenshotRequest screenshotRequest
)
{
    var playwright = await Playwright.CreateAsync();

    var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
    {
        Headless = false,
    });
    var browserContext = await browser.NewContextAsync();
    var page = await browserContext.NewPageAsync();

    await page.GotoAsync(screenshotRequest.Url!, new PageGotoOptions
    {
        WaitUntil = WaitUntilState.NetworkIdle
    });

    // You could try doing scroll here, go to bottom, go back to top...
    // But not mandatory, without scrolling bottom elements don't appear too
    // await page.Mouse.WheelAsync(0, 1000);

    var screenshot = await page.ScreenshotAsync(new PageScreenshotOptions
    {
        FullPage = true,
        Type = ScreenshotType.Jpeg
    });

    await browser.CloseAsync();

    return File(screenshot, MediaTypeNames.Image.Jpeg);
}

// ScreenshotRequest.cs
public class ScreenshotRequest
{  
    public string? Url { get; set; } = default!;
}
```

### Expected behavior

The expected behavior would be to get a full page screenshot with all elements appearing in it. Like the screenshot gofullpage-fullpage-spiderman.png
![Image](https://github.com/user-attachments/assets/3c1070e2-4176-4440-b348-bf1cc8eb3367)

### Actual behavior

**Playwright taken screenshot without scrolling and missing bottom elements: playwright-fullpage-spiderman-no-scroll.jpeg**
![Image](https://github.com/user-attachments/assets/12e2b2df-085c-4a83-ada2-9d26e0b1da16)

**Playwright taken screenshot scrolling to bottom and missing elements: playwright-fullpage-spiderman-scroll-to-bottom.jpeg**
![Image](https://github.com/user-attachments/assets/a9c75691-6d7a-4bda-b03f-e037d380b8a1)

### Additional context

This happens when running it in my local machine. But when I run it in docker happens too, using the image `mcr.microsoft.com/playwright/dotnet:v1.48.0-noble`

### Environment

 System:
    OS: Windows 11 10.0.26100
    CPU: (16) x64 AMD Ryzen 7 PRO 5850U with Radeon Graphics
    Memory: 13.13 GB / 30.83 GB
  Binaries:
    Node: 22.8.0 - ~\AppData\Roaming\nvm\v22.8.0\node.EXE
    npm: 10.8.2 - ~\AppData\Roaming\nvm\v22.8.0\npm.CMD
  IDEs:
    VSCode: 1.95.2 - C:\Users\jlatorre\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.2.37 - C:\Program Files\Git\usr\bin\bash.EXE

**Comment by yury-s** [comment]
Provided the elements are fully loaded (which I don't see to be enforced in your test code and this is very likely at least a part of the problem), there maybe some parts/tiles that are not properly rendered for a full page screenshot, it can be due to hitting some limitations of [image size](https://github.com/microsoft/playwright/issues/13496) or [tile manager](https://github.com/microsoft/playwright/issues/11054), hardware configuration etc. If you think this is a Playwright bug, please provide a minimal self-contained repro (note that bing serves different results page for the same request even from the same machine) that we could run locally.

**Comment by javierlatorrep** [comment]
Thank you for your fast response. I appreciate your insights on the potential issues with the full-page screenshot. I'm sending a full test project now so you can run it locally. When testing on different Bing pages, you can encounter the issues I'm posting about. How can I ensure all elements are loaded? Couldn't Playwright handle this when requesting a full-page screenshot as the browser extensions mentioned in the bug description do? Your guidance on this would be greatly appreciated!

How to run the sample project:
1. It is attached a test project bundle in a zip file. Download it.
[ScreenshotTest.zip](https://github.com/user-attachments/files/17700061/ScreenshotTest.zip)
2. Unzipped and you'll see the `ScreenshotTest.bundle` file.
![Image](https://github.com/user-attachments/assets/5ec56628-e2ce-46a3-b254-4830e1a80032)
Here the bundle file:
![Image](https://github.com/user-attachments/assets/abbbf732-ef97-4331-8897-4e9e5ee35852)
4. Open a terminal in the folder containing the bundle file.
5. Run the following command to unbundle: `git clone ScreenshotTest.bundle ScreenshotTest`
6. Now open ScreenshotTest folder and you're ready to open the `ScreenshotTest.csproj` in `Visual Studio` to run profile `ScreenshotTest`.
![Image](https://github.com/user-attachments/assets/a475eb6e-ad2c-4865-9f79-6eace98ee80d)
8. Use a tool like Postman to send requests to take a screenshots.![Image](https://github.com/user-attachments/assets/a66b195d-de45-4792-a5ff-56f1968d97c2)
