### ISSUE TITLE
[Feature]: Functionality to skip playwright internal test files globbing while loading of tests phase

### ISSUE THREAD

**Issue by Jamesj001** [microsoft/playwright#33504]
### 🚀 Feature Request

For user defined playwright configs like : 

```
import { defineConfig } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'project1',
      grep: /@proj1_test/,
      use: { device1}
    },
    {
      name: 'project2',
      grep: /@proj2_test/,
      use: { device2 }
    },
  ],
});
```

Test filtering is required at the test case title level (since we are using `grep`) not at the test suite file level so for this custom config, playwright will be [setting same test files paths data for each project](https://github.com/microsoft/playwright/blob/main/packages/playwright/src/runner/loadUtils.ts#L46) either `project1` or `project2` ([ref](https://github.com/microsoft/playwright/blob/7073f80879a9c194abe969fd7b5c145c4b15caaa/packages/playwright/src/runner/projectUtils.ts#L141C9-L141C17)) since testDir is also same.

So in case if we are able to supply all test files paths already pre-computed to playwright before hand then we could skip this [collectFiles](https://github.com/microsoft/playwright/blob/main/packages/playwright/src/runner/projectUtils.ts#L138) step from doing duplicate computation while loading of tests and this would help us in saving time on playwright side

Because currently even if we want to run a single test Playwright first computes [all test file paths and sets them in each project configured](https://github.com/microsoft/playwright/blob/main/packages/playwright/src/runner/loadUtils.ts#L46) and then does filtering around it to decide which tests to run

For projects where we have big monorepos, this save us good amount of time while running tests locally.

So for configurations like this where we have each project relying on just `grep` for filtering out tests (also same `testDir`) and if we supply all test suite paths in arguments to playwright command then we should be able to skip this redundant computation happening on Playwright side internally

### Example

Exposed via a playwright cli flag i.e. `skipPlaywrightInternalTestFilesGlobbing (by default : false)`

Patch change would look like: 

```
// File location: https://github.com/microsoft/playwright/blob/main/packages/playwright/src/runner/loadUtils.ts#L46

async function collectProjectsAndTestFiles(testRun, doNotRunTestsOutsideProjectFilter, additionalFileMatcher) {
  ...
  ...
  ...

  // First collect all files for the projects in the command line, don't apply any file filters.
  const allFilesForProject = new Map();
  const filteredProjects = (0, _projectUtils.filterProjects)(config.projects, config.cliProjectFilter);
  if(config.cliSkipPlaywrightInternalTestFilesGlobbing && config.cliArgs.length) {
    for (const project of filteredProjects) {
     // consuming cli args for setting test file paths
      const files = (0, _projectUtils.collectFilesForProjectFromArgs)(project, fsCache, config.cliArgs);
      allFilesForProject.set(project, files);
    }
  } else {
    for (const project of filteredProjects) {
     // playwright internal test suite file globbing
      const files = await (0, _projectUtils.collectFilesForProject)(project, fsCache);
      allFilesForProject.set(project, files);
    }
  }
  ....
  ....
  ....
}
```

```
File location: https://github.com/microsoft/playwright/blob/main/packages/playwright/src/runner/projectUtils.ts#L138

function collectFilesForProjectFromArgs(project, fsCache = new Map(), configCliArgs = []) {
  const allFiles = cachedCollectFilesFromArgs(project.project.testDir, project.respectGitIgnore, fsCache, configCliArgs);
  const testMatch = (0, _util2.createFileMatcher)(project.project.testMatch);
  const testIgnore = (0, _util2.createFileMatcher)(project.project.testIgnore);
  const testFiles = allFiles.filter(file => {
    const isTest = !testIgnore(file) && testMatch(file);
    if (!isTest) return false;
    return true;
  });
  return testFiles;
}

function cachedCollectFilesFromArgs(testDir, respectGitIgnore, fsCache, configCliArgs = []) {
  const key = testDir + ':' + respectGitIgnore;
  let result = fsCache.get(key);
  if (!result) {
    // consuming cli args for setting test file paths
    result = [...configCliArgs];
    fsCache.set(key, result);
  }
  return result;
}
```
New method added here is mainly : `collectFilesForProjectFromArgs(project, fsCache, config.cliArgs)` which is relying on small utility functions i.e. `collectFilesForProjectFromArgs` and `cachedCollectFilesFromArgs`

Code Change description: 
The only change that this patch brings in is that Playwright would have the ability to either leverage the arguments array (i.e.`config.cliArgs`) for all test suites path data or to rely back on its [internal test suite file globbing](https://github.com/microsoft/playwright/blob/main/packages/playwright/src/runner/projectUtils.ts#L165)

### Motivation

Having this would give consumers the ability to prevent this redundant time consumption from happening on the Playwright's internal side if they have the ability to supply all the test suite paths pre-computed to the Playwright itself given performance time boost

**Comment by Jamesj001** [comment]
@aslushnikov @pavelfeldman happy to hear out your feedback on this request

**Comment by yury-s** [comment]
Can you start with a description of the problem you are trying to solve? From what I understood, there is a monorepo project with a large number of files and you'd like to optimize playwright start-up time when running a single test. Would it be possible for you to share the repository (or equivalent one that exposes the same performance problem, but doesn't depend on your app specific, from what I understand it's the sheer number of files that is suspected to cause a trouble), details of the environment (OS etc) and what are the steps where you think Playwright should be faster.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Allow me to close it, but please file a new one and link to this issue when you get back to it!
