### ISSUE TITLE
[Docs]: .NET Assertions class documentation

### ISSUE THREAD

**Issue by RuanAlesi** [microsoft/playwright#33508]
### Page(s)

https://playwright.dev/dotnet/docs/api/class-locatorassertions
https://playwright.dev/dotnet/docs/api/class-pageassertions

### Description

It should mention the Assertions class. As it is, it gives the idea that the package Playwright.MSTest should be used, when it's not necessary.
Such like:
```
await Page.GetByRole(AriaRole.Button, new() { Name = "Sign In" }).ClickAsync();
await Assertions.Expect(Page.Locator(".status")).ToHaveTextAsync("Submitted");

**Comment by mxschmitt** [comment]
By default `Expect` is available in our base-classes as a method. If you decide to use a custom setup, you can use static uses like shown here: https://playwright.dev/dotnet/docs/library#using-assertions

Using `Assertions.*` is not something we endorse, hence its not documented.

**Comment by RuanAlesi** [comment]
I see @mxschmitt. But out of curiosity, why would you not endorse it?

**Comment by mxschmitt** [comment]
Its the same in the end - having `Assertions.` in the beginning is a bit verbose - thats the main argument. Closing by that.
