### ISSUE TITLE
[Bug]: Can't Play DRM content on Playwright docker image

### ISSUE THREAD

**Issue by MaximeKervella** [microsoft/playwright#33516]
### Version

1.48.0

### Steps to reproduce

Simple code to reproduce issue:
[script_to_reproduce.txt](https://github.com/user-attachments/files/17680706/script_to_reproduce.txt)

Please change extension to .py to run the code in attachment.

I am currently trying to play video with DRM with playwright.

Issue is that I have a different behavior between locally and playwright docker image: mcr.microsoft.com/playwright/pythonv1.48.0-jammy

Scripts steps:

1. Launch chromium with channel chrome and **_ignore_default_args=["--disable-component-update"]_**
2. open page : https://bitmovin.com/demos/drm/
3. take a screenshot / print page content to check manually if DRM are supported.

How to reproduce:

1. Launch script (in attachment) on my local env,
2. DRM are supported as expected
3. Launch script on docker
4. DRM are not supported
5. Launch chrome install by playwright (on docker image) with command: _**google-chrome --no-sandbox --headless --dump-dom "https://bitmovin.com/demos/drm/"**_
6. Check in DOM : DRM are supported

### Expected behavior

I expect that DRM are supported in playwright docker image like they are on my env.

### Actual behavior

DRM are not supported by playwright when using playwright docker image

### Additional context

As I check, Chrome support DRM when launch without playwright.
It should be an issue with playwright args but I do not manage to find which one.
I already try with this arg : --disable-component-update, it works perfectly locally but not in docker image

### Environment

```shell
Playwright docker image : mcr.microsoft.com/playwright/python:v1.48.0-jammy
Command added:
pip install playwright
playwright install chrome
```

**Comment by yury-s** [comment]
It shows "No DRM" on macOS too, you can try ignoring individual flags with [ignoreDefaultArgs](https://playwright.dev/docs/next/api/class-browsertype#browser-type-launch-option-ignore-default-args) parameter to pass options that might cause the trouble. To see all options the browser is launched with, run with `DEBUG=pw:browser` environment variable.

**Comment by yury-s** [comment]
'--disable-component-update' does fix the problem on macOS though. Can you try running passing `args: ['--headless=new']` and see if that makes it work?

**Comment by yury-s** [comment]
The behavior is only supported `--headless=new` mode, to enable it in playwright you need to pass `args: ['--headless=new']`. Upstream Chrome switched to headless=new by default in version 112 (see [this page](https://developer.chrome.com/docs/chromium/headless#use_headless_mode)). Playwright uses headless old by default, which is why the behavior is different.

**Comment by MaximeKervella** [comment]
Sorry I tested today and it works thank you @yury-s for your help !
