### ISSUE TITLE
Configuring videos for failed tests in Playwright

### ISSUE THREAD

**Issue by Fazlaaa** [microsoft/playwright#33514]
I am trying to enable videos for failed tests. I used mode: 'retain-on-failure' option. Sometimes, I don't see videos at all. Sometimes, I see videos for only one test, Sometimes, I see videos for passed tests. Can someone share some experience because this behavior looks very strange to me? I also tried with some custom options available on internet, but I didn't have luck with this.

**Comment by Fazlaaa** [comment]
I am trying to enable videos for failed tests. I used mode: 'retain-on-failure' option. Sometimes, I don't see videos at all. Sometimes, I see videos for only one test, Sometimes, I see videos for passed tests. Can someone share some experience because this behavior looks very strange to me?

**Comment by yury-s** [comment]
This doesn't sound like a bug or feature request, please use our [community resources](https://playwright.dev/community/welcome) for general questions. If you think this is a bug in Playwright, please open a new issue and follow the bug template.
