### ISSUE TITLE
[Question] Playwright not opening full URL (query string parameters) in headless mode when a new tab is opened

### ISSUE THREAD

**Issue by lucy7099** [microsoft/playwright#33510]
### Please do not submit this issue.

- [x] I understand

**Comment by lucy7099** [comment]
I am trying to click on a button that opens a new tab in the same window using Playwright. When I run the test locally (headed) in VS code the flow works correctly. However when I run the tests in my GitLab CI (not headed) and locally (not headed) the tab still opens but it seems to truncate the entire query string parameters of the URL of the new tab.

The test is running on Chromium

This is the code I am running to open new tab:

```
  async cancelInsurance() {
        const popupPromise = this.page.waitForEvent('popup');
        await this.page.locator(Selectors.idpLink).click();
        const newTab = await popupPromise;
        console.log(newTab.url());
        await newTab.click(Selectors.cancelButton);
       
    }
```

example url:

Url in gitlab: https://test-environment.com/insurance_details.en-gb.html

Url locally (how it should open): https://test-environment.com/insurance_details.en-gb.html?&aid=100000&auth_key=12345

Any help on this is much appreciated

**Comment by yury-s** [comment]
This doesn't sound like a bug or feature request, please use our [community resources](https://playwright.dev/community/welcome) for general questions. If you think this is a bug in Playwright, please open a new issue and follow the bug template.
