### ISSUE TITLE
[Bug]: `Target page, context or browser has been closed` on Firefox with `<input type="file">` using `setInputFiles`

### ISSUE THREAD

**Issue by AlexErrant** [microsoft/playwright#33525]
### Version

1.48.2

### Steps to reproduce

1. Clone https://github.com/AlexErrant/playwright-solid-fileinput
2. `pnpm i && pnpm exec playwright test`
3. Observe failing test

### Expected behavior

The code is a minimal playwright + SolidJS app with a single [`<input type="file">`](https://github.com/AlexErrant/playwright-solid-fileinput/blob/c61b7e4c9af35cc88c6ced4c022e7e5e1609d569/src/App.tsx#L6-L12).

[There are two tests](https://github.com/AlexErrant/playwright-solid-fileinput/blob/main/tests/example.spec.ts), which both attempt to "select" the playwright config file. One uses `setInputFiles`, and the other `filechooser`. I believe they are functionally equivalent. There is no `expect`. `filechooser` passes in chromium/firefox/webkit, but `setInputFiles` fails for _only_ firefox:

```
  1) [firefox] › example.spec.ts:3:5 › setInputFiles ───────────────────────────────────────────────

    Error: locator.setInputFiles: Target page, context or browser has been closed
    Call log:
      - waiting for locator('#selectafile')


      4 |   await page.goto("/");
      5 |   await page.locator("#selectafile").click();
    > 6 |   await page.locator("#selectafile").setInputFiles("playwright.config.ts");
        |   ^
      7 | });
      8 |
      9 | test("filechooser", async ({ page }) => {

        at /home/runner/work/playwright-solid-fileinput/playwright-solid-fileinput/tests/example.spec.ts:6:3

    Error: Target page, context or browser has been closed
```

Example github actions run log [here](https://github.com/AlexErrant/playwright-solid-fileinput/actions/runs/11752267900/job/32743589490).

### Actual behavior

Both tests should pass.

### Environment

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (4) x64 AMD EPYC 7763 64-Core Processor
    Memory: 14.43 GB / 15.61 GB
    Container: Yes
  Binaries:
    Node: 22.10.0 - /opt/hostedtoolcache/node/22.10.0/x64/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.9.0 - /opt/hostedtoolcache/node/22.10.0/x64/bin/npm
    pnpm: 9.12.3 - /opt/hostedtoolcache/node/22.10.0/x64/bin/pnpm
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.48.2 => 1.48.2
```

**Comment by mxschmitt** [comment]
Might be fixed on main already, please try https://playwright.dev/docs/canary-releases.

Looks like https://github.com/microsoft/playwright/issues/33257

**Comment by AlexErrant** [comment]
Can confirm `1.49.0-alpha-2024-11-09` works, somehow missed that issue when searching >_>

Thanks for letting me know on a weekend!
