### ISSUE TITLE
[Bug]: Fast Network Responses causing tests to fail

### ISSUE THREAD

**Issue by rainerhahnekamp** [microsoft/playwright#33526]
### Version

1.47.1

### Steps to reproduce

A button in the application triggers a request, during which the UI displays “Saving…” until a response is received, then changes to “Saved.” The simulated response time is 30ms.

In the trace view, “Saving…” (images below) appears as expected, but Playwright doesn’t catch it reliably unless the request duration is increased. This check is crucial to confirm that the request has actually started. We also need to confirm “Saved” once the request completes.

The application is accessible at http://rh-test-pw.s3-website.eu-central-1.amazonaws.com/.

Steps to reproduce:

Use the following test code to observe the issue:

````
import { test, expect } from "@playwright/test";

test('flaky', async ({ page }) => {
    await page.goto('http://rh-test-pw.s3-website.eu-central-1.amazonaws.com/');
    await page.getByRole('button', { name: 'Click' }).click();
    await expect(page.getByText('Saving...')).toBeVisible(); // <-- fails here
    await expect(page.getByText('Saved')).toBeVisible();
});
```

### Expected behavior

The test should catch "Saving..."

### Actual behavior

The test doesn't catch "Saving..."

### Additional context

Test waiting for "Saving..." to appear which is shown for a very short amount of time.

![Image](https://github.com/user-attachments/assets/d4f1c26a-418b-4693-b3e9-9cef633c85fa)

Test failing because of change to "Saved"

![Image](https://github.com/user-attachments/assets/5657b087-9368-4b51-833a-b8be5827e8f1)

Before the Click action
![Image](https://github.com/user-attachments/assets/96113fa5-55b1-4e94-b578-9305c26d480f)

After the Click action (note that this time it is already "Saved."
![Image](https://github.com/user-attachments/assets/cd354fb1-7af9-4d28-b7c7-1ec0dc9ad340)



### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 6.63 GB / 64.00 GB
  Binaries:
    Node: 22.5.1 - ~/.nvm/versions/node/v22.5.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v22.5.1/bin/yarn
    npm: 10.8.2 - ~/.nvm/versions/node/v22.5.1/bin/npm
    pnpm: 9.6.0 - ~/.nvm/versions/node/v22.5.1/bin/pnpm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.47.1 => 1.47.1
```

**Comment by pavelfeldman** [comment]
I don't think Playwright can handle this case. It is inherently racy (imagine Saving... flashing really fast), so the test will always be flaky. If your button uses timeout, consider using page.clock to step in time. For a real use case with the network, consider routing the network using page.route to throttle the request until the check is verified. Both would solve your problem w/o flakes.

**Comment by rainerhahnekamp** [comment]
Hey @pavelfeldman, thanks for the update. Some threshold where it is quite sure that Playwright will cover it? > 100ms or more?
