### ISSUE TITLE
[Feature]:  Trace Viewer: fileName in URI parameters as alternative to manual selection

### ISSUE THREAD

**Issue by Oscaruzzo** [microsoft/playwright#33520]
### 🚀 Feature Request

I think it would be very useful if the trace filename could be passed in an URI parameter

### Example

If my trace file is in `/var/tmp/trace1.zip` I would like something like `https://trace.playwright.dev/?fileName=%2Fvar%2Ftmp%2Ftrace1.zip`

### Motivation

Integration in internal reporting dashboards

**Comment by yury-s** [comment]
A web page served by an https server cannot have access to the local filesystem for security reasons. The browser requires the user to explicitly select a file/directory via system dialog, the one that you see when selecting trace files when clicking on the blue button. You should upload the trace files to a web server if you want to show them inside the web viewer, see [this doc](https://playwright.dev/docs/trace-viewer#viewing-remote-traces) for an example.

**Comment by Oscaruzzo** [comment]
Thank you, I missed that bit of information. Viewing from a web server is perfect.
