### ISSUE TITLE
[Feature]: Screenshots for tracking supports taking screenshots of individual pages.

### ISSUE THREAD

**Issue by LuHugo** [microsoft/playwright#33530]
### 🚀 Feature Request

I have a project that uses the connectOverCDP way of writing code, when I use tracing with screenshots set to true, the tracing screenshot will take a screenshot of all the pages, this is an unanticipated result, I only want to take a screenshot of one of the target pages, and I would like to see support for setting the screenshot function for the specified page.

### Example

```
const browser = await playwright.chromium.connectOverCDP(CDP_ENDPOINT);
const defaultContext = await browser.contexts()[0];
const pages = await defaultContext.pages();
// The page option is optional, when the page option is not set, the tracking screenshot will take a screenshot of all pages at this time
await context.tracing.start({ screenshots:{page: pages[1], enable: true}, snapshots: true });
```
## Or add tracing to the page object.

```
const browser = await playwright.chromium.connectOverCDP(CDP_ENDPOINT);
const defaultContext = await browser.contexts()[0];
const pages = await defaultContext.pages();
const page = pages[1];
await page.tracing.start({ screenshots:true, snapshots: true });
```

### Motivation

I have a project that uses the connectOverCDP way of writing code, when I use tracing with screenshots set to true, the tracing screenshot will take a screenshot of all the pages, this is an unanticipated result, I only want to take a screenshot of one of the target pages, and I would like to see support for setting the screenshot function for the specified page.

**Comment by pavelfeldman** [comment]
This falls outside of the scope of Playwright. Sounds like you are solving a non-testing problem, for which you can consider using CDP or other tools.

**Comment by LuHugo** [comment]
> This falls outside of the scope of Playwright. Sounds like you are solving a non-testing problem, for which you can consider using CDP or other tools.

This is a question related to tracking information. I have an electron project and launch it via connectOverCDP, then I need to track the playwright automation of one of the web content created via the WebContentsView container, but the screenshot of the tracking information takes a screenshot of the entire electron application, but the goal is actually to only take a screenshot of the page inside the WebContentsView container. This means that only the pages inside the WebContentsView container are automated, not the entire application.

``` javascript
// connect to the electron application
const browser = await playwright.chromium.connectOverCDP(CDP_ENDPOINT);

const context = await browser.contexts()[0];
const pages = await context.pages();

 // This page is created by WebContentsView
const page = pages[1];

// context.tracing will trace the whole application instead of the pages created by WebContentsView, 
// the screenshot contains the screenshot of the application in addition to the screenshot of the pages, 
// this is because the screenshot is of the whole context under all the pages instead of the executing pages.
await context.tracing.start({ screenshots: true, snapshots: true });
await page.goto("https://www.example.com");
// ...
await context.tracing.stop({ path: "trace.zip" });
```
This may not be a common scenario, but it's certainly a problem here.
