### ISSUE TITLE
[Bug]: While running the tests from the Playwright Test for VSCode, the globalSetup is not "called"

### ISSUE THREAD

**Issue by davitebralidze** [microsoft/playwright#33538]
### Version

1.1.11

### Steps to reproduce

1. Create a playwright project
2. Create allure-results folder in the project
3. create global-setup.ts file in your project
4. paste the next code in global-setup.ts file:
```
import fs from 'fs';
import path from 'path';

const allureResultsPath = path.join(__dirname, 'allure-results');

export default async () => {
    if (fs.existsSync(allureResultsPath)) {
        fs.rmSync(allureResultsPath, { recursive: true, force: true });
    }
};
```
5. add   **globalSetup: require.resolve('./global-setup')** int the defineConfig
6. Run some random tests from the Playwright Test for VSCode extension

### Expected behavior

The allure-results file is deleted from the project before the test run starts

### Actual behavior

The allure-result folder is not deleted (If I run tests from terminal with a command npx playwright test or a specific test npx playwright test -g "{nameOfTheTest}" the folder is deleted)

### Environment

```shell
System: Windows 11
node: 22.7.5
playwright: 1.48.0
```

**Comment by Amaimaya** [comment]
Hi, I'm having the same issue, how did you solve it?
