### ISSUE TITLE
[Bug]: ANSI signs shown in hover preview connected with Playwright VSCode Extension not reloading context (manual reload needed)

### ISSUE THREAD

**Issue by jaktestowac** [microsoft/playwright#33531]
### Version

1.48.2

### Steps to reproduce

Start new project with: 
`npm init playwright@latest --yes '--' '--quiet' '--browser=chromium'`

Make sure that you have Playwright Extension installed.

Make changes to test script to make VSCode show some red underlines indicating that are problems with code.
Use Ctr (Cmd) + Z to udo some actions if bug output will not appear.

![Image](https://github.com/user-attachments/assets/15f1c2be-7776-4e4f-9fc0-a101921dd099)

In my case only entering `const` caused above situation.

The problem disappears when navigating to Testing | TEST EXPLORER | Refresh Tests 

### Expected behavior

Correct error displayed

### Actual behavior

ANSI sings presented, code is not reloaded by Playwright Extension

### Additional context

All plugins except the Playwright Extension were turned off. All updates have been applied.

Sometimes several actions on the code need to be executed to trigger this error. It occurs on multiple machines, both Windows and macOS.

This bug appeared in previous extension releases, but recently it has been occurring frequently.

As the provider of a very popular free Playwright course on YouTube (in Polish), we receive a high number of reports about this problem.
If any issues with reproducing the error arise, please consult the team and ask if they have encountered this error.

Maybe it is connected with some caching mechanism.

### Environment

```shell
System:
    OS: Windows 11
    CPU: (16) x64 11th Gen Intel(R) Core(TM)
    Memory: 43.39 GB / 63.71 GB
  Binaries:
    Node: 20.11.0 - \nodejs\node.EXE
    npm: 10.4.0 - \nodejs\npm.CMD
  IDEs:
    VSCode: 1.95.2 - \Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.48.2 => 1.48.2
```

**Comment by mxschmitt** [comment]
Probably caused by https://github.com/microsoft/playwright-vscode/blob/3f51ee08a4a7ab74c207e2b72a0ccd8f6e82be75/src/playwrightTestServer.ts#L372

**Comment by pavelfeldman** [comment]
That's what I have:

![Image](https://github.com/user-attachments/assets/cd41d73e-6d24-45b3-abfd-c63741e33fb7)

**Comment by pavelfeldman** [comment]
Does it also show ansi sequences when you have a regular assertion failure?

**Comment by jaktestowac** [comment]
@pavelfeldman  Regarding regular assertion failure - all is fine.


I prepared virtual machine with this bug to share it with you - you will receive invitation to repository to get access to it.

After installing fresh Windows VM with VSCode and Node.js (all default) 
Then installed default PW Project and PW Extension. 
Bug not appearing at once when I done simple code changes.
 
I done additional steps with installation of of next release to simulate standard usage of Playwright. 
Bug appeared so is connected with upgrading Playwright. 
![Image](https://github.com/user-attachments/assets/0121a52c-b8ca-4c85-b46c-053406d3dc0a)


Feel free to explore machine in case of problems give me a comment.

**Comment by pavelfeldman** [comment]
@jaktestowac thanks for the VM, that's the first time we get a repro in a form of a VM. I'm hesitant accepting the invite, but let me try performing the same steps on a fresh virtual devbox.
