### ISSUE TITLE
[Feature]: Force Playwright ignore the SELENIUM_REMOTE_URL environment variable.

### ISSUE THREAD

**Issue by hhlTer** [microsoft/playwright#33541]
### 🚀 Feature Request

Issue Description: I am currently utilizing Playwright in a project where the browser needs to be initialized on a remote Selenium Grid server. This is accomplished by setting the SELENIUM_REMOTE_URL environment variable. This setup works well for remote execution, as Playwright automatically detects this environment variable and runs the tests remotely without any additional configuration in the code.

However, I also need to run the Playwright tests locally on my development machine from time to time. To achieve this, I have to delete the SELENIUM_REMOTE_URL environment variable from the system, which is not convenient.

Feature Request: I propose adding an option to explicitly tell Playwright to ignore the SELENIUM_REMOTE_URL environment variable, even if it is set, and to use local browser configurations instead.

### Example

```java
setIgnoreSeleniumRemoteUrl(true)
```
---
````java
public BrowserType.LaunchOptions launchOptions() {
    return new BrowserType.LaunchOptions()
        .setArgs(browserArgs())
        .setIgnoreSeleniumRemoteUrl(true);
}
```

### Motivation

Switching between local and remote execution in Playwright is currently cumbersome. Adding an option to ignore SELENIUM_REMOTE_URL will streamline the process and enhance workflow efficiency.

**Comment by pavelfeldman** [comment]
You can run those Playwrights from processes with different environments.
