### ISSUE TITLE
[Feature]: Hide response.* calls from test reports

### ISSUE THREAD

**Issue by kekcuuuk** [microsoft/playwright#33558]
### 🚀 Feature Request

When writing your own fixture that listens to all requests on the page, calling methods, for example, text() / toJson() causes the creation of a new step in the report. This behavior is noisy and generally seems unnecessary. I would like to be able to disable adding such steps to the report.

### Example

Let's take a simple example and look at the resulting html-report
```typescript
import { test, expect } from '@playwright/test'

test.describe('Example', () => {
  test.beforeEach(async ({ page }) => {
    page.on('response', async (response) => {
      const textResponse = await response.text()

      // some checks on response
      expect.soft(textResponse).toContain('some text')
    })
  })
  test('Some executed requests', async ({ page }) => {
    await page.evaluate(async () => {
      await fetch('https://swapi.dev/api/planets/1/')
      await fetch('https://swapi.dev/api/planets/1/')
      await fetch('https://swapi.dev/api/planets/1/')
      await fetch('https://swapi.dev/api/planets/1/')
      await fetch('https://swapi.dev/api/planets/1/')
    })
  })
})
```
![Image](https://github.com/user-attachments/assets/f50bdcb8-1263-44c0-811c-7f5b1cec5713)

All calls to the response.text() method are automatically logged into the report and clutter up the overall understanding of what happened in the test. As the number of requests increases, things get much worse.

The problem is that I can’t hide these calls on my own. Yes I can wrap them in test.step and group them in some way, but that won't solve the noise problem

### Motivation

In longer tests, there can often be hundreds of network requests which fill the UI and make it tricky to find steps related to actual test assertions. If Playwright supported hiding these, it could make test reports much simpler to parse.

**Comment by Skn0tt** [comment]
We discussed this tonight and agree that these shouldn't be shown in test reports. There's nothing action-like about `await response.text()`. We'll stop emitting steps for them, so they're hidden from both the HTML report and the trace.

**Comment by kekcuuuk** [comment]
Thanks! I'm really looking forward to the new version

**Comment by kosteklvp** [comment]
@Skn0tt Will this also apply to `await response.json()` calls?

**Comment by Skn0tt** [comment]
It will, yes.

**Comment by kvnschlndt** [comment]
I can still see this steps in the report. @Skn0tt 
Can they also be removed somehow?

<img width="968" alt="Image" src="https://github.com/user-attachments/assets/1e05a444-4fa0-4f80-b84b-3edaab638ec4" />

**Comment by kosteklvp** [comment]
I can also see them still in report.

**Comment by Skn0tt** [comment]
Please open a bug report about that so we can investigate.

**Comment by kvnschlndt** [comment]
@Skn0tt there is the bug :) 
https://github.com/microsoft/playwright/issues/34840
