### ISSUE TITLE
[Bug]: Trace screenshots of canvas elements look incorrect

### ISSUE THREAD

**Issue by craigglennie** [microsoft/playwright#33562]
### Version

1.49.0-alpha-2024-11-12

### Steps to reproduce

Filing this at the request of @Skn0tt per our conversation in [feat(trace viewer): show Screenshot instead of Snapshot](https://github.com/microsoft/playwright/pull/32248#issuecomment-2465461548)

Clone the repo at [https://github.com/craigglennie/playwright-canvas-bug-repro](https://github.com/craigglennie/playwright-canvas-bug-repro) and follow the instructions to run the test.

### Expected behavior

Trace screenshots should look like the webpage

Expected the following

![Image](https://github.com/user-attachments/assets/de06ef0f-3db1-45d2-82df-c0256259a9ce)

### Actual behavior

The trace image is stretched and kinda smeared. Also the `<canvas>` border appears doubled, there's a blue background where none is specified, and theres a horizontal line below the canvas that isn't in the HTML.

Get the following

![Image](https://github.com/user-attachments/assets/9991115b-a55e-4762-9b56-1f8de9383b0c)

### Environment

```shell
System:
    OS: macOS 15.0.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 59.52 MB / 36.00 GB
  Binaries:
    Node: 20.18.0 - ~/.local/state/fnm_multishells/86698_1724810507933/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.8.2 - ~/.local/state/fnm_multishells/86698_1724810507933/bin/npm
    pnpm: 8.15.9 - /opt/homebrew/opt/pnpm@8/bin/pnpm
  IDEs:
    VSCode: 1.95.1 - /opt/homebrew/bin/code
  Languages:
    Bash: 5.2.32 - /opt/homebrew/bin/bash
  npmPackages:
    @playwright/test: ^1.49.0-alpha-2024-11-12 => 1.49.0-alpha-2024-11-12
```

**Comment by pavelfeldman** [comment]
Apart from the position mismatch, I don't think the approach is compatible with the canvas in the background, hence I recommend reverting in 1.49

**Comment by Skn0tt** [comment]
Thanks for the repro. This is interesting, it appears to only happen when snapshotting in headless mode. I'm looking into it.

**Comment by Skn0tt** [comment]
I found a fix for the stretching in https://github.com/microsoft/playwright/pull/33575. The blue background and horizontal line are highlighters that appear because the `expect.toHaveTitle` step is selected, that's expected.
Let's discuss tonight what we think about the canvas in background case.
