### ISSUE TITLE
[Bug]: Issue with Client-Based Authentication Testing in Playwright

### ISSUE THREAD

**Issue by laminesadiki** [microsoft/playwright#33563]
### Version

latest (1.48.2)

### Steps to reproduce

In our setup, we use Keycloak as our authentication service, supporting both email/password login and CBA (Client Based Authentication) login.
I’m encountering issues when testing the CBA login flow with Playwright.

In a regular browser session, when the required certificates are installed (in Firefox, they are browser-specific; in Chrome, they inherit from the OS), the CBA login works as expected. Here’s the typical flow:

1. The user navigates to our website via a URL like _mydomain.com_.
2. The user is redirected to the Keycloak login page: _auth.mydomain.com/...._
3. The user has two options: login with a password or with a client certificate.
4. If the user selects the certificate option and clicks the submit button:
    - A popup appears, allowing the user to choose from the saved certificates in the browser.
    - If the user selects the correct certificate, they are logged in successfully.
    - If no valid certificate is chosen, or if there are no registered certificates, an error page is displayed by Keycloak.

### Expected behavior

- The user should be able to select a valid certificate from the popup.
- If the correct certificate is selected, the login should proceed successfully without any errors.
- If no valid certificate is chosen or no certificates are available, the user should see an error page served by Keycloak.

### Actual behavior
**Witouht adding clientCertificates option**
- The test script navigates to the website and redirects to the Keycloak login page.
- After selecting the certificate-based login option and clicking the submit button, the certificate selection popup does not appear.
- Instead, the script encounters an error and goes directly to the Keycloak error page without giving the option to choose a certificate.

**With clientCertificates option**
We have the below error =>  `browser.newContext: Failed to load client certificate: ca md too weak`

### Additional context

I’ve written a script to automate this process, but it fails at step 4 — the certificate selection popup is not shown. 
Instead, the script directly encounters the error page without presenting the certificate choice.

I attempted to add clientCertificates to the Playwright configuration, but it didn’t resolve the issue. 
For our use case, we use certificates in the .p12 format.

Below is the configuration I am using:

```tsx
// playwright.config.ts
import { defineConfig, devices } from "@playwright/test";

export default defineConfig({
  testDir: "./tests",
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: "html",
  projects: [
    {
      name: "firefox",
      use: {
        ...devices["Desktop Firefox"],
        clientCertificates: [
          {
            origin: "https://auth.mydomain.com",
            pfxPath: "./certs/[CERTIFICATE_PATH_TO_TEST].p12",
            passphrase: "passphrase",
          },
        ],
        ignoreHTTPSErrors: true,
      },
    },
  ],
});
```
And here’s the test script:

```tsx
// tests/loginWithCert.spec.ts
import { test, expect } from "@playwright/test";

test("login with certificate", async ({ page }) => {
  await page.goto("https://mydomain.com/");
  // Wait for redirection to Keycloak login page
  await page.waitForURL(/auth\.mydomain.com/i);

  // Select the certificate login option
  const stakeholderDiv = page.locator(".stakeholder").nth(0);
  await expect(stakeholderDiv).toBeVisible();
  await stakeholderDiv.click();

  // Click the submit button
  const submitBtn = page.getByRole("button", { name: /submit/i });
  await expect(submitBtn).toBeVisible();
  await submitBtn.click();

  // Keep the script running to observe behavior
  await new Promise(() => {});
});
```

When I run the test with:

```bash
npx playwright test tests/loginWithCert.spec.ts --headed
```

I receive the following error:

```
Error: browser.newContext: Failed to load client certificate: ca md too weak
```

### Environment

```shell
System:
    OS: macOS 13.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 731.63 MB / 16.00 GB
  Binaries:
    Node: 18.18.1 - ~/.nvm/versions/node/v18.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.18.1/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.1/bin/npm
    pnpm: 9.4.0 - ~/.nvm/versions/node/v18.18.1/bin/pnpm
  IDEs:
    VSCode: 1.95.1 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.48.2 => 1.48.2
```

**Comment by pavelfeldman** [comment]
You scenario is fairly involved, I'll have to request a minimal repo I can clone to repro it locally.

**Comment by mxschmitt** [comment]
I remember a related Node.js bug. Could you try updating to 22.X?

**Comment by laminesadiki** [comment]
> You scenario is fairly involved, I'll have to request a minimal repo I can clone to repro it locally.

thanks @pavelfeldman for your answer and support.

Unfortunately, I can't provide more information because we use digital certificates (with .p12 extension) for login, and our End-to-End tests are directly integrated into our platform to verify its functionality. 
Since I’m not authorized to share these certificates publicly, I can’t include them, as doing so would grant access to the platform with these certificates for many people.

The only missing parts here are the valid certificate and the domain name.

Otherwise, if you have a public example that uses certificates for login, please share it, and I’ll try to figure out what I might be missing.

Alternatively, could you let me know in which examples or conditions you’ve seen this error appear: `Error: browser.newContext: Failed to load client certificate: ca md too weak` ?

**Comment by laminesadiki** [comment]
> I remember a related Node.js bug. Could you try updating to version 22.X?

I tried the LTS version of Node 22.11.0, but I'm still encountering the same error as before.

**Comment by mxschmitt** [comment]
The "ca md too weak" error typically occurs when OpenSSL (which Node.js uses) encounters certificates using older/weaker hash algorithms. The most common cause is certificates signed with MD5 or older SHA-1 algorithms, which are considered cryptographically weak by modern standards.

To fix this, you'll need to:

1. Check how your .p12 certificates are being generated. They should be:
   - Using SHA-256 or stronger for signatures (not MD5 or SHA-1)
   - Using RSA with at least 2048-bit keys or appropriate ECC curves
   
2. If using OpenSSL to generate certificates, ensure you're using commands that specify strong algorithms, for example:
```bash
openssl req -new -sha256 -key private.key -out cert.csr
openssl x509 -req -sha256 -days 365 -in cert.csr -signkey private.key -out cert.pem
```

3. You can inspect your current certificate's properties using:
```bash
openssl pkcs12 -info -in certificate.p12 -noout
```

**Comment by laminesadiki** [comment]
this is the output of last command
```
MAC: sha256, Iteration 2048
MAC length: 32, salt length: 8
PKCS7 Encrypted data: PBES2, PBKDF2, AES-256-CBC, Iteration 2048, PRF hmacWithSHA256
Certificate bag
Certificate bag
PKCS7 Data
Shrouded Keybag: PBES2, PBKDF2, AES-256-CBC, Iteration 2048, PRF hmacWithSHA256
```

**Comment by laminesadiki** [comment]
please tell me if the last output contains sensitive data to hide. I don't think so but who knows.

**Comment by mxschmitt** [comment]
Could you try the following script and see if it also throws the error? Adjust the path to your liking and add a passphrase if needed:

```js
const tls = require('tls')
const fs = require('fs')

tls.createSecureContext({
  pfx: fs.readFileSync('certificate.p12'),
  // passphrase: ''
});
```

Save it to a file and run it with `node test.js`.

**Comment by laminesadiki** [comment]
I found some interesting things and entry points to solve this issue.

Running the above script causes an error (the same as the one shown by Playwright) in both Node.js version 18 and 22:
```
node:internal/tls/secure-context:278
      context.loadPKCS12(toBuf(pfx), toBuf(passphrase));
              ^

Error: ca md too weak
```

The interesting part is that when **I switch to Node.js version 16, the script runs correctly without errors.**

For our CBA login tests, I switched to Node.js v16, and it worked correctly with the certificate being injected as expected.

After some research on how to solve this issue for Node.js versions 18 and 20, I added the **ciphers** option as follows and the script passed correclty

```js
const tls = require('tls')
const fs = require('fs')

tls.createSecureContext({
  pfx: fs.readFileSync('certificate.p12'),
  passphrase: 'passphrase',
  ciphers: "DEFAULT:@SECLEVEL=0", // this fix the issue
});
```


Now, to fix this for Playwright, how can we inject `ciphers: "DEFAULT:@SECLEVEL=0"` into Playwright ? 
or is there a way to use a specific version of Node.js for Playwright ? 
In our entire project, we're using v18 of Node.js , and we plan to upgrade to v22 later.

**Comment by mxschmitt** [comment]
The difference between Node.js 16/18/20/22 is that they updated the OpenSSL version. OpenSSL is used to process and take care of TLS. So most likely a newer OpenSSL version doesn't like the certificate.

> Now, to fix this for Playwright, how can we inject ciphers: "DEFAULT:@SECLEVEL=0" into Playwright ?

So far we don't provide an option to modify the ciphers. 

It seems like you can change it [in Node.js](https://nodejs.org/api/tls.html#modifying-the-default-tls-cipher-suite) via an env var:

`export NODE_OPTIONS=--tls-cipher-list='DEFAULT:@SECLEVEL=0'`

Not great but probably working. Also it seems like you could put this inside your playwright.config and it might work:

```ts
import tls from 'tls';
tls.DEFAULT_CIPHERS = "DEFAULT:@SECLEVEL=0";
// Rest of your config
```

Here is also a note about OpenSSL security levels, might make sense to find out what exactly is causing it (by increasing it and looking whats different): https://docs.openssl.org/master/man3/SSL_CTX_set_security_level/#default-callback-behaviour

**Comment by laminesadiki** [comment]
Adding the TLS script to the config file solved the issue. Thanks for that.

However, I noticed something strange: the popup for selecting the certificates doesn't open. I provided a list of 3 certificates in the array, but only the last one is used and injected correctly for the login. Is this normal?

the config file like this: 
```ts
import { defineConfig, devices } from "@playwright/test";
import tls from "tls";
tls.DEFAULT_CIPHERS = "DEFAULT:@SECLEVEL=0";

export default defineConfig({
  testDir: "./tests",
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: "html",
  use: {
    clientCertificates: [
      {
        origin: "origin",
        pfxPath: "certificate_1.p12",
        passphrase: "passphrase",
      },
      {
        origin: "origin",
        pfxPath: "certificate_2.p12",
        passphrase: "passphrase",
      },
      {
        origin: "origin",
        pfxPath: "certificate_3.p12",
        passphrase: "passphrase",
      },

    ],
    ignoreHTTPSErrors: true,
  },
  /* Configure projects for major browsers */
  projects: [
    {
      name: "firefox",
      use: {
        ...devices["Desktop Firefox"],
      },
    },
  ],
});

```


In our scenario, we want to inject multiple certificates, each corresponding to a different user type, and run tests for each user type to check all rules and access rights.

Do we need to add a context in each test with the correct certificate, or is there a solution to inject all the certificates at once in the config file and select them via the popup in each test?

**Comment by mxschmitt** [comment]
> However, I noticed something strange: the popup for selecting the certificates doesn't open. I provided a list of 3 certificates in the array, but only the last one is used and injected correctly for the login. Is this normal?

This is expected. There is no popup anymore since the client certificate handling happens via Node.js.

If you want to have a different client certificate for different tests, you can use `test.use`: 

```ts
test.use({ clientCertificates: [{...}] });
```

inside your test file: https://playwright.dev/docs/test-use-options#configuration-scopes

**Comment by laminesadiki** [comment]
Thank you so much, @mxschmitt, for your help and very detailed, prompt and rapid answers 🙏 . 
I really appreciate it 🙌.

As the issue is resolved, I'll leave it to you to close it and get that sweet dopamine boost 😉🚀 !

**Comment by charlescoult** [comment]
How might I set the
`ciphers: "DEFAULT:@SECLEVEL=0"`
Setting for python-playwright?
