### ISSUE TITLE
[Feature] Add nodejs expect.toPass to python library

### ISSUE THREAD

**Issue by molinacarlos** [microsoft/playwright#33571]
To improve test robustness , using python library, should be great if the [expect.toPass](https://playwright.dev/docs/test-assertions#expecttopass) method will be available in python library mode (sync or async mode)

**Comment by pavelfeldman** [comment]
`expect.toPass` is a part of the @playwright/test test runner. If you are interested in a similar feature in python, you should request it from the test runner product you are using, most likely pytest.
