### ISSUE TITLE
[Bug]: Webkit doen't work with browser network (Desktop Safari/ devices iphone)

### ISSUE THREAD

**Issue by salemvi** [microsoft/playwright#33574]
### Version

1.48.1

### Steps to reproduce

Go to the api and try to substitute the result of the function via route.fulfill
```js
const page = 'http://localhost:3000/';
(any mock)
const mock = {
        code: 200,
        lang: 'ru-en',
        text: ['My mind, oh my mind'],
    };

export async function translateTextApiMock(
    page: Page,
    mock: any
): Promise<void> {
    await page.route(
        '**/api/*',
         (route: Route) => {
            void route.fulfill({
                status: mock.code,
                body: JSON.stringify(mock),
                contentType: 'application/json; charset=utf-8',

            });
        }
    );
}
```

There are no interceptions of network requests and substitution for mockups in the webkit environment

### Expected behavior

I expect that the request sent via the api will be intercepted and my mock will be returned to me, and not the real server response (this works fine in chromium)

### Actual behavior

I execute the request and get the real server response, without being able to view the response body

### Environment

```shell
Ubuntu 20.04 / Macos Sonoma 14.1
```

**Comment by Addison-Dalton** [comment]
This sounds very similar to an issue I was facing: https://github.com/microsoft/playwright/issues/33518

**Comment by pavelfeldman** [comment]
Could you please follow the BUG template and provide something we can reproduce? If I understand the scenario properly, it works fine for me locally and in our tests.

**Comment by salemvi** [comment]
what kind of template is needed? webkit does not intercept POST requests from the client to the backend and returns an empty response, chromium works fine

**Comment by pavelfeldman** [comment]
Our BUG template requires that you provide a scenario that we can reproduce locally. Otherwise, we have dozens of tests that show that it works across the browsers (tests/page/page-route.spec.ts, tests/library/browsercontext-route.spec.ts, etc.).

**Comment by salemvi** [comment]
tell me please, where I can see your webkit test cases? thanks
