### ISSUE TITLE
[Bug]: Init scripts failures

### ISSUE THREAD

**Issue by jardinetsouffleton** [microsoft/playwright#33589]
### Version

1.45 and above

### Steps to reproduce

Example steps (replace with your own):
1. Clone my repo at https://github.com/ServiceNow/WorkArena
2. pip install -r requirements.txt
3. pip install playwright==1.45.0
4. pytest '[PATH_TO_WORKARENA]/WorkArena/tests/test_task_general.py::test_cheat[chromium-0-FilterAssetListTask]'
5. You should see the error come up.

### Expected behavior

I expect the test to pass. We use `page.context.add_init_scripts` to add init scripts that will display some information on the page, but they appear to be missing as playwright times out because the information fails to be displayed (this fails starting at 1.45.0 and works for prior versions). Looking at the console, we get a lot of error messages related to missing scripts.

### Actual behavior

Init scripts seem to be missing. You can have a look at [WorkArenasrc/browsergym/workarena/tasks/utils/js_utils.js ](https://github.com/ServiceNow/WorkArena/blob/main/src/browsergym/workarena/tasks/utils/js_utils.js) for sample scripts.

### Environment

```Text
- Operating System: [macOS Sonoma 14.7.1]
- CPU: [apple M1 Pro]
- Browser: [Chromium]
- Python Version: [3.12]
- Other info:
```

**Comment by pavelfeldman** [comment]
Your repo is a bit too large to debug, could you please share a minimal repro of the issue as a repository, archive or a single file with a self-sufficient test?

**Comment by mxschmitt** [comment]
You need to add the functions on the window aka. `globalThis`, then things work. Similar to https://github.com/microsoft/playwright/issues/31864.

**Comment by dgozman** [comment]
Closing as per above. If you still encounter problems, please file a new issue by filling in the "Bug Report" template and link to this one.
