### ISSUE TITLE
[Feature]: Self healing on locators

### ISSUE THREAD

**Issue by NSnietol** [microsoft/playwright#33586]
### 🚀 Feature Request

It would be really great to have the ability to integrate plawyright with healenium or any service to performance self-healing. This is one most time consuming task in the daily maintaince. 

### Motivation

This will sky rocket playwright popularity since Playwright is already powerful but self-healing capabilities will make it the definnitely go to tool for test automation

**Comment by pavelfeldman** [comment]
This falls outside of the scope for Playwright.
