### ISSUE TITLE
[Feature]:  Global "expect" Timeout Config Setting for Playwright Library

### ISSUE THREAD

**Issue by spacos-super** [microsoft/playwright#33587]
### 🚀 Feature Request

I'm using playwright as a library and running tests with cucumber-js. Currently, there is no way to set a global timeout for `expect` with a configuration variable. There's a `context.setDefaultTimeout()` method that works for browser navigations and element interactions. But there exists no similar setting for `expect`. This means I have to specify the timeout on every `expect` call, which is very cumbersome and hard to change. 
I think there should either be (1) a way to set this globally when using playwright as a library, or (2) just make this reference the context's default timeout when using playwright as a library.

Versions:
"@cucumber/cucumber": "^11.0.1"
"@playwright/test": "^1.48.1"

### Example

Option 1:
`playwrightConfig.expect.timeout = 10_000`
or
`context.setExpectTimeout = 10_000`

Option 2:
make `expect` use the context's existing default timeout

### Motivation

This will make it much easier to make assertions with Playwright as a library. Less code duplication, more maintainability.

**Comment by pavelfeldman** [comment]
Playwright's expect are to be used with the @playwright/test runner, running them in a different environment is not guaranteed. I'm open to a PR that would be setting this timeout on the expect instance though.

**Comment by spacos-super** [comment]
Ah, yeah that makes sense. Playwright's assertions are too good to give up, though. So if I have some time I'll see if I can add this in a PR. Thanks for taking a look!

**Comment by mxschmitt** [comment]
You can create your own expect instance via configure() have you tried that?

https://playwright.dev/docs/test-assertions#expectconfigure

**Comment by spacos-super** [comment]
> You can create your own expect instance via configure() have you tried that?
> 
> https://playwright.dev/docs/test-assertions#expectconfigure

That's exactly what I needed, actually! I thought I searched the docs but I guess not enough. Thanks!
