### ISSUE TITLE
[Bug]: getByRole accessible name matching normalizes whitespace but expect toHaveAccessibleName does not

### ISSUE THREAD

**Issue by WestonThayer** [microsoft/playwright#33592]
### Version

1.48.1

### Steps to reproduce

Given the following test:

```js
test("non-breaking space bug", async ({ page }) => {
  await page.setContent(`<button>foo&nbsp;bar</button>`);
  await expect(page.getByRole("button", { name: "foo bar" })).toBeVisible();
  await expect(
    page.getByRole("button", { name: "foo bar" }),
  ).toHaveAccessibleName("foo bar");
});
```

### Expected behavior

I expect the test to pass.

### Actual behavior

The test failed at `expect.toHaveAccessibleName` because:

```
Error: Timed out 5000ms waiting for expect(locator).toHaveAccessibleName(expected)

Locator: getByRole('button', { name: 'foo bar' })
Expected string: "foo bar"
Received string: "foo bar"
```

If you have console colors, there is a helpful highlight on the whitespace difference:

![Screenshot of console with the whitespace between foo and bar highlighted in red/green to show its the source of the diff.](https://github.com/user-attachments/assets/1824950a-88da-4238-b58b-f74514fe0647)

The HTML report doesn't have this feature.

### Environment

```shell
System:
    OS: macOS 15.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 91.28 MB / 16.00 GB
  Binaries:
    Node: 20.17.0 - /opt/homebrew/opt/node@20/bin/node
    npm: 10.8.2 - /opt/homebrew/opt/node@20/bin/npm
  IDEs:
    VSCode: 1.94.0 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ~1.48.1 => 1.48.1
```

**Comment by WestonThayer** [comment]
Potentially a duplicate of #23037.

**Comment by pavelfeldman** [comment]
HTML reporter was fixed to show where the diff is:

![Image](https://github.com/user-attachments/assets/0a6c3803-678c-415e-a4cc-63d972a4c5fa)

**Comment by WestonThayer** [comment]
Is that in 1.48.2? I just installed it, but not getting a highlight in the HTML report:

![Image](https://github.com/user-attachments/assets/941792e2-3984-4d3f-bac5-381f09816958)

**Comment by pavelfeldman** [comment]
> Is that in 1.48.2?

Nope, that's @playwright/test@next, 1.49 that will release later this week.

**Comment by WestonThayer** [comment]
Just verified, wonderful thank you. That helps mitigate this issue a bit.
