### ISSUE TITLE
[Bug]: Self-signed cert fails in Firefox (and sometimes Chrome)

### ISSUE THREAD

**Issue by AlexErrant** [microsoft/playwright#33596]
### Version

1.49.0-alpha-2024-11-09

### Steps to reproduce

1. Clone https://github.com/AlexErrant/playwright-solid-fileinput/tree/firefox_cert (note we're on the `firefox_cert` branch)
2. `pnpm i`
3. Install/run [`mkcert`](https://github.com/FiloSottile/mkcert)

```sh
sudo apt install libnss3-tools
curl -L -o mkcert "https://github.com/FiloSottile/mkcert/releases/download/v1.4.4/mkcert-v1.4.4-linux-amd64"
chmod +x mkcert
sudo mv mkcert /usr/local/bin/mkcert
mkcert -install
mkdir .cert
mkcert -key-file .cert/key.pem -cert-file .cert/cert.pem localhost
```

4. Build and run the web proj

```sh
pnpm run build
pnpm run serve &
```

5. Run the test and observe Firefox failing

```sh
NODE_EXTRA_CA_CERTS=$(mkcert -CAROOT)/rootCA.pem DEBUG=pw:webserver pnpm exec playwright test
```

### Expected behavior

Firefox should recognize the self-signed cert.

### Actual behavior

It doesn't.

### Additional context

You can view a demo GitHub actions run [here](https://github.com/AlexErrant/playwright-solid-fileinput/actions/runs/11830064077/job/32962967045#step:7:463):

```
    Retry #2 ───────────────────────────────────────────────────────────────────────────────────────

    Error: page.goto: SEC_ERROR_UNKNOWN_ISSUER
    Call log:
      - navigating to "https://localhost:3000/", waiting until "load"


      2 |
      3 | test("navigate", async ({ page }) => {
    > 4 |   await page.goto("https://localhost:3000");
        |              ^
      5 | });
      6 |
        at /home/runner/work/playwright-solid-fileinput/playwright-solid-fileinput/tests/example.spec.ts:4:14

  1 failed
    [firefox] › example.spec.ts:3:5 › navigate ─────────────────────────────────────────────────────
  2 passed (8.1s)
```

Note that [`curl -v https://localhost:3000/`](https://github.com/AlexErrant/playwright-solid-fileinput/blob/firefox_cert/.github/workflows/playwright.yml#L44) recognizes and accepts the cert:

```
* Server certificate:
*  subject: O=mkcert development certificate; OU=runner@fv-az1776-162
*  start date: Nov 14 03:17:03 2024 GMT
*  expire date: Feb 14 03:17:03 2027 GMT
*  subjectAltName: host "localhost" matched cert's "localhost"
*  issuer: O=mkcert development CA; OU=runner@fv-az1776-162; CN=mkcert runner@fv-az1776-162
*  SSL certificate verify ok.
```

### Environment

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (4) x64 AMD EPYC 7763 64-Core Processor
    Memory: 14.41 GB / 15.61 GB
    Container: Yes
  Binaries:
    Node: 22.10.0 - /opt/hostedtoolcache/node/22.10.0/x64/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.9.0 - /opt/hostedtoolcache/node/22.10.0/x64/bin/npm
    pnpm: 9.13.0 - /opt/hostedtoolcache/node/22.10.0/x64/bin/pnpm
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    @playwright/test: 1.49.0-alpha-2024-11-09 => 1.49.0-alpha-2024-11-09
```

**Comment by AlexErrant** [comment]
For Chrome:

In the Github actions script for Firefox above, [we run the test before installing `mkcert` to show the expected cert failures](https://github.com/AlexErrant/playwright-solid-fileinput/blob/firefox_cert/.github/workflows/playwright.yml#L26-L27):

```sh
NODE_EXTRA_CA_CERTS=$(mkcert -CAROOT)/rootCA.pem DEBUG=pw:webserver pnpm exec playwright test || true
```

If we [comment out this preliminary test run](https://github.com/AlexErrant/playwright-solid-fileinput/compare/firefox_cert..chrome_cert), Chrome fails in the subsequent test. It is unclear to me why this preliminary run is necessary....?

[Example github actions run](https://github.com/AlexErrant/playwright-solid-fileinput/actions/runs/11830066753/job/32962972981):

```
  1) [chromium] › example.spec.ts:3:5 › navigate ───────────────────────────────────────────────────

    Error: page.goto: net::ERR_CERT_AUTHORITY_INVALID at https://localhost:3000/
    Call log:
      - navigating to "https://localhost:3000/", waiting until "load"


      2 |
      3 | test("navigate", async ({ page }) => {
    > 4 |   await page.goto("https://localhost:3000");
        |              ^
      5 | });
      6 |
        at /home/runner/work/playwright-solid-fileinput/playwright-solid-fileinput/tests/example.spec.ts:4:14
```

This is potentially a separate issue; I would be willing to separate it out if asked!

**Comment by pavelfeldman** [comment]
> NODE_EXTRA_CA_CERTS=$(mkcert -CAROOT)/rootCA.pem DEBUG=pw:webserver pnpm exec playwright test

None of the browsers respect NODE_EXTRA_CA_CERTS environment variable, it is only recognized by Node.js. If you want to allow self-signed certificates you should configure Playwright to ignore tls errors. See https://playwright.dev/docs/api/class-testoptions#test-options-ignore-https-errors

**Comment by AlexErrant** [comment]
A few follow ups:

1. Is `ignoreHTTPSErrors` the _recommended_ way of handling self-signed certs? In my non-toy project I'm using a [custom hostname](https://web.dev/articles/when-to-use-local-https#when_to_use_https_for_local_development_2) to simulate having different domains, e.g. `mysite.localhost` and `untrusted-user-generated-content-mysite.localhost`, necessitating the self-signed cert. My non-toy project also uses `data:` URLs, which I believe makes it [mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content), which has HTTPS implications. Ideally, I'd like to make my testing environment as close to production as possible, though I admit I currently don't have a test case where an ignored HTTPS error causes a problem.
2. When I use [`use: { ignoreHTTPSErrors: true }`](https://github.com/AlexErrant/playwright-solid-fileinput/commit/3fa6f0ecbcf735d85b3f4ffb839184b6a7d5e53f#diff-f679bf1e58e8dddfc6cff0fa37c8e755c8d2cfc9e6b5dc5520a5800beba59a92R33) as documented in your link, I get the following error in Github actions: [`pw:webserver Error while checking if https://localhost:3000/ is available: unable to verify the first certificate`](https://github.com/AlexErrant/playwright-solid-fileinput/actions/runs/11840424091/job/32994211247).
3. If, instead, I use [`webServer: { ignoreHTTPSErrors: true }`](https://github.com/AlexErrant/playwright-solid-fileinput/commit/044cd8ef8d2374ded84555569daf9e012b0cd781#diff-f679bf1e58e8dddfc6cff0fa37c8e755c8d2cfc9e6b5dc5520a5800beba59a92R78), since `webserver` is running the server now, I get errors in Firefox and Chromium, but not Webkit. [Example github run:](https://github.com/AlexErrant/playwright-solid-fileinput/actions/runs/11840206790/job/32993469303)

Chromium:

```
  1) [chromium] › example.spec.ts:3:5 › navigate ───────────────────────────────────────────────────

    Error: page.goto: net::ERR_CERT_AUTHORITY_INVALID at https://localhost:3000/
    Call log:
      - navigating to "https://localhost:3000/", waiting until "load"


      2 |
      3 | test("navigate", async ({ page }) => {
    > 4 |   await page.goto("https://localhost:3000");
        |              ^
      5 | });
      6 |
        at /home/runner/work/playwright-solid-fileinput/playwright-solid-fileinput/tests/example.spec.ts:4:14
```

Firefox:

```
  2) [firefox] › example.spec.ts:3:5 › navigate ────────────────────────────────────────────────────

    Error: page.goto: SEC_ERROR_UNKNOWN_ISSUER
    Call log:
      - navigating to "https://localhost:3000/", waiting until "load"


      2 |
      3 | test("navigate", async ({ page }) => {
    > 4 |   await page.goto("https://localhost:3000");
        |              ^
      5 | });
      6 |
        at /home/runner/work/playwright-solid-fileinput/playwright-solid-fileinput/tests/example.spec.ts:4:14
```

**Comment by pavelfeldman** [comment]
> When I use [use: { ignoreHTTPSErrors: true }](https://github.com/AlexErrant/playwright-solid-fileinput/commit/3fa6f0ecbcf735d85b3f4ffb839184b6a7d5e53f#diff-f679bf1e58e8dddfc6cff0fa37c8e755c8d2cfc9e6b5dc5520a5800beba59a92R33) as documented in your link, I get the following error in Github actions:

Playwright waits for the server to come up and probes it. Since your certificate is not trusted, probing fails unless you ignore that errors in webServer configuration. You still need it in the browser configuration.

**Comment by AlexErrant** [comment]
Of course; I needed `ignoreHTTPSErrors: true` in both `use` and `webServer` >_>

I'm hesitant about ignoring this error in the test env, but I suppose asking for a "recommended" way to do things when there's no obvious bug kinda earns me a blank stare.

Thank you for your time and attention!

**Comment by arikkfir** [comment]
So there's no way to install `mkcert` self-signed certificates into the browsers' trusted certificate stores? I'm getting the same error on GitHub Actions and I have to say I'm reluctant to use `ignoreHTTPSErrors`...

Even more so given that when running locally on macOS this setup works great:

1. Use `mkcert -install`
2. Both regular browsers AND the Playwright browsers are able to approach the custom domain with my self-signed certificate

But it breaks on GitHub Actions - I even tried this in my GitHub Actions workflow:

```shell
sudo apt install libnss3-tools
sudo curl -sSL -o /usr/local/bin/mkcert "${MKCERT_URL}" && sudo chmod +x /usr/local/bin/mkcert
mkcert -install
cat "$(mkcert -CAROOT)/rootCA.pem" | sudo tee -a /etc/ssl/certs/ca-certificates.crt
```

But it still fails in GHA.

Is there no way to get Playwright browsers trust the CA created by `mkcert` ?

**Comment by flosell** [comment]
In case someone stumbles across this in the future - the workaround here worked for me to get mkcert and chromium to work together in a container: https://github.com/FiloSottile/mkcert/issues/219#issue-522233833

as a tl;dr (the order of commands might be important): 

```
apt update && apt install -y libnss3-tools mkcert
npm install
npx playwright install --with-deps chromium

mkdir -p $HOME/.pki/nssdb
certutil -d sql:$HOME/.pki/nssdb -N --empty-password

mkcert -install && mkcert localhost

npm test
```
