### ISSUE TITLE
[Feature]: Ability to runs tests based tag and exclude certain tags using grep and invert-grep

### ISSUE THREAD

**Issue by darren-kong-ai** [microsoft/playwright#33595]
### 🚀 Feature Request

After reading the documentation [here](https://playwright.dev/docs/test-annotations#tag-tests) I understand that we are able to tag tests and selectively grep what tests we want based on tags. I wanted to also be able to grep for specific tests and from the filtered tests exclude, certain tags which we do not want to run. 

I attempted running the a grep and grep-invert but I believe we are not able to run these together.  

### Example

The use case is that we have a set of tests tagged as `core` tests but of those tests there are also tests marked as `flaky`. So I would want to first grep for the `core` tests and then filter out the `flaky` tests. 

### Motivation

I think being able to selectively exclude from the grep could allow for more complex test selection. See

**Comment by pavelfeldman** [comment]
> I attempted running the a grep and grep-invert but I believe we are not able to run these together.

This should work, `--grep=@core --grep-invert=@flaky` should run core that is not flaky.

**Comment by dgozman** [comment]
Closing as per above. If you still encounter problems, please file a new issue by filling in the "Bug Report" template and link to this one.
