### ISSUE TITLE
[Feature]: playwright as a devcontainer feature

### ISSUE THREAD

**Issue by ThePlenkov** [microsoft/playwright#33610]
### 🚀 Feature Request

Hi! 

I know it's not a big deal to install playwright with few commands like this:
```
FROM mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
RUN npx playwright install-deps & npx playwright install
```

But installing dependencies manually makes devcontainer build time longer and also requires usage of Dockerfile

It would be nice if we could have a feature here https://containers.dev/features

Thanks!

### Example

So i want to use something like this in a devcontainer.json  

 "features": {
    "ghcr.io/microsoft/playwright": "latest"
   },

### Motivation

- avoid creation of Dockerfile/ using post-create scripts
- spend less time on container build if possible
- make playwright more discoverable ( via features registry )

**Comment by LarsKemmann** [comment]
@pavelfeldman
> This does not look like a request for Playwright library!

I respectfully disagree. Playwright really does need to add a first-party devcontainers feature; [the existing ones](https://containers.dev/features?search=playwright) are third-party and thus much less likely to see adoption. This feature provides all the benefits @ThePlenkov cited, and, by definition, no one other than the Playwright team could do this. Please consider reopening this issue.
