### ISSUE TITLE
[Bug]: VSCode extension produces "Error: Must start tracing before stopping" when "Show browser" option is enabled and "afterAll" hook is used

### ISSUE THREAD

**Issue by groinder** [microsoft/playwright#33611]
### Version

1.48.2

### Steps to reproduce

Steps to reproduce:
1. Clone my repo at: https://github.com/groinder/pw-vscode-bug
2. Run `npm install`
3. Run `npx playwright install`
4. Open the project in VS Code.
5. Install "Playwright Test for VSCode" extension, version `1.1.11` (latest at the time of writing).
6. Navigate to the "Playwright Test for VSCode" extension, make sure the `Show browser` option is enabled. 
![Image](https://github.com/user-attachments/assets/cd93995f-8c85-4b13-b1fd-7d78c4e0b371)
7. Run any test in `tests\example.spec.ts` using the "Playwright Test for VSCode" extension.

### Expected behavior

The test finishes without error.

### Actual behavior

Once the test finishes, there is an error: `Error: Must start tracing before stopping`.
![Image](https://github.com/user-attachments/assets/b380de08-c411-4b4c-89de-59a67e22e250)

### Additional context

- This happens on "Playwright Test for VSCode" extension version `1.1.11`, it works fine on version `1.1.7` - I didn't test other versions.
- It only happens when the `Show browser` option is enabled, it works if it's disabled.
- It only happens if `test.beforeAll` is used, it works when you remove it from `tests\example.spec.ts`. As you can see the  `test.beforeAll` doesn't even need to do anything in particular, it's mere presence causes the bug.

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13950HX
    Memory: 34.17 GB / 63.69 GB
  Binaries:
    Node: 22.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.95.2 - C:\Users\z004fhxd\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.48.2 => 1.48.2
```

**Comment by ch4r-ch4r** [comment]
Managed to create a simpler repro, doesn't need `afterAll` hook to error out.

Clean playwright install, replace the `example.spec.ts` with:

```typescript
import { test } from '@playwright/test'

// First test using browser context
test('First Test', async ({ context }) => {
  await context.newPage()
})

// Second test
test('Second Test', async () => {
  console.log('second test')
})
```

Using the VSCode extension, enable "Show Browser" and execute the `example.spec.ts` file.

Observed: The second test failes with `Error: Must start tracing before stopping`
