### ISSUE TITLE
[Bug]: 'Pick Locator' doesn't update the Locator in Codegen

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#33625]
### Version

@next

### Steps to reproduce

1. Open codegen on https://primevue.org/inputnumber/
2. Pick locator on the 'Integer only' input field

### Expected behavior

Locator gets updated in the Inspector

### Actual behavior

It stays 'is not available during recording'

### Environment

```shell
n/a
```

**Comment by pavelfeldman** [comment]
This is what I get on 1.48:

![Image](https://github.com/user-attachments/assets/6db49648-50e5-42c1-b016-8896a5da0f3d)

**Comment by mxschmitt** [comment]
Fixed by https://github.com/microsoft/playwright/pull/33635
