### ISSUE TITLE
[Bug]: Cannot correctly get style in Safari after programmatically inserting style rule in an empty `@scope`  by using CSSOM

### ISSUE THREAD

**Issue by PupilTong** [microsoft/playwright#33647]
### Version

1.48.2

### Steps to reproduce

Test case:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>safari issue</title>
    <meta content="yes" name="apple-mobile-web-app-capable">
    <meta content="default" name="apple-mobile-web-app-status-bar-style">
    <meta content="telephone=no" name="format-detection">
    <meta content="portrait" name="screen-orientation">
    <meta
      content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no"
      name="viewport"
    >
    <meta content="portrait" name="x5-orientation" />

  </head>

  <body>
    <div>
      <style id="style">
        @scope{
        }
      </style>
      <div id="target" target="abc" style="height: 100px; width: 100px;"></div>
    </div>
    <script>
      const style = document.getElementById('style');
      style.sheet.cssRules[0].insertRule('[target="abc"]{background:green}');
    </script>
  </body>
</html>

```

Test script

```javascript

    test('try', async ({ page }) => {
      await page.goto(/*url here*/)
      await wait(500);
      const target = page.locator('#target');
      await expect(target).toHaveCSS(
        'background-color',
        'rgb(0, 128, 0)',
      );
    });
```

### Expected behavior

The code works fine in desktop chrome and desktop safari. However, playwright cannot detect the background color correctly if the at-rule `@scope` initially has an empty body.

### Actual behavior

The test fails on safari but passes on chrome.

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 130.17 MB / 64.00 GB
  Binaries:
    Node: 22.8.0 - ~/.local/state/fnm_multishells/72887_1731298859655/bin/node
    npm: 10.8.2 - ~/.local/state/fnm_multishells/72887_1731298859655/bin/npm
    pnpm: 9.11.0 - ~/.local/state/fnm_multishells/72887_1731298859655/bin/pnpm
  IDEs:
    VSCode: 1.94.2 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by PupilTong** [comment]
If the `@scope` has any style rule it works.

**Comment by dgozman** [comment]
@PupilTong I can see this code working in Chrome. However, trying both `Safari Version 18.1 (20619.2.8.11.10)` or `Safari Technology Preview Release 207 (Safari 18.2, WebKit 20621.1.4.3)` on `macOS 15.1 (24B83)`, neither of them shows a green square. What are the Safari and OS versions you try that actually show the green square?

**Comment by PupilTong** [comment]
> [@PupilTong](https://github.com/PupilTong) I can see this code working in Chrome. However, trying both `Safari Version 18.1 (20619.2.8.11.10)` or `Safari Technology Preview Release 207 (Safari 18.2, WebKit 20621.1.4.3)` on `macOS 15.1 (24B83)`, neither of them shows a green square. What are the Safari and OS versions you try that actually show the green square?

@dgozman It works find in my safari and chrome(showing a green square), but the assertion fails in playwright

**Comment by PupilTong** [comment]
I'll upgrade my osx and give some feedback later

**Comment by PupilTong** [comment]
@dgozman Seems it's a safari issue. Thanks!

**Comment by dgozman** [comment]
Thank you for confirming, closing.
