### ISSUE TITLE
[Bug]:  [BUG] Get the following error when installing Playwright on OJET

### ISSUE THREAD

**Issue by shastrisubramaniam** [microsoft/playwright#33646]
### Version

v1.48.2

### Steps to reproduce

sudo yarn create playwright

### Expected behavior

Should install successfully.

### Actual behavior

Error: Command failed: yarn add --dev @playwright/test
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at executeCommands (/usr/local/share/.config/yarn/global/node_modules/create-playwright/lib/index.js:4730:39)
    at Generator.run (/usr/local/share/.config/yarn/global/node_modules/create-playwright/lib/index.js:4906:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/local/share/.config/yarn/global/node_modules/create-playwright/lib/index.js:5217:3 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 36606,
  stdout: null,
  stderr: null
}
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-playwright
Arguments: 
Directory: /Users/sushastr/bitbucket/ohpp-ojet-ui
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

### Environment

```shell
System:
    OS: macOS 14.7.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 5.93 GB / 32.00 GB
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.11.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
  Languages:
    Bash: 5.2.37 - /opt/homebrew/bin/bash
```

**Comment by dgozman** [comment]
@shastrisubramaniam What is OJET? Please provide more details so that we can reproduce your issue. When I run `yarn create playwright`, it works for me.

**Comment by shastrisubramaniam** [comment]
Oracle Javascript Extension Toolkit.

There were dependency conflicts with react-redux looks like.

Anyways, I was able to resolve it by using  sudo npm init playwright@latest --force
