### ISSUE TITLE
[BUG] Firefox cookies are Lax by default

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#3364]
There is no plan / target date to make cookies Lax by default. They are only Lax in Beta now. Let's make sure Firefox is consistent with the stable channel.

**Comment by aslushnikov** [comment]
It turned out that the Nightly/Beta building mode is defined by the `//config/milestone.txt` file which is committed to the repository. Our last roll picked a revision with `alpha` milestone, which is nightly.

This will be fixed by itself once we roll further up.

**Comment by aslushnikov** [comment]
This is fixed with #3468
