### ISSUE TITLE
[Bug]: WebSocket leakage in UI Mode

### ISSUE THREAD

**Issue by ruifigueira** [microsoft/playwright#33641]
### Version

1.48.2

### Steps to reproduce

- Run:

```
npx playwright test --ui
```

- Open **DevTools > Network** and filter by **WS** type
- In UI mode, click **Reload** button a few times
- In DevTools, check WS connections, there are several ones pending:

![Image](https://github.com/user-attachments/assets/9e67e827-7805-4313-954c-fa82c5d1ae96)

Here is a test that catches the leakage (requires `runUITest` fixture from `tests/playwright-test/ui-mode-fixtures.ts`):

```js
test('should not leak websocket connections', async ({ runUITest }) => {
  const { page } = await runUITest({
    'a.test.ts': `
      import { test, expect } from '@playwright/test';
      test('test', async () => {});
    `,
  });

  const [ws1] = await Promise.all([
    page.waitForEvent('websocket'),
    page.getByTitle('Reload').click(),
  ]);

  await Promise.all([
    page.waitForEvent('websocket'),
    page.getByTitle('Reload').click(),
  ]);

  await expect.poll(() => ws1.isClosed()).toBe(true);
});
```

### Expected behavior

Existing WebSocket connection should close when reloading. 

### Actual behavior

Existing WebSocket connections are kept open.

### Additional context

`testServerConnection` is never closed when a reload is performed:

https://github.com/microsoft/playwright/blob/46321e5bf25225762a375514063c55bda130ec9e/packages/trace-viewer/src/ui/uiModeView.tsx#L111-L120

If existing connection is closed in `reloadTests`, the test above no longer fails:

```js
  const reloadTests = React.useCallback(() => {
    setTestServerConnection(prevConnection => {
      prevConnection?.close();
      return new TestServerConnection(new WebSocketTestServerTransport(wsURL));
    });
  }, []);
```

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 13th Gen Intel(R) Core(TM) i5-1335U
    Memory: 12.87 GB / 31.66 GB
  Binaries:
    Node: 20.17.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    Yarn: 1.22.22 - ~\scoop\apps\yarn\current\bin\yarn.CMD
    npm: 10.8.2 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
    pnpm: 9.12.3 - ~\scoop\shims\pnpm.EXE
  IDEs:
    VSCode: 1.95.3 - C:\Users\rui.figueira\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.2.37 - C:\Users\rui.figueira\scoop\shims\bash.EXE
  npmPackages:
    @playwright/test: ^1.48.2 => 1.48.2
```

**Comment by pavelfeldman** [comment]
True! Do you want to send a fix?
