### ISSUE TITLE
[Bug]: toBeHidden Ignores Timeout

### ISSUE THREAD

**Issue by jwalkerinterpres** [microsoft/playwright#33656]
### Version

Latest

### Steps to reproduce

Please re-open https://github.com/microsoft/playwright/issues/30953.  It has all the relevant details, including a reproduction script ... but really this is such a basic issue you shouldn't need one (just do a `toBeHidden` with a long timeout, then watch the video and see it wait 1ms).

### Expected behavior

See https://github.com/microsoft/playwright/issues/30953

### Actual behavior

See https://github.com/microsoft/playwright/issues/30953

### Additional context

See https://github.com/microsoft/playwright/issues/30953

### Environment

```shell
See https://github.com/microsoft/playwright/issues/30953
```

**Comment by pavelfeldman** [comment]
I can see strict mode violation exceptions. Locators must be strict. You can add .first() if you want to opt out of strictless.

**Comment by dgozman** [comment]
@jwalkerinterpres This is working as expected. Strict mode violation takes priority. You can always work around that by appending `.first()` at the end of your locator, or by calling `expect(locator).toHaveCount(0)`.
