### ISSUE TITLE
[internal]: VSCode highlight test is failing on Windows

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#33655]
Issue: Since https://github.com/microsoft/playwright/pull/33638 a Playwright for VSCode highlight test is failing.

Repro: 

    npx playwright test highlight-locators.spec.ts:28:5 --project=default-reuse --reporter=html

Note: Can't repro on macOS.

**Comment by pavelfeldman** [comment]
This regressed in #33632 not in #33638
