### ISSUE TITLE
[Bug]: Unable to run Playwriht Typescript Bitbucket Pipeline

### ISSUE THREAD

**Issue by ScarletMcLearn** [microsoft/playwright#33658]
### Version

1.49.0

### Steps to reproduce

Hello.

I have the following files:

bitbucket-pipelines.yml
[Ubuntu Pastebin](https://paste.ubuntu.com/p/9GvMzTCj3x/)

package.json
[Ubuntu Pastebin](https://paste.ubuntu.com/p/X8YHH9rScF/)

package.lock.json
[Ubuntu Pastebin](https://paste.ubuntu.com/p/GJMZr6b6t7/)

### Expected behavior

It should successfully run the pipeline.

### Actual behavior

When I try to run the pipeline, I get this error:
[Ubuntu Pastebin](https://paste.ubuntu.com/p/mhKCwxXCgx/)

### Additional context

Please suggest how to resolve this.

I tried several different images, but its not working.

Thank you for your time.

### Environment

```shell
bitbucket-pipelines.yml
[Ubuntu Pastebin](https://paste.ubuntu.com/p/9GvMzTCj3x/)

package.json
[Ubuntu Pastebin](https://paste.ubuntu.com/p/X8YHH9rScF/)

package.lock.json
[Ubuntu Pastebin](https://paste.ubuntu.com/p/GJMZr6b6t7/)
```

**Comment by dgozman** [comment]
@ScarletMcLearn Something is wrong with your setup. Most likely, your `playwright.config.ts` is in a different place from where you have `npm install`'ed your packages, and so it cannot find `@playwright/test`.

Unfortunately, we are not experts in bitbucket pipelines. I'd recommend to ask around on [Playwright's discord](https://aka.ms/playwright/discord), or seek help from the bitbucket community.

**Comment by ScarletMcLearn** [comment]
Thank you guys.

This is the solution in case anyone else faces a similar issue:

https://stackoverflow.com/questions/79201395/playwright-error-cannot-find-module-in-bitbucket-pipelines/79202647#79202647
