### ISSUE TITLE
[Bug]: NS_ERROR_PROXY_CONNECTION_REFUSED when trying to override headers in Firefox with Proxy enabled

### ISSUE THREAD

**Issue by paveldudka** [microsoft/playwright#33663]
### Version

1.48.0

### Steps to reproduce

In my setup I try to override "User-Agent" http header while using Firefox + HTTP Proxy 
However I get `NS_ERROR_PROXY_CONNECTION_REFUSED` error.
Important notes:
* I verified that my HTTP Proxy works fine
* Commenting out part that is responsible for http header solves the issue
* Switching to Chromium solves the issue

My script:

```
import asyncio
import logging

from playwright.async_api import ProxySettings, async_playwright
logging.basicConfig(level=logging.DEBUG)


async def main():
    proxy: ProxySettings = {
        "server": "<proxy host>",
        "username": "< proxy username>",
        "password": "<proxy password>",
    }
    

    async with async_playwright() as playwright, await playwright.firefox.launch(
        headless=False,
    ) as browser:
        context = await browser.new_context(proxy=proxy)
        page = await context.new_page()
        await page.route(
            "**/*",
            lambda route: route.continue_(
                headers={
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:131.0) Gecko/20100101 Firefox/131.0",
                }
            ),
        )

        await page.goto("https://bot.sannysoft.com/")

        await page.wait_for_timeout(30000)


if __name__ == "__main__":
    asyncio.run(main())
```

### Expected behavior

I expect web page to load

### Actual behavior

Calling `page.goto()` throws `NS_ERROR_PROXY_CONNECTION_REFUSED`

### Environment

```Text
- Operating System: MacOS 14.6.1
- CPU: Apple M3 Max
- Browser: Firefox
- Python Version: 3.12.5
```

**Comment by dgozman** [comment]
@paveldudka Did you have a chance to try the suggestion above? That will add user agent header as browser expects it.

In your snippet, you override **all headers** with just a single one `"User-Agent"`. This drops all other headers, including the proxy authorization header. Take a look at [this example](https://playwright.dev/python/docs/network#modify-requests) that properly keeps all the headers, and only modifies some of them.

**Comment by paveldudka** [comment]
@dgozman , setting UA during context creation works, however in my specific example context is created in completely different part of the code, so I can't really override UA at that stage :(

> In your snippet, you override all headers with just a single one "User-Agent"

Yes, this is just a sample snippet. In real code I don't drop the rest of the headers. But that don't have any impact on the issue.

I will start looking towards reworking the business logic, so UA is set during `new_context` call. Still strange that it works with Chromium, but not Firefox

**Comment by mxschmitt** [comment]
I'll close it for now as a won't fix - since we recommend setting the User-Agent when creating a context rather than doing it per each individual request via an override.
