### ISSUE TITLE
[Feature] Provide waitForSelector option on Element

### ISSUE THREAD

**Issue by Tallyb** [microsoft/playwright#3366]
Support waitForSelector on ElementHandle, similar to the one on page. 
`ElementHandle.waitForSelector(selector[, options])`; (selector can be optional here as well);

This can resolve 2 use cases I have encountered: 
**Case 1: Selecting a specific element**
Assume the following structure but with multiple levels and shadow doms (e.g. wrapping the label and wrapping the input): 
```
<div class="container>
  <label> Label1</label>  
<input type="text"/>
</div>
<div class="container>
  <label>Label2</label>
  <input type="text"/>
</div>
```

I want to grab the container by the label name: 
`const myField = await page.awaitForSelector('*css=div.container >> text="Label1")`
Now, I want to wait for something to happen on the subtree of this specific div such as: `myField.waitForSelector('input.valid')`.

**case 2: waiting for an element to disappear** 
Assume the following structure: 
```
<div> Name </div>
<div> Name </div>
<div> Name </div>
```

I want to be able to grab the 2nd item and after some action (e.g. delete), I want to wait until it is detached from the DOM: 
```
const myDiv = await page.$('css=div:nth-child(2)');
//some action
myDiv.waitForSelector({state: 'hidden'});
```

**Comment by dgozman** [comment]
Thank you for the issue! The proposal seems good, I will look into it.

**Comment by dgozman** [comment]
With #3501, version 1.4 will provide the following api:

```js
const myDiv = await page.$('css=div:nth-child(2)');
//some action
myDiv.waitForElementState('hidden');
```
