### ISSUE TITLE
[Regression]: Unable to open Playwright UI in Dark Mode.

### ISSUE THREAD

**Issue by ScarletMcLearn** [microsoft/playwright#33695]
### Last Good Version

1.49.0

### First Bad Version

1.49.0

### Steps to reproduce

Running the following command:
npx playwright test tests --ui

### Expected behavior

I want it to open in Dark mode.

### Actual behavior

In 1.48.1. - opens the UI in Dark Mode
In 1.49.0. - opens the UI in Light Mode

### Additional context

It was fixed previously. But its repeating again.

### Environment

```shell
npx envinfo --preset playwright

System:
OS: Windows 11 10.0.22631
CPU: (22) x64 Intel(R) Core(TM) Ultra 7 155H
Memory: 9.27 GB / 31.58 GB
Binaries:
Node: 20.15.1 - C:\Program Files\nodejs\node.EXE
npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
IDEs:
VSCode: 1.95.3 - E:\Project\Project_Tools\Microsoft VS Code\bin\code.CMD
Languages:
Bash: 5.1.16 - C:\Windows\system32\bash.EXE
npmPackages:
@playwright/test: ^1.49.0-beta-1732021985000 => 1.49.0
playwright: ^1.49.0 => 1.49.0
```

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/33660
