### ISSUE TITLE
[Feature] playwright-cli 

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#3371]
Publish `playwright-cli` with the following initial set of features:
- [ ] open Playwright browser
- [ ] support device emulation
- [ ] dump cookies on browser exit to help with state
- [ ] docs changes

**Comment by roughsoft** [comment]
record API ？

**Comment by roughsoft** [comment]
we can ref taiko repl.
https://github.com/getgauge/taiko#interactive-recorder

**Comment by pavelfeldman** [comment]
Spinning off into its own repo.
