### ISSUE TITLE
How to set a custom name for snapshot in the Playwright ?

### ISSUE THREAD

**Issue by DmytroNebelskyi** [microsoft/playwright#33715]
Hello everyone and thanks in advance !

I have a test named:
`test.only("TC-0003-Verify that user can import new HTML Creative Template (300x250)", async ({ page }) => {`

And I have a path configuration to be:
`snapshotPathTemplate: "{testFileDir}/../snaphots/{projectName}/{testFileName}/{testName}/{arg}{ext}"`

By using this approach Playwright generates:
/snaphots/regression-chrome/creativeTemplates.spec.ts/TC-0003-Verify-that-user-can-import-new-HTML-Creative-Template-300x250-/banner.png

I do not want to have a long scenario name in the snapshot path: "TC-0003-Verify-that-user-can-import-new-HTML-Creative-Template-300x250-"

Can I somehow cut the name to be: "TC-0003" or can I override it somewhere ?

Thanks a lot !

**Comment by dgozman** [comment]
This issue tracker is reserved for bug reports and feature requests.

For anything else, such as questions or getting help, please see:
- [The Playwright documentation](https://playwright.dev/)
- [Our Discord server](https://aka.ms/playwright/discord)

**Comment by DmytroNebelskyi** [comment]
> This issue tracker is reserved for bug reports and feature requests.
> 
> For anything else, such as questions or getting help, please see:
> 
> * [The Playwright documentation](https://playwright.dev/)
> * [Our Discord server](https://aka.ms/playwright/discord)

But when I was opening ticket there was "Questions", why u closed ?
