### ISSUE TITLE
[Feature]: I want to know how to click the cors iframe in close shadow root

### ISSUE THREAD

**Issue by fancy45daddy** [microsoft/playwright#33725]
### 🚀 Feature Request

I see playwright can click the element in iframe with different domain. But now the iframe is inside the close shadow root. I can not use playwright to click the iframe. I have to write an chrome extension content script to access the close shadow root like:
```
(async () =>
{
    await new globalThis.Promise(_ => globalThis.setTimeout(_, 1000 * 60))
    const shadowRoot = chrome.dom.openOrClosedShadowRoot(document.querySelector('div[style*="display: grid;"] > div > div'))
    const iframe = chrome.dom.openOrClosedShadowRoot(shadowRoot.querySelector('iframe').contentDocument.body)
    iframe.querySelector('input').click()
})()
```
But querySelector('iframe').contentDocument will return null due to different domain. I want to know how playwright access the dom of iframe with different domain. So I can use it in my case.

Use javascript? Use chrome extension? or any devtools?

### Motivation

N/A

**Comment by fancy45daddy** [comment]
I already try not working all the closed shadow roots still close.

**Comment by dgozman** [comment]
@fancy45daddy Helping to circumvent anitbot mechanisms is out of scope for Playwright, which is focused on testing.

**Comment by fancy45daddy** [comment]
i need the exact coordinate of element in shadow root for testing
