### ISSUE TITLE
[Bug]: Browser sometimes randomly does not open.

### ISSUE THREAD

**Issue by ScarletMcLearn** [microsoft/playwright#33733]
### Version

1.48.0

### Steps to reproduce

Run the command:
`npx playwright test tests 
`

### Expected behavior

Tests should run.
And show results as expected.

### Actual behavior

Sometimes randomly browser does not open.
Sometimes it also randomly works when called from the Terminal but not in VSCode.

### Additional context

Playwright Config: https://paste.ubuntu.com/p/H43RcrM79G/
Browser Config: https://paste.ubuntu.com/p/3qzwjfHxtP/
Global Setup: https://paste.ubuntu.com/p/6HHsQKVmfV/
Memory Dump: https://ufile.io/j529e628
Logs: https://ufile.io/0gzxkg91

Also, if I run the tests in UI mode (--ui) - everything runs fine.

### Environment

```shell
npx envinfo --preset playwright

  System:
    OS: Windows 11 10.0.22631
    CPU: (22) x64 Intel(R) Core(TM) Ultra 7 155H
    Memory: 13.71 GB / 31.58 GB
  Binaries:
    Node: 20.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.95.3 - E:\Project\Project_Tools\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.1.16 - C:\Windows\system32\bash.EXE
  npmPackages:
    @playwright/test: ^1.48.0 => 1.49.0
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
