### ISSUE TITLE
[Bug]: Playwright UI unable to find tests when ran from project root directory.

### ISSUE THREAD

**Issue by ScarletMcLearn** [microsoft/playwright#33745]
### Version

1.49.0

### Steps to reproduce

1. Given in Project Root
2. When Tests are in a subdirectory called tests in project root
3. And discovery for tests is made for any file starting with test_
4. Run `npx playwright test --ui`

### Expected behavior

1. Tests should be found in UI mode

### Actual behavior

1. Tests are not found.

### Additional context

1. Tests are found when you go inside the test directory and then run the same command.

### Environment

```shell
npx envinfo --preset playwright

  System:
    OS: Windows 11 10.0.22631
    CPU: (22) x64 Intel(R) Core(TM) Ultra 7 155H
    Memory: 13.71 GB / 31.58 GB
  Binaries:
    Node: 20.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.95.3 - E:\Project\Project_Tools\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.1.16 - C:\Windows\system32\bash.EXE
  npmPackages:
    @playwright/test: ^1.48.0 => 1.49.0
```

**Comment by mxschmitt** [comment]
Do you have your `playwright.config.ts` in a sub-directory? You can specify it when running UI Mode via

    npx playwright test --ui --config=./foo/playwright.config.ts

If this doesn't work, we need a small reproduction repository in order to triage this issue further. Thank you!

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
