### ISSUE TITLE
[BUG] When using login once using project dependency setup I am getting a browser opening and closing before each test using session storage

### ISSUE THREAD

**Issue by Aromal0105** [microsoft/playwright#33743]
I have implemented login once using project dependency as mentioned in below playwright document.
Link : https://dev.to/playwright/a-better-global-setup-in-playwright-reusing-login-with-project-dependencies-14

I have defined the session storage in project config as in the above document.
But before each test execution using session storage, I can see a browser getting opened and closed.

Below is the actual behaviour:
1. Dependent setup project runs and saves session storage.
2. A empty browser is getting opened and closed.
3. Test are executed in the new browser with login state using saved session storage.

Why is the 2nd step happening. I am not able to figure the issue by debugging.
 Is it expected or can anyone help me if you have experienced similar issue before.

**Comment by ScarletMcLearn** [comment]
Might be similar to https://github.com/microsoft/playwright/issues/33733 .

**Comment by ScarletMcLearn** [comment]
Might be similar to https://github.com/microsoft/playwright/issues/33733 .

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
