### ISSUE TITLE
[Bug]: Custom fixture title is not displayed in the html report.

### ISSUE THREAD

**Issue by OlegsHanins** [microsoft/playwright#33741]
### Version

1.49.0

### Steps to reproduce

https://github.com/OlegsHanins/playwright-fixtures-title-bug

`npm instal`
`npx playwright test`
`npx playwright show-report`

"My custom fixture title" is not mentioned in html report
https://github.com/OlegsHanins/playwright-fixtures-title-bug/blob/b32ec3a8d0e25edf666b641e52a3bd4498c94267/tests/fixtures-titles.spec.ts#L11

### Expected behavior

Expect to work as its described in the docs https://playwright.dev/docs/test-fixtures#custom-fixture-title
"custom title that will be shown in test reports"

### Actual behavior

Dont see my custom fixture title

![Image](https://github.com/user-attachments/assets/c3e8019f-59a1-4965-9417-3b4cd929187c)

### Additional context

Same issue metioned by othesr in playwright discord

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 2700 Eight-Core Processor
    Memory: 14.07 GB / 15.60 GB
    Container: Yes
  Binaries:
    Node: 20.18.0 - ~/.nvm/versions/node/v20.18.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.18.0/bin/npm
  IDEs:
    VSCode: 1.95.3 - /mnt/d/Microsoft VS Code/bin/code
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.49.0 => 1.49.0
```

**Comment by mxschmitt** [comment]
I can reproduce - does not show up in Trace Viewer nor HTML report.
