### ISSUE TITLE
[Bug]: webServer not been shut down after finished running

### ISSUE THREAD

**Issue by dylannnn** [microsoft/playwright#33756]
### Version

1.49.0

### Steps to reproduce

Run the test with a webServer configuration on a port
After test finished, CTRL + C to terminate the job

### Expected behavior

I expected the webServer will also be shut down after terminate the testing

### Actual behavior

The webServer is still up and running

### Additional context

It used to be fixed by #19049 

### Environment

```shell
System:
  OS: MAC OS - 15.0.1 (24A348)
  CPU: Apple M1 Pro
Binaries:
  Node: 18.20.4
  npm: 10.7.0
npmPackages:
  @playwright/test: 1.49.0
```

**Comment by dylannnn** [comment]
I'm not sure if this is related to #33379.

**Comment by clockback** [comment]
Given that the associated PR was closed due to being stale, this issue really ought to be reopened.
