### ISSUE TITLE
playwright component testing control url

### ISSUE THREAD

**Issue by pan-alexey** [microsoft/playwright#33755]
### Please do not submit this issue.

- [x] I understand

**Comment by pan-alexey** [comment]
I'm trying to use Playwright component testing, but I need to use a remote browser. Are there any ways to use component testing with a remote browser and HTTP over SSH (like ngrok)?

**Comment by mxschmitt** [comment]
The following should work for you: https://github.com/microsoft/playwright/issues/26482

I'm not sure I follow what "and HTTP over SSH (like ngrok)" is.

**Comment by pan-alexey** [comment]
Thank you very much for your response. I will try to explain my use case. I need to run Playwright tests, but I want to use the browsers on my computer to do this, connecting to the browsers similarly to a Selenium Grid setup. 

When running component tests, I observe that the browser opens the link http://localhost:3100. However, because the browser is not on my local device, I need to establish a tunnel (such as using https://ngrok.com/docs/http/).

So, I need to first set up a tunnel from http://localhost:3100 to http://mytunnelip so the remote browser can open my page. 

Therefore, I need to:
1. Be able to assign a port for the server 3100.
2. Replace the address http://localhost:3100 with http://mytunnelip in the component test.

The address http://mytunnelip is just an example.

**Comment by pan-alexey** [comment]
Hmm, find in code, very 😊
![Image](https://github.com/user-attachments/assets/83b9fdc6-05e1-4b76-a493-72e3894e590f)

**Comment by pan-alexey** [comment]
But component testing does not working with selenium grid

**Comment by pan-alexey** [comment]
But is very strange, becous i can not rewrite base url. I have fixture for rewrite base url, but in ct browser always try open http://localhost:8001/


Error message:
```
    Error: net::ERR_CONNECTION_REFUSED at http://localhost:8001/
    Call log:
      - navigating to "http://localhost:8001/", waiting until "load"
```

How can i rewrite base url before start component testing?

**Comment by pan-alexey** [comment]
Any idea, why a can not use fixture for rewrite baseUrl?

**Comment by mxschmitt** [comment]
Have you tried to put `baseURL: 'https://your-hostname'` in your config in the use section of it?

Also you can customise the port by putting `ctPort: 1234` next to it.

**Comment by pan-alexey** [comment]
Thank you very much for the response. However, this option doesn't work for me. Here's why:

When the test is run, vite with a server for component testing is launched first. Then the global.setup.ts script is run, in which I create a tunnel and obtain a URL. Next, I create a fixture and set the baseURL to the URL that was created by the tunnel.

But because my fixture is created after the Playwright-ct fixture, it creates a problem where I can't set or overwrite PLAYWRIGHT_TEST_BASE_URL.

If I use a hack, everything works:

```
export default async function globalSetup() {
  const teardownTunneler = !process.env["CI"]
    ? await setupTunneler({
        localport: Number(STATIC_PORT),
      })
    : () => {};

  setInterval(() => {
    process.env["PLAYWRIGHT_TEST_BASE_URL"] =
      process.env["__TUNNELER_BASE_URL__"];
  }, 0);

  console.log(process.env["PLAYWRIGHT_TEST_BASE_URL"]);
  return async () => {
    teardownTunneler();
  };
}

```
What do you think, would it be useful to add such code?


![Image](https://github.com/user-attachments/assets/290f6d7e-8e47-41c8-9cb6-fbb21234ffb2)

**Comment by mxschmitt** [comment]
Since this seems like a very advanced use-case its unlikely that we'll add something like this. You could probably add a auto worker fixture which re-writes this env var if you like: https://playwright.dev/docs/test-fixtures#automatic-fixtures

**Comment by pan-alexey** [comment]
Большое спасибо, я обязательно попробую этот код

**Comment by mxschmitt** [comment]
awesome I'll close it for now since there is a workaround and it seems answered.
