### ISSUE TITLE
Is there any options to hide the Blinking effect on the page when taking the screenshot?

### ISSUE THREAD

**Issue by knight2015** [microsoft/playwright#33766]
### Please do not submit this issue.

- [x] I understand

**Comment by knight2015** [comment]
When I call the playwright screenshot() function to take a screenshot of an element and the page, the browser page usually flickers. Is there any way to avoid the blinking effect on the page?

**Comment by jeff-an** [comment]
Yes, usually page screenshot is fine but to do element screenshot you can follow the bounding box method and crop it yourself. I had filed a similar issue https://github.com/microsoft/playwright/issues/29487

**Comment by mxschmitt** [comment]
You can do

    await expect(locator).toHaveScreenshot('image.png', { caret: 'hide' });

would that work for you?

**Comment by knight2015** [comment]
> Yes, usually page screenshot is fine but to do element screenshot you can follow the bounding box method and crop it yourself. I had filed a similar issue [#29487](https://github.com/microsoft/playwright/issues/29487)

Thank you for your answer,  it seems to be an effective approach.

**Comment by diegohaz** [comment]
> You can do
> 
> ```
> await expect(locator).toHaveScreenshot('image.png', { caret: 'hide' });
> ```
> 
> would that work for you? See [here](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-have-screenshot-1).

I actually need the opposite: for the caret to always be visible and not blink. Is this possible?
