### ISSUE TITLE
[Bug]: Filling a textarea element with lots of text lines is surprisingly slow

### ISSUE THREAD

**Issue by tomppa65** [microsoft/playwright#33761]
### Version

1.48.0

### Steps to reproduce

1. Copy this gist to you python IDE: https://gist.github.com/tomppa65/4ddea187309e41401869e0f1e3ffb35b
2. Run it.
3. Go grab a cup of your favorite beverage
4. In about five minutes you will have the results the python script prints out.

### Expected behavior

I would expect all three browsers to act like firefox does. It can fill a textarea with 4000 lines of text in under a second.

### Actual behavior

Webkit takes some seconds at 2000 lines of text being filled to a textarea, 7 seconds at 3000 and over 12 at 4000 lines.
Chromium takes the biscuit, though: 5 seconds at 1000, 22 seconds at 2000 lines, 48 seconds at 3000 lines and about 85 seconds at 4000 lines.

### Additional context

This is not a serious bug, just something I stumbled upon when writing automated test cases. Found a workaround too, I implemented a javascript function to just set the value attribute of a textarea element, then press tab on it so events fire.

The times seem to vary a bit. There have been times when four minutes were not enough for chromium to get the job done.
This may not even be Playwright problem but perhaps you can forward it, if that turns out to be true?

### Environment

```Text
- Operating System: [Windows 11 Pro, 23H2]
- CPU: [Intel Core i7 10875H CPU @ 2.30 GHz]
- Browser: [All]
- Python Version: [3.12]
- Other info:
```

**Comment by mxschmitt** [comment]
Investigation notes:

- CDP `'Input.insertText'` is slow for large newline separated inputs
- For each of the lines the layout is getting re-calculated, which seems to be different compared to when we paste it in
- Performance trace shows this as well. Its too large to upload it here tho:

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/23077
