### ISSUE TITLE
[Bug]: Headless mode ignores arguments like "ignoreDefaultArgs". works only in headful mode.

### ISSUE THREAD

**Issue by hschn** [microsoft/playwright#33768]
### Version

1.49.0

### Steps to reproduce

based on [this](https://playwright.dev/docs/api/class-browsertype#browser-type-launch) example, I want to ignore the default value for "notifications", which is "allow". I want to have the chrome-default (which is "ask")

![Image](https://github.com/user-attachments/assets/3e5a0ec2-573f-4f1e-b97b-66b90037ccc6)

this is my code:
```

const context: BrowserContext = await chromium.launchPersistentContext('./lpc',{
        ignoreDefaultArgs: ['--notifications'],
        headless: true,
    });
```

if I switch "headless" to false, everything works as expected and the value for "notifications" has "Ask (default)"

### Expected behavior

settings for "notifications" have the value "Ask (default)

### Actual behavior

settings for "notifications" have the value "Allow"

### Environment

```shell
System:
	OS: Ubuntu 22.04.5 LTS
	CPU: Ryzen pro 6850u (8)
Binaries:
	Node: 20.17.0
	npm: 10.8.2
playwright:
	@playwright/tests: 1.49.0
```

**Comment by hschn** [comment]
ok thx. 

`  permissions: ['notifications'] ` 

sets it to "allow", which is the same as the chromium default if started from playwright. any idea how to set the value not do "allow" but to "Ask", like in the screenshot of the chrome settings in my first post?

**Comment by mxschmitt** [comment]
It should `prompt` by default. Can you provide us a minimal reproduction which we can run locally which is not working as expected?

You can also modify [our tests](https://github.com/microsoft/playwright/blob/f3ae940684dd26de1d4674d66dd98b8722b08d50/tests/library/permissions.spec.ts#L58) but they return 'prompt' when I don't grant them - so it looks all good?

**Comment by hschn** [comment]
the link to the tests was super helpful, thx! 

I could compare now the notification value for headless and headful, and "prompt" is the default for both indeed.

this issue can be closed. not a bug.
