### ISSUE TITLE
[Bug]: VSC extension isn't capturing all entered text and semi unresponsive when hitting tab or enter buttons

### ISSUE THREAD

**Issue by sharesies-amy** [microsoft/playwright#33773]
### Version

1.49.0

### Steps to reproduce

1. Open VS Code
2. Click `Record new` under Playwright Testing tools
3. Observe Chromium window open
4. The app I'm testing requires me to log in, enter info into form
5. Observe that codegen hasn't captured all text. It seems to only capture the first character of what I enter in the field.
6. Attempt to tab between fields
7. Codegen hasn't captured this keyboard action

### Expected behavior

I expect all inputs to be recorded and generate code

```
    await page.getByTestId('login-email-input').click()
    await page.getByTestId('login-email-input').fill('testing-account@test.com')
    await page.getByTestId('login-email-input').press('Tab');
    await page.getByTestId('password-input').fill('password 123')
```

### Actual behavior

The generated code as below

```
    await page.getByTestId('login-email-input').click()
    await page.getByTestId('login-email-input').fill('t')
    await page.getByTestId('password-input').click() -- because I can't record tab
    await page.getByTestId('password-input').fill('p')
```

### Environment

```shell
System:
    OS: macOS 15.1.1
    CPU: (8) arm64 Apple M1
    Memory: 186.22 MB / 16.00 GB
  Binaries:
    Node: 22.1.0 - ~/.nvm/versions/node/v22.1.0/bin/node
    Yarn: 3.2.1 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v22.1.0/bin/npm
  IDEs:
    VSCode: 1.95.3 - /usr/local/bin/code
  Languages:
    Bash: 5.2.37 - /opt/homebrew/bin/bash
  npmPackages:
    @playwright/test: ^1.49.0 => 1.49.0
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
