### ISSUE TITLE
Intermittent issue with snapshot comparison

### ISSUE THREAD

**Issue by amankagithub** [microsoft/playwright#33776]
### Please do not submit this issue.

- [x] I understand

**Comment by amankagithub** [comment]
We use playwright HTML report to compare between actual and expected snapshots when test fails . One issue has been happening intermittently for us where the actual snapshot is not present in the reports .
 ![Image](https://github.com/user-attachments/assets/9fbef8ce-9a62-439d-b5bb-982227b09024)

Is it possible that during playwright test assertion the actual snapshot is not created at all while matching with the expected snapshot?

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!

**Comment by amankagithub** [comment]
We didn't have a repro as this is intermittent , that's why I didn't create a bug report , but rather a question/help issue . If you find anything related to the above issue do update us . Thanks .
