### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by NissimAriel** [microsoft/playwright#33777]
### Version

Version 1.49.0

### Steps to reproduce

1. Install Playwright.
2. Use it to write tests.

### Expected behavior

No connectivity to server issue should accrue. 

### Actual behavior

Sudenly playwright.config.ts\js gets red and an error appears under "import { defineConfig, devices } from '@playwright/test';" - "Internal error - unable to connect to test servers".

### Additional context

New installation didnt solve it.
The command install newplaywright scrambles the project. I expect more efficient solution, so that we wont be needing to copy the project to new folders.

### Environment

```shell
System: macOS Version 15.1.1
Node Version 10.9.1
Playwright - Version 1.49.0
TypeScript.
```

**Comment by mxschmitt** [comment]
Looks like your 10.9.1 is your NPM version. Whats your Node.js version? (node --version).

Does this also happen with [a new project](https://playwright.dev/docs/intro) from the getting started?

**Comment by NissimAriel** [comment]
My Node version is v22.11.0.
It happened several times after projects were already up and running.

**Comment by Skn0tt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
