### ISSUE TITLE
[Bug]: Slowness issue in application navigations when used http_credentials in browser context for SSO Authentication

### ISSUE THREAD

**Issue by surbhiD** [microsoft/playwright#33786]
### Version

1.49.0

### Steps to reproduce

self._browser = BrowserType.create_browser(browser_type)
self._context = self._browser.new_context(
http_credentials = {'username': username,'password': password} if username and password else None,
no_viewport = True)
self._page = self._context.new_page()
1.I am launching my browser like this and authenticating in azure sso login .
2.I am able to login but after that on every page navigation browser is taking too much time to load the page.This is causing my application to behave very slow.
Note : however if i use cookies in place of using http_credentials its working very fast.Also using Http_credential based login is the only solution for me as 

### Expected behavior

The application should behave as usual as its behaving when interacting manual.the page loading should not take unusual time

### Actual behavior

The application takes too much time on every page navigation

### Additional context

Works fine on firefox nightly build. Issue is there for chrome and edge

### Environment

```shell
- Operating System: Windows 10 enterprise
- CPU: [arm64]
- Browser: [All, Chromium, Firefox, WebKit]
- Python Version: [3.11.4]
```

**Comment by Skn0tt** [comment]
You could try running a test with traces on, and take a look at the network tab to see if there's any long operations.

**Comment by surbhiD** [comment]
BssoInterrupt_Core_zKox_QMcTIVut7mG_Z9Eew2 this call is there for chrome in tracer network tab of tracer but not for firefox

**Comment by surbhiD** [comment]
Hello Team,

I’ve identified that certain calls  are additional in network tab for Chrome, and some are taking longer compared to Firefox. However, I’m unsure how to resolve these discrepancies. I’d appreciate your guidance on addressing this issue.

Thank you!

**Comment by yury-s** [comment]
Unfortunately we can't help much without a repro. Try to reduce the test scenario to a repro example that you can share and file a new issue with that. Seeing in the trace which requests took longer should give you an idea what is being slow since you are familiar with the app.
