### ISSUE TITLE
[Bug]: Playwright Test for VSCode v1.1.12 does not launch browser

### ISSUE THREAD

**Issue by dpasqua-newclassrooms** [microsoft/playwright#33783]
### Version

1.1.12

### Steps to reproduce

This issue can be reproduced with a default install of Playwright. Here's my setup:

- Playwright -- 1.49
- Playwright Test for VSCode -- v1.1.12
- VSCode -- 1.95.3
- Node -- 23.3.0

The test appears to start, but the browser is not launched, even though **Show browser** is selected. After clicking on the Stop button, the test continues to run unless VSCode is shut down.

My workaround so far has been to revert the extension to v1.0.22 so I can use the Debug button, but then all of my breakpoints are ignored. 

### Expected behavior

I want to be able to successfully use the latest version of Playwright Test for VSCode and have my tests stop at breakpoints.

### Actual behavior

The latest version of Playwright Test for VSCode starts a does, but does not launch a browser and hangs until I have to close VSCode. I also want my tests to stop at breakpoints when I use the Debug option.

### Environment

```shell
System:
  OS: Windows 11 10.0.22631
  CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-13700H
  Memory: 15.71 GB / 31.62 GB
Binaries:
  Node: 23.3.0 - C:\Program Files\nodejs\node.EXE
  npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
IDEs:
  VSCode: 1.95.3 - C:\Users\dpasqua\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
Languages:
  Bash: 5.1.16 - C:\Windows\system32\bash.EXE
```

**Comment by mxschmitt** [comment]
We need more information in order to act on issues like this. Would it be possible to share a reproduction with us? Does it happen with the default project you create in the [getting started](https://playwright.dev/docs/intro)?

**Comment by dpasqua-newclassrooms** [comment]
Here are the error messages I see if I toggle the tools, then click on the extension to debug.

My apologies, attaching the PNG file didn't work.

`default.exp-tas.com/vscode/ab:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
api.github.com/copilot_internal/user:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED`

**Comment by mxschmitt** [comment]
These logs look unfortunately unrelated. I tried using:

```
PS C:\Users\maxschmitt\Developer\tmp> npm --version
10.9.0
PS C:\Users\maxschmitt\Developer\tmp> node --version
v23.3.0
```

On Windows and was unfortunately not able to reproduce. Its interesting tho that they are not getting resolved - is your machine locked down / has special anti-virus on it?

Does only `Debug` not work or also just when clicking the `Run` button?

Does it work if you run `npx playwright test` inside your terminal?

**Comment by tasawar-hussain** [comment]
@dpasqua-newclassrooms Try turning off github co pilot

**Comment by dpasqua-newclassrooms** [comment]
@mxschmitt It's only `debug` that doesn't work; using the `Run` button works as expected. The tests run with `npx playwright test`, but they hang when I add `--debug` to the end of the command.

When I added `--debug`, it never went past the `page.goto`; it just launched a blank browser. ![Image](https://github.com/user-attachments/assets/32241cef-db6b-454c-bb96-a23c7324bea7)

**Comment by dpasqua-newclassrooms** [comment]
@tasawar-hussain I don't use the GitHub Copilot extension, and I don't have the Intellicode completions checkbox checked in the Settings. Is there anywhere else I should check?

**Comment by dpasqua-newclassrooms** [comment]
@mxschmitt I forgot to add to my last response that our anti-virus software isn't causing the issue. The security engineer and I walked through the steps to check that before I logged this ticket.

**Comment by dpasqua-newclassrooms** [comment]
@mxschmitt -- I tried followed these exact steps on my Mac laptop, and I was able to successfully use the Debug option of the extension. I pasted my environment settings.

```
System:
  OS: macOS 14.2.1
  CPU: (11) arm64 Apple M3 Pro
  Memory: 951.34 MB / 18.00 GB
Binaries:
  Node: 20.10 - ~/.nvm/versions/node/v20.10.0/bin/node
  npm: 10.9.0 - ~/.nvm/versions/node/v20.10.0/bin/npm
Languages:
  Bash: 3.2.57 - /bin/bash
npmPackages:
  @plawright/test: ^1.49.0 => 1.49.0
```

**Comment by dpasqua-newclassrooms** [comment]
@mxschmitt Just an update. I bumped Node back to v18 and was able to successfully use the Debug option of the VSCode extension.

**Comment by mxschmitt** [comment]
I'm a bit confused https://github.com/microsoft/playwright/issues/33783#issuecomment-2515322852 you mentioned that Debug of a test in VSCode is working. In https://github.com/microsoft/playwright/issues/33783#issuecomment-2511860668 you mention, that Run is working as well. So both is working?

> The tests run with npx playwright test, but they hang when I add --debug to the end of the command.

This is expected, you need to press the Continue button in the Inspector window which opens see [here](https://playwright.dev/docs/debug#run-in-debug-mode-1). Does the Inspector window open?

What does `npx playwright --version` yield to?

Have you tried restarting VSCode?
