### ISSUE TITLE
[Bug]: Unable to Capture All WebViews on Android Emulator Using Playwright _android Module

### ISSUE THREAD

**Issue by arpit-kyada** [microsoft/playwright#33780]
### Version

^1.49.0

### Steps to reproduce

1) Run multiple webViewes on Android App  
2) capture with await device.webViews() or device.addListener('webview',() => {}) (device is coming from _android => const [device] = await _android.devices();)
3) you can verify how many webViews are open in App => chrome://inspect/#devices

### Expected behavior

The await device.webViews() method should return all the WebViews currently open in the app, and the device.addListener('webview', () => {}) should capture every WebView that opens within the app.

### Actual behavior

The await device.webViews() method returns only the first WebView that is opened in the app, while subsequent WebViews are not included in the returned array. Additionally, the device.addListener('webview', () => {}) event listener is only capturing the initial WebView and does not detect any additional WebViews.

### Additional context

const { test, _android } = require('@playwright/test');

test('has title', async () => {
  const [device] = await _android.devices();

  if (!device) {
    console.log('No device connected');
    return;
  }

  console.log(`Model: ${device.model()}`);
  console.log(`Serial: ${device.serial()}`);

  const allWebViews = await device.webViews();
  console.log('Total WebViews Open:', allWebViews?.length);

  device.addListener('webview', async (context) => {
    const webviewContext = await context.page();
    const pageUrl = webviewContext.url();
    const allWebViews = await device.webViews();
    console.log('In Event Listener WebView Context:', {
      pageUrl,
      openWebViewCount: allWebViews?.length,
    });
  });

  await device.waitForEvent('webview');
  await device.waitForEvent('webview');
});

### Environment

```shell
System: 
Android Emulator: Pixel 3a API 34
```

**Comment by mxschmitt** [comment]
Would it be possible to provide a self-contained reproduction, which we can run locally to reproduce your issue? Ideally a apk file which you can share with us in combination with a Playwright test/script.

**Comment by Skn0tt** [comment]
Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
