### ISSUE TITLE
[Bug]: Specifying `client_certificates` overrides browser launch arguments

### ISSUE THREAD

**Issue by mt-xing** [microsoft/playwright#33790]
### Version

1.49.0

### Steps to reproduce

Create a python file with the following:
```
from playwright.sync_api import sync_playwright
from time import sleep

p = sync_playwright().start()
browser = p.chromium.launch(args=["--host-resolver-rules=MAP google.com bing.com"], headless=False)
ctx = browser.new_context(ignore_https_errors=True, client_certificates=[{
    "origin": "https://test.com",
    "pfxPath": "./cert.p12"
}])
# ctx = browser.new_context(ignore_https_errors=True)
page = ctx.new_page()
page.goto("https://google.com")

sleep(60)
```

Also create a TLS certificate and name it `cert.p12` in the same directory.

Run this file (eg: `python test.py` if the file is named `test.py`)

### Expected behavior

Browser should respect the host resolution rules, causing `google.com` to fail to render (as it's trying to reach `bing.com`'s IP addresses)

### Actual behavior

`google.com` loads as browser is not respecting host resolution rules

### Additional context

Uncomment the `ctx = browser.new_context(ignore_https_errors=True)` line and comment out the original context call, to turn the file into:

```
from playwright.sync_api import sync_playwright
from time import sleep

p = sync_playwright().start()
browser = p.chromium.launch(args=["--host-resolver-rules=MAP google.com bing.com"], headless=False)
# ctx = browser.new_context(ignore_https_errors=True, client_certificates=[{
#     "origin": "https://test.com",
#     "pfxPath": "./cert.p12"
# }])
ctx = browser.new_context(ignore_https_errors=True)
page = ctx.new_page()
page.goto("https://google.com")

sleep(60)
```

Run this again. Notice now that the browser respects the host mapping. Clearly the host mapping browser argument gets lose when specifying `client_certificates`

### Environment

```Text
- Operating System: Windows 11
- CPU: Intel Core i7-11370H
- Browser: Chromium
- Python Version: 3.11.9
- Other info:
```

**Comment by mxschmitt** [comment]
Passing a custom arg falls [outside of the scope](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-option-args) for Playwright. For this use-case, we would recommend to adjust your application so you can open it on `localhost:3000` instead of having to rewrite the actual hostname. Alternatively, a bit more advanced you could write your own proxy which takes care of the hostname rewrite and pass it to Playwright.
