### ISSUE TITLE
[Bug]: playwright hangs while waiting for pending navigations

### ISSUE THREAD

**Issue by dgozman** [microsoft/playwright#33806]
### Version

1.49.0

### Steps to reproduce

Reported by @chrisbottin in https://github.com/microsoft/playwright/pull/32899#issuecomment-2506437082.

The problem we are having is when we click on a link which triggers the `beforeunload` dialog, after we dismiss the dialog and try to interact with the page again, we get timeout errors.

Here is a simple test replicating the error ...

```js
const {chromium} = require('playwright');
const {expect} = require('@playwright/test');

(async () => {
    const browser = await chromium.launch();
    const page = await browser.newPage();

    await page.mainFrame().goto('https://www.npmjs.com/');

    expect(await page.mainFrame().title()).toStrictEqual('npm | Home');

    await page.evaluate(() => {
        window.onbeforeunload = () => false;
    });

    page.on('dialog', async dialog => {
        await dialog.dismiss();
    });

    await page.getByRole('menuitem', {name: 'Teams'}).click({noWaitAfter: true});

    await page.evaluate(() => {
        window.onbeforeunload = null;
    });

    // Timeout error will occur here:
    await page.getByRole('menuitem', {name: 'Teams'}).click({timeout: 1000});

    expect(await page.mainFrame().title()).toStrictEqual('npm | Teams');

    await browser.close();
})();
```

### Expected behavior

Test passes.

### Actual behavior

The test fails on the line `await page.getByRole('menuitem', {name: 'Teams'}).click({timeout: 1000});` with the error:

```
locator.click: Timeout 1000ms exceeded.
Call log:
  - waiting for getByRole('menuitem', { name: 'Teams' })
  - waiting for navigation to finish...
```

### Additional context

During debugging, I noticed the `pendingDocument()` is set to `{documentId: undefined, request: undefined}`

If this line https://github.com/microsoft/playwright/blob/b5bd543cc6935f62732da3b6183bd319eb2bdc2a/packages/playwright-core/src/server/page.ts#L472 is changed to the following, our problem disappears:

```js
if (!mainFrame || !mainFrame.pendingDocument() || !mainFrame.pendingDocument().documentId)
      return;
```

### Environment

```shell
unknown
```

**Comment by dgozman** [comment]
As a workaround, try running with `PLAYWRIGHT_SKIP_NAVIGATION_CHECK=1 npx playwright test` and let me know whether that helps.

**Comment by chrisbottin** [comment]
@dgozman Yes using `PLAYWRIGHT_SKIP_NAVIGATION_CHECK` environment variable works. This is the route we were going to take to be able to use `1.49` but we don't think it's a long-term solution.

**Comment by seahindeniz** [comment]
I'm not sure if it is related, but it doesn't work for me! Tried it on `@playwright/test@1.49.0`

```bash
PLAYWRIGHT_SKIP_NAVIGATION_CHECK=1 playwright test test.spec.ts --debug
```

![Image](https://github.com/user-attachments/assets/cdb5d0f4-07a6-45ec-9c84-332b6f4bb2af)
