### ISSUE TITLE
[Bug]: PLaywright UI deployed on Scalingo Ubuntu 22.04 LTS with missing dependencies for webkit

### ISSUE THREAD

**Issue by spiquera** [microsoft/playwright#33800]
### Version

1.49.0

### Steps to reproduce

Deploying Playwright UI in a Scalingo app, using a image based on Ubuntu22.04 (https://hub.docker.com/r/scalingo/scalingo-22/tags) by creating a Procfile which executes `npx playwright test --ui-port=$PORT --ui-host=0.0.0.0` when the container starts.

Installed the following buildpacks by a file .buildpacks:
https://github.com/Scalingo/apt-buildpack.git
https://github.com/Scalingo/nodejs-buildpack.git

Created a file called Aptfile with the necessary dependencies for the brwosers to make them work:
# tools

xvfb
fonts-noto-color-emoji
fonts-unifont
libfontconfig1
libfreetype6
xfonts-cyrillic
xfonts-scalable
fonts-liberation
fonts-ipafont-gothic
fonts-wqy-zenhei
fonts-tlwg-loma-otf
fonts-freefont-ttf

# chromium

libasound2
libatk-bridge2.0-0
libatk1.0-0
libatspi2.0-0
libcairo2
libcups2
libdbus-1-3
libdrm2
libgbm1
libglib2.0-0
libnspr4
libnss3
libpango-1.0-0
libwayland-client0
libx11-6
libxcb1
libxcomposite1
libxdamage1
libxext6
libxfixes3
libxkbcommon0
libxrandr2

# firefox

ffmpeg
libasound2
libatk1.0-0
libcairo-gobject2
libcairo2
libdbus-1-3
libdbus-glib-1-2
libfontconfig1
libfreetype6
libgdk-pixbuf-2.0-0
libglib2.0-0
libgtk-3-0
libpango-1.0-0
libpangocairo-1.0-0
libx11-6
libx11-xcb1
libxcb-shm0
libxcb1
libxcomposite1
libxcursor1
libxdamage1
libxext6
libxfixes3
libxi6
libxrandr2
libxrender1
libxtst6

# webkit

libsoup-3.0-0
libenchant-2-2
gstreamer1.0-libav
gstreamer1.0-plugins-bad
gstreamer1.0-plugins-base
gstreamer1.0-plugins-good
libicu70
libatk-bridge2.0-0
libatk1.0-0
libcairo2
libdbus-1-3
libdrm2
libegl1
libepoxy0
libevdev2
libffi7
libfontconfig1
libfreetype6
libgbm1
libgdk-pixbuf-2.0-0
libgles2
libglib2.0-0
libglx0
libgstreamer-gl1.0-0
libgstreamer-plugins-base1.0-0
libgstreamer1.0-0
libgtk-4-1
libgudev-1.0-0
libharfbuzz-icu0
libharfbuzz0b
libhyphen0
libjpeg-turbo8
liblcms2-2
libmanette-0.2-0
libnotify4
libopengl0
libopenjp2-7
libopus0
libpango-1.0-0
libpng16-16
libproxy1v5
libsecret-1-0
libwayland-client0
libwayland-egl1
libwayland-server0
libwebpdemux2
libwoff1
libx11-6
libxcomposite1
libxdamage1
libxkbcommon0
libxml2
libxslt1.1
libx264-163
libatomic1
libevent-2.1-7
libavif13

Add into the Procfile a command to install the necessary browsers `npx playwright install `.

### Expected behavior

When tests are run inside PLaywright UI for webkit, we expect to see them running instead of complaining about missing dependencies.

### Actual behavior

When a webkit test runs inside Scalingo (even the playwright example ones), it fails due to missing dependencies for this browser, this is the error shown in the PLaywright UI:

Error: browserType.launch: 
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Please install them with the following command:      ║
║                                                      ║
║     sudo npx playwright install-deps                 ║
║                                                      ║
║ Alternatively, use apt:                              ║
║     sudo apt-get install libgles2\                   ║
║         gstreamer1.0-libav                           ║
║                                                      ║
║ <3 Playwright Team                                   ║
╚══════════════════════════════════════════════════════╝

### Additional context

After installing the dependencies, after `npx playwright install`, scalingo logs show this:
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Please install them with the following command: ║
║ ║
║ sudo npx playwright install-deps ║
║ ║
║ Alternatively, use apt: ║
║ sudo apt-get install libgles2\ ║
║ gstreamer1.0-libav ║
║ ║
║ <3 Playwright Team ║
╚══════════════════════════════════════════════════════╝

Also take in count that commands that need administrator permission, such as `npx playwright install-deps` or `npx playwright install --with-deps` are not a possibility because Scalingo team prevents root operations like those ones, for this reason we install the broswers by running `npx playwright install` and the dependencies are installed via apt as they suggested to do with buildpack + Aptfile.

### Environment

```shell
System:
OS: Linux 5.4 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
Container: Yes
Bash: 5.1.16 - /usr/bin/bash
CPU: (8) x64 Intel Xeon Processor (Icelake)
npmPackages:
Node: 22.11.0 - ~/.scalingo/node/bin/node
@playwright/test: ^1.49.0 => 1.49.0
Memory: 4.05 GB / 39.18 GB
Languages:
Binaries:
npm: 10.9.0 - ~/.scalingo/node/bin/npm
```

**Comment by mxschmitt** [comment]
Scalingo falls outside of our support. You could try getting the list from [here](https://github.com/microsoft/playwright/blob/fd25f3ab8540a644da56cc011c7e7202e21fd045/packages/playwright-core/src/server/registry/nativeDeps.ts#L237-L363) - that should hopefully help.

**Comment by spiquera** [comment]
Hello, I double check the list of dependencies and is the exact same as the one you mention.
I was told that Scalingo installs dependencies in /app/.apt/usr/lib, but the aptfile installs dependencies in /app/.apt/usr/lib/x86_64-linux-gnu/ is there a way to change that dependency path in Playwright or create an environment variable for that?

Thanks
