### ISSUE TITLE
[Bug]: Emulate viewport size (npx playwright codegen --viewport-size=800,600 playwright.dev) is failing

### ISSUE THREAD

**Issue by AtulKrSharma** [microsoft/playwright#33805]
### Version

1.49.0

### Steps to reproduce

Was working on requirements for viewport emulation and found this link on the documentation: Emulate viewport size [https://playwright.dev/docs/codegen#emulate-viewport-size] and tried the code sample given there.

`npx playwright codegen --viewport-size=800,600 playwright.dev`

![Image](https://github.com/user-attachments/assets/6cf72e4b-6e17-41bd-b35a-5abcd6b1b006)

### Expected behavior

Playwright show open a browser window with its viewport set to a specific width and height

### Actual behavior

`npx playwright codegen --viewport-size=800,600 playwright.dev`

![Image](https://github.com/user-attachments/assets/aaafc04a-f6d5-4ac2-8f10-fc8d1312154c)

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1265U
    Memory: 17.76 GB / 31.67 GB
  Binaries:
    Node: 22.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.95.3 - C:\Users\AtulSharma\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.2.21 - C:\WINDOWS\system32\bash.EXE
  npmPackages:
    @playwright/test: ^1.49.0 => 1.49.0
```

**Comment by AtulKrSharma** [comment]
It works fine, if I use this in CLI:-

`npx playwright codegen --viewport-size "800,600" playwright.dev`

**Comment by dgozman** [comment]
@AtulKrSharma I guess this depends on your shell. This works fine for me, but perhaps fails in power shell. I'll update the docs.

**Comment by AtulKrSharma** [comment]
thank you @dgozman . Now, I confirm that bug is fixed and working fine now.
