### ISSUE TITLE
[Bug]: Playwright-testing-Automation:Not able to click UI radio buttons in latest angular version webpages

### ISSUE THREAD

**Issue by AshikSajjad** [microsoft/playwright#33813]
### Version

10.9.1

### Steps to reproduce

I tried to automate my front end application. I tried it with record option. When I tried to click on the radio buttons the page start moving up and down. After so many analysis I found that older angular version didn't have this issue. My web page is using latest angular version and this is applicable for all the radio buttons. Is there any solutions for this??

### Expected behavior

Able to click on radio buttons

### Actual behavior

Not able to click. when we click the button it start moving up and down.

### Environment

```shell
Version : angular v16.2.12
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
