### ISSUE TITLE
[Docs]: document the expected format of the proxy `bypass` value

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#33812]
### Page(s)

https://playwright.dev/python/docs/network#http-proxy

### Description

this is the only mention of the `bypass` field but it doesn't explain what the format of the value is supposed to be:

> You can optionally specify username and password for HTTP(S) proxy, you can also specify hosts to bypass proxy for.

i'm trying to get it to bypass the proxy for localhost by setting its value to `localhost` but can't seem to get it to work.

**Comment by mxschmitt** [comment]
See here for the API documentation: https://playwright.dev/python/docs/api/class-browser#browser-new-context-option-proxy. We can add a cross-reference to that.

If you think its a bug - I recommend to re-file as a bug and provide a self-contained reproduction.

**Comment by DetachHead** [comment]
unfortunately the network configuration at my workplace is such a mystery it's extremely difficult to narrow anything down to a self contained repro, i was able to workaround my issue by just not passing the `proxy` argument at all when navigating to localhost
