### ISSUE TITLE
[Feature]: native and hybrid mobile apps testing

### ISSUE THREAD

**Issue by Helpmerunaway** [microsoft/playwright#33827]
### 🚀 Feature Request

Add the ability to test native and hybrid mobile applications in Playwright. This will allow developers and testers to use Playwright for automating the testing of mobile applications, not just web applications.

### Example

With this feature, users will be able to write tests for their mobile applications using the same API they already use for web tests. For instance, a tester could run automated scenarios on iOS and Android devices, interacting with UI elements such as buttons, text fields, and lists, similar to how it is done in web applications. This may include actions such as:

• Launching the application on a real device or emulator.

• Interacting with native controls (e.g., gestures, scrolling).

• Checking the display of the user interface and functionality.

### Motivation

Supporting the testing of mobile applications will significantly enhance the functionality of Playwright and make it a more versatile tool for developers and QA teams. This will allow:

• Streamlining the testing process for teams already using Playwright for web applications, minimizing the need to use multiple tools.

• Accelerating the release of mobile applications through test automation.

• Improving the quality of mobile applications through a more thorough and structured testing approach.

Implementing this feature will make Playwright more competitive in the market for testing automation tools and help attract more users.

**Comment by Skn0tt** [comment]
Folding into https://github.com/microsoft/playwright/issues/27778#issuecomment-1777754813.

> There are no immediate plans for extending this functionality/adding similar support for iOS.
