### ISSUE TITLE
[Feature]: How can I launch the browser on Mac OS and use Live Debugging feature when I develop the project by Remote SSH

### ISSUE THREAD

**Issue by a1245582339** [microsoft/playwright#33825]
### 🚀 Feature Request

Due to some company policies, I have to use VSCode Remote SSH to develop the front-end project. However, the target server is a Linux environment and does not provide a graphical interface.

I want to use powerful features such as **Live Debugging**, **UI Mode**, and **Record scripts** in this development mode. Is there any way to launch the browser on my local computer and use these features while operating in VSCode?

Looking forward to your reply.

### Motivation

As Feature Request.

**Comment by Skn0tt** [comment]
Hi there! Running tests in Headed mode won't work via SSH, so Live Debugging and script recording won't be possible. You can use UI mode though, see https://playwright.dev/docs/test-ui-mode#docker--github-codespaces for how. Let me know if that helps!
