### ISSUE TITLE
[Bug]: Opening Snapshot in New Tab - from Playwright UI Mode  - does not follow the zoom out state.

### ISSUE THREAD

**Issue by ScarletMcLearn** [microsoft/playwright#33820]
### Version

1.49.0

### Steps to reproduce

1. Given, this is my base page:
```
import { Page, Locator } from "@playwright/test";

export class BasePage {
	protected _page: Page; // Keep the original page property protected

	constructor(page: Page) {
		this._page = page;

		this.setZoomOut();

	}

	// Public getter for the page property
	public get page(): Page {
		return this._page;
	}

// Function to set the zoom-out transformation
	private async setZoomOut(): Promise<void> {
		try {
			await this._page.evaluate(() => {
				document.body.style.transform = "scale(0.6)";
				document.body.style.transformOrigin = "0 0"; // Adjust origin to top-left corner
			});
			console.log("Zoom-out transformation applied successfully.");
		} catch (error) {
			console.error(
				"Error while applying zoom-out transformation:",
				error
			);
		}
	}
}
```

2. When I extend base page to any other page and try to access any URL
3. The page successfully gets zoomed out
4. Click open snapshot in new tab

### Expected behavior

1. Snapshot should show full screen
2. Also browser when running the tests should follow appropriate resolution

### Actual behavior

1. Snapshot shows cropped
2. Browser follows a weird zoomed in resolution - for this reason having to manually zoom out.
3. https://ibb.co.com/M1XRcYb
4. 

### Additional context

The browser by default opens in a weird zoomed in state.
When zoom out manually, the snapshots look improper - not correct resolution.

### Environment

```shell
npx envinfo --preset playwright                          

  System:
    OS: Windows 11 10.0.22631
    CPU: (22) x64 Intel(R) Core(TM) Ultra 7 155H
    Memory: 8.33 GB / 31.58 GB
  Binaries:
    Node: 20.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.95.3 - E:\Project\Project_Tools\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.1.16 - C:\Windows\system32\bash.EXE
  npmPackages:
    @playwright/test: ^1.48.0 => 1.49.0
```

**Comment by Skn0tt** [comment]
Hi @ScarletMcLearn! Can you please expand? From what you've described, you're complaning that your document is scaled that your document is scaled. 

Hi @ScarletMcLearn! Could you expand on what you're trying to achieve here? On first glance, it looks like everything's working as intended.

**Comment by ScarletMcLearn** [comment]
@Skn0tt  thank you for the response. Why is there so much white space in the snapshot?

**Comment by Skn0tt** [comment]
> Why is there so much white space in the snapshot?

That's what `transform: scale(0.6)` does - it resizes the `body` element to 0.6 times its original size. So it shrinks towards the top left, and the rest of the viewport is blank. It's different from zooming out with <kbd>Ctrl+/-</kbd>,

**Comment by Skn0tt** [comment]
You say the browser follows a weird zoomed in resolution. Is that what you're trying to work around with `transform`? Maybe that's the bug we should be looking to solve.

**Comment by ScarletMcLearn** [comment]
Yes, @Skn0tt . There's a weird zoom resolution. When I go to a website using other browsers it loads in proper resolution / scale factor.

But when I load in PW it loads in a too zoomed in state.

Hence I was trying to zoom out. 

But when I zoom out, it makes the rest of the screen blank. 

Is there any way I can zoom out similar to CTRL - using PW?

And can you also suggest regarding the default state being extremely zoomed in?

Thank you!

**Comment by Skn0tt** [comment]
I think the `transform` is doing what it's supposed to do here. The culprit seems to be that the page is weirdly zoomed in in the first place. Please provide us with a reproduction repo so we can take a look at that. Thank you!

**Comment by ScarletMcLearn** [comment]
[This is the URL](https://american-equity-qa-uatx.unqork.io/app/financial-viability/#/auth/login)

```
import { test, expect } from '@playwright/test';

test('navigate to login page', async ({ page }) => {
  // Navigate to the specified URL
  await page.goto('https://american-equity-qa-uatx.unqork.io/app/financial-viability/#/auth/login');

  // Optionally, you can add an assertion to verify that the page has loaded correctly
  await expect(page).toHaveURL('https://american-equity-qa-uatx.unqork.io/app/financial-viability/#/auth/login');
});
```

The repository is private. Any other way I can provide reproducibility?

**Comment by ScarletMcLearn** [comment]
@Skn0tt I am sharing a minimal code sample below. Please check it out and suggest.
[Code](https://ufile.io/3dqybkhw)

**Comment by Skn0tt** [comment]
That's not minimal at all. We can't spend time debugging your code, i'm afraid. Please create a blank Playwright project with `npm init playwright` and make edits to recreate the bug.
