### ISSUE TITLE
[Feature] provide details on the element receiving mouse events

### ISSUE THREAD

**Issue by Tallyb** [microsoft/playwright#3382]
Let us know what functionality you'd like to see in Playwright and what is your use case.

"element does not receive pointer events" is very hard to debug in nontrivial cases. Providing ANY information on the blocking element(s), even on the first one if multiple exists, can save hours of debugging...

Do you think others might benefit from this as well?
Benefit? they will love you!

**Comment by dgozman** [comment]
Sounds like a great feature!
