### ISSUE TITLE
[Bug]: the Chrome starting by playwright doesn`t support the Shortcuts of  Ctrl  - or Ctrl  +

### ISSUE THREAD

**Issue by soldiergp** [microsoft/playwright#33828]
### Version

1.49

### Steps to reproduce

the Chrome strating by playwright doesn`t support the Shortcuts of  Ctrl  - or Ctrl  +  , the web didn`t zoom out or zoom  in.

Using code:
page.locator("body").press("ControlOrMeta+-")
or
page.locator("body").press("Control+-")
 
it doesn`t work ,            but the hotkeys Control -   or Control +  could change the web size  which start the Chrome normally

**Comment by Skn0tt** [comment]
`.press("ControlOrMeta+-")` won't work as you expect. It goes to the `body` DOM node. But the `Ctrl -` short cut you're used to from using general chrome goes to the browser shell, which is a different thing.

Folding into https://github.com/microsoft/playwright/issues/2497.
