### ISSUE TITLE
[Docs]:  Cannot use({ headless }) in a describe group, because it forces a new worker.

### ISSUE THREAD

**Issue by baixiaoyu2997** [microsoft/playwright#33833]
### Page(s)

https://playwright.dev/docs/api/class-test#test-use

### Description

![Image](https://github.com/user-attachments/assets/b87a6963-0bd5-4eac-942f-534d744cbb78)
![Image](https://github.com/user-attachments/assets/69e2f028-476c-4358-a091-09d7ce39dce3)

```typescript
import test from '@playwright/test';
import { chromium } from 'playwright';

test.describe('group1', () => {
  test.use({ headless: false });
  test('nihao', async () => {
    const browser = await chromium.launch();
    const page = await browser.newPage();
    await page.goto('https://example.com');

    await page.pause();
  });
});
```

**Comment by Skn0tt** [comment]
The error message explains what's going on and how to fix it - I think everything's as expected here.

**Comment by nlmhanh110** [comment]
> The error message explains what's going on and how to fix it - I think everything's as expected here.

No. I don't think so. The test.use is used within a describe block not before ones (exactly like the documentation) but it returns error.
