### ISSUE TITLE
[Bug]: keyboard inputs are not working in GitHub Actions during CI run

### ISSUE THREAD

**Issue by renardeinside** [microsoft/playwright#33832]
### Version

1.49.0

### Steps to reproduce

The problem only arises in CI run, and not locally. 

My test practically does the following:

1. Input some text
2. hit ctrl+z (I'm using ControlOrMeta + Z) 
3. Expect undo

However this doesn't happen in CI. Locally on my Mac everything works as expected. 
Here is the CI run for example: https://github.com/renardeinside/strophe/actions/runs/12105019260

### Expected behavior

CtrlOrMeta+Z are handled correctly in github actions CI run

### Actual behavior

I see from the logs and traces that the undo event didn't happen. 
I'm pretty sure it happens in local tests so it shouldn't be an issue with my code.

### Environment

```shell
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Install Playwright Browsers
        run: npx playwright install chromium

      # note: we need to build before running tests because it's a chrome extension
      - name: Test
        run: |
          yarn build   
          yarn test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
```

**Comment by Skn0tt** [comment]
Hi Ivan! Could you try boiling this down to a minimal repro that we can use to look at it locally? Also, try if you can reproduce it locally by running in headed vs headless mode.
