### ISSUE TITLE
[Bug]: Playwright global config - metadata is not attached to tests

### ISSUE THREAD

**Issue by yonatanai** [microsoft/playwright#33831]
### Version

1.49.0

### Steps to reproduce

Maybe I didn't understand how it should work, but https://playwright.dev/docs/api/class-testproject#test-project-metadata says that adding the metadata should attach it as serialized JSON to the test report.
First, there is a string in the example, and in the TS, it requires an object. 
Secondly, I don't see the metadata attached to the test report.

```typescript
export default defineConfig<GlobalConfiguration>({
  // ...
  metadata: {
    moreData: 'moreValue',
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
      metadata: {
        someData: 'someValue',
      },
    },
  ],
});

```
![Image](https://github.com/user-attachments/assets/51b0f23d-9368-4fab-aa21-4145d35510d0)

### Expected behavior

Metadata will be attached to the test report when defined in the playwright config

### Actual behavior

Can't see the metadata in the report

### Environment

```shell
Mac M1, node 18.17.0,
```

**Comment by Skn0tt** [comment]
Hey Yonatan! I think the documentation is off on this one. The HTML reporter doesn't show arbitrary metadata there, just a number of metadata fields like commit ID. See https://github.com/microsoft/playwright/blob/4e33ade28754a8cdc9fbc0302d3dc3a0f3eb05c0/packages/html-reporter/src/metadataView.tsx#L64-L124 for reference.

Could you expand on what kinds of metadata things are you looking to add to the report? Maybe there's a different Playwright feature you can use for that.

**Comment by Skn0tt** [comment]
Closing as stale.
