### ISSUE TITLE
[Bug]: Missing dependencies for webkit browsers

### ISSUE THREAD

**Issue by spiquera** [microsoft/playwright#33835]
### Version

1.49.0

### Steps to reproduce

Create a buildpack to install playwright browsers dependencies with apt, including the following in a Aptfile for webkit:
# webkit

libsoup-3.0-0
libenchant-2-2
gstreamer1.0-libav
gstreamer1.0-plugins-bad
gstreamer1.0-plugins-base
gstreamer1.0-plugins-good
libicu70
libatk-bridge2.0-0
libatk1.0-0
libcairo2
libdbus-1-3
libdrm2
libegl1
libepoxy0
libevdev2
libffi7
libfontconfig1
libfreetype6
libgbm1
libgdk-pixbuf-2.0-0
libgles2
libglib2.0-0
libglx0
libgstreamer-gl1.0-0
libgstreamer-plugins-base1.0-0
libgstreamer1.0-0
libgtk-4-1
libgudev-1.0-0
libharfbuzz-icu0
libharfbuzz0b
libhyphen0
libjpeg-turbo8
liblcms2-2
libmanette-0.2-0
libnotify4
libopengl0
libopenjp2-7
libopus0
libpango-1.0-0
libpng16-16
libproxy1v5
libsecret-1-0
libwayland-client0
libwayland-egl1
libwayland-server0
libwebpdemux2
libwoff1
libx11-6
libxcomposite1
libxdamage1
libxkbcommon0
libxml2
libxslt1.1
libx264-163
libatomic1
libevent-2.1-7
libavif13

Set in a script.sh which executes when the container runs, to make ffmpeg work:
export PLAYWRIGHT_BROWSERS_PATH=0
export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:/app/.apt/usr/lib/x86_64-linux-gnu/pulseaudio/:/app/.apt/usr/lib/x86_64-linux-gnu

Then execute:
npx playwright install

Then deploy the ui playwright inside a ubuntu 22.04 container:
npx playwright test --ui-port=$PORT --ui-host=0.0.0.0

### Expected behavior

Expected to be running tests in Webkit without dependencies problems.

### Actual behavior

When running a webkit test in PLaywright UI, even the test examples, i get:

Error: browserType.launch: 
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Please install them with the following command:      ║
║                                                      ║
║     sudo npx playwright install-deps                 ║
║                                                      ║
║ Alternatively, use apt:                              ║
║     sudo apt-get install libgles2\                   ║
║         gstreamer1.0-libav                           ║
║                                                      ║
║ <3 Playwright Team                                   ║
╚══════════════════════════════════════════════════════╝

### Additional context

Do i need to install the browsers in a certain path, such as app/.apt/usr/lib/x86_64-linux-gnu folder where dependencies are installed by apt buildpack, can i tell in playwright.config.js anything to make webkit browser aware of depdendencies? The rest of browsers are working fine. 

Since I have limited permission inside the container, I am currently unable to execute a npx playwright install-deps, which needs admin rights, thats why browser dependencies are being installed with apt buildpack-

### Environment

```shell
System:
OS: Linux 5.4 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
Container: Yes
Bash: 5.1.16 - /usr/bin/bash
CPU: (8) x64 Intel Xeon Processor (Icelake)
npmPackages:
Node: 22.11.0 - ~/.scalingo/node/bin/node
@playwright/test: ^1.49.0 => 1.49.0
Memory: 4.05 GB / 39.18 GB
Languages:
Binaries:
npm: 10.9.0 - ~/.scalingo/node/bin/npm
```

**Comment by Skn0tt** [comment]
Hi there! Playwright should be running fine on Ubuntu - is there a chance that Scalingo is doing something weird with the Ubuntu they provide you? Maybe talk to them to figure out what's going wrong here.

**Comment by Shirueopseo** [comment]
I asked the Scalingo team and what they suggested is to install the browser dependencies trough the apt buildpack and include all of them in an Aptfile. This way seems to install them all but then when a webkit test runs, it seems to not getting two dependencies (which by logs where installed). They even don't know what is happening and told me to ask to you.

**Comment by spiquera** [comment]
I asked the Scalingo team and what they suggested is to install the browser dependencies trough the apt buildpack and include all of them in an Aptfile. This way seems to install them all but then when a webkit test runs, it seems to not getting two dependencies (which by logs where installed). They even don't know what is happening and told me to ask to you, if anything can be done or if there is a way that **libgles2** and **gstreamer1.0-libav** are not found by playwright browsers.

**Comment by spiquera** [comment]
> Hi there! Playwright should be running fine on Ubuntu - is there a chance that Scalingo is doing something weird with the Ubuntu they provide you? Maybe talk to them to figure out what's going wrong here.

I asked the Scalingo team and what they suggested is to install the browser dependencies trough the apt buildpack and include all of them in an Aptfile. This way seems to install them all but then when a webkit test runs, it seems to not getting two dependencies (which by logs where installed). They even don't know what is happening and told me to ask to you, if anything can be done or if there is a way that libgles2 and gstreamer1.0-libav are not found by playwright browsers.
