### ISSUE TITLE
[Bug]: Chrome is automatically getting closed in the middle if any testcase got failed

### ISSUE THREAD

**Issue by Kartheeswari-git** [microsoft/playwright#33847]
### Version

1.49.0

### Steps to reproduce

Issue: Lets say I have 10 testcases. During the execution, for some reason testcase#5 failed and now its closing the crome and opening the new one to execute the testcase#6. 

### Expected behavior

It should execute testcase #6 from the same chrome where testcase#5 left instead of closing it. Its working like this in Playwright python and facing the issue with Playwright Js

### Actual behavior

Its closing the chrome if any testcase got failed which is affecting all the upcoming testcases in the suite. 

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz
    Memory: 5.90 GB / 19.74 GB
  Binaries:
    Node: 22.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.9.1 - ~\node_modules\.bin\npm.CMD
  IDEs:
    VSCode: 1.95.3 - C:\Users\Karthee\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.1.4 - C:\Windows\system32\bash.EXE
  npmPackages:
    @playwright/test: ^1.49.0 => 1.49.0
    playwright: ^1.49.0 => 1.49.0
```

**Comment by Skn0tt** [comment]
Hi there! Playwright's working as intended here. Could you elaborate on why it's important to your usecase that chrome's not restarted?

**Comment by Kartheeswari-git** [comment]
I want to avoid restarting Chrome on failure and instead maintain the same Chrome context throughout the test suite execution. Here's the scenario: 

We execute our product test cases in the following structure:

**Suite1**: 56 test cases  
**Suite 2**: 30 test cases  

Each suite contains test cases for specific pages, combining both UI validation and functionality tests. During execution, if an issue occurs (e.g., the UI doesn't display the expected error message), a particular test case might fail. However, the subsequent test case is supposed to continue from the same page where the previous one left off. 

Currently, because Chrome is being closed and reopened upon failure, the test loses the page state required for the next execution. Setting this in a "Before All" method isn't feasible since each test case starts on a different state.

**Comment by AnzeKop** [comment]
Running into a similar issue in our app, we want to have 1 persistant browser assigned to the BrowserManager class but as the app can hit errors we don't want this to restart the browser as it leads to this error when being used

```plaintext
Browser logs:

<launching> /Users/anze/Library/Caches/ms-playwright/chromium_headless_shell-1148/chrome-mac/headless_shell --disable-field-trial-config --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding,ThirdPartyStoragePartitioning,LensOverlay,PlzDedicatedWorker --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --unsafely-disable-devtools-self-xss-warnings --enable-use-zoom-for-dsf=false --use-angle --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --disable-gpu --disable-dev-shm-usage --disable-software-rasterizer --disable-extensions --no-sandbox --single-process --user-data-dir=/var/folders/zb/hgzc5jv96xg8sjcm44y344yw0000gn/T/playwright_chromiumdev_profile-W8Cz0p9tkW8s --remote-debugging-pipe --no-startup-window
<launched> pid=13433
[pid=13433][err] [1204/140344.549627:WARNING:viz_main_impl.cc(85)] VizNullHypothesis is disabled (not a warning)
[pid=13433][err] [1204/140344.575595:ERROR:cv_display_link_mac.mm(165)] CVDisplayLinkCreateWithCGDisplay failed. CVReturn: -6670
```
