### ISSUE TITLE
[Bug]: `page.goto` takes very long

### ISSUE THREAD

**Issue by Swathi-00** [microsoft/playwright#33846]
### Version

1.49

### Steps to reproduce

I am using Playwright version 1.49 with TypeScript in VS Code. During test execution, loading a URL takes at least 22 seconds for each tests, which significantly slows down the overall execution. Has anyone experienced a similar issue?
currently, I am using chrome and edge browser, facing this loading issue in both browsers.
Note: My browser configuration and network connection are both fine, so I don't believe that's the cause.

### Expected behavior

The URL should load and open the webpage more quickly.

### Actual behavior

 #![Image](https://github.com/user-attachments/assets/9b769da1-4075-4277-b0e7-062642982673)

just to load the url "google.de" its taking 22 seconds

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
    Memory: 48.88 GB / 63.73 GB
  Binaries:
    Node: 22.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 4.5.3 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.95.3 - C:\Users\EPRAKASBE\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.49.0 => 1.49.0
```

**Comment by Skn0tt** [comment]
Hi there! Could you provide us with a minimal repro that showcases this? Loading `google.de` is fast for me, so there's clearly something special about your setup.

**Comment by Swathi-00** [comment]
My code
test('my test', async ({ browser }) => {
  const context = await browser.newContext();
  await context.tracing.start({ screenshots: true, snapshots: true });
  const page = await context.newPage();
  await page.goto('https://www.google.de/');
  await context.tracing.stop({ path: 'trace-test-case.zip' })
});

playwright config defined under projects
{
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        launchOptions: {
          args: ['--ignore-certificate-errors, --disable-extensions', '--no-sandbox', '--disable-setuid-sandbox']
        },
        ignoreHTTPSErrors: true,
}

**Comment by Skn0tt** [comment]
That's not a self-contained repro. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
