### ISSUE TITLE
[Bug]: Show trace viewer is not showing live trace

### ISSUE THREAD

**Issue by adityabeniwal** [microsoft/playwright#33848]
### Version

1.49.0 

### Steps to reproduce

System info
Playwright Version: [1.49.0 ]
Operating System: [ Windows 11]
Browser: [Chromium]
Other info:

Steps

1. Tick Show trace viewer.
2. Run any test.
3. Check the trace viewer.

![Image](https://github.com/user-attachments/assets/a0ca1b75-4753-4c46-9a03-0a0077f02247)
![Image](https://github.com/user-attachments/assets/3a566967-d31e-46bf-8962-0ae163caeb4d)
![Image](https://github.com/user-attachments/assets/267b70ae-1ec1-466f-b036-f70f4553dc3a)

### Expected behavior

It should show step by step of actions in test file while running just like UI Mode

### Actual behavior

Show trace viewer but tell me "Select test to see the trace" while running. After finish the test, the results finally appear.

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 13th Gen Intel(R) Core(TM) i7-1365U
    Memory: 2.09 GB / 15.64 GB
  Binaries:
    Node: 20.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.2 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.95.3 - C:\Users\ndladi01\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.49.0 => 1.49.0
    playwright-performance: ^1.0.2 => 1.0.2
```

**Comment by Skn0tt** [comment]
Hi there! Could you provide us with a reproduction repo that we can use to look at this?

**Comment by Skn0tt** [comment]
When I try it on my machine, I can see the "Select test to see the trace" overlay, but it goes away after the test starts running. So something's different with your setup, and the repro should help figure that out.
