### ISSUE TITLE
[Feature]: Option to blur input element after locator.fill()

### ISSUE THREAD

**Issue by ValorHeart** [microsoft/playwright#33849]
### 🚀 Feature Request

Some dynamic web applications wait for input elements to blur before triggering a network request to the backend to persist the data.
It would be comfortable to have the option to blur after using fill() instead of explicitly writing both actions in a large-scale testing project.

### Example

`page.locator().fill('', { blur: true })`

### Motivation

Developer experience

**Comment by Skn0tt** [comment]
Sounds like you're looking for a helper function:

```ts
async function fillAndBlur(locator, content) {
   await locator.fill(content)
   await locator.blur()
}
```
