### ISSUE TITLE
[Bug]: Playwright browsers keeps triggering Windows Credentials via SSO

### ISSUE THREAD

**Issue by mstancl** [microsoft/playwright#33850]
### Version

1.49.0

### Steps to reproduce

```java
  Playwright.CreateOptions createOptions = new Playwright.CreateOptions();
        Map<String, String> map = new HashMap<>();

        map.put("PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD", "1");
        map.put("PLAYWRIGHT_NODEJS_PATH", System.getenv(PropertiesConstants.PLAYWRIGHT_NODE_JS_PATH));
        createOptions.setEnv(map);
        try (Playwright playwright = Playwright.create(createOptions)) {
            Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setChannel("msedge").setHeadless(false));
            Page page = browser.newPage();
            page.navigate("URL-BEHIND-SSO");
        }
```

Just a simple opening of a new microsoft edge browser that, as a first step, opens URL of Web application, that is behind SSO (single sign on) in Microsoft Edge that is already present on the machine.
Also because of our workstation policy, we need to use the node.exe in already installed folder, hence passing the property. 

### Expected behavior

Browser opens in an incognito mode, which triggers a redirect to SSO , that opens without any credentials being passed from the browser.

### Actual behavior

SSO redirect happens, but is pre-filled with the username of the user that is logged in on the machine.

### Additional context

Hi,

I am trying to automate a web application that is behind an SSO in our company (this SSO is  internally done here where I work).
This SSO (as confirmed by the team responsible for it) asks for Windows Credentials via pop-up, to pre-fill the screen and, if successfull (the retrieval of the Windows credentials) , it will also ask for 2FA token on the redirect screen.

If it fails (to retrieve the windows credentials), it will not pre-fill the screen and will trigger a different redirect, to username+password screen, without 2FA (so non human, machine users can log in).

I tried to do the same action in manually opened browser, in an incognito mode and it works as expected (the incognito does not pass any windows credentials, so it triggers the username+password). Also Selenium does the same.
Playwright however, keeps redirecting me to the other redirect, where 2FA is needed, hence blocking the automation. 

I tried several things as explained here :
https://github.com/microsoft/playwright/issues/15367 
https://github.com/microsoft/playwright/issues/29297
https://stackoverflow.com/questions/64549577/prevent-sso-with-playwright

Which suggests to pass an extra argument of  --auth-server-allowlist="*" or --auth-server-allowlist="_"
but none of that worked. 

I would greatly appreciate any support,

Thank you very much!

### Environment

- Operating system - Windows 10
- Browser - Microsoft edge Version 130.0.2849.46 (Official build) (64-bit)
- JDK 21
- Playwright version 1.49.0

**Comment by mxschmitt** [comment]
Have you tried using a [persistent context](https://playwright.dev/java/docs/api/class-browsertype#browser-type-launch-persistent-context)? This should align more with what Selenium does under the hood. Playwright by default uses in-memory profiles compared to Selenium.

**Comment by mstancl** [comment]
I tried it, and I was able to kind of hack my way around to get it working...but I still believe this is a defect. 
Here is what I did :


1) I opened edge://version in a new page of Selenium and Playwright, to compare them both, to make sure the flags are the same to be able to debug in the same environment
2) I noticed that Playwright is passing twice as many things and was missing few, so I disabled the extra ones and added the missing ones. I was then able to compare it again vie edge://version and it was indeed matching. 
3) Now the behavior was strange, playwright was opening a new page automatically on creation of the browser, even without calling the .newPage() method. (this was caused by disabling the flag of --no-startup-window as I found later) . But the interesting thing was the this window was now correctly triggering the SSO redirect as it should have. 
4) However, the page opened by .newPage() method was then again ignoring all the flags provided at the startup and was again triggering the incorrect sso redirect. The issue was that the browser did not 'see' this page and I could not use it. So it was no use to me.
5)I then tried to use the persistent context option to create the browser and I was able to use the originally opened window (thanks to disabling the --no-startup-window), but the newPage() again was ignoring that and the SSO was failing.

Conclusion for this, is that I believe the newPage() method is ignoring whatever flags were provided at the beginning. For example, I create browser and IGNORE the --inprivate and --no-startup-window flags which will automatically on creation of browser, create a new, private window. However, once you call .newPage() on the created browser, this again is showing that its incognito, ignoring that it was provided at the beginning. 


Sample code below :

` try (Playwright playwright = Playwright.create()) {
            Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setChannel("msedge").setHeadless(false).setIgnoreDefaultArgs(List.of("--no-startup-window","--inprivate"))); //creation of browser will automatically open a NON incognito window
            Page page = browser.newPage(); // this will open a new page, but its again incognito. Ignoring the flags configured previously
        }`

This is unfortunately a blocker. We would need the browser to be using the flags for all the new pages as well. 
Is there any possible solution?

**Comment by kasikcz** [comment]
I think this looks exactly like my problem right now on 1.47.1. Currently i added Authorization with fixture and usage of storageState before some test which needs the SSO and when i navigate to office.com click on sign-in then input account name it instantly logs me in without asking for password, if I use account which i don't use on my local it works normally asking for pw.

` storageState: ({ workerStorageState }, use) => use(workerStorageState),
  workerStorageState: [async ({ browser}, use) => {
    const authFile = path.resolve(__dirname, '../.auth/user.json')
    if (fs.existsSync(authFile)) {
      console.log('Found existing authentication state, reusing it...')
      // Reuse existing authentication state if any.
      await use(authFile)
      return
    }
    console.log('No authentication state found, logging in...')
    const page = await browser.newPage({ storageState: undefined })
    await page.goto('https://login.microsoftonline.com')
    await page.context().clearCookies()
    // Sign in using creds from env variables
    await page.getByPlaceholder('Email, phone, or Skype').fill('myACC')
    await page.getByRole('button', { name: 'Next' }).click()
    await page.waitForURL('https://www.office.com/')

    // End of authentication steps.
    await page.context().storageState({ path: authFile })
    await page.close()
    await use(authFile)
  }, { scope: 'worker' }]`

**Comment by mxschmitt** [comment]
This sounds working as expected - if you are using launch() it ends up in a OffTheRecord Chromium profile what the browser often visualises as incognito and when you use launchPersistentContext() it ends up in a normal browser session like you are used from Selenium. The latter should work for your use-case. We need something we can run locally in order to reproduce further. Since you are using Microsoft Edge the policies apply which might infer with Playwright. Maybe you could give us a copy of what `edge://policies` shows? Enterprise policies is something we can't control / support see [here](https://playwright.dev/docs/browsers#google-chrome--microsoft-edge).

**Comment by mstancl** [comment]
You are right, I did a few further checks regarding our enterprise policies and that seems indeed to be the issue.
I was however able to run this via LaunchPersistentContext which now works the way we need.

Closing the issue.

Thanks for your assistance, truly appreciate it.
