### ISSUE TITLE
Why tests in UI mode are run in a separate detached window

### ISSUE THREAD

**Issue by BoisAuLit** [microsoft/playwright#33854]
### Please do not submit this issue.

- [x] I understand

**Comment by BoisAuLit** [comment]
I'm setting up playwright for our team. When I run tests in UI mode, the tests are launched in a separate chrome instance (other than the UI mode chrome window itself), please look at the screenshot attached.

![Image](https://github.com/user-attachments/assets/a7d5eb07-077b-4831-834e-12dc1489f3da)

I'm sorry that I cannot show a clear screenshot of it because of sensitive data reasons.

As you can see in the screenshot, the separate chrome instance is always launched on top of the UI mode window itself, and the separate window on top will be closed automatically after the tests finished running.

**Comment by BoisAuLit** [comment]
Hi @Skn0tt , as this thread has been closed, could you please advise me the correct way of asking this kind of questions (where should it be). Thanks a lot. Have a nice day.

**Comment by Skn0tt** [comment]
Hi there! As per the issue template, the discord is a good place to ask questions:

![Image](https://github.com/user-attachments/assets/ea0431c9-3494-4bee-9fb9-805f22d9fbbb)


When I closed this, I didn't see your actual question yet though. Let me answer that:

The browser-like window you see on the right side of UI mode is not the real browser the test is executed in. It shows a "snapshot" of the real browser. That's why you can scroll through the timeline and see how the page looked as the test progressed.

While executing the test, it's important that the browser used for testing is as similar to a real browser as possible. So that's why we open it in a separate window. In headless mode, it doesn't even open the browser!

> My goal is to launch the tests in the embedded window in the UI mode window itself.

Could you elaborate on why that's your goal?

**Comment by BoisAuLit** [comment]
Hi @Skn0tt , thank you for your reply.
Please look athe screenshot below
![Image](https://github.com/user-attachments/assets/744b1037-a5eb-4459-968e-8bdb5af414fb)

If UI mode opens a separate window on top of it, it's not only very distracting, but also I lost my view of the "middle column" in the UI mode window (where it shows at which exact step I'm executing my tests, and it shows all the selectors, assertions, and also network calls in the middle column).

It's very weird that several weeks ago everything was working fine. I have no idea what I have changed in my project to make this "separate detached window" occur.

So I would like to know if there's a specific setting or configuration in playwright that can toggle this "open tests in separate chrome instance in UI mode" feature off.

**Comment by Skn0tt** [comment]
I think you're looking for headless test execution! In headless execution, no browser window is opened, and you're only seeing things in the UI. Maybe something changed in your `playwright.config.ts` around the `headless` option, or did you start running with `npx playwright test --ui --headed`? https://playwright.dev/docs/api/class-testoptions#test-options-headless

**Comment by Skn0tt** [comment]
Also, try going to the settings tab in the bottom left and uncheck the "Show browser" setting.

**Comment by BoisAuLit** [comment]
@Skn0tt  My bottom left settings only allows me to toggle dark mode.![Image](https://github.com/user-attachments/assets/ece91420-59ab-4359-8493-e85b8f3d39cc)

**Comment by BoisAuLit** [comment]
> I think you're looking for headless test execution! In headless execution, no browser window is opened, and you're only seeing things in the UI. Maybe something changed in your `playwright.config.ts` around the `headless` option, or did you start running with `npx playwright test --ui --headed`? https://playwright.dev/docs/api/class-testoptions#test-options-headless

So in fact, I know how to use headless mode, that's what I opted for in my pipelines (jenkins). But in daily development of playwright on our local machine, we would like to see a "live" version to better visualize what's happening.

I launched playwright with the following options (the --headed option is not included):
```
npx playwright test --ui --workers=1
```

**Comment by Skn0tt** [comment]
I see. I'm pretty sure there's something in your project that's turning on headed execution. Could you provide me with a minimal repro that shows what's going on, or maybe post your `playwright.config.ts` file?

**Comment by BoisAuLit** [comment]
Hi @Skn0tt , I finally found the root cause of this:

![Image](https://github.com/user-attachments/assets/0a40f96f-cee8-424e-ae77-9d5e2750bf75)

So recently I added the headless: false at the location shown in the screenshot above in the playwright.config.ts file. Once I remove the "headless: false" part, there's no separate window on top of the UI mode window anymore, everything runs smoothly in the embedded windows of UI mode.
