### ISSUE TITLE
[Bug]: WebKit tests significantly slower when using forms

### ISSUE THREAD

**Issue by DrMueller** [microsoft/playwright#33857]
### Version

1.49.0

### Steps to reproduce

steps:
1. Clone the repository from https://github.com/DrMueller/PlayWrightNetPerformance.
2. Run the `Create_Individual ` test with 50 iterations.
3. Observe the difference in execution time between Chromium and Webkit.

![Image](https://github.com/user-attachments/assets/b7581e0d-0551-4431-b62a-735adcf5844e)

I’ve also experimented with other tests, such as loading weather data from the Blazor example app. However, in these tests, no significant performance discrepancies were observed. It appears that using forms has a notable performance impact on Webkit, but this is just my assumption, as Blazor might also have an impact.

### Expected behavior

- Webkit tests using forms have roughly the same performance as with Firefox and Chromium

### Actual behavior

- Webkit test being around 2 (sometimes about 5) times slower than Chromium and Firefox

### Additional context

The PlayWright repository appears to have similar issues, as noted in [this GitHub issue](https://github.com/microsoft/playwright/issues/18119). In my case, videos are not executed anyway (as I'm not configuring a video path), but I’ve added the following code to my tests (see the reproduction repository):

```csharp
if (browserToTest == BrowserToTest.Webkit)
{
    await context.Tracing.StartAsync(new TracingStartOptions
    {
        Screenshots = true,
        Snapshots = true,
        Sources = true
    });
}
```

This adjustment improves test stability slightly, but the underlying problem still persists.

### Environment

```Text
- Operating System: Windows 11 Pro
- CPU: 12th Gen Intel(R) Core(TM) i7-1270P   2.20 GHz
- Browser: [All, Chromium , WebKit]
- .NET Version (TFM): [net9.0]
```

**Comment by Skn0tt** [comment]
Hi! Webkit on Windows is expected to be slower than chromium, yeah. That's a known issue, and I don't think we can do anything about it. To rule out that it's Blazor, could you try reproducing this just with plain HTML and CSS?

**Comment by DrMueller** [comment]
> Hi! Webkit on Windows is expected to be slower than chromium, yeah. That's a known issue, and I don't think we can do anything about it. To rule out that it's Blazor, could you try reproducing this just with plain HTML and CSS?

Hi Simon, thank you for the feedback. Do you think if generally someone is working on the topic? Or would you expect to the integration getting better?  I guess it doesn't make too much sense to investigate further in regard of Blazor if that's a known issue?

**Comment by Skn0tt** [comment]
There's no upcoming Webkit for windows changes we're aware of that should make this faster. If you can narrow this slow page down to a small HTML file, then we can look at working with the Webkit folks to speed up that specific problem. Blazor adds too much noise to that, so any repro would need to be pure HTML.

**Comment by YesCT** [comment]
> That's a known issue 

What would be a good source of truth to reference for this known issue? Is there a docs page somewhere?
