### ISSUE TITLE
[Bug]: v1.49.0 Playwright downloads wrong chrome browser version on macOS agent in Azure DO

### ISSUE THREAD

**Issue by sivanov-ss** [microsoft/playwright#33851]
### Version

v1.49.0

### Steps to reproduce

When `pnpm playwright install --with-deps chromium webkit` is being called on `vmImage: macOS-latest`, the logs are showing downloading process being stuck at this step:

```
.../node_modules/puppeteer postinstall: chrome-headless-shell (121.0.6167.85) downloaded to /Users/runner/.cache/puppeteer/chrome-headless-shell/mac-121.0.6167.85
.../node_modules/puppeteer postinstall: Chrome (121.0.6167.85) downloaded to /Users/runner/.cache/puppeteer/chrome/mac-121.0.6167.85
```

### Expected behavior

Chrome version that should be installed is Chromium 131.0.6778.33 as locally it installs this one
![Image](https://github.com/user-attachments/assets/4fad18c1-bb25-4e98-b1ef-f56ea80f2576)

### Actual behavior

An unsuccessful attempt to install wrong version which leads to the download process to get stuck until the pipeline reaches the timeout.

### Additional context

![Image](https://github.com/user-attachments/assets/b67475f4-98db-49c4-a3d1-6b1551a04bd5)
mac OS version is 15.1.1 (Beta)

![Image](https://github.com/user-attachments/assets/83992da6-b973-4afb-92bb-3466a3bf0baf)
mac OS version is 14.7.1 (latest)

### Environment

```shell
Agent name: 'Azure Pipelines 15'
Agent machine name: 'Mac-1733246513082'
Current agent version: '3.248.0'
Operating System
macOS
15.1.1
24B91
Runner Image
Image: macos-15
Version: 20241125.404
Included Software: https://github.com/actions/runner-images/blob/macos-15/20241125.404/images/macos/macos-15-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macos-15%2F20241125.404
Runner Image Provisioner
2.0.385.1+6d6c56aa16f1b9c7dd7935df5d63980397e44def
Current image version: '20241125.404'
Agent running as: 'runner'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: CmdLine (2.246.1)
Downloading task: NodeTool (0.247.1)
Downloading task: npmAuthenticate (0.247.1)
Downloading task: Cache (2.198.0)
Downloading task: Bash (3.246.1)
Downloading task: PublishTestResults (2.247.1)
Downloading task: PublishPipelineArtifact (1.242.0)
```

**Comment by Skn0tt** [comment]
Hi Stanislav! The download logs you posted are about Puppeteer. I don't think that's the relevant log lines - are you sure this is an issue with Playwright downloads?

**Comment by sivanov-ss** [comment]
> Hi Stanislav! The download logs you posted are about Puppeteer. I don't think that's the relevant log lines - are you sure this is an issue with Playwright downloads?

Hi Simon, 
What I know is that If I would have a way of setting what browser version I want to use in my tests, most probably I wouldn't have this problem. 

In my pipeline I have a task `pnpm install` -> which runs after installation `"postinstall": "pnpm playwright install --with-deps chromium webkit",` script that is in my package json.

**Comment by Skn0tt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
