### ISSUE TITLE
[Bug]: HTML reporter does not properly detect output folder clash

### ISSUE THREAD

**Issue by mattjennings** [microsoft/playwright#33863]
### Version

1.49.0

### Steps to reproduce

Run any Playwright project with the following reporter config:

```ts
const outputDir = './test-results'

export default defineConfig({
  /* ... */
  outputDir,
  reporter:   [  
    // does not log error, overwrites outputDir
    [
      'html',
      {
        open: 'never',
        outputFolder: outputDir
      },
    ],
    // logs error but does not overwrite outputDir - correctly outputs to outputDir/report
    [
      'html',
      {
        open: 'never',
        outputFolder: outputDir + '/report'
      },
    ],
  ]
})
```

Output (note error is from 2nd reporter, not 1st):

```bash
npx playwright test

Running 2 tests using 2 workers

Configuration Error: HTML reporter output folder clashes with the tests output folder:

    html reporter folder: /Users/mattjennings/tmp/html-reporter/test-results/report
    test results folder: /Users/mattjennings/tmp/html-reporter/test-results

HTML reporter will clear its output directory prior to being generated, which will lead to the artifact loss.
  2 passed (1.0s)

To open last HTML report run:

  npx playwright show-report test-results


To open last HTML report run:

  npx playwright show-report test-results/report
```

### Expected behavior

First reporter should log the error because it does overwrite the output folder. Second reporter should not log the error because it does not overwrite the output folder.

### Actual behavior

First reporter does not log error and overwrites output folder. Second reporter does log error but does not overwrite output folder.

### Environment

```shell
System:
    OS: macOS 15.1.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.32 GB / 32.00 GB
  Binaries:
    Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
    pnpm: 8.12.0 - /opt/homebrew/bin/pnpm
    bun: 1.0.0 - ~/.bun/bin/bun
  IDEs:
    VSCode: 1.95.3 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.49.0 => 1.49.0
```

**Comment by Skn0tt** [comment]
Outputting to nested folders is not supported, I don't think there's a bug here. If you need the HTML reports to be nested, do `mv report-a report-b/report-a` after running the test.

**Comment by reyrodrigez** [comment]
hey @Skn0tt is the restriction on outputting to nested folders documented somewhere? I couldn't find any trace apart of the configuration error on the runtime. Maybe adding a note to the reporter docs would help avoiding the issue. Thanks
