### ISSUE TITLE
[Bug]: Sharding doesn't appear to be working as per playwright documentation

### ISSUE THREAD

**Issue by Shaun-Regan** [microsoft/playwright#33871]
### Version

1.48.1

### Steps to reproduce

- Have multiple projects (we have 4 - chromium, Firefox, Edge and Chrome)
- In playwright.config.ts Set fullyParallel: false,
- In four different terminals set npx playwright test --shard=1/4, 2/4 etc
- Note that all 4 terminals start to execute the same test in the same .spec.ts file but in a different browser.

### Expected behavior

Playwright documentation states 

Without fullyParallel: Tests are split at the file level, so to balance the shards, it's important to keep your test files small and evenly sized.

I'm expecting each shard to own the test file assigned, to not share a test file (as per documentation) and execute all tests, in all browsers before moving onto the next test file assigned to the shard. 

### Actual behavior

Each shard executes the same test in the same test .spec.ts file at the same time but in a different browser.  With fullyParallel: false, I would expect a shard to own a test file and execute all tests in all browsers. 

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 3.78 GB / 15.61 GB
  Binaries:
    Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.95.3 - C:\Users\shaun.regan\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.48.1 => 1.48.1
```

**Comment by Skn0tt** [comment]
From what you're outlining, everything works as expected here. If you believe there's a bug, please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
