### ISSUE TITLE
[Bug]: context.newPage() is slow

### ISSUE THREAD

**Issue by stevendarby** [microsoft/playwright#33877]
### Version

1.49.0

### Steps to reproduce

[tests.zip](https://github.com/user-attachments/files/18026263/tests.zip)
`npm install`
`npx playwright install --with-deps`
`npx playwright test`
Note the times reported by the test.

### Expected behavior

`await context.newPage()` should be fast. I don't know whether this is really a fair comparison, but opening a new tab on Chrome is almost instant.

### Actual behavior

`await context.newPage()` is slow.

Here's the output of running the attached tests 3 times on my machine.

```
Running 1 test using 1 worker
[chromium] › example.spec.ts:3:5 › newPage
Page 1: 4.831s
Page 2: 4.192s
Page 3: 4.230s
```
```
Running 1 test using 1 worker
[chromium] › example.spec.ts:3:5 › newPage
Page 1: 6.853s
Page 2: 5.735s
Page 3: 4.943s
  Slow test file: [chromium] › example.spec.ts (17.6s)
  Consider splitting slow test files to speed up parallel execution
```

```
Running 1 test using 1 worker
[chromium] › example.spec.ts:3:5 › newPage
Page 1: 6.821s
Page 2: 4.591s
Page 3: 3.078s
```

### Additional context

`await context.newPage()` is slower on 1.49.0 with  chromium, and tbh was already slow before that.

In our real test project, our setup involves logging in with multiple users and storing the state for use in tests later. Each login is done in a new context; creating the context is quick but creating the page is very slow. 4+ seconds for 40 users really adds up.

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12800H
    Memory: 9.77 GB / 63.68 GB
  Binaries:
    Node: 18.20.5 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.95.3 - C:\Users\steven.darby\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: 1.49.0 => 1.49.0
    playwright: 1.49.0 => 1.49.0
```

**Comment by Skn0tt** [comment]
Thanks for providing the repro! The numbers i'm seeing on my macOS and Windows machines are in the millisecond range, so it looks like there's something special about your machine. I recommend you try reproduce it on a blank Windows VM. That should help you figure out what's the culprit. If that makes you find a bug in Playwright, please come back and file another issue with the findings! Happy to fix it then.

**Comment by stevendarby** [comment]
@Skn0tt oh interesting. This is an issue others at my workplace are having, so it might be some IT policy interfering. Will investigate.

**Comment by stevendarby** [comment]
Just an FYI for anyone else who might come across this, we did indeed pin it down to the Check Point endpoint security software we use at our workplace. Updating to the latest client roughly halved the times but it's still not in the millisecond range (which I could get on a clean VM). Hoping to raise the issue with Check Point to see if there's anything more they can do.

**Comment by Skn0tt** [comment]
Security software slowing down process startup times sounds familiar! Good to hear you've figured it out.
