### ISSUE TITLE
[Feature]: Custom Accordion Titles in HTML Reporter

### ISSUE THREAD

**Issue by mag09** [microsoft/playwright#33875]
## 📝 Description
Currently, the HTML reporter uses spec filenames as accordion titles in the test report. This approach leads to technical and sometimes unclear naming in the report UI. We'd like to have the ability to customize these titles to make reports more user-friendly and organized.

## 🔍 Current Behavior
The reporter automatically uses spec filenames as accordion titles:
example.spec.ts
tablebaseforblue.spec.ts
vsyakaya_vsyachina.spec.ts

## ✨ Desired Behavior
We want to be able to set custom, human-readable titles for each spec file or group of tests:
Basic Examples
Tables
Miscellaneous Tests

## 💡 Proposed Solution
A few possible approaches could be:

1. Via Configuration
// playwright.config.ts
export default defineConfig({
  reporter: [['html', {
    accordionTitles: {
      'example.spec.ts': 'Basic Examples',
      'tablebaseforblue.spec.ts': 'Tables',
      'vsyakaya_vsyachina.spec.ts': 'Miscellaneous Tests'
    }
  }]]
});

2. Via Test Annotations
// example.spec.ts
test.describe('Basic Examples', () => {
  // tests...
});

3. Via Special Comments (BEST)
// @accordion-title: Basic Examples
import { test } from '@playwright/test';

## 🤔 Questions
1. Is this feature already possible through existing configuration?
2. What would be the preferred way to implement this from the Playwright team's perspective?
3. Are there any technical limitations that might prevent this implementation?

## 🏷️ Labels
enhancement reporter documentation help wanted

---
Thank you for considering this feature request! Let me know if you need any additional information or clarification.

## 📋 Additional Context
This would be particularly useful for:
- Creating more organized and readable reports
- Better navigation in large test suites
- Improved communication with non-technical stakeholders
- Maintaining clear test organization without changing file names

**Comment by Skn0tt** [comment]
I think you're looking for either `test.describe` to give titles to tests within a suite, or you want to rename your spec files. Try renaming `example.spec.ts` to `Basic Examples.spec.ts`.

**Comment by mag09** [comment]
> I think you're looking for either `test.describe` to give titles to tests within a suite, or you want to rename your spec files. Try renaming `example.spec.ts` to `Basic Examples.spec.ts`.


Yes, I prefer not to change the filename, especially keeping it with spaces. The core concept here is that filenames serve an internal purpose, primarily for those working directly with the repository. 

Let me elaborate on this:

1. Internal Usage:
   - Filenames are meant for repository management
   - They follow specific naming conventions
   - They're used by QA and development teams

2. External Considerations:
   - Reports are often shared with various stakeholders
   - Many colleagues who view these reports aren't directly involved in testing
   - They don't need to see technical file naming details

3. User Experience:
   - Displaying filenames to non-technical users creates visual clutter
   - It can be confusing for stakeholders who aren't familiar with our naming conventions
   - Clean, relevant information is more valuable for external readers

In essence, we want to maintain a clear separation between technical infrastructure (like filenames) and user-facing content to ensure better readability and understanding for all stakeholders.
