### ISSUE TITLE
[Bug]: Uncaught exceptions from browser.Close()

### ISSUE THREAD

**Issue by jezusgyerekkorihaverja** [microsoft/playwright#33880]
### Version

1.49.0

### Steps to reproduce

1. Create a new node.js project, install playwright, open in VSCode
3. Create an example test:
 
```
import { test } from '@playwright/test';
import * as playwright from '@playwright/test';

test.describe('Sample test', () => {
   test('should open Google', async () => {
      const browser = await playwright.chromium.launch();
      const page = await browser.newPage();
      await page.goto('https://google.com');
      await browser.close();
   });
});
```

4. Check "Uncaught Exceptions" option in Run and Debug/Breakpoints settings in VSCode
5. Start a new Javascript Debug Terminal and execute npx playwright install
6. Notice the exception "Exception has occurred: TargetClosedError:Target page, context or browser has been closed"

### Expected behavior

No uncaught exceptions when closing the browser gracefully.

### Actual behavior

While debugging our Playwright tests in VSCode, we noticed they consistently end with TargetClosedError exceptions, even when the test results are successful. 

Initially, we suspected unresolved promises due to missing await statements, but the same issue occurs even with a minimal test case. Reproduction steps are provided below.

### Environment

```shell
System:
	Windows 10 Enterprise 19045.5131
	CPU: (6) 64bit
Binaries:
	Node: v20.12.2
	npm: 10.5.0
npm packages:
	@playwright/test: 1.49.0
```

**Comment by Skn0tt** [comment]
We can reproduce in Node 20, but not in Node 22. Looks like this is an upstream bug in Node.js. Try upgrading Node!

**Comment by kapouer** [comment]
I've added a test case to https://github.com/nodejs/node/issues/53732#issuecomment-2866009650
