### ISSUE TITLE
Route Interception Not Triggering for Specific URL with Query Parameters

### ISSUE THREAD

**Issue by AndriopoulosPanos** [microsoft/playwright#33884]
### Please do not submit this issue.

- [x] I understand

**Comment by AndriopoulosPanos** [comment]
I’m having trouble getting Playwright to intercept a specific GET request (redirect) that includes query parameters . Despite seeing the request logged by page.on('request', ...), the corresponding page.route handler never gets triggered for that URL.

I want to intercept and mock a response for this request:

http://<mydomain>.local/api/test-process/test-callback?code=example_code&state=example_state

I’ve tried various route patterns, including exact matches, wildcards but none of them seem to intercept. For example:

// Attempt 1: Exact match
await page.route('http://<mydomain>.local/api/test-process/test-callback?code=example_code&state=example_state', async (route) => {
  await route.fulfill({
 status: 200, 
body: 'mocked' });
});

// Attempt 2: Using wildcards
await page.route('**/tester/test?**', async (route) => {
  await route.fulfill({ status: 200, body: 'mocked' });
});

await page.route('**/tester/test**', async (route) => {
  await route.fulfill({ status: 200, body: 'mocked' });
});

In all cases, I can see the request in:

page.on('request', request => {
  console.log('Request made:', request.url());
});

The logged URL matches what I’m expecting. However, my route interception callbacks never fire.

What I’ve Tried:

    Matching with **/tester/test?**, and other increasingly broad patterns.
    Ensuring the route is registered before page.goto() or before the request triggers.
    Confirming the domain <mydomain>.local resolves correctly and is accessible.
    During test run i used fetch for the url and it got intercepted successfully.

Environment:

    Playwright version: 1.48.1
    Browser:  Chromium


Is there something I’m missing about how Playwright matches routes with query parameters? Or could this be a known issue or bug? Any guidance on properly intercepting this type of request would be greatly appreciated.

Thank you in advance for any help or insights!

**Comment by mio-moto** [comment]
What was the fix? I'm running into a similar issue and cannot make heads or tails when a route is caught or not.
