### ISSUE TITLE
[Bug]: Stuck if there is no ffmpeg in launchPersistentContext / electron

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#33899]
When recording a video with launchPersistentContext / electron with enabled video it hangs instead of throws an error that ffmpeg is missing.

Problem is that we wait for the page here: 

https://github.com/microsoft/playwright/blob/b3a82bef46e6f704312c441eea17a6bd737c1302/packages/playwright-core/src/server/browserContext.ts#L365

and receive an error here:

https://github.com/microsoft/playwright/blob/4696dd8682be4f644602a89594945e8b0f8f162c/packages/playwright-core/src/server/chromium/crPage.ts#L124

So we should wire

https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/page.ts#L205

together with when we wait for the error./

**Comment by sergiou87** [comment]
Hello @mxschmitt 👋 

FYI I ran into [this issue](https://github.com/microsoft/playwright/issues/26648) today with Playwright Test 1.58.2, and I had to run `npx playwright install ffmpeg` as you suggested to fix it, so maybe it regressed and this issue should be reopened? 🤔
