### ISSUE TITLE
[Bug]: Playwright fails to start with bun when Nodejs is not in path

### ISSUE THREAD

**Issue by Azeirah** [microsoft/playwright#33891]
### Version

1.1.31

## Summary

I'm trying to run playwright using the bun runtime. People are running into issues with [bun and playwright](https://github.com/oven-sh/bun/issues/8222)

I made a reproducible example to narrow down the exact issue. What I found by using Nix is that playwright fails to run well when nodejs is not in path, when executing with bun.

Is it possible there is an implicit dependency on nodejs somewhere within playwright?

## Reproducing

1. Make sure you have nix installed. You don't need NixOS. Just Nix. Run it in a vm or in a container if you don't want to pollute your environment. Preferably use the [determinate installer](https://determinate.systems/posts/determinate-nix-installer/)
2. Copy the flake.nix below
3. Start the shell `nix develop`
4. Confirm that `bun playwright test` hangs
5. Run `nix-shell -p nodejs_20`, in the same shell (do NOT exit the previous shell. Nix-shells stack)
6. Confirm that `bun playwright test` runs well

Here's a nix flake to reproduce the issue:

```nix
{
  description = "Bun.js development environment";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.05";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs {
          inherit system;
        };
      in
      {
        devShells.default = pkgs.mkShell {
          nativeBuildInputs = with pkgs; [
            playwright-driver.browsers
            playwright-test
          ];

          buildInputs = with pkgs; [
            bun
          ];

          PLAYWRIGHT_BROWSERS_PATH="${pkgs.playwright-driver.browsers}";
      });
}
```

## Some more detail

Is it possible that playwright implicitly depends on node somewhere? Here's the output of the PATH where it _does_ work:

Here's a nix flake to reproduce the issue:

```
PATH=/nix/store/wz8vix9vpcddikszq88aj1dy0bhcs1v9-playwright-test-1.47.0/bin:/nix/store/xjlvb8x7z3f5rxxswa3c6ghay74a58jm-patchelf-0.15.0/bin:/nix/store/3ix5h74n7ar9950vwzp4dxmil70pmx0k-gcc-wrapper-13.3.0/bin:/nix/store/xzfmarrq8x8s4ivpya24rrndqsq2ndiz-gcc-13.3.0/bin:/nix/store/26dy2y29fhissya64ygahwpidpvs3bm3-glibc-2.40-36-bin/bin:/nix/store/k48bha2fjqzarg52picsdfwlqx75aqbb-coreutils-9.5/bin:/nix/store/9bacph866qhmr2zfib1h49jixq5hhd01-binutils-wrapper-2.43.1/bin:/nix/store/va7kw1i822h95im4jacci19v0cqajfyf-binutils-2.43.1/bin:/nix/store/xy5raazymalxya0wjqwh5r63gxmxnv65-bun-1.1.31/bin:/nix/store/k48bha2fjqzarg52picsdfwlqx75aqbb-coreutils-9.5/bin:/nix/store/lfhmpajzgfmgl8xrdvp2r9hdi2rf17wy-findutils-4.10.0/bin:/nix/store/xrpvl6c1pyq7zazqnb41kgshmkr85da1-diffutils-3.10/bin:/nix/store/gvivnz7rb2gz1vy7d9mdxgzj9didz7w2-gnused-4.9/bin:/nix/store/14aswfz6pm8zvyyy927xzmi8x4rnvlc8-gnugrep-3.11/bin:/nix/store/45jb5s18799g8day8zjixrvknj4chp6r-gawk-5.3.1/bin:/nix/store/sdljgkhcmlflr785i4jffg1rvm294i1k-gnutar-1.35/bin:/nix/store/pg1n8f8zlwh4q4bsbnm9gwhx7cbix1m6-gzip-1.13/bin:/nix/store/y59bxw99pbld247dznzv352cqdhlybqi-bzip2-1.0.8-bin/bin:/nix/store/a08385589ajv3ahmp81nml9bh5dsi55n-gnumake-4.4.1/bin:/nix/store/0irlcqx2n3qm6b1pc9rsd2i8qpvcccaj-bash-5.2p37/bin:/nix/store/0knrdpnzi5s4igcvzw8yhkj8daq84a2v-patch-2.7.6/bin:/nix/store/g6rf9zyrz8hrgz4r7sd2hab3j1afxdkr-xz-5.6.3-bin/bin:/nix/store/83jpg0nha0gp1pggdvsk7zh6wn5lgm00-file-5.45/bin:/home/lb/.pyenv/shims:/home/lb/.pyenv/bin:/run/current-system/sw/bin:/run/wrappers/bin:/home/lb/.nix-profile/bin:/nix/profile/bin:/home/lb/.local/state/nix/profile/bin:/etc/profiles/per-user/lb/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/nix/store/2zihfr3bw3pbhlkkfdd3nba24spww6ai-nodejs-22.4.1/bin
```

If I manually remove the `/nix/store/2zihfr3bw3pbhlkkfdd3nba24spww6ai-nodejs-22.4.1/bin` at the end? Then it DOESN'T WORK.

Very odd.

### Expected behavior

I expect playwright to function as expected with bun

### Actual behavior

It hangs

### Additional context

[Related issue on the bun Github repository](https://github.com/oven-sh/bun/issues/8222)

### Environment

```shell
irrelevant. The nix environment provides a reproducible example
```

**Comment by Skn0tt** [comment]
Bun support is out of scope.

**Comment by Azeirah** [comment]
> Bun support is out of scope for Playwright.

Is playwright particularly tied to node and its runtime? Or is this likely incredibly difficult and time-consuming to fix?
