### ISSUE TITLE
Need to control the order of execution

### ISSUE THREAD

**Issue by Kartheeswari-git** [microsoft/playwright#33892]
### Version

1.49.0

### Steps to reproduce

I want to control the order of test execution in parallel mode. Here's the desired execution structure:

**Suite 1**  
**Suite 2**  
**Suite 3**

   **#WAIT** → Once the above three suites complete execution, proceed with the following:

**Suite 4**  
**Suite 5**  
**Suite 6**

**Requirement**:  
- **Suite 2** generates a significant number of chats.  
- After its execution, I need to verify the chat history in **Suite 5** and analyze the dashboard in **Suite 6**.  
- To ensure this dependency is respected, I need to execute **Suites 5 and 6** only after **Suites 1–3** are completed.  

### Expected behavior

How can I control the order of execution to meet this requirement?

### Actual behavior

If i mention the suites in groups in playwright.config.json, it executing all suites together

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz
    Memory: 5.93 GB / 19.74 GB
  Binaries:
    Node: 22.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.9.1 - ~\node_modules\.bin\npm.CMD
  IDEs:
    VSCode: 1.95.3 - C:\Users\Karthee\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.1.4 - C:\Windows\system32\bash.EXE
  npmPackages:
    @playwright/test: ^1.49.0 => 1.49.0
    playwright: ^1.49.0 => 1.49.0
```

**Comment by Skn0tt** [comment]
If your tests depend on data from one another, look at [Serial mode](https://playwright.dev/docs/test-retries#serial-mode) or putting it into one test with multiple [steps](https://playwright.dev/docs/api/class-test#test-step).
