### ISSUE TITLE
[Feature]: Native Mobile Application Testing for Android and ios in playwright.

### ISSUE THREAD

**Issue by OnlyKeval** [microsoft/playwright#33895]
### 🚀 Feature Request

Now a days and upcoming years there are lots of demand increasing for mobile app testing e2e like we doing with web now with playwright so any plans from **playwright official team** for launching in built **mobile application testing** soon or in 2025? 

### Example

We want feature should like appium in playwright. 

### Motivation

If this happens we have one stop solutions in market so personally I and all QA's wants playwright team will think and work for it. 

Also wants playwright think and work more in area of test cases running directly on cloud or remote machine.

**Comment by gjmargallo** [comment]
We need definitely this: we cannot call an automation framework e2e if it doesn't allow testing at the same time of native apps

**Comment by mxschmitt** [comment]
No plans as of today. Folding into https://github.com/microsoft/playwright/issues/27778

**Comment by VINOD-GOSWAMI** [comment]
hi playwright team any plans to have support for native ios app testing the last comment was a year back

**Comment by leor-mn** [comment]
We built it. 

Mobilewright ([mobilewright.dev](https://mobilewright.dev/)) is a native iOS/Android automation framework modeled directly on Playwright's API. Same locators, same auto-waiting, same assertion model:
tsimport { ios, expect } from 'mobilewright';

const device = await ios.launch({ bundleId: 'com.example.app' });
const { screen } = device;

await screen.getByRole('button', { name: 'Sign In' }).tap();
await expect(screen.getByText('Welcome back')).toBeVisible();

await device.close();
getByRole, getByLabel, getByText, getByTestId — all work on the native accessibility tree, not screenshots. mobilewright init, mobilewright doctor, HTML reporter, --grep, --retries — it's all there.
Supports UIKit, SwiftUI, React Native, Expo. iOS simulators, Android emulators, real devices. If you want real cloud devices, [mobile-use.com](https://mobile-use.com/) is the device cloud with native Mobilewright support.
Disclosure: I'm one of the authors.

**Comment by matt-architect** [comment]
Does https://mobilewright.dev/ support .NET MAUI apps?

**Comment by omnarayan** [comment]
For anyone still looking: it's possible today without changing Playwright, by making the device a page. DeviceDeck (free, Apache-2.0; I'm the author) serves an iOS Simulator or Android emulator in the browser and mirrors the app's accessibility tree
  into the DOM — accessibility ids become `data-testid`, element types become ARIA roles — so a normal Playwright test drives the native app:

  ```ts
  await page.goto(`http://127.0.0.1:8787/device/${udid}?app=com.example.app`);
  await page.getByRole('button', { name: 'Sign In' }).click();
  ```

  It's the real `@playwright/test` runner, report and CI, not a lookalike API. Limits: macOS host, simulators and emulators only (not physical phones).

  https://github.com/devicelab-dev/DeviceDeck
