### ISSUE TITLE
Screenshot failed

### ISSUE THREAD

**Issue by Mortsadok** [microsoft/playwright#33905]
### Please do not submit this issue.

- [x] I understand

**Comment by Mortsadok** [comment]
![Image](https://github.com/user-attachments/assets/bdee7aa1-2d39-4095-b6d1-d7e88b27328e)

Screenshots fail to capture when a test fails, but this issue occurs only in the CI environment.

**Playwright config file:
screenshot: 'only-on-failure'**

Any suggestions?

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
