### ISSUE TITLE
[Question] Github Reports eslint-plugin-internal-playwright as malware

### ISSUE THREAD

**Issue by Vinyzu** [microsoft/playwright#33908]
Github Advisories reports (the npm version of) `eslint-plugin-internal-playwright` as [malicious](https://github.com/advisories/GHSA-ggxx-9q8p-fhj8).
This causes npm to declare this package as having a "critical vulnerability".

This also affects the file installment of `eslint-plugin-internal-playwright` in playwrights [package.json](https://github.com/microsoft/playwright/blob/dfa24462dbad83c404dca9443e551b8083a4d8b1/package.json#L90).

Can this be resolved? Is the Advisory correct?

**Comment by yury-s** [comment]
Does it break anything for you?

This is a package internal to playwright, which is loaded from a file and has never been published to `npmjs`.  The audit violation seems like a bug in `npm audit` that confuses the internal package with the malicious one published to `https://npmjs.com/` by someone.

**Comment by Vinyzu** [comment]
No, i dont think this breaks anything.
I think your theory is correct.

I was just wondering about if this was an issue/compromise and just think that it isnt a nice look ^^
