### ISSUE TITLE
[Bug]: beforeAll/afterAll run more than once per worker with default mode

### ISSUE THREAD

**Issue by csvtuda** [microsoft/playwright#33915]
### Version

1.49.0

### Steps to reproduce

To my understanding, when a test file is run in parallel mode and using several workers:
- each worker will run top-level beforeAll/afterAll hooks in the file once
- new workers will be created if a test fails, running the hooks again

This works as expected when no further describe groups are introduced which are configured with `default` mode.

But as soon as such groups are added, the top-level hooks are run more than once per worker, _even if no test fails_.

---
 
1. Clone my repo at https://github.com/csvtuda/playwright-beforeall-bug
2. `npm install`
3. `npx playwright test --workers 3 --reporter line | grep "LOG"`

The problematic code in question is the following:

```ts
import { test } from "@playwright/test";
import { setTimeout } from "timers/promises";

test.describe.configure({mode: 'parallel'});

test.beforeAll(({}, testInfo) => { console.log(`LOG before all @ worker ${testInfo.workerIndex}`); });

test.describe("group 1", () => {
    test("Test 1", async ({}, testInfo) => { await setTimeout(100); console.log(`LOG     Test 1 @ worker ${testInfo.workerIndex}`); });
    test("Test 2", async ({}, testInfo) => { await setTimeout(100); console.log(`LOG     Test 2 @ worker ${testInfo.workerIndex}`); });
    test("Test 3", async ({}, testInfo) => { await setTimeout(100); console.log(`LOG     Test 3 @ worker ${testInfo.workerIndex}`); });
});

test.describe("group 2", () => {    
    test.describe.configure({ mode: 'default' });
    test("Test 4", async ({}, testInfo) => { await setTimeout(100); console.log(`LOG     Test 4 @ worker ${testInfo.workerIndex}`); });
    test("Test 5", async ({}, testInfo) => { await setTimeout(100); console.log(`LOG     Test 5 @ worker ${testInfo.workerIndex}`); });
    test("Test 6", async ({}, testInfo) => { await setTimeout(100); console.log(`LOG     Test 6 @ worker ${testInfo.workerIndex}`); });
});

test.describe("group 3", () => {
    test.describe.configure({ mode: 'default' });
    test("Test 7", async ({}, testInfo) => { await setTimeout(100); console.log(`LOG     Test 7 @ worker ${testInfo.workerIndex}`); });
    test("Test 8", async ({}, testInfo) => { await setTimeout(100); console.log(`LOG     Test 8 @ worker ${testInfo.workerIndex}`); });
    test("Test 9", async ({}, testInfo) => { await setTimeout(100); console.log(`LOG     Test 9 @ worker ${testInfo.workerIndex}`); });
});
```

### Expected behavior

The message `LOG before all @ worker X` should _at most_ appear once for each worker:

```console
$ npx playwright test --workers 3 --reporter line | grep "LOG"
LOG before all @ worker 2
LOG before all @ worker 1
LOG     Test 7 @ worker 2
LOG     Test 4 @ worker 1
LOG     Test 8 @ worker 2
LOG     Test 5 @ worker 1
LOG     Test 9 @ worker 2
LOG     Test 6 @ worker 1
LOG     Test 1 @ worker 2
LOG     Test 2 @ worker 1
LOG     Test 3 @ worker 2
```

### Actual behavior

The message appears more than once per worker:

```console
$ npx playwright test --workers 3 --reporter line | grep "LOG"
LOG before all @ worker 2
LOG before all @ worker 1
LOG     Test 7 @ worker 2
LOG     Test 4 @ worker 1
LOG     Test 8 @ worker 2
LOG     Test 5 @ worker 1
LOG     Test 9 @ worker 2
LOG before all @ worker 2
LOG     Test 6 @ worker 1
LOG before all @ worker 1
LOG     Test 1 @ worker 2
LOG before all @ worker 2
LOG     Test 2 @ worker 1
LOG     Test 3 @ worker 2
```

### Additional context

As mentioned, as soon as the `test.describe.configure({ mode: 'default' });` lines are commented out, everything works as expected again:

```console
$ npx playwright test --workers 3 --reporter line | grep "LOG"
LOG before all @ worker 1
LOG before all @ worker 2
LOG     Test 1 @ worker 1
LOG     Test 4 @ worker 2
LOG     Test 2 @ worker 1
LOG before all @ worker 0
LOG     Test 5 @ worker 2
LOG     Test 3 @ worker 1
LOG     Test 7 @ worker 0
LOG     Test 6 @ worker 2
LOG     Test 8 @ worker 0
LOG     Test 9 @ worker 0
```

---

Am I missing something? I've tried looking through the open and closed issues, but almost all of them were addressing the "unexpected" behaviour that beforeAll/afterAll can run more than once with multiple workers.

The [documentation](https://playwright.dev/docs/test-parallel#parallelize-tests-in-a-single-file) also states the following:

> Note that parallel tests are executed in separate worker processes and cannot share any state or global variables. Each test executes all relevant hooks just for itself, including beforeAll and afterAll.

Does this mean that _each test_ that is run in parallel mode will trigger a beforeAll/afterAll on its own, regardless of whether the worker triggered one already? If yes, then why does the run without the `default` configures only run the hook three times, although the file is in `parallel` mode?

### Environment

```console
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 5.63 GB / 15.73 GB
  Binaries:
    Node: 22.11.0 - C:\Program Files\nodejs\v22.11.0\node.EXE
    npm: 10.8.1 - C:\Program Files\nodejs\v22.11.0\npm.CMD
  IDEs:
    VSCode: 1.95.3 - C:\Users\csvtuda\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.2.26 - C:\Program Files\Git\usr\bin\bash.EXE
  npmPackages:
    @playwright/test: ^1.49.0 => 1.49.0
```

**Comment by yury-s** [comment]
> Does this mean that each test that is run in parallel mode will trigger a beforeAll/afterAll on its own, regardless of whether the worker triggered one already?

In general yes. Sometimes Playwright will optimize this out, but it is not always smart enough to apply the optimization. It may run `beforeAll`, `test 1`, `afterAll` and then `beforeAll`, `test 2`, `afterAll` in the same worker or  it can run`beforeAll`, `test 1`, `test 2`, `afterAll` both sequences satisfy the description in the docs.

> If yes, then why does the run without the default configures only run the hook three times, although the file is in parallel mode?

This is a specifics of the current implementation and may change in the future.

Closing as this is not an issue from the correctness stand point. Playwright may do better job optimizing redundant `beforeAll/afterAll` hooks for parallel tests ending up on the same worker instance but there is no ongoing work on that.

**Comment by azad-resolver** [comment]
> * new workers will be created if a test fails, running the hooks again

I just encountered this and to my knowledge that's not expected behaviour. Where is that documented?

Edit: Ah nvm I finally [found it](https://playwright.dev/docs/test-retries#failures)! That is very odd behaviour (why would `beforeAll()` and `afterAll()` have to run again after a test failure?), I was almost certain this was a bug.
