### ISSUE TITLE
[Feature]: PLAYWRIGHT_JUNIT_SUITE_NAME option support on config file

### ISSUE THREAD

**Issue by dbwodlf3** [microsoft/playwright#33910]
### 🚀 Feature Request

Plz support PLAYWRIGHT_JUNIT_SUITE_NAME option on playwright configuration file.
https://github.com/microsoft/playwright/blob/dfa24462dbad83c404dca9443e551b8083a4d8b1/packages/playwright/src/reporters/junit.ts#L81

This is suported only via env variable.

### Example

export default defineConfig({
  reporter: [
    ['html', { outputFolder: reportDirectory }],
    ['junit', { outputFile: join(reportDirectory, 'modeler-client.dt.xml'), suiteName: 'Modeler Client Test' }],
  ],
})

### Motivation

I am writing some program report to confluence based on junit xml

**Comment by yury-s** [comment]
As a workaround you can do  process.env[`PLAYWRIGHT_JUNIT_SUITE_NAME`]='foo'; right in the config.

**Comment by dbwodlf3** [comment]
okay.
