### ISSUE TITLE
[Feature]: Assign workers to subsets of projects

### ISSUE THREAD

**Issue by Zanzibarbarian** [microsoft/playwright#33918]
### 🚀 Feature Request

I'm working with a staging env and a prod env, both of which we are testing against Chrome, FF, and Safari. Our system requires only one instance of a given user being logged in at a time.

What I would like to do is assign one worker in CI to the staging env and one worker to the prod env, to avoid the overlapping users concern. Is there another way to accomplish this right now?

### Example

Something like:
```
{ 
  name: 'staging',
      {
        name: 'chromium',
        use: { ...devices['Desktop Chrome'] },
        dependencies: ['setup'],
      },

      {
        name: 'firefox',
        use: { ...devices['Desktop Firefox'] },
        dependencies: ['setup'],
      },

      {
        name: 'webkit',
        use: { ...devices['Desktop Safari'] },
        dependencies: ['setup'],
      },
   workers: 1,
},

{
  name: 'prod',
...
```

### Motivation

Right now I don't see another way to do this. I could also see this being useful if you have categories of devices, e.g. Android and iOS.

**Comment by yury-s** [comment]
Folding this into https://github.com/microsoft/playwright/issues/21484, another related issue is https://github.com/microsoft/playwright/issues/21970. Please upvote one of those instead.
