### ISSUE TITLE
[Docs]: Mention the need to run playwright install as the same user that will use playwright

### ISSUE THREAD

**Issue by mattalbr** [microsoft/playwright#33920]
### Page(s)

https://playwright.dev/docs/docker#build-your-own-image

### Description

This was tricky to debug and unfortunately https://github.com/microsoft/playwright/issues/4033 is closed so I can't comment my fix for others who hit the same snag.

When building a docker container, it's not uncommon to do a lot of setup as root before switching to another user to actually run the application code. When I was installing playwright as root and then running my tests as `testworker`, playwright was looking in the `testworker`'s home directory and saying playwright was not installed, when it had actually be installed under root.

Would be nice to mention this in the docs, or at the very least in that github issue others are likely to find.

**Comment by yury-s** [comment]
Guiding users on how to build custom Docker images and deal with linux file permissions is out of scope for Playwright. It's a good idea to run npm commands under the same user which will run the tests. For simplicity our images and examples use `root` by default.
