### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Pavankishorek** [microsoft/playwright#33924]
Hi team,

Playwright - 1.46.0

We are facing a issue related to the application fitting to the browser responsiveness.

We are trying to invoke the browser with the default size and launch the URL and dynamically fetch the execution system resolution and append it on playwright to fit to screen. But, in this case, application is not getting fit to the browser size in both the minimized and maximized views.

![Image](https://github.com/user-attachments/assets/6f4ef1af-fc11-4dfd-bd77-e8700c24a51a)

Please reach out to us for further details to check and resolve this issue.

Requesting the GitHub to resolve this as quick as possible.

Thanks.

**Comment by yury-s** [comment]
Here is the doc explaining how to emulate viewport in Playwright: https://playwright.dev/docs/emulation#viewport. You should set desired size beforehand, another option would be [setViewPort](https://playwright.dev/docs/api/class-page#page-set-viewport-size) which can change it dynamically. If it still doesn't work, please file a new issue following our bug template and provide a reproduction that we can run locally to reproduce it.
