### ISSUE TITLE
Playwright auto wait feature causing delays

### ISSUE THREAD

**Issue by Abinayadevi16** [microsoft/playwright#33933]
### Version

1.46.0

### Steps to reproduce

The existing implementation of our code uses try and except blocks to handle multiple locators when a common locator fails. However, this approach slows down execution due to the timeout incurred before switching to the except block.

Is there any way to disable playwrights auto wait feature and have a global timeout parameter where we can set our timeout and enable explicit timeouts wherever required 

### Expected behavior

Try block should not wait for more time to execute and locate the element before moving to catch block for alternate locator 

### Actual behavior

Try block taking more time and slowing down execution

### Environment

```shell
1.46.0
```

**Comment by yury-s** [comment]
> The existing implementation of our code uses try and except blocks to handle multiple locators when a common locator fails. However, this approach slows down execution due to the timeout incurred before switching to the except block.

Please share a sample code and point out which part you want to speed up, ideally it'd be something that we could run locally.

> Is there any way to disable playwrights auto wait feature and have a global timeout parameter where we can set our timeout and enable explicit timeouts wherever required

There is no way to completely disable auto-wait feature but you can adjust individual timeouts, such as [actionTimeout](https://playwright.dev/docs/api/class-testoptions#test-options-action-timeout), see [this doc](https://playwright.dev/docs/test-timeouts) for more details about different timeouts.

**Comment by saeed6944** [comment]
> ### Version
> 
> 1.46.0
> 
> ### Steps to reproduce
> 
> The existing implementation of our code uses try and except blocks to handle multiple locators when a common locator fails. However, this approach slows down execution due to the timeout incurred before switching to the except block.
> 
> Is there any way to disable playwrights auto wait feature and have a global timeout parameter where we can set our timeout and enable explicit timeouts wherever required 
> 
> ### Expected behavior
> 
> Try block should not wait for more time to execute and locate the element before moving to catch block for alternate locator 
> 
> ### Actual behavior
> 
> Try block taking more time and slowing down execution
> 
> ### Additional context
> 
> _No response_
> 
> ### Environment
> 
> ```shell
> 1.46.0
> ```

**Comment by Abinayadevi16** [comment]
@yury-s , The doc you have mentioned is for node.js , I need to implement timeout using python. Any reference doc to look for ?
def method(self, var1, var2):
       
  
        try:
            try:
               # locator to identify element
                locator = 
            except Exception as exception:
              # fallback locator
               alternate_locator = 
            assert_verify.report(f"Entered value '{value}'")

        except Exception as exception:
            assert_verify.assert_fail(str(exception))
   Here if the element cannot be identified with the locator in the try block it auto waits and then only it moves to except block to check for alternate locator which is causing delays . Any global timeout can we set to avoid such delays ?

**Comment by Abinayadevi16** [comment]
Does adding timeout variable to launch method of Browser type class helps ?

**Comment by Abinayadevi16** [comment]
How to change the default timeout ? The below implementation didnt help
browser_context.set_default_timeout(timeout = 0)

**Comment by yury-s** [comment]
In python, you can set per context [timeout](https://playwright.dev/python/docs/api/class-browsercontext#browser-context-set-default-timeout)  and global [assertion timeouts](https://playwright.dev/python/docs/test-assertions). Setting timeout to `0` means no timeout, that's why the result is not what you expect. If you want to just query presence of an element without performing any actions and waiting for it, you should use methods like [`is_visible`](https://playwright.dev/python/docs/api/class-locator#locator-is-visible).
