### ISSUE TITLE
[Bug]: Script fails with Error

### ISSUE THREAD

**Issue by shastrisubramaniam** [microsoft/playwright#33932]
### Version

1.49.1

### Steps to reproduce

Error: file data stream has unexpected number of bytes

Error: end of central directory record signature not found when running in Chromium

### Expected behavior

No error and scripts should Pass.

### Actual behavior

Error: file data stream has unexpected number of bytes

    Error: end of central directory record signature not found![Image](https://github.com/user-attachments/assets/c283cb5a-6e3b-45d6-a540-8a6d4f5fe4b5)

### Environment

```shell
System:
    OS: macOS 15.1.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 745.02 MB / 32.00 GB
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.11.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
  Languages:
    Bash: 5.2.37 - /opt/homebrew/bin/bash
```

**Comment by yury-s** [comment]
Sounds like a problem with a zip file, could be caused by some concurrent access to the same file. We need a reproduction example to act on this, please share code that we could run locally and see the issue. Unfortunately we can't do anything based on provided information.

**Comment by shastrisubramaniam** [comment]
I am not sure if the below will suffice : 

**Limited_auth_setup.ts** 

import { expect } from '@playwright/test';
import path from 'path';
import {Environment} from './utils/Environment';
import { test } from './utils/customFixtures';
import 'dotenv/config';
import {VerifyPatientPage} from "./utils/Verify_Patient"

test('authenticate', async ({token,uniquelink,page}) => {
  // Perform authentication steps. Replace these actions with your own.

  const token_response = await token.getLimitedAuthAccessToken();
  expect(token_response.ok()).toBeTruthy();
  const body = await token_response.json();
  process.env.limited_auth_token = body.access_token;
  const ul_response = await uniquelink.getUniqueLink(process.env.limited_auth_token);
  const uniquelinkBody = await ul_response.json();
  expect(ul_response.ok()).toBeTruthy();
  await page.goto(Environment.getSelfRegistrationUrl() + uniquelinkBody.id + "/f?p=15200700");
  let mypage = new VerifyPatientPage(page);
  mypage.verifyPatient();
});

**Verify_Patient.ts**

import { expect, type Locator, type Page } from '@playwright/test';
import {Environment} from './Environment';
import dotenv from 'dotenv';
dotenv.config();
let data:any;
async function loadJSON(path: string): Promise<any> {
  const {default:jsonObject} = await import(path, { assert: { type: "json" } });
  return jsonObject;
}
export class VerifyPatientPage {
  readonly page: Page;
  readonly verifyPatientHeader: Locator;
  readonly firstName: Locator;
  readonly lastName: Locator;
  readonly dateofBirth: Locator;
  readonly getStartedButton: Locator;


  constructor(page: Page) {
    this.page = page;
    this.verifyPatientHeader = page.getByText('Sign In');
    this.firstName = page.getByLabel('First Name');
    this.lastName = page.getByLabel('Last Name');
    this.dateofBirth = page.getByPlaceholder('MM/DD/YYYY');
    this.getStartedButton = page.getByRole('button', { name: 'Get Started' });
  }

  async verifyPatient() {
    const testdatapath = Environment.getTestDataPath() + 'ValidExistingPatient_UpdateProfile.json';
    data = await loadJSON(testdatapath);
    await expect(this.verifyPatientHeader).toBeVisible();
    await this.firstName.fill(data.firstName);
    await this.lastName.fill(data.lastName);
    await this.dateofBirth.fill(data.uidateOfBirth);
    await this.getStartedButton.click();
  }
}

**apiHelpers.ts**

import { APIRequestContext } from '@playwright/test';
import {Environment} from './Environment'
import dotenv from 'dotenv';
dotenv.config();
let data:any;
async function loadJSON(path: string): Promise<any> {
  const {default:jsonObject} = await import(path, { assert: { type: "json" } });
  return jsonObject;
}
export class accessToken {
  constructor(private request: APIRequestContext) {}
  async getLimitedAuthAccessToken()
      {
        const testdatapath = Environment.getTestDataPath() + 'ValidExistingPatient_UpdateProfile.json';
        loadJSON(testdatapath);  
        return this.request.post(Environment.getPAS_APIIdentityUrl(),{form:{
            grant_type: "password",
            username: Environment.getPAS_APIUser(),
            password: Environment.getPAS_APIPassword(),
            scope: Environment.getPAS_APIScope()},headers:{
              Authorization: Environment.getPAS_APIClientAuth()
            }});
      };
  async getFullAuthAccessToken ()
      {
        return this.request.post(Environment.getPP_APIIdentityUrl(),{headers:{
          Authorization: Environment.getPP_APIClientAuth()
        },form:({
          grant_type: "password",
          username: Environment.getPP_APIUser(),
          password: Environment.getPP_APIPassword(),
          scope: Environment.getPP_APIScope()})}); //sets to application/x-www-form-urlencoded
      };
    }
      export class uniqueLink {
        constructor(private request: APIRequestContext) {}
      async getUniqueLink (request:any)
        {
          const testdatapath = Environment.getTestDataPath() + 'ValidExistingPatient_UpdateProfile.json';
          data = await loadJSON(testdatapath);
          console.log(data);
            return this.request.post(Environment.getApiUlEndpoint(),{data: {
              firstName: data.firstName,
              lastName: data.lastName,
              patientId: data.patientId,
              proxyId: data.proxyId,
              appointmentId: data.appointmentId,
              application: data.application,
              dob: data.apidateOfBirth,
            },headers: {
              Authorization: "Bearer " + process.env.limited_auth_token,
            } //sets to application/x-www-form-urlencoded
            });
        }
      }

**apiHelper.ts**

import { test as baseTest } from '@playwright/test';
import * as apiHelpers from './apiHelpers';

export const test = baseTest.extend<{ token: apiHelpers.accessToken;
  uniquelink: apiHelpers.uniqueLink;
 }>({
  token: async ({request},use) => {
    await use(new apiHelpers.accessToken(request));
  },
  uniquelink: async ({request},use) => {
    await use(new apiHelpers.uniqueLink(request));
  },
});

**playwright.config.ts**
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  timeout: 120_000,
  fullyParallel: true,
  use: {
    // Capture screenshot after each test failure.
    screenshot: 'only-on-failure',
  },
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Configure projects for major browsers */
  projects: [
    { name: 'Full Auth Setup', testDir :'./',testMatch: 'full_auth.setup.ts'},
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'],
        storageState: 'playwright/.auth/user.json',
      },
      dependencies: ['Full Auth Setup'],
    },
    { name: 'Limited Auth Setup', testDir :'./',testMatch: 'limited_auth.setup.ts'},
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'],
        storageState: 'playwright/.auth/user.json',
        screenshot: 'only-on-failure'
      },
      dependencies: ['Full Auth Setup'],
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] ,
        storageState: 'playwright/.auth/user.json',
      },
      dependencies: ['Full Auth Setup'],
    },
  ],
});

I run : environment=eod1 npx playwright test --project 'Limited Auth Setup' --ui

**Comment by shastrisubramaniam** [comment]
So it works if I don't use a Page Object. But it fails when I use a Page Object.

**Comment by shastrisubramaniam** [comment]
I was able to resolve it by moving the test data for the Page Object to the calling test.
