### ISSUE TITLE
[Feature]: Click position should accept `right` and `bottom` values

### ISSUE THREAD

**Issue by Bilge** [microsoft/playwright#33944]
### 🚀 Feature Request

If I want to click the right-hand edge of an element, I must somehow first measure the size of the element being clicked. This is highly impractical and asymmetric in terms of difficulty when compared to clicking the left-hand edge. That is, to click the left-hand edge I merely need to do `click({position: {x: 0}})` (no measuring involved).

### Example

`locator().click({position: {right: 0}})`

### Motivation

Make it easier to click on different parts of an element.

**Comment by saeed6944** [comment]
👍

**Comment by saeed6944** [comment]
> ### 🚀 Feature Request
> 
> If I want to click the right-hand edge of an element, I must somehow first measure the size of the element being clicked. This is highly impractical and asymmetric in terms of difficulty when compared to clicking the left-hand edge. That is, to click the left-hand edge I merely need to do `click({position: {x: 0}})` (no measuring involved).
> 
> ### Example
> 
> `locator().click({position: {right: 0}})`
> 
> ### Motivation
> 
> Make it easier to click on different parts of an element.

**Comment by Bilge** [comment]
Aside, it seems to me specifying the click position does not work at all: no matter what is specified, it always tries to click in the center.

**Comment by saeed6944** [comment]
> ### 🚀 Feature Request
> 
> If I want to click the right-hand edge of an element, I must somehow first measure the size of the element being clicked. This is highly impractical and asymmetric in terms of difficulty when compared to clicking the left-hand edge. That is, to click the left-hand edge I merely need to do `click({position: {x: 0}})` (no measuring involved).
> 
> ### Example
> 
> `locator().click({position: {right: 0}})`
> 
> ### Motivation
> 
> Make it easier to click on different parts of an element.

**Comment by saeed6944** [comment]
> ### 🚀 Feature Request
> 
> If I want to click the right-hand edge of an element, I must somehow first measure the size of the element being clicked. This is highly impractical and asymmetric in terms of difficulty when compared to clicking the left-hand edge. That is, to click the left-hand edge I merely need to do `click({position: {x: 0}})` (no measuring involved).
> 
> ### Example
> 
> `locator().click({position: {right: 0}})`
> 
> ### Motivation
> 
> Make it easier to click on different parts of an element.

**Comment by yury-s** [comment]
You can use [`boundingBox`](https://playwright.dev/docs/api/class-locator#locator-bounding-box) to get the element's size and use it to compute a click point you like. This is not the most convenient way but the use case is also very niche, which is why we only provide the most flexible way to specify click point coordinates. I'm going to close this request as there are no plans to change this API.

> Aside, it seems to me specifying the click position does not work at all: no matter what is specified for x and y, it always tries to click in the center.

Please file this is a separate bug report and attach a repro.
