### ISSUE TITLE
[Bug]: Page that normally triggers desktop app never loads

### ISSUE THREAD

**Issue by jeff-an** [microsoft/playwright#33948]
### Version

1.44.1

### Steps to reproduce

Paste following in an index.ts file:

```
import { chromium } from "playwright";

async function main() {
  console.log("starting", Date.now());
  const browser = await chromium.launch({
    headless: true,
  });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto(
    "https://dropbox.zoom.us/j/99710057228?pwd=Z07jZXXOv2Ou9zfb81r1NBqKOizVbx.1"
  );
  console.log("loaded");
  console.log("done", Date.now());
  process.exit(0);
}

void main();
```

Then:
```
npx playwright install # if browsers are needed
npx tsx index.ts
```

### Expected behavior

The page should load and the script should exit normally in a reasonable amount of time.

### Actual behavior

The page load times out, even though I can very quickly load this link in a normal browser and also when using Chromium in headful mode on my Mac OS machine.

```
npx tsx index.ts
starting 1733896124032
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://dropbox.zoom.us/j/99710057228?pwd=Z07jZXXOv2Ou9zfb81r1NBqKOizVbx.1", waiting until "load"

    at main (/Users/jeffan/code/playwright-repro/index.ts:11:14) {
  name: 'TimeoutError'
}

Node.js v20.9.0
```

To be clear, I don't mind that there is likely no way to trigger the Zoom desktop app from a headless browser, but the page should load in the normal amount of time and I should be able to continue with the test without the timeout error.

### Additional context

My best guess is it's related to how the website triggers a custom protocol handler to open a desktop app. Perhaps since there is no way to trigger the normal dialog in a headless environment, playwright never thinks the page is loaded?

I also tried registering a dialog handler before navigating (e.g. adding `page.on('dialog', dialog => dialog.accept());`) but this doesn't seem to help.

### Environment

```shell
System:
    OS: macOS 14.4
    CPU: (14) arm64 Apple M3 Max
    Memory: 401.84 MB / 36.00 GB
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.21 - ~/Library/pnpm/yarn
    npm: 10.9.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 8.7.6 - ~/Library/pnpm/pnpm
  IDEs:
    VSCode: 1.95.3 - /Applications/Visual Studio Code.app/Contents/Resources/app/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    playwright: 1.44.1 => 1.44.1
```

**Comment by yury-s** [comment]
This is a known issue and there is an open feature request for it: https://github.com/microsoft/playwright/issues/11014. You can try the workarounds mentioned there or if testing the page while the dialog is still open, you can avoid waiting for 'load' event and just wait for the page navigation to commit like this:

```ts
test('test', async ({ page }) => {
  await page.goto("https://dropbox.zoom.us/j/99710057228?pwd=Z07jZXXOv2Ou9zfb81r1NBqKOizVbx.1", { waitUntil: "commit" });
  console.log("loaded");
  await expect(page.getByText('Don’t have the Zoom Workplace app installed?')).toBeVisible();
});
```

Folding into  https://github.com/microsoft/playwright/issues/11014, please upvote that issue if you are interested in this feature.
