### ISSUE TITLE
[Bug]: `:right-of` fails in Firefox for sub-pixel overlap

### ISSUE THREAD

**Issue by Bilge** [microsoft/playwright#33958]
### Version

1.49.0

### Steps to reproduce

1. Place a series of pairs of adjacent (not overlapping) elements together.
2. Query each with `page.locator(':right-of(:text-is("Foo"))` for each uniquely labelled pair.

### Expected behavior

The element immediately to the right of the element labelled "Foo" should be selected.

### Actual behavior

Due to sub-pixel overlap, which will affect _some_ but not _all_ of the pairs of elements, the wrong element will be selected, or more specifically, the immediately adjacent element effectively becomes "invisible" to the test because Playwright/Firefox sees the adjacent element as overlapping by fractions of a pixel.

### Additional context

In my example, my left-hand element of the pair has property `right` of its bounding rectangle set to `681.7666931152344` whilst the right-hand element of the pair has its `left` property set to `681.7666625976562`. Due to the fact that Firefox identifies the left element as extending over the right element by fractions of a pixel, it does not consider it to actually be to the right of it.

Note this behaviour does not occur in Chromium. I did not test Webkit.

Here is a screenshot of my element pairs, in case that's useful.

![Image](https://github.com/user-attachments/assets/09141bbd-bc29-4258-b09f-bf17dbbd97f3)

The markup is just the following, where each `<ul>` and `<li>` is a flex container. I do not think the specific mark-up is important, it is just that these positional tests are overly sensitive to imprecise floating point expressions in Firefox.

```yaml
- ul
  - li
    - span
    - div
  - li
    - span
    - div

etc.
```

Might I suggest simply rounding the positioning co-ordinates before doing the comparison?

### Environment

```shell
System:
    OS: Windows 11 10.0.26100
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 34.28 GB / 63.93 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\.yarn\bin\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Bash: 5.2.26 - C:\Program Files\Git\usr\bin\bash.EXE
  npmPackages:
    @playwright/test: ^1.49.0 => 1.49.0
```

**Comment by yury-s** [comment]
Please attach code of the repro, so that we could run it locally.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
