### ISSUE TITLE
[Bug]: Playwright tries to use incorrect executable for `channel: 'chromium'` in headless mode

### ISSUE THREAD

**Issue by Ethan-Arrowood** [microsoft/playwright#33960]
### Version

1.49.1

### Steps to reproduce

Install playwright with `npx playwright install chromium --with-deps --only-shell`

Define config as:

```js
const { defineConfig, devices } = require('@playwright/test');

module.exports = defineConfig({
	projects: [
		{
			name: 'chromium',
			use: { ...devices['Desktop Chrome'], channel: 'chromium' },
		}
	],
});
```

Attempt to run a test, and get: 

```
    Error: browserType.launch: Executable doesn't exist at /root/.cache/ms-playwright/chromium-1148/chrome-linux/chrome
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝
```

The `chromium-1148` does not exist:

```
> ls /root/.cache/ms-playwright/
.links/                       chromium_headless_shell-1148/ ffmpeg-1010/  
```

### Expected behavior

I expect playwright to execute chromium_headless_shell-1148

### Actual behavior

It attempts to execute `chromium-1148` and I don't see anyway to configure or fix that.

### Additional context

Related: https://github.com/microsoft/playwright/issues/33673

I'm trying to optimize my docker container image: https://playwright.dev/docs/browsers#opt-in-to-new-headless-mode

### Environment

```shell
System:
    OS: Linux 6.11 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (6) arm64 unknown
    Memory: 1.97 GB / 3.53 GB
    Container: Yes
  Binaries:
    Node: 22.12.0 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.9.0 - /usr/local/bin/npm
  Languages:
    Bash: 5.2.15 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.49.0 => 1.49.1
```

**Comment by Ethan-Arrowood** [comment]
It also occurs on my local macos system following the exact same steps. it looks for `chromium-1148` and only `chromium_headless...` gets installed.

**Comment by yury-s** [comment]
This is working as expected, by setting `channel: 'chromium'` you opt into the [new headless mode](https://playwright.dev/docs/browsers#opt-in-to-new-headless-mode), it will run the chromium binary. If you want to stay with headless shell, which is the default, you need to remove `channel` option from the config. I'll update the documentation to clarify this confusion.

**Comment by mirao** [comment]
I've got the same issue.
In my docker image, the correct way how to install Playwright with Chromium in the new headless mode (`channel: "chromium"`) is `pnpm playwright install --with-deps --no-shell` (see https://github.com/microsoft/playwright/issues/33566).

The option `--no-shell` allows to get rid of downloading of the shell binary I don't need for the new headless mode.
BTW the option `--no-shell` isn't mentioned in official docs on https://playwright.dev/. It would be fine to put it there.

**Comment by Zubair2019** [comment]
Do **playwright install chromium** instead of **playwright install**

**Comment by Samiu1** [comment]
I'm on a mac and had the same issue. try

`npx playwright install --with-deps --only-shell`

**Comment by ghost** [comment]
@yury-s https://playwright.dev/docs/library maybe u should fix the main page of guides that provides broken description as well?
