### ISSUE TITLE
[Feature]: Add ability to validate PDF file contents by loading it into the browser or any other means. User should be able to assert different text elements, images/icons presence and CSS properties too.

### ISSUE THREAD

**Issue by rehan1124** [microsoft/playwright#33971]
### 🚀 Feature Request

Many products in the market has functionality to generate report from their application. This report could be in PDF format or CSV/Excel.
Although Playwright is browser automation tool, it would be very helpful if Playwright also supports ability to validate PDF contents.

User should be able to assert text elements on PDF, presence of images/icons, CSS properties for any element.

Also it would be nice if in-built mechanism to validate CSV/Excel content is also provided.

I understand there are external libraries, but instead of doing that, why not have it inside Playwright itself.

### Example

1. Feature will be used to validate PDF contents, texts, presence of images/icon, CSS properties.
2. If CSV/Excel content validation can be added too, that would be great.

### Motivation

Motivation is my company's products. We are using paid tools to validate this feature. Want to move away from that and bring everything to Playwright as it's open-source.

_How will it make Playwright better?_
Well none of the other automation libraries/frameworks that are open, has this ability. So Playwright would be the first one in market and trust me guys, you will break all those paid tools out there.
I see bright future for Playwright + Microsoft Playwright Testing (on-cloud)

**Comment by yury-s** [comment]
Testing PDFs is out of scope for Playwright. As a workaround you can use something like PDF.js to render PDF and then test it as a regular website.

Related issue https://github.com/microsoft/playwright/issues/19253
