### ISSUE TITLE
[Feature]: Add ToMatchSelectorAsync to LocatorAssertion

### ISSUE THREAD

**Issue by Totati** [microsoft/playwright#33978]
### 🚀 Feature Request

Add a LocatorAssertion, so the element can be checked against matching a css selector. This would allow more robust assertions.
HTMLElement implements a [matches method](https://developer.mozilla.org/en-US/docs/Web/API/Element/matches), this allows checking attributes, classes with one call. Same would be nice in Playwright as well.

### Example

```html
<div class='selected row' id='component'></div>
```

``` c#
var locator = Page.Locator("#component");
await Expect(locator).ToMatchSelectorAsync('.selected');
```

### Motivation

Using `Regex` and `ToHaveClassAsync` and checking attributes one by one with `ToHaveAttributeAsync` feels inefficient.

**Comment by yury-s** [comment]
Is there another example apart from matching multiple classes on the same element where it would be useful?

**Comment by Totati** [comment]
@Skn0tt @yury-s. Yes, it can be used for matching multiple classes, but also any css selectors. Currently there's no way to check [custom states](https://developer.mozilla.org/en-US/docs/Web/CSS/:state) or most of the [pseudo classes](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes).
