### ISSUE TITLE
[Bug][Playwright Test for VSCode]: Lint issue resulting in lingering SyntaxErrors

### ISSUE THREAD

**Issue by rozdun** [microsoft/playwright#33985]
### Version

1.1.12 (Playwright Test for VSCode)

### Steps to reproduce

Sometimes (but fairly consistently during normal coding) some errors will remain on the Problems list, even after undoing changes or removing code in full.

The issue does not reproduce on version 1.1.7 or lower (Playwright Test for VSCode).

Repro steps:
1. Write simple code such as:
```
import { test, expect } from '@playwright/test'

test('test', async ({ page }) => {
    const successButton = page.locator('button')
})
```
2. Remove part of the code so that an error can be expected.
3. Press Ctrl + Z.
4. Press Ctrl + Y.
5. Repeat steps 3-4 at various speeds until the issue appears.

### Expected behavior

No lingering errors in the Problems tab.

### Actual behavior

The errors remain on the list, even after undoing changes or removing code in full.

### Additional context

Video:
https://streamable.com/9l40jf

### Environment

```shell
System:
    OS: Windows 10 10.0.18362
    CPU: (16) x64 AMD Ryzen 7 1700 Eight-Core Processor
    Memory: 6.47 GB / 15.95 GB
  Binaries:
    Node: 22.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @playwright/test: ^1.49.1 => 1.49.1
```

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/33671
