### ISSUE TITLE
[Bug]: Key board operation are not working in headless mode if my webpage have Cross-Origin Restrictions

### ISSUE THREAD

**Issue by JyotiPMallick** [microsoft/playwright#33995]
### Version

1.49.0

### Steps to reproduce

I am automating my login functionality using typescript. 
1. Open up the browser.
2. Enter the 10-digit mobile number. 
3. Now click on generating the OTP.
4. For the test environment, we have a bypass mechanism, so we have leveraged "**Control + V**" (which eventually pastes the OTP). 

Note: I am running the test with **"Headless: True"**

So I took 2 way to solve this,

Way 1: traditional one

```
this.page.keyboard.down('Control');
this.page.keyboard.press('V');
this.page.keyboard.up('Control');
```

Way 2: I tried with a work around, by copying the OTP to clipboard 

Copy the OTP to the clipboard and assign this to a variable. After it fill it in the OTP field.

In both scenarios, I am getting,

"**Permission Denied**" issue due to cross-origin restrictions: In some cases, browser security settings restrict access to the clipboard, especially if you're dealing with cross-origin content.

Is there any workaround for this? Or how we can deal with it. But same isworking fine when I am running the test with headless "**False**"

### Expected behavior

The OTP should be getting copied

### Actual behavior

The OTP is not getting copied

### Environment

```shell
OS : Windows 
Scripting Language : Typescript
```

**Comment by yury-s** [comment]
This seems to be the same as https://github.com/microsoft/playwright/issues/24039. Please share a reproduction, so that we can run it locally.

Can you try it with the [new headless](https://playwright.dev/docs/browsers#opt-in-to-new-headless-mode) mode?

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/24039
