### ISSUE TITLE
[Bug]: tobeeditable() assertion is not working as expected after update to 1.49.1

### ISSUE THREAD

**Issue by sat1591** [microsoft/playwright#34007]
### Version

1.49.1

### Steps to reproduce

I see there is an issue with the tobeeditable() function. This version has worked until yesterday but after updating to 1.49.1 this function is stopped working

Test Code:
```
this.$unitField = page.getByRole("cell", { name: "Unit" });
await expect(orfpage.$unitField).not.toBeEditable();
```

HTML Element (Kendo dropdown Element):
`
<span title="" class="k-picker k-dropdownlist k-disabled k-picker-solid k-picker-md k-rounded-md" unselectable="on" role="combobox" aria-expanded="false" aria-controls="unitOfMeasure_listbox" aria-disabled="true" aria-readonly="false" style="width: 100%; border-color: rgba(66, 66, 66, 0.5) !important;" aria-busy="false" aria-describedby="fbbaee54-8064-4e6d-a8fa-e5f4841e2746"><span id="fbbaee54-8064-4e6d-a8fa-e5f4841e2746" unselectable="on" class="k-input-inner"><span class="k-input-value-text">- Select Unit -</span></span><span role="button" class="k-input-button k-button k-button-md k-button-solid k-button-solid-base k-icon-button" aria-label="select" type="button"><span class="k-icon k-i-arrow-s k-button-icon"></span></span><input disabled="disabled" id="unitOfMeasure" name="unitOfMeasure" required="required" style="width: 100%; border-color: rgba(66, 66, 66, 0.5) !important; display: none;" type="text" validationmessage="Unit is required" value="" data-role="dropdownlist"></span>
`

![Image](https://github.com/user-attachments/assets/dc8ad089-aded-4e0b-83cc-451e1cbd6da0)

### Expected behavior

I expected the test should pass because the dropdown element is not editable in our UI

### Actual behavior

Test is getting failed because the element is reading as editable.

Locator: getByRole('cell', { name: 'Unit' })
Expected: not editable
Received: editable

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 AMD EPYC 7763 64-Core Processor
    Memory: 5.27 GB / 15.95 GB
  Binaries:
    Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.88.1 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  npmPackages:
    @playwright/test: ^1.49.1 => 1.49.1
```

**Comment by yury-s** [comment]
Please share complete example which we could run locally, `getByRole("cell", { name: "Unit" })` doesn't resolve to an element on the provided html snippet.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
