### ISSUE TITLE
[Feature]: mode=serial option to behave same as mode=parallel with workers=1

### ISSUE THREAD

**Issue by davidAtInleague** [microsoft/playwright#34003]
### 🚀 Feature Request

mode=serial differs in more than parallelism from mode=parallel, in that ["If one of the serial tests fails, all subsequent tests are skipped. All tests in a group are retried together." ](https://playwright.dev/docs/test-parallel#serial-mode)

Owing to this behavioral difference, I have some tests that should run "mode=parallel, workers=1", so that a single failure does not result in a retry of all tests in the file. But, workers is not configurable on a per-file basis, so this test must be run separately from other tests we have, to enable commandline configuration of `--workers 1`. I wonder if it is possible to add one of the following options:

- `test.describe.configure({workers: number})`
- `test.describe.configure({mode: "serial-but-really-more-like-parallel-with-workers-1"})`

### Motivation

This would turn a comment in the file ("hey you! make sure to run this file serially, but not actually serially, use parallel with --workers 1") into actual test configuration code (which itself may be commented, but at least the behavior of playwright is then code driven).

**Comment by yury-s** [comment]
By default "Tests in a single file are run in order, in the same worker process." (see https://playwright.dev/docs/test-parallel#introduction), how is what you request different from that behavior?

**Comment by davidAtInleague** [comment]
In parallel mode, with workers=1, the failure of a single test continues on to the next test, or retries the failed test until the max retries, and then continues to the next test.

In serial mode, a failure of a single test skips all subsequent tests; if there are retries, all tests are retried, including the ones that already succeeded up to the point of the first failure.

The request here is for an option that would configure a test file to run in serial mode, but with failure/retry behavior of a test run in "parallel with workers=1".

**Comment by yury-s** [comment]
This is what 'default' mode does: single test failure doesn't prevent execution of subsequent tests in the same file, on retries only failed tests will rerun, and the tests from the same file will run on a single worker process, i.e. the won't run in parallel with one another. If you have 'fullyParallel: true` in the config, you can set the mode per file:

```ts
test.describe.configure({
  mode: 'default',
});
```

would that work?

**Comment by davidAtInleague** [comment]
Oh, I see. Yes, that is what I was looking for. Thank you for patience, and guiding me to the answer.

**Comment by Makavelic** [comment]
> This is what 'default' mode does: single test failure doesn't prevent execution of subsequent tests in the same file, on retries only failed tests will rerun, and the tests from the same file will run on a single worker process, i.e. the won't run in parallel with one another. If you have 'fullyParallel: true` in the config, you can set the mode per file:
> 
> test.describe.configure({
>   mode: 'default',
> });
> would that work?

Just a suggestion, the documentation you linked does not mention default mode at all, I think adding a section would help clear up confusion for new users.
