### ISSUE TITLE
[Docs]: locator('visible=false') doesn't find invisible elements

### ISSUE THREAD

**Issue by dnotes** [microsoft/playwright#34019]
### Page(s)

https://playwright.dev/docs/locators#matching-only-visible-elements

### Description

The [documentation page for matching only visible elements](https://playwright.dev/docs/locators#matching-only-visible-elements) instructs us to use `.locator('visible=true')` for matching only visible elements. This clearly implies that something like `.locator('visible=false')` will find the invisible elements, but no: that also finds the visible elements. In fact any value, even something like `.locator('visible=fwah')` will find the visible elements. I thought maybe there was no way to find hidden elements, but eventually I found that `.locator('visible=')` serves for this purpose. I suggest adding this to the documentation at least, or perhaps, even making `.locator('visible=false')` work like one might expect.

**Comment by pavelfeldman** [comment]
Probably better to make false work. Today it is looking at the truthy string value it seems.
