### ISSUE TITLE
[Feature]: `create-playwright` option `--with-version` flag

### ISSUE THREAD

**Issue by karlhorky** [microsoft/playwright#34026]
### 🚀 Feature Request

A new `create-playwright` option `--with-version <@playwright/test version specifier>` to allow specifying a specific version number of `@playwright/test`

### Example

```bash
$ pnpm create playwright --with-version 1.41.1

...


devDependencies:
 + @playwright/test 1.41.1
```

or with a version range specifier:

```bash
$ pnpm create playwright --with-version ^1.41.0

...


devDependencies:
 + @playwright/test 1.41.2
```

### Motivation

Currently, it's only possible to specify `--next` and `--beta` flags, not a specific version number of `@playwright/test`

```bash
$ pnpm create playwright --help
.../193cb9bff6e-185f1                    |   +1 +
.../193cb9bff6e-185f1                    | Progress: resolved 1, reused 0, downloaded 1, added 1, done
Usage: npx create-playwright@latest [options] [rootDir]
    Available options are:
      --help: print this message
      --browser=<name>: browsers to use in default config (default: 'chromium,firefox,webkit')
      --no-browsers: do not download browsers (can be done manually via 'npx playwright install')
      --no-examples: do not create example test files
      --install-deps: install dependencies (default: false)
      --next: install @next version of Playwright
      --beta: install @beta version of Playwright
      --ct: install Playwright Component testing
      --quiet: do not ask for interactive input prompts
      --gha: install GitHub Actions
      --lang=<js>: language to use (default: 'TypeScript'. Potential values: 'js', 'TypeScript')
```

**Comment by pavelfeldman** [comment]
> Currently, it's only possible to specify --next and --beta flags, not a specific version number of @playwright/test

That's by design, we never want to see projects created with the out-of-date Playwright.

**Comment by karlhorky** [comment]
@pavelfeldman it wouldn't necessarily need to be an out-of-date version:

```bash
$ pnpm create playwright --with-version 1.50.0-alpha-2024-12-14

...


devDependencies:
 + @playwright/test 1.50.0-alpha-2024-12-14
```

A specific, newer version.

**Comment by pavelfeldman** [comment]
I see. I am worried that this will encourage installation of the out-of-date versions more than help those interested in alpha / beta. Those interested in the newer versions would do `npm i`. What is your exact scenario?

**Comment by karlhorky** [comment]
1. Easy scaffolding for quick creation of bug reproductions (also for old versions)
2. Bug-for-bug, feature-for-feature scaffolding compatibility with pinned versions of `@playwright/test`, for reproducibility with existing pinned material such as docs, training material, blog posts

**Comment by pavelfeldman** [comment]
That sounds narrow enough to allow for the `npm i` workaround.

**Comment by karlhorky** [comment]
Ok, closing.
