### ISSUE TITLE
Blank screen is opening while running plawright in UI mode and Trace Viewer is also launching in blank screen

### ISSUE THREAD

**Issue by Shubhamrk10-JS** [microsoft/playwright#34021]
### Please do not submit this issue.

- [x] I understand

**Comment by Shubhamrk10-JS** [comment]
I am getting blank screen of playwright UI and trace viewer is also showing blank screen. 

Below is the playwright config file:
// @ts-check
const { defineConfig, devices } = require('@playwright/test');

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// require('dotenv').config({ path: path.resolve(__dirname, '.env') });

/**
 * @see https://playwright.dev/docs/test-configuration
 */
module.exports = defineConfig({
  testDir: './tests',
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: 'html',
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://127.0.0.1:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on',

    
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },

    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },

    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },



    /* Test against mobile viewports. */
    // {
    //   name: 'Mobile Chrome',
    //   use: { ...devices['Pixel 5'] },
    // },
    // {
    //   name: 'Mobile Safari',
    //   use: { ...devices['iPhone 12'] },
    // },

    /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: { ...devices['Desktop Edge'], channel: 'msedge' },
    // },
    // {
    //   name: 'Google Chrome',
    //   use: { ...devices['Desktop Chrome'], channel: 'chrome' },
    // },
  ],

  /* Run your local dev server before starting the tests */
  // webServer: {
  //   command: 'npm run start',
  //   url: 'http://127.0.0.1:3000',
  //   reuseExistingServer: !process.env.CI,
  // },
});


In config file I tried with 'trace: 'retain-on-failure', but still it was same issue.

Error/Help:

Getting such screen:
![Image](https://github.com/user-attachments/assets/aca5f4c9-b4aa-4aef-b835-b386167d7962)

**Comment by Shubhamrk10-JS** [comment]
Using cmd: npx playwright test --ui

Getting same blank screen:
![Image](https://github.com/user-attachments/assets/34994549-aa85-46e7-ba33-24cae5d7d6eb)

**Comment by pavelfeldman** [comment]
Try opening devtools and seeing if there are some bad error messages in console.

**Comment by Toxiapo** [comment]
I'm experiencing the same issue, but it's inconsistent. About half the time, I encounter a blank page during my test, which is marked as flaky and failed in our Ci/CD. I'd really appreciate it if anyone could provide some insights to help resolve this.

This is a React app and I used the following code snippet to capture screenshots on failed tests.

```
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status === "failed") {
    await page.screenshot({
      path: `screenshots/${testInfo.title}.png`,
      fullPage: true,
    });
  }
});
```

**Comment by IsmailSAly** [comment]
How did this get marked as complete. I am facing same issue with 1.49.1 using webkit and device emulation
