### ISSUE TITLE
[Feature] - playwright browser installation is not working in red hat linux

### ISSUE THREAD

**Issue by ashishsaboo15** [microsoft/playwright#34027]
I am doing npx install playwright which is not working in red hat linux. and my organization is only supporting RHEL. I was trying to use docker but outside image also not supported as there is no internet connectivity in docker machine. could you please suggest what is best way to run playwright in this situation.

**Comment by pavelfeldman** [comment]
As this falls outside of the scope for Playwright, I'd recommend asking the community at Discord.
