### ISSUE TITLE
[Bug]: Playwright has a hidden vulnerability to detection

### ISSUE THREAD

**Issue by electroae4** [microsoft/playwright#34025]
### Version

1.49.0

### Steps to reproduce

Playwright has a hidden vulnerability that makes it easy to detect.

For example, the site https://domclick.ru easily detects the Playwright robot. And at the same time, it cannot detect the Selenium robot with the same settings.

### Expected behavior

With the same settings for Playwright and Selenium, Playwright should not be so easy to detect.

### Actual behavior

The site https://domclick.ru easily detects the use of Playwright. 
There are some distinctive behaviors or properties that signal automation.
Selenium is not detected.

#### Playwright
```
from time import sleep
from playwright.sync_api import sync_playwright

playwright = sync_playwright().start()

browser = playwright.chromium.launch(
    args=['--disable-blink-features=AutomationControlled'],
    ignore_default_args=["--enable-automation"],
    headless=False,
)

page = browser.new_page()

try:
    page.goto('https://domclick.ru')
    sleep(20)

finally:
    page.close()
    browser.close()
    playwright.stop()
```

#### Selenium
Note: when using Selenium, need to additionally remove the window.cdc_... properties. Playwright simply does not have them.
```
from time import sleep
from selenium import webdriver

options = webdriver.ChromeOptions()
options.add_argument('--disable-blink-features=AutomationControlled')
options.add_experimental_option("excludeSwitches", ["enable-automation"])

driver = webdriver.Chrome(options=options)

driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {
    'source': '''
        delete window.cdc_adoQpoasnfa76pfcZLmcfl_Array;
        delete window.cdc_adoQpoasnfa76pfcZLmcfl_Promise;
        delete window.cdc_adoQpoasnfa76pfcZLmcfl_Symbol;
        delete window.cdc_adoQpoasnfa76pfcZLmcfl_JSON;
        delete window.cdc_adoQpoasnfa76pfcZLmcfl_Object;
        delete window.cdc_adoQpoasnfa76pfcZLmcfl_Proxy;
        delete window.cdc_adoQpoasnfa76pfcZLmcfl_Window;
    '''
})

try:
    driver.get('https://domclick.ru/')
    sleep(20)

finally:
    driver.close()
    driver.quit()
```

### Additional context

I've been looking very carefully for Playwright detection points, but haven't found anything yet.
This problem exists in all three browsers (chromium, firefox, webkit)

### Environment

```Text
- Operating System: [Windows 10 Pro]
- CPU: [AMD Ryzen 5 3600 6-Core]
- Browser: [Chromium, Firefox, WebKit]
- Python Version: [3.12.0]
```

**Comment by pavelfeldman** [comment]
Playwright is making sure it is easily detectable to prevent misuse. So should all other testing tools.

**Comment by electroae4** [comment]
Thanks for your reply.
Too bad. Playwright is a great tool, but I guess I'll have to use others.

**Comment by electroae4** [comment]
Playwright + Camoufox = Great tool
