### ISSUE TITLE
[Feature]: API for window.history.go()

### ISSUE THREAD

**Issue by leotg130** [microsoft/playwright#34028]
### 🚀 Feature Request

Currently Playwright supports both `page.goBack()` and `page.goForward()`, but seems to lack the other option that `window.history.go()` supports, which is multiple history navigations in one go.

Not sure if it even makes sense to keep both the `goBack()/goForward()`, or if there should be just `.go(delta: number, options: {...})`.

Might also make sense to expose the entire history API, and if possible more extensively than is allowed by JS on a page, which doesn't have access to the URL's, etc. Though I'm not sure how Playwright instruments the browser, so it might not have any more access than JS on page does.

### Motivation

Allows to better simulate user behavior where user navigates multiple history pages.

**Comment by pavelfeldman** [comment]
I'd recommend using `page.evaluate()` to make a call to this window API.

**Comment by leotg130** [comment]
Yeah, I do use that as a workaround, but would be nicer if Playwright provided it out of the box, no?

**Comment by pavelfeldman** [comment]
It is so rare, that's the first time it is requested over the last 4 years, so with the clear workaround closing it as "has workaround" is very tempting.

**Comment by leotg130** [comment]
Fair enough.. I thought a clean API would be nice, and presumably quite simple to do, though I don't know the Playwright internals.

No problem with closing the issue if you don't think it's worth it.
