### ISSUE TITLE
[Feature]: State visibility check for multiple elements

### ISSUE THREAD

**Issue by tasawar-hussain** [microsoft/playwright#34024]
### 🚀 Feature Request

Support for non-strict mode in waitFor and new assertions like toBeAllVisible() / toBeAllHidden() to handle multiple matching elements gracefully.

### Example

Currently, when migrating from deprecated waitForSelector, the following code breaks in strict mode if the selector resolves to more than one element:

// Previously worked fine:
```js
await page.waitForSelector('.skeleton', { state: 'hidden' });
await page.waitForSelector('.skeleton');
```
After migrating to waitFor or using assertions, the same logic fails when the selector resolves to multiple elements:

// Fails in strict mode with multiple matching elements
```js
await page.locator('.skeleton').waitFor({ state: 'hidden' });
await page.locator('.skeleton').waitFor({ state: 'visible' });
```

Proposed solutions:

- Introduce a strict: false option for waitFor, allowing it to work with multiple elements.
- Provide assertions like toBeAllVisible() and toBeAllHidden() to handle visibility checks for multiple elements in a single call.

### Motivation

The transition away from [waitForSelector](https://playwright.dev/docs/api/class-page#page-wait-for-selector) has introduced challenges for cases where selectors resolve to multiple elements. Strict mode enforces the expectation of a single match, which breaks compatibility with prior implementations.

Adding a `strict: false` option or supporting assertions like `toBeAllVisible()` and `toBeAllHidden()` would:

- Ensure smoother migration from waitForSelector to waitFor or locator-based assertions.
- Improve readability and maintainability by providing concise APIs for visibility checks on multiple elements.
- Align Playwright's flexibility with real-world use cases where multiple matching elements are expected.

**Comment by pavelfeldman** [comment]
Can you try adding `.first()` to after your locator to opt out from the strict mode like in other actions?

**Comment by tasawar-hussain** [comment]
Adding `.first()` defeats the purpose , specially dealing with skeletons

**Comment by pavelfeldman** [comment]
I probably misunderstood the issue then. Can you provide a self-contained example that I could run?

**Comment by Skn0tt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
