### ISSUE TITLE
[Bug]: The recording duration of the video does not match the test duration

### ISSUE THREAD

**Issue by Damon99999** [microsoft/playwright#34043]
### Version

1.49

### Steps to reproduce

 **1: Trun on the video recording in the configuration file(playwright.config.js)**
 **2: run the test for hours**

### Expected behavior

**The recording time will match with the test time**

### Actual behavior

**The recording time don't match with the test time. Actually,the recording time is longer than test time**

### Additional context

![Image](https://github.com/user-attachments/assets/d77513bf-ce1b-457e-9864-b733aaf1fc63)
![Image](https://github.com/user-attachments/assets/199fbe9c-8a87-4b56-a329-909bbd93d92a)
![Image](https://github.com/user-attachments/assets/ae59bc3e-9a1f-486b-ac4d-a45ce724f993)

# Environment

```shell
System:
  OS: Windows 10 (19043.1023)
  CPU: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz   2.90 GHz
Binaries:
  Node: v20.18.0
  npm: 10.8.2
  yarn：1.22.22
npmPackages:
  @playwright/test: version 1.49.1 => 1.49.1
```

**Comment by pavelfeldman** [comment]
Please follow the issue template to file something we can repro. I'm not sure we'll be addressing and/or reproducing the 16h recording though. Is your test taking 16h? That would make a large video file.

**Comment by Damon99999** [comment]
> Please follow the issue template to file something we can repro. I'm not sure we'll be addressing and/or reproducing the 16h recording though. Is your test taking 16h? That would make a large video file.

Actually, the test task will last a minimum of 8 hours and could extend up to 72 hours, depending on various factors. As a result, the video file size is expected to range from 2GB to 10GB.

**Comment by pavelfeldman** [comment]
I don't think we'll be able to help with it. One idea would be that the video includes context creation as well, so it captures more time.

**Comment by Damon99999** [comment]
> I don't think we'll be able to help with it. One idea would be that the video includes context creation as well, so it captures more time.

ok. Anyway, thinks for you help

**Comment by MohammadMDSA** [comment]
> I don't think we'll be able to help with it. One idea would be that the video includes context creation as well, so it captures more time.

It is not. I have tested it a lot. For some reason, it is simply recording at a slower rate. Maybe the load on the CPU is high, so it is missing frame deadlines. Is this the reason it is longer?
