### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by shreenidhishegde** [microsoft/playwright#34060]
### Version

1.41.2

### Steps to reproduce

Playwright tests are flaky

### Expected behavior

I expect the playwright tests to pass on GitHub actions

### Actual behavior

My Playwright tests work fine on local, However, they are flaky on GitHub Actions. I am getting timeout error most of the time : 

 async def continuation() -> Optional[Response]:
>       event = await waiter.result()
E       playwright._impl._errors.TimeoutError: Timeout 120000ms exceeded.
E       =========================== logs ===========================
E       waiting for navigation to "http://localhost:5173/login" until 'load'
E       ============================================================

### Environment

```shell
System:
    OS: macOS 15.1.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 251.36 MB / 16.00 GB
  Binaries:
    Node: 23.3.0 - /opt/homebrew/bin/node
    npm: 10.9.0 - /opt/homebrew/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
