### ISSUE TITLE
[Bug]: The method toMatchSnapshot() is not tolerating a Threshold of 20%

### ISSUE THREAD

**Issue by prabsaho** [microsoft/playwright#34062]
### Version

1.49.1

### Steps to reproduce

Pre requisite : The expected screenshot is already saved by playwright in the respective folder for comparison
1.Write a code for screenshot comparison of a particular locator in webpage.
 e.g. expect (await page.locator("[class='map-goal']")).screenshot('actual-map-screenshot.png')).toMatchSnapshot('expected-map-screenshot',{threshold :0.2})

### Expected behavior

It should allow a threshold upto 0.2

### Actual behavior

it's failing at Threshold of 0.02

![Image](https://github.com/user-attachments/assets/8c657cbd-4e88-46ca-85f2-750ac2ae0774)

Error is : Expected an image 616px by 375px, received 615px by 374px. 4497 pixels (ratio 0.02 of all image pixels) are different.

### Environment

```shell
Both Mac & Windows latest
```

**Comment by pavelfeldman** [comment]
Please follow the issue template and provide something I can reproduce locally via running the test. Include resources, scripts and command line.

**Comment by Skn0tt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
