### ISSUE TITLE
[Bug]: Playwright tests are flaky on GitHub actions (worked only few times and not working most of the times), while they work on local

### ISSUE THREAD

**Issue by shreenidhishegde** [microsoft/playwright#34075]
### Version

1.41.2

### Steps to reproduce

Code Snippet
---> Below is the workflow I have been using.

name: playwright-test
on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [main]
jobs:
  build_playwright_tests:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    # Check out our code.
    - uses: actions/checkout@v3
    # Use a Python version that matches our local setup.
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
        cache: "pip"
        cache-dependency-path: requirements/**.txt
    - name: Debug information
      run: |
        echo "Node version: $(node -v)"
        echo "NPM version: $(npm -v)"
        echo "Playwright version: $(npx playwright -v)"
        echo "System info: $(uname -a)"
      shell: bash

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements/local.txt
        python -m pip install -r requirements/dev.txt
        python -m pip install --upgrade pip
        cd abc/web/frontend && npm install && cd -
        playwright install

    - name: Playwright tests
      env:

        EG_TEST_USER_PASSWORD: ${{ secrets.EG_TEST_USER_PASSWORD }}

        PLAYWRIGHT_DEBUG: 1
      # Don't eat too much quota.
      timeout-minutes: 40
      
      run: |
        make test-playwright-gh PLAYWRIGHT_DEBUG=1 

    - name: Debug on failure
      if: failure()
      run: |
        echo "Test failed. Outputting additional debug information..."
      shell: bash

### Expected behavior

Expect the tests to pass on GitHub actions workflow

### Actual behavior

Error on github actions workflow : 

abc/web/tests-e2e/test-playwright/test_login_logout.py:41: AssertionError
------------------------------ Captured log call -------------------------------
WARNING  test_login_logout:test_login_logout.py:31 H1 element not found
ERROR    test_login_logout:test_login_logout.py:58 Error during test: Locator expected to have text 'Welcome'
Actual value: None 
Call log:
LocatorAssertions.to_have_text with timeout 60000ms
  - waiting for locator("h1")
Traceback (most recent call last):
  File "/home/runner/work/core/core/abc/web/tests-e2e/test-playwright/test_login_logout.py", line 41, in test_login_logout
    expect(page.locator("h1")).to_have_text("Welcome", timeout=60000)
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/playwright/sync_api/_generated.py", line 20408, in to_have_text
    self._sync(
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/playwright/_impl/_assertions.py", line 471, in to_have_text
    await self._expect_impl(
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/playwright/_impl/_assertions.py", line 70, in _expect_impl
    raise AssertionError(
AssertionError: Locator expected to have text 'Welcome'
Actual value: None 
Call log:
LocatorAssertions.to_have_text with timeout 60000ms
  - waiting for locator("h1")
=============================== warnings summary ===============================
../../../../../opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/pypdf/_crypt_providers/_cryptography.py:32
  /opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/pypdf/_crypt_providers/_cryptography.py:32: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
    from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED abc/web/tests-e2e/test-playwright/test_login_logout.py::test_login_logout - AssertionError: Locator expected to have text 'Welcome'
Actual value: None 
Call log:
LocatorAssertions.to_have_text with timeout 60000ms
  - waiting for locator("h1")
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
=================== 1 failed, 1 warning in 271.58s (0:04:31) ===================

### Additional context

This is my tests file run using pytest : test_sites_loads.py

import datetime

from playwright.sync_api import Page, expect

# `reset` is a test fixture that forces us to start the test backend/frontend.
# For details, see `conftest.py`.
def test_site_redirects_to_login_page_on_unauth(page: Page, reset) -> None:
    print(f"Test start time: {datetime.datetime.now()}")

    # Give CI environment more time to load the frontend
    #
    page.goto("http://localhost:5173/", wait_until="domcontentloaded", timeout=120000)

    print("Frontend loaded. Waiting for redirection...")
    page.wait_for_url("http://localhost:5173/login", timeout=120000)

    print(f"Test end time: {datetime.datetime.now()}")

    # Redirect ...

    expect(page).to_have_url("http://localhost:5173/login", timeout=30000)
    expect(page.get_by_role("heading", name="Welcome")).to_be_visible()
    expect(page.get_by_text("Sign in to abc")).to_be_visible()
    expect(page.get_by_placeholder("Enter your email")).to_be_visible()
    expect(page.get_by_placeholder("Password")).to_be_visible()

Makefile  command :
 test-playwright-gh:
	pytest -x -s abc/web/tests-e2e/test-playwright/

confest.py : 

CI_ENV = os.getenv("CI", "false").lower() == "true"

# Add custom browser path for local development (Google Chrome or others)
LOCAL_CHROME_PATH = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

@pytest.fixture(scope="session")
def browser():
    with sync_playwright() as p:
        if CI_ENV:
            # Use Playwright's bundled Chromium in CI environments (e.g., GitHub Actions)
            browser = p.chromium.launch(headless=True)
        else:
            # Use custom Google Chrome on local machines if available
            if os.path.exists(LOCAL_CHROME_PATH):
                browser = p.chromium.launch(
                    headless=False,  # Set to False to see the browser locally
                    executable_path=LOCAL_CHROME_PATH,
                )
            else:
                # Fallback to Playwright's bundled Chromium locally if Google Chrome is not found
                browser = p.chromium.launch(headless=False)

        yield browser
        browser.close()

@pytest.fixture(scope="function")
def page(browser):
    # Create a new page within the launched browser
    page = browser.new_page()
    yield page
    page.close()

### Environment

```shell
System:
    OS: macOS 15.1.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 92.69 MB / 16.00 GB
  Binaries:
    Node: 23.3.0 - /opt/homebrew/bin/node
    npm: 10.9.0 - /opt/homebrew/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Comment by pavelfeldman** [comment]
This usually means that your tests are flaky and you were lucky when running them locally. Make sure you follow the best practices and use Playwright's web assertions. We can't tell what is wrong without seeing the script, and we don't debug users' problems overall. Please only submit an issue with reproduction if you believe there is a bug in Playwright.
