### ISSUE TITLE
[Feature]: Run multiple instances of same test with different testdata

### ISSUE THREAD

**Issue by jdeisenhofer** [microsoft/playwright#34082]
### Background
I have found other feature requests like https://github.com/microsoft/playwright/issues/28220 or https://github.com/microsoft/playwright/issues/7036 .
My situation ist pretty similiar in that I have a set of testdata and I want my test to execute itself for each of them. My issue is, that I do not know the data, since they are sent to me and read automatically, so I don't know the size of my testdata and therefore I also do not know how many tests to start. As far as I know, this rules out the possibility of using this solution:
 `Data.foreach{
test(.........)
} `
Playwright needs to know how many tests to start. If I write my code this way, it will not recognize any tests to start, since the testdata are empty, until the test.beforeAll loop was executed.

### My current Solution

As proposed in the two above mentioned requests, there is already a solution in place to use the test.step method, which would look something like this: 
```
test.describe('execute tests on testdata', async() => {
    let data;
    test.beforeAll('load data', async() => {
        //load data from source here
        data = someMethodToLoadData('source');
    });

    test('execute tests with data', async() => {
        for(const dataEntry of data) {
            await test.step('This is the actual testcase!', async() => {
                //run test with data here
                ........testcode............
            });
        }
    });
});
```

The problem I have with this solution is that my actual testcases (in line 10 of my example) are not executed in parallel but in serial order and one failed test will cancel the execution of all other tests, due to playwright not considering them as testcases but rather as steps within the same test. What I wanted to do is create an own browsersession for each of them with own report etc... Playwright seemingly needs to know beforehand how many browsers to start. Only that this is precisely the information that I retrieve from the beforeAll part.

### Request

Is it possible to start a test execution without clearly defining how many test instances to start? Basically the idea is that I read data and depending on what was obtained, I want to start multiple testcases with different data. I want to build a data driven test approach by using a configurable testtemplate, that can be executed by specifying the data it uses. 
All solutions I found recently, only work, when the amount of data is known or when the tests are executed in serial order.

Always feel free to share your thoughts on my problem as well, as I have possibly overlooked a couple other routes to take.

### Motivation

This feature might help build automated test solutions in a more abstracgt way, so that data driven approaches can be built more easily. This way it should be easier to achieve greater test coverage with less coding work. Of course only assuming, that there isn't already a better solution for my problem.

**Comment by pavelfeldman** [comment]
Can you do this?

```js
const data = someMethodToLoadData('source');
for(let i = 0; i < data.length; ++i) {
  await test('This is the actual testcase ' + i, async() => {
    //run test with data[i] here
    ........testcode............
  });
}
```

**Comment by jdeisenhofer** [comment]
As far as I know, this would resolve in playwright not executing any tests, since `data.length` returns undefined until someMethodToLoadData() was executed. Therefore it regards the for loop executed without looping through its scope even once.

In my case I needed to put the function someMethodToLoadData into the test.beforeAll() , because the method is async. So I needed the context of another asynchronous function to load the data. I might be able to look up some library that helps me load the data without beeing asynchronous, but I don't know, where this would get me.

**Comment by pavelfeldman** [comment]
I did not realize someMethodToLoadData was async. when you say data.length returns undefined, you probably mean that data is a Promise object. Playwright does not support your scenario. You can fetch / generate your data as a separate step before you run tests or in global setup. Then in test file you would read it synchronously from the disk.

**Comment by jdeisenhofer** [comment]
I forgot to mention that my function was async. Sorry for the confusion.

Using global setup might be working in my scenario. Thanks for the help. I'll try that!
