### ISSUE TITLE
[Docs]: document HTML reporter output folder clash

### ISSUE THREAD

**Issue by reyrodrigez** [microsoft/playwright#34087]
### Page(s)

https://playwright.dev/docs/next/test-reporters#html-reporter

### Description

Could not find reference in the documentation to this configuration error below. Would be great to mention it in the [HTML reporter docs](https://playwright.dev/docs/next/test-reporters#html-reporter).
```
Configuration Error: HTML reporter output folder clashes with the tests output folder:

    html reporter folder: /tmp/build/upload/playwright/test-results/html
    test results folder: /tmp/build/upload/playwright/test-results

HTML reporter will clear its output directory prior to being generated, which will lead to the artifact loss.
```

**Comment by pavelfeldman** [comment]
Thank you for your report. This is as designed - users don't typically study the docs for all the potential runtime errors beforehand. And it is not feasible / practical to list all the potential errors anyways. That's why it is printed as a part of the runtime error message.
