### ISSUE TITLE
[Docs]: clarify that testInfo methods can not be destructured in fixtures

### ISSUE THREAD

**Issue by jancbeck** [microsoft/playwright#34089]
### Page(s)

https://playwright.dev/docs/api/class-testinfo
https://playwright.dev/docs/test-fixtures

### Description

I would expect this to work in principle e.g. when tests describe some seed data but I want to conditionally pre-seed an environment without actually running the tests:

```typescript
export const test = base.extend<{
  ...
}>({
  seed: [ 
    async ({ page, seedOptions }, use, { skip } ) => {

      const data = seedTestData(seedOptions)

      if (process.env.SKIP_TESTS) {
        skip();
      }

      await use(data);
    }, {
      auto: true,
      scope: 'test',
    }]
});
```

but it actually returns this error:

> TypeError: Cannot read properties of undefined (reading '_modifier')

I first considered that tests cannot be skipped via fixtures as that is not explicitly stated in the docs if #15071 didn't suggest it should work.

The solution is that `testInfo` must not be destructured:

```typescript
export const test = base.extend<{
  ...
}>({
  seed: [
    async ({ page, seedOptions }, use, testInfo ) => {

      const data = seedTestData(seedOptions)

      if (process.env.SKIP_TESTS) {
        testInfo.skip();
      }

      await use(data);
    }, {
      auto: true,
      scope: 'test',
    }]
});
```

This is counterintuitively the reverse of https://github.com/microsoft/playwright/issues/14590#issuecomment-1911734641 where the **first** fixture argument **must** be destructured and throws a helpful error if it isn't.

I'm posting this here as help for others who stumble upon this and in hope that this can be better documented.

**Comment by pavelfeldman** [comment]
That's how JavaScript works. The function needs to be bound to the receiver if you are calling it as free standing. This would not work either:

```js
const { querySelectorAll } = document;
querySelectorAll('body');
```
