### ISSUE TITLE
[Bug]:Har File issue

### ISSUE THREAD

**Issue by sandeep27121986** [microsoft/playwright#34109]
### Version

1.48.0

### Steps to reproduce

In playwright running with multiple scenario from Feature file
1 created Single Har file for Multiple API  scenario for Mock Routing 
2 route from Har file

### Expected behavior

It should route API  differently in Har file 

### Actual behavior

Issue

It not difference the API during routing post data value,
It route through the first API match in Har  file.

### Environment

```shell
Playwright java 1.48.0
java 8
```

**Comment by pavelfeldman** [comment]
Please follow the issue template to file something we can reproduce.

**Comment by dgozman** [comment]
Closing as per above. Please file a new issue by filling in the "Bug Report" template.
