### ISSUE TITLE
[Feature]: Global Retry Mechanism:

### ISSUE THREAD

**Issue by Rahimtulla** [microsoft/playwright#34112]
### 🚀 Feature Request

Implementing a global retry mechanism at the framework level would simplify handling flaky tests. This would allow retries to work seamlessly across all scenarios without requiring additional configuration or manual intervention, thereby improving test stability.

### Motivation

Flaky tests are a common challenge in test automation, often caused by intermittent issues such as network latency, resource contention, or timing inconsistencies. Addressing these flakes typically requires manual intervention or custom retry logic for each test, which can be time-consuming and error-prone.  

Implementing a **global retry mechanism** at the framework level would provide a standardized solution for managing flaky tests. By enabling retries to occur seamlessly across all scenarios without additional configuration, the framework can ensure higher test stability and reduce the manual overhead required to manage such issues.  

This feature would be particularly beneficial in large test suites executed in CI/CD pipelines, where reliability and efficiency are critical. A global retry mechanism would allow teams to focus on identifying real failures instead of debugging intermittent issues, ultimately improving productivity and confidence in test results.

**Comment by pavelfeldman** [comment]
Playwright has retry built-in, please start with exploring its capabilities and then file specific requests with specific examples.
