### ISSUE TITLE
[Bug]: Mobile webkit tests on Ubuntu works 4x slower in comparison with macOS

### ISSUE THREAD

**Issue by Ihor123166** [microsoft/playwright#34119]
### Version

1.49.1

### Steps to reproduce

1. `git clone https://github.com/Ihor123166/mobile-safari-bug-on-ubuntu.git`
2. `cd mobile-safari-bug-on-ubuntu` 
3. Install yarn if needed `npm install -g yarn`
4. Install dependencies `yarn && yarn playwright install --with-deps`
5. Install docker if needed
6. Run tests on ubuntu `docker run -it --rm --ipc=host -v ./:/tests mcr.microsoft.com/playwright:v1.49.1 /bin/bash -c "cd /tests && yarn playwright test tests/slow.spec.ts"`

### Expected behavior

Expect mobile WebKit tests on Ubuntu to pass at approximately the same speed as on macOS

![Image from macOS run](https://github.com/user-attachments/assets/0151ba80-c1c3-4162-acad-cf4df45e0262)

### Actual behavior

Mobile webkit tests on Ubuntu passed 4-5x slower in comparison with macOS. But other projects doesn't have such big difference in speed

![Image from Ubuntu docker run](https://github.com/user-attachments/assets/f3bceceb-7f58-45e0-b614-693519b6f834)

### Environment

```shell
System:
    OS: macOS 15.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 100.48 MB / 16.00 GB
  Binaries:
    Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: ^1.49.1 => 1.49.1
```

**Comment by pavelfeldman** [comment]
I can repro, unclear what is going on, looks like dedicated WebKit headless implementation on Linux (WPE) is hammered with rendering.

As a workaround, you can run your tests in a headed mode under xvfb:

```js
    {
      name: "Mobile Safari",
      use: {
        ...devices["iPhone 12"],
        headless: false,
      },
    },
```

![Image](https://github.com/user-attachments/assets/39ee9cf9-3029-4a86-9460-c451364c0e56)

**Comment by pavelfeldman** [comment]
Also, ToT seems to be working fine:

```js
npm i @playwright/test@1.50.0-alpha-2024-12-20
```

**Comment by Ihor123166** [comment]
@pavelfeldman Thank you, the workaround helped me, and it's working fine on version 1.50.0-alpha-2024-12-20 for me too
