### ISSUE TITLE
[BUG] Footer of Docs Misplaced

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#3412]
<img width="1441" alt="Screen Shot 2020-08-12 at 10 37 56 AM" src="https://user-images.githubusercontent.com/11915034/90048175-fe197b80-dc87-11ea-900a-b3e8dedde37d.png">

Aside: Is the site template open source?

**Comment by arjun27** [comment]
Thanks for checking @rwoll. This should be fixed now. We'll open source the website repo shortly.
