### ISSUE TITLE
[BUG] I am facing lot of browser slowness while executing the chrome browser tests

### ISSUE THREAD

**Issue by jagadish1010** [microsoft/playwright#34123]
I am using latest chrome and latest playwright jar. but while executing the tests locally on my mac 16 gb ram , post launching the browser , browser is becoming too slow and because of this tests are failing.

**Comment by Skn0tt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!

**Comment by jagadish1010** [comment]
Sorry I can't give the application details, I am trying to use chrome browser for automating our application. 
but with chrome browser, playwright automation is too slow. We are not able to run the tests. Tests are failing abrouptly.
