### ISSUE TITLE
[Feature]: QTWebEngine+React desktop app support as Electron

### ISSUE THREAD

**Issue by luccasgois1** [microsoft/playwright#34128]
### 🚀 Feature Request

It would be nice to support QTWebEngine desktop apps created with React as we support electron

### Example

With selenium is possible to do that by:

```python
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

service = Service(executable_path= 'path/to/webenginedriver''
options = webdriver.ChromeOptions()
options.binary_location = 'path/to/qtwebengine_react_app_binary'

driver = webdriver.Chrome(service=service, options=options)
```

### Motivation

Be able to test not only Desktop electron applications but also QTWebengine desktop aplicaitons would be great

**Comment by pavelfeldman** [comment]
This would be firmly out of scope for Playwright. Having said that, as QTWebEngine is built on top of Chromium, you should be able to `--remote-debugging-port=5000` and then [connect over cdp](https://playwright.dev/docs/api/class-browsertype#browser-type-connect-over-cdp).

**Comment by dgozman** [comment]
Adding to the above, the process should be somewhat similar to [WebView2](https://playwright.dev/docs/webview2) - run in a way to expose remote debugging port, connect from Playwright, optionally wrap it up with a nice helper.

Closing as there is no action item from Playwright side here.
