### ISSUE TITLE
[Feature]: Extending existing context objects or namespacing

### ISSUE THREAD

**Issue by NagRock** [microsoft/playwright#34126]
### New PO naming conflict

I want to create Browser functionality that will open new page by some action:

```export class Browser {
  constructor(private readonly context: BrowserContext) {}

  async newPageByAction(openAction: () => Promise<void>) {
    const pagePromise = this.context.waitForEvent('page');
    await openAction();
    const newPage = await pagePromise;
    await newPage.waitForLoadState('load');
  }
}
```

And I want to name it `Browser` just like the build one. I have naming conflict.

Of course I can name it `myBrowser` etc. but this will break my naming convention.

### New API naming conflict

Imagine I have a `window` named injectable object and playwright team decide to add `window` in one of next versions of playwright. I will need to make a refactor in my code to avoid conflicts. Rename my existing one PO and all usages.

### Idea

Option to extend `Browser`.

AFAiK only `Browser` interface is exported and I would need to implement all functions that `Browser` needs to create new one.

Option with scoped injection.

One for core objects and one for custom ones.

```test('should do something', async ({customOne, customTwo}, { context, browser }) => {
```

### Motivation

Option to extends or not to fall into naming conflicts when playwright API will be extended

**Comment by pavelfeldman** [comment]
That's not how Node modules and TypeScript work. Do your research, you should be able to find a solution!
