### ISSUE TITLE
[Feature]:   Request for Window Maximization and Minimization Features in Playwright

### ISSUE THREAD

**Issue by mostafakavand** [microsoft/playwright#34137]
### 🚀 Feature Request

Dear Playwright Development Team,

I hope this message finds you well.

First of all, I would like to express my sincere appreciation for the outstanding work you’ve done with Playwright. The library has been an invaluable tool in my automation and testing workflows, and I’m truly grateful for the continuous improvements.

While using Playwright, I noticed that there is no built-in support for maximizing or minimizing browser windows, which are common features in UI automation and testing. I wanted to inquire whether the absence of this functionality was a deliberate design decision or if it simply hasn’t been implemented yet.

As a developer who is passionate about contributing to open-source projects, I would love to collaborate with the Playwright team and add these features to the library. Specifically, I am interested in implementing methods to allow the following:

**.**  **Maximize** the browser window, similar to how it is handled in other frameworks like Selenium.
**.**  **Minimize** the browser window, to replicate real-world user interactions more closely during testing scenarios.
Before proceeding with the development of these features, I wanted to ask whether this functionality aligns with Playwright's goals and whether you would be open to including these changes in future versions of the library. I would be more than happy to contribute to the project and submit a pull request with my implementation.

Please let me know if you have any thoughts or guidelines regarding this feature, and I would be glad to discuss how we can make this contribution beneficial for the community.

Thank you once again for your hard work and dedication to the project. I look forward to hearing from you.

Best regards,
Mostafa Kavand

### Example

This feature would allow users to maximize the browser window during automation or testing. For example:
```
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    context = browser.new_context()
    page = context.new_page()
    
    # Open a page
    page.goto("https://example.com")
    
    # Maximize the browser window
    context.maximize_window()

    # Perform other actions
    page.click("button#submit")
```

Similarly, users could minimize the browser window to test specific interactions or simulate real-world scenarios:

```
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    context = browser.new_context()
    page = context.new_page()
    
    # Open a page
    page.goto("https://example.com")
    
    # Minimize the browser window
    context.minimize_window()
```

These methods (```maximize_window``` and ```minimize_window```) would provide developers with more flexibility for UI testing and help replicate real-world browser interactions more accurately.

### Motivation

The addition of maximize_window and minimize_window features will enhance Playwright's functionality and provide developers with greater control over browser window states. These features are essential for several reasons:

**1. Improved Testing Scenarios:** Many real-world UI interactions require the browser to be maximized or minimized to test responsiveness, layout behaviors, or user interactions in different states.

**2. Feature Parity:** Other automation frameworks like Selenium offer similar functionalities, and adding this to Playwright will make it more competitive and attractive for developers who need advanced window management.

**3. Real-World Simulation:** Maximizing and minimizing windows is a common action performed by end-users. Including these features in Playwright allows developers to better simulate actual user behavior in their automated tests.

**4. Flexibility for Developers:** These methods provide more flexibility when writing automation scripts, especially for those dealing with dynamic layouts or applications designed for different screen sizes.

Overall, these features will make Playwright a more robust and versatile tool, meeting the needs of a wider range of use cases.

**Comment by dgozman** [comment]
@mostafakavand Thank you for the kind words and for filing this issue!

We've seen such a request before, and most users actually need to set a large viewport instead of maximizing the window. See [viewport emulation](https://playwright.dev/docs/emulation#viewport) in the docs. This gives you predictable page viewport that is independent from the display of the machine you are running the tests on. Predictable behavior helps a lot with local debugging vs CI, because it makes sure that tests are running in as close environment as possible.

I haven't seen requests for minimizing the window, and I struggle to come up with an automated test that would require this functionality. Any specific ideas?

Overall, could you please share a real example of a test that would use the maximize/minimize feature, and that will not pass if we just remove the maximize/minimize call? Since this feature is not available today in Playwright, an example of a test using a different library, e.g. Selenium, would also work. Without a clear example we cannot prioritize and design this feature to serve our users in the best way. Thank you!

**Comment by mostafakavand** [comment]
Hi @dgozman ,  

First of all, I want to sincerely thank you for your thoughtful consideration of my feature suggestion and the meticulous approach you take when evaluating enhancements to Playwright. It's inspiring to see how deeply you care about balancing the library’s simplicity with its robustness, and I genuinely appreciate the opportunity to engage with such a dedicated team.  

---

### Why Minimize and Maximize Matter  

While I understand that not every feature request aligns with the broader goals of Playwright, I believe adding **minimize** and **maximize** capabilities could open up new possibilities for testing scenarios that are currently difficult or even impossible to automate. Let me share a specific use case where these capabilities become crucial.  

#### Real-World Example: Testing Web Apps Like Google Meet  

Consider a scenario where you are testing a web application such as **Google Meet** or **Microsoft Teams**. These apps behave differently depending on the window state:  

1. **When Minimized**:  
   - Notifications for events like incoming calls need to be displayed in the system tray, as the user is no longer actively viewing the application.  

2. **When Maximized**:  
   - The app should present the full-featured user interface, ensuring all elements are displayed properly and interactable.  

Without **minimize** and **maximize** capabilities, replicating these user interactions requires either manual testing or complex and unreliable workarounds.  

---

### Code Example  

Here’s a small example to demonstrate the importance of these features:  

```python
from playwright.sync_api import sync_playwright

def test_window_behavior():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        page = browser.new_page()
        
        # Open the web application
        page.goto("https://example.com/web-app")

        # Simulate maximize
        page.context.browser.maximize_window()
        # Verify behavior in maximize state
        assert page.locator("#fullscreen-element").is_visible()

        # Simulate minimize
        page.context.browser.minimize_window()
        # Verify system notification in minimize state
        assert check_system_notification("Incoming Call")

        browser.close()
```

This script demonstrates how automating window state changes can ensure reliable testing of features like UI responsiveness and system notifications. Without **maximize** and **minimize**, achieving the same results would involve manually resizing windows or relying on imprecise adjustments.  

---

### Why It Matters for Playwright  

Adding these capabilities would:  
- Empower developers to test applications with window-state-dependent behaviors more efficiently.  
- Reduce the need for manual intervention, aligning with Playwright's goal of reliable automation.  
- Strengthen Playwright's position as a versatile tool for a wider range of real-world testing scenarios.  

---

I hope this example demonstrates the value these features could bring. Of course, I’m happy to provide further insights or collaborate more closely if needed. I genuinely admire the work you and your team are doing, and I’d love to contribute in any way I can to help Playwright continue to excel.  

Looking forward to hearing your thoughts!  

Best regards,  
Mostafa Kavand

**Comment by mostafakavand** [comment]
Hi @dgozman ,  

Thank you for your detailed response and for pointing me towards the viewport emulation feature. I completely agree that predictable environments between local debugging and CI are crucial for reliable test automation, and I appreciate the thoughtful design behind this approach in Playwright.  

Regarding your request for a real-world example, here’s a scenario that I believe highlights the necessity of **maximize** and **minimize** capabilities:  

---

### Use Case: Testing Behavior in Window States  

Consider an application like **Google Meet** or **Microsoft Teams**:  
- In a **minimized** state, these applications trigger system-level notifications for events such as incoming calls or messages. This is critical because the user is no longer actively engaging with the application. Testing this behavior programmatically is essential for ensuring a seamless user experience.  
- In a **maximized** state, the application must display a full-featured UI, ensuring all elements are rendered and interactable without truncation or overflow.  

Viewport resizing is certainly helpful in many cases, but it doesn’t account for state-specific functionalities tied to the browser window’s visibility (e.g., minimized to taskbar).  

---

### Why Minimize Matters  

While maximizing might overlap with large viewport emulation, minimizing tests whether the application correctly transitions into a background state. Without this, testing behaviors like notifications, state persistence, or CPU throttling during minimized states would be incomplete.  

---

### Real-World Test Example  

Here’s an example of a test that would fail without minimize/maximize functionality:  

```python
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options

# Using Selenium for demonstration, as Playwright lacks minimize/maximize capabilities
options = Options()
service = Service(executable_path="path_to_chromedriver")

driver = webdriver.Chrome(service=service, options=options)
driver.get("https://example.com/web-app")

# Maximize window
driver.maximize_window()
assert driver.find_element_by_id("fullscreen-element").is_displayed()

# Minimize window
driver.minimize_window()
# Verify system-level notification appears
assert check_system_notification("Incoming Call")

driver.quit()
```

In this example:  
- The maximize step ensures the UI adapts to full-screen mode, showing all elements correctly.  
- The minimize step verifies that a system notification is triggered, as expected, when the application loses focus.  

These behaviors are not tied to viewport size but rather to the browser window’s state, which makes them impossible to test effectively without dedicated methods like `maximize_window` and `minimize_window`.  

---

### Why This Matters  

Introducing these capabilities would:  
1. Enable developers to test state-dependent features that go beyond viewport size (e.g., notifications, background behaviors).  
2. Expand Playwright’s utility for testing real-world applications that rely on window state changes.  
3. Ensure compatibility with existing tests written in other frameworks, easing migration to Playwright.  

---

I hope this example clarifies the value these features could bring to Playwright. I’d be happy to collaborate further or provide additional insights if needed. Please let me know how I can assist!  

Best regards,  
Mostafa Kavand

**Comment by dgozman** [comment]
@mostafakavand Thank you for the explanation. Please see my replies below, and let me know what you think.

Re: minimizing scenario. I see the usecase now, thank you. However, Playwright makes all windows/tabs/pages always focused to avoid tabs backgrounding, because that simplifies most testing scenarios. Issue #3570 is tracking the request to selectively disable this behavior. I think that should cover things like testing a notification from an invisible window that you are talking about.

From the API point of view, making this into an actual "minimized" window has downsides, so perhaps some kind of moving to "background" would work. Anyway, let's track this in #3570.

---

Re: maximize. Looking at your example, it tries to test some kind of "fullscreen-element". There are two possibilities here:
- Some element on the page went fullscreen, like a video player goes fullscreen on many pages. This is tracked in #1086 and #27598.
- You just want to test responsive layout, meaning there is a large element that is visible on very large viewports. In this case, setting the viewport is what you want.

Note that neither of the scenarios above require a "maximized" window. In fact, maximizing my Chrome window manually just resizes it to fit the screen size. As I explained earlier, this is not predictable between different computers, so Playwright is hesitant exposing such an API - you would be much better served by a large fixed viewport.

---

> Real-World Test Example

I looked at this example. Unfortunately, there is no "#fullscreen-element" on https://example.com/web-app. Similarly, this page does not produce a notification "Incoming Call". When I asked for a real-world example, I meant an actual example that works, not a hypothetical test script. Having a concrete scenario is a huge help in making a feature proposal into an actual feature.

**Comment by mostafakavand** [comment]
@dgozman Thank you so much for your detailed and insightful responses. After reviewing your feedback and reflecting on the use cases mentioned, I now understand that the maximize/minimize feature is not as essential for my current use case. The large viewport approach indeed offers more predictable behavior, and I truly appreciate the explanation.

I believe it would be best to close this issue for now, but please feel free to reach out if you need further clarification or if there’s anything else I can help with. I'm always happy to contribute when there’s an opportunity to improve the project, whether through smaller enhancements or other areas that might require attention.

Thank you again for your time and attention. I look forward to any potential future collaboration.

**Comment by dgozman** [comment]
@mostafakavand Thank you for your response. I agree that it's best to close this issue, in favor of #3570 for minimize scenarios, and #1086 for fullscreen.

> I look forward to any potential future collaboration.

That would be great, looking forward to it! For starters, we recommend to look for an issue labelled "open-to-a-pull-request" and see whether you'd like to contribute a PR.
