### ISSUE TITLE
Is there a way to use Playwright Python to interact with an existing Google Chrome browser and specify a TABID?

### ISSUE THREAD

**Issue by Xiaomajohn** [microsoft/playwright#34148]
### Please do not submit this issue.

- [ ] I understand

**Comment by dgozman** [comment]
This issue tracker is reserved for bug reports and feature requests.

For anything else, such as questions or getting help, please see:
- [The Playwright documentation](https://playwright.dev/)
- [Our Discord server](https://aka.ms/playwright/discord)
