### ISSUE TITLE
[Question] How to debug playwright-core?

### ISSUE THREAD

**Issue by killaragorn** [microsoft/playwright#34142]
Hello everyone,

I have read all available materials including Playwright documentation and shared documents, but I haven't found any information about how to debug playwright-core code.

I want to understand Playwright's internal implementation, and I've discovered that all core functionality is implemented in playwright-core. To better understand Playwright's logic, I would like to debug the related code. Can anyone help me with this?

**Comment by dgozman** [comment]
@killaragorn Please follow the [CONTRIBUTING.md](https://github.com/microsoft/playwright/blob/main/CONTRIBUTING.md). You can debug Playwright code with any Node.js debugger of your choice. We often use [JavaScript Debug Terminal in VSCode](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_javascript-debug-terminal) for this.

**Comment by dgozman** [comment]
> However, I still have a question: when running tests through the VSCode test panel, VSCode automatically starts playwright-core with the run-server command line. Is there a way to attach to this server?

There is no easy way to do this, sorry.
