### ISSUE TITLE
[Bug]: deviceScaleFactor is not working in library mode

### ISSUE THREAD

**Issue by sevenc-nanashi** [microsoft/playwright#34140]
### Version

1.49.1

### Steps to reproduce

1. Install `playwright` and `@playwright/browser-googlechrome`
2. Run this snippet:

```ts
import playwright from "playwright";

const browser = await playwright.chromium.launch({
  headless: false,
});
const context = await browser.newContext({
  viewport: { width: 1280, height: 720 },
  deviceScaleFactor: 2,
});
const page = await context.newPage();

await page.goto("https://example.com");

await page.waitForTimeout(60000);

await browser.close();
```

### Expected behavior

The page is zoomed.

### Actual behavior

The page is not zoomed.

<details>
<summary>With DPR 1:</summary>

![Image](https://github.com/user-attachments/assets/7fb6b149-074b-4ada-bc65-2e2cb1b75c92)

</details>

<details>
<summary>With DPR 2:</summary>

![Image](https://github.com/user-attachments/assets/fc4a0f3e-c371-4732-800f-71e13b3be238)

</details>

### Additional context

N/A

### Environment

```shell
❯ npx envinfo --preset playwright
  System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 1.52 GB / 7.76 GB
    Container: Yes
  Binaries:
    Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
    Yarn: 1.22.22 - ~/.bun/bin/yarn
    npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
    pnpm: 9.13.2 - ~/.bun/bin/pnpm
    bun: 1.1.40 - ~/.bun/bin/bun
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
  npmPackages:
    playwright: ^1.49.1 => 1.49.1 

(I used pnpm for package manager)
```

**Comment by pavelfeldman** [comment]
Your expectations are off, deviceScaleFactor is not about zoom, if is about how many physical pixels device uses for one logical pixel.

**Comment by sevenc-nanashi** [comment]
Thanks for the info.

btw, I tried using presets, like this:
```ts
const page = await browser.newPage({
  ...playwright.devices["iPhone SE landscape"],
})
```

But it was only to render a huge screen...

**Comment by pavelfeldman** [comment]
Correct, Playwright does not support zoom. Also when it comes to mobile devices, they don't use zoom - they use scale which we also don't support.
