### ISSUE TITLE
[Bug]: getByText only returns matching child, although parent matches itself

### ISSUE THREAD

**Issue by fnetX** [microsoft/playwright#34152]
### Version

Version 1.49.1

### Steps to reproduce

- create HTML structure with a p element (containing a certain text), which also contains another (e.g. a element) with the same text
- use `page.getByText('certain text')` and check its output

### Expected behavior

Either

- see a match for the outer p element

or

- see a match for
  - the outer p element
  - the inner a element

### Actual behavior

There is only a match for the inner a element. `p` is never matched.

### Additional context

Reproducer uploaded to https://codeberg.org/fnetX/reproducer-playwright-get-by-text

In the example, I replace the text. As you can see, only the text in the inner (`a`) is replaced, the outer element is not touched and only matched in a subsequent call to the locator.

### Environment

```shell
System:
    OS: Linux 6.1 LMDE 6 (faye) 6 (faye)
    CPU: (4) x64 Intel(R) Core(TM) i5-3340 CPU @ 3.10GHz
    Memory: 2.17 GB / 7.65 GB
    Container: Yes
  Binaries:
    Node: 20.18.1 - /usr/bin/node
    npm: 10.8.2 - /usr/bin/npm
    pnpm: 9.14.2 - /usr/bin/pnpm
  Languages:
    Bash: 5.2.15 - /usr/bin/bash
  npmPackages:
    @playwright/test: ^1.49.1 => 1.49.1
```

**Comment by yury-s** [comment]
This is working as intended, playwright currently returns innermost element in the parent chain which contains given text. The result is the same for `<p>Outer matching element<a href='#'>with an inner matching element</a></p>` and `<p><a href='#'>with an inner matching element</a></p>` (in both cases both `<p>` and `<a>` contain text 'matching'). If you want to select outer element, you should refine your selector, e.g.:

```ts
test('test', async ({ page }) => {
  await page.setContent("<!doctype html><html><main><p>Outer matching element<a href='#'>with an inner matching element</a></p></main></html>");  
  await expect(page.getByText('matching')).toHaveText('with an inner matching element');
  await expect(page.locator('p', { hasText: 'matching'})).toHaveText('Outer matching elementwith an inner matching element');
});
```

**Comment by fnetX** [comment]
Thank you for the response.

For me, it is not possible to adjust the selectors. The use case is replacing certain elements on the page for mocking (dynamic content, mostly). I see no simple way to get a list of elements that need to be replaced.

Is there any documentation on the design for this? I find the expected design confusing and unintuitive, but maybe there is documentation that explains the design decisions for this behaviour? I would expect the list of elements containing a certain content to provide a covering set.

**Comment by yury-s** [comment]
>  The use case is replacing certain elements on the page for mocking (dynamic content, mostly). I see no simple way to get a list of elements that need to be replaced.

In your case, you can replace matching elements and then repeat the operation to see if there are new matches and replace again if needed.
