### ISSUE TITLE
what is the requirements for system?

### ISSUE THREAD

**Issue by LinXin04** [microsoft/playwright#34151]
Is the setting of System OK for playwight?
Operating System: Linux
OS Release: 4.19.91-014.15-kangaroo.alios7.x86_64
OS Version: #1 SMP Thu Aug 29 16:01:12 CST 2024
Detailed Info: Linux-4.19.91-014.15-kangaroo.alios7.x86_64-x86_64-with-glibc2.34
Uname Info: uname_result(system='Linux', node='kmaker-54-011064071091', release='4.19.91-014.15-kangaroo.alios7.x86_64', version='#1 SMP Thu Aug 29 16:01:12 CST 2024', machine='x86_64')
Processor: 
Architecture: ('64bit', 'ELF')

**Comment by dgozman** [comment]
Please see the [system requirements](https://playwright.dev/docs/intro#system-requirements) in the docs.
