### ISSUE TITLE
[Docs]: specify that playwright does not support negation in url matching glob patterns

### ISSUE THREAD

**Issue by tallcoleman** [microsoft/playwright#34162]
### Page(s)

Page to be updated: https://playwright.dev/docs/network#glob-url-patterns

Other pages where it may be worth considering a link to the page above or other documentation on what glob patterns are supported:

- https://playwright.dev/docs/api/class-page#page-route
- https://playwright.dev/docs/api/class-page#page-wait-for-response
- https://playwright.dev/docs/api/class-browsercontext#browser-context-route

### Description

Glob patterns used in playwright methods (e.g. `page.route`) do not appear to support negation. For example:

```ts
// goal: abort all routes except for localhost

// does not work
await context.route('http?(s)://!(localhost)**/**', route => route.abort());

// negation in regex does work with negative lookahead
await context.route(/https?:\/\/(?!localhost).+/, route => route.abort());
```

Suggested change would be to add a line on [Network: Glob URL Patterns](https://playwright.dev/docs/network#glob-url-patterns), e.g. under "Important notes" to state something like "The negation operator (`!`) is not currently supported" or "Operators not noted above, such as the negation operator (`!`) may not be supported"

However, I'm not 100% confident that the issue isn't just that I don't know how to use glob properly, so it would be helpful for someone to confirm that negation is not currently supported before any doc updates.

Thanks!

**Comment by Skn0tt** [comment]
Thanks for opening the issue! The linked docs page already states that these patterns support a *simplified* glob pattern, and explicitly lists all supported operators. The negation operator is not one of them. In the interest of overloading the page, I don't think we'll explicitly list what's not supported.
