### ISSUE TITLE
[Bug]: Slow Page Loading and Infinite Spinner in Playwright

### ISSUE THREAD

**Issue by ALIMURTAZAAMJ** [microsoft/playwright#34164]
### Version

v1.49.1

### Steps to reproduce

I am experiencing issues with Playwright where certain websites, particularly those with ads, are loading much slower than in a normal browser. On some websites, the page appears to load, but the ads do not display, and the site spinner keeps spinning indefinitely (even after 30 minutes).

`
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch_persistent_context(
        user_data_dir=user_data_dir,
        headless=False,
        proxy=Play_proxy,
        user_agent=user_agent,
        locale="en-US",
        timezone_id=timezone,
        viewport={"width": width, "height": height},
        device_scale_factor=3,
        is_mobile=True,
        has_touch=True  # Enable touch events
    )
    page = browser.pages[0]
    page.add_init_script(spoofing_script)
    page.goto("https://ip-score.com", timeout=60000)
    page.wait_for_timeout(5000)
`

### Expected behavior

The website should load as quickly as in a standard browser.
Ads should load, and the spinner should stop once the page has loaded.

### Actual behavior

The unexpected behavior includes:

**Slow Loading Speeds:**

The website (https://ip-score.com) takes significantly longer to load in Playwright compared to a standard browser.
**Ads Not Loading:**

Websites with ads fail to load the advertisements.
**Infinite Loading Spinner:**

The page spinner does not stop, even after waiting for up to 30 minutes. The page appears partially loaded, but not fully functional.
**No Error Messages:**

No explicit error messages are displayed in the Playwright script or console.
Please let me know if additional debug logs or outputs are required.

### Additional context

I am using custom settings, including user agents, touch events, and proxy configurations.

### Environment

```shell
Playwright Version: [Provide version, e.g., v1.37.0]
Operating System: [e.g., Windows 10]
Browser: Chromium (persistent context)
Proxy: [Specify details if any, e.g., HTTP/HTTPS proxy with Play_proxy]
Custom User-Agent: [Provide details if applicable]
```

**Comment by Skn0tt** [comment]
Sounds like the page tries to prevent scraping, not a bug in Playwright. If you think you've found a bug within Playwright, please open another issue with a self-contained repro.
