### ISSUE TITLE
[Bug]: `performance.measureUserAgentSpecificMemory` fails in chromium's new headless mode

### ISSUE THREAD

**Issue by GermanJablo** [microsoft/playwright#34163]
### Version

1.49.1

### Steps to reproduce

1. Clone my repo at https://github.com/GermanJablo/measureUserAgentSpecificMemory
2. pnpm install
3. pnpm test

### Expected behavior

No error

### Actual behavior

Error: page.evaluate: TypeError: performance.measureUserAgentSpecificMemory is not a function

### Additional context

According to https://github.com/krausest/js-framework-benchmark/issues/1050#issuecomment-1176862401 and https://github.com/microsoft/playwright/issues/27499, Chromium's new headless mode allows `performance.measureUserAgentSpecificMemory` to be run.

I looked [in the first repository and found](https://github.com/krausest/js-framework-benchmark/blob/master/webdriver-ts/src/forkedBenchmarkRunnerPlaywright.ts#L198) that the way to use it is inside a page.evaluate like this:

`await page.evaluate("performance.measureUserAgentSpecificMemory()")`.

I tried enabling the new headless mode as explained from version 1.49 [in the documentation](https://playwright.dev/docs/browsers#opt-in-to-new-headless-mode):

```js
projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], channel: 'chromium' },
    },
  ],
```

And also as it was done before version 1.49:

```js
projects: [
    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
        launchOptions: {
          ignoreDefaultArgs: ["--headless", "--headless=old"],
          args: ["--headless=new"],
        },
      },
    },
  ],
```

But I still get the error.

### Environment

```shell
System:
    OS: macOS 14.4
    CPU: (12) arm64 Apple M3 Pro
    Memory: 64.44 MB / 18.00 GB
  Binaries:
    Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
    pnpm: 9.12.3 - ~/.nvm/versions/node/v22.11.0/bin/pnpm
  IDEs:
    VSCode: 0.44.9 - /usr/local/bin/code
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    @playwright/test: 1.49.1 => 1.49.1
```

**Comment by GermanJablo** [comment]
Thanks, but isn't localhost supposed to be a secure context?
Could you tell me how I can use that API in Playwright? Based on the 2 issues I linked it seems like it should be possible.

**Comment by GermanJablo** [comment]
I'm having trouble using `performance.measureUserAgentSpecificMemory` in Playwright. I've opened an issue here: https://github.com/microsoft/playwright/issues/34163#issuecomment-2565182617 Can anyone help me figure out what I'm doing wrong?

Also, what would be the recommended way to measure memory usage in Safari and Firefox?

**Comment by Skn0tt** [comment]
The way you're calling it from inside Playwright works, but you need to make sure that the security prerequisites from that linked MDN article are there. Even if localhost were a secure context (not sure about that!), your repro doesn't contain `page.goto("https://localhost:...)`.

**Comment by GermanJablo** [comment]
Thanks for the reply. I updated my repo. I'm serving a page with vite and doing a `goto` to localhost. Still not working :/

**Comment by jsangmeister** [comment]
In case anyone else stumbles upon this, you'll have to add `channel: "chromium"` to your test's `use` section or otherwise playwright will use the "old" standalone headless chrome binary which seemingly does not support the `measureUserAgentSpecificMemory` method.
