### ISSUE TITLE
[Feature] Actionability: Enabled check for Hover action

### ISSUE THREAD

**Issue by DJ-Glock** [microsoft/playwright#3437]
From the Slack thread:
By default pw checks that element is visible, enabled and not moving. All three checks make sense for click, but not for hover action.
I have a button that could be disabled until user enters a comment. And while it’s disabled, tooltip should appear when user hovers over this button (see the attached image).
If I use hover with default parameters (like I did with Puppeteer), it will fail when timed out:
```
2020-08-13 11:44:02.608 UTC [16564]:  api:info attempting hover action
2020-08-13 11:44:02.608 UTC [16564]:  api:info   waiting for element to be visible, enabled and not moving
2020-08-13 11:44:02.635 UTC [16564]:  api:info     element is disabled - waiting...
2020-08-13 11:44:32.586 UTC [16564]:  api:info <= page.hover failed
```
You will probably say: “Denis, use the force”.  And I will do, but using force flag can cause another issue - hover will be executed even if the element is hidden.
Why don’t you remove waiting for the element to be enabled by default or add some option to not to check element state?
![image](https://user-images.githubusercontent.com/26511191/90155227-bf70e780-dd93-11ea-9534-9f52f2c81dc9.png)

Pavel Feldman  1 hour ago
Makes sense to me

Pavel Feldman  1 hour ago
You can force: true today, but maybe we can skip the enabled check.

**Comment by DJ-Glock** [comment]
@dgozman I just hope that you won't forget to change docs accordingly https://playwright.dev/#version=v1.3.0&path=docs%2Factionability.md&q=

**Comment by dgozman** [comment]
Nice catch!
