### ISSUE TITLE
[Question] chromium tabs don't share cookies?

### ISSUE THREAD

**Issue by DemGiran** [microsoft/playwright#3461]
Say I have the following snippet:

let browser = await playwright.chromium.launch(...);
let context = await playwright.newContext();
let page_1 = await context.newPage();
let page_2 = await context.newPage();
await page_1.goto(...);
await page_2.goto(...);

tabs page_1 and page_2 donnot share cookies? is this by design or perchaps im doing something wrong

**Comment by pavelfeldman** [comment]
Pages within the context share cookies. Let us know if you have a scenario that does not work.
