### ISSUE TITLE
[Feature] Fill input field based on label text

### ISSUE THREAD

**Issue by torkjels** [microsoft/playwright#3466]
When an input field is properly connected to a label it would be nice to be able to fill the input field based on the label text using `await page.fill('text=Name', 'John Doe');`.

It's often possible to fill the input field based on a CSS selector like `id` or `name`, but making it possible to fill by label text would make it more straight-forward to both read and write the test. Especially if you write tests for screens you did not make yourself.

Examples of cases where it should work:
```
<label for="input1">Name</label>
<input id="input1" value="">
```

```
<label>Name <input value=""></label>

```

**Comment by Snooz82** [comment]
i think in general `label=` could be a nice selector strategy.
I would feel comfortable to mix it with general Text selector, because then it would be possible anymore to select the <label> tag itself with the "Text" selector.

i would also not limit it to <input> fields!
Labels can be used on:
```
<input>
<meter>
<progress>
<select>
<textarea>
```
