### ISSUE TITLE
[Bug] Firefox DevTools are not opened

### ISSUE THREAD

**Issue by sunaram** [microsoft/playwright#3470]
I am using node v12.16.1, playwright 1.3.0 and firefox 79.
After launching Firefox, I can't launch "developer toolbox" window after clicking on "inspect element" on any webpage. It simply shows some css selectors for a few of the elements on the page.
What could be the issue?

**Comment by pavlealeksic** [comment]
After clicking the inspect element, increase height of the window and you will see the console

**Comment by dgozman** [comment]
@aslushnikov I hit the same issue today. Had to resize the window to see some DevTools. Should we force Firefox DevTools open undocked?

**Comment by mxschmitt** [comment]
I did experience the same issue on macOS with 1.3.0. The DevTools seem to be launched (see the elements highlighted on the page) but can't see the full DevTools.
