### ISSUE TITLE
cannot open https://playwright.dev

### ISSUE THREAD

**Issue by nonew** [microsoft/playwright#3495]
I tried with both Chrome and Edge, but cannot open docs from https://playwright.dev. it show me blank page, I cannot search anything.
![image](https://user-images.githubusercontent.com/6738220/90346004-10186700-e058-11ea-8831-f888fedca41d.png)

I have to open this page: https://github.com/microsoft/playwright/blob/master/docs/api.md#class-page

**Comment by mxschmitt** [comment]
#3318 should fix it, happens randomly currently.
