### ISSUE TITLE
[Feature] Deploy drivers to CDN

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#3503]
Context: RPC clients need to have the driver to use Playwright. Currently they build it themselves. To simplify that for new languages we would provide the driver on the CDN so the RPC clients do not have to embed it into their packages and can download it on-demand.

The driver was added in #3500 and it relates to https://github.com/microsoft/playwright-python/issues/140.

As discussed with @aslushnikov.

**Comment by pavelfeldman** [comment]
They are now there!
