### ISSUE TITLE
[BUG] Fullscreen of videos goes to browser's full screen rather than window full screen

### ISSUE THREAD

**Issue by VikramTiwari** [microsoft/playwright#3511]
**Context:**
- Playwright Version: 1.3.0
- Operating System: Mac
- Node.js version: ~12
- Browser: Chromium

**Code Snippet**

```javascript
const { chromium } = require("playwright");

(async () => {
	const context = await chromium.launchPersistentContext(`./udd`, {
		headless: false,
		viewport: null,
	});
	const page = await context.newPage();
	await page.goto("https://youtube.com/");
})();

```

**Describe the bug**
- On youtube page, click on any video and try to make it go full screen.
- Expected behavior would be that the video goes completely full screen, but what we see is that the video size is limited to the browser's window size.

I thought maybe viewport was the issue here but setting that to null didn't solve the problem either. Is this some permission that needs to be set?

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.

**Comment by shingz96** [comment]
having the same issue where as when try to fullscreen the video, it only full screen until the browser window but not the entire screen

![image](https://user-images.githubusercontent.com/14905938/209655767-4bf748c4-ca8e-422d-b00b-5b1b7c9285d9.png)
