### ISSUE TITLE
[Question] Click on button and get json response and save it in var

### ISSUE THREAD

**Issue by osmenia** [microsoft/playwright#3527]
Hello Team,

There is one button, i can click on buton then in browser will be created a table with data.

In Chrome Network after click on button i can see two requerst: 
Name: Column Method: GET
Name: DBGroup Method: Post

and response of post request  is data in json format.

Is it possible to click on button, and get json response and save it in variable?

i tried this but did not work:

```
var response = await page.click("#Button_0_label");
console.log(response );
```

Message: undefined

thanks a lot

**Comment by arjun27** [comment]
You can use the `response` event on the page and get a [Response object](https://playwright.dev/#version=v1.3.0&path=docs%2Fapi.md&q=class-response), which has the response body. Docs for [page.waitForEvent](https://playwright.dev/#version=v1.3.0&path=docs%2Fapi.md&q=pagewaitforeventevent-optionsorpredicate).

```js
// wait for specific request
const response = await page.waitForEvent('response', response => response.url().includes('DBGroup'));
const responseBody = await response.json();
```

**Comment by osmenia** [comment]
thank you very much
