### ISSUE TITLE
[Feature] Additions to docker instance?

### ISSUE THREAD

**Issue by Westbrook** [microsoft/playwright#3529]
I'm attempting to use Playwright with CircleCI and when doing a `checkout` I get the following warning:
```
Either git or ssh (required by git to clone through SSH) is not installed in the image. Falling back to CircleCI's native git client but the behavior may be different from official git. If this is an issue, please use an image that has official git and ssh installed.
```
I later get a message about `yarn` not being available as well.

Would it be possible to add these to the image?

**Comment by aslushnikov** [comment]
> Would it be possible to add these to the image?

@Westbrook For sure!
