### ISSUE TITLE
[Feature] Lazy loaded frames API

### ISSUE THREAD

**Issue by jperl** [microsoft/playwright#3540]
Let us know what functionality you'd like to see in Playwright and what is your use case:

To create a test with an iframe that causes the page to reload, you need to re-reference the frame per reload.

```
  await page.goto("http://printingforless.com/");
  const frame = await (
    await page.waitForSelector("#footerFrame")
  ).contentFrame();
  await frame.click("text=Announcements");
  const frame2 = await (
    await page.waitForSelector("#footerFrame")
  ).contentFrame();
  await frame2.click("text=Booklets");
  const frame3 = await (
    await page.waitForSelector("#footerFrame")
  ).contentFrame();
  await frame3.click("text=Calendars");
```

It would be nice to have the frame lazy loaded instead:

```
  await page.goto("http://printingforless.com/");
  const frame = await page.lazyContentFrame("#footerFrame");
  await frame.click("text=Announcements");
  await frame.click("text=Booklets");
  await frame.click("text=Calendars");
```

**Comment by pavelfeldman** [comment]
First of all, thank you for filing this issue. We appreciate your input, in many ways Playwright is based on it. This particular feature request didn't get enough stars for us to prioritize the work on it and hence is being closed. We are a relatively small team and we need to prioritize aggressively to deliver support and new features to you.

**Comment by TimeInvestor** [comment]
I would hope Playwright could let me decleare a frame like locator (looks like such behaviour is called lazy load).
This is a very nice feature for Page Object Model when every page like in my case has an iframe (which holds the main content of the page) to deal with. So that I can declare an `frame` object for the iframe in the constructor of a Page Object class. Use the `frame` object to initialize `Locators` within the iframe.

Sample code would look like this:
```typescript
import { Frame, Locator, Page } from '@playwright/test';

export default class AccountPage {
  readonly page: Page;
  readonly contentFrame: Frame;
  // Locators within the content iframe
  readonly addBtn: Locator;
  readonly listBtn: Locator;

  constructor(page: Page) {
    this.page = page;
    this.contentFrame = page.lazyFrame('#content_frame');
    // Initialize locators within the content iframe
    this.addBtn = this.contentFrame.locator('#add');
    this.listBtn = this.contentFrame.locator('.list_all');
  }
}
```

**Comment by dgozman** [comment]
@TimeInvestor Great proposal! We are thinking along these lines, see #7982.
