### ISSUE TITLE
[Question] First-class test runner support

### ISSUE THREAD

**Issue by celeryclub** [microsoft/playwright#3552]
Hey team. I hope all is well. Thanks for all the great fixes recently. Things are feeling really solid.

I'm curious what the priority is for test runner support. I currently use [jest-playwright](https://github.com/playwright-community/jest-playwright), which is a great short-term solution to this issue. I'm aware of [playwright-runner](https://github.com/microsoft/playwright-runner) too, but it seems to be more of an experimental project rather than an official test runner integration.

Mind shedding some light on the status of this effort? Thanks!

**Comment by arjun27** [comment]
Hey @celeryclub! We are dogfooding the test runner integration on Playwright (this repo), and working on moving it to the playwright-runner repo for early adopters. Are you facing any issues/gaps with jest-playwright?

**Comment by celeryclub** [comment]
I see. That makes sense. jest-playwright is working pretty well for me - my main issue is around debugging tests. `jestPlaywright.debug()` doesn't work the way I'd expect it to. It'd also be great to have more features built in, like screenshots/videos on failure. I can certainly file these issues on that repo, but I was curious about the status of an official runner.

**Comment by pavelfeldman** [comment]
@celeryclub we will move the local test runner into the playwright-runner repo shortly. Could you share more details on you debug requirements/expectations?

**Comment by dgozman** [comment]
We are addressing this with [playwright-test](https://github.com/microsoft/playwright-test).
