### ISSUE TITLE
[Question]Skip Screenshots on Playwright

### ISSUE THREAD

**Issue by Sreejithw** [microsoft/playwright#3559]
Hi,

Is there a way to skip all screenshot methods in a test file/make it optional?

**Comment by aslushnikov** [comment]
> Is there a way to skip all screenshot methods in a test file/make it optional?

I'd recommend wrapping all screenshot calls in a function that will take screenshots depending on some other state:

```js
function maybeScreenshot(page, screenshotPath) {
  if (GLOBAL_CONDITION)
    await page.screenshot({path: screenshotPath});
}
```

Alternatively, you can re-write screenshot method on the page object:

```js
// rewrite screenshot method
page.screenshot = () => {}
// all subsequent calls to `page.screenshot` will be noop
await page.screenshot({path: './foo.png']);
```
