### ISSUE TITLE
How can I set calendar date and timestamp?

### ISSUE THREAD

**Issue by byteshiva** [microsoft/playwright#3578]
How do I set or pick calendar date and set time stamp using playwright?

Example given in the image.

![image](https://user-images.githubusercontent.com/10637299/90957045-115af100-e4a9-11ea-9d3e-710d3922c572.png)

**Comment by byteshiva** [comment]
> Those should be basically writeable input elements, so with just doing page.type('#dateinputidorselector','16111990') and same for time. But you need to find proper selectors for those fields(id, class, xpath...)

Thanks @pavlealeksic 

I think the selectors are not correct in my use-case. The code is listed below for reference. 

https://gist.github.com/byteshiva/cab5d4d06d78e8b3f24e4ebed2f2329e

**Comment by pavlealeksic** [comment]
Selectors are correct, and its made by puppeteer recorder i presume, you should be able just to add page.type below the clicks on the elements and you should be good

**Comment by byteshiva** [comment]
> Selectors are correct, and its made by puppeteer recorder i presume, you should be able just to add page.type below the clicks on the elements and you should be good

To my things simple, I've used  puppeteer recorder. But when I replace with page.type, it doesn't seems to work.

It's not replacing empty with values.

Let me revert with recreated fresh script with page.type

**Comment by mxschmitt** [comment]
`Page.type` does somehow not work, but `Page.fill` does. Here is an example:

```js
// @ts-check
const playwright = require("playwright");

(async () => {
  for (const browserType of ['chromium', 'firefox', 'webkit']) {
    /** @type {import('playwright').Browser} */
    const browser = await playwright[browserType].launch();
    const page = await browser.newPage();
    await page.setContent(`
      <input type="date" />
      <input type="time"/>
    `)
    await page.fill("[type=date]", "2000-05-25")
    await page.fill("[type=time]", "05:10")
    await page.screenshot({ path: `example-${browserType}.png` });
    await browser.close();
  }
})();
```

Interactive: https://try.playwright.tech/?s=xknjq

**Comment by byteshiva** [comment]
> `Page.type` does somehow not work, but `Page.fill` does. Here is an example:
> 
> ```js
> // @ts-check
> const playwright = require("playwright");
> 
> (async () => {
>   for (const browserType of ['chromium', 'firefox', 'webkit']) {
>     /** @type {import('playwright').Browser} */
>     const browser = await playwright[browserType].launch();
>     const page = await browser.newPage();
>     await page.setContent(`
>       <input type="date" />
>       <input type="time"/>
>     `)
>     await page.fill("[type=date]", "2000-05-25")
>     await page.fill("[type=time]", "05:10")
>     await page.screenshot({ path: `example-${browserType}.png` });
>     await browser.close();
>   }
> })();
> ```
> 
> Interactive: https://try.playwright.tech/?s=xknjq

It worked in my case. I have switched to playwright, Don't know the equivalent of page.fill in puppeteer. it works!

Here is the demo link, also noticed there is some issue with my selector query for date, to make it work i had to use (type=date)
. The type=number works fine.
https://try.playwright.tech/?s=yx2yi
