### ISSUE TITLE
[BUG] page.screenshot -> blank

### ISSUE THREAD

**Issue by osmenia** [microsoft/playwright#3601]
**Context:**
- Playwright Version: 1.3.0
- Operating System: Windows
- Node.js version: 12
- Browser: [All, Chromium, Firefox, WebKit]

**Code Snippet**

Hi Team,
Can you pls check this link:
```

https://try.playwright.tech/?s=bzs2g 

```

**Describe the bug**

Screenshot ist blank page.
it works very fine with plw Ver: 1.0.2,
is there any problem with page.screenshot?

tnx a lot

**Comment by mxschmitt** [comment]
[Page.goto](https://playwright.dev/#version=v1.3.0&path=docs%2Fapi.md&q=pagegotourl-options) normally waits until the [load event](https://developer.mozilla.org/en/docs/Web/Events/load) will get fired. The site which you are trying to navigate to does a few requests after the load event was fired and then renders the full page. To wait until all the requests are done (a network idle for at least 500ms) you can modify your goto statement to that:

```js
    await page.goto('https://b2b.bmw.com/', {
      waitUntil: "networkidle"
    });
```

Or on Try Playwright: https://try.playwright.tech/?s=2mlmj

**Comment by osmenia** [comment]
I used also waitForSelector, and it works.

tnx a lot
