### ISSUE TITLE
[BUG] browserContext.cookies

### ISSUE THREAD

**Issue by aaronD1414** [microsoft/playwright#3640]
Hey,

I have problems with: [https://playwright.dev/#version=v1.3.0&path=docs%2Fapi.md&q=browsercontextcookiesurls](url)

Tried everything can't get this to work get the hole time, browserContext.cookies Is not a function

**Comment by mxschmitt** [comment]
Hi,
here you go with an example:
```
// @ts-check
const playwright = require("playwright");

(async () => {
  const browser = await playwright.chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://github.com');
  await page.screenshot({ path: `example.png` });

  const cookies = await context.cookies("https://github.com")
  console.log(JSON.stringify(cookies, null, 4))

  await browser.close();
})();
```

Interactive: https://try.playwright.tech/?s=07x8r

**Comment by aaronD1414** [comment]
Here my full code:

const path = require('path');
const {firefox} = require('playwright');
const webExt = require('web-ext');

(async () => {
	try {
		
		// Enable verbose logging and start capturing logs.
        webExt.util.logger.consoleStream.makeVerbose();
        webExt.util.logger.consoleStream.startCapturing();
		

        // Launch firefox
        const runner = await webExt.cmd.run({
			sourceDir: path.join(__dirname, 'webextension'),
            firefox: firefox.executablePath(),
	        args: [`-juggler=1234`],
	    }, {
			shouldExitProgram: false,
        });


        // Parse firefox logs and extract juggler endpoint.
        const JUGGLER_MESSAGE = `Juggler listening on`;
        const message = webExt.util.logger.consoleStream.capturedMessages.find(msg => msg.includes(JUGGLER_MESSAGE));
        const wsEndpoint = message.split(JUGGLER_MESSAGE).pop();



        // Connect playwright and start driving browser.
        const browser = await firefox.connect({ wsEndpoint });
        const page = await browser.newPage();


        await page.addInitScript({
			path: 'evasions.js'
        });


        await page.addInitScript({
			path: 'index.js'
        });

		
        await page.goto('https://www.zalando.be/', { waitUntil: 'networkidle0' })
		
		
        const cookies = await page.cookies("https://www.zalando.be/")
        console.log(JSON.stringify(cookies, null, 4))
	
	    } catch (error) {
			console.log(error);
        }
})();

**Comment by aaronD1414** [comment]
I tried it like yours but get empty JSON string

        const browser = await firefox.connect({ wsEndpoint });
	    const context = await browser.newContext();
        const page = await context.newPage();


        await page.addInitScript({
			path: 'evasions.js'
        });


        await page.addInitScript({
			path: 'index.js'
        });

		
        await page.goto('https://www.zalando.be')
		
		
        const cookies = await context.cookies("https://www.zalando.be")
        console.log(cookies)
	
	    } catch (error) {
			console.log(error);
        }

**Comment by mxschmitt** [comment]
If you use `const cookies = await context.cookies("https://.zalando.be")` it would work. But I agree that this is not very user-friendly, I'll dig into it and see if we can improve it.

**Comment by aaronD1414** [comment]
on your example doesn't work either [https://try.playwright.tech/?s=09ayi](url)

**Comment by mxschmitt** [comment]
See here: https://try.playwright.tech/?s=1h4nc

Also its possible to not pass any URLs to make the filtering yourself: https://try.playwright.tech/?s=al6g8

**Comment by aaronD1414** [comment]
thx men you saved me lol
