### ISSUE TITLE
[Feature] Provide command args with Logger logs

### ISSUE THREAD

**Issue by celeryclub** [microsoft/playwright#3648]
Hey team! I'm using the `Logger` class to clean up some of my code as suggested by @aslushnikov in this thread https://github.com/microsoft/playwright/issues/1654.

It's working well for the most part, but I am having one issue. The `log` function signature looks like this `(name, severity, message, args)`, but I'm not seeing any args come through - the value of `args` is always `[]`.  If I run `page.click('.cool-selector')`, I'd expect `args` to be `['.cool-selector']`.

Is this the intended behavior of `Logger` or is it a bug? Thanks!

**Comment by dgozman** [comment]
Logger `args` are not strictly defined. I think we might as well provide api arguments for api calls.

**Comment by pavelfeldman** [comment]
First of all, thank you for filing this issue. We appreciate your input, in many ways Playwright is based on it. This particular feature request didn't get enough stars for us to prioritize the work on it and hence is being closed. We are a relatively small team and we need to prioritize aggressively to deliver support and new features to you.
