### ISSUE TITLE
[Question] Force CSS to "screen" for PDF

### ISSUE THREAD

**Issue by waynerobinson** [microsoft/playwright#3656]
Hi!

Is it possible to force the browser to generate its PDF in screen mode? 

This website I'm attempting to export as PDF has done some terrible, terrible things with it's print CSS and I'd like to disable all of it if possible.

**Comment by celeryclub** [comment]
One potential solution would be to block the print stylesheet from downloading.

`await page.route('url of print stylesheet', route => route.abort());`

**Comment by waynerobinson** [comment]
Unfortunately, in this case it’s a series of @media tags interspaced amongst the existing CSS. :-(

**Comment by arjun27** [comment]
@waynerobinson, you can use the `page.emulateMedia` API. [Docs for reference](https://playwright.dev/#version=v1.3.0&path=docs%2Fapi.md&q=pagepdfoptions).

```js
// Generates a PDF with 'screen' media type.
await page.emulateMedia({media: 'screen'});
await page.pdf({path: 'page.pdf'});
```
