### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by mashaBu** [microsoft/playwright#3669]
using example code:
  const jobsNav = await page.$("//a[@href='/jobs' and text()='Jobs']")

I do not get an ElementHandle I get Promise: {pending}

null or handle would make sense, exception would make sense -- pending promise does not.

I am seeing this with multiple different selectors but not consistently.

Please advise if I am committing some errant thing here or if this is a bug?

**Comment by arjun27** [comment]
hey @mashaBu, this is not expected behavior, since you are `await`ing the promise. Can you share a more complete code snippet for us to review? Thanks!

**Comment by mashaBu** [comment]
------------------------- test

beforeAll(async () => {
    browser = await chromium.launch({ headless: false });
    context = await browser.newContext();
});

beforeEach(async () => {
    page = await context.newPage();
});

 it.only("...", async () => {
      await page.goto(URLHomepageSF)
      const jobsNav = await page.$(//a[@href='/jobs' and text()='Jobs'])

      console.log(jobsNav.innerText());

      await expect(jobsNav).toBeInTheDocument();

-------------------- output
console.log
      Promise { <pending> }

received value must be an HTMLElement or an SVGElement.
    Received has type:  array
    Received has value: [{"_context": {"_delegate": {"_client": {"_callbacks": [Map], "_connection": [CRConnection], "_crashed": false, "_events": [Object], "_eventsCount": 29, "_maxListeners": undefined, "_rootSessionId": "", "_sessionId": "D09A54422792EFFA73E94195CC29EC9A", "_targetType": "page", "addListener":  ...

--------------------- html
...
<div data-v-2cd5276e="" class="menu">
  <div data-v-2cd5276e="" class="menu-link"><a data-v-bc34c296="" data-v-2cd5276e="" href="/jobs">Jobs</a></div>
  <div data-v-2cd5276e="" class="menu-link"><a data-v-bc34c296="" data-v-2cd5276e="" href="/companies">Startups</a></div>
 <div data-v-2cd5276e="" class="menu-link menu-link-events"><a data-v-bc34c296="" data-v-2cd5276e="" href="/events">Events</a></div>
 <div data-v-2cd5276e="" class="menu-link"><a data-v-bc34c296="" data-v-2cd5276e="" href="/blogs">News</a></div>
 <div data-v-2cd5276e="" class="menu-link"><a data-v-bc34c296="" data-v-2cd5276e="" href="/salaries">Salaries</a></div></div>

**Comment by arjun27** [comment]
Thanks for sharing.

1. The promise returned from `jobsNav.innerText()` is not awaited. `console.log(await jobsNav.innerText())` will return the inner text. [API reference](https://playwright.dev/#version=v1.3.0&path=docs%2Fapi.md&q=elementhandleinnertext).
2. I'm not aware of the `expect(...).toBeInTheDocument` API. Is this from an external dependency?

**Comment by mashaBu** [comment]
Ok, thanks, that explains the pending. I'll debug and see what's wrong in the rest of the test.
