### ISSUE TITLE
[Feature] Add ssh to docker image

### ISSUE THREAD

**Issue by Westbrook** [microsoft/playwright#3681]
Leveraging the Docker image in CircleCI, I'm running into issues fully leveraging `git` in the way that I had with previous images I had run my build on. In particular, being able to push changed to my `gh-pages` branch from CI. It looks like this is due to a lack of `ssh`, could we get that added to the image?

Separately, I'm not a very advanced user in this context, but is there a good way for me to overcome your use of `USER pwuser` in the build? It would allow for the use (maybe also the install) of `sudo` and other tools without getting blocked by the lock:
```
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
```
This would all for actually confirming what sort of things should be added to the build in order to leverage the image more successfully when running into issue like this.

**Comment by aslushnikov** [comment]
>  In particular, being able to push changed to my gh-pages branch from CI. It looks like this is due to a lack of ssh, could we get that added to the image?

@Westbrook I think this is because we didn't have git installed there; it's been added recently so should be available in the next release.

> Separately, I'm not a very advanced user in this context, but is there a good way for me to overcome your use of USER pwuser in the build? It would allow for the use (maybe also the install) of sudo and other tools without getting blocked by the lock:

Sounds reasonable, we'll enable password-less sudo for `pwuser` inside the docker image.

**Comment by Westbrook** [comment]
Hi @aslushnikov, thanks for your note! Very happy to have gotten the updates in #3651, this has already been very helpful via the `mcr.microsoft.com/playwright:next` tag. However, I still get issues with either `git` or `ssh` missing from the image when trying to checkout the code in CircleCI:
```
Either git or ssh (required by git to clone through SSH) is not installed in the image. Falling back to CircleCI's native git client but the behavior may be different from official git. If this is an issue, please use an image that has official git and ssh installed.
```
Even though other actions against git, e.g `git config --global user.email "circleci@adobe.com" && git config --global user.name "CircleCI"`, no longer trigger errors. This leads me to think the issue is in the lack of `ssh` or something more difficult for me to assess at this time. 

Is `ssh` available on the image, and I'm just missing something?

With the addition of `sudo` access I should definitely be able to dig deeper here and will report back what I find!

**Comment by Westbrook** [comment]
This is the specific error I get when attempting to push a specific folder to my `gh-pages` branch:
```
$ /home/pwuser/project/node_modules/.bin/gh-pages -d documentation/dist -m '[skip ci] update demonstration site'
Cloning into '/home/pwuser/project/node_modules/.cache/gh-pages/git@github.com!adobe!spectrum-web-components.git'...
fatal: unable to fork
```

**Comment by aslushnikov** [comment]
> However, I still get issues with either git or ssh missing from the image when trying to checkout the code in CircleCI:

@Westbrook ah, my bad! SSH is missing as well!

**Comment by Westbrook** [comment]
🙏 Thanks for getting into that!

No guarantees, but if that solves my CircleCI issue then the need for `sudo` _should_ go way down for me...I saw some early pushback on the PR for that.

**Comment by Westbrook** [comment]
Oooh, yes! That did the trick. 🔥🔥🔥🔥🔥🔥🔥 

I'm OK with not worrying about having `sudo`, for now... Other than a process slowdown that I haven't tracked down yet, this gets my use of Playwright fully caught up to where my project was before the conversion. Woot!
