### ISSUE TITLE
[BUG] proxy support for firefox?

### ISSUE THREAD

**Issue by aaronD1414** [microsoft/playwright#3690]
Hey,

So I can't seem to get http proxy working on firefox.
I tried https://playwright.dev/#version=v1.3.0&path=docs%2Fapi.md&q=browsertypelaunchoptions--options-proxy but only works In chrome.

I looked at the solutions here on this github for proxy support on firefox but didn't work either does anybody has a solution that works nowadays?

**Comment by mxschmitt** [comment]
The proxy integration should work without issues currently. I tried it myself, see here: https://try.playwright.tech/?s=dn6jm

Could you provide us a reproducible code snippet or did you receive an error message?

**Comment by aaronD1414** [comment]
ah Its something In my code that Is not right then, ty for helping
