### ISSUE TITLE
[BUG] RPC/Firefox goBack does not return a response (guid)

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#3693]
**Context:**
- Playwright Version: 3cc91093a1f73245c64c26e324ba4192dddb5dd9
- Operating System: macOS/Linux
- Node.js version: 12
- Browser: Firefox
- Scope: Playwright Python / Playwright Go / RPC clients

RPC response for all the browsers after executing Page.goBack:

```
// CR: RECV>{"id":7,"guid":"","method":"","params":null,"result":{"response":{"guid":"Response@231e838041ee4d319287bae674996b65"}},"error":null}
// FF: RECV>{"id":7,"guid":"","method":"","params":null,"result":{},"error":null}
// WK: RECV>{"id":7,"guid":"","method":"","params":null,"result":{"response":{"guid":"Response@70df6e01fce0e946812fc2ad67a46fc8"}},"error":null}
```

Expected: Firefox does return a response value in the result map like CR and WK are doing.

I tried to reproduce it with the upstream implementation in Playwright but was not able to. Thats the failing Playwright Python test: https://github.com/microsoft/playwright-python/pull/181

**Comment by mxschmitt** [comment]
It seems like it has todo with [`FrameManager.frameRequestedNavigation`](https://github.com/microsoft/playwright/blob/cd220daa839ab627f65032eb576e2a795e55a57f/src/server/frames.ts#L153) which gets called in FF but not in WK and CR.

**Comment by aslushnikov** [comment]
This seems to be working on current tip-of-tree; I tried with `page.goBack should work` test.

So closing!

**Comment by mxschmitt** [comment]
@aslushnikov sorry to reopen, issue is still reproducible, at least in version `1604019206789`. Was it fixed recently you think?

Also I experienced, that it was not reproducible in upstream Playwright, only in Python or Go e.g.

https://github.com/microsoft/playwright-python/pull/279/checks?check_run_id=1352140044

**Comment by aslushnikov** [comment]
for the record: we spent an hour with Max debugging this over zoom and turned out its an issue with python test server!
