### ISSUE TITLE
[Question] Passing a DOM element to an exposed function

### ISSUE THREAD

**Issue by lewisl9029** [microsoft/playwright#3695]
Hi playwright team!

I was wondering if it's possible to pass a DOM element to a function exposed through exposeFunction, or alternatively, maybe there's some way to create an ElementHandle from a DOM element on the page and then passing the handle to the exposed function?

Imagine a use case where JS on the page already obtained a reference to a DOM element through something like a [React Ref](https://reactjs.org/docs/refs-and-the-dom.html) (or any dynamically created & injected DOM node), and wants to use playwright to perform some action on that element (say clicking or screenshotting it) through a function injected using exposeFunction so the page can control the timing of that action. 

Adding an id or class to the element just so that we can re-select it after the fact using playwright selectors doesn't seem ideal since we already have an actual reference to the element itself, but that's what I'm doing so far to work around this. I wonder if I'm missing something obvious here.

Any pointers/ideas would be appreciated!

**Comment by pavelfeldman** [comment]
It'll just happen on its own. If you pass a DOM element into the exposed function on the web side, the binding will be called with the element handle on the Playwright side.

**Comment by lewisl9029** [comment]
@pavelfeldman Thanks for the quick follow up!

Hmm if it's supposed to work like that then I might be doing something wrong. I set up a quick repro of the behavior I've been seeing here: https://github.com/lewisl9029/playwright-expose-function-repro

You can run it by cloning and doing `yarn && yarn start` on node 14+. Basically, when I pass in the element to the exposed function I seem to get an empty object instead of a playwright handle on the playwright side: https://github.com/lewisl9029/playwright-expose-function-repro/blob/master/index.js#L8

In my own project that uses React, I also get an additional error that looks something like this: 

```
VM30:15 Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'HTMLButtonElement'
    |     property '__reactInternalInstance$jdtn80jveb' -> object with constructor 'FiberNode'
    --- property 'stateNode' closes the circle
    at JSON.stringify (<anonymous>)
    at window.<computed> (<anonymous>:15:22)
    at <anonymous>:1:1
```

Presumably because it's trying to serialize the element but fails due to the circular structure that react attached to it.

Any ideas what I can do to get this behaving as you described?

**Comment by pavelfeldman** [comment]
Ouch, thanks for the test. We are indeed accepting serialized value (json) rather than a serialized argument that can be a handle. Thanks for the report!

**Comment by dgozman** [comment]
Hmm... I can see how we can do this with a separate method `page.exposeBindingHandle`, but not with an existing one.

**Comment by benoitjchevalier** [comment]
I'd love that feature too
