### ISSUE TITLE
[Question] What is the best way to use "goto" in an application that uses long-polling?

### ISSUE THREAD

**Issue by jonathanheijmans** [microsoft/playwright#3705]
We would like to use the "networkidle" option in goto and other functions so that we don't have to add waitfor's for regular api requests. But that does not work with long polling, giving timeouts. So what is best practice for this?

**Comment by dgozman** [comment]
[Here](https://gist.github.com/dgozman/d1c46f966eb9854ee1fe24960b603b28) is a snippet that implements "network settled after action" semantic, that should account for long polling. If you give it a try, any feedback is welcome.
