### ISSUE TITLE
[Question] Why is an explicit npm install playwright needed?

### ISSUE THREAD

**Issue by umaar** [microsoft/playwright#3712]
Any ideas why [this](https://github.com/umaar/learn-browser-testing/blob/1084387b371010710c4c3ba3bdfa18f42260b2e0/.github/workflows/4-deploying-videos-simple.yaml#L29-L31) is needed explicitly?

E.g. this:

```sh
npm install && npm install playwright
```

Rather than [just](https://github.com/umaar/learn-browser-testing/blob/1084387b371010710c4c3ba3bdfa18f42260b2e0/package.json#L22) an `npm install`?

Without this workaround, I get the following error on GH actions:

```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error: browserType.launch: Failed to launch chromium because executable doesn't exist at /home/runner/.cache/ms-playwright/chromium-792639/chrome-linux/chrome
Try re-installing playwright with "npm install playwright"
```

**Comment by arjun27** [comment]
Hey @umaar, this is because NPM wouldn't run the `postinstall` hook, as the `node_modules` directory is cached. Did you consider caching the [npm-cache](https://docs.npmjs.com/cli-commands/cache.html) directory instead? We have other alternative approaches [documented here](https://playwright.dev/#version=v1.3.0&path=docs%2Fci.md&q=caching-browsers). Let me know if you have any other ideas – would love to make this more intuitive.

**Comment by umaar** [comment]
Thanks for the quick reply! That makes perfect sense and those documented approaches look good. Tbh I think the only other thing which could be useful is including the error messages on that page, so when people search for it through search engines, it shows up. But I guess the errors appear for unrelated reasons? 

In which case, if playwright could detect that the `postinstall` hook hadn't run, then it could display a link to that documentation?

**Comment by arjun27** [comment]
> But I guess the errors appear for unrelated reasons? 

Yes, the error is a catch-all for missing browser binaries.

> playwright could detect that the postinstall hook hadn't run

I might be wrong but I don't think it's possible to detect the hook didn't run. Playwright can check whether browser binaries 
are available and show the catch-all error.

Appreciate these ideas! I'd like to find a way so this becomes obvious, and something that we could handle by default. One approach could be to set the PLAYWRIGHT_BROWSERS_PATH=0 env var by default on CI environments, or at least on github actions (as @mxschmitt suggested). I noticed that you're not using the [playwright github action](https://github.com/microsoft/playwright-github-action). We could solve caching/config within the action, but I'm curious if you knew about it and chose to not use it.

**Comment by umaar** [comment]
Max's idea sounds good imo!

Hmm probably missing something obvious but does the playwright GH action do extra stuff? Because ultimately I'm still doing `npm i && npm test` right? Maybe a 'when to use this action vs. writing your own` Q&A would be good in the readme!

But to answer your question, that whole repo and their action files is all about learning (a course I'm doing), so would definitely favour "vanilla" approaches for the sake of education - in those particular action files. But if it turns out that the official playwright github action makes life easier, then might investigate it more for sure.

I am interested though, the playwright action source code does a bunch of [installing](https://github.com/microsoft/playwright-github-action/blob/13542e6d63ed24b80d76823b2f7d6e1004bcb996/index.js#L9) of important deps, e.g. all those `libnspr4` and so on, which I remember having to install on a server ages ago. But have clearly taken it for granted, because I'm not installing those deps myself, so how is it working?! Maybe they're already installed in `ubuntu-latest` which my actions use.

**Comment by mxschmitt** [comment]
Closed, see https://github.com/umaar/learn-browser-testing/pull/11 for a further reference.
