### ISSUE TITLE
[Feature] Get timeout on Page level

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#3727]
In the Playwright-runner it would be useful to add a check like:

```js
if (page.getNavigationTimeout() > runner.timeout) {
  console.warning("Since Runner timeout is < Playwright timeout we increased the runner timeout to ensure good error reporting.")
  // Alternatively call [Page.setDefaultTimeout](https://playwright.dev/#version=v1.3.0&path=docs%2Fapi.md&q=pagesetdefaulttimeouttimeout)
}
```

For that we need to expose the timeout so its accessible.

**Comment by pavelfeldman** [comment]
Timeouts inside Playwright are implemented based on the deadlines. Test runner can specify a deadline for the entire page / context to make sure it ends in time. Otherwise, two navigation timeouts will still run out of runner.timeout.

**Comment by dgozman** [comment]
It seems like forcefully closing the context upon timeout will lead to essentially the same behavior - all operations will end with "Page has been closed" and provide collected logs.
