### ISSUE TITLE
[Feature] Controlling debug mode features on browser launch, separately

### ISSUE THREAD

**Issue by lewisl9029** [microsoft/playwright#3786]
I've been working on a library that uses playwright for browser control, and there are some playwright features from PWDEBUG that would be really helpful to enable for my users (namely devtools preference saving, the playwright object on window, and source maps for evaluate functions).

However, I would prefer to not have to ask my users to run the library with a PWDEBUG env var manually, and setting process.env.PWDEBUG before importing playwright doesn't seem like the most elegant API ever (especially when using ESM with node 14+, where we'd have to use a dynamic import). Also, some of the features in PWDEBUG are actually not desirable for my use case (the forced headful mode and disabling timeouts), so it'd be great if we could control these features separately.

Curious what the maintainers think about providing an API like this on `browserType.launch` in addition to the PWDEBUG env var:

```
type LaunchOptionsBase = {
  // will read PWDEBUG to determine default boolean value
  // but overrides if present
  debugMode?: boolean | {
    // all defaulting to true for backwards compatibility with current PWDEBUG=1 behavior
    disableHeadless?: boolean;
    injectPlaywrightApi?: boolean;
    saveDevtoolsPreferences?: boolean; 
    disableTimeout?: boolean; 
    enableEvaluateSourcemaps?: boolean;
  }
};
``` 

This would allow users of playwright to control these features at runtime in their scripts for reach browser instead of only at script launch, and would allow them to enable/disable these features separately based on their use case.

If folks are onboard with the idea, I'd be happy to start working on a PR to see how far I can get.

**Comment by dgozman** [comment]
We are thinking along these lines as well, but do not have a specific proposal just yet.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
