### ISSUE TITLE
[Question] Is there a list of all devices?

### ISSUE THREAD

**Issue by nrhoffmann** [microsoft/playwright#3788]
I'm looking for a list of all the devices supported (by default) in  `playwright.devices`. Obviously, I could generate such a list myself by looping though the keys, but I think this should exist somewhere in the documentation. Does it?

**Comment by viraxslot** [comment]
@nrhoffmann Hi, I'm not sure about the documentation, but [this file](https://github.com/microsoft/playwright/blob/master/src/server/deviceDescriptors.ts) should help

**Comment by dgozman** [comment]
Thanks, @viraxslot! This file is indeed the source of truth for all devices. Documentation for [devices](https://playwright.dev/#version=v1.3.0&path=docs%2Fapi.md&q=playwrightdevices) also has a link to this source file.

**Comment by nrhoffmann** [comment]
> Actual list of devices can be found in src/deviceDescriptors.ts.
from the docs

That link is giving me a 404.

**Comment by dgozman** [comment]
> > Actual list of devices can be found in src/deviceDescriptors.ts.
> 
> That link in the docs is giving me a 404.

Oh, that's a bug on the documentation site! Thanks for spotting.
