### ISSUE TITLE
[Question] Wait for scoped selector (aka ElementHandle.waitForSelector)

### ISSUE THREAD

**Issue by sjurgis** [microsoft/playwright#3790]
I'm trying to use Playwright as end-to-end test for my complex application (built on Salesforce). My goal is to have POM for each component on the page, so rather than querying entire DOM for my component elements, I can just query subset of it.

In Pupeteer I was able to use scoped selector as outlined in example [here](https://github.com/puppeteer/puppeteer/issues/1726#issuecomment-355672247), but in Playwright that doesn't seem to work.

I'm still very new to Playwright, so perhaps there's a better way to do this.

Seeing @JoelEinbinder was original comment author, perhaps he can advice here?

**Comment by JoelEinbinder** [comment]
I updated the code to Playwright for you. Playwright only supports passing one argument into functions.

```js
function waitForScopedSelector(selector, scopeElement) {
    return page.waitForFunction(({selector, scopeElement}) => scopeElement.querySelector(selector), {selector, scopeElement});
}
```

**Comment by sjurgis** [comment]
Also worth noting that there's API in dev stage now - see #3452
