### ISSUE TITLE
[BUG]: Missing video codecs for Firefox in Heroku

### ISSUE THREAD

**Issue by ProQuestionAsker** [microsoft/playwright#3813]
It appears that videos in a headless Firefox browser within Heroku (using the [Playwright buildpack](https://github.com/mxschmitt/heroku-playwright-buildpack)) are missing codecs. I'm getting the following error:

```
[JavaScript Warning: "The video on this page can't be played. 
Your system may not have the required video codecs for: 
video/mp4;codecs="avc1.4d402a"" {file: "https://link/to/video" line: 0}]
```

This is the same error that was reported for [Dockerized Playwright](https://github.com/microsoft/playwright/issues/1613) and had been solved by installing `ffmpeg`. I've tried to do the same within Heroku (both by forking the buildpack and requiring `ffmpeg` as a dependency and by including an `ffmpeg` buildpack) without luck. I'm unclear if this is an issue with Playwright itself or with the buildpack, so I've also filed [an issue](https://github.com/mxschmitt/heroku-playwright-buildpack/issues/7) over there (apologies for the duplicate!)

It's worth noting that I'm only getting this error when my script is run remotely in Heroku. Running it locally (using `heroku local` on my machine) returns no errors and videos play as expected.

Happy to provide more info if needed. Many thanks for such a great project!

**Comment by mxschmitt** [comment]
Hi @ProQuestionAsker. Just want to let you know that we're on it. Should be added in the next few days.

**Comment by ProQuestionAsker** [comment]
Amazing, thank you! Apologies again for cross posting, just wanted to make sure this was documented in the right spot.

**Comment by mxschmitt** [comment]
Hi @ProQuestionAsker, would be awesome if you could try out this branch on the buildpack, for me it seems to work:

`https://github.com/mxschmitt/heroku-playwright-buildpack.git#bugfix/pw-1-4` (just set it on Heroku)

![image](https://user-images.githubusercontent.com/17984549/92713185-f3bbd180-f35a-11ea-92c3-16070693e23d.png)

**Comment by ProQuestionAsker** [comment]
Yes! This works now. Thank you so much for the fix!!

**Comment by mxschmitt** [comment]
> Yes! This works now. Thank you so much for the fix!!

Cool, glad to hear, then I'll merge it to master. Thanks!
