### ISSUE TITLE
waitForElementState is not a function

### ISSUE THREAD

**Issue by Pooort** [microsoft/playwright#3829]
**Context:**
- Playwright Version: 1.3.0
- Operating System: Linux
- Node.js version: 14.9.0
- Browser: Chromium
- Extra: -

**Code Snippet**

```javascript
const el = await this.page.$(selector);
await el.waitForElementState('hidden');
```

Failed with `undefined el.waitForElementState is not a function`.

Thank you for the project.

**Comment by mxschmitt** [comment]
Hi, `waitForElementState` is not yet released. So you can either use the latest development version `npm install playwright@next` or wait a couple of days until it's released.

Where did you obtain the method?

**Comment by Pooort** [comment]
Here:
https://github.com/microsoft/playwright/blob/master/docs/api.md#elementhandlewaitforelementstatestate-options

You're completely right, it doesn't described here:
https://playwright.dev/#?path=docs/api.md

Sorry for bother you.
