### ISSUE TITLE
[Typo in Documentation] `goto` should be `navigate`

### ISSUE THREAD

**Issue by nrhoffmann** [microsoft/playwright#3854]
On [this page](https://playwright.dev/#version=master&path=docs%2Fpom.md&q=) in the docs the example of a page object defines a function `goto`. The usage of the page object uses a function `navigate`. It seems to me that the `goto` function should really be `navigate`. If this is the case, I can make a PR to fix the typo.

**Comment by arjun27** [comment]
That's right, good catch! Can you send a PR? I'd love to merge.
