### ISSUE TITLE
[Feature] Driver - allow to install only selected browsers

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#3866]
Proposal by dgozman: #3197

Relates to the following issues: 
- https://github.com/microsoft/playwright-python/issues/47
- https://github.com/mxschmitt/playwright-go/issues/52
- https://github.com/microsoft/playwright-sharp/issues/890
- https://github.com/microsoft/playwright-java/issues/215

Closes #4631

**Comment by mxschmitt** [comment]
Seems like it was implemented in #4952.

**Comment by k1w1m8** [comment]
Implemented in playwright.

Missing in playwright-java.

Would be good to have consistency on these API changes.

**Comment by mxschmitt** [comment]
This feature is implemented in all the language ports. I recommend filing a new issue if you don't see this option or it does not work for you since we usually don't monitor closed issues.
