### ISSUE TITLE
[REGRESSION]: Calling `browserType.launchServer` stopped working in 1.4.0

### ISSUE THREAD

**Issue by Snikanes** [microsoft/playwright#3872]
**Context:**
- GOOD Playwright Version: 1.3.0
- BAD Playwright Version: 1.4.0
- Operating System: RHEL 8

```typescript
const chromiumServer = await chromium.launchServer({ port: 1234 });
```
Running the snippet above causes `Error: Cannot specify a port without launching as a server` to be thrown.

When calling `BrowserServerLauncherImpl.launchServer` with a port (which is allowed according to [LaunchServerOptions](https://github.com/microsoft/playwright/blob/master/src/client/types.ts#L67)) these options are immediately spread into the argument to [browserType.launch](https://github.com/microsoft/playwright/blob/master/src/browserServerImpl.ts#L42). This argument is a [LaunchOptions](https://github.com/microsoft/playwright/blob/master/src/protocol/channels.ts#L176) which does not accept a port. In turn, this leads the [following assert](https://github.com/microsoft/playwright/blob/master/src/server/browserType.ts#L69) to fail causing the aforementioned error.

**Comment by dgozman** [comment]
Fixed by #3877.
