### ISSUE TITLE
[Question] Contributing to website

### ISSUE THREAD

**Issue by SteveByerly** [microsoft/playwright#3887]
I was hoping to contribute an update for the website docs (https://playwright.dev) that would highlight the current page in the side navigation.

For example, the following path would make `Selectors` show up with `color: var(--link-color)` (#0366d6)
https://playwright.dev/#version=v1.4.0&path=docs%2Fselectors.md

I cannot seem to find where the site gets compiled. Is there a script I'm not seeing or a separate project that builds the website?

**Comment by yury-s** [comment]
Thanks for your interest in the project! The site sources are in a separate repo: https://github.com/microsoft/playwright.dev

**Comment by SteveByerly** [comment]
Thanks for following up.

Since that link results in a 404 for me, and I don't see a similar repo under the Microsoft org, I'd assume it's a private repo. If it is private, is there any way to either make it public and open to contributions? If that's not possible, could you add this as a feature request to that repo?

**Comment by arjun27** [comment]
Thanks for pointing that out @SteveByerly. playwright.dev is now public repo. Would love to see this as a contribution there 👍
