### ISSUE TITLE
[BUG] playwright-electron error with native dependency

### ISSUE THREAD

**Issue by panuhorsmalahti** [microsoft/playwright#3896]
**Context:**
- Playwright Version: 1.4.0 (also tested with 1.3.0)
- Operating System: Windows
- Node.js version: v13.11.0
- Browser: (Electron)
- Extra: Electron 9.x. 10.x and beta

**Describe the bug**

When I run the test file using playwright and playwright-electron I get the error:
```
electron/js2c/renderer_init.js:91 Error: Module did not self-register: '\\?\C:\app\node_modules\@serialport\bindings\build\Release\bindings.node'.
```

serialport is a "native" dependency that is used in my application. I tried various Electron versions and I got the same error in all of them. The dependency works fine when the application is executed normally.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
