### ISSUE TITLE
[BUG] - selectors for data attributes are inconsistent

### ISSUE THREAD

**Issue by oscarcarlstrom** [microsoft/playwright#3900]
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System: Windows
- Node.js version: 14.5.0
- Browser: Chromium (only tested on Chromium)
- Preset: jest-playwright
- Testrunner: Jest

**Code Snippet**

Works:
```javascript
test('Log out', () => {
	const logOutLink = await page.waitForSelector('[data-componentid=menuitem-1015]');
	await logOutLink.click();
	//assertions etc...
});
```

Doesn't work:
```javascript
test('Log out', () => {
	const logOutLink = await page.waitForSelector('data-componentid=menuitem-1015');
	await logOutLink.click();
	//assertions etc...
});
```
**Describe the bug**
```javascript
	waitForSelector('data-componentid=menuitem-1015');
```
results in this error:
**_Unknown engine "data-componentid" while parsing selector data-componentid=menuitem-1015_**

while using a CSS selector:
```javascript
	waitForSelector('[data-componentid=menuitem-1015]');
```
works just fine

**Comment by mxschmitt** [comment]
I think its expect. Playwright has the concept of selector engines and `data-componentid` is not a registered selector engine. Also `data-componentid=menuitem-1015 ` not a valid css selector, so it can't fallback. For more information see here: https://playwright.dev/#path=docs%2Fselectors.md&q=

To always ensure that the CSS selector engine will be used, you can prefix it with `css=` like `css=[data-componentid=menuitem-1015]`

**Comment by oscarcarlstrom** [comment]
Thanks @mxschmitt, you might be right. But I still don't get how these can all be interchangeable then:
```` javascript
// queries data-test-id attribute with css
await page.click('css=[data-test-id=directions]');
await page.click('[data-test-id=directions]'); // short-form

// queries data-test-id with id
await page.click('data-test-id=directions');
````
https://playwright.dev/#version=v1.4.0&path=docs%2Fselectors.md&q=define-explicit-contract

What is it that makes `await page.click('data-test-id=directions');` valid and `await page.waitForSelector('[data-componentid=menuitem-1015]');` invalid? That is what confuses me.

**Comment by pavelfeldman** [comment]
What makes them different is that they are baked in selector engines as per the [doc](https://playwright.dev/#version=v1.5.1&path=docs%2Fselectors.md&q=id-data-testid-data-test-id-data-test-and-their-light-counterparts)!
