### ISSUE TITLE
[Feature] APIs for getting values from the page

### ISSUE THREAD

**Issue by domderen** [microsoft/playwright#3901]
Hey,

Thanks for creating playwright, its a very cool utility for web automation! I have a use case for being able to gather values from pages quickly, and it seems current Playwright API is mostly focused on operating on HTML DOM Elements, and doesn't really support getting values from pages directly.

Such API is great for manipulating DOM nodes, but it makes it quite tedious to quickly extract values from the page, as for each value extraction, one has to process DOM nodes manually.

I'm wondering if it would make sense to add helper functions to Playwright API that could make it easier to quickly extract values from the page, either as simple string labels, or composite objects. 

I created a small sample of such APIs to illustrate what I'm talking about: https://gist.github.com/domderen/a12ba5804b5cc5b41f2dd69c0cd11c2b

Those APIs are supposed to simplify the process of extracting values from the page to just defining a set of selectors for obtaining specific values, and encapsulate the tedious node processing code. That way, tests that need to verify content of the page, can easily obtain those values without the need to parse HTML DOM nodes directly.

I'm pretty sure that those APIs could be optimized by putting them somewhere deeper in the Playwright API than directly on the Page object, but in my example I just wanted to visualize the potential application, before digging too deep into Playwright internals.

What do you think about such extensions?

**Comment by pavelfeldman** [comment]
Hi Dominik! People are using Playwright for all kinds of needs and we can't account for all of them in the core API. As a result, we defer it to the clients of the api and third parties to bulk scan values and return them using general methods such as `page.evalute`.

**Comment by dgozman** [comment]
We are considering APIs for getting values from the page, evaluating them case-by-case. For example, there are [`page.textContent`](https://playwright.dev/#version=v1.6.2&path=docs%2Fapi.md&q=pagetextcontentselector-options) and [`page.getAttribute`](https://playwright.dev/#version=v1.6.2&path=docs%2Fapi.md&q=pagegetattributeselector-name-options) methods that were added based on feedback of our users.

Please file a specific issue for a particular method you'd like to see, explaining the usecase, and we'll assess the community interest in it.
