### ISSUE TITLE
[BUG] MacOS 10.13 Webkit error

### ISSUE THREAD

**Issue by maxwell8888** [microsoft/playwright#3919]
**Context:**
- Playwright Version: 1.4.0
- Operating System: MacOS 10.13
- Node.js version: Tried with 10 and 14
- Browser: Chromium
- Extra: 

**Code Snippet**

```javascript
const {chromium} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  // ...
})();
```

**Describe the bug**
Webkit is not support for MacOS 10.13, however even just importing chromium fails with this error:
```
Uncaught Error: Browser is not supported on current platform
    at WebKit.executablePath
```

Add any other details about the problem here.
Seems to be the same problem as [this](https://github.com/microsoft/playwright/issues/1941)

**Comment by mxschmitt** [comment]
Chromium and Firefox should work. For WebKit we don't plan to support it since it has EOL in November. See here for more information: https://github.com/microsoft/playwright/issues/1941#issuecomment-651363301
