### ISSUE TITLE
[Feature] coverage per frame

### ISSUE THREAD

**Issue by gullerya** [microsoft/playwright#3920]
Right now `coverage` property is found on the `Page` object, but not on the `Frame` object.
Since there are obvious use-cases, where scripts can be loaded specifically in the frames - any intention (or deliberate decision to not) to add a capability of collecting coverage on the `Frame` level?

**Comment by pavelfeldman** [comment]
No deliberate decision to not support it, but no intention either. What's your code coverage use case if you don't mind sharing? We can rarely see coverage used with the end-to-end testing, so any details will help.

**Comment by gullerya** [comment]
I'm working on the next version of my `just-test` framework, where PlayWright comes instead of Puppeteer 👍 .

The idea is to run tests in UI in dev flavor (see some control panel, test outcomes/elements in the working panel, re-run and debug via the dev-tools), and also in CI flavor - almost the same, but just run all of the tests once and report.

Report should give coverage per test. UI/dev mode also allows to re-run a single test ad-hoc just in the browser and see the results/debug. For both those use-cases it would be perfect to load and run each test-run in it's own `iframe`, but for that I need an ability to collect coverage on the Frame level.

Until that is possible (if any), my plan is to split the code and for the CI flavor run each test in its own Page, but obviously I'd prefer to have a unified flow logic as much as possible.

**Comment by dgozman** [comment]
Coverage per frame is a major effort. JavaScript VMs usually share the scripts cache between frames from the same origin, and collecting separate coverage for them might be very hard. I would not expect this feature any time soon, sorry.

**Comment by gullerya** [comment]
Understandable, thanks.
