### ISSUE TITLE
[REGRESSION]: no longer able to connect to FF using webExt (for testing extension)

### ISSUE THREAD

**Issue by sublimator** [microsoft/playwright#3932]
**Context:**
- GOOD Playwright Version: [what Playwright version worked nicely?]
1.3.0 

- BAD Playwright Version: [what Playwright version doesn't work any more?]
1.4.1
- Operating System: [e.g. Windows, Linux or Mac]
Linux & Mac

Am no longer able to connect to a firefox launched by webext as per: https://github.com/microsoft/playwright/issues/2644#issuecomment-647842059

I note that Firefox has been upgraded from 78 to 80 from Playwright 1.3.0 to 1.4.1
(edit: I tried launching a copy of the 1.3.0 bundle of FF v78 and it was still unable to connect)

Never get to the `complete` part:
```
    debug('connecting to %s', jugglerEndpoint)
    const ff = await firefox.connect({
      wsEndpoint: jugglerEndpoint
    })
    debug('complete')
```

**Comment by pavelfeldman** [comment]
Playwright now uses it's own protocol for communication between its client and server, so it is essential that the Playwright is used to launch the browser and obtain the web socket address.

**Comment by sublimator** [comment]
Can we get an updated code snippet then:
https://github.com/microsoft/playwright/issues/2644#issuecomment-647842059

?

Will post myself if I come up with anything

**Comment by sublimator** [comment]
@pavelfeldman 

Any solution for this ?

**Comment by sublimator** [comment]
I stole the RemoteFirefox class from web-ext and tried the following:

```typescript
    const port = await getPort()
    const ff = await firefox.launch({
      executablePath: firefox.executablePath(),
      headless: false,
      ignoreDefaultArgs: ['-no-remote'],
      args: [`--start-debugger-server=${port}`]
    })
    const context = ff.newContext({ viewport: viewOptions.viewport })
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const client = await require('@cliqz-oss/node-firefox-connect')(port)
    const remote = new RemoteFirefox(client)
    await remote.installTemporaryAddon(EXTENSION_PATH)
    return context
```

I get this at the start though:
![image](https://user-images.githubusercontent.com/525211/94331711-1a376900-fff9-11ea-83af-c17d8de3aa17.png)

Anyone have any ideas ?

**Comment by sublimator** [comment]
@pavelfeldman

Do you know if Firefox extension loading support is on the road map? 
If not, could you outline how you think it could work?

I ported our tests from puppeteer to playwright with the assumption that Firefox extensions are supported via web-ext and a little glue code(see: https://github.com/microsoft/playwright/issues/2644#issuecomment-647842059)

**Comment by sublimator** [comment]
@aslushnikov

Do you have any ideas? 

Thanks!

**Comment by pavelfeldman** [comment]
As per https://github.com/microsoft/playwright/issues/2644#issuecomment-647634774, extension automation is currently out of the scope of Playwright. Apologies for building the wrong expectation here.

**Comment by sublimator** [comment]
What a bummer! But understood :) 

Hope you guys revisit this

**Comment by sublimator** [comment]
Given you guys maintain patches of browsers, would it be possible to patch FF itself to load an extension via the command line upon launch?  That may be easier than trying to get web-ext to work with the new juggler replacement. Would you accept a PR for this?
