### ISSUE TITLE
[BUG] Locale override does not affect date input field rendering

### ISSUE THREAD

**Issue by midgleyc** [microsoft/playwright#3934]
By the docs, I can set the locale using [browser.newContext({locale})](https://playwright.dev/#version=v1.4.1&path=docs%2Fapi.md&q=browsernewcontextoptions). However, this doesn't seem to set the locale for time / date form entry.

```
const playwright = require('playwright');

(async () => {
    const browser = await playwright['chromium'].launch();
    const context = await browser.newContext({'locale': 'en-GB'}); // or en-US
    const page = await context.newPage();
    await page.goto("https://interactive-examples.mdn.mozilla.net/pages/tabbed/input-date.html")
    await page.screenshot({ path: `input-date.png` });
    await browser.close();
})();
```

If I run this on my local machine, dates are formatted as British time (DD/MM/YYYY) no matter the locale I set. If I run this on the provided docker container:

```
docker run -it --rm -v $(pwd):/date-format --ipc=host mcr.microsoft.com/playwright:bionic /bin/bash -c "cd date-format; node date-format-test.js"
```

then dates are formatted as US time (MM/DD/YYYY) no matter the locale I set.

Is there a way to configure the locale for formatting dates and times in forms?

**Comment by pavelfeldman** [comment]
I can repro this, I can see emulated language for number and date formatting in console, but not for the date input field rendering in the page.

**Comment by midgleyc** [comment]
Experimenting with this more, it seems to use the value of `process.env.LANGUAGE` when `playwright['chromium'].launch()` is called. By closing and re-launching the browser, I can have it use a different format.

It only works if the locale is installed.

I checked using `en_US`, `en_GB` and `de_DE`, which all format dates differently.

**Comment by yury-s** [comment]
I can reproduce this locally. WebKit doesn't support input with type 'date' yet, it is rendered as text input. Chromium does inherit locale from  `LANG`, firefox takes it from somewhere else.

**Comment by lngr** [comment]
I'm having the same issue, setting the LANG env variable makes chromium respect the date input field, but firefox sticks to US-formatting rules.

@yury-s I've seen this PR: https://github.com/microsoft/playwright/pull/1560
How is this rellated to this issue and how an I make Firefix respect the date formatting?

For instance, I'm using     

    New Context     viewport={'width': 1920, 'height': 1080}    acceptDownloads=True    locale=de-DE

but it's still using wrong formatting.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.

**Comment by KastnerTobias** [comment]
Big thanks to @SebCorbin,
you solved the problem I had with this. Just setting the LC_ALL in my docker file made the locale work!
