### ISSUE TITLE
[BUG] browserType.connect() throws on executablePath errors

### ISSUE THREAD

**Issue by Niek** [microsoft/playwright#3935]
**Context:**
- Playwright Version: 1.4.1
- Operating System: macOS 11 beta 7
- Node.js version: 10.14
- Browser: Chromium

**Code Snippet**
```javascript
const { chromium } = require('playwright');
(async () => {
    const b = await chromium.connect({wsEndpoint: '...'});
})();
```

**Describe the bug**

Chromium is not currently supported with Playwright on macOS 11 beta 7. It (correctly) throws this error:
```javascript
.../node_modules/playwright/lib/server/browserType.js:48
            throw new Error('Browser is not supported on current platform');
```
The bug is that this error is **also** thrown when using ``browserType.connect()``. The file ``browserTypeDispatcher.js`` checks for ``executablePath``, even if you're connecting to a remote websocket. It should only check on ``browserType.launch*()``

**Comment by mxschmitt** [comment]
Hi we don't yet support MacOS Big Sur: https://github.com/microsoft/playwright/issues/2789

**Comment by Niek** [comment]
I am aware of that. It's perfectly fine to throw an error when trying to launch a browser instance on macOS Big Sur. However, the bug is that the same error is thrown when connecting to a remote browser - that doesn't make sense to me. The limitation is in the browser builds, not in de node code.

**Comment by mxschmitt** [comment]
Gotcha, makes sense. Then it seems to be a bug and related to #3919 too.
