### ISSUE TITLE
[Question] list iframes?

### ISSUE THREAD

**Issue by sergicloud** [microsoft/playwright#3951]
I don't understand the api well.. I want to list all iframes and get their properties) url, name, sandbox, etc of a website (without knowing iframe names) queryselector? or page.frame? can't find any example

<iframe id="result" src="https://localhost/1/2/3" sandbox="allow-downloads allow-forms allow-modals allow-pointer-lock allow-popups allow-presentation allow-same-origin allow-scripts allow-top-navigation-by-user-activation" allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; microphone; midi; payment; vr" allowTransparency="true" allowpaymentrequest="true" allowfullscreen="true" class="result-iframe"></iframe>

**Comment by mxschmitt** [comment]
Hi,

you can loop over the DOM elements and get the attributes of it, example: https://try.playwright.tech/?s=6y992
