### ISSUE TITLE
[Question] request.url together with request.abort() not working?

### ISSUE THREAD

**Issue by sergicloud** [microsoft/playwright#3953]
I expect to abort png,jpeg,jpeg requests and get some debug information on aborted requests. But snippet fails with "TypeError request.url is not a function"

```js
await page.route('**/*.{png,jpg,jpeg}', request => {
console.log('request', request.url());
request.abort()
});
```

**Comment by arjun27** [comment]
Thanks @sergicloud. The signature of the handler in your snippet is slightly wrong. Please see [API reference for page.route](https://playwright.dev/#version=v1.4.1&path=docs%2Fapi.md&q=pagerouteurl-handler)

```js
  await page.route('**/*.{png,jpg,jpeg}', (route, req) => {
    console.log(req.url());
    route.abort();
  })
```
