### ISSUE TITLE
[BUG] Click doesn't work for > than a single word title.

### ISSUE THREAD

**Issue by wadezone** [microsoft/playwright#3954]
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System:  **Windows**
- Node.js version: v12.18.3
- Browser: Chromium Only
- Extra: Power BI Reports within the Power BI Service

**Code Snippet**

### This works
await page.waitForTimeout(500); 
await page.click("[aria-label='Unidentified (Not Claimed) Performances Matrix'] [title='Unidentified']"); 
await page.waitForTimeout(500); 
await page.click("[aria-label='Unidentified (Not Claimed) Performances Matrix'] [title='20194']"); 

![UndentifiedWorks](https://user-images.githubusercontent.com/71278576/93905020-1be2f300-fcc0-11ea-9b4c-ce34d9274439.JPG)

### This doesn't work; I tried two different ways. 
await page.waitForTimeout(500); 
await page.click("[aria-label='Unidentified (Not Claimed) Performances Matrix'] [title='Unprocessed Performances']"); 
await page.click("[aria-label='Unidentified (Not Claimed) Performances Matrix'] [title='Unprocessed%nbsp;Performances']"); 

For every single word title I can get the click to happen. For every word greater than 1 word titles it fails with timeout 3000ms exceeded. When I copy the value from the Chrome Dev Tools it doesn't give me the non blank space version. 

**Describe the bug**

Need to click on a row within a Power BI report for the visuals to adjust based on the selected click. When I code for the click it works for a single word title label, but doesn't work for any title with a space; two ore more words for title. 

![DoesntWork](https://user-images.githubusercontent.com/71278576/93906234-92ccbb80-fcc1-11ea-85a7-87e2e800d8bf.JPG)

**Comment by arjun27** [comment]
Similar to #3830, which is being worked upon in #3873. But I believe the fix is only targeting text selectors (not css, which is what happens in this case). Can we include this in the fix, @mxschmitt @dgozman?

**Comment by mxschmitt** [comment]
> Similar to #3830, which is being worked upon in #3873. But I believe the fix is only targeting text selectors (not css, which is what happens in this case). Can we include this in the fix, @mxschmitt @dgozman?

I had an offline discussion with dgozman about that. We had the idea of normalising all the `\s` characters which would also replace \n with " ". Since browsers do that in general too, like rendering a space instead of a new line in a DIV e.g. it should not harm the users.

Good catch, that we should apply that probably also for HTML attributes in the CSS selector engine.

The missing piece in our decision was if we should differentiate between an exact match and a lazy match in the text selector engine. (normalise only in the lazy - contains one)

**Comment by wadezone** [comment]
@mxschmitt @dgozman 

Would this also applied to getting the values? The Power BI report I started with I was never able to "get" a person's legal name like "Theresa Wade" that would show up in Chrome Dev Tools as "Theresa&nsp;Wade". I would need to "get" the person's name that was clicked to be used as a parameter to drill through to a different Power BI report.  I gave up on that report and went to what I consider a simple Power BI report. I had no luck with the "get" working either. 

Should getAttribute or using the evaluate work for the get?

Theresa

**Comment by dgozman** [comment]
I am not sure whether we should normalize whitespace in CSS selectors - this will change the defined CSS semantics.
I think the following would work in this particular case, although not strictly equal:
```js
await page.click(`[title~=Unprocessed][title~=Performances]`);
```

I am pretty sure we do not want to change the output of `getAttribute` and similar methods that retrieve information from the page to avoid data loss. Perhaps, some option like `{normalizeSpace: true}`, or maybe even the reverse `{preserveSpace: true}` to address this?

**Comment by wadezone** [comment]
@dgozman & @mxschmitt 

I wanted to verify what is creating the &nbsp; I had our developers look into our report and found that the Power BI "word wrap" attribute is why it shows up in Chrome like that. If the word wrap is set to on by default then it doesn't give the %nbsp. Our reports the word wrap is off per the business requirement which is showing the %nbsp.

I had the developer give me a version of the report with the word wrap on and I am still not able to get the "click" for a two word title. 

**These work**
await page.click('div[aria-label="Unidentified (Not Claimed) Performances Matrix"] >> text="20191"'); 
await page.click("[aria-label='Unidentified (Not Claimed) Performances Matrix'] [title='Unidentified']"); 

**These do not work**
await page.click('div[aria-label="Unidentified (Not Claimed) Performances Matrix"] >> text="Not Affiliated"'); 
await page.click("[aria-label='Unidentified (Not Claimed) Performances Matrix'] [title='Not Affiliated']"); 

Based on @dgozman's example above, I tried the following: Is this the correct syntax on what you were suggesting?

**This doesn't work**
await page.click("[aria-label='Identified (Claimable) Performances by PRO Matrix'] [title~='Unprocessed '] [title~='Performances']"); 

**This doesn't work**
await page.click("[aria-label='Identified (Claimable) Performances by PRO Matrix'] [title='Unprocessed '] [title='Performances']"); 

The below has never worked for me for a single word or multiple words until I added in the aria-label
 await page.click("[title='Unidentified']"); 

Is there any additional information that I might be able to provide that would help?

I still haven't had success in getting a line of code to do a "get" for any of the elements. I keep getting a time out error or can't get something that is null.

Theresa

**Comment by wadezone** [comment]
@dgozman @mxschmitt 
Update:

Developers had to go change ever single cell in this Power BI report to have word wrap set to on. Once they did this The following did work.

await page.click('div[aria-label="Unidentified (Not Claimed) Performances Matrix"] >> text="Not Affiliated"');
await page.click("[aria-label='Unidentified (Not Claimed) Performances Matrix'] [title='Not Affiliated']");

The problem right now is the business requirement is to have those Word Wrap setting to false for these visuals.  This means it would have the &nbsp. Is there a way to call the click to work with the two word titles that include &nbsp?

Theresa

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
