### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Download failed: server returned code 403

### ISSUE THREAD

**Issue by gkushang** [microsoft/playwright#3960]
I get this error in Jenkins while installing Playwright. Any idea what could be wrong? Any workaround?

```
(node:1636) UnhandledPromiseRejectionWarning: Error: Download failed: server returned code 403. URL: https://playwright.azureedge.net/builds/chromium/799411/chromium-linux.zip
11:23:17      at /home/jenkins/agent/workspace/eline_PR-447/node_modules/playwright/lib/install/browserFetcher.js:181:27
```

**Comment by mxschmitt** [comment]
Hi, would it be possible to give us the full response from that server? It seems like either a temporary issue or maybe due some abuse / blocking reasons.

```
curl -v https://playwright.azureedge.net/builds/chromium/799411/chromium-linux.zip
```

**Comment by firebluetom2** [comment]
I have a similar issue due to corporate proxy. 
You can `export no_proxy=azureedge.net` and see what happens, but probably will not connect.
I think proxy-ing is a bit to figure out here. Is the HTTPS_PROXY variable set?
```
HTTP_PROXY=http://some-route.your-company-proxy.com:8099
```

**Comment by pavelfeldman** [comment]
Please feel free to reopen with the additional details if this is still the case!

**Comment by Dottenpixel** [comment]
I am experiencing this same issue and working in an environment where `HTTP_PROXY` and `HTTPS_PROXY` are set like @firebluetom2 indicates:
```
HTTP_PROXY=http://some-route.your-company-proxy.com:8099
```
