### ISSUE TITLE
[Question] Why does chromiumBrowserContext.newCDPSession require a page?

### ISSUE THREAD

**Issue by VikramTiwari** [microsoft/playwright#3962]
I used to use `CRBrowserContext._browser` which is not available any more. Rather we have [chromiumBrowserContext.newCDPSession(page)](https://playwright.dev/#version=v1.4.1&path=docs%2Fapi.md&q=chromiumbrowsercontextnewcdpsessionpage) which requires a page. I retrofitted to pass in a page and the resultant session did the job properly but I am unsure why that page is required. Looking at the code it seems like the session is created relative to the page. Does this mean that session will be closed if that page is closed? Should there be a different call `chromiumBrowserContext.newBrowserCDPSession()` which doesn't require a page?

**Comment by pavelfeldman** [comment]
That depends on the target you intend to attach to. If you need a session to a page, you pass the page in, if you want to attach to the browser, you use the newBrowserCDPSession.

**Comment by VikramTiwari** [comment]
@pavelfeldman That makes sense. However I am launching browser using `browserType.launchPersistentContext`. With that `newBrowserCDPSession` is not available with `chromiumBrowserContext`. I also didn't see a way to get `browser` from `browserContext`. So this leaves me with just `newCDPSession(page)` which doesn't seem ideal.

**Comment by dgozman** [comment]
Closing since the question is resolved.
