### ISSUE TITLE
[Feature] Use text "title" values instead of nth-child

### ISSUE THREAD

**Issue by wadezone** [microsoft/playwright#3973]
I wasn't sure what the subject should be but hopefully this makes sense.

I am using playwright to automate testing Power BI reports like the user would click. Also grabbing visual "cell" values to validate against a database. Currently focussing on the clicking and the "getting".

nth-of-type(#) and nth-child(#) only accepts a number

These work to click or "get" the value:
await page.click('.bodyCells > :nth-child(1) > :nth-child(1) > :nth-child(1) > div:nth-of-type(2)'); 

const test1 = await page.textContent('.bodyCells > :nth-child(1) > :nth-child(1) > :nth-child(1) > div:nth-of-type(2)'); 
console.log(test1); 

const test2 = await page.textContent('.bodyCells > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(2)'); 
console.log(test2); 

const elementByClass = await page.$('.bodyCells > :nth-child(1) > :nth-child(1) > :nth-child(1) > div:nth-of-type(1)') 
const innerText = await elementByClass.innerText() 
console.log(innerText) 

It would be awesome if I could actually refer these by the section name and column/row header names to "get" the one value I want. In this case, I would "get" 258,886.064  from the example picture attached.
     "[aria-label='Identified (Not Claimed) Performances']"
     [title='Unidentified']
     [title='20191']

This would benefit from having to re-code the entire page when business makes changes to the report by moving around or deleting sections.

![cell](https://user-images.githubusercontent.com/71278576/94191117-ad926200-fe72-11ea-9db1-95035fa42ff9.JPG)
  
Thoughts?

Thanks for reviewing.
Theresa

**Comment by dgozman** [comment]
If I understand correctly, you would like to select a table cell using the row+column text values.

Unfortunately, this is currently outside of the scope of Playwright. We provide [basic selectors](https://playwright.dev/#version=v1.4.2&path=docs%2Fselectors.md&q=) like text, css and xpath, and encourage the use of [custom selectors](https://playwright.dev/#version=v1.4.2&path=docs%2Fextensibility.md&q=custom-selector-engines) whenever appropriate. I can imagine a "table" custom selector, but it will probably be tailored to a particular layout, for example only work with `<table>`, `<tr>` and `<td>` elements.

Depending on the page structure, there could be different workarounds for this particular case. For example something like this, where you find the row using text xpath, and then locate the third cell using index:
```js
await page.textContent('.bodyCells >> //tr[contains(normalize-space(.), "Unidentified")]/td[3]')
```

Does this answer your question?

**Comment by wadezone** [comment]
@dgozman: Thank you for your response. It didn't hurt to ask. The Power BI reports do not use the <table>, <tr> or <td> for elements which is why I am struggling.  I am having difficulty in converting or translating the correct html element selector to the playwright syntax. 

For this example you provide;  can it work if referencing the div class or the div title when there isn't a span class? 
await page.textContent('.bodyCells >> //tr[contains(normalize-space(.), "Unidentified")]/td[3]')

I tried with no luck. 
I also see a selector element type of "data-automation-type" that I wonder if I would need to use it instead but having no luck. 

This is what the XPath is to one of the cell values. Could you provide me another syntax example on how to reference elements besides the nth-child(1) with your approach? I believe it would be better than just using the below example since there are multiple .bodyCells selections on the Power BI report. 

const test2 = await page.textContent('.bodyCells > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(2)');
console.log(test2); 


This is what the xpath element selector looks like for a cell value. 

//*[@id="pvExplorationHost"]/div/div/exploration/div/explore-canvas-modern/div/div[2]/div/div[2]/div[2]/visual-container-repeat/visual-container-group[3]/transform/div/div[2]/visual-container-modern[2]/transform/div/div[3]/div/visual-modern/div/div/div[2]/div[1]/div[4]/div/div/div[1]/div[2]


This is what the hierarchy structure looks like. Does it required to start at the top level when referencing the one cell? 

![Screen Shot 2020-09-30 at 9 38 30 PM](https://user-images.githubusercontent.com/71278576/94757432-cfeb1a80-035f-11eb-899e-e425831f62b2.png)
![Screen Shot 2020-09-30 at 9 47 46 PM](https://user-images.githubusercontent.com/71278576/94757442-d7122880-035f-11eb-9369-1020bbb69114.png)

**Comment by pavelfeldman** [comment]
We just support `css`, `xpath` and `text` selectors and their combinations. Selectors don't need to start from the root, here is the [selectors](https://playwright.dev/#version=v1.5.1&path=docs%2Fselectors.md&q=) doc page!
