### ISSUE TITLE
[Question] Using firefox as browser on test throws: `Response body is unavailable for redirect responses`

### ISSUE THREAD

**Issue by maurusrv** [microsoft/playwright#3987]
I'm new in using `jest` and `playwright` but using it is really a breeze. I don't have anymore detailed explanation but what i wrote in the title. What does this message mean? 

Here's what i encounter:
```js

    Response body is unavailable for redirect responses

      at node_modules/playwright/lib/server/network.js:210:27
      at ResponseDispatcher.body (node_modules/playwright/lib/dispatchers/networkDispatchers.js:62:27)
      at DispatcherConnection.dispatch (node_modules/playwright/lib/dispatchers/dispatcher.js:137:28)
```
This only throws on my test cases when the browser i use is firefox. may test passes on both chrome and webkit.

Thanks in advance!

**Comment by dgozman** [comment]
Unfortunately, response body is not always available. For example, it is not available for redirect responses, when server responds, for example, with 302 server redirect. According to [our tests](https://github.com/microsoft/playwright/blob/master/test/network-response.spec.ts#L47-L57), this should be the case for all browsers. My guess would be that server sends different response for Firefox in your particular case.

I'd suggest to catch the error when accessing `response.body`:
```js
page.on('response', async response => {
  const body = await response.body().catch(e => null);
  if (!body)
    console.log('Failed to fetch response body');
  else
    doSomethingWithResponseBody(body);
});
```

Does this answer your question?

**Comment by maurusrv** [comment]
I found out that in my case, it was 304 responses that i keep getting, and i think it's because my tests sometimes involves a lot of calling the same endpoint. 

But now i wonder why this only happens on Firefox though. some nuance among the different browsers huh.

Anyway, thanks for the insight @dgozman!
