### ISSUE TITLE
[Feature] Adding support to custom keyboard layout

### ISSUE THREAD

**Issue by oriSomething** [microsoft/playwright#3989]
Currently both [keyboard simulated events](https://github.com/microsoft/playwright/blob/109688a066a3168177b0244534b0d35dcd6161a9/src/server/input.ts#L53) and the [KeyboardEvent data they use](https://github.com/microsoft/playwright/blob/109688a066a3168177b0244534b0d35dcd6161a9/src/server/input.ts#L245) is locked out to US QWERTY keyboard layout.
I think supporting setting custom keyboard layout or at least supporting more customized `KeyboardEvent` can be very beneficial to any webapp that supports keyboard management and doesn't want to be locked by broken testing in AZERTY/QWERTZ/Turkish (and even in QWERTY, QWERTY for French Canadian is a bit different, and every layout has its customizations per country) keyboard layouts

**Comment by pavelfeldman** [comment]
Thank you for reporting this issue and providing comments to those that might be facing a similar problem. I am now closing this as a part of the triage, please feel free to file a new issue with additional details. Given the limited resource and a lot of requests, we need to fulfill most popular requests and at the same time keep our issue database manageable.
