### ISSUE TITLE
[BUG] browserType.connect() promise never resolved after version 1.4.x

### ISSUE THREAD

**Issue by ccpu** [microsoft/playwright#3991]
**Context:**
- Playwright Version: 1.4.2
- Operating System: Windows, Linux
- Node.js version: 12.16.1
- Browser: All
- Extra: Using docker

After version 1.4.x the `browserType.connect()` never get resolved, it appears that the promis in this [line](https://github.com/microsoft/playwright/blob/df777344a3e5de2700fa7f0ecc4031f3f4a18e11/src/client/connection.ts#L66) never get resolved.

For remote browser, I am using [this docker](https://github.com/ccpu/playwright-docker-server) repo.

Docker image runs playwright version 1.4.2, i know that the problem is not docker image because when vscode debugger attached, I can see the playwright launch the server and pass it on from [this line](https://github.com/ccpu/playwright-docker-server/blob/de1c8614fa0c0a668901b366a861b7efe7afa5e8/src/browser.ts#L22).

Also, I have managed to connect to the chromium-browser in docker running V 1.4.2 from  1.3.0 client. so I am assuming that the problem is not docker image.

Thanks!

**Comment by dgozman** [comment]
Could it be that you rely on the specific `wsEndpoint` format or the shape of the remote protocol?

With 1.4 we switched to the new non-compatible protocol compared to 1.3. You can read about it in the "New Client / Server Wire protocol" section of [release notes](https://github.com/microsoft/playwright/releases/tag/v1.4.0).

Note that if you `launchServer` with 1.4 and `connect` with 1.4 by passing `wsEndpoint` directly, it is supposed to work.

To help debugging, could you please run your server or client with `DEBUG=pw:channel*` and provide the logs?

**Comment by ccpu** [comment]
i have had a chance to look into it today, the problem was not with playwright nor docker image, it was my mistake of using docker local registry wrongly, sorry for any inconvenient.
