### ISSUE TITLE
[Feature] webkit webrtc (RTCPeerConnection) support?

### ISSUE THREAD

**Issue by aaronD14** [microsoft/playwright#4017]
Is there a way to enable webrtc or just RTCPeerConnection connection In webkit?

**Comment by yury-s** [comment]
It should be enabled. I can run basic examples from https://webrtc.github.io/samples/ on my mac laptop. Note though that Linux implementation in WebKit is quite different and may be missing some of the features.

**Comment by Sue9445** [comment]
Hi @yury-s 

How can I enable on ubuntu? It seems completely disabled.

**Comment by yury-s** [comment]
Well, I've tried that on Ubuntu and it worked fine. Like I said some of the features are missing in WebKit Linux implementation but some of them are working. Do examples from the url above work for you or how do you test it and see that it's 'completely disabled'?

**Comment by Sue9445** [comment]
@yury-s, thanks for the your reply.

You're right, I tried on my mac 11.0 laptop and it worked fine (headless & headfull) but when I tried with Ubuntu, interfaces returned as undefined.

It would be great if it worked like other browsers.

Also there is 1 more opened issue related this: #2973

Thank you

https://try.playwright.tech/?s=j6rxlbi

**Comment by R-Bower** [comment]
Any progress on this?  I'm incorporating playwright for a few applications that I'm working on and Webkit WebRTC testing would be a huge boon.
