### ISSUE TITLE
Browser launch argument for firefox.

### ISSUE THREAD

**Issue by jknooks583** [microsoft/playwright#4022]
I see the list of chromium flags (https://peter.sh/experiments/chromium-command-line-switches/) that can be used as part of the args field when we launch a browser. I was wondering if these would also work for firefox as well? If not, are there a list of flags available for firefox as well?

**Comment by mxschmitt** [comment]
Hi, does that fit for your needs? https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options

**Comment by jknooks583** [comment]
Yes, just to confirm, I won't be able to use something like "--disable-dev-shm-usage" for firefox?

**Comment by dgozman** [comment]
> Yes, just to confirm, I won't be able to use something like "--disable-dev-shm-usage" for firefox?

Nope, this is Chromium-only command line flag. Do you need it for Firefox? Do you run into the problem of failing shared memory allocations? IIRC, this problem is Chromium-specific.
