### ISSUE TITLE
[Question] Access-Control-Allow-Origin issue

### ISSUE THREAD

**Issue by vitaly87** [microsoft/playwright#4031]
Hi ,
I am using codeceptjs with Playwright , 
the issue that I have cross origin issue,
I added the args like this

```
   ignoreHTTPSErrors: true,
      chromium: {

        args: [
          "--disable-web-security",
          "--user-data-dir",
          "allow-insecure-localhost",
          "--ignore-certificate-errors",
          "--window-size=1920,1280",
          "--no-sandbox",
          "-–allow-file-access-from-files"

        ]
      }
```

but still getting same error

**Comment by dgozman** [comment]
Could you please provide more details about the issue? A repro script, error message, screenshot or some logs?

Btw, you probably wanted to pass `--allow-insecure-localhost` with the double hyphen.

**Comment by vitaly87** [comment]
Access to XMLHttpRequest at 'https://qa-ma.com/identity-service/home' (redirected from 'https://localhost:3000/console/login') from origin 'https://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. add this also like you said same issue

**Comment by pavelfeldman** [comment]
We still need more details in order to help you. I.e. what is your scenario, preferably with the source code, what the expectations are and how they are not met.

**Comment by yury-s** [comment]
There hasn't been any response for almost a month, closing the issue for now.

@vitaly87 please reopen with the failing code snippet and/or more details on your use case.

**Comment by devdelpiero** [comment]
What more details do you need? Its a cross origin error. Sounds like the redirect is erasing session credentials.

**Comment by bartoszdBB** [comment]
This issue is still not resolved. When I try to login to the app via Playwright script I see the following error is displayed in the console
`
Access to XMLHttpRequest at 'https://identity-es.tst.adv.live.backbaseservices.com/auth/realms/advanzia-esp/protocol/openid-connect/token' from origin 'https://my_URL' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is 'false' which must be 'true' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

Has anyone faced similar issue using Playwright? @yury-s @vitaly87

**Comment by xyngfei** [comment]
I also have a similar issue. 
When I launch the site https://xxx.abc.org, it has the submit button trigger to another API, https://bbb-api.abc.org/tenant/approval, then it will return the error below. Any suggestions for fixing this issue?

FYI, when I manually perform the same actions, i don't see this issue at all. 

Access to XMLHttpRequest at 'https://bbb-api.abc.org/tenant/approval' from origin 'https://xxx.abc.org' has been blocked by CORS 
policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by CTimmerman** [comment]
Same here. Afaik the only solution is to use a local proxy server somehow or the desktop browser with a CORS and/or CSP add-on somehow. I'm still searching for a solution.

```
~/code/widget-tests master*                                                                                     16:06:21
❯ npx playwright codegen http://127.0.0.1:9080/apps/secure/org/ide/manager.html --project="Google Chrome"
error: unknown option '--project=Google Chrome'
~/code/widget-tests master*                                                                                     16:06:45
❯ npx playwright codegen http://127.0.0.1:9080/apps/secure/org/ide/manager.html --browser="Google Chrome"
Usage: npx playwright [options] [command]

Options:
  -V, --version                          output the version number
  -h, --help                             display help for command

Commands:
  open [options] [url]                   open page in browser specified via -b, --browser
  codegen [options] [url]                open page and generate code for user actions
  install [options] [browser...]         ensure browsers necessary for this version of Playwright are installed
  uninstall [options]                    Removes browsers used by this installation of Playwright from the system (chromium, firefox,
                                         webkit, ffmpeg). This does not include branded channels.
  install-deps [options] [browser...]    install dependencies necessary to run browsers (will ask for sudo permissions)
  cr [options] [url]                     open page in Chromium
  ff [options] [url]                     open page in Firefox
  wk [options] [url]                     open page in WebKit
  screenshot [options] <url> <filename>  capture a page screenshot
  pdf [options] <url> <filename>         save page as pdf
  show-trace [options] [trace...]        show trace viewer
  test [options] [test-filter...]        run tests with Playwright Test
  show-report [options] [report]         show HTML report
  help [command]                         display help for command
~/code/widget-tests master*                                                                                     16:06:57
❯ npx playwright codegen cr http://127.0.0.1:9080/apps/secure/org/ide/manager.html
Error: net::ERR_NAME_NOT_RESOLVED at http://cr/
=========================== logs ===========================
navigating to "http://cr/", waiting until "load"
============================================================
~/code/widget-tests master*                                                                                     16:07:26
❯ npx playwright codegen --project="Google Chrome" http://127.0.0.1:9080/apps/secure/org/ide/manager.html
error: unknown option '--project=Google Chrome'
~/code/widget-tests master*                                                                                     16:07:57
❯ man playwright
Unknown locale, assuming C
No manual entry for playwright
~/code/widget-tests master*                                                                                     16:08:15
❯
```

**Comment by felixtruong-vn** [comment]
> Could you please provide more details about the issue? A repro script, error message, screenshot or some logs?
> 
> Btw, you probably wanted to pass `--allow-insecure-localhost` with the double hyphen.

Thanks, It works for me
