### ISSUE TITLE
[REGRESSION]: Tall screenshots in chromium get corrupted at bottom

### ISSUE THREAD

**Issue by benoitjchevalier** [microsoft/playwright#4038]
**Context:**
- GOOD Playwright Version: 1.3.0
- BAD Playwright Version: 1.4.0
- Operating System: OSx mojave (10.14.5)

**Code Snippet**

This [small project ](https://github.com/benoitjchevalier/playwright-screenshot) just takes a 1250*8440px screenshot of a div with a linear gradient to expose the problem. 

```javascript
const {chromium, webkit, firefox} = require('playwright');
const playwright = require("playwright");
const playwrightP = require("playwright/package.json");
const path = require("path");
const { cwd, exit } = require("process");

// allow await
(async () => {
  const options = {
    headless: true,
  };

  const chrome = await playwright["chromium"].launch(options);

  const newPage = async (browser) => {
    const context = await browser.newContext({
        viewport: { width: 1280, height: 800 },
      }),
      page = await context.newPage();
    return page;
  };

  newPage(chrome).then(async (page) => {
    await page.evaluate((body) => {
      const div = document.createElement("div");
      div.style.width = "1250px";
      div.style.height = "8440px";
      div.style.background = "linear-gradient(#e66465, #9198e5)";
      document.body.appendChild(div);
    });
    const divHandle = await page.$("div");
    const dest = path.join(
      process.cwd(),
      "screenshots",
      `${playwrightP.version}.png`
    );
    await divHandle.screenshot({ path: dest });

    exit();
  });
})();

```

**Describe the bug**

In Chromium, when the screenshot is taller than ~8200px then the bottom of the screenshot is a repeat of the top instead of whatever it is supposed to be. 

[screenshot with 1.3.0](https://github.com/benoitjchevalier/playwright-screenshot/blob/main/screenshots/1.3.0.png)
[screenshot with 1.4.0](https://github.com/benoitjchevalier/playwright-screenshot/blob/main/screenshots/1.4.0.png)

I haven't tried width wise if the same issue happens.

**Comment by dgozman** [comment]
I can repro. Bisected down to [this](https://github.com/microsoft/playwright/commit/e8cf89572a4f220c52afdb768c52a17231caf058) Chromium roll.

**Comment by dgozman** [comment]
Bisected to this range: https://chromium.googlesource.com/chromium/src/+log/ac7726b8ebe3e40013ee60820f0c2c723bed44f4..7ecabc007eeaa4a53b225506d529070ce79143c4.

Suspecting https://chromium.googlesource.com/chromium/src/+/78ee2cc77ba093d5fa1ca57c27dadcc501a71ce2 that introduces ```capabilities_.max_render_target_size = 8192```.

**Comment by dgozman** [comment]
@benoitjchevalier We are working on the fix in upstream Chromium. Do you have an idea of what's the maximum size for screenshots you usually take with Playwright? Your test repo takes 1250x8440, but I guess the size might differ in other scenarios.

**Comment by benoitjchevalier** [comment]
@dgozman I don't really as our use of playwright is for a visual regression tool which is used by a bunch of teams internally. I've discovered it with 8440px but could see people trying to screenshot apps with longer body.
If there is a limitation in terms of allowing any size then knowing the max size will be good so we can work around it by splitting screenshots

**Comment by dgozman** [comment]
For the record: [upstream issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1137291) has been fixed in [r817038](https://crrev.com/817038).
