### ISSUE TITLE
[Feature] BrowserContext.maximizeWindow()

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#4046]
**Note from maintainers:**

We recommend [setting a viewport](https://playwright.dev/docs/emulation#viewport) for setting the width / height and have a fixed viewport.

```ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        // It is important to define the `viewport` property after destructuring `devices`,
        // since devices also define the `viewport` for that device.
        viewport: { width: 1920, height: 1080 },
      },
    },
  ]
});
```

---

Selenium feature: https://www.selenium.dev/selenium/docs/api/py/webdriver_remote/selenium.webdriver.remote.webdriver.html#selenium.webdriver.remote.webdriver.WebDriver.maximize_window

Requested via Slack.

Scenario: Automate a website and then let the user complete something. Its great if the max possible width/height could be determined so the user has "maximum available viewport".

But not sure how or if its easy implementable since we in CR e.g. emulate the viewport independent from the window size.

For Chromium it works already like that:

```js
// @ts-check
const playwright = require('playwright');

(async () => {
    const browser = await playwright.chromium.launch({
      args: ["--start-maximized"],
      headless: false,
    });
    const context = await browser.newContext({
      viewport: null
    });
    const page = await context.newPage();
    await page.goto('http://whatsmyuseragent.org/');
    await browser.close();
})();
```

**Comment by linvaux** [comment]
It is a great feature

**Comment by shtlrs** [comment]
IT would be great to have this !

**Comment by gigitalz** [comment]
voting this up

**Comment by AlexKomanov** [comment]
Voting this up!

**Comment by tomekTieto** [comment]
+1 for this solution

**Comment by tmazumder** [comment]
in Selenium we have .maximize(), so de we have any such in playwright?

**Comment by dsebata** [comment]
Would really be great to have this

**Comment by starosta357** [comment]
Solution for Java:
![image](https://user-images.githubusercontent.com/18212153/143455840-f03711a5-5c23-4a6a-8428-c75e89a9af98.png)

**Comment by lmlikota** [comment]
Upvote.

**Comment by alterhu2020** [comment]
upvote

**Comment by sg0nzalez** [comment]
Upvote.

**Comment by doppelganger23** [comment]
Upvote

**Comment by AlexKomanov** [comment]
Upvote

**Comment by zy-su** [comment]
Upvote

**Comment by gvsharshavardhan** [comment]
> Solution for Java: ![image](https://user-images.githubusercontent.com/18212153/143455840-f03711a5-5c23-4a6a-8428-c75e89a9af98.png)

Unfortunately this is not working!

**Comment by pavelfeldman** [comment]
@azad-derakhshani-GS 
> allowing multiple people with different screens to work on testautomation without any problems (fixed viewport would be problematic because everyone has different monitors and resolutions)

This looks backwards to me: maximize would make pages behave differently, while fixed viewport guarantees consistent behavior. What do I miss?

**Comment by davidhprotective** [comment]
Upvoting!

**Comment by shibababa** [comment]
Upvoting

**Comment by azad-derakhshani-GS** [comment]
> @azad-derakhshani-GS
This looks backwards to me: maximize would make pages behave differently, while fixed viewport guarantees consistent behavior. What do I miss?

A well-designed page behaves consistently across different viewports, so this is nothing for the testautomation framework to worry about.
Trust me, in several years of TA experience, maximizing the browser window never caused any such issues, not even once.
It's also closer to the way a real user would behave.
But Playwright artificially shrinks the viewport so the pages aren't even displayed in full, which (despite it scrolling into elements) leads to page elements not being fully displayed while PW interacts with them.

**Comment by naveenanimation20** [comment]
Solution in Java:

try (Playwright playwright = Playwright.create()) {
				Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setHeadless(false));

Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
int width = (int)screenSize.getWidth();
int height = (int)screenSize.getHeight();
			
BrowserContext context = browser.newContext(new Browser.NewContextOptions().setViewportSize(width,height)
Page page = context.newPage();

**Comment by aalcatelz** [comment]
Upvote

**Comment by hoangngocanhskedulo** [comment]
Upvote

**Comment by davidhprotective** [comment]
Upvote

**Comment by dbhimar** [comment]
does anyone have solution in .net(c#)  for maximizing the browser window?

**Comment by mamoorkhan** [comment]
> does anyone have solution in .net(c#) for maximizing the browser window?

The following worked for me at last.
```
using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
{
    Headless = false,
    Args = new [] { "--start-maximized" },
    SlowMo = 100
});

var context = await browser.NewContextAsync(new BrowserNewContextOptions {
    ViewportSize = ViewportSize.NoViewport
});

var page = await context.NewPageAsync();
await page.GotoAsync("https://playwright.dev/dotnet/docs/intro");
```

**Comment by NitishJoggessur** [comment]
> > does anyone have solution in .net(c#) for maximizing the browser window?
> 
> The following worked for me at last.
> 
> ```
> using var playwright = await Playwright.CreateAsync();
> await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
> {
>     Headless = false,
>     Args = new [] { "--start-maximized" },
>     SlowMo = 100
> });
> 
> var context = await browser.NewContextAsync(new BrowserNewContextOptions {
>     ViewportSize = ViewportSize.NoViewport
> });
> 
> var page = await context.NewPageAsync();
> await page.GotoAsync("https://playwright.dev/dotnet/docs/intro");
> ```

Thanks Mamoorkhan,

At least the above now changes the browser size. But It is not maximizing to the full screen. Like only half - as if split screen with another app.

Any idea?

**Comment by dbhimar** [comment]
@pavelfeldman mamoorkhan

> > does anyone have solution in .net(c#) for maximizing the browser window?
> 
> The following worked for me at last.
> 
> ```
> using var playwright = await Playwright.CreateAsync();
> await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
> {
>     Headless = false,
>     Args = new [] { "--start-maximized" },
>     SlowMo = 100
> });
> 
> var context = await browser.NewContextAsync(new BrowserNewContextOptions {
>     ViewportSize = ViewportSize.NoViewport
> });
> 
> var page = await context.NewPageAsync();
> await page.GotoAsync("https://playwright.dev/dotnet/docs/intro");
> ```

@mamoorkhan Thanks, but still I am not seeing the maximized browser by using the above code

**Comment by mamoorkhan** [comment]
@NitishJoggessur and @dbhimar I was getting the same half screen maximised window wI was using only the --start-maximized flag, but when I added the viewport settings and created a new context for the page, it worked. I am using windows 10 x64 Enterprise. I am not sure if that helps.

**Comment by dbhimar** [comment]
> @NitishJoggessur and @dbhimar I was getting the same half screen maximised window when I was using only the --start-maximized flag, but when I added the viewport settings and created a new context for the page, it worked. I am using windows 10 x64 Enterprise. I am not sure if that helps.
@mamoorkhan 

I am also using the windows 10 x64


 _playwright = await Playwright.CreateAsync();

            _browser = await _playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
            {
                Headless = false,
                Channel = "msedge",
                Args = new[]
                    {
                        "--start-maximized"
                    },
            });
           _browserContext = await _browser.NewContextAsync();
            await _browserContext.Tracing.StartAsync(new()
            {
                Screenshots = true,
                Snapshots = true,
                Sources = true
            });
            _page = await _browserContext.NewPageAsync();
            await _browser.NewContextAsync(new BrowserNewContextOptions()
            {
                RecordVideoDir = "videos/",
                ViewportSize = ViewportSize.NoViewport
            });

above is the code which I am trying to maximize the browser window

**Comment by mamoorkhan** [comment]
@dbhimar you are recreating the context in the last line. try the following code

```
        _browser = await _playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
        {
            Headless = false,
            Channel = "msedge",
            Args = new[]
                {
                    "--start-maximized"
                },
        });
       _browserContext = await _browser.NewContextAsync(new BrowserNewContextOptions()
        {
            RecordVideoDir = "videos/",
            ViewportSize = ViewportSize.NoViewport
        });
        await _browserContext.Tracing.StartAsync(new()
        {
            Screenshots = true,
            Snapshots = true,
            Sources = true
        });
        _page = await _browserContext.NewPageAsync();

```

**Comment by AlexKomanov** [comment]
Upvote

**Comment by anandhaprakash-mani** [comment]
Upvote!

**Comment by trjo1016** [comment]
You can maximize the window by knowing which launch options each browser type has:

For Chromium, you need:  --start-maximized
For Firefox, you need: --kiosk

Currently trying to find out what to use for webkit.
Knowing this, you can set up launch options like this, when you are launching the browser:

`        List<String> launchOptions = new ArrayList<>();
        Playwright playwright = Playwright.create();

        // Change browser type
        BrowserType type = playwright.firefox();

        switch (type.name()) {
            case "chromium": {
                launchOptions.add("--start-maximized");
                launchOptions.add("--incognito");

                // Can be "msedge", "chrome-beta", "msedge-beta", "msedge-dev", etc.
                String browserChannel = "chrome";

                browser = type.launch(new BrowserType.LaunchOptions()
                        .setChannel(browserChannel)
                        .setHeadless(settings.enableHeadlessMode)
                        .setArgs(launchOptions)
                        .setSlowMo(settings.slowMoTime));
                
                break;
            }
            case "firefox": {
                launchOptions.add("--kiosk");
                launchOptions.add("--private-window");

                browser = type.launch(new BrowserType.LaunchOptions()
                        .setHeadless(settings.enableHeadlessMode)
                        .setArgs(launchOptions)
                        .setSlowMo(settings.slowMoTime));

                break;
            }
}`

**Comment by testgitdl** [comment]
Hello,

We also need this. We cannot get it to work. We need to maximize chrome because setting the viewport has downfalls - cannot really see the popup's in our up.

Thnaks!

**Comment by vishal7788** [comment]
We too need the maximized browser window. Viewport option splits the browser on my laptop and extended monitor desktop screen. Its funny to watch, half of the elements being interacted on laptop screen and other half on desktop :D

**Comment by mohanbabu-zumen** [comment]
How can I maximize the chromium window in **js**?

**Comment by vbhardwaj87** [comment]
How we can maximize the browser as per screen size in playwright Java

**Comment by SouhaB** [comment]
Hi,
I would be perfect if we have .maximize like selenium.
Meanwhile, this works for me (version 1.29 java)
`playwright = Playwright.create();
        browser = playwright.chromium().launch(new BrowserType.LaunchOptions()
        		.setArgs(List.of("--start-maximized"))
        		.setHeadless(false)
        		.setSlowMo(500));
        context = browser.newContext(new Browser.NewContextOptions().setViewportSize(null));
        page = context.newPage();`

**Comment by mohanbabu-zumen** [comment]
> Hi, I would be perfect if we have .maximize like selenium. Meanwhile, this works for me (version 1.29 java) ![image](https://user-images.githubusercontent.com/20262460/210746632-1a112e40-69fc-4c52-bfd2-7edb7ab0d729.png)

@SouhaB Any idea about JavaScript?

**Comment by dbhimar** [comment]
Does anyone find the solution to maximize the window using C#.net ?
@mamoorkhan its working for you?

**Comment by VasanthVJ** [comment]
Have tried all the possible ways but the maximize function isn't accurate. Also, when I launch browser browser in my extended screen I had to maximise  manually, the inner page remains cropped and doesn't adopt the screen size. I am getting the feeling the maximise function is not accurate as Selenium.

**Comment by mohanbabu-zumen** [comment]
> Have tried all the possible ways but the maximize function isn't accurate. Also, when I launch browser browser in my extended screen I had to maximise manually, the inner page remains cropped and doesn't adopt the screen size. I am getting the feeling the maximise function is not accurate as Selenium.

Yes, The same is occurring to me as well. It would be great If they address it ASAP!

**Comment by areeba-shuja-10p** [comment]
Hello.
Following worked for me!

    {
      name: "chromium",
      use: {
        ...devices["Desktop Chromium"],  
        viewport: null,
        launchOptions: {
          args: ["--start-maximized"]
        }
      },
    },

Thanks,

**Comment by AlllxT** [comment]
List<String> args = new ArrayList<>();
        args.add("--start-maximized");
        args.add("--start-fullscreen");

        browser = playwright.chromium().launch(new BrowserType.LaunchOptions()
                        .setArgs(args)
                        .setHeadless(false)
                );

It doesn't work..

Firstly it set window to full, then it returns back the start sizes

**Comment by heenavasdani** [comment]
Upvote!

**Comment by heenavasdani** [comment]
@mxschmitt , is there any workaround for it in .net when using PageTest class?

**Comment by shridhar007** [comment]
Following code worked for me. 
![image](https://github.com/microsoft/playwright/assets/948365/7acce670-27f7-49d9-824c-3f37b7659682)

**Comment by EugeneMac** [comment]
Proposed solution for .NET doesn't work for me as well. The page is still cropped and in case of dynamic UI interface with react controls and stuff PW works weird time to time which leads to flakiness for some tests. What frustrates the most the glitches often happen at nightly run on TeamCity agent and almost never when you run the same test from you laptop browser. When I inspect the trace I don't even see some controls. When I open the trace viewport in a new page at fullsize - I see the controls. So the feature is anticipated. At least as a workaround maybe there is a way to launch Chrome in some mode when it fits all the content on one viewport (zooming out the page maybe?) like it is possible in Chrome inspector.

**Comment by siddharth2023** [comment]
Bump!

**Comment by shisrafilov** [comment]
Bump

**Comment by benVicarius** [comment]
> Solution for Java: ![image](https://user-images.githubusercontent.com/18212153/143455840-f03711a5-5c23-4a6a-8428-c75e89a9af98.png)

This definitely worked for me, thanks @starosta357 !!!

**Note: using playwright version 1.43.0**

**Comment by OleksandrKovalenko2** [comment]
Upvote!

**Comment by OleksiiT** [comment]
Up!

**Comment by vshulha** [comment]
Would be great to have such feature in .NET. Thanks in advance

**Comment by shisrafilov** [comment]
In Python too.

**Comment by PeterHevesi** [comment]
@mxschmitt, would you please tell us, if you ever plan to implement this, or what is the current status of this issue?
There are already almost 100 likes on this issue, and for me it is absolutely important for Firefox to work reliably !
Please focus on this feature ASAP, it is very important for many people, thanks so much :)

**Comment by PeterHevesi** [comment]
I have found this awesome tool called [Metalama](https://www.postsharp.net/metalama) based on Roslyn (they have their own fork of Roslyn), that can do AOP, but beside that, can also generate code (new fields and properties, new methods and even classes) and you can specify order of those "Metalama aspects" there! While not needing any additional compilations !
It can't solve the problem with built-in .NET's Roslyn generators, as all "Metalama aspects" run after Roslyn source generators..
But at least while using Metalama, you can specify order between those "aspects" without performance killing !

**Comment by oscartorres9** [comment]
bump

**Comment by mxschmitt** [comment]
Please see the maintainers note in the [issue description](https://github.com/microsoft/playwright/issues/4046#issue-713826638).

**Comment by PeterHevesi** [comment]
This is crazy... I don't understand, why you don't want to solve this issue... You could recommend us to use exact ViewPort size...
But YOU ARE NOT LISTENING TO US !!! We have a problem with this approach! Do you understand?

**Comment by olasak-vendavo** [comment]
> Hello. Following worked for me!
> 
> ```
> {
>   name: "chromium",
>   use: {
>     ...devices["Desktop Chromium"],  
>     viewport: null,
>     launchOptions: {
>       args: ["--start-maximized"]
>     }
>   },
> },
> ```
> 
> Thanks,

This doesn't work any more.

<img width="792" height="38" alt="Image" src="https://github.com/user-attachments/assets/08ff7c53-9d5f-4934-9604-4e1f042b1096" />

**Comment by BlackDragonBE** [comment]
5 years. 5 f**** years of no full screen. Is this some kind of joke? I need to be able to make videos go actual full screen, but I can't automate that step in any way. The video is never nicely on the screen, and the top of the browser is still visible. You even patched out the one workaround.
