### ISSUE TITLE
[Question] Is it possible to launch windows browsers from WSL environment?

### ISSUE THREAD

**Issue by ezhikov** [microsoft/playwright#4047]
Hello. I'm using WSL for development, but Windows IDE and browsers for debug. I don't want to pollute windows part with all kind of tools that is hard to manage, like node, npm and git, but I also don't want to waste large amount of time to get something actually running with GUI in WSL (at least before promised native support), so I'd like to run node and Playwright in Linux part and see results in Windows part (just like I do with my dev server). Is it possible?

**Comment by yury-s** [comment]
IIUC you want to launch the browsers with GUI in the Windows host but control the execution from playwright running in WSL. It could be achieved by launching playwright browser [server](https://playwright.dev/#version=v1.5.2&path=docs%2Fapi.md&q=browsertypelaunchserveroptions) in the host system and exposing the websocket to the linux running under WSL, where you could connect to it using [`browserType.connect()`](https://playwright.dev/#version=v1.5.2&path=docs%2Fapi.md&q=browsertypeconnectoptions). Using Windows IDE for debugging is going to be tricky in this case though. The easiest solution is likely to run in headless mode on linux under WSL.

**Comment by ezhikov** [comment]
Great. Thank you.

**Comment by ecalcutin** [comment]
Link is invalid now. Can someone post a solution?

**Comment by nite** [comment]
Googled it for you :) https://playwright.dev/docs/api/class-browserserver
