### ISSUE TITLE
[BUG] page.coverage.stopJsCoverage returns wrong coverage info.

### ISSUE THREAD

**Issue by angryai** [microsoft/playwright#4049]
**Context:**
- Playwright Version: 1.2.1
- Operating System: Windows
- Node.js version: 10.19.0
- Browser: Chromium

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
		// Once the app is loaded, Stop the coverage gathering
		const [jsCoverage, cssCoverage] = await Promise.all([
			page.coverage.stopJSCoverage(),
			page.coverage.stopCSSCoverage(),
		]);

		for (const entry of jsCoverage) {
				let usedBytes = 0;
				let totalBytes = entry.source.length;
				let blockMap:any = [];
				entry.functions.filter((x:any) => x.functionName !== "" && x.isBlockCoverage === true).forEach((element: any) => {
					element.ranges.filter((y:any) => y.count !== 0).forEach((functionRange:any) => {
						const start = functionRange.startOffset;
						const end = functionRange.endOffset;

						let didMerge = false;
						for (const range of blockMap) {
								if (start <= range.start) {
									if (end >= range.end) {
										range.start = start; 
										range.end = end;
										didMerge = true;
										break;
									}
									else if (end >= range.start){
										range.start = start;
										didMerge = true;
										break;
									}
								}
								else if (start > range.start && start <= range.end) {
									if (end >= range.end) {
										range.end = end;
										didMerge = true;
										break;
									}
									else if (end < range.end) {
										didMerge = true;
										break;
									}
								}
							}
						
							if (didMerge === false)
							{
								blockMap[blockMap.length] = {start:start, end:end};
							}
						});
					});
					
				for (const range of blockMap) {
					usedBytes += range.end - range.start;
				}

				console.log(`${entry.url}: ${usedBytes*100.0/totalBytes}`);
		}
```

**Describe the bug**
As it exists today, the jsCoverage returned by the page.coverage.stopCoverage method seems to return the wrong coverage info for JS files. The above code which I put together by iterating through all the functions and merging their ranges and summing over the result, ,seems to return > 99% coverage for files which I can see are covered close to 30% when I run devtools. 

Based on the above, there are two requests : 

1. Is there a bug here ? or am I doing something wrong in the above method ? 
2. Can we please have a code snippet to calculate the coverage of an entire JS file ? It would help if the returned output was 
not overlapping so that it was easy to calculate per file. Something similar to the puppeteer API - https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#coveragestopjscoverage which makes it straightforward to calculate coverage per JS file and not have to deal with blocks/functions.

Thanks!

**Comment by ozcoder** [comment]
I don't see where **blockMap** gets the initial _range_ object, so won't it always be empty, and thus the **for** loops won't do anything?

**Comment by pavelfeldman** [comment]
Could you share more about why you are using coverage?

**Comment by angryai** [comment]
Hi Pavel, 

I'm using coverage to automate detection and prevention of further unused code being added to the JS bundles being downloaded at runtime. 

The automated test above loads a page, looks at the JS files' code coverage within, and fails if the coverage is below a pre-configured limit. (This limit is currently hardcoded to be the minimum coverage we want).

**Comment by pavelfeldman** [comment]
Got it. The reason it is different from Puppeteer is that we decided to return the raw v8 output so that third party tools like https://github.com/istanbuljs/v8-to-istanbul worked out of the box. Could you see if you could merry our output with the v8 -> istanbul tools?

**Comment by angryai** [comment]
Hi Pavel, 

Thanks for your comment! 

1. I tried that, but it seems like the coverage data returned by playwright doesn't work with v8-to-istanbul either (throws an error (node:40420) UnhandledPromiseRejectionWarning: **TypeError: blocks.forEach is not a function**
    at V8ToIstanbul.applyCoverage (E:\node_modules\v8-to-istanbul\lib\v8-to-istanbul.js:98:12)
    at ClientRequest.<anonymous> (E:\test.ts:31:23))

Here's the simple script I am using : 

[test.txt](https://github.com/microsoft/playwright/files/5884631/test.txt)


2. I haven't found any examples on any playwright forums/blogs that seem to measure JS code coverage accurately with Playwright - either with or without v8-to-istanbul. This makes me believe that the coverage API might be busted.

3. Even if not, it would be helpful to have a simple API that provides the JS/CSS coverage % like we see in the Devtools. 

4. Also, apparently v8ToIstanbul requires the original source of the JS file, which just seems like a strange hoop to jump through when all you're measuring is the coverage and might not have the original JS file source available. I had to download the file from the URL for this, but seems strange. 



Please let me know in case I can try anything else. Can you provide a simple playwright script that measures code coverage accurately for 1 entire JS file ?

**Comment by gsai0205** [comment]
Any update on this please? @angryai Did you find any workaround?

**Comment by gullerya** [comment]
@angryai - one question / clarification regarding your original question and script - how (and actually do) you getting that `isBlockCoverage` truthy?

To me, it is always `false`, which means that according to your script you'd never get anything after the very first `filter`.

Beside that, it is working well to me (I'm not using Istanbul, but my own proc), while my assumptions are:
- any function is treated like a new scoped range
- top level nameless function is the whole module's top level scope
- functions can only be nested, never partially overlap (obviously), so your conditional flow B > A in the inner loop shouldn't really happen
- the start/end offsets are not enough, they'll always be all inclusive in them selves, but also take into consideration the `count` property, which actually signals if that range was executed or not

Makes sense?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
