### ISSUE TITLE
[Question] Can I watch for changes in a specific element?

### ISSUE THREAD

**Issue by Ron-SSG** [microsoft/playwright#4051]
Hi!

I'm trying watch for changes in a certain `div` that keeps getting new elements added to it.
I couldn't seem to find a proper way of listening to such "change" event via the API, am I missing something? 

Thanks in advance.

P.S: I though about using `MutationObserver` but `page.$$('.someClass')` isn't returning a `Node` type object (not to mention the workaround of using `window` in a nodejs environment just to be able to use `MutationObserver`).

**Comment by dgozman** [comment]
There is no such API. Using [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) is a good way to achieve this. Note that you have to evaluate the whole script in the page context:

```js
// Get a handle to the div.
const divHandle = await page.$('text=Target div');
await divHandle.evaluate(div => {
  new MutationObserver((mutationsList, observer) => {
    // Handle mutations.
  }).observe(div, { childList: true, subtree: true });
});
```

Does this answer your question?

**Comment by Ron-SSG** [comment]
@dgozman thank you for answering.

That didn't seem to detect the addition of child divs, here's my code:

```javascript
const myClassHandle = await page.$('.myClass');

const window = new Window();
await myClassHandle.evaluate((div) => {
	new window.MutationObserver((mutationsList, observer) => {
		console.log(`Mutation Detected!`);
	}).observe(div, { childList: true, subtree: true });
});
```

Any idea why?

Just to clarify if my div looks like this:

```html
<div class="myClass display-inline">
	<div class="mySubClass display-inline-block">...</div>
	<div class="mySubClass display-inline-block">...</div>
	<div class="mySubClass display-inline-block">...</div>
</div>
```
And I'm trying to detect any `mySubClass` divs when they are being added inside `myClass`.

**Comment by dgozman** [comment]
How do you detect whether you've got any mutations? Perhaps you are not waiting for it? Here's a sample that waits for at least two `mySubClass` divs:

```js
await myClassHandle.evaluate((div) => {
  return new Promise(resolve => {
    new window.MutationObserver((mutationsList, observer) => {
      // Assuming all children are 'mySubClass'. If not, add more logic here to determine whether
      // we are done.
      if (div.childElementCount >= 2)
        resolve();
    }).observe(div, { childList: true });
  });
});
```

Do you get any errors or unhandled promise rejects? Also, you probably don't need the `window = new Window()` anymore, try removing it.

**Comment by dgozman** [comment]
Another solution would be to use [waitForFunction](https://playwright.dev/#version=v1.4.2&path=docs%2Fapi.md&q=pagewaitforfunctionpagefunction-arg-options).

```js
await page.waitForFunction(() => {
  return Array.from(document.querySelectorAll('.myClass > .mySubClass')).length >= 2;
});
```

**Comment by Ron-SSG** [comment]
> How do you detect whether you've got any mutations? Perhaps you are not waiting for it? Here's a sample that waits for at least two `mySubClass` divs:
> 
> ```js
> await myClassHandle.evaluate((div) => {
>   return new Promise(resolve => {
>     new window.MutationObserver((mutationsList, observer) => {
>       // Assuming all children are 'mySubClass'. If not, add more logic here to determine whether
>       // we are done.
>       if (div.childElementCount >= 2)
>         resolve();
>     }).observe(div, { childList: true });
>   });
> });
> ```
> 
> Do you get any errors or unhandled promise rejects? Also, you probably don't need the `window = new Window()` anymore, try removing it.

It worked! Also, you were right, no need to use `window` at all because inside `evaluate` i'm using the browser/page context and it already exists there.

the only thing I wasn't able to do is to access the div it self, for example

```javascript
await myClassHandle.evaluate((div) => {
  return new Promise(resolve => {
    new window.MutationObserver((mutationsList, observer) => {
      if (div.childElementCount >= 1) {
        const myInnerElement = await div.$$('.inner-element') // this won't return anything, expecting an array of inner-elements
        resolve();
      }
    }).observe(div, { childList: true });
  });
});
```

**Comment by dgozman** [comment]
> the only thing I wasn't able to do is to access the div it self, for example
> 
> ```js
> await myClassHandle.evaluate((div) => {
>   return new Promise(resolve => {
>     new window.MutationObserver((mutationsList, observer) => {
>       if (div.childElementCount >= 1) {
>         const myInnerElement = await div.$$('.inner-element') // this won't return anything, expecting an array of inner-elements
>         resolve();
>       }
>     }).observe(div, { childList: true });
>   });
> });
> ```
> 
> Any idea on how to get it?

This is not going to work, because you are trying to use Playwright Node.js API in the web page. [See here](https://playwright.dev/#version=v1.4.2&path=docs%2Fcore-concepts.md&q=execution-contexts-nodejs-and-browser) for some explanations of page vs node execution context.

You can use any web apis in evaluation scripts instead, e.g. `div.querySelectorAll('.inner-element')`.

**Comment by Ron-SSG** [comment]
Thanks a lot for all the help!

I ended up using [`page.exposeFunction()` ](https://playwright.dev/#version=v1.4.2&path=docs%2Fapi.md&q=pageexposefunctionname-playwrightfunction) to allow me to use the Node.js API like so:
```javascript

const myClassHandle = await page.$('.myClass');

page.exposeFunction('myNodeFunc', async () => {
	externalNodeFunc(myClassHandle);
});

await myClassHandle.evaluate((div) => {
  return new Promise(resolve => {
    new window.MutationObserver((mutationsList, observer) => {
      if (div.childElementCount >= 1) {
        myNodeFunc();
        resolve();
      }
    }).observe(div, { childList: true });
  });
});

// Find the latest element added to the div and get its internals
const externalNodeFunc = (myClassHandle) => {
  const whatIWantedToFind = await myClassHandle.$$('.mySubClass');
  const lastChildAdded = await whatIWantedToFind[ whatIWantedToFind.length -1 ].$$('.inner-element');
}
```

Hope this could help someone in the future 😄 
Thanks again @dgozman !

**Comment by dgozman** [comment]
You are welcome 😄

**Comment by hungdao-testing** [comment]
Hi all,

Thanks for interesting topic, I am curious about how we observe the changes for attribute (im my case: `style`) in a HTML tag. 

When I scroll the table, the value of the attribute `style` will be updated to a certain value. If I could know when the changes are applied to DOM for the certain element, I could add it to custom `scroll` function to handle waiting

![image](https://user-images.githubusercontent.com/51052135/180641321-f8a42ce4-ac00-4f92-bd8b-bce4d68bf50c.png)

**Comment by dgozman** [comment]
@hungdao-testing You can do something like this today:

```js
await expect(page.locator('.my-element')).toHaveAttribute('style', 'top: 47px; transform: translated3d(0px, 0px, 0px);');
```

Alternatively, if `style` value is unpredictable, you can write a function to [wait for](https://playwright.dev/docs/api/class-page#page-wait-for-function):
```js
await page.waitForFunction(() => {
  const e = document.querySelector('.my-element');
  return parseInt(e.style.top, 10) >= 47;
});
```

**Comment by AndersonEngenheiro** [comment]
Hi, guys.

This code below works  when I'm using on console dev browser, but I could not use them on playwright.
I try somethings that I read here, but not work. Someone could "translate" my code to playwright ?
Thank you so much.


```
let list = document.querySelector('.results > span')

let mutationObserver = new MutationObserver(function(mutations) {
    mutations.forEach( mutation => {
        mutations.forEach(record => {
            const number = record.target.nodeValue
            console.log(number);
        })

    });
  });
 
  mutationObserver.observe(list, {
    characterData: true,
    childList: true,
    subtree: true,

  });
```
