### ISSUE TITLE
[BUG] Imossible to add and read cookies

### ISSUE THREAD

**Issue by 90sidortAP** [microsoft/playwright#4057]
**Context:**
- Playwright Version: 1.4.2
- Operating System: Ubuntu 20.4
- Node.js version: 10.15.1
- Browser: Chromium]

**Code Snippet**

```javascript
  beforeEach(async function fn() {
    this.timeout(20000);
    browser = await chromium.launch({ headless: false });

    const context = await browser.newContext();
    page = await context.newPage();

    await page
      .goto("http://localhost:4200/#/login", {
        waitUntil: "networkidle0",
      })
      .catch(() => {});
  });
```
```javascript
      await context.addCookies([
         { name: "csrftoken", value: cookieToken, path: "/" },
         { name: "sessionid", value: cookieSession, path: "/" },
       ]);
       await context.cookies();
```

**Describe the bug**

No matter what I do I get an error (either X.cookies is not a function or X.addCookies is not a function). I tried with context, page.context. browserContext etc. and it always ends up in the same way (ok, page.context as well as browserContext are undefined so error is different).

**Comment by arjun27** [comment]
Hey @90sidortAP, can you share a more complete snippet? I suspect that the context in scoped to `beforeEach` and when it's used later, the name is referring to something like. You could use something like this:

```js
let context = undefined;

beforeEach(async () => {
  // ...
  context = await browser.newContext();
});

it('is a test', async () => {
  await context.addCookies(...);
});
```

**Comment by 90sidortAP** [comment]
My bad, thank you @arjun27

**Comment by akapitoha** [comment]
hi @arjunattam 
below is a bit modified example of mocha runner from playwright docs
```
const {chromium} = require('playwright');
const assert = require('assert');

let browser;
before(async() => {
  browser = await chromium.launch();
});
after(async () => {
  await browser.close();
});
let page;
beforeEach(async() => {
  page = await browser.newPage();
});
afterEach(async () => {
  await page.close();
});

it('should work', async () => {
  await page.click('smth');
});

it('should work too', async () => {
  await page.click('smth');
});
```
imagine, both tests require login. could you please give a tip what's the best way here to share authentication here? would be also great to have an ability to, for example, `skip` first test and still have ability to login for the 2nd one if required (if I launch only this test). thank you in advance
