### ISSUE TITLE
Detecting page changes when only text re-renders[Question]

### ISSUE THREAD

**Issue by barakbs1** [microsoft/playwright#4060]
Hi everyone,

So first of all its worth mentioning that the app I'm testing is react.js based. Regardless of this fact, most actions in the app causes many components to render, so it's quite easy to use waitForSelector method. Nonetheless, there's a specific case I've yet to find fitting solution for - actions which causes only text to re-render. That means that, following a certain action (button click), all the component in the page stays the same, and only the text changes. I thought of two options to detect page changes:
1. Save the text in the page to a variable, and following action check if the text have changed every x milliseconds. Although this option works, it is very unstable, as the texts in our app changes constantly by non-programmers.
2. The even less preferred option of using waitForTimeout for say 5 seconds following action.

I think these two options are far from ideal, can you guys recommend about better options?

**Comment by dgozman** [comment]
If you know the expected text after the change, you can use `waitForSelector`:

```js
await page.click('button');
await page.waitForSelector('text=Expected text');
```

Does that work?

**Comment by dgozman** [comment]
In this case, using [`waitForFunction()`](https://playwright.dev/#version=v1.4.2&path=docs%2Fapi.md&q=pagewaitforfunctionpagefunction-arg-options) that compares text against the old one is the right solution.

However, perhaps you could wait for something else? For example, if the text change happens after particular xhr/fetch, you could use [`waitForResponse`](https://playwright.dev/#version=v1.4.2&path=docs%2Fapi.md&q=pagewaitforresponseurlorpredicate-options).

**Comment by barakbs1** [comment]
That might be a good idea, thanks!

**Comment by pavelfeldman** [comment]
Closing for now!

**Comment by barakbs1** [comment]
Good idea, I'll try that
