### ISSUE TITLE
[Question] How can we integrate Lighthouse with playwright

### ISSUE THREAD

**Issue by sunnysachdeva99** [microsoft/playwright#4064]
I want to know if there is any way to integrate https://github.com/GoogleChrome/lighthouse with playwright as Lighthouse invokes its own chrome sessions via CLI or as a chrome extension.

**Comment by pavelfeldman** [comment]
Could you share more about your use case? We would need to hand over the CDP session to Lighthouse, similarly to how DevTools does it when you run Lighthouse from the Audits panel, but that means that Playwright's capabilities after getting the session back will be limited.

**Comment by mxschmitt** [comment]
I saw this a few weeks ago, maybe it helps: https://github.com/abhinaba-ghosh/playwright-lighthouse

**Comment by pavelfeldman** [comment]
Please feel free to reopen in case other questions!
