### ISSUE TITLE
[Question] Run headless Firefox with non-default executable path

### ISSUE THREAD

**Issue by johnnyhuynh-dev** [microsoft/playwright#4075]
I followed the "Advanced Installation" guide and found a way to download the binaries browsers into the node_modules folder of my project instead of the default path.

```
# Linux/macOS
$ PLAYWRIGHT_BROWSERS_PATH=0 npm i -D playwright

# Windows
$ set PLAYWRIGHT_BROWSERS_PATH=0
$ npm i -D playwright
```
However, when I run the script it returns an error:

```
browserType.launch: Failed to launch firefox because executable doesn't exist at C:\Users\johnnyhuynh007\AppData\Local\ms-playwright\firefox-1171\firefox\firefox.exe
Try re-installing playwright with "npm install playwright"
```

I tried to modify the option 'executablePath' in the browserType.launch([options]) but got a similar error:
```
browserType.launch: Failed to launch firefox because executable doesn't exist at ../node_modules/playwright/.local-browsers/firefox-1171/firefox/firefox.exe
```

How could I specify the path of the executable for Playwright to run correctly? 

*Note: the reason I want this specific behavior is I need to upload my functions to Firebase Cloud functions, which doesn't seem to run normally with the default path option (seems like it doesn't install the browsers when it npm install package.json). By attaching the browsers to the **playwright** folder in **node_modules** and upload the whole folder, I hope it could solve the problem.

**Comment by mxschmitt** [comment]
Hi, the `PLAYWRIGHT_BROWSERS_PATH=0` environment variables needs to be set during installation (npm i) and during running your actual script (node foo.js). Seems like you run your script without the required environment variable.

**Comment by johnnyhuynh-dev** [comment]
> Hi, the `PLAYWRIGHT_BROWSERS_PATH=0` environment variables needs to be set during installation (npm i) and during running your actual script (node foo.js). Seems like you run your script without the required environment variable.

Hi, is there any way that I can override this environment variable in the code? The Cloud Functions I am using doesn't have an option to specify an environment variable when running the script.

**Comment by mxschmitt** [comment]
```js
// @ts-check
const playwright = require("playwright");

(async () => {
    // needs to be before the launch of the browser.
    process.env. PLAYWRIGHT_BROWSERS_PATH = "0";
    const browser = await playwright.firefox.launch();
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto('http://whatsmyuseragent.org/');
    await page.screenshot({ path: `example.png` });
    await browser.close();
  }
})();
```

Something like that should work.

**Comment by johnnyhuynh-dev** [comment]
I tried setting PLAYWRIGHT_BROWSERS_PATH=0 **node** theScript.js as you said and it worked perfectly. However, this `process.env.PLAYWRIGHT_BROWSERS_PATH = "0";` doesn't work. Any kind of **npm config** or .env setting that I can set it for once and don't need to call it again?
Sorry I am not too familiar with environmental variables.

**Comment by mxschmitt** [comment]
Are you running it on Google Cloud Functions?

**Comment by johnnyhuynh-dev** [comment]
> Are you running it on Google Cloud Functions?

I haven't tested on Google Cloud Functions yet, I am trying to test it on my local environment first. Do you have any suggestions for Playwright to work with GCF? All of what I am trying to do is to get it runs on GCF

**Comment by johnnyhuynh-dev** [comment]
After some more research I found that you wrote a buildpack for Heroku.

> https://playwright.tech/blog/running-playwright-on-heroku

I think Firebase has a very similar issue with that, which involved the setting of environmental variables or that sort of things.

**Comment by sunaram** [comment]
Just make sure you have set the environment variable before you require the "playwright" module.  
e.g. if app.js is your entry script, define
`process.env.PLAYWRIGHT_BROWSERS_PATH = 0; `
at the top .app.js

**Comment by dgozman** [comment]
Thanks @sunaram - that should do the trick!
