### ISSUE TITLE
[BUG] Response.body gives misinterpreted text instead of raw network buffer

### ISSUE THREAD

**Issue by Deathspike** [microsoft/playwright#4077]
**Context:**
- Playwright Version: 1.4.2
- Operating System: Windows 10 64-Bit (Build 2004)
- Node.js version: 12.19.0
- Browser: Chromium

**Code Snippet**

```javascript
const http = require('http');
const playwright = require('playwright-chromium');

const server = http.createServer((_, res) => {
  const buffer = Buffer.from('Flächendeckender Blitzzauber wird ausgelöst.', 'utf8');
  res.write(buffer);
  res.end();
  server.close();
}).listen(4567);

(async () => {
  const browser = await playwright.chromium.launch();
  const page = await browser.newPage();
  const response = await page.goto('http://localhost:4567');

  // Expected: Text is interpreted as the default encoding, not UTF-8.
  const text = await response.text();
  console.log(text); // -> FlÃ¤chendeckender Blitzzauber wird ausgelÃ¶st.

  // Unexpected: I should receive the buffer without text interpretation.
  const buffer = await response.body();
  const bufferText = buffer.toString('utf8');
  console.log(bufferText); // -> FlÃ¤chendeckender Blitzzauber wird ausgelÃ¶st.

  await browser.close();
})();

```

**Describe the bug**

When a HTTP server does not send a text encoding, Chromium naturally interprets received data using the default encoding. In this example, I've actually sent a 'utf8' encoded string. When using playwright, I expect `response.text()` to give me the misinterpreted data. That's exactly what happens.

But when I'm using `response.body()`, I expect the raw data from the network request. Yet it seems like `response.body()` just gives me a `Buffer` of the misinterpreted text. Shouldn't `response.body()` give me the raw data of the network request? I believe the code snippet I put above should work at the `response.body()` part.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by huw** [comment]
I think I’m seeing this while using `page.waitForResponse` to intercept responses. In this case, the API I’m using ([Remix](https://remix.run)) is replying with a custom `Content-Type` (`text/remix-deferred`). I don’t have this issue when hitting the API directly from my browser.

Did the issue ever get fixed? The close on this is ambiguous.

**Comment by Deathspike** [comment]
It's not fixed. It's closed because not enough people care about this. If you need to access raw, non-interpreted responses, you're better off avoiding playwright altogether. I cobbled together a solution that would abort the request in playwright, then use the request headers to send a raw request through node. Since nobody seems to care about this, that's your only route AFAIK.

**Comment by abuaziz** [comment]
@Deathspike 
Have you solved this problem？
