### ISSUE TITLE
[Feature] pass args to new context

### ISSUE THREAD

**Issue by joerg1985** [microsoft/playwright#4112]
Creating a new Context will ignore the args passed to the browser, this makes it impossible to create Contexts with the desired flags set. e.g. in my case it is --disable-back-forward-cache

**Comment by joerg1985** [comment]
One addition to this, a new context does not take the flags from the main process.
A manually opened incognito tab does take the current flags from the browser.

**Comment by pavelfeldman** [comment]
`--disable-back-forward-cache` is a browser launch flag, so it affects all the contexts created in that browser. Could you specify what your expectations are and how they are not met?

**Comment by joerg1985** [comment]
@pavelfeldman sorry for the late response, this code shows the current behaviour

```
const browser = await playwright['chromium'].launch({
    "headless": false, "args": [ '--disable-back-forward-cache' ]
});

const ctx = await browser.newContext();
const page = await ctx.newPage();
page.goto("about:flags");

await page.type('#search', 'back-forward-cache');
```
I would expect the page to show "Back-forward cache" is "Disabled", the page actually shows "Default". 

![flags](https://user-images.githubusercontent.com/16140691/97623560-1c407d80-1a26-11eb-887d-1eb9cb397367.png)

**Comment by dgozman** [comment]
@joerg1985 This is just Chromium UI showing you the "Back-forward cache" feature, but not the argument value. These are two different things in Chromium. If you go to `chrome://version` you can see `--disable-back-forward-cache` under the "Command Line".

Whether this means that specific behavior is enabled or disabled varies based on the behavior. Looking [at the code](https://source.chromium.org/chromium/chromium/src/+/master:content/common/content_navigation_policy.cc;l=48;drc=b56bf97a1ca6a95f927049ca0db5237304b3c240) for back-forward cache, the argument is checked before the feature, so passing the argument should disable it.
