### ISSUE TITLE
I am trying to use a proxy in Webkit and when I redirect once it loses the proxy. What am I doing wrong?

### ISSUE THREAD

**Issue by blakel58** [microsoft/playwright#4117]
const browser = await webkit.launch({
   headless: false,
   ignoreDefaultArgs: ["--enable-automation"],
   proxy: {
      server: `http://${proxyUse.host}:${proxyUse.port}`,
      username: proxyUse.username,
      password: proxyUse.password,
   }
});
const context = await browser.newContext();
const page = await context.newPage();

This will keep the proxy on the first page I go to, but after that the proxy is lost.

**Comment by pavelfeldman** [comment]
I can't repro this, will add a test shortly.

**Comment by blakel58** [comment]
Okay thank you. I noticed that a certain site you can reproduce it on and it is very strange. When on https://www.supremenewyork.com/shop/all you can see the proxy is set and used as the top time changes to the region (I am USA and when using a UK proxy I get LDN for the time) but as soon as I change to a category such as https://www.supremenewyork.com/shop/all/accessories you'll notice the time changes back. When I used puppeteer in the past I never had the issue, so I'm confused as to why this is occurring. I've tried in both js and go, and on webkit and chromium. Thanks for the response.

**Comment by pavelfeldman** [comment]
Closing it since we can't act on it w/o the repro. Please feel free to reopen it with the additional details!
