### ISSUE TITLE
[BUG] page.click() is inconsistent in large webapp

### ISSUE THREAD

**Issue by redsuperbat** [microsoft/playwright#4124]
**Context:**
- Playwright Version: 1.4.2
- Operating System: Mac
- Node.js version: 12.18.3
- Browser: Chromium
- Extra: Webapp that I am testing is running inside a docker container

Output from npx envinfo:
  System:
    OS: macOS 10.15.6
    Memory: 6.65 GB / 32.00 GB
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    npm: 6.14.6 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash

**Code Snippet**

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
 page = browser.newPage({
    logger: {
      isEnabled: (name, severity) => true,
      log: (name, severity, message, args) =>
        console.log(`${name} ${message} ${severity} ${args}`),
    },
  })
  it('should add a new item', async () => {
    const title = `${v1()}`; // Added v1 for uniqueness
    await page.click('button.sr-button');
    await page.click('li.sr-list-item');
    await page.click('li.sr-list-item');
    await page.click('button[test-selector=header-save-btn]'); // Sometimes clicks this button correctly sometimes not...
    await page.type('input[test-selector=modal-name-input]', title);
    await page.click('button[test-selector=modal-save-btn]');
    await page.waitForTimeout(500);
    await page.click('a');
    const newItem = page.$(`*css=tr >> text=${title}`);
    expect(newItem).toBeTruthy();
  });
 
})();
```

**Describe the bug**

I'm testing a large webapp written in vue and backbone.js. I have noticed inconsistencies with playwrights page.click api. Sometimes the element is clicked and sometimes it is not clicked. We have no animations that are delaying the render of the element nor hidden elements on top of the element supposed to be clicked.

An example of a problematic click event is displayed above. The selector is a custom attribute used specifically for testing.

When the click is unsuccessful the playwright logs says that the click event was a success, indicating that playwright found the element and clicked on it. This has forced me to write helper functions which executes the click event until the desired outcome is achieved. I am also quite new to testing so any help or discussion is appreciated.

**Comment by dgozman** [comment]
It is hard to say what's going on without the page url. However, I think this might be related to the common pattern where event listener is not added immediately, but after some async processing (react effect, xhr, timeout). I'd suggest to console.log when you add the listener and use `page.on('console', console.log)` to try debuging the issue. Btw, woes your page use React?

Unrelated suggestions:
- You probably don't need the `logger`. Are you interested in page console logs? If so, use `page.on('console', console.log)` instead.
- Why are you waiting for 500ms? Is something dynamic happening on the page? Perhaps, you just need the `<a>` element to be visible/enabled to click it? If so, `page.click` will wait for that automatically.

**Comment by redsuperbat** [comment]
Thanks for your reply. As stated in the post the webpage uses a combination of backbonejs and Vuejs. Unfortunately i cannot provide the url for you since the environment is not in production at the moment. Sorry about that.

Im waiting 500ms because the modal needs some time to leave the DOM tree and was blocking the anchor tag from being clicked.

I did not know about ```javascript page.on('console', console.log) ``` I will try this out when debugging next time and see how it works out. 

If issue is the async processing, what is the best way to resolve this issue? I have written several more tests that share this inconsistency and when running them all at least 10% of the tests fail. Most likely because of this issue. If this inconsistency continues we will have to switch to another E2E framework which would be a shame since I really like playwright. I have noticed that setting the slowMo to around ~200ms increases the success rate of the tests however I don't want to slow down the tests if it's not necessary.

**Comment by pavelfeldman** [comment]
Playwright is strict, if it is saying that it clicked the selector, that means that there was an element with this selector in the screen, the element was visible, received input events and it was clicked. If the page behaves like that did not happen, it means that the web app was not listening to the click. I.e. there was something like a lazy hydration where DOM is built first and listeners are added later. That works for human slow clicks, but computer is faster and it manages to click before the hydration.

Overall, having visible enabled, but not hydrated element in the screen is considered an application bug, so maybe you found a bug?

> Im waiting 500ms because the modal needs some time to leave the DOM tree and was blocking the anchor tag from being clicked.

Things like this suggest that there is animation-like behavior on the page and it could be responsible for the behavior you are observing. It is best to find selectors that appear after the navigation and anchor execution to them (wait for them to become visible, stabilize).

Could it also be that there are navigations between your clicks? Then you could be picking wrong (pre-navigation) elements in the clicks. Using `codegen` in `playwright-cli` could help you detecting if there are navigations - it emits the right code for those.

**Comment by pavelfeldman** [comment]
Closing as per above, please file it and link to this issue if it repros on 1.6!
