### ISSUE TITLE
[REGRESSION]: Browser Logger only capturing "api" type logs

### ISSUE THREAD

**Issue by alexduhanov** [microsoft/playwright#4125]
**Context:**
- GOOD Playwright Version: 1.2.0
- BAD Playwright Version: 1.4.2
- Operating System: MacOS 10.15.7

**Code Snippet**

```javascript
  test('Example test', async () => {
    browser = await playwright['chromium'].launch({
      logger: {
          isEnabled: () => true,
          log: (name, severity, message) => {
            console.log(name);
          },
        },
    });

    const context = await browser.newContext();
    const page = await context.newPage();

    await page.goto('localhost:3000/test.html');

    await page.waitForSelector('"Hello World"');

    await context.close();

    await browser.close();
  });
```

**Describe the bug**

Upgraded from Playwright 1.2.0 to 1.4.2 and noticed one of my tests that looks for a specific "browser" type log is failing.

Printing out all logs in version 1.4.2 for a basic test only shows "api" type logs, whereas in 1.2.0 I was seeing "browser" and "protocol" types as well. Tested this with Chromium, Firefox, and Webkit.

**Comment by alexduhanov** [comment]
I was able to rewrite my test using `page.on('console', function).`

However, the problem above may still be a regression and I was unable to find information about it in the changelog.

**Comment by arjunattam** [comment]
Thanks for reporting, @alexduhanov. This was caused due to the move to an internal wire protocol in 1.4.x. Were you using the browser logs for in-page console logs? Let us know if you had any other need for browser logs – we should be able to find a more reliable approach which is covered by the API.

**Comment by alexduhanov** [comment]
@arjunattam Correct - I have since switched to using `page.on` for checking this, which works a bit better for my needs.
