### ISSUE TITLE
How to use multiple Chromium/Firefox versions on single run

### ISSUE THREAD

**Issue by nisimjoseph** [microsoft/playwright#4135]
In my project I need to run tests on  with multiple Chromium versions, I search for an example but I can't find any which doing it.

in addition, I want to run specific tests only on specific browser, like Firefox or specific Chromium version.

any example of doing it?

**Comment by pavelfeldman** [comment]
Playwright only works with Chromium and Firefox versions it is bundled with, there is no way to specify a version.

**Comment by terryzfeng** [comment]
I'm trying to test for browser performance regression. Are there any plans to implement this as a feature, or would I need to roll back different versions of Playwright?

**Comment by Manuservus11** [comment]
Any updates on this, or any chance it could be reconsidered?
