### ISSUE TITLE
[BUG] [Webkit] page.innerText() result adding new line

### ISSUE THREAD

**Issue by laurentpayot** [microsoft/playwright#4151]
**Context:**
- Playwright Version: 1.5.0
- Operating System: Ubuntu 20.04 LTS
- Node.js version: 14.4.0
- Browser: WebKit

**index.html**
```html
<html><body>
    <button id="foo">
        <div>Foo</div>
    </button>
</body></html>
```
**debug.js**
```javascript
const { chromium, webkit, firefox } = require('playwright');

[chromium, webkit, firefox].forEach(async b => {
    const browser = await b.launch()
    const page = await browser.newPage()
    await page.goto('http://localhost:8000')
    const label = await page.innerText('#foo')
    console.log(`${b.name()} label = "${label}" (length of ${label.length})`)
    await browser.close()
})
```
Serve index.html using for instance
```
python3 -m http.server 8000
```
and run `node debug.js`, you'll get:
```
chromium label = "Foo" (length of 3)
webkit label = "Foo
" (length of 4)
firefox label = "Foo" (length of 3)
```
Note the new line at the end of the webkit `innerText` result.
Interestingly, if you replace the `button` tag in the html file by a simple `div` tag, there is no added new line for webkit.

**Comment by mxschmitt** [comment]
I tried to simplify the example a bit, so it seems it's caused by the `div` inside of the button. If you remove the div and only have the text, then it's fine. Good find!

Example: https://try.playwright.tech/?s=0r7ap

**Comment by pavelfeldman** [comment]
Browsers are different, that's why we did Playwright :) `page.innerText` gives you [HMTLElement.innerText](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText), which is layout-dependent. You might want to use [page.textContent](https://playwright.dev/#version=v1.5.1&path=docs%2Fapi.md&q=pagetextcontentselector-options) if you are asserting the text.

**Comment by laurentpayot** [comment]
@pavelfeldman If I add the following style:
```css
#foo {
  text-transform: uppercase;
}
```
`page.textContent` will only get `Foo` but `page.innerText` will get `FOO`, and the later is what I want to detect as that's what users will see.

> Browsers are different, that's why we did Playwright :) 

Isn't it precisely why `page.innerText` should return the same value whatever the browser is? :wink:
