### ISSUE TITLE
[Question] How to make POST request with postData override?

### ISSUE THREAD

**Issue by 000dry** [microsoft/playwright#4156]
Hi, I'm trying to use playwright to launch an application by POSTing directly into it with some form data, but in route.continue(...) it looks like the API doesn't support multiple overrides for a given route, and ideally I'd like to override both method and postData.

Is there any other way I can POST to a URL with form data?

**Comment by pavelfeldman** [comment]
Not sure I understand the question, but at the very least, `page.route` will be called as many times as there are requests and you can specify new postData every time it happens in `route.continue`. Or what are you trying to do?

**Comment by 000dry** [comment]
Hey, thanks for your response. Sure, I can specify postData every time, but I can't specify both postData and method every time.

In code, what I'd want to achieve is:

`await page.route('http://some-url.com/post-route', (route, request) => {
    const method = 'POST';
    const postData = 'foo=bar';
    route.continue({ method, postData });
});`

But the docs state you can override _one_ of method, postData and headers, and in practice this does seem to be the case. Puppeteer, conversely, seems to allow override of all request data, and I'm wondering if this sort of freedom to customise requests makes more sense?

`page.on('request', interceptedRequest => {
        const data = {
            'method': 'POST',
            'postData': 'foo=bar'
        };
        interceptedRequest.continue(data);
 });`

I have a workaround which is to have playwright load up my own html form as a mock entrypoint to our app, but it'd be cleaner if playwright could just go straight to the app as above.

Fyi if I override the method to POST, when I check the request type using request().method(), it always comes back as GET (even though my application does indeed receive a POST). This is playwright@1.5.0 running Chromium, MacOS 10.14.

Otherwise loving playwright btw :)

**Comment by pavelfeldman** [comment]
> But the docs state you can override one of method

It is a documentation bug, you can surely override any combination of those.

**Comment by 000dry** [comment]
@pavelfeldman thanks again for your response and for the fix on the docs.

However, the above code snippet I posted where I try to override both gives me 'null' when I log out request().postData() following an attempt to go to my target URL. However, if only override postData, and not both postData and method, then I can successfully log out the values I overrode.

Now of course its possible that my set up here is incorrect for launching my app (though I don't really believe this is the case), but the behaviour I'm seeing from calling .postData() and .method() on .request() are still unexpected.

**Comment by 000dry** [comment]
As an example below:

```
await page.route('http://some-url.com/post-route', (route, request) => {
    const method = 'POST';
    const postData = 'foo=bar';
    route.continue({ method, postData });
});

const response = page.goto('http

**Comment by pavelfeldman** [comment]
> response.request().postData() returns null
> response.request().method() returns "GET"

You are getting the original request here, not the one that you created via the override, so it looks good to me. The server is getting the right, overridden values, right?

**Comment by pavelfeldman** [comment]
(was auto-closed by a merge, reopening to get your reply)

**Comment by 000dry** [comment]
Yup it works, I had misunderstood the what the .postData() and .method() functions were supposed to return in this scenario. Thanks again for your responses.
