### ISSUE TITLE
[Question] Cannot read cookies from blank playwright page

### ISSUE THREAD

**Issue by majapw** [microsoft/playwright#4160]
I'm currently trying to build out the ability to render arbitrary React components in the browser via Playwright and run tests against them. I'm using the [`jest-playwright-preset`](https://github.com/playwright-community/jest-playwright) in my jest config. 

The general gist of my setup is:
1. Build a webpack bundle with an entrypoint that exposes `mount` and `unmount` functions on the `window` that will render a specific component when given a unique ID
2. Use jest with a custom playwright config to run the corresponding test files 
3. In jest's `setupFilesAfterEnv` run a playwright setup script that injects the aforementioned webpack bundle into the page using `page.addScriptTag` in a `beforeAll` block.
4. In the `beforeEach` of the test, call the `mount` function on the relevant component. 

At this stage, I get the following error in the browser:
```
Error: Failed to read the 'cookie' property from 'Document': Access is denied for this document.
    at cookie (frontend/foo/playwright/build/index.js:522:43)
    at initializeI18n (frontend/foo/playwright/build/index.js:27449:55)
    at new withHypernovaBootstrap(Component) (frontend/foo/playwright/build/index.js:21400:29)
    at Lg (frontend/foo/playwright/build/index.js:13923:171)
    at fi (frontend/foo/playwright/build/index.js:13965:149)
    at Rj (frontend/foo/playwright/build/index.js:14052:490)
    at Qj (frontend/foo/playwright/build/index.js:14035:265)
    at Kj (frontend/foo/playwright/build/index.js:14035:194)
    at yj (frontend/foo/playwright/build/index.js:14028:172)
    at Ig (frontend/foo/playwright/build/index.js:14019:137)
```
(as an aside, it'd be ideal if I could see this full error in the terminal. I'm currently piping console logs through using `page.on('console', (msg) =>console.log(`<browser> (${msg.type()}): ${msg.text()}`);` but the terminal prints out the highly mangled `<browser> (error): JSHandle@error {"extra":{"componentStack":"\n    in withHypernovaBootstrap(Component)\n    in withPhrases(withHypernovaBootstrap(Component))\n    in Router\n    in MemoryRouter\n    in WithStylesContextProvider\n    in withDirection(WithStylesContextProvider)\n    in GlobalThemeProvider\n    in ErrorBoundary\n    in VariationWrapper\n    in BootstrappedComponent\n    in withDirection(BootstrappedComponent)"}}`)

The code that is triggering this error is attempting to read the browser cookie in order to setup responsive breakpoints for the page. I think the problem comes from the fact that this anonymous page I'm building doesn't have a url. Are there any recommendations for this situation? I'm currently just running the code locally on my machine.

**Comment by pavelfeldman** [comment]
Not a Jest expert, but your plan looks good to me. The reason cookie isn't there is that your page does not have an origin, hence can't have cookies. This would be an ugly way to emulate origin:
```js
  await page.route('**/*', route => route.fulfill({ body: '<html></html>' }));
  await page.goto('http://origin');
  await page.unroute('**/*');
```

But maybe you could leverage routing to inject your webpack as a `<script src>` there, inside `<html>`, so it'll solve two purposes.

**Comment by pavelfeldman** [comment]
Also, we recommend creating page-per test, that way components won't affect each other. As of today, we are inviting customers to try out our new [@playwright/test](https://github.com/microsoft/playwright-test) runner that uses fixtures to make your tests isolated and elegant. Here is what it would look like in the @playwright/test terms:

```js
// test.spec.ts
import { it } from './fixtures';

it('component A', ({ mount }) => {
  mount('A');
});

it('component B', ({ mount }) => {
  mount('B');
});
```

```js
// fixtures.ts
import { folio as baseFolio } from '@playwright/test';
import type { Page } from 'playwright';

type TestFixtures = {
  // Page with exposed mount.
  playground: Page;
  // Mounting function.
  mount: (uniqueId: string) => Promise<void>;
};

const fixtures = baseFolio.extend<TestFixtures>();

// Define playground fixture that is a page with your webpack bundle.
fixtures.playground.init(async ({ page }, run) => {
  await page.route('**/*', route => route.fulfill({ body: '<html></html>' }));
  await page.goto('http://origin');
  await page.unroute('**/*');
  await page.evaluate(`
    window.mount = (id) => console.log('mount ' + id);
    window.unmount = (id) => console.log('unmount ' + id);
  `);
  page.on('console', console.log);
  await run(page);
});

// Define mount fixture that is a function that mounts your component.
fixtures.mount.init(async ({ playground }, run) => {
  const mountedIds = [];
  const result = async (uniqueId: string) => {
    mountedIds.push(uniqueId);
    await playground.evaluate(uniqueId => (window as any).mount(uniqueId), uniqueId);
  };

  await run(result);

  // Clean-up automatically
  for (const uniqueId of mountedIds)
    await playground.evaluate(uniqueId => (window as any).unmount(uniqueId), uniqueId);
});

const folio = fixtures.build();
export const it = folio.it;
export const describe = folio.describe;
```

Then you run it as
```sh
npm i @playwright/test
npx folio -p browserName=chromium
```
(or no parameter for all three browsers)

**Comment by pavelfeldman** [comment]
Closing as the original issue has a mitigation recipe.
