### ISSUE TITLE
[Question] elementHandle.waitForSelector followed by elementHandle.waitForElementState

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright#4175]
[waitForSelector](https://github.com/microsoft/playwright/blob/v1.4.0/docs/api.md#elementhandlewaitforselectorselector-options)  could be followed by a [waitForElementState](https://github.com/microsoft/playwright/blob/v1.4.0/docs/api.md#elementhandlewaitforelementstatestate-options) to e.g. make sure that an element is not moving, using the `stable` state.

Is this always the required workflow to achieve this, or was there ever an idea that `waitForSelector` could also somehow wait for the element to become stable?

**Comment by pavelfeldman** [comment]
It should be doable, but we discourage using element handles for operations and recommend using page/frame + a selector instead.

**Comment by thernstig** [comment]
For clarity, I actually do use `page.waitForSelector`. In the same essence then. Is it required to use `const element = page.waitForSelector()` and then `element.waitForElementState("stable")` to make sure an element is not moving?

Or would it be an idea that  `page.waitForSelector` already does this?

**Comment by pavelfeldman** [comment]
Why do you wait for it? I.e. what is following your wait? An action? A sceenshot? Something else?

**Comment by thernstig** [comment]
I think this was more of semantics i.e. is it a good idea for waitForElement() to be able to wait for something to be stable. I.e. in a screenshot scenario.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
