### ISSUE TITLE
[BUG] Unable to close page when confirm dialog is open

### ISSUE THREAD

**Issue by celeryclub** [microsoft/playwright#4179]
**Context:**
- Playwright Version: 1.4.2
- Operating System: macOS
- Node.js version: 12.18.3
- Browser: Chromium

**Code Snippet**

```javascript
const { chromium } = require('playwright-chromium');

(async () => {
  const browser = await chromium.launch({
    headless: false,
  });

  const page = await browser.newPage();

  await page.goto('https://opffc.csb.app');
  await page.waitForSelector('.ok');
  await page.click('.ok');
  await page.close();

  await browser.close();
})();
```

**Describe the bug**

Hey team. It seems like there's no way to close the current page if a confirm dialog is open. This causes some of my tests to time out unexpectedly.

**Comment by pavelfeldman** [comment]
I guess you never pass by the `await page.click('.ok');`. alert/prompt/confirm are blocking, so click won't finish until you consume the dialog.

**Comment by pavelfeldman** [comment]
Can still repro a problem on WebKit Mac (added a failing test)

**Comment by celeryclub** [comment]
Thanks for adding that test. Have you not been able to repro on Chromium?

**Comment by pavelfeldman** [comment]
Nope, does not repro on Chromium, the test passes there...

**Comment by aslushnikov** [comment]
@celeryclub in your example, you indeed never go past the `page.click` command; so the following would work:

```js
const { chromium } = require('playwright-chromium');

(async () => {
  const browser = await chromium.launch({
    headless: false,
  });

  const page = await browser.newPage();

  await page.goto('https://opffc.csb.app');
  await page.waitForSelector('.ok');
  page.once('dialog', dialog => dialog.dismiss());
  await page.click('.ok');
  await page.close();
  await browser.close();
})();
```

**Comment by celeryclub** [comment]
Right, it looks like `page.click` is never resolving. So does that mean that this is the expected behavior? An unhandled dialog will cause the test to time out?

**Comment by pavelfeldman** [comment]
Yes, unhandled dialog blocks JavaScript execution on the page, so the world stops. I.e. you get in the test what you get in the real life...

**Comment by pavelfeldman** [comment]
Closing this one since it has been replied to, but please feel free to file new issues in case of follow up ideas.
