### ISSUE TITLE
[Feature] Selectors being aware of default attributes

### ISSUE THREAD

**Issue by AntonNeld** [microsoft/playwright#4189]
It would be useful to have an option to make selectors aware of the default values of HTML attributes.

For example: The default type of an input element is "text". Currently, the selector 'input[type=text]' will match input elements where the type is set to "text" explicitly, but not input elements with no explicit type set.

This was a problem for us since the default configuration of [HtmlWebpackPlugin](https://webpack.js.org/plugins/html-webpack-plugin/) removes redundant attributes when bundling for production, which made our tests fail only when run against the bundled page.

Now that we know about it we can easily work around this by using other selectors in these cases or changing the Webpack config, but it would be nice to not have to do that.

**Comment by pavelfeldman** [comment]
> It would be useful to have an option to make selectors aware of the default values of HTML attributes.

While I think this is feasible, we wouldn't want to deviate from the CSS / XPath specs. Those rely upon DOM in a strict manner which makes them predictable and maintainable.

**Comment by pavelfeldman** [comment]
Closing as per above! Please feel free to reopen or file new if you have questions / suggestions.

**Comment by AntonNeld** [comment]
Sorry, forgot to reply! I don't have permission to reopen, it seems. Maybe you can reopen it? (Or leave it closed if you disagree with my suggestion below, since I don't have any further comments.)

Anyway, that sounds reasonable. Maybe it's worth a sentence or two in the selectors documentation, though? Something like: "CSS selectors will only see explicitly set attributes, not implicit defaults like type=text in an input field. Since redundant attributes may sometimes be removed when minifying (like when using the default configuration of HtmlWebpackPlugin), care should be taken when selecting on attributes that are set to their default values."

I have no idea how common it is that this happens, and if it's worth it to devote space in the documentation for it. So do with this what you will.
