### ISSUE TITLE
is there a way to not to close browser on error ? 

### ISSUE THREAD

**Issue by tanneerumahesh** [microsoft/playwright#4190]
Hi guys, I am using playwright with Gauge(https://gauge.org/) and want to capture screenshots on test failure. gauge does this by default but as playwright closes the browser immediately after the error, gauge screenshots are coming as blank because of this. is there a way to not close the browser on error? (and close it explicitly in after scenario). Thanks

**Comment by pavelfeldman** [comment]
Playwright does not close the browser on error, there must be something in your trst harness that does it.

**Comment by tanneerumahesh** [comment]
oh ok. thanks for confirming
