### ISSUE TITLE
[Question] How to prevent a crash after a 'page.evaluate' request ? (Playwright with Python)

### ISSUE THREAD

**Issue by Morbius01** [microsoft/playwright#4192]
My environment :
● Windows 7
● Python 3.7.6
● Playwright 1.5.1

I am a complete newbie with Playwright. I wrote the following Python app for testing purpose. This app uses sync_playwright and opens a browser in interactive mode, then connects to a Youtube video page, and displays every second (infinite loop), for the video being played :
● Current Time
● Duration
● Title

After several days of research, I found a way to display those parameters, using 'page.evaluate'.

My code is as follows :

```python
from playwright import sync_playwright
from time import sleep
playwright = sync_playwright().start()
browser = playwright.firefox.launch(headless=False)
page = browser.newPage()
page.goto('https://www.youtube.com/watch?v=O192eo9zbT4')
while True:
    current = page.evaluate("""() => {return document.getElementById('movie_player').getCurrentTime()}""")
    duration = page.evaluate("""() => {return document.getElementById('movie_player').getDuration()}""")
    title = page.evaluate("""() => {return document.getElementById('movie_player').getVideoData().title}""")
    print(current)
    print(duration)
    print(title)
    sleep(1)
```

While this app works fine, displays the correct values for the desired parameters, and accepts interaction from the user such as move forward/backward in the video or switch to the next video, it crashes when the user navigates to a non-Youtube video page, for instance the Youtube Login page. I get an error message : "playwright.helper.Error: Execution context was destroyed, most likely because of a navigation."

I have this problem with Firefox as well as with Chromium.

I understand why the error occurs, but I wish to be able to handle it with no crash.

What I have right now :
● On a Youtube video page : Current Time, Duration and Title are correctly acquired and displayed. No problem here.
● On a non Youtube video page : error and app crash due to the impossibility to perform the 'page.evaluate ...getElementById ...' instruction.

What I want :
● On a Youtube video page : Current Time, Duration and Title are correctly acquired and displayed. I already have this !
● On a non Youtube video page : either get the NULL values (0, 0, "") for the parameters or being able to handle the error myself, with no crash !

How do I need to modify my code ?

**Comment by pavelfeldman** [comment]
It throws because you navigate mid-evaluate, just catch it:

```py
from playwright import sync_playwright
from time import sleep
import sys

playwright = sync_playwright().start()
browser = playwright.firefox.launch(headless=False)
page = browser.newPage()
page.goto('https://www.youtube.com/watch?v=O192eo9zbT4')
while True:
    try:
        current = page.evaluate("""() => {return document.getElementById('movie_player').getCurrentTime()}""")
        duration = page.evaluate("""() => {return document.getElementById('movie_player').getDuration()}""")
        title = page.evaluate("""() => {return document.getElementById('movie_player').getVideoData().title}""")
        print(current)
        print(duration)
        print(title)
    except Exception:
        pass
    sleep(1)
```

**Comment by Morbius01** [comment]
@pavelfeldman
Many thanks for the speedy answer.

It works AOK !  Exactly what I wanted.
Maybe was more a Python issue (I have 8 days of experience with this language...)

Before trying Playwright, I have been playing around with Selenium Webdriver for 3 weeks, trying to achieve the same goal. The issue I had with Selenium was a performance problem : approximately 1.5 second to obtain the 3 values in the 'while' loop ! Even without the 1 second  'sleep' delay !  --> Impossible to use it for my app.

I wanted to try Puppeteer next, but found some positive feedback about Playwright while doing some research, so I decided to try Playwright first. The result is that Playwright works so well for me that I won't need to try anything else...

The last 2 issues I need to solve with my app (making use of Playwright) are :

1. Store session cookies somewhere while using the browser so that a user can login to his Youtube account through the Playwright browser, then close the app, then start it again and be connected back to his Youtube account without having to login again. I think that I saw a page with explanations on how to do that. Will have to try...

2. Save an extension installed on Playwright Firefox or Chromium browser so that the user can get it back when opening again the browser in a new session without having to install the extension again. Not sure this is possible though...

Well, I think I might post a new request again if I need help on this later...
	
Congrats to you and the Playwright team for a great product !

**Comment by pavelfeldman** [comment]
For (1) check out browserContext.cookies and browserContext.addCookies. That way you can log in, save cookies and then create new browser context and add them there. This new context will become "logged in".

There is nothing for (2) out of the box, but maybe you can use command line flags to run browser w/ extension on disk.

**Comment by pavelfeldman** [comment]
Closing this issue so that it did not turn into a thread, please feel free to file new issues / questions!
