### ISSUE TITLE
[Question]Can we generate a HAR? 

### ISSUE THREAD

**Issue by NareshMurthy** [microsoft/playwright#4194]
Is there a way to fetch all the network requests and responses  (headers and body) from a page?

**Comment by pavelfeldman** [comment]
We expose all the information modulo timing:

```js
page.on('request', request => ...);
page.on('response', response => ...);
```

should get you there. [Request](https://playwright.dev/#version=v1.5.1&path=docs%2Fapi.md&q=class-request), [Response](https://playwright.dev/#version=v1.5.1&path=docs%2Fapi.md&q=class-response)

**Comment by NareshMurthy** [comment]
Thanks @pavelfeldman 
Just a follow up question, Is there way I can switch between tabs, like how selenium does  `driver.switch_to.window(w)` ?

**Comment by pavelfeldman** [comment]
There is no need to switch tabs in Playwright, you can work with as many page objects as you'd like simultaneously.

**Comment by pavelfeldman** [comment]
Folding into #3206
