### ISSUE TITLE
[BUG] Using a typescript version thats too old gives a bad error message

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright#4203]
We support typescript versions >= 3.7.5. If a user installs playwright with an older typescript, it prints an ugly error about Unboxed not being generic, rather than something good about typescript being too old.

Pasting the error here for SEO purposes:
```
node_modules/playwright/types/types.d.ts:44:61 - error TS2315: Type 'Unboxed' is not generic.
```

- [ ] Update the docs to show the minimum typescript version
- [ ] Make use of [typesVersions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html#version-selection-with-typesversions) to give a nice error message or partial typings for older typescripts.

**Comment by pavelfeldman** [comment]
I don't think we got any external signals on this one, so maybe we are ok?
