### ISSUE TITLE
[BUG] Timout Error on firefox for popup

### ISSUE THREAD

**Issue by Sreejithw** [microsoft/playwright#4208]
**Context:**
- Playwright Version: 1.5.1
- Operating System: Windows
- Node.js version: 15.0.1
- Browser: firefox
- Extra: Also using jest version 26.6.0

I have a page with some links that opens on a new tab when clicked. I handle the opening of the new tab and get additional screenshots inside the new tab. But i get a timeout error for 'popup' event in firefox although its working perfectly for chromium. 

**Code Snippet**
```javascript
for(let[i,boxes] of content.entries()){      
       if((content.name).split('_')[1] == serviceName){
           const [page1] = await Promise.all([
                     page.waitForEvent('popup'),
                     frame.click(`#${boxes.id}`)
            ]);
            await page1.waitForLoadState('networkidle');
        }
}
```

Add any other details about the problem here.

**Comment by pavelfeldman** [comment]
I can repro this and it seems unrelated to the networkidle itself. As I open popups, rafs get throttled to the extent of being non-responsive. Investigating.

**Comment by Sue9445** [comment]
+1 @pavelfeldman i have the same problem
