### ISSUE TITLE
[Feature] Add WaitForRedirects as additional waiting option

### ISSUE THREAD

**Issue by mrudulp** [microsoft/playwright#4209]
_Let us know what functionality you'd like to see in Playwright and what is your use case._
One can log/capture all redirects using `page.route(url, handler)`
If there is a waitForRedirect then it can be useful in places where one cannot use `waitForNavigation`  since system under test _(for eg: Salesforce sandboxes or scratch orgs[Basically cloud based development environments])_  does lot of redirects and `waitForNavigation` always timeout.
By waitingForRedirects to complete with certain quiet timeout period, user is closer to usable System for subsequent calls.
After waitingForRedirect, one would then be able to either waitForSelector in subsequent call for a fairly small timeout period or start using system, since one would be fairly sure the system is ready for use.

_Do you think others might benefit from this as well?_
Any one using cloud based development environments for test automation would benefit from it

**Comment by pavelfeldman** [comment]
I would recommend bumping the navigation timeout or removing it altogether. Waiting for the redirects is risky since in case of the redirect loop, it'll wait indefinitely, which is equivalent to removing the timeout altogether.

**Comment by mrudulp** [comment]
Probably I was not clear or there is still something I don't understand...
here is a code I took from slack or documentation ->
`self.page.route('**', lambda route, request: self.log_and_continue_request(route, request))`
where 
```
    def log_and_continue_request(self, route, request):
        print(request.url)
        route.continue_()
```
When I run this I notice it prints request urls and finally after sometime it stops doing that. The timing of "request urls ending" is very close to lazily loaded elements being visible for further interaction. I was thinking if I had some kind of timer there( _log_and_continue_request_ ), it can be a waiter function itself.
This itself is the motivation for the feature request.

Now I don't understand why such request urls would continue for ever or in multiple loops leading to indefinite wait. Ideally there would be N such requests and then site would wait for further input from user as it has got all necessary data to plot on the screen. Isn't it this the case for most web based systems or is there something else I don't understand which makes an indefinite wait scenario.

**Comment by pavelfeldman** [comment]
A bit hard to analyse this without the full context. The symptoms suggest that you program simply completes. You are waiting for this interactable element to appear, perform the action and the program completes. You are using synchronous API, so when the main control flow reaches the end, things are done. You could add `page.waitForTimeout(1000000)` in the end of your program to make it wait for a long time, that way events will keep coming and will be processed. Alternatively, if you are familiar with `asyncio`, you could use async API - this situation is self-explanatory there.

**Comment by pavelfeldman** [comment]
Closing for now, please feel free to open a follow-up issue with comments of additional information!
