### ISSUE TITLE
[Question]Test fails once in while for page.waitForSelector after page.click

### ISSUE THREAD

**Issue by emil45** [microsoft/playwright#4213]
We have a test that simulating a search+autocomplete feature.
This is the simple flow we are doing:

```
await this.page.type(searchInput, text);
await this.page.click('[data-testid="autocomplete-result"]');

await this.page.waitForSelector('[data-testid="search-result"]');
await this.page.click('[data-testid="search-result-button"]');
```

We are clicking the first autocomplete first,
Then we are clicking the first search result 
(there is a button inside the `search-result`, so we are waiting for the whole div).

This test working great, BUT, once In a while, we get an error:

```
 TimeoutError: page.waitForSelector: Timeout 60000ms exceeded.
    =========================== logs ===========================
    [api] waiting for selector "[data-testid="search-result"]" to be visible
    ============================================================
       8 | 
       9 |   private async selectFirstSearchResult() {
    > 10 |     await this.page.waitForSelector('[data-testid="search-result"]');
         |                     ^
      11 |     await this.page.click('[data-testid="search-result-button"]');
      12 |   }
      13 | 
```

We have a video of that failed test:

- it succeeded to type the text
- the autocomplete result was shown for a second
- disappeared
- no search result was shown.

Anyone got an idea?

Environment:

- React SPA
- Node v10.20.1
- Docker - ubuntu:bionic

**Comment by pavelfeldman** [comment]
I think you found a bug in your app. Most likely, an asynchronous process that fetches the data for autocomplete and populates it is deleting / removing the autocomplete result.

**Comment by pavelfeldman** [comment]
Please feel free to reopen in case follow up questions!
