### ISSUE TITLE
[Feature] Environment variable to install browsers via proxy

### ISSUE THREAD

**Issue by 000dry** [microsoft/playwright#4220]
Hi there,

I'm wondering if there is any possibility of/what would be required for introducing a new environment variable where we can set an internet proxy specifically for downloading the browsers (i.e. a different configuration to our .npmrc), so that we can do something like `PLAYWRIGHT_DOWNLOAD_PROXY=http://some-proxy:9000 npm i playwright`.

The use case would basically be for us in corporate settings where we're locked into fetching npm packages via our company's CDN via VPN, but would like the option to go out to the internet at the point the browsers are installed.

Is this something the team would be interested in supporting?

**Comment by pavelfeldman** [comment]
We are using [proxy-from-env](https://www.npmjs.com/package/proxy-from-env) package to fetch browsers, you can do this today.

```sh
HTTPS_PROXY=http://some-proxy:9000 npm i playwright
```
