### ISSUE TITLE
[BUG] download file not occurs

### ISSUE THREAD

**Issue by yael118** [microsoft/playwright#4233]
**Context:**
- Playwright Version: [v1.5.1]
- Operating System: [Windows]
- Node.js version: [v12.18.4]
- Browser: [Chromium]

Hi, 
after updating to the new playwright version- downloading not really occurs.
using waitForEvent('download') is passing
but the file not really was downloaded

**Code Snippet**
```javascript

const os= require('os');
const fs =require('fs')
let userName = os.userInfo().username;
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
        const context = await browser.newContext();
        const page = await context.newPage();
        await page.goto('https://upbeat-nightingale-6e32da.netlify.app/download');
        await page.click('a');
   
        await page.waitForEvent('download');
        await fs.unlinkSync(`C:\\Users\\${userName}\\Downloads\\Archive.zip`)

})();
```

**Describe the bug**
result:
Error: ENOENT: no such file or directory, unlink 'C:\Users\david\Downloads\Archive.zip'

function waitForEvent('download')- succeeded
but it doesn't really happen

**Comment by pavelfeldman** [comment]
You snippet does not enable downloads and does not obtain the downloaded path, so it should not work. Please follow the [doc](https://playwright.dev/#version=v1.5.1&path=docs%2Fnetwork.md&q=handle-file-downloads/

**Comment by yael118** [comment]
Thanks for the quick response!!

I fixed the code and it does work.
But I wanted to ask - is there a way to get the file to download  to the folder I want on my PC

**Comment by arjunattam** [comment]
Hi @yael118, you can use `downloadsPath` to specify the download directory.

```
const browser = await chromium.launch({ downloadsPath: './temp-dir-for-downloads/' });
```

I'll close this issue. Feel to comment/create new issue if we are missing anything.

**Comment by yael118** [comment]
Thank you all
Keep up the good work
