### ISSUE TITLE
[Question] How to fight web app (Salesforce) pausing due to window/tab not in focus

### ISSUE THREAD

**Issue by sjurgis** [microsoft/playwright#4235]
The application that I'm testing (Salesforce's Lightning) has some sort of feature where it stops loading when it detects it is not in an active tab. Quite useful when users try to open multiple records in background - so it doesn't overwhelm their browsers. Historically it used to be quite slow and memory hungry, but I digress.

That's pretty bad when my tests are running in parallel - they are quite flaky as Salesforce decides not load parts that I'm testing...

I'm trying to understand what is the mechanism such apps typically use and how to reverse engineer them. They do not public source code and IIRC no source maps so it's a bit tricky.

I think this issue is described in [here](https://github.com/puppeteer/puppeteer/issues/3339) but not sure how Playwright solves this if at all. It certainly doesn't seem to have `createCDPSession` that Puppeteer has.

p.s. Google Flights does the same thing where it wouldn't load pricing in background tabs. You can observe the behaviour in [this Pupetteer scraper](https://github.com/sjurgis/puppeteer-flights). I've tried cycling window/tab focus in random to no avail.

**Comment by pavelfeldman** [comment]
CDP factory settings is on the context object: https://playwright.dev/#version=v1.5.1&path=docs%2Fnetwork.md&q=handle-file-downloads

**Comment by pavelfeldman** [comment]
Looking at it again, Playwright emulates active state for all tabs, so they should not be detected as being background. Could you give us a hint on how your app is checking the active state?

**Comment by sjurgis** [comment]
@pavelfeldman well it's not me who does that but Salesforce itself. That's the question I'm trying to understand too - how does Salesforce implement it, what are the typical techniques, etc.

All that said I don't think I've noticed this being issue anymore. Maybe it still does in when using multitple tabs, but right now we use multiple browser instances.

**Comment by dgozman** [comment]
Let me close this one for now, based on the last comment. However, we would be very interested in the repro script if this happens again.
