### ISSUE TITLE
[BUG] Webkit browser doesn't run on Ubuntu 20.10

### ISSUE THREAD

**Issue by angryziber** [microsoft/playwright#4236]
**Context:**
- Playwright Version: 1.5.1
- Operating System: Ubuntu 20.10
- Node.js version: 14
- Browser: WebKit

**Describe the bug**

WebKit binary fails to run due to missing **libicu66** package - Ubuntu 20.10 includes an upgraded **libicu67**.

```
[err] /home/anton/.cache/ms-playwright/webkit-1347/minibrowser-gtk/bin/MiniBrowser: error while loading shared libraries: libicui18n.so.66: cannot open shared object file: No such file or directory
<process did exit: exitCode=127, signal=null>
```

Why such strict version dependency?

Symlinking .so.67 files to .so.66 doesn't help unfortunately, the failure message becomes:
```
[err] /home/anton/.cache/ms-playwright/webkit-1347/minibrowser-gtk/bin/MiniBrowser: symbol lookup error: /home/anton/.cache/ms-playwright/webkit-1347/minibrowser-gtk/lib/libjavascriptcoregtk-4.0.so.18: undefined symbol: u_strToUpper_66
```

**Comment by arjunattam** [comment]
Thanks for the report @angryziber. We prepare builds for Ubuntu 20.04, but did not extend it to work with 20.10, which I believe was released last week. Tagging @aslushnikov so we can fix this.

In general, we prefer supporting LTS only, and I'm curious to know if that influences your decision to pick the OS version as well. Thanks!

**Comment by angryziber** [comment]
@arjunattam newer laptops don't always work with LTS versions :-)

For the Docker images/build systems, LTS only makes sense.
Anyway, not having too strict version dependencies will probably make it easy to just work on newer versions, without dedicated "support". Official binaries of e.g. Google Chrome work on Ubuntu 20.10 just fine without modifications.

**Comment by angryziber** [comment]
Workaround: install the package from Ubuntu 20.04:
http://archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu66_66.1-2ubuntu2_amd64.deb

**Comment by yury-s** [comment]
Closing this issues as we are not planning to support non-LTS Ubuntu versions at the moment. Your workaround should fix the problem, I also had to install `tzdata` which libicu66 seems to depend on.

**Comment by mirao** [comment]
I had the same issue in Ubuntu 21.04 (non-LTS) with Playwright 1.11.1/WebKit 1472. Moreover WebKit required `libenchant1c2a` that is not present in Ubuntu 21.04 repo anymore (it is in Ubuntu [20.04](https://packages.ubuntu.com/focal/libenchant1c2a)/20.10).
```
  Missing libraries are:
      libicui18n.so.66
      libicuuc.so.66
      libenchant.so.1
```
Installation of both DEB packages from Ubuntu 20.04 helped me.
