### ISSUE TITLE
[Feature] Add clear option to page.type method

### ISSUE THREAD

**Issue by viraxslot** [microsoft/playwright#4237]
Use case:
1. I use `page.type` method instead of `page.fill`, because that's more natural way to interact with the site (from my pov).
2. `page.type` appends text to the end of the input.
3. It would be nice to have an option `clear` that allows to clear input before typing.

Of course I can do
```javascript
await page.fill(selector, '');
await page.type(selector, 'some text');
```

Proposal code:
```javascript
await page.type(selector, 'some text', { clear: true });
```

**Comment by pavelfeldman** [comment]
`type` and `fill` are equally useful, it just depends on the use case. Typing generates intermediate keyboard events and some functionality is triggered by those. Typically auto-suggest, would be tested with typing. And `fill` is like pasting into the field - it is totally legit, is much faster and is useful where you just need to fill the form. Using `type` for forms is a waste of system resources.

`type` has clear semantics today, it presses keys in a loop. Making it clear would require it to programmatically select all and erase, similarly to how `fill` behaves. And it'll become much harder to explain what `type` is, it will stop being `natural` speaking in your terms.

**Comment by viraxslot** [comment]
@pavelfeldman thanks for the answer :)
