### ISSUE TITLE
[BUG] A png screenshot is produced when a jpeg/jpg screenshot is requested

### ISSUE THREAD

**Issue by rinogo** [microsoft/playwright#4238]
**Context:**
- Playwright Version: 1.4.2 and 1.5.1
- Operating System: macOS, Linux
- Node.js version: 14.1.0
- Browser: All
- Extra: (None)

**Code Snippet**

```const playwright = require('playwright');

(async () => {
  for (const browserType of ['chromium', 'firefox', 'webkit']) {
    const browser = await playwright[browserType].launch();
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto('http://whatsmyuseragent.org/');
    //await page.screenshot({ path: `example-${browserType}.png` }); //Generates .png screenshots
    await page.screenshot({ path: `example-${browserType}.png`, type: "jpeg" }); //Also generates .png screenshots
    await browser.close();
  }
})();
```

**Describe the bug**

Providing `type: "jpeg"` in `page.screenshot()`'s `options` parameter has no effect. I initially noticed this problem on 1.4.2. After upgrading to 1.5.1, I'm still seeing the same behavior. All generated screenshots are of type png.

[Documentation reference for `page.screenshot() options`](https://playwright.dev/#version=v1.5.1&path=docs%2Fapi.md&q=pagescreenshotoptions)

**Comment by arjunattam** [comment]
Thanks for the report, @rinogo. I can repro this. The file extension specified in `path` is taking precedence over the `type` option [1]. I understand how this can be confusing, and we should fix this – at the very least in docs.

Can you try using a `.jpg` in the path and verify that works for you?

[1] Relevant code snippet:

https://github.com/microsoft/playwright/blob/f5fbea94bb87dd2859222f35f931013fa03f97f8/src/client/elementHandle.ts#L285

**Comment by rinogo** [comment]
Thanks, @arjunattam! You're right - using the following line does generate .jpg files:

```
await page.screenshot({ path: `example-${browserType}.jpg`, type: "jpeg" });
```

I came across this issue because I'm specifying the path/filename separately from the other options (like `type`), so it was easy to end up with a "contradictory" configuration. (`.png` extension but `jpeg` `type`)

For what it's worth, there appears to be some quirky behavior with the filetype detection, as well. Removing the extension from the `path` but explicitly specifying the `type` as follows...
```
await page.screenshot({ path: `example-${browserType}`, type: "jpeg" });
```

...now generates the following error message (and zero screenshots):

```
(node:99333) UnhandledPromiseRejectionWarning: Error: page.screenshot: path: unsupported mime type "null"
    at Object.determineScreenshotType (/Users/user/Company/repos/project/scraper-playwright/node_modules/playwright/lib/client/elementHandle.js:245:15)
    at /Users/user/Company/repos/project/scraper-playwright/node_modules/playwright/lib/client/page.js:353:42
    at Page._wrapApiCall (/Users/user/Company/repos/project/scraper-playwright/node_modules/playwright/lib/client/channelOwner.js:80:34)
    at Page.screenshot (/Users/user/Company/repos/project/scraper-playwright/node_modules/playwright/lib/client/page.js:352:21)
    at /Users/user/Company/repos/project/scraper-playwright/screenshot-example.js:35:16
(Use `node --trace-warnings ...` to show where the warning was created)
(node:99333) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:99333) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Regardless, your first response resolves my immediate needs. Thank you! :)

**Comment by arjunattam** [comment]
Thanks for confirming. I believe there are 2 action items:

1. Clarify in docs that extension in `path` takes precedence over `type`.
2. Support case where `path` does not have an extension, but `type` is specified.

**Comment by rinogo** [comment]
Sounds spot on to me! 😁🙌 Thank you for your hard work on this amazing project!

**Comment by pavelfeldman** [comment]
This is in fact an RPC regression.

**Comment by dave-cheever** [comment]
Hi guys how can i change the path for the screenshots for my test
await this.page.screenshot({ path:'screenshot'+Date.now()+'.png' });

**Comment by rinogo** [comment]
Hi, @dave-cheever! You can use an absolute path (`/tmp/filename.png`) or a relative path (`../example/filename.png`).

In the future, instead of commenting on an irrelevant Issue, please create a new Issue or Discussion.

**Comment by dave-cheever** [comment]
Hi Rich!

Thanks for the reply, although I figured it out with trial and error.
Thank you so much for taking time to reply. And I'll create a separate
ticket if I encounter a problem.

Thanks!
