### ISSUE TITLE
[BUG] Helpful error message for lockfile

### ISSUE THREAD

**Issue by arjunattam** [microsoft/playwright#4242]
From a [user report on Slack](https://playwright.slack.com/archives/CSUHZPVLM/p1603522725233600):

```
error /Users/xxx/node_modules/playwright: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/xxx/node_modules/playwright
Output:
/Users/xxx/node_modules/proper-lockfile/lib/lockfile.js:68
                return callback(Object.assign(new Error('Lock file is already being held'), { code: 'ELOCKED', file }));
                                              ^
Error: Lock file is already being held
    at /Users/xxx/node_modules/proper-lockfile/lib/lockfile.js:68:47
    at callback (/Users/xxx/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqCallback.oncomplete (node:fs:184:5) {
```

Manually cleaning up the browsers directory and reinstalling fixed it. Not sure how the lockfile was initialized (hopefully not a yarn quirk), but we could show a more helpful error message suggesting towards a fix.

Update: This response might explain the cause

> Okay great. Not sure if it will help your debugging but I had a poor internet connection that time so the installation was taking too long to go through. I had to terminate the installation Ctrl + C in the middle and then ran yarn add … again.

**Comment by buggedcom** [comment]
If anyone else arrives here due to searching about lock file errors. I had the same problem, but came to realise that since I had included playwright and all the browser packages as dependencies that the lockfile was causing issues because the browser packages were simultaneously being built. 

To fix, just change

```
		"playwright": "^1.9.1",
		"playwright-chromium": "^1.9.1",
		"playwright-firefox": "^1.9.1",
		"playwright-webkit": "^1.9.1",
```
to
```
		"playwright": "^1.9.1",
```

in your `package.json`
