### ISSUE TITLE
[BUG] UnhandledPromiseRejectionWarning: Error: Unknown permission: *

### ISSUE THREAD

**Issue by aarock1234** [microsoft/playwright#4248]
**Context:**
- Playwright Version: ^1.5.1
- Operating System: Windows
- Node.js version: v12.16.2
- Browser: Webkit
- Extra: None

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
       const { webkit, devices } = require('playwright');
       const iPhone11 = devices['iPhone 11 Pro'];

        const browser = await webkit.launch();
        const context = await browser.newContext({
            ...iPhone11,
            locale: 'en-US',
            permissions: ['*']
        });
```

**Describe the bug**

When I run the code it says `UnhandledPromiseRejectionWarning: Error: Unknown permission: *`. 

Under the [docs](https://playwright.dev/#version=master&path=docs%2Fapi.md&q=browsercontextgrantpermissionspermissions-options--permissions-) it says you can write `*` as permission to (I'm assuming) grant all permissions at once. This is the expected behavior, but in practice, I get the error shown above.

**Comment by pavelfeldman** [comment]
That's a bug in the docs - we only support a wildcard `*` for specifying origin, not the permission.

**Comment by arjunattam** [comment]
Thanks for reporting this @aarock1234, and apologies for the confusion this caused. I've created #4260 to fix the docs.
