### ISSUE TITLE
[Question] Will node js be updated to 14 lts in docker image?

### ISSUE THREAD

**Issue by niyarlatotep** [microsoft/playwright#4254]
Since node js 14 lts is active now can we have 14 version in docker image? I use some features of 14 node and would like to use official image of docker playwright in CI with 14 version of node js. Can you consider updating it?

**Comment by mxschmitt** [comment]
Yup good catch (as discussed [here](https://github.com/microsoft/playwright/pull/3642#issuecomment-686640755)) it should be changed. On the other GitHub Action workflows we are using Node.js 10 which is our minimal version, so I guess only bumping the version in the Dockerfiles should be enough.

**Comment by arjunattam** [comment]
Quick status update on this: On looking at [Node.js release calendar](https://nodejs.org/en/about/releases/), we plan to replace Node.js 12 with 14 in our base image when active LTS for 12 ends: November 30, 2020. This will align with the timeline for v1.7. For now, I would recommend installing Node.js 14 in a user-land Dockerfile.

```
FROM mcr.microsoft.com/playwright:v1.5.2

RUN apt-get update && apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y nodejs
```

**Comment by niyarlatotep** [comment]
@arjgupta Thank you for the info!
