### ISSUE TITLE
[Question] Video Stream

### ISSUE THREAD

**Issue by nor0x** [microsoft/playwright#4263]
I'm pretty sure it's not the intended behavior of the newly added video features and `IVideo`, but would it be possible to retrieve a live video stream from a headless browser context, similar to continuous calls to `page.ScreenshotAsync`. 

As far as I understood the new video feature, it's for recording and saving it afterwards?

**Comment by nor0x** [comment]
thanks for the reply @arjunattam - currently Chromium-only would be very fine. Do you have a hint at what code to look at?

**Comment by atemiz** [comment]
I think eliminating the delays (currently min 100ms) between ScreencastFrame events might be useful.

**Comment by nor0x** [comment]
@atemiz good idea, i didn't know that there are 100ms between ScreencastFrame events. Just to make sure i get this right - these 100ms are in Chromium or playwright?

**Comment by atemiz** [comment]
@nor0x Chromium;
https://chromium.googlesource.com/chromium/src/+/refs/heads/master/content/browser/devtools/devtools_video_consumer.cc

**Comment by pavelfeldman** [comment]
Note that non-Chromium do not have this limitation and stream into vp8.

**Comment by pavelfeldman** [comment]
@atemiz: thanks for the pointer, I removed the limitation upstream: https://chromium-review.googlesource.com/c/chromium/src/+/2546475, I believe that was a regression. We are still dropping frames based on the backpressure, but it should not be as bad as it used to be.

**Comment by nor0x** [comment]
thanks for the update @pavelfeldman i will see how i can use this

**Comment by nor0x** [comment]
Hey @pavelfeldman, another (maybe stupid) question. Chromium uses Skia for rendering, right? 
If i wanted to get a snapshot or preview of the current browser content, do i always have to go through snapshotting - even if i use Skia for rendering the content on my side (currently as images)

**Comment by dgozman** [comment]
@nor0x In theory it is possible to expose some other format representing the content being drawn (DisplayList? Maybe even Skia commands list?), but that's not the usecase Playwright focuses on.

**Comment by nor0x** [comment]
@dgozman alright got it! thanks

**Comment by pavelfeldman** [comment]
Thank you for reporting this issue and providing comments to those that might be facing a similar problem. I am now closing this as a part of the triage, please feel free to file a new issue with additional details. Given the limited resource and a lot of requests, we need to fulfill most popular requests and at the same time keep our issue database manageable.

**Comment by jfloodnet** [comment]
> (currently as images)

I have a similar usecase, did you get something working?

**Comment by jfloodnet** [comment]
@nor0x I have a similar use case, did you get something working?

**Comment by frmsaul** [comment]
I'm curious also. Any progress on this?

**Comment by SuperPauly** [comment]
Me too, any updates?

**Comment by RicoChr** [comment]
I also have a use case for this. I would love to use such a feature to enable the user of an automation framework to witness a demanded automatic process being executed.

**Comment by johntharian** [comment]
Is this feature in ?
