### ISSUE TITLE
[Feature] Multiple text selectors

### ISSUE THREAD

**Issue by rinogo** [microsoft/playwright#4265]
Sometimes, it's useful to select on a group of selectors. In other words, to provide multiple selectors that are used in a "logical or" search. With CSS, this is easy:

```
await page.waitForSelector("css=.class1, .class2");
```

I was trying to find an equivalent way to do this with the text selector. I tried (and possibly propose?) the following, but it doesn't seem to work:

```
await page.waitForSelector("text='String 1', text='String 2'");
```

The best I could come up with was to use regex alternation:

```
await page.waitForSelector("text=/^(String 1|String 2)$/");
```

Is there a non-regex way to accomplish this with the text selector?

If there isn't, then I suppose one could be implemented using the regex alternation approach as a sort of "syntactic sugar". However, I also recognize that the proposed "multiple text selectors" format above might not jive with the "microformat" used to parse Playwright selectors.

**Comment by pavelfeldman** [comment]
Would this work for you?
```js
await Promise.race(['text=String 1', 'text=String 2'].map(selector => page.waitForSelector(selector));
```

**Comment by rinogo** [comment]
Thanks, @pavelfeldman! I think that would have the desired effect. I like your use of `map()`. If I turn this into a helper function, the `map()` function is a perfect fit for working with an arbitrary number of selectors.

If I go with the `Promise.race()` approach, I may consider going with something a little less sexy in the interest of simplicity and readability:
```
await Promise.race([
	page.waitForSelector('text=String 1'),
	page.waitForSelector('text=String 2')
]);
```

Regardless, thanks again for your help on this Issue and the enormous amount of work you and the others put into this tool overall. I'm seeing a huge amount of potential in both the short and long term!

**Comment by rinogo** [comment]
For Google/indexers: this approach could also be useful for mixing/combining selectors of different types: CSS, Text, XPath, and any future selector types introduced by the Playwright project.
