### ISSUE TITLE
[Question] Exported video quality

### ISSUE THREAD

**Issue by rudasn** [microsoft/playwright#4266]
Hi all. Is it possible to define or control the quality of the video that gets generated after running a session?

Thanks!

**Comment by arjunattam** [comment]
Hi @rudasn, not at this point. Can you share what you'd like to change?

**Comment by yury-s** [comment]
@rudasn current API allows to set video dimensions and the picture of the page (its view port to be more accurate) will be scaled down if necessary to fit that size. This should give you pretty good control over the video resolution and as a result the output file size. We thought that separate knob for video quality was not justified. Can you elaborate on why you need to change the quality?

**Comment by rudasn** [comment]
@arjunattam @yury-s thanks for replying.

I just played around with the video size and viewport dimensions and the resulting video looks pretty good to me.

Could you point me to the right direction on where/how the video gets recorded? 

Thanks. You can close this issue.

**Comment by arjunattam** [comment]
For Chromium, this is relevant: https://github.com/microsoft/playwright/blob/master/src/server/chromium/videoRecorder.ts

Firefox and WebKit have browser-side changes.

**Comment by rudasn** [comment]
Great, thanks!
