### ISSUE TITLE
[Question] Does puppeteer have Redhat Dockerfile support?

### ISSUE THREAD

**Issue by millisande** [microsoft/playwright#4268]
How do I deploy a server running on a Redhat container which installs puppeteer? 

If I try either firefox or chrome as the browser type I get this error: `[Error: EACCES: permission denied, mkdir '/usr/src/build/node_modules/puppeteer/.local-firefox']` or `[Error: EACCES: permission denied, mkdir '/usr/src/build/node_modules/puppeteer/.local-chromium']`

I therefore have changed my docker file to run the installation at build time with `--unsafe-perm=true`.

This is my docker file when trying to deploy with firefox

```
# Build within docker container
ARG ubi
FROM registry.access.redhat.com/ubi8/nodejs-12 as build
WORKDIR /usr/src/build
USER root

# Install app dependencies
COPY package.json .
ENV PUPPETEER_PRODUCT='firefox'
RUN npm install --production
RUN npm install puppeteer --unsafe-perm=true --save-dev

# Copy full repository
COPY .env .env
COPY . .  

# Setup a minimal ubi
FROM $ubi

# Copy app contents for install
WORKDIR /usr/src/app
COPY --from=build /usr/src/build .
USER root
ENV PUPPETEER_PRODUCT='firefox'
RUN npm i --production
RUN npm install puppeteer --unsafe-perm=true --save-dev

# Server runs on port 4016
EXPOSE 4016

# Start the app  
CMD ["npm", "run", "prod"]
```

This is my docker file when trying to run with chromium:

```
# Build within docker container
ARG ubi
FROM registry.access.redhat.com/ubi8/nodejs-12 as build
WORKDIR /usr/src/build
USER root

# Install app dependencies
COPY package.json .
RUN npm install --production
RUN npm install puppeteer --unsafe-perm=true --save-dev

# Copy full repository
COPY .env .env
COPY . .  

# Setup a minimal ubi
FROM $ubi

# Copy app contents for install
WORKDIR /usr/src/app
COPY --from=build /usr/src/build .
USER root
RUN npm i --production
RUN npm install puppeteer --unsafe-perm=true --save-dev

# Server runs on port 4016
EXPOSE 4016

# Start the app  
CMD ["npm", "run", "prod"]
```

When running with firefox I get this error:
`Failed to launch the browser process!\nXPCOMGlueLoad error for file /usr/src/app/node_modules/puppeteer/.local-firefox/linux-84.0a1/firefox/libmozgtk.so:\nlibgtk-3.so.0: cannot open shared object file: No such file or directory\nCouldn't load XPCOM.\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n"`

When running chromium I get this error:
`Error: Failed to launch the browser process!
/usr/src/app/node_modules/puppeteer/.local-chromium/linux-800071/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory`

I have tried to add the libnss3 library using this command 
```
RUN apt-get install -y wget unzip fontconfig locales gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
```
But that seems to be for alpine rather than redhat. I get an error saying cannot find command apt-get. If I shift to apk still doesn't recognise the command. I have tried yum and I have tried rpm instead and rpm doesn't seem to have an equivalent library for libnss3. 

If someone can tell me what the equivalent is for redhat or any other advice about the best way to deploy this server which uses puppeteer I would really appreciate it.

**Comment by mxschmitt** [comment]
Hi, this is the Playwright repository which has not much to do with Puppeteer, also in your code it seems like you are using Puppeteer and not Playwright, or do I miss something?

**Comment by millisande** [comment]
oh silly me, thank you!
