### ISSUE TITLE
[BUG] Firefox workers cause frame navigation

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#4277]
Firefox is reporting main frame navigation to Blob and internal URLs when web workers load

`DEBUG=pw:api npm run ftest -- workers.spec.ts --reporter=list`

Observe `navigated to` values around "should clear upon navigation" tests.

**Comment by pavelfeldman** [comment]
Found out while investigating flaky test

```
workers.spec.ts:84:1 › should clear upon navigation
```

**Comment by aslushnikov** [comment]
fixed!
