### ISSUE TITLE
How to Compare two screenshots? Need code [Question]

### ISSUE THREAD

**Issue by ProgrammingWithPradeep** [microsoft/playwright#4279]
I have a Grid table that has 30 columns and each column can be sorted , i want to check Playwright if it can capture the baseline image and then Apply Sort on any column and capture the screenshot this time with sorted values and make base line 2 .
Now next time when i run the test , i want to compare the screens from the test with baseline and baseline 2 images. 
Any thoughts? 

Thanks !

**Comment by arjunattam** [comment]
Hi, Playwright can capture screenshots for pages/elements. You can use an image comparison library to then compare these screenshots. The choice of library depends on your test runner:

* If you're using Jest, jest-image-snapshot is a popular choice
* For the Playwright test runner (available in preview), you can use the [built-in comparison API](https://github.com/microsoft/playwright-test#visual-comparisons)

**Comment by ProgrammingWithPradeep** [comment]
Thank you for the response ! 
As of now there is no test runner and we are open . But second option seems more apt for the scenario i explained above. 
Is Jest some third party library ? Any Sample Code for Jest to try out?

Thanks!
