### ISSUE TITLE
[BUG] Firefox starts in safe mode 

### ISSUE THREAD

**Issue by shirshak55** [microsoft/playwright#4281]
Hmm When we run test sometime  and close browser and open browser again firefox suddenly gives prompt whether to start in safe mode or not? How do I disable that? 

I am using heedful mode for that. And the code is just simple load website and close browser and again respawn browser.

And Yes its compulsory for me to restart browser due to proxy thing.

**Comment by pavelfeldman** [comment]
We probably don't close the browser gracefully and the non-graceful bit is stuck in the profile that you reuse. Btw, I'm working on https://github.com/microsoft/playwright/pull/4280.

**Comment by pavelfeldman** [comment]
Could you share more on why you need multiple proxies?

**Comment by shirshak55** [comment]
@pavelfeldman our website have some ip rate limit on registration page so what we do is use multiple proxies to test registration page.

We do this in staging build just to ensure everything is working when some real human uses the website. I wished proxies were applied in context rather than whole browser instance.

**Comment by yury-s** [comment]
@shirshak55 can you confirm if #4280 fixes your issues?

**Comment by shirshak55** [comment]
yea should be
