### ISSUE TITLE
[Question] is there a way to get element background colour ?

### ISSUE THREAD

**Issue by tanneerumahesh** [microsoft/playwright#4282]
Hi guys,  is there a way to get element background colour using playwright?

Tahnks

**Comment by viraxslot** [comment]
Hey @tanneerumahesh!
Try this code:
```javascript
const element = await page.waitForSelector(selector);
const color = await element.evaluate((el) => {
       return window.getComputedStyle(el).getPropertyValue('background-color');
});
console.log(color);
```

Be aware of [this](https://playwright.dev/#version=v1.5.2&path=docs%2Fcore-concepts.md&q=execution-contexts-nodejs-and-browser)
Maybe there is better solve, it's my approach to do it :)

**Comment by mxschmitt** [comment]
Feature request in https://github.com/microsoft/playwright/issues/11494

**Comment by isa3bel** [comment]
For some reason, doing @viraxslot solution gives me a color that is an empty object. Does his solution work for anyone else?

**Comment by viraxslot** [comment]
@isa3bel Hi, I've just made a fresh example with the `locator` approach:
```typescript
import {test, expect} from "@playwright/test"

test("basic test", async ({page}) => {
    await page.goto("https://playwright.dev/docs/intro")
    const docsLink = page.locator("a >> text=Docs")
    const color = await docsLink.evaluate((e) => {
        return window.getComputedStyle(e).getPropertyValue("color")
    })
    expect(color).toBe("rgb(69, 186, 75)")
})

```

I believe it should check the color of this link:
![image](https://user-images.githubusercontent.com/20737672/170584558-3ab2255f-4112-4d77-8f87-e1397ea58dbb.png)

Please pay attention that you have a typo in `evalutate` function. It should be `evaluate`. And please don't forget `await` :)
Hope it'll help you.

**Comment by isa3bel** [comment]
I was wondering, why is the await keyword needed in this case? @viraxslot

**Comment by viraxslot** [comment]
@isa3bel Well, due to playwright docs `evaluate` function returns Promise, so you need to add `await` for sure: https://playwright.dev/docs/api/class-locator#locator-evaluate 

And about `getPropertyValue` function itself, our statement will work for both cases (async or not). But as I can see this function is synchronous: https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/getPropertyValue
So, I guess `evaluate` won't wait and will return the value right away, because you can await synchronous functions with no problem (but it's redundant of course).

So it's hard to say what's wrong in your case. Could you please provide a reproducible example?

**Comment by shilpa32** [comment]
Hi guys, how to get element background color using playwright java?

**Comment by dourbi** [comment]
@shilpa32 did u find any method  for background color in java??

**Comment by shilpa32** [comment]
locator(locator).evaluate("element => getComputedStyle(element)['background-color']");

**Comment by samaquartey** [comment]
this works for me in C# and should also work for Java,
you could put it in re-usable method.

await Expect(locator).ToHaveCSSAsync("background-color", "rgb color here");

**Comment by jwerre** [comment]
Has anyone run into this issue:

```ts
const property = 'background-color';
const styles = await locator.evaluate((el) => {
  return window.getComputedStyle(el).getPropertyValue(property);
});

// ERROR: locator.evaluate: ReferenceError: property is not defined
```

Why is it not able to read `property`? Since `evaluate` is running in a different virtual machine is this even possible?

**Comment by dustyshaw** [comment]
Does anyone know how to do something similar in C#? In my case, if an element has the css display property set to block, my Playwright test needs to click an extra button.  If it isn't set to block, my test should continue.

**Comment by phungleson** [comment]
@jwerre evaluation happens in browser, so you have to manually pass the value to it, something like this

`locator.evaluate((el, property) => window.getComputedStyle(el).getPropertyValue(property), property); `

**Comment by samaquartey** [comment]
you just have to pass the element locator and the expected color.


    // Check element background-color
    public async Task CheckElementBackgroundColor(ILocator locator, string color)
    {
        await Expect(locator).ToHaveCSSAsync("background-color", color);
    }

    // Check element color
    public async Task CheckElementColor(ILocator locator, string color)
    {
        await Expect(locator).ToHaveCSSAsync("color", color);
    }

**Comment by yabols** [comment]
> you just have to pass the element locator and the expected color. just copy the methods, ready to use
> 
> ```
> // Check element background-color
> public async Task CheckElementBackgroundColor(ILocator locator, string color)
> {
>     await Expect(locator).ToHaveCSSAsync("background-color", color);
> }
> 
> // Check element color
> public async Task CheckElementColor(ILocator locator, string color)
> {
>     await Expect(locator).ToHaveCSSAsync("color", color);
> }
> ```

So the evaluate method won't work? I don't want to assert it straight away.  I need value as this is some nested object.

**Comment by InTouch1988** [comment]
> Has anyone run into this issue:
> 
> ```ts
> export const getStyle = async ( locator: Locator, property: string): Promise<string> => {
>   return locator.evaluate((el) => window.getComputedStyle(el).getPropertyValue(property) );
> };
> getStyle(page.getByRole('button'), 'background-color');
> 
> // ERROR: locator.evaluate: ReferenceError: property is not defined
> ```
> 
> Why is it not able to read `property`? Since `evaluate` is running in a different virtual machine is this even possible?

Did you find any solution? I faced with the same issue. The solution, provided by [phungleson](https://github.com/phungleson) doesn't work, still see the error

**Comment by jwerre** [comment]
@InTouch1988, @phungleson solution does work. Here's what I have (Typescript)

```ts
/**
 * Retrieve a computed style for an element.
 *
 * @function getStyle
 * @async
 * @param locator {Locator} The Playwright locator to evaluate (see: https://playwright.dev/docs/locators)
 * @param property {string} The CSS property for the style to retrieve
 * @returns Promise<string> The style value
 */
export const getStyle = async (locator: Locator, property: string): Promise<string> => {
   return locator.evaluate( (el, property) => window.getComputedStyle(el)
     .getPropertyValue(property), property );
};


test('get button background color', async ({ page }) => {
  cost btnBgColor = await getStyle(page.getByRole('button'), 'background-color');
  expect(btnBgColor).toBe('rgb(255, 0, 0)')
});

```

**Comment by GStasiakVolue** [comment]
Working solution in C#:
```
private ILocator _btn => _page.Locator("button");
var backgroundColor = await _btn.EvaluateAsync<string>(@"element => window.getComputedStyle(element).getPropertyValue('background-color')");
```

**Comment by samaquartey** [comment]
Great thanks @GStasiakVolue 
I just made it resuable: works perfectly 

public string GetElementBackgroundColor(ILocator locator)
    {
        var backgroundColor = locator.EvaluateAsync<string>(@"element => window.getComputedStyle(element).getPropertyValue('background-color')").Result;
        return backgroundColor.ToString();
    }

**Comment by lihka1202** [comment]
I'm not too sure but as of 29th January 2024 you can make use of the `toHaveCSS` assertion to verify the colour. In my case I wanted to find the background colour of the page (should work for any element), and I did something along the following lines:

```js
await expect(this.page.locator('body')).toHaveCSS('background-color', 'rgb(250, 250, 250)')
```

**Comment by matusdrobuliak66** [comment]
In Playwright for Python:
```
 _button_style = run_button.evaluate("el => window.getComputedStyle(el)")
 _button_style['backgroundColor'] == "'rgb(105, 105, 255)'"
```

**Comment by dongthg7** [comment]
You can try this:
`const color = await element.evaluate((e) => {
      return e.style.color;
  });`
It works for me !

**Comment by LinhDo-LGG** [comment]
> You can try this: `const color = await element.evaluate((e) => { return e.style.color; });` It works for me !

Thank you! you save my day!

**Comment by Groaning2** [comment]
@samaquartey https://javascripter.space/questions/guide-to-obtaining-border-width-with-computedstyle-in-javascript
