### ISSUE TITLE
[Question] Docker browsers are downloading during npm ci command

### ISSUE THREAD

**Issue by viraxslot** [microsoft/playwright#4283]
Hi, team! I use 2 docker images because I want to install playwright and download browsers once in `base` image and then only run test cases.

Base image:
```
FROM mcr.microsoft.com/playwright:v1.5.2
USER root
RUN mkdir -p /home/tests
WORKDIR /home/tests

COPY package.json . 
COPY package-lock.json .
COPY policies/policies.json /etc/firefox/policies

RUN mkdir -p /etc/chromium/policies/managed
COPY policies/chromiumPolicy.json /etc/chromium/policies/managed

RUN npm i
```

Image for running tests:
```
FROM artifactory/playwright-base:latest
USER root
WORKDIR /home/tests

COPY . .

RUN npm ci && chmod 777 entrypoint.sh
CMD ["/bin/bash", "./entrypoint.sh"]
```

When I run my tests using 2nd image I see in logs
```
12:47:55 > playwright@1.5.2 install /home/tests/node_modules/playwright
12:47:55 > node install.js
12:47:55 
12:47:55 Removing unused browser at /root/.cache/ms-playwright/chromium-799411
12:47:56 Removing unused browser at /root/.cache/ms-playwright/firefox-1171
12:47:56 Removing unused browser at /root/.cache/ms-playwright/webkit-1343
12:47:57 
12:47:57 chromium v815036 downloaded to /root/.cache/ms-playwright/chromium-815036
12:48:06 
12:48:06 firefox v1188 downloaded to /root/.cache/ms-playwright/firefox-1188
12:48:10 
12:48:10 webkit v1347 downloaded to /root/.cache/ms-playwright/webkit-1347
```

As I can understand browsers are downloading on this stage. What am I doing wrong?
Thanks in advance.

**Comment by mxschmitt** [comment]
The Docker image tag and the Playwright version in the package.json need to match otherwise the browsers get re-downloaded. From what I've seen in your details this looks fine.

I tried to compare the browsers in the Docker image (`mcr.microsoft.com/playwright:v1.5.2`) with the browser revisions in the NPM version (https://unpkg.com/playwright@1.5.2/browsers.json). They match, so I guess that on your environment it might be a Docker layer caching issue since your base image has the Chromium revision 799411 which is not v1.5.2.

**Comment by viraxslot** [comment]
@mxschmitt thanks for the quick response!
I've added `--no-cache` option to both images build command and reverted version to `1.5.1` for checking and for being sure the new image will be pushed.

Same situation:
```
13:36:52 > playwright@1.5.1 install /home/tests/node_modules/playwright
13:36:52 > node install.js
13:36:52 
13:36:52 Removing unused browser at /root/.cache/ms-playwright/chromium-799411
13:36:52 Removing unused browser at /root/.cache/ms-playwright/firefox-1171
13:36:52 Removing unused browser at /root/.cache/ms-playwright/webkit-1343
13:36:54 
13:36:54 chromium v815036 downloaded to /root/.cache/ms-playwright/chromium-815036
13:37:03 
13:37:03 firefox v1188 downloaded to /root/.cache/ms-playwright/firefox-1188
13:37:07 
13:37:07 webkit v1347 downloaded to /root/.cache/ms-playwright/webkit-1347
```

Could it be because of this error during `base` image building?
```
> playwright@1.5.1 install /home/tests/node_modules/playwright
> node install.js

Failed to process descriptor at /tmp/pw/node_modules/playwright
```

**Comment by viraxslot** [comment]
@mxschmitt hmm, it's interesting. I remembered it worked in on of previous versions, so I've found this version:

Base image for 1.3.0
```
> playwright@1.3.0 install /home/tests/node_modules/playwright
> node install.js

chromium v792639 downloaded to /root/.cache/ms-playwright/chromium-792639

firefox v1144 downloaded to /root/.cache/ms-playwright/firefox-1144

webkit v1322 downloaded to /root/.cache/ms-playwright/webkit-1322
```

Base image for 1.4.0 and later versions:
```
> playwright@1.4.0 install /home/tests/node_modules/playwright
> node install.js

Failed to process descriptor at /tmp/pw/node_modules/playwright
```

Now we now there to search :)

**Comment by pavelfeldman** [comment]
Looks like the `pw` user change? @aslushnikov

**Comment by mxschmitt** [comment]
> Looks like the `pw` user change? @aslushnikov

Tested with root + pwuser and the following Dockerfile. Seems fine

```
FROM mcr.microsoft.com/playwright:v1.5.2

ADD ./package.json /
ADD ./package-lock.json /

RUN npm ci
```

**Comment by viraxslot** [comment]
@mxschmitt it's strange, because I made a new repo with only playwright in dependencies and problem reproduces with root or default user.

https://github.com/viraxslot/test-pw-docker

**Comment by arjunattam** [comment]
Thanks for repo! Unfortunately, I wasn't able to repro the issue while buidling (logs below). Would it be worth clearing up the Docker objects cache? Are you seeing this on both macOS and Linux?

```
docker images --no-trunc --format '{{.ID}}' | xargs docker rmi
```
<details>
<summary>Logs</summary>

```
$ docker build .
Sending build context to Docker daemon  75.78kB
Step 1/4 : FROM mcr.microsoft.com/playwright:v1.5.2
 ---> 6fde119daa71
Step 2/4 : ADD ./package.json /
 ---> c3d6c15f7674
Step 3/4 : ADD ./package-lock.json /
 ---> a5dc7d5bc04e
Step 4/4 : RUN npm ci
 ---> Running in 581a83e0a5b3

> playwright@1.5.2 install /node_modules/playwright
> node install.js

Failed to process descriptor at /tmp/pw/node_modules/playwright
added 37 packages in 1.799s
Removing intermediate container 581a83e0a5b3
 ---> 7941264e12b2
Successfully built 7941264e12b2
```
</details>

**Comment by viraxslot** [comment]
Hi @arjunattam, you've reproduced it :) The problem was in `Failed to process descriptor at /tmp/pw/node_modules/playwright` message, instead of it browsers should be downloaded. If you change version of playwright to 1.3.0 you'll see this (correct) behavior.

**Comment by mxschmitt** [comment]
Yeah the error seems confusing but the actual feature (don't download the browsers again if the Docker image version and the NPM version match) seem to work. (root and pwuser).

**Comment by viraxslot** [comment]
@yury-s hi, can I check the fix in playwright@next?

**Comment by mxschmitt** [comment]
> @yury-s hi, can I check the fix in playwright@next?

Yes. But to confirm, what was the actual issue? Only the warning being printed? Since Arjun was not able to reproduce it.

**Comment by viraxslot** [comment]
@mxschmitt well, browsers were not downloaded when I built my base docker image and were downloaded before the test run. The purpose of the base image was to minimize time before tests start.

Anyway, I updated pw like:
"playwright": "^1.8.0-next.1608603118992"
FROM mcr.microsoft.com/playwright:next-focal

**As I can see there is no browser downloading at all**
Base image build:
```
> playwright@1.8.0-next.1608603118992 install /home/tests/node_modules/playwright
> node install.js

> husky@4.3.6 postinstall /home/tests/node_modules/husky
> opencollective-postinstall || exit 0
```

Main image build:
```
> playwright@1.8.0-next.1608603118992 install /home/tests/node_modules/playwright
> node install.js

> odiff-bin@1.0.4 postinstall /home/tests/node_modules/odiff-bin
> node ./postinstall.js
```
**but e2e tests in browser works just fine.** 

If use v1.7.0 then base image
```
> playwright@1.7.0 install /home/tests/node_modules/playwright
> node install.js

Failed to process descriptor at /tmp/pw/node_modules/playwright
```

main image build:
```
> playwright@1.7.0 install /home/tests/node_modules/playwright
> node install.js
Removing unused browser at /root/.cache/ms-playwright/chromium-792639
Removing unused browser at /root/.cache/ms-playwright/firefox-1144
Removing unused browser at /root/.cache/ms-playwright/webkit-1322

chromium v833159 downloaded to /root/.cache/ms-playwright/chromium-833159
firefox v1221 downloaded to /root/.cache/ms-playwright/firefox-1221
webkit v1402 downloaded to /root/.cache/ms-playwright/webkit-1402
```

**Fixed I guess :) Thanks a lot @yury-s!**

**Comment by mxschmitt** [comment]
@viraxslot Thanks for confirming!
