### ISSUE TITLE
[BUG] page.addInitScript doesn't work for large scripts

### ISSUE THREAD

**Issue by fawazahmed0** [microsoft/playwright#4284]
**Context:**
- Playwright Version: 1.5.2
- Operating System: Windows 7
- Node.js version: 12.18.0
- Browser: Firefox

**Code Snippet 1(JQuery- Script Large Size - Doesn't work):**

```javascript
const fs = require('fs')


const { firefox } = require('playwright');

(async () => {
  const browser = await firefox.launch();
  const context = await browser.newContext();
  const page = await context.newPage();


var preloadFile = fs.readFileSync('./jquery-3.5.1.js', 'utf8');
await page.addInitScript(preloadFile);
await page.goto("https://www.example.com/")

value =  await page.evaluate(() => window.jQuery ? 'yes jQuery' : 'no jQuery');
console.log(value)
  await browser.close();
})().catch(console.error);

```

**Expected Output:**
`yes jQuery`

**Actual Output:**
`no jQuery`

**Code Snippet 2(Lodash- Small Size - Works Great):**

```javascript
const fs = require('fs')


const { firefox } = require('playwright');

(async () => {
  const browser = await firefox.launch();
  const context = await browser.newContext();
  const page = await context.newPage();

var preloadFile = fs.readFileSync('./core.min.js', 'utf8');
await page.addInitScript(preloadFile);
await page.goto("https://www.example.com/")

value =  await page.evaluate(() =>  _.defaults({ 'a': 1 }, { 'a': 3, 'b': 2 }));
console.log(value)
  await browser.close();
})().catch(console.error);

```

**Expected Output:**
`{ a: 1, b: 2 }`

**Actual Output:**
`{ a: 1, b: 2 }`

**Describe the bug**

[page.addInitScript](https://playwright.dev/#version=v1.5.2&path=docs%2Fapi.md&q=pageaddinitscriptscript-arg) doesn't seem to work, when the script size is large.
I have attached the relevant scripts used.

[Scripts Used.zip](https://github.com/microsoft/playwright/files/5459799/Scripts.Used.zip)

Thanks

**Comment by pavelfeldman** [comment]
I tried this in Chromium and in WebKit and both showed be an error:

![jquery](https://user-images.githubusercontent.com/883973/97605394-cd65fa00-19cb-11eb-8998-e1269bca6e2d.png)

`addInitScript` runs before anything else in the page and you can't create elements yet. jQuery is using document elements for feature detection and it fails.

**Comment by fawazahmed0** [comment]
Thanks, so the problem is in how the jQuery works.
Maybe you might want to consider running the `addInitScript` at later stages, so scripts similar to jquery could work.

I am ok with `page.addScriptTag` for now

Thanks
