### ISSUE TITLE
Running WebKit on AWS EC2 Instance [Question]

### ISSUE THREAD

**Issue by evading-bot-detection** [microsoft/playwright#4285]
Which AWS EC2 instance types support the WebKit browser? I am able to get the Chrome and Firefox browsers working fine but not WebKit. I've attached a couple screenshots of the instance types and errors I get.

<img width="630" alt="Screen Shot 2020-10-29 at 11 34 56 AM" src="https://user-images.githubusercontent.com/68316580/97617256-c692b380-19da-11eb-8b61-8eac965c1b93.png">
<img width="628" alt="Screen Shot 2020-10-29 at 11 35 11 AM" src="https://user-images.githubusercontent.com/68316580/97617291-cf838500-19da-11eb-872f-629305fa15ce.png">

**Comment by arjunattam** [comment]
Hi, it seems Ubuntu 20.04 is running WebKit but there's an error in your script. Can you share the script here?

**Comment by evading-bot-detection** [comment]
You are correct, this script is giving me an error regardless of the browser. It is essentially the same test script that I downloaded with the package a few months ago.
[playwright-test.js.zip](https://github.com/microsoft/playwright/files/5460744/playwright-test.js.zip)

**Comment by evading-bot-detection** [comment]
The same script which works on my laptop is not working on the EC2 instance, what needs to be changed for it to work?

**Comment by arjunattam** [comment]
Thanks for checking. I wasn't able to repro this on my end either. Can you share versions of Playwright and Node.js that you're using? It might also be worth trying with Playwright 1.5.2 since it includes a relevant fix (#4258).

**Comment by evading-bot-detection** [comment]
I just installed it fresh a few hours ago with "npm install playwright" so it should be up to date.

Again this script works just fine on my Mac but not on EC2.

**Comment by arjunattam** [comment]
Thanks. Can you share the version of Node.js running on the EC2?

**Comment by evading-bot-detection** [comment]
13.1.0

**Comment by arjunattam** [comment]
13.1.0 has known issues, and I can't go beyond the "do not define a valid . target", which [affects a lot of packages](https://stackoverflow.com/questions/61621828/getting-strange-error-using-uuid-npm-module-what-am-i-doing-wrong). I would recommend using one of the LTS versions: v12.19 or v14.15

**Comment by evading-bot-detection** [comment]
Got it. I'll try it out, thanks.

**Comment by arjunattam** [comment]
I'll close this for now. Both Ubuntu 18.04 and 20.04 are well supported for WebKit and our Docker images are based on them. Other (glibc based – not alpine) distros will also work as long as the system dependencies are available. Launching WebKit on them prints dependencies that are missing.
