### ISSUE TITLE
[Question] Have the browsers that are downloaded for playwright 1.3.0 changed somehow ?

### ISSUE THREAD

**Issue by sublimator** [microsoft/playwright#4319]
I was assuming that the associated browsers for a pinned version would also be pinned. 
But perhaps not?

We had some spurious CI failures which I tracked down to document.visibilityState not being updated properly when a tab is backgrounded. Possibly a regression ?

**Comment by mxschmitt** [comment]
The associated browsers for a Playwright version are pinned and won't change once they are released on NPM. If you are pinning your NPM packages either with a specific version or with `npm ci` then it should result in the same browsers always.

**Comment by sublimator** [comment]
Thanks for the answer, that makes sense
