### ISSUE TITLE
[DevOps] GitHub Dependency graph does not work

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#4320]
Since we generate our package.json files for the main and sub-packages on-demand with a script, they are not in the repository.

It would be cool if we could create maybe a dummy folder with a minimal one for the packages, so that GitHub can pick it up and shows us a number and which projects are using it.

Example: https://github.com/playwright-community/jest-playwright/network/dependents?package_id=UGFja2FnZS04NjcyNjkyMjc%3D

@arjunattam

**Comment by JoelEinbinder** [comment]
Will dummy files work or do we need the correct dependencies in these package.jsons? We could publish the generated ones. It would be yet another script to add to npm watch. @pavelfeldman

**Comment by mxschmitt** [comment]
> Will dummy files work or do we need the correct dependencies in these package.jsons? We could publish the generated ones. It would be yet another script to add to npm watch. @pavelfeldman 

I think the best would be if it would contain the real dependenciee too (like mirror them), then they will be shown too. I would see potential value in this and it seems easy to add.

**Comment by mxschmitt** [comment]
Would be good to know, maybe ask the folks at GitHub what the minimum requirement is to have the feature to work, I tried:
- on my fork a small package.json, seems not to work: https://github.com/mxschmitt/playwright/network/dependents
- on a new repo a small package.json, seems not to work: https://github.com/mxschmitt/test/network/dependents

**Comment by mxschmitt** [comment]
Opened a GitHub support ticket 928291 for it, try to get more requirements whats needed out of it.

**Comment by mxschmitt** [comment]
Closed, the applied CR worked, see the outcome here: https://github.com/microsoft/playwright/network/dependents?package_id=UGFja2FnZS00MjQ2NjcwOQ%3D%3D

cc @JoelEinbinder @arjunattam
