### ISSUE TITLE
[BUG] Browser Closes when Print Window is opened

### ISSUE THREAD

**Issue by shirshak55** [microsoft/playwright#4337]
It seems we cannot test print features. Printing is important as almost all the app have invoice feature which usually needs to be tested. 

With Recent Update if i press Ctrl + P browser closes without giving any error? I don't know why its happening to me. I tried with firefox I got same result?

Is it only my issue? And please test it on non ephemeral mode

**Comment by JoelEinbinder** [comment]
Thanks for the report
- Which browser is this?
- Did this work with a previous version of playwright? I wouldn't have expected it to.

In headless chromium, you can use [page.pdf](https://playwright.dev/#version=v1.5.2&path=docs%2Fapi.md&q=pagepdfoptions) to print to pdf. Does this work for you?

**Comment by shirshak55** [comment]
@JoelEinbinder Its both firefox and chrome running latest version of puppeteer. 

And Yes previous version of playright used to work fine infact after doing yarn upgrade --interactive latest it stopped working.


And no page.pdf doesn't give high quality image I was surprised at this. The bar code it give wasn't even scanned by bar code reader.

**Comment by JoelEinbinder** [comment]
Can you provide a code snippet? I can't reproduce this.

What operating system. Can you also please provide an example of the low quality pdf. That sounds like a bug.

**Comment by shirshak55** [comment]
will pause it for a moment untill i reproduce.

**Comment by shirshak55** [comment]
ok guys it was upstream bug in chromium repo. So closing it :)
