### ISSUE TITLE
[BUG] WebKit Mac BrowserFetcher Link Not Working

### ISSUE THREAD

**Issue by isaacaddis** [microsoft/playwright#4348]
**Context:**
- Playwright Version: 1.5.2
- Operating System: Mac

**Describe the bug**

I cannot download the Playwright WebKit browser for Mac using the URL naming conventions outlined in [browserFetcher.ts](https://github.com/microsoft/playwright/blob/master/src/install/browserFetcher.ts). For example, I am using this download link: [https://playwright.azureedge.net/builds/webkit/1317/webkit-mac-10.15.zip](https://playwright.azureedge.net/builds/webkit/1317/webkit-mac-10.15.zip). It downloads the actual folder fine, but it won't open. Trying to open the downloaded application in a Terminal gives the following output:

```
dyld: Symbol not found: _OBJC_CLASS_$__WKBrowserContext
  Referenced from: /Applications/webkit-mac-10/Playwright.app/Contents/MacOS/Playwright
  Expected in: /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
 in /Applications/webkit-mac-10/Playwright.app/Contents/MacOS/Playwright
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

If this is a bug, I hope it can get fixed soon, and if it is not, I hope someone can point me in the right directions about what I might be doing wrong! Thank you

**Comment by JoelEinbinder** [comment]
[playwright-cli](https://github.com/microsoft/playwright-cli) is an easy way to run the playwright browsers on any platform. No need to download them yourself!

However if you must, the `Playwright` executable is designed to be run by `pw_run.sh`. It sets up the library paths for everything to work correctly.

Closing this issue, but feel free to continue the discussion here if you have more questions or if something doesn't work.

**Comment by isaacaddis** [comment]
Thanks for your quick response, unfortunately I do need the actual browser. Is there anyway to get past the repeated "___ is damaged and can’t be opened" (especially for JavaScriptCore.framework and WebCore.framework) dialogs, after running `sh pw_run.sh`?

**Comment by yury-s** [comment]
@isaacaddis can you share the error message that you get?

Also does it work if you install playwright via `npm` and try to launch the browser from playwright script?
