### ISSUE TITLE
[BUG] Webkit in Docker only scroll once

### ISSUE THREAD

**Issue by diegofernandezmrf** [microsoft/playwright#4366]
**Context:**
- Playwright Version: 1.5.2
- Operating System: Linux
- Node.js version: 12
- Browser: Chromium, WebKit
- Extra: It's the Docker image provided by you
```
  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    Memory: 2.25 GB / 3.84 GB
    Container: Yes
  Binaries:
    Node: 12.19.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.8 - /usr/bin/npm
  Languages:
    Bash: 5.0.17 - /usr/bin/bash
```
**Code Snippet**

I created a repository that could be used to easily reproduce the error: https://github.com/Marfeel/use-cases/tree/master/playwright-docker-webkit

but here is the gist of it

```javascript
test('the page should scroll down twice', async () => {
  await page.goto('http://localhost:8084')

  // the scroll is at the very top
  expect(await page.evaluate(() => window.scrollY)).toBe(0);
  // there is enough scroll heigth available
  expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBeGreaterThan(400);

  await page.waitForFunction(() => window.scroll(0, 100) || true);
  // just to check the scroll worked
  expect(await page.evaluate(() => window.scrollY)).toBe(100);

  await page.waitForFunction(() => window.scroll(0, 200) || true);
  // this expectation should pass on host and fail on docker
  expect(await page.evaluate(() => window.scrollY)).toBe(200);
});

```

**Describe the bug**

My team was using playwright in our computers (all macs) but we wanted to make it part of our CI tests.
I changed the docker image we used to yours and tests that rely on scrolling to trigger some behaviour started failing in webkit (all tests run fine on chromium).
The problem seems to be that only the first call to `window.scroll(...)` is taking effect.

Please let me know if you need more information, and available to help with it.

**Comment by JoelEinbinder** [comment]
I can repro most of this locally. Docker doesn't change the results, but it looks like there is something very strange with how scrolls are handled in our headless webkit with emulation. If I scroll 0 to 100 to 200, it ends up at 100. If I scroll 0 to 100 to 110, it ends at 10(?!).

Thanks for the report! I'm still debugging.

**Comment by diegofernandezmrf** [comment]
I forgot to mention my host is running MacOS, maybe that is why it works on the host and not on Docker.

**Comment by diegofernandezmrf** [comment]
Any news here? We chose Playwright for it's WebKit support but we are not running WebKit right now because of this bug.
Is there anything I can do to unblock this?

**Comment by pavelfeldman** [comment]
@diegofernandezmrf: Hang on, this fell through the cracks, resolving it asap.

**Comment by aslushnikov** [comment]
This is fixed with https://github.com/microsoft/playwright/pull/5173 and verified with https://github.com/microsoft/playwright/pull/5550

**Comment by diegofernandezmrf** [comment]
Thanks for fixing this one 👏 👏 👏 👏 

Will this be released as a minor or a patch?

**Comment by JoelEinbinder** [comment]
> Thanks for fixing this one 👏 👏 👏 👏 
> 
> 
> 
> Will this be released as a minor or a patch?

It'll be a minor release. Targeting 1.9 which should be released shortly.
