### ISSUE TITLE
Can I control the opened browser

### ISSUE THREAD

**Issue by mokaki** [microsoft/playwright#4371]
Hello
I am making a facebook plugin with playwright python
 
Every time you modify the code, you must reopen chrome and log in again
However, if you log in multiple times in a short time, fb will block the account

Can I control the opened browser
Thank you

```py



name_entry ='mail.com'
pwd_entry ='@#^'
FBcode000 = str('https://www.facebook.com/')
FBcode010 = str('//*[@id="email"]')
FBcode011 = str('//*[@id="pass"]')
FBcode012 = str('//*[@id="u_0_b"]')
def fblogin(page):
page.goto(FBcode000)
page.fill(FBcode010, name_entry)
page.fill(FBcode011, pwd_entry)
page.click(FBcode012)
os.system("pause")

if __name__ == "__main__":
playwr = playwright.sync_playwright().start()
browser = playwr.chromium.launch(headless=False)
page = browser.newPage()
try:
fblogin(page)
except Exception as e:
logging.exception(e)
finally:
browser.close()
playwr.stop()





```

**Comment by yury-s** [comment]
You can store facebook cookies first time after you've signed in and restore them in the context (using `BrowserContext.addCookies`) next time you launch playwright. Alternatively, you could use persistent context that would persist all user data between sessions: [launchPersistentContext](https://microsoft.github.io/playwright-python/sync_api.html#playwright.sync_api.BrowserType.launchPersistentContext)
