### ISSUE TITLE
[Question] Is it possible to extend launchServer?

### ISSUE THREAD

**Issue by Alexeykhr** [microsoft/playwright#4379]
Hi, thanks for the wonderful library. Can I extend the logic for working with a websocket connection?

[lauchServer](https://github.com/microsoft/playwright/blob/master/src/browserServerImpl.ts#L43)

For example, monitor connections, catch messages, etc.

And the `logger`, should it display the commands being executed?

![image](https://user-images.githubusercontent.com/14747569/98465428-abd9ef00-21d1-11eb-9cf3-0f6297502e8d.png)

**Comment by pavelfeldman** [comment]
You should be getting log messages when client attaches to the socket, but they will be low-level ones. Commands being executed are available to the logger on the client side. What do you mean by catch messages?

**Comment by Alexeykhr** [comment]
I'm sorry, I probably didn't understand the logic of creating a server :)

I originally thought this. If a couple of clients connect to the server, then how can I track/limit the number of connections, maybe filter commands, etc.?

And also the question, if I cannot track the commands and everything that comes from the client to the server, then perhaps through the logs on the server I can track the commands being executed, since the property is present, why not :)

So .. Apparently I didn't understand the original purpose of the method `lauchServer`

**Comment by pavelfeldman** [comment]
Hang on, it looks like logger passed into launchServer is broken. If you are interested in sniffing to the protocol, you can run Playwright with `DEBUG=pw:channel*` env variable, no need to use `launchServer` for that, things work over the protocol internally anyways.

**Comment by yury-s** [comment]
The protocol messages are now passed to the logger. Feel free to reopen if you have further questions.
