### ISSUE TITLE
[Question] drag and drop

### ISSUE THREAD

**Issue by Whooolia** [microsoft/playwright#4382]
![Screen Shot 2020-11-09 at 6 24 41 PM](https://user-images.githubusercontent.com/36998110/98523176-f6826680-22b8-11eb-9bf4-9d3167462c16.png)

^ what the steps option does? without passing steps, it doesn't drag and drop, but with that, it does.

can anyone explain what's the difference, thanks

**Comment by yury-s** [comment]
The `steps` parameter allows to break the path from start to end point into `steps` equal intervals and do that many smaller moves. So essentially it is equivalent to `steps` calls of `move()` ([here](https://github.com/microsoft/playwright/blob/58b5872ecbf8568d807d43a937eb997ebb7c4e1e/src/server/input.ts#L186) is the code that implements it). It's hard to tell how it affects drag-and-drop in your case, we are working on native support for drag-n-drop which is tracked by #1094
