### ISSUE TITLE
[Feature] a hook mechanism to augment cross-cutting logic

### ISSUE THREAD

**Issue by devalex88** [microsoft/playwright#4390]
Hi Playwright developers. Thank you so much for this great framework. One thing I would love to see in Playwright is the ability to intercept commands send to browsers for handling some cross-cutting concerns such as logging. Is it currently available or in the roadmap?

**Comment by pavelfeldman** [comment]
Could you share more about your goal?

**Comment by devalex88** [comment]
@pavelfeldman I'm looking for something like this https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/support/events/WebDriverEventListener.html. As an example I would be able to capture the screenshots after every `page.click()`.

**Comment by pavelfeldman** [comment]
Got it. For screenshots to work, you need async hooks that we await for and we don't have those. It is a fine idea though, so I'm leaving this open as a feature request.

**Comment by devalex88** [comment]
Thank you @pavelfeldman. Just to clarify, did you mean that non-async hooks were available?

**Comment by pavelfeldman** [comment]
No, I just meant to say that we would need hooks to be async as we are implementing them.

**Comment by pavelfeldman** [comment]
Closing this as a part of the triage, please feel free to file a new issue with additional details. Given the limited resource and a lot of requests, we need to fulfill most popular requests and at the same time keep our issue database manageable.
