### ISSUE TITLE
[BUG] Context.route => request.postData undefined in Chrome

### ISSUE THREAD

**Issue by yyvess** [microsoft/playwright#4392]
**Context:**
- Playwright version : 1.5.2
- Operating System: Windows
- Node.js version: 12
- Browser: Chrome
- Extra: Bug not present in Edge

**Code Snippet**

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const ctx = await browser.newContext();
  await ctx.route('**/*', (route, req) => {
       console.log(req.postData());
  });
})();
```

**Describe the bug**

In Context.route interceptor request.postData() is always undefined with Chrome.

That work as expected with Edge Chromium.

**Comment by yury-s** [comment]
It could be that you check `postData` on a wrong request, I don't see `route.continue()` in your snippet, in which case the code would stuck on the first request. Also I don't see any navigations in your snippet so it should not trigger `route` at all. The following snippet works for me locally, does it work for you?

```js
  const {chromium} = require('playwright');

  (async () => {
    const browser = await chromium.launch();
    const ctx = await browser.newContext();
    await ctx.route('**/*', (route, req) => {
      console.log('route url = ' + req.url() + ' req.postData() = ' + req.postData());
      route.continue();
    });
    const page = await ctx.newPage();
    await page.goto('https://example.com');
    await page.evaluate(() => fetch('./post', { method: 'POST', body: JSON.stringify({foo: 'bar'})}));
  })();
```

It prints following output:
```
route url = https://example.com/ req.postData() = null
route url = https://example.com/post req.postData() = {"foo":"bar"}
```

**Comment by yury-s** [comment]
Please reopen if you can still reproduce it.

**Comment by yyvess** [comment]
Thanks for your response.
Your code don't work but I suspect that is caused by my Chromium version that is 84.
