### ISSUE TITLE
[Question]Do I have to connect to localhost?

### ISSUE THREAD

**Issue by aaronportier** [microsoft/playwright#4395]
I am trying this out and using the example below. Everytime I try I get connection refused from Localhost. Computer is locked down heavily so any change I can make to fix that issue I have done. Can I achieve connecting this without Localhost?
Const playwright = require('playwright);
(async () => {
const browser = await playwright["chromium"].launch();
const context= await browser.newContext();
const page = await context.newPage();
I.amOnPage("('https://github.com');)")

**Comment by yury-s** [comment]
Which line is failing? Can you run with `DEBUG=pw:api*` and post the logs here?

Unless you are trying to navigate to a localhost url Playwright doesn't need access to it, so it should work.

**Comment by aaronportier** [comment]
Where in the code is it navigating to the localhost?

**Comment by yury-s** [comment]
Like I said above Playwright itself does not navigate to localhost unless you instruct it to, so there is likely some code in your test that does it. Can you provide full code snippet, error message you see and logs produced when running with `DEBUG=pw:api*`, so that we could help you better understand what's going on?

**Comment by aaronportier** [comment]
I provided all the code I am using. I can't provide the logs though. I run
without debugging from Visual Studio code ide.

**Comment by yury-s** [comment]
The code snippet is incomplete and wouldn't compile, also it calls into `I.amOnPage` which suggests you are using CodeceptJS. The 'connection refused' error you are seeing may well come from their logic of launching playwright but it's hard to tell without seeing full snippet and knowing about how you run it.

> I can't provide the logs though. I run without debugging from Visual Studio code ide.

It should be possible to run the script from terminal.

Closing as there is not enough details to help you. Feel free to reopen if you can share the snippet.

**Comment by aaronportier** [comment]
Okay but I used the sample from the documentation and only used the last
 I am line after nothing else would work. It brings up Chrome and sits on
the URL for localhost. I run it through Visual Studio code run without
debugging. The code is the sample found in documentation.

**Comment by yury-s** [comment]
I suggest you first try running the snippet as is from the terminal and check that it doesn't throw any errors. Chances are the localhost issue has something to do with your setup IDE/codeceptjs configuration and it be nice to first rule them out.
