### ISSUE TITLE
[Question] Enhanced tracking protection for Firefox

### ISSUE THREAD

**Issue by partizanen69** [microsoft/playwright#4399]
Is there any way to launch Firefox with Enhanced tracking protection in strict mode. 
Thanks in advance.

**Comment by yury-s** [comment]
Playwright disables tracking protection in Firefox by default for performance reasons and to reduce number of requests to external URLs when running tests. Relevant user setting is [`pref("privacy.trackingprotection.enabled", false);`](https://github.com/microsoft/playwright/blob/c8a64b88e1bb3892db1481a11f58e4ba481a34e0/browser_patches/firefox/preferences/playwright.cfg#L229) You can pass your own overrides via [`firefoxUserPrefs`](https://playwright.dev/#version=v1.5.2&path=docs%2Fapi.md&q=browsertypelaunchoptions--options-firefoxuserprefs) browser launch option.

Please reopen the bug if it doesn't work or you have further questions.
