### ISSUE TITLE
[Docs] Add tap to actionability doc

### ISSUE THREAD

**Issue by arjunattam** [microsoft/playwright#4409]
https://github.com/microsoft/playwright/blob/master/docs/actionability.md

**Comment by ImpossibleIsPossible** [comment]
As I see, they already updated docs.

I tried tap to element with this code:
`await page.tap("#calculatedValue");`

But i get this error:
`page.tap is not a function`

Any idea?

**Comment by JoelEinbinder** [comment]
Tap is coming out in 1.6 (very soon!) you can npm I playwright@next to test it early.

**Comment by ImpossibleIsPossible** [comment]
> npm i playwright@next

THANKS A LOT!!!!!
