### ISSUE TITLE
[BUG] Can't get sessionStorage without slowMo option.

### ISSUE THREAD

**Issue by seunghunee** [microsoft/playwright#4422]
Hi, I'm very a newbie in playwright.
I followed [playwright's authentication tutorial](https://playwright.dev/#version=v1.6.1&path=docs%2Fauth.md&q=).
I just want get session storage and store as environment variable.
Following code works. But, without [slowMo option](https://playwright.dev/#version=v1.6.1&path=docs%2Fapi.md&q=browsertypelaunchoptions--options-slowmo) it doesn't work. (Environment variable was empty)
Am I missing something?

**Context:**
- Playwright Version: 1.5.2
- Operating System: Linux and Mac
- Node.js version: 15.2.0
- Browser: Chromium (iPhone 7)
- Test runner: Jest (26.6.3)

**Code:**

Because of [tutorial's suggestion(section Lifecycle, #2)](https://playwright.dev/#version=v1.6.1&path=docs%2Fauth.md&q=lifecycle), I've tried to execute this code in globalSetup

```javascript
// setup.js
const { chromium, devices } = require("playwright");
const iPhone7 = devices["iPhone 7"];

module.exports = async () => {
  const browser = await chromium.launch({ slowMo: 500 }); // --> No slowMo or less than 500, DOESN'T WORK !
  const context = await browser.newContext({ ...iPhone7 });
  const page = await context.newPage();

  // Interact with login form
  await page.click('text=Login');
  await page.fill('input[name="login"]', USERNAME);
  await page.fill('input[name="password"]', PASSWORD);
  await page.click('text=Submit');

  // Get session storage and store as env variable
  const sessionStorage = await page.evaluate(() => JSON.stringify(sessionStorage));
  process.env.SESSION_STORAGE = sessionStorage;
  console.log(sessionStorage); // --> Without slowMo, just empty object {} was printed

  await browser.close();
};

```

**Describe the bug**

If this code run faster than specific speed (500 milliseconds, like above example), it cannot get sesstionStorage data.

**Comment by pavelfeldman** [comment]
Slowmo just makes it wait a little for the login to navigate, complete and store credentials in the storage. You should wait for some trigger, something like `waitForNavigation`, `waitForSelector`, `waitForResponse`, etc., depending on how auth is implemented.

**Comment by seunghunee** [comment]
Very fast answer, Thank you!
Sorry for my careless :sweat_smile:
