### ISSUE TITLE
[Question] - Firefox.launch.Process failed to launch! No space left on device.

### ISSUE THREAD

**Issue by jknooks583** [microsoft/playwright#4432]
Seeing the following error message. Not sure how I can go about fixing this issue and was wondering if I could get help please.

```
browserType.launch: Process failed to launch!
=========================== logs ===========================
<launching> /home/udocker/awb-worker/node_modules/playwright-firefox/.local-browsers/firefox-1171/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-4MsxQP -juggler 0 -silent
<launched> pid=34339
[err] *** You are running in headless mode.
[err] [34339, Main Thread] WARNING: fallocate failed to set shm size: No space left on device: file /mnt/cron/playwright/browser_patches/firefox/checkout/ipc/chromium/src/base/shared_memory_posix.cc, line 189
[err] ExceptionHandler::GenerateDump cloned child 34389
[err] ExceptionHandler::SendContinueSignalToChild sent continue signal to child
[err] ExceptionHandler::WaitForContinueSignal waiting for continue signal...
[err] Traceback (most recent call last):
[err]   File "/usr/bin/lsb_release", line 25, in <module>
[err]     import lsb_release
[err] ModuleNotFoundError: No module named 'lsb_release'
[err] Unable to init server: Could not connect: Connection refused
```

**Comment by mxschmitt** [comment]
Hi, ` No space left on device: file` means that your disk is full. A little bit of storage is always required so browsers can create temporary files.

**Comment by yury-s** [comment]
@jknooks583 in what environment (what linux distribution, docker etc) do you see this? Firefox somehow fails to allocate shared memory for interprocess communication, so it might be unrelated to available disk space. Also the error from `lsb_release` suggests that the os may be in a bad state as normally it should print info about the debian system.

**Comment by jknooks583** [comment]
@yury-s For more context, we are launching multiple browser instances (we are closing them but we are launching quite a lot before they close out again) which I thought might be related to the issue. Wasn't sure if this is a problem and if so, how it can be fixed.

**Comment by yury-s** [comment]
That may well be the reason why it fails, do you mind sharing some details on how many browser instances are running simultaneously  and what is the machine configuration? Also you could consider creating reusing browser instance but creating multiple contexts instead which in general is more performant and our recommended way for running multiple tests in parallel.

**Comment by jknooks583** [comment]
We are using
2 CPU
4000 Memory
20000 Disk Size 

We are trying to increase memory and cpu here to see if it helps at all

**Comment by pavelfeldman** [comment]
Looks like out of memory / resources issue. Closing this for now, please feel free to reopen with the additional details!
