### ISSUE TITLE
[BUG] Firefox/Nightly Memory Leak

### ISSUE THREAD

**Issue by jasonandmonte** [microsoft/playwright#4434]
**Context:**
- Playwright Version: 1.5.2
- Operating System: Windows
- Node.js version: 12.18.4
- Browser: Firefox

**Code Snippet**

```javascript
const { firefox } = require('playwright');

(async function crawler() {
  const browser = await firefox.launch({ headless: false });
  const context = await browser.newContext({ viewport: null });
  const page = await context.newPage();

  for (let x = 0; x < 1000; x += 1) {
    // Review Nightly process in the Task Manager
    await page.goto('https://www.youtube.com/');
    await page.waitForTimeout(1000);
  }
}());
```

**Describe the bug**

When navigating to multiple JavaScript heavy pages I am seeing consistent growth of the memory usage in the Task Manager by Nightly. Even though only one page is ever active, resources are not released.  This eventually leads to an `out of memory` error in the browser console and the script hangs on the page.

**Comment by yury-s** [comment]
I can reproduce this locally on my Linux box, browser process memory footprint gradually grows from 300Mb to 15Gb with 1k iterations in the script.
