### ISSUE TITLE
[REGRESSION]: self signed certificate in certificate chain -> Error with installation

### ISSUE THREAD

**Issue by diegoavalon** [microsoft/playwright#4439]
Hi Playwright team,

I ran into some security issues when installing Playwright with Yarn that didn't happen a couple of months ago. For example, I  can successfully install older versions such as v1.5 today.

The error I'm getting when running `yarn add -D playwright` is:
```
yarn add -D playwright
yarn add v1.22.5
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[1/2] ⠂ playwright
error /Users/davalon/Projects/Work/medicare-tools-test/node_modules/playwright: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/davalon/Projects/Work/medicare-tools-test/node_modules/playwright
Output:
(node:29537) UnhandledPromiseRejectionWarning: Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:29537) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:29537) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

upgrading npm or even the risky `yarn config set strict-ssl=false` and other common solutions don't help. Are there any new code changes released 

========
System Software Overview:

      System Version: macOS 10.15.6 (19G2021)
      Kernel Version: Darwin 19.6.0
      Boot Volume: Macintosh HD
=========
Model Name: MacBook Pro
      Model Identifier: MacBookPro16,1
      Processor Name: 6-Core Intel Core i7
      Processor Speed: 2.6 GHz

**Comment by pavelfeldman** [comment]
Did you set up proxy for playwright browser download?

**Comment by diegoavalon** [comment]
Thank you @pavelfeldman, this ended up being an environment issue with our cloud security platform. I've added the proper certs to my local environment and no longer have this issue. Closing as not related to this project. Thanks again!

**Comment by boris-meerovich-sp** [comment]
@diegoavalon Any chance you can explain what was a solution?
