### ISSUE TITLE
[BUG] Periodic call page.innerHTML() leads to memory leak

### ISSUE THREAD

**Issue by a-konyaev** [microsoft/playwright#4440]
**Context:**
- Playwright Version: 1.6.1
- Operating System: Windows, Linux
- Node.js version: 12.18.2
- Browser: Chromium

**Code Snippet**
```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const url = 'http://www.eveandersson.com/pi/digits/1000000';
  const selector = 'body > table:nth-child(4) > tbody > tr > td:nth-child(1) > pre';

  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.goto(url, {waitUntil: 'domcontentloaded'});

  while (true) {
    await new Promise(r => setTimeout(r, 100));
    const content = await page.innerHTML(selector);
    console.info('new content: ' + content.length);
  }
})();
```

**Describe the bug**
If my program repeatedly gets some data from the page (e.g. calling page.innerHTML) it leads to a memory leak. 
I found a place that leads to this: see `src/server/dom.ts:738`
If I commented out this line `//this._streamLogs();` so then everything becomes ok.

**Comment by pavelfeldman** [comment]
Thanks for the report and the investigation!

@dgozman
