### ISSUE TITLE
When running playwright through github actions, it's unable to navigate properly.

### ISSUE THREAD

**Issue by DanJohnstonArmory** [microsoft/playwright#4443]
Hello! i'm using playwright for the first time and the tests run fine locally. When I try to run inside a github action though, it times out before it does anything. 

I have noticed the following which may be the cause? 

`2020-11-15T05:59:20.938Z pw:api => browserType.connect started
2020-11-15T05:59:20.950Z pw:browser [err] [1115/055920.811686:ERROR:vaapi_wrapper.cc(539)] Could not get a valid VA display
2020-11-15T05:59:20.963Z pw:api <= browserType.connect succeeded`

My action looks like this and I'm using "playwright": "^1.6.0"
`on: [pull_request]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
      - uses: microsoft/playwright-github-action@v1.4.4
      - name: Install dependencies
        run: yarn
      - name: Start local service and run tests
        run: yarn test:e2e`

Please let me know what other information would be useful for debugging!

**Comment by DanJohnstonArmory** [comment]
From looking at the code, Playwright.navigate is called via webkit and Page.navigate from Chromium. I only have Chromium selected in my jest.playwright.config.js. But I think it at least gives me a breadcrumb to work with :-)

**Comment by DanJohnstonArmory** [comment]
I'm closing this for now as I dig deeper.

**Comment by koynoyno** [comment]
@DanJohnstonArmory Have you solved this problem?
