### ISSUE TITLE
[BUG] Cannot install chromium on Cloud Functions

### ISSUE THREAD

**Issue by sakebook** [microsoft/playwright#4444]
**Context:**
- Playwright Version: v1.6.1
- Operating System: Linux
- Node.js version: v12.18.4
- Browser: Chromium
- Extra: PLAYWRIGHT_BROWSERS_PATH=0

**Code Snippet**

```javascript
const playwright = require('playwright-chromium');
exports.capture = (req, res) => {
    capturePage(res)
};

function capturePage(res) {
    (async () => {
        const browser = await playwright.chromium.launch({
            args: ["--no-sandbox"],
        });
        const page = await browser.newPage();
        await page.goto('http://whatsmyuseragent.org/');
        await page.screenshot({ path: `/tmp/example.png` });
        await browser.close();
    })();
}
```

**Describe the bug**

I tried three libraries with Node 12.

- puppeteer
- playwright-aws-lambda
- playwright-chromium

puppeteer and playwright-aws-lambda are work fine.

playwright-chromium is not work.

I guess download failed.

Error

```
2020-11-15 18:46:06.530 JSTcapturema7fim0d6js8 browserType.launch: Failed to launch chromium because executable doesn't exist at /workspace/node_modules/playwright-chromium/.local-browsers/chromium-823944/chrome-linux/chrome
browserType.launch: Failed to launch chromium because executable doesn't exist at /workspace/node_modules/playwright-chromium/.local-browsers/chromium-823944/chrome-linux/chrome
2020-11-15 18:46:06.530 JSTcapturema7fim0d6js8 Try re-installing playwright with "npm install playwright"
```

I use environment variables

- PLAYWRIGHT_BROWSERS_PATH=0

Any solution?

**Comment by pavelfeldman** [comment]
> PLAYWRIGHT_BROWSERS_PATH=0

You tell it not to download Playwright, so it doesn't. And then it can't launch!

**Comment by sakebook** [comment]
> You tell it not to download Playwright, so it doesn't. And then it can't launch!

I'm using `PLAYWRIGHT_BROWSERS_PATH`, not `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD `.

I think `PLAYWRIGHT_BROWSERS_PATH=0` mean install to node_modules/${PACKAGE}/.local-browsers.

https://github.com/microsoft/playwright/blob/master/docs/api.md#environment-variables

**Comment by dgozman** [comment]
This works for me locally. Did you pass `PLAYWRIGHT_BROWSERS_PATH=0` both when installing and when running?

```sh
PLAYWRIGHT_BROWSERS_PATH=0 npm install playwright
PLAYWRIGHT_BROWSERS_PATH=0 node script.js
```

**Comment by sakebook** [comment]
> This works for me locally.

Yes me too. But not worked on Cloud Functions.

I am using CloudBuild. I excluded `node_modules/` with `.gcloudignore`.

Puppeteer is works fine in the same environment. Installing chromium when call function.

**Comment by dgozman** [comment]
@sakebook To be able to help you, we need some kind of repro scenario, otherwise we can only guess at the possible cause. 

For example, my guess would be that Cloud Functions run `npm install` for you and it is missing the `PLAYWRIGHT_BROWSERS_PATH=0` during installation.

Perhaps, you could point to a repository that exhibits this problem, or show some cloud function configs, or provide some other information?

**Comment by sakebook** [comment]
Currently deploy command execute on local.

```sh
$ gcloud builds submit . --config cloudbuild.yaml
```

My cloudbuild.yaml

```.yaml
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    timeout: 600s
    args:
      - functions
      - deploy
      - capture01
      - --source=.
      - --region=asia-northeast1
      - --trigger-http
      - --runtime=nodejs12
      - --allow-unauthenticated
      - --verbosity=debug
      - --memory
      - 512MB
      - --timeout=540s
      - --update-env-vars
      - PLAYWRIGHT_BROWSERS_PATH=0

    env:
      - PLAYWRIGHT_BROWSERS_PATH=0
```

The deployed source is as follows

![image](https://user-images.githubusercontent.com/729101/100309625-af051580-2fee-11eb-8d26-cb5f7ad8dc7d.png)

**Comment by dgozman** [comment]
Thank you for the information. This seems reasonable. Perhaps, you should also update [`--update-build-env-vars`](https://cloud.google.com/functions/docs/env-var#using_build_environment_variables) in addition to `--update-env-vars`, just in case there are separate env vars for `npm install` vs function execution?

**Comment by sakebook** [comment]
> --update-build-env-vars 

Not worked.

I've created a repository to reproduce.

https://github.com/sakebook/playwright-issue

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
