### ISSUE TITLE
[QUESTION] `failed to launch chromium` error while running `npx jest` within Dockerfile.bionic

### ISSUE THREAD

**Issue by fasatrix** [microsoft/playwright#4485]
**Context:**
I am using this container
https://github.com/microsoft/playwright/blob/master/docs/docker/Dockerfile.bionic

After running the container, install all dependencies  successfully, I have the following error:

**Command used to run the container:**

```
docker run -it --name playwright  -v "C:\myProject\web":/home mcr.microsoft.com/playwright bash
```

**Command used to install project dependencies:**

```
npm install 
```

Command to run tests: 

```
npx jest 
```

**Error:**

```
root@f542143afa64:/home/e2e_tests# npm run test
```

> catalogue-testing-framework-with-playwright@1.0.0 test /home/e2e_tests
> npx jest

```
Error: Failed to launch chromium because executable doesn't exist at /root/.cache/ms-playwright/chromium-827102/chrome-linux/chrome
Try re-installing playwright with "npm install playwright"
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at Chromium._launchProcess (/home/e2e_tests/node_modules/playwright/lib/server/browserType.js:128:19)
    at async Chromium._innerLaunch (/home/e2e_tests/node_modules/playwright/lib/server/browserType.js:70:62)
    at async ProgressController.run (/home/e2e_tests/node_modules/playwright/lib/server/progress.js:85:28)
    at async Chromium.launch (/home/e2e_tests/node_modules/playwright/lib/server/browserType.js:53:25)
    at async BrowserServerLauncherImpl.launchServer (/home/e2e_tests/node_modules/playwright/lib/browserServerImpl.js:35:25)
    at async PlaywrightRunner.launchServer (/home/e2e_tests/node_modules/jest-playwright-preset/lib/PlaywrightRunner.js:61:48)
    at async PlaywrightRunner.getTests (/home/e2e_tests/node_modules/jest-playwright-preset/lib/PlaywrightRunner.js:96:40)
    at async PlaywrightRunner.runTests (/home/e2e_tests/node_modules/jest-playwright-preset/lib/PlaywrightRunner.js:123:30)
    at async TestScheduler.scheduleTests (/home/e2e_tests/node_modules/@jest/core/build/TestScheduler.js:321:13)
    at async runJest (/home/e2e_tests/node_modules/@jest/core/build/runJest.js:376:19)
```

Any idea to what is going wrong here? thx

my package.json

```
{
  "name": "catalogue-testing-framework-with-playwright",
  "version": "1.0.0",
  "description": " E2E testing framework",
  "main": "index.js",
  "scripts": {
    "lint": "eslint test/**/*.{js,ts,tsx} --quiet --fix",
    "pretty": "npx prettier --no-config test/**/*.{js,ts,tsx} --write",
    "test": "npx jest"
  },
  "dependencies": {
    "chromedriver": "85.0.1",
    "jest": "26.6.3",
    "jest-playwright": "0.0.1",
    "jest-playwright-preset": "^1.4.0",
    "playwright": "^1.5.2",
    "ts-jest": "26.4.4",
    "typescript": "4.0.5"
  },
  "devDependencies": {
    "@types/jest": "26.0.15",
    "@types/node": "13.13.30",
    "eslint": "^6.6.0",
    "expect-playwright": "^0.2.6",
    "jest-circus": "^26.6.3",
    "jest-html-reporters": "^2.1.0",
    "playwright-core": "^1.5.2",
    "prettier": "2.1.2"
  },
  "license": "MIT",
}
```

**Comment by golfzaptw** [comment]
I got the same issue when I used the docker with the new Playwright version

**Comment by pavelfeldman** [comment]
My understanding is that `npx` does not run under `root` in docker and the temporary workaround is to `npm i jest` prior to calling it.

**Comment by fasatrix** [comment]
Thanks for your answer but still did not make much difference:

root@2af26501fb5b:/home/e2e_tests# node_modules/jest/bin/jest.js test/
Error: Failed to launch chromium because executable doesn't exist at /root/.cache/ms-playwright/chromium-827102/chrome-linux/chrome
Try re-installing playwright with "npm install playwright"
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at Chromium._launchProcess (/home/e2e_tests/node_modules/playwright/lib/server/browserType.js:128:19)
    at async Chromium._innerLaunch (/home/e2e_tests/node_modules/playwright/lib/server/browserType.js:70:62)
    at async ProgressController.run (/home/e2e_tests/node_modules/playwright/lib/server/progress.js:85:28)
    at async Chromium.launch (/home/e2e_tests/node_modules/playwright/lib/server/browserType.js:53:25)
    at async BrowserServerLauncherImpl.launchServer (/home/e2e_tests/node_modules/playwright/lib/browserServerImpl.js:35:25)
    at async PlaywrightRunner.launchServer (/home/e2e_tests/node_modules/jest-playwright-preset/lib/PlaywrightRunner.js:61:48)
    at async PlaywrightRunner.getTests (/home/e2e_tests/node_modules/jest-playwright-preset/lib/PlaywrightRunner.js:96:40)
    at async PlaywrightRunner.runTests (/home/e2e_tests/node_modules/jest-playwright-preset/lib/PlaywrightRunner.js:123:30)
    at async TestScheduler.scheduleTests (/home/e2e_tests/node_modules/@jest/core/build/TestScheduler.js:321:13)
    at async runJest (/home/e2e_tests/node_modules/@jest/core/build/runJest.js:376:19)


Test Suites: 0 of 4 total
Tests:       0 total
Snapshots:   0 total
Time:        6 sroot@2af26501fb5b:/home/e2e_tests#

**Comment by fasatrix** [comment]
I have installed all packages with -g and getting the same error what I found as difference is that this time I have something under **/root** but chromium still missing

`root@18d0b4236493:/home/e2e_tests# cd ~                                                            
root@18d0b4236493:~# pwd                                                                           
/root                                                                                              
root@18d0b4236493:~# ls -la                                                                        
total 40                                                                                           
drwx------ 1 root root 4096 Nov 17 21:06 .                                                         
drwxr-xr-x 1 root root 4096 Nov 19 17:34 ..                                                        
-rw-r--r-- 1 root root 3106 Apr  9  2018 .bashrc                                                   
drwxr-xr-x 2 root root 4096 Nov 17 21:06 .cache                                                    
drwx------ 1 root root 4096 Nov 17 21:06 .config                                                   
drwxr-xr-x 1 root root 4096 Nov 19 17:38 .npm                                                      
-rw-r--r-- 1 root root  148 Aug 17  2015 .profile                                                  
root@18d0b4236493:~# ls .cache/ms-playwright                                                       
.cache/ms-playwright                                                                               
root@18d0b4236493:~# ls -ltr .cache/ms-playwright                                                  
lrwxrwxrwx 1 root root 34 Nov 17 21:06 .cache/ms-playwright -> /home/pwuser/.cache/ms-playwright/  `

**Comment by fasatrix** [comment]
hey I found the workaround but would be good to have it sorted for root too.

Entry point should be pwuser. then install all modules under that user (npm i) and voila'

pwuser@d35208e019fa:~/e2e_tests$ npm i
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

> playwright-core@1.6.2 install /home/pwuser/e2e_tests/node_modules/playwright-core
> node install.js


> chromedriver@85.0.1 install /home/pwuser/e2e_tests/node_modules/chromedriver
> node install.js

/tmp/85.0.4183.87/chromedriver is not writable: EACCES: permission denied, open '/tmp/85.0.4183.87/chromedriver/1605810948234.tmp'
/tmp/85.0.4183.87/chromedriver is not writable: EACCES: permission denied, open '/tmp/85.0.4183.87/chromedriver/1605810948234.tmp'
Current existing ChromeDriver binary is unavailable, proceeding with download and extraction.
Downloading from file:  https://chromedriver.storage.googleapis.com/85.0.4183.87/chromedriver_linux64.zip
Saving to file: /home/pwuser/e2e_tests/node_modules/chromedriver/tmp/85.0.4183.87/chromedriver/chromedriver_linux64.zip
Received 1040K...
Received 2080K...
Received 3120K...
Received 4160K...
Received 5200K...
Received 5233K total.
Extracting zip contents to /home/pwuser/e2e_tests/node_modules/chromedriver/tmp/85.0.4183.87/chromedriver.
Copying to target path /home/pwuser/e2e_tests/node_modules/chromedriver/lib/chromedriver
Fixing file permissions.
Done. ChromeDriver binary available at /home/pwuser/e2e_tests/node_modules/chromedriver/lib/chromedriver/chromedriver

> playwright@1.6.2 install /home/pwuser/e2e_tests/node_modules/playwright
> node install.js

Downloading chromium v827102 - 119.8 Mb [====================] 100% 0.0s

chromium v827102 downloaded to /home/pwuser/.cache/ms-playwright/chromium-827102
Downloading firefox v1205 - 72.7 Mb [====================] 100% 0.0s
firefox v1205 downloaded to /home/pwuser/.cache/ms-playwright/firefox-1205
Downloading webkit v1383 - 71.3 Mb [====================] 100% 0.0s
webkit v1383 downloaded to /home/pwuser/.cache/ms-playwright/webkit-1383
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.2.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 751 packages from 472 contributors and audited 756 packages in 299.17s

31 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

pwuser@d35208e019fa:~/e2e_tests$
pwuser@d35208e019fa:~/e2e_tests$ ls -la /home/pwuser/.cache/ms-playwright/chromium-827102
total 0
drwxrwxr-x 1 pwuser pwuser 4096 Nov 19 18:37 .
drwxrwxr-x 1 pwuser pwuser 4096 Nov 19 18:37 ..
-rw-rw-r-- 1 pwuser pwuser    0 Nov 19 18:37 INSTALLATION_COMPLETE
drwxr-xr-x 1 pwuser pwuser 4096 Nov 19 18:37 chrome-linux

**Comment by Prior99** [comment]
Same problem here. Seems like the image wasn't updated, but chrome was.

**Comment by ryneeverett** [comment]
TLDR Workaround: `su pwuser`

**Comment by alstas** [comment]
Having the same issue. Running playwright with jest-playwright in Azure Pipelines inside a docker container. Tried suggested workarounds - did not help.

 In my case, the `npm install` command downloads the `chromium-833159` browser but the playwright looks for the `chromium-827102`.

Even if I set the browser path with `executablePath` option:
```
  launchOptions: {
    executablePath: '/home/pwuser/pw-browsers/chromium-833159/chrome-linux/chrome',
  },
```
it still looks for the `chromium-827102` (but launches the `chromium-833159` first?).

The logs that I'm getting with `DEBUG=pw:browser`:
```
 2020-12-22T21:53:48.907Z pw:browser <launching> /home/pwuser/pw-browsers/chromium-833159/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=/tmp/playwright_chromiumdev_profile-jkcTGS --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --no-startup-window
 2020-12-22T21:53:48.913Z pw:browser <launched> pid=43
 2020-12-22T21:53:49.006Z pw:browser [err] [1222/215349.005503:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
 2020-12-22T21:53:53.237Z pw:browser [err] [1222/215349.021621:ERROR:vaapi_wrapper.cc(617)] Could not get a valid VA display
 FAIL browser: chromium specs/ux-landing-mocked.spec.ts
   ● website › Home
 
     browserType.launch: Failed to launch chromium because executable doesn't exist at /home/pwuser/pw-browsers/chromium-827102/chrome-linux/chrome
     Try re-installing playwright with "npm install playwright"
     Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.:
```

**Comment by aslushnikov** [comment]
(sorry for the long reply - we have a huge stream of incoming requests)

> I am using this container
https://github.com/microsoft/playwright/blob/master/docs/docker/Dockerfile.bionic

@fasatrix did you just build it yourself and then use it? How would I reproduce this error locally?

**Comment by aslushnikov** [comment]
@alstas your case seems to be different. Can you please file a separate issue? Also, details that would help us reproduce this locally are greatly appreciated!

**Comment by fasatrix** [comment]
> (sorry for the long reply - we have a huge stream of incoming requests)
> 
> > I am using this container
> > https://github.com/microsoft/playwright/blob/master/docs/docker/Dockerfile.bionic
> 
> @fasatrix did you just build it yourself and then use it? How would I reproduce this error locally?

@aslushnikov No worries I know you guys are busy..

I am using the following repo only as example but the behavior is exactly the same as for mine

Platform windows 10

Steps: 

1.  cd c:\temp (or wherever you want to)
2. git clone https://github.com/marcosvega91/msw-ssl.git
3. cd msw-ss
4. docker run -it --name playwright -v C:\Users\FSantoro\Projects\WebstormProjects\msw-ssl:/home mcr.microsoft.com/playwright bash
5. At this stage your prompt should be root
6. cd /home/src
7. npm install
8. npm run test

Error

root@11675bad909f:/home# npm run test

> msw-ssl@0.1.0 test /home
> jest

Error: Failed to launch chromium because executable doesn't exist at /root/.cache/ms-playwright/chromium-844399/chrome-linux/chrome
Try re-installing playwright with "npm install playwright"
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at Chromium._launchProcess (/home/node_modules/playwright/lib/server/browserType.js:134:19)
    at async Chromium._innerLaunch (/home/node_modules/playwright/lib/server/browserType.js:73:62)
    at async ProgressController.run (/home/node_modules/playwright/lib/server/progress.js:85:28)
    at async Chromium.launch (/home/node_modules/playwright/lib/server/browserType.js:55:25)
    at async BrowserServerLauncherImpl.launchServer (/home/node_modules/playwright/lib/browserServerImpl.js:35:25)
    at async PlaywrightRunner.launchServer (/home/node_modules/jest-playwright-preset/lib/PlaywrightRunner.js:62:48)
    at async PlaywrightRunner.getTests (/home/node_modules/jest-playwright-preset/lib/PlaywrightRunner.js:97:40)
    at async PlaywrightRunner.runTests (/home/node_modules/jest-playwright-preset/lib/PlaywrightRunner.js:121:30)
    at async TestScheduler.scheduleTests (/home/node_modules/@jest/core/build/TestScheduler.js:321:13)
    at async runJest (/home/node_modules/@jest/core/build/runJest.js:376:19)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! msw-ssl@0.1.0 test: `jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the msw-ssl@0.1.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-02T02_15_30_862Z-debug.log
root@11675bad909f:/home#

**Comment by fasatrix** [comment]
@aslushnikov 
on a different note where would it be a good place to start a conversation around playwright and openlayers (https://openlayers.org/) testing?
My team is building apps that are using openlayer as base for maps and build the application on top of that (layers). We would like to use some playwirght APIs to interact with openlayers (e.g zoom in , draws polygons , select points etc.)
I was able to do some very basic interaction  using puppeteer using  but not totally satisfied .. however it seems harder with playwirght.. Do you guys have any suggestion/recommendation to tests maps with playwright?

**Comment by aslushnikov** [comment]
@fasatrix awesome, thank you for the repro. I can repro now.

> `docker run -it --name playwright --user pwuser -v c:\temp\msw-ssl:/home/pwuser mcr.microsoft.com/playwright bash`

The reason this doesn't work is because you're overwriting the `/home/pwuser` location with your project mount. The `/home/pwuser` location contains playwright registry, so after this things go south.

One easy fix would be to mount your project to some root location inside docker. For example, the following worked for me:

```shell
$ docker run -it --name playwright --user pwuser -v c:\temp\msw-ssl:/mswssl mcr.microsoft.com/playwright bash
$ cd /mswssl
$ npm ci && npm run test
```

On a related note, I'd recommend using a docker image version that matches the playwright version you use. This way
you can save some time on `npm i` step inside docker since playwright will use the pre-installed browsers inside docker image.

Since you use playwright v1.6.2, you can use a matching docker image;

```shell
$ docker run -it --rm -v c:\temp\msw-ssl:/mswssl mcr.microsoft.com/playwright:v1.6.2 bash
$ cd /mswssl
$ npm ci && npm run test
```

> on a different note where would it be a good place to start a conversation around playwright and openlayers (https://openlayers.org/) testing?

I'd suggest opening a new issue and sharing your problems. It should all just work!

**Comment by aslushnikov** [comment]
@fasatrix but actually let me try fixing our docker image..

**Comment by fasatrix** [comment]
> @fasatrix but actually let me try fixing our docker image..

That's what I thought it'd be the best anti error prone solution. Thanks allot @aslushnikov you are the best 😉

**Comment by nboisteault** [comment]
> @aslushnikov on a different note where would it be a good place to start a conversation around playwright and openlayers (https://openlayers.org/) testing? My team is building apps that are using openlayers as base for maps and build the application on top of that (layers). We would like to use some playwright APIs to interact with openlayers (e.g zoom in , draws polygons , select points etc.) I was able to do some very basic interaction using puppeteer using but not totally satisfied .. however it seems harder with playwright.. Do you guys have any suggestion/recommendation to tests map with playwright?

Hi @fasatrix  I'm also interested in testing OpenLayers with Playwright. Did you achieve to draw a point and move it on the map with Playwright?
