### ISSUE TITLE
[Question] chromium with head

### ISSUE THREAD

**Issue by Whooolia** [microsoft/playwright#4486]
Hello, I've got a question regarding running chromium with head.

It's very weird behaviour because I can run locally with the head but not against dev. However, my colleague has no issue to run against dev with head.

For me, it is firstly open the chrome to log in(SSO Microsoft) and seems trying to redirect to the site. At this point, it closes the browser and failed.

It doesn't throw any error, it just close and failed at this.

```
 logStep(`Navigating to the dashboard`)
  console.log('here')
  await page.waitForNavigation({ url: /dashboard/i })
``` 

When I run it yesterday, I've got this below. Is there anything I can try? It's so hard to debug without a head when some tests fail.

* If I run with Firefox, I can see the head sometimes.

<img width="1432" alt="Screen Shot 2020-11-18 at 11 57 37 AM" src="https://user-images.githubusercontent.com/36998110/99625513-c59df080-2a73-11eb-855c-38d0e8f7078a.png">

**Comment by aslushnikov** [comment]
> Hello, I've got a question regarding running chromium with head.

@Whooolia hey! Do I understand correctly that this is "running Chromium in headful mode"?

> It's very weird behaviour because I can run locally with the head but not against dev. 

What "dev" are we talking about? Is this a "dev" version of the website you're testing? 

> Is there anything I can try?

I don't yet understand the whole picture, but from the screenshot you show it looks like you don't have certificates on the website. You should either setup certificates, or create playwright context with [`ignoreHTTPSErrors`](https://playwright.dev/#version=v1.6.2&path=docs%2Fapi.md&q=browsernewcontextoptions--options-ignorehttpserrors) option.

**Comment by pavelfeldman** [comment]
We are lacking information to resolve this one, could you please file it with the additional details for us to be able to act on it?
