### ISSUE TITLE
[BUG] Playwright not intercepting fetch requests in WebWorker

### ISSUE THREAD

**Issue by David-Development** [microsoft/playwright#4487]
**Context:**
- Playwright Version: 1.6.2
- Operating System: Mac, Linux, Docker
- Node.js version: 12 & 14
- Browser: Chromium

```
System:
  OS: macOS 11.0.1
  Memory: 651.86 MB / 32.00 GB
Binaries:
  Node: 14.8.0 - /usr/local/bin/node
  npm: 6.14.7 - /usr/local/bin/npm
Languages:
  Bash: 3.2.57 - /bin/bash
```

**Code Snippet**

I created a minimal example to reproduce the issue. You can find it here:

https://github.com/David-Development/playwright-worker-bug

**Describe the bug**

Intercepting network requests does not work if the request is made from a web worker. Only fetch requests from the main execution thread will be intercepted. I'm trying to use the `route.fulfill` method to mock some data that our web workers are fetching. If I disable the web workers in our application it works fine but if the requests are made from the web workers they are not intercepted. This happens on Chromium on Mac, Linux and inside the Playwright Docker Container.

**Comment by aslushnikov** [comment]
> https://github.com/David-Development/playwright-worker-bug

@David-Development thank you for the awesome repro! 🙏

> This happens in all browsers and at least on Mac, Linux and inside the Playwright Docker Container.

Interestingly, I can reproduce this only with Chromium, both Firefox and WebKit were able to intercept (I'm on Mac 10.15). Looks like a bug in Chromium.

**Comment by David-Development** [comment]
@aslushnikov Thank you for looking into it! 🙇‍♂️ Let me know if there is anything else I can do to help. 

> Both Firefox and WebKit were able to intercept

Oh, hm.. you are right! I just double checked and it work on Firefox and Safari (Mac 11.0.1). Sorry for the false alarm! After I saw this error the first time I just kept on testing against chromium. I'll adjust the ticket description then
