### ISSUE TITLE
Logging requests to BrowserServer

### ISSUE THREAD

**Issue by fabiomoggi** [microsoft/playwright#4498]
I am implementing the API reference code to output a messsage when a client requests BrowserServer to run Chrome:

    const browser = await chromium.launchServer({
        logger: {
            isEnabled: (name, severity) => name === 'browser',
            log: (name, severity, message, args) => console.log(`${name} ${message}`)
        }
    });

This code is supposed to write a message to the console whenver a new request comes in, however, no message is written.

I am wondering if there is an issue with this feature or the API doc is missing something - or I might be completely wrong about the purpose of this code =) 

Thanks!

**Comment by fabiomoggi** [comment]
Any feedback on this?

**Comment by dgozman** [comment]
> Any feedback on this?

`P3-collecting-feedback` label means we are collecting feedback from the community. Sorry if that is not clear.

The feature request is clear and I don't see anything specific that would prevent such a feature. However, the priority for this is not clear, so we look for community feedback (e.g. upvotes) to decide the priority compared to other features/bugs.

**Comment by fabiomoggi** [comment]
Thanks very much for taking the time to explain me the process, dgozman.

I was thinking the issue described was more a problem than a non-implemented feature.

Also tried posting it on Stackoverflow, but no answers at all. Seems like not many people run BrowswerServer as a remove server.

I will still investigate on how to run the API example correctly: 
`log: (name, severity, message, args) => console.log(`${name} ${message}`)`

Thanks for the support the community.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
