### ISSUE TITLE
[BUG] DeviceDescriptor not exposed

### ISSUE THREAD

**Issue by Th-Os** [microsoft/playwright#4507]
**Context:**
- Playwright Version: 1.4.0
- Operating System: Mac
- Node.js version: v14.5.0
- Browser: All
- Extra: VSCode

Error message:
Module '"../../node_modules/playwright"' has no exported member 'DeviceDescriptor'.
import { DeviceDescriptor } from 'playwright';

**Code Snippet**

```typescript
import { DeviceDescriptor } from 'playwright';

```

**Describe the bug**

Variants of above import, like `import { DeviceDescriptor } from 'playwright/types/types';` or `import { DeviceDescriptor } from 'playwright-core';` don't work either.

Could you please export this type?

**Comment by pavelfeldman** [comment]
@JoelEinbinder should we generalize it to BrowserContextOptions?

**Comment by pavelfeldman** [comment]
Closing this as a part of the triage, please feel free to file a new issue with additional details. Given the limited resource and a lot of requests, we need to fulfill most popular requests and at the same time keep our issue database manageable.
