### ISSUE TITLE
How to login to Microsoft Azure AD

### ISSUE THREAD

**Issue by aaronportier** [microsoft/playwright#4509]
I can't seem to even get to fill out the Sign-in screen. It gets me there then it does not fill out anything.
Const playwright= require('playwright');
(Async()=>{
const browser= await playwright["chromium"].Launch();
const context =await browser.newContext();
cons page = await context.newPage();
await page.goto("('https://login.microsoftonline.com');")})();
await page.fill('input[name="#email"]','1234@cloud.company.net');
await page.click('button#submit');

**Comment by yyvess** [comment]
Hi,
Your selector not look good.
Try fill('input[type=email]')

**Comment by aaronportier** [comment]
Thanks I put that in and ran my app. In Debug I see Could not read source
map for url: unexpected 404 response.

BSSO Telemetry: {"result":"Error":"No extension",type Chromes
so...Error:ChromeBrowserCote error No extension Extension not installed.

**Comment by dgozman** [comment]
The following script works for me locally and produces an expected error message `We couldn't find an account with that username.`

Note that I fixed the syntax around `page.goto` and also used correct selectors for `page.fill` and `page.click`.
Also, I am using `headless: false` option to actually see the page for debugging purposes. You can safely omit it.

```js
const playwright = require('.');
(async() => {
  const browser= await playwright.chromium.launch({ headless: false });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://login.microsoftonline.com');
  await page.fill('input[type=email]', '1234@cloud.company.net');
  await page.click('input[type=submit]');
})();
```

If this does not answer your question, please comment or reopen.

**Comment by aaronportier** [comment]
Thank you for the help with this. When I run my test it stops once I get to
the URL. The one I provided is not my actual url as I can not give it but
it uses Azure Ad. I think it uses my Launch Json script but does not run
playwright? I am using Visual Studio Code as an IDE and I click the Run
menu and Run Without Debugging is this the appropriate actions?
The config I am using is
"type":"pwa-chrome",
"request":"launch",
"name":"Launch Chrome",
"url":"my Azure ad url",
"webRoot":"${workspaceFolder}"

**Comment by dgozman** [comment]
@aaronportier The launch config you are using just launches Chrome itself and opens the url, it does not use Playwright.

I'd suggest to use the [debugging terminal](https://github.com/microsoft/vscode-js-debug#debug-nodejs-processes-in-the-terminal) with config similar to the following, or just open a terminal with "Debug: Create JavaScript Debug Terminal" command.

```json
{
  "type": "pwa-node-terminal",
  "command": "node my-playwright-script.js",
}
```

**Comment by aaronportier** [comment]
Thanks I have tried getting rid of the other configs to use your config but
the command is not recognized and type can only be "pwa-node" after I run
that nothing happens.

**Comment by aaronportier** [comment]
Update. I changed my config to Node Launch via NPM I also changed my url to
https://www.google.com just until I can get playwright to work at all. When
I start debug I can see the debug console say Process exited with code 1.

**Comment by dgozman** [comment]
Could you please post your javascript file here if possible? Did you try running this in terminal like `node myscript.js`?

**Comment by aaronportier** [comment]
I get cannot find module when I run node myscript.js...i can write my code
here in a few mins.

**Comment by aaronportier** [comment]
Const playwright= require('platwright');
(async () =>{
const browser = await chrome.launch({headless:false});
const context =await browser.newContext();
Const page = await context.newPage();
await page.goto(https://www.google.com);

Let's try to just get it to that point for now.
I sometimes also see Error the process "10124" not found
Node11000 UnhandledPromiseRejectionWarning browser type.launch protocol
error (Browser.getVersiob): Target closed.

**Comment by aaronportier** [comment]
Googled both those errors but neither have good defined fixes.

**Comment by aaronportier** [comment]
Using the Terminal I choose JavaScript debug Terminal I do node the name of
my script.js
I do have a launch.json with the Launch via NPM config but I am not running
it because of the above statement.
then I run into Error: The process 24368 not found.
UnhandledPromiseRejectionWarning: browser type.launch: Protocol error (
Browser.getVersion): Target closed. Followed by some [err]
crashforexceptionInNonABICompliantCodeRange
VR_GetStringForHmdErroRelaunchChroneBrowserwithNewCommandLineIfNeeded
CrashForexceptionInNonABICompliantCodeRange
ovly_debug_event
ChromeMain
Ordinal10
GetHandleVerifier
BaseThreadInitThunk
RtUserThreadStart
Error:process_reader_win.cc Access denied A process has requested access to
an object but has not been granted those rights.
at module.load etc
Unhandled PromiseTejectionWarning

**Comment by aaronportier** [comment]
Is anyone else experiencing the problem from my last email?
