### ISSUE TITLE
[BUG] 'The expression evaluated to a falsy value' in GitHub authentication example

### ISSUE THREAD

**Issue by alvipeo** [microsoft/playwright#4530]
Re-opening as [the original issue](https://github.com/microsoft/playwright/issues/4523) was quickly closed without fix.

- Playwright Version: 1.6.2
- Operating System: Windows 10
- Node.js version: 14.15.1

I just took this [authentication example](https://github.com/microsoft/playwright/blob/master/docs/examples/authentication.js) and run it and it didn't work. So I played with it but couldn't make it work (TypeScript):
```
import { chromium, webkit } from "playwright";
import * as assert from "assert";

const verifyIsLoggedIn = async (page) => {
  await page.click('summary[aria-label="View profile and more"]');
  let details = await page.waitForSelector("details[open]");
  await page.screenshot({ path: `verify.png` });
  // await page.waitForSelector("details-menu");           // ====> this one never works!
  const yourProfile = await details.$(`text="Your profile"`);
  assert(yourProfile);                                     // ====> FAILS
  await page.screenshot({ path: `verify1.png` });
};

/**
 * In this script, we will login on GitHub.com through Chromium,
 * and reuse the login cookies state inside WebKit. This recipe can be
 * used to speed up tests by logging in once and reusing login state.
 *
 * Steps summary
 * 1. Login on GitHub.com in Chromium
 * 2. Export cookies from Chromium browser context
 * 3. Set cookies in WebKit browser context and verify login
 */

const account = { login: "", password: "" };

(async () => {
  // Create a Chromium browser context
  const crBrowser = await chromium.launch();
  const crContext = await crBrowser.newContext();
  const crPage = await crContext.newPage();
  crPage.setDefaultTimeout(6000);

  // Navigate and auto-wait on the page to load after navigation
  await crPage.goto("https://github.com/login");

  // Fill login form elements
  await crPage.fill('input[name="login"]', account.login);
  await crPage.fill('input[name="password"]', account.password);

  // Submit form and auto-wait for the navigation to complete
  await crPage.click('input[type="submit"]');
  await verifyIsLoggedIn(crPage);

  // Get cookies from Chromium browser context
  const cookies = await crContext.cookies();
  await crBrowser.close();

  // Create WebKit browser context and load cookies
  const wkBrowser = await webkit.launch();
  const wkContext = await wkBrowser.newContext();
  await wkContext.addCookies(cookies);

  // Navigate to GitHub.com and verify that we are logged in
  const wkPage = await wkContext.newPage();
  await wkPage.goto("https://github.com");
  await verifyIsLoggedIn(wkPage);
  await wkBrowser.close();
})();
```
But the `verify1.png` screenshot does show the menu item that we're looking for.

The problem with the code is that `await page.waitForSelector("details-menu");` throws after timeout saying it got the element but it was hidden. It WAS NOT! That's verified by the screenshot.

Another problem (probably related) are these 2 lines:
```
 const yourProfile = await details.$(`text="Your profile"`);
  assert(yourProfile);                                     // ====> FAILS
```

The value of `yourProfile` is undefined even though the element IS PRESENT in the `details`. Basically, both problems are here:
```
const verifyIsLoggedIn = async (page) => {
  await page.click('summary[aria-label="View profile and more"]');
  let details = await page.waitForSelector("details[open]");
  await page.screenshot({ path: `verify.png` });
  // await page.waitForSelector("details-menu");           // ====> this one never works!
  const yourProfile = await details.$(`text="Your profile"`);
  assert(yourProfile);                                     // ====> FAILS
  await page.screenshot({ path: `verify1.png` });
};
```

**Comment by dgozman** [comment]
The link to the [authentication example](https://github.com/microsoft/playwright/blob/master/docs/examples/authentication.js) contains different code from what is posted here. Perhaps you are using the example from some strange place? Am I misreading it?

**Comment by alvipeo** [comment]
The example was the source. "It didn't work on my machine", so I tried different ways. My changes should work, but they don't. Anyway, I'm pretty sure it's a bug - the original version doesn't work and my version doesn't work but really should.

**Comment by pavelfeldman** [comment]
@alvipeo: I just tried the [authentication example](https://github.com/microsoft/playwright/blob/master/docs/examples/authentication.js) and it worked perfectly. What is your locale, could it be that GitHub is sending different page to your location?

**Comment by pavelfeldman** [comment]
I can see you are using wrong code to pick profile:

```
await details.$(`text="Your profile"`);
```

was replaced with
```
await page.waitForSelector(`text="Your profile"`)
```

based on your previous report.

**Comment by alvipeo** [comment]
ok, this one works:
```
const verifyIsLoggedIn = async (page) => {
   await page.click('summary[aria-label="View profile and more"]');
   await page.screenshot({ path: `verify.png` });
   // assert(await page.waitForSelector("details-menu"));                            ==> FAILS
   const yourProfile = await page.waitForSelector(`text="Your profile"`);
   assert(yourProfile);
   await page.screenshot({ path: `verify1.png` });
};
```

But I wonder why that commented line fails this way? Because at that moment `details-menu` does exist and it's visible.

>(node:22488) UnhandledPromiseRejectionWarning: page.waitForSelector: Timeout 6000ms exceeded.
=========================== logs ===========================
waiting for selector "details-menu" to be visible
  selector resolved to hidden <details-menu role="menu" class="dropdown-menu dropdown-menu-s…>…</details-menu>
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.:
    at Connection.sendMessageToServer (e:\Documents\repos\Playwright-test\node_modules\playwright\lib\client\connection.js:69:15)
    at Proxy.<anonymous> (e:\Documents\repos\Playwright-test\node_modules\playwright\lib\client\channelOwner.js:54:53)
    at e:\Documents\repos\Playwright-test\node_modules\playwright\lib\client\frame.js:180:48
    at Frame._wrapApiCall (e:\Documents\repos\Playwright-test\node_modules\playwright\lib\client\channelOwner.js:80:34)
    at Frame.waitForSelector (e:\Documents\repos\Playwright-test\node_modules\playwright\lib\client\frame.js:175:21)
    at e:\Documents\repos\Playwright-test\node_modules\playwright\lib\client\page.js:212:60
    at Page._attributeToPage (e:\Documents\repos\Playwright-test\node_modules\playwright\lib\client\page.js:202:20)
    at Page.waitForSelector (e:\Documents\repos\Playwright-test\node_modules\playwright\lib\client\page.js:212:21)
    at e:\Documents\repos\Playwright-test\github.ts:10:22
    at step (e:\Documents\repos\Playwright-test\github.ts:33:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22488) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by dgozman** [comment]
There are two `details-menu` in the page, you can check that by calling `page.$$('details-menu')`. The first one is a part of "plus" menu and is not visible.

**Comment by alvipeo** [comment]
Damn...! ok, thank you!
