### ISSUE TITLE
[BUG] unable to switch between tabs in test when run in Azure pipeline

### ISSUE THREAD

**Issue by onno-amsterdam** [microsoft/playwright#4531]
**Context:**
- Playwright Version: 1.6.2
- Operating System: Azure pipeline - vmImage: windows-latest (vs2017-win2016);
- Node.js version: v12.19.0
- Browser: [Chromium, Firefox]
- Jest: 26.6.3
- testRunner: Jasmine2

**Code Snippet**
Scenario 1: 
```javascript
// link should be opened in a new tab
await page.click('a.opens-in-new-tab');
// wait for tab to open (just to be sure);
await page.waitForTimeout(5000);
// grab all tabs
const pages = context.pages();
console.log(pages.length) // "2" when run locally, "1" when run in azure pipeline
```
Scenario 2:
```javascript
const [newPage] = await Promise.all([
     context.waitForEvent('page', { timeout: 5000 }),
     await page.click('a.opens-in-new-tab'),
]);
// Result local: no issue - can work with newPage
// Result Azure pipeline: TimeoutError: Timeout while waiting for event "page"
```

**Describe the bug**
In my test I click a link tab opens in a new tab. I try to switch to this new tab and continue the test execution. Both code snippets work fine when run locally on my Windows machine, however when run in Azure pipeline (dev.azure.com) both fail. I'm I missing something here or can this be an issue?

**Comment by pavelfeldman** [comment]
You should await for the 'popup' event, tests run faster for you locally, never use timeout in your tests, timeout is only for debugging.

**Comment by pavelfeldman** [comment]
The second snippet looks better, but you need to remove await before click and remove timeout (default one is 30s).

**Comment by onno-amsterdam** [comment]
Hi @pavelfeldman, thank you for your quick response and your help - with it I managed to get it working: 
```javascript
page.click(a.opens-in-new-tab);
context.waitForEvent('page');
newPage = context.pages();
expect (newPage.length).to.equal(2);
// continue with new page
```

**Comment by dgozman** [comment]
I'd suggest to follow [our docs](https://playwright.dev/#version=v1.6.2&path=docs%2Fverification.md&q=popup---handle-popup-windows) and write this:


```js
// Wait for the new page as a result of click action.
const [newPage] = await Promise.all([
     context.waitForEvent('page'),
     page.click('a.opens-in-new-tab'),
]);

// Now we can verify it works.
expect(context.pages().length).to.equal(2);
expect(context.pages().includes(page)).to.equal(true);
expect(context.pages().includes(newPage)).to.equal(true);
```

Please reopen the issue if this does not answer your question.
