### ISSUE TITLE
Add method to get web element coordinates

### ISSUE THREAD

**Issue by valeria20** [microsoft/playwright#4534]
I'd like to see something like `element.getLocation() <{x: nubmer, y: number}>`  to use coordinates for mouse move actions.

**Comment by mxschmitt** [comment]
Does maybe ElementHandle.boundingBox fit for your use case? With it you can get x, y and its width and height: https://playwright.dev/#version=v1.6.2&path=docs%2Fapi.md&q=elementhandleboundingbox

**Comment by valeria20** [comment]
> Does maybe ElementHandle.boundingBox fit for your use case? With it you can get x, y and its width and height: https://playwright.dev/#version=v1.6.2&path=docs%2Fapi.md&q=elementhandleboundingbox

You're right. Thanks :)

**Comment by acharjeeauntor** [comment]
Seems the above link (https://playwright.dev/#version=v1.6.2&path=docs%2Fapi.md&q=elementhandleboundingbox) is not available now. Team, Please update the link that will be very much helpful for us.

**Comment by shaikkkkk** [comment]
I believe this is the new link: https://playwright.dev/docs/api/class-locator#locator-bounding-box
