### ISSUE TITLE
[BUG] Actionability checks doesn't pass after actionable element changes size

### ISSUE THREAD

**Issue by Gotterbild** [microsoft/playwright#4537]
**Context:**
- Playwright Version: 1.6.2
- Operating System: Linux (Ubuntu 20.04)
- Node.js version: 10.19.0
- Browser: Chromium (didn't check other browsers)

Too busy right now and in too much hurry to create a snippet, sorry.

**Describe the bug**

Looks like actionability checks can be false negative after element changes its size. It leads to strange bugs.

In our app we have discount field that looks like this:
![image](https://user-images.githubusercontent.com/23502743/100544184-0b716a80-3265-11eb-96ce-19b8394a93ac.png)

When you click on a `Flat` button, the discount changes to percentage and sign on button represents that:
![image](https://user-images.githubusercontent.com/23502743/100544213-3360ce00-3265-11eb-9989-d5ad04ea2c90.png)

Notice the button changes its size. Physically it is the same DOM element, only the text changes.

Initially, when you click the button while text is `Flat`, the click is sucessful. Text changes to `Percentage`.

When you later make a click to change back, click never happens. It hangs and then fails due timeout.

When I try `force: true`, click action passes (promise resolves sucessfully), but button is actually not clicked.

But when I provide `position: { x: 16, y: 16 }` - the click is successful (promise resolves, click actually happens).

I think the issue is [actionability](https://github.com/microsoft/playwright/blob/master/docs/actionability.md) tests doesn't pass after button changes its size. Maybe the bounding box size is cached and Playwright expects button to be of different size (of bigger one). It looks like comprehending smaller size as a fact that element is unstable and waits until element becomes [stable](https://github.com/microsoft/playwright/blob/master/docs/actionability.md#stable).

**Comment by JoelEinbinder** [comment]
Thanks for the report.
Can you run your script with the environment variable set to `DEBUG=pw:api`? It should provide lots of useful info about what actionability checks are running.

Also can you please post the dom for this element? I'm curious how the text field relates to the button.

**Comment by aslushnikov** [comment]
Closing as part of triaging. Please re-file to bring back our attention if necessary.
