### ISSUE TITLE
[Feature] landmarks support for selection

### ISSUE THREAD

**Issue by callmemagnus** [microsoft/playwright#4538]
Hi all,

I think that supporting landmarks (HTML5 + ARIA: https://www.w3.org/TR/wai-aria-practices/examples/landmarks/index.html) in element selection would greatly enhance the quality of the written tests.

First because, in the end, no user should care that a `button` is a `<button>` or a `<div role="button">` (yeah I know, that is bad practice). Or that a `textbox`is an `<input>`, a `<textarea>` or a `<div role="textbox" contenteditable="true">`

Second because, having that available would probably make most selectors more legible instead of using lots of either xpath or css selector to do selection, those tests become dependent to the implementation at one given moment in time, and it might break when we upgrade a frontend component library.

It should even be documented as "the way to go" to write selectors. This would bring some attention to better semantic coding practices for those who don't already do it.

What do you think ?

PS: @testing-library that we use for component tests supports it: https://testing-library.com/docs/dom-testing-library/api-queries#byrole

**Comment by JoelEinbinder** [comment]
Thanks for the request. We've been discussing with the team a possible larger story around accessibility selectors.

@dgozman @avodovnik : another person who wants accessibility selectors.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.

**Comment by callmemagnus** [comment]
Sad day for writing legible tests.
