### ISSUE TITLE
[Question] Plans to implement puppetaria (aria/ selector)

### ISSUE THREAD

**Issue by AutoSponge** [microsoft/playwright#4543]
Are there plans to implement [this](https://developers.google.com/web/updates/2020/11/puppetaria) or something similar?

**Comment by pavelfeldman** [comment]
No such plans. We consider our new selectors to be a super-set of what can be achieved with just aria. See https://playwright.dev/docs/selectors for more details.

**Comment by AutoSponge** [comment]
I looked at the docs, there's no way to query implicit role in playwright.
