### ISSUE TITLE
[BUG] How to dismiss dialogs on Firefox?

### ISSUE THREAD

**Issue by saltyshiomix** [microsoft/playwright#4546]
The code below works well on Chromium and Webkit, but on Firefox.

```js
page.on('dialog', dialog => {
  dialog.dismiss().catch(() => {})
})
```

Is there another way to dismiss dialogs on Firefox?

**Update**:

An example repo which reproduces this error: https://github.com/saltyshiomix/playwright-issue-4546

It seems that Firefox can't handle the second dialog which includes the additional text `Prevent this page from creating additional dialogs`.

<img width="413" alt="スクリーンショット 2020-12-01 6 43 37" src="https://user-images.githubusercontent.com/5608079/100669439-be92ae80-33a0-11eb-8102-f952222bb8ef.png">

It works perfectly both of Chromium and Webkit 👍 

**Environment**

- Playwright version: `0.162.0`
- OS version: macOS Big Sur `11.0.1（20B29）`

**Comment by dgozman** [comment]
Could you please provide a page url, or a snippet that reproduces the issue?
Also, could you please provide Playwright version and OS version?

**Comment by saltyshiomix** [comment]
Thank you for your reply, @dgozman !

I edited the description of this issue.

By the way, I proudly believe the playwright saves the E2E world so I'm ready to contribute to around the playwright at anytime :)

**Comment by dgozman** [comment]
Thank you for your kind words! I can repro this, we'll fix it soon.
