### ISSUE TITLE
[Feature] Allow disabling third party cookies

### ISSUE THREAD

**Issue by weyert** [microsoft/playwright#4548]
I would like to be able to control whether the browser context running Playwright accepts third-party cookies. As I think it can be useful during test runs to block third-party cookies to see how the web-application behaves when disabled.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
