### ISSUE TITLE
[Question] Is there any way to instrument webkit/firefox with address asanitizer and launch it by specifying executablePath?

### ISSUE THREAD

**Issue by zyscoder** [microsoft/playwright#4558]
I downloaded WebKit from https://playwright.azureedge.net/builds/webkit/1317/webkit-mac-10.15.zip and launched it by specifying executablePath, and this works well. Now I would like to do some test on WebKit with asan. If there any advice for me?

**Comment by pavelfeldman** [comment]
That would be https://trac.webkit.org/wiki/ASanWebKit, but you would need to apply our patches from the browser_patches folder. What is your end goal?

**Comment by zyscoder** [comment]
I try to build webkitgtk from a release tarball [in this way](http://www.linuxfromscratch.org/blfs/view/svn/x/webkitgtk.html) on ubuntu20.04 and the Minibrowser works well. But I cannot patch the bootstrap.diff file in playwright/browser_patches/webkit/patches to build a Minibrowser that can work with playright. Would you mind telling me the way to apply your patch and build the patched webkitgtk on ubuntu ?

**Comment by yury-s** [comment]
You can find instructions [here](https://github.com/microsoft/playwright/tree/master/browser_patches), the patch is applied by  [`prepare_checkout.sh`](https://github.com/microsoft/playwright/tree/master/browser_patches) script. Also for build steps you can look at our build bot configs, for webkit docs https://trac.webkit.org/wiki/BuildingGtk and https://trac.webkit.org/wiki/WPE would be better sources.

**Comment by zyscoder** [comment]
> You can find instructions [here](https://github.com/microsoft/playwright/tree/master/browser_patches), the patch is applied by [`prepare_checkout.sh`](https://github.com/microsoft/playwright/tree/master/browser_patches) script. Also for build steps you can look at our build bot configs, for webkit docs https://trac.webkit.org/wiki/BuildingGtk and https://trac.webkit.org/wiki/WPE would be better sources.

Thank you very much. I would have a try.

**Comment by zyscoder** [comment]
I followed the instructions to checkout and build the patched WebKit, but something wrong happened.
First, an executables seems build failed:
~~~
[8/8] Linking CXX executable bin/WebKitTestRunner
FAILED: bin/WebKitTestRunner 
: && /usr/bin/c++ -fdiagnostics-color=always -Wextra -Wall -Wno-expansion-to-defined -Wno-noexcept-type -Wno-psabi -Wno-misleading-indentation -Wno-maybe-uninitialized -Wwrite-strings -Wundef -Wpointer-arith -Wmissing-format-attribute -Wformat-security -Wcast-align -Wno-tautological-compare  -fno-strict-aliasing -fno-exceptions -fno-rtti -O3 -DNDEBUG -fuse-ld=gold -Wl,--disable-new-dtags Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/CyclicRedundancyCheck.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/GeolocationProviderMock.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/Options.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/PixelDumpSupport.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/TestController.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/TestInvocation.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/TestOptions.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/UIScriptControllerCommon.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/WebNotificationProvider.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/WorkQueueManager.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/cairo/TestInvocationCairo.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/gtk/EventSenderProxyGtk.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/gtk/PlatformWebViewGtk.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/gtk/TestControllerGtk.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/gtk/UIScriptControllerGtk.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/gtk/main.cpp.o -o bin/WebKitTestRunner  -Wl,-rpath,/app/webkit/WebKitBuild/Release/lib  lib/libTestRunnerShared.a  lib/libWebCoreTestSupport.a  /usr/lib/x86_64-linux-gnu/libatk-1.0.so  /usr/lib/x86_64-linux-gnu/libglib-2.0.so  /usr/lib/x86_64-linux-gnu/libcairo.so  -lstdc++fs  lib/libWebCoreTestSupport.a  lib/libwebkit2gtk-4.0.so.37.50.0  lib/libWebCoreGTK.a  /usr/lib/x86_64-linux-gnu/libcairo.so  lib/libPAL.a  lib/libjavascriptcoregtk-4.0.so.18.18.0  lib/libWTFGTK.a  lib/libbmalloc.a  /usr/lib/x86_64-linux-gnu/libicudata.so  /usr/lib/x86_64-linux-gnu/libicui18n.so  /usr/lib/x86_64-linux-gnu/libicuuc.so  -lpthread  /usr/lib/x86_64-linux-gnu/libsystemd.so  lib/libANGLE.a  -ldl  /usr/lib/x86_64-linux-gnu/libxml2.so  /usr/lib/x86_64-linux-gnu/libsqlite3.so  /usr/lib/x86_64-linux-gnu/libxslt.so  /usr/lib/x86_64-linux-gnu/libGL.so  /usr/lib/x86_64-linux-gnu/libEGL.so  /usr/lib/x86_64-linux-gnu/libwoff2dec.so  lib/libxdgmime.a  lib/libwebrtc.a  /usr/lib/x86_64-linux-gnu/libvpx.so  /usr/lib/x86_64-linux-gnu/libevent.so  /usr/lib/x86_64-linux-gnu/libopus.so  /usr/lib/x86_64-linux-gnu/libfontconfig.so  /usr/lib/x86_64-linux-gnu/libfreetype.so  /usr/lib/x86_64-linux-gnu/libharfbuzz.so  /usr/lib/x86_64-linux-gnu/libharfbuzz-icu.so  /usr/lib/x86_64-linux-gnu/libgcrypt.so  /usr/lib/x86_64-linux-gnu/libgstapp-1.0.so  /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so  /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so  /usr/lib/x86_64-linux-gnu/libgstpbutils-1.0.so  /usr/lib/x86_64-linux-gnu/libgstaudio-1.0.so  /usr/lib/x86_64-linux-gnu/libgsttag-1.0.so  /usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so  /usr/lib/x86_64-linux-gnu/libgstgl-1.0.so  /usr/lib/x86_64-linux-gnu/libgstcodecparsers-1.0.so  /usr/lib/x86_64-linux-gnu/libgstfft-1.0.so  /usr/lib/x86_64-linux-gnu/libgcrypt.so  /usr/lib/x86_64-linux-gnu/libgstapp-1.0.so  /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so  /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so  /usr/lib/x86_64-linux-gnu/libgstpbutils-1.0.so  /usr/lib/x86_64-linux-gnu/libgstaudio-1.0.so  /usr/lib/x86_64-linux-gnu/libgsttag-1.0.so  /usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so  /usr/lib/x86_64-linux-gnu/libgstgl-1.0.so  /usr/lib/x86_64-linux-gnu/libgstcodecparsers-1.0.so  /usr/lib/x86_64-linux-gnu/libgstfft-1.0.so  -lgpg-error  /usr/lib/x86_64-linux-gnu/libjpeg.so  /usr/lib/x86_64-linux-gnu/libpng.so  /usr/lib/x86_64-linux-gnu/libz.so  /usr/lib/x86_64-linux-gnu/libopenjp2.so  /usr/lib/x86_64-linux-gnu/libwebpdemux.so  /usr/lib/x86_64-linux-gnu/libwebp.so  /usr/lib/x86_64-linux-gnu/libsoup-2.4.so  /usr/lib/x86_64-linux-gnu/libenchant-2.so  /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so  -lsecret-1  -lgio-2.0  -lgobject-2.0  -lglib-2.0  /usr/lib/x86_64-linux-gnu/libtasn1.so  /usr/lib/x86_64-linux-gnu/libhyphen.so  /usr/lib/x86_64-linux-gnu/libX11.so  /usr/lib/x86_64-linux-gnu/libXcomposite.so  /usr/lib/x86_64-linux-gnu/libXdamage.so  /usr/lib/x86_64-linux-gnu/libXrender.so  /usr/lib/x86_64-linux-gnu/libXt.so  /usr/lib/x86_64-linux-gnu/libwpe-1.0.so  -lwayland-server  -lwayland-egl  -lwayland-client  /usr/lib/x86_64-linux-gnu/libWPEBackend-fdo-1.0.so  /usr/lib/x86_64-linux-gnu/libgtk-3.so  /usr/lib/x86_64-linux-gnu/libgdk-3.so  /usr/lib/x86_64-linux-gnu/libz.so  /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so  /usr/lib/x86_64-linux-gnu/libpango-1.0.so  /usr/lib/x86_64-linux-gnu/libharfbuzz.so  /usr/lib/x86_64-linux-gnu/libatk-1.0.so  /usr/lib/x86_64-linux-gnu/libcairo-gobject.so  /usr/lib/x86_64-linux-gnu/libcairo.so  /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so  /usr/lib/x86_64-linux-gnu/libgio-2.0.so  /usr/lib/x86_64-linux-gnu/libgobject-2.0.so  /usr/lib/x86_64-linux-gnu/libglib-2.0.so && :
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld.gold: error: cannot find -lstdc++fs
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
~~~
Besides, when I tried to directly run the MiniBrowser with the script "Tools/Scripts/run-minibrowser --gtk", an error occured:
~~~
» Tools/Scripts/run-minibrowser --gtk                            
Gtk-Message: 09:21:34.032: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:21:34.033: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:21:34.501: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:21:34.502: Failed to load module "canberra-gtk-module"
~~~

For the second problem, I tried to "sudo apt install libcanberra-gtk-module libcanberra-gtk3-module", but it does not work. If I used wrong command to build or run the Minibrowser?

**Comment by zyscoder** [comment]
> I followed the instructions to checkout and build the patched WebKit, but something wrong happened.
> First, an executable seems build failed:
> 
> ```
> [8/8] Linking CXX executable bin/WebKitTestRunner
> FAILED: bin/WebKitTestRunner 
> : && /usr/bin/c++ -fdiagnostics-color=always -Wextra -Wall -Wno-expansion-to-defined -Wno-noexcept-type -Wno-psabi -Wno-misleading-indentation -Wno-maybe-uninitialized -Wwrite-strings -Wundef -Wpointer-arith -Wmissing-format-attribute -Wformat-security -Wcast-align -Wno-tautological-compare  -fno-strict-aliasing -fno-exceptions -fno-rtti -O3 -DNDEBUG -fuse-ld=gold -Wl,--disable-new-dtags Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/CyclicRedundancyCheck.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/GeolocationProviderMock.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/Options.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/PixelDumpSupport.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/TestController.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/TestInvocation.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/TestOptions.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/UIScriptControllerCommon.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/WebNotificationProvider.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/WorkQueueManager.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/cairo/TestInvocationCairo.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/gtk/EventSenderProxyGtk.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/gtk/PlatformWebViewGtk.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/gtk/TestControllerGtk.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/gtk/UIScriptControllerGtk.cpp.o Tools/WebKitTestRunner/CMakeFiles/WebKitTestRunner.dir/gtk/main.cpp.o -o bin/WebKitTestRunner  -Wl,-rpath,/app/webkit/WebKitBuild/Release/lib  lib/libTestRunnerShared.a  lib/libWebCoreTestSupport.a  /usr/lib/x86_64-linux-gnu/libatk-1.0.so  /usr/lib/x86_64-linux-gnu/libglib-2.0.so  /usr/lib/x86_64-linux-gnu/libcairo.so  -lstdc++fs  lib/libWebCoreTestSupport.a  lib/libwebkit2gtk-4.0.so.37.50.0  lib/libWebCoreGTK.a  /usr/lib/x86_64-linux-gnu/libcairo.so  lib/libPAL.a  lib/libjavascriptcoregtk-4.0.so.18.18.0  lib/libWTFGTK.a  lib/libbmalloc.a  /usr/lib/x86_64-linux-gnu/libicudata.so  /usr/lib/x86_64-linux-gnu/libicui18n.so  /usr/lib/x86_64-linux-gnu/libicuuc.so  -lpthread  /usr/lib/x86_64-linux-gnu/libsystemd.so  lib/libANGLE.a  -ldl  /usr/lib/x86_64-linux-gnu/libxml2.so  /usr/lib/x86_64-linux-gnu/libsqlite3.so  /usr/lib/x86_64-linux-gnu/libxslt.so  /usr/lib/x86_64-linux-gnu/libGL.so  /usr/lib/x86_64-linux-gnu/libEGL.so  /usr/lib/x86_64-linux-gnu/libwoff2dec.so  lib/libxdgmime.a  lib/libwebrtc.a  /usr/lib/x86_64-linux-gnu/libvpx.so  /usr/lib/x86_64-linux-gnu/libevent.so  /usr/lib/x86_64-linux-gnu/libopus.so  /usr/lib/x86_64-linux-gnu/libfontconfig.so  /usr/lib/x86_64-linux-gnu/libfreetype.so  /usr/lib/x86_64-linux-gnu/libharfbuzz.so  /usr/lib/x86_64-linux-gnu/libharfbuzz-icu.so  /usr/lib/x86_64-linux-gnu/libgcrypt.so  /usr/lib/x86_64-linux-gnu/libgstapp-1.0.so  /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so  /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so  /usr/lib/x86_64-linux-gnu/libgstpbutils-1.0.so  /usr/lib/x86_64-linux-gnu/libgstaudio-1.0.so  /usr/lib/x86_64-linux-gnu/libgsttag-1.0.so  /usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so  /usr/lib/x86_64-linux-gnu/libgstgl-1.0.so  /usr/lib/x86_64-linux-gnu/libgstcodecparsers-1.0.so  /usr/lib/x86_64-linux-gnu/libgstfft-1.0.so  /usr/lib/x86_64-linux-gnu/libgcrypt.so  /usr/lib/x86_64-linux-gnu/libgstapp-1.0.so  /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so  /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so  /usr/lib/x86_64-linux-gnu/libgstpbutils-1.0.so  /usr/lib/x86_64-linux-gnu/libgstaudio-1.0.so  /usr/lib/x86_64-linux-gnu/libgsttag-1.0.so  /usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so  /usr/lib/x86_64-linux-gnu/libgstgl-1.0.so  /usr/lib/x86_64-linux-gnu/libgstcodecparsers-1.0.so  /usr/lib/x86_64-linux-gnu/libgstfft-1.0.so  -lgpg-error  /usr/lib/x86_64-linux-gnu/libjpeg.so  /usr/lib/x86_64-linux-gnu/libpng.so  /usr/lib/x86_64-linux-gnu/libz.so  /usr/lib/x86_64-linux-gnu/libopenjp2.so  /usr/lib/x86_64-linux-gnu/libwebpdemux.so  /usr/lib/x86_64-linux-gnu/libwebp.so  /usr/lib/x86_64-linux-gnu/libsoup-2.4.so  /usr/lib/x86_64-linux-gnu/libenchant-2.so  /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so  -lsecret-1  -lgio-2.0  -lgobject-2.0  -lglib-2.0  /usr/lib/x86_64-linux-gnu/libtasn1.so  /usr/lib/x86_64-linux-gnu/libhyphen.so  /usr/lib/x86_64-linux-gnu/libX11.so  /usr/lib/x86_64-linux-gnu/libXcomposite.so  /usr/lib/x86_64-linux-gnu/libXdamage.so  /usr/lib/x86_64-linux-gnu/libXrender.so  /usr/lib/x86_64-linux-gnu/libXt.so  /usr/lib/x86_64-linux-gnu/libwpe-1.0.so  -lwayland-server  -lwayland-egl  -lwayland-client  /usr/lib/x86_64-linux-gnu/libWPEBackend-fdo-1.0.so  /usr/lib/x86_64-linux-gnu/libgtk-3.so  /usr/lib/x86_64-linux-gnu/libgdk-3.so  /usr/lib/x86_64-linux-gnu/libz.so  /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so  /usr/lib/x86_64-linux-gnu/libpango-1.0.so  /usr/lib/x86_64-linux-gnu/libharfbuzz.so  /usr/lib/x86_64-linux-gnu/libatk-1.0.so  /usr/lib/x86_64-linux-gnu/libcairo-gobject.so  /usr/lib/x86_64-linux-gnu/libcairo.so  /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so  /usr/lib/x86_64-linux-gnu/libgio-2.0.so  /usr/lib/x86_64-linux-gnu/libgobject-2.0.so  /usr/lib/x86_64-linux-gnu/libglib-2.0.so && :
> /usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld.gold: error: cannot find -lstdc++fs
> collect2: error: ld returned 1 exit status
> ninja: build stopped: subcommand failed.
> ```
> 
> Besides, when I tried to directly run the MiniBrowser with the script "Tools/Scripts/run-minibrowser --gtk", an error occured:
> 
> ```
> » Tools/Scripts/run-minibrowser --gtk                            
> Gtk-Message: 09:21:34.032: Failed to load module "canberra-gtk-module"
> Gtk-Message: 09:21:34.033: Failed to load module "canberra-gtk-module"
> Gtk-Message: 09:21:34.501: Failed to load module "canberra-gtk-module"
> Gtk-Message: 09:21:34.502: Failed to load module "canberra-gtk-module"
> ```
> 
> For the second problem, I tried to "sudo apt install libcanberra-gtk-module libcanberra-gtk3-module", but it does not work. If I used wrong command to build or run the Minibrowser?

My gcc version is 9.3 and it seems that there is no need to use the flag anymore. After I remove the flag, the building process can work well. 
I still stuck in the second problem: "Gtk-Message: 09:21:34.032: Failed to load module "canberra-gtk-module". Any advice for me?

**Comment by yury-s** [comment]
Note that we build using clang which might explain why the linker flag is not recognized. As for the launch problem we usually use [pw_run.sh](https://github.com/microsoft/playwright/blob/master/browser_patches/webkit/pw_run.sh) which properly sets up library paths for the browser. For using `run-minibrowser` look at the WebKit documentation, it might assume by default that you've built the browser in flatpak environment.

**Comment by zyscoder** [comment]
I tried to use the build.sh to build webkit, but an error occurs:
~~~
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GSTREAMER_CODECPARSERS_LIBRARIES (ADVANCED)
    linked by target "WebCore" in directory /path/to/playwright/browser_patches/webkit/checkout/Source/WebCore
    linked by target "WebCoreTestSupport" in directory /path/to/playwright/browser_patches/webkit/checkout/Source/WebCore
~~~

**Comment by zyscoder** [comment]
After handling amounts of dependencies, I  used the build.sh and built the patched WebKit successfully, but when I use pw_run.sh to set up the browser, it exits immediately. 
As a comparison,  I tried to build firefox with "./browser_patches/firefox/build.sh" and set up firefox with "./browser_patches/firefox/checkout/mach run" and it works normally. Why the WebKit exits immediately?

**Comment by yury-s** [comment]
The WebKit browser may be crashing due to a missing dependency again or there may be some other problem. It is hard to help without knowing the details of how you set up your dev environment and what the error is (look at the process output, it usually contains enough information to guess why it aborted). These [tips](https://github.com/microsoft/playwright/blob/master/browser_patches/webkit/cheatsheet.md) may be useful for debugging the problem.
