### ISSUE TITLE
[Question] how to run v1.6.2 with non default version of chromium

### ISSUE THREAD

**Issue by 40x** [microsoft/playwright#4567]
I have v1.6.2 installed locally and I have downloaded the chromium binary 827993.

When I try to run my test script it always tries to pick chromium-827102 which is the default and fails. Any way I can specify a non default different version? 

TIA

![image](https://user-images.githubusercontent.com/10065828/100802506-35ef2f00-33ef-11eb-9b2d-3bdce94f15af.png)

**Comment by yury-s** [comment]
You can pass custom [`executablePath`](https://playwright.dev/#version=v1.6.2&path=docs%2Fapi.md&q=browsertypelaunchoptions--options-executablepath) as an option to `browserType.launch()`.

**Comment by 40x** [comment]
Seems to be getting access issue - any suggestions on what the right permissions are?

```browserType.launch: Failed to launch browser: Error: spawn /Users/kashyap.mukkamala/git/snc/playwrite/playwright/browsers/default EACCES```

**Comment by 40x** [comment]
![image](https://user-images.githubusercontent.com/10065828/100810330-e06e4e80-33fd-11eb-9b6d-cfe967c554c0.png)

**Comment by yury-s** [comment]
Can you check if you can launch the browser from the specified location manually (without playwright)?

> /Users/kashyap.mukkamala/git/snc/playwrite/playwright/browsers/default EACCES
> current permissions are - -rwxr-xr-x 1 kashyap.mukkamala staff 602256 Dec 1 15:25 Chromium

You mentioned at least 3 different directories in your comments (default, other, Chromium), make sure that you check permissions on the same path as you pass to playwright. If you can launch the browser from terminal playwright should also be able to launch it.
