### ISSUE TITLE
[Question] Make custom firefox builds

### ISSUE THREAD

**Issue by 40x** [microsoft/playwright#4568]
If I need to work with the latest Firefox (or webkit) nightly (bundle 8520 in case of Firefox) do I need to change anything on the nightly for it to work with playwright? I saw the info.plist of the latest version of Firefox that ships with playwright and looks like is modified in some way?

```
  <key>MozillaDeveloperRepoPath</key>
  <string>/Users/aslushnikov/prog/cron/playwright/browser_patches/firefox/checkout</string>
  <key>MozillaDeveloperObjPath</key>
  <string>/Users/aslushnikov/prog/cron/playwright/browser_patches/firefox/checkout/obj-build-playwright</string>
```

Any suggestions would be helpful

**Comment by 40x** [comment]
I am trying to follow the docs here - https://github.com/microsoft/playwright/tree/v1.6.2/browser_patches not sure if this is the right way to do it for an external developer?

**Comment by pavelfeldman** [comment]
Could you share you use case for Playwright?

**Comment by 40x** [comment]
we are trying to run tests on an array of browsers (think last 3-5 versions of each Chromium, Firefox, and webkit). I was able to download the Chromium binaries and test with that (apart from the ones which come by default when we install Playwright) and it works, but it keeps failing for Firefox with the error `browserType.launch: Protocol error (Browser.enable): Target closed.` and when I investigate I found that both Firefox and WebKit have their own patches. I am trying to figure out how I can apply those and create my own binaries which would be compatible with pw

**Comment by 40x** [comment]
Here is my sample script - 

```
const playwright = require("playwright");
const executablePath = process.env.PLAYWRIGHT_BROWSERS_PATH;

const browsers = [
	{
		type: "chromium",
		version: 827102,
		executablePath:
			"playwright/browsers/chromium-827102/chrome-mac/Chromium.app/Contents/MacOS/Chromium",
	},
	{
		type: "chromium",
		version: 827993,
		executablePath:
			"playwright/browsers/chromium-827993/chrome-mac/Chromium.app/Contents/MacOS/Chromium",
	},
	{
		type: "firefox",
		version: 1205,
		executablePath:
			"playwright/browsers/firefox-1205/firefox/Nightly.app/Contents/MacOS/firefox",
	},
	{
		type: "firefox",
		version: 85,
		executablePath:
			"playwright/browsers/firefox-85/Firefox Nightly.app/Contents/MacOS/firefox",
	},
	{
		type: "firefox",
		version: 86,
		executablePath:
			"playwright/browsers/firefox-86/Firefox.app/Contents/MacOS/firefox",
	},
	{
		type: "webkit",
		version: 1383,
		executablePath: "playwright/browsers/webkit-1383/pw_run.sh",
	},
];

(async () => {
	for (const b of browsers) {
		console.info("===== Running", b.type, b.version, "======");
		let browser = null;
		try {
			browser = await playwright[b.type].launch({
				executablePath: b.executablePath,
				headless: b.type !== "firefox",
			});
		} catch (err) {
			console.error(err);
		}
		if (!browser) return;
		const context = await browser.newContext();
		const page = await context.newPage();
		await page.goto("http://localhost:8081");
		await page.waitForLoadState("domcontentloaded");
		await page.screenshot({
			path: `output/example-${b.type}-${b.version}.png`,
		});
		await browser.close();
	}
})();

```

**Comment by yury-s** [comment]
Both WebKit and Firefox require patches to provide remote debugging protocol required by Playwright, without that you won't be able to control those browsers from Playwright. The docs you referred to describe the way we apply the patches, so it should work for you as well. To build the browsers you'll need to setup dev environment following corresponding WebKit and Firefox documentation on their sites. Our [buildbot docs](https://github.com/microsoft/playwright/tree/v1.6.2/browser_patches/buildbots) may be useful too.

**Comment by 40x** [comment]
Thank you, I will take a look. I did run it locally to apply the patches on Firefox, but I couldnt tell which version it was applying them to.

**Comment by pavelfeldman** [comment]
> we are trying to run tests on an array of browsers (think last 3-5 versions of each Chromium, Firefox, and webkit).

I wouldn't recommend building browsers, it is a tedious process. You could instead use last few versions of Playwright. Playwright uses nightly versions of the browsers. For example, v1.6 is using the browsers that are ~4 weeks old now, but when v1.7. releases, they are new again. If you'd like to test against 3 versions of each, you can test against 3-5 versions of Playwright itself. It'll be using respective older browsers.
