### ISSUE TITLE
[BUG] MiniBrowser stays in memory even after it's window is manually closed

### ISSUE THREAD

**Issue by cbxp** [microsoft/playwright#4569]
**Context:**
- Playwright Version: 1.6.2
- Operating System: Linux
- Node.js version: 14
- Browser: WebKit

**Describe the bug**

If you don't call `await browser.close()` at the end of the test (in order to inspect what happened), then the browser stays running after tests quit. However, manually closing the browser window still leaves some processes running in the system. They seem never to terminate on their own and leak memory.

Workaround: call `killall MiniBrowser` periodically.

**Comment by pavelfeldman** [comment]
Do you use any test harness? How does the test end, do you do process.exit?

**Comment by angryziber** [comment]
@pavelfeldman yes, the test process is terminated (using `jest --forceExit`), and browser window stays for examination.

My expectation is still that the browser should be unloaded from memory (terminated) when user closes the browser window manually.
The same way as any normal GUI software.

**Comment by pavelfeldman** [comment]
I see. It looks like jest forced exit w/o giving Playwright a chance to shut down the browsers. We have a fix for that in the works that should be available in v1.7 (~ 10 days from now).

**Comment by dgozman** [comment]
Fixed by #4494.
