### ISSUE TITLE
[Question] Running all browsers in a docker don´t work fine

### ISSUE THREAD

**Issue by DiegoFBenavides** [microsoft/playwright#4570]
Hi guys! I´m new here. I´m starting using playwright and I have a little script to check a web in different browsers, it run in local but when I try to launch in a docker (Playwright by microsoft) firefox & webkit don´t work fine. It seem that not even open the browser  

● SmokeTest firefox › prestashop should be loaded in firefox

    Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:27:45)

I forget tell you that I´m using jest like framework.

Can someone help me? Thanks in advance.

**Comment by pavelfeldman** [comment]
Try bumping up your timeout? Not sure what jest is unhappy about, but Firefox takes longer to start than the others...

**Comment by DiegoFBenavides** [comment]
oh men! that´s the solution for mi test. Lot of thanks

**Comment by pavelfeldman** [comment]
Also check out https://github.com/microsoft/playwright-test, it solves this and other problems if you are not yet bound to jest.
