### ISSUE TITLE
[BUG] playwright-electron fails to close down after a screenshot is taken

### ISSUE THREAD

**Issue by cserby** [microsoft/playwright#4571]
**Context:**
- Playwright Version: playwright-electron "0.5.0"
- Operating System: Linux
- Node.js version: v10.16.0
- Browser: Electron
- Extra: used with cucumber-js 7.0

**Code Snippet**

I have an After hook:

```
After(function () {
    const world: World = (this as World);
    return world.stopApp();
});

```
where `world.stopApp()` is a `Promise<void>`, and this works as expected: after everything is done, app gets closed, node exits.

Now, if I change it to:
```
After(function (testCase) {
  const world: World = this as World;
  return Promise.resolve()
    .then(() => {
      if (testCase.result && testCase.result.status !== Status.PASSED) {
        return world.getMainWindow().then(
          window =>
            window!
              .screenshot({
                type: 'png',
                fullPage: true,
              })
              .then(screenshot => world.attach(screenshot, 'image/png'))
        );
      } else { return Promise.resolve(); }
    })
    .then(() => world.stopApp());
});
```
, then the screenshot gets taken, the app gets closed, but nevertheless, the node process stays hanging when done,  and then after a certain time it exits with:

```
0m03.194s (executing steps: 0m03.184s)
/home/cserby/src/node_modules/playwright-electron/lib/client/connection.js:138
            throw new Error(`Cannot find parent object ${parentGuid} to create ${guid}`);
            ^
Error: Cannot find parent object ElectronApplication@063e69bc2fb5f6904e9734e426ad2eb7 to create JSHandle@37d05e59586959bd4828bc50e5d5edff
    at Connection._createRemoteObject (/home/cserby/src/node_modules/playwright-electron/lib/client/connection.js:138:19)
    at Connection.dispatch (/home/cserby/src/node_modules/playwright-electron/lib/client/connection.js:105:18)
    at Immediate.setImmediate (/home/cserby/src/node_modules/playwright-electron/lib/inprocess.js:42:85)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

It's like in this case, playwright would fail to close down correctly.

**Comment by pavelfeldman** [comment]
It looks like unhandled promise rejection takes place as a part of the failing test (which is a valid situation, things break in the failing tests) and your test harness does not do proper handling and teardown?

**Comment by cserby** [comment]
Hi Pavel,

Thanks for the quick triage.
Indeed, I suspect a promise rejection too. However, I run the exact same test case (which is in fact failing) with only the After hook differing when I experience this behavior. This makes me think, that the promise rejection (or a leftover `.setTimeout()` maybe?) might occur somewhere around the `.screenshot()` call in `playwright-electron`.

Also, I noticed that the version for `playwright-electron` is very far behind that of `playwright`. Would it make sense to make a rebase and a new release of it?

Thanks,
Marton

**Comment by pavelfeldman** [comment]
I think you are a spot on, something goes wrong and it can't capture a screenshot. This is still something that should be taken care of by the harness. Unfortunately w/o the code snippet in hand it is somewhat hard to diagnose.

> Also, I noticed that the version for playwright-electron is very far behind that of playwright. Would it make sense to make a rebase and a new release of it?

0.5.0 corresponds to Playwright 1.5, so it is fairly recent. The reason major == 0 is that playwright-electron is not officially stable yet, we are still collecting the feedback from the users before we freeze the API and call it semver stable. Then its version train will match the one for Playwright.

**Comment by cserby** [comment]
I'll try to come up with a minimal repro project.

**Comment by cserby** [comment]
Trying to come up with a minimal repro project led me to the unhandled promise rejection in my own code. Please feel free to close this issue.
