### ISSUE TITLE
[BUG] https://playwright.dev/ website does not render in Firefox Private Window

### ISSUE THREAD

**Issue by snerks** [microsoft/playwright#4574]
**Context:**
- Playwright Version: N/A
- Operating System: Windows 10 Home
- Node.js version: N/A
- Browser: Firefox
- Extra: Firefox Private Windows

**Describe the bug**

In a Firefox Private Window, navigate to:
https://playwright.dev/

**Expected Result**
Page renders

**Actual Result**
Page does not render

**Console output in Developer Tools**
Uncaught (in promise) ReferenceError: data is not defined
    set https://playwright.dev/main.js:19
    create https://playwright.dev/main.js:19

**Comment by mxschmitt** [comment]
I can repro.
