### ISSUE TITLE
[Feature] Support for "forced-colors: active" media query

### ISSUE THREAD

**Issue by Westbrook** [microsoft/playwright#4591]
I use Playwright as a runner for visual regression testing in my project. My team and I are beginning to add Window High Contrast Mode support to our UI via color application in the `forced-colors: active` media query. Could support for this be added to the `emulateMedia` options object?

It would be great if it were so simple as:

```
await page.emulateMedia({ forcedColors: 'active' });
await page.evaluate(() => matchMedia('(forced-colors: active)').matches);
```

Accessibility is important to every web product, so I could see this being of benefit to all users of Playwright.

**Comment by misterbrownlee** [comment]
+1

**Comment by Westbrook** [comment]
@aslushnikov what sort of feedback would you like to receive on this issue in order for it to move forward? I'd be happy to spread out to a broader group in search of that if there was a specific shape you were interested in receiving.

While WHCM is a somewhat niche setting, proper web support for users of various ability is quite important to any and all products that might leverage Playwright in their automated workflow. People who leverage Mac or Linux for their development environments often don't even know this is a context that they need to be prepared to support, so merely its presence in Playwright could go a long way towards educating the community on the many and diverse concepts that go into developing an accessible web property. Being able to leverage Playwright x-browser/platform as a visual regression driver for this would be an amazing addition to the web community.

Would it be possible to hear where the team stood on the feasibility of this?

**Comment by aslushnikov** [comment]
> what sort of feedback would you like to receive on this issue in order for it to move forward?

@Westbrook No feedback needed, just collecting for upvotes

**Comment by mxschmitt** [comment]
Tracking comment:

- Chromium: Upstream patch will follow
- Firefox: #6902
- WebKit: blocked by upstream: https://bugs.webkit.org/show_bug.cgi?id=225281
- Base PR: #6903
