### ISSUE TITLE
Multiple screens in mobile screenshot.

### ISSUE THREAD

**Issue by Pooort** [microsoft/playwright#4613]
**Context:**
- Playwright Version:1.5.2

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    Memory: 6.27 GB / 17.59 GB
    Container: Yes
  Binaries:
    Node: 14.15.1 - /usr/bin/node
    npm: 6.14.9 - /usr/local/bin/npm

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
    const pixel2 = devices['Pixel 2'];

    const context = await chromium.launchPersistentContext(
        account.profilePath, {
          ...pixel2,
          headless: config.headless,
          ignoreHTTPSErrors: true,
          proxy: isNoProxy ? undefined : {server: account.proxy},
        },
    );
....
   await this.page.screenshot({path: filePath});
```

**Describe the bug**

The screenshot contains 6 screens. Looks like:

![1](https://user-images.githubusercontent.com/10560550/101285087-7508f000-37f4-11eb-9fad-e2f579a69263.png)

**Comment by aslushnikov** [comment]
@Poort I tried running the following script and ended up with a normal screenshot:

```js
const pw = require('playwright');

(async () => {
  const pixel2 = pw.devices['Pixel 2'];
  const context = await pw.chromium.launchPersistentContext('./ctx', {
    ...pixel2,
    headless: false,
    ignoreHTTPSErrors: true,
  });
  const page = await context.newPage();
  await page.goto('https://example.com');
  await page.screenshot({
    path: './example.png',
  });
  await context.close();
})();
```

Can you please share a script that we can run locally and reproduce the problem?

**Comment by aslushnikov** [comment]
Closing as part of triaging. Please re-file to bring back our attention if necessary.
