### ISSUE TITLE
[Question] stderr sink logger

### ISSUE THREAD

**Issue by yuli4nm** [microsoft/playwright#4615]
Hello friends!

I'm a bit stuck on a task, I don't understand how to do it. I am developing unit tests for new features (w3c). My browsers are on DEBUG. Because it is necessary to check a test is correct and does not generate browser errors between various platforms. Due to which I need to check if stderr contains a substring ASSERT. 
So far I've fs.createWriteStream to log all stdout, stderr to a file (nasty), and I have to go one by one log files with a grep cron task..  Further sometimes there are dynamic generated tests. So I want to keep reponse.body() if ASSERT appears in a request (without performing two requests to same url because it will be a different result every time, dynamic css or elements) to save it as a new test case for the testsuite. 

I've tried to modify the logger API with indexOf("ASSERT") within but no luck.
```js
//without this there is no [err] output
process.env.DEBUG = 'pw:browser*';
...
     logger: {
        isEnabled: (name, severity) => name === 'browser',
        log: (name, severity, message, args) => console.log(`${name} ${severity} ${message}`)

       if (message.indexOf('ASSERT') > 0 ){
       const testcase = await response.body();
       // Debug, it has to be written to a file
       console.log(buffer.toString('utf8'));
      }
...
await page.goto('http://testsuite.local/test1');
await page.close();
await browser.close();
process.exit(0);
...
```
Thank you very much for developing this framework. Any examples are welcome!

**Comment by aslushnikov** [comment]
> I'm a bit stuck on a task, I don't understand how to do it. I am developing unit tests for new features (w3c).

@yuli4nm just to clarify: are you developing tests for [WebPlatformTests](https://github.com/web-platform-tests/wpt)?

> My browsers are on DEBUG. 

Does it mean you have browsers compiled with debug symbols?



I'm overall confused: Playwright ships with its own browsers - do you use `executablePath` to supply your own browser build?

**Comment by yuli4nm** [comment]
> @yuli4nm just to clarify: are you developing tests for [WebPlatformTests](https://github.com/web-platform-tests/wpt)?
> 
Right but some are attached to bugzilla and does not include a testing framework but a testcase.html

> I'm overall confused: Playwright ships with its own browsers - do you use `executablePath` to supply your own browser build?. 

Right, I do build Mozilla Firefox, WebKitGTK and chrome with Debug to catch ASSERT and other crashes or warnings and I have to specify executablePath. Usually work without issues because I use browser_patches to ensure it's same version supported by pw.

**Comment by JoelEinbinder** [comment]
> > I'm overall confused: Playwright ships with its own browsers - do you use `executablePath` to supply your own browser build?.
> 
> Right, I do build Mozilla Firefox, WebKitGTK and chrome with Debug to catch ASSERT and other crashes or warnings and I have to specify executablePath. Usually work without issues because I use browser_patches to ensure it's same version supported by pw.

Impressive!

I would side step the logger sink by launching your own browser server and reading the stderr directly.

```js
const server = await webkit.launchServer({
  executablePath: '...'
});
const stderr = server.process().stderr;
const browser = await webkit.connect({
  wsEndpoint: server.wsEndpoint()
});
```

**Comment by yuli4nm** [comment]
> I would side step the logger sink by launching your own browser server and reading the [stderr](https://nodejs.org/api/child_process.html#child_process_subprocess_stderr) directly.

effectively this works!, thank you. Now I wonder how get response.body(); without a double request. Some tests have dynamic content and two requests are two different response.body(). I've to store it as a new file if stderr.on contains ASSERT string. Can you think of a simple way to do it with my code snippet?

**Comment by JoelEinbinder** [comment]
Stderr comes in out of sync with the rest of your test. You'll have to capture the response body unconditionally while the test is running. Then after you close the browser and read the stderr, you can discard it. Or do I misunderstand the question?

**Comment by yuli4nm** [comment]
> Stderr comes in out of sync with the rest of your test. You'll have to capture the response body unconditionally while the test is running. Then after you close the browser and read the stderr, you can discard it. Or do I misunderstand the question?

stderr snippet works, I've ASSERTs, WARNINGs.

```
       stderr.on('data', (data) => {
         if (data.toString().indexOf(ASSERT') > -1 ){
         require('fs').appendFileSync('playwright.stderr', data);
        }
        });
```
Should:
if ASSERT,WARNING or crash , then store it in playwright.stderr log, but also response.body() to get a sample to triage what printed or crashed browser. But I see no way to get response.body() logged if navigation failed because page crashed (```page.goto: Navigation failed because page crashed!```). I can't request it twice because it will be a different page or if lucky different page with same root cause bug still crashes again the page.

**Comment by JoelEinbinder** [comment]
I see the issue. If the page crashes while navigating, we only have a short time to get the response body before the crashes page cannot communicate.

Ideally you'd want response interception. We'd pause the page after sending you the response, you could store it, and then the page would unpause and the navigation would continue. We don't have that in playwright today. There are protocol methods for it in Chromium, but not the other browsers.

Do you control the web server? You can store the responses there. Or set up a proxy. If your requests are simple you can use node-fetch + page.route to build a quick proxy.

**Comment by yuli4nm** [comment]
>Do you control the web server? You can store the responses there. Or set up a proxy. If your requests are simple you can use node-fetch + page.route to build a quick proxy.



I don't. A proxy may work. Thank you!
