### ISSUE TITLE
[Feature] Toggle on/off javascript for an existing context

### ISSUE THREAD

**Issue by mjgp2** [microsoft/playwright#4616]
It is useful when testing or automating to sometimes disable javascript for certain requests within a context, and then enable javascript for following ones. Currently it does not seem possible in the API, but as I understand it is possible on the DTP:

https://chromedevtools.github.io/devtools-protocol/1-3/Emulation/#method-setScriptExecutionDisabled

Although it does not seem implemented by Firefox, and I am unsure what other workarounds there may be.

**Comment by pavelfeldman** [comment]
What is your use case? Are you simulating a real user?

**Comment by aslushnikov** [comment]
Closing as part of triaging. Please re-file to bring back our attention if necessary.
