### ISSUE TITLE
[Question] Headful context in headless browser server

### ISSUE THREAD

**Issue by eboody** [microsoft/playwright#4653]
Hey guys!

I have a headless browser that I like to run a bunch of my scripts off of. But when I want to write a new script id like it to be headful without having to restart the existing headless browser server or create a new one.

If there is no other option then that's what I'll do, but is it possible to create headful contexts connected to a headless browser?

**Comment by yury-s** [comment]
You cannot mix headful and headless pages in the same browser instance, headless behavior is configured at the browser level when it is being launched and cannot be changed after. So you'd need to launch another browser if you need to switch from headless to headful mode.

**Comment by eboody** [comment]
Thanks @yury-s !!
