### ISSUE TITLE
[Question] WebKit Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by zyscoder** [microsoft/playwright#4663]
I followed the instructions [here](https://github.com/microsoft/playwright/tree/master/browser_patches) and built a patched WebKit on ubuntu20.04 successfully. But when setting up the MiniBrowser by running "Tools/Script/run-minibrowser --gtk", an error occurs, and the browser exits immediately:
~~~
» Tools/Scripts/run-minibrowser --gtk
Gtk-Message: 23:04:24.573: Failed to load module "canberra-gtk-module"
Gtk-Message: 23:04:24.574: Failed to load module "canberra-gtk-module"
Gtk-Message: 23:04:25.012: Failed to load module "canberra-gtk-module"
Gtk-Message: 23:04:25.013: Failed to load module "canberra-gtk-module"
~~~
I tried to reinstall the libcanberra-gtk-module,
~~~
sudo apt-get install libcanberra-gtk-module
~~~
and the library is installed successfully.
~~~
» locate libcanberra-gtk-module.so
/snap/gnome-3-34-1804/36/usr/lib/gtk-3.0/modules/libcanberra-gtk-module.so
/snap/gnome-3-34-1804/60/usr/lib/gtk-3.0/modules/libcanberra-gtk-module.so
/usr/lib/i386-linux-gnu/gtk-2.0/modules/libcanberra-gtk-module.so
/usr/lib/libcanberra-gtk-module.so
/usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libcanberra-gtk-module.so
/usr/lib/x86_64-linux-gnu/gtk-3.0/modules/libcanberra-gtk-module.so
/usr/lib64/libcanberra-gtk-module.so
~~~
I have no idea why the Minibrowser cannot find the dynamic library. If someone can give me some help?

**Comment by yury-s** [comment]
Your library paths are likely misconfigured. Let's keep the discussion in the original issue: https://github.com/microsoft/playwright/issues/4558
