### ISSUE TITLE
[Question] Lighthouse integration in firefox

### ISSUE THREAD

**Issue by 40x** [microsoft/playwright#4669]
I am trying to use PW with firefox and I was wondering if I can connect it with lighthouse as well. This is how the browser is being launched - 

```
browser = await playwright['firefox'].launch({
	executablePath: executablePath,
	args: ["-start-debugger-server=9222 --jsdebugger"],
});

```

when I try to connect lighthouse to that port I see the following error 

![image](https://user-images.githubusercontent.com/10065828/101819892-733c7680-3aeb-11eb-83ce-e20bb3224208.png)

When I run it in non headless mode I can see the remote debugging turned on

![image](https://user-images.githubusercontent.com/10065828/101820083-b8f93f00-3aeb-11eb-985b-290a19b44a82.png)

Any suggestions on what I could do here to get Lighthouse to work with FF ?

**Comment by aslushnikov** [comment]
To the best of my knowledge, I don't think you can connect Lighthouse to Firefox. Sorry!
