### ISSUE TITLE
[REGRESSION]: _videostarted event not fired in 1.6.2 but does in 1.4.0

### ISSUE THREAD

**Issue by chrisjsimpson** [microsoft/playwright#4682]
**Context:**
- GOOD Playwright Version: 1.4.0
- BAD Playwright Version: 1.6.2
- Operating System: Linux 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Extra: https://www.youtube.com/watch?v=DklP4iB5QdY

**Code Snippet**

(using *exact* code from release notes) https://github.com/microsoft/playwright/releases/tag/v1.4.0
```
const fs = require('fs');
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({
    _videosPath: __dirname  //  save videos here.
  });
  const context = await browser.newContext({
    _recordVideos: { width: 1024, height: 768 },  // downscale
  });
  const page = await context.newPage();
  const video = await page.waitForEvent('_videostarted');
  await page.goto('https://github.com/microsoft/playwright');
  // ... perform actions
  await page.close();
  fs.renameSync(await video.path(), 'video.webm');
  await browser.close();
})();
```

**Describe the bug**

The _videostarted event fires in 1.4.0 but does not in 1.6.2 with the same code snippet. 
Attached video shows both happy path and sad path

The exact error message from 1.6.2 is:

```Timeout while waiting for event "_videostarted"```

**Comment by mxschmitt** [comment]
Hi, the API was changed, see here for the new API: https://playwright.dev/#version=v1.6.2&path=docs%2Fapi.md&q=browsernewpageoptions--options-recordvideo

**Comment by chrisjsimpson** [comment]
Thanks @mxschmitt  

It's not clear to me from the api docs where/how to set the filename of the video, or how to set save points.

e.g: Using new api:

It's clear how to set the directory: :+1:  https://playwright.dev/#version=v1.6.2&path=docs%2Fapi.md&q=browsernewpageoptions--options-recordvideo-dir

```
  const page = await context.newPage({
    recordVideo: {
      dir: __dirname, 
      size: { width: 1024, height: 768 }
    }
   });
```

But not how to?

- Set the file name
- Save each stage during a script: 

e.g. in 1.4.0: `fs.renameSync(await video.path(), 'video.webm');` could be used at any stage

**Comment by mxschmitt** [comment]
You can do ` const videoFile = await page.video().path();` would that work for you?

**Comment by chrisjsimpson** [comment]
Appreciate the tip @mxschmitt 


Both the `video()` and `path` property are null in that context for some reason, 

I'm looking for a "save()" method where I can ask Playwright to save the video, and specify the filename. 

What I'm trying to do is: A playwright script which records a video called video.webm, which saves its progress at each assert (working 1.4.0 code below). It is helpful to save the video at different points because otherwise it's not possible to visualise where a test failed (useful for qa).

## Happy path 1.4.0:

```
const fs = require('fs');
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({
    _videosPath: __dirname  //  save videos here.
  });
  const context = await browser.newContext({
    _recordVideos: { width: 1024, height: 768 },  // downscale
  });
  const page = await context.newPage();
  const video = await page.waitForEvent('_videostarted');
  await page.goto('https://github.com/microsoft/playwright');

  // Save video now. We want to save multiple times, because if an assert 
  // failed, we can still visualise how far the test got
  fs.renameSync(await video.path(), 'video.webm');
  assert(1==1);

  // Go to microsoft org page on github
  await page.goto('https://github.com/microsoft');
  assert(1===2); // this will fail, but we have already saved the video.  

  // Save video again. We will never get here (due to assert(1===2), but 
  // the video will still have been saved as the first assert passed.
  fs.renameSync(await video.path(), 'video.webm');
  await page.close();
  await browser.close();
})();
```

## pseudo code 1.6.2 (not working): 

```
const fs = require('fs');
const { chromium } = require('playwright');
const assert = require('assert');


(async () => {
  const browser = await chromium.launch({
  });
  const context = await browser.newContext();

  // Set page to recordVideo
  const page = await context.newPage({
    recordVideo: {
      dir: __dirname,
      size: { width: 1024, height: 768 }
    }
   });

  // Go to playwright homepage
  await page.goto('https://github.com/microsoft/playwright');

  // Save video now. We want to save multiple times, because if an assert 
  // failed, we can still visualise how far the test got

  const videoFile = await page.video().path(); //?? how to save? in old api we can call fs.renameSync(await video.path(), 'video.webm')
  assert(1==1);

  // Go to microsoft org page on github
  await page.goto('https://github.com/microsoft');
  assert(1===2); // this will fail, but we have already saved the video.

  // Save video at this point, overwriting previous with longer video
  videoFile = await page.video().path(); //?? how to save again in old api we can call fs.renameSync(await video.path(), 'video.webm')

  await page.close();
  await browser.close();
})();

````

The 1.6.2 api [notes](https://playwright.dev/#version=v1.6.2&path=docs%2Fapi.md&q=browsernewpageoptions--options-recordvideo) say "Make sure to await page.close for videos to be saved." which sounds like it's no longer possible to save multiple times? It's not clear how to set the filename of the video. 

Thank you for your time sorry I'm not able to see how to achieve this with the new api docs

**Comment by aslushnikov** [comment]
> Both the video() and path property are null in that context for some reason,

@chrisjsimpson the problem is that you provided `recordVideo` argument to `context.newPage()` instead of `browser.newContext()`, so you get `null` there. 

```js
const browser = await chromium.launch();
// Set CONTEXT to recordVideo
const context = await browser.newContext({
  recordVideo: {
    dir: __dirname,
    size: { width: 1024, height: 768 }
  }
});

// Open new page
const page = await context.newPage();
```

**Comment by chrisjsimpson** [comment]
Thanks @aslushnikov :pray: 

I've also since  found the helpful test which you committed to very helpful as example code: 
https://github.com/microsoft/playwright/blob/1c39689dd6e8b163ed77114f7aa40fac0063c38b/packages/installation-tests/screencast.js#L44

I'll update with further example, thank you for your help both.
