### ISSUE TITLE
[Question] Ubuntu 20.04 instructions for browser dependencies

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright#4683]
According to https://github.com/microsoft/playwright/blob/master/docs/troubleshooting.md I need to install these dependencies:

<details>
  <summary>Debian (e.g. Ubuntu) Dependencies</summary>

```
gconf-service
libasound2
libatk1.0-0
libatk-bridge2.0-0
libc6
libcairo2
libcups2
libdbus-1-3
libexpat1
libfontconfig1
libgcc1
libgconf-2-4
libgdk-pixbuf2.0-0
libglib2.0-0
libgtk-3-0
libnspr4
libpango-1.0-0
libpangocairo-1.0-0
libstdc++6
libx11-6
libx11-xcb1
libxcb1
libxcomposite1
libxcursor1
libxdamage1
libxext6
libxfixes3
libxi6
libxrandr2
libxrender1
libxss1
libxtst6
ca-certificates
fonts-liberation
libappindicator1
libnss3
lsb-release
xdg-utils
wget
libgbm1
```

</details>

But the text also says:

>  For dependencies on Ubuntu, please refer to [Dockerfile ](https://github.com/microsoft/playwright/blob/master/docs/docker/Dockerfile.bionic)which is used to run our tests

**Questions**

1. It is slightly confusing that it first says to read the Dockerfile and then also still lists the dependencies for Ubuntu. Maybe only one of them should exist, or the text rephrased to say something like that you can _also_ see the dependencies in the Dockerfile (or similar)?

2. The link to the Dockerfile goes to Ubuntu 18.04 (bionic) whilst there is also one for Ubuntu 20.04 (focal) https://github.com/microsoft/playwright/blob/master/docs/docker/Dockerfile.focal - that the link only points to one confuses users if they are using Ubuntu 20.04. Should a link to both exist on that page, or just a general link to https://github.com/microsoft/playwright/tree/master/docs/docker ?

3. https://github.com/microsoft/playwright/tree/master/docs/docker and the first paragraph starts with:
> Dockerfile.bionic can be used to run Playwright scripts in Docker environments.

I assume it would be good to also mention `focal` here?

4. When I run Playwright in a custom Dockerfile built on Ubuntu 20.04 where I forgot to install many of the dependencies I get:
```
Error: Host system is missing dependencies!

  Install missing packages with:
      sudo apt-get install libnss3\
          libnspr4\
          libatk1.0-0\
          libatk-bridge2.0-0\
          libcups2\
          libdrm2\
          libxkbcommon0\
          libgtk-3-0\
          libpango-1.0-0\
          libcairo2\
          libgdk-pixbuf2.0-0\
          libgbm1\
          libasound2\
          libatspi2.0-0

  Missing libraries we didn't find packages for:
      libx11-xcb.so.1
      libxcomposite.so.1
      libxdamage.so.1
      libxfixes.so.3
      libxrandr.so.2

Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at validateDependenciesLinux
```
Why does it say I am missing libraries that it did not find packages for? How can this be the case if https://github.com/microsoft/playwright/blob/master/docs/docker/Dockerfile.focal works fine?

**Comment by aslushnikov** [comment]
> 1. It is slightly confusing that it first says to read the Dockerfile and then also still lists the dependencies for Ubuntu. Maybe only one of them should exist, or the text rephrased to say something like that you can also see the dependencies in the Dockerfile (or similar)?

@thernstig sorry, this doc was pretty outdated. Today you should be able to get a list of dependencies either from docker file, or it'll be printed on the first launch.

> 2. The link to the Dockerfile goes to Ubuntu 18.04 (bionic) whilst there is also one for Ubuntu 20.04 (focal) https://github.com/microsoft/playwright/blob/master/docs/docker/Dockerfile.focal - that the link only points to one confuses users if they are using Ubuntu 20.04. Should a link to both exist on that page, or just a general link to https://github.com/microsoft/playwright/tree/master/docs/docker ?

Updated the doc with both links - thank you! 👍

> 3. https://github.com/microsoft/playwright/tree/master/docs/docker and the first paragraph starts with:

Fixed.

> 4. When I run Playwright in a custom Dockerfile built on Ubuntu 20.04 where I forgot to install many of the dependencies I get:

This is an interesting one. Is this with Playwright 1.6.2? Can you please share your docker file so that I can debug this behavior?

**Comment by thernstig** [comment]
It is playwright `1.5.1`, would this be fixed in 1.6.2? I can test if you definitely want me to.

**Comment by aslushnikov** [comment]
> It is playwright 1.5.1, would this be fixed in 1.6.2? I can test if you definitely want me to.

We had a bug like this some time ago and I expect it to be fixed. So yes, I'll appreciate if you can test v1.6.2!

**Comment by thernstig** [comment]
I am glad to verify that 1.6.2 works fine. Sorry about the fuzz about that one:

```sh
Error: Host system is missing dependencies!

  Install missing packages with:
      sudo apt-get install libnss3\
          libnspr4\
          libatk1.0-0\
          libatk-bridge2.0-0\
          libcups2\
          libdrm2\
          libxkbcommon0\
          libxcomposite1\
          libxdamage1\
          libxfixes3\
          libxrandr2\
          libgbm1\
          libgtk-3-0\
          libpango-1.0-0\
          libcairo2\
          libgdk-pixbuf2.0-0\
          libasound2\
          libatspi2.0-0


Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at validateDependenciesLinux
```

**Comment by aslushnikov** [comment]
Awesome, thank you. It looks like all action items are addressed - shall we close the issue?

**Comment by thernstig** [comment]
All fixed, closing, thanks.
