### ISSUE TITLE
[BUG] Filechooser seems to fail for me

### ISSUE THREAD

**Issue by fawazahmed0** [microsoft/playwright#4686]
Hi,
I was trying upload few files using playwright, but it seems to fail for me. I assume I might be doing something wrong.

**Details:**
Playwright Version: 1.6.2
Operating System: Windows 7
Node.js version: 12.18.0
Browser: Firefox

**Code:**
```javascript
const {
  firefox
} = require('playwright');
const path = require('path');

// Add youtube email & password
let email = 'xxxxxxx@email.com'
let pass = 'xxxxxxxxxxxx'
let filePath = path.join(__dirname, 'xxxxxxxxxxx.mp4')

async function begin(){
   const browser = await firefox.launch({
        headless: false
      })
     const context = await browser.newContext()
 
    const page = await context.newPage()
    await page.goto('https://www.youtube.com/upload')

    await page.fill('input[type="email"]', email);
    await page.click('text=Next');
    await page.fill('input[type="password"]', pass);
    await page.click('text=Next');
    await page.waitForLoadState();
 await page.on('filechooser', async (fileChooser) => {
     console.log("filechooser called")
      await fileChooser.setFiles(filePath)
  })

  // Button that initiates filechooser event
  await page.click('text=Select files');

}

begin()
```

**Log:**
```
     pw:api <= page.click succeeded +2ms
    filechooser called
      pw:api => elementHandle.setInputFiles started +20ms
      pw:api   navigated to "https://studio.youtube.com/ytscframe" [] +172ms
      pw:api   "domcontentloaded" event fired [] +2ms
      pw:api   "networkidle" event fired [] +498ms
      pw:api <= elementHandle.setInputFiles failed +691ms
     (node:15396) UnhandledPromiseRejectionWarning: Error: elementHandle.setInputFiles: Evaluation failed: NetworkError when attempting to fetch resource.
    
    Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
        at checkException (c:\Users\Nawaz\node_modules\playwright\lib\firefox\ffExecutionContext.js:86:15)
        at FFExecutionContext.evaluateWithArguments (c:\Users\Nawaz\node_modules\playwright\lib\firefox\ffExecutionContext.js:49:9)
        at async evaluateExpression (c:\Users\Nawaz\node_modules\playwright\lib\javascript.js:164:16)
        at async FrameManager.waitForSignalsCreatedBy (c:\Users\Nawaz\node_modules\playwright\lib\frames.js:90:24)
        at async FrameExecutionContext.evaluateInternal (c:\Users\Nawaz\node_modules\playwright\lib\dom.js:36:16)
        at async FFPage.setInputFiles (c:\Users\Nawaz\node_modules\playwright\lib\firefox\ffPage.js:380:9)
        at async c:\Users\Nawaz\node_modules\playwright\lib\dom.js:440:13
        at async FrameManager.waitForSignalsCreatedBy (c:\Users\Nawaz\node_modules\playwright\lib\frames.js:90:24)
        at async ElementHandle._setInputFiles (c:\Users\Nawaz\node_modules\playwright\lib\dom.js:438:9)
        at async c:\Users\Nawaz\node_modules\playwright\lib\dom.js:421:28
      -- ASYNC --
        at ElementHandle.setInputFiles (c:\Users\Nawaz\node_modules\playwright\lib\helper.js:79:23)
        at FileChooser.setFiles (c:\Users\Nawaz\node_modules\playwright\lib\fileChooser.js:35:36)
        at FileChooser.setFiles (c:\Users\Nawaz\node_modules\playwright\lib\helper.js:80:31)
        at Page.<anonymous> (c:\Users\Nawaz\Desktop\playwright\login.js:51:25)
        at Page.emit (events.js:315:20)
        at Page._onFileChooserOpened (c:\Users\Nawaz\node_modules\playwright\lib\page.js:100:14)
    (node:15396) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
    (node:15396) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
      pw:api   "load" event fired [] +9s
```

**Link:**
https://www.youtube.com/upload

**Page Screenshot:**

![-2020-dec-11-003](https://user-images.githubusercontent.com/20347013/101915399-94848c00-3beb-11eb-9d37-88bf6115c83c.jpg)

Thanks

**Comment by mxschmitt** [comment]
Hi, how big is your file which you are uploading?

**Comment by fawazahmed0** [comment]
around 8mb

**Comment by fawazahmed0** [comment]
I tried emulating this in puppeteer using [FileChooser](https://pptr.dev/#?product=Puppeteer&version=v5.5.0&show=api-class-filechooser) and it seems to work fine without any issue, I assume this should be a bug then.

**Comment by viraxslot** [comment]
@fawazahmed0 Hey, could you please share all the code? Files uploading works just fine for me, so maybe there are some problems in browser/page init.

**Comment by fawazahmed0** [comment]
@viraxslot ,hi, I have added the complete code in bug details, you just have to replace the email, password & filePath with appropriate values

**Comment by viraxslot** [comment]
@fawazahmed0 begin() function is async, please use `await begin()` to call it. I suppose it should help.

**Comment by fawazahmed0** [comment]
@viraxslot the await keyword only works inside a async function, my code should work fine because begin is an initial function.

**Comment by viraxslot** [comment]
@fawazahmed0 yeah, you're right, sorry. Well, I have no errors:
![image](https://user-images.githubusercontent.com/20737672/102085563-e1ed3d00-3e27-11eb-8f0a-05dcdc049021.png)

File was uploaded correctly.

**Comment by fawazahmed0** [comment]
Thanks for testing @viraxslot , probably it might be a windows(or windows 7) only issue like [before](https://github.com/microsoft/playwright/issues/3496)

**Comment by aslushnikov** [comment]
@fawazahmed0 I just tried on Win 10 + node 14 and it uploaded just fine.

> I tried uploading in puppeteer using FileChooser and it seems to work fine without any issue, I assume this should be a bug in playwright then.

Can you try using chromium in playwright as well? This might be a firefox-specific issue on Windows 7. Win 7 is not supported any more so I wouldn't be surprised with this.

**Comment by fawazahmed0** [comment]
@aslushnikov Well, chromium doesn't seem to work in windows 7 , see [this](https://github.com/microsoft/playwright/issues/3496)

**Comment by aslushnikov** [comment]
> @aslushnikov Well, chromium doesn't work in windows 7 , see this

@fawazahmed0 Ah! But how did Puppeteer work for you then?

**Comment by fawazahmed0** [comment]
@aslushnikov , Not sure, but it seems to work fine for me.
![-2020-dec-14-006](https://user-images.githubusercontent.com/20347013/102137284-974bdf00-3e80-11eb-9a77-0335046e68f5.jpg)

**Comment by aslushnikov** [comment]
@fawazahmed0 the https://github.com/microsoft/playwright/issues/3496 should be fixed now - so at the very least, Chromium should work fine for this usecase. Could you please verify this?

**Comment by fawazahmed0** [comment]
@aslushnikov yep, file uploading works fine in chromium (v1.7) 

![-2020-dec-16-116](https://user-images.githubusercontent.com/20347013/102320476-5946dc00-3fa2-11eb-87a9-4570b96e805d.jpg)

Thanks

**Comment by ShaneyWaris** [comment]
Sir, @aslushnikov @viraxslot @fawazahmed0 , is there any way to choose a single folder with playwright when clicking on a div/button?
