### ISSUE TITLE
[Feature] Playwright.connect() for remote connection

### ISSUE THREAD

**Issue by yury-s** [microsoft/playwright#4687]
Current API allows to connect to Playwright server remotely by means of `browserType.launchServer()` and `browserType.connect()`. This requires launching local instance of playwright first and then establishing connections to each of the browsers individually. This can be replaced with a single client->server connection when creating Playwright client (e.g. `new Playwright(<websocket address>)`. Among other things this approach doesn't require launching Playwright driver on the client side, so language bindings wouldn't need to bundle it in such cases.

**Comment by pavelfeldman** [comment]
I don't think we have enough data to move further with this one, punting for now.

**Comment by vania-pooh** [comment]
@pavelfeldman at least there should be some way to connect to remote web socket. Otherwise you limit Playwright to local test execution only.

**Comment by pavelfeldman** [comment]
Let me clarify why I closed it. This request was not about ability to connect remotely, this will still be our goal. This bug was about internal design, not requiring the driver internally when connecting remotely from the language ports (Python, Java, etc). Original bug claims:

> This requires launching local instance of playwright first and then establishing connections to each of the browsers individually.

I think this is Ok since during the inner loop, developers run full Playwright anyways

> This can be replaced with a single client->server connection when creating Playwright client (e.g. new Playwright(<websocket address>).

And while it can be done, I think it is a wrong direction from the layering standpoint. We can optimize the language ports significantly if we don't mix those aspects and keep driver and rpc aspects separate.

**Comment by fehmer** [comment]
hi @pavelfeldman , 

>This request was not about ability to connect remotely, this will still be our goal. 

That's good news. Some bugs/feature request got linked to this issue, I guess that's why the closing caused confusion. Is there a issue/feature request we can use instead to keep track of this in the linked issues?

**Comment by kumaraditya303** [comment]
Another use case would be to run Playwright browser instances on a remote server and run the clients as light weight docker container e.g. alpine linux to run the tests without using driver locally.

**Comment by pavelfeldman** [comment]
It looks like the industry has settled on the browserType.connect. Please file a new issue if you are still interested in this functionality.

**Comment by sridharreddysuram123** [comment]
> @pavelfeldman at least there should be some way to connect to remote web socket. Otherwise you limit Playwright to local test execution only.

Any solution for this?

**Comment by dskochubey** [comment]
@pavelfeldman I’m currently evaluating 1.27 with LambdaTest. I’m following LambdaTest example of using `browserType.connect()` or `browserType.launch()`  to connect to a remote browser. Playwright returns error `browserType.launch: Playwright version 1.27.0 not supported. Supported versions are 1.19.0 to 1.24.2`. I didn’t find any announcements that that feature doesn’t supported any more and what use instead. Can anybody clarify on this? 

P.S. with 1.24.2 everything works just fine.

**Comment by pavelfeldman** [comment]
Looks like Lambdateat is only supporting old versions of Playwright?

**Comment by dskochubey** [comment]
@pavelfeldman It seems that issue is on Playwright's side. I use the Playwright method [browserType.connect(wsEndpoint[, options])](https://playwright.dev/docs/api/class-browsertype#browser-type-connect) with wsEndpoing provided by LambdaTest. When running a test, Playwright throws the error: `browserType.connect: Playwright version 1.27.0 not supported. Supported versions are 1.19.0 to 1.24.2`.

**Comment by jfrantzius** [comment]
In my case I want to run my Java test on a non-supported platform in Jenkins, while connecting to a Playwright server (which runs using the official docker image). Because my Jenkins is air-gapped, I need to disable the browsers download. 

The problem now is that `Playwright.create()` (in `PlaywrightImpl.createImpl()` always creates a process for a local driver, which then fails for me like this:
```
/tmp/playwright-java-7549223223667235521/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/playwright-java-7549223223667235521/node)
/tmp/playwright-java-7549223223667235521/node: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/playwright-java-7549223223667235521/node)
/tmp/playwright-java-7549223223667235521/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/playwright-java-7549223223667235521/node)
/tmp/playwright-java-7549223223667235521/node: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/playwright-java-7549223223667235521/node)
/tmp/playwright-java-7549223223667235521/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/playwright-java-7549223223667235521/node)
/tmp/playwright-java-7549223223667235521/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/playwright-java-7549223223667235521/node)
Skipping browsers download because `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` env variable is set
java.io.IOException: Stream closed
	at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442)
	at java.base/java.io.OutputStream.write(OutputStream.java:157)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at com.microsoft.playwright.impl.WriterThread.run(PipeTransport.java:167)
java.io.IOException: Stream closed
	at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442)
	at java.base/java.io.OutputStream.write(OutputStream.java:157)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:182)
	at com.microsoft.playwright.impl.PipeTransport.close(PipeTransport.java:93)
	at com.microsoft.playwright.impl.PipeTransport.poll(PipeTransport.java:71)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:200)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:118)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:126)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:106)
	at com.microsoft.playwright.impl.Connection$Root.initialize(Connection.java:82)
	at com.microsoft.playwright.impl.Connection.initializePlaywright(Connection.java:177)
	at com.microsoft.playwright.impl.PlaywrightImpl.createImpl(PlaywrightImpl.java:52)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:35)
	at com.microsoft.playwright.Playwright.create(Playwright.java:110)
	at com.microsoft.playwright.Playwright.create(Playwright.java:114)
```
Currently I see no way to work around this problem, does anybody perhaps know a solution?

**Comment by slav4ik51493** [comment]
@jfratzius

Did you find any solution for this? 
I've also problem when I need to connect to remote browser on the server without running locally node process and save memory.
I'm working with .NET and I had the idea prevent running node process and just creating websocket to remote browser.
