### ISSUE TITLE
[Question] should I be able to type a page object as Page in typescript

### ISSUE THREAD

**Issue by onno-amsterdam** [microsoft/playwright#4702]
Consider the following code:
```javascript
import { Page } from 'playwright';

export async function openNewBrowserContext(): Promise<Page> {
    const context = await browser.newContext();
    return context.newPage();
}
```

and

```javascript
import { Page } from 'playwright';

let page: Page;

const context = await browser.newContext();
page = await context.newPage();
```

Both code blocks give me the TS error:
`Type 'Page' is missing the following properties from type 'Page': tap, touchscreen ts(2739)`

I would expect this to work or am I missing something?

**Comment by mxschmitt** [comment]
What is browser in your case? And what TypeScript version are you using?

I tried the following example which didn't lead to warnings to me:

```ts
import { chromium, Page } from '.';

let page: Page;

(async () => {
  const context = await (await chromium.launch()).newContext();
  page = await context.newPage();
  console.log(page.url());
})();
```

**Comment by onno-amsterdam** [comment]
@mxschmitt thank you. Yes I see I should have provided some more information. I'm using jest-playwright so the browser instance I'm using is global (chromium defined in the config).  Should I be able to type page when using the global browser?

**Comment by JoelEinbinder** [comment]
It looks like you have a version mismatch with the `playwright-core` downloaded by `jest-playwright` and the `playwright` you installed yourself. Reinstalling `jest-playwright` will probably help. Otherwise you can probably force it to work by installing `playwright-core@1.6.2` yourself. If you are still having trouble, please post your `package.json` so I can take a look. Thanks!

**Comment by mxschmitt** [comment]
@JoelEinbinder good catch, a few releases since `playwright-core` was removed from the `playwright` package the users have to install it manually and themselves make sure that the version is the same.

**Comment by onno-amsterdam** [comment]
Thank you! Installing `playwright-core` fixed it for me.
