### ISSUE TITLE
[BUG] Throw MODULE_NOT_FOUND error on require

### ISSUE THREAD

**Issue by ysmood** [microsoft/playwright#4703]
**Context:**
- Playwright Version: v1.6.2
- Operating System: Windows7
- Node.js version: v13.6.0

**Code Snippet**

![image](https://user-images.githubusercontent.com/1415488/102082456-5c808180-3e55-11eb-97d0-06c2ac308071.png)

**Describe the bug**

Shouldn't throw any error. 

The same project, it works well on Windows10.

**Comment by mxschmitt** [comment]
It seems like your test project has the name playwright (package.json) and you want to install Playwright, so NPM or more specific Node.js is confused when loading the module. Could you try to use e.g. `test-playwright` as a folder name and name in your package.json?

Seems to be related to that: https://docs.npmjs.com/cli/v6/commands/npm-install#limitations-of-npms-install-algorithm

```
temporaryadmin@C02D91BJML86 playwright % npm install playwright
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "playwright" under a package
npm ERR! also called "playwright". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/temporaryadmin/.npm/_logs/2020-12-14T12_51_22_339Z-debug.log
```

**Comment by ysmood** [comment]
@mxschmitt 
![image](https://user-images.githubusercontent.com/1415488/102083818-80dd5d80-3e57-11eb-8e63-6edd1da2078a.png)

**Comment by aslushnikov** [comment]
@ysmood can you please share a link to your project so that we can reproduce locally?

**Comment by ysmood** [comment]
It has only 1 line of code. Type it is faster than clone it 😂

**Comment by aslushnikov** [comment]
@ysmood your package.json is missing though - can you share it as well?

**Comment by ysmood** [comment]
It's in the first screenshot, do you see it in the top right?

```
{
  "dependencies": {
    "playwright": "^1.6.2"
  }
}
```

**Comment by ysmood** [comment]
Just normal `npm init`, `npm i playwright`, nothing fancy.

**Comment by aslushnikov** [comment]
@ysmood I think both Win 7 and node 13 are unsupported and I don't have them at my disposal, but I do have win10 with node 14. 

There in Git Bash I do the following:

```sh
$ mkdir tmp
$ cd tmp
$ npm init -y
$ npm install playwright
$ echo "require('playwright');" > index.js
$ node . 
```

And things work for me. Can you running these steps? Also, can you try updating node to 14 at least?

**Comment by ysmood** [comment]
@aslushnikov Yes, I already said about Windows10 on my first comment. I think you missed that line.

Node13 is maximum version Win7 supports. Please take some time to google.

**Comment by aslushnikov** [comment]
>  I think you missed that line.

@ysmood I did

> Node13 is maximum version Win7 supports. Please take some time to google.

So I was able to repro this with [x86 win7 with IE11](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) VM
and [node.js v13.6.0](https://nodejs.org/dist/v13.6.0/).

This is a node bug though; if you use [node v13.14.0](https://nodejs.org/dist/v13.14.0/) it goes away. 

Good luck!

**Comment by ysmood** [comment]
I see, thank you!
