### ISSUE TITLE
[Feature] Mouse Move Actions for Frame Element

### ISSUE THREAD

**Issue by qtpsudhakar** [microsoft/playwright#4720]
Currently mouse.move, mouse.down, mouse.up actions are available only for page but not for frame or element. As of now I am handling it by writing custom logic with respect to page using x, y and width of frame elements. Please make mouse actions available for frames and elements.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
