### ISSUE TITLE
[Question] Finding verbose logging

### ISSUE THREAD

**Issue by shkkim** [microsoft/playwright#4721]
I've currently set my environment variables as the following
# Linux/macOS
$ DEBUG=pw:api 

Next after running 'node myScript.js' 
Where can I find my verbose logs?

**Comment by mxschmitt** [comment]
If you run `DEBUG=pw:api node myScript.js` it will print the verbose logs to the stderr, does this fit for your use-case?

**Comment by avodovnik** [comment]
@shkkim are you running the script locally or in a CI-like environment? As @mxschmitt pointed out, the default output is `stderr` so you should see them in the console, if running locally. 

It should look something like this:

![image](https://user-images.githubusercontent.com/1932563/102251527-39150f80-3f05-11eb-8b7f-27d46b89f2ef.png)

If you're running in a CI-like environment, you might want to redirect the `stderr` output. Most shells will let you do something like

`node index.js 2>pwdebug.log`
