### ISSUE TITLE
[Question] Can we use env. variable (browser) from a jenkinsfile in the tests?

### ISSUE THREAD

**Issue by DiegoFBenavides** [microsoft/playwright#4725]
Hi guys!
Can someone help me to use the browser variable used in the jenkinsfile into the test to give value to browsertype?

Sorry... I´m so new here

Regards

**Comment by avodovnik** [comment]
If I understand what you're asking for, this should be a [good guide](https://stackoverflow.com/questions/49777610/jenkins-pipeline-access-environment-variable-in-nodejs-builds).

Basically, in your `jenkinsfile`, have something like:

```
pipeline {
    ...

    environment {
        MYBROWSERTYPE="webkit"
    }

    ...
}
```

Then you can use `process.env.MYBROWSERTYPE;` in something like:

```
const browser = await playwright[process.env.MYBROWSERTYPE].launch({headless: false});
```

Hopefully that helps. In the future, I'd suggest using https://stackoverflow.com/questions/tagged/playwright to ask questions. You'll get a better answer sooner there.
