### ISSUE TITLE
[Question] Best way to use playwright in parallel?

### ISSUE THREAD

**Issue by MihailPertsev** [microsoft/playwright#4729]
Hi there!

I have an electron app that is doing a browser automation (navigation, form population, saving files, etc). The user can add a various of scripts in the "script store" and they will run in parallel.

Currently I am using mocha because it has parallel mode (since 8 version) and I am more familiar with it. I have a function like this:

```
function runMochaTest(pathToScript, reportFileName, callback) {
  const mocha = new Mocha({
    parallel: true,
    reporter: "xunit",
    reporterOptions: {
      output: `${exeDirectory}/../reports/${reportFileName}.xml`
    },
  });

  mocha.addFile(pathToScript);

  mocha.run(() => {
    callback();
  });
}

```
And a typical script is look like this:

```
const data = require('./somedata.json');

describe("parallel playwright execution via mocha 8.0", async function () {
  data.forEach(async function (product) {
    it(`parsing data for ${product}`, async function () {
      this.timeout(120000);
      const browser = await chromium.launch();
      const context = await browser.newContext({
        ignoreHTTPSErrors: true,
        viewport: null,
        httpCredentials: {
          username: credentials.username,
          password: credentials.password,
        },
      });

      const page = await context.newPage();
      await page.goto("http://website.com", { waitUntil: "load"});

     //... some data related stuff 

      await browser.close();
    });
  });
});
```

So far everything is working, but since I don't need any mocha features beside the parallel execution and xml report, I want to explore other alternatives to what I am doing now.

So, my question is: What are the "best practices" to execute playwright in parallel? Are you using something like jest or other test runners?

**Comment by thernstig** [comment]
Jest with [Jest-Playwright](https://github.com/playwright-community/jest-playwright) works just fine for this. I recommend creating a separate [Jest project](https://jestjs.io/docs/en/configuration#projects-arraystring--projectconfig). You can then execute it with `jest --selectProjects e2e`, see https://jestjs.io/docs/en/cli#--selectprojects-project1--projectn.

**Comment by MihailPertsev** [comment]
> Jest with [Jest-Playwright](https://github.com/playwright-community/jest-playwright) works just fine for this. I recommend creating a separate [Jest project](https://jestjs.io/docs/en/configuration#projects-arraystring--projectconfig). You can then execute it with `jest --selectProjects e2e`.

Thanks for suggestion, never used jest before but I will try it out. But jest-playwright feels like an overkill in my case since I am not doing any testing and I only need a parallel execution and json/xml report. Maybe I should start with "pure" jest.

**Comment by fawazahmed0** [comment]
Please refer [this](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await)
you will have to use await & promise.all

```
javascript
async function somefunc(){
// both will run in parallel, dosometask1 & dosometask2 is async
let sometask1 = dosometask1();
let sometask2 = dosometask2();
// wait for both tasks to complete
await Promise.all([sometask1 , sometask2])
}
```

**Comment by MihailPertsev** [comment]
> Please refer [this](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await)
> you will have to use await & promise.all
> 
> ```js
> async function somefunc(){
> // both will run in parallel, dosometask1 & dosometask2 is async
> let sometask1 = dosometask1();
> let sometask2 = dosometask2();
> // wait for both tasks to complete
> await Promise.all([sometask1 , sometask2])
> }
> ```

Thanks for suggestion, but I think in my case this behaviour is not the one I want. I do not need to wait all scripts to be done at the same time, in fact what I need is complete opposite. I think I needs something like [run-parallel](https://www.npmjs.com/package/run-parallel) but with a little bit more functionality. The test runner like Mocha or jest seems like a good case for me because you can have a programmatic control(I think you can't in Mocha-parallel tho...) over each task(test) when it is over or when it failed, etc.

But still I am trying to find something else, because Mocha or jest is an overkill in terms of features.

This is a workflow in my app: user adds **script1** and it starts executing. => then user can add **script2** and it starts executing => script 1 is done and we should report it to the user without waiting for script2 to be done.

**Comment by fawazahmed0** [comment]
you can use async await for any scenario, for example, you start script1 without await keyword, then you start script2 without await keyword, then you await for script1 and then report to the user

**Comment by MihailPertsev** [comment]
> you can use async await for any scenario, for example, you start script1 without await keyword, then you start script2 without await keyword, then you await for script1 and then report to the user

I though you meant Promise.all ... Yeah, sure. I am already using async/await inside my scripts which are basically playwright instructions. 

Something like: go to this website => fill the form => download the file, etc

And the "script" is just a .js file like this one:

`const data = require('./somedata.json');

describe("parallel playwright execution via mocha 8.0", async function () {
  data.forEach(async function (product) {
    it(`parsing data for ${product}`, async function () {
      this.timeout(120000);
      const browser = await chromium.launch();
      const context = await browser.newContext({
        ignoreHTTPSErrors: true,
        viewport: null,
        httpCredentials: {
          username: credentials.username,
          password: credentials.password,
        },
      });

      const page = await context.newPage();
      await page.goto("http://website.com", { waitUntil: "load"});

     //... some data related stuff 

      await browser.close();
    });
  });
});`

And right now I am using Mocha programmatically to use it like a [https://www.npmjs.com/package/run-parallel](run-parallel) package + [https://www.npmjs.com/package/mochawesome](mochawesome) html report.

I might misunderstood you, did you suggest to create some kind of "runScriptsInParallel" async function and inside that function wait for some event like "newScriptAdded" and then process it via `let sometask1 = dosometask1();` and then use await `await sometask1`  ?

**Comment by fawazahmed0** [comment]
please refer any async await tutorial, that will surely help you achieve what ever you want, using pure Javascript

**Comment by nicoandmee** [comment]
Check out: https://github.com/agaricide/puppeteer-functional-patterns (although it is for puppeteer, still directly applicable)

**Comment by thernstig** [comment]
@MihailPertsev I have a hard time understanding what your question is then. There are several options, and multiple have been suggested, but they do not seem to suite your need. There is no "best practice" in that case, since many common ones have been mentioned already. I think you just have to come up with how you yourself want this to work.

Just go with Jest if that is what you want then, even though you said you are not doing any tests. It will work just fine.

**Comment by MihailPertsev** [comment]
> Check out: https://github.com/agaricide/puppeteer-functional-patterns (although it is for puppeteer, still directly applicable)

Thank you! This is really useful! Are there any other chapters?

**Comment by MihailPertsev** [comment]
> @MihailPertsev I have a hard time understanding what your question is then. There are several options, and multiple have been suggested, but they do not seem to suite your need. There is no "best practice" in that case, since many common ones have been mentioned already. I think you just have to come up with how you yourself want this to work.
> 
> Just go with Jest if that is what you want then, even though you said you are not doing any tests. It will work just fine.

As I noted earlier, my current solution via Mocha already works, and it works well. I just want to know alternatives to this approach, and have learned a lot already.

**Comment by aslushnikov** [comment]
@MihailPertsev one other option to run Playwright in parallel would be our very own [playwright-test](https://github.com/microsoft/playwright-test) which is in preview.
