### ISSUE TITLE
[Question] Manual installation of browsers

### ISSUE THREAD

**Issue by GooglePeng** [microsoft/playwright#4734]
Where I can find the chrome/firefox/webkit link？
I can't execute 'python -m playwright install'
so I want to download from links

**Comment by avodovnik** [comment]
Can you elaborate? Why can't you execute the install command? 

If this is a corporate restriction problem, please add a comment to https://github.com/microsoft/playwright-python/issues/236.

**Comment by aslushnikov** [comment]
If you absolutely need to download browsers manually, you can get them from the https://devops.aslushnikov.com

**Comment by andrewchenshx** [comment]
can NOT download the browsers either.
request for https://raw.githubusercontent.com/ returns 503

**Comment by tennessine** [comment]
You can check this file

/Users/gekongfei/Projects/my-electron-app/node_modules/playwright-core/lib/server/registry/index.js

you can change the url of your own, or download it manually and put it somewhere.

**Comment by vishnuport** [comment]
Hi everyone 
I want to manually  install latest Firefox stable build for play wright 1.34.0 
can someone provide the link please
