### ISSUE TITLE
[Question] how to know exactly where to look for the target image when using `.toMatchSnapshot(targetImg)` ? 

### ISSUE THREAD

**Issue by shyan1** [microsoft/playwright#4735]
At line 34 of https://github.com/microsoft/playwright/blob/master/test/elementhandle-screenshot.spec.ts 

I get that the image was located in `test/__snapshots__` folder, but cannot figure out how the image was located. 

The snippet is as follows, 
```javascript
  it('should work', async ({page, server}) => {
    await page.setViewportSize({width: 500, height: 500});
    await page.goto(server.PREFIX + '/grid.html');
    await page.evaluate(() => window.scrollBy(50, 100));
    const elementHandle = await page.$('.box:nth-of-type(3)');
    const screenshot = await elementHandle.screenshot();
    expect(screenshot).toMatchSnapshot('screenshot-element-bounding-box.png');
  });
```

**Comment by mxschmitt** [comment]
Playwright internally uses [Folio](https://github.com/microsoft/folio) as a test runner. It has a snapshot functionality built-in, if no snapshots are persistent, you can use the -u flag:
> -u, --update-snapshots           Whether to update snapshots with actual results (default: false)
to update or create the snapshots. Internally it compares then images and determines how different they are on a percentage level.

Maybe it should be followed up by adding more docs to folio about that feature.
