### ISSUE TITLE
[Question] Running playwright from inside browser.

### ISSUE THREAD

**Issue by ferllings** [microsoft/playwright#4738]
Hello,

I'll would to know if it is feasible to run playwright scenario from inside a browser plugin.
I would like to be able to launch (from a plugin) some tests against the DOM, to check the page code for various parameters and generates a report.

Thanks,

**Comment by aslushnikov** [comment]
> I'll would to know if it is feasible to run playwright scenario from inside a browser plugin.

@ferllings I'm not sure I follow exactly what's meant here, so I'll try to answer both possible meanings I can think of:

- If we talk about running all of playwright script from-inside browser (including commands such as `chromium.launch()`), than this is not feasible. Playwright is a node.js application, and browser env simply doesn't provide all the necessary functionality.
- However, if you just want to run some of the tests inside browser, than you can use [`page.evaluate()`] to run code inside browser context.

>I would like to be able to launch (from a plugin) some tests against the DOM, to check the page code for various parameters and generates a report.

This should be doable with a regular playwright operation: you start in node.js to launch the browser, and then do [`page.evaluate()`] to gather some statistics inside the page. Check out this tutorial: https://playwright.dev/docs/core-concepts#execution-contexts-nodejs-and-browser


[`page.evaluate()`]: https://playwright.dev/docs/api/class-page?_highlight=page.evaluate#pageevaluatepagefunction-arg

**Comment by dgozman** [comment]
Please reopen if this didn't answer your question.
