### ISSUE TITLE
[BUG] [Firefox] TypeError: browser.webProgress is undefined / assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#4740]
**Context:**
- Playwright Version: 1.7.0
- Operating System: Linux, Heroku
- Node.js version: v12.20.0
- Browser: Firefox

**Code Snippet**

```javascript
// @ts-check
const playwright = require("playwright");

(async () => {
    const browser = await playwright.firefox.launch();
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto('http://whatsmyuseragent.org/');
    await page.screenshot({ path: `example.png` });
    await browser.close();
})();
```

**Describe the bug**

Firefox can't start, the tab suprocess crashes. It was working with 1.5.1 but with 1.7.0 I run into this weird error (not me actually, I'm maintaining the Heroku buildpack, probably then the users).

The full logs see here:
[log (1).txt](https://github.com/microsoft/playwright/files/5704743/log.1.txt)

GLib-GObject-CRITICAL **: 18:20:18.805: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

Related PR: https://github.com/mxschmitt/heroku-playwright-example/pull/8

**Comment by mxschmitt** [comment]
Seems like its failing for the same reason on the bots sometimes: https://github.com/microsoft/playwright/pull/4747/checks?check_run_id=1569969846#step:9:56

**Comment by dgozman** [comment]
@aslushnikov  Searching around for this error, it's somewhat common when running Firefox on linux. Perhaps upstream bug?

**Comment by aslushnikov** [comment]
@mxschmitt is this still bothering you on Heroku?

**Comment by mxschmitt** [comment]
No seems fixed, lets close it.
