### ISSUE TITLE
integration for the aXe accessibility testing engine [Feature]

### ISSUE THREAD

**Issue by Djelloul007** [microsoft/playwright#4750]
Let us know what functionality you'd like to see in Playwright and what is your use case.
Do you think others might benefit from this as well?
integration for the aXe accessibility testing engine   https://github.com/dequelabs/axe-core

**Comment by pavelfeldman** [comment]
Could you provide more details on the way you'd like to see those integrated?

**Comment by pavelfeldman** [comment]
This isn't something we'll be doing immediately, but definitely open to the topic. Please feel free to file a new issue if you'd like to see a specific shape of such API + use cases!
