### ISSUE TITLE
[Feature] Fail smart option

### ISSUE THREAD

**Issue by kaushalyap** [microsoft/playwright#4759]
This is similar to request made [here](https://github.com/cypress-io/cypress/issues/518) but with an improvement

I suggest providing an option in Playwright to fail smart

Usually fail fast work when first failed test encountered rest of the test are skipped until you fixed it even though there might be several failing tests down the line. But developer have to fix all those failed test one after other waiting for the CI. [This Reddit comment](https://www.reddit.com/r/javascript/comments/k4hoky/a_cypress_plugin_to_skip_tests_on_first_failure/gebek28) explain what I am telling . 

I suggest a Playwright option like below which allows test suites to fail smart  by specifying threshold for number of failed tests before skipping the rest of the test suite.

```
fail-smart: true,
no-fails: 10
```

**Comment by aslushnikov** [comment]
> [This Reddit comment](https://www.reddit.com/r/javascript/comments/k4hoky/a_cypress_plugin_to_skip_tests_on_first_failure/gebek28) explain what I am telling . 

@kaushalyap this behavior is specific to the test runner rather than Playwright it self. Depending on the test runner you use, you might get it out of the box.

For example, out [playwright-test](https://github.com/microsoft/playwright-test) test runner already has this behavior - so you'll get a list of all the test failures after a single CI run. I think something similar could be setup using jest.

**Comment by kaushalyap** [comment]
> @kaushalyap this behavior is specific to the test runner rather than Playwright it self. Depending on the test runner you use, you might get it out of the box.

So Playwright does not have test runner built in like Cypress? Can we use Jest as test runner with Playwright?

> For example, out playwright-test test runner already has this behavior - so you'll get a list of all the test failures after a single CI run. I think something similar could be setup using jest.

Can we define a test skipping threshold with Playwright-test rather than waiting for completion of the whole test suite?

**Comment by aslushnikov** [comment]
> So Playwright does not have test runner built in like Cypress?

@kaushalyap that's right. There's a `playwright-test` though that is in early preview that fulfills this.

> Can we use Jest as test runner with Playwright?

Yes, for sure

> Can we define a test skipping threshold with Playwright-test rather than waiting for completion of the whole test suite?

There's a `--max-failures N` flag in Playwright-test that you can specify to abort running tests when N tests fail.

**Comment by kaushalyap** [comment]
Thanks I'll close this now.
