### ISSUE TITLE
[Feature] Please implement elementHandle.locator([options]) feature

### ISSUE THREAD

**Issue by And93** [microsoft/playwright#4763]
Hi,

For now, if we need to get a selector of an element, we need to implement a few additional helpers from project to project.
But it would be great to have this feature out of the box.
This function should provide a selector not only for the current node, but also for the parent node.

Example:
```js
const liEl = await page.$('li');
const hrefEl = await liEl.$('a');

console.log(hrefEl.locator({param: 'tag', parents: '1'})) // li > a
console.log(hrefEl.locator({param: 'attribute', parents: '2'})) // .row > [data-element] > [href="..."]
console.log(hrefEl.locator({param: 'combined', parents: '2'})) // div.row > li[data-element] > a[href="..."]
console.log(hrefEl.locator({param: 'index', parents: '3'})) // body > div > li:nth-child(2) > a
```

My current helper: [click](https://github.com/And93/autotests-by-levels/blob/master/3_ui/puppeteer/mocha/src/helpers/SelectorHelper.ts#L33)

**Comment by aslushnikov** [comment]
FYI: We have a [codegen functionality](https://github.com/microsoft/playwright-cli#generate-code) in [`playwright-cli`](https://github.com/microsoft/playwright-cli), but that's not programmatic at this moment.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.

(Note that we plan to implement something similar. The message above is just a part of the semi-automatic triage.)
