### ISSUE TITLE
[Feature] Record gif snippets

### ISSUE THREAD

**Issue by Aaron-Pool** [microsoft/playwright#4772]
The full-fledged video recording feature is nice, but often times I just want to record a one or two second interaction from  a test that might run for 10 seconds, so that I can provide assurance to my QA team that a particular behavior is correct.

In that case, recording a video of the whole test is a bit heavy handed, and it adds a substantial time delay to closing the browser context. Is there any way we could get a simple `start` and `stop` api for creating very small gif clips? Kind of a medium solution between simple screenshots, and potentially cumbersome full-length video recordings.

**Comment by mxschmitt** [comment]
Note: Since ffmpeg is shipped, it would be nice if an output format could be selected in the recordVideo options. Then mp4, webp or gif would be great to have.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
