### ISSUE TITLE
[Feature] Playwright does not support chromium on mac11.1

### ISSUE THREAD

**Issue by mer163** [microsoft/playwright#4775]
(node:1278) UnhandledPromiseRejectionWarning: Error: ERROR: Playwright does not support chromium on mac11.1

**Comment by aslushnikov** [comment]
Which playwright version did you try? Playwright v1.7.0 should support it just fine.

**Comment by xg-wang** [comment]
I'm on playwright 1.6.2 and seeing this error.

I was running `node node_modules/playwright/install.js` to be able to see the error message, normal `yarn install` succeeds but left `~/Library/Caches/ms-playwright` empty folder.

Upgrading to 1.7.0 does fix the issue.

**Comment by nwittwer** [comment]
Seeing this error also on MacOS 11.2 (beta) with Playwright 1.7.1.

```
npm i playwright -D
> playwright@1.7.1 install /Users/me/node_modules/playwright
> node install.js
UnhandledPromiseRejectionWarning: Error: ERROR: Playwright does not support chromium on mac11.2
```

**Comment by MarcoZehe** [comment]
I am seeing this error, too, when trying to build VsCode. Pulling current Master, making sure all build prerequisites are met, then running `yarn` results in this error:

```
error /Users/marco/projects/vscode/node_modules/playwright: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/marco/projects/vscode/node_modules/playwright
Output:
/Users/marco/projects/vscode/node_modules/playwright/lib/utils/utils.js:58
        throw new Error(message);
              ^

Error: ERROR: Playwright does not support chromium on mac11.2-arm64
    at Object.assert (/Users/marco/projects/vscode/node_modules/playwright/lib/utils/utils.js:58:15)
    at revisionURL (/Users/marco/projects/vscode/node_modules/playwright/lib/install/browserFetcher.js:143:13)
    at Object.downloadBrowserWithProgressBar (/Users/marco/projects/vscode/node_modules/playwright/lib/install/browserFetcher.js:168:17)
    at async validateCache (/Users/marco/projects/vscode/node_modules/playwright/lib/install/installer.js:103:9)
```

This is on an M1 MacBook Pro running the 11.2 Beta. VSCode Insiders itself runs perfectly fine natively on this machine.

**Comment by karoukastro** [comment]
Hi @aslushnikov I installed it today and it is returning error. What should I do?

carol@Carolinas-MBP parodify % python3 -m playwright install
Failed to process descriptor at /Users/carol/robot/parodify/node_modules/playwright
Removing unused browser at /Users/carol/Library/Caches/ms-playwright/chromium-844399
Removing unused browser at /Users/carol/Library/Caches/ms-playwright/firefox-1225
Removing unused browser at /Users/carol/Library/Caches/ms-playwright/webkit-1423
(node:3565) UnhandledPromiseRejectionWarning: **Error: ERROR: Playwright does not support chromium on mac11.2**
    at Object.assert (/snapshot/playwright-cli/node_modules/playwright/lib/utils/utils.js:58:15)
    at revisionURL (/snapshot/playwright-cli/node_modules/playwright/lib/install/browserFetcher.js:143:13)
    at Object.downloadBrowserWithProgressBar (/snapshot/playwright-cli/node_modules/playwright/lib/install/browserFetcher.js:168:17)
    at async validateCache (/snapshot/playwright-cli/node_modules/playwright/lib/install/installer.js:103:9)
    at async Object.installBrowsersWithProgressBar (/snapshot/playwright-cli/node_modules/playwright/lib/install/installer.js:60:5)
(node:3565) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3565) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by aslushnikov** [comment]
@karoukastro which version of playwright-python do you use? The bugfix should be available in version `1.8.0` and is not available in earlier versions on playwright-python.

**Comment by karoukastro** [comment]
@aslushnikov Playwright Version: 1.8.1
 I've raised a new bug: #5443

**Comment by JayKishoreDuvvuri** [comment]
Yes the Bug still exists. I can still see this error Playwright does not support chromium for MacOs 11.2

**Comment by juli1** [comment]
I still have the issue when trying to install playright with npm.

```
pip3 install playwright==1.9.0
```

and then

```
$ npm i
npm ERR! code 1
npm ERR! path /Users/julien/git/ci-react-frontend/node_modules/playwright
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! /Users/julien/git/ci-react-frontend/node_modules/playwright/lib/utils/utils.js:58
npm ERR!         throw new Error(message);
npm ERR!               ^
npm ERR!
npm ERR! Error: ERROR: Playwright does not support chromium on mac11.2
npm ERR!     at Object.assert (/Users/julien/git/ci-react-frontend/node_modules/playwright/lib/utils/utils.js:58:15)
npm ERR!     at revisionURL (/Users/julien/git/ci-react-frontend/node_modules/playwright/lib/install/browserFetcher.js:143:13)
npm ERR!     at Object.downloadBrowserWithProgressBar (/Users/julien/git/ci-react-frontend/node_modules/playwright/lib/install/browserFetcher.js:168:17)
npm ERR!     at async validateCache (/Users/julien/git/ci-react-frontend/node_modules/playwright/lib/install/installer.js:103:9)
npm ERR!     at async installBrowsersWithProgressBar (/Users/julien/git/ci-react-frontend/node_modules/playwright/lib/install/installer.js:60:5)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/julien/.npm/_logs/2021-04-28T16_48_08_543Z-debug.log
```

**Comment by mxschmitt** [comment]
@juli1 is it also reproducible on Playwright 1.10? `pip3 install playwright==1.10.0`

**Comment by JayKishoreDuvvuri** [comment]
I still see the error on MacOS Big Sur 11.2 saying playwright does not support chromium

**Comment by roseline124** [comment]
still error, too

**Comment by JayKishoreDuvvuri** [comment]
Error resolved now thank you!

**Comment by mxschmitt** [comment]
Please open a new issue, with more details.

---

Locking this issue - to not spam the other subscribed folks.
