### ISSUE TITLE
[BUG] Error: EPERM: operation not permitted, unlink "..../CrashpadMetrics-active.pma"

### ISSUE THREAD

**Issue by meotimdihia** [microsoft/playwright#4780]
**Context:**
- Playwright Version: ^v1.6.2
  System:
    OS: Windows 10 10.0.19041
    Memory: 5.71 GB / 15.92 GB
  Binaries:
    Node: 12.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - ~\.yarn\bin\yarn.CMD
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Bash: 4.4.23 - C:\Program Files\git\usr\bin\bash.EXE

**Code Snippet**

```javascript
let browser
;(async () => {
  try {
    const { chromium } = require("playwright")
    browser = await chromium.launch()
    const context = await browser.newContext()
    const page = await context.newPage()
    await page.goto("https://exampsas12le.com")
  } catch (e) {
//    await new Promise(resolve => setTimeout(resolve, 1000))  // The bug won't happen if I uncomment this line
    await browser.close()
  }
})()

```

**Describe the bug**
The code works fine in `headless: false` mode but the bug appear in headless mode.
```
$ node dist/src/examples/test
[Error: EPERM: operation not permitted, unlink 'C:\Users\meoti\AppData\Local\Temp\playwright_chromiumdev_profile-CVW7lo\CrashpadMetrics-active.pma'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\Users\\meoti\\AppData\\Local\\Temp\\playwright_chromiumdev_profile-CVW7lo\\CrashpadMetrics-active.pma'
}
```
![WindowsTerminal_2020-12-20_14-55-19](https://user-images.githubusercontent.com/300961/102708155-67af3380-42d3-11eb-84af-b5f3201e2d79.png)

**Comment by JoelEinbinder** [comment]
Thanks for the report. Does this happen on any url?

**Comment by meotimdihia** [comment]
This always happen when did I use dead proxy to fetch data.

**Comment by pavelfeldman** [comment]
@dgozman could it be that you fixed it?

**Comment by aslushnikov** [comment]
Crash reporter has been disabled in Firefox in #5514, so hopefully we won't see this ever again.

**Comment by meotimdihia** [comment]
@aslushnikov: the bug is remaining for playwright 1.9.1

**Comment by MkrV** [comment]
I have the same issue, even at headful mode.
playwright-python 1.9.1, Windows 10.

because of it Chromium(chrome.exe) doesn't close correctly, and very soon start consuming 100% CPU.
As a temporary solution I close all Chromiums via CMD in Admin mode: 
wmic process where ExecutablePath='C:\\Users\\User\\AppData\\Local\\ms-playwright\\chromium-854489\\chrome-win\\chrome.exe' delete

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/6123

**Comment by mxschmitt** [comment]
Closing since #6123 was closed and https://chromium-review.googlesource.com/c/chromium/src/+/2999433 was merged.
