### ISSUE TITLE
[Question] Wait for image loaded.

### ISSUE THREAD

**Issue by tzuseeworld** [microsoft/playwright#4782]
I have an image on the page will not loaded at once, how can I ensure it has been loaded and wait for it?

**Comment by gonzobard777** [comment]
To make sure that the image is loaded and wait for this moment, you can use  
[page.waitForResponse(urlOrPredicate[, options])](https://github.com/microsoft/playwright/blob/master/docs/api.md#pagewaitforresponseurlorpredicate-options)

**Comment by pavelfeldman** [comment]
Closing as per ^^ as a viable solution.
