### ISSUE TITLE
[Question]UnhandledPromiseRejectionWarning EVERYTIME

### ISSUE THREAD

**Issue by aaronportier** [microsoft/playwright#4788]
I seem to get the error shown after the code everytime.
code:
const playwright= require('playwright');

(async function main() {

    const browser = await playwright.chromium.launch({headless:false});

  //  const context =await broswer.newContext();

    const page = await browser.newPage();

    await page.goto('https://www.google.com/');
    await page.waitForTimeout(5000);
    
    await browser.close();
})
(node:4192) UnhandledPromiseRejectionWarning: ReferenceError: playwright is not defined
    at C:\Users\Aarons\Desktop\playwrighttest.js:5:21
    at Object.<anonymous> (C:\Users\Aarons\Desktop\playwrighttest.js:17:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
<node_internals>/internal/process/warning.js:43

**Comment by gonzobard777** [comment]
try this
```js
const playwright= require('playwright');

(async function main() {

  const browser = await playwright['chromium'].launch({headless:false});
// const context =await broswer.newContext();

  const page = await browser.newPage();

  await page.goto('https://www.google.com/');
  await page.waitForTimeout(5000);

  await browser.close();
})()
```

**Comment by dgozman** [comment]
Did you install playwright? Try running `npm install playwright` before running the script.
