### ISSUE TITLE
[Feature] Option to return HAR via method instead of to file

### ISSUE THREAD

**Issue by BeauAgst** [microsoft/playwright#4798]
Currently, there is a `browserContext` option of `recordHar`, which when a path is set, will save the JSON data to a file. This means that once your action has completed, you have to manually find the file if you need to read that data. 

In my use-case, it would definitely be easier if the user were able to grab HAR data directly from the page, via `page.har()` or similar. I could imagine this working in the same way that `page.screenshot()` operates, where if you don't pass a path, the data is returned directly from the function.

**Comment by dgozman** [comment]
The problem with HAR is that it consumes extra memory during the page load, retaining network requests/responses. We can do something like this, but it's not clear what the api could be.

**Comment by BeauAgst** [comment]
Maybe if `recordHar` options aren't supplied, a user may manually call a `recordHar` method on the `BrowserContext`. Those options could be passed to the method instead, which would keep things more in-line with the `screenshot` method. if path is omitted from these options, the data is returned as json. 

In this situation, the user would have to manually stop recording via another method, which would return the data (or save to a file depending on the options).

I just had a poke around in the code, I'm not sure how well this would work with current the ContextListener implementation, as they are all created on `BrowserContext` init

**Comment by danielbogatinov13** [comment]
> Maybe if `recordHar` options aren't supplied, a user may manually call a `recordHar` method on the `BrowserContext`. Those options could be passed to the method instead, which would keep things more in-line with the `screenshot` method. if path is omitted from these options, the data is returned as json.
> 
> In this situation, the user would have to manually stop recording via another method, which would return the data (or save to a file depending on the options).
> 
> I just had a poke around in the code, I'm not sure how well this would work with current the ContextListener implementation, as they are all created on `BrowserContext` init

This sounds like a really great option. I need this exact thing. There are cases where I like to save the HAR in a file, and there are cases where I just want to do checks to the HAR data and use code to decide if everything is good to go or needs tweaking. Opening the file and later disposing it seems like unnecessary step in more than half of my use cases, and is affecting my performance

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
