### ISSUE TITLE
[Docs] Broken links on "Running Playwright in Docker" page

### ISSUE THREAD

**Issue by viraxslot** [microsoft/playwright#4799]
Open https://playwright.dev/docs/docker/README/
Click "Dockerfile.bionic" or "Dockerfile.focal" in the first paragraph.

Links are broken:
https://playwright.dev/docs/docker/README/Dockerfile.bionic
https://playwright.dev/docs/docker/README/Dockerfile.focal

Check other links also please:
https://playwright.dev/docs/docker/README/seccomp_profile.json
https://playwright.dev/docs/docker/README/build.sh

**Comment by aslushnikov** [comment]
Links are good now!
