### ISSUE TITLE
[Question] Intermittent waitForResponse timeouts when looping

### ISSUE THREAD

**Issue by LA1CH3** [microsoft/playwright#4806]
Hi, I am trying to use Playwright to automate visiting some webpages and validate that certain analytics files are loaded and contain proper values in their URLs. It is working somewhat- every time I run, I am getting several of the following error, though it seems to happen at random:

```
(node:1485) UnhandledPromiseRejectionWarning: TimeoutError: Timeout while waiting for event "response"
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
```

Sometimes it will work successfully, other times it will work successfully for all but one of the tags. Here is my code for reference. Let me know if there is something I am doing wrong here that could be causing this.

```ts
import { chromium } from "playwright";

import pages from "./pages";

(async () => {
  pages.forEach(async (pageConfig) => {
    pageConfig.tags.forEach(async ({ name, pattern, ...rest }) => {
      const browser = await chromium.launch();
      const context = await browser.newContext();
      const page = await context.newPage();
      await page.goto(pageConfig.path);

      const response = await page.waitForResponse(pattern, { timeout: 20000 });

      if (Object.keys(rest).length) {
        const tagsMet = Object.values(rest).every((tagValue) => {
          return response.url().includes(tagValue);
        });

        if (tagsMet) {
          console.log(`${pageConfig.path}:${name}:PASSED`);
        } else {
          console.log(`${pageConfig.path}:${name}:FAILED`);
        }
      } else {
        console.log(`${pageConfig.path}:${name}:PASSED`);
      }

      await browser.close();
    });
  });
})();
```

**Comment by yury-s** [comment]
Sounds like the server is throttling your requests every once in a while or just slow and `waitForResponse` times out (as expected) after 20s.

Feel free to reopen if there is an evidence that there is a problem on Playwright side.
