### ISSUE TITLE
[BUG]Screenshot quality parameter setting error

### ISSUE THREAD

**Issue by jhjade** [microsoft/playwright#4811]
**Context:**
- Playwright Version: [1.7.1]
- Operating System: [ Windows10]
- Node.js version: [v12.13.1]
- Browser: [All]
- Extra: []

**Code Snippet**
```javascript
const { chromium, firefox, webkit } = require('playwright') 

;(async () => {
  const browser = await firefox.launch()
  const page = await browser.newPage()
  await page.goto('https://www.cnblogs.com/cmt/p/14109447.html')
  //https://playwright.dev/docs/api/class-page#pagescreenshotoptions
  await page.screenshot({
    path: `example.png`,
    fullPage: true,
    quality: 20, // The quality of the image, between 0-100. Not applicable to png images
    type: 'png',
  })
  await browser.close()
  console.log('success')
})()

```

**Describe the bug**

An exception occurs when the quality setting is greater than 0
![微信截图_20201223111136](https://user-images.githubusercontent.com/66857797/102955457-e644e480-4510-11eb-839c-273a2e7b4a70.png)

![微信截图_20201223111136](https://user-images.githubusercontent.com/66857797/102956336-e940d480-4512-11eb-9c97-6bdc4258e802.png)

**Comment by yury-s** [comment]
You should omit `quality` option completely as it only makes sense for `jpg` screenshots. I'll update the code to throw the same error when quality is 0.

**Comment by jhjade** [comment]
> You should omit `quality` option completely as it only makes sense for `jpg` screenshots. I'll update the code to throw the same error when quality is 0.

Sorry, it is my problem. Did not pay attention to the parameter description
