### ISSUE TITLE
[BUG] Missing dependencies in Docker image to play video in Webkit.

### ISSUE THREAD

**Issue by KateKorneeva** [microsoft/playwright#4813]
**Context:**
- Playwright Version:  1.7.1
- Operating System: Linux Ubuntu 20.04.1 (Docker https://github.com/microsoft/playwright/blob/master/docs/docker/Dockerfile.focal)
- Node.js version: v14.15.3, 
- Browser: WebKit

**Code Snippet**
```javascript
const { webkit } = require('playwright');
(async () => {
  const browser = await webkit.launch({ headless: true, slowMo: 2000 });
  const page = await browser.newPage();
  await page.goto('https://my-business-e2etest.coachannel.com/login/');
  await page.fill('[name="login-form"] input[name="email"]', 'test@test.com');
  await page.fill('[name="login-form"] input[name="password"]', 'qwerty123');
  await page.click('[name="login-form"] button[type="submit"]');
  await page.goto('https://my-business-e2etest.coachannel.com/pwdocker/videoinwebkit');
  await page.screenshot({ path: `screenshots/example.png` });
  await browser.close();
})();
```

**Describe the bug**
The visited page ('https://my-business-e2etest.coachannel.com/pwdocker/videoinwebkit', see credentials in script) contains mp4 video.

I run my script within Docker image https://github.com/microsoft/playwright/blob/master/docs/docker/Dockerfile.focal
`DEBUG=pw:browser*  node test.js`

The test runs fine until the browser meets the video. Here is the output:
```
  pw:browser <launching> /root/.cache/ms-playwright/webkit-1402/pw_run.sh --inspector-pipe --headless --no-startup-window +0ms
  pw:browser <launched> pid=3360 +6ms
  pw:browser [err] WebKit wasn't able to find a WebVTT encoder. Not continuing without platform support for subtitles. +20s
  pw:browser [err]  +3ms
  pw:browser [err] ** (WPEWebProcess:3377): WARNING **: 13:01:46.901: WebKit wasn't able to find the GL video sink dependencies. Hardware-accelerated zero-copy video rendering can't be enabled without this plugin. +0ms
  pw:browser <gracefully close start> +2s
  pw:browser <process did exit: exitCode=0, signal=null> +8ms
  pw:browser <gracefully close end> +
```

On the screenshot video has 0:00 duration, which means it is not loaded.

It runs fine fine outside of the Docker container, so I guess there are some libs missing in the image.

**Comment by yury-s** [comment]
> It runs fine fine outside of the Docker container, so I guess there are some libs missing in the image.

I can only play it Chrome but not in Chromium (or WebKit/Firefox open-source builds), the latter shows video duration 0:00. Are you able to play it in Chromium? It seems to require some DRM support which is apparently only available in the official Chrome build, Firefox shows the following message when navigating to the page in UI mode:

![image](https://user-images.githubusercontent.com/9798949/103026167-2a7fb700-4508-11eb-9b53-e03600684d5f.png)

**Comment by KateKorneeva** [comment]
@yury-s thank you, you are right, it does not work in Chromium. However, it works in Safari outside of Docker, this is why I expected it to work in WebKit in Docker as well.

**Comment by yury-s** [comment]
Safari has some proprietary code which is not a part of the open-source WebKit project. We don't have access to that unfortunately as we use only open-source part of the stack (same story with Chrome vs. Chromium). Maybe you could test with a video source that doesn't require proprietary DRM implementation?

Closing this issue as there is not much we can do at this point. Feel free to reopen if you think we can still help you.

**Comment by KateKorneeva** [comment]
@yury-s Thank you for the analysis done here! I will use another video for the tests.
