### ISSUE TITLE
[Question] How does Playwright handle a big list of pages?

### ISSUE THREAD

**Issue by StarpTech** [microsoft/playwright#4814]
Hi,
Does exist a queue or any other mechanism to avoid running out of resources when creating many pages?

**Comment by yury-s** [comment]
There is no inbuilt limit on the number of the pages one can create with Playwright, it's up to the user. The client is expected to close the pages/contexts after running the tests which should free up resources.

**Comment by StarpTech** [comment]
Thanks for the response!
