### ISSUE TITLE
[Question] Docs page color is wierd in night mode chrome

### ISSUE THREAD

**Issue by qzyse2017** [microsoft/playwright#4818]
![Screenshot from 2020-12-24 10-10-37](https://user-images.githubusercontent.com/31987568/103050920-84e44a80-45d0-11eb-94f4-44c26f40ffef.png)

**Comment by qzyse2017** [comment]
gray text with white background seems not clear enough

**Comment by mxschmitt** [comment]
Which Chrome version are you using? I can't reproduce it on the latest Chrome 87. Is it reproducible for you?

**Comment by qzyse2017** [comment]
@mxschmitt it's Version 84.0.4147.125 (Official Build) (64-bit)

**Comment by mxschmitt** [comment]
I tried to reproduce it with chrome 84 on Windows with Browserstack, but was not able to. Is the issue for you still persistent? Which operating system do you have?

**Comment by qzyse2017** [comment]
It's opensuse Leap 15.1, I got the page on my working PC, I will try it again tommorrow morning, thanks  @mxschmitt

**Comment by qzyse2017** [comment]
@mxschmitt it is still persistent and there is no error logs in browser console

**Comment by pavelfeldman** [comment]
Works for me on Chrome 87! Looks like this is specific to your system since there are many docusaurus docs sites in the wild and they are all working fine...
