### ISSUE TITLE
[Question] How to disable bringing page to front during launching.

### ISSUE THREAD

**Issue by shirshak55** [microsoft/playwright#4822]
Its Headful mode.

Currently I am doing web chat tests where I would like to test multiple context. 

If I spawn new context it brings that page to front loosing the focus.

```js
let browser = await firefox.launch()

// Every 1 minute open new context and open page just to test if chat shows history or not.
while(true) {
  let context = await browser.newContext()
  let page = await context.newPage();
  
  // delay code is there not shown here.

}
```

The issue is that newContext spawns a new window which has focus or something is in page that is calling page.bringToFront() when its launched. 

Questions:
1. I would like to disable these behavior. If possible please let me know. 
2. Is there anyway to minimize the context window after launch. If I need to bring page to front I think i can call page.bringToFront() at the moment. 

Its not a new issue I think and there are no answers available afaik.
https://github.com/puppeteer/puppeteer/issues/5484
https://stackoverflow.com/questions/53501564/hide-browser-in-puppeteer

**Comment by creage** [comment]
Well, we have a plenty of chat testing, and we have no issues running multiple browser instances. We have tests up to 4 users chatting at the same time, with no issues.

What exact problem do you have?

**Comment by shirshak55** [comment]
@creage the issue is focus stealing. For 2-3 edge case we tests manually. When testing manually when we are typing browser come in front of face which is abit annoying.

**Comment by creage** [comment]
Oh, so you are not doing a real automation here then 😄

How about running instances you are not interested in, in HEADLESS mode? Or, as another option - lowering your VIEWPORT to some size that will allow you to fit multiple windows on your screen, positioning them in a custom way, so stealing focus should not distract you that much?

**Comment by pavelfeldman** [comment]
Playwright emulates all pages as focused, what exactly do you mean by focus stealing?

**Comment by pavelfeldman** [comment]
Ah, you mean your scenarios are hybrid and the focus is stolen from the person performing the manual steps? Can I ask why you are typing manually?

**Comment by shirshak55** [comment]
@pavelfeldman Yea its like when we are doing some work on one window and if another window is spawned focus is stolen from the person doing manual steps. Sometime we need to do it for accessibility check in headful mode and is mostly from devops team.

**Comment by pavelfeldman** [comment]
I don't think we can do anything about it (focusing), but we could try helping automating those a11y checks!

**Comment by shirshak55** [comment]
alright then I shall close this issue :) I also think its probably firefox or chrome issue 

Thanks.

**Comment by bstro** [comment]
I also experience this; its pretty annoying to have jest running with `--watch` while developing and have focus stolen away constantly by the playwright. It seems like it has to be possible to have an option to instruct playwright to open Chromium in the background, rather than foreground.

**Comment by ThatGuySam** [comment]
There's a command I figured out on macOS to start iOS Simulator in the background which reliably disables it from taking focus. 
```bash
open -g -a Simulator
```

However, I'm unsure how to launch Playwright's Chromium with this option

**Comment by sneko** [comment]
I was also surprised there is no way to prevent bringing it to front and loosing focus.

My workaround is to have "reusable pages" (1 if your program is simple, or X if you have a X as concurrency). You wait for a created page instance to be marked as available (with a mutex or so) to reuse it.

_Make sure to clear all listeners if you added some, or the storage if you don't want it's shared. It's a bit more at risk... but for now that's the only viable solution when `headless: true` does not fit the use case._

**Comment by Andrew-Chen-Wang** [comment]
This apparently really only affects chromium and only when launching a new page or launchPersistentContext. Added a PR: https://github.com/microsoft/playwright/pull/41282

**Comment by johnlshankman-privy** [comment]
bringing this back from the dead because this still affects me daily. is there no workaround anyone has found?

@Andrew-Chen-Wang still has an open PR https://github.com/microsoft/playwright/issues/41306

**Comment by Andrew-Chen-Wang** [comment]
@johnlshankman-privy Create a patches folder, and make a file. I use both playwright and patchright so:

`patches/patchright-core-no-focus.patch`:

```
diff --git a/lib/server/chromium/crBrowser.js b/lib/server/chromium/crBrowser.js
--- a/lib/server/chromium/crBrowser.js
+++ b/lib/server/chromium/crBrowser.js
@@ -315,7 +315,7 @@ class CRBrowserContext extends import_browserContext.BrowserContext {
     return this._crPages().map((crPage) => crPage._page);
   }
   async doCreateNewPage() {
-    const { targetId } = await this._browser._session.send("Target.createTarget", { url: "about:blank", browserContextId: this._browserContextId });
+    const { targetId } = await this._browser._session.send("Target.createTarget", { url: "about:blank", browserContextId: this._browserContextId, background: true, focus: false });
     return this._browser._crPages.get(targetId)._page;
   }
   async doGetCookies(urls) {
```

one more: `patches/playwright-core-no-focus.patch`

```
diff --git a/lib/server/chromium/crBrowser.js b/lib/server/chromium/crBrowser.js
--- a/lib/server/chromium/crBrowser.js
+++ b/lib/server/chromium/crBrowser.js
@@ -315,7 +315,7 @@ class CRBrowserContext extends import_browserContext.BrowserContext {
     return this._crPages().map((crPage) => crPage._page);
   }
   async doCreateNewPage() {
-    const { targetId } = await this._browser._session.send("Target.createTarget", { url: "about:blank", browserContextId: this._browserContextId });
+    const { targetId } = await this._browser._session.send("Target.createTarget", { url: "about:blank", browserContextId: this._browserContextId, background: true, focus: false });
     return this._browser._crPages.get(targetId)._page;
   }
   async doGetCookies(urls) {
```

in pnpm-workspace.yaml:

```yaml
patchedDependencies:
  "patchright-core@*": patches/patchright-core-no-focus.patch
  "playwright-core@*": patches/playwright-core-no-focus.patch
```

The `@*` entries in `pnpm-workspace.yaml` reapply the patches across versions,
including the installed Playwright alpha. Keep patch failures fatal: if an upgrade
changes the surrounding code, regenerate the affected patch with `pnpm patch`
and `pnpm patch-commit`, then restore the wildcard entry. Check headed page creation,
navigation, input, and macOS focus behavior after browser upgrades.
