### ISSUE TITLE
[Question] Where can I find default args used by playwright?

### ISSUE THREAD

**Issue by shirshak55** [microsoft/playwright#4823]
I checked on api docs regarding browser.launch(args) . In args object there is ignoreDefaultArgs but the issue is I don't know what what are the default args available.

Why I am asking?
Because docs mentions there is ignoreDefaultArgs but it doesn't mention what are those default args. 

What did I tried?
I tried searching on github search for ignoreDefaultArgs but I don't think I could find location where these default args are found. And source code looks huge already to find it.

Thanks.

**Comment by mxschmitt** [comment]
Here you can find the current default args, but they contain some logic:
- https://github.com/microsoft/playwright/blob/5faf6f9e69c2148e94c81675fb636eb31a02b5e7/src%2Fserver%2Fchromium%2Fchromium.ts#L78
- https://github.com/microsoft/playwright/blob/5faf6f9e69c2148e94c81675fb636eb31a02b5e7/src%2Fserver%2Ffirefox%2Ffirefox.ts#L51
- https://github.com/microsoft/playwright/blob/5faf6f9e69c2148e94c81675fb636eb31a02b5e7/src%2Fserver%2Fwebkit%2Fwebkit.ts#L44

Does this help you? Which arguments are you try to ignore? For the normal use cases ignoreDefaultArgs is not needed and should only used in advanced edge-case scenarios.

**Comment by shirshak55** [comment]
@mxschmitt it seems some args is causing firefox to steal focus.  I think playwright uses some arg like foreground or something like that.

**Comment by shirshak55** [comment]
Closing it as I think your answer is complete.

Thanks
