### ISSUE TITLE
[Feature] Perform actionability checks manually

### ISSUE THREAD

**Issue by terion-name** [microsoft/playwright#4824]
Many actions (like click, check, hover, etc) perform actionability checks before taking place. But it seems to be no way to perform these checks on your own, without performing actions. And if I need to check did some elements, for example, appear and became actionable - there is no way to do this.

Can an api for this added? Something like `element.actionable(checks: Array = ['visible', 'stable', 'enabled', 'receiving_events', 'attached']) : bool`

**Comment by pavelfeldman** [comment]
These landed, will be available in 1.8 (https://playwright.dev/docs/next/api/class-page#pageiseditableselector-options, etc)

**Comment by terion-name** [comment]
@pavelfeldman why doesn't it perform all available checks? Checks for enabled, editable and visible are present, checks for receiving events, attached and stable — not. So still one can't fully check if element is, for example, clickable

**Comment by luixo** [comment]
This is still true in 1.41.2 - no check for stability, attached and receiving events.
The only way I see is to run them combined with trial click invocation:
```ts
try {
  page.locator("...").click({ trial: true });
  return true;
} catch {
  return false;
}
```
