### ISSUE TITLE
[BUG] `request.postData()` output is distorted on webkit

### ISSUE THREAD

**Issue by frezot** [microsoft/playwright#4833]
**Context:**
- Playwright Version: 1.7.1
- Operating System: Mac (also reproduced in Ubuntu container)
- Node.js version: v12.18.3
- Browser: WebKit

**Code Snippet**

example available on https://github.com/frezot/pw-decoding-bug

**Describe the bug**

`request.postData()` output is wrong on webkit when contain Cyrillic symbols or emoji 

Or maybe exists some workaround for avoid this issue?

**Comment by mxschmitt** [comment]
Thanks for the report, seems like it was already filed in #4723 and fixed in #4744. Could you try the latest master version with `npm install playwright@next` to see if the issue is still persistent? Should typically be then in the next release in a few weeks.
Thanks!

**Comment by frezot** [comment]
@mxschmitt  thnx alot, works correct on `1.8.0-next.1609087451261`
