### ISSUE TITLE
[Question] Is it possible to save video by parts for one page?

### ISSUE THREAD

**Issue by niyarlatotep** [microsoft/playwright#4834]
Is it possible to save video by parts for one page. For example I run three cases in one page, but I want to  have three independent video files for each case. Is it possible somehow? As I understand now it's possible save only one video within the page.

**Comment by dgozman** [comment]
@niyarlatotep That's correct. We suggest to create a new context for every independent scenario, or a new page if multiple scenarios depend on each other. Does that work for your usecase?

**Comment by niyarlatotep** [comment]
@dgozman  No, actually I create one context before tests and then run tests in one context without recreating new contexts it's easier to me not to reinitialize the context. Actually I use playwright-video package and it accomplish my needs but it works only for chrome for now and I'd prefer to use native api instead of using separate package.

**Comment by dgozman** [comment]
@niyarlatotep What is the "initialization" you do in the context? Perhaps [`browserContext.storageState()`](https://playwright.dev/docs/api/class-browsercontext?_highlight=storage#browsercontextstoragestateoptions) will help? You can use it to save the storage state, and then later pass it to `browser.newContext()` as an option to get the "initialized" context right away.

**Comment by niyarlatotep** [comment]
@dgozman I see, in the case of using new context for each test I should create ```browser.newContext()``` in BeforEach fixture and close afterEach test in my case I can create context once and use it for all the tests I don't need strict isolation between contexts my tests run by one and I don't need splited contexts so it would be  convenient to me if I could run video recording and stop it when I'd like, for example I could do it using reporter when test starts record starting  when the test stop recroding stops. But I understand what you mean I can use creating context for each test to achieve this aim it's just not such convinient .

**Comment by pavelivanov** [comment]
@niyarlatotep hi, have you solved this?

**Comment by niyarlatotep** [comment]
@pavelivanov no, I have to create a new context in beforeach fixture and then close in in aftereach.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
