### ISSUE TITLE
[Question] Cannot launch chrome again after close the previous one

### ISSUE THREAD

**Issue by zyscoder** [microsoft/playwright#4847]
I launched a chrome instance and closed it.
~~~
const browserInstance = await playwright['chromium'].launch({
                headless: false
            });
await browserInstance.close();
~~~
When I try to launch a new instance again (rerun the code before.), something wrong happened and I cannot get a new instance. What should I do to address this problem?

**Comment by mxschmitt** [comment]
Do you have an error or stack trace what exactly went wrong or is not expected?

**Comment by JoelEinbinder** [comment]
Max asks a good question. Can you also provide your operating system and node version. We launch chrome browsers all the time in our tests, so there is likely something about your setup that is triggering this issue. Does it happen every time or only sometimes?

**Comment by zyscoder** [comment]
Sorry, this is my mistake. I removed the "disconnect" listener before I invoke the close function, and causes this result.
