### ISSUE TITLE
[Question]How to judge whether an element visble or not?

### ISSUE THREAD

**Issue by dld8888** [microsoft/playwright#4854]
pgge.querySelector('tbody>tr:nth-child(2)>input')
If it is not found, an error occurs, causing the script to break

Something like that：How can I tell if a selection box has been selected?
thank you

**Comment by pavelfeldman** [comment]
It is unclear what you are asking. Could you provide a snippet of the code and more context?

**Comment by pavelfeldman** [comment]
https://playwright.dev/docs/actionability/#assertions - I hope this is what you are looking for. Please feel free to open new issues with additional details!
