### ISSUE TITLE
[Question] How to handle dialog box (promptUserAndPass) which shows up when landing on page

### ISSUE THREAD

**Issue by leochung042** [microsoft/playwright#4859]
Hi All

Currently, I facing this directly showing up dialog box when landing on page.
How do we handle dialog box popup when landing on the page without any click event.
Also the dialog needs to be enter username and password.

Thank you,
Leo

**Comment by pavelfeldman** [comment]
Should be something like

`page.on('dialog', dialog => dialog.accept())`

before you navigate.

**Comment by pavelfeldman** [comment]
We need your response to act on this, please feel free to open a new issue with more details!
