### ISSUE TITLE
[Question] How does Playwright communicate with browsers?

### ISSUE THREAD

**Issue by suryagh** [microsoft/playwright#4862]
I understand Playwright does not use Selenium. So, does Playwright use DevTools protocol to interact with browsers? I could not find much detail on how cross-browser is accomplished. 

Is it DevTools? (+ something else too / browser-by-browser basis?) Any thoughts or comment is highly appreciated (Please feel free to point me to and doc/write-up, if there is one)

Thank you!

**Comment by JoelEinbinder** [comment]
We use the DevTools Protocol to communicate with Chromium. For Firefox and WebKit, we implemented on our own protocols similar to the chrome one. You can find these in the [browser_patches](https://github.com/microsoft/playwright/tree/master/browser_patches) folder.
