### ISSUE TITLE
[Feature] Include browser audio with recordVideo

### ISSUE THREAD

**Issue by NithinSGowda** [microsoft/playwright#4870]
_recordVideo_ currently enables us to record just screen-video
Please add an extra option to record browser audio along with the screen recording

Please let the audio input be the browser's audio and not the mic. Or else provide a selection attribute to select between them

**Comment by panabee** [comment]
This is extremely valuable and allow us to abandon Puppeteer altogether.

The use case is to turn JavaScript/CSS animations, plus accompanying audio, into a video.

Many users are requesting this.

It would be awesome to use Playwright for this use case.

**Comment by panabee** [comment]
@aslushnikov 
This is an urgent use case, so we could also implement the changes ourselves and issue a PR if you could provide guidance on what to do.

**Comment by danisharora099** [comment]
> @aslushnikov
> 
> This is an urgent use case, so we could also implement the changes ourselves and issue a PR if you could provide guidance on what to do. To clarify, the need is to let servers convert JavaScript/CSS animations, plus accompanying audio, into a WebM video.
> 
> Would the solution be similar to what you described for exposing **getUserMedia** in Puppeteer? [puppeteer/puppeteer#3761 (comment)](https://github.com/puppeteer/puppeteer/issues/3761#issuecomment-454219874)

Hey panabee, any luck with finding potential help?
I'm looking for something very similar too - I want my (headless) Chromium to screen+audio-record the website  - do you have any directions for this?

**Comment by panabee** [comment]
Nothing yet @danisharora099, but happy to pay someone to build this functionality. Anyone interested?

**Comment by pavelfeldman** [comment]
We concluded that this is outside of the scope for Playwright, so closing it as WontFix.

**Comment by hexabyte23** [comment]
As Microsoft concluded than record audio is out of their scope, I conclude than playwright will be out of usage and I continue to use  puppeteer... kind of curious position for a challenger !

**Comment by emircanerkul** [comment]
@pavelfeldman it's quite a weird conclusion. Playwright is a testing tool but we can not test audios..

**Comment by WestonThayer** [comment]
I'm new to xvfb, only have a high level understanding. @danisharora099 is my understanding correct that the xvfb approach works natively on a Linux CI runner, but to run it locally on macOS, you'd need to do it in a Docker container or similar?

**Comment by sourabh-goyal-kasitech** [comment]
> been a while since i had this issue, but the way i made it work for myself was to use xvfb + headless chromium (puppeteer tho)

Need some help with this @danisharora099

**Comment by apis3445** [comment]
I Would like to include the audio on the video recording to improve the accessibility of the video errors but maybe I need to ressearch another options
