### ISSUE TITLE
page.exposeBinding passing an element handle ERRO

### ISSUE THREAD

**Issue by selang** [microsoft/playwright#4872]
playwright version 1.7.1

Failed to run the example
REF: https://playwright.dev/docs/api/class-page#pageexposebindingname-playwrightbinding-options

> await page.exposeBinding('clicked', async (source, element) => {
>   console.log(await element.textContent());
> }, { handle: true });
> await page.setContent(`
>   <script>
>     document.addEventListener('click', event => window.clicked(event.target));
>   </script>
>   <div>Click me</div>
>   <div>Or click me</div>
> `);

Google Chrome console reports error :
`Uncaught (in promise) elementHandle.textContent: dispatcher[method] is not a function`

**Comment by mxschmitt** [comment]
I can reproduce that, full example: https://try.playwright.tech/?s=vf8khy5

**Comment by aslushnikov** [comment]
> I can reproduce that, full example: https://try.playwright.tech/?s=vf8khy5

@mxschmitt It would be super helpful if we could pick a Playwright version there (to help bisecting)
