### ISSUE TITLE
[Feature] Ability to listen to HTTP responses of childFrames

### ISSUE THREAD

**Issue by goleary** [microsoft/playwright#4874]
Using the chrome debugger I'm able to observe requests/responses that initiate from childFrames (iframes) of the page that I am inspecting.

With playwright, when I use 

```
page.on('response', response =>
    console.log('<<', response.status(), response.url()));
```
It does not appear to register any responses from requests that are initiated from childFrames.  Is this intended?

**Comment by aslushnikov** [comment]
@goleary no, this is not intended. Can you share a link to the website so that we can reproduce this locally?

**Comment by goleary** [comment]
Thanks for responding! Good to know iframe responses should also be captured.

Looks like I may be running into a different issue with this particular site, I need to do some additional digging. Feel free to close this in the meantime and I'll report back if the problem seems to be with Playwright instead of the site itself.

**Comment by goleary** [comment]
@aslushnikov 
I'm not sure if this is related, but this [url ](https://www.newyorker.com/podcast/the-new-yorker-radio-hour/bruce-springsteen-in-conversation-with-david-remnick) seems to crash `chromium` in `headless: false` mode.  It doesn't crash when in headless mode and also does not crash `firefox` (in either mode).

The page itself was failing to make the request that I was listening for, but when I use firefox it works as expected.
