### ISSUE TITLE
[BUG] The page.frames() doesn't return all frames

### ISSUE THREAD

**Issue by kanishkadistill** [microsoft/playwright#4890]
**The page.frames() doesn't return all frames and Navigation does not happen for iFrame with src=javascript:void(0)**
- Playwright Version: 1.7.1
- Operating System:  18.04.5 LTS
- Node.js version: 12.20.0
- Browser:  Chromium

```
    let browserType = 'chromium';
    const browser = await playwright[browserType].launch({
        headless: false
    });
    const context = await browser.newContext();
    const page = await context.newPage();
    page.on("frameattached", async (frame) => {
        let url = await frame.evaluate("window.frameElement?.getAttribute('src')");
        console.log("frameattached Eval", frame._guid, "src:", url);
    });
    page.on("framenavigated", (frame) => {
        console.log("framenavigated",frame._guid, frame.url());
    });

    await page.goto('http://localhost:8081/frames.html');
    let fUrls = page.frames().map((f) => f.url());

    console.log("frames", fUrls);
```
**frames.html**
```
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8" />
  <title>Page with frames</title>
</head>

<body>
  <iframe src="javascript:void(0)"></iframe>
  <iframe src="about:blank"></iframe>
</body>
</html>
```

**Bugs**
1.The navigation event should be triggered for all the frames but it did not happen for  `<iframe src="javascript:void(0)"></iframe>`

2.The page.frames() should contain all the frames but `<iframe src="javascript:void(0)"></iframe>` is missing in the list.

**Expected Results:**
```
framenavigated Frame@9df46bfb06b531c72fc35f8b0753e662 http://localhost:8081/frames.html 
framenavigated Frame@510fbadb78219a924d2ef1f263da7c5c about:blank 
frameattached Eval Frame@510fbadb78219a924d2ef1f263da7c5c  src: about:blank
frameattached Eval Frame@f55a258427af1bafe3e4e2ead0809073  src: javascript:void(0)
framenavigated Eval Frame@f55a258427af1bafe3e4e2ead0809073  src: javascript:void(0)
frames [ 'http://localhost:8081/frames.html', '', 'about:blank', 'javascript:void(0)' ] 
```

**Actual Results:**
```
framenavigated Frame@9df46bfb06b531c72fc35f8b0753e662 http://localhost:8081/frames.html 
framenavigated Frame@510fbadb78219a924d2ef1f263da7c5c about:blank 
frameattached Eval Frame@510fbadb78219a924d2ef1f263da7c5c  src: about:blank
frameattached Eval Frame@f55a258427af1bafe3e4e2ead0809073  src: javascript:void(0)
frames [ 'http://localhost:8081/frames.html', '', 'about:blank', ] 
```

**Comment by JoelEinbinder** [comment]
The lack of a navigation is actually a quirk of how iframes work. Loading `src="about:blank"` will queue a navigation, whereas src="javascript:void(0)" keeps the same initial document and then runs some javascript in there.

So I'd expect to see two navigations, one for the main frame and one for the frame navigated to `about:blank`.
And then I'd expect to see two `frameattached` events, one for each of the iframes.
and lastly I'd expect to see three frames returned by `page.frames()`. The main frame set to `frames.html`, a frame with the initial blank document, and a frame navigated to `about:blank`.

This matches your results, so I think everything is working as intended.

Is there something broken in your test/app? Maybe the current results are not useful for some usecase.

**Comment by kanishkadistill** [comment]
I see,
Thanks, @JoelEinbinder.
You can close the issue.
