### ISSUE TITLE
[BUG] Links in Docker docs broken

### ISSUE THREAD

**Issue by jamesgorrie** [microsoft/playwright#4892]
**Context:**
- Playwright Version: 1.7.1
- Operating System: All
- Node.js version: N/A
- Browser: N/A
- Extra: N/A

**Describe the bug**

[Documentation in docker hub](https://hub.docker.com/_/microsoft-playwright?tab=description) has become out of date with updates to this repo. They should be updated. 

It seems as thought there was a time where markdown files didn't have `.md` extensions. It's hard to tell as the history to these files aren't easily accessible in GitHub.

**Comment by JoelEinbinder** [comment]
@pavelfeldman looks like cleanup after you moved all the docs around.

**Comment by mxschmitt** [comment]
Maybe by that it can also be added that there exists an Ubuntu 20 image.

**Comment by jamesgorrie** [comment]
Another option would be to use [automated builds](https://docs.docker.com/docker-hub/builds/#understand-the-build-process) which would then take the README file from repo.

Not sure if that's something that would be desired though, as I am new to the repo.

**Comment by aslushnikov** [comment]
Links are working now!
