### ISSUE TITLE
[BUG] selectOption doesn't auto-wait for the options being selected

### ISSUE THREAD

**Issue by russelldavis** [microsoft/playwright#4921]
Playwright docs talk a lot about reliable execution by auto-waiting for elements to be ready. Unfortunately `selectOption` doesn't live up to that. It does auto-wait for the given selector, but not for the values to be found inside that selector. E.g:

```javascript
  await page.selectOption('#my-select', {label: "badlabel"});
```

**Desired behavior**: `selectOption` waits until `badlabel` can be found, eventually throwing a TimeoutError.

**Actual behavior**: If `#my-select` is found, but `badlabel` is not, `selectOption` immediately clears the selection in `#my-select` and returns without throwing an error.

The current behavior leads to flaky executions in pages where options are dynamically added to `select` elements.

Even worse, it can lead to confusing and dangerous bugs by causing the wrong element to be selected. After clearing the selection on a select element (like `selectOption` does when there's no match), the next element added to the dropdown will automatically become the selection.

So you can end up with an arbitrary option in the dropdown being mistakenly selected. Imagine that  causing the wrong record in a database to be updated, or even deleted. Something similar to that just happened to me.

### Compatibility

Not sure the best way to handle backwards compatibility. Maybe make a new `selectOptionWait` function and deprecate the old one, or at least strongly recommend using the new one?

**Comment by JoelEinbinder** [comment]
Do you have an example of a website where options are added to a select after a delay? It's my experience that the selects are usually created with all the options intact. Maybe there's something else about this pattern that we can use as a signal.

**Comment by JoelEinbinder** [comment]
Here is a snippet to wait for the target option to appear before selecting it:
```js
await page.waitForFunction(() => {
  const select = document.querySelector('#my-select');
  if (!select)
    return false;
  return [...select.options].some(x => x.label === 'badlabel');
});
await page.selectOption('#my-select', {label: 'badlabel'});
```

**Comment by russelldavis** [comment]
Thanks, I ended up writing a helper function that does something similar.

I don't have an example offhand, other than the site I'm working on (it requires a login and has sensitive data, so I can't share it). It's a jamstack app — static html that starts out with an empty `<select>` element (well, it actually has one disabled option that says "Select an option"), then makes an API call and populates it with the results.

**Comment by JoelEinbinder** [comment]
Interesting. I would expect the `<select>` to be marked as disabled rather than having one disabled option. I think we should wait to see if other people are running up against sites that use this pattern. Maybe we could special case select boxes where every option as disabled and consider them to be disabled.

**Comment by dgozman** [comment]
I think the fact that `selectOption` does not throw when option is not found is a bug. @JoelEinbinder, wdyt? If so, waiting for the option makes sense.

**Comment by mkorpela** [comment]
Same reported to our project https://github.com/MarketSquare/robotframework-browser/issues/630 .. so would be great if changed in upstream.

**Comment by mkorpela** [comment]
Both this and our issue are rather new. Could this be a regression?

**Comment by nrayburn-tech** [comment]
Another example would be when the options of one dropdown, depends on another.
Picking a country first, this triggers a fetch request to fill the state dropdown.

**Comment by russelldavis** [comment]
Thanks for the fix!
