### ISSUE TITLE
How to modify element attributes?[Question]

### ISSUE THREAD

**Issue by dld8888** [microsoft/playwright#4924]
I have an element that contains the readonly attribute. How can I delete this attribute? For example:
\<input> datainput readonly="readonly"\</input>

How to delete or modify the readonly attribute?
Is it similar to set_elementAttrib() method？
Thank you

**Comment by creage** [comment]
I wonder what are you testing by removing attributes from DOM - this should be some edge scenario, but you can use native [`Element.removeAttribute()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/removeAttribute).

Combine it with [`jsHandle.evaluate()`](https://playwright.dev/docs/api/class-jshandle#jshandleevaluatepagefunction-arg), so you'd have something like this
```js
const elementHandle = await page.$('.myelement');
await elementHandle.evaluate(node => node.removeAttribute('readonly'));
```

**Comment by mxschmitt** [comment]
Can be also done like `await page.$eval(".myelement", el => el.removeAttribute("readonly"))`

**Comment by JoelEinbinder** [comment]
This answers look right. Closing this issue to remove it from our queue.

**Comment by danielcassiano** [comment]
```
const elementHandle = await page.$('.myelement');
await elementHandle.evaluate(node => node.value = "false");
```
