### ISSUE TITLE
[Question] Build WebKitGTK failed

### ISSUE THREAD

**Issue by zyscoder** [microsoft/playwright#4925]
**Context:**
- Playwright Version: release-1.7
- Operating System: Ubuntu20.04
- Node.js version: 15.5.0
- Browser: WebKit
- Extra: none

**Describe the bug**
I checkout out Webkit and try to build it, but an error accurs.
```
FAILED: docs-build-no-html.stamp 
cd /home/zys/Toolchains/playwright/browser_patches/webkit/checkout/WebKitBuild/GTK/Release && /usr/bin/cmake -E env CC=/usr/bin/cc "CFLAGS=-fdiagnostics-color=always -Wextra -Wall -Wno-expansion-to-defined -Wno-psabi -Wno-misleading-indentation -Wno-maybe-uninitialized -Wwrite-strings -Wundef -Wpointer-arith -Wmissing-format-attribute -Wformat-security -Wcast-align -Wno-tautological-compare  -fno-strict-aliasing -fno-exceptions -Wno-unused-parameter" "LDFLAGS=-L/home/zys/Toolchains/playwright/browser_patches/webkit/checkout/WebKitBuild/GTK/DependenciesGTK/Root/lib -L/usr/local/lib -fuse-ld=gold -Wl,--disable-new-dtags" /usr/bin/python2.7 /home/zys/Toolchains/playwright/browser_patches/webkit/checkout/Tools/gtkdoc/generate-gtkdoc --gtk --skip-html && touch docs-build-no-html.stamp
Traceback (most recent call last):
  File "/home/zys/Toolchains/playwright/browser_patches/webkit/checkout/Tools/gtkdoc/generate-gtkdoc", line 254, in <module>
    build_gtkdoc_for_wkgtk(arguments)
  File "/home/zys/Toolchains/playwright/browser_patches/webkit/checkout/Tools/gtkdoc/generate-gtkdoc", line 208, in build_gtkdoc_for_wkgtk
    saw_warnings = generate_documentation(jsc_generator)
  File "/home/zys/Toolchains/playwright/browser_patches/webkit/checkout/Tools/gtkdoc/generate-gtkdoc", line 158, in generate_documentation
    return generate_doc(generator, arguments.skip_html)
  File "/home/zys/Toolchains/playwright/browser_patches/webkit/checkout/Tools/gtkdoc/generate-gtkdoc", line 145, in generate_doc
    generator.generate(not skip_html)
  File "/home/zys/Toolchains/playwright/browser_patches/webkit/checkout/Tools/gtkdoc/gtkdoc.py", line 146, in generate
    self._run_gtkdoc_scan()
  File "/home/zys/Toolchains/playwright/browser_patches/webkit/checkout/Tools/gtkdoc/gtkdoc.py", line 311, in _run_gtkdoc_scan
    self._run_command(args)
  File "/home/zys/Toolchains/playwright/browser_patches/webkit/checkout/Tools/gtkdoc/gtkdoc.py", line 196, in _run_command
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[6533/6727] Generating ../../WebKit2-4.0.gir
../../../../../Source/WebKit/UIProcess/API/glib/WebKitWebView.cpp:2209: Warning: WebKit2: multiple comment blocks documenting 'WebKitWebView::show-option-menu:' identifier (already seen at WebKitWebView.cpp:2173).
../../../../../Source/WebKit/UIProcess/API/glib/WebKitWebView.cpp:2209: Warning: WebKit2: incorrect number of parameters in comment block, parameter annotations will be ignored.
ninja: build stopped: subcommand failed.
```

Here is my step:
```
cd playwright
git checkout release-1.7
cd browser_patches
./prepare_checkout.sh webkit
cd webkit
./build.sh --gtk
```

By the way, I have tried to build a playwright instrumented WebKitGTK on Ubuntu20.04 but failed several times. Would you mind showing me the step to build an AddressSanitizer & playwright instrumented WebKitGTK on Ubuntu20.04?

**Comment by yury-s** [comment]
We are building on Ubuntu 20.04 and 1.7 branch clearly works their, something is wrong with your setup. You may want to try
```bash
./browser_patches/webkit/build.sh --full
```
which will install some required dependencies. But the error looks odd I haven't seen it in our builds.

> Would you mind showing me the step to build an AddressSanitizer & playwright instrumented WebKitGTK on Ubuntu20.04?

We don't build webkit with ASan. You can follow the instructions on webkit.org to build with ASan support, they should work with our patches just fine.

**Comment by zyscoder** [comment]
I tried many ways to build playwright instrumented ebkitgtk on ubuntu20.04:
(1) Use ``` //browser_patches/webkit/patches/bootstrap.diff``` to patch webkit and build it following [the offical way].(https://trac.webkit.org/wiki/BuildingGtk)
(2) Checkout webkit  ```//browser_patches/prepare_checkout.sh webkit``` and run ```//browser_patches/webkit/build.sh --full``` or  ```//browser_patches/webkit/build.sh --gtk``` to build it.
However, all the way failed, and I haven't tried to instrument asan till now.
I aim to do some tests on WebKit but stuck in building WebKit with playwright, would you mind have a try to build it on ubuntu20.04?

**Comment by zyscoder** [comment]
I tried ```build.sh --full``` again and succeeded this time. I have thought I can run set up WebKit with ```pw_run.sh``` like a normal browser but it exits immediately without any error or debug information. I then tried to set up it with``` browser.launch``` in playwright and it works.
