### ISSUE TITLE
[BUG] browserContext.cookies([urls]) doesn't work when URLs are specified

### ISSUE THREAD

**Issue by honglax** [microsoft/playwright#4927]
**Context:**
- Playwright Version: 1.7.0
- Operating System: macOS 10.15.7
- Node.js version: 12.18.4
- Browser: All
- Extra: None

**Code Snippet**
```javascript
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch()
  const page = await browser.newPage()
  const URL = 'https://google.com.vn/'
  await page.goto(URL)
  const cookies = await page.context().cookies(URL)
  cookies.map((cookie) => console.log(JSON.stringify(cookie)))
  await browser.close()
})();
```

**Describe the bug**

When the URLs params are specified, this method can not get any cookies that affect those URLs (e.g: **https://google.com.vn**) while If no URLs are specified, this method returns all cookies of **https://google.com.vn**

**Comment by mxschmitt** [comment]
Seems like there is a bug in the implementation for cookies which are for the subdomain too (start with a dot). Good catch, reproducible example here: https://try.playwright.tech/?s=ud7psdf

**Comment by honglax** [comment]
Are you going to have the plan to fix it?

**Comment by honglax** [comment]
I've tried with `Playwright@next` but it seems to be unstable between browser. When I used `webkit`, the returned cookies is consistent between `await page.context().cookies()` and `await page.context().cookies([urls])`. But when I used `chromium` and specified `urls` like below lines of code

```javascript
const { chromium } = require('playwright')

;(async () => {
  const browser = await chromium.launch()
  const page = await browser.newPage()
  const URL = 'https://google.com/'
  await page.goto(URL, { waitUntil: 'load' })

  const cookies = await page.context().cookies(URL)
  for (const cookie of cookies) {
    console.log(JSON.stringify(cookie))
  }
  await browser.close()
})()
```
I just got 1 cookie instead of 2.

**Comment by yury-s** [comment]
AFAICT this is real difference in how Google treats different browsers, for Chromium the cookies are:

```js
[
  {
    sameSite: 'None',
    name: '1P_JAR',
    value: '2021-01-13-20',
    domain: '.google.com',
    path: '/',
    expires: 1613163581.10335,
    httpOnly: false,
    secure: true
  },
  {
    sameSite: 'None',
    name: 'NID',
    value: '207=da537BAs334iEZsruF2GkVN_AsxJLaHyqd8lIIGPRSoHYQgjWevtNFLLJY9oF_G7LHnPPThwVlW-iQENHYhqIfH71uXt_f0gzXJNXkwDsWzY2CyKGyYp7DZTv7hcWsLH7KVf_-7T2aRDmPVLZHoyH-U72iVgp9_Z19U1y74dKAY',
    domain: '.google.com',
    path: '/',
    expires: 1626382780.648371,
    httpOnly: true,
    secure: false
  }
]
```
Note that first one is `secure: true` and second is     `secure: false` whereas for WebKit both are `secure: true`:

```js
[
  {
    sameSite: 'None',
    name: '1P_JAR',
    value: '2021-01-13-20',
    domain: '.google.com',
    path: '/',
    expires: 1613163581.10335,
    httpOnly: false,
    secure: true
  },
  {
    sameSite: 'None',
    name: 'NID',
    value: '207=da537BAs334iEZsruF2GkVN_AsxJLaHyqd8lIIGPRSoHYQgjWevtNFLLJY9oF_G7LHnPPThwVlW-iQENHYhqIfH71uXt_f0gzXJNXkwDsWzY2CyKGyYp7DZTv7hcWsLH7KVf_-7T2aRDmPVLZHoyH-U72iVgp9_Z19U1y74dKAY',
    domain: '.google.com',
    path: '/',
    expires: 1626382780.648371,
    httpOnly: true,
    secure: false
  }
]
```

When filtering by '**https**://google.com/' you'll only get secure cookies.

**Comment by honglax** [comment]
Thanks for your information.
