### ISSUE TITLE
[Feature] Add browser executables to PATH in Docker image

### ISSUE THREAD

**Issue by disintegrator** [microsoft/playwright#4929]
It would be great if we can use the docker image as a means to launch browsers and orchestrate them from our host machines. To make this process ergonomic, we would need to symlink the browser executables located under `/home/pwuser/.cache/ms-playwright/*` to somewhere in PATH. This would allow the following convenient invocation for example:

```
docker run \
	-it --rm --ipc=host --user pwuser --security-opt seccomp=seccomp_profile.json \
	mcr.microsoft.com/playwright:focal \
	chrome --headless --remote-debugging-port=4444
```

**Comment by mxschmitt** [comment]
This would only work with Chromium, a better approach would be using BrowserType.launchServer(), see here for more information: https://playwright.dev/docs/api/class-browsertype?_highlight=wsend#browsertypelaunchserveroptions

Would that work for your use case?

**Comment by disintegrator** [comment]
@mxschmitt oh i totally missed that! Thanks for the tip 🔥
