### ISSUE TITLE
[Feature] Axis and table selectors

### ISSUE THREAD

**Issue by dgozman** [microsoft/playwright#4935]
Extracted from https://github.com/microsoft/playwright/pull/4923#issuecomment-756362951, by @Aaron-Pool

---

Consider this example:
![image](https://user-images.githubusercontent.com/5634834/103940272-1092c680-50fb-11eb-926d-39a191821f11.png)

This is not a site that I control the layout of, I'm just trying to automate a task I need to perform on it/scrape it for data. The elements are not labeled in a semantic way and both the section header and whatever element contains "value" are a simple span element. To keep the task from being prone to breakage, I really just want the selector equivalent of "I want whatever is vertically aligned with this label, to its right".

**Comment by falcon030** [comment]
Maybe this is what you are looking for:  relative/proximity selectors mentioned in https://github.com/microsoft/playwright/issues/2877?

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
