### ISSUE TITLE
[Feature] Payment Request API

### ISSUE THREAD

**Issue by zhiyi01** [microsoft/playwright#4941]
I want to autofill the payment cart infomation,but I can't do it by 'page' api.

open [https://googlechrome.github.io/samples/paymentrequest/credit-cards/](https://googlechrome.github.io/samples/paymentrequest/credit-cards/), and click the 'bug' button

**Comment by JoelEinbinder** [comment]
We don't currently have a solution for this. Re-framing your question as a feature request:

The [Payment Request API](https://developer.mozilla.org/en-US/docs/Web/API/Payment_Request_API) pops up a dialog with many fields. We should have a way to intercept this dialog and fulfill it with information from the user.

**Comment by zhiyi01** [comment]
I try to resolve this problem but i found that Chrome Devtools Protocol maybe didn't support it. Can you give me some suggestion ? Thx

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
