### ISSUE TITLE
[BUG][Electron] page.waitForSelector : Passed function is not well-serializable!

### ISSUE THREAD

**Issue by Jinul** [microsoft/playwright#4961]
I am using version 1.7,1

I am trying this code  `const productPage = await page.waitForSelector('.products', { state: 'visible' });`

But I am getting this error page.waitForSelector : Passed function is not well-serializable!

Can someone please help with this? 

Thank you

**Comment by Jinul** [comment]
I tested the same code with a standalone node app, which is working fine. I faced this issue only while working with the electron renderer process. I believe this happened because of some v8 limitations.

**Comment by yury-s** [comment]
@Jinul can you share your code snippet, I couldn't reproduce the error with a simple test case?

**Comment by aslushnikov** [comment]
Closing this due to lack of feedback and big stream of bugs. Please feel free to reopen with more details if this is still an issue for you!

**Comment by hiko-vietduong** [comment]
It still happen, any update for this one?

**Comment by dhxkgozj** [comment]
Add an 'unsafe-eval' to the electron render index.html.

`<meta
http-equiv="Content-Security-Policy"
content="script-src 'self' 'unsafe-inline' 'unsafe-eval'"
/>`


I solved it like this.
