### ISSUE TITLE
[Feature] Expose Trace-Viewer as a static web application available in Playwright documentation page.

### ISSUE THREAD

**Issue by domderen** [microsoft/playwright#4967]
Playwright has a CLI command for showing the Trace Viewer web application, that helps visualize the steps a Playwright script executed. This can be useful for debugging broken tests, by visually inspecting why the test broke. 

I'd like to avoid the need to download the tracer file for my test session, and viewing my trace via the CLI command, and instead I would like to be able to display such session in a public web app, by providing a url to my tracer log file. 

For example, the Trace Viewer could be hosted at the address: https://trace-viewer.playwright.dev/ and I would like to pass a url to my trace log file as a url parameter: `?tracePath=https://some-domain.com/trace_logs.zip`. The Trace Viewer web app could then load the file via an XHR request, and allow debugging my Playwright script.

What do you think about such a solution? Would others find it useful? I think that way we could pass artifacts from CI systems directly to the static web app for rendering.

**Comment by dgozman** [comment]
There are some issues to sort out for this scenario:
1. We currently postprocess the trace: render video thumbnails, render action previews on demand. I imagine this could be solved with not-so-static server, or with pre-processing on the client side instead.
2. Existing snapshot technology requires playwright routing fore precise control over iframe origins and headers. This requires investigation, perhaps some smart service worker could help?

**Comment by domderen** [comment]
Yeah that might be complicated. My personal preference would be to go with pre-processing on the client side. If I were to use a hosted website like that, I'd like my files be processed only by my machine, rather than sending them to the server.

Regarding your second point, that's an interesting thought with trying a service worker. I was wondering it that might require some modification of the snapshot content, to replace iframes with a "shadow-dom" wrapper, so that they can be rendered bypassing the request.

**Comment by dgozman** [comment]
> Regarding your second point, that's an interesting thought with trying a service worker. I was wondering it that might require some modification of the snapshot content, to replace iframes with a "shadow-dom" wrapper, so that they can be rendered bypassing the request.

This could be possible, however we should be careful about link resolutions. For example, `<script src='foo.js'>` resolves relative to the base url of the iframe, so some careful processing is required. More complex example would be `background: url(foo.png)` in the css file that is also relative to the iframe base.

**Comment by domderen** [comment]
I tried understanding how the current route handling logic works, and what would need to change to handle it client-side only. Below I list the steps, as I understand them, that trace-viewer is performing to render the snapshot.

1. The SnapshotTab React component is loaded in the trace-viewer web app. This component creates an iframe element on the page.

2. User selects an action event which is passed to the SnapshotTab component, and this runs an effect that calls window.renderSnapshot(actionEntry.action).

> This step would have to be converted into following steps:

> a) Resources & frames from this action and this action’s snapshot are loaded into Cache API inside the browser with keys set to the request url. This would create a cache of resources that service-worker would be able to access. This would require access to snapshotRouter from the client code.

> b) A new ServiceWorker would have to be loaded into the page, with fetch event listener, capable of routing all requests coming from the iframe, to resources loaded inside the Cache.  

**Open question: Looks like ServiceWorkers can only be registered to control pages within the same origin, so to handle requests from the iframe, those requests would have to be made to the same origin. Otherwise, they would not be caught in the fetch event handler. As far as I can see, it is not possible to register a service-worker to operate in a scope of different origin. So it looks like we would still need to rewrite the iframe content (and content of resources loaded inside an iframe), to modify all links to also be same-origin requests. Am I getting it right, or is there some other workaround for this?**

3. Inside the renderSnapshot bounded function, the snapshotRouter instance is initialied with the snapshotObject from the selected action, and the iframe inside the react component is navigated to the url of the first frame in the snapshot object.

> This step would have to be converted to changing the src attribute on the iframe loaded inside the SnapshotTab React component to the url of the first frame in the snapshotObject.

4. Next, Playwright has a route handler for all requests from the web app, and all requests sent from inside the iframe, are handled by snapshotRouter’s route method.

> This step would be converted into the fetch event handler inside the service worker that was loaded before initiating the first request from the iframe. This handler would have to load resources from Cache based on the url, and potentially add headers from NetworkEvent.

5. Inside the route method, we first check if requested url is a url to one of the frames stored in the snapshot object. If true, we return the html blob directly.

6. Otherwise, we try to find a snapshot file for this resource, by finding the resource using the request url, and then identifying sha1 associated with that resource. In some cases resources might be overridden on the fameSnapshot level. In that case, a new sha1 might be found in the frameSnapshot.resourceOverrides array by url.

7. The response sent to the server is also accompanied by response headers associated with that resource network event.

> Logic from the last three steps would exist inside the service-worker’s fetch handler and load resources from Cache inside the service-worker.

What do you think about it, does my understanding makes sense?

**Comment by jeff1985** [comment]
Is there any alternative approach for a non dev to view the traces without the need to operate command line? Web interface would be the best, but maybe there is more?

**Comment by neil-morrison44** [comment]
My request was merged into this one since it's similar, I'm wanting a way to make a deployable web bundle (html, js, css) out of the trace + the trace viewer so I can auto-deploy it and put a link to it in my (failing) PR runs.

I don't think your playwright hosted web app suggestion would cover my CI use case though

**Comment by Evilweed** [comment]
Not sure if described here feature request is exactly what i think it is, but case in our company is as follows.

We have our own WEB internal tool that gets all the artifacts and data from E2E tests ran on Google Cloud Run instantly after each test passes or fails. In current solution we can immediately start debugging (videos, outputs and so on) in our WEB internal tool (with many more features, like stability checks and so on). We do not require our dev team to download any files and run cli commands to start debugging. 

Can you provide a way to render your cli viewer on a website and just use it there. Embed it for example as plain js or react component. We would add it to our internal tool and allow instant debugging in an environment where we can add even more helpful features to our developers.

**Comment by neil-morrison44** [comment]
@Evilweed That sounds more like what I was suggesting here https://github.com/microsoft/playwright/issues/9026

You could deploy the traces as pages then link / iframe them into your report rather than a 3rd party website where you still have to upload the trace (which I think is what this issue suggests) or run the cli.

**Comment by pavelfeldman** [comment]
This is now done, we'll provide more details as a part of the release notes.

**Comment by kjr-lh** [comment]
Is it still planned to have the trace viewer as part of the static site rather than needing the `show-report` command?

**Comment by mxschmitt** [comment]
It's already a static site which you can host yourself, see here: http://trace.playwright.dev/

(source is located [here](https://github.com/microsoft/playwright-trace))

**Comment by kjr-lh** [comment]
Can this be included in the report directory? I want to be able to upload the html report directory to a web bucket after a build, but at the moment the trace viewer there doesn't work as it requires server side functionality

**Comment by mxschmitt** [comment]
The html report is not the same as the trace viewer. The html report does already contain a copy of the trace viewer but not vice-versa. With server side functionality, you are partly right. It needs to be accessed via a web-server (because we leverage ServiceWorkers which don't work when you open it locally via double click / `file://`).

It should work without any issues when you upload the playwright-report directory to a web bucket and access it by that, html report and clicking on traces should work as expected.

Will work on making the repository public later.

---

I'm locking this issue now, to reduce noise for the other subscribers to it. Please open a new issue if you still have questions or something does not work.
