### ISSUE TITLE
[BUG] launchPersistentContext hanging on "about:blank"

### ISSUE THREAD

**Issue by bb1234cp** [microsoft/playwright#4981]
**Context:**
- Playwright Version: 1.7.1
- Operating System: Mac
- Node.js version: v14.15.1
- Browser: Chromium

**Code Snippet**
```javascript
const {chromium} = require('playwright');

(async () => {
  const options = {
                  headless : false, 
                  userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/87.0.4280.77 Mobile/15E148 Safari/604.1'
                }

                const browser = await chromium.launchPersistentContext(`udd1`, options)
                var [page] = await browser.pages();
                await page.goto("https://www.google.com/");
})();
```

**Describe the bug**
Sometimes the browser hangs on "about:blank". I've tested and it seems that if I even console.log(browser), then it doesn't even log it when this occurs... The only way to get past this is to refresh the page by using CMD + R on my keyboard. I'm unsure why this is happening as it doesn't occur every time I run my code. It seems as if the browser isn't even launching as it doesn't log.

**Comment by yury-s** [comment]
> I've tested and it seems that if I even console.log(browser), then it doesn't even log it when this occurs...

Do you log it before ` var [page] = await browser.pages();` ?

Can you run the test with `DEBUG=pw:protocol` and show the log it prints when it gets stuck on about:blank?

**Comment by pavelfeldman** [comment]
We need more info to act on this, please feel free to open a new app.

**Comment by june07** [comment]
Ever figure this one out?!  I'm having the exact same problem.
