### ISSUE TITLE
[Feature] Support for Raspberry PI

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#4984]
Issue to see if there is an interest in using it on a Raspberry PI / ARM. 

Changes required: Add custom build targets.

Please vote up if so.

Came up here:
- #2834
- #2838
- #1243
- https://github.com/microsoft/playwright-python/issues/211

**Comment by kumaraditya303** [comment]
@mxschmitt For Raspberry PI there is aarch64 which is the new unstable version and armhf which is the older, curious to know which architectures are the part of this issue ?

**Comment by pavelfeldman** [comment]
I'll close this as not a goal for now.

**Comment by emiliogarza** [comment]
I would love to see this! Have a PI I want to delegate some browser testing stuff to.

**Comment by glops** [comment]
I made a Dockerfile to install playwright-python on Raspberry pi (chrome only).
[playwright-rpi4](https://github.com/glops/playwright-rpi4)

**Comment by YNedderhoff** [comment]
I am very interested in this 👍

**Comment by smoshsimp** [comment]
@glops 
> I made a Dockerfile to install playwright-python on Raspberry pi (chrome only).
> [playwright-rpi4](https://github.com/glops/playwright-rpi4)


Is there a way to get it working for webkit as well since you were able to get it working with Chromium? @YNedderhoff also appears to be interested in this (https://github.com/microsoft/playwright-java/issues/399)

**Comment by TLombard2** [comment]
I'm running raspbian on a raspberry pi 4b and changed the path playwright looks for chromium to the default chromium web browser that is included with raspbian. Playwright still expects to find chrome in /chromium-901522/chrome-linux so I just added those directories and moved all the files into the chrome-linux directory so the path looks like /usr/lib/chromium/chromium-901522/chrome-linux. Then I just use PLAYWRIGHT_BROWSERS_PATH=/usr/lib/chromium node yourapphere.js. I imagine you could just copy the included chromium files somewhere else too as changing the directories makes it so the web browser no longer points to chromium.

**Comment by aslushnikov** [comment]
For the record: Playwright v1.17+ supports Raspberry PI - see [1.17 release notes](https://github.com/microsoft/playwright/releases/tag/v1.17.0)
