### ISSUE TITLE
[BUG] route.fulfill doesn't update cookies from Set-Cookie header

### ISSUE THREAD

**Issue by yury-s** [microsoft/playwright#4987]
**Context:**
- Playwright Version: 1.8-next

**Code Snippet**

The following snippet works only in Chromium but not in Firefox or WebKit.

```javascript
  await page.route('https://example.com/', (route, request) => {
    route.fulfill({
      headers: {
        'Set-Cookie': 'name=value; domain=.example.com; Path=/'
      },
      contentType: 'text/html',
      body: 'done'
    });
  });
  await page.goto('https://example.com');
  expect(await context.cookies()).toEqual([{
    sameSite: 'None',
    name: 'name',
    value: 'value',
    domain: '.example.com',
    path: '/',
    expires: -1,
    httpOnly: false,
    secure: false
  }]);
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
