### ISSUE TITLE
[Question] Waiting for a selector with a specific index

### ISSUE THREAD

**Issue by 15alja** [microsoft/playwright#4995]
Given a page with the following code
```
<div>
  <span>span1</span>
</div>
<div>
  <span>span2</span>
</div>
```

What is the best way to access the 2nd span element with Playwright? The css selector `nth-of-type` is not what I'm looking for - I just want the 2nd instance of span in a generic way.

**Comment by yury-s** [comment]
The following snippet should get it:

```js
const span = (await page.$$('span'))[1];
```

**Comment by 15alja** [comment]
> The following snippet should get it:
> 
> ```js
> const span = (await page.$$('span'))[1];
> ```

Thanks, however this is not precisely what I'm looking for. I want to wait for this element with index 1 to appear, similar to `waitForSelector`.

**Comment by yury-s** [comment]
Why not use `waitForSelector`  then, can you tell more about your constraints ?

**Comment by 15alja** [comment]
`waitForSelector` waits for the first element matching a selector. Specifically, I want to wait for the k-th element matching a selector.

I snooped through some PRs and found that what I'm requesting was _removed_ in #4640, though I'm unsure why.

**Comment by dgozman** [comment]
We are working on the index selector, see issue #3697.

**Comment by 15alja** [comment]
@dgozman great, I'm excited to see that this is being worked on

For now, I accomplish it by continuously querying until it is found or timing out. It's a hacky approach that I would prefer to avoid, but do I have any better options for now?
