### ISSUE TITLE
[Question] How to simulate Drag and Drop upload a file

### ISSUE THREAD

**Issue by louis57** [microsoft/playwright#5001]
I am writing a test case to upload a file. Problem is, the drag and drop area doesn't have an Input (type="file") to receive the file. It looks like this:

![image](https://user-images.githubusercontent.com/12949146/104482012-b7c5a100-55c6-11eb-9961-b89754c7c63f.png)

```javascript
<div ref="fileDrop" class="fileSelector">
      <i class="fa fa-cloud-upload"></i> Drag and drop files to attach or 
      <a class="browse wb-js-file-browse" ref="fileBrowse" href="#">browse</a>
 </div>
```
As shown, `fileSelector` is the drop area but there is no `input` to receive the file. FE uses `form.io file component`

Is there a way to simulate upload file?

Thanks.

**Comment by yury-s** [comment]
We are working on support for drag-and-drop, that should help with this scenario  @JoelEinbinder any thoughts?

Meanwhile if your goal is to just set the files for upload you can click "browse" link and intercept [`filechooser`](https://playwright.dev/docs/api/class-page?_highlight=filecho#pageonfilechooser) dialog to provide the files.

**Comment by JoelEinbinder** [comment]
Yes, dragging in files is the next feature in my queue. But I don''t have any patches in flight that will solve this yet.

**Comment by louis57** [comment]
> We are working on support for drag-and-drop, that should help with this scenario @JoelEinbinder any thoughts?
> 
> Meanwhile if your goal is to just set the files for upload you can click "browse" link and intercept [`filechooser`](https://playwright.dev/docs/api/class-page?_highlight=filecho#pageonfilechooser) dialog to provide the files.

Thanks @yury-s , I could set the file for upload with `filechooser`, it is really helpful. :+1:

**Comment by mfonsen** [comment]
Drag and Drop seems to be now possible as described in a later issue: https://github.com/microsoft/playwright/issues/10667#issuecomment-998397241
(commenting as this was the top search result for me)
