### ISSUE TITLE
[BUG] --allow-running-insecure-content doesn't work in headless mode

### ISSUE THREAD

**Issue by jordangarside** [microsoft/playwright#5012]
**Context:**
- Playwright Version: 1.6.2
- Operating System: Mac, Linux
- Node.js version: 12.18.4
- Browser: Chromium

**Code Snippet**
```ts
fixtures.browserOptions.override(
  async ({ browserOptions, browserName }, runTest) => {
    const browserArgs = []
    if (browserName === 'chromium') {
      browserArgs.push(
        ...['--disable-web-security', '--allow-running-insecure-content']
      )
    } else if (browserName === 'firefox') {
      browserArgs.push(...['--allow-running-insecure-content'])
    }
    const modifiedOptions: LaunchOptions = {
      ...browserOptions, // Default options
      args: browserArgs,
    }
    await runTest(modifiedOptions)
  }
)
```

**Describe the bug**

When I run my tests with the above chromium params in headful mode, everything works as expected. If the only thing I change is switching it to headless mode, then seemingly the `--allow-running-insecure-content` arg stops working:

```
"[02:24:23] error: Mixed Content: The page at 'https://my.dev.environment.com' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost'. This request has been blocked; the content must be served over HTTPS."
```

Seems likely to me that this is a chromium bug, but I figured I'd ask here first.

**Comment by yury-s** [comment]
Yeah, looks like upstream Chromium issue (my guess is that [HeadlessContentBrowserClient](https://source.chromium.org/chromium/chromium/src/+/master:headless/lib/browser/headless_content_browser_client.cc;l=166) doesn't seem to propagate the value to web prefs).

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.

**Comment by sohaib17** [comment]
crbug: https://crbug.com/1352473

**Comment by sehrgut** [comment]
As of 2023, this is supposed to be fixed in Chromium, but the latest playwright with the latest chromium still exhibits it. Please reopen this at least to give an option to pass the --headless=new flag that does not seem to make it though headless_shell.
