### ISSUE TITLE
[BUG][Electron] filechooser event not emitted when dialog.show(Open|Save)Dialog is called

### ISSUE THREAD

**Issue by rfricz** [microsoft/playwright#5013]
**Context:**
- Playwright Version: playwright-electron 0.5.0
- Operating System: Windows 10 20H2
- Node.js version: 12.18.1
- Browser: Electron 11.1.1

**Description**
The `filechooser` event is not emitted when `dialog.show(Open|Save)Dialog` is called in Electron’s main process. It doesn’t matter if the dialog function is called via `app.evaluate` during a test or triggered from the webapp. Electron also allows selecting directories by these dialogs, FileChooser should support this too.

**Code Snippet**

The following test suite that times out shows the issue. Adapted from [How to demo](https://www.npmjs.com/package/playwright-electron#how-to-demo) on the npm package page, only spec.js is different. Put all three files in one dir and run `npx mocha spec.js`:

main.js:
```javascript
const { app, BrowserWindow } = require('electron');

function createWindow () {
  let win = new BrowserWindow({
    width: 800,
    height: 600,
  });

  win.loadFile('index.html');
}

app.whenReady().then(createWindow);
```

index.html:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
    <meta http-equiv="Content-Security-Policy" content="script-src 'self' 'unsafe-inline';" />
    <style>
      html {
        width: 100%;
        height: 100%;
        display: flex;
        background: white;
      }

      body {
        flex: auto;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
      }
    </style>
  </head>
  <body>
    <h1>Hello World!</h1>
    <button onclick="console.log('click')">Click me</button>
  </body>
</html>
```

spec.js:
```javascript
const { electron  } = require('playwright-electron');
const assert = require('assert');
const electronPath = require('electron');
const path = require('path');

describe('filechooser bug', function () {
  this.timeout(10000);

  before(async () => {
    this.app = await electron.launch(electronPath, {
      args: [path.join(__dirname, "main.js")]
    });
  });

  after(async () => {
    await this.app.close();
  });

  it('filechooser fires in electron', async () => {
    let resolve;
    const promise = new Promise(r => {
      resolve = r;
    });
    const page = await this.app.firstWindow();
    page.on('filechooser', async (fileChooser) => {
      resolve(true);
      await fileChooser.setFiles('/foo/bar.baz');
    });

    await this.app.evaluate(async ({ BrowserWindow, dialog }) => {
      const win = BrowserWindow.getAllWindows()[0];
      await dialog.showOpenDialog(win, {});
    });
    assert.ok(await promise);
  });
});
```

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.

**Comment by Daveiano** [comment]
Any progress or update on this? I am struggling with the same issue.

**Comment by wsw0108** [comment]
Based on spectron-fake-dialog, I wrote a little library to fake electron dialog for playwright/electron, 
https://github.com/wsw0108/playwright-fake-dialog

**Comment by eric-burel** [comment]
As far as I understand dialogs are not normal browser filechooser, as they are triggered from the backend. So the new dialog is probably more a "window" object, though I could not grab it either this way.

**Comment by jessfraz** [comment]
can we pay you all to fix this we need it @pavelfeldman

**Comment by kogratte** [comment]
Hey there. Any tips regarding this? I also need to save a file using main process and I'm also stucked with untriggered events.
