### ISSUE TITLE
[Question] How can I use page.route on a network request initiated by a service worker?

### ISSUE THREAD

**Issue by Aaron-Pool** [microsoft/playwright#5014]
I'm using [mock service worker](https://mswjs.io/) to mock out api calls when running integration tests, but I'm finding that neither `page.on` or `browserContext.on` seems to be detecting calls made my the service worker the library sets up. Am I doing something wrong?

**Comment by yury-s** [comment]
Normally service worker requests should trigger `page.on('request',..)` handlers. I'm not familiar with the mock service worker framework but I'd expect a mock environment to serve all data locally without issuing any network requests. Can you share code of your test?

**Comment by Aaron-Pool** [comment]
@yury-s the way I understand it, mock service worker _does_ issue real requests, they just have a service worker intercept the requests and handle responses. Which is nice, because it makes the mock response "as real as possible" while still being a mock. In fact this is something they highlight in their feature list.

![Screenshot_20210114-214938](https://user-images.githubusercontent.com/5634834/104674938-80ccb980-56b2-11eb-9ce3-8f2c1ea61b79.png)

Additionally, I _do see_ the network requests happening in the network panel. I'll try to add some repro code and network panel screenshots in the morning.

**Comment by yury-s** [comment]
I apologize for deluding you, we currently do not intercept requests issued by service workers, only those sent by the page itself. We may support this in the future, it is tracked in #1090, please add thumbs up for that feature request so we prioritize it higher.
