### ISSUE TITLE
[Question] How do I use Playwright to automate Azure AD based authentication?

### ISSUE THREAD

**Issue by neeldeep** [microsoft/playwright#5017]
I have Azure AD based authentication on a single page application. When a user enters the app url, they are first directed to login.microsoft.com and once user enters the email id they are directed back again to application home page. This is a standard implementation when using SSO for authentication. How do we automate this functionality using playwright? Apologies if this has been already answered before but I couldn't find any details around this?

**Comment by creage** [comment]
Well, in general it is just a set of navigations and forms - right?

```js
await page.waitForNavigation();
// MS login page
await App.fill('input[type="email"][name="loginfmt"]', process.env[user]);

await Promise.all([
    page.waitForNavigation(),
    page.click('input[type="submit"]')
]);
// AzureAD login page (organization login page)
await App.fill('input[type="password"][name="Password"]', process.env[`${user}_PASSWORD`]);

await Promise.all([
    page.waitForNavigation(),
    page.click('#submitButton')
]);
```

**Comment by neeldeep** [comment]
Hi

Thanks for your response but I am not sure if this approach will work. My application URL is say "_somewebapp.com_". User is initially redirected to below page for authentication. There is an azure authentication token being returned after successful authentication and finally user is redirected back to original application URL.
![image](https://user-images.githubusercontent.com/4015081/104653610-c6898200-56b2-11eb-92b2-679242f48bb6.png)

**Comment by theonesmitty** [comment]
Has anyone slayed this beast?  What if the App Proxy uses MFA (Phone auth)?  how can we capture logon state for unattended use?

**Comment by bheemreddy181** [comment]
> Has anyone slayed this beast? What if the App Proxy uses MFA (Phone auth)? how can we capture logon state for unattended use?

Technically you should pick a non human user from whom the MFA is disabled

**Comment by saadman13** [comment]
Is there any recommended approaches for programatically signing in and setting the auth token in playwright browser so that when the user is directed the azure ad for sso it just redirects them back to the app (sp)?
