### ISSUE TITLE
[Question] Is it possible to scroll element into view until it's visible and can be clicked?

### ISSUE THREAD

**Issue by nadavkaner** [microsoft/playwright#5052]
I have a use case in which I have a side nav that is scrollable and there is a fixed overlay element (the black rectangle in the image) that can hide items that clickable in the side nav:
<p float="left">
  <img src="https://user-images.githubusercontent.com/17930663/105047394-f0f08c00-5a72-11eb-9f6d-1f1019ec5868.png" width="300" />
  <img src="https://user-images.githubusercontent.com/17930663/105047510-18dfef80-5a73-11eb-9c27-19784f94a604.png" width="300" /> 
</p>

I'm trying in my test to click on the "Test 2" link but it's hidden by the overlay and I don't see a way to scroll it into view until it visible and can be clicked, I tried to use `scrollIntoViewIfNeeded` that doesn't work.
Is there an existing API that can help in this case to scroll to the element until it visible and can be clicked?

Thanks!

**Comment by pavelfeldman** [comment]
Typically, click will scroll the element into view. But in your case, it seems like the overlay is still covering the item? You could page.evaluate(() => document.body.scrollTop = ...) or document.documentElement.scrollTop = ... manually, depending on where your scroll bar is.

**Comment by nadavkaner** [comment]
Right, the overlay is still covering the item. I can do the scroll manually but probably it will tend to break more easily if the UI or data changed.

**Comment by pavelfeldman** [comment]
As per @dgozman, we should now be alternating scroll into view strategy in order to address your issue. Are you on the latest Playwright?

**Comment by dgozman** [comment]
See issue #3105. Should be fixed in Playwright v1.8.0.

**Comment by pavelfeldman** [comment]
Yay! @nadavkaner, closing as per above, please feel free to open a new issue if it did not do the trick!

**Comment by ManikandanMani** [comment]
Hi All, I am trying to click an element located at the bottom on this [page](http://the-internet.herokuapp.com/),
I tried these but its not clicking/scrolling into the element.
``` var multipleWin = page.Locator("//li[text()='Multiple Windows']");```
```await multipleWin.ClickAsync(new LocatorClickOptions() { Force=true});```
```await multipleWin.ScrollIntoViewIfNeededAsync();```
```await page.DispatchEventAsync("//li[text()='Multiple Windows']", "click"); ```

can anyone let us know how to scroll into an element to the bottom of the page to do a click? 
![image](https://user-images.githubusercontent.com/42301172/171335893-9723ceac-cd5a-4d71-8f71-2147f7f9356f.png)
