### ISSUE TITLE
[Question]How do I Automate the SSO Login Prompt.

### ISSUE THREAD

**Issue by neeldeep** [microsoft/playwright#5053]
When i type the application URL I am presented with the below screen first,
![image](https://user-images.githubusercontent.com/4015081/105059117-dcaa9000-5a6e-11eb-812d-afe5245d72b5.png)

As I enter Email Address and Click next I am have this SSO Login Window.
![image](https://user-images.githubusercontent.com/4015081/105059223-f2b85080-5a6e-11eb-887a-6dbce7e8bcf9.png)

I am using Playwright with CodeceptJS and have the below code:

```
I.amOnPage('/');

I.usePlaywrightTo('handle ms login', async ({ browser, context, page }) => {

    const contexts = await browser.contexts(); 

    const loginPage=await contexts[0].pages()[1];

    await loginPage.waitForNavigation();

   await loginPage.fill('input[type="email"][name="loginfmt"]', 'UserEmail');
   await Promise.all([
    loginPage.click('input[type="submit"]'),
    loginPage.waitForNavigation({ waitUntil: 'networkidle0' })
]);

await loginPage.type('Username', 'Hello');

await loginPage.type('Password', '12345');

  });
```

**Comment by pavelfeldman** [comment]
Looks like in your script you click 'submit' first and then you type into username and password fields. Also you have random waitForNavigations there, not sure why you need all that! https://playwright.dev/docs/next/auth has some auth examples.

**Comment by pavelfeldman** [comment]
(this does not look like a bug report against Playwright, so closing!)

**Comment by neeldeep** [comment]
> (this does not look like a bug report against Playwright, so closing!)

HI @pavelfeldman 
This was created as a question and not a bug report. I have checked the auth examples and it doesn't mention how we can handle SSO Login Prompts. The first submit is there to move from the initial page(refer first screenshot) where user has to enter the email. The Login prompt appears after the first.

**Comment by neeldeep** [comment]
I have opened #5061 as I guess the information wasn't provided properly by me. The first submit is to get over the page where user has to enter Email. The next Login prompt appears after that.
