### ISSUE TITLE
[BUG] Error: Unsupported platform: freebsd

### ISSUE THREAD

**Issue by OctoD** [microsoft/playwright#5084]
**Context:**
- Playwright Version: 1.8.0
- Operating System: freebsd
- Node.js version: 12.18.4

**Describe the bug**

It does not even install:

```
Error: Unsupported platform: freebsd

node_modules/playwright/lib/utils/browserPaths.js:133:11
```

**Comment by yury-s** [comment]
We don't build browsers for FreeBSD today. We haven't seen enough interest in this platform so far.

**Comment by OctoD** [comment]
Ok nevermind, just skipped the browsers installation configuring a .npmrc file. Doing this resolves the issue. Thank you

**Comment by jsjoeio** [comment]
@OctoD do you mind posting your solution? (Haven't used `.npmrc` before and running into a similar issue.

**Comment by OctoD** [comment]
@jsjoeio 

I added these two lines to a global `.npmrc` to skip browsers install:

```
playwright_skip_browser_download=1
playwright_browsers_path=/nonexistent
```
I am using freebsd packages for the browsers, hope it will help.

**Comment by jsjoeio** [comment]
Awesome! Thanks so much! 🙏

**Comment by jfadelhaye** [comment]
Thank you @OctoD ! 🙏
