### ISSUE TITLE
[BUG] Fix documentation regarding Java

### ISSUE THREAD

**Issue by AlbozDroid** [microsoft/playwright#5085]
Reading the `Limitations` section of your official docs here: https://playwright.dev/docs/why-playwright
It says:

> Java language bindings: The Playwright API cannot be used in Java or Ruby today.

However, just above that section, it lists Java as one of the supported languages (https://github.com/microsoft/playwright-java)

I'm I missing something?

**Comment by mxschmitt** [comment]
@AlbozDroid good catch! Thats definitely something which needs to be fixed in the docs.
