### ISSUE TITLE
[Feature] Add debug log when calling to waitForResponse/waitForRequest

### ISSUE THREAD

**Issue by nadavkaner** [microsoft/playwright#5087]
When calling to `waitForResponse`/`waitForRequest` I don't see any debug logs, it can be very useful to have some debug log with the URL or the predicate in order to debug issues

**Comment by mxschmitt** [comment]
What kind of debug logs do you expect to see or would be useful?

**Comment by pavelfeldman** [comment]
You mean to pw:api entries whatsoever? Yeah, should be fixed.

**Comment by nadavkaner** [comment]
Yeah I mean to pw:api entries, I would expect to see some logs like for the other api, something like "waiting for network request/response [URL/predicate]..."
