### ISSUE TITLE
[Question] disable timeout for waitForSelector

### ISSUE THREAD

**Issue by Whooolia** [microsoft/playwright#5099]
Hello, I need some help!

We are seeing timeout error sometimes, so we increase the default timeout using `page.setDefaultTimeout(40000)`.

However, we are getting the same error again, so clearly the 40s timeout is not enough for the element to be visible sometimes (it fails sometimes randomly, not all the time).

I was thinking to set {timeout :0} for this specific element like this below. My questions here is what happen if the element is not there for a long time? is it eventually close the test? or is it going to keep waiting since the timeout disabled? Is there anything I should be aware or careful to set timeout as 0? 

If there is a better solution for this, please let me know. Thanks for reading!
```  
await page.waitForSelector(
    `[data-add-subsection-title="add-subsection-${sectionTitle}"]`,
    { timeout: 0 }
  )
  await page.click(
    `[data-add-subsection-title="add-subsection-${sectionTitle}"]`
  )
```

<img width="1110" alt="Screenshot 2021-01-22 at 15 59 51" src="https://user-images.githubusercontent.com/36998110/105457861-ddd7f900-5cca-11eb-93aa-dfc69918f3f3.png">

**Comment by pavelfeldman** [comment]
The risk is that it will stall forever, so one way or the other you need to have some timeout, maybe on the whole test sweet or on test group.
