### ISSUE TITLE
[Question] CSS element+element selector, click/fill following element (Shadow DOM)

### ISSUE THREAD

**Issue by wrone** [microsoft/playwright#5103]
Hi!

I'm testing a web component and I'm trying to click/fill the input element that doesn't have any unique values (id="input-1434" is not reliable, it is frequently changing). I need to use a selector that can pierce shadow dom. Can't figure it out :( 

HTML example:
```html
<lightning-input class="slds-form-element slds-form-element_stacked" >
    <label class="slds-form-element__label slds-no-flex" for="input-1434">Opportunity Name</label>
    <div class="slds-form-element__control slds-grow">
        <input  type="text" class="slds-input" id="input-1434">
    </div>
</lightning-input>
```

I was trying to do something like this in DevTools but it didn't work:
`playwright.$(":text-is('Opportunity Name') + input");` 

This works `playwright.$(":text-is('Opportunity Name')");`, apparently I'm doing something wrong when I'm trying to find the following input.

XPath example that works and does the same thing:
`playwright.$("//label[contains(text(),'Opportunity Name')]//following::input");`

I would appreciate any suggestions!

**Comment by wrone** [comment]
Also doesn' work `playwright.$("text='Opportunity Name' + input");`

**Comment by wrone** [comment]
Another selectors that I tried:
1. `playwright.$('input:below(:text("Opportunity Name"))')` - Error while parsing selector "input:below(:text("Opportunity Name"))"
2. `playwright.$('input:text("Opportunity Name")')` - returns undefined

**Comment by pavelfeldman** [comment]
It is a little tricky, but we are working on making it simpler.

`playwright.$('lightning-input:has(:text("Opportunity Name")) input')`

- Select `lightning-input` that has given text
- Then look for input in this node

**Comment by dgozman** [comment]
Also note that clicking or filling the `<label for=input-1434>` element should just work, because it is correctly linked with the `<input>` using the `for` attribute. I'll add that to documentation. Let me know if that does not work for you.

```js
await page.click('text=Opportunity Name');
await page.fill('text=Opportunity Name', 'value');
```

**Comment by wrone** [comment]
Hey guys!

@pavelfeldman, thanks, it gave me an idea how to test tricky scenarios!

@dgozman, thanks for a suggestion. Click method worked, fill method failed:
![image](https://user-images.githubusercontent.com/9321029/105547098-d33b5500-5d06-11eb-81e6-19c4bbe9a605.png)

But at the same time `await page.type('text=Opportunity Name', 'hey');` worked, it successfully typed the 'hey' to the existing value in the field. Looks like fill() fails when input field is not empty? 

HTML code of the the field:
```html
<div data-aura-rendered-by="3490:0" class="uiInput uiInputText uiInput--default uiInput--input" data-aura-class="uiInput uiInputText uiInput--default uiInput--input">
    <label class="label inputLabel uiLabel-left form-element__label uiLabel" for="2695:0" data-aura-rendered-by="3485:0" data-aura-class="uiLabel">
        <span class="" data-aura-rendered-by="3486:0">Opportunity Name</span>
        <span class="required" data-aura-rendered-by="2696:0">*</span>
    </label>
    <input class="input" maxlength="120" type="text" aria-describedby="" placeholder="" required="" id="2695:0" data-aura-rendered-by="2699:0" data-interactive-lib-uid="6" aria-required="true" />
</div>
```

**Comment by dgozman** [comment]
@wrone That's interesting. What's your playwright version?

**Comment by wrone** [comment]
@dgozman 1.7.1

**Comment by wrone** [comment]
I'm closing the ticket because my question was answered. Thank you, guys!

**Comment by dgozman** [comment]
Thank you! However, I will most likely follow up with the "fill does not work when pointing to the span inside the label" issue. It should be reasonable to fill in this case.

**Comment by wrone** [comment]
Sure, let me know if you want me to re-test it. Tomorrow I will make few tests again.

**Comment by dgozman** [comment]
The `fill` fix should be available in `playwright@next`. If you are willing to try it, do `npm install playwright@next`. Note that `@next` version is not stable, so be careful and ready for unexpected 😄

**Comment by wrone** [comment]
I just tried to test it, fill() have failed, but I think my test was not really suitable. I also noticed some weird behavior, I will explain below.

I was trying to populate an input field called "Opportunity Name", I used these two lines:
```js
await page.type('text=Opportunity Name', 'Type');
await page.fill('text=Opportunity Name', 'Fill');
```

Outcome:
1. type() method populated the wrong field. 

I think it was not able to find the correct field and started to type the value into the focused field instead. On the screenshot you can see that I'm pointing to that field with a green arrow and the method only typed the half of it - just 'pe', first half 'Ty' was lost.

It looks like it couldn't locate the right field because there is a field with the same name in the background (pointing with red arrow on the screenshot)

2. fill() still fails - I guess it just can't locate the correct field because of the multiple occurrences 
```
  page.fill: Element is not an <input>, <textarea> or [contenteditable] element
=========================== logs ===========================
waiting for selector "text=Opportunity Name"
  selector resolved to visible <span class="test-id__field-label" force-recordlayouti…>Opportunity Name</span>
elementHandle.fill("Fill")
  waiting for element to be visible, enabled and editable
```

Screenshot:
![image](https://user-images.githubusercontent.com/9321029/105866441-e478b000-5feb-11eb-9ebf-b2c235d78d7f.png)

**Comment by wrone** [comment]
I think this issue appeared on my side, not because of some Playwright bugs. Looks like when I was initially testing it and type() worked but fill() failed, I just didn't noticed that it typed the value into the wrong field.

**Comment by dgozman** [comment]
@wrone Sounds like everything is resolve. Let me know if you see another issue. Thank you for the thorough digging!

**Comment by wrone** [comment]
Sure. Thank you!

**Comment by akapitoha** [comment]
hi @pavelfeldman 
> `playwright.$('lightning-input:has(:text("Opportunity Name")) input')`

I found this very helpful for my test, but can't understand how it works (especially space before `input` in the end). Is it documented?
thank you.

**Comment by dgozman** [comment]
@akapitoha This is a CSS selector `lightning-input input` with an extra `:has()` pseudo-class. Read more about `:has()` and more Playwright selectors [here](https://playwright.dev/docs/selectors#selecting-elements-that-contain-other-elements).
