### ISSUE TITLE
[Feature](playwright-cli) Option to install system dependencies

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright#5105]
Similar to how playwright installs browsers with `playwright install`, it should prompt for installing system dependencies if not found on the host system or something like that to notify the user. This way it would be a much better experience that to copy paste that `sudo apt-get install ...` command and running it automatically. Doing so would also make it easier to install on CI environments with a simple command `playwright install` and good to go :rocket: . Would also fix issues like https://github.com/microsoft/playwright-python/issues/453

Please :+1: if so.

**Comment by pavelfeldman** [comment]
Would you be open to working on it? Note that there are as many library lists as there are Linux distributions  and their versions, so we are talking about dozens of configs.

**Comment by mxschmitt** [comment]
I think thats not good to integrate it into the playwright install command in my opinion, since it touches apt and users don't expect that when they run `python -m playwright install`. Since each system is kinda different it would either not work or require much maintenance overhead over time.

**Comment by kumaraditya303** [comment]
As far as I think by `playwright install` users expect whatever dependencies playwright would be installed and no need of other dependencies. Also this issue is not only for distributions using `apt` but also other distributions using `yum` etc.

**Comment by kumaraditya303** [comment]
@pavelfeldman  I am open to be working on it.

**Comment by andrisi** [comment]
Isn't this really about installing dependencies of the browsers you download? Don't they support downloading their dependencies or maintain what you need to run then somewhere?
