### ISSUE TITLE
[BUG] Webkit leaking Proxy-Authorization header

### ISSUE THREAD

**Issue by apmcodes** [microsoft/playwright#5108]
**Context:**
Playwright: 1.7.1
System:
    OS: Linux 4.15 Ubuntu 18.04.5 LTS (Bionic Beaver)
    Memory: 476.47 MB / 7.51 GB
    Container: Yes
  Binaries:
    Node: 12.19.0 - /usr/bin/node
    npm: 6.14.9 - /usr/bin/npm
  Languages:
    Bash: 4.4.20 - /bin/bash

**Code Snippet**

```javascript
const webkit = require('playwright').webkit;

(async () => {
      const options = {
        headless: false,
        proxy,
        timeout: 30000,
    };
        const browser = await webkit.launch(options);
  // ...
})();
```

**Describe the bug**
In the webkit browser visit https://www.deviceinfo.me/ and under http headers one can find the Proxy-Authorization header. This header is not visible in FireFox.

I have no idea if this is how its meant to be on the WebKit side or something can be done on the PlayWright side to hide it. If this can be hidden from the PlayWright (by setting any options) would be great. 

```
HTTP Request Headers: 
■ Accept:
text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
■ Accept-Encoding: gzip, deflate
■ Accept-Language: en-IN
■ Connection: Keep-Alive
■ Host: www.deviceinfo.me
■ Proxy-Authorization: Basic Ym91..................Rlcw==
■ User-Agent:
Mozilla/5.0 (iPhone; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/80.0.3987.95 Mobile/15E148 Safari/604.1
```

**Comment by pavelfeldman** [comment]
Browser needs to send authorization header for proxies with auth, but proxy must remove this header to not leak it to the target host. What ia your proxy?

**Comment by apmcodes** [comment]
Got it. I was intrigued as it happened with WebKit and not with FireFox. 

We are using a residential proxy service (not naming it here) so not sure of the proxy server/ tool being used. Will check with them.

**Comment by aslushnikov** [comment]
Closing this due to big stream of bugs. Please feel free to reopen/refile if there's more we can do here!
