### ISSUE TITLE
[BUG] browserContext.addCookies() fails when !cookie.value

### ISSUE THREAD

**Issue by fcastrocs** [microsoft/playwright#5127]
**Context:**
- Playwright Version: 6.14.9
- Operating System: Windows, Linux
- Node.js version: v14.15.4
- Browser: Firefox

**Code Snippet**

let context = await this.page.context();
let cookies = await context.cookies();
// then after reusing cookies
await context.addCookies(cookies); <-- throws "browserContext.addCookies: Cookie should have a value"

**Describe the bug**
I pass unaltered cookies to context.addCookies() and it throws: "browserContext.addCookies: Cookie should have a value"
So I have to loop through the cookies to make sure each cookie has a 'value' property set.

The following cookie would cause a throw because value is unset,
{
  name: '52245',
   value: '',
  domain: 'www.example',
  path: '/',
  expires: 1619160010,
  httpOnly: false,
  secure: false,
  sameSite: 'None'
},

**Comment by aslushnikov** [comment]
Fixed by Pavel!
