### ISSUE TITLE
[Feature] Controlling images quality when exporting to pdf

### ISSUE THREAD

**Issue by kuworking** [microsoft/playwright#5132]
When exporting a pdf, file sizes can be huge if images are big

It would be nice to have the same capabilities than when using a screenshot

```js
  await page.pdf({
    path: `${__dirname}/build/file.pdf`,
    type: 'jpeg',
    quality: 10,
  })
```

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
