### ISSUE TITLE
[BUG] title getting when alert shown (after timeouted click) jams forever

### ISSUE THREAD

**Issue by mkorpela** [microsoft/playwright#5134]
**Context:**
- Playwright Version: 1.8.0
- Operating System: OSX
- Node.js version: 12.6.0
- Browser: Chromium
- Extra: Original reported issue to RobotFramework-Browser https://github.com/MarketSquare/robotframework-browser/issues/674

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium} = require('playwright');

(async () => {
    const browser = await chromium.launch({ headless: false });
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto('http://localhost:8000/');
    console.log("CLICK");
    try {
        await page.click('text=First click');
    } catch (e) {
        console.log("timeout! CLICK - done -> getting title");
        try {
            console.log(await page.title());
        } catch (e) {
            console.log("exception");
        }
        console.log("Title done")
    }
    await browser.close();
  }
)();
```

```html
<!doctype html>
<html>
  <head>
    <title>Title</title>
  </head>
  <body>
    <p>Content</p>
	<button type="button" onclick="javascript:alert('your msg')";>First click</button>
	<button type="button">Second click</button>
  </body>
</html>
```

**Describe the bug**
Should timeout after some time. Seems to be stuck forever.

**Comment by pavelfeldman** [comment]
That's how web works, alert dialog blocks everything. See https://playwright.dev/docs/dialogs

**Comment by mkorpela** [comment]
The click that causes the dialog, will timeout. Only the action after that will not..

**Comment by mkorpela** [comment]
I just think that the original report we have has a point. It would be much better that a long running test suite execution will continue after some timeout even if some poor person has forgotten a debug alert box to somewhere.

**Comment by adrian-evo** [comment]
One frequent use case during testing is when the alert is unexpected and thus obviously it cannot be handled programmatically. Please consider also the example below to simulate random appearance of an alert during load. In real web applications this unexpected alert might be displayed for example due to a temporary server error and it is handled fine by Selenium as in the attached picture below.

```
<!doctype html>
<html>
  <head>
    <title>Title</title>
  </head>
  <body onload="loaded()">
    <p>Content</p>
	<button type="button">First click</button>
  </body>
  <script>
    function loaded() {
	  if (Math.random() < 0.5)
		alert("Failed to load!");
    }
  </script>
</html>
```


Real project sample with Selenium:

![2021_01_26_10_26_22_Window](https://user-images.githubusercontent.com/19324942/105954272-20a82100-607d-11eb-8dee-1c6791997d12.png)

**Comment by aslushnikov** [comment]
> One frequent use case during testing is when the alert is unexpected and thus obviously it cannot be handled programmaticall

@adrian-evo You actually can handle all the unexpected dialogs and disregard them altogether:

```js
...
const page = await context.newPage();
// As soon as you created a page, add an event handler to disregard all the dialogs right away.
page.on('dialog', dialog => dialog.dismiss());
...
```

>  It would be much better that a long running test suite execution will continue after some timeout even if some poor person has forgotten a debug alert box to somewhere.

@mkorpela I think this should be an explicit decision on the side of the test/automation author. If they'd like to do this decision, the trick I mention above should be working just fine!

**Comment by mkorpela** [comment]
@aslushnikov and implicit then is to wait forever? I believe that default covers very little real use cases.
