### ISSUE TITLE
[Question] scrollIntoViewIfNeeded is not a function

### ISSUE THREAD

**Issue by wrone** [microsoft/playwright#5135]
Hey,

I can't make scrollIntoViewIfNeeded() work, probably because I'm doing something wrong, I'm new to node.js. I would appreciate your help!

I need to scroll down to the field before clicking it. My Playwrigth code:
```js
const typePicklist = page.waitForSelector('lightning-combobox:has(:text("Type")) input');
await typePicklist.scrollIntoViewIfNeeded({ timeout: 60 });
```

I get this error:
`TypeError: typePicklist.scrollIntoViewIfNeeded is not a function`

**Comment by wrone** [comment]
I think I figured it out, I had to use "await" on both lines. It was still failing though because of this `elementHandle.scrollIntoViewIfNeeded: Timeout 60ms exceeded.`. I didn't notice this error earlier. 

I increased the timeout and it executed with erorrs.
```js
const typePicklist = await page.waitForSelector('lightning-combobox:has(:text("Type")) input');
await typePicklist.scrollIntoViewIfNeeded({ timeout: 600 });
```

Is it an ok approach?

**Comment by pavelfeldman** [comment]
600ms is too fast? Those are milloseconds...

**Comment by wrone** [comment]
Yeah, I increased the timeout eventually. I guess I was too overwhelmed by other issues with Docker and didn't realize that these are ms. Closing the ticket. Thank you!
