### ISSUE TITLE
[Question] Expect element to be null 

### ISSUE THREAD

**Issue by Whooolia** [microsoft/playwright#5137]
<img width="1114" alt="Screenshot 2021-01-25 at 19 19 11" src="https://user-images.githubusercontent.com/36998110/105692782-3533ce80-5f42-11eb-94ca-5f96c5c5f7db.png">

The test failed at this, and not clear why it fails.. any suggestions or ideas? 

```
 logStep(`The delete button shouldn't appear`)
    await page.waitForSelector(`[data-testid="${sectionForm}"]`)
    const addSectionForm = await page.$(`[data-testid="${sectionForm}"]`)
    expect(addSectionForm).toBeDefined()

    if (addSectionForm) {
      const deleteButton = await addSectionForm.$(
        `[data-testid="${buttonDelete}"]`
      )
      expect(deleteButton).toBeNull()
    }
```

**Comment by pavelfeldman** [comment]
I guess delete button is there, but is invivsible? `expect(await deleteButton.isVisible()).toBeFalse()`.

Btw, there is extra line in your snippet, can be
```
const formElement = await page.waitForSelector(`[data-testid="${sectionForm}"]`)
```

**Comment by Whooolia** [comment]
Thanks for the advice,

I ended up doing this - I couldn't use `isVisible` for `deleteButton` so checking if the element is not attched. Thanks again!
```
    const addSectionForm = await page.waitForSelector(
      `[data-testid="${sectionForm}"]`
    )
    expect(addSectionForm).toBeDefined()
    if (addSectionForm) {
      await addSectionForm.waitForSelector(`[data-testid="${buttonDelete}"]`, {
        state: 'detached',
      })
    }
```

**Comment by Whooolia** [comment]
@pavelfeldman Hi, just another question about timeout failure, so we have e2e tests running on circleCI.

It randomly fails with timeout issue with some element that also seems random.. we already `setDefaulttimeout` for each page. 

Any other ways that we can address this issue? Also, ddo you know why we are getting this random timeout issue?

**Comment by aslushnikov** [comment]
> Hi, just another question about timeout failure, so we have e2e tests running on circleCI.

Looks like you've already filed this at https://github.com/microsoft/playwright/issues/5198

Closing this one since questions have been resolved!
