### ISSUE TITLE
[Question] 是否考虑支持 antd upload 场景

### ISSUE THREAD

**Issue by crazyair** [microsoft/playwright#5155]
封装的 upload  https://ant-design.gitee.io/components/upload-cn/  
codegen 生成的代码执行报错

```
    // Go to https://ant-design.gitee.io/components/upload-cn/
    await page.goto("https://ant-design.gitee.io/components/upload-cn/");

    // Click text="Click to Upload"
    await page.click('text="Click to Upload"');

    // Upload demo.jpg
    await page.setInputFiles(
        "//button[normalize-space(.)='Click to Upload']",
        "demo.jpg"
    );
```

**Comment by aslushnikov** [comment]
If I understand correctly, the `demo.jpg` is missing for you. You should put it in the CWD when running the script.

P.S. Next time, please use english to describe the issue so that the discussion is available for broader community.
