### ISSUE TITLE
[Feature] Ability to provide user-defined name for Tracers

### ISSUE THREAD

**Issue by domderen** [microsoft/playwright#5157]
In the trace viewer, I'd like to be able to see traces for all my executed tests, with the ability to quickly identify which trace relates to which test. At the moment, each trace for a single test is defined in a separate file, and its name is a random guid. I would like to specify a name for that trace. The name doesn't have to be reflected in the filename, but when I open trace-viewer, I would like to be able to select traces by name in the dropdown highlighted on the screenshot below.

<img width="1680" alt="Zrzut ekranu 2021-01-26 o 17 54 22" src="https://user-images.githubusercontent.com/2360738/105876837-a2596980-5fff-11eb-892a-695e89f52781.png">

I'm happy to contribute code that would provide such functionality, but before going too far, I wanted to see if such feature makes sense for others as well.

**Comment by dgozman** [comment]
This is indeed useful! We discussed this a while ago, and so far the `debugName` option in `browser.newContext` seems like the easiest solution.

**Comment by domderen** [comment]
Yeah that was my thinking as well. Do you think `debugName` or `tracerName` would be more meaningful? Second one seems more descriptive, but I'm not sure if there are other places where this name could be used as well...

**Comment by dgozman** [comment]
`debugName` would allow us to use it in more places if the need arises.
