### ISSUE TITLE
[Question] Is SubtleCrypto available?

### ISSUE THREAD

**Issue by bkiac** [microsoft/playwright#5158]
I'm trying to test my functions which use the SubtleCrypto API.

```ts
import type { FirefoxBrowser, Page } from "playwright"
import { firefox } from "playwright"

async function test() {
  const browser = await firefox.launch()
  const page = await browser.newPage()
  
  const cryptokey = await page.evaluate(async () => {
    const key = await window.crypto.subtle.importKey(
      "raw",
      crypto.getRandomValues(new Uint8Array(8)),
      "HKDF",
      false,
      ["deriveKey"],
    )
    return key
  })
}

void run()
```

This snippet fails with the following error:
```
page.evaluate: Evaluation failed: crypto.subtle is undefined
@debugger eval code line 307 > eval:2:21
callFunction@debugger eval code:308:28
@debugger eval code:1:44
page.evaluate: Evaluation failed: crypto.subtle is undefined
@debugger eval code line 307 > eval:2:21
callFunction@debugger eval code:308:28
@debugger eval code:1:44
```

Can I access the SubtleCrypto API with Playwright somehow?

Thanks!

**Comment by mxschmitt** [comment]
[SubtleCrypto is only available on secure contexts](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto), see this example which works: https://try.playwright.tech/?s=vbczji0

So you have to navigate to a https based URL before.

**Comment by pavelfeldman** [comment]
... or http://localhost. You can context.route to get yourself a secure context on localhost if you have no server running.

**Comment by bkiac** [comment]
Thank you, it works!
