### ISSUE TITLE
[Feature] Pointing to Dev Channel instead of nightly

### ISSUE THREAD

**Issue by gilles-yvetot** [microsoft/playwright#5159]
Recent versions of Chromium/Chrome (88 and 89) have been causing issue with specific versions of PW.
PW ships with the nightly version of Chromium and I think it could be beneficial to point to the Dev channel to be able to "jump" faulty versions and increase reliability for a specific version.

**Comment by pavelfeldman** [comment]
@aslushnikov : do you think we can do this at some point?

**Comment by aslushnikov** [comment]
This will be possible once https://github.com/microsoft/playwright/issues/5067 is complete. Actually, merging it in #5067 - we'll naturally move to Dev branches once we have builders in place.
