### ISSUE TITLE
[Question] Way to do mouse.move(selector, steps) type functionality

### ISSUE THREAD

**Issue by cwar082** [microsoft/playwright#5160]
Currently using Playwright for Python 0.171.1.

- I'm trying to make the videos of the tests look more like people, so having the mouse move towards an element before hovering, then clicking.
- I'm currently doing this like the code snippet below, but it doesn't work unless it's a fresh page/I move the mouse back to the top left. 
- There's also a bit of jank when it ends the mouse move to go to hover as the bounding client calculation gets the top left of the element, whereas hover goes for the middle. 
- The mouse pointer function is [this function for showing the mouse pointer but modified for Playwright for Python](https://github.com/puppeteer/puppeteer/issues/4378#issuecomment-499726973). 

```
with sync_playwright() as p:
        browser = p.chromium.launch()
        context = browser.newContext(recordVideo={'dir':'videos/'})
        page = context.newPage()
        page.goto("http://example.com")
        page.on("domcontentloaded", mouse_pointer_function)
        selector = "h1"
        x_pos = page.evaluate("""document.querySelector("{}").getBoundingClientRect()["x"]""".format(selector)
        y_pos = page.evaluate("""document.querySelector("{}").getBoundingClientRect()["y"]""".format(selector)
        page.mouse.move(x=x_pos, y=y_pos, steps=100)
        page.hover(selector)
        page.click(selector)
```

**Comment by aslushnikov** [comment]
> I'm trying to make the videos of the tests look more like people, so having the mouse move towards an element before hovering, then clicking

@cwar082 So why do you want this, in the first place? Is it something you stumbled upon while testing your website?

**Comment by cwar082** [comment]
> > I'm trying to make the videos of the tests look more like people, so having the mouse move towards an element before hovering, then clicking
> 
> @cwar082 So why do you want this, in the first place? Is it something you stumbled upon while testing your website?

I am recording our sign up flow and a couple of other critical paths and adding it in our issue management tool to have a shareable record of it - but thought the videos looked strange without the mouse.

**Comment by aslushnikov** [comment]
@JoelEinbinder can we have an api for your Mouse indicator in https://github.com/microsoft/playwright/pull/3526 so that it would appear on videos as well?

**Comment by delimmy** [comment]
+1 would be great to have functionality to emulate mouse movements to a specific selector

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.

**Comment by baptisteArno** [comment]
This can be done with:
```ts
await page.locator('...').hover()
```

**Comment by dscape** [comment]
> This can be done with:
> 
> ```ts
> await page.locator('...').hover()
> ```

Thank you for the userful response.

**Comment by zeekrey** [comment]
Hover wasn't working for me either. I'm using this approach now:

```javascript
const element = page.getByText("whatever");
const { x, y, width, height } = await element.boundingBox();
await page.mouse.move(x + width / 2, y + height / 2);
```

**Comment by doglex** [comment]
It is useful when hard to locate child in child in child in child in child ... element, but easy to locate the parent emlent .
```
await page.locator('div[aria-label="parent"]').hover()
await page.mouse.down();
await new Promise(resolve => setTimeout(resolve, 50))
await page.mouse.up();
```

**Comment by dmitry-kurmanov** [comment]
> This can be done with:
> 
> await page.locator('...').hover()

it seems that the `page.locator('...').hover()` doesn't raise the `mousemove` event. Probably it works by `mouseenter/mouseout`.
