### ISSUE TITLE
[Question] How to test functions that use the Web API?

### ISSUE THREAD

**Issue by bkiac** [microsoft/playwright#5165]
I'm trying to test my functions that utilize the Web Crypto API, for example:

```js
const { webkit } = require("playwright")

async function importKey() {
  return window.crypto.subtle.importKey("raw", new Uint8Array(8), "HKDF", false, ["deriveKey"])
}

(async function test() {
  const browser = await webkit.launch()
  const page = await browser.newPage()
  await page.goto("https://example.com")

  // how to test `importKey` with the Playwright context's `window.crypto`?

  await browser.close()
})()
```

I was thinking about running a dev server that hosts a page with a JS file that contains the `importKey` function and visiting this page with Playwright. Is there a simpler way to use my custom modules inside Playwright that use Web APIs?

**Comment by gonzobard777** [comment]
maybe [page.evaluate](https://playwright.dev/docs/core-concepts#execution-contexts-playwright-and-browser)
```js
const browser = await webkit.launch()
const page = await browser.newPage()
await page.goto("https://example.com")

// how to test `importKey` with the Playwright context's `window.crypto`?
const key= await page.evaluate(([format, algorithm, extractable, keyUsages]) => {
  return window.crypto.subtle.importKey(format, new Uint8Array(8), algorithm, extractable, keyUsages);
}, ["raw", "HKDF", false, ["deriveKey"]]);

await browser.close()
```

**Comment by bkiac** [comment]
I thought about this but I have several more complex functions that I don't want to duplicate inside `evaluate`, the `importKey` one is just an example.
It would also mean I have to maintain two versions and keep them in sync.

**Comment by aslushnikov** [comment]
> I thought about this but I have several more complex functions that I don't want to duplicate inside evaluate

@bkiac there's actually no need to duplicate stuff; you can simply use your function as an argument to evaluate. In this case, your function will be serialized and sent over to browser.

```js
const { webkit } = require("playwright")

async function importKey() {
  return window.crypto.subtle.importKey("raw", new Uint8Array(8), "HKDF", false, ["deriveKey"])
}

(async function test() {
  const browser = await webkit.launch()
  const page = await browser.newPage()
  await page.goto("https://example.com")
  await page.evaluate(importKey); // <<---- 

  await browser.close()
})()
```

Alternatively, you can put all your web-based functions in a single file, and then use [`page.addScript()`](https://playwright.dev/docs/api/class-page?_highlight=addscript#pageaddscripttagoptions) to load it in the browser.

**Comment by bkiac** [comment]
@aslushnikov I tried the first approach, but I couldn't pass imported functions to `evaluate`.

This is my complete `importKey` implementation in `keys.ts`:
```ts
export async function importKey(ikm: Uint8Array): Promise<CryptoKey> {
	return crypto.subtle.importKey("raw", ikm, "HKDF", false, ["deriveKey"])
}
```
Importing this method and passing it to `evaluate` did not work.

I've been looking at `addScript` but my functions are written in TypeScript so I would need to compile them before I can pass them to `addScript`. Overall I think this approach might be the best.

Thanks for the suggestions!

**Comment by aslushnikov** [comment]
> Importing this method and passing it to evaluate did not work.

@bkiac what exactly didn't work? I noticed that your actual function accepts an argument. Just to make sure: could it be that you didn't pass the argument in these and function just failed?

**Comment by bkiac** [comment]
I changed the function to use no arguments to test the imports. I tried to create a reproducible test but it works now so it must have been something I overlooked the first time.

Regarding the arguments I tried it like this:
```ts
const key = await page.evaluate(importKey, new Uint8Array(8))
```

and I got this error:
```
page.evaluate: Evaluation failed: TypeError: Member JsonWebKey.kty is required and must be an instance of DOMStringpage.evaluate: Evaluation failed: TypeError: Member JsonWebKey.kty is required and must be an instance of DOMString:
```

I also tried wrapping it in a function like this:
```ts
async function testImportKey(): Promise<CryptoKey> {
	return importKey(new Uint8Array(8))
}

const key = await page.evaluate(testImportKey)
```
and I got this error:
```
page.evaluate: Evaluation failed: ReferenceError: Can't find variable: keys_1page.evaluate: Evaluation failed: ReferenceError: Can't find variable: keys_1:
```

**Comment by aslushnikov** [comment]
@bkiac ah i see. This is because typed arrays serialization is not supported currently. I filed #5241 to track this separately.
