### ISSUE TITLE
[Feature] export codegen as a library

### ISSUE THREAD

**Issue by xylix** [microsoft/playwright#5176]
Currently it is quite difficult to make use of playwright-cli as an imported npm package in typescript projects. Would it be possible to provide the type stubs along with the compiled .js on `npm install playwright-cli`?

Possibly just changing `declaration: false` to `declaration: true` and including them in the npm package might be enough.

The use case I'm looking for is being able to import the codegen functionality from playwright-cli to build on top of that.

**Comment by dgozman** [comment]
We are not likely to work on this in the near future. However, if this turns into a popular request, we will prioritize.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
