### ISSUE TITLE
[Feature] codegen: detect if hover changes DOM and then record a hover event

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#5177]
Dropdown menus like here: https://ant.design/components/dropdown/ are often used to e.g. "hide" the logout functionality and provide other profile related actions. We did this in an internal application.

Is it possible to detect if a hover by a user changes the DOM / CSS / layout and if so then record a page.hover call?

Example:

![image](https://user-images.githubusercontent.com/17984549/92596032-72eece00-f2a5-11ea-8587-d34702d40035.png)

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.

**Comment by jaybowang** [comment]
@mxschmitt Found a workaround. Everytime you hover something, just click it. "Click" means hover explicitly.

**Comment by sidvud98** [comment]
> @mxschmitt Found a workaround. Everytime you hover something, just click it. "Click" means hover explicitly.

@jaybowang Even clicking it is not recording the action for some strange reason. The element getting clicked is a styled component in a webapp built on Next(v.12.3.1) & Typescript.
