### ISSUE TITLE
How can I download chromium for playwright-core? [Question]

### ISSUE THREAD

**Issue by dllmkdir** [microsoft/playwright#5183]
## Use case
I want to use `playwright` with `chromium` to create a bot.
The problem: `playwright-chromium` does not pass bot detection tests for `navigator.webdriver` because it is already set.
On top of that,  using `playwright` is too heavy for the container where we are testing our jobs. 

I saw this [Solution](https://github.com/microsoft/playwright/issues/1191#issuecomment-594326392) that has already been merged. Even so, I am not able to locate the `browserType.downloadIfNecessary` feature in `playwright-core` and `playwright`. It is not specified in [the documentation](https://playwright.dev/docs/api/class-browsertype/). I don't know if the method changed over time.

**Comment by mxschmitt** [comment]
What do you mean with "does not pass bot detection tests"? Because downloading Chromium with playwright-core would end up in being the same as the playwright-chromium package. 

There is currently no official exposed function which makes it possible to install the browsers manually (except hacky solutions).

**Comment by dllmkdir** [comment]
> What do you mean with "does not pass bot detection tests"? 

I am not able to override the `navigator.webdriver`, necessary for the site where I  am scrapping. This property is not overrideable in `playwright-chromium` but it is in playwright`. Are there known hacky solutions to download the browser manually?

**Comment by dllmkdir** [comment]
Saw the issue: playwright chromium was bugged. A fresh install was enough 😓
