### ISSUE TITLE
[BUG] codegen: The generated code is incomplete in Windows system

### ISSUE THREAD

**Issue by istommao** [microsoft/playwright#5184]
The generated code is incomplete in Windows system when click login button

But it works in MacOS when click login button.
```node
  // Click //button[normalize-space(.)='login']
  await Promise.all([
    page.waitForNavigation(/*{ url: 'http://test.com/workbench' }*/),
    page.click('//button[normalize-space(.)=\'login\']')
  ]);
```

**Comment by dgozman** [comment]
@istommao Could you please provide the steps to reproduce the problem? What is expected? What you get instead? Is the code snippet above expected or unexpected?

**Comment by dgozman** [comment]
Closing per lack of feedback. Please reopen when new information is available.
