### ISSUE TITLE
[BUG] Codegen does not record actions after pressing concrete keys

### ISSUE THREAD

**Issue by rmallof** [microsoft/playwright#5185]
Hi,

When I click in a random form field and press 'alt', for example to write '@' something happens and actions on **select fields** of the form are no longer recorded

Running the command:
playwright-cli -b ff --lang "en" codegen https://sforce.co/34AHdU4

1. Click in "First name"
2. Press "alt"
3. The following shows up in the logs:

  **pw:api => frame.press started +2s
  pw:api waiting for selector "input[name="UserFirstName"]" +1ms
  pw:api   selector resolved to visible <input type="text" required="" name="UserFirstName" ari…/> +8ms
  pw:api elementHandle.press("AltGraph") +15ms
  pw:api <= frame.press failed +11ms**

Then, when changing the option from the "Country" field, the action is not recorded

This issue may be related to https://github.com/microsoft/playwright-cli/issues/188

Versions:
Windows 10 Pro 20H2

playwright-cli --version
Version 0.170.0

node --version
v15.4.0

**Comment by dgozman** [comment]
I can reproduce this. We'll work on a fix.

**Comment by xpedrooo** [comment]
Hi,

Actions are not recorded in codegen like clicking the button, filling up input fields.

Any idea?

Thanks
