### ISSUE TITLE
[BUG] codegen: do not use select's innerText for selector

### ISSUE THREAD

**Issue by rmallof** [microsoft/playwright#5190]
Hi,

When a form select / dropdown list changes the DOM depending on the choosen option, for example adding a new field in the form, the code selecting the option is not recorded

Running the command: 
playwright-cli -b ff --lang "en" codegen https://sforce.co/34AHdU4
And choosing "United States" as the "Country" field will trigger this behavior, dumping the following into the logs:

**pw:api => frame.selectOption started +5s
pw:api waiting for selector "//div[starts-with(normalize-space(.), '  Sign up now to start your free trial. First name Enter your first name Last na')]" +1ms
pw:api   selector resolved to visible <div class="col  text-left col-xs-12 col-sm-6 col-md-…>…</div> +19ms
pw:api <= frame.selectOption failed +6ms**

Versions:
Windows 10 Pro 20H2

playwright-cli --version
Version 0.170.0

node --version
v15.4.0

Thanks!

**Comment by dgozman** [comment]
This is because generated selector contains the dump of all selector options in this case. We should fix that.

**Comment by dgozman** [comment]
This will be fixed in the next v1.9 release.
