### ISSUE TITLE
[Feature] codegen: Add support for Crystal Language

### ISSUE THREAD

**Issue by alexanderadam** [microsoft/playwright#5191]
It would be great if [a code generator](https://github.com/microsoft/playwright-cli/tree/master/src/codegen/languages) for @crystal-lang could be added.

A corresponding driver for Crystal already exist ([`playwright-cr`](https://github.com/naqvis/playwright-cr#usage) was [just recently created](https://github.com/crystal-community/crystal-libraries-needed/issues/119#issuecomment-754847744)) and I'm sure that there will be some similarities to the [Python generator](https://github.com/microsoft/playwright-cli/blob/master/src/codegen/languages/python.ts).

**PS:** Thank you for your work! :pray: 
**PPS:** See also Playwright PRs [4911](https://github.com/microsoft/playwright/pull/4911) and [4945](https://github.com/microsoft/playwright/pull/4945)

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
