### ISSUE TITLE
[Feature] codegen: How to record video?

### ISSUE THREAD

**Issue by hcaihao** [microsoft/playwright#5192]
Sorry I'm new to playwright.

Can it implement by add some params after npx playwright-cli xxx or some other usage?

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
