### ISSUE TITLE
[Question] random timeout

### ISSUE THREAD

**Issue by Whooolia** [microsoft/playwright#5198]
Hello, I am wondering what would be the best way to handle the timeout issue.

The thing is that it fails with a random element so it is really hard to understand why and how to address this issue.

we have tried `setdefault timeout` for each page (still doesn't help), also disable timeout with a specific element that we have seen that it failed frequently, but still fails sometimes with a different element. 

It is hard to expect which element causes the issue because it fails with different element each time. so is there anything we can do at configuration level instead of taking care of each element/page?

- would it be good to set `slowMo: 100` by any chance? (tried but it doesn't seem helpful)
- Is there a way to re-run automatically if the test fails with timeout?

<img width="1041" alt="Screenshot 2021-01-28 at 14 31 22" src="https://user-images.githubusercontent.com/36998110/106094524-81b32000-6175-11eb-992f-291e02388906.png">

**Comment by aslushnikov** [comment]
@Whooolia from your description it looks like website is rendered differently every once in a while. This might happen if A/B testing is not disabled for testing usecases. Did you try running scenarios manually many times and making sure all the elements are actually there and visible?

> It is hard to expect which element causes the issue because it fails with different element each time. so is there anything we can do at configuration level instead of taking care of each element/page?

I don't think so: it looks like website behaves unpredictably, so it's hard to test it reliably.

> would it be good to set slowMo: 100 by any chance? (tried but it doesn't seem helpful)

The `slowMo` option is not a good way to workaround issues like this. It **might** mask some of the problems, but it would drastically slow down tests and won't remove flakiness.

> Is there a way to re-run automatically if the test fails with timeout?

It depends on your testrunner, but most of them have this ability one way or another. Which one do you use?
