### ISSUE TITLE
[Question] wildcard in playwright page.frame (url option)

### ISSUE THREAD

**Issue by dandreaf** [microsoft/playwright#5206]
I'm trying to find a way to use a wildcard in the `page.frame(url)` function of playwright, I have this code:

await page.frame({
    url: 'http://192.168.20.222:8080/ords/f?p=150:13:12188371642929::NO:13::&cs=3rW0d3IdG36wpBBz1GAnD2UV8kf7xWvgqUaa28l5eceRm71VjW6F33ufnHQnEvSAJpbB7CSDdVQNXeKOyLRYnQw&p_dialog_cs=IBgwSu6yIUBbITteHHI5ea8wU7JXa9CDY1LsEMKeBVEM7oYixeWw0HW9GrCAtCPffvG3VLlveff_t720koyh3Q'
}).click('button[id="B5602689567386780"]');

and when I open the same page with the test tool the url changes:

await page.frame({
    url: 'http://192.168.20.222:8080/ords/f?p=150:13:1511883080952::NO:13::&cs=3DJ0vt7NMVCCk4xQvKJoD-unSF5896wbfp99oGMQ0Qg7DaIbaeJOV0oqnEfkntXgnLNq902F97vpFAm2-dlFGRQ&p_dialog_cs=Ui4xj5jDt_J91vpSWo-MezLxSG60jFLoGhx3oh85DTIaR7Tv9c7wdCSXRRikra57RyQz2hvkPzZEXNqbwqF83g'
}).click('button[id="B5602689567386780"]');

Do I have any option to use a wildcard in the url?

Like `*` and have my code like this?

await page.frame({
    url: 'http://192.168.20.222:8080/ords/f?p=150:*'
}).click('button[id="B5602689567386780"]');

thanks you a lot

**Comment by aslushnikov** [comment]
Hey @dandreaf, you should use regex instead of a string, like this:

```js
const frame = page.frame({
url: /192.168.20.222:8080\/ords\/f?p=150:*/
});
await frame.click('button[id="B5602689567386780"]');
```

**Comment by dandreaf** [comment]
> Hey @dandreaf, you should use regex instead of a string, like this:
> 
> ```js
> const frame = page.frame({
> url: /192.168.20.222:8080\/ords\/f?p=150:*/
> });
> await frame.click('button[id="B5602689567386780"]');
> ```


it did not work, it throws me this error:

frame.click: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "button[id="B5602689567386780"]"
============================================================

**Comment by pavelfeldman** [comment]
Your regex does not match your url, you did not escape '?'

**Comment by pavelfeldman** [comment]
You can find more filtering options at https://playwright.dev/docs/api/class-page#pageframeframeselector !
