### ISSUE TITLE
[BUG] Version 1.8.0 doesn't read secure cookies

### ISSUE THREAD

**Issue by julianengel** [microsoft/playwright#5215]
**Context:**
- Playwright Version: 1.8.0
- Operating System: Mac
- Node.js version: v13.13.0
- Browser: Webkit, Firefox

  System:
    OS: macOS 10.15.7
    Memory: 1002.46 MB / 16.00 GB
  Binaries:
    Node: 13.13.0 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
 const storage = await context.storageState();
        await fs.writeFileSync(__dirname + '/cookies/auth.json', JSON.stringify(storage))

const cookies = await context.cookies().catch(e => { console.log("e: " + e) });
        console.log(cookies)
```

**Describe the bug**

When requesting the cookies either via` storageState()` or via `cookies()`, only the httpOnly=false cookies get returned, while 3 httpOnly cookies cannot be found. 

This started to happen today after upgrading to 1.8.0.

**Comment by julianengel** [comment]
Better formating

**Comment by aslushnikov** [comment]
@julianengel I've added a test to see if I can reproduce this easily. At the very least, basic fetching of http only cookies works with `context.cookies()` method. Can you share more about your scenario?

**Comment by yury-s** [comment]
Do you pass a URL as argument to `context.cookies()` ? This behavior has changed a bit as part of the fix for #4927 but from your description the problem is different.

**Comment by julianengel** [comment]
Hi, 

Apologies for the late reply, I didn't have my laptop most of today. 
@yury-s I am not passing in any arguments, I started to use `storageState` just yesterday to grab both `localhost` as well as `cookies`. The non-httpOnly cookies get set correctly surprisingly, and they are all being set for the same domain. 

I am saving cookies at two points, once when logging in, and once when starting a session in the app. 
During the login, everything works, the server sends the 6 cookies, however only 3 cookies get saved. Each does not have `httpOnly` enabled. The three that have it enabled, however, do not get saved. 

On the second time, when saving the cookies upon starting the session, only 1 cookie is returned total, that cookie is `httpOnly` and it gets saved correctly. 
Both cases use  `await page.waitForNavigation()`, and then retrieve the cookies, and it works as expected with non `httpOnly` cookies.

**Comment by julianengel** [comment]
**UPDATE**

Upon further investigation, it is not `httpOnly` that is causing this problem, it is the `secure` attribute.

The cookies for sessions don't use `secure`, but `httpOnly`, and the ones during auth used `secure`. 

When disabling `secure` for testing, the cookies show up and save correctly. 


I am not sure if I am supposed to replace the title of the issue now, add `secure` to the title or open a new one entirely?

**Comment by dgozman** [comment]
@julianengel Are you using https? Browsers have opinions on how to treat "Secure" cookies sent over http. For example, our WebKit ignores them.

**Comment by julianengel** [comment]
@dgozman the issue first appeared when testing over 'localhost:8080'. As far as I understood it, browsers handle localhost as a secure connection. (At least WebKit on Safari does). But to try and see if the issue got resolved, I tried with https over 'ngrok' and they still weren't being shown. 

But shouldn't 'localhost' be secure by definition?

**Comment by dgozman** [comment]
@julianengel Thank you for trying. From my local testing, WebKit on mac ignored secure cookies from localhost http.

I am out of ideas, without a repro/logs. Playing locally, I can get secure cookies from https sites, e.g. `https://www.microsoft.com/`. Would you mind sharing a script, or running with `DEBUG=pw:protocol` and posting the logs?

> But shouldn't 'localhost' be secure by definition?

Browsers have [different opinions](https://www.chromestatus.com/feature/6269417340010496) here, and it changes over time.
