### ISSUE TITLE
[Question] How to lock screen using playwright-android?

### ISSUE THREAD

**Issue by NareshMurthy** [microsoft/playwright#5216]
How do I ( lock screen / swipe down the notification center / press recent apps button )  using playwright android?
Thanks!

**Comment by pavelfeldman** [comment]
Here is the list of buttons you can `press`, I would start with the `Power` and then `swipe`?

https://github.com/microsoft/playwright/blob/master/types/android.d.ts#L119

**Comment by NareshMurthy** [comment]
Tried to lock with `await device.press("Power");` and `await device.press("body", "Power");` 
Throws me error, could you let me know, if I am doing anything wrong here.

**Comment by pavelfeldman** [comment]
`await device.input.press('Power');` - since your actions is not associated with any UI element, you just perform this event globally.

**Comment by NareshMurthy** [comment]
@pavelfeldman Thanks,  I was able to lock using `await device.input.press("Power");` , Is there a Key for recent app switcher?
After spending some time, I was able to swipe down the notification drawer with 
```
await device.input.swipe(
    { x: 1, y: 1 },
    [
      { x: 1, y: 10 },
      { x: 1, y: 80 },
    ],
    2
  );
``` 
But not sure if its the right way, is there any documentation for playwright-android so that i can look in to?

**Comment by pavelfeldman** [comment]
@NareshMurthy : `swipe`corresponds to [UiDevice.swipe](https://developer.android.com/reference/androidx/test/uiautomator/UiDevice#swipe(int,%20int,%20int,%20int,%20int)) I can also see `wakeUp` there that we did not plumb. Tell us if there are more methods you'd like to see on device!

**Comment by pavelfeldman** [comment]
Looks like you would want `sleep`, `wakeUp` and [`recentApps`](https://developer.android.com/reference/androidx/test/uiautomator/UiDevice#pressrecentapps) as well...

**Comment by NareshMurthy** [comment]
Yes! I am looking for a recentApps button as well

**Comment by NareshMurthy** [comment]
@pavelfeldman I have a test page, which captures active user time on the page, I noticed that, even after locking the screen / pulling down the notification bar, doesn't change the visibilityState of the page.
Something similar to this https://github.com/microsoft/playwright/issues/2286

Thanks!
