### ISSUE TITLE
[BUG] Codegen does not record actions after pressing concrete keys II

### ISSUE THREAD

**Issue by rmallof** [microsoft/playwright#5227]
The bug was fixed at https://github.com/microsoft/playwright/issues/5185

I'm able to reproduce the issue with the same reproduction steps using the current Playwright version

Can you please confirm if is actually resolved?

System:
    OS: Windows 10 10.0.19042
    Memory: 7.75 GB / 15.88 GB
  Binaries:
    Node: 15.4.0 - ~\scoop\apps\nodejs\current\node.EXE
    npm: 7.0.15 - ~\scoop\apps\nodejs\current\npm.CMD
  Languages:
    Bash: 4.3.11 - C:\Windows\System32\bash.EXE

node --version
v15.4.0

playwright --version
Version 1.8.0

**Comment by aslushnikov** [comment]
@rmallof it is fixed, but the patch is not pushed to the release branch yet. You can test it out though if you install the beta version:

```sh
$ npm i playwright@next # install playwright@next that has the fix
$ npx playwright -b ff --lang 'en'  codegen https://sforce.co/34AHdU4
```

The fix will be released in a few weeks in Playwright 1.9

**Comment by rmallof** [comment]
Thanks @aslushnikov :)

**Comment by nuthanqa** [comment]
playwright -record from here is missing from 11-11-2022. any updates on it
