### ISSUE TITLE
[BUG] launchPersistentContext hanging on "about:blank" [REOPENED]

### ISSUE THREAD

**Issue by bb1234cp** [microsoft/playwright#5228]
**Context:**
- Playwright Version: 1.7.1
- Operating System: Mac
- Node.js version: v14.15.1
- Browser: Chromium

**Code Snippet**
```js
const {chromium} = require('playwright');

(async () => {
  const options = {
                  headless : false, 
                  userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/87.0.4280.77 Mobile/15E148 Safari/604.1'
                }

                const browser = await chromium.launchPersistentContext(`udd1`, options)
                var [page] = await browser.pages();
                await page.goto("https://www.google.com/");
})();
```

**Describe the bug**

Sometimes the browser hangs on "about:blank". I've tested and it seems that if I even console.log(browser), then it doesn't even log it when this occurs... The only way to get past this is to refresh the page by using CMD + R on my keyboard. I'm unsure why this is happening as it doesn't occur every time I run my code. It seems as if the browser isn't even launching as it doesn't log.

https://github.com/microsoft/playwright/issues/4981

**Comment by bb1234cp** [comment]
I've tried logging the `browser` after creating and there is no log info of any browser... even though it's opened.

**Comment by bb1234cp** [comment]
I'm running playwright with vuetify. I'm not sure if that's an issue?

**Comment by aslushnikov** [comment]
@bb1234cp So the following snippet works reliably without issues for me on Mac. 

```js
const {chromium} = require('playwright');

(async () => {
  const options = {
    headless : false,
    userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/87.0.4280.77 Mobile/15E148 Safari/604.1'
  };

  const browser = await chromium.launchPersistentContext(`udd1`, options)
  var [page] = await browser.pages();
  await page.goto("https://www.google.com/");
})();
```

> I'm running playwright with vuetify. 

What does this mean? I was under impression that vuetify is a web framework so it shouldn't interfere how node.js process runs.

**Comment by bb1234cp** [comment]
It seems like the issue is when i change my code to `udd${counter}`. Counter add +1 when I want to run more than one context browsers. So I can use more than one instance separately.

**Comment by aslushnikov** [comment]
> It seems like the issue is when i change my code to udd${counter}. Counter add +1 when I want to run more than one context browsers. So I can use more than one instance separately.

@bb1234cp It looks like there's some more code than you show in the snippet :-) Can you share the whole thing? Maybe I'll be able to reproduce it locally and see what's gong on.

**Comment by bb1234cp** [comment]
Of course :) My bad ahahah 
```const options = {
            executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', 
            headless : false, 
            userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/87.0.4280.77 Mobile/15E148 Safari/604.1'
          }

          var counter = 0
          for (var i = 0; i < 2 ; i++) {
            if(counter < 2) {
              const browser = await chromium.launchPersistentContext(`udd${counter++}`, options)
              var [page] = await browser.pages();
              await page.goto("https://www.google.com/");
            }
          }```

**Comment by aslushnikov** [comment]
@bb1234cp well, the following does work perfectly for me as well:

```js
const {chromium} = require('.');

(async () => {
  const options = {
    headless : false,
    userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/87.0.4280.77 Mobile/15E148 Safari/604.1'
  };

  let counter = 0
  for (var i = 0; i < 2 ; i++) {
    if(counter < 2) {
      const browser = await chromium.launchPersistentContext(`udd${counter++}`, options)
      var [page] = await browser.pages();
      await page.goto("https://www.google.com/");
    }
  }
})();
```

I end up with 2 chromium being opened. Can you run my snippet and see if it works for you?

Also, speculation: could it be that you're running out of system resources and things are just very slow for you?

**Comment by bb1234cp** [comment]
Very strange as the same thing happens to me. It happens on my Vuetify application, but not on a normal js file. Regarding system resources it doesn't seem to be that either... This is weird.

**Comment by aslushnikov** [comment]
> It happens on my Vuetify application, but not on a normal js file

@bb1234cp Can you share this one with me so that I can run it locally as well?

**Comment by bb1234cp** [comment]
Of course! Where could i message you privately with the files? As I'd rather keep my project private.

**Comment by aslushnikov** [comment]
My corporate e-mail: anlushni [at] microsoft [dot] com

**Comment by bb1234cp** [comment]
I've just emailed you the folder from my email. Please let me know if you've received it :)

**Comment by aslushnikov** [comment]
@bb1234cp received it. How do run things there?

**Comment by bb1234cp** [comment]
cd and drag the folder into terminal, then run npm run electron:serve. To open the browsers press the play button.

**Comment by bb1234cp** [comment]
Hey, was just wondering if you've had the chance to look?

**Comment by aslushnikov** [comment]
@bb1234cp **thank you** the repro steps! I was able to debug this to a nasty race condition on our side. Sorry for this taking so long!

**Comment by bb1234cp** [comment]
> @bb1234cp **thank you** the repro steps! I was able to debug this to a nasty race condition on our side. Sorry for this taking so long!

No problem at all I’m glad you have debugged it! Appreciate your hard work. When will an update be expected to fix this ?

**Comment by aslushnikov** [comment]
As long as folks like my fix, we'll merge it and it'll be live tomorrow at the `playwright@next` channel. We'll have a `1.10` release some time soon (in a week?), and it'll be there as well.

**Comment by bb1234cp** [comment]
> As long as folks like my fix, we'll merge it and it'll be live tomorrow at the `playwright@next` channel. We'll have a `1.10` release some time soon (in a week?), and it'll be there as well.

Looking forward! Very happy you found the issue😁 Thanks again!
