### ISSUE TITLE
[Feature] Extract pdf data to text and read the data in playwright -typescript

### ISSUE THREAD

**Issue by chinnisanti** [microsoft/playwright#5234]
Let us know what functionality you'd like to see in Playwright and what is your use case.
Do you think others might benefit from this as well?

Save the pdf and extract the data from saved pdf to text file. Read the data from text file.
In playwright using type script.

**Comment by aslushnikov** [comment]
> Save the pdf and extract the data from saved pdf to text file

@chinnisanti PDF processing is outside of the scope for Playwright. However, instead of extracting text from PDF, 
you can extract it from the page itself. It can be as crude as 

```js
const allText = await page.textContent('body');
```

...or fine-grained if you know exact DOM elements you care about.

**Comment by dgozman** [comment]
Playwright does not read pdf files and will not extract any data from it. Closing this. If we misunderstood your feature request, please comment and we'll reopen.

**Comment by chinnisanti** [comment]
Yes I need the data from pdf

**Comment by mtbun** [comment]
I wrote a blog post about verify PDF content using Playwright and pdf-parse..

You can reach the blog post using [this link](https://medium.com/p/dd3cf6749f70).
