### ISSUE TITLE
[BUG] error while running folio test

### ISSUE THREAD

**Issue by Ppkd2021** [microsoft/playwright#5235]
Hey,
I am using npx folio command to execute the test cases with param set for video, reporter and browser. When browser param is sent alone then it does not throw below error but when I am executing using all three params then it throws below error.

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! convosight-web-client@1.0.0 test-playwright: npx folio playwright/e2e/user-onboarding-journey/onboarding-test-cases.test.ts --param browserName=chromium video
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the convosight-web-client@1.0.0 test-playwright script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Devashish Katyal\AppData\Roaming\npm-cache\_logs\2021-02-01T09_31_57_880Z-debug.log
```

- Playwright Version: 1.7.1
- Operating System: windows
- Node.js version: [e.g. 10.12, 10.14]
- Browser: Chromium
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  // ...
})();
```

**Describe the bug**

Add any other details about the problem here.

**Comment by aslushnikov** [comment]
@Ppkd2021 can you please share your folio test file?

**Comment by pavelfeldman** [comment]
Use -p video

**Comment by dgozman** [comment]
You should prefix each parameter with `-p`.

For example `npx folio playwright/e2e/user-onboarding-journey/onboarding-test-cases.test.ts -p browserName=chromium -p video`. Note double `-p`.

Please comment/reopen if that does not help.

**Comment by Ppkd2021** [comment]
Hey @dgozman, Thanks for reaching out. I tried with the below command but still, the result is the same no video is getting genrated.
`npx folio playwright/e2e/user-onboarding-journey/onboarding-test-cases.test.ts --timeout=120000 -p browserName=chromium -p video --reporter=junit,line`
Please check below test file which we are executing.
`import {afterEach, beforeEach, describe, expect, it} from '../../utils/fixtures';
import ManageGroupsPage from '../../pages/manageGroupsPage';
import FacebookUtilities from '../../utils/facebookUtilities';
import NoGroupsPage from '../../pages/noGroupsPage';
import SettingsPage from '../../pages/settingsPage';
import {baseUrl, usergroupAdmin} from '../../utils/credentials';
import {deleteUser, getUserIdByUsername, removeFacebookAccessTokenUsingUsername} from '../../utils/database.adapter';
import {generateEmail, getEmail} from '../../utils/testUtilities';

describe('User Onboarding 2.0', () => {
	let id: string, email: string, password: string;

	beforeEach(async ({page, context}) => {
		//@ts-ignore
		const facebookUtilities: FacebookUtilities = new FacebookUtilities(page, context);

		({id, email, password} = await facebookUtilities.TestUserCreation());
	});

	it('C8 : Verify when user logged into convosight with no Groups', async ({page, context}) => {
		//@ts-ignore
		const facebookUtilities: FacebookUtilities = new FacebookUtilities(page, context);
		//@ts-ignore
		const noGroupsPage: NoGroupsPage = new NoGroupsPage(page, context);
		//Arrange
		await page.goto(baseUrl);
		await expect(page.$(facebookUtilities.BtnLogin)).toBeDefined();
		await facebookUtilities.login(email, password);
		await expect(page.$(facebookUtilities.BtnProfileContinue)).toBeDefined();
		await facebookUtilities.profilePopupClickContinue();
		await facebookUtilities.groupsPageClickOnOk();
		await page.waitForSelector(noGroupsPage.ElmtWelcomeText);
		const innerText = await (await page.waitForSelector(noGroupsPage.ElmtWelcomeText)).innerText();
		//Assert
		expect(innerText).toContain(`Oops! No groups found`);
		expect(await page.title()).toEqual('Group Admin No Groups');
		//Act
	});
	it.only('FB access token is fetched and populated in the user table', async ({page, context}) => {
		//@ts-ignore
		const facebookUtilities: FacebookUtilities = new FacebookUtilities(page, context);

		//Arrange
		await removeFacebookAccessTokenUsingUsername(usergroupAdmin.username);

		await getUserIdByUsername(usergroupAdmin.username).then(param => {
			const {
				Items: [{fbUserAccessToken}]
			} = param;
			expect(fbUserAccessToken).toBeUndefined();
		});

		await page.goto(baseUrl);
		// //Act
		await expect(page.$(facebookUtilities.BtnLogin)).toBeDefined();
		await facebookUtilities.login(usergroupAdmin.username, usergroupAdmin.password);
		await page.waitForSelector(`[data-cs-label="Convosight"]`);
		await getUserIdByUsername(usergroupAdmin.username).then(param => {
			const {
				Items: [{fbUserAccessToken}]
			} = param;
			expect(fbUserAccessToken).not.toBeNull();
			expect(fbUserAccessToken).not.toBeUndefined();
		});
	});

	it('C10 : Verify when user logged into Convosight first time with Groups as moderator', async ({
		page,
		context,
		browser
	}) => {
		//@ts-ignore
		const facebookUtilities: FacebookUtilities = new FacebookUtilities(page, context);
		//@ts-ignore
		const manageGroupsPage: ManageGroupsPage = new ManageGroupsPage(page, context);

		//Arrange
		//Admin
		const generatedemail = (await generateEmail()).split(' ').join('');
		// @ts-ignore
		let adminContext = await browser.newContext();
		let adminPage = await adminContext.newPage();

		//@ts-ignore
		const adminFacebookUtilities = new FacebookUtilities(adminPage, adminContext);
		//@ts-ignore
		const adminManageGroupsPage = new ManageGroupsPage(adminPage, adminContext);
		await adminPage.goto(baseUrl);
		await expect(adminPage.$(facebookUtilities.BtnLogin)).toBeDefined();
		await adminFacebookUtilities.login(usergroupAdmin.username, usergroupAdmin.password);
		// await adminPage.click(`[name="__CONFIRM__"]`); - for additional fb pop up if comes in future.
		await adminPage.waitForSelector(`button.linker`).then(ele => ele.click());
		await adminPage.click(`[data-cs-label="Add Moderators"]`, {force: true});
		await adminManageGroupsPage.addModerator('Jitendra Choudary', generatedemail, '9879879877');
		const inviteEMail = await getEmail(
			`Advitiya Sujeet invited you to become a moderator for the group Test group`,
			generatedemail
		);
		expect(inviteEMail).toBeTruthy();
		await adminPage.close();
		await adminContext.close();

		//Moderator
		//@ts-ignore
		const noGroupsPage = new NoGroupsPage(page, context);
		//@ts-ignore
		const settingsPage = new SettingsPage(page, context);
		await page.goto(baseUrl);
		//Act
		await expect(page.$(facebookUtilities.BtnLogin)).toBeDefined();
		await facebookUtilities.login(email, password);
		await expect(page.$(facebookUtilities.BtnProfileContinue)).toBeDefined();
		await facebookUtilities.profilePopupClickContinue();
		await expect(page.$(facebookUtilities.BtnGroupsOk)).toBeDefined();
		await facebookUtilities.groupsPageClickOnOk();
		await noGroupsPage.init();
		await noGroupsPage.goToSettingsPage();
		await page.click(`[data-cs-id="c1da9b60-5f5d-41e6-841e-f646dadf5057"]`);
		await settingsPage.completeEmailVerification(generatedemail);
		await manageGroupsPage.init();

		//Assert
		await page.waitForSelector(`p.group-name`);
		const groupName = await (await page.$(`p.group-name`)).innerText();
		await expect(groupName).toEqual(`Test group`);
		const title = await page.title();
		expect(title).toEqual('Group Admin Manage Groups');
	});

	it('C12 : Verify when user logged into Convosight but not given groups permission', async ({page, context}) => {
		//@ts-ignore
		const facebookUtilities: FacebookUtilities = new FacebookUtilities(page, context);
		//@ts-ignore
		const noGroupsPage: NoGroupsPage = new NoGroupsPage(page, context);
		//Arrange
		await page.goto(baseUrl);

		//Act
		await expect(page.$(facebookUtilities.BtnLogin)).toBeDefined();
		await facebookUtilities.login(email, password);
		await expect(page.$(facebookUtilities.BtnProfileContinue)).toBeDefined();
		await facebookUtilities.profilePopupClickContinue();
		await expect(page.$(facebookUtilities.BtnGroupsNotNow)).toBeDefined();
		await facebookUtilities.groupsPageClickOnNotNow();
		//Assert
		const heading = await (await page.waitForSelector(noGroupsPage.ElmtWelcomeText)).innerText();
		await expect(heading).toEqual('Welcome Sai!');
		const title = await page.title();
		expect(title).toEqual('Group Admin No Groups');
	});

	it('C13 : Verify when the user logged into Convosight but not given permission and later given', async ({
		page,
		context
	}) => {
		//@ts-ignore
		const facebookUtilities: FacebookUtilities = new FacebookUtilities(page, context);
		//@ts-ignore
		const noGroupsPage: NoGroupsPage = new NoGroupsPage(page, context);
		//Arrange
		await page.goto(baseUrl);

		// //Act
		await expect(page.$(facebookUtilities.BtnLogin)).toBeDefined();
		await facebookUtilities.login(email, password);
		await expect(page.$(facebookUtilities.BtnProfileContinue)).toBeDefined();
		await facebookUtilities.profilePopupClickContinue();
		await expect(page.$(facebookUtilities.BtnGroupsNotNow)).toBeDefined();
		await facebookUtilities.groupsPageClickOnNotNow();
		await noGroupsPage.clickOnAddGroupsButton();
		await page.waitForSelector(noGroupsPage.ElmtWelcomeText);
		//Assert
		const heading = await (await page.waitForSelector(noGroupsPage.ElmtWelcomeText)).innerText();
		await expect(heading).toEqual('Oops! No groups found');
	});
	afterEach(async ({page, context}) => {
		//@ts-ignore
		const facebookUtilities: FacebookUtilities = new FacebookUtilities(page, context);
		await deleteUser(email);
		await facebookUtilities.TestUserDeletion(id);
	});
});
`
Also, please can you guide us on how to specify a path for the video and report generated in a specific folder.

**Comment by dgozman** [comment]
Where are you looking for video files? It should be located in a directory that's called something like `test-results/playwright/e2e/user-onboarding-journey/onboarding-test-cases/...`.

> Also, please can you guide us on how to specify a path for the video and report generated in a specific folder.

Use `FOLIO_JUNIT_OUTPUT_NAME=my-report-file` to write junit report to a file:
```sh
$ FOLIO_JUNIT_OUTPUT_NAME=my-report-file npx folio --reporter=junit,line
```

**Comment by Ppkd2021** [comment]
@dgozman The video is getting generated only for the failures. Earlier I was checking for videos when test cases were passing. 
Is there an option that videos can be generated for success scenarios as well?
