### ISSUE TITLE
[BUG] Webkit (docker image) cookie added but ignored

### ISSUE THREAD

**Issue by BrunoWilkinson** [microsoft/playwright#5236]
**Context:**
- Playwright Version: [1.7.1]
- Operating System: [Windows, WSL 2 (Ubuntu 20.04)]
- Node.js version: [14.15.4]
- Browser: [WebKit]
- Extra: [Docker image (mcr.microsoft.com/playwright:focal and bionic)]

Host OS (WSL):
![image](https://user-images.githubusercontent.com/14802661/106445600-20da5f00-6477-11eb-8a72-d9a931c1ea11.png)

Docker:
![image](https://user-images.githubusercontent.com/14802661/106445427-eb357600-6476-11eb-899d-99af2b9c0565.png)

**Code Snippet**
```typescript
it('Should login', async () => {
    await page.goto(ADMIN_URL);
    await page.fill(LOGIN_FORM_EMAIL, 'bart@zeigo.com');
    await page.fill(LOGIN_FORM_PASSWORD, 'password');
    await page.click(LOGIN_FORM_SUBMIT);
    await page.waitForLoadState('networkidle');
    expect(
      await page.isVisible("text=Hi Bart, you're managing Zeigo")
    ).toBeTruthy();
  });
```

**Describe the bug**

After doing the login process, the cookie is added to the browser context, (using jest-playwright) when accessing the other pages where the cookie auth is required to allow the user to enter, the cookie is ignored and cannot access the page. 
The cookie isn't been used and the backend just received an undefined cookie.
 Only affects when using WebKit with the docker.

Tested on OS X (with the latest update), without the docker instance, ran it locally, and it worked just fine.

**Comment by JoelEinbinder** [comment]
Does this line fail in docker but pass in vanilla WSL? Or does it pass in both, but then cookies don't work later when running in docker?
```
    expect(
      await page.isVisible("text=Hi Bart, you're managing Zeigo")
    ).toBeTruthy();
```

**Comment by BrunoWilkinson** [comment]
Tested on vanilla WSL, getting the same issue. It might not be docker problem but a Linux (Ubuntu 20.04) one ? 
Side note, tested on OS X, and it worked fine.

**Comment by BrunoWilkinson** [comment]
I know it's a little confusion, took me a while to figure out, here's the process:

- user login
- when successful creates a cookie and append it to the browser (session)
- to access the app the browser sends the newly created cookie to backend
- if the cookie is valid allow to fetch data and access the secure pages

Cookie dump (from the browser context)
```typescript
// using jest-playwright
console.log(await context.cookies());

{
        name: // value are created can't share it because of private repo
        value: // value are created can't share it because of private repo
        domain: // value are created can't share it because of private repo
        path: '/',
        expires: 1613035398,
        httpOnly: true,
        secure: true,
        sameSite: 'Strict'
      }
```

Haven't set up a route within playwright, but we do use a nginx container to create reserve proxy (only on dev environment)

Unfortunately, I can't share the repo like it's private.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.

**Comment by ptorrsmith** [comment]
Hi.  Having similar issue where the playwright docker image is being told to drive a safari/webkit browser, but no matter what we give it for the new browser context, it seems to be being ignored... in this case, the browser is expecting US format dates but we are expecting to give it UK format.
```
const context = await browser.newContext(
    {
      locale: 'en-GB',
    }
  );
```

Any follow up links re this sort of issue?

**Comment by mot4** [comment]
We are also experiencing the issue; it works launching Playwright directly but not within Docker.

**Comment by jth0024** [comment]
I'm also experiencing this issue on v 1.57.0 and up. Like others have mentioned, the tests pass on Mac OS but fail in Ubuntu. I thought it was the official docker image, but it also occurs in the GHA base Ubuntu image. 

I'm currently trying to debug it and will post an update if I find the root cause
