### ISSUE TITLE
[Feature] proper serialization of typed arrays

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#5241]
(Coming from https://github.com/microsoft/playwright/issues/5165)

Consider the following snippet:

```js
const {chromium} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  page.on('console', msg => console.log(msg.text()));
  await page.evaluate(e => console.log(e.constructor.name), new Uint8Array(8));
  await browser.close();
})();
```

**Expected**: `Uint8Array`
**Actual**: `Object`

As a result, passing typed arrays from node.js to browser context doesn't work reliably, causing some confusion.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.

**Comment by Tyriar** [comment]
This was my workaround, I wouldn't expect this to be particularly hard doing some `instanceof` checks. Definitely unexpected/inconvenient behavior.

Before:

```ts
  public async write(data: string | Uint8Array): Promise<void> {
    return this._page.evaluate(([term, data]) => {
      return new Promise(r => term.write(data, r));
    }, [await this._getHandle(), data] as const);
  }
```

After:

```ts
  public async write(data: string | Uint8Array): Promise<void> {
    return this._page.evaluate(([term, data]) => {
      return new Promise(r => term.write(typeof data === 'string' ? data : new Uint8Array(data), r));
    }, [await this._getHandle(), typeof data === 'string' ? data : Array.from(data)] as const);
  }
```

**Comment by Joozty** [comment]
@pavelfeldman 

It would be helpful to have an option to pass binary data directly to the evaluate function. Currently, the only workaround I see is to convert the data to base64 and then decode it within the evaluate function. It that is not possible it would be beneficial if the evaluate function were properly typed, as TypeScript does not raise a warning when binary data is passed.

```typescript
await page.evaluate((e) => {
  // TypeScript infers Uint8Array here, but this is inaccurate since it's a serialized object.
  console.log(e.constructor.name);
}, new Uint8Array(8));
````

**Comment by kekekuli** [comment]
How's the going? Is playwright support it nowdays?
