### ISSUE TITLE
[BUG] data attributes cannot selector by id selector

### ISSUE THREAD

**Issue by Amoyens1s** [microsoft/playwright#5253]
**Context:**
- Playwright Version: 1.8.0
- Operating System: Linux
- Node.js version: 14.15.4
- Browser: Chromium
- Testrunner: Jest

**Describe the bug**

Queries data-test-id whit id doesn't work.
Docs give three ways to query it.

Works

```javascript
await page.click('[data-test-id=cluster]');
await page.click('css=[data-test-id=cluster]');
```
Doesn't Work

```javascript
await page.click('data-test-id=cluster');
```

**Comment by dgozman** [comment]
Could you please share your snippet and page ur;? If the page is not public, right-clicking on the element in Developer Tools and selecting "Copy outerHTML" would work as well. Otherwise it's very hard to help - our tests indicate that `page.click('data-test-id=cluster')` should work.

**Comment by Amoyens1s** [comment]
> Could you please share your snippet and page ur;? If the page is not public, right-clicking on the element in Developer Tools and selecting "Copy outerHTML" would work as well. Otherwise it's very hard to help - our tests indicate that `page.click('data-test-id=cluster')` should work.

Thank you for your reply. The problem appeared in company's project. But I tried it on my local project at home and it works fine. I will check again when I arrive at the company. Now I can be sure that this is not a bug in playwright.
