### ISSUE TITLE
[BUG] Codegen code editor is opening in multiple frames & on-screen tools are hiding page elements

### ISSUE THREAD

**Issue by domderen** [microsoft/playwright#5257]
**Context:**

- Playwright Version: 1.9.0-next
- Operating System: macOS 10.15.7
- Node.js version: v12.19.0
- Browser: All

**Code Snippet**

```bash
npx playwright codegen -b chromium https://developer.mozilla.org/pl/docs/Web/HTML/Element/iframe
npx playwright codegen -b firefox https://developer.mozilla.org/pl/docs/Web/HTML/Element/iframe
npx playwright codegen -b webkit https://developer.mozilla.org/pl/docs/Web/HTML/Element/iframe
```

**Describe the bug**

When I open a page with an iframe in the Codegen view, and I click on the `pw-button-drawer` button to open the code editor for my session, this code editor is opened in the main page frame, as well as inside the iframes on the page. This can prevent the ability to record actions within iframes on the page, while the code editor is open.

Additionally, both the code editor, as well as the action buttons on the left hand side of the screen, are displayed on top of the website content. In specific cases those elements can block the visibility or ability to interact with target website's elements.

I would suggest creating a separate view for those elements, or displaying them outside the viewport size of the target page.

![chromium](https://user-images.githubusercontent.com/2360738/106602637-928cd880-655d-11eb-99c7-b2b03a3a2b57.gif)
![webkit](https://user-images.githubusercontent.com/2360738/106602657-97ea2300-655d-11eb-86c8-f69cfbad1611.gif)
![firefox](https://user-images.githubusercontent.com/2360738/106602673-9caed700-655d-11eb-9e25-1f6f711b6a20.gif)

**Comment by dgozman** [comment]
Should be fixed.

**Comment by domderen** [comment]
@dgozman Thanks very much for a quick turnaround on this one!

There was also this part of the bug:
> Additionally, both the code editor, as well as the action buttons on the left hand side of the screen, are displayed on top of the website content. In specific cases those elements can block the visibility or ability to interact with target website's elements.

Should I create a separate ticket for this one? With this issue, I guess the main problem are the action buttons on the left hand side of the screen, as the code editor can be closed. I ran into one instance where I wasn't able to train a "click" action, because the checkbox I wanted to click was exactly under those action buttons, and since the page had no scroll, I was not able to just position my checkbox in a different place on screen.

Maybe there is a way to make those action buttons draggable, so that user could move them to a different place if they are blocking the view?

**Comment by dgozman** [comment]
> Maybe there is a way to make those action buttons draggable, so that user could move them to a different place if they are blocking the view?

Yep, we recently made them draggable. However, we'll probably soon these actions completely, in favor of another UI approach. In any case, this should not be a problem anymore.

**Comment by domderen** [comment]
Ah awesome thanks!

**Comment by D1rtyDann** [comment]
excuse me, how to open the code editor in the browser? Looking forward to your help
