### ISSUE TITLE
[Question] page.waitForSelector issues with ReactJS

### ISSUE THREAD

**Issue by fcpunk** [microsoft/playwright#5259]
Hey folks,

I have a website written on ReactJs and have issues with page.waitForSelector. The page I'm trying to test has two parts:
1) on the left-hand side list of clickable items with the scrollbar 
2) on the right-hand side part there is a content (text), which changes based on which line is chosen in the list (1).
I added data-id attributes where necessary and want to go over the list of items checking that right side text renders correctly when I click on every item.
An example of list item selector: page.waitForSelector('li[data-id="123"]');
An example of rhs selector: page.waitForSelector('article[data-id="123"]');
Where data-id changes based on which item was clicked on.
At times page.waitForSelector just hangs on rhs and times out, although rhs rendered properly and respective data-id is in place. I tried to use { state: 'attached' } but it didn't help much. If I don't use data-id and just wait on article tag in the rhs selector playwright ends up getting out of sync. It just clicks as fast as possible through all items in the list not giving enough time for rhs article to render properly and my test fails due to incorrect content of the articles.

Could you please give me a hint how to do it in a proper way? Playwright 1.8.0, the latest version of ReactJS.

**Comment by dgozman** [comment]
You are doing the right thing, however something does not work out. Let us help you by providing more information.

- Could you please post (at least partially) your script?
- Could you try running with `DEBUG=pw:api` environment variable and post the logs here? For example, `DEBUG=pw:api node script.js`
- Pasting the dom structure would also help. For example, right-click the element in Developer Tools and use "Copy outerHTML" option.

> It just clicks as fast as possible

This makes sense, given that there is probably an `article` element present, although from the other item. Using `data-id` is great.

**Comment by fcpunk** [comment]
> Could you please post (at least partially) your script?
In the nutshell:
const page = await context.newPage();
page.setDefaultNavigationTimeout(60000);
page.setDefaultTimeout(60000);
const browser = await chromium.launch({headless: false, logger: {
                isEnabled: (name, severity) => name === 'browser',
                log: (name, severity, message, args) => console.log(`${name} ${message}`)
           }});
let listItems = await page.$$('li.list-item');
for await (let item of listItems) {
	let dataId = await item.getAttribute('data-id');
	await item.click();
	// once item is clicked there can be some queries running in the background to the back-end
	await page.waitForLoadState();
	// making sure that after click list-item became selected
	await page.waitForSelector('li.list-item[selected="true"][data-id="' + dataId + '"]'/*, { state: 'attached' }*/);
	// making sure that article was switched from one to another, this place causes a lot of trouble with occasional timeouts
	await page.waitForSelector('article[data-id="' + dataId + '"]'/*, { state: 'attached' }*/);
	// do some asserts with article internals and other things
}

> Could you try running with DEBUG=pw:api environment variable and post the logs here? For example, DEBUG=pw:api node script.js
  ....
  pw:api => elementHandle.getAttribute started +0ms
  pw:api <= elementHandle.getAttribute succeeded +6ms
  pw:api => elementHandle.click started +0ms
  pw:api attempting click action +1ms
  pw:api   waiting for element to be visible, enabled and not moving +0ms
  pw:api   element is visible, enabled and does not move +23ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +1ms
  pw:api   checking that element receives pointer events at (251,676.18) +4ms
  pw:api   element does receive pointer events +8ms
  pw:api   performing click action +0ms
  pw:api   click action done +205ms
  pw:api   waiting for scheduled navigations to finish +0ms
  pw:api   navigations have finished +8ms
  pw:api <= elementHandle.click succeeded +1ms
  pw:api => page.waitForSelector started +0ms
  pw:api waiting for selector "li.list-item[selected="true"][data-id="3765349260"]" to be visible +0ms
  pw:api   selector resolved to visible <li data-id="3765349260" data-se…>…</li> +8ms
  pw:api <= page.waitForSelector succeeded +7ms
  pw:api => page.waitForSelector started +0ms
  pw:api waiting for selector "article[data-id="3765349260"]" to be visible +1ms
  pw:api <= page.waitForSelector failed +4m
  Logger: TimeoutError: page.waitForSelector: Timeout 60000ms exceeded.
=========================== logs ===========================
waiting for selector "article[data-id="3765349260"]" to be visible
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
stackTrace: undefined
  pw:api => browserContext.close started +1ms
  ....

Visually it looks like browser clicked on сщккусе list item, item got selected and then it just gets stuck on article for some reason and times out. I checked in devtools that article with such data-id exists and I was able to find it by running selector tester in the console "playwright.$('article[data-id="3765349260"]')".

> Pasting the dom structure would also help. For example, right-click the element in Developer Tools and use "Copy outerHTML" option.
Can't do due to limitations.

**Comment by dgozman** [comment]
> Visually it looks like browser clicked on the list item, item got selected and then it just gets stuck on article for some reason and times out.

Do you see the new article on the right? If not, it sounds like a bug in the page. Logs indicate that Playwright did not find an element that matches the selector.

> Can't do due to limitations.

Unfortunately, that's as much as I can help with this information. Overall, I suspect some race condition in the page, but to debug it I wound need a repro script, or at least a page url.

**Comment by fcpunk** [comment]
> Do you see the new article on the right? If not, it sounds like a bug in the page. Logs indicate that Playwright did not find an element that matches the selector.
Yes, the new article is present on the right and I selector evaluates just fine in the console but playwright occasionally gets stuck and times out for some reason.

> Unfortunately, that's as much as I can help with this information. Overall, I suspect some race condition in the page, but to debug it I wound need a repro script, or at least a page url.
[Here's](https://www.glassdoor.co.uk/Job/qa-engineer-jobs-SRCH_KO0,11.htm) a closes sample I could find. I tried to run the script in the same way as I do for my company's internal portal and it fails randomly too.

**Comment by dgozman** [comment]
Here's a sample script that works for me locally. I guess we'll need a page url and/or repro script to help you.

```js
  await page.goto('https://www.glassdoor.co.uk/Job/qa-engineer-jobs-SRCH_KO0,11.htm')
  const ids = await page.$$eval('[data-test=jobListing]', els => els.map(e => e.getAttribute('data-id')));
  for (const id of ids) {
    console.log(id);
    await page.click(`[data-test=jobListing][data-id="${id}"]`);
    await page.waitForSelector(`article[data-id="${id}"]`);
    console.log(id + ' done');
  }
```

**Comment by fcpunk** [comment]
@dgozman Thank you, it helped. Looks like the issue was happening because I was keeping ElementHandle instances and iterating through them.
