### ISSUE TITLE
[Feature] Extracting the actions performed by the recorder

### ISSUE THREAD

**Issue by vigneshshanmugam** [microsoft/playwright#5266]
Thanks for the amazing project. Is there an easy way to get the IR (Intermediate Representation) of the playwright recorder/codegen so other tools can be built on top of it. 

Right now Playwright generates code for each action in the page using the IR and generates platform specific code. It would be cool to get these raw events from the Recorder without the final output so we can customize the output format. 

If there is none right now, happy to submit a feature request / PR if there is enough interest from the team.

**Comment by dgozman** [comment]
Could you please share more details of what you'd like to do? Do intend to run codegen and get some kind of json file? Or use codegen as a library? What kind of postprocessing do you think about?

**Comment by vigneshshanmugam** [comment]
Mostly to extract these actions and build another output format on top of the actions (Yes JSON output would be amazing) . Output can be used to generate code for different formats -> `playwright-test` or `@elastic/synthetics` or something similar. 

If there is a possibility of hooking in to the events for each action, that would also add the ability to build an UI alongside the recorder to modify the selectors and other elements before generating the final output.

**Comment by dgozman** [comment]
> Mostly to extract these actions and build another output format on top of the actions (Yes JSON output would be amazing) . Output can be used to generate code for different formats -> `playwright-test` or `@elastic/synthetics` or something similar.

This makes sense. Let's see whether there is more interest for this feature, so we could prioritize it.

> If there is a possibility of hooking in to the events for each action, that would also add the ability to build an UI alongside the recorder to modify the selectors and other elements before generating the final output.

Hooks during the execution to build UI alongside is a stretch, and not likely to happen in the short/middle-term.

However, if you have any ideas about recorder experience, we'd love to incorporate them directly into the recorder! It would be ideal to file a separate issue for that. PRs are welcome as well 😄

**Comment by vigneshshanmugam** [comment]
This makes sense. Let's see whether there is more interest for this feature, so we could prioritize it.

Sure. 

> However, if you have any ideas about recorder experience, we'd love to incorporate them directly into the recorder! It would be ideal to file a separate issue for that. PRs are welcome as well 😄

I have played around a bit multiple times, it really has a very good DX and works correctly most of the times without requiring any changes in code. Few places where recorder could be improved 

+ Selector engine where the output could be a bit more readable and provides multiple options like CSS classnames, Data attributes, XPath so user could pick one among the provided options. 

If there is a place where i could have a look at the roadmap, I am super curious to jump in and contribute as well. Thanks!

**Comment by dgozman** [comment]
> * Selector engine where the output could be a bit more readable and provides multiple options like CSS classnames, Data attributes, XPath so user could pick one among the provided options.

Yeah, this is something we will look into. It needs some UX ideas and overall thinking on where recorder is heading.

> If there is a place where i could have a look at the roadmap, I am super curious to jump in and contribute as well. Thanks!

Sorry, no roadmap as of today 😄 Recorder is not a big effort just yet, so we are mostly collecting feedback about how it is used and what is lacking.

**Comment by vigneshshanmugam** [comment]
I took sometime to go over the playwright codebase and also check the new recorder app. It is super cool and I can see myself using it everyday for the dev workflow. 

But, do you think we can move towards a API from the `RecordSupplement` that would emit events for the actions that are performed by the recorder and use this model for the `CodeGenerator` instead of having them tightly coupled as  its right now https://github.com/microsoft/playwright/blob/c57f1fc3908f47fe477fd4821fd82ba7e70c4799/src/server/supplements/recorderSupplement.ts#L92-L110

This would allow any tool to build on top of the playwright recorder API. Some of the things thats popping up immediately 

+ Playwright core library can emit a single schema (Intermediate format mostly JSON) which would be used by the inbuilt recorder app.
+ Other tools such as [Playwright test](https://github.com/microsoft/playwright-test), [Synthetics](https://github.com/elastic/synthetics/) can use these IR and generate the code based on their own syntax.

To give more clarity to the picture, we could build something like [Selenium IDE](https://www.selenium.dev/selenium-ide/) that purely changes the recording experience. Having the ability to do CURD operations on the GUI feels like a great addition to the playwright recorder experience rather than having the final format as code as its right now. 

I am not sure if this would align with playwright's roadmap and the release of 1.9.x but feels like a great addition. I am happy to give it a spin and do a PR for exposing the API from the supplement and using it in the inbuilt recorder. 

Please do let me know your thoughts.

**Comment by aslushnikov** [comment]
(cc'ing @pavelfeldman since he might find this topic interesting)

**Comment by vigneshshanmugam** [comment]
@pavelfeldman @dgozman Any ideas here?

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
