### ISSUE TITLE
[BUG]  Popup Timout Error on firefox 

### ISSUE THREAD

**Issue by Sreejithw** [microsoft/playwright#5267]
Context:

Playwright Version: 1.8.0
Operating System: Windows
Node.js version: 12.18.3
Browser: firefox
Extra: Also using jest version 26.6.0

This is the same issue as #4208 . I am reopening this issue since i am facing the same timeout issue when i updated playwright.
I have a page with some links that opens on a new tab when clicked. I handle the opening of the new tab and get additional screenshots inside the new tab. But i get a timeout error for 'popup' event in firefox although its working perfectly for chromium.

**Code Snippet**
```
for(let[i,boxes] of content.entries()){      
       if((content.name).split('_')[1] == serviceName){
           const [page1] = await Promise.all([
                     page.waitForEvent('popup'),
                     frame.click(`#${boxes.id}`)
            ]);
            await page1.waitForLoadState('networkidle');
        }
}
```

**Comment by aslushnikov** [comment]
it has been awhile and I can't reproduce this one; lots of bugs has been fixed since v1.8! 

If it reproduces for you, please re-file with a reproduction script that we can run locally. Thanks!
