### ISSUE TITLE
[Question] how to run headless on ubuntu server without docker ?

### ISSUE THREAD

**Issue by nongnoobjung** [microsoft/playwright#5280]
[Question] how to run headless on ubuntu server without docker ?

**Comment by anderslangballe** [comment]
You could have a look at the [Dockerfile for Playwright](https://github.com/microsoft/playwright/blob/master/utils/docker/Dockerfile.bionic), which is based on an Ubuntu image, to get an idea of what dependencies you need.

**Comment by dgozman** [comment]
Are you asking about what dependencies you need, or how to launch headless, or something else?
