### ISSUE TITLE
[Question] Does Playwright plan on supporting Yarn zero-installs setups?

### ISSUE THREAD

**Issue by cipivanov** [microsoft/playwright#5285]
I'm using Playwright in my Yarn projects. We are moving to using the [zero-installs](https://yarnpkg.com/features/zero-installs) approach. 

Just wondering if there are any plans for Playwright to move away from `postinstall` scripts to enable the above mentioned project setup?

Thanks! 🚀

**Comment by dgozman** [comment]
@cipivanov Playwright downloads browser binaries during `install` script. If you cache downloaded browsers somewhere and use `PLAYWRIGHT_BROWSERS_PATH`, there is no need for the actual install. See [installation docs](https://playwright.dev/docs/installation#managing-browser-binaries) for more information. Does that work for you?
