### ISSUE TITLE
[Feature] expose pid

### ISSUE THREAD

**Issue by talmobi** [microsoft/playwright#5299]
Let us know what functionality you'd like to see in Playwright and what is your use case.
Expose pid. Ex: similar to how puppeteer exposes pid.

Helps to get rid of zombies. Since neither puppeteer, or any kind of library that does this kind of thing all the way back to phantomjs, has ever managed to cleanup after itself reliably.

Do you think others might benefit from this as well?
Yes.

**Comment by mxschmitt** [comment]
Do you have screenshots / htop of which processes exactly leak? If it occurs on all the browsers etc. When you call ` await browser.close()` it should cleanup the browser processes.

**Comment by talmobi** [comment]
Only tested on chromium. Similar issues happen with puppeteer, though. Sometimes things don't get cleaned up. Crashes or whatnot. Exit handlers not properly cleaning up.

Ex: If `await browser.close()` is not called zombies may appear.

Having pid would allow external process to keep track of it. Making sure that once the node process is dead (process.pid) it will tree-kill the browser processes it spawned through playwright as a last resort.

**Comment by dgozman** [comment]
Does [BrowserServer.process()](https://playwright.dev/docs/api/class-browserserver#browserserverprocess) work for you?

**Comment by talmobi** [comment]
I haven't tried. Switched back to puppeteer. pid access should be available by default and/or zombies should be handled internally.

I'll put a task to try using BrowserServer instead and see if 1) zombies occur (probably will) and 2) if I can clean them using their pid's.

Will take a few days, though. Results sometime next week.

**Comment by dgozman** [comment]
> I'll put a task to try using BrowserServer instead and see if 1) zombies occur (probably will) and 2) if I can clean them using their pid's.

We'd be interested in a repro script that leaves zombies around - would definitely like to fix that.

**Comment by JoelEinbinder** [comment]
We should be much better than puppeteer about cleaning up zombies. If you see zombies please file a separate issue. Thanks!
