### ISSUE TITLE
[BUG] element was detached from the DOM

### ISSUE THREAD

**Issue by DigitalFlow** [microsoft/playwright#5307]
**Context:**
- Playwright Version: v1.8.0
- Operating System: Ubuntu 20.04
- Node.js version: 10.23.1 x64
- Browser: Chromium
- Extra: Headless on Azure DevOps

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
await Promise.all([
        page.waitForNavigation({ waitUntil: "load", timeout: 120000 }),
        page.click("#confirmButton", { timeout: 120000 })
]);
```

**Describe the bug**
First of all, thanks a lot again for providing this project. It made UI testing much more feasible for us and is on it's way to make UI testing a new standard inside our projects, where we previously didn't do any UI testing at all.

Since v1.8.0 clicking of page elements has become a little flaky on our side.
We use playwright for testing Dynamics 365 applications, I wrote a library for that: https://github.com/XRM-OSS/D365-UI-Test

The library has a function for deleting records: https://github.com/XRM-OSS/D365-UI-Test/blob/729688efb6183e87d81b424afccb8311e099b08a/src/xrm/Entity.ts#L161
When you click the delete button, a popup dialog appears where you have to confirm the deletion.
The button is clicked and the actions occur, but playwright seems to not notice that it clicked it?

It keeps trying, but in reality the button was clicked and it still thinks that it has to wait for clicking the button.
This is only happening sometimes, but it seems to be flaky.

Log:
```
TimeoutError: page.click: Timeout 120000ms exceeded.
=========================== logs ===========================
waiting for selector "#confirmButton"
selector resolved to visible <button tabindex="0" type="button" id="confirmButton" ar…>…</button>
attempting click action
waiting for element to be visible, enabled and not moving
element is visible, enabled and does not move
scrolling into view if needed
element was detached from the DOM, retrying
waiting for selector "#confirmButton"
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.page.click: Timeout 120000ms exceeded.
=========================== logs ===========================
waiting for selector "#confirmButton"
selector resolved to visible <button tabindex="0" type="button" id="confirmButton" ar…>…</button>
attempting click action
waiting for element to be visible, enabled and not moving
element is visible, enabled and does not move
scrolling into view if needed
element was detached from the DOM, retrying
waiting for selector "#confirmButton"
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.:
at Connection.sendMessageToServer (/home/vsts/work/1/s/node_modules/playwright/lib/client/connection.js:69:15)
at Proxy.<anonymous> (/home/vsts/work/1/s/node_modules/playwright/lib/client/channelOwner.js:44:61)
at _wrapApiCall (/home/vsts/work/1/s/node_modules/playwright/lib/client/frame.js:257:40)
at Frame._wrapApiCall (/home/vsts/work/1/s/node_modules/playwright/lib/client/channelOwner.js:72:34)
at Frame.click (/home/vsts/work/1/s/node_modules/playwright/lib/client/frame.js:256:21)
at _attributeToPage (/home/vsts/work/1/s/node_modules/playwright/lib/client/page.js:406:60)
at Page._attributeToPage (/home/vsts/work/1/s/node_modules/playwright/lib/client/page.js:205:20)
at Page.click (/home/vsts/work/1/s/node_modules/playwright/lib/client/page.js:406:21)
at Entity.delete (/home/vsts/work/1/s/node_modules/d365-ui-test/src/xrm/Entity.ts:163:24)
```

Thanks for your help.

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
I was able to reproduce the issue with playwright set to debug.
You can find the log here: https://pastebin.com/MNntEb8c

What I am wondering about:

My following code created an error:
```Javascript
console.log("Clicking confirm");

await Promise.all([
    this._page.waitForNavigation({ waitUntil: "load", timeout: this.xrmUiTest.settings.timeout }),
    this._page.click(D365Selectors.PopUp.confirm, { timeout: this.xrmUiTest.settings.timeout })
]);
```

I'm calling clicking of the confirm button only once, but the log seems to indicate that it is really trying to click the button twice:

```
  pw:api => page.click started +1ms
  pw:api waiting for selector "#confirmButton" +1ms
  console.log src/xrm/Entity.ts:163
    Clicking confirm
 
  pw:api   selector resolved to visible <button tabindex="0" type="button" id="confirmButton" ar…>…</button> +156ms
  pw:api   selector resolved to visible <button tabindex="0" type="button" id="confirmButton" ar…>…</button> +19ms
  pw:api attempting click action +2ms
  pw:api   waiting for element to be visible, enabled and not moving +1ms
  pw:api attempting click action +6ms
  pw:api   waiting for element to be visible, enabled and not moving +0ms
  pw:api   element is visible, enabled and does not move +24ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +1ms
  pw:api   checking that element receives pointer events at (1015.03,726.48) +5ms
  pw:api   element does receive pointer events +6ms
  pw:api   performing click action +1ms
  pw:api   click action done +19ms
  pw:api   waiting for scheduled navigations to finish +0ms
  pw:api   navigations have finished +6ms
  pw:api <= page.click succeeded +0ms
  pw:api   element is visible, enabled and does not move +122ms
  pw:api   scrolling into view if needed +0ms
  pw:api element was detached from the DOM, retrying +14ms
  pw:api waiting for selector "#confirmButton" +1ms
```
Do you have any idea what's happening in here? Is that a bug?

Thanks for your help.

Kind Regards,
Florian

**Comment by dgozman** [comment]
Hi Florian, thank you for your kind words!

Logs look like you are indeed clicking the button two times, concurrently, and only the first one succeeds. I'd look whether you somehow run two tests at the same time, and they share the page object.

The pastebin link says it's private, so I cannot see the source code, unfortunately. Could you please re-share it?

**Comment by DigitalFlow** [comment]
Hi @dgozman,

sorry, it seems the pastebin Team moderated my paste because there where typings into fields named "passwd", although I removed the passwords.
I removed these and auth related navigation events, you should be able to see this one:
https://pastebin.com/pbHhzKFk

As you can see in the logs, my "Clicking confirm" log is only visible once, so it seems my function really only issued one clicking of the page element, but playwright somehow executes two.

Thanks a lot for your help.

Kind Regards,
Florian

**Comment by dgozman** [comment]
@DigitalFlow I am looking at the logs and I see two clicks on the confirm button at the same time: one on the line 123-124, and another 299-300. One of them fails, and another finishes successfully.

I looked around a bit, and I think the issue is [this line](https://github.com/XRM-OSS/D365-UI-Test/blob/66662a1896c9abd1603a1279501e00fac7630eed/src/xrm/Navigation.ts#L48). It tries to click "confirm" and does not finishes because there was no dialog (and because there is Promise.race), and it keeps trying, eventually intercepting the real "confirm" click from the test, and the test click fails after that. Does that make sense?

**Comment by DigitalFlow** [comment]
Hi @dgozman,

thanks a thousand times for looking through the code.
I'm sure that you found the reason, that really makes sense. I totally did not consider that the Promises that did not "win" the race are really still running.
What is the best practice for dealing with cases like this? These confirm dialogs might be shown when leaving the page or they might not be shown. Promises in JS are not cancellable, so I have to think of another way.

Easiest solution seems to drastically reduce timeouts for these wait operators to only a few seconds, as they should either show fairly fast or not at all.
Is that how you would do it as well?

Again thank you very much for your help and sorry for submitting it as bug. I'll close this issue.

Kind Regards,
Florian

**Comment by dgozman** [comment]
@DigitalFlow Not much I can suggest in this situation. I guess shortening the timeout, and changing Promise.race to Promise.all to always wait for "click the confirm" to either succeed or fail is the closest to what you want.

**Comment by DigitalFlow** [comment]
Hi @dgozman,

I decided to only wait for the selector in Promise.race and to check whether the value that won the race is a page element (by checking if it has a click property).
If it is a page element, I click it, if not I just proceed. That seems very stable.

Again, thanks for your help.

Kind Regards,
Florian

**Comment by dloz-xbox** [comment]
@dgozman Hi! What are the implications of running 2 tests concurrently that use the same page object model? I've been experiencing some flaky tests, that I seem to have solved by using a getter in the POM instead of directly referencing the global locator instances, but I'm not sure how to explain why that fixed it. Thanks!
