### ISSUE TITLE
[BUG] iframe inside an iframe is not visible

### ISSUE THREAD

**Issue by DoroNahari** [microsoft/playwright#5313]
**Context:**
- Playwright Version: [1.7.1]
- Operating System: [Mac]
- Node.js version: [12, 14.9.0]
- Browser: [Chromium, Firefox]

  System:
    OS: macOS 11.1
    Memory: 1.25 GB / 32.00 GB
  Binaries:
    Node: 14.9.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    playwright: ^1.7.1 => 1.7.1 

**Describe the bug**
I have a website with an iframe inside iframe such as:
```
<iframe src="https://host-x/">
<iframe src="https://host-x/webview/index.html></iframe>

</iframe>
```

On chrome when i go to this webside i can see the inner iframe.
When i'm running a test with playwright on this website, the inner iframe is blank. (when i open dev-tools, it's suddenly appears)
When i run the same chromium by my self i can see the inner iframe.

my test config:
```
            browser = await chromium.launch({headless: isHeadless, args: ["--start-maximized"]});
            page = await browser.newPage(
                {
                    viewport: isHeadless ? {
                            width: 1920,
                            height: 1080
                        } : null
                }
            );
```
Any idea what could be the issue?

**Comment by dgozman** [comment]
Try launching like this, to see why Playwright makes it different:

```js
const browser = await chromium.launch({
  ignoreDefaultArgs: ['--disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading']
})
```

Otherwise, it's hard to help without a repro script.

**Comment by JoelEinbinder** [comment]
Feel free to reopen this with more info. Thanks!

**Comment by odeliat** [comment]
I'm trying to figure out this issue. 
I added the ignoreDefaultArgs but got the same result.

@dgozman 
What are the propose of those ignoreDefaultArgs  options?

@JoelEinbinder 
What more information do you need? 
I also tried it on a windows machine.

Can you please reopen this issue? we couldn't. 

Do you have any further ideas on how to solve this?

**Comment by dgozman** [comment]
@odeliat My snippet disabled some Chromium arguments that might affect iframes visibility.

> What more information do you need?
Do you have a repro script by any chance? It is hard to help without a script, or at least a page url that exhibits this behavior.

**Comment by odeliat** [comment]
One way to reproduce it is to open theia IDE gitpod on Chromium.

1. Open [Theia Gitpod](https://gitpod.io/#https://github.com/eclipse-theia/theia) on a regular browser.
2. Click Open on the master branch:
![Screenshot 2021-03-03 140404](https://user-images.githubusercontent.com/14539932/109803134-5b2b4d80-7c29-11eb-9c3b-689ce952dbcc.jpg)
3. Copy the url of the gitpod and open it at Chromium.
4. Login with your git/bitbucket account.
5. Wait for Theia to open.
6. Click on the extensions pane:
![Screenshot 2021-03-03 140706](https://user-images.githubusercontent.com/14539932/109803491-c83ee300-7c29-11eb-8fde-46c4bca3328c.jpg)
7. Search for 'Browser Preview' and install it:
![Screenshot 2021-03-03 140837](https://user-images.githubusercontent.com/14539932/109804131-9417f200-7c2a-11eb-9de3-6534401dd23f.jpg)
8. A new icon will appear on the left. Click on it and you need to see a webview but in the Chromium it dose not show
![Screenshot 2021-03-03 141529](https://user-images.githubusercontent.com/14539932/109804484-f7098900-7c2a-11eb-9811-6b93252b6de0.jpg)

You can do the same steps on a regular browser and see that it does show.
