### ISSUE TITLE
[Question] How to get websocket url from running server

### ISSUE THREAD

**Issue by danez** [microsoft/playwright#5314]
I have chromium running via `playwright.launchServer()` in k8s and want to connect to it from somewhere else via `playwright.connect()`. 
Previously we used puppeteer and it used to get the websocket URL from `/json/version`, but I assume this is the cdp websocket mentioned in there as `webSocketDebuggerUrl`? When I tried to connect with this websocket it did not work and I think I did run into #4054.
So how do I get the websocket URL? Is there a new endpoint to discover the websocket URL or is always the same URL?

I couldn't find anything about this in the docs.

I wanted to ask here before I start solving this myself by adding an extra HTTP entrypoint to our proxy in front of `playwright.launchServer()` and expose the ws url.

Thanks in advance :)

**Comment by dgozman** [comment]
Please help me understand the exact scenario you'd like to solve. Depending on how you launch Chromium and consume it, we might or might not be able to help you in the near future.

> I have chromium running via `playwright.launchServer()` in k8s and want to connect to it from somewhere else via `playwright.connect()`.

In this case [`browserServer.wsEndpoint()`](https://playwright.dev/docs/api/class-browserserver#browserserverwsendpoint) should work. It is specifically designed to be passed to `connect()` method.

> Previously we used puppeteer and it used to get the websocket URL from `/json/version`, but I assume this is the cdp websocket mentioned in there as `webSocketDebuggerUrl`? When I tried to connect with this websocket it did not work and I think I did run into #4054.
> So how do I get the websocket URL? Is there a new endpoint to discover the websocket URL or is always the same URL?

We are launching Chromium with remote debugging pipe, not websocket port, so it does not expose the CDP websocket url.

> I wanted to ask here before I start solving this myself by adding an extra HTTP entrypoint to our proxy in front of `playwright.launchServer()` and expose the ws url.

So it sounds like you actually want to do something similar to #4054? Run Chromium yourself, expose its own CDP endpoint, and connect to that?

**Comment by danez** [comment]
> In this case [`browserServer.wsEndpoint()`](https://playwright.dev/docs/api/class-browserserver#browserserverwsendpoint) should work. It is specifically designed to be passed to `connect()` method.

Yes, I also saw that in the docs. But it never mentions how to get the websocket URL from remote. 

So assume I have playwright started with `launchServer` somewhere, and then somewhere else (different machine on the other end of the world) I want to know the websocket URL so I can `connect` to it. How do I do that? 
That is my main question. `browserServer.wsEndpoint()` helps not much here, because it can only be run on the server side (`launchServer`), the client (`connect`) still does not know about the ws URL and it seems there is no way right now to "autodiscover" the websocker URL like with puppeteer? I have to transfer the websocket URL myself somehow to the client?


> We are launching Chromium with remote debugging pipe, not websocket port, so it does not expose the CDP websocket URL.

It is, if you navigate to `/json/version` on the launched server there is the cdp websocket mentioned in there.

> So it sounds like you actually want to do something similar to #4054? Run Chromium yourself, expose its own CDP endpoint, and connect to that?

No

**Comment by dgozman** [comment]
> > In this case [`browserServer.wsEndpoint()`](https://playwright.dev/docs/api/class-browserserver#browserserverwsendpoint) should work. It is specifically designed to be passed to `connect()` method.
> 
> Yes, I also saw that in the docs. But it never mentions how to get the websocket URL from remote.
> 
> So assume I have playwright started with `launchServer` somewhere, and then somewhere else (different machine on the other end of the world) I want to know the websocket URL so I can `connect` to it. How do I do that?
> That is my main question.
> `browserServer.wsEndpoint()` helps not much here, because it can only be run on the server side (`launchServer`), the client (`connect`) still does not know about the ws URL and it seems there is no way right now to "autodiscover" the websocket URL like with puppeteer? I have to transfer the websocket URL myself somehow to the client?

I am not sure I follow. How do you plan to visit `/json/version` from another computer? Are you talking about local scenario, where server and client are on the same computer? In this case, I'd suggest to print the `wsEndpoint()` to the terminal, or write it to a file, or set an environment variable - up to you. We are not making `wsEndpoint` a well-known location for security reasons, and expect the user of `BrowserServer` to share it in a way they find comfortable. Does that answer you question?
