### ISSUE TITLE
[Question] Ability to connect to running chromium instance?

### ISSUE THREAD

**Issue by Altneuj** [microsoft/playwright#5317]
This is a question/feature request if it is not possible. 

Currently I test my chromium web view that is running within a desktop application using puppeteer via `puppeteer.connect({browserWSEndpoint:myBrowserDebuggingEndpoint})` however I would like to switch over to playwright. Is there an equivalent for this in playwright? I have experimented with `chromium.connect({wsEndpoint})` but it seems that it only accepts endpoints set up by playwright not just running in the environment. 

Thanks!

**Comment by dgozman** [comment]
This is not possible currently, but we are working on it.

**Comment by Altneuj** [comment]
Awesome look forward to it, any specific thread I should watch for this? Thanks!

**Comment by dgozman** [comment]
This will be fixed in v1.9 by #5207.
