### ISSUE TITLE
[BUG] page.waitForFunction with { timeout: 0 } fails with a timeout

### ISSUE THREAD

**Issue by AviVahl** [microsoft/playwright#5323]
**Context:**
- Playwright Version: 1.8.0
- Operating System: Linux
- Node.js version: 14.15.4
- Browser: Chromium

**Code Snippet**

```javascript
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const ctx = await browser.newContext();
  const page = await ctx.newPage();
  await page.waitForFunction('window.definedWhenDone', { timeout: 0 });
})().catch(console.error);

```

**Describe the bug**

Above code explicitly specifies `timeout: 0`, and it seems to be ignored. Running the code results in `Timeout 30000ms exceeded.` being thrown.

**Comment by yury-s** [comment]
Second parameter in `waitForFunction` is the argument which is passed to the evaluated function, so what you need is:
```js
 await page.waitForFunction('window.definedWhenDone', null, { timeout: 0 });
```
This is indeed somewhat confusing but since the argument can be anything there is no way to tell the two apart.

**Comment by AviVahl** [comment]
Oh, wow. Can't believe I missed that. Thank you.
