### ISSUE TITLE
[Question] how to use proxy with playwright ?

### ISSUE THREAD

**Issue by Nattakitt-Tin** [microsoft/playwright#5325]
### I'm try to use proxy from ipvanish like this.

> const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({proxy:{server:'socks5://sin.ipvanish.com:1080',username:'myuser',password:'mypass' }});
  const page = await browser.newPage();
  await page.goto('https://getfoxyproxy.org/geoip/');
  await page.screenshot({ path: `example.png` });
  await browser.close();
})();

### but i'm get some error like this. 

> (node:12356) UnhandledPromiseRejectionWarning: page.goto: net::ERR_SOCKS_CONNECTION_FAILED at https://getfoxyproxy.org/geoip/
=========================== logs ===========================
navigating to "https://getfoxyproxy.org/geoip/", waiting until "load"
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at Connection.sendMessageToServer (C:\Users\nattakitt\node_modules\playwright\lib\client\connection.js:69:15)
    at Proxy.<anonymous> (C:\Users\nattakitt\node_modules\playwright\lib\client\channelOwner.js:44:61)
    at C:\Users\nattakitt\node_modules\playwright\lib\client\frame.js:80:71
    at Frame._wrapApiCall (C:\Users\nattakitt\node_modules\playwright\lib\client\channelOwner.js:72:34)
    at Frame.goto (C:\Users\nattakitt\node_modules\playwright\lib\client\frame.js:78:21)
    at C:\Users\nattakitt\node_modules\playwright\lib\client\page.js:270:60
    at Page._attributeToPage (C:\Users\nattakitt\node_modules\playwright\lib\client\page.js:205:20)
    at Page.goto (C:\Users\nattakitt\node_modules\playwright\lib\client\page.js:270:21)
    at C:\Users\nattakitt\Desktop\playwright_node\proxy.js:6:14
(node:12356) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process 
on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12356) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Pls, Let me know how to fix this code.

**Comment by dgozman** [comment]
It seems like you are using socks5 with authentication. Chromium does not support that. Please see issue #2425 - you'll need some middleware proxy that applies auth in between Chrome and your proxy.

**Comment by Nattakitt-Tin** [comment]
> It seems like you are using socks5 with authentication. Chromium does not support that. Please see issue #2425 - you'll need some middleware proxy that applies auth in between Chrome and your proxy.

thx for your help.
It seem like firefox and webkit does not support too ?
