### ISSUE TITLE
[Feature] Expose `playwright` object to user's pageFunction code.

### ISSUE THREAD

**Issue by domderen** [microsoft/playwright#5326]
I'd like to be able to use Playwright selector engine inside pageFunction code to be able to query selectors using the full capabilities of Playwright's selector engine, rather than being limited to standard `querySelector` & `querySelectorAll`.

And example code:

```typescript
const result = await page.evaluate(async () => {
  const elements = await playwright.$$('text=Something');
});
```

This would allow to query selectors without the need to move back and forth between playwright code & browser code.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
