### ISSUE TITLE
[Question] Run playwright in non-incognito chromium mode

### ISSUE THREAD

**Issue by veerendra1990** [microsoft/playwright#5328]
Hi,

Is there anyway i can run my test suits file in non-incognito chromium.
My case: i have to install the extension in chromium to login into my-website, in incognito chromium i cannot install my extensio , so please suggest how can i use the playwright.

**Comment by yury-s** [comment]
Please use [`launchPersistentContext`](https://playwright.dev/docs/api/class-browsertype?_highlight=launc#browsertypelaunchpersistentcontextuserdatadir-options) for such scenario, it will launch regular context for you.
