### ISSUE TITLE
[Question]Is there anyway i can run my test suits file in non-incognito chromium.?

### ISSUE THREAD

**Issue by veerendra1990** [microsoft/playwright#5329]
Hi,

Is there anyway i can run my test suits file in non-incognito chromium.
My case: i have to install the extension in chromium to login into my-website, in incognito chromium i can not install my extension due to (chromium limitation) , so please suggest how can i use the playwright.

**Comment by dgozman** [comment]
Here is Chromium-specific [documentation](https://playwright.dev/docs/api/class-chromiumbrowser/), look for "Chrome Extensions". Does that help?

**Comment by JoelEinbinder** [comment]
You can use `launchPersistentContext` to launch in non-incognito mode:

```js
const pathToExtension = require('path').join(__dirname, 'my-extension');
const userDataDir = '/tmp/test-user-data-dir';
const browserContext = await chromium.launchPersistentContext(userDataDir,{
  headless: false,
  args: [
    `--disable-extensions-except=${pathToExtension}`,
    `--load-extension=${pathToExtension}`
  ]
});
```
