### ISSUE TITLE
[BUG] Docs - misnamed launch parameters in python docs

### ISSUE THREAD

**Issue by Mattwmaster58** [microsoft/playwright#5336]
The [python docs](https://playwright.dev/python/docs/api/class-browsertype?_highlight=launch#browser_typelaunchkwargs) define the following parameters for `launch`:
```
handle_sighup <bool> Close the browser process on SIGHUP. Defaults to true.
handle_sigint <bool> Close the browser process on Ctrl-C. Defaults to true.
handle_sigterm <bool> Close the browser process on SIGTERM. Defaults to true.
```
However, this doesn't reflect what's in the libary.
The correct parameters are named `handleSIGHUP`, `handleSIGINT` and `handleSIGTERM`

**Comment by dgozman** [comment]
Thank you for the issue, we'll fix it!

Do you need to use these options, or just stumbled upon them? If the former, could you please share your scenario?

**Comment by Mattwmaster58** [comment]
I was messing around trying to solve this https://github.com/microsoft/playwright-python/issues/483 and knew of these options existence due to work with pyppeteer prior.

**Comment by Mattwmaster58** [comment]
Hmm, maybe the documentation is in sync with the alpha? Just based on this info on the alpha:

> The API has changed since the last 0.170.0 version:
>
>    Snake case notation for methods and arguments:
>
```py
    # old
    browser.newPage()

    # new
    browser.new_page()
```

**Comment by dgozman** [comment]
You are right, 1.8alpha and future version use snake case, so it should be `handle_sighup` and alike. I just double-checked the source code, sorry for not spotting that earlier.
