### ISSUE TITLE
[Question] How to listen to page url changes ?

### ISSUE THREAD

**Issue by mboullouz** [microsoft/playwright#5349]
How we can listen to page url changes ?
_Context_:
 I have a JS function (evaluated as string) that do several links clicks, each time the page reloaded I want to get the new url and perform some operations (in the context of the webdriver)
Eg:   
<pre>
 Page page = context.newPage();  
 page.evaluate("() => { " +  
                " MyBigFunction();"  + 
  "}"); 
  page.onUrlChange(xs-> {   /*  <== Need something like this or equivalente */
     //get the new url
     String newUrl = xs.getUrl(...);  
     if(newUrl matches .....) {
          //Do some operations...
         //Close page
      }  
  }  
);
</pre>

**Comment by dgozman** [comment]
> How we can listen to page url changes ?

Use [`framenavigated`](https://playwright.dev/docs/api/class-page/#pageonframenavigated) event.

```js
page.on('framenavigated', frame => {
  if (frame === page.mainFrame())  // Top frame url is the page url.
    console.log('new url', page.url());
});
```

Does this help?

**Comment by mboullouz** [comment]
> Does this help?

Seems not working (:

**Comment by dgozman** [comment]
> > Does this help?
> 
> Seems not working (:

Could you share your script please? What exactly does not work? What's happening instead? Do you see any console logs?

**Comment by mboullouz** [comment]
Hi,
Thanks for your time,
This is the code: 
<pre>
public static void main () {
    Playwright playwright = Playwright.create();
    Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions().withHeadless(false));
    BrowserContext context = browser.newContext( new Browser.NewContextOptions().withViewport(1024, 900));
    Page page = context.newPage();
    page.navigate("https://myapp-link-to-test.org");
    page.onFrameNavigated(xs -> {
        if(xs.equals(page.mainFrame())) {
            String url = xs.url();
            log.info("\n  CHANGE PAGE URL ", url); // <== this never printed, the url changed as I can verify on looking in the adress bar
            runUrl(url, page);
        }
    });
    runUrl(page.url(), page);
}

public static void runUrl(String url, Page page) {
  
    page.evaluate("() => { " +
            " do some clicks on urls using JS ..."   +
        "}");

    //get the current url just for logs
    Object r = page.evaluate("() => { " +
            " return window.location.href;" +
            "}");
    log.info("\n... objURL => : {} ", r);
}
 
</pre>

**Comment by JoelEinbinder** [comment]
@yury-s Do we have DEBUG=pw:api in Java? Whats the best way to debug this?

**Comment by yury-s** [comment]
```java
    page.navigate("https://myapp-link-to-test.org");
    page.onFrameNavigated(xs -> {
```
`page.navigate()` will wait for the navigation to commit and the method will only return after main frame has navigated so you are adding event listener after the event has already fired, just swap these two lines.

> @yury-s Do we have DEBUG=pw:api in Java?

Yes, we do support it in java too.

**Comment by yury-s** [comment]
You could simplify the code even further and remove the listener completely, just put the logging code after `page.navigate()`
