### ISSUE TITLE
[Question] How to download and save multiple files

### ISSUE THREAD

**Issue by Mbensler** [microsoft/playwright#5351]
Playwright will only allow me to save one file, even though it downloads both files in headless: true mode, only one is saved.

My code is working just fine and i can see both files being downloaded, and finishes the download, but only one is saved.

My code:

``` JS

const { chromium } = require('playwright');

(async () => {

    const browser = await chromium.launch({headless: false, downloadsPath: ''}); // {headless: false, slowMo: 1000}
    const page = await browser.newPage({acceptDownloads: true});

    await page.goto('https://mysite.com'); // just a random site right now. I know it doesn't have downloads.

   // Loop through downloads
   const classes = ['.jss31', '.jss37']
   const downloadLoop = async _ => {
       for (let index = 0; index < classes.length; index++) {
            const element = classes[index];
            page.click(element);
       }
   }
    
    // Download files
    const [ download ] = await Promise.all([

        // Start waiting for the download
        page.waitForEvent('download'),

        // Perform the action that initiates download
        downloadLoop(),
      ]);

      // Wait for the download process to complete
      const path = await download.path();
      await download.saveAs(download.suggestedFilename());

    await browser.close();
})();
```

How can i save all the files that i download and not just one? I am currently trying to save two files but in the future more.

**Comment by dgozman** [comment]
Well, this code only calls `download.saveAs` once, so it only saves a single download. Do it in the loop:

```js
const { chromium } = require('playwright');

(async () => {

    const browser = await chromium.launch({headless: false, downloadsPath: ''}); // {headless: false, slowMo: 1000}
    const page = await browser.newPage({acceptDownloads: true});

    await page.goto('https://mysite.com'); // just a random site right now. I know it doesn't have downloads.

    const classes = ['.jss31', '.jss37'];
    for (const cls of classes) {
        const [ download ] = await Promise.all([
            page.waitForEvent('download'),
            page.click(cls),
        ]);
        await download.saveAs(download.suggestedFilename());
    }
    
    await browser.close();
})();
```

Does that help?

**Comment by Mbensler** [comment]
> Well, this code only calls `download.saveAs` once, so it only saves a single download. Do it in the loop:
> 
> ```js
> const { chromium } = require('playwright');
> 
> (async () => {
> 
>     const browser = await chromium.launch({headless: false, downloadsPath: ''}); // {headless: false, slowMo: 1000}
>     const page = await browser.newPage({acceptDownloads: true});
> 
>     await page.goto('https://mysite.com'); // just a random site right now. I know it doesn't have downloads.
> 
>     const classes = ['.jss31', '.jss37'];
>     for (const cls of classes) {
>         const [ download ] = await Promise.all([
>             page.waitForEvent('download'),
>             page.click(cls),
>         ]);
>         await download.saveAs(download.suggestedFilename());
>     }
>     
>     await browser.close();
> })();
> ```
> 
> Does that help?

**Comment by Mbensler** [comment]
Thank you so much, it worked!

**Comment by bc-owner-auto** [comment]
Hi , just wanted to ask, what if one click on locator triggers download of 3 files.. not sure what to do in this case

**Comment by dgozman** [comment]
@bc-owner-auto You should use [`page.on('download')` event](https://playwright.dev/docs/api/class-page#page-event-download), put downloads into an array and then handle them.
