### ISSUE TITLE
[Question] Issues with file downloads using webkit-1423

### ISSUE THREAD

**Issue by jevgenijusmarinuskinas** [microsoft/playwright#5396]
Hello,

I've came across an issue with Webkit. I am unable to get any kind of file download - it is just getting opened in the browser window itself. The same applies to ZIP, PDF, JSON, etc.

Question: Is there any way to force Webkit to download a file? Using the html `download` attribute does not help. With Firefox and Chrome it is working just fine.

![image](https://user-images.githubusercontent.com/71834787/107500879-5c73d800-6b9f-11eb-8a31-c931d37b4d81.png)

My own simple HTML, which is not working:

```<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Download example page</title>
</head>
<body>
    <h1>File download example</h1>
    </br>
    <a href="files/example.zip" id="downloadLink" download="example.zip">example.zip</a>
</body>
</html>

**Comment by pavelfeldman** [comment]
Could you confirm that it does not works in headless mode too?

**Comment by jevgenijusmarinuskinas** [comment]
It does not, and in headless I am getting this error: `WAR The download attribute on anchor was ignored because its href URL has a different security origin.`

For Chrome and Firefox, the test is passing and file is downloaded. As I've mentioned, I am just executing the test against my local machine, with

`page.goto(`file:///${localPath}/example/examplePages/download.html`)`

And then downloading the file

**Comment by aslushnikov** [comment]
@jevgenijusmarinuskinas So this is a twofold issue:

1. different file URLs are considered different in Safari/WebKit. So this is why you get this `The download attribute on anchor was ignored because its href URL has a different security origin.` error. in order to avoid this, you'll have to setup a simple web server for testing.
2. On mac, headful webkit indeed did not download files marked with `download` attribute. This is fixed on tip-of-tree and will be released in v1.9.0

**Comment by jevgenijusmarinuskinas** [comment]
> @jevgenijusmarinuskinas So this is a twofold issue:
> 
> 1. different file URLs are considered different in Safari/WebKit. So this is why you get this `The download attribute on anchor was ignored because its href URL has a different security origin.` error. in order to avoid this, you'll have to setup a simple web server for testing.

@aslushnikov Does this mean, that on webkit we would be unable to use local file:/// like in Chrome and Firefox?

**Comment by aslushnikov** [comment]
@jevgenijusmarinuskinas yeah, that's how safari works 🤷‍♂️
