### ISSUE TITLE
[Question]: Occasionally getting "page.$: Execution context was destroyed, most likely because of a navigation.:" with re-trying to re-load page

### ISSUE THREAD

**Issue by sjurgis** [microsoft/playwright#5418]
I'm still kinda new to Playwright, although ironed most kinks so far. I'm using with with jest to test Salesforce. Occasionally Salesforce's pages would halt loading which is when I try to detect and reload:

```
global.reset = async (url, reloadCount = 1) => {
    if (reloadCount > 3) {
        throw new Error('Page reload count exceeded')
    }
    await jestPlaywright.resetPage()
    try {
        await page.goto(url, {
            timeout: reloadCount * 60 * 1000
        })
    } catch (e) {
        console.warn(e)
        console.warn('Reloading page')
        return await reset(url, reloadCount + 1)
    }
    const errorModal = await page.$('//*[text()="Please click Refresh."]')
    const propagationError = await page.$('//*[text()="Exception, DomainNotPropagated"]')
    if (propagationError || errorModal) {
        await page.screenshot({
            path: `screenshots/bad-page.png`,
        })
        console.warn('bad page detected, reloading page', url)
        return await reset(url, reloadCount)
    }
}
```

I do get error in title occasionally, but not always. The url does a couple for HTTP redirects and possibly JS ones.
I dunno how to repro outside of Salesforce.

**Comment by kababoom** [comment]
I have these too occasionally on different sites/scripts, also with earlier versions but am unable to steadily reproduce it. Ideas on what it is and how to fix or avoid it are very welcome.

**Comment by sjurgis** [comment]
So in essence I have this repro:

```
global.reset = async (url, reloadCount = 1) => {
    if (reloadCount > 3) {
        throw new Error('Page reload count exceeded')
    }
    await jestPlaywright.resetPage()
    try {
        await page.goto(url, {
            timeout: reloadCount * 60 * 1000
        })
    } catch (e) {
        console.warn(e)
        console.warn('Reloading page')
        return await reset(url, reloadCount + 1)
    }
    await page.waitForTimeout(15 * 1000)
    const errorModal = await page.$('//*[text()="Test across all modern browsers"]')
    console.log(errorModal)
    if (errorModal) {
        await page.screenshot({
            path: `screenshots/bad-page.png`,
        })
        console.warn('bad page detected, reloading page', url)
        return await reset(url, reloadCount + 1)
    }
}
describe('EDITOR COLUMNS', () => {
    beforeAll(async () => {
        await reset('https://shortner.com/7d7')
    }, 300000)
    test('aa', () =>{

    })
})

```

https://shortner.com/ is an URL shortener that uses JS to redirect page, takes approx. 15 seconds or so. Salesforce's redirects are normally faster than that, but CI being run in a container at multiple threads occasionally means some things run slower.

I wonder what's best way to deal with redirects in pw

**Comment by aslushnikov** [comment]
> Occasionally getting "page.$: Execution context was destroyed, most likely because of a navigation.:" with re-trying to re-load page 

@sjurgis  could you please post the whole error here with the stack trace? It might be that we didn't expect page to navigate somewhere.

**Comment by aslushnikov** [comment]
Closing this due to lack of feedback. Feel free to re-submit with more details!
