### ISSUE TITLE
How to  get the Request payload of the service in Playwright -Typescript

### ISSUE THREAD

**Issue by chinnisanti** [microsoft/playwright#5419]
Hi All,

I have to extract the request payload of the service in playwright automation chromium .
Please suggest .

Thanks,
Santi.

**Comment by aslushnikov** [comment]
@chinnisanti assuming you mean `POST` body of the request - use [`request.postData()`](https://playwright.dev/docs/api/class-request?_highlight=post#requestpostdata) method.

Here's a quick snippet:

```js
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  page.on('request', async request => {
    const postData = request.postData();
    if (postData)
      console.log(request.url() + ' ' + 'data: ' + postData.length);
  });
  await page.goto('https://microsoft.com');
  await browser.close();
})();
```
