### ISSUE TITLE
[Feature] Add url/method to the error message for waitForResponse method

### ISSUE THREAD

**Issue by viraxslot** [microsoft/playwright#5441]
Hi, team! I think it's a bit hard now to understand what's wrong with `waitForResponse` method, because we have no information about method or/and url in the error message.

Current error message:
```
Timeout while waiting for event "response"
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
```

So it's needed to dig into the code, because we have no idea what we've waited.

Proposal, add information about response url and method:
```
Timeout while waiting for event "response", requested POST https://test.com/api/v1/login
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
```

Real case: I've deleted '/' before api path because `axios` don't need it. But I used the same paths in UI tests and just concatenated them. With URL logged bug will be obvious from the message.

Thanks!

**Comment by dgozman** [comment]
Next v1.9 release should print string/regex url from `waitForRequest` and `waitForResponse` methods in the logs, including the timeout error message.
