### ISSUE TITLE
[BUG] typing fails in firefox

### ISSUE THREAD

**Issue by hatufacci** [microsoft/playwright#5448]
**Context:**
- Playwright Version: 1.9.0-next-1611308472000
- Operating System: Mac OS
- Node.js version: v12.19.0
- Browser: Firefox

Hey, i bumped into error with juggler protocol for Firefox browser: I just tried fill field via await elementHandle.type([id="profile_profileid-autocomplete"], 'test');.
element looks like:
<input id="profile_profileid-autocomplete" class="ui-autocomplete-input ui-widget ui-widget-content ui-corner-left" autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true">
the error is:
**Code Snippet**

```sh
(node:2483) UnhandledPromiseRejectionWarning: elementHandle.type: Protocol error (Page.dispatchKeyEvent): error in channel "content::page": exception while running method "dispatchKeyEvent" in namespace "page": Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsITextInputProcessor.keydown] _dispatchKeyEvent@chrome://juggler/content/content/PageAgent.js:689:13
_onMessage@chrome://juggler/content/SimpleChannel.js:165:37
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
 _onMessage@chrome://juggler/content/SimpleChannel.js:149:16
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42

=========================== logs ===========================
elementHandle.type("test")
============================================================
```
**Describe the bug**
Add any other details about the problem here.
In chromium, webkit it works ok

**Comment by mxschmitt** [comment]
Hi, is this for you reproducible? If so, a small minimal script to reproduce it would be super helpful.

**Comment by aslushnikov** [comment]
@hatufacci this looks very similar to #5460, but that one lacks a repro as well. Any chance you can share a script so that we can reproduce this locally?

**Comment by aslushnikov** [comment]
Merging this into #5460 as a dupe.
