### ISSUE TITLE
[BUG] Fill call sometimes fails on element that is visible

### ISSUE THREAD

**Issue by bradydowling** [microsoft/playwright#5460]
See #9776 for a reliable repro.

---

**Context:**
- Playwright Version: 1.8.0
- Operating System: macOS Mojave
- Node.js version: 14.15.0
- Browser: Firefox

```
  System:
    OS: macOS Mojave 10.14.6
    Memory: 693.14 MB / 16.00 GB
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
```

**Code**

```
const { firefox } = require('playwright');
const envMap = require("../env-vars");
require('dotenv').config();


const deploy = async (page, { env, terraformDockerTag, applicationDockerTag, versionNum }) => {
  let buildNum = "No build num retrieved";
  let successMessage = 'Latest master deployed successfully';
  await page.goto(envMap[env].deploy);
  await page.click('//a[normalize-space(.)=\'Build with Parameters\' and normalize-space(@title)=\'Build with Parameters\']');
  await page.waitForLoadState('networkidle');

  if (env === "dev" && terraformDockerTag && applicationDockerTag) {
    console.log(`⏳ [DEV] Deploying latest master...`);
    await page.fill('input.setting-input', terraformDockerTag);
    await page.fill('input[value="APP_VERSION"] + input.setting-input', applicationDockerTag);
  }
  else if (versionNum) {
    console.log(`⏳ [${env.toUpperCase()}] Deploying ${envMap[env].prevEnv} build #${versionNum}...`);
    const buildButtonSelector = 'input[name="_.buildNumber"]';
    await page.waitForSelector(buildButtonSelector, { timeout: 0 });
    await page.fill(buildButtonSelector, versionNum);
    successMessage = `Deployed build #${versionNum} successfully`;
  }
  else {
    throw new Error("Missing params needed to deploy");
  }

  await page.click('//button[normalize-space(.)=\'Build\']');
  await page.waitForLoadState('networkidle');
  await page.goto(`${envMap[env].deploy}/lastBuild/console`);
  await page.waitForLoadState('networkidle');
  buildNum = getBuildNum(page);
  await proceedWithDeploy(page);
  await page.waitForSelector('pre:text("Finished: SUCCESS")', { timeout: 0 });
  console.log(`✅ [${env.toUpperCase()}] ${successMessage}`);

  return buildNum;
}

const getBuildNum = async (page) => {
  const buildNumText = await page.evaluate(() => {
    const breadCrumbs = [...document.querySelectorAll('.breadcrumbBarAnchor')];
    return breadCrumbs[breadCrumbs.length - 1].innerText;
  });
  return buildNumText.split("#")[1];
};

const proceedWithDeploy = async (page) => {
  const proceedButtonSelector = '//a[normalize-space(.)=\'Proceed\']';
  await page.waitForSelector(proceedButtonSelector, { timeout: 0 });
  await page.click(proceedButtonSelector);
};

(async () => {
  const browser = await firefox.launch({ headless: false, slowMo: 50 });
  const page = await browser.newPage();

  const devBuildNum = await deploy(page, { env: "dev", terraformDockerTag, applicationDockerTag });
  const qatBuildNum = await deploy(page, { env: "qat", versionNum: devBuildNum });
  await deploy(page, { env: "stg", versionNum: qatBuildNum });

  await browser.close();
})();
```

**Describe the bug**

I'm running a Playwright script on a Jenkins page that has input elements. When I try to `fill` one of the inputs with text, it fails with this error:

```
(node:3337) UnhandledPromiseRejectionWarning: page.fill: Protocol error (Page.insertText): error in channel "content::page": exception while running method "insertText" in namespace "page": Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsITextInputProcessor.commitCompositionWith] _insertText@chrome://juggler/content/content/PageAgent.js:891:32
```

I've tried running with `DEBUG=pw:api environment` enabled but the logs there aren't too helpful. From the normal console log I get the following log:

```
waiting for selector "input[name="_.buildNumber"]"
  selector resolved to visible <input value="" type="text" name="_.buildNumber" class=…/>
elementHandle.fill("54")
  waiting for element to be visible, enabled and editable
  element is visible, enabled and editable
```

So it seems like the element exists and can be edited but for some reason Playwright is unsuccessful at trying to fill it. What am I missing here?

**Comment by aslushnikov** [comment]
@bradydowling this looks like a bug, but we'd need more info to fix it. Any chance you can share more details? If there's a script that we can run locally to reproduce this, it'd be fantastic.

**Comment by aslushnikov** [comment]
@bradydowling There's nothing suspicious in the code. Any chance you can share a URL as well? I'd need to experience this bug myself so that I can debug it.

**Comment by dgozman** [comment]
This is coming from `TextInputProcessor::PrepareKeyboardEventToDispatch`, where it calls `aKeyboardEvent.InitEditCommandsFor` and fails. Not yet sure why.

**Comment by bradydowling** [comment]
As mentioned, this is on a Jenkins instance so probably not the brightest thing to share a link to it. That said, it’s on a VPC and requires VPN access anyway so there is no chance unless you join Chewy 😜

**Comment by chrisdavies** [comment]
I've got a similar issue when trying to get Firefox to type into a contenteditable. Nothing happens. Works fine in webkit / chromium.

**Comment by aslushnikov** [comment]
📣 Everybody: this looks like a real bug in Firefox, but in order for us to fix it **we need a repro** (something we can run locally to experience & debug this issue).

- If you have one, please share with us!
- if you can't share publicly, I'd be happy to share my corp email to communicate privately.

**Comment by Tomm1ch** [comment]
I might have found a reproducible situation in firefox where this bug can be tested. I just tried running the script with the bug multiple times and every time the error occured. 
However, I don't want the code or page to be shared publicy. Could you therefore send me your contact details?

**Comment by aslushnikov** [comment]
@Tomm1ch - for sure! anlushni [at] microsoft [dot] com

**Comment by TimarTimar** [comment]
"playwright": "^1.12.2
firefox
windows 10
node: v14.15.5

This happened with me also.

I was able to reproduce it multiple times with the following scenario:
1. run script
2. the script needs my permission to move forward so I have to admit it on another browser.
3. then the script moves forward and eventually type

Case: (I do nothing else, dont click anywhere just the mentionted points
If I open the other browser with alt+tab and click admit then I got the error
If I open the other browser by click minimize and click to open the other browser and click admit I dont get the error

Hope it helps! :)
![useragent](https://user-images.githubusercontent.com/31423611/123257729-d5daea00-d4f2-11eb-9afa-040dd5ad11c6.jpg)

**Comment by b4s36t4** [comment]
I've seen this when ever I give input manually.!

my code 
```js
element.type('string')
```
if my code fails, then I'll type that manually

when ever the type get called again, I see this error.!

I want to say that, if input or any editable field had contact manually (type | fill) this comes when next type method called.!

I've seen this error some times like @TimarTimar Said. When you had contact with the other browser like real Firefox browser without minimizing it this error comes then too.

**Comment by mirao** [comment]
Sometimes we hit it in our [CodeceptJS](https://codecept.io/helpers/Playwright/) test too, with Playwright 1.14 + Firefox 91, when the test is filling a value in a "filter" field.
But it's an occasional issue and unable to reproduce it reliably. 
The issue doesn't happen in Chromium (we run the test daily in Chromium and Firefox), so it's a Firefox issue only.

Error + stack:
```
elementHandle.type: Protocol error (Page.dispatchKeyEvent): error in channel "content::page": exception while running method "dispatchKeyEvent" in namespace "page": Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsITextInputProcessor.keydown] _dispatchKeyEvent@chrome://juggler/content/content/PageAgent.js:563:13
_onMessage@chrome://juggler/content/SimpleChannel.js:165:37
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
 _onMessage@chrome://juggler/content/SimpleChannel.js:149:16
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42

=========================== logs ===========================
elementHandle.type("ATSchool20038596558348876")
============================================================
    at Playwright.fillField (/workspace/node_modules/codeceptjs/lib/helper/Playwright.js:1275:14)
    at async Object.setDates (fragments/EditTestAvailability.js:46:39)
    at async Test.<anonymous> (SchoolTestAvailability_test.js:56:17)
```
A screenshot from the test shows that the field was focused by the method "fillField", but no text was filled in.
![image](https://user-images.githubusercontent.com/12584138/130350127-2b560fd6-e2f3-424e-b8cb-7456643e5cc1.png)
