### ISSUE TITLE
[BUG] Installation retry is broken

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#5462]
https://github.com/microsoft/playwright/pull/5461/checks?check_run_id=1896586548

Is an example when it fails on misc bots. Is it trying to unzip a 404 html file?

**Comment by mxschmitt** [comment]
I also saw this error before in a new empty Docker node:15 image but was not able to reproduce it.

**Comment by aslushnikov** [comment]
Could not reproduce!
