### ISSUE TITLE
[Feature] Android: Run as root, do not require "#enable-command-line-on-non-rooted-devices" chrome flag

### ISSUE THREAD

**Issue by tobiasmuehl** [microsoft/playwright#5463]
To run Playwright on Android the mentioned chrome flag needs to be set on the device. When resetting chrome user data (e.g. through `pm clear com.android.chrome`), the flag is reset. It would be beneficial to be able to launch chrome with the command line settings inline for users that have a rooted device. 

I believe these lines are relevant, although I could not figure out how to change them

https://github.com/microsoft/playwright/blob/449adfd3ae28b69c43de03c1ee43b3443c422d69/src/server/android/android.ts#L241-L244

**Comment by pavelfeldman** [comment]
What happens when you run it against the rooted device today? It does not respect the command line params?  Could you try replacing /data/local/tmp/ with /data/local/ in the line that you found and give it a try?

**Comment by tobiasmuehl** [comment]
Running it on the rooted device without changing code is indistinguishable from running it on a non-rooted device. Playwright opens the Chrome app, fails to control it, then stalls forever. The debug logs indicate that it's waiting for a socket (indefinitely).

Will try the patch you described and report back.

**Comment by tobiasmuehl** [comment]
I can't explain why but it works now, I lost the original node_modules/ folder and reinstalled with yarn and then it worked right away, without patching the line of code you mentioned. :confounded: :smile: 

This issue can be closed
