### ISSUE TITLE
[Question] How to control the timeout for waitForSelector for more than 2 seconds?

### ISSUE THREAD

**Issue by visenzeviclim** [microsoft/playwright#5468]
Hi I have tried to use the waitForSelector, as I am expecting an element to show 10 seconds later. However, it appears that as of now, the maximum allowable for timeout appears to be at 2000ms.
```
await page.waitForSelector("h3[class=\"text-muteed\"]",{
            waitFor:"visible",
            timeout:10000
});

// Log
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. 

```

However, I am able to 'fail' my execution if I were to set the timeout to be lesser than 2 seconds, i.e.
```
await page.waitForSelector("h3[class=\"text-muteed\"]",{
            waitFor:"visible",
            timeout:1990
});

// Log
page.waitForSelector: Timeout 1900ms exceeded.
=========================== logs ===========================
waiting for selector "h3[class="text-hahazzzz"]" to be visible
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.

```

As such, is there a way to control this timeout ?

**Comment by creage** [comment]
It is not PW who fails, but mocha. PWs default timeout is 30 seconds.

Try to change your timeout by command
```json
"scripts": {
    "test": "mocha --timeout 10000"
}
```

**Comment by visenzeviclim** [comment]
Alrighty. Thanks !!!!

**Comment by tommyh** [comment]
If you are using the playwright test runner, you can pass it on the command line:

```
npx playwright test --timeout=10000
```

If you want to disable the timeout because you are doing a `page.pause()`, then you can pass a timeout of `0`:

```
npx playwright test --timeout=0

# or put it in your playwright.config.js
module.exports = {
  timeout: 0,
};
```
