### ISSUE TITLE
[BUG] CRON MacOS Big Sur with Playwright

### ISSUE THREAD

**Issue by PaulRosset** [microsoft/playwright#5469]
**Context:**
- Playwright Version: 1.8.0
- Operating System: macOS Big Sur 11.2.1 Intel Chip
- Node.js version: 12.3.1
- Browser: Tested on Chromium
- Extra: Cron Jobs Env

Hello, Thanks for the great work on Playwright!

We are experiencing an issue since we updated our Mac Mini to the newest version of the OS, Mac OS Big Sur 11.2.1.

We are launching Daily playwright jobs from CRON.

It seems that when we launch the script from the traditional CLI, it works fine, but launching it from a CRON job, we get that error:

![image](https://user-images.githubusercontent.com/14330374/108042906-b9a8d700-7040-11eb-8f02-034405ef9602.png)

I barely dived into the code from my `node_modules`, and it seems that it is those lines below that keep us away from working:

[Lines](https://github.com/microsoft/playwright/blob/ac1599cc2c5fb7de909e0930d0f4aed5cf1b1158/src/utils/registry.ts#L136)

```js
 let arm64 = false;
  // BigSur is the first version that might run on Apple Silicon.
  if (major >= 11) {
     arm64 = child_process_1.execSync('sysctl -in hw.optional.arm64', {
        stdio: ['ignore', 'pipe', 'ignore']
     }).toString().trim() === '1';
 }
``` 

By patching the `node_modules` file, we managed to make it work.

**Comment by aslushnikov** [comment]
@PaulRosset sorry for the regression! This will be fixed in tonight's nightly release. We might also release 1.8.2 with the fix shortly.
