### ISSUE TITLE
[BUG] wrong innerText on webkit

### ISSUE THREAD

**Issue by amit-parizian-erudite** [microsoft/playwright#5478]
**Context:**
- Playwright Version: 1.8.1
- Operating System: Mac
- Node.js version: 14.15.4
- Browser: webkit

```
test(
    "Log in with mail and password",
    async () => {
      await loginPage.login(TestManager.USER_EMAIL, TestManager.USER_PASSWORD);
      expect(await loginPage.getUserName()).toBe(TestManager.USER_NAME);
    },
    TestManager.TIMEOUT
  );

//in LoginPage
async getUserName() {
    return this.page.innerText("data-test-id=user-menu-button");
  }
```

Hi!
the test above is supposed to get username written on the user menu button via innerText.
when running this test on chromium, it passes. when running it on webkit, it fails, since the innerText received is with two new lines appended to it. meaning: I expect "username" but get "username\n\n". and as I said, on chromium I get "username" as expected.

Thanks in advance!

attached is the failure log, where you can see the 2 extra new lines.
![image (1)](https://user-images.githubusercontent.com/78478421/108180315-4752f800-710f-11eb-9d40-5300fbb8b6a2.png)

**Comment by mxschmitt** [comment]
Hello, is it possible that you provide the inner html of the `data-test-id=user-menu-button` element? For example with the `innerHTML` method, then it should be probably possible to reproduce.

**Comment by pavelfeldman** [comment]
Browsers are different and innerText is layout-dependent, so you naturally get different values in different browsers. Maybe you wanted to use `textContent` instead of `innerText`?

**Comment by pavelfeldman** [comment]
https://stackoverflow.com/questions/35213147/difference-between-textcontent-vs-innertext

**Comment by amit-parizian-erudite** [comment]
Hi! thanks for your answers and sorry for the late replay.
so I tried doing it with textContent as you suggested, and it worked, but in a different place it didn't. It returned the string with space at the start and at the end, so I had to use the trim() function. anyway, by using the trim() function it works also with innerText so I just stayed with that...
Do you have any other ideas?
Thanks a lot in advance.

**Comment by aslushnikov** [comment]
> it returned the string with space at the start and at the end, so I had to use the trim() function. 

@amit-parizian-erudite text content doesn't trim spaces - so using `trim()` to do so if you need this is a perfectly fine solution.

**Comment by amit-parizian-erudite** [comment]
I know it's not supposed to trim on it's own, but I meant that when using <innerText> it returns without spaces at the start and at the end, while using <textContent> it returns with them

**Comment by aslushnikov** [comment]
@amit-parizian-erudite Ah, this is a web API question then! The short answer would be that `innerText` is doing some magic before returning text which is usually hard to rely upon. `textContent` is standardized and aligned between browsers.

There's more info on the web regarding this, e.g.: https://stackoverflow.com/questions/35213147/difference-between-textcontent-vs-innertext 

Closing this bug then; feel free to submit a new issue if something seems wrong with Playwright!

**Comment by amitpariz** [comment]
thanks!
