### ISSUE TITLE
[BUG] Unable to click on hover menu item with codegen

### ISSUE THREAD

**Issue by arjunattam** [microsoft/playwright#5481]
**Context:**
- Playwright Version: 1.9.0-next-alpha-feb-17-2021
- Operating System: macOS
- Browser: Chromium

**Describe the bug**

When I hover over "pricing" on [this page](https://github.com/marketplace), I want to be able to click on a menu item with codegen. The menu unexpectedly disappears.

![Kapture 2021-02-17 at 22 34 03](https://user-images.githubusercontent.com/284612/108239859-51f1a980-7170-11eb-9f4b-3934d021fc06.gif)

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
