### ISSUE TITLE
[Question] Close dialog a popup

### ISSUE THREAD

**Issue by ortamir** [microsoft/playwright#5482]
Hi,

I'm looking to close an alert that is fired on a popup.
Here is what I'm trying to do:

```
async with main_page.expect_popup() as popup_info:
        await main_page.click('#Button')

new_page= await popup_info.value
new_page.on("dialog", handle_dialog)
```

I would like to add the listener to the new page before it's created (but I don't know how) or add a global listener to all pages in the browser.

Since I couldn't find a function in the playwright docs I have tried to use a CDP session (BTW reloading the page and adding the listener works in this example but not in my big example):

```
import asyncio
from playwright.async_api import async_playwright, ChromiumBrowserContext, Page

async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=False)
        page: Page = await browser.new_page()
        page.on("dialog", lambda dialog: dialog.accept())
        await page.goto("http://jsfiddle.net/c7mjvnau/2/")
        print(await page.title())
        frame = await (await page.query_selector('#editor > div.panel-v.right > div.panel-h.panel.resultsPanel > div > div.iframeCont > iframe')).content_frame()
        async with page.expect_popup() as popup_info:
            await frame.click('body > button')
        new_page = await popup_info.value
        # new_page.on("dialog", lambda dialog: dialog.accept())
        # await new_page.reload()
        context: ChromiumBrowserContext = new_page.context
        client = await context.new_cdp_session(new_page)
        res = await client.send("Page.handleJavaScriptDialog", params={"accept": True})
        await browser.close()

asyncio.run(main())
```
 
Here I'm getting: 
Exception has occurred: Error
Protocol error (Page.handleJavaScriptDialog): No dialog is showing

Help will be greatly appreciated!

**Comment by aslushnikov** [comment]
@ortamir in the current tip-of-tree, dialogs are automatically dismissed if there's no listener - see [tip-of-tree documentation on dialogs](https://playwright.dev/docs/next/dialogs#alert-confirm-prompt-dialogs).

So once the new version of playwright-for-python is released, this will be working for you out-of-the-box.

**Comment by ortamir** [comment]
Thanks @aslushnikov .
What is the planned time for v1.9.0 release?
Is there a stable commit that you recommend to work with meanwhile (the last commit wheel install seems to be broken)?

**Comment by aslushnikov** [comment]
@ortamir v1.9.0 is scheduled for the next week. 

> (the last commit wheel install seems to be broken)?

Hmm, interesting! What command do you run?

**Comment by ortamir** [comment]
Well I tried running:
pip install git+https://github.com/microsoft/playwright-python.git

Here is the output:


(venv) C:\Users\user\PycharmProjects\project1>pip install git+https://github.com/microsoft/playwright-python.git
Collecting git+https://github.com/microsoft/playwright-python.git
  Cloning https://github.com/microsoft/playwright-python.git to c:\users\user\appdata\local\temp\pip-req-build-_b_trav6
  Running command git clone -q https://github.com/microsoft/playwright-python.git 'C:\Users\user\AppData\Local\Temp\pip-req-build-_b_trav6'
Requirement already satisfied: greenlet==1.0.0 in c:\users\user\PycharmProjects\project1\venv\lib\site-packages (from playwright==0.152.0.post85+gc05ca
d2) (1.0.0)
Requirement already satisfied: pyee>=8.0.1 in c:\users\user\PycharmProjects\project1\venv\lib\site-packages (from playwright==0.152.0.post85+gc05cad2)
(8.1.0)
Requirement already satisfied: typing-extensions in c:\users\user\PycharmProjects\project1\venv\lib\site-packages (from playwright==0.152.0.post85+gc05
cad2) (3.7.4.3)
Building wheels for collected packages: playwright
  Building wheel for playwright (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\user\PycharmProjects\project1\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\lev
ia.tamir\\AppData\\Local\\Temp\\pip-req-build-_b_trav6\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-req-build-_b_trav6\\
setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__
, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\user\AppData\Local\Temp\pip-wheel-anznvwtp'
       cwd: C:\Users\user\AppData\Local\Temp\pip-req-build-_b_trav6\
  Complete output (197 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\playwright
  copying playwright\_repo_version.py -> build\lib\playwright
  copying playwright\__init__.py -> build\lib\playwright
  copying playwright\__main__.py -> build\lib\playwright
  running egg_info
  creating playwright.egg-info
  writing playwright.egg-info\PKG-INFO
  writing dependency_links to playwright.egg-info\dependency_links.txt
  writing entry points to playwright.egg-info\entry_points.txt
  writing requirements to playwright.egg-info\requires.txt
  writing top-level names to playwright.egg-info\top_level.txt
  writing manifest file 'playwright.egg-info\SOURCES.txt'
  writing manifest file 'playwright.egg-info\SOURCES.txt'
  copying playwright\py.typed -> build\lib\playwright
  creating build\lib\playwright\_impl
  copying playwright\_impl\_accessibility.py -> build\lib\playwright\_impl
  copying playwright\_impl\_api_structures.py -> build\lib\playwright\_impl
  copying playwright\_impl\_api_types.py -> build\lib\playwright\_impl
  copying playwright\_impl\_async_base.py -> build\lib\playwright\_impl
  copying playwright\_impl\_browser.py -> build\lib\playwright\_impl
  copying playwright\_impl\_browser_context.py -> build\lib\playwright\_impl
  copying playwright\_impl\_browser_type.py -> build\lib\playwright\_impl
  copying playwright\_impl\_cdp_session.py -> build\lib\playwright\_impl
  copying playwright\_impl\_chromium_browser_context.py -> build\lib\playwright\_impl
  copying playwright\_impl\_connection.py -> build\lib\playwright\_impl
  copying playwright\_impl\_console_message.py -> build\lib\playwright\_impl
  copying playwright\_impl\_dialog.py -> build\lib\playwright\_impl
  copying playwright\_impl\_download.py -> build\lib\playwright\_impl
  copying playwright\_impl\_driver.py -> build\lib\playwright\_impl
  copying playwright\_impl\_element_handle.py -> build\lib\playwright\_impl
  copying playwright\_impl\_event_context_manager.py -> build\lib\playwright\_impl
  copying playwright\_impl\_file_chooser.py -> build\lib\playwright\_impl
  copying playwright\_impl\_frame.py -> build\lib\playwright\_impl
  copying playwright\_impl\_helper.py -> build\lib\playwright\_impl
  copying playwright\_impl\_impl_to_api_mapping.py -> build\lib\playwright\_impl
  copying playwright\_impl\_input.py -> build\lib\playwright\_impl
  copying playwright\_impl\_js_handle.py -> build\lib\playwright\_impl
  copying playwright\_impl\_network.py -> build\lib\playwright\_impl
  copying playwright\_impl\_object_factory.py -> build\lib\playwright\_impl
  copying playwright\_impl\_page.py -> build\lib\playwright\_impl
  copying playwright\_impl\_path_utils.py -> build\lib\playwright\_impl
  copying playwright\_impl\_playwright.py -> build\lib\playwright\_impl
  copying playwright\_impl\_selectors.py -> build\lib\playwright\_impl
  copying playwright\_impl\_sync_base.py -> build\lib\playwright\_impl
  copying playwright\_impl\_transport.py -> build\lib\playwright\_impl
  copying playwright\_impl\_video.py -> build\lib\playwright\_impl
  copying playwright\_impl\_wait_helper.py -> build\lib\playwright\_impl
  creating build\lib\playwright\async_api
  copying playwright\async_api\__init__.py -> build\lib\playwright\async_api
  copying playwright\async_api\_context_manager.py -> build\lib\playwright\async_api
  copying playwright\async_api\_generated.py -> build\lib\playwright\async_api
  creating build\lib\playwright\sync_api
  copying playwright\sync_api\__init__.py -> build\lib\playwright\sync_api
  copying playwright\sync_api\_context_manager.py -> build\lib\playwright\sync_api
  copying playwright\sync_api\_generated.py -> build\lib\playwright\sync_api
  installing to build\bdist.win-amd64\wheel
  running install
  running install_lib
  creating build\bdist.win-amd64
  creating build\bdist.win-amd64\wheel
  creating build\bdist.win-amd64\wheel\playwright
  creating build\bdist.win-amd64\wheel\playwright\async_api
  copying build\lib\playwright\async_api\_context_manager.py -> build\bdist.win-amd64\wheel\.\playwright\async_api
  copying build\lib\playwright\async_api\_generated.py -> build\bdist.win-amd64\wheel\.\playwright\async_api
  copying build\lib\playwright\async_api\__init__.py -> build\bdist.win-amd64\wheel\.\playwright\async_api
  copying build\lib\playwright\py.typed -> build\bdist.win-amd64\wheel\.\playwright
  creating build\bdist.win-amd64\wheel\playwright\sync_api
  copying build\lib\playwright\sync_api\_context_manager.py -> build\bdist.win-amd64\wheel\.\playwright\sync_api
  copying build\lib\playwright\sync_api\_generated.py -> build\bdist.win-amd64\wheel\.\playwright\sync_api
  copying build\lib\playwright\sync_api\__init__.py -> build\bdist.win-amd64\wheel\.\playwright\sync_api
  creating build\bdist.win-amd64\wheel\playwright\_impl
  copying build\lib\playwright\_impl\_accessibility.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_api_structures.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_api_types.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_async_base.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_browser.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_browser_context.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_browser_type.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_cdp_session.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_chromium_browser_context.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_connection.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_console_message.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_dialog.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_download.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_driver.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_element_handle.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_event_context_manager.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_file_chooser.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_frame.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_helper.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_impl_to_api_mapping.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_input.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_js_handle.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_network.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_object_factory.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_page.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_path_utils.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_playwright.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_selectors.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_sync_base.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_transport.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_video.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_impl\_wait_helper.py -> build\bdist.win-amd64\wheel\.\playwright\_impl
  copying build\lib\playwright\_repo_version.py -> build\bdist.win-amd64\wheel\.\playwright
  copying build\lib\playwright\__init__.py -> build\bdist.win-amd64\wheel\.\playwright
  copying build\lib\playwright\__main__.py -> build\bdist.win-amd64\wheel\.\playwright
  running install_egg_info
  Copying playwright.egg-info to build\bdist.win-amd64\wheel\.\playwright-0.152.0.post85+gc05cad2-py3.9.egg-info
  running install_scripts
  adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
  creating build\bdist.win-amd64\wheel\playwright-0.152.0.post85+gc05cad2.dist-info\WHEEL
  creating 'C:\Users\user\AppData\Local\Temp\pip-wheel-anznvwtp\playwright-0.152.0.post85+gc05cad2-py3-none-any.whl' and adding 'build\bdist.win-amd
64\wheel' to it
  adding 'playwright/__init__.py'
  adding 'playwright/__main__.py'
  adding 'playwright/_repo_version.py'
  adding 'playwright/py.typed'
  adding 'playwright/_impl/_accessibility.py'
  adding 'playwright/_impl/_api_structures.py'
  adding 'playwright/_impl/_api_types.py'
  adding 'playwright/_impl/_async_base.py'
  adding 'playwright/_impl/_browser.py'
  adding 'playwright/_impl/_browser_context.py'
  adding 'playwright/_impl/_browser_type.py'
  adding 'playwright/_impl/_cdp_session.py'
  adding 'playwright/_impl/_chromium_browser_context.py'
  adding 'playwright/_impl/_connection.py'
  adding 'playwright/_impl/_console_message.py'
  adding 'playwright/_impl/_dialog.py'
  adding 'playwright/_impl/_download.py'
  adding 'playwright/_impl/_driver.py'
  adding 'playwright/_impl/_element_handle.py'
  adding 'playwright/_impl/_event_context_manager.py'
  adding 'playwright/_impl/_file_chooser.py'
  adding 'playwright/_impl/_frame.py'
  adding 'playwright/_impl/_helper.py'
  adding 'playwright/_impl/_impl_to_api_mapping.py'
  adding 'playwright/_impl/_input.py'
  adding 'playwright/_impl/_js_handle.py'
  adding 'playwright/_impl/_network.py'
  adding 'playwright/_impl/_object_factory.py'
  adding 'playwright/_impl/_page.py'
  adding 'playwright/_impl/_path_utils.py'
  adding 'playwright/_impl/_playwright.py'
  adding 'playwright/_impl/_selectors.py'
  adding 'playwright/_impl/_sync_base.py'
  adding 'playwright/_impl/_transport.py'
  adding 'playwright/_impl/_video.py'
  adding 'playwright/_impl/_wait_helper.py'
  adding 'playwright/async_api/__init__.py'
  adding 'playwright/async_api/_context_manager.py'
  adding 'playwright/async_api/_generated.py'
  adding 'playwright/sync_api/__init__.py'
  adding 'playwright/sync_api/_context_manager.py'
  adding 'playwright/sync_api/_generated.py'
  adding 'playwright-0.152.0.post85+gc05cad2.dist-info/LICENSE'
  adding 'playwright-0.152.0.post85+gc05cad2.dist-info/METADATA'
  adding 'playwright-0.152.0.post85+gc05cad2.dist-info/WHEEL'
  adding 'playwright-0.152.0.post85+gc05cad2.dist-info/entry_points.txt'
  adding 'playwright-0.152.0.post85+gc05cad2.dist-info/top_level.txt'
  adding 'playwright-0.152.0.post85+gc05cad2.dist-info/RECORD'
  removing build\bdist.win-amd64\wheel
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  100 16.2M  100 16.2M    0     0  2772k      0  0:00:06  0:00:06 --:--:-- 3612k
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  100 18.3M  100 18.3M    0     0  3134k      0  0:00:06  0:00:06 --:--:-- 3475k
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  100 11.7M  100 11.7M    0     0  3018k      0  0:00:04  0:00:04 --:--:-- 3544k
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  100 13.3M  100 13.3M    0     0  2731k      0  0:00:05  0:00:05 --:--:-- 3467k
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\user\AppData\Local\Temp\pip-req-build-_b_trav6\setup.py", line 108, in <module>
      setuptools.setup(
    File "c:\users\user\PycharmProjects\project1\venv\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\user\AppData\Local\Temp\pip-req-build-_b_trav6\setup.py", line 66, in run
      base_wheel_location = glob.glob("dist/*.whl")[0]
  IndexError: list index out of range
  Fetching  https://playwright.azureedge.net/builds/driver/next/playwright-1.9.0-next-1613683796000-mac.zip
  Fetching  https://playwright.azureedge.net/builds/driver/next/playwright-1.9.0-next-1613683796000-linux.zip
  Fetching  https://playwright.azureedge.net/builds/driver/next/playwright-1.9.0-next-1613683796000-win32.zip
  Fetching  https://playwright.azureedge.net/builds/driver/next/playwright-1.9.0-next-1613683796000-win32_x64.zip
  ----------------------------------------
  ERROR: Failed building wheel for playwright
  Running setup.py clean for playwright
Failed to build playwright
Installing collected packages: playwright
    Running setup.py install for playwright ... done
  DEPRECATION: playwright was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. A possible replacement is to
 fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Successfully installed playwright-0.152.0.post85+gc05cad2

**Comment by pavelfeldman** [comment]
We don't support installation off git atm. See https://playwright.dev/python/docs/intro/#installation
