### ISSUE TITLE
[Question] installed versions don't correlate with the release notes

### ISSUE THREAD

**Issue by onno-amsterdam** [microsoft/playwright#5490]
Dear Playwright, I'm a little bit confused about the browser versions and the link to the Playwright versions. With any version I install I get different versions of browser than what I can see in the release notes. I hope you can help me with that. 

When I install Playwright version 1.7.1 I see in the npm install logs: 
```bash
> playwright@1.7.1 install C:\Repositories\PRIVA\My Priva\Application\e2e\Playwright\node_modules\@playwright\test\node_modules\playwright
> node install.js

Downloading chromium v833159 - 90.1 Mb [====================] 100% 0.0s
chromium v833159 downloaded to C:\Users\ovanpiggelen\AppData\Local\ms-playwright\chromium-833159
Downloading firefox v1221 - 75.4 Mb [====================] 100% 0.0s
firefox v1221 downloaded to C:\Users\ovanpiggelen\AppData\Local\ms-playwright\firefox-1221
Downloading webkit v1402 - 38.6 Mb [====================] 100% 0.0s
webkit v1402 downloaded to C:\Users\ovanpiggelen\AppData\Local\ms-playwright\webkit-1402

> playwright-core@1.7.1 install C:\Repositories\PRIVA\My Priva\Application\e2e\Playwright\node_modules\playwright-core
> node install.js


> playwright@1.7.1 install C:\Repositories\PRIVA\My Priva\Application\e2e\Playwright\node_modules\playwright
> node install.js
````

However in the release notes for 1.7.1 I see the versions: 
```
Chromium 89.0.4344.0
Mozilla Firefox 84.0b9
WebKit 14.1
```
https://github.com/microsoft/playwright/releases

I would expect these versions from the release notes to be installed with 1.7.1 or **am I missing something?**

=============================================================

I came to check the versions because I have a curious issue with a test running in Webkit. With version 1.6.2 this was not yet an issue, now I'm using 1.8.0 (latest) and I have a test failing in Webkit.

It's very hard to make a reproducible bug I can share with you but I'll try to explain: 
```
I have an Angular application deploy on an Azure environment. When I run my test against it from my local machine, all works fine. However when I run the same test in an Azure pipeline the test fails at this point: 

A button is clicked which should open a dialog. This dialog is not opened.

This issue in the pipeline only occurs in Webkit in a version higher then 1.6.2. Also it works fine with Chrome and Firefox
```

Any ideas what I can try?

**Comment by mxschmitt** [comment]
These numbers which you can see in the console during the installing phase as version numbers are an internal representation of the browsers. Behind them are the correct versions which are also in the release notes.

Regarding your bug, it would be great if you could try the latest version (1.9.0) and try to make it reproducible, so it can be shared on the GitHub issue. Everything else is unfortunately only guessing.

**Comment by aslushnikov** [comment]
Yeah, I don't think this is much actionable without a repro. I'll close this right now - please feel free to re-submit when you have a good repro!
