### ISSUE TITLE
[BUG] Can't run Playwright in Nix

### ISSUE THREAD

**Issue by VaasRamsay** [microsoft/playwright#5501]
**Context:**
- Playwright Version: 1.8.0
- Operating System: Linux
- Node.js version: 12
- Browser: All

**Describe the bug**

Running Playwright in Nix Shell throws `missing dependencies` error. Even after explicitly adding the missing dependencies suggested by "launch doctor", the same error is thrown. 

```
Error: browserType.launch: Host system is missing dependencies!
--
  | Missing libraries we didn't find packages for:
  | libexpat.so.1
  | libxshmfence.so.1
```

Probably, I'm hitting this error from [here](https://github.com/microsoft/playwright/blob/a9faa9c941fa0b0383d68dff2fb7ef825bd258ea/src/server/validateDependencies.ts#L250). Nix has it's own `ldconfig` and it's not found in `sbin`.

**Comment by aslushnikov** [comment]
@SamBreaksThings we don't support Nix at the moment and this is the first request we've received regarding it so far. 

So until there's a huge demand for Nix support, this will be low-pri for us. Is there something easy we can do to enable you use Playwright on Nix?

**Comment by uri-canva** [comment]
Is it possible to make the linked workaround configurable: https://github.com/microsoft/playwright/blob/a9faa9c941fa0b0383d68dff2fb7ef825bd258ea/src/server/validateDependencies.ts#L247-L250?

Note the commit message of https://github.com/aslushnikov/playwright/commit/aa3019bc8225abd463602481e3362fc61ea33b40

> To the best of my knowledge, `ldconfig` is always located at `/sbin`.

This is one case where it's not located there, and loading it from there leads to broken behaviour.

**Comment by joscha** [comment]
> Is it possible to make the linked workaround configurable:

maybe via an env var `await spawnAsync(process.env.LDCONFIG_PATH || '/sbin/ldconfig', ['-p'], {});`

? Or if that is an unwanted API it would also be thinkable to make it a fallback from the generic `ldconfig` (w/o qualified path, e.g. `command -v ldconfig` or `which ldconfig`) and if that one is not found to fall back to `/sbin/ldconfig`. Or if we want to make the speed sacrifice for more exotic users of this package if could be in the catch block of the `/sbin/ldconfig` spawn and introspect the error and retry with `ldconfig` from path?

**Comment by uri-canva** [comment]
Alternatively an option to entirely disable validating dependencies would work even better: I'm noticing `ldconfig` is only used to provide an error message suggesting how to install missing dependencies.

**Comment by aslushnikov** [comment]
@uri-canva @joscha Is this the only thing that breaks Playwright on Nix? In this case, would symlinking ldconfig to `/sbin/ldconfig` solve it on your end?

**Comment by joscha** [comment]
A system can have multiple nix profiles. Which one is used is dependent on the environment started. These virtualizations only affect the `PATH` (and a few other things like env) but not the file system, so changing a symlink is not really idiomatic as you would suddenly bind the static filesystem to a specific, arbitrary nix profile.

**Comment by aslushnikov** [comment]
@joscha if this is the only thing that doesn't work on Nix - then sure, we can come up with something as long as it's non-intrusive for the codebase & API. 

But is this the only thing that prevents you from running on NIX? For example, I'll be surprised if our browser builds launch on NIX. Have you tried running them?

**Comment by uri-canva** [comment]
The browsers require a wrapper around them to launch on nix: https://github.com/ludios/nixos-playwright

**Comment by aslushnikov** [comment]
> The browsers require a wrapper around them to launch on nix: https://github.com/ludios/nixos-playwright

@uri-canva impressive!

So to double-check: the `ldconfig` is the last thing that stops you folks from using playwright on nix?

Would you be open to send a PR that detects *NIX system and disables launch doctor there? I cannot guarantee we land it, but we'll discuss it. I'd appreciate if it's as non-invasive as possible.

**Comment by uri-canva** [comment]
We can make it agnostic to nix: look if `ldconfig` is on `PATH`, if not try `/sbin/ldconfig`, if that doesn't exist either fail?

**Comment by olebedev** [comment]
I have made a PR that allows disabling host requirements validation, please have a look https://github.com/microsoft/playwright/pull/5806.

**Comment by mxschmitt** [comment]
Since the PR for skipping the host validation got merged and there won't be official supported added we will close it for now, feel free to reopen / upvote it when there is a higher demand.

**Comment by aabccd021** [comment]
[Playwright package](https://github.com/NixOS/nixpkgs/blob/6428fc1a54986d2da12c669877497159df3085dd/pkgs/development/python-modules/playwright/default.nix) is now available in unstable channel.
I got it working with nix flake by using following `flake.nix` and then running `nix develop`
```nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
  };
 
  outputs = { self, nixpkgs }: with nixpkgs.legacyPackages.x86_64-linux; {
    devShell.x86_64-linux = mkShell {
      buildInputs = [
        playwright
        playwright.browsers
      ];
      shellHook = ''
        export PLAYWRIGHT_BROWSERS_PATH=${playwright.browsers}
        export PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS=true
      '';
    };
  };
}
```
<details>
  <summary>`flake.lock`</summary>

```json
{
  "nodes": {
    "nixpkgs": {
      "locked": {
        "lastModified": 1666926733,
        "narHash": "sha256-+gYfOEnQVISPDRNoWm2VJD5OEuTUySt48RchLpvm61o=",
        "owner": "nixos",
        "repo": "nixpkgs",
        "rev": "f44ba1be526c8da9e79a5759feca2365204003f6",
        "type": "github"
      },
      "original": {
        "owner": "nixos",
        "ref": "nixpkgs-unstable",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
    "root": {
      "inputs": {
        "nixpkgs": "nixpkgs"
      }
    }
  },
  "root": "root",
  "version": 7
}
```

</details>

**Comment by FossPrime** [comment]
> ```nix
> playwright.browsers
> ```

I have 22.11 with playwright installed through config... that may work for python, but packages that depend on playwright like Node Slidev still don't work and you'll get the dreaded message:

```
Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libgobject-2.0.so.0                              ║
║     libglib-2.0.so.0                                 ║
║     libnss3.so                                       ║
║     libnssutil3.so                                   ║
║     libsmime3.so                                     ║
║     libnspr4.so                                      ║
║     libatk-1.0.so.0                                  ║
║     libatk-bridge-2.0.so.0                           ║
║     libcups.so.2                                     ║
║     libgio-2.0.so.0                                  ║
║     libdrm.so.2                                      ║
║     libdbus-1.so.3                                   ║
║     libatspi.so.0                                    ║
║     libX11.so.6                                      ║
║     libXcomposite.so.1                               ║
║     libXdamage.so.1                                  ║
║     libXext.so.6                                     ║
║     libXfixes.so.3                                   ║
║     libXrandr.so.2                                   ║
║     libgbm.so.1                                      ║
║     libexpat.so.1                                    ║
║     libxcb.so.1                                      ║
║     libxkbcommon.so.0                                ║
║     libpango-1.0.so.0                                ║
║     libcairo.so.2                                    ║
║     libasound.so.2
```

**Comment by adam248** [comment]
I get the same error message...

**Comment by adam248** [comment]
Calling the heroes in:
@techknowlogick
@yrd
@SuperSandro2000

**Comment by yrd** [comment]
> `playwright install` does download the 3 different browser drivers, with a warning `BEWARE: your OS is not officially supported by Playwright; downloading fallback build.`

The Playwright package splits the browser bundle depending on the platform. For Linux, `playwright.browsers` is a derivation that emulates what you get when running `playwright install`, but with the Nixpkgs version of each browser. As @aabccd021 mentioned, you will need to set `PLAYWRIGHT_BROWSERS_PATH` to this derivation, instead of having Playwright download the precompiled browsers. Try something like this:

```shell
export PLAYWRIGHT_BROWSERS_PATH=$(nix build --print-out-paths nixpkgs#playwright.browsers)
nix shell nixpkgs#playwright
playwright open nixos.org
```

(Add `--no-out-link` to the `nix build` step if you don't wan't the `result` symlink to the browsers derivation). I just tested this using NixOS/nixpkgs@5a350a8f31bb7ef0c6e79aea3795a890cf7743d4 and it seems to work:

![grafik](https://user-images.githubusercontent.com/1820447/217739845-cd6de23f-69f7-498c-98ff-56db19a368f4.png)

If you're on Darwin, `playwright.browsers` will be the same bundle you get when running `playwright install` (the pre-built binaries by the Playwright team, including their patches), just as an FOD so we get the reproducibility. On Mac, using Playwright's install script as @adam248 described should work as well, but `playwright.browsers` in combination with the environment variable will keep everything in the Nix store.

**Comment by yrd** [comment]
One more note when using our browser bundle on Linux instead of the Playwright-provided one: this does mean that you won't be getting any Playwright-specific [browser patches](https://github.com/microsoft/playwright/tree/main/browser_patches). Maybe someone from the Playwright team could weigh in on the implications here?

**Comment by SuperSandro2000** [comment]
Applying a 3000 or 23000 line patch is guaranteed to break at some point. Unless those patches get split up into smaller ones, we cannot maintainable apply them to a source build unless we fetch the same exact version.

**Comment by yrd** [comment]
I just don't know if there are any Playwright Features we're currently missing out on by using the regular browser builds… But I do agree with @SuperSandro2000 that it's infeasible for us to include all patches. Maybe there are some parts which could be interesting to cherry-pick, but I'm not versed enough in Playwright's internals to say anything about that.

**Comment by pbek** [comment]
Currently, this `shell.nix` is working for me:

```nix
{ pkgs ? import <nixpkgs> {} }:
  pkgs.mkShell {
    # nativeBuildInputs is usually what you want -- tools you need to run
    nativeBuildInputs = with pkgs; [
      playwright-driver.browsers
    ];

    shellHook = ''
      export PLAYWRIGHT_BROWSERS_PATH=${pkgs.playwright-driver.browsers}
      export PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS=true
    '';
}
```

**Comment by ManUtopiK** [comment]
@pbek It works also for me with node package `@playwright/test` version 1.40.1 with the same shell.nix.
I updated to 1.41.1 and now I can't launch playwright : Error No chromium-based browser found on the system. 
I've downgraded for now...

**Comment by pbek** [comment]
I already added the version matching in the nix wiki last week, because I had a similar issue. 😅

**Comment by ml21** [comment]
> I already added the version matching in the nix wiki last week, because I had a similar issue. 😅

I tried to find it in wike https://nixos.wiki/wiki/Playwright , but no version matching there.

And one more question please - in wiki:
```
Note: Keep in mind that you need to use the same version of playwright in your node playwright project as in your nixpkgs, or else playwright will try to use browsers versions that aren't installed!
```
How can I specify playwright\playwright-driver.browsers version in my flake.nix? 
Here is my test flake with dev env
```
{
  description = "dev env";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
  };

  outputs = { self, nixpkgs }: let
    system = "x86_64-linux";
    pkgs = import nixpkgs { inherit system; };
  in {
      devShells.${system}.default = pkgs.mkShell {
      packages = with pkgs; [
        nodejs
        dotnet-sdk_8
        process-compose
        playwright
      ];

      PLAYWRIGHT_NODEJS_PATH = "${pkgs.nodejs}/bin/node";
      # PLAYWRIGHT_LAUNCH_OPTIONS_EXECUTABLE_PATH = "${pkgs.playwright-driver.browsers}/chromium-1091/chrome-linux/chrome";
      PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS = true;
      PLAYWRIGHT_BROWSERS_PATH="${pkgs.playwright-driver.browsers}";

      shellHook = ''
        echo "dev env started"
        fish && echo "exit dev env" && exit
      '';
    };
  };
}
```

**Comment by pbek** [comment]
> Note: Keep in mind that you need to use the same version of playwright in your node playwright project as in your nixpkgs, or else playwright will try to use browsers versions that aren't installed!

I was talking about that note. 😉 

I was looking at https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=playwright-driver, noting the version.
Then updating my flake.
Then installing exact that version with npm too.

**Comment by ml21** [comment]
> Then installing exact that version with npm too.

What if I can't change the version in the project (dotnet in my case, not node)?

In this case, I need to find and specify a suitable version of playwright from nixpkgs.

How could I do that?

**Comment by pbek** [comment]
> https://www.nixhub.io/packages/playwright

Oh, that's nice. I didn't know that service! And I didn't know "devbox". Did you try it, @ml21? Does it create a flake for your project to pin the version? Because that's what I would have done. Pin the nix version of playwright (by searching the github nixpkgs repository for the commit hash of exactly the version that I need) with a nix flake.

**Comment by ml21** [comment]
> Did you try it, @ml21?

@pbek I haven’t tried Sugar yet because I want to use as few additional utilities as possible. I simply specify the version (found on nixhub) of the nixpkgs that has the version of playwright I need.

For example, I need playwright v1.34:

```
{
  description = "dev env";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
    nixpkgs-pw-v1_34.url = "github:NixOS/nixpkgs/dfcffbd74fd6f0419370d8240e445252a39f4d10";
  };

  outputs = { self, nixpkgs, nixpkgs-pw-v1_34 }: let
    system = "x86_64-linux";
    pkgs = import nixpkgs { inherit system; };
    pkgs-pw-v1_34 = import nixpkgs-pw-v1_34 { inherit system; };
  in {
      devShells.${system}.default = pkgs.mkShell {
      packages = [
        pkgs.nodejs_18
        pkgs.dotnet-sdk_8
        pkgs.process-compose
        pkgs-pw-v1_34.playwright
      ];

      PLAYWRIGHT_NODEJS_PATH = "${pkgs.nodejs}/bin/node";
      PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS = true;
      PLAYWRIGHT_BROWSERS_PATH="${pkgs-pw-v1_34.playwright-driver.browsers}";

      shellHook = ''
        echo "dev env started"
        fish && echo "exit dev env" && exit
      '';
    };
  };
}
```

**Comment by pbek** [comment]
@ml2, yes that's what I would have been done too.
Meanwhile, I tried devbox, works great too to pin the version.

**Comment by rjpcasalino** [comment]
@tobiasBora you just blew my mind

**Comment by cristianoliveira** [comment]
For those that ended up here after fighting with this issue, and is running under wayland. Running headless browser under wayland is it's own beast and it was experimental not so long ago and required setting some environment variables, so make sure to upgrade NixOs to the latest version before debugging :) 

Also make sure to use the same `@playwright/test` version to the `playwright-driver.browsers` which for version 24.11 is 1.47.0

**Comment by tobiasBora** [comment]
Note that if you use `nix-ld`, you just need to additionally run:
```
export LD_LIBRARY_PATH=$NIX_LD_LIBRARY_PATH
```
since I guess the library uses a custom loader not in `/lib` (the one patched by nix-ld).
