### ISSUE TITLE
Unsecure cookies are not returned from `BrowserContext.cookies(...)` for HTTPS urls

### ISSUE THREAD

**Issue by zevisert** [microsoft/playwright#5504]
Reading [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies), it sounds like browsers send cookies according to the following table

| Secure attribute value | Request URL scheme | Allow cookie to be sent |
| -- | -- | -- |
| true                     | HTTPS              | Yes |
| true                     | HTTP                | No |
| false (or unset)    | HTTPS              | Yes |
| false (or unset)    | HTTP                | Yes |

It seems that the logic for retrieving cookies in playwright trys to mirror this behaviour. It's the third row in that table I'm interested in.

If a `BrowserContext` has a cookie that has `{ secure: false }`, then this line prevents returning the cookie for urls that use `HTTPS`: 

https://github.com/microsoft/playwright/blob/970e230fcba1c62aad9ffb8ddb858e18caa478a0/src/server/network.ts#L36

If this is not intended behaviour, I'd be happy to make a PR, since the change (barring any testing) to align with the table above amounts to:

```diff
- if ((parsedURL.protocol === 'https:') !== c.secure)
+ if ((parsedURL.protocol === 'https:') || !c.secure)
```

**Comment by aslushnikov** [comment]
@zevisert This looks like a bug to me. We'd be happy to review a PR, and we'd also appreciate a test to validate the behavior in the [`//tests/browsercontext-cookies.spec.ts`](https://github.com/microsoft/playwright/blob/master/test/browsercontext-cookies.spec.ts).
