### ISSUE TITLE
[Question]In the docker container use playwright

### ISSUE THREAD

**Issue by SansLang** [microsoft/playwright#5508]
In the docker container, I executed python -m playwright install chromium, and then I exported the container and imported it for use elsewhere. The browser installed before exists in the root's .cache folder, but the execution of the test case prompts that the browser cannot be found , Do I have to re-execute python -m playwright install every time I import the container?

**Comment by mxschmitt** [comment]
If the Docker image version matches with the Playwright for Python version, then the browsers should be installed and you don't have to re-execute the install command. 

For example: `git pull mcr.microsoft.com/playwright:v1.8.0-focal` matches 1.8.0: https://github.com/microsoft/playwright-python/releases/tag/v1.8.0a1

**Comment by SansLang** [comment]
The docker image is built by myself based on centos8

**Comment by SansLang** [comment]
But there is a strange phenomenon. I have no problem importing docker image on one machine, but there is a problem on the other machine.

**Comment by aslushnikov** [comment]
@SansLang you might have an old docker image cached on one of the machines that's old.

**Comment by SansLang** [comment]
> @SansLang，您可能在一个旧机器上缓存了一个旧的docker映像。可能是这样吗？

It may be like this, now I re-imported the docker image on that machine and it runs normally
