### ISSUE TITLE
[BUG] Download does not work with Chromium in a headless mode

### ISSUE THREAD

**Issue by jevgenijusmarinuskinas** [microsoft/playwright#5509]
**Context:**
System:
    OS: Windows 10 10.0.19042
    Memory: 18.10 GB / 31.61 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD    
  Languages:
    Bash: 4.4.20 - C:\WINDOWS\system32\bash.EXE     
  npmPackages:
    playwright: ^1.8.0 => 1.8.0 

```
async downloadFile(filePath, isAbsolutePath) {
        if (!isAbsolutePath) filePath = process.cwd() + filePath;
        await this.click();
        const download = await page.waitForEvent("download");
        await download.saveAs(filePath);
    }
```

When running tests with Chromium in a headless mode, unable to download a file, getting the **net::ERR_ABORTED** error. In usual mode and Firefox is it working fine.

**Comment by pavelfeldman** [comment]
Your code does not seem to be right, please refer to https://playwright.dev/docs/downloads for the code snippet that handles downloads.

**Comment by jevgenijusmarinuskinas** [comment]
Do you mean it won't work without promise? As I've mentioned, it works with Firefox and non-headless Chrome.

As I am using await on click event and then await or download event, it seems to be fine.

**Comment by aslushnikov** [comment]
@jevgenijusmarinuskinas  in your code snippet, there's a race condition between you clicking the button and awaiting the download. A safe way to avoid it would be to use `Promise.all` combinator:

```js
const [download] = await Promise.all([
  page.waitForEvent("download"),
  this.click(),
]);
await download.saveAs(filePath);
```

> When running tests with Chromium in a headless mode, unable to download a file, getting the net::ERR_ABORTED error. In usual mode and Firefox is it working fine.

As for the `net::ERR_ABORTED`, it looks like website decided not to serve download. This might happen due to server-side headless agent detection; we'd recommend disable them on your test deployment.

**Comment by jevgenijusmarinuskinas** [comment]
Okay, thank you. Will try. About the headless: I was able to reproduce the
problem locally (just opening the plain html with file:///) and with
website running on the server.

**Comment by aslushnikov** [comment]
>  I was able to reproduce the
problem locally (just opening the plain html with file:///)

In this case, did the click trigger a download from a remote server or a file:// url as well?

**Comment by jevgenijusmarinuskinas** [comment]
No, just a local file.

**Comment by aslushnikov** [comment]
@jevgenijusmarinuskinas Interesting! Could you please share the script and the local HTML with us so that we can reproduce it locally and see what's going on?

**Comment by jevgenijusmarinuskinas** [comment]
Hello,

Please find the local html and example file attached. You would need to
just click the download element and wait for an event, in a usual way.

Kind regards
Jevgenijus


2021-02-19, pn, 19:57 Andrey Lushnikov <notifications@github.com> rašė:

**Comment by jevgenijusmarinuskinas** [comment]
You were right indeed. When incorporating into a Promise, chrome has also
started working.

Thank you!

Kind regards
Jevgenijus

2021-02-22, pr, 08:41 Jevgenijus Marinuškinas <
jevgenijus.marinuskinas@gmail.com> rašė:

**Comment by jevgenijusmarinuskinas** [comment]
> @jevgenijusmarinuskinas in your code snippet, there's a race condition between you clicking the button and awaiting the download. A safe way to avoid it would be to use `Promise.all` combinator:
> 
> ```js
> const [download] = await Promise.all([
>   page.waitForEvent("download"),
>   this.click(),
> ]);
> await download.saveAs(filePath);
> ```
> 
> > When running tests with Chromium in a headless mode, unable to download a file, getting the net::ERR_ABORTED error. In usual mode and Firefox is it working fine.
> 
> As for the `net::ERR_ABORTED`, it looks like website decided not to serve download. This might happen due to server-side headless agent detection; we'd recommend disable them on your test deployment.

Hello,
Seems like the suggested Promise solution is working indeed in a headless mode. Thank you, closing the issue.
