### ISSUE TITLE
[BUG] Using non installed version of the browser

### ISSUE THREAD

**Issue by madsbuch** [microsoft/playwright#5545]
**Context:**
- Playwright Version: 1.8.1@npm
- Operating System: Pop!_OS 20.10 (Linux)
- Node.js version: v14.2.0
- Browser: Chrome
- Extra: yarn 1.22.10

**Code Snippet**

When running my program I get following error:

```
(node:183709) UnhandledPromiseRejectionWarning: browserType.launch: Failed to launch chromium because executable doesn't exist at /home/[user]/.cache/ms-playwright/chromium-844399/chrome-linux/chrome
Try re-installing playwright with "npm install playwright"
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.:
... [Stack Trace]
```

Upon investigation, the requested version of chrome does not exist, but another version does:

```
~ ❯❯❯ /home/[user]/.cache/ms-playwright/chromium-844399/chrome-linux/chrome  
zsh: no such file or directory: /home/mads/.cache/ms-playwright/chromium-844399/chrome-linux/chrome
~ ❯❯❯ /home/[user]/.cache/ms-playwright/chromium-823944/chrome-linux/chrome
[output]
```

Ie. `chromium-844399` does _not_ exist, but `chromium-823944` does.

**Describe the bug**

It appears that playwright does not install newer versions of browsers. This bug reoccurs basically everytime I get back to the project I am working on. My impression is that it reoccurs everytime a new version of chrome is out.

The only work around I have is a force install, `yarn install --force`. But that is tedious.

Btw, thanks for a great piece of software! Really appreciate the effort on this one!

**Comment by aslushnikov** [comment]
@madsbuch first of all, **disclaimer**: I'm not familiar with Pop!_Os in any way, and playwright doesn't support it officially.

Is there a docker image I can use to try to reproduce this? 

Additionally, does it happen for you with a traditional OS, e.g. ubuntu?

**Comment by pavelfeldman** [comment]
This is out of scope for Playwright atm
