### ISSUE TITLE
[Question] Is there a way to capture console error logs ?

### ISSUE THREAD

**Issue by vincent-prz** [microsoft/playwright#5546]
I tried to use this setting : https://playwright.dev/docs/api/class-logger?_highlight=log#loggerisenabledname-severity

But it didn't succeed. 

Note: we're using QAWolf 1.3.3, with Playwright 1.8.0

**Comment by mxschmitt** [comment]
You can do something like that to listen to `console.error` events: https://playwright.dev/docs/api/class-page/#pageonconsole

```js
// @ts-check
const playwright = require("playwright");

(async () => {
  const browser = await playwright.chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  const errorLogs = []
  page.on("console", (message) => {
    if (message.type() === "error") {
      errorLogs.push(message.text())
    }
  })
  await page.evaluate(() => {
    console.error("hello from the browser")
  })
  console.log(errorLogs)
  await browser.close();
})();
```

There is also the [`pageError`](https://playwright.dev/docs/api/class-page#pageonpageerror) event which can be used to catch unhandled exceptions which get thrown inside the browser:

```js
 page.on("pageerror", (err) => {
    console.log(err.message)
  })
```

Does this fit for your needs?

**Comment by vincent-prz** [comment]
The `pageerror` handler fits our needs perfectly! Thanks @mxschmitt !
