### ISSUE TITLE
[Feature] Allow Context to use proxies optionally without global browser option set.

### ISSUE THREAD

**Issue by zMrKrabz** [microsoft/playwright#5558]
It is possible to create a new context and override the current proxy, however, if you wanted some contexts to use proxies while others do not, you would have to create 2 browsers: one without a proxy set (to allow non proxy requests) and one with proxy set. Currently running on firefox.

**Comment by aslushnikov** [comment]
@zMrKrabz Changing this is a non-trivial engineering investment. So yess, creating 2 browsers is the way to go here. That'll be a one-process overhead for the system which is not that big of a deal.
