### ISSUE TITLE
[BUG] README links to bad system requirements URL

### ISSUE THREAD

**Issue by stuartlangridge** [microsoft/playwright#5568]
The README file in this repo links to https://playwright.dev/#?path=docs/intro.md&q=system-requirements for system requirements, which is a strange looking link which seems to have a query string in its fragment identifier, and doesn't work besides. I'm not sure what the link is supposed to be (which is why this isn't a PR); perhaps https://playwright.dev/docs/intro#system-requirements which is a much more sensible-looking link. (Maybe the website used to be some sort of client-side SPA and is now linkable HTML?)

**Comment by mxschmitt** [comment]
Thanks for reporting, these were from the old documentation. It seems the redirects which were there before don't work anymore, fixed the broken links right away, so it does not rely on these redirects in the future.
