### ISSUE TITLE
[Question]traceview ui

### ISSUE THREAD

**Issue by chenshuichao** [microsoft/playwright#5579]
when I can use traceview ui,since we know it in github some days.

**Comment by aslushnikov** [comment]
@chenshuichao I'm not sure I follow the question. Could you please elaborate?

**Comment by chenshuichao** [comment]
Thank you!
I means trace feature by enable trace view

**Comment by aslushnikov** [comment]
Ah! It's coming! No ETA though :) Keep tight!
