### ISSUE TITLE
[REGRESSION][1.9.0]: Cannot find module 'electron' or its corresponding type declarations

### ISSUE THREAD

**Issue by AviVahl** [microsoft/playwright#5585]
**Context:**
- GOOD Playwright Version: 1.8.0
- BAD Playwright Version: 1.9.0
- Operating System: Linux. Fedora 33.
- Extra: using `playwright-core`. `skipLibCheck` is *not* turned on.

**Code Snippet**

```javascript
const {chromium, webkit, firefox} = require('playwright-core');

(async () => {
  const browser = await chromium.launch();
  // ... 
})();
```

**Describe the bug**

After upgrading to the new version, I see the following type errors when using playwright-core programmatically:
```ts
node_modules/playwright-core/types/types.d.ts:7098:63 - error TS2307: Cannot find module 'electron' or its corresponding type declarations.
7098   evaluate<R, Arg>(pageFunction: PageFunctionOn<typeof import('electron'), Arg, R>, arg: Arg): Promise<R>;
                                                                   ~~~~~~~~~~

node_modules/playwright-core/types/types.d.ts:7099:58 - error TS2307: Cannot find module 'electron' or its corresponding type declarations.
7099   evaluate<R>(pageFunction: PageFunctionOn<typeof import('electron'), void, R>, arg?: any): Promise<R>;
                                                              ~~~~~~~~~~

node_modules/playwright-core/types/types.d.ts:7120:69 - error TS2307: Cannot find module 'electron' or its corresponding type declarations.
7120   evaluateHandle<R, Arg>(pageFunction: PageFunctionOn<typeof import('electron'), Arg, R>, arg: Arg): Promise<SmartHandle<R>>;
                                                                         ~~~~~~~~~~

node_modules/playwright-core/types/types.d.ts:7121:64 - error TS2307: Cannot find module 'electron' or its corresponding type declarations.
7121   evaluateHandle<R>(pageFunction: PageFunctionOn<typeof import('electron'), void, R>, arg?: any): Promise<SmartHandle<R>>;
                                                                    ~~~~~~~~~~

Found 4 errors.
```

**Comment by mxschmitt** [comment]
Sems like already fixed in #5572 and cherry-picked in #5576. Should get released as 1.9.1 shortly.

**Comment by aslushnikov** [comment]
The fix was merged in v1.9.1 and 1.9.1 is live!

**Comment by mxschmitt** [comment]
Can verify it works!

**Comment by joelgriffith** [comment]
Thanks @aslushnikov!

**Comment by aarvay** [comment]
Breaks in 1.10.0

**Comment by AviVahl** [comment]
> Breaks in 1.10.0
odd. we're using 1.10.0 and no issue. re-verify the local version.

**Comment by aarvay** [comment]
Re-verified local version. 1.10.0. 

```
node_modules/playwright-core/lib/server/electron/electron.js:129:66: error: Could not resolve "electron/index.js" (mark it as external to exclude it from the bundle)
    129 │ ...utablePath: options.executablePath || require('electron/index.js'),
```

**Comment by aarvay** [comment]
Last working version for me was 1.8.0. Even 1.9.1 doesn't work. I get the same error.

**Comment by AviVahl** [comment]
that doesn't look like a type error. which tool/lib is giving you this error?

**Comment by aarvay** [comment]
esbuild

**Comment by AviVahl** [comment]
ah, might want to open a separate issue and give exact steps to reproduce, expected behavior, etc...

**Comment by aarvay** [comment]
@AviVahl will do that! thanks.

**Comment by mikejackowski** [comment]
Still happening ot me, playwright-core 1.20, building using `tsc` 

`Could not resolve "electron/index.js" (mark it as external to exclude it from the bundle)`

**Comment by AviVahl** [comment]
@mikejackowski 
That's not an error from tsc. It's an error from some bundler (I'm guessing esbuild, but you'd be the one to say).
You probably need to avoid trying to bundle playwright, or any test file that imports it.
