### ISSUE TITLE
ARIA or Semantic query engine?

### ISSUE THREAD

**Issue by benjamind** [microsoft/playwright#559]
While I will love to see the ShadowDOM support mentioned in #152 I would also like to promote the idea of adding an 'ARIA' or 'Semantic' query engine early on.

The idea here would be something similar to the queries provided by `testing-library` with its [byRole](https://testing-library.com/docs/dom-testing-library/api-queries#byrole) or [byLabelText](https://testing-library.com/docs/dom-testing-library/api-queries#bylabeltext) queries.

A syntax like `aria=role['textbox'] >> semantic=placeholder['Username']` would be especially powerful for testing without dependencies on specific HTML structure.

This would of course have to have ShadowDOM support to work correctly at this time I think.

**Comment by pavelfeldman** [comment]
Closing in favor of the metabug: https://github.com/microsoft/playwright/issues/686
