### ISSUE TITLE
BUG: Cannot find chrome executable in official docker image

### ISSUE THREAD

**Issue by haikyuu** [microsoft/playwright#5590]
**Context:**
- Playwright Version: 1.8.0
- Operating System: Docker playwright bionic image
- Extra: I'm running in Google Cloud CI

```
Step #0: Status: Downloaded newer image for mcr.microsoft.com/playwright:bionic
Step #0: mcr.microsoft.com/playwright:bionic
Step #0: 
Step #0: > playwright@1.8.0 install /workspace/node_modules/@playwright/test/node_modules/playwright
Step #0: > node install.js
Step #0: 
Step #0: Removing unused browser at /ms-playwright/chromium-854489
Step #0: Removing unused browser at /ms-playwright/firefox-1234
Step #0: Removing unused browser at /ms-playwright/webkit-1438
Step #0: 
Step #0: chromium v844399 downloaded to /ms-playwright/chromium-844399
Step #0: 
Step #0: firefox v1225 downloaded to /ms-playwright/firefox-1225
Step #0: 
Step #0: webkit v1423 downloaded to /ms-playwright/webkit-1423
Step #0: 

...

Step #5:     browserType.launch: Failed to launch chromium because executable doesn't exist at /ms-playwright/chromium-844399/chrome-linux/chrome
Step #5:     Try re-installing playwright with "npm install playwright"
Step #5:     Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
Step #5: 
```

**Comment by haikyuu** [comment]
Note that it works fine in my local Mac machine and that it used to work previously in this same environment in CI

**Comment by mxschmitt** [comment]
The issue is probably that on Google Cloud CI the image is not cached and on your local MacBook it's cached. By that it uses the `latest` tag which was updated yesterday to Playwright v1.9.0.

Pinning the Docker image's version with a tag would probably work for your scenario: `docker pull mcr.microsoft.com/playwright:bionic:v1.8.1-bionic`

**Comment by haikyuu** [comment]
Thanks @mxschmitt
It's worth noting that the image name is `mcr.microsoft.com/playwright:v1.8.1-bionic`.

Maybe we could add this to the docs for CI and/or display a warning that there is a mismatch between CI image and library version.

**Comment by mxschmitt** [comment]
I've created an issue to follow up on the Docker docs: #5591

Also a mismatch between the docker image version and the NPM library might be something to consider. Good point!

**Comment by pavelfeldman** [comment]
folding into #5591
