### ISSUE TITLE
[BUG] Playwright installation cause to UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by Pooort** [microsoft/playwright#5592]
**Context:**
System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
    Memory: 3.59 GB / 15.06 GB
    Container: Yes
  Binaries:
    Node: 14.15.0 - /usr/bin/node
    npm: 6.14.11 - /opt/test/test/node_modules/.bin/npm
  Languages:
    Bash: 4.2.46 - /usr/bin/bash
  npmPackages:
    playwright: ^1.9.0 => 1.9.0

**Code Snippet**

Under `root` user:
```
$PLAYWRIGHT_BROWSERS_PATH=/home/test/.cache/ms-playwright
npm install playwright
(node:720) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/home/test/.cache/ms-playwright'
```

But if I run:
```
node install.js
```
It downloads browsers correctly.

**Comment by aslushnikov** [comment]
@Pooort  There's an access error - for some reason your user cannot access `/home/test/.cache/ms-playwright` folder. 
Does it happen for you on v1.8.0?

**Comment by pavelfeldman** [comment]
Closing as per above.

**Comment by Semigradsky** [comment]
@pavelfeldman @aslushnikov I have the same issue, what the solution for this?

I tried `sudo npm install playwright` in ubuntu (wsl in Windows) and get errors like
```
(node:11346) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/root/.cache/ms-playwright'
(Use `node --trace-warnings ...` to show where the warning was created)
```

But I can create folder manually: `sudo mkdir /root/.cache/ms-playwright`

**Comment by Semigradsky** [comment]
`PLAYWRIGHT_BROWSERS_PATH=0` helped me.

**Comment by Pezhvak** [comment]
nothing worked, do anyone know why?

**Comment by aslushnikov** [comment]
@Pezhvak if you have a repro, please file! Maybe there's something we can do on our side

**Comment by Eideen** [comment]
I have the same problem.
using this repo: [MMM-YrThen](https://github.com/fmandal/MMM-YrThen)
install path is `/opt/magicmirror/modules/`

If running with user that have `HOME=/opt/magicmirror/`, it has access.

**Comment by letsandeepio** [comment]
This bug is still present as of date, resolved it by using command `PLAYWRIGHT_BROWSERS_PATH=0 npm install` , it seems when install.js script is invoked from within the npm it doesn't have sufficient permissions and give up.

```
npm ERR! command sh -c node install.js
npm ERR! node:internal/process/promises:288
npm ERR!             triggerUncaughtException(err, true /* fromPromise */);
npm ERR!             ^
npm ERR! 
npm ERR! [Error: EACCES: permission denied, mkdir '[user]/Library/Caches/ms-playwright/__dirlock'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/[user]Library/Caches/ms-playwright/__dirlock'
npm ERR! }
```

**Comment by sandeepk1989** [comment]
I am also facing the same issue which @letsandeepio mentioned. Does anybody got any solution?

**Comment by ctrlaltdylan** [comment]
Coming up in 2023, tried using the ENV flag mentioned but no luck.

**Comment by PeeJeeDR** [comment]
Also have the same error on my new M1 mac...

**Comment by richard-stafflink** [comment]
> `PLAYWRIGHT_BROWSERS_PATH=0` helped me.

https://playwright.dev/docs/browsers#hermetic-install
