### ISSUE TITLE
[Question] How to tab in webkit?

### ISSUE THREAD

**Issue by mfrachet** [microsoft/playwright#5609]
Hello folks 👋🏻 

I'm having a tiny problem: I'm using playwright to make accessibility testing and user navigation using the keyboard. And it works pretty well on chromium and firefox. My biggest issue, for now, is that in order to make WebKit react to tabs, I have to check a specific setting in the browser preferences.

See the following screenshot in safari showing the "Press Tab to highlight each item on a web page"

<img width="788" alt="Screenshot 2021-02-25 at 08 18 32" src="https://user-images.githubusercontent.com/3874873/109117609-83571000-7742-11eb-83ca-22fd45452593.png">

Do I have a way to allow for that setting using playwright so that I can write keyboard-oriented tests with Playwright?

**Comment by JoelEinbinder** [comment]
Sorry for the late response on this. While we can add this feature (`tabsToLinks` preference in WebKit), it is a pretty edge-case feature. On a Mac, holding down `Option` should reverse the tabbing behavior. In Playwright you would use `await page.keyboard.press('Alt+Tab')` to access the other behavior. Does that work for you?

**Comment by mfrachet** [comment]
Oh great! I didn't know about Alt+Tab and it actually works in my test :). Thanks for the hint 👍🏻
