### ISSUE TITLE
[BUG] Unable to use page.pause() inside of Promise.all block with response waiting

### ISSUE THREAD

**Issue by viraxslot** [microsoft/playwright#5611]
**Context:**
- Playwright Version: 1.9.0
- Operating System: MacOs
- Node.js version: 15.8.0
- Browser: chromium

**Describe the bug**

Hi, team! Awesome idea with the debugger, but I have a problem.
I wanted to place `page.pause()` inside the `page.create(data)` function and debug, but my script fails because of timeout for response waiting:

```javascript
const [response] = await Promise.all([
    page.waitForResponse(someUrl),
    page.create(data),
]);
```

I think it's needed to set infinite timeout for such cases if possible.
I'll try to provide repo a bit later, but I suppose reproducing is obvious :)

**Comment by pavelfeldman** [comment]
https://playwright.dev/docs/inspector#open-playwright-inspector suggests using `PWDEBUG=1`, but I agree that we can try disabling timeouts globally while on pause w/o that.

**Comment by viraxslot** [comment]
@pavelfeldman I double checked - the same behaviour with this env variable. And I used it of course.

**Comment by pavelfeldman** [comment]
Could it be that your testing framework times out? Which framework do you use?

**Comment by viraxslot** [comment]
@pavelfeldman I use `mocha`, but it's a different problem. I have 100 seconds timeout for my runner and debug fails because of this timeout, but not in the current case. This case fails because of response waiting.

Honestly I wanted to ask you about test runners: is there any possibility to set really big timeout automatically during playwright debug? I understand it's not about playwright, but it'll be really often case during the debug and it would be nice to have such feature.

**Comment by aslushnikov** [comment]
@viraxslot so can you please lead us with exact repro steps? A small demo repository on github, or maybe a step-by-step description with code snippets that I can copy locally and run?

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
