### ISSUE TITLE
How to skip Java script error in the application.

### ISSUE THREAD

**Issue by ajantabisht** [microsoft/playwright#5612]
Problem - 
I am getting "503 Service Temporarily Unavailable".
The application that I am testing is a 3rd party application and there is a javascript error on one of the pages.
I tried to "Uncaught Exception" using link https://docs.cypress.io/api/events/catalog-of-events.html#Examples but it is not helping me out. 
I am still getting "503 Service Temporarily Unavailable". 
Please help me in resolving this problem.

<img width="949" alt="Snag_4ba71c7" src="https://user-images.githubusercontent.com/25607476/109158112-393a5280-7773-11eb-807b-ee19af409c52.png">

**Comment by mxschmitt** [comment]
This is the Playwright repository which has no connection to the Cypress project. I think opening an issue on their side might help to get assistance there: https://github.com/cypress-io/cypress/issues/new/choose

**Comment by ajantabisht** [comment]
I am investigating both the tools, posted the question in the wrong thread.
