### ISSUE TITLE
Run playwright with firefox in Lambda

### ISSUE THREAD

**Issue by crazy-djactor** [microsoft/playwright#5613]
I am now trying to run playwright with firefox in aws lambda. My lambda is deployed as docker container
Playwright is working well with docker and firefox on my local, but I can't find a way how to run this on lambda with docker.

```
<launched> pid=23
[err] *** You are running in headless mode.
[err] ExceptionHandler::GenerateDump cloned child 34
[err] ExceptionHandler::SendContinueSignalToChild sent continue signal to child
[err] ExceptionHandler::WaitForContinueSignal waiting for continue signal...
=========================== logs ===========================
<launching> /opt/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-BYvMgD -juggler-pipe -silent
<launched> pid=23
[err] *** You are running in headless mode.
[err] ExceptionHandler::GenerateDump cloned child 34
[err] ExceptionHandler::SendContinueSignalToChild sent continue signal to child
[err] ExceptionHandler::WaitForContinueSignal waiting for continue signal...
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at Connection.sendMessageToServer (/var/task/node_modules/playwright/lib/client/connection.js:69:15)
    at Proxy.<anonymous> (/var/task/node_modules/playwright/lib/client/channelOwner.js:44:61)
    at /var/task/node_modules/playwright/lib/client/browserType.js:61:73
    at BrowserType._wrapApiCall (/var/task/node_modules/playwright/lib/client/channelOwner.js:72:34)
    at BrowserType.launch (/var/task/node_modules/playwright/lib/client/browserType.js:52:21)
    at Runtime.exports.lambdaHandler [as handler] (/var/task/app1.js:6:39)
    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)
END RequestId: ec405a11-a666-42ff-a6e3-a87050e38716
REPORT RequestId: ec405a11-a666-42ff-a6e3-a87050e38716	Duration: 1636.06 ms	Billed Duration: 2771 ms	Memory Size: 512 MB	Max Memory Used: 166 MB	Init Duration: 1134.78 ms	```

What should I do for this?```

**Comment by pavelfeldman** [comment]
Lambda might be lacking resources to run stock Firefox...

**Comment by aslushnikov** [comment]
@crazy-djactor we don't have much experience with AWS lambda - so we can't advice much here. Maybe someone from community can come over and help?

**Comment by crazy-djactor** [comment]
> @crazy-djactor we don't have much experience with AWS lambda - so we can't advice much here. Maybe someone from community can come over and help?

Thanks for reply.

**Comment by wesley-campbell-q2** [comment]
Someone was able to patch firefox to get it to work in lambda, https://github.com/george-lim/firefox-lambda

**Comment by burritoIand** [comment]
@crazy-djactor what's the context? I am running playwright as part of ci/cd using a custom build image w/playwright pre-loaded. It's nice because nothing is downloaded and it just runs the tests.

**Comment by eft24** [comment]
@mxschmitt, @aslushnikov , @pavelfeldman

I think the problem for firefox is no shared memory volume (/dev/shm) mounted on AWS Lambda environment.
Thats why we can use only Chrome, Chrome can pass this with --disable-dev-shm-usage

**Comment by rcribb** [comment]
> Someone was able to patch firefox to get it to work in lambda, https://github.com/george-lim/firefox-lambda

George mentioned shortly after publishing that this only works in the lambda handler local, and will not work deployed to the cloud. Mozilla seems to have no desire to fix the shared memory volume issue so it's unlikely this will ever be an option unless AWS makes it possible.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
