### ISSUE TITLE
[BUG] Drop support for Node.js 10 (2021-04-30)

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#5614]
When: 2021-04-30
Reference: https://nodejs.org/en/about/releases/

Actions:
- [ ] Change tsconfig target to ES2019 (https://node.green/#ES2019)
- [ ] Change GitHub Actions Node.js version from 10 to 12
- [ ] Update docs (search for Node.js)

Any other opinions on that? Should reduce a lot of complexity.

**Comment by aslushnikov** [comment]
Sounds good to me!

**Comment by kumaraditya303** [comment]
Docker images are based on `node` 14, so for consistency either playwright should target 🎯 `node` 14 or both should be based on `node` 12.
