### ISSUE TITLE
page.selectOption: Unknown engine "name" while parsing selector name="serviceType" [BUG]

### ISSUE THREAD

**Issue by dcleve333** [microsoft/playwright#5615]
**Context:**
- Playwright Version: 1.9.0 and 1.8.1
- Operating System: windows
- Node.js version: v14.15.4
- Browser: Chromium
- Extra: [any specific details about your environment]

Command:  npx folio .\xxx\xxx\<testname.spec.ts>  --param browserName=chromium --param headful

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

    //select service type
    async serviceType_select(serviceTypeToSelect: string) {
        return await this.page.selectOption('name="serviceType"', serviceTypeToSelect)
    }

Or, without inner quotes:

    //select service type
    async serviceType_select(serviceTypeToSelect: string) {
        return await this.page.selectOption('name=serviceType', serviceTypeToSelect)
    }

**Describe the bug**

selectOption works fine with an id selector, but not with name attribute selector.

**Comment by aslushnikov** [comment]
@dcleve333 there's no `name=` selector. We currently support only a handful of attribute selectors:
- `id`
- `data-testid`
- `data-test-id`
- `data-test`

We [have docs](https://playwright.dev/docs/next/selectors#id-data-testid-data-test-id-data-test-selectors) regarding this, but I admit they're not clear. Let us fix them!
