### ISSUE TITLE
[BUG] [Codegen] Page click recorded as click + goto

### ISSUE THREAD

**Issue by arjunattam** [microsoft/playwright#5617]
**Context:**
- Playwright Version: 1.9.0
- Operating System: macOS
- Browser: Chromium

Repro steps
1. Start recording actions on the microsoft/playwright github page
2. Click on pull requests
3. Expect to see click in the generated output. Actual has click + goto:

```javascript

  // Click text=Pull requests
  await page.click('text=Pull requests');
  // assert.equal(page.url(), 'https://github.com/microsoft/playwright/pulls');

  // Go to https://github.com/microsoft/playwright/pulls
  await page.goto('https://github.com/microsoft/playwright/pulls');
```

**Comment by dgozman** [comment]
Should be fixed by #6252.
