### ISSUE TITLE
[Question] Is there a way to inject JS code into all iframes?

### ISSUE THREAD

**Issue by michael-siek** [microsoft/playwright#5623]
Is there a way to get all of the iframes on the page and inject them with JavaScript code like this?

```js
const iframes = await page.$$('iframe')
const function = () => {console.log('hello world')}
for (const iframe of iframes) {
    await iframe.waitForElementState('stable')
	await iframe.evaluate(function)
}
```

**Comment by pavelfeldman** [comment]
https://playwright.dev/docs/api/class-page?pageaddinitscriptscript-arg

**Comment by michael-siek** [comment]
It looks like `Page#addinitscript` is only available on `page.` and not `frame.` and the return value of `const iframes = await page.$$('iframe')` is of type `ElementHandleForTag<"iframe">` which only has access to https://playwright.dev/docs/api/class-frame/

**Comment by aslushnikov** [comment]
@michael-siek the method is available on page - that's correct. It'll add the script in every frame in the given page. Isn't it what you want?

**Comment by pavelfeldman** [comment]
Closing as per above.
