### ISSUE TITLE
[BUG] Unexpected character in app icon 

### ISSUE THREAD

**Issue by zMrKrabz** [microsoft/playwright#5627]
**Context:**
- Playwright Version: 1.9.1
- Operating System: Ubuntu 20.4
- Node.js version: 15.9.0
- Extra: Packaging with [pkg](https://github.com/vercel/pkg)

**Code Snippet**
package.json
```json
  "pkg": {
    "assets": [
      "src/assets/**/*",
      "node_modules/playwright/browsers.json"
    ],
    "scripts": "./lib/**/*.js",
    "targets": [
      "node14-linux-x64",
      "node14-win-x64"
    ]
  }
```

**Describe the bug**

Currently using oclif and pkg to create a cli application, however, the app icon seems to have a malformed character. The error is resolved when I remove the png file, but I was hoping there was a less hacky way to go about it.

**Comment by aslushnikov** [comment]
>  the app icon seems to have a malformed character. The error is resolved when I remove the png file, but I was hoping there was a less hacky way to go about it.

@zMrKrabz what PNG file are we talking about here?

**Comment by zMrKrabz** [comment]
[web/recorder/app_icon.png](https://github.com/microsoft/playwright/blob/master/src/web/recorder/app_icon.png)

**Comment by aslushnikov** [comment]
> Currently using oclif and pkg to create a cli application, however, the app icon seems to have a malformed character.

@zMrKrabz hmm, this is a PNG icon - it's binary, there can be no malformed characters. Do I miss something? All in all, this does look like a bug in pkg to me - do you want to file this upstream?

**Comment by zMrKrabz** [comment]
I thought this might be a bug with `pkg` as well, but wanted to check with you first. I think it will be better to file this upstream.

**Comment by dannielibor** [comment]
Hi can we re-open this Im also experiencing this error. Any help? TIA

```
error  in ./node_modules/playwright/lib/web/recorder/app_icon.png

Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

 @ ./node_modules/playwright/lib/server/supplements/recorder/recorderApp.js 61:41-94
 @ ./node_modules/playwright/lib/server/supplements/recorderSupplement.js
 @ ./node_modules/playwright/lib/dispatchers/browserContextDispatcher.js
 @ ./node_modules/playwright/lib/dispatchers/browserDispatcher.js
 @ ./node_modules/playwright/lib/browserServerImpl.js
 @ ./node_modules/playwright/lib/inprocess.js
 @ ./node_modules/playwright/index.js
 @ ./src/background.js
 @ multi ./src/background.js
```

**Comment by cnikolov** [comment]
Me too 👍

**Comment by jomarocas** [comment]
same issue, if i remove, make error in playwright/lib/server/supplements/recorder'

**Comment by Bananamilk452** [comment]
i just added this in webpack config
you need to install `raw-loader` as devDependencies

for vue & webpack
```js
// vue.config.js
module.exports = {
  chainWebpack: (config) => {
    config.module
      .rule('ext')
      .test(/playwright/)
      .use('raw-loader')
      .loader('raw-loader')
      .end();
  }
}
```

for webpack only user (i didn't test this code)
```js
// webpack.config.js
module.exports = {
  //...
  module: {
    rules: [
      //...
      {
        test: /playwright/,
        use: [ { loader: 'raw-loader'} ]
      },
    ],
  },
};
```

**Comment by ttrreevvoorr** [comment]
Playwright is a fantastic package. This issue is also alive and well and should be considered for re-opening.

I am not sure if playwright is imported into the project properly when I use `raw-loader` as suggested by @Bananamilk452 -- I am missing (at least) devices on `const { devices, chromium } = require("playwright-chromium");`

With `raw-loader`:
```
const { devices, chromium } = require("playwright-chromium");
const iPhone11 = devices["iPhone 11 Pro"];
> Cannot read property 'iPhone 11 Pro' of undefined
```

Without a specific webpack loader:
```
ERROR in ./node_modules/playwright-chromium/node_modules/playwright-core/lib/server/chromium/appIcon.png 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
 @ ./node_modules/playwright-chromium/node_modules/playwright-core/lib/server/chromium/crApp.js 28:51-83
 @ ./node_modules/playwright-chromium/node_modules/playwright-core/lib/server/supplements/recorder/recorderApp.js
 @ ./node_modules/playwright-chromium/node_modules/playwright-core/lib/server/supplements/recorderSupplement.js
 @ ./node_modules/playwright-chromium/node_modules/playwright-core/lib/dispatchers/browserContextDispatcher.js
 @ ./node_modules/playwright-chromium/node_modules/playwright-core/lib/browserServerImpl.js
 @ ./node_modules/playwright-chromium/node_modules/playwright-core/lib/inProcessFactory.js
 @ ./node_modules/pl-chromium/node_modules/playwright-core/lib/inprocess.js
 @ ./node_modules/playwright-chromium/node_modules/playwright-core/index.js
```

Though I'd prefer not to use an entirely new webpack loader for one module if I can help it. Perhaps someone else knows of a loader or has written one that can resolve this issue for playwright if re-opening is not considered?

**Comment by yizhiyan** [comment]
I also encountered this problem when using pkg packaging
```
(function (exports, require, module, __filename, __dirname) { �PNG


SyntaxError: Invalid or unexpected token
    at new Script (vm.js:89:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
C:\snapshot\citi-reg\node_modules\playwright-core\lib\server\chromium\appIcon.png:1
(function (exports, require, module, __filename, __dirname) { �PNG


SyntaxError: Invalid or unexpected token
    at new Script (vm.js:89:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
> Warning Failed to make bytecode node12-x64 for file C:\snapshot\citi-reg\node_modules\playwright-core\lib\server\chromium\appIcon.png
```

**Comment by ngustavo** [comment]
Any news on this? I have the same issue.

**Comment by ngustavo** [comment]
Any news on this? I have the same issue.
I tried specifying `appIcon` as an asset but it still gives me the same error.
```js
// pkg.config.js
const { version } = require("./package.json");

module.exports = {
  name: `helper-v${version}.exe`,
  pkg: {
    assets: [
      "client/dist/**/*",
      "node_modules/playwright-core/lib/server/chromium/appIcon.png",
    ],
    targets: ["win"],
    outputPath: "bin",
  },
};
```

**Comment by ngustavo** [comment]
Any news on this? I have the same issue.

**Comment by MurzNN** [comment]
This issue makes impossible to test the apps UI with Pseudo-locale, because it throws an error on every English `i` character, that is pseudo-localized:
```
unexpected symbol "ĩ" at position N during parsing attribute value
```

What is pseudolocalization? More details are here https://lingui.dev/guides/pseudolocalization

**Comment by MurzNN** [comment]
A workaround for the issue is to use RegExp for checks, instead of plain strings, like this:
```ts
    await page.getByRole('button', { name: new RegExp('Ćĺĩćķ ḿē') }).click()
```

**Comment by MurzNN** [comment]
As this bug report is closed and can't be reopened, reported a fresh bug report about errors with pseudolocalized strings: https://github.com/microsoft/playwright/issues/41750
