### ISSUE TITLE
Migration script from puppeteer

### ISSUE THREAD

**Issue by KevinGrandon** [microsoft/playwright#563]
Nice library you all have here, it's unfortunate that this is not a new major version of puppeteer though. I think you all would gain a lot more adoption if you had a script to convert puppeteer tests to playwright tests. There should be a way of automatically doing this with a codemod.

**Comment by JoelEinbinder** [comment]
The apis are very similar. It should mostly be replacing require(“puppeteer”) with playwright. Is something particularly painful to transition?

**Comment by giuseppeg** [comment]
Would you have time to make a codemod?

**Comment by joewood** [comment]
Out of interest, any reason why the new features couldn't have been added to Puppeteer with a feature flag? Is there a more fundamental re-architecture in PlayWright?

**Comment by pavelfeldman** [comment]
Playwright is cross-browser and Puppeteer was only done for Chrome. Not all the Puppeteer APIs and abstractions made sense for cross-browser story. Playwright aims at testing: we wait for elements to be interactable when we click, etc. That's a significant change in philosophy, so maintaining the API would be misleading.

I don't think we will be providing a conversion utility, but there already are migration guides available in the wild.

**Comment by mmbatha** [comment]
> Playwright is cross-browser and Puppeteer was only done for Chrome. Not all the Puppeteer APIs and abstractions made sense for cross-browser story. Playwright aims at testing: we wait for elements to be interactable when we click, etc. That's a significant change in philosophy, so maintaining the API would be misleading.
> 
> I don't think we will be providing a conversion utility, but there already are migration guides available in the wild: https://medium.com/@davert/puppeteer-to-playwright-migration-guide-6c86ea66e85e

The author deleted the Medium article referred to above
