### ISSUE TITLE
[Question]  Logging into Azure AD on azure-pipeline?

### ISSUE THREAD

**Issue by waystilos** [microsoft/playwright#5630]
Looking for advice on the best approach for logging into Azure AD on azure pipeline. 

On my local machine, auth works as specified on the [ playwright docs](https://playwright.dev/docs/auth/?_highlight=authe#reuse-authentication-state). Currently, when I run my CRA app on azure pipeline,  I'm currently using [start-server-and-test](https://github.com/bahmutov/start-server-and-test) but throws errors sometimes.  My package.json to run this is:

```
  "scripts": {
    "ci": "start-server-and-test start :3000 test-e2e",
    "test-e2e": "jest --config=jest.integration.config.js"
    }
```

I would like to use [jest-playwright](https://github.com/playwright-community/jest-playwright) to run the server but it doesn't run the globalSetup where my auth is being executed there so it'll throw an error.  Any advice on how to handle this in azure-pipeline?

Thanks!

**Comment by aslushnikov** [comment]
> Currently, when I run my CRA app on azure pipeline, I'm currently using start-server-and-test but throws errors sometimes

@waystilos who throws errors and what kind of errors? Is it playwright or is it the server startup? Could it be that you try to automate website too early, before the server actually started?

**Comment by waystilos** [comment]
> @waystilos who throws errors and what kind of errors? Is it playwright or is it the server startup? Could it be that you try to automate website too early, before the server actually started?

@aslushnikov Thanks for the reply! Here is the error in ADO when it hits the Azure AD login screen when it asks "Do you want to stay logged in" and has the option to click the checkbox. It got past the email and the password screen without a problem.

```
/usr/bin/npm run ci

page.click: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "text="Yes""
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.Error
    at Object.captureStackTrace (/__w/1/s/client/node_modules/playwright/lib/utils/stackTrace.js:48:19)
    at Connection.sendMessageToServer (/__w/1/s/client/node_modules/playwright/lib/client/connection.js:69:48)
    at Proxy.<anonymous> (/__w/1/s/client/node_modules/playwright/lib/client/channelOwner.js:64:61)
    at /__w/1/s/client/node_modules/playwright/lib/client/frame.js:279:34
    at Frame._wrapApiCall (/__w/1/s/client/node_modules/playwright/lib/client/channelOwner.js:77:34)
    at Frame.click (/__w/1/s/client/node_modules/playwright/lib/client/frame.js:278:21)
    at /__w/1/s/client/node_modules/playwright/lib/client/page.js:447:60
    at Page._attributeToPage (/__w/1/s/client/node_modules/playwright/lib/client/page.js:231:20)
    at Page.click (/__w/1/s/client/node_modules/playwright/lib/client/page.js:447:21)
    at module.exports (/__w/1/s/client/__tests__/config/authSetup.js:19:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sa-cc-ui@0.1.0 test-e2e: `jest --config=jest.integration.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sa-cc-ui@0.1.0 test-e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by aslushnikov** [comment]
@waystilos it does look like there's no "Yes" to click. Could it be that it doesn't appear sometimes? Any chance you can take a screenshot if the `await page.click('text="Yes"')` times out on Azure Pipelines and check to see what's the in the browser?

**Comment by waystilos** [comment]
> @waystilos it does look like there's no "Yes" to click. Could it be that it doesn't appear sometimes? Any chance you can take a screenshot if the `await page.click('text="Yes"')` times out on Azure Pipelines and check to see what's the in the browser?

The screen shots aren't too helpful but it would appear you're right. There is no checkbox. 

![test-shot](https://user-images.githubusercontent.com/5862314/109341032-abb43c80-781e-11eb-847b-d638c7c111b3.png)

When I remove the check for checkbox and the "yes" button or leave the yes button, it hangs and fails on this line:

`  await page.waitForSelector('text="TEST TEXT"')`

I tried to use `wait-on` in a little script to make sure the server is up before it runs the tests but got the same failures.

**Comment by waystilos** [comment]
I found out that the library we use for logging in has a mock provider so I ended up bypassing logging in. Thanks again for all the help!

**Comment by aslushnikov** [comment]
@waystilos Great news!

**Comment by bheemreddy181** [comment]
@aslushnikov is there a way we can simulate a similar functionality like cypress https://medium.com/version-1/using-cypress-to-test-azure-active-directory-protected-spas-47d04f5add9 ?
