### ISSUE TITLE
[BUG] Chromium 'push' permission does not work

### ISSUE THREAD

**Issue by xylix** [microsoft/playwright#5631]
**Context:**
- Playwright Version: v1.9.1
- Operating System: Arch Linux
- Node.js version: 14
- Browser: chromium

```
npx: installed 1 in 0.658s

  System:
    OS: Linux 5.11 Arch Linux
    Memory: 8.53 GB / 15.55 GB
    Container: Yes
  Binaries:
    Node: 15.10.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.11 - /usr/bin/npm
  Languages:
    Bash: 5.1.4 - /usr/bin/bash
  npmPackages:
    playwright: ^1.9.1 => 1.9.1 
```

Also happened to a downstream user of robotframework-browser who was using a different setup. Can repro on macOS.
 
**Code Snippet**

```javascript
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();
  // browser.newContext({ permissions: ['push'] })
  const context = await browser.newContext()
  context.grantPermissions(['push'])
  
  await browser.close();
})();
```

**Describe the bug**

Code above crashes with 
```
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

browserContext.grantPermissions: Unknown permission: pushError
    at Object.captureStackTrace (/home/kerkko/Downloads/playwright-chromium-notification-bug-repro/node_modules/playwright/lib/utils/stackTrace.js:48:19)
    at Connection.sendMessageToServer (/home/kerkko/Downloads/playwright-chromium-notification-bug-repro/node_modules/playwright/lib/client/connection.js:69:48)
    at Proxy.<anonymous> (/home/kerkko/Downloads/playwright-chromium-notification-bug-repro/node_modules/playwright/lib/client/channelOwner.js:64:61)
    at /home/kerkko/Downloads/playwright-chromium-notification-bug-repro/node_modules/playwright/lib/client/browserContext.js:142:27
    at ChromiumBrowserContext._wrapApiCall (/home/kerkko/Downloads/playwright-chromium-notification-bug-repro/node_modules/playwright/lib/client/channelOwner.js:77:34)
    at ChromiumBrowserContext.grantPermissions (/home/kerkko/Downloads/playwright-chromium-notification-bug-repro/node_modules/playwright/lib/client/browserContext.js:141:21)
    at /home/kerkko/Downloads/playwright-chromium-notification-bug-repro/index.js:7:11
```

Might be related to https://github.com/puppeteer/puppeteer/issues/3573. Does not seem to happen with firefox or webkit.

**Comment by pavelfeldman** [comment]
Could you share more on your scenario? Are you talking about a notification permission?

**Comment by xylix** [comment]
There seem to be both 'nofitications' and 'push' permissions, documented here https://playwright.dev/docs/api/class-browsercontext#browsercontextgrantpermissionspermissions-options. 

It is unclear to me which of ['notifications', 'push'] permissions does grant push notification permission, or does either. But it at least seems like there is either a documentation or a code problem here.

For context: I'm an author of the RobotFramework browser automation library which uses Playwright, and heard from this from one of our end users. The end user is trying to test an application's push notifications.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.

**Comment by TomasHubelbauer** [comment]
I think the right permission might be `notifications`. See #3301. Unfortunately it doesn't seem to work end to end even with it.

**Comment by ThisIsBenny** [comment]
Any updates here? I notice this error when i run the Tests in debug mode:

![image](https://github.com/microsoft/playwright/assets/66417262/b6633595-7502-477e-a77c-a413e9db54ee)

https://bugs.chromium.org/p/chromium/issues/detail?id=401439

Are all tests running in Incognito mode? If yes, this would be maybe the reason why Permissions for Notifications are not working as expected.
