### ISSUE TITLE
[Question] How to download a file which just starts downloading once you goto url in Python

### ISSUE THREAD

**Issue by bhaskar253** [microsoft/playwright#5639]
**My Code:**
```
import asyncio
from playwright.async_api import async_playwright as apw

async def main():
    async with apw() as p:
        b = await p.chromium.launch(headless=False,downloads_path="dwld")
        pg = await b.new_page(accept_downloads=True)
        async with pg.expect_download(timeout=0) as di:
            await pg.goto("http://ovh.net/files/1Mb.dat",wait_until="networkidle")
        dwld = await di.value
        print(await dwld.path())
        await b.close()

if __name__ == '__main__':
    asyncio.run(main())
```

**Upon trying the above-mentioned code I keep on getting**
```Traceback (most recent call last):
  File "test.py", line 16, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "test.py", line 9, in main
    await pg.goto("http://ovh.net/files/1Mb.dat",wait_until="networkidle")
  File "/home/test/my_test/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 5811, in goto
    await self._async(
  File "/home/test/my_test/lib/python3.8/site-packages/playwright/_impl/_page.py", line 461, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/home/test/my_test/lib/python3.8/site-packages/playwright/_impl/_frame.py", line 114, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/home/test/my_test/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "/home/test/my_test/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 47, in inner_send
    result = await callback.future
playwright._impl._api_types.Error: net::ERR_ABORTED at http://ovh.net/files/1Mb.dat
```

**Comment by pavelfeldman** [comment]
There is no download in this page, so Playwright gets confused. What is your use case? It does not look like something user would do.

**Comment by bhaskar253** [comment]
My use case is like I will open and sign in to web-page for parsing "**identifier**" from the loaded page then using that identifier generate URL, which upon loading starts the download. 

Finding and generating the download URL part is complete, but I am stuck in loading the download URL. 

The above code is just trying to achieve going to download URL scenario, which will trigger the download event upon loading it.

**Note:**
"http://ovh.net/files/1Mb.dat" this link is working for me, if it is not working for you could you try replacing it with
"https://speed.hetzner.de/100MB.bin"

**Comment by pavelfeldman** [comment]
I see. You could generate a link that you click that results in a download. Something like:

```js
const downloadUrl = 'https://speed.hetzner.de/100MB.bin';
const [download] = await Promise.all([
  page.waitForEvent('download'),
  page.evaluate(href => {
    const a = document.createElement('a');
    a.href = href;
    a.download = true;
    a.click();
  }, downloadUrl)
]);
```

**Comment by bhaskar253** [comment]
@pavelfeldman Thank you for the code. 


```python
# Python version for the same:
url = 'https://speed.hetzner.de/100MB.bin'
dwld = await asyncio.gather(
    page.wait_for_event('download'),
    page.evaluate('''href => {
        const a = document.createElement('a');
        a.href = href;
        a.download = true;
        a.click();
    }''', [url])
)
await dwld[0].save_as("100MB.bin")
await dwld[0].delete()
```

**P.S.** _It would be great if we add this example in Playwright's Python Document._

**Comment by Docdez** [comment]
> I see. You could generate a link that you click that results in a download. Something like:
> 
> ```js
> const downloadUrl = 'https://speed.hetzner.de/100MB.bin';
> const [download] = await Promise.all([
>   page.waitForEvent('download'),
>   page.evaluate(href => {
>     const a = document.createElement('a');
>     a.href = href;
>     a.download = true;
>     a.click();
>   }, downloadUrl)
> ]);
> ```

I have deal with it also and it's look like workaround.

Another solution is use request by page context, but:

1. all data hold on memory( 
2. hello memory limitation with no possibility to increase it [(#13449)](https://github.com/microsoft/playwright/issues/13449)

I agree with the documentation on this matter.
