### ISSUE TITLE
[Question] How to start webkit with persistent context?

### ISSUE THREAD

**Issue by downstream84** [microsoft/playwright#5642]
I want to start webkit as I can do with chromium or firefox using PersistentContext, so that I can read data from a forum which I browse and use the saved session.

In chromium I do 

`options['executablePath'] = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';`
`var browser = await playwright.chromium.launchPersistentContext(data_directory['chrome'], options);`

How can I do the same for Safari (WebKit)?

**Comment by pavelfeldman** [comment]
Setting up a context using persistent session and then reusing it isn't a recommended way of handling logged-in tests, etc. The recommended way is described [here](https://playwright.dev/docs/auth#reuse-authentication-state) and [here](https://playwright.dev/docs/cli#preserve-authenticated-state). The idea is that you use CLI to set up your context, then you persist the state into the file and re-create as many ephemeral contexts that use this initial data as you'd like. It works with all the browsers. Please tell us if that was what you were looking for.

**Comment by yury-s** [comment]
Closing per the response above.
