### ISSUE TITLE
[Question]why not ref the TestProject Recorder

### ISSUE THREAD

**Issue by chenshuichao** [microsoft/playwright#5647]
I use TestProject Recorder some days, it is very amazing!
I like playwright much too,so why not ref the TestProject Recorder?
https://docs.testproject.io/using-the-smart-test-recorder/web-testing/creating-a-web-test-using-the-testproject-recorder

**Comment by pavelfeldman** [comment]
Sorry, it us unclear what the actual question is.

**Comment by pavelfeldman** [comment]
You probably want us to add a link to it to the show cases? I don't think TestProject Recorder has any relation to Playwright, so I'm closing your request.
