### ISSUE TITLE
[Question] How to disable Debug mode, once I set PWDEBUG in env. variable now it's always running in debug mode

### ISSUE THREAD

**Issue by yousufwaqar** [microsoft/playwright#5649]

**Comment by pavelfeldman** [comment]
What do you call a debug mode? pw:api only prints the logs, it isn't a debug mode, PWDEBUG=1 is.

**Comment by mxschmitt** [comment]
Probably you used `set` on Windows, which sets the environment variable for the current shell, try to either reset it with:

```
set DEBUG=
```

or create a new terminal shell.

**Comment by yousufwaqar** [comment]
@Pavelfeldman, even though by just using node Filename.js. it's opening the inspector tool everytime and have to explicitly press the play button to continue the execution. It's been only few days that I am using Playwright, maybe I've missed something but I think the inspector feature introduced in 1.9.1 few days ago only.

**Comment by yousufwaqar** [comment]
> Probably you used `set` on Windows, which sets the environment variable for the current shell, try to either reset it with:
> 
> ```
> set DEBUG=
> ```
> 
> or create a new terminal shell.

No, I only used set DEBUG=pw:api

**Comment by pavelfeldman** [comment]
Could you check if your environment has PWDEBUG variable set?

**Comment by yousufwaqar** [comment]
> Could you check if your environment has PWDEBUG variable set?

@pavelfeldman , Yes env. had PWDEBUG variable set to 1. after deleting it. the scripts are running fine but to check I set the variable again it was again launching the browser along with inspector even after simply just running the script using node fiilename.js. Is this expected behavior that we have to explicitly add and delete PWDEBUG variable every-time we want to debug using inspector cuz it could be a little tedious.

**Comment by pavelfeldman** [comment]
You can use `cross-env` to simplify it on Windows:

```sh
npx cross-env PWDEBUG=1 node test.js
```

This will only enable this environment variable for the time of execution.
