### ISSUE TITLE
WebKit build flags

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright#565]
WebKit has a lot of compile time flags that radically change its behavior. Each of our ports has different defaults. We should audit them and try to make each as close to safari as possible.

**Comment by pavelfeldman** [comment]
I'm on it.

**Comment by aslushnikov** [comment]
For the record: webkit flags are now available in [//docs/webkit.md](https://github.com/microsoft/playwright/blob/master/docs/webkit.md)
