### ISSUE TITLE
[BUG]: Missing video codecs for Firefox on Fedora

### ISSUE THREAD

**Issue by CL-Jeremy** [microsoft/playwright#5651]
**Context:**
- Playwright Version: 1.9.1
- Operating System: Fedora 33
- Node.js version: 14.15.4
- Browser: Firefox
- Extra: FFmpeg installed (even with `-devel` packages) from negativo17-repo (3rd-party, but installs to standard location) 

```
npx envinfo --preset playwright

  System:
    OS: Linux 5.9 Fedora 33 (Workstation Edition) 33 (Workstation Edition)
    Memory: 447.86 MB / 11.68 GB
    Container: Yes
  Binaries:
    Node: 14.15.4 - /usr/bin/node
    Yarn: 1.22.4 - ~/.local/bin/yarn
    npm: 6.14.10 - /usr/bin/npm
  Languages:
    Bash: 5.0.17 - /usr/bin/bash
  npmPackages:
    playwright: ^1.9.1 => 1.9.1 
```

**Describe the bug**

(FYI, on Arch Linux it's working fine, so this might relate to Red Hat using `/usr/lib64` for libraries)

Cannot play videos with the bundled Firefox nightly, neither with HTML5, nor by directly opening local video file.

Sample debug output:
```
[Child 197974, MediaDecoderStateMachine #1] WARNING: Decoder=7fa87413d800 Decode error: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005) - Error no decoder found for video/avc: file /home/azureuser/actions-runner/_work/playwright-internal/playwright-internal/browser_patches/firefox/checkout/dom/media/MediaDecoderStateMachine.cpp:3474
```

I haven't tried symlinking the libraries elsewhere, but it's strange that this doesn't work, as `ldconfig` should be taking care of this already, and setting `LD_LIBRARY_PATH` has no effect.

**Comment by CL-Jeremy** [comment]
Just tried symlinking the libraries to `.cache/ms-playwright/firefox-1234/firefox` with no avail.

Bundled Chromium and WebKit both work. Firefox from package manager works.

**Comment by CL-Jeremy** [comment]
Further testing with Chromium (headful) reveals that it was actually not playing, but rather was manage to capture the thumbnail before video kicks in (JavaScript), which makes more sense now. WebKit is working consistently, though.

**Comment by yaakov123** [comment]
I'm getting a similar issue when trying to play a video with Chromium. I get the following error in the videoElement.error property:

MediaError {code: 4, message: "DEMUXER_ERROR_NO_SUPPORTED_STREAMS: FFmpegDemuxer: no supported streams"}

**Comment by CL-Jeremy** [comment]
> I'm getting a similar issue when trying to play a video with Chromium. I get the following error in the videoElement.error property:
> MediaError {code: 4, message: "DEMUXER_ERROR_NO_SUPPORTED_STREAMS: FFmpegDemuxer: no supported streams"}
> This is on Windows

I think that'd be a different issue though. in my case the value is `null`.

**Comment by xflihaibo** [comment]
**Context:**
- Playwright Version:1.10.0
- Operating System: mac
- Node.js version: 12.22
- Browser:  Chromium

```javascript
browserContext.newPage: 
============================================================
  Please install ffmpeg in order to record video.

  $ npx playwright install ffmpeg
============================================================
      
Error
    at Object.captureStackTrace (/Applications/eTest.app/Contents/Resources/app.asar/node_modules/playwright/lib/utils/stackTrace.js:48:19)
    at Connection.sendMessageToServer (/Applications/eTest.app/Contents/Resources/app.asar/node_modules/playwright/lib/client/connection.js:69:48)
    at Proxy.<anonymous> (/Applications/eTest.app/Contents/Resources/app.asar/node_modules/playwright/lib/client/channelOwner.js:64:61)
    at /Applications/eTest.app/Contents/Resources/app.asar/node_modules/playwright/lib/client/browserContext.js:119:52
    at ChromiumBrowserContext._wrapApiCall (/Applications/eTest.app/Contents/Resources/app.asar/node_modules/playwright/lib/client/channelOwner.js:77:34)
    at ChromiumBrowserContext.newPage (/Applications/eTest.app/Contents/Resources/app.asar/node_modules/playwright/lib/client/browserContext.js:116:21)
    at file:///Applications/eTest.app/Contents/Resources/app.asar/build/static/js/main.f0b88d7d.chunk.js:1:30692
    at u (file:///Applications/eTest.app/Contents/Resources/app.asar/build/static/js/2.6ec6b73d.chunk.js:2:639728)
    at Generator._invoke (file:///Applications/eTest.app/Contents/Resources/app.asar/build/static/js/2.6ec6b73d.chunk.js:2:639516)
    at Generator.next (file:///Applications/eTest.app/Contents/Resources/app.asar/build/static/js/2.6ec6b73d.chunk.js:2:640153)

```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
