### ISSUE TITLE
[Question] QuerySelector not grabbing all elements

### ISSUE THREAD

**Issue by Alcampopiano** [microsoft/playwright#5653]
Hi Folks!

Thanks so much for playwright. It's awesome!

Quick question:

I'm using trying to grab a list of elements containing the text "Running" in MS Flows. I use the following command:

`running_jobs = page.querySelectorAll("text='Running'")`

Unfortunately, I noticed that it does not grab all the running jobs. For example, the variable `running_jobs`
contains only 7 elements, but as you can see below there are 8 running jobs. The last job is not getting captured.

Could anyone nudge me in the right direction here as to what I'm doing incorrectly?

![sc](https://user-images.githubusercontent.com/4624246/109513226-e1516380-7a72-11eb-8394-5435cbd2f130.png)

**Comment by pavelfeldman** [comment]
It is a little hard to tell without seeing the DOM, but your selector looks good. Could it be that 8th element appears after you queried?

**Comment by Alcampopiano** [comment]
Thank you so much!!! Yes, I think the elements at the bottom had not yet been loaded as you've suggested. I added some statements to allow the program to wait and that seems to fix the issue. Thanks again!
