### ISSUE TITLE
[BUG] playwright-chromium tries to do webkit tasks

### ISSUE THREAD

**Issue by kblok** [microsoft/playwright#5677]
**Context:**
- Playwright Version: 1.9.1
- Operating System: Mac 11.2

I was getting an `Playwright does not support webkit on mac11.2` while trying to do `npm install playwright`, I mentioned that here #5443
In the meantime, I wanted just at least use `playwright-chromium`, but I got the same error

```
neo@darios-mbp playwright % npm install playwright-chromium 
npm ERR! code 1
npm ERR! path /Users/neo/node_modules/playwright-webkit
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! /Users/neo/node_modules/playwright-webkit/lib/utils/utils.js:58
npm ERR!         throw new Error(message);
npm ERR!               ^
npm ERR! 
npm ERR! Error: ERROR: Playwright does not support webkit on mac11.2
npm ERR!     at Object.assert (/Users/neo/node_modules/playwright-webkit/lib/utils/utils.js:58:15)
npm ERR!     at revisionURL (/Users/neo/node_modules/playwright-webkit/lib/install/browserFetcher.js:125:13)
npm ERR!     at Object.downloadBrowserWithProgressBar (/Users/neo/node_modules/playwright-webkit/lib/install/browserFetcher.js:150:17)
npm ERR!     at async validateCache (/Users/neo/node_modules/playwright-webkit/lib/install/installer.js:85:9)
npm ERR!     at async installBrowsersWithProgressBar (/Users/neo/node_modules/playwright-webkit/lib/install/installer.js:43:5)
```

I think we should do webkit stuff if I want to install the chromium flavor.

**Comment by mxschmitt** [comment]
Could it be that you have `playwright-webkit` also installed in your package.json? Because the `postinstall` hooks run after the install, so even when vplaywright-webkit` is outdated and you install latest `playwright-chromium` the `postinstall` of `playwright-webkit` will run and by that show the error.

**Comment by kblok** [comment]
nope, brand new, empty folder.

**Comment by mxschmitt** [comment]
It seems like there is a package.json/node_modules folder in the user's home directory: /Users/neo/node_modules/playwright-webkit/
And then your children npm installs picks this one up (which is outdated), since it traverses up to the root dir.

**Comment by kblok** [comment]
I don't know how you did it but you just hacked into my machine. Well done!
