### ISSUE TITLE
Flag page.query_selector that matches multiple elements

### ISSUE THREAD

**Issue by pohlt** [microsoft/playwright#5680]
Thanks for playwright, it's awesome!

IMHO the current behavior for `page.query_selector` which returns any (the first?) matching element is quite error-prone. I can see why you try to stay as close as possible to the JS behavior, but if you look at it without a JS bias, it would be less error-prone if it would raise an exception if there's more than exactly one match.

You still have `page.query_selector_all` if you want all matches.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
