### ISSUE TITLE
[Question] How to run headful in docker visually (macOS)

### ISSUE THREAD

**Issue by ayroblu** [microsoft/playwright#5688]
Hey, I've been trying to figure this out, I want to run playwright to "debug" i.e. in headful mode but also run it in CI, therefore in docker. I was wondering if it's possible to run it in docker and visually see it?

I think I got as far as writing a script that runs playwright headfully, then calling `xvfb-run node index.js` but I don't know how to actually see the browser, is that possible?

**Comment by weyert** [comment]
You can try to connect to the docker file using `tigervnc`, a vnc viewer which you could try to connect to `xfvb` or together with `xfce`.

**Comment by ayroblu** [comment]
Thanks for the hint, I did find this example of running vnc with docker:
https://github.com/jkuri/docker-ubuntu-vnc

I had a general think about this overnight and I think this is unnecessarily complicated for my use case, probably I'll just make a rule to not do screenshot tests natively, especially while headful.
