### ISSUE TITLE
[Feature] breakdown PWDEBUG flags

### ISSUE THREAD

**Issue by idoros** [microsoft/playwright#5693]
I was using `PWDEBUG` in order to preserve the developer tools settings as part of my workflow process. Over time the `PWDEBUG` introduced more setting, like the automatic opening of the new inspector and canceling the timeout. 

The main thing that broke my flow was the `x-pw-glass` element injected by the inspector. The element cannot be toggled off even while the inspector is closed and causes my image snapshots to fail (I think it would be nice to somehow hide the `x-pw-glass` element from snapshots).

I wonder if those behaviors could be broken down into individuals environment variables?

**Comment by pavelfeldman** [comment]
Makes sense. *Note that the cancel timeout behavior has always been there*.
