### ISSUE TITLE
[Feature] Docker image with custom Node/Npm version

### ISSUE THREAD

**Issue by lavcraft** [microsoft/playwright#5698]
Hi, i'm working with official docker image mcr.microsoft.com/playwright:bionic

https://github.com/microsoft/playwright/blob/master/utils/docker/Dockerfile.bionic

I need replace node version to 15 in my cases these days in default docker image. What do you think about template Dockerfile for build set of each version. 

For example, in my mind:
```
mcr.microsoft.com/playwright:bionic-node15
mcr.microsoft.com/playwright:bionic-node14
mcr.microsoft.com/playwright:bionic-npm75
```

What do you think about it?

**Comment by pavelfeldman** [comment]
No plans to do this atm, we will switch our image to newer Node LTS once existing one ends life. I'd recommend to build this image locally for now.
