### ISSUE TITLE
[Question] Can we not scroll element into view by default while using elementHandle.hover() ?

### ISSUE THREAD

**Issue by NareshMurthy** [microsoft/playwright#5700]
I have a scenario where the element is already scrolled 50% , is there a way to hover over without disturbing the scroll?

Thanks!

**Comment by pavelfeldman** [comment]
@dgozman, wdyt?

**Comment by dgozman** [comment]
This is technically possible. Could you please share why scrolling is a problem? I'd like to better understand the scenario to provide the optimal solution to our users.

**Comment by NareshMurthy** [comment]
I am running the test on a page which has an Ad Element, the element records the percentage it is being viewed.
 In my case, I have already scrolled the element to some percentage.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
