### ISSUE TITLE
[BUG] ConnectOverCDP Duplicate target Error

### ISSUE THREAD

**Issue by selang** [microsoft/playwright#5701]
**Context:**
- Playwright Version: [1.9.1]
- Operating System: [Windows7 x64]
- Node.js version: [v12.18.3]
- Browser: [Chrome 88.0.4324.104    89.0.4389.72]
- Extra: [node-fetch 2.6.1]

**Code Snippet**

After the following code runs, it will always report exceptions 

```javascript
const {chromium} = require('playwright');
const fetch = require('node-fetch');

async function getHtml(url) {
    let resp = await fetch(url, {
        method: 'GET'
    });
    return await resp.text();
}

async function doSomething(url) {
    let browserVersion = await getHtml("http://localhost:9222/json/version");
    let browserVersionJSON = JSON.parse(browserVersion);
    let wsEndpoint = browserVersionJSON.webSocketDebuggerUrl;
    let browser = await chromium.connectOverCDP({
        wsEndpoint
    });
    let contexts = await browser.contexts();
    if (contexts.length == 1) {
        let defaultContext = contexts[0];

        let page = await defaultContext.newPage();
        await page.goto(url);
        await page.close();
        await browser.close();
    } else {
        await browser.close();
    }
}

(async () => {
    for (let i = 0; i < 10; i++) {
        console.log(`============ >${i + 1} times`);
        let bugTriggerUrl = 'https://playwright.dev';
        let bugNoTriggerUrl = 'https://www.google.com';
        await doSomething(bugTriggerUrl);
        // await doSomething(bugNoTriggerUrl);
    }
})();
```

**Describe the bug**

It seems to be related to the website, the previous Google website will trigger the bugger, but today it is found that it cannot be reproduced. Now it is found that https://playwright.dev will also trigger the bugger.

(node:13056) UnhandledPromiseRejectionWarning: Error: Duplicate target 06859E3437592E4AC988B694F81BCBBF

**Comment by pavelfeldman** [comment]
I just tried it locally and I could not reproduce it. Chrome 88 as well.

I also added `console.log(browserVersionJSON);` to ensure that this was indeed Chrome I intended to connect. Could you print it as well?

Also, could you run it as 

```sh
npx cross-env DEBUG=pw:protocol node test.js
```

And share the log with us?

@JoelEinbinder ^^

**Comment by selang** [comment]
> I just tried it locally and I could not reproduce it. Chrome 88 as well.
> 
> I also added `console.log(browserVersionJSON);` to ensure that this was indeed Chrome I intended to connect. Could you print it as well?
> 
> Also, could you run it as
> 
> ```shell
> npx cross-env DEBUG=pw:protocol node test.js
> ```
> 
> And share the log with us?
> 
> @JoelEinbinder ^^

I have updated the bugger to reproduce the code and instructions, and attached the log file. Thank you for your prompt feedback.

**Comment by VikramTiwari** [comment]
Here's another sample: https://github.com/microsoft/playwright/issues/5648#issuecomment-788268209

**Comment by pavelfeldman** [comment]
Folding into #5648 we'll issue a patch release with the fix.
