### ISSUE TITLE
[Question] is there a way to select text in the DOM?

### ISSUE THREAD

**Issue by amit-parizian-erudite** [microsoft/playwright#5714]
Hi!
is there a way to emulate selection of some text in a paragraph?
for example, if the page contains something like:
`<p> here I have some text that I want to select <p>`
and I want to select a part of it, say "have some". is there a way to do it?
by selecting I mean like a user can do with the mouse:
![image](https://user-images.githubusercontent.com/78478421/109962384-ca6d7400-7cf3-11eb-8520-2860e57b1bb7.png)

**Comment by amit-parizian-erudite** [comment]
BTW, I tried to do something like this:
`const elem = await this.page.$(
      "text=have some"
    );
    const box = await elem.boundingBox();
    await this.page.mouse.move(box.x, box.y);
    await this.page.mouse.down();
    await this.page.mouse.move(box.x + 30, box.y + 1);
    await this.page.mouse.up();`

but box.x and box.y is the top left of the box so I can only select words from the start of the <p> node (of course I can play around with the numbers, but it is not really a solution).
so I am looking for some native way to do this, preferably by the words that I want to select and not coordinates.
Thanks in advance!

**Comment by pavelfeldman** [comment]
You can do this with DOM api, but not via the mouse drag atm:
```js
await pagea.$eval('selector', element =>
    const range = element.ownerDocument.createRange();
    range.setStart(element, 10);
    range.setEnd(element, 20);
    const selection = element.ownerDocument.defaultView.getSelection();
    selection.removeAllRanges();
    selection.addRange(range);
})
```

Is selecting using drag essential to your use case?

**Comment by amit-parizian-erudite** [comment]
thanks a lot for the quick answer! 
no it's not essential. bu the solution you gave me doesn't work (or I don't fully understand how to use it).
say I have `<p> this is some text that I have <strong> and this is some bold text I have </strong> <p>`
so if I use createRange on the <p> element it returns "this is some text that I have" for range (0,1) and "and this is some bold text I have" for range (1,2). and for anything other than that it says "There is no child at offset X."
if I am doing something wrong I'd be happy to get a link to some guide to this solution.
if not, do you have any other ideas on how can I select certain words inside the paragraph?
thanks.

**Comment by yury-s** [comment]
The solution above is slightly incorrect as you need to specify positions within text nodes, so what you need is something like this:
```js
  await page.setContent(`<p> this is some text that I have <strong> and this is some bold text I have </strong> </p>`);
  await page.$eval('p', element => {
    const range1 = element.ownerDocument.createRange();
    const text1 = element.firstChild;
    const text2 = element.firstElementChild.firstChild;
    range1.setStart(text1, 10);
    range1.setEnd(text2, 20);
    const selection = element.ownerDocument.defaultView.getSelection();
    selection.removeAllRanges();
    selection.addRange(range1);
  });
```

It will select a range which spans across several DOM nodes.

![image](https://user-images.githubusercontent.com/9798949/110400865-45ed5f00-802d-11eb-8753-e33282b562a0.png)


Please reopen this issue if it doesn't work for you.

**Comment by yury-s** [comment]
> unfortunately this didn't work. using this method selects nothing for me for some reason (don't know why).

Do you mean this particular example didn't work or it didn't work for your DOM tree? If the latter, could you share source of the page where you try to select the text and the code that does it, otherwise it's hard to give a meaningful advise?

> is there any way to use the mouse to select text by the content? ideally, something like page.mouse.move(text=middle of line)

There is no such API.

**Comment by yury-s** [comment]
Can you also show your code snippet and explain what's not working?

**Comment by amit-parizian-erudite** [comment]
async tryThis() {
    await this.page.$eval(
      "text=Bloom's taxonomy is a set of three",
      (element) => {
        const range1 = element.ownerDocument.createRange();
        const text1 = element.firstChild;
        const text2 = element.firstElementChild.firstChild;
        range1.setStart(text1, 10);
        range1.setEnd(text2, 20);
        const selection = element.ownerDocument.defaultView.getSelection();
        selection.removeAllRanges();
        selection.addRange(range1);
      }
    );
  }
  
  --------------
  
![image](https://user-images.githubusercontent.com/78478421/110767691-32c1d580-825f-11eb-92b6-6e8bee5f115a.png)

that's the error I get. please note that the selector is fine. I am using it in the method I tried with the mouse. also, note what I said about the earlier solution (can't select some words, only complete text of element).

**Comment by yury-s** [comment]
> that's the error I get. please note that the selector is fine. I am using it in the method I tried with the mouse. also, note what I said about the earlier solution (can't select some words, only complete text of element).

You need to adjust the code from my example above to fit this particular DOM tree. The reason it fails is that the selector matches `<strong></element>` rather than its parent. You can change the selector to match different element and/or the way you get from the selected element to its sibling. E .g. if you change your snippet to this:

```js
await page.$eval("text=Bloom's taxonomy is a set of three", element => {
  const range1 = element.ownerDocument.createRange();
  const text1 = element.firstChild;
  const text2 = element.parentElement.lastChild;
  range1.setStart(text1, 10);
  range1.setEnd(text2, 20);
  const selection = element.ownerDocument.defaultView.getSelection();
  selection.removeAllRanges();
  selection.addRange(range1);
});
```
It will select the following range:
![image](https://user-images.githubusercontent.com/9798949/110855351-1035b980-826b-11eb-8748-f1470f41d77e.png)

**Comment by amit-parizian-erudite** [comment]
your'e right, now it works, thank you so much! you have been a great help!
just a little last question, sometimes my ```<p>``` element has several children. can I reach all of them by something like ```firstChild``` or ```lastChild``` or it's only those two?

**Comment by yury-s** [comment]
You can use [nextSibling](https://developer.mozilla.org/en-US/docs/Web/API/Node/nextSibling) or even [chilsNodes](https://developer.mozilla.org/en-US/docs/Web/API/Node/childNodes) to traverse other children. Look at DOM documentation there is a plenty of methods to get from one node to another.

**Comment by amit-parizian-erudite** [comment]
Thank you so much!
