### ISSUE TITLE
[Question] What's the best way to wait for the document.title?

### ISSUE THREAD

**Issue by qmmr** [microsoft/playwright#5715]
Hey all 👋 
In my React app, I'm using hook '@rehooks/document-title' to update the `document.title`.
In my e2e tests I had to use `await page.waitForTimeout(1000)` because when I check for the title, it's the title before it gets updated via the hook. Is there a way to wait for the `document.title` to be as expected?

```js
test('render correct markup', async () => {
    await page.waitForTimeout(1000)

    expect(await page.title()).toBe('My updated title')
})
```

**Comment by pavelfeldman** [comment]
```js
page.waitForFunction(title => document.title === title, 'My title');
```

**Comment by yury-s** [comment]
Closing for now, feel free to reopen if the response above doesn't work for you.
