### ISSUE TITLE
[Feature] make scroll into view optional for page.click()

### ISSUE THREAD

**Issue by Nilsty** [microsoft/playwright#5716]
**Problem statement:**
I have a dropdown menu where the bottom part is cut off. The elements which are cut off are still clickable as page.click() will scroll them into view. But I would like to make sure that all elements of the dropdown are fully visible without scrolling.

**Proposed solution**
My proposed solution would be to make the scrolling into view optional for page.click() as an option. E.g. scroll=false

**Additional context**
![image](https://user-images.githubusercontent.com/23235511/109990291-8b4a1d80-7d09-11eb-8e12-8f0bed3973ad.png)

This issue seems somewhat related to #5700

**Comment by pavelfeldman** [comment]
To make sure I understand, you would want to say
```js
await page.click('text=Rename draft', { scroll: false });
````

It will click the center of the visible portion, so it'll work in this case. What signal would it give to you? Or are you worried about other elements that are not visible altogether? Or does your menu have overflow: auto? Trying to make sense of this!

**Comment by Nilsty** [comment]
Thanks for your question @pavelfeldman 
There are more elements in this dropdown. This is how it looks when it's not cut off:
![image](https://user-images.githubusercontent.com/23235511/110088233-e2e19b00-7d94-11eb-9fb7-44fa5d14045f.png)
So, my idea would be to check if the last element in this dropdown is clickable without scrolling by doing something like this:
```
await page.click('(//li)[last()]', { scroll: false });
```
![image](https://user-images.githubusercontent.com/23235511/110089464-723b7e00-7d96-11eb-826f-f5bc83c4ce0e.png)

**Comment by pavelfeldman** [comment]
It looks like you don't care whether user is able to click it for real, you just want to trigger it, is that right? In that case you can just 

```js
await page.dispatchEvent('(//li)[last()]', 'click')
```
that's just trigger it programmatically.

Playwright's way of clicking is 'tapping on the glass', i.e. as if user clicked it using pointer controller or finger tap. So if we don't scroll, we can't click...

**Comment by Nilsty** [comment]
`await page.dispatchEvent('(//li)[last()]', 'click')`
is still scrolling the element into view. It would be great to have a way to suppress that scrolling behavior.

**Comment by yury-s** [comment]
Could it be that one of the the click handlers in the page performs scrolling? If you try the following snippet it will dispatch 'click' without scrolling (while `page.click` would scroll), something is different in your page:
```js
  await page.goto('https://github.com/microsoft/playwright/issues/5716');
  await page.dispatchEvent('text=is still scrolling the element', 'click');
```

**Comment by aslushnikov** [comment]
> `await page.dispatchEvent('(//li)[last()]', 'click')` is still scrolling the element into view.

@Nilsty Similarly to Yury, I don't see this happening anywhere in our code as well. I'll close this for now since it does look like `dispatchEvent` solves the usecase here. If you believe that it doesn't, or if `dispatchEvent` somehow scrolls element for you - please re-submit with a repro steps so that we can debug locally!

**Comment by icdt-qsheridan** [comment]
await page.click('(//li)[last()]', { scroll: false }); works, but it would be nice if it were mentioned in the official documentation.  Lost a lot of time on this. 

![image](https://user-images.githubusercontent.com/75633337/164506307-f661bfd3-ebb2-4b89-94c6-5dd7af6084c6.png)
