### ISSUE TITLE
chore: firefox crashes upstream + keyboard shortcuts changed

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#5721]
The new roll [fails 2 tests](https://github.com/microsoft/playwright/runs/2021159243) on mac:

- [`capabilities.spec.ts - should play video`](https://github.com/microsoft/playwright/blob/8ffcbb380861e64174f670c957619d567a4b2baa/test/capabilities.spec.ts#L54-L71) crashes. This is due to [upstream regression](https://bugzilla.mozilla.org/show_bug.cgi?id=1693011) that is filed as P1. With this regression, current tip-of-tree firefox headless (Mozilla Firefox 88.0a1) is crashing when trying to play videos, e.g. loading our video test asset:

    ```sh
    $ # the following crashes
    $ /Applications/Firefox\ Nightly.app/Contents/MacOS/firefox --headless file:///Users/aslushnikov/prog/playwright/test/assets/video.html
    $ # hotfix - MOZ_WEBRENDER=0
    $ MOZ_WEBRENDER=0 /Applications/Firefox\ Nightly.app/Contents/MacOS/firefox --headless file:///Users/aslushnikov/prog/playwright/test/assets/video.html
    ```
- [`page-keyboard.spec.ts - should support MacOS shortcuts`](https://github.com/microsoft/playwright/blob/e56f56c11e60636011a2d2861d30d6afdff39331/test/page-keyboard.spec.ts#L345-L355) - fails. This is due to upstream changes to the native shortcut resolving - https://phabricator.services.mozilla.com/D102877 The new logic hardcodes the "default layout" for Mac, and it looks like the obscure shortcut we use in tests is not part of this hardcoded list. We discussed this with Joel and decided to disable the test for now and let him decide later what to do with it.

**Comment by aslushnikov** [comment]
For the record: we tried rolling onto it and failed on mac: https://github.com/microsoft/playwright/runs/2021159243

**Comment by aslushnikov** [comment]
Upstream crash bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1697004

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
