### ISSUE TITLE
[REGRESSION]: elem screenshot (sticky elements outside elem are overlapping)

### ISSUE THREAD

**Issue by hampsterx** [microsoft/playwright#5725]
**Context:**

Was working prior in 1.7. Now not working in 1.9.1

Operating System: Linux, python playwright

**Describe the bug**

```
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>

    <div class="m-5 p-5 bg-red-400" style="display:block; position:sticky; top:25px;">
        sticky header
    </div>
    <div id="content" class="m-5 p-5 bg-green-400">
        <p>test</p>
        <p>test</p>
        <p>test</p>
        <p>test</p>
        <p>test</p>
    </div>
</body>
</html>
```

![screenshot_playwrite_test](https://user-images.githubusercontent.com/1887721/110054493-11c13680-7dc0-11eb-9afc-b5031c04e922.png)

pip freeze | grep play
playwright==0.171.1

```
    page.goto("http://localhost:8000/test.html")

    elem = page.querySelector("#content")
    elem.screenshot(path="test_171.png")
```    

![test_171](https://user-images.githubusercontent.com/1887721/110054593-3e754e00-7dc0-11eb-9b3a-945c823d079f.png)

Now with 

pip freeze | grep play
playwright==1.9.1
 

```
    page.goto("http://localhost:8000/test.html")

    elem = page.query_selector("#content")
    elem.screenshot(path="test.png")
```

![test_191](https://user-images.githubusercontent.com/1887721/110054806-a75cc600-7dc0-11eb-8693-db0f09cb20ca.png)

Obviously I am only wanting to clip the element, not anything positioned over it.

**Comment by dgozman** [comment]
I bisected this down to https://github.com/microsoft/playwright/pull/5434. Most likely upstream Chromium CL https://chromium-review.googlesource.com/c/chromium/src/+/2643792 is a culprit.

More details: to capture this particular element, we set viewport override to the element's bounding box, and new Chromium behavior is to reposition sticky header according to the new viewport. That seems like a logical move in Chromium, but produces unexpected result for this screenshot.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by djanowski** [comment]
Has this been resolved? We're still dealing with these screenshot issues.
