### ISSUE TITLE
[Question] Is there a way to access the payload for a PUT request method?

### ISSUE THREAD

**Issue by resaldiv** [microsoft/playwright#5735]
Hi!

I'm writing a playwright test that intercepts a PUT request and I want to verify that the request payload contains the expected data. I've tried to access the payload like this:

```
let payload;
let saveCalled = false;

page.on("request", (request) => {
  if (request.url() === requestUrl && request.method() === "PUT") {
    payload = request.postDataJSON();
    saveCalled = true;
  }
});

/*****
*
* Trigger save call
*
*/

expect(saveCalled).toBeTruthy();
expect(payload).not.toBeNull(); // test fails
```

Even though it enters the if condition and I see the payload in the browser, the postDataJSON() returns null.

I believe that postData() and postDataJSON() only works for POST methods. If that's true, is there a way I can access the request payload for a PUT request method and what would be the right approach to do it?

Thank you.

**Comment by pavelfeldman** [comment]
What about `request.postDataBuffer()`? It could be that your request does not set the `content-type` request header and Playwright can't know it is JSON.

**Comment by resaldiv** [comment]
Thank you for your answer Pavel. I tried using `request.postDataBuffer()` and it returns null. I wonder if it has anything to do that the request method is PUT?

Also, thank you for the solution. I will try this when it gets merged.

**Comment by pavelfeldman** [comment]
Looks like not yet addressed. PUT should not matter, adding a test for it.

**Comment by pavelfeldman** [comment]
Could you share more about your use case? I added a test for PUT specifically and it passed. I wonder if there is something special about your setup. Could you print request headers?

**Comment by resaldiv** [comment]
Thanks for adding a PUT test. I want to validate that the Azure Storage SDKs are being called correctly from our app using PUT requests. In order to do it, I'm trying to intercept and test this call: https://docs.microsoft.com/en-us/rest/api/storageservices/put-range

**Comment by avodovnik** [comment]
@resaldiv Feel free to reopen this issue if the problem is still there, providing some sample code for us to figure out how to go about reproducing it.

**Comment by misharosa** [comment]
Is there some progress in fixing that problem? @BarrBozzO

**Comment by pishiko** [comment]
In my case I am using PUT multipart/form-data for file updates, which is deprecated, so I found it impossible to get form-data with playwright's API.

**Comment by MarcRosewarne** [comment]
Found this thread looking into the same/simular issue, Not sure if useful but I found this worked.

```
page.waitForResponse(
      (response) =>
        response.url().includes(endpointUrl) &&
        response.status() === 204 &&
        response.request().method() === "PUT" &&
        response.request().postData().includes(item),
    )
```


`endpointUrl` & `item` are variables and this code is wrapped in a Promise.all with the button click.
I am not accessing the data, but at least I can assert that the post data contains what I am checking for.
