### ISSUE TITLE
How to get response from XHR while clicking a button

### ISSUE THREAD

**Issue by 77staz** [microsoft/playwright#5750]
Hey, I have been stuck on this for hours and I cant seem to figure out how to intercept the XHR request when the button is clicked. Current code look likes this:

```
await page.goto( "https://example.com", {
    waitUntil: "load",
    timeout: 0
});

console.log("Page Loaded");

await Promise.all([
    page.click('button[type="button]'),
    page.waitForNavigation({
        waitUntil: 'networkidle0'
    }),
]);

```
When the button is pressed on the main website, it sends an XHR request and gives the response in json. When I run this, it gives the time limit 3000s... error but the button works and the XHR req is completed. I only want the json response, not the html or anything. Please help, thank you.

**Comment by mxschmitt** [comment]
Something like that should work for that use-case, then you can interact with the response object:
```js
// @ts-check
const playwright = require('playwright');

(async () => {
  const browser = await playwright.chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  // Creating a dummy page with click to network request interaction
  await page.goto('http://worldtimeapi.org/');
  await page.setContent(`
      <button onclick="fetch('http://worldtimeapi.org/api/timezone')">click me</button>
    `)

  const [response] = await Promise.all([
    page.waitForResponse("**/*"), // <-- there you can specify the pattern of the URL more precise
    page.click("text=click me") // important that the waitForResponse happens first in the Promise.all statement, otherwise the request can already be done once the click happened. (so it waits for a request and then clicks)
  ])
  console.log(response.url(), await response.json())

  await browser.close();
})();
```
Does this fit for your use-case?

[`waitForNavigation`](https://playwright.dev/docs/api/class-page/#pagewaitfornavigationoptions) is used when the URL of the page was changed.

**Comment by 77staz** [comment]
> Something like that should work for that use-case, then you can interact with the response object:
> 
> ```js
> // @ts-check
> const playwright = require('playwright');
> 
> (async () => {
>   const browser = await playwright.chromium.launch();
>   const context = await browser.newContext();
>   const page = await context.newPage();
>   // Creating a dummy page with click to network request interaction
>   await page.goto('http://worldtimeapi.org/');
>   await page.setContent(`
>       <button onclick="fetch('http://worldtimeapi.org/api/timezone')">click me</button>
>     `)
> 
>   const [response] = await Promise.all([
>     page.waitForResponse("**/*"), // <-- there you can specify the pattern of the URL more precise. In this case it matches every pattern.
>     page.click("text=click me") // important that the waitForResponse happens first in the Promise.all statement, otherwise the request can already be done once the click happened. (so it waits for a request and then clicks)
>   ])
>   console.log(response.url(), await response.json())
> 
>   await browser.close();
> })();
> ```
> 
> Does this fit for your use-case?
> 
> [`waitForNavigation`](https://playwright.dev/docs/api/class-page/#pagewaitfornavigationoptions) is used when the URL of the page was changed.

Oh my god man you are a saviour. Thanks alot
