### ISSUE TITLE
CURLOPT_INTERFACE alternative in Playwright browser?

### ISSUE THREAD

**Issue by 74staz** [microsoft/playwright#5752]
Hey, I can see that we can use proxies with username & password in the browser but cant seem to find a function which runs with the same server IP. Would be great if someone can guide me, thanks.

**Comment by pavelfeldman** [comment]
What do you mean a function that runs with the same server IP? https://playwright.dev/docs/network#http-proxy - our proxy docs.

**Comment by 74staz** [comment]
> What do you mean a function that runs with the same server IP? https://playwright.dev/docs/network#http-proxy - our proxy docs.

Yes already read the proxy docs but what I am talking about is different. i-e I have this x.x.x.xx as my main server IP and I own another secondary IP address (x.x.xx2) in the same server and when I use `(CURLOPT_INTERFACE, x.x.xx2)` in the request in php, the request websites get the request from x.x.xx2.

**Comment by yury-s** [comment]
If you want to change IP address the request is sent from you can do it in the proxy that you specify. Playwright doesn't have API for changing source IP. It should be possible to achieve by configuring your system network to use certain network interface for particular destination addresses but this is outside of Playwright scope.

**Comment by yury-s** [comment]
Closing for now, feel free to reopen if there is anything we can help with.
