### ISSUE TITLE
[Question] browserType.launch: Host system is missing dependencies!

### ISSUE THREAD

**Issue by 74staz** [microsoft/playwright#5759]
I am on centOS 6 and used playwright browser 5 months ago and it worked but now it keeps giving me this error. I downgraded my node version to 10.0.0 because I was getting `/lib64/libc.so.6: version GLIBC_2.14 not found` error before.
```
browserType.launch: Host system is missing dependencies!

  Install missing packages with:
      sudo apt-get install gstreamer1.0-libav

  Missing libraries we didn't find packages for:
      libsoup-2.4.so.1
      libgtk-3.so.0
      libgdk-3.so.0
      libGL.so.1
      libEGL.so.1
      libnotify.so.4
      libvpx.so.6
      libopus.so.0
      libharfbuzz.so.0
      libwoff2dec.so.1.0.2
      libharfbuzz-icu.so.0
      libgcrypt.so.20
      libgstapp-1.0.so.0
      libgstbase-1.0.so.0
      libgstreamer-1.0.so.0
      libgstpbutils-1.0.so.0
      libgstaudio-1.0.so.0
      libgsttag-1.0.so.0
      libgstvideo-1.0.so.0
      libgstgl-1.0.so.0
      libgstcodecparsers-1.0.so.0
      libgstfft-1.0.so.0
      libjpeg.so.8
      libpng16.so.16
      libopenjp2.so.7
      libwebpdemux.so.2
      libwebp.so.6
      libenchant.so.1
      libsecret-1.so.0
      libtasn1.so.6
      libhyphen.so.0
      libwayland-server.so.0
      libwayland-egl.so.1
      libwayland-client.so.0
      libicui18n.so.66
      libicuuc.so.66
      libsystemd.so.0
      libxkbcommon.so.0
      libepoxy.so.0
      libatk-bridge-2.0.so.0
      libGLESv2.so.2

```
I tried yum install -y gstreamer1.0-libav and it says this package is not available??

**Comment by yury-s** [comment]
These instructions are for Ubuntu distro, officially support Ubuntu 18.04 and 20.04 and run tests for them. CentOS is not among officially supported linux distribution in Playwright. Running on CentOS will likely require dedicated browser builds for that platform, we are not planning to work on that, but if somebody wants to contribute PRs are very welcome.

**Comment by 74staz** [comment]
Playwright browser was working just fine for me like 4-5 months ago. This just suddenly happened and now I cant run my code.

**Comment by machineghost** [comment]
I'm getting this issue on Linux Mint (ie. a Debian/Ubuntu-based Linux).
