### ISSUE TITLE
[BUG] iframe inside an iframe is not visible

### ISSUE THREAD

**Issue by odeliat** [microsoft/playwright#5762]
**Context:**
Playwright Version: [1.7.1]
Operating System: [Mac]
Node.js version: [12, 14.9.0]
Browser: [Chromium, Firefox]

**System:**
OS: macOS 11.1 + windows 10
Memory: 1.25 GB / 32.00 GB

**Binaries:**
Node: 14.9.0 - /usr/local/bin/node
Yarn: 1.22.5 - /usr/local/bin/yarn
npm: 6.14.7 - /usr/local/bin/npm

**Languages:**
Bash: 3.2.57 - /bin/bash

**npmPackages:**
playwright: ^1.7.1 => 1.7.1

**Describe the bug**
I have a website with a iframe inside iframe.
On chrome, When I go to this iframe I can see the inner iframe.
When I'm running a test with playwright on this website, the inner iframe is blank. (when I open dev-tools, it's suddenly appears)

my test config:
```
browser = await chromium.launch({headless: isHeadless, args: ["--start-maximized"]});
page = await browser.newPage(
      {
           viewport: isHeadless ? {
           width: 1920,
           height: 1080
      } : null
   }
);
```
**Steps to reproduce:**
[https://github.com/microsoft/playwright/issues/5313#issuecomment-789673448](https://github.com/microsoft/playwright/issues/5313#issuecomment-789673448)

Do you have any ideas on how to solve this?

**Comment by yury-s** [comment]
I followed the steps from the comment you pointed at and the `#webview` and `#avtive-frame` iframes are both populated. Could you share playwright script that doesn't work?

**Comment by odeliat** [comment]
@yury-s 
Did you follow the steps with the chromium that lunched from the playwright script?
The playwright script is what I put on the description:
```
browser = await chromium.launch({headless: isHeadless, args: ["--start-maximized"]});
page = await browser.newPage(
      {
           viewport: isHeadless ? {
           width: 1920,
           height: 1080
      } : null
   }
);
```

**Comment by yury-s** [comment]
> @yury-s
> Did you follow the steps with the chromium that lunched from the playwright script?

Yes, this is what I got:

![image](https://user-images.githubusercontent.com/9798949/111009867-99232280-8349-11eb-99a2-13993fa0bd63.png)

**Comment by odeliat** [comment]
Hi @yury-s, This is what I get when I follow the steps:
![Screenshot 2021-03-16 095032](https://user-images.githubusercontent.com/14539932/111273932-0fbb6b00-863d-11eb-98f6-ea1c11254bfc.jpg)

What am I doing wrong?

**Comment by pavelfeldman** [comment]
Sorry, we need more information and a minimal reproduction to fix the issue. If it still persists, could you re-file it? I can see that you are using Browser preview extension. I'm not sure how it works in the remote workflow, so it might be that it simply isn't capable of working in this setup? In either case, please re-file with a smaller repro.
