### ISSUE TITLE
[Question] Firefox Error: NS_BINDING_ABORTED [Question]

### ISSUE THREAD

**Issue by ychaudhari** [microsoft/playwright#5775]
I intermittently get following error (specially on firefox)
 Error: [JavaScript Error: "NS_BINDING_ABORTED: " {file: "https://www.google.com/recaptcha/<remaining-url>" line: 1}]
@https://www.google.com/recaptcha/<remaining-url>:1:14

The application uses recaptcha but I have never seen this error on chromium.

Can someone help?

There is no helpful information/error in DEBUG=pw:api

**Comment by yury-s** [comment]
There is [a lot of places](http://ffsearch.azurewebsites.net/#search=NS_BINDING_ABORTED) in the Firefox network code where this error could be produced, it's hard to tell without a repro script what is going on. It could be that the loading is forcefully stopped for some reason.

**Comment by ychaudhari** [comment]
I'm not able to consistently reproduce this issue but it is definitely happening once in 7-8 executions. Recaptcha is implemented in the login page, so I'm thinking if this could be because of navigating too early?
Trying to figure out if this could be the issue with test script, playwright or the firefox

**Comment by ychaudhari** [comment]
Thanks yury-s
It's difficult to share the app code but I will reproduce by creating separate sample code.

**Comment by aslushnikov** [comment]
Looks like the discussion stalled here - so I'll close the issue. Please feel free to resubmit when there's a repro! ❤️
