### ISSUE TITLE
[BUG] Chromium: screenshot is created without scrollbars

### ISSUE THREAD

**Issue by DJ-Glock** [microsoft/playwright#5778]
**Context:**
- Playwright Version: playwright-chromium 1.9.2
- Operating System: Windows (also can be reproduced on a Linux, using PW docker image)
- Node.js version: 12.18.3
- Browser: Chromium
- Extra: can be reproduced with React based sites.

**Code Snippet**
Here you are a code sample that can reproduce the issue

```javascript
// @ts-check
const playwright = require("playwright-chromium");

(async () => {
  const browser = await playwright.chromium.launch({
    // Change it according your needs
    headless: true,
    slowMo: 100,
    args: [
      '--start-maximized',
      // '--window-size=1920,1080',
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--enable-logging',
    ]
  });
  const context = await browser.newContext({viewport:{width:1920,height:1080}});
  // const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/virtual-scrolling/', { timeout: 60000 });
  await page.waitForTimeout(3000);

  const demo = await page.waitForSelector('[class="embedded-demo"]');
  await demo.scrollIntoViewIfNeeded();

  await page.screenshot({ path: './screenshots/test.png' });

  await browser.close();
})();
```

**Describe the bug**
When PW takes a screenshot of React based grid, scrollbars disappeared.

What you see in your browser:
![image](https://user-images.githubusercontent.com/26511191/110603673-5110ce00-8198-11eb-8bcb-05a7c4445a75.png)

What you can see on PW screenshot of the page:
![image](https://user-images.githubusercontent.com/26511191/110603747-638b0780-8198-11eb-8b1f-a3451aa6bae0.png)

**Comment by yury-s** [comment]
This is specific to headless mode where playwright [hides scrollbars](https://github.com/microsoft/playwright/blob/7706e5a24abd1aefed019b11c320f9fee74dbdb4/src/server/chromium/chromium.ts#L131) by default. You can override this behavior by changing your launch code like this:

```js
const browser = await playwright.chromium.launch({
  ignoreDefaultArgs: [
    '--hide-scrollbars'
  ],
  // other options
});
```

**Comment by nickofthyme** [comment]
Alternatively, this can be set in the playwright config...

```ts
// playwright.config.ts
import { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  use: {
    headless: true,
    launchOptions: {
      ignoreDefaultArgs: ['--hide-scrollbars'],
    },
  },
  projects: [
    {
      name: 'chrome',
      use: {
        browserName: 'chromium',
        launchOptions: {
          ignoreDefaultArgs: false, // overrides top-level `use` value
        },
      },
    },
  ],
};
export default config;
```
