### ISSUE TITLE
[Question]/[Feature Request] Taking a screenshot of the element without shadow

### ISSUE THREAD

**Issue by DJ-Glock** [microsoft/playwright#5779]
I have an issue with creating a screenshot of the element. The element has a shadow and when PW creates a screenshot, it takes it with a shadow. The issue here is that shadow is translucent and data behind the shadow can be different from run to run (it's okay). I use such screenshots for screenshots comparison - checking that test screenshot is equal (with some precision) to reference screenshot. But because of data behind the shadow it's not always true. Is there any way to take screenshot of the element without shadow? If there is no way, can it become a feature request?

Adding a couple of pics for better understanding.
![image](https://user-images.githubusercontent.com/26511191/110604665-60444b80-8199-11eb-88e8-8da41bf2214f.png)

![image](https://user-images.githubusercontent.com/26511191/110604684-64706900-8199-11eb-8492-0d2cf5f8e895.png)

As a workaround I change shadow to completely black before taking a screenshot. And it works. I also tried to set boxShadow = 'none', but it did not help.

```
await element.evaluate(e => {
        e.style.boxShadow =
          '0px 2px 4px -1px rgb(0 0 0), 0px 4px 5px 0px rgb(0 0 0), 0px 1px 10px 0px rgb(0 0 0)';
      });
```

**Comment by yury-s** [comment]
Are you taking screenshot using `ElementHandle.screenshot` or `Page.screenshot`? I tried the following
```
await page.setContent('<div style="box-shadow: 10px 5px 5px red; max-width:100px">Text</div>');
const div = await page.$('div');
await div.screenshot({path: 's.png'});
```
And it doesn't include the shadow. Adding round corners (`border-radius: 4px;`) paints a part of the element in the shadow color but I still don't see the shadow outside the borders.

**Comment by DJ-Glock** [comment]
Hey @yury-s,
I use ElementHandle.screenshot. I played with HTML code and it looks very interesting. I was able to create a minimum code sample to reproduce the issue:

```
// @ts-check
const playwright = require("playwright-chromium");

(async () => {
  const browser = await playwright.chromium.launch({
    // Change it according your needs
    headless: true,
    slowMo: 100,
    args: [
      '--start-maximized',
      // '--window-size=1920,1080',
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--enable-logging',
    ]
  });
  const context = await browser.newContext({viewport:{width:1920,height:1080}});
  // const context = await browser.newContext();
  const page = await context.newPage();
  await page.setContent(`<div class="MuiPaper-root sc-jcRDWI kPwfsx MuiPaper-elevation4 MuiPaper-rounded" data-test-id="compact-view">
	<div data-test-id="compact-view-header" class="sc-iuGMqu fzqxIX">
		<div class="sc-gfHAkt eMijpD">
			<div data-test-id="sec-type" class="sc-ezront fmBQoE">
				<div class="sc-jfJzZe cCqKgO">
					<img src="/static/media/EQTY.90bcffe3.png" alt="EQTY">
						<span data-test-id="sec-type-value">EQTY</span>
					</div>
				</div>
			</div>
			<div data-test-id="issuer" class="sc-irOQnY bhfAri">3M Co</div>
			<div data-test-id="sec-name">
				<span class="sc-gJrzqj dEQKoj">
					<span>3M CO</span>
				</span>
			</div>
			<div class="jss35" data-test-id="symbol">2595708</div>
			<div data-test-id="payment-info" class="sc-eJBYSJ kxwMyr">
				<div data-test-id="country-name" class="sc-fFYUoA FCJNq">United States</div>
				<div class="sc-eUWgFQ SpAPz">
					<span data-test-id="currency" class="sc-hlWvWH dgxEoC">USD</span>
				</div>
			</div>
			<div class="sc-hxqDJO kUOQaz">
				<div>
					<div data-test-id="cusip" class="sc-gATInX eAZrlv">
						<span>Cusip</span>
						<strong>88579Y101</strong>
					</div>
					<div data-test-id="sedol" class="sc-gATInX eAZrlv">
						<span>Sedol</span>
						<strong>2595708</strong>
					</div>
					<div data-test-id="isin" class="sc-gATInX eAZrlv">
						<span>Isin</span>
						<strong>US88579Y1010</strong>
					</div>
				</div>
			</div>
		</div>
	</div>`);
  const element = await page.$('[data-test-id="compact-view"]');
  await element.evaluate(e => {
    e.style.boxShadow =
      '0px 2px 4px -1px rgb(0 0 0), 0px 4px 5px 0px rgb(0 0 0), 0px 1px 10px 0px rgb(0 0 0)';
  });
  
  await element.screenshot({path: './screenshots/s.png'});
  await page.screenshot({ path: './screenshots/test.png' });

  await browser.close();
})();
```

Once run you should get two screenshots. Full page screenshot:
![image](https://user-images.githubusercontent.com/26511191/110764742-7b2fc200-8264-11eb-8720-ff937cdf1c09.png)

And element screenshot:
![image](https://user-images.githubusercontent.com/26511191/110765041-d06bd380-8264-11eb-92ed-5be2f2bf628a.png)

But! If I use your sample or truncate my element, for example like this:
```
  await page.setContent(`<div class="MuiPaper-root sc-jcRDWI kPwfsx MuiPaper-elevation4 MuiPaper-rounded" data-test-id="compact-view">
	<div data-test-id="compact-view-header" class="sc-iuGMqu fzqxIX">
		<div class="sc-gfHAkt eMijpD">
			<div data-test-id="sec-type" class="sc-ezront fmBQoE">
				<div class="sc-jfJzZe cCqKgO">
					<img src="/static/media/EQTY.90bcffe3.png" alt="EQTY">
						<span data-test-id="sec-type-value">EQTY</span>
					</div>
				</div>
			</div>
			<div data-test-id="issuer" class="sc-irOQnY bhfAri">3M Co</div>
			<div data-test-id="sec-name">
				<span class="sc-gJrzqj dEQKoj">
					<span>3M CO</span>
				</span>
			</div>
			<div class="jss35" data-test-id="symbol">2595708</div>
			<div data-test-id="payment-info" class="sc-eJBYSJ kxwMyr">
				<div data-test-id="country-name" class="sc-fFYUoA FCJNq">United States</div>
				<div class="sc-eUWgFQ SpAPz">
					<span data-test-id="currency" class="sc-hlWvWH dgxEoC">USD</span>
				</div>
			</div>
		</div>
	</div>`);
  const element = await page.$('[data-test-id="compact-view"]');
  await element.evaluate(e => {
    e.style.boxShadow =
      '0px 2px 4px -1px rgb(0 0 0), 0px 4px 5px 0px rgb(0 0 0), 0px 1px 10px 0px rgb(0 0 0)';
  });
```
I will get a screenshot without shadow.
Page screenshot:
![image](https://user-images.githubusercontent.com/26511191/110765164-f6917380-8264-11eb-81aa-6d9867beb01c.png)

Element screenshot:
![image](https://user-images.githubusercontent.com/26511191/110765215-04df8f80-8265-11eb-9cb3-d8d4c5bd798a.png)

It looks like `<strong>text</strong>` affects taking screenshot procedure.

**Comment by DJ-Glock** [comment]
But today I am not able to reproduce on the same Windows machine, with Docker image and on MacOS. I need some time to think. :-/

**Comment by yury-s** [comment]
> UPDATE: Please note that I was able to reproduce it on Windows 10, but on Mac OS Big Sur it looks fine. Will check with Docker once again.

This is all in Chromium, right?

**Comment by DJ-Glock** [comment]
@yury-s correct

**Comment by pavelfeldman** [comment]
I can't repro this on Ubuntu 20.04. Could you paste exact system set up where this happens?

**Comment by DJ-Glock** [comment]
I have attached you zip file with sample project. Please run it in docker, it should reproduce the issue.
You should see something like this:
![image](https://user-images.githubusercontent.com/26511191/112903851-c06f4300-90f0-11eb-85ad-e379edaa52cb.png)

Sample project:
[playwright.zip](https://github.com/microsoft/playwright/files/6224737/playwright.zip)

Just run the following command:
`docker-compose up --build --abort-on-container-exit pw_sample
`

**Comment by pavelfeldman** [comment]
The zip file that you provided there is no shadow, but I can see the right border, is that what you are referring to?

![element](https://user-images.githubusercontent.com/883973/113020857-dc4a0780-9137-11eb-99c1-f38c858b7585.png)

The border is due to the fractional coordinates of the div:

<img width="184" alt="Screen Shot 2021-03-30 at 9 28 42 AM" src="https://user-images.githubusercontent.com/883973/113023355-61362080-913a-11eb-9a36-d916fa081df0.png">

width is fractional and we are rounding it up in order to not miss any user data.

**Comment by pavelfeldman** [comment]
So I think the request stands, but it isn't obvious what we can do about it.

**Comment by pavelfeldman** [comment]
I was referring to the zip file that you attached, it did not have shadow, just a 1px border on the right, the one from this post: https://github.com/microsoft/playwright/issues/5779#issuecomment-809734560

**Comment by pavelfeldman** [comment]
@DJ-Glock: You specify shadow, we clip it so it was not visible, but 1 pixel leaks due to the fractional coordinates. It is unclear where you are seeing the shadow in your zip file...

**Comment by DJ-Glock** [comment]
Okay Pavel, thanks for you time and clarification. Probably this is the root cause and not a PW or chromium issue.
