### ISSUE TITLE
[Question]WebKit version

### ISSUE THREAD

**Issue by dave-hart** [microsoft/playwright#5795]
Hi,

How do I link back the WebKit version packaged with playwright to that used in my Safari browser?

I am finding lots of different representations of WebKit versions when I attempt to figure this out
Playwright Specify 14.2 on their Readme
The about box on my stock Safari install states 610.4.3.1.4
The Downloads page on the WebKit site just has a 5 digit number

In order for WebKit to be a viable replacement for Safari and WebDriver, I need to be able to identify exactly what I am testing against. This came about as I am seeing bugs in my local stock Safari install, that do not appear in tests against WebKit. I suspect it's a versioning issue, but without being able to see versions I cannot say for sure.

Many thanks

**Comment by yury-s** [comment]
The version listed in our README.md corresponds to the 'Version/<x.y.z>" part in the user agent string (and displayed in about safari dialog):
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) **Version/14.0.2** Safari/605.1.15"

14.2 corresponds to [the version](https://webkit.org/blog/11555/release-notes-for-safari-technology-preview-121/) currently used in [Safari Technology Preview](https://developer.apple.com/safari/technology-preview/). There might be some slight differences between the private build of webkit and playwright build which includes only the open-source part. Also webkit revision which is used in playwright may be a bit ahead of the version used in the technology preview (e.g. 1.9.2 is based on [274075](https://trac.webkit.org/changeset/274075) while Safari Tech Preview 121 uses [272845](https://trac.webkit.org/changeset/272845)).

**Comment by dave-hart** [comment]
@yury-s Thank you for your answer. 

How is browser versioning managed in Playwright? Do we get a particular version of all three browsers at the time we fetch Playwright from npm, or does Playwright dynamically fetch newer versions at runtime?

**Comment by dave-hart** [comment]
@yury-s 

In fact, I have just updated to Playwright 1.9.2 (having cleaned my cache directory and node modules) and typing `navigator.userAgent` into the web console of the playwright launched webkit, I get:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Safari/605.1.15`

**Version/13.0.4** doesn't seem to match anything else .... 
Stock Safari gives me **Version/14.0.3**
Safari Tech Preview (updated this morning): **Version/14.2**

Updating seems to have given me a much older WebKit version.

**Comment by pavelfeldman** [comment]
Release notes point to the exact versions of the browsers used: https://github.com/microsoft/playwright/releases

**Comment by yury-s** [comment]
> Do we get a particular version of all three browsers at the time we fetch Playwright from npm, or does Playwright dynamically fetch newer versions at runtime?

Each Plawright version comes with a fixed version of each browser, the browsers are downloaded when you run `npm install`.

**Comment by JGJP** [comment]
@yury-s
Is the answer here that to use older version of browsers you need to use older versions of Playwright? I don't think this works for any team that needs to support older versions of browsers (very common).

Another issue is that when using iPhone 8 from Playwright's devices it runs Safari 17.4, which is not even supported on the iPhone 8 device.
