### ISSUE TITLE
[Feature] Option to not remove unused browsers

### ISSUE THREAD

**Issue by kolodny** [microsoft/playwright#5797]
I have a global cache for all browsers that will run in different docker images and with different versions. Specifically, I have a /.cache directory that stores all the browsers I care about and I plan on pruning that as necessary.

Is it possible to introduce an ENV variable to opt out of the browser autocleanup?

TL;DR: ENV var to opt out of "Removing unused browser" install step

**Comment by yury-s** [comment]
This is certainly possible but since it'd introduce another installation flow we need to better understand if it's justified. Can you share a bit more details about your use case, do you want to mount some shared volume at ~/.cache and have all the browsers preinstalled there? What's the benefit of it compared to preinstalling required browsers into corresponding docker images (I'm assuming they will anyway have different playwright versions)?

**Comment by kolodny** [comment]
Sure! One of the steps we want to avoid is to have to build a docker image per CI build, right now we just mount the current directory as a volume (including node_modules) and run the tests there (on a docker-best image). Building a docker repo specific image would also require rerunning npm install in CI which is a pretty expensive step as well. The only reason we need a docker image is because we can't run open the browsers on the out of the box CI machines.

I also see this being useful if the user has something like `PLAYWRIGHT_BROWSERS_PATH=$HOME/pw-browsers` in their `.bashrc` like you have shown in https://playwright.dev/docs/1.7.0/installation. If someone were to do that then having two projects anywhere with two versions of playwright would break the other

**Comment by yury-s** [comment]
Thanks for explaining! You can make Playwright skip the browser download step altogether by setting [`PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1`](https://playwright.dev/docs/installation?_highlight=skip_#skip-browser-downloads), does it solve your problem?

> I also see this being useful if the user has something like `PLAYWRIGHT_BROWSERS_PATH=$HOME/pw-browsers` 

`PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` should be compatible with that too. Please let us know if it works for you.

**Comment by kolodny** [comment]
Not really since I do need to install the browser when necessary, I only don't want to to blast away other installations as well during that process.

In the case of someone using `PLAYWRIGHT_BROWSERS_PATH` as a global export variable, it would break competing installations. In our case we need it to install when we don't have the browser installed yet but there are many tests all using the same cache with different versions that we don't want to break or delete

**Comment by kolodny** [comment]
Wow, thanks!

**Comment by nottrobin** [comment]
Is there no way for it to use the same downloaded browser between two different runs?
