### ISSUE TITLE
[Question] Is there a way to emulate cmd+f functionality?

### ISSUE THREAD

**Issue by VikramTiwari** [microsoft/playwright#5804]
Goal: I am trying to find all `elementHandle`s in the page which match a text value. Essentially emulating "find in page" with text.

I have tried various suggested selectors but seems like I am missing something in how I am trying to approach this problem. Here's the code sample I am trying with comments on what I don't understand.

```js
const { chromium } = require("playwright");

(async () => {
	const browser = await chromium.launch();
	const page = await browser.newPage();
	await page.goto("http://playwright.dev/");

	// Q: Why aren't these 6? Is it because these elements are above fold.
	console.log(
		`\n\n Q: Why aren't these 6? Is it because these elements are above fold.`
	);
	console.log(
		`shortcut`,
		(await page.$$(`"Playwright"`)).length // 3
	);
	console.log(
		`text=`,
		(await page.$$(`text="Playwright"`)).length // 3
	);
	console.log(
		`:text-is`,
		(await page.$$(`:text-is("Playwright")`)).length // 3
	);

	// incorrect because of matchedNode + allParentNodes count
	console.log(`\n\n Incorrect because of matchedNode + allParentNodes count.`);
	console.log(
		`:has-text`,
		(await page.$$(`:has-text("Playwright")`)).length // 38
	);

	// Q: Why is following count 7? What is it matching?
	console.log(`\n\n Q: Why is following count 7? What is it matching?`);
	console.log(
		`:text`,
		(await page.$$(`:text("Playwright")`)).length // 7
	);
	console.log(
		`:text-matches`,
		(await page.$$(`:text-matches("Playwright")`)).length // 7
	);
	await browser.close();
})();

```

**Comment by mxschmitt** [comment]
I've tried to track it more down, seems like this is quite minimal which demonstrates the issue: https://try.playwright.tech/?s=osvbb76

**Comment by VikramTiwari** [comment]
@mxschmitt Good find! 👍 

With that known the correct query would be `await page.$$(`:text("Playwright"):visible`)`

Any ideas about why this `await page.$$(`text="Playwright"`)` returns only 3?

**Comment by mxschmitt** [comment]
Playwright does not perform auto-waiting for actionability checks when you are using e.g. `$$`. See here for more information: https://playwright.dev/docs/actionability

in your case you can loop e.g. over the ElementHandles which you get from $$ and check if they are visible by using the isVisible method. Example: https://try.playwright.tech/?s=ajjtoaj

**Comment by VikramTiwari** [comment]
Makes sense. I can work around that. Thanks Max!
