### ISSUE TITLE
[Question]how to use playwright cookies to bypass login

### ISSUE THREAD

**Issue by chaowenGUO** [microsoft/playwright#5809]
I need to use playwright to login a website, but the website is protected by google recaptcha v2. So I have to manual bypass google recaptcha v2 in the first time and get cookies for later login.

Here is the example working in selenium:
import selenium.webdriver, time
options = selenium.webdriver.ChromeOptions()
options.headless = True
options.add_argument('--disable-popup-blocking')
options.add_argument('--incognito')
options.add_argument('--no-first-run')
driver = selenium.webdriver.Chrome(options=options)
driver.get('http://www.ebesucher.com/surfbar/chaowenguo')
driver.add_cookie({'name':'device', 'value':'jc7VYKQxoMWrzY7095d3Ir'})
driver.get('http://www.ebesucher.com/surfbar/chaowenguo')
time.sleep(20)
driver.save_screenshot('good.png')
driver.close()

Now I want to do the same stuff in playwright:
import {chromium} from 'playwright-chromium'
const browser = await chromium.launch({executablePath:'/usr/bin/google-chrome', args:['--disable-gpu']}
const context = await browser.newContext({storageState:{cookies:[{name:'device', value:'jc7VYKQxoMWrzY7095d3Ir', domain:'www.ebesucher.com', path:'/'}]}})
const ebesucher = await browser.newPage()
await ebesucher.goto('http://www.ebesucher.com/surfbar/chaowenguo')
await new globalThis.Promise(_ => globalThis.setTimeout(_, 1000 * 20))
await ebesucher.screenshot({path:'good.png'})
await browser.close()
It is not working, the ouput of good,png in playwright is hang in the login page, do not go inside, maybe there is some misuderstanding of the playwright api. But I can not find any working example in the internet. So I ask for help here.

Thank you very much

**Comment by pavelfeldman** [comment]
https://playwright.dev/docs/auth isna good start!

**Comment by chaowenGUO** [comment]
Thank you. The example in https://playwright.dev/docs/auth is not quite working in my case. The example in https://playwright.dev/docs/auth use username and password to login a website and the use context.storageState to get cookies. I can not do that, I have to use a chrome browser to login and do the google recaptcha v2 challenge manually and then go to developer tools->application->storage->Cookies to copy useful cookies because all the google recaptcha v2 bypassers are suck.
I also go to https://playwright.dev/docs/api/class-browser#browsernewcontextoptions to check the api detail. The code I write in playwright is followed such api. Maybe there is something wrong because there is not example in the api. Any help?

**Comment by yury-s** [comment]
If you already have cookies that you want to use for authentication you can add them via [`browserContext.addCookies`](https://playwright.dev/docs/api/class-browsercontext?_highlight=addcookies#browsercontextaddcookiescookies) like this:

```js
  await context.addCookies([{
    name: 'username',
    value: 'John Doe',
    domain: 'www.example.com',
    path: '/',
    expires: -1,
    httpOnly: false,
    secure: false,
    sameSite: 'None',
  }]);
  const page = context.newPage();
  await page.goto('https://www.example.com');
```

The storage API that Pavel mentioned will do this(and more) automatically for you. You could launch the browser in the ui mode, do all the steps manually and then export browser's storage state via `await context.storageState();` instead of going to devtools.

**Comment by pavelfeldman** [comment]
https://playwright.dev/docs/cli#preserve-authenticated-state - this seems to exactly match your use case.

**Comment by avodovnik** [comment]
@chaowenGUO I'll close the issue for now, as it seems like the answers should give you a clear path forward. Feel free to reopen the issue if you need more help or have more questions!
