### ISSUE TITLE
[Feature] Inspector Recorder  Raw Mouse/Screenshot tools

### ISSUE THREAD

**Issue by BryonLewis** [microsoft/playwright#5816]
**Let us know what functionality you'd like to see in Playwright and what is your use case.**
Really looking for some more tools in the inspector to streamline some of the recording/debug mode processes as well as support for canvas/webGL interactions.  End goal is some sanity integration testing and during the process recording screenshots for documentation.
- Raw mouse input mode (move mouse followed by mousedown/mouseup).  This helpse immensely with canvas based elements
- Screenshots from recorder (fullscreen | selector based | rect based)

I imagine this is somewhere in the backlog already and I tried searching but didn't find anything.

I hope this doesn't go against any policy, but a video (yay github update) describes it much better:

https://user-images.githubusercontent.com/61746913/111014422-8ae8fc80-8371-11eb-93b9-a493c061619c.mp4

I kind of did that quickly and probably not in the right way regarding passing data between the browser and the inspector.

**Do you think others might benefit from this as well?**
Ease of creating automated actions I think will always be a benefit.

**Comment by pavelfeldman** [comment]
These look like great ideas. Would you be interested in giving it a try and landing it in our repo? That would require adding the tests as an overhead though.

**Comment by BryonLewis** [comment]
Sorry I've just been a bit busy for the past few days.  I can work on cleaning this up and providing tests.  It may take me a little while, because I want to make sure the info passing between the Inspector Recorder and the page doesn't seem too hacky.

I'll probably split it into two parts, one for raw mouse input and another for the screenshot capability.

**Comment by pavelfeldman** [comment]
Please file a new bug and link this one if you are still open to doing it! Closing all non-actionable bugs...

**Comment by letsgotomars** [comment]
Hey @BryonLewis our team is very interested in these features and agree they could be quite useful. Are you still planning on working these 2 Inspector improvements and if so do you have a timeframe or would like some assistance?

**Comment by mxschmitt** [comment]
We track it now in #6737

**Comment by BryonLewis** [comment]
Sorry, I've just been really busy with work so I haven't had time to work on this at all.  I'm likely going to be very busy for the next few months.
