### ISSUE TITLE
[Question] is it not possible to use no proxy with 'per-context' lauched instance?

### ISSUE THREAD

**Issue by Nisthar** [microsoft/playwright#5818]
is it not possible to use no proxy with 'per-context' lauched instance?

I am getting "Exception has occurred: Error: NS_ERROR_UNKNOWN_PROXY_HOST"

if i do
```js 
browser = await firefox.launch({
        headless: false,
        proxy: { server: "per-context" },
        timeout: 0,
      }); 
context = await browser.newContext();
```

**Comment by pavelfeldman** [comment]
It is not. But you can specify default proxy instead of the per-context string.

**Comment by Nisthar** [comment]
> It is not. But you can specify default proxy instead of the per-context string.

Yeah but i need to launch a new window everytime i don't use proxy. i would prefer to use/not use proxy inside the context.

**Comment by pavelfeldman** [comment]
Can you launch one browser with per-proxy and another browser w/o proxy and just keep them running? That way you only need to launch 2 browsers.

**Comment by Nisthar** [comment]
> Can you launch one browser with per-proxy and another browser w/o proxy and just keep them running? That way you only need to launch 2 browsers.

Its a workaround but it should work.
Thanks.
