### ISSUE TITLE
Does playwright support waiting for the element invisible?

### ISSUE THREAD

**Issue by SansLang** [microsoft/playwright#5822]
For example, the same as selenium, WebDriverWait(driver, timeout).until_not(EC.visibility_of_element_located((By.XPATH, locator)))

**Comment by pavelfeldman** [comment]
Sure, see https://playwright.dev/docs/api/class-page/#pagewaitforselectorselector-options. Pass hidden or detached state into it.

**Comment by SansLang** [comment]
okay

**Comment by yb172** [comment]
Looks like this has been updated to https://playwright.dev/docs/api/class-locator#locator-wait-for

**Comment by TomasHubelbauer** [comment]
Also https://playwright.dev/docs/api/class-page/#page-wait-for-selector-option-selector
