### ISSUE TITLE
[BUG] Firefox is too slow with going to page and getting content

### ISSUE THREAD

**Issue by hahyes** [microsoft/playwright#5839]
**Context:**
- Playwright Version: last release, from Nuget package: 0.192
- Operating System: Windows 10
- Node.js version: v12.18.3
- Browser: Firefox
- Extra: Used on .NET Core 3.1 and Visual Studio 2019

**Code Snippet**

```csharp
   //earlier is just standard initialization of Firefox browser, context and page from docs

   await page.GoToAsync("https://allegro.pl");

   string html = await page.GetContentAsync();
```

**Describe the bug**

Hi there,

I tried to use Firefox browser for loading page and getting whole HTML code. Problem is... this is slow. Incredibly slow.

These two lines take in my test from 17 to 25 seconds, measured with Stopwatch.
On Webkit it's between 4 and 6 seconds, depends on using or not VPN.

How is this possible? 

Version of browsers:

- Firefox: 86.0b10
- Webkit: 14.1

I didn't try downgrade of Playwright. I'm fine with using Webkit for now, but wanted to report that something is wrong with Firefox here.

**Comment by aslushnikov** [comment]
@hahyes is this a regression? Could you please try an older version, e.g. 0.180.0?  

> I'm fine with using Webkit for now, but wanted to report that something is wrong with Firefox here.

Thank you for the heads up! ❤️

**Comment by pavelfeldman** [comment]
We need more information to address this issue. Please file a new one with the response to above if this is still a case!
