### ISSUE TITLE
Electron support

### ISSUE THREAD

**Issue by akosyakov** [microsoft/playwright#584]
Hey, very cool that it supports WebKit and Firefox. Do you have plans to support Electron?

**Comment by corevo** [comment]
I'm assuming you can do it today the same way you would with puppeteer, by enabling the Chrome debugging protocol.

```js
const { app, BrowserWindow } = require('electron')
const puppeteer = require('puppeteer-core')

app.commandLine.appendSwitch('remote-debugging-port', '8315')
const electronBrowser = await puppeteer.connect({
    browserURL: 'http://localhost:8315',
  })
```

**Comment by JoelEinbinder** [comment]
Yes, it should be doable by manually hooking up the debugging protocol as corevo says. But I’d really like to have a nicer solution that just works out of the box.

There are some logistics to work out. Playwright needs to be compatible with the version of electron. Also the way we handle contexts might clash with how electron is implemented. But these both seem like problems that can be overcome.

**Comment by akosyakov** [comment]
puppeteer had some issues to support Electron: https://github.com/puppeteer/puppeteer/issues/4283 I was wondering whether it will be the same here.

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/647

**Comment by pavelfeldman** [comment]
@akosyakov: in case you are still interested...

https://www.npmjs.com/package/playwright-electron is now publicly available. It does not have docs, just a bare README.md, but it should be enough to get a rough idea about it. Please let us know what you think!

**Comment by akosyakov** [comment]
@pavelfeldman cool! thanks. Do I understand correctly that it works only against Electron 9?

**Comment by pavelfeldman** [comment]
Yes, Electron 9 at this point.

**Comment by aslushnikov** [comment]
An electron support is now available with [`playwright-electron`](https://www.npmjs.com/package/playwright-electron)! 🎉

**Comment by NanFengCheong** [comment]
@aslushnikov 
Hi,

Do you have example to launch from index.js and control the electron using playwright?

**Comment by sAbakumoff** [comment]
> Yes, it should be doable by manually hooking up the debugging protocol as corevo says. But I’d really like to have a nicer solution that just works out of the box.

My app is built with electron but it needs to load a certain page in the headless browser and read cookies. I don't want to run another headless browser because electron already has the debugger window. How exactly to "hook up" the debugging protocol?
