### ISSUE TITLE
Selenium grid alternative? 

### ISSUE THREAD

**Issue by muodov** [microsoft/playwright#585]
Are there any plans on supporting a multi-host infrastructure like selenium grid? 
I'm just curious on what the authors' opinion is. Do you consider this as part of this project, or do you think it needs to be separate (like selenium grid is separate from WebDriver)

**Comment by monkpit** [comment]
I am also interested in this - if I'm already using selenium grid, is there any reason for me to want to switch my code to playwright?

**Comment by CrispusDH** [comment]
You could take a look at much stronger alternative - [Selenoid](https://github.com/aerokube/selenoid)

**Comment by monkpit** [comment]
I already use [Zalenium](https://github.com/zalando/zalenium) as it fits my needs better than Selenoid - but that's not what I'm wondering about. More curious about using this package as a replacement for WebDriver itself.

**Comment by leorush** [comment]
Selenoid proxying CDP into container, so it's worth checking.

**Comment by CrispusDH** [comment]
I use Selenoid for parallel my tests on puppeteer. Firstly, using axios I send request to create a browser into Selenoid container and then connect to it via puppeteer. Here, the example repo https://github.com/CrispusDH/puppeteer-ava-selenoid

**Comment by aslushnikov** [comment]
> Do you consider this as part of this project, or do you think it needs to be separate (like selenium grid is separate from WebDriver)

@muodov We'd love to see this as a separate project. We know this is an important use-case, so if there's something in PlayWright that's missing - please file a bug against us!
