### ISSUE TITLE
[BUG] webkit evaluate promise never returns / fails

### ISSUE THREAD

**Issue by natew** [microsoft/playwright#5851]
**Context:**
- Playwright Version: 1.9.2
- Operating System: Linux + Mac
- Node.js version: 15.10.0
- Browser: Webkit

**Code Snippet**

```javascript
const {webkit} = require('playwright');

(async () => {
  const browser = await webkit();
  const page = await browser.newPage();
  await page.goto('https://google.com')
  await page.evaluate((uri) => Promise.resolve(uri), 'test')
  // ... never finishes
})();
```

**Describe the bug**

I've tested this on linux and mac, headless and non-headless. Webkit never returns from any of them. Firefox seems to work just fine.

**Comment by aslushnikov** [comment]
@natew how do you know it never finishes? The process hangs since you don't close the browser. For example, the following works just fine for me:

```js
const {webkit} = require('playwright');

(async () => {
  const browser = await webkit.launch();
  const page = await browser.newPage();
  await page.goto('https://google.com');
  await page.evaluate((uri) => Promise.resolve(uri), 'test');
  console.log('done!');
  await browser.close();
})();
```

**Comment by natew** [comment]
Hm, not able to replicate anymore, closing
