### ISSUE TITLE
[BUG] codegen inserts AltGraph key press

### ISSUE THREAD

**Issue by black-silence** [microsoft/playwright#5854]
**Context:**
- Playwright Version: 1.9.2
- Operating System: Linux
- Node.js version: v12.18.2
- Browser: Chromium 90.0.4421.0
- Extra: pipenv 11.9.0

  System:
    OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
    Memory: 1.11 GB / 15.30 GB
    Container: Yes
  Binaries:
    Node: 12.18.2 - /usr/bin/node
    npm: 6.14.8 - /usr/bin/npm
  Languages:
    Bash: 5.0.17 - /usr/bin/bash

**Code Snippet**

Snip generated by codegen:

```python
    # Fill input
    page.fill("input", "playwright")
    # Press AltGraph
    page.press("input", "AltGraph")
    # Fill input
    page.fill("input", "playwright@example.com")
```

**Describe the bug**

When typing an email address into an input, codegen creates a fill command up to the @, then inserts an AltGraph keypress, then continues with the final fill command.

IMO Codegen should try to avoid the extra commands. Without copy-paste the user will always have to use AltGr to write the @ but the browser should not receive it as a separate keypress I guess. A developer could still insert it manually if required for some special case.

**Comment by pavelfeldman** [comment]
What is your keyboard layout?

**Comment by black-silence** [comment]
XKBMODEL="pc105"
XKBLAYOUT="de"
XKBVARIANT="nodeadkeys"
XKBOPTIONS=""

Standard Qwertz with nodeadkeys
