### ISSUE TITLE
WebKit Canvas element invisible on screenshot

### ISSUE THREAD

**Issue by lucas-jones** [microsoft/playwright#586]
When using `page.screenshot` on Webkit, Canvas elements appear to be invisible.

_When running `headless: false` the canvas is visible in browser just not in screenshot._

It looks to be only on WebGL Canvas elements...

Chromium & Firefox work as intended.

**Example**
```
const pw = require('playwright');

(async () => {
  const browser = await pw.webkit.launch(); // or 'chromium', 'firefox'
  const context = await browser.newContext();
  const page = await context.newPage();

  await page.goto('https://pixijs.io/examples/#/demos-basic/container.js');

  await page.screenshot({ path: 'example.png' });
  await browser.close();
})();
```

Chromium
![chromium](https://user-images.githubusercontent.com/809463/72971049-cf59b780-3dc0-11ea-82a6-03082e5f68a3.png)

Firefox
![firefox](https://user-images.githubusercontent.com/809463/72971050-cf59b780-3dc0-11ea-835c-a654504ce012.png)

WebKit
![webkit](https://user-images.githubusercontent.com/809463/72971052-cff24e00-3dc0-11ea-861f-6004e4ef9432.png)

**Comment by lucas-jones** [comment]
Looks to be WebGL Canvas that are invisible, tested on these two links, the Basic Canvas one worked but the WebGL again invisible

Basic Canvas:
https://www.w3schools.com/html/html5_canvas.asp

WebGL Canvas:
https://webglsamples.org/field/field.html

**Comment by JoelEinbinder** [comment]
Which operating system is this? Thanks.

**Comment by lucas-jones** [comment]
MacOS

**Comment by pavelfeldman** [comment]
I believe this is everywhere. We have test for it that is marked as disabled on both WebKit  and Firefox. https://github.com/microsoft/playwright/blob/5c5faf35a961865c75202a4032d470c5c1eb6503/test/screenshot.spec.js#L178

**Comment by pavelfeldman** [comment]
@yurys do you think you can get composited pixels with your new screencasting infrastructure?

**Comment by yury-s** [comment]
Yes, should be possible. Not sure about full page mode but at least capturing viewport is doable.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
