### ISSUE TITLE
[Bug] not getting all DEBUG=pw:api calls into the Logger

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright#5871]
I am sometimes using the awesome `DEBUG=pw:api` to see what happens during a failure (in combination with the awesome video recording and/or inspector). All great tools.

But I would want to run my tests in CI and get the logs shown by `DEBUG=pw:api` into the [Logger](https://playwright.dev/docs/api/class-logger/). Something like:

```js
const { chromium } = require('playwright');  // Or 'firefox' or 'webkit'.

(async () => {
  const browser = await chromium.launch({
    debug: ['pw:api']
    logger: {
      isEnabled: (name, severity) => name === 'browser',
      log: (name, severity, message, args) => console.log(`${name} ${message}`)
    }
  });
  ...
})();
```

I do not want to just set `DEBUG=pw:api` to print to stdout but I want these specific logs only sent to the Logger so I can save it in a file during my runs. It is a great tool combined with a video, to see when something fails.

**Comment by pavelfeldman** [comment]
name === 'api' corresponds to pw:api, but it doesn't currently print as many details as pw:api. We'll look into it.

```js
const browser = await chromium.launch({
    logger: {
      isEnabled: name => name === 'api',
      log: (name, severity, message) => console.log(message)
    }
});
```

**Comment by thernstig** [comment]
@pavelfeldman that snippet gave me no logs at all. `isEnabled: name => true',` only gives me logs for `protocol`. No `api` at all.

**Comment by pavelfeldman** [comment]
What Playwright version are you on? It works for me.

**Comment by thernstig** [comment]
1.9.2. I am using jest-playright though, but I doubt that should be the problem as I can properly use `isEnabled: (name) => true,`.

This is my launch options:
```js
  launchOptions: {
    slowMo,
    proxy,
    logger: {
      isEnabled: (name) => name === 'api', // This works though: isEnabled: (name) => true,
      log: (name, severity, message) => console.log(message),
    },
  },
```

**Comment by worldomonation** [comment]
I believe this is the issue I am running into with my project.

Playwright 1.11.0, nodeJS 14.16.1, mocha runner on macOS Big Sur 11.2.3.

This is my code snippet around the `launch()` method:

```
	return await browser.newContext( {
		viewport: null, // Do not override window size set in the browser launch parameters.
		recordVideo: { dir: videoDir, size: { width: dimension.width, height: dimension.height } },
		userAgent: userAgent,
		logger: {
      		isEnabled: (_name, _severity) => _name === 'api',
      		log: (_name, _severity, _message) => writeLog({name: _name, severity: _severity, message: _message}, timestamp)
   		}
	} );
```

The logs that `writeLog` function ends up writing are as follows:

```
28305 api info => browserContext.newPage started
28305 api info <= browserContext.newPage succeeded
28305 api info => page.goto started
28305 api info <= page.goto succeeded
28305 api info => page.close started
28305 api info <= page.close succeeded
```

The verbosity of logs generated does not change regardless of what I set as the name (`protocol`, `api`, `browser`).

**Comment by thernstig** [comment]
@aslushnikov what does the label "P3-collecting-feedback" mean in this case? It is a real bug as far as I can tell?

**Comment by dwalleck** [comment]
Bumping this because I would like to see if this could be improved. My team's scenario is that they would like to log to a file or other logging sinks using something like winston. The only workaround I've found is to redirect output to a file like `DEBUG=pw:api npx playwright test &> playwright-api.log`

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
