### ISSUE TITLE
Logging and/or Progress indicators

### ISSUE THREAD

**Issue by jcousins-ynap** [microsoft/playwright#588]
It would be great to have some form of progress indicators, or logging output, when a flag is passed, like `verbose`.

At the moment when the script runs it looks like it hangs until done.

**Comment by JoelEinbinder** [comment]
We use the `debug` package from npm. You can set the environment variable `DEBUG=*` to see a variety of verbose logs.

**Comment by pavelfeldman** [comment]
I hope this worked for you!

**Comment by jcousins-ynap** [comment]
I haven't checked, but I sure it works.
