### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mitchied** [microsoft/playwright#5890]
FAIL   browser: chromium  tests/e2e/*.e2e.test.ts
  ● Test suite failed to run
    PlaywrightError: jest-playwright-preset: Cannot find playwright package to use open
      at Object.getPlaywrightInstance (node_modules/jest-playwright-preset/lib/utils.js:120:15)
      at PlaywrightEnvironment.setup (node_modules/jest-playwright-preset/lib/PlaywrightEnvironment.js:114:78)

**Context:**
- Playwright Version:  
     "jest-playwright-preset": "1.5.1",
    "playwright": "1.9.2",
- Operating System: Mac
- Node.js version: v14.16.0
- Browser: Chromium + FF
- Extra: [any specific details about your environment]

This is more like a configuration issue since my team members can run the tests without any issues

**Comment by pavelfeldman** [comment]
jest-playwright is a community effort tracked at https://github.com/playwright-community/jest-playwright. Sorry for closing it here so late, but you should follow up with them.
