### ISSUE TITLE
[Feature] Support sites hosted on cloudflare.com

### ISSUE THREAD

**Issue by suntong** [microsoft/playwright#5895]
Can we support sites hosted on cloudflare.com like finviz.com?

```js
const playwright = require('playwright').chromium;  // Or 'firefox' or 'webkit'.

(async () => {
  const browser = await playwright.launch();
  const context = await browser.newContext();
  const page = await context.newPage('https://finviz.com/news.ashx');
  // other actions...
  console.log(await page.content());
  await page.waitForSelector('#news > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody');
  await page.screenshot({ path: 'finviz.png' });
  await browser.close();
})();
```

I can't see anything wrong with above code, but when I run it, I'll get:

```
<html><head></head><body></body></html>
(node:880627) UnhandledPromiseRejectionWarning: page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "#news > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody" to be visible
```

Coming from Puppeteer, I tried to wait for more content than the pure empty `<html><head></head><body></body></html>`, like:

```js
 await page.waitFor(1000);
 page.waitForNavigation({ waitUntil: 'networkidle' })
```

But none of them work for playwright. 

There is a HUGE list of sites hosted on cloudflare.com, finviz.com happens just to be one of a million.

Any help making such sites work appreciated.

**Comment by suntong** [comment]
Update, found

`  await page.waitForTimeout(1200);`

works, but the result is the same, no matter how long I wait.

**Comment by pavelfeldman** [comment]
`newPage` does not accept url, you need to call `page
goto`.

**Comment by suntong** [comment]
It should work, but anyway, I've change to 

```
  const page = await context.newPage();
  await page.goto('https://finviz.com/news.ashx');
``

but the result is exactly the same.

**Comment by suntong** [comment]
Sorry I made a silly mistake/reply previously, and now it's been corrected. 

Just that I'm facing a new issue. Please check above. thx.

**Comment by pavelfeldman** [comment]
Sorry, could you re-file the issue? You are saying that you changed the original description, but I think it is still the same. The snippet still misses page.goto. Without being able to see the script or to repro it, I suspect that cloudflare identified you as a spammer - that's their business basically and you are pointing automated software at them...
