### ISSUE TITLE
[Question] switch different firefox/chrome version 

### ISSUE THREAD

**Issue by aaronxiang0926** [microsoft/playwright#5897]
Hello i want to use this framework, but i have some concerns ,

If I already have installed the firefox 85 in my local machine.  i want to use this version of firefox for testing , how should i do ?

**Comment by shirshak55** [comment]
I think the best way is to read docs. Most of the browser playwright provides are patched internally so there is no guarantee that all the features will work. If you don't use playwright provided browser some weird features usually wont work.

However if you want to run specific version just use executable path when launching the browser. It should be maintained in docs. For that please move ahead to playwright.dev 

Have Fun!

**Comment by pavelfeldman** [comment]
More info at https://playwright.dev/docs/next/browsers
