### ISSUE TITLE
Metrics API

### ISSUE THREAD

**Issue by Quramy** [microsoft/playwright#590]
Hi. I want to an API to measure pages' metrics, like https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pagemetrics. How about it ?

### Motivation
I maintain https://github.com/reg-viz/storycap, which captures Storybook with puppeteer and want to migrate from puppeteer to playwright in order to provide options of multiple rendering engines. 
We need the metics API because our tool uses Puppeteer's metrics ( especially `LayoutCount` and `RecalcStyleCount`) to watch whether the browser rendering pipeline is stable.

**Comment by JoelEinbinder** [comment]
Maybe we can directly provide some indication whether the rendering is stable? I'm very curious as to how your tool works.

**Comment by Quramy** [comment]
@JoelEinbinder Thanks for reply.

>  I'm very curious as to how your tool works

The following figure is a screenshot of Chrome rendering pipeline.

![chrome_rendering_pipeline](https://user-images.githubusercontent.com/1262998/73051498-34e39c00-3ec6-11ea-864b-d83930cbc358.png)

I really want the (A) timing to get stable `page.screenshot()` result, but, as far as I know, we can't get if painting/composition finished ( if you have some plans to get (A) timing, please tell me).

So we use (B) timing instead of (A). The (B) timing is closer to (A) than JS function call finished timing. The (B) timing means style recalculation and layouting finished and we wait for (B) using code such as:

```ts
let recalcStyleCountOfPreviousFrame = -1, layoutCountOfPreviousFrame = -1;
for (let i = 0; i < 100; i++) {
  const { RecalcStyleCount, LayoutCount } = await page.metrics();
  const isStable = 
    recalcStyleCountOfPreviousFrame === RecalcStyleCount &&
    LayoutCount === layoutCountOfPreviousFrame;
  if (isStable) {
    break;
  }
  recalcStyleCountOfPreviousFrame = RecalcStyleCount;
  layoutCountOfPreviousFrame = LayoutCount
  await new Promise(res => setTImeout(res, 16));
}

await page.screenshot();
```

Of course, I'm sure this logic is not perfect. But it works well to some extent.

Metrics API is not our  goal. We really want a method/API to get (A) timing.

**Comment by Quo0** [comment]
It would be great if we would have the same metrics API that we have in Puppeteer. 
JSheap tracking is really important thing and I think that a lot of people would miss it in Playwright =)
It would be great if we would be able to track CPU usage, also.

**Comment by JoelEinbinder** [comment]
You can measure memory in chromium by evaluating ‘performance.memory.usedJSHeapSize’ within the page.

**Comment by pavelfeldman** [comment]
This only collected 8 upvotes during the last 18 months, so I'm going to close it and defer to the third parties to resolve this. You can always open a new bug and link to this one with additional information!
