### ISSUE TITLE
[Feature] Make test execution speed (option slowMo) adjustable during test execution

### ISSUE THREAD

**Issue by klhex** [microsoft/playwright#5900]
Currently, you can only artificially lower Playwright's execution speed for the entirety of a test execution, using the browserType.launch option "slowMo" (see https://playwright.dev/docs/api/class-browsertype#browsertypelaunchoptions):

![image](https://user-images.githubusercontent.com/71178731/111997737-a0051e80-8b1b-11eb-9b2f-046b9fc1be46.png)

However, in many debugging situations you're only interested in watching Playwright doing it slowly during specific parts of your test while the remainder of your test execution could very well be executed at normal (warp) speed in order to save your precious test development/debugging time (e.g. you're testing an app consisting of 6 pages and you only want to watch the last page being tested in slow motion).

Therefore, it would be very handy if you could slow Playwright temporarily down for specific parts of your test code only, for example via ```await page.slow(30)``` and then resetting it via ```await page.slow(0)``` or something comparable.

**Comment by thernstig** [comment]
That sounds great! Could be used with the Inspector if one has also set `await page.paus()` to then directly in the Inspector set the slow speed (without even having to use `await page.slow(30)`. I.e. you could use that, but when you hit that location the Inspector has a field where you see the normal speed change to 30, but you can then also further change it if wanted to another speed direclty.

**Comment by klhex** [comment]
Actually, API-wise, maybe something like ```page.debug( { slowMo: 60 } )``` would be better in order to cater for future debug-related options.

**Comment by thernstig** [comment]
If so, then I assume `page.pause()` should be put into that as well. I'd maybe rather have `page.debug.slowMo(60)` then as I find it faster to type and easier for auto-completion. But I suppose all this is up to the Playwright peeps :)

**Comment by klhex** [comment]
@thernstig Yes, indeed, in that case it would make sense to integrate ```page.pause()``` into ```page.debug(...)``` as well, good hint

**Comment by LanderBeeuwsaert** [comment]
Jep, for us, a slowMo per page + (optionally that you can set dynamically) would be what we are looking for.

**Comment by tommyh** [comment]
While this is still collecting feedback, I'd be interested in changing the timeout every time I make a call to `page.pause()`.

Use-case: I call `pause` so that I can experiment and figure out the best selector for an element.  I will be poking around the page and the test fails because it hits the 30 second timeout.  Right now, I just override timeout on the command line via `npx playwright test --timeout=0`.

What would be *really* interesting, is if I could have a set of config options which I can set in `playwright.config.js` and they get set when I call `pause()`:

```
module.exports = {
   timeout: 30000,
   pauseOptions: {
      timeout: 0,
      slowMo: 200,
   },
};
```

**Comment by ani-im** [comment]
Do have any updates deadlines for this?

**Comment by Zoltanpetrik** [comment]
It seems like this affects typing into input fields, so a slowmo of 2000 makes typing extremely slow.

Overriding typing speed is not possible with this parameter:

```
*locator*.type(text, {
  delay: 10
})
```

**Comment by alexn-s** [comment]
would be really helpful  +1

**Comment by ivanvison** [comment]
Definitely a must! +1
Currently getting trained in Playwright and my training lead me here.

**Comment by klhex** [comment]
Since this issue is approaching is first birthday, I'm using this opportunity to ping @pavelfeldman and @arjunattam to highlight people's interest in this feature. :eyes: :pray:

**Comment by krishnaaSundaram-QaStack-1989** [comment]
> ```ts
> page.locator = slowLocator(page, 500);
> ```

Can I get the same for expect assertions with tobevisible or tobeenabled combination

**Comment by luucamay** [comment]
does anyone know if this feature has been added to the options when running test from command line?

**Comment by AWolf81** [comment]
@luucamay Yes, the `slowMo` feature is available.

It can be configured at the `launchOptions` of your browser in the Playwright config. https://playwright.dev/docs/test-configuration#more-browser-and-context-options

Example snippet for Playwright config with chrome and slow-down (untested, but this should work):
```ts
import type { PlaywrightTestConfig } from '@playwright/test';
const config: PlaywrightTestConfig = {
  use: {
    channel: 'chrome',
    slowMo: 600
  },
};
export default config;
```

With this each browser interaction will be slowed down by 600ms clicking, typing etc. **Note:** Typing can take some time if you're choosing a large value. The 600ms will be between each character that is typed.

**Comment by ATARARHRB** [comment]
+1 for this issue. I'm using getAttribute to get all the attributes of 90+ elements to verify if they are filled in or not, while the rest is just ordinary navigating and clicking. The getAttribute loop grinds to a halt with a slowmo of 1 second, while the rest could benefit from taking a second to be able to see what is going on. Being able to selectively pass a slowmo for a test step or certain sections would be useful rather than having to toggle it for a test.

**Comment by MobileTester** [comment]
> Here's a hack I wrote to get this functionality going without any changes required to the Playwright codebase.
> 
> For context, I wanted to "slow down" certain operations in the tests so I could record videos that didn't blaze through the operations so they could be used to show people for training purposes.
> 
> Waiting per-operation is easy in a test by just wrapping the request in a Promise that delays a certain amount of time, but I wanted to be able to enable/disable the delay with a small code change instead of having to change every line of the test to wait a certain amount of time.
> 
> Here's what I came up with (it's in TypeScript). It wraps the `page.locator` function with a version that replaces `click` and `fill` to be artificially slowed.
> 
> ```ts
> import { Locator, Page } from "@playwright/test";
> 
> // Return a "slow" page locator that waits before 'click' and 'fill' requests
> function slowLocator(
>   page: Page,
>   waitInMs: number
> ): (...args: any[]) => Locator {
>   // Grab original
>   const l = page.locator.bind(page);
> 
>   // Return a new function that uses the original locator but remaps certain functions
>   return (locatorArgs) => {
>     const locator = l(locatorArgs);
> 
>     locator.click = async (args) => {
>       await new Promise((r) => setTimeout(r, waitInMs));
>       return l(locatorArgs).click(args);
>     };
> 
>     locator.fill = async (args) => {
>       await new Promise((r) => setTimeout(r, waitInMs));
>       return l(locatorArgs).fill(args);
>     };
> 
>     return locator;
>   };
> }
> ```
> 
> Now, I just put this at the start of my test:
> 
> ```ts
> test("sample test", async ({ page }) => {
>   // Overwrite page.locator to give us back a version that waits 500ms before `click` and `fill`
>   page.locator = slowLocator(page, 500);
> 
>   await page.locator('input).fill();
>   await page.locator('button').click();
> });
> ```
> 
> It should be pretty trivial to add delays to methods on the locator other than `click` and `fill` by following the pattern.
> 
> Now if you want the original/fast version of the locator, just comment out the one line that resets the `page.locator` and you get back your speedy tests. If you want to record a slowed-down video you can just uncomment the line (or add it in temporarily) to get a more relaxed version.

Is it possible to write similar wrapper for getByRole ?

**Comment by edelreal** [comment]
When running a test manually and watching the browser in headed mode, it would be very convenient to set the "speed" (slowMo) in the command line, rather than editing the test or creating a config file.

**Comment by vitalets** [comment]
> does anyone know if this feature has been added to the options when running test from command line?

This is my workaround to automatically set `slowMo` when running in `--headed` mode from cli:
```ts
export default defineConfig({
  use: {
    launchOptions: { 
      slowMo: slowMoInHeadedMode(1000) 
    }
  }
});

function slowMoInHeadedMode(ms: number) {
  if (process.argv.includes('--headed')) process.env.SLOW_MO = '1';
  // important to use env var - for workers
  return process.env.SLOW_MO ? ms : undefined;
}
```

**Comment by jshet** [comment]
Has anyone solved this with Python?

**Comment by basickarl** [comment]
Bumping, this would be super useful. I currently have concurrent process happening. I have a MutationObserver that looks for DOM changes and then takes a screenshot via an exposed function. The screenshot however is too slow as the UI changes and updates the UI. I'd like a hook or setting that would be able to slow down all commands except the screenshot which is running in another thread.

**Comment by mxschmitt** [comment]
Closing for now since we offer better tools for debugging and recommend these instead:

- Playwright [Trace Viewer](https://playwright.dev/docs/trace-viewer-intro): This one allows you to debug local and remote tests including full snapshot and screenshots to see how the page behaved.
- [Visual Studio Code extension](https://playwright.dev/docs/getting-started-vscode): This one allows you to run tests and set breakpoints during the test execution and inspect the actual page state.
- Using [`page.pause()`](https://playwright.dev/docs/api/class-page#page-pause): This one will pause the test execution and open the Playwright Inspector to inspect the page state. Inspect and Verify Locators etc.

For slowing down videos, we recommend instead looking at a specific [Trace](https://playwright.dev/docs/trace-viewer-intro). You can upload the zip at [trace.playwright.dev](https://trace.playwright.dev/).
