### ISSUE TITLE
[BUG] browserType.launch: Host system is missing dependencies! Missing libraries are: libenchant.so.1

### ISSUE THREAD

**Issue by machineghost** [microsoft/playwright#5901]
**Context:**
  System:
    OS: Linux 5.4 Linux Mint 20.1 (Ulyssa)  (**NOTE:** Linux Mint is essentially Ubuntu)
    Memory: 276.33 MB / 23.40 GB
    Container: Yes
  Binaries:
    Node: 15.10.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 7.3.0 - /usr/local/bin/npm
  Languages:
    Bash: 5.0.17 - /bin/bash
  npmPackages:
    playwright: ^1.9.2 => 1.9.2 

**Issue Template Note**
One small suggestion: in your issue template, you have the "Context" form followed by the `npx envinfo --preset playwright` comment.  This means most people will read, and then fill out, that form ... and then _after_ they do, they'll see that they wasted their time, because they could have just used that command you offer :)

Please consider moving that command to the start of the form, so people can know it exists (and use it) before they've filled out the form manually.

**Code Snippet**

I'm trying to run a "Hello World" Playwright test:

```javascript
describe('Front Page Acceptance Tests', () => {
  it('takes a screenshot', async () => {
    const browser = await webkit.launch();
    const page = await browser.newPage();
    await page.goto('https://www.example.com');
    await page.screenshot({ path: `example.png` });
    await browser.close();
  });
});
```

**Describe the bug**

When I try to run it (using Mocha test runner), I get:

```
     browserType.launch: Host system is missing dependencies!

  Missing libraries are:
      libenchant.so.1
```
I found similar issues from (unsupported) Arch Linux users with this problem, but I'm using Linux Mint, which uses Ubuntu (and it's Debian package system) ... and Ubuntu _is_ supposed to be supported.

As a side note, I already had the package `libenchant-2-2` installed, and I also tried installing `libenchant-2-dev`, but neither fixes things.  If a dev could even just explain what package this `libenchant.so.1` is supposed to come from (on Ubuntu Linux), it would help a lot.

**Comment by pavelfeldman** [comment]
As long as you are using our docker image or GitHub Action, this should not be an issue for you. You can also run `npx playwright install-deps` to install all the missing dependencies. But sadly there is no generic solution to ensure you have all the deps beyond running a script manually or using a container...
