### ISSUE TITLE
[Feature] console events for electron app

### ISSUE THREAD

**Issue by sirtimid** [microsoft/playwright#5905]
It would be great if we could use the the pluggable logger sink for Electron tests as well. :)

**Comment by pavelfeldman** [comment]
We are actually thinking about going the other way around elsewhere. How do you use the sink? Does DEBUG= not work for you?

**Comment by sirtimid** [comment]
Hey @pavelfeldman I would like to use logger in order to assert things within tests, so I would push the logs in an array and assert that the expected string exists in that array, The DEBUG flag won't help me with this

**Comment by sirtimid** [comment]
Issue is that currently we can only get the logs only from renderer with the `console` event, I need a way to take the logs from main process as well, spectron has a `app.client.getMainProcessLogs()` method

**Comment by pavelfeldman** [comment]
@sirtimid: would it work if you had something like [page.on('console')](https://playwright.dev/docs/api/class-page#pageonconsole) on the electronApp object?

**Comment by sirtimid** [comment]
@pavelfeldman yeah, for sure, it would be even better TBH!

**Comment by rssk** [comment]
Is there any way to get at electron main logs from the launched process? It seems like otherwise it'd be hard to debug fails on headless tests

**Comment by imolorhe** [comment]
I also need this API to retrieve logs from the main process, for the same reasons as @sirtimid. Are there any timelines for this?

**Comment by cameron-martin** [comment]
It does seem to [collect the stdout and stderr](https://github.com/microsoft/playwright/blob/807f70bccf975a007f68a3faf7e4a949d58b1ab7/packages/playwright-core/src/utils/processLauncher.ts#L102-L110) of the launched electron process, but I can't work out how to access them via the public APIs.

**Comment by Prinzhorn** [comment]
> It does seem to [collect the stdout and stderr](https://github.com/microsoft/playwright/blob/807f70bccf975a007f68a3faf7e4a949d58b1ab7/packages/playwright-core/src/utils/processLauncher.ts#L102-L110) of the launched electron process, but I can't work out how to access them via the public APIs.

To safe anyone from going through the same rabbit hole I just did, this works with the latest playwright 1.24.1:

```js
const app = await electron.launch({ args: ['main.js'] });

app.process().stdout.on('data', (data) => console.log(`stdout: ${data}`));
app.process().stderr.on('data', (error) => console.log`stderr: ${error}`));
```

From https://github.com/microsoft/playwright/issues/13267#issuecomment-1086786960 and https://github.com/microsoft/playwright/pull/13280

**Comment by ahmedmukhtar1133** [comment]
@Prinzhorn This doesn't seems to be working in `playwright 1.24.2`.
This piece of code gives error app.process is not function.

<img width="716" alt="image" src="https://user-images.githubusercontent.com/15345707/182710348-18390979-4226-4a1b-9ee0-cc5454c1fa5f.png">

**Comment by fcastilloec** [comment]
> To safe anyone from going through the same rabbit hole I just did, this works with the latest playwright 1.24.1:
> 
> ```js
> const app = await electron.launch({ args: ['main.js'] });
> 
> app.process().stdout.on('data', (data) => console.log(`stdout: ${data}`));
> app.process().stderr.on('data', (error) => console.log`stderr: ${error}`));
> ```
> 
> From [#13267 (comment)](https://github.com/microsoft/playwright/issues/13267#issuecomment-1086786960) and #13280

Thanks so much for mentioning this new feature! Unfortunately, this doesn't output all `stdout` or `sterr` messages from the electron app, only the ones emitted after the app finished loading (or some other condition). I'm interested in seeing all logs, especially the ones emitted before the `did-finish-load` event is fired.
As a test, just issue a `console.log` before you create/load your `BrowserWindow` and that message is not shown.
So this issue is still not fully fixed.
<br/><br/>

> @Prinzhorn This doesn't seems to be working in `playwright 1.24.2`. This piece of code gives error app.process is not function.

You can only access the `process` once the app has finished launching, in other words, you probably forgot to use `await` when launching your app.

**Comment by MatthijsBurgh** [comment]
Is there any progress on this one? Has someone maybe found a workaround?

I experience the same issue as @fcastilloec, where logs before loading are not accessible.
