### ISSUE TITLE
[Feature] save page or trigger download event on non-html content

### ISSUE THREAD

**Issue by andrisi** [microsoft/playwright#5906]
Add a method to save the raw page content to a file. Useful in case it is not HTML but an image, pdf or a text file wich Chrome (and probably the other browsers as well) display directly. I can get the page holding them (from the context's page event) but not save them. Or trigger a download or load event if the response is not HTML. Thanks!

**Comment by andrisi** [comment]
...also, if the page is a pdf perhaps you could alter the pdf() function to just save that directly.

**Comment by JoelEinbinder** [comment]
An api like
```js
await page.savePage({path: 'mypath.pdf'});
```
sounds reasonable to me.

**Comment by andrisi** [comment]
Great. Just remember to wait for the page (pdf, image, csv, ...) to download. Or expose the "load" even even if it is not a HTML/js page.

**Comment by sarink** [comment]
How can you download a pdf file? Playwright just keeps opening it

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
