### ISSUE TITLE
GPU/WebGL/WebGPU support?

### ISSUE THREAD

**Issue by robertleeplummerjr** [microsoft/playwright#591]
Curious if this is supported.  It would seem so, but I didn't see if this had been asked previously.

**Comment by JoelEinbinder** [comment]
WebGL is definitely supported! Whether or not it has hardware acceleration depends on your system, but it often does.

WebGPU I think is only supported for WebKit, and is disabled by default.

**Comment by pavelfeldman** [comment]
Please reopen if you have further comments or questions!
