### ISSUE TITLE
[Feature] pass config values to chromium

### ISSUE THREAD

**Issue by andrisi** [microsoft/playwright#5918]
Would be nice to be able to set config options as you can with ChromeDriver: https://chromedriver.chromium.org/capabilities + the "config" capability. My use case is related to #5906 - I'd need to set the plugins.always_open_pdf_externally to true, so Chromeium does not use it's internal PDF viewer, so I could download a PDF, but I guess there a zillion other use cases when testing your web apps. Thanks.

**Comment by pavelfeldman** [comment]
Could you share a snippet showing how you are configuring ChromeDriver today?

**Comment by andrisi** [comment]
I don't actually use Selenium (or clearly understand how it works) but the site I linked above mentions passing config values to Chrome through some ChromeOptions object, and this "capability" is mentioned in discussions around other tools using Selenium. Of course this is a Google tool (Chromedriver) and a binary so they might use some insider trick... I'll try to see if there is any source code available for tools using this magic trick.

**Comment by pavelfeldman** [comment]
No worries, we are all Chromium engineers here. I wanted to make sure we solved your problem in full.

**Comment by andrisi** [comment]
Thanks. For now I use firefox and launchPersistentContext() with a prefs.js which disables its internal PDF viewer.

**Comment by JoelEinbinder** [comment]
Our current configuration options are very powerful, especially passing command line flags directly into chromium via `args`. I think we will tackle this option by option if any functionality is missing.
