### ISSUE TITLE
[BUG] userAgent on context may not work with proxy

### ISSUE THREAD

**Issue by buckthebug** [microsoft/playwright#5935]
**Context:**
- Playwright Version: 1.9.2
- Operating System: Windows
- Node.js version: 10.24.0
- Browser: Chromium
- Extra: **proxy server filters requests**

node userAgentBug.js

```javascript
// userAgentBug.js

const { chromium, webkit } = require('playwright');

(async () => {
  const browser = await chromium.launch(
    {
      headless: false,

      args: [
        // This works
        //'--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36'
      ],

      proxy: { server: 'http://webproxy.paranoidcompany.com:8080' }

    });
  const context = await browser.newContext({userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36'})
  const page = await context.newPage();

  await page.goto('http://google.com/');
  console.log(await page.evaluate('navigator.userAgent'));
  await page.waitForTimeout(3000)

  await page.click('"Store"');
  console.log(await page.evaluate('navigator.userAgent'));

  await page.waitForTimeout(3000)

  await page.goto('https://bing.com/');
  console.log(await page.evaluate('navigator.userAgent'));

})();
```
Console output:
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36

```

**Describe the bug**

As mentioned, we have a proxy that blocks requests from "non-standard" (not approved) browsers. Chromium isn't approved, unlike Chrome. 
With the attached code, the first page is displayed correctly, even the click on a link (within the same domain) works. The navigation to another site is blocked.
The weird thing is that navigator.userAgent is set correctly (see Console output) but something on a lower level likely not.
I know this is really an edge case. Please give it a try to investigate it a bit. Maybe, it will be enough to mention it in documentation with a note that using args --userAgent is a workaround.
Thanks

**Comment by JoelEinbinder** [comment]
It's going to be a bit tricky to debug without code to repro, but it sounds like we are leaking some network request with the wrong user agent when chromium swaps the web process on navigation.

I tried to write a test to reproduce this, but I was unsuccessful. Can you investigate how the bad user agent appears to the proxy?

**Comment by buckthebug** [comment]
Hi Joel,
Yeah, it's tricky even for me. Since I can't control the real proxy (and I don't want to ask for logs because bypassing the rules wouldn't have been perceived well). But I've succussed with Fiddler as a local proxy.
When it's navigated to bing.com for the first time, there is a request with CONNECT method and its User-Agent is the default one (this could be the place). The very next request with GET method has the agent specified on the playwright context.
Hope I helped you to be able to reproduce it. On the other had, I don't understand why our proxy blocks it... there is one digit different. 🤦‍♂️

**Comment by pavelfeldman** [comment]
I can repro this. Network stack is not configured with the per-context user agent and uses a real global one. It also explains why your workaround works. I added a failing test for it, but fixing it is going to take time, so I'd suggest to stick with the workaround. Thanks for filing and great repro steps!

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
