### ISSUE TITLE
[Feature] page.$: add waitForSelector as optional parameter

### ISSUE THREAD

**Issue by Ank2503** [microsoft/playwright#5936]
Is it possible to add optional parameter in page.$ to wait for selector first, than perform searching, another words replacing
`await page.waitForSelector('selector');
await page.$('selector');`
with
`await page.$('selector',{waitFor: true});`
or something like it, because for my tests $ or $$ functions sometimes return undefined

**Comment by JoelEinbinder** [comment]
waitForSelector returns the selector, so you can just do
```js
const handle = await page.waitForSelector('selector');
await handle.click();
```
