### ISSUE TITLE
[BUG] waitForEvent 'page' seems to be unstable

### ISSUE THREAD

**Issue by KevinLuc95** [microsoft/playwright#5948]
**Context:**
I'm trying to get the new window tab when run automation by playwright but I open facing the issue timeout when waitForEvent page even though increase timeout

**Code Snippet**

```javascript
      const [newPage] = await Promise.all([
        context.waitForEvent('page', { timeout: 180000 }),
      ]);
```

**Describe the bug**
```
 TimeoutError: Timeout while waiting for event "page"
13:28:21      Note: use DEBUG=pw:api environment variable to capture Playwright logs.
13:28:21          at /home/ec2-user/workspace/hg-web-automation-test/node_modules/playwright/lib/client/waiter.js:49:51
13:28:21          at Waiter.waitForPromise (/home/ec2-user/workspace/hg-web-automation-test/node_modules/playwright/lib/client/waiter.js:57:28)
13:28:21          at ChromiumBrowserContext.waitForEvent (/home/ec2-user/workspace/hg-web-automation-test/node_modules/playwright/lib/client/browserContext.js:214:24)
13:28:21          at HomePage.getNewWindowPage (/home/ec2-user/workspace/hg-web-automation-test/src/page/Page.js:24:29)
13:28:21          at Object.<anonymous> (/home/ec2-user/workspace/hg-web-automation-test/src/test/smoke/homepage.test.js:45:31)
13:28:21          at _callCircusTest (/home/ec2-user/workspace/hg-web-automation-test/node_modules/jest-circus/build/run.js:212:5)
13:28:21          at _runTest (/home/ec2-user/workspace/hg-web-automation-test/node_modules/jest-circus/build/run.js:149:3)
13:28:21          at _runTestsForDescribeBlock (/home/ec2-user/workspace/hg-web-automation-test/node_modules/jest-circus/build/run.js:63:9)
13:28:21          at _runTestsForDescribeBlock (/home/ec2-user/workspace/hg-web-automation-test/node_modules/jest-circus/build/run.js:57:9)
13:28:21          at run (/home/ec2-user/workspace/hg-web-automation-test/node_modules/jest-circus/build/run.js:25:3)
```

**Comment by pavelfeldman** [comment]
Promise.all should always have at least two items: waitFor and the action itself that results in something you wait for. If you perform this action before waiting, by the time you start waiting popup page is already there. See https://playwright.dev/docs/events for details.

**Comment by KevinLuc95** [comment]
@pavelfeldman 
Thank you for the quick response, maybe I do not make clear my context sorry for that, in my script it's will click on an element and the website will be open a new window tab, I just want to get the new page and continue run with the new page

**Comment by aslushnikov** [comment]
@KevinLuc95 can you share a larger snippet? It's hard to say what's going on with this single line of code. Ideally, you'll share the whole thing with us so that we can run it locally and debug it.

**Comment by andrisi** [comment]
@pavelfeldman It might be a related issue, but `waitForEvent('page', ...` does not seem to "await" on the handler function, so when the function is called it runs in paralell with other operations and it becomes a race condition.

**Comment by KevinLuc95** [comment]
I checked again and with my script waitForEvent ('page') run normally in local, it just has the problem when running it on the docker image ```mcr.microsoft.com/playwright:bionic```, whether the problem is coming from docker?

**Comment by pavelfeldman** [comment]
I'm not sure what your expectations are regarding this snippet. You are reloading a page and are expecting a new page to appear? Could you explain what you are trying to do in greater detail?

**Comment by pavelfeldman** [comment]
We need more details in order to be able to address this issue, namely answer to the above. I'll close this bug as non-actionable, but if this still happens to you, could you please file a new issue with the log dump and link this one?

**Comment by KevinLuc95** [comment]
@pavelfeldman thank you for the help, the issue looks like not happen in my script until now, maybe I misunderstanding about waitForEvent
