### ISSUE TITLE
[BUG] Browser is not been fully captured by page.screenshot() with the settings 125% (Recommended) for "Scale and layout" on Windows 10.

### ISSUE THREAD

**Issue by AndrewCore** [microsoft/playwright#5959]
**Context:**
- Playwright Version: 1.9.1
- Operating System:Windows
- Browser: Chromium
- Device: Laptop

**Describe the bug**
page.screenshot() not works well within my laptop by using the system recommended settings "125%" for "Scale and layout" on Windows 10 (Settings > Display), it only captures part of the browser. Please check below attachments for more details.

Also tried with full_page, clip and viewport params, which also not works normally.

It only works normally while I set it to 100%.

Screenshots under 125% (Recommended):
![screenshot under 125%](https://user-images.githubusercontent.com/3733661/112613875-93eec900-8e5b-11eb-9bba-7944291c549d.png)
Screenshots under 100%:
![screenshot under 100%](https://user-images.githubusercontent.com/3733661/112613889-97825000-8e5b-11eb-975a-17427f5c4d3d.png)
System settings:
![Windows settings](https://user-images.githubusercontent.com/3733661/112613956-a963f300-8e5b-11eb-85c8-45246ccb2ba7.png)

**Comment by aslushnikov** [comment]
@AndrewCore could you please try taking a screenshot using Chrome DevTools with the 125% scaling enabled?

1. Open Chrome DevTools
2. Hit "Ctrl-Shift-P"
3. Type "capture screenshot"

This way we'll see if this is an upstream issue or something on the Playwright side.

**Comment by AndrewCore** [comment]
Hi @aslushnikov ,

Just tried the steps as you mentioned above, the "capture screenshot" seems work but one thing I noticed that the "capture screenshot" function of "Chrom Devtools" will only capture the part of screen currently we can see, which means the part has been covered by " Chrome Devtools" sidebar will not been captured.

From below video you can see when I running the page.screenshot(), the layout of page seems changed at 00:04 because something pops out and occupied the places, it seems like the "Devtools", not sure about that.

So it seems the issue has nothing to do with the "Scale and Layout" settings under 125%, when I running it well under 100% just because the page is spacious enough that "Devtools" will not occupy the places

**More information:**
Just test with Firefox with the same method and it works well.

**Video:**
https://user-images.githubusercontent.com/3733661/112821537-656e2980-90b9-11eb-94e7-bba7004ba7e9.mp4

**Screenshot captured**
![test_screeshot](https://user-images.githubusercontent.com/3733661/112824373-08747280-90bd-11eb-8be2-007247f5447a.png)

**Comment by pavelfeldman** [comment]
Could you paste screenshots of some regular sites you don't need to mask? wikepedia, google, webkit.org, any public site?

**Comment by AndrewCore** [comment]
Hi,

Here is th video and captured screenshots for google.


https://user-images.githubusercontent.com/3733661/112922885-d821e800-913f-11eb-91f9-90d3aa316367.mp4

![test_google](https://user-images.githubusercontent.com/3733661/112922892-db1cd880-913f-11eb-961e-b8620ce37068.png)

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
