### ISSUE TITLE
[BUG] Firefox crash with SVG favicon on Win10

### ISSUE THREAD

**Issue by faulpeltz** [microsoft/playwright#5977]
**Context:**
- Playwright Version: v1.10, v1.9.x
- Operating System: Windows 10 64bit
- Node.js version: 14.16 (not relevant for this bug)
- Browser: Firefox
- Extra: Works on Ubuntu 20.04

**Describe the bug**

The bundled firefox version (firefox-1238, and earlier) crashes when using a SVG favicon:

```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="icon" type="image/svg+xml" href="/favicon.svg">
    <title>SVG ICON TEST</title>
  </head>
<body>
  NO TEXT
</body>
</html>
```

```xml
<svg width="32" height="32" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg">
  <style>
  @media (prefers-color-scheme: dark) {
    .dummy { fill: #f22 }
  }
  </style>
  <circle fill="red" cx="16" cy="16" r="12" />
</svg>
```

**Windows event log**
```
Faulting application name: firefox.exe, version: 87.0.0.7746, time stamp: 0x6051c457
Faulting module name: xul.dll, version: 87.0.0.7746, time stamp: 0x6051c464
Exception code: 0xc0000005
Fault offset: 0x00000000034e8512
```

**Notes**
- This happens when running the bundled FF instance manually or from PW
- Does not happen with various "stock" FF nightly/beta/release versions
- Reproducible on multiple Win10 machines with different hardware
- Safe mode does not help
- Headless also does not work
- When running manually the cached svg favicon causes a crash when opening history

**edit**: only crashes with the "prefers-color-scheme" media query, this might be uncommon in favicons - but it *does* cause a hard crash

**Comment by rwoll** [comment]
I've added a test case here and that as a repros: https://github.com/microsoft/playwright/pull/5979. macOS Playwright FF crashes in both headful and headless mode when you run the test while the stock FF does not crash.

**Comment by rwoll** [comment]
I don't yet have a Playwright dev FF setup, but I want to see if we're executing https://github.com/microsoft/playwright/blob/0943af28069774b09dd2481059568072c88cd3dd/browser_patches/firefox/patches/bootstrap.diff#L641 when the SVG loads, and if there's a null pointer or some other crash there.

**Comment by faulpeltz** [comment]
I was able to get a dev FF running (somewhat, it always opens a second "privacy notice" window for me), and could reproduce the crash -- Adding a null pointer check fixes it for me 
```cpp
if (docShell && docShell->...)
```

**Comment by rwoll** [comment]
Sweet, same (minus the privacy notice)! Thanks for giving it a try! 🎉  (See updates in https://github.com/microsoft/playwright/pull/5979 with full patch.) 

(Turns out Firefox only took 47 minutes to build from scratch on my machine; I was expecting it would take the 6+ hours Chromium took, but glad it was faster! 🕐 )
