### ISSUE TITLE
[Feature] Improve Error LOGS for page.waitForResponse(urlOrPredicate[, options]) function (and waitForRequest)

### ISSUE THREAD

**Issue by garciallorente-fer** [microsoft/playwright#5986]
**page.waitForResponse(urlOrPredicate[, options]) returns: <Promise<Response>>, (and waitForRequest)**

The function returns the Response that matches the Predicate passed as an arugment, but if it fails, it does not show any log of what was the URL or Predicate used in the case that it failed. Would be good for Playwright that it logs what was the URL or Predicate used to match a Response that never occured.

It is a problem when you have like 8 waitForResponses in the same Promise.all([]) and then one fails and you dont know which one or why, which ones occured and which ones not, etc.

In addition, would be even nicer to log , or have the possibility to log, what were the Responses that happened when looking for a Response that never returned any match.
That way the developer can see what Response was trying to waitFor and which ones occured while waiting for it when failed.
Would make the life of the Automation Tester much easier and for people reading the failure LOGS easy to understand what failed. At least to have the option to log the XHRequests that occured while doing the page.waitForResponse()

_https://playwright.dev/docs/api/class-page?_highlight=waitforresponse#pagewaitforresponseurlorpredicate-options_

Example of a log failure in my project:

```
TimeoutError: page.waitForResponse: Timeout while waiting for event "response"
    Note: use DEBUG=pw:api environment variable to capture Playwright logs.

      16 |     static async waitForResponseObject<T>(api: API, timeout?: number): Promise<T> {
      17 |         try {
    > 18 |             const response = await page.waitForResponse(
         |                              ^
      19 |                 (response: Response) =>
      20 |                     ApiInterception.urlIncludes(response.url(), api.url, api.searchParams)
      21 |                     && ApiInterception.urlNotIncludes(response.url(), api.avoidParams)

      at node_modules/playwright/lib/client/waiter.js:49:51
      at Waiter.waitForPromise (node_modules/playwright/lib/client/waiter.js:57:28)
      at Page._waitForEvent (node_modules/playwright/lib/client/page.js:350:24)
      at Page._wrapApiCall (node_modules/playwright/lib/client/channelOwner.js:77:28)
      at Function.waitForResponseObject (src/utils/api.utils.ts:18:30)
          at async Promise.all (index 0)
```

For this code:

```
    static async waitForResponseObject<T>(api: API, timeout?: number): Promise<T> {
        try {
            const response = await page.waitForResponse(
                (response: Response) =>
                    ApiInterception.urlIncludes(response.url(), api.url, api.searchParams)
                    && ApiInterception.urlNotIncludes(response.url(), api.avoidParams)
                    && (api.status === response.status() || response.ok())
                , { timeout: timeout ? timeout : this.timeoutApi }
            )
            return await response.json() as T
        } catch (error) {
            error.message = error.message + ' > ' + `${api.url}, ${api.searchParams}, ${api.status}`
            throw error
        }
    }
```

**Comment by pavelfeldman** [comment]
Could you paste the log that you gen when using`DEBUG=pw:api` and provide additional information on what is missing? I ask because I think we are already logging all the information you are requesting.

**Comment by garciallorente-fer** [comment]
Thanks for the answer. When using **$env:DEBUG="pw:api"** , then I can also receive these logs:
```
pw:api <= page.waitForResponse failed +3ms
  pw:api <= page.waitForResponse failed +5ms
  pw:api <= page.waitForResponse failed +3ms
  pw:api <= page.waitForResponse failed +3ms
```
  **But still no more info**, It would be good if without using the DEBUG=pw:api , the logs already show the Response that failed, like when using waitForSelector shows the selector that was not visible or not enabled etc.

Also I ask the request to have it without DEBUG=pw:api, because the idea is to be able to run in in the cloud, using CI, so the logs already log all the info about the failure without having to use that and wihtout loosing time investigating what happened
  
  I tried to get the info myself but the only way I can log it is using console.log() at the moment which is not ideal, as I cant seem to be able to pass the info through the error.message
  
```
static async waitForResponseObject<T>(api: API, timeout?: number): Promise<T> {
        const allResponses = []
        try {
            const response = await page.waitForResponse(
                (response: Response) => {
                    if (!ApiInterception.urlIncludes(response.url(), api.url, api.searchParams)
                        && !ApiInterception.urlNotIncludes(response.url(), api.avoidParams)
                        && !(api.status === response.status() || response.ok()) && allResponses.push(response)) {
                        return true
                    }
                    ApiInterception.urlIncludes(response.url(), api.url) && allResponses.push(response.url())
                }, { timeout: timeout ? timeout : this.timeoutApi }

            )
            return await response.json() as T
        } catch (error) {
            console.log(`ERROR> ${api.url}, ${api.searchParams}, ${api.status}`)
            console.log(allResponses)
            error.message = error.message + ' > ' + `${api.url}, ${api.searchParams}, ${api.status}`
            throw error
        }
    }
```

**Comment by pavelfeldman** [comment]
> But still no more info

What is your Playwright version? I am getting the following:

```
  pw:api => page.waitForResponse started +0ms
  pw:api   waiting for response "http://my-url-i-am-waiting-for" +2ms
```

> Also I ask the request to have it without DEBUG=pw:api, because the idea is to be able to run in in the cloud, using CI,

All the CIs allow specifying the environment variables, typically using `env:` keyword. We assume you can configure steps in your CI like this: 

```yml
env:
  DEBUG: pw:api
```

As a result, users that would like to see logs have them and those that don't have clear log.

**Comment by garciallorente-fer** [comment]
I am using the last version of PlayWright, 1.10.0, but as you can see in my code, I dont look for a specific URL but for certain conditions to be matched with the response, therefore I cant see the URL that has failed in case, as I imagine you get that info because you use the function .waitForResponse using a string URL as a parameter

**Comment by dgozman** [comment]
> I am using the last version of PlayWright, 1.10.0, but as you can see in my code, I dont look for a specific URL but for certain conditions to be matched with the response, therefore I cant see the URL that has failed in case, as I imagine you get that info because you use the function .waitForResponse using a string URL as a parameter

You are right, we are not printing anything when you pass the predicate.

> But still no more info, It would be good if without using the DEBUG=pw:api , the logs already show the Response that failed, like when using waitForSelector shows the selector that was not visible or not enabled etc.

What do you want to see exactly? I have some ideas but they seem to be not ideal:
- Print `predicate.toString()`. This is very verbose, I am not sure every user wants that.
- Print all responses as they happen. Again, very verbose. You can do that yourself with `page.on('response', console.log)`.

The way you `console.log` when the error happens looks good - you print exactly the information you'd like to see. We use a bit more elaborate way to rewrite error messages, you can take a look [here](https://github.com/microsoft/playwright/blob/master/src/utils/stackTrace.ts#L29-L37), but your code looks good anyway.

Overall, if you have any specific idea of what to print in this case, we are happy to help!

**Comment by dgozman** [comment]
Closing this one as there is no action item here. If you have any ideas on what exactly would be helpful to see in the logs, please comment here, and we'll reopen.
