### ISSUE TITLE
 SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by stefanstranger** [microsoft/playwright#600]
I'm getting the following error:

UnhandledPromiseRejectionWarning: Error: Navigation to https://stranger.nl/ failed: SSL peer certificate or SSH remote key was not OK.

Is there an option or configuration to disable SSL verification? But to my knowledge my website has a valid SSL certificate.

/Stefan

**Comment by JoelEinbinder** [comment]
I assume this is with webkit on linux? I get an https error for your site when I try to view it in [GNOME Web](https://en.wikipedia.org/wiki/GNOME_Web). Playwright successfully found a cross browser error for you! :)

More seriously, I assume our linux webkit is using different root certificates than iOS/Mac webkit. I don't see an error with your site when I view it from an iPhone. Maybe we can add some certificates to more closely match the Safari experience.

**Comment by pavelfeldman** [comment]
You can try [ignoreHTTPSErrors](https://github.com/microsoft/playwright/blob/master/docs/api.md#browsernewcontextoptions) as a workaround while we are figuring the CAs out.

```js
const { webkit } = require('playwright');

(async () => {
  const browser = await webkit.launch();
  const context = await browser.newContext({ ignoreHTTPSErrors: true });
  const page = await context.newPage('https://stranger.nl/');
  await page.screenshot({ path: 'stranger.png' });
  await browser.close();
})();
```

**Comment by pavelfeldman** [comment]
Also, to Joel's point, I just tried it with stock Firefox on Windows and it did not like the certificate either!

<img width="473" alt="Screen Shot 2020-01-24 at 8 05 25 PM" src="https://user-images.githubusercontent.com/883973/73116067-2b1d6100-3ee5-11ea-8ad0-f2e03c835148.png">

**Comment by stefanstranger** [comment]
Well it's just a Lets Encrypt certificate.  And wel I check the cert in Edge its OK.

**Comment by aslushnikov** [comment]
@stefanstranger  So to summarize:
- certificate works on Chrome/ Edgium
- certificate doesn't work on Firefox

And similar situation is with playwright:
```js
const { chromium, webkit } = require('playwright');

(async () => {
  for (const type of [chromium, firefox]) {
    const browser = await type.launch();
    const context = await browser.newContext();
    const page = await context.newPage('https://stranger.nl/').catch(e => null);
    console.log(`Loaded: ` + (page ? 'YES' : 'NO')); // YES for chromium, NO for firefox
    await browser.close();
  }
})();
```

PlayWright is consistent with what I see as a user. Which sounds great to me!

Closing this; let us know if we missed something here!
