### ISSUE TITLE
[Question] Is it possible to get access to raw chrome DevTool api?

### ISSUE THREAD

**Issue by zdm** [microsoft/playwright#6000]
I need to override not only `userAgent` but also `platform`.
This is possible in `Network.setUserAgentOverride` call, but I am unable to find possibility to performs such calls directly.

**Comment by mxschmitt** [comment]
Yes it is using [`chromiumBrowserContext.newCDPSession(page)`](https://playwright.dev/docs/api/class-chromiumbrowsercontext#chromiumbrowsercontextnewcdpsessionpage) there you can interact with the CDP directly.

**Comment by zdm** [comment]
Thanks, I will try.
