### ISSUE TITLE
[Question] Session storage for browserContext.storageState

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright#6006]
According to the docs at https://playwright.dev/docs/api/class-browsercontext#browsercontextstoragestateoptions it does not save session storage, only local storage. What is the reason behind this? It feels like I am missing something obvious.

**Comment by pavelfeldman** [comment]
> is not persisted across page loads.

Yes, it probably should say across pages.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
