### ISSUE TITLE
[Feature] closest or ancestor engine

### ISSUE THREAD

**Issue by srguiwiz** [microsoft/playwright#6015]
Proposed is a `closest` or `ancestor` engine for going upwards until a CSS match, using JavaScript closest https://developer.mozilla.org/en-US/docs/Web/API/Element/closest .

It should be usable like

``` javascript
await page.click(":text-matches('^barbecue','i') >> closest=.MuiGrid-root >> button:has-text('Yes')");
```

or

``` javascript
await page.click(":text-matches('^barbecue','i') >> ancestor=.MuiGrid-root >> button:has-text('Yes')");
```

Use case are React created HTML element subtrees.  Example is from Material-UI.

Aware of

``` javascript
await page.click(".MuiGrid-root:has(:text-matches('^barbecue','i'))");
```

but that picks the outermost.

What a test author does, or would do, is find something that can be matched, a label, text, the content of span, and then we recongize we need an ancestor, often a `div` with a certain `class`, that contains an `input` element, a `div`, or something else to `click` on, or to `fill` with text, or to `type` into.

It may be worth noting, the traversal of DOM with JavaScript and CSS in order to click on an element for automation doesn't have the same concerns as CSS for applying styles.  Meaning, for CSS for style there probably have been good reasons, some related to performance, not to allow going up to an ancestor like this.  Meaning, it is okay to be different here.

**Comment by pavelfeldman** [comment]
What is wrong with the one below?
```
.MuiGrid-root:has-text('barbecue') button:text('Yes')
```

**Comment by srguiwiz** [comment]
When there are nested `.MuiGrid-root` it picks the outermost `.MuiGrid-root` when the user really wants the one closest to the text because that's where the elements are that matter.

**Comment by srguiwiz** [comment]
As a workaround, meanwhile in our fixture we are getting this via

``` javascript
const ancestorEngine = () => ({
  query(root, selector) {
    return root.closest(selector);
  },
  queryAll(root, selector) {
    const closest = root.closest(selector);
    return closest ? new Array(closest) : new Array;
  }
});
playwright.selectors.register("ancestor", ancestorEngine);
```

**Comment by pavelfeldman** [comment]
Got it.

**Comment by dgozman** [comment]
@srguiwiz Do you specifically need "DOM ancestor", or perhaps the "Yes button near the barbecue" works for you? In the latter case, [using `:next()`](https://playwright.dev/docs/selectors#selecting-elements-based-on-layout) might work: `button:has-text('Yes'):near(:text-matches('^barbecue','i'))`. Note that it is currently limited to the distance of 50px, but we can make that configurable.

**Comment by srguiwiz** [comment]
The problem with `:near()` would be in responsive design.  Two containers (each by itself being a `.MuiGrid-root` and together in a larger whole-form `.MuiGrid-root`) when on a narrow phone-like screen could be above each other instead of to the side of each other.  Then, pixel proximity could be closer to an item in the neighboring `.MuiGrid-root` rather than within its own.

Sure there is `right-of()`, `left-of()`, `:above()`, `:below()`, etc..  But, that could change too with responsive desgin.  And, some layouts are flipped in international markets.

Containment per DOM is most constant.

We can survive in our immediate use, per registering above listed workaround.  But, this feature has good purpose.

**Comment by srguiwiz** [comment]
@pavelfeldman Worth thinking a moment whether the name `ancestor` (already has a slightly different meaning in XPath) or `closest` (what to use from JavaScript) is better, or something else.

I'd consciously keep the result identical to JavaScript `closest` because it is well thought out, native, known.

Anyone who doesn't want the element itself to match ever can easily first go to the parent with `>> .. >> ancestor=.MuiGrid-root >>`.  So it is a non-issue that `closest` may return the element itself.

To prevent naming that is non-intuitive by too much contradicting what people are used to, this may be worth asking before implementing.

The problem with naming it `closest` is people could associate that word with various concepts of close.  That could be confusing.  It isn't "next", not a sibling in the tree.  It is "up", upwards in the tree, an ancestor.

In our workaround we chose `ancestor`.  And probably that is good.  Maybe only very few people would feel troubled by a somewhat different meaning in XPath.  My personal past experience in XPath may matter less than how can we make this easy to author.  And, maybe I have to get used to the fact it is called `closest` in JavaScript, and this feature should be called `closest` for consistency?

**Comment by srguiwiz** [comment]
Thinking more about naming.  `closest` may be best for consistency.  The `ancestor` of XPath gives a list, while `closest` from JavaScript using CSS always returns one.  The `ancestor` list in XPath goes from outside to inside.

To solve the problem this feature request is talking about, `closest` from JavaScript, returning one element, searching up in the tree, from inside to outside, gives the answer that is needed.

As much as I would like to explain to other "this picks the closest ancestor that matches the given CSS", the name that is established for that in existing APIs, in JavaScript, that name is `closest`.

While on the topic, I saw the temptation to return more than one, in case more can be found, from `queryAll`, but that would be problematic.  For the intended use cases, sticking with the same functionality as `closest` from JavaScript should be it, with the one possible element, or none, returned from `queryAll` in an array.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by vnesterovsky** [comment]
I have found that one can use css+xpath selectors to achieve the goal, like this:
```typescript
page.locator(":text-matches('^barbecue','i')").
  locator("xpath=ancestor::*[contains(@class, 'MuiGrid-root')]").
  last().
  locator("button:has-text('Yes')").
  click();
```

**Comment by kirilltikhonoff** [comment]
Why not possible to implement a simple method like in cypress? cy.get('header').parent(). It's pretty often case in practice, at least...
