### ISSUE TITLE
[Feature] Remove route handler

### ISSUE THREAD

**Issue by kahoot-karl** [microsoft/playwright#6018]
It's clear that it's possible to add route handlers to intercept requests, etc. https://playwright.dev/docs/api/class-page?_highlight=page.route#pagerouteurl-handler. 

But I don't see a clear way to remove this handler afterwards. Use case: route handler is specific for a test and should not be active afterwards

**Comment by mxschmitt** [comment]
To remove a route, you can use Page.unroute or Context.unroute, see here: https://playwright.dev/docs/api/class-page#pageunrouteurl-handler

> Use case: route handler is specific for a test and should not be active afterwards

It's recommended to use a new Context for each test, this will have clean routes.
