### ISSUE TITLE
[Feature] Allow to route once time only

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#6027]
Other testing frameworks (e.g. Cypress) have it per default activated to route only a single time on a request.

Example TBD implementation:

```js
await page.route('**/my/great/api', route => {
  route.fulfill({
    status: 404,
    contentType: 'text/plain',
    body: 'Not Found!'
  });
}, { times: 1 });
```

**Comment by klhex** [comment]
Why restrict it to "once"? Why not outright adding a property that allows to specify the number of times a route should be executed?
