### ISSUE TITLE
[BUG] Dialog flickering

### ISSUE THREAD

**Issue by VikramTiwari** [microsoft/playwright#6028]
**Context:**
- Playwright Version: v1.10.0
- Operating System: Mac
- Node.js version: 14.x
- Browser: Chrome 89
- Extra: connectOverCDP

**Code Snippet**

```javascript
const { chromium } = require("playwright");

(async () => {
	const browser = await chromium.connectOverCDP({
		wsEndpoint: `ws://localhost:24362/devtools/browser/1d790f73-6601-4239-bca7-da860a1b81d3`,
	});
	const page = await browser.newPage();
	await page.goto("https://playwright.dev");
	// page.on(`dialog`, () => {}); // works
	page.on(`dialog`, function a() {}); // flickers
	page.evaluate(() => {
		alert(1);
	});
})();

```

**Describe the bug**
- Anonymous functions work but named functions cause flicker of the dialog and it goes away

Add any other details about the problem here.
- Works fine with `chromium.launch`
- Haven't tested with connectOverCDP with chromium

**Comment by pavelfeldman** [comment]
I can't explain why this is happening, but I assume that you are connecting to the browser that you launched with launchPersistentProfile, is that correct? In that case both Playwrights are attaching to the page and both Playwrights think they are the only 'controllers'. This isn't a scenario we currently support.

**Comment by pavelfeldman** [comment]
You could try `launchServer` instead of `launchPersistentProfile` when you start your server and see if that helps...

**Comment by VikramTiwari** [comment]
Hey @pavelfeldman I have better repro script

```
const { chromium } = require("playwright");

async function run(browserContext, url, dismiss = true) {
	const page = await browserContext.newPage();
	await page.goto(url);
	await page.goto(`https://playwright.dev`);
	page.on(`dialog`, async (dialog) => {
		if (dismiss) {
			await dialog.dismiss();
		}
	});
	page.evaluate(() => {
		alert(1);
	});
}

(async () => {
	const browser = await chromium.connectOverCDP({
		wsEndpoint: `ws://localhost:12345/devtools/browser/faadbf70-63c5-4b13-805c-da846387efdc`,
	});
	const [browserContext] = browser.contexts();
	await run(browserContext, `chrome://new-tab-page/`, false);
	await run(browserContext, `chrome://new-tab-page/`, true);
})();

```

On run of this, the dialog will flicker on the second page.

To answer your other questions I am launching my normal chrome with `--remote-debugging-port=12345` from command line and then using playwright with it to connect and run scripts. Assuming this is same as `launchPersistentContext`.

**Comment by pavelfeldman** [comment]
This looks as expected, dialog is shown and then it is dismissed, as programmed, so it flickers.

**Comment by VikramTiwari** [comment]
@pavelfeldman Ah! My bad on the repro steps. Both of the calls to run should be set as false.

```js
const { chromium } = require("playwright");

async function run(browserContext, url, dismiss = true) {
	const page = await browserContext.newPage();
	await page.goto(url);
	await page.goto(`https://playwright.dev`);
	page.on(`dialog`, async (dialog) => {
		if (dismiss) {
			await dialog.dismiss();
		}
	});
	page.evaluate(() => {
		alert(1);
	});
}

(async () => {
	const browser = await chromium.connectOverCDP({
		wsEndpoint: `ws://localhost:12345/devtools/browser/faadbf70-63c5-4b13-805c-da846387efdc`,
	});
	const [browserContext] = browser.contexts();
	await run(browserContext, `chrome://new-tab-page/`, false);
	await run(browserContext, `chrome://new-tab-page/`, false);
})();
```
This will cause the dialog to go away from both the pages. On second page, it appears for a second and then goes away.

**Comment by pavelfeldman** [comment]
Can't repro, I see dialogs in place. The only explanation to dialogs auto-closing is that you did not actually run Chromium manually from the command line.

**Comment by pavelfeldman** [comment]
I'll close this for now, but please feel free to file a new one with the exact repro steps!
