### ISSUE TITLE
[BUG] fonts looks broken inside docker image (playwright:bionic)

### ISSUE THREAD

**Issue by frezot** [microsoft/playwright#6033]
**Context:**
- Playwright Version: doesn't matter
- Operating System: `image: "mcr.microsoft.com/playwright:bionic"`
- Browser: any
- Extra: also reproduced in  `playwright:focal` image

**Code Snippet**

Run in docker 

```javascript
  const browser = await playwright["chromium"].launch({ headless: true });
  const context = await browser.newContext();
  const page = await context.newPage();

  await page.goto(`file:${path.join(__dirname, "test.html")}`);
  const container = await page.waitForSelector("#target_container");
  await container.screenshot({ path: "test-1.png" });
```

where test.html:
```html
<!doctype html>
<html>

<head>
</head>

<body>
    <div id="target_container">
            Just some text with currency (₽) and emoji (🥶)
    </div>
</body>

</html>
```

**Describe the bug**

Actual:
![test-1-indocker](https://user-images.githubusercontent.com/7229738/113281789-3b627480-9310-11eb-8094-8bf757ce57e9.png)
Expected:
![test-1-local](https://user-images.githubusercontent.com/7229738/113281795-3c93a180-9310-11eb-8f5e-e211138983f2.png)

**Comment by mxschmitt** [comment]
Seems like somehow `fonts-noto-color-emoji` got removed from the dependencies.

Could you try install it manually with `apt-get update && apt-get install -y fonts-noto-color-emoji`?

That should fix it.

**Comment by frezot** [comment]
@mxschmitt,  thx for fast answer
after `apt-get update && apt-get install -y fonts-noto-color-emoji`
I get
![test-1](https://user-images.githubusercontent.com/7229738/113282803-a3658a80-9311-11eb-9599-1c43f300f187.png)

So it fixed just a part of problem

**Comment by mxschmitt** [comment]
@frezot I've created a patch which fixes it. To also have the unicode characters in place, you have to install them with `apt-get install -y ttf-unifont`
