### ISSUE TITLE
[Feature] Link to docs page when "Unable to open X display" gets logged.

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#6037]
Link to that: https://playwright.dev/docs/ci#running-headful

Relates to https://github.com/microsoft/playwright-python/issues/607

Would probably help users that they fix it themselves instead of opening an issue.

(not sure if the output on all the browsers is the same.)

**Comment by mxschmitt** [comment]
Maybe `xvfb-run` should be integrated into Playwright when using headful? That would add more magic but also more comfort to the user-experience.

**Comment by dgozman** [comment]
@yury-s, what do you think about this?

**Comment by mxschmitt** [comment]
Linking https://github.com/microsoft/playwright/issues/8393

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by SgtPooki** [comment]
Not needing any action from playwright here, but FYI that playwright, service workers, and iframes caused me a lot of pain in https://github.com/ipfs-examples/js-ipfs-examples/pull/527 and I had to remove the iframes entirely to get CI to pass in github CI. If anyone knows a solution that I missed, please update me =)
