### ISSUE TITLE
[Question] Is it possible to start chromium with network throttling (3g slow) mode ?

### ISSUE THREAD

**Issue by petriichuk** [microsoft/playwright#6038]
I need to imitate slow connection in my autotests, is it technically possible?

**Comment by pavelfeldman** [comment]
We don't support this at the moment. You can defer your network via awaiting time in `page.route` as a quick and dirty solution:

```js
await page.route('**/*', async route => {
  await new Promise(f => setTimeout(f, 100));
  await route.continue();
});
```

That won't be accurate in terms of latency and throughput, but you can simulate delays in network responses that way.

**Comment by petriichuk** [comment]
thanks, but no really helps. I am testing a PWA app, need to catch some background sync problem while the user is navigating between pages

**Comment by pavelfeldman** [comment]
If you need to induce a delay to trigger the race condition, `page.route` is in fact a way to go, slow 3g is not going to help thete. Throttling will make things slow, but it will be non-deteministic and flaky. `page.route` allows slowing down specific requests (navigation request in your case) in a deterministic manner.

**Comment by petriichuk** [comment]
I don't need to slow down navigation requests, it's API sync. I have complex frontend navigation. So, I need to test quik navigating between pages while the API request is not finished. Throttling make slow all background api requests (in my case requests from service-worker)

**Comment by mxschmitt** [comment]
@petriichuk since you asked for Chromium, you can throttle it like via the Chromium DevTools via such an example:

```js
// @ts-check
const playwright = require('playwright');

// Example values
const networkConditions = {
  'Slow 3G': {
    download: ((500 * 1000) / 8) * 0.8,
    upload: ((500 * 1000) / 8) * 0.8,
    latency: 400 * 5,
  },
  'Fast 3G': {
    download: ((1.6 * 1000 * 1000) / 8) * 0.9,
    upload: ((750 * 1000) / 8) * 0.9,
    latency: 150 * 3.75,
  },
};

(async () => {
  const browser = await playwright.chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  const cdpSession = await context.newCDPSession(page)

  await cdpSession.send("Network.emulateNetworkConditions", {
    downloadThroughput: networkConditions["Fast 3G"].download,
    uploadThroughput: networkConditions["Fast 3G"].upload,
    latency: networkConditions["Fast 3G"].latency,
    offline: false
  })

  const start = new Date().getTime()
  await page.goto("https://microsoft.com")
  // Shows you that its significant slower when using the throttle
  console.log((new Date().getTime() - start) / 1000)
  await browser.close();
})();
```

References:
- https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-emulateNetworkConditions
- https://playwright.dev/docs/api/class-chromiumbrowsercontext#chromiumbrowsercontextnewcdpsessionpage

**Comment by pavelfeldman** [comment]
@mxschmitt: network throttling on SW should be enabled via the SW session, we do have browserContext.newCDPSession(page), but we don't have it for the service worker, so there is no way to emulate it.

@petriichuk: I don't think we have a good solution for you currently. Throttling (as a variation of timeout) is never the answer, even if you slow down background fetch from the service worker, bg sync will live its own life. It'll race against your page no matter what you do, so the test will fail time to time. The only way to reliably test it is to control the race, as in tell SW to not perform bg sync, perform things that should happen before it does, then unstall it.

**Comment by dgozman** [comment]
There is no action item here, so closing.
