### ISSUE TITLE
[Question] Run inside a browser

### ISSUE THREAD

**Issue by jasonswearingen** [microsoft/playwright#6053]
Hello, is there any docs/guide on how I could run playwright from inside a browser?  Specifically, run playwright in a browser and attach to another browser  (or maybe another tab in the same browser).

If there are no docs, is it at all possible to do so?

Thank you

**Comment by pavelfeldman** [comment]
No, we don't support it out of the box.

**Comment by jasonswearingen** [comment]
okay thank you for the info!
