### ISSUE TITLE
[BUG] Firefox show's network request's status in the video recording (bottom left)

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#6056]
**Context:**
- Playwright Version: 1.10
- Operating System: Linux (linux only tested)
- Node.js version: 15
- Browser: Firefox

**Code Snippet**

Any video recording.

**Describe the bug**

The following messages gets shown:

- `Waiting for <host>`
- `Transferring data from <host>`
- `Looking up <host>`
- `Read <host>`
- `<host>`

Example video:

https://user-images.githubusercontent.com/17984549/113443030-712b5a00-93f1-11eb-938d-ceaabd437c30.mp4

Feel free to close if it's not a bug.

**Comment by yury-s** [comment]
It is expected in headed mode as we simply capture window from the X server. Should not be there in headless.

**Comment by mxschmitt** [comment]
Its headless without xvfb / X server.

**Comment by yury-s** [comment]
ok, apparently we capture the entire[ headless window](http://ffsearch.azurewebsites.net/#path=%2Fhome%2Fjoe%2Fplaywright%2Fbrowser_patches%2Ffirefox%2Fcheckout%2Fwidget%2Fheadless%2FHeadlessCompositorWidget.cpp&line=98) surface after compositing, so it includes whatever overlays may be on top of it. Does it cause any issues? I don't think we need to fix this.

**Comment by mxschmitt** [comment]
It does not, just thought its something which user's don't expect and it's different than in FF compared to WK and CR.

**Comment by JoelEinbinder** [comment]
Closing as a wontfix :)
