### ISSUE TITLE
[Feature] Add context "platform" option

### ISSUE THREAD

**Issue by zdm** [microsoft/playwright#6070]
Hi.

Chrome `Emulation.setUserAgentOverride` devtools call supports `platform` option.
Is it possible to add this option to the new context constructor options, in order to have this setting applied automatically to all pages, opened by thus context?

**Comment by pavelfeldman** [comment]
Could you share more about your use case?

**Comment by zdm** [comment]
To override userAgent for chromium playwright uses `Emulation.setUserAgentOverride` call.
https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setUserAgentOverride

This call supports additional `platform` option, that allows to override `navigation.platform`. In our case we need to override platform together with the user Agent to keep them consistent.

So, I am propose to add new `platform` option to context constructor:
```
const ctx = await browser.newContext({
    userAgent: "Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) Version/11.0 Mobile/15A5341f Safari/604.1",
    platform: "iPad",
});
```

**Comment by pavelfeldman** [comment]
I understand that I was curious about your use case that requires it. What is your setup?

**Comment by zdm** [comment]
We need stealth mode, when we overriding user agent we need to override 
platform too, because in our case we become detected as bot.

**Comment by zdm** [comment]
Also, could you, pls, take a look at issue https://github.com/microsoft/playwright/issues/6026 again?
I found the way to reproduce it.
For me it appears every time, when I run script.
Is it possible to update exports to the new rules? I tested new syntax and it works in `lts` and `latest` releases.
Thank you.

**Comment by pavelfeldman** [comment]
We don't prioritize features for scrapers and spammers - if property decided to detect bots, we respect their choice. At the same time, you can use https://playwright.dev/docs/api/class-chromiumbrowsercontext#chromiumbrowsercontextnewcdpsessionpage to issue arbitrary cdp commands should you choose to.

**Comment by ccll** [comment]
> We don't prioritize features for scrapers and spammers - if property decided to detect bots, we respect their choice

Respect to you for the choice, it's very reasonable.

But the situation may have changed in the last 2 years, we are in the cyber-security business that offer software to check if an URL links to phishing websites, using automated browsers of cause, nowadays we are seeing more and more phishing sites are using bot detection to evade security checks, so beside the traditional benign sites vs. scrapers game, now we have this new kind of malicious sites vs. security guard game.

Maybe time to re-consider the choices?
