### ISSUE TITLE
How to preform touch events?

### ISSUE THREAD

**Issue by ccpu** [microsoft/playwright#6072]
Apparently  playwright only supports tab on touchscreen, but how other touch events such as touchmove, touchend and touchcancel can be simulated?

**Comment by soulchainer** [comment]
@ccpu I think (not tried) you can do it with `elementHandle.dispatchEvent('eventType')`. Check the [`elementHandle.dispatchEvent` in docs](https://playwright.dev/docs/api/class-elementhandle#elementhandledispatcheventtype-eventinit).

**Comment by ccpu** [comment]
@soulchainer indeed dispatchEvent is the solution, i have forgotten about that, thank you.

 [Here is the implementation](https://github.com/ccpu/storybook-addon-playwright/blob/master/src/page-extra/utils/dispatch-touch-event.ts) if someone needed.
