### ISSUE TITLE
Worker Terminated? [Question] 

### ISSUE THREAD

**Issue by russellg** [microsoft/playwright#6073]
Intermittently I receive this error message. I am not sure what the exact cause is. I think I have narrowed it down to either being caused by file uploads or opening an extra browser window. However I cannot be sure.

This is the error from the terminal after running the test:

```
Worker was terminated

      at w (https:/cdnjs.cloudflare.com/ajax/libs/pdf.js/2.5.207/pdf.worker.min.js:22:3152)
      at https:/cdnjs.cloudflare.com/ajax/libs/pdf.js/2.5.207/pdf.worker.min.js:22:8677 
```

Has anyone else experienced this?

Playwright version: 1.10.0 (but also occurred in 1.8)

**Comment by pavelfeldman** [comment]
Could you give us a better idea on your test? What it does, how you run it, etc. A code snippet would be best.

**Comment by russellg** [comment]
Hi @pavelfeldman - Here is a snippet of the test that is intermittently failing:

```typescript
test("Documentation Page (post-submission) Upload Documents (PDF & JPEG formats)", async () => {
    await postDoc.academicUpload(
      [
        "C:/projects/gemsas/src/util/upload/pdf_test_1.pdf",
        "C:/projects/gemsas/src/util/upload/jpg_test_1.jpg",
      ],
      [
        "C:/projects/medical/src/util/upload/pdf_test_2.pdf",
        "C:/projects/medical/src/util/upload/jpg_test_2.jpg",
      ]
    );
  });
```

I am using POM - so here is the code from the postDoc.academicUpload function:

```typescript
async academicUpload(upload1: any, upload2: any) {
    await this.page.click("text=Upload Documents Now");

    await this.page.click("//span[normalize-space()='Proceed']");

    let first = await page.$$eval(
      "span.mat-button-wrapper",
      (element: any) => (element[6].innerText = "XXXXX")
    );

    let second = await page.$$eval(
      "span.mat-button-wrapper",
      (element: any) => (element[7].innerText = "YYYYY")
    );

    const [fileChooser] = await Promise.all([
      page.waitForEvent("filechooser"),
      page.click(`text=${first}`),
    ]);

    await fileChooser.setFiles(upload1);

    const [fileChooser2] = await Promise.all([
      page.waitForEvent("filechooser"),
      page.click(`text=${second}`),
    ]);
   
    await fileChooser2.setFiles(upload2);

    await this.page.click("text=/.*Upload all.*/", {
      waitUntil: "networkidle",
    });
  }
```

**Comment by JoelEinbinder** [comment]
pdfjs is running inside your page right? It looks like an error from inside pdfjs. Does it happen without playwright? Open the devtools console -> perform these steps manually -> see if the error appears in the console.

**Comment by russellg** [comment]
@JoelEinbinder - error does not appear in the console nor under sources. Asked a dev and he said pdf.js was not part of the app either (however he may be wrong but I have to assume he is correct here).

Could this issue actually be related to Playwright? I don't want to take up peoples time here if this is a more generic issue.

**Comment by JoelEinbinder** [comment]
Is this in firefox?

**Comment by russellg** [comment]
@JoelEinbinder - Ignore my above post. I did some more digging and it looks like it's part of Angular: [https://imgur.com/a/C7TzY4P](url)

On this particular page we have a hyperlink that allows someone to click a link to see PDFs they have previously uploaded.

Now I need to find out why it causes an error in the test.

**Comment by JoelEinbinder** [comment]
I'm going to consider this a victory for testing since the error comes from the page. :)

If you figure out more details and it looks like it is a playwright bug, feel free to refile with more info.
