### ISSUE TITLE
[BUG] $$eval('[array-item]', (el) => el) -> returns undefined

### ISSUE THREAD

**Issue by burritoIand** [microsoft/playwright#6087]
I just upgraded to version 1.10.0 from 1.1.0 and previously working tests broke due to the following:
```
      const items = await page.$$eval('[data-test-item]', (el) = el);
      
      assert.equal(items.length, 1); // items is undefined
```
shows: `items is undefined`

If I inspect inside the $$eval's pageFunction, I see that `el` is indeed the correct value, so it seems like it's not being properly returned by the promise resolving?

- Playwright Version: 1.10.0
- Operating System: Mac
- Node.js version: 12
- Browser: Chrome
- running tests in mocha

edit: not sure if related? https://github.com/microsoft/playwright/issues/3865

**Comment by pavelfeldman** [comment]
> const items = await page.$$eval('[data-test-item]', (el) = el);

A couple of issues here:
- arrow function is missing > in `el => el`
- code assumes el is element, whereas for $$eval it is array of matching elements
- $$eval returns only serializable values (those that can be JSON-ified)

If all you need is to query elements, you should
```
const items = await page.$$('[data-test-item]');
assert.equals(items.length, 1);
```

**Comment by burritoIand** [comment]
@pavelfeldman ok thanks for clearing that up, I realized the response wasn't serializable as an html element, although it worked in the past for some reason (updating old tests).

thanks
