### ISSUE TITLE
How to open PDF file with playwright?

### ISSUE THREAD

**Issue by Sapkotaanish** [microsoft/playwright#6091]
I want to open PDF file with any of the browser in playwright and take a screenshot or other tasks. Is it possible to do so?

**Comment by JoelEinbinder** [comment]
Unfortunately we only automate web content, not PDFs. This is out of scope of this project.

**Comment by dgtlmoon** [comment]
@JoelEinbinder if someone wanted to write a plugin or something for this, would it be possible? like, do you know what the technical blocks in the way are and could drop a few hints for someone who wanted to go in that direction? :)

**Comment by dgtlmoon** [comment]
@JoelEinbinder https://github.com/microsoft/playwright/issues/7822 reads like its possible?
