### ISSUE TITLE
[BUG] page.fill fails in Github Actions but succeeds locally

### ISSUE THREAD

**Issue by reidbuzby** [microsoft/playwright#6097]
**Context:**
- Playwright Version: 1.10.0
- Operating System: Ubuntu-20.04
- Node.js version: 14
- Browser: Chromium
- Extra: Running Playwright tests on a Github workflow in Github Actions

**Code Snippet**

```javascript
const { chromium } = require('playwright');

describe('Tests', () => {
  /*** SETUP ***/

  let browser;
  
  beforeAll(async () => {
    browser = await chromium.launch({
      headless: true,
      chromiumSandbox: false,
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    });
  });

  afterAll(async () => {
    await browser.close();
  });

  /*** TESTS ***/

  test('Test', async () => {
    const page = await browser.newPage({
      acceptDownloads: true
    });

    await page.goto(URL);

    await page.fill(
      '[data-test-id="userLoginEmail"]',
      '<user_email>'
    );
    await page.fill('[data-test-id="userLoginPassword"]', '<password>');

    await page.click('[type="submit"]');

    const userName = await page.textContent('[data-test-id="<username>"]');
    expect(userName).toBe('<username>');

    /*** CODE THAT FAILS ***/

    await page.fill('[data-test-id="cardInfo-Name"]', '<name>');
    
    ...
  });

});
```
**Describe the bug**

I am running multiple Playwright tests in a Github workflow, and the beginning of all of the tests look like the code snippet above. When I run them locally with `npm`, they all pass 100% of the time. However, when I run them in Github Actions they all fail on the line `await page.fill('[data-test-id="cardInfo-Name"]', '<name>');` with the logs:
```
page.fill: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector "[data-test-id="cardInfo-Name"]"
      selector resolved to visible <input value="" type="text" data-test-id="cardInfo-Name…/>
    elementHandle.fill("Test User")
      waiting for element to be visible, enabled and editable
    element was detached from the DOM, retrying
    waiting for selector "[data-test-id="cardInfo-Name"]"
    ============================================================
```
However, all of the previous lines in the test are executed successfully, including an earlier page.fill. The logs make it seem like the element was once visible, but got detached from the DOM somehow. This made me think it might be something to do with running multiple tests at the same time, but even if I just run a single test in Github Actions, it still fails on the same line. The fact that it succeeds 100% of the time locally, and the earlier actions in the test succeed makes me think this is an issue on your end. Any help would be appreciated, thank you!

**Comment by reidbuzby** [comment]
Seems similar to this issue: https://github.com/microsoft/playwright/issues/5753

**Comment by JoelEinbinder** [comment]
Github actions is usually much slower than whatever local machine you are working on. So its very possible that this is simply a timing issue, where by the time `cardInfo-Name` is searched for, it has already disappeared.

Can you record a [video](https://playwright.dev/docs/1.10.0/videos) while running on github actions? That should provide a better idea about whats really going on. Or take a [screenshot](https://playwright.dev/docs/1.10.0/screenshots) right before the code that fails.
