### ISSUE TITLE
[Feature] Export Playwright script from Power Automate Desktop - Web recorder

### ISSUE THREAD

**Issue by jitterbox** [microsoft/playwright#6099]
Microsoft's **Power Automate Desktop** is now free to all Windows 10 users, and its Web recorder enables rich recording of browser interactions which likely map (almost) directly to Playwright syntax.
![image](https://user-images.githubusercontent.com/6708273/113758635-1f7d1b00-96e2-11eb-86d9-59770443d9b5.png)

Playwright codegen is a great feature, and a much-needed one. However, being Microsoft-owned, Power Automate Desktop is the _perfect_ candidate for an integration/extension project that adds Playwright code generation. We require non-developer resources to record most of our tests, and I suspect there's a very common need for a tool like this to help bridge the coding skill gap, and make it a more compelling choice vs. platforms like Katalon with its recording UI for Selenium.

**Comment by jitterbox** [comment]
[Feature request also posted](https://powerusers.microsoft.com/t5/Power-Automate-Ideas/Add-Playwright-code-generation-to-Power-Automate-Desktop-Web/idi-p/882980#M24894) to Power Automate Community idea exchange.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.

**Comment by rodrigosf672** [comment]
Can we please add this feature to Power Automate? It would be extremely useful and time-saving. Thanks.
