### ISSUE TITLE
[Question] File download during page load

### ISSUE THREAD

**Issue by iamandras** [microsoft/playwright#6101]
Hello :)

I have a URL which starts downloading a file right away.
I would like to write a script which navigates to this URL and download the file.

Something like this:
```
const [ download ] = await Promise.all([
    page.waitForEvent('download'),
    page.goto('/report/download');
]);
```

Is it possible?

Thanks,
Andras

P.S: playwright is amazing. Keep up the good work!

**Comment by yury-s** [comment]
If the navigation turns into download it will be aborted and goto will throw so you need to update your snippet to accommodate that, this snippet should work:
```js
const [ download ] = await Promise.all([
    page.waitForEvent('download'),
    page.goto('/report/download').catch(e => console.log(e))
]);
```

**Comment by iamandras** [comment]
Thanks. It works :)
