### ISSUE TITLE
[Question] Get request response as string

### ISSUE THREAD

**Issue by Suniron** [microsoft/playwright#6104]
Hey there!

How can i get the response as string like in DevTool? I want to get the body without blocking request.

![image](https://user-images.githubusercontent.com/36677774/113777693-b91cea80-972b-11eb-93cf-c475d2327400.png)

I have tried many methods but i'm stucked on this problem 😅.. (i use Typescript Playwright).

Thanks by advance !

**Comment by yury-s** [comment]
Did you try [response.text()](https://playwright.dev/docs/api/class-response?_highlight=response#responsetext) ? If it doesn't work for you, can you share your code snippet?

**Comment by Suniron** [comment]
Sorry it's my bad.
