### ISSUE TITLE
[BUG] Error: Unsupported platform: android

### ISSUE THREAD

**Issue by jsjoeio** [microsoft/playwright#6105]
**Context:**

- System: OS: android
  - Memory: 79.39 MB / 3.57 GB
- Binaries:
  - Node: 14.15.4 - /data/data/com.termux/files/usr/bin/node
  - Yarn: 1.22.10 - ~/dev/code-server/node_modules/.bin/yarn
  - npm: 6.14.10 - /data/data/com.termux/files/usr/bin/npm
- Languages:
  - Bash: 5.1.4 - /data/data/com.termux/files/usr/bin/bash
- Playwright: 1.8.0

**Reproduction**
1. Install [Termux](https://play.google.com/store/apps/details?id=com.termux&hl=en_US&gl=US) on Android phone
2. Install node/yarn and other stuff:
```sh
apt update && apt upgrade
apt install build-essential python git nodejs yarn
```
3. Run `yarn install` in a project using `playwright` i.e. code-server

**Describe the bug**

```js
error /data/data/com.termux/files/home/dev/code-server/test/node_modules/playwright: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /data/data/com.termux/files/home/dev/code-server/test/node_modules/playwright
Output:
/data/data/com.termux/files/home/dev/code-server/test/node_modules/playwright/lib/utils/browserPaths.js:133
    throw new Error('Unsupported platform: ' + process.platform);
    ^

Error: Unsupported platform: android
    at cacheDirectory (/data/data/com.termux/files/home/dev/code-server/test/node_modules/playwright/lib/utils/browserPaths.js:133:11)
    at /data/data/com.termux/files/home/dev/code-server/test/node_modules/playwright/lib/utils/browserPaths.js:139:36
    at Object.<anonymous> (/data/data/com.termux/files/home/dev/code-server/test/node_modules/playwright/lib/utils/browserPaths.js:140:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/dev/code-server/test/node_modules/playwright/lib/install/installer.js:25:22)
```

**Comment by pavelfeldman** [comment]
See https://playwright.dev/docs/api/class-android. Playwright works with the phone over the wire, you don't need to install it on the phone.

**Comment by jsjoeio** [comment]
Oh that's awesome! Good to know.

Although my use case might be a little different. I'm trying to  debug an issue that happens with our project when running it in Termux on an Android phone. See [issue](https://github.com/cdr/code-server/issues/3036). 

I don't plan to actually run the tests on the device, but running `yarn install` on my Android shouldn't exit and fail the dependency installation, should it? I feel like a warning would be better suited i.e.

"WARNING: `playwright` doesn't currently support your platform: `android`"

**Comment by JoelEinbinder** [comment]
We don't know what browser to download, so you get that error. You can use the environment variable `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1` to skip that step and get playwright without browsers. See https://playwright.dev/docs/installation#skip-browser-downloads

**Comment by Jobians** [comment]
Solution 
https://github.com/Jobians/playwright-termux
