### ISSUE TITLE
[BUG] Missing lib libxtst.so.6 in mcr.microsoft.com/playwright

### ISSUE THREAD

**Issue by thewizarodofoz** [microsoft/playwright#6117]
Getting an error when trying to run playwright:
```
Error: browserType.launch: Host system is missing dependencies!
Missing libraries are:  libxtst.so.6
```

This is the dockerfile:
```
FROM mcr.microsoft.com/playwright:bionic as base

USER root

RUN npm install -g yarn

WORKDIR /e2e

COPY package.json yarn.lock .npmrc tsconfig.json ./
RUN yarn --frozen-lockfile
COPY . .

ENTRYPOINT [ "yarn", "test:cj" ]
```

It used to work until very recently, nothing has changed on our side.

I also tried the `mcr.microsoft.com/playwright:focal` image, got the same result.

Adding `RUN apt-get install -y libxtst6` to the dockerfile solves it.

**Comment by JoelEinbinder** [comment]
@yury-s can you take a look?

**Comment by yury-s** [comment]
You may need to run `docker pull mcr.microsoft.com/playwright:focal` (or `docker pull mcr.microsoft.com/playwright:bionic` respectively) to update the image to the most recent one.

Which browser and which playwright version is this? It works fine for me with the following simple script:

```js
const playwright = require('playwright');

(async () => {
    for (const browserName of ['chromium', 'webkit', 'firefox']) {    
        const browser = await playwright.firefox.launch();
        const context = await browser.newContext();
        const page = await context.newPage();
        await page.goto('https://example.com');
        console.log(`${browserName}: ${await page.evaluate(() => location.href)}`);
        await browser.close();
    }
})();
```

Can you share a repro?

**Comment by zlk89** [comment]
I got the same issue, bumping the playwright version fixes the issue

**Comment by mxschmitt** [comment]
The internal Playwright tests run on Docker daily which are [passing](https://github.com/aslushnikov/devops.aslushnikov.com/runs/2323488906?check_suite_focus=true): Also its recommended to pin the Docker image to a specific Playwright version, see [here](https://playwright.dev/docs/next/docker#pull-the-image). Without a reproducible its hard to debug and the cause is probably a Docker image which is outdated and locally cached.

**Comment by dgozman** [comment]
@thewizarodofoz Did you try pulling a new image and [pinning the version](https://playwright.dev/docs/next/docker/#pull-the-image)? Did it help?

**Comment by thewizarodofoz** [comment]
Sorry for being unresponsive, I'll try everything you mentioned and update as soon as I can.

**Comment by thewizarodofoz** [comment]
OK so pinning the version to `mcr.microsoft.com/playwright:v1.10.0-focal` solved it.
Thanks for the help.
