### ISSUE TITLE
[BUG] Documentation API Reference doesn't match typings

### ISSUE THREAD

**Issue by dilame** [microsoft/playwright#6120]
**Context:**
- Playwright Version: 1.10.0

**Describe the bug**

Your [API reference](https://playwright.dev/docs/api/class-page) declares all your API entities as classes, but your [types.d.ts](https://github.com/microsoft/playwright/blob/master/types/types.d.ts#L74) declares the same entities as interfaces.

**Comment by JoelEinbinder** [comment]
Duplicate of #3978
