### ISSUE TITLE
[BUG] Firefox/Nightly is crushing

### ISSUE THREAD

**Issue by Xezed** [microsoft/playwright#6132]
I have problems with Nightly again. Maybe your experience can help?

```
describe('Opportunities tests', function () {
  it('should work properly', async () => {
    await page.waitForTimeout(50000000)
  });
});
```
```
aleksandr@aleksandr-desktop:~/work/acceptance_tests$ DEBUG=pw:api npm run test
> acceptance_tests@ test /home/aleksandr/work/acceptance_tests
> jest --forceExit --maxWorkers=2

  pw:api => browserType.connect started +0ms
  pw:api <= browserType.connect succeeded +10ms
  pw:api => browser.newContext started +0ms
  pw:api <= browser.newContext succeeded +7ms
  pw:api => browserContext.newPage started +0ms
  pw:api   navigated to "about:blank" +691ms
  pw:api   navigated to "about:blank" +43ms
  pw:api <= browserContext.newPage succeeded +4ms
  pw:api => page.waitForTimeout started +1s
  pw:api   navigated to "http://localhost:8080/log-in" +12s
  pw:api   "domcontentloaded" event fired +1s
  pw:api   "load" event fired +447ms

 RUNS   browser: firefox  tests/opportunities.test.js
 ```
I go manually to `localhost:8080` it loads some html and fails. Browser is crushing. How to debug? Other engines are fine.

I had some weird problem there: #5684.
It wasn't solved due to lack of need in Firefox engine. But now I need it. Seems like problem in our site. Other ones not crushing anything. 

Problem still persists in Docker (with your image of course).

**Comment by Xezed** [comment]
```
aleksandr@aleksandr-desktop:~/.cache/ms-playwright/firefox-1238/firefox$ ./firefox
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
Exiting due to channel error.
Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: Receive IPC close with reason=AbnormalShutdown (t=21.6187) Exiting due to channel error.
Segmentation fault (core dumped)
aleksandr@aleksandr-desktop:~/.cache/ms-playwright/firefox-1238/firefox$ 
```
Maybe it will help

**Comment by Xezed** [comment]
Firefox (not Nightly) is working just fine. 
What was the motivation behind this unstable pick? Just curios.

**Comment by Xezed** [comment]
https://beta.recallmasters.com/ this is our site. You can test it in Nightly by yourself.

**Comment by aslushnikov** [comment]
@Xezed oh, could you please try running with `playwright@next`?  I think this should be fixed.

> What was the motivation behind this unstable pick? Just curios.

We're currently working against firefox beta - which is, well, beta. We'll have Firefox stable channel some time soon (I'm working on it).

**Comment by Xezed** [comment]
@aslushnikov spasibo dyad' :) It's working just fine with @next.
