### ISSUE TITLE
[BUG] Xpath start with dot (.//) not recognized as valid selector

### ISSUE THREAD

**Issue by mostor-v** [microsoft/playwright#6139]
Playwright Version: 1.10.0
Operating System: Windows
Node.js version: v12.20.0
Browser: at least Chromium and Firefox

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const element: ElementHandle = page.$("//form[@id='new_issue']");
// And then search in this element
const childElement: ElementHandle = element.$(".//input");
```

**Describe the bug**

Selector starts with dot not recognized as xpath locator.
This needed to search elemnt from another element

**Comment by JoelEinbinder** [comment]
We autodetect xpath for `//`, but for other xpath you can do `element.$("xpath=.//input")`. This is for compatibility with css selectors, which will start with "." for class selectors.
