### ISSUE TITLE
[BUG] Webkit doesn't work on Linux Red Hat 8

### ISSUE THREAD

**Issue by mcmaclachlan** [microsoft/playwright#6140]
**Context:**
- Playwright Version: 1.10
- Operating System: Red Hat Enterprise Linux 8.3 
- Node.js version: v14.16.0
- Browser: WebKit
- Extra: [any specific details about your environment]

**Code Snippet**

const { webkit } = require('playwright');

(async () => {
  const browser = await webkit.launch({
    headless: false
  });
  const page = await browser.newPage();
  await page.goto('http://whatsmyuseragent.org/');
  await page.screenshot({ path: `example.png` });
  await browser.close();
})();

**Describe the bug**

pw:protocol SEND ► {"id":1,"method":"Playwright.enable"} +0ms
  pw:browser [pid=4013250][err] /uio/platon/med-medsekr-u1/marycm/.cache/ms-playwright/webkit-1446/minibrowser-gtk/bin/MiniBrowser: error while loading shared libraries: libvpx.so.6: cannot open shared object file: No such file or directory +

I have installed these packages:
libvpx.i686              1.7.0-8.el8            rhel-8-for-x86_64-appstream-rpms
libvpx.x86_64            1.7.0-8.el8            rhel-8-for-x86_64-appstream-rpms

**Comment by yury-s** [comment]
We only provide Linux builds for Ubuntu 18.04 and 20.04 at the moment. RHEL 8 is not officially supported currently. The most reliable way to run webkit on RHEL would be to build it from sources.

> libvpx.i686 1.7.0-8.el8 rhel-8-for-x86_64-appstream-rpms

[libvpx-1.7.0-8.el8.i686.rpm](https://centos.pkgs.org/8-stream/centos-appstream-x86_64/libvpx-1.7.0-8.el8.i686.rpm.html) provides libvpx.so.5 while webkit requires libvpx.so.6. Note also that the versioning is distribution-specific for libvpx and it may well be two different APIs in Ubuntu and RHEL even though the number matches.

**Comment by yury-s** [comment]
We use [build.sh](https://github.com/microsoft/playwright/blob/master/browser_patches/webkit/build.sh) and all the patches are in that directory too. Basic instructions on how to checkout the sources are [here](https://github.com/microsoft/playwright/tree/master/browser_patches). For the prerequisites see upstream [webkit documentation](https://webkit.org/getting-started/).

**Comment by ikke-t** [comment]
I have an organization I work with, who would want to use this on OpenShift. It would be great if there was RHEL UBI image build for playwright as well in addition to Ubuntu. Problem with ubuntu images often run into issues like ubuntu not having selinux which fail useradd etc random stuff.
