### ISSUE TITLE
[BUG] UnhandledPromiseRejectionWarning in CI logs

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#6144]
**Context:**
- Playwright Version: v1.10.0
- Operating System: Mac
- Node.js version: v15.4.0
- Browser: Webkit
- Extra: Docker image - v1.10.0-focal

**Describe the bug**
Noticed the following logs in Jenkins console output. These logs are only present when a specific test fails and only on webkit browser. 
```
(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 22)
(node:20) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'attribution' of null
    at new SdkObject (/app/node_modules/playwright/lib/server/instrumentation.js:24:40)
    at new Request (/app/node_modules/playwright/lib/server/network.js:83:9)
    at new WKInterceptableRequest (/app/node_modules/playwright/lib/server/webkit/wkInterceptableRequest.js:69:24)
    at WKPage._onRequestWillBeSent (/app/node_modules/playwright/lib/server/webkit/wkPage.js:823:25)
    at WKSession.<anonymous> (/app/node_modules/playwright/lib/server/webkit/wkPage.js:343:100)
    at WKSession.emit (events.js:315:20)
    at /app/node_modules/playwright/lib/server/webkit/wkConnection.js:139:47
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at processImmediate (internal/timers.js:434:9)
```
The playwright logs for test failure are:
Build 1 - page.click: Evaluation failed: Protocol error: Execution context was destroyed, most likely because of a navigation.
Build 2 - page.click: waitForFunction failed: frame got detached.

**Comment by JoelEinbinder** [comment]
@dgozman looks like the frame is null here: https://github.com/microsoft/playwright/blob/f7e7ea93e28f95e14b813fc21d14059617bd03cc/src/server/webkit/wkPage.ts#L899

Should we just swallow the network request or is something deeper broken?

**Comment by dgozman** [comment]
> Should we just swallow the network request or is something deeper broken?

Something's definitely broken, but I don't know whether that's a severe issue.

**Comment by vsravuri** [comment]
I see 'Frame has been detached.' error in Firefox but not in Chrome

frame.click
(text=Content)
— 84ms
waiting for selector "text=Content"
selector resolved to visible <td id="Col4" name="Col4" width="120" align="center"…>…</td>
attempting click action
waiting for element to be visible, enabled and stable
element is visible, enabled and stable
scrolling into view if needed
done scrolling
checking that element receives pointer events at (184.19,56.85)
Frame has been detached.

**Comment by vsravuri** [comment]
@JoelEinbinder 

I noticed this issue in both Webkit and Firefox. Will the fix work for Firefox as well?
