### ISSUE TITLE
[BUG] Not able to check if browser instanceof concrete browser type

### ISSUE THREAD

**Issue by dilame** [microsoft/playwright#6145]
**Context:**
- Playwright Version: 1.10.0

**Code Snippet**

```ts

import { FirefoxBrowser, firefox } from 'playwright';

(async () => {
  const browser = await firefox.launch();
  if(browser instanceof FirefoxBrowser) {...do some firefox-specific stuff...}
})();
```

**Describe the bug**

TypeScript complains

```
TS2693: 'FirefoxBrowser' only refers to a type, but is being used as a value here.
```

**Comment by dilame** [comment]
We can easily fix it by replacing `interface FirefoxBrowser` with `declare class FirefoxBrowser`

**Comment by JoelEinbinder** [comment]
Please stop filing these.

**Comment by JoelEinbinder** [comment]
You keep filing the same issue for something we have made clear we aren't going to do.
