### ISSUE TITLE
[Feature] Test payment card auto-fill

### ISSUE THREAD

**Issue by jperl** [microsoft/playwright#6150]
We would like to test a checkout page to check that auto-fill with a payment card in chrome://settings/payments works.

**Comment by JoelEinbinder** [comment]
This is probably a bit tricky to implement. I think the payment api is not implemented for headless. I agree that its a high value testing target, as I hate when sites don't work with autofill. Maybe instead we can run some kind of validator that verifies the correct autofill attributes are in your html?

**Comment by jperl** [comment]
The validator could work but it would be much nicer to have a true e2e test. FWIW if it were headed only that would be fine.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
