### ISSUE TITLE
[Question] How to run chrome in debug mode from executable path?

### ISSUE THREAD

**Issue by mostor-v** [microsoft/playwright#6158]
In my organization i can't download executable files from internet. Chrome version managed by oraganizationsecurity department.
Playwright works fine on chrome which i passed to executablePath: but in debug mode playwright tries to find executable in path where it should be downloaded by playwright. How can i change executablePath for debug mode? (PWDEBUG=1)

**Comment by yury-s** [comment]
How do you pass executable pass? The following should work fine with `PWDEBUG=1` (just checked locally):
```js
    const browser = await chromium.launch({
        executablePath: '/opt/google/chrome/chrome'
    });
```

**Comment by mostor-v** [comment]
> How do you pass executable path? The following should work fine with `PWDEBUG=1` (just checked locally):
> 
> ```js
>     const browser = await chromium.launch({
>         executablePath: '/opt/google/chrome/chrome'
>     });
> ```

I'm using jest-playwright-preset and specify executablePath in launchOptions in jest-playwright config file

**Comment by JoelEinbinder** [comment]
It looks like we don't respect executable path when launching the recorder.

**Comment by dezsiszabi** [comment]
This still doesn't seem to work for me.

I have `executablePath` in my `playwright.config.ts` file like this:

```
projects: [
  {
    name: 'chromium',
    use: {
      ...devices['Desktop Chrome'],
      launchOptions: {
        env: {
          ...process.env,
          http_proxy: '<redacted>',
          https_proxy: '<redacted>'
        },
        executablePath: '/path/to/chromium/chrome',
        args: [
          '--disable-gpu',
          '--disable-setuid-sandbox',
          '--auth-server-allowlist=<redacted>',
          '--auth-negotiate-delegate-allowlist:<redacted>
        ]
      }
    }
  }
]
```

And when I try running `npx playwright test --project=chromium --debug` I'm getting `No chromium-based browser found on the system.` It works fine without `--debug`.

If I go into `node_modules/playwright-core/lib/server/recorder/recorderApp.js` and remove the `channel` property from the parameter passed to the `recorderPlaywright.chromium.launchPersistentContext` call and manually add `executablePath: '/path/to/chromium/chrome'` then it works fine.

So question is: can `recorderApp.ts` either use a new property to allow specifying a custom executable path it uses or can it be modified to respect the `launchOptions`?
