### ISSUE TITLE
[Feature] Add more info to pw:api log

### ISSUE THREAD

**Issue by mostor-v** [microsoft/playwright#6162]
I suggest to add more debug info to pw:api output.

As i see this log displays enough info for navigation and wait for selector functions
```
pw:api navigated to "http://localhost:" +86ms 
pw:api => page.waitForSelector started +1ms 
pw:api waiting for selector ".awesome-page" to be visible +2ms 
pw:api selector resolved to visible <div class="awesome-page">-</div> +52ms 
pw:api <= page.waitForSelector succeeded +6ms 
```
Can you add same logging info for `$` and `evaluate ` functions ?

**Comment by JoelEinbinder** [comment]
what would you like to see there?

**Comment by mostor-v** [comment]
@JoelEinbinder We have testing with random data, so i don't need to implement loggers to see what playwright tried to search and  what was entered into the fields

**Comment by mostor-v** [comment]
For $ i would like to see which selector we are searching
For evaluate i would like to see function and parameter passed to evaluate
For fill i would like to see selector and text

**Comment by anirudh-modi** [comment]
Hi @JoelEinbinder I would like to take this issue up, if a PR has not been raised against this.. 

Just to clarify the scope of the Pull Request will be limited to 
- For $ i would like to see which selector we are searching
- For evaluate i would like to see function and parameter passed to evaluate
- For fill i would like to see selector and text

Does that sound good?
