### ISSUE TITLE
[Question] How does the driver timestamp correspond to the commit?

### ISSUE THREAD

**Issue by octaltree** [microsoft/playwright#6178]
Hello Playwright team, I'm writing [a Rust binding of Playwright](https://github.com/octaltree/playwright-rust).
It works for now, but I need to adjust the version to write tests.

I get the driver from Azure CDN like playwright-python and playwright-go are doing.
https://playwright.azureedge.net/builds/driver/next/1.11.0-next-{timestamp}-{platform}.zip
There doesn't seem to be any commits that match the timestamp.
Can I assume that all master commits up to the timestamp are included?

**Comment by mxschmitt** [comment]
You can use a version directly which represents a Git commit. For example:

```
https://playwright.azureedge.net/builds/driver/playwright-1.10.0-win32_x64.zip
```

Also each version does also contain the specific commit hash in a file:

```
cat playwright-1.10.0-win32_x64/package/commitinfo
```

Why do you need to adjust the version to write tests?

**Comment by octaltree** [comment]
> `cat playwright-1.10.0-win32_x64/package/commitinfo`

I looked for package.json or something and greped in package, but I missed this. Thank you.

> Why do you need to adjust the version to write tests?

There are some unimplemented parts, including tests, so I'm developing to provide a stable version for the 1.11 release. I didn't want to run into differences in behavior due to version mismatch when writing tests, so I wanted a commit hash for code and tests that was not included in the zip.

Thank you.
