### ISSUE TITLE
[Question] How to check if pop up exists?

### ISSUE THREAD

**Issue by ArmanYeghiazaryan** [microsoft/playwright#6179]
Hello, 

I am working on a Playwright project **in Java** at the moment and would like to know how to check if a captcha **popup** appeared on the current page. (Pop up like in attached image) 
![image](https://user-images.githubusercontent.com/82316190/114301759-727e1600-9ac6-11eb-9424-0be69c772301.png)

Please be so kind and help me out.

**Comment by JoelEinbinder** [comment]
Sorry but this is not the right place to ask about circumventing captchas.
