### ISSUE TITLE
[Question] Wait for pop up in Java

### ISSUE THREAD

**Issue by ArmanYeghiazaryan** [microsoft/playwright#6182]
Hello, 

How can I check if a pop up exists in Firefox? Running Java and the pop up should be detected via keywords. 

Thank you a lot!

**Comment by yury-s** [comment]
You can use [`page.waitForPopup()`](https://playwright.dev/java/docs/api/class-page?_highlight=waitforpopup#pagewaitforpopupoptions-callback) to wait for a new popup like this:

```java
    Page popup = page.waitForPopup(() -> page.evaluate(
      "url => window['_popup'] = window.open(url)", "https://github.com/"));
```

If the page can open multiple popups you can use [`page.onPopup`](https://playwright.dev/java/docs/api/class-page?_highlight=waitforpopup#pageonpopuphandler) to subscribe to all popup events and then filter them by whatever condition you like. There is also context level [`onPage()`](https://playwright.dev/java/docs/api/class-browsercontext?_highlight=context.onp#browsercontextonpagehandler) which can be used to listen to all pages created in the cotnext.

**Comment by ArmanYeghiazaryan** [comment]
Thank you, I have another question. How can I set that waitForSelector() should check every 1000ms, if the selector is available?

**Comment by yury-s** [comment]
> How can I set that waitForSelector() should check every 1000ms, if the selector is available?

There is now way to do that. It will poll on every RAF and return as soon as it is there. Why do you need to change that to time based interval?

In the future please file separate issue for unrelated topics.

**Comment by ArmanYeghiazaryan** [comment]
Sorry, won't happen again! I would like to need that, as I need to monitor if a button exists or not. Is there any possibility to check if a button exists?

**Comment by yury-s** [comment]
> Is there any possibility to check if a button exists?

Yes, you can call [`Page.querySelector`](https://playwright.dev/java/docs/api/class-page?_highlight=querysele#pagequeryselectorselector) which doesn't wait for the selector to resolve. If the button is there it will return it, if not it will give you `null`.

**Comment by ArmanYeghiazaryan** [comment]
Sorry yury-s, but I am still bit unsure... Can you show me once again, how I could wait for an pop-up and once it exists, get its HTML source-code?

Thanks a lot!

**Comment by yury-s** [comment]
Something like this:

```java
Page popup = page.waitForPopup(() -> {
  page.click("a"); // assume it loads the link in a new window
});
System.out.println(popup.innerHTML("body"));
```
