### ISSUE TITLE
[BUG] Chromium crops the screenshot when deviceScaleFactor > 1

### ISSUE THREAD

**Issue by zlk89** [microsoft/playwright#6188]
**Context:**
- Playwright Version: 1.10.0
- Operating System: Mac
- Node.js version: 12
- Browser: Chromium
- Extra: 
Base Docker image: mcr.microsoft.com/playwright:v1.10.0-focal

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const path = require('path');
const Playwright = require('playwright');

(async () => {
  const DEVICE = Playwright.devices['Pixel 2'];
  const browser = await Playwright.chromium.launch({
    args: ['--disable-dev-shm-usage', '--no-sandbox'],
  });
  const context = await browser.newContext(DEVICE);
  await context.addInitScript({
    path: path.resolve(__dirname, 'initScript.js'),
  });
  const page = await context.newPage();
  await page.goto(`https://getbootstrap.com/docs/3.4/examples/non-responsive/`);
  await page.screenshot({ path: './screenshot.png' });
  await browser.close();
})();

```

**Describe the bug**
You can see the screenshot has been cropped:
![image](https://user-images.githubusercontent.com/7234480/114496489-eb6b9380-9bd4-11eb-8269-c4033b075066.png)

If I manually set `deviceScaleFactor` to 1, it then works fine:
```javascript
const path = require('path');
const Playwright = require('playwright');

(async () => {
  const DEVICE = Playwright.devices['Pixel 2'];
  const browser = await Playwright.chromium.launch({
    args: ['--disable-dev-shm-usage', '--no-sandbox'],
  });
  const context = await browser.newContext({
    ...DEVICE,
    viewport: {
      width: Math.round(411 * 2.625),
      height: Math.round(731 * 2.625),
    },
    deviceScaleFactor: 1,
  });
  await context.addInitScript({
    path: path.resolve(__dirname, 'initScript.js'),
  });
  const page = await context.newPage();
  await page.goto(`https://getbootstrap.com/docs/3.4/examples/non-responsive/`);
  await page.screenshot({ path: './screenshot.png' });
  await browser.close();
})();

```
![image](https://user-images.githubusercontent.com/7234480/114602591-a171c480-9c4b-11eb-8ea2-6e49fbc4f3e8.png)

**Comment by Nav-2d** [comment]
Observed the same issue but it is intermittent.

Playwright Version: 1.10.0
Operating System: Mac
Node.js version: v15.4.0
Browser: Chromium
Device - Pixel 2
Docker image: mcr.microsoft.com/playwright:v1.10.0-focal

**Comment by dgozman** [comment]
I bisected this to the upstream Chromium change: https://chromium.googlesource.com/chromium/src/+/cf473da50bad58c644262b91dbb9d51b4ff319fb.

**Comment by zlk89** [comment]
Is this something we should fix in playwright or chromium?

**Comment by dgozman** [comment]
> Is this something we should fix in playwright or chromium?

Probably both. We'll look into this.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
