### ISSUE TITLE
[Question] How can I wait for window.location.reload(true) (full page reload)

### ISSUE THREAD

**Issue by burritoIand** [microsoft/playwright#6194]
I have a test where I log into my app, and then log out. The log out performs a full page reload `window.location.reload(true)`.

I have an important value set in `window.sessionStorage` that I want to verify is removed after log out/page reload.

I tried the following but the value of `storage` is the value from before the reload, however at debugger if I inspect the actual page and do `window.sessionStorage`, I see the correct updated value that I'm trying to assert.
```
      storage = await page.evaluate(() => JSON.stringify(sessionStorage));

      // log out.
      await page.click('[data-test-logout]');
      await page.waitForLoadState();
      await page.waitForSelector('[data-test-is-connected]');

      storage = await page.evaluate(() => JSON.stringify(sessionStorage));

      debugger; // storage is stale

```

**Comment by pavelfeldman** [comment]
note: `page.waitForLoadState` is a noop in your script - it ensures the page is loaded, but it does not know if that is pre- or post-reload page.

If the sessionStorage is stale, it means that evaluation took place before the reload. It means that Playwright could find the data-test-is-connected element on the logout page. If you know that the page performs navigation / reload, you can say

```js
await Promise.all([
  page.waitForNavigation(),
  page.click('[data-test-logout'])
]);
```

Alternatively, wait for some selector / test on the page that would uniquely identify it as a logged-out page.

**Comment by burritoIand** [comment]
hey @pavelfeldman thanks for suggestion, I've tried a few different things along with your suggestion but seem to get errors
```
      // log out.
      await page.click('[data-test-logout]');
      await page.waitForSelector('[data-test-is-authenticated="false"]', { timeout: 10000 }); // signal that page reloaded
      await page.waitForSelector('[data-test-is-connected="true"]');
```

```
     page.waitForSelector: Protocol error (DOM.describeNode): Cannot find context with specified id
=========================== logs ===========================
waiting for selector "[data-test-is-authenticated="false"]" to be visible
  selector resolved to visible <main data-test-app-main="" class="↵    __1770d↵    ↵ …>…</main>
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
```

**Comment by burritoIand** [comment]
FYI this worked:
```
      // log out.
      await page.click('[data-test-logout]');
      await page.waitForFunction(() => document.querySelector(
        '[data-test-is-authenticated="false"]'));
      await page.waitForSelector('[data-test-is-connected="true"]');

```

**Comment by burritoIand** [comment]
closing as I got the above to work
