### ISSUE TITLE
Issues with the filling input field and click on submit button

### ISSUE THREAD

**Issue by enessijaric** [microsoft/playwright#6197]
I have two questions:
1)
HTML:
```<div class="v-text-field__slot"><label for="input-19" class="v-label theme--light error--text" style="left:0px;right:auto;position:absolute;">Email address *</label><input autofocus="autofocus" id="input-19" type="email"></div>```
How to fill input field with email? I tried
  `page.fill('#input-19', 'Peter')`
  but this doesent works

2) How to click on this button by class name?
```
<button class="sign-in-btn" ng-click="vm.signIn('\\',true)">
               Sign In
            </button>
```

I tried 

`await page.click('text=Sign In')`
but I have so many Sign In the text, so it doesn't work?

**Comment by dgozman** [comment]
Closing since there is no action item here. If there is something else to resolve, please comment here and we'll reopen.
