### ISSUE TITLE
[Question] How to wait for several responses that differs only with body?

### ISSUE THREAD

**Issue by Kremliovskyi** [microsoft/playwright#6199]
After clicking button multiple requests to GraphQL are made. URL is the same, only body is different. I tried the following:

```
async uploadFile() {
    const [fileChooser] = await Promise.all([
        this.page.waitForEvent('filechooser'),
        this.page.click(this.elements.csvInput)
    ]);
    await fileChooser.setFiles('./resources/upload_findings.csv');
    await this.page.click(this.elements.uploadButton);
}

async function waitForFindingUpload(page, findingName) {
    return await page.waitForResponse(async (response) => {
        let body = await response.text();
        return body.includes(findingName)
    }, {
        timeout: 10000
    });
}
const [response1, response2] = await Promise.all([
    waitForFindingUpload(page, "Name of Finding 1"),
    waitForFindingUpload(page, "Name of Finding 2"),
    uploadFindingsPage.uploadFile()
])
```
These response1, response2 are both either "Name of Finding 1" or "Name of Finding 2". I can not get both responses. 
How can I do this ?

**Comment by dgozman** [comment]
I think the issue here is that `waitForResponse` does not support an async predicate. So it treats the returned promise as truthy, and always returns the response that comes first, for both `waitForResponse` calls. We should fix that.

**Comment by pavelfeldman** [comment]
Wouldn't it be a breaking change?

**Comment by Kremliovskyi** [comment]
@dgozman What about https://playwright.dev/docs/api/class-page#pagerouteurl-handler ? I have entirely forgot about it. It looks like handler can not be async too. Sorry for late comment, I am new to playwright.

**Comment by dgozman** [comment]
@Kremliovskyi Yep, the route predicate cannot be async either. Not sure we can change that, but we'll consider - please file another issue for that 😄

**Comment by GetafixIT** [comment]
Would rather use async/await but this seems to work on a graphql query for the time being:

```
await this.page.waitForResponse((resp) => {
      return resp.text().then((body) => {
        return body.indexOf("someTextFromTheResponseBody") > -1;
      });
    });
```

**Comment by dgozman** [comment]
@GetafixIT `async/await` should work as well, it was fixed in #6201.

**Comment by GetafixIT** [comment]
@dgozman thanks - I'll try that 🙄 ... looked like it was an open ticket above

**Comment by GetafixIT** [comment]
Great... this works nicely

```
await this.page.waitForResponse(
    async (resp) => !!JSON.parse(await resp.text())?.data?.someProperty
);
```
