### ISSUE TITLE
Full page screenshot not rendering correctly

### ISSUE THREAD

**Issue by rightqa** [microsoft/playwright#620]
Here is my code 

```
const pw = require('playwright');

(async () => {
  const browser = await pw.chromium.launch(); // or 'chromium', 'firefox'
  const context = await browser.newContext();
  const page = await context.newPage();

  await page.goto('https://www.waze.com/');
  await page.screenshot({ 
      path: 'example.png',
      fullPage : true });

  await browser.close();
})();
```

![example](https://user-images.githubusercontent.com/12410419/73042080-f7761300-3eb3-11ea-9357-e48f7108081c.png)

If you see the content at the bottom of the page is not properly captured in screenshot. Any help will be appreciated.

**Comment by arjun27** [comment]
Interesting example, thanks for sharing. On observing the page, I noticed that the bottom parts of the page load after scrolling. To replicate this behavior through Playwright, I've added a method `scrollFullPage` to your code snippet, executed right before taking a screenshot.

```js
const pw = require('playwright');

(async () => {
  const browser = await pw.chromium.launch({ headless: false }); // or 'chromium', 'firefox'
  const context = await browser.newContext();
  const page = await context.newPage();
  
  await page.goto('https://www.waze.com/');
  await scrollFullPage(page);
  
  await page.screenshot({ 
    path: 'example.png',
    fullPage : true
  });
  
  await browser.close();
})();

async function scrollFullPage(page) {
  await page.evaluate(async () => {
    await new Promise(resolve => {
      let totalHeight = 0;
      const distance = 100;
      const timer = setInterval(() => {
        const scrollHeight = document.body.scrollHeight;
        window.scrollBy(0, distance);
        totalHeight += distance;
        
        if (totalHeight >= scrollHeight){
          clearInterval(timer);
          resolve();
        }
      }, 100);
    });
  });
}
```

**Comment by zac11** [comment]
Any chance this can be implemented as a method since there are many scenarios where we're in need of taking full page screenshots. 
This was a limitation in Puppeteer and it would be a definite plus point for a lot of users imho.
Issue - https://github.com/GoogleChrome/rendertron/issues/108 (Puppeteer doesn't support full page screenshot)

**Comment by arjun27** [comment]
Thanks @zac11. Full page screenshots are supported with the `fullPage : true` flag. Can you share any examples where the flag does not work for you? Thanks!

**Comment by jcousins-ynap** [comment]
It's definitely due to the website animating in all images when inside the viewport. A fullpage screenshot scrolls too fast for the code to show the images. This isn't a puppeteer/playwright limitiation.

**Comment by rightqa** [comment]
> Interesting example, thanks for sharing. On observing the page, I noticed that the bottom parts of the page load after scrolling. To replicate this behavior through Playwright, I've added a method `scrollFullPage` to your code snippet, executed right before taking a screenshot.
> 
> ```js
> const pw = require('playwright');
> 
> (async () => {
>   const browser = await pw.chromium.launch({ headless: false }); // or 'chromium', 'firefox'
>   const context = await browser.newContext();
>   const page = await context.newPage();
>   
>   await page.goto('https://www.waze.com/');
>   await scrollFullPage(page);
>   
>   await page.screenshot({ 
>     path: 'example.png',
>     fullPage : true
>   });
>   
>   await browser.close();
> })();
> 
> async function scrollFullPage(page) {
>   await page.evaluate(async () => {
>     await new Promise(resolve => {
>       let totalHeight = 0;
>       const distance = 100;
>       const timer = setInterval(() => {
>         const scrollHeight = document.body.scrollHeight;
>         window.scrollBy(0, distance);
>         totalHeight += distance;
>         
>         if (totalHeight >= scrollHeight){
>           clearInterval(timer);
>           resolve();
>         }
>       }, 100);
>     });
>   });
> }
> ```

Thanks @arjun27 , it worked for the given example. I appreciate your help. Will try with some other examples and let you know how I go.

This project looks interesting, anyway I can contribute to the project? Say some doco, tutorial etc?

**Comment by utkarshpaliwal9** [comment]
> Thanks @zac11. Full page screenshots are supported with the `fullPage: true` flag. Can you share any examples where the flag does not work for you? Thanks!

There's this page https://extrasalt.org/ where even with the fullPage flag enabled, playwright doesn't capture the entire page SS. Only a part of it.
![https%3A%2F%2Fextrasalt org%2F1](https://user-images.githubusercontent.com/34744375/108183478-1a630d00-7130-11eb-9502-f20b34c67294.png)

**Comment by davidricardo1026** [comment]
> > Interesting example, thanks for sharing. On observing the page, I noticed that the bottom parts of the page load after scrolling. To replicate this behavior through Playwright, I've added a method `scrollFullPage` to your code snippet, executed right before taking a screenshot.
> > ```js
> > const pw = require('playwright');
> > 
> > (async () => {
> >   const browser = await pw.chromium.launch({ headless: false }); // or 'chromium', 'firefox'
> >   const context = await browser.newContext();
> >   const page = await context.newPage();
> >   
> >   await page.goto('https://www.waze.com/');
> >   await scrollFullPage(page);
> >   
> >   await page.screenshot({ 
> >     path: 'example.png',
> >     fullPage : true
> >   });
> >   
> >   await browser.close();
> > })();
> > 
> > async function scrollFullPage(page) {
> >   await page.evaluate(async () => {
> >     await new Promise(resolve => {
> >       let totalHeight = 0;
> >       const distance = 100;
> >       const timer = setInterval(() => {
> >         const scrollHeight = document.body.scrollHeight;
> >         window.scrollBy(0, distance);
> >         totalHeight += distance;
> >         
> >         if (totalHeight >= scrollHeight){
> >           clearInterval(timer);
> >           resolve();
> >         }
> >       }, 100);
> >     });
> >   });
> > }
> > ```
> 
> Thanks @arjun27 , it worked for the given example. I appreciate your help. Will try with some other examples and let you know how I go.
> 
> This project looks interesting, anyway I can contribute to the project? Say some doco, tutorial etc?

[over](overflow-y: initial !important;)

**Comment by bryanjtc** [comment]
Can scrollFullPage() be implemented with a flag option? I use gsap animations that load the website content when the user scrolls.  In my case `fullPage: true` is not enough.

**Comment by 250king** [comment]
I have some problem about screenshot. I don't know why mine is a little fuzzy? Viewport size is 480×1080.
![Cache_1a7696eb549ef62e.jpg](https://github.com/microsoft/playwright/assets/61256966/2cc6daad-b5ed-4ee3-a129-df13f34fd57a)

**Comment by slorber** [comment]
Similar issue here, I couldn't understand why the bottom of my page gets cropped while running Argos (visual regression tests)

It turns out a widget on the page (the docs 👍 👎 rating widget) produces a layout shift when loading and it messes up with the fullPage screenshot. The bottom cropped part is exactly 109px which is the height this widget takes in practice.

![CleanShot 2023-08-24 at 12 05 25@2x](https://github.com/microsoft/playwright/assets/749374/d3796b04-8cb3-4562-a4c1-92cbb50869d7)

Screenshotting code, using Playwright 1.30:

```ts
  await handle.screenshot({
    path: resolve(screenshotFolder, `${name}.png`),
    type: "png",
    fullPage: true,
    mask: [page.locator('[data-visual-test="blackout"]')],
    animations: "disabled",
    ...options,
  });
```

Considering the widget is visible on both screenshots, it looks to me that there might be some kind of race condition happening in the playwright screenshotting logic. My intuition is:
- We call `screenshot()`
- Screenshot computes the final height
- The widget appears on the page
- Playwright takes the screenshot

Example page I found this issue on: https://deploy-preview-3780--react-native.netlify.app/architecture/overview
