### ISSUE TITLE
[Question] Not all graphql requests are replicated when running tests via playwright

### ISSUE THREAD

**Issue by jaroszan** [microsoft/playwright#6200]
I am working on a script against an app which performs backend queries via graphql. Request path is the same, only body in POST requests are different. When I manually visit one section of the site which displays various data I can clearly see multiple graphql queries with different content. However when I run it in a playwright script only first one issued and responded, rest of them do not fire up. This issue happens in puppeteer as well, but not selenium which handles it correctly.

For example when I visit page manually 3 requests are issued (also via selenium):
- graphql1
- graphql2
- graphql3

In case of Playwright and Puppeteer only first one is issued, **graphql2** and **graphql3** are not visible in devtools (it's also noticeable on page which lacks data)

Question is - is there a special way to handle such scenarios in Playwright? Is there some magic in the background that blocks requests considered duplicates and can be turned off?

**Comment by dgozman** [comment]
@jaroszan Nothing special comes to mind. Playwright should not affect how the page works, although there could be bugs of course 😄  Do you have a repro script or at least a page url to share? Otherwise, it's hard to help you.

**Comment by jaroszan** [comment]
Unfortunately I am not able to share url (it's not accessible publicly anyway). What I can share is that click is initiated using xpath as selector, eg:

```javascript
await page.click("//div[contains(., 'Network')]/*[name()='svg']/ancestor::li//a[contains(., 'Devices')]")
```

Nothing special about it.

I have set up explicitly request interceptor to confirm that only one request is fired up. If you have any advice about how to best troubleshoot the issue I will be happy to learn about. I have some of the scripts in selenium/webdriver which I will gladly migrate to playwright since it allows transparent access to raw requests and responses (for dealing with proxies and MFA) and much easier to set up for CI/CD.

**Comment by dgozman** [comment]
Some ideas about troubleshooting:
- Run `npx playwright codegen`, do the actions manually and see whether the problem persists. Codegen could also help with nice selectors 😄 
- Run with environment variable `DEBUG=pw:browser* node myscript.js` and look for suspicious logs (or post them here).
- Same but with more comprehensive protocol log `DEBUG=pw:browser*,pw:protocol node myscript.js` (this one is hard to read, so better send it to us).
- If you feel comfortable sharing privately, send me instructions to dgozman [at] microsoft [dot] com.

**Comment by pavelfeldman** [comment]
I would use [inspector](https://playwright.dev/docs/inspector) and would check DevTools console for errors. Playwright does not affect the behavior, but there could be a timing or a similar issue. Let us know what you find out please!

**Comment by jaroszan** [comment]
After in-depth verification it looks like this issue has nothing to do with playwright. Some non-chromium based browsers seem to be affected as well during regular usage (without testing tools) so it's very likely application specific. Debug logs proved useful though, thanks for the hints!
