### ISSUE TITLE
[BUG] yar

### ISSUE THREAD

**Issue by yarangel72** [microsoft/playwright#6217]
**Context:**
- Playwright Version: [what Playwright version do yo -->

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript


(async () => {
  const browser = await chromium.launch();
  // ...
})();
```

**Describe the bug**

Add any other details about the problem here.

**Comment by mxschmitt** [comment]
Closed, since it seemed to be open by accident.
