### ISSUE TITLE
[Feature] add page.setJavaScriptEnabled (enabled) method to switch dynamically

### ISSUE THREAD

**Issue by liukaigsx** [microsoft/playwright#6218]
var page = await browser.NewPageAsync(new BrowserContextOptions
            {
                JavaScriptEnabled = false
            });
This will disable JavaScript , but I want to switch dynamically later
like puppeteer setJavaScriptEnabled(true)
puppeteer-sharp SetJavaScriptEnabledAsync(true)

**Comment by pavelfeldman** [comment]
Could you tell why you need this?

**Comment by liukaigsx** [comment]
like i need to load a user home page , don't need to enable JavaScript ,  when the page reaches a certain amount of access , will jump to the captcha page , need to enable javascript to load the captcha.
by looking at the source code , I found a way by using CDPSession 
`this._client.send('Emulation.setScriptExecutionDisabled', { value: false})`

thanks for reply

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.

**Comment by Zlitus** [comment]
Would love it too, I stopped using Playwright and switched some of my libs to Puppeteer because of this lack 😕.

**Comment by elyran** [comment]
I'd like to be able to disable/enable JS in any time, as we can do with DevTools. A method like `setScriptExecution(boolean)`.
