### ISSUE TITLE
[Feature] Playwright on CentOS 

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright#6219]
# Description
I have created [Dockerfile](https://github.com/kumaraditya303/playwright-centos/blob/master/Dockerfile) for playwright based on CentOS 8 image and I have got `chromium` and `firefox` working on it, only webkit is not working because it requires  these libraries  which isn't available on CentOS Repository. 
```console
      libvpx.so.6
      libjpeg.so.8
      libwebp.so.6
      libicui18n.so.66
      libicuuc.so.66
``` 

# Fix
It can be fixed if playwright static links these libraries so that there isn't need to install it or it can included in the `zip` archive.
It is only required for webkit.
```console
      libvpx.so.6
      libjpeg.so.8
      libwebp.so.6
      libicui18n.so.66
      libicuuc.so.66
```

If the dependency is resolved then the image can also be upstream and merged into `install-deps` option for centos.

cc: @aslushnikov @pavelfeldman @mxschmitt 

https://github.com/kumaraditya303/playwright-centos

Pull Image:
```console
$ docker pull docker.pkg.github.com/kumaraditya303/playwright-centos/playwright:latest
```

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
