### ISSUE TITLE
[Question] page.waitForEvent doesn't appear to catch the event

### ISSUE THREAD

**Issue by tommulkins** [microsoft/playwright#6220]
Perhaps I'm just doing this in the wrong way but I have been trying to catch custom events that load on a page with no luck.

For example, I create a simple page firing a "test" event each second.

```
const event = new Event('test')
const el = document.querySelector(`body`)

el.addEventListener("test", (e) => console.log(`${e.type} triggered`))

setInterval(() => {
  el.dispatchEvent(event)
  }, 1000)

```

Playwright will show the event being triggered each 1 second from console.log yet `page.waitForEvent('test')` times out.

What am I missing here?

**Comment by dgozman** [comment]
[`waitForEvent`](https://playwright.dev/docs/api/class-page/#pagewaitforeventevent-optionsorpredicate) waits for Playwright's own events in the Node.js environment, for example [`console` event](https://playwright.dev/docs/api/class-page/#pageonconsole).

To wait for a particular event inside the page itself, you can use evaluate:
```js
await page.evaluate(eventName => {
  return new Promise(callback => document.addEventListener(eventName, callback, { once: true }));
}, 'my-custom-event-name');
```
