### ISSUE TITLE
[Question] don't know what to wait for

### ISSUE THREAD

**Issue by amit-parizian-erudite** [microsoft/playwright#6221]
Hi,
our app uses a tool called PDFTron which among other things allows to upload a pdf and highlight some of the text. I am trying to automate a test that selects some text and then highlights it. **after** selecting the text and **before** clicking the highlight button I need to wait. if there is not enough waiting the highlight is not saved (for example after reloading the page the highlight is gone). but I am not sure what to wait for. it seems the only change after selecting the text is a pop up with the highlight button. I tried:
`page.waitForLoadState("load")`
`page.waitForLoadState("domcontentloaded")`
`page.waitForLoadState("networkidle")`
`page.waitForSelector("highlight-button")`
`page.waitForNavigation()`

but none of those worked. there is no network activity after selecting the text, nothing in the console, no other element that appear or disappear beside "highlight-button". the only thing I could find was that there is a 'Worker message' event when selecting. I tried `page.waitForEvent("message")` but it doesn't (at least for ten minutes) resolve.

the only thing that works is `page.waitForTimeout(2000)` but as your documentation say it should only be used for debugging.

code snippet:

```
async highlightTextInFirstPageByMouse({
    xStartOffset,
    yStartOffset,
    selectionAreaWidth,
    selectionAreaHeight,
  }) {

    await this.selectTextInFirstPageByMouse({
      xStartOffset,
      yStartOffset,
      selectionAreaWidth,
      selectionAreaHeight,
    });
    const pdftronFrame = await this.getPDFTronFrame();
    await pdftronFrame.click(ArticlePage.PDFTRON_HIGHLIGHT_BUTTON_XPATH);

    await pdftronFrame.waitForSelector(
      ArticlePage.PDFTRON_ANNOTATION_DELETE_BUTTON_XPATH
    );

    await pdftronFrame.click(
      `//*[@id='${ArticlePage.ARTICLE_CONTENT_SELECTOR}']`
    );

    await pdftronFrame.waitForSelector(
      ArticlePage.PDFTRON_ANNOTATION_DELETE_BUTTON_XPATH,
      { state: "detached" }
    );
}

async selectTextInFirstPageByMouse({
    xStartOffset,
    yStartOffset,
    selectionAreaWidth,
    selectionAreaHeight,
  }) {

    const firstPageElement = await this.getFirstPageOfArticle();
    const firstPageBoundingBox = await firstPageElement.boundingBox();
    await this.page.mouse.move(
      firstPageBoundingBox.x + xStartOffset,
      firstPageBoundingBox.y + yStartOffset
    );
    await this.page.mouse.down();
    await this.page.mouse.move(
      firstPageBoundingBox.x + xStartOffset + selectionAreaWidth,
      firstPageBoundingBox.y + yStartOffset + selectionAreaHeight
    );
    await this.page.mouse.up();

    const pdftronFrame = await this.getPDFTronFrame();
    await pdftronFrame.waitForSelector(
      ArticlePage.PDFTRON_HIGHLIGHT_BUTTON_XPATH
    );

    await pdftronFrame.waitForTimeout(2000);
}
```

do you have any ideas?
thanks in advance.

**Comment by dgozman** [comment]
You have this nice `waitForSelector` that should wait until the highlight element appears.
```js
await pdftronFrame.waitForSelector(
  ArticlePage.PDFTRON_HIGHLIGHT_BUTTON_XPATH
);
```

Does that work? If not, perhaps there is something else inside that highlight element that appears, maybe some text? If so, you can wait for that text to appear. I'd suggest to run [codegen](https://playwright.dev/docs/cli/#generate-code), click on the highlight element and check the selector it generates. Try waiting for that particular selector.

**Comment by amit-parizian-erudite** [comment]
the wait for selector doesn't work. thanks for introducing codegen to me, awesome tool! unfortunately it didn't work either, the selector it generated for me was similar to the one i used. also, i tried selecting something inside the button and it didn't help either.

**Comment by dgozman** [comment]
@amit-parizian-erudite There is not much we can help with here. How do users know that it is time to click the highlight button? If nothing changes on the page, they get no indication, so that's the bug on the page. If something changes, you should be able to use `waitForSelector`. Unfortunately, there is no magic "wait until something happens" solution without defining what are we waiting for 😄

**Comment by amit-parizian-erudite** [comment]
haha I know. it's just that I wondered if maybe you encountered text selection in the past and knew about some event or anything that I could wait for after selecting text. anyway thanks for the help!!
