### ISSUE TITLE
[BUG] Errors occur when use innerText() "ElementHandle.innerText: Not an HTMLElementError:"

### ISSUE THREAD

**Issue by wenshu520** [microsoft/playwright#6225]
**Context:**
- Playwright Version: 1.9.2
- Operating System: Linux
- Node.js version: v14.16.0
- Browser:  Chromium

**Code Snippet**

```
const selector = `${this.selector} svg g[class="bottom axis"] g`;
    await page.waitForSelector(selector);
    const axisElements = await page.$$(selector);
    const axes = await Promise.all(
      axisElements.map((element) => element.innerText())
    );
    return axes;
```

**HTML**
![image](https://user-images.githubusercontent.com/45124186/115207484-3a15b200-a12e-11eb-8c9e-fd7beb9b9fc9.png)

**Describe the bug**
Hi experts,

I want to get each element's text but here are errors when doing it like this. However, if I tried to use "textContent()", it can work. So I want to know why the innerText can't work as I expected?. And what is the difference between "textContent" and "innerText". Thanks.

 elementHandle.innerText: Not an HTMLElementError:

      29 |     const axisElements = await page.$$(selector);
      30 |     const axes = await Promise.all(
    > 31 |       axisElements.map((element) => element.innerText())
         |                                             ^
      32 |     );
      33 |     return axes;
      34 |   }

**Comment by thernstig** [comment]
@dgozman is the TypeScript interface for this incorrect then? It lists SVGElement.

![screenshot](https://user-images.githubusercontent.com/30827238/115860888-6da85300-a432-11eb-9107-1d95199987eb.png)
