### ISSUE TITLE
[Question] $eval Property 'value' does not exist on type 'SVGElement | HTMLElement'.

### ISSUE THREAD

**Issue by ortoniKC** [microsoft/playwright#6229]
Hi, I am trying to get the selected option from a dropdown. 
```
const last = await page.$eval("#country", el => el.value);
console.log(last);
```
But getting the error as 
```
Property 'value' does not exist on type 'SVGElement | HTMLElement'.
Property 'value' does not exist on type 'SVGElement'
```

![image](https://user-images.githubusercontent.com/58769833/115244851-f7f66b80-a141-11eb-9da0-e851b729d679.png)

**Comment by mxschmitt** [comment]
You can use generics to adjust the type inside the inner function like that:

```ts
await page.$eval<string, HTMLSelectElement>('#my-select', e => e.value);
```

**Comment by ortoniKC** [comment]
It worked. Thank you so much :)
