### ISSUE TITLE
[BUG] Wrong element is clicked due to lazy loading/UI shift

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#6238]
**Context:**

- Playwright Version: v1.10.0
- Operating System: Mac
- Node.js version: v15.4.0
- Browser: Webkit
- Extra: Docker image - v1.10.0-focal

**Describe the bug**
Scenario - Click "Contact Agent" button.

Issue - I am trying to click "Contact Agent" button on the page but there is a section "Popular Search" that loads later and shifts the UI. While the test is trying to click the button, the UI changes and instead it ends up clicking one of the popular searches. Please see the screenshot below captured using PWDEBUG=1 - the button is found and highlighted but pointer is on one of the searches.

![webkit_pointer](https://user-images.githubusercontent.com/22205721/115429903-b81e9b00-a1b8-11eb-9c11-ee80f1c79d5b.png)

**Comment by worldomonation** [comment]
Want to add that we have been able to reproduce this behavior on a site that I am developing browser testing on. The description is very similar to the OP; an optional component of the page loads after the main components have loaded, resulting in the target element shifting down some pixels. Intermittently on CI Playwright clicks on the coordinates where the target _used_ to be, which is now occupied by an entirely different element.

`page.click` nor `elementHandle.click` are able to work around this behavior. Waiting for various load states have also been unsuccessful as the events fire before the delayed element is loaded.

If the team would like logs from my end, please let me know.

**Comment by Nav-2d** [comment]
@worldomonation did you try waiting for delayed selector and then clicking the target element? (This workaround worked for me)

```
await this.page.waitForSelector('delayed element');
await this.page.click('target element');
```

**Comment by Nav-2d** [comment]
@worldomonation - I see. Few snippets that could help:

```
try {
    await page.waitForSelector('delayed/optional banner', { timeout: 5000 });
} catch (error) {
   await page.click('target element');
}
```

```
const el = await page.$('delayed/optional banner');
if (el) {
   await page.click('target element');
}
await page.click('target element');
```

**Comment by Nav-2d** [comment]
Another instance where clicks misses the original element due to the animation/UI shift. Clicking Root opens a dropdown (expanding animation) and after that trying to click `Sign Out` link fails intermittently. Solutions already tried:
`waitForSelector`
`reducedMotion: 'reduce'`

![wrong_click](https://user-images.githubusercontent.com/22205721/135020858-f2639f32-a4f8-46a0-bcad-d3f4ee76ce04.JPG)

**Comment by dgozman** [comment]
We have some ideas about addressing this, but did not make it in time for v1.16.

**Comment by worldomonation** [comment]
> We have some ideas about addressing this, but did not make it in time for v1.16.

That's great to hear - in the meantime, I have been able to work around this by using page.dispatchEvent("click") on my end.

**Comment by dgozman** [comment]
Since #9546 was reverted, reopening this issue.

**Comment by MartinP-Autopilot** [comment]
I don't think that this is a bug; it is perhaps not even a design flaw, the behaviour just needs to be better documented (maybe in a guide).

Most automaters are used to WebDriver whose [Element.click ](https://www.w3.org/TR/webdriver1/#element-click) operation fires the click event on the target element's parent node.  It appears that Playwright fires the click event much higher up using the _viewport_ XY co-ordinates.  If the element moves between getting the XY co-ordinates and using them (as appears top be the case here), you get a click miss.

There are several solutions to above problem and which one should be used depends on the situation.  You just need to understand that the problem exists before you try and figure out the solution for your situation (you didn't need to worry about this in WebDriver, but I am sure that there is a method to the madness).

@Nav-2d, in the case of the initial problem, the data that is rendered had to come from somewhere and it will usually come in the response to a request that was sent as a result of some event (either an earlier click, or the initial page load).  You just need to figure out which event the request is sent from and do a waitForResponse (it is _rare_ for Web apps to delay rendering after they get a response).

In the case of [your second problem](https://github.com/microsoft/playwright/issues/6238#issuecomment-928744966), are you doing 'waitForSelector` on the "Sign out" button, or on what ever element is being rendered _after_ the "Sign out" button and causing that button to be pushed down?
