### ISSUE TITLE
[Question] Appetite for bare bone browser?

### ISSUE THREAD

**Issue by ali-habibzadeh** [microsoft/playwright#624]
Sometimes what matters is how fast you get the content or can run a function against the DOM. Specially in web analysis use cases where a perfect browser replication is not important.

Are there conversations / plans to add a browser type which only does the very minimum and focuses on speed rather than all the bells and whistles of a full modern browser like FF or Chrome?

**Comment by JoelEinbinder** [comment]
Headless Chromium is quite fast, without sacrificing accuracy. I think you'd be hard pressed to make something faster even if you don't need to support as much.

However, latency is hurt a bit by downloading the browser and running it in another process. Maybe you'd be interested in [JSDOM](https://github.com/jsdom/jsdom) or [Cheerio](https://github.com/cheeriojs/cheerio)?

**Comment by aslushnikov** [comment]
I'd vote for Headless Chrome as well. It's really nice and performant.

**Comment by ali-habibzadeh** [comment]
@aslushnikov For your attention: https://v8.dev/blog/v8-lite
