### ISSUE TITLE
[Question] Can't wait for an element to be visible when it is overlapped with other elements in frontend

### ISSUE THREAD

**Issue by wenshu520** [microsoft/playwright#6240]
Hi Experts,

I have a doubt here. 
This is frontend. As you can see, here is one line with zero value. So the whole line is overlapped with the zero value.
![image](https://user-images.githubusercontent.com/45124186/115329052-45b3b800-a1c4-11eb-88df-93457a9d56b3.png)

HTML is as below:
![image](https://user-images.githubusercontent.com/45124186/115331240-21f27100-a1c8-11eb-9381-07fc2ce93146.png)

Code:

```js
const selector = `${this.selector} svg g[class="line-group"] path`;
await page.waitForSelector(selector);
const pathElements = await page.$$(`${selector} path`);
return pathElements.length;
```

When I run this code in debug mode, it will stuck in the "waitForSelector", it seems that playwright don't find the element, but I do see it display in the frontend. However, if I change the code to be "page.waitForSelector(selector, {state: "attached"}", it can work well.

Therefore, I want to know why it can't find the selector to be visible? 

Thanks

BR,
Wenshu

**Comment by mxschmitt** [comment]
Playwright internally checks for Accessibility checks, see here: https://playwright.dev/docs/api/class-accessibility 

Getting via that values from inside a SVG is currently not intended, what is the exact use-case for it? You can try to disable them via adding `{force: true}` to your waitForSelector call, maybe it works.

Having a small available reproducible and its scenario would help a lot, thanks!

**Comment by wenshu520** [comment]
Hi @mxschmitt ,

Thanks for your reply. However, I didn't find here is an option of {force:true} in waitForSelector function.

![image](https://user-images.githubusercontent.com/45124186/116506652-464cfc80-a8f0-11eb-9683-5a1f3b7eec6d.png)

**Comment by mxschmitt** [comment]
good catch, try state: attached instead, this should work:

`await page.waitForSelector("#foo > g > path", {timeout: 1000, state: "attached"})`

**Comment by aslushnikov** [comment]
(closing due to lack of feedback)
