### ISSUE TITLE
[Question] Element is not attached to the DOM

### ISSUE THREAD

**Issue by iamandras** [microsoft/playwright#6244]
Hello,

I have a script like this.
I randomly get `Element is not attached to the DOM` error when I run this.

```
await page.waitForSelector(selector);
const element = await page.$(selector);
await element.click();
```

Is it possible that the element disappears between the $ command and the click?
If yes, how can I prevent this issue?

Thanks,
Andras

**Comment by iamandras** [comment]
Thanks for the reply.
I would like to understand the difference. Could you please explain it?

Similar question:
What if I use the $$ function to get a list of elements.
I guess in this case it can easily happen that one of the elementHandles becomes invalid. Any suggestion here?
```
 await page.waitForSelector(selector);
 const elements = await page.$$(selector);
 for (let i=0; i < elements.length; ++i) {
     await elements[i].click();
 }
```

Thanks.

**Comment by dgozman** [comment]
@iamandras The difference is that `page.click(selector)` will retry when the element disappears during the click: it will retrieve a new element matching the `selector` and click it. At the same time, if you insist on a particular `element.click()`, Playwright will only click that specific element and not any other elements. If that element is detached, the error will be thrown.

Same goes for `$$`: if the page is changing while you are working with these elements, they could be detached and Playwright won't be able to click them.

We suggest to use `page.click()` when possible to avoid this problem.

**Comment by iamandras** [comment]
Thanks for the explanation @dgozman. Makes sense, I've thought it works this way.

**Comment by dgozman** [comment]
Let me close this issue then. If you have any more questions, please comment here, and I'll reopen.

**Comment by mercer** [comment]
Playwright docs discourage this @dgozman. Why?

https://playwright.dev/docs/api/class-page#page-click

**Comment by mfplunet** [comment]
@mercer AFAICT they are saying you should write `page.locator('selector').click()` which is not the same as `page.$('selector').click()` because the `$` immediately returns an element whereas `locator` remains dynamic and can be retried when the `click` fails.

**Comment by Evelynsound** [comment]
Here’s a useful insight https://bastard-working-class.github.io/rylan228/
