### ISSUE TITLE
How to Clear Cookies , Site Data, And Offline Data From Firefox using Playwright [Question]

### ISSUE THREAD

**Issue by tahmid00911** [microsoft/playwright#6245]
![Screenshot from 2021-04-20 21-44-19](https://user-images.githubusercontent.com/75070039/115425623-9a395080-a221-11eb-9959-6cb5a77745fa.png)

Without Creating incognito or Closing Browser Context How to Achieve This in Firefox nightly.

I tried browserContext.clearCookies() but couldn't achieve the effect I want

**Comment by dgozman** [comment]
@tahmid00911 Playwright does not allow manipulating browser settings and dialogs. Instead, it is focusing on automating the web pages. This "Clear Recent History" dialog is a Firefox-specific dialog that we do not support.

**Comment by mxschmitt** [comment]
@tahmid00911 why does creating a new context no work for your use-case?
