### ISSUE TITLE
Will this "just work" at some point, without having to say which browser to use?

### ISSUE THREAD

**Issue by Pomax** [microsoft/playwright#625]
All I care about is that my code works in all browsers, so I'd expected a cross-browser testing setup to offer a clean "run this code, and every one of the supported and installed browsers will do so, yielding separate screenshots and logs for each" despite using a single test script.

Is that on the roadmap? If not, can that _please_ be on the roadmap? Because otherwise all this automates is the installation of the headless browsers themselves. The actual hassle, namely writing separate files and running separate tasks just to test the same thing, is still right there. 

Rather than three scripts, the _usefulness_ comes from being able to write this, instead:

```javascript
const pw = require('playwright');

// zero-conf with all supported browsers enabled: updating pw simply
// gets you more targets as they get added, for free, with zero work.
// The ideal setup for 99% of folks who need to write tests.
const instance = pw.createInstance({ 
  ...
  // but if you're in the 1% of folks who need to target fewer than "all browsers",
  // you get to configure things yourself. And having a "browsers" conf option
  // means that rather than all-enabled, things should be all-disabled, only enabling
  // those browsers that have a truthy conf value, because now you need to make
  // sure new engines *don't* kick in for free:
  browsers: {
    chrome: true, // true/falsey or object with more specific props - keep it simple until it needs to be complicated
    firefox: true
  },
  ...
});

(async () => {
  // plural because we want to target all browsers, not "write lots
  // of code for each separate browser":
  const browsers = await instance.startBrowsers();
  // start testing stuff.
  const page = await browsers.newPage('https://maps.google.com');
  // start performing tasks and waiting for those tasks to complete
  // in _all_ browsers before moving on.
  await page.click('text="Your location"');
  // take as many screenshots as there are browsers running
  await page.screenshot({ path: 'initial-click.png' });
  await browsers.close();
})();
```

**Comment by jperl** [comment]
@pomax One possible solution is that you can create a `launch` helper in your codebase which takes the browser as an option and pass the browser as an environment variable. So you could get similar behavior just by calling `npm test` multiple times.

Ex. 

in code

`browser = await launch({ browser: process.env.BROWSER || "chrome" });`

in CI

```
BROWSER=chrome npm test
BROWSER=firefox npm test
BROWSER=webkit npm test
```

FWIW, that is how I plan to handle it in [qawolf](https://github.com/qawolf/qawolf).

**Comment by arjun27** [comment]
Thanks @Pomax for this sharing this. With Playwright, you can use a single test script to run automation scripts across Chromium, Firefox and WebKit. This is possible with a single API that can works on the 3 browsers.

Playwright can be integrated with your test runners in any way that you like—thanks @jperl for an example integration. We could share examples of how it could work with popular test runners like Jest/Mocha, without imposing a particular runner. Is there a particular test runner you prefer?

Also just so we're more clear on the readme, I've created #631 to communicate this better.

**Comment by Pomax** [comment]
@jperl that's still the opposite of what I want: no testing individual browsers, just finally have a test runner that just tests _everything_ using universal code.

**Comment by jperl** [comment]
@pomax those are really good points. Build the `create-react-app` of browser testing is what I am trying to do with [qawolf](https://github.com/qawolf/qawolf). It sets up Puppeteer ([working on switching to Playwright](https://github.com/qawolf/qawolf/pull/352)) and Jest with one command based on your browser actions, and sets up CI with one command.

One idea based on your thoughts, is that we could make a flag that allows you to run tests on all browsers. `npx qawolf test --all-browsers.` 

I don't want to hijack this thread, so I reached out to your listed github email because I would love to get your thoughts on how to make testing easier.

**Comment by aslushnikov** [comment]
> Is that on the roadmap? If not, can that please be on the roadmap?

@Pomax It's outside of the scope for the PlayWright project. Our hope is that community projects such as qawolf will address this!

**Comment by jperl** [comment]
We will be adding a flag to qawolf to run tests on all browsers with playwright. 👍
