### ISSUE TITLE
[Regression ToT] bypassCSP does not apply to frame-src

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#6251]
```
mkdir ~/tmp/csp
cd ~/tmp/csp
npm init -y
npm i playwright@next
```

```js
// @ts-check
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({ headless: false });
  const context = await browser.newContext({ bypassCSP: true });
  const page = await context.newPage();
  page.on('console', m => console.log(m));
  await page.goto('https://github.com/microsoft');
  await page.evaluate(() => {
    const iframe = document.createElement('iframe');
    iframe.src = 'https://example.com';
    document.body.appendChild(iframe);
  });
  await context.close();
  await browser.close();
})();
```

works fine in v1.10.

**Comment by pavelfeldman** [comment]
Bisect range: https://chromium.googlesource.com/chromium/src/+log/98e7c00beaae772132e7b567f21247f144b3b7a6..e6997b7d6020e7307f9ea1c4ea68692b34a66640

Change:
https://chromium.googlesource.com/chromium/src/+/1d017fa5d733d14afa7098905d4f49ae007db981

**Comment by pavelfeldman** [comment]
Upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1200957
Upstream fix: https://chromium-review.googlesource.com/c/chromium/src/+/2842785

**Comment by aslushnikov** [comment]
This is fixed with the last Chromium roll. https://github.com/microsoft/playwright/commit/5509527917ff20af4e4ae31c6b66ea31475048d9
