### ISSUE TITLE
[Question] Where can i find this dictionary in the Python version of Playwright?

### ISSUE THREAD

**Issue by jmartle** [microsoft/playwright#6263]
so this is the python version of playwright: https://github.com/microsoft/playwright-python

and im trying to find [this](https://github.com/microsoft/playwright/blob/b4209e9dc80e6226f6b173ab77f0390a809964a2/src/deviceDescriptors.ts) dictionary there but I cant find it. 

pls advise

**Comment by YusukeIwaki** [comment]
Official document is here: https://playwright.dev/python/docs/emulation

**Comment by dgozman** [comment]
The source file with devices is only available in typescript. The dict is available via `playwright.devices`. See docs: https://playwright.dev/python/docs/emulation#devices.
