### ISSUE TITLE
[BUG] keyboard.type doesn't raise all events

### ISSUE THREAD

**Issue by hshristov** [microsoft/playwright#6267]
**Context:**
- Playwright Version: 1.9.2
- Operating System: Windows
- Node.js version: 12.20.1.0
- Browser: Chromium [probably All]
- Extra: I'm using PlaywrightSharp 0.192.0 with the embedded Chromium and Node.js but my assuption is that this issue comes from Playwright

System:
    OS: Windows 10 10.0.19042
    Memory: 15.84 GB / 31.93 GB
Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD

**Describe the bug**

When calling `await page.keyboard.type('한');` only `input` event is fired. According to documentation `keydown, keypress/input, and keyup` should be fired as well.

**Comment by JoelEinbinder** [comment]
For characters that are not type-able on a US keyboard, we only send `input` events.

Is this just confusion with the docs, or do you need to test a user typing `한` on a Korean keyboard?

**Comment by hshristov** [comment]
Got it. I don't have issues with specific site. It is the framework that I'm working on that I want to be able to raise all keyboard events. Any tips on how to implement it on my own are really appreciated. Thanks.
