### ISSUE TITLE
Types exported from playwright-core, but not playwright

### ISSUE THREAD

**Issue by jperl** [microsoft/playwright#627]
```
// this works
import { ElementHandle } from "playwright-core";
// this does not
import { ElementHandle } from "playwright";
```

**Comment by jperl** [comment]
I believe this can be solved by changing index.d.ts to 

```
export * from "./src/api";
export const chromium: import("./src/api").ChromiumPlaywright;
export const firefox: import("./src/api").FirefoxPlaywright;
export const webkit: import("./src/api").WebKitPlaywright;
export type PlaywrightWeb = typeof import("./src/web");
```

setting up playwright locally right now to check

**Comment by jperl** [comment]
I am experiencing many type issues. Should I collect them all here, or open separate tickets?

Ex. 

```
// types ok
await elementHandle.press("Backspace", undefined);

// not ok
await elementHandle.press("Backspace");
```

I believe

`async press(key: string, options: { delay?: number; text?: string; } | undefined) {`

should be

`async press(key: string, options?: { delay?: number; text?: string; }) {`

--

and 

```
// works
import { DeviceDescriptor } from "playwright-core/lib/types";

// does not work
import { DeviceDescriptor } from "playwright-core";
```

**Comment by dgozman** [comment]
Thanks @jperl! Collecting typing  issues around specific methods is great, and any PRs are welcome. However, we plan to work on types soonish (probably hand-written `.d.ts` file), so general improvements like re-exporting types between packages will be probably lost during transition.

**Comment by jperl** [comment]
Thanks for your response. I will just keep collecting the type issue here.

**Comment by jperl** [comment]
@dgozman Out of curiosity, what is the benefit of hand writing declaration files instead of exporting types directly from packages?

**Comment by dgozman** [comment]
> @dgozman Out of curiosity, what is the benefit of hand writing declaration files instead of exporting types directly from packages?

We can have different defaults externally vs internally (e.g. `ElementHandle` wrapping `HTMLElement` by default), have short documentation attached to be shown in IDEs, and not pollute types with internal methods starting with underscore.
