### ISSUE TITLE
[Question] Browser in Docker while playwright test script is not

### ISSUE THREAD

**Issue by dimovelev** [microsoft/playwright#6287]
Hi,

I am trying to get playwright to work on our build infrastructure (jenkins). Unfortunately, we do not have Ubuntu (or any Debian flavour) but rather RHEL / CentOS / etc (RedHat...). When Chromium is started it fails to load some dynamic library - I assume that is due to missing packages on the host. This seems a bit undocumented as to what needs to be installed or not - I found some issues in puppeteer / here but no official documentation. It also sounds like a lot to ask from CI to have a large list of packages installed on each of the CI nodes.

An alternative that we use with selenium is let the browsers run in a docker container containing all the packages that they require and the test driver running outside of the container talking via TCP/HTTP with the browser inside the container.

Is that something that can be done with playwright - start a browser in a container and talk to it from the outside?

Thank you
Dimo

**Comment by mxschmitt** [comment]
Hi yes, you can use [BrowserType.connect](https://playwright.dev/docs/api/class-browsertype#browsertypeconnectparams) and [BrowserType.launchServer](https://playwright.dev/docs/api/class-browsertype#browsertypelaunchserveroptions) to launch Playwright in server mode e.g. in another Docker container or virtual machine and connect from some other environment to that server without having all the dependencies in place from the machine where you connect from.

**Comment by dimovelev** [comment]
That is great news! I would be very happy if you had a link to a howto on how to start the image exactly and connect to it. I could not find anything but will try to figure it out from the image's content.

Thank you a lot!

**Comment by mxschmitt** [comment]
There is no pre-built image available which starts a server and logs it's connection address to the console. Its basically something like that which you can use to extend the [existing Docker image](https://playwright.dev/docs/next/docker) with and execute in the entrypoint.

```js
const { chromium } = require('playwright');

(async () => {
  const browserServer = await chromium.launchServer();
  const wsEndpoint = browserServer.wsEndpoint();
  console.log(wsEndpoint)
})();
```

**Comment by dimovelev** [comment]
Thank you, Max! Just for reference if anyone else has the same goal as me - run a browser in a container and connect to it from outside (e.g. java). I ended up with the following Dockerfile to generate a runnable image:
```
FROM mcr.microsoft.com/playwright:bionic
WORKDIR /root
RUN npm install -g typescript && \
	npm install playwright && \
	npm i --save-dev @types/node
EXPOSE 8080
COPY entrypoint.ts /root/
RUN	tsc entrypoint.ts

ENTRYPOINT [ "node", "entrypoint.js" ]
```
and the entrypoint file used by the dockerfile entrypoint.ts:
```
const { chromium } = require('playwright');

(async () => {
  const browserServer = await chromium.launchServer({
	  port: 8080,
	  logger: {
		isEnabled: (name, severity) => severity === 'info' || severity === 'error',
		log: (name, severity, message, args) => console.log(`${name} ${message}`)
	  }
  });
  const wsEndpoint = browserServer.wsEndpoint();
  const path = wsEndpoint.slice(wsEndpoint.lastIndexOf('/') + 1); 
  console.log(path);
  const fs = require('fs');
  fs.writeFile('path.txt', path,  function(err) {
	if (err) {
		return console.error(err);
	}
  });
})();
```
An image can then be built using
```
docker build -t playwright .
```
And started like that:
```
docker run -it --rm -p 8080:8080 --name playwright playwright
```
Unfortunately it does not seem to be possible to configure a hard coded path and a random one is generated upon start (https://github.com/microsoft/playwright/blob/master/src/browserServerImpl.ts#L56). The entrypoint.sh outputs it and also stores it in /root/path.txt so that it can be read from the user. Just an example code in java that fetches the file from a container (based on docker-java library - the container id of course needs to be more dynamic):
```
        DockerClientConfig config = DefaultDockerClientConfig.createDefaultConfigBuilder().build();
        try (final DockerHttpClient httpClient = new ApacheDockerHttpClient.Builder().dockerHost(config.getDockerHost())
            .sslConfig(config.getSSLConfig()).build()) {
            try (final DockerClient client = DockerClientImpl.getInstance(config, httpClient)) {
                try (final InputStream is = client.copyArchiveFromContainerCmd("87ede7a443a1", "/root/path.txt")
                    .exec()) {
                    try (final TarArchiveInputStream tarArchiveInputStream = new TarArchiveInputStream(is)) {
                        final TarArchiveEntry entry = tarArchiveInputStream.getNextTarEntry();
                        final byte[] content = new byte[(int) entry.getSize()];
                        tarArchiveInputStream.read(content, 0, content.length);
                        final String path = new String(content, StandardCharsets.US_ASCII);
                        System.out.println(path);
                    }
                }
            }
        }
```

I will probably propose a feature in a separate issue to allow for hard-coded path to be used.
