### ISSUE TITLE
[BUG] Client-side redirect before 'load' event rejects previous goto()

### ISSUE THREAD

**Issue by sadiqueimam** [microsoft/playwright#629]
Am launching a browser and hitting an URL but sometime browser is getting closed and throws below error, this is happening infrequently:

```
Error: Navigation to https://test.com/ was canceled by another one
    at LifecycleWatcher._onCommittedNewDocumentNavigation (/Users/PlayWright/node_modules/playwright-core/lib/frames.js:856:45)
    at FrameManager.frameCommittedNewDocumentNavigation
```

**Comment by dgozman** [comment]
Could you please post a snippet of code which fails? One possible cause could be a `await` on the previous `goto` method, or perhaps the page navigates away before finishing navigation to https://test.com.

**Comment by sadiqueimam** [comment]
const page = await context.newPage('https://test.com/');
.
.
  const button = await page.waitForSelector("//input[@id='Login']");
  await button.click()
  await page.waitForNavigation({ waitUntil: ['domcontentloaded','load'],timeout: 0 });
  await page.goto('https://test/../../');
  
This is the code, the issue is very inconsistent, here am able to login into the site and after login am trying to navigate to another internal URL directly.

**Comment by jussikuosa** [comment]
Hello @sadiqueimam, I saw the same issue and I managed to work around it by adding `{waitUntil: 'networkidle2'}` to goto options. @dgozman my URL has 2 redirects (needs VPN, sorry). HTH

**Comment by tmunihareesh** [comment]
I am getting same error but my browser is not closing. But my issue might be due to AUTO PAGE REDIRECT to sign page once i access my URL.
Can anyone suggest me to handle auto page redirect?

**Comment by dangsteffens** [comment]
Same issue redirecting to auth0 url

**Comment by kblok** [comment]
Check this out @dgozman 

```js
(async () => {
  const browser = await playwright.chromium.launch({
    headless: false
  });
  const context = await browser.newContext();
  const page = await context.newPage("https://portal.azure.com/");
  await page.screenshot({ path: `example.png` });
  await browser.close();
})();
```

**Comment by dangsteffens** [comment]
@kblok Still getting the same error on sites that redirect.

**Comment by kblok** [comment]
Yup @dangsteffens, it's a code snippet for @dgozman to test.

**Comment by claudiordgz** [comment]
I tried using the `waitUntil` idle to no avail. My screenshot comes in blank.

```
/* eslint-disable @typescript-eslint/no-var-requires */
const playwright = require("playwright");

(async () => {
  try {
    const browser = await playwright.chromium.launch();
    const context = await browser.newContext();
    const page = await context.newPage("about:blank");
    await page.goto("https://portal.azure.com/", { waitUntil: "networkidle2" });

    await page.screenshot({ path: `example.png` });
    await browser.close();
  } catch (e) {
    console.log(e);
  }
})();
```

**Comment by dgozman** [comment]
I am able to repro, this is indeed an issue. Thank you, @kblok!

**Comment by dgozman** [comment]
This should be fixed in version 0.11.1.

**Comment by dangsteffens** [comment]
I still have the same issue.

**Comment by dgozman** [comment]
> I still have the same issue.

Mind sharing a script?
