### ISSUE TITLE
[BUG] Using playwright-core with custom Chromium execution path breaks Inspector

### ISSUE THREAD

**Issue by paya-cz** [microsoft/playwright#6290]
**Context:**
  System:
    OS: Windows 10 10.0.19042
    Memory: 3.21 GB / 5.98 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    playwright-chromium: ^1.10.0 => 1.10.0
    playwright-core: ^1.10.0 => 1.10.0

**Code Snippet**

```
npm install playwright-core
npm install --save-dev playwright-chromium
```

```
PLAYWRIGHT_BROWSERS_PATH=0
PWDEBUG=1
```

```javascript
import playwright from 'playwright-core';

(async () => {
    const { chromium: devChromium } = await import('playwright-chromium');

    console.log('chromium path:', devChromium.executablePath());

    try {
        const browser = await playwright.chromium.launch({
            executablePath: devChromium.executablePath(),
        });

        const page = await browser.newPage();

        await page.setContent('<html><body><h1>Hello World</h1></body></html>');

        await page.pause();
    } catch (e) {
        console.log(e);
        throw e;
    }
})();
```

**Describe the bug**

I use playwright-core for JS code, and playwright-chromium for Chromium binary, so I can run the code locally before packaging and deploying to AWS lambda with a different Chromium binary (chrome-aws-lambda instead of playwright-chromium).

The issue described here has nothing to do with AWS lambda, rather it is an issue of wiring up playwright-core with playwright-chromium. If you run the above code without PWDEBUG=1 environment variable, it will work fine. When I add the PWDEBUG=1 env variable, the code will throw an exception on the newPage() line:

```
'browser.newContext: Failed to launch chromium because executable doesn't exist at C:\XYZ\node_modules\playwright-core\.local-browsers\chromium-857950\chrome-win\chrome.exe
Try re-installing playwright with "npm install playwright"'
```

For some reason, Chromium is being searched for in `node_modules\playwright-core\.local-browsers`, even though the path I passed to the launch() via executablePath param is `node_modules\playwright-chromium\.local-browsers\chromium-857950\chrome-win\chrome.exe`

**Comment by dgozman** [comment]
Thank you for filing the issue! This problem was fixed in #6214, will be available with the next v1.11 release.
