### ISSUE TITLE
[Feature] allow for starting a browser with a hard-coded web-socket path for easier use

### ISSUE THREAD

**Issue by dimovelev** [microsoft/playwright#6291]
I start a browser in a docker container and connect to it from the host that started the container. Unfortunately the path is always randomly generated - https://github.com/microsoft/playwright/blob/master/src/browserServerImpl.ts#L56 and thus requires some work to fetch it and configure it in the host's test code.

I propose a new option to be added to the launch options specifying a path. Something like:
```
  const browserServer = await chromium.launchServer({
	  port: 8080,
	  path: 'playwright'
  });
```
If that option is provided then the given path is used otherwise it behaves as it does at the moment (generate a random path).

Alternatively, one could think about environment variable that can be set and has the same effect (if that is easier to implement and / or matches the design of the rest of the code).

**Comment by dimovelev** [comment]
If you are willing to accept the feature request I can provide a PR for it - beats my current sed -ir solution on the Javascript file 😀

**Comment by rwoll** [comment]
I'd find this feature helpful as well. We dynamically spawn docker containers that only call launchServer once in there lifetime and load balance externally. 

The logic would be greatly simplified if the the path could be specified at runtime.
