### ISSUE TITLE
[BUG]  Playwright Inspector hangs on waitingForResponse due to slowmo

### ISSUE THREAD

**Issue by ksawerykarwacki** [microsoft/playwright#6292]
**Context:**
  System:
      OS: Windows 10 10.0.19042
      Memory: 6.02 GB / 31.71 GB
  Binaries:
    Node: 15.11.0 - ~\scoop\apps\nodejs\current\node.EXE
    npm: 7.6.0 - ~\scoop\apps\nodejs\current\npm.CMD    
  Languages:
    Bash: 5.0.17 - C:\WINDOWS\system32\bash.EXE
  npmPackages:
    playwright: ^1.10.0 => 1.10.0 

**Issue Description**

We are testing Angular app with cucumber.js as test runner. For testing with Inspector we set slowmo, issue described occurs when slowmo >= 100

Playwright inspector hangs despite the fact that response is already received. Tests run without PWDEBUG works correctly. Disabling slowmo makes everything work right. 

The same issue occurs when runs without debug but with slowmo enabled and set above 100. Wait is just killed by cucumber.js timeout.

***First scenario***

![image](https://user-images.githubusercontent.com/11694791/115855066-25d1fd80-a42b-11eb-8db2-2f4be2e68a4d.png)

![image](https://user-images.githubusercontent.com/11694791/115855895-130bf880-a42c-11eb-9631-0c541605da17.png)

>   pw:api attempting click action +6ms
  pw:api   waiting for element to be visible, enabled and stable +0ms
  pw:api   element is visible, enabled and stable +17ms
  pw:api   scrolling into view if needed +1ms
  pw:api   done scrolling +1ms
  pw:api   checking that element receives pointer events at (581.31,496.76) +3ms
  pw:api   element does receive pointer events +4ms
  pw:api   performing click action +1ms
  pw:api   navigated to "http://alpha.localhost/fiscal-calendar/list" +110ms
  pw:api   click action done +591ms
  pw:api   waiting for scheduled navigations to finish +0ms
  pw:api   navigations have finished +2ms
  pw:api <= page.click succeeded +1ms
.  pw:api => page.waitForResponse started +2ms
  pw:api waiting for response "**/proxy/fiscal?*" +7ms

***Second Scenario***

![image](https://user-images.githubusercontent.com/11694791/115875949-0b594d80-a446-11eb-87c0-e3736e75139a.png)

![image](https://user-images.githubusercontent.com/11694791/115875999-16ac7900-a446-11eb-8974-bef0322d3502.png)

> pw:api attempting click action +4ms
  pw:api   waiting for element to be visible, enabled and stable +0ms
  pw:api   element is visible, enabled and stable +37ms
  pw:api   scrolling into view if needed +1ms
  pw:api   done scrolling +2ms
  pw:api   checking that element receives pointer events at (543.79,226) +2ms
  pw:api   element does receive pointer events +9ms
  pw:api   performing click action +2ms
  pw:api   click action done +710ms
  pw:api   waiting for scheduled navigations to finish +0ms
  pw:api   navigations have finished +2ms
  pw:api <= elementHandle.click succeeded +1ms
  pw:api => page.waitForResponse started +0ms
  pw:api waiting for response "**/proxy/fiscal/preview/*" +4ms

**Comment by dgozman** [comment]
I think there is a race condition in your snippet. The proper way to wait for response after a click would be to use `Promise.all`. See more about [waiting for events](https://playwright.dev/docs/events/#waiting-for-event).

```js
// Note that Promise.all prevents a race condition between clicking and waiting for the response.
await Promise.all([
  // Waits for the next response with the specified url
  this.page.waitForResponse('**/proxy/fiscal/preview/*),
  // Triggers the response
  this.calendarCellPickerPo.clickCell(calendarPopup, day),
]);
```

Does this help?

**Comment by dgozman** [comment]
Closing since there is no action item here. If you still have questions, please comment here.
