### ISSUE TITLE
Being able to run Firefox ESR

### ISSUE THREAD

**Issue by odinho** [microsoft/playwright#630]
Often it is not the newest browsers that breaks, but the older versions that no developers (or anyone else really) regularly tests on.

It would be really nice to be able to test Firefox ESR, as it is a browser that's kinda old but still being some kind of "faded evergreen".

**Comment by pavelfeldman** [comment]
We can't backport Playwright calabilities into all the major browsers retrospectively. What you are asking for will happen organically with time, but we facilitate it much.
