### ISSUE TITLE
[Question] Download in new tab waits forever

### ISSUE THREAD

**Issue by iamandras** [microsoft/playwright#6303]
Hello,

I have a page. If playwright (v1.10) clicks on a button the download unfortunately starts in a new tab.
Headful chrome on linux.

```
 const [ download ] = await Promise.all([
        page.waitForEvent('download'),
        page.click('.btn')
    ]);

 await download.path()
```

I know that this was asked already last year and there was no solution at that time (https://github.com/microsoft/playwright/issues/3689)

I also saw this comment in the tests.
https://github.com/microsoft/playwright/blob/f63f92be5ec891c4c8ca854fa64da2b73cae8267/tests/download.spec.ts#L278

Is it even possible to solve it on your side? 

Thanks,
Andras

**Comment by dgozman** [comment]
I think this should be fixed in the next v1.11 release - we were fixing some similar downloads issues. Please comment here whether it works for you when v1.11 is available.

**Comment by iamandras** [comment]
@dgozman thx for your answer. Do you mean this PR? https://github.com/microsoft/playwright/pull/6082/files
If I understood it correctly the download event will be detected on the browser level?

**Comment by dgozman** [comment]
Yep, that's the right PR, and it should go into v1.11.
