### ISSUE TITLE
[Question] Java Firefox Proxy

### ISSUE THREAD

**Issue by ArmanYeghiazaryan** [microsoft/playwright#6311]
Hello, 

I am using Java Playwright (Firefox). Looking for a solution to use a proxy in my browser. I would appreciate, if somebody could show me a Java code snippet for using a proxy. 

Thank you a lot!

**Comment by mxschmitt** [comment]
Something like that should work:

```java
package org.example;

import com.microsoft.playwright.*;

public class PrintTitle {
  public static void main(String[] args) {
    try (Playwright playwright = Playwright.create()) {
      Browser browser = chromium.launch(new BrowserType.LaunchOptions()
        .setProxy(new Proxy("http://myproxy.com:3128")
        .setUsername('usr')
        .setPassword('pwd'));
      BrowserContext context = browser.newContext();
      Page page = context.newPage();
      page.navigate("http://playwright.dev");
      System.out.println(page.title());
    }
  }
}

```

See here for the full docs: https://playwright.dev/java/docs/network#http-proxy

**Comment by pavelfeldman** [comment]
See our docs for more details. https://playwright.dev/java/docs/network/#http-proxy

**Comment by dgozman** [comment]
If you have any more questions, please comment here and we'll reopen.
