### ISSUE TITLE
[BUG] Downloaded file name is UUID and extension is lost

### ISSUE THREAD

**Issue by Kremliovskyi** [microsoft/playwright#6316]
**Context:**
  System:
    OS: Windows 10 10.0.19042
    Memory: 7.78 GB / 19.43 GB
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 7.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Bash: 4.4.19 - C:\WINDOWS\system32\bash.EXE
  npmPackages:
    playwright: ^1.11.0-next-alpha-apr-20-2021 => 1.11.0-next-alpha-mar-31-2021

**Code Snippet**
some fragments, everything else is default:
```javascript

        await browser.newContext({
                deviceScaleFactor: 1,
                acceptDownloads: true
         })

        await page.goto('https://some-url/findings/908543')

        const [ download ] = await Promise.all([
            page.waitForEvent('download'), 
            page.click('.toolbar .download-pdf-download')
        ]);
        
        const path = await download.path();
        console.log(path)
```

**Describe the bug**

Whenever I download file which is supposed to be PDF playwright downloads it without extension and proper name (it changes name to some UUID). Whenever I download file manually everything is fine. It looks like this 
![image](https://user-images.githubusercontent.com/12884831/116007843-5b890900-a61a-11eb-99ff-286b785046e6.png)

As I understand file is processed by js in front end if it matters. I do not see any call to back end for it.

**Comment by dgozman** [comment]
Use [`download.suggestedFileName`](https://playwright.dev/docs/api/class-download/#downloadsuggestedfilename) to get the file name. You can also use `download.saveAs()` to move the file anywhere you'd like.
