### ISSUE TITLE
[BUG] setInputFiles does fetch that fails due to CSP

### ISSUE THREAD

**Issue by sadiqueimam** [microsoft/playwright#632]
Hi, I am trying to upload a file but getting below error:
Error: Evaluation failed: TypeError: Failed to fetch
    at __playwright_evaluation_script__:3:30
    at Array.map (<anonymous>)
    at __playwright_evaluation_script__:2:46
    at CRExecutionContext.evaluate 

Code: 
const drop= await page.waitForSelector("//input[@type='file']");
 await drop.setInputFiles('pic.png')

Also, the same was working with below Puppeteer code:
const drop= await page.waitForXPath("//slot/input[@type='file']");
await drop.uploadFile('pic.png');

**Comment by JoelEinbinder** [comment]
Can you provide a small script that reproduces the problem? I tried and was unable to:

```js
const {chromium} = require('.');
chromium.launch().then(async browser => {
    const [page] = await browser.defaultContext().pages();
    await page.setContent(`<input type="file">`);
    const input = await page.$('input');
    await input.setInputFiles('index.js');
    await browser.close();
});
```

**Comment by sadiqueimam** [comment]
I have tried the code and it works fine if the button is clickable but in my scenario the button is kind overlays by a label. If I do drop.click(); it fails so I tried drop.setInputFiles('pic.png') but this doesnt seem to work for me. Is it an open issue?

**Comment by dgozman** [comment]
Clickability should not affect `setInputFiles`, so the reason should be something else. If you could share the page where this does not work (a link or maybe saved as mhtml), I would be happy to take a look. Thank you!

**Comment by dgozman** [comment]
Closing because we cannot repro this for a while. Feel free to reopen if this is still an issue.

**Comment by jacobmesu** [comment]
This error occurs when content security policy on document is enabled. Fix it by disabling CSP by setting bypassCSP to true in newContext method.

**Comment by klctrl** [comment]
Disabling CSP fixed it for me as well, thanks for the hint. 

There should be a user-editable (possibly via PRs) FAQ section on playwright.dev where people can put their HOWTOs, tips & tricks and so on.

**Comment by dgozman** [comment]
> (There should be a user-editable (possibly via PRs) FAQ section on playwright.dev where people can put their HOWTOs, tips & tricks and so on.)

You can send a PR editing [documentation source](https://github.com/microsoft/playwright/tree/master/docs), it will be reflected on [playwright.dev](https://playwright.dev).

As for the fetch error, let me take a look. Disabling CSP is a big hammer, so I'd prefer another solution.

**Comment by klctrl** [comment]
@dgozman Thanks for pointing out the link to the documentation source.

Also thanks for looking again into this error. I have sent you the repro URL via email.
