### ISSUE TITLE
[Feature Request] Text Selector like :has-text("") but Strict & Case Sensitive > :has-text-is("")

### ISSUE THREAD

**Issue by garciallorente-fer** [microsoft/playwright#6326]
Text Selector like :has-text("playwright") but Strict & Case Sensitive

Example:
await page.click('article:has-text("Playwright")'); would not work for some specific cases if there are 2 article that have different texts and both contains the word "Playwright"

Using await page.click('article:text-is("Playwright")'); does not work

The possibility of searching for elements that contain the exact text introduced would be very useful for multiple things

There is a possibility currently using the old way of selectors *css=article >> text="Playwright Two"
But that doesnt work well when using it with other selector engines
Example: div:has(article:has-text("Playwright") would not work with this other way

So that feature would be very needed for a lot of cases and I am sure it would help a lot of people when selecting elements that have very similar texts or texts that contains the same words

**Comment by mxschmitt** [comment]
The `has-text` pseudo selector has currently not yet a way built it for matching exactly for it. It does internally convert it to lower-case. You could use the Playwright `text=` selector or the `text-is` pseudo-selector, an example would look like:

```js
// @ts-check
const playwright = require('playwright');

(async () => {
  const browser = await playwright.chromium.launch();
  const page = await browser.newPage();
  await page.setContent(`
      <div>
        <span>
          kekTop
        </span>
      </div>
    `);
  await page.waitForSelector("div >> text=kekTop") // matches
  await page.waitForSelector("div >> text=kektop") // matches

  await page.waitForSelector("div >> text='kekTop'", { timeout: 1000 }) // does match
  try {
    await page.waitForSelector("div >> text='kektop'", { timeout: 1000 }) // does not match
  } catch (err) { console.log("threw", err) }

  await page.waitForSelector("span:text-is('kekTop')", { timeout: 1000 }) // does match
  try {
    await page.waitForSelector("span:text-is('kektop')", { timeout: 1000 }) // does not match
  } catch (err) { console.log("threw", err) }

  await browser.close();
})();
```

See here for more docs: https://playwright.dev/docs/selectors/#text-selector

**Comment by garciallorente-fer** [comment]
If I am not mistaken the text-is pseudo-selector doesnt work if the text is in the subtree of the element that is wanted to be selected, the example you proposed works because it is the same element

What would be very good and uself to have would be a **:has-text-is("")** that would work the same way as the :has-text() but in a strict and case sensitive way, avoiding problems like the one I mentioned before, and would be very useful to use to make sure we are selecting the element that contains the exact same text and not includes that text , which can lead to some errors

Regarding the "div >> text='kektop" , again same problem, it would only work if we want to select the element that contains that text but its not the same functionality as :has-text() as with that it **matches any element containing specified text somewhere inside, possibly in a child or a descendant element**

If using "*css=div >> text='kektop'" is the old way of doing it and cannot be implement alongside these other engine selectors 
Example: div:has(*css=div >> text='kektop') would not work, but **div:has(div:has-text-is('kektop'))** would work and would match the element that contains only that specified work kektop, not other elements containg that same word

So I would insist in the necessity of creating a **:has-tex-is() pseudo-class**, as I think it would be very useful and improve massively the element selector engine of Playwright, and in some cases would be even more recommended to use than the :has-text("") one

**Comment by mxschmitt** [comment]
Thanks for the detailed input!

cc @dgozman

**Comment by dgozman** [comment]
@garciallorente-fer Would the following work for you?
```js
await page.click('article:has(:text-is("Playwright"))');
```

**Comment by garciallorente-fer** [comment]
Hi @dgozman ,that would work indeed! Thanks for the solution.

I never thought of that possibility as then it would be the same for :has-text() where you could just do :has(:text(""))

Maybe it would be worth adding it to the documentation an example for those people that have the same problems as me, (the cases mentioned earlier) :)

Thanks also @mxschmitt for the quick replies and the help

**Comment by dgozman** [comment]
@garciallorente-fer Sounds great! We already have [documentation](https://playwright.dev/docs/selectors#selecting-elements-that-contain-other-elements) for `:has()`, but I'll see how we can make things better in this area.
