### ISSUE TITLE
[Question] CDP Session on Webkit and Firefox

### ISSUE THREAD

**Issue by RoxyAndElsewhere** [microsoft/playwright#6334]
How does one get a CDP session object with Webkit or FireFox?

```
const browser = await webkit.launch();
const context = await browser.newContext();
const page = await context.newPage();
const session = await page.context().newCDPSession(page);  // fails with 'TypeError: page.context(...).newCDPSession is not a function'

```
For what it's worth, I'm using plain JS, not TS so the "just cast it to ChromiumBrowserContext" solution provided elsewhere isn't an option.

**Comment by mxschmitt** [comment]
CDP is the [Chrome DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/) which is only available in Chromium based browsers like Google Chrome, or Microsoft Edge etc. For Firefox or WebKit it is not available.
