### ISSUE TITLE
[Question]Playwright: Cant fill out the "share with other people" field in Googlesheet

### ISSUE THREAD

**Issue by Smiro3** [microsoft/playwright#6338]
H Guys,

I am trying to automatically share a google sheet with other people but i cant fill out the "Add people and groups" field. I tried:

wait newPage.type('css=input','email') but in this way it types the email in the sheet title field.
I also tried await newPage.fill('text=Add people and groups ', 'email') but it throws me an error tht says that the selector cant be found.

Any suggestions on how to go about this?
Thanks!

![image](https://user-images.githubusercontent.com/76685636/116197139-9f703100-a734-11eb-9556-85ffb201b9e4.png)

**Comment by mxschmitt** [comment]
You can use Chrome DevTools to inspect their DOM, there you can obtain that they have the `aria-label` Node property set, you can use it by using e.g. such a selector: `page.type("[aria-label='Add people and groups']", "foobar")`.

For all the supported selectors, see the documentation here: https://playwright.dev/docs/selectors

**Comment by Smiro3** [comment]
Thanks @mxschmitt , i tried that ( and other available aria-label as well) but it seems like it cant find it:



![image](https://user-images.githubusercontent.com/76685636/116223025-6a250c80-a74f-11eb-8bc3-d01d10196089.png)

**Comment by mxschmitt** [comment]
Consider using the debugging tools to understand why its not finding the element, it gives insights why its ending up in a timeout in the end: https://playwright.dev/docs/debug

**Comment by Smiro3** [comment]
Hi @mxschmitt , sorry to bother you again. I tried what you suggest but im not sure i m doing it in the right way. I used set DEBUG=pw:api  and then luanched the script. I ve got this:
Is what am i supposed to get? Ralted questiion, do you reckon this way of selecting a class ('css=[.boqDrivePeopleWebMultiselectInputchipInputBase.boqDrivePeopleWebMultiselectInputchipTextField]') should work?
![image](https://user-images.githubusercontent.com/76685636/117107922-bb05b800-ad82-11eb-969f-5dc1aebb4d27.png)

**Comment by mxschmitt** [comment]
This is not a valid selector, you can do:

`.boqDrivePeopleWebMultiselectInputchipInputBase.boqDrivePeopleWebMultiselectInputchipTextField `

to select elements which have these two classes, for more information see here: https://playwright.dev/docs/selectors and how CSS selectors are working see here: https://www.w3schools.com/cssref/css_selectors.asp

**Comment by Smiro3** [comment]
Hi @mxschmitt i tested what i want to do with npx plawright and to fill out the field i need to fill it generetaed the followng:
![image](https://user-images.githubusercontent.com/76685636/117263439-911bc680-ae52-11eb-8a0f-77c2ea95816e.png)



but when i try in my code it gives the same error:

![image](https://user-images.githubusercontent.com/76685636/117263467-96791100-ae52-11eb-8cc3-500bdf148f2a.png)

i tried with the .frame and without it but still get the same error

Any thoughts?

Thanks again for your patience
