### ISSUE TITLE
[Suggestion]: update bug report template -> npx envinfo --markdown

### ISSUE THREAD

**Issue by jsjoeio** [microsoft/playwright#6355]
In the bug report template, you ask users to run `npx envinfo`.

I suggest you change that to -> `npx envinfo --markdown`. That way, when they copy it in, it's formatted nicely.

Source: [envinfo CLI options](https://github.com/tabrindle/envinfo#cli-options)

**Comment by mxschmitt** [comment]
Sounds good to me, thank you for the suggestion. :+1:
