### ISSUE TITLE
Stream or capture Video into buffer [Question]

### ISSUE THREAD

**Issue by alexsorinsky** [microsoft/playwright#6373]
how to stream video similar like make screenshots [into buffer](https://playwright.dev/docs/screenshots#capture-into-buffer) ?

**Comment by mxschmitt** [comment]
Currently you can only read it from the filesystem (via fs.readFile) using the path from `video.path()` see here: https://playwright.dev/docs/api/class-video
What is your use-case for having it in the memory?

**Comment by alexsorinsky** [comment]
well, i need to be able to review testing process in headless mode.
lets say i'd like to catch the videostream from playwrite's browser and figure out whether everything fine or there are some errors there

**Comment by mxschmitt** [comment]
Why is it not enough to see the video once the test is e.g. completed or failed? Curious to know more about this use-case.

**Comment by hubertlepicki** [comment]
I would also like to capture / stream the video as the tests are executing. Currently I am thinking this would either require me to hack on Playwright as it seems like the frame capture -> ffmpeg -> save video thing is hardcoded and can't be customized, i.e. I can't access the captured frames and/or stream from my JavaScript code.

I am considering the alternative in form of building a Chrome extension based on this sample: https://github.com/orbitbot/chrome-extensions-examples/tree/master/tabCapture

The downside here is that it will not work in headless set up, as Chrome extensions are not supported in headless mode.

**Comment by hubertlepicki** [comment]
You have asked for a use case: I am building a tool that would allow mere mortals build some simple test cases, and provide building blocks for navigation, filling in forms etc. and possibly also record / replay functionality but I'd have to also figure out how to capture / forward user interaction / input events.

**Comment by JoelEinbinder** [comment]
We are still missing the use case for directly returning a buffer instead of reading it from the path. Everything described could be done by saving the video to a temporary directory and then reading them. There is a lot of complexity with this api because we don't know how many video streams there will be when the context is first created. Closing this for now, feel free to open a new issue with a use case that isn't solved by reading from the video file.

**Comment by alexsorinsky** [comment]
> Everything described could be done by saving the video to a temporary directory and then reading them. 

the problem with this approach is that i'l be able to overview the recorded video only **after** the testing sequence has been done but not realtime while testing is in progress.

is there any way to stream testing process as video stream instantly?
