### ISSUE TITLE
[Question] How to run tests on docker which points to other than localhost url?

### ISSUE THREAD

**Issue by szamacz** [microsoft/playwright#6382]
Is there a way to run playwright tests on docker, which will be pointing to some deployed application, like www.google.com? All examples that I found describing running tests on via localhost.

**Comment by mxschmitt** [comment]
To which examples do you refer to?

Using different application environments on different URLs means generally only switching the base URL or the URL where you navigate to (Page.goto).

**Comment by szamacz** [comment]
Apologize If I wasn't clear enough in my question.
I have my tests in the repository and build agents on azure devops. I would like to run tests on this build agent against google page.  This is not the case of continuous integration but scheduled run. In your [documentation ](https://playwright.dev/docs/docker) you have mentioned how to run docker image with playwright, but there is no example of how to run tests on it it - or maybe I miss something.

**Comment by mxschmitt** [comment]
Playwright is a library to automate and control browsers, which test-runner you choose is up to you, e.g. Jest, Mocha or Cucumber are common solutions. To have custom links for your testing environments, you can e.g. setup your CI to inject the base URL as environment variables, and access to e.g. `process.env.BASE_URL` during the runtime/test-execution.
Does this answer your question?

**Comment by szamacz** [comment]
Not really. I know the purpose of this tool and I'm using dotnet test runner (c# bindings),setup tests that they are running in headless mode on my Linux build agent. Is there any separate setup to run them on docker (like  RemoteWebDriver in case of Selenium) or I should just copy my test code to docker image [docker image playwirght](https://hub.docker.com/_/microsoft-playwright) and run tests there?

**Comment by mxschmitt** [comment]
Oh didn't know that you are using the C# bindings. For the there is no official Docker image yet available, you can use the official one and install dotnet e.g. or wait until the C# bindings reach version 1.0 then there should be an image available.

**Comment by LGinC** [comment]
dockerfile:
> FROM mcr.microsoft.com/playwright
RUN apt-get update; \\
    apt-get install wget apt-transport-https && \\
    wget https://packages.microsoft.com/config/ubuntu/20.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \\
    dpkg -i packages-microsoft-prod.deb && \\
    rm packages-microsoft-prod.deb && \\
    apt-get update && apt-get install -y dotnet-runtime-5.0 && \\
    apt-get clean
WORKDIR /app
COPY . .
ENTRYPOINT ["dotnet", "ConsoleApp.dll"]`


replace ConsoleApp.dll  to  name of  your dll
