### ISSUE TITLE
[Question] How to use the docker container

### ISSUE THREAD

**Issue by MoSattler** [microsoft/playwright#6383]
Hi!

I am super new to playwright, so this might not be a good question

I am currently trying to use the docker container for e2e tests in local development and the CI. 
Whenever I was doing this in cypress, I just have to run the image and it executes all tests that I added via a volume to the image. 

In playwright, it's not quite clear to me on how to achieve this. When executing the image, I just bash into the container. But how do I execute the tests? Running `playwright` does not work. Is there maybe any example on how the docker image is meant to be used?

Keep up the great work!
Moritz

**Comment by mxschmitt** [comment]
Playwright is a library to automate browsers and gives the way of executing the tests to the user, they then can use their test runner (Jest, folio, mocha, cucumber etc.) by that the image does not automatically run your tests, but this sounds also interesting.
The Docker image which Playwright provides is currently designed to be used as a Docker base image, so all operating system dependencies are then satisfied and you can do your `npm install` e.g. with your test-runner in it. So you can either mount there your repository or clone it directly which is mostly done when its used as a CI runner image.
Let me know if this didn't answer your question, thanks!

**Comment by MoSattler** [comment]
Thanks for the answer @mxschmitt, that makes sense. If I understand you correctly, the docker image is more of a prepared runtime environment for playwright + browsers, but does not ship playwright itself. 
I think that makes a lot of sense, and I can work with that. 

Thank you!
