### ISSUE TITLE
[Feature] Documentation of the ability to target <select> element by label text in page.selectOption

### ISSUE THREAD

**Issue by torkjels** [microsoft/playwright#6384]
It would be nice to have a feature for `page.selectOption` that is similar to what was done in https://github.com/microsoft/playwright/pull/4342. It would allow us to target a `<select>` based on the accompanying label.
```
<label for="my-select">Choose a color</label>
<select id="my-select">
  <option value="red">Red</option>
  <option value="blue">Blue</option>
</select>

await page.selectOption('text="Choose a color"', 'blue');
```

**Comment by torkjels** [comment]
I see that this is a duplicate of #4400 which was resolved by #4402, which is great! :raised_hands:  But I don't see this anywhere in the documentation, it would be good to have it documented somewhere.

**Comment by klhex** [comment]
Shouldn't the last line in your code example rather be

```javascript
await page.selectOption('text="Choose a color:"', 'blue');
```
than
```javascript
await page.selectOption('text="My dropdown label"', 'blue');
```
?

**Comment by torkjels** [comment]
Yes, classic copy-paste error :wink: Point still stands, though

**Comment by thernstig** [comment]
This is documented here, or am I missing something? https://playwright.dev/docs/input#select-options

**Comment by mxschmitt** [comment]
cc @dgozman, thx

**Comment by klhex** [comment]
@thernstig No, the current documentation only relates to a select element's values, not the element itself.
