### ISSUE TITLE
[BUG] playwright install / Failed to install browsers

### ISSUE THREAD

**Issue by mrjebabli** [microsoft/playwright#6385]
**Context:**
- Playwright Version:  playwright-1.10.0
- Operating System: Windows 10
- Node.js version: not installed i use python not node 
- Extra: first installation 

**Describe the bug**
i want to install playwright, its well downloaded, and i get Successfully installed greenlet-1.0.0 playwright-1.10.0 pyee-8.1.0.
but playwright install returns:
Failed to install browsers
Error: Failed to download chromium, caused by
Error: getaddrinfo ENOTFOUND playwright.azureedge.net
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26).

i am using 
Python 3.9.4
pip 20.2.3

can you please suggest a workaround

**Comment by mxschmitt** [comment]
This means your operating system is not able to resolve the nameserver of `playwright.azureedge.net` which is required to use Playwright. Could you try setting e.g. [Google DNS ](https://developers.google.com/speed/public-dns)or [Cloudflare DNS](https://1.1.1.1) on your system and see if it resoles this issue?

**Comment by mrjebabli** [comment]
yes true, my problem was related to proxy .
now i can reach playwright.azureedge.net 
thanks

> This means your operating system is not able to resolve the nameserver of `playwright.azureedge.net` which is required to use Playwright. Could you try setting e.g. [Google DNS ](https://developers.google.com/speed/public-dns/docs/using#windows)or [Cloudflare DNS](https://1.1.1.1) on your system and see if it resoles this issue?
