### ISSUE TITLE
Not a bug, but a question. Can we run tests in parallel?

### ISSUE THREAD

**Issue by rightqa** [microsoft/playwright#639]
Thanks for the amazing tool (it's amazing so far!) I have a quick question though. Say I write a test and I want to run the same test against Chrome and Firefox, can we run same tests in parallel against different browsers?

**Comment by JoelEinbinder** [comment]
Yes, although you will have to write a bit of scaffolding today.

```js
const {chromium, firefox} = require('playwright');
(async function() {
  console.log('starting firefox and chromium tests.');
  await Promise.all([
      test(firefox),
      test(chromium)
    ]);
  console.log('done');
})();

async function test(launcher) {
    const browser = await launcher.launch();
    // run your test with the browser
    await browser.close();
}
```

**Comment by rightqa** [comment]
> Yes, although you will have to write a bit of scaffolding today.
> 
> ```js
> const {chromium, firefox} = require('playwright');
> (async function() {
>   console.log('starting firefox and chromium tests.');
>   await Promise.all([
>       test(firefox),
>       test(chromium)
>     ]);
>   console.log('done');
> })();
> 
> async function test(launcher) {
>     const browser = await launcher.launch();
>     // run your test with the browser
>     await browser.close();
> }
> ```

Thanks @JoelEinbinder , will give it a try. Is there a plan to have built in within playwright?

**Comment by JoelEinbinder** [comment]
My thought is that this is a job for a test runner, like jest or mocha. We definitely want a good story around it to exist, but haven't started to look at it yet.

**Comment by vania-pooh** [comment]
@rightqa JFYI we added remote parallel Playwright test execution support on the remote side in recent release of [Moon](https://aerokube.com/moon/). It was initially running Selenium tests in parallel in Kubernetes cluster, but is now able to do the same with Playwright. Documentation about it is here: https://aerokube.com/moon/latest/#_using_playwright It is a free solution up to 4 parallel browsers, but requires a license if you need more. We also have plans to deliver the same in our open-source solution called Selenoid.

**Comment by rightqa** [comment]
Thanks @vania-pooh , will take a look.
