### ISSUE TITLE
[BUG] relative downloadsPath does not work on Windows

### ISSUE THREAD

**Issue by PhilAndrew** [microsoft/playwright#6401]
**Context:**
- Playwright Version: 1.10.0
- Operating System: Windows
- Node.js version: v14.15.4
- Browser: Chromium

**Code Snippet**

I copied this file into my project and ran.
https://github.com/nmanikiran/playwright-demos/blob/master/download.js

**Describe the bug**

If I run it with ```const browser = await chromium.launch({ headless: false });```
Then I see it say at the bottom left of the page "Failed - download error".

**Comment by mxschmitt** [comment]
Playwright has a download functionality built in which works across all browsers (not only Chromium via the CDP session which is how your example is doing it). Try to follow the official guides for [Download](https://playwright.dev/docs/downloads) to check if it solves your problem.
