### ISSUE TITLE
[BUG] Playwright Inspector out of view

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright#6416]
**Context:**
- Playwright Version: [what Playwright version do you use?] Version 1.10.0-next-1616530863000
- Operating System: [e.g. Windows, Linux or Mac]  WIndows 10 10.0.19043 N/A Build 19043
- Node.js version: [e.g. 12.22, 14.6] Python 3.9
- Browser: [e.g. All, Chromium, Firefox, WebKit] All
- Extra: [any specific details about your environment]

**Code Snippet**

Try to launch playwright for codegen
```shell
$ playwright codegen https://github.com/
```

**Describe the bug**

When the playwright inspector is launched, It is out of my view of my display, so I clicked on taskbar with <kbd>shift</kbd> and clicked maximised I got inspector full screen but wasn't able to get inspector without maximising it.

![Screenshot (58)](https://user-images.githubusercontent.com/59607654/117133513-f7a4d400-adc1-11eb-96b2-551a60904881.png)

![Screenshot (60)](https://user-images.githubusercontent.com/59607654/117134177-de505780-adc2-11eb-98a1-16c5afdbc445.png)

**Comment by yury-s** [comment]
This is the same issue as #5696, closing as duplicate.
