### ISSUE TITLE
Feature Request: Can we make Playwright Codegen ignore certificates?

### ISSUE THREAD

**Issue by lecaroman** [microsoft/playwright#6418]
Currently, when using playwright codegen over http**s** sites, an error is returned. Example:

`>playwright codegen wikipedia.org `
returns
`page.goto: net:: ERR_CERT_AUTHORITY_INVALID at http://wikipedia.org`

Can we have something accessible like this?
`playwright codegen --ignore_http_errors=True`

There is a workaround [here](https://stackoverflow.com/questions/67048422/ignore-ssl-errors-with-playwright-code-generation), via jest, but I was aiming for a fast CLI solution via python.

Thanks!

**Comment by mxschmitt** [comment]
You can run the codegen with a custom setup, for that you can call `page.pause()`. See here: https://playwright.dev/python/docs/cli/#codegen-with-custom-setup
