### ISSUE TITLE
[Feature] Allow custom selectors to use :nth-match

### ISSUE THREAD

**Issue by NickTulett** [microsoft/playwright#6459]
Allow selectors with = to be used in :nth-match clauses

Currently `:nth-match(text=foo)` will fail a syntax check

Also if you define a custom selector "tag" `:nth-match(tag=bar)` is not allowed

It would be good if :nth-match could support custom selectors.

Java v.1.10.0

**Comment by pavelfeldman** [comment]
There is n-th in our new locators api, i think it should work for you!
