### ISSUE TITLE
getDisplayMedia in headless

### ISSUE THREAD

**Issue by ldenoue** [microsoft/playwright#6460]
I would like to record the current page using getDisplayMedia().

It works now in headful, not headless.
I launch the browser using these args:
```
browser = await playwright.launch({
		headless:**false**,
		ignoreHTTPSErrors:true,
		args: [
      '--enable-experimental-web-platform-features',
      '--disable-infobars',
      '--enable-usermedia-screen-capturing',
      '--allow-http-screen-capture',
      '--auto-select-desktop-capture-source=**MYPAGETITLE**',
      '--ignore-certificate-errors',
      '--no-sandbox',
      '--autoplay-policy=no-user-gesture-required',
      '--disable-gpu',
      '--hide-scrollbars'
    ],
	});
```

and inside my web page loaded by the browser, I can now use 
```
canvasStream = await navigator.mediaDevices.getDisplayMedia();
``` 

and I indeed get the stream of the tab.

However, it fails when headless = true;

Do you think others might benefit from this as well?
I believe that running headless is much easier since it doesn't require us running a virtual display (e.g. xvfb).

**Comment by aslushnikov** [comment]
@ldenoue There's no screen capture in headless chrome, so it won't work there. And I'm not aware of any plans to support it.
However, playwright has a screen recording API that works across broowsers: https://playwright.dev/docs/videos

Would it work for you?

**Comment by aslushnikov** [comment]
> Instead of dispatching NotifyScreencastFrame it would be amazing to feed this directly to the video encoder

@ldenoue Actually, we do this already: 
https://ffsearch.azurewebsites.net/#path=%2Fhome%2Fjoe%2Fplaywright%2Fbrowser_patches%2Ffirefox%2Fcheckout%2Fjuggler%2Fscreencast%2FScreencastEncoder.cpp&line=228

Or do I fail to understand something? 

> not quite since I need audio as well.

Interesting! Would you mind sharing your usecase? We didn't know audio was of much importance for anybody.

**Comment by ldenoue** [comment]
@aslushnikov thanks for sending me this link, I now understand that on Firefox (and webkit too I think), the video is generated on the fly using a VPX encoder.
I noticed that the resulting videos are much more grainy than when using Chromium (which uses FFMPEG I believe).
Is there a reason why the webm generated by Firefox and Webkit are of inferior quality?
I've attached 3 screenshots to illustrate: one for chromium, firefox and webkit.

I'm using MacOS, perhaps people have no issue on other platforms?

I also noticed that the fps seems hardcoded to 25. Could we change that when requesting to capture a video?
https://ffsearch.azurewebsites.net/#path=%2Fhome%2Fjoe%2Fplaywright%2Fbrowser_patches%2Ffirefox%2Fcheckout%2Fjuggler%2Fscreencast%2FScreencastEncoder.h&line=24

Chrome 
![image](https://user-images.githubusercontent.com/149561/117579242-546dfa80-b0f2-11eb-897f-abd4f705552e.png)

Firefox 
![image](https://user-images.githubusercontent.com/149561/117579257-5f288f80-b0f2-11eb-9cdb-ea0b8ef9f348.png)

Webkit 
![image](https://user-images.githubusercontent.com/149561/117579270-694a8e00-b0f2-11eb-935d-1dcbd5ff7e74.png)

**Comment by aslushnikov** [comment]
> thanks for sending me this link, I now understand that on Firefox (and webkit too I think), the video is generated on the fly using a VPX encoder.

@ldenoue yes, this is the case. Just in case, here's a [WebKit reference](https://wksearch.azurewebsites.net/#path=%2Fhome%2Fjoe%2Fplaywright%2Fbrowser_patches%2Fwebkit%2Fcheckout%2FSource%2FWebKit%2FUIProcess%2FInspector%2FAgents%2FScreencastEncoder.h&line=56).

> I also noticed that the fps seems hardcoded to 25. Could we change that when requesting to capture a video?

Sure! Do you want to submit a PR? 

> For audio capture, do you know where we could we tap into the browser's audio output, like e.g. Firefox does in HeadlessCapture.cpp ?

Unfortunately, I didn't look in the audio capture. Do you want to investigate?

> Is there a reason why the webm generated by Firefox and Webkit are of inferior quality?

Actually, I'd recommend talking to @pavelfeldman  on slack: https://aka.ms/playwright-slack He's currently refactoring screencast implementation across browsers, so he has a lot of relevant context. And it looks like we all are in the same time zone :)

**Comment by aslushnikov** [comment]
The discussion here seemed to stale - closing this for now. Please re-submit to continue discussion (we're much better at looking in open issues than through closed ones)

**Comment by ldenoue** [comment]
@aslushnikov I was on vacation last week. I found a project https://github.com/centricular/gstcefsrc that uses Chromium Embedded Framework to provide video and audio recording.
Perhaps the source code would be useful to know how they tap into the audio part?
Notice that at the moment gstcefsrc requires running a frame buffer like xvfb-run, so it's not completely headless.

I won't submit a PR now for the FPS because the quality issues don't come from the frame rate, but most likely from the parameters of the VP8 encoder (notice the pixelation for both Firefox and Webkit, whereas Chrome's frames look much higher quality because "we" use ffmpeg instead of the VP8 encoder I guess).
