### ISSUE TITLE
Other Browsers

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright#647]
Mega issue to discuss playwright support for more platforms.

## Older versions of our core browsers
- Firefox Stable/ ESR (#630)
- Safari general release
- Chromium stable

As we upstream our patches and time goes on, the current versions of the browsers playwright supports will naturally be the older versions. Firefox ESR is supported for up to a year though, so we might get some value by specifically releasing an older version.

## Branded Chromium
- Edge
- Chrome
- Opera

These should just work today by specifying `executablePath` and running with the `chromium` object. They provide some small value over testing against the Chromium we download because they turn on different feature flags, and can play different media types. We could be doing more to help people with compatibility between the playwright package version and the specific branded browser they have.

## Electron
- Electron (#584)

Electron is supported with `playwright-electron` package.  

## Mobile Browsers
- iOS Safari
- Android Chrome

Right now we fake these browsers. It would be cool to be able to run tests directly against them. Maybe we can use the IOS simulator? 

## Internet Explorer
- IE 11 (#594)
- IE 10 (#594)
- EdgeHTML

IE is still around somehow, and people want to test against it. The new Edge is based on Chromium, but still has an IE mode. It's very unlikely we would get our full feature set into IE. But having a small playwright-compatible subset of features could help tide people over until IE finally goes away. We could potentially wrap the work that has been done on WebDriver here.

**Comment by headlesstesting** [comment]
We've been experimenting with different browsers and Playwright.
Edge is working fine, however Opera (68) does not work yet, this is returning an error:
`Browser.setDownloadBehavior' wasn't found` at the start of the session.

**Comment by mxschmitt** [comment]
I can confirm that these browsers are working:
- Microsoft Edge Canary  85.0.563.0 
- Google Chrome Canary  86.0.4187.0
- Brave Nightly - 1.12.64 Chromium 83.0.4103.116

but these not:
- Opera Developer edition 71.0.3735.0 - Chromium 86.0.4187.0
- Vivaldi Snapshot 3.2.1964.3  - Chromium 84.0.4147.62

A working Opera version would be probably useful.

**Comment by 12masta** [comment]
@mxschmitt Hey, how to execute playwright with Edge Canary? Could you share that knowledge somewhere?

**Comment by mxschmitt** [comment]
> @mxschmitt Hey, how to execute playwright with Edge Canary? Could you share that knowledge somewhere?

Hey! I created a blog post about it, let me know if I forgot something.
https://playwright.tech/blog/automate-microsoft-edge-with-playwright

**Comment by NareshMurthy** [comment]
Hey @mxschmitt,
I see that playwright uses firefox nightly 78 right now,  I tried to run tests on firefox-stable present at `'/Applications/Firefox.app/Contents/MacOS/firefox' `.  I could see the browser launching, but it directly goes to https://0.0.0.0
Is there a way we could use firefox stable build with playwright?

**Comment by mxschmitt** [comment]
> Hey @mxschmitt,
> I see that playwright uses firefox nightly 78 right now, I tried to run tests on firefox-stable present at `'/Applications/Firefox.app/Contents/MacOS/firefox' `. I could see the browser launching, but it directly goes to https://0.0.0.0
> Is there a way we could use firefox stable build with playwright?

Hi, my blog post only relates to Chromium based browsers. For Firefox or WebKit it's not possible to use own versions since Playwright internally injects there some wrappers to provide the APIs to automate it on compile time.

**Comment by rudeshkumar** [comment]
How to launch opera browser in playwright??

**Comment by mxschmitt** [comment]
> How to launch opera browser in playwright??

Use Chromium to launch a browser and set your opera as a executable path when launching chromium.

**Comment by rudeshkumar** [comment]
can you please share any example for this?

**Comment by mxschmitt** [comment]
```ts
    const browser = await playwright.chromium.launch({
      executablePath: '/foo/bar/foobar'
    });
```

this then depends on which OS you use, on Windows its e.g. on C:/Programs etc. on mac in /Applications etc.
