### ISSUE TITLE
[Feature] Timestamp for videos

### ISSUE THREAD

**Issue by NickTulett** [microsoft/playwright#6478]
Could you embed a per-frame timestamp in the recorded video, so that it can be synced with the debug log to make investigation easier? 

This would save having to continually take screenshots when debugging.

If you could embed each line from the log, so much the better.

**Comment by JoelEinbinder** [comment]
@pavelfeldman this is a customer for tracing?

**Comment by pavelfeldman** [comment]
Yes, let's see if a new feature release in 1.12 will help you.

**Comment by NickTulett** [comment]
Yes the trace viewer is a much better solution, thanks!
