### ISSUE TITLE
[Question] How to set path for local exe?

### ISSUE THREAD

**Issue by tomByrer** [microsoft/playwright#6483]
Hi, migrating from Puppeteer.  I can use FxDev in Puppeteer on local machine as:
```js
browser = await puppeteer.launch({
  executablePath: `C:\\Program Files\\Firefox Developer Edition\\firefox.exe`,
  extraPrefsFirefox: {
    'image.avif.enabled': true,
  },
  headless: false,
  product: 'firefox',
})
```

I can't find docs to do change the local exe path.

Also I don't see [anything](https://playwright.dev/docs/api/class-browsertype#browsertypelaunchoptions) for `browserType.launch({channel :'firefox'})`

Thanks for your time!

**Comment by JoelEinbinder** [comment]
We have a fork of firefox to enable more features, so you cannot point Playwright at a version of firefox that you download yourself. This is unlikely to change any time soon, but we are planning to release multiple versions of our fork to match up with firefox beta/stable.

Is there an underlying reason that you want to use dev? Maybe we can address that?

**Comment by tomByrer** [comment]
> underlying reason that you want to use dev

I most often test on FxDev, so it is what I'm used to.  I guess for my immediate purposes FxBeta works; thanks for the suggestion!

But I can see the need to point to a local exe if the tester wants to use a build they made.
(EG I plan to submit bugs to Chrome/Chromium team, & they might want to use their own hand-compiled version.)

That said, I understand my question/request to be 'out of scope'.  Seems you're most focused on fully automated testing on a CI platform, not pseudo-automation like I am doing.  I'm cool with that you might want to close this with 'no action taken'.

**Comment by JoelEinbinder** [comment]
We support using your own browser for Chromium, but unfortunately we can't for Firefox or WebKit.
