### ISSUE TITLE
[BUG] Cannot download a file in `/tmp/` with a Snap browser

### ISSUE THREAD

**Issue by regseb** [microsoft/playwright#6485]
# Context

## System:
 - OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
 - Memory: 8.56 GB / 15.38 GB
 - Container: Yes

```shell
$ df   
Sys. de fichiers blocs de 1K   Utilisé Disponible Uti% Monté sur
udev                 8036728         0    8036728   0% /dev
tmpfs                1613108      2348    1610760   1% /run
/dev/sda2          490691512 132868204  332827828  29% /
tmpfs                8065528     45672    8019856   1% /dev/shm
tmpfs                   5120         4       5116   1% /run/lock
tmpfs                8065528         0    8065528   0% /sys/fs/cgroup
...
/dev/loop3            142336    142336          0 100% /snap/chromium/1564
...
/dev/loop10           142336    142336          0 100% /snap/chromium/1568
...
/dev/sda1             523248      8040     515208   2% /boot/efi
...
tmpfs                1613104        84    1613020   1% /run/user/1000
```

## Binaries:

 - Node: 16.1.0 - /usr/bin/node
 - npm: 7.12.0 - /usr/bin/npm
 - Chromium: 90.0.4430.93 snap - /snap/bin/chromium

## Languages:

 - Bash: 5.0.17 - /bin/bash

## npmPackages:

 - playwright: ^1.10.0 => 1.10.0

# Code Snippet

```javascript
const fs = require("fs/promises");
const { chromium } = require ("playwright");

(async () => {
    const browser = await chromium.launch({
        downloadsPath:  "/tmp/playwright_testcase/",
        executablePath: "/snap/bin/chromium",
    });
    const page = await browser.newPage({ acceptDownloads: true });
    await page.goto("http://test-debit.free.fr/");
    const [download] = await Promise.all([
        page.waitForEvent("download"),
        page.click(`a[href="4096.rnd"]`),
    ]);
    console.log("download...");
    const path = await download.path();
    console.log(`rename ${path}`);
    await fs.rename(path, "/tmp/playwright_testcase/foo.rnd");
    await browser.close();
})();
```

```shell
$ node testcase.js
download...
rename /tmp/playwright_testcase/23325c8d-f9dd-43d7-bb4a-81a70eefba4f
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: ENOENT: no such file or directory, rename '/tmp/playwright_testcase/23325c8d-f9dd-43d7-bb4a-81a70eefba4f' -> '/tmp/playwright_testcase/foo.rnd'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/tmp/playwright_testcase/23325c8d-f9dd-43d7-bb4a-81a70eefba4f',
  dest: '/tmp/playwright_testcase/foo.rnd'
}
```

# Describe the bug

playwright doesn't download file in `/tmp/playwright_testcase/23325c8d-f9dd-43d7-bb4a-81a70eefba4f` (I couldn't find if it was downloading it to another directory). Directory `/tmp/playwright_testcase/` is created, but it's always empty.

It works in my `$HOME` (which is on the same partition as `/tmp/`):

```JavaScript
    const browser = await chromium.launch({
        downloadsPath:  "/home/regseb/playwright_testcase/",
        executablePath: "/snap/bin/chromium",
    });
```

It works with bundled browser:

```JavaScript
    const browser = await chromium.launch({
        downloadsPath:  "/tmp/playwright_testcase/",
    });
```

**Comment by JoelEinbinder** [comment]
I suspect this is because your snap/chromium does not have permissions to access `/tmp/`. I'm not sure how permissions work for snap, but the downloads path has to be somewhere that chromium can access.

**Comment by regseb** [comment]
The problem is related to the Snap version of Chromium ([_Ubuntu Bug #1849437_](https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1849437) / [_Ubuntu Bug #1876236_](https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1876236)).

Here's how I think the code snippet works:

- Playwright creates the `/tmp/playwright_testcase/` directory.
- Playwright launches Chromium Snap.
- Snap creates the directory `/tmp/snap.chromium/tmp/` (where `/tmp/snap.chromium/` is accessible only as `root`).
- Chromium creates the directory `/tmp/snap.chromium/tmp/playwright_testcase/` and downloads the file in this directory.
- Chromium provides the filename to Playwright ([`FrameSession._onDownloadWillBegin()`](https://github.com/microsoft/playwright/blob/8d21b12454632430433d46e0a0a3a4fbc468a884/src/server/chromium/crPage.ts#L821-L834)).
- Playwright concatenates the download directory (retrieved from the [browser options](https://github.com/microsoft/playwright/blob/8d21b12454632430433d46e0a0a3a4fbc468a884/src/server/browser.ts#L81)) and the filename ([`path.join(downloadsPath, uuid)`](https://github.com/microsoft/playwright/blob/8d21b12454632430433d46e0a0a3a4fbc468a884/src/server/download.ts#L30)). But Chromium used another directory.

Playwright would have to retrieve the real download directory used by Chromium. But maybe Chromium does not give it. Or maybe Chromium thinks it's writing to `/tmp/` because Snap is redirecting it to `/tmp/snap.chromium/tmp/`.

If Playwright returned the right path, it would still be complicated to use the downloaded file because it's in a directory accessible only by `root`. But it would be easier to understand the problem.
