### ISSUE TITLE
[Feature] Deny permissions

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright#6488]
Right now we have `grantPermissions`, but what if you want to deny permissions?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by rise-worlds** [comment]
```python
context = await browser.new_context(permissions=[])
```
