### ISSUE TITLE
[Feature] Allow methods with Javascript arguments to accept Path as well as String

### ISSUE THREAD

**Issue by NickTulett** [microsoft/playwright#6497]
Methods such as Page.evalOnSelector and Selectors.register take javascript arguments as strings - which can quickly become nasty.

It would be nice if we could pass in a Path argument to a javascript file, so that the script can be edited in a different tab in the same IDE.

**Comment by NickTulett** [comment]
Path as in filepath

Based on the example from Selectors.register

```   

    String createTagNameEngine = "{\n" +

        "  // Returns the first element matching given selector in the root's subtree.\n" +

        "  query(root, selector) {\n" +

        "    let dar = root.querySelector('[data-alfa-ref=\"' + selector + '\"]');\n" +

        "    if (dar === null) {dar = root.querySelector('[data-alfa-component=\"' + selector + '\"]');}\n" +

        "    return dar;\n" +

        "  },\n" +

        "  // Returns all elements matching given selector in the root's subtree.\n" +

        "  queryAll(root, selector) {\n" +

        "    const dars = Array.from(root.querySelectorAll('[data-alfa-ref=\"' + selector + '\"]'));\n" +

        "    const dacs = Array.from(root.querySelectorAll('[data-alfa-component=\"' + selector + '\"]'));\n" +

        "    return dars.concat(dacs);\n" +

        "  }\n" +

        "}";

    playwright.selectors().register("alfa", createTagNameEngine);
```

Ideally I'd like that javascript to be in a separate js file and just call

`playwright.selectors().register("alfa", alfa-selectors.js)`

**Comment by JoelEinbinder** [comment]
Sounds reasonable to me!

@yury-s

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
