### ISSUE TITLE
[BUG] Playwright hangs or stops running when JS date is mocked eg. with Sinon.useFakeTimers

### ISSUE THREAD

**Issue by elepedus** [microsoft/playwright#6505]
**Context:**
- Playwright Version: 1.10.0
- Operating System: MacOS 11.2.3
- Node.js version: 14.15.4
- Browser: Webkit
- Extra: SinonJS 10.0.0

**Code Snippet**

```typescript
import { webkit } from 'playwright';
import Sinon from 'sinon';

let clock: Sinon.SinonFakeTimers;

async function mockSystemDate(date: string) {
  let systemDate = new Date(date);
  clock = Sinon.useFakeTimers(systemDate);
}

async function run() {
  await mockSystemDate('2019-12-01');
  const browser = await webkit.launch({headless: false});
  const page = await browser.newPage();
  let url = `http://www.example.com`;
  await page.goto(url);
  await browser.close();
  if (clock) {
    clock.restore();
  }
}

run();
```

**Mocking the date breaks playwright**

Using the code above with `DEBUG=pw:browser,pw:api`  doesn't open the page, and produces the following output:
```
  pw:api => browserType.launch started +0ms
```
Commenting out the mocking call correctly opens the page, producing the following output:
```
 pw:api => browserType.launch started +0ms
  pw:browser <launching> /Users/me/Library/Caches/ms-playwright/webkit-1446/pw_run.sh --inspector-pipe --no-startup-window +0ms
  pw:browser <launched> pid=14568 +0ms
  pw:api <= browserType.launch succeeded +2s
  pw:api => browser.newContext started +0ms
  pw:api <= browser.newContext succeeded +316ms
  pw:api => browserContext.newPage started +0ms
  pw:api <= browserContext.newPage succeeded +1s
  pw:api => page.goto started +0ms
  pw:api navigating to "http://www.example.com", waiting until "load" +2ms
  pw:api   navigated to "http://www.example.com/" +401ms
  pw:api   "load" event fired +1ms
  pw:api   "domcontentloaded" event fired +1ms
  pw:api <= page.goto succeeded +1ms
  pw:api => browser.close started +0ms
  pw:browser [pid=14568] <gracefully close start> +4s
  pw:browser [pid=14568] <process did exit: exitCode=0, signal=null> +176ms
  pw:browser [pid=14568] <gracefully close end> +2ms
  pw:api <= browser.close succeeded +180ms
```
Moving the mocking call further down in the method, e.g. just before the `page.goto(url)` call, opens the browser window, but doesn't navigate to the page, and just hangs there until interrupted. Console output is:
```
 pw:api => browserType.launch started +0ms
  pw:browser <launching> /Users/me/Library/Caches/ms-playwright/webkit-1446/pw_run.sh --inspector-pipe --no-startup-window +0ms
  pw:browser <launched> pid=14730 +0ms
  pw:api <= browserType.launch succeeded +241ms
  pw:api => browser.newContext started +0ms
  pw:api <= browser.newContext succeeded +110ms
  pw:api => browserContext.newPage started +0ms
  pw:api <= browserContext.newPage succeeded +480ms
  pw:api => page.goto started +-528d
^C  pw:browser [pid=14730] <gracefully close start> +-528d
  pw:browser [pid=14730] <process did exit: exitCode=0, signal=null> +
```

It appears that Playwright just stops working as soon as we mock the system date with Sinon.

**Comment by JoelEinbinder** [comment]
Playwright uses an out-of-process design, where your test runs in node but your website runs in the browser. In your example you set up Sinon in the node process not in the web process. So it messes with playwright but it won't have any effect on the page itself.

Instead do something like this:
```js
await page.addScriptTag({ url: 'https://sinonjs.org/releases/sinon-9.2.4.js' });
```

**Comment by JoelEinbinder** [comment]
We use 30 second timeouts on most actions to throw in error in case they stall. We also use timers to guarantee that events fire in separate node major tasks.

**Comment by elepedus** [comment]
Aha.. I now understand why messing with the global date breaks things. 

How would I go about running playwright in an (node) vm? 

I see I can just contextify an object (maybe process.env so it can still receive debug  settings etc?) and then run a function in that context. 

However, I'm not clear on what happens from there? Can I just run `webkit.launch()` in the vm context and then use the returned browser as normal, or would every subsequent command also have to explicitly set the context?

**Comment by JoelEinbinder** [comment]
Once the objects are created in the vm all of their functions use the vm's globals instead of the main globals. So it should just work.

Closing this because there's no playwright action to be taken.

**Comment by elepedus** [comment]
I'll give the VM a try -- thanks for your help! :)

**Comment by elepedus** [comment]
Just to update in case others find this thread, I tried using Node's VM to isolate the contexts, but the fake timer still leaked through and caused Playwright to hang.

I've now moved to an out-of-process design, exposing endpoints when NODE_ENV=test to mock the system date etc. and all is working well.
