### ISSUE TITLE
context.pages() is an empty array?

### ISSUE THREAD

**Issue by edi2004** [microsoft/playwright#651]
When using puppeteer, i used to get new tab by using this lines of code:
```
const browser = await puppeteer.launch()
const [page] = await browser.pages()

await page.goto('http://example.com')
```
The main purpose of this is the fewer tabs number, my app is running lighter.
But when i using playwright, it seems that the context isn't contain any page yet.
```
const browser = await playwright.chromium.launch()
const context = await browser.newContext()
const [page] = await context.pages()

await page.goto('http://example.com')
```
My code is running, but i keep getting this error message:
> (node:47248) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'goto' of undefined

Am i the only one who getting this kind of error?

**Comment by edi2004** [comment]
After trying to modify my code to be like this, using defaultContext, it running without get that above kind of error again.
```
const browser = await playwright.chromium.launch()
const context = await browser.defaultContext()
const [page] = await context.pages()

await page.goto('http://example.com')
```

Thank you, and i'm closing this issue.

**Comment by Coriou** [comment]
Hey

I want to achieve the same thing but it seems that `browser.defaultContext()` no longer exists.

I've also noticed something strange:

- When I launch a "regular" browser (ie `chromium.launch()`) it opens an empty page that **is not** listed in `context.pages()` (after I created a new context for that browser)

- When I launch a "persistent" browser (ie `chromium.launchPersistent()`) it opens an empty page that **is** listed in `context.pages()`

So, in order to close that empty window for instance, this kind of code works:

```js
const context = chromium.launchPersistent({})
context.pages().then(pages => pages[0].close()) // pages[0] is the empty, initial page
```

while this one doesn't

```js
const context = chromium.launch({})
const context = browser.newContext({})
context.pages().then(pages => pages[0].close()) // pages is an empty array at this point
```

Any idea what's the current best way to get that initial window, in both persistent and regular modes ?

**Comment by yury-s** [comment]
> I want to achieve the same thing but it seems that `browser.defaultContext()` no longer exists.
>
Correct, the only way to get the "default" context is to use `launchPersistentContext`.

> I've also noticed something strange:
> 
> * When I launch a "regular" browser (ie `chromium.launch()`) it opens an empty page that **is not** listed in `context.pages()` (after I created a new context for that browser)

That was an inadvertent artifact and should not appear in the  more recent versions. When you launch a "regular" browser you should only see contexts/pages that you have created.

> * When I launch a "persistent" browser (ie `chromium.launchPersistent()`) it opens an empty page that **is** listed in `context.pages()`
> 
The persistent context will have one page in it created automatically and you should see it in `context.pages()`. This is inconsistent with the ephemeral contexts but we left it in the persistent context for convenience as many scenarios with persistent context use just that page. 

> So, in order to close that empty window for instance, this kind of code works:
> ...
> Any idea what's the current best way to get that initial window, in both persistent and regular modes ?

You should be able to close all pages in the context by simply closing the context. Does it not work for your scenario for some reason and you want to pick which pages to close?

**Comment by Coriou** [comment]
@yury-s First of all, thank you for the quick and detailed response.

> That was an inadvertent artifact and should not appear in the more recent versions. When you launch a "regular" browser you should only see contexts/pages that you have created.

I can't confirm right now, but I'll make sure I'm using the latest version of Playwright and see if this is still happening. As of a couple of days ago, I was using the latest version (back then) and I still had this issue.

> The persistent context will have one page in it created automatically and you should see it in context.pages(). This is inconsistent with the ephemeral contexts but we left it in the persistent context for convenience as many scenarios with persistent context use just that page.

Thanks for the info, kinda makes sense too.

> You should be able to close all pages in the context by simply closing the context. Does it not work for your scenario for some reason and you want to pick which pages to close?

In the case of a "regular" (non persistent) browser, I just wish to close the empty page which - as I understand it - is bound to the (now unreachable) default context. 

But, if I understand correctly, you perfectly answer my question / issue: I want to be able to close the initial empty page in both "regular" and "persistent" environments. I can already close that page in with the "persistent" browser but couldn't close it when using a "regular" one. But, this shouldn't be an issue with latest Playwright versions.

I'll test when possible and will report, but I believe it's all good =)
