### ISSUE TITLE
Giving permissions to any origin within browser context

### ISSUE THREAD

**Issue by nicoandmee** [microsoft/playwright#652]
Is wildcard functionality currently supported in setting permissions for browser contexts? As in: [3225](https://github.com/puppeteer/puppeteer/issues/3225)

**Comment by aslushnikov** [comment]
Ah, not yet! But I'd love to see this.

**Comment by nicoandmee** [comment]
@aslushnikov  Can you advise if this would require a change to chromium or something that could fit into the existing CDT protocol? I'd love to try and tackle it.

**Comment by aslushnikov** [comment]
@nicoandmee nah, I'm afraid it requires changes in all 3 browsers =/

**Comment by dgozman** [comment]
Fixed by #1406.
