### ISSUE TITLE
elementHandle.evaluate missing from documentation

### ISSUE THREAD

**Issue by lukeapage** [microsoft/playwright#653]
I spent a while trying to work out how to evaluate on an element I already have because $eval and $$eval are documented but not evaluate.

I found it by looking at the source and it seems to work: https://github.com/microsoft/playwright/blob/5c5faf35a961865c75202a4032d470c5c1eb6503/src/dom.ts#L463

should it be documented?

**Comment by pavelfeldman** [comment]
Thanks for the report. `ElementHandle` extends `JSHandle` and we should make it clear in the docs.

**Comment by lukeapage** [comment]
Ah yes. It does say inherits in the docs, it just didn’t occur to look.
Feel free to close..

**Comment by pavelfeldman** [comment]
@aslushnikov ^^ How do you feel about including the links to the inherited methods into our class ToCs for clarity?
