### ISSUE TITLE
[Question] Blank screenshots on test failure

### ISSUE THREAD

**Issue by ALegchilov** [microsoft/playwright#6532]
**Context:**
- "playwright": "^1.10.0"
- "jest": "^26.6.3"
- "jest-playwright-preset": "^1.5.2"
- Windows 10
- Node.js version: v16.1.0
- Browser: All available: Chromium, Firefox, WebKit

**Code Snippet**

```javascript
const PlaywrightEnvironment = require('jest-playwright-preset/lib/PlaywrightEnvironment').default;

class TestEnvironment extends PlaywrightEnvironment {
  async handleTestEvent(event) {
    if (event.name === 'test_done' && event.test.errors.length > 0) {
      const parentName = event.test.parent.name.replace(/\W/g, '-');
      const specName = event.test.name.replace(/\W/g, '-');
      await this.global.page.screenshot({
        path: `screenshots/${parentName}_${specName}.png`
      });
    }
  }
}
```

**Problem description**

Even though I use recommended capturing screenshots on failure implementation, I see only blank images (completely white color) instead of real page content on saved files. Moreover, screenshots size is 1280x720 in spite I run test scripts in 1920x1080 view port.
If I trigger page.screenshot() within a test, it works fine.

**Comment by JoelEinbinder** [comment]
Can you share one of your tests? I expect that you are not using the global page in the test.

**Comment by ALegchilov** [comment]
> Can you share one of your tests? I expect that you are not using the global page in the test.
Correct. I work with customized page instance and looking for a way to capture screenshot on failure.

**Comment by mariiasolodiankina-valagroup** [comment]
I'm having exactly the same issue with the same setup. What was the solution?

**Comment by mariiasolodiankina-valagroup** [comment]
I'm having exactly the same issue with the same setup. What was the solution?
