### ISSUE TITLE
[Feature] Omit background in video

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright#6537]
From https://github.com/microsoft/playwright/discussions/6050

The user wants to record video without the background. @yury-s is that possible?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
