### ISSUE TITLE
[Question] Explicitly launching firefox results in this error: Failed to launch chromium because executable doesn't exist

### ISSUE THREAD

**Issue by ebzimny01** [microsoft/playwright#6538]
**Context:**
- Playwright Version: 1.11
- Operating System: Windows 10
- Python: v3.9
- Browser: Firefox
- Extra: Python venv based on 3.9 and using the hermetic install powershell env variable $ENV:PLAYWRIGHT_BROWSERS_PATH=0

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```
playwright install firefox
Downloading firefox v1250 - 75.9 Mb [====================] 100% 0.0s
firefox v1250 downloaded to c:\Users\myuser\code\virtualenvs\gdrecruit39\Lib\site-packages\playwright\driver\package\.local-browsers\firefox-1250

playwright codegen -b firefox

Failed to launch chromium because executable doesn't exist at c:\Users\myuser\code\virtualenvs\gdrecruit39\Lib\site-packages\playwright\driver\package\.local-browsers\chromium-8Try re-installing playwright with "npm install playwright"
Error
    at Object.captureStackTrace (c:\Users\myuser\code\virtualenvs\gdrecruit39\Lib\site-packages\playwright\driver\package\lib\utils\stackTrace.js:50:19)
    at Connection.sendMessageToServer (c:\Users\myuser\code\virtualenvs\gdrecruit39\Lib\site-packages\playwright\driver\package\lib\client\connection.js:65:48)
    at Proxy.<anonymous> (c:\Users\myuser\code\virtualenvs\gdrecruit39\Lib\site-packages\playwright\driver\package\lib\client\channelOwner.js:64:61)
    at BrowserContext._enableRecorder (c:\Users\myuser\code\virtualenvs\gdrecruit39\Lib\site-packages\playwright\driver\package\lib\client\browserContext.js:280:29)
    at codegen (c:\Users\myuser\code\virtualenvs\gdrecruit39\Lib\site-packages\playwright\driver\package\lib\cli\cli.js:318:19)

```

**Describe the bug**

A previous venv had been working with Playwright fine and then stopped working - could not launch the hermetic installed firefox browser.

I created a new venv to troubleshoot and am running in to same problem.

If I install only the firefox browser, I get the error above when attempting `playwright codegen -b firefox`.
However, if I hermetic install **both** chromium and firefox, then running `playwright codegen -b firefox` succeeds --> I don't get any error and it does indeed open the firefox browser, not the chromium browser.

This used to work fine with just firefox installed, so I don't understand what's changed or what's going wrong on my end.

**Comment by JoelEinbinder** [comment]
We use chromium to run the inspector, so unfortunately it does not work without chromium installed.

**Comment by ebzimny01** [comment]
Interesting, not sure how it was working before. Can the chromium browser be installed using the default location and then I can install firefox separately using the hermetic install location?

**Comment by ebzimny01** [comment]
And is that a documented system requirement that I missed somewhere?

**Comment by JoelEinbinder** [comment]
Currently codegen expects there to be a chromium browser next to the firefox browser you point it at.

**Comment by mxschmitt** [comment]
Closing for now, since codegen is based on Chromium and only works with Chromium. If it's not possible for you to use Chromium, please reopen with more details.

**Comment by ortoniKC** [comment]
Hi, I am not using the code gen, just trying to launch the firefox local browser and facing the same issue.

Note: File path is correct
```
browserType.launch: Failed to launch firefox because executable doesn't exist at ‪C:/Program Files/Mozilla Firefox/firefox.exe
```


Sample code:
``` 
let browser: Browser;
    let context: BrowserContext;
    let page: Page;
    beforeAll(async () => {
        browser = await firefox.launch({
            executablePath: "‪C:/Program Files/Mozilla Firefox/firefox.exe",

             // with chromium.launch this works
            // executablePath: "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe",

            headless: false
        });
        context = await browser.newContext()
        page = await context.newPage();
    })

  test("launch browser", async () => {
        await page.goto("https://letcode.in/edit")
    })

```

**Comment by AlanJereb** [comment]
From what I have observed, Playwright fails to install through NPM and just hangs.

Node version: 15.14.0
