### ISSUE TITLE
[Feature] Listen for print dialog

### ISSUE THREAD

**Issue by aaliakseyenka** [microsoft/playwright#6543]
Hi, I would like to test printing of the page, particularly that print dialog is opened on user action. Although seems existing api in typescript doesn't allow that. `page.on('dialog')` seems doesn't work with `print()` call. Am I missing anything?

**Comment by JoelEinbinder** [comment]
No you are not missing anything. Sorry we don't current support listening for the print dialog.

**Comment by aaliakseyenka** [comment]
thanks for prompt answer. Wondering are there any plans to add this in near future?

**Comment by mxschmitt** [comment]
It's marked as collecting feedback. When there are enough upvotes and interest, it gets considered for implementation.

**Comment by qwpnqjucz** [comment]
also interested in this.

**Comment by leochung042** [comment]
Hi All

For all whose use case like me, then you could check on https://github.com/microsoft/playwright-python/issues/739 .

For my use case is after click on print button, then the Browser Print preview shows up, then I would like to save Print preview as PDF file.

Thank you,
Leo

**Comment by nbnds** [comment]
Some corporate web applications  have printing feature at its core, like bookkeeping software, where you need to print invoices, reports etc. 
It would be very useful if we could test that we can invoke printing function by clicking the designated button.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by Digraj22** [comment]
Any workaround for this, this is a show stopper for me. Also I do not want to execute the script in headless mode. #16100 is also closed.

Is there any plan to provide the support in future?

**Comment by uchagani** [comment]
Here is how I handle it:  Since all we need to do is ensure that the print was actually called when the print button is clicked we do: 

(in Java but easy to translate to other languages):

```java
page.onLoad(pa -> pa.evaluate("window.print = function() { console.log('Print was triggered'); };"));
```

then you can use [waitForConsoleMessage](https://playwright.dev/java/docs/api/class-browsercontext#browser-context-wait-for-console-message) to verify that `Print was triggered` was called.

**Comment by pradeipp** [comment]
I'm surprised that this simple yet frequently used feature is not supported in Playwright. It's a total blocker for me since we have a print functionality in our gift card page that's used often by our customers and the print function has failed in the past and we need to put a test for it.  
@pavelfeldman how many upvotes are needed for this feature to be considered worthy to be implemented?

**Comment by snehankekre** [comment]
+1 to re-opening this issue.

**Comment by AlexRhadoo** [comment]
+1 to re-opening this issue.

**Comment by ikonovalov070285** [comment]
Hi, I have the same case: I need to verify the prints button and data in the print preview window before printing.

**Comment by tverdokhlebd** [comment]
+1 to re-open the issue.

**Comment by easyas123l11** [comment]
Hello, this is a important feature for a project I'm working on. I hope this feature gains some traction soon!

**Comment by marnandr** [comment]
Hi,

I want to share with you the closest workaround that I found. Used a selector which points to the print event triggering button and add an additional event listener to the click event. The event listener writes a message to the console, and I checked it with an expect. If you reload the page, it will close the print dialog.

```typescript
const printButton = page.frameLocator('iframe').getByRole('button', { name: 'Print' });
await printButton.evaluate(node => node.addEventListener('click', function printEventLogger(){ console.log('Print button clicked!'); }));
const msgPromise = page.waitForEvent('console');
await printButton.click();
const msg = await msgPromise;
expect(msg.text()).toBe('Print button clicked!');
await page.reload();
```

**Comment by mxschmitt** [comment]
We added it to our docs [here](https://playwright.dev/docs/dialogs#print-dialogs), please create a new issue if it doesn’t work for you or you have feedback for it. Thanks!
