### ISSUE TITLE
Sign in dialog isn't dismissed

### ISSUE THREAD

**Issue by KotlinIsland** [microsoft/playwright#6553]
**Context:**
- Playwright Version: 1.11.0
- Operating System: Windows
- Node.js version: python 3.10
- Browser: Chromium

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```py
page.goto(url)
```

**Describe the bug**
But guess what! it wasn't dismissed and I can't find any info about this scenario.
![image](https://user-images.githubusercontent.com/65446343/118087498-ff3f2b00-b408-11eb-86c8-5f333449e44f.png)

**Comment by mxschmitt** [comment]
You can set the credentials (username and password) when creating a new context. That should fix it. https://playwright.dev/docs/network#http-authentication

**Comment by KotlinIsland** [comment]
I don't want to enter credentials, I want to dismiss it.

**Comment by mxschmitt** [comment]
This is currently not possible, what is the use-case for it?

**Comment by KotlinIsland** [comment]
This system I was testing shows a dialog for some reason and you just be like "dismiss" and it acts as normal.

There was a url parameter that disabled it so i'm not blocked or anything.
