### ISSUE TITLE
[BUG] console events are not triggered for console.log from service workers

### ISSUE THREAD

**Issue by hugomrdias** [microsoft/playwright#6559]
**Context:**
- Playwright Version: 1.11.0
- Operating System: all
- Node.js version: all
- Browser: all
- Extra: [any specific details about your environment]

## System:
 - OS: macOS 11.3.1
 - Memory: 665.71 MB / 16.00 GB
## Binaries:
 - Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
 - Yarn: 1.22.10 - /usr/local/bin/yarn
 - npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
## Languages:
 - Bash: 5.1.8 - /usr/local/bin/bash
## npmPackages:
 - playwright-core: 1.11.0 => 1.11.0
**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
// sw.js

self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url)
  console.log('hello world')
})

// main.js
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch(); 
  const context = await browser.newContext()
  const page = await context.newPage()
  await page.goto('http://localhost:3000')
  await page.evaluate(() => navigator.serviceWorker.register('/sw.js'))
  page.on('console', ()=>{
    console.log('never runs')
  })
  await page.evaluate(()=>{
   fetch('http://localhost:3000/hello')
  })
})();
```

**Describe the bug**

Add any other details about the problem here.

**Comment by JoelEinbinder** [comment]
Reasonable!

**Comment by kettanaito** [comment]
I confirm that this is still an issue in `playwright@1.12.2`. I understand that the worker runs in a separate thread and that's a likely reason why its console messages are not bubbling to the "console" event of the page. 

That, however, creates a wrong expectation, as for the library's user I expect the "console" event to be called whenever _any_ console message happens, regardless of its origin. I don't have any insights as to how the "console" event is implemented, but I'd be happy to suggest a solution if there's any feedback from the maintainers.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
