### ISSUE TITLE
[BUG] Downloads are canceled on Chromium when requests are intercepted

### ISSUE THREAD

**Issue by Kalliser** [microsoft/playwright#6573]
**Context:**
- Playwright Version: 1.8.1 and 1.11.0
- Operating System: Linux
- Node.js version: 14.15
- Browser: Chromium only, works fine on firefox and webkit
- Extra: -

**Code Snippet**

Downloads are canceled if using interception of requests

Sample of code : 
```javascript
const util = require('util');
const { chromium, firefox, webkit, devices } = require('playwright');
const options = {
    devtools: false,
    dumpio: true,
    ignoreHTTPSErrors: true,
    args: [
        '--disable-web-security',
        '--allow-running-insecure-content',
        '--disable-dev-shm-usage',
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-gpu',
        '',
        '--lang=fr',

    ],
};

chromium.launch(options).then(async (browser) => {
    const context = await browser.newContext({
        acceptDownloads: true
    })
    await context.route(/.*/, (route) => {
         route.continue();
    });

    const page = await context.newPage();
    page.on('download', async (download) => {
        console.log(util.inspect(download.suggestedFilename()));
        const failureMsg = await download.failure();
        const path = await download.path();

        console.log(util.inspect({
            failureMsg: failureMsg,
            path: path
        }));
    });
    await page.goto('https://www.trionsnosdechets-dijon.fr/fr/Particulier/Reduire-mes-dechets/Jardinage-et-compostage');
    const element = await page.$('[download="Guide du jardinage au naturel et du compostage.pdf"]:visible');
    await element.click();
});
```

**Describe the bug**

Using the interception of requests makes download are always canceled, even if using route.continue() as showed in my example.

Disabled it will make download works as expected : 
```
 // await context.route(/.*/, (route) => {
 //        route.continue();
 //   });
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
