### ISSUE TITLE
[Question] Request / Response TTFB may become large.

### ISSUE THREAD

**Issue by YokoyamaKazuki** [microsoft/playwright#6574]
I am using Playwright to measure performance, but the TTFB of Request / Response may be large depending on the website to be measured.
This does not occur with a normal web browser that does not use Playwright.
Do you know the cause and solution of this phenomenon?

chrome（TTFB 895ms）：
<img width="1276" alt="スクリーンショット 0003-05-14 18 15 14" src="https://user-images.githubusercontent.com/59683678/118249628-91fec900-b4e0-11eb-84d6-ae9217e6dbd8.png">

Playwright Chroimum（TTFB 10.6s）：
<img width="1280" alt="スクリーンショット 0003-05-14 18 13 12" src="https://user-images.githubusercontent.com/59683678/118249829-c5415800-b4e0-11eb-829e-ef878bc042b4.png">

**Comment by JoelEinbinder** [comment]
I could reproduce this a few days ago, but it stopped happening for me. Not sure what is going on, but I am guessing it was something the site was doing to detect automation. I don't think there's anything we can do about it.
