### ISSUE TITLE
[Question] Element is NOT visible

### ISSUE THREAD

**Issue by marklane2001** [microsoft/playwright#6584]
Hi

Currently I am asserting that some button elements are visible to the user using :
```python
result = self.manage_candidiates_button.is_not_visible()
```
I also need to check that various elements are NOT visible for this role type. I thought it would be as simple as stating button_is_not_visible but this doesn't seem to be the case. Can anyone help?

**Comment by JoelEinbinder** [comment]
If you have an element handle to the element you can of course do:
```py
result = not self.manage_candidiates_button.is_visible()
```

But I suspect that your element is actually not in the dom. So instead use `is_visible()` from the page with a selector that would resolve to the element you are checking.

```py
result = not page.is_visible(".my-selector")
```

**Comment by aslushnikov** [comment]
(closing since discussion has stalled)
