### ISSUE TITLE
What is equivalent of getCssValue (protrator) 

### ISSUE THREAD

**Issue by wupaz** [microsoft/playwright#6595]
Hi,

I didn't find how get value of a css attribute with Playwright like I does with Protractor.
ex.:
 expect(saveButton.getCssValue("background-color")).toBe(saveBtnValidColor

Eric

**Comment by JoelEinbinder** [comment]
You can evaluate javascript to get it

```js
const button = await page.$('.my-button');
const color = await button.evaluate(button => window.getComputedStyle(button)['background-color']);
expect(color).toBe('blue');
```
