### ISSUE TITLE
Add real-world examples

### ISSUE THREAD

**Issue by guzzur** [microsoft/playwright#660]
I would be great to have a few real-world examples, e.g.:
- go to page
- wait for it to load
- select a specific `input[name=username]`
- type a username into it
- select a specific `input[name=password]`
- type a password into it
- take a screenshot
- select `button[name=submit]` (or submit)
- wait for next page to load

The boilerpate for a newbie may be devastating.

E.g. the first very simple test I wrote took me a while to get to work:

```
await page.goto(address);
await page.screenshot({ path: screenshotPath }); // <- shots a loading page... but I asked to await

let elementHandle = await page.$('input[name="username"]'); // <- doesn't happen as we got here too soon
await elementHandle.type(email); // <- crashes as elementHandle is null

elementHandle = await page.$('input[name="password"]');
await elementHandle.type(password);
```

I think a simple example describing a login or data-entry and the entered-data-evaluation flows may help.

Thank you for this amazing tool!

**Comment by Segevz** [comment]
I wrote a simple script for you demonstrating this task:
```
const { chromium } = require('playwright');

(async () => {
    const browser = await chromium.launch();
    const context = await browser.newContext();
    const page = await context.newPage("http://localhost/");
    await page.screenshot({path: 'pre_login.png'});
    
    await page.type('input[name="username"]', 'some@account');
    await page.type('input[name="password"]', 'somepassword');
    await page.keyboard.press('Enter');
    await page.screenshot({path: 'post_login.png'});

    await browser.close();
})();
```
Hope it helps :)

**Comment by arjun27** [comment]
This is now underway with the [getting started guide](https://github.com/microsoft/playwright/blob/master/docs/examples/README.md). Will be adding more examples over time. Thanks for the suggestion @guzzur.
