### ISSUE TITLE
[Question] Way for capturing screenshot with `:visited` style?

### ISSUE THREAD

**Issue by progfay** [microsoft/playwright#6615]
## Description

Serve HTML on `http://localhost:3000/index.html`:

```html
<style>
  a:visited { color: red }
</style>

<a id="visited" href="/visited.html">Visited</a>
<a id="not-visited" href="/not-visited.html">Not Visited</a>
```

And run:

```js
await page.goto("http://localhost:3000/index.html");
await page.click(`a#visited`);
await page.goBack();

await page.screenshot({ path: "./screenshot.png" });
```

Then, screenshot.png:

![screenshot](https://user-images.githubusercontent.com/19568747/118508941-96d6ad80-b76a-11eb-89b5-4fc152b89968.png)

Expected (captured by hand operation):

![image](https://user-images.githubusercontent.com/19568747/118509394-f339cd00-b76a-11eb-9e72-9fb4cfe8a76c.png)

## Why `:visited` styles are ignored?

For privacy reason.
To prevent history leaking, `window.getComputedStyle` return a lie property.

Ref:
- https://developer.mozilla.org/en-US/docs/Web/CSS/Privacy_and_the_:visited_selector
- https://dbaron.org/mozilla/visited-privacy
- https://github.com/progfay/visited-pseudo-history-leaking/blob/main/overview.md

## Question

Is there any way to capturing screenshot with `:visited` style?

**Comment by JoelEinbinder** [comment]
We shouldn't be affected by the privacy concerns around `:visited`. I'll take a look.

**Comment by JoelEinbinder** [comment]
So the issue here is that in our default mode of operation we launch incognito browser contexts, which do not track the `:visited` state at all. It should work if you use [chromium.launchPersistentContext](https://playwright.dev/docs/api/class-browsertype/#browsertypelaunchpersistentcontextuserdatadir-options).

**Comment by progfay** [comment]
I tried to capture screenshot with `BrowserType.launchPersistentContext`.
Only firefox was styled, others weren't.

Repository: https://github.com/progfay/visited-pseudo-history-leaking
Screenshots: https://github.com/progfay/visited-pseudo-history-leaking/tree/db28e6ad9167afdda43e37b3ed876d8c3074a690/screenshots

**Comment by progfay** [comment]
@JoelEinbinder 
Do you know anything for reason why Why styles are not applied except in firefox browser?

**Comment by pavelfeldman** [comment]
I think we are missing this feature, so it can be considered a Playwright bug. Let me start collecting upvotes for it.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
