### ISSUE TITLE
[Feature] HAR: IP Address and SSL Info

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#6624]
It would be helpful to have the remote IP address for connections as well as SSL details in the Playwright generated HAR.

Currently, we run a separate proxy to get this info for our tests.

I'd like to drop the proxy and only use Playwright's HAR. 

In regional e2e smoketests I want to assert the browser is picking certain CDN server blocks.

Additionally, I'd like to monitor connections made be embedded SDKs and ensure they only reach out to certain IP blocks (based on geoip) to ensure they are maintaining contract commitments.

Let me know priority, and I'd be happy to contribute the chrome portion of the work if someone else could assist with WK and FF. (Maybe I could do those two but I'm much less familiar.)

**Comment by mxschmitt** [comment]
Seems related to https://github.com/microsoft/playwright/issues/2474 to me.
