### ISSUE TITLE
[BUG] Webkit Can't find variable RTCRtpSender

### ISSUE THREAD

**Issue by zyscoder** [microsoft/playwright#6625]
**Context:**
- Playwright Version: v1.11.0
- Operating System: Linux
- Node.js version: 14.15.1
- Browser: Webkit

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const { webkit } = require('playwright');

(async () => {
    const browser = await webkit.launch();
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto('http://www.w3.org');
    const code = "RTCRtpSender.prototype";
    try {
        await page.evaluate(code);
    } catch(e) {
        console.error(e.toString());
    }
})();

```

**Describe the bug**
An Exception is thrown:
```
Error: page.evaluate: Evaluation failed: ReferenceError: Can't find variable: RTCRtpSender
```
However, as [the MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender) said, Webkit supports the API RTCPtpSender.
I set up the Webkit MiniBrowser manually and evaluate the same code `RTCRtpSender.prototype` in the Console of Devtools, and there is no error that occurs. 
![Screenshot from 2021-05-18 12-16-09](https://user-images.githubusercontent.com/23655282/118589377-dafd9880-b7d2-11eb-9de8-ad1ed8fab816.png)
Why cannot access RTCRtpSender with `page.evaluate`?

**Comment by mxschmitt** [comment]
Folding into #6638
