### ISSUE TITLE
[Feature] Request to show the cursor on a video recording

### ISSUE THREAD

**Issue by mishalalex** [microsoft/playwright#6629]
Hi, it would be amazing if the playwright screen capture captures cursor as well. This feature would help in communication and bug reporting.

**Comment by letsgotomars** [comment]
Agree this would be value added if this is technically possible

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by pavelfeldman** [comment]
Please consider using Trace Viewer instead.
