### ISSUE TITLE
[Question] Is there a way to add extension to the Firefox browser?

### ISSUE THREAD

**Issue by Pooort** [microsoft/playwright#6636]

**Comment by avodovnik** [comment]
If you only want to add the extension, have a look at this comment: https://github.com/microsoft/playwright/issues/2644#issuecomment-647842059

cc: @aslushnikov might also have more information

**Comment by mxschmitt** [comment]
Closing, see also here: https://github.com/microsoft/playwright/issues/2874#issuecomment-717520563
