### ISSUE TITLE
[BUG] Pressing Enter key is not working

### ISSUE THREAD

**Issue by snehalk20** [microsoft/playwright#6637]
**Context:**
- Playwright Version: [1.11.0]
- Operating System: [Windows]
- Node.js version: [14.6]
- Browser: [e.g. All, Chromium, Firefox, WebKit]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

``` const { chromium } = require('playwright'); 
    const { HomePage } = require('../pageObjects/homePage');
    var chai = require('chai');
    var expect = chai.expect;
    var assert = chai.assert;

    const searchItem = "context";
    const searchText = "browserContext.addInitScript(script[, arg])";

    (async() => {
        
        const browser = await chromium.launch({headless: false});
        const browserContext = await browser.newContext();
        const page = await browserContext.newPage();
    
        await page.goto("https://playwright.dev/",{waitUntil: 'networkidle'});
        **await page.fill(".navbar__search-input", "context");
        await page.keyboard.press('Enter');**
        await page.click('a[href="/docs/api/class-browsercontext#browsercontextaddinitscriptscript-arg"]');
        const handle = await page.$$(`text=${searchText}`);
        expect(handle).to.have.lengthOf.above(0);
        
        browser.close();

    })();
```

**Describe the bug**
Press enter key doesn't seem to work. After filling the input text Nothing is happening on the page.
await page.keyboard.press('Enter');

**Comment by avodovnik** [comment]
This looks like a "problem" with the JavaScript code on our site. 

`Enter` won't actually do the search, but open the first item on the menu. If you do the following, it works.

```js
        await page.fill(".navbar__search-input", "context");
        **await page.waitForSelector(".dropdownMenu_X-NJ", { state: 'visible' });**
        await page.keyboard.press('Enter');
```

**Comment by snehalk20** [comment]
@avodovnik Thanks for the inputs. But shouldn't the keyboard press API wait automatically for the dropdown to be visible ? Please correct me if my understanding on auto waits is not right.

**Comment by avodovnik** [comment]
Well, not really. This specific implementation is on the `playwright.dev` site. If you try using [https://keycode.info](https://keycode.info), for example, you'll see the `Enter` gets pressed. But the JavaScript code on _our_ website, is an implementation detail, and the test should reflect that. You as the developer need to know what's going to happen/what you expect to happen.
