### ISSUE TITLE
[Question] Using Web Authentication API in Webkit

### ISSUE THREAD

**Issue by zyscoder** [microsoft/playwright#6638]
**Context:**
- Playwright Version: v1.11.0
- Operating System: Linux
- Node.js version: 14.15.1
- Browser: Webkit

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const { webkit } = require('playwright');

(async () => {
    const browser = await webkit.launch();
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto('http://www.w3.org');
    const code = "AuthenticatorAssertionResponse.prototype";
    try {
        await page.evaluate(code);
    } catch(e) {
        console.error(e.toString());
    }
})();

```

**Describe the bug**
An Exception is thrown:
```
page.evaluate: Evaluation failed: ReferenceError: Can't find variable: AuthenticatorAssertionResponse
```
As [the MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorAssertionResponse) said, Safari supports the API from v13. However, I cannot access this API in Webkit v14.2. Is that reasonable?

**Comment by JoelEinbinder** [comment]
WebAuthentication is only implemented in WebKit for MacOS/iOS. It would be a lot of work to add it for linux and windows. What do you need it for?

**Comment by mxschmitt** [comment]
Closing for now since it seemed stale, feel free to reopen with a use-case in the automation area, then we can label it as a feature request.
