### ISSUE TITLE
[Question] How to Loop through elements to get attribute of each element

### ISSUE THREAD

**Issue by raghavakora** [microsoft/playwright#6642]

**Comment by mxschmitt** [comment]
You could do something like this:

```js
// @ts-check
const playwright = require('playwright');

(async () => {
    const browser = await playwright.chromium.launch();
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.setContent(`
      <div>foo</div>
      <div>bar</div>
      <div>foobar</div>
    `)

    const attributes = await page.$$eval("div", elements => elements.map(element => element.innerText))
    console.log(attributes)

    await browser.close();
})();
```

**Comment by raghavakora** [comment]
Thank you @mxschmitt for your quick response.
In the above code we get the complete list as a single string which will get concatenated and assigned to attributes

I am looking to have a condition after grabbing a text which is returned in getAttribute for each element 
Ex: 
const value = element.getAttribute('xxxxx')
expectt(value).toBe............

**Comment by mxschmitt** [comment]
You can also get an attribute for a single element, see here: https://playwright.dev/docs/assertions#attribute-value

or if you already have an element handle: https://playwright.dev/docs/api/class-elementhandle#elementhandlegetattributename

**Comment by raghavakora** [comment]
@mxschmitt it looks like you got me wrong, let me reiterate what i am requesting 
I am fine to get the attribute for an element either at parent/child level 

All I am trying to get the the attribute of a child element and I would like to have a condition at this level 
`
const elements  = page.$$(locator)
elements.foreach((element)=>{
const attributeValue = element.getAttribute(attributeName)
expect(attributeValue).tobe(expectedText)
`

here is what I am trying to achieve the above logic using playwright 
Thank you for your responses earlier and I hope it is clear now

**Comment by mxschmitt** [comment]
Would something like that work for you?

```js
    const attributes = []
    for (const element of await page.$$("div")) {
      if (await element.innerText() !== "bar")
        attributes.push(await element.getAttribute("foo"))
    }
    console.log(attributes)
```

**Comment by raghavakora** [comment]
similar way but when i have tried the above approach I am getting an issue where it is complaining **element** as undefined and also due to no-shadow variable as well 
highlighted in Bold
```
for (const **element** of await page.$$("div")) {
      if (await element.innerText() !== "bar")
        attributes.push(await element.getAttribute("foo"))
    }
```

**Comment by raghavakora** [comment]
I managed to resolve the issue with the proposed solution 
thank you @mxschmitt
