### ISSUE TITLE
[Feature] Up2date device-descriptor user-agents for Firefox and WebKit

### ISSUE THREAD

**Issue by lioulbehailu** [microsoft/playwright#6679]

**Comment by mxschmitt** [comment]
We have now updated user agents, which reflect the current Chromium version (https://github.com/microsoft/playwright/pull/6594). You can test it with the development-release `npm install playwright@next`

**Comment by lioulbehailu** [comment]
> We have now updated user agents, which reflect the current Chromium version (#6594). You can test it with the development-release `npm install playwright@next`

what about for firefox and webkit???

**Comment by mxschmitt** [comment]
They are still outdated in terms of from the day when we obtained them. Normally you should not run into issues there but we can update them as well.

**Comment by lioulbehailu** [comment]
does those devices work in `playwright@1.8.0`
