### ISSUE TITLE
request.continue() override with post data

### ISSUE THREAD

**Issue by Sue9445** [microsoft/playwright#668]
Hi,

How to override post data with request.continue() on request interception ?

**Comment by yury-s** [comment]
Only headers overrides are supported at the moment for the requests. Could you share more details about your use case to help us evaluate how to shape this API?

**Comment by aslushnikov** [comment]
The common usecase for this is a POST-navigation; see https://github.com/puppeteer/puppeteer/issues/1062

This is something coming from the phantomjs days.
