### ISSUE TITLE
[BUG] Concurrency issues - Playwright tests time out randomly when running in parallel or all run fine

### ISSUE THREAD

**Issue by cullman1** [microsoft/playwright#6680]
**Context:**
- Playwright Version: 1.11.0-1621402998000 (but happened in all versions of 1.10 and 1.11 we have tried)
- Operating System: Windows 10 Pro 20H2 Build - 19042.985
- Node.js version: v12.3.0
- Browser: Chromium 90.0.4430.212 (64-bit) and/or Firefox 82.03 (64 bit)
- Extra: 
- jest: 26.6.3
- yarn: 1.16.0
- Docker: 20.10.6

**Code Snippet**

Typical test:

```javascript
it(
    "Resend-Welcome-Email-manage-staff",
    async () => {
      const page = getPage();
      await page.goto(`${BASE_URL}/schools/${SCHOOL_ID}/staff`);
      await page.click("button[data-testid=resend]");
      await page.waitForURL(`${BASE_URL}/schools/${SCHOOL_ID}/staff`, {
        waitUntil: "networkidle"
      });
      await page.focus("span[data-testid=sent]");
      const innerText = await page.$$("span[data-testid=sent]");
      assert.notStrictEqual(innerText, []);
    },
    TEST_TIMEOUT
  );
```
Here's the code that handles beforeAll/afterAll:

``` javascript
const defaultBrowser = chromium;

export function adminTest(
  scenario: string,
  blocks: (getPage: () => Page, browserName: string) => void
) {
  describe(scenario, () => {
    let browser: Browser;
    let page: Page;
 
    beforeAll(async () => {
      jest.setTimeout(ASYNC_CALLBACK_TIMEOUT);
      removeUsers([
        `${EMAIL1}`,
        `${EMAIL2}`,
        `${EMAIL3}`
      ]);
      browser = await defaultBrowser.launch({
          chromiumSandbox: true
      });     
      let needSysAdmin = TESTS_THAT_REQUIRE_SYSADMIN.includes(scenario);
      page = await getLoggedInContext(browser, needSysAdmin);
      page.setDefaultNavigationTimeout(0);
      page.setDefaultTimeout(0);
    }, 75000);

 blocks(() => page, defaultBrowser.name());

    afterAll(async () => {
      await browser.close();
    });
  });
}
```

**Describe the bug**

We have built 77 test suites with 116 tests (max 5 or 6 in each suite). The whole environment is run in Docker, using webpack and IISExpress. We use jest as a test runner. If we run test suites individually or sequentially in band, they never fail. If we run them in parallel then sometimes all tests works, sometimes one or two tests will randomly timeout or stop responding. The system has to log in first, it does this once via a cookie in a json file, and then remains logged in for all tests. A typical error for the sample code above looks like this. If we place console.log statements, it will inevitably the page.goto or (now) the waitForUrl that it hangs on. 

```error 
Manage Staff Edit › Resend-Welcome-Email-manage-staff

    : Timeout - Async callback was not invoked within the 55000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 55000 ms timeout specified by jest.setTimeout.Error:

      68 |   );
      69 |
    > 70 |   it(
         |   ^
      71 |     "Resend-Welcome-Email-manage-staff",
      72 |     async () => {
      73 |       const page = getPage();

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at tests/admin/manage-staff-edit/manageStaffEdit.test.ts:70:3
      at Suite.<anonymous> (shared/adminTestHelpers.ts:57:5)
```

However in another similar test, it times out waiting for a button that is clearly visible on the screen when running headless:false: 

```Manage Staff Edit › Edit-a-staff-member-manage-staff

    TimeoutError: page.waitForSelector: Timeout 6000ms exceeded.
    =========================== logs ===========================
    waiting for selector "button[data-testid=add-staff]" to be visible
```
(the portion of the code for the test can be seen below)

```
  it(
    "Edit-a-staff-member-manage2-staff",
    async () => {
      const page = getPage();
      await page.goto(`${BASE_URL}/schools/${SCHOOL_ID}/staff`);
      await page.waitForSelector("button[data-testid=add-staff]", {
        timeout: 6000
      });
      await page.click("button[data-testid=add-staff]");
      await page.fill("#emailAddresses", `${EMAIL6}`);
      ....
},
    TEST_TIMEOUT
  );
```

Occasionally on other tests rather than timeout, it will end the navigation with ERR:aborted after 1 or 2 seconds. The random nature of where / when a test might fail make it impossible to debug. The tests are simple, 95% of tests work 100% of the time, and the other 5% work 90% of the time. Running sequentially increases the time by 5 or 10 times the amount. Detailed debug traces reveal nothing other than some worker processes simply halt/stop responding or just abort. In headless mode the tests might stop but the browser remains responsive, and the "waiting buttons" can be clicked on. What could be causing particular Playwright threads to get blocked or stuck?

**Comment by yury-s** [comment]
All tests inside single `describe(scenario` block should run sequentially and should not be affected by parallel run. The tests from different describe blocks use their own browsers processes with ephemeral contexts and should be well isolated from each other during parallel execution.  Probably you run too many parallel workers for the machine and it just gets overwhelmed causing slowness and timeouts. It might also be that the server behaves differently when there are parallel clients.

**Comment by yury-s** [comment]
What does `blocks` actually do? Does it call `test.concurrent` at some point?

**Comment by cullman1** [comment]
Ok - the concurrency issue seems to be at the DB end, which due to incomplete error reporting looked more a playwright issue. (we were seeing time outs, but there was a db error when inspected closely).  There is another concurrency issue wrapped up in there that the team are experiencing, where the browser will just reject some requests when tests are running concurrently ...with ERR_ABORTED, BUT I couldn't reproduce consistently and the team found a workaround (creating a new browser context for each individual test, instead of using the same one which adds a bit of time to the tests but not massively) to make sure it doesn't happen at all. So I'm closing this issue. Thanks for getting back.

**Comment by yury-s** [comment]
Cool, thanks for posting the update. In general we recommend running each test scenario in a new context for maximal state isolation. Context is very cheap, in your case you were also reusing the same page so the difference now is that you also create a new page (which entails new render process creation etc) and that contributes to the performance. Unless this performance hit is critical for you we'd encourage you start with separate contexts for separate tests.
