### ISSUE TITLE
[BUG]Playwright Webkit :: elementHandle.screenshot() not capturing the screenshot of the entire area of the element

### ISSUE THREAD

**Issue by linichacko** [microsoft/playwright#6691]
**Context:**
- Playwright Version: v1.11.0
- Operating System: Mac or Windows
- Node.js version: 15.14.0
- Browser: WebKit
- Extra: [any specific details about your environment]

**Code Snippet**

const example = await page.$('.adn.ads');
await example.screenshot({path: `example.png`});

**Describe the bug**
In chromium (headless: false) , the whole portion of the element screenshot is captured, but in webkit (headless: false), only the visible area in view port is captured. Tried the clip option in page.screenshot() , but no luck

**Comment by yury-s** [comment]
@linichacko  Can you share the page and failing code snippet?

**Comment by pavelfeldman** [comment]
We need additional details requested above to act on this issue! Please file a new one and link this issue there to follow up!
