### ISSUE TITLE
[Question] Do not pause with inspector enabled

### ISSUE THREAD

**Issue by chambo-e** [microsoft/playwright#6694]
Hello 👋 ,  

I'm trying to run a script with the inspector enabled and without pausing the execution
Running `resume` at the beginning of the script does not work for subsequent pauses.
Is there any way to do this ? 

Thanks :)

**Comment by yury-s** [comment]
> Running `resume` at the beginning of the script does not work for subsequent pauses.

Resume state is not preserved between playwright launches so this is working as intended. We assume that people run their scripts with inspector when debugging them in which case pausing in the beginning gives the user a chance to run it step by step from the very beginning. Do you want to run your script with inspector open but without pausing on the first call and only pause on failures? What is your use case?

**Comment by pavelfeldman** [comment]
Please open a new bug to follow up and link this one if there is additional input or the answer above does not cover it!
