### ISSUE TITLE
[BUG] ElectronApplication is missing some common EventEmitter types

### ISSUE THREAD

**Issue by samuelmaddock** [microsoft/playwright#6699]
**Context:**
- Playwright Version: playwright-electron@0.5.0
- Operating System: Windows
- Node.js version: 14.16.1
- Browser: Electron

**Code Snippet**

```javascript
const app = await electron.launch(electronPath, args: ['...']);
const listener = () => {};
app.on('window', listener);
app.off('window', listener);
```

**Describe the bug**

The type definitions for playwright-electron seem to be missing a few common methods that exist, but aren't typed. `ElectronApplication` has `addListener()` and `on()`, but no `removeListener()` or `off()`.

**Comment by mxschmitt** [comment]
The playwright-electron package is deprecated, try to use the normal playwright package to see if the error is also persistent in the latest version. See here for the documentation: https://playwright.dev/docs/api/class-electron

**Comment by samuelmaddock** [comment]
@mxschmitt The `playwright` package indeed has these types, thanks!

It'd be great if `playwright-electron` could be [deprecated on npm](https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions) to avoid this confusion for others.

**Comment by mxschmitt** [comment]
We will do it, hopefully today! Thanks for your suggestion.
