### ISSUE TITLE
Question: Any plans to support Cucumber.js? 

### ISSUE THREAD

**Issue by Phonesis** [microsoft/playwright#670]
Currently use Protractor but keen to potentially move over to Playwright. However, we use Cucumber.js along with the Protractor-Cucumber-Framework library to structure our tests in a BDD format. 

Wondered if Playwright will support Cucumber? Will be just work as step definition code (replacing the existing protractor code with it) or is there more to it?

**Comment by JoelEinbinder** [comment]
I’m not super familiar with cucumber, but I’d imagine that’s something they would need to do on their end. We aren’t planning to do anything special to support them, but if there are some capabilities we are lacking I can look into them.

**Comment by aslushnikov** [comment]
If I understand correctly, cucumber is a plain language test runner, whereas playwright provides API to drive browsers. So in order for cucumber to work with playwright, someone needs to come up with `cucumber-playwright` package - similarly to the [cucumber-puppeteer](https://github.com/patheard/cucumber-puppeteer#readme).

We are not in a position to do `cucumber-playwright` - we're not experts there, but if someone comes up with the package, we'd be happy to refer to it from our documentation.
