### ISSUE TITLE
[Question] block level coverage

### ISSUE THREAD

**Issue by gullerya** [microsoft/playwright#6707]
I'm seemingly can't found a documentation on taking coverage with block precision level.

What I do?
I'm using the method `startJSCoverage()` with Chromium. Here, I do not see an option to make it block level (detailed).

What am I missing?
The coverage returns back (upon `stopJSCoverage()`) while `isBlockCoverage` is always `false`.

Is it possible to run coverage in precise mode?

**Comment by yury-s** [comment]
Can you share code snippet where block coverage is missing?  We do collect coverage reports with [block-level](https://github.com/microsoft/playwright/blob/adf87fe9c6c8a661173c2d0912ac440b6a5885a2/src/server/chromium/crCoverage.ts#L86) details and I just checked that isBlockCoverage is true for the functions where block-level information was collected. Here is a report for [this test](https://github.com/microsoft/playwright/blob/adf87fe9c6c8a661173c2d0912ac440b6a5885a2/tests/chromium/js-coverage.spec.ts#L22):

```json
[
  {
    "scriptId": "4",
    "url": "http://localhost:8907/jscoverage/simple.html",
    "functions": [
      {
        "functionName": "",
        "ranges": [
          {
            "startOffset": 0,
            "endOffset": 61,
            "count": 1
          }
        ],
        "isBlockCoverage": true
      },
      {
        "functionName": "foo",
        "ranges": [
          {
            "startOffset": 1,
            "endOffset": 53,
            "count": 1
          }
        ],
        "isBlockCoverage": true
      },
      {
        "functionName": "bar",
        "ranges": [
          {
            "startOffset": 17,
            "endOffset": 35,
            "count": 0
          }
        ],
        "isBlockCoverage": false
      }
    ],
    "source": "\nfunction foo() {function bar() { } console.log(1); } foo(); "
  }
]
```

Note that `isBlockCoverage` is false for function `bar` which is ok as it could have been optimized out.

**Comment by gullerya** [comment]
I see.

I'll try to narrow down what I'm doing, since the whole story is TLRD;
The code doing, also, the very logic of start/stop coverage is [here](https://github.com/gullerya/just-test/blob/restructure/src/server/environments/browser/browser-env-service.js).

The steps are as following:
- launch browserContext
- expose bindings for 2 functions: start / stop coverage (I need to manage this flow from the 'client' side)
- the bindings are exposed on the context level, if any important

Observations:
- when running that with the Playwright's `coverage` syntax sugar - never seen `isBlockCoverage` true 
- when running with CDP session and `Profiler.start... / stop...` I do get `isBlockCoverage` true (and seemingly the data of the ranges self is different, i'm collecting the differences now), __BUT__
- this `isBlockCoverage` true shows up ONLY when I'm stopping on it in VSCode debugger, so that even when running in debug mode but not stopping on some breaking point - `isBlockCoverage` is always false

So, essentially it splits into 2:
- Playwright's start / stop is not getting me anywhere
- even the `Profiler...` approach, which is not related per se to the Playwright, behaves strangely

Is there any special evaluation of the coverage object happening that can explain?

**Comment by gullerya** [comment]
Few things, that caught my eyes when looking onto the Playwright's `coverage` object:
- I'm attaching new CDP session per page (not sure if the 'client' is reused in your case)
- I'm not fiddling with `Debugger`, presuming that you need it only for the high level functionality like scripts filtering / sources provisioning etc

Hope that may give some clues...

**Comment by gullerya** [comment]
I'll add more to this:
- as I've said, I'm collecting the coverage per page, via dedicated CDP session
- pages are not created via Playwright, but `window.open('', 'something')` from within the main page
- some specific script that I'm tracking here is 'injected' into the page via new `script` tag attached to that newly created window/document

Let's assume that I can track the pages' IDs.
Let's assume that I'm interested in some specific script, so narrowing it down.

The table below shows what I'm getting after running 5 pages:
| Times script seen | Page ID | script IDs |
|-------------------|--------|----------- |
| 2 | page-0 | 129, 138 |
| 1 | page-1 | 140 |
| 2 | page-2 | 140, 141 |
| 3 | page-3 | 140, 141, 142 |
| 3 | page-4 | 140, 141, 142 |

What's specifically interesting:
- scripts reused across the pages?!
- due to the point above, time script seen per page is absolutely random

What am I missing?

**Comment by yury-s** [comment]
> * this `isBlockCoverage` true shows up ONLY when I'm stopping on it in VSCode debugger, so that even when running in debug mode but not stopping on some breaking point - `isBlockCoverage` is always false

It suggests that the coverage may not work properly for optimized code, when you stop on a breakpoint the compiled code usually gets deoptimized and that may help with collecting coverage. Since this is devtools profiler issue it's better to ask chrome devtools team about the reasons why the coverage is missing there.

**Comment by yury-s** [comment]
> * I'm not fiddling with `Debugger`, presuming that you need it only for the high level functionality like scripts filtering / sources provisioning etc

Well, enabling debugger turns off optimizations. I don't know much details of the coverage implementation but I'd expect it to work properly only for non-optimized functions, i.e. without enabling debugger the coverage will be  collected only for those functions that happened to be unoptimized which is somewhat unpredictable.

Do you have a small repro that uses playwright API (rather than raw CDP) and where the coverage report is not working?

**Comment by gullerya** [comment]
I'll try to play with it a bit more, in general will be able to just give here few command lines to run on my branch and you'll get the output. But let me play a bit more with this.

BTW, I'm trying to turn on the debugger (well, pretty much almost the same as in the code you've sent me), but seemingly the code still get's optimized - I'm judging from the coverage data self...
