### ISSUE TITLE
[Question] Test Execution: Documentation missing 

### ISSUE THREAD

**Issue by macroking** [microsoft/playwright#6711]
Looks like there is no documentation around test execution. I think we can include steps to execute the playwright script in the **Getting Started** section.

**Comment by mxschmitt** [comment]
What kind of documentation do you think is missing? The execution is up to the user, either via a test runner or directly e.g. via node script.js.
There is also a dedicated section for test-runners: https://playwright.dev/docs/test-runners

**Comment by macroking** [comment]
A user without any prior knowledge hits the Getting Started section, we are showing a sample test script which is good. In addition to that if we can show steps to execute the sample test script. He would be very happy to try it out immediately without having to browse through the entire documentation. Something like this https://www.protractortest.org/#/tutorial which has a nice information flow for a new user.

**Comment by vsravuri** [comment]
I am migrating my test cases from Protractor to Playwright. Trying to find out documentation how to integrate Jasmine test runner with Playwright. It will be very helpful if there is an example of test framework (config file) how to integrate Playwright with test runner.

**Comment by aslushnikov** [comment]
We now have a tracking bug for test runner: https://github.com/microsoft/playwright/issues/6857
