### ISSUE TITLE
[BUG] Inconsistent behavior when using connectOverCDP

### ISSUE THREAD

**Issue by redReno** [microsoft/playwright#6715]
**Context:**
- Playwright Version:  1.11.0
- Operating System: Linux
- Node.js version: v13.10.1
- Browser:  Chromium
- Project: JS and React with Material

**What I want to do**

We have a web page which uses a Material FAB button. When the button is clicked, it displays a speed dial action buttons which can be clicked to open their respective linked pages. https://material.io/components/buttons-floating-action-button

The speed dials are configured to stay up until clicked, like this:
![image](https://user-images.githubusercontent.com/5901432/119359512-02100a80-bcaa-11eb-86d6-3f38646e0d3c.png)

I can perform these actions without issue when I create a new browser context manually. The example below is not the real code but does the same thing.

```javascript
  const browser = await chromium.launch();
  const page = await browser .newPage();
  await page.goto('${URL'});
  await page.click('[data-testid=bigFab]');
  await page.click('[data-testid=smallFab]');
```

I want to do the same thing using an already running Chromium instance.
So I run the browser with:  ~/.cache/ms-playwright/chromium-878941/chrome-linux --remote-debugging-port=9222 --no-sandbox

And then: 
```
  browser = await chromium.connectOverCDP({endpointURL: 'http://localhost:9222'});
  const page = await browser.newPage();
  await page.goto('${URL}');
  await page.click('[data-testid=bigFab]');
  await page.click('[data-testid=smallFab]');
```

**What happens**
Playwright is able to load the page and click the first button. The test gives the first click a pass, but it seems that either the speed dial buttons never appear, or if they do, disappear before the buttons can be clicked. If I debug using VSC I never see the buttons appear. They are supposed to stay up indefinitely or until clicked. If I tried to force the click, the element is outside the viewport. But using dispatchEvent worked:

```
  await page.dispatchEvent('[data-testid=bigFab]');
  await page.dispatchEvent('[data-testid=smallFab]');
```
To make it clearer, I can use the normal click function with any other button element I've tested, but there seems to be an issue with the FAB buttons and the speed dial when using connectOverCDP.

**Wanted behavior**
The web page should behave the same whether I use the chromium.launch() function or use connectOverCDP() to make use of an existing instance. If any related events are triggered when the normal click() function is used in the former, it should work with the latter, because I would prefer to avoid using dispatchEvent.

**Comment by yury-s** [comment]
@redReno can you attach a page with the configured buttons where the click doesn't work?

**Comment by redReno** [comment]
@yuru-s I can't use that project but I'll try to recreate it in a project of my own.

**Comment by pavelfeldman** [comment]
We'll keep it open for a few more days, but we really need those repro steps in order to fix it!

**Comment by redReno** [comment]
Thanks. I have unfortunately not been able to allocate the time to create a custom page for the test yet. I will try to get it done tomorrow. If I can't do it then it's probably better that I come back to this when I do get the time, especially if no one else has this problem.

**Comment by redReno** [comment]
Update: I've managed to get the test to pass, by:

1) Starting a local installation of chromium, headless.
/usr/bin/chromium -remote-debugging-port=9222 --headless
2) Running the test using the ws address and headless, with executable path set.
  let browser = await chromium.connectOverCDP({
    endpointURL: 'ws://localhost:9222/devtools/page/06C3ED12A88B62550CF613ECD298297C',
    headless: false,
    executablePath: '/usr/bin/chromium'
  });
  const context = await browser.newContext();
  const page = await context.newPage();
...
rest of test code ..
...

I'm not sure what has changed, but when I try to recreate my instructions from the first message, I get this error:

node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

browser.newContext: Protocol error (Target.createBrowserContext): Not allowed
Error
    at Object.captureStackTrace (/home/alfs/git/acs/node_modules/playwright/lib/utils/stackTrace.js:50:19)
    at Connection.sendMessageToServer (/home/alfs/git/acs/node_modules/playwright/lib/client/connection.js:65:48)
    at Proxy.<anonymous> (/home/alfs/git/acs/node_modules/playwright/lib/client/channelOwner.js:64:61)
    at /home/alfs/git/acs/node_modules/playwright/lib/client/browser.js:43:81
    at async Browser._wrapApiCall (/home/alfs/git/acs/node_modules/playwright/lib/client/channelOwner.js:77:28)

The difference is that I run the test headless. It doesn't matter if I try using my own chromium installation or the Playwright one. Do you have a recommended way of using chromium.connectOverCDP? Is it even a good idea to use it with headfull?

**Comment by redReno** [comment]
I think I managed to get an example working. It's not a 1-1 page and the error is a little different, but it is interesting.
I made a project with a small web page, and two playwright tests.

For some reason, using ws with CDP did not work, but localhost:9222 did. Any reason for this?

Here are some instructions.
1) Use yarn, and yarn start to start the server.
2) Start a chromium browser with --remote-debugging-port=9222
3. Run two tests with yarn test. The first will start a new browser, the next will use CDP.
4. The CDP test should fail, since a hover command fails to display the other buttons. It is possible to help it out by hovering the button manually. I made sure that the button was visible and it still fails.
5. Here is the interesting part - if you start the browser with the debug flag AND --headless, both tests will pass.

Here is the repo.
https://github.com/redReno/test_fab_with_playwright

Thanks for looking into this. It's not exactly the same issue as I described before but they do seem to behave differently.

**Comment by dgozman** [comment]
@redReno Thank you for the repro! I went ahead and tried it, but without any luck. If there is anything else I can try, please let me know.

```sh
git clone git@github.com:redReno/test_fab_with_playwright.git
cd test_fab_with_playwright
yarn install
yarn start
```

Then I also launched the browser manually. Note that I am using MacOS, and launch the Chromium version that comes with Playwright. I have tried both with `--headless` and without it.
```sh
/Users/dgozman/Library/Caches/ms-playwright/chromium-878941/chrome-mac/Chromium.app/Contents/MacOS/Chromium --remote-debugging-port=9222 --headless
```

Now running tests, and both of them work.
```sh
DEBUG=pw:api,pw:browser* node playwright_test/test.js
```

<summary>
Here are the logs
<details>

```log
  pw:api => browserType.launch started +0ms
  pw:browser <launching> /Users/dgozman/Library/Caches/ms-playwright/chromium-878941/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --user-data-dir=/var/folders/rb/xdvh0vks3n3c0tztdc3r8rtm0000gn/T/playwright_chromiumdev_profile-nC2Fg4 --remote-debugging-pipe --no-sandbox --no-startup-window +0ms
  pw:browser <launched> pid=14329 +4ms
  pw:api <= browserType.launch succeeded +475ms
  pw:api => browser.newContext started +1ms
  pw:api <= browser.newContext succeeded +7ms
  pw:api => browserContext.newPage started +0ms
  pw:api <= browserContext.newPage succeeded +500ms
  pw:api => page.goto started +1ms
  pw:api navigating to "http://localhost:3000", waiting until "load" +1ms
  pw:api   navigated to "http://localhost:3000/" +31ms
  pw:api   "domcontentloaded" event fired +270ms
  pw:api   "load" event fired +1ms
  pw:api <= page.goto succeeded +105ms
  pw:api => page.hover started +0ms
  pw:api waiting for selector "button" +4ms
  pw:api   selector resolved to visible <button tabindex="0" type="button" aria-haspopup="true" …>…</button> +17ms
  pw:api attempting hover action +3ms
  pw:api   waiting for element to be visible and stable +1ms
  pw:api     element is not stable - waiting... +23ms
  pw:api   element is visible and stable +86ms
  pw:api   scrolling into view if needed +1ms
  pw:api   done scrolling +0ms
  pw:api   checking that element receives pointer events at (44,380) +2ms
  pw:api   element does receive pointer events +4ms
  pw:api   performing hover action +0ms
  pw:api   hover action done +113ms
  pw:api   waiting for scheduled navigations to finish +1ms
  pw:api   navigations have finished +1ms
  pw:api <= page.hover succeeded +1ms
  pw:api => page.click started +0ms
  pw:api waiting for selector "[data-testid=facebook]" +2ms
  pw:api   selector resolved to visible <svg focusable="false" aria-hidden="true" viewBox="0 …>…</svg> +3ms
  pw:api attempting click action +3ms
  pw:api   waiting for element to be visible, enabled and stable +0ms
  pw:api     element is not stable - waiting... +33ms
  pw:api   "networkidle" event fired +99ms
  pw:api   element is visible, enabled and stable +4ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +1ms
  pw:api   checking that element receives pointer events at (44,316) +1ms
  pw:api   element does receive pointer events +4ms
  pw:api   performing click action +0ms
  pw:api   click action done +219ms
  pw:api   waiting for scheduled navigations to finish +0ms
  pw:api   navigations have finished +1ms
  pw:api <= page.click succeeded +0ms
  pw:api => browser.close started +0ms
  pw:api => browserType.connectOverCDP started +1ms
  pw:browser [pid=14329] <gracefully close start> +2s
  pw:browser <ws connecting> ws://localhost:9222/devtools/browser/6a3be3d0-245e-4e70-8ff5-e6bc107d51fb +12ms
  pw:browser <ws connected> ws://localhost:9222/devtools/browser/6a3be3d0-245e-4e70-8ff5-e6bc107d51fb +4ms
  pw:api <= browserType.connectOverCDP succeeded +26ms
  pw:api => browser.newContext started +0ms
  pw:api <= browser.newContext succeeded +2ms
  pw:api => browserContext.newPage started +0ms
  pw:api <= browserContext.newPage succeeded +115ms
  pw:api => page.goto started +0ms
  pw:api navigating to "http://localhost:3000", waiting until "load" +1ms
  pw:api   navigated to "http://localhost:3000/" +16ms
  pw:browser [pid=14329] <process did exit: exitCode=0, signal=null> +405ms
  pw:api   "domcontentloaded" event fired +280ms
  pw:api   "load" event fired +10ms
  pw:browser [pid=14329] <gracefully close end> +33ms
  pw:api <= browser.close succeeded +6ms
  pw:api <= page.goto succeeded +97ms
  pw:api => page.hover started +0ms
  pw:api waiting for selector "button" +1ms
  pw:api   selector resolved to visible <button tabindex="0" type="button" aria-haspopup="true" …>…</button> +20ms
  pw:api attempting hover action +3ms
  pw:api   waiting for element to be visible and stable +0ms
  pw:api     element is not stable - waiting... +26ms
  pw:api   element is visible and stable +86ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +1ms
  pw:api   checking that element receives pointer events at (44,380) +2ms
  pw:api   element does receive pointer events +3ms
  pw:api   performing hover action +0ms
  pw:api   hover action done +112ms
  pw:api   waiting for scheduled navigations to finish +0ms
  pw:api   navigations have finished +1ms
  pw:api <= page.hover succeeded +1ms
  pw:api => page.click started +0ms
  pw:api waiting for selector "[data-testid=facebook]" +1ms
  pw:api   selector resolved to visible <svg focusable="false" aria-hidden="true" viewBox="0 …>…</svg> +3ms
  pw:api attempting click action +3ms
  pw:api   waiting for element to be visible, enabled and stable +0ms
  pw:api     element is not stable - waiting... +24ms
  pw:api   "networkidle" event fired +110ms
  pw:api   element is visible, enabled and stable +15ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +1ms
  pw:api   checking that element receives pointer events at (44,316) +1ms
  pw:api   element does receive pointer events +4ms
  pw:api   performing click action +0ms
  pw:api   click action done +163ms
  pw:api   waiting for scheduled navigations to finish +0ms
  pw:api   navigations have finished +2ms
  pw:api <= page.click succeeded +0ms
  pw:api => browser.close started +0ms
  pw:browser <ws disconnecting> ws://localhost:9222/devtools/browser/6a3be3d0-245e-4e70-8ff5-e6bc107d51fb +682ms
  pw:browser <ws disconnected> ws://localhost:9222/devtools/browser/6a3be3d0-245e-4e70-8ff5-e6bc107d51fb +1ms
  pw:api <= browser.close succeeded +3ms
```

</details>
</summary>

**Comment by pavelfeldman** [comment]
@redReno: I'm triaging bugs and closing those not actionable. If this is still an issue, please open a new bug and link this one.
