### ISSUE TITLE
[BUG] page.selectOption() throws on navigation

### ISSUE THREAD

**Issue by yury-s** [microsoft/playwright#6725]
`should not throw when select causes navigation` test is [flaky](https://devops.aslushnikov.com/flakiness2.html#filter_spec=should+not+throw+when+select+causes+navigation&browser=webkit&timestamp=1621884655183) in WebKit.

The problem is that in WebKit `evaluateWithArguments` is implemented as three protocol commands:
`Runtime.callFunctionOn` - get original eval result
`Runtime.awaitPromise` - optional await for promise
`Runtime.callFunctionOn` - to serialize handle to JSON

If first callFunctionOn causes navigation any of the subsequent 2 commands may fail and eval will throw in this case.

**Comment by dgozman** [comment]
This was fixes by #6852.
