### ISSUE TITLE
[Feature] Want to add popup window capture to "page. Screenshot"

### ISSUE THREAD

**Issue by luxuncang** [microsoft/playwright#6734]
Returns the buffer with the captured screenshot and popup window?
The screenshot cannot contain popup window. I hope this function can be added.

Thank you for your project !

**Comment by yury-s** [comment]
You can listen for [`popup`](https://playwright.dev/docs/multi-pages?_highlight=popup#handling-popups) event and take screenshot of the popup page separately.

Closing this issue as there are no current plans to provide screenshots containing multiple pages.

**Comment by luxuncang** [comment]
Thank you very much for your advice.
