### ISSUE TITLE
[Question] Determine playwright Version 

### ISSUE THREAD

**Issue by karanshah-browserstack** [microsoft/playwright#6736]
How do I determine the playwright version running on the machine when user makes websocket connection?

**Comment by mxschmitt** [comment]
So far there is no way, but you can use the headers option to send the Playwright version as a header when a clients connects: https://playwright.dev/docs/api/class-browsertype#browsertypeconnectparams

**Comment by pavelfeldman** [comment]
What is your use case?

**Comment by karanshah-browserstack** [comment]
@pavelfeldman We are trying to run this in grid mode(i.e client running on one machine and server is running on a different machine) and see certain differences that are breaking across versions.  We couldn't establish the connection when client was running on 1.10.0 and server was running 1.11.0. Hence, we just want to detect the playwright versions and handle it gracefully.
