### ISSUE TITLE
[BUG] - Empty 2kb videos generated when accessing `context.storageState()`

### ISSUE THREAD

**Issue by bmcbrayerledgex** [microsoft/playwright#6743]
## Context:
- Playwright Version: 1.11.0
- Operating System: Windows 10
- Node.js version: 14.16.1
- Browser: Chromium (EDIT: also Firefox, also WebKit)
### System:
 - OS: Windows 10 10.0.19043
 - Memory: 18.00 GB / 31.71 GB
### Binaries:
 - Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
### Languages:
 - Bash: 4.4.23 - C:\Program Files\git\usr\bin\bash.EXE

## Code Snippet

```javascript
import { chromium } from "playwright"; // EDIT: Note, also happens in Firefox and WebKit
(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext({ recordVideo: { dir: 'results/videos' } });
  const page = await context.newPage();
  await page.goto("https://www.google.com");
  for (let i = 0; i < 100; i++) {
    await context.storageState();
  }
  await browser.close();
})();
```

## Description of bug

I found that when I record a video of a page, if I access `context.storageState()`, a tiny, 0-second, 2kb .webm is generated sometimes. The script above produces one video of Google and usually 5-10 empty videos with hashes as their names.

I've looked through the Playwright code and cannot determine what causes this.

Playwright is awesome by the way!

UPDATE: This also happens in Firefox
UPDATE: This also happens in WebKit

**Comment by bmcbrayerledgex** [comment]
Update: just in case someone doesn't read the update in the bug report, this also happens in Firefox

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
