### ISSUE TITLE
[BUG] Transparent stripes on screenshots

### ISSUE THREAD

**Issue by chrstnv** [microsoft/playwright#6744]
**Context:**

- Playwright Version: 1.10.0
- Operating System: Mac
- Node.js version: v12.16.2
- Browser: Chromium
- Extra: jest-playwright-preset (v1.5.2), jest (v25.5.4), jest-image-snapshot (v4.4.1)

**Code Snippet**

Here is my simplified code snippet. Actually I have 83 such kind of screenshot tests for different users and ui blocks. They test the same hint component with different text content.

```javascript
const {jest} = require('@jest/globals');
const {chromium} = require('playwright');

jest.retryTimes(1);

class MyPage {
    constructor(page) {
        this.page = page;
    }
    async navigate() {
        await this.page.goto('https://my-app-url.com', {waitUntil: 'networkidle'});
    }
}

describe('My page tests', () => {
    let browser;
    let myPage;
    let context;
    let page;

    beforeEach(async () => {
        browser = await chromium.launch();
        context = await browser.newContext({ignoreHTTPSErrors: true});

        page = await context.newPage();

        myPage = new MyPage(page);
    });

    afterEach(async () => {
        await browser.close();
    });

    describe('First tab', () => {
        beforeEach(async () => {
            await myPage.navigate();

            await page.waitForResponse('**/api/some-domain**');

            const isInformerVisible = await page.isVisible('informer-selector');

            // hide informer tooltips that could affect screenshots
            if (isInformerVisible) {
                await page.click('informer-selector');
            }
        });

        it('Hint content looks correct', async () => {
            await page.click('hint-toggler-selector');

            const activeDropdownElem = await page
                .waitForSelector('hint-content-dropdown-selector', {state: 'visible'});

            // wait for the animation to end
            await activeDropdownElem.waitForElementState('stable');

            expect(await activeDropdownElem.screenshot({omitBackground: true})).toMatchImageSnapshot();
        });
    });
});
```

My test component looks like this:
![image](https://user-images.githubusercontent.com/17298953/119548142-9491d600-bd9e-11eb-80d3-a5ee85a61200.png)

**Describe the bug**

Sometimes on about 1-2 random tests out of 83, a transparent horizontal stripe appears on the captured screenshot. Unfortunately, I did not achieve stable reproduction of the bug.

![image](https://user-images.githubusercontent.com/17298953/119548198-a2475b80-bd9e-11eb-8d0e-aae9951a1aeb.png)

This is on an IDE background:

![image](https://user-images.githubusercontent.com/17298953/119548236-aa9f9680-bd9e-11eb-9271-8cdf91ca7f47.png)

I have implemented the same tests on puppeteer, and this bug has never been reproduced in several runs.

I've been tried to completely eliminate the unstable state of the component when I take a screenshot. I wait for the data to be fully loaded, wait for the animation to end when the tooltip is expanded. I even tried setting a long timeout before taking a screenshot, and the problem was reproduced anyway. When debugging in the inspector, it wasn't reproduced even once.

I would be very grateful for some thoughts about possible causes of the problem!

**Comment by pavelfeldman** [comment]
> I have implemented the same tests on puppeteer, and this bug has never been reproduced in several runs.

This is likely due to Puppeteer using an older Chrome version.

> I've been tried to completely eliminate the unstable state of the component when I take a screenshot.

Some things are inherently racy, including web font swap - even though everything is loaded, if you are using web font, it'll be swapped live. Another one would be rasterisation when browser renders your data using GPU or CPU compositing.

Try switching from the GPU to CPU compositing: add `--disable-gpu` in the Chromium launch args.

**Comment by aslushnikov** [comment]
Closing this since discussion has stalled; please feel free to re-submit a new one if there's a question!
