### ISSUE TITLE
[BUG] Electron - race condition when evaluating multiple BrowserWindows

### ISSUE THREAD

**Issue by samuelmaddock** [microsoft/playwright#6748]
**Context:**
```
## System:
 - OS: Windows 10 10.0.19042
 - Memory: 16.79 GB / 31.91 GB
## Binaries:
 - Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.19.1 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 7.11.2 - C:\Program Files\nodejs\npm.CMD
## Languages:
 - Bash: 4.4.23 - C:\Program Files\Git\usr\bin\bash.EXE
## npmPackages:
 - playwright: ^1.11.1 => 1.11.1
 ```

**Code Snippet**

I wrote an example Electron application demonstrating the issue using [Electron Fiddle](https://www.electronjs.org/fiddle): https://gist.github.com/38f12167513796435d2012df6dc2e8d0

The important snippet from the gist is in renderer.js:
```js
window.open('https://www.electronjs.org', 'firstWindow')
window.open('https://github.com/electron/electron', 'secondWindow')
```

```javascript
const path = require('path');
const { _electron: electron } = require('playwright');

(async () => {
  const app = await electron.launch({
    args: ['/path/to/saved/electron/fiddle'],
  });

  app.on('window', async page => {
    const browserWindowHandle = await app.browserWindow(page);

    const frameName = await browserWindowHandle.evaluate(
      browserWindow => browserWindow.webContents.mainFrame.name,
    );

    console.log(
      `app 'window' event [frameName:${frameName}, playwrightFrameName:${page.mainFrame().name()}, url:${page.url()}]`,
    );
  });
})();

```

**Describe the bug**

The Electron Fiddle gist linked above opens a new BrowserWindow with a button that opens two other BrowserWindows. Each of the BrowserWindows opened have their own, unique frame name and URL.

Running the test and clicking the button demonstrates some issues:
- `page.mainFrame().name()` never reads the actual frame name of the Electron BrowserWindow.
- The frame name received from evaluating the `browserWindowHandle` doesn't always match the expected `page.url()`.
   - Potential race condition?

Here's an example of  output I've seen from running this.
```
$ node test.js 
app 'window' event [frameName:firstWindow, playwrightFrameName:, url:https://www.electronjs.org/]
app 'window' event [frameName:secondWindow, playwrightFrameName:, url:https://github.com/electron/electron]
app 'window' event [frameName:firstWindow, playwrightFrameName:, url:https://www.electronjs.org/]
app 'window' event [frameName:secondWindow, playwrightFrameName:, url:https://github.com/electron/electron]
app 'window' event [frameName:firstWindow, playwrightFrameName:, url:https://github.com/electron/electron]
app 'window' event [frameName:secondWindow, playwrightFrameName:, url:https://www.electronjs.org/]
```

Notice the last two console messages in which `frameName` doesn't match the expected `url`.

**Comment by samuelmaddock** [comment]
Here's the equivalent test for Chromium:
```js
const { chromium } = require('playwright');

(async () => {
  const app = await chromium.launch({ headless: false })
  const page = await app.newPage()

  await page.goto('about:blank')

  const pages = []

  page.context().on('page', async (page) => {
    pages.push(page)
    
    const frameName = await page.evaluate(() => {
      return window.name;
    })

    console.log(
      `app 'window' event [frameName:${frameName}, playwrightFrameName:${page
        .mainFrame()
        .name()}, url:${page.url()}]`,
    );
  })

  do {
    await page.evaluate(() => {
      window.open('https://www.electronjs.org', 'firstWindow')
      window.open('https://github.com/electron/electron', 'secondWindow')
    })
    await new Promise(resolve => setTimeout(resolve, 2000))
    await Promise.all(pages.map(page => page.close()))
    await new Promise(resolve => setTimeout(resolve, 1000))
  } while (true);
})();
```

- `page.mainFrame().name()` also doesn't work here.
- The 'page' event is sometimes received out of order (secondWindow then firstWindow), which may hint at the possible underlying issue.

**Comment by yury-s** [comment]
> Here's the equivalent test for Chromium:
> ...
This one is working as intended, see below.

> * `page.mainFrame().name()` also doesn't work here.

[`Frame.name()`](https://playwright.dev/docs/api/class-frame?_highlight=frame.nam#framename) "Returns frame's name attribute as specified in the tag.", window.name is different.

> * The 'page' event is sometimes received out of order (secondWindow then firstWindow), which may hint at the possible underlying issue.

This is also expected as `window.open()` calls are handled asynchronously and corresponding `Page` events can come in any order.
