### ISSUE TITLE
[BUG] Firefox 89.0b6 evaluate `document.getAnimations()` failed

### ISSUE THREAD

**Issue by zyscoder** [microsoft/playwright#6750]
**Context:**
- Playwright Version: 1.11.1
- Operating System: Linux
- Node.js version: v14.15.1
- Browser: Firefox

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const { firefox } = require('playwright');

(async () => {
    const browser = await firefox.launch();
    console.log(`${browser.version()}`);
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto('http://www.disney.cn/');
    const code = "document.getAnimations();";
    try {
        const res = await page.evaluate(code);
        await res;
    } catch(e) {
        console.error(e.toString());
    }
})();
```

**Describe the bug**

Run the code above and an exception would be thrown:
```
~ » node test.js
89.0b6
TypeError: page.evaluate: value.a.map is not a function
```

**Comment by yury-s** [comment]
Array has a custom map method on that site, evaluating `'' + [].map` gives this: 
```js
"function(C){var D=[];this.each(function(A,B){D.push((C||Prototype.K)(A,B));});return D;}"
```
for some reason it works incorrectly when we call it in our utility script. As a workaround we can switch to `Array.prototype.map`

**Comment by yury-s** [comment]
On a closer look the page overrides JSON.stringify and it works incorrectly: `JSON.stringify({a:[1]})` returns `'{"a":"[1]"}'` instead of `'{"a":[1]}'`. We should not use overridden version of the method but our workaround fails on this site.
