### ISSUE TITLE
[BUG] pw-video: error capturing video: ffmpeg exited with code 1: Error initializing output stream 0:0

### ISSUE THREAD

**Issue by JohnnyMnemonick** [microsoft/playwright#6751]
**Context:**
- Playwright Version: 1.8.0
- Operating System: Windows 10
- Node.js version: 14,16
- Browser: Chromium

**Code Snippet**
```javascript
Context.capture = await saveVideo(page, `TestResults/recording.mp4`);
...
await Context.capture.stop()
```

**It worked fine until Playwright 1.8.0** (still works in 1.7.0) 
Video capture isn't working anymore, it generates:
```SQL
pw-video: error capturing video: ffmpeg exited with code 1: Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height

       Conversion failed!
```

**Comment by mxschmitt** [comment]
It seems your are using playwright-video which is not needed anymore in newer Playwright versions since it supports video recording for all browsers now.

See here for a guide: https://playwright.dev/docs/videos

**Comment by JohnnyMnemonick** [comment]
Not a bug but a feature (LOL)
