### ISSUE TITLE
[BUG] Chrome args "--start-maximized" doesn't work on macOS Big Sur 11.3.1

### ISSUE THREAD

**Issue by wanghongjuan** [microsoft/playwright#6752]
**Context:**
- Playwright Version: 1.11.1
- Operating System: macOS Big Sur 11.3.1 (Apple M1)
- Node.js version: v16.1.0
- Browser: Chrome

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium} = require('playwright-chromium');

(async () => {
  const browser = await chromium.launchPersistentContext('./userDataDir', {
    headless: false,
    args: ['--start-maximized']
  });
  const page = await browser.newPage();
  await page.goto('https://playwright.dev/docs/intro');
})();
```

**Describe the bug**

The webpage launches successfully without maximized window.

**Comment by yury-s** [comment]
Note that you also need to pass [`viewport: null`](https://playwright.dev/docs/api/class-browsertype#browsertypelaunchpersistentcontextuserdatadir-options) option to avoid Playwright resetting it to the default value. With that said, the flag doesn't  work in Chrome on Mac. Launching the browser from terminal with the flag doesn't maximize the window:

```sh
'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' --user-data-dir=./userDataDir --start-maximized about:blank
```
You can report this issue in http://crbug.com/

**Comment by wanghongjuan** [comment]
hi @yury-s thanks for your quickly response, I tried adding `viewport: null`, the flag still doesn't work, but launching the browser from terminal with the flag works well, so I think maybe this issue should be reported to here.

**Comment by mxschmitt** [comment]
I tested the following which works for me: 

```js
// @ts-check
const playwright = require('.');

(async () => {
    const context = await playwright.chromium.launchPersistentContext("./dir", {
      args: ["--start-maximized"],
      headless: false,
      viewport: null
    });
    const page = await context.newPage();
    await page.waitForTimeout(999999)
    await context.close();
})();
```

Keep in mind, that you need a clean user-dir, since in it Chromium stores the previous windows-locations.

**Comment by yury-s** [comment]
@mxschmitt it works fine on Linux for me but not on Mac. I'm still struggling to maximize Chrome even from the terminal without playwright.

**Comment by yury-s** [comment]
> hi @yury-s thanks for your quickly response, I tried adding `viewport: null`, the flag still doesn't work, but launching the browser from terminal with the flag works well, so I think maybe this issue should be reported to here.

I tried on macOS 10.15.7 and on 11.4, on both of them Chromium doesn't maximize when started from terminal with that flag. @aslushnikov also tried it on Big Sur and it didn't maximize. I also tried on Big Sur on M1 with same result.

**Comment by wanghongjuan** [comment]
Many thanks for your clarification again, I double confirmed that the Chrome can be maximized with old userDataDir, but failed with new userDataDir.
