### ISSUE TITLE
[Feature] Linux WebKit Connection Details Feature Parity (TLS info, Cert Info)

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#6759]
While working through https://github.com/microsoft/playwright/issues/6624 / https://github.com/microsoft/playwright/pull/6631 it became apparent that on Linux WebKit there are many connection and certificate details missing (like protocol, subjectName, validFrom, validTo, etc.) as WebKit has no way to currently populate the fields from libsoup.

This is an upstream issue: WebKit > libsoup > glib > glib-networking but cross-filing here to track bringing in the changes to Playwright WebKit for more feature parity with the other platforms:
1. Add `subject-name`, `issuer-name`, `not-valid-before`, `not-valid-after` ([glib PR](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2113) / [glib-networking PR](https://gitlab.gnome.org/GNOME/glib-networking/-/merge_requests/156))
2. add `protocol-version`, `ciphersuite-name` ([glib PR](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2077) / [glib-networking PR](https://gitlab.gnome.org/GNOME/glib-networking/-/merge_requests/151))

Feel free to assign to me as the first sent of linked glib* PRs are from me; I'm happy coordinate with the second set and intend to see the change through to WebKit (in Playwright's patched build or upstream depending on what a fully upstreamed WK patch entails).

Relates: #6624 
Relates: #6631 
Relates: [Playwright Slack Thread](https://playwright.slack.com/archives/C0141EZ6ZNH/p1622041407035900?thread_ts=1621906702.021200&cid=C0141EZ6ZNH)

**Comment by rwoll** [comment]
These patches ended up making it into glib 2.70 which should ship with Ubuntu 22.04 (April 2022). Once those are there, I can patch up Linux WK accordingly if someone else has not yet integrated the changes. (I don't want anyone to have to compile glib from scratch, so, IMO, it doesn't make sense to patch WK until next year.)

**Comment by mcatanzaro** [comment]
WebKit is not going to be allowed to depend on GLib 2.70 for a long time (several years). You're going to need to guard the new code with `#if GLIB_CHECK_VERSION`. You can do that whenever.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
