### ISSUE TITLE
page.goto: net::ERR_NAME_NOT_RESOLVED --DNS issue 

### ISSUE THREAD

**Issue by Paramesh82** [microsoft/playwright#6771]
Below issue we used to see frequently in version “1.6.2” but we are seeing it intermittently in current version “1.11.1”. 

**Error message :**
 
Error message :  page.goto: net::ERR_NAME_NOT_RESOLVED at http://AuroraVXXXX.AuroraXXXXdom.extest.microsoft.com/apps =========================== logs =========================== navigating to http://AuroraVXXXX.AuroraXXXXdom.extest.microsoft.com/apps, waiting until "networkidle"
 
**Call stack :**
Note: use DEBUG=pw:api environment variable to capture Playwright logs. Error: at Object.captureStackTrace (C:\Playwright-31_work\6\s\node_modules.pnpm\playwright@1.11.1\node_modules\playwright\lib\utils\stackTrace.js:50:19) at Connection.sendMessageToServer (C:\Playwright-31_work\6\s\node_modules.pnpm\playwright@1.11.1\node_modules\playwright\lib\client\connection.js:65:48) at Proxy.<anonymous> (C:\Playwright-31_work\6\s\node_modules.pnpm\playwright@1.11.1\node_modules\playwright\lib\client\channelOwner.js:64:61) at C:\Playwright-31_work\6\s\node_modules.pnpm\playwright@1.11.1\node_modules\playwright\lib\client\frame.js:102:65 at Frame._wrapApiCall (C:\Playwright-31_work\6\s\node_modules.pnpm\playwright@1.11.1\node_modules\playwright\lib\client\channelOwner.js:77:34) at Frame.goto (C:\Playwright-31_work\6\s\node_modules.pnpm\playwright@1.11.1\node_modules\playwright\lib\client\frame.js:100:21) at C:\Playwright-31_work\6\s\node_modules.pnpm\playwright@1.11.1\node_modules\playwright\lib\client\page.js:303:60 at Page._attributeToPage (C:\Playwright-31_work\6\s\node_modules.pnpm\playwright@1.11.1\node_modules\playwright\lib\client\page.js:238:20) at Page.goto (C:\Playwright-31_work\6\s\node_modules.pnpm\playwright@1.11.1\node_modules\playwright\lib\client\page.js:303:21) at navigateToUrl (C:\Playwright-31_work\6\s\src\integration-tests\utils\appUtils.ts:203:13) at Object.getAppInfo (C:\Playwright-31_work\6\s\src\integration-tests\utils\appUtils.ts:121:8) at Object.<anonymous> (C:\Playwright-31_work\6\s\src\features\multisession\integration-tests\consoleAppTitle.test.ts:34:35) at _callCircusHook (C:\Playwright-31_work\6\s\node_modules.pnpm\jest-circus@26.6.3\node_modules\jest-circus\build\run.js:175:5) at _runTest (C:\Playwright-31_work\6\s\node_modules.pnpm\jest-circus@26.6.3\node_modules\jest-circus\build\run.js:142:5) at _runTestsForDescribeBlock (C:\Playwright-31_work\6\s\node_modules.pnpm\jest-circus@26.6.3\node_modules\jest-circus\build\run.js:87:7) at _runTestsForDescribeBlock (C:\Playwright-31_work\6\s\node_modules.pnpm\jest-circus@26.6.3\node_modules\jest-circus\build\run.js:57:9) at run (C:\Playwright-31_work\6\s\node_modules.pnpm\jest-circus@26.6.3\node_modules\jest-circus\build\run.js:25:3) at runAndTransformResultsToJestFormat (C:\Playwright-31_work\6\s\node_modules.pnpm\jest-circus@26.6.3\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapterInit.js:176:21) at jestAdapter (C:\Playwright-31_work\6\s\node_modules.pnpm\jest-circus@26.6.3\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapter.js:109:19) at runTestInternal (C:\Playwright-31_work\6\s\node_modules.pnpm\jest-runner@26.6.3\node_modules\jest-runner\build\runTest.js:380:16) at runTest (C:\Playwright-31_work\6\s\node_modules.pnpm\jest-runner@26.6.3\node_modules\jest-runner\build\runTest.js:472:34)
 
**Code snippet:**
 
export async function navigateToUrl(page: Page, navigationUrl: string, waitToLoadDomContent = true): Promise<void> {
    // Navigate to the required URL.
    const loadState = isOnPremiseEnvironment ? LoadState.NetworkIdle : LoadState.Load;
    await page.goto(navigationUrl, { waitUntil: loadState, timeout: 0 });
 
    // Wait until dom-content is loaded successfully upto max 1 minute.
    if (waitToLoadDomContent) await waitForDomContentLoad(page);
}

I encountered this issue locally also, the site is not able to access after couple of runs.

**Comment by mxschmitt** [comment]
Hi, Playwright internally does not touch the DNS resolving. This happens on the operating system level, so it's likely that the virtual machine, buildbots or in your case Azure Pipelines has DNS issues (maybe temporarily), I would reach out to them to debug it further or try if possible set another DNS server.

**Comment by yury-s** [comment]
Closing per the last comment. This is a genuine error in the browsers when it tries to navigate to the page.
