### ISSUE TITLE
[Feature] Slack-Playwright Integration

### ISSUE THREAD

**Issue by smseese1** [microsoft/playwright#6778]
I would like to have something similar to the cypress slack integration https://docs.cypress.io/guides/dashboard/slack-integration#Install-the-Cypress-Slack-app. Where I can easily view things from the test case level and see screenshots where failures exist.

Thanks!

**Comment by pavelfeldman** [comment]
This would be resolved on the test runner level. So far we don't ship Playwright with the test runner, but we will.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
