### ISSUE TITLE
Problems with :nth-match(tr, n)

### ISSUE THREAD

**Issue by avietkfi** [microsoft/playwright#6780]
![image](https://user-images.githubusercontent.com/73585703/119900985-f6dd0900-bf4d-11eb-8d27-5ad60b608096.png)

I can't figure this out.

`playwright.$$('css=div.react-bootstrap-table > table > :nth-match(tbody, 1) > :nth-match(tr, 3)');`

matches the second tr in the table (see image 1), `:nth-match(tr,2)` the first. Sort of logical so far but following the same indexing `nth-match(tr, 4)` and `nth-match(tr, 5)` do not match the next two trs, why?

![image](https://user-images.githubusercontent.com/73585703/119901837-188ac000-bf4f-11eb-85de-5f503549b9d2.png)

playwright@1.11.0

**Comment by yury-s** [comment]
Can you attach sample html page where this selector fails?

**Comment by pavelfeldman** [comment]
We need answers to the question above in order to act on this request! Please file a bug with additional details and link this bug if this is still an issue!
