### ISSUE TITLE
[Question] Looking for the equivalent of Cyrpress.io '--no-exit' feature 

### ISSUE THREAD

**Issue by dman777** [microsoft/playwright#6790]
I am using mocha test runner (in continuous file watch mode) with playwright. 

Coming from cypress, cypress has a feature that I use alot when I write tests

![image](https://user-images.githubusercontent.com/887815/120048028-af9d5980-bfdb-11eb-9967-d8c3774177a8.png)

What this does is.... I have cypress running continuously and watching for file changes. When I modify a file and it changes, I have a single browser session that stays open and the test re-runs in the same browser. Cypress re-uses the same browser. 

With playwright, I try to have this same behavior. I thought I could remove browser.close() but then it just pops up many browsers for each file change. 

Is there a way to have playwright have the same behavior as cypress `--no-exit` feature?

**Comment by yury-s** [comment]
This depends on how much state Mocha reuses between tests launches in the the watch mode. Can you share the code where you configure Mocha to recycle the browser instance?

**Comment by dman777** [comment]
Suer, 

Here is my .mocharc.js 

```
const {
  chromium,
  firefox,
} = require('playwright');
const chai = require('chai');
chai.use(require('sinon-chai'));
const should = chai.should();


global.should = should;
global.chromium = chromium;
global.firefox = firefox;



module.exports = {
  ui: 'bdd',
  spec: ['test/stories/**/*spec*.js'],
  timeout: 9000000,
  require: ["./test/stories/init.js"],
}
```
In effort to try and get it to share the same browser instance, I tried using a mocha root hook to no success:

init.js

```javascript
exports.mochaHooks = {
  beforeAll: [
    async function() {
      const browser = await chromium.launch({headless: false, slowMo: 500 })
      const context = await browser.newContext();
      this.page = await context.newPage();
    }
  ]
};
```

And in the test, I access it:

```javascript
describe('List Forms Widget', function() {
  let browser;

  let page;

  beforeEach(async function() {
    page = this.page;

    await page.route('**/graphql', (route, request) => {
      const requestQuery = JSON.parse(request.postData()).query;

      const graphqlMock = mockGraphqlRoutes.find((el) => {
        if (el.query === requestQuery) {
          return el
         }
      })

      if (graphqlMock) {
        return route.fulfill({
          headers: {
            "access-control-allow-origin": "*",
          },
          status: 200,
          body: JSON.stringify(graphqlMock.body),
        });
      }

    });

    await page.addInitScript(params => {
      window.localStorage.setItem(params.name, params.value);
    }, {name: KEY_NAME, value: JWT_TOKEN});

    await page.goto('http://localhost:5000/foo');
  });
```

Please let me know if you need anything else or would like me to post a repo link with the test setup.

**Comment by pavelfeldman** [comment]
We don't have this functionality, so I'm converting this into a feature request to collect upvotes. I'm up-voting it myself!
