### ISSUE TITLE
After each click event, how to get the HTTP response content? For example, how to judge success after clicking login?[Question]

### ISSUE THREAD

**Issue by weujieytt** [microsoft/playwright#6797]
After each click event, how to get the HTTP response content? For example, how to judge success after clicking login?

**Comment by mxschmitt** [comment]
See [here](https://playwright.dev/docs/api/class-page#pagewaitforresponseurlorpredicate-options) and [here](https://playwright.dev/docs/api/class-response) how to interact with the Response object:

**Comment by weujieytt** [comment]
I didn't find this in Python

**Comment by pavelfeldman** [comment]
https://playwright.dev/python/docs/api/class-page?_highlight=expect_respo#pageexpect_responseurl_or_predicate-kwargs
