### ISSUE TITLE
[Question] Playwright POM model

### ISSUE THREAD

**Issue by lonely-caat** [microsoft/playwright#6799]
Hi! 
I want to implement POM in my tests using playwright. I am referring to the [POM example](https://playwright.dev/docs/pom/) in the docs. I am struggling with getting it done. My Idea is have a base page (after log in) and all other pages should inherit from it and start their adventure there.
```js
//base_page.js:
class BasePage {
    constructor(page) {
        this.page = page;
        this.context = page.context();
    }
    async logIn() {
        await this.page.goto('https://github.com/', {timeout:0});
        await this.page.click('[aria-label="Sign in"]');
        await this.page.fill('[placeholder="example@email.com"]', 'kate@tesc.com');
        await this.page.fill('[placeholder="Enter password"]', 'Password');
        await this.page.click('[aria-label="Sign in"]');
    }
}
module.exports = { BasePage };
```

and the test using the jest test runner:
```js
test.js
const { Dashboard } = require('../pages/authorization-page');

describe("tests for the new dash", () => {
  beforeAll(async(done) => {
    const page = await browser.newPage();
    const loginPage = LoginPage(page);
    await loginPage.logIn()
    await Dashboard.logIn()

  });
    it("should have the exact text 'Dashboard' in the h1", async () => {
      await expect(page).toEqualText("h1", "Dashboard")
    })
  });
```

also I am using 
```js
//jest-playwright.config.js
module.exports = {
  browsers: ["chromium", "firefox", "webkit"],
  exitOnPageError: false, // GitHub currently throws errors
  launchOptions: {
    headless: false
  }
}
```

but somehow the browser is always idle, goto does not seem to fire, and the test fails because of the timeout. Please advise - what am I doing wrong? The documentation for each feature is really good, but I am struggling to unite it all together:(

**Comment by pavelfeldman** [comment]
`LoginPage(page)` looks like a method call, not a constructor. I also don't see a definition of `LoginPage` in your snippet. Could it be a single JavaScript bug on your side?

**Comment by mxschmitt** [comment]
Closing since the issue seemed stale as part of the triage process. Please reopen if you have further questions.

**Comment by lonely-caat** [comment]
hi @mxschmitt , this is not really an issue with the framework - but a question. I'm not really sure how to answer @pavelfeldman 's message, I don't see what the issue is with the code that I supplied.  
Also I don't see a 'reopen' functionality :(

**Comment by mxschmitt** [comment]
Can you provide us the source code of `LoginPage`?  Also since you are using jest-playwright there is no need to create a new browser, context, or page since jest-playwright does it automatically for you as global variables.

**Comment by lonely-caat** [comment]
thanks for the advice!
This is what I use for the Login Page:
```
class SearchPage {
    constructor(page) {
        this.page = page;
        this.context = page.context();
    }
    async logIn() {
        await this.page.goto('https://my.website.com/', {timeout:0});
        await this.page.fill('[placeholder="example@email.com"]', 'testing@mailinator.com');
        await this.page.fill('[placeholder="Enter password"]', 'Password1');
        await this.page.click('[aria-label="Sign in"]');
    }
}
module.exports = { SearchPage };


//
const playwright = require('playwright')

class BasePage {
    constructor(page) {
        this.page = page;
        this.context = page.context();
    }
}

class LoginPage extends BasePage {
    async doLogin() {
        await this.page.goto('https://my.website.com, {timeout:0});
        await this.page.fill('[placeholder="example@email.com"]', 'testing@mailinator.com');
        await this.page.fill('[placeholder="Enter password"]', 'Password1');
        await this.page.click('[aria-label="Sign in"]');
    }
}

class Dashboard extends BasePage {}

async function logIn() {
    const browser = await playwright.chromium.launch();
    const context = await browser.newContext();
    const loginPage = new LoginPage(await context.newPage());
    await loginPage.doLogin();
    // Assuming that login page navigates to admin page after successful login.
    const adminPage = new AdminPage(loginPage.page);
    return adminPage
}

logIn()
```
My idea is to have a base page (after log in) to start all the next tests from there

**Comment by mxschmitt** [comment]
So this seems like you are not using jest or jest-playwright at all - which is totally fine. What kind of issues do you encounter now?

**Comment by lonely-caat** [comment]
that's tough, I was pretty sure I'm using playwright-jest for a test runner that you wrote in https://github.com/playwright-community/playwright-jest-examples :)
my problem is that when I run the tests with `npm run test` - all the browsers start up empty, and nothing happens. I don't know where to start debugging what the issue is.

**Comment by mxschmitt** [comment]
Got it. This is because you are starting the browsers yourself via e.g. plalywright.chromium.launch() which is by default using the headless browsers. When you are using jest-playwright, then you should rely on the global variables (browser, context, page) see [here](https://github.com/playwright-community/jest-playwright#globals) and then you can use the global `page` variable which is available in each test/it.

**Comment by lonely-caat** [comment]
sorry @mxschmitt that i didn't include it in the original post, I'm actually using the globals in the config file:
```
// jest-playwright.config.js
module.exports = {
  browsers: ["chromium", "firefox", "webkit"],
  exitOnPageError: false, // GitHub currently throws errors
  launchOptions: {
    headless: false
  }
}
```
unlike in headless mode the browsers do start as new applications, just that nothing happens in them

**Comment by lonely-caat** [comment]
```
 npm run test
> jest-playwright-example-basic@1.0.0 test playwright-jest-examples/basic
> jest

 RUNS   browser: chromium  tests/example.test.js
```
<img width="1281" alt="Screenshot 2021-06-07 at 17 03 00" src="https://user-images.githubusercontent.com/33058683/121030584-4921f380-c7b2-11eb-928f-b9652395dae9.png">

**Comment by mxschmitt** [comment]
Referring to your login function in it you launch a browser via playwright.chromium.launch.
Replace
```
    const browser = await playwright.chromium.launch();
    const context = await browser.newContext();
    const loginPage = new LoginPage(await context.newPage());
```

with 

```
    const loginPage = new LoginPage(page);
```

Then the correct browser window get's used. The browser, context and page instance created via jest-playwright. Keep in mind, that this page variable is only accessible in a test/it statement.

**Comment by mxschmitt** [comment]
Closing since this issue seems to be solved.
