### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hananmalka** [microsoft/playwright#6806]
**Context:**
- Playwright Version: 1.10
- Operating System: Linux
- Node.js version: 12.22
- Browser: Chromium
- Extra: [any specific details about your environment]

**Describe the bug**

According to the documentation, the method "fill", triggers an "input" event - which mean, set "value" attribute in the input element. 

We had a case in our application, where trying to set text in an input field **manually** throws an exception.
Setting the text manually didn't work (because of the exception) but the test did **pass** (apparently since it's just set the value "attribute") and didn't indicate for this critical bug. 

Other selenium test, did catch this issue. I believe since the set text functionality is different. 

I'm not sure it's a bug, but defiantly something worth to pay an attention.
Is there a method that setting the text in a different way?

**Comment by yury-s** [comment]
> Is there a method that setting the text in a different way?

Try [`page.type()`](https://playwright.dev/docs/api/class-page?_highlight=type%28#pagetypeselector-text-options), it will also send keyboard events (keydown, keyup etc), it may well be that the error is triggered by one of those (`page.fill` doesn't trigger them).

**Comment by pavelfeldman** [comment]
As per above, if you care about custom logic while typing, you should use `page.type`. I'll catch the bug!

**Comment by hananmalka** [comment]
> As per above, if you care about custom logic while typing, you should use `page.type`. I'll catch the bug!

Thanks @pavelfeldman @yury-s 
It's indeed solved the problem, but tests become significantly slow. (x2)
Didn't change any of the default values of options object parameter but still it's really slow.

Is there a method that sets input by triggering key events but faster?

**Comment by mxschmitt** [comment]
Are you using the slowmo mode?

**Comment by hananmalka** [comment]
Yes. I am. of 150 MS. 
Thanks for the update. I'll check it without it. 
We did use it since we found out that tests failed occasionally without it
