### ISSUE TITLE
[BUG] page.add_init_script does not work if main page spawns child with window.open

### ISSUE THREAD

**Issue by puniaze** [microsoft/playwright#6810]
**Context:**
- Playwright Version: 1.8.1 (latest)
- Operating System: Linux
- Node.js version: whatever is bundled in playwright
- Browser: Chromium

I have defined function in page script and it works fine for usual windows.
However, when I create new child window using window.open(), playwright fails to execute page script in child windows. 
Note: I have created context.on(page, myfunc) and when new pages created, it automatically sets page init script to all pages.

For reproducing, just use this code:

**bug_poc.py**

```python
import asyncio
from playwright.async_api import async_playwright
import sys

async def browserPageCreated(page):
	await page.add_init_script(path='helloworld/testing.js')
	

async def main():

	chrome_additional_args = [
                                    "--disable-web-security",
                                    "--no-sandbox",
                                    "--disable-setuid-sandbox",
                                    "--disable-xss-auditor",
                                    "--disable-prompt-on-repost",  
                                    "--disable-popup-blocking"
                                ]
	ignore_args = [
		'--disable-extensions'
	]

	async with async_playwright() as p:
		browser = await p.chromium.launch(headless=False, args=chrome_additional_args, chromium_sandbox=False, ignore_default_args=ignore_args)
		context = await browser.new_context(bypass_csp=True, ignore_https_errors=True, user_agent='Demo UA')

		context.set_default_timeout(0)

		context.on('page', browserPageCreated)

		page  = await context.new_page()

		await page.goto('http://localhost:8000/bug.html', wait_until="networkidle")


		#await context.close()

		while True:

			await asyncio.sleep(10)

asyncio.run(main())


```

**testing.js**
```javascript
window.HELLO='123';

function demo(){
    console.log("TESTING>>>")
}
```
**bug.html**

```html
<h1>HI</h1>
<script>
    window.open('/pox.html')
</script>
```

**RESULTS:**
_main page:_

![image](https://user-images.githubusercontent.com/7716515/120234663-1ed7af80-c261-11eb-80dd-fa67fe34b5e1.png)

_child page:_

![image](https://user-images.githubusercontent.com/7716515/120234595-049dd180-c261-11eb-9f06-d853464a6fd9.png)

**Comment by mxschmitt** [comment]
For this case `add_init_script` on the browser context level should work: https://playwright.dev/python/docs/api/class-browsercontext/#browser_contextadd_init_scriptkwargs

It does not work in your case, because the page is already loaded when the page event get's emitted and it gets only executed when you navigate to a new sites.

**Comment by puniaze** [comment]
@mxschmitt even if I create variable in `context.add_init_script `, it is lost in child page when it is opened via window.open.

**Comment by pavelfeldman** [comment]
Closing this as per above, please let us know if it did not work for you via opening a new bug and linking this one!
