### ISSUE TITLE
[BUG] Unable to clear text input field 

### ISSUE THREAD

**Issue by Amrkamel1** [microsoft/playwright#6814]
**Context:**
- Playwright Version: 1.11.0
- Operating System: ubuntu
- Node.js version: 14
- Browser: Chromium

**Code Snippet**
`        await page.fill(this.username, '')
`

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  // ...
})();
```

**Describe the bug**

Unable to clear text input

**Comment by mxschmitt** [comment]
What is the value of `this.username` in your scenario? Is the application which you are testing public so we can reproduce it?

**Comment by Amrkamel1** [comment]
> What is the value of `this.username` in your scenario? Is the application which you are testing public so we can reproduce it?

class Login{

    username = '#username'
    password = 'input[name="password"]';
    loginButton = '#submit_login_form';
    errorMsg = '#login_error';

    async loginWith(username, password) {
        const page =  await config.page()
        await page.fill(this.username, '')
        await page.type(this.username, username)
        await page.type(this.password, '')
        await page.type(this.password, password)
        await page.click(this.loginButton);
        return this;
    }
}

unfortunately its private

**Comment by Amrkamel1** [comment]
@mxschmitt  seems that fill and type are not working in the same way, try to clean and input using .type('') is not working, while using .fill('') is woking fine

**Comment by pavelfeldman** [comment]
`page.type('abc')` means type letters a, b, c. And `page.fill('abc')` means make sure that the input has a value 'abc'. They do work differently, that's why we have both. Does this match the behavior you are observing?

**Comment by Amrkamel1** [comment]
@pavelfeldman , okay gotcha.
thanks for the clarification, but I just wondering how then I can send an empty string since fill.('') will clear the input

**Comment by Amrkamel1** [comment]
im closing this one, to clear an input I have used  await page.fill(ele, '')
