### ISSUE TITLE
[Question] How to prevent test exit on page error ?

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#6821]
I see an option in jest-playwright runner to prevent test exit on page error.

**exitOnPageError <[boolean]>. Exits process on any page error. Defaults to true.**

https://github.com/playwright-community/jest-playwright

Is there any similar option in playwright to prevent test exit on page error?

While running e2e test i would like to continue the test run if an assertion failed.

**Comment by pavelfeldman** [comment]
This should be filed in the community effort jest-playwright. Note that we are launching our own e2e test runner in a few days that will solve this and many other existing test integration shortcomings.
