### ISSUE TITLE
page.waitForXPath is not a function

### ISSUE THREAD

**Issue by saurabhxkapoor** [microsoft/playwright#683]
Trying playwright on existing tests by removing puppeteer dependency and installing playwright. 
Found that `page.waitForXPath` is not recognized.

Error:

> TypeError: page.waitForXPath is not a function

Are we going to incorporate this function ? We depend heavily on xapths and would be helpful if this can be incorporated.

**Comment by pavelfeldman** [comment]
You can say `page.waitForSelector('xpath=foo')`. See working with selectors [section](https://github.com/microsoft/playwright/blob/master/docs/api.md#working-with-selectors).

**Comment by pavelfeldman** [comment]
Closing in favor of https://github.com/microsoft/playwright/issues/688
