### ISSUE TITLE
[Question] Scaling tests

### ISSUE THREAD

**Issue by gaborari** [microsoft/playwright#6843]
I haven't found official documentation about scaling - sorry if there is any.

I have a scenario when a typical e2e test takes about ~1min. As the test coverage grows, it could take quite amount of time to run the full test suite.
I run e2e tests within an Azure DevOps pipeline, and so the pipeline has limited amount of resources (memory and CPU) - so increasing the degree of parallelism within a single pipeline might slow down the test execution (as different threads are having less resources).

In the past I used TestCafe in similar cases, but at the end I had to migrate to Selenium because with Selenium Grid I could scale up the tests (decreasing the total execution time from 20 mins to 2-3 mins).

Is there a Selenium Grid like capability with Playwright - or having a connector to execute the tests within Selenium Grid?

Also could you recommend solutions for scaling (virtual machine, docker swarm, Kubernetes, etc.)?

**Comment by pavelfeldman** [comment]
Some pointers for you:
- https://aerokube.com/moon/, https://saucelabs.com/platform/automation-tools/playwright are commercial services. I think browserstack is working on one as well.
- You can re-purpose existing Selenium Grid to make Playwright run against existing browser array, that is if you are only interested in Chromium. You would use https://playwright.dev/docs/api/class-browsertype/#browsertypeconnectovercdpparams to connect to the running browser in the cloud

**Comment by gaborari** [comment]
@pavelfeldman Thank you!
Sorry I forgot to mention, mainly I was looking for an in-house solution (I cannot use SouceLabs, Moon, Browserstack as of now). The connectOverCDP seems promising, I'll check it with SeleniumGrid soon.

**Comment by mxschmitt** [comment]
Closing since it seems answered.
