### ISSUE TITLE
[Question] How to get screenshot for failed test ?

### ISSUE THREAD

**Issue by Amrkamel1** [microsoft/playwright#6844]

**Comment by pavelfeldman** [comment]
This would be a question to the testing framework. Depending on the one you use, they offer different ways of capturing screenshot on failure. We are about to release our own test runner where this capability is built in, so please stay tuned. If you prefer to use jest, you can use https://github.com/playwright-community/jest-playwright#usage-with-custom-testenvironment.

**Comment by Amrkamel1** [comment]
@pavelfeldman Great! and thanks for the reply, I'm using mocha but didn't find any way to get the screenshot upon failure. 
I will check the URL you have provided anyway.
