### ISSUE TITLE
[Feature] Language support for Go

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#6856]
It's about moving the Go language binding over to the Microsoft organization, see here: https://github.com/mxschmitt/playwright-go/issues/122

We are currently collecting feedback and upvotes.

**Comment by AngangGuo** [comment]
We're excited about the news that the playwright-go project can be moved under Microsoft organization. Hope it can get the go-ahead soon. 💯

**Comment by jeroendee** [comment]
Very excited to see this issue. Indeed hope to see Go being adopted as an official Playwright SDK language.

**Comment by KiqoCode** [comment]
+1

**Comment by extrasalt** [comment]
What does it take for the go binding to move into the microsoft repo and the microsoft release schedule..?

Is there a page with guidelines/requirements that the project needs to fulfil?

**Comment by utkarshpaliwal9** [comment]
Eagerly waiting for the transition to be completed. Any updates on the same yet?

**Comment by jeroendee** [comment]
I can imagine, this will not get adopted. MS and the Playwright team already need to dev/maintain 4 different client libraries. Adding a 5th one that needs to follow the normal release cycle, might be a bit too much. Also counting in, the possible niche group that want to use the Go bindings, the investments MS has to do, prob. won't yield a positive return.

**Comment by gedw99** [comment]
What about if the client is golang and compiled to wasm ?

then put use a little bit of js / typescript to interact with the wasm .

the wasm acts as a proxy. Just like how service worker is designed

**Comment by phorcys420** [comment]
would love to see this happen, +1

**Comment by k2glyph** [comment]
Excited. +1

**Comment by gedw99** [comment]
> I can imagine, this will not get adopted. MS and the Playwright team already need to dev/maintain 4 different client libraries. Adding a 5th one that needs to follow the normal release cycle, might be a bit too much. Also counting in, the possible niche group that want to use the Go bindings, the investments MS has to do, prob. won't yield a positive return.

I changed over to just using chromep and the many golang tools around it.
so far it gives better feature set.

**Comment by jeroendee** [comment]
> 



> > I can imagine, this will not get adopted. MS and the Playwright team already need to dev/maintain 4 different client libraries. Adding a 5th one that needs to follow the normal release cycle, might be a bit too much. Also counting in, the possible niche group that want to use the Go bindings, the investments MS has to do, prob. won't yield a positive return.
> 
> I changed over to just using chromep and the many golang tools around it. so far it gives better feature set.

I'll start exploring chromedp as well.
