### ISSUE TITLE
[Feature] Add native GitHub security and versioning dependency alerts

### ISSUE THREAD

**Issue by aleks-ivanov** [microsoft/playwright#6865]
- [Dependabot](https://dependabot.com/) alerts on updates for the project's dated and vulnerable dependencies and automatically creates PRs to easily update them

Pipeline Foundation is **a non-profit initiative** with the sole purpose of giving back to the IT community by assisting OSS projects with DevOps implementations and best practices.

Built with ❤ by [Pipeline Foundation](https://pipeline.foundation).

**Comment by pavelfeldman** [comment]
Could you give us a hint on the expected report / finding?

**Comment by aleks-ivanov** [comment]
Here is how it looks when Dependabot is active:

- list of dependency sources which Dependabot scans, with the logs of the scans

![1](https://user-images.githubusercontent.com/74899441/120770176-8eca8c00-c526-11eb-88a3-2337f6b1d157.png)

- PRs that Dependabot opens with security and version updates

![2](https://user-images.githubusercontent.com/74899441/120770285-a6a21000-c526-11eb-91f1-bf217f162848.png)

**Comment by aslushnikov** [comment]
So once again, what is this and why should we add it? Do we have a problem we're not aware of that this solves?

**Comment by aslushnikov** [comment]
Anyway, I'll close this for now - it's not clear why and how we should use it. I'm not convinced it solves much problems.
