### ISSUE TITLE
[Feature] Add native GitHub continuous code security and quality analysis

### ISSUE THREAD

**Issue by aleks-ivanov** [microsoft/playwright#6867]
- [CodeQL](https://github.com/github/codeql) is an open source code scanning tool for discovering vulnerabilities across a codebase

Pipeline Foundation is **a non-profit initiative** with the sole purpose of giving back to the IT community by assisting OSS projects with DevOps implementations and best practices.

Built with ❤ by [Pipeline Foundation](https://pipeline.foundation).

**Comment by pavelfeldman** [comment]
Thanks! It does not look like it found anything, so I am not sure it adds value. Could you suggest an example of an issue it reports?

**Comment by aleks-ivanov** [comment]
Hi @pavelfeldman 

as far as I understand, since the pipeline in the PR doesn't yet exist on in your repo, it is ran against our fork, so until you merge it you won't be able to see any results at **Security -> Code scanning alerts -> CodeQL**.

However, here is the result of the last scan on our side:

![erthh3455j](https://user-images.githubusercontent.com/74899441/120752144-d8f54280-c511-11eb-857a-ccca4f0b2c63.png)

Most importantly the pipeline runs on every push commit and pull request, so you will be able to catch code issue from any contribution quickly.

**Comment by aslushnikov** [comment]
In general, tooling is a good thing! However, most of the errors here aren't errors, so I'd refrain from adding this.

**Comment by snamilikonda** [comment]
Any plan to reintroduce this? Since additional concerns are flagged?
