### ISSUE TITLE
[BUG] $$eval does not evaluate the expected amounts of elements

### ISSUE THREAD

**Issue by verhovsky** [microsoft/playwright#6869]
**Context:**

- Playwright Version: tried both 1.9.2 and 1.11.1-1621490832000
- Operating System: Ubuntu 20.10
- Python Version: 3.9

**Code Snippet**

```python
import time
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()

    page.goto("https://www.littlegreene.com/wallpaper/collection/")

    # Neither of these are necessary, it's just in case.
    time.sleep(15)
    for elem in page.query_selector_all("div.categories-landing h3 a"):
        elem.scroll_into_view_if_needed()

    # print(len(page.eval_on_selector_all("div.categories-landing h3 a", "(l) => l.map(a => a.href)")))
    print(len(page.eval_on_selector_all("div.categories-landing h3 a", "(l) => l")))
    print(len(page.query_selector_all("div.categories-landing h3 a")))
```

**Describe the bug**

The output is 

```
0
7
```

when I would expect the first snippet to also return results. I can run the selector with the `map` in the Chrome devtools and running it through `page.evaluate`

```python
page.evaluate("$$('div.categories-landing h3 a').map(a => a.href)")
```
works as well. This is the first time I've encountered this issue.

Edit: it seems like selectors don't work through `eval_on_selector` or `eval_on_selector_all`, 

```python
    print(page.eval_on_selector("a", "l => l"))
    print(page.eval_on_selector("div", "l => l"))
```

return `None` and `{}` respectively.

**Comment by dgozman** [comment]
This site overrides `Array.from` method and does so incorrectly. For example,  `Array.from(new Set([1]))`results in `[]`.

I confirmed that if we do not use Array.from, this works as expected.
