### ISSUE TITLE
[BUG] Unable to catch pop up alert 

### ISSUE THREAD

**Issue by Amrkamel1** [microsoft/playwright#6873]
**Context:**
- Playwright Version: 1.11.1
- Operating System: ubuntu 20.04.2
- Node.js version: 14
- Browser: chromium

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```    async getAlertText() {
        const [popup] = await Promise.all([
            page.waitForEvent('popup'),
          ])
          await popup.waitForLoadState('domcontentloaded')
          console.log(await popup.title());
        // await page.on('dialog', async dialog => {
        //     console.log(dialog.message());
        //     await dialog.accept();
        //   });
          return this;
    }
```

**Describe the bug**

alert pop up is appearing for instance and dismissed right away, in the screenshot below it shows alert is dismissed while waiting for pop up alert is still pending
![image](https://user-images.githubusercontent.com/32042806/120676891-c8ec4d00-c496-11eb-8e0b-a78314d229b0.png)

**Comment by pavelfeldman** [comment]
So there is alert() call in the popup window and you'd like to handle it, but popup comes in too late?

**Comment by Amrkamel1** [comment]
@pavelfeldman actually when using firefox the pop up is not coming late, it appears in fracture of second and disappear again. on chrome it won't appear at all, however, the confirmation pop up is appearing normally and not disappearing when u do the same scenario manually

**Comment by dgozman** [comment]
@Amrkamel1 A few questions just to make sure we understand the issue correctly:
- Does `page.click('[name="sub"]')` open a new tab/window?
- Does that new tab show a confirmation dialog when you do this manually? How does that dialog look like?
- Do you want to confirm this dialog in your scenario?

**Comment by Amrkamel1** [comment]
@dgozman 
- page.click('[name="sub"]') is a submit button once you click on, it will trigger that alert window 

- yes when, I do this manually it appears normally as shown below 
![image](https://user-images.githubusercontent.com/32042806/121143305-34d70880-c83d-11eb-9caa-45c0f80d2773.png)

![Peek 2021-06-08 09-27](https://user-images.githubusercontent.com/32042806/121141948-ccd3f280-c83b-11eb-8834-cee2151c22f6.gif)

- Yes I want to confirm that the alert is appearing and get its text message, when I automate the scenario above the dialog appears for sp short instance that you hardly can notice and redirection to the main page is happening which I guess means that the playwright confirm the alert automatically

**Comment by ealap** [comment]
I think I am encountering the same issue. The confirm dialog always closes.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/15620712/121153440-a7b1a500-c878-11eb-9b4f-7d6a5c5d04ba.gif)


Note that I am using robotframework-browser, where I believe this is where they are handling dialogs.
```js
export async function handleAlert(request: Request.AlertAction, page: Page): Promise<Response.Empty> {
    const alertAction = request.getAlertaction() as 'accept' | 'dismiss';
    const promptInput = request.getPromptinput();
    const fn = async (dialog: Dialog) => {
        const dialogueText = dialog.message();
        if (promptInput) await dialog[alertAction](promptInput);
        else await dialog[alertAction]();
        logger.info(`Alert text: ${dialogueText}`);
    };
    page.on('dialog', fn);
    return emptyWithLog('Set event handler for next alert');
}

export async function waitForAlert(request: Request.AlertAction, page: Page): Promise<Response.String> {
    const alertAction = request.getAlertaction() as 'accept' | 'dismiss';
    const promptInput = request.getPromptinput();
    const dialogObject = await page.waitForEvent('dialog');
    const message = dialogObject.message();
    if (alertAction === 'accept' && promptInput) {
        dialogObject.accept(promptInput);
    } else if (alertAction === 'accept') {
        dialogObject.accept();
    } else {
        dialogObject.dismiss();
    }
    return stringResponse(message, 'Next alert was handeled succesfully.');
}
```

**Comment by dgozman** [comment]
Thank you for the answers! To recap, there is no "popup page", but a "popup alert box" in this scenario. Playwright automatically dismisses all alerts, unless there is a listener that handles it - that's why you either see it quickly flashing or do not see it at all.

Here is the snippet that should work for @Amrkamel1, see [documentation](https://playwright.dev/docs/dialogs) for more details. Let me know if this helps.

```js
page.once('dialog', dialog => {
  console.log(dialog.message());
  dialog.accept();
});

await page.click('[name="sub"]');
```

Alternatively, using Promises:
```js
// Wait for the dialog, and start clicking.
const dialogPromise = await page.waitForEvent('dialog');
const clickPromise = page.click('[name="sub"]');

// Click should open the dialog. Handle it.
const dialog = await dialogPromise;
console.log(dialog.message());
dialog.accept();

// Finish the click. Note that click does not finish until you close the dialog.
await clickPromise;
```

Note that click does not finish until you close the dialog. Read more in [documentation](https://playwright.dev/docs/api/class-dialog).

@ealap I think you observe the same issue that dialogs are dismissed automatically. Unfortunately, I cannot help with a snippet since I am not familiar with how robotframework-browser works.

**Comment by Amrkamel1** [comment]
@dgozman  thanks for sharing these snippets 
I have tried both of them but both are not working, page now is waiting for the pop up however the '[name="sub"]' button is not triggered as shown below 
![image](https://user-images.githubusercontent.com/32042806/121301237-2c8fd380-c8f8-11eb-9f8b-41109dc0f955.png)

I have tweaked it like below and it works 

`    async getAlertText() {
        await this.page.click('[name="sub"]');
        const dialogPromise = await this.page.waitForEvent('dialog');
        // const clickPromise =  await this.page.click('[name="sub"]');
        
        // Click should open the dialog. Handle it.
        const dialog = await dialogPromise;
        console.log(dialog.message());
        dialog.accept();
        
        // Finish the click. Note that click does not finish until you close the dialog.
        // await clickPromise;
        return this;
    }`

**Comment by dgozman** [comment]
@Amrkamel1 It's great that you have found a solution! I will close this issue then.
