### ISSUE TITLE
Can we get HAR data without file

### ISSUE THREAD

**Issue by danielbogatinov13** [microsoft/playwright#6885]
When I started to look into Playwright Sharp I really liked the record HAR functionality. I would really like to get most of the requests and responses, cookies and many other things(so record HAR is a great to use), but I would like to use the data for checks and filtering right away after closing the context. Is it possible that in near future we will get a object that contains the HAR data without saving it in a file, since many of us are discouraged to use as little space as possible, and also, I think it would greatly improve performances since when we need a file we will save it(or would be saved automatically) and when we don't we will just use the object to do our checks instead of reading the file and serialize/deserialize, and then delete it.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
