### ISSUE TITLE
Page.GetPdfAsync does not seem to respect PreferCSSPageSize option

### ISSUE THREAD

**Issue by lvmajor** [microsoft/playwright#6898]
When generating a pdf and passing the options, even when specifying `PreferCSSPageSize = false`, it seems like the generator does give precedence to the `@page` rule. 

To be honest on this one I think it might be more of an upstream issue as the code seems to only pass the option directly within the `args` and the default value of the option is `false`. I just wanted to let you know this is an issue that also affects Playwright-Sharp due to upstream dependency, I will try to confirm if I didn't only do a stupid mistake and if not, I will report on the Playwright repository and link the issue here.

Thanks again for your work, it's really appreciated!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
