### ISSUE TITLE
[BUG] Headless / Headed screenshots are different in Chromium

### ISSUE THREAD

**Issue by zeesaad** [microsoft/playwright#6899]
**Context:**
- Playwright Version: [Microsoft.Playwright 1.11.1-alpha-2]
- Operating System: [Windows 10 -x64]
- Node.js version: []
- Browser: [Chromium]
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

**Describe the bug**

the screenshot taken in headless mode is different from that in non-headless mode in size.

Add any other details about the problem here.

**Comment by mxschmitt** [comment]
Hi, is it possible that you could provide us a reproducible and/or the images? The width/height should not be different or what do you mean with size?

**Comment by pavelfeldman** [comment]
I'm triaging bugs and closing those not actionable. If this is still an issue, please open a new bug with details requested above and link this one!
