### ISSUE TITLE
[BUG] sec-ch-ua header is empty when using headless Chromium

### ISSUE THREAD

**Issue by gaborari** [microsoft/playwright#6900]
**Context:**
- Playwright Version: Playwright v1.11.1, PlaywrightSharp v0.192.0
- Operating System: Windows 10
- Node.js version: 12.18.4
- Browser: Chromium Headless
- Extra: -

**Code Snippet**
In javascript:
```javascript
beforeAll(async () => {
       browser = await playwright['chromium'].launch({ headless: true });
       page = await browser.newPage();

       if (!page) {
            throw new Error("Connection wasn't established");
       }

       // Open the page
       await page.goto(configObj.baseUrl + '/test', {
            waitUntil: 'networkidle0'
       });
});
```
In C#:
``` c#
using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Chromium.LaunchAsync();
var page = await browser.NewPageAsync();

await page.GoToAsync($"{config["BASE_URL"]}/test");


```

**Describe the bug**

When using headless Chromium, the `sec-ch-ua` header is empty on requests.

Headers when using headless Chromium:
```
header: sec-ch-ua
header: Referer xxx
header: sec-ch-ua-mobile ?0
header: User-Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/90.0.4
```

Headers when using non-headless Chromium:

```
header: sec-ch-ua " Not A;Brand";v="99", "Chromium";v="90"
header: Referer xxx
header: sec-ch-ua-mobile ?0
header: User-Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4421.0 Sa
```

This might cause a problem when there is a firewall that rejects requests containing empty headers - the header value should be filled, or empty header should not be added to requests.

I could workaround this problem with a following setting:
```
page = await browser.newPage({ userAgent: 'Chromium headless' });
```
or
```
var page = await browser.NewPageAsync(userAgent: "Chromium headless");
```

**Comment by mxschmitt** [comment]
This is not related to Playwright and already reported upstream: https://bugs.chromium.org/p/chromium/issues/detail?id=1212793

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
