### ISSUE TITLE
[Feature] Video recording with `pw:api` debug logs attached

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright#6904]
There are two great ways to check if a failure happened in CI. Since it might not always be reproducible easily locally, these two ways are indispensable:

1. Using the videos functionality to record the test cases, https://playwright.dev/docs/videos/
2. Using `DEBUG=pw:api` (or better yet, setup a logger when this is fixed https://github.com/microsoft/playwright/issues/5871)

When a failure happens, I want to look at the video to see what happens. But I also want to check the logs in some cases where I cannot see enough in the video.

**The idea**

It would be awesome if a time-synced overlay was added at the bottom of the video recording where the output from `pw:api` was seen. I realize this is a rather advanced feature request and I am fine with closing it.

**Comment by mxschmitt** [comment]
In the next release v1.12 a new tracing feature get's released, this should help you debugging failing tests locally or on the CI. It contains all the logs and snapshots etc, stay tuned!

**Comment by thernstig** [comment]
@mxschmitt that is all great of course, but does it actually cover the exact scenario described in this issue?

**Comment by dgozman** [comment]
> @mxschmitt that is all great of course, but does it actually cover the exact scenario described in this issue? I can hold off to check it out of course :)

@thernstig It will not cover the exact scenario that you have described. However, it is intended to be used for the same purpose of debugging failures happened on CI (or locally), so we definitely want to improve this area!

**Comment by thernstig** [comment]
@dgozman @mxschmitt I just saw the new release, and feel it might be a very competent solution to do what I asked. It seems to have screenshots instead of videos, but that might not be a bad thing in this case. Also maybe in the future  maybe you will even have video that can sync to timestamps in the logs etc to scroll back/forth. So closing this and will request that instead, if I find a need for it after having tested out the new Playwright Trace Viewer 👍
