### ISSUE TITLE
[Question] Is possible to forward log into different files

### ISSUE THREAD

**Issue by xuanzhaopeng** [microsoft/playwright#6905]
Hey team,

We have great logger, but however is it possible that I can forward logger output into different files for each test? so in this way It would be easier for debug when test failed in CI, especially when we have a lot of test case.

In webdriverio, the logger can be reinitialised before each test, so I can forward logger output into different files by test name, seems there is no way to do it in Playwright?

Cheers

**Comment by dgozman** [comment]
Hi @xuanzhaopeng, could you please provide some sample code so that we can help you? Specifically, are you talking about logger api, or `DEBUG=` logs or something else? Are you using a particular test runner?

**Comment by xuanzhaopeng** [comment]
Hey @dgozman , thanks very much for your help. 

In webdriver.io they have this logger: https://github.com/webdriverio/webdriverio/tree/main/packages/wdio-logger , it print similar code like `DEBUG=pw:api`

so I wanna have an ability to forward all `DEBUG=pw:api` outpu**t for each test case to different files**, so it will be easier to debug once we can attach the output into the Allure report. 

Maybe you have other ideas?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
