### ISSUE TITLE
[Question] Why fonts look different in firefox and webkit than in chrome?

### ISSUE THREAD

**Issue by apapkevich** [microsoft/playwright#6907]
Context:

- Playwright Version: v1.11.1
- Operating System: image: "mcr.microsoft.com/playwright:v1.11.1-bionic"
- Browser: Firefox, Webkit
- Extra: also reproduced in playwright:focal image

Chrome:
<img src="https://user-images.githubusercontent.com/57415806/120812340-9190a580-c555-11eb-8868-3eeb664fb18f.png" width="200">
Firefox:
<img src="https://user-images.githubusercontent.com/57415806/120813159-504cc580-c556-11eb-9ee8-5e8f52d5b0fc.png" width="200">
Webkit:
<img src="https://user-images.githubusercontent.com/57415806/120813568-acafe500-c556-11eb-9ddc-ae0c7d9c0a4e.png" width="200">

**Comment by dgozman** [comment]
@apapkevich That's because browsers resolve fonts differently. That's why you want cross-browser testing! I am not sure we can help here, unless you provide more details - what are you trying to do and what do you expect?

**Comment by apapkevich** [comment]
I expect that fonts in headless Firefox on Ubuntu will be like in headless Firefox on Windows, not monospaced.
Headless Firefox Windows 10: 

<img src="https://user-images.githubusercontent.com/57415806/121396480-161b6380-c95c-11eb-8d79-3a8ed4d8fbdc.png" width="200">

Headless Firefox mcr.microsoft.com/playwright:v1.11.1-bionic: 

<img src="https://user-images.githubusercontent.com/57415806/121396961-904be800-c95c-11eb-96e6-b1f022b6073e.png" width="200">

**Comment by aslushnikov** [comment]
> I expect that fonts in headless Firefox on Ubuntu will be like in headless Firefox on Windows

Unfortunately this is not true: font rendering is driven by operating system. Thus linux firefox is rendering fonts differently then windows firefox.

**Comment by apapkevich** [comment]
Yes, I think there are some fonts missing in the container.

Ubuntu 20.04, Firefox:

<img src="https://user-images.githubusercontent.com/57415806/121666623-22193980-cab2-11eb-8a50-7bbffb1f7ac1.png" width=300/>

font-family: -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Noto Sans',Oxygen,Ubuntu,'Droid Sans','Helvetica Neue',sans-serif;

**Comment by dgozman** [comment]
@aslushnikov Let's double check whether we need some font pack in the docker for Firefox.
