### ISSUE TITLE
Playwright : TypeError: Cannot read property 'snapshotPath' of null

### ISSUE THREAD

**Issue by Aishwarya-UR** [microsoft/playwright#6921]
Hello,

Trying to compare two images with [https://github.com/microsoft/playwright-test#visual-comparisons](url) But trying to use that throws below exception:

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'snapshotPath' of null
    at Object.toMatchSnapshot
```

```
const timeLog = await page.$$("canvas")
const actual = await timeLog[0].screenshot({path:'timelog-actual.png'})
expect(actual).toMatchSnapshot(`timelog.png`) //this line throws exception
```

Here - timelog.png is an image already present in solution.
Can someone please help here?

**Comment by mxschmitt** [comment]
Are you using `npm install @playwright/test@next` and `npm install playwright@next`? It works for me.

**Comment by mxschmitt** [comment]
Closed since the issue seemed stale. Please create a new issue if its reproducible with the new release.
