### ISSUE TITLE
how to access shared worker

### ISSUE THREAD

**Issue by larrypaul93** [microsoft/playwright#6924]
is there any way to access shared worker ?

**Comment by mxschmitt** [comment]
What kind of data do you want to access an what is the use-case of it?

**Comment by larrypaul93** [comment]
I want to run some js code in shared worker context. like to patch platform and useragent.

**Comment by mxschmitt** [comment]
Playwright is designed to be a testing library for reliable end-to-end testing. So this is not in the scope of it.
