### ISSUE TITLE
[Feature] add BrowserContext.loadStorageState()

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#6929]
**Question:**How set the context storageState in **test.use** during run time by passing parameter to storageState. 

My Application require authentication. I followed the steps provided here to configure authentication.
https://playwright.dev/docs/next/auth

**Environment:** 
"playwright": "^1.12.0-next-alpha-jun-5-2021"
"@playwright/test": "^1.12.0-next-alpha-jun-5-2021",
Language: JavaScript

**Here is the sample code for GitHub.**
```javascript

let storageState = null;

test("Save Cookie and Local Storage", async ({page, context}) => {
await page.goto('https://github.com/login');

await page.click('text=Login');
await page.fill('input[name="login"]', USERNAME);
await page.fill('input[name="password"]', PASSWORD);
await page.click('text=Submit');

const storage = await context.storageState();
process.env.STORAGE = JSON.stringify(storage);
storageState = JSON.parse(process.env.STORAGE);

});

test.describe("Load StorageState", () => {

    test.use({ storageState: storageState });

    test('Should not ask for credentials', async ({ page }) => {
        await page.goto('https://github.com');
        const url = page.url();
            expect(url).toMatch('https://github.com');
    });
});


```

**Working**
=======
1. Absolute path in **test.use** storageState works
    test.use({ storageState: '/tmp/storage.txt' });
2. Valid JSON string in **test.use** storageState works
    test.use({ storageState: `{"cookies":[],"origins":[]}'});
3. Creating new context by passing parameter works 
const context = await browser.newContext({ storageState });

**Not Working**
=========
4. Substituting the storageState value with parameter doesn't work in test.use
    test.use({ storageState: storageState });

I don't want to explicitly create new context using storageState in every test case as by default every test case will create a new context. If i do this, there will be always two contexts.

Instead i would like to override the test fixture context storage on demand by using **test.use** storageState by passing parameter during run time, this will help me in using the new context created by test case with loaded storageState. 

My application issue new token every 10 minutes, it will be huge overhead for me to keep writing the storage information in JSON file and read it during run time.

I am migrating from Protractor to Playwright.

Appreciate if you could provide me a solution to overcome this issue.

**Comment by dgozman** [comment]
Does a temporary file work for you?

```js
// Save it to the file
await context.storageState({ path: 'storage.json' });

// Load it from the file
test.use({ storageState: 'storage.json' });
```

**Comment by vsravuri** [comment]
Thanks for the solution. Playwright Test Runner is a great tool but i do see challenges using Playwright Test Runner with applications that require authentication and reissue tokens in short span.

1. Test Runner opens new context for every test case (it would have been nice if there is an option to open new context at spec file level as well)
2. localStorage saved during globalSetup phase can be used until the cookie expires, once the cookie expire, i need to re-authenticate and overwrite the storage.json file with new localStorage to use it in subsequent test cases
3. I have multiple applications which reissue tokens at 10 minutes and 15 minutes interval
4. It's hard to keep track of session expiry time in order to re-login to the application and capture new localStorge

With your proposed solution, apart from globalSetup, i need to add this line 
**await context.storageState({ path: 'storage.json' });**
at the end of every test case to capture latest localStorage state in case new token is issued , then pass this value to subsequent test case for session continuity.
test.use({ storageState: 'storage.json' });

**Comment by dgozman** [comment]
@vsravuri This seems like a complex scenario. I would suggest to authenticate in each test separately - this way you will not have any expiration issues and tests will be properly isolated from each other. Does that work for you?

**Comment by vsravuri** [comment]
@dgozman Thanks for the feedback. I will make adjustments to my test cases. You can close this issue.

**Comment by done3t** [comment]
> Does a temporary file work for you?
> 
> ```js
> // Save it to the file
> await context.storageState({ path: 'storage.json' });
> 
> // Load it from the file
> test.use({ storageState: 'storage.json' });
> ```
> 
> Also, you probably want to move your "Save Cookie and Local Storage" code to a `globalSetup` phase, to do it once before all the tests.

hello, I did want to set a "session" Cookie in a global place, so that I can login in before all the tests, does any suitable place to do that? 
I had been try to config contextOptions:{cookies: [cookieObject]}, but it seems to doesn't work.
