### ISSUE TITLE
[Feature] Support OpenFin app

### ISSUE THREAD

**Issue by hptabster** [microsoft/playwright#6936]
I'd like to be able run the Playwright automations in OpenFin. [OpenFin](https://www.openfin.co/container/runtime/) is built on Chromium and Electron. Is this possible today, or is further support required in Playwright?

**Comment by dgozman** [comment]
Playwright does not have anything special for OpenFin, but it works with Electron out of the box. See here for more details: https://playwright.dev/docs/next/api/class-electron. Does that help with OpenFin?

**Comment by hptabster** [comment]
The OpenFin application I am using is experienced like a session in Chrome, where the application opens in OpenFin with a URL, not from a JS file. I'll look into this a bit more, but the relevant information I've seen is how to automate using Puppeteer: https://github.com/testable/openfin-puppeteer-testable-example/blob/master/test.js

I was trying to figure out how OpenFin could be launched and create a "browser" object. The rest of my test code user browser, context and page objects.

**Comment by dgozman** [comment]
You can use [`BrowserType.connectOverCDP`](https://playwright.dev/docs/next/api/class-browsertype#browser-type-connect-over-cdp) and just follow the example above with Playwright:

```js
async function connect() {
  return await playwright.chromium.connect({ endpointURL: `http://localhost:${RemoteDebuggingPort}` });
}
```

**Comment by nedwardsOF** [comment]
> The OpenFin application I am using is experienced like a session in Chrome, where the application opens in OpenFin with a URL, not from a JS file. I'll look into this a bit more, but the relevant information I've seen is how to automate using Puppeteer: https://github.com/testable/openfin-puppeteer-testable-example/blob/master/test.js
> 
> I was trying to figure out how OpenFin could be launched and create a "browser" object. The rest of my test code uses browser, context and page objects.

We're you able to adapt Testable's Puppeteer example to work with Playwright? I have a thread going in the Playwright Slack about using connectOverCDP, but haven't given it a shot yet.

**Comment by hptabster** [comment]
This is the code I use to launch OpenFin instead of Chromium:
```
const { exec } = require("child_process");
const { expect } = require("chai");
const { chromium } = require("playwright");

const globals = require("./test_globals");
const utils = require("./utils");

const IS_WINDOWS = process.platform === "win32";
const OPENFIN = process.env.TEST_OPENFIN === "true" && IS_WINDOWS;
const OPENFIN_CONFIG_URL =
  process.env.TEST_OPENFIN_CONFIG_URL ||
  "https://beta.edgefx.pro/api/fin-manifest";
const REMOTE_DEBUGGING_PORT = 12565;
const OPENFIN_DIR = `${process.env.LOCALAPPDATA}\\OpenFin`;
const OPENFIN_EXE = "OpenFinRVM.exe";

const LOGIN_SELECTOR = "#root > .main-login";
const USER_SELECTOR = 'span[class="user-name"]';

async function launchChrome() {
  if (OPENFIN) {
    return await launchOpenFin();
  }
  const browser = await chromium.launch({
    headless: globals.HEADLESS,
    args: ["--mute-audio"],
  });
  const context = await browser.newContext({
    acceptDownloads: true,
    permissions: ["clipboard-read"],
  });
  const page = await context.newPage();
  return [browser, context, page];
}

async function launchOpenFin() {
  const openFinArgs = `--config=${OPENFIN_CONFIG_URL} --runtime-arguments="--remote-debugging-port=${REMOTE_DEBUGGING_PORT}"`;
  utils.debug(`launchOpenFin: ${OPENFIN_EXE} ${openFinArgs}`);
  exec(`${OPENFIN_EXE} ${openFinArgs}`, { cwd: OPENFIN_DIR });
  const startTime = Date.now();
  let browser;
  while (Date.now() - startTime < 5000) {
    try {
      browser = await chromium.connectOverCDP({
        endpointURL: `http://localhost:${REMOTE_DEBUGGING_PORT}`,
      });
      break;
    } catch (err) {
      continue;
    }
  }
  utils.debug(
    `launchOpenFin: contexts=${JSON.stringify(await browser.contexts())}`
  );
  const context = await browser.contexts()[0];
  await context.grantPermissions(["clipboard-read"]);
  utils.debug(`launchOpenFin: pages=${JSON.stringify(await context.pages())}`);
  const page = await context.pages()[0];
  return [browser, context, page];
}

async function browserClose(browser, page) {
  if (OPENFIN) {
    return await page.evaluate(() => {
      fin.desktop.System.exit(); //  eslint-disable-line
    });
  }
  return await browser.close();
}

```

**Comment by Eshaanee** [comment]
@hptabster could you please share test_globals(line 4) and utils files(line 5). It will be great help.

**Comment by hptabster** [comment]
[test_globals.js.log](https://github.com/microsoft/playwright/files/7565002/test_globals.js.log)
[utils.js.log](https://github.com/microsoft/playwright/files/7565005/utils.js.log)

**Comment by SabFloki** [comment]
Thanks for looping here @mxschmitt .
Hi @hptabster  : 
exe file built on openfin - I have the .exe which has to be launched via playwright , access menus that will land on chrome browser on separate window.

Do I still need to run the debugging port as above or directly can I launch the exe file via 'executablePath' as launchOptions in playwright?

Kindly suggest.

**Comment by hptabster** [comment]
I launch OpenFin the same way Chrome and use the CDP (Chrome Developer Port).

Here's a code snippet:
```
const OPENFIN = process.env.TEST_OPENFIN === "true" && IS_WINDOWS;
const OPENFIN_CONFIG_URL =
  process.env.TEST_OPENFIN_CONFIG_URL ||
  "https://uat.edgefx.pro/api/fin-manifest";
const REMOTE_DEBUGGING_PORT = 12565;
const OPENFIN_DIR = path.join(process.env.LOCALAPPDATA || "", "OpenFin");
const OPENFIN_EXE = path.join(OPENFIN_DIR, "OpenFinRVM.exe");
let OPENFIN_PROC;
....
async function launchOpenFin(opts = {}) {
  const width = opts.width || WIDTH;
  const height = opts.height || HEIGHT;
  const openFinArgs = [
    `--config=${OPENFIN_CONFIG_URL}`,
    `--runtime-arguments=--remote-debugging-port=${REMOTE_DEBUGGING_PORT}`,
    `--working-dir=${OPENFIN_DIR}`,
  ];
  utils.debug(`launchOpenFin: ${OPENFIN_EXE} ${openFinArgs}`);
  OPENFIN_PROC = spawn(OPENFIN_EXE, openFinArgs, {
    stdio: ["pipe", "ignore", "pipe"],
    detached: false,
  });
  const browser = await connectCDP();
  utils.debug(
    `launchOpenFin: contexts=${JSON.stringify(await browser.contexts())}`
  );
  const context = await browser.contexts()[0];
  if (TEST_TRACE) {
    await context.tracing.start({ screenshots: true, snapshots: true });
  }
  await context.grantPermissions(["clipboard-read"]);
  utils.debug(`launchOpenFin: pages=${JSON.stringify(await context.pages())}`);
  const page = await context.pages()[0];
  await utils.sleep(1000);
  await page.evaluate(
    async ([width, height]) => {
      await (await fin.Window.getCurrent()).resizeTo(width, height);
    },
    [width, height]
  );
  return [browser, context];
}

**Comment by SabFloki** [comment]
Could you please share utils and env file for reference?

**Comment by hptabster** [comment]
There is no ENV file, it uses command line environment variables, i.e.,  TEST_OPENFIN=true mocha testfile.js. The only thing used from utils is debug:

```
const DEBUG = process.env.TEST_DEBUG === "true";
function debug(message) {
  if (DEBUG && message) {
    console.log(`${new Date().toISOString()} ${message}`);
  }
}
```

**Comment by SabFloki** [comment]
Can you please let me know - whats being called below ? 

`const browser = await connectCDP();`

**Comment by hptabster** [comment]
async function connectCDP(port = REMOTE_DEBUGGING_PORT, timeout = 5000) {
  let browser;

  return (await utils.timer(
    async () => {
      try {
        browser = await chromium.connectOverCDP({
          endpointURL: `http://localhost:${port}`,
        });
        return true;
      } catch (err) {} // eslint-disable-line no-empty
      return false;
    },
    { timeout: timeout, message: `connectCDP: ${port} timed out` }
  ))
    ? browser
    : null;
}

**Comment by SabFloki** [comment]
For some reason, 
endpointURL (ws://xxx.com/amps/json )- throws **browsertype.connectOverCDP: Websocket error - connect ETIMEDOUT**

Still trying with (wss://xxx.com/amps/json ) - throws **browsertype.connectOverCDP: Websocket error : self signed in certificate chain**

Because of this error, next step to get browser.contexts() fails as it cannot read the properties of undefined 'contexts'

Question:
1.If endPointURL is down, is the above first error expected?
2. Is there a way to solve Self-Signed in certificate chain

--------- Meanwhile to find alternate way ----- 
Found few docs , where electron.launch can be used to launch app and get firstWindow easily without connecting to CDP.

Hence I tried the set up with electron.launch() instead of spawn. App gets launched but electron.launch doesn't come out of the process and throws timeout error. Can you please help on this if you are aware?
I could see in Playwright docs -

Ensure that nodeCliInspect ([FuseV1Options.EnableNodeCliInspectArguments](https://www.electronjs.org/docs/latest/tutorial/fuses#nodecliinspect)) fuse is not set to false?

Can you please tell how to set and solve this?

**Comment by mandeep-singh-lab49** [comment]
@hptabster what is REMOTE_DEBUGGING_PORT and how could i find it ?

**Comment by harisjasar** [comment]
> @hptabster what is REMOTE_DEBUGGING_PORT and how could i find it ?

In the manifest file of OpenFin app, there should be this line specified:
"devtools_port": 9090

By default, it's usually port 9090

**Comment by hptabster** [comment]
const REMOTE_DEBUGGING_PORT = 12565;

**Comment by pthomasius** [comment]
> This is the code I use to launch OpenFin instead of Chromium:
> 
> ```
> const { exec } = require("child_process");
> const { expect } = require("chai");
> const { chromium } = require("playwright");
> 
> const globals = require("./test_globals");
> const utils = require("./utils");
> 
> const IS_WINDOWS = process.platform === "win32";
> const OPENFIN = process.env.TEST_OPENFIN === "true" && IS_WINDOWS;
> const OPENFIN_CONFIG_URL =
>   process.env.TEST_OPENFIN_CONFIG_URL ||
>   "https://beta.edgefx.pro/api/fin-manifest";
> const REMOTE_DEBUGGING_PORT = 12565;
> const OPENFIN_DIR = `${process.env.LOCALAPPDATA}\\OpenFin`;
> const OPENFIN_EXE = "OpenFinRVM.exe";
> 
> const LOGIN_SELECTOR = "#root > .main-login";
> const USER_SELECTOR = 'span[class="user-name"]';
> 
> async function launchChrome() {
>   if (OPENFIN) {
>     return await launchOpenFin();
>   }
>   const browser = await chromium.launch({
>     headless: globals.HEADLESS,
>     args: ["--mute-audio"],
>   });
>   const context = await browser.newContext({
>     acceptDownloads: true,
>     permissions: ["clipboard-read"],
>   });
>   const page = await context.newPage();
>   return [browser, context, page];
> }
> 
> async function launchOpenFin() {
>   const openFinArgs = `--config=${OPENFIN_CONFIG_URL} --runtime-arguments="--remote-debugging-port=${REMOTE_DEBUGGING_PORT}"`;
>   utils.debug(`launchOpenFin: ${OPENFIN_EXE} ${openFinArgs}`);
>   exec(`${OPENFIN_EXE} ${openFinArgs}`, { cwd: OPENFIN_DIR });
>   const startTime = Date.now();
>   let browser;
>   while (Date.now() - startTime < 5000) {
>     try {
>       browser = await chromium.connectOverCDP({
>         endpointURL: `http://localhost:${REMOTE_DEBUGGING_PORT}`,
>       });
>       break;
>     } catch (err) {
>       continue;
>     }
>   }
>   utils.debug(
>     `launchOpenFin: contexts=${JSON.stringify(await browser.contexts())}`
>   );
>   const context = await browser.contexts()[0];
>   await context.grantPermissions(["clipboard-read"]);
>   utils.debug(`launchOpenFin: pages=${JSON.stringify(await context.pages())}`);
>   const page = await context.pages()[0];
>   return [browser, context, page];
> }
> 
> async function browserClose(browser, page) {
>   if (OPENFIN) {
>     return await page.evaluate(() => {
>       fin.desktop.System.exit(); //  eslint-disable-line
>     });
>   }
>   return await browser.close();
> }
> ```

How do you call this in your playwright config or tests?
