### ISSUE TITLE
[Feature] Define default browser context timeout via configuration

### ISSUE THREAD

**Issue by AmitAber** [microsoft/playwright#6940]
When creating a new `BrowserContext` via `Browser.newContext(...)` it would be useful to provide a value for the default timeout in the newly created browser context. Having this option would make controlling this timeout via simple configuration in higher-level wrappers such as `jest-playwright` where currently the default Playwright timeout causes failing tests to time-out at the jest test level instead of the playwright selector / matcher ([link](https://github.com/playwright-community/jest-playwright#error-reporting-with-jest)).

**Comment by dgozman** [comment]
Can `jest-playwright` just call [`BrowserContext.setDefaultTimeout`](https://playwright.dev/docs/next/api/class-browsercontext#browser-context-set-default-timeout) manually?

```js
// Options object, with a default timeout.
const myContextOptions = { defaultTimeout: 120000, ignoreHTTPSErrors: true };

// Create context, and set the default timeout.
const context = await browser.newContext(myContextOptions);
context.setDefaultTimeout(myContextOptions.defaultTimeout);
```

**Comment by mxschmitt** [comment]
Jest-playwright maintainer here. 

Yes, calling `context.setDefaultTimeout(123)` in a beforeAll should work. The `context` variable is globally defined.

**Comment by AmitAber** [comment]
While solving this in the test suite itself is possible in beforeAll, it's repetitive and is already a known pitfall.

My point is that jest-playwright supports passing in a BrowserContext configuration object (`contextOptions` [here](https://github.com/playwright-community/jest-playwright#options)) but it can't be utilized to configure the timeout.  Adding this option will make the timeout issue easier to resolve in a single place while also providing the means to utilize this in other automation contexts (e.g. @playwright/test).

**Comment by aslushnikov** [comment]
Ok, so I merged this first and then reverted the patch since these options now conflict with our bright test runner future. We might land it later - we'll discuss on the meeting later, but not rn.

@AmitAber I'd recommend to land the timeout configuration line to the jest-playwright for now. Should be easier!

**Comment by AmitAber** [comment]
I think it would be quite awkward to add this as a configuration to jest-playwright since it won't belong in `contextOptions` (that's meant to be a pass-through field directly to `newContext`) and having another field to configure the context would be incoherent (@mxschmitt please keep me honest here).

@aslushnikov care to explain what conflict this creates or would create so that I can think of a non-conflicting approach?

**Comment by pavelfeldman** [comment]
Looks like a request for jest-playwright, closing!
