### ISSUE TITLE
[Feature]Allow skipping actionability checks when using page.selectOption

### ISSUE THREAD

**Issue by qwpnqjucz** [microsoft/playwright#6945]
Similar to how page.click allows skipping actionability checks with `setForce`, it would be nice if we could do the same when using page.selectOption.

**Comment by jonathanpmartins** [comment]
Yep, this would be very nice. How can I accomplish something like this today, without the feature implementation?

**Comment by pavelfeldman** [comment]
you can pass { force } into selectOption now.
