### ISSUE TITLE
[BUG] ffmpeg can't get used when before downloaded with different architecture

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#6946]
**Context:**
- Playwright Version: ToT
- Operating System: Windows
- Node.js version: 14

**Steps to reproduce**

1. Use Playwright for Python on x64 Windows which will use the x64 driver and download ffmpeg x64
2. Use Node.js x32. Run `npx playrwight install` and use the recordVideo functionality in Chromium. This requires ffmpeg 
3. Then Node.js reports: "Hey please install ffmpeg"
4. I run `npx playwright install ffmpeg` - nothing happens

Expected: It does download the x32 executable which is in this scenario required for Node.js
Actual: It does not download anything because the folder is there.

**Comment by aslushnikov** [comment]
We're dropping win32 altogether, so this will become irrelevant!
