### ISSUE TITLE
[Question] elementHandle is returning null ?

### ISSUE THREAD

**Issue by Amrkamel1** [microsoft/playwright#6956]
I'm not sure if this is a bug or I'm missing something, I'm trying to assert that an element is existing using expect chai expression 

     genricEl(value) { return `//td[text()="${value}"]` }
    
     async expectListOfElementsToBeExisting(elementArray) {
        var list = elementArray;
        var element;
        for (element of list) {
            const ele = await this.page.$(this.genricEl(element))
            expect(ele).to.exist;
        }
        return this;
    }

------------------- in the test
```
    it('01. Should be able to add new project', async () => {
        const p = new Dashboard(await baseSetup.page());
        await p.navigateToAddProject()
        await p.fillProjectDetailsFields(D.projectNumber, D.qouteId, D.projectName, D.type)
        await p.clickOnSaveButton()
        await p.expectListOfElementsToBeExisting(['helo', 'something','test'])
    })
```
`

     AssertionError: expected null to exist

**Comment by mxschmitt** [comment]
`$` does not wait that the element is actually on the page. Using `page.waitForSelector("text=foobar")` will help there. Then there is also no need to assert manually that the element is truthy. So looping over your array of selectors using `page.waitForSelector()` should work in that case.

**Comment by Amrkamel1** [comment]
@mxschmitt
aha great! thank you
