### ISSUE TITLE
[Question] How to pass parameters through command line to Playwright Test Runner ?

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#6962]
I would like to pass few parameters through command line while running Playwright Test Runner, access the parameters in test cases.

e.g
Base URL
Test User Login
Test User Password
Environment Prefix

How can i do this in Playwright ?

In Protractor i use something like this, looking for something similar to this in Playwright Test Runner
--params='{ "baseURL" : "https://playwright.dev/"}

**Comment by JoelEinbinder** [comment]
The current simplest way to  do this is via environment variables:

```
MAGIC_URL=https://playwright.dev/ npx playwright test
```

```js
await page.goto(process.env.MAGIC_URL);
```

**Comment by vsravuri** [comment]
Thanks, that answer my question.
