### ISSUE TITLE
Can I set useragent like puppeteer?

### ISSUE THREAD

**Issue by trustyoo86** [microsoft/playwright#697]
I found this plugin while developing E2E server using puppeteer, So I considering replace it with this plugin.

But, I can't find `page.setUserAgent` function like puppeteer. My company use app using webview, So we add to the flag in useragent to identify it is an app.

So, Can I set useragent or add useragent use page object? If I can not add useragent, Are there any plans to add an useragent?

**Comment by aslushnikov** [comment]
Playwright's cornerstone is a "browser context" - all the setup goes through it. You can create a new browser context with a given user agent - and all pages inside of it will inherit it:

```js
const {webkit} = require('playwright');
(async () => {
  const browser = await webkit.launch();
  // Create a new incognito browser context with a proper user agent
  const context = await browser.newContext({
    userAgent: 'my-user-agent'
  });
  // Now the page will have the user agent 
  const page = await context.newPage('https://example.com');
  console.log(await page.evaluate(() => navigator.userAgent));
})();
```

Check out [docs](https://github.com/microsoft/playwright/blob/master/docs/api.md#browsernewcontextoptions)  for all the info.

**Comment by trustyoo86** [comment]
Thx for my question. It helped a lot 👍

**Comment by yury-s** [comment]
It works just fine for me:
```js
  const context = await browser.newContext({userAgent: 'foo'});
  const p = await context.newPage();
  await p.goto('https://example.com');
  console.log(await p.evaluate('navigator.userAgent'));
  await p.goto('https://bing.com');
  console.log(await p.evaluate('navigator.userAgent'));
```
Please open a new issue with failing code snippet if it fails for you.

**Comment by buckthebug** [comment]
Thanks for your response. I've described it here: https://github.com/microsoft/playwright/issues/5935
It's likely an edge case but if someone struggles like me, they can find a workaround there.

**Comment by AlexMarchini** [comment]
> Playwright's cornerstone is a "browser context" - all the setup goes through it. You can create a new browser context with a given user agent - and all pages inside of it will inherit it:
> 
> ```js
> const {webkit} = require('playwright');
> (async () => {
>   const browser = await webkit.launch();
>   // Create a new incognito browser context with a proper user agent
>   const context = await browser.newContext({
>     userAgent: 'my-user-agent'
>   });
>   // Now the page will have the user agent 
>   const page = await context.newPage('https://example.com');
>   console.log(await page.evaluate(() => navigator.userAgent));
> })();
> ```
> 
> Check out [docs](https://github.com/microsoft/playwright/blob/master/docs/api.md#browsernewcontextoptions) for all the info.

Is there a way to do this, but still inherit the global config settings in the new context? I noticed that by calling `newContext()` with a parameter, I'm losing the context options set in playwright.config.js. I want to just override the userAgent in the new context and preserve everything else.
