### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by maxwell8888** [microsoft/playwright#6972]
**Context:**
- Playwright Version: 1.11.1
- Operating System: Mac Big Sur
- Node.js version: 16.2
- Browser: Chromium

**Code Snippet**
Typescript
```ts
import { chromium } from "playwright";
(async () => {
  const browser = await chromium.launch({ viewport: null });
})();
```
**Describe the bug**
In above snippet the `viewport: null` option creates the following error:
```
Argument of type '{ viewport: null; }' is not assignable to parameter of type 'LaunchOptions'.
  Object literal may only specify known properties, and 'viewport' does not exist in type 'LaunchOptions'.
```

**Comment by mxschmitt** [comment]
viewport is a property which you can pass to newContext: https://playwright.dev/docs/next/api/class-browser#browser-new-context

Not for BrowserType.launch.
