### ISSUE TITLE
[Question] How to set the path of test output directory 'test-results' folder in playwright.config.js file ?

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#6979]
As per documentation, screenshots, videos and trace logs are saved in 'test-results' folder.
https://playwright.dev/docs/test-configuration

I would like to set the path of test output directory 'test-results' folder in playwright.config.js file 

I didn't find any option in the documentation to set the path.

**Comment by pavelfeldman** [comment]
That would be `outputDir` inside your project.

**Comment by pavelfeldman** [comment]
```ts
const config: PlaywrightTestConfig = {
  projects: [
    {
      name: 'myproject',
      outputDir: 'test-output',
      ....
    },
```

**Comment by vsravuri** [comment]
Thank you @pavelfeldman
