### ISSUE TITLE
[Question]How can I call set_input_files on elements with input set display: none

### ISSUE THREAD

**Issue by SansLang** [microsoft/playwright#6983]
If I call set_input_files directly on this element, it will be prompted that the element cannot be found

**Comment by SansLang** [comment]
For example：
       html_content:<input id="pdf" type="file" style="display: none;">
       playwright code：page.set_input_files("#pdf", root_path + '/test.pdf')

 it will be prompted that #pdf element object cannot be found

**Comment by mxschmitt** [comment]
Is your application public or is it possible that you can create a small reproducible for us?

I tested it with `display: none` which works for me.

```
it.only('should work', async ({page, asset}) => {
  await page.setContent(`<input id="pdf" type=file style="display: none">`);
  await page.setInputFiles('#pdf', asset('file-to-upload.txt'));
  expect(await page.$eval('#pdf', input => input.files.length)).toBe(1);
  expect(await page.$eval('#pdf', input => input.files[0].name)).toBe('file-to-upload.txt');
});
```

Also what is the exact error message?

**Comment by SansLang** [comment]
As shown in the picture is an upload component
![html](https://user-images.githubusercontent.com/20985179/121451570-6af8c180-c9d0-11eb-87cb-baa402ee9049.png)
In fact, upload is triggered by div button click instead of input.How do I call set_input_file in this case

**Comment by SansLang** [comment]
Oh, I found a solution, through page.expect_file_chooser after click upload  button
