### ISSUE TITLE
[Question] Is there a feature to set cookies in browser storage ?

### ISSUE THREAD

**Issue by Amrkamel1** [microsoft/playwright#6986]
I was wondering if there is any feature that allows setting cookies in the browser session, so user can avoid the login step

**Comment by mxschmitt** [comment]
You can leverage the storageState functionality of Playwright, see here: https://playwright.dev/docs/auth

**Comment by Amrkamel1** [comment]
@mxschmitt  thanks for the reply, but i didn't mean to reuse an existing cookies from the previous session.
I have a scenario where I don't have a login page, so I'm getting the required cookies from API  so the key is PHPSESSID with value X which I'm getting in before hook, so can I inject this key and value in the storage

**Comment by mxschmitt** [comment]
Then you can use [BrowserContext.addCookies](https://playwright.dev/docs/api/class-browsercontext#browser-context-add-cookies) which should fit for that use-case.

**Comment by Amrkamel1** [comment]
@mxschmitt  whats is browserContext, how i can define it?

**Comment by mxschmitt** [comment]
See here what a browser context is: https://playwright.dev/docs/core-concepts#browser-contexts

**Comment by Amrkamel1** [comment]
@mxschmitt  awesome!  it works now thank you
