### ISSUE TITLE
[BUG] beforeAll hook cannot depend on a test fixture "page"

### ISSUE THREAD

**Issue by dwalleck** [microsoft/playwright#6989]
**Context:**
- Playwright Version: 1.12.0
- Operating System: Ubuntu 20.04 via WSL
- Node.js version: 16.3.0
- Browser: All

## System:
 - OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
 - Memory: 12.69 GB / 24.84 GB
 - Container: Yes
## Binaries:
 - Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
 - Yarn: 1.22.10 - /mnt/c/Users/DarylWalleck/AppData/Roaming/npm/yarn
 - npm: 7.15.1 - ~/.nvm/versions/node/v16.3.0/bin/npm
## Languages:
 - Bash: 5.0.17 - /usr/bin/bash

**Code Snippet**

```typescript
import { test, expect } from '@playwright/test';
import dotenv from 'dotenv';
dotenv.config();

test.describe("When a superadmin user logs in with valid credentials", () => {
    test.beforeAll(async ({ page }) => {
        await page.goto(`${process.env.APP_URL}static/ng/index.html#/pages/signin`);
        await page.fill('[placeholder="Username or Email"]', process.env.SUPERADMIN_USERNAME);
        await page.fill('[placeholder="Password"]', "demo");
        await Promise.all([
            page.waitForNavigation(),
            page.click('button:has-text("Log In")')
        ]);
    });

    test("should display the main org dashboard", async ({ page }) => {
        expect(await page.isEnabled('#content > div > section > div:nth-child(2)')).toBeTruthy();
    });
});
```

**Describe the bug**

I had previously been using Playwright with Jest and wanted to port some of my tests over to Playwright's new runner. However, it seems like the new fixtures system does not allow `page` to be injected as a test fixture to `beforeAll`. It is allowed for `beforeEach` which is a workaround for a small scenario like the one shown above, but would be a blocker for other more complex test I have. Was the decision to not allow `page` to be used as a test fixture for `beforeAll` intentional?

**Comment by dwalleck** [comment]
As I dig into this it seems intentional (`browser` is instead exposed at the `beforeAll` stage), but I'll let someone confirm that.

**Comment by pavelfeldman** [comment]
In @playwright/test, each test has its own page, so you should do beforeEach. If you'd like to reuse auth state for your context, refer to https://playwright.dev/docs/auth#reuse-authentication-state. I'll be updating this doc to make a recommendation in terms of @playwright/test for your convenience.

**Comment by pavelfeldman** [comment]
Added the docs! https://playwright.dev/docs/auth#reuse-authentication-in-playwright-test
