### ISSUE TITLE
stuck at reify:caniuse-lite: timing reifyNode:node_modules/playwright Completed in 1298ms

### ISSUE THREAD

**Issue by Amrkamel1** [microsoft/playwright#6990]
**Context:**
- Playwright Version: 1.12.0
- Operating System: linux
- Node.js version: 14
- Browser: Chromium

**Code Snippet**

npm i -D playwright

**Describe the bug**
installing playwright stuck at the following 
![image](https://user-images.githubusercontent.com/32042806/121397002-3b0bd880-c954-11eb-8ff5-08f79cd01d96.png)

**Comment by mxschmitt** [comment]
Is it reproducible for you? Seems more like a network issue or temporary outage on NPM side. We run npm install probably over 100 times per day on the bots and never experienced problems.

**Comment by Amrkamel1** [comment]
Its happening with me quite often, for playwright particularly. But i didnt try again since i report this bug, but i will try one more time and let you know.

**Comment by mxschmitt** [comment]
Closed for now since the issue is not related to Playwright. Its probably a network issue or temporary outage on NPM or your side.

**Comment by towfiqi** [comment]
Same here. Only happening with playwright..

**Comment by svlieri** [comment]
Update npm/node to latest

**Comment by yaogengzhu** [comment]
You can use NVM to manage node versions. Try upgrading to a later version
```bash
nvm ls 
````
