### ISSUE TITLE
[BUG] PW does not pierce shadow root

### ISSUE THREAD

**Issue by tymfear** [microsoft/playwright#6998]
**Context:**
- Playwright Version: 1.12.0
- Operating System: Mac
- Node.js version: 14.3.0
- Browser:  Chromium
- Extra: AVA test runner

So code snippet is like `page.innerText('#accountSettingsModal #language div')`

<img width="778" alt="Screenshot 2021-06-09 at 22 22 28" src="https://user-images.githubusercontent.com/6705391/121417439-90ef7900-c972-11eb-968b-9b9499bbec2a.png">

Getting error
```
  TimeoutError {
    message: `page.innerText: Timeout 30000ms exceeded.␊
    =========================== logs ===========================␊
      retrieving innerText from "#accountSettingsModal #language div"␊
    ============================================================␊
    Note: use DEBUG=pw:api environment variable to capture Playwright logs.`,
  }

```

**Comment by aslushnikov** [comment]
user-agent shadow dom is a closed root shadow DOM that we don't pierce. These browser internals are likely to change with browser updates, so relying on their structure in tests might backfire.

This one in particular is internal to `<select>` element. Depending on what you want to do with it, you can do either:
- get `<select>` value:
  ```js
  const value = await page.$eval('#accountSettingsModal #language', el => el.value)
  ```
- get all options: [...$0.options].map(a => a.text)
  ```js
  const options = await page.$eval('#accountSettingsModal #language', el => [...el.options].map(option => option.text))
  ```

**Comment by tymfear** [comment]
Thanks, @aslushnikov ! Was doing exactly that, just thought that it's a workaround, not as designed.
Do you mind if I oper PR with docs update on Shadow Dom piercing feature?
