### ISSUE TITLE
[Feature] Enable inspector in "auto-play" mode

### ISSUE THREAD

**Issue by Tallyb** [microsoft/playwright#7008]
Allow running tests without the inspector waiting to start. i.e. the inspect is shown but there is no need to click the play button.
This is useful when we debug the test via the IDE and breaking points are defined in the code. 
It is also beneficial when there are tests across multiple pages.

**Comment by Tallyb** [comment]
Our tests are pretty long, so we combine both pausing on the IDE and pausing on the inspector as needed.

**Comment by june07** [comment]
Was also trying to figure out how to do this as well.  This issue makes it clear that "auto-play" is currently not built in.  Is there an API for the inspector and/or someway to connect to it the same way you can connect to the node.js inspector via the DevTools protocol?

**Comment by cjsheets** [comment]
@june07, @Tallyb, not sure if you're still looking for a solution, but we're able to bypass pausing-by-default by running:

>   await page.evaluate(() => {
    window._playwrightResume();
  });

**Comment by june07** [comment]
No, but thanks for the tip... might help in the future.  Funny it's such a simple solution!

**Comment by DetachHead** [comment]
> 
> 
> @june07, @Tallyb, not sure if you're still looking for a solution, but we're able to bypass pausing-by-default by running:
> 
> > await page.evaluate(() => {
> > window._playwrightResume();
> > });

unfortunately this workaround doesn't seem to work when using playwright with python. it just pauses on that `page.evaluate` call instead

**Comment by DetachHead** [comment]
as of playwright 1.23.0:
```js
await context.addInitScript(() =>window.__pw_resume())
await use(context)
```

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
