### ISSUE TITLE
Mapping table of Playwright version and Browser build versions? 

### ISSUE THREAD

**Issue by simonmeggle** [microsoft/playwright#7009]
Hi, 

I need to write a web test which has to use a specific version of Firefox. 
As far as I understand, there is a hard binding between Playwright versions and browser build versions. 
[browser.json](https://github.com/microsoft/playwright/blob/master/browsers.json) describes the browser build version for a single Playwright version - but is there any table where I could see **which Playwright version ships Firefox version x.y**? 
Thanks, Simon

**Comment by mxschmitt** [comment]
See in the [releases tab](https://github.com/microsoft/playwright/releases) which version is associated with which exact browser version. In general its not recommend to use outdated Playwright versions.

**Comment by simonmeggle** [comment]
OK, I see. Thanks. 

     In general its not recommend to use outdated Playwright versions.

I agree in general. But the SUT has to be tested exactly with the browser version it was developed against, this is a requirement. That is the only reason I am bound to an older Playwright version. 

On the other hand: what could be the impact of using the system's (old) Firefox with a recent playwright version by changing the browser executable path? Are there known incompatibilities or is it rather also just "not recommended" (i would give it a try)?

**Comment by mxschmitt** [comment]
Its not possible to use a custom Firefox or WebKit, since Playwright has custom builds which allow us to automate the browsers. Only Chromium based browsers can be easily switched out.

**Comment by simonmeggle** [comment]
Ok, thanks again, Max!
