### ISSUE TITLE
[BUG] Trace view errors

### ISSUE THREAD

**Issue by ludeknovy** [microsoft/playwright#7012]
**Context:**
- Playwright Version: 1.12.1
- Operating System: macOS
- Node.js version: 14

**Describe the bug**

`npx playwright show-trace trace.zip ` does not load the trace view page correctly. Actually it throws a couple of errors in the console - see attached screenshot.

![Snímek obrazovky 2021-06-10 v 11 29 27](https://user-images.githubusercontent.com/13610612/121501098-30e2ec00-c9df-11eb-8ba9-69d6ddfc5b91.png)

I used it like this:
```
await context.tracing.start({ screenshots: true, snapshots: true })
.. test code
await context.tracing.stop({ path: 'trace.zip' })
```

**Comment by mxschmitt** [comment]
Would it be possible to provide us a full reproducible with the web-site which you navigating to?

**Comment by ludeknovy** [comment]
@mxschmitt thanks for quick reply! Unfortunately I cannot share it. But I could try it with different site, maybe? Btw I use `jest-playwright`, not sure if it changes anything for you.

**Comment by aslushnikov** [comment]
@ludeknovy anything that will help us reproduce it locally would work!

**Comment by ludeknovy** [comment]
I found the root of this issue - setting `viewport` to `null` cause this issue. When I remove it from `contextOptions` it works correctly.  Example of `jest-playwright.config.js`: 
```
module.exports = {
  browsers: ["chromium"],
  launchOptions: {
    headless: true
  },
  contextOptions: {
    viewport: null,
  }
}
```

**Comment by mxschmitt** [comment]
I was able to reproduce, thanks!

minimal reproducible:

```js
// @ts-check
const playwright = require('.');

(async () => {
    const browser = await playwright.chromium.launch();
    const context = await browser.newContext({viewport: null});
    await context.tracing.start({
      name: "foo",
      snapshots: true,
      screenshots: true,
    })
    const page = await context.newPage();
    await page.goto('http://whatsmyuseragent.org/');
    await page.screenshot({ path: `example.png` });
    await context.tracing.stop({path: "foo.zip"})
    await browser.close();
})();
```
