### ISSUE TITLE
[Question] Playwright Runner + es6 syntax tests

### ISSUE THREAD

**Issue by trinode** [microsoft/playwright#7013]
We've a rather large app that takes advantage of es6 syntax.

we use a babel config, and I added a .babelrc

I've been able to get jest-playwright to run just fine with a plain jest command, but I'd like to take advantage of the playwright runner, how do I get it to do the necessary transpiling on running tests?

Currently I do 
`npx playwright test`

and get greeted with:
```
SyntaxError: Error while reading <test filename>:
Cannot use import statement outside a module
```

I'm presuming it's a relatively simple fix but I can't find reference to it anywhere.

Thanks

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/7121

**Comment by surfmuggle** [comment]
In my case i got the same error after doing the following in windows 10

> 1. Run `npm init playwright@latest` this start a wizard with some options and creates config files `package.json` and  `package-lock.json` and around 400 other files
> 2. You  may need to update the browsers that playwright wants to use; run `npx playwright install` to update the browsers. The browsers are located at `%userprofile%\AppData\Local\ms-playwright\`. 
> 3. Start recording with `npx playwright codegen --save-storage=./auth.json <your-url>`
> 4. Copy the code from the `Playwright inspector` into a new file my.test.js inside the project you created in step 1

The first line in the `Playwright inspector`  is this `import { test, expect } from '@playwright/test';`. But in case you configured your project to use javascript you have to change this line to `const { test, expect } = require('@playwright/test');`

After you made this change you can start the tests with `npx playwright test`
