### ISSUE TITLE
[BUG] Firefox: strange undefined toJSON property on JS objects

### ISSUE THREAD

**Issue by creage** [microsoft/playwright#7015]
**Context:**
- Playwright Version: 1.12.1
- Operating System: Windows
- Node.js version: 14.6.1
- Browser: Firefox

**Describe the bug**
After evaluating some custom code in the context of the **page**, some of JS objects receive strange `toJSON` property, which is `undefined`. Started to happen after upgrade to 1.12. And this happens on Firefox ONLY.

**Comment by mxschmitt** [comment]
Probably related to #6767

**Comment by creage** [comment]
Oh gosh, this reminds me [old issues](https://en.wikipedia.org/wiki/Prototype_JavaScript_Framework#Problems) you guys might not even heard about 😄 

That library taught all of us one thing - you should never modify objects you don't own.

**Comment by mxschmitt** [comment]
This was the original reason why we implemented this fix (prototype.js) to bypass a broken `Array.prototype.toJSON` method. Well... this lead to a broken `Array.prototype.toJSON` method for all users. Should get fixed soon.
