### ISSUE TITLE
[Question] Custom Selector Logs in Inspector

### ISSUE THREAD

**Issue by RichiCoder1** [microsoft/playwright#7022]
Would it be/is it possible to add custom "actions" to the inspector view? We have a step that runs during tests that takes a second, and I'd like to visualize it in the inspector so it doesn't look like "nothing" is happening.

**Comment by pavelfeldman** [comment]
So you'd like to add custom annotations to the log? Something like console.time/timeEnd that ends up on the timeline? Would that only be in the inspector or in the [trace viewer](https://playwright.dev/docs/trace-viewer) too?

**Comment by RichiCoder1** [comment]
That's a good question! Essentially, yes. TIL about `console.time`. I'd expect both, but primarily for Inspector where it may be a bit more mystifying what's happening.

**Comment by PfrLisBerndt** [comment]
That would be definitly a useful feature.
During the test we send commands to other devices that influence our apps behavior.
For this purpose, would it be furthermore possible to implement a function like "page.customAction" and a corresponding hook in the reporter,  "onCustomActionBegin"?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
