### ISSUE TITLE
[BUG] video isn't recorded when set "recordVideo" option in "contextOptions" of jest-playwright.config.js

### ISSUE THREAD

**Issue by Yurii397** [microsoft/playwright#7023]
**Context:**
- Playwright Version: [1.12.0]
- Operating System: [Mac]
- Node.js version: [v16.2.0]
- Browser: [e.g. All]

**Code Snippet**
This is my `jest-playwright.config.js` config file

```
module.exports = {
    preset: 'jest-playwright-preset',
    testMatch: [
        '<rootDir>/ui-tests/**/*.spec.ts'
    ],
    browsers: [process.env.BROWSER || 'chromium'],
    devices: ['iPad Pro 11'],
    launchOptions: {
        headless: process.env.BROWSER_MODE || true,
        devtools: process.env.BROWSER_DEVTOOL || false,
        slowMo:50
    },
    exitOnPageError: true,
    contextOptions: {
        recordVideo: {
            dir: './videos',
            size: { width: 640, height: 480 },
        }
    },
    setupFilesAfterEnv: ['<rootDir>/ui-tests/utils/setup.ts']
}
```

The folder with the video doesn't appear. When I do the same through the jest hooks using  browser.newContext() it works fine. 

```javascript
 browser.newContext({
        recordVideo: {
            dir: "./video",
            size: {width: iPadPro.viewport.width, height: iPadPro.viewport.height}
        // },
    });
```

What is the difference? Did I miss something? Looks did the same as described here - https://playwright.tech/blog/record-your-browser-tests-with-playwright

**Comment by mxschmitt** [comment]
Hi, this seems like an issue with jest-playwright. Please open an issue in [their repository](https://github.com/playwright-community/jest-playwright) or use the [new Playwright test-runner](https://playwright.dev/docs/test-intro)
