### ISSUE TITLE
don't download all of the browsers

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright#7024]
We should have a good story using playwright-core to not download any browsers on install, but get them just-in-time when the user wants to run tests in them.

This isn't trivial because it also has to work on CI, where people expect all of their dependencies to install on `npm install`, and then they cache their node modules folder and send it to a computer with no network access. But maybe we can make this the edge case solved via environment flags?

**Comment by pavelfeldman** [comment]
test runner no longer downloads the browsers: https://playwright.dev/docs/next/test-intro
