### ISSUE TITLE
nice browser debugging experience

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright#7025]
- [ ] javascript source maps in vscode
- [ ] javascript breakpoints in vscode
- [ ] pause test timeouts when paused
- [ ] open browser devtools on start so that my javascript `debugger;` and breakpoints work.
- [ ] see mouse cursor
- [ ] see keyboard
- [ ] see failed input attempts
- [ ] `--debug` to open in headful mode, pause on the start of the test somehow, enable all debugging features.

**Comment by pavelfeldman** [comment]
This is going to get a fresh start, rebooting this request.

**Comment by mrmckeb** [comment]
@pavelfeldman Is there a ticket we can subscribe to for updates and to follow along? :)
