### ISSUE TITLE
[Feature] Investigate in fixture support for mocking responses

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#7027]
Expose a fixture like that:

```js
    await registerRoute({
      method: 'GET',
      url: '**/v1/flow*',
      response: 'fixture:mockFooBar.json',
      status: 200,
      delay: 2 * 1000,
    })
```

which adds the specific route/fulfill to the context. Its possible to specify:
- an object -> JSON.stringify()
- a string -> use it
- a string which starts with `fixture:` to it, which will read it from a specific given folder.

This simplifies and eases up the handling when testing a fully mocked web application.

**Comment by pavelfeldman** [comment]
Closing due to lack of stars.
