### ISSUE TITLE
[Feature] Predictable sorting of test files, useful with --workers=1

### ISSUE THREAD

**Issue by anoushkadoctor** [microsoft/playwright#7028]
I have about 13 test suites (.spec.ts) files and i want to run all 13 files in a specific order each time. Only after one test suite has ended, should a new one begin. Is there a way to achieve this?

All of my test suites have the following structure:
```
import {expect, it, describe} from './fixtures'
describe("something", ()=>{
        it("test1", async({page, data})=>{
        });
        .
        .
        .
        //other it blocks...
});
```

**Comment by dgozman** [comment]
`@playwright/test` v1.12 should run tests in predictable order with `--workers=1` - it sorts files alphabetically.
