### ISSUE TITLE
Feature Request: Rails System Tests w/ playwright-test

### ISSUE THREAD

**Issue by tommyh** [microsoft/playwright#7032]
Background: I'm looking to use playwright (playwright-test w/ node API) for our e2e feature/system tests for a Ruby on Rails application.  Traditionally this is done via capybara/selenium, but I'd love to use playwright for these tests.

Question: Is an integration between playwright-test and Rails on the roadmap?

Rails has a pretty tight integration with Capybara/Selenium.  The closest project I could see to this feature request is [`cypress-rails`](https://github.com/testdouble/cypress-rails) and [`cypress-on-rails`](https://github.com/shakacode/cypress-on-rails).   It covers things like:
*  the connection between the cypress cli run and the test server rails spins up for that test run
* a "hook" to create setup/teardown data in rails/activerecord via your cypress-js tests.

I'm assuming the answer is no, but thought I'd toss it out there.  :)

Note: I'm not actually asking for a `playwright-ruby` client (ala `playwright-python`) where the actual tests are written in ruby.  While this would be very cool, I'd be 100% happy writing the tests in js (because this is where most community examples/mindshare/etc is anyway).  This feature request is more about the integration between playwright-test and rails.

**Comment by pavelfeldman** [comment]
> I'm assuming the answer is no, but thought I'd toss it out there. :)

We'll expose capabilities and apis necessary to do this, but someone would need to use them to wire to rails.

**Comment by tommyh** [comment]
Hey @pavelfeldman, thank you for the response and sorry for the slow reply.  Do you know what shape the capabilities/apis you'd expose would look like?  Any ideas on timing?

More context: We're evaluating playwright right now (my spike has gone extremely well) and I'm trying to figure out the scope of pulling it into our Rails app.

Thank you for all of your hard work, playwright has been amazing to use - the ability to create multiple contexts so that I can have 1 test which goes "end to end" between 2 types of users is a game-changer.  :)

**Comment by dgozman** [comment]
@tommyh Perhaps you know what APIs are needed? Basically, we do not have insights into the Rails ecosystem, so any help pointing what exactly is required would be great! Otherwise, it will take a lot of time to first research the area 😄

**Comment by tommyh** [comment]
@dgozman - of course!  I'll get back to you with some thoughts.  :)

**Comment by YusukeIwaki** [comment]
@tommyh Hi, I'm really interested in this issue. Thank you for proposing curious idea.

I think `capybara-playwright-driver` (not official) library would cover most use cases of Rails System-testing while playwright test runner works awesomely.

> I'd be 100% happy writing the tests in js

I understand this motivation however most Rails users already use RSpec or MiniTest as a test runner. So I think it would be better to provide a concrete use-case within Rails application where playwright test runner works better than RSpec or MiniTest. 
(ex: Handling flaky testcases with `--retries=x`, parallel testing with a single test runner, or another)

**Comment by tommyh** [comment]
@dgozman - I did some digging into what would be needed from the playwright team if the rails community wanted to create something like [cypress-on-rails](https://github.com/shakacode/cypress-on-rails) and I *think* the answer is nothing.  :). I read your [advanced config docs for workerInfo](https://playwright.dev/docs/test-advanced/#workerinfo-object) about how playwright can start the application server (parallel workers, retries, etc) and that seems to be enough for a bridge library to connect playwright with rails.

@YusukeIwaki - thank you so much for pointing that out.  your driver didn't come up in my searches, so very interested to learn more about it.  I'll definitely give it a spin and see which features (mainly from the playwright test runner) would be missed: video retain-on-failure, retries, parallel brower modes, playwright inspector/debugger/explore?

`I'd be 100% happy writing the tests in js` - yes, if playwright had an official ruby client (similar to python), that'd be amazing for 2 reasons: 1) it'd work within rspec and 2) you can put `FactoryBot.create` calls at the top of the spec.  While those reasons are nice, a connection between playwright and rails is essential.

So it sounds like there are 2 potential strategies for that connection: [capybara-playwright-driver](https://github.com/YusukeIwaki/capybara-playwright-driver) which plugs playwright into capybara, or something like [cypress-on-rails](https://github.com/shakacode/cypress-on-rails) which ignores capybara and plugs playwright test runner into rails.

**Comment by pavelfeldman** [comment]
It seems like there is nothing Playwright team can act on in the scope of this bug, so closing it.

**Comment by justin808** [comment]
https://github.com/shakacode/cypress-on-rails supports Playwright!

**Comment by searls** [comment]
Late to the party, but today I wrote a guide on using [capybara-playwright-driver to replace Selenium for Rails System Tests](https://justin.searls.co/posts/running-rails-system-tests-with-playwright-instead-of-selenium/) for anyone interested
