### ISSUE TITLE
Feature request: it instead of test

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright#7033]
We have multiple test suites written as `it('dances in the night')` where one can read it as a sentence.

Changing it to use `test()` instead means we would have to change all our test case names.

Could `it()` be considered an alternative? To let users chose themselves.

**Comment by JoelEinbinder** [comment]
We currently export the `test` object as the default. So you can actually just do
```ts
import it from "@playwright/test";
```

**Comment by thernstig** [comment]
Usually though users import more things e.g. `expect` and named exports have some benefits. But I agree that is a solution in case you absolutely do not want to alias `it` to `test` internally.

**Comment by mxschmitt** [comment]
Closing since as written above you can do one of both:

```
import it, { expect } from "@playwright/test";
import { test as it, expect } from "@playwright/test";
```
