### ISSUE TITLE
Importing JS files that use ES modules syntax

### ISSUE THREAD

**Issue by zakkor** [microsoft/playwright#7037]
```
// src/file.js
export function foo() {}
```

```
// test/file.spec.ts
import { foo } from '../src/file.js';
```

Running folio on the above setup yields the following error:
```
Error while reading .../test/file.spec.ts:
Unexpected token 'export'
```
Using commonjs syntax makes folio work, but changing our codebase to make folio work is not a great solution.
Is there any way to make folio work with ESM syntax?

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/7121
