### ISSUE TITLE
[Feature] Add GitHub Action failed test annotation for failed tests

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#7038]
Example: 
![image](https://user-images.githubusercontent.com/17984549/117486113-830c9980-af69-11eb-9adb-13bd7998adff.png)

Implementation: https://github.com/cschleiden/jest-github-actions-reporter/blob/master/src/index.ts#L29-L36
Some other implementation: https://github.com/mattallty/jest-github-action/blob/12c8c9a48ae4543fdcf5faa4d126e922d69783a8/src/action.ts#L188-L205
Jest does it somehow also internally automatically afaik.

Documentation: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-status-checks#checks

Edit: Seems also possible without the GitHub SDK: https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-error-message

**Comment by pavelfeldman** [comment]
No external requests -> archiving.

**Comment by mxschmitt** [comment]
Linking https://github.com/microsoft/playwright/issues/9147
