### ISSUE TITLE
browserApp.wsEndpoint() returns null

### ISSUE THREAD

**Issue by malcolm-kee** [microsoft/playwright#704]
As [documented](https://github.com/microsoft/playwright/blob/master/docs/api.md#browserappwsendpoint), `browserApp.wsEndpoint()` should returns a string, but it does not when I call it.

Note: I understand the documentation indicates that the value may not be available, but it doesn't state how to make it available. So this requires a bugfix or an update on docs to clarify the behavior.

Reproduction repo: https://github.com/malcolm-kee/playwright-wsendpoints-bug

**Comment by pavelfeldman** [comment]
Thanks for the heads up!

`const browserApp = await playwright[browserType].launchBrowserApp({ webSocket: true });`

will make it work. updating the docs...

**Comment by pavelfeldman** [comment]
Done!

**Comment by malcolm-kee** [comment]
@pavelfeldman thanks for the prompt fix. Awesome 👍
