### ISSUE TITLE
[Feature] Extend tsconfig and babel configuration

### ISSUE THREAD

**Issue by btvanhooser** [microsoft/playwright#7041]
I'm using @playwright/test with typescript in a project that already uses typescript, so I've made a 2nd tsconfig. I was previously using Jest which has ts-jest to handle the TS related configurations. Is there anything in the Playwright Test Runner where I can set that as well, or would I need to use ts-node or something of the like to be able to set a path other than the default "./tsconfig.json"?

**Comment by pavelfeldman** [comment]
Playwright should respect your tsconfig, could you provide more details on what your expectations are and what happens instead?

**Comment by btvanhooser** [comment]
So in my project, I have a tsconfig.json and a tsconfig.e2e.json because I need different configurations for the e2e sub project, but when running playwright test runner it's unclear how to set the config path to point to the e2e config. I tried diving through the PlaywrightTestOptions class/interface and the CLI options and it wasn't clear how to set that. 

I'm trying to migrate from the jest-playwright-preset pattern and there you can set the path via the jest config. I'm just trying to see if the same can be be done with this runner.

**Comment by mxschmitt** [comment]
The playwright test-runner does so far not use your own tsconfig or babel configuration. I will keep it open and mark it as a feature-request so we can add support for it.

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/7121
