### ISSUE TITLE
[Feature] Support .tsx files in @playwright/test

### ISSUE THREAD

**Issue by mattjennings** [microsoft/playwright#7042]
Importing a .tsx file in a test or configuration file causes the test runner to fail with a `Cannot find module` error.

```ts
import { test, expect } from "@playwright/test";
import { Something } from "./types"; // types.tsx

test("basic test", async ({ page }) => {
  const something: Something = "123";

  ...
});

```

It would be nice to either support these extensions out of the box, or add some way to configure which extensions the test runner will compile.

My use-case is I have a codegen utility that spits out both React components and types into the same file, and I'm looking to import one of those types into my test.

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/7121
