### ISSUE TITLE
[Feature] Retry on Specific Failure

### ISSUE THREAD

**Issue by RichiCoder1** [microsoft/playwright#7043]
Very often with our tests, they are flaky in a _very specific_ way. Would it be possible, either via some sort of configuration delegate or regex, to essentially only retry if a specific error occurs?

**Comment by RichiCoder1** [comment]
Maybe something like:

```
retryOn: (result: TestResult) => boolean
```

**Comment by pavelfeldman** [comment]
Could you share more on a potential use case? You'd like to look into the result data and consider whether retrying makes sense? I.e. looking at the result / logs you can figure out whether it makes sense to bail and not do the retries? Or you'll be only selecting certain tests for retry? The more information you give, the better we can address it!

**Comment by RichiCoder1** [comment]
> looking at the result / logs you can figure out whether it makes sense to bail and not do the retries

Mostly this. Essentially looking for specific `Error`s or log lines, if that makes sense.

**Comment by pavelfeldman** [comment]
Can't this be a try/catch on your side?

**Comment by RichiCoder1** [comment]
That doesn't allow retrying though. I would like the test to teardown and restart/retry.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
