### ISSUE TITLE
Set background image and/or color in Header and Footer in Page.printToPDF

### ISSUE THREAD

**Issue by zigm** [microsoft/playwright#7046]
I posted this issue on chromium-dev but didn't get satisfactory response. 
[Header and Footer issue](https://groups.google.com/a/chromium.org/g/chromium-dev/c/xHMM2mVrm1w)

Issue is that I am not able to inject background image and color into header and footer running the chrome-headless-render-pdf tool.

Based on results of my investigation, it is not likely that the chrome-headless-render-pdf java tool is the problem. The chrome-headless-render-pdf  relies on the chrome-remote-interface  npm package that implements CDP  protocol. The chrome-remote-interface  connects to Chrome remote debugging port, loads the page, populates print to pdf CDP method and forwards to Chrome.  

I did set the break point in void PrintRenderFrameHelper::PrintHeaderAndFooter()  and all internal structures for rendering  seem to be set properly.   It is possible that printing of the header and footer implement subset of HTML only. 

It looks like the **print_header_footer_template_page.html** controls the printing but problem is that debugging of the rendering is beyond my level of expertise. 

I was planning to test my Header and Footer HTML definitions using Playwright but noticed the following :

**note headerTemplate and footerTemplate markup have the following limitations: > 1. Script tags inside templates are not evaluated. > 2. Page styles are not visible inside templates.**

How should I read this? Does this imply that background-image and background-color properties will be ignored? I that is the case I may consider to file the enhancement request to Chromium.

I would expect that Puppeteer will have the same issue but I did not test this.

Thanks
Zbigniew

**Comment by JoelEinbinder** [comment]
Considering you are already in deep into the guts of CDP, I think this is an issue for the Chromium team. Playwright/Puppeteer/CRI all go through the same CDP method, so you shouldn't find any difference in how they behave.

**Comment by zigm** [comment]
Thanks for responding. I would most likely create the Playwright script, run the test, observe the same problem/limitation and not open the ticket except that I noticed the below on Playwright page:

**note headerTemplate and footerTemplate markup have the following limitations: > 1. Script tags inside templates are not evaluated. > 2. Page styles are not visible inside templates.**

which indicated to me that somebody on the Playwright team has a deeper knowledge of the limitations and could shed some light what I am seeing.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
