### ISSUE TITLE
[Question] Support for running tests serially

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#7050]
**Playwright Test Runner: v1.12.1**

I have 2 projects in playwright.config.js file. By default both projects run in parallel and in each project the test runs in parallel

Within each project i have 3 spec files, total 6 spec files. Noticed 6 browser instances are invoked when i run the test.

I have test case dependency between spec files. Can i control the parallel execution at project level to prevent too many worker invocation? I am looking for something where i can run both the projects in parallel but i should be able to control the parallel execution at the project level. Anything like max instances at project level will be helpful. 

With 2 projects and 2 workers set in config file, the order of execution is different.

Without specifying max workers in config file, two workers are invoked one for each project. With max workers =2 in config file, both the worker picks up the spec files from project 1 then project 2.

If one spec file is = one worker, then it will be difficult to control the browser invocations. If i set worker = 1, the entire test execution becomes sequential. It will be helpful if i have better control at project level.

Appreciate if you could provide me some solution for my requirement.

Projects: [
{
 name: 'project1'
testDir: 'test1
testMatch: ['*.spec.js]
use: {
}
}
 name: 'project2'
testDir: 'test2'
testMatch: ['*.spec.js]

use: {
}
]

**Comment by pavelfeldman** [comment]
It looks like you are trying to run tests in one of your projects serially and we don't support that. Let's keep this open to collect more feedback, I think it makes sense.

As a workaround, you could try running two projects simultaneously (you can tell playwright test to run only one project, so you run that command twice on your CI, in parallel). And in one of them you set workers=1...

**Comment by vsravuri** [comment]
Thanks for the feedback. Yes, previously with Protractor i used to invoke multiple browser instance, each instance running group of spec files in sequential order, to main the flow of functionality (in my application, i need to create article content, then categorize them, group them etc.). I have 50+ spec files with 400+ cases.

With Playwright Runner, i tried to achieve the same by grouping the spec files into multiple projects. Will try the workaround suggested by you.

**Comment by tanvee38** [comment]
@mxschmitt @pavelfeldman could you please consider Playwright test runner to run tests serially within a test script like Jest? I think for e2e tests it makes sense as it saves lots of time by not repeating the same test steps (for example login) in every test. After checking the playwright test runner, my understanding is that it considers every test independent even within a file and for every test case it launches the browser and runs each test separately. I really liked lots of amazing features playwright test runner provides out of the box (for example: configuring browsers, devices, running tests across all browsers, taking a screenshot/video on error and so on) while other test runners do not. I hope Playwright test runner will be flexible enough to accommodate the option to run tests serially at least within the test file. Thanks again for this awesome project!

**Comment by mxschmitt** [comment]
Closing since we have the serial mode now: https://playwright.dev/docs/api/class-test#test-describe-serial
