### ISSUE TITLE
[Feature] Add HTML reporter

### ISSUE THREAD

**Issue by kspolam** [microsoft/playwright#7062]
how can we use HTML reporters like allure reports or extent report in playwright/test

**Comment by Nav-2d** [comment]
[Reporters](https://playwright.dev/docs/test-reporters) in playwright/test.

Also, you can upvote the following feature request to add Allure Reporter: https://github.com/microsoft/playwright/issues/7034

**Comment by mxschmitt** [comment]
@kspolam is a html reporter important for you or would Allure be enough?

**Comment by kspolam** [comment]
A html reporter is important for me

**Comment by RichiCoder1** [comment]
Not sure if it'd be the same or a seperate issue, but a Markdown-flavored version would be awesome too

**Comment by mxschmitt** [comment]
What would be your use-case for that?

**Comment by RichiCoder1** [comment]
In a very narrowed down nutshell, often I want to print the output to something like a PR comment or a message thread and those tend to (either directly or indirectly) support markdown messages, but not rich html. A chat-and-GitHub-Actions specific issue though.

**Comment by AlexKomanov** [comment]
I'm joining for this feature! 
After your amazing update with a test runner - the HTML report is a kind of MUST!

**Comment by mpuertao** [comment]
I need report in HTML, thanks, stay tuned

**Comment by mpuertao** [comment]
This is possible?-> add screenshots to the report with allure in the version 1.13.0 of @playwright/test

**Comment by kspolam** [comment]
I should be able to access this reporter object in the test function so that I can add multiple steps information.

**Comment by adambbn** [comment]
It would be great if HTML report could contain screenshot added on test failure.

**Comment by alisterscott** [comment]
A HTML reporter similar to jest-stare would be great 👍 

https://www.npmjs.com/package/jest-stare

**Comment by mstepin** [comment]
Now that a test runner is available, a HTML reporter feels like an essential friend to have by your side. Should be a quick win and keep the entire community very happy.
