### ISSUE TITLE
Parallelism with playwright/test

### ISSUE THREAD

**Issue by kspolam** [microsoft/playwright#7063]
if 2 browser pages are opened concurrently, one browser closed with following error msg

 page.goto: net::ERR_CONNECTION_RESET

**Comment by mxschmitt** [comment]
Could you provide us the example tests which you are using and how do you start your web-server?

This means that the connection to your web server cannot be established.

**Comment by kspolam** [comment]
HI,

thanks for your reply.

The exact scenario is:

two tests which are in different test files are trying to navigate to the
same url using the  {page} fixture.

when these tests are invoked parallelly , browser launched from the one of
the test closed down automatically.

**Comment by mxschmitt** [comment]
Having code would help us a lot to find out where the exact problem is. Are you using version 1.12.1 for the test-runner and playwright library?

**Comment by kspolam** [comment]
HI,

I have checked with different urls, and found that the problem is
reproducible with a specific URL.
await this.page.goto('https://cspungw01/iM1WS_QO999/#/login');

what could be the problem and how can i resolve this issue?

**Comment by mxschmitt** [comment]
This is probably a problem with your internal (maybe staging) environment. That the webserver / firewall can't handle the load or blocks you and thinks the traffic is suspicious and refuses by that the connection. This is not a Playwright issue.

**Comment by kspolam** [comment]
Thanks for your valuable feedback. I will talk to my dev team and get back
to you.

**Comment by JoelEinbinder** [comment]
Closing this because it's not actionable from the playwright team.  If the dev team comes back and blames us, feel free to file a new issue with their reasoning.
