### ISSUE TITLE
[Question] How to parametrize fixtures in playwright-test?

### ISSUE THREAD

**Issue by radekBednarik** [microsoft/playwright#7065]
Hello,
first, thank you for the test runner!
I have a question regarding parametrization of the fixtures - is it possible and if so, then how? Did not find anything in the docs. For example pytest enables you to parametrize your fixtures....
Best
RB

**Comment by RichiCoder1** [comment]
They sorta allude to it, but don't directly mention it in the Test Fixtures section: https://playwright.dev/docs/test-fixtures#test-fixtures

Essentially, you define a "constant" fixture and then consume that via the parameterized fixture.

And, importantly, you can override the "constant" fixture using `text.use()`.

So, given the example:

```typescript
// hello.ts
import base from '@playwright/test';

// Define test fixtures "hello" and "helloWorld".
type TestFixtures = {
  hello: string;
  helloWorld: string;
};

// Extend base test with our fixtures.
const test = base.extend<TestFixtures>({
  // This fixture is a constant, so we can just provide the value.
  hello: 'Hello',

  // This fixture has some complex logic and is defined with a function.
  helloWorld: async ({ hello }, use) => {
    // Set up the fixture.
    const value = hello + ', world!';

    // Use the fixture value in the test.
    await use(value);

    // Clean up the fixture. Nothing to cleanup in this example.
  },
});

// Now, this "test" can be used in multiple test files, and each of them will get the fixtures.
export default test;
```

you could change hello like this:

```typescript
// hello.spec.ts
import test from "./hello";

test.use({ hello: 'aloha' });

test('my test', async ({ helloWorld }) => {
    expect(helloWorld).toBe('aloha, world!')
});
```

**Comment by radekBednarik** [comment]
@RichiCoder1 oh, seems I kinda skipped over this part :) . will try this approach ...

**Comment by radekBednarik** [comment]
so I looked into it, and yes, I can create multiple fixtures and pass the "returned" value by `use()` around. Cannot decide yet, if I actually like this approach, or not ...
However, what stopped me was this.
I am basically doing simple "data-driven" test, where I have configuration .toml file with defined urls of the domain, I want to visit them one by one and just verify specific request in the network.
Now, I am totally fine doing it in one spec file - for example in jest via `describe.each()` function.
When I tried doing something probably really naive -  like this in the fixture (this may be not syntactically correct, writing it directly here):

```
// this is loaded by global hook
const URLS = [url1, url2, etc]

const test = base.test.extend({
  urls: async ({}, use) => {
    for (const url of URLS) {
      await use(url);
    }
  });
})
```
then after first test run I will get the error, that I cannot reuse the fixture.

If I could somehow "yield" the items of the array of urls, that would be great. But I do not know, how to do it.

**Comment by radekBednarik** [comment]
So I looked into it, and in the source code of the fixtures, it is this line, that is tripping me up:
https://github.com/microsoft/playwright/blob/master/src/test/fixtures.ts#L74

in case, that I will try to provide fixture multiple times, as I try to feed to the test items from the array.

More specific example (please do not mind some peculiarities):

```
const it = test.extend({
  urls: Object.values(markets.cz.facelift.urls),
  container: listenerContainer,
  testedPage: async ({ urls, page, container }, use) => {
    const testedPage = new BasePage(
      page,
      { cookieManager: CookieManager },
      { network: Network }
    );

    for (let url of urls) {
      await testedPage.goto(url);
      await Promise.all([
        testedPage.network.catchRequest(
          re_pageview,
          container,
          undefined,
          ga.property.cz
        ),
        testedPage.cookieManager.clickBttnMainBannerAccept().catch(() => {}),
      ]);
      await testedPage.wait(3000);
      await use(testedPage, container);
      await testedPage.context.clearCookies();
      container.length = 0;
    }
  },
});

it("has all 'x' dimensions", async ({ testedPage, container }) => {
  expect(container).toHaveLength(1);

  const parsedDims = parseCustomDimsToBools(container[0], re_customDims, "=");

  expect(
    await testedPage.network.validateCustomDimensions(
      parsedDims,
      def_customDims
    )
  ).toBe(true);
});
```

**Comment by pavelfeldman** [comment]
> This can be solved by putting whole test code into the callback of the Array.forEach() and loop thru the array this way.

This ^^. We try to keep it simple and use a regular for loop for this:

```js
for (const data in [...]) {
  test('testing ' + data, async () => {});
}
```

Looks similar to https://github.com/microsoft/playwright/issues/7036
The fixtures trick with `use` would work if you'd like to pass different data into different testing projects though, so it is also valid.

**Comment by radekBednarik** [comment]
Let's say that I want to store the fixture and import it into multiple spec files.

Now I am providing for example url via looping from array, and using it in the fixture. - as shown above. 

After the abstraction, I cannot provide the url, or am I missing something? Because the imported fixture has to be used as argument of test() callback and I cannot provide the url to the code inside the fixture.. 

So I can have 'parametrized' test via looping, if I have fixture in the spec file, but not, if I will try to import it...

**Comment by pavelfeldman** [comment]
> Let's say that I want to store the fixture and import it into multiple spec files.

I am not sure we are talking about the same fixtures. The fixture term that we use in a Playwright context is a particular thing: https://playwright.dev/docs/next/test-fixtures. It can't be stored, it is defined once via `extend`.

> After the abstraction, I cannot provide the url, or am I missing something? Because the imported fixture has to be used as argument of test() callback and I cannot provide the url to the code inside the fixture..

I am not sure which abstraction you are talking about, could you elaborate? In either case, your fixture can be of type function:

```js
test('test', async ({ fixtureFunc }) => {
  const result = await fixtureFunc(url);
});
```

**Comment by radekBednarik** [comment]
@pavelfeldman sure, sorry for not being clear.

So, if I understood the example here https://playwright.dev/docs/test-fixtures#test-fixtures correctly, you can basically export (aka my incorrect term 'store the fixture') the extended test in the .js file (hello.js in the example) and then import the extended test function and provide the fixtures into the new test() functions as arguments to the callback.

I know, that I can provide arguments to the fixture used in the `test()`.

But, If I understood correctly - but maybe I am just being stupid this late in the day, fixtures passed in the `test()` works like this: code in the fixture that is provided as argument for `test()` callback gets executed first automatically, and then the code declared in the `test()` gets executed afterwards.

So if my fixture looks like this:

```
const it = test.extend({
  container: listenerContainer,
  testedPage: async ({ url, page, container }, use) => {
    const testedPage = new BasePage(
      page,
      { cookieManager: CookieManager },
      { network: Network }
    );

      await testedPage.goto(url);
      await Promise.all([
        testedPage.network.catchRequest(
          re_pageview,
          container,
          undefined,
          ga.property.cz
        ),
        testedPage.cookieManager.clickBttnMainBannerAccept().catch(() => {}),
      ]);
      await testedPage.wait(3000);
      await use(testedPage, container);
      await testedPage.context.clearCookies();
      container.length = 0;
  },
});
```
so I have no way to pass the url into it? Or did I get it wrong?

**Comment by pavelfeldman** [comment]
So you have two ways of passing `url` into it. First via introducing a `url` fixture and then passing it into `use {}` via your config or in your test:

```js
const { test: base } = require('@playwright/test');

const test = base.extend({
  url: 'default',
  testedPage: async ({ url }, use) => {
    console.log(url);
    await use();
  }
});

// The scope of use is file or describe
test.use({
  url: 'overridden',
});

test('test 1', async ({ testedPage }) => {
});
```

Second is via making testedPage a function:

```js
const { test: base } = require('@playwright/test');

const test = base.extend({
  testedPage: async ({}, use) => {
    await use(url => console.log(url));
  }
});

test('test 1', async ({ testedPage }) => {
  testedPage('url')
});
```

**Comment by radekBednarik** [comment]
Thanks a lot, I understand now👍Because you linked this issue to another one, please close it, as you will.

**Comment by pavelfeldman** [comment]
Closing as per above!
