### ISSUE TITLE
[REGRESSION]: `folio` cannot be exported when upgrading to 1.12

### ISSUE THREAD

**Issue by AntouanK** [microsoft/playwright#7070]
**Context:**
- GOOD Playwright Version: 0.1111.0
- BAD Playwright Version: 1.12.1
- Operating System: Linux

**Code Snippet**

So far I had this line to get the base
```javascript
import {folio as baseFolio} from '@playwright/test';
```

After updating to 1.12.1 that doesn't work anymore.

Also imports like this
```javascript
import {Route} from 'playwright';
```
are not working

**Comment by mxschmitt** [comment]
Playwright does not use Folio anymore, see here for an up-to-date guide and how to use the new test-runner: https://playwright.dev/docs/test-intro

**Comment by AntouanK** [comment]
We still need something like `folio` to run the tests though, right?

I used to have this snippet to change the executable path
```js
import {folio as baseFolio} from '@playwright/test';

const builder = baseFolio.extend();
builder.browserOptions.override(async ({browserOptions}, runTest) => {
  const modifiedOptions: LaunchOptions = {
    ...browserOptions, // Default options
    slowMo: 50,
    headless: true,
    executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,
  };
  await runTest(modifiedOptions);
});
```

how can I do it now that Playwright and folio are separate?

**Comment by mxschmitt** [comment]
See here how you can use projects: https://playwright.dev/docs/test-advanced#projects

**Comment by AntouanK** [comment]
Ok, I got tests running.

How can we change the `executablePath` at runtime now?
Is there an env variable?
`page` is injected automatically in tests, so I cannot see how to set the `executablePath` to the browser it uses.

**Comment by mxschmitt** [comment]
Why do you want to change it at runtime? Curious to hear about that use-case.

**Comment by AntouanK** [comment]
because for the CI we have a docker image that has chrome pre-installed ( https://github.com/Zenika/alpine-chrome)

I tried this
```
// extend base test
export const test = base.extend<{page: Page}>({
  page: async () => {
    const browser = await browserPromise;
    const page = await browser.newPage();
    return page;
  }
});
```

and pass the `test` to the test files.
but all tests are failing and there's no error log or screenshots to see why.

any ideas on how to debug it?

**Comment by mxschmitt** [comment]
Do you are skipping the browser downloads like here? https://playwright.dev/docs/installation#skip-browser-downloads

In the project configuration under launchOptions you can set the executable path: https://playwright.dev/docs/test-configuration

Will adjust the docs later, so it's more clear.

**Comment by AntouanK** [comment]
I think that's what I did in the code snippet I posted above.

The issue is that when I try it locally ( where I have the browser installed ) all tests fail.
Without that snippet ( so with the original `test` ) they all work.
On CI again they all fail.

Cannot understand why. I'm printing the url of the new page ( "about:blank" ) so the page is there.
Not sure how to debug it.

**Comment by mxschmitt** [comment]
I mean having a playwright.config.ts like that:

```ts
// playwright.config.ts
import path from 'path'

import { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  timeout: 120 * 1000,
  testDir: path.join(__dirname, 'tests'),
  forbidOnly: !!process.env.CI,
  workers: 1,
  projects: [
    {
      name: 'chromium',
      use: {
        browserName: 'chromium',
        launchOptions: {
          executablePath: "/fooo"
        }
      },
    },
  ],
  reporter: 'list',
};

export default config
```

This should give you a Chromium browser with your custom executable path.

**Comment by AntouanK** [comment]
That worked fine. Thank you. :+1: 
I think some examples like that in the doc would be very useful.
The multiple reporters took me a while to figure out as well ( `[['list'],['junit']]` ) so an example there would be nice as well.

**Comment by mxschmitt** [comment]
We have recently adjusted the docs, so that it contains `launchOptions` and `contextOptions`, see here: https://playwright.dev/docs/next/test-configuration

This should be the default docs in v1.13 then.
