### ISSUE TITLE
[BUG] Traceviewer screens are not recorded well when using constructable stylesheets

### ISSUE THREAD

**Issue by Tallyb** [microsoft/playwright#7085]
**Context:**
- Playwright Version: 12.1.1
- Operating System: mac
- Node.js version: 16
- Browser: Chromium
- Extra: [any specific details about your environment]

when running trace viewer on a site built with stencil-js, the html snapshots are displayed incorrectly. 
This is due to the use of constructable stylesheet.

**Comment by Tallyb** [comment]
Still exists in 1.12.3

**Comment by dgozman** [comment]
@Tallyb Does this still repro for you? I am trying to reproduce this on sites like https://stenciljs.com/, but it seems to work.

**Comment by Tallyb** [comment]
@dgozman - It still happens. I believe the stencil.js site does not contain web components with shadow dom. 
You can run on our website (app.yoobic.com. You should encounter the issue on the login page so no credentials are needed).
