### ISSUE TITLE
[BUG] Reporter configuration 

### ISSUE THREAD

**Issue by macroking** [microsoft/playwright#7088]
**JSON report is not generated**
- Playwright Version: 1.12.0
- Operating System: Linux
- Node.js version: 12.x
- Browser: Chromium

**Configuration**

```javascript

// playwright.config.js
module.exports = {
    use: {
        // Browser options
        headless: false,
        slowMo: 50,
        browserName: 'chromium',
        channel: 'chrome',

        // Context options
        viewport: { width: 1280, height: 720 },
        ignoreHTTPSErrors: true,

        // Run options
        forbidOnly: true,
        maxFailures: 10,
        preserveOutput: 'always',

        // Artifacts
        //screenshot: 'only-on-failure',
        video: 'retry-with-video',
        trace: 'only-on-failure',

        // Reporter
        reporter: [['json', { outputFile: 'results.json' }]],
    },
};
```

When I pass the `--reporter` param from the command line JSON output is logged in the console. I passed the same from the `playwright.config.js` but is not producing the JSON file after the execution.

I also tried closing the context after each test even that is not helping.

EDIT: I moved the reporter configuration outside of the browser and context configuration and is now working fine. I think the documentation needs to be updated to make it very clear about the configuration.

**Comment by mxschmitt** [comment]
Do you have a broken snippet from somewhere or where do you think do the docs need an adjustment?

We recommend using TypeScript, then your editor like Visual Studio Code should gave you a hint, that this property is not supported.

**Comment by pavelfeldman** [comment]
I went over the docs and they all seem right. @ts-check will probably also suggest the fix.
