### ISSUE TITLE
[Question] How to apply map function to each element in array of elements ?

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#7091]
I am migrating my test cases from Protractor to Playwright.

In Protractor i used map function to return multiple properties of each element in array of elements.

This function was useful for me to assert sort order of elements in array of elements with index value, also to return multiple properties of each element. Also helpful in returning table rows and columns with index value.

How can i achieve this with Playwright? My application has huge number of HTML tables. Appreciate if you can provide me a solution to achieve the with Playwright.

Here is the sample code in Protractor.

```javascript
<ul class="items">
  <li class="one">First</li>
  <li class="two">Second</li>
  <li class="three">Third</li>
</ul>

let items = element.all(by.css('.items li')).map(function(elm, index) {
  return {
    index: index,
    text: elm.getText(),
    class: elm.getAttribute('class')
  };
});
expect(items).toEqual([
  {index: 0, text: 'First', class: 'one'},
  {index: 1, text: 'Second', class: 'two'},
  {index: 2, text: 'Third', class: 'three'}
]);

// Or using the shortcut $$() notation instead of element.all(by.css()):

let items = $$('.items li').map(function(elm, index) {
  return {
    index: index,
    text: elm.getText(),
    class: elm.getAttribute('class')
  };
});
expect(items).toEqual([
  {index: 0, text: 'First', class: 'one'},
  {index: 1, text: 'Second', class: 'two'},
  {index: 2, text: 'Third', class: 'three'}
]);

```

https://www.protractortest.org/#/api?view=ElementArrayFinder.prototype.map

**Comment by creage** [comment]
#6447

**Comment by vsravuri** [comment]
Thanks, it works.
