### ISSUE TITLE
[BUG] Firefox 89.0b6 evaluate ImageData.data failed

### ISSUE THREAD

**Issue by zyscoder** [microsoft/playwright#7095]
**Context:**
- Playwright Version: v1.11.1
- Operating System: Linux
- Node.js version: v14.15.1
- Browser: Firefox
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const { firefox } = require('playwright');

(async () => {
  const browser = await firefox.launch();
  console.log(`${browser.version()}`);
  const context = await browser.newContext();
  const page = await context.newPage();
  try {
    const res = await page.evaluate(() => new ImageData(1280, 720).data);
    console.log(code, res.toString());
  } catch (e) {
    console.error(e, e.toString());
  }
})();
```

**Describe the bug**

An exception is thrown: `Error: page.evaluate: Protocol error (Runtime.callFunction): error in channel "content::page": exception while running method "callFunction" in namespace "page":  sendMessage@chrome://juggler/content/SimpleChannel.js:21:30
_onMessage@chrome://juggler/content/SimpleChannel.js:166:24
 _onMessage@chrome://juggler/content/SimpleChannel.js:149:16
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42`

**Comment by mxschmitt** [comment]
`new ImageData(1280,720).data` results in a `Uint8ClampedArray` which has a length of `3686400` which would be JSON serialized 50.5 MB. What are you trying to accomplish?

**Comment by zyscoder** [comment]
I filed this report because I found the same code would be evaluated successfully in both Chrome and Webkit. Only Firefox threw.

**Comment by mxschmitt** [comment]
Closing since this feels not like a real scenario. Please create a new issue if you face into any bugs with a repro.
