### ISSUE TITLE
[Question] User Authentication

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [microsoft/playwright#7096]
I have a scenario where I want to automate a set of actions, but the authentication has to be done by the user (I cannot store the login credentials in a script). 

Is it possible to create a script that loads the login screen and waits for the user to login (the login may include user name, password and optionally captcha and 2 factor authentication). Once the user is logged in, I want script to do its job and finally logout the user.

**Comment by VinayaSathyanarayana** [comment]
Any example will be of great help.

**Comment by pavelfeldman** [comment]
You can use `page.pause()` in your script and resume once you've logged in. Does this work for you?

**Comment by VinayaSathyanarayana** [comment]
@pavelfeldman - Thanks for the response.   Can I do a conditional ```page.pause()``` and wait till the user completes the login [May be wait till ```logout``` button gets enabled and then do the rest of the required steps.  Would appreciate an example

**Comment by pavelfeldman** [comment]
In this case you don't need pause at all, you just wait for the button to get enabled with some generous timeout (or 0 for infinite timeout). When user is done, the script will continue on its own.

**Comment by VinayaSathyanarayana** [comment]
Thanks  @pavelfeldman.  Any example I can refer to?

**Comment by pavelfeldman** [comment]
That would be

```js
await page.waitForSelector('element-that-is-there-only-after-login', { timeout: 0 });
```

This would make playwright stall on that line until user logs in and `element-that-is-there-only-after-login` shows up on the screen.

**Comment by pavelfeldman** [comment]
Closing as resolved
