### ISSUE TITLE
[test-runner] Missing  types for the expect library

### ISSUE THREAD

**Issue by fbasso** [microsoft/playwright#7099]
Hi !

In vscode, the expect library imported from '@playwright/test' proposes only a few choices:

![image](https://user-images.githubusercontent.com/1152930/121865483-4e28fa80-ccfe-11eb-80c6-948ca0ec1070.png)

And using the available assertions displays an error. For example:

```ts
import { expect } from '@playwright/test';
expect(...).toBe(...)
// Property 'toBe' does not exist on type 'Matchers<string>'.ts(2339)
```

**Comment by mxschmitt** [comment]
As a workaround for now setting `esModuleInterop` or `allowSyntheticDefaultImports` to `true` in your `tsconfig.json` under `compilerOptions` should fix it.

**Comment by fbasso** [comment]
It worked perfectly, thanks @mxschmitt !
