### ISSUE TITLE
[BUG] SharedWorker constructor request is missing from network

### ISSUE THREAD

**Issue by Meir017** [microsoft/playwright#7107]
**Context:**
- Playwright Version: 1.12.2
- Operating System: Windows
- Node.js version: v12.13.1
- Browser: Chromium, Firefox (doesn't exist in Webkit)

**Code Snippet**

SharedWorker constructor does not trigger the `request`

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
    const browser = await playwright.chromium.launch({
        headless: false,
        devtools: true
    });
    const context = await browser.newContext({ });
    const page = await context.newPage();
    await page.goto('https://example.com/');
    const requestPromise = context.waitForEvent('request', { predicate: () => true, timeout: 5000 });
    await page.evaluate(() => {
        new SharedWorker("/worker.js");
    });
    const request = await requestPromise;
    console.info(request);
})();
```

**Describe the bug**

I suspect the issue is related to the devtools component and not playwright

**Comment by mxschmitt** [comment]
Looks related to https://bugs.chromium.org/p/chromium/issues/detail?id=851323

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
