### ISSUE TITLE
[BUG] Issue with coverage after istanbul conversion

### ISSUE THREAD

**Issue by ExFlo** [microsoft/playwright#7109]
**Context:**
- Playwright Version:1.12.2
- Operating System: Windows
- Node.js version: 12.8.3
- Browser: Chromium,
- Extra: 

**Code Snippet**

Repo to clone
[reproducer](https://github.com/ExFlo/playwright-codecoverage)

**Describe the bug**

I want to be able to merge the coverage generated by Playwright for each tests into one.
I have an issue using nyc to merge and generate the reports after the conversion to istanbul (as described by documentation).

I don't know if this is linked to coverage generated by Playwright or the other tools.

I am able when using other tool, to instrument the tests and to extract the coverage, to generate coverage but not in case of Playwright tools.

After cloning the repo run:
npm install; npm run e2e:playwright

to reproduce the issue.

Error message is: 
"Invalid file coverage object, missing keys, found:path,all,statementMap,s,branchMap,b,fnMap,f"

Indeed the file generated have empty path which leads to the error.

Thx for the help.

BR

**Comment by mxschmitt** [comment]
Hi, since you are using @playwright/test I would recommend that you wait for #7030. This gives you coverage report out of the box for all the browsers and not only or Chromium.

**Comment by mxschmitt** [comment]
Closing as it gets addressed in #7030.

**Comment by fschwalm** [comment]
Hello @ExFlo! Have you fixed this problem?
I'm facing the same problem.


thank you so much!

**Comment by ExFlo** [comment]
> Hello @ExFlo! Have you fixed this problem?
> I'm facing the same problem.
> 
> thank you so much!

Hi 
No I am waiting for the coverage report system in @playwright/test as described above. Did not landed in 1.13 version...so still waiting.

**Comment by fschwalm** [comment]
@mxschmitt any updates?

thank you so much!
