### ISSUE TITLE
[Question] setup-after-env equivalent for test runner

### ISSUE THREAD

**Issue by suchlike** [microsoft/playwright#7116]
I'm using a setup-after-env script with jest-playwright to load some static test data into env variables which are then used in the tests and page objects. Is there an equivalent way to do this with the new test runner?

**Comment by pavelfeldman** [comment]
Could you share more about the data you are sharing? What kind of data is that, how does it relate to the parallelization? Why does regular require not work for you?

**Comment by suchlike** [comment]
We have environment specific test data loaded from json files, not related to the parallelization. With some refactoring this could work without the stetup-after-env and regular require. But transitioning to the playwright runner would be easier if the same mechanism existed there :)

**Comment by pavelfeldman** [comment]
Could you give me an idea on the changes that you would need to do? I'm trying to figure out if transition ergonomics is worth additional API. If that is solved with a 4 liner that exposes data that can be either stored in env in setup-after-env and could be explicitly required, it would probably be not worth it. But if it is a substantial refactoring - it is.

**Comment by suchlike** [comment]
In our case it is probably simple enough to move the data to static members of the base page object class and reference it there rather than loading it into env variables in the setup-after-env script. So not substantial refactoring for our use case, but this was the only gap we noticed from jest-playwright.

**Comment by dgozman** [comment]
Closing this one in favor of `require`.
