### ISSUE TITLE
[Feature] HDR and/or P3 color space support?

### ISSUE THREAD

**Issue by LouisStAmour** [microsoft/playwright#7126]
It's not clear to me where the blockers are on this one. 

I tried a couple combinations of the `force-color-profile` flag and couldn't get Chrome to launch on Mac when combined with the `ensure-forced-color-profile` flag. 

On Linux (via Docker for Mac, default Playwright image), it ran (because ensure-forced-color-profile is a no-op) but every time the screenshots looked like sRGB, not P3. 

I didn't have a windowing Linux environment to see if Chrome was successfully running in a different colour profile or not.

My test was pretty basic:

```
test("P3 color", async ({ page }) => {
  await page.goto("https://webkit.org/blog-files/color-gamut/comparison.html", { waitUntil: "networkidle" })
  expect(await page.screenshot()).toMatchSnapshot(`test-p3.png`)
})
```

There's a lot of places where this could break down. All I was seeing was sRGB screenshots or some weird forced-P3-mapped-to-sRGB out of Firefox. (Come to think of it, Firefox might be giving us P3 data, but then the image is tagged as sRGB instead of P3? Maybe? Seems kind of broken.)

So I thought, let's try it in `--headed` mode on my P3 Macbook display. Chromium and Firefox seemed to give the same odd results, but Safari visually showed the correct P3 output. But the screenshot taken by Playwright didn't support P3, it was flattened to sRGB reds instead.

Any ideas on how we could push for more complete HDR10+ and/or P3 support in Playwright test screenshots and, ideally, device specifications? https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-captureScreenshot doesn't seem to indicate any preferences for colour space, for example, not that it theoretically would need to if done correctly...? 

I can confirm that on a Macbook, both Chrome and Safari stable versions show the P3 images. Firefox stable converts colours to sRGB then displays the sRGB colours untagged as P3 colours, so the reds are really intense. Firefox Dev Edition, on the other hand, still displays the page as sRGB, but manages to tag it as sRGB such that colours aren't weirdly blown out, it just doesn't support showing the P3 content. Let's skip Firefox for now, because https://bugzilla.mozilla.org/show_bug.cgi?id=455077 indicates a bunch of attempts over the years but nothing final yet.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
