### ISSUE TITLE
What is replacement of browser from Protractor in playwright[Question]

### ISSUE THREAD

**Issue by goyalshweta017** [microsoft/playwright#7128]
Hello, 

I am migrating my automated script from protractor to playwright.
I have observe that in protractor, we have 'browser' object which we can use anytime directly importing protractor.

But when i have migrating to Playwright, we have not have similar object which can be used through out code.

We are creating Page object but Page object as well can be call in same class or only in extended class.
Hence i have query and need suggestion like is there way we can use page object anywhere in code like browser in protractor

**Comment by mxschmitt** [comment]
Closed, we are going to track it in #7189 and add some guides there.
