### ISSUE TITLE
[Feature]: Global Page Instance Variable

### ISSUE THREAD

**Issue by goyalshweta017** [microsoft/playwright#7137]
Let us know what functionality you'd like to see in Playwright and what is your use case.
Do you think others might benefit from this as well?
Hello,

To give you background, I am migrating my protractor test to Playwright. I have one main repo containing all fixture( having all methods interacting with browser element. from there different App Repo targeting and reusing fixture from main repo. We are having helper methods in each app repo. hence in few places when we need to interact with browser, we use 'browser' from protractor. like  browser.getAllWindowHandles() OR await browser.getCurrentUrl() etc.

Now in Playwright, we found it restricted as when we launch wit chrome.launch() and then BrowserContext/Page to open URL. Page instance is restricted to have scope only in that test file or max file which extending it.

Hence to simplify migration it will be great if there will be page/browser instance variable which can be use from playwright and once instantiate will have value until browser kill. 

I guess it will helpful to every one who will migrate from protractor to playwright and can simplify migration too.

Thanks,
Shweta

**Comment by mxschmitt** [comment]
Sharing a page object between tests is not recommended. We would switch test after test into the new setup with the Playwright test-runner to ensure the best-practices are applied. Having a new page (and in the Playwright world context) for each test makes it possible to run them individually without any dependencies.

**Comment by goyalshweta017** [comment]
hello,

Here we will not be sharing page object between tests.

Its like once page object is instantiate( page launch) we will able to access that page object in any helper function . like at present 'browser' in protractor. 

In Playwright i can access page object only in test where its created.not in any helper. if i need to use in helper it should be pass as variable in each helper. 

If Page object will be global it will easy to use like “browser” is an instance of ProtractorBrowser class.

**Comment by pavelfeldman** [comment]
I'll fold this into https://github.com/microsoft/playwright/issues/7254, because it looks like you can achieve the same result with the steps inside a single large test.
