### ISSUE TITLE
[Docs] Add example for connectOverCDP and the test-runner

### ISSUE THREAD

**Issue by markov00** [microsoft/playwright#7138]
I'm currently working on migrating our [visual regression tests setup](https://github.com/elastic/elastic-charts) from Puppeteer to Playwright.
Our current setup allows running the test suite locally running test the VRTs against a dockerized instance of the Puppeteer browser. Only the browser works in Docker and we connect our Puppeteer test via websocket.

This setup is reusable both locally and on CI and reduces the need of building and packaging a Docker image with all the dependencies required to run the application (node, storybook, etc) since most of the time everything is already available and running locally.
Running the browsers within Docker helps us on avoiding rendering differences between OS (font, aliasing, etc)

I was wondering if such a thing is also possible with Playwright: how can I connect a Playwright test to a Dockerized browser instance from Playwright? 
Thanks

**Comment by mxschmitt** [comment]
Related #7031

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
