### ISSUE TITLE
[Question] Which typescript configuration is used by Playwright and how to extend it (if possible) ?

### ISSUE THREAD

**Issue by ExFlo** [microsoft/playwright#7142]
Hi
Question is: Which typescript configuration is used by Playwright and how to extend it (if possible) ?
Thx a lot

**Comment by mxschmitt** [comment]
Playwright does ship its own types with the main package. So no @types packages are required. What do you mean with extend?

We use [this](https://github.com/microsoft/playwright/blob/master/tsconfig.json) tsconfig.json for out build, but this should not have any effects on end user experience.

**Comment by ExFlo** [comment]
I mean for example with jasmine I was able to provide a tsconfig (for include, exclude definition) and add some path definition also. Is it possible to do so with playwright/test ?

**Comment by mxschmitt** [comment]
You can have your main tsconfig, which your editor like Visual Studio Code will pick up. Having a custom tsconfig is not supported, see here #7121.
