### ISSUE TITLE
[Feature] Support for Raspberry PI 4

### ISSUE THREAD

**Issue by alvipeo** [microsoft/playwright#7143]
Guys, I know there was another feature request created long time ago. But this is really important functionality for test automation. Raspberry pi does not consume nearly as close power as any pc. Besides, it's cheap and we can use multiple of them.

I just wanted to know how difficult this would be?

Thanks!

**Comment by mxschmitt** [comment]
If you are only relying on Chromium, this should be faily easy but not officially supported. You can use the `PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS=1` environment variable and use the `playwright-core` package. In the `executablePath` when launching, you need to specify a local Chromium binary or use channels which "should" also work, which you can typically install from your package manager (apt).

For WebKit and Firefox its not possible.

**Comment by alvipeo** [comment]
Thank you. Let me try that. I'll follow up on this.

**Comment by pavelfeldman** [comment]
I hope it works for you since we don't list Raspberry as our supported platform. Patches are welcome though, so if you find an issue and fix it, we can review and help landing.

**Comment by mxschmitt** [comment]
Video recording is probably problematic, since it uses our custom ffmpeg which is not built for the RPI architecture.
