### ISSUE TITLE
[Question] [TestRunner] How to take screenshots or video for test group?

### ISSUE THREAD

**Issue by ortoniKC** [microsoft/playwright#7144]
### Hi, I am using a test group with hooks in page object model.

**tc001.test.ts**
```ts
test.describe("TC001", () => {
    let header: HeaderPage;
    let login: LoginPage;
    let common: CommonFunctions;
    let page: Page;
    test.beforeAll(async ({ browser }) => {
        page = await browser.newPage();
        // constructor - Pages
        header = new HeaderPage(page);
        login = new LoginPage(page);
        common = new CommonFunctions(page);
    })
    test.beforeEach(async () => {
        await page.goto("https://letcode.in")
    })

    test("Login positive", async () => {
        await page.goto("https://letcode.in")
        expect(page.url()).toBe("https://letcode.in/")
        await header.clickLoginLink();
        expect(page.url()).toBe("https://letcode.in/signin")
        await login.enterUserName(data.email);
        await login.enterUserPassword(data.pass);
        await login.clickLoginBtn();
        const toaster = await common.toaster();
        expect(await toaster?.textContent()).toContain("Welcome");
        await header.clickSignOutLink();
    });
    test("Login again", async () => {
        await page.goto("https://letcode.in")
        await header.clickLoginLink();
        await login.login("koushik350@gmail.com", data.pass);
        await page.waitForNavigation();
        expect(page.url()).toBe("https://letcode.in/")
    })
})
```
**playwright.config.ts**
```ts
const config: PlaywrightTestConfig = {
    use: {
        headless: false,
        channel: "chrome",
        screenshot: "on",
        video: "on"
    },
    testMatch: ["tc001.test.ts"],
    retries: 0,
    reporter: [["dot"], ["json", { outputFile: "test-result.json" }]]
}
```
**Problem:**
If we have a page fixture within every test it's taking the video and screenshots but that will run in every context, I want to execute in a single context (browser).

**Comment by mxschmitt** [comment]
Hi, your current setup is not ideal, because you share a page with different tests. This means, you can never run your tests individually, since they depend on each-other.

A recommended solution is to create a custom fixture for your header and login, this would look something like that:

```ts
// baseFixtures.ts
import { test as baseTest } from '@playwright/test';
import { Page } from 'playwright';

const test = baseTest.extend<{letcodeInPage: Page, headerPage: HeaderPage, loginPage: LoginPage, common: CommonFunctions}>({
  letcodeInPage: async ({ page }, use) => {
    await page.goto("https://letcode.in")
    await use(letcodeInPage);
  },
  headerPage: async ({ letcodeInPage }, use) => {
    const headerPage = new HeaderPage(letcodeInPage);
    await use(headerPage);
  },
  loginPage: async ({ letcodeInPage }, use) => {
    const loginPage = new LoginPage(letcodeInPage);
    await use(loginPage);
  },
  common: async ({ letcodeInPage }, use) => {
    const common = new CommonFunctions(letcodeInPage);
    await use(common);
  },
});

export const it = test;
export const expect = test.expect;
```

Then inside your tests you can do:

```ts
// example.test.ts
import {test, expect} from './baseFixtures';

test.describe("TC001", () => {
    test("Login positive", async ({headerPage, loginPage, commmon}) => {
        expect(page.url()).toBe("https://letcode.in/")
        await headerPage.clickLoginLink();
        expect(page.url()).toBe("https://letcode.in/signin")
        await loginPage.enterUserName(data.email);
        await loginPage.enterUserPassword(data.pass);
        await loginPage.clickLoginBtn();
        const toaster = await common.toaster();
        expect(await toaster?.textContent()).toContain("Welcome");
        await headerPage.clickSignOutLink();
    });
    test("Login again", async ({headerPage, page, loginPage}) => {
        await headerPage.clickLoginLink();
        await loginPage.login("koushik350@gmail.com", data.pass);
        await page.waitForNavigation();
        expect(page.url()).toBe("https://letcode.in/")
    })
})
```

(untested, since I don't have your fixtures, but something like that should work and give you the ability of running them individually)

**Comment by ortoniKC** [comment]
Thanks for the response, I'll try it and update.

**Comment by ortoniKC** [comment]
Hi, after few modifications of the code, I am able to execute it, but still, the problem is the same. 
Even with fixtures, every test runs in its own context.

I have achieved using Jest and if I try to apply the same logic in Test Runner it's working cool but the video and snapshot alone not working.
I will link my git repo for both, if you have time kindly suggest. 

[Playwright POM with Jest:](https://github.com/ortoniKC/Playwright-TypeScript-Jest)

[Playwright POM with test runner:](https://github.com/ortoniKC/Playwright-Test-Runner)

**Comment by mxschmitt** [comment]
Ah yeah my bad. Its not possible to have a video for a whole group/describe out of the box. The test-runner is designed that every test can ran independently and by that its an own context for each individual test. This has the limitation that a new video gets started for each test.

You could do it with your approach, launch the browser manually but this is not recommended and not supported with this test-runner.

**Comment by ortoniKC** [comment]
Ok got it. 
May be global page object can solve this I believe. 
As of now, I will go with my approach but please add this as a feature request.

Thanks for a quick reply, have a great day.

**Comment by begli80** [comment]
Has any solution been found to this issue or not yet ?

**Comment by lalit4786** [comment]
Is the feature request for global page object is upcoming!!!
