### ISSUE TITLE
include API for drag and drop simulation

### ISSUE THREAD

**Issue by owenpearson** [microsoft/playwright#715]
I'm having a play around with replacing selenium in my automated tests with playwright and i can't seem to get drag and drop to work using the 'move', 'down', and 'up methods on page.mouse. the app i'm testing uses DragEvent.dataTransfer so i imagine this is why i'm not having any luck. is there a reccomended way to simulate drag and drop events using the current api, or better yet, would it be possible to introduce an api for simulating drag and drop events?

p.s. i would prefer not to use page.eval to trigger events using javascript if possible.

cheers.

**Comment by JoelEinbinder** [comment]
I definitely want to do this. It requires some upstream work in Chromium.

**Comment by JoelEinbinder** [comment]
Closing as a retroactive duplicate of #1094
