### ISSUE TITLE
[Feature] strict test mode

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright#7153]
Fail a test if the website has:
- any unhandled javascript errors
- any 4xx 5xx or otherwise failed network requests
- mixed content warnings
- deprecation messages
- cors errors

**Comment by pavelfeldman** [comment]
Like this:

`strict: '*'`
`strict: '404,error,warning,deprecation,mixedContent'`

or this?

```
{
  404: 'fail',
  consoleError: 'fail',
  jsError: 'fail',
  mixedContent: 'warn'
}
```

**Comment by RichiCoder1** [comment]
The latter would be awesome, I think. Especially if 'warn' produces a state indicator in results like 'slow' does.

**Comment by RichiCoder1** [comment]
And addendum to this might also eventually being able to allow list/allow function specific violations, but the described here would be a great MVP.

**Comment by JoelEinbinder** [comment]
> Like this:
> 
> `strict: '*'`
> `strict: '404,error,warning,deprecation,mixedContent'`
> 
> or this?
> 
> ```
> {
>   404: 'fail',
>   consoleError: 'fail',
>   jsError: 'fail',
>   mixedContent: 'warn'
> }
> ```

I was thinking a `strict` boolean with more specific flags for overrides a la [typescript](https://www.typescriptlang.org/tsconfig#strict). Happy with your second proposal as well, as long as I can say `strict: 'error'` to opt in to all current/future strict modes.

**Comment by Nav-2d** [comment]
Coming from Slack.
```
// utils/pageUtils.js
module.exports = {
  logErrors: (page) =>
    page.on('console', async (msg) => {
      if (msg.type() === 'error') {
        console.log(`Error text: "${msg.text()}"`);
      }
    }),
};
```
```
// specs/example.spec.js
const { logErrors } = require('../utils/pageUtils');
test.describe('Test example', () => {
  test.beforeEach(async ({ page }) => {
    logErrors(page);
  });
  // ...
```
I want to capture error logs and for that I have the above util function. I am passing the page from each spec file to the util function and it works as expected. Let’s say I have 50 spec files, then I have to pass the page from each spec (repetitive code). Is there a way to implement it globally to capture errors logs for all tests? Maybe a variable `captureConsoleLogs` which can set to `yes` or `no`.

**Comment by dgozman** [comment]
From #7484: currently using Protractor config to filter errors and write them to the test results folder:

```
screenshotPath: reportDirectory,
            withLogs: 'true',
            htmlReport: 'true',
            verbose: 'info',
            failTestOnErrorLog: {
                failTestOnErrorLogLevel: 900,
                excludeKeywords: ["favicon.png "]
            }
```

**Comment by shadow-light** [comment]
@Nav-2d Yes, you can call your error logging util within an override of the page fixture like so:

```
import {test} from '@playwright/test'
const extended_test = test.extend({
    page: async ({page}, run) => {
        attach_js_error_handler(page)
        await run(page)
    },
})
export {extended_test as test}
```

You should import `test` from that file rather than from `@playwright/test`. You'll need to do this if you want to add any other fixtures in the future too, so it's good practice to always import from an extended test, as far as I can tell.

**Comment by shadow-light** [comment]
Having a strict mode would be great, especially for single page apps where a JS error can often be fatal, and might happen at the very end of a test, so wouldn't be picked up by any assertions.

At the moment I'm just throwing within my js error handler util (similar to what @Nav-2d has).

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
