### ISSUE TITLE
[Question] How to remove '[Automation]' in browser title

### ISSUE THREAD

**Issue by srkeyan** [microsoft/playwright#7166]
when using playwright-python, there's always the world '[Automation]' in page title

Does anyone know how to remove this tag?

Thanks.

**Comment by mxschmitt** [comment]
It's not possible to remove it. What is your use-case for it?

**Comment by pavelfeldman** [comment]
Which browser is that, WebKit?

**Comment by srkeyan** [comment]
> Which browser is that, WebKit?

yes, webkit

**Comment by srkeyan** [comment]
> It's not possible to remove it. What is your use-case for it?

when using playwright + webkit to visit some sites, it easily gets blocked or be asked to pass captcha

so I wonder it mitght be because the 'Automation' in browser title

do you know this tag comes from playwright or webkit?

**Comment by pavelfeldman** [comment]
This is not because of this message. This message is only there for the user, web page does not know about it.

**Comment by srkeyan** [comment]
> This is not because of this message. This message is only there for the user, web page does not know about it.

Thanks
