### ISSUE TITLE
[Feature] Default configuration option values in docs

### ISSUE THREAD

**Issue by phuctm97** [microsoft/playwright#7168]
Let us know what functionality you'd like to see in Playwright and what is your use case.
Do you think others might benefit from this as well?

Mention default values of configuration in docs. Playwright docs did a good job describing all the options but it didn't say what default value each option has, this allows users to what to expect when leaving certain options.

**Comment by mxschmitt** [comment]
Which options do you mean? In the normal public API or is it something test-runner specific?

**Comment by phuctm97** [comment]
I mean this section: https://playwright.dev/docs/test-configuration#configure-browser-context-videos-and-screenshots
Think it is the most common configuration.

**Comment by mxschmitt** [comment]
For `launchOptions` and `contextOptions` we fixed it in the new release, see [here](https://playwright.dev/docs/next/test-configuration). Before it was not referenced correctly.

For the other values, its mentioned, that tracing, video and screenshot are all off by default.

**Comment by phuctm97** [comment]
Got it!
