### ISSUE TITLE
[Feature]: Add tag support for test-runner

### ISSUE THREAD

**Issue by akshayp7** [microsoft/playwright#7169]
Hi Folks,

I have a question, I have written a single test case inside a single .ts file, So if I want to run 2 test cases I must run two .ts files. So my question is there a way to tag only these 2 .ts files and run? Is there any other way?

Like for example in a folder I have 10 .ts files but I want to run only two of them.

Thanks in Advance.

**Comment by mxschmitt** [comment]
You can focus tests by using `test.only(` instead of `test(`. Does this work for your use-case?

See here: https://playwright.dev/docs/next/test-intro#focus-a-test

Do you need it during writing your test-files?

**Comment by akshayp7** [comment]
This Worked for me, Thank you so much...

But my idea was like do we have something like in jest-runner-group, where we tag the files right like @Regression and run only those with tags.

**Comment by akshayp7** [comment]
thanks for looking into this feature !!!!!

**Comment by klhex** [comment]
Yes, such a feature would be really nice. Maybe something similar to the "--grep" option in Mocha (https://mochajs.org/api/mocha#grep).

**Comment by pavelfeldman** [comment]
https://playwright.dev/docs/next/test-annotations/#tag-tests

**Comment by akshayp7** [comment]
Thanks this feature is working like charm
