### ISSUE TITLE
[BUG] WebKit WebInspector does not work on Windows

### ISSUE THREAD

**Issue by DukeBJ** [microsoft/playwright#7170]
Context:
- Playwright Version: 1.12.2
- Operating System: win 10 20H2 19042.1052
- Node.js version: 14.16.0
- Browser: wk
- Extra: no

Don't work Inspect element when i'm open page via cli

npx playwright wk https://wikipedia.org

**Comment by imagoiq** [comment]
Same issue on my machine, win 10 21H1 19043.1023. Latest version to work is @1.11.1

**Comment by mxschmitt** [comment]
I can repro. Its about the Web Inspector which leads to a white window on Windows. On Ubuntu it was working for me with 1.12.X. 1.11.1 was also working for me on Windows.

**Comment by mxschmitt** [comment]
I verified this works now in the latest version. You can try it via the development releases via `npm install playwright@next` or wait for 1.13.
