### ISSUE TITLE
[BUG] Discrepancy in Trace Viewer screenshots

### ISSUE THREAD

**Issue by NickTulett** [microsoft/playwright#7173]
**Context:**
- Playwright Version: 12.1.1
- Operating System: Mac
- Node.js version: 12.18
- Browser: Chromium
- Extra: trace generated in **playwright-java** but viewed using **npx playwright show-trace trace.zip**

Hopefully you can see from the image that the left-hand menu in our app is different in the large screenshot and the smaller timeline thumbnail. This test is clicking elements in the menu that causes sub-menus to open. The timeline thumbnail is correct and the red dot is in the correct relative position but the Action screenshot is not updating to show the current view as in the timeline - the red dot appears to be randomly moving around a static menu as I step through the test.

**Describe the bug**
![image](https://user-images.githubusercontent.com/350365/122205840-97ad4d00-ce98-11eb-968c-bee814a55e2a.png)

**Comment by dgozman** [comment]
I think the cause here is that red dot is not scrolling as expected.

**Comment by NickTulett** [comment]
The issue is that the main "Action" screenshot is not being updated to reflect what is in the timeline. The app's side menu scrolls up the screen as each section is opened by a click.
The red dot is in the correct position for clicking the "Credit" section of the menu but the screenshot is wrong - it should look like the one in the timeline.

**Comment by NickTulett** [comment]
There are 6 main sections in the menu and in the test there is a click for each one, so I should see 6 different Action screenshots in this part of the test, but the screenshot does not update after the first click.

**Comment by NickTulett** [comment]
Ah wow I had completely missed the fact that the Action screenshot has an active toolbar, so the discrepancy is that the element being clicked hasn't been scrolled into position to meet the red dot.

**Comment by dgozman** [comment]
v1.13 should have scrolled elements in the right position.
