### ISSUE TITLE
[Bug] Improve error handling when Playwright calls will stall and test-runner timeouts the test

### ISSUE THREAD

**Issue by shtlrs** [microsoft/playwright#7174]
Hi,

So I'm testing a web application using playwright and i'm making a test fail on purpose.

The problem is that there's no traceback in the console when a test fails, so I don't really know where it has failed exactly.

Is there a way to enable this ? 

Here's an example of what I'm talking about:

```
Running 2 tests using 2 workers
  1) Invoice\addInvoice.spec.ts:4:5 › [chromium] Add a simple invoice test 01.Login & add an invoice

    Timeout of 30000ms exceeded.

    Retry #1 --------------------------------------------------------------------------------------

    Timeout of 30000ms exceeded.

  Slow test: addInvoice.spec.ts (1m)

  1 failed
    Invoice\addInvoice.spec.ts:4:5 › [chromium] Add a simple invoice test 01.Login & add an invoice
  1 passed (1m)
````

The **addInvoice.spec.ts:4.5** shows where the grouped tests start and not where it has failed exactly.

Thanks.

**Comment by mxschmitt** [comment]
This is caused that the test reached the timeout and it gets terminated. You can increase the timeout, in the test-runner config and set it to e.g. 60 seconds. This should then result that the Playwright methods will actually have enough time to timeout and show a full stack-trace.

See here how to adjust the timeout: https://playwright.dev/docs/next/test-configuration#testing-options

I've created also an issue #7175 to set the default timeout to 60 seconds.

**Comment by shtlrs** [comment]
Thanks for the answer @mxschmitt, It worked ! 

But isn't this a strange behavior ? 

Because if a timeout does occur, whether it's  60 or 30 seconds, it should also result , just like in any other test runner , in a helpful output. 

Because having to wait for 60 seconds just for a test to log meaningful things to console doesn't seem like a regular "pattern".
