### ISSUE TITLE
[BUG] Powershell/cmd.exe does not display the status mark (✓/x)

### ISSUE THREAD

**Issue by akshayp7** [microsoft/playwright#7177]
**Context:**
- Playwright Version: [1.12.0]
- Operating System: [Windows]
- Browser: [ Chromium]

Description:

This is a minor issue , if you run test cases using Line reporter via Command prompt or Gitbash, when test cases pass, we get a question 
![Gitbash](https://user-images.githubusercontent.com/78036666/122257071-47140f00-ceed-11eb-80b1-71d30fd7d280.PNG)
![CmdPrompt](https://user-images.githubusercontent.com/78036666/122257136-585d1b80-ceed-11eb-9c59-a699c5e54260.PNG)

mark symbol instead of a tick mark

**Comment by mxschmitt** [comment]
Which version of Windows are you using?

**Comment by akshayp7** [comment]
Thanks for Replying quickly .
Windows 10.

**Comment by akshayp7** [comment]
![vscode](https://user-images.githubusercontent.com/78036666/122360781-4bcfd600-cf74-11eb-9ff9-215e7e0c6ecb.PNG)
 Another thing, inside VS Code terminal(Poweshell) it works fine

**Comment by mxschmitt** [comment]
I'm able to repro in cmd.exe and PowerShell. The [new Windows Terminal](https://github.com/microsoft/terminal) seems to work fine.
