### ISSUE TITLE
[Doc] Introduce Protractor and Jest migration guides for Test Runner

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#7189]
There are a lot of questions about global page object, global setup, passing data among those migrating. Let's help them with the guide.

https://github.com/microsoft/playwright/issues/7116
https://github.com/microsoft/playwright/issues/7137
#7128

**Comment by Tallyb** [comment]
FWIW, I will leave it here for defining browser as global with typescript (I had some trouble getting there): 

```
//@types/node@16
// eslint-disable-next-line no-var
var browser: ChromiumBrowser | FirefoxBrowser | WebKitBrowser;

declare global {
  // eslint-disable-next-line no-var
  var browser: ChromiumBrowser | FirefoxBrowser | WebKitBrowser;
}
browser = await chromium.launch()
```

```
//@types/node@15
declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace NodeJS {
    interface Global {
      browser: ChromiumBrowser | FirefoxBrowser | WebKitBrowser; //change to your favorite browser
    }
  }
}
global.browser = await webkit.launch(browserOptions);

**Comment by aslushnikov** [comment]
- We're looking for the protractor test suite with no luck. 
- We decided not to follow-up on the jest-playwright migration guide. Those folks are already happy!
