### ISSUE TITLE
[BUG] Hermetic install downloads to wrong directory causing tests to always fail

### ISSUE THREAD

**Issue by kevin-brotcke** [microsoft/playwright#7197]
I upgraded to the latest version 1.12.2 to use the new Playwright test runner (AWESOME!) but it looks like it broke the [hermetic install](https://playwright.dev/docs/installation#managing-browser-binaries) feature enabled by setting `PLAYWRIGHT_BROWSERS_PATH=0`. Every time it will successfully re-download the browsers but won't be able to find them. To confirm I ran it with debug logs enabled, here is a snippet:

```
$ export PLAYWRIGHT_BROWSERS_PATH=0
$ export DEBUG=pw:*
$ npx playwright install
$ npx playwright test

  pw:install downloading Playwright build of chromium v888113 - attempt #1 +0ms
  pw:install running download: +1ms
  pw:install -- from url: https://playwright.azureedge.net/builds/chromium/888113/chromium-linux.zip +0ms
  pw:install -- to location: /tmp/playwright-download-chromium-ubuntu18.04-888113.zip +0ms
  pw:install -- response status code: 200 +230ms
  pw:install -- total bytes: 130326367 +2ms
Downloading Playwright build of chromium v888113 - 124.3 Mb [====================] 100% 0.0s 
  pw:install SUCCESS downloading Playwright build of chromium v888113 +24s
  pw:install extracting archive +0ms
  pw:install -- zip: /tmp/playwright-download-chromium-ubuntu18.04-888113.zip +0ms
  pw:install -- location: /home/kevin/.npm/_npx/11833/lib/node_modules/playwright/.local-browsers/chromium-888113 +0ms
  pw:install fixing permissions at /home/kevin/.npm/_npx/11833/lib/node_modules/playwright/.local-browsers/chromium-888113/chrome-linux/chrome +5s

  pw:channel:response   id: 1,
  pw:channel:response   error: {
  pw:channel:response     error: {
  pw:channel:response       message: "Failed to launch chromium because executable doesn't exist at /home/kevin/myproject/node_modules/@playwright/test/.local-browsers/chromium-888113/chrome-linux/chrome\n" +
```
It looks like it's installing the browsers in the wrong NPM config cache dir then attempting to launch them in the correct dir but fails since nothing was ever downloaded at that location.

This is easy to workaround for now by manually setting the value to the correct dir.

**Comment by mxschmitt** [comment]
It seems like you don't have the playwright package installed in your project thats why its using the NPX tmp directory. You you try running `npm install playwright` and then again your install commands?

**Comment by kevin-brotcke** [comment]
I also tried installing `playwright` package but it installs the browsers to its own local node modules folder that `@playwright/test` doesn't find.

```
$ npm i -D playwright

> playwright@1.12.2 install /home/kevin/myproject/node_modules/playwright
> node install.js

  pw:install downloading Playwright build of chromium v888113 - attempt #1 +0ms
  pw:install running download: +1ms
  pw:install -- from url: https://playwright.azureedge.net/builds/chromium/888113/chromium-linux.zip +0ms
  pw:install -- to location: /tmp/playwright-download-chromium-ubuntu18.04-888113.zip +0ms
  pw:install -- response status code: 200 +411ms
  pw:install -- total bytes: 130326367 +1ms
Downloading Playwright build of chromium v888113 - 124.3 Mb [====================] 100% 0.0s 
  pw:install SUCCESS downloading Playwright build of chromium v888113 +25s
  pw:install extracting archive +1ms
  pw:install -- zip: /tmp/playwright-download-chromium-ubuntu18.04-888113.zip +0ms
  pw:install -- location: /home/kevin/myproject/node_modules/playwright/.local-browsers/chromium-888113 +0ms
  pw:install fixing permissions at /home/kevin/myproject/node_modules/playwright/.local-browsers/chromium-888113/chrome-linux/chrome +5s
Playwright build of chromium v888113 downloaded to /home/kevin/myproject/node_modules/playwright/.local-browsers/chromium-888113
```

Then I get the same error when running the tests.

```
$ npx playwright test

    browserType.launch: Failed to launch chromium because executable doesn't exist at /home/kevin/myproject/node_modules/@playwright/test/.local-browsers/chromium-888113/chrome-linux/chrome
    Try re-installing playwright with "npm install playwright"
```

Strangely running install command says it's already downloaded.

```
$ npx playwright install

  pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'BrowserType',
  pw:channel:event     initializer: {
  pw:channel:event       executablePath: '/home/kevin/myproject/node_modules/playwright/.local-browsers/chromium-888113/chrome-linux/chrome',
  pw:channel:event       name: 'chromium'
  pw:channel:event     },
  pw:channel:event     guid: 'browser-type@d96e1782583b292804e20cad5bddf533'
  pw:channel:event   }
  pw:channel:event } +0ms
pw:install browser chromium is already downloaded. +0ms
```

**Comment by pavelfeldman** [comment]
@mxschmitt we don't expect people to install both playwright and @playwright/test. This can be done, but we hope to never see it happening - people that need library would go for playwright, people that test will go for @playwright/test.

For the hermetic install, what I did locally was:
```sh
mkdir hermetic
cd hermetic
npm init -y
npm i -D @playwright/test
PLAYWRIGHT_BROWSERS_PATH=0 npx playwright install
```

and it downloaded the browser to the right location. Then I ran tests as 

```sh
PLAYWRIGHT_BROWSERS_PATH=0 npx playwright test
```

and it used those browsers.

**Comment by pavelfeldman** [comment]
I can see how `npx playwright install` w/ `PLAYWRIGHT_BROWSERS_PATH=0` gets confused. The intention here is mixed: 'Perform a hermetic install while using shared non-hermetic npx cache'. We should probably throw if we see npx without the project installed locally in combination with the PLAYWRIGHT_BROWSERS_PATH.

**Comment by kevin-brotcke** [comment]
The example you posted works for me but still doesn't work in my project. Looking to see if it's something to do with the upgrade or another workspace setting.

**Comment by kevin-brotcke** [comment]
Okay I see what's happening now and understand your comment. I'm executing playwright using the global install of npx which seems to create a unique cache directory. If I install npx locally or call `node_modules/.bin/playwright install` directly it works fine.

Maybe the playwright executable could set the browser install path relative to itself? `node_modules/.bin/playwright/../../@playwright/test/.local-browsers`

**Comment by pavelfeldman** [comment]
I actually don't think we should install browsers to under node_modules, we should rather put them into the root folder of the project. That's something we inherited from the earlier versions of ourselves.

In either case, if you do run `npm install @playwright/test` prior to running `npx playwright install`, things do work, can you confirm that? I guess that's what you should do? Hermetic install implies that playwright is installed locally, so `node_modules/.bin/playwright/../../@playwright/test/.local-browsers` should point to the same location we would install browsers. Or do I miss something?

**Comment by kevin-brotcke** [comment]
I agree, I'd prefer the hermetic default to be something like `.ms-browsers` folder created in root project folder.

I wasn't seeing the issue after I uninstalled all old versions of playwright (local and global) and completely cleared npm cache directories. It was still bugging me how I got into that state and I finally found a way to reproduce it.

New install, working:
```
export PLAYWRIGHT_BROWSERS_PATH=0
export DEBUG=pw:*
mkdir hermetic_fresh_install
cd hermetic_fresh_install
npm init -y
npm i -D @playwright/test
npx playwright install # to node_modules/@playwright/test/.local-browsers
npx playwright test
```

Example of upgrading, also working:
```
export PLAYWRIGHT_BROWSERS_PATH=0
export DEBUG=pw:*
mkdir hermetic_good_upgrade
cd hermetic_good_upgrade
npm init -y
npm i -D playwright # to node_modules/playwright/.local-browsers
npm un playwright
npm i -D @playwright/test
npx playwright install # to node_modules/@playwright/test/.local-browsers
npx playwright test
```

I followed the [documentation update note](https://playwright.dev/docs/test-intro):

> Playwright Test is self-contained, it does not need Playwright to be installed. If you are an existing Playwright user, make sure that you either uninstall Playwright or update Playwright before installing Playwright Test: `npm i -D playwright @playwright/test`

```
export PLAYWRIGHT_BROWSERS_PATH=0
export DEBUG=pw:*
mkdir hermetic_bad_upgrade
cd hermetic_bad_upgrade
npm init -y
npm i -D playwright @playwright/test # to node_modules/playwright/.local-browsers
npx playwright install # already at node_modules/playwright/.local-browsers
npx playwright test # uses node_modules/playwright/.local-browsers
npm un playwright # after realizing I don't need
```

At this point we're in a broken state and weird things happen. If I run `npx playwright test` again it can't find the browsers and installs them to a cache dir like `~/.npm/_npx/32519/lib/node_modules/playwright/.local-browsers`. If I run install or test commands again it keeps installing in new temp dirs and always fails to run because `npx playwright` attempts to use `node_modules/@playwright/test/.local-browsers`.

It might not be worth fixing since it's such an obscure bug that depends on specific upgrade steps + hermetic feature enabled. I think we just need to clarify in the docs to only have one version installed at a time and default instructions use the new playwright test runner package. Currently the [getting started page](https://playwright.dev/docs/intro) that most people will read first says to run `npm i -D playwright` then the [test runner page](https://playwright.dev/docs/test-intro) says to run `npm i -D @playwright/test` so I probably won't be the only one confused by this and accidentally install both. It would make sense for `npm i -D playwright` instruction to be moved to [third party runners page](https://playwright.dev/docs/test-runners) to avoid confusion.

**Comment by kevin-brotcke** [comment]
Also, this error message is misleading if I only have `@playwright/test` installed and haven't run `npx playwright install` yet.

```
browserType.launch: Failed to launch chromium because executable doesn't exist at /home/kevin/myproject/node_modules/@playwright/test/.local-browsers/chromium-888113/chrome-linux/chrome
Try re-installing playwright with "npm install playwright"
```

When it should actually say something like:

```
Try re-installing playwright browsers with "npx playwright install"
```

Or even do that automatically if they are missing.

**Comment by mxschmitt** [comment]
This was fixed a few releases ago. Please create a new issue of you still encounter this behavior.
