### ISSUE TITLE
[Question] Using waitForFunction to wait for component to re-render

### ISSUE THREAD

**Issue by TC-mSundaram** [microsoft/playwright#7217]
I have a component that initially shows the text "Loading..." until the text is calculated. I thought that I could use the `page.waitForFunction` like this:

```ts
    await page.waitForFunction(() => {
      const profile = document.querySelector('[aria-label="profile name"]') as HTMLSpanElement | null;
      return !profile?.innerText.includes('Loading');
    });

    const profileName = await page.innerText('[aria-label="profile name"]');

    expect(profileName).toBe(profile.name);
```

However this isn't working, I always still get back that `profile` is `"Loading..."` 

If I instead use

```ts
    await page.waitForTimeout(1000);
    const profileName = await page.innerText('[aria-label="profile name"]');
    expect(profileName).toBe(profile.name);
```

it works fine. 

What am I missing about using the `waitForFunction`? The docs say that using `waitForTimeout` in a test isn't a good idea.

**Comment by pavelfeldman** [comment]
I guess the problem is that at first element has no text, then it has Loading text and then it gets populated. I would do something like this:

```js
// Wait for Loading to appear
await page.waitForSelector(`[aria-label="profile name"]:has-text('Loading')`);
// Now wait for it to become something different from Loading and get innerText
const profileName = await page.innerText(`[aria-label="profile name"]:not(:has-text('Loading'))`);
```

If someone calls profile "Loading" you are in trouble though. But maybe Loading also has some extra css class you can use instead of text for matching!

**Comment by TC-mSundaram** [comment]
@pavelfeldman Thanks so much, that works! I hadn't thought of using the `:not` in a `waitForSelector` - that's great.
