### ISSUE TITLE
[Question] disable timeout with playwright test runner

### ISSUE THREAD

**Issue by mtt87** [microsoft/playwright#7222]
I'm trying to start a test and then pause and start the recording to capture stuff in the inspector.

I've tried different methods, run it with:
```bash
PWDEBUG=1 playwright test
PWDEBUG=console playwright test
```
Add these on the tests
```js
await page.pause()
await page.waitForSelector('abc', {
  timeout: 0
})
```

but nothing seems to be working, once I hit the 30000ms timeout I get the thrown out of the tests and I can't finish to record the steps.

I was using Jest before and I could add this
```js
jest.setTimeout(process.env.PWDEBUG === '1' ? 1000000 : 30000)
```

Is there an equivalent for playwright test runner?
I've searched the documentation but couldn't find anything about this.

Thank you!

**Comment by mxschmitt** [comment]
You can have a custom timeout in the config, see [here](https://playwright.dev/docs/test-configuration#testing-options) or via the CLI parameters [here](https://playwright.dev/docs/test-cli).

This issue looks also similar to #7174 for me, which gets fixed in the next release.

**Comment by mtt87** [comment]
Thank you very much @mxschmitt I've totally missed that!
