### ISSUE TITLE
How to prevent TimeoutError: Navigation timeout of 30000 ms exceeded or TimeoutError: page.waitForLoadState: Timeout 30000ms exceeded ? 

### ISSUE THREAD

**Issue by HelenMariia** [microsoft/playwright#7233]
Hello! I'm writing e2e-tests with Playwright. Tests are integrated in Pipeline and run every time as a part of building.
```
Versions:
 "playwright": "^1.10.0",
 "jest-playwright-preset": "~1.5.2".
```
 The problem  - when I run tests locally or they are run during the building process, from time to time the browser just stop and then I have `TimeoutError: page.waitForLoadState: Timeout 30000ms. ` or `TimeoutError: Navigation timeout of 30000 ms exceeded` I want to understand the reason as of such an issue and prevent it. Forums are full of advises like to change` 'networkidle'` to `'domcontentloaded'`, or to add `page.setDefaultNavigationTimeout(0)`. Also I found that to I have to increase the Jest timeout because the Playwright timeout is greater than the Jest timeout - so to add `jest.setTimeout(35 * 1000) `. It helped for 90% of cases. 
 Could you, please, explain why does this happens and what it the best practice to prevent it ?
 I can share some code, but which one do you need ?

**Comment by mxschmitt** [comment]
Playwright has recently released a [Trace Viewer](https://playwright.dev/docs/trace-viewer) which is designed for giving you insights why a certain test is e.g. failing. I would recommend to try that out to investigate why its failing. There is also a dedicated page for debugging tests, which you can find [here](https://playwright.dev/docs/debug).
With jest-playwright-preset you need to call context.tracing.start and stop manually. With the Playwright test-runner its available out of the box, see [here](https://playwright.dev/docs/test-intro).

**Comment by mxschmitt** [comment]
Closing since the issue seems stale. Please create a new issue if you still face any issues.
