### ISSUE TITLE
[Feature] reduce playwright-core npm package size

### ISSUE THREAD

**Issue by btecu** [microsoft/playwright#7241]
Why is `playwright-core` so much larger than `puppeteer-core`?
Storage is not an issue, but the size has a cost (time) when it comes to AWS Lambda startup:

![image](https://user-images.githubusercontent.com/7517745/122692092-2c99a880-d201-11eb-9e89-54a521d3e775.png)

Looks like `playwright-core` size almost doubled from `1.8.1` to `1.9.0`:
![image](https://user-images.githubusercontent.com/7517745/122692100-391e0100-d201-11eb-8e00-2d5d6170f5c5.png)

It appears that `playwright-core` does not whitelist files and instead includes everything, even testing assets and some Android tooling (likely for testing as well):
![image](https://user-images.githubusercontent.com/7517745/122692369-91093780-d202-11eb-9112-73eb521a71d5.png)

`puppeteer-core` instead lists the files to be included when using the library (not developing it):
![image](https://user-images.githubusercontent.com/7517745/122692398-bd24b880-d202-11eb-8682-a5ec95e32f95.png)

Finally, it's possible `playwright-core` may also need to trim the dependencies a bit, maybe move some to `devDependencies`?
For example, `pixelmatch` is only used in `/test`, hence it shouldn't be bundled with `playwright-core` or even `playwright` but with `@playwright/test`.

**Comment by mxschmitt** [comment]
Maybe we should move the binary files on the CDN like we do the same with browsers.
- PrintDeps.exe
- android-driver-target.apk
- android-driver.apk

Regarding the dependencies, we trim them when we publish, see here for a few current examples:
- https://unpkg.com/browse/playwright-core@next/package.json
- https://unpkg.com/browse/playwright@next/package.json

which don't contain pixelmatch etc.

cc @aslushnikov

**Comment by aslushnikov** [comment]
> Why is playwright-core so much larger than puppeteer-core?

@btecu We ship some assets in the `bin` folder for ease of deployment. However, like Max said, we can kick them out to our registry so that NPM package size is slim again.

Did you like the size of `playwright-core` pre-1.9.0 release?

**Comment by btecu** [comment]
Yes, that would be a good first step. The `/test` content should also be excluded, right?

**Comment by aslushnikov** [comment]
> Yes, that would be a good first step. The /test content should also be excluded, right?

@btecu We don't ship `/test`. Do you see it somewhere?

![image](https://user-images.githubusercontent.com/746130/123063929-afb62c80-d3c2-11eb-8cdc-1ed150cee8f0.png)

**Comment by btecu** [comment]
It's under `/lib`, maybe not the same thing?
<img width="769" alt="image" src="https://user-images.githubusercontent.com/7517745/123177360-23077f00-d453-11eb-91f9-29fa5e09001c.png">

Also `/lib/third_party` might not be needed.

**Comment by aslushnikov** [comment]
Ah, these! 
- `/lib/test` is the `@playwright/test` implementation,
- `/lib/third_party` is used in test runner and GUI tools

These all are just code though, so I expect savings to be negligible for the zip archive.

Realistically, we can kick binary assets out of bin folder to get to pre-v1.9 size, but that'll be it.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
