### ISSUE TITLE
[BUG] getAttribute('select', 'value') returns null

### ISSUE THREAD

**Issue by mtt87** [microsoft/playwright#7245]
**Context:**
 - OS: macOS 11.4
 - Memory: 7.82 GB / 32.00 GB
 - Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
 - Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.0/bin/yarn
 - npm: 7.15.1 - ~/.nvm/versions/node/v14.17.0/bin/npm
 - Bash: 3.2.57 - /bin/bash
 - playwright: ^1.12.2 => 1.12.2

**Code Snippet**

```ts
// works correctly and the value is set in the browser
await page.selectOption('select[name="country"]', 'IT')

// returns null
console.log(await page.getAttribute('select[name="country"]', 'value'))
```

**Describe the bug**

`getAttribute(selector, 'value')` of a `<select>` seems to always return `null`.

**Comment by mxschmitt** [comment]
`value` is a property and not an attribute. Some documentation sites on the internet reference it wrongly which might be confusing.

See here for more information; https://github.com/microsoft/playwright/issues/3265#issue-670663769

Are you migrating from Selenium?

This should work in your scenario:

```js
console.log(await page.$eval('select[name="country"]', element => element.value))
```

See here for reference: https://playwright.dev/docs/api/class-page#page-eval-on-selector

**Comment by Edord99** [comment]
On this

**Comment by mtt87** [comment]
@mxschmitt Thanks for the explanation.

I'm not trying to move from Selenium, I've started from scratch using Playwright (which I love, great job ❤️ )

If I understand correctly `value` is considered a property only for the `select` element but not for the `input` element? 

Because this code works for the input
```ts
// works
expect(await page.getAttribute('input[name="city"]', 'value')).toBe(
  details.city,
)
```
