### ISSUE TITLE
[Feature] Test Runner - One snapshot for all browsers

### ISSUE THREAD

**Issue by cscheffauer** [microsoft/playwright#7247]
At the moment if 
```javascript
expect(await page.screenshot()).toMatchSnapshot('Login.png');
```
will be used, 3 screenshots will be created (per browser one):
![image](https://user-images.githubusercontent.com/29776408/122768059-85ba1880-d2a3-11eb-9233-c53330f583b4.png)

This is happening because I've used the 3 browsers in the playwright config as projects.  

Is there a way to just have 1 screenshot file to compare against, so the naming ("Login") keeps persistent and cross browser comparisons can be done? 

Related issue: https://github.com/microsoft/playwright/issues/7182

**Comment by mxschmitt** [comment]
The reason behind that is that browser rendering engines are different. Some add here and there a bit more spacing or the fonts look different. Having the same picture for all the browsers to compare with does not work in most scenarios.

Is this a big issue for you?

**Comment by cscheffauer** [comment]
Right - the intention of this test is that the UI doesn't break / look different across browsers. But I guess therefore the threshold option by underlying pixelmatch library is not smart enough to ignore a bit of spacing here and there right?

**Comment by pavelfeldman** [comment]
It is a bit more fun than a pixel, if the text is one pixel off, it breaks line after a different word, the entire page shifts and transforms...

**Comment by cscheffauer** [comment]
Gotcha - so you think the snapshot functionality can't be used for cross browser visual testing?

**Comment by aslushnikov** [comment]
> Gotcha - so you think the snapshot functionality can't be used for cross browser visual testing?

We've spent quite some time trying to make it work, and so far we don't think it's possible. Fonts are very different across browsers and operating systems, and they affect layout and rendering drastically.

**Comment by cscheffauer** [comment]
Ok thanks, @aslushnikov :)

**Comment by AzrizHaziq** [comment]
I'm writing tests and update snapshot in my local with: 
- OS: macos
- Browser: chrome

And on CI(github-action) with: 
- OS: Linux
- Browser: chrome

Screenshot image from local will generate something like `abc-chromium-darwin.png` while on CI it will try to match the snapshots with `abc-chromium-linux.png`. See more [here](https://github.com/AzrizHaziq/automate/runs/2929792514?check_suite_focus=true#step:7:14)

I agreed that different browser & OS will have different snapshots. However, if we can have optional config that we can overwrite the generated filename would be really helpful 😄.

**Comment by AzrizHaziq** [comment]
So I just found a config that suit my need.

```
  test.beforeEach(async ({ page: p }, testInfo) => {
    testInfo.snapshotSuffix = ''
    ...
```

with this, output image will not suffixed with os `abc-chromium.png` 
[DOC](https://playwright.dev/docs/test-advanced#testinfo-object)

**Comment by florianbepunkt** [comment]
@AzrizHaziq 
I have the same situation, however I have the os not only in the file name, but also in the folder names, e. g. "login-screen-Desktop-darwin"

It would be helpful to be able to configure this behaviour

**Comment by AzrizHaziq** [comment]
Hi @florianbepunkt , have you try `snapshotPath,  outputDir, outputPath`. Hope this help you.
https://playwright.dev/docs/test-advanced/#testinfo-object

**Comment by florianbepunkt** [comment]
@AzrizHaziq Thanks. Found out my problem was that setting `testInfo.snapshotSuffix = ''` in beforeEach did not work. Not sure why, but setting it inside a test worked.

```ts
test.beforeEach(async ({}, testInfo) => {
    testInfo.snapshotSuffix = ''"
})

test("some test", async ({}, testInfo) => {
    console.log(testInfo.snapshotSuffix); // this still gave me "darwin
    testInfo.snapshotSuffix = ''"; // I had to set this individual inside each test
    console.log(testInfo.snapshotSuffix); // now it gave ""
})
```
