### ISSUE TITLE
[Question]Running test multiple times with different parameters

### ISSUE THREAD

**Issue by macroking** [microsoft/playwright#7259]
Is it possible to run the same test with different input data?. Possibly using the test data from a JSON file

**Comment by aslushnikov** [comment]
> Is it possible to run the same test with different input data?. Possibly using the test data from a JSON file

*(NB: I assume we're talking about [@playwright/test](https://playwright.dev/docs/test-intro/))*

@macroking If you have a JSON data, you can just do a for-loop. Alternatively, you can just have a single test that iterates over the data elements.

Let me illustrate this. Say for example we have `data.json` that looks like this:

```json
[
  { "value": 1 },
  { "value": 2 },
  { "value": 3 }
]
```

Now I can create multiple tests from this `data.json` the following way - here's my `test.js`:

```js
const {test, expect} = require('@playwright/test');
// import JSON data
const data = require('./data.json');

for (const {value} of data) {
  test(`should work with value ${value}`, () => {
    console.log(`DONE - value ${value}`);
  });
}
```

**NOTE**: a few important things to pay attention to:
- this way we will generate multiple tests. If the JSON data is large, we might end up with lots of tests. Playwright test runner will run them very fast though, but you might not want it
- if you **do want** to create many tests, make sure to change test names like in this example to simplify your life in test reporting
- if you **do not want** to create many tests, read on

Alternatively we can have a single test that validates the JSON data:

```js
test('should be valid data', () => {
  for (const {value} of data) {
    expect(value > 0).toBe(true);
  }
});
```

This way you have a single test that can iterate over JSON structure and do something.

Both approaches are very valid.

**Comment by macroking** [comment]
@aslushnikov  Thank You. It is working as expected even when using multiple workers.

I am wondering if there is any plans to add a syntactic sugar , something like what `jasmine-data-provider` provides. https://www.npmjs.com/package/jasmine-data-provider

I tried `jasmine-data-provider` with playwright and is working well.

**Comment by mxschmitt** [comment]
I think its similar to #7036 with test.each.
