### ISSUE TITLE
[BUG] PDF margins - Playwright output is different from the Chrome PDF output (a wide html table)

### ISSUE THREAD

**Issue by naro** [microsoft/playwright#7261]
**Context:**
- Playwright Version: 1.12.1
- Operating System: Mac
- Node.js version: N/A (Python 3.8.5, but should not matter)
- Browser: Playwright build of chromium v888113

**Code Snippet**

Create file /tmp/test.html
```
<html>
<head>
<style>
  table {
    width: 100%;
    border: 1px solid black;
    border-collapse: collapse;
  }
  table td, table th {
    border: 1px solid black;
    padding: 4px
  }
</style>
</head>

<body>
<table>
  <thead>
    <tr>
        <th>Header 1</th>
        <th>Header 2</th>
        <th>Header 3</th>
        <th>Header 4</th>
        <th>Header 5</th>
        <th>Header 6</th>
        <th>Header 7</th>
        <th>Header 8</th>
        <th>Header 9</th>
        <th>Header 10</th>
        <th>Header 11</th>
        <th>Header 12</th>
        <th>Header 13</th>
        <th>Header 14</th>
        <th>Header 15</th>
        <th>Header 16</th>
        <th>Header 17</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>
</body>

</html>
```

```python
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    page.goto("file:///tmp/test.html")
    options = dict(
        path="/tmp/test.pdf",
        format="A4",
    )
    page.pdf(**options)
    browser.close()
```

**Describe the bug**

When the PDF is generated with default margins or with all margins set to 12mm the output generated by the Playwright is different from the out that could be seen on Chrome Print as PDF dialog. See the Playwright screenshot and Chrome screenshot.

In Chrome the full page content is visible until the left/right margin is set to 15mm. Then Chrome starts stripping the content.
Playwright can't fit the content to the page. I would like Playwright to be able to fit the page content with margins set to 12mm in this case.

![playwright-screenshot](https://user-images.githubusercontent.com/518956/122931347-17418d00-d36d-11eb-8c45-736cb7164794.png)

![chrome-screenshot](https://user-images.githubusercontent.com/518956/122931388-2294b880-d36d-11eb-8496-14e509d5c96d.png)

Attaching the PDF from Playwright  [test.pdf](https://github.com/microsoft/playwright/files/6694486/test.pdf)
and from Chrome [test-chrome.pdf](https://github.com/microsoft/playwright/files/6694493/test-chrome.pdf)

**Comment by fspin** [comment]
I had the same issue, but it works now on v1.12.3

**Comment by naro** [comment]
I have just tried the example in the issue description with Playwright 1.14.0 and it's still the same.

**Comment by yury-s** [comment]
This is what I get with 1.14.1: [test.pdf](https://github.com/microsoft/playwright/files/7086350/test.pdf) seems totally fine. The chromium version is 907428 (94.0.4595.0). What version are you on?

**Comment by naro** [comment]
@yury-s  Thanks for testing. I have tried again. In Python 3.8.5 in OSX, it works as you describe and I can generate the same PDF with all columns. Using latest Playwright 1.14.1 and "Playwright build of chromium v907428"

Since my issue is repeatable in a python:3.8.5-buster Docker environment which I use as a base for my project I tried it in that clean Docker container and reproduced the issue. I tried also in mcr.microsoft.com/playwright:focal docker container and that works fine. It seems the issue is hidden somewhere in the system dependencies :(

**Comment by yury-s** [comment]
Could be some  some system fonts or the build for Debian is slightly different, dunno. Note that we don't officially support Debian, we only test with Ubuntu for now.

Closing for now, feel free to reopen if there is anything else we could do.
