### ISSUE TITLE
[BUG][TypeScript] Hidden state does not get proposed in Visual Studio Code

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#7263]
See here:

![image](https://user-images.githubusercontent.com/17984549/122956249-1fa3c300-d381-11eb-9a49-5e4ecc46e099.png)

Not sure if its a TypeScript bug or if our types can be improved there. It's about prioritisation of the method type overloads afaik.

**Comment by cscheffauer** [comment]
Just tried to understand it and found out that in this line: 
https://github.com/microsoft/playwright/blob/master/src/client/page.ts#L268
the `channels.FrameWaitForSelectorOptions` have `& { state: 'attached' | 'visible' }` attached (which is a Typescript intersection). 

In the `FrameWaitForSelectorOptions` all 4 states (including hidden) are already defined properly:
https://github.com/microsoft/playwright/blob/master/src/protocol/channels.ts#L1798

Would it be fine to remove the intersection at the page definition? Any idea why this intersection is there?

**Comment by mxschmitt** [comment]
Hi thanks for digging into it. We generate the types independent of the TypeScript source. The relevant code are the waitForSelector calls here: https://github.com/microsoft/playwright/blob/master/utils/generate_types/overrides.d.ts#L55

These get then reflected in the types.

**Comment by cscheffauer** [comment]
Gotcha - so we would need to change this line to include all 4 states?
https://github.com/microsoft/playwright/blob/master/utils/generate_types/overrides.d.ts#L22

I could take a look at this if u like.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
