### ISSUE TITLE
[Question] Can `page.exposeFunction(name, ...)` use a long name with dots like `foo.bar.someFunc` as the name parameter?

### ISSUE THREAD

**Issue by imWildCat** [microsoft/playwright#7272]
Hello,

We're considering to mock the WebKit message handlers ([iOS example](https://diamantidis.github.io/2020/02/02/two-way-communication-between-ios-wkwebview-and-web-page)) like `window.webkit.messageHandlers.toggleMessageHandler.postMessage()`.

Could we use this long name on `window`? Or any workaround can be used in this case?

If we cannot use this name for [`page.exposeFunction()`](https://playwright.dev/docs/api/class-page#page-expose-function), we might have to use conditional build for the test target.

**Comment by aslushnikov** [comment]
> Could we use this long name on window? Or any workaround can be used in this case?

@imWildCat you can use `page.addInitScript` to re-expose the binding anywhere. For example:

```js
const playwright = require('playwright');

(async() => {
  const browser = await playwright.chromium.launch();
  const page = await browser.newPage();
  // expose function
  await page.exposeFunction('__sum_binding__', (a, b) => a + b);
  await page.addInitScript(() => {
    // re-expose binding at a new location
    window.foo = {
      bar: {
        baz: window.__sum_binding__,
      },
    };
  });

  // make sure everything works
  await page.goto('https://aslushnikov.com');
  console.log(await page.evaluate(() => window.foo.bar.baz(7, 8)));
  await browser.close();
})();
```

Does it work for you?

**Comment by imWildCat** [comment]
Thanks a lot, @aslushnikov!

It works perfectly!
