### ISSUE TITLE
[DOC BUG] CI instructions on .NET have broken links and outdated recommendations

### ISSUE THREAD

**Issue by timheuer** [microsoft/playwright#7277]
Doc point: https://playwright.dev/dotnet/docs/ci#github-actions

This section has two problems:
- [ ] Refers to using the Playwright Action and when you go to that page it says 
![image](https://user-images.githubusercontent.com/4821/123142991-e3b73f00-d40e-11eb-8990-35f9911156b3.png)
- [ ] Broken link to the test.yml file used in the repo that is intended to show an example

**Comment by mxschmitt** [comment]
👍 good point! We can remove all occurrences of the GitHub Action in our repositories since the Playwright CLI is enough.
