### ISSUE TITLE
[BUG] Some configuration options doesn't work

### ISSUE THREAD

**Issue by seunghunee** [microsoft/playwright#7289]
**Context:**
- Playwright Version: 1.12.2
- Operating System: Mac
- Node.js version: v14.15.1
- Browser: Chromium

**Code Snippet**

Playwright Test

```javascript
// playwright.config.js
module.exports = {
  use: {
    // Browser options
    timeout: 120000, // <--- doesn't work

    // Context options
    acceptDownloads: true, // <--- doesn't work
    viewport: { width: 1280, height: 720 },
    ignoreHTTPSErrors: true,

    // Artifacts
    screenshot: "only-on-failure",
    video: "retry-with-video",
  },
  globalSetup: require.resolve("./global-setup"),
};
```

Jest

```js
// package.json
{
   ...
  "jest": {
    "globalSetup": "<rootDir>/global-setup.js",
    "testTimeout": 120000
  }
}
```

**Describe the bug**

We've just migrate from Jest to Playwright Test.
When these options specified locally in a test file, it works.
But, when specified globally in the configuration file, it doesn't. (for timeout option, command line option doesn't work too)
Our some `page.waitForSelector()` failed for this reason.
We've got this error message.
```
page.waitForSelector: Timeout 30000ms exceeded.
```
Maybe it doesn't propagate for all the methods accepting timeout option.

**Comment by pavelfeldman** [comment]
Adding `//@ts-check` above might help you navigate the options. Only some of the very popular options are top level in `use {}`. The ones you are trying to set are actually lower level (under `launchOptions` and `contextOptions` inside `use`).

**Comment by seunghunee** [comment]
Oh, thank you. My mistake.
I've just tried this. But it doesn't work 😢 
Am I still got wrong?
```js
// playwright.config.js
module.exports = {
  use: {
    // Browser options
    launchOptions: {
      timeout: 120000,
    },

    // Context options
    contextOptions: {
      acceptDownloads: true,
    },
    ...
  },
};
 ```

**Comment by pavelfeldman** [comment]
Actually, it looks like I lied to you:
- `acceptDownloads` is promoted to the `use` level, so your original usage was good
- for `timeout`, if you want to set a timeout for your tests, it should be on the topmost level. The one you set now is a timeout for the browser launch.

I just ran a test:

```js
test('timeout', async ({ page }) => {
  await new Promise(() => {});
});
```

with config

```js
module.exports = {
  timeout: 2000,
};
```

And it timed out after 2 seconds.

**Comment by pavelfeldman** [comment]
How do you verify downloads are not accepted?

**Comment by seunghunee** [comment]
- `timeout`
We have a test which includes a very heavy calculation logic.
With putting the option on the topmost level in the configuration file, It works 🎉 
with:
```js
module.exports = {
  timeout: 120000,
};
```
But, sometimes I got error from another test:
```
    page.waitForSelector: Timeout 30000ms exceeded.
```
What I expected if failed with timeout: 
```
    page.waitForSelector: Timeout 120000ms exceeded.
```
This global timeout doesn't propagate other methods like `waitForSelector`?
Do I have to set `page.setDefaultTimeout` separately?

- `acceptDownloads`
I verify downloads are not accepted with the following error message
```
    .path: Pass { acceptDownloads: true } when you are creating your browser context.
```

**Comment by seunghunee** [comment]
For timeout, there is no global timeout right? #5495

**Comment by aslushnikov** [comment]
@seunghunee the timeout issue will be addressed by https://github.com/microsoft/playwright/pull/7312

**Comment by seunghunee** [comment]
@pavelfeldman What about `acceptDownloads`?

**Comment by seunghunee** [comment]
I've checked out v1.12.3, @aslushnikov 
It works ! Thank you ! 🎉

**Comment by akshayp7** [comment]
timeout must be specifies outside projects and accept downloads inside 

module.exports = {
  timeout: 300000,
  retries: 0,

  projects: [
    {
      name: `Chrome`,
      use: {
        browserName: `chromium`,

        // Test against Chrome
        channel: `chrome`,

        acceptDownloads: true

      }
    }
  ]
};

**Comment by akshayp7** [comment]
> @pavelfeldman What about `acceptDownloads`?
timeout must be specifies outside projects and accept downloads inside

module.exports = {
timeout: 300000,
retries: 0,

projects: [
{
name: Chrome,
use: {
browserName: chromium,

    // Test against Chrome
    channel: `chrome`,

    acceptDownloads: true

  }
}
]
};
