### ISSUE TITLE
[Question]How to Return All Requests Triggered When Using Page.waitForRequest()

### ISSUE THREAD

**Issue by xueshennnn** [microsoft/playwright#7295]
Hi,

I am trying to capture all requests triggered by page clicks that satisfy the filter condition. But I found only one single request is returned when I use page.waitForRequest(). Does anyone know how to get all the requests?

```
const result = await Promise.all([ 
                        page.waitForRequest(request => request.url().startsWith("https://browser.events.data.msn.com/OneCollector/") )
                        page.click("fluent-button[title='Close']"),
                      ]);
```

**Comment by aslushnikov** [comment]
@xueshennnn you need to use the `'request'` event

```js
const clickRequests = [];
const requestHandlers = request => clickRequests.push(request);
page.on('request', requestHandler);
page.click("fluent-button[title='Close']");
page.off('request', requestHandler);
console.log(clickRequests.length); // here are all the requests that happened during click
```

**Comment by xueshennnn** [comment]
Hi @aslushnikov ,
Thanks for your suggestion. But I found page.on can catch partial requests. Here is my test:

`
var events = [];
function requestCollect(request){
                if(request.url().startsWith("https://browser.events.data.msn.com/OneCollector/"))
                    events.push(JSON.parse(request.postData()));
            }
await page.on('request', requestCollect);
                    await page.click("fluent-button[id='SettingsDialog']"),  
                    await page.removeListener('request', requestCollect);
 console.log("now event size " + events.length);`

It returns 4 requests and has no the "click" action request, but when I manually click the button in web and check the requests in inspect, it has totally 12 requests and has the "click" action request.
![image](https://user-images.githubusercontent.com/86413332/123361932-750aea80-d5a2-11eb-9ec0-696ac38b586a.png)

**Comment by aslushnikov** [comment]
@xueshennnn would you mind sharing the URL so that I can look at this?

**Comment by xueshennnn** [comment]
@aslushnikov  Could you please try this one in anaheim browser?  https://ntp.msn.com/edge/ntp?locale=en-US

**Comment by xueshennnn** [comment]
@aslushnikov  Can I understand like this:
It seems the "requestHandlers " that is used to collect requests works async with page.click. So when removing the listener, requestHandlers is actually still in progress which caused some requests missed.

**Comment by dgozman** [comment]
@xueshennnn That's probably right. If your click action causes some requests asynchronously, you'll have to wait until some specific point - maybe a last request? Here is an example:

```js
var events = [];
function requestCollect(request){
  if(request.url().startsWith("https://browser.events.data.msn.com/OneCollector/"))
    events.push(JSON.parse(request.postData()));
}
page.on('request', requestCollect);
await Promise.all([
  page.waitForRequest('url-of-the-last-request-you-expect'),
  page.click("fluent-button[id='SettingsDialog']"),  
]);
page.removeListener('request', requestCollect);
console.log("now event size " + events.length);
```
