### ISSUE TITLE
[BUG] Webkit. Select don't have highlighted

### ISSUE THREAD

**Issue by ViaMay** [microsoft/playwright#7296]
**Context:**
- Playwright Version: "jest-playwright-preset": "^1.6.0",
- Operating System: Windows
- Node.js version: v14.17.1
- Browser: WebKit

**Code Snippet**
Problem only for WebKit.
Opening the page with the Selector.  View

```html
<select class="..."  placeholder="--Select--">
        <option value="">--Select Option--</option>
        <option value="OptionOne">OptionOne</option>
        <option value="OptionTwo">OptionTwo</option>
    </select>
```

This selector has the style of board highlighting
Selecte a option.
Expected result: the selector will be highlighted
Actual  result: the selector won't be highlighted
![image](https://user-images.githubusercontent.com/10914859/123263537-81476700-d512-11eb-998f-a11ddc3f790e.png)

For real Safari, Chome and for firefox work correctly
![image](https://user-images.githubusercontent.com/84974188/123262262-1cd7d800-d511-11eb-97cb-3fc4c32494af.png)

please tell me if you will fix this problem. Thanks in advance

**Comment by aslushnikov** [comment]
@ViaMay Looks like a bug to me! May I ask you what kind of testing you do so that you find this bug important?

**Comment by ViaMay** [comment]
@aslushnikov   I test to work web elemets like Button, link, select, textInput an other. It is visual testing: highlighted , color, themes, border

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
