### ISSUE TITLE
[Question] double-click the label and take a screenshot

### ISSUE THREAD

**Issue by ViaMay** [microsoft/playwright#7299]
This my code.  I double-click the label and take a screenshot. I see that the label is selection. BUT!  the screenshot is without this selection. what am I doing wrong?

```js
    const label = await inputPasswordModule.label;
    expect(await label.innerText()).toBe('Label Text *');
   const box = await label.boundingBox();
    await page.mouse.dblclick(box.x, box.y);
    image = await page.screenshot({ fullPage: true });
    expect(image).toMatchImageSnapshot();
```

**Comment by ViaMay** [comment]
And I have same problem for a select. If I try take a screenshot when a select is open for Webkit and firefox my select is close
![image](https://user-images.githubusercontent.com/10914859/123291112-3ede5400-d52b-11eb-8601-288791dd8bb3.png)

**Comment by aslushnikov** [comment]
> BUT! the screenshot is without this selection. what am I doing wrong?

@ViaMay This I could not reproduce - here's the snippet I tried:

```js
const { chromium, firefox, webkit } = require('playwright');

(async () => {
  const browser = await chromium.launch({headless: false});
  const page = await browser.newPage();
  await page.goto('data:text/html,<label>Label Text *</label>');
  const label = await page.$('label');
  console.log('Label text:', await label.innerText());
  const box = await label.boundingBox();
  await page.mouse.dblclick(box.x, box.y);
  await page.screenshot({path: './foo.png', fullPage: true});
  await browser.close();
})()
```

> And I have same problem for a select. If I try take a screenshot when a select is open for Webkit and firefox my select is close

@ViaMay Well, selects are native widgets, so you probably won't see an open select on a screenshot. I don't think we can do much here - this is inherent to browsers, so this behavior will be the same across all browser automation libraries.

**Comment by ViaMay** [comment]
@aslushnikov  dblclick works. Thank you!
