### ISSUE TITLE
[BUG] Snapshots are not captured if there is an animation at the beginning

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#7304]
**Context:**
- Playwright Version: 1.12.2
- Operating System: Windows only (works fine on mac)
- Node.js version: 12.14.1
- Browser: Chromium, Webkit

**Describe the bug**
There is an animation at the beginning when the page loads (i.e. when navigating to "XYZ" url). My test scenario involves:
- Click "Forgot Password"
- Navigates to different Page
- Enter email address
- Click Button (Intentionally failing the test on this step)

When capturing the snapshots in trace viewer, it only captures animation loading instead of capturing the actual actions. 
Please see the attached video.

https://user-images.githubusercontent.com/22205721/123350983-06318100-d511-11eb-92c0-465526f2172c.mov

**Comment by aslushnikov** [comment]
@Nav-2d could you please share a website where we can test this?

**Comment by Nav-2d** [comment]
@aslushnikov - Hi, I won't be able to share the url here but Pavel has the necessary details :)
