### ISSUE TITLE
reduce size

### ISSUE THREAD

**Issue by johnnliu** [microsoft/playwright#731]
Hi I'm trying to reduce the size of the bundle to deploy to AzureFunctions.  I think if I can bundle only 1 browser that'd work.

How do I go about making this settings change?

**Comment by JoelEinbinder** [comment]
You can use one of the packages `playwright-chromium`, `playwright-firefox`, or `playwright-webkit`. Each bundles only one browser.

**Comment by aslushnikov** [comment]
(Looks like it's solved - i'll close it! Feel free to shout if not!)
