### ISSUE TITLE
[Feature] Allow multiple contexts in codegen

### ISSUE THREAD

**Issue by roniemartinez** [microsoft/playwright#7316]
When using `codegen` to generate the script for multi-user environments (e.g. chat as described [here](https://playwright.dev/docs/multi-pages/#multiple-contexts)), we are currently running 2 separate `codegen` and then manually merge both scripts into one.

It would be easier if `codegen` support multiple contexts out-of-the-box. For example:

```bash
playwright codegen --contexts=2 ...
# or
playwright codegen --contexts="user,admin" ...
```

Now, some adjustments to other functionalities might be needed: `load-storage`, `save-storage`.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
