### ISSUE TITLE
[Feature] Include browser version of bundled browsers

### ISSUE THREAD

**Issue by weyert** [microsoft/playwright#7317]
Currently an auto-generated file `browsers.json` gets bundled with `playwright` packages which at first sight seem to define which commit/revision of the upstream browsers are included. 

I was wondering if it would be possible to include the human readable version of the browser that typically the `Browser.version()`-function would return?

My reason is that it would avoid to instantiate a copy of the browser to be collect the browser's version as I could just read this `browsers.json`-file to extract it from there. I have a PR [1] in Cypress repo which tries to add Playwright support to Cypress so it supports Webkit but now I need instantiate each browser and call `version()`. I was thinking the above change would avoid this but I can imagine there could be good reasons how it works now. If so, I could probably cache the results in somehow.

[1] https://github.com/cypress-io/cypress/pull/17002

**Comment by pavelfeldman** [comment]
`browser.json` is an implementation detail inside Playwright, so relying on its format would not be a great idea - we are very likely to break you.

**Comment by weyert** [comment]
Ah that makes sense :) I just tried to avoid needing to create the Browser instance to get the version. But maybe running it once and then cache it manually by writing it to disk. I don't think Playwright can download different versions when re-running `npm install`.

**Comment by pavelfeldman** [comment]
It will fetch new browsers every time Playwright is updated (once a month)
