### ISSUE TITLE
[Feature] Please add ability to execute system commands inside the tests

### ISSUE THREAD

**Issue by arkjel** [microsoft/playwright#7318]
Hi. I have had a hard time lately because I try to migrate from Cypress to Playwright but I cannot avoid an issue with running custom commands from CLI in tests. After sign up procedure I would like to confirm user in AWS Cognito tool. In Cypress it's easy because I can run `cy.exec` command like this:

Cypress.Commands.add("confirmUserSignUp", (email: string) => {
  cy.exec(`aws cognito-idp admin-confirm-sign-up --user-pool-id ${Cypress.env("AWS_COGNITO_USER_POOL_ID")} --username ${email}`);
});

Can we add the same functionality to Playwright or is there any other options to handle that issue? Thanks in advance!

Documentation: https://docs.cypress.io/api/commands/exec

**Comment by pavelfeldman** [comment]
Playwright runs inside the Node.js environment, so you can do anything you want, including running other programs:

```js
require('child_process').execSync(
    `aws cognito-idp admin-confirm-sign-up --user-pool-id ${Cypress.env("AWS_COGNITO_USER_POOL_ID")} --username ${email}`);
```

**Comment by pavelfeldman** [comment]
Look around [this method](https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options) to see more options.

**Comment by arkjel** [comment]
Thank you so much @pavelfeldman. It works!
