### ISSUE TITLE
[BUG] Output files are with non-existing source-maps

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#7325]
Either remove source-map annotation or add source-maps.

**Comment by pavelfeldman** [comment]
While files?

**Comment by mxschmitt** [comment]
Joel is familiar with the problem. The files in the lib/ folder when we push to npm.

**Comment by mxschmitt** [comment]
Closed for now since it was also pre the Babel change like that.

**Comment by mxschmitt** [comment]
Thats the warnings which I'm getting in Visual Studio Code while debugging:

![image](https://user-images.githubusercontent.com/17984549/125605195-c0419e52-b54b-401a-8527-6438320adaaa.png)
