### ISSUE TITLE
[Question] Get html content of rendered iframe?

### ISSUE THREAD

**Issue by abdes-zakari** [microsoft/playwright#7340]
How to get html content of rendered iframe?

![image](https://user-images.githubusercontent.com/30769602/123537756-538c3900-d731-11eb-9490-70d5b37864f7.png)

**Comment by mxschmitt** [comment]
In your case, doing the following should work for you:

```js
    const iframe = page.frame({
      name: "h5host"
    })
    console.log(await iframe.click("..."))
    console.log(await iframe.innerHTML("body"))
```
See here for more references:
- https://playwright.dev/docs/api/class-frame
- https://playwright.dev/docs/api/class-page#page-frame

**Comment by pavelfeldman** [comment]
https://playwright.dev/docs/api/class-frame#frame-content
