### ISSUE TITLE
[BUG] HAR: Body Content Race for Short-Lived Pages (Chromium-only) 

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#7348]
**Context:**
- Playwright Version: 1.12.1, 1.13.0-next-alpha-jun-28-2021
- Operating System: macOS, Linux
- Node.js version: v15.14.0
- Browser: Chromium

Add the following test to `har.spec.ts` and run the test 20 times via

```
npm run ctest -- --repeat-each 20
```

```ts
it.only('should include content for JavaScript redirects', async ({ contextFactory, server }, testInfo) => {
  server.setRoute('/js-redirect', (req, res) => {
    res.setHeader('Content-Type', 'text/html');
    res.end(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>Redirect to Empty</title>
      </head>
      <body>
        redirect content
        <script>
          window.location.href = "${server.EMPTY_PAGE}"
        </script>
      </body>
    </html>
  `);
  });

  const { page, getLog } = await pageWithHar(contextFactory, testInfo);
  await page.goto(server.PREFIX + '/js-redirect');

  const log = await getLog();

  const content = log.entries[0].response.content;
  expect(content.encoding).toBe('base64');
  expect(content.mimeType).toBe('text/html');
  expect(Buffer.from(content.text, 'base64').toString()).toContain('redirect content');

  expect(log.entries[1].request.url).toBe(server.EMPTY_PAGE);
});
```
**Describe the bug**

The response body of `/js-redirect` is not consistently captured in the HAR. In one set of 20 runs, 12 failed.

Given the following modification to harTracer.ts

```diff
diff --git a/src/server/supplements/har/harTracer.ts b/src/server/supplements/har/harTracer.ts
index b34c3fdb..295bb547 100644
--- a/src/server/supplements/har/harTracer.ts
+++ b/src/server/supplements/har/harTracer.ts
@@ -225,7 +225,7 @@ export class HarTracer {
       const promise = response.body().then(buffer => {
         harEntry.response.content.text = buffer.toString('base64');
         harEntry.response.content.encoding = 'base64';
-      }).catch(() => {});
+      }).catch((err) => { console.error(response.url(), err); });
       this._addBarrier(page, promise);
     }
   }
```

whenever the test fails, we get the following error when trying to get the body:

```
http://localhost:8907/js-redirect Protocol error (Network.getResponseBody): No resource with given identifier foundError
    at /Users/rwoll/code/playwright/src/server/chromium/crConnection.ts:174:56
    at new Promise (<anonymous>)
    at CRSession.send (…/code/playwright/src/server/chromium/crConnection.ts:173:12)
    at Response.getResponseBody [as _getResponseBodyCallback] (…/code/playwright/src/server/chromium/crNetworkManager.ts:284:43)
    at …/code/playwright/src/server/network.ts:392:21
```

I tried playing around with the `*bufferSize*` parameters at `Network.enable` PW calls, but that did not help. I'm assuming the error we're getting is from somewhere here https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/inspector/inspector_network_agent.cc;l=2078;drc=c14f6f4b9c44fe479a8d004576b42723b2a5feb6

and this comment https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/inspector/inspector_network_agent.cc;l=1322;drc=c14f6f4b9c44fe479a8d004576b42723b2a5feb6;bpv=1;bpt=1 caught my attention. I'm curious to know if the response never makes it into `resource_data_` member or if it is simply being destroyed by the time we get to it.

/cc @pavelfeldman

**Comment by rwoll** [comment]
Description updated with a link to example code in the form of passing and failing tests: https://github.com/microsoft/playwright/pull/7349

**Comment by rwoll** [comment]
@pavelfeldman I updated the title and description to better capture what the problem is. The charset bit turned out to not be relevant. Do those Chromium links at the end look roughly like the right spot to start poking at? It seems when I look at an equivalent page in Chrome with Network Inspector open (and protocol monitor) it's hitting the same error when trying to preview the response of the first request (`/js-redirect`).

**Comment by rwoll** [comment]
@pavelfeldman I added upstream tests: https://chromium-review.googlesource.com/c/chromium/src/+/2992465; however, based on their behavior, it's not clear to me whether Playwright should be calling and buffering getReponseBody sooner (since it looks from upstream test if you call it immediately after loadingFinished you are fine), or if Chromium should be keeping the response bodies around longer. See description in Chromium CL FMI.

**Comment by rwoll** [comment]
@mxschmitt Can you unassign this from me in GH? Unfortunately, it doesn't look like I will get around to this soon! ☹️ Sorry I wasn't able to be more helpful with this one!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
