### ISSUE TITLE
[Internal] chromium-with-symbols on Mac does not have symbols

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#7352]

**Comment by mxschmitt** [comment]
These builds are triggered manually via the dispatch event. See here: https://github.com/microsoft/playwright/actions/workflows/trigger_build_chromium_with_symbols.yml

I've triggered one for ToT.

**Comment by aslushnikov** [comment]
Auto-trigger for all Chromium changes

**Comment by pavelfeldman** [comment]
Ok, looks like we sorted this out. Having said that, Mac gave me no symbols.
