### ISSUE TITLE
[Question] Pass baseURL from the outside

### ISSUE THREAD

**Issue by sadik13** [microsoft/playwright#7358]
HI,
As per my requirement, I wanna access the below code instead of the full URL I wanna set the hostname into env variables outside of the tes.journey.js file and access it into my playwright code.

await page.goto('http://www.google.com');

I need like this below way, here I am using playwright scripts:

journey('Ensure elastic home page is correct', async ({ page }) => {
  step('load elastic homepage', async () => {
  const URL ="env path address of HOST";
  await page.goto(url);
});
});

so, plz suggested ur ideas of code for this.

Thanks in advance!!!

**Comment by mxschmitt** [comment]
Does this work for your use-case?

```js
const yourURL = `http://${process.env.YOUR_BASE_URL}`;
await page.goto(yourURL);
```

**Comment by mtt87** [comment]
Also in case you are wondering how to pass that env variable, you can run the playwright test with
```bash
YOUR_BASE_URL=https://google.com playwright test
```

**Comment by pavelfeldman** [comment]
You can use `process.env.YOUR_BASE_URL` inside your test if you specify it in env.

**Comment by akshayp7** [comment]
you can put it in json file(e.g. test.json) and access it in your script using key value pair like 
"baseURL": "https://www.google.com"

in your script then you can use below code

import fs from 'fs';

const login = JSON.parse(fs.readFileSync(`./test.json`, `utf8`));

async navigateToGoogle(): Promise<void> {
        await page.goto(login.baseURL);
 }

Hope this solves the issue.

**Comment by sadik13** [comment]
> you can put it in json file(e.g. test.json) and access it in your script using key value pair like
> "baseURL": "https://www.google.com"
> 
> in your script then you can use below code
> 
> import fs from 'fs';
> 
> const login = JSON.parse(fs.readFileSync(`./test.json`, `utf8`));
> 
> async navigateToGoogle(): Promise {
> await page.goto(login.baseURL);
> }
> 
> Hope this solves the issue.

if I am using the code as per ur suggestion I am getting the below error(i.e.Error: Cannot find module 'fs/promises')

```
my code snippet as per ur suggestion:-

import { journey, step, page } from '@elastic/synthetics';
import { deepStrictEqual } from 'assert';
import fs from 'fs';
import {promises} from 'fs'

journey('Ensure elastic home page is correct', async ({ page }) => {
  step('load elastic homepage', async () => {
    //const url =  process.NODE_ENV.url ;
    //await page.goto(url);
    const login = JSON.parse(fs.readFileSync(./test.json, utf8));

    async navigateToGoogle(): Promise {
    await page.goto(login.baseURL);
}
  });
});


```

**Comment by mxschmitt** [comment]
You don't need `import {promises} from 'fs'`. Once you remove it, it should work.

**Comment by sadik13** [comment]
After so much investigation its worked the below code for me to access the URL from outside of the file(test.json):

test.js:-
=======================
import { fs } from 'fs';

    const fs = require('fs');
    const rawdata = fs.readFileSync('./test.json');
    const std = JSON.parse(rawdata);
    await page.goto(std.baseURL);

test.json
==============
{ 
    "baseURL": "https://www.google.com"
}

**Comment by sadik13** [comment]
Thanks all for your suggestions for my query.
