### ISSUE TITLE
[Question] Is playwright.config.ts supported only for page fixture

### ISSUE THREAD

**Issue by akshayp7** [microsoft/playwright#7359]
Hi Guys,

Just had a doubt that all the configuration (e.g. acceptDownloads:true), provided in playwright.config.ts are picked up only by page fixture because if I pass browser fixture it doesn't work?. Do we have some config file for browser fixture as well or should we define all the configuration in newContext() ?

Thanks in Advance

**Comment by mxschmitt** [comment]
They are not picked up when you create new additional context instances via browser.newContext. What is your use-case for that? Do you need two isolated pages in a single test? You can create multiple pages via context.newPage() which includes the configuration values from the playwright.config.ts.

I will mark this as a feature-request, we could add a contextFactory to allow creating additional context instances with the configuration specified in the playwright.config.ts.

**Comment by akshayp7** [comment]
Got the answer, I was actually trying browser.newContext(). Thanks for help.
Currently I am using page fixture itself.

**Comment by akshayp7** [comment]
My Use case was like, In case of Emulation , we give values to browser like shown below, in below case we dont use page fixture, 
So is it a right approach to give browser and device value in and external json file and read it accordingly?

const browser = await chromium.launch({ headless: false });
const pixel2 = devices[`Pixel 2`];
const context = await browser.newContext({ ...pixel2 });
