### ISSUE TITLE
[Internal] page-drag tests fail on macOS 11.0

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#7362]

**Comment by mxschmitt** [comment]
Bisect range: https://chromium.googlesource.com/chromium/src/+log/10e0ac62c6863972849a48210922e10a9cc96f6f..0e4fd6359e7245b8c527bff6de55d7e162827b9a

**Comment by dgozman** [comment]
Upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1324819
