### ISSUE TITLE
[Feature] @playwright/test support for non-screenshot toMatchSnapshot expectations

### ISSUE THREAD

**Issue by dbjorge** [microsoft/playwright#7363]
Our team is interested in migrating from Jest to @playwright/test for a few of our end-to-end test suites (especially in https://github.com/microsoft/accessibility-insights-web). We're particularly excited for per-test retry support, screenshot/video on failure support, and test sharding.

Our tests currently use [Jest Snapshot testing](https://jestjs.io/docs/snapshot-testing) in several cases (for strings/objects, not screenshots). It would be easier for us (and for other Jest users in a similar situation) to migrate to @playwright/test if it supported the original forms of `toMatchSnapshot` that work with strings/objects, in addition to the existing `toMatchSnapshot` support for screenshots.

**Comment by pavelfeldman** [comment]
Could you give us an idea on the snapshots you use? Are those HTML markup, textual content, anything else?

**Comment by adambbn** [comment]
In my case I'm checking JSON data sent in POST request. Cool feature about Jest is that it allows "asymmetric matcher", for properties values we cannot predict:
```
expect(user).toMatchSnapshot({
    createdAt: expect.any(Date),
    id: expect.any(Number),
  });
```

**Comment by dbjorge** [comment]
@pavelfeldman The cases where our e2e tests use snapshots are:

* Frequently, for snapshotting rendered html markup of specific page components.
    * Where we do this, we first run it through a custom formatter that normalizes certain cases that are otherwise nondeterministic (a UI framework with generated element IDs, CSS module classNames with hash-based distinguishers, style attributes of certain absolutely positioned elements, etc).
    * The primary use case for these is to detect when we need to give extra scrutiny to a dependabot update
    * We've experimented with replacing these with screenshot-based snapshots (which would do a better job of detecting problematic css changes), but abandoned those experiments because there didn't seem to be a great way to deal with cross-OS differences in font rendering. Our developers don't all use the same OS for development, so we think we'd have needed to do something like forcing the screenshot tests to run only in docker containers, and force any dev making any UI change to spin up a dockerized build + test to update snapshots; we tried that, but reverted it because it introduced too much overhead to local development.
* Occasionally (in some tests of our electron app), we snapshot stdout/stderr/activity logs of other processes that our app communicates with. Particularly, our electron app shells out to `adb` for some operations and we snapshot its output.
* Rarely, for snapshotting "fingerprints" of accessibility failures (like [this example](https://github.com/microsoft/axe-pipelines-samples/blob/d7e5bfef12371ee354c196ade15c3194a5f66a0e/typescript-selenium-webdriver-sample/tests/index.test.ts#L92-L114)). We run accessibility scans with axe-core on our pages as part of our e2e tests and if we ever have known issues that we want to temporarily suppress, we use snapshots of "fingerprints" of those issues. These would be easy to replace with `toMatchObject` or similar.

We also have some cases where we export an entire html file; we use [jest-snapshot-file](https://github.com/satya164/jest-file-snapshot) for that, which provides a separate `.toMatchFile()` API that doesn't appear to require `.toMatchSnapshot()` to exist, so I'd expect it to work just fine already without any changes to playwright (but haven't tested that).

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
