### ISSUE TITLE
[Question] playwright test support component level integration test?

### ISSUE THREAD

**Issue by davidNHK** [microsoft/playwright#7375]
First of all, thanks for provide great tools for e2e testing 

But do it possible do thing like in cypress components test currently ?

https://docs.cypress.io/guides/component-testing/introduction

Just render the react component and assert the results?

**Comment by mxschmitt** [comment]
There is already a feature request similar to this one: #7148 So it seems like a duplicate for me.

**Comment by dgozman** [comment]
Closing in favor of #7148.
