### ISSUE TITLE
[BUG] Codegen doesn't record mobile

### ISSUE THREAD

**Issue by Voodu** [microsoft/playwright#7378]
**Context:**
- Playwright Version: 1.11.1
- Operating System: Ubuntu 20.04.2 LTS
- Node.js version: 16.3.0
- Browser: Chromium

**Describe the bug**

When entering codegen with ex. `npx playwright codegen https://www.wikipedia.org/`, opening developer tools and changing device to mobile there, recording of click/touch events doesn't work. Typing is correctly saved as `page.fill`, but clicks aren't recorded at all.

**Comment by mxschmitt** [comment]
You can pass your device type when launching codegen. Example would be:

```
npx playwright codegen --device='iPhone 11' wikipedia.com
```

Let us know if you are running into issues with it.

**Comment by Voodu** [comment]
@mxschmitt Thank you for the reply. That works.
