### ISSUE TITLE
[Question] Is it possible to change default "test-results" directory location?

### ISSUE THREAD

**Issue by arkjel** [microsoft/playwright#7379]
Hi guys!
Is it possible to change default `test-results` directory location? Now this directory can be created in the root path of the project but I want to change it to the custom `playwright/test-results`. There are screenshots, videos and traces. I cannot find this feature in the documentation. It'll be great if you could add a new property e.g. `testResultsDir` to the `playwright.config` file.

Regards
Arek

**Comment by mpuertao** [comment]
Hello. Yes you can. 

 Example in the playwroght.config.ts add: 
`reporter: [ ['junit', { outputFile: 'report/results.xml' }] ],`

**Comment by mxschmitt** [comment]
You can set the [`outputDir`](https://playwright.dev/docs/test-advanced#test-suite-options) in your config. Its by default `test-results` and these files should not be added to your version control system since they can contain screenshots for screenshot-on-failure, videos-on-failure or traces to debug failed tests.

If you are using [screenshot comparison](https://playwright.dev/docs/test-snapshots) via toMatchSnapshot, they are stored next to your test-files, these should be added to your Git repository.

**Comment by arkjel** [comment]
Ok, thanks!

**Comment by jvitoriano** [comment]
`const {
  devices
} = require('@playwright/test')
require('dotenv').config()

const config = {
  workers: 3,
  outputDir: './test/e2e/artifacts/test-failures',
  // globalSetup: require.resolve('./test/e2e/global-setup'),

  use: {
    baseURL: process.env.BASE_URL || 'http://localhost:3000',
    launchOptions: {
      slowMo: 50,
    },
    screenshot: 'only-on-failure'
  },

  projects: [{
      name: 'Chromium',
      use: devices['Desktop Chrome'],
    },

    {
      name: 'Firefox',
      use: devices['Desktop Firefox'],
    },

    {
      name: 'Safari',
      use: devices['Desktop Safari'],
    },
  ],

}

module.exports = config
`

**Comment by DarthVanger** [comment]
> You can set the [`outputDir`](https://playwright.dev/docs/test-advanced#test-suite-options) in your config. Its by default `test-results` and these files should not be added to your version control system since they can contain screenshots for screenshot-on-failure, videos-on-failure or traces to debug failed tests.
> 
> If you are using [screenshot comparison](https://playwright.dev/docs/test-snapshots) via toMatchSnapshot, they are stored next to your test-files, these should be added to your Git repository.

There's no `outputDir` option on the docs page you shared :(

Could you please explain how to change the default `test-results/` folder again pls 🙄 

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/6686679/188996429-1efd9dd0-0cdd-4533-aad7-5029afb051c2.png">

**Comment by mxschmitt** [comment]
> @mxschmitt 
> > You can set the [`outputDir`](https://playwright.dev/docs/test-advanced#test-suite-options) in your config. Its by default `test-results` and these files should not be added to your version control system since they can contain screenshots for screenshot-on-failure, videos-on-failure or traces to debug failed tests.
> > 
> > If you are using [screenshot comparison](https://playwright.dev/docs/test-snapshots) via toMatchSnapshot, they are stored next to your test-files, these should be added to your Git repository.
> 
> There's no `outputDir` option on the docs page you shared :(
> 
> Could you please explain how to change the default `test-results/` folder again pls 🙄 
> 
> <img width="1268" alt="image" src="https://user-images.githubusercontent.com/6686679/188996429-1efd9dd0-0cdd-4533-aad7-5029afb051c2.png">
> 



https://playwright.dev/docs/api/class-testconfig#test-config-output-dir
