### ISSUE TITLE
Typescript definitions only work from 'playwright-core' and not 'playwright'

### ISSUE THREAD

**Issue by lukeapage** [microsoft/playwright#738]
playwright the module does not include any typescript definitions, it just exports 'playwright-core' which does have typescript definitions.

so to use playwright in a project with typescript you have to import the core module.

Is it possible you can add a definition to 'playwright' telling typescript to get types from 'playwright-core' ?

**Comment by jperl** [comment]
A fix for this was merged. https://github.com/microsoft/playwright/pull/628
Types should be fixed in the next release.
