### ISSUE TITLE
[BUG] [@playwright/test] Timeout when using more than 2 workers

### ISSUE THREAD

**Issue by badsyntax** [microsoft/playwright#7381]
**Context:**
- Playwright Version: 1.12.3
- @playwright/test version: 1.12.3
- Operating System: MacOS
- Node.js version: 16.1.0
- Browser: Chromium
- Extra: 

**Describe the bug**

When using more than 2 workers I consistently get a `Timeout of 30000ms exceeded` error. Some of the tests are doing visual comparisons using  `expect(await page.screenshot()).toMatchSnapshot(..)`.

When using 2 or less workers, the tests consistently pass. I don't think the timeout is related to the server as i've tried 2 different server implementations. 

Please let me know if you require any additional information.

**Comment by JoelEinbinder** [comment]
you can run --remote-debugging-port=0 to get a new debugging port every time, but you will have to read the browser stderr to figure out what it is. If you override the `browser` fixture you could construct your own browser and pass in a unique port.

You can also use `context.createCDPSession` and try to hook it up directly to lighthouse, but that might take a bit of effort.

**Comment by badsyntax** [comment]
Thanks @JoelEinbinder!

Would something like this work:

```ts
test.describe('Lighthouse', () => {
  const port = getUnusedPort();
  test.use({
    launchOptions: {
      args: [`--remote-debugging-port=${port}`],
    },
  });
  test('should pass lighthouse', async ({ page }) => {
    // ...
  });
});
```

So I essentially set an unused port for every lighthouse test which should prevent conflicts when the lighthouse tests are run in parallel. It appears to work based on my initial testing...

**Comment by badsyntax** [comment]
I've changed approach and have followed your advice to override the `browser` fixture: 

```ts
const test = base.extend<{ port: number; browser: Browser }>({
  port: [
    async ({}, use) => {
      const port = await getPort();
      await use(port);
    },
    // @ts-ignore
    { scope: 'worker' },
  ],

  // @ts-ignore
  browser: async ({ port }, use) => {
    const browser = await chromium.launch({
      args: [`--remote-debugging-port=${port}`],
    });
    await use(browser);
  },
});
```

This works but results in a whole bunch of TypeScript errors hence the usage of `// ts-ignore`
