### ISSUE TITLE
[BUG] Importing package from CDN results in ENOENT error

### ISSUE THREAD

**Issue by BenPrt** [microsoft/playwright#7385]
**Context:**
- Playwright Version: "@web/test-runner-playwright": "^0.6.6",
- Operating System: WIndows/Linux
- Node.js version: 14.16.1
- Browser: Chromium

**Code Snippet / Describe the bug**

In my code, I import a library via our CDN : 
![Bug Playwright 1](https://user-images.githubusercontent.com/10711603/123844598-3ac28580-d8e1-11eb-9543-2f15b9246114.PNG)

But when I run our unit tests, it seems like Playwright tries to access to this file as it was declared as a relative path, and then obviously throw an ENOENT error :
![Bug Playwright 2](https://user-images.githubusercontent.com/10711603/123844887-912fc400-d8e1-11eb-8dff-08ad96fbf52e.PNG)

Is there a way to fix this?

**Comment by mxschmitt** [comment]
This is probably a bug in `@web/test-runner-playwright` which internally tries to convert the source-maps from the Chromium V8 engine over to the istanbul format and they don't filter for local files only.

I would recommend reaching out to them in [their issue tracker](https://github.com/modernweb-dev/web).
