### ISSUE TITLE
[BUG] If a test case fails, subsequent test case in describe block fails with error ' page.goto: Protocol error (Page.navigate): Cannot navigate to invalid URL'

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#7389]
**Context:**
- Playwright Version: 1.12.3
- Operating System:  Mac
- Node.js version: 14.17.0
- Browser: Google Chrome
- Extra: N/A

**Code Snippet**

Not Working
=========
```javascript
const { test,expect } = require('@playwright/test');

const delay = ms => new Promise(res => setTimeout(res, ms));
process.env.exampleURL = null;

test.describe('Test Example.COM Website', () => {

    test('Test Case #1 Example.COM Website', async ({page}) => {
        await page.goto('http://example.com');
        await delay(5000);
        process.env.exampleURL = await page.url();
        console.log('Page URL1: ' + process.env.exampleURL);
        expect(process.env.exampleURL).toBe('Test');
    });

    test('Test Case #2 Example.COM Website', async ({page}) => {
        console.log('Page URL2: ' + process.env.exampleURL);
        await page.goto(process.env.exampleURL);
        await delay(5000);
    });

});
```

Working
=========
```javascript
const { test,expect } = require('@playwright/test');

const delay = ms => new Promise(res => setTimeout(res, ms));
process.env.exampleURL = null;

test.describe('Test Example.COM Website', () => {

    test('Test Case #1 Example.COM Website', async ({page}) => {
        await page.goto('http://example.com');
        await delay(5000);
        process.env.exampleURL = await page.url();
        console.log('Page URL1: ' + process.env.exampleURL);
        //expect(process.env.exampleURL).toBe('Test');
    });

    test('Test Case #2 Example.COM Website', async ({page}) => {
        console.log('Page URL2: ' + process.env.exampleURL);
        await page.goto(process.env.exampleURL);
        await delay(5000);
    });

});
```

**Describe the bug**

If a test case fails in describe block, the subsequent test in the describe block fails with an error

> 
>  page.goto: Protocol error (Page.navigate): Cannot navigate to invalid URL
>     =========================== logs ===========================
>     navigating to "null", waiting until "load"
>     ============================================================

In Test Case 1 i am storing the value of URL in environment variable 'process.env.exampleURL' captured at run time, i am using this URL in Test Case 2. If Test Case 1 fails in asserting the URL, in Test Case 2, new context is opened but it doesn't load the URL i am passing. If Test Case1 pass, in Test Case 2, new context loads the URL correctly.

My use case is to test with authentication. After authentication, i capture the URL and pass it to subsequent test cases in a spec file.

Kindly suggest if i am missing something in understanding.

**Comment by JoelEinbinder** [comment]
This looks like it's working as intended. When a test fails, we restart the worker with the assumption that something potentially unrecoverable happened.

If you authenticate in a `beforeAll` then everything should work.

```ts
let authenticatedURL;
test.beforeAll(async({browser}) => {
  const page = await browser.newPage();
  authenticatedURL = ... // do something to get the url
  await page.close();
});
```
