### ISSUE TITLE
Webkit locale

### ISSUE THREAD

**Issue by haflinger** [microsoft/playwright#739]
Hi,

Is it possible to define a default locale in webkit browserContext ? 

Thanks,

**Comment by pavelfeldman** [comment]
Not yet, let me see how hard that would be.

**Comment by pavelfeldman** [comment]
Could you clarify which bits you would like to override? I would think you at least need:

- `Accept-Language` header that goes to the server
- `navigator.language` available to JavaScript

anything else? is locale-specific Date / time format essential?

**Comment by haflinger** [comment]
Thanks for the response. In my app i just use navigator.language  to define the user default language and i try to test it with E2E tests. It would be nice to be able to change this value. Date / time format is not essential to me.

**Comment by pavelfeldman** [comment]
`browser.newContext({locale: 'en-US'})` should work in WebKit now.

**Comment by rogerpadilla** [comment]
Still not working

**Comment by GeorgeM200** [comment]
Setting the locale for webkit to en-US or en-GB does not work in my case, I have the answers to the questions returned in German, on Chromium and Firefox it worked. 
I tried even locale: ' ' 
Coul I get some help here?

**Comment by aminaodzak** [comment]
why this is being closed, when there is no answer at all? I have the same issue.

**Comment by mia-zityhub** [comment]
same problem here

**Comment by IuliiaBondarieva** [comment]
Same problem. Input date format doesn't change by setting locale in any of possible ways.

**Comment by ASchmidtGit** [comment]
Same Problem here. Set browser.newContext({locale: 'en-US'}) but still get the german translations

**Comment by lucamug** [comment]
I think the issue is that `browser.newContext({locale: 'en-US'})` set `navigation.language` but most applications use `navigation.languages` (note the `s`). I think this is the correct way because `navigation.languages` contains the preferred languages of the user.

A work-around that I use for the moment is to set this value from the URL

`index.html?navigator.languages=ja,ko,en`

And then, inside the page:

```
// Function to get URL parameters
function getUrlParameter(name) {
    name = name.replace(/[\[]/, '\\[').replace(/[\]]/, '\\]');
    var regex = new RegExp('[\\?&]' + name + '=([^&#]*)');
    var results = regex.exec(location.search);
    return results === null ? '' : decodeURIComponent(results[1].replace(/\+/g, ' '));
}

// Get the 'navigator.languages' parameter from the URL
var languagesParam = getUrlParameter('navigator.languages');

// Split the parameter value to get an array of languages, or use default ['en'] if empty
var languagesArray = languagesParam ? languagesParam.split(',') : ['en'];

// Define the 'navigator.languages' property
Object.defineProperty(navigator, 'languages', {
    get: function() {
        return languagesArray;
    }
});
```
