### ISSUE TITLE
[Feature] Ability to override routes in reverse order

### ISSUE THREAD

**Issue by mortargrind** [microsoft/playwright#7394]
One of the very common patterns we have in our project for our integration/e2e level tests is having default/fallback routes. Basically the idea revolves around only focusing and mocking the routes that you are interested in for that specific test case/scenario that you are in and having default values/behaviors for the rest of the things as fallback. 

Of course we don't want to re-define these default/fallback routes over and over again for each test case; ideally we want to have 1 place to define all of them, and optionally override only a small subset of them specifically per test case if the test case demands it.

Currently in `@playwright/test` when we register multiple routes via `page.route(...)` and when one request can match multiple of these routes in theory, the match order will follow `First register first match` rule. So if you want to have a default behaviour for a route and override it only in 1 of your test cases, the final order of the `page.routes(...)` will have to be like this eventually:

```
page.route('/api/v1/my-crazy-endpoint', (route) => {
     // test case specific behaviour
     route.fulfill({
         status: 404,
         body: '404 response string'
     })
}) 

page.route('/api/v1/my-crazy-endpoint', (route) => {
     // the fallback/default
     route.fulfill({
         status: 200,
         body: 'default 200 response string'
     })
}) 
```

And the only way we were able to find for this final order of `page.route` statements is doing this inside of the each `it` callback we have:

```

  it('My unbelievable test case', async ({ page }) => {
    page.route('/api/v1/my-crazy-endpoint', (route) => {
         route.fulfill({
             status: 404,
             body: '404 response string'
         })
    })
    
    await registerDefaultRoutes({ page })

    await page.goto('.......')

    await page.click('text=My orders')
    ...
    ...
  })

```

As you can see this is not scalable since it forces every test author to not forget about calling the `registerDefaultRoutes` in the correct place while writing their test cases. What we'd like to have is as follows:

```
  // a global beforeEach for all the test cases in the project
  beforEach(() => {
    await registerDefaultRoutes({ page })
  })

  ...
  ...

  it('My unbelievable test case', async ({ page }) => {
    page.route('/api/v1/my-crazy-endpoint', (route) => {
         route.fulfill({
             status: 404,
             body: '404 response string'
         })
    })

    await page.goto('.......')

    await page.click('text=My orders')
    ...
    ...
  })

```

My suggestion is on top of having a route registration function that always adds to the **beginning** of the `_routes` array, having another similar one that adds to the start of it. So consumers can choose what to do depending on their needs easily.

Actually I already patched our `@playwright/test` using [patch-package](https://www.npmjs.com/package/patch-package) with a similar fix in our project in order to see this suggestion in action; I have updated the existing `page.route` to do what I want and add a new `page.routeToEnd` that behaves exactly same as the current `page.route`. My motivation is that I think adding to the the start of the `_routes` array is the more desired & expected behaviour for integration/e2e tests. So in our project all the fallback default routes are registered using `page.routeToEnd` and all the regular route registrations in `it` callbacks are using `page.route`.

Cypress had a similar issue when they introduced a new API for their routing mechanism on top of the old `cy.route`. Basically `cy.route` was behaving as what I am requesting here and the new `cy.intercept` was behaving how the current `page.route` behaves in terms of matching order. You can see the issues that this caused in this link: https://github.com/cypress-io/cypress/issues/9302

We are right now in the middle of phasing out Cypress and completely migrating into Playwright for integration/e2e testing and this was the biggest blocker for us. I think it will be a blocker for the rest of the teams in and and outside of our company. And I suspect many people won't even bother with patching the test library that they depend on just to make it work.

_**EDIT**:_ You can also find the patch below:

```diff --git a/node_modules/@playwright/test/lib/client/browserContext.js b/node_modules/@playwright/test/lib/client/browserContext.js
index 769633e..7b65459 100644
--- a/node_modules/@playwright/test/lib/client/browserContext.js
+++ b/node_modules/@playwright/test/lib/client/browserContext.js
@@ -340,6 +340,19 @@ class BrowserContext extends _channelOwner.ChannelOwner {
 
   async route(url, handler) {
     return this._wrapApiCall('browserContext.route', async channel => {
+      this._routes.unshift({
+        url,
+        handler
+      });
+
+      if (this._routes.length === 1) await channel.setNetworkInterceptionEnabled({
+        enabled: true
+      });
+    });
+  }
+
+  async routeToEnd(url, handler) {
+    return this._wrapApiCall('browserContext.routeToEnd', async channel => {
       this._routes.push({
         url,
         handler
diff --git a/node_modules/@playwright/test/lib/client/page.js b/node_modules/@playwright/test/lib/client/page.js
index b8dc73e..10b6460 100644
--- a/node_modules/@playwright/test/lib/client/page.js
+++ b/node_modules/@playwright/test/lib/client/page.js
@@ -543,6 +543,19 @@ class Page extends _channelOwner.ChannelOwner {
 
   async route(url, handler) {
     return this._wrapApiCall('page.route', async channel => {
+      this._routes.unshift({
+        url,
+        handler
+      });
+
+      if (this._routes.length === 1) await channel.setNetworkInterceptionEnabled({
+        enabled: true
+      });
+    });
+  }
+
+  async routeToEnd(url, handler) {
+    return this._wrapApiCall('page.routeToEnd', async channel => {
       this._routes.push({
         url,
         handler
diff --git a/node_modules/@playwright/test/types/types.d.ts b/node_modules/@playwright/test/types/types.d.ts
index 9f0baf3..5ac43f0 100644
--- a/node_modules/@playwright/test/types/types.d.ts
+++ b/node_modules/@playwright/test/types/types.d.ts
@@ -2445,6 +2445,8 @@ export interface Page {
    */
   route(url: string|RegExp|((url: URL) => boolean), handler: ((route: Route, request: Request) => void)): Promise<void>;
 
+  routeToEnd(url: string|RegExp|((url: URL) => boolean), handler: ((route: Route, request: Request) => void)): Promise<void>;
+
   /**
    * Returns the buffer with the captured screenshot.
    * @param options
@@ -5480,7 +5482,8 @@ export interface BrowserContext {
    * });
    * ```
    *
-   * Page routes (set up with [page.route(url, handler)](https://playwright.dev/docs/api/class-page#page-route)) take
+   * Page routes (set up with [page.route(ur
+   * l, handler)](https://playwright.dev/docs/api/class-page#page-route)) take
    * precedence over browser context routes when request matches both handlers.
    *
    * To remove a route with its handler you can use
@@ -5492,6 +5495,8 @@ export interface BrowserContext {
    */
   route(url: string|RegExp|((url: URL) => boolean), handler: ((route: Route, request: Request) => void)): Promise<void>;
 
+  routeToEnd(url: string|RegExp|((url: URL) => boolean), handler: ((route: Route, request: Request) => void)): Promise<void>;
+
   /**
    * > NOTE: Service workers are only supported on Chromium-based browsers.
    *
```

**Comment by pavelfeldman** [comment]
Thank you for the report, it makes total sense. While reversing the order is a breaking change, I don't think we documented the current behavior anywhere, so I think we can try claiming it was a bug. Let me talk to the team about it!

**Comment by mortargrind** [comment]
Obviously a breaking change wouldn't affect me in a bad way since I am the initial reporter but for the sake of doing things by the book and not putting other people in a bad situation here are my 2 cents (or 3 paragraphs) about this:

I guess you could do it without any breaking changes by keeping the current `page.route` as it is and introduce a `page.routeToTop` (name doesn't make any sense I know) method? Who ever is interested in what I am raising here can use that new method. 

_Because I am not sure if the current behavour is completely unnecessary/doesnt-make-any-sense or not_. That's why I had just patched it to keep both capabilities in case we'd need the current behavior in a different situation for ourselves. Of course for me there were no breaking change constraints since it was a private patch and I did the patch in a breaking way by changing the semantics of existing `page.route` and having an additional `page.routeToEnd` method for safety.

When you have enough data/idea about what is really needed or not and are ready to publish a version 2.0.0 for other reasons in the future; then you can re-implement this in a breaking manner if needed for the sake of a more clear and concise API. This way we could have the feature safely right now and you'd have the time & data to make a bigger decision later.

Anyway, thanks for looking into it.

**Comment by mxschmitt** [comment]
Needs to be changed int he following language ports:

- [ ] Python
- [ ] Java
- [ ] .NET

**Comment by PawelWesolowski** [comment]
I am not against this change but it broke my tests. Please document how it should be working.
My scenario was/is:
```
...
await page.route('**/api/more/specific/path**', ...
await page.route('**/api/other/specific/path**', ...
await page.route('**/api/**', ... //catch all the other
await page.goto(...
```
I just had to change the order to fix this "regression" but it is necessary to have a rule in Playwright for multiple possible matches (sth like "narrowing wildcards" feature). 
Cheers!
