### ISSUE TITLE
[Feature] Add web server support

### ISSUE THREAD

**Issue by KirProkopchik** [microsoft/playwright#7398]
Hi Guys,
My current test solution uses jest as test runner. I would like to migrate to the @playwright/test. But I don`t find the following functionality in the doc. Jest-playwright allows to launch the app before test running.
module.exports = {
    serverOptions: {
        command: 'yarn start',
        port: 3000,
        launchTimeout: 300000,
      },
  }
Is there same functionality in @playwright/test?

**Comment by mxschmitt** [comment]
We are currently working on it, stay tuned!
