### ISSUE TITLE
[Question] how can page.waitForNavigation({ url }) throw error immediately when url  is not match

### ISSUE THREAD

**Issue by eJayYoung** [microsoft/playwright#7399]
Hi, I have a puzzle problem, 

as the doc [Multiple navigations](https://playwright.dev/docs/navigations#multiple-navigations) usage. 
I'm going to test a page login with button click, after login success, page will redirect serval (which is not fixed) times.
```js
await Promise.all([
  page.waitForNavigation({ url: target }),
  page.click('text=login]'),
])
```
But when the final navigation url is not match `target`,  test error will wait util Timeout of 300000ms exceeded
![image](https://user-images.githubusercontent.com/18661091/123967154-a04d6980-d9e8-11eb-87c2-740530c74191.png)

so, the question is: how can page.waitForNavigation({ url }) throw error immediately when url is not match ?

Best Regards!

**Comment by pavelfeldman** [comment]
I don't think this is possible, as you say, the number of redirects is not fixed, so a new client-side redirect can happen at any moment. Suppose we throw immediately as you request, and after only 1 millisecond the page is navigated to the right url. So we should not have thrown and should have waited.

**Comment by JoelEinbinder** [comment]
To answer your exact question, this would wait for one navigation and check the url. But if you don't know how many navigations will occur before the url appears, then there is nothing we can do but time out waiting for it.

```ts
await page.waitForNavigation();
expect(page.url()).toBe(url);
```

**Comment by eJayYoung** [comment]
thanks for the answer
