### ISSUE TITLE
[BUG] Missing WebKit dependencies on GitHub Actions

### ISSUE THREAD

**Issue by arjunattam** [microsoft/playwright#7400]
I configured @playwright/test 1.12.3 to run on GitHub Actions, with `npx playwright install` to install browsers and their dependencies. While the tests for Chromium and Firefox run as expected, WebKit throws the following error. Is `npx playwright install` supposed to install these dependencies?

Agent OS: Ubuntu 20.04
WebKit build: v1492
[Run logs on GitHub Actions](https://github.com/arjunattam/react-todo/runs/2952605130?check_suite_focus=true)

```
      Install missing packages with:
          sudo apt-get install libegl1\
              libopus0\
              libwoff1\
              libharfbuzz-icu0\
              gstreamer1.0-plugins-base\
              libgstreamer-gl1.0-0\
              gstreamer1.0-plugins-bad\
              libopenjp2-7\
              libwebpdemux2\
              libenchant1c2a\
              libhyphen0\
              libgles2\
              gstreamer1.0-libav
```

**Comment by mxschmitt** [comment]
`npx playwright install` does not yet install the dependencies, we might change it in the future. For now you need to call `npx playwright install-deps`, see [here](https://playwright.dev/docs/cli#install-system-dependencies).

**Comment by arjunattam** [comment]
Thanks! I was following the playwright-test getting started instructions and assumed the install step was doing everything. Perhaps we could update the CI docs page with the `install-deps` step?

**Comment by mxschmitt** [comment]
I updated it recently in #7281 which should get reflected in the next release (not live yet under next). There we reference now to the CLI command to install the dependencies as the solution.

**Comment by mxschmitt** [comment]
Closing since there is no action item in it and all is implemented.
