### ISSUE TITLE
[Question] Full Screen , headless mode 

### ISSUE THREAD

**Issue by akshayp7** [microsoft/playwright#7402]
Hi,

   I tried using below configuration in headful mode for full screen which works perfectly, but in headless mode it seems like browser is like 800x600 , I checked it on the video recorded.
 viewport : null ,
 launchOptions: {
       args: [`--start-maximized`]
}

Later I just gave the viewport option as below which is working correctly with headful and headless mode.
viewport: { width: 1500, height: 700 }

Am I doing something wring while trying to maximize browser??

**Comment by JoelEinbinder** [comment]
Headless mode doesn't know anything about your display size, so it can't support start-maximized. Manually setting the viewport as you did is the correct way to go. It means your tests will be consistent even if your monitor changes size or your teammate tries to rum them on their computer.

**Comment by akshayp7** [comment]
Thanks for clearing doubt Joel.
