### ISSUE TITLE
Requesting 'testDir' to take in an string array instead of just string

### ISSUE THREAD

**Issue by kshrestha99** [microsoft/playwright#7403]
I currently have tests in multiple directories and want to indicate which directories to use based on testDir. So, if we have a way to allow string[] instead of a string, then I can provide multiple directories. Is this possible?

**Comment by JoelEinbinder** [comment]
Can you elaborate on why you have tests in multiple directories? My instinct would be that each folder would be different enough to warrant separate configs, and you would solve this by specifying an array of projects instead of an array of testDir.

**Comment by kshrestha99** [comment]
@JoelEinbinder Fair question...I have to run tests on different viewports. I have a bunch of tests that are only valid in the wide viewport, another set only valid for medium viewports, and another set of tests that are valid for both wide and medium viewports. Is there a better way to create config files for this scenario?

**Comment by JoelEinbinder** [comment]
You can do this today by having a project for each viewport+testDir combination. I get that could be a little awkward to write because you need a for-loop etc, but I hope it lets you keep working while we evaluate this feature.

**Comment by kshrestha99** [comment]
Thanks, I can try the for-loop for now but I do hope that others also see the flexibility if make testDir accept a string array. Thank you again!

**Comment by kshrestha99** [comment]
@JoelEinbinder Any updates on this? Is there anything I can do?

**Comment by playwright2021** [comment]
how do you use "can try the for-loop for now" to solve this typical problm? could you share?

**Comment by lionel-bijaoui** [comment]
I have git submodules for each project so a typical structure is like this (inside a project main folder of course) :
- "framework" folder
  - Is a submodule git
  - A reusable base between projects and modules can build upon it
  - Contain most of the base config for eslint/babel/whatever that can be extended or configured by the project
  - **Contain the config for playwright**
  - Contain a main node_module folder
  - Contain tests files among other things
- Modules folders (a project can have N modules depending on the need of the project)
  - Is a submodule git
  - Add reusable feature between projects
  - Contain specific test file for the module scope
- "src" folder
  - Project specific files
  - Might contain specific test files

I would like to use `projects` (in the meaning of playwright) to setup browser to use or some filtering system with `--grep`, but not use them for declaring test directories. 
By supporting an array of `testDir` I would be able to do that without worries. 
In the meantime, I have set up `testDir: "../"` and used `testIgnore` and `testMatch` to avoid `node_module` folder and only take some file extension into account as test files, but I'm guessing it slow down Playwright that need to recursively visit a lot of folder for nothing.

I hope this is adding more context and needs for this functionality.

Thanks a lot for your time and for Playwright, the best tool I have ever seen 👍

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by hmaddischool** [comment]
I just started using playwright. This feature would be perfect for my use case and really for all apps that leverage the micro-frontends technology. I have a folder for plugins and would love to isolate the plugins tests and keeps them in there respective folder.

**Comment by phproberto** [comment]
Same here. We use a setup like:

- /cms
   - /composables
   - /config
   - /tests
-  /plugin1
    - /composables
    - /config
    - /tests
- /plugin2
    - /composables
    - /config
    - /tests
- /plugin3
    - /composables
    - /config
    - /tests

Plugins can use and access cms composables and config internally to create data used by tests.

For those of you trying to find a way to achieve this an env setting allows it.

In my config I have:

```
const config: PlaywrightTestConfig = {
  testDir: process.env.PLUGIN ? `./${process.env.PLUGIN}/tests` : './cms/tests',
}
```

That allows me to execute it like:

```
# Run tests for plugin1
PLUGIN=plugin1 npx playwright test plugin1/tests

# Run tests for plugin2
PLUGIN=plugin2 npx playwright test plugin2/tests

# If no plugin is specified it executes the global/cms tests
npx playwright test cms/tests
``

That way I can share the same config for all the plugins.

**Comment by hsein-bitar** [comment]
I would like 'testDir' to take in an array, thank you
