### ISSUE TITLE
[Feature] Support multiple header values in Request/Response objects/Request interception

### ISSUE THREAD

**Issue by nexcode** [microsoft/playwright#7404]
```
browserContext.route('**', async (route, request) => {
    await route.fulfill({
        status: 200,
        headers: {'set-cookie': 'cookie'}, // headers?: {[p: string]: string}
    });
});
```

It is impossible to set several identical headers in the map, but cookies are set using multiple set-cookies headers.
NodeJS solves this problem like this: **{ [p: string]: string | string[] }**

Could it be worth doing the same here too?

**Comment by nexcode** [comment]
Same in https://playwright.dev/docs/api/class-request#request-headers
returns: **<Object<string, string>>** must be **<Object<string, string | string[]>>** or **<Object<string, string[]>>**

**Comment by mindplay-dk** [comment]
> It is impossible to set several identical headers in the map

Are you sure?

When I read from `response().headers()`, in the case of `set-cookie`, I get multiple header-values separated by `\n` - have you tried that?

> NodeJS solves this problem like this: **{ [p: string]: string | string[] }**

Please, not a type union - this requires `if`-statements and `typeof ` checks before you can do anything.

If we're going to fix this, let's have a proper `string[]` with new method-names and/or a proper header collection-type of some sort, with an API with suitable semantics to add/remove/replace headers.

If adding header values *is* supported with `\n`, it would be possible to make the collection-type optional, keeping existing API and semantics. (Although, in my opinion, it's kind of messy and confusing as-is.)

**Comment by mindplay-dk** [comment]
Looks like this is landing with #8638

**Comment by nexcode** [comment]
In v1.15 you can get multiple headers, but you still can't set multiple headers on `route.fulfill`

**Comment by Mattstir500** [comment]
I just had the same problem, here is a ugly workaround that works for me:
You can use different upper-lower case variants to set more cookies
e.g.:
```
headers: {
    'set-cookie': 'cookie1',
    'Set-Cookie': 'cookie2',
    'set-Cookie': 'cookie3',
    'SET-Cookie': 'cookie4',
    ...
}
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by serozhenka** [comment]
@pavelfeldman can you reopen this issue, please?
It seems like it's not fixed properly and dirty workarounds need to be applied to make this work

**Comment by stockiNail** [comment]
+1

> [@pavelfeldman](https://github.com/pavelfeldman) can you reopen this issue, please? It seems like it's not fixed properly and dirty workarounds need to be applied to make this work
