### ISSUE TITLE
[Feature] Expect in playwright inspector

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright#7405]
The playwright inspector instruments all of the playwright api, but we could also instrument the expect api to give better messages when something goes wrong.

See #7397 for more context

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
