### ISSUE TITLE
[Feature] Include and export the SHA-256 of expected downloaded browsers

### ISSUE THREAD

**Issue by joeljeske** [microsoft/playwright#7411]
It would be helpful include the SHA256 sum of the browsers that are downloaded. That would allow the checking to ensure that the proper binary was downloaded as expected. 

Additionally, this would aid in integration with other tools that may have download caches to prevent duplicated downloads.

**Comment by JoelEinbinder** [comment]
How would you want this exposed?

**Comment by joeljeske** [comment]
@JoelEinbinder, it would seem nice if the public "browsers.json" doc at the top of the package was extended like this:

```ts
{
  "browsers": [
    {
      "name": "chromium",
      "revision": "891964",
      "installByDefault": true,
      "binaries": {
          "ubuntu18.04": {
              "downloadURL": "https://playwright.azureedge.net/builds/chromium/891964/chromium-linux.zip",
              "sha256": "b524720777280c86b14a86ed1e58fa361ac390ff4fcdc45847de23c96fb716fc"
           },
           "mac10.14": {
               "downloadURL": "https://playwright.azureedge.net/builds/chromium/891964/chromium-mac.zip",
               "sha256": "097982525f6ebe584e9872c2eb84f01e81573d74766a66070fdd0cdd0e8791ce"
           }
      }
    }
   ]
}
```

I am interested in this being exposed as I want to create a playwright testing rules to work well within Bazel. Theres a couple pieces of functionality that I would want to provide: 

1. Bazel controls the downloading of the browser binaries for better performance and caching in a controlled environment instead of in a global cache
2. Only the binaries that are required, (based on browser used in the test and the platform the test is running on) would be downloaded and provided to the test run for optimal performance

By providing the download information in an accessible json doc or within an easy node-js api, these rules would be able to automatically download the appropriate browser and cache it based on the SHA256. It is important to note that Bazel has good capabilities of working remote build/test farms, which means that there is a need to be aware of other browser binaries that may not be compatible with the "host" system on which this information is gathered: A host MacBook may need to download and prepare a linux browser binary that will run on a different machine. 

Sometimes, this issue is worked around in other tools by either:
1. Hardcoding common versions of the relevant binaries for the relevant systems.
OR 
2. Asking the consuming user of the playwright bazel tools to provide the URLS and SHA256 of the relevant browser binaries. 

Given that playwright should really only use the exact browser versions that it ships with, AND the sheer number of different binaries for all the supported browsers and platforms, neither of those options is very good; it would be very helpful to do this automatically.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
