### ISSUE TITLE
[Feature] - Delete a certain cookie instead of clear all cookies

### ISSUE THREAD

**Issue by PeterNgTr** [microsoft/playwright#742]
Based on the docs here https://github.com/microsoft/playwright/blob/master/docs/api.md#class-browsercontext we cannot delete a certain cookie, is there any consideration to have that kind of feature?

**Comment by pavelfeldman** [comment]
We could add that. The cookie would be identified by the secure+domain+path+name key. Could you share the use case for the individual cookie removal?

*(You can work around it today via getting all cookies, deleting all cookies and restoring everything but one cookie in case your context is not huge)*

**Comment by PeterNgTr** [comment]
@PavelBansky I'm not really sure if there are many users want to manipulate the cookies but it would be nice to have an option to delete a special cookie key. Thanks!

**Comment by PavelBansky** [comment]
@PeterNgTr : wrong Pavel

**Comment by PeterNgTr** [comment]
> @PeterNgTr : wrong Pavel

hey man, sorry for the wrong mentioned.

**Comment by mxschmitt** [comment]
I would try to add this functionality.

**Comment by zelmarou** [comment]
Hi All,

I was thinking about this feature - should not we try do to something like delete all cookies matching a certain set of criteria. 
What would be the point of limiting the scope to delete only one cookie ?
Would be something like

```
cookies.DeleteWhere((cookie) => cookie.domain = "xxx")
cookies.DeleteWhere((cookie) => cookie.domain = "xxx" && cookie.path == "zzz" )
```

**Comment by nrayburn-tech** [comment]
@pavelfeldman, I was looking into adding this. I am not super familiar with how playwright interfaces with Chromium, so correct me if I am wrong anywhere.
Using docs from here, https://chromedevtools.github.io/devtools-protocol/tot/Storage/, there doesn't seem to be a method  for `Storage` to delete an individual cookie.  `Page` and `Network` have relevant methods to delete an individual cookie.  I don't know if those are applicable though.
The other option would be like you mentioned, delete all cookies and restore the others.  This could be created and exposed to the users as a method just for convenience and would internally still use `clearCookies` and `add/setCookies`.
Any thoughts?

**Comment by pavelfeldman** [comment]
> The other option would be like you mentioned, delete all cookies and restore the others. This could be created and exposed to the users as a method just for convenience and would internally still use clearCookies and add/setCookies.

That would probably work.

**Comment by pavelfeldman** [comment]
First of all, thank you for filing this issue. We appreciate your input, in many ways Playwright is based on it. This particular feature request didn't get enough stars for us to prioritize the work on it and hence is being closed. We are a relatively small team and we need to prioritize aggressively to deliver support and new features to you.
