### ISSUE TITLE
[Question] Wait for other async functions to finish before the page context was destroyed

### ISSUE THREAD

**Issue by Tverous** [microsoft/playwright#7440]
Hi, all

I have some async functions that will collect data from the DOM tree when navigates to a new page during the tests. 

However, errors will occur when the page is redirected to another url or closed before these async functions are finished. 
Since the page context has been destroyed, therefore, no DOM data from the page can be retrieved.

This can be solved by doing some examinations before every route's request and before the page was destroyed :

``` typescript
await page.route(new RegExp('.*', ), async (route) => {
    /* examination with even sourcings */ 
    route.continue();
});


await use(page);

/* examination with even sourcings*/ 

}, {scope: 'test'}]

```

However, this will significantly slow down the tests.

Other solutions include inserting some waiting functions within the testcase, but this will bring many inconveniences during developments. 

And I wonder if there are any other better ways to solve the problem.

Any suggestions are welcomed.

Thank you.

**Comment by mxschmitt** [comment]
What kind of errors do come up where? Could you try using `route.continue.catch(() => {})` instead? this should prevent these errors from happening.

(might also make sense to fix it in Playwright to prevent it in the future if your errors come from continue)

**Comment by Tverous** [comment]
The errors are not raised by the router but other customized async functions for collecting data from the DOM tree.  

For instance:
``` typescript
page.on('load', async () => {
    let elemHandles = await page.$$('input');
    await page.evaluate(async ({ elemHandles }) => {
        /* do stuff with elemHandles */
    }, { elemHandles });
});
```

The errors raise from the DOM parser whenever the page is being navigated to another url since the original page context has been destroyed.

**Comment by pavelfeldman** [comment]
Thanks for the report! Your use case and request are clear.

Note to self: can we throttle the navigations while evaluates are in flight?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
