### ISSUE TITLE
[BUG] when maxFailures is reached it does not terminate the other workers

### ISSUE THREAD

**Issue by Daemos87** [microsoft/playwright#7444]
**Context:**
- Playwright Version: @playwright/test@^1.12.3
- Operating System: mac big sur
- Node.js version:  v14.16.1
- Browser: all
- Extra: N/a

I'm running 3 sample tests with the following configuration 

``` typescript
const config: PlaywrightTestConfig = {
  maxFailures: 1,
  workers: 2,
  use: {
    headless: true,
  },
  reporter: [["list"], ["json", { outputFile: "report.json" }]],
  timeout:40000,
  outputDir:`${process.cwd()}/output`
}
```

I'm noticing that the "maxFailures" option have a strange behaviour running on multiple workers, the runner seems to wait for every worker to complete tests, even after the max failure count is reached, but then all subsequent tests are marked as "skipped".

Here's my console output for an ad hoc test run aimed to reproduce the issue. 

```
Running 3 tests using 2 workers

    long.test.ts:5:5 › [chromium] long tests long test: 
  x 1) short.test.ts:3:1 › [chromium] short test (10ms)
**long test finished**
    long.test.ts:12:5 › [chromium] long tests another long test: 
another long test finished


  1) short.test.ts:3:1 › [chromium] short test =====================================================

    Error: expect(received).toBeFalsy()

    Received: true

      2 |
      3 | test("short test",()=>{
    > 4 |     expect(true).toBeFalsy()
        |                  ^
      5 |     console.log('short test finished')
      6 | })

        at /Users/agiangrande/Documents/repo/issue-playwright/short.test.ts:4:18
        at FixtureRunner.resolveParametersAndRunHookOrTest (/Users/agiangrande/Documents/repo/issue-playwright/node_modules/@playwright/test/lib/test/fixtures.js:241:16)
        at WorkerRunner._runTestWithBeforeHooks (/Users/agiangrande/Documents/repo/issue-playwright/node_modules/@playwright/test/lib/test/workerRunner.js:290:39)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)


  1 failed
    short.test.ts:3:1 › [chromium] short test ======================================================
  2 skipped
```

[here's](https://github.com/Daemos87/issue-playwright.git) a repo to reproduce the issue, just clone, yarn install, yarn test  

**Expectation**

I think the runner should stop all workers immediately after the max failure count is reached, or at least it shouldn't mark a test as skipped if it was effectively executed.

**Comment by avodovnik** [comment]
This is semi-expected behaviour. The `maxFailures` is currently tracked on a per-worker basis. You can verify this behaviour by changing the number of workers to 1, and failing the first of your `long tests`. You'll see none of them get executed. 

This should be made clear in the docs - we'll update that.
