### ISSUE TITLE
[Feature] Use codegen tool with wsEndpoint argument

### ISSUE THREAD

**Issue by oneassasin** [microsoft/playwright#7449]
Need to use codegen tool with wsEndpoint. How can I make that? 
I want to use playwright with MultiLogin (or indigo/incogniton) antidetect browser and generating code for automatization processes.

**Comment by pavelfeldman** [comment]
Could you share more on your scenario?

**Comment by oneassasin** [comment]
I use antidetect browser for working with google/facebook from multiple accounts (multiloginapp in my case) 
And i cant use common browser (chromium, for example) because fb/google keeps track of browser fingerprint
without codegen I need to write code manually, but with codegen with wsEndpoint I can make that more simply

**Comment by oneassasin** [comment]
any news?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
