### ISSUE TITLE
master fails to build

### ISSUE THREAD

**Issue by jperl** [microsoft/playwright#745]
<img width="1649" alt="Screen Shot 2020-01-29 at 10 48 25 AM" src="https://user-images.githubusercontent.com/1136652/73382572-fe6e9e00-4284-11ea-94cc-1b54fefd5cbf.png">

Reproduction steps:

Checkout https://github.com/microsoft/playwright/commit/fc93b886d9a037a9214e17e298002335122d1054

`npm run build`

Relates to https://github.com/microsoft/playwright/pull/692

I would be happy to add a test that tries to build and use the types in an external project or I could add a test in typescript?

**Comment by jperl** [comment]
Closing temporarily, I need to check if I generated the protocols.

**Comment by jperl** [comment]
My mistake, I forgot to run `npm run prepare` 🤦‍♂. It build properly.

**Comment by aslushnikov** [comment]
@jperl I believe if you do `npm install` after checking out the revision, it should run prepare for you (and install all the correct deps!)
