### ISSUE TITLE
[BUG] Error displayed in a console after closing the Trace Viewer

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#7456]
**Context:**
- Playwright Version: 1.12.3
- Operating System: Windows
- Node.js Version: v14.16.1
- Browser: Chromium [channel: 'chrome']

**Code Snippet**

```javascript
npx playwright show-trace trace.zip
```

**Describe the bug**

I use the trace log in my test. In order to open the trace, I perform the code as displayed above in the Code Snippet part.
The trace displayed as well.
When I close the trace viewer - I get the following error (see more details in the attached video):
'ERROR: The process "4436" not found.'
The trace closed as well.

https://user-images.githubusercontent.com/52656401/124379732-6074d380-dcc1-11eb-94e7-0e586db18eeb.mp4

**Comment by mxschmitt** [comment]
I was able to reproduce it, currently on Windows when we kill the process it leads to an error when the process does not exist anymore. Related to [that](https://superuser.com/questions/232703/taskkill-exe-dont-throw-an-error-if-the-process-is-not-running/630799). process.exit(<pid>) does not throw on Unix based operating systems.
