### ISSUE TITLE
[Question] using msw as api mocking in test

### ISSUE THREAD

**Issue by yanirmanor** [microsoft/playwright#7461]
Is it possible to use mswjs as rest/graphql mocking in playwright test?

**Comment by mxschmitt** [comment]
Hi, if they make it possible to mock it using a proxy (which you can set on Playwright side when creating a context), then it should be no problem. From a quick research, it seems like they don't support it, maybe open a feature request for it on their side.

**Comment by mxschmitt** [comment]
Closed as part of the triage process. This is a feature which most likely should get implemented by msw/a wrapper package, since Playwright has the API to provide support for it.
