### ISSUE TITLE
[Feature] Playwright get long polling response body

### ISSUE THREAD

**Issue by AmosDinh** [microsoft/playwright#7466]
Reposting this from Stackoverflow:
Is it possible to get the response body "stream" of a long polling response using `page.on('response')`? 
The content type of the specific response is `'text/event-stream'`.
The code stops("freezes") at `await response.body()`, is there some solution in Python?
I would be grateful for solutions in other languages as well.
Thank you

**Comment by yury-s** [comment]
With current implementation you can only get full body of the response after the request has finished (e.g. EventSource has been closed). `response.body()` will block until the request is finished which may never happen in case of `'text/event-stream'`. Getting the response data before the request is finished is possible but would require a new api on the Response (something like `Response.bodyAsStream`) so changing this issue to a feature request.

For now subscribing to `EventSource.onmessage` via javascript is your best bet if you can't wait until the request is finished.

**Comment by AmosDinh** [comment]
Thank you

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
