### ISSUE TITLE
[BUG] playwright-test-runner skips second and subsequent calls of a re-used function in a single test suite file

### ISSUE THREAD

**Issue by cullman1** [microsoft/playwright#7475]
**Context:**
- Playwright Version: 1.12.3
- Operating System: Windows 10 Pro - 21H1 -19043.1081
- Node.js version: 12.3 /also node-fetch 2.6.1
- Browser: All
- Extra: Runs within Docker v 20.10.7

**Code Snippet**

The code worked fine with jest, but when transferred to playwright-test-runner, it doesn't work in the same way. I have the following helper function:

``` 
import { BASE_URL } from "../shared/constants";
import { Page } from "playwright";
import { getLoggedInContext } from "./auth";
import { expect, test } from "@playwright/test";

export function testScreenshot({ name, url }: { name: string; url: string }) {
  test(name, async ({ browser }) => {
    const page = await getLoggedInContext(browser, true);
    await page.goto(`${BASE_URL}/${url}`);
    await page.waitForLoadState("networkidle");
    const screenshot = await page.screenshot({
      path: "/test-results-originals/" + name + ".png"
    });
    expect(screenshot).toMatchSnapshot(
      "../../test-results-originals/" + name + ".png"
    );
  });
}
```

And a single test suite file, for example (note this is artificial - normally the links are all the same, and the tests are all testing specific aspects of one page, but I note it still fails when it goes to different URLs as below):

```
import { testScreenshot } from "../../../../../shared/screenshotTestHelpers";
import { SCHOOL_ID } from "../../../../../shared/constants"

testScreenshot({
  name: "Headline Reports",
  url: `schools/${SCHOOL_ID}/reports/headlines`
});
testScreenshot({
  name: "Ladder Reports",
  url: `schools/${SCHOOL_ID}/reports/ladder`
});
```

**Describe the bug**

The test-runner will show the name of the report is "Ladder reports" both times, and it will run one and skip the other. 

```Running 2 tests using 1 worker

  ✓ ..\shared\screenshotTestHelpers.ts:10:3 › [project5] Ladder Reports (3s)
  ✓ ..\shared\screenshotTestHelpers.ts:10:3 › [project5] Ladder Reports (2s)


  1 skipped
  1 passed (5s)
```

It looks like it's doing some sort of lookup before it runs. I can get around it by renaming testScreenshot and putting it in a separate helper, so I'm calling testScreenshot1 from first helper then testScreenshot2  from second but that is complete overkill and when you have 5 calls to the same function in one file.

Context: [from Slack](https://playwright.slack.com/archives/CSUHZPVLM/p1625500760135400)

**Comment by dgozman** [comment]
I think this was fixed in #7243, and should get into next v1.13 release. Please comment here if you can reproduce it in v1.13 (or `@playwright/test@next` if you try before 1.13 is out).
