### ISSUE TITLE
[BUG] "timeout" annotations and helpers do not affect fixtures and before* hooks

### ISSUE THREAD

**Issue by mlmmn** [microsoft/playwright#7479]
**Context:**
- Playwright Version: 1.12.3
- Operating System: Mac, official docker image
- Node.js version: 16.3.0, dunno which is in docker
- Browser: all

**Code Snippet**

```javascript
import { test as base, expect } from '@playwright/test';

const test = base.extend<{ fixture: string }>({
  fixture: async ({}, use) => {
    await new Promise<void>((resolve) => {
      setTimeout(() => {
        console.log('resolve promise');
        resolve();
      }, 31000);
    });

    await use('this is a fixture');
  },
});

test('timeout annotation issue', async ({ fixture }) => {
  test.setTimeout(60000);
  console.log('test: ', fixture);

  expect('doesntmatter').toEqual('doesntmatter');
});

```

**Describe the bug**

When preparing an async fixture which time to resolve exceeds the global `timeout` setting, calling either `test.slow()` or `test.setTimeout()` has no effect on increasing the test timeout and leads to playwright error

```sh
Running 1 test using 1 worker

  x 1) timeout.spec.ts:21:3 › [chromium] description timeout annotation issue (30s)


  1) timeout.spec.ts:21:3 › [chromium] description timeout annotation issue ========================

    Timeout of 30000ms exceeded.

  Slow test: timeout.spec.ts (30s)

  1 failed
    timeout.spec.ts:21:3 › [chromium] description timeout annotation issue =========================
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mxschmitt** [comment]
You can set the global timeout in the [`playwright.config.ts`](https://playwright.dev/docs/next/test-configuration#testing-options) or pass it via a CLI argument `--timeout 120000`, could you try that?

**Comment by mlmmn** [comment]
@mxschmitt Yes, I eventually ended up with setting the global timeout in the `playwright.config.ts` but I feel like this makes selective test timeouts pointless. I mean, when a test that is "fast" is about to get failed for whatever reason, Playwright will unnecessary wait for the global timeout which was set only for those "slow" tests.

To me this is either a bug or an undocumented limitation.

**Comment by mxschmitt** [comment]
The reason that it does not work is that the fixture runs actually before running the test. It gets detected by the object which you pass into the function, then it sees a key with the value "fixture" and runs it. This means test.setTimeout does not run before the fixture.

Moving test.setTimeout outside the test "should" work, since it's then on the suite level and runs/sets it before the fixture runs.

I agree that the way how fixtures run and when should be documented, will check later if we already have it somewhere or it needs to be added.

**Comment by dgozman** [comment]
@mlmmn You can use `testInfo.setTimeout()` from the fixture to change the timeout for any test that uses this long-running fixture. Below is the original snippet with a small tweak. Does that work for you?

```js
import { test as base, expect } from '@playwright/test';

const test = base.extend<{ fixture: string }>({
  fixture: async ({}, use, testInfo) => {
    testInfo.setTimeout(testInfo.timeout + 31000);   // Here we go, give it 31 more seconds!

    await new Promise<void>((resolve) => {
      setTimeout(() => {
        console.log('resolve promise');
        resolve();
      }, 31000);
    });

    await use('this is a fixture');
  },
});

test('timeout annotation issue', async ({ fixture }) => {
  console.log('test: ', fixture);
  expect('doesntmatter').toEqual('doesntmatter');
});
```
