### ISSUE TITLE
[Feature] Possibility to define listen address and path for launchServer() method

### ISSUE THREAD

**Issue by zdm** [microsoft/playwright#7481]
Hi.

We want to use playwright as service for apps in out cluster. For this purpose we need to launch service on "0.0.0.0" and with some static path (currently random on each server launch), so our services will have persistent remote endpoint to connect.

Is it possible to add new options for the launchServer() method, which will be passed to the `ws.Server`:
- `host` specify ip address to listen, default 127.0.0.1;
- `path` specify path, default randomly generated.

Thank you.

**Comment by avodovnik** [comment]
Can you help us understand the use case for this? Is there a reason that running it on each node is not acceptable?

**Comment by zdm** [comment]
1. We don't need to run it on each node, what is the sense? Better to use it as shared service.
2. With the current limitations we are unable to run it in separated docker container. We need to include playwright code and browser instance to the each container, which is use it. This affects containers size and affect performance, because instead of just run new context we need to run whole browser in each container.

**Comment by zdm** [comment]
Any news?

**Comment by zdm** [comment]
Sorry for disturbing but will you implement this, I need to know?
What is the sense of this restriction? Give users possibility to use playwright as the need.
Thank you.

**Comment by zdm** [comment]
Could you please, at least, add possibility to specify path instead of generate it randomly?
This is prevents to use playwright as standalone service.

**Comment by mxschmitt** [comment]
A custom path seems implemented in https://github.com/microsoft/playwright/commit/25a4c7b3dfd64df47c18a829719a7e3d87a18ab1

**Comment by zdm** [comment]
Yes, thanks.
But do you know is this feature released or not?

**Comment by zdm** [comment]
Seems, that not yet.

**Comment by mxschmitt** [comment]
It was merged 16 hours ago, so no. But you can use it via the next releases: `npm install playwright@next`
