### ISSUE TITLE
[Feature]: Set localstorage on values retreived in test.beforeEach

### ISSUE THREAD

**Issue by florianbepunkt** [microsoft/playwright#7483]
I test a multiplayer game app with playwright. For each test I need to create a new match and the app uses localstorage to retreive the match id and some match auth info (that is unique for each match).

So I need to set the local storage for each test based on values retreived in test.beforeEach. I think this use case is not very special.

Problem: It is currently not possible if you want to use the test playwright test runner

(a) One can specify localstorage for project. But I need to create the data for each test in `test.beforeEach()`. So this option does not work
(b) One cannot modify the localstorage after context is created
(c) One cannot use `test.use()` inside test.beforeEach()

I think (b) or (c) would solve my problem

**Comment by florianbepunkt** [comment]
additional option (d) would be a convenience method to copy context arguments from playwright.config.ts to the new context I would need to create in `test.beforeEach`

**Comment by pavelfeldman** [comment]
You can always use plain evaluate to set the local storage values in beforeEach. Would that work for you?

**Comment by florianbepunkt** [comment]
Yes, I believe so. For now I leverage a fixture to recreate context and page, not sure if this is the "playwright way" to do, but it works:

```ts
export const test = base.extend<TestFixtures>({
  snapshotSettings: snapshotSettings(),
  match: async ({}, use) => {
    const match = await createMatch({ status: 6 });
    await use(match);
    await deleteMatch(match.accessCode);
  },
  context: async ({ browser, contextOptions, match }, use) => {
    const context = await browser.newContext({
      ...contextOptions,
      storageState: match.loggedInHostState,
    });
    await use(context);
  },
  page: async ({ context }, use) => {
    const page = await context.newPage();

    await page.route("**/*", (route) => {
      return route.request().resourceType() === "image" ? route.abort() : route.continue();
    });

    await page.goto("https://localhost:3000");
    await use(page);
  },
});
```

**Comment by dgozman** [comment]
@florianbepunkt You can override `storageState` with a fixture function:

```ts
export const test = base.extend({
  storageState: async ({}, use) => {
    const match = await createMatch({ status: 6 });
    await use(match.loggedInHostState);
    await deleteMatch(match.accessCode);
  },
});
```

`test.use()` also accepts a fixture function if you'd like it locally:

```ts
test.use({
  storageState: async ({}, use) => {
    const match = await createMatch({ status: 6 });
    await use(match.loggedInHostState);
    await deleteMatch(match.accessCode);
  },
});

test('my test', async ({ page }) => {
});
```

Does that work for you?

**Comment by florianbepunkt** [comment]
@dgozman Perfect, thank you
