### ISSUE TITLE
[Feature] Request to add feature to capture console logs configurable in Playwright.config file at project level.

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#7484]
Request to add feature to capture console logs configurable in Playwright.config file at project level.

It would be very helpful to have a flag in Playwright.config file to enable / disable console logs, output the console logs to the test case output directory along with screenshot and video.

I used this plugin in Protractor to configure console logs in protractor.config file.

https://www.npmjs.com/package/protractor-screenshoter-plugin

```javascript

screenshotPath: reportDirectory,
            withLogs: 'true',
            htmlReport: 'true',
            verbose: 'info',
            failTestOnErrorLog: {
                failTestOnErrorLogLevel: 900,
                excludeKeywords: ["favicon.png "]
            }
```

**Comment by mxschmitt** [comment]
Hi, do you want to have the console logs to debug failing tests or do you want to have it to ensure that your application does not throw e.g. exceptions / use console.error while running the tests?

Regarding the first case for debugging it, there is an open feature request https://github.com/microsoft/playwright/issues/7456 for adding it to the [Trace Viewer](https://playwright.dev/docs/trace-viewer), which should cover that.

**Comment by vsravuri** [comment]
I want to ensure my application doesn't throw browser console errors during e2e test (my e2e test runs for long hours). Also want to filter the exceptions at config level. Instead of writing the code in all the spec files to capture the errors, i want to have a setting at config level.

**Comment by dgozman** [comment]
@vsravuri It seems like you want a configurable "strict mode", see #7153. Does that sound right?

**Comment by vsravuri** [comment]
@dgozman 

Yes, something similar to what is mentioned in 7153.

Currently i use this setting with Protractor where i specify the error level and filter the errors. This also has the option to provide keywords to filter the errors.

Also write the error output in test results

**Comment by vsravuri** [comment]
By mistake this ticket got closed.

**Comment by dgozman** [comment]
@vsravuri Let me copy your input to #7153, to consolidate the discussion in one place.
