### ISSUE TITLE
[Feature] Expose a /json/list endpoint when calling `launchServer` compatible with the one Chromium publishes

### ISSUE THREAD

**Issue by connor4312** [microsoft/playwright#7485]
For VS Code, we are building a way to run unit tests in "serverless"/web mode on browsers. To enable debugging in this scenario, we need to either have playwright attach to the browser the js-debug launches (which I hacked together but sometimes fails and is [not recommended](https://github.com/microsoft/playwright/issues/1985#issuecomment-650799451)) or have js-debug attach to playwright's browser.

Playwright has a `launchServer` option already. If the launched server exposed a `/json/list` endpoint roughly compatible with the one Chromium publishes, we'd be able to attach to it. Or, if there was some other way to ask the browser to set up a `--remote-debugging-port` on a specific port number.

For additional discussion and context, see https://github.com/microsoft/vscode-internalbacklog/issues/2235#issuecomment-875017195

**Comment by JoelEinbinder** [comment]
I think you linked to an internal issue that I don't have access to :)

You can pass `--remote-debugging-port=9222` in the `args` option of [`browserType.launchServer`](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-server). Is there a reason this doesn't work for you?

**Comment by connor4312** [comment]
That works beautifully. I assumed this wouldn't work, but should have checked 🤦  thanks!
