### ISSUE TITLE
[Bug]: Chromium crash WARNING:process_memory_mac.cc(93)] mach_vm_read(0x16eef0000, 0x8000): (os/kern) protection failure (2) +5ms

### ISSUE THREAD

**Issue by worldomonation** [microsoft/playwright#7488]
### Playwright version

1.12.x, 1.13-next

### Operating system

MacOS, Linux

### What browsers are you seeing the problem on?

Chromium

### Other information

Node.JS version: 14.16.1
CI: TeamCity + Docker (debian)
Local: macOS 11.4, MacBookPro17,1

### What happened? / Describe the bug

Chromium bundled with Playwright `1.12.x` and `1.13.0-next-alpha-jul-6-2021` crashes when interacting with certain elements on a published WordPress.com page. 

This issue was not reproducible on Playwright 1.11.x with its bundled Chromium browser.

On WordPress.com, when the end-to-end tests attempt to either:
- post a comment then like it, or
- click on the like button on the post itself

the browser crashes immediately with Error 11. 

In fact, it appears that merely attempting to load the published page triggers the crash.

I have attempted to isolate the section of code that triggers this behavior, but have been unsuccessful in doing so at this moment. However, the page objects that represent the suspected triggers are implemented as [CommentsComponent](https://github.com/Automattic/wp-calypso/blob/trunk/packages/calypso-e2e/src/lib/components/comments-component.ts) and [PublishedPostPage](https://github.com/Automattic/wp-calypso/blob/trunk/packages/calypso-e2e/src/lib/pages/published/published-post-page.ts).

An video showing an example of the crash (run locally) is attached for reference.

Please let me know what other information I should provide. This is an issue I am trying to further isolate without much luck.

https://user-images.githubusercontent.com/6549265/124672515-ff3d3380-de6b-11eb-85de-63baa3d8fcae.mov

### Relevant log output

```shell
pw:api elementHandle.fill("24 Scary Aardvarks Trot Roughly") +3ms
  pw:api   waiting for element to be visible, enabled and editable +0ms
  pw:api   element is visible, enabled and editable +14ms
  pw:api <= page.fill succeeded +3ms
  pw:api => page.click started +1ms
  pw:api waiting for selector ".form-submit #comment-submit" +1ms
  pw:api   selector resolved to visible <input name="submit" type="submit" id="comment-submit" …/> +4ms
  pw:api attempting click action +2ms
  pw:api   waiting for element to be visible, enabled and stable +0ms
  pw:api   navigated to "about:blank" +53ms
  pw:api   "load" event fired +0ms
  pw:api   "domcontentloaded" event fired +0ms
  pw:api   element is visible, enabled and stable +3ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +1ms
  pw:api   checking that element receives pointer events at (832.2,738.54) +3ms
  pw:api   element does receive pointer events +7ms
  pw:api   performing click action +1ms
  pw:api   click action done +11ms
  pw:api   waiting for scheduled navigations to finish +0ms
  pw:api   navigated to "https://accounts.google.com/o/oauth2/iframe#origin=httpsundefinedAundefinedFundefinedFpublic-api.wordpress.com&rpcToken=387664834.15366864" +10ms
  pw:api   "load" event fired +23ms
  pw:api   "domcontentloaded" event fired +0ms
  pw:api   navigated to "https://widgets.wp.com/notifications/?v=@automattic/jetpack-blocks@13.1.0-12669-g727d23c131v2&locale=en-gb#https://e2eflowtestinggutenbergsimple.wordpress.com/2021/07/06/cagey-woodchucks-jump-safely/" +2s
  pw:api   "domcontentloaded" event fired +1ms
  pw:api   "load" event fired +0ms
  pw:api   navigated to "https://public-api.wordpress.com/wp-admin/rest-proxy/?v=2.0#https://widgets.wp.com" +252ms
  pw:api   "domcontentloaded" event fired +1ms
  pw:api   "load" event fired +0ms
  pw:api   navigations have finished +133ms
  pw:api <= page.click succeeded +0ms
      ✓ Post a comment (2844ms)
  pw:api => page.waitForSelector started +3ms
  pw:api waiting for selector ".comment-list" to be visible +1ms
  pw:api <= page.waitForSelector failed +30s
      1) Like the comment
  pw:api => page.screenshot started +26ms
  pw:api <= page.screenshot failed +17ms
      2) "after each" hook: saveScreenshot for "Like the comment"

  pw:api => page.close started +7ms
  pw:api <= page.close succeeded +15ms
  pw:api => video.delete started +0ms
  pw:api <= video.delete succeeded +10s
  pw:api => browser.close started +1ms
  pw:api <= browser.close succeeded +155ms

  4 passing (50s)
  2 failing

  1) [WPCOM] Likes (Comment): (desktop) @parallel
       Comment and like on an existing post
         Like the comment:
     page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector ".comment-list" to be visible
============================================================
      at CommentsComponent._click (/Users/edwintakahashi/workspace/wp-calypso/packages/calypso-e2e/dist/cjs/src/lib/components/comments-component.js:69:25)
      at CommentsComponent.like (/Users/edwintakahashi/workspace/wp-calypso/packages/calypso-e2e/dist/cjs/src/lib/components/comments-component.js:97:36)
      at Context.<anonymous> (specs/specs-playwright/wp-likes__comment-spec.js:48:28)

  2) "after each" hook: saveScreenshot for "Like the comment":
     page.screenshot: Target crashed
      at Context.saveScreenshot (/Users/edwintakahashi/workspace/wp-calypso/packages/calypso-e2e/dist/cjs/src/hooks/screenshot.js:31:16)
```

**Comment by worldomonation** [comment]
Interestingly, I was able to prevent Chromium from crashing if the test was run headlessly.

**Comment by mxschmitt** [comment]
This is interesting, would it be possible that you could provide us debug logs which you can set when setting the env var `DEBUG=pw:browser,pw:api`? (This might contain confidential information, if so, let me know then I can give you my work email.)

Also could you try to do it manually via opening the browser - so its a normal Chromium? The location where Chromium is stored on your file system, you can find [here](https://playwright.dev/docs/installation#managing-browser-binaries). When its also reproducible there, we know that its an upstream Chromium bug.

**Comment by worldomonation** [comment]
Hi @mxschmitt, thanks for some leads!

> Also could you try to do it manually via opening the browser - so its a normal Chromium?

I located several Chromium installations on my machine under `~/Library/Caches/ms-playwright/` but I believe `chromium-888113` is of interest. 

I tried the following scenario in both regular and incognito sessions:

1. log in to WordPress.com
2. start a new post
3. publish
4. like the post
5. comment on post
6. like the comment

When running under Playwright, it would typically crash on step 4.
When interacting with the browser manually, I was **not** able to trigger the crash.

> This is interesting, would it be possible that you could provide us debug logs which you can set when setting the env var `DEBUG=pw:browser,pw:api`? 

I ran the crashing test with your parameters set and was able to get some potentially useful information, including a line where this appears:
`  pw:browser [pid=56422][err] Received signal 11 SEGV_ACCERR 0000000003f0 +494ms`

If you could provide me with your work email, and I can send the logs to you.

**Comment by mxschmitt** [comment]
awesome, `maxschmitt[AT]microsoft[DOT]C0M`, would also be cool if you could add there a reproducible script, so I don't need to create an account there, thanks in advance.

**Comment by mxschmitt** [comment]
Seems like an upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1223052

Relevant logs:

```
  pw:browser [pid=29088][err] [0708/093712.523439:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x16dd3c000, 0x8000): (os/kern) protection failure (2) +5ms
  pw:browser [pid=29088][err] Received signal 11 SEGV_ACCERR 0000000003f0 +142ms
```

**Comment by worldomonation** [comment]
> Seems like an upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1223052

Thanks @mxschmitt! Does the Playwright team have their own channel for interacting with Chromium project, or should I take it this report to the upstream bug myself?

**Comment by mxschmitt** [comment]
The best would be that you either create a new bug report there or (if I think its the case) write + star that you are also affected on the linked bug report. (reproducibles are important there).

We also investigate into upstream bugs occasionally if there are multiple users affected by it.

**Comment by worldomonation** [comment]
> The best would be that you either create a new bug report there or (if I think its the case) write + star that you are also affected on the linked bug report. (reproducibles are important there).
> 
> We also investigate into upstream bugs occasionally if there are multiple users affected by it.

Understood, thanks - I will report my observation to the bug you linked. No better luck at coming up with a reproducible script that does not rely on my infra, but I will give it a shot next week.

**Comment by worldomonation** [comment]
Looping back to say that this has been resolve as of Playwright 1.14. I never got around to filing the issue with the Chromium project. I also see the [upstream issue referenced](https://bugs.chromium.org/p/chromium/issues/detail?id=1223052) remains open and untriaged, so it must have been reported in another issue.

Anyway, closing this issue as it is resolved for me.
