### ISSUE TITLE
[Bug]: page.on('console') yields logs in incorrect order

### ISSUE THREAD

**Issue by Izhaki** [microsoft/playwright#7489]
### Playwright version

1.12.3

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

Taking the docs example:

```js
  page.on('console', async (msg) => {
    for (let i = 0; i < msg.args().length; ++i)
      console.log(`${i}: ${await msg.args()[i].jsonValue()}`);
  });
```

Refactoring a bit:
```js
  page.on('console', async (msg) => {
    const parsed = await Promise.all(msg.args().map((arg) => arg.jsonValue()));
    console.log(...parsed);
  });
```

The order of the messages is incorrect when logs are fired in quick succession (and even in not-so-quick-succession).

This is due to timing variations in resolving `jsonValue` and/or the overall amount of arguments.

So for the following code in the loaded page:

```js
  console.log('1', { first: 'John', family: 'Smith' });
  console.log(2);
```

The log output after `page.on('console')` that awaits `jsonValue` is:

```
2
1 { first: 'John', family: 'Smith' }
```

(In fact, there can be a quite a few more console messages after `2` before `1` is resolved - for statements executed after `console.log(2)`)

Whereas with:
```js
  page.on('console', console.log);
```

The order of the logs is correct (and identical to the one in the actual browser). The obvious issue with this approach is that you get `JSHandle@object` in the output rather than the actual logged value.

I would assume the `on` handler would wait for the callback to be resolved before firing the next log event (ie, it would have to queue these logs somehow).

### Code snippet to reproduce your bug

```shell
// Browser

console.log('1', { first: 'John', family: 'Smith' });
console.log(2);


// Node
page.on('console', async (msg) => {
  const parsed = await Promise.all(msg.args().map((arg) => arg.jsonValue()));
  console.log(...parsed);
});
```

**Comment by pavelfeldman** [comment]
Playwright works as any other EventEmitter in Node, with the same strict behavior. Events are emitted in oder and awaits take arbitrary amount if time. So if you want console messages with the resolved args, you need to queue them manually.

> I would assume the on handler would wait for the callback to be resolved before firing the next log event (ie, it would have to queue these logs somehow).

That's not how event handlers work in Node. Events are emitted in order and idiomatic Node events are not async / queueing. If they were, it would create more problems than it would solve.

**Comment by Izhaki** [comment]
> Playwright works as any other EventEmitter in Node, with the same strict behavior. Events are emitted in oder and awaits take arbitrary amount if time. So if you want console messages with the resolved args, you need to queue them manually.

This makes sense, so I think we should close this issue.

I just wonder if this is something the docs should mention... I've spent an hour trying to figure why my code doesn't work only to find out that the console logs are not ordered.

**Comment by pavelfeldman** [comment]
Ouch. Yes, promises can be tricky. We'll see if we get more reports on this and if we do, we'll figure something out.
