### ISSUE TITLE
[Question]: browserContext.setHTTPCredentials deprecation and test runners

### ISSUE THREAD

**Issue by truefusion** [microsoft/playwright#7490]
### Your question

I noticed that the documentation for [browserContext.setHTTPCredentials](https://playwright.dev/docs/api/class-browsercontext/#browser-context-set-http-credentials) asserts deprecation and that we should create a new browser context each time to provide our own credentials. This would be all well and good if we weren't interested in using test runners. Since `browserContext.setHTTPCredentials` is still available it is currently not a problem. However, once removed, what are we to do for those of us who wish to make use of test runners? Don't test runners automatically create a new browser context for each test? Does this mean that test runners are essentially deprecated? Or is there something I can do with the configuration that would allow me to provide the credentials that's not mentioned in the documentation?

**Comment by pavelfeldman** [comment]
You can always configure the way test runners create browser context and among other options, you can specify the http credentials there.

**Comment by truefusion** [comment]
After reading the documentation a bit more, I came to understand how to pass the data to the test runners.

```js
// playwright.config.js
module.exports = {
  use: {
    httpCredentials: {
      username,
      password,
    },
};
```
