### ISSUE TITLE
[Feature] Allow getting the Request headers for WebSockets

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#7494]
Context: https://github.com/microsoft/playwright/issues/7474

**Comment by zydjohnHotmail** [comment]
Hello:
Have you made any progress in this feature?
It has been more than one month now.
Thanks,

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
