### ISSUE TITLE
[Bug]: A new worker gets created when skip is used.

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#7496]
### Playwright version

1.12.0

### Operating system

Windows, MacOS, Linux

### What happened? / Describe the bug

> I was playing around with playwright test runner and test.fixme and test.skip annotation. I’ve noticed that using skip or fixme result in creating a new worker to run remaining tests after the skipped one. Is there any technical reason for doing that ? Here’s a screen of a sample test run

![image](https://user-images.githubusercontent.com/17984549/124747471-3e2dc080-df22-11eb-902a-b4f9088debfe.png)

From Slack: https://playwright.slack.com/archives/C01AG7QGW2F/p1625649237089500

**Comment by pavelfeldman** [comment]
We restart workers on exceptions, fixme is internally implemented as exception, but we surely don't want to restart workers on them.

**Comment by mxschmitt** [comment]
Closed since fixed in https://github.com/microsoft/playwright/pull/7511.
