### ISSUE TITLE
[Question]: How to do Device Emulation config with playwright.config.ts?

### ISSUE THREAD

**Issue by akshayp7** [microsoft/playwright#7497]
### Your question

My Use case is like, In case of Emulation , we give values to browser like shown below, 
We are creating a new Context so values are not picked from playwright.config.ts 

const browser = await chromium.launch({ headless: false });
const pixel2 = devices[Pixel 2];
const context = await browser.newContext({ ...pixel2 });

So is it a right approach to give browser attributes values and device value in and external json file and read it accordingly?

**Comment by mxschmitt** [comment]
Hi, this should give you a good overview in how mobile emulation works with Playwright Test: https://playwright.dev/docs/next/test-configuration#mobile-emulation

In Playwright Test you should not create your browser or context yourself. It gets automatically created for you and provided as a [fixture](https://playwright.dev/docs/next/test-fixtures) inside your test.

**Comment by akshayp7** [comment]
Thanks for helping out, Looks like I missed reading this part of documentation for config. Now its working for me.
