### ISSUE TITLE
[Question]: Skip single project in test (mobile device emulation)

### ISSUE THREAD

**Issue by florianbepunkt** [microsoft/playwright#7498]
### Your question

I have setup mobile emulation like shown here: https://playwright.dev/docs/next/test-configuration/#mobile-emulation

We have a feature in our app that is only present on mobile. Therefore I would like to run the corresponding test suite only for one project and skip the other project for this particular test. How does this work?

**Comment by mxschmitt** [comment]
The easiest way of doing it would be to skip it by the project name. This would then look like this:

```js
test('should do ABC', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name === 'iPhone 11');
  // ...
});
```

See here for further information:
- about annotations: https://playwright.dev/docs/next/test-annotations
- about the testInfo object: https://playwright.dev/docs/next/test-advanced#testinfo-object

**Comment by florianbepunkt** [comment]
Thank you!
