### ISSUE TITLE
[Question]: playwright config set in config.ts file overwrites context set in fixture?

### ISSUE THREAD

**Issue by archlichking** [microsoft/playwright#7505]
### Your question

I have a question and I cannot find an answer to it from doc. I have a playwright config file, like this 

```js
// playwright.config.ts
const config: PlaywrightTestConfig = {
  testDir: 'tests',
  testMatch: '**/*.test.ts',
  workers: 4,
  reporter: 'list',
  use: {
    headless: true,
    video: 'on',
    contextOptions: {
      recordVideo: {
        dir: 'test-results/video',
      },
    },
  },
}
```

This config file is loaded when test runs via 

```bash
npx playwright test --config=playwright.config.ts --project="safari@iphone 12pm"
```

In our test we want to test scenarios for both logged in user and guest, so I create separate test fixtures according to https://playwright.dev/docs/test-fixtures this link.

```js
// guest fixture
export const visitorTestFixture = base.extend({
  page: async ({ page, video }, use, testInfo) => {
    await use(page);
    ...
  }
})
```

```js
// logged in fixture
export const userTestFixture = base.extend({
  contextOptions: { storageState: './state.json' },
  page: async ({ page, video }, use, testInfo) => {
    await use(page);
    ...
  }
})
```

Our website uses cookies to authenticate. What I found was, if `contextOptions` are enabled in both config file and fixtures, then cookies aren't load in test. I guess the `contextOptions` in config file has the highest priority here.

I don't know if this is the expected behavior. What is the recommended way here if I need to add some `contextOptions` on the fly?

**Comment by yury-s** [comment]
@archlichking can you share complete example where it is failing? I tried this [pwtest.zip](https://github.com/microsoft/playwright/files/6784405/pwtest.zip) and it passed.

**Comment by archlichking** [comment]
@yury-s ahhh, thanks. The difference is here, instead of 

```js
// logged in fixture
export const userTestFixture = base.extend({
  contextOptions: { storageState: './state.json' },
  page: async ({ page, video }, use, testInfo) => {
    await use(page);
    ...
  }
})
```
your example uses
```js
// guest fixture
const test = base.extend({
  data,
  storageState: './tests/state.json', //<------------- difference
  page: async ({ page, video }, use, testInfo) => {
    await use(page);
  },
});
```

Your example works, I'll use this pattern. Thanks, we can close this ticket now.

**Comment by yury-s** [comment]
The test runner should throw an error like `Error: browser.newContext: ENOENT: no such file or directory, open './state.json'` if the file doesn't exist so you probably had both state.json and tests/state.json.
