### ISSUE TITLE
[Bug]: Can't resolve 'electron/index.js'

### ISSUE THREAD

**Issue by florianbepunkt** [microsoft/playwright#7508]
### Playwright version

1.12.3

### Operating system

MacOS

### Other information

I installed `"@playwright/test": "1.12.3"`with NPM7 and Create React App. When starting the react app in dev mode, I get the error below

I already deleted node_modules as well as package-lock.json, but to no avail.

### What happened? / Describe the bug
```
./node_modules/@playwright/test/lib/server/electron/electron.js
Module not found: Can't resolve 'electron/index.js' in '/Users/florian/Github Repositories/cm-online/client/node_modules/@playwright/test/lib/server/electron'
```

### Relevant log output

```shell
./node_modules/@playwright/test/lib/server/electron/electron.js
Module not found: Can't resolve 'electron/index.js' in '/Users/florian/Github Repositories/cm-online/client/node_modules/@playwright/test/lib/server/electron'
```

**Comment by florianbepunkt** [comment]
it seems to boil down to line 128 in `client/node_modules/@playwright/test/lib/server/electron/electron.js`

`executablePath: options.executablePath || require('electron/index.js'),`

**Comment by szakharchenko** [comment]
I may be dense, but why did you close this yourself? This makes e.g. `rollup` unhappy seemingly needlessly (OK, I know it can be worked around). How about requiring clients to always provide a path?
