### ISSUE TITLE
[Feature]: Document "fixture enhancement"

### ISSUE THREAD

**Issue by mskelton** [microsoft/playwright#7512]
### Feature request

As I've began to utilize the Playwright test runner, I discovered that it supports overriding/enhancing existing fixtures.  After more digging, I found other examples in issues including this example shared by @mxschmitt.

https://github.com/microsoft/playwright/issues/7051#issuecomment-859916019

```js
import { test as baseTest } from '@playwright/test';

const test = baseTest.extend({
  page: async ({ page }, use) => {
    await page.goto('http://localhost:3579');
    await use(page);
  },
});

export const it = test;
export const expect = test.expect;
```

This is a very powerful pattern as you can add functionality in layers by adding more extends on base fixtures based on various use cases a test suite might have.  Could we add documentation for this type of pattern somewhere in the docs?

I'd be more than happy to write the docs if you are all good with adding it.  Just point me in the direction of where to go!

**Comment by dgozman** [comment]
@mskelton Here is the source for the documentation: https://github.com/microsoft/playwright/blob/master/docs/src/test-fixtures.md. Look around for other docs as well. Any documentation PRs are immensely valuable, so please go ahead!
