### ISSUE TITLE
[Feature]: Build off of existing playwright scripts

### ISSUE THREAD

**Issue by IgorGee** [microsoft/playwright#7514]
### Feature request

I'd like to be able to create a playwright script and treat it as an initialization or base script for additional scripts.

I can think of two use cases for this:
* Quickly fix a script for a site that changed
* Create DRY playwright scripts for tests that have a common set of initial steps

Quick Fix Workflow:
1. Normal playwright script creation: `playwright codegen --output base.js`
2. Site Change: delete the the changed part of `base.js`
3. Create fix: `playwright codegen --init base.js --output fix.js`

DRY Business Paths Workflow:
1. Normal playwright script creation: `playwright codegen --output base.js`
2. Building off of that file: `playwright codegen --init base.js --ouput bizPath1.js`
3. And then another: `playwright codegen --init base.js --output bizPath2.js`

We can take this a step further by having an `--end` script that runs after the main playwright script.
This is pretty much just like having a `beforeAll` and `afterAll` script.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
