### ISSUE TITLE
[Feature]: Access to fixtures in page object model methods

### ISSUE THREAD

**Issue by srguiwiz** [microsoft/playwright#7520]
### Feature request

Methods in the page object model as supposed to abstract "doing stuff".  Fixtures contain objects that methods would need to operate with.  Therefore, fixtures would be useful to have available in a similar way as in test code.

Workaround meanwhile:  We can pass fixtures to the constructor of a page object model class.

I cannot say yet whether the effort to implement and document this feature will pay off in time.

**Comment by dgozman** [comment]
@srguiwiz This seems somewhat vague, because page object classes are some arbitrary javascript, we have no control over it. That said, you can provide your page object through a fixture, so that every test does not have to pass all the fixture to it:

```ts
import { test as base, expect } from '@playwright/test';
const test = base.extend<{ pom: MyPOM }>({
  pom: async ({ page, context, whateverFixture }, use) => {
    const pom = new MyPOM(page, context, whateverFixture);
    await use(pom);
  },
});

test('example', async ({ pom }) => {
  await pom.doStuff();
});
```

Does that help?

**Comment by srguiwiz** [comment]
Yes, that is what we are doing now.  That workaround is reasonable.  Thank you.

The feature idea was to have access to all fixtures, maybe in a method of the page object model, to avoid test authors needing to bother with each, given a page object model.

But, you are right, I just noticed a base page object model class doesn't extend any further base class.  Strike this feature idea.  If ever implement it will be gladly accepted.  Meanwhile, okay to close this feature request.

**Comment by dgozman** [comment]
> But, you are right, I just noticed a base page object model class doesn't extend any further base class.

Indeed, thank you for double-checking!
