### ISSUE TITLE
[Bug]: Can't connect playwright to existing browser

### ISSUE THREAD

**Issue by niewiemczego** [microsoft/playwright#7523]
### Playwright version

1.12.0

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

Playwright open another browser and open google.com instead of opening google.com in the existing browser

### Code snippet to reproduce your bug

```shell
import asyncio
from playwright.async_api import async_playwright
import time
import random
import subprocess
import requests
import threading
import os
import glob
import json

profile_dir = r"E:\\testfolder\\Files\\chrome_p\\testowy_profil5"

def start_chrome(port):
    subprocess.call([r"C:\\Program Files\\Google\\Chrome\Application\\chrome.exe",
        f"--remote-debugging-port={port}",
        "--user-data-dir=" + profile_dir,
        "--window-size=1280,720"])

async def main(ws_url):
    async with async_playwright() as p:
        print("connecting...")
        browser = await p.chromium.connect_over_cdp(ws_url) #działa <-----
        page = await browser.new_page()
        await page.goto("https://www.google.com")
        time.sleep(1002)
        await browser.close()

def get_ws_url(port):
    print("Getting ws url")
    r = requests.get(f'http://127.0.0.1:{port}/json/version')
    ws_url = r.json()["webSocketDebuggerUrl"]
    print("Found ws url: " + ws_url)
    return ws_url

port = str(random.randint(10240,65535))
threading.Thread(target=start_chrome, args=(port,)).start()
time.sleep(2)
ws_url = get_ws_url(port)
asyncio.get_event_loop().run_until_complete(main(ws_url))
```

**Comment by dgozman** [comment]
@niewiemczego This is expected. Playwright opens a new browser window when you call `browser.new_page()`. If you'd like full control over the browser, I suggest to use `chromium.launch()` instead. Is there a reason you use `chromium.connect_over_cdp()`?

**Comment by niewiemczego** [comment]
@dgozman Im using this method to be able to bypass security on some sites. If I use chromium.launch() or other launch options site somehow detects that the browser is automated by bot but when Im running mine chrome and then connect to it site doesnt detect it and Im able to use playwright automation.

**Comment by dgozman** [comment]
@niewiemczego In this case a new browser window will be opened, and I don't think this will change in the nearest future. Sorry for the inconvenience!
