### ISSUE TITLE
UnhandledRejection error during page.click  with navigation

### ISSUE THREAD

**Issue by Mango88Boba** [microsoft/playwright#7527]
When I execute page.click on a button that causes a navigation, I encounter a unhandledRejection error that is not coming from the playwright code that I cannot catch or expect to catch, since it is not a timeout error.  Please help me understand if there is issue with my sample code.  I have changed all the links to be anonymous, since they are not public.

I have attached the sample source code to reproduce the issue without the real links.  Also attached is the pw log from a working and failing run.

The error sequence from the pw logs:
  pw:api => page.click started +0ms
  pw:api waiting for selector "text="Patients"" +2ms
  pw:api   navigated to "link4" +629ms
  pw:api   "domcontentloaded" event fired +5ms
  pw:api   "load" event fired +16ms
  pw:api   selector resolved to visible <button class="add-bag-main col-5 text-center nav-text d…> Patients </button> +78ms
  pw:api attempting click action +5ms
  pw:api   waiting for element to be visible, enabled and stable +1ms
  pw:api   element is visible, enabled and stable +54ms
  pw:api   scrolling into view if needed +1ms
  pw:api   done scrolling +4ms
  pw:api   checking that element receives pointer events at (355,571) +3ms
  pw:api   element does receive pointer events +5ms
  pw:api   performing click action +1ms
  pw:api   click action done +31ms
  pw:api   waiting for scheduled navigations to finish +0ms
  pw:api   navigations have finished +27ms
  pw:api <= page.click succeeded +0ms
  pw:api => page.waitForTimeout started +1ms
  pw:api   navigated to "link9" +45ms
unhandledRejection: Error
    at Object.assert (C:\Users\TTNUC01\Desktop\podapp-e2e.701\node_modules\playwright\lib\utils\utils.js:86:15)
    at FrameManager.frameAttached (C:\Users\TTNUC01\Desktop\podapp-e2e.701\node_modules\playwright\lib\server\frames.js:95:21)
    at FrameSession._onFrameAttached (C:\Users\TTNUC01\Desktop\podapp-e2e.701\node_modules\playwright\lib\server\chromium\crPage.js:528:34)   
    at CRSession.<anonymous> (C:\Users\TTNUC01\Desktop\podapp-e2e.701\node_modules\playwright\lib\server\chromium\crPage.js:346:96)
    at CRSession.emit (events.js:315:20)
    at C:\Users\TTNUC01\Desktop\podapp-e2e.701\node_modules\playwright\lib\server\chromium\crConnection.js:158:22
[rejection.zip](https://github.com/microsoft/playwright/files/6788293/rejection.zip)

**Comment by Mango88Boba** [comment]
Adding my test config:
Playwright version: 1.11.1 (also fails on 1.12.3)
Operating system: Windows 10
What browsers are you seeing the problem on? Chromium

**Comment by akshayp7** [comment]
1. I had a redirection issue on button click, I used the below code which solved my issue, it waits for navigation event on click of button,

await Promise.all([
            page.waitForNavigation(),
            page.click(locator);
        ]);
2. My second solution would be try to record the script using "npx playwright codegen" , and perform the same action and look into the code generated.

Hope this might help you

**Comment by akshayp7** [comment]
oh ok. Another option would be to add a small amount of delay say 500 ms and check, 
Lets wait for better solutions in comments.

**Comment by mxschmitt** [comment]
Closing as part of the triage process. This was unfortunately of one of the issues which went under our radar. The reason for the unhandled rejection is that you await the click inside the Promise.all.
So it should be:

```js
    await Promise.all([
      page.waitForNavigation(),
      page.click(SIGN_IN_BUTTON),
    ]);
```

After you remove the `await ` there you which you had previously it works for me. Please reopen / create a new issue if you still encounter issues.
