### ISSUE TITLE
[Bug]: Typo in auth - session-storage documentation

### ISSUE THREAD

**Issue by christianbaumann** [microsoft/playwright#7530]
### Playwright version

1.12.0

### What happened? / Describe the bug

On https://playwright.dev/java/docs/auth/#session-storage the code example is:
`String sessionStorage = (String) page.evaluate("() => JSON.stringify(sessionStorage");`

There's a `)` missing, the snippet should be:
`String sessionStorage = (String) page.evaluate("() => JSON.stringify(sessionStorage)");`

**Comment by mxschmitt** [comment]
Do you want to submit a PR for it? You can find the source-file here: https://github.com/microsoft/playwright/blob/master/docs/src/auth.md

If not, no worries. We can pick it up.

**Comment by christianbaumann** [comment]
Never done that, but happy to pick up the challenge. :-)
