### ISSUE TITLE
[Feature]: Publish types for use by libraries

### ISSUE THREAD

**Issue by mskelton** [microsoft/playwright#7533]
### Feature request

Currently, there isn't a clear approach for how third party libraries should utilize the Playwright TypeScript definitions.  Should you install `playwright` as a peer dependency?  Should you install `playwright-core` as a peer dependency?  Should you install `playwright-core` as a dependency?

Looking for either some guidance on what to do here, or if there is an improvement to Playwright that needs to be made to better support third party library development.

**Comment by dgozman** [comment]
I'd suggest to use `playwright-core` dependency for now. Is there a reason this does not work for you?

**Comment by mskelton** [comment]
That should work, I was mostly just looking for recommendations as there seems to be some confusion in the ecosystem regarding the right way to handle this.  Having a dependency or peer dependency on `playwright` is definitely wrong as using `playwright-chromium` or `@playwright/test` with a third party library that depends on `playwright` would cause unnecessary browser downloads.
