### ISSUE TITLE
[Question]: run Chromium from Flatpak

### ISSUE THREAD

**Issue by nexcode** [microsoft/playwright#7536]
### Your question

```
executablePath: '/usr/bin/flatpak run org.chromium.Chromium'
```

Error: `Failed to launch chromium because executable doesn't exist at /usr/bin/flatpak run org.chromium.Chromium`

Is it possible to launch it somehow?

**Comment by dgozman** [comment]
@aslushnikov This basically means treating `executablePath` as a shell command, perhaps we can do that?

**Comment by pavelfeldman** [comment]
Could you tell us a little more about your scenario? How do you run Node, what test runner you use?

**Comment by nexcode** [comment]
Node runs as a systemd service on centos 8 (node 16).
Just in a flatpak, chrome supports codecs out of the box and it would be more convenient to use it for tests (video playback).

**Comment by nexcode** [comment]
Or launching version from flatpak different from launching just a binary?

**Comment by aslushnikov** [comment]
@nexcode The quick workaround would be to have a simple bash script like this:

```sh
#!/usr/bin/env bash

/usr/bin/flatpak run org.chromium.Chromium "$@"
```

And pass a path to this bash script as the `executablePath` at the `chromium.launch()` method.

**Comment by pavelfeldman** [comment]
Please feel free to open a new issue if this is still a problem.
