### ISSUE TITLE
Debug mode for test runner

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#7537]
### Feature request

Requested on Twitter: https://mobile.twitter.com/eliostruyf/status/1413392602418790401

```
The ideal would be a test runner
that shows the test progress, and
a separate browser instance.
```

- [x] My understanding is that this is a new mode

```bash
npx playwright test --debug
```

Which is a shortcut to

```bash
PWDEBUG=1 npx playwright test --workers=1 --headed
```

But in addition to that,

- [x] inspector and browser window are reused to reduce flashing
- [ ] elements of the new test status UI show the history of successful/failed runs in the inspector

This basically produces debug experience visually resembling Cypress for those relying only on core testing scenarios.

**Comment by visortelle** [comment]
This feature done right can allow to build [storybook](https://storybook.js.org/)-like components catalogs.

There is no need to setup a separate storybook/styleguidist/etc. to display a UI components list with usage examples if you already have a list tests for each component and can run it in browser just by clicking a right test case.

**Comment by mxschmitt** [comment]
This got partially implemented in https://github.com/microsoft/playwright/pull/8938
