### ISSUE TITLE
[Question]: playwright-artifacts

### ISSUE THREAD

**Issue by nexcode** [microsoft/playwright#7538]
### Your question

In `/tmp` folder many `playwright-artifacts-XXXXX` folders.
Is there any way to change their location?

**Comment by dgozman** [comment]
These folders should be automatically removed. Could you please run your script with `DEBUG=pw:browser*` environment variable and post the output here, so we can better understand why these folders are not removed?

Also, are you using `chromium.connectOverCDP` by any chance?

**Comment by nexcode** [comment]
I use browserType.launchPersistentContext

**Comment by pavelfeldman** [comment]
Could you share more on where you use it and how? Playwright exits in a way that does not handle the process exit signals and hence does not do the cleanup.

**Comment by nexcode** [comment]
```
const context = await playwright.chromium.launchPersistentContext(...);

process.once('exit', () => {
    context.BrowserContext().close();
});
```
Will this be enough for playwright have time to validly end its session?

**Comment by aslushnikov** [comment]
> Will this be enough for playwright have time to validly end its session?

I don't think so. the `close` operation is async, and there's no guarantee it'll terminate before the process is killed.

**Comment by nexcode** [comment]
Indeed, it is strange that my static analyzer did not highlight this area.
