### ISSUE TITLE
[Feature]: add args parameter when running PW test

### ISSUE THREAD

**Issue by Tallyb** [microsoft/playwright#7539]
### Feature request

Allow users to pass cli args to a PW run. 
`playwright test --args=arg1,arg2,arg3`

And then get context.args: string[] = [arg1, arg2, arg3]

Allow for run time execution beyond env params.

**Comment by dgozman** [comment]
@Tallyb Could you share a bit more, like an example where this is useful? Also, when you say `context.args` - do you mean the default `context` fixture that is provided to each test?

**Comment by Delexir** [comment]
+ for this request
In my case it seems to looks like 
npx playwright test --product1_url https://test-vm1 --product2_url https://test-vm2 --product3_url https://test-vm3 --product4_url https://test-vm4
to use this args in tests with multiclaster product cases on any sets of urls.

**Comment by CallOBock** [comment]
Or add the ability to connect an additional file with custom data:
Something like this: `npx playwright test testingFuters.mjs --data=custom_data.js`

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
