### ISSUE TITLE
[Feature]:  Allow users the ability to influence selectors in recording.

### ISSUE THREAD

**Issue by ZooDoo4U** [microsoft/playwright#7545]
### Feature request

As a tester needing to extract elements on a page it would be great if we could have an option for specifying what a selector is in the generated script from the recording...   

Specifically, just learned about the "data-" attribute which seems would be perfect for this.  They are intended to store custom data private for a page or application.   Additionally using the "data-XXXX" attribute it would be helpful to effectively side step localization/globalization concerns for the UI test... 

Cheers, and thanks for your consideration.

**Comment by dgozman** [comment]
This seems very similar to #5178, so let's continue discussion there.
