### ISSUE TITLE
[Question]: Do all tests run in parallel?

### ISSUE THREAD

**Issue by mahaveer0496** [microsoft/playwright#7546]
### Your question

First of all thanks for the amazing library! It's awesome to work with. 🙌 

---

I noticed that tests in separate files run in parallel but what about tests in the same file? Are they always executed sequentially?

For the snippet below will the 2nd test always get executed after the first one?
```js
// foo.js

test('A' ({page}) => {})
test('B' ({page}) => {})
```

What about this snippet?
```js
// foo.js
describe('some description', ()=>{
  test('A' ({page}) => {})
  test('B' ({page}) => {})
})
```

**Comment by mxschmitt** [comment]
A test file gets executed in a single worker so the tests inside a file don't run in parallel. Currently they do run sequentially per file in terms of the order.

(You might be interested in the #7254 feature-request too)

**Comment by mahaveer0496** [comment]
Thank you so much for the quick reply! 🙏
