### ISSUE TITLE
[Question]: How to run tests in parallel when using playwright-github-action

### ISSUE THREAD

**Issue by mahaveer0496** [microsoft/playwright#7547]
### Your question

I've been trying to get tests to run in parallel but could not find a resource. 
Any help would be great. Thanks!

**Comment by mxschmitt** [comment]
There are two ways of achieving that.

a) You can run your tests parallel on a single GitHub Action job by using the `--workers=4` CLI argument ([or in the config](https://playwright.dev/docs/test-configuration#testing-options)), there you can specify how much workers should be spawned to parallelise your test runs on a single machine.
b) You can leverage test sharding, see [here](https://playwright.dev/docs/test-parallel#shards). This means, you start multiple GitHub Action jobs by using a matrix there with the values of e.g. `[1,2,3,4,5,6,7,8]` and pass the shard over to the Playwright test-runner e.g. `1/8`, `2/8` etc. This internally will figure out which tests to run on which of your jobs. This results in running your tests on multiple machines.

**Comment by mahaveer0496** [comment]
Thanks a ton! I'll try the solutions :)
