### ISSUE TITLE
[Question]: Java User-Agent and Browser Size

### ISSUE THREAD

**Issue by ArmanYeghiazaryan** [microsoft/playwright#7549]
### Your question

Hello,

I have two questions. Unfortunately I could not find a solution for Java.

1. How can I set a custom user-agent into my firefox browser in Java?

2. How can I set my firefox browser as full screen? (In general change the size)

I would really appreciate, if you could attach a Java code snippet. 

Thank you very much!

**Comment by ArmanYeghiazaryan** [comment]
Would appreciate any help.

**Comment by yury-s** [comment]
> 1\. How can I set a custom user-agent into my firefox browser in Java?

You can specify user agent string when creating [new context](https://playwright.dev/java/docs/api/class-browser#browser-new-context). See [this example](https://playwright.dev/java/docs/emulation/#user-agent).


> 2\. How can I set my firefox browser as full screen? (In general change the size)

There is now built-in support for full-screen mode in Playwright but you can configure any custom size, see [this guide](https://playwright.dev/java/docs/emulation#viewport) for the viewport property. If you really need to run it in fullscreen mode in headful you can use [setFirefoxUserPrefs](https://playwright.dev/java/docs/api/class-browsertype#browser-type-launch) to pass custom firefox settings and configure custom command line arguments via [`setArgs`](https://playwright.dev/java/docs/api/class-browsertype#browser-type-launch).
