### ISSUE TITLE
[Feature]: Support .tsx files to avoid need for jest

### ISSUE THREAD

**Issue by cefn** [microsoft/playwright#7551]
### Feature request

Given playwright has its own test runner, I was expecting to be able to drop the use of jest for simple unit testing in favour of `@playwright/test` which would simplify a lot of things..

* No need to install, configure jest
* All tests could be invoked with a simple glob, rather than having to partition my test scripts into jest vs. playwright tests

Unfortunately, because some of the elements I'm unit testing live alongside React components, they are in .tsx files, such as this simple counter example, meaning I can't import the business logic elements without having .tsx support in playwright...

```typescript
import React from "react";
import { Immutable, Store } from "@lauf/store";
import { useSelected, useStore } from "@lauf/store-react";

/** BUSINESS LOGIC */

export interface AppState {
  counter: number;
}

export const INITIAL_STATE: Immutable<AppState> = {
  counter: 0
} as const;

export const increment = (store: Store<AppState>) =>
  store.edit((draft) => (draft.counter += 1));

export const decrement = (store: Store<AppState>) =>
  store.edit((draft) => (draft.counter -= 1));

/** UI BINDINGS */

interface StoreProps {
  store: Store<AppState>;
}

const Display = ({ store }: StoreProps) => {
  const counter = useSelected(store, (state) => state.counter);
  return <h1>{counter}</h1>;
};

const IncreaseButton = ({ store }: StoreProps) => (
  <button onClick={() => increment(store)}>Increase</button>
);

const DecreaseButton = ({ store }: StoreProps) => (
  <button onClick={() => decrement(store)}>Decrease</button>
);

export const App = () => {
  const store = useStore(INITIAL_STATE);
  return (
    <>
      <Display store={store} />
      <IncreaseButton store={store} />
      <DecreaseButton store={store} />
    </>
  );
};

```

For now I'll have to go back to jest for half my tests, but not because any functionality is missing in playwright as far as I can see, it's just about transpilation support from the .tsx targets.

**Comment by davidNHK** [comment]
https://github.com/microsoft/playwright/issues/7148

I thought this issue duplicated

But seem component test is heavy demanded 👀

**Comment by mxschmitt** [comment]
As @davidNHK said, if you are interested in component level testing, see #7148.

For having TSX/custom Babel support, see here: #7121

**Comment by pavelfeldman** [comment]
Yup, looks like it folds into either of those above.
