### ISSUE TITLE
[Bug]: Playwright Test loads test files two times

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#7552]
### Playwright version

next

### Operating system

Windows, MacOS, Linux

### What happened? / Describe the bug

See here for the repro: https://github.com/mxschmitt/playwright-test-repro-test-gets-two-times-executed

Reported in https://github.com/microsoft/playwright/issues/7529#issuecomment-877706705

And seems the root cause of https://github.com/microsoft/playwright/issues/7029

### Excpected

```text
Running 1 test using 1 worker

test
  ✓ foo.spec.ts:5:1 › [chromium] should do foo (1ms)


  1 passed (973ms)
```

### Actual

```
test

Running 1 test using 1 worker

test
  ✓ foo.spec.ts:5:1 › [chromium] should do foo (1ms)


  1 passed (973ms)
```

### Note:

- The `test` is logged inside the `foo.spec.ts`.
- A common unexpected behaviour is also when an environment variable gets set in the global setup, its
  - in the first execution not set -> undefined
  - in the second execution its set with the correct value
  - -> so an additional null-check is required to workaround this.

**Comment by pavelfeldman** [comment]
I don't think we can/should work around this. That's how folio is supposed to work.
