### ISSUE TITLE
[Bug]: ERROR: Playwright does not support chromium on mac12

### ISSUE THREAD

**Issue by steverandy** [microsoft/playwright#7555]
### Playwright version

1.12.3

### Operating system

MacOS

### Other information

macOS 12.0 Beta

### What happened? / Describe the bug

Not able to install playwright via npm.

### Relevant log output

```shell
npm ERR! Error: Failed to download chromium, caused by
npm ERR! Error: ERROR: Playwright does not support chromium on mac12
```

**Comment by steverandy** [comment]
Is there a temporary workaround to install playwright on macos v12 beta?

**Comment by yury-s** [comment]
> Is there a temporary workaround to install playwright on macos v12 beta?

You can download Chromium manually and point [`executablePath`](https://playwright.dev/docs/api/class-browsertype#browser-type-launch) to it or use [`channel`](https://playwright.dev/docs/api/class-browsertype#browser-type-launch) with a preinstalled official build of Chrome/Edge.

**Comment by aslushnikov** [comment]
I think this is already fixed on tip-of-tree. Could you please try installing `npm install playwright@next`?

**Comment by steverandy** [comment]
It works on `next` version. Thanks.

**Comment by PetkovBG** [comment]
Hello! What is the solution for this as I encountered the same issue. I am getting an error message stating playwright can't install on Mac12.

**Comment by mxschmitt** [comment]
> Hello! What is the solution for this as I encountered the same issue? I am getting an error message stating playwright can't install on Mac12.

Upgrade Playwright!

**Comment by mxschmitt** [comment]
> Thanks for the quick reply. I am using VS Code and trying to install in the terminal. Would you be able to provide instructions on how I can upgrade it?

`npm install -D @playwright/test@latest`

**Comment by PetkovBG** [comment]
> > Thanks for the quick reply. I am using VS Code and trying to install in the terminal. Would you be able to provide instructions on how I can upgrade it?
> 
> `npm install -D @playwright/test@latest`

Hello! I tried running "npm install -D @playwright/test@latest" in the terminal but I get the error message below:

npm install -D @playwright/test@latest
npm WARN deprecated ecstatic@3.3.2: This package is unmaintained and deprecated. See the GH Issue 259.

-----
Error: ERROR: Playwright does not support chromium on mac12

**Comment by PetkovBG** [comment]
Hello! I tried running "npm install -D @playwright/test@latest" in the terminal but I get the error message below:

npm install -D @playwright/test@latest
npm WARN deprecated ecstatic@3.3.2: This package is unmaintained and deprecated. See the GH Issue 259.

Error: ERROR: Playwright does not support chromium on mac12

Can you give me some advice on what the best way to proceed is?

**Comment by mxschmitt** [comment]
> Hello! I tried running "npm install -D @playwright/test@latest" in the terminal but I get the error message below:
> 
> 
> 
> npm install -D @playwright/test@latest
> 
> npm WARN deprecated ecstatic@3.3.2: This package is unmaintained and deprecated. See the GH Issue 259.
> 
> 
> 
> Error: ERROR: Playwright does not support chromium on mac12
> 
> 
> 
> Can you give me some advice on what the best way to proceed is? 

Maybe you have multiple versions of Playwright installed? Look in the package.json to double check and run npm i afterwards.

**Comment by PetkovBG** [comment]
![image](https://user-images.githubusercontent.com/97334281/201347797-368d24bd-3e4d-49c9-8fd7-8baa9026ffce.png)

This is what the content of my package.json shows:

{
  "name": "softterest",
  "version": "1.0.0",
  "description": "",
  "main": "index.html",
  "scripts": {
    "test": "mocha tests",
    "start": "http-server -a localhost -p 3000 -P http://localhost:3000?"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {},
  "devDependencies": {
    "chai": "4.3.3",
    "http-server": "0.12.3",
    "mocha": "8.3.0",
    "playwright-chromium": "1.9.1"
  }
}

**Comment by mxschmitt** [comment]
I see a very outdated playwright-chromium version!

**Comment by PetkovBG** [comment]
Found a resolution with manually deleting the playwright field from the package.json file and then trying to install it. It worked.
