### ISSUE TITLE
[Bug]: cannot got Iframe dynamic content 

### ISSUE THREAD

**Issue by interiv** [microsoft/playwright#7556]
### Playwright version

1.12

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

```js
"use strict";
const { chromium } = require('playwright');

(async () => {
    const browser = await chromium.launch();
    // Create pages, interact with UI elements, assert values

    let content=await browser.newContext();
    let page=await content.newPage();
    await  page.goto("d:\\a.html");
    let fr=  page.frames();
    console.log(fr[2]);
    let b=await fr[2].$$('body');
console.log(b);



    await browser.close();
})();

```

```html
<html>

<body>
<iframe id="u0" width="100px" height="100px" frameborder="1"></iframe>
<p>there has a frame</p>
<iframe id="u1" width="100px" height="100px" frameborder="1"
        src="javascript:document.write('<body ><p>111111111111</p></body>')"></iframe>

<iframe id="u2" width="100px" height="100px" frameborder="1"></iframe>
</body>
</html>

```

### What happened? / Describe the bug

the  b is null

### Code snippet to reproduce your bug

```js
"use strict";
const { chromium } = require('playwright');
(async () => {
    const browser = await chromium.launch();
    let content=await browser.newContext();
    let page=await content.newPage();
    await  page.goto("d:\\a.html");
    let fr=  page.frames();
    console.log(fr[2]);
    let b=await fr[2].$$('body');
console.log(b);
    await browser.close();
})();
```

### Relevant log output

```shell
null
```

**Comment by yury-s** [comment]
You are querying `body` element on third frame while the content is dynamically loaded in the second one, the following snippet should do the trick:

```js
"use strict";
const { chromium } = require('playwright');
(async () => {
    const browser = await chromium.launch();
    let content=await browser.newContext();
    let page=await content.newPage();
    await  page.goto("d:\\a.html", {waitUntil: 'domcontentloaded'});
    let fr=  page.frames();
    console.log('fr = ' + fr[1]);
    let b=await fr[1].$$('body');
    console.log('b = ' + b);
    await browser.close();
})();

```

With that said what I see is that `fr[2].$$('body')` just hangs instead of returning null which is a bug.

**Comment by interiv** [comment]
not 

> You are querying `body` element on third frame while the content is dynamically loaded in the second one, the following snippet should do the trick:
> 
> ```js
> "use strict";
> const { chromium } = require('playwright');
> (async () => {
>     const browser = await chromium.launch();
>     let content=await browser.newContext();
>     let page=await content.newPage();
>     await  page.goto("d:\\a.html", {waitUntil: 'domcontentloaded'});
>     let fr=  page.frames();
>     console.log('fr = ' + fr[1]);
>     let b=await fr[1].$$('body');
>     console.log('b = ' + b);
>     await browser.close();
> })();
> ```
> 
> With that said what I see is that `fr[2].$$('body')` just hangs instead of returning null which is a bug.

not like you say.

if you can ,got  and print all iframe name .show them.\

**Comment by yury-s** [comment]
Yes, you are right fr[2] is the one being written from js, I apologize for the confusion. However, what I see is that `let b=await fr[2].$$('body');` just hangs I wonder why it returns null for you.

**Comment by interiv** [comment]
`"use strict";
const {chromium} = require('playwright');

(async () => {
    const browser = await chromium.launch();
    let content = await browser.newContext();
    let page = await content.newPage();
    await page.goto("d:\\a.html");



    let f2 = page.frame('u2');
    console.log(f2);
    console.log('-----------------')
    let b2 = await f2.$('body');
    console.log(b2);
    console.log('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
    
    
    let f1 = page.frame('u1');
    console.log(f1);
    console.log('-----------------')
    let b1 = await f1.$('body');
    console.log(b1);



    await browser.close();
})();
`

use this ,you will find out  the bug


and

the a.html 
you can use this.
\

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<iframe id="u0" width="100%" height="100%" frameborder="0" src="b.html"></iframe>
<p>there has a frame</p>
<iframe id="u1" width="100%" height="100%" frameborder="0"
        src="javascript:document.write('<body><input type=\'text\' id=\'abc\'><br> <p>111111111111</p></body>');document.close();"></iframe>

<iframe id="u2" width="100%" height="100%" frameborder="0"></iframe>
</body>
</html>

**Comment by yury-s** [comment]
What I get in this case is `TypeError: Cannot read property '$' of null` because `  let f1 = page.frame('u1');` resolves f1 to null, is that what you see?

**Comment by interiv** [comment]
like I sad .it is a bug

**Comment by yury-s** [comment]
Yes, there seems to be a bug, but in your original report you claimed that in `let b=await fr[2].$$('body');` b was null which is why I wanted to make sure that we are talking about the same issue.

**Comment by interiv** [comment]
fr[0] is  mainFrame
a.html has 3 frame in body .
 you can remove others 2 frame ,keep one frame to test.you will see 2 frame.

it is not importent 
The main problem is that we can't get the iframe content  of dynamic one;

**Comment by pavelfeldman** [comment]
This issue is clear.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
