### ISSUE TITLE
[Feature]: export globals/currentTestInfo() for custom matchers

### ISSUE THREAD

**Issue by florianbepunkt** [microsoft/playwright#7558]
### Feature request

I'm writing a custom matcher that ports additional image comparison algorithms in order to solve my issue in #7548 

Could you please export `currentTestInfo()` from  https://github.com/microsoft/playwright/blob/master/src/test/globals.ts  so wen can import it in our custom matchers like `import { currentTestInfo } from "@playwright/test"`

As far as I know this is the only method to receive snapshots paths and some more test info inside a custom matcher. I can require this file, but this means loosing TS support in IDE.

I think other people writing their own matchers would benefit from this as well.

**Comment by pavelfeldman** [comment]
test.info() will be there as of v1.18.

**Comment by nicojs** [comment]
And how will we get a reference to the `test`?
