### ISSUE TITLE
Missing dependency chrome_elf.dll

### ISSUE THREAD

**Issue by alberspim** [microsoft/playwright#7560]
Running the following test using .NET

```
public async Task Test1()
{
    using var playwright = await Playwright.CreateAsync();
    await using var browser = await playwright.Chromium.LaunchAsync(new() { Headless = false });
    var page = await browser.NewPageAsync();
    await page.GotoAsync("https://playwright.dev/dotnet");
    await page.ScreenshotAsync(new PageScreenshotOptions { Path = "screenshot.png" });
}
```

Results in following error

```

[xUnit.net 00:00:02.01]     PlaywrightDemo.UnitTest1.Test1 [FAIL]
  Failed PlaywrightDemo.UnitTest1.Test1 [1 s]
  Error Message:
   Microsoft.Playwright.PlaywrightException : Host system is missing dependencies!

Full list of missing libraries:
    chrome_elf.dll

  Stack Trace:
     at Microsoft.Playwright.Transport.Connection.SendMessageToServerAsync[T](String guid, String method, Object args)
   at Microsoft.Playwright.BrowserType.LaunchAsync(IEnumerable`1 args, String channel, Nullable`1 chromiumSandbox, Nullable`1 devtools, String downloadsPath, IEnumerable`1 env, String executablePath, Nullable`1 handleSIGINT, Nullable`1 handleSIGTERM, Nullable`1 handleSIGHUP, Nullable`1 headless, Proxy proxy, Nullable`1 timeout, String tracesDir, IEnumerable`1 firefoxUserPrefs, Nullable`1 slowMo, IEnumerable`1 ignoreDefaultArgs, Nullable`1 ignoreAllDefaultArgs)
   at PlaywrightDemo.UnitTest1.Test1() in C:\WS\Tmp\PlaywrightDemo\PlaywrightDemo\UnitTest1.cs:line 13
--- End of stack trace from previous location ---
```
The chrome_elf.dll **IS** present in the following location:
C:\Users\<username>\AppData\Local\ms-playwright\chromium-888113\chrome-win\chrome_elf.dll

NuGet Package: Microsoft.Playwright (Version 1.12.2)
Node.JS: v16.4.2
Dotnet: 5.0.301
OS: Windows 10

**Comment by avodovnik** [comment]
That's an interesting one. I wonder if something could have happened with the installation at some point. My suggestion would be to try reinstalling it. You do that by deleting the `C:\Users<username>\AppData\Local\ms-playwright\chromium-888113\` folder. (or the entire `ms-playwright` one, if you want to do a complete reinstall) and running `playwright install` again. 

Let us know if that fixes it.

**Comment by alberspim** [comment]
First of all thank you for your quick response.

I completely removed the ms-playwright folder and reinstalled.
Because I am behind a corporate proxy the playwright install command fails.

```
Failed to install browsers
Error: Failed to download chromium, caused by
Error: connect ETIMEDOUT 13.107.246.67:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
```

I have installed the Browsers using the command: `npm i -D playwright`

This again downloads chromium, ffmpeg, firefox and webkit. I can start chrome.exe from the chromium-888113/chrome-win folder.

chrome_elf.dll is present
![image](https://user-images.githubusercontent.com/12752414/125578281-c3cdc881-b3ef-4bbe-8a38-c58d1309c19d.png)

Test still fail with same error: Host system is missing dependencies! (chrome_elf.dll)

**Comment by avodovnik** [comment]
@alberspim One quick question, do you have Chrome installed on your system as well (i.e. as a regular browser)?

**Comment by aslushnikov** [comment]
@alberspim is it 32bit windows or 64bit?

**Comment by alberspim** [comment]
@avodovnik 
> @alberspim One quick question, do you have Chrome installed on your system as well (i.e. as a regular browser)?
Yes, Chrome is my regular browser

@aslushnikov 
> @alberspim is it 32bit windows or 64bit?
64bit

> @alberspim also, can you please try running playwright with the `PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS` env variable set to 1? This way we'll see if the chrome launch for you or not.

With env variable set to 1 test won't start. Well it starts, but keeps on waiting. Nothing happens.

**Comment by mxschmitt** [comment]
How did you install the browser since you set a proxy? Did you follow [these](https://playwright.dev/docs/installation#install-behind-the-firewall-or-proxy) introductions?

Executing `playwright install` should work when the HTTP_PROXY env var is set.

**Comment by alberspim** [comment]
@mxschmitt 
> How did you install the browser since you set a proxy? Did you follow [these](https://playwright.dev/docs/installation#install-behind-the-firewall-or-proxy) introductions?
> 
> Executing `playwright install` should work when the HTTP_PROXY env var is set.

I have installed playwright using the command: `npm i -D playwright`

My npm is configured with a .npmrc file which sets both the proxy and https-proxy.

Furthermore I think that some routes are opened in our proxy firewall regarding npm. I do not know what routes are taken using the playwright install command. Maybe some are blocked?

**Comment by aslushnikov** [comment]
> With env variable set to 1 test won't start. Well it starts, but keeps on waiting. Nothing happens.

@alberspim it should timeout in ~30 seconds and tell you where exactly things went south. Does it do it?

> This again downloads chromium, ffmpeg, firefox and webkit. I can start chrome.exe from the chromium-888113/chrome-win folder.

Is this browser fully functional? Can you manually launch it and try navigating to pages?

**Comment by alberspim** [comment]
> > With env variable set to 1 test won't start. Well it starts, but keeps on waiting. Nothing happens.
> 
> @alberspim it should timeout in ~30 seconds and tell you where exactly things went south. Does it do it?
> 
> > This again downloads chromium, ffmpeg, firefox and webkit. I can start chrome.exe from the chromium-888113/chrome-win folder.
> 
> Is this browser fully functional? Can you manually launch it and try navigating to pages?

@aslushnikov 
- It does not timeout in 30 seconds. It just keeps on waiting. (Fun fact: I can see chromium is started in the Task Manager when running the test. Used both headless set to true and false. Same behaviour. Test wont't run, browser not opened/visible)
- I can manually navigate to pages, the browser is fully functional when starting it from `ms-playwright\chromium-888113\chrome-win`

**Comment by alberspim** [comment]
> > With env variable set to 1 test won't start. Well it starts, but keeps on waiting. Nothing happens.
> 
> @alberspim it should timeout in ~30 seconds and tell you where exactly things went south. Does it do it?
> 
> > This again downloads chromium, ffmpeg, firefox and webkit. I can start chrome.exe from the chromium-888113/chrome-win folder.
> 
> Is this browser fully functional? Can you manually launch it and try navigating to pages?

@aslushnikov 
- It does not timeout in 30 seconds. It just keeps on waiting. (Fun fact: I can see chromium is started in the Task Manager when running the test. Used both headless set to true and false. Same behaviour. Test wont't run, browser not opened/visible)
- I can manually navigate to pages, the browser is fully functional when starting it from `ms-playwright\chromium-888113\chrome-win`

**Comment by aslushnikov** [comment]
@alberspim ok, a few more questions.

Since you have Node.js, can you please try running the following 2 scripts:

```js
// a.js
const {chromium} = require('playwright');

(async() => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  console.log(await page.evaluate(() => navigator.userAgent));
  await browser.close();
})();
```

```js
// b.js
const {chromium} = require('playwright');

(async() => {
  const browser = await chromium.launch({
    ignoreDefaultArgs: true,
    args: [
      '--remote-debugging-pipe',
      '--headless',
    ],
  });
  const page = await browser.newPage();
  console.log(await page.evaluate(() => navigator.userAgent));
  await browser.close();
})();
```

**Comment by alberspim** [comment]
@aslushnikov 

Both scripts return the following error

PS C:\WS\Tmp\js> node .\b.js
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

browserType.launch: Host system is missing dependencies!

Full list of missing libraries:
    chrome_elf.dll

Error
    at Object.captureStackTrace (C:\WS\Tmp\js\node_modules\playwright\lib\utils\stackTrace.js:51:19)
    at Connection.sendMessageToServer (C:\WS\Tmp\js\node_modules\playwright\lib\client\connection.js:73:48)
    at Proxy.<anonymous> (C:\WS\Tmp\js\node_modules\playwright\lib\client\channelOwner.js:64:61)
    at C:\WS\Tmp\js\node_modules\playwright\lib\client\browserType.js:59:67
    at BrowserType._wrapApiCall (C:\WS\Tmp\js\node_modules\playwright\lib\client\channelOwner.js:77:34)
    at BrowserType.launch (C:\WS\Tmp\js\node_modules\playwright\lib\client\browserType.js:50:21)
    at C:\WS\Tmp\js\b.js:5:34
    at Object.<anonymous> (C:\WS\Tmp\js\b.js:15:3)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47`

**Comment by aslushnikov** [comment]
@alberspim my bad; I forgot to ask running it with PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS env variable set to 1. 

Secondly, Playwright comes with a program called "PrintDeps.exe" that is located in the `//node_modules/playwright/bin/PrintDeps.exe`. This is our version of LDD-for-windows that reports the missing dependencies.

Could you please launch it, passing a path to the Chromium's .exe file as an argument?

**Comment by alberspim** [comment]
@aslushnikov 

Running PrintDeps.exe results in the following:

```
PS C:\PlaywrightDemo\node_modules\playwright\bin> .\PrintDeps.exe C:\Users\UserName\AppData\Local\ms-playwright\chromium-888113\chrome-win\chrome.exe C:\Users\UserName\AppData\Local\ms-playwright\chromium-888113\chrome-win\chrome.exe
    KERNEL32.dll => C:\windows\System32\KERNEL32.DLL
    VERSION.dll => C:\windows\SYSTEM32\VERSION.dll
    chrome_elf.dll => not found
```

And again checked chrome_elf.dll is still available

![image](https://user-images.githubusercontent.com/12752414/126321659-86580859-7267-4de3-a235-b09cd557be5e.png)

**Comment by aslushnikov** [comment]
@alberspim can you please run [these scripts](https://github.com/microsoft/playwright/issues/7560#issuecomment-880692324) with PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS=1 ?

**Comment by alberspim** [comment]
> @alberspim can you please run [these scripts](https://github.com/microsoft/playwright/issues/7560#issuecomment-880692324) with PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS=1 ?

@aslushnikov My bad, this results in the following

```
PS C:\WS\Tmp\js> node .\a.js
Skipping host requirements validation logic because `PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS` env variable is set.
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/93.0.4530.0 Safari/537.36
PS C:\WS\Tmp\js> node .\b.js
Skipping host requirements validation logic because `PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS` env variable is set.
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/93.0.4530.0 Safari/537.36
PS C:\WS\Tmp\js>
```

**Comment by aslushnikov** [comment]
@alberspim awesome, these are great results!

One more ask: can you please run the following scripts with PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS=1:


```js
// c.js
const {chromium} = require('playwright');

(async() => {
  const browser = await chromium.launch({headless: false});
  const page = await browser.newPage();
  console.log(await page.evaluate(() => navigator.userAgent));
  await browser.close();
})();
```

```js
// d.js
const {chromium} = require('playwright');

(async() => {
  const browser = await chromium.launch({
    ignoreDefaultArgs: true,
    headless: false, 
    args: [
      '--remote-debugging-pipe',
      '--headless',
    ],
  });
  const page = await browser.newPage();
  console.log(await page.evaluate(() => navigator.userAgent));
  await browser.close();
})();
```

**Comment by alberspim** [comment]
@aslushnikov running c.js and d.js gives the following result:
```
PS C:\WS\Tmp\js> node .\c.js                                                                                                      
Skipping host requirements validation logic because `PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS` env variable is set.
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4530.0 Safari/537.36
PS C:\WS\Tmp\js> node .\d.js                                                                                                      
Skipping host requirements validation logic because `PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS` env variable is set.
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/93.0.4530.0 Safari/537.36
PS C:\WS\Tmp\js>                                                                                       
```

Sidenote: I can briefly see chromium browser is started when running c.js. It pops-up quickly and is closed. I do not see this happen when running d.js

**Comment by aslushnikov** [comment]
@alberspim thank you for your time. May I ask you to repeat [this experiment](https://github.com/microsoft/playwright/issues/7560#issuecomment-883343714), this time using a newly built [`PrintDeps.exe`](https://playwright.azureedge.net/builds/winldd/1005/winldd-win64.zip) ?

**Comment by alberspim** [comment]
@aslushnikov Sure! Replaced the "PrintDeps.exe" in folder "C:\WS\Tmp\PlaywrightDemo\node_modules\playwright\bin" with the one you provided.

Running:
```
PS C:\WS\Tmp\PlaywrightDemo\node_modules\playwright\bin> .\PrintDeps.exe C:\Users\UserName\AppData\Local\ms-playwright\chromium-888113\chrome-win\chrome.exe
```
Results in:
```
C:\Users\UserName\AppData\Local\ms-playwright\chromium-888113\chrome-win\chrome.exe
```

**Comment by aslushnikov** [comment]
@alberspim ok, I have more favors to ask for.

1. In [this experiment](https://github.com/microsoft/playwright/issues/7560#issuecomment-883343714), can you please `cd` into the `C:\Users\UserName\AppData\Local\ms-playwright\chromium-888113\chrome-win\` directory and run `PrintDeps.exe`:

```
PS C:\Users\UserName\AppData\Local\ms-playwright\chromium-888113\chrome-win> C:\PlaywrightDemo\node_modules\playwright\bin\PrintDeps.exe .\chrome.exe
```

2. Now, if the command in (1) shows any "not found" libraries, I cooked a [new build of `PrintDeps.exe`](https://send.vis.ee/download/156fb809bdb839d1/#0mTkP0rTqIciWnT_1jbViQ) that might help. Could you please download it and do the same thing?

**Comment by alberspim** [comment]
@aslushnikov
Running the command as requested results in the following:
```
PS C:\Users\UserName\AppData\Local\ms-playwright\chromium-888113\chrome-win> C:\WS\Tmp\PlaywrightDemo\node_modules\playwright\bin\PrintDeps.exe .\chrome.exe
.\chrome.exe
Failed to load .\chrome.exe  Error: The parameter is incorrect.
```
It can be run using the following
```
PS C:\Users\UserName\AppData\Local\ms-playwright\chromium-888113\chrome-win> C:\WS\Tmp\PlaywrightDemo\node_modules\playwright\bin\PrintDeps.exe C:\Users\UserName\AppData\Local\ms-playwright\chromium-888113\chrome-win\chrome.exe
C:\Users\UserName\AppData\Local\ms-playwright\chromium-888113\chrome-win\chrome.exe
```
It then only outputs the file path of chrome.exe

As for request 2
My corporate firewall blocks the download using this URL (send.vis.ee). I was able to download the other version using the route you mentioned here (playwright.azureedge.net):

> @alberspim thank you for your time. May I ask you to repeat [this experiment](https://github.com/microsoft/playwright/issues/7560#issuecomment-883343714), this time using a newly built [`PrintDeps.exe`](https://playwright.azureedge.net/builds/winldd/1005/winldd-win64.zip) ?

**Comment by aslushnikov** [comment]
ok, I give up :( there's only so much we can do blindly, without being able to repro locally.

@alberspim I'll close this issue for now since it's not actionable any more. If there's a good repro, please feel free to re-file!
