### ISSUE TITLE
[Feature]: High level drag api

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright#7562]
### Feature request

Now that we have support for drag and drop via mousedown/mousemove/mouseup, its time to create a high level `page.dragAndDrop` api.

**Comment by klhex** [comment]
It would be cool if the API offered not only coordinates or a relative distance as an option to specify the destination but also most/all of the element selectors. See Taiko API: https://docs.taiko.dev/api/draganddrop/

**Comment by mxschmitt** [comment]
Closing since it was implemented in https://github.com/microsoft/playwright/pull/6910.
