### ISSUE TITLE
[BUG] Chromium fullPage screenshot mistreats vh and vw units

### ISSUE THREAD

**Issue by KartoffelToby** [microsoft/playwright#757]
I tested a very basic code with playwright. to take a fullpage screenshot of a webpage with a css typed header thats using `height: 65vh;`

The problem here with pupeeter is that the viewport haven't any relation to the vh. so the Screenshot has the wrong result. Playwright with chroimuim have the same problem.

But playwright with Firefox Headless Browser take the right result.

So i think the core bug is in Chroimuim.

Are there any Solutions that all 3 Browsers can handle CSS vh and vw with the right viewport?

My testing code is:

```
const playwright = require('playwright');

(async () => {
  for (const browserType of ['chromium', 'firefox']) {
    const browser = await playwright[browserType].launch({
      args: [
        '--disable-gpu',
        '--no-sandbox',
        '--disable-web-security',
        '--disable-dev-profile'
      ]
    });

    const  context = await browser.newContext({
      viewport: {
        width: 1920,
        height: 1080
      }
    });
    
    const page = await context.newPage('https://elements.t-haber.de/');
    await page.screenshot({ path: `example-${browserType}.png` , fullPage: true });
    await browser.close();
  }
})();
```

**Comment by duytran-agilityio** [comment]
I saw the same issue. I see the results are different between Firefox and Chromium. Firefox has a better results.

**Comment by Prior99** [comment]
I have the same issue with an even more basic site. Chromium just doesn't screenshot the whole page.

**Comment by Lemaro86** [comment]
I have the same issue

**Comment by mxschmitt** [comment]
Should be fixed in https://github.com/microsoft/playwright/pull/10606
