### ISSUE TITLE
Firefox not firing "requestfailed" event even when request fails in Dev Tools Network tab

### ISSUE THREAD

**Issue by gomisha** [microsoft/playwright#7570]
I'm trying to check all failed requests that my extension blocks.

I'm manually loading my extension into Firefox by sleeping to give enough time to load the extension manually like this:

![image](https://user-images.githubusercontent.com/15269764/125362951-c1458100-e33d-11eb-9182-3762c0def0d1.png)

I also open Dev Tools Network tab so I can confirm that some domains / requests are getting blocked:

![image](https://user-images.githubusercontent.com/15269764/125363206-35802480-e33e-11eb-944c-577a2f2c339a.png)

I registered to receive these blocked / failed requests like this in my Playwright code:

```
    this.extensionBrowserContext.on("requestfailed", request => {
        this.expectedRedListSet.add(this.extractDomainName(request.url()));
    });

```

But I'm not getting anything fired for this event.

The same code works for Chrome and Edge where I can load the extension automatically using a persistent browser context. I don't understand why Firefox isn't firing the requestfailed event.

**Comment by yury-s** [comment]
Playwright doesn't support extensions in Firefox at the moment, see [this issue](https://github.com/microsoft/playwright/issues/2874). If the failing requests are issues by the extension's background pages you won't see them in the context listener. Please vote for that feature request if you need extension support in FF.
