### ISSUE TITLE
[Question]: How to set the disable-web-security as an args in playwright.config.ts

### ISSUE THREAD

**Issue by yusoof-pret** [microsoft/playwright#7574]
### Your question

Some of the frame are not loading in the browser (chrome and firefox), I believe it may be because of different domain. How to set the disable-web-security as an args in playwright.config.ts.

**Comment by yury-s** [comment]
You can set [`bypassCSP`](https://playwright.dev/docs/api/class-browser#browser-new-context) option like this:

```typescript
const config: PlaywrightTestConfig = {
  use: {
    contextOptions: {
      bypassCSP: true
    }
  },
};
```
