### ISSUE TITLE
[Question]: Screenshot comparison inside Page Model

### ISSUE THREAD

**Issue by UnderTheMoonspell** [microsoft/playwright#7579]
### Your question

I created a class to abstract some of my tests like so:

![image](https://user-images.githubusercontent.com/10156878/125446171-117aeee3-f2a4-4091-aff1-f7f3e72d529f.png)

And this is my test :

![image](https://user-images.githubusercontent.com/10156878/125446222-ee9425d1-dc00-4a7e-a13e-c8e9f45996d4.png)

If I change the color of a h1 I have and run the tests with the takeScreenshotAndCompare function inside the class all the tests pass, if I use the toMatchSnapshot function direcly in the tests it detects the change in color and fails. Could anyone explain to me why is this? I've started using Playwright. a couple of days ago so I'm still learning the ins and outs.

**Comment by yury-s** [comment]
It should make any difference. Could it be that the threshold has some weird value in the POM?

**Comment by UnderTheMoonspell** [comment]
It doesnt. Its the same 0.2 

![image](https://user-images.githubusercontent.com/10156878/125455258-43635631-cb80-4e54-9179-eb3ce916dbdb.png)

**Comment by yury-s** [comment]
Can you share a minimal reproduction example? The following code works just fine:

```typescript
// utils/pom.ts
import { expect } from "@playwright/test";
import { Page } from "playwright";

export class MyPage {
    page: Page;
    constructor(page: Page) {
        this.page = page;
    }

    async test() {
      expect(await this.page.screenshot({fullPage: true})).toMatchSnapshot(`test.png`, {threshold: 0.2});
    }
}

// tests/example.spec.ts
import { expect, test } from '@playwright/test';
import { MyPage } from '../utils/pom';

test('should work', async ({ page, browser, contextOptions }, testInfo) => {
  await page.goto('http://localhost/');
  expect(await page.screenshot({fullPage: true})).toMatchSnapshot(`test.png`, {threshold: 0.2});
  await new MyPage(page).test();
});


```

**Comment by UnderTheMoonspell** [comment]
> Can you share a minimal reproduction example? The following code works just fine:
> 
> ```ts
> // utils/pom.ts
> import { expect } from "@playwright/test";
> import { Page } from "playwright";
> 
> export class MyPage {
>     page: Page;
>     constructor(page: Page) {
>         this.page = page;
>     }
> 
>     async test() {
>       expect(await this.page.screenshot({fullPage: true})).toMatchSnapshot(`test.png`, {threshold: 0.2});
>     }
> }
> 
> // tests/example.spec.ts
> import { expect, test } from '@playwright/test';
> import { MyPage } from '../utils/pom';
> 
> test('should work', async ({ page, browser, contextOptions }, testInfo) => {
>   await page.goto('http://localhost/');
>   expect(await page.screenshot({fullPage: true})).toMatchSnapshot(`test.png`, {threshold: 0.2});
>   await new MyPage(page).test();
> });
> ```

Does this work if you comment the `await new MyPage(page).test();` ?

**Comment by pavelfeldman** [comment]
Is there anything we could try running locally to reproduce this? We need a reproduction scenario that we can run and yours relies upon your local server and helper files.
