### ISSUE TITLE
[Bug]: Iframe not loading in chromium and firefox  

### ISSUE THREAD

**Issue by yusoof-pret** [microsoft/playwright#7582]
### Playwright version

1.12.3

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium

### Other information

Your browser does not support iframes.. this is happening with chromium and firefox. The Iframe is not loading and the section is disabled.

![image](https://user-images.githubusercontent.com/84907221/125468087-7f4918ce-0f5a-4483-89dc-84e3d80d39c7.png)

This is happening only with chromium launched using Playwright

### What happened? / Describe the bug

Your browser does not support iframes. this is happening with chromium and firefox. The Iframe is not loaded and the section is disabled.

```js
module.exports = {
  testDir: "src/specs",
  timeout: 70000,
  forbidOnly: !!process.env.CI,
  bypassCSP: true,
  retries: 0,
  workers: process.env.CI ? 2 : undefined,
  use: {
    headless: true,
    browserName: "chromium",
    contextOptions: {
      bypassCSP: true,
    },
  },
  projects: [
    {
      name: "chromium",
      use: { browserName: "chromium" },
    },
  ],
};
```

**Comment by mxschmitt** [comment]
Where do you get the error message `Your browser does not support iframe` from? Having a URL for that to reproduce it ourselves would be awesome.

**Comment by yusoof-pret** [comment]
https://lab.pret.co.uk/en-GB
hopefully you will be able to signup and navigate to the url https://lab.pret.co.uk/en-GB/pretcoffeesub/checkout . you will find the payment section where the cardnumber and cvc are disabled.

**Comment by yusoof-pret** [comment]
did you had chance to look into the issue?

**Comment by pavelfeldman** [comment]
Sorry, we don't sign in to the accounts that verify phone. Where do you see the error message? Could you open DevTools and tell us what you see in the console? I noticed you disabled CSP, why did you do that?

**Comment by yusoof-pret** [comment]
![image](https://user-images.githubusercontent.com/84907221/126310683-fab6daf0-bf11-4b78-af40-95e4f0bf6988.png)
The reason  I did set the bypassCSP to true is because the iframe has different domain from the app. 

If I launch the page from a browser not with playwright I could see the below
![image](https://user-images.githubusercontent.com/84907221/126311255-238458ac-be2f-4704-b25c-1631c2df056a.png)

**Comment by yusoof-pret** [comment]
also if you want to bypass the phone validation please use the email with the format below this should bypass the phone validation check
pret-cypress-test-a567d686-125c-4ce1-83e2-ab637ad93318@mailinator.com

**Comment by pavelfeldman** [comment]
So there are some error in the console, I was asking to see what is in Console. I suspect it'll tell that the iframe you are trying to embed is not embeddable across origins.

**Comment by yusoof-pret** [comment]
Thanks for looking into the issue. Following is what I can see in the console. 
![image](https://user-images.githubusercontent.com/84907221/126443773-b74d3791-65ff-42ca-b9af-ca0bc6a2ab92.png)

**Comment by yusoof-pret** [comment]
Do we have any work around for this?

**Comment by pavelfeldman** [comment]
Unfortunately I can't reproduce this issue and we haven't seen anyone else running into it. We need a local or a public reproduction to be able to help...

**Comment by yusoof-pret** [comment]
Please find the script below : run the command to debug 'PWDEBUG=1 npm run test' .  You will notice the card section has the frame disabled. Hope this helps in reproducing the issue. 
test.describe("Buy Coffee subscription", () => {
  test("testing", async () => {
    const browser = await chromium.launch({
      args: ["--disable-web-security"],
      headless: false,
    });
    const page = await browser.newPage();

    await page.goto("https://lab.pret.co.uk/en-GB", {
      waitUntil: "domcontentloaded",
    });
    await page.goto("https://lab.pret.co.uk/en-GB/pretcoffeesub/signup", {
      waitUntil: "networkidle",
    });
    const email = `pret-cypress-test-${uuidv4()}@mailinator.com`;
    await page.click("button:has(span:has-text('Create an account'))");
    await page.fill("[data-testid='name']", "firstname");
    await page.fill("[data-testid='lastName']", "lastname");
    await page.fill(
      "[data-testid='mobile-number']",
      `07${Math.floor(100000000 + Math.random() * 900000)}`
    );
    await page.fill("[data-testid='email']", email);
    await page.fill("[data-testid='confirmEmail']", email);
    await page.fill("[data-testid='password']", "Test@123");
    await page.click("button[type='submit']");
    await page.waitForLoadState("domcontentloaded");
    await page.fill(
      ".adyen-checkout__card__holderName  input",
      "cardHolderName"
    );
  });

**Comment by pavelfeldman** [comment]
It works for me:

<img width="521" alt="Screen Shot 2021-07-22 at 2 32 52 PM" src="https://user-images.githubusercontent.com/883973/126712282-4286b611-a72b-4281-be78-8534d690d4f7.png">

**Comment by yusoof-pret** [comment]
Could you please guide me with the package. I am using  "playwright": "^1.13.0-1626828370000" . Will that make any difference. .

**Comment by yusoof-pret** [comment]
I got it working when I upgrade the version of playWright to the latest. Thanks. So Closing it.
