### ISSUE TITLE
How to know the style of an element, such as: the size of the element, the location of the page, etc.  

### ISSUE THREAD

**Issue by 000xiaoxiao000** [microsoft/playwright#7596]
### Playwright version

1.12.0

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

How to know the style of an element, such as: the size of the element, the location of the page, etc.

**Comment by aslushnikov** [comment]
check out the [`elementHandle.boundingBox()`](https://playwright.dev/docs/api/class-elementhandle#element-handle-bounding-box) API!

**Comment by 000xiaoxiao000** [comment]
Use page, which API?  

> check out the [`elementHandle.boundingBox()`](https://playwright.dev/docs/api/class-elementhandle#element-handle-bounding-box) API!

Use page, which API?  

How to Verify Images
