### ISSUE TITLE
[Bug]: Webserver should run before global-setup

### ISSUE THREAD

**Issue by plessbd** [microsoft/playwright#7597]
### Playwright version

@next

### What happened? / Describe the bug

related to #7368

When using @next with the webserver config global-setup runs first. (I want to use e2e tests in an angular project)

where global-setup is being used to create an initial state as per https://playwright.dev/docs/auth#reuse-authentication-in-playwright-test this will fail as the webserver has not started.

I have tested a fix by moving the webserver line up before global-setup and it "works", but I have not built any tests
https://github.com/microsoft/playwright/blob/master/src/test/runner.ts#L170-L173

### Code snippet to reproduce your bug

```shell
import { PlaywrightTestConfig } from '@playwright/test';
const config: PlaywrightTestConfig = {
    webServer: {
        command: 'npx ng serve',
        timeout: 120 * 1000,
    },
    globalSetup: require.resolve('./global-setup'),
    use: {
        // Browser options
        slowMo: 50,

        // Context options
        //viewport: { width: 2048, height: 1280 },
        ignoreHTTPSErrors: true,
        //permissions:['clipboard-read'],

        // Artifacts
        screenshot: 'only-on-failure',
        video: 'retry-with-video',
    },
};
export default config;


```typescript
import { firefox } from '@playwright/test';

async function globalSetup() {
  //const browser = await firefox.launch();
  const browser = await firefox.launch({});

const context = await browser.newContext({
    ignoreHTTPSErrors: true
});
  const page = await context.newPage();
  //const page = await browser.newPage();
  await page.goto(`${process.env.PLAYWRIGHT_TEST_BASE_URL}/login`);
  await page.fill('input[type="text"][name="username"]', process.env.USERNAME);
  await page.fill('input[type="password"][name="password"]', process.env.PASSWORD);
  await page.click('input[type="submit"]');
  await page.waitForTimeout(2000)
  await page.context().storageState({ path: 'state.json' });
  await browser.close();
}

export default globalSetup;
```

**Comment by zomars** [comment]
Hey @mxschmit I can confirm that this is happening again.

**Comment by zomars** [comment]
Also it seems that globalSetup just timeouts in CI like GitHub Actions. Here's an example:

https://github.com/calcom/cal.com/runs/5206065056?check_suite_focus=true

**Comment by mxschmitt** [comment]
> Also it seems that globalSetup just timeouts in CI like GitHub Actions. Here's an example:
> 
> https://github.com/calcom/cal.com/runs/5206065056?check_suite_focus=true

Please file a new separate issue!
