### ISSUE TITLE
[Question]: use of interface Page in Playwright vs ElementFinder/ElementArrayFinder in Protractor

### ISSUE THREAD

**Issue by kshrestha99** [microsoft/playwright#7598]
### Your question

When using Protractor, I can do this:

In a Page object class:

```
// locators
public readonly myElement  = element(by.css('.myClass')  // or $('.myClass')

public async myElementMethod(): Promise<void> {
    await myElement.click();
}

```
And in test runner file, I can simply call that method after instantiating the page object:
```
....
await browser.get(browser.baseUrl + endPoint);
....
....
await myPageObject.myElementMethod();

```

The above way does not require a page constructor and so the elements can be used as parameters/arguments in helper methods or other files without needing a page context.

But in Playwright, I have to first have a constructor for a Page like this:
In a Page object class:

```
readonly page: Page;
  constructor(page: Page) {
    this.page = page;
  }

 //locators:
 public readonly myElement  = '.myClass';

public async myElementMethod(): Promise<void> {
     await this.page.click(this.myElement);
}

```
This playwright process works, but the constructor overhead means I need to have a constructor even in the helper-method class. Is there a way to NOT have a constructor and use something similar to Protractor?
Looking for advice for page object pattern. 
Thank you!

**Comment by aslushnikov** [comment]
@kshrestha99 First of all: we do discuss locators API, inspired by protractor. There's a vague tracking bug at https://github.com/microsoft/playwright/issues/7565 - feel free to upvote to get updates when it's fixed and locators are landed.

> This playwright process works, but the constructor overhead means I need to have a constructor even in the helper-method class. Is there a way to NOT have a constructor and use something similar to Protractor?

The locators that we discuss is a sugar around the `(page, selector)` pair. So instead of passing both to the helper functions, you'll be able to create a locator and use it:

```js
// without locators, with selectors - today's world
async function countRowsSelector(page, tableSelector) {
  // Some logic to count rows in the given table in a page
}
console.log(await countRowsSelector(page, '#table'));

// same function with locators
async function countRowsLocator(tableLocator) {
  // Some logic to count rows in the given table. NOTE: tableLocator
  // has all the similar API's like `page`
}
const tableLocator = page.createLocator('#table'); // not final API - just for illustrative purposes
console.log(await countRowsLocator(tableLocator));
``` 

Would this work for you?

**Comment by kshrestha99** [comment]
@aslushnikov Thank you for the suggestion of using page and element locator as two arguments. That will also work but this means that all those methods will have an extra argument. But if there is no other solution, I will probably just stick to putting a constructor for the helper class too.

**Comment by aslushnikov** [comment]
> But if there is no other solution, I will probably just stick to putting a constructor for the helper class too.

Yep this is fine. It'll also make it very easy to do multitab tests for you; doing multitab tests in protractor would be more painful!

**Comment by pavelfeldman** [comment]
Locators landed
