### ISSUE TITLE
[Bug]: Providing 'page' as parameter in child class new instance displays error in WebStorm IDE but doesn't display in Visual Studio Code

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#7602]
### Playwright version

1.12.3

### Operating system

Windows

### Other information

**Windows version:** 10
**Visual Studio Code version:** 1.57.1
**WebStorm version:** 2021.1.2

### What happened? / Describe the bug

I've created a little project that uses the Page Object Model pattern with Typescript.
I've created it with a Visual Studio Code IDE. 
I have a **BasePage.ts** class that has child classes. The **BasePage.ts** class has a constructor that gets **page: Page** as a parameter:

![image](https://user-images.githubusercontent.com/52656401/125594038-05f57f2f-7425-4dbc-afd5-d0d03ae22f04.png)

As mentioned, the child class extends the **BasePage.ts** class without overriding the constructor. Example from the class **RegisterForm.ts** class:

![image](https://user-images.githubusercontent.com/52656401/125594323-533678ad-3756-45b4-ae56-ce1618ca63c3.png)

Then, in the test files, I create a new instance of every required class. Due to inheritance, I need to provide a **page: Page** parameter to every instance of a class that extends from a **BasePage.ts** class. 
In the Visual Studio Code IDE I have a regular behavior: 

![image](https://user-images.githubusercontent.com/52656401/125594849-5c174a15-ec1d-49fd-9589-5d7193c5ecfd.png)

In the WebStorm IDE I get the errors:

![image](https://user-images.githubusercontent.com/52656401/125595052-fc9158d7-28ee-4d4b-abae-e39228617e44.png)

Example of the error:

![image](https://user-images.githubusercontent.com/52656401/125595737-56c875b0-f5e6-4a52-a181-450542765119.png)

Another error:

![image](https://user-images.githubusercontent.com/52656401/125595911-a8b3a876-4073-4703-8817-78405cb5abae.png)

Does this behavior has some explanation? Or does it a bug?

### Code snippet to reproduce your bug

```shell
import { test, expect, Page, BrowserContext } from "@playwright/test";
import BasePage from "../../common/BasePage";
import Header from "../components/Header";
import RegisterForm from "../components/RegisterForm";
import ApplicationUrl from "../../helpers/applicationUrl";

test.describe("User Registrarion Feature/", () => {
  let basePage: BasePage;
  let header: Header;
  let registerForm: RegisterForm;
  let page: Page;
  let context: BrowserContext;

  test.beforeAll(async ({ browser }) => {
    context = await browser.newContext({});
    
    await context.tracing.start({
      screenshots: true,
      snapshots: true,
    });
    page = await context.newPage();
    basePage = new BasePage(page);
    header = new Header(page);
    registerForm = new RegisterForm(page);
  });

  test.beforeEach(async () =>{
    await basePage.loadApplication(ApplicationUrl.ESRO);
  });

  test.afterAll(async() => {
    await context.tracing.stop({
      path: "trace.zip"
    })
  })

  test.afterEach(async()=> {
    await context.clearCookies();
  })

  test("Register with special offers", async ({}) => {
    let firstName = basePage.getRandomFirstName;
    let lastName = basePage.getRandomLastName;
    let email = basePage.getRandomMail;
    let phone = basePage.getRandomPhone;
    // await page.pause();
    
    await header.openRegisterForm();
    await registerForm.fillRegisterFormWithSkip(firstName, lastName, email, phone);
    await header.validateUserDetails(firstName, lastName);
  });

  test("Register without special offers", async ({}) => {
    let firstName = basePage.getRandomFirstName;
    let lastName = basePage.getRandomLastName;
    let email = basePage.getRandomMail;
    let phone = basePage.getRandomPhone;
    // await page.pause();
    
    await header.openRegisterForm();
    await registerForm.fillRegisterFormWithContactMe(firstName, lastName, email, phone);
    await header.validateUserDetails(firstName, lastName);
  });


  
});
```

**Comment by badsyntax** [comment]
Perhaps because you're importing the `Page` type from different packages? 

BasePage is using `import { Page } from 'playwright` but your test file is using `import {  Page } from "@playwright/test";`

Have you tried using the `Page` type from `@playwright/test` in your BasePage?

**Comment by AlexKomanov** [comment]
@badsyntax 
Thanks a lot. My mistake.
Works perfectly!
