### ISSUE TITLE
[Feature]: add option test.Each and test.describe.Each

### ISSUE THREAD

**Issue by ViaMay** [microsoft/playwright#7607]
### Feature request

I will be good to have option like https://jestjs.io/ru/docs/api#testeachtablename-fn-timeout and https://jestjs.io/ru/docs/api#describeeachtablename-fn-timeout  for this: https://playwright.dev/docs/test-intro/#use-test-hooks

I know I can use 'for')

**Comment by mxschmitt** [comment]
Seems like a duplicate of #7036, please add to that issue why for of is currently not working for you. Thanks!

**Comment by ViaMay** [comment]
@mxschmitt yep
