### ISSUE TITLE
[Bug]: Error: ENOENT: no such file or directory, open '...\test1\test2\snapshot-name-expected.png

### ISSUE THREAD

**Issue by ViaMay** [microsoft/playwright#7609]
### Playwright version

1.12.3

### Other information

node v14.17.1
npm 6.14.13
"@playwright/test": "^1.12.3",
"playwright": "^1.12.3"

### What happened? / Describe the bug

**Actual refult:**
if we run test we will have a error:
 1) tests\tests\test.js:3:1 › [Chromium] test =====================================================

    Error: ENOENT: no such file or directory, open 'C:\..\src\test-results\tests-tests-test.js-test-Chromium\test1\test2\snapshot-name-expected.png'

       9 |      await page.goto('data:text/html,<label>Logo Text *</label>');
      10 |      images = await page.screenshot({fullPage: true});
    > 11 |      expect(images).toMatchSnapshot('test1/test2/snapshot-name.png');
                   ^

**Expected refult:** I want to see screenshots that show the differences between the expected screenshot and actual screenshot. Now the folder is being created but it is empty
![image](https://user-images.githubusercontent.com/10914859/125646437-783e2fc1-6912-465f-9154-09a3fb7b01e1.png)

### Code snippet to reproduce your bug

```shell
const { expect, test } = require('@playwright/test');

test('test', async ({ page }) => {

	await page.goto('data:text/html,<label>Text *</label>');
	let images = await page.screenshot({fullPage: true});
	expect(images).toMatchSnapshot('test1/test2/snapshot-name.png');

	await page.goto('data:text/html,<label>Logo Text *</label>');
	images = await page.screenshot({fullPage: true});
	expect(images).toMatchSnapshot('test1/test2/snapshot-name.png');
});


config:

module.exports = {
  // Put any shared options on the top level.
  use: {
    headless: false,
  },
  screenshot: 'only-on-failure',
  timeout: 30000,
  workers: 3,
  testMatch: 'tests/tests/test.js',
  projects: [
    {
      name: 'Chromium',
      use: { browserName: 'chromium' },
    },
  ],
};
```

### Relevant log output

```shell
Using config at C:...\src\tests\playwright.config.js

Running 1 test using 1 worker

  x 1) tests\tests\test.js:3:1 › [Chromium] test (936ms)


  1) tests\tests\test.js:3:1 › [Chromium] test =====================================================

    Error: ENOENT: no such file or directory, open 'C:...\src\test-results\tests-tests-test.js-test-Chromium\test1\test2\snapshot-name-expected.png'

       9 |      await page.goto('data:text/html,<label>Logo Text *</label>');
      10 |      images = await page.screenshot({fullPage: true});
    > 11 |      expect(images).toMatchSnapshot('test1/test2/snapshot-name.png');
         |                     ^
      12 | });
      13 |

        at Object.openSync (fs.js:498:3)
        at Object.writeFileSync (fs.js:1524:35)
        at Object.compare (C:...\src\node_modules\@playwright\test\lib\test\golden.js:119:18)
        at Object.toMatchSnapshot (C:...\src\node_modules\@playwright\test\lib\test\expect.js:37:40)
        at __EXTERNAL_MATCHER_TRAP__ (C:..\src\node_modules\expect\build\index.js:342:30)
        at Object.throwingMatcher (C:...\src\node_modules\expect\build\index.js:343:15)
        at C:...\src\tests\tests\tests\test.js:11:17
        at WorkerRunner._runTestWithBeforeHooks (C:..\src\node_modules\@playwright\test\lib\test\workerRunner.js:290:13)


  1 failed
    tests\atoms\test.js:3:1 › [Chromium] test ======================================================
npm ERR! Test failed.  See above for more details.

Process finished with exit code 1
```

**Comment by aslushnikov** [comment]
@ViaMay The error is cryptic indeed - that's a bug, we'll fix it.

However, do you intentionally compare two different pages to the same snapshot? The following worked just fine for me (pay attention to the last line in the test):

```js
const { expect, test } = require('@playwright/test');

test('test', async ({ page }) => {

	await page.goto('data:text/html,<label>Text *</label>');
	let images = await page.screenshot({fullPage: true});
	expect(images).toMatchSnapshot('test1/test2/snapshot-name.png');

	await page.goto('data:text/html,<label>Logo Text *</label>');
	images = await page.screenshot({fullPage: true});
        // NOTICE: snapshot-name2.png
	expect(images).toMatchSnapshot('test1/test2/snapshot-name2.png');
});
```

**Comment by ViaMay** [comment]
@aslushnikov This is a fake test for us to show an error)
In fact, when my test fails because the screenshot does not match the expected screenshot, I just cannot see what the problem is. I have to update the screenshot and see the error with my eyes (

**Comment by dgozman** [comment]
@ViaMay The problem here is that you use `test1/test2/snapshot-name.png` as a snapshot name, probably meaning some relative path? After #7620, you should see the 'expected/received/diff' error message now.

That said, we are not going to treat `test1/test2/snapshot-name.png` as a path. I'd suggest to replace it with something like `test1-test2-snapshot-name.png` or just `snapshot-name.png` to avoid confusion.

**Comment by ViaMay** [comment]
@dgozman the solution #7620  will suit me . Can you tell us about when it can be expected on prod?

**Comment by mxschmitt** [comment]
You can try it out today via `npm install @playwright/test@next` or wait a few days until 1.13.0 gets released.
