### ISSUE TITLE
[Bug]: Self signed certificate doesn't work for Docker

### ISSUE THREAD

**Issue by JoFrMueller** [microsoft/playwright#7611]
### Playwright version

1.12.3

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium, Firefox

### Other information

Current Docker image from mcr.microsoft.com/playwright:focal

### What happened? / Describe the bug

As long as we run `playwright` outside (for Windows 10) of Docker it picks up the locally installed SSL certificates correctly.

`curl -v` inside of Docker works correctly as well and picks up the custom certificates, but it seems that the Browsers don't expect the same.

But what has to be done for Docker so that the Browsers that `playwright` brings consider the custom SSL certificates just like other binaries do? We **don't want to use the following** property on the Browser configuration:

```json
ignoreHTTPSErrors: true
```

We just want the Docker image to behave the same like the native experience.

### Relevant log output

```shell
page.goto: net::ERR_CERT_AUTHORITY_INVALID at https://integration.user.ui.domain.local

page.goto: SEC_ERROR_UNKNOWN_ISSUER
```

**Comment by aslushnikov** [comment]
@JoFrMueller could you please try launching docker with `--network host` option?

**Comment by JoFrMueller** [comment]
Why? [Docker documentation](https://docs.docker.com/network/host/)

Could you explain how this should be related?

`curl -v` does work correctly (inside of Docker) and picks up the enterprise certificates from within the container itself correctly. It doesn't pick up anything from the host. And neither it should!

I have to somehow explain towards FireFox and Chrome to also pick up the Docker container added certificates - just like `curl -v` does by default.

We actually do this kind of enterprise SSL certificate Docker stuff for a lot of containers that execute different kind of tests. It seems to be some kind of "a missing flag error" for the Browsers used/provided by `playwright`.

**Comment by aslushnikov** [comment]
@JoFrMueller wait, I'm confused. Do I understand correctly that you have your own docker image atop of Playwright's official where you add a self-signed certificate?

**Comment by JoFrMueller** [comment]
@aslushnikov exactly.

Or we just add the self-signed certificate as part of the `Dockerfile` that executes the `playwright` tests. There's no difference...

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by sshishov** [comment]
Issue is still happening and should be reopened.

Setup, official docker image slightly overriden to inject self signed certificates inside `/usr/local/share/ca-certificates/`, modified entrypoint to "update" certificates using `/usr/sbin/update-ca-certificates` and just copied tests.

I can observe the same error:
```
Error: page.goto: net::ERR_CERT_AUTHORITY_INVALID at https://my.great.localhost/
Call log:
  - navigating to "https://my.great.localhost/", waiting until "load"


   6 |   test('...', async ({ page }) => {
>  8 |     await page.goto('...');

    at /path/test.spec.ts:8:16

```

And at the same time `curl` is working without any issues and without ignoring SSL errors

**Comment by lobrau** [comment]
Also having this issue still. It should be reopened. I'm using custom certificates and the only way to make it work is still to ignoreHTTPSErrors: true

**Comment by neongreen** [comment]
> Do I understand correctly that you have your own docker image atop of Playwright's official where you add a self-signed certificate?

I also do exactly this -- add a mkcert certificate root to the system store and to NODE_EXTRA_CA_CERTS. `curl -v` is fine. Still getting `Error: page.goto: net::ERR_CERT_AUTHORITY_INVALID` from Playwright.
