### ISSUE TITLE
[Feature]: Add social image to Playwright repository

### ISSUE THREAD

**Issue by mskelton** [microsoft/playwright#7618]
### Feature request

When viewing the Playwright repo in GitHub Explore, there is no social image.  Might be nice to add the Playwright logo as the social image for this repo so it shows up nicer in explore.

Here is how it currently looks:

<img width="782" alt="Screen Shot 2021-07-14 at 3 45 05 PM" src="https://user-images.githubusercontent.com/25914066/125690502-8162783b-ac4b-47a7-9a81-b800c3406d5f.png">

**Comment by aslushnikov** [comment]
@mxschmitt explained that this social image is what shows up at https://github.com/topics/e2e-testing

**Comment by aslushnikov** [comment]
We have an image now!
