### ISSUE TITLE
[feature] support 'microphone' permission on Firefox

### ISSUE THREAD

**Issue by 2007anu** [microsoft/playwright#7635]
### Your question

Using playwright@1.12.3 with Node js, 

Below code is giving error:

```
  const context = await browser.newContext();
  const cars = ["microphone", "camera"];
  context.grantPermissions(cars);

  const page = await context.newPage();
```

Error:
```
(node:67404) UnhandledPromiseRejectionWarning: browserContext.grantPermissions: Unknown permission: microphone
    at Proxy.<anonymous> (\node_modules\playwright\lib\client\channelOwner.js:64:61)
    at \node_modules\playwright\lib\client\browserContext.js:190:27
    at BrowserContext._wrapApiCall (\node_modules\playwright\lib\client\channelOwner.js:77:34)
    at BrowserContext.grantPermissions (\node_modules\playwright\lib\client\browserContext.js:189:21)
    at\main.js:7:11
(Use `node --trace-warnings ...` to show where the warning was created)
(node:67404) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:67404) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aslushnikov** [comment]
@2007anu Which browser is this?

**Comment by 2007anu** [comment]
Nightly

**Comment by aslushnikov** [comment]
Firefox indeed doesn't support microphone permission. I'll mark this as a feature-request

**Comment by 2007anu** [comment]
Ok, thanks

**Comment by 2007anu** [comment]
Any other workaround for this?

**Comment by aslushnikov** [comment]
no workaround that i'd know of

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by roycamp** [comment]
+1 for this, please reopen

**Comment by BlkPingu** [comment]
Please implement this

**Comment by Neformaln** [comment]
HI! Does anyone have a solution to run the tests of Firefox using camera and microphone permissions?

**Comment by kosteklvp** [comment]
To grant permissions to microphone or camera by default, it can be configured in `playwright.config.js` file. It needs to be configured like this under projects section:

```
projects: [
  {
    name: 'firefox',
    use: {
      browserName: 'firefox',
      launchOptions: {
        firefoxUserPrefs: {
          'permissions.default.microphone': 1,
          'permissions.default.camera': 1,
        },
      },
    }
  }
]
```

**Comment by rudeshatkar** [comment]
HI! Does anyone help inhow to run the tests on Webkit using camera and microphone permissions?

**Comment by carlosllanos12** [comment]
I am still having issues on Webkit, is there a non-official way to grant camera and microphone permission to webkit?
