### ISSUE TITLE
[Question]: timeout

### ISSUE THREAD

**Issue by kspolam** [microsoft/playwright#7636]
### Your question

Is there anything similar to selenium implicit wait ?

when I use page.setDefaultTimeout() for the implicit wait purpose , it is also overriding maximum timeout set in the playwright config for each test

**Comment by aslushnikov** [comment]
Are we talking about @playwright/test here? In this case, `page.setDeafultTimeout` does not affect test. You can configure test timeout separately with `test.setTimeout()` method:

```js
const {test} = require('@playwright/test');

test('should work', async () => {
  test.setTimeout(500);
  await new Promise(x => setTimeout(x, 1000));
});
```

**Comment by kspolam** [comment]
> Are we talking about @playwright/test here? In this case, `page.setDeafultTimeout` does not affect test. You can configure test timeout separately with `test.setTimeout()` method:
> 
> ```js
> const {test} = require('@playwright/test');
> 
> test('should work', async () => {
>   test.setTimeout(500);
>   await new Promise(x => setTimeout(x, 1000));
> });
>

**Comment by kspolam** [comment]
> Are we talking about @playwright/test here? In this case, `page.setDeafultTimeout` does not affect test. You can configure test timeout separately with `test.setTimeout()` method:
> 
> ```js
> const {test} = require('@playwright/test');
> 
> test('should work', async () => {
>   test.setTimeout(500);
>   await new Promise(x => setTimeout(x, 1000));
> });
> ```
thanks for the quick response.
test.setTimeout(500) this has solved the problem.

Can we configure test timeout in playwright test config file ?

**Comment by aslushnikov** [comment]
Yes, just use `timeout` config option like in this snippet:

```ts
// playwright.config.ts
import { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  // Look for test files in the "tests" directory, relative to this configuration file
  testDir: 'tests',

  // Each test is given 30 seconds
  timeout: 30000,

  // Forbid test.only on CI
  forbidOnly: !!process.env.CI,

  // Two retries for each test
  retries: 2,

  // Limit the number of workers on CI, use default locally
  workers: process.env.CI ? 2 : undefined,

  use: {
    // Configure browser and context here
  },
};
export default config;
```

Also, check out our docs: https://playwright.dev/docs/next/test-configuration

**Comment by kspolam** [comment]
Hi,

What i have observed is that, page.setDefaultTimeout, test.setTimeout and timeout in config file is overriding each other

Same time out  applied for both tests and element locators
