### ISSUE TITLE
[Question]: Usage video records.

### ISSUE THREAD

**Issue by cybopob93** [microsoft/playwright#7638]
### Your question

I have necessity of recording video in portions. What I mean: We work with the same page and run a lot of actions on this page and we need in portions recorded videos. Example:
- 1st video is: go to page expamle.com, open login form, submit it
- 2nd video is: while on page after 1st step go to search form or pesonal page and do some actions there
- 3rd video is: reopen main page and relogin to another account

In current version - I've got only one big file with out any possibility to split it on parts. 
Also I can't remove current video before I close page. It means, if I write smthg like this:

```
....
const path = await page.video().path()
fs.renameSync(path, 'logs/test.mp4')
await page.video().delete()
console.log('removed, start record new file') // It will never runs. Also it works the same for 'video.saveAs()'
....
```

Questions: 
How I can record unique video with out nesessety to close and laucnh new page every time?
How to find and remove empty record if I use 'storageState' in launch otions? (when it has, playwright create 2 video files. 1st one short before 'storageState' inited, second one after init completed.

**Comment by aslushnikov** [comment]
There's no API for now that will let you do this. We'll discuss this topic on today's team gathering.

**Comment by aslushnikov** [comment]
Update: we discussed this on the meeting. As long as there is more interest in this (read: more upvotes), we'd be happy to prioritize it accordingly!

**Comment by limshuang** [comment]
we also need, preferably pw-java also provides this api.

**Comment by 15jszlszbysj** [comment]
we need too!!
Now we use ffmpeg and mencoder to cut multi-page video timeline. We hope pw can provide a better function.

**Comment by eugenbg** [comment]
We would really appreciate this too!

**Comment by dkuzmenchuk** [comment]
I'll be happy to have this feature

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
