### ISSUE TITLE
[Bug]: Problem in runner with report: junit and shard=x/y

### ISSUE THREAD

**Issue by Belisckner** [microsoft/playwright#7639]
### Playwright version

1.12.0

### Operating system

MacOS, Linux

### What browsers are you seeing the problem on?

Chromium, Firefox, WebKit

### Other information

test-runner

### What happened? / Describe the bug

When running tests by the command `playwright test --reporter=junit --shard=1/2 `, in the junit report the skipped tests are marked "passed" with time '0'.

At the same time, in gitlab ci in Test, after testing in two different threads,  the number of tests in the gitlab is more than it actually is.
![image](https://user-images.githubusercontent.com/37740578/125773766-824542be-fb36-4646-a812-90e7a7e8532e.png)

I suggest not to include tests with time '0' in the JUnit report or don't include not running tests

**Comment by mxschmitt** [comment]
We recently fixed a similar bug #7568 sounds like a duplicate or related.

**Comment by Belisckner** [comment]
It's related, yes.
But not the same.

in #7568 suggest marked "skip" test. But in gitlab-ci there are both variant of test. Skipped and passed (with time).
In first thread test would be "skipped"  
In second thread test would be "passed" with example time="1.234"

For gitlab, it would be different tests, but this is actually one test

**Comment by dgozman** [comment]
Fixed by #7708, should be available in v1.14.
