### ISSUE TITLE
[Bug]: The command "npx playwright show-trace" doesn't work with trace zipped folder if name contains spaces 

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#7640]
### Playwright version

1.12.3

### Operating system

Windows

### Other information

**Node.js version:** v14.16.1
**Windows version:** 10
**WebStorm version** 2021.1.3

### What happened? / Describe the bug

I record a trace for each test that I perform.
In order to avoid file overwriting - I use the title of the test (testInfo.title) as the name of the file (see the complete code in the section below). 

![image](https://user-images.githubusercontent.com/52656401/125779088-b114b4f1-50b5-4d94-865f-11777cd9d266.png)

After test performing - I get the following trace zipped folder:

![image](https://user-images.githubusercontent.com/52656401/125779555-b5400361-66a4-49a9-89be-f037c3701e66.png)

As can be seen - the name of the zipped folder is '**Search and buy item.zip**'.

In order to open the trace of the test, I use the "npx playwright show-trace" command via the IDE terminal. Using the terminal autocompletion - I get the following path:

![image](https://user-images.githubusercontent.com/52656401/125779776-f12c5b2e-dd67-47b5-bb95-3e3d98d469d1.png)

But the attempt to perform this command with the provided path - triggers error:

![image](https://user-images.githubusercontent.com/52656401/125779934-5e49ccfe-7baa-4e03-a98b-f7ad16dfc4ee.png)

Only if I'll remove the spaces from the zipped directory (for example: '**Searchandbuyitem.zip**') - it will work as well. 

See the full code in the section below.

### Code snippet to reproduce your bug

```shell
import test, { BrowserContext, Page } from "@playwright/test";
import BasePage from "../../common/BasePage";
import ApplicationUrl from "../../helpers/applicationUrl";
import Header from "../components/Header";
import RegisterForm from "../components/RegisterForm";
import UpperNavigationMenu from "../components/UpperNavigationMenu";
import MerchandisePage from "../pages/MerchandisePage";

test.describe("Buy Merchandise Feature", async () => {
  let basePage: BasePage;
  let header: Header;
  let registerForm: RegisterForm;
  let upperNavigationMenu: UpperNavigationMenu;
  let merchandisePage: MerchandisePage;


  test.beforeAll(async ({ }) => {});

  test.beforeEach(async ({ page, context}) => {
    basePage = new BasePage(page);
    header = new Header(page);
    registerForm = new RegisterForm(page);
    upperNavigationMenu = new UpperNavigationMenu(page);
    merchandisePage = new MerchandisePage(page);

    await basePage.loadApplication(ApplicationUrl.ESRO);
    await context.tracing.start({
      screenshots: true,
      snapshots: true,
    });
  });

  test.afterAll(async ({browser}) => {
    await browser.close();
  });

  test.afterEach(async ({context, page, }, testInfo) => {
      await context.clearCookies();

      //await page.screenshot();
    await context.tracing.stop({path: 'traces/'+ testInfo.status + '/' + testInfo.title +'.zip'});
    //await page.close();
    //await context.close();


  });

  test.only('Search and buy item', async ({browser}) => {
    let firstName = basePage.getRandomFirstName;
    let lastName = basePage.getRandomLastName;
    let email = basePage.getRandomMail;
    let phone = basePage.getRandomPhone;

    await header.openRegisterForm();
    await registerForm.fillRegisterFormWithSkip(firstName, lastName, email, phone);
    await header.validateUserDetails(firstName, lastName);

    await upperNavigationMenu.chooseMenuTab('Merchandise');
    await upperNavigationMenu.validateEndPoint('/merchandise');
    await merchandisePage.searchAndChooseItem('Tea');
  })

});
```

**Comment by aslushnikov** [comment]
@AlexKomanov This seems to be an NPX issue on Windows:
- https://github.com/npm/npx/issues/43
- https://github.com/npm/cli/issues/502

The official "workaround" for this would be to [install NPM v7](https://github.com/npm/cli/issues/502#issuecomment-767371011):

```shell
$ npm i -g npm@v7
```

**Comment by AlexKomanov** [comment]
@aslushnikov 
Thanks! 
Worked for me perfectly!!!
