### ISSUE TITLE
[Bug]: do verify ffmpeg exit code after recording video

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#7641]
We currently don't check that ffmpeg exit code is 0 when recording the video with Chromium.

Action item: verify that its == 0 and throw otherwise.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
