### ISSUE TITLE
[Question]: Playwright doesn't find the right location of elements with 'zoom' css property

### ISSUE THREAD

**Issue by radamihai** [microsoft/playwright#7642]
### Your question

On a specific website playwright doesn't seem to find the location of elements accurately:

![issue1](https://user-images.githubusercontent.com/23338650/125783337-ed62a618-acbf-46e4-8e28-8f4eb75ae4e5.png)

In the above image I'm hovering over the button in the browser opened by codegen. The highlighted area does not match the element position, as seen on the screen or when hovering over the element definition in the Developer Tools:
![issue2](https://user-images.githubusercontent.com/23338650/125784412-29fabd3b-7615-4f57-9996-0df764fbb44b.png)

This behavior is causing some issues, with functions like elementHandle.screenshot() and page.click(). This issue happens on all elements on this page and scrolling on the page seems to affect the location determined by playwright relative to the actual location of the element. I'm looking for some insight into how this issue could be fixed or why is it occurring.

Website I'm talking about: https://factura.vodafone.ro/

**Comment by aslushnikov** [comment]
Easily reproes for me on tip-of-tree as of Jul 15, 2021:

```bash
npx playwright open https://factura.vodafone.ro/
```

![image](https://user-images.githubusercontent.com/746130/125789254-c3f8144c-7031-4d91-9635-b515fdaf6156.png)

**Comment by dgozman** [comment]
This is due to `zoom: 90%` css property on the `body` element. It is not trivial to work around this one, unfortunately.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
