### ISSUE TITLE
[Question]: How to return the selected text of dropdown?

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#7645]
### Your question

How to return the selected text of dropdown ?

**Playwright + JavaScript**

Here is my HTML source code

```html
<select name="displaytitle31" id="displaytitle31" style="font-size:10px;">
<option value="1" selected=""> Yes</option>
<option value="0"> No</option>
</select>
```

This line of code returns **1**, i would like to return **Yes**
```javascript
return elementHandle.$eval('select[id^="displaytitle"]', e => e.value);
```

Appreciate any help!

**Comment by aslushnikov** [comment]
@vsravuri  Just use `textContent` instead of value:
```js
return elementHandle.$eval('select[id^="displaytitle"]', e => e.textContent);
```

**Comment by vsravuri** [comment]
@aslushnikov I tried the solution, during test run if i select 'No' in the Select Box, i still see 'Yes' ('Yes' is default selected value in drop-down on page load) returned using 

```javascript
return elementHandle.$eval('select[id^="displaytitle"]', e => e.selectedOptions[0].textContent);
```
Basically this returns whatever value is set on page load, not what i select in UI.

Is there any other way to return the text selected in UI during test run ?

**Comment by aslushnikov** [comment]
> Basically this returns whatever value is set on page load, not what i select in UI.

@vsravuri  interesting - can you please share your script that doesn't work? It should work unless there's some race condition in automation.

> With Protractor i was able to do this

This will work with Playwright too:

```js
const text = await page.$eval('select[id^="displaytitle"] option:checked', e => e.text);
```

**Comment by vsravuri** [comment]
@aslushnikov 

I found the problem.

I have two styles, style1 and style2. style1 is hidden (style="display: none) and style2 is visible. 

```javascript select
select[id^="displaytitle"] 
``` 
locator is available in both the styles. 

<img width="615" alt="Screen_Shot_2021-07-16_at_8_26_33_AM" src="https://user-images.githubusercontent.com/22808594/125978405-484349e2-a8cd-4395-b06e-6c1026a0a42b.png">


```javascript
const text = await page.$eval('select[id^="displaytitle"] option:checked', e => e.text);
```

$eval is resolving to the hidden locator but not the visible locator.

**Comment by aslushnikov** [comment]
Oh, just use the `:visilbe` pseudo-selector that playwright has for these cases:

```js
const text = await page.$eval('select[id^="displaytitle"]:visible option:checked', e => e.text);
```

**Comment by vsravuri** [comment]
@aslushnikov 

Thank you very much.

The solution worked.
