### ISSUE TITLE
[Bug]: run-driver-posix.sh does not work under NixOS

### ISSUE THREAD

**Issue by tuxinaut** [microsoft/playwright#7647]
### Playwright version

1.12.3

### Operating system

Linux

### Other information

Linux distribution: [NixOS](https://nixos.org/)
Node.js version: v12.22.2

### What happened? / Describe the bug

The [run-driver-posix.sh](https://github.com/microsoft/playwright/blob/07fc8cc77793aa4e014940f06e83bd29b655ab6b/utils/build/run-driver-posix.sh) shell script has a hard-coded `sh` path and uses its own `nodejs` binary, both things do not work under NixOS.

In a nutshell, NixOS does use standard paths like _/bin/_

```
~
❯ which sh
/run/current-system/sw/bin/sh

❯ ll /run/current-system/sw/bin/sh
lrwxrwxrwx 3 root root 75 Jan  1  1970 /run/current-system/sw/bin/sh -> /nix/store/zdk63pzvb0qgs5wy1rji3qj4h4kcl5hg-bash-interactive-4.4-p23/bin/sh
❯
```

`Nodejs` can not be executed because the binary contains hard-coded paths (same problem as described above).

The first problem is easily solvable instead of using _#!/bin/sh_  the right path / sh version could be picked by `env`  _#!/usr/bin/env sh_

For nodejs it would be an idea to check for the (right) nodejs version on system-level if the "normal" command failed?¿ :thinking:

**Comment by aslushnikov** [comment]
@tuxinaut both are very valid. Would you like to submit a PR?

**Comment by tuxinaut** [comment]
ACK; I try to provide a pull request soonish.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
