### ISSUE TITLE
[Feature]:  Playwright Inspector -- Show count of item matched.

### ISSUE THREAD

**Issue by ZooDoo4U** [microsoft/playwright#7648]
### Feature request

As a user creating selectors would be helpful to see the count of matched items upon pressing "Explore".

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
