### ISSUE TITLE
[Bug]: Gsts via node2nix on nixOS

### ISSUE THREAD

**Issue by souleb** [microsoft/playwright#7650]
### Playwright version

1.12.3

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

trying to install [gsts](https://github.com/ruimarinho/gsts) via node2nix on nixOS get me the following error:

```
...............] \ : info lifecycle aws-sdk@2.946.0~postinstall: aws-sdk@2.[0m
> playwright@1.12.3 install /nix/store/gz3difck1w4py00qrdn8iin74cnbgjmi-node_gsts-3.0.6/lib/node_modules/gsts/node_modules/playwright
> node install.js

(node:3961) UnhandledPromiseRejectionWarning: Error: Failed to download chromium, caused by
Error: getaddrinfo ENOTFOUND playwright.azureedge.net
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
    at /nix/store/gz3difck1w4py00qrdn8iin74cnbgjmi-node_gsts-3.0.6/lib/node_modules/gsts/node_modules/playwright/lib/install/installer.js:124:19
    at async validateCache (/nix/store/gz3difck1w4py00qrdn8iin74cnbgjmi-node_gsts-3.0.6/lib/node_modules/gsts/node_modules/playwright/lib/install/installer.js:123:9)
    at async installBrowsersWithProgressBar (/nix/store/gz3difck1w4py00qrdn8iin74cnbgjmi-node_gsts-3.0.6/lib/node_modules/gsts/node_modules/playwright/lib/install/installer.js:74:9)
```

### Code snippet to reproduce your bug

```shell
[souleb@nixos21:~/node-packages]$ cat packages.json 
[ "gsts" ]

[souleb@nixos21:~/node-packages]$ node2nix -i packages.json
[souleb@nixos21:~/node-packages]$ nix-env -f default.nix -iA gsts
```

**Comment by aslushnikov** [comment]
> Error: getaddrinfo ENOTFOUND playwright.azureedge.net

@souleb I'm not familiar with either node2nix or nixOS, but it looks like Playwright install script doesn't have access to the internet. Could it be the case?

**Comment by souleb** [comment]
nope, all other dependencies resolve correctly

**Comment by aslushnikov** [comment]
@souleb can you please try running with `DEBUG=pw:install` env variable?

**Comment by souleb** [comment]
Does not seem to work with the nix package manager

**Comment by pavelfeldman** [comment]
Sorry, you are on your own with the Linux distributions outside of the supported set (Ubuntu).

**Comment by kczulko** [comment]
@souleb

There is an env variable that controls it. Please take a look on this: https://github.com/microsoft/playwright/blob/ddccb590932fcab7943a10f0c79734d6f8a6b83b/packages/playwright-core/src/server/registry/index.ts#L930

It helped me to go further while porting gsts to nix :)

Best regards,
Karol
