### ISSUE TITLE
[Bug]: screen in video recorded in docker webkit is scaled up

### ISSUE THREAD

**Issue by archlichking** [microsoft/playwright#7653]
### Playwright version

1.12.3

### Operating system

Linux

### What browsers are you seeing the problem on?

WebKit

### Other information

docker image: mcr.microsoft.com/playwright:v1.12.3-focal

### What happened? / Describe the bug

The video doesn't scale correctly for webkit mobile simulation in docker container. In chromium it scales well. 

webkit video screenshot

<img width="452" alt="Screen Shot 2021-07-15 at 9 38 03 AM" src="https://user-images.githubusercontent.com/836567/125825183-3cce4e9f-fc75-42cc-82b8-20930693c19b.png">

chromium video screenshot

<img width="446" alt="Screen Shot 2021-07-15 at 9 39 28 AM" src="https://user-images.githubusercontent.com/836567/125825326-a20cc07c-f1f2-414f-922e-f207f037cf6d.png">

### Code snippet to reproduce your bug

```shell
// test

test.describe(' - Open Google', () => {
  test('@P0 Page should scale well', async ({ page }) => {
    await page.goto('https://www.google.com');
    await page.waitForTimeout(2000);
  });
});

// playwright config

const config: PlaywrightTestConfig = {
  use: {
    video: 'on',
    launchOptions: {
      headless: true,
      slowMo: 200,
    },
  },
  projects: [
    {
      name: 'safari@iphone 12pm',
      use: {
        browserName: 'webkit',
        ...devices['iPhone 12 Pro Max'],
      },
    },
    {
      name: 'chrome@iphone 12pm',
      use: {
        browserName: 'chromium',
        ...devices['iPhone 12 Pro Max'],
      },
    },
  ]
}
```

**Comment by tking16** [comment]
I'm still seeing this issue, Webkit in a docker container
