### ISSUE TITLE
[Question]: Test finish successfully, but not open browser.

### ISSUE THREAD

**Issue by Schepetkov** [microsoft/playwright#7654]
### Your question

Hi all.
I set up all from https://playwright.dev/dotnet/docs/intro/#installation, run test and test finish successfully, but not open browser. 
https://drive.google.com/file/d/1uRT1aBfKe6NuFRrzK1S86lmsdKrj9WBT/view?usp=sharing
Why? How to fix it?

**Comment by aslushnikov** [comment]
@Schepetkov By default, Playwright runs browsers in headless mode. Pass "Headless=false" when launching browser: https://playwright.dev/dotnet/docs/api/class-browsertype#browser-type-launch

**Comment by Schepetkov** [comment]
> @Schepetkov By default, Playwright runs browsers in headless mode. Pass "Headless=false" when launching browser: https://playwright.dev/dotnet/docs/api/class-browsertype#browser-type-launch
