### ISSUE TITLE
[Bug]: Node is not running in focal or bionic Docker container on M1 mac 

### ISSUE THREAD

**Issue by pbrovarnik** [microsoft/playwright#7655]
### Playwright version

1.12.0

### Operating system

MacOS, Linux

### Other information

docker image: mcr.microsoft.com/playwright:focal
docker image: mcr.microsoft.com/playwright:bionic

### What happened? / Describe the bug

Node seems to crash when trying to install dependencies when building a Docker image FROM mcr.microsoft.com/playwright:focal or bionic on an M1 Mac. 

I ran `docker run -it --rm --ipc=host mcr.microsoft.com/playwright:focal /bin/bash` command which started a container and tried to directly run `node` and i got the same error as the one during the Docker build process: 
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
root@058c62a236c8:/# node

#
# Fatal process OOM in CodeRange setup: allocate virtual memory
#

qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
Trace/breakpoint trap
```
Also tried to run `docker run -it --rm --platform linux/amd64 --ipc=host mcr.microsoft.com/playwright:focal /bin/bash` which got rid of the WARNING but still got the same error.

**Comment by aslushnikov** [comment]
@pbrovarnik the `mcr.microsoft.com/playwright:focal` is a linux/amd64 image, so your first attempt - `docker run -it --rm --ipc=host mcr.microsoft.com/playwright:focal /bin/bash` - is supposed to fail.

However, the `docker run -it --rm --platform linux/amd64 --ipc=host mcr.microsoft.com/playwright:focal` should work.
Let me look into why it doesn't.

**Comment by aslushnikov** [comment]
Turns out `--platfom linux/amd64` does a virtualization that just can't handle node 16. I guess that's all the fancy things V8 is doing under the hood that break virtualization.

Filed #7723 feature request for the arm-based docker containers and closing this in favor of that issue.
