### ISSUE TITLE
[Bug]: @playwright/test generates a confusing error message when I forgot to run `npx playwright install`

### ISSUE THREAD

**Issue by dtinth** [microsoft/playwright#7656]
### Playwright version

1.12.3

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

I installed `@playwright/test` but did not install `playwright`, following docs:

> Playwright Test is self-contained, **it does not need Playwright to be installed.**

I forgot to read the part where it says:

> Unlike Playwright, Playwright Test does not bundle browsers by default, so you need to install them explicitly: `npx playwright install`

I tried running a test, it says:

```
  1) hello.spec.ts:3:1 › [chromium] basic test =====================================================

    browserType.launch: Failed to launch chromium because executable doesn't exist at /Users/dtinth/Library/Caches/ms-playwright/chromium-888113/chrome-mac/Chromium.app/Contents/MacOS/Chromium
    Try re-installing playwright with "npm install playwright"

      1 | import { test, expect } from '@playwright/test'
      2 |
      3 | test('basic test', async ({ page }) => {
```

The error message told me to run `npm install playwright`, which contradicts what I read earlier.

I believe the error message should suggest `npx playwright install` instead.

**Comment by mxschmitt** [comment]
Good catch! With the next version it will say `npx playwright install` instead: https://github.com/microsoft/playwright/pull/7410
