### ISSUE TITLE
[Feature]: exposing cipher and keyExchange on securityDetails 

### ISSUE THREAD

**Issue by vigneshshanmugam** [microsoft/playwright#7663]
### Feature request

Currently, [response.securityDetails()](https://github.com/microsoft/playwright/blob/master/docs/src/api/class-response.md#async-method-responsesecuritydetails) only exposes some of the fields that are used by the HARTracer. 

Would like PW API to also expose some additional information like `cipher`, `keyExchange` and `keyExchangeGroup` from CDP - https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-SecurityDetails

I am not sure if these fields are cross browser compatible,However I did find these fields are not available in `webkit` at the moment - https://github.com/microsoft/playwright/issues/6759. 

I am happy to give a PR if it's possible to extract these information cross browser.

**Comment by aslushnikov** [comment]
let's have this on hold while we lack necessary information exposed across all the browsers.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
