### ISSUE TITLE
[Question]: Inject value

### ISSUE THREAD

**Issue by ArmanYeghiazaryan** [microsoft/playwright#7667]
### Your question

Hey, 

I have a HTML element which is not visible and has the value "A". How can I change its value to "B" using Playwright and Java? 

Also, is it possible to make the element visible? Once it is visible, a text field will appear. 

Thank you very much!

**Comment by aslushnikov** [comment]
> How can I change its value to "B" using Playwright and Java?

@ArmanYeghiazaryan Use [`page.evalOnSelector()`](https://playwright.dev/java/docs/api/class-page#page-eval-on-selector) method:

```java
page.evalOnSelector("#search", "el => el.value = 'B'");
```

> Also, is it possible to make the element visible? Once it is visible, a text field will appear.

This depends on the method the element was hidden by the page. You might need to either change its display, or visibility, or display/visibility of its parent.
