### ISSUE TITLE
[Question] : open intranet url

### ISSUE THREAD

**Issue by agaramudhala** [microsoft/playwright#7672]
Hi team,

Intranet url aren't opening inside playwright docker container or via pw debugger. Any work around for this pls

**Comment by aslushnikov** [comment]
@dineshbabuv try running docker container with `--network host` flag

**Comment by dineshbabuv** [comment]
> @dineshbabuv try running docker container with `--network host` flag 
I have read only access in tat container. Can add i add network flag explicitly in playwright config or launchoptions? @aslushnikov

**Comment by aslushnikov** [comment]
> Can i add 'network flag' explicitly in playwright config or launchoptions?

@dineshbabuv no, docker container isolates playwright from external environment.

**Comment by aslushnikov** [comment]
I'll close this for now; feel free to re-submit the issue if the question remains.
