### ISSUE TITLE
[Feature]: Case insensitive `--grep`

### ISSUE THREAD

**Issue by mskelton** [microsoft/playwright#7673]
### Feature request

Currently, the `--grep` CLI command is case sensitive which makes matching tests more difficult if you don't know remember the exact casing offhand.  I think it would be beneficial to make the `--grep` command case insensitive by default.

Looking at the source, it would appear that the grep command accepts a regex expression, but since this is also a CLI flag it isn't as simple as just passing a regex argument.

**Comment by aslushnikov** [comment]
it looks like it's working! Please re-file if it's not!
