### ISSUE TITLE
[Question]: How to get es6 to work with Playwright?

### ISSUE THREAD

**Issue by AveryTheDev** [microsoft/playwright#7678]
### Your question

I'm getting an error when attempting to run my tests. `Cannot use import statement outside a module`.

I saw in https://github.com/microsoft/playwright/pull/3125 there was supposed to be a wrapper included to help handle this but I don't see this in my node module folder.

I also tried reinstalling `playwright` and `@playwright/test` but I am still facing the same issue.

**Comment by aslushnikov** [comment]
@AveryTheDev which version of playwright do you use? With Playwright 1.12.3 and node v14.9.0, the following works for me:

```js
import {chromium} from 'playwright';

const browser = await chromium.launch();
const page = await browser.newPage();
console.log(await page.evaluate(() => navigator.userAgent));
await browser.close();
```

**Comment by AveryTheDev** [comment]
I reinstalled today, so I have the version "^1.12.3" as a dev dependency in my app

**Comment by AveryTheDev** [comment]
The error is thrown on my config file and my spec file

**Comment by mxschmitt** [comment]
Do you want to use it with `@playwright/test`? Then using the `.mjs` file extension should work for you.

**Comment by AveryTheDev** [comment]
Error was due to a mixture of ts/js files. After migrating or deleting the js files the es6 syntax worked

**Comment by mrienstra** [comment]
I encountered a similar issue, in my case the error was:
```
Error: test/some.test.ts: JavaScript files must end with .mjs to use import.
    at errorWithFile (~/repo/.yarn/unplugged/@playwright-test-npm-1.14.1-07404d0924/node_modules/@playwright/test/lib/test/util.js:216:10)
    at Loader._requireOrImport (~/repo/.yarn/unplugged/@playwright-test-npm-1.14.1-07404d0924/node_modules/@playwright/test/lib/test/loader.js:219:145)
    at Loader.loadTestFile (~/repo/.yarn/unplugged/@playwright-test-npm-1.14.1-07404d0924/node_modules/@playwright/test/lib/test/loader.js:130:18)
    at Runner._run (~/repo/.yarn/unplugged/@playwright-test-npm-1.14.1-07404d0924/node_modules/@playwright/test/lib/test/runner.js:210:59)
```

1. I had recently added `playwright.config.ts` & `playwright-utils.ts`.
2. When running `yarn build` (`tsc && vite build; yarn run clean`) JS versions of these files were being created (by `tsc`).
3. Adding them to my existing `yarn clean` command (`"clean": "rm src/**/*.js*; rm test/**/*.js*; rm playwright.config.js*; rm playwright-utils.js*; rm vite.config.js*",`) resolved the issue.

Having to remove these build artifacts was not surprising, but the error threw me off, as I had not encountered it before. And it was odd that nothing came up when searching Google for that exact phrase ("JavaScript files must end with .mjs to use import").

**Comment by mrbrianevans** [comment]
> I encountered a similar issue, in my case the error was:
> 
> ```
> Error: test/some.test.ts: JavaScript files must end with .mjs to use import.
>     at errorWithFile (~/repo/.yarn/unplugged/@playwright-test-npm-1.14.1-07404d0924/node_modules/@playwright/test/lib/test/util.js:216:10)
>     at Loader._requireOrImport (~/repo/.yarn/unplugged/@playwright-test-npm-1.14.1-07404d0924/node_modules/@playwright/test/lib/test/loader.js:219:145)
>     at Loader.loadTestFile (~/repo/.yarn/unplugged/@playwright-test-npm-1.14.1-07404d0924/node_modules/@playwright/test/lib/test/loader.js:130:18)
>     at Runner._run (~/repo/.yarn/unplugged/@playwright-test-npm-1.14.1-07404d0924/node_modules/@playwright/test/lib/test/runner.js:210:59)
> ```

I've encounted the same error when one of my dependencies was an ES module. 

Because I was only importing a type definition, I solved the issue by using `import type {} from 'package'` rather than simply `import {} from 'package'`. This means that the import is removed when its compiled to javascript, and so it solved the problem with playwright. Not sure what the actual solution is, but thought I would put this here in case it can be of help to anyone else.

**Comment by MikeYermolayev** [comment]
Looks like I experience the same problem. 
Seems like it occurs when I try to import something from `src` folder instead of `tests`

e.g. 
test.fixture.ts
```
import { MockServiceWorker, createWorkerFixture } from 'playwright-msw';
import { test as base, expect } from '@playwright/test';
import { handlers } from '../src/mocks/handlers';

const test = base.extend<{ worker: MockServiceWorker }>({
  worker: createWorkerFixture(...handlers),
});

export { test, expect };
```

main.test.ts
```
import { test, expect } from './test.fixture';

test('landing page', async ({ page }) => {
  await page.goto('/, { waitUntil: 'networkidle' });

  await expect(page).toHaveTitle('MY TITLE');
});
```

Any advices?

**Comment by MikeYermolayev** [comment]
Okay. so the reason was the same as here https://github.com/microsoft/playwright/issues/7678#issuecomment-882659295

If I change all imported files to .ts then it works. But there are other issues I face with that setup. Seems like it's not the best idea to re-use code from 'src'

**Comment by alexciesielski** [comment]
All my imported files end with `.ts` and I still get this error with latest Playwright `1.43.0`

**Comment by mxschmitt** [comment]
@alexciesielski please file a separate issue with a reproduction.
