### ISSUE TITLE
[Question]: Difference between context.tracing & browser.startTracing?

### ISSUE THREAD

**Issue by ortoniKC** [microsoft/playwright#7683]
### Your question

Hi, I am trying to find the difference between both the code, as per the document both should work.

This works:
```
import { test } from "@playwright/test";
test("Conetext tracing", async ({ browser }) => {
    const context = await browser.newContext();
    // start tracing
    await context.tracing.start(
        {
            screenshots: true, snapshots: true
        }
    );
    const page = await context.newPage();
    await page.goto('https://letcode.in');
    // Stop tracing and export it into a zip archive.
    await context.tracing.stop({ path: 'trace0.zip' });
})
```
This is not working.
this generates the file but while opening
**Invalid trace file: trace.zip**
```
test("Browser tracing", async ({ page, browser }) => {
    await browser.startTracing(page, { path: "./trace1.zip" });
    await page.goto('https://letcode.in');
    await browser.stopTracing();
})
```

Thanks!

**Comment by mxschmitt** [comment]
`browser.startTracing` is a Chromium only tracing feature, which gives you a JavaScript event profiler, see [here](https://www.chromium.org/developers/how-tos/trace-event-profiling-tool).

`context.tracing*` is the Playwright tracing feature, which is cross-browser compatible and provides you screenshot, snapshot, DOM inspection out-of-the-box to debug your failing or flaky end-to-end tests.

Also for your example, we recommend setting the trace configuration in the Playwright Test config, then you don't need to launch own context, take care about closing it, save it etc. see [here](https://playwright.dev/docs/test-configuration).

I will mark this issue as a documentation change, so we can make it more clear for future users.

**Comment by ortoniKC** [comment]
Thank you it helped 😊
 @mxschmitt
