### ISSUE TITLE
[Feature]: Add `firefoxUserPrefs` as a parameter for `browserType.launchPersistentContext`

### ISSUE THREAD

**Issue by nlile** [microsoft/playwright#7687]
### Feature request

Currently the `BrowserType` method `launchPersistentContext` doesn't accept `firefoxUserPrefs` as a parameter. `firefoxUserPrefs` is an available parameter for `launch` and `launchServer`.

I'm brand new to this project, but I would assume a temporary workaround would be `page.goto('about:config');`. I'll try to test this and report back.

Edit: Because  `about:config` doesn't return a HTTP status code, I don't think this will be a valid workaround. Testing in the python API and I'm timing out.

**Comment by aslushnikov** [comment]
@nlile the `firefoxUserPrefs` is implemented via writing `user.js` to the `userDataDir` file. We don't have this option since it might overwrite the file.

But you can easily emulate this option yourself:

```js
function setCustomPrefs(userDataDir, firefoxUserPrefs) {
  const lines = [];
  for (const [name, value] of Object.entries(firefoxUserPrefs))
    lines.push(`user_pref(${JSON.stringify(name)}, ${JSON.stringify(value)});`);
  fs.writeFileSync(path.join(userDataDir, 'user.js'), lines.join('\n'));
}
```

**Comment by pavelfeldman** [comment]
Closing as per above! Please feel free to file a new issue if this does not address your question.
