### ISSUE TITLE
[Bug]: Toast message is not displayed in firefox browser

### ISSUE THREAD

**Issue by kumars3** [microsoft/playwright#7690]
### Playwright version

1.12.3

### Operating system

Windows

### What browsers are you seeing the problem on?

Firefox

### What happened? / Describe the bug

On uploading an invalid file. I am expecting a toast message to be displayed. But in the playwright firefox (v 89) nightly version no toast message is displayed. When I am uploading same file in Mozilla normal firefox or google chrome a toast message is displayed.
N.B. Once the playwright firefox browser is launched on uploading the invalid file manually also not toast message is displayed.

### Code snippet to reproduce your bug

```shell
await page.setInputFiles(selector, 'fullyQualified file name')
```

**Comment by aslushnikov** [comment]
@kumars3 what's a toast message? Can you please share a snippet that I can run locally to reproduce this behavior?

**Comment by kumars3** [comment]
Hi Andrey,
Thanks for your message. Very first thing, this is **NOT** an issue/bug anymore. There was some problem in my test script which I have fixed few hours back.
Toast message is displayed with playwright. I will close this issue.
Toast message is a small, nonblocking notification pop-up triggered by some action on web control like clicking on button etc. It is displayed for 5-10 seconds and then disappears. 
Like when you upload a file a flash message saying that ‘your file is uploaded’ successfully. It appears for few seconds and then disappears.
More details can be found here.
https://material.angularjs.org/latest/demo/toast

**Comment by aslushnikov** [comment]
Ah I see, thank you. I'm closing this then!
