### ISSUE TITLE
[Feature]: support direct image in `toMatchSnapshot`

### ISSUE THREAD

**Issue by just-boris** [microsoft/playwright#7697]
### Feature request

Currently, `toMatchSnapshot` always expects a file

```js
expect(await page.screenshot()).toMatchSnapshot('home.png');
```

In our case, we compare two simultaneously open pages. In this case, it would be great to have an ability to provide the expected image directly as an argument, to avoid writing it to disk:

```js
await page.goto('first');
const screenshotA = await page.screenshot();
await page.goto('second');
const screenshotB = await page.screenshot();
// proposed API
expect(screenshotA).toMatchSnapshot(screenshotB);
```

**Comment by aslushnikov** [comment]
@just-boris probably specifying a name for the image diff as the second argument would be handy.

**Comment by just-boris** [comment]
This works, but it produces extra temporary files we will need to clean up. Also it is weird overall to write extra data to FS just to workaround inconvenient API

**Comment by p01** [comment]
@just-boris: The current version of Playwright and Playwright/Test supports the syntax you first asked for:

```typescript
test("example test", async({ page }, testInfo) => {
    await page.goto("https://playwright.dev");
    const devScreenshotBuffer = await page.screenshot();
    await page.goto("https://playwright.prod");
    const prodScreenshotBuffer = await page.screenshot();
    expect(prodScreenshotBuffer).toMatchSnapshot(devScreenshotBuffer);
})
```

**Comment by aslushnikov** [comment]
>  The current version of Playwright and Playwright/Test supports the syntax you first asked for:

@p01 I don't think this is the case. (at least it doesn't work for me locally)

> In our case, we compare two simultaneously open pages. In this case, it would be great to have an ability to provide the expected image directly as an argument, to avoid writing it to disk:

@just-boris you can work-around this by just comparing buffers:

```js
await page.goto('first');
const screenshotA = await page.screenshot();
await page.goto('second');
const screenshotB = await page.screenshot();
// proposed API
expect(screenshotA.equals(screenshotB)).toBe(true);
```

Would this work for you?

**Comment by just-boris** [comment]
This is pretty much what I am doing now. However, it also requires me to re-implement diff generation code from scratch: https://github.com/microsoft/playwright/blob/2bc19ae07618f08c8435a472b32cd2559a921b9d/packages/playwright-test/src/matchers/toMatchSnapshot.ts#L51-L58

Would be great to leverage the framework functionality.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
