### ISSUE TITLE
[Bug]: page.waitForSelector() doesn't fail a test in case the selector not found

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#7703]
### Playwright version

1.12.3

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

**Node version:** 14.16.1
**NPM version:** 7.19.1
**Windows version:** 10
**VS Code version:** 1.57.1

### What happened? / Describe the bug

As a part of the method that checking if the element exists - I use the 'page.waitForSelector()' method. 
If I provide an incorrect locator (actually the element doesn't exist) - I don't get any error from the 'page.waitForSelector()' method. 
For example: 
If I run with the correct locator - I get the following result in the console:

![image](https://user-images.githubusercontent.com/52656401/126070194-df59ebe1-5832-4ee2-b1fa-7b9dcfae5fce.png)

If I run with an incorrect locator - I just see that the test ended - But I don't get any error or any failed status of the test:

![image](https://user-images.githubusercontent.com/52656401/126070284-167a2e6e-ae46-46c4-b05f-5ce8b93fc44b.png)

As can be seen from the image above - I don't see any status of the test(failed/skipped/passed) even though the test already finished.

### Code snippet to reproduce your bug

```shell
//Class with methods 

public async validateElementExist(element: string){
        await this.page.waitForSelector(element)
        const expectedElement = await this.page.$(element)
        const isVisible = await expectedElement.isVisible();
        expect(isVisible).toBe(true);
    }

//Class that uses the method

export default class MainPage extends BasePage {

    public async validateLogin(){
        await this.validateElementExist(Menu.HOME);
        await this.validateElementExist(Menu.CRM);
    }
}

//Test file
 test.only("Login with correct credentials", async () => {
    await unifyLoginPage.loginToUnify("sro", "1");
    await mainPage.validateLogin(); 
  });

//playwright.config.ts
import { PlaywrightTestConfig } from "@playwright/test";

const config: PlaywrightTestConfig = {
  timeout: 30000,
  globalTimeout: 30000,
  reporter: [["list"], ["junit", { outputFile: "reports/test-results.xml" }]],
  use: {
    trace: 'on',
    screenshot: 'on',
    video: {
      mode: "on",
      size: {
        width: 1920,
        height: 1080
      }
    },
    contextOptions: {
      
    },
    // Browser options   
    launchOptions: {     
      channel: 'chrome',
      headless: false,
    },
    slowMo: 0,

  },
};

export default config;
```

**Comment by AlexKomanov** [comment]
Hi all.
Do I need to add some additional info?

**Comment by mxschmitt** [comment]
Sorry for the delay, this issue went unfortunately under our radar. Could you provide us your test file, specifically how you get your page instance?

Since we only guarantee good reporting if you use the `page` instance which you get via the fixtures, see here: https://playwright.dev/docs/next/intro#first-test

**Comment by mxschmitt** [comment]
Closing since it seems stale, please create a new issue if you still encounter issues.
