### ISSUE TITLE
[Bug]: 'globalTimeout' option doesn't trigger any indication if reached

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#7704]
### Playwright version

1.12.3

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

**Node version:** 14.16.1
**NPM version:** 7.19.1
**Windows version:** 10
**VS Code version:** 1.57.1

### What happened? / Describe the bug

If the time parameter of the 'globalTimeout' was reached - the tests suite stops the run. The user doesn't get any indication about the reason. 
In my case, without noticing' I defined the value as '30000'. The tests run was stopped after reaching the value (30000) and I didn't understand the reason because the test run was just stopped:

![image](https://user-images.githubusercontent.com/52656401/126072493-85dd9bd9-b14c-44a9-b218-90736127bcd0.png)

After changing the value to '300000' - the run was finished as well:

![image](https://user-images.githubusercontent.com/52656401/126072519-a5e822d0-dc52-46d0-bba1-e5567bbb3f44.png)

Does it as expected?
If yes - maybe I can suggest adding any indication to the console output? Like in the case when the test timeout is reached, like the following:

![image](https://user-images.githubusercontent.com/52656401/126073607-3e0588bc-a5d1-421a-a9ec-ef7d5a254142.png)

### Code snippet to reproduce your bug

```shell
import { PlaywrightTestConfig } from "@playwright/test";

const config: PlaywrightTestConfig = {
  timeout: 30000,
  globalTimeout: 30000,
  reporter: [["list"], ["junit", { outputFile: "reports/test-results.xml" }]],
  use: {
    trace: 'on',
    screenshot: 'on',
    video: {
      mode: "on",
      size: {
        width: 1920,
        height: 1080
      }
    },
    contextOptions: {
      
    },
    // Browser options   
    launchOptions: {     
      channel: 'chrome',
      headless: false,
    },
    slowMo: 0,
  },
};

export default config;
```

**Comment by dgozman** [comment]
I think this is already fixed for v1.13. Let me double check after 1.13 is live.

**Comment by AlexKomanov** [comment]
@dgozman 
Thanks for your response. 
Do you know when the v1.13 will be released?

**Comment by aslushnikov** [comment]
@AlexKomanov it's being baked right now. You can always get a sneak peak using `npm i playwright@next`
