### ISSUE TITLE
[Bug]: globalSetup doesn't wait for the returned callback

### ISSUE THREAD

**Issue by davidfou** [microsoft/playwright#7705]
### Playwright version

1.12.3

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

Hi :wave: 

I configured a `globalSetup` which returns a promise with something similar to what's described on the [doc](https://playwright.dev/docs/test-advanced/#global-setup-and-teardown). By putting some `console.log`, it looks like the project exists before the callback is completed.

Let me know if you have the same behaviour. Also, I wouldn't mind to give a hand to fix that one :smile:

### Code snippet to reproduce your bug

`playwright.config.js`:
```js
module.exports = {
  // ...
  globalSetup: "tests/setup.js",
};
```

`tests/setup.js`:
```js
const rollup = require("rollup");

module.exports = async () => {
  const bundle = await rollup.rollup({
    // ...
  });

  return async () => {
    console.log('CLEAN')
    await bundle.close().then('DONE!');
  };
};
```

In the logs, `CLEAN` is printed but `DONE!` not. I believe the same is reproducible with a server.

**Comment by pavelfeldman** [comment]
Could it be that your bundle.close() throws? The following snippet works for me:

```js
module.exports = async () => {
  return async () => {
    console.log('CLEAN');
    await new Promise(f => setTimeout(f, 3000));
    console.log('DONE!');
  };
};
```

**Comment by pavelfeldman** [comment]
Ah, now that I read you snippet, `.then('DONE!')` is not a thing.

**Comment by davidfou** [comment]
Thanks a lot @pavelfeldman for your answer! Sorry, I was in rush and indeed, the code I wrote makes no sense :+1: I gave it a try today and indeed, it works like a charm.

I'll think twice before opening a ticket again next time :sweat_smile:
