### ISSUE TITLE
[Question]: Print #document

### ISSUE THREAD

**Issue by ArmanYeghiazaryan** [microsoft/playwright#7706]
### Your question

Hello, 

I have a question. How can I implement Java code, which lets Playwright print the following content inside of the #document? 
Please have a look at the attached screenshot. 

![image](https://user-images.githubusercontent.com/82316190/126076560-1f6930a2-6ea4-474a-a4aa-7ef421db5011.png)

Thank you very much!

**Comment by mxschmitt** [comment]
This is an iframe, so you first need to get the frame and then you can interact with its DOM.

```java
ElementHandle frameElement = page.waitForSelector("#enforcementFrame");
Frame frame = frameElement.contentFrame();
System.out.println(frame.content());
System.out.println(frame.textContent("h1")); // interact with the Frame, see all methods here: https://playwright.dev/java/docs/api/class-frame
```

**Comment by pavelfeldman** [comment]
Closing as per above.
