### ISSUE TITLE
[Bug]: Files are deleted from downloadsPath when the browser context that produced them is closed

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#7707]
### Playwright version

1.12.3

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium

### Other information

Node: v14.17.0
Browser: Chrome, Chromium
Mac OS: 11.4

### What happened? / Describe the bug

As per the documentation here https://playwright.dev/docs/downloads

**_Unless downloadsPath is set, downloaded files are deleted when the browser context that produced them is closed._**

<img width="981" alt="Screen Shot 2021-07-18 at 12 15 46 PM" src="https://user-images.githubusercontent.com/22808594/126079536-05880ff8-4e90-467f-af08-0777e56c1b1f.png">

Although  i specified the downloadsPath, file is downloaded correctly in downloadsPath but file is deleted when the browser context is closed.

As per the documentation, i would expect the file to be retained

### Code snippet to reproduce your bug

```shell
const { test, expect,chromium } = require('@playwright/test');
const path = require("path");

test('Test File Download', async ({ page }) => {
    const browser = await chromium.launch({
        headless: false,
        downloadsPath: path.join(__dirname, 'downloads'),
        //channel: 'chrome'
    });

    const context = await browser.newContext({
        acceptDownloads: true,
    });

    const page1 = await context.newPage();

    await page1.goto('https://file-examples.com/index.php/sample-documents-download/sample-xls-download/');

        const [download] = await Promise.all([
            page1.waitForEvent('download'),
            page1.click('xpath=//tbody/tr[1]/td[5]/a[1]')
        ]);

    let downloadPath;
    downloadPath = await download.path();
    console.log(downloadPath);

    await page1.close();
    await context.close();
    await browser.close();
});
```

### Relevant log output

```shell
n/a
```

**Comment by pavelfeldman** [comment]
This looks like a bug in the docs.

**Comment by aslushnikov** [comment]
@vsravuri please use [`download.saveAs()`](https://playwright.dev/docs/api/class-download#download-save-as) to retain download after automation.

**Comment by vsravuri** [comment]
Thanks @aslushnikov
