### ISSUE TITLE
[Bug]: expect(...).toMatchObject(...) output is too verbose

### ISSUE THREAD

**Issue by Tyriar** [microsoft/playwright#7710]
### Playwright version

@playwright/test@1.12.3

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

When running `expect(savedData).toMatchObject(loadedData)` on a large number array where only a single index differs, this is what happens:

![recording (5)](https://user-images.githubusercontent.com/2193314/126084928-6c189c60-dfd3-4b5a-9f21-cb20935a51ba.gif)

It goes on for minutes at least, the `number[]`'s size in this case is `809600` .

`deepStrictEqual`'s output by comparison is much nicer:

```
    AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Expected values to be strictly deep-equal:
    + actual - expected ... Lines skipped

      {
        data: [
    +     118,
    -     0,
          181,
    ...
        height: 368,
        width: 550
      }
```

**Comment by mxschmitt** [comment]
Hi! Using the following workaround should lead to your expected behavior:

```js
import { expect, test } from '@playwright/test';

test("can disable diff expanding", async () => {
  expect.setState({ expand: false });

  const expected = Array.from({ length: 5000 }).map(() => 1);
  const actual = Array.from({ length: 5000 }).map(() => 1);
  actual[actual.length / 2] = 2;
  expect(actual).toEqual(expected);
})
```

Since this is something which Jest is setting [by default to false](https://github.com/facebook/jest/blob/bc50e7f360ab1845abbaa0b3ad788caead0d3174/packages/jest-circus/src/legacy-code-todo-rewrite/jestExpect.ts#L21), I think we should also do that.
