### ISSUE TITLE
[Bug]:  Video players don't work correctly

### ISSUE THREAD

**Issue by ViaMay** [microsoft/playwright#7716]
### Playwright version

1.12.3

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium, WebKit

### What happened? / Describe the bug

1. First error: HTML Video Player MP4 Video didn't play for Chrome and for Webkit
2. Brightcove Embed Video Player  didn't play for Chrome 
3. Brightcove Video Player didn't play for Chrome and for Webkit

### Code snippet to reproduce your bug

```shell
1) run
const { chromium } = require('playwright');
(async () => {
	const browser = await chromium.launch({ headless: false });
	const page = await browser.newPage();
	await page.goto(`data:text/html,<video width="320" height="240" controls autoplay muted><source src="https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4" type="video/mp4"></video>`);
	await page.pause();
})();

________________________
const { chromium } = require('playwright');

(async () => {
	const browser = await firefox.launch({ headless: false });
        const page = await browser.newPage();
	await page.goto(`https://docs.prebid.org/examples/video/instream/brightcove/pb-ve-brightcove.html`);
	await page.pause();
})();

________________________
3) run: 
const { chromium } = require('playwright');

(async () => {
	const browser = await firefox.launch({ headless: false });
        const page = await browser.newPage();
	await page.goto(`https://players.brightcove.net/1752604059001/15933ac1-884c-40e0-8cae-a06c7d9e4c0a_default/index.html`);
	await page.pause();
})();
```

**Comment by aslushnikov** [comment]
@ViaMay you'll need to use chrome stable to get all the video codecs.

You can install chrome stable with the following command:

```
npx playwright install chrome
```

To use installed chrome stable to run your scripts, pass `channel: 'chrome'` in launch parameters:

```js
const browser = await chromium.launch({
  headless: false,
  channel: 'chrome',
});
```

**Comment by ViaMay** [comment]
@aslushnikov Thanks! it work for chrome.
Can you help with the Webkit?
This "https://players.brightcove.net/1752604059001/15933ac1-884c-40e0-8cae-a06c7d9e4c0a_default/index.html" video didn't work

**Comment by aslushnikov** [comment]
@ViaMay your video doesn't work in Safari either, so looks like an expected behavior!

**Comment by pavelfeldman** [comment]
Video codecs are highly platform-specific. Whether the video is working or not on Windows and/or Linux won't tell you much about the actual experience on the macOS or iOS device. While all the browser features are working on Windows, WebKit media can be limiting. We recommend running your CI/CD bots on macOS machines to test those specifics.

**Comment by ViaMay** [comment]
ok) thanks!
