### ISSUE TITLE
[Question]: Can you use attribute selectors with input tags in Playwright?

### ISSUE THREAD

**Issue by AveryTheDev** [microsoft/playwright#7724]
I tried using an attribute selector to grab an input element whose id will always start with a key word, say `id=foo_bar"hsakjf"` with `foo_bar` being the keyword. The rest is generated gibberish which is why I'm hoping to grab the first that match this criteria.

I've tried selecting with `^=` but my test is timing out before the element is found, which I am interpreting as the test failing to find the element with the instructions left. `input[id^=id=foo_bar"hsakjf"]`.

However, I created another app solely to test this method of selection and found that it wasn't working specifically with `input` tags. This method of grabbing elements was fine with `p` tags and `img` tags when I tested this. Wondering if this could be a bug?

**Comment by pavelfeldman** [comment]
You can use xpath selectors for that: `//*[contains(@id,'foo_bar')]`

**Comment by AveryTheDev** [comment]
So the latter I showed above doesn't work with input tags then? Thank you for the alternative suggestion!

**Comment by AveryTheDev** [comment]
My issue was timing out specifically with the input tag and I've been told that using xpath was slower. I'm running into the same issue with xpath due to the same reason if this is the case.

**Comment by pavelfeldman** [comment]
Xpath might be a millisecond slower, but I'm sure it won't show up on any benchmarks, it is still very fast. You should try opening your script / test with debugger `PWDEBUG=1 node test` (`set PWDEBUG=1` on Windows) and playing with the Explore field. This is a fairly trivial selector, but there might be a timing issue or something like that.

**Comment by AveryTheDev** [comment]
It looks like the problem is that the input field I am trying to select was previously hidden and even though its visible on the page after its reveal, Playwright still thinks of it as hidden. I was wondering if you guys had any advice for selecting inputs that are considered hidden even when it can be detected enough to state "Its hidden"

```

 page.click: Element is not visible
    =========================== logs ===========================
    waiting for selector "input[id^=special_id]"
      selector resolved to hidden <input value="" autocomplete="off" id="special_id-3-inpu…/>
    attempting click action
      scrolling into view if needed
      
 ```

**Comment by AveryTheDev** [comment]
It shouldn't be considered hidden anymore to clarify. It just was previously hidden then toggled into view by another component and Playwright doesn't seem to understand that it is no longer hidden.

**Comment by pavelfeldman** [comment]
It is unlikely that Playwright considers something that is not hidden as hidden, I would not try working around it, it is unlikely to be an issue. You can record a trace and explore it, it'll likely give you a clue: https://playwright.dev/docs/trace-viewer
