### ISSUE TITLE
Yarn installation is currently unsupported for @playwright/test?

### ISSUE THREAD

**Issue by Romeodewit** [microsoft/playwright#7727]
Hi all,

Not sure if anyone else has noticed but adding the playwright test runner to your package.json and running yarn just leaves you with an empty @playwright folder in node modules.

Does anyone else have this issue and if so is there a current fix for this? We currently use yarn to install all our dependencies and mixing both npm and yarn tents to cause a load of dependency issues. 

Any tips are more than welcome

**Comment by pavelfeldman** [comment]
Things work for me if I do
```bash
yarn init -y
yarn add @playwright/test
```

**Comment by Romeodewit** [comment]
Tried this 100's of times. Package shows up in package.json but the actual folder in nodemodules ends up being completely empty preventing me from using the test runner

**Comment by Romeodewit** [comment]
bit of background. After installing it by running npm i -d @playwright/test, it completely messes up all my other dependencies. Making it so I can't use yarn anymore (we use this company-wide so we can just completely switch dependency manager). This means I have to then delete my yarn lock file, and re-run yarn to install all my dependencies again. The problem with this is it then seems to remove all the files from the @playwright node modules folder which makes us end up with an empty node modules folder. I'm trying to install @playwright/test 12.2.3 and it's listed under my devDependencies in my package.json

**Comment by mxschmitt** [comment]
Which Yarn version are you using?
Would it be possible that you could create a reproducible in form of a small GitHub repository?

We understand that switching package managers is not the solution for that, so we are trying to find out the reason. I also tried to reproduce it, but its working for me, version: v1.22.10

**Comment by Romeodewit** [comment]
Found the issue, it was one of our .yarnclean files that had the test directory listed in the cleanup. My bad!

**Comment by mxschmitt** [comment]
Awesome, thanks for confirming that it works now!
