### ISSUE TITLE
[Bug]: chromium args are not being honored unless ignoreDefaultArgs is set to true

### ISSUE THREAD

**Issue by VinnyIla** [microsoft/playwright#7735]
### Playwright version

1.12.3

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

I am trying to start the browser in maximized state, but it wont use the args value, unless i specify ignoreDefaultArgs:true

`const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({
    headless: false,
    **ignoreDefaultArgs: true,**
    **args: ['--start-maximized']**
  });
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.waitForTimeout(30000);
  // other actions...
  await browser.close();
})();`

### Code snippet to reproduce your bug

```shell
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({
    headless: false,
    **args: ['--start-maximized']**
  });
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.waitForTimeout(30000);
  // other actions...
  await browser.close();
})();
```

**Comment by mxschmitt** [comment]
In `browser.newPage()` you need to specify `{ viewport: null }` then it should work also without ignoreDefaultArgs.

**Comment by AlexKomanov** [comment]
@mxschmitt 
Thanks a lot. 
This worked for me as well:

![image](https://user-images.githubusercontent.com/52656401/126281162-1353c523-16c9-4a29-be7c-b93764548166.png)

**Comment by mxschmitt** [comment]
Yup looks good, results in the same internally. Closing then since it seems answered and no bug of Playwright.
