### ISSUE TITLE
[Bug]: WaitForSelector don't consider element as visible

### ISSUE THREAD

**Issue by Kalliser** [microsoft/playwright#7737]
### Playwright version

1.12.3

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium, WebKit

### Other information

nodejs: v14

### What happened? / Describe the bug

The button accept cookies is in viewport and visible but PW don't consider it visible (see screenshot).
![pw_visible_button](https://user-images.githubusercontent.com/2920509/126292396-04f5ac18-1cd3-46f2-9519-30a3ded77eb3.png)
![pw_visible_button_log](https://user-images.githubusercontent.com/2920509/126292408-ba5305ed-9a4f-45eb-bb38-edb17abe9824.png)

### Code snippet to reproduce your bug

```shell
const util = require('util');
const { chromium, firefox, webkit, devices } = require('playwright');
const options = {
    headless: true
};

chromium.launch(options).then(async (browser) => {
    try {
        const context = await browser.newContext({
            ignoreHTTPSErrors: true,
            geolocation: {latitude: 47.21288, longitude: -1.55611},
            ...devices['iPhone X']
        })

        const page = await context.newPage();

        let element;

        await Promise.all([
            page.waitForNavigation({timeout: 15000, url: /https:\/\/www\.femmeactuelle\.fr\//i}),
            page.goto('https://www.femmeactuelle.fr/')
        ]);
        console.log('Homepage OK')

        await page.waitForTimeout(5000);
        element = await page.waitForSelector('[title="Accepter"]:visible', {timeout: 15000})
        await element.click()
        await element.waitForElementState("hidden")
        console.log('Cookies OK')

        await Promise.all([
            page.waitForNavigation({timeout: 15000, url: /https:\/\/connect\.femmeactuelle\.fr\//i}),
            page.click('.pmc-authentification .headerMain-ctaLink')
        ]);
        console.log('Connect OK')

        await Promise.all([
            page.waitForNavigation({timeout: 30, url: /https:\/\/connect\.femmeactuelle\.fr\//i}),
            page.click('.sc-jlyJG.jmuBoc:visible')
        ]);
        console.log('login OK')

        browser.close();
    }
    catch (e) {
        console.log(e.message);
    }
});
```

### Relevant log output

```shell
pw:api waiting for selector "[title="Accepter"]:visible" to be visible +4ms
pw:api <= page.waitForSelector failed +15s
```

**Comment by pavelfeldman** [comment]
I can reproduce this (it is "Accepter & Fermer" in my case). Note that you should be using `webkit`, not `chromium` if you are interested in Safari testing.

**Comment by dgozman** [comment]
The button is "Accepter & Fermer" for me as well. This button is in the `iframe`, that's why it is not found by `page.waitForSelector`. If I change the script like the following, `waitForSelector` works for me. Note how I use `page.frame()` instead of just `page`.

```js
// ...
element = await page.frame({ url: /consent.femmeactuelle.fr/ }).waitForSelector('[title="Accepter & Fermer"]:visible', {timeout: 15000})
// ...
```

I'd recommend to use [codegen](https://playwright.dev/docs/cli#generate-code) to try and record a script - it will automatically notice the `iframe` for you.

**Comment by Kalliser** [comment]
Thanks it's my mistake I didn't notice the frame.
I Think this ticket can be closed.
