### ISSUE TITLE
[Question]: Load multiple storageStates into a single context

### ISSUE THREAD

**Issue by spidyhackx** [microsoft/playwright#7738]
### Your question

Hi guys,so i want to load multiple storageStates into a single context in playwright but when i do this

```
const context = await browser.newContext({
      storageState: "telegram.json",storageState: "google.json"
    });
```
or this
```
const context = await browser.newContext({
      storageState: ["telegram.json","google.json"]
    });
```
none of the states is loaded.

But the code below will load one storageState
```
const context = await browser.newContext({
      storageState: "telegram.json"
    });
```
How do i achieve this?

**Comment by pavelfeldman** [comment]
Could you share more about your use case?

**Comment by spidyhackx** [comment]
i am trying to load the google state to solve captchas in one click during tests and also be automatically signed in when i goto the telegram webclient (https://webk.telegram.org/)

**Comment by pavelfeldman** [comment]
This does not look like a test scenario, more like a scraping scenario. We are not focusing on scraping, sorry!
