### ISSUE TITLE
[Bug]: strange error when waiting for element or URL

### ISSUE THREAD

**Issue by redReno** [microsoft/playwright#7742]
### Playwright version

1.12.3

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

I load a web page using httpCredentials in the context.
Then whenever I try to use waitForURL or waitForSelector the test crashes. It crashes also when I don't use the httpCredentials, but it was when I used it that I first discovered the error.

The goto event succeeds. When I try using something like await page.waitForURL('**/example') the last log I see is:
pw:api waiting for navigation to "**/example" until "load" +1ms

When I try waiting for an element it is:
pw:api waiting for selector "[class^=Checkbox] :text("Enable")" to be visible

What could be the problem here? I can load the page fine manually, and the page is loaded properly using Playwright, it is just the waiting functions that fail. I see no errors in the browser console.

### Code snippet to reproduce your bug

```shell
const { chromium } = require('playwright');
const { expect } = require('chai');

(async () => {
  let browser = await chromium.launch();
  const context = await browser.newContext({
    httpCredentials: {
      username: 'root',
      password: 'pass'
    }
  });
  const page = await context.newPage();
  await page.goto('http://localhost:8080/example');
  await page.waitForURL('**/example');
  expect(page.url()).to.contain('example');
  await page.waitForSelector(`[class^=Checkbox] :text("Enable")`);
  browser.close();
})();
```

### Relevant log output

```shell
Error
    at Object.assert (/home/git/test/node_modules/playwright/lib/utils/utils.js:194:15)
    at new Dispatcher (/home/git/node_modules/playwright/lib/dispatchers/dispatcher.js:53:17)
    at new WebSocketDispatcher (/home/git/node_modules/playwright/lib/dispatchers/networkDispatchers.js:108:9)
    at Page.<anonymous> (/home/git/node_modules/playwright/lib/dispatchers/pageDispatcher.js:60:106)
    at Page.emit (node:events:394:28)
    at FrameManager.onWebSocketRequest (/home/git/node_modules/playwright/lib/server/frames.js:312:24)
    at CRSession.<anonymous> (/home/git/node_modules/playwright/lib/server/chromium/crNetworkManager.js:67:130)
    at CRSession.emit (node:events:394:28)
    at /home/git/node_modules/playwright/lib/server/chromium/crConnection.js:158:22
    at runNextTicks (node:internal/process/task_queues:61:5)
```

**Comment by redReno** [comment]
Seems the error triggers in waitForNavigation, after the test has matched the url values.

const navigatedEvent = await waiter.waitForEvent(this._eventEmitter, 'navigated', event => ... fails.

If I block the execution and wait until timeout while debugging the test fails but I get the normal timeout error.

**Comment by redReno** [comment]
@pavelfeldman It's just an example to show that the suite crashes when the command is used.

**Comment by pavelfeldman** [comment]
I see, Anyhow, if you get something hosted publicly where we can reproduce this, please let us know. Otherwise it is not actionable on our side, so I'll close it.
