### ISSUE TITLE
[Bug]: page.waitForTimeout();

### ISSUE THREAD

**Issue by peterkantas** [microsoft/playwright#7744]
### Playwright version

1.9.0-alpha-0

### Operating system

Windows

### What browsers are you seeing the problem on?

WebKit

### Other information

Java11

### What happened? / Describe the bug

page.waitForTimeout(); <- in now it is a threadsleep.
Everything works fine, but the name is wrong. 
Solutions
- page.waitForSleep();
- page.waitForDelay();

### Code snippet to reproduce your bug

```shell
System.out.println(new Date().toString());
            page.waitForTimeout(5000);
            System.out.println(new Date().toString());
```

### Relevant log output

```shell
Tue Jul 20 17:01:15 CEST 2021
Tue Jul 20 17:01:20 CEST 2021
```

**Comment by pavelfeldman** [comment]
We prefer this name for consistency between the ports!
