### ISSUE TITLE
[Question]: Testing application with 1 host and 2 participants

### ISSUE THREAD

**Issue by r1kkk** [microsoft/playwright#7768]
### Your question

I would like to test the following scenario, but i am not sure if i can use playwright. I would be more than happy if anyone could help me out.

- I have one host, who is creating a meetingroom with several questions (the questions must be answered mutually by the participants)
- I need at least two participants, who can join the meetingroom in their own browser tabs / instances in order to answer the question 
- After the two participants gave an answer the host needs to click on "next question", the two participants need to answer these questions as well and so on

example:

Browser/Tab 1: Host clicks on "next question"
Browser/Tab 2: Participant A answer question no.1 and clicks on "ready"
Browser/Tab 3: Participants B answer question no.1 and clicks on "ready"
Browser/Tab 1: Host clicks on "next question"
Browser/Tab 2: Participants A answer question no 2 and clicks on "ready"
Browser/Tab 3: Participants B answer question no 2 and clicks on "ready"
and so on ... 

Is this kind of scenario possible to solve with playwright, in which each browser tab / instances need to be controlled separately? Thanks a lot

**Comment by pavelfeldman** [comment]
You should create a browser context for each user as described here: https://playwright.dev/docs/multi-pages#multiple-pages

Are you using @playwright/test or some other test runner? We should add some nice fixtures for that in @playwright/test, so I am leaving this open.

**Comment by r1kkk** [comment]
we are currently not using playwright - but we are interested to tests our application in the future with it. Thanks for your answer - i will defintely check it out. 
Unfortunately i am still a beginner: Under the link with the pull request (feat(test runner): createContext fixture for multi-context scenarios #7779) - is there any useful information for me in the link or is this more for you guys?
And what about the fixutres? I am sure you are very busy, but any helpful words are very much appreciated. Thanks

**Comment by dgozman** [comment]
Linked pull request allows testing your application like this:

```js
test('1 host and 2 participants', async ({ createContext }) => {
  const hostContext = await createContext();
  const hostPage = await hostContext.newPage();
  await hostPage.goto('https://my.web.app/host');
  // ... interact with hostPage, e.g. login as a host

  const participant1Context = await createContext();
  const participant1Page = await participant1Context.newPage();
  await participant1Page.goto('https://my.web.app/participant');
  // ... interact with participant1Page, e.g. login as a participant1

  const participant2Context = await createContext();
  const participant2Page = await participant2Context.newPage();
  await participant2Page.goto('https://my.web.app/participant');
  // ... interact with participant2Page, e.g. login as a participant2

  await hostPage.click('text=Next question');
  await participant1.click('text=Answer 1');
  await participant1.click('text=Ready');
  await participant2.click('text=Answer 2');
  await participant2.click('text=Ready');
  // ... continue
});
```

All three pages are isolated, logged in as different hosts/participants and you can interact with them as you'd like.

**Comment by r1kkk** [comment]
Thanks a lot! Great help
