### ISSUE TITLE
[Bug]: `device.launchBrowser()` stops on `about:blank` when changing the page URL

### ISSUE THREAD

**Issue by OxNinja** [microsoft/playwright#7771]
### Playwright version

1.12.2

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium

### Other information

- NodeJS `v12.21.0`
-  `Linux thonkpad 5.10.0-kali9-amd64 #1 SMP Debian 5.10.46-1kali1 (2021-06-25) x86_64 GNU/Linux`

### What happened? / Describe the bug

Using physical devices and ADB I want to use Playwright's NodeJS API for browser automation.

I can get an AndroidDevice object and launch its browser using my script. But it stops here on a new page `about:blank`.

I use *experimental Android API functions* in my code, so maybe this is why I get this bug.

### Code snippet to reproduce your bug

```shell
const { _android: android, chromium } = require("playwright");

(async () => {
    // get the list of all connected devices
    const devices = await android.devices();
    for(device of devices) {
        // in real example I start chromium remote debugging with the flag `--remote-debugging-port=${port}`, but for reading purposes I simplified the thing
        device.shell(`am start -n com.android.chrome/com.google.android.apps.chrome.Main`);
        // launch the browser to automate it afterwards
        const browser = await device.launchBrowser(); // from here, no more logging output, even using `console.log`
        const page = await browser.newPage(); // launches a new page stuck on `about:blank`
        
        await page.goto("https://google.com"); // not working

        await browser.close();
    }
})();
```

**Comment by pavelfeldman** [comment]
A couple of things to fix:

1. You are not supposed to be running `device.shell(`am start -n com.android.chrome/com.google.android.apps.chrome.Main`);`, `launchBrowser` does it for you:

2. Android browser is single-context, so you get context and page right away:

```js
const browserContext = await device.launchBrowser();
const [ page ] = browserContext.pages();
```

Please tell us if that helped.

**Comment by OxNinja** [comment]
I am using `device.shell(am start ...)` in order to use Chromium's remote debug feature, does `launchBrowser` implements that?

I tried with your code and it does not change the problem, am I missing something important?

**Comment by pavelfeldman** [comment]
Which Chromium's remote debug feature are you talking about? You mean chrome://insect to connect to the browser, yes, that works for all the browser instances.

**Comment by OxNinja** [comment]
I use the command `device.shell(am start com.android.chrome/com.google.android.apps.chrome.Main --esa commandLineArgs --remote-debugging-port=xxxx)` and with `device.forward("tcp:xxxx", "localabstract:chrome_devtools_remote")` I can remotely debug the device on host at `localhost:xxxx`.

**Comment by pavelfeldman** [comment]
Yeah, but you don't need any of that if you just go to `chrome://inspect`. It'll discover your device and connect to that remote.

**Comment by OxNinja** [comment]
Thanks again for your support :)

The problem seems to happen on this line:

```js
const context = await device.launchBrowser();
```

Right before I can log info, but after nothing. Any idea?

**Comment by OxNinja** [comment]
Hello, update:

Using the following code helped me to precise the bug:

```js
const {_android: android } = require("playwright");

(async () => {
    const device = await android.devices()[0];
    console.log(device); // we get the first connected device
    const context = await device.launchBrowser(); // the browser launches
    console.log(context); // undefined
})()
```

The returned context of `AndroidDevice.launchBrowser()` is undefined.

The corresponding code seems to be defined here: https://github.com/microsoft/playwright/blob/f43b4efbc944c958ad22bf633fd67cc29c006ba3/src/client/android.ts#L229-L235

Although I tried to find the cause of this undefined return value, I couldn't find why.

**Comment by pavelfeldman** [comment]
You should go to chrome://flags on your mobile device and enable "Enable command line on non-rooted devices" experiment. See https://playwright.dev/docs/mobile/ - somehow that page is lost from our docs index.
