### ISSUE TITLE
[Question]: Doc: playwright.config.js example in v1.13.0 is different from v1.12.0

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#7776]
### Your question

Noticed v1.13.0 examples of playwright.config.js file shows 'export config'

https://playwright.dev/docs/test-configuration

<img width="1039" alt="Screen Shot 2021-07-21 at 11 28 46 AM" src="https://user-images.githubusercontent.com/22808594/126540812-7f7ce62e-f8c2-41e1-a81d-3b21d11b0718.png">

In v1.12.0 it's like this

<img width="1031" alt="Screen Shot 2021-07-21 at 11 28 54 AM" src="https://user-images.githubusercontent.com/22808594/126540833-3818877c-f77b-4828-87c9-3e3532eba8b5.png">

https://playwright.dev/docs/1.12.0/test-configuration

**Question:** Would like to know which syntax i should follow 1.12.0 or 1.13.0 ?

**Comment by pavelfeldman** [comment]
These two look the same to me, where is the `export config` you are referring to?

**Comment by vsravuri** [comment]
1.13 it's like this

```javascript
const config = {
  use: {
    headless: false,
    viewport: { width: 1280, height: 720 },
    ignoreHTTPSErrors: true,
    video: 'on-first-retry',
  },
};

module.exports = config;
```
the last line is **_module.exports = config;_**


where as in 1.12 it's like this
```javascript
module.exports = {
  use: {
    // Browser options
    headless: false,
    slowMo: 50,

    // Context options
    viewport: { width: 1280, height: 720 },
    ignoreHTTPSErrors: true,

    // Artifacts
    screenshot: 'only-on-failure',
    video: 'retry-with-video',
  },
};
```

**Comment by pavelfeldman** [comment]
That's the same thing. One of them uses an intermediate variable, that's all.

**Comment by pavelfeldman** [comment]
(see the first line of the snippets)

**Comment by vsravuri** [comment]
Thank you
