### ISSUE TITLE
[Bug]: Cannot take Screenshot via Config file. Creates empty folder only

### ISSUE THREAD

**Issue by AveryTheDev** [microsoft/playwright#7777]
### Playwright version

1.12.3

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

If you try to make it so that screenshots are taken via the config file, only the folder in which the screenshot should go is created. This is the same if the user does something like:

```
test.use({
  headless: false,
    viewport: { width: 1440, height: 800 },
    screenshot: 'only-on-failure', //Only creates empty folder
})

```

Videos can be created using the config file or the above manner just fine however. Attached is an example screenshot of what happens. 

<img width="1710" alt="Screen Shot 2021-07-21 at 4 18 44 PM" src="https://user-images.githubusercontent.com/23192489/126554386-d272e691-0e59-4db7-a876-aaf6d14b7a5c.png">

I've created a public repo with this code to reproduce and test the issue if [desired](https://github.com/AveryTheDev/playwright-test-clone).

**Comment by AveryTheDev** [comment]
This is what the config file looks like if you don't want to use the repo however

```
import { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {

  outputDir: './e2e_screenshots',
  use: {
    headless: false,
    viewport: { width: 1440, height: 800 },
    screenshot: 'only-on-failure', //Only creates empty folder
  },
  projects: [
    {
      name: 'Chrome',
      use: {
        browserName: 'chromium',
      },
    },
  ],
};

export default config;
```

**Comment by pavelfeldman** [comment]
Just looking at the code, I think `page.close()` in `e2e/baseFixtures.ts` could be an issue. You want to take a screenshot when the test is over, but you close all the pages before the test is over.

**Comment by pavelfeldman** [comment]
Yeah, I removed it and everything worked.

**Comment by AveryTheDev** [comment]
Okay so I noticed that if you remove that and you close the window of the page when the test is done if you're running it in headless mode, I'm assuming you removed that setting as well, that can also prevent the screenshot from being taken. 

Do you have a recommendation for best handling screenshots on error then if the config waits until all of the actions are completed before taking a screenshot?

**Comment by AveryTheDev** [comment]
Do you think the `page.close()` should interfere with screenshots? Maybe it would be better that the screenshot is taken before that line on default if that is necessary for a test.

**Comment by pavelfeldman** [comment]
> Okay so I noticed that if you remove that and you close the window of the page when the test is done if you're running it in headless mode, I'm assuming you removed that setting as well, that can also prevent the screenshot from being taken.

I did not remove other settings, just that one line. It should work in headless and headful as is.

> Do you have a recommendation for best handling screenshots on error then if the config waits until all of the actions are completed before taking a screenshot?

I don't think I follow the question. Playwright will take the screenshot on failure, just don't close the pages before it has a chance to do that!

> Do you think the page.close() should interfere with screenshots? Maybe it would be better that the screenshot is taken before that line on default if that is necessary for a test.

Yes, if you close the pages, there is nothing to take the screenshot of. Wht do you need to close the pages? They'll all close when the test ends anyways.

**Comment by JayKishoreDuvvuri** [comment]
I found that playwright not taking screenshots and videos even after giving the 	screenshot: 'only-on-failure',
		video: 'retry-with-video'  in config file of playwright test runner. I#m using Mac OS BigSur 11.5.2 is there any problem?

**Comment by JayKishoreDuvvuri** [comment]
Created new issue since this one is already closed. New issue https://github.com/microsoft/playwright/issues/8354
