### ISSUE TITLE
[Feature]: Make URL parameter optional in page.goto if global baseUrl is set

### ISSUE THREAD

**Issue by olesiaMartushkanova** [microsoft/playwright#7783]
### Feature request

**Playwright version: 1.13.0**

Since introducing `baseURL` global configuration, there is no need to have `url` parameter as required in `page.goto` API.

**Current behaviour:** 
To avoid this error, I have to write something like `page.goto('/)` (my code does not look good)

![Screen Shot 2021-07-22 at 4 57 02 PM](https://user-images.githubusercontent.com/48032815/126593501-b43605ba-0937-456f-8f44-c66474cf6363.png)
![Screen Shot 2021-07-22 at 4 56 32 PM](https://user-images.githubusercontent.com/48032815/126593509-a1e8b14e-97bb-4a15-bad3-a8b50a6e9541.png)

**Expected behaviour:**
If `baseURL` is set in global playwright configurations, `page.goto()` should default to `/`

**Comment by pavelfeldman** [comment]
While being a fair proposal, I don't think it is such a big deal. Let's see if we get a lot of upvotes for this one.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
