### ISSUE TITLE
[Question]: Is there any way by which we can assert whether the element is clickable or not in Playwright?

### ISSUE THREAD

**Issue by shiv-jirwankar** [microsoft/playwright#7788]
### Your question

Is there any way by which we can assert whether the element is clickable or not in Playwright?

**Comment by aslushnikov** [comment]
@shiv-jirwankar You can use [`page.click()`](https://playwright.dev/docs/api/class-page#page-click) with `trial: true`.

**Comment by vsravuri** [comment]
@aslushnikov 

Could you please help me to assert if these two are clickable in this [site](https://www.iana.org/domains/reserved) 

**Domain Names**

**Reserved Domains**

I want to return status of clickable from page object to spec file

**Comment by pavelfeldman** [comment]
That would be `await page.click('.my-button', { trial: true })`. If this throws, it was not clickable.
