### ISSUE TITLE
[Feature]: Can I somehow change the directory for saving screenshots?

### ISSUE THREAD

**Issue by ViaMay** [microsoft/playwright#7792]
### Your question

I used this https://playwright.dev/java/docs/test-snapshots function
Can I somehow change the directory for saving screenshots?

**Comment by pavelfeldman** [comment]
*Which language are you using? This page you refer to is for Java, it should not have test-snapshot section.*/

I assume you use JavaScript. Snapshot paths  are not configurable when you are using `expect.toMatchSnapshot`. But you can `page.screenshot({ path })` into any desired location.

Could you share more about your use case?

**Comment by ViaMay** [comment]
@pavelfeldman Yes I used JavaScript. Can you give an example of how you can save screenshots one level higher than the current test?

**Comment by mxschmitt** [comment]
It's not possible currently, the snapshot files when using toMatchSnapshot are always next to the actual test file (<test-file-name>-snapshots directory). Why does this not work for you?

**Comment by ViaMay** [comment]
@mxschmitt it works but it is not convenient. I want to create a shared library of screenshots. And for different tests to refer to it. Now that not possible (

**Comment by dgozman** [comment]
This sounds like a feature request for more control over expected screenshots.

**Comment by ViaMay** [comment]
@dgozman Thanks!

**Comment by ViaMay** [comment]
@pavelfeldman hi, very upset that this fix will not be included in the next release. Tell me whether to wait for him at all?

**Comment by nickofthyme** [comment]
In my use case I am testing against storybook stories and I would love to structure the output of the screenshots to match that of the stories to make them easier to find. Currently, I have a single test file that loops through all the stories so all the screenshots are thrown into a single directory making them hard to find. Controlling the output at a `test`/`expect` level would be ideal or even some mechanism at top-level config that has access to the `testInfo` to be used to determine the directory.

This issue (https://github.com/americanexpress/jest-image-snapshot/issues/97) is similar to the request, though less flexible than I propose, which allows a top-level config option (i.e. `customDiffDir`) to set the directory where the images are to be stored. This still lumps them all into a single file just different than the top level. But the reasoning behind the feature is similar IMHO.

Using `page.screenshot({ path })` only stores the screenshot to a given directory but this image is never used as the baseline image for `toMatchSnapshot`. So if I try doing something like...

```ts
import { test, expect } from '@playwright/test';

const myStories = [{ path: 'components/button' }];

myStories.forEach(({ path }) => {
  test('renders correctly', async ({ page }, info) => {
    await page.goto('https://my-site.com');
    const name = `${info.title}.png`;
    expect(await page.screenshot({ path: `foo.spec.ts-snapshots/${path}/${name}` })).toMatchSnapshot(name);
  });
});
```

https://github.com/microsoft/playwright/blob/1db41c330a7d50c1264da4a7b175861b701a105e/src/test/workerRunner.ts#L247-L259

**Comment by nickofthyme** [comment]
In my use case I am testing against storybook stories and I would love to structure the output of the screenshots to match that of the stories to make them easier to find. Currently, I have a single test file that loops through all the stories so all the screenshots are thrown into a single directory making them hard to find. Controlling the output at the `test`/`expect` level would be ideal that way we'd have access to the `testInfo` to use to determine the directory if necessary.

This issue (https://github.com/americanexpress/jest-image-snapshot/issues/97) is similar to the request, though less flexible than I propose, which allows a top-level config option (i.e. `customDiffDir`) to set the directory where the images are to be stored. This still lumps them all into a single file just different than the top level. But the reasoning behind the feature is similar IMHO.

Using `page.screenshot({ path })` only stores the screenshot to a given directory but this image is _never_ used as the baseline image for `toMatchSnapshot` comparison. So if I try doing something like...

```ts
// foo.spec.ts
import { test, expect } from '@playwright/test';

const myStories = [{ path: 'components/button' }];

myStories.forEach(({ path }) => {
  test('renders correctly', async ({ page }, info) => {
    await page.goto('https://my-site.com');
    const name = `${info.title}.png`;
    expect(await page.screenshot({ path: `foo.spec.ts-snapshots/${path}/${name}` })).toMatchSnapshot(name);
  });
});
```

After running the test I would get something like...

```
foo.spec.ts-snapshots/
├── basic-test-Chrome-linux.png
├── basic-test-Safari-linux.png
└── components/
    └── button/
        └── basic\ test.png
```

Where only the `./basic-test-*-linux.png` files are used for comparison and `components/button/*` files are virtually ignored.

## Solution idea

Add `path` to the `toMatchSnapshot` options.

Adding `path` to the options could allow the user to set a `path` to the screenshot for both writing and reading the baseline file. In the example above that would look something like...

```diff
myStories.forEach(({ path }) => {
  test('renders correctly', async ({ page }, info) => {
    await page.goto('https://my-site.com');
    const name = `${info.title}.png`;
-    expect(await page.screenshot({ path: `foo.spec.ts-snapshots/${path}/${name}` })).toMatchSnapshot(name);
+    expect(await page.screenshot()).toMatchSnapshot(name, { path });
  });
});
```

The output would then look something like...

```
foo.spec.ts-snapshots/
└── components/
    └── button/
        ├── basic-test-Chrome-linux.png
        └── basic-test-Safari-linux.png
```

> Note the file is still within the `foo.spec.ts-snapshots` directory for the given test, not sure how important this is but would be good to avoid collisions. Also note the file names are still processed as before into dash cased including the `project.name` and `snapshotSuffix`.

---

Pertinent code link

https://github.com/microsoft/playwright/blob/1db41c330a7d50c1264da4a7b175861b701a105e/src/test/workerRunner.ts#L247-L259

**Comment by topolanekmartin** [comment]
Hello, is there any progress? It would be nice to specify path in `toMatchSnapshot` function.

**Comment by sebastian-xitaso** [comment]
We have baseline images that are shared across tests, as they are only part of the web page. We use `locator.screenshot()`, not `page.locator()` to get the screenshot.

We can't specify the path to the shared image folder, so we'd have to duplicate our baseline images for every test.
