### ISSUE TITLE
[Bug]: page is set to null inside lambda expression

### ISSUE THREAD

**Issue by shtlrs** [microsoft/playwright#7795]
### Playwright version

1.12.2

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

node.js 14.17.2

### What happened? / Describe the bug

I'm trying to make a method that waits until a specific element's attribute contain a specific value.

### Code snippet to reproduce your bug

```shell
export default class WebComponent {
    public selectorString: string
    public page: Page;
    public elementHandle: ElementHandle;

    constructor(selectorString: string, page: Page) {
        this.selectorString = selectorString;
        this.page = page;
    }

   async waitForAttributeToEqualValue({ selectorString = this.selectorString, targetAttribute, 
    targetValue }) {
        await this.page.waitForFunction(async () => {
            const attributeValue = await this.page.getAttribute(selectorString, targetAttribute);
            return attributeValue === targetValue ;
        })
    }
}
```

**Comment by pavelfeldman** [comment]
This is working as intended, please refer to https://playwright.dev/docs/next/core-concepts#execution-contexts-playwright-and-browser for explanation. There is no "this.page" in your web page.
