### ISSUE TITLE
Dropdown list element is not selected when script is ran more than two times, worked in first 2 runs.

### ISSUE THREAD

**Issue by ALNQACODER** [microsoft/playwright#7804]
### Your question

Hi,

 I am able to run my script  successfully couple of times  but when I tried to run the same script again it is not selecting the dropdown value.

await page.click("text=Choose a line of business");
await page.waitForSelector('text=Retirement');
await page.click('label:has-text("Retirement")');

**Comment by pavelfeldman** [comment]
You can try our debugging tools: https://playwright.dev/docs/next/debug or provide steps we can use to reproduce the problem.

**Comment by ALNQACODER** [comment]
I am trying to select element ("Retirement") in the drop down list of "text=Choose a line of business", I did added wait for selector 
await page.waitForSelector('text=Retirement') but my script some times able to click 'text=Retirement' and some times it doesn't.
Did used wait function too but it still the same

**Comment by dgozman** [comment]
@ALNQACODER Thank you for additional information. Unfortunately, this is not enough. If you have a script that you can share the shows the problem, that would be great! Otherwise we cannot do anything meaningful here.

**Comment by mxschmitt** [comment]
Closing since the issues seems stale. Please reopen / create a new issue if you still encounter issues.
