### ISSUE TITLE
[Question]: Is there any way to define custom assertion error message with 'expect' function in Playwright?

### ISSUE THREAD

**Issue by shiv-jirwankar** [microsoft/playwright#7816]
### Your question

I want to define custom assertion error with 'expect' function so that whenever the assertion is getting failed then I can use that custom error message. Is there any way to do this in Playwright?

Linking:
- https://github.com/microsoft/playwright/pull/4778
- https://github.com/microsoft/playwright/issues/4665

**Comment by pavelfeldman** [comment]
You can extend `expect` library like so: https://jestjs.io/docs/expect#expectextendmatchers

**Comment by asterium** [comment]
Hey @pavelfeldman 
It's nice that there's a way to provide custom matchers, and specify adjusted messages there, but it would be really great if there is a way to have this process more streamlined, having such ability out of the box. 

I saw there were some attempts for jest lib already: 
https://github.com/mattphillips/jest-expect-message

It would be really awesome to see such functionality in future releases.

**Comment by neongreen** [comment]
```typescript
// playwright.config.ts

expect.extend({
  fail(_: null, msg: string) {
    return {
      message: () => msg,
      pass: false
    }
  }
})
```

I ended up defining this in `playwright.config.ts`. Now I can call `expect(null).fail("Whatever")` and it will fail with the message "Whatever". Note that for TS to know that `.fail` is available you'd also have to add a declaration to `global.d.ts` but I haven't found where to put `global.d.ts` in Next.js so I just `// @ts-ignore`'d it.

Agreed that it should be available out of the box.

**Comment by Oliver-Fish** [comment]
You can also just throw an error to fail a test without having to build a custom expect method.

```Javascript
  throw new Error("test failed for reason X");
```

**Comment by mpelzsherman** [comment]
In case, like me, you ended up here looking for how to do this:

https://playwright.dev/docs/test-assertions#custom-expect-message
