### ISSUE TITLE
[Feature]: Is it possible to add method to handle children elements inside the father element?

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#7817]
### Feature request

Hi all!
Thanks for your frequent updates! It's awesome!

Is it possible to add some method to handle elements inside a particular element? 
For example - after finding an element (like a form) we will get other methods to handle children elements inside father the element (rows, td's etc.).

The example of something like that is 'within' method of Cypress:
[https://docs.cypress.io/api/commands/within#Syntax](https://docs.cypress.io/api/commands/within#Syntax)

**Comment by pavelfeldman** [comment]
You should get ElementHandle for the parent element via page.waitForSelector. Then use its API to work with its children. It has

https://playwright.dev/docs/api/class-elementhandle#element-handle-query-selector-all
https://playwright.dev/docs/api/class-elementhandle#element-handle-eval-on-selector-all

Like when you work with DOM

**Comment by AlexKomanov** [comment]
@pavelfeldman 
Thanks. I know about it.
The question is - if it is possible to add some method like in the case of Cypress and chain next methods inside?

**Comment by pavelfeldman** [comment]
I don't think so. We use a regular programming model, w/o control flow chaining. Why do you want to chain?

**Comment by AlexKomanov** [comment]
@pavelfeldman 
I found it very useful in the case of Cypress.
If it is not possible - it's clear enough. 
You can close.
Thanks!

**Comment by dgozman** [comment]
It looks like there is no action item here.
