### ISSUE TITLE
[Feature]: Soft/queued asserts/expects so that it does not fail after the first one

### ISSUE THREAD

**Issue by shiv-jirwankar** [microsoft/playwright#7819]
### Your question

I have a scenario where we have multiple scenarios to assert. I want to finish off all assertions irrespective of their status and need to see what all assertions got passed or failed once all validations steps were done. 
Is there any way to do this in Playwright?

**Comment by pavelfeldman** [comment]
I did not find any soft assert wrappers for `expect`, but this is a popular request, so we'll do that.

**Comment by A-ZC-Lau** [comment]
maybe instead of "soft assert", it would be queued asserts? Would seem easier to implement.

**Comment by dimaBondarenko** [comment]
IMHO this feature or something like this #7786 would be one of the determinant factors to choose Playwright runner for people who think of migrating from legacy frameworks which use Jasmine soft assertions (Protractor, for example) or people that worked previously with Java frameworks where TestNG soft assertion was widely used. At my company I told several people about Playwright and they were pretty excited, but the absence of soft assertions stopped them to consider this tool further and do the leap of faith 🙂

**Comment by refactoreric** [comment]
(Not needing this myself (yet?) but stumbled on the issue and thought I'd share some examples)

In case you're looking for examples how it looks in other assertion libraries:
https://fluentassertions.com/introduction#assertion-scopes
https://docs.nunit.org/articles/nunit/writing-tests/assertions/multiple-asserts.html
(Both are examples from .NET)

**Comment by refactoreric** [comment]
And now as I'm browsing through our existing Protractor tests, I see we are working around chai limitations there by having one dedicated "it" block (test) per assertion. So the action is done in a previous "it" block, and the assertions follow each in their own separate "it" block. That wouldn't work in @playwright/test.

So I think we need this after all.

**Comment by AndyGleed** [comment]
This feature would be very useful for my company as well.  Not a deal breaker to not have it but would be greatly appreciated if this could be added at some point :)

**Comment by amrsa1** [comment]
Hi guys any update regarding this feature , i saw that @aslushnikov have created a PR but its blocked for some reasons.
It will be really awesome if we saw it live soon

**Comment by aslushnikov** [comment]
@amrsa1 that's a work-in-progress. The PR didn't pass the code review and quality checks yet, so it's not landed. We'll land it if its up to our standards!

**Comment by amrsa1** [comment]
Thats awesome looking forward to it
