### ISSUE TITLE
[Feature]: Hide Elements from screenshot

### ISSUE THREAD

**Issue by rollin-cogers** [microsoft/playwright#7820]
### Feature request

Sometimes when taking a full page screenshot there is a dynamic element that would throw off the test. Sometimes this is a carousel, or a video. This can be avoided by taking a screenshot of individual elements instead of the entire page, but this does not work for every use case.

Something like this would be excellent:
`await page.screenshot({hide: ['.carousel', '#video']})`
Where hide accepts an array of string selectors.

Thank you for the excellent automation tool!

**Comment by pavelfeldman** [comment]
Starting collecting feedback for this one to see upvotes. For how you can:

```js
for (const selector of ['.carousel', '#video'])
  await page.$$eval(nodes => nodes.map(node => node.style.visibility = 'hidden');
await page.screenshot();
for (const selector of ['.carousel', '#video'])
  await page.$$eval(nodes => nodes.map(node => node.style.removeProperty('visibility'))`
```

**Comment by aslushnikov** [comment]
@rollin-cogers would it work if we black out the elements for you? 

For example:

```js
await page.screenshot({
  blackout: ['.carousel', '#video'],
})
```

**Comment by aslushnikov** [comment]
And folding this one in the most popular https://github.com/microsoft/playwright/issues/10162
