### ISSUE TITLE
[Bug]: Transparent stripes on screenshots 

### ISSUE THREAD

**Issue by chrstnv** [microsoft/playwright#7821]
### Playwright version

1.10.0

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

Hi! :)

This discussion is a continuation of this issue: https://github.com/microsoft/playwright/issues/6744. 

So, I've tried to pass the `--disable-gpu` arg to chromium.launch() method, but unfortunately it didn't make a shot :( 
I see transparent stripes in the screenshots still.

Here is my little code snippet:
```
beforeEach(async () => {
    browser = await chromium.launch({headless: false, args: ['--disable-gpu']});
    context = await browser.newContext({ignoreHTTPSErrors: true});

    page = await context.newPage();
});
```

Maybe you have another assumptions about this problem? Thanks!!

**Comment by pavelfeldman** [comment]
Is there a public page we could reproduce it with? Disabling GPU is the first advice we give, but maybe something else is wrong here.

**Comment by chrstnv** [comment]
Unfortunately, it's not a public page. I'll try to make a public repro and be back soon.

**Comment by mxschmitt** [comment]
Closing as part of the triage process. Please create a new issue/reopen if you have a reproducible, thanks!
