### ISSUE TITLE
[Question]: Why was page.title() was not working when using fixture.

### ISSUE THREAD

**Issue by Lakshmi-Yaswanth** [microsoft/playwright#7824]
### Your question

Ill give my piece of code:
login.ts=>Code
 ```
 public async login(username: string, pass: string) {
        await this.enterUserName(username);
        await this.enterUserPassword(pass);
        await Promise.all([
            this.page.waitForNavigation({ 'waitUntil': 'domcontentloaded' }),
            this.clickLoginBtn()
        ]);
    }
```
login.test.ts=>code
```
test.describe("Login as user", () => {

    test("test 1", async ({ loginPage, page }) => {
        await page.goto(environment.frontendUrl, { waitUntil: 'load', timeout: 100000 });
        expect(page.url()).toBe(environment.frontendUrl);
        await loginPage.login(environment.frontendUser, environment.password);
        expect(await page.title()).toBe("RevaturePro - Dashboard");
    });
})
```
Error which is getting is:

  1) [chromium] › tests\login.test.ts:6:5 › Login as user test 1 ===================================

    Error: expect(received).toBe(expected) // Object.is equality

    Expected: "RevaturePro - Dashboard"
    Received: "RevaturePro - Login"
Is there any way to handle it.please give any approach if possible.Thank you

**Comment by mxschmitt** [comment]
Instead of asserting the current title you could wait until the title is the expected one. This can be achieved via:

```js
await page.waitForFunction(() => document.title === 'RevaturePro - Dashboard')
```

**Comment by Lakshmi-Yaswanth** [comment]
Thank u @mxschmitt.Ill try this approach and let u know. Thank u so much.

**Comment by Lakshmi-Yaswanth** [comment]
I have used the approach  which u have given. But i couldn't get the output which was expected .I trying to solve the error. 
which is
```
page.waitForFunction: Evaluation failed: TypeError: result.finally is not a function
        at Object.run (<anonymous>:2036:21)
        at eval (eval at evaluate (:338:25), <anonymous>:1:14)
        at UtilityScript.evaluate (<anonymous>:341:16)
        at UtilityScript.<anonymous> (<anonymous>:1:44);
```
Can u help me how to solve it. If Possible. Thank u

**Comment by mxschmitt** [comment]
Your site probably overrides Promise that is missing the finally method. I don't think we can do anything good here, since waitForFunction must be evaluated inside the page.

Is it possible that you can share the URL of your site so we can find out which Promise polyfill is breaking it? Maybe we can fix it in their implementation to make the web better.

Related #6233

**Comment by Lakshmi-Yaswanth** [comment]
Sorry @mxschmitt  we can't share the url. Thank u for uour response. Is there anyway that u can tell process to fix implementation from our side to make it web better.

**Comment by dgozman** [comment]
You can wait for something specific on the page before checking the title. For example:
```js
// ...
await page.waitForSelector('text=Welcome to RevaturePro Dashboard');
expect(await page.title()).toBe("RevaturePro - Dashboard");
// ...
```

Basically, choose something that is present on the dashboard page, but not on the login page, and you should get the expected result.

**Comment by dgozman** [comment]
Closing this one. If you still have questions, feel free to ask!
