### ISSUE TITLE
[Feature]: Test Runner to Support running n projects from cmd line

### ISSUE THREAD

**Issue by jithinjosejacob** [microsoft/playwright#7826]
### Feature request

I have a project which contains 5 projects

I need to run 2 projects in DEV Environment and 3 projects in Test Environment

npx playwright test --projects=v1,v2 .

npx playwright test --projects=v1,v2 ,v3

Currently we can run all projects using npx playwright test or 1 project using npx playwright test --project=v1

**Comment by archlichking** [comment]
+1, this is very useful for us too

**Comment by mxschmitt** [comment]
Closing since it got implemented in https://github.com/microsoft/playwright/pull/8600
