### ISSUE TITLE
[Question]: Docker Issue when trying to install Chrome

### ISSUE THREAD

**Issue by akshayp7** [microsoft/playwright#7829]
### Your question

I was trying to run my test cases on Chrome on Docker, it gave me a message stating me to install chrome.
When I run the command "RUN npx playwright install chrome", I am getting the below issue in Docker

#10 0.502 /app/node_modules/@playwright/test/bin/reinstall_chrome_stable_linux.sh: line 21: wget: command not found

Playwright Version : 1.13.0
npm version :  7.20.1
node version : v14.17.3

NOTE : Tests run fine on Chromium browser.

Things I tried:
1.  upgrade npm from 7.20.0 to 7.20.1
2. FROM mcr.microsoft.com/playwright:v1.13.0-bionic (I used latest tag too but same issue)

**Comment by mxschmitt** [comment]
If you manually do `apt-get install -y wget` it should fix it as a workaround.

(We already fixed it in #7793)

**Comment by akshayp7** [comment]
Thanks this solved my issue.
