### ISSUE TITLE
[Feature] Expose page.target()

### ISSUE THREAD

**Issue by umanghome** [microsoft/playwright#783]
We're opening a popup and need to get its parent. Puppeteer give a [`page.target`](https://pptr.dev/#?product=Puppeteer&version=v2.1.0&show=api-pagetarget) API that lets us do that.

Target is present as a Symbol on the Page, but there's API that exposes it. It would be great if there was a way to get a reference to it. Currently using this hack:

```js
/**
 * Playwright doesn't expose an API to get the target.
 * This is a hack to get it.
 * @param {Page} page
 *
 * @returns {Target}
 */
function getTarget(page) {
  const symbol = Object.getOwnPropertySymbols(page).find(
    symbol => String(symbol) === 'Symbol(target)'
  );

  if (!symbol) {
    return;
  }

  return page[symbol];
}
```

**Comment by yury-s** [comment]
There is no such API in Playwright today. You learn about new popups by listening to the [`popup`](https://github.com/microsoft/playwright/blob/master/docs/api.md#event-popup) event on the opener so you should already now what it is for each new popup page. Can you provide some details on why it is not sufficient in your scenario?

**Comment by umanghome** [comment]
The `popup` event doesn't seem to work for my case. [`targetcreated`](https://github.com/microsoft/playwright/blob/master/docs/api.md#event-targetcreated) seems to work, though. Moving it to a #873.

**Comment by umanghome** [comment]
This seems to be incorrectly closed too. I'm trying to get the `CRTarget` associated with a `Page`. `page.opener()` just gives me the opener's `CRTarget`.
