### ISSUE TITLE
[Question]: How to debug: No resource with given identifier found

### ISSUE THREAD

**Issue by nicoandmee** [microsoft/playwright#7831]
### Your question

*Context*: I have some code that is using playwright to perform some basic automation (logging into a website). The cookies are pre-set and the process basically boils down to load a page, click sign in button (if present), intercept some XHR responses as json. I think clicking the sign in btn triggers a navigation.

*My problem*: Occasionally I encounter an error where the `interceptedResp.json()` is undefined. When debugging it locally I found this error produced on the CDP level: `No resource with given identifier found`. Researching this led me to [this](https://github.com/puppeteer/puppeteer/issues/2258) where I learned at least with puppeteer `resources get dumped after page commits navigation`. 

In my case I am doing 
```js
context.on('response', async (response) => {
      const url = response.url();

      if (url.includes(respURL1) && response.status() === 200) {
        respBody = await response.json();
      }

      if (url.includes(respURL2) && response.status() === 200) {
        headers = response.request().headers();
      }
    });
```

And clicking the btn like this:
```js
if (visible) {
await Promise.all([
 page.waitForResponse(response => response.url().includes(respURL1) && response.status() === 200),
 page.waitForResponse(response => response.url().includes(respURL2) && response.status() === 200),
 page.click('#SIGNINBTN')
 ]);
}
```

Destructuring the responses directly from the above wasn't an option because sometimes the sign in btn doesn't appear, and in that case I wanted to still intercept the responses. Strangely the above promise also resolves (so I know the response was there) but `respBody` is still undefined. How can I debug this issue and/or understand what's going wrong here?

**Comment by dgozman** [comment]
@nicoandmee This is indeed a real limitation. This feature is implemented differently in Firefox, so it might just work for you if you use `firefox.launch` instead of `chromium`. The most reliable way to get responses would be #1774, but that is still under construction.

Let me know if you have more questions.

**Comment by nicoandmee** [comment]
@dgozman It's been a while and I had forgotten about this error. But recently it was brought to my attention again and as a "fix" I changed from this:
```js
context.on('response', async (response) => {
    const url = response.url();

    if (url.includes(respURL1) && response.status() === 200) {
        respBody = await response.json();
    }

    if (url.includes(respURL2) && response.status() === 200) {
        headers = response.request().headers();
    }
});
```

to this:
```js
await page.route('**/*', async (route) => {
    const url = route.request().url();

    if (url.includes(respURL1)) {
        const response = await page.request.fetch(route.request(), { ignoreHTTPSErrors: true, failOnStatusCode: true });
        respBody = await response.json();
        return route.fulfill({ response });
    }

    if (url.includes(respURL2)) {
        headers = route.request().headers();
    }

    return route.continue();
});
```

I thought maybe the 2nd would avoid some kind of race condition with the 1st, where the page might be already navigating so the resources would be dumped. As it turns out though, the 2nd also fails. When I login to the site in chrome browser, it fails (I can't view the response, I see that same error). 
But when I login with firefox, it works and I'm able to view the json response. From the json I found that all accounts that are used to login on this site have some privileges suspended and all have a popup shown upon login. Somehow, this popup being shown is preventing chrome from loading the response body (I assume because it triggers navigation, so resources get dumped, and therefore CDT can't find what it doesn't have). I can see the response has a 200 status code, headers, etc. but no body. 

I have two questions:
- Does that theory make sense?
- Where can I learn more about the internals of how CDT handles cases such as this, and why does firefox implementation work but chrome does not.

Thank you! Sorry about the backstory.

**Comment by adrianodennanni** [comment]
Just a quick note: another easy way to fix it seem to be putting this before any interception:
```javascript
await page.route('**', async (route) => route.continue());
```

**Comment by dr3adx** [comment]
> Just a quick note: another easy way to fix it seem to be putting this before any interception:
> 
> ```js
> await page.route('**', async (route) => route.continue());
> ```

how does this fix it i dont understand?

**Comment by adrianodennanni** [comment]
After pasting this in the code, the resource error stopped happening. I don't know Chrome/Playwright internally too well to know what's going on, but at least the problem is not happening anymore.

**Comment by Vitalicus** [comment]
I had a "-" simbol instead of "=" in a onload function
