### ISSUE TITLE
[Bug]: Unable to set reporter -> outputFile path through enviroment variable created in globalSetup

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#7832]
### Playwright version

1.13.0

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium

### Other information

Node v14.17.0 

### What happened? / Describe the bug

I have a requirement to output the reporter output file (json / xml file) to dynamic folder created with appended timestamp.

I create the folder path in globalSetup and assign it to environment variable.
```javascript
process.env.JUNITREPORTDIR = '/tmp/playwright_test1-07-25-2022';
```
When i set 
```javascript
process.env.JUNITREPORTDIR
```
in reporter -> outputFile, i see the error when i run the test.

```javascript
reporter: [ ['junit', { outputFile: path.join(process.env.JUNITREPORTDIR,'junit_results.xml') }] ],
```

```javascript
The "path" argument must be of type string. Received undefined
```
<img width="1342" alt="Screen_Shot_2021-07-25_at_11_21_12_AM" src="https://user-images.githubusercontent.com/22808594/126909346-758e3160-1456-4366-a483-6dd9e3da0069.png">

If i do this, the xml output is displayed in the console.
```javascript
process.env.JUNITREPORTDIR = '/tmp/playwright_test1-07-25-2022/junit_results.xml';

reporter: [ ['junit', { outputFile: process.env.JUNITREPORTDIR }] ],
```
<img width="1156" alt="Screen_Shot_2021-07-25_at_11_23_20_AM" src="https://user-images.githubusercontent.com/22808594/126909354-3fbb9e00-501c-4689-b909-64351988f7f9.png">

**It seems reporter outputFile path is parsed before loading the globalSetup. I didn't see any issues when i set the outputDir, downloadsPath through environment variables created in globalSetup.** 

### Code snippet to reproduce your bug

```shell
playwright.config.js

const fs = require('fs');
const path = require('path');

module.exports = {
    globalSetup: require.resolve('./global-setup.js'),
    timeout: 60000,
    use: {
        headless: false,
        viewport: { width: 1280, height: 720 },
        ignoreHTTPSErrors: true,
        video: 'on-first-retry',
    },
    outputDir: process.env.TESTOUTPUTDIR,
    //reporter: [ ['junit', { outputFile: path.join(process.env.JUNITREPORTDIR,'junit_results.xml') }] ],
    reporter: [ ['junit', { outputFile: process.env.JUNITREPORTDIR }] ],

    projects: [
        {
            name: 'pw-test',
            testDir: 'spec',
            testMatch: [
                'foo.spec.js'
            ],
            use: {
                browserName: 'chromium',
                channel: 'chrome',
            },
        },
    ],
};

```

global-setup.js
```javascript
const fs = require('fs');
const path = require('path');

module.exports = async () => {

    process.env.TESTOUTPUTDIR = '/tmp/playwright_test1/';
    console.log(process.env.TESTOUTPUTDIR);
    process.env.JUNITREPORTDIR = '/tmp/playwright_test1-07-25-2022/junit_results.xml';
    console.log(process.env.JUNITREPORTDIR);

};
```

foo.spec.js
```javascript
const { test, expect } = require('@playwright/test');

test('basic test', async ({ page }) => {
    await page.goto('https://playwright.dev/');
    const name = await page.innerText('.navbar__title');
    expect(name).toBe('Playwright');
});
```
```


### Relevant log output

N/A

**Comment by mxschmitt** [comment]
It seems like you are using the wrong environment variables to set the output file name, where did you get it from? There is an official one which gets lazily loaded where the global setup process env changes should affect it.

The following in the global setup works for me:

```ts
export default () => {
  process.env.PLAYWRIGHT_JUNIT_OUTPUT_NAME = "fooobar.xml"
}
```

Regarding to your example, it is correct that first the config gets parsed and then the global setup gets executed, we would need to end up with a callback e.g. to prevent that or read it multiple times. For your downloads-path use-case, it's probably because the config gets loaded again on the worker level where then the process.env from the global setup is set.

**Comment by vsravuri** [comment]
Sorry, i overlooked the documentation and defined my own environment variable name thinking it will work. Yes it works with the official environment variable provided in the documentation.

```javascript
process.env.PLAYWRIGHT_JUNIT_OUTPUT_NAME
```

It will be helpful if there is a section in the documentation to list all the official environment variables used in Playwright.

**Comment by mxschmitt** [comment]
Closing then, Playwright Test does not use much environment variables, only in special scenarios like this one. Happy to hear that it's working now.
