### ISSUE TITLE
[Question]: route.fulfill after browser closes

### ISSUE THREAD

**Issue by nicoandmee** [microsoft/playwright#7833]
### Your question

Currently I am sometimes getting an error/warning like: `(node:13440) UnhandledPromiseRejectionWarning: route.fulfill: Target page, context or browser has been closed`. I think this is because I am routing all requests, intercepting some of them and fetching the response manually, feeding that back via `route.fulfill()`. The requests hang sometimes so the browser ends up closing with some still in flight. Not a big deal because the code still succeeds but I am wondering:

- What happens if browser closes and route.fulfill() hasn't been called yet? Does `route.fulfill()` have a means to check if browser has been closed?

**Comment by mxschmitt** [comment]
You can manually do `route.fulfill().catch(() => {})` as a workaround instead of checking if the browser is already closed. Does this work for your use-case?

**Comment by nicoandmee** [comment]
it does! thanks
