### ISSUE TITLE
[Question]: For what do I need to wait when clicking on next page?

### ISSUE THREAD

**Issue by PoddarYash** [microsoft/playwright#7837]
### Your question

For what do I need to wait when clicking on next page?

![image](https://user-images.githubusercontent.com/66639139/126954216-360645fc-89da-43cc-b16a-ac6d64439e9d.png)

**Comment by dgozman** [comment]
@PoddarYash Usually it just works without any specific waits. If you share more details, we might be able to help you better.

**Comment by akshayp7** [comment]
await Promise.all([
            this.page.waitForNavigation(),
            webUIActions.clickElement(NEXT_BUTTON_LOC)
        ]);

**Comment by dgozman** [comment]
@akshayp7 Unfortunately, this snippet does not help at all. I need at least the page url and the exact `NEXT_BUTTON_LOC` value. Sharing the full script would be ideal.

**Comment by akshayp7** [comment]
Oh Ok, I was providing the solution to question asked by PoddarYash, he might give some more insight on issue.

**Comment by dgozman** [comment]
@akshayp7 Sorry, I misread your comment, thinking this was a repro snippet!

**Comment by mxschmitt** [comment]
Closing as part of the triaging process. Please reopen/ create a new issue if you still encounter issues.

Usually you use e.g.
- [await page.waitForSelector()](https://playwright.dev/docs/api/class-page#page-wait-for-selector)
- [await page.waitForURL()](https://playwright.dev/docs/api/class-page#page-wait-for-url)
- [await page.waitForNavigation()](https://playwright.dev/docs/api/class-page#page-wait-for-navigation)
