### ISSUE TITLE
[Question]: Why is the `Sec-WebSocket-Key` hardcoded?

### ISSUE THREAD

**Issue by OxNinja** [microsoft/playwright#7839]
### Your question

I saw this in the code:
https://github.com/microsoft/playwright/blob/f43b4efbc944c958ad22bf633fd67cc29c006ba3/src/server/android/android.ts#L407

According to https://datatracker.ietf.org/doc/html/rfc6455#page-7 and https://datatracker.ietf.org/doc/html/rfc6455#page-8 shouldn't this field be randomized in order to prevent the server to respond to unwanted connections?

**Comment by pavelfeldman** [comment]
It is Ok!
