### ISSUE TITLE
[Question]: Use Playwright by users without install Node

### ISSUE THREAD

**Issue by mlxgang** [microsoft/playwright#7840]
### Your question

Hello everyone I use Playwright in my project on Vue+Electron. In Electron builder settings use `externals: ['playwright-chromium']` but end users can`t use Playwright module with error:

> Looks like Playwright Test or Playwright was just installed or updated. Please run the following command to download new browsers: npx playwright install

How users can use Playwright module without install Node and Playwright? What I can use to package browsers with Electron-Builder?

**Comment by dgozman** [comment]
You probably want to use `PLAYWRIGHT_BROWSERS_PATH`, here are the docs: https://playwright.dev/docs/library#managing-browser-binaries.

See also #2539 for a similar discussion.
