### ISSUE TITLE
[Question]: How do I get Tracing data out of Chrome DevTools Protocol?

### ISSUE THREAD

**Issue by sebastianplsim** [microsoft/playwright#7841]
### Your question

I'm trying to record Chromium Tracing data in a PlayWright test. This Tracing data will be used to measure impact of changes in a CI Pipeline.

I've been using the [newCDPSession](https://playwright.dev/docs/api/class-cdpsession) docs to help me get going. However, I've found that `Tracing.dataCollected` & `Tracing.tracingComplete` events from the [Chrome DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/tot/Tracing/) are never called.

Here's a snippet of the test code I've written.
```js
const { test, expect } = require("@playwright/test"); // v1.13.0

test("basic test", async ({ page, context, browser }) => {
  let dataCollected;
  let tracingComplete;

  const client = await context.newCDPSession(page);

  client.on("Tracing.dataCollected", (payload) => {
    dataCollected = payload;
  });

  client.on("Tracing.tracingComplete", (payload) => {
    tracingComplete = payload.stream;
  });

  await client.send("Tracing.start");

  await page.goto("https://playwright.dev/");

  await client.send("Tracing.end");

  await page.close();

  expect(tracingComplete || dataCollected).toBeTruthy();
});
```

It's likely that I'm missing something really obvious. If you can spot something I need to change - or you've run into similar issues & know a better way to get access to this data let me know 🙏

**Comment by mxschmitt** [comment]
You can use `Browser.startTracing` and `Browser.stopTracing` see here: https://playwright.dev/docs/api/class-browser#browser-start-tracing

This uses the Chrome Tracing under the hood, this should work for your use-case.

**Comment by sebastianplsim** [comment]
Thanks @mxschmitt - will use this going forwards 👍

**Comment by Mifrill** [comment]
Hey @sebastianplsim did you find a way to make events called in your snippet?

As I see the implementation of tracing in `Browser.startTracing and Browser.stopTracing` is quite similar to your snippet solution:
https://github.com/microsoft/playwright/blob/c373986ca0b91b76d4910ce0617b55e50934114c/packages/playwright-core/src/server/chromium/crBrowser.ts#L242-L262

https://github.com/microsoft/playwright/blob/c373986ca0b91b76d4910ce0617b55e50934114c/packages/playwright-core/src/server/chromium/crBrowser.ts#L268-L269

What's needs to be changed in your snippet to fire `Tracing.tracingComplete` event?

**Comment by Mifrill** [comment]
I did tried to use `categories` and `transferMode: "ReturnAsStream"` but still not good
