### ISSUE TITLE
[Question]: no proxy variable support 

### ISSUE THREAD

**Issue by agaramudhala** [microsoft/playwright#7842]
### Your question

Does playwright support no_proxy variable ? I’m not able to access intranet urls inside playwright docker img in Jenkins

**Comment by dgozman** [comment]
Playwright uses OS-configured proxy, unless you set `proxy` option as described here: https://playwright.dev/docs/network#http-proxy. Does that answer your question? If not, please provide more details about your setup so we can better understand the problem/question.

**Comment by agaramudhala** [comment]
I did set proxy per playwright docs. With that I'm able to access internet's url not intranet ones.. though I had set no_proxy variable explicitly, it's not picking no_proxy and blocks intranet apps

**Comment by dgozman** [comment]
@agaramudhala What is this `no_proxy` you are talking about? Where do you set it? Please provide more details about your setup, otherwise we won't be able to help.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. 

Using `proxy.bypass` is probably for what you are looking for. A list of hostnames which don't get proxied when a proxy is set, see here: https://playwright.dev/docs/api/class-browsertype#browser-type-launch-option-proxy
