### ISSUE TITLE
[Question]: How to manage multiple environment config in playwright

### ISSUE THREAD

**Issue by ssachdevatwist** [microsoft/playwright#7843]
### Your question

Is there any utility from playwright that can manage multiple env config. For example,  most of the projects will have QA, DEV , STAGING etc env. 

How can one switch from one env to other from code as well as CLI level?

**Comment by dgozman** [comment]
@ssachdevatwist Could you please provide more details about your usecase?

Overall, `playwright.config.js` is just a javascript file, so you can do configurations based on your `process.env` or anything else. However, if we know more details, we might suggest or even help with some specific scenarios.

**Comment by ssachdevatwist** [comment]
Thanks, @dgozman for your reply.

We have 3 different environments in my project ( DEV, QA, and Staging) and each of these environments have different hosts which are needed to perform end to end

"env":{
        "QA":{ 
            "ecomUrl":"https://ecom-qadomain.example.com",
            "cmsUrl":"https://cms-qadomain.example.com",
            "sfdcUrl":"https://sfdc-qadomain.example.com
        },
        "STAGING":{
            "ecomUrl":"https://ecom-stagingdomain.example.com",
            "cmsUrl":"https://cms-stagingdomain.example.com",
            "sfdcUrl":"https://sfdc-stagingdomain.example.com
        }
       
    }

What I am looking for is a way to run tests based on environment value which can be changed in some config value locally as well as from CLI
P.S I am coming from a Java Selenium background so not sure how to handle multiple env config in playwright

**Comment by dgozman** [comment]
@ssachdevatwist Are you looking for using the [`baseURL`](https://playwright.dev/docs/api/class-fixtures#fixtures-base-url) based on some config? Here is a basic sketch for you:

```ts
// playwright.config.ts

const json = require('./path-to-env.json');
const ecomUrl = json[process.env.DEV_ENV].ecomUrl;
const config = {
  use: {
    baseURL: ecomUrl
  },
};
export default config;
```

You can then run it like this:
```bash
DEV_ENV=STAGING npx playwright test
```

Does this help?

**Comment by mxschmitt** [comment]
Closing since the issue seems answered, please create a new issue if you still encounter issues.
