### ISSUE TITLE
[Bug]: Trace Viewer red dot does not line up with active element

### ISSUE THREAD

**Issue by NickTulett** [microsoft/playwright#7847]
### Playwright version

1.13

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

After the fix for #7173 I still see the red dot not overlaying the active element properly.

I'm not sure it is possible to achieve this by parsing scroll positions - my app has nested scrollable areas and the red dot is still misaligned in 1.13.
In some cases the alignment is worse now than before because it is also wrong on the horizontal axis - where there are no scrollbars.

Could you simply highlight the element with CSS rather than trying to position another element over it?

**Comment by dgozman** [comment]
@NickTulett Could you please provide a repro that we can run locally? We'd like to understand what the problem is before addressing it 😄 Otherwise, I am not sure we can do anything that would help.

**Comment by NickTulett** [comment]
[justSignIn.zip](https://github.com/microsoft/playwright/files/6883646/justSignIn.zip)
@dgozman you can see in the last step in this trace that the red dot does not line up with the "Log in" button.

**Comment by dgozman** [comment]
@NickTulett Thank you for the trace. I see that you use `noDefaultViewport: true` - perhaps that's the problem? We'll take a look.
