### ISSUE TITLE
[Bug]: onBeginTest not test when `test.only` is used in reporter API

### ISSUE THREAD

**Issue by weyert** [microsoft/playwright#7850]
### Playwright version

1.13.0

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium

### Other information

Node.js 14.17.3
macOS 11.5

### What happened? / Describe the bug

I tried to write a custom reporter so added logs in each of the functions of the Reporter API and noticed that `onBeginTest` case didn't log as expected when you  have 6-7 test cases and you use `test.only` to skip all other cases.

**Comment by dgozman** [comment]
This does not reproduce for me locally. See #7862 for a test. Do you have a full repro with your custom reporter, config file and test file? Without a repro we are not able to help here.

**Comment by weyert** [comment]
Yeah, I will work on a reproducible case :)

**Comment by mxschmitt** [comment]
Closing as part of the triage process. Please reopen/create a new issue if you still encounter this issue.
