### ISSUE TITLE
[Feature]: element selector explorer in the trace viewer

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#7853]
### Feature request

it would be very useful if the same selector explorer thing that that's available in the inspector was also present for the dom snapshots in the trace viewer

![image](https://user-images.githubusercontent.com/57028336/127108876-b96709c1-d9ef-4925-8dc3-f7b3452d4c6a.png)

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by KotlinIsland** [comment]
This feature is intensely based, it looks like a mistake was made by closing it.

**Comment by logan5259** [comment]
Is it a joke? Selector playground is a basic functionality - must have in the modern framework. Please add a component which allows users to verify playwright selectors directly in trace viewer and snapshots.

**Comment by DetachHead** [comment]
@logan5259 they did, see #20965

**Comment by logan5259** [comment]
Yes, thank you I've missed it ;)  [DetachHead](https://github.com/DetachHead)
