### ISSUE TITLE
[Bug]: timeout at element level not working when used playwright test runner

### ISSUE THREAD

**Issue by ssachdevatwist** [microsoft/playwright#7854]
### Playwright version

1.13.0

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

I am using playwright test runner and below is my playwright.config.ts.

Issue --> Explicit timeout is not respected by playwright. for example for below command, I am expecting , playwright should wait for 5000 ms before throwing exception but it throws exception after waiting for 3000ms , as mentioned in the config

await page.click("//label[text()='Checkout']", {timeout:5000});  

```
import { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  use :{
    browserName : 'chromium',
    headless : false ,
    screenshot: 'only-on-failure'
  },
  timeout : 3000,
  globalTimeout: 60000,
  testDir : 'integration',
  reporter: 'list'
    
  };
  export default config;
```

<img width="1384" alt="Screenshot 2021-07-27 at 2 02 53 PM" src="https://user-images.githubusercontent.com/87409477/127123331-71509d51-de7f-4608-b029-372bca379b07.png">

**Comment by dgozman** [comment]
@ssachdevatwist This is expected, since you have configured timeout of 3000 for the whole test that includes not only the click, but also a lot of actions. We recommend to avoid setting action-specific timeouts and instead rely on the test timeout.

What are you trying to achieve with 3000? We'd like to understand this usecase.

**Comment by ssachdevatwist** [comment]
A use case might be that one of the element takes more than, say 50 seconds to appear, Now just to wait for this button, its not good idea to increase overall test time out, otherwise, playwright will wait for 50 seconds for each element before it throws timeout

**Comment by dgozman** [comment]
@ssachdevatwist Well, if your test waits for a single element for 50 seconds, then it must have the test timeout of at least 50 seconds. Note that you can [configure timeout for each test separately](https://playwright.dev/docs/api/class-test#test-set-timeout), that could help if you are worried about execution time for all other tests.

To summarize:
- Update your default test timeout in the config to something average, like 30 seconds (default).
- Increase timeout for a specific test if that needs 50 seconds with `test.setTimeout()`.
- Optionally pass timeout for an action if you'd like.
