### ISSUE TITLE
[Bug]: Viewport and Device option in the config not resizing the browser width and height

### ISSUE THREAD

**Issue by cheytan86** [microsoft/playwright#7863]
### Playwright version

1.13.0

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium, WebKit

### Other information

Node : v14.15.5

### What happened? / Describe the bug

Using viewport to resize image in the playwright.cofig.ts is not working  and even the device  doesn't open the browser in the resized window when we execute the code.
Refer the config used in the project.

Can you please share the correct config as i referred to the  playwright documentation to run my test using devices

### Code snippet to reproduce your bug

```shell
{
    projects: [
        // "Pixel 4" tests use Chromium browser.
        {
          name: 'Pixel 4',
          use: {
            browserName: 'chromium',
            headless: false,
            ...devices['Pixel 4'],
          },
        }],
    workers: 5,
    timeout: 60000,
    outputDir: 'test-results',
    testMatch: ['src/tests/**.ts'],
    grep: /.*/,
    reporter: [
        ['dot'],
        ['junit', {outputFile: 'test-results/results.xml'}],
]
}
```

**Comment by dgozman** [comment]
@cheytan86 This config works for me and produces a mobile-like viewport in Chromium. Could you please share more details? What do you expect to happen? When you say "even the device doesn't open the browser in the resized window" - does it mean you see no browser windows at all? Could you please paste your whole config file as well as the test file?

**Comment by mxschmitt** [comment]
Closing since the issue seems stale. Please reopen / create a new issue if you still encounter unexpected behaviour.
