### ISSUE TITLE
[Bug]: Source code doesn't displayed in source tab in trace viewer when running tests in jenkins

### ISSUE THREAD

**Issue by hananmalka** [microsoft/playwright#7864]
### Playwright version

1.12

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium

### Other information

Node.js version: 12.22

### What happened? / Describe the bug

We are running our tests on jenkins. 
When opening trace-viewer, nothing is shown under the "source" section, but the stacktrace. 
<img width="308" alt="Screen Shot 2021-07-27 at 21 00 52" src="https://user-images.githubusercontent.com/14985481/127204724-64f65900-7128-4d22-be60-386edb94d882.png">

**Comment by dgozman** [comment]
@hananmalka This is because source code in Jenkins is probably in the different location that on your local computer. We don't have a way to configure this yet, but we should in the future.

**Comment by hananmalka** [comment]
Thanks @dgozman 
What do you mean different place? The repo structure is the same as on my local computer. 
Does the source code loaded to the source section just when executing the show-trace command?
Isn't it kept in the ZIP file?

**Comment by dgozman** [comment]
@hananmalka You are right, source code currently is not in the zip file.

**Comment by hananmalka** [comment]
Thanks
