### ISSUE TITLE
[Question]: Installation clarification

### ISSUE THREAD

**Issue by BlazerYoo** [microsoft/playwright#7868]
### Your question

Since installing Playwright installs binaries for Chromium, Firefox and Webkit, I do not need to install any browser binaries separately, right?

**Comment by dgozman** [comment]
That's true for `playwright` but not `@playwright/test`. We have it covered in the docs for [`@playwright/test`](https://playwright.dev/docs/intro#installation) and [`playwright`](https://playwright.dev/docs/library#usage) respectively.
