### ISSUE TITLE
[Question] Proxy with webkit

### ISSUE THREAD

**Issue by Raidus** [microsoft/playwright#787]
Hey,

I can launch a chromium instance using a proxy by adding `--proxy-server=protocoll://IP:PORT` to the launch args.

How can I specify a proxy in webkit?

Best
Wilhelm

**Comment by yury-s** [comment]
On Linux you can pass `--proxy=<default_proxy_uri>` as launcher argument. This will apply to the default context only at the moment. More work needs to be done to support it on the other platforms. We'll have a look into this.

**Comment by Raidus** [comment]
ah ok thanks @yury-s! i have tried this argument but didn't work on my mac. I'll try it on linux. Would be great to see this on mac os working :-)

**Comment by aslushnikov** [comment]
We'll probably need to have a cross-browser proxy support with launch args. Merging as #810; feel free to upvote it :)

**Comment by MeiK2333** [comment]
On the Linux platform, webkit respects `http_proxy` settings, so you can set the proxy by setting env.

```node
const pw = require('playwright');

(async () => {
  const proxy = 'http://127.0.0.1:7890';
  const browser = await pw.webkit.launch({
    headless: false,
    env: {
      ...process.env,
      http_proxy: proxy,
      https_proxy: proxy,
      ftp_proxy: proxy,
      all_proxy: proxy
    }
  });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://httpbin.org/get');
  await browser.close();
})();
```

**Comment by MeiK2333** [comment]
On the macOS platform, webkit uses system proxy settings, which you can view with the `scutil --proxy` command.

**Comment by imartinflores** [comment]
Can this be used from a playwright.config file with webkit ? I am still seeing the modal with Proxy HTTP error when running webkit and setting a proxy.


```
name: 'ios',
      use: {
        headless: false,
        ...devices['iPhone 12'],
        launchOptions:{
          proxy: {
            server: `myProxy`,
            username: 'myuser',
            password: 'mypassword'
          },
        },
```
