### ISSUE TITLE
[Feature]: Unique context in a test suite with describe().

### ISSUE THREAD

**Issue by JuanCruzTrinidad** [microsoft/playwright#7881]
### Unique context in a test suite with describe().

We are working with the jest-playwright preset (v 1.6.0) and we are analyzing the migration to playwright's own runner. The tests we develop usually navigate a unique page per test file (describe()), and each test() searches for selectors or count HTML elements. 
Currently, the tool allows us to use the same page and context in all the describe(). Because each test() doesn't affect the others (only looks for elements), opening a new browser per test() is useless.
We tried to replicate this with playwright runner, version 1.13, but it was notpossible. We assume this happens due to the concept of fixture, where each test runs in a completely separate context from the previous one.

**Comment by radekBednarik** [comment]
Hi, I had similar issue. Currently, You can write you own context and page fixtures with worker scope. That way the tests in the spec file will stay within one context and page and there will be no redundant opening and closing of the context for each test.

**Comment by vsravuri** [comment]
@radekBednarik Could you please share code snippet how you did it ?

**Comment by radekBednarik** [comment]
@vsravuri sure, here it is:

- please note, that you cannot use `context` and `page` for context and page fixture names, those are already reserved for these native fixtures in test scope and you would get an error
- if you are using `playwright.config.js` file, than options for `context` will not apply to your custom context. You have to specify them again - see the link to the issue related to that in the snippet below
- and you will then use you custom fixtures in the `test()` function instead the native ones

```
const { test: base } = require("@playwright/test");

/** Exports extended test object */
module.exports = base.extend({
  // see: https://github.com/microsoft/playwright/issues/7267#issuecomment-875821371
  wContextOptions: [{}, { scope: "worker" }],
  wContext: [
    async ({ browser, wContextOptions }, use) => {
      const wContext = await browser.newContext(wContextOptions);
      await use(wContext);
    },
    { scope: "worker", auto: true },
  ],
  wPage: [
    async ({ wContext }, use) => {
      const wPage = await wContext.newPage();
      await use(wPage);
    },
    { scope: "worker", auto: true },
  ],
});
```

**Comment by vsravuri** [comment]
@radekBednarik Thank you very much!

**Comment by Arun8295524** [comment]
Thanks alot

**Comment by mxschmitt** [comment]
Closing since the issue seems answered https://github.com/microsoft/playwright/issues/7881#issuecomment-888799627. Thanks to @radekBednarik. See here for docs: https://playwright.dev/docs/test-fixtures#worker-fixtures
