### ISSUE TITLE
[Question]: Is it expected that failing tests close the Page?

### ISSUE THREAD

**Issue by VincentDondain** [microsoft/playwright#7882]
### Your question

I'm using "@playwright/test": "^1.13.0", and if any of the tests fails it closes the Page (therefore subsequent tests relying on the Page do not work). That behavior seems different than jest-playwright.

I have a `test.describe` where I have all my tests and inside that `describe` I start with a:

```
let page: Page

test.beforeAll(async () => {
  const context = await (await chromium.launch()).newContext();
  page = await context.newPage();
});
```

I do not have any `page.close();`

**Comment by VincentDondain** [comment]
Precisely this comment: https://github.com/microsoft/playwright/issues/7857#issuecomment-889137809

> However the problem is that if any test fails the page closes (even though it's a test.afterAll which shouldn't run after each test...).

**Comment by mxschmitt** [comment]
Currently it is unfortunately expected, because when a testing is failing a new worker gets assigned it. We will probably release with 1.14 another way of declaring these sub-tests which share a page instance, see here for a sneak peak: https://github.com/microsoft/playwright/pull/7956/files#diff-650126980bbc9d8dedd2889375096a0ed85b98b5c17ae62df6588a5a4ff3a546

let me know if this would work for you (a single test but separating it into multiple steps). If then a test will fail, the whole test will stop.

**Comment by VincentDondain** [comment]
> If then a test will fail, the whole test will stop.

I assume you meant: "the whole test will *not* stop" (;

I guess having 1 super large test and many steps would work though I'm curious how the results are displayed in the terminal/logs and if the reporter works properly (are the tests results displayed properly in the test tab of Azure DevOps for instance).

**Comment by vsravuri** [comment]
I used the Playwright@next build to test sub-test. Here is my code. I noticed the first test case failed in 'Test Step1', new worker is created. Not sure if i am missing something about the expectation @mxschmitt 

```javascript
const { test, expect } = require('@playwright/test');

test('basic test1', async ({ page }) => {
    await page.goto('https://playwright.dev/');
    await test.step('Test Step1', async () => {
        const name = await page.innerText('.navbar__title');
        expect(name).toBe('Playwright1');
    });
});

test('basic test2', async ({ page }) => {
    await page.goto('https://playwright.dev/');
    await test.step('Test Step2', async () => {
        const name = await page.innerText('.navbar__title');
        expect(name).toBe('Playwright');
    });
});
```

**Comment by aslushnikov** [comment]
> That behavior seems different than jest-playwright.

@VincentDondain This is right. @playwright/test by default is different than jest-playwright in this regard. 

However! In our upcoming release, 1.14, a new feature will be released - `describe.serial`, that mimics jest-playwright behavior. Stay tuned!

**Comment by mxschmitt** [comment]
Closing since 1.14 is released, see here for the serial feature: https://playwright.dev/docs/api/class-test#test-describe-serial
