### ISSUE TITLE
[Bug]: browsers fail to install: 'mkdir' command fails

### ISSUE THREAD

**Issue by RobbieS82** [microsoft/playwright#7884]
### Playwright version

1.13.0 on Node v10.16.2

### Operating system

Windows

### Other information

Documentation on GitHub and https://playwright.dev/docs/intro#installation indicate the command 'npx playwright install' will install browsers; however, that command fails with the following:

"Failed to install browsers
TypeError: Cannot read property 'mkdir' of undefined"
![mkdir failed](https://user-images.githubusercontent.com/71034808/127339791-3aa6dffd-d7f0-4721-a80e-5289c91cfd13.png)

### What happened? / Describe the bug

I expected to see an installation process kick off that downloaded the browser binaries and installed them.

**Comment by mxschmitt** [comment]
Which version of Node.js are you using? `node --version`

**Comment by RobbieS82** [comment]
Updated the bug report with my node version, which is v10.16.2
