### ISSUE TITLE
[Bug]: No attachments in junit report

### ISSUE THREAD

**Issue by Daemos87** [microsoft/playwright#7887]
### Playwright version

1.13.0

### Operating system

MacOS

### Other information

node version 14.6

### What happened? / Describe the bug

As discussed on the slack channel ( https://playwright.slack.com/archives/C01AG7QGW2F/p1627460935345900) seems that using the reporter api does not work with junit report, the attachment field is missing. It seems to work with the json reporter instead.

To reproduce  the issue just clone this [repo,](https://github.com/Daemos87/reporter-api) then npm install, npm test. A junit and a json report will be created, the former without attachments.

**Comment by dgozman** [comment]
@Daemos87 How do you consume junit report?

As far as I know, there is no attachment support in junit xml output that is standard. The most common way I see is the Jenkins junit attachments in the form of `[[ATTACHMENT|<absolute file name>]]` somewhere. We can add this line to, say, stdout section, but it does ultimately depend on how the xml file is consumed.

**Comment by Daemos87** [comment]
@dgozman I'm consuming junit report with gitlab CI, here's some docs 

https://docs.gitlab.com/ee/ci/unit_test_reports.html#viewing-junit-screenshots-on-gitlab

It seems to have the same syntax as jenkins
