### ISSUE TITLE
[Question]: WebStorm / VSCode Editor not detecting page object methods while typing

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#7890]
### Your question

I used the JS code snippet provided here https://playwright.dev/docs/test-fixtures to create page objects using  WebStorm and VSCode Editor. Noticed while typing the page object methods are not detected.

```Javascript
// todo-page.js

exports.TodoPage = class TodoPage {

    /**   * @param {import('playwright').Page} page    */

    constructor(page) {
        this.page = page;
    }

    async goto() {
        await this.page.goto('https://playwright.dev');
    }

    async toc() {
        const text = await this.page.innerText('article ul');
        return text.split('\n').filter(line => !!line);
    }

    async getStarted() {
        await this.page.click('text=Get started');
        await this.page.waitForSelector(`text=Core concepts`);
    }

    async coreConcepts() {
        await this.getStarted();
        await this.page.click('text=Core concepts');
        await this.page.waitForSelector(`h1:has-text("Core concepts")`);

    }}
```

```Javascript
// todo.spec.js

const base = require('@playwright/test');
const { TodoPage } = require('./todo-page');

// Extend basic test by providing a "todoPage" fixture.

const test = base.test.extend({
    todoPage: async ({ page }, use) => {
        const todoPage = new TodoPage(page);
        await todoPage.goto();
        await use(todoPage);
        },
});

test('should add an item', async ({ todoPage }) => {

    await todoPage.

});

```
After typing **todoPage.**, editor is not suggesting the methods in TodoPage class. Editor is detecting the methods only if i add this line within the test case itself.
```Javascript
const todoPage = new TodoPage(page);
```

Appreciate if you could provide any solution to overcome this issue as i have to manually type the methods in every test case.

**Comment by mxschmitt** [comment]
The reason for that you don't have auto-completion inside your TodoPage is that your constructor JSDoc annotation is broken, it should be the following:

```
  /**   
   * @param {import('playwright').Page} page
   */
  constructor(page) {
      this.page = page;
  }
```

To have custom fixtures with normal JavaScript and type-checking support, it would end up probably being non-trivial. I would recommend to use TypeScript. which works out of the box with the test-runner and is the recommended approach of writing tests with Playwright Test.

**Comment by dgozman** [comment]
As @mxschmitt points out, type checking with custom fixtures in plain JavaScript does not work. Please use TypeScript if you'd like out of the box typings.

One workaround for you that could work if you export `TodoPage` in the way VSCode understands it:
```js
test('should add an item', async ({ todoPage: todoPageHelper }) => {
    /** @type {import('./todo-page').TodoPage} */
    const todoPage = todoPageHelper;
});
```

**Comment by ahobson** [comment]
In case anyone else stumbles across this issue, I found something that seems to work for me

```javascript
// @ts-check
const base = require('@playwright/test');

class TodoPage {
  /**
   * Create a TodoPage.
   * @param {base.Page} page
   */
  constructor(page) {
    this.page = page;
  }
}

/**
 * @typedef {object} TodoPageTestArgs - todo page test args
 * @property {TodoPage} todoPage     - todo page
 */
/** @type {base.Fixtures<TodoPageTestArgs, {}, base.PlaywrightTestArgs, base.PlaywrightWorkerArgs>} */
const todoFixtures = {
  todoPage: async ({ page }, use) => {
    const adminPage = new TodoPage(page);
    await use(todoPage);
  },
};

exports.test = base.test.extend(todoFixtures);
```

**Comment by EvidentlyCube** [comment]
It would be amazing if we could have this codified somewhere in PW's documentation, because I've been looking for a solution to this problem for a few days using google and (the very unhelpful) Chat GPT, until it struck me to just search github issues for it.
