### ISSUE TITLE
[Question]: Testing for the presence of the HTML hidden attribute

### ISSUE THREAD

**Issue by ollicle** [microsoft/playwright#7899]
I’m attempting to test for the presence/absence of the `hidden` attribute (that the code I am testing ought to remove):
```
<button hidden>…</button>
```

I have tried:
```
const { test, expect } = require('@playwright/test');
test('button is initially unhidden', async ({ page }) => {
	await page.goto('/examples/initially-hidden/');
	const isHidden = page.$eval('button', e => e.hidden);
	expect(isHidden).toBe(false);
});
```

and:
```
const { test, expect } = require('@playwright/test');
test('button is initially unhidden', async ({ page }) => {
	await page.goto('/examples/initially-hidden/');
	const button = await page.$('button');
	const isHidden = button.getProperty('hidden');
	expect(isHidden).toBe(false);
});
```

In both cases `isHidden` returns `{}` when the hidden attribute is absent.

An alternative approach that occurs to me is to attempt to find a hidden button with a CSS selector, e.g.:
`'button[hidden]'` 

Is there a better approach to this? 

I’m new to playwright (and front end testing!) so any pointers are very welcome.

🙏

**Comment by mxschmitt** [comment]
`const isHidden = await page.$eval('button', e => e.hidden);` in general is the right approach, but in your example you missed an `await` so the returned value is always [Truthy](https://developer.mozilla.org/en-US/docs/Glossary/Truthy).

**Comment by ollicle** [comment]
Can confirm that adding the missing `async` worked:
```
const { test, expect } = require('@playwright/test');
test('button is initially unhidden', async ({ page }) => {
	await page.goto('/examples/initially-hidden/');
	const isHidden = page.$eval('button', async e => e.hidden);
	expect(isHidden).toBe(false);
});
```
Thank-you @mxschmitt !
