### ISSUE TITLE
[Feature]: Expose API of native reporters

### ISSUE THREAD

**Issue by radekBednarik** [microsoft/playwright#7900]
### Feature request

From https://playwright.slack.com/archives/CSUHZPVLM/p1627457401116800 as requested by @dgozman 

When playing with experimental allure reporter I got an idea - often times, when test fail, I want to log additional output to the console. Your allure reporter handles is as it should be and add the `console.log()` under `stdout` label from the given test case to the report under the correct test case.

However, playwright's native reporters do not handle this and if multiple tests fails, then due to parallel execution the `console.log()` output of the failed test cases get printed out all over the place.

Would it be possible to either let native reported handle custom stdouts correctly or create some public api, so I can print some additional info to the console via native reporter myself?

**Comment by dgozman** [comment]
> Would it be possible to either let native reported handle custom stdouts correctly...

What do you mean by correctly? How should it look like in the terminal? Any specific ideas for improving this are welcome!

**Comment by radekBednarik** [comment]
@dgozman hello, I will try to illustrate via screenshots, hopefully it will help. Sorry for sloppy highlighting - doing that on notebook touchpad ;)

In this example I am using native "list" reporter. There are several tests which will fail. In the case of failure, I am using `console.log()` to output additional info, which helps with debugging.

In the first screenshot, you will see, that the `console.log()` output to the console gets split because due to parallel execution (red highlight). The actual failed test is highlighted by blue.

In the second screenshot the failed test with stderr output is highlited by blue. Ideally here I would like to have my custom console.log() output.

*Screenshot 1*
![Snímek z 2021-07-29 18-03-01](https://user-images.githubusercontent.com/64590001/127528248-a2072625-8435-4693-9cf3-fecb78a8c065.png)

*Screenshot 2*
![Snímek z 2021-07-29 18-11-00](https://user-images.githubusercontent.com/64590001/127528305-57db61f3-6ddb-4915-84dc-3ed136dfacd6.png)

**Comment by dgozman** [comment]
@radekBednarik Thank you for more details, this makes sense, we'll look into this.

**Comment by dgozman** [comment]
#8150 introduced test output for failures in v1.14. Let us know if that does not work for some reason.
