### ISSUE TITLE
[Bug]: Error: read ECONNRESET during installation

### ISSUE THREAD

**Issue by FelixMW-CM** [microsoft/playwright#7904]
### Playwright version

1.13.0

### Operating system

Linux

### Other information

NodeJS version: 16.5.0
npx version: 7.20.2
Linux Distro: centOS 8.4.2105

The system is a workplace Virtual Machine, with the necessary proxy information added in the env HTTPS_PROXY (as well as https_proxy, for good measure).

### What happened? / Describe the bug

When trying to run `npx playwright install`, after only a few seconds the process errors out, with the following output:
```
Error: Failed to download chromium v901522, caused by
Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:211:20)
```

Does anyone have any ideas what could cause this? Alternatively, do you know how / where I could find more logging information about this?

**Comment by dgozman** [comment]
@FelixMW-CM Seems like a sporadic network failure. Does this happen regularly/sometimes/often/just once?

**Comment by FelixMW-CM** [comment]
> @FelixMW-CM Seems like a sporadic network failure. Does this happen regularly/sometimes/often/just once?

Nope, it happens every single time I tried.

**Comment by dgozman** [comment]
@FelixMW-CM Interesting! If you run with `DEBUG=pw:install` environment variable, there might be some clue. Sorry I missed that the first time.

**Comment by FelixMW-CM** [comment]
> @FelixMW-CM Interesting! If you run with `DEBUG=pw:install` environment variable, there might be some clue. Sorry I missed that the first time.

Running it with the DEBUG env gives this output:
```
npm ERR! 2021-07-30T20:37:43.186Z pw:install downloading Playwright build of chromium v901522 - attempt #1
npm ERR! 2021-07-30T20:37:43.187Z pw:install running download:
npm ERR! 2021-07-30T20:37:43.187Z pw:install -- from url: https://playwright.azureedge.net/builds/chromium/901522/chromium-linux.zip
npm ERR! 2021-07-30T20:37:43.187Z pw:install -- to location: /tmp/playwright-download-chromium-ubuntu20.04-901522.zip
npm ERR! 2021-07-30T20:37:43.246Z pw:install attempt #1 - ERROR: read ECONNRESET
npm ERR! 2021-07-30T20:37:43.246Z pw:install sleeping 469.06073477514053ms before retry...
npm ERR! 2021-07-30T20:37:43.717Z pw:install downloading Playwright build of chromium v901522 - attempt #2
npm ERR! 2021-07-30T20:37:43.717Z pw:install running download:
npm ERR! 2021-07-30T20:37:43.717Z pw:install -- from url: https://playwright.azureedge.net/builds/chromium/901522/chromium-linux.zip
npm ERR! 2021-07-30T20:37:43.717Z pw:install -- to location: /tmp/playwright-download-chromium-ubuntu20.04-901522.zip
npm ERR! 2021-07-30T20:37:43.747Z pw:install attempt #2 - ERROR: read ECONNRESET
npm ERR! 2021-07-30T20:37:43.747Z pw:install sleeping 690.1081949841528ms before retry...
npm ERR! 2021-07-30T20:37:44.439Z pw:install downloading Playwright build of chromium v901522 - attempt #3
npm ERR! 2021-07-30T20:37:44.439Z pw:install running download:
npm ERR! 2021-07-30T20:37:44.439Z pw:install -- from url: https://playwright.azureedge.net/builds/chromium/901522/chromium-linux.zip
npm ERR! 2021-07-30T20:37:44.439Z pw:install -- to location: /tmp/playwright-download-chromium-ubuntu20.04-901522.zip
npm ERR! 2021-07-30T20:37:44.466Z pw:install attempt #3 - ERROR: read ECONNRESET
npm ERR! 2021-07-30T20:37:44.466Z pw:install FAILED installation Playwright build of chromium v901522 with error: Error: read ECONNRESET
npm ERR! (node:2938992) UnhandledPromiseRejectionWarning: Error: Failed to download chromium v901522, caused by
npm ERR! Error: read ECONNRESET
npm ERR!     at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
npm ERR!     at /usr/local/lib/python3.9/site-packages/Browser/wrapper/node_modules/playwright/lib/utils/registry.js:551:13
npm ERR!     at async Registry._downloadExecutable (/usr/local/lib/python3.9/site-packages/Browser/wrapper/node_modules/playwright/lib/utils/registry.js:550:5)
npm ERR!     at async Registry.install (/usr/local/lib/python3.9/site-packages/Browser/wrapper/node_modules/playwright/lib/utils/registry.js:537:34)
npm ERR!     at async installDefaultBrowsersForNpmInstall (/usr/local/lib/python3.9/site-packages/Browser/wrapper/node_modules/playwright/lib/utils/registry.js:664:3)
```

**Comment by dgozman** [comment]
cc @aslushnikov

**Comment by aslushnikov** [comment]
@FelixMW-CM can you try `curl`'ing it from `https://playwright.azureedge.net/builds/chromium/901522/chromium-linux.zip`?


```sh
$ curl -o cr.zip  https://playwright.azureedge.net/builds/chromium/901522/chromium-linux.zip
```

**Comment by FelixMW-CM** [comment]
(Apparently, I had forgotten to press Comment when writing this one, so I had assumed I had already replied. Whoops...)

> @FelixMW-CM Seems like a sporadic network failure. Does this happen regularly/sometimes/often/just once?

Nope, it happens every single time I tried.

**Comment by FelixMW-CM** [comment]
> @FelixMW-CM can you try `curl`'ing it from `https://playwright.azureedge.net/builds/chromium/901522/chromium-linux.zip`?
> 
> ```shell
> $ curl -v -o cr.zip https://playwright.azureedge.net/builds/chromium/901522/chromium-linux.zip
> ```

This gives me the following error:
```
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 172.31.105.20:9090 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 172.31.105.20:9090 
```

Curiously, using wget to get the file works without a problem.


By now, I'm convinced that the incompatibility lies with centOS: I tried using localhost as an artifact repository (serving the files in the correct location via python), and while it worked without a problem on Ubuntu, centOS gave me the very same error as when trying to download it from azure.

**Comment by aslushnikov** [comment]
@FelixMW-CM Oh, you're on CentOS! It definitely might be. We don't run any tests on centOS and don't support it officially, so things might be off there.

I'll close this bug then! Thank you for posting your reply here.
