### ISSUE TITLE
[Bug]: Playwright Test is not support tsconfig.json paths resolution

### ISSUE THREAD

**Issue by dartyuhov** [microsoft/playwright#7911]
### Playwright version

1.13.0

### What happened? / Describe the bug

Hello, I've noticed that if you have a project that has been configured with custom paths aliases ([link to typescript doc](https://www.typescriptlang.org/docs/handbook/module-resolution.html)), playwright-test won't work.

Probably, this is an issue of folio framework, that is being used by playwright-test

### Code snippet to reproduce your bug

```shell
tsconfig.json:

{
  "compilerOptions": {
    "target": "ESNext",
    "module": "commonjs",
    "strict": true,
    "esModuleInterop": true,
    "baseUrl": ".",
    "paths": {
        "@pages/*": ["pageobjects/*"],
    }
  }
}
```
some.test.ts:
```
import { test as base, expect } from '@playwright/test';
import { PlaywrightDevPage } from '@pages/mypage';

test('basic test', async ({ page }) => {
  page.goto('https://playwright.dev');
  const name = await page.title();
  expect(name).toBe('Fast and reliable end-to-end testing for modern web apps | Playwright');
});


```
run command:
```
npx playwright test
```

### Relevant log output

```shell
Error: Cannot find module '@pages/mypage'
Require stack:
- ../test/some.test.ts
```

**Comment by mxschmitt** [comment]
Closing and folding into #7121 since Playwright Test does not consider the tsconfig for TypeScript.
