### ISSUE TITLE
[Bug]: Tests are not running for `.tsx` file type in `@playwright/test`

### ISSUE THREAD

**Issue by saikat-samanta** [microsoft/playwright#7913]
### Playwright version

1.13.0

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium

### Other information

Node version: 16.5.0,
Linux distribution: Arch Linux

### What happened? / Describe the bug

Tests are only running for `.ts` but ignored for `.tsx` file type in `@playwright/test`.

My playwright config file:
```js
// playwright.config.js
const config = {
  testMatch: [".*.e2e.{ts,tsx}"],
  use: {
    headless: false,
    viewport: { width: 1280, height: 720 },
    ignoreHTTPSErrors: true,
  },
  globalSetup: require.resolve("./global-setup"),
};

module.exports = config;
```
Similar issues are here microsoft/playwright#7121

**Comment by mxschmitt** [comment]
TSX is currently not supported, I'm folding it into #7121 for custom tsconfig/babel support and #7148 for making component testing possible.
