### ISSUE TITLE
[Bug]: Hero image is not rendered in Trace viewer snapshot (mobile devices)

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#7917]
### Playwright version

1.13.0

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium, WebKit

### What happened? / Describe the bug

The hero image is not rendered in Trace viewer snapshot window. It is displayed as broken. The issue is only observed for mobile.

Also, the images screenshot strip is zoomed in. 

![Screen Shot 2021-07-29 at 12 47 57 PM](https://user-images.githubusercontent.com/22205721/127556624-049b8a5b-1578-4409-8666-c53f5e49a26e.png)

Shared the trace file privately with @pavelfeldman for further investigation

**Comment by pavelfeldman** [comment]
That's the same as the original Mac issue: https://github.com/microsoft/playwright/issues/6980. You can work around it temporarily via setting [deviceScaleFactor](https://playwright.dev/docs/api/class-fixtures#fixtures-device-scale-factor) to 1. (Mobile devices set it to 2-3).
