### ISSUE TITLE
[Feature]: Enable Trace Viewer with ENV variable

### ISSUE THREAD

**Issue by ferrykranenburgcw** [microsoft/playwright#7928]
### Feature request

Currently the trace viewer need to be integrated inside the test code itself. We could integrate it for all tests but this creates a lot of very large *.zip files on the system. It would be better to introduce a ENV variable like `TRACE=1` that starts the test, automatically generates a trace file and opens it up after test has been run. This way we can easily and quickly use the trace viewer from within the IDE.

**Comment by uchagani** [comment]
I've done something similar where I check if an environment variable is set before running the code that starts the trace.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
