### ISSUE TITLE
[Bug]: Windows defender real time protection lock files

### ISSUE THREAD

**Issue by sytolk** [microsoft/playwright#7929]
### Playwright version

"playwright": "^1.12.3"

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

Im testing with playwright Electron app: https://playwright.dev/docs/api/class-electron/

### What happened? / Describe the bug

My operationg system is Windows 10 and I dont have this issue on other platforms. When I start tests it somethimes succeeded but somethimes hangs with timeout error on all fs-extra functions like fs.lstat() .fs.readFile() fs.readdir()

This happened on the first test only. I have set my project folder in windows defender exceptions but without success. But if I stop real time protection of the windows defender the problem not exist anymore..

I'm writing the issue here why this happened only on testing environment. The application works without this fs issue on windows: https://github.com/tagspaces/tagspaces

### Code snippet to reproduce your bug

```shell
import fs from 'fs-extra';

const promise = new Promise(resolve => {
      fs.lstat(path, (err, stats) => {
        if (err) {
          resolve(false);
          return;
        }

        if (stats) {
        //...
        }
      });
    });

// Create a promise that rejects in <ms> milliseconds
  timeout = (ms: number): Promise<any> =>
    new Promise((resolve, reject) => {
      const id = setTimeout(() => {
        clearTimeout(id);
        reject(new Error('Timed out in ' + ms + 'ms.'));
      }, ms);
    });

    // Returns a race between our timeout and the passed in promise
    return Promise.race([promise, this.timeout(1000)]);
```

### Relevant log output
```
  console.log
    Error loading meta of:C:\Users\smari\IdeaProjects\tagspaces\tests\testdata-tmp\file-structure\supported-filestypes Error: Timed out in 2000ms.

      at Page.emit (node:events:394:28)

  console.log
    Error loading directory: Error: Timed out in 2000ms.

      at Page.emit (node:events:394:28)
```

**Comment by dgozman** [comment]
@sytolk I am not sure Playwright can do anything here. It looks like some code using `fs` does not play nicely with Windows defender, but how is Playwright involved?

Please comment if I misunderstood, and I will reopen the issue.

**Comment by sytolk** [comment]
The reason to open this issue is: this happens in testing environment but the reason for this is different (it appears that path from the testing folder was wrong) it strange that tests succeeded somethimes..
