### ISSUE TITLE
[Question]: page.hover is not working as per the expectation.

### ISSUE THREAD

**Issue by shiv-jirwankar** [microsoft/playwright#7930]
### Your question

I am trying to hover to an element with text 'Reporting' using page.hover() method. However, I have noticed hover() is waiting for another element with tag <div> to get visible and stable. I am not sure why it is happening. 

Here's the log:

page.hover: Timeout 30000ms exceeded.
       =========================== logs ===========================
       waiting for selector "//div[text()='Reporting']//ancestor::a"
         selector resolved to visible <a href="/g/reporting" class="jss100 jss95">…</a>
       attempting hover action
         waiting for element to be visible and stable
         element is visible and stable
         scrolling into view if needed
         done scrolling
         checking that element receives pointer events at (431.41,251)
         `<div aria-hidden="true"></div> from <div role="presentation" class="MuiPopover-root jss27">…</div>` subtree intercepts pointer events      
       retrying hover action, attempt #1
         waiting for element to be visible and stable
         element is visible and stable
         scrolling into view if needed
         done scrolling
         checking that element receives pointer events at (431.41,251)
         `<div aria-hidden="true"></div> from <div role="presentation" class="MuiPopover-root jss27">…</div>` subtree intercepts pointer events      
       retrying hover action, attempt #2

**Comment by dgozman** [comment]
@shiv-jirwankar `selector resolved to visible …` line shows which element will be hovered. That should be something with `Reporting` text as I understand. However, later on Playwright tells you that `MuiPopover-root` blocks the target element (most likely this is a popover that lays above the 'Repporting'), so Playwright cannot hover it.
