### ISSUE TITLE
npx playwright show-trace trace.zip shows Blank screen with no errors or exception on terminal

### ISSUE THREAD

**Issue by baleshkoijam** [microsoft/playwright#7932]
### Playwright version

1.13.1

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium

### Other information

node.js : 6.14.12
Here is my entry of the package.json:

{
  "name": "Temp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "playwright": "^1.13.1"
  }
}

### What happened? / Describe the bug

i can see the trace.zip file generated with 304 bytes size, when tried to open it using the command "npx playwright show-trace trace.zip" it show the traceview screen with no details on it ( all blank white, refer the screen shot below).

![image](https://user-images.githubusercontent.com/46170480/127669803-6a5f09a0-87a8-4ef5-8a22-507209e4fd18.png)

### Code snippet to reproduce your bug

```shell
const {chromium} = require('playwright');

(async() => {
    const browser = await chromium.launch({headless:false})

    const context = await browser.newContext();

    await context.tracing.start({ screenshots: true, snapshots: true });

    const page = await browser.newPage()


     await page.goto('https://docs.datadoghq.com/api/latest/');
     await page.pause()

await context.tracing.stop({ path: 'trace.zip' });
await browser.close()

}) ()
```

**Comment by mxschmitt** [comment]
The reason for that is that `browser.newPage()` will create a new independent browser context for you. So you then have two contexts which don't know each other. On one tracing enabled, but you are not using it and another one where you actually navigate to datadoghq.com.

To fix it use `context.newPage()` instead of `browser.newPage()`. This will result in 1 context and 1 page.

**Comment by baleshkoijam** [comment]
@mxschmitt,
Thank you for this feedback. silly mistake from my end. i can see now the details are being displayed. closing the issue.
thanks once again.

**Comment by slott56** [comment]
I think this needs to be a much more prominent note in the documentation pages.
https://playwright.dev/python/docs/trace-viewer#recording-a-trace for example
