### ISSUE TITLE
[Bug]: Invalid association browserWindow / window for electron target

### ISSUE THREAD

**Issue by ggreco** [microsoft/playwright#7933]
### Playwright version

1.13.1

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium

### Other information

Node version is 14.17.3, Electron 13.1.x, macOS 10.15

### What happened? / Describe the bug

If you have multiple windows created in your main electron script the order you get them with `app.windows()` is random (and this is ok). But if you try to get the "BrowserWindow" object associated to a given window with `app.browserWindow(window)` the association is often wrong.

### Code snippet to reproduce your bug

If you have multiple windows created in your main electron script the order you get them with:

`app.windows()`

 is random (and this is ok).

The problem is that when you try to get the "BrowserWindow" object of a given window with:

`app.browserWindow(window)`

The association is often wrong.

If I have a window hidden and one visible (with #visible in the loading URL) the following test will fail about 50% of times (also if url dumps the correct window):

```javascript
const windows = app.windows();
expect(windows.length).equals(2);
for (const win of windows) {
  const url = win.url();
  if (!url.contains("visible"))
     continue;
  let browserWindow = await app.browserWindow(win);
  expect(await browserWindow.evaluate((b) => {
      return b.isVisible();
  })).equals(true);
}
```

The BrowserWindow associated to the Page object is wrong, but the Page itself is correct, and I can test this because If I expose the remote module in window in the renderer and change the last expect to:

```javascript
  expect(await win.evaluate(() => {
      return window.remote.getCurrentWindow().isVisible();
  })).equals(true);
```
 
... the test works 100% of times.

If needed I will try to put on github a complete example, but I think the bug is trivial, I looked also a bit at the sources to fix it myself but I get lost on the channel stuff!

### Relevant log output

[THIS IS THE POINT WHERE WE CALL FOR BROWSERWINDOW]
```shell
pw:api => electronApplication.browserWindow started +2ms
  pw:api <= electronApplication.browserWindow succeeded +1ms
  pw:api => page.evaluate started +1ms
  pw:api <= page.evaluate succeeded +2ms
  pw:api   "networkidle" event fired +18ms
  pw:api => jSHandle.evaluate started +1s
  pw:api <= jSHandle.evaluate succeeded +1ms
```
[THE TEST FAILS HERE]

**Comment by pavelfeldman** [comment]
Looks like the same as https://github.com/microsoft/playwright/issues/6748
