### ISSUE TITLE
Unknown file extension ".ts" when importing ES modules

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#7936]
### Feature request

https://github.com/ychaudhari/playwright-import-issue reproduces the issue. Use Node 14+.

**Comment by aslushnikov** [comment]
Joel's WIP: https://github.com/microsoft/playwright/pull/8046

This was discussed on a meeting, we're fixing it "in docs".
Thus removing ASAP, and moving to 1.15

**Comment by JoelEinbinder** [comment]
Closed via #8046

**Comment by rhysstubbs** [comment]
For anyone that's arriving here from a Google search for an error like `TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts"` then try the following:

In the test file, keep the `.js` extension for the `.ts` file import, e.g. `import { something } from '../../functionality.js`

Rename your test file, e.g. `search.test.js` to `search.test.ts`

You should then find you're able to run the tests without the error
