### ISSUE TITLE
[Feature]: CodeSign chromium by default in macOS big sur

### ISSUE THREAD

**Issue by xuanzhaopeng** [microsoft/playwright#7937]
### Feature request

In macOS big sur , every time I get a popup to allow the Chromium to access network when I execute test.

So I googled a bit that it said it's because of the app is not signed , so I'm doing something like

```
    cd $HOME/Library/Caches/ms-playwright/
    # codesign for chromium in Macos
    for d in chromium-*; do
        echo Sign $HOME/Library/Caches/ms-playwright/${d}/chrome-mac/Chromium.app
        sudo codesign --force --deep --sign - ./${d}/chrome-mac/Chromium.app
    done
```

however is it possible to sign it by default when install add new Chromium inside of $HOME/Library/Caches/ms-playwright?

**Comment by mxschmitt** [comment]
Is your device managed or has special firewall rules from your company?

**Comment by xuanzhaopeng** [comment]
Hey @mxschmitt ,  yep, for WebKit there is no problem, since I haven't check FF, but I will let u know soon.
