### ISSUE TITLE
[Bug]: can't find libyuv during compiling the patched WebKit

### ISSUE THREAD

**Issue by ChijinZ** [microsoft/playwright#7939]
### Playwright version

1.13.1

### Operating system

Linux

### What browsers are you seeing the problem on?

WebKit

### Other information

I run it on Ubuntu 20.04

### What happened? / Describe the bug

I would like to build the patched WebKit from scratch. As suggested by ``browser_patches/README.md``, I run ``./browser_patches/prepare_checkout.sh webkit`` script, and successfully download WebKit source code and apply playwright-required patches to it. However, when I use cmake to compile the patched code, an error shows up:

```
../Source/WebKit/UIProcess/Inspector/Agents/ScreencastEncoder.cpp:33:10: fatal error: 'libyuv.h' file not found
```

It seems that the libyuv dependency is introduced by playwright-required patches. How can I install libyuv?

**Comment by mxschmitt** [comment]
To build browsers, you need to use the custom build.sh script in each directory. See here: https://github.com/microsoft/playwright/blob/master/browser_patches/webkit/build.sh

Let us know if this works for you. Once it's built you can use the `WKPATH` env var to run tests on your built browser.

**Comment by ChijinZ** [comment]
Thanks! It works for me, I can build the patched WebKit successfully. 

One strange thing I faced is that, when I set env var ``WKPATH=/path/to/playwright-1.13.1/browser_patches/webkit/checkout/WebKitBuild/GTK/Release`` and run tests, the launched browser is the default WebKit binary (in ``~/.cache/ms-playwright/webkit-xxxx/``) instead of my specified one. I used ``playwright-python`` to run the tests. The script is as follow:

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.webkit.launch(headless=False)
    page = browser.new_page()
    page.goto("http://playwright.dev")
    print(page.title())
    page.pause()
```

Does the ``playwright-python`` support the ``WKPATH`` env var? Or I should manually move the built WebKit to  ``~/.cache/ms-playwright/webkit-xxxx/``?

**Comment by mxschmitt** [comment]
WKPATH is only supported on the normal Playwright. On the language bindings you need to set the executable path manually when launching the browser.

I'm curious, what are you working on?

**Comment by ChijinZ** [comment]
Thanks! Nothing special, just try to build browsers with customized instrumentation, by which I can collect some dynamic information (e.g. coverage) of the browsers. I think Playwright is a good fit for me to script the browsers to visit some websites. So I'm currently working on bridging Playwright to my built browsers. Any suggestions (or experience) for this task?

**Comment by pavelfeldman** [comment]
Closing as this does not seem to be Playwright related!
