### ISSUE TITLE
[Question]: Is there any way to visit a local html file?

### ISSUE THREAD

**Issue by ntcmp2u** [microsoft/playwright#7943]
### Your question

I notice that ``page.goto()`` takes a URL as argument and can't open a local html file like ``page.goto('~/index.html')``. Is there a method for Page to open a local file?

**Comment by mxschmitt** [comment]
You can use the `file://` protocol to open local files. Example for automatic generated urls:

```js
const path = require("path")
const myFileLink = new URL('file://' + path.join(__dirname, 'assets', 'empty.html')).toString();
console.log(myFileLink)
await page.goto(myFileLink)
```

**Comment by ntcmp2u** [comment]
thanks!
