### ISSUE TITLE
[Question]: Failing Webkit tests in Gitlab pipeline

### ISSUE THREAD

**Issue by wcossio123** [microsoft/playwright#7945]
### Your question

Playwright Version: 1.13.1
Browser: webkit

We're currently using CodeceptJs with Playwright to automate cross-browser testing in a gitlab pipeline. Our gitlab jobs are using the playwright:focal docker image, and we're executing tests on Chromium, Firefox, and Webkit. Our Chromium and Firefox tests are passing consistently, but our Webkit tests are failing randomly.

 After a bit of debugging, it looks like our app is randomly timing out on calls to our API. Occasionally, the webkit tests pass, but fail a majority of the time, and on random pages of our application. Unfortunately, I'm unable to replicate my issue on my local machine (mac). In fact, the tests are passing consistently on my local machine. Is this due to any limitation with webkit running on linux/focal image? Are there any open issues that may relate to the issue I'm seeing?

Additional Details: we're accessing our application through a proxy and running headless

Thanks!

**Comment by wcossio123** [comment]
Additional details: we're accessing our app through a proxy in all three browsers.

**Comment by mxschmitt** [comment]
There should be no limitations, but depends on your web application. All our features are guaranteed to work across all browsers. Including Docker, we run our tests inside Docker too to ensure it works: https://github.com/microsoft/playwright/actions/runs/1079709040

I would recommend to enable tracing on your tests and provide the trace file via an artifact if the test is failing. So you can open it locally and investigate what was going on and why something was timing out. It also includes logs etc.

See here: https://playwright.dev/docs/trace-viewer

And here about GitLab Job Artifacts: https://docs.gitlab.com/ee/ci/pipelines/job_artifacts.html

**Comment by wcossio123** [comment]
@mxschmitt Thanks! i was able to use tracing and video to get a better picture of what is happening in our app in the pipeline. i looks like my assumption is correct. our app is timing out on certain pages. Still not sure why it’s only happening in webkit, and only in our pipeline though.

One thing I wasn't able to see in the trace is the network request that timed out. Will I only see the request if there was a response? or should i be able to see the request even if it timed out?

**Comment by mxschmitt** [comment]
Yes, currently you will only see it in the trace viewer if the response was received. Please create a new issue if you want to see  network failures in the trace-viewer. Closing since the original issue seems solved after debugging the trace with the trace viewer.
