### ISSUE TITLE
[Question]: How to add testInfo.repeatEachIndex into the output test status line of Playwright Test?

### ISSUE THREAD

**Issue by khtan** [microsoft/playwright#7946]
### Your question

Environment : Playwright using typescript on Windows 10 

Scenario: To eliminate unreliable tests in Playwright, I am thinking of using the repeatEach setting in playwright.config.ts 
          so that before checking in my tests, I set it to a high number like 100 and let it run overnight. If it fails,
          I wish to know which repeat number was the last failure.
Bigger scenario:
          Let's say you've inherited many Playwright tests and you wish to qualify them for reliability. One way is to set
          repeatEach to 100 and let all the tests run overnight. In the morning, we can review each test to see at what
          repeatEachIndex did each of the tests fail at, giving us an indication of its reliability.

Problem:
   The current Playwright test run outputs the run status like : 
   >  ok [chromium] › tests\visitPlaywright.spec.ts:21:5 › visitPlaywight visit1 0 (5s)
   > x  1) [chromium] › tests\visitPlaywright.spec.ts:29:5 › visitPlaywight visit1 0 (3s)
where 1 is the first failure.

How can I override or redefine this output line so that the testInfo.repeatEachIndex value is part of the output?

Thanks in advance,

**Comment by pavelfeldman** [comment]
Custom reporter https://playwright.dev/docs/api/class-reporter would give you the most flexibility, it is very easy to write your own. See https://playwright.dev/docs/test-reporters as qell.

**Comment by mxschmitt** [comment]
Closing for now, since the issue seemed stale. Please create a new issue if you still encounter issues.
