### ISSUE TITLE
[Question]: How can we handle browser navigation like clicking back button, forward button of the browser?

### ISSUE THREAD

**Issue by shiv-jirwankar** [microsoft/playwright#7949]
### Your question

How can we handle browser navigation like clicking the back button, forward button of the browser?

**Comment by mxschmitt** [comment]
- [page.goForward([options])](https://playwright.dev/docs/api/class-page#page-go-forward)
- [page.goBack([options])](https://playwright.dev/docs/api/class-page#page-go-back)
- [page.goto(url[, options])](https://playwright.dev/docs/api/class-page#page-goto)
