### ISSUE TITLE
[Question]: Typescript imports

### ISSUE THREAD

**Issue by brtn1234** [microsoft/playwright#7953]
### Your question

My project works fine in js but I need to move to ts. Using an import like this gives an error. 'Node' option is set. Am I missing something?

import { Page } from "playwright";

Cannot find module 'playwright'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?

**Comment by mxschmitt** [comment]
Could you provide us your current tsconfig.json?

**Comment by brtn1234** [comment]
{
"compileOnSave": false,
"compilerOptions": {
  "baseUrl": "src",
  "target": "ES2021", 
  "module": "commonjs",  
  "moduleResolution": "node",  
  "allowJs": true,  
  "checkJs": true, 
  "esModuleInterop": true,   
  }
}

**Comment by mxschmitt** [comment]
This looks more like a jsconfig. Could you provide us the full error - preferable as a screenshot?

**Comment by mxschmitt** [comment]
Normally this should not be needed and `import { Page, BrowserContext } from "playwright";` should work. Would be awesome if you could create a small demo repo so we can take a more detailed look.

What kind of error do you get?

**Comment by mxschmitt** [comment]
Closing since the issue seems stale.
