### ISSUE TITLE
[Question]: UI element IDs keep changing?

### ISSUE THREAD

**Issue by Kangaxx-0** [microsoft/playwright#7955]
### Your question

Hello.

I was new to playwright, and spent some time playing with this amazing framework. I kind of ended up with a very weird behavior - e.g. I have a text field element (out of the box from Fluent UI library), 

I opened up our Azure app service URL in Microsoft Edge, element ID

![image](https://user-images.githubusercontent.com/85712372/127933424-5bfd85f4-ec0a-4425-95b5-ed26e458ca71.png)

In my test code , i set the text field value to "zhang" as below with id = `TextField21`

`await this.page.type("id=TextField21", "zhang");`

![image](https://user-images.githubusercontent.com/85712372/127932203-7a10ac9a-f2d3-4955-a21c-aa11f544626a.png)

However, in the same file, when I trying to retrieve the text filed value with the code below

![image](https://user-images.githubusercontent.com/85712372/127933661-73af9546-2d72-4d9e-a9c1-bed2b56c30d5.png)

![image](https://user-images.githubusercontent.com/85712372/127933572-d5842bf0-d14a-46f4-aeb7-950e5d3faa74.png)

The element could not be found, after inspecting the UI, it turns out ID = 100
![image](https://user-images.githubusercontent.com/85712372/127933790-bbb896b8-b79f-412a-aed8-a9b456edd31f.png)

NOTICE- This ID did not change outside playwright runner browser

I changed the ID to 100 in my code and everything just passed fine.  Last but not the least, I run `npx playwright test` one more time, the test fails again because the id changed to another number.

As you could see, the behavior I was expecting did not match up:
1. I could successfully set a value to text input, but not able to retrieve value with the same ID
2. The ID kept changing in the browser during testing, specifically, when test runner fire up browser.

I would appreciate if anyone could help me to understand what's going on, thanks in advance!

**Comment by pavelfeldman** [comment]
The framework that was used while building this web page assigns random IDs to elements, so you can't rely on them. You should always use the semantics selectors, here it would be either `[aria-labelledby=lastName]` or `[name=lastName]`.

**Comment by Kangaxx-0** [comment]
Thanks for this clarification, it would be better to have it documented somewhere :)
