### ISSUE TITLE
[Bug]: `page.waitForNavigation` has a chance of failure

### ISSUE THREAD

**Issue by suedar** [microsoft/playwright#7959]
### Playwright version

1.13.1

### Operating system

MacOS, Linux

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

I have a page that is running very slow. The page need to perform login on one page and redirect into another page. As I record the page I get this action.
``` js
await Promise.all([
   page.waitForNavigation(/*{ url: 'https://example' }*/),
   page.click('button:has-text("Log In")')
 ]);
```
It seems that `page.waitForNavigation` make the test has a chance of failure. After several times of running `npx playwright test` with the same test code, sometime it run perfectly but sometime it doesn't. After I replace the above code into these which is not including `page.waitForNavigation` , the test run perfectly all the time.

``` js
await page.waitForTimeout(2000);
await page.click('button:has-text("Log In")')
await page.waitForTimeout(2000);
```

Maybe there is something wrong with `page.waitForNavigation` ?

**Comment by mxschmitt** [comment]
What do you mean with "it does not run perfectly"? Would it be possible that you provide us debug logs via setting the env var `DEBUG=pw:api` and/or a trace file, see [here](https://playwright.dev/docs/trace-viewer) how to record one. This would help to us analyse the issue better.

**Comment by aslushnikov** [comment]
Closing here since the discussion has stalled!
