### ISSUE TITLE
[Question]: How to verfiy the background color of webelement after doing click operation on it?

### ISSUE THREAD

**Issue by shiv-jirwankar** [microsoft/playwright#7961]
### Your question

I want to verify the background color of the webelement during the click operation on that element. I tried verifying the background color after clicking on element, but it isn't working the way I wanted as clicking on the element is navigating to the other page.
Then I tried to right-click on the element which is changing the background-color of the element. And then I have added code to verify the background color. 
This seems to be working well most of the time. But I have observed that doing right-click operation highlights the element for a very small duration, and thus the assertion failure happened few times. 
I want the element to be highlighted for a longer duration as soon as I perform right-click on it. I tried with different 'options' available in **page.click()** method like _**clickCount, delay, trial**_ , etc. But nothing seems to be working.

Any way by which we can achieve the requirement?

**Comment by mxschmitt** [comment]
clickCount, and trial are unrelated to this. I tried to come up with an example for your use-case which should work for you:

```js
// @ts-check
const playwright = require('playwright');

(async () => {
  const browser = await playwright.chromium.launch({
    headless: false
  });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.setContent(`
      <style>
        button {
          background-color: green;
        }
        button:active {
          background-color: red; /* This is the same as rgb(255, 0, 0) */
        }
      </style>
      <button>some button</button>
    `)

  const button = await page.waitForSelector("button:text('some button')")
  page.on("console", console.log) // only for debugging
  await Promise.all([
    page.waitForFunction(button => {
      const calculatedBackgroundColor = getComputedStyle(button).backgroundColor;
      console.log(calculatedBackgroundColor) // only for debugging
      return calculatedBackgroundColor === 'rgb(255, 0, 0)'
    }, button),
    button.click({
      delay: 1000
    })
  ])
  await browser.close();
})();
```

- Get the ElementHandle of the element, since we pass it over to [page.waitForFunction](https://playwright.dev/docs/api/class-page#page-wait-for-function).
- Use[ Promise.all](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) which waits until the given function to [page.waitForFunction](https://playwright.dev/docs/api/class-page#page-wait-for-function) is happy and clicks on the button
- We pass [delay](https://playwright.dev/docs/api/class-elementhandle#element-handle-click-option-delay): 1000 to the button click, which will hold the button for 1000ms and then release it
- Inside the function of page.waitForFunction we use [getComputedStyle](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle) to get the actual calculated CSS property of the background color. We return a boolean if the calculated value matches red.

Let me know if this is working for you.

**Comment by shiv-jirwankar** [comment]
@mxschmitt I tried this. But sadly it is not something which I am looking for. Actually, its a link where I need to verify the background color, clicking on that link is navigating to another page and hence the background color verification is failing.

Can we have a similar work-around by doing right-click instead?

**Comment by mxschmitt** [comment]
You can do this instead which will do a right click:

```js
   button.click({
      button: 'right',
      delay: 1000
    })
```

**Comment by shiv-jirwankar** [comment]
@mxschmitt Thanks for the update. I have tried the right-click option as well. But it isn't working the way I want. 

Here's my requirement:
- Right-click on the link element.
- Get the background color of the element which will change once we click on it.

Can you suggest any way by which we can do the following:

- Right-click on the link element and hold it for n second(s).
- While the right-click button is still pressed, I want to get the background color of the element before it is released.

Let me know if you have any solutions for this use case. Thanks.

**Comment by mxschmitt** [comment]
A different approach would be the following:

```js
// @ts-check
const playwright = require('playwright');

(async () => {
  const browser = await playwright.chromium.launch({
  });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.setContent(`
      <style>
        button {
          background-color: green;
        }
        button:active {
          background-color: red; /* This is the same as rgb(255, 0, 0) */
        }
      </style>
      <button>some button</button>
    `)

  const button = await page.waitForSelector("button:text('some button')")
  await button.hover();
  await page.mouse.down({
    button: "right",
  });  
  const buttonBackgroundColor = await button.evaluate(button => getComputedStyle(button).backgroundColor);
  console.log(buttonBackgroundColor, 'rgb(255, 0, 0)') // do your expect assertion here
  await page.mouse.up();
  await browser.close();
})();
```

**Comment by aslushnikov** [comment]
I'll close this since there's no response; feel free to re-file if things don't work!

**Comment by shiv-jirwankar** [comment]
@mxschmitt thanks for the update. The latest approach worked.
