### ISSUE TITLE
[Feature]: add page.scroll() method

### ISSUE THREAD

**Issue by radekBednarik** [microsoft/playwright#7963]
### Feature request

I encountered use case, where it would be usefull for me to have option to call something like this:

```
page.scroll({height: 50 %});
```
or

```
page.scroll({height: 540});
```

and this would scroll the page to the given pixel or percent ratio of the height.

In my use case, this action triggers another action, I want to test.

I know, that I can resolve some element sufficiently below the needed threshold and call:

```
elementHandle.scrollIntoViewIfNeeded();
```

but that creates dependency on that element.

Would something like this sound reasonable to you, Playwright team?

**Comment by mxschmitt** [comment]
Does the following work for your use case?

```js
await page.evaluate(() => window.scrollTo(0, 540));
```

See [here](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo) for docs.

**Comment by radekBednarik** [comment]
@mxschmitt omg, yes, ofc, I should have thought of this, thank you.
