### ISSUE TITLE
[Bug]: Black window background in chromium

### ISSUE THREAD

**Issue by fabianMendez** [microsoft/playwright#7966]
### Playwright version

1.13.1

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium

### Other information

OS: Ubuntu 21.04 x86_64

### What happened? / Describe the bug

A black background behind the chromium window

![image](https://user-images.githubusercontent.com/32204060/128029211-15947951-1ab8-4f6c-9712-9bb7c83c598d.png)

**Comment by mxschmitt** [comment]
How did you obtain the screenshot? Are you using Ubuntu Desktop or Server?

**Comment by fabianMendez** [comment]
> How did you obtain the screenshot? Are you using Ubuntu Desktop or Server?

I took it manually. I'm using Ubuntu desktop

**Comment by mxschmitt** [comment]
and when using normal Chromium there is no black background?

**Comment by fabianMendez** [comment]
> and when using normal Chromium there is no black background?

No, its looking fine:

![imagen](https://user-images.githubusercontent.com/32204060/128433188-cd352599-426c-47a7-974a-ac17bd2fdab5.png)


Also if I launch the browser directly from `~/.cache/ms-playwright/chromium-901522/chrome-linux/chrome` the black background appears.


And this version works fine: `~/.cache/ms-playwright/chromium-888113/chrome-linux/chrome`

**Comment by mxschmitt** [comment]
This then looks more like a Chromium bug. So I would recommend to open a bug report there and provide your "good" and "bad" version number: https://crbug.com

**Comment by mxschmitt** [comment]
You could also try to use a more recent development version of Playwright: `npm install playwright@next` (same would work with @playwright/test if you are using that). It might be fixed there already.

**Comment by fabianMendez** [comment]
I tried using @playwright/test@next but it also uses chromium build 901522 and the black background is still there.

Using the builds from here: https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/ I found the error was present until build 902463 and it was fixed in build 902556.

**Comment by mxschmitt** [comment]
Awesome, then this likely gets fixed when we are rolling to a new Chromium version via #8052. Thanks for confirming.
