### ISSUE TITLE
[Feature]: css selector pseudoclass that works like `innerText`

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#7978]
### Feature request

the current pseudoclasses for matching text, from my understanding, do the following:
- `:has-text` - matches every node which contains the specified text
- `:text` - matches the lowest node which contains the specified text
- `:text-is` - matches the lowest node with the exact specified text

what i want is a pseudoclass that works like the `innerText` method on element handles, which would allow you to match every node with exact text

additionally, the names of these pseudoclasses and the documentation doesn't really make it clear how they behave. the existence of `:has-text` and `:text-is` makes the behaviour of `:text` a complete mystery that isn't really explained in the docs

**Comment by KotlinIsland** [comment]
### Given:
```html
<label>foo</label>
<label><bdi>foo</bdi></label>
<label><span><bdi>foo</bdi><span></label>
```
### When:
you want to select a label node that that has has the exact text 'foo'
### Then:
This selector should work:
```css
label:text-is('foo'),label:has(:text-is('foo'))
```

### RECORD SCRATCH 💿📀💽
This doesn't work like innterText 😲 because 
```html
<label><span>foo</span><bdi>bar</bdi></label>
```
If I want to match this, I would have to use a gross XPath(🤮) selector 
```xpath
//label[.="foobar"]
```

**Comment by dgozman** [comment]
Could you please clarify your proposal? How would selector look like, e.g. `label:inner-text('foo')`? What should it return in the great example by @KotlinIsland? More examples will definitely help us understand the problem better.

**Comment by DetachHead** [comment]
It should work exactly like the `innerText` method on the element handle. So `label:inner-text('foo')` wouldn't match anything in that example because that label's `innerText` is "foobar"

Basically, it should work exactly the same as `//label[.='foo']` does

**Comment by KotlinIsland** [comment]
Same behavior as `//label[.='foo']`, but use innerText instead of concatenating all text nodes like XPath does.

I believe this selector will get you almost desired behavior(it's a strict match in total node text) except for not matching against 'innerText', ie will behave exactly like the XPath.
`label:text-matches('^foobar$')`

**Comment by KotlinIsland** [comment]
And yeah, I agree [the documentation](https://playwright.dev/docs/selectors/#text-selector) could be cleared up a little.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by KotlinIsland** [comment]
@pavelfeldman This feature is needed, please reopen.
