### ISSUE TITLE
[Feature]: Iframe selector that pierces iframes

### ISSUE THREAD

**Issue by uchagani** [microsoft/playwright#7982]
### Feature request

Similar to how playwright pierces shadow DOMs, it would be great to have an `:iframe` selector that can do the same thing.  This would allow us to write code that interacts with elements inside iframes in a similar manner.

For example, if we have a document that looks like this:

```html
<html>
   <head></head>
   <body>
      <div id="outside-iframe"></div>
      <iframe id="frame1">
         #document
         <html>
            <head></head>
            <body>
               <div class="inside-iframe">This is the Element I want</div>
            </body>
         </html>
      </iframe>
   </body>
</html>
```

Maybe we can have a selector called `:iframe` to access element inside the iframe:

```js
page.textContext(":iframe(#frame1 div.inside-iframe)");
```

the first parameter inside the selector is how to find the iframe. 

For nested iframes maybe we an nest the selector like this:

```js
page.textContent(":iframe(#frame1 :iframe(#nestedIFrame #someElementInsideNestedIframe))")
```

**Comment by splurgeop** [comment]
would be good to have this feature in playwright.

**Comment by unlikelyzero** [comment]
This would be a key differentiator in the e2e testing world.

**Comment by aslushnikov** [comment]
this is fixed!
