### ISSUE TITLE
[BUG] Unexpected behavior of the zs selector

### ISSUE THREAD

**Issue by arjun27** [microsoft/playwright#799]
I'm running into some unexpected behavior with the zs selector, given the following page content.
```js
await page.setContent(`
    <form>
        <div>Username</div>
        <div>
            <input type="text">
        </div>
    </form>
`)
```

This returns the input element:

```js
await page.$eval('zs=form input', e => e.outerHTML); // <input type="text">
```

But this throws an error:

```js
await page.$eval('zs=div input', e => e.outerHTML); // error
```

I would expect these 2 to behave consistently. Playwright Version: 0.10.0.

**Comment by pavelfeldman** [comment]
That's because `zs` has vastly different semantics from `css`. We should make it look different. Also, I think we should remove `zs` from playwright for now to not blur the driver focus. Wdyt?

**Comment by arjun27** [comment]
I think that's a good idea, especially since we support pluggable selectors. It will enable zs to go through its own cycles of maturity, independent of the driver focus (+1 on making it look different to css). It could even become a reference implementation of a pluggable selector that sits in its own package.

**Comment by pavelfeldman** [comment]
Removed
