### ISSUE TITLE
[Feature]: Trace Viewer expand the error logged in Console tab

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#7993]
### Feature request

We had a test that was failing intermittently and while analyzing the traces, we noticed an error being thrown while trying to submit the form. But the error details were missing and we could not debug the issue. Finally, after multiple tries, we were able to reproduce the issue manually and capture the error with details in DevTools.

Trace Viewer:
```
[2021-08-04T03:43:58.549Z] ERROR (SubmitForm): JSHandle@error              commons.test121332423.js:0
```
DevTools:
```
commons.test121332423.js:0 [2021-08-04T23:54:19.421Z] ERROR (SubmitForm): Error: [{"message":"HTTP Error","locations":[{"line":6,"column":11}],"path":["submit_shop","cloth_value"],"name":"HTTPError","time_thrown":"2021-08-04T23:54:19.320Z","data":{"code":500,"error":"RequestError","message":"getaddrinfo ENOTFOUND shop-value-api.test.test.com","url":"http://shop-value-api.test.test.com/shop_value/v1/clothes/123"}}]
    at r.<anonymous> (hello-world-a494cd680eae9a2bfecd.js:1)
    at s (commons.test121332423.js:1)
    at Generator._invoke (commons.test121332423.js:1)
    at Generator.next (commons.test121332423.js:1)
    at r (commons.test121332423.js:1)
    at u (commons.test121332423.js:1)
    at nrWrapper (Shopping:30)
```

Before:
Currently, in Trace Viewer -> Console tab, the errors are swallowed i.e. details are missing/error is not expanded.

After:
Trace Viewer -> Console tab, the errors are displayed with details to help debugging the issue

**Comment by pavelfeldman** [comment]
Fixed
