### ISSUE TITLE
[Question]: Is there any limitation on which header can we modify/remove?

### ISSUE THREAD

**Issue by thegamblerrises** [microsoft/playwright#7999]
### Your question

Playwright java 1.12.0
OS - MacOS/Ubuntu
Browser - chromium

I am unable to modify/remove some headers. These don't come in `route` method.
Are there limitation on which headers can be altered? Comment on this [bug#6190](https://github.com/microsoft/playwright/issues/6190#issuecomment-818959752) says like this.

```java
                page.route(s -> true, route -> {
                    Map<String, String> headers = new HashMap<>(route.request().headers());
                    headers.put("foo", "bar"); // set "foo" header
//                    headers.remove("accept");
                    headers.remove("Cache-Control"); // this doesn't get removed
                    headers.remove("upgrade-insecure-requests"); // this gets removed
                    headers.put("Accept-Encoding", "gzip");
                    route.resume(new Route.ResumeOptions().setHeaders(headers));
                });
```
Hars recorded still shows headers unchanged. Let me know if Har is needed. Thanks.

**Comment by mxschmitt** [comment]
Cookies/Host/security headers are probably either not possible to override or available after the request is finished. This is a network stack limitation of the browsers. In which headers are you particular interested to override them? 

As you already linked, see in https://github.com/microsoft/playwright/issues/6190#issuecomment-818959752 how to verify when which headers are available.

**Comment by thegamblerrises** [comment]
Hi @mxschmitt, thanks for the response. Actually, our tool is open for user to add/update/remove headers. So, we don't really have control over it, maybe except few.

I will check in #6190 (comment). Thanks.
