### ISSUE TITLE
INTERNAL: run all the tests with npm test

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright#8]
We are cross browser for real now. Let's run all the tests on npm test.

EDIT: This issue seems to be search engine bait for people looking how to run tests their with playwright. This is talking about how to run playwright's own internal tests. Please file a new issue if you need help running your own tests with playwright.

**Comment by yanivefraim** [comment]
@JoelEinbinder - Have you though about moving to Jest as the test runner? I think that using a standard open source library as a test runner is a better choice. I'll be happy to help.

**Comment by JoelEinbinder** [comment]
> @JoelEinbinder - Have you though about moving to Jest as the test runner? I think that using a popular open source library as a test runner is a better choice (easier for new developer to get in, tons of features, etc.)
> 
> I'll be happy to help.

We’ve been very happy with our current testing setup. Philosophically it would be good to be on Jest, because it would bring us closer to our users. But I don’t want to regress our dev experience in order to accomplish that.

If you send a PR or a prototype I’ll gladly take a look. I don’t want to commit to landing anything yet. I don’t know enough about jest.

**Comment by yanivefraim** [comment]
Ok, fair enough. I think that Jest might bring a better dev experience (Jest brings tons of really awesome features out of the box)
I can play with it and maybe have some prototype with several tests, running with Jest.

**Comment by jpita** [comment]
complete newbie to node/JS here.
once I have my tests, how do I run them?
