### ISSUE TITLE
[Bug]: Firefox not take screenshot in headless mode when canvas in hidden from page

### ISSUE THREAD

**Issue by sumitnegi7** [microsoft/playwright#8000]
### Playwright version

1.13.1

### Operating system

Linux

### What browsers are you seeing the problem on?

Firefox

### Other information

Ubuntu 20.04

### What happened? / Describe the bug

I hided an element (canvas) from the page and was trying to do visual testing against devices like iPad, Desktop versions of `chromium , firefox and webkit`. So the test passes in `webkit and chromium` but not taking screenshot in `firefox` when headless is set to true but works when headless is set to false.

### Code snippet to reproduce your bug

```shell
test file

import { test, expect } from "@playwright/test";

test.describe("Screenshot Testing", () => {
  test("compares screenshots for desktop, tablet and mobile screen", async ({ page }) => {
    await page.goto("/", {
      waitUntil: "networkidle",
    });
    await page.waitForSelector("canvas", { state: "visible" });
    await page.evaluate(() => {
      (document.querySelector("canvas") as HTMLElement).style.visibility = "hidden";
    });
    expect(await page.screenshot({ fullPage: true })).toMatchSnapshot("snap.png", { threshold: 0.05 });
  });
});


Config file

/** @type {import('@playwright/test').PlaywrightTestConfig} */
const { devices } = require("@playwright/test");
const config = {
  testDir: process.cwd(),
  use: {
    baseURL: `http://localhost:${process.env.PORT}`,
    headless: true,
    ignoreHTTPSErrors: true,
  },
  timeout: 120000,
  projects: [
    {
      name: "Chromium Desktop",
      use: {
        browserName: "chromium",
        ...devices["Desktop Chrome"],
      },
      testMatch: "*.e2e.ts",
    },

    // Test against different devices for visual tests.

    {
      name: "Firefox Desktop",
      use: {
        browserName: "firefox",
        viewport: devices["Desktop Firefox"],
       // headless: false,
      },
      testMatch: "*.visual.e2e.ts",
    },

    {
      name: "Webkit Desktop",
      use: {
        browserName: "webkit",
        ...devices["Desktop Safari"],
      },
      testMatch: "*.visual.e2e.ts",
    },

    {
      name: "Webkit IPhone X",
      use: {
        browserName: "webkit",
        ...devices["iPhone X"],
      },
      testMatch: "*.visual.e2e.ts",
    },

    {
      name: "Chromium Desktop HiDPI",
      use: {
        browserName: "chromium",
        ...devices["Desktop Chrome HiDPI"],
      },
      testMatch: "*.visual.e2e.ts",
    },

    {
      name: "Webkit iPad",
      use: {
        browserName: "webkit",
        ...devices["iPad Pro 11"],
      },
      testMatch: "*.visual.e2e.ts",
    },
  ],
  globalSetup: require.resolve("./global-setup"),
};

module.exports = config;


```

### Relevant log output

```shell
Slow test: [Firefox Desktop] › src/pages/home/tests.visual.e2e.ts (2m)
   1 failed
    [Firefox Desktop] › src/pages/home/tests.visual.e2e.ts:4:3 › Screenshot Testing compares screenshots for desktop, tablet and mobile screen
```

**Comment by mxschmitt** [comment]
Is there any other output being generated? Is in side the test-results an expected, actual, diff image for the test?

**Comment by sumitnegi7** [comment]
@mxschmitt  the image is not even being captured while running in headless mode.

**Comment by sumitnegi7** [comment]
@mxschmitt It works if i use browserName property with viewport(height and width) and not ` devices["Desktop Firefox"],`.

**Comment by mxschmitt** [comment]
Is the site public available? In your example you assigned the whole device descriptor to the viewport. You need to either spread it inside `use` or use the `viewport` directly what you wrote. In my case I tried both which was working for me.

If you could create a small Git repository with e.g. a local dev server or `await page.setContent()` to demonstrate it, it would probably help a lot.

**Comment by sumitnegi7** [comment]
@mxschmitt [here is a sample git repository](https://github.com/sumitnegi7/playwright-firefox) which replicates the bug please have a look.

**Comment by saikat-samanta** [comment]
I am also facing the same issue. Screenshot not capturing in `devices["Desktop Firefox"]`

**Comment by aslushnikov** [comment]
@saikat-samanta turns out this website is allergic for the user agent that we have as a part of device.

Here's the workaround that worked for me: https://github.com/sumitnegi7/playwright-firefox/pull/1

**Comment by sumitnegi7** [comment]
@aslushnikov thanks a lot works now.

**Comment by sumitnegi7** [comment]
@aslushnikov  It works in `https://www.manufacanalytics.com/career` page but in `https://www.manufacanalytics.com/` it takes a blank screenshot in firefox. Please have a look.

**Comment by aslushnikov** [comment]
@sumitnegi7 hmm, it runs fine when I run headful, and doesn't run in headless. It looks like the website is doing some anti-automation detection.

We don't give advice on mitigating this kind of issues, so i'll have to close this.
