### ISSUE TITLE
[Bug]: Trace Viewer doesn't show all screenshots

### ISSUE THREAD

**Issue by DavertMik** [microsoft/playwright#8003]
### Playwright version

playwright@1.13.1

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

I recorded a trace and I see a preview of some screenshots while I can't see them. For instance, I can't see what happened after the form was submitted. I see the preview of a last screenshot but I can't open it in full!

![image](https://user-images.githubusercontent.com/220264/128356613-60af10e5-ca34-42d6-9357-e8ba15d73915.png)

### Expected Behavior

I can travel through the timeline no matter there were Playwright commands executed or not.
I can see all the recorded screenshots and snapshots

**Comment by mxschmitt** [comment]
Could you provide us your trace file?

**Comment by DavertMik** [comment]
[register.zip](https://github.com/microsoft/playwright/files/6940696/register.zip)

Sure. I was using CodeceptJS to record this so maybe I was doing something wrong. But I just enabled trace recording at the very beginning of a test and stopped it after

**Comment by mxschmitt** [comment]
It's expected that in the first call, there is no "before" and in the last call no "after" snapshot. The top represents a timeline view of the whole execution while on the left side only the steps get represented. If you want to include more there, you can e.g. continue your test with page.click, use page.waitForSelector etc.

Above the snapshot previews at the top you see a visualisation of the steps and which of the steps where executed.

**Comment by DavertMik** [comment]
@mxschmitt So maybe this is not a bug then but a feature request. 

I was thinking that I could use Trace View as an alternative to video for session tracking, not only for cases where the session is controlled by Playwright.

For instance, I would like to ask QA to reproduce a bug, create a simple script to launch Playwright and save tracing and ask user to do clicks and send a file to me. I would like to replay this with all information I need.

So I expect Trace View will help me to debug an issue even if there were no Playwright actions.
Also, it would be nice if Trace could also catch user performed actions, like clicks, text inputs, etc and include it as well.

**Comment by aslushnikov** [comment]
@DavertMik sounds like you can do this already using `npx playwright codegen`. It'll open a browser window, users will be able to click, and the script will be auto-generated. The only missing bit is tracing that they'll need to record separately.

So maybe what you need is a `--tracing` option in the `npx playwright codegen` command?

**Comment by DavertMik** [comment]
I think I misunderstood this feature. I expected it to be a more detailed alternative to video... 

This is the use case I had in mind:

> For instance, I would like to ask QA to reproduce a bug, create a simple script to launch Playwright and save tracing and ask user to do clicks and send a file to me. I would like to replay this with all information I need.

I don't think I need playwright steps pre-generated for that. Probably this can be a good side-effect but this doesn't seem to be important.

What I thought the trace to be is to take Screenshots/Snapshots per some time or by listening to DOM Mutation and page loads. 
At least this approach seems to provide more complete info. And this may get more use cases than just test automation.

**Comment by aslushnikov** [comment]
@DavertMik we just had a team meeting where we discussed this. It looks like what you actually want is

```sh
$ npx playwright codegen --trace=./trace.json
```

This way you'll get a browser UI, possible script, and a saved trace to a `./trace.json` file. Then you can ask QA to just send you the `trace.json` file. 

Would this work for you? We don't have this flag yet, but it seems to be very real to add it.

**Comment by DavertMik** [comment]
This can be an option. Thank you! 
I will create a new issue for that
