### ISSUE TITLE
[Question]: Why isn't `test.afterAll` ran after a failed test?

### ISSUE THREAD

**Issue by raikoss** [microsoft/playwright#8005]
### Your question

I assume this is somewhat related to #7882, more specifically with how a new worker being created for a new test run after one fails. 

## Use case

I have a use case where I need to allocate something externally before a test suite is ran, and clear it after it is finished, regardless of whether any tests failed. Now, I can understand _why_ the new worker runs `test.beforeAll` again when continuing with the tests, which leads to one-time setups per suite being ran multiple times in case one fails. This is problematic when relying on external resources, as now my allocation is being ran multiple times to my external resource, and never being cleared as `test.afterAll` is not being ran on the workers with the failed tests. 

## Example

Take this simple test file. You will not see "End of test" printed, which is to be expected, but you do not see "AfterAll" printed either. Depending on how many retries you've set in your config, "BeforeAll" and "Start of test" is being printed those times as well. 

```js
import test, { expect } from "@playwright/test";

test.beforeAll(() => {
  console.log("BeforeAll");
});

test.afterAll(() => {
  console.log("AfterAll");
});

test("Test", async () => {
  console.log("Start of test");
  expect(true).toBe(false);
  console.log("End of test");
});
```

Is this intentional? I guess it may not be a very common use case, but it is a different way of handling failed tests than [jest-playwright](https://github.com/playwright-community/jest-playwright) which I originally started with and migrated from. 

Answers and reasoning is much appreciated, and thanks for a great testing library :)

**Comment by dgozman** [comment]
Fixed by #8102.
