### ISSUE TITLE
[Feature]: `test.omit` to ignore tests on certain environments

### ISSUE THREAD

**Issue by ingvar-nikiforov** [microsoft/playwright#8006]
### Feature request

Use case

I have 3 different environments: `qa`, `qa mobile` and `staging`. And I created 3 projects for them in `playwright.config.js`.

```js
// registration.spec.js
test('Register', async ({ env, registration }) => {
```

The new feature came up for registration page and is available on `qa` environments but not on `staging`.
So I wrote a new test.
I use `test.skip` to avoid running test on non-suitable environments.

```js
// new_registration.spec.js
test.skip(({ env }) => !['qa', 'qa mobile'].includes(env.name))
test('Register', async ({ env, registration }) => {
```

The old test has changed too:
```js
// registration.spec.js
test.skip(({ env }) => !['staging'].includes(env.name))
test('Register', async ({ env, registration }) => {
```

The output of both registration tests is messy.

```
Running 6 tests using 4 workers

  - [qa] › register/registration.spec.js:6:1 › Registration
  ✓  [qa] › register/new_registration.spec.js:6:1 › Registration (6s)
  - [qa mobile] › register/registration.spec.js:6:1 › Registration
  ✓  [qa mobile] › register/new_registration.spec.js:6:1 › Registration (6s)
  ✓  [staging] › register/registration.spec.js:6:1 › Registration (6s)
  - [staging] › register/new_registration.spec.js:6:1 › Registration
  
  3 skipped
  3 passed (6s)
```

So I propose to add `test.omit` so that excluded environments will not show up in results like this:
 ```
Running 3 tests using 3 workers

  ✓  [qa] › register/new_registration.spec.js:6:1 › Registration (6s)
  ✓  [qa mobile] › register/new_registration.spec.js:6:1 › Registration (6s)
  ✓  [staging] › register/registration.spec.js:6:1 › Registration (6s)
  
  3 passed (6s)
```

**Comment by ingvar-nikiforov** [comment]
In CI with parallel run through shards: some shards are assigned with only skipped tests. 
Which results in ineffective usage of threads. 
```
> npx playwright test "--shard" "10/20"


  225 skipped
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
