### ISSUE TITLE
[Feature]: Fail when there is an uncaught JS error

### ISSUE THREAD

**Issue by unformatt** [microsoft/playwright#8013]
### Feature request

I can catch the JS error myself and close the page myself but the resulting error shown by the test runner is not informative `playwright._impl._api_types.Error: net::ERR_ABORTED; maybe frame was detached?`

```python
        def on_page_error(exc):
            cls.page.close()

        cls.page.on('pageerror', on_page_error)
```

Two options I see

1) Option to tell Playwright to fail a test when there is an uncaught JS error on the page and have test error message show the JS error message.

2) Be able to fail test from page object e.g. 

```python
        def on_page_error(exc):
            cls.page.fail_test("There was a JS error: " + str(exc))

        cls.page.on('pageerror', on_page_error)
```

**Comment by mxschmitt** [comment]
Normally `: net::ERR_ABORTED; maybe frame was detached?` should not result in a `pageerror` event from my understanding. Only JavaScript exceptions should. Do you have a reproducible script for that?

**Comment by aslushnikov** [comment]
I'll close this due to lack of feedback; feel free to re-file!
