### ISSUE TITLE
[BUG] Firefox Self signed certificate not working

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#802]
**Context:**
- PlayWright Version: 0.10.0
- Operating System: Mac
- Extra: -

**Code Snippet**

```javascript
const { firefox } = require('playwright');

(async () => {
  const browser = await firefox.launch({
    headless: false,
    ignoreHTTPSErrors: true
  });
  const context = await browser.newContext();
  const page = await context.newPage('https://localhost:8000');

  await page.screenshot({ path: `firefox.png` });
  await browser.close();
})();
```

**Describe the bug**

I was not able to automate the behaviour to visit https based sites with a self-signed-certificate.
Instead a ` failed: SSL_ERROR_UNKNOWN` error was thrown during the `newPage` call.
Also if we take a look at the actual page via `headless: false`, we see the following error:

<img width="694" alt="Screenshot 2020-02-02 at 12 53 36" src="https://user-images.githubusercontent.com/17984549/73607798-1adb4500-45bb-11ea-8b72-8bb063b721a4.png">

**Comment by pavelfeldman** [comment]
You should pass `ignoreHTTPSErrors` into [browser.newContext](https://github.com/microsoft/playwright/blob/master/docs/api.md#browsernewcontextoptions) instead of `launch`. Please reopen if that does not work for you!

**Comment by m4rcelofs** [comment]
@pavelfeldman is there any way of installing custom certificates instead of ignoring the errors? would installing the certs on the local machine work?

we are visiting some government websites where the root cert is not installed on any browser, but would like to avoid loosing https validation.
