### ISSUE TITLE
[Question]: How can I run playwright test programmatically?

### ISSUE THREAD

**Issue by ua2028** [microsoft/playwright#8027]
### Your question

hi, 

With Mocha you can the tests programmatically, as in: `await mocha.run` directly from a script, adding all the files, options, and getting the results from the tests run back. 
I was wondering how I can do that with playwright test

Thanks

**Comment by mxschmitt** [comment]
Do you mean you want a Node.js API to add files manually which you want to test?

**Comment by ua2028** [comment]
Yes like the link that you shared. "currently not yet possible" is better than "won't be possible" I guess, thank you for your swift reply.

**Comment by mxschmitt** [comment]
👍  I might it fold it into #7275 since it seems similar.
