### ISSUE TITLE
[Bug]: isEnabled / isDisabled not working with custom elements

### ISSUE THREAD

**Issue by pohlt** [microsoft/playwright#8028]
### Playwright version

1.13.1

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

I'm using playwright-python 1.13.1.

### What happened? / Describe the bug

We are using custom elements (e.g. `my-checkbox`). This custom checkbox mimics the interface of a regular checkbox. In particular, it uses a `disabled` attribute just like a regular checkbox.

playwright seems to assume that only certain standard elements can be disabled (as suggested in the [docs](https://playwright.dev/python/docs/actionability#enabled)) and always returns `true`/`false` when using `isEnabled`/`isDisabled` on this custom element independent of the `disabled` attribute of the custom element.

Currently, I'm checking the `disabled` attribute "manually" using `getAttribute("disabled")`.

Is this the intended behavior for `isEnabled`/`isDisabled` in combination with custom elements?

**Comment by mxschmitt** [comment]
Currently we only allow it for certain node types (button, input, select, textarea) ref: https://github.com/microsoft/playwright/blob/cc43f9339f91011fdb795ea01c07d5122f6179c6/src/server/injected/injectedScript.ts#L459-L463

Marking it as a feature request.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
