### ISSUE TITLE
[Bug]: inputValue method is not available in  version 1.13.1

### ISSUE THREAD

**Issue by macroking** [microsoft/playwright#8036]
### Playwright version

13.0.1

### Operating system

Windows

### Other information

NodeJS v14.17.0
Windows 10

### What happened? / Describe the bug

In version 1.13.0, `*.inputValue()` method was added to retrieve value from an input box or text area. That function is not available in 1.13.1

**Comment by mxschmitt** [comment]
Please provide a code snippet how you are using it.

**Comment by macroking** [comment]
Assume AUT has a bunch of text boxes.  This is the code I wrote with version1.13.0

``` javascript
let fields = ['field`', 'field2', 'field3'];
let op = {};
for (let i = 0; i < fields.length; i++) {
    op[fields[i]] = await this.page.inputValue('#edit-' + fields[i]);
}
```

`inputValue` method is not available in the latest version.

**Comment by mxschmitt** [comment]
Are you using Playwright or Playwright Test? Which versions do you have in your package.json? Can you execute there "npm install" to install the latest one?

**Comment by macroking** [comment]
I am using playwright test   `  "@playwright/test": "^1.13.1",`. I installed the latest version of Playwright test, that is when I ran into this issue.

**Comment by mxschmitt** [comment]
I tried the following which works for me with 1.13.1 and 1.13.0:

```js
import { expect, test } from '@playwright/test';

test("foo", async ({ page }) => {
  await page.setContent(`<input value="123"/>`)
  expect(await page.inputValue("input")).toBe("123")
})
```

So I expect that e.g. your node_modules is busted or this.page is null/undefined. What is the exact error which you are getting?

**Comment by macroking** [comment]
Thanks @mxschmitt , it is working now. Now, VSCode is unable to find the typings for `inputValue'.  I guess it is may be something on my end.
