### ISSUE TITLE
[Question]: Can be standard page fixture extended by other fixture?

### ISSUE THREAD

**Issue by nickosh** [microsoft/playwright#8037]
### Your question

In fixture documentation I see an example:

> // Extend basic test by providing a "table" fixture.
> const test = base.extend<{ todoPage: TodoPage }>({
>   todoPage: async ({ page }, use) => {
>     const todoPage = new TodoPage(page);
>     await todoPage.goto();
>     await todoPage.addToDo('item1');
>     await todoPage.addToDo('item2');
>     await use(todoPage);
>     await todoPage.removeAll();
>   },
> });

It looks like _todoPage_ fixture can be mixed with _page_ because of _todoPage.goto()_. It is real can me merged together or this just same named function in todoPage?

**Comment by mxschmitt** [comment]
You can do both, the page instances stays the same when multiple times using the fixture, you can keep it as a instance variable inside the todoPage and access it by that or you use the `page` fixture as normal inside your tests in combination with the `todoPage`.

It's not possible to add custom methods on a page instance or extend it, if it's that what you ask for.

**Comment by nickosh** [comment]
Yes, exactly what I asked. So if I use page instances inside TodoPage I can use it like todoPage.page.goto() or made my own goto with this instance. Original page instance can't be changed or extended. Got it, thanks!

**Comment by mxschmitt** [comment]
In theory you can override see here: https://playwright.dev/docs/test-fixtures#overriding-fixtures

**Comment by nickosh** [comment]
Override not exactly same - than I need to fully rebuild page fixture by myself from scratch. More easy will be use page instance inside my fixture then. My idea to use my own page fixtures instead of prebuilded.

**Comment by mxschmitt** [comment]
(This example also shows how you can override the page fixture. By doing page.goto always before getting it. So you don't need to implement it from scratch, you have access to the previous inherited value.)

**Comment by nickosh** [comment]
I see. Looks like my pages fixture will be pretty big to override 'page' this way but maybe I can use it for another purpose. From that example I just wrongly thinks there a way to mix 'page' fixture with 'todoPage' fixture automatically. Like extend 'todoPage' fixture from original 'page' but it not works this way. Still will be useful to have ability to do it, I think.
