### ISSUE TITLE
[BUG] Firefox dev tools limited by viewport width/height

### ISSUE THREAD

**Issue by aesyondu** [microsoft/playwright#804]
**Context:**
- PlayWright Version: 0.10.0
- Operating System: Mac OS X - 10.14.6
- Extra: Node v13.7.0

**Code Snippet**

```javascript
const playwright = require("playwright");

(async () => {
    for (const browserType of ["chromium", "firefox", "webkit"]) {
        const browser = await playwright[browserType].launch({
            headless: false,
        })
        const context = await browser.newContext({})
        const page = await context.newPage("http://localhost:8080")

        // await browser.close()
    }
})();
```

**Describe the bug**

When using non-headless "firefox", dev tools width/height limited by viewport. Works ok on "chromium" and "webkit".

Firefox:

![firefox](https://user-images.githubusercontent.com/57334943/73610197-ba2a2780-460f-11ea-9022-acfaf3f76584.gif)

<hr>

Chromium:

![chromium](https://user-images.githubusercontent.com/57334943/73610200-c9a97080-460f-11ea-9a51-8553c394157e.gif)

**Comment by dgozman** [comment]
This is a side-effect of setting page viewport size. The workaround is to undock developer tools into a separate window (from the `...` menu).
