### ISSUE TITLE
[Question]: How to set the location of allure-results and screenshot via playwright.config.ts file?

### ISSUE THREAD

**Issue by kshrestha99** [microsoft/playwright#8041]
### Your question

I am using experimental-allure-playwright which creates the allure-results folder at the root of my project. I want to be able to control where it is created via my config file. The only documentation I could find in regards to this is:
"Keep in mind that, you can specify target folder using ALLURE_RESULTS_DIR environment variable."
I am not sure how to do this, and also I would love to be able to do something like this in the config file:
```
reporter: [
    ['line'],
    [
      'experimental-allure-playwright',
      {
        outputFile: `${process.cwd()}/qe/test-reports/alure-results`,
      },
    ],
  ],

```

The other question I have is when I have "screenshot" as "on" in the config file, it automatically creates a new folder called "test-results" again in the root of the project. How can I control where this folder is created via the config file?
@pavelfeldman 
@AlexKomanov

**Comment by mxschmitt** [comment]
```bash
# Linux/macOS
ALLURE_RESULTS_DIR=qe/test-reports/alure-resultsr npx playwright test

# Windows with cmd.exe
set ALLURE_RESULTS_DIR=qe/test-reports/alure-results
npx playwright test

# Windows with PowerShell
$ALLURE_RESULTS_DIR="qe/test-reports/alure-results"
npx playwright test
```

`test-results` can be modified in the config via the `outputDir` property, see here: https://playwright.dev/docs/api/class-testconfig#test-config-output-dir

**Comment by kshrestha99** [comment]
Thank you @mxschmitt as always! Appreciate it!
