### ISSUE TITLE
[Feature]: The ability to locate psudo-elements or obtain a refreshed copy of the DOM once psudo elements are loaded in. 

### ISSUE THREAD

**Issue by supercom32** [microsoft/playwright#8042]
### Feature request

Recently I noted an increasing amount of websites which have started to use psudo-elements (for example, "::before" and "::after") to insert large amounts of dynamic content on a page. While opening your browsers debug console, your free to locate these elements using standard methods (like xPath) which appears to work just fine. However when using playwright, this does not work since psudo elements do not yet exist in the DOM (from playwrights perspective), and are only added in after the fact.

Is there a proper way for playwright-go to locate psudo elements using standard methods like xPath? Or, is there a way to somehow ask playwright to refresh it's copy of the DOM once a page has been fully loaded (when the DOM is finally updated to what the user actually sees? Ie. HTML [→ JavaScript] → CSS → Result)?

This is rather an important issue, since you cannot interact with any portion of a page that is contained under a psudo-element, and large portions (if not entire chunks) of pages are now using them for displaying dynamic content?

**Comment by pavelfeldman** [comment]
Pseudo elements are not exposed to the web. Could you provide an example of xpath that works for you an what it exposes? (Playwright supports xpath). Also there is no trend here - pseudo elements are an ancient feature that can be used for visual effects, but they are not interactive, interactivity works through the owning elements. Would appreciate an example you'd like to see supported.

**Comment by supercom32** [comment]
Hi there. Thanks for the kind reply. I am trying to see if I can reproduce this, but it sounds like just waiting an arbitrary amount of time is now working for me. I'm not sure what was different before. I will consider the matter closed for now, but if I can find a reproducable test case I'll keep it in mind and present something that can be looked at.

Thanks again for your help. I sincerely do appreciate it!
