### ISSUE TITLE
[Internal] Drop 32 bit Windows builds

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#8045]
Windows 32 bit is not used anymore. The measurements which we currently use (VSC, browser download stats) are not correct, because os.arch() returns also 32 bit on a 64 system. In Python or other languages this is e.g. not the case and returns 64 bit instead (for driver downloads e.g.).

![image](https://user-images.githubusercontent.com/17984549/128538258-7dbc853c-7440-49bf-bcc9-841e88571bee.png)

ref: https://www.pcbenchmarks.net/os-marketshare.html

**Comment by mxschmitt** [comment]
Merged the drop of 32 bit and moved to 1.17 the removal of the infrastructure changes.

**Comment by aslushnikov** [comment]
this is fixed
