### ISSUE TITLE
[Feature]: Add error handling for flaky tests

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#8048]
### Feature request

Currently, if a test is flaky (i.e. fails on first run but passes on retry), the traceback in console is not printed for first failure.

For example (current behavior):

```
Running 1 test using 1 worker

✘  1) [Desktop Chrome] › testrunnerdemo.spec.js:3:1 › test (20s) //Made the first run fail on purpose
✓  [Desktop Chrome] › testrunnerdemo.spec.js:3:1 › test (7s)

  Slow test: [Desktop Chrome] › testrunnerdemo.spec.js (27s)

  1 flaky
    [Desktop Chrome] › testrunnerdemo.spec.js:3:1 › test 
```
Feature request is to print something similar to this:

```
✘  1) [Desktop Chrome] › testrunnerdemo.spec.js:3:1 › test (20s)
✓  [Desktop Chrome] › testrunnerdemo.spec.js:3:1 › test (7s)

1) [Desktop Chrome] › testrunnerdemo.spec.js:3:1 › test
    Timeout of 20000ms exceeded.

    Pending operations:
      - page.click at tests/testrunnerdemo.spec.js:6:14

    page.click: Protocol error (Runtime.callFunctionOn): Target closed.
    =========================== logs ===========================
    waiting for selector "text=Get started"
    ============================================================

      4 |   await page.goto("https://playwright.dev/");
      5 |   await page.waitForTimeout(3000);
    > 6 |   await page.click('text=Get started');
        |              ^
      7 | });

        at /Users/test/Desktop/Demo/play_demo/tests/testrunnerdemo.spec.js:6:14
        at WorkerRunner._runTestWithBeforeHooks (/Users/test/Desktop/Demo/play_demo/node_modules/@playwright/test/lib/test/workerRunner.js:390:7)
```

```
// testrunnerdemo.spec.js
const { test } = require('@playwright/test');

test('test', async ({ page }) => {
  await page.goto("https://playwright.dev/");
  await page.waitForTimeout(3000);
  await page.click('text=Get started');
});
```

```
//playwright.config.js
module.exports = {
  timeout: 20000,
  retries: 1,
  workers: 2,
  use: {
    headless: false,
  },

  reporter: 'list',

  projects: [
    {
      name: 'Desktop Chrome',
      use: { browserName: 'chromium' },
    }
  ],
};

```

**Comment by dgozman** [comment]
@Nav-2d Could you please help me better understand flaky tests in your workflow? Some questions are directly related to this issue, and some are less so:
- How much are you concerned with flaky tests? What number of retries do you use?
- If we introduce something like `config.showFlakyFailures`, would that work for you?
- Do you consider your flaky tests as non-failing the run? E.g. if something flakes on CI, is that ok for you or not? Would you like that changed?
- Would you like to mark known flaky tests as `test.flaky` - so that newly introduced flaky tests will give you red CI runs?

Thank you!

**Comment by Nav-2d** [comment]
@dgozman  Thank you for looking into this. I discussed these questions with my team and here are the answers:

> How much are you concerned with flaky tests? What number of retries do you use?

Normally the product is the source of the flakiness, and capturing that (and all the details around it) is really important for us. With trace viewer, that really solves half the battle. We have the info we need for intermittent failures, without needing to return and try to reproduce manually ourselves between 1-1000 times (so wasteful for rare intermittent issues). 

We are currently using `retries: 1`

> If we introduce something like `config.showFlakyFailures`, would that work for you?

Just to clarify, would this print the number of failures (i.e. count) or traceback from all flaky tests? It would be beneficial to have a list of flaky tests with traceback to quickly analyze and find the root cause.

> Do you consider your flaky tests as non-failing the run? E.g. if something flakes on CI, is that ok for you or not? Would you like that changed?

We would like to keep the things similar to what we have currently i.e. if the test fails on first try and passes on retry then we do not fail the build. 

1. Automatically continue past a retry-then-pass result and forget about it (NOT OK)
2. Automatically continue past a retry-then-pass result and notify/collect/analyze the first failure result (OK)

Currently, we have another project which uses `WDIO` with retry set to 1 and have similar approach to not fail the CI build if the test passes on retry. But we do capture the details of the first failure from Jenkins console in Splunk dashboard so that we can reference them in the future and do not forget about them. We are currently thinking of having a similar dashboard for `Playwright` tests as well to keep track of first failure.

Alternatively, we wanted to get your thoughts on a service similar to the following (this is a stretch goal and might not be on Playwright's roadmap):
Create some kind of cloud service trace viewer to collect results (similar to SauceLabs). A service to collect, store and run analytics on the test results and even to notify in the case that a retry happened, so it can be investigated immediately. More of a test result analyzing service.

> Would you like to mark known flaky tests as test.flaky - so that newly introduced flaky tests will give you red CI runs?

In our workflow, if the test is flaky, we mark it as `test.skip` until the test script is fixed or product issue is resolved so that we are not blocking the builds.

**Comment by dgozman** [comment]
@Nav-2d Thank you for the detailed answer.

> Just to clarify, would this print the number of failures (i.e. count) or traceback from all flaky tests? It would be beneficial to have a list of flaky tests with traceback to quickly analyze the failure

Yes, and maybe even without a setting.

> Alternatively, we wanted to get your thoughts on a service similar to the following (this is a stretch goal and might not be on Playwright's roadmap):
> Create some kind of **_cloud service_** which stores trace files and test results (similar to Cypress and SauceLabs paid services). This service can be used to collect, store and run analytics on the test results and even to notify in the case that a retry happened, so it can be investigated immediately. In that way, we can investigate retries and act upon it instead of forgetting about them. (More of a test result analyzing service)

This sounds great and is a logical thing to do, but there are no specific plans for this right now.

> > Would you like to mark known flaky tests as test.flaky - so that newly introduced flaky tests will give you red CI runs?
> 
> In our workflow, if the test is flaky, we mark it as `test.skip` until the test script is fixed or product issue is resolved so that we are not blocking the builds. Would you like to elaborate how marking test flaky would help considering we don't want to block pipeline builds?

This is about being more strict. For example, if you'd like to not retry by default because you believe in your tests being strict, but perhaps some of them are still flaky so you mark them as "flaky" instead of removing them entirely or skipping and losing some coverage. Something like that might be interesting for teams that actively fight flaky tests. But these are just ideas, nothing specific planned yet, just gathering more opinions/feedback.

**Comment by Nav-2d** [comment]
@dgozman Thank for implementing the functionality :) 

> This sounds great and is a logical thing to do, but there are no specific plans for this right now.

Yes, I believe it will benefit lot of teams. Another use-case I can think of is: Currently, Allure Report comes with `trace.zip` file and we can download the trace file and run it locally using terminal. But sometimes developers or product managers or BAs look at allure results to get an overview of the test results and they don't want to download the file or take extra steps. Instead opening the trace file on cloud service or browser itself would be amazing (Similarly, traces stored in S3 bucket or as Jenkins build artifacts). I am just throwing ideas here and could be wrong as well. Would you like a separate ticket for tracking purposes or get opinions from others?

> This is about being more strict. For example, if you'd like to not retry by default because you believe in your tests being strict, but perhaps some of them are still flaky so you mark them as "flaky" instead of removing them entirely or skipping and losing some coverage. Something like that might be interesting for teams that actively fight flaky tests. But these are just ideas, nothing specific planned yet, just gathering more opinions/feedback.

Thanks for the explanation. Yes, I really like the idea of being strict with an option to mark test as flaky (considering `retries` are set to 0) and get more insights. Depending on the requirements , teams can decide where to mark the CI build as red or not. Again, let me know if you think it could be pulled out in a separate ticket to gather more opinions.

**Comment by dgozman** [comment]
> Yes, I believe it will benefit lot of teams. Another use-case I can think of is: Currently, Allure Report comes with `trace.zip` file and we can download the trace file and run it locally using terminal. But sometimes developers or product managers or BAs look at allure results to get an overview of the test results and they don't want to download the file or take extra steps. Instead opening the trace file on cloud service or browser itself would be amazing (Similarly, traces stored in S3 bucket or as Jenkins build artifacts). I am just throwing ideas here and could be wrong as well. Would you like a separate ticket for tracking purposes or get opinions from others?

These are all good ideas, and we are thinking along the lines. I don't think that a ticket will help right now though, it's too early.

> Thanks for the explanation. Yes, I really like the idea of being strict with an option to mark test as flaky (considering `retries` are set to 0) and get more insights. Depending on the requirements , teams can decide where to mark the CI build as red or not. Again, let me know if you think it could be pulled out in a separate ticket to gather more opinions.

This one we can do if we gather enough feedback. Please file an issue if you'd like and explain it as you see it 😄

**Comment by pbn04001** [comment]
Would it be possible to get this output in a processable format like xml, json, etc.    Ideally so we can then alert these flaky tests to teams who can work to harden them.
