### ISSUE TITLE
[Question] addScriptTag path relativity

### ISSUE THREAD

**Issue by aesyondu** [microsoft/playwright#805]
According to [addScriptTag api docs](https://github.com/microsoft/playwright/blob/master/docs/api.md#pageaddscripttagoptions),

> If path is a relative path, then it is resolved relative to current working directory.

I have a folder structure as follows:
rootProject/
--src/
----main.js
----main.spec.js
----test.js

I execute playwright using `rootProject$ node src/main.spec.js`. When I add the following in `main.spec.js`:
```javascript
page.addScriptTag({
    path: "./test.js",
})
```

and execute using `rootProject$ node src/main.spec.js`, I get an error:
```
Error: ENOENT: no such file or directory, open './test.js'
```

However, when I `cd src` and `node main.spec.js`, it works fine with no errors.

Is this expected behavior? I assumed that the path string would be relative to the current file, i.e., `src/main.spec.js`, instead of relative to the current working directory where node was executed, i.e., `rootProject$`?

**Comment by pavelfeldman** [comment]
It looks like it is working as intended: your current working directory `process.cwd()` points to `rootProject`, so relative to `cwd`, the path you should specify is `src/main.spec.js`. If you'd like it to be relative to your script file, you can use `path.join(__dirname, 'test.js')`. Please reopen if I got it all wrong!

**Comment by aesyondu** [comment]
Got it, thanks for clarifying :)
