### ISSUE TITLE
[Bug]: Bump Runtime.Evaluate priority in Chromium

### ISSUE THREAD

**Issue by hptabster** [microsoft/playwright#8053]
I'm stymied with this issue, tried page.click with delay set to various values (including 0) and longer timeouts values as well. Also tried to set force to true.

I've seen this issue in versions 1.8 up to 1.13.

 Here is the error from the catch block (is there more detailed debugging possible):

```
  pw:api => page.click started +296ms
  pw:api waiting for selector ".modal__body.settings-body div:nth-child(3) button.secondary" +1ms
  pw:api   "networkidle" event fired +202ms
  pw:api   selector resolved to visible <button class="secondary">Clear browser memory</button> +1s
  pw:api attempting click action +2s
  pw:api   waiting for element to be visible, enabled and stable +0ms
  pw:api <= page.click failed +3s
page.click: Timeout 5000ms exceeded.
=========================== logs ===========================
waiting for selector ".modal__body.settings-body div:nth-child(3) button.secondary"
  selector resolved to visible <button class="secondary">Clear browser memory</button>
attempting click action
  waiting for element to be visible, enabled and stable
============================================================
    at Object.click (/Users/jonathan/EWM/bitbucket/qa-latamfx/utils/utils.js:127:18)
    at async Object.clearBrowserMemory (/Users/jonathan/EWM/bitbucket/qa-latamfx/utils/settings.js:68:6)
    at async Context.<anonymous> (/Users/jonathan/EWM/bitbucket/qa-latamfx/test/trading_widget_orders.js:29:12) {
  name: 'TimeoutError'
}
```

This is the wrapper function used:
```
async function click(page, selector, opts = {}) {
  const wait = opts.wait || 0;
  const retries = opts.retries || 0;
  let timeout = opts.timeout || 5000;
  let delay = opts.delay || 20;
  let error;
  await sleep(wait);
  for (let i = 0; i <= retries; i++) {
    try {
      await page.click(selector, {
        force: false,
        ...opts,
        timeout: timeout,
        delay: delay,
      });
      return true;
    } catch (err) {
      error = err;
      timeout += 25;
      delay += 25;
    }
  }
  debug(error);
  return false;
}
```

**Comment by pavelfeldman** [comment]
I can see "waiting for element to be enabled and stable" followed by "Timeout 5000ms exceeded" in the log. It means that you are trying to click something invisible/disabled/moving and we time out waiting for it to become do. Try recording a trace or running headed to see what's going on in the page / snapshot.

**Comment by hptabster** [comment]
Please elaborate what you mean by recording a trace.

I typically run theses tests "headed" and do see the selector. Not sure why it might be considered moving. When I manually inspect (increase timeout to a large value) the element it appears to be there. Is there anything else to help debug this?

Thanks,
Jonathan

**Comment by aslushnikov** [comment]
@hptabster by trace we actually mean [Playwright Tracing](https://playwright.dev/docs/api/class-tracing)

Basically, in the very beginning of your script, enable tracing, and stop it in the very end:

```js
await context.tracing.start({ screenshots: true, snapshots: true });
// ....... script ......
await context.tracing.stop({ path: 'trace.zip' });
```

After that, please share the trace with us!

> **NOTE** The resulting script will have all kinds of data regarding the website you automate, including cookies set during website automation.

**Comment by hptabster** [comment]
Attaching trace.zip

[trace.zip](https://github.com/microsoft/playwright/files/6962389/trace.zip)

**Comment by hptabster** [comment]
Any update on this?

**Comment by aslushnikov** [comment]
@hptabster interesting! This does look like a bug indeed.  Any chance you can actually share your script with us so that we can repro it locally?

**Comment by hptabster** [comment]
@aslushnikov  The codebase is quite large. Is it possible to setup a screen share session?

**Comment by pavelfeldman** [comment]
I also looked at the trace and it looks weird. Could you ping us on our slack? It is easier to sync up regarding a screen share session there.

**Comment by pavelfeldman** [comment]
I ran it locally. What happens there is 100% CPU load with never-ending sequence of 11ms tasks processing web socket data.

User gesture can break through this busy loop due to scheduler prioritization, but Playwright's helper evaluates are getting stuck. This is most likely a bug on the page side, but it would be nice for Playwright to bump its evaluate priorities and get evaluates on the user gesture priority level scheduler-wise.

**Comment by dgozman** [comment]
For the reference, upstream patch: https://chromium-review.googlesource.com/c/chromium/src/+/3166590

**Comment by hptabster** [comment]
Is there any timeframe for making this change, reported over 11 months ago. My application has a lot of websocket traffic and the automation cannot run.

**Comment by dgozman** [comment]
@hptabster Unfortunately, the proposed fix in Chromium did not work right away, so this is still not fixed. Meanwhile, we haven't seen many reports of similar issues, so we haven't prioritized it.

**Comment by hptabster** [comment]
It's definitely blocking my use of Playwright, as I have written extensive test of a trading platform that heavily uses websockets for price updates. Unfortunately, what I can do easily in Chrome browser fails when running in Playwright, due to the CPU expended on handling the websocket traffic. At this point I can no longer run my Playwright tests.

I've looked into porting the Playwright to other frameworks (Cypress.io), but they also have limitations (lack of support for multiple Chrome windows/tabs).

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
