### ISSUE TITLE
[Feature]: Create a test adapter for Test Explorer UI

### ISSUE THREAD

**Issue by scraper** [microsoft/playwright#8077]
### Feature request

It would be nice to have for Playwright Test a test adapter for [Test Explorer UI](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer)

**Comment by mxschmitt** [comment]
We are exploring something similar for Visual Studio Code, stay tuned!

**Comment by ingvar-nikiforov** [comment]
Are you going to create your own extension based on that newly released [VSCode Testing API](https://code.visualstudio.com/api/extension-guides/testing)?

The integration of Microsoft software is insane.

**Comment by mxschmitt** [comment]
We just released a first version of it and would be more than happy to get some initial feedback: 

Extension: https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright
Repository: https://github.com/microsoft/playwright-vscode

@scraper @ingvar-nikiforov @Polycapa @Friendseeker
