### ISSUE TITLE
[Bug]: Artifacts have fullpath in allure results

### ISSUE THREAD

**Issue by ingvar-nikiforov** [microsoft/playwright#8079]
### Playwright version

1.13.1

### Operating system

MacOS

### Other information

CI tool

### What happened? / Describe the bug

Bug regarding `experimental-allure-playwright`

Screenshots have full path in allure results json files.

My problem appears in CI. I run tests in docker containers.
After the tests are done the script makes a copy of allure results and screenshots to allure server. Since allure cannot resolve the path the screenshots are not shown in webview.

Source should be local path
```
"attachments": [{
  "name": "screenshot",
  "type": "image/png",
  "source": "/Users/casey/Projects/e2e-tests/test-results/register-fields_validation-Fields-Validation-qa/test-failed-1.png"
}]
```

**Comment by mxschmitt** [comment]
Seems fixed upstream.
