### ISSUE TITLE
[Bug]: with multiple worker and record video may cause test timeout

### ISSUE THREAD

**Issue by houmingjie** [microsoft/playwright#8086]
### Playwright version

1.13.1

### Operating system

MacOS, Linux

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

Take video may cause test timeout.
Step0:
node_modules/@playwright/test/lib/test/index.js  at line 240
```
    const st = Date.now();

    await context.close();

    console.info(`close context cost ${Date.now() - st}`);
```

Step1:
Config :video: 'on' and run my test
```
Running 2 tests using 2 workers
close context cost 6923
close context cost 6343
  Slow test: test.test.js (22s)
  Slow test: test2.test.js (21s)
```
Step2:
Config :video: 'off' and run my test
```
Running 2 tests using 2 workers
close context cost 33
close context cost 28
  2 passed (16s)
```

Seems take video will slow context.close then cause my test timeout.

### Code snippet to reproduce your bug

```shell
const { test, expect } = require('@playwright/test');

test.describe('Customer_Join_Journey_Elec', () => {
    let testData
    test.beforeEach(async({
        page
    }) => {
        await page.goto('https://playwright.dev/');
    });
    test('test1', async({
        page
    }) => {
        const name = await page.innerText('.navbar__title');
        await page.waitForTimeout(10000)
    });
});
```

**Comment by gkushang** [comment]
@houmingjie - I am seeing the Tests slows down by 2x times (2m tests take 4m) when I make `video: 'on'`. Is that something similar you're facing?

**Comment by houmingjie** [comment]
> @houmingjie - I am seeing the Test **Slows Down by 2x times** (2m tests take 4m) when I make `video: 'on'`. Is that something similar you're facing?

Try test more case, it slow down more than 2x times.

**Comment by gkushang** [comment]
It'd be good to have an option during Context Closure so that we can optionally close it without processing videos,

e.g. this would be useful when test Passes and we want to skip the video (currently, it processes all the videos)

```
context.close({ video: false }) // do not process frames
```

**Comment by mxschmitt** [comment]
Linking #8683

**Comment by dgozman** [comment]
We've recently improved video performance for Chromium, it should be live in v1.15 release.
