### ISSUE TITLE
[Feature]: Trace Viewer show error obj preview in console

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#8087]
### Feature request

This feature request is a continuation of #7993.

**Trace Viewer**:
![console](https://user-images.githubusercontent.com/22205721/128658922-8f7ef818-abcc-4996-a52f-27ed7c6dc449.png)

**DevTools**:
```
t {headers: e, status: 422, statusText: "OK", url: "https://test-api.test.com/mass_shopping_session", ok: false, …} main.3bad21394a6ab3dae858.js:1 
```
which can further be expanded to view (This is probably a stretch goal and not necessarily required. Maybe the error property can be included):
```
  error: {code: 999, data: null, errors: Array(1), message: "Unknown error", status_code: 422, …}
  headers: e {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}
  message: "Http failure response for https://test-api.test.com/mass_shopping_session: 422 OK"
  name: "HttpErrorResponse"
  ok: false
  status: 422
  statusText: "OK"
  url: "https://test-api.test.com/mass_shopping_session"
```

Before:
Currently, in Trace Viewer -> Console tab, if the error is an Object then it is not displayed

After:
Trace Viewer -> Console tab, the error Obj is displayed as a preview

**Comment by pavelfeldman** [comment]
Lowering the priority of this one for now, will collect reports.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
