### ISSUE TITLE
[Question]: Is there a way to dump the whole dom tree?

### ISSUE THREAD

**Issue by ntcmp2u** [microsoft/playwright#8088]
### Your question

Is there a way to access the whole dom tree like ``google-chrome --headless --dump-dom`` after ``page.goto()``?

**Comment by aslushnikov** [comment]
@ntcmp2u there's no buit-in solution, but you can easily DIY one using `page.evaluate()` and some DOM API, e.g. [`TreeWalker`](https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker) API or just `element.children`.

A very crude and simple one would be:

```js
const { chromium } = require('playwright');

async function main() {
  const browser = await chromium.launch({channel: 'chrome'});
  const page = await browser.newPage();
  await page.goto('https://aslushnikov.com');
  console.log(JSON.stringify(await page.evaluate(() => {
    return (function dfs(element) {
      return {
        [element.tagName]: [...element.children].map(dfs),
      };
    })(document.body);
  }), null, 2));
  await browser.close();
}

main()
```
