### ISSUE TITLE
[Question]: Timeout on PlaywrightTestConfig (version 1.13+)

### ISSUE THREAD

**Issue by hungdpham93** [microsoft/playwright#8089]
### Your question

My team is upgrading Playwright from 1.12.1 to 1.13.1 and we experienced a "strange" behavior regarding timeout.

**Context**
Most of our E2E tests take more than one minute to run. In order to set a timeout for a test, we use the configuration `timeout` in `PlaywrightTestConfig` and set it to 5 minutes.
```
const config: PlaywrightTestConfig = {
    testDir: 'src/tests',
    timeout: 5 * 60 * 1000, 
    globalTimeout: 60 * 60 * 1000,
};
```
In Playwright 1.12.1, it seems that the timeout on element actions (ie. `page.click`) is set to 30 seconds by default and it doesn't share the timeout in `PlaywrightTestConfig`.
For the tests that fail because of the element is not attached to the DOM, our test waits for 30 seconds then fails.
```
test('Timeout test', async ({ page }) => {
    await page.click('invalid-selector');
});
```

**Playwright 1.12.1**
The test fails 30 seconds after it cannot find the element within the DOM.
```
 page.click: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector "invalid-selector"
    ============================================================
    Note: use DEBUG=pw:api environment variable to capture Playwright logs.
```

**Playwright 1.13.1**
It takes 5 minutes (the timeout that I set in `PlaywrightTestConfig`) to fail the test - which is too much time to wait.
```
Timeout of 300000ms exceeded.

    Pending operations:
      -  at <unknown>
      - page.click at src\tests\test.spec.ts:18:16

    page.click: Protocol error (Runtime.callFunctionOn): Target closed.
    =========================== logs ===========================
    waiting for selector "invalid-selector"
    ============================================================

```

My question is whether this behavior is intentional? If the answer is yes, how can we separate the timeout in `PlaywrightTestConfig` (maximum time for a test to run) and the timeout to locate an element in the DOM?

We do want to upgrade to 1.13.1 to use some new functionalities (like the method inputValue()) but it causes a significant increase of run time so we had to stick with 1.12.1.

**Comment by aslushnikov** [comment]
@hungdpham93 in the upcoming 1.14 release, you'll be able to set actions timeout separately with an [`actionTimeout`](https://playwright.dev/docs/next/api/class-fixtures#fixtures-action-timeout) fixture.

You can try it right now with our canary version of Playwright Test (installable via `npm i @playwright/test@next`).

The configuration will need to be like this:
```ts
const config: PlaywrightTestConfig = {
    testDir: 'src/tests',
    timeout: 5 * 60 * 1000, 
    globalTimeout: 60 * 60 * 1000,
    use: {
      actionTimeout: 30 * 1000, // 30 seconds for action
    },
};
```

**Comment by hungdpham93** [comment]
Thanks for your clarification. We look forward to the release of v1.14.
