### ISSUE TITLE
[Question]: Is there a way to check which page/tab is currently active/visible on a given context ?

### ISSUE THREAD

**Issue by sandratreneska** [microsoft/playwright#8090]
### Your question

Hello,

In a multi-page scenario I need to find which page/tab is currently active/visible on a given context. In my application, a user can (non-programmatically) click on or open new tabs, and I need to know what is the currently opened (visible) tab.

**Comment by aslushnikov** [comment]
>  In my application, a user can (non-programmatically) click on or open new tabs, and I need to know what is the currently opened (visible) tab.

This is not a scenario that we support right now - we focus on testing / webautomation. 

> In a multi-page scenario I need to find which page/tab is currently active/visible on a given context. 

In playwright-controlled browser, all pages are "focused" - so that's probably not what you want.
