### ISSUE TITLE
[Bug]: Chromium doesn't render avif image when lazy/async

### ISSUE THREAD

**Issue by ThewBear** [microsoft/playwright#8094]
### Playwright version

1.13.1

### Operating system

Windows, Linux

### What browsers are you seeing the problem on?

Chromium

### Other information

Node.js 14 and Node.js 16

### What happened? / Describe the bug

All of the screenshots below were captured on Chromium.

These websites cannot render **avif** images with `loading=lazy` and `decoding=async`:
https://fantinel.dev/web-images-modern-formats/
![fantinel.dev](https://user-images.githubusercontent.com/26767607/128731319-e92457cb-bc32-4a54-aa6b-bb9c17313b6e.png)
https://www.thewdhanat.com/blog/how-to-use-local-fonts-in-google-docs-sheets-slides/
![thewdhanat.com](https://user-images.githubusercontent.com/26767607/128731464-0e246f2d-ca62-4a9b-90ac-a949a42d36db.png)

When I am trying to get a screenshot, the avif images are not rendered, alt text are shown instead.

I have tried Firefox and they are rendered properly. Moreover, the webp/jpeg images are rendered properly on Chromium even with  `loading=lazy` and `decoding=async`.

This [AVIF Support Test](https://avif-support-test.glitch.me/) website can render avif without `loading=lazy` or `decoding=async`.
![avif-support-test.glitch.me](https://user-images.githubusercontent.com/26767607/128731739-207c6192-d877-4ef8-a3c3-5fb200e52f21.png)

I'm not sure whether this is an upstream chromium bug or related to playwright.

### Code snippet to reproduce your bug

```shell
const { chromium } = require("playwright");

async function main() {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  # Just change the below url.
  await page.goto("https://avif-support-test.glitch.me/");
  await page.waitForTimeout(3000);
  await page.screenshot({ path: "test.png" });
  await browser.close();
  process.exit(0);
}

main()
```

**Comment by ThewBear** [comment]
Might be related to
- crbug.com/1198455
- https://github.com/lovell/sharp/issues/2666

I checked the images from the first two sites with https://gpac.github.io/ComplianceWarden-wasm/avif.html and found `pixi` errors.

My current workaround is intercepting the browser request to load other formats instead.
```js
context.route(/\.avif$/, (route) => {
  const url = route.request().url();
  route.continue({ url: url.substr(0, url.length - 5) + ".webp" });
});
```

**Comment by aslushnikov** [comment]
Yes, looks like an upstream bug. You can always use stable chrome channel, e.g. the following works right now for me:

```js
const { chromium } = require("playwright");

async function main() {
  // note the "channel" argument here!
  const browser = await chromium.launch({channel: 'chrome'});
  const page = await browser.newPage();
  await page.goto("https://avif-support-test.glitch.me/");
  await page.waitForTimeout(3000);
  await page.screenshot({ path: "test.png" });
  await browser.close();
}

main()

```

I'll close this for now since there's nothing to do on our side.
