### ISSUE TITLE
trace-viewer doesn't show formatted (main screen) 

### ISSUE THREAD

**Issue by emakaay** [microsoft/playwright#8095]
### Playwright version

1.13.1

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

nodejs 14.1
windows 8
robotframework 4.1
robotframework-browser 7.0.0 (using playwright 1.13.1)

### What happened? / Describe the bug

I created a script to create a trace with the below robot script. after getting to the trace it shows the following screen
![image](https://user-images.githubusercontent.com/72747481/128731393-a5b8d864-7578-4e18-9580-48cb0acb5e99.png)

What's strange about this screen, that the main screen doesn't contain any formatting. It looks like CSS is completely ignored. And the red dot indicating what has been pressed (the whole reason for this test), is not pointing to a clickable element.

I have seen this behavior in different versions of robotframework-browser (at least 6.0.0 and 7.0.0) which used playwright 1.12.3 and 1.13.1 (I think).

The first test I did using traces was in a corporate environment, and I thought that caused this problem. But now I can reproduce this problem on a private laptop, which has no limits.

Any reasons why it doesn't show formatted screens (but is does in the timeline) ?
I already created an issue with the robotframework-browser team, but they directed me here.
I would assume playwright trace viewer works as depicted in following [youtube](https://www.youtube.com/watch?v=Zutt7N6VvcU) clip. Which seems awesome

### Code snippet to reproduce your bug

```shell
*** Settings ***
Library  Browser

*** Test Cases ***
Enable Tracing To File
    New Browser  chromium    headless=false
    New Context    tracing=trace.zip
    New Page    https://duckduckgo.com/
	
    Fill Text  id=search_form_input_homepage    tweakers.net
    Click    id=search_button_homepage
    Close Context
```

**Comment by aslushnikov** [comment]
I can reproduce with the following script:

```js
const {chromium} = require('playwright');
const path = require('path');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  await context.tracing.start({snapshots: true, screenshots: true});
  const page = await context.newPage();
  await page.goto('https://duckduckgo.com/');
  await page.fill('id=search_form_input_homepage', 'tweakers.net');
  await page.click('id=search_button_homepage');
  await context.tracing.stop({path: path.join(__dirname, 'tt.zip')});
  await browser.close();
})();
```

and by opening trace with:

```sh
npx playwright show-trace ./tt.zip
```
