### ISSUE TITLE
[Question]: How to create promise in playwright.

### ISSUE THREAD

**Issue by Lakshmi-Yaswanth** [microsoft/playwright#8096]
### Your question

In protarctor we have
`var deferred = protractor.promise.defer();
var promise = deferred.promise;`

In playwright is there anyway can create promise.
Thank u in advance

**Comment by aslushnikov** [comment]
@Lakshmi-Yaswanth Playwright is just a node.js library, so you can do all the things you can do in a regular node.js program.

A simple polyfil to make exactly the same API would be this:

```js
function createDeferred() {
  let fulfill, reject;
  const promise = new Promise((a, b) => {
    fulfill = a;
    reject = b;
  });
  return {promise, fulfill, reject};
}
```

and then you can do exactly the same thing:

```js
var deferred = createDeferred();
var promise = deferred.promise;
```
