### ISSUE TITLE
[Bug]: NaCl helper error when launching Chromium on linux

### ISSUE THREAD

**Issue by chargreezy** [microsoft/playwright#8098]
### Playwright version

1.13.1

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

When attempting to run tests using `npx playwright test` or running codegen `npx playwright codegen` chrome will fail to open and dump an error:

`Failed to open NaCl IRT file "/home/me/.cache/ms-playwright/chromium-901522/chrome-linux/nacl_irt_x86_64.nexe`

Attempting to launch chromium directly from the playwright cache with all the flags will also lead to this error as well as

`ERROR:devtools_pipe_handler.cc(231)] Could not write into pipe`

I'm able to launch firefox without problems so this seems to be a chromium specific error. It's launched with these flags:

```
 /home/me/.cache/ms-playwright/chromium-901522/chrome-linux/chrome 
--disable-background-networking 
--enable-features=NetworkService,NetworkServiceInProcess 
--disable-background-timer-throttling 
--disable-backgrounding-occluded-windows 
--disable-breakpad 
--disable-client-side-phishing-detection 
--disable-component-extensions-with-background-pages 
--disable-default-apps 
--disable-dev-shm-usage 
--disable-extensions -
-disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose 
--allow-pre-commit-input 
--disable-hang-monitor 
--disable-ipc-flooding-protection 
--disable-popup-blocking 
--disable-prompt-on-repost 
--disable-renderer-backgrounding 
--disable-sync --force-color-profile=srgb 
--metrics-recording-only 
--no-first-run 
--enable-automation 
--password-store=basic 
--use-mock-keychain 
--no-service-autorun 
--user-data-dir=/tmp/playwright_chromiumdev_profile-90z9KD 
--remote-debugging-pipe 
--no-sandbox 
--no-startup-window
```

If I launch Chromium 92.0.4515.131 with these flags it does not crash but it logs `ERROR:devtools_pipe_handler.cc(231)] Could not write into pipe` I also tried with Chromium 94.0.4603.0 snapshot and it's much the same.

I'm also aware that this could be a Chromium issue and not a playwright issue! But anything to point me in the right direction would be much appreciated. I love using playwright and I'm not sure what has caused this to start happening.

**Comment by aslushnikov** [comment]
@chargreezy which linux distribution is this?

**Comment by chargreezy** [comment]
Arch Linux 5.13.8-arch1-1

**Comment by aslushnikov** [comment]
Ah! I think webkit doesn't run on Arch linux too. We don't support Arch linux at all at the moment - i just filed a tracking bug for this: https://github.com/microsoft/playwright/issues/8100 

Feel free to upvote that one!
