### ISSUE TITLE
[Feature] Proxy options support?

### ISSUE THREAD

**Issue by und3fined** [microsoft/playwright#810]
Hi team,

Currently, with *Chrome* i'm use a argument `--proxy-server` for change proxy 

But in *Firefox*, no any options for it, can find it in [command line options](https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options)

Answer from [here](https://askubuntu.com/questions/23117/configuring-firefox-to-use-a-proxy-from-the-command-line) can't help me

**Comment by yury-s** [comment]
Thanks for your report! Some extra work needs to be done to support proxy settings in Firefox and WebKit (see #787), we'll look into this.

**Comment by aslushnikov** [comment]
Firefox uses [preferences](https://ffsearch.azurewebsites.net/#line=3278&path=%2Fhome%2Fjoe%2Ffirefox%2Fbrowser%2Fcomponents%2FBrowserGlue.jsm&search=prefs.*proxy) instead of command-line flags. We'll need to have launcher proxy options so that we can support http proxy in the same way across browsers.

**Comment by MeiK2333** [comment]
Firefox configures proxy-related settings via user.js, so you can set Firefox's proxy by specifying `userDataDir`.

However, as with the problem in #1349, the method provided by playwright does not provide us with a browser object, so I used the private method.

```node
const firefoxUserJs = `
user_pref("security.cert_pinning.enforcement_level", 0);
user_pref("security.tls.version.min", 1);
user_pref("network.stricttransportsecurity.preloadlist", false);
user_pref("network.proxy.type", 1);
user_pref("network.proxy.share_proxy_settings", true);
user_pref("network.proxy.http", "127.0.0.1");
user_pref("network.proxy.http_port", 7890);
user_pref("network.proxy.ssl", "127.0.0.1");
user_pref("network.proxy.ssl_port", 7890);
`;
const userDataDir = await mkdtempAsync(path.join(os.tmpdir(), 'playwright_dev_firefox_profile-'));
await writeFileAsync(path.join(userDataDir, "./user.js"), firefoxUserJs);
//@ts-ignore
const browser = await playwright.firefox._launchServer({
  headless: false
}, 'server', userDataDir);
```
Note that the `_launchServer` function, which is a private method, may vary in different versions, I am using ^0.12.1 and in version 0.13 it needs to be added `.browserServer` at the end.

**Comment by MeiK2333** [comment]
Also, [here](https://github.com/microsoft/playwright/issues/787#issuecomment-612867176) is how webkit uses proxies.

**Comment by und3fined** [comment]
i'm patch to `playwright.cfg` in firefox browser :)

**Comment by YindSoft** [comment]
> Firefox configures proxy-related settings via user.js, so you can set Firefox's proxy by specifying `userDataDir`.
> 
> However, as with the problem in #1349, the method provided by playwright does not provide us with a browser object, so I used the private method.
> 
> ```js
> const firefoxUserJs = `
> user_pref("security.cert_pinning.enforcement_level", 0);
> user_pref("security.tls.version.min", 1);
> user_pref("network.stricttransportsecurity.preloadlist", false);
> user_pref("network.proxy.type", 1);
> user_pref("network.proxy.share_proxy_settings", true);
> user_pref("network.proxy.http", "127.0.0.1");
> user_pref("network.proxy.http_port", 7890);
> user_pref("network.proxy.ssl", "127.0.0.1");
> user_pref("network.proxy.ssl_port", 7890);
> `;
> const userDataDir = await mkdtempAsync(path.join(os.tmpdir(), 'playwright_dev_firefox_profile-'));
> await writeFileAsync(path.join(userDataDir, "./user.js"), firefoxUserJs);
> //@ts-ignore
> const browser = await playwright.firefox._launchServer({
>   headless: false
> }, 'server', userDataDir);
> ```
> 
> Note that the `_launchServer` function, which is a private method, may vary in different versions, I am using ^0.12.1 and in version 0.13 it needs to be added `.browserServer` at the end.

The problem here is how do I set authorization for the proxy?

**Comment by MeiK2333** [comment]
@YindSoft

```javascript
const context = await browser.newContext({
  httpCredentials: {
    username: `username`,
    password: `password`
  }
});
const page = await context.newPage();
// You code
// ......
```

But, this method does not support access to pages that require authentication, so if you have such a need, consider using https://github.com/apifytech/proxy-chain

**Comment by Anthony-Janin** [comment]
proxy url + user proxy + proxy chain:
Doesn't work with browserless io...

**Comment by pavelfeldman** [comment]
Proxy settings now work across browsers: https://playwright.dev/#version=v1.1.1&path=docs%2Fapi.md&q=browsertypelaunchoptions--options-proxy

**Comment by heyt0ny** [comment]
Is it possible to change proxy on already initialised browser instance?

**Comment by Nisthar** [comment]
@heyt0ny +1

**Comment by hubba-bubba-776** [comment]
@Nisthar you can initialise different contexts for the same browser instance and pass different proxies to each one

**Comment by dpgraham** [comment]
The link provided on Jun 28th is broken. Here's an updated link: https://playwright.dev/docs/api/class-browsertype?_highlight=launch#browsertypelaunchoptions
