### ISSUE TITLE
[Question]: using regex in attributes

### ISSUE THREAD

**Issue by worldomonation** [microsoft/playwright#8101]
### Your question

👋 I have a question about using regex.

Say there is an element on page as follows:

```
<img .... data-permalink="2021-08-09/hello-world.png">
```

I would like to use regex to match the element like this:

```
await page.waitForSelector( 'img[data-permalink="/*world*/i"' );
```

However when I try using regex in the Playwright debugger it does not appear to match anything, unfortunately.
Question: is this possible? If not, is this something that may be on the roadmap?

---

Background: in my use case, I am attempting to verify that a file upload has taken place as expected. I have only the file name to work with, and the file name is added as an attribute to the resulting `<img>` element.
The caveat is that the attribute holding the file name can possibly not match the actual file name 100%, due to sanitization as well as duplicate existing file resulting in something like this possibly happening:

```
2021-08-09/hello-world-1.png
```

Now, I realize I can wait for the `<img>` element, then extract the `data-permalink` attribute from the resulting ElementHandle, then check if it contains `world`, but that is a bit tedious.

Thanks!

**Comment by aslushnikov** [comment]
@worldomonation you can use attribute css selectors to match by substring, even case-insensetively! Notice `*=` instead of `=` and trailing `i`:

```js
await page.waitForSelector( 'img[data-permalink*="world" i]' );
```

More on attribute selectors: [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors)

**Comment by worldomonation** [comment]
> @worldomonation you can use attribute css selectors to match by substring, even case-insensetively! Notice `*=` instead of `=` and trailing `i`:
> 
> ```js
> await page.waitForSelector( 'img[data-permalink*="world" i]' );
> ```
> 
> More on attribute selectors: [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors)

Thanks. I thought this might be the case. Appreciate your reply!
