### ISSUE TITLE
[Bug]:  Fails visibility checks

### ISSUE THREAD

**Issue by sjurgis** [microsoft/playwright#8108]
### Playwright version

1.13.1

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium

### Other information

```
        "expect-playwright": "^0.7.2",
        "jest-playwright-preset": "^1.7.0",
        "playwright-chromium": "^1.13.1",
        "jest": "^27.0.6",
```

### What happened? / Describe the bug

I'm using Salesforce's lwc (lightning web components) to render some components and then hide them using css. Whenever I try to click on something that has duplicate, but hidden, playwright fails to with error below. It works fine when using simple local file, but fails in lwc.

Please ignore the iframe part, that's just how webcomponents.dev wraps lwc's.

### Code snippet to reproduce your bug

```shell
describe('my simple file', () => {
    beforeAll(async () => {
        await page.goto(`https://webcomponents.dev/preview/MYiM2ZRhLzFC22xLHesM/`);
        await page.waitForTimeout(35 * 1000)
        const handle = await page.$$('iframe');
        const contentFrame = await handle[0].contentFrame();
        await contentFrame.click(`//span[@title="Group 2"]`)
        await contentFrame.click(`//button[@title="aaa"]`)
    }, 2 * 60 * 1000)
    it( 'has one visible element', async () =>{
        // await expect(page).toHaveSelector(`//div//span[text()='imma']`)
    })
})
```

### Relevant log output

```shell
frame.click: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector "//button[@title="aaa"]"
      selector resolved to 2 elements. Proceeding with the first one.
      selector resolved to hidden <button title="aaa">aa</button>
    attempting click action
      waiting for element to be visible, enabled and stable
        element is not visible - waiting...
```

**Comment by aslushnikov** [comment]
@sjurgis can you please [record a trace](https://playwright.dev/docs/api/class-tracing) and attach it here?

**Comment by sjurgis** [comment]
here it is @aslushnikov [trace.zip](https://github.com/microsoft/playwright/files/6979447/trace.zip)

**Comment by sjurgis** [comment]
@aslushnikov does it help at all?

**Comment by pavelfeldman** [comment]
Sorry about the delay.

> Whenever I try to click on something that has duplicate, but hidden, playwright fails to with error below.

Yeah, that's by design though. You can add :visible to your selector or use Playwright 1.14 and append `>> visible=true` to your selector to make sure that you are interested in the visible element. Otherwise, Playwright picks the first (hidden) element and waits for it to become visible.

**Comment by sjurgis** [comment]
Thanks that solved it
