### ISSUE TITLE
[Feature] DOM Snapshot Testing

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#8113]
I'd like to author tests like

```
expect(await page.domSnapshot()).toMatchSnapshot()
```

where the snapshot serializes to a format similar to Chrome DevTools' Inspect > Elements
tab (which, presentationally, inlines all iframes—including OOPIFs—and adds pseudo elements).

I'd imagine `page.domSnapshot()` to have signature `Promise<playwright.DOMSnapshot>` where `DOMSnapshot` has
a `toString()` or `prettyPrint()` to get the pretty printed document (that looks like Chrome DevTools)
while `DOMSnapshot` itself maintains a walkable tree structure.

NB: The snapshot is a snapshot in time of the DOM and should not hold handles
back into the browser.

I attempted to create such a thing in user-land using DOM.getDocument CDP command
with `pierce = true` and `depth = -1` (no depth limit, IIRC), but OOPIFs were
missed. While you get the OOPIF node, it doesn't have a contentDocument (like
in process frames); it does have a frameId, but I could not find a way to take
this frameId and invoke DOM.getDocument on it recusively via the CDP functionality
expose by Playwright. (I was going to "hydrate" the missing contentDocument's for
the OOPIFs.)

Please let me know your thoughts and I'd be happy to collaborate on a PR!

Follow up from: https://playwright.slack.com/archives/CSUHZPVLM/p1628544879250600

**Comment by rwoll** [comment]
Going to close this as I found tests with these turned out to be less useful than Image/Screenshot based snapshots, and more susceptible to breakage and maintenance overhead.

**Comment by p01** [comment]
By themselves, DOM + CSS snapshot are too noisy, but they are extremely valuable to understand the reason behind visual changes.

**Comment by dgozman** [comment]
@p01 Did you try [Playwright traces](https://playwright.dev/docs/trace-viewer)? They include DOM snapshots for exactly this reason.

**Comment by p01** [comment]
Oh! Of course! Thanks @dgozman 

Reading the docs, my initial thinking is to use [tracing.startChunk(...)](https://playwright.dev/docs/api/class-tracing#tracing-start-chunk) to get a trace as small as possible right around the calls to `page.screenshot(...)` to easily associate the traces and screenshots together.

Or does that sound like a wrong approach ?

**Comment by dgozman** [comment]
@p01 You could try that, but check the trace size to make sure it helps. You can also play with enabling/disabling screenshots.

**Comment by Tallyb** [comment]
I think this might be helpful for visual comparison tools. E.g. Percy is not really capable of doing this correctly itself. Visual comparison tools bring a lot of benefit in managing the full workflow of visual comparison: storing all images, comparing branches, approval and denial of screenshots, merging branches etc.
