### ISSUE TITLE
[BUG] "empty" trace.zip is generated

### ISSUE THREAD

**Issue by digio-peterbaldwin** [microsoft/playwright#8133]
**Context:**
- Playwright Version: 1.13.1
- Operating System: Linux
- Node.js version: 14.17.2
- Browser: Chromium
- Extra: Playwright is executing inside Docker Container "mcr.microsoft.com/playwright"; invoked by the following Buildkite Step:

> - label: ":playwright: E2E test"
>     agents:
>       ...
>     command:
>       - "aws s3 cp s3://nib-shared-artifacts/.npmrc - > .npmrc"
>       - "docker run -it -v $(pwd):/tmp -w /tmp mcr.microsoft.com/playwright /bin/bash -c 'npm install'"
>       - "docker run -it -v $(pwd):/tmp -w /tmp mcr.microsoft.com/playwright /bin/bash -c 'npm run test:e2e'"
>     artifact_paths:
>       - "/tmp/test-results/**/trace.zip"
>       - "test-results/**/trace.zip" 

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```playwright.config.js
module.exports = {
  use: {
    // Browser options
    headless: true,
    slowMo: 200,

    // Context options
    ignoreHTTPSErrors: true,

    // Artifacts
    screenshot: "only-on-failure",
    video: "retry-with-video",
    trace: "on",
  },

  projects: [
    {
      name: "Default - iPhone browser",
      use: {
        browserName: "webkit",
      },
    },
    {
      name: "Samsung browser",
      use: {
        browserName: "chromium",
        ...devices["Galaxy S9+"],
      },
    },
  ],
};
```

```Playwright test
const { test, expect } = require("@playwright/test");
const { format } = require("date-fns");

test("basic test", async ({ page }, workerInfo) => {
  await page.goto("https://playwright.dev/");
  const name = await page.innerText(".navbar__title");
  expect(name).toBe("Playwright");
});
```

**Description of the bug**

1. download the `trace.zip` artifact (from Buildkite)
2. open the Trace by invoking `npx playwright show-trace ./trace.zip`
3. the window of the Trace tool displays nothing. Ie. there is no content in the window (as shown in screenshot)
![Screen Shot 2021-08-11 at 11 32 23 am](https://user-images.githubusercontent.com/86395294/128956150-17263f20-e60e-49b5-b303-83b71fea4654.png)
.

**Comment by aslushnikov** [comment]
@digio-peterbaldwin can you please attach this trace file here?

**Comment by digio-peterbaldwin** [comment]
> @digio-peterbaldwin can you please attach this trace file here?

[trace.zip](https://github.com/microsoft/playwright/files/6971808/trace.zip)

**Comment by aslushnikov** [comment]
@digio-peterbaldwin Hm, so it is empty indeed. 

Then we'll need a good repro. I just tried your `test.spec.js` with `playwright.config.js`, and noticed that you missed the `devices` import in the config. 

Here are the things I tried:

<details>
  <summary>
  <code>playwright.config.js</code>
</summary>

```js
const {devices} = require('@playwright/test');

module.exports = {
  use: {
    // Browser options
    headless: true,
    slowMo: 200,

    // Context options
    ignoreHTTPSErrors: true,

    // Artifacts
    screenshot: "only-on-failure",
    video: "retry-with-video",
    trace: "on",
  },

  projects: [
    {
      name: "Default - iPhone browser",
      use: {
        browserName: "webkit",
      },
    },
    {
      name: "Samsung browser",
      use: {
        browserName: "chromium",
        ...devices["Galaxy S9+"],
      },
    },
  ],
};
```

</details>

<details>
  <summary>
  <code>test.spec.js</code>
</summary>

```js
const { test, expect } = require("@playwright/test");
const { format } = require("date-fns");

test("basic test", async ({ page }, workerInfo) => {
  await page.goto("https://playwright.dev/");
  const name = await page.innerText(".navbar__title");
  expect(name).toBe("Playwright");
});
```

</details>

I put this files in `tmp` folder and ran the following:

```sh
$ npm init -y
$ npm i @playwright/test
$ npm i date-fns
$ npx playwright test
```

And it worked. I ended up with 2 nice traces in the `test-results/` folder. 
Can you please try exactly these steps and tell me if they fail for you?

**Comment by digio-peterbaldwin** [comment]
These steps (that you requested) have been executed. The result is two nice traces of the test. I will investigate further what is the key to reproducing this issue.

**Comment by pavelfeldman** [comment]
Is this now resolved? Please open a new issue and link this one if your investigation yields some interesting results!
