### ISSUE TITLE
[BUG] Trace viewer, can not loaded image in snapshot

### ISSUE THREAD

**Issue by vctqs1** [microsoft/playwright#8134]
**Context:**
- Playwright Version:1.13.0 
- Operating System:Linux
- Node.js version: 12.20.0
- Browser: Chromium
- Extra: Snapshot can not load image

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript

(async () => {

        const browser = await chromium.launch({
            headless: this.headless,
            timeout: 10000,
            channel: 'chrome',
            args: ['--unlimited-storage', '--full-memory-crash-report'],
        });

        const contextOptions: BrowserContextOptions = {
            acceptDownloads: true,
            permissions: ['camera', 'microphone', 'notifications'],
            viewport: { width: 1280, height: 720 },
            baseURL: this.origin,
        };
        const context: BrowserContext = await browser.newContext(contextOptions);
        this.context = context;

       //start tracing viewer
        return await this.context?.tracing.start({
            screenshots: true,
            snapshots: true,
            name: this.driverName,
        });

        const page: Page = await context.newPage();

        await this.waitForConnection(options.origin);
        await page.goto(options.origin, {
            waitUntil: 'networkidle',
        });
       // login into app       

       page.goto('/tab?tab_name=todos');

       //stop tracing viewer
        return await this.context?.tracing.stop({
            path: pathTraceView,
        });


})();
```

**Describe the bug**

Add any other details about the problem here.
Cannot load the image in a snapshot and text in button
![image](https://user-images.githubusercontent.com/30227910/128974228-a3849370-cf6c-47be-bcd9-348a929563ce.png)
![image](https://user-images.githubusercontent.com/30227910/128975569-765bc123-cdc6-4154-abb6-dabac78a5143.png)

**Expected**
Snapshot should be like screenshot 
![image](https://user-images.githubusercontent.com/30227910/128975579-bb506e65-8185-4f6f-b2c9-5ab3f7a44003.png)

**Comment by aslushnikov** [comment]
@vctqs1 can you please attach your trace file here?

**Comment by vctqs1** [comment]
@aslushnikov here. could you help take a look
[learner_1.zip](https://github.com/microsoft/playwright/files/6980027/learner_1.zip)

**Comment by pavelfeldman** [comment]
Looks like we have a problem with blob urls.
