### ISSUE TITLE
[BUG] page.goto doesn't handle onbeforeunload popup on Chromium and Webkit

### ISSUE THREAD

**Issue by yongjik** [microsoft/playwright#8144]
**Context:**
- Playwright Version: 1.13.1
- Operating System: Linux
- Node.js version: 15.8.0
- Browser: Chromium & Webkit
- Extra: Ubuntu 20.04

**Code Snippet**

```javascript
const { chromium, firefox, webkit } = require('playwright');

(async () => {
    const browser = await chromium.launch();
    // const browser = await webkit.launch({headless: false});
    const page = await browser.newPage();
    await page.goto('file:///' + __dirname + '/pwtest.html');
    await page.waitForSelector('div');
    await page.goto('about:blank');
    await browser.close();
})();
```

pwtest.html contains the following:

```html
<html><head><title>page.goto() test</title>
<script>
function onload() {
    window.onbeforeunload = () => 'Are you sure?';
    document.querySelector('body').innerHTML = '<div>Loaded!</div>';
}
</script>
</head><body onload="onload();"></body></html>
```

**Describe the bug**

When I call `page.goto()` and the page I'm leaving has beforeunload ("Do you really want to leave?") popup enabled, playwright fails to handle it on Chromium and Webkit.  On Chromium, it fails with the following cryptic error message:

```
node:internal/process/promises:227
          triggerUncaughtException(err, true /* fromPromise */);
          ^

page.goto: net::ERR_ABORTED at about:blank
=========================== logs ===========================
navigating to "about:blank", waiting until "load"
============================================================
    at /home/yongjik/.../pwtest2.js:9:16 {
  name: 'Error'
}
```

Meanwhile, on Webkit, the page is stuck in "Are you sure?" popup - and it won't proceed even if I click "Leave Page".

Not sure why, but on Webkit, if I change the second URL from `about:blank` to `www.google.com` then it starts working.  Loading a different (or the same!) local file doesn't work, so it might have something to do with domain name.  (Doesn't work on Chromium, though.)

**Comment by pavelfeldman** [comment]
This looks like a bug. For now you can use https://playwright.dev/docs/api/class-page#page-close-option-run-before-unload to test beforeunload.
