### ISSUE TITLE
[BUG] page.waitForNavigation: net::ERR_ABORTED; maybe frame was detached? when headless is false

### ISSUE THREAD

**Issue by naknode** [microsoft/playwright#8145]
**Context:**
- Playwright Version: 1.13.1
- Operating System: macOS Catalina 10.15.7
- Node.js version: 14.16.1
- Browser: Chromium

## System:
 - OS: macOS 10.15.7
 - Memory: 5.40 GB / 32.00 GB
## Binaries:
 - Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
 - npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
## npmPackages:
 - playwright: ^1.12.3 => 1.13.1 

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
test.only('Can we export the report into a PDF?', async ({ page }) => {
  const [popup] = await Promise.all([page.waitForEvent('popup'), page.click(`button:has-text("Export to PDF")`)]);

  await popup.waitForNavigation({
    waitUntil: 'networkidle',
    timeout: 5000
  });

  expect(popup.url().startsWith('blob')).toBeTruthy();

  popup.close();
});

```

So, when this runs in `headless = false` (showing browser) this works OKAY. However, in CI/CD land... we'll turn headless off and we get this error:

```
  1) reports/main-report.spec.ts:27:6 › Can we export the report into a PDF? =================

    page.waitForNavigation: net::ERR_ABORTED; maybe frame was detached?
    =========================== logs ===========================
    waiting for navigation until "load"
    ============================================================

    > 32 |   await popup.waitForNavigation({
         |               ^
      33 |     waitUntil: 'load',
      34 |     timeout: 5000
      35 |   });
```

I've tried with all three states: `load`, `domcontentloaded`, and `networkidle`. Same error.

**Comment by aslushnikov** [comment]
@naknode First of all, it's important to know that Chromium's PDF behavior is different in headless and headful modes: #6342

So this might be the root cause. Otherwise, it's hard to say anything without a good repro that we can run locally to debug this.

**Comment by pavelfeldman** [comment]
Unfortunately, we don't have enough information to act on this one. Please file a new issue and link this one if you have a reproduction for us!

**Comment by robotic1** [comment]
Using chromium headless you have a different behavior and often generate errors even in situations other than the one mentioned.
Errors do not occur when using firefox or webkit.
I have noticed that firefox and webkit behave equally both headless and non-headless.
example
const browser = await playwright.firefox.launch ({headless: true});
const context = await browser.newContext ({});
const page = await context.newPage ();
