### ISSUE TITLE
[BUG] Browser / BrowserContext split is confusing

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#816]
Consider the snippet:

```js
const { chromium } = require('playwright');

(async () => {
  // Why is |headless| set on launch level?
  const browser = await chromium.launch({ headless: false });
  // What is BrowserContext?
  // What is BrowserContext? Why is viewport on the BrowserContext level?
  const context = await browser.newContext({ viewport: null });
  // ...
})();
```

a straw man for addressing the confusion:

```js
const { chromium } = require('playwright');

(async () => {
  const driver = await chromium.launch({ headless: false });
  // Browsers are lightweight and isolated.
  const browser = await driver.newBrowser({ viewport: null });
  // ...
})();
```

**Comment by aesyondu** [comment]
You can also [set viewport on per-page basis](https://github.com/microsoft/playwright/blob/master/docs/api.md#pagesetviewportviewport).

Not arguing for anything, but just to show my (beginner) understanding of the hierarchy based on reading api docs is:
- browser (chromium, firefox, webkit)
- - defaultContext (group of pages, useful for isolating cookies?, grouping headers?)
- - non-defaultContext (opens a new incognito window to group pages)
- - - page (the tab inside the web browser, grouped within a context)
- - - - mainFrame (the default window)
- - - - otherFrames (other iframe???)

**Comment by dgozman** [comment]
Does this mean no `defaultContext`? 🙏

**Comment by hdorgeval** [comment]
Hi @pavelfeldman , as a developer of a fluent API around playwright  (https://github.com/hdorgeval/playwright-controller), my feeling is that the `browserContext` is an implementation detail on how to instantiate a page object from a browser object.

This `browserContext` should be hidden from your API consumers, and the `BrowserContextOptions` should be part of the `LaunchOptions` object:

```js
export declare type LaunchOptions = BrowserArgOptions & {
    executablePath?: string;
    ignoreDefaultArgs?: boolean | string[];
    handleSIGINT?: boolean;
    handleSIGTERM?: boolean;
    handleSIGHUP?: boolean;
    timeout?: number;
    dumpio?: boolean;
    env?: {
        [key: string]: string;
    } | undefined;
    webSocket?: boolean;
    slowMo?: number;
    context: BrowserContextOptions;
};
```

Next point , is that when I launch manually a browser, I got both a browser and a new page in one operation. Your API should reflect this behavior:

```js
const browser = await chromium.launch({ headless: false, context: {viewport: null} });
const page = browser.defaultPage();
```

and when I want to create a new Tab within the current browser:

```js
const newTab = browser.newPage();
```

**Comment by pavelfeldman** [comment]
> This browserContext should be hidden from your API consumers

The idea behind `BrowserContext` is that it is isolated, ephemeral and inexpensive to create. We absolutely need it. Launching browser is expensive, creating browser context is what I do for every test. I filed this bug with the idea of finding a better name for it, not deleting it. If anything, `Browser` might go, but `BrowserContext` needs to stay.

> Next point , is that when I launch manually a browser, I got both a browser and a new page

This is no longer the case!
