### ISSUE TITLE
[Question] Passing variable to :has-text selector

### ISSUE THREAD

**Issue by r1kkk** [microsoft/playwright#8164]
I would like to pass an variable into the has-text selector - is that possible?

Following snippet:

    const questionSetName = await function.generateName()
    await page.fill('input[formcontrolname="name"]', questionSetName)
    await page.click('mat-panel-title:has-text("questionSetName")')

I would like to search for the mat-panel-title with the text saved in the variable questionSetName.

**Comment by aslushnikov** [comment]
@r1kkk selector is just a string! YOu can do it like this:

```js
const questionSetName = await function.generateName()
await page.fill('input[formcontrolname="name"]', questionSetName)
await page.click(`mat-panel-title:has-text(${JSON.stringify(questionSetName)})`)
```

notice backticks and `${}` - these are called [template strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)
