### ISSUE TITLE
On retry test passes but execution fails

### ISSUE THREAD

**Issue by sandeepreddy237** [microsoft/playwright#8175]
Hi there

I have an issue where couple of tests are flaky and i am using retry feature. These tests are run as part CICD deployments and on retry test actually passes but test execution fails. Hence the deployment fails as well 

Is there way i could pass test execution if the test passes on retry?

thanks for help in advance

**Comment by aslushnikov** [comment]
> Is there way i could pass test execution if the test passes on retry?

@sandeepreddy237 What's "test execution"?

**Comment by pavelfeldman** [comment]
Please file a new bug and link this one if you get back to it. The test that passed on retry is considered passed, it should not fail the execution.
