### ISSUE TITLE
How to set baseURL with url parameters?

### ISSUE THREAD

**Issue by Gornostalev** [microsoft/playwright#8181]
Hello, I have url http://localhost:1337/?path=/story/ and i put this value on parameter 'baseURL' in config
and i want when i use ,method page.goto('./page.html')
browser will opened page http://localhost:1337/?path=/story/page.html
but i got http://localhost:1337/page.html
What am I doing wrong?

**Comment by aslushnikov** [comment]
@Gornostalev so the `baseURL` is a URL, and relative paths are resolved according to general URL resolvement rules.

Here's a good explanation how URL's are resolved: https://stackoverflow.com/a/2005174/314883

In general, everything after `?` is not part of the URL path - that's called "query". Relative URLs are resolved wrt URL paths - which is `/` in your case. 

Hope this helps!

**Comment by Gornostalev** [comment]
thank you for answer, i resolve this like that: page.goto(`/?path=/story/ ${pageUrl}`)
