### ISSUE TITLE
[Question] record video only for failed tests

### ISSUE THREAD

**Issue by sir-alex** [microsoft/playwright#8188]
Hello,

my stack:
```
"playwright": "^1.13.1",
"typescript": "4.2.4"
"jest": "26.6.3",
```

I try to use build in video record API from playwright following to
https://playwright.dev/docs/videos

videos are coming and it works as expected

due a limited space I need to record only failed tests or to delete recorded video if test is successfull.

I am following https://playwright.dev/docs/test-configuration#record-video and I use 'on-first-retry' option in config. But unfortunatelly it does not work. Videos are recording for all tests successfull and failed

Mocha has an API with test state failed/success but JEST does not have it from the box and it can be done only with some script in Jasmine. It is a bit not stable. I understand that I can try to use Jasmine features to detect does test success or not and if yes I can get path of created video by page.video().path() and remove this file by node.js in afterEach hook. But I want to believe that this functionality should exist in playwright

thank you for any suggestion

**Comment by aslushnikov** [comment]
@sir-alex please use `retain-on-failure` video option to keep only videos of ffailing tests.

**Comment by pavelfeldman** [comment]
Could you elaborate on the expected behavior? Test fails, then during the retry video is being recorded. Is it that you want to delete video when retry is successful?

**Comment by sir-alex** [comment]
@aslushnikov 
I use JEST as test runner and I have jest.config.js with all params as I mentioned in my original post. 
I run tests as 
`jest sometest.spec.ts`
Do I understand correct that any config settings mentioned in https://playwright.dev/docs/test-configuration/#record-video this is valid only if I use playwright test runner and run tests as 
`playwright sometest.spec.ts`
and in that case I can create playwright.config.ts with 'retain-on-failure' option and it will work but if I use JEST there is not similar settings and there is not way to have the same option for JEST test runner?

**Comment by sir-alex** [comment]
@pavelfeldman 
Sorry, I mentioned 'on-first-retry' in my original post but my main goal is to save video only if test failed. In case of success tests does not matter from which attempt/retry it was marked as success in that case video should be deleted

**Comment by sir-alex** [comment]
and 1 more question: is any plans to add video generation in mp4 format? I see now only webm is supported

**Comment by aslushnikov** [comment]
> Do I understand correct that any config settings mentioned in https://playwright.dev/docs/test-configuration/#record-video this is valid only if I use playwright test runner and run tests as
playwright sometest.spec.ts
and in that case I can create playwright.config.ts with 'retain-on-failure' option and it will work but if I use JEST there is not similar settings and there is not way to have the same option for JEST test runner?

@sir-alex Yes, these are only for Playwright Test

> and 1 more question: is any plan to add video generation in mp4 format? I see now only webm is supported

No, there are no plans for mp4 so far.
