### ISSUE TITLE
[BUG] Await addEventListener() halts Javascript Execution on Playwright build of Chromium

### ISSUE THREAD

**Issue by Friendseeker** [microsoft/playwright#8193]
**Context:**
- Playwright Version: "@playwright/test": "^1.14.0"
- Operating System: Windows 10 19042.1165
- Node.js version: 16.6.2
- Browser: Chromium

**Code Snippet**

```javascript
// root/app.js
async function alertDuration({ target: { files } }) {
    // Load the video in an HTML element
    const video = document.createElement('video')
    video.src = URL.createObjectURL(files[0])
    video.load()

    // Wait for the video to finish loading
    await new Promise(resolve => (video.addEventListener('durationchange', () => resolve())))

    alert(`Video duration is ${video.duration}s`)
    video.remove()
}

document.querySelector('#media-upload').addEventListener('change', alertDuration)

// root/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>
<input type="file" id="media-upload" accept="audio/*,video/*">
<label for="media-upload" id="message">Choose a Clip</label>
<script src="app.js"></script>
</body>
</html>
```

**Describe the bug**

Above code snippet contains an HTML with a button that allows user to select video/audio file, and shows an alert containing the duration of uploaded video/audio.

The snippet works as expected on Chrome and on non-playwright build of Chromium, but for Playwright build of Chromium, app.js reaches ```await new Promise(resolve => (video.addEventListener('durationchange', () => resolve())))``` during execution then stops without any console warning. Lines after are then never executed (e.g. alert).

**Steps to Reproduce**
- Open https://friendseeker.github.io/MRE/ (A GitHub Page hosting the snippet) with Playwright build of Chromium (double click on %USERPROFILE%\AppData\Local\ms-playwright\chromium-907428\chrome-win\chrome.exe)
- Select Choose File to upload a Video/Audio File
- Expected alert do not emerge

**Extra Note**
Identical issue presents in Playwright Chromium 901522 & Playwright 1.13.1

**Comment by pavelfeldman** [comment]
Without running this, I would guess that alert blocks the execution. Try replacing it with console.log?

**Comment by Friendseeker** [comment]
> 
> 
> Without running this, I would guess that alert blocks the execution. Try replacing it with console.log?

I quickly [added console.log between await and alert](https://github.com/Friendseeker/MRE/commit/b1aee4346685387fa6afcc8236eff2cfd8fd331b) in https://friendseeker.github.io/MRE/. The console.log line was never executed in the Playwright build of Chromium yet executed for the Non-Playwright build.

**Comment by pavelfeldman** [comment]
I see. Could you elaborate on what you mean when you say non-Playwright build of Chromium? Playwright works with regular Chrome and Chromium, there are no Playwright builds. Also, how do you test it? Does it work when you use headed version (non-headless)?

**Comment by Friendseeker** [comment]
> I see. Could you elaborate on what you mean when you say non-Playwright build of Chromium? Playwright works with regular Chrome and Chromium, there are no Playwright builds. Also, how do you test it? Does it work when you use headed version (non-headless)?

I used chrome.exe under %USERPROFILE%\AppData\Local\ms-playwright. I double clicked on the aforementioned chrome.exe, opened the GitHub Page hosting the snippet and uploaded a video file.

I also used chrome & chromium installed from Chocolatey as comparison, and alert & console log did show up on these two.

**Comment by aslushnikov** [comment]
@Friendseeker Can you please try downloading Chromium Continuous Build from here:  https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/907429/chrome-win.zip and trying out your repro?

My suspicion is that it will not work similarly. (at least it doesn't for me on MacOS)

**Comment by Friendseeker** [comment]
> 
> 
> @Friendseeker Can you please try downloading Chromium Continuous Build from here: https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/907429/chrome-win.zip and trying out your repro?
> 
> My suspicion is that it will not work similarly. (at least it doesn't for me on MacOS). If this is the case, then `choco install chromium` probably installs some stable channel with codecs, whereas Chromium is missing them and thus can't parse video duration.

I tried repro on the downloaded build. Indeed, I managed to reproduce the issue.
Your suspicion is probably right.

**Comment by pavelfeldman** [comment]
I would try using Playwright with `channel: "chrome"`, it that works, it is likely due to the proprietary codecs that Chrome has and Chromium does not have.

**Comment by Friendseeker** [comment]
> 
> 
> I would try using Playwright with `channel: "chrome"`, it that works, it is likely due to the proprietary codecs that Chrome has and Chromium does not have.

Thank you a lot!
I can confirm that the issue is fixed.
