### ISSUE TITLE
[Question] Unable to get contents of an Element

### ISSUE THREAD

**Issue by WINOFFRG** [microsoft/playwright#8196]
> In the case of JS on a page when I do `document.querySelectorAll('.ts-calling-thread-header');` it gives me an array of HTML Node list upon which I have to do several things like accessing attributes and play with values.

Required Output: _Shown in Dev Tools in left_

![image](https://user-images.githubusercontent.com/61311751/129431413-75992378-18d5-463b-a878-d7e725f9ade7.png)

I tried a lot to do the same in playwright like:
1. Using `page.evaluate()`
> `var selector = '.ts-calling-thread-header';
    const result = await page.evaluate(selector => document.querySelectorAll(selector) , selector);
    `
which just kept on giving me `{ '0': {} }`

2. Using `page.$( )` or `page.$$( )`
This gave access to that element which was a very long object. And I found no way to access its content which in my case is `div`. The documentation has examples like `elementHandle.click()` but I didn't find one to access the contents of that element.
The same thing when done in dev tools like `playwright.$$('.ts-calling-thread-header');` gave me the required thing as shown above.

I just want to select that element and in a variable. In my case save that array, Iterate on each object, and get its attribute. **Stuck on this issue for the past 4 days, need urgent help.**

**Comment by ltsuda** [comment]
Please, can you try using `for in` iteration instead of `forEach`?
I've had this issue too.
Please, try the following snippet. Also, your `createMeet` function would need to be async because the `getAttribute` returns a Promise.
```
for (const meeting of meetings) {
  const id = await.getAttribute('id')
  ...
}```

**Comment by WINOFFRG** [comment]
Hello! As you said I tried using `for of` loop, But seems like it is the problem with the element itself. The line `await page.$$('.ts-calling-thread-header', 20);` doesn't return what it should or I might be using it incorrectly. 

**Explanation:**

When run in NodeJS Environment the line `await page.$$('.ts-calling-thread-header', 20);` actually returns an object by the name `ElementHandle` which is **printed on line 29** in Screenshot 1. I have [saved the output of that object in this gist](https://gist.github.com/WINOFFRG/a1535043315fb5493ab56e5c7f6a2053#file-logs-json) for your reference.

![image](https://user-images.githubusercontent.com/61311751/129473790-d8bf4c44-1438-4586-ae96-94ee400ad2b7.png)

Whereas, If I do the same thing in Dev Tools in the browser window that opens up, using the `playwright` object available to the browser. It gives me the correct output of that div selection.

![image](https://user-images.githubusercontent.com/61311751/129473989-87425394-f646-4c2a-8dae-ce815933fd87.png)

Probably, it looks like the way of selecting the element using `page.$$( )` isn't the correct CSS Selector method.

**Comment by ltsuda** [comment]
You're correct, the `page.$$('selector')` returns a list of ElementHandles [ElementHandle](https://playwright.dev/docs/api/class-page#page-query-selector-all).

Looking at your code, you need to use `return await createMeet(hrefEle)` at line 21 because the function is async. And also you need to call `var id = await meeting.getAttribute('id')`  at 31 because the `getAttribute` returns a Promise so you need to wait for that. 
[getAttribute](https://playwright.dev/docs/api/class-elementhandle#element-handle-get-attribute)
