### ISSUE TITLE
[Feature] Codegen command option to save trace

### ISSUE THREAD

**Issue by DavertMik** [microsoft/playwright#8197]
As discussed in #8003 with @aslushnikov it would be nice to have an option to record a trace for any browser session.
This requires starting Playwright in codegen mode and saving a trace after:
```
$ npx playwright codegen --trace=./trace.json
```

**Comment by aslushnikov** [comment]
I'll tentatively mark it for 1.15 since it seemed to be easy to implement. We'll see how it pans out

**Comment by RogerW-STR** [comment]
I just raised this today:
https://github.com/microsoft/playwright/issues/41607

It was also raised in 2024:
https://github.com/microsoft/playwright/issues/30548 and closed 10 days before it was opened.

The "this was fixed" seems to be in cli?


```
$ npx playwright codegen --save-trace
error: unknown option '--save-trace'
(Did you mean --save-storage?)
```
