### ISSUE TITLE
[Question] What reasons except memory out can trigger a page to emit 'crash' event?

### ISSUE THREAD

**Issue by zyscoder** [microsoft/playwright#8199]
Except for memory out, if any other reasons for Page to emit a 'crash' event?
is there any way to detect a Page crash like "Aw, snap".

**Comment by aslushnikov** [comment]
> Except for memory out, if any other reasons for Page to emit a 'crash' event?

@zyscoder Usually these are memory limitations and various bugs - both chromium and OS. 

> is there any way to detect a Page crash like "Aw, snap".

There's a [`page.on('crash')`](https://playwright.dev/docs/api/class-page#page-event-crash) event.

**Comment by zyscoder** [comment]
Is there any way to log the stack trace when emitting the 'crash' event? Or any way to dump some debug info?

**Comment by aslushnikov** [comment]
@zyscoder you can run with `DEBUG=pw:browser:*` environment variable to see all the browser output. If browser dumps anything into console, you'll see it there.

If it does give you stack, it might be without symbols. To get symbols, you can do: `npx playwright install chromium-with-symbols` and then use `channel` option when launching chromium:

```js
const browser = await playwright.chromium.launch({
  channel: 'chromium-with-symbols'
});
```

**Comment by zyscoder** [comment]
> @zyscoder you can run with `DEBUG=pw:browser:*` environment variable to see all the browser output. If browser dumps anything into console, you'll see it there.
> 
> If it does give you stack, it might be without symbols. To get symbols, you can do: `npx playwright install chromium-with-symbols` and then use `channel` option when launching chromium:
> 
> ```js
> const browser = await playwright.chromium.launch({
>   channel: 'chromium-with-symbols'
> });
> ```

Thanks very much for your reply, and I would have a try.
Another problem is that if I'd like to build a specified version of Chrome/Firefox/Webkit on my own, how can I build them with symbols?

**Comment by zyscoder** [comment]
@aslushnikov Something wrong when installing chromium-with-symbols
```
 » npx playwright install chromium-with-symbols
Invalid installation targets: 'chromium-with-symbols'. Expecting one of: 'chromium', 'webkit', 'firefox', 'ffmpeg', 'webkit-technology-preview', 'firefox-beta', 'chrome-beta', 'chrome', 'msedge'
```

**Comment by zyscoder** [comment]
@aslushnikov Sorry to bother you, would you mind telling me the method to build chrome with debug symbols? I'd like to do some debug on chrome but I didn't find the way to build it with debug symbols.

**Comment by pavelfeldman** [comment]
What is your use case? Could it be that you are not re-creating browser context for each test?

**Comment by pavelfeldman** [comment]
Sadly, we can't act on this without extra info. Please file a new issue and link this one if you get back to it!
