### ISSUE TITLE
[Feature] Richer convenience API

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#820]
I was looking at [Cypress API](https://docs.cypress.io/api/api/table-of-contents.html) - it does a great job exposing some of the higher-level driver primitives and I was wondering if some of them would make sense to Playwright as well.

- [x] [`check()`](https://docs.cypress.io/api/commands/check.html#Options) - @dgozman had a patch for it already.
- [ ] [`clock()`](https://docs.cypress.io/api/commands/clock.html#Syntax) - a user-land virtual time implementation, limited to `setTimeout`, `setInterval` and `Date`. I don't think we should get into the weeds of the native virtual time implementation, but we could at least make it work across frames and workers (currently [not supported](https://docs.cypress.io/api/commands/clock.html#Notes) in Cypress), wire `performance.now`, etc. Would be interesting to get some feedback from the field on how useful it is. Time mock was already mentioned [here](https://github.com/microsoft/playwright/issues/654#issuecomment-578642444).
- [ ] [`pause()`](https://docs.cypress.io/api/commands/pause.html#Syntax`) - handy for those not using the debugger, we could resume from cli or devtools.
- [ ] [`request(url)`](https://docs.cypress.io/api/commands/request.html#Syntax) - `auth0` [recommends](https://auth0.com/blog/end-to-end-testing-with-cypress-and-auth0/) it as a part of the login routine in your POM. This could simply be a `fetch` call wrapper, returning status, headers and body using our interception. Not sure why Cypress does it from [within Node](https://docs.cypress.io/api/commands/request.html#Notes) context, they could be doing a real fetch.
- [ ] [`rightclick`](https://docs.cypress.io/api/commands/rightclick.html#Right-click-with-key-combinations) - we have `click`, `dblclick` and even `tripleclick`. Probably worth exposing [isTrusted](https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted) context menu trigger as well.
- [x] [`route`](https://docs.cypress.io/api/commands/route.html#Syntax) - looks like a user-land XHR override. Playwright's interception is much more powerful, but I like the shape of the route API. I don't like how Puppeteer/Playwright handle network from the events today, I'd rather use the glob / predicate matcher.
- [ ] [`submit`](https://docs.cypress.io/api/commands/submit.html#Syntax) - looks simple and useful
- [x] [`uncheck()`](https://docs.cypress.io/api/commands/uncheck.html#Options) - same as `check`

Feel free to comment add / remove things you'd like to see (would not like to see) in Playwright.

**Comment by jperl** [comment]
Idea for pause(): opens a repl so user can try out different commands like this https://github.com/qawolf/qawolf/blob/master/packages/repl/src/repl.ts

**Comment by hdorgeval** [comment]
Hi @pavelfeldman, you might be interested in this project: [Fluent API around Playwright](https://github.com/hdorgeval/playwright-controller)

**Comment by jperl** [comment]
This project is holds our utilities (working on adding a lot more). Perhaps some of them might move into playwright core. https://github.com/qawolf/playwright-utils

**Comment by aesyondu** [comment]
How about `elementHandle.text()`, as a convenience for `elementHandle.evaluate((node) => node.textContent)`.

Generally, `page.$eval(".css-selector", (node) => node.textContent) -> page.text(".css-selector")`.

**Comment by pavelfeldman** [comment]
@aesyondu: `elementHandle.textContent` and `elementHandle.innerText` are now available. I'll close the meta bug and open new bugs as we go.
