### ISSUE TITLE
[Feature] add BrowserType to TestCase in Reporter events.

### ISSUE THREAD

**Issue by vmelikyan** [microsoft/playwright#8200]
It would be great to be able to have access to `BrowserType` in Reporter events to be used in `onTestBegin` and `onTestEnd`.

**Comment by aslushnikov** [comment]
@vmelikyan You can put this information yourself in the `metadata` field in the project: https://playwright.dev/docs/test-advanced#test-suite-options

Would this work for you?

**Comment by vmelikyan** [comment]
@aslushnikov is this `metadata` available on the Reporter events? E.g. `onTestEnd()`

**Comment by pavelfeldman** [comment]
You can add any attachments on testInfo 
https://playwright.dev/docs/next/api/class-testinfo#test-info-attachments

and read them in testResult:
https://playwright.dev/docs/next/api/class-testresult#test-result-attachments

I hope this helps!

**Comment by vmelikyan** [comment]
I will give this a try.

**Comment by pavelfeldman** [comment]
Please feel free to open a new issue if this did not work!
