### ISSUE TITLE
[Feature] page.locator() for "attached" elements

### ISSUE THREAD

**Issue by radekBednarik** [microsoft/playwright#8201]
Hi, thanks for great `page.locator()` feature!

One question though:
does this statement from documentation `Note that locator always implies visibility, so it will always be locating visible elements.` , really mean, that locators will not work on elements, which state is "attached"?

If so, would it be possible to add this functionality?

**Comment by pavelfeldman** [comment]
The doc is wrong here, locators don't imply visibility. I'll fix the doc.

**Comment by pavelfeldman** [comment]
I pushed the fix, it'll update live shortly.
