### ISSUE TITLE
[Bug]: Element with "opacity: 0;" is considering as visible and clickable

### ISSUE THREAD

**Issue by Andrei-Sav** [microsoft/playwright#8203]
### Playwright version

1.13

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

.NET 5.0

### What happened? / Describe the bug

Element with "opacity: 0;" is considering as visible and clickable, which is incorrect I guess.
![image](https://user-images.githubusercontent.com/68162973/129263265-0d02d375-39b8-48bc-bbaa-2476e1f662b0.png)

### Code snippet to reproduce your bug

```shell
public IElementHandle ExportTextLabel => page.WaitForSelectorAsync("xpath=//div[text()='Export']").Result;
----------------------------------------------------------------------------------------------------
var a = await leftSidePanel.ExportTextLabel.IsVisibleAsync();
Console.WriteLine($"=================================={a}====================================");
----------------------------------------------------------------------------------------------------
==================================True====================================
```

**Comment by pavelfeldman** [comment]
That's by design. Testing frameworks converged on not accounting opacity when considering visibility.
