### ISSUE TITLE
[Feature] Support emulating User Agent data like navigator.platform

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#8216]
Reference: https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#type-UserAgentMetadata

![image](https://user-images.githubusercontent.com/17984549/129541193-9927ee6c-7d7c-49ad-9258-e750ad6a2098.png)

**Comment by qkdreyer** [comment]
- https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setUserAgentOverride
- https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setNavigatorOverrides
