### ISSUE TITLE
[BUG] Cannot open file:// URLs with Firefox

### ISSUE THREAD

**Issue by hdorgeval** [microsoft/playwright#822]
**Context:**
- PlayWright Version: 0.10.0
- Operating System: Mac OS X 10.15.2 Catalina
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const browser = await firefox.launch({ headless: true });
const context = await browser.newContext();
const url = `file:${path.join(__dirname, 'foobar.html')}`;
const page = await context.newPage(url);

```

**Describe the bug**

`const page = await context.newPage(url);` will provoke a code freeze

Here is a repo where you could reproduce the problem: 
https://github.com/hdorgeval/playwright-controller (the purpose of this repo is to have the same features as exposed by the repo: https://github.com/hdorgeval/puppeteer-core-controller)

and the test in that repo is here:
https://github.com/hdorgeval/playwright-controller/blob/master/src/controller/tests/ctor/controller-ctor.test.ts at line 78

**Comment by pavelfeldman** [comment]
Thanks, I can repro! In the snippet below, `goto` never completes for Firefox when navigating to the file URL.

```js
const playwright = require('playwright');
const path = require('path');

(async () => {
  for (const type of ['chromium', 'webkit', 'firefox']) {
    const browser = await playwright[type].launch();
    const context = await browser.newContext();
    const page = await context.newPage();

    console.log(`${type}: goto`);
    await page.goto(`file:${path.join(__dirname, 'foobar.html')}`);
    console.log(`${type} -> ${await page.evaluate(() => document.body.textContent)}`);

    await browser.close();    
  }
})();

```

**Comment by pavelfeldman** [comment]
@aslushnikov  ^^

**Comment by aesyondu** [comment]
Just encountered the same issue:

https://github.com/aesyondu/javascript-questions/tree/tmp/playwright-sample

snippet:
```javascript
const path = require("path")
const { firefox } = require("playwright-firefox");
const { chromium } = require("playwright-chromium");
const { webkit } = require("playwright-webkit");

(async () => {
    const browser = await firefox.launch({ headless: false })
    // const browser = await chromium.launch({ headless: false })
    // const browser = await webkit.launch({ headless: false })
    const context = await browser.newContext()
    context.setDefaultTimeout(9999999)
    const page = await context.newPage()

    await page.goto(`file:${path.join(__dirname, "index.html")}`) // 2. firefox not resolving page.goto file:
    console.log("FIREFOX not outputting this")
```
