### ISSUE TITLE
[Feature] Adding step names to test output in terminal

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#8220]
Thanks a lot for the new API of the steps.

It will very nice to see the step names in console output.

The current state is:

![image](https://user-images.githubusercontent.com/52656401/129570251-ea3ca33b-7518-4973-923f-7c38176ceb4f.png)

We see only the names of the 'describe' part and of the test path.

**Comment by pavelfeldman** [comment]
What kind of rendering would you like to see?

**Comment by AlexKomanov** [comment]
@pavelfeldman 
I would like to see step names (the value written in test.step('value') ).
If it will be grouped in output under the test name - it would be great!!!

**Comment by pavelfeldman** [comment]
Fixed in https://github.com/microsoft/playwright/pull/8270
