### ISSUE TITLE
[Feature] API for customizing ALLURE Report

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#8221]
Hi all.

Is it possible to add some annotations or methods for customizing the Allure report? It will help with writing the steps to the report etc.

for example like in the Java-Allure case:
- Annotations
![image](https://user-images.githubusercontent.com/52656401/129572875-4ac6e9a1-d64e-4564-906f-b6784e67a709.png)

- Step-Names:

![image](https://user-images.githubusercontent.com/52656401/129572999-c01d1285-bd0b-4040-9f23-78e8e5949c54.png)

- Grouping 

![image](https://user-images.githubusercontent.com/52656401/129573159-7992103c-485e-494c-819c-dc9f5738d7b2.png)

More examples can be found here:
[link](https://www.swtestacademy.com/allure-report-testng/)

**Comment by pavelfeldman** [comment]
https://playwright.dev/docs/api/class-test#test-step is already landed, we need to update Allure report to render it. I'll use this feature request to track it.

**Comment by AlexKomanov** [comment]
@pavelfeldman 
Thanks!!!
