### ISSUE TITLE
[Question] Help when working with an array of elements

### ISSUE THREAD

**Issue by kshrestha99** [microsoft/playwright#8222]
We are transitioning from Protractor to Playwright and here is our blocker:
We currently have a method in Protractor like this:
```
 public static async getArrayListOf(
    listLocator: ElementArrayFinder,
    waitTime?: number
  ): Promise<string[]> {
    let parentList: string[];
    try {
      await HelperMethods.waitForElement(listLocator.first(), waitTime);
    } catch (err) {
      return (parentList = []);
    }
    parentList = await listLocator.map((locator: ElementFinder) =>
      locator.getText().then((text: string) => text.trim())
    );
    return parentList;
  }

```
This method returns a list of texts  from multiple elements that match the listLocator value.

So for example, we have `hz-layers-menu [class*="hz-checkbox-label"]` locator that returns 5 matches in our page, each with a different inner text.
So the method result will look like this: 

['Sara', 'Harry', 'Shiva', 'Jerry', 'Tara']

I saw that in v1.14.0, there is `Locator` but I still don't know how to get this done in Playwright.
Any help will be great and sorry to be always comparing Playwright with Protractor (Love Playwright, by far! :) ) 
Thank you!

**Comment by pavelfeldman** [comment]
```js
// wait for at least one element to be on screen
await page.waitForSelector('hz-layers-menu [class*="hz-checkbox-label"]');

// print all text contents
await page.$$eval('hz-layers-menu [class*="hz-checkbox-label"]', ee => ee.map(e => e.textContent));

// Or with the new locator API, latter is
const locator = page.locator('hz-layers-menu [class*="hz-checkbox-label"]');
await locator.allTextContents();
```

**Comment by kshrestha99** [comment]
@pavelfeldman Thank you as always!
