### ISSUE TITLE
[Question] What is the proper way to create a persistent extension-enabled context with Playwright Test?

### ISSUE THREAD

**Issue by cat-ninja** [microsoft/playwright#8223]
Hey guys!
I'm trying to create some tests for a Chrome extension using Playwright Test.
The problem is in the error I'm seeing when the browser is started: 
![image](https://user-images.githubusercontent.com/17785134/129582772-aa927d79-d0af-41c8-a322-2dc5e7e0fd3f.png)

This is the code I'm using:
```typescript
import { test, expect, chromium } from "@playwright/test";
import { join } from "path";
import { tmpdir } from "os";
import fs from "fs";
import rimraf from "rimraf";

const testPersistent = test.extend({
  page: async ({}, use) => {
    const pathToExtension = join(__dirname, "/utils/extensions");
    const dir = await fs.promises.mkdtemp(join(tmpdir(), "user-data-dir-"));
    const context = await chromium.launchPersistentContext(dir, {
      headless: false,
      args: [
        `--disable-extensions-except=${pathToExtension}`,
        `--load-extension=${pathToExtension}`,
      ],
    });
    await use(context.pages()[0]);
    await context.close();
    rimraf.sync(dir);
  },
});

testPersistent("basic test", async ({ page }) => {
  expect(1).toBe(2);
});
```
This is strange because when I'm not using Playwright Test I don't see any issues.
Here is the code that's working:
```typescript
import { chromium } from "@playwright/test";
import { join } from "path";
import { tmpdir } from "os";
import fs from "fs";
import rimraf from "rimraf";

(async () => {
  const pathToExtension = join(__dirname, "/utils/extensions");
  const dir = await fs.promises.mkdtemp(join(tmpdir(), "user-data-dir-"));
  const browserContext = await chromium.launchPersistentContext(dir, {
    headless: false,
    args: [
      `--disable-extensions-except=${pathToExtension}`,
      `--load-extension=${pathToExtension}`,
    ],
  });
  ... some code here
  rimraf.sync(dir);
})();
```
I assume I'm doing something wrong. What is the proper way to start the browser with the extension using Playwright Test?

**Comment by pavelfeldman** [comment]
The code looks the same to me, I wouldn't know why it gives different behavior!

**Comment by cat-ninja** [comment]
> The code looks the same to me, I wouldn't know why it gives different behavior! 

Agree. Could you please check if it's reproducible for you?
For me it's reproducible with any extension I tried

**Comment by cat-ninja** [comment]
> The code looks the same to me, I wouldn't know why it gives different behavior!

I just found a silly error I made.
 `__dirname` in my case points to different folders and that's why I'm seeing this error.
My apologies, it's not an issue with Playwright Test
