### ISSUE TITLE
[BUG] First test# (https://playwright.dev/docs/intro#first-test) failed ' strict mode violation: selector resolved to 2 elements.'

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#8235]
**Context:**
- Playwright Version: [1.14.0]
- Operating System: [Mac]
- Node.js version: [14.7]
- Browser: All
- Extra: N/A

**Code Snippet**

```javascript
const { test, expect } = require('@playwright/test');

test('basic test', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  const title = page.locator('.navbar__title');
  await expect(title).toHaveText('Playwright');
});
```

**Describe the bug**

The JavaScript example documented here https://playwright.dev/docs/intro#first-test failed due to error 

```javascript
 locator.textContent: Evaluation failed: Error: strict mode violation: selector resolved to 2 elements.
        at u.querySelector (<anonymous>:3:34807)
        at eval (eval at evaluate (:3:1339), <anonymous>:6:32)
        at i (<anonymous>:3:37685)
        at <anonymous>:3:37773
        at Object.run (<anonymous>:3:38253)
        at eval (eval at evaluate (:3:1339), <anonymous>:1:14)
        at t.default.evaluate (<anonymous>:3:1362)
        at t.default.<anonymous> (<anonymous>:1:44)
    =========================== logs ===========================
      retrieving textContent from ".navbar__title"
      strict mode violation: selector resolved to 2 elements.
    ============================================================

```

Looking for a solution to overcome this problem. How can i assert only one of the locator ?

**Comment by pavelfeldman** [comment]
Ouch - we picked a very unfortunate example, because there are two elements matching `.navbar__title` selector in the latest site version. Locators are strict, so they throw if selector matches more than one element. You can resolve this one via

- picking a better selector:


  ```
  const title = page.locator('.navbar__inner .navbar__title');
  ```

- or ignoring the ones that are not visible:
  ```
  const title = page.locator('.navbar__title').locator('visible=true');
  ```

Both resolve ambiguity.

**Comment by vsravuri** [comment]
@pavelfeldman Thank you very much. It would be helpful if a note is added here https://playwright.dev/docs/api/class-locator that Locators are strict. Although i could see a note in 1.14 Release Notes.

**Also, locators are "strict" by default!**

**Comment by pavelfeldman** [comment]
Pushed the updated docs, they should be live in 15 mins or so. Thanks for the report!
