### ISSUE TITLE
[Question] Not Able to install playwright 1.14.0

### ISSUE THREAD

**Issue by mv-test-account** [microsoft/playwright#8237]
Hi 
Im not able to install your package I will always receive error: 
(node:82242) ExperimentalWarning: The fs.promises API is experimental
(node:82242) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'mkdir' of undefined

when i run npm install playwright

**Comment by pavelfeldman** [comment]
Looks like you need Node 14+

**Comment by mv-test-account** [comment]
Thanks for quick update.
You are right sorry for troubles
