### ISSUE TITLE
[Question] How to mark test.step as "fixme"

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#8238]
v1.14.0 introduced new test function 'test.step(title, body)'

I would like to mark a test step as "fixme" instead of marking the entire test as "fixme"

This will help me to split long tests into multiple steps and continue the execution by marking the problematic step as  "fixme"

Appreciate if you guide me how to achieve this.

**Comment by pavelfeldman** [comment]
If you need to skip / fixme some entities, it means those are tests, not steps. Luckily we introduced a new serial test mode where you can have large scenarios as a sequence of tests as well. We'll post a link to a doc once it is published.

**Comment by dgozman** [comment]
Here is a link to the serial mode docs: https://playwright.dev/docs/test-parallel#serial-mode.

**Comment by casurin** [comment]
This really is a missing feature and also an inconsistency in the API.

And what is a test-step or an entire test is not something other outsiders can judge. For us there is a big difference in the setup and overhead of a `test` and a `test.step`. Moving from `test.step` to test would incur a significant overhead, slowdown and increase in resource-utilization as well as being more error-prone. 

even on `expect` should have a way to .skip and `.fixme` : With data-dependencies we have the scenario that a single action will change multiple elements and for some of them the functionality has not been finalised. it is a singular logical step to say enter a Date - and multiple checks were some need to be fixed later.
