### ISSUE TITLE
[Feature] Export PageWaitForSelectorOptions

### ISSUE THREAD

**Issue by zefirka** [microsoft/playwright#8247]
I'm implementing simple wrapper over `page` object on TypeScript and it would be very useful if I could determine incoming types for `page.waitForSelector` options, so can you allow export of PageWaitForSelectorOptions?

**Comment by mxschmitt** [comment]
As a workaround in the meantime, you can use the following:

```ts
import { Page } from 'playwright';
type PageWaitForSelectorOptions = Parameters<Page['waitForSelector']>[1];
```

**Comment by yury-s** [comment]
Closing this issue as we are not planning to export options types please use the workaround above.

Having PageWaitForSelectorOptions as a named type in the api was a mistake and we'd rather align it with other option definitions by removing named type/interface than export those types.
