### ISSUE TITLE
[Question] Best way to update Playwright?

### ISSUE THREAD

**Issue by OxNinja** [microsoft/playwright#8250]
Hello, I there a way to maintain Playright up-to-date? [I saw the new](https://playwright.dev/docs/intro#installation) `@playwright/test` NPM and I got confused, as I am used to the classic `playwright` package.

For the moment I can't get the latest version because `npm up` runs in an infinite loop at 100% update and I have to `Ctrl-C` the command. I also tried `npm uninstall playwright; npm i -D playwright` but same infinite loop.

What am I doing wrong?

I read #8237 and will try to update NodeJS as well.

Moreover, as the title says, is `npm update` the best way to update to Playwright's latest version?

**Comment by mxschmitt** [comment]
If something runs in an infinite loop, please provide us a minimum reproducible. You can consume Playwright in two ways:

a) via Playwright Test, an end-to-end testing focused test-runner which includes Playwright. You don't need Playwright in that case additionally installed https://playwright.dev/docs/intro
b) via Playwright Library, you can use it with external test-runners or do custom stuff with it, see here: https://playwright.dev/docs/next/library

The best way to update Playwright is `npm install -D @playwright/test@latest` (or just `playwright` if you consume it via the library)

Your linked issue is unrelated, this is about an outdated Node.js version.

**Comment by OxNinja** [comment]
Thanks for the fast answer. Here is more information a minimum reproducible:

`Node: v12.22.5` (why I thought my Node version was outdated)

![image](https://user-images.githubusercontent.com/57400445/129705365-6ff48026-9437-465c-81fc-8dd85e0d24ec.png)

**Comment by mxschmitt** [comment]
Could you run `DEBUG=pw:install npm i -D playwright`? There you should get more debug output. 

Also `npm --version` might help to debug that issue further.

**Comment by OxNinja** [comment]
`npm version: 7.5.2`

![image](https://user-images.githubusercontent.com/57400445/129706877-9fe8e062-f187-42ff-8769-3ffa0422e64c.png)

Thanks for your time

**Comment by JoelEinbinder** [comment]
@aslushnikov Just a guess: I suspect this is something with the lock file code. I had a similar experience upgrading from a very old beta version of playwright-test to the modern one. I think Ctrl+C can put us into a bad state.

**Comment by pavelfeldman** [comment]
See if `rm -rf  ~/.cache/ms-playwright/` fixes it for you!

**Comment by OxNinja** [comment]
My fix was to install playwright in another directory, I will try that if it happens again
