### ISSUE TITLE
[Feature] Support of ignoreHTTPSErrors in launchServer options

### ISSUE THREAD

**Issue by karanshah-browserstack** [microsoft/playwright#8251]
We are facing issues with Self Signed Certificates on firefox and while doing browser.newPage() we are getting SEC_ERROR_UNKNOWN_ISSUER which gets resolved by setting ignoreHTTPSErrors: true.
Can we allow Self Signed Certificates by default or provide an option to pass these as options in launchServer options? 

Working code: 
```
const browser = await firefox.connect({
    wsEndpoint: "ws://127.0.0.1:55614/a4de39415b37282b3f8ee16845753bf8",
  });

  const context = await browser.newContext({
    ignoreHTTPSErrors: true
  });

  // Use the default browser context to create a new tab and navigate to URL

  const page = await context.newPage();
```
  
  Not Working: 
  ```  
const browser = await firefox.connect({
    wsEndpoint: "ws://127.0.0.1:55614/a4de39415b37282b3f8ee16845753bf8",
  });

  // Use the default browser context to create a new tab and navigate to URL

  const page = await browser.newPage();
```

**Comment by JoelEinbinder** [comment]
`browser.newPage()` does not use the default browser context. It creates a new one for this page. You can specify ignoreHTTPSErrors [there](https://playwright.dev/docs/api/class-browser#browser-new-page-option-ignore-https-errors).
```js
const page = await browser.newPage({ ignoreHTTPSErrors: true} );
```
