### ISSUE TITLE
[Question] I want to use geteventlisteners in page.evaluate but I do not know how to

### ISSUE THREAD

**Issue by chaowenGUO** [microsoft/playwright#8254]
In chrome devtools I can use geteventlisteners, but I do not know how to do that in playwright page.evaluate

For example, I can use the following code to remove all the events associated to document in devtools:
```js
for (const [key,value] of Object.entries(globalThis.getEventListeners(document)))
    for (const _ of value) document.removeEventListener(key, _.listener)
```

but the following code in playwright not working:
```js
await page.evaluate(() => {for (const [key,value] of Object.entries(globalThis.getEventListeners(document)))
                                              for (const _ of value) document.removeEventListener(key, _.listener)})
```

**Comment by JoelEinbinder** [comment]
`getEventListeners` is part of the [DevTools Command Line API](https://github.com/GoogleChrome/devtools-docs/blob/master/docs/commandline-api.md#geteventlistenersobject) and is not supported by Playwright.

**Comment by chaowenGUO** [comment]
Is there any idea how to

**Comment by JoelEinbinder** [comment]
It is unlikely that we will add this feature, but you can make it work today using [CDPSession](https://playwright.dev/docs/api/class-cdpsession) (Chromium only) and [Runtime.evaluate](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-evaluate)'s `includeCommandLineAPI`.

**Comment by chaowenGUO** [comment]
const client = await context.newCDPSession(page)
    const {result} = await client.send('Runtime.evaluate', {expression:'document', objectGroup:'handler'})
    const {listeners} = await client.send('DOMDebugger.getEventListeners', {objectId:result.objectId})
    for (const {type, handler} of listeners) console.log(type, handler)
    await client.send('Runtime.releaseObjectGroup', {objectGroup:'handler'})

Now I can get type and handler of ducument. But I do not know how to remove the even listener?

What I try:
    await page.evaluate(({type, ??}) => document.removeEventListener(type, ??), {type, ??})

What I should put in ?? I think ?? is some expression of handler

**Comment by chaowenGUO** [comment]
Is there any idea how to fill out ??
