### ISSUE TITLE
[Feature] Add 'jest-diff' for the matchers to display the differences clearly.

### ISSUE THREAD

**Issue by elaichenkov** [microsoft/playwright#8258]
It'll be really great to show the differences so people can review the changes confidently.

Because now it's too hard to find the differences in the text.

Actual:
![image](https://user-images.githubusercontent.com/29764053/129743239-fc67122c-7033-4df3-88d0-e3334cd827aa.png)

Expected:

![image](https://user-images.githubusercontent.com/29764053/129744105-52f18db9-39fa-4add-849f-6801dbb8076c.png)

**Comment by elaichenkov** [comment]
Just wanted to add that would be awesome to have it for all the matchers, which are comparing string such as `toHaveText, toHaveValue, toHaveUrl, toHaveTitle` and so on.

**Comment by JoelEinbinder** [comment]
> Just wanted to add that would be awesome to have it for all the matchers, which are comparing string such as `toHaveText, toHaveValue, toHaveUrl, toHaveTitle` and so on.

Yes, it should be fixed for all of them in the next release. Let me know if any still don't work!

**Comment by elaichenkov** [comment]
Awesome! Thank you!
