### ISSUE TITLE
[Feature] expect that waits should have a different name

### ISSUE THREAD

**Issue by srguiwiz** [microsoft/playwright#8264]
It will be hard to quickly make sense of traditional `expect` versus `await expect`, for reviewing someone else's test code, making changes, debugging, training new test developers.

For example, instead of
``` typescript
await expect(locator).toContainText(text);
```
it could or should be
``` typescript
await expect(locator).asyncToContainText(text);
```

That compares to the non-async version used for example like
``` typescript
expect(await page.innerText(locator)).toContain(text);
```

The documentation at https://playwright.dev/docs/test-assertions/ and https://playwright.dev/docs/intro/#writing-assertions currently puts so much emphasis on the async matchers, someone new might overlook there is actually a rich set of functionality in the sync matchers, the more traditional use of expect.

**Comment by pavelfeldman** [comment]
We considered naming it differently, but ultimately decided that consistent naming would be better. Similar thing happened when async methods were introduced - inertia made people add Async suffix to those method names, but it passed shortly.
