### ISSUE TITLE
[Question] Configuring the boilerplate in Playwright Inspector

### ISSUE THREAD

**Issue by ChristianMay21** [microsoft/playwright#8265]
Hi! Thanks so much for all your work on this great tool. A quick question - is there a way to configure the boilerplate in Playwright Inspector when running Playwright codegen? I'd love to, for example, be able to change it to automatically put a test in a loop to test on Firefox, Chrome, and Safari, but currently I can't seem to find any way to tweak it. 

![image](https://user-images.githubusercontent.com/45889402/129786511-af616833-ad27-46d9-8257-248315e63d43.png)

**Comment by pavelfeldman** [comment]
Our test runner integration will run it for all browsers. Learn more at https://playwright.dev/dotnet/docs/test-runners

**Comment by ChristianMay21** [comment]
I re-read the documentation that you linked. Thank you for directing me to it.

You can manually create tests that run in all browsers, yes. However, unless I'm missing something, code output by playwright inspector with the codegen command in the CLI seems to hard-code the browser: notice line 10 in the above image, where the output code explicitly specifies chromium.

So in order to achieve testing in multiple browsers, I'd have to manually change line 10 every time I created a test, or write some program that would go in and edit the generated file. What I'd much prefer is some way to change line 10 to, for example, read whatever browser is currently set in the BROWSER environment variable.

Alternatively, I would love to be able to configure the boilerplate that populates as soon as codegen is run: see here the default code that is generated when running codegen on google.com. That would open up a lot of possibilities for customizing test generation workflows for me and my team.
![image](https://user-images.githubusercontent.com/45889402/129907930-3ee1a8fb-9eeb-450e-8b3e-067d97397bd5.png)

Is anything like this accomplishable with the current builds?

**Comment by pavelfeldman** [comment]
We assume that you need to edit the tests generated with the codegen. Codegen is only there to save time, not to create production tests. I'll leave your bug open so that others could 'upvote' it.

**Comment by ChristianMay21** [comment]
That about sums it up, yup.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
