### ISSUE TITLE
Timeout error occurs for test that took more than 30s

### ISSUE THREAD

**Issue by algot** [microsoft/playwright#8268]
- Playwright Version: 1.13.1

- Operating System: Ubuntu 20.04
- Node.js version: 14.15.0
- Browser: Chromium

**System:**

- OS: Linux 5.11 Ubuntu 20.04.2 LTS (Focal Fossa)
- Memory: 1.93 GB / 7.59 GB
- Container: Yes

**Binaries:**

- Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
- npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm

```javascript
import { test, expect } from '@playwright/test';
test('basic test', async ({ page }) => {
    await page.goto('https://playwright.dev/');
    await page.waitForTimeout(15000);
    console.log(await page.title());
    await page.waitForTimeout(15000);
    console.log(await page.title());
    await page.waitForTimeout(15000);
    console.log(await page.title());
});
```

My test execution last more than 30 seconds for 1 test (see example for reproduce above).
It causes timeout error.
I don't have any custom configuration. Just code above and run it via playwright test runner

```
❯ npx playwright test

Running 1 test using 1 worker

  ✘  test.spec.ts:2:1 › basic test (30s)
Fast and reliable end-to-end testing for modern web apps | Playwright


  1) test.spec.ts:2:1 › basic test =================================================================

    Timeout of 30000ms exceeded.

--- Test output ------------------------------------------------------------------------------------

Fast and reliable end-to-end testing for modern web apps | Playwright

----------------------------------------------------------------------------------------------------

  Slow test: test.spec.ts (30s)

  1 failed
    test.spec.ts:2:1 › basic test ==================================================================
```

As far as I understand default 30s timeout is related to UI element querying not for entire test execution limit.
Am I right?
Or default timeout setting should be increased in order to run test with execution time > 30s?

**Comment by pavelfeldman** [comment]
Yes, you need to bump `timeout` in your config:

https://playwright.dev/docs/api/class-testconfig#test-config-timeout
https://playwright.dev/docs/test-configuration#testing-options
