### ISSUE TITLE
[BUG] test status changer 

### ISSUE THREAD

**Issue by Gornostalev** [microsoft/playwright#8273]
OS: Windows 10
Node: 14.15.4
Playwrigth: 1.14.0

Hello, i need change test status from fail to skipped, can i do that? I have project on C# with NUnit and he has such an [opportunity](https://stackoverflow.com/questions/34406857/failing-an-nunit-test-inside-teardown)
i was trying use afterEach:
```
 test.afterEach(async ({  }, testInfo) => {
   testInfo.status = 'skipped'
});
```
and got exception:
```
TypeError: Cannot read property 'stack' of undefined
    at formatError (C:\Users\egor\Desktop\node_modules\@playwright\test\lib\test\reporters\base.js:221:23)
```

**Comment by mxschmitt** [comment]
You can skip the test by a condition, see here: https://playwright.dev/docs/test-annotations#conditionally-skip-a-test
