### ISSUE TITLE
[Question] Executing script on remote machine

### ISSUE THREAD

**Issue by macroking** [microsoft/playwright#8280]
Protractor let's us run the script in remote machines/nodes registered with selenium grid. Doing so will reduce the overall execution time of test suite.

I have gone through the documentation and feels like sharding will help in some way. But what I am not sure is that how do I instruct playwright to perform the execution on Machine1, Machine2, etc...

Is there any configuration in playwright that delegates the execution to multiple machines?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
