### ISSUE TITLE
[BUG] electron.launch's option types don't include the timeout field

### ISSUE THREAD

**Issue by Nokel81** [microsoft/playwright#8283]
**Context:**
- Playwright Version: 1.14
- Operating System: macOS
- Node.js version: 14.17.5
- Browser: Electron 12.0.15

**Code Snippet**

```javascript
const { electron } = require('playwright');

(async () => {
  await electron.launch({ timeout: 100_000 }); // typeerror
})();
```

**Describe the bug**

Looking at the code, it seems like timeout should be exported here as the code for consuming a custom timeout exists.

**Comment by pavelfeldman** [comment]
What is you use case for passing the timeout?

**Comment by Nokel81** [comment]
I guess just the same as any point of modifying the timeout. I just noticed while looking through the code that this wasn't exposed as part of the typescript types even though it would work.

I was looking through because I was trying to see if I could pass in a timeout to close.

**Comment by Nokel81** [comment]
@pavelfeldman Furthermore, if I look at the typescript file `src/protocol/channels.ts` I see that the types do include the `timeout` field. Are the files under `types/` hand made and not generated from the typescript files?
