### ISSUE TITLE
[Question] Can I disable browsers from taking keyboard focus?

### ISSUE THREAD

**Issue by yongjik** [microsoft/playwright#8301]
Hi, sorry if it's a dumb question, but I have some Python tests that I usually run on non-headless (headful?) mode, and I can't really use the computer while they're running, because they steal keyboard focus whenever a new tab is opened (which is, unfortunately, very often for my tests).

So I was wondering... is it possible to disable this (focus stealing)? Then I could keep an eye on the running script, while I'm free to do other stuff in the meantime.

Not a super big deal, but I thought it would be nice to have... :)

* I'm using Ubuntu 20.04.

**Comment by shirshak55** [comment]
I have already raised similar issue regarding focus stealing. Currently, there is no solution. It would at least be helpful if they start minimized and don't focus steal.

**Comment by JoelEinbinder** [comment]
Yes as shirshak says this is not a trivial fix for us. You can run with headless mode or [Xvfb](https://en.wikipedia.org/wiki/Xvfb) on Ubuntu. But adding this into our browsers is a very large amount of work for a relatively minor feature.
