### ISSUE TITLE
[Question] How to handle browser `Observing lost connection from node`?

### ISSUE THREAD

**Issue by zyscoder** [microsoft/playwright#8302]
The browsers raise the following error and the playwright cannot continue to conmmuticate with them:
```
 pw:browser [pid=1753121][err] [0819/022631.799439:VERBOSE1:node_controller.cc(604)] Dropped peer 70C22B3E42DF1E90.AD77EEBF1E7510A6
 pw:browser [pid=1753121][err] [0819/022631.830696:VERBOSE1:node.cc(504)] Observing lost connection from node A919EF913B6B35A5.379438BA9016D9F7 to node 70C22B3E42DF1E90.AD77EEBF1E7510A6
 pw:browser [pid=1753121][err] [0819/022631.862960:VERBOSE1:node_controller.cc(686)] Dropping message for unknown peer: 70C22B3E42DF1E90.AD77EEBF1E7510A6
 pw:browser [pid=1753121][err] [0819/022631.878038:VERBOSE1:node_controller.cc(686)] Dropping message for unknown peer: 70C22B3E42DF1E90.AD77EEBF1E7510A6
```
How to handle this problem?

**Comment by JoelEinbinder** [comment]
This looks like a mojo thing. Sometimes Chromium prints some error messages. I wouldn't expect it to be necessarily related to other problems you might be having. Can you describe whats broken with playwright for you?

**Comment by zyscoder** [comment]
> This looks like a mojo thing. Sometimes Chromium prints some error messages. I wouldn't expect it to be necessarily related to other problems you might be having. Can you describe whats broken with playwright for you?

I tried to use `page.evaluate` to test some JavaScript code. I launched my chrome with arg "--enable-logging, --v=1" and get the log file: [chrome_debug.log](https://github.com/microsoft/playwright/files/7030496/chrome_debug.log).
Would you mind sharing me some experience to analyze this kind of log file?

**Comment by JoelEinbinder** [comment]
If you aren't experiencing trouble you can safely ignore these logs. Chrome prints all sorts of scary error messages but they rarely effect anything.

**Comment by zyscoder** [comment]
> If you aren't experiencing trouble you can safely ignore these logs. Chrome prints all sorts of scary error messages but they rarely effect anything.

But what about the FATAL log: 
![image](https://user-images.githubusercontent.com/23655282/130561394-011e873d-a024-4b47-a6f9-2f80f1e0e4a0.png)
It seems a 'crash' event in Page would be thrown at the same time of the FATAL. The FATAL implies something wrong or just not effect anything?

**Comment by pavelfeldman** [comment]
I see, then there is a page crash under the hood. We would need a reproduction steps in order to help with it. Is there a script or steps we can follow to trigger it?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
