### ISSUE TITLE
[BUG] Java Docs have several mistakes

### ISSUE THREAD

**Issue by andrejs-ps** [microsoft/playwright#8303]
**Issue 1:**
This doc: https://playwright.dev/java/docs/api/class-route

Has a code snippet that does not compile - it misses one ")" at the end:
```
page.route("**/xhr_endpoint", route -> route.fulfill(
  new Route.FulfillOptions().setPath(Paths.get("mock_data.json")));
```

It should be:
```
page.route("**/xhr_endpoint", route -> route.fulfill(
  new Route.FulfillOptions().setPath(Paths.get("mock_data.json"))));
```

**Issue 2:**
This doc: https://playwright.dev/java/docs/trace-viewer/
Has an invalid code snippet (probably a copy-paste mistake from NodeJS docs)

```
Browser browser = chromium.launch();
BrowserContext context = browser.newContext();

// Start tracing before creating / navigating a page.
context.tracing.start(new Tracing.StartOptions()
  .setScreenshots(true)
  .setSnapshots(true);

Page page = context.newPage();
page.goto("https://playwright.dev");

// Stop tracing and export it into a zip archive.
context.tracing.stop(new Tracing.StopOptions()
  .setPath(Paths.get("trace.zip")));
```

Should probably be as below ("navigate" instead of "goto" and "tracing()" instead of "tracing":

```
Browser browser = chromium.launch();
BrowserContext context = browser.newContext();

// Start tracing before creating / navigating a page.
        context.tracing().start(new Tracing.StartOptions()
                .setScreenshots(true)
                .setSnapshots(true));

        Page page = context.newPage();
        page.navigate("https://playwright.dev");

// Stop tracing and export it into a zip archive.
        context.tracing().stop(new Tracing.StopOptions()
                .setPath(Paths.get("trace.zip")));
```

**Comment by mxschmitt** [comment]
@andrejs-ps are you interested in creating a Pull Request and fixing it? No worries if not, we'll otherwise take care of it.

**Comment by andrejs-ps** [comment]
@mxschmitt - thank you for the offer, I'm currently not fully set up to do PRs, so I'd be happy if someone took care of it. But I'm a guy who likes clean Docs, so when I get more time on my hands, I intend to contribute to Playwright by improving the documentation directly via PRs.
