### ISSUE TITLE
[REGRESSION]: os name is appended to .txt snapshots in 1.14

### ISSUE THREAD

**Issue by crazyvan25** [microsoft/playwright#8304]
**Context:**
- GOOD Playwright Version: 1.13
- BAD Playwright Version: 1.14
- Operating System: Mac

```javascript
expect(translationsJson).toMatchSnapshot(`config-translations.txt`)
```
creates a `config-translations.txt` file in 1.13 and appends the os name in 1.14 by default `config-translations-darwin.txt`.

Is there a way to disable this suffix for .txt snapshots as the snapshot is not dependent on the os and browser?

**Comment by aslushnikov** [comment]
looks like a regression; we'll fix it

**Comment by aslushnikov** [comment]
> creates a config-translations.txt file in 1.13

@crazyvan25 for the record: Playwright Test 1.13 actually creates a `config-translations-myproject.txt` for me in 1.13, where `myproject` is the name of the project specified in `playwright.config.js`.

**Comment by aslushnikov** [comment]
@crazyvan25 ah, while looking into this it turned out that there's a `testInfo.snapshotSuffix` option. it defaults to `process.platform`, but you can make it empty:

```js
const {test, expect} = require('@playwright/test');

test('foo', ({}, testInfo) => {
  testInfo.snapshotSuffix = '';
  expect('foo bar').toMatchSnapshot('foobar.txt');
});
```

**Comment by crazyvan25** [comment]
Awesome, thanks! 
I've not set up a `playwright.config.js` yet.
I'll try setting `snapshotSuffix`.

**Comment by JoelEinbinder** [comment]
@aslushnikov I don't understand why the p1 label went away. Is this not a regression? If the defaults changed the snapshot file name, then thats something we should cherry pick.

**Comment by aslushnikov** [comment]
@crazyvan25 We discussed this, and turns out this was a bug fix. You happen not to use `page` fixture in your test that was doing text snapshot; thus you had this kind of behavior.

from now on, use `testIno.snapshotSuffix` to opt out from platform-dependent snapshots!

**Comment by zomars** [comment]
How about the project suffix ? Text files should be browser agnostic also. We don't need to the have `translations-chromium.txt` ,  `translations-firefox.txt`, etc...

Setting `snapshotSuffix` doesn't remove those.
