### ISSUE TITLE
[Feature] Adding option to download specific browser engine

### ISSUE THREAD

**Issue by edi2004** [microsoft/playwright#831]
Multiple browsers testing is not really required on every tests.
Chromium, Webkit, and Firefox downloaded all at once at first install is really huge in download size. Maybe need a prompt before downloading all package to ask user what specific browser is they really need. AFAIK, Chromium and Webkit are basically the same.

**Comment by mxschmitt** [comment]
Maybe #812 will solve your issue.

**Comment by aslushnikov** [comment]
> Maybe #812 will solve your issue.

Yeah, there are `playwright-webkit`, `playwright-chromium` and `playwright-firefox` packages that
download only specific browsers.

Also, for a programmatic download API - there's  https://github.com/microsoft/playwright/issues/823
