### ISSUE TITLE
[BUG] Local Run:  args: ['--window-size=1920,1080'] opens the browser window with deviation to right and down

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#8334]
**Context:**
- Playwright Version: 1.14
- Node.js version: v14.16.1
- Browser: Chrome

**Code Snippet**

```javascript
import { PlaywrightTestConfig } from "@playwright/test";


const config: PlaywrightTestConfig = {
  retries: 1,
  timeout: 180000,
  globalTimeout: 300000,
  reporter: [["./my-reporter.ts"], ["list"], ["junit", { outputFile: "reports/test-results.xml" }]],
  use: {
    trace: 'on',
    screenshot: 'on',
    video: {
      mode: "on",
      size: {
        width: 1920,
        height: 1080
      }
    },
    contextOptions: {
      viewport: null,
    },
    // Browser options   
    launchOptions: {     
      channel: 'chrome', //Changed back to chromium due to the issue with chrome on CI
      headless: false,
      args: ['--window-size=1920,1080'],
      //args: ['--start-maximized']
    },
    //slowMo: 0,
  },
};

export default config;
```

**Describe the bug**

**_Local Run:_**
I try to open the browser window in maximized resolution. 
I tried  to open via viewport (viewport: {width:1920, height: 1080} definition or via args definition(args: ['--window-size=1920,1080'],). Both two options open the the browser window with deviations to right and down (can be seen in attached screenshot)

![image](https://user-images.githubusercontent.com/52656401/130177579-d23cd618-8213-4b9c-b46b-e1b9535a176d.png)

Only the option -> args: ['--window-size=1920,1080'] works as well. 
In the case of defining resolution - it should be calculated from the upper left corner, isn't it?

**Comment by JoelEinbinder** [comment]
We don't support `--window-size`. You can try filing an issue against chromium at https://crbug.com
