### ISSUE TITLE
Provide the ability to handle ElementHandle events[Feature]

### ISSUE THREAD

**Issue by medabalimi-jagadeesh** [microsoft/playwright#8335]
something analogous to EventFiringWebDriver of Selenium. The objective is to be able to achieve self-logging tests in an easy manner as shown here https://alexsiminiuc.medium.com/self-logging-selenium-webdriver-tests-142701e6b815

**Comment by pavelfeldman** [comment]
Could you share a use case for it? Playwright comes with the tracing capabilities out of the box, does that not cover your use case? 

https://playwright.dev/docs/trace-viewer
https://playwright.dev/docs/test-configuration#record-test-trace

**Comment by medabalimi-jagadeesh** [comment]
When automated scripts are executed, we often need to log the step by step execution, such as what actions we performed on the web elements as a test evidence to the stake holders. We generally save these per test logs and report them to testcase management systems such as testrail.

Is there a way to get the Actions performed part as test logs mentioned at this URL? https://playwright.dev/docs/trace-viewer/

**Comment by JoelEinbinder** [comment]
These should be available via the [logger api](https://playwright.dev/docs/api/class-logger) or via [`DEBUG=pw:api`](https://playwright.dev/docs/debug#verbose-api-logs)
