### ISSUE TITLE
[BUG:Webkit] `page.goto() / page.waitForLoadState()` method does not wait for the `load` event

### ISSUE THREAD

**Issue by canonic-epicure** [microsoft/playwright#8340]
**Context:**
- Playwright Version: 1.14.0
- Operating System: Ubuntu 18
- Node.js version: v12.22.5

Bug appears only with Webkit launcher.

Steps to reproduce (reduced to a bare minimum):
1) Clone this repo: `git clone https://github.com/canonic-epicure/playwright-8340-repro`
2) In the checkout directory, run `npm install`
3) In console, run `npx exec wds`. This will launch the dev web server on port 8000 (should be free, port is hardcoded)
4) Now, run the `node server.js` in the separate shell.
5) Observe the `TypeError: window.CLIENT is not a function` exception
6) Uncomment this line in `server.js`:
`await page.waitForFunction(() => document.readyState === 'complete')` 
This line performs a "manual" waiting for the `load` event
7) Run `node server.js` again and observe the exception is gone.
8) Comment that line back and make sure the exception appears again
9) Comment these lines in `client.js`:
```
import { it } from 'https://cdn.jsdelivr.net/npm/@bryntum/siesta@latest/index.js'
it('', () => {})
```
10) Observe the exception disappears (probably, since its a race condition).

The rootcause of the issue seems to be that `client.js` is importing some other big external module.

**Comment by canonic-epicure** [comment]
Actually, I just checked the docs and it seems the `page.goto()` method itself is supposed to wait for `load` event: https://playwright.dev/docs/api/class-page#page-goto

Please feel free to change the title of the of ticket

**Comment by pavelfeldman** [comment]
I started watching the video and noticed that your script has a `module` type. JavaScript modules are async, they imply `defer`, which I think explains the behavior you are observing.

You might want to use

```js
await page.waitForFunction(() => !!window.connect));
```

to ensure connect object is created.

**Comment by canonic-epicure** [comment]
@pavelfeldman 

> JavaScript modules are async, they imply defer

I don't think so, can you provide a link to spec or MDN?

For this simple test file:
```html
<!DOCTYPE HTML>
<html>
    <head>
        <script type="module">
            window.addEventListener('load', () => console.log('LOAD'))
            window.addEventListener('DOMContentLoaded', () => console.log('DOMContentLoaded'))
        </script>

        <script type="module" src="test1.js"></script>
        <script type="module" src="test2.js"></script>
    </head>

    <body>
    </body>
</html>
```

I receive the following output in console, both in Chrome and FF (`test1.js` and `test2.js` both contains a single `console.log()` call):
```
test1
test2
DOMContentLoaded
LOAD
```

**Comment by canonic-epicure** [comment]
I've managed to reduce the test case to a bare minimum. It seems the race condition happens when a module on page imports some other big module. It is not reproducible in Chromium/Firefox. I'll update the steps to reproduce.

**Comment by JoelEinbinder** [comment]
Module loading is async to allow for top level await. 

It sounds like your issue is with the timing of the load event in webkit, not whether playwright properly waits for it.

**Comment by pavelfeldman** [comment]
Scripts without async , defer or type="module" attributes, as well as inline scripts, are fetched and executed immediately, before the browser continues to parse the page.

**Comment by pavelfeldman** [comment]
I meant to comment, not close.

**Comment by pavelfeldman** [comment]
Nice explainer from Jake here: https://jakearchibald.com/2017/es-modules-in-browsers/

**Comment by canonic-epicure** [comment]
@pavelfeldman Hm.. I see, didn't know that, thanks for pointing.

However, according to[the `defer` attribute [description](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-defer)
>Scripts with the defer attribute will prevent the DOMContentLoaded event from firing until the script has loaded and finished evaluating.

So it does not affect the topic of this issue (`page.goto()` should wait for `load` event)

**Comment by canonic-epicure** [comment]
@JoelEinbinder Mm, no if you check the reproduce script `server.js`, it seems playwright really does not wait for the `load` event (`DomContentLoaded` to be precise). If you add a manual waiting for that event, exception does not appear.

**Comment by ThisIsMissEm** [comment]
I'm not sure if it's related, I think it may be though: I'm seeing weirdness in Safari on MacOS 12.1 relating to `page.waitForNavigation` and `page.click`, where I've a button that I'm clicking that triggers a form submission.

My page does use `defer` on a script tag, too.

The docs say to use:

```
await Promise.all([
  page.waitForNavigation({ waitUntil: "networkidle" }),
  page.click("form > button")
])
```

Which works on all browsers besides Safari, where I had to change to using:

```
await page.click("form > button")
await page.waitForNavigation({ waitUntil: "networkidle" }),
```

And then everything works as expected. I note that in the source code `waitForNavigation` and `waitForLoadState` use fairly similar code, hence suspecting this is error I'm observing is related.

**Comment by unlikelyzero** [comment]
I think i'm experiencing this; my waitforNavigation events are not working when running with webkit

**Comment by unlikelyzero** [comment]
@dgozman would https://github.com/microsoft/playwright/pull/14897 address this issue?

**Comment by dgozman** [comment]
@unlikelyzero This is a different issues, specific to WebKit and async modules. #14897 fixes a race condition in Playwright code.

**Comment by Itimol82** [comment]
__

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
