### ISSUE TITLE
[BUG] Run on GitLab: The argument --window-size=1920,1080 - opens resolution of 1028 X 696

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#8342]
**Context:**
- Playwright Version: 1.14
- Operating System: Windows
- Browser: Chromium (chrome)

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
import { PlaywrightTestConfig } from "@playwright/test";


const config: PlaywrightTestConfig = {
  retries: 1,
  timeout: 180000,
  globalTimeout: 300000,
  reporter: [["./my-reporter.ts"], ["list"], ["junit", { outputFile: "reports/test-results.xml" }]],
  use: {
    trace: 'on',
    screenshot: 'on',
    video: {
      mode: "on",
      size: {
        width: 1920,
        height: 1080
      }
    },
    contextOptions: {
      viewport: null,
    },
    // Browser options   
    launchOptions: {     
      channel: 'chrome', //Changed back to chromium due to the issue with chrome on CI
      headless: false,
      args: ['--window-size=1920,1080'],
      //args: ['--start-maximized']
    },
    //slowMo: 0,
  },
};

export default config;

```

**Describe the bug**

I perform the tests on GitLab runner. I defined the arguments of the resolution args: ['--window-size=1920,1080'], but actually it runs with 1028 x 696. 
I attach the screenshot and video. 
Do I have some mistakes with any of the configurations? 

[Attachment.zip](https://github.com/microsoft/playwright/files/7021021/Attachment.zip)

According to taken screenshot the resolution is:
![image](https://user-images.githubusercontent.com/52656401/130223823-11cea4dd-18bf-4352-ab5b-6485868c793d.png)

**Comment by JoelEinbinder** [comment]
We don't support `--window-size`, and if it works its only by accident. Does the same problem occur if you specify the viewport directly?

**Comment by AlexKomanov** [comment]
@JoelEinbinder 
I'll check the option of the viewport. 
The definition of the viewport should be added in the part of 'contextOptions' or of the 'use' part?

![image](https://user-images.githubusercontent.com/52656401/130324201-c0bdf4d3-37e0-449d-944a-2fd189a97a5e.png)

**Comment by AlexKomanov** [comment]
@JoelEinbinder 
I defined the resolution via viewport (I removed the window-size argument).
The issue still occurs. 
As can be seen from the attached video, that recorded with a resolution of 1920x1080 - the viewport resolution is less. See the attached video.

[738439920573b5fe0e85cdf48ef682f1.zip](https://github.com/microsoft/playwright/files/7025708/738439920573b5fe0e85cdf48ef682f1.zip)

Also, there is my 'playwright.config.ts' file:
![code](https://user-images.githubusercontent.com/52656401/130326134-2ee86a1c-e471-4564-b46e-530ef3c5a72b.png)

**Comment by AlexKomanov** [comment]
@JoelEinbinder 
I note that only the option of setting resolution inside the test file works as well. 
![image](https://user-images.githubusercontent.com/52656401/130351900-a487475f-af07-416e-892c-c268d6b84bbe.png)

Other attempts to change resolution on the GitLab run - didn't succeed.

**Comment by AlexKomanov** [comment]
Do I need to provide any additional information? Or it is good enough?

**Comment by JoelEinbinder** [comment]
@yury-s do we expect the video to be clipped here?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
