### ISSUE TITLE
[Question]"no tests found" issue with Jenkins

### ISSUE THREAD

**Issue by akshayp7** [microsoft/playwright#8344]
Hi team,

I have written my Playwright tests in typescript and naming convention is "TestCase.test.ts", I have placed them inside a folder named "tests". When I clone directly from repo and run test cases on local they are working fine. But when I try to execute the same in Jenkins I am getting "no tests found" error. 

Solutions tried:
1. Rename my folder from tests to test -> Didn't work
2. I tried given test case name directly in testMatch section of "playwright.config.ts"-> Didn't Work
3. I tried going to the workspace that jenkins had created i.e. ".jenkins->workspace->project" and tried executing the command npm run tests -> Didn't work.

Am I doing something wrong??

Playwright Version : 1.14.0

**Comment by JoelEinbinder** [comment]
I doubt there is something specific to jenkins going on here. It sounds like the file structure is different and somehow your tests are not where they should be. Without seeing the file structure its impossible for me to debug though.

**Comment by akshayp7** [comment]
![image](https://user-images.githubusercontent.com/78036666/130312104-0ece1390-3e27-4a68-8fb4-b8ba7acc30ea.png)
Image in LHS is my Jenkins structure and image on RHS is my local . Both have no changes. test cases are present in tests folder

**Comment by akshayp7** [comment]
Hi Joel,

   Thanks for responding. I just verified folder structure both Jenkins and Same both are same, Sorry can't provide a screenshot as its company specific.

**Comment by akshayp7** [comment]
Hi I am running directly on Docker container it is working fine now.
