### ISSUE TITLE
[Feature] Document improvement.  I have some tips want to add into document

### ISSUE THREAD

**Issue by cnmade** [microsoft/playwright#8351]
Hello, i want to add some tips to improve playwright document, but can not find the right place to put

Here are they

```
//string newHtmlText = await page.InnerTextAsync(".jxyzuvw_list");
string newHtmlText = await page.EvaluateAsync<string>("() => document.querySelector('div.jxyzuvw_list').innerText");
```

For anyone who want to capture DOM innerText, should better using EvaluateAsync and do not relay on innerTextAsync.

Because the EvaluateAsync will output the after calcluate DOM result, the page.InnerTextAsync won't capture the final result, it can not detected the page dom changed. (Such as dom insert, dom delete) it can not run more than once, and can not detect web page change.

For test purpose, if the webpage was changed by the Ajax request, you need know the after changes on the DOM.

**Comment by pavelfeldman** [comment]
These will output the same text. Both will get current innerText value of the dom node.

`page.innerText` is also better because it accepts all Playwright selector engines.

**Comment by cnmade** [comment]
no sir. @pavelfeldman `page.InnerTextAsync`  won't read DOM update, I test for one day. figure it out.
