### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JayKishoreDuvvuri** [microsoft/playwright#8354]
I found that playwright not taking screenshots and videos even after giving the screenshot: 'only-on-failure',
video: 'retry-with-video' in config file of playwright test runner with JavaScript. I'm using MacOS BigSur 11.5.2 is there any problem? retries is working fine. Not able to see the test-results folder with screenshots and video? I tried to to put OutputDir: in config file but still it did not Work?

**Comment by pavelfeldman** [comment]
Make sure you follow the docs, it should all work on all operating systems.

https://playwright.dev/docs/test-configuration#automatic-screenshots

**Comment by JayKishoreDuvvuri** [comment]
Yes I followed the same from the docs https://playwright.dev/docs/test-configuration#automatic-screenshots but couldn#t get the screenshots and videos

**Comment by akshayp7** [comment]
Are you using Node 12+ version??

**Comment by JayKishoreDuvvuri** [comment]
yes is that a problem?

**Comment by JoelEinbinder** [comment]
Your tests do not use the [`page`](https://playwright.dev/docs/api/class-fixtures#fixtures-page) provided by playwright test. Instead you launch your own browser and page. Configuring video and screenshots in the test runner only effects the pages launched by the test runner itself.

**Comment by JayKishoreDuvvuri** [comment]
I know you would say this. despite of using https://playwright.dev/docs/api/class-fixtures/#fixtures-page (Page) it worked in Jest and Playwright test runner until I updated to MacOS 11.5.2. Don't close this defect. Try running my repo on Jest https://github.com/JayKishoreDuvvuri/Playwright-Test-Runner and  https://github.com/JayKishoreDuvvuri/Playwright-Jest-Test-Automation-Framework on MacOS 11.0 or windows it will work without page. after all it is javascript. doesn't matter. I'm not satisfied to close the ticket. Please re-open this or else I will open a new issue. Thanks!
