### ISSUE TITLE
[Feature] off firefox video picture in picture browser options

### ISSUE THREAD

**Issue by jung-han** [microsoft/playwright#8357]
Hello! playwright team!
I am using E2E testing using @playwright/test, and I am using it with great satisfaction.

Currently, we are developing a video player, and in the case of firefox, the picture in picture feature is turned on, which is interfering with the element that should trigger a click event.

Currently, the click event is handled by `force`, but it would be nice to have an option to turn off the browser setting.

It's not urgent, so it would be good to consider it once!

* https://support.mozilla.org/en-US/kb/turn-picture-picture-mode

#### using version

```
"@playwright/test": "^1.14.0",
"playwright": "^1.14.0",
```

**Comment by jung-han** [comment]
Separately, I wonder if there is a fake timer that can be used like `@sinonjs/fake-timers`. Looking at the related issues, it seems difficult to go back to a separate process and use it. `waitForTimeout` is recommended to be used for debugging purposes. Is there any other recommended method?

**Comment by JoelEinbinder** [comment]
You can use [`firefoxUserPrefs`](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-option-firefox-user-prefs) to  change preferences without going into the settings manually.

> Sorry for writing so many things into one issue.
> 
> Separately, I wonder if there is a fake timer that can be used like `@sinonjs/fake-timers`. Looking at the related issues, it seems difficult to go back to a separate process and use it. `waitForTimeout` is recommended to be used for debugging purposes. Is there any other recommended method?

I don't think I have a good answer for you here. In the future please file a separate issue or comment on the one you are referring to.
