### ISSUE TITLE
[Feature] Ability to abort tracing

### ISSUE THREAD

**Issue by spegoraro** [microsoft/playwright#8359]
It would be awesome if tracing could be stopped without writing to a file.

The main use case for this is to do with scraping. In production, traces could be captured but only output in the event of some failure (e.g. the target site changing their layout). This way a developer investigating the logs can look into a failure and see what needs to be changed to adapt.

Edit: on further review of the source, does calling `tracing.stop()` without an options arg already achieve this? If so can we add it to the docs?

**Comment by unnati914** [comment]
could i work on this?

**Comment by JoelEinbinder** [comment]
You can just delete the trace file if you don't want it? Capturing the trace is way more expensive than outputting it. So I don't think this is a great pattern if you are trying to be speedy.
