### ISSUE TITLE
[Feature]: install-deps does not support debian 11

### ISSUE THREAD

**Issue by cnmade** [microsoft/playwright#8361]
### Feature request

install-deps does not support debian 11, need support debian 11

**Comment by mxschmitt** [comment]
Only Ubuntu 18 and Ubuntu 20 is supported, see here: https://playwright.dev/docs/library#system-requirements

**Comment by PlanetMacro** [comment]
This is ages old. Has it been resolved?

**Comment by mxschmitt** [comment]
Yes, Debian 11 is supported nowadays.
