### ISSUE TITLE
[Feature] Make Playwright install-deps work with NVM installations of Node/NPM

### ISSUE THREAD

**Issue by HyperCrowd** [microsoft/playwright#8367]
I have Node and NPM installed via NVM, which means my pathing to these executables are going to be different than OS-specific package management installation.

Playwright is asking me to run `sudo npx playwright install-deps` to install all the browser dependencies.

I don't have `npx` on root because I'm using NVM.  I used this hack to expose the executable to root:

```bash
sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/node" "/usr/local/bin/node"
sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/npm" "/usr/local/bin/npm"
sudo npm i -g npx
```

But this gives me an EACCESS error when trying to perform a directory rename during the `npx` install.

Can playwright ever work with an NVM installation of Node/NPM?

**Comment by HyperCrowd** [comment]
If I change:

```
sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/node" "/usr/local/bin/node"
sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/npm" "/usr/local/bin/npm"
sudo npm i -g npx
```

to:

```
sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/node" "/usr/local/bin/node"
sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/npm" "/usr/local/bin/npm"
sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/npx" "/usr/local/bin/npx"
```

It appears the `install-deps` process works.

**Comment by JoelEinbinder** [comment]
Glad you solved it. You can always run playwright directly from `node_modules/.bin/playwright` if you don't want to use npx.
