### ISSUE TITLE
[Feature] subscribe for selector being attached or visible 

### ISSUE THREAD

**Issue by radekBednarik** [microsoft/playwright#8376]
Hello,
this is probably a niche use-case, but why not try ;)

I have a situation, when on tested frontend there is a popup (modal) which will appear randomly. (there is some ML logic behind it, but nevermind that). I have no control over this behaviour.

Standard `page.waitForSelector()` will not help me in this case.

Would it be possible to create API in spirit of:

```javascript

on("selector", selector, callback)
```
or something like this?

I am able to create very crude polling promise which is "abusing" `setInterval()` and `page.$()`, but it has drawbacks - namely when popup will not appear, than I will get protocol error, because page will close before polling timeout, etc...

**Comment by JoelEinbinder** [comment]
Use waitForSelector and catch the errors would be my suggestion. We would implement this feature as waitForSelector + timeout = 0 + .catch, but there is nothing stopping you from doing it yourself.

**Comment by radekBednarik** [comment]
Thank you for the suggestion, I tottaly forgot, that you can disable the timeout. Will try this.

**Comment by radekBednarik** [comment]
@JoelEinbinder it works. thanks again for the suggestion.
