### ISSUE TITLE
[Feature] Test.fail for negative testing

### ISSUE THREAD

**Issue by PfrLisBerndt** [microsoft/playwright#8394]
Currently test.fail seems to work like test.skip.
My expectation on this feature was, that I can use it to realize negative testing; given invalid data, this test (step) fails and the next one will executed.

**Comment by pavelfeldman** [comment]
That's exactly what it should do. Could you post an example? Are you using test.serial?

**Comment by PfrLisBerndt** [comment]
I tried both, test.desribe and test.describe.serial

```
test.describe.serial("some_description", () => {
  test.beforeEach(async ({ page }) => {
// Go to https://www.wikipedia.de/
    await page.goto("/");
  });
  test.fail("foo", async ({ page }) => {
    await test.step("bar", async () => {
      await page.click('input[alt="Search Criteria"]');
      await page.fill('input[alt="Search Criteria"]', "shortcut");

      await page.click('button[name="not_existing_button"]');

      );
    });
  });

  test("next_foo", async ({ page }) => {
    ...
    });
  });
});
```

Output: 

>  -  [RAD] › ..\tests\systemtest\RAD\RAD_N1.test.js:14:8 › some_description foo
> ✓  [RAD] › ..\tests\systemtest\RAD\RAD_N1.test.js:39:3 › some_description next_foo (5s)
> 
> 
>   1 skipped
>   1 passed (7s)

I expected "foo" to pass when failed to click on "non_existing_button".

**Comment by pavelfeldman** [comment]
`test.fail` should be put inside the test:

```js
test("foo", async ({ page, browserName }) => {
  test.fail(browserName === 'webkit', 'Failes on WebKit');
});
```

(don't use serial, I was just exploring reasons)

**Comment by pavelfeldman** [comment]
See https://playwright.dev/docs/api/class-test#test-fail
