### ISSUE TITLE
[Question] about timer exists that can be used for testing

### ISSUE THREAD

**Issue by jung-han** [microsoft/playwright#8396]
Hello! Sorry for posting multiple questions.I'm testing video to E2E, and there are times when it's necessary to use a timer.

I wonder if there is a fake timer that can be used like @sinonjs/fake-timers. Looking at the related issues, it seems difficult to go back to a separate process and use it. waitForTimeout is recommended to be used for debugging purposes. I added a timer by importing it using `addScriptTag` and `evaluate`, but a scenario like clicking a button after 3 seconds seems impossible.

Is there any other recommended method?

**Comment by mxschmitt** [comment]
We have a feature request for emulating time/clock behaviour: https://github.com/microsoft/playwright/issues/6347

For now you need to use addScriptTag with evaluate or just evaluate to modify it.

**Comment by aslushnikov** [comment]
Closing this in favor of #6347
