### ISSUE TITLE
[Docs]: incorrect code example 

### ISSUE THREAD

**Issue by Gornostalev** [microsoft/playwright#8400]
https://playwright.dev/dotnet/docs/api/class-keyboard#keyboard-type
in code example have line with slow typing but without `double` argument
```
await page.Keyboard.TypeAsync("Hello"); // types instantly
await page.Keyboard.TypeAsync("World"); // types slower, like a user
```

**Comment by pavelfeldman** [comment]
Should update when we push the docs.
