### ISSUE TITLE
Reference to : [BUG] #8354

### ISSUE THREAD

**Issue by JayKishoreDuvvuri** [microsoft/playwright#8402]
I know you would say this. despite of not using https://playwright.dev/docs/api/class-fixtures/#fixtures-page (Page) it worked in Jest and Playwright test runner until I updated to MacOS 11.5.2. Don't close this defect. Try running my repo on Jest - https://github.com/JayKishoreDuvvuri/Playwright-Test-Runner and Playwright Test - https://github.com/JayKishoreDuvvuri/Playwright-Jest-Test-Automation-Framework on MacOS 11.0 or Windows it will work without page for sure. I guarantee you that it works. I used in my project in the company as well in the same way. after all it is javascript. doesn't matter.

If I don't use **page** according to your logic tests should not run at all with **retries** right, forget about the screenshots tests shouldn't run as well with retries. But i do got screenshots with the same framework trust me until I moved to MacOs 11.5.2.

If without using a **(Page)**, **Retries** is working then I expect Screenshot and videos to work.For reference from my github code mentioned above Playwright Test - https://github.com/JayKishoreDuvvuri/Playwright-Jest-Test-Automation-Framework , run this docker command on your PC

docker pull jaykishoreduvvuri/playwright:v1   
docker run -it jaykishoreduvvuri/playwright:v1  

if you have docker installed, please check and see **retires** works!

**Comment by pavelfeldman** [comment]
Apologies for closing this one as well. In order for us to be able to help / fix some issue, we need a reproducible use case, a small reduction that would show the problem. Could you file a new issue with just one test that would demonstrate an issue along with your expectations. Please forgive us for closing your bugs, but we are getting a dozen of bugs a day, so in order to be fixing them quickly we need high quality bugs.

**Comment by JayKishoreDuvvuri** [comment]
Hi Pavel, Thanks for your reply.

Steps to Re-produce:

1. Clone or download the Repo : `https://github.com/JayKishoreDuvvuri/Playwright-Test-Runner`
2. Run the command : `npm install`
3. By default this is headless. If you want to run in headed mode, In the pages/basePage.js add this line in this page like this:
4. 
```
async open() {
		browser = await chromium.launch({ headless: false })
		context = await browser.newContext()
		page = await context.newPage()
		await page.goto(this.path)
	}
```

5. run the individual test with command : `npm run toggle-product-colour-test`

6. See the playwright.config.js file below from the repo:
```
const config  = {
	use: {
		headless: true,
		screenshot: 'only-on-failure',
		video: 'retry-with-video'
	},
	timeout: 5000,
	retries: 1,
	reporter: 'line',
	outputDir: './screenshots'
}
module.exports = config;
```
Here except screenshot all like reporter, timeout and retries work.

7.  you get output on the terminal like this: 
```
playwright-test-automation@1.0.0 toggle-product-colour-test
> npx playwright test tests/toggleProductColour.test.js

Using config at /Users/jaykishore/Desktop/Playwright-Test-Runner-main/playwright.config.js

Running 7 tests using 1 worker
  1) tests/toggleProductColour.test.js:86:2 › Toggle between the colours of the Product Navigate to Landing Page 

    ReferenceError: navigateUrl1 is not defined

      87 |              await ProductPage.navigateToHomePage()
      88 |              expect(await ProductPage.getTitle()).toEqual(title)
    > 89 |              expect(await ProductPage.getUrl()).toEqual(navigateUrl1) // Remove 1 in the end of navigateUrl
         |                                                         ^
      90 |      })
      91 | })
      92 |

        at /Users/jaykishore/Desktop/Playwright-Test-Runner-main/tests/toggleProductColour.test.js:89:46
        at WorkerRunner._runTestWithBeforeHooks (/Users/jaykishore/Desktop/Playwright-Test-Runner-main/node_modules/@playwright/test/lib/test/workerRunner.js:425:7)

    Retry #1 ---------------------------------------------------------------------------------------

    ReferenceError: navigateUrl1 is not defined

      87 |              await ProductPage.navigateToHomePage()
      88 |              expect(await ProductPage.getTitle()).toEqual(title)
    > 89 |              expect(await ProductPage.getUrl()).toEqual(navigateUrl1) // Remove 1 in the end of navigateUrl
         |                                                         ^
      90 |      })
      91 | })
      92 |

        at /Users/jaykishore/Desktop/Playwright-Test-Runner-main/tests/toggleProductColour.test.js:89:46
        at WorkerRunner._runTestWithBeforeHooks (/Users/jaykishore/Desktop/Playwright-Test-Runner-main/node_modules/@playwright/test/lib/test/workerRunner.js:425:7)


  1 failed
    tests/toggleProductColour.test.js:86:2 › Toggle between the colours of the Product Navigate to Landing Page 
  6 passed (36s)
```

Please let me know if you need anything. Thanks very much for your support.
