### ISSUE TITLE
[Question]: Speed up test/tests now fail if exceeding timeout after update?

### ISSUE THREAD

**Issue by AveryTheDev** [microsoft/playwright#8404]
After updating `playwright` and `@playwright/test` to the latest versions available (^1.14.0), I've noticed a couple of interesting things.

1. it is significantly longer for pages to load and elements to be interactive in the test. I'm talking the first page loading in 5s to loading in 20s with no change in code. An element will not be clickable for longer periods. Some elements take 15 seconds as witnessed via videos recorded on failure as well as debugger.

2. The test will fail if the test exceeds the timeout limit (default or set) and has to wait for an element to be interactive. As a result, more of the tests are failing even with the test successfully completing the tasks.

Due to the above issue, we are experiencing a lot more false positives. Are there new settings in place that could slow down tests/cause failures after exceeding timeout?

**Comment by AveryTheDev** [comment]
The increase in page load time is consistent, but not the increased length in time it takes to select inputs or buttons. That varies but it seems to switch between one of the elements having an issue, rather than all or none are selectable in a reasonable time.

**Comment by pavelfeldman** [comment]
This is unexpected and concerning. Could you tell us more about your tests? Do you use @playwright/test or playwright+ other test runner? What is your config? Do you capture videos? Does switching back to 1.13 make it faster again? We need to repro it to localize it and fix it on our side...

**Comment by pavelfeldman** [comment]
Is that Chromium? What is the OS?

**Comment by AveryTheDev** [comment]
> Do you use @playwright/test or playwright+ other test runner? 

We use `@playwright/test` as the sole test runner at version `"^1.14.0"`. It has been installed with `playwright` at `"^1.14.0"`.

> What is your config?

Our config is the following

```js
import { PlaywrightTestConfig } from '@playwright/test';
import { baseUrl } from './e2e/constants';

const config: PlaywrightTestConfig = {
  outputDir: './e2e/test-results',
  globalSetup: './e2e/fixtures/global-setup.ts',
  use: {
    viewport: { width: 1440, height: 800 },
    video: 'retain-on-failure',
    storageState: './state.json',
    baseURL: baseUrl,
  },
};

export default config;
```

>  Do you capture videos?

Via the global config, we capture videos and they are retained-on-failure

> Is that Chromium? What is the OS?

The tests are run on Chromium and my OS is macOS Big Sur

> Does switching back to 1.13 make it faster again?

It did indeed make the test faster with a difference of 20s. We changed the version of Playwright to make use of the new Locator API, which has been more reliable as far as selecting elements and validating their presence in the page has been.

However,  considering the time difference along with the increase in test failures due to timeouts it may not be worth the change for us.

**Comment by AveryTheDev** [comment]
Just to have clarity, it is expected that the tests supposed to fail/stop automatically after timeout set (default 30s)?

If I do something like 

```js
test("Test Timeout Failure", async ({ page }) => {
  await page.waitForTimeout(28000);
  await page.goto("https://google.com"); //test fails here because it can't load the page before 30s has elapsed
  const header = await page.$("Google");
  expect(header).toBeTruthy();
});

```

It is expected that the test will stop and not continue because it is past 30s?

**Comment by AveryTheDev** [comment]
I am asking because initially, at version 1.13 that was not something that failed the tests but after a reinstall of that version, I've experienced the same behavior that was to me seemingly introduced with 1.14.

Wasn't certain if there was an error with my initial install on that regard.

**Comment by pavelfeldman** [comment]
> Just to have clarity, it is expected that the tests supposed to fail/stop automatically after timeout set (default 30s)

Yes, the test will 'time out'. Is that what you are seeing?

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
