### ISSUE TITLE
[DOCS] Incorrect args documented for reporter.OnStepbegin

### ISSUE THREAD

**Issue by Ghislain89** [microsoft/playwright#8411]
Today I had a fiddle with the custom reporter, it seems the documentation isn't entirely accurate. the argsfor `reporter.onStepBegin` and `reporter.onStepEnd` ([here](https://playwright.dev/docs/api/class-reporter)) are defined as `test, result, result`

Judging from  [this page](https://playwright.dev/docs/api/class-reporter#reporter-on-step-begin), it would make more sense to rename the last arg to step or teststep?

**Comment by pavelfeldman** [comment]
Thanks! It'll update next time we publish the docs.
