### ISSUE TITLE
[BUG] page.goto() with route interceptor no longer works with file:/// URLs.

### ISSUE THREAD

**Issue by LeviticusMB** [microsoft/playwright#8412]
**Context:**
- Playwright Version: 1.12.3 works, 1.13.0 and 1.14 does not
- Operating System: Mac
- Node.js version: v14.17.0
- Browser: Chromium (Firefox and WebKit works)

## System:
 - OS: macOS 11.5.2
 - Memory: 198.02 MB / 16.00 GB
## Binaries:
 - Node: 14.17.0 - /usr/local/opt/node@14/bin/node
 - Yarn: 1.22.10 - /usr/local/bin/yarn
 - npm: 6.14.13 - /usr/local/opt/node@14/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
## npmPackages:
 - playwright: ~1.13.0 => 1.13.1 

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');
const fs = require('fs');
const { cwd } = require('process');

const htmlFile = `${cwd()}/test-goto-file.html`
fs.writeFileSync(htmlFile, '<script>console.log("hello")</script>');

(async () => {
    for (const route of [false, true]) {
        for (const browser of [firefox, webkit, chromium]) {
            const instance = await browser.launch();

            try {
                console.log(`Launching ${instance._name}`);
                const page = await instance.newPage();

                console.log(route ? `Adding route interceptor` : `Not adding route interceptor`);

                if (route) {
                    page.route('**/*', async (route, req) => {
                        try {
                            console.debug(`route ${req.url()}`);
                            await route.continue();
                            console.debug(`continue ${req.url()}`);
                        } catch (err) {
                            console.error(err);
                        }
                    });
                }

                page.on('console', (message) => console.info(message.text()));

                console.log(`Loading ${htmlFile}`);
                await page.goto(`file://${htmlFile}`, { waitUntil: 'load' });
                console.log(`Loaded ${htmlFile}`);
            }
            finally {
                console.log(`Closing ${instance._name}`);
                await instance.close();
            }
        }
    }
})()
```

**Describe the bug**

Starting with 1.13.0, Chromium fails to `page.goto()` to `file:///` URL:s if a route interceptor has been attached to the `Page` object.

**Comment by pavelfeldman** [comment]
I am not sure we'll be fixing this one since file:// does not go through the network stack and routing it might become an uphill battle in the modern browsers going forward. Can you run it off localhost instead?

**Comment by LeviticusMB** [comment]
I guess I *could* but that would be a security issue for me. It's a command-line tool that uses Playwright to process HTML templates and data files specified as arguments. I would have to spawn a server that exposes everything local as long the tool is running.

**Comment by pavelfeldman** [comment]
>  I would have to spawn a server that exposes everything local as long the tool is running.

A bunch of options for you:

- You can navigate to http://localhost:1234, route it like you do and serve them off filesystem
- Or you can serve just one folder and as long as you use default macOS settings, your ports will be protected by the firewall. Spinning a localhost server during development is considered a good (and secure) practice.

In terms of the original bug, it is unlikely we'll be able to maintain file:// + routing long term, so closing this isse.

**Comment by LeviticusMB** [comment]
Just in case somebody else needs this: I solved it by using a "magic" host name as a HTTPS URL, and then handling it in the `page.route()` handler itself using `fulfill()`. Works like a charm.
