### ISSUE TITLE
[Feature] Manually clear waitsFors...

### ISSUE THREAD

**Issue by HyperCrowd** [microsoft/playwright#8418]
The webpage I'm trying to scrape is loaded to the gills with bad SPA practices, annoying anti-scrape features, an extremely slow server with random response times that require me to read console log output to determine progress, and all around terrible programming that makes it a real challenge to scrape properly.

I have to have multiple `waitFors...` established to account for different outcomes.  I would like the ability to clear waits manually if possible.  (Like `clearInterval` or `clearTimeout` in JavaScript). This will allow me to close all waits and then close the page without throwing errors every single time.

Does this feature exist?

**Comment by pavelfeldman** [comment]
Playwright is a framework for testing, not scraping.
