### ISSUE TITLE
[Bug] Project options do not apply to browsers launched manually

### ISSUE THREAD

**Issue by JayKishoreDuvvuri** [microsoft/playwright#8428]
Hi Pavel,

As you closed the bug:  #8354 #8402 and As discussed on previous bug comments, Please see below.

Steps to Re-produce:

1. Clone or download the Repo : https://github.com/JayKishoreDuvvuri/Playwright-Test-Runner
2. Run the command : `npm install` **( I did on MacOs 11.4 and MacOs 11.5.2)**
3. By default this is `headless`. If you want to run in `headed `mode, In the folder **pages/basePage.js** add this line in this basePage like this:
```
async open() {
		browser = await chromium.launch({ headless: false })
		context = await browser.newContext()
		page = await context.newPage()
		await page.goto(this.path)
	}
```
4. Run the individual test with command : `npm run toggle-product-colour-test`

5. See the playwright.config.js file below from the repo:

```
const config  = {
	use: {
		headless: true,
		screenshot: 'only-on-failure',
		video: 'retry-with-video'
	},
	timeout: 5000,
	retries: 1,
	reporter: 'line',
	outputDir: './screenshots'
}
module.exports = config;
```

Here except screenshot and headless options, all the other options like reporter, timeout and retries work.

6. You get output on the terminal like this:

```
playwright-test-automation@1.0.0 toggle-product-colour-test
> npx playwright test tests/toggleProductColour.test.js

Using config at /Users/jaykishore/Desktop/Playwright-Test-Runner-main/playwright.config.js

Running 7 tests using 1 worker
  1) tests/toggleProductColour.test.js:86:2 › Toggle between the colours of the Product Navigate to Landing Page 

    ReferenceError: navigateUrl1 is not defined

      87 |              await ProductPage.navigateToHomePage()
      88 |              expect(await ProductPage.getTitle()).toEqual(title)
    > 89 |              expect(await ProductPage.getUrl()).toEqual(navigateUrl1) // Remove 1 in the end of navigateUrl
         |                                                         ^
      90 |      })
      91 | })
      92 |

        at /Users/jaykishore/Desktop/Playwright-Test-Runner-main/tests/toggleProductColour.test.js:89:46
        at WorkerRunner._runTestWithBeforeHooks (/Users/jaykishore/Desktop/Playwright-Test-Runner-main/node_modules/@playwright/test/lib/test/workerRunner.js:425:7)

    Retry #1 ---------------------------------------------------------------------------------------

    ReferenceError: navigateUrl1 is not defined

      87 |              await ProductPage.navigateToHomePage()
      88 |              expect(await ProductPage.getTitle()).toEqual(title)
    > 89 |              expect(await ProductPage.getUrl()).toEqual(navigateUrl1) // Remove 1 in the end of navigateUrl
         |                                                         ^
      90 |      })
      91 | })
      92 |

        at /Users/jaykishore/Desktop/Playwright-Test-Runner-main/tests/toggleProductColour.test.js:89:46
        at WorkerRunner._runTestWithBeforeHooks (/Users/jaykishore/Desktop/Playwright-Test-Runner-main/node_modules/@playwright/test/lib/test/workerRunner.js:425:7)


  1 failed
    tests/toggleProductColour.test.js:86:2 › Toggle between the colours of the Product Navigate to Landing Page 
  6 passed (36s)

```
Please let me know if you need anything. Thanks very much for your support.

**Comment by pavelfeldman** [comment]
> Retries, timeout, reporter are working absolutely fine for me from the playwright.config.file. Why not screenshot and videos working if these all config options above work?

This is expected:
- @playwright/test consists of two layers: generic test runner and Playwright fixtures
- Retries and reporter are the test runner settings, they control runner and are decoupled from Playwright, so they work
- Screenshots and videos are the Playwright fixture settings, specified in { use: {} }, those only affect other fixtures such as `page`, `context`, etc.

So I while I understand that this might be confusing, that's the design we'd like to stick with for long term maintenance. So we'll be addressing it with the docs as I mentioned above.

**Comment by JayKishoreDuvvuri** [comment]
Thanks Pavel for explaining it. However, without using fixture like page, I did get screenshot and video for my internal company project. But the same page object automation framework is not here with this repo in my very first comment. 

I mean  it should be uniform right? my internal company project did worked fine with screenshot and videos but same thing is not working with this repo! Looks strange to me though! Thank you for your support!

**Comment by pavelfeldman** [comment]
Sorry, there isn't anything I can add here. We'll try to work on the docs to better explain how it works and why.

**Comment by aminaodzak** [comment]
@dgozman Has this ever solved actually? 

We are hitting a wall to generate video for report, when using persistent browser context.

**Comment by dgozman** [comment]
@aminaodzak Video options are not applied to your `launchPersistentContext()` calls. This should be covered by #11833.
