### ISSUE TITLE
[Internal]: Roll Chromium and fix build infra

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#8436]
Chromium with Symbols bots can't compile, the last roll seemed like a bad one tho.

**Comment by aslushnikov** [comment]
turned out to be a whole lot of issues:
- mac builders died after migration to a new hardware
- goma cookie died so had to be renewed
- there was a bug in the chromium-with-symbols build so it didn't build with symbols, actually

All are fixed now.
