### ISSUE TITLE
[Question]: What does the err means?

### ISSUE THREAD

**Issue by niewiemczego** [microsoft/playwright#8437]
### Your question

Hi Im using firefox and sometimes got this message: `NS_BINDING_ABORTED; maybe frame was detached?`
Any idea how to fix it and why it occurs?

**Comment by aslushnikov** [comment]
@niewiemczego the error would happen when e.g. the page navigates while you're running some operation on the page. So the advice would be to make sure that page doesn't navigate unpredictably!

**Comment by pavelfeldman** [comment]
@niewiemczego: we need a repro to be able to fix it. NS_BINDING_ABORTED is an internal Firefox error, not a Playwright error. You can read more about it here: https://stackoverflow.com/questions/704561/ns-binding-aborted-shown-in-firefox-with-httpfox
