### ISSUE TITLE
[BUG] WebKit scrollbars are not hidden

### ISSUE THREAD

**Issue by FezVrasta** [microsoft/playwright#844]
**Context:**
- Playwright Version: 0.10.0
- Operating System: macOS

**Code Snippet**

N/A

**Describe the bug**

`chromium` and `firefox` hide scrollbars by default, while `webkit` shows them. This makes difficult to perform image snapshot comparison tests across browsers.

WebKit should hide scrollbars by default, to be consistent with the other 2 browsers.

**Comment by aslushnikov** [comment]
@FezVrasta can you show your screenshot?

**Comment by mmarkelov** [comment]
@aslushnikov for example:
- Webkit
![2](https://user-images.githubusercontent.com/22371328/73911299-ace89380-48c2-11ea-8eb1-1d3ed00750bd.jpg)
- Chrome
![1](https://user-images.githubusercontent.com/22371328/73911326-ba9e1900-48c2-11ea-95d0-a1bdd65b952b.jpg)

**Comment by Anrb13** [comment]
Still have dat issue on windows, webkit - devices - iphone 8.
playwright@1.2.1
![2020-08-06T18-33-08 939Z_iphone](https://user-images.githubusercontent.com/53814667/89568828-8b924100-d82c-11ea-9348-ddda45632c4a.jpeg)
![2020-08-06T18-16-49 254Z_iphone](https://user-images.githubusercontent.com/53814667/89568834-8c2ad780-d82c-11ea-8718-25889dc8288b.jpeg)
![2020-08-06T18-30-24 798Z_iphone](https://user-images.githubusercontent.com/53814667/89568837-8cc36e00-d82c-11ea-9f19-3f5bdc265309.jpeg)
![2020-08-06T18-32-21 374Z_iphone](https://user-images.githubusercontent.com/53814667/89568838-8d5c0480-d82c-11ea-8202-81182cb329c3.jpeg)

**Comment by Pomax** [comment]
Same, I'm still seeing screenshots taken with the [example code from the README.md](https://github.com/microsoft/playwright/blob/master/README.md#page-screenshot) look fine for Chromium and Firefox, whereas Webkit shows a big old bar of "nothing", completely throwing off automated screenshot image comparisons.

Even for screenshots that use `full_page=True`, which by its very nature should mean that there is no vertical scrollbar.
