### ISSUE TITLE
[Question] How to create a new Browser instance per test in @playwright/test

### ISSUE THREAD

**Issue by archlichking** [microsoft/playwright#8459]
Hi team, this question is about the Browserstack integration with `@playwright/test` and relates to https://github.com/microsoft/playwright/issues/8379.

According to [Playwright's doc](https://playwright.dev/docs/1.13.0/core-concepts#browser), all tests in one worker run in one browser instance, and I observe the same behavior. With code in https://github.com/microsoft/playwright/issues/8379#issuecomment-905741931, all tests in the same test file, which are assigned to the same worker,  run in the same browser session in Browserstack. This behavior results in one single long Browserstack test session, and we cannot really mark test status (pass/fail) for a test on Browserstack.

The expected behavior would be, to run one test per Browserstack session. I didn't find a better way to do this by overriding browser fixture, so I override the page fixture like this

```js
  page: async ({ page, browser }, use, testInfo) => {
    const caps = {
      browser: 'chrome',
      os: 'osx',
      os_version: 'catalina',
      name: 'My first playwright test',
      build: 'playwright-build-1',
      'browserstack.username': process.env.BROWSERSTACK_USERNAME,
      'browserstack.accessKey': process.env.BROWSERSTACK_ACCESS_KEY,
      'client.playwrightVersion': '1.13.1',
    };
    const vBrowser = await chromium.connect({
      wsEndpoint:
        `wss://cdp.browserstack.com/playwright?caps=` +
        `${encodeURIComponent(JSON.stringify(caps))}`,
    });
    // new browser context per page per test
    const vPage = await vBrowser.newPage(testInfo.project.use);
    await use(vPage);

    const testResult = {
      action: 'setSessionStatus',
      arguments: {
        status: testInfo.status,
        reason: JSON.stringify(testInfo?.error),
      },
    };
    await vPage.evaluate(() => {}, `browserstack_executor: ${JSON.stringify(testResult)}`);

    await vBrowser.close();
  },
```

In this way each test runs as a separate Browserstack session and we can mark its status successfully.

However, when I run tests in parallel (like more than 2 workers), frequently this error shows up

```bash
browserType.connect: connect ETIMEDOUT 207.254.8.24:443. Most likely ws endpoint is incorrect
```

When this error shows up, no websocket connection is established for current test.

I'm using `@playwright/test@1.13.1`. When use the same version 1.13.1 in [Browserstack's example repo](https://github.com/browserstack/playwright-browserstack), tests are correctly executed and queued from Browserstack side.

I suspect something goes wrong in `@playwright/test` as there is always one browser instance up and doing nothing in the way how I override the page fixture. Please let me know if there is a better way of creating a new browser instance per test, or any more info we need to reproduce this.

**Comment by pavelfeldman** [comment]
You should probably direct this question to browserstack!
