### ISSUE TITLE
[Feature] Treshold for test failed/passed

### ISSUE THREAD

**Issue by PfrLisBerndt** [microsoft/playwright#8464]
My structure is: 
```
test.describe("TEST", () => {
 
  test("TEST_PART_1", async ({ page }) => {
  //...
  });

  test("TEST_PART_2", async ({ page }) => {
 //...
  });

  test("TEST_PART_3", async ({ page }) => {
 //...
  });
   
});
```

If now one of these parts fails, the whole run is declared as failed afterwards. 
Is it possible to implement the option to define a treshold to have a run declared as passed though some parts have failed?

**Comment by pavelfeldman** [comment]
No such option and it is unlikely that we introduce one, this would be a quite unusual contract. A couple of tools that could help you are:
- Tag some of the tests as 'blocker' and require that they all pass. And for the other tests you can ignore the exit code. See https://playwright.dev/docs/test-annotations#tag-tests for tagging
-  You can also implement your own reporter that would analyze the test results and produce its own alternative exit code: https://playwright.dev/docs/test-reporters#custom-reporters
