### ISSUE TITLE
[BUG] tracing.stop: Must start tracing before exporting

### ISSUE THREAD

**Issue by BeataKr** [microsoft/playwright#8466]
**Context:**
- Playwright Version: 1.14.0
- Operating System: Linux
- Node.js version: 16.6.2 / 14.15.5
- Browser: Chromium
- Extra: -

**Description**

Till working with playwright v1.13 code starts failing with v1.14 due to **tracing.stop: Must start tracing before exporting** error (in a case when we have failed test).
Looks like _beforeEach_ block doesn't use setup() (I'm extending my custom playwright environment with PlaywrightEnvironment from jest-playwright-preset) where I have:
```javascript
await this.global.context.tracing.start({ screenshots: true, snapshots: true });
```

Any idea for a workaround?

**Comment by mxschmitt** [comment]
Closing since its stale.

**Comment by xrash** [comment]
I'm having this issue. Maybe it's a misunderstanding on how fixtures are supposed to work.

I set up a minimal example to reproduce it. Please clone https://github.com/xrash/pwt-tracing-bug-example, then run `yarn` and `npx playwright test`.
