### ISSUE TITLE
[Feature] Make the steps API log the steps to console.

### ISSUE THREAD

**Issue by shtlrs** [microsoft/playwright#8470]
Currently, the newly released steps API doesn't keep a log of the steps being executed in the console.
It would be helpful for tracking purposes to log the steps in console in a tree-fashion

It'll be something like this:

status testSuite
            -step1
            -step2

Reference: https://playwright.slack.com/archives/CSUHZPVLM/p1629978340015400

**Comment by khalilyamoun** [comment]
much needed !

**Comment by pavelfeldman** [comment]
Which reporter would you like to see it in?

**Comment by shtlrs** [comment]
I think it makes sense to have this in the line & list reports, what do you think ?

**Comment by pavelfeldman** [comment]
I believe this has been implemented, please feel free to reopen with the exact items that were not addressed.

**Comment by shtlrs** [comment]
> I believe this has been implemented, please feel free to reopen with the exact items that were not addressed.

Sweet, in which release has this been implemented ?
