### ISSUE TITLE
[Feature] Support test.step in JSON reporter

### ISSUE THREAD

**Issue by keevie** [microsoft/playwright#8475]
Pretty self-explanatory -- I'd love to have the new test steps api reflected in the json reports!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by grappler** [comment]
This comment is not really correct. The issue was fixed in https://github.com/microsoft/playwright/pull/8476

> #### Why was this issue closed?
> We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

Currently, the steps are only added when running the test but not when using `--list`
