### ISSUE TITLE
[Feature] Allow different 'Test run options' for different projects

### ISSUE THREAD

**Issue by ychaudhari** [microsoft/playwright#8479]
Currently in version 1.14.1,  as per [the docs](https://playwright.dev/docs/test-advanced/#:~:text=Each%20project%20can%20be%20configured%20separately%2C%20and%20run%20different%20set%20of%20tests%20with%20different%20parameters.%20See%20test%20suite%20options%20for%20the%20list%20of%20options%20available%20to%20each%20project.), in configuration, only 'Test suite options' can be provided under different `projects`.

**use case:** We have two projects, one of which requires a `globalSetup` for saving state (and testDir) and other doesn't work with the global setup. Currently there is no way to configure two projects with one configuration. Having this feature will make the configuration much easier.

**Comment by mxschmitt** [comment]
Does creating multiple configurations work for you? You can pass them via the `--config` parameter.

**Comment by pavelfeldman** [comment]
As per above, we recommend using different projects when run options are different!
