### ISSUE TITLE
[Feature] Standalone application for Trace Viewer

### ISSUE THREAD

**Issue by uchagani** [microsoft/playwright#8481]
Sometimes it is necessary to pass along trace files to people that don't have the node/java/etc installed.  It would be nice to have a standalone app or something that resembles that so we can share trace files easily.

for example, i’m using playwright-java and if i run `mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="show-trace myTrace.zip"`  outside of my project directory, i get the error: `Goal requires a project to execute but there is no POM in this directory (C:\Users\someUser). Please verify you invoked Maven from the correct directory.`  A standalone app would allow us to pass traces around without people needing to clone the project to view it.

**Comment by kevinbarabash** [comment]
It would be nice if the trace viewer could provide a list of the tests it has traces for along with a way to switch between them without having to restart the app.

**Comment by mxschmitt** [comment]
This gets released as part of version 1.18 of Playwright, stay tuned!
