### ISSUE TITLE
[Feature] Separate HTTP credentials per domain

### ISSUE THREAD

**Issue by azhawkes** [microsoft/playwright#8487]
Playwright allows you to set HTTP credentials when creating a context with `browser.newContext({ httpCredentials })`. Unfortunately, this doesn't support the use case of visiting multiple sites or domains in the same context. 

The current behavior of sending the same credentials to all visited sites is undesirable and possibly even a security risk.

Also, since `browserContext.setHTTPCredentials` has been deprecated, there's no supported way to supply new credentials before navigating to another domain.

It would be great if we could specify different credentials per domain, perhaps like this:

```
browser.newContext({
    httpCredentials: {
        "www.example1.com": {
            username: "username1",
            password: "password1"
        },
        "www.example2.com": {
            username: "username2",
            password: "password2"
        }
    }
});
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
