### ISSUE TITLE
[BUG] Select all bug when migrating from Puppeteer to Playwright (affects Firefox)

### ISSUE THREAD

**Issue by codex-zaydek** [microsoft/playwright#849]
I’m running the current version of Playwright, that would be 0.10, and I’m running on a Mac 10.14.6 and running Playright via Yarn/Jest.

As I’m experienced with Puppeteer, I thought I needed to do something like this:

```js
		// https://github.com/puppeteer/puppeteer/issues/1313
		await page.evaluate(() => document.execCommand("selectall", false, null))
		await page.keyboard.press("Backspace")
```

In order to select all and delete an editable region.

When doing so, I get the following (only concerning `firefox` -- `chrome` and `webkit` appear to be unaffected):

```
    Evaluation failed: {}

      12 | 		await page.focus("[contenteditable]")
      13 | 		// https://github.com/puppeteer/puppeteer/issues/1313
    > 14 | 		await page.evaluate(() => document.execCommand("selectall", false, null))
         | 		^
      15 | 		await page.keyboard.press("Backspace")
      16 | 		await page.keyboard.type("Hello, world! 😀", { delay: 50 })
      17 | 		await browser.close()

      at checkException (node_modules/playwright-core/lib/firefox/ffExecutionContext.js:155:19)
      at FFExecutionContext.evaluate (node_modules/playwright-core/lib/firefox/ffExecutionContext.js:92:9)
      at Object.<anonymous> (src/components/Editor/__tests/playwright.test.js:14:3)
```

It turns out, to my surprise, that `Meta` does work in Playwright, so the following code *does work*:

```js
		page.keyboard.down("Meta")
		page.keyboard.down("a")
		page.keyboard.down("Meta")
		page.keyboard.down("Backspace")
```

I don’t know if this is a regression, but I was definitely surprised and perceived Playwright as not working the first time around.

I also wanted to mention that `firefox` opens in the background, which is unlike `chrome` and `webkit`. ~Also, the `webkit` binary renders without anti-aliasing, so it’s very fuzzy,~ and the monkey emoji 🙊 at the top UI is a bit disconcerting.

I hope this helps -- thanks.

**Comment by aslushnikov** [comment]
> When doing so, I get the following (only concerning firefox -- chrome and webkit appear to be unaffected):

@codex-zaydek Well, yeah - firefox does not support `selectall` in their execCommand. browsers! :man_shrugging: 

Meta-A probably doesn't work on chromium though (according to @JoelEinbinder at least)

The good news is that Playwright has a [`page.fill`](https://github.com/microsoft/playwright/blob/master/docs/api.md#pagefillselector-value-options) method that can be used to clear fields:

```js
await page.fill('input', '');
```

Or, I guess you actually want to type into the input - so you can just
```js
await page.fill('input', 'some text');
```

Behind the back, it selects the text in the text input in a cross-browser way and fills the area with your text.

**Comment by codex-zaydek** [comment]
Thanks Andrey!

Can I assume `fill` works with a contenteditable node? I’m not using `<input>` or `<textarea>`.

Also, I wanted to follow-up:

> Also, the webkit binary renders without anti-aliasing

So that can be fixed with this: `await page.setViewport({ deviceScaleFactor: 2 })` -- it wasn’t obvious to me but might put some users off.

**Comment by codex-zaydek** [comment]
> Meta-A probably doesn't work on chromium though (according to @JoelEinbinder at least)

I can confirm this.

**Comment by codex-zaydek** [comment]
If anyone’s reading this, this is what I’m using to perform a select all and delete that works in all browsers:

```js
await page.focus("[contenteditable]")
await page.keyboard.down("Meta")
await page.keyboard.press("a", options)
await page.keyboard.up("Meta")
try {
	// https://github.com/microsoft/playwright/issues/849
	await page.evaluate(() => document.execCommand("selectall", false, null))
} catch (e) {
	// No-op
}
await page.keyboard.press("Backspace", options)
```

**Comment by jperl** [comment]
This is what I am doing FWIW.

```
export const clearElement = async (
  elementHandle: ElementHandle
): Promise<void> => {
  // Select the element's content and press backspace to clear the element
  // We do this instead of setting the value directly since that does not mimic user behavior.
  // Ex. Some sites might rely on an isTrusted change event which we cannot simulate.
  // https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange
  // https://developer.mozilla.org/en-US/docs/Web/API/Window/getSelection
  // https://stackoverflow.com/a/3806004/230462
  const hasValue = await elementHandle.evaluate((element: HTMLInputElement) => {
    const value = element.isContentEditable ? element.innerText : element.value;

    if (!value || value.length <= 0) return false;

    element.focus();

    if (element.setSelectionRange) {
      element.setSelectionRange(0, value.length);
    } else if (window.getSelection && document.createRange) {
      const range = document.createRange();
      range.selectNodeContents(element);

      const selection = window.getSelection();
      if (selection) {
        selection.removeAllRanges();
        selection.addRange(range);
      }
    }

    return true;
  });

  if (hasValue) {
    logger.verbose("clearElement: clear value");
    await elementHandle.press("Backspace", undefined);
  } else {
    logger.verbose("clearElement: no value to clear");
  }
};
```

https://github.com/qawolf/qawolf/blob/master/packages/browser/src/actions/clearElement.ts

**Comment by codex-zaydek** [comment]
Thanks @jperl! I’ll try integrating something like this later. If it helps, [this is my playwright e2e test suite](https://github.com/codex-src/codex-app/tree/097e6b617d35d35627bc9f46ca9c8194542eea0f/src/components/Editor/__tests).

And [these are my helper functions for interfacing with playwright](https://github.com/codex-src/codex-app/blob/097e6b617d35d35627bc9f46ca9c8194542eea0f/src/components/Editor/__tests/playwright.js).

**Comment by jperl** [comment]
I’ll definitely check those out. Thanks!

**Comment by jperl** [comment]
For anyone looking at this issue in the future, in case it is helpful. We [changed the logic](https://github.com/qawolf/qawolf/pull/426/files) from clearing then typing, to just selecting all then typing. Since if you select all first, it will replace the content. This has been tested across all browsers for content editables, text inputs, date inputs, time inputs.

```
import { logger } from "@qawolf/logger";
import { ElementHandle } from "playwright";

export const selectElementContent = async (
  elementHandle: ElementHandle
): Promise<void> => {
  // Select the element's content
  // https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange
  // https://developer.mozilla.org/en-US/docs/Web/API/Window/getSelection
  // https://stackoverflow.com/a/3806004/230462
  logger.verbose(`selectElementContent`);

  await elementHandle.evaluate((element: HTMLInputElement) => {
    // When element.select() is supported by browsers we can use that instead
    // https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/select
    if (element.setSelectionRange) {
      try {
        element.setSelectionRange(0, element.value.length);
      } catch (e) {
        // setSelectionRange throws an error for inputs: number/date/time/etc
        // we can just focus them and the content will be selected
        element.focus();
      }
    } else if (window.getSelection && document.createRange) {
      const range = document.createRange();
      range.selectNodeContents(element);

      const selection = window.getSelection();
      if (selection) {
        selection.removeAllRanges();
        selection.addRange(range);
      }
    }
  });
};
```

**Comment by andyjessop** [comment]
> The good news is that Playwright has a [page.fill](https://github.com/microsoft/playwright/blob/master/docs/api.md#pagefillselector-value-options) method that can be used to clear fields

@aslushnikov this doesn't work with tools like `ace-editor`, where the input area is not `input`/`textarea`, etc. It would need to be done by cmd+a instead. Would be great to have a cross-browser way to handle this.
