### ISSUE TITLE
[Question] :has-text() case sensitive

### ISSUE THREAD

**Issue by Nhasa** [microsoft/playwright#8494]
I found that `className:has-text("text")` is case insensitive. How can we use `className:has-text("text")` selector to be case sensitive? 

Note: I tried all text selector from the docs and only has-text that satisfy my use case.

**Comment by abhi10shek** [comment]
> Does this not work?
> 
> `div.section:has(h2:text-is(“Target 2”))`

I used page.textContent and it worked perfectly for me as well.

**Comment by Nhasa** [comment]
@uchagani @abhi10shek thanks for your answers! Yes that's work for that specific use case. 

Unfortunately, it doesn't work in my use case. My use case is more abstract as we should not relying DOM structure. In another word we don't really care where `Target 2` will be placed in the DOM. We only want which `div.section` has text `Target 2` inside. Below is the illustration to help understand the use case. 
```html
<div class="section">
  <x>
    <xx>
      <xxx>
        <xxxx>
          <xxxxx>target 2</h2> 
        </xxxx>
      </xxx>
    </xx>
  </x>
</div>
<div class="section"> <!-- i want this div.section  -->
  <x>
    <xx>
      <xxx>
        <xxxx>
          <xxxxx>Target 2</h2> 
        </xxxx>
      </xxx>
    </xx>
  </x>
</div>
```

**Comment by uchagani** [comment]
You don’t have to:

`div.section:has(:text-is(“Target 2”))` or if that doesn’t work you can use the text selector with regex:

`div.section:has(text=/Target 2/)`

**Comment by Nhasa** [comment]
@uchagani thanks for your answer. 

> `div.section:has(:text-is(“Target 2”))`

this one doesn't work in my use case as well

> `div.section:has(text=/Target 2/)`

I got this error => Unexpected token "=" while parsing selector

**Comment by dgozman** [comment]
I believe that `div.section:has(:text-is(“Target 2”))` should just work. It definitely works for me on the example above.

`:has(:text("foo"))` is a full equivalent of `:has-text("foo")`, and you just want to change `:text()` to `:text-is()` for case sensitive match.

If this does not work for some reason, could you please provide a sample DOM and a selector that do not work for you as expected?

**Comment by Nhasa** [comment]
@dgozman thanks for you reply. The use case is to select element `.section` (can be any element not only div) and has text `Target 2` in it (can be placed in random children of the .section element)

```html
<div class="section">
  <span>
    <div>
      <div>
        <span>
          <h2>target 2</h2> 
        </span>
      </div>
    </div>
  </span>
</div>
<div class="section"> <!-- i want this div.section  -->
  <span>
    <div>
      <div>
        <!-- no h2  -->
        <span>Target 2</span>
      </div>
    </div>
  </span>
</div>
```

**Comment by uchagani** [comment]
So get rid of the div:

`page.textContent(“.section:has(:text-is(“Target 2”))`

**Comment by yury-s** [comment]
Please reopen if suggested solution doesn't work.

**Comment by Nhasa** [comment]
@uchagani thanks for your answer, Yes that's working.

It turns out my use case is like `string.includes()` behavior. So this selector is the best fit for my use case `.section:has(:text-matches(“Target 2”))`.

Sorry for the confusion.
