### ISSUE TITLE
[BUG] Documentation enumerable described as strings

### ISSUE THREAD

**Issue by dajunhuo** [microsoft/playwright#8497]
**Context:**
- Playwright Version: 1.14.0
- Operating System: NA
- Node.js version: NA
- Browser: NA
- Extra: Documentation Issue

**Describe the bug**

https://playwright.dev/dotnet/docs/api/class-page#page-wait-for-selector
Options state parameter is described as a String when it's actually an enumerable

**Comment by pavelfeldman** [comment]
Got it.
