### ISSUE TITLE
[REGRESSION]: fixture is now inherited to browser.newPage()

### ISSUE THREAD

**Issue by seunghunee** [microsoft/playwright#8498]
**Context:**
- GOOD Playwright Version: 1.13.0
- BAD Playwright Version: 1.14.1
- Operating System: Linux

**Code Snippet**

This work in 1.13.0 but not 1.14.1:
```ts
// Test mobile app with mobile user agent
test.use({ storageState: "state-mobile.json", ...devices["iPhone 7"] });

test.beforeAll(async ({ browser }) => {
  // Before test, we have to do some job with desktop user agent
  const page = await browser.newPage({ storageState: "state-admin.json" });
  // ...
});
```

**Describe the bug**

The fixture specified with `test.use()` now inherited to `browser.newPage()` in v1.14.0
In v1.13.0, no matter what fixture is used, `browser.newPage()` can create a clean state new page.
Which one is correct?
If this was a bug of v1.13.0, is there a better way than following?
```ts
test.use({ storageState: "state-mobile.json", ...devices["iPhone 7"] });

test.beforeAll(async ({ browser }) => {
  const page = await browser.newPage({ storageState: "state-admin.json", ...devices["Desktop Chrome"] });
  // ...
});
```

**Comment by seunghunee** [comment]
Thanks for quick responses.

@dgozman 
> Does this work for you?

But It doesn't work
```
Error: Cannot use({ defaultBrowserType }) in a describe group, because it forces a new worker.
Make it top-level in the test file or put in the configuration file.
```

Do I have to specify a browser like `browser.newPage({ ...devices["Desktop Chrome"] })`?

**Comment by dgozman** [comment]
@seunghunee I was trying to come up with a nicer workaround, but unfortunately was not able to.

Although your snippet works fine, I'd suggest to be more explicit and set `userAgent` and/or `isMobile` if you'd like them different in `beforeAll`:
```js
test.use({ storageState: "state-mobile.json", ...devices["iPhone 7"] });

test.beforeAll(async ({ browser }) => {
  // Passing "undefined" resets user agent to the default one. You can also pass any specific user agent here.
  const page = await browser.newPage({ storageState: "state-admin.json", userAgent: undefined, isMobile: false });
  // ...
});
```

**Comment by seunghunee** [comment]
Thank you.
