### ISSUE TITLE
[Question] Save localStorage between it blocks execution?

### ISSUE THREAD

**Issue by novakalexx** [microsoft/playwright#8506]
Hey guys ,
I'm trying out playwright as a possible alternative to the cypress stack we use in my company.
I can't figure out how to save local storage between it blocks.
Pretty much webdriverio/protractor does this out of the box, and in cypress i've solved this by using this snippet:

```
Cypress.Commands.add("saveLocalStorage", () => {
  Object.keys(localStorage).forEach(key => {
    LOCAL_STORAGE_MEMORY[key] = localStorage[key];
  });
});
```

and then 
```
beforeEach(() => {
    cy.restoreLocalStorage();
});
```

```
afterEach(() => {
    cy.saveLocalStorage();
});
```

How can I achieve this using playwright?

**Comment by pavelfeldman** [comment]
It looks like you are fighting the cleanup that  jest-playwright is doing for you. We don't support jest-playwright, it is a community project. We recommend using @playwright/test with Playwright. It's serial mode and/or auth reuse patterns should support your use case well:

https://playwright.dev/docs/auth#reuse-authentication-in-playwright-test
https://playwright.dev/docs/test-parallel#serial-mode

**Comment by mxschmitt** [comment]
Closing since it seems answered. Please create a new issue otherwise.
