### ISSUE TITLE
[Feature] Get browser version from persistent context

### ISSUE THREAD

**Issue by szmarczak** [microsoft/playwright#8508]
[`persistentContext.browser()` returns `null`](https://playwright.dev/docs/api/class-browsercontext#browser-context-browser) so currently it's not possible to get the [browser version](https://playwright.dev/docs/api/class-browser#browser-version).

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
