### ISSUE TITLE
[Feature] Add instructions for getting codegen to run from within a devcontainer

### ISSUE THREAD

**Issue by jongio** [microsoft/playwright#8509]
I would like to be able to run `npx playwright codegen uri` from within a devcontainer, but obviously the user will need to wireup x-display, etc.

We do have a script here that we should look at getting to work and integrating into the playwright docs.

https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docs/desktop-lite.md

azsdke2e
azsdke2e2

**Comment by aslushnikov** [comment]
@jongio Your blogpost seems to be a good-enough place for this recommendation! It's ranked pretty high up in google search results for the "playwright dev container" query.
