### ISSUE TITLE
[Feature] Make it easier to bundle playwright

### ISSUE THREAD

**Issue by mhils** [microsoft/playwright#8512]
#### Problem Description

I have a use case where I want to bundle some code with playwright into a standalone JS file:

```typescript
import {chromium} from "playwright";
console.log(chromium);
```
Doing that with esbuild currently produces multiple warnings and one error:
```shell
esbuild --bundle --platform=node main.ts
 > node_modules/playwright/lib/server/chromium/crApp.js:28:67: warning: "./appIcon.png" should be marked as external for use with "require.resolve"
    28 │   const icon = await _fs.default.promises.readFile(require.resolve('./appIcon.png'));
       ╵                                                                    ~~~~~~~~~~~~~~~

 > node_modules/playwright/lib/server/electron/electron.js:168:51: error: Could not resolve "electron/index.js" (mark it as external to exclude it from the bundle)
    168 │         command: options.executablePath || require('electron/index.js'),
        ╵                                                    ~~~~~~~~~~~~~~~~~~~

 > node_modules/playwright/lib/utils/registry.js:207:23: warning: This call to "require" will not be bundled because the argument is not a string literal (surround with a try/catch to silence this warning)
    207 │   const browsersJSON = require(_path.default.join(packagePath, 'browsers.json'));
        ╵                        ~~~~~~~

2 warnings and 1 error
```

The first warning is fine and can optionally be suppressed with `--external:"*.png"`. 

The following error I don't quite understand (there is no `electron/index.js` anywhere in my playwright distribution), 
but it can also be fixed easily with `--external:"electron/index.js"`.

The final warning hints at the only serious problem, namely a runtime error that occurs when invoking the compiled `main.js`: 
```
internal/modules/cjs/loader.js:888
  throw err;
  ^

Cannot find module '/browsers.json'
```

If one manually patches `browsers.json` into the compiled `main.js`, the resulting standalone JS file works perfectly fine.

#### Proposal

It would be really useful if `browsers.json` could be imported more regularly so that bundling just works. For example, `require('../../browsers.json')` does just work on my platform. I assume there is some reason for not doing that? Alternatively, if `browsers.json` would be located in `src/utils`, `require('./browsers.json'))` could be used and that'd just work as esbuild (and other bundlers) can deal with simple string literals.

#### Version Information
```
$ esbuild --version
0.12.24
$ npx playwright --version
Version 1.14.1
```

**Comment by aslushnikov** [comment]
>  I think all that needs to be changed is in mhils@7b3b918

@mhils I left a comment there. Overall, patch looks harmless to me. Feel free to send a PR, if noone complains we'll land it in.
Do keep in mind though that this is a "best-effort" on our side, so things might break in future!
