### ISSUE TITLE
[BUG] `webServer.reuseExistingServer` doesn't work with servers bound to a specific address

### ISSUE THREAD

**Issue by targos** [microsoft/playwright#8513]
**Context:**
- Playwright Version: 1.14
- Operating System: Mac
- Node.js version: 16.8.0
- Browser: N/A
- Extra: N/A

**Code Snippet**
```javascript
const net = require('net');

const existingServer = net.createServer();
existingServer.listen(3000, '127.0.0.1', () => {
  canBindPort(3000).then((result) => {
    console.log(`Can bind port: ${result}`);
    existingServer.close();
  });
});

async function canBindPort(port) {
  return new Promise((resolve) => {
    const server = net.createServer();

    server.on('error', () => resolve(false));
    server.listen(port, () => {
      server.close(() => {
        resolve(true);
      });
    });
  });
}
```

**Describe the bug**

Above is a copy of the `canBindPort` function from `node_modules/@playwright/test/lib/test/webServer.js`.
The script starts a server that listens on `127.0.0.1:3000`, then calls `canBindPort(3000)`, which returns `true` when it shouldn't. The function only returns `false` if the `existingServer` is started without passing a specific address.

Found this while using the [`Vite`](https://vitejs.dev/) dev server.

**Comment by FokkeZB** [comment]
The current implementation also doesn't detect servers that aren't running with `SO_REUSEADDR`.

Funny enough using a socket like Playwright does in `waitForSocket` _would_:

https://github.com/microsoft/playwright/blob/d3a8c38b7e8a8bbf5aea0f7d9ad277f02a292bd9/src/test/webServer.ts#L121-L129

I'll do a PR to repurpose that to fix this issue.
