### ISSUE TITLE
[Feature] "Release notes" anchors: add version as needed to prevent rot

### ISSUE THREAD

**Issue by mrienstra** [microsoft/playwright#8515]
The [Release notes](https://playwright.dev/docs/release-notes) page contains various anchors for convenience, however the anchors within each version do not contain the version, and thus the release of a new version often "clobbers" (by adding a higher-on-the-page duplicate) older anchors.

This may cause confusion, for example if someone had used https://playwright.dev/docs/release-notes#playwright-test to link to the "Playwright Test" section of the "Version 1.13" release notes, which now points to the "Playwright Test" section of the "Version 1.14" release notes.

A simple (in theory) solution: include the version in the anchor as needed. In the example I gave above:
https://playwright.dev/docs/release-notes#playwright-test
... might become:
https://playwright.dev/docs/release-notes#v1.13-playwright-test
(or something like that)

I took a quick look through the repo (found [docs/development/releasing.md](https://github.com/microsoft/playwright/blob/master/docs/development/releasing.md) & [utils/draft_release_notes.sh](https://github.com/microsoft/playwright/blob/master/utils/draft_release_notes.sh)), wasn't clear how this might be accomplished.

**Comment by pavelfeldman** [comment]
I'll close this feature request, because we could not prioritize it, but would be happy to accept a PR with the fix from anyone!
