### ISSUE TITLE
[BUG] context.newPage always launches in Default chrome profile

### ISSUE THREAD

**Issue by VikramTiwari** [microsoft/playwright#852]
**Context:**
- Playwright Version: 0.10.0
- Operating System: Mac
- Extra: Using chrome and not the bundled chromium

**Code Snippet**
Gist link: https://gist.github.com/VikramTiwari/56a6ff6d46496efc3613d624c9e8cd80

**Describe the bug**
- Would have expected the new page to open in the same context where the browser was launched with.
- Or a better feature would be to launch pages in specific chrome profiles

Another connected bug:
- I would have expected `userDataDir` to work properly but seems like it defaulted to using the temporary location

Screenshot:
<img width="1353" alt="Screen Shot 2020-02-05 at 3 15 38 PM" src="https://user-images.githubusercontent.com/1330677/73892524-0c479480-482c-11ea-88c3-083d51f22664.png">

From screenshot:
- Profile path should be "Profile 1" for both pages
- Profile path should start be the `${userDataDir}/${profileId}` vs temporary path it is right now.

**Comment by pavelfeldman** [comment]
Could you share more about your use case? I just removed access to the default profile from the browsers that connects remotely via `browserType.connect`, so the scenario from your snippet won't be possible.

**Comment by VikramTiwari** [comment]
Hey @pavelfeldman The aim is to run automated scripts on the user's browser that is already set up with their accounts etc. This requires the ability to:
- Launch existing browser
- With already set up user data directory
- And specific profile

I am unsure what your change enables. Does it enable:
- launch `chrome + userDataDir + profile-1` (would work) or 
- launch `chrome + userDatDir` and choose profile during runtime (ideal solution)

**Comment by pavelfeldman** [comment]
In 0.10 you need to use `browser.defaultContext` to fetch context associated with userDataDir. All new contexts you create are incognito there.

In the latest version of the Playwright code we added explicit `launchPersistent(userDataDir)` option that returns a `BrowserContext` that corresponds to that profile directory and removed `browser.defaultContext`.

**Comment by pavelfeldman** [comment]
Please reopen in case there are still outstanding issues!

**Comment by VikramTiwari** [comment]
Thanks @pavelfeldman :)
