### ISSUE TITLE
[Feature] Add the time each step took to trace viewer

### ISSUE THREAD

**Issue by uchagani** [microsoft/playwright#8524]
The trace viewer captures each step that playwright takes.  It would be great if we could have how long each step took so we can easily identify which steps are causing slowness in tests.

**Comment by MacaulayKoontz** [comment]
Question, Not sure if it belongs here. I'm am looping a test by 10,000 to load data into a database. Was wondering if there's a way to record the time each step took. So I can look at the data on certain steps and have statistical data with 10,000 samples.
