### ISSUE TITLE
[Feature] Downloads

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright#853]
It would be nice to have an api like:

```js
page.on('download', async download => {
   const buffer = await download.data();
   console.log('got download', download.url(), buffer.length);
});
```

We can hack it with `Page.setDownloadBehavior` in chromium and monitoring the download folder, but it would be nicer to have something like download interception in all of the browsers.

Should the event come when the download starts, or when it finishes? I think when it starts.

Previous discussion in puppeteer: puppeteer/puppeteer#299

**Comment by JoelEinbinder** [comment]
@aslushnikov what do you think?

**Comment by KevinYeramian** [comment]
@joelbyford have you tried https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-downloadWillBegin?

**Comment by joelbyford** [comment]
Believe that comment was for @JoelEinbinder instead 😄

**Comment by pavelfeldman** [comment]
Download event is now available.
