### ISSUE TITLE
[feature] support tab share permission 

### ISSUE THREAD

**Issue by DhairyaBahl** [microsoft/playwright#8532]
### Description 

Unable to do tab share in google meet.

### Target Browsers

Firefox: Doesn't support tab-share
Chromium : your browser can't share your screen
Google chrome , brave :  Doesn't have permission to screen share.

### Screenshots

Google chrome & brave : 
<img src = "https://user-images.githubusercontent.com/71627983/131230478-863d003f-2cce-4169-95e1-f82b086cd697.png" width=600>

Chromium : 
<img src = "https://user-images.githubusercontent.com/71627983/131230506-628625b4-3dcd-454d-bae1-ee2fe529a1fe.png" width = 600>

**Comment by aslushnikov** [comment]
@DhairyaBahl We currently don't support tab share permission; so let it be a feature request

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by hungdao-testing** [comment]
Hi all,

 Per on the discussion, I would take a chance to ask, hope you could help to share the way to select a specific screen from the modal below
![image](https://user-images.githubusercontent.com/51052135/182415292-97a3f1a4-4acc-405a-a09b-93d029b19a7d.png)

I also configured the chromium option but not help

```ts
const context = await chromium.launch({
            args: [
                '--auto-select-desktop-capture-source=Entire Screen',

            ],
            headless: false,

        });
        const page = await context.newPage();
        await page.goto("https://www.screenleap.com/login");
```
