### ISSUE TITLE
[BUG] Can't resolve 'electron/index.js' in newest version.

### ISSUE THREAD

**Issue by oscarmoraog** [microsoft/playwright#8534]
**Context:**
- Playwright Version: v1.14.1
- Operating System: Ubuntu 20.04.3 LTS
- Node.js version: v10.19.0
- Browser: Chrome Version 92.0.4515.159 (Official Build) (64-bit)
- Extra: No details

**Code Snippet**
Error:
./node_modules/playwright//lib/server/electron/electron.js
Module not found: Can't resolve 'electron/index.js'

Related some similar behavior in issue #7508

**Describe the bug**
There is no index.js file in electron folder

**Comment by pavelfeldman** [comment]
What is your code snippet?

**Comment by oscarmoraog** [comment]
Thanks, seems it was the issue. Ubuntu only have v10 in their repository, so probably more people like me will arrive here with the same issue.
