### ISSUE TITLE
[Feature] Add webServer.host to check against and use specific host in baseURL

### ISSUE THREAD

**Issue by FokkeZB** [microsoft/playwright#8538]
This would fix one cause of #8513 although #8537 addresses it in a better way.

But more importantly this makes `baseURL` indirectly set by `webServer` no longer always needs to be `localhost:<port>` but can also be `<host>:<port>`.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
