### ISSUE TITLE
[Feature]: Don't throw when loading storageState

### ISSUE THREAD

**Issue by jamiehaywood** [microsoft/playwright#8539]
If loading a `state.json` file that doesn't exist, I would expect the context to be created without throwing but perhaps a warning and `storageState` resolving to be undefined.

```
// `state.json` does not exist locally

const context = await browser.newContext({ storageState: 'state.json' });

// Exception: Error: browser.newContext: ENOENT: no such file or directory, open 'state.json'
```

Happy to raise a PR if this would be welcomed functionality. I'm thinking something along the lines of:
```ts
const readAndParseFileIfExists = async (path) => {
  try {
    return JSON.parse(await fs.readFile(path, 'utf8'));
  } catch (e) {
    if (e.code === 'ENOENT') return undefined;
    throw e;
  }
};
```

```
storageState: typeof options.storageState === 'string' ? readAndParseFileIfExists(options.storageState) : options.storageState
```
https://github.com/microsoft/playwright/blob/3bf33183500b150abf9198bba8cba7706481d7cc/src/client/browserContext.ts#L363

**Comment by pavelfeldman** [comment]
That would be a very unusual contract, similar to fs.readFileSync returning undefined if the file does not exist. If the file does not exist, this is clearly a bug on user's side, we should be explicit about it and throw.

**Comment by jamiehaywood** [comment]
@pavelfeldman thanks for the quick response. I completely get where you're coming from. I guess I was looking at it from an dev ergonomics perspective - rather than the consumer doing a check for the file, the check for the file is done in the library.

**Comment by pavelfeldman** [comment]
Got it. Ergonomics-wise, the sooner we fail, the more helpful it is to the user. Instead of figuring out why the test does not work, they would know that they forgot to create the file! Thanks for the report anyways, appreciate all the input in making our api more user-friendly!
