### ISSUE TITLE
[Feature] mouse detect if it's a cursor or a hand or just an arrow

### ISSUE THREAD

**Issue by SirineMrabet-Mobimeo** [microsoft/playwright#8541]
Hello Beautiful Team,
I would like to thank you for your continuous efforts. I'm a beginner using Playwright, I wanted to ask you if there is a  possibility to detect the pointer of a mouse after a hover if it's a hand or a cursor or an arrow.
Many thanks

**Comment by aslushnikov** [comment]
>  I wanted to ask you if there is a possibility to detect the pointer of a mouse after a hover if it's a hand or a cursor or an arrow.

@SirineMrabet-Mobimeo this is not possible from the OS-perspective. The best you could do is get computed styles of the element and check the "cursor" property.

> I would like to thank you for your continuous efforts. 

Thank you for the warm words!

**Comment by SirineMrabet-Mobimeo** [comment]
Hey @aslushnikov , 
Thanks for the hint. I really appreciate it.
Just if someone have the same question mark, the following works perfectly:
`    const page = this.page!;
    await page.hover(MiroPage.Sign_in_Button_Selector);
    var element = await page.waitForSelector(MiroPage.Sign_in_Button_Selector);;
    var icon_cursor = await element.evaluate((el) => {
        return window.getComputedStyle(el).getPropertyValue('cursor');
    });
    expect(icon_cursor).toBe('pointer');

    await page.hover(MiroPage.Email_Selector);
    element = await page.waitForSelector(MiroPage.Email_Selector);;
    icon_cursor = await element.evaluate((el) => {
        return window.getComputedStyle(el).getPropertyValue('cursor');
    });
    expect(icon_cursor).toBe('text');`
