### ISSUE TITLE
[Question] How to `page.query_selector` with regex for id?

### ISSUE THREAD

**Issue by playgithub** [microsoft/playwright#8543]
The samples below failed, error as invalid XPath expression.

```python
wifi_switch_btn = await page.wait_for_selector(r'xpath=//*[re:match(@id, "wifi(On|Off)2G_btnId")]', strict=True)
```

```python
wifi_switch_btn = await page.wait_for_selector(r'xpath=//*[matches(@id, "wifi(On|Off)2G_btnId")]', strict=True)
```

**Comment by aslushnikov** [comment]
@playgithub i didn't try running your code snippet, but it looks like you should pass a string in there instead of a regex. Try the following:

```py
wifi_switch_btn = await page.wait_for_selector('xpath=//*[matches(@id, "wifi(On|Off)2G_btnId")]', strict=True)
```

**Comment by playgithub** [comment]
> @playgithub i didn't try running your code snippet, but it looks like you should pass a string in there instead of a regex. Try the following:
> 
> ```python
> wifi_switch_btn = await page.wait_for_selector('xpath=//*[matches(@id, "wifi(On|Off)2G_btnId")]', strict=True)
> ```

Tried, same result, `r` before is to save escape chars.
Is regex supported?

**Comment by mxschmitt** [comment]
Playwright [uses xpath 1](https://stackoverflow.com/questions/25455351/does-chrome-use-xpath-2-0) under the hood, since the browsers only support xpath v1. In your case, something like this should work for you:

```py
wifi_switch_btn = await page.wait_for_selector('css=[id="wifiOn2G_btnId"],[id="wifiOff2G_btnId"]"', strict=True)
```

**Comment by playgithub** [comment]
> Playwright [uses xpath 1](https://stackoverflow.com/questions/25455351/does-chrome-use-xpath-2-0) under the hood, since the browsers only support xpath v1. In your case, something like this should work for you:
> 
> ```python
> wifi_switch_btn = await page.wait_for_selector('css=[id="wifiOn2G_btnId"],[id="wifiOff2G_btnId"]"', strict=True)
> ```

After removing the `"` after `]` as below, it work
```python
```
wifi_switch_btn = await page.wait_for_selector('css=[id="wifiOn2G_btnId"],[id="wifiOff2G_btnId"]', strict=True)
```

Thanks
```
