### ISSUE TITLE
[Feature][HTML report] Inform report data json fail to be downloaded

### ISSUE THREAD

**Issue by fcollonval** [microsoft/playwright#8549]
When loading a HTML report directly from the local file, the user is presented with the misleading `You are awesome` although it failed to load the JSON report due to CORS error.

The best solution would be to allow opening the report directly without the need for a server. But at least it would be good to display a error message (and a suggestion to start a simple server to view the report) if the report data is undefined.

![image](https://user-images.githubusercontent.com/8435071/131349538-5d0f3afd-21d0-42f1-b9b0-5929751aebb1.png)

**Comment by dgozman** [comment]
#8788 now shows the error message. We are exploring the solutions besides running the server.
