### ISSUE TITLE
[Bug]: [Error] Protocol error (Runtime.callFunction): error in channel "content::page" while scrolling down the page

### ISSUE THREAD

**Issue by chwba** [microsoft/playwright#8554]
### Playwright version

1.14.0-1629718845000

### Operating system

Windows

### What browsers are you seeing the problem on?

Firefox

### Other information

Python 3.9.6

### What happened? / Describe the bug

I am scrolling down a feed (like on facebook) using the provided code-snippet. After a bit of runtime I get the provided exception/log output. It apparently crashes the whole thread, as "still scrolling" is not being printed anymore after the exception was logged.

### Code snippet to reproduce your bug

```python
have_reached_bottom_of_page = False
def my_response_handler():
    global have_reached_bottom_of_page
    response_text = response.text()
    if response_text and "information_signalizing_bottom_of_page_reached" in response_text:
        have_reached_bottom_of_page = True


playwright = sync_playwright().start()
browser = playwright.firefox.launch(headless=True, , ignore_default_args=["--mute-audio"])
context = browser.new_context(
                bypass_csp=True,
                ignore_https_errors=True,
                java_script_enabled=True,
                proxy=prepared_proxy_dict,
)
page = context.new_page()
page.goto("https://example.com")
page.on("response", my_response_handler)

while not have_reached_bottom_of_page:
    try:
        log.info("still scrolling...")
        page.evaluate("""() => {
                window.scrollTo(0, 1000000);
            }""")
    except Exception as e:
        log.debug(f"[{e.__class__.__name__}] {e}")
        sleep(1)
# ....
```

### Relevant log output

```shell
[Error] Protocol error (Runtime.callFunction): error in channel "content::page": exception while running method "callFunction" in namespace "page": undefined undefined _onMessage@chrome://juggler/content/SimpleChannel.js:149:16
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
```

**Comment by chwba** [comment]
Here with a full traceback:
![image](https://user-images.githubusercontent.com/22568014/131396322-7651b6ae-d894-4e85-b464-53230bd9196e.png)

So apparently it just takes extra long until it appears - one has to scroll a long while (my scroll height was 988628 when it dropped).

**Comment by pavelfeldman** [comment]
Sadly, I don't think we'll be able to help here. Something like a 10 line script that allows us reproducing the behavior would help a lot. Please file a new issue and link this one if you manage to get us something we can act upon!

**Comment by chwba** [comment]
Well it only happens after you scroll a long time on a website, that has a feed which repopulates more content on scrolling if any and its quite interesting that it always happens at around the same scroll height 950.000 - 1.000000 - not sure how I could provide a smaller/simpler example.
