### ISSUE TITLE
[Feature] access current device inside a test

### ISSUE THREAD

**Issue by mjvdende** [microsoft/playwright#8568]
Maybe just add device to the globals?

for example:

in a test:
 
```ts
...
await page.screenshot({ path: `${deviceName}-${browserName}-my_screenshot.png` })
...
```

because I am defining my projects in ```playwright.config.ts```
```ts
...
const config: PlaywrightTestConfig = {
  projects: [
    // "Pixel 4" tests use Chromium browser.
    {
      name: 'Pixel 4',
      use: {
        browserName: 'chromium',
        ...devices['Pixel 4'],
      },
    },
...
```

**Comment by aslushnikov** [comment]
@mjvdende if you use `expect.toMatchSnapshot()` function, then projectName is already included in the snapshot suffix - so you'll have it there. 

Would it work?

**Comment by mjvdende** [comment]
@aslushnikov I am using a cloud tool to compare screenshots. So I think this will not work.  I extended expect to use this tool

```
await expect(image).screenshotCompareTool(`${browserName}-hover`)
```

I am trying to create an unique screenshot name and send it for comparison for example
chrome-stable-test-case-name.png
or
iphone13-webkit-test-case-name.png

**Comment by pavelfeldman** [comment]
https://playwright.dev/docs/api/class-testinfo#test-info-output-path will give you a unique path. You can re-base it to any location outside test-results and use it as a unique path.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by mjvdende** [comment]
I managed to figure I can use ```project```. Thanks for your help and patience!  

```ts
await expect(image).screenshotCompareService(`${testInfo.title}-${testInfo.project.name}`)
```
