### ISSUE TITLE
[BUG] `postData` is not applied for POST request

### ISSUE THREAD

**Issue by indapublic** [microsoft/playwright#8572]
**Context:**
> Playwright Version: [what Playwright version do you use?]

playwright@1.14.1

> Operating System: [e.g. Windows, Linux or Mac]

OSX 11.4 (20F71)

> Node.js version: [e.g. 12.22, 14.6]

v15.14.0

> Browser: [e.g. All, Chromium, Firefox, WebKit]

Chromium, Firefox

```
  System:
    OS: macOS 11.4
    Memory: 100.27 MB / 16.00 GB
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    Yarn: 1.22.11 - /opt/homebrew/bin/yarn
    npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
  npmPackages:
    playwright: ^1.14.1 => 1.14.1
```

**Code Snippet**

```typescript
import { chromium, Request, Route } from "playwright"

(async () => {
    const browser = await chromium.launch({ headless: false, devtools: true })
    const browserContext = await browser.newContext({ ignoreHTTPSErrors: true })
    const page = await browserContext.newPage()
    await page.route("https://example.com", (route: Route, request: Request): void => {
        route.continue({
            headers: {
                "Accept": "*/*",
                "Content-Type": "application/x-www-form-urlencoded",
                "X-Requested-With": "XMLHttpRequest",
            },
            method: "POST", 
            postData: "foo=bar",
        })
    })
    const response = await page.goto("https://example.com")
})()
```

**Describe the bug**

Request is `GET` and `postData` is not applied for GET request

<img width="336" alt="image" src="https://user-images.githubusercontent.com/856260/131433872-b6a615ae-4ace-4be6-8780-41604db07ed3.png">

<img width="364" alt="image" src="https://user-images.githubusercontent.com/856260/131433854-232ace29-8a57-4a39-a447-06f331a320af.png">

**Comment by indapublic** [comment]
Just tried with `http://httpbin.org/post` instead of `https://example.com` and it works so it's POST request I assume, but `postData` not applied still

<img width="352" alt="image" src="https://user-images.githubusercontent.com/856260/131434636-456c460d-b739-4a55-9493-b9ee5daad9da.png">

**Comment by pavelfeldman** [comment]
It is being sent, it is just that DevTools is clueless about it. You should check on the server side that they are delivered.
