### ISSUE TITLE
[Feature] Show parsed stacktrace in the Allure report

### ISSUE THREAD

**Issue by MindaugasMateika** [microsoft/playwright#8576]
It would be great if parsed stack trace would appear in the Allure report like in the line reporter. It would more convenient to understand where the test broke.

Allure:

![Screenshot at Aug 31 10-46-26](https://user-images.githubusercontent.com/17873445/131463689-5eaa61cb-f64b-4404-8e70-56539419d563.png)

Line:
```
    Error: expect(received).toBeTruthy()

    Received: false

      11 |   await loginPage.typeLoginInformation('user', 'pass')
      12 |   await loginPage.clickSubmit()
    > 13 |   await feedPage.mainHeader.assertUserMenuButtonIsVisible()
         |   ^
      14 | })
      15 |

        at /Users/mindaugasm/web-e2e-tests/pages/components/MainHeader.ts:22:59
        at TestTypeImpl._step (/Users/mindaugasm/web-e2e-tests/node_modules/@playwright/test/lib/test/testType.js:196:7)
        at MainHeader.assertUserMenuButtonIsVisible (/Users/mindaugasm/web-e2e-tests/pages/components/MainHeader.ts:21:5)
        at /Users/mindaugasm/web-e2e-tests/tests/BasicTests.ts:13:3
        at WorkerRunner._runTestWithBeforeHooks (/Users/mindaugasm/web-e2e-tests/node_modules/@playwright/test/lib/test/workerRunner.js:426:7)
```

**Comment by pavelfeldman** [comment]
I like how you folks instantly produce 5 upvotes :)

**Comment by MindaugasMateika** [comment]
Sorry, just shared the issues with the team 😅

**Comment by pavelfeldman** [comment]
Let's route it to https://github.com/allure-framework/allure-js/tree/master/packages so that we could track issues next to the code.

**Comment by pavelfeldman** [comment]
I can't transfer, so I'll close this one and hope you file it there.
