### ISSUE TITLE
[BUG] Can't close remote context

### ISSUE THREAD

**Issue by DavertMik** [microsoft/playwright#858]
**Context:**
- Playwright Version: 0.1.0
- Operating System: Linux
- Extra: remote browser connection

While dealing with remote browser connection I try to iterate over all contexts and close all of them.
However, I receive an error that connection is closed even it doesn't set to be so:

```js
const contexts = await this.browser.browserContexts();

  for (let c of contexts) {
      console.log('context', c);
      await c.close();
    }
```
Console.log prints that ths context is not closed:

```
closed BrowserContext {
  _closed: false,
  _delegate: {
    pages: [AsyncFunction: pages],
    existingPages: [Function: existingPages],
    newPage: [AsyncFunction: newPage],
    close: [AsyncFunction: close],
    cookies: [AsyncFunction: cookies],
    clearCookies: [AsyncFunction: clearCookies],
    setCookies: [AsyncFunction: setCookies],
    setPermissions: [AsyncFunction: setPermissions],
    clearPermissions: [AsyncFunction: clearPermissions],
    setGeolocation: [AsyncFunction: setGeolocation]
  },
```
but when I call `.close()` explicitly it throws an error.

```
 Error: Protocol error (Target.disposeBrowserContext): Session closed. Most likely the browser has been closed.
```
I just received information from a browser context of a browser and it's very strange that a browser is already closed. I also do not close the browser asynchronously at this point.

**Comment by pavelfeldman** [comment]
With https://github.com/microsoft/playwright/pull/863, we are changing the semantics of connections to the remote browsers. `browser.close()`-ing the browser that was obtained via `browserType.connect` will clean up all the contexts created by this browser instance and leave `BrowserServer` alive. The playwright-side change is up for review, bu there are going to be browser-side changes that would make it fail-proof. I'm currently filing bugs for them.

**Comment by pavelfeldman** [comment]
This is now done.
