### ISSUE TITLE
[Question] 1 . How to get all select option list from selectbox element  ? 2. select value from selectbox with spaces not working.

### ISSUE THREAD

**Issue by dimag25** [microsoft/playwright#8580]
Hello , I have 3 questions about select option functionality :
1. how can I retrieve all option values as a list?
2. when Im trying to select option by label its working only for options with one word(without spaces).
3. Is it possible to retrieve value by option text/label?

- in example:
-  currentFrame.selectOption(selector,new SelectOption().setLabel("Broker")); Working good

-   currentFrame.selectOption(selector,new SelectOption().setLabel("Cedant Company")); -
-Not working (tried also with spaces string as : "Cedant&nbsp;Company")

we have the following select element:
![image](https://user-images.githubusercontent.com/11368130/131476079-e008b05a-9abf-45c8-b8ab-ae0de57fad59.png)

Thank you,
Dima
``

**Comment by dimag25** [comment]
<select class="DSEL" name="sel_sing" size="2" style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"></select>
<select class="DSEL" name="sel_sing" size="15" style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 13px; font-weight: normal; display: block; width: 249px; height: auto; top: 209px; left: 474px; visibility: visible;" dir="ltr" tabindex="9">
   <option value="-2"></option>
   <option value="0">Assumed&nbsp;Company&nbsp;(Reinsured)</option>
   <option value="1">Broker</option>
   <option value="2">Cedant&nbsp;Company</option>
   <option value="3">Commutation&nbsp;Retention</option>
   <option value="4">Gross&nbsp;Retention</option>
   <option value="5">Insurance&nbsp;Company</option>
   <option value="6">Lloyds&nbsp;Syndicate</option>
   <option value="7">Other&nbsp;Recoverable</option>
   <option value="8">Other&nbsp;Reinsurer</option>
   <option value="9">Pool</option>
   <option value="10">Primary&nbsp;Retention</option>
   <option value="11">Reinsurer</option>
   <option value="12">Ceding</option>
   <option value="13">Secondary&nbsp;Retention</option>
   <option value="14">Inuring&nbsp;Retention</option>
</select>

**Comment by dimag25** [comment]
`[<select class="DSEL" name="sel_sing" size="2" style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);"></select>
<select class="DSEL" name="sel_sing" size="15" style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 13px; font-weight: normal; display: block; width: 249px; height: auto; top: 209px; left: 474px; visibility: visible;" dir="ltr" tabindex="9">
   <option value="-2"></option>
   <option value="0">Assumed&nbsp;Company&nbsp;(Reinsured)</option>
   <option value="1">Broker</option>
   <option value="2">Cedant&nbsp;Company</option>
   <option value="3">Commutation&nbsp;Retention</option>
   <option value="4">Gross&nbsp;Retention</option>
   <option value="5">Insurance&nbsp;Company</option>
   <option value="6">Lloyds&nbsp;Syndicate</option>
   <option value="7">Other&nbsp;Recoverable</option>
   <option value="8">Other&nbsp;Reinsurer</option>
   <option value="9">Pool</option>
   <option value="10">Primary&nbsp;Retention</option>
   <option value="11">Reinsurer</option>
   <option value="12">Ceding</option>
   <option value="13">Secondary&nbsp;Retention</option>
   <option value="14">Inuring&nbsp;Retention</option>
</select>](url)`

**Comment by pavelfeldman** [comment]
Try using

```java
page.locator('selector option').allTextContents()
```

**Comment by pavelfeldman** [comment]
Closing as per above.
