### ISSUE TITLE
Header model semantic mismatch

### ISSUE THREAD

**Issue by mindplay-dk** [microsoft/playwright#8587]
Your header model generally looks something like this:

https://github.com/microsoft/playwright/blob/9da26f9534adcbd855e37b1584a94ca673e7f4bf/types/types.d.ts#L13228-L13231

Strictly speaking, headers are not a key/value map - and in practice, this causes some problems, for example with `set-cookie`, which frequently occurs more than once.

Apparently, the way you address this, is by concatenating multiple header-values with a `\n` (line-break) character.

It doesn't look like this detail is described in [documentation](https://playwright.dev/docs/api/class-request#request-headers) - and by the time you uncover this, it makes it quite difficult and clumsy to work with the model.

For example, the widely-used [set-cookie-parser](https://www.npmjs.com/package/set-cookie-parser) package has some extremely weird behavior when you pass it a multi-value header like this - and the `splitCookiesString` function doesn't help here either, as it expects multi-value headers to be separated by commas rather than line-breaks.

It's not obvious how to add a header either - doing so correctly is pretty clumsy:

```js
function addHeader(headers, name, value) {
  if (name in headers) {
    headers[name] = header[name] + "\n" + value;
  } else {
    headers[name] = value;
  }
}
```

It's not clear to me if the line-breaks detail is the only detail either, or just the one I've discovered

Is there anything else I need to know?

Either way, I would suggest a deprecation of the existing methods and a replacement with some sort of abstraction/type to properly deal with headers?

That or a wrapper-type for the current model, to take care of the the splitting and recombining, adding/removing headers, etc. - which I will most likely write under any circumstances to avoid these issues.

At the very least, these details should be documented.

I am happy to help with whatever course of action you prefer. 🙂

**Comment by mxschmitt** [comment]
Linking #7404 which is similar

**Comment by mindplay-dk** [comment]
Looking at the code, and I am quite confused.

The headers get denormalized into two models - an array and a `Set`:

https://github.com/microsoft/playwright/blob/16b0a96e78ec3bbb0fbdb12ca1c14959ad42e7dc/src/server/network.ts#L326-L327

`headers()` appears to return the array version:

https://github.com/microsoft/playwright/blob/16b0a96e78ec3bbb0fbdb12ca1c14959ad42e7dc/src/server/network.ts#L398-L400

And the array version is *not* the lossy `[key: string]: string` model described in the manual:

https://github.com/microsoft/playwright/blob/16b0a96e78ec3bbb0fbdb12ca1c14959ad42e7dc/src/server/types.ts#L193

I also don't see the code anywhere that collapses repeated headers and joins them with line-breaks?

This code hasn't been touched in a year - how come this is so different from the the published version I got from npm?

If I could get the `{ name: string, value: string }[]` version of the headers, no problems, I could handle everything from there.

If the model is somehow lossy from the Chrome integration side or something, there's probably not much I can do from here...

(on a side note, the code that constructs the `Set` from the array is duplicated among several constructors and methods, and should be consolidated.)

**Comment by mindplay-dk** [comment]
Oh, I see... the release-branch is 200 commits behind master. 👀

![image](https://user-images.githubusercontent.com/103348/131520854-61d14557-7688-430b-8e37-b8672d9aec5f.png)

The release-branch has an entirely different header model:

https://github.com/microsoft/playwright/blob/cf1fd795a6efa00a1bbe0642e38bca2e1f65fe18/src/network.ts#L96

It also doesn't have the denormalization from the master branch, or the duplicate code.

What exactly is your process here? It looks like you're maintaining two different pieces of software. 😐

**Comment by pavelfeldman** [comment]
Yeah, we are well-aware of this problem. This goes back to the times when browsers did not allow us getting the raw header information. Certain network stacks (macOS, libsoup, libcurl) are harder to work with than Chromium's stack. We'll probably fix it at some point.

What is the exact problem you are resolving? Knowing the use case would help us prioritizing the fix.

**Comment by mindplay-dk** [comment]
@pavelfeldman I can see you're working on the master branch almost daily, so is that where you're planning the next major release? The release branch is (technically) for maintenance only, is that correct?

I'm just trying to understand the process and assess the status of this project, before committing myself to building a fairly large and complex project with it. 😄

> We'll probably fix it at some point.

I could probably help, but I'd need to know which branch is considered the "source of truth".

Are you releasing the master branch anywhere in public? I might want to try it out instead of the release branch.

> What is the exact problem you are resolving?

I needed to parse multiple `set-cookie` headers from the response - I found a way, by simply splitting the combined header values with `.split("\n")`, and that seems to work... But since this detail is unspecified, I'm afraid I'm relying on an implementation detail.

> This goes back to the times when browsers did not allow us getting the raw header information.

Yeah, what you're doing on the master branch seems less lossy and definitely more sensible - but also a bit problematic in terms of how it duplicates logic and denormalizes the header. If I'm going to commit myself to working with this in the long term, I'm mostly probing to see if/where I might be able to help, and this would be something I could easily jump in and fix.

But that only makes sense if there's an unstable/pre-release and I could actually use what I contribute... 🙂

**Comment by mxschmitt** [comment]
The master branch is for the next release and gets released daily under `npm install playwright@next`. The release-1.14 branch is for bugfix releases (patch releases) for 1.14.X when we need to backport changes.

Instead of modifying the current header functions we could add rawHeaders() to stay conform with semver.

**Comment by mindplay-dk** [comment]
> The master branch is for the next release (1.15.0)

Okay, that's great! I will give that a shot.

> Instead of modifying the current header functions we could add rawHeaders() to stay conform with semver.

Yeah, definitely - I'm not proposing a breaking change. The existing model works well for some use-cases, so. 🙂

Would you guys care to review a proposal PR, or do you prefer doing this work on your own?

**Comment by mindplay-dk** [comment]
Looks like this is landing with #8638
