### ISSUE TITLE
[BUG] page.evaluate is not using correct type for when passing in an array with mixed types

### ISSUE THREAD

**Issue by Tyriar** [microsoft/playwright#8590]
**Context:**
- Playwright Version: [what Playwright version do you use?] @playwright/test@1.13.1
- Operating System: [e.g. Windows, Linux or Mac] N/A
- Node.js version: [e.g. 12.22, 14.6] v14.16.1
- Browser: [e.g. All, Chromium, Firefox, WebKit] N/A

**Describe the bug**

I have this test code which fails to compile unexpectedly:

```javascript
const target = await ctx.page.evaluate(([luna, x, y]) => luna.test.getCellPosition(x, y), [ctx.luna, x, y]);
```

In order to compile it I need to cast the array as the type:

```javascript
const target = await ctx.page.evaluate(([luna, x, y]) => luna.test.getCellPosition(x, y), [ctx.luna, x, y] as [JSHandle<ILuna>, number, number]);
```

This is happening because the array is coming in as `[A | B]` instead of `[A, B, B]`:

![image](https://user-images.githubusercontent.com/2193314/131512755-6dc5cb9f-ae1d-4de6-b80e-9085738dbcb9.png)

Maybe infer or ... in the generics would help here? I haven't dealt with this particular TS problem.

cc @mxschmitt

**Comment by mxschmitt** [comment]
Minimum repro:

```ts
const playwright = require('playwright');

(async () => {
  const browser = await playwright.chromium.launch();
  const page = await browser.newPage();
  await page.evaluate(([a, b, c]) => a.length + b.length + c, ["foo", "bar", 42])
  await browser.close();
})();
```

**Comment by JoelEinbinder** [comment]
Can you provide your typescript version. The behavior of this has changed from version to version. Sometimes you need to cast your array to const: '[ctx.luna, x, y] as const'

**Comment by Tyriar** [comment]
I'm on 4.3. I'd hope some TS magic would be able to handle it so I don't need to write `as const` everywhere

**Comment by JoelEinbinder** [comment]
Minimal typescript repro:

```ts
function foo<T>(callback:(x:T)=>void, x: T) {
    callback(x);
}

foo(([a, b, c]) => {
  a.toExponential();
}, [1, 'a', true]);
```

I thought this was changing between typescript versions because the behavior `Promise.all` kept changing, but it looks like they solve that via 10 overloads each with a different number of template parameters. That's a lot of overloads to maintain in our api, so I'd rather avoid it if its not a pressing issue.

Alternatives today are to use `as const` or switch to curly braces:

```ts
const target = await ctx.page.evaluate(({luna, x, y}) => luna.test.getCellPosition(x, y), {luna: ctx.luna, x, y});
```

I like curly braces because they prevent accidental ordering mixups when parameters share the same type like x and y.

**Comment by Tyriar** [comment]
I just tried to come up with a solution and couldn't figure it out. Will go with `[] as const` for now as it's more concise and less fragile as the property names don't need to align.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
