### ISSUE TITLE
[Webkit ] HTTP Error 401 - Unauthorized: Access is denied`.

### ISSUE THREAD

**Issue by Paramesh82** [microsoft/playwright#8597]
Unable to login with UserID  and password with webkit browser , the same scenario is working fine for chrome and firefox.

App page navigation is performed (By checking the page URL, shown the default app page URL, which will be shown generally after app page will be loaded) but app page is not loaded due to the issue `HTTP Error 401 - Unauthorized: Access is denied`.

Attaching the trace viewer logs too.

[trace.zip](https://github.com/microsoft/playwright/files/7086696/trace.zip)

**Comment by yury-s** [comment]
What platform is this? Can you share your code and the log that plawright prints when running with `DEBUG=pw:protocol`? Do you know if the server uses NTLM authentication?

**Comment by Paramesh82** [comment]
it's a windows platform ( win10) and the server support NTLM authentication. 
Attached are the logs .. 
[integration-tests-logs.txt](https://github.com/microsoft/playwright/files/7092925/integration-tests-logs.txt)

**Comment by yury-s** [comment]
Is there an easy way for me to repeat your setup where this error is reproducible? I feel like ntlm authentication may be broken in WebKit Win port. Perhaps you could run this test on a Mac or Linux machine and see if WebKit still fails (the network stack is platform dependent in WebKit) that would help us better understand what's not working?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

We need a script that you use, auth type that you use, expectations and actual observations. Thanks!
