### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ajinkya201991** [microsoft/playwright#8612]
**Context:**
- Playwright Version: 1.14.0
- Operating System: Windows
- Node.js version : v12.21.0
- Browser: Chromium

**Code Snippet**
****'SHIFT + mouse RMB' action is not found to work together*****
                await page.waitForTimeout(5000);
		await page.mouse.move(500, 340);
		await page.waitForTimeout(2000);
		await page.keyboard.down('SHIFT ');
		await page.waitForTimeout(2000);
		await page.mouse.down({button:'right'});
		await page.waitForTimeout(2000);
		await page.mouse.move(500, 418);
		await page.keyboard.up('SHIFT ');
		await page.waitForTimeout(2000);
		await page.mouse.up({button:'right'});
		await page.waitForTimeout(2000);

**Describe the bug**

'CTRL + mouse RMB' action is found to work together

               await page.waitForTimeout(5000);
		await page.mouse.move(500, 340);
		await page.waitForTimeout(2000);
		await page.keyboard.down('Control');
		await page.waitForTimeout(2000);
		await page.mouse.down({button:'right'});
		await page.waitForTimeout(2000);
		await page.mouse.move(500, 418);
		await page.keyboard.up('Control');
		await page.waitForTimeout(2000);
		await page.mouse.up({button:'right'});
		await page.waitForTimeout(2000);

Some issue is seen for Shift key to operate with mouse RMB action

**Comment by aslushnikov** [comment]
@ajinkya201991 can you please come up with a reproducible code snippet that we can run locally to observe the issue? Otherwise this is not actionable; I'll close this for now, but feel free to re-file!
