### ISSUE TITLE
Is this npm package (playwright-firefox) used for testing firefox ESR and Non-ESR versions instead of nightly ?

### ISSUE THREAD

**Issue by ajinkya201991** [microsoft/playwright#8613]
If yes....How is the usage for this package (playwright-firefox)

Not provided here : https://www.npmjs.com/package/playwright-firefox

Can we run automation over firefox ESR and Non-ESR versions instead of nightly, using playwright.....please provide any assistance...

Thanks

**Comment by aslushnikov** [comment]
> Can we run automation over firefox ESR and Non-ESR versions instead of nightly,

@ajinkya201991 There's no nightly; Playwright v1.14 runs a build of firefox that matches Firefox Stable 91.0.

Playwright doesn't support Firefox ESR.
