### ISSUE TITLE
[BUG] newPage accepts a url, but lacks waitOptions

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright#862]
We now take a URL in newPage, but we don't provide any navigation waiting options. This is a bug, because it makes it impossible to properly use the page on that url.

**Comment by pavelfeldman** [comment]
@JoelEinbinder now that we have `browser.newPage` (again), do we still want url there? I originally added it to get back the source line taken by the context creation...

**Comment by JoelEinbinder** [comment]
I'm fine with removing it.

**Comment by pavelfeldman** [comment]
Ok, I'll do it

**Comment by pavelfeldman** [comment]
Fixed
