### ISSUE TITLE
[Question] Does playwright support ability of chaining elements (not selectors)

### ISSUE THREAD

**Issue by Yurii397** [microsoft/playwright#8623]
Hi folks, 
I'm using custom `data-test-id` selectors for getting elements in my TAF. And sometimes I need to works with some small pieces of an already existing element. 
For intance, I got counter element  -  `page.$('[data-test-id="counter"]')` 
At the same time, the counter has kind of plus and minus buttons (represented as `button` tags in DOM). 

Is there any ability in Playwright to chain elements like - `page.$('[data-test-id="counter"]').$('button')`

**Comment by uchagani** [comment]
what you have should work.  `$` returns an `ElementHandle` and `ElementHandle` also has a `$` function you can call. Keep in mind that when you use `$` you are not using playwright's autowaiting.  to recreate that you would need to do:

`page.waitForSelector('[data-test-id="counter"]').waitForSelector('button')`

you can also do it with locators:

`page.locator('[data-test-id="counter"]').locator('button')`

**Comment by yury-s** [comment]
Closing per the above answer.
