### ISSUE TITLE
[Feature] Add titlePath to testInfo

### ISSUE THREAD

**Issue by vmelikyan** [microsoft/playwright#8635]
`titlePath` on the Reporter api has useful information that is useful in tests. It would be great if we could add `titlePath` to `testInfo` fixture.

**Comment by vmelikyan** [comment]
What we really need is a way to get the parent `describe` name in a `test`.
Discussion can be found here [here](https://playwright.slack.com/archives/C01AG7QGW2F/p1630106248016800)

**Comment by pavelfeldman** [comment]
Could you share why testInfo.outputPath did not work for you?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
