### ISSUE TITLE
[BUG] Inconsistent `responseEnd` timing in chromium for network events

### ISSUE THREAD

**Issue by vigneshshanmugam** [microsoft/playwright#8636]
**Context:**
- Playwright Version: master
- Operating System: Mac
- Node.js version: 14.15
- Browser: Chromium

**Code Snippet**
```ts
it('should produce consistent RT', async ({ contextFactory, }) => {
  const context = await contextFactory();
  const page = await context.newPage();
  const map = new Map();
  context.on('requestfinished', req => {
    const timing  = req.timing();
    const dns = timing.domainLookupEnd - timing.domainLookupStart;
    const connect = timing.connectEnd - timing.connectStart;
    const ssl = timing.connectEnd - timing.secureConnectionStart;
    const wait = timing.responseStart - timing.requestStart;
    const receive = timing.responseEnd - timing.responseStart;
    map.set(req.url(), {
      dns,
      connect,
      ssl,
      wait,
      receive // would include the total time on chrome 
    });
  });
  await page.goto('https://vigneshh.in');
  for (const [key, value] of map.entries())
    console.log(key, value);

  await context.close();
});
```

**Describe the bug**

+ Resource timing data from `request.timing` API is exposing incorrect timing for `responseEnd` data in chromium browser. This results in `receive` part of the HAR denoting the overall duration of the request instead of the specific timing data. Works properly on FF. 

+ `responseEnd` timing actually denotes the complete request duration in chromium as opposed to only including the relative time from responseStart. https://github.com/microsoft/playwright/blob/9618a8477b33d5a6b69ec1a3abe43b193d1d8bc0/src/server/chromium/crNetworkManager.ts#L380

**Comment by yury-s** [comment]
Looks like the implementation is consistent between [Chromium](https://github.com/microsoft/playwright/blob/b1260602ac84305bd755de05b9ef9a3b7ba04813/src/server/chromium/crNetworkManager.ts#L380) and [WebKit](https://github.com/microsoft/playwright/blob/b1260602ac84305bd755de05b9ef9a3b7ba04813/src/server/webkit/wkPage.ts#L1055) where responseEndTiming is reported as difference between request start timestamp and loading finished (i.e. total request time as you mentioned) whereas in [Firefox](https://github.com/microsoft/playwright/blob/b1260602ac84305bd755de05b9ef9a3b7ba04813/src/server/firefox/ffNetworkManager.ts#L129) it is reported as time between response start and response end. So, if I understand correctly, we need to fix Firefox as all fields in [timing](https://playwright.dev/docs/api/class-request#request-timing) are relative to `startTime`, in that case [har](https://github.com/microsoft/playwright/blob/b1260602ac84305bd755de05b9ef9a3b7ba04813/src/server/supplements/har/harTracer.ts#L276) will automatically get right `receive` time in Firefox.
