### ISSUE TITLE
[BUG] Terminating the remote browser connection should clear all contexts

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#864]
Consider the following scenario:

```js
const browserServer = await chromium.launchServer();
const wsEndpoint = browserServer.wsEndpoint();
const browser = await chromium.connect({ wsEndpoint });
await browser.newContext();
await browser.newContext();
await browser.newContext();
// <-- connection terminates here due to network error
await browser.close();
```

In this case, browser client is not given a chance to clean up all the contexts it has created. We should make sure browsers are doing that upon physical web socket connection termination.

**Comment by aslushnikov** [comment]
will be pretty hard to test on the playwright level :'(

**Comment by dgozman** [comment]
Note that if we keep an intermediate proxy (like a multiplexer), this could be easily done on front-end side.

**Comment by pavelfeldman** [comment]
Fixed
