### ISSUE TITLE
[BUG] Trace viewer cannot show iframes

### ISSUE THREAD

**Issue by liyuanqiu** [microsoft/playwright#8644]
**Context:**
- Playwright Version: 1.14.1
- Operating System: Windows 10
- Node.js version: v12.19.0
- Browser: Chromium
- Extra:

## System:
 - OS: Windows 10 10.0.19043
 - Memory: 12.12 GB / 31.34 GB
## Binaries:
 - Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
 - npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
## Languages:
 - Bash: 4.4.23 - C:\Program Files\Git\usr\bin\bash.EXE
## npmPackages:
 - playwright: ^1.14.1 => 1.14.1

**Code Snippet**

```bash
npx playwright show-trace <path_to_trace.zip>
```

**Describe the bug**

![image](https://user-images.githubusercontent.com/24999464/131777991-0a4b3bf4-8b1f-4a65-9b70-78f71eccad0a.png)

Our web page is heavily based on iframes, but in Trace viewer, the iframe part cannot display correctly, while the screenshots are ok.

**Comment by dgozman** [comment]
@liyuanqiu Could you please share the trace itself? Or a script that was used to generate it? Otherwise it's hard to pinpoint the problem.

**Comment by liyuanqiu** [comment]
@dgozman Not sure the trace.zip file will contain credentials or not, so share you the file in Teams chat, thanks!

**Comment by dgozman** [comment]
Looking at the trace, the issue is with Content-Security-Policy meta tag that prevents snapshot render script from executing and updating iframe urls from stripped down versions to snapshots.
