### ISSUE TITLE
ElementHandle.inputValue is not a function

### ISSUE THREAD

**Issue by nate-buck** [microsoft/playwright#8648]
**Context:**
- Playwright Version: 1.14.1
- Operating System: Windows
- Node.js version: 14.7.6
- Browser: All
- Extra: [any specific details about your environment]

**Code Snippet**

`const elementHandle = await page.waitForSelector("id=elementId"); // resolves with the expected ElementHandle<HTMLInputElement> [type='text']`
`const value = await elementHandle.inputValue(); // throws error: 'elementHandle.inputValue is not a function'`

**Describe the bug**

According to documentation [here](https://playwright.dev/docs/api/class-elementhandle#element-handle-input-value), the ElementHandle should have a member function called `inputValue`, but it doesn't.

**Comment by mxschmitt** [comment]
Do you have playwright-core installed? Which test-runner are you using?

My assumption is that internally you don't have the latest Playwright TypeScript types. (npm i playwright-core@latest might fix it if you are using jest-playwright)

**Comment by nate-buck** [comment]
Hi @mxschmitt. Thanks for your quick response. How do I see which test-runner we're using? I executed the command you suggested but it seems to have had no effect. Is there something I need to do to update the internal TypeScript types?

**Comment by mxschmitt** [comment]
How do you execute your tests? Are you using Jest or @playwright/test? Do you have a reproducible somewhere?

**Comment by nate-buck** [comment]
Using @playwright/test. At the moment, no reproducible as it's still a WIP. I have come up with a work-around using `ElementHandle.evalute`, but it would be nice to solve the issue.

**Comment by mxschmitt** [comment]
`npm i -D @playwright/test` and `npm ci` might fix it then. Seems like your node_modules is not up to date.

**Comment by nate-buck** [comment]
That's solved the issue. Thanks @mxschmitt.
