### ISSUE TITLE
[Question] video quality

### ISSUE THREAD

**Issue by gigitalz** [microsoft/playwright#8650]
is there a way to control video quality?
It's be nice to have such parameters and control ffmpeg to some extent at least.

**Comment by yury-s** [comment]
The only way to control the video quality today is to configure video frame dimensions via [`recordVideo.size`](https://playwright.dev/docs/api/class-browser#browser-new-context) option. Does it not help?

**Comment by gigitalz** [comment]
Actually not, the default quality is low and some recordings require low frame rate, one fps. The best would be to be able to customize the ffmpeg parameters with a setArgs or overrideArgs kinda function set.

**Comment by anishkny** [comment]
@yury-s how to configure `recordVideo.size` from within `playwright.config.js` test config?

I tried configuring within `config`, `config.use`, `config.use.launchOptions`, `projects.use` etc but couldn't figure it out 😞 

Thanks!
