### ISSUE TITLE
[Question] Why I am not able to play DRM protected content in firefox ?

### ISSUE THREAD

**Issue by star-kashyap** [microsoft/playwright#8652]
Any workaround to play & validate DRM protected contents ?
<img width="1282" alt="Screenshot 2021-09-02 at 7 15 39 PM" src="https://user-images.githubusercontent.com/58773425/131855174-cf4013de-c404-4167-82f9-d75428c35d49.png">

**Comment by shirshak55** [comment]
whats the point anyway. You want to screen record it? That might be bad idea because it will have fps/quality issue. And as its drm its already encrypted in super secure way.

**Comment by yury-s** [comment]
DRM protected videos only work in official browser builds, you would need to run Playwright with stock [Google Chrome or MS Edge](https://playwright.dev/docs/browsers#google-chrome--microsoft-edge) to make them playable.

**Comment by shirshak55** [comment]
@yury-s unfortunately ppl are forced to use firefox because chrome/edge can be detected so easily. Its probably hard for them.
