### ISSUE TITLE
[Question] Check if headless from BrowserContext.

### ISSUE THREAD

**Issue by QueshAnmak** [microsoft/playwright#8654]
### Description
Is there any way of checking whether the browser is running in headless mode, from the BrowserContext?

**Comment by yury-s** [comment]
There is no such API. In chrome you can get user agent string (`await page.evaluate(() => navigator.userAgent)`) and see if it contains `HeadlessChrome`

**Comment by mxschmitt** [comment]
How do you launch your browser and context? Are you using the Library or Playwright Test?
