### ISSUE TITLE
[Question] How to send text to dialogs

### ISSUE THREAD

**Issue by kapros** [microsoft/playwright#8664]
Hello, I was working on an example repo that would load an extension and do some stuff inside it. One of the things involves a dialog where you can enter text to rename a test case or the file to be downloaded. I see that the API doesn't have anything that would send text to a dialog. Is there any alternative / workaround for this?

**Comment by yury-s** [comment]
You can listen to the dialog and fill it with text using [`dialog.accept`](https://playwright.dev/docs/api/class-dialog#dialog-accept). If the dialog you are talking about is a regular page you need to listen to 'popup' event, see [this doc](https://playwright.dev/docs/multi-pages#handling-popups).
