### ISSUE TITLE
[Feature] allAttributes on a Locator

### ISSUE THREAD

**Issue by naknode** [microsoft/playwright#8666]
I'd like to get a `allAttributes` with the specified data attribute looking for in a page. It would be just like `Locator.allTextContents()`.

Do you take PRs? Perhaps I can try my hand if this deemed useful?

**Comment by yury-s** [comment]
What's the use case for such method?

**Comment by naknode** [comment]
> What's the use case for such method?

Let's say you have a Vue/React/Svelte/what-have-you component that gets repeated so you put in `data-input="Input of Label"`, so you have a dozen or so of these on the page. The use-case being that with this, you'd be able to scoop up all of the elements (and their value) with the same data attribute.

**Comment by yury-s** [comment]
> Let's say you have a Vue/React/Svelte/what-have-you component that gets repeated so you put in `data-input="Input of Label"`, so you have a dozen or so of these on the page. The use-case being that with this, you'd be able to scoop up all of the elements (and their value) with the same data attribute.

If I understand correctly, you want the result to be a list of elements with matching attribute value (not attributes themselves as there is not much on can do with the attribute) which could already be implemented like this:
```js
 parent.locator(`[data-input="Input of Label"]`).elementHandles()
```
One important difference compared to `allTextContents` is that you get back a list of handles to live nodes as opposed to the text content (which won't change even if the nodes are updated) and for that it may be better to use handles api.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
