### ISSUE TITLE
[Question] Does Playwright Docker Image contain Playwright CLI?

### ISSUE THREAD

**Issue by valoricDe** [microsoft/playwright#8678]
Hello there,

I'm trying to use the following docker command on my Mac OSX

```docker run --rm -v "${PWD}/playwrightfolder:/tmp" --ipc=host mcr.microsoft.com/playwright:focal /bin/sh -c "playwright test"```

But it says it does not find the playwright cli. So I'm wondering if it is not already installed as a global npm module?

Furthermore running 
```docker run --rm -v "${PWD}/playwrightfolder:/tmp" --ipc=host mcr.microsoft.com/playwright:focal /bin/sh -c "npx playwright test"```
results in `Error: Cannot find module '/root/.npm/_npx/7/lib/node_modules/playwright/install.js'`

Do you have any advise or should I create a bug out of this issues?

**Comment by valoricDe** [comment]
I read somewhere that the second problem is related to the root user so I added `--user pwuser` as suggested by the docs. But then `npx playwright test` fails with 
```
Please install @playwright/test package to use Playwright Test.
  npm install -D @playwright/test
```
Is this intended. Am I missing something?

**Comment by yury-s** [comment]
> But it says it does not find the playwright cli. So I'm wondering if it is not already installed as a global npm module?

No, it is not. You need to install it yourself. You can look at our [Dockerfile](https://github.com/microsoft/playwright/blob/master/utils/docker/Dockerfile.focal) to get an idea what it preinstalls, it's mostly about browsers and their dependencies, @playwright/test and playwright modules have to be installed separately.

> I read somewhere that the second problem is related to the root user so I added `--user pwuser` as suggested by the docs. But then `npx playwright test` fails with

Correct, that will fix the problem. Once again, you'll need to install `@playwright/test` separately if you want to use it.

**Comment by valoricDe** [comment]
To share my findings with others. It was unclear to me that I don't need npx playwright test as  playwright codegen's result can be run just with node. That's the script I use now:

```
#!/bin/bash

docker run --rm -v "${PWD}/playwrightscript.js:/home/pwuser/playwrightscript.js" --ipc=host --user pwuser mcr.microsoft.com/playwright:focal \
/bin/sh -c "cd ~ && npm i playwright && node ~/playwrightscript.js"
```
