### ISSUE TITLE
[Feature] It would be nice if test.step showed up in trace view actions

### ISSUE THREAD

**Issue by mwhebert** [microsoft/playwright#8682]
When I use test.step I was expecting to see that step in the trace viewer actions list and not just in the source panel.  This would be nice to see and be able to jump to a particular test location or at least have more context while diagnosing the test run.  Especially if the contained step were indented below the step text.

**Comment by jespertheend** [comment]
What is the step title currently being used for?
I was expecting it to show when an error occurs but this doesn't seem to be the case.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by aslushnikov** [comment]
(re-opening since a new request was filed)

**Comment by segevfiner** [comment]
This would definitely be helpful, will make it much easier to associate a part of the trace to the relevant part of a test. And yeah, Playwright/Node side console.log output would also be helpful.

**Comment by mxschmitt** [comment]
This is now implemented since a few releases, closing.
