### ISSUE TITLE
[Question] Tuning video performance

### ISSUE THREAD

**Issue by jacobmesu** [microsoft/playwright#8683]
We build our own testrunner with Playwright. We use the external library playwright-video for recording and rendering our videos. (https://github.com/qawolf/playwright-video). We'd like to switch to the internal recording option in Playwright itself. So I did some testing, but the performance of the internal recording is quite different compared to playwright-video. Playwright-video can somewhat keep up with rendering and while the internal recording takes 5 to 10 minutes to render the videos after the context is closed. Is it possible to tune the video performance somehow? I would love to switch since Playwright-video is archived, but the internal recordings performance is unacceptable. When a lot of tests are failing, it will double the running time. Any tips or hints are greatly appreciated.

**Comment by yury-s** [comment]
Which playwright version are you on? We had a problem where video encoding would continue for up to a minute in Chromium after test finished but it was fixed.  5-10 minutes is huge (we'd expect it to take a few seconds after test finishes in worst case) , can you share a repro? Also can you confirm that it's Chromium-only?

Answering your question: we don't expose any options for tuning video performance, only configuration option we provide is video frame dimensions. All performance issues we saw were related to ffmpeg. Even though we use ffmpeg internally for Chromium it may change in the future and exposing its options in the API would make such transition harder. If the video encoding is slow we'd rather fix it than add more config params.

**Comment by pavelfeldman** [comment]
playwright-video and playwright use the same code to produce videos in case of Chromium. If you are seeing difference in performance, it most likely means that you are requesting different video sizes. Our default is inscribing video into 800x600 unless you are overriding it.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by MuTsunTsai** [comment]
Hi @jacobmesu — old thread, but the symptom you described ("internal recording takes 5 to 10 minutes to render after context closes") is now solvable without forking Playwright. [`playwright-recorder-plus`](https://github.com/MuTsunTsai/playwright-recorder-plus) uses a fixed two-pass pipeline:

- First pass is H.264 ultrafast, so capture stays ahead of realtime and `recorder.stop()` returns as soon as that flushes.
- Second pass (transcode + audio mux) runs in the background; you can await `recorder.finalized` only when you actually need the final file.

So for a CI run, `stop()` no longer blocks the test on encoding. Sharing in case you (or anyone landing here from search) is still hitting it. Not a Playwright maintainer.
