### ISSUE TITLE
[BUG] Openning a new page by clicking on a link with reset the context viewport to default values

### ISSUE THREAD

**Issue by florin-talarian** [microsoft/playwright#8684]
**Context:**
- Playwright Version: 1.14.0
- Operating System: Linux
- Node.js version: 14.17.5
- Browser: Chromium

**Code Snippet**
this.context = await this.browser.newContext({ viewport: { width: 1920, height: 1080 } });
this.page = await this.context.newPage();
........
return await Promise.all([this.page.waitForEvent("popup"), this.yammFrame.click("text=" + this.allertText)]);

**Describe the bug**

When I'm opening a new page by clicking on a link it will minimize the browser to default values (1280x720) including the parrent page that was fullscreen.

**Comment by yury-s** [comment]
Can you share complete repro with the page where it happens?

**Comment by florin-talarian** [comment]
Hi @yury-s and sry for the delay.
While writing the script to reproduce this I was able to further localize the issue. So this one reproduces the issue:

const { test, expect } = require("@playwright/test");
const sleep = require("await-sleep");
const data = require("../data/variables");

test("basic test", async ({ browser }) => {
  let context = await browser.newContext({
    storageState: data.MAIN_EMAIL + "-state.json",
    viewport: { width: 1920, height: 1080 },
  });
  let page = await context.newPage();
  await page.goto("https://www.npmjs.com/package/playwright");
  const [page1] = await Promise.all([page.waitForEvent("popup"), page.click("text=github.com/Microsoft/playwright")]);
  await sleep(10000);
  await browser.close();
});

But if I delete the storageState arg it will not reproduce, so I believe it happens because of storageState.
BR

**Comment by pavelfeldman** [comment]
Is there a way you get us a script we could run to reproduce? It looks like a Playwright bug, but we need a repro.

**Comment by florin-talarian** [comment]
Hi @pavelfeldman 
Yes, the script above reproduces the issue:

`const { test, expect } = require("@playwright/test");
const sleep = require("await-sleep");
const data = require("../data/variables");

test("basic test", async ({ browser }) => {
let context = await browser.newContext({
storageState: data.MAIN_EMAIL + "-state.json",
viewport: { width: 1920, height: 1080 },
});
let page = await context.newPage();
await page.goto("https://www.npmjs.com/package/playwright");
const [page1] = await Promise.all([page.waitForEvent("popup"), page.click("text=github.com/Microsoft/playwright")]);
await sleep(10000);
await browser.close();
});`

**Comment by dgozman** [comment]
I tried to reproduce this locally, but it works as expected for me. The browser window is opened large (not fullscreen like when you click a "fullscreen" button in a video player, just large), the second page is a tab, browser window stays large. I guess we'll need a script with more details, like contents your `...-state.json` and `../data/variables` files.

```js
const { chromium } = require('@playwright/test');

(async () => {
  const browser = await chromium.launch({ headless: false });
  let context = await browser.newContext({
    viewport: { width: 1920, height: 1080 },
  });
  let page = await context.newPage();
  await page.goto("https://www.npmjs.com/package/playwright");
  const [page1] = await Promise.all([page.waitForEvent("popup"), page.click("text=github.com/Microsoft/playwright")]);
  await page.waitForTimeout(10000);
  await context.close();
  await browser.close();
})();

```

**Comment by florin-talarian** [comment]
Here's the storage state json and the code to reproduce
```
const { test, chromium } = require("@playwright/test");

test("Test issue 8684", async ({}) => {
  const browser = await chromium.launch({ headless: false });
  let context = await browser.newContext({
    storageState: "florin.barbu.js@gmail.com-state.json",
    viewport: { width: 1920, height: 1080 },
  });
  let page = await context.newPage();
  await page.goto("https://www.npmjs.com/package/playwright");
  const [page1] = await Promise.all([page.waitForEvent("popup"), page.click("text=github.com/Microsoft/playwright")]);
  await page.waitForTimeout(10000);
  await context.close();
  await browser.close();
});
```
[florin.barbu.js@gmail.com-state.json.txt](https://github.com/microsoft/playwright/files/7169629/florin.barbu.js%40gmail.com-state.json.txt)

**Comment by mxschmitt** [comment]
Thanks for the report! It does look like there is a real bug here, but it is very hard to understand what's going on. We often spend days on these kinds of bugs that involve digging into large codebases. Feel free to open a new issue with a smaller repro script.
