### ISSUE TITLE
[Question] How can I scroll to bottom inside a modal window ?

### ISSUE THREAD

**Issue by francislagares** [microsoft/playwright#8693]
The thing is that I need to test a modal window that will enable a button
only when the user scrolls to the bottom, but I don't find the way how I
could do it. 
Any help will be appreciated. Thanks !

**Comment by yury-s** [comment]
You can get access to the modal window by listening ['popup'](https://playwright.dev/docs/multi-pages#handling-popups) event, then you can use either [scrollIntoViewIfNeeded](https://playwright.dev/docs/api/class-locator#locator-scroll-into-view-if-needed) or evaluate [`window.scrollBy()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollBy)
