### ISSUE TITLE
Headless mode does not identify a new opened tab url

### ISSUE THREAD

**Issue by alfflores** [microsoft/playwright#8707]
**Context:**
- Playwright Version: "playwright": "1.14.1"
- Operating System: Windows
- Node.js version: 14.16.0
- Browser: Chromium
- Extra: "@cucumber/cucumber": "7.3.1",  "expect": "27.1.0"
- Language: "typescript": "4.4.2"
````
const browserOptions: LaunchOptions = {
  headless: true,
  slowMo: 1000
};

**FEATURE**
    Then I click the element "linkUserGuide"
    Then I switch to the last tab
    Then I validate the browser url should match "https:\/\/(\S+)?ticket.com\/new-form\/assets\/docs\/user_guide(.*).pdf"


**STEP**
Then ('I validate the browser url should match {string}', async function (urlRegexp: string) {
  await playwright.page?.waitForLoadState();
  const brUrl = playwright.page?.url();
  expect(brUrl).toEqual(expect.stringMatching(urlRegexp));
});
````

**Describe the bug**

   × Then I validate the browser url should match "https:\/\/(\S+)?ticket.com\/new-form\/assets\/docs\/user_guide(.*).pdf" # src\libraries\steps\common-fe.steps.ts:30
       Error: expect(received).toEqual(expected) // deep equality

       Expected: StringMatching /https:\/\/(\S+)?ticket.com\/new-form\/assets\/docs\/user_guide(.*).pdf/
       Received: ":"
           at CustomWorld.<anonymous> (C:\Users\Desktop\REPOS\Testing\src\libraries\steps\common-fe.steps.ts:32:17)

One step performs a click in an element and it opens a new tab, I need to validate the Url name matches an expected value.
When the option headless=false  the url matches.
When the option headless=true the url is not loaded.

**Comment by pavelfeldman** [comment]
Please file this against cucumber, there seems to be nothing about Playwright in your report. If you think this is a Playwright problem, please provide a short script for us to reproduce it in a new bug!
