### ISSUE TITLE
[Question] How to know which browser failed a test?

### ISSUE THREAD

**Issue by shadow-light** [microsoft/playwright#8708]
I have a single test that runs in all three browsers, and only one of them fails. How am I supposed to know which browser failed? (aside from trial and error) It doesn't seem to mention it in the test output, and none of the [reporter types](https://playwright.dev/docs/next/test-reporters) seems to mention it either.

Is there a way, or should this be a feature request? thanks

**Comment by shadow-light** [comment]
Sample output:

```
··F

  1) spec.ts:5:1 › Visiting displayer without a hash ===============================================

    Error: expect(received).toBeTruthy()

    Received: false

      5 | test('Visiting displayer without a hash', async ({page}) => {
      6 |     await page.goto('')
    > 7 |     expect(await page.isVisible('text=Click original link to view message')).toBeTruthy()
        |                                                                              ^
      8 | })
      9 |

        at /home/runner/work/app/app/displayer/tests/spec.ts:7:78
        at WorkerRunner._runTestWithBeforeHooks (/home/runner/work/app/app/node_modules/@playwright/test/lib/test/workerRunner.js:426:7)


  1 failed
    spec.ts:5:1 › Visiting displayer without a hash ================================================
  2 passed (8s)
```

**Comment by pavelfeldman** [comment]
How do you run the tests? You need a basic config and it'll start showing the project names.

**Comment by shadow-light** [comment]
```
projects: [
        {use: {browserName: 'chromium'}},
        {use: {browserName: 'firefox'}},
        {use: {browserName: 'webkit'}},
    ],
```

I didn't have the `name` property set as it was optional. That fixed it, thanks @pavelfeldman.

`  1) [wekbit] › spec.ts:5:1 › Visiting displayer without a hash ====================================`

Problem solved, but perhaps it could default to the name of the browser if no name is set? Just a suggestion to help new users.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
