### ISSUE TITLE
Why does the compilation fail during installation

### ISSUE THREAD

**Issue by 368573607** [microsoft/playwright#8709]
**Context:**
- Playwright Version: latest
- Operating System: big sur
- Node.js version: 16.7.0
- Browser: none
- Extra: none

![image](https://user-images.githubusercontent.com/60562136/132089717-4414f2ae-ad9d-462a-9180-8e43743b093e.png)

As shown, I'm tried to install playwright. But this throws an error. Why?

**Comment by pavelfeldman** [comment]
We should suggest removing the ms-playwright folder from under ~/Library/Caches when this happens instead of failing.

**Comment by aslushnikov** [comment]
@368573607 a few questions:
- did you launch installation a few times and aborted it?
- can you try running
    ```sh
    $ curl -o chromium.zip https://playwright.azureedge.net/builds/chromium/901522/chromium-linux.zip
    ```
