### ISSUE TITLE
[Question] Packaging of a playwright script.

### ISSUE THREAD

**Issue by QueshAnmak** [microsoft/playwright#8711]
### Description:
I want to package my playwright script as an executable file (.exe). The executable should be self contained i.e include node and all the required node_modules. Is there any way to do this?

**Comment by mxschmitt** [comment]
This is not supported by Playwright out of the box, but should be doable in the user-land via installing the browsers inside node_modules: https://playwright.dev/dotnet/docs/browsers#managing-browser-binaries-1 and then deploying this folder.
