### ISSUE TITLE
Playwright site cannot be reached [BUG]

### ISSUE THREAD

**Issue by jrpool** [microsoft/playwright#8712]
**Context:**
- Requesting https://playwright.dev in a browser.

**Describe the bug**

When https://playwright.dev is requested in Chrome, Safari, Vivaldi, or Opera, the response is:

This site can’t be reached
playwright.dev’s server IP address could not be found.
Try:
Checking the connection
Checking the proxy, firewall, and DNS configuration
ERR_NAME_NOT_RESOLVED

Add any other details about the problem here.

This bug does not exist with Firefox.

OS is OS X 10.15.7.
Chrome is 92.

**Comment by mxschmitt** [comment]
This is a DNS problem on your site. Try to set e.g.
- https://developers.google.com/speed/public-dns
- https://1.1.1.1/dns/

**Comment by jrpool** [comment]
Thank you, @mxschmitt, but what site do you mean by “your site”?

**Comment by mxschmitt** [comment]
*side

I mean with that your computer configuration / network setup.

**Comment by jrpool** [comment]
That does not help. I get the same result. From a terminal I get 3 IPV4 addresses with either host or dig. But from all browsers except Firefox I get a DNS failure. If I try to directly access one of the IP addresses with a browser. such as https://185.199.109.153, I get:

404
There isn't a GitHub Pages site here.

**Comment by pavelfeldman** [comment]
Looks like you local problem. Site is reported as live:
https://www.isitdownrightnow.com/playwright.dev.html
