### ISSUE TITLE
[BUG] - Session is lost after logged in while app behaves correctly when we test manually

### ISSUE THREAD

**Issue by hienhoang88** [microsoft/playwright#8713]
**Context:**
- Playwright Version: 1.14.1
- Operating System: Mac OS Big Sur 11.5.2
- Node.js version: 14.13.1
- Browser: Chromium
- Extra: Project is built on top of Playwright with Jest and Allure as reporting tools. For the part of API tests, I use supertest.

I already attached the project zip file here: https://drive.google.com/file/d/1P70lNnLh4y5VgOLMznnIRSlaBrJsj-Sq/view?usp=sharing & command line to run the test:  npm run test tests/gate-nomination/PaidGate-WithLink-Metamask.test.js

**Describe the bug**

After logged in with Metamask, suddenly the session is lost and it fails to load the user data. But I can login manually to the application without error.

**Comment by pavelfeldman** [comment]
We need a short repro scenario in a form of a snippet to be able to look at it / act on it. Is there anything you can share?

**Comment by hienhoang88** [comment]
Hi there,

The scenario is quite simple:
- User have the url of the race, may be share by friend, etc...
- User goes to the race URL ,for example: https://goerli-test.zed.run/race/vkpsc96M
- User login with Metamask
- After logged in, when user click on a gate, user is able to select available horses to assign to the gate in order to form a race

You can always find the events here: https://goerli-test.zed.run/racing/events
Information to login with metamask: 
```
SEED_PHRASE:
        "promote involve unaware today camera major net tail area rule manual humor",
    PASSWORD: "nidalee1",
    CONFIRM_PASSWORD: "nidalee1"
```

**Comment by pavelfeldman** [comment]
We need something we can reproduce in a form of a 10 line script to be able to act on it. Reproducing your particular steps is very time-consuming. It also doesn't look like a testing scenario. Please file an issue with a short repro!
