### ISSUE TITLE
[BUG] Code is not running asyncronoulsy 

### ISSUE THREAD

**Issue by Amrkamel1** [microsoft/playwright#8716]
**Context:**
- Playwright Version: 1.14.1
- Operating System: linux
- Node.js version: 14.6
- Browser: [e.g. All, Chromium, Firefox, WebKit]

         TypeError: Cannot read property 'query' of undefined

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript

    test.beforeAll(async ()=>{
        await DB.ConnectToDataBase()
        
        const insertUser = await DB.submitDBQuery(`INSERT  INTO ....etc`)
        user_id = insertUser.insertId
        
        await DB.submitDBQuery(`INSERT INTO ....;`)
            console.log(user_id)
    })
```

```
let pool;

class DB {
    
    async ConnectToDataBase() {
        new Promise((_resolve, reject) => {
            this.sshClient.on('ready', async () => {
                this.sshClient.forwardOut(
                    this.forwardConfig.srcHost,
                    this.forwardConfig.srcPort,
                    this.forwardConfig.dstHost,
                    this.forwardConfig.dstPort,
                    async (err, stream) => {
                        if (err) reject(err);
                        // create a new DB server object including stream
                        const updatedDbServer = {
                            ...this.dbServer,
                            stream
                        }; // connect to mysql
                        pool = mysql.createPool(updatedDbServer);
                    });
            }).connect(this.tunnelConfig);
        });
    }

   async submitDBQuery(query) {
        const outPut = await pool.query(query);
        const results = JSON.parse(JSON.stringify(outPut));
        return results[0];
    }
```

**Describe the bug**

when using the beforeAll hook, the method is not working asynchronously , as I got query not defined which means that the previous method wasn't executed however I'm using wait and async.

when I separate them, add connectToDataBase in beforeAll method and  submitQuery in test block it works fine

**Comment by pavelfeldman** [comment]
You just create a promise in ConnectToDataBase and return immediately. You should return that new Promise. I also don't see you calling _resolve after pool is created, so you connect will just hang.
