### ISSUE TITLE
[BUG] Cannot install PlayWright

### ISSUE THREAD

**Issue by KaneZhangRyman** [microsoft/playwright#8719]
**Context:**
- Playwright Version: 1.14.1
- Operating System: Windows
- Node.js version: 14.17.5

Got those warning after run 'npm i -D playwright'

npm WARN saveError ENOENT: no such file or directory, open 'C:\PlayWright\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\PlayWright\package.json'
npm WARN PlayWright No description
npm WARN PlayWright No repository field.
npm WARN PlayWright No README data
npm WARN PlayWright No license field.

**Comment by KaneZhangRyman** [comment]
npm init -y can generate 'package.json' and resolve some warnings. But still haveing

npm WARN PlayWright@1.0.0 No description
npm WARN PlayWright@1.0.0 No repository field.

Also can't find any tests inside tests folder

**Comment by mxschmitt** [comment]
This is expected that no test files are there, to get started with Playwright you need to:

1. Have Node.js installed (you did that)
2. Create some directory and execute `npm init -y` there
3. Install Playwright Test `npm i --dev @playwright/test`
4. Create a test file, e.g. `foo.spec.ts`
5. Run the tests: `npx playwright test`

See here: https://playwright.dev/docs/intro#first-test

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
