### ISSUE TITLE
[Feature] Expect(locator).toHaveCountGreaterThen

### ISSUE THREAD

**Issue by cardinalX** [microsoft/playwright#8725]
I want to check that number of locators is Greater then given value or Less then given value.
There is method to check Equal [.tohaveCount](https://playwright.dev/docs/test-assertions#expectlocatortohavecountcount.
I can't always check that number of paragraphs on the page are equal, because the content may change over time and updating these values too often will be quite problematic.

**Comment by pavelfeldman** [comment]
You can do `expect(await locator.count()).toBeGreatedThen()` as a workaround for now. It won't be waiting until the number is greater than, it will just assert it immediately, but it looks like it might work for you.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by PawelWesolowski** [comment]
my current workaround for async greater than 5 is:
`await expect(page.locator("selector >> nth=5").toBeVisible()`

**Comment by brianmazzocchi** [comment]
> >> nth=5").toBeVisible()

Thank Pawel, this did the trick for me...

**Comment by robertlagrant** [comment]
@pavelfeldman my use case would be this: I want to click on the first item in a list. The list is populated from test data. I'd like to be able to say something like:

`expect(page.locate("li").count().isGreaterThan(0));`

Or even, more generally:

`expect(page.locate("li").count(), (p) => p > 0);`

**Comment by marco-elder** [comment]
I had a similar problem but in my case I'm forced to use `getByText`. I adapted the workaround @PawelWesolowski suggested like this: `expect(page.getByText("Download").nth(1)).toBeVisible()`.

**Comment by BrandonDH** [comment]
> 

Hey there can you elaborate on your syntax here? are you shifting bits? Thanks

**Comment by PawelWesolowski** [comment]
> @PawelWesolowski
> 
> > my current workaround for async greater than 5 is:
> > await expect(page.locator("selector >> nth=5").toBeVisible()
> 
> Hey there can you elaborate on your syntax here? are you shifting bits? Thanks

Sure. `page.locator("selector >> nth=5")` is the same as `page.locator("selector").nth(5)` - the `>>` is just Playwright's way of chaining multiple selectors using one string. `await expect(some_locator).toBeVisible()` will be waiting for some_locator to be visible. In our case we wait for the sixth (0-based indexing) element that matches the selector - when the sixth is visible, there is more then 5

**Comment by jwalkerinterpres** [comment]
This would be nice in filtering.  Right now if I select two `UL`s (eg. because they are indistinguishable), and I want to (for instance) "filter out the one that has at least two `LI`s" ... there's no (easy/intuitive) way to express that in Playwright. 

But, if there was a filter version of this feature, there would be ...

      page.locator('ul').filter({hasCountGreaterThanOrEqualTo: ['li', 2]})

**Comment by lazarljubenovic** [comment]
> You can do `expect(await locator.count()).toBeGreatedThen()` as a workaround for now. **It won't be waiting until the number is greater than, it will just assert it immediately**, but it looks like it might work for you.

I mean if you ignore this you don't need half the `Locator` 😄

**Comment by AndiBMGitHub** [comment]
+1 I would like this to be implemented

**Comment by costa-collibra** [comment]
I did my own implementation like this

```typescript
async toHaveCountGreaterThan(locator: Locator, expectedCount: number) {
    const assertionName = 'toHaveCountGreaterThan';

    try {
      await baseExpect(locator.nth(expectedCount)).toBeVisible();

      const actualCount = await locator.count();

      return {
        message: () => `Expected more than ${expectedCount} elements, and found ${actualCount}.`,
        pass: true,
        name: assertionName,
      };
    } catch {
      const actualCount = await locator.count();
      return {
        message: () => `Expected more than ${expectedCount} elements, but only found ${actualCount}.`,
        pass: false,
        name: assertionName,
      };
    }
  },
```

**Comment by Anutrix** [comment]
Why isn't this implemented yet?

**Comment by rinnnn** [comment]
It actually is implemented like below, see the feature mentioned above
```
await expect.poll(() => page.locator('something').count()).toBeGreaterThan(0);
```

**Comment by deerwithanopinion** [comment]
While the poll solution suggested by @rinnnn works, it pollutes the actions tab with all the failed attempts' error logs until it passes. The proposed feature and @PawelWesolowski workaround is cleaner.

**Comment by ronanshel** [comment]
+1 to this request.

I think the solution for checking whether the `nth` element is visible (proposed by @PawelWesolowski ) has a potential flaw where the other elements might exist but be non-visible, leading to potential false positives if the intent was to check that at least n elements are **visible**.

Due to the poll solution polluting the logs (as @deerwithanopinion pointed out), neither solution actually achieves the feature request in a clean way.

**Comment by Aaron-Pool** [comment]
It seems like the cleanest solution here would just be a more general numeric [asymmetric matcher](https://tfsserver.ornl.gov/tfs/DefaultCollection/RES-Agile/_git/RESolution/pullRequest/8162#1775148458). Something like:

```ts
expect.number({ min: number, max: number } | { min: number } | { max: number })
```

Allowing us to use the existing locator assertion for more general use cases:
 ```ts
expect(someLocator).toHaveCount(expect.number({ min: 5 });
expect(someLocator).toHaveCount(expect.number({ max: 3 });
expect(someLocator).toHaveCount(expect.number({ min: 5, max: 10 });
```
