### ISSUE TITLE
[BUG] CLI - `playwright debug` doesn't work with --project flag

### ISSUE THREAD

**Issue by lucasdellabella** [microsoft/playwright#8726]
**Context:**
- Playwright Version: 1.14.1
- Operating System: Mac
- Node.js version: 12.22

I try to run `npx playwright debug [--project=chromium] npx playwright test [--project=chromium]` with the project flag in either of these two places. In either case I get the output "error: unknown option '--project=Chromium'"

I'm able to run playwright with the inspector open if I run `PWDEBUG=1 npx playwright test --project=chromium`. I assume that I'm not doing something wrong and that this is a legimiate bug.

**Comment by mxschmitt** [comment]
Where did you see docs about `npx playwright debug`? There is not such a mode in the test-runner.

As you said, `PWDEBUG=1 npx playwright test --project=chromium` is the way how its recommended currently.

**Comment by lucasdellabella** [comment]
It's listed in the help output `npx playwright --help`, and works for some cases. Should probably be removed from the cli if the intent is for it to not exist.

```Usage: npx playwright [options] [command]

Options:
  -V, --version                          output the version number
  -h, --help                             display help for command

Commands:
  open [options] [url]                   open page in browser specified via -b, --browser
  codegen [options] [url]                open page and generate code for user actions
  debug <app> [args...]                  run command in debug mode: disable timeout, open inspector
  install [options] [browser...]         ensure browsers necessary for this version of Playwright are installed
  install-deps [browser...]              install dependencies necessary to run browsers (will ask for sudo permissions)
  cr [options] [url]                     open page in Chromium
  ff [options] [url]                     open page in Firefox
  wk [options] [url]                     open page in WebKit
  screenshot [options] <url> <filename>  capture a page screenshot
  pdf [options] <url> <filename>         save page as pdf
  show-trace [options] [trace]           Show trace viewer
  test [options] [test-filter...]        Run tests with Playwright Test
  help [command]                         display help for command
  ```

**Comment by mxschmitt** [comment]
Alright, thanks for providing that. Actually you were right, the `npx playwright debug` is a command and its intended to spawn a subprocess with the PWDEBUG environment variable. So it can be used like `npx playwright debug npx playwright test --project=chromium`.

In the current variant its not possible to pass additional parameters, but it gets fixed with https://github.com/microsoft/playwright/pull/8732 so its actually a bug!

**Comment by lucasdellabella** [comment]
Sweet, thanks max! Guess it's not something users are using often lol 🙃
