### ISSUE TITLE
[BUG] `popup` event seems to be unreliable

### ISSUE THREAD

**Issue by umanghome** [microsoft/playwright#873]
**Context:**
- Playwright Version: 0.10.0
- Operating System: Mac
- Extra: Running tests using Jest

**Describe the bug**
Trying to listen to `popup` event on the page, as well as `targetcreated` event on the browser. The listener for `popup` never gets invoked, but the one for `targetcreated` does.

**Comment by umanghome** [comment]
Don't have shareable code right now, will add it tomorrow.

**Comment by pavelfeldman** [comment]
Do you still experience this?

**Comment by pavelfeldman** [comment]
Closing since we can't repro this
