### ISSUE TITLE
[Question] Mute single tab

### ISSUE THREAD

**Issue by QueshAnmak** [microsoft/playwright#8730]
### Description
Is it possible to mute a single tab using playwright?
On msedge Ctrl+M shortcut can mute a tab, however 
```
await page.keyboard.down('Control');
await page.keyboard.press('KeyM');
await page.keyboard.up('Control');
```
```
await page.keyboard.press('Control+KeyM');
```
```
await page.keyboard.press('Control+M');
```
None of these 3 work.

I do not want to mute the whole browser using the `--mute-audio` switch, just a single tab.

**Comment by pavelfeldman** [comment]
This is outside of the scope for Playwright - our main focus is testing.
