### ISSUE TITLE
[Feature] Enable Istanbul code coverage collection with Playwright Test

### ISSUE THREAD

**Issue by anishkny** [microsoft/playwright#8734]
For frontend source code instrumented with [babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul) for code coverage, allow an easy way to collect that code coverage via `nyc`. The plugin stores coverage data in the `window.__coverage__` variable in the browser.

For now, this can be done in user-land via the [playwright-test-coverage](https://www.npmjs.com/package/playwright-test-coverage) package.

Ideally this should be built into Playwright test runner.

See also: https://github.com/mxschmitt/playwright-test-coverage/issues/1

**Comment by mxschmitt** [comment]
Let's maybe instead reopen https://github.com/microsoft/playwright/issues/7030?
