### ISSUE TITLE
[Feature] add expect(locator).isInViewport() / isIntersectingViewport

### ISSUE THREAD

**Issue by cardinalX** [microsoft/playwright#8740]
Now we have to use this method, the implementation of which is taken from puppeteer. It would be more convenient if it was in the playwright itself
```ts
  /**
   * @returns {!Promise<boolean>}
   * @summary Проверка, что нужный элемент находится в текущей области видимости(viewPort)
   */
  isIntersectingViewport(selector: string): Promise<boolean> {
    return this.page.$eval(selector, async element => {
      const visibleRatio: number = await new Promise(resolve => {
        const observer = new IntersectionObserver(entries => {
          resolve(entries[0].intersectionRatio);
          observer.disconnect();
        });
        observer.observe(element);
        // Firefox doesn't call IntersectionObserver callback unless
        // there are rafs.
        requestAnimationFrame(() => {});
      });
      return visibleRatio > 0;
    });
  }
```

Context: https://playwright.slack.com/archives/CSUHZPVLM/p1631008178339400

**Comment by pavelfeldman** [comment]
What's your use case for the method? (Helps us prioritize)

**Comment by cardinalX** [comment]
> What's your use case for the method? (Helps us prioritize)

We have some card elements, on clicking on which another subcards appears, and this appearance should occur in the user's field of view(there may be bugs that the subcards appeared below and the user will not even notice that something appeared)

**Comment by cardinalX** [comment]
I can, in principle, use the above method, which you actually suggested, thank you:) 
Therefore, I would not give this task a high priority if there are no new applicants

**Comment by federico-moretti** [comment]
I also would like this feature as we have an anchor tag and on mobile we want to check that after the click the page scrolls down to the anchor correctly.

**Comment by NikkTod** [comment]
We have long list of vertical pages of a report. When we select a particular page ( e.g. 10) we want to verify if the scroll has been performed and the page is now in the viewport.

**Comment by cliffordfajardo** [comment]
**Use case from our app**
Our page is loaded to a specific section of the page (essentially your pretty scrolled down)
User clicks the breadcrumb, and it scrolls them up to the first container of their page

I would like to assert the top container is in the viewport

https://user-images.githubusercontent.com/6743796/160018972-d69db8f3-4d31-4da0-8229-9d0c72d0a114.mp4

**Comment by cliffordfajardo** [comment]
Hi @pavelfeldman  @dgozman  @mxschmitt ,

**Use case from our app** (greetings from MSFT as well, well technically LinkedIn 😄 )
Our page is loaded to a specific section of the page (essentially your pretty scrolled down)
User clicks the breadcrumb, and it scrolls them up to the first container of their page

I would like to assert the top container is in the viewport

https://user-images.githubusercontent.com/6743796/160018972-d69db8f3-4d31-4da0-8229-9d0c72d0a114.mp4

**Comment by martindzejky** [comment]
My use-case from #13131: I have a sidebar in my app which, when collapsed, animates out of the viewport using `transform: translateX(-100%)` (see more in the linked issue). I want to write a test which asserts that when I press the collapse button, the sidebar animates out of the viewport and becomes "hidden".

**Comment by arturozv** [comment]
+1 on the use case of anchor tags that scroll to different sections of the page

**Comment by hkfsc** [comment]
+1 need this

**Comment by PeterHevesi** [comment]
Why not to add it directly into Playwright itself, when the method already exist? :D 
I don't think it would require a lot of work just to make this method available to everyone :D

**Comment by PeterHevesi** [comment]
Does anybody know, how can I create this method, to check if an element is in viewport in C#?
Because this method is in Javascript (which I hate) and I am not really able to port it into C# :D
Thanks for any help, I will greatly appreciate :)

**Comment by topolanekmartin** [comment]
+1 In my case this assertion will be very useful. I don't have any possibility how to check if element is fully visible at this moment.

![overlapping](https://user-images.githubusercontent.com/44465269/180977435-61b35517-73b9-49c1-8bb2-12554617bf54.gif)

**Comment by yurii-sav** [comment]
+ 1 I need this also

**Comment by edgeboy47** [comment]
+1 for testing if a navigation element scrolls to the correct section

**Comment by test20161010** [comment]
I need this to determine
if  the radio button is on negative coordinates and the corresponding label must be clicked or not.

**Comment by sarah-gelt** [comment]
+1 for this. We recently had a regression where scrolling stopped working in our side panel which opens to show detailed information about a row clicked in a table. 

I would want to:
1. Assert that the bottom-most element in the side panel is not in the viewport initially (there is always a delete button at the bottom of the side panel to delete the selected item from the table)
2. Scroll the delete button element into view
3. Assert that the delete button element is now in the viewport

There are various other parts of our UI that would benefit from this kind of regression testing including to check that long tables scroll correctly, navigation menu scrolls if the viewport is shorter than the menu height, etc. It seems this is a feature in Puppeteer and it has many potential benefits.
