### ISSUE TITLE
[Question/proposal/request] Is it possible to remove `await` from the syntax?

### ISSUE THREAD

**Issue by eLeontev** [microsoft/playwright#8745]
Hi,

I started to work with playwright and faced that it provides a lot of freedom for the developers/QA. That is really great.

In the examples it looks pretty good then as a code owner I could manipulate `async` flow and proper chain my `Promises` then the library takes care about synchronization of the steps. Like that

```{js}
const cb = async () => {
  await page.goTo(pageUrl);

  const title = await page.locator(titleSelector).textContent();

  expect(title).toBe(expectedTitle);
}
```

To look deeply on these lines I started to ask myself about "what does `await` mean?" - Is it to block my thread till the step is ready?

If we will look at any Test Cases we will see that they are in mostly cases are consistent - the next step can be started only previous is completed. Moreover in the tests we mostly do not expect to see a lot of parallel work (expect of test data preparation and business related tasks)

I started to look at `sync` languages like `Python` or `Java` and testing by them looks like the list of commands performed in declarative way
```{code}
// pseudo code
page.goto(pageUrl)
title = page.locator(titleSelector).textContent()
expect(title).toBe(expectedTitle)
```

So the languages themselves take care to handle all `async` functionality and perform the next steps right thread is ready. (I know it's their nature)

In the same time JS or Node engines were developed in async(unblocked) in/out flow that lead us to use `async` `await` or `chain`  flow to maintain the right order. 
For the tests scope I could suggest that it looks like that I must to `force block` the thread  to form the proper order.

In browser standards we have `XMLHttpRequest` which was used as the root of the `fetch` `polifylls`.
In the same time it supports `sync` and `async` flows [XMLHttpRequest/open](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/open) to block/unblock the thread during the requests.

Sync flow is not used as a  `not optimal` practice which lead to block browser users during the requests. So it was set to `async` flow by default to prevent  to unexpectedly block users.

Also for Node we have two types of API `async` and `sync` (e.g. file scope related)

**The question is next:** is it possible to extend current api based on something like was provided to use `sync` (blocked) threads methods to do not write redundant `async` `await` syntax?

The expected result could be next:
```{js}
const cbSync = () => {
  page.goToSync(pageUrl);

  const title = page.locatorSync(titleSelector).textContent();

  expect(title).toBe(expectedTitle);
}
```

p.s. I tried to find any `sync` `Http` related methods in Node but did not see it (like it is not implemented). In this case I guess this could be problematic to implement if this issues is resolved.

**Comment by pavelfeldman** [comment]
> is it possible to extend current api based on something like was provided to use sync (blocked) threads methods to do not write redundant async await syntax?

No, this is not a sustainable model in the Node.js platform.
