### ISSUE TITLE
Error: test.js:3:1: test() can only be called in a test file [Question]

### ISSUE THREAD

**Issue by Rainmen-xia** [microsoft/playwright#8748]
![image](https://user-images.githubusercontent.com/5163662/132364182-97acddf5-900a-4f88-a6eb-c484a8eb6b23.png)

I recode a "tes.js" file by "codegen";
but run failed:
show:
Error: test.js:3:1: test() can only be called in a test file

**Comment by pavelfeldman** [comment]
How are you running your tests, where are they located?

**Comment by Rainmen-xia** [comment]
> How are you running your tests, where are they located?

"node test.js"

**Comment by pavelfeldman** [comment]
That's not how Playwright Test is used. Please refer to https://playwright.dev/docs/intro#first-test for docs on how to write tests!
