### ISSUE TITLE
[BUG] frame.click and frame.fill hangs on "element is not visible - waiting..." even when the page is fully loaded and the element selector is clearly visible

### ISSUE THREAD

**Issue by ubersl0th** [microsoft/playwright#8766]
**Context:**
- Playwright Version: 1.14.1
- Operating System: Linux 5.10 Ubuntu 20.04.3 LTS on WSL2
- Node.js version: 16.8.0
- Browser: Chromium
- Extra: frame is this case is an IFrame handle

**Code Snippet**

```javascript
// IFrame contentframe
const locator = page.locator('iframe.iframe-class').first();
const handle = await locator.elementHandle();
const iframe = await handle.contentFrame();
    

// Click [data-testid="testid"]
await iframe.click('[data-testid="testid"]');
// Stuck here forever with the folowing in debugger: "element is not visible - waiting..."
```

I have a test case where I load in an iframe and locate its contentFrame and then want to click a button with frame.click().
I use a unique data-testid as the selector.
But *sometimes*, not always, the test hangs on a click() or a fill() with the following message in the Inspector log: "element is not visible - waiting..."
So it seems to me the method for waiting for element visible does not recheck the state, but checks it once and then hangs until the timeout is exceeded, and if the page load is a bit slow it hangs.

See image below to see the console and the highlighted selector, it is clearly visible and fully loaded, however it will hang here for eternity when running in debug mode, I have to close it manually to kill the test.
![image](https://user-images.githubusercontent.com/6698759/132478151-7413a516-2295-457c-a420-01c2d40e9be1.png)

**Comment by JoelEinbinder** [comment]
Did you figure it out?

**Comment by ubersl0th** [comment]
The selectors was not as unique as I thought, so just faulty logic regarding multiple instances of the same iframe. Didn't find any way to delete the issue so just closed it, sorry.
