### ISSUE TITLE
Firefox in Docker Container throws TimeOut Error for Playwright

### ISSUE THREAD

**Issue by sqalearnings** [microsoft/playwright#8767]
There is scenario where we don't want to use Playwright browser. We are installing Firefox browser manually by passing install command in Docker File. There is no error while installing but running Firefox in Docker Container throws below error.

![image](https://user-images.githubusercontent.com/79274352/132483659-c8076edd-bf7f-447f-8d76-eefdae9bd451.png)

Tried with Ubuntu Firefox packages : firefox-geckodriver and firefox

**Below is the Docker File**

![image](https://user-images.githubusercontent.com/79274352/132484141-5e9fe263-f86f-4cd3-bce6-19d201f88d38.png)
![image](https://user-images.githubusercontent.com/79274352/132484216-abf2c901-8c4d-4738-886f-b9e76a71526d.png)

-------------------------------------------------------------------------------------

**Comment by JoelEinbinder** [comment]
We run against our own fork of Firefox, so using the official builds will not work.
