### ISSUE TITLE
[Question]: Single Sign On logins do not work in headless mode but the same are working in non-headless mode

### ISSUE THREAD

**Issue by kumarragMSFT** [microsoft/playwright#8777]
### Your question

I am working on an automation tool to check links for validity. Most of the links being tested are internal links and require that the browser adheres to policies i.e. a user is logged into the browser (i.e. the browser context is launched using launch_persistent_async function) and then the user is signed in to the single sign on.

At setup the browser is opened in non-Headless mode and admin signs into the single sign on using a given account. Poth that the browser is able to access all the links, beyond the authentication, as long as the browser runs in the non-headless mode, but if I try to run the browser in headless mode it does not work and the single sign on is unable to detect that the user is already logged in. Note that in both the cases the browser context is being launched using launch_persisten_context and the user path is  same i.e. the saved user profile information should be same in both the modes. Another interesting part is that in headless mode some of the websites identify the logged in user, but some sites don't and if I try to automate the process of entering user id and password, the site blocks the attempt stating policies are not met.

How can I ensure that the browser behaves similarly in headless as well as non-headless mode with respect to authentication and if it is okay to expect the headless and non-headless mode to behave exactly the same wrt cookies, authentication and single sign on?

**Comment by MarcusFelling** [comment]
@kumarragMSFT - there are a number of reasons you're experiencing this. As @avodovnik mentioned, policies could be one of them, detecting user agent, headless, etc. Another could be cookies not persisting (known issue: https://github.com/microsoft/playwright/issues/717).
