### ISSUE TITLE
[BUG] Editing on canvas element produces invalid screenshot on macOS Webkit

### ISSUE THREAD

**Issue by henrydzung** [microsoft/playwright#8796]
**Context:**
- Playwright Version: 1.14.1
- Operating System: macOS Big Sur
- Node.js version: 14.17.5
- Browser: Webkit

**Code Snippet**

``` typescript
test('canvas drawing', async ({ page }) => {
  await page.goto('https://amoshydra.github.io/draw/', { waitUntil: 'networkidle' });

  await addLine(1); // Draw first line
  await page.screenshot({ path: 'canvas-1.png' });

  await addLine(2); // Add second line
  await page.screenshot({ path: 'canvas-2.png' });

  await addLine(3); // Add third line
  await page.screenshot({ path: 'canvas-3.png' });
});
```

**Describe the bug**

I have a web app that has an editable canvas area that let user draw with their cursor. I have to take screenshots for different scenarios where user draws different things.

On `macOS` - `webkit`, after taking screenshot of the first edit, screenshots taken by subsequent edits will be the same as the first.   
(In the above example, `canvas-2.png` and `canvas-3.png` will be the same as `canvas-1.png` - only have one line).

This only happens in `webkit` on `macOS`, on `Windows` or other browsers it's working as intended.

**Comment by dgozman** [comment]
I can reproduce this.

**Comment by yury-s** [comment]
I believe it might be another manifestation of the same problem with hw accelerated canvas as in https://github.com/microsoft/playwright/issues/586

**Comment by henrydzung** [comment]
It seems that the bug has been fixed in v1.18.1.

**Comment by aslushnikov** [comment]
@henrydzung are you on MacOS 12?

**Comment by henrydzung** [comment]
@aslushnikov I'm still on MacOS 11. 11.6.2 to be specific.
