### ISSUE TITLE
[BUG] Incorrect attachments in junit report  

### ISSUE THREAD

**Issue by Gornostalev** [microsoft/playwright#8799]
**Context:**
- Playwright Version: [1.14.1]
- Operating System: [Windows]
- Node.js version: [v14.17.5]
- Browser: [Chromium]

 Hello 🤚🏻, i need to xml file for azure devops pipeline 
 i upload bug example in my [repo](https://github.com/Gornostalev/playwrightBugAttach)

and for attach info i use that code:

```
test.afterEach(async ({ }, testInfo) => {
  testInfo.attachments.push({
    name: 'my attach',
    path: `/testPath`,
    contentType: 'text/html',
  })
})
```
when i run this with command `npx playwright test --config=playwright.config.ts`
i expected this https://docs.gitlab.com/ee/ci/unit_test_reports.html#viewing-junit-screenshots-on-gitlab
but got this in console but no in file:

`<testsuites id="" name="" tests="1" failures="0" skipped="0" errors="0" time="0.374">
<testsuite name="test.test.ts" timestamp="1631177140166" hostname="" tests="1" failures="0" skipped="0" time="0.004" errors="0">
<testcase name="Test" classname="test.test.ts:3:1 › Test" time="0.004">
</testcase>
<system-out>
[[ATTACHMENT|..\..\..\..\..\testPath]]
</system-out>
</testsuite>
</testsuites>`
tag `<system-out>` must be in `<testcase>` tag, for this reason i have null attachments on pipeline in azure devops

and why output in console?

**Comment by dgozman** [comment]
> tag `<system-out>` must be in `<testcase>` tag

This is a bug, we'll fix it. Thank you for the repro!

> and why output in console?

It is explained in the [junit reporter documentation](https://playwright.dev/docs/next/test-reporters#junit-reporter).
