### ISSUE TITLE
[Feature] Allow multiple grep patterns

### ISSUE THREAD

**Issue by MindaugasMateika** [microsoft/playwright#8800]
Similarly to [running multiple projects](https://github.com/microsoft/playwright/issues/8583) I find it useful if it would be possible to pass multiple grep patterns. I'm curious to find if it's something that you would consider implementing.

Problem:

Given tests with different tags

```
import { test, expect } from '@playwright/test';

test('Test login @smoke', async ({ page }) => {
  // ...
});

test('Test upload @team-a', async ({ page }) => {
  // ...
});

test('Test catalog @team-b ', async ({ page }) => {
  // ...
});
```

in my case sometimes it's required to run tests containing different tags, for example `"@smoke @team-a"`. However, at the moment, it's only possible to pass a single pattern `--grep="@smoke"` and well, trying to pass multiple tags or using --grep more than once, doesn't work.

**Comment by pavelfeldman** [comment]
You can 'or' in grep!

**Comment by MindaugasMateika** [comment]
Oh my, indeed. I should spend more time investigating issues on my own :< If anyone else stumbles on this, 
`--grep='pattern1|pattern2'`  works.
