### ISSUE TITLE
[Feature] Possibility to register a step inside a custom fixture.

### ISSUE THREAD

**Issue by cardinalX** [microsoft/playwright#8804]
Now I use just a functions to use common actions. Since I break most of these actions into steps, so that it is clearer in the reports what the failure occurred on, because the expect method cannot accept messages, to clarify the details. 
Therefore, I use `test.step()`, which is even more convenient for allure reports in principle.

Thus, I would like to use the fixture mechanisms, with the ability to specify steps, instead of using the usual typescript functions.

**Comment by JoelEinbinder** [comment]
@pavelfeldman seems reasonable to me. Can we do testInfo.step or does it break because of worker fixtures?

**Comment by pavelfeldman** [comment]
Could you provide an example?

**Comment by dgozman** [comment]
@cardinalX Perhaps you can just call `test.step`?

```js
const myTest = test.extend({
  myFixture: async ({}, use) => {
    await test.step('my step', () => { /* do stuff */ });
    await use(123);
  },
});
```

**Comment by dgozman** [comment]
Using `test.step` should just work. Feel free to open a new issue with an example where it does not work.
