### ISSUE TITLE
[BUG] Closing the page manually does not trigger the onClose event

### ISSUE THREAD

**Issue by gigitalz** [microsoft/playwright#8818]
When closing the page manually, the onClose event on contexts and/or pages is not triggered and the page navigates an invisible instance.
I started chrome in headless mode false.

**Context:**
- Playwright Version: 1.14.1
- Operating System: Windows, 10
- Node.js version: 14
- Browser: Chrome

**Comment by pavelfeldman** [comment]
When you say manually, do you mean via closing the tab or via issuing page.close()? Could you provide steps to repro?

**Comment by gigitalz** [comment]
Open an headless browser, then navigate to any url, then close the page manually (i mean with the mouse)... onClose does not trigger.

**Comment by dgozman** [comment]
This works for me locally. Could you please provide a repro script?

```js
const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({ headless: false });
  const context = await browser.newContext();
  const page = await context.newPage();
  page.on('close', () => {
    console.log('Got it!');
  });
  // Click on the 'x' button and observe "Got it!".
})();
```

**Comment by dgozman** [comment]
Closing because we cannot repro.
