### ISSUE TITLE
can't click button, always returns "element is not visible" error

### ISSUE THREAD

**Issue by XufengXufengXufeng** [microsoft/playwright#8830]
the page i am visiting is [https://olympics.com/tokyo-2020/olympic-games/en/results/swimming/results-women-s-4-x-100m-freestyle-relay-fnl-000100-.htm](url)

i need to click on the plus sign, which is "input" element on page. so that a detail table appears. but it keeps output "element is not visible" error. I have tried many setting, like long timeout and force action, no luck.

here is my python code: 
`
page = browser.new_page()
page.goto(url,timeout=180000)

msc = page.query_selector_all("table.table-result:has(tbody)")[0].query_selector("tbody")
for tr in msc.query_selector_all("tr"):
    button = tr.query_selector("input.split_button")
    button.click(button="middle",timeout=180000,force=True,no_wait_after=False)`

someone please help, many thanks.

**Comment by pavelfeldman** [comment]
do `page.locator('.table-result .spli_button').first().click()` instead of all of that!

**Comment by XufengXufengXufeng** [comment]
> do `page.locator('.table-result .split_button').first.click()` instead of all of that!

thank you for your reply, but i get `AttributeError: 'Page' object has no attribute 'locator'` error with the page.locator. I am using python 3.8. And playerwright version is 1.13.1,

by the way, what's the reason why element_handle.click() doesn't work for my case? And that .first api, what's the functionality of it?

**Comment by XufengXufengXufeng** [comment]
> do `page.locator('.table-result .split_button').first.click()` instead of all of that!

 I upgrade the playwright to 1.14.1, now the error appears as `element is not visible - waiting...`. With force=True setting, the error goes `playwright._impl._api_types.Error: Element is not visible`. Same error as the element_handle.click(). 

My internet is not stable for sure, but I can visit the site and click buttons on web browser. please help me with this issue. thank you.

**Comment by XufengXufengXufeng** [comment]
> do `page.locator('.table-result .split_button').first.click()` instead of all of that!

 I upgrade the playwright to 1.14.1, now the error appears as `element is not visible - waiting...`. With force=True setting, the error goes `playwright._impl._api_types.Error: Element is not visible`. Same error as the element_handle.click(). 

My internet is not stable for sure, but I can visit the site and click buttons on web browser. please help me with this issue. thank you.

**Comment by XufengXufengXufeng** [comment]
It is my miss operation of the api. I apply click on the first element, which is wrong, it should be the second element. the click api works fine.
