### ISSUE TITLE
[Question] Is there a workaround to the restriction for route.resume(options.setUrl()) where in, it does not allow the new Url to have a different protocol than the original one?

### ISSUE THREAD

**Issue by tushitaaggarwal** [microsoft/playwright#8831]
I am trying to replace a url of an intercepted request say https://localhost/index.html to file://C://somepath/index.html. How can I achieve this in playwright java? I tried using route.resume and set url there but it has the above mentioned restriction. Let me know if there is any way to replace the original url with a new one starting with a different protocol. And if not, can support for the same be added?

**Comment by pavelfeldman** [comment]
You can't route to file://. But you can reqd from file and route.fulfill right away.

**Comment by tushitaaggarwal** [comment]
Hi Pavel,
Thank you for the clarification. We were aiming to load the an html file using file protocol instead of localhost protocol in our intercepted request but as I understand that will not be currently viable in playwright. Also wanted to know why there is a restriction on changing protocols in the urls when calling route.resume(options.setUrl(newUrl))? This was previously working for us using the Chromium Embedded Framework and since then we switched to playwright where we could not find an equivalent way to accomplish it.

**Comment by pavelfeldman** [comment]
```js
await page.route('**/*', route => {
  const url = new URL(route.request().url());
  route.fulfill({
    body: fs.readFileSync(url.pathname),
    contentType: mime.getType(url.pathname)
  });
});
```

**Comment by dgozman** [comment]
@tushitaaggarwal Let us know if the snippet above does not work for you.

**Comment by tushitaaggarwal** [comment]
Hey, sure but this is in nodejs, could you provide the java version equivalent for the above snippet.

**Comment by tushitaaggarwal** [comment]
Hi Pavel/Dmitry,
I tried to run the code snippet attached by you, while it is able to read the contents for some files fine, it fails in case of a url to a local html but with parameters such as - C:/Users/file_location/workspace.html?param_one=https%3A%2F%2xyz.com%2F&param_two=xyz.  Could you please help me with resolving the above snippet for this case?

Here is our code for playwright java- 
```
String fileContents = new String(Files.readAllBytes(Paths.get(routeURL)));
route.fulfill(new Route.FulfillOptions().setBody(fileContents).setContentType(Files.probeContentType(Paths.get(routeURL))));
```

Note: the routeURL here is of the format -  C:/Users/file_location/workspace.html?param_one=https%3A%2F%2xyz.com%2F&param_two=xyz

**Comment by dgozman** [comment]
@tushitaaggarwal How do you get the `routeURL`? I'd suggest to parse it with `java.net.URL`:

```java
import java.net.URL;
// ...
String routeURL = new URL(route.request().url()).getPath();
```

**Comment by tushitaaggarwal** [comment]
Hi Max/Pavel/Dmitry,
We would need a more detailed discussion since the above approach is still not working for us and I think this could be due to a url with some query params like -  C:/Users/file_location/workspace.html?param_one=https%3A%2F%2xyz.com%2F&param_two=xyz . We can open the file contents but not sure what happens to the query params. We would be happy to share the test files over a private thread for more details.

**Comment by dgozman** [comment]
@tushitaaggarwal What are your expectations about query params? When you fulfill the route, you just give it the content, and url in the page stays the same and query params should still be there.

Do you have a repro script that we can run locally? That would greatly help the discussion.

**Comment by dgozman** [comment]
It looks like we cannot do anything useful here from the Playwright side.
