### ISSUE TITLE
Unable to install browser binaries with 1.14.1

### ISSUE THREAD

**Issue by Phonesis** [microsoft/playwright#8834]
**Context:**
- Playwright Version: v1.14.1
- Operating System: Mac
- Node.js version: 10.13.0

Since upgrading to 1.14.1, we cannot install the browser binaries. Playwright installs ok but complains at run time that the binaries are not installed.

We perform npx install command but this fails with 

```
Failed to install browsers
TypeError: Cannot read property 'mkdir' of undefined
```

I have tried deleting nodule modules folder and performing npm install --force. Neither work. Have had to roll back to version 1.12.3 where we do not get any install issue

**Comment by mxschmitt** [comment]
Playwright requires Node.js 12+. We recommend 14+

**Comment by Phonesis** [comment]
Thank you, did this requirement come in with 1.14 then as, like I say, seemed to work fine with version 10.13.0 of node when using 1.12.3 of Playwright

**Comment by mxschmitt** [comment]
We internally changed some internals which are only available in Node.js 12+ yeah.

Keep in mind, that Node.js 10 does not get security updates etc. anymore.
