### ISSUE TITLE
[Question] What is the current directory for test.use() to load storage state?

### ISSUE THREAD

**Issue by sheeeng** [microsoft/playwright#8838]
I would like to [reuse authentication state](https://playwright.dev/docs/auth#reuse-authentication-in-playwright-test). However, I failed to load the file even though it exists in `process.cwd()` directory.

```typescript
import { test } from '@playwright/test';

test.use({ storageState: 'state.json' });

test('test', async ({ page }) => {
  await page.goto('http://localhost:5000/');
  // We are still _NOT_ logged in!
});
```

**Comment by pavelfeldman** [comment]
It should be `process.cwd()`. Try printing your `process.cwd()` from the test to see if it matches your expectations.

**Comment by pavelfeldman** [comment]
Also, if you are saying your test ran, it means it did not throw exception in test.use. Which means it found the file. Looks like your state does not have enough information to log you in. You can use CLI to open a page based on that state and see if you are logged in.

**Comment by sheeeng** [comment]
Tried `test.beforeEach` and `test.beforeAll` to make sure `globalSetup` completes before running other tests, but to no avail.

**Comment by sheeeng** [comment]
Also, I do not setup global setup inside the main Playwright Configuration, as I also would like to test sign in process as a separate test that does not rely on reuse of authentication state.

As the [documentation](https://playwright.dev/docs/auth#code-generation) mentions, `In each test, load authentication state in beforeEach or beforeAll step.` Most tests requires reuse of authentication state from `globalSetup` as mentioned in earlier comments, am I missing something else to make it work?

Perhaps it is related to https://github.com/microsoft/playwright/issues/7050, but I am not sure about it.

**Comment by sheeeng** [comment]
Closing this issue as the current directory question was explained clearly.
