### ISSUE TITLE
[BUG] Empty Folder for successful test

### ISSUE THREAD

**Issue by StfBauer** [microsoft/playwright#8840]
**Context:**
- Playwright Version: 1.14.1
- Operating System: MacOS
- Node.js version: 14.16.0
- Browser: ALL
- Extra: [any specific details about your environment]

## System:
 - OS: macOS 10.15.7
 - Memory: 9.32 GB / 64.00 GB
## Binaries:
 - Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
 - Yarn: 1.22.10 - /usr/local/bin/yarn
 - npm: 7.20.5 - ~/.nvm/versions/node/v14.16.0/bin/npm
## Languages:
 - Bash: 5.1.4 - /usr/local/bin/bash

**Describe the bug**
It seems like the BUG #7093 has come back again.

I use in my playwright config:

```js
screenshot: 'only-on-failure'
```
but still get spammed with empty folder even of test that had no issue.

**Comment by pavelfeldman** [comment]
I created an empty project with just one test, specified screenshot: 'only-on-failure' there, no stray folders. Switched it to 'on', got the folders with images. Is there a repro you could share?

**Comment by StfBauer** [comment]
I should probably do the same next to the original project, this then I would be able to share.

**Comment by dgozman** [comment]
@StfBauer Any chance for a repro?

**Comment by StfBauer** [comment]
I will provide one this week. Sorry for the delay.

**Comment by mxschmitt** [comment]
Closing since it seems stale. Please create a new issue with a repro so we can fix it for future users.
