### ISSUE TITLE
[Question] How to use Playwright with Docker Compose and Node.js?

### ISSUE THREAD

**Issue by alinnert** [microsoft/playwright#8845]
I'm trying to setup a Node.js application that uses Playwright and that runs inside Docker. I use the Playwright image as a base image inside my own `Dockerfile`. This `Dockerfile` gets then used by a `docker-compose.yml`.

I did see [this page about Docker](https://playwright.dev/docs/docker) in the docs. But it only includes a docker CLI command. That's not super helpful for my use-case. I was able to use the information to build my Compose setup, though. Almost. I also found this comment in the following issue: https://github.com/microsoft/playwright/issues/6383#issuecomment-831145063. It basically says that the Playwright Docker image is meant to be used as a base image for your own custom image. That's exactly what I'm trying to do. This confuses me even more why there's no Dockerfile or Compose example. Could those maybe added to the docs?

Anyway, I'm stuck at the `--security-opt seccomp=seccomp_profile.json` option. I don't know how to translate this to use it inside my `docker-compose.yml`. According to this PR: https://github.com/docker/compose/pull/5701 Compose should support such JSON files. But also, the Docker docs ([one](https://docs.docker.com/engine/security/seccomp/) and [two](https://docs.docker.com/compose/compose-file/compose-file-v3/#security_opt)) don't say *how* that can be done.

I've tried this:

~~~ yml
services:
  my-service:
    # ...
    security_opt:
      - seccomp:seccomp_profile.json
~~~

But then I get the error that `s` is an unexpected token. If I try `- seccomp:./seccomp_profile.json` then `.` is an unexpected token. That means that Compose is unhappy about what comes after `seccomp:`.

I can run my application and use Playwright just fine by removing the `security_opt:` portion, but I guess this should not be used in production, right?

Btw: While running the container directly I've noticed that the provided content for the `seccomp_profile.json` includes a mistake. It's structured like this: `[{ ... }]`. The top-level item in the JSON file should be the object, not an array. So, the array's brackets should be removed. After doing this locally the container started running.

**Comment by pavelfeldman** [comment]
This looks like a docker question more than a Playwright question. @aslushnikov, do you know if we can help here?

**Comment by aslushnikov** [comment]
> I can run my application and use Playwright just fine by removing the security_opt: portion, but I guess this should not be used in production, right?

@alinnert Most of the time you can disregard `security_opt` if you're running your tests inside docker. The security profile for docker is only needed if you want to force sandbox to `true` when launching chromium; this is only needed if you load untrusted content in the browser (e.g. scraping some URLs).

**Comment by alinnert** [comment]
> The security profile for docker is only needed if you want to force sandbox to true when launching chromium; this is only needed if you load untrusted content in the browser (e.g. scraping some URLs).

@aslushnikov yes, that's what I'm planning to do. Basically, I'm trying to build a kind of feed app for websites that don't support RSS or not for a specific set of items.

**Comment by aslushnikov** [comment]
@alinnert ah, i see. Seccomp would be helpful then, indeed!

However, I don't have experience with providing seccomp to docker-compose; I see you already dug some history there. 
If you find anything, please post here so that we can learn too!

(Closing this since there's no action on the Playwright side.)

**Comment by unikitty37** [comment]
I found this was valid:

```
    security_opt:
      - seccomp=seccomp_profile.json
```

However, when I use the `seccomp.json` from the documentation, I get this error:

```
ERROR: for playwright  Cannot start service playwright: Decoding seccomp profile failed: 
json: cannot unmarshal array into Go value of type seccomp.Seccomp
```

which at least shows it's reading the file! But I have no idea what I should be putting in the file when I've already copied what's in the docs:

```json
[
  {
    "comment": "Allow create user namespaces",
    "names": [
      "clone",
      "setns",
      "unshare"
    ],
    "action": "SCMP_ACT_ALLOW",
    "args": [],
    "includes": {},
    "excludes": {}
  }
]
```
