### ISSUE TITLE
[Feature] Show skipped tests names and skip messages in --list output

### ISSUE THREAD

**Issue by MindaugasMateika** [microsoft/playwright#8852]
Edited the issue: 

The initial proposal was to put skipped tests info in the reporter output but after what Pavel said, it would make more sense to have it in `--test` output avoiding spam in reporter output. The minor downside is that `--list` not gonna tell which tests will be actually skipped but having annotation info would be helpful anyway. Given tests:

```
test('Test catalog search', async ({page}) => {
  await test.skip(page.url().startsWith('https://www.someurl.fr'), 'There is no search on FR environment')
  ...
})

test('Test catalog filters', async ({page}) => {
  ...
})

...
``` 

maybe `--list` could provide output similar to that. Not sure about formatting though.

```
Listing tests:
  [fr] › CatalogTests.ts:4:1 › Test catalog search -- There is no search on FR environment
  [fr] › CatalogTests.ts:20:1 › Test catalog filters
  [fr] › CatalogTests.ts:24:1 › ...
 ```

**Comment by MindaugasMateika** [comment]
In the meantime, maybe I could achieve this behaviour in some other way? I've looked into implementing my own reporter but I don't think I can access skip message, can I?

**Comment by pavelfeldman** [comment]
You should see it in the annotations (https://playwright.dev/docs/next/api/class-testcase#test-case-annotations) in your reporter. Your proposal makes sense for 1 skipped, but larger projects will have 768 skipped and it'll be spamming console for no good reason. We could probably improve `--list` and print skipped tests with annotations.

**Comment by MindaugasMateika** [comment]
Fair point, such info in `--list` would help too. I've updated issue title and body.

**Comment by cmacdonnacha** [comment]
@pavelfeldman Would you be able to provide an example on how to get this working with annotations? I have the following skip annotation in my test:

`test.skip(process.env.TOKEN === undefined, 'This test was skipped because token was not passed in');`

But I don't see the description in the terminal output. Is there something else I need to include or pass into the command: `npx playwright test`.

**Comment by unickq** [comment]
So is there an option to list skipped tests? --list for `test.skip()`
Tried grep, but didn't work

**Comment by angelo-loria** [comment]
+1, having an option to print skipped test description from `test.skip( condition, description )` would be handy

**Comment by pavelfeldman** [comment]
We are leaving this to the third parties to implement using the reporters api!
