### ISSUE TITLE
[Question] How to avoid the error: Error: locator.count: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#8857]
Hi all.
In our web application, we have a kind of spinner in order to disable the page - until the data is loaded.
If the network is slow - there is a case that several spinners can appear in the DOM.
 I use the locator.count() method in order to check the counter of spinner locator and in order it bigger than 0 - I wait until it will 0.

But I sometimes get the mentioned error.

I guess it related to the disappearance of the element.
Is any solution to handle this situation? 
```javascript
public async waitUntilSpinnerInvisible() {
        try {
        let elementCounter = await this.page.locator('[class="waitingMask"]').count();
        console.log('elementCounter',elementCounter);
        while(elementCounter > 0){
       
            elementCounter = await this.page.locator('[class="waitingMask"]').count();
            console.log('elementCounter inside while',elementCounter);
        }
   
            } catch (error) {
                this.logger.error(`${error}`);
            }

    }
```
I made an attempt to use the locator.isHidden() method - but sometimes got the same error.

**Comment by dgozman** [comment]
@AlexKomanov I think that your test times out and closes the page before spinners disappear. Here is an easier version waiting for zero spinners. See docs for other [useful assertions](https://playwright.dev/docs/test-assertions).

```js
await expect(this.page.locator('[class="waitingMask"]')).toHaveCount(0);
```

Does this help?

**Comment by AlexKomanov** [comment]
@dgozman 
Thanks a lot!
It seems very helpful and I don't need to use hard-coded waiters.
