### ISSUE TITLE
[Feature] API for direct integration with some dashboard service

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#8858]
Hi guys!
Thanks to all of you!
You do a great job!
We got the integration with the Allure report. I would like to ask for integration that will take it several levels up.
Is it possible to make some API for direct integration with some dashboard service? Like a [DataDog](https://www.datadoghq.com/) ?

The report can be not so useful if there is a huge amount of them. The dashboard service - stores the results and provides additional information like history of runs, the current state of any feature, etc. 
The Datadog service is just an example - if you can provide your solution (like in the case of the [Cypress](https://www.cypress.io/dashboard/) it will be great!

Thanks!

**Comment by dgozman** [comment]
@AlexKomanov This is not currently in scope of Playwright. We are looking forward for third-party integrations with any dashboards. I believe our current [reporter api](https://playwright.dev/docs/api/class-reporter) is enough for this, but if not we are always open to providing more information if needed. Thank you for the issue!
