### ISSUE TITLE
[Feature] Dedicated section for options like '>> visible=true' in the documentation

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#8860]
Hi team!

I would like to suggest the creation of a dedicated section in the documentation that describes options like '>> visible=true'. I found it in this [section](https://playwright.dev/docs/selectors#quick-guide), but I didn't find any section that contains all options. Also, the auto-complete doesn't give any hint about possible options. 

In my case - the mentioned option is very useful because on several pages (in our web application) the playwright finds several same elements in DOM, and also those that are not actually visible. And this option helps to handle actually only with a visible element.

**Comment by dgozman** [comment]
@AlexKomanov There is a [visibility section](https://playwright.dev/docs/selectors/#selecting-visible-elements) for this. For some reason we don't have links from the "quick guide" to detailed explanations, I'll take a look at it.
