### ISSUE TITLE
[Question] I cannot navigate to a relative url in Java

### ISSUE THREAD

**Issue by gigitalz** [microsoft/playwright#8861]
If I put a relative url in the navigate method it thinks it's an invalid url...
Ho can we navigate relatively?

**Comment by ltsuda** [comment]
Are you using Playwright Test ? If so, you can add the `baseURL` to the `playwright.config.js or .ts` as stated in this link https://playwright.dev/docs/test-configuration#basic-options

Then, every `.goto("/path")` will be relative to that URL.

**Comment by ltsuda** [comment]
I think you can set the `baseURL` on the `Browser.newContext()` and `Browser.newPage()` as stated here:
https://playwright.dev/java/docs/api/class-browser/#browser-new-context
https://playwright.dev/java/docs/api/class-browser/#browser-new-page

Then the navigate("/path") will be relative to that URL.

**Comment by dgozman** [comment]
@ltsuda Thank you, that's exactly right!
