### ISSUE TITLE
[Question] addScriptTag - throw an error of: page.addScriptTag: Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'

### ISSUE THREAD

**Issue by hananmalka** [microsoft/playwright#8866]
Hi, 

I'm trying to add a script tag:
`page.addScriptTag({ path: "automation/script.js" });`

And when reaching this line in code I'm getting the error:
page.addScriptTag: Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'

I added the following args to my launch config but still getting this error:
`args: ["--disable-web-security"]`

Am I missing some args? How can I overcome this issue?

**Comment by pavelfeldman** [comment]
https://playwright.dev/docs/api/class-browser#browser-new-context-option-bypass-csp try this one!

**Comment by hananmalka** [comment]
Thanks!!! @pavelfeldman 
Missed that property.
It works!

**Comment by nikitaeverywhere** [comment]
> https://playwright.dev/docs/api/class-browser#browser-new-context-option-bypass-csp try this one!

@pavelfeldman in my use case, `bypassCSP` option has to be disabled as it changes the page's behavior.

Is there any workaround to `page.addInitScript()` while preserving original CSP settings?
