### ISSUE TITLE
[Question] How to remove older versions of the playwright?

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#8867]
Hi all,

As I understand, the older created folders by the playwright, not removed. Like in this screenshot:

![image](https://user-images.githubusercontent.com/52656401/132972915-80199658-05d2-4d97-be89-b3dbcfcef73f.png)

Do I need to remove the older version in some way (for example: `npm uninstall playwright`) before I update to the newest version?

**Comment by pavelfeldman** [comment]
When you install new version of Playwright, it removes browsers that are no longer used. If you see those browsers in that folder, it means there are other projects on the system that are using older versions of Playwright. Upgrade them to the new Playwright and these browsers will get deleted.

**Comment by AlexKomanov** [comment]
Thanks @pavelfeldman

**Comment by rojobuffalo** [comment]
is there no uninstall script?
