### ISSUE TITLE
[Feature] Playwright API for checking 'text contains' in array of elements 

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#8869]
Hi all,

I want to check if some row within a table (array of rows) contains some text.
If I use the **expect** API - it will fail on the first not matching result.
I created a custom method as can be seen below and I use a regular JS forEach() function. Is any other solution that I missed? Orr if there is no one - is it possible to create it?

```javascript
   public async validateItemOnGrid(item: string) {
        await this.searchWithQuickSearchField(item);
        const gridRows = await this.page.$$('[data-uitestingname="body.Grid"] [data-uitestingname^="body.Grid.Row."] >> visible=true');
        for (let gridRow of gridRows) {
            const rowText = await gridRow.innerText();
            console.log(rowText);
            if (rowText.includes(item)) {
                await gridRow.click();
                await this.validator.validateContainText(rowText, item)
                return;
            }
        }
    }
```

**Comment by dgozman** [comment]
@AlexKomanov So, you want to check that one of the elements in a list (with the same selector?) contains some text?

Perhaps, ```await expect(`[data-uitestingname="body.Grid"] [data-uitestingname^="body.Grid.Row."] >> text=${item}`).toBeVisible()``` will just work for you?

**Comment by AlexKomanov** [comment]
@dgozman 
Actually, I need to check that one of the rows in the table contains the text that I'm looking for. And then It should click the row. The table looks like this:

![image](https://user-images.githubusercontent.com/52656401/133198101-aca2942b-1572-4c4e-a9da-7af8654d691e.png)

And I check each row with the same pattern (same locator).

**Comment by dgozman** [comment]
@AlexKomanov In this particular case, why don't you use a text selector for this?
```js
await page.locator(`[data-uitestingname="body.Grid"] [data-uitestingname^="body.Grid.Row."] >> visible=true >> text=${item}`).click();
```

If you wouldn't need to click, we  can implement something like `await expect(locator).toContainText(['foo', 'bar'])` that is somewhat similar but not exactly what you need here.

**Comment by AlexKomanov** [comment]
@dgozman 
In my opinion, the most useful case should be the option to provide to expect some array of elements and only in case that no one of them was found as a matching one - it will trigger some error.

**Comment by dgozman** [comment]
With #9160, I think we should have all the expects in place:

- Expect that the list contains some items with specific text:
  ```js
  await expect(page.locator('.list-item')).toContainText(['Item 4', 'Item 18']);
  ```

- Expect that some element has one of the possible text values (using regex):
  ```js
  await expect(page.locator('.title')).toHaveText(/foo|bar|baz/);
  ```

- Expect that some item from the list contains one of the possible text values:
  ```js 
  await expect(page.locator('.list-item')).toContainText([/foo|bar|baz/]);
  ```
