### ISSUE TITLE
[BUG] Cannot read property 'width' of null for Webkit screenshot

### ISSUE THREAD

**Issue by mmarkelov** [microsoft/playwright#887]
**Context:**
- Playwright Version: [0.10.0]
- Operating System: [Mac]

**Code Snippet**

```javascript
const playwright = require('playwright');

(async () => {
    for (const browserType of ['chromium', 'firefox', 'webkit']) {
        const browser = await playwright[browserType].launch();
        const context = await browser.newContext({viewport: null});
        const page = await context.newPage('https://whatismybrowser.com/');

        await page.screenshot({ path: `example-${browserType}.png` });
        await browser.close();
    }
})();
```

**Describe the bug**

According to [documentation](https://github.com/microsoft/playwright/blob/v0.10.0/docs/api.md#browsernewcontextoptions) **viewport** option can be `null`. And in this case I got error with Webkit: `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'width' of null` from here:
https://github.com/microsoft/playwright/blob/d397bb1bc34d11ccf3d2d38623e2a318f652ab4f/src/webkit/wkPage.ts#L493

So I suppose it should have some checks for **viewport**.

I can make PR to fix this. 
Thanks!

**Comment by pavelfeldman** [comment]
Thanks for the report! I'll use this opportunity to rearrange some of the logic and add a test for this one, hesitant asking for a PR here due to all this extra work.
