### ISSUE TITLE
[Feature] Add support for `sessionStorage` to `browserContext.storageState` and `browser.newContext`

### ISSUE THREAD

**Issue by mindplay-dk** [microsoft/playwright#8874]
The guide explains how to [reuse authentication state](https://playwright.dev/docs/auth/#reuse-authentication-state), but currently this feature only covers cookies and `localStorage`, neglecting `sessionStorage`.

* The [`browserContext.browserStorage`](https://playwright.dev/docs/api/class-browsercontext/#browser-context-storage-state) function should return a `sessionStorage` object in `origins`, similar to `localStorage`.

* The [`storageState` option for `browser.newContext`](https://playwright.dev/docs/api/class-browser#browser-new-context-option-storage-state) should support `sessionStorage` in `origins`, similar to `localStorage`.

Consider adding a `setBrowserStorage` method, which is where users are likely to look - this function will likely be needed internally anyhow, so this is probably mostly a matter of factoring the change to `browser.newContext` as a call to this function, so this functionality can also be used on-demand, independently of the `newContext` factory-function.

Consider also these [notes from @yuri-s](https://github.com/microsoft/playwright/issues/1129#issuecomment-803011431):

>  There are some questions like what to do if there are two pages from the same origin in the same context that have different sessionStorage states and whether sessionStorage for the current origin in the page is sufficient or you may need previous states too, otherwise it's doable.

> Having Page.sessionStorage()/setSessionStorage() could be more straightforward.

Consider refactoring to support `sessionStorage()` and `setSessionStorage()`, along with `localStorage` and `setLocalStorage`, making all of these features as granular as might be needed for any given use-case, e.g.:

* `sessionStorage` and `setSessionStorage`
* `localStorage` and `setLocalStorage`
* `cookies` and `setCookies`
* `browserStorage` and `setBrowserStorage` for the full browser storage state

(`setCookies` might be out of context for this feature request - but it would be nice and intuitive if every type of storage was consistently supported with full round-trip capability.)

**Comment by mochicode** [comment]
I would also love to see support for IndexedDB.

**Comment by peakcool** [comment]
yes, the support of indexedDB is very important to me

**Comment by matzeeable** [comment]
I just tried to modify the following lines with an additional `sessionStorage: sessionStorage.length` return value, unfortunately it is always `0`:

https://github.com/microsoft/playwright/blob/6a8d835145e2f4002ee00b67a80a1f70af956703/packages/playwright-core/src/server/browserContext.ts#L391-L401

After some time, I realised that the Session Storage is only valid in the current tab and that a new page is initialised by `newPage`. Is there any chance to get the Session Storage for all origins for a current tab?

**Comment by Wilhop** [comment]
I ran into an issue with logging into our application. The workflow was as follows:
1. Log in first and save cookies, localstorage and sessionstorage info into auth.json `await context.storageState({ path: 'state.json' });`
2. Each test uses the auth.json that is saved `test.use({ storageState: 'state.json' });`
3. For some reason the login was not working fully and I finally noticed that auth.json didn't include sessionStorage data.

It would be really useful to be able to save sessionStorage with context.storageState() if not by default, then with some parameters.

**Comment by svdHero** [comment]
I have a very similar issue / use case as @Wilhop.

The [Playwright documentation](https://playwright.dev/docs/auth#session-storage) states
> Rarely, [session storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) is used for storing information associated with the logged-in state. Session storage is specific to a particular domain and is not persisted across page loads.

However, [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-js) uses session storage for storing login information. That means that for any front-end SPA that authenticates against Azure AD or Azure B2C, login state cannot be reused as described [here](https://playwright.dev/docs/test-auth#multiple-signed-in-roles). It gets especially messy when trying to test multiple signed-in roles. For more details compare #17328 and https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5221.

This is a major draw-back when using Playwright for testing web applications in the Microsoft Azure ecosystem. Which is kind of sad, considering that Playwright is a test framework my Microsoft.

It would make life so much easier, if there was an easy way to export the session storage alongside the local storage in the JSON file's `origins` array.

**Comment by bheemreddy181** [comment]
> I have a very similar issue / use case as @Wilhop.
> 
> The [Playwright documentation](https://playwright.dev/docs/auth#session-storage) states
> 
> > Rarely, [session storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) is used for storing information associated with the logged-in state. Session storage is specific to a particular domain and is not persisted across page loads.
> 
> However, [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-js) uses session storage for storing login information. That means that for any front-end SPA that authenticates against Azure AD or Azure B2C, login state cannot be reused as described [here](https://playwright.dev/docs/test-auth#multiple-signed-in-roles). It gets especially messy when trying to test multiple signed-in roles. For more details compare #17328 and [AzureAD/microsoft-authentication-library-for-js#5221](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5221).
> 
> This is a major draw-back when using Playwright for testing web applications in the Microsoft Azure ecosystem. Which is kind of sad, considering that Playwright is a test framework my Microsoft.
> 
> It would make life so much easier, if there was an easy way to export the session storage alongside the local storage in the JSON file's `origins` array.

How did you fix this for the time being - I mean, how did you set the session storage ?

**Comment by svdHero** [comment]
I did not. My workaround is that before each test the login process has to be executed again, which is rather time consuming.

**Comment by bheemreddy181-zz** [comment]
> I did not. My workaround is that before each test the login process has to be executed again, which is rather time consuming.

If you are doing api login then it shouldn't be time consuming no ?

**Comment by svdHero** [comment]
It's not an API call. The test has to navigate to the B2C login form, fill in user name and password, authenticate against B2C/AAD and then return to the app's page. There are multiple http redirects involved in this process, which takes more time than just loading session data.

If that was not the case, the whole support of [reusing authentication state](https://playwright.dev/docs/auth#reuse-signed-in-state) would be pointless in the first place, I guess.

**Comment by bheemreddy181** [comment]
> It's not an API call. The test has to navigate to the B2C login form, fill in user name and password, authenticate against B2C/AAD and then return to the app's page. There are multiple http redirects involved in this process, which takes more time than just loading session data.
> 
> If that was not the case, the whole support of [reusing authentication state](https://playwright.dev/docs/auth#reuse-signed-in-state) would be pointless in the first place, I guess.

Why not use api to do the login like this https://medium.com/version-1/using-cypress-to-test-azure-active-directory-protected-spas-47d04f5add9

**Comment by svdHero** [comment]
Thanks, I will look into that workaround.

However, this seems to be a discussion about test design that is orthogonal to the issue at hand.

Obviously quite a few people here would appreciate session storage support in Playwright. And since Playwright features reusing login state in their official documentation, they should support that regardless of where the state is stored.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by lucastho** [comment]
Another vote to open this issue and implement sessionStorage in an easier to use way. Like many other folks, I'm testing a web app that uses sessionStorage to store a bearer token and other details for auth instead of a session cookie.

**Comment by LeonGeldsch** [comment]
Same here, I would also like this to be added as an option in the same way that IndexedDB was added.
