### ISSUE TITLE
Images not rendered correctly from local webserver

### ISSUE THREAD

**Issue by TheProgrammer21** [microsoft/playwright#8882]
Since this only applies for images from my local webserver and not for images from the web I am not sure whether this is a bug:

I try to generate a PDF document from HTML which includes an image, that needs to be provided locally. Hence I have a express webserver that staticly serves the files.

Webserver: 
```javascript
const app = express();
const port = 6666;
app.use(express.static("F:\\path_to_project\\pdf_export"));
app.listen(port);
```

The code for PDF generation:
```javascript
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.setContent(htmlString, { waitUntil: "load" });
  await page.pdf({ path: "F:\\Desktop\\file.pdf", printBackground: true });
  await browser.close();
```

The htmlString:
```html
<html xmlns="http://www.w3.org/1999/xhtml">
   <head></head>
   <body>
	<p>Some text...</p>
	<img src="http://localhost:6666/test.png" width="20px" height="20px" />
	<p>End text...</p>
   </body>
</html>
```

Instead the image being rendered correctly the pdf file shows a default icon for images that cannot be rendered: 
![image](https://user-images.githubusercontent.com/52009814/133108087-5ae35dc1-9aca-4d85-bd83-6777f1ec1aaa.png)

Do you have any ideas what I did wrong or how I could solve this issue?

**Comment by TheProgrammer21** [comment]
The reason is ERR_UNSAFE_PORT! The port 6666 is considered unsafe. A full list of unsafe ports can be seen here: https://superuser.com/questions/188058/which-ports-are-considered-unsafe-by-chrome

More detailed answer: 
The solution is, what I would actually classify as a bug. The port number 6666 is not a "trusted port" which leads to images not being loaded from the webserver. The strange thing is: The argument `--explicitly-allowed-ports=6666` is ignored in headless mode, at least for the usecase of generating pdfs and screenshots. I had the same problem with puppeteer which is why I initially came to playwright.
When I tried the `headless: false` option of puppeteer though, the images were loaded. So I think the option is just ignored in the headless mode, which I would classify as a bug.
However, there should be a way of loading images/files from a local webserver on a "non-trusted" port in any way. Is there another option or does it need to be implemented?

**Comment by mxschmitt** [comment]
Awesome! Closing since it's solved and thanks for posting the solution.
