### ISSUE TITLE
[Feature] Allow for globalSetup & globalTeardown CLI overrides

### ISSUE THREAD

**Issue by cipivanov** [microsoft/playwright#8883]
# Current Situation

Our project has a test suite that can be ran against two different environments. One environment requires obtaining an authentication token before it can be accessed and the test suite can be exectued. `globalSetup` was the perfect use case for the authentication scenario, and that is the one we went with. The only way to accomodate both cases it seems was to create two separate config files, one with and one without `globalSetup` and pass the appropriate one via `-c` flag. 

This worked great, but we ended up with some duplication and an extra file for a single config change.

# Potential Solution

The duplication can be avoided by removing the `-c` middleman and pass on the `globalSetup` override via a CLI flag. Adding `--global-setup` & `--global-teardown` flags to the `test` sub-command is a way to achieve that.

## Alternatives

Potential alternative is to have `project` level setup/teardown overrides, similar to `timeout`, where we can have both config wide and project specific values.

## PR

My go at it: https://github.com/microsoft/playwright/pull/8884.

**Comment by dgozman** [comment]
@cipivanov Thank you for the PR and an issue! Will something like env variable work for you as well?

```js
// playwright.config.js
module.exports = {
  globalSetup: process.env.GLOBAL_SETUP ? './global-setup' : undefined,
};
```

```bash
# Without global setup
npx playwright test
# With global setup
GLOBAL_SETUP=1 npx playwright test
```

**Comment by cipivanov** [comment]
@dgozman thanks for the suggestion! It should work, this approach did not even cross my mind.

The environment variable route also works great for situations where there are 2 or more distinct setup/teardown required, for those cases we can pass on the path directly I guess:
```shell
GLOBAL_SETUP=./path/to/your/setup GLOBAL_TEARDOWN=./path/to/your/teardown npx playwright test
```
```ts
// playwright.config.ts
const config: PlaywrightTestConfig = {
  globalSetup: process.env.GLOBAL_SETUP
    ? require.resolve(process.env.GLOBAL_SETUP)
    : undefined,
  globalTeardown: process.env.GLOBAL_TEARDOWN
    ? require.resolve(process.env.GLOBAL_TEARDOWN)
    : undefined,
};
```

Feel free to close the issue and the PR.
