### ISSUE TITLE
[Feature] List test steps before running

### ISSUE THREAD

**Issue by keevie** [microsoft/playwright#8888]
In a custom reporter, I'd like to be able to have access to the test steps in the onBegin callback -- currently it seems that there is no way to do this as the test results are not populated until the tests are actually run. 

A method similar to suite.allTests() would be ideal here.

**Comment by dgozman** [comment]
@keevie This is not possible - `test.step` is a function called during test execution, so steps are not available without actually running the test. Is there a reason you'd like them beforehand? Perhaps you'd better have multiple tests in this case, instead of multiple steps?

**Comment by keevie** [comment]
I think you're right, I do want multiple steps! I hadn't been able to get reusing the page object to work across tests in a serial execution mode, but with the help of new documentation I got it working.
