### ISSUE TITLE
[internal] create-playwright release blockers

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#8892]
- [x] `end-to-end` vs. ~~`integration`~~ naming clarification
- [x] `Add GitHub Actions workflow` -> `Add a GitHub Actions workflow`
- [x] Add description of the commands which get executed which get reflected in the logs
- [x] Add `test-results/` to the .gitignore?
- [x] compare with create-react-app about a better rootDir default. -> CRA creates new applications we get applied on existing ones mostly.
- [x] Maybe use something different then `npm run playwright-tests`?
- [x] better debug command --debug CLI flag on CLI https://github.com/microsoft/playwright/pull/8938
- [x] - --project= use double quotes.
- [x] dont warn if gitignore gets overriden.
- [x] point to the config and test file which got created
- [x] ~~ Add a gif how it can be used on NPM/main readme to show which features it supports~~
- [x] ~~Add a README in the `e2e` directory with more information.~~
- [x] evaluate better CLI examples
- [x] reduce projects
- [x] add more examples of use properties

**Comment by rwoll** [comment]
Some initial feedback:

* refuse to overwrite existing files. I (intentionally) had it overwrite an existing package.json but it should refuse to do this out of the box. This is P0/1 to me.
* take a directory as the first argument or prompt the user for the directory to init in. I didn't expect it to be CWD. (See create-react-app UX.)
* publish as `@playwright/create`. The official Playwright ecosystem has a bit of mixed naming (playwright, @playwright/test, playwright-chromium, create-playwright) making it hard to tell what exactly is official from  Playwright team (and there's new tools every week)
* include GitLab CI/CD option. We don't all use Microsoft's GitHub :)

Overall, awesome tool and will help folks getting started!

**Comment by mxschmitt** [comment]
> refuse to overwrite existing files. I (intentionally) had it overwrite an existing package.json but it should refuse to do this out of the box. This is P0/1 to me.

I tried to repro this, but was not able to. If a package.json exists in the directory, it will only update it with adding @playwright/test there and add playwright to the scripts section. I can prevent the modification of the scripts section if there is already an entry for Playwright.

> take a directory as the first argument or prompt the user for the directory to init in. I didn't expect it to be CWD. (See create-react-app UX.)

The difference between CRA and us is that in their case a new application gets always created. In our case it often gets added to an existing project, so having . as a default is IMO fine. Also I've added a log message in the beginning which will print the path where it gets invoked in (or path passed) so its more clear.

> publish as @playwright/create

Unfortunately then the main selling point of `npm init playwright` does not work anymore.

**Comment by rwoll** [comment]
> > refuse to overwrite existing files. I (intentionally) had it overwrite an existing package.json but it should refuse to do this out of the box. This is P0/1 to me.
> 
> 
> 
> I tried to repro this, but was not able to. If a package.json exists in the directory, it will only update it with adding @playwright/test there and add playwright to the scripts section. I can prevent the modification of the scripts section if there is already an entry for Playwright.
> 

Sounds good. I can't repro any more either, so may have bad state from the initial crashed run.

> 
> > take a directory as the first argument or prompt the user for the directory to init in. I didn't expect it to be CWD. (See create-react-app UX.)
> 
> 
> 
> The difference between CRA and us is that in their case a new application gets always created. In our case it often gets added to an existing project, so having . as a default is IMO fine. Also I've added a log message in the beginning which will print the path where it gets invoked in (or path passed) so its more clear.
> 

Sounds good. If more users are surprised by this, a compromise can be to prompt the user for confirmation if they call it in a dir without an existing project.

It littered my FS the first run.

> 
> > publish as @playwright/create
> 
> 
> 
> Unfortunately then the main selling point of `npm init playwright` does not work anymore.
> 
> 
> 
> 

You should be able to do:

```
npm init @playwright 
```

which translates to `npm exec @playwright/create`.

On first run, npm prompted me to confirm if I wanted to install `create-playwright` and from the name alone, I didn't know if it was official playwright tool or not.

**Comment by mxschmitt** [comment]
Closing for now since the first iteration of it is done. Next iteration is adding more examples.
