### ISSUE TITLE
[BUG] Missing target documentation

### ISSUE THREAD

**Issue by kblok** [microsoft/playwright#891]
**Describe the bug**

The [api.md](https://github.com/microsoft/playwright/blob/v0.10.0/docs/api.md) have [many references](https://github.com/microsoft/playwright/blob/v0.10.0/docs/api.md#event-targetchanged) to `Target` using the URL [https://github.com/microsoft/playwright/blob/v0.10.0/docs/api.md#class-target](https://github.com/microsoft/playwright/blob/v0.10.0/docs/api.md#class-target), but there is no documentation related to that class.

**Comment by dgozman** [comment]
`Target` was renamed to `ChromiumTarget`, and we've fixed the docs recently. Thank you for filing!
