### ISSUE TITLE
[BUG] when use chromium.launchPersistentContext, video recording for failure case doesn't work

### ISSUE THREAD

**Issue by kuladeep-journey** [microsoft/playwright#8913]
**Context:**
- Playwright Version: [1.14.1]
- Operating System: [Mac]
- Node.js version: [v12.16.1]
- Browser: [Chromium]
- Extra: [playwright-test]

**Code Snippet**
playwright.config.js:
const config = {
  maxFailures: 0,
  timeout: 30000,
  use: {
    channel: "chrome",
    headless: false,
    screenshot: "only-on-failure",
    video: "retain-on-failure",
  },
};

xyz.test.js:
const browser = chromium.launchPersistentContext(udd, options)
// navigate to any URL
// fail the test

```

**Describe the bug**
When launched browser with persistent context, video recording for test execution is not working. However screenshot still works.

**Comment by dgozman** [comment]
@kuladeep-journey This is because you call `chromium.launchPersistentContext()` and not use test fixtures. See [this comment](https://github.com/microsoft/playwright/issues/8428#issuecomment-906098812) for an explanation.

**Comment by kuladeep-journey** [comment]
Hi @dgozman ,
I have to launch Chrome in non incognito mode and thus I have to create browser using launchPersistentContext(). Thus if I use this API, how is it possible tot use the fixture? Even if I just add fixture in my test, the video recorded is on the fixture page but not the page created using persistent context.

Any possible solution for this? Or can we make the browser/page default mode to non incognito mode? I have issues in using incognito mode as my client application is restricted for certain features in incognito mode and If I use persistent context to create browser page, I am unable to record video as I am not using the fixture and adding just fixture will not workout as recorded video will be blank.

Please suggest any possible solution to my problem.
