### ISSUE TITLE
[BUG] Test fails abruptly with no given reason.

### ISSUE THREAD

**Issue by shtlrs** [microsoft/playwright#8916]
**Context:**
- Playwright Version: [1.14.1]
- Operating System: [Windows,]
- Node.js version: [14.17.2]
- Browser: [Chromium]

**Describe the bug**

In the web I'm testing, that's a toast that appears whenever an action is successful. 
I first discovered the behavior when I tried to hide the toast by clicking on it and waiting for it to be "detached".
The test would just cut off out of the blue  and I get a "page.click: Target page, context or browser has been closed"

So I commented out all the code that clicks on the toast and waits for it to go away and now it's happening at a different level.

Here's a trace of the test.
[trace.zip](https://github.com/microsoft/playwright/files/7162941/trace.zip)
And here's my config file.

I have also talked about it here:
https://playwright.slack.com/archives/CSUHZPVLM/p1631279492018400

```typescript
import { PlaywrightTestConfig } from '@playwright/test';
const physicalCpuCount = require('physical-cpu-count');

const config: PlaywrightTestConfig = {
    use: {
        browserName: 'chromium',
        // Make Chromium maximized
        // @ts-ignore
        trace: "retain-on-failure",
        // The view port (size) of the browser
        viewport: { width: 1920, height: 1080 },
        // The timeout for each page action, such as the clicks, checks, etc...
        actionTimeout: 250 * 1000,
        // Config upon launching the browser, start maximized or not, headed or headless, etc...
        launchOptions: {
            headless: true,
             //args: ["--start-maximized"]
        },
    },

    // Look for test files in the "tests" directory, relative to this configuration file
    testDir: 'tests',
    
    // Each test is given 4 minutes before it times out..
    // This is just for trial purposes now, will be changed once we start launching tests frequently.
    timeout: 8 * 60 * 1000,

    // Two retries for each test
    retries: 2  ,
    // Limit the number of workers on CI, use default locally
    workers: (physicalCpuCount * 2)-3,

    preserveOutput: 'always',

    reporter: "list",

    reportSlowTests: { max:50, threshold: 2*60*1000 },

    quiet: false,

};
export default config;
```

**Comment by dgozman** [comment]
@shtlrs I have looked at the trace, but I don't see any actions that had an error.

`Target page, context or browser has been closed` usually means that your test has finished and the page was closed, while some click as still running. Either you are missing `await` somewhere in your test, or the test did timeout. Unfortunately, we cannot help more without the test that reproduces the issue.

**Comment by shtlrs** [comment]
@dgozman I see.
I'll check more in the morning tomorrow.
What would you like me to give you precisely so that we can proceed with this in case it's a bug ?

**Comment by dgozman** [comment]
@shtlrs Ideally, a small repro that we can run locally and see the problem. Large test suite that sometimes fails with this error is less ideal 😄

**Comment by shtlrs** [comment]
@dgozman makes sense, I'll first check the forgotten await theory, it's starting to make sense from what I remember.
If it's not the case, I'll try to have a scenario we can reproduce

**Comment by shtlrs** [comment]
I'm closing the issue since it was eventually related to a design error on my end.
Big thanks to @dgozman For assisting me with it and thanks to all the playwright team for the constant help.
