### ISSUE TITLE
Trace does not capture network traffic

### ISSUE THREAD

**Issue by nssidhu** [microsoft/playwright#8917]
I am running into couple of issues
1) I do see Trace.zip being generated but it does not capture any network traffic.
2) I do have pause, it actually shows up the Playwright Inspector window but quickly closes automatically, i don't get chance to view the developer tools.
3) I have enabled to record the video, but it is not generating any video file.
4) Is is possible to create sub folders under the trace file for each run based on date and time ?

I am new to Playwright and would like to know what would be the correct settings ?

I do see trace being generated, but it does not capture any network traffic.
Also even though i have specified to record video even that is not being recorded

```
const config = {
    use: {
      headless: false,
      slowMo: 500,
      devtools: true,
      viewport: { width: 1280, height: 720 },
      video: 'on', //'on' , 'off'
      screenshot: 'on',  //'on' , 'off'
      recordVideo:{
        dir :"Video/"
      },
      trace: 'on',
    },
  };
  
  module.exports = config;
```

const { Browser, BrowserContext, Chromium, ElementHandle,test, expect,Page } = require('@playwright/test');

  test.describe.serial('use the same page', () => {
    /** @type {import('@playwright/test').Page} */
    let page;
    let browser;
    let context;

    test.beforeAll(async ({ browser }) => {

      page = await browser.newPage();

    });
  
  
    test('=> Load Login Page', async () => {
      await page.goto('https://localhost:5001/',  { waitUntil: "networkidle" });
      await expect(page).toHaveURL('https://localhost:5001/');
    });
  
    test('=> click Login Button', async () => {
     
      page.evaluate(() => console.clear());

      page.on('requestfailed', request => {
        console.log(request.url() + ' ' + request.failure().errorText);
        expect(false);
      });

      page.on('console', msg => {
        expect(msg.type()).not.toBe('error');
      });

      page.on('pageerror', exception => {
        console.log(`Uncaught exception: "${exception}"`);
      });

      

      await page.click('input:has-text("Login")',  { waitUntil: "networkidle" });
      await expect(page).toHaveURL('https://localhost:5001/LoginOrSignUp');
      await page.waitForLoadState('networkidle');
      await page.pause();
      
    });

    test.afterAll(async () => {
      await page.close();
      //await context.close();
      //await browser.close();
    });

  });

**Comment by dgozman** [comment]
@nssidhu Unfortunately, we cannot run your test locally because it uses some localhost server at `https://localhost:5001/`.

> * I do see Trace.zip being generated but it does not capture any network traffic.

Could you please attach the trace file for us to check this? Ideally, with a repro test.

> * I do have pause, it actually shows up the Playwright Inspector window but quickly closes automatically, i don't get chance to view the developer tools.

Perhaps your test times out? Try running like this: `npx playwright test --timeout=0`.

> * I have enabled to record the video, but it is not generating any video file.

Note that `recordVideo` in your config is ignored. If you'd like to specify custom video dir, take a look at `video` option: https://playwright.dev/docs/api/class-fixtures#fixtures-video.

> * Is is possible to create sub folders under the trace file for each run based on date and time ?

No, each test gets a single trace.

**Comment by dgozman** [comment]
Closing because we cannot repro. Feel free to open a new issue with a repro script that we could run locally.
