### ISSUE TITLE
[Feature] Allow to modify request.timing / PerformanceResourceTiming

### ISSUE THREAD

**Issue by bratao** [microsoft/playwright#8924]
I would like to modify request.timing / PerformanceResourceTiming.

I use .route with route.fulfil to serve a local webpage with a fake URL, but the loading time of the page is instantaneously. Even if I introduce a Sleep in the route handler, it shows in PerformanceResourceTiming as a Stalled request.

My use for this is that my Web app have a handler to send me the page load time. Mocking with playwright I get, for example, that my domainLookup, connectStart and connectEnd was 0.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
