### ISSUE TITLE
[BUG] List Reporter not working on CI when combined with allure-playwright

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#8931]
**Context:**
- Playwright Version: 1.14.1
- Operating System: MacOS
- Node.js version: 12.22
- Browser: All
- Extra: Runs test on Jenkins using Docker Playwright image

**Code Snippet**
Playwright Config file: `reporter: [['line'], ['allure-playwright']]` 

Jenkins Console log:
```javascript
[1A[2K
[1A[2K
[1A[2K
[1A[2K
[1A[2K
[1A[2K
[1A[2K
[1A[2K
[1A[2K
[1A[2K
[1A[2K
[1A[2K
[1A[2K
```

Compared to using `list` reporter without `allure-reporter`:
```
[2K[0G  ✓  [Desktop Chrome] › specs/
```

**Describe the bug**
I am trying to use both `list` and `allure-playwright` while running tests. It is working as expected locally but when running on CI (Jenkins), it doesn't print the test name which is the expected result of `list` reporter.

**Comment by pavelfeldman** [comment]
Is the problem with `line` reporter or `list` reporter? `line` reporter is not CI-friendly, uses ascii codes to move around the terminal...

**Comment by Nav-2d** [comment]
Actually, I wanted to use `list` reporter but my config had `line` reporter. My bad. It is working as expected in CI as well. Closing the issue.
