### ISSUE TITLE
[Question] How I can integrate native playwright test runner with Moon

### ISSUE THREAD

**Issue by AndreyMelnichenko** [microsoft/playwright#8944]
Conditions: 
**Node 14.17.6
TS: 4.3
Playwright: latest
Test runner: @playwright/test**
-------
My current solution based on **Docker** with headless browsers, it works fine, but I'd like scale my tests with **moon**, also I'm using config
```// playwright.config.ts
import { PlaywrightTestConfig, devices } from '@playwright/test';

const config: PlaywrightTestConfig = {
    retries: 2,
    workers: process.env.CI ? 6 : 2,
    timeout: 20000,
    use: {
        headless: true,
        baseURL: process.env.BASE_URL,
        locale: 'en-US',
        screenshot: 'only-on-failure',
        trace: 'retain-on-failure',
        viewport: {
            width: 1800,
            height: 1600,
        },
    },
    testDir: '.',
    reporter: [
        ['experimental-allure-playwright'],
        ['list'],
        ['./MyReporter.ts']
    ],
    projects: [
        {
            name: 'Desktop Chrome',
            use: {
                browserName: 'chromium',
                channel: 'chrome',
                screenshot: 'only-on-failure',
            },
        },
        {
            name: 'Desktop Safari',
            use: {
                browserName: 'webkit',
                screenshot: 'only-on-failure',
                viewport: { width: 1200, height: 750 },
            },
        },
        {
            name: 'Desktop Firefox',
            use: {
                browserName: 'firefox',
                screenshot: 'only-on-failure',
                viewport: { width: 1200, height: 750 },
            },
        },
        {
            name: 'Mobile Chrome',
            use: {
                ...devices['iPhone 12'],
                browserName: 'chromium',
                screenshot: 'only-on-failure',
                viewport: { width: 390, height: 669 },
            },
        },
        {
            name: 'Mobile Safari',
            use: {
                ...devices['iPhone 12'],
                screenshot: 'only-on-failure',
            },
        },
    ],
};
// eslint-disable-next-line import/no-default-export
export default config;
```

in my code I am using only [**page**] entity

```
 test(async ({ page }) => {
        await page.goto('/');
        mainPage = new MainPage(page);
        await mainPage.pageLoaded();
    });
```

so my page would be opened with configuration according yo config above
But if I want run tests in Moon, I should setup
browserType, browserName, browserContext (it may be difference for each browser)

```
browser = await [browserType].connect('ws://192.168.0.2:4444/playwright/${browserName}?headless=false', {
            timeout: 180000,
        });
        context = await browser.newContext({
            ...iPhone11,
        });
        page = await context.newPage();
```

How I can resolve it for all project?

**Comment by unlikelyzero** [comment]
@AndreyMelnichenko there is a similar ask here: https://github.com/microsoft/playwright/issues/8379#issuecomment-905612057

As more folks migrate away from selenium, I think we're going to see this same request in many ways.: "how can I integrate playwright-test into my existing browser test automation infrastructure?"

@JoelEinbinder should we make a net new feature request to generalize the request for browserType, browserName, browserContext in the playwright-test config?

**Comment by pavelfeldman** [comment]
You can override `browser` fixture to connect to Moon. Let me fold this into #8379.

**Comment by unlikelyzero** [comment]
@pavelfeldman, should we update #8379 to be more discoverable in the general case? Maybe a new title? A new issue?

**Comment by mxschmitt** [comment]
@unlikelyzero I renamed it. Yes you should upvote this issue then.

**Comment by AndreyMelnichenko** [comment]
@unlikelyzero  @pavelfeldman @mxschmitt 
It would be extremely helpfull to provide small example how I can override, I think my case it is ordinary for people who just migrate from old Selenium based frameworks to Playwright + native test runner + Moon
