### ISSUE TITLE
[BUG] Received String 'undefined' is not printed completely

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#8949]
**Context:**
- Playwright Version: 1.14.1
- Operating System: Mac
- Node.js version: 12.22
- Browser: All

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const { test, expect } = require("@playwright/test");

test('basic test', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  const title = page.locator('.navbar__inner .navb1ar__title'); // Intentionally fail the test
  await expect(title).toHaveText('Playwright');
});
```
Output Trace
```
Timeout of 15000ms exceeded.
Pending operations:
      - locator.textContent at node_modules/@playwright/test/lib/test/matchers/matchers.js:195:29
      - 
Error: expect(received).toHaveText(expected)

Expected string: "Buy"
Received string: undefi // not rendered completely
```

**Describe the bug**

If the locator is not found, the Received string doesn't print `undefined` completely

**Comment by dgozman** [comment]
I can reproduce this.

**Comment by mxschmitt** [comment]
Note: I also encountered this with various other thrown errors in the past.
