### ISSUE TITLE
[BUG] element id's with periods produce cryptic error

### ISSUE THREAD

**Issue by tquid** [microsoft/playwright#8953]
**Context:**
- Playwright Version: 1.13.1
- Operating System: Mac
- Node.js version: 14.17.4
- Browser: n/a
- Extra: [any specific details about your environment]

## System:
 - OS: macOS 11.6
 - Memory: 93.23 MB / 16.00 GB
## Binaries:
 - Node: 14.17.4 - ~/.nvm/versions/node/v14.17.4/bin/node
 - Yarn: 1.22.5 - ~/.yvm/shim/yarn
 - npm: 7.20.3 - /opt/homebrew/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**

```
  await page.type('#generalCalls.0.travel.start', '0')
  await page.type('#generalCalls.0.travel.end', '0')
```

**Describe the bug**

With the above code, the script dies with an error:

```
page.type: Unexpected token ".0" while parsing selector "#generalCalls.0.travel.start"
```

Add any other details about the problem here.

This can be worked around by double-escaping the periods, e.g. `#generalCalls\\.0\\.travel\\.start`. Periods are legal in CSS selector names, so it's puzzling that this happens, and it is not mentioned (as far as I can see) in the docs.

**Comment by dgozman** [comment]
This selector is not a valid CSS selector. You are probably looking for [something like this](https://stackoverflow.com/questions/12310090/css-selector-with-period-in-id) that also suggests backslash escaping.

This is the error I get in Chrome, and Playwright's error seems a tiny bit friendlier.
```js
> document.querySelector('#generalCalls.0.travel.start')
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#generalCalls.0.travel.start' is not a valid selector.
```

**Comment by tquid** [comment]
Thanks, it appears there is an unfortunate disagreement between what constitutes a legal _selector_ vs. a legal _identifier_. Do you have any idea why Playwright requires not one but two backslashes to properly escape the periods?

**Comment by dgozman** [comment]
> Do you have any idea why Playwright requires not one but two backslashes to properly escape the periods?

That's because you pass selector as a JavaScript string that requires escaping backslashes with backslashes 😄
