### ISSUE TITLE
[BUG] Filetype is not detected on setInputFiles

### ISSUE THREAD

**Issue by DavertMik** [microsoft/playwright#896]
**Context:**
- Playwright Version: 0.10.0
- Operating System: Linux

```js
await el.setInputFiles('avatar.jpg')
await page.click('input[type=submit]');
```

Expected: filetype to be `image/jpeg`
Actual file:

```
{
  name: 'avatar.jpg',
  type: 'application/octet-stream',
  tmp_name: '/tmp/phpe1S4NZ',
  error: 0,
  size: 5621
}
```
The file is not empty but the file type is not detected. There is a second parameter of filetype in `setInputFiles` where I can specify a filetype. However, I assume this is a bug because the same test passes for all other engines: WebDriver, Puppeteer, TestCafe

**Comment by pavelfeldman** [comment]
Thanks for the report, I'll take a look, should be an easy fix.
