### ISSUE TITLE
[BUG] Playwright keeps retrying/re-running a test if a step fails in beforeAll

### ISSUE THREAD

**Issue by TimeInvestor** [microsoft/playwright#8960]
**Context:**
- Playwright Version: 1.14.1
- Operating System: Windows 10
- Node.js version: v14.17.6
- Browser: Chromium
- Extra: n/a

## System:
 - OS: Windows 10 10.0.19042
 - Memory: 7.66 GB / 15.76 GB
## Binaries:
 - Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
 - npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
## Languages:
 - Bash: 5.0.17 - C:\Windows\system32\bash.EXE

**Code Snippet**
```javascript
import { test, expect, Page } from "@playwright/test";

test.describe.serial('Feature Test: ', () => {
  let page: Page;

  test.beforeAll(async ( { browser } ) => {
    page = await browser.newPage();
    await page.goto('https://playwright.dev/');
    await page.click('selector');
  });

  test.afterAll(async () => {
    await page.close();
  });

  test('basic test', async({ }) => {
    const title = page.locator('.navbar__inner .navbar__title');
    await expect(title).toHaveText('Playwright');
  });
  
});
```

**Describe the bug**
When step `await page.click('selector')` in **beforeAll** fails, Playwright reruns test again and again.
Even I set `--retries=1`, it still keeps retrying.

**Comment by dgozman** [comment]
Thank you for the issue! This was fixed in #8529, will be included in the next v1.15 release.
