### ISSUE TITLE
[BUG]During the return visit,Protocol error (DOM.describeNode): Cannot find context with specified id

### ISSUE THREAD

**Issue by JackMeng1209** [microsoft/playwright#8961]
在录制后，回放过程中提示报错Protocol error (DOM.describeNode): Cannot find context with specified id
![image](https://user-images.githubusercontent.com/90816495/133592487-5f42b5a5-2c7c-4887-95d6-8901c6e4a818.png)

**Comment by JackMeng1209** [comment]
发现生成的代码为：

**Comment by JackMeng1209** [comment]
发现生成的代码为：
  await Promise.all([
    page.waitForNavigation(/*{ url: 'https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&rsv_idx=1&tn=baidu&wd=%E6%88%91%E7%9A%84%E4%B8%96%E7%95%8C&fenlei=256&oq=%25E6%2588%2591%25E7%259A%2584%25E4%25B8%2596%25E7%2595%258C&rsv_pq=e01a4b2d0002dedf&rsv_t=0d98%2FcHKsE63ClL1%2Fg8qm9YjVxc1zE%2BKTT9IfH%2BYxYS0cT%2BUlMSiEULoJIk&rqlang=cn&rsv_enter=0&rsv_dl=tb&rsv_btype=t&bs=%E6%88%91%E7%9A%84%E4%B8%96%E7%95%8C&rsv_jmp=fail' }*/),
    page.click('text=百度一下')
  ]);
修改成:page.waitForNavigation(/*{ url: 'https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&rsv_idx=1&tn=baidu&wd=%E6%88%91%E7%9A%84%E4%B8%96%E7%95%8C&fenlei=256&oq=%25E6%2588%2591%25E7%259A%2584%25E4%25B8%2596%25E7%2595%258C&rsv_pq=e01a4b2d0002dedf&rsv_t=0d98%2FcHKsE63ClL1%2Fg8qm9YjVxc1zE%2BKTT9IfH%2BYxYS0cT%2BUlMSiEULoJIk&rqlang=cn&rsv_enter=0&rsv_dl=tb&rsv_btype=t&bs=%E6%88%91%E7%9A%84%E4%B8%96%E7%95%8C&rsv_jmp=fail' }*/),
await page.click('text=百度一下')
就可以正常执行了

**Comment by JackMeng1209** [comment]
发现生成的代码为：
  await Promise.all([
    page.waitForNavigation(/*{ url: 'https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&rsv_idx=1&tn=baidu&wd=%E6%88%91%E7%9A%84%E4%B8%96%E7%95%8C&fenlei=256&oq=%25E6%2588%2591%25E7%259A%2584%25E4%25B8%2596%25E7%2595%258C&rsv_pq=e01a4b2d0002dedf&rsv_t=0d98%2FcHKsE63ClL1%2Fg8qm9YjVxc1zE%2BKTT9IfH%2BYxYS0cT%2BUlMSiEULoJIk&rqlang=cn&rsv_enter=0&rsv_dl=tb&rsv_btype=t&bs=%E6%88%91%E7%9A%84%E4%B8%96%E7%95%8C&rsv_jmp=fail' }*/),
    page.click('text=百度一下')
  ]);
修改成:
await page.waitForNavigation(/*{ url: 'https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&rsv_idx=1&tn=baidu&wd=%E6%88%91%E7%9A%84%E4%B8%96%E7%95%8C&fenlei=256&oq=%25E6%2588%2591%25E7%259A%2584%25E4%25B8%2596%25E7%2595%258C&rsv_pq=e01a4b2d0002dedf&rsv_t=0d98%2FcHKsE63ClL1%2Fg8qm9YjVxc1zE%2BKTT9IfH%2BYxYS0cT%2BUlMSiEULoJIk&rqlang=cn&rsv_enter=0&rsv_dl=tb&rsv_btype=t&bs=%E6%88%91%E7%9A%84%E4%B8%96%E7%95%8C&rsv_jmp=fail' }*/),
await page.click('text=百度一下')
就可以正常执行了

**Comment by JackMeng1209** [comment]
Promise.all方法内会无序执行   没有加载完页面就跳转完就执行了点击 导致没有点击到

**Comment by dgozman** [comment]
Please tell us your OS, Playwright version and paste a repro script that we can run locally. Otherwise, we cannot do anything meaningful here.

**Comment by JackMeng1209** [comment]
OS：MacOS 10.16.6 Mojave
Playwright version: 1.14.1
NodeJs version:v14.17.4

`
const { test, expect } = require('@playwright/test');

test('test', async ({ page }) => {

  // Go to https://www.baidu.com/
  await page.goto('https://www.baidu.com/');

  // Click input[name="wd"]
  await page.click('input[name="wd"]');

  // Fill input[name="wd"]
  await page.fill('input[name="wd"]', '我的世界');

  // Click text=百度一下
  await Promise.all([
    page.waitForNavigation(/*{ url: 'https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&rsv_idx=1&tn=baidu&wd=%E6%88%91%E7%9A%84%E4%B8%96%E7%95%8C&fenlei=256&rsv_pq=a08c21bc0002bc79&rsv_t=574fsyp8epkWAkQH9XuXHhb12eHn0%2BsZaSnOeeghIkwVoSXGds4cwQxojZY&rqlang=cn&rsv_enter=0&rsv_dl=tb&rsv_sug3=17&rsv_sug1=10&rsv_sug7=100&rsv_btype=i&prefixsug=%25E6%2588%2591%25E7%259A%2584%25E4%25B8%2596%25E7%2595%258C&rsp=4&inputT=5279&rsv_sug4=6242&rsv_jmp=fail' }*/),
    page.click('text=百度一下')
  ]);

  // Click #page >> text=2
  await Promise.all([
    page.waitForNavigation(/*{ url: 'https://www.baidu.com/s?wd=%E6%88%91%E7%9A%84%E4%B8%96%E7%95%8C&pn=10&oq=%E6%88%91%E7%9A%84%E4%B8%96%E7%95%8C&ie=utf-8&usm=3&fenlei=256&rsv_idx=1&rsv_pq=ec875b7d0002e983&rsv_t=9d93rubBluIUb2eCN6wb4Cc3tddcAXmoXH31YEGIHYzuZKthN47R72GCHMA&bs=%E6%88%91%E7%9A%84%E4%B8%96%E7%95%8C&rsv_jmp=fail' }*/),
    page.click('#page >> text=2')
  ]);

  // Click text=下一页 >
  await Promise.all([
    page.waitForNavigation(/*{ url: 'https://www.baidu.com/s?wd=%E6%88%91%E7%9A%84%E4%B8%96%E7%95%8C&pn=20&oq=%E6%88%91%E7%9A%84%E4%B8%96%E7%95%8C&ie=utf-8&usm=3&fenlei=256&rsv_idx=1&rsv_pq=d62e94a400063b51&rsv_t=0fcdIhMo79pL1DMDl8Fqcqiid%2BaO3LsnzmRUHjre4Zd0LRowMqPIABtkuT4&rsv_page=1&bs=%E6%88%91%E7%9A%84%E4%B8%96%E7%95%8C&rsv_jmp=fail' }*/),
    page.click('text=下一页 >')
  ]);

  // Click text=百度一下
  await Promise.all([
    page.waitForNavigation(/*{ url: 'https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&rsv_idx=1&tn=baidu&wd=%E6%88%91%E7%9A%84%E4%B8%96%E7%95%8C&fenlei=256&oq=%25E6%2588%2591%25E7%259A%2584%25E4%25B8%2596%25E7%2595%258C&rsv_pq=953ff50b00030020&rsv_t=9a82q%2F9t3R7Gr8sTftTAcWkJ3YCdhNXmhkWRAdZoexVtIn%2Fxa6irrFScBM4&rqlang=cn&rsv_enter=0&rsv_dl=tb&rsv_btype=t&bs=%E6%88%91%E7%9A%84%E4%B8%96%E7%95%8C&rsv_jmp=fail' }*/),
    page.click('text=百度一下')
  ]);

  // Close page
  await page.close();

});
`
The above is the script content. thank you very much

**Comment by JackMeng1209** [comment]
There is a chance of success, but you need to try again and again.

**Comment by dgozman** [comment]
Thank you, I can repro this.

**Comment by JackMeng1209** [comment]
Thank you,Happy Mid-autumn Day！
