### ISSUE TITLE
[BUG] When running tests through azure pipeline, only the first attachment is displayed in the results

### ISSUE THREAD

**Issue by almazmr** [microsoft/playwright#8962]
**Context:**
- Playwright Version: [1.15.0-next-alpha-sep-16-2021
- Operating System: [Windows 10]
- Node.js version: [v16.1.0.]
- Browser: [All]
- Extra: [any specific details about your environment]

Hello! I **record** a **screenshot** and a **video** when the test fails and display it in **JUnit** format to display attachments in **Azure DevOps**

```javascript
import { PlaywrightTestConfig } from '@playwright/test'

const devConfig: PlaywrightTestConfig = {
  use: {
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    trace: 'on',
    baseURL: config.baseURL,
  }
}
export default devConfig
```

I end up with the following XML (JUnit)

```xml
...
</failure>
<system-out>
[[ATTACHMENT|test-results/Tests-failed-Упавший-тест-для-проверки-CI-6299/b86d5287702d513749d6229cfe7f153e.webm]]
</system-out>
<system-out>
[[ATTACHMENT|test-results/Tests-failed-Упавший-тест-для-проверки-CI-6299/trace.zip]]
</system-out>
<system-out>
[[ATTACHMENT|test-results/Tests-failed-Упавший-тест-для-проверки-CI-6299/test-failed-1.png]]
</system-out>
</testcase>
</testsuite>
...
```
When loading results in Azure DevOps, I see only the first attachment
![image](https://user-images.githubusercontent.com/36359177/133604154-56c00744-6b48-4eeb-92a6-cb6525d2d14a.png)

**I am assuming all attachments should be kept under one "system-out" then, it will display all attachments**

**Comment by Belisckner** [comment]
Maybe Azure supported only 1 `<system-out> ` tag?

As example,  there are 2 or more `<system-out></system-out>` tags in testcase in GitLab result in an error 
`JUnit data parsing failed: undefined method 'match' for`
(yes, in v1.15.0 junit report don't work in GitLab CI if there are 2 or more artifacts in  `<system-out></system-out> ` each testcase )
