### ISSUE TITLE
How can we access elements in nested iframes

### ISSUE THREAD

**Issue by LeanSaucecode** [microsoft/playwright#8967]
Good Day, is it possible to target nested iframes using playwright? 

For example I want to click on a button, but the button exist in an iframe within an iframe. Take the selector for example. 

iframe1 > iframe2 > #myButton 

How can I get the second iframe into context? 

Thanks in advance

**Comment by dgozman** [comment]
Use [`page.frame()`](https://playwright.dev/docs/next/api/class-page#page-frame) to get the correct frame, and then [`frame.click()`](https://playwright.dev/docs/next/api/class-frame#frame-click) in that frame.

If you use `npx playwright codegen`, it will generate sample code for you that handles iframes, so you'll get a working example.

Let us know if that helped.

**Comment by uchagani** [comment]
Find the first iframe, then find the second iframe, then find the element. If #7982 is implemented it’ll make piercing iframes the same as shadow doms (hopefully)

**Comment by dgozman** [comment]
Looks like the question has been answered.

**Comment by LeanSaucecode** [comment]
Sorry for my late response, have been quite busy. 

So the way I got it working was by following this [guide](https://thompson-jonm.medium.com/handling-iframes-using-python-and-playwright-da46d1c64196)

Ultimately you get the `children` of the `parent`, and by using a reducer you can iterate over a number list that contains the indexes of every child you want to access in every iframe. To get the children of the main_frame _`n`_ child frame, you need to overwrite the existing `childFrames`  list. 

```js
const numberList = [1,2,1]
const frameHandle = await ctx.page.$(selector)
const parent = await frameHandle.contentFrame()
let childFrames = parent.childFrames()
 
const frame = r.reduce((pageCtx, next) => {

            // Get the child using a number list index number
            pageCtx = r.prop(next - 1, childFrames)

            // If there is no children, return the parent variable
            if (r.anyOf([r.isNil(pageCtx), r.isEmpty(pageCtx)])) {
              return parent
            }
            // Get the childFrames of the current child frame
            childFrames = pageCtx.childFrames()

            return pageCtx
          },
          {},
          numberList
          )
```
