### ISSUE TITLE
[Question] Does the time for each test override default timeout for each action?

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#8973]
Scenario: Let's say I have a test to click button but I am failing it intentionally by providing wrong selector.

Config file:
```
timeout: 120000, // 2mins
use: {
    actionTimeout: 10000, // 10s
}
```
The outcome of the test is: `page.click: Timeout 10000ms exceeded.` (Works as expected)
___________________________________________________________________________________________________

If we remove the `actionTimeout` from the config file, the outcome of the test is: `Timeout of 120000ms exceeded.`

My expectation in this scenario is: The test should fail in 30s instead of 2mins since that is the default timeout for `page.click` action. Is this the correct expectation?

Thank you!

**Comment by dgozman** [comment]
> The test should fail in 30s instead of 2mins since that is the default timeout for page.click action. Is this the correct expectation?

No, Playwright Test works a bit differently. If you do not set `actionTimeout` value, it will disable default timeouts (set them to zero) so you'll get a test timeout instead.

**Comment by Nav-2d** [comment]
Thank you for clarifying @dgozman. Would be a good idea to add this in the [Configuration](https://playwright.dev/docs/test-configuration) section of Playwright Test?

**Comment by dgozman** [comment]
@Nav-2d Thank you for the fix!
