### ISSUE TITLE
[Question] How to translate intercept network code snippet from Cypress to Playwright?

### ISSUE THREAD

**Issue by sheeeng** [microsoft/playwright#8974]
How do I translate intercept network Cypress code snippet to Playwright?

```typescript
  beforeEach(() => {
    cy.visit('/');
    cy.intercept('POST', 'http://localhost:3000/secret', {
      body: { message: '75c3383d-a0d9-4296-8ca8-026cc2272271' },
    }).as('post');
  });

...
...

const mockGetResponse = (intercept) => {
  const body = JSON.parse(intercept.request.body);
  expect(body.expiration).to.equal(3600);
  expect(body.one_time).to.equal(true);
  cy.intercept(
    'GET',
    'http://localhost:3000/secret/75c3383d-a0d9-4296-8ca8-026cc2272271',
    {
      body: { message: body.message },
    },
  );
};
```

**Comment by pavelfeldman** [comment]
So the first snippet would be:

```ts
test.beforeEach(({ page }) => {
  // Intercept requests matching pattern, return given body
  await page.route('localhost:3000/secret', route => {
    route.fulfill({
      body: `{ message: '75c3383d-a0d9-4296-8ca8-026cc2272271' }`
    });
  });
  await page.goto('/');
});
```

The second one would be similar. Let me know if this helps or you need further help.

**Comment by sheeeng** [comment]
Is the second Cypress code snippet looks like the following Playwright code?

```typescript
const mockGetResponse = async ({intercept, page}) => {
  const body = JSON.parse(intercept.request.body);
  expect(body.expiration).toEqual(3600);
  expect(body.one_time).toEqual(true);
  // Intercept requests matching pattern, return given body
  await page.route('localhost:3000/secret/75c3383d-a0d9-4296-8ca8-026cc2272271', route => {
    route.fulfill({
      body: `{ message: '75c3383d-a0d9-4296-8ca8-026cc2272271' }`
    });
  });
  // Continue requests as GET.
  await page.route('**/*', route => route.continue({method: 'GET'}));
};
```

**Comment by sheeeng** [comment]
Also, what is the equivalent of `cy.wait('@post').then(mockGetResponse);` in Playwright?

**Comment by uchagani** [comment]
> Also, what is the equivalent of `cy.wait('@post').then(mockGetResponse);` in Playwright?

I could be wrong but In playwright the setting up of mocks and waiting for calls are separate.

so you would set up your mock via page.route/route.fulfill as explained above.

If you want to wait for it when the test is running you would use `page.waitForRequest`

however if you’ve mocked it I don’t see a good reason to wait for it as it will be near instantaneous and well within any element interaction that happens afterwards.

**Comment by dgozman** [comment]
Looks like this question has been answered. Please comment here if that's not the case.

**Comment by sheeeng** [comment]
My subsequent questions were not answered. Could you please reopen this issue?

**Comment by mxschmitt** [comment]
> Is the second Cypress code snippet looks like the following Playwright code?
> 
> ```ts
> const mockGetResponse = async ({intercept, page}) => {
>   const body = JSON.parse(intercept.request.body);
>   expect(body.expiration).toEqual(3600);
>   expect(body.one_time).toEqual(true);
>   // Intercept requests matching pattern, return given body
>   await page.route('localhost:3000/secret/75c3383d-a0d9-4296-8ca8-026cc2272271', route => {
>     route.fulfill({
>       body: `{ message: '75c3383d-a0d9-4296-8ca8-026cc2272271' }`
>     });
>   });
>   // Continue requests as GET.
>   await page.route('**/*', route => route.continue({method: 'GET'}));
> };
> ```

See here: https://playwright.dev/docs/api/class-page#page-wait-for-response

With this you have a [response instance](https://playwright.dev/docs/api/class-response) once the Promise.all resolves and can call e.g. `body()` on it.

But normally instead of waiting for requests which are finished you should wait for text / selectors to be available to not depend on the actual implementation of the application.

**Comment by sheeeng** [comment]
Sorry that I have ran out of time to complete this task.

Closing this issue for the time being.
