### ISSUE TITLE
[Question] How to wait for N childFrames to load on the mainPage

### ISSUE THREAD

**Issue by mkiddTempus** [microsoft/playwright#8978]
Apologies for not providing code that can replicate what I'm trying to do but I'll do my best given the repo I'm working with on this end.

My goal is that upon arrival to a page I can register all childFrames (need to wait on this due to dynamic nature of the frames) and have each childFrame report out they have finished loading.

The issue stems from the mainPage creating the childFrames as soon as I arrive at the url (I am waiting for a navigation after I click on a display grid page) which I accomplish like this:

`
    await Promise.all([
      page.waitForNavigation(),
      firstRow.hover(),
      firstRow.click()
    ]);
`

To grab the childFrames I have something like this: 

```
    const mainFrame = page.mainFrame();
    console.log(`childframes length: ${mainFrame.childFrames().length}`);
    const reportPreviewIframe = mainFrame.childFrames().filter((childFrame) => { return childFrame.name() === "test-preview-iframe" })[0];
```

It's at this point roughly that I would like to wait for each childframe to completely render. Any suggestions?

**Comment by dgozman** [comment]
You can do the following. It will wait for the "load" event in each frame if one hasn't fired already.
```js
await Promise.all(mainFrame.childFrames().map(frame => frame.waitForLoadState()));
```

That said, definition of "completely rendered" is different for each web page and heavily depends on async processing that page/frame does. If "load" event does not work, you'll have to figure out a signal that is good for your page, for example find the last network response that loads in the page and use `frame.waitForResponse()`.

Does that help?

**Comment by mkiddTempus** [comment]
I've dug a little deeper into the playwright api and found that all of my iframes will ultimately have a _loadStates of `{ 'domcontentloaded', 'load', 'networkidle' }`. That combined with an appropriate `page.pause()` I also discovered that for my use case if I do not appropriately wait my test will show 4 child frames when there should be five. So I have to wait for all the childFrames AND that each frame has reached `networkidle` or all three using some set comparison but I also have to poll the childFrames effectively to make sure all the childframes are there. 

Sorry I'm rambling having just discovered this as you commented. I'll use that Promise.all approach specific to networkidle. Helped immensely as well did logging our each frame. Learned a lot!
