### ISSUE TITLE
[Feature]: Use source-maps when available in test-runner for reporting and errors

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#8982]
See https://github.com/microsoft/playwright-vscode/issues/27

Users who are using a custom setup with the test-runner (feed transpiled files into the test-runner) currently can't use the extension. It should be possible that when there are source-map files, that they get used in the JSON reporter and in the error stack-traces.

**Comment by pavelfeldman** [comment]
Is there a repro? This should be working out of the box.

**Comment by pavelfeldman** [comment]
This should work: https://github.com/microsoft/playwright/blob/main/tests/playwright-test/reporter.spec.ts#L569
