### ISSUE TITLE
[BUG] Referer header is duplicated if set via setExtraHTTPHeaders

### ISSUE THREAD

**Issue by yury-s** [microsoft/playwright#8999]
The following test fails in Chromium:
```js
  const response = await page.goto(server.EMPTY_PAGE);
  expect(response.ok()).toBe(true);
  expect(response.request().headers()['referer']).toBe(server.EMPTY_PAGE);
```

The headers look like this:
```json
[
  {
    "name": "Upgrade-Insecure-Requests",
    "value": "1"
  },
  {
    "name": "User-Agent",
    "value": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/96.0.4645.0 Safari/537.36"
  },
  {
    "name": "referer",
    "value": "http://localhost:8907/empty.html"
  },
  {
    "name": "Referer",
    "value": "http://localhost:8907/empty.html"
  }
]
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
