### ISSUE TITLE
[Feature] Increase page load event timeout in codegen

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#9001]
Command: `npx playwright codegen https://my-website-url.com/slugID`

```
[codegen: Timeout 10000ms exceeded.
=========================== logs ===========================
navigating to "https://my-website-url.com/slugID", waiting until "load"
============================================================
] {
  name: 'TimeoutError'
}
```

Request: Is it possible to increase the `pageload` timeout when recording scripts?

**Comment by mxschmitt** [comment]
You can pass a custom timeout via the `--timeout` CLI parameter. Example:

```
npx playwright codegen --timeout=60000 https://my-website-url.com/slugID
```

Let us know if this works for you.

**Comment by Nav-2d** [comment]
Thank you Max! The solution works for me. Closing the issue.
