### ISSUE TITLE
how to automation translate webpage

### ISSUE THREAD

**Issue by kakaok** [microsoft/playwright#9003]
i want to automation translate webpage by playwright-python,but don‘t know how to settings from the API

**Comment by dgozman** [comment]
Playwright does not support translating web pages.

**Comment by kakaok** [comment]
does Playwright  can load chrome plugins like selenium  
chrome_options = Options()
prefs = {
        "translate": {"enabled": "true"},
        "translate_whitelists": {"zh-CN": "en"}
    }
chrome_options.add_argument(
        "--user-data-dir="+r"C:/Users/Administrator/AppData/Local/Google/Chrome/User Data/")
chrome_options.add_experimental_option("prefs", prefs)

**Comment by mxschmitt** [comment]
https://playwright.dev/python/docs/chrome-extensions/
