### ISSUE TITLE
[Feature] Unnamed snapshots

### ISSUE THREAD

**Issue by schickling** [microsoft/playwright#9007]
Currently snapshots require a `name` like the following:

```ts
    expect(something).toMatchSnapshot({ name: 'some name' })
```

It would be great if the `name` and the entire `toMatchSnapshot` argument was optional like this:

```ts
    expect(something).toMatchSnapshot()
```

**Comment by sidharthv96** [comment]
Absolutely, if it follows the jest pattern and generates a dynamic name, it'll save us from having to name one more thing :)
