### ISSUE TITLE
[Question] data-test-id partial match

### ISSUE THREAD

**Issue by TroutZen** [microsoft/playwright#9009]
Is there a way to partial match on `data-test-id`? It appears that when I use a selector like `data-test-id=my-test-id` it fails to select on an element that looks like `data-test-id=my-test-id my-other-test-id`. I assumed that it would behave like `text=` where you can either provide quotes for exactness or leave them off for partial matching.

Thanks!

**Comment by ltsuda** [comment]
I think partial matches can be done like this `[data-test-id~=“my-test-id”] ` to find any element that contains `my-test-id`. You can use `[data-test-id|="some value"]` to match the first word, in this case, any `data-test-id` that starts with `some`. Or  `[data-test-id^="item"]` to match the things that starts with `item`, like `item12345`.

I hope this helps.

**Comment by mxschmitt** [comment]
Closing since it seems answered. Feel free to create a new issue if you still have questions.
