### ISSUE TITLE
allure-results are not overwritten instead it is cascaded

### ISSUE THREAD

**Issue by akshayp7** [microsoft/playwright#9011]
Use Case : If I execute TC01 for the first time, after completing execution I execute TC02
Now when I check for allure-results folder, instead of generating fresh results previous results are also cascaded so instead of getting report for only TC02 I am getting combined report for TC 01 and TC 02

**Comment by pavelfeldman** [comment]
Do you have experience using Allure with other frameworks? I know there is --clean option that you can use while generating report, but I'm not sure what your workflow is.

**Comment by vsravuri** [comment]
When we run this command 

```javascript
allure generate ./allure-result --clean && allure open ./allure-report
```

**--clean** will clear the **allure-report** folder before generating new report, before next test run if **allure-result** folder is not cleaned up manually, then the new report may won't show you the correct report.

Option:
1. Clean up ALLURE_RESULTS_DIR folder before running playwright test
2. Append timestamp to ALLURE_RESULTS_DIR directory name so that each test results will have unique allure-result folder

**Comment by akshayp7** [comment]
Have tried above command but still all the Jason files in Allure-results remain

**Comment by akshayp7** [comment]
@vsra

> When we run this command
> 
> ```js
> allure generate ./allure-result --clean && allure open ./allure-report
> ```
> 
> **--clean** will clear the **allure-report** folder before generating new report, before next test run if **allure-result** folder is not cleaned up manually, then the new report won't show you the correct report.
> 
> Option:
> 
> 1. Clean up ALLURE_RESULTS_DIR folder before running playwright test
> 2. Append timestamp to ALLURE_RESULTS_DIR directory name so that each test results will have unique allure-result folder

Exactly. My observation, there is no command to clear allure-results before execution right. We have to do it manually or via some code am I correct..

**Comment by MindaugasMateika** [comment]
I believe the behavior is the same with other frameworks as well (I use allure with appium). What I'm doing with Playwright is using rimraf library and global setup to delete allure-results before tests execution.
```
const rimraf = require('rimraf')

async function globalSetup(): Promise<void> {

  await new Promise(resolve => {
    rimraf('./allure-results', resolve)
  })
}

export default globalSetup
```

**Comment by akshayp7** [comment]
> I believe the behavior is the same with other frameworks as well (I use allure with appium). What I'm doing with Playwright is using rimraf library and[ global setup](https://playwright.dev/docs/test-advanced#global-setup-and-teardown) to delete allure-results before tests execution.
> 
> ```
> const rimraf = require('rimraf')
> 
> async function globalSetup(): Promise<void> {
> 
>   await new Promise(resolve => {
>     rimraf('./allure-results', resolve)
>   })
> }
> 
> export default globalSetup
> ```

Thank you This is exactly what I required
