### ISSUE TITLE
[Question] Cannot run test in docker image mcr.micRosoft.com/playwright:focal when using Playwright Test Runner

### ISSUE THREAD

**Issue by KevinLuc95** [microsoft/playwright#9012]
I've converted my source code from Jest Test Runner to Playwright Test Runner, but when I run it in docker mcr.micRosoft.com/playwright:focal, I'm facing the issue:
`19:13:29      browserType.launch: Chromium distribution 'chrome' is not found at /opt/google/chrome/chrome
19:13:29      Run "npx playwright install chrome"`
It works well with Jest Runner

**Comment by akshayp7** [comment]
Give below command in your docket file. You have to install chrome in your container 
RUN npx playwright install chrome

**Comment by KevinLuc95** [comment]
I've fixed this issue by remote `channel: chrome` in playwright.config.ts

**Comment by mxschmitt** [comment]
Closing since it seems answered
