### ISSUE TITLE
[BUG] Trace -> retain-on-failure doesn't delete the resources and trace file after zip file is created at the end of the test

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#9017]
**Context:**
- Playwright Version: 1.14.1
- Operating System:  Mac
- Node.js version: 16.9.1
- Browser: Chromium
- Extra: Issue is also noticed in playwright@next

**Code Snippet**

```javascript
/** @type {import('@playwright/test').PlaywrightTestConfig<{ version: string }>} */
    const config = {
        workers: 1,
        globalTimeout: 0,
        globalSetup: require.resolve('./pw-global.js'),
        globalTeardown: require.resolve('./pw-global-teardown.js'),
        reporter: [['junit', {outputFile: process.env.PLAYWRIGHT_JUNIT_OUTPUT_NAME}],
            ['list'],
            ['json', {outputFile: process.env.PLAYWRIGHT_JSON_OUTPUT_NAME}],
            ['allure-playwright']
        ],
        projects: [{
            name: 'Chromium',
            testDir: './smk-test',
            testMatch: 'test1.spec.js',
            outputDir: process.env.pwRptDir,
            timeout: 0,
            retries: 0,
            use: {
                browserName: 'chromium',
                channel: 'chrome',
                headless: false,
                viewport: {width: 1700, height: 800},
                ignoreHTTPSErrors: true,
                screenshot: 'off',
                video: 'on',
                trace: 'retain-on-failure',
                launchOptions: {
                    slowMo: 500,
                    timeout: 0,
                    tracesDir: process.env.pwRptDir,
                },
            }
        }]

    };
    module.exports = config;
```

```javascript
// test1.spec.js
const { expect,test} = require('@playwright/test');
test('basic test', async ({ page,context }) => {
    await page.goto('https://playwright.dev/',{waitUntil: 'networkidle'});
    const title = await page.locator('.navbar__inner .navbar__title');
    await expect(title).toHaveText('Playwright');
    await context.close();
});
```

**Describe the bug**
Even though **trace: 'retain-on-failure'** doesn't create a zip file if the test case didn't fail, the source files (resources folder and trace file) are not deleted at the end of the test.

If the test succeeds, i would expect the trace source files to be deleted. These files are retained even if i set **preserveOutput: 'failures-only',** even though the test case pass.

![Screen Shot 2021-09-19 at 3 53 00 PM](https://user-images.githubusercontent.com/22808594/133945573-7d1a035a-3fbe-4172-9ec8-dc799ba3dccf.png)

Kindly let me know if this is a bug or i need to manually clear the trace files.

**Comment by mxschmitt** [comment]
Hi, if you use screenshot/video/tracing options from the test-runner with e.g. `retain-on-failure`, it does store the artifacts inside the output directory of the test-runner which is by default `test-results/` see [here](https://playwright.dev/docs/api/class-testconfig#test-config-output-dir).

In your scenario you should drop the custom `tracesDir` option via the `launchOptions` and then the traces should be placed inside the `test-results/` directory.

Let us know if this works for you, thanks!

**Comment by vsravuri** [comment]
Thanks @mxschmitt 

It works!
