### ISSUE TITLE
[Question] Enable / disable reuse of authentication state in serial test suite?

### ISSUE THREAD

**Issue by sheeeng** [microsoft/playwright#9018]
Is it possible to enable / disable reuse of authentication state in the same test suite?

```typescript
test.describe.serial('playwright', () => {

  test('check without authentication state', async ({ page }) => {
  });
  
  test.use({ storageState: storageStateFilePath });
  test('check with authentication state', async ({ page }) => {
  });

  test.use({ storageState: "" }); // TODO: Can we disable resuse of authentication state here?
  test('check without authentication state again', async ({ page }) => {
  });

  test.use({ storageState: storageStateFilePath });
  test('check with authentication state again', async ({ page }) => {
  });


});
```

**Comment by mxschmitt** [comment]
You can split it up with multiple describe blocks, inside the describe blocks you can use different test.use() blocks which can reflect a different storageState. Would this work for you?

**Comment by sheeeng** [comment]
Thank  you for the suggestion, Max!

Do you have a code snippet that describe what you have suggested?

Is it possible that we "empty" a storage state in a same or different block?

**Comment by mxschmitt** [comment]
https://playwright.dev/docs/test-configuration#local-configuration

This should be possible yes I think.

**Comment by sheeeng** [comment]
Thanks you for the information, Max! It works on my machine. 😄 

```typescript
test.describe.serial('anonymous access', () => {
  test.use({ storageState: 'empty_storage_state.json' });
  });
});
```
