### ISSUE TITLE
[Question] Copy To Clipboard in Playwright

### ISSUE THREAD

**Issue by rthi-rajan** [microsoft/playwright#9019]
I am automating an openfin application
I want to copy come content to clipboard.
I tried to use the WriteText method of Clipboard API (I saw it is supported in Chrome https://caniuse.com/?search=clipboard)
But it giving me an error

Below is my code
runtimeCDPConnection = await chromium.connectOverCDP({ endpointURL: '<URL>' })

        allContexts = runtimeCDPConnection.contexts()
        runtimeContext = allContexts[0];
      
        runtimeContext.grantPermissions(['clipboard-read', 'clipboard-write'])
        await runtimeContext.writeText("Abcd")
        var abc = await runtimeContext.readText()
        console.log(abc)

I am getting error
runtimeContext.writeText is not a function

page = await runtimeContext.pages()[0]
        await page.writeText("Abcd")
        var abc = await page.readText()
        console.log(abc)

Again getting error 
TypeError: page.writeText is not a function

Am I using it wrong? Could someone guide me to add content to clipboard

**Comment by mxschmitt** [comment]
We have a feature request for adding copy/paste clipboard support across all the browsers: https://github.com/microsoft/playwright/issues/8114. Please upvote it there.

Regarding your example, there is no method called writeText in Playwright yet.

**Comment by mxschmitt** [comment]
This is not yet possible. Merging into https://github.com/microsoft/playwright/issues/8114
