### ISSUE TITLE
[Feature] Run through all assertions in the test before failing

### ISSUE THREAD

**Issue by A-ZC-Lau** [microsoft/playwright#9022]
# Scenario

Right now, if even a single assertion in a test fails, none of the other assertions will be run.

# Proposal

It would be great if it was possible to have all assertions in the test to run and then respond back with the actual assertions that failed. For example, as of now, if you have 5 assertions in a test, and the 2nd one fails, you are left in the dark of the remaining 3. If you fix your 2nd test, and re-run, and find that the 3rd assertion fails, it feels it would have been better if we could have known beforehand, so we can fix multiple failures at the same time.

Example:

```javascript
test.describe.serial("serial", () => {
    let page : Page;
    test.beforeAll(async ({browser}) => {
        page = await browser.newPage();
        await page.goto("https://getbootstrap.com/docs/5.1/components/modal/");
    });

    test("On modal page", async function () {
        const titlePage = await page.title();
        expect(titlePage).toContain("Modal");

        const idText = await page.locator("#content").innerText();
        expect(idText).toBe("Modall"); // this will fail and exist

        const worksText = await page.locator("#how-it-works").innerText();
        expect(worksText).toBe("How it works"); // this will pass, but we don't know due to previous assertion
    });
});
```

# Ideas

This might be difficult or impossible with the current `test` architecture, which is similar to other testing frameworks.

Since Playwright already has the notion of actions, perhaps a different kind of testing style, e.g. `action -> consequence/assertion` could be thought about.

An idea might be have the new equivalent of `test` function as a describe block (let's call it `When` for now), and then be able to queue up assertions (let's call it `Then` for now), with maybe the ability to fill in the title like `it.each` from Jest.

For example:

```javascript
When("I click on the modal button", ({ action, Then }) => {
	action(async ({ page }) => {
		await page.click("#modal");
	});

	Then("Title")("The title is '%s'", async ({ expect, page }, expectedText) => {
		const title = await page.locator("#title").innerText();
		expect(title).toBe(expectedText);
	});
	Then("Some long string")("The body has text '%s'", async ({ expect, page }, expectedText) => {
		const title = await page.locator("#body").innerText();
		expect(title).toBe(expectedTitle);
	});
	Then("Ending text")("The footer has text '%s'", async ({ expect, page }, expectedText) => {
		const title = await page.locator("#footer").innerText();
		expect(title).toBe(expectedTitle);
	});
});
```

A notable scenario where this could be particularly useful is after filling in a form and you want to ensure that the page after has all of the correct details.

# Note

I am not advocating for a BDD/cucumber style, as I actually hate writing steps to match cucumber, as it's generally unintuitive in the end, but would like to know the results of all of my assertions without necessitating that all previous assertions have passed.

**Comment by mxschmitt** [comment]
This sounds similar to the proposed "soft expect statements" feature request: https://github.com/microsoft/playwright/issues/7819

**Comment by A-ZC-Lau** [comment]
@mxschmitt Yeah, I think it's similar.

**Comment by mxschmitt** [comment]
Merging then 👍

**Comment by amrsalem1** [comment]
is it implemented yet ?

**Comment by mxschmitt** [comment]
No, see here for the current status: https://github.com/microsoft/playwright/issues/7819
