### ISSUE TITLE
[Feature] Allow exporting trace-viewer pages as static website bundles (e.g. for deployment to S3 etc)

### ISSUE THREAD

**Issue by neil-morrison44** [microsoft/playwright#9026]
Similar to https://github.com/microsoft/playwright/issues/4967 but I want to fully control the trace viewer instance.

During CI runs if there's a failure & a trace has been taken of it I'd like to call trace-viewer in a manner in which it exports a static html file (& JS, CSS, images, etc) I could dump on to a static web host.

I'd then create a link to the trace-viewer and put it in the comments on the PR run (or whatever) & could visit the site to see the trace. ( similar to https://github.com/microsoft/playwright/issues/8284, would also allow more people to see traces like https://github.com/microsoft/playwright/issues/8481 )

**Comment by mxschmitt** [comment]
Lets merged it into https://github.com/microsoft/playwright/issues/4967 which is similar.

**Comment by neil-morrison44** [comment]
> Lets merged it into https://github.com/microsoft/playwright/issues/4967 which is similar. 

It's similar, but that issue requests a web app hosted by Playwright that can import & view any trace.

What I'm asking for is a way to bundle a _single_ trace as a standalone website, which to me was distinct enough to be its own feature request (mostly since if Playwright implemented the other feature it wouldn't help my ideal CI flow at all)
