### ISSUE TITLE
[Bug]: Timeout error when the page is already loaded

### ISSUE THREAD

**Issue by niewiemczego** [microsoft/playwright#9028]
### Playwright version

1.14.0

### Operating system

Windows

### What browsers are you seeing the problem on?

Firefox

### Other information

python 3.8.8

### What happened? / Describe the bug

Always, but only the first time when the program does page.goto, playwright despite correctly loading the page throw timeout error. When I will do while loop with lets say 5 tries then second try will work without any issue. So the first try always throw for some reason timeout error.

### Code snippet to reproduce your bug

```shell
from playwright.sync_api import sync_playwright

def login(email:str, password:str) -> None:
    base = "https://www.nike.com/ca/launch/t/womens-air-max-furyosa-night-green"
    with sync_playwright() as playwright:
        browser = playwright.firefox.launch(headless=False)
        page = browser.new_page()
        try:
            page.goto(base, timeout=20000)
        except Exception as e:
            print("Error: " + str(e))
        page.click("//button[@data-qa='accept-cookies']")
        page.click("text=Join / Log In") # 
        page.fill(".emailAddress input", str(email))
        page.fill(".nike-unite-password-input input", str(password))
        page.click(".loginSubmit input")
        browser.close()


if __name__ == "__main__":
    login("email","password")
```

**Comment by liuxingbaoyu** [comment]
Fixed in https://github.com/microsoft/playwright/pull/13340

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
