### ISSUE TITLE
[BUG] No redirect is allowed to the custom error page if intercept is successful

### ISSUE THREAD

**Issue by mrQanderson** [microsoft/playwright#9032]
- Playwright Version: 1.13.1
- Operating System: Mac
- Python version: 3.8
- Browser: All

Python

def test_intercept_404():
	page.goto("https://domain.com")
        page.route("**/sign-in", lambda route: route.fulfill(status=404))
	page.goto("https://domain.com/sign-in")

I returned browser 404 as needed.
I’ve got browser error, but have to see redirect to the custom site page 404 
Playwright throw an error because of waiting. 

<img width="1196" alt="Screenshot 2021-09-18 at 23 41 18" src="https://user-images.githubusercontent.com/66297758/134056396-edbc05ea-2386-4fc9-a281-1ec0590bb90a.png">
<img width="1269" alt="Screenshot 2021-09-18 at 21 48 50" src="https://user-images.githubusercontent.com/66297758/134056398-5a68d473-2841-45c0-9bfb-48ad4f3d7ce9.png">

**Comment by mxschmitt** [comment]
You can set a custom body, then Chromium will display the 404 response. 

`page.route("**/sign-in", lambda route: route.fulfill(status=404, body="Not found"))`

What do you mean with the following?

> but have to see redirect to the custom site page 404

**Comment by mrQanderson** [comment]
such kind of page
<img width="832" alt="Screenshot 2021-09-21 at 10 50 06 3" src="https://user-images.githubusercontent.com/66297758/134133148-c815df1d-5412-41ac-a873-58ed91a7e6e2.png">
s

**Comment by mxschmitt** [comment]
This page is a page created by their backend server and contains custom HTML / or is created by their SPA (Single Page Application).

Closing since this is not about Playwright.

**Comment by mrQanderson** [comment]
I got redirect to this 404 page without playwright and everything is ok

But when I use interception with route.fulfill and application thrown 404 status code -> playwright closed the browser
<img width="943" alt="Screenshot 2021-09-21 at 11 43 52" src="https://user-images.githubusercontent.com/66297758/134146438-15e8f420-c925-43dc-9376-be47ced60054.png">

It wait for the url with navigation -> default 404 page shown up -> browser closed

If it's not about Playwrighe, please explain the syntax, example - how can I allow browser to have a redirect to custom page after 404  interception

**Comment by mxschmitt** [comment]
Let me explain. So page.route does intercept the request which is coming from the browser to the internet in your case disney.com You instruct it to return only http status code 404 which means "not found". So an empty http response gets sent back to the browser without any body. Thats the reason why there is an error happening in Chromium or when using body="Not found" only the text "Not found" gets displayed.

What exact scenario are you trying to test?

**Comment by mrQanderson** [comment]
I try to test scenario that:
1) custom error pages (403, 404, 500) are exist 
2) 404 page is shown up after non-exist on site page is followed

Example:
1) Follow to url https:\\disney.com\non-exist-page
2) 404 page with Disney 404 is shown up
3) assert page.title with 404 or numbers on page 404 == 404

**Comment by mxschmitt** [comment]
Gotcha, then in this case you can't test it by mocking the endpoint (using page.route) - since the http request would never reach the backend server. In this case the actual backend server needs to respond with these custom error pages.

For 404 its probably easy as you wrote (just navigate to a non-existent path) and for 403 and 500 you need to ask the backend server team for assistance.

**Comment by mrQanderson** [comment]
You won, thank you ) As I understood mock such pages is not a good solution to test them.
