### ISSUE TITLE
[BUG] Role attributes not being implicitly resolved

### ISSUE THREAD

**Issue by nathanhannig** [microsoft/playwright#9033]
**Context:**
- Playwright Version: 1.14.1
- Operating System: Windows
- Node.js version: 16.1
- Browser: Chromium
- Extra: Using Browser Library of Robot Framework. https://marketsquare.github.io/robotframework-browser/Browser.html

**Describe the bug**

I am using Robot Framework library called Browser Library which uses Playwright under the hood. It uses same selector strategy so I would imagine this bug is related to Playwright as the selector should be passed on to Playwright to find the element.

I have a form with a button that I am trying to locate and click. I would like to use the role attribute to find the element. 

W3 standards say that the roles for this html should be implicit; however, Playwright is not finding the elements. My assumption is that Playwright only finds the role if it is explicitly provided.

The first selector strategy works.
```css=#root >> css=form >> css=button```

The second selector strategy does not work.
```css=#root >> css=[role=form] >> css=[role=button]```

Example HTML
```html
<div id="root">
  <form>
    <button>Submit</button>
  </form>
</div>
```

Please let me know if I am doing anything wrong. I think this would be necessary you want all implicit and explicate roles to be referenced in searching through selectors.

**Comment by ltsuda** [comment]
I'm not sure, as I just research myself about using `role`, but I think in this example you can't use CSS selector `role` as the HTML is using native tags `<button>` and `<form>`. So you can find the button with `#root form button` or directly with `page.click('button')` or by text `page.click('text=Submit')`. The last two examples was from the Javascript framework.

I think `role` is to identify other elements like `div` or `a` as button using the `role` attribute as shown in the link below. Please, take a look at the Print and Mute examples.

https://www.w3.org/TR/wai-aria-practices/examples/button/button.html

If someone more experienced to explain correctly about this, feel free to comment. I saw the issue and read a little to understand too.

**Comment by dgozman** [comment]
@nathanhannig We follow CSS selectors spec, and `[role=button]` does not match `button`. You can do `#root >> css=button,[role=button]` if you are not sure whether you have a native button or a button-like element.

Alternatively, it could make sense to introduce some kind of aria selector that will work as you propose. Should we change this into a feature request for the aria selector engine?

**Comment by nathanhannig** [comment]
> Alternatively, it could make sense to introduce some kind of aria selector that will work as you propose. Should we change this into a feature request for the aria selector engine?

Definitely not a bad idea. Based on Playwright best practices and even other libraries (like React Testing Library); writing tests based on how a user would observe the page is best and aria selector engine I think would make good sense.

Here is a pretty good write up about the browser implicitly adding roles to elements without the role attribute.
https://testing-library.com/docs/queries/byrole/

**Comment by maslade** [comment]
I second that this library would benefit from a first-class selector for ARIA roles that can handle implicit or explicit roles. This is in line with Playwright's (and other frameworks') best practices and how browsers work. The example given in the Playwright documentation for selecting by role is not actually selecting by role but by element name.

```ts
await page.locator('css=nav >> text=Login').click();
```

When a user with accessibility tooling is navigating a page, they aren't concerned with whether a button is a `<button>` or a `<div aria-role="button">`. They care whether or not its role is "button", which their browser determines based on the `aria-role` attribute, if present, and the implicit role for that element otherwise. The purpose of these attributes is to abstract that away as an implementation detail, so that to the user a button is a button is a button is a button.

I think the framework would be more robust and allow for less fragile test writing if it behaved in a way parallel to browsers. Would a test author ever want to select by role but _not_ include both explicit and implicit semantics?

**Comment by reubenvivi** [comment]
I have an ember Button element to which I added an `aria-label` to identify it, but playwright seems to go into an infinite loop and never stops once the line is encountered. Below is how the element is defined in the DOM

**Comment by dgozman** [comment]
@reubenvivi Most likely, you have more than one element with the same `aria-label`. Try [recording a trace](https://playwright.dev/docs/trace-viewer) and see what's going on.

**Comment by reubenvivi** [comment]
@dgozman I tried executing the trace but unfortunately the script does not stop once it encounters the line where I pass the aria-label, and I am not sure if the trace file is generated if the script is manually stopped. Also, the aria-label attached to the component was manually created by me specifically for that element and hence no duplicates exist.

**Comment by dgozman** [comment]
@reubenvivi Unless you provide us a repro we can run locally, you'll have to use available debugging tools. You can start with `PWDEBUG=1` to run [inspector](https://playwright.dev/docs/inspector) and check the logs for the operation that does not finish.

**Comment by reubenvivi** [comment]
@dgozman thank you for your response. I ran the inspector but it does not display the log of what happens when it gets stuck. It shows the previous element interaction. I found this article and on Modal Dialogs and it seems to make sense as to why it is behaving like that. [https://playwright.dev/docs/dialogs#alert-confirm-prompt-dialogs](url) My only issue is why other selectors work on the modal but when I refer to the button using an aria-label the execution fails.

**Comment by reubenvivi** [comment]
Not sure if the HTML will help with this. Below is the extract of which I am trying to get the button using the `aria-label=Send Link` attribute. This is an ember application page
```
<div class="ModalDialog_g42qr8">
  <div class="_RouteShareLink_16hlxk">
    <div class="_container_16hlxk">
      <div class="_contents_16hlxk">
          <div class="_heading_16hlxk">Share a Link With Everyone in This Room:</div>
          <input placeholder="Paste URL Here" id="ember491" class="ember-text-field ember-view" data-vivi- 
           link="shareLinkInput" type="text">
          <button class="ladda-button  _ViviButton_1fsknc _intentPrimary_1fsknc _sizeMedium_1fsknc" data-style="zoom- 
            out" aria-label="Send Link" data-vivi-link="shareLinkSendButton" type="button">
          <span class="ladda-label">
            <svg class="IconSvg_xv72im" width="18" height="18" style="min-width:18px;" 
               xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                <use xlink:href="images/icons/send-link.svg#icon-send-link"></use>
            </svg>
         Send Link
         <!---->
      </span>
<span class="ladda-spinner"></span></button>
      </div>
        <!---->    
    </div>
 </div>
 <button><svg class="_ViviIconSvg_xv72im" width="16" height="16" style="min-width:16px;" 
   xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <use xlink:href="images/icons/cross.svg#icon-cross"></use>
</svg>
</button>
  </div>```

**Comment by lucasfv-c1** [comment]
Were there any updates locating elements by implicitly defined ARIA roles?

According to Playwright docs on [selecting elements by role](https://playwright.dev/docs/selectors#role-selector), they say we can do something like `role=button` and it should grab `<button/>` elements but it's not working as expected.

Playing around with the Playwright Inspector, I'm not being able to select elements by implicit ARIA roles.

**Comment by dgozman** [comment]
@lucasfv-c1 This is expected. Role selector is not a css selector. Follow the [role selector docs](https://playwright.dev/docs/selectors#role-selector) for examples and details. If you have questions or something is not clear in the docs, let us know, and we'll happily improve them!

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
