### ISSUE TITLE
[BUG] Docs - Mismatched Typings `playwright` and `@playwright/test`

### ISSUE THREAD

**Issue by sidharthv96** [microsoft/playwright#9035]
**Context:**
- Playwright Version: 1.14
- Operating System: Mac
- Node.js version: 14
- Browser: N/A

**Code Snippet**
The example listed in https://playwright.dev/docs/test-pom

```ts
// playwright-dev-page.ts
import type { Page } from 'playwright';
export class PlaywrightDevPage {  
    readonly page: Page;
```

```ts
// example.spec.ts
import { test, expect } from '@playwright/test';
import { PlaywrightDevPage } from './playwright-dev-page';
test('Get Started table of contents', async ({ page }) => {  
    const playwrightDev = new PlaywrightDevPage(page);
```

**Describe the bug**

This causes issue with Typescript as the `Page` Type is from two different package.

Which is the correct package to use, `'playwright'` or `'@playwright/test'`?
I believe it is `'@playwright/test'`, I can raise a PR fixing the issue in docs.
It's present in multiple places.

**Comment by mxschmitt** [comment]
All Playwright types, values etc. are exported from `@playwright/test` so you also don't have to install the `playwright` NPM package next to the test-runner. If you still find places where we use the wrong one, feel free to raise a PR! Thanks.

We already fixed the example which you are referring to in ef35bfa0da2f04a2dcd0f701af6faa091997de9e. It should get live in the next ~1 days when 1.15 gets released.
