### ISSUE TITLE
[BUG] Expect statements don't get correctly displayed in trace-viewer

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#9044]
**Context:**
- Playwright Version: ToT
- Operating System: macOS
- Node.js version: 14

```ts
import { test, expect } from '@playwright/test'

test('B', async ({ page }) => {
  await page.goto("http://example.com")
  await expect(page.locator("body")).toHaveText('Playwright')
})
```

expected: something which contains Playwright

actual:

![image](https://user-images.githubusercontent.com/17984549/134169233-cab971fe-d412-4b1c-918b-4813323785e4.png)

**Comment by pavelfeldman** [comment]
Fixed.
