### ISSUE TITLE
[Question]Why all methods are async and in java are sync?

### ISSUE THREAD

**Issue by apis3445** [microsoft/playwright#9047]
Hello! Why all methods are async and in java are sync. If all are async I need to use await in all code lines and it's hard to compare two lists of objects with the collection assert.

**Comment by mxschmitt** [comment]
This is not a sustainable model in the Node.js platform and cannot removed by that. Java and Node.js are fundamental different.

**Comment by apis3445** [comment]
I though this was .net repo not  node
