### ISSUE TITLE
[Question] Is it possible to customize my own command and call it globally in any spec file ?

### ISSUE THREAD

**Issue by Amrkamel1** [microsoft/playwright#9055]
Is there any option through which I can add my own custom command and to be called anywhere, some command for example execute some DB queries or API request or whatever, something similar to custom command feature in cypress and wide 
https://docs.cypress.io/api/cypress-api/custom-commands

**Comment by mxschmitt** [comment]
What do you mean with customize? Please give us more input, otherwise its hard to assist. Do you want to execute shell commands inside your tests?

**Comment by mxschmitt** [comment]
No this is not possible, but a custom command is just a normal JavaScript/TypeScript function which you can import and then execute whereever you want.

Overriding existing Playwright API is not supported.

**Comment by pavelfeldman** [comment]
Unlike Cypress, Playwright is a real Node library running a real Node environment. So you don't need to extend Playwright in order to run things, you just require Node module and use it like in any other Node program.

**Comment by mxschmitt** [comment]
Closing since the issue seems answered. For any other questions please open a new one.
