### ISSUE TITLE
[BUG] Unable to see a detailed error or reason of failaure in console when waiting for element is timeout

### ISSUE THREAD

**Issue by Amrkamel1** [microsoft/playwright#9058]
**Context:**
- Playwright Version: 1.15
- Operating System: linux
- Node.js version: 14
- Browser: any

![image](https://user-images.githubusercontent.com/32042806/134247242-71332b49-f66d-4239-81f4-1c5fb1adbfcb.png)

**Code Snippet**

console show error timeout, but not specifying any useful details, like time out for what and for which element, which line...etc

```javascript

    test.beforeAll(async ({browser}) =>{
        page = await browser.newPage()
        p = new ParentList(page);
        const loginCookie = await API.getCookies('admin', 'pds');
        await page.context().addCookies([{ name: 'PHPSESSID', value: loginCookie, path: '/' ,domain:'dev.d.d'}]);

    });

    test.beforeEach(async () =>{
        await page.goto('/parent/list')
    });

    test('01. Should be able to add new project', async () => {
        await p.waitForElement(p.parentListHeader)   //  I intentionally make it fails here
    });
```

**Describe the bug**

Unable to see a detailed info when a test is failing like referring to an element and print a meaningful error that could help in debugging.

**Comment by dgozman** [comment]
@Amrkamel1 Could you please share the `ParentList.waitForElement` method? What Playwright APIs does it call? We need to reproduce the issue to be able to fix it 😄

**Comment by Amrkamel1** [comment]
@dgozman 

```
    parentListHeader = 'text="Parents Lists"';

    async waitForElement(element) {
        await this.page.waitForSelector(element)
        return this;
    }
```

```
    test('01. Should be able to add new project', async () => {
        await p.waitForElement(p.parentListHeader)   //  I intentionally make it fails here
    });
```

**Comment by Amrkamel1** [comment]
@dgozman Is there something I missing, prevent detailed log from being displayed

**Comment by dgozman** [comment]
@Amrkamel1 The reason is that you create your own `page` in the `beforeAll`. So when the test times out, `p.waitForElement()` is still running and does not give you any logs. Since you are already navigating in `beforeEach`, I'd suggest you to use built-in `page` instead: https://playwright.dev/docs/intro#using-test-fixtures.

Meanwhile, I'll see what we can do to improve the situation.

**Comment by Amrkamel1** [comment]
Gotcha thank you.
