### ISSUE TITLE
Is there any way we can able to automate chartsJs and canvas graph

### ISSUE THREAD

**Issue by Lakshmi-Yaswanth** [microsoft/playwright#9063]
For ur reference :https://www.chartjs.org/docs/latest/samples/bar/vertical.html
this is the url for charts we can able to automate.

**Comment by mxschmitt** [comment]
You could use [page.mouse.click(x, y)](https://playwright.dev/docs/api/class-mouse#mouse-click) but besides that there is no other way since you can't search elements on a canvas by e.g. text.

What kind of interaction would you like to implement?

**Comment by Lakshmi-Yaswanth** [comment]
Reference: `https://www.awesomescreenshot.com/image/13841134?key=7a3b3865fa3cf1c079bc3a1a97de0492`
Here in this image we are using two button. Yes as you said in canvas we cannot get "Text" or any selector. Is there any way we can able to click that button which was highlighted in image i have send.

**Comment by mxschmitt** [comment]
Then only page.mouse.click(x, y) would work for now.

**Comment by Lakshmi-Yaswanth** [comment]
Thanks u @mxschmitt .Thanks for ur reply.
