### ISSUE TITLE
[Question] How can I add global variables to the playwright test runner?

### ISSUE THREAD

**Issue by MaksymChepilDevPro** [microsoft/playwright#9064]
I've planing to migrate from jest to the playwright-test. In jest config I can declare globals trough config

```
  globals: {
    'ts-jest': {
      tsconfig: 'tsconfig.json'
    },
    page: {},
    testId: '',
    timeout: 30_000,
    allureConfig: {
      epic: '',
      feature: '',
      story: '',
      issues: [],
      owner: '',
      severity: ''
    }
  },
```

For now I declare this variables via node.js, nevertheless I get error for testId that I add at the beginning of each suite:
```
testId = 'INV-T00001';
test.describe(`[${testId}] Login page`, () => {
```
`ReferenceError: testId is not defined`
 
Question: 
How can I declare global variable through pw-test?

NOTE:
Also this will help with migration from Jest to PW-test

**Comment by mxschmitt** [comment]
In Playwright Test there is no concept of global variables. You could hack it yourself together, but we would not recommend that. Instead we would pass the page instance everywhere where you need it. For constants a constants file e.g. can be used.

Would that work for you?

Also this might be useful for you while migrating: https://playwright.dev/docs/test-retries#reuse-single-page-between-tests

**Comment by MaksymChepilDevPro** [comment]
Thank you for the response.
In my case we are using page objects and pass page through the test [without fixtures ](https://playwright.dev/docs/test-fixtures/#without-fixtures)- no problems here.
One of the blocker during the migration is to manage passing variable from the test to the service through global vars (this helps with logs and allure), without passing it as an args to services and with allure integration (hope there will be no problem with [allure-playwright](https://www.npmjs.com/package/allure-playwright).

Also we have almost 2K tests and it will be awesome to have minimum refactoring of the "test design". 

Even jest-playwright-preset has this globals under the hood. We manage to get rid of jest-playwright-preset and using jest+playwright with global variables.

Is there a plan of adding ability to declare global variables?

**Comment by mxschmitt** [comment]
> Also we have almost 2K tests and it will be awesome to have minimum refactoring of the "test design".

You could do it in two iterations.

1. stay on jest-playwright-preset and move all global page uses to passing them from the test over to your classes
1. move to the playwright test-runner

> Is there a plan of adding ability to declare global variables?

Probably not, because we prefer the normal world where a page instance gets passed into a test and you don't need custom TypeScript definitions.

**Comment by MaksymChepilDevPro** [comment]
Thank you for the quick response. Will think about get rid of global variables.

**Comment by nishantkhandelwal** [comment]
@mxschmitt
Sorry for commenting on a closed issue but my scenario is quite similar to this.
I am using @playwright/experimental-ct-react for component testing and I have got few variables using process and exposed via webpack's definePlugin.
Which I am not able to access when mounting my component in the playWright.
any help regarding this ?

**Comment by mxschmitt** [comment]
@nishantkhandelwal I recommend to file a new issue. Playwright component testing is using Vite, so it won't look at your webpack configuration.
