### ISSUE TITLE
How can I verify all the dropdown values in Playwright?

### ISSUE THREAD

**Issue by tmazumder** [microsoft/playwright#9066]

**Comment by mxschmitt** [comment]
See here: https://playwright.dev/docs/input#select-options

If its not a native `<select>` element then you need to manually check if your element contains text. 

https://playwright.dev/docs/test-assertions#expectlocatortohavetextexpected-options

**Comment by tmazumder** [comment]
Thanks for the update. My web elements were not in native select.
Below code worked for me :

const locatorFCR = this.page.locator('#behavior-selection .cxone-singleselect-dropdown .dropdown-popover-wrapper .options-wrapper .item-row');   //locator for dropdown
 
 await expect(locatorFCR).toHaveText(['Dropdown Value1', 'Dropdown Value2', 'Dropdown Value3', 'Dropdown Value4']);
//assert for matching the dropdown values
