### ISSUE TITLE
[BUG] Large locators in Playwright Inspector are overlapping in v.1.15.0

### ISSUE THREAD

**Issue by RockMinsk** [microsoft/playwright#9067]
**Context:**
- Playwright Version: 1.15.0
- Operating System: Windows 10
- Node.js version: 14.17.3
- Browser: Chromium

**Description**

Large locators in Playwright Inspector are overlapping in v.1.15.0
See attached screenshot to clarify the issue:

![1](https://user-images.githubusercontent.com/30350649/134312343-df3f39f8-cab6-41e4-aae2-844d84417268.png)

**Comment by mxschmitt** [comment]
@RockMinsk it should be fixed already when you are using the `next` release.

```
npm i playwright@next 
npm i @playwright/test@next # When using Playwright test-runner 
```

Would be awesome if you could confirm, thanks!
