### ISSUE TITLE
[BUG] Type error when installing playwright 

### ISSUE THREAD

**Issue by jkanchelov** [microsoft/playwright#907]
I am getting definition error - 

`node_modules/playwright-core/lib/helper.d.ts:17:23 - error TS2688: Cannot find type definition file for 'debug'.`

here is my .tscconfig 

`{
    "compilerOptions": {
        "target": "esnext",
        "module": "commonjs",
        "declaration": true,
        "outDir": "./dist",
    },
    "files": ["./src/index.ts"]
}
`

**Comment by pavelfeldman** [comment]
Could you share more about your project set up and what you are doing? This looks like an error that VS Code is reporting? What's your TS version, what is your Playwright version?

**Comment by jkanchelov** [comment]
Here is the project ( I left the problem unresolved just for the sake of this issue ). Using playwright 0.10.0 on windows env

https://github.com/jkanchelov/browser-screenshot-taker/

PS - If I add @types/debug everything is alright

**Comment by pavelfeldman** [comment]
I cloned the project, but I can't find the error that you mention above. Are there any extra steps?

**Comment by jkanchelov** [comment]
I tried with my personal computer installing the latest LTS version of node 12.15.0, removing the package-lock.json and still when I am trying to build with tsc I get this reference error in helper.d.ts referencing the "debug" types. 

I see that the dependency version of @types/debug is 0.0.31 and the debug package version is ^4.1.0. Is this intended?

**Comment by pavelfeldman** [comment]
I need exact steps that you perform to be able to fix it. I.e. sequence of commands you run in bash or in vscode or in other environment you use.

**Comment by dgozman** [comment]
We'll fix this as a part of #6.
