### ISSUE TITLE
[Feature] Allow init-scripts to return JSHandle

### ISSUE THREAD

**Issue by mindplay-dk** [microsoft/playwright#9072]
I have a use-case where I'm injecting a script using `page.addInitScript`.

The injected script collects some information on the page (across iframes) in a global variable attached to `window.top`.

I can then use `page.evaluateHandle` to obtain a `JSHandle` reference to the global variable I attached to `window.top`.

The concern for this particular project, is this would enable someone to use a technology sniffer and discover that our script is present - we operate in a space where this is potentially a legal concern, so I need to address that somehow.

I thought about randomizing the variable-name - but you could still potentially scan all the properties of `window.top` and identify our object by one of it's property-names.

What I'd like to do, is avoid the global variable attached to `window.top`, and instead return a `JSHandle` from the init-script - so that this is only ever a variable in a local scope, which can't be sniffed out by someone trying to circumvent our script.

My understanding (from the documentation) is that `JSHandle` can somehow keep variables from getting garbage-collected?

However, there is no way to return a `JSHandle` from an init-script, and no way to run `evaluateHandle` as early as in init-script.

I suppose this might not be an easy fix, since an init-script gets run more than once? Maybe this would work only for the handle returned by the root frame? 🤔

**Comment by mxschmitt** [comment]
This is probably the best effort what you can do right now:

```js
const playwright = require('playwright');

(async () => {
    const browser = await playwright.chromium.launch();
    const context = await browser.newContext();
    await context.exposeBinding('registerCallback', async source => {
      const myHandle = await source.page.evaluateHandle(() => window.myExposedValue)
      await source.page.evaluate(() => delete window.myExposedValue)
      console.log("foo", (await (await myHandle.getProperty("foo")).jsonValue()))
    })
    await context.addInitScript(() => {
      const myClass = new Object()
      myClass.foo = "bar"
      window.myExposedValue = myClass // use there your value
      window.registerCallback()
    })
    const page = await context.newPage();
    await page.goto('http://whatsmyuseragent.org/');
    await browser.close();
})();
```

but there is "registeredCallback" exposed and myExposedValue is temporarily exposed.

Since this is not about end-to-end testing I'm closing this issue.
