### ISSUE TITLE
[Question] Cause test failure on error in test.afterAll

### ISSUE THREAD

**Issue by rollin-cogers** [microsoft/playwright#9086]
I have a situation where I am calling on an api to tear down test data for my test. In most cases this is not an issue, but I noticed some data hanging around after a previous run because the tear down failed and threw an error.

Something like this:
```javascript
test.describe('Related tests', async () => {
    test('test one', async () => {
        expect(true).toBe(true)
    })
    test.afterAll(async () => {
        throw Error('oops!') //This does not fail the test, but does get logged to the console.
    })
})
```

Is there a way that I can fail the spec or describe here based on an error in the afterAll?
Thanks for any help or input!

**Comment by mxschmitt** [comment]
This is not yet possible, but you could use e.g. a try/catch and just log it to the console instead of throwing an error. Would that work for your use-case?

**Comment by mxschmitt** [comment]
afterAll gets run after all the tests. So they were already reported to the reporters as passing etc. due to that its not possible to set them after the afterAll ran to the failed status.
Its then reporting as exitCode = 1 t reflect that which is working as intended.
