### ISSUE TITLE
[QUESTION] N-th element selector does not work for data inside tables?

### ISSUE THREAD

**Issue by sheeeng** [microsoft/playwright#9090]
I have [this failing test](https://github.com/3lvia/onetime-yopass/runs/3680211069?check_suite_focus=true) on GitHub Actions and Azure DevOps with the same error messages.

```typescript
    const allTableBody = await page.$$eval(
      'tbody .MuiTableRow-root',
      (items) => {
        return items.map((item) => {
          const secondColumnData = item.querySelector('td:nth-child(2)');
          const thirdColumnData = item.querySelector('td:nth-child(3)');
          return {
            secondColumnData: secondColumnData.textContent.trim(),
            thirdColumnData: thirdColumnData.textContent.trim(),
          };
        });
      },
    );

    console.log(`The table has ${allTableBody.length} items....`);
    if (allTableBody.length > 0) {
      console.dir(allTableBody);
      console.log('OneClickLink:', `${allTableBody.at(0).thirdColumnData}`);
      accessSecretFullLinkText = `${allTableBody.at(0).thirdColumnData}`;
    } else {
      console.log('The table is empty!');
    }
```

However, I can run this test successfully locally on my machine on each and every single time.

```text
The table has 3 items....
[
  {
    secondColumnData: 'One-click link',
    thirdColumnData: 'http://localhost:3000/#/s/84e6def0-9a60-41ab-902e-260e871e7d17/phtROfGY6SrA'
  },
  {
    secondColumnData: 'Short link',
    thirdColumnData: 'http://localhost:3000/#/s/84e6def0-9a60-41ab-902e-260e871e7d17'
  },
  {
    secondColumnData: 'Decryption Key',
    thirdColumnData: 'phtROfGY6SrA'
  }
]
OneClickLink: http://localhost:3000/#/s/84e6def0-9a60-41ab-902e-260e871e7d17/phtROfGY6SrA
```

<img width="891" alt="Screenshot 2021-09-22 at 23 06 13" src="https://user-images.githubusercontent.com/305414/134422235-a9461a5f-2ed4-48e4-ada7-cc8f79150555.png">

How can I obtain the text inside the red area in the table using the correct way?

I have also tried the following alternative, but I receive `locator.textContent: Target closed` error.

```typescript
    const fullLinkSelector = 'tr >> nth=0 >> td >> nth=2';
    const fullLinkLocator = page.locator(fullLinkSelector);
    console.table(fullLinkLocator);
    accessSecretFullLinkText = (await fullLinkLocator.textContent()).toString();
```

Any ideas to debug this tricky issue are very much appreciated.

**Comment by mxschmitt** [comment]
> How can I obtain the text inside the red area in the table using the correct way?

We need the DOM / website, otherwise we are not able to assist you with that.

I recommend to follow the debugging steps, especially of using the trace-viewer to find out why its failing on your CI: https://playwright.dev/docs/debug

**Comment by sheeeng** [comment]
> We need the DOM / website, otherwise we are not able to assist you with that.

Do you mean [these lines](https://github.com/3lvia/onetime-yopass/blob/master/website/src/displaySecret/Result.tsx#L30-L75)?

**Comment by mxschmitt** [comment]
I would recommend to upload the test-results/ folder in your GitHub Actions setup to GitHub: https://github.com/actions/upload-artifact

Then you are able to use the [trace-viewer](https://playwright.dev/docs/trace-viewer) to understand why it is failing (and inspect the DOM) on the CI and why not.

**Comment by sheeeng** [comment]
Thank you for the suggestion on using the trace-viewer! I will look into them.
