### ISSUE TITLE
[Question] Is it possible to access a baseURL that contains a hashtag directly?

### ISSUE THREAD

**Issue by A-ZC-Lau** [microsoft/playwright#9098]
Given that I have the baseURL as

`baseURL : "http://www.google.com/something/#/channels"`

Is there a way to also access the `/#/channels` portion when using `page.goto`?

When I use `page.goto("")` it will go to `http://www.google.com/something/` and I can't use `page.goto()` as it gives me the error `page.goto: url: expected string, got undefined`

**Comment by ltsuda** [comment]
You can use `page.goto("/")` to navigate to the `baseURL`.

As linked here https://playwright.dev/docs/api/class-page#page-goto in the link [new URL()](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL), see example:
```text
let a = new URL("/", m); 
```
I hope this helps.

**Comment by A-ZC-Lau** [comment]
@ltsuda That doesn't go to that url, it goes to `http://www.google.com`

```javascript
const m = "http://www.google.com/something/#/channels/"
let a = new URL("/", m); 
a.toString()
    |    "http://www.google.com/"
```

**Comment by mxschmitt** [comment]
Its expected currently that baseURL does not take the URL fragment into consideration. 

You would have to do something like that then:

```ts
const m = "http://www.google.com/something/"
console.log(new URL("./#/abc", m).toString())
// -> http://www.google.com/something/#/abc
```

would this work for you?

**Comment by A-ZC-Lau** [comment]
@mxschmitt It will just be something to note. But I guess I can work around it.
