### ISSUE TITLE
[BUG] install-deps causes error "Invalid or unexpected token" on upgrading to v1.15.0

### ISSUE THREAD

**Issue by anishkny** [microsoft/playwright#9100]
**Context:**
- Playwright Version: v1.15.0 (upgrading form v1.14.1)
- Operating System: GitHub Actions Ubuntu 20.04.3 LTS
- Node.js version: v10.24.1
- Browser: All
- Extra: 

**Code Snippet**

```bash
$ npx playwright install-deps
Invalid or unexpected token
```

**Describe the bug**

This issue was observed on a Dependabot PR upgrading from v1.14.1 to v1.15.0: https://github.com/anishkny/playwright-test-coverage/pull/2

The action has run fine in the past when on v1.14.1, e.g. https://github.com/anishkny/playwright-test-coverage/runs/3654208040?check_suite_focus=true#step:4:36

```
2021-09-20T16:48:20.7507350Z + npx playwright install-deps
2021-09-20T16:48:21.1968873Z Installing Ubuntu dependencies...
2021-09-20T16:48:21.4591252Z Hit:1 http://azure.archive.ubuntu.com/ubuntu focal InRelease
2021-09-20T16:48:21.4627170Z Get:2 http://azure.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
...
```

**Comment by mxschmitt** [comment]
@anishkny I see the CI pipeline passing after you restarted it. Seemed just like an temporary problem?

**Comment by anishkny** [comment]
@mxschmitt yes thanks for checking in. The fix was to upgrade the workflow to use Node.js v14 (the default was v10).

https://github.com/anishkny/playwright-test-coverage/commit/8752c4a343a93a3707bdc11b923b939a56587662

Although the error message could have been more helpful? I had to dig around to figure it out.

Also, it appears Node.js v10 was not supported even back in Playwright v1.14? So it was weird it broke on upgrading to Playwright v1.15.

**Comment by mxschmitt** [comment]
Weird, we say that we are only compatible with 12+ so it should have mentioned it somewhere: https://unpkg.com/browse/@playwright/test@1.15.0/package.json

**Comment by mxschmitt** [comment]
Closing since when installing it will say that 12+ is required:

```
root@2ba4fa6350d8:/tmp# npm install @playwright/test

> @playwright/test@1.15.0 install /tmp/node_modules/@playwright/test
> node install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for @playwright/test@1.15.0: wanted: {"node":">=12"} (current: {"node":"10.24.1","npm":"6.14.12"})
```

The reason for the error that we are using [numeric separators](https://v8.dev/features/numeric-separators) which were introduced in Node.js 12.
