### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by vivekvasu** [microsoft/playwright#9103]
How can i get the total number of tabs opened. For instance, i clicked on a link which opened a couple of new tabs and I have to verify the tab count ?

**Comment by mxschmitt** [comment]
You could do `context.pages().length` but this also include popups etc. There is no concepts of tabs in Playwright. See here: https://playwright.dev/docs/core-concepts#browser-contexts

**Comment by mxschmitt** [comment]
Closing since the issue seems answered. For any other questions please open a new one.
