### ISSUE TITLE
[BUG]: downloading browsers via https endpoint does not work behind proxy in some cases.

### ISSUE THREAD

**Issue by pomahtuk** [microsoft/playwright#9106]
**Context:**
## System:
 - OS: Linux 3.10 CentOS Linux 7 (Core)
 - Memory: 15.78 GB / 125.51 GB
 - Container: Yes
## Binaries:
 - Node: 16.8.0 - /usr/bin/node
 - Yarn: 1.22.11 - /usr/bin/yarn
 - npm: 7.24.0 - /usr/bin/npm
## Languages:
 - Bash: 4.2.46 - /usr/bin/bash

**Describe the bug**

Inside my company network we usually define proxy like this:
```
export http_proxy=http://proxy.company.com:3128/; export https_proxy=$http_proxy; export no_proxy=.company.com 
```

And as defined here: https://github.com/microsoft/playwright/blob/master/src/utils/utils.ts#L81
if protocol is not `https` then `http.request` will be used.

But end result is an `https` response.

This results in this error during installation (error sanitized to remove unecessary paths):

```
erroe <some>/node_modules/playwright: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: <some>/node_modules/playwright
Output:
<some>/node_modules/playwright/lib/utils/registry.js:557
      throw new Error(`Failed to download ${title}, caused by\n${e.stack}`);
            ^
Error: Failed to download chromium v920619, caused by
TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new NodeError (node:internal/errors:371:5)
    at new ClientRequest (node:_http_client:158:11)
    at Object.request (node:https:353:10)
```

**Comment by mxschmitt** [comment]
This is related to: https://github.com/microsoft/playwright/blob/bb4cf28879df19f50f43d6d2c78d9e589d216ab9/src/utils/utils.ts#L40-L60

**Comment by mxschmitt** [comment]
Is it correct that you are using a http:// proxy and set it for http_proxy and https_proxy environment variable?

I tried to reproduce it but it works for me in an isolated environment:

```
HTTPS_PROXY=http://squid:3128
HTTP_PROXY=http://squid:3128
npx playwright install
-> downloads browsers
```

**Comment by pomahtuk** [comment]
It is correct.

**Comment by pomahtuk** [comment]
Unfortunatelly, issue only reproducible inside CI runners, so i don't have interactive shell to try things out.

**Comment by pomahtuk** [comment]
Also, important note - it works just fine on NodeJS 14, but somethign works differently on version 16.

**Comment by pomahtuk** [comment]
Sorry for spam.

Actually, reproduced locally.

```
HTTPS_PROXY=http://squid:3128  HTTP_PROXY=http://squid:3128 npx  playwright install  
```

Works fine for Node version `12` and `14`, but throwing `TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"` in version `16`

**Comment by mxschmitt** [comment]
Hmm, I'm unfortunately not able to repro. I'm using this squid container with which it seems to work: https://hub.docker.com/r/sameersbn/squid

Do you have insights what kind of proxy you are using?

Node.js 16.8.0
Playwright 1.15.0

**Comment by pomahtuk** [comment]
Ok, it defenitelly seems like some network configuration.

I think issue can be closed, this has nothing to do with playwright itself.
