### ISSUE TITLE
[Question] Is regex supported while passing --project in @playwright/test

### ISSUE THREAD

**Issue by karanshah-browserstack** [microsoft/playwright#9108]
We have a requirement where we want to run the projects on-demand with different configurations. We would like to know is regex supported in --project. For example: `--project chrome*`
```
 "projects": [
{
      name: "chrome",
      use: {
        browserName: "chromium",
        // Test against Chrome channel.
        channel: "chrome",
      },
    },
    {
      name: "safari",
      use: {
        browserName: "webkit",
        viewport: { width: 1200, height: 750 },
      },
    },
    {
      name: "firefox",
      use: {
        browserName: "firefox",
        viewport: { width: 800, height: 600 },
      },
    },
    {
      name: "chrome@pixel5",
      use: {
        ...devices["Pixel 5"]
      }
    },
]
```

**Comment by mxschmitt** [comment]
It is not supported but you can specify it multiple times.

```
npx playwright test --project chromium --project chrome@pixel5
```

Would that work for you?

**Comment by mxschmitt** [comment]
Closing since the issue seems answered. For any other questions please open a new one.

**Comment by karanshah-browserstack** [comment]
@mxschmitt No, this doesn't work as we keep adding automation and new projects for cross browser testing. And need to run test cases based on different os browser combinations.  So ideally a regex whould be preferred . Eg. win-chrome*, win-osx* etc
