### ISSUE TITLE
How to give index to a "selector" to the xpath.

### ISSUE THREAD

**Issue by Lakshmi-Yaswanth** [microsoft/playwright#9110]
##Protractor
```
In Protractor we have locator such Xpath
 public columnsDropdownSelectOptions = element.all(
    by.xpath(
      "//button[text()='Columns']/following::div[1]//mdb-checkbox//label"
    )
  );
columnsDropdownSelectOptions.get(1);
`https://www.protractortest.org/#/api?view=ElementArrayFinder.prototype.get
`Here get help to give index to the xpath .
```
In Playwright is there anyway we can give index to the `"Xpath="//span[@class='pillContent']/following-sibling::span";`
`for Example://span[@class='pillContent']/following-sibling::span[1]`

**Comment by mxschmitt** [comment]
You should be able to combine it with the `nth` selector engine. See here: https://playwright.dev/docs/selectors#n-th-element-selector

example: `xpath="//span[@class='pillContent']/following-sibling >> nth=1`

Also you can use the Playwright Inspector to try out the selectors: https://playwright.dev/docs/inspector#open-playwright-inspector
