### ISSUE TITLE
[BUG] Setting storageState in the global-setup doesn't propagate to the tests

### ISSUE THREAD

**Issue by rafaelramalho19** [microsoft/playwright#9112]
**Context:**
- Playwright (Test) Version: 1.15.0
- Browser: Chromium

## System:
 - OS: macOS 11.4
 - Memory: 391.70 MB / 16.00 GB
## Binaries:
 - Node: 16.5.0 - ~/.nvm/versions/node/v16.5.0/bin/node
 - Yarn: 1.22.11 - ~/.nvm/versions/node/v16.5.0/bin/yarn
 - npm: 7.19.1 - ~/.nvm/versions/node/v16.5.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
// global-setup.ts
import { chromium } from '@playwright/test';
import dotenv from 'dotenv'
import path from 'path'

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') })

async function globalSetup(config) {
  const { baseURL, storageState } = config.projects[0].use;
  const browser = await chromium.launch();
  const page = await browser.newPage();

  console.log("🐙 Started Github login");
  await page.goto(`${baseURL}/login/`);

  await page.click("form > div > button");

  await page.waitForSelector("#login_field");

  await page.fill("#login_field", process.env.TEST_EMAIL);
  await page.fill("#password", process.env.TEST_PASSWORD);
  await page.click('text="Sign in"');

  console.log("🐙 Finished Github login");

  await page.waitForSelector('text="ONLY VISIBLE WHEN LOGGED IN"');
  await page.context().storageState({ path: storageState });

  console.log("✅ Saved authentication state to ", storageState);
  await browser.close();
}

export default globalSetup;
```

```javascript
// playwright.config.ts
const config = {
  globalSetup: require.resolve('./tests/global-setup'),
  use: {
    baseURL: 'https://my-url.com',
    storageState: './tests/state.json'
  },
};
export default config;
```

```javascript
// test.spec.ts
import { test, expect } from "@playwright/test";

test("basic test", async ({ page }) => {
  await page.goto("/upload");

  await page.waitForSelector(ITEM_THAT_ONLY_SHOWS_WHEN_AUTHENTICATED);
});
```

**Describe the bug**

When storing the `storageState` in the `globalSetup` function, it doesn't apply it to the test file. (So, when I run the "basic test", it shows me as not logged in).
However, when I don't run the `await page.context().storageState({ path: storageState });` code in the global-setup, it works. So my issue is that I want to make sure I have a fresh storageState in every CI run, but if I store the state in a run, it doesn't work. While running with a previous storageState it works!

**Comment by mxschmitt** [comment]
> When storing the storageState in the globalSetup function, it doesn't apply it to the test file.

This is expected, you need to save it inside your global setup and then set it inside your playwright.config.ts file so that it gets applied in all the tests.

> but if I store the state in a run, it doesn't work.

what do you mean with that? Normally you add it to your gitignore, then in the global setup it gets created and in the playwright.config it gets applied to all your tests.

**Comment by mxschmitt** [comment]
I tried to reproduce it but for me its working as expected, see here: https://github.com/mxschmitt/playwright-issue-9112

**Comment by rafaelramalho19** [comment]
> I tried to reproduce it but for me its working as expected, see here: https://github.com/mxschmitt/playwright-issue-9112

That link is private

**Comment by mxschmitt** [comment]
Sorry my bad, @rafaelramalho19 its public now.

**Comment by rafaelramalho19** [comment]
Thanks for spending time on this @mxschmitt, I just double checked from your project and for my use-case personally still fails.

Is it because I require authentication from an external origin (https://auth.magic.link) ? I'm really not seeing any other difference here other than that...

**Comment by aslushnikov** [comment]
@rafaelramalho19 the only thing that bothers me in this setup is the relative path to the `storageState`. Could you please try putting the absolute path there with `path.resolve()`?

But that's speculation. Maybe you can come up with a public repro so that we can reproduce this? Or maybe you can share something privately?

**Comment by rafaelramalho19** [comment]
I also used absolute paths and it didn't change anything @aslushnikov. I'm trying to debug what's the issue with magic auth and playwright's storageState, because it looks like that's the issue

**Comment by ip19** [comment]
@rafaelramalho19, have you resolved that issue? The same thing for me.
