### ISSUE TITLE
[BUG] browser has no newPage method

### ISSUE THREAD

**Issue by lcswillems** [microsoft/playwright#912]
**Context:**
- Playwright Version: 0.10
- Operating System: Linux

**Code Snippet**

This snippet:

```javascript
import playwright from "playwright";

(async () => {
  const browser = await playwright.chromium.launch();
  const page = await browser.newPage("http://whatsmyuseragent.org/");
  await page.screenshot({ path: `example-chromium.png` });
  await browser.close();
})();

```

gives me this Typescript error:

```
Property 'newPage' does not exist on type 'CRBrowser'
```

**Comment by pavelfeldman** [comment]
There is no `browser.newPage`in 0.10.0 (see the [docs](https://github.com/microsoft/playwright/blob/v0.10.0/docs/api.md#class-browser)). You should explicitly create the browser context as in our examples.

**Comment by lcswillems** [comment]
In this case, you should update the examples on the home README

**Comment by pavelfeldman** [comment]
Yes, @lcswillems, just did. Those slipped my sight, so thank you for the heads up again. It is all a little confusing since the have that method in the tip of the tree, but we need to make sure README makes sense for the latest pushed version.

**Comment by lcswillems** [comment]
Thanks a lot for your great work!!

I was trying to do something with Puppeteer but it didn't. I tried with Playwright and it worked! Playwright works better than Puppeteer even if the stable version is not released yet. Amazing work!

**Comment by arjun27** [comment]
Thanks @lcswillems. If you don't mind sharing, I would love to know more about your scenario and how it worked better with Playwright. Thank you!

**Comment by lcswillems** [comment]
I don't remember precisely but I know that `waitForSelector` was not working with Puppeteer on headless mode (it was waiting indefenitely). I tried with Playwright and it was working fine with webkit for example.
