### ISSUE TITLE
[BUG] waitForFunction may be broken by in-browser fake timers

### ISSUE THREAD

**Issue by PaperStrike** [microsoft/playwright#9123]
**Context:**
- Playwright Version: 1.14.1
- Operating System: Windows
- Node.js version: 14.17.0
- Browser: Chromium
- Extra: Running unit tests with [`playwright-test`](https://github.com/hugomrdias/playwright-test)

**Code Snippet**

```javascript
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();

  const hang = page.waitForFunction(() => window.foo === 'bar');

  page.evaluate(() => {
    const { requestAnimationFrame } = window;

    // Comment out to pass
    window.requestAnimationFrame = () => {};

    // Two request to bypass requested predicate
    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        window.foo = 'bar';
      });
    });
  });

  await hang;

  console.log('you must have had something commented out to get this log');

  await browser.close();
})();
```

I think the problem is quite clear that we are always relying on the functions from `window` in browser

https://github.com/microsoft/playwright/blob/0908dc98c8d6226fa02c6a0a5fd81003dcb8e158/src/server/injected/injectedScript.ts#L282
https://github.com/microsoft/playwright/blob/0908dc98c8d6226fa02c6a0a5fd81003dcb8e158/src/server/injected/injectedScript.ts#L309

without storing a reference in advance.

**Describe the bug**

`waitForFunction` may break if `window.setTimeout` / `window.requestAnimationFrame` were mocked.

**Comment by mxschmitt** [comment]
waitForFunction is running in the same execution context as the normal JavaScript runs. Due that its expected that it missbehaves when the globals are modified, monkey-patched, or emulated.
