### ISSUE TITLE
[BUG] 2-argument functions as fixtures

### ISSUE THREAD

**Issue by thewilkybarkid** [microsoft/playwright#9125]
**Context:**

Run using the `mcr.microsoft.com/playwright:v1.14.1-focal` container.

 - OS: macOS 11.6
 - Memory: 63.82 MB / 16.00 GB
 - Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
 - npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
 - Bash: 5.1.4 - /usr/local/bin/bash

**Code Snippet**

Untyped wrapped function fixture:

```typescript
import baseTest from '@playwright/test';

type MyFixtures = {
  fixture: (arg1: string, arg2: string) => number;
};

export const myTest = baseTest.extend<MyFixtures>({
  fixture: async ({ baseURL }, use) => {
    await use((arg1, arg2) => baseURL.length + arg1.length + arg2.length);
  },
});
```

Untyped constant function fixture:

```ts
export const myTest = baseTest.extend<MyFixtures>({
  fixture: (arg1, arg2) => arg1.length + arg2.length,
});
```

(Based on https://github.com/PREreview/prereview/blob/9e8f3db401f1fa7fc953c29d672b6a93e2fb9ee1/integration/src/fixtures.ts#L31-L39.)

**Describe the bug**

Having a fixture that's a function that takes two arguments (snippet 1) leads TypeScript to fail to infer the type. I have TypeScript's strict mode on locally, so this causes 'No Implicit Any' failures. The code runs successfully, however.

![image](https://user-images.githubusercontent.com/1784740/134660386-c7d6e7cc-e39f-42cb-829b-16544fb428f4.png)

As a workaround, I have to type it explicitly, meaning something like:

```ts
import { PlaywrightTestOptions } from '@playwright/test';

export const myTest = baseTest.extend<MyFixtures>({
  fixture: async ({ baseURL }: PlaywrightTestOptions, use: (r: MyFixtures['fixture']) => Promise<void>) => {
    await use((arg1, arg2) => baseURL.length + arg1.length + arg2.length);
  },
});
```

which isn't ideal.

Having a constant fixture (i.e. one not wrapped in a `use`) also can't be inferred (snippet 2):

![image](https://user-images.githubusercontent.com/1784740/134660871-e8309dfc-bf5a-485d-96ac-b507451906b8.png)

But can be typed:

```ts
export const myTest = baseTest.extend<MyFixtures>({
  fixture: (arg1: string, arg2: string): number => arg1.length + arg2.length,
});
```

The problem is the union types in https://github.com/microsoft/playwright/blob/231bf36029dacdd6787e49bc7f87e3a671cd4f6e/types/test.d.ts#L2285-L2286

Is having a function as a fixture that is constant meant to be possible? If not, then the types could be updated to

```ts
type TestFixtureValue<R, Args> = (R extends Function ? never : R) | TestFixture<R, Args>;
type WorkerFixtureValue<R, Args> = (R extends Function ? never : R) | WorkerFixture<R, Args>;
```

which allows the first snippet to be inferred correctly, and the second snippet error (even when not using TS's strict mode).

![image](https://user-images.githubusercontent.com/1784740/134660093-d6d3687b-6e7b-46c3-b76e-b0851e6289b4.png)

**Comment by mxschmitt** [comment]
This seems related to https://github.com/microsoft/playwright/issues/9116 maybe its even the same bug.

**Comment by mxschmitt** [comment]
I was able to verify that it works on the latest version `npm i @playwright/test@next`. We'll release it soon with 1.15.1.

code:

```ts
import { Fixtures, PlaywrightTestOptions } from '@playwright/test';
import crc32 from 'crc-32';
import faker from 'faker';
import { ensurePreprint, Preprint } from './api';
import { Fetch, fetch } from './fetch';

type FakerFixtures = {
  seed: number;
  faker: typeof faker;
};

type HttpFixtures = {
  fetch: Fetch;
};

type DataFixtures = {
  preprint: Preprint;
};

export const fakerFixtures: Fixtures<FakerFixtures> = {
  seed: async ({}, use, testInfo) => {
    await use(crc32.str(testInfo.snapshotPath(testInfo.title)));
  },
  faker: async ({ seed }, use) => {
    faker.seed(seed);

    await use(faker);
  },
};

export const httpFixtures: Fixtures<HttpFixtures & PlaywrightTestOptions> = {
  fetch: async ({ baseURL }, use,) => {
    await use(fetch(baseURL));
  },
};

export const dataFixtures: Fixtures<DataFixtures, {}, FakerFixtures & HttpFixtures> = {
  preprint: async ({ faker, fetch }, use) => {
    const preprint: Preprint = {
      doi: `10.5555/${faker.datatype.uuid()}`,
      title: faker.lorem.sentence(),
      abstract: faker.lorem.sentences(),
    };

    await ensurePreprint(fetch, preprint);

    await use(preprint);
  },
};
```

**Comment by thewilkybarkid** [comment]
@mxschmitt Could this be reopened? I've just tried all the code above and, unfortunately, none of it works in 1.15.1... (still getting `[...]  implicitly has an 'any' type`.)

**Comment by mxschmitt** [comment]
Did you try `npm i @playwright/test@next`? I think we did not cherry-pick it.

**Comment by thewilkybarkid** [comment]
Ah yes, the types are correct there.
