### ISSUE TITLE
[BUG] Nested iframes

### ISSUE THREAD

**Issue by Mbensler** [microsoft/playwright#9127]
**Context:**
- Playwright Version: 1.15.0
- Operating System: Windows
- Node.js version: 14.17.6
- Browser: Chromium

**Code Snippet**

```javascript
// Main iframe
const elementHandle = await page.$('iframe[name="firebird"]');
const frame = await elementHandle.contentFrame();

// 2nd iframe -> Inside main iframe
const elementHandle2 = await frame.$('iframe[id="midnav-frame"]');
const frame2 = await elementHandle2.contentFrame();

// 3rd iframe -> inside 2nd iframe
const elementHandle3 = await frame2.$('#content-frame');
const frame3 = await elementHandle3.contentFrame();

console.log(await frame3.content());
```

**Describe the bug**

I am currently logging in to a website that has 3 nested iframes. 

I can get the elements of the main iframe and the 2nd iframe just fine, but when it comes to the last iframe all that I'm getting is:
```js
<html class=" firebird js flexbox flexboxlegacy rgba opacity cssgradients csstransitions csscalc"><head></head><body></body></html>
```
Looking at the developer tools this is what it looks like:
```js
<iframe name="firebird" class="border-none hidden h-full w-full absolute top-0 left-0 z-0" src="/secure/default.aspx" title="legacy" style="display: block;">
  <iframe id="midnav-frame" name="midnav" src="about:blank" frameborder="0" style="height: 466px; width: calc((100% - 256px) - 2px);">
    <iframe id="content-frame" src="about:blank" name="content" style="height: 100vh;">
    #document
    <html class="firebird js flexbox flexboxlegacy rgba opacity cssgradients csstransitions csscalc">
    <head>...</head>
    <body class="table-page">
      .....alot of html
    </body>
    </html>
    </iframe>
  </iframe>
</iframe>
```
There's supposed to be a ton of stuff inside the body which there is in the dev tools inside the iframe on the website, but not when i get the iframe through playwright.

I need to be able to manipulate the content inside the 3rd iframe, but i don't understand why it's empty when playwright catches it. Seems like a bug?

**Comment by mxschmitt** [comment]
Do you have a website where we can reproduce it? Having debug logs via setting `DEBUG=pw:protocol,pw:api` env var would also help.

**Comment by Mbensler** [comment]
It seems that the iframe had not finished loading, and therefore the contents of it was not being fetched. It worked after inserting a wait. Thanks :)
