### ISSUE TITLE
 [Feature] [test-runner] add annotation for allure-report

### ISSUE THREAD

**Issue by Belisckner** [microsoft/playwright#9128]
in #8221 already mention annotation and group for allure reports.
But closed issue and maked only steps.

Is it possible to add some annotations or methods for customizing the Allure report? It will help with link test in TMS (testops or etc.) with autotest.

it already make for mocha and some other frameworks (as example [allure-typescript-mocha](https://github.com/allure-examples/allure-typescript-mocha))
In playwright it may be as other annotations  (test.skip(), test.slow())
```
test('test name', async ({ page }) => {
    test.allure.story('story name')
    test.allure.epic('epic name')
    test.allure.issue(
          "issue-12",
          "https://github.com/allure-examples/allure-examples/issues/12"
        );
})
```

**Comment by mxschmitt** [comment]
This seems possible now see (https://github.com/allure-framework/allure-js/pull/408)

see here: https://github.com/allure-framework/allure-js/blob/master/packages/allure-playwright/README.md
