### ISSUE TITLE
User constantly getting locked out from ms-playwright process

### ISSUE THREAD

**Issue by gm3jjones** [microsoft/playwright#9130]
Hello, I have a user who is constantly getting locked out from the following process:

"process_name": "C:\\Users\\auser\\AppData\\Local\\ms-playwright\\chromium-920619\\chrome-win\\chrome.exe"

This user has no knowledge of this. How do I remove this add-on from his PC? We checked all the chrome extensions, and there were none for ms-playwright. Any assistance would be greatly appreciated!

**Comment by mxschmitt** [comment]
Does the user write end-to-end tests using Playwright? This process is a Chromium browser instance which is running in the background. So maybe a end-to-end test/script is currently running.

You could check its parent process to find out which process started it.

**Comment by mxschmitt** [comment]
Closing since this issue is answered.
