### ISSUE TITLE
[BUG] Playwright error when used on Bamboo: "Process from config.launch was not able to start. Exit code: 0"

### ISSUE THREAD

**Issue by gcatto** [microsoft/playwright#9135]
**Context:**
- Playwright Version: v1.15.0
- Operating System: Docker, mcr.microsoft.com/playwright:focal
- Node.js version: 14.17.5
- Browser: N/A
- Extra: Trying to setup Playwright tests to run in Bamboo using Bamboo's docker support

**Code Snippet**

Logs from Bamboo for it:

```
Running npm run playwright-junit

> foo@0.0.1 playwright-junit /opt/bamboo/xml-data/build-dir/CMP-SPRKCR0-JOB1
> cross-env NODE_ENV=test PLAYWRIGHT_JUNIT_OUTPUT_NAME=playwright.junit.results.xml npx playwright test --reporter=junit,line

Error: Process from config.launch was not able to start. Exit code: 0
  at Object.onExit (/opt/bamboo/xml-data/build-dir/CMP-SPRKCR0-JOB1/node_modules/@playwright/test/lib/test/webServer.js:95:43)
  at ChildProcess.<anonymous> (/opt/bamboo/xml-data/build-dir/CMP-SPRKCR0-JOB1/node_modules/@playwright/test/lib/utils/processLauncher.js:116:13)
  at Object.onceWrapper (events.js:520:26)
  at ChildProcess.emit (events.js:400:28)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foo@0.0.1 playwright-junit: `cross-env NODE_ENV=test PLAYWRIGHT_JUNIT_OUTPUT_NAME=playwright.junit.results.xml npx playwright test --reporter=junit,line`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foo@0.0.1 playwright-junit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-24T17_09_27_063Z-debug.log
```

**Describe the bug**

Playwright cannot start when used on Bamboo with Docker and does not give particularly useful error. On a different project, I've gotten it to work with jest and jest-playwright-preset, but I was hoping I did not HAVE to go that route.

**Comment by mxschmitt** [comment]
What is Bamboo? Can you provide us a repro?

**Comment by gcatto** [comment]
Bamboo is Atlassian's continuous delivery pipeline software: https://www.atlassian.com/software/bamboo

I'll see if I can find a way to put together a way to reproduce it, but it being within Bamboo makes it a bit tricky. I can run it on Windows locally fine.

I use the the `mcr.microsoft.com/playwright:focal` image. After the image checks out the code, I run the following commands:
```
// Install dependencies
npm install
// Setup/recreate the database
npm run reset-db
// Build the browser app
npm run build-dev
// Install latest playwright browser
npx playwright install
// Run playwright
// Equivalent of cross-env NODE_ENV=test PLAYWRIGHT_JUNIT_OUTPUT_NAME=playwright.junit.results.xml npx playwright test --reporter=junit,line
npm run playwright-junit
```

My playwright config is the following, although I've tried a few different variants:
```
module.exports = {

  testDir: 'test/e2e',

  webServer: {
    command: 'npm run dev',
    port: 80,
    // timeout: 120 * 1000,
    // reuseExistingServer: !process.env.CI
  },

  use: {
    baseURL: 'http://localhost',
    headless: true
  },

  workers: 1,

  projects: [{
    name: 'Chromium',
    use: {
      browserName: 'chromium'
    }
  }]
};
```

**Comment by gcatto** [comment]
I've been trying to create a simple repo on Bamboo to reproduce and thus have been unable to do so, things work so far.

I did discovered that in my real app, if I comment out the `webServer` block from my playwright config, then playwright runs (the tests just all fail, because the web server isn't running). Therefore, I think it's something about the `webServer` command for my setup.

Is there a way to get additional debugging for the web server stuff specifically?

**Comment by aslushnikov** [comment]
@gcatto do things work if you try running server separately? Could it be that your server actually launches on other port - not 80?

**Comment by gcatto** [comment]
@aslushnikov good question, I'll have to see if/how I can set that up in my Bamboo scripts. I am pretty sure that the web server uses port 80, that's what I use everywhere. When I include the `webServer` option in the Playwright config, I don't get any of the logging from my web server (I use pino) which makes it hard to know/tell for sure or to see if the server is choking on something. Is there a way to set Playwright to pass along the logs from the web server?

**Comment by gcatto** [comment]
Figured out that my web server was crashing, was able to fix it, and now everything works, so my own stupidity on display here, heh.

That being said, it would be useful to know if there's a way to propagate log messages from the Playwright's web server to the console, as that would have save me time and effort? I haven't found anything in the docs about it.
