### ISSUE TITLE
[Feature] Add current URL (from navigation bar) to trace viewer

### ISSUE THREAD

**Issue by klhex** [microsoft/playwright#9137]
Hello everyone,

We are using Playwright's screen recording functionality ("[recordVideo](https://playwright.dev/docs/videos)") for all our e2e tests when they are executed in our CI/CD environment (browser = chromium). I have noticed that the recording does not include the browser's navigation bar and therefore one cannot tell the current URL from watching the recordings.

However, it would be very handy to know which URL is used at which point in time throughout the journey of our application without retrieving this information programmatically in the test code, not least because in some situations the URL differs from when the tests are executed locally outside the CI/CD environment.

Why is the navigation bar not part of the screen recording?

**Comment by pavelfeldman** [comment]
Did you consider using trace viewer? https://playwright.dev/docs/trace-viewer/ It is like video, but interactive. We can add URL there, adding it to the video is much harder. We recommend all users that rely on video to migrate to the traces.

**Comment by klhex** [comment]
Thanks for the reminder! I know the trace viewer and I am already using it for debugging purposes, especially when the tests are executed in the background (CI/CD). And indeed for our use cases it would be perfectly fine to have the URL available in the trace viewer (i.e. in relation to each screen shot) instead of the "recordVideo" functionality. It wouldn't need to be displayed visually there (navigation bar), a simple plain text field or something like this would suffice.

(We'd still continue using "recordVideo" by default for test execution in our CI/CD environment because those screen recordings are used every now and then by our functional testers (who are from the business) whenever they want to check what was going on during the execution of a specific e2e test. But for this use case they wouldn't need to see the current URL, that's only relevant for us tech people for analyses/debugging.)

Therefore, I am converting this issue into a feature request regarding URL @ trace viewer.

**Comment by klhex** [comment]
@yury-s Since you've added the trace-viewer label to several corresponding issues lately, could you do the same for this one? 😏
