### ISSUE TITLE
[Question] Good way to implement common page components?

### ISSUE THREAD

**Issue by TimeInvestor** [microsoft/playwright#9144]
In Playwright's doc, there is great mentioning on Page Object Model. However, when I try to follow this model (using TypeScript), I encounter a problem. For common page components, like menu or navigation bar, which appreas on every page on my website, if I create web elements for them in each page object, there will be lots of duplications.
So what's a good way to implement such common components to avoid duplications?

**Comment by mxschmitt** [comment]
> For common page components

do you mean in terms of behaviour?

You could extract the logic of these into own classes and then just create instances of them inside your actual POMs. For example a selection control. Input parameter: The locator and you then have functions on it to set an item or clear them.

Let us know if you have other questions.

**Comment by TimeInvestor** [comment]
Thanks for your advice.
I was reading some articles online. Some said, for common page elements or page fragments, I should follow composite (over inheritence) pattern. As I am very new to TypeScript, I am not sure how to exactly implement that pattern.
It would be like if we can add an example in the Playwright doc to illustrate how to handle common page elements/fragments under the "Page Object Model" section.

**Comment by sidharthv96** [comment]
This would be a simple implementation of composite pattern.
We are creating standalone classes which can be bundled together (composition) and used.

I do agree that few examples in the docs or link to an example repo would be really helpful, especially for people without much experience in writing good, maintainable and extendable e2e tests.
I personally had to search github for repos which had playwright in their dependencies to get some idea into structuring tests.

## /common/navbar.ts
```ts
import type { Page } from "@playwright/test";

export class NavBar {
  readonly page: Page;
  constructor(page: Page) {
    this.page = page;
  }

  async goHome() {
    await this.page.click("text=Home");
  }

  async search(query: string) {
    await this.page.fill('input[type="text"]', query);
    await this.page.click("text=Search");
  }
}
```

## /home.ts
```ts
import type { Page } from "@playwright/test";
import { NavBar } from "./common/navbar";
export class HomePage {
  readonly page: Page;
  readonly navbar: NavBar;
  constructor(page: Page) {
    this.page = page;
    this.navbar = new NavBar(page);
  }

  async action1() {
    await this.navbar.search("hello");
    ...
  }

  async action2() {
    ...
    await this.navbar.goHome();
  }
}
```

**Comment by TimeInvestor** [comment]
Thanks @sidharthv96 for great example 👍 . Now I have idea how to start😄

**Comment by Bessonov** [comment]
Another way to reduce boilerplate code is creation of fixture:

```ts
import { Page, test as base } from '@playwright/test'
import { StartpagePage } from '../startpage/StartpagePage'

class Pages {
	// example of one page; wow, wasn't aware of this way of declaration
	public readonly startpage = new StartpagePage(this.page)

	// allows access to `page` through `pages.page`
	constructor(public readonly page: Page) {
	}
}

export const test = base.extend<{ pages: Pages, login: () => Promise<void> }>({
	pages: ({ page }, use) => use(new Pages(page)),
	// example of an utility function
	login: ({ pages }, use) => use(async () => {
		await pages.startpage.go()
		await pages.startpage.login()
	}),
})
```

Now usage:

```ts
import { expect } from '@playwright/test'
import { test } from '../Pages'

test('my test', async ({ pages, login }) => {
	// now you can use this one
	await test.step('login', login)
	// or this one
	await test.step('login', async () => {
		await pages.startpage.go()
		await pages.startpage.login()
	})
})
```

I use it more hierarchically, but the core idea is simple.

Question: Which is the best way to extend the page object/interface, so I can use `page.login()`? I can think of delegation + Proxy, but it doesn't feel right.
