### ISSUE TITLE
PLaywright with executable Electron app, does it work?

### ISSUE THREAD

**Issue by LucasSantosSilva** [microsoft/playwright#9145]
I have a executable in Electron app (not the code or project) I see in the Electron that have a function that execute the application (`executablePath `- https://playwright.dev/docs/api/class-electron). I used the example code, but return `not found tests`.

When execute using Playwright inspector it even opens the executable but when click em record nothing happens

```
    const { _electron: electron } = require('playwright');
    const { test, expect} = require('@playwright/test');

(async () => {
  const electronApp = await electron.launch({ executablePath : './myexecutable.exe' });

  const appPath = await electronApp.evaluate(async ({ app }) => {
    return app.getAppPath();
  });
  const window = await electronApp.firstWindow();
  await window.click('text=Click me');
  await electronApp.close();
})();
```

**Comment by mxschmitt** [comment]
Its not supported yet, see here: https://github.com/microsoft/playwright/issues/8208 Closing as a duplicate.

Depending on your situation, you can launch your electron app e.g. for every test and use a beforeEach (test fixture) for it or launch it for every file only (beforeAll). See here: https://playwright.dev/docs/test-fixtures

Once doing that you then can access the window or the Electron App itself.
