### ISSUE TITLE
[Question]Playwright not able to find test in the folder

### ISSUE THREAD

**Issue by Sauravpersonal08** [microsoft/playwright#9146]
I am facing issue with configuration of playwright. Test scenarios is placed under the project directory but during execution it shows no tests found

npm i -D @playwright/test
npx playwright install
Execution : npx playwright test

![PlaywrightClass](https://user-images.githubusercontent.com/52004006/134769378-a2a721bb-47e3-45cf-a237-ab35e1f743a9.png)

**Comment by mxschmitt** [comment]
You need to call the file `foo.test.js` or `foo.spec.js`. It matches by default against `**/*.{spec,test}.{js,ts}` see here: https://playwright.dev/docs/api/class-testconfig#test-config-test-match

**Comment by Sauravpersonal08** [comment]
Thanks for your reply. Tried with the same , same issue

![PlaywrightClass2](https://user-images.githubusercontent.com/52004006/134771050-333cd5e1-1922-4410-9dc4-1196476d7929.png)

**Comment by mxschmitt** [comment]
You need to rename your files to e.g. `first.test.js` or `second.test.js`.

**Comment by Sauravpersonal08** [comment]
> You need to rename your files to e.g. `first.test.js` or `second.test.js`.

Thanks :)
