### ISSUE TITLE
[Question] Is telemetry enabled in chrome?

### ISSUE THREAD

**Issue by shirshak55** [microsoft/playwright#9152]
Afaik in firefox telemetry is disabled but in chromium browser I see lot of things calling to the google server which is unnecessary in my opinion?  Because it consumes unnecessary data etc?

So to prove what I did was run a headless browser and used the net export feature. 
![Screenshot from 2021-09-26 10-58-19](https://user-images.githubusercontent.com/8097377/134794621-c400b73b-3514-4ee1-aa6f-f2c5ba55acca.png)

**Comment by aslushnikov** [comment]
Well, we disable something, but IIUC there's no global chromium switch to disable all of it. 🤷‍♂️

**Comment by shirshak55** [comment]
@aslushnikov I mean at least we can patch the browser we use and remove these url? Will you accept PR that does it?
