### ISSUE TITLE
[Feature] support ublock origin's cosmetic filtering selectors

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#9153]
https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters

these selectors are very useful, it would be cool if playwright supported them all

**Comment by DetachHead** [comment]
the `matches-css` one would be nice

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
