### ISSUE TITLE
[BUG] - Not able to install Playwright 1.15

### ISSUE THREAD

**Issue by saivarma576** [microsoft/playwright#9157]
Hi Team,
can u please look into this 
It's got stuck at this place with installing, I had tried multiple times as well 

D:\Automation Projects_FE\lnt_s1_fe-automation>npm i
[##############....] / reify:open: timing reifyNode:node_modules/is-wsl Completed in 188ms
[](url)
![2021-09-26_23-39-59](https://user-images.githubusercontent.com/67151480/134819360-e88f9fd9-45cb-484f-a93e-017ef2b171b0.png)

**Comment by mxschmitt** [comment]
Could you set the following environment variable and see if then more verbose output will appear?

```ts
set DEBUG=pw:install
npm install --foreground-scripts playwright
```

**Comment by aslushnikov** [comment]
Additionally, you can try running `npx playwright install`. This way you'll see if there's any progress in browser downloads.

**Comment by mxschmitt** [comment]
Closing since the issue seems stale. Please open a new one if you still encounter it.
