### ISSUE TITLE
[Question] How to wait for content change

### ISSUE THREAD

**Issue by A-ZC-Lau** [microsoft/playwright#9163]
So for the following html file

```html
<html>
	<body>
		<div id="message">
			Sending your request...
		</div>
	</body>
</html>

<script>
	setTimeout(
		() => {
			document.querySelector("#message").innerText = "Thanks, your request was received"
		},
		3000
	)
</script>
```

How would I check when the text is completed/changed so I may continue the test as needed? This is what I currently have, and it fails. fiddle: https://jsfiddle.net/41bLswqg/

```javascript
import { test } from "@playwright/test";

test("should find the right a", async ({ page, context }) => {
	await page.goto("https://jsfiddle.net/41bLswqg/");
	const frame = await page.frame("result");
	
	const text = await frame.locator("#message").textContent();
	
	test.expect(text).toBe("Thanks, your request was received");
})
```

In Cypress, this can be very easily done via:

```javascript
/// <reference types="cypress" />

it("should have the right count", () => {
	cy.visit("assets/example.html");

	cy.get("#message").should("have.text", "Thanks, your request was received")
});
```

And while I'm asking, would there be a way to wait and check that the number of elements are correct? I.e. `elementHandle.count === 3`. E.g. the number of `<li>` that populates a `<ul>` are dynamic and you want to wait until x number shows up before proceeding with tests on their content.

**Comment by mxschmitt** [comment]
You can do the following:

```ts
const locator = page.locator('#message');
await expect(locator).toHaveText("Thanks, your request was received");
```

This will automatically internally retry, see here for more information:

- https://playwright.dev/docs/test-assertions#expectlocatortohavetextexpected-options
- https://playwright.dev/docs/test-assertions#matching

**Comment by A-ZC-Lau** [comment]
@mxschmitt Thanks, worked perfectly. Didn't realize that the expects would also contain auto assertions.

And I think the reason why I overlooked this was because I thought expect was just like the Jest expect, and didn't realize it was extended.

Perhaps add an additional function to Locator that does this automatically? Could just basically copy Cypress.

I.e.

```javascript
await page.locator('#message').should("toHaveText", "Thanks, your request was received");
```

Feel free to close when it suits your process.

**Comment by aslushnikov** [comment]
> Perhaps adding an additional function to Locator would help prevent this confusion? Could just basically copy Cypress.

We keep Playwright library free of assertions, and put all assertions and expects to Playwright Test (thus an extended `expect`).
