### ISSUE TITLE
[Question] How to clear Session and Local Storage ?

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#9164]
I need to test my application by clearing Session and Local Storage during test run.

I went through the documentation but didn't find any method to do this.

Appreciate if you could guide me how to achieve this.

**Comment by mxschmitt** [comment]
You can do the following:

```ts
await page.evaluate(() => window.localStorage.clear());
await page.evaluate(() => window.sessionStorage.clear());
```

(If its about re-using a browser context, we recommend that a new one gets created for each test since the creation of a browser context is cheap and is isolated out of the box)

**Comment by vsravuri** [comment]
Thanks @mxschmitt 

I am testing visitor journey with shopping cart.

I have overwritten the context options fixture like this.

base-fixture.js
```javascript
const base = require("@playwright/test");
module.exports = base.test.extend({
    custContextOptions: [ {}, { scope: "worker" } ],
    custContext: [
        async ({ browser, custContextOptions }, use) => {
            const custContext = await browser.newContext(custContextOptions);
            await use(custContext);
        },
        { scope: 'worker', auto: true },
    ],
    custPage: [
        async ({ custContext }, use) => {
            const custPage = await custContext.newPage();
            await use(custPage);
        },
        { scope: 'worker', auto: true },
    ],
}
```
I have two spec files. In each of these spec files i tried to use **custPage & custContext**. Everything works fine in spec1. If i close the context (custContext) at the end of first spec file, i see new context is created with blank page and test stops saying page doesn't exist. If i don't close the context at the end of spec1, the context is reused in spec2. I thought if i close the context in spec1, a brand new context will be re-created and test continue similar to spec1. Clearing the storage works for my scenario.

```javascript
spec1.js

const test = require('../../base-fixture');
....
```

```javascript
spec2.js
const test = require('../../base-fixture');
....
```

**Comment by aslushnikov** [comment]
> If i close the context (custContext) at the end of first spec file, i see new context is created with blank page and test stops saying page doesn't exist.

@vsravuri Your custom fixtures are created with a "worker" scope - which means they won't be re-created for each test, so I don't understand how this is possible.

Can you show your test as well?

**Comment by vsravuri** [comment]
@aslushnikov I mean to say new in second spec file, it fails saying page doesn't exist. Kindly correct me if I'm doing something wrong here.

I expected spec2 will continue after spec1.

```javascript
const config = {
        workers: 1,
        globalTimeout: 0,
        reporter: [
            ['list']
        ],
        projects: [{
            name: 'Chromium',
            testDir: './test',
            testMatch: '*.test.spec.js',
            timeout: 0,
            retries: 0,
            use: {
                browserName: 'chromium',
                channel: 'chrome',
                headless: false,
                viewport: {width: 1600, height: 825},
                ignoreHTTPSErrors: true,
            }
        }]

    };
    module.exports = config;
```

```javascript
const base = require("@playwright/test");
module.exports = base.test.extend({
    custContext: [
        async ({ browser }, use) => {
            const custContext = await browser.newContext();
            await use(custContext);
        },
        { scope: 'worker', auto: true },
    ],
    custPage: [
        async ({ custContext }, use) => {
            const custPage = await custContext.newPage();
            await use(custPage);
        },
        { scope: 'worker', auto: true },
    ]
});
```

```javascript
pw2.test.spec.js
const test = require('../base-fixture-demo');
test.describe.serial('Spec1', () => {
    test('Spec2', async ({ custPage,custContext }) => {
        await custPage.goto('https://ace.c9.io/');
        await custPage.click('.ace_content');
        await custPage.type('textarea', 'Testing1\n\n');
        custPage.close();
        custContext.close();
    });
});
```

```javascript
pw2.test.spec.js
const test = require('../base-fixture-demo');
test.describe.serial('Sepc2', () => {
    test('Sepc2', async ({ custPage,custContext }) => {
        await custPage.goto('https://ace.c9.io/');
        await custPage.click('.ace_content');
        await custPage.type('textarea', 'Testing2\n\n');
        custPage.close();
        custContext.close();
    });
});
```

```javascript
 page.goto: Target page, context or browser has been closed
```

**Comment by aslushnikov** [comment]
@vsravuri These tests you show here will be just fine without the fixtures you have out-of-the-box:
- Just drop your custom fixtures altogether
- And you probably don't need the `.serial` mode

```js
const test = require('@playwright/test');
test.describe('Spec1', () => {
    test('Spec1', async ({ page }) => {
        await page.goto('https://ace.c9.io/');
        await page.click('.ace_content');
        await page.type('textarea', 'Testing1\n\n');
    });
    test('Spec2', async ({ page }) => {
        await page.goto('https://ace.c9.io/');
        await page.click('.ace_content');
        await page.type('textarea', 'Testing2\n\n');
    });
});
```

**Comment by vsravuri** [comment]
Thanks

**Comment by GeenCo86** [comment]
I have a similar question. If I use the [authenticate flow](https://playwright.dev/docs/auth) you describe and save the token into the json file. How do I clear the files content or specific part of the localstorage inside the file at teardown.

```
const authFile = 'playwright/.auth/user.json';
await page.context().storageState({ path: authFile });
```

So I would like to change the localStorage values inside the user.json in my teardown
