### ISSUE TITLE
[Question] test.describe.parallel(title, callback) not working?

### ISSUE THREAD

**Issue by DvDream** [microsoft/playwright#9165]
Hi, I'm trying to run several micro tests into a single file in parallel. I've found the test.describe.parallel function but when I write it I get this error:

`
Property 'parallel' does not exist on type 'SuiteFunction & { only: SuiteFunction; serial: SuiteFunction & { only: SuiteFunction; }; }'.ts(2339)`

why this? I'm following the same structure which is described in the documentation. Thank you!

**Comment by mxschmitt** [comment]
Are you using version 1.15+?

**Comment by DvDream** [comment]
> Are you using version 1.15+?

1.14.1

**Comment by DvDream** [comment]
> test.parallel was introduced in 1.15. So you need 1.15+

Is it possible to update it from the command line? Sorry for the trivial question but I'm quite new with playwright :)

**Comment by mxschmitt** [comment]
```
npm install -D @playwright/test@latest
```

**Comment by DvDream** [comment]
> ```
> npm install -D @playwright/test@latest
> ```

Thank you so much, solved it! :)
