### ISSUE TITLE
[Feature] Add `suite` as a parameter to onEnd() method of Reporter API

### ISSUE THREAD

**Issue by sb-michal-murray** [microsoft/playwright#9170]
This will enable more generic integration with e.g. TeamCity, which uses [service messages](https://www.jetbrains.com/help/teamcity/service-messages.html#Supported+test+service+messages)

what is:
```ts 
onEnd?(result: FullResult): void | Promise<void>;
```

what should be 
```
onEnd?(result: FullResult, suite: Suite): void | Promise<void>;
```

**Comment by mxschmitt** [comment]
Does this work for you?

```ts
class YourReporter {
  private config!: FullConfig;
  private suite!: Suite;

  onBegin(config: FullConfig, suite: Suite) {
    this.config = config;
    this.suite = suite;
  }

  async onEnd() {
    console.log(this.suite);
  }
```

**Comment by sb-michal-murray** [comment]
yep, i tried to use it as class fields, but to no avail. the message like above will give `undefined` in stdout
