### ISSUE TITLE
[Question] How to make test retried in `for` loop same as original?

### ISSUE THREAD

**Issue by sb-michal-murray** [microsoft/playwright#9177]
Let's say i have loop and test data generator function like that:

```
test.describe('Tests...', () => {
  for (const item of getRandomSampleForTest()) {
    test(`${item.name} test`, async ( { page } ) => {
      await doSomething(page)
    })
  }
})
```
With retry set to nonzero value i'd like playwright/test to retry this specific test case, not to run the loop again (probably retrying the whole `describe`?)
How would i do it?

**Comment by pavelfeldman** [comment]
It'll rerun the for loop, but it will only retry the failed test.
