### ISSUE TITLE
[Question] Worker Fixtures with Account Logins

### ISSUE THREAD

**Issue by AAAstorga** [microsoft/playwright#9178]
Hello, I had a question about how worker fixtures work with the context of logging into accounts.
I run my tests on CI with 4 workers, so I expected my worker fixture to retrieve login credentials and store `storageState` to only run 4 times. Here is a code snippet:
```typescript
type WorkerFixtures = {
    userAccount: StorageState;
};

export const test = base.extend<Fixtures, WorkerFixtures>({
    // Inject the storage account into context so we don't have to sign in
    storageState: async ({ userAccount }, use) => {
        await use(userAccount);
    },

    userAccount: [
        // eslint-disable-next-line no-empty-pattern
        async ({}, use) => {
            const [user, storageState] = await checkoutAndSignInUser();

            await use(storageState);

            // Clean up
            await checkinUser(user);
        },

        { scope: 'worker' },
    ],
    ...
```

As you can see for the `userAccount` fixture, I checkout a user from an internal service that allows you to use a username/password in your tests and checks out those credentials so another test does not also try to use those same credentials since our site has some specific limitations around the same user on different devices/browsers trying to do things at the same time.

After checking out the user, we sign in the user through a long, out of our control, auth process that eventually gets the `storageState` of the browser so with future tests we can just inject the `storageState` with all the cookies, etc so the user is already signed in.

This is great and works as expected. The issue starts to appear when a test fails. From what I can tell, if say Worker1 ran a test that failed, then that whole worker will be teared down and then another worker will be created and that new worker will run through the `userAccount` fixture. I understand the reasoning behind this approach since failed tests can put things in an undefined state.

The problem is our `checkoutAndSignInUser` flow is completely irrelevant to the test and I would only like to checkout and sign in 4 users (when using 4 workers) only no matter how many tests failed. This is because our `checkoutAndSignInUser` flow is long and some auth services we depend on are quite old and sometimes can be flakey so the less we have to `checkoutAndSignInUser`s the better. 

How can I accomplish this? Do I need to write the `storageState` to disk and somehow determine if a worker is being recreated and try to retrieve some storageState on disk? Not sure how that would work since `workerIndex` is unique from what I understand. As in if `Worker1` with an workerIndex of 1 failed, the new worker created would not have a `workerIndex` of 1 anymore.

Please let me know how I can solve this problem. Let me know if you have any more questions. Thank you!

**Comment by dgozman** [comment]
@AAAstorga If we expose something like `workerParallelIndex` that is between `0` and `workers - 1`, would that help?

**Comment by AAAstorga** [comment]
@dgozman yes that would work. That would allow me to reuse credentials properly. Thank you!
