### ISSUE TITLE
[Question] How to increase the speed of locator.type ?

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#9187]
I am automating Ace Editor (https://ace.c9.io/).

While typing noticed a difference between locator.type and locator.fill.

My understanding is fill is equivalent to copy & paste as the text is injected into the input field whereas type is equivalent to user typing the keyboard. I am unable to validate the editor using locator.fill as it's not triggering the editor events. When i use locator.type, the default typing seed is too slow. To type one line in the editor it took one minute for me. Same thing i achieved using Protractor in few seconds using element.sendKeys method.

locator.type documentation has option to delay typing. I didn't find option to increase the typing speed.

Appreciate if you could guide me if it's possible to increase the locator.type speed using Playwright.

**Comment by aslushnikov** [comment]
@vsravuri I just tried the following snippet and it was instant for me:

```js
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({
    headless: false,
  });

  const page = await browser.newPage();
  // Go to https://ace.c9.io/
  await page.goto('https://ace.c9.io/');

  // Click .ace_content
  await page.click('.ace_content');

  // Fill textarea
  await page.type('textarea', 'asdfasdfa sdflk ajsdlfjasldkfjalskdjflaksdjflkasdjflaskdjflaksd\n\n');
})();
```

A script repro will be very helpful!

**Comment by vsravuri** [comment]
@aslushnikov Thanks for looking into this issue. I'm working on getting a repro script.

**Comment by vsravuri** [comment]
@aslushnikov Thank you! i figured out the problem is with my code. I used slowMo in launchOptions to handle flaky tests, this made the typing to slow down. Closing this ticket.
