### ISSUE TITLE
[BUG] version `GLIBC_2.18' not found while launching Chromium, with v1.15.0

### ISSUE THREAD

**Issue by gkushang** [microsoft/playwright#9194]
**Context:**
- Playwright Version: 1.15.0
- Operating System: Docker CentOS 7
- Node.js version: 14.16
- Browser: Chromium
- Extra: It's our Jenkins CI environment where we install Playwright Browsers in the Docker (centOS7)

**Describe the bug**

The issue started happening when we upgraded Playwright from `1.11.1` to `1.15.0`. It does not launch the `chromium` browser and throws an error,

```
[pid=4303][err] /usr/lib/playwright/chromium-920619/chrome-linux/chrome: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /usr/lib/playwright/chromium-920619/chrome-linux/chrome)
```
When I switch back to `v.1.11.1`, everything works fine but `v1.15.0` needs `GLIBC_2.18` on CentOS7. This is blocking us from upgrading.

[Playwright Slack Thread ](https://playwright.slack.com/archives/CSUHZPVLM/p1632772749420200)with @pavelfeldman 

How do we resolve this issue?

**Comment by aslushnikov** [comment]
@gkushang first of all, disclaimer: we don't officially support centOS – so it's all "best effort" here.

Now, it might be that Chromium changed something upstream, or it might be some change in our infrastructure.

To validate, can you please try downloading and running roughly the same Chromium build on CentOS? 

```bash
wget https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/920625/chrome-linux.zip
```

**Comment by udit0802** [comment]
I am also facing the same issue on our jenkins CI with similar configurations as mentioned above.

**Comment by udit0802** [comment]
> @udit0802 please try downloading & running the chromium build on this configuration:
> 
> 
> ```shell
> wget https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/920625/chrome-linux.zip
> ```

Could you please guide with the steps, are any changes required in the configuration of playwright from my end, or do you want me install manually this zip on centos machine?

**Comment by aslushnikov** [comment]
OK I already check it in the Docker's centos:centos7 image. 

Turns out Chromium bumped it's GLIBC revision; I bisected it down to this range: https://chromium.googlesource.com/chromium/src/+log/08c30cf9e1370433a06980161e2b754c4b903e98..f61b6ea07f5050320e886b862379fdc8e36b3286

Anyway, there are no plans to support CentOS right now; if you'd like one, please file a separate issue requesting CentOS! If it gets lots of demand, we'll prioritize it!

**Comment by joker4786** [comment]
Is this issue also comes in windows agent in Jenkins

**Comment by 2dareis2do** [comment]
As mentioned Chromium seemed to bump the this the middle of 2001. I was able to install a version that predates this on an older version of Centos. 

e.g. pip install --force-reinstall -v playwright==v1.10.0

**Comment by 2dareis2do** [comment]
playwright 1.10 is missing loads of features. For me I was able to get the features I wanted by installing with a later version
`pip3 install playwright==1.30.0`

As mentioned I previously tried to install the latest version (1.44.0) I also received `version `GLIBC_2.27' not found` error

When downloading a version (after x and before y) I get the following when using `python3 -m playwright install`

```
BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
Downloading Chromium 110.0.5481.38 (playwright build v1045) from https://playwright.azureedge.net/builds/chromium/1045/chromium-linux.zip
141.7 Mb [====================] 100% 0.0s
Chromium 110.0.5481.38 (playwright build v1045) downloaded to /root/.cache/ms-playwright/chromium-1045
BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
Downloading Firefox 108.0.2 (playwright build v1372) from https://playwright.azureedge.net/builds/firefox/1372/firefox-ubuntu-20.04.zip
77.8 Mb [====================] 100% 0.0s
Firefox 108.0.2 (playwright build v1372) downloaded to /root/.cache/ms-playwright/firefox-1372
BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
Downloading Webkit 16.4 (playwright build v1767) from https://playwright.azureedge.net/builds/webkit/1767/webkit-ubuntu-20.04.zip
89.8 Mb [====================] 100% 0.0s
Webkit 16.4 (playwright build v1767) downloaded to /root/.cache/ms-playwright/webkit-1767

```
If I understand correctly it is downloading the Ubuntu version of the build. 1.30 was working for me. Somewhere between 1.40 and 1.44 the installation breaks, specifically "version `GLIBC_2.27' not found` error"

I believe there are workarounds ti enable GLIBC_2.27 or later but reading other comments, if you are not sure what you are doing, could lead to your server being unable to start. Not sure, but not something I really understand the implications of.
