### ISSUE TITLE
[BUG] CircleCI Chromium console doesn't return values

### ISSUE THREAD

**Issue by alisterscott** [microsoft/playwright#920]
**Context:**
- Playwright Version: 0.10.0
- Operating System: macOS
- Extra:  this happens on CircleCI node 13.8.0

Link: https://circleci.com/gh/alisterscott/playwright-demo/23

**Code Snippet**

```javascript
import assert from 'assert';
import playwright from 'playwright';
import config from 'config';

const mochaTimeoutMS = config.get( 'mochaTimeoutMS' );

// Doesn't work on CircleCI
describe( 'Playwright 4', function() {
	this.timeout( mochaTimeoutMS );

	let browser, context;

	before( async function() {
		browser = await playwright.chromium.launch();
		context = await browser.newContext();
	} );

	it( 'can check for console errors when there are present', async function() {
		const page = await context.newPage();
		let errors = '';

		page.on( 'console', msg => {
			if ( msg.type() === 'error' ) {
				errors = errors + msg.text();
			}
		} );
		await page.goto( 'https://webdriverjsdemo.github.io/error' );
		assert( errors.indexOf( 'Purple Monkey Dishwasher Error' ) > -1 );
	} );

	after( async function() {
		await browser.close();
	} );

} );

```

**Describe the bug**

When running this test on CircleCI the console errors is empty, whereas locally on same browser it is able to extract the errors.

**Comment by pavelfeldman** [comment]
Your page does not do `console.error`, it throws. So you want to use [pageerror](https://github.com/microsoft/playwright/blob/v0.10.0/docs/api.md#event-pageerror) event instead:

```js
page.on('pageerror', error => {
  errors = errors + error.message;
});
```

`page.on('console')` is emitted upon `console.*` calls, whereas `page.on('pageerror')` is triggered when [`window.onerror`](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror) fires. DevTools would show them similarly in console, but these are different things. Not sure why it worked for you locally.

Please feel free to reopen if this did not address the issue.

**Comment by alisterscott** [comment]
Thanks, this works. The old code worked in Puppeteer
