### ISSUE TITLE
Can't install unsigned extensions in Firefox

### ISSUE THREAD

**Issue by HMaker** [microsoft/playwright#9202]
In Firefox Nightly unsigned extensions [can be installed][1]:
> What are my options if I want to install unsigned extensions in Firefox?
The Nightly and Developer Edition versions of Firefox have a preference to disable signature enforcement. There are also be special unbranded versions of Release and Beta that have this preference, so that add-on developers can work on their add-ons without having to sign every build. To disable signature checks, you will need to set the xpinstall.signatures.required preference to "false".

I started playwright with firefox preference `xpinstall.signatures.required` set to false, I could see it was set in `about:config`, but Firefox launched by playwright still refuses to install unsigned extensions. Looking at the About menu, it says it's Firefox Nightly 92.0, why it does not accepts unsigned extensions? I tried installing same unsigned extension in official Nightly 93.0 and it worked.

I tried it with playwright-firefox 1.15 on Ubuntu 18.04.

To reproduce it take any extension, say `extension.xpi`, and remove its signature:
```bash
mkdir unpacked-extension
unzip -q extension.xpi -d unpacked-extension
rm -rf unpacked-extension/META-INF
cd unpacked-extension
zip -q -r -FS ../unsigned-extension.xpi *
cd -
```
create a profile folder and add that extension
```bash
mkdir -p profile/extensions
cp unsigned-extension.xpi profile/extensions
```
then launch a persistent firefox browser context and pass `profile` to `userDataDir`.

[1]: https://wiki.mozilla.org/Add-ons/Extension_Signing

**Comment by aslushnikov** [comment]
We actually build Firefox with build config identical to the stable build; it's curious that it still reports it as nightly. 

We do have internal Firefox beta builds that you can use as a `channel: "firefox-beta"` and installing them with `npx playwright install firefox-beta`. 

**HOWEVER!** We do not commit to supporting these builds; these are used for our own purposes, and if our needs change in future then we might stop doing them. So please consider them as a best-effort.

**Comment by HMaker** [comment]
Since playwright is meant for test automation could not unsigned extensions installation be allowed like it is in official Nightly?

**Comment by aslushnikov** [comment]
I'll look into this!

**Comment by HMaker** [comment]
Thanks, what need to be done for installation of unsigned extensions be supported?

**Comment by sublimator** [comment]
You may find of interest:
You can use --marionette protocol to install temporary add-ons into a running Firefox
Example code here:  https://github.com/deepsweet/foxr

**Comment by sublimator** [comment]
To be clear, I don't know if this will work with the Playwright builds of FF, but it could be worth trying:
https://github.com/deepsweet/foxr/blob/master/src/api/Browser.ts#L53-L60

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
