### ISSUE TITLE
Playwright SelectOption is not selecting a value

### ISSUE THREAD

**Issue by TheChosenQA** [microsoft/playwright#9203]
When attempting to use page.SelectOption with Playwright, im getting an issue where my chosen value is not being selected, it doesnt matter if I use index, value, or label to try to select.

I know the selector is being found as when I debug using trace viewer I cant see that the step shows:
![image](https://user-images.githubusercontent.com/45701241/135161304-75f33eb4-0d31-45fb-b4d8-e1c0631a813b.png)

However on the select box it doesn't change and acts like it hasn't selected anything.

![image](https://user-images.githubusercontent.com/45701241/135161352-16ecf03a-1360-42b0-b7c5-f4366a5ef720.png)

code used: 
```await page.selectOption('#select', "2");```

Does anyone have any ideas or any possible work arounds?

**Comment by udit0802** [comment]
const selector = await page.$("#select")
await selector?.selectOption("2")

I use this and it works.

**Comment by TheChosenQA** [comment]
> const selector = await page.$("#select")
> await selector?.selectOption("2")

I just tried this and the same happens, you can see it tries to select it, but when viewing in trace viewer it still does not select the option

**Comment by TheChosenQA** [comment]
This actually is working, I think there is a bug with Trace viewer not showing the selected text from a dropdown.
