### ISSUE TITLE
[Question] Is there any option to search frames not only by name or url? 

### ISSUE THREAD

**Issue by orihomie** [microsoft/playwright#9209]
I've tried to search by "frameSelector" passing xpath and css selectors but none worked meanwhile when I've passed frame's `name` by `{ name: "frameName" }` I've got that frame. 

So, I'm looking for something like a method which args are:
`attribute` - attribute to find element (in this case it is `name`, but could be any of DOM element attributes)
`attributeValue` - attribute value, in this case `frameName`

so it would look like
```js
page.frame( { attribute: 'name', attrubuteValue: 'frameName' } )
```

**Comment by TimeInvestor** [comment]
Hi @orihomie 
You can also use a frame's url to find it.
`const frame = page.frame({ url: /.*domain.*/ });`
Refer to https://playwright.dev/docs/api/class-page#page-frame

**Comment by orihomie** [comment]
The frame I'm looking for has no url, only src attribute.

**Comment by aslushnikov** [comment]
@orihomie frame's src sets up frame's URL.

**Comment by orihomie** [comment]
Src is the property frame would always have, wouldn't it?

**Comment by orihomie** [comment]
Ok, I'll give it a try with a bit note - its not just list, but a tree, so such an option would take a heavy while.

**Comment by aslushnikov** [comment]
> Ok, I'll give it a try with a bit note - its not just list, but a tree, so such an option would take a heavy while.

Should be pretty instant anyway!

**Comment by orihomie** [comment]
No, it didnt worked

```js
async function filterFramesByAttribute(page: Page, attributeName: string, attributeValue: string) {

  const result = [];

  const frameFilter = async (frames: Array<Frame>) => {

    for (const frame of frames) {
      if (frame.isDetached()) {
        continue;
      }

      const handle = await frame.frameElement();
      const value = await handle.getAttribute(attributeName);

      if (value === attributeValue)
        result.push(frame);

      if (frame.childFrames()) {
        await frameFilter(frame.childFrames());
      }
    }
  }

  await frameFilter(page.frames());

  return result;
}
```

> frame.frameElement: Frame has been detached.

**Comment by aslushnikov** [comment]
@orihomie I'm happy you found your solution!

For the sake of completeness: you don't need to recurse using `frame.childFrames()` - [`page.frames()`](https://playwright.dev/docs/api/class-page/#page-frames) method already returns **all frames, flattened** for you. 

Since we do operations asynchronously, we indeed have to handle frame detachment. I updated [the answer here](https://github.com/microsoft/playwright/issues/9209#issuecomment-930220020) - should work now.

> What about extending PW's API by page.frameByAttribute function?

Makes sense; let me file this separately as a feature request. Closing this in favor of https://github.com/microsoft/playwright/issues/9227

**Comment by orihomie** [comment]
@aslushnikov
Then it seems there's a bug with `page.frames()`:

```js
export async function flattenFrameTree(frames: Array<Frame>) {
  const result = [];

  for (const frame of frames) {
    try {
      if (!result.includes(frame)) {
        result.push(frame);
      }

      if (frame.childFrames()) {
        result.push(...(await flattenFrameTree(frame.childFrames())));
      }
    } catch (e) {}
  }

  return result;
}
```
![image](https://user-images.githubusercontent.com/29889683/135417262-85b814ac-217e-44c8-8f79-0ec5b5954bba.png)
