### ISSUE TITLE
[Question] Is there a way to check what headers you're sending when using `.request`

### ISSUE THREAD

**Issue by A-ZC-Lau** [microsoft/playwright#9210]
Is there a way to check to see what headers are in the request when using `page._request`? I tried using a `page.route` with it, but it never checks it (which I assume is intentional).

The journey is:
1. I've logged onto a certain page
2. Then try calling a certain API with a payload to create something
3. But I receive an error 401 Unauthorized

So I want to see what kind of headers are being sent.

Here's what I'm doing (sorry no re-creatable urls and such)

```javascript
function HANDLE_ROUTE(route : Route, request : Request) {
    request.allHeaders().then((headers) => {
        console.log(headers);
    });
    chalk.blueBright(request.postData());
    route.continue();
}

test.only("test request headers", async ({ page }) => {
    const apiUrl = /* some url */;
    await page.route(apiUrl, HANDLE_ROUTE);
    const payload = CREATE_PAYLOAD("Old");
    const response = await page._request
        .post(
            apiUrl, 
            {
                data : JSON.stringify(payload),
            },
        );
    console.log(response.status());
    const buffer = await response.body();
    console.log(response.headers());
    // console.log(buffer.toString());
});
```

**Comment by yury-s** [comment]
> Is there a way to check to see what headers are in the request when using `page._request`?
Currently we don't expose access to the request (and its headers) that was sent. If it just for debugging perhaps we can add logging for the requests to print out such information.

> I tried using a `page.route` with it, but it never checks it (which I assume is intentional).
> 
Yes, this is intentional, the request doesn't go through the browser and cannot be intercepted by its instrumentation.

> 3. But I receive an error 401 Unauthorized
> 
Looks like you need to provide [`httpCredentials`](https://playwright.dev/docs/api/class-browser#browser-new-context) when creating the test context, you could use [testOptions](https://playwright.dev/docs/api/class-testoptions#test-options-http-credentials) for that. Would that work?

**Comment by A-ZC-Lau** [comment]
@yury-s The the request I'm sending requires a JWT in its `authorization` header. From the API page https://playwright.dev/docs/api/class-page/#page-request it reads

> API testing helper associated with this page. Requests made with this API will use page cookies.

So I thought logging in and sending a request from that page would result in the correct headers being passed, which I guess isn't the case?

The login also uses AWS Cognito.

**Comment by yury-s** [comment]
> So I thought logging in and sending a request from that page would result in the correct headers being passed, which I guess isn't the case?

This is true for cookies, everything matching the URL will be sent along with the request.  With JWT authorization there is no standard way to store it in the browser and only the app knows how to construct it, so you need to get the JWT token from the page and set it in `Authorization` header on the request manually.

**Comment by A-ZC-Lau** [comment]
okay, I added the authorization and it passed.
