### ISSUE TITLE
[BUG] Official docker image: Error: Cannot autolaunch D-Bus without X11 $DISPLAY

### ISSUE THREAD

**Issue by thegalah** [microsoft/playwright#9211]
**Context:**
- Playwright Version: 1.13.1
- Operating System: Docker (official iamge: mcr.microsoft.com/playwright:focal)
- Node.js version: [e.g. 12.22, 14.6]
- Browser: Chromium
- Extra: using playwright-test
```
  27) src/scenarios/test.test.ts:10:1 › can login =======================

     Error: Cannot autolaunch D-Bus without X11 $DISPLAY
```
FROM mcr.microsoft.com/playwright:bionic
RUN npm i -g yarn
COPY package.json /app/package.json
COPY ../../yarn.lock /app/yarn.lock
WORKDIR /app
RUN yarn install
ENTRYPOINT yarn run test
```



running a docker-compose with the tests mounted in the official docker image. I receive the error
Error: Cannot autolaunch D-Bus without X11 $DISPLAY

and the tests don't run

**Comment by aslushnikov** [comment]
Do you run your tests in headful mode? In this case, change `ENTRYPOINT yarn run test` to 

```
ENTRYPOINT xvfb-run --auto-servernum yarn run test
```

**Comment by thegalah** [comment]
I just tried that modification to the entry point and now I receive:
```
Error: Failed to execute child process “dbus-launch” (No such file or directory)
```

**Comment by aslushnikov** [comment]
I've never seen this. Can you provide us with your dockerfile & code you run into it so that we can try reproducing this?

**Comment by thegalah** [comment]
Resolved this. I believe it was caused by some confict with other node modules since it is part of a mono repo
