### ISSUE TITLE
[Bug]: Dont work .tap() in allready browser context

### ISSUE THREAD

**Issue by 66696e656c696665** [microsoft/playwright#9213]
### Playwright version

1.15

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

I connect to allready browser with `browser_type.connect_over_cdp`
and .tap() dont work. How to fix this

**Comment by aslushnikov** [comment]
This should work! But that's definitely not enough information to reason abbout.

Please re-file with a code snippet that illustrates your problem and that we can run locally to debug.
