### ISSUE TITLE
[Feature] timeout in test.use()

### ISSUE THREAD

**Issue by buckthebug** [microsoft/playwright#9214]
It would be great to have a possibility to set the test timeout in a particular test file or in a test.describe() by `test.use({ timeout: xyz })`. Now, it's possible only globally through testConfig.
Why? We have a lot of tests. Most of them are fast (1-2 seconds) and only a few tests take minutes (several redirects) but we have to set the timeout to 3 minutes for all of them. In the case of the fast test, a 10-second run means that something went wrong and it could fail quickly.
If there is this possibility and I didn't find it, please let me know. I'll be happy.
Thanks, guys!

**Comment by aslushnikov** [comment]
> It would be great to have a possibility to set the test timeout in a particular test file or in a test.describe() by test.use({ timeout: xyz }). Now, it's possible only globally through testConfig.

@buckthebug you can do it using the [`test.setTimeout()`](https://playwright.dev/docs/api/class-test#test-set-timeout) API!

**Comment by buckthebug** [comment]
> > It would be great to have a possibility to set the test timeout in a particular test file or in a test.describe() by test.use({ timeout: xyz }). Now, it's possible only globally through testConfig.
> 
> @buckthebug you can do it using the [`test.setTimeout()`](https://playwright.dev/docs/api/class-test#test-set-timeout) API!
