### ISSUE TITLE
[Question]  Visual Object Model for Playwright itself?

### ISSUE THREAD

**Issue by ZooDoo4U** [microsoft/playwright#9220]
As they say a picture is worth a lot of words,   Getting into using playwright was looking for a Object model diagram to visually get a view of what and how things are put together...  Might be helpful for others, just getting into using Playwight, if something is terribly off, i'll update the model and update...

![image](https://user-images.githubusercontent.com/11509268/135353951-d8881e99-02ad-42f9-a020-7b08d3951434.png)

**Comment by aslushnikov** [comment]
Yeah, we'll add a picture with a good structural representation of the API.

**Comment by ZooDoo4U** [comment]
Thanks @aslushnikov, if you don't mind and given what is shown, is there any glaring issues where it is wrong?  Did my best from reading the docs on the web so far.

**Comment by aslushnikov** [comment]
I'll close this for now - maybe we'll come with something nice in future.

> is there any glaring issues where it is wrong?
