### ISSUE TITLE
[BUG]Getting SameSite Cookie Issue while navigating back to Parent page from new Window

### ISSUE THREAD

**Issue by jithinjosejacob** [microsoft/playwright#9223]
**Context:**
- Playwright Version: 1.15
- Operating System: Mac
- Node.js version: 12.19.1
- Browser: Chrome
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:
NA
```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  // ...
})();
```

**Describe the bug**

1) Navigate to merchant site which needs to be tested.

2) Add any product to cart page, and navigate to Cart

3) Make a payment with Afterpay express checkout in a new window,and make a successful payment.

4) Once Payment is successful,user is redirected back to merchant page, but purchase is not successful .

Note:Same action could be done manually successfully

Console error

Indicate whether to send a cookie in a cross-site request by specifying its SameSite attribute
Because a cookie’s SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, which prevents the cookie from being sent in a cross-site request. This behavior protects user data from accidentally leaking to third parties and cross-site request forgery.
Resolve this issue by updating the attributes of the cookie:
Specify SameSite=None and Secure if the cookie should be sent in cross-site requests. This enables third-party use.
Specify SameSite=Strict or SameSite=Lax if the cookie should not be sent in cross-site requests.

Sample Site : https://www.justjeans.com.au/shop/en/justjeans (Once we add a product to Cart , there will be a Checkout with Afterpay button(Thats express checkout). A similar site is bieng tested in lower environments

**Comment by aslushnikov** [comment]
> Note:Same action could be done manually successfully

@jithinjosejacob chromium's same-site cookies behavior has changed recently. Could you please try running this test manually on Chrome Canary and see if it works?

**Comment by jithinjosejacob** [comment]
@aslushnikov - This scenario is passing in chrome canary and chrome while testing manually . Even if i use debugger to step over each action it works. But when the actual test runs in Playwright chrome or chrome canary it breaks, i could see that once payment is processed,it takes a lot of time to get the response back. I tried to use page.on('close') hookthere, but still icould see that navigation moved on, it could be not waiting until the payment finishes, and then gets the above error.

**Comment by pavelfeldman** [comment]
I can add more lax tests, so far I did not find any discrepancies.

**Comment by jithinjosejacob** [comment]
i managed to get a fix for the issue, it was not related to playwright. but was due to an async call happening in the window and i press Buy Now during the time. Thanks for having a look

**Comment by jithinjosejacob** [comment]
Not a playwright issue
