### ISSUE TITLE
[BUG] Difference in the size of the trace file on chromium vs webkit

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#9226]
**Context:**
- Playwright Version: 1.15.0
- Operating System: Mac
- Node.js version: 12.22
- Browser: Chromium, WebKit

**Code Snippet**
```javascript
test('basic test', async ({ page }) => {
    const title = page.locator('.navbar__inner .navb2ar__title');
    await expect(title).toHaveText('Playwright');
});
```

```javascript
// playwright.config.js
trace: 'on'

projects: [
    {
      name: 'Desktop Chrome',
      use: { browserName: 'chromium' },
    },
    {
      name: 'Desktop Safari',
      use: { browserName: 'webkit' },
    },
};
```

**Describe the bug**
Observe the trace file size created for test run on chromium vs webkit. There is a huge difference in the size:

- Chromium: 2KB
- WebKit: 89KB

**Comment by dgozman** [comment]
@Nav-2d This is because WebKit produced many screenshot frames during the 5 seconds expect was waiting for, while Chrome was smart and produced just one. Do you have a more realistic example where you actually load the page with some content, or did you only spot it on this empty page test?

**Comment by Nav-2d** [comment]
@dgozman - Thanks for looking into this! Yes, I do have a realistic example and we experience this on our website too. The size of trace file in chromium is 2.3MB and the size in webkit is 27.5MB. I won't be able to share the trace file here but I have pinged you in Slack with the files. Thank you! 

Please let me know if I provide any additional details.

**Comment by mxschmitt** [comment]
Fixed
