### ISSUE TITLE
[Feature] page.frameByAttribute / page.findFrame methods

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#9227]
(coming from the discussion at https://github.com/microsoft/playwright/issues/9209)

Playwright currently has a synchronous `page.frame()` method that accepts a frame selector. However, its capabilities are limited to filtering by name and url only.

I'd be very helpful to web testers to have `page.frameByAttribute()` method or even `page.findFrame()` that accepts a predicate.

Examples:

```js
const myFrame1 = await page.frameByAttribute('data-test-id', 'my-subframe');
const myFrame2 = await page.findframe(iframe => iframe.getAttribute('data-test-id') === 'my-subframe');
```

A possible workaround: https://github.com/microsoft/playwright/issues/9209#issuecomment-930220020

**Comment by dgozman** [comment]
It seems like frame locators are covering this.
