### ISSUE TITLE
missing screenshot when using test.steps in allure report

### ISSUE THREAD

**Issue by Lakshmi-Yaswanth** [microsoft/playwright#9228]
**Example Code**

[test("test",()=>{
test.step(" Step 1",()=>{
console.log("Step1");
});
test.step(" Step 2",()=>{
console.log("Step2");
});
})

After completion of running script. When generating report I am not getting screenshots of the **test.steps.**
Is there any way we can get screenshot for the **test.steps.**

**Comment by TimeInvestor** [comment]
I am not sure exactly how to do it and I also want to know how to do in with Playwright (in TypeScript or JavaScript).
But I think, for one thing, you need to take screenshot like page.screenshot.
And in Java (Selenium + Allure), there is attachment method of Allure call to tell Allure to attach the screenshot to the step.

**Comment by yury-s** [comment]
Closing in favor of  https://github.com/microsoft/playwright/issues/9481
