### ISSUE TITLE
[Question]: FetchRequest usage

### ISSUE THREAD

**Issue by dshaplyko** [microsoft/playwright#9232]
Hello!

I'm trying to use the newly introduces FetchRequest API but unable to do that properly.
According to the current implementation it should be used smth like that:
`const response: FetchResponse = await page._request.get("https://jsonplaceholder.typicode.com/posts"`;
As far as I know, "._" means that the field is a private.

Is it the correct syntax or the feature implementation is still in progress?

**Comment by aslushnikov** [comment]
@dshaplyko that's an experimental feature, thus the leading `_`. Your usage is correct though!

**Comment by dshaplyko** [comment]
> @dshaplyko that's an experimental feature, thus the leading `_`. Your usage is correct though!

Thank you for your reply!
