### ISSUE TITLE
[BUG] initial combinator in a :has() selector not working

### ISSUE THREAD

**Issue by thewilkybarkid** [microsoft/playwright#9233]
**Context:**

- OS: macOS 11.6
 - Memory: 81.65 MB / 16.00 GB
- Node: 14.17.3
 - npm: 6.14.13
 - Bash: 5.1.4
- Playwright: 1.15.0

**Code Snippet**

```typescript
await page.waitForSelector('a:has(> img)')
```

**Describe the bug**

The [`:has()` pseudo-class documentation](https://playwright.dev/docs/selectors/#selecting-elements-that-contain-other-elements) links to the [MDN page for `:has()`](https://developer.mozilla.org/en-US/docs/Web/CSS/:has), which has an example selector `a:has(> img)`.

Using `a:has(> img)` in Playwright results in a `Unexpected token ">" while parsing selector "a:has(> img)"`.

Is this meant to be supported? If not, the Playwright docs should be updated to include what `:has()` does support.

**Comment by aslushnikov** [comment]
@thewilkybarkid it is fixed on tip-of-tree! Try installing `npm i @playwright/test@next`. Will be released in 1.16!

**Comment by dgozman** [comment]
For the record, this was fixed in #9088.
