### ISSUE TITLE
[Feature]: Add initiator to HAR recording

### ISSUE THREAD

**Issue by ducalpha** [microsoft/playwright#9237]
### Feature request

Current HAR recording does not include `_initator` of HTTP requests. DevTools dump from UI contains this information. `HTTPRequest` with the `initiator` feature is now supported by [Puppeteer](https://github.com/puppeteer/puppeteer/pull/7614).

**Comment by pavelfeldman** [comment]
What is your use case for it?

**Comment by ducalpha** [comment]
I need the `initiator` information to analyze data traffic originated from different sources (e.g., which scripts) of a web page to identify data leakage (i.e., privacy issues) on websites. The `initiator` can also be used in other use cases such as web-page performance analysis and testing/debugging.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
