### ISSUE TITLE
[Bug]: context settings are not applied to new page

### ISSUE THREAD

**Issue by 66696e656c696665** [microsoft/playwright#9238]
### Playwright version

1.15

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

Python version 3.8

### What happened? / Describe the bug

I have an open anonymous browser with a chromium based devtool protocol. I am connecting to it via .connect_over_cdp.
And I'm working in an existing context that uses the profile settings of this browser.
When I load sites in an existing page, everything is fine. But when I create a new page, the settings of the existing context are lost. There are no such problems with a puppeteer.

P.S. I want to add that my browser is working in mobile emulation mode 

### Code snippet to reproduce your bug

```shell
from playwright.sync_api import sync_playwright

def run():
	playwrite = sync_playwright()
	chromium = playwrite.start()
	browser = chromium.chromium.connect_over_cdp('ws://127.0.0.1:3668/devtools/browser/7110d5e0-4643-45c9-8204-8be1fe6b69ff')
	context = browser.contexts[0]
	page = context.new_page()
	page.goto("https://pixelscan.net")
run()
```

**Comment by pavelfeldman** [comment]
Which settings are lost?

**Comment by 66696e656c696665** [comment]
> Which settings are lost?

Screen resolution

How can I get the rest of the browser context options as a complete list?

**Comment by 66696e656c696665** [comment]
Я бегло изучил ваш nodejs сервер и понял что this._page._browserContext._options содержит лишь одну строку:

`{"noDefaultViewport":true}`

Мне кажется все дело в этой опции и что playwright не способен работать с уже настроенным браузером с активированным профилем через .connect_over_cdp

Хочу так же отметить что у меня не срабатывал метод .tap(), я понял что проблема в файле:

```
\site-packages\playwright\driver\package\lib\server\input.js

336: if (!this._page._browserContext._options.hasTouch) throw new Error('hasTouch must be enabled on the browser context before using the touchscreen.');
```

Тут происходит проверка доступности touch основываясь лишь опциями текущего browser сontext которые прописаны в самом сервере playwright. Но проблема в том что playwright не получает browser сontext options из открытого браузера, а оперирует лишь теми что сгенерил сам playwright в одностороннем порядке. Поэтому работа с уже настроенными браузерными профилями и подключение к активному браузеру через connect_over_cdp происходит с ошибками.
Это большой недостаток, потому что огромное кол-во браузеров предсотавляют настраиваемые средства анонимности и профили уже из коробки.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
