### ISSUE TITLE
[BUG] Format of the className in junit reporter causes issue with viewing TestComplete Test Results in Jenkins

### ISSUE THREAD

**Issue by udit0802** [microsoft/playwright#9249]
**Context:**
- Playwright Version: 1.15.0
- Operating System: centos
- Node.js version: 14.6.1
- Browser: Chrome
- Extra: running on jenkins machine

**Code Snippet**

Configuration

```javascript
["junit", { outputFile: "target/report/test/results.xml",stripANSIControlSequences:true}]
```

**Describe the bug**

I am trying to integrate junit style report generated using junit reporter with the testcomplete plugin of jenkins.
Generated XML file is something like : 
[results.txt](https://github.com/microsoft/playwright/files/7263987/results.txt)

This is generating fine view of the test suites, as in:
<img width="1323" alt="test_suites" src="https://user-images.githubusercontent.com/29638296/135562395-49330314-98ee-4e83-9113-a09cf897f2fc.png">
Reference : https://support.smartbear.com/testcomplete/docs/working-with/integration/jenkins/viewing-test-results.html#junit-style-reports

But when I am trying to dig deep into the specific test of test suite getting error : 
https://<jenkins-host>/job/<jobname>/<PR>/testReport/PlaywrightE2Etests.[Chrome]%20%E2%80%BA%20test_ccrLetterSanity.test/

These % are present in the URL because of the space In the class name, which seems like the reason of issue to me.

Getting 400 error, this seems because of the classname generated with weird characters, can we make it something like java based class convention?

**Comment by aslushnikov** [comment]
@udit0802 so does it work fine for tests without spaces in their name?

**Comment by udit0802** [comment]
> @udit0802 so does it work fine for tests without spaces in their name?

yes, our other integration tests also generate junit-style reports, I have compared both the reports and the only significant difference I found which explains the issue is the name with special characters.
Attaching the junit XML files, if this can help in your investigation.
Do let me know if you require any other information.
[not-working.txt](https://github.com/microsoft/playwright/files/7269038/not-working.txt)
[working.txt](https://github.com/microsoft/playwright/files/7269039/results.txt)

**Comment by udit0802** [comment]
> > But when I am trying to dig deep into the specific test of test suite getting error : https:///job///testReport/PlaywrightE2Etests.[Chrome]%20%E2%80%BA%20test_ccrLetterSanity.test/
> > These % are present in the URL because of the space In the class name, which seems like the reason of issue to me.
> 
> This sounds like a problem in TestComplete and how it handles such strings. There are no %.. in the xml files as you can see. What does the error say besides the url?

Here the names are generated by the playwright framework with spaces in between.
This appears when try to look into the test result, there is no such error at console.
Attaching the curl request.

`curl 'https://<ci-name>/job/master/139/testReport/PlaywrightE2Etests.\[Edge\]%20%E2%80%BA%20test_ccrLetterSanity.test/' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'sec-ch-ua: "Chromium";v="94", "Google Chrome";v="94", ";Not A Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: navigate' \
  -H 'Sec-Fetch-User: ?1' \
  -H 'Sec-Fetch-Dest: document' \
  -H 'Referer: https://<ci-name>/job/master/139/testReport/' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'Cookie: acaplup=learner; _scid=cc91af09-81aa-4938-a09b-4fa051ca0bfb; s_ims=https://ims-na1.adobelogin.com/ims/session/v1/YmRiNGNkNWUtOGE4Yy00MWRlLTgzMTUtMTc4MDlmMjg3NGIwLS05REFDMzBDQjVERDUyRjMwMEE0OTVDMURAYWRvYmUuY29t; AMCVS_9E1005A551ED61CA0A490D45%40AdobeOrg=1; s_ecid=MCMID%7C74547229694644194331499154627669938736; s_cc=true; AMCVS_1E7D2DE65D135D0B0A495E9E%40AdobeOrg=1; AMCV_1E7D2DE65D135D0B0A495E9E%40AdobeOrg=1585540135%7CMCMID%7C74547229694644194331499154627669938736%7CMCIDTS%7C18933%7CMCOPTOUT-1635755273s%7CNONE%7CvVersion%7C4.4.0; screenResolution=1680x1050; jenkins-timestamper-offset=-19800000; at_check=true; AMCVS_8F99160E571FC0427F000101%40AdobeOrg=1; feds_privacy_consent={"hasUserProvidedConsent":true,"userHasCustomConsent":false}; s_fid=721DFF0AC90B050F-370BD46201799A60; _ga=GA1.2.1242026893.1636572269; _ga_86VDHR43HP=GS1.1.1636572268.1.0.1636572271.0; jenkins-timestamper=system; jenkins-timestamper-local=true; kndctr_8F99160E571FC0427F000101_AdobeOrg_consent=general%3Din; primec=NnZkZlVJZ0gyb0pPVzgyUnV4dUVwM3l4TjF5NVRvd1JWdHVOTzdDa0Y4RUhHSG9UVWQ3VmtyMmdnMysyaGtoZU0zcEJ4SHRObXBZRHhjN1ljMkN5K2c9PQ; fg=V6JG56R4FLG5ATECFAQBRPQAEY======; AMCV_8F99160E571FC0427F000101%40AdobeOrg=-1124106680%7CMCMID%7C74547229694644194331499154627669938736%7CMCIDTS%7C18948%7CMCAAMLH-1637666762%7C12%7CMCAAMB-1637666762%7Cj8Odv6LonN4r3an7LhD3WZrU1bUpAkFkkiY1ncBR96t2PTI%7CMCOPTOUT-1637069162s%7CNONE%7CvVersion%7C5.2.0; mbox=PC#c8c4578350f44e5387990f9ec0ca29c0.31_0#1700306763|session#bb5ccd22211f4a548bef9d70f65303c0#1637063822; OptanonConsent=isIABGlobal=false&datestamp=Tue+Nov+16+2021+16%3A56%3A02+GMT%2B0530+(India+Standard+Time)&version=6.9.0&hosts=&consentId=7f58c005-2ebe-4329-9676-bb93e46c7b40&interactionCount=1&landingPath=NotLandingPage&groups=C0001%3A1%2CC0002%3A1%2CC0003%3A1%2CC0004%3A1&AwaitingReconsent=false; kndctr_8F99160E571FC0427F000101_AdobeOrg_identity=CiY3NDU0NzIyOTY5NDY0NDE5NDMzMTQ5OTE1NDYyNzY2OTkzODczNlIPCKnd%2DcPQLxgBKgRJTkQx8AHn7PzD0i8%3D; JSESSIONID=FD0BE8B3B52683F1AEC24231E8837133; RDC=AdsvgG2kq5A9ruWr6r39UBWLoCvwTXWxINldrud1c0hwdXegkWRC2_eEj8ZTx9Y; fg_stg=V6LRN6R44ZYZA4DZPCRMA2IA5Y======; s_ims_stg=https://ims-na1-stg1.adobelogin.com/ims/session/v1/NWQzNjAzYTAtNjMxZi00MWIxLWI4NjAtN2UxZjU2MWI0MDU2LS05OThBN0EyRjVERTdGQjFFMEE0OTQxMjFAQWRvYmVJRA; shellImsEnv=stage; aux_sid=eyJhbGciOiJSUzI1NiIsImtpZCI6Imltc19uYTEtc3RnMS1rZXktY2stMSIsIml0dCI6ImNrIn0.eyJzaWQiOiIxNjM3MTMzNTIzNTc1X2IxZjE3ZGU2LWI5N2EtNDk4OS04NjE5LTczZDhmNmU0OTkwMV91ZTEiLCJ1aWQiOiI5OThBN0EyRjVERTdGQjFFMEE0OTQxMjFAQWRvYmVJRCIsImFpZCI6bnVsbCwiaXNpIjpudWxsLCJpaWQiOm51bGx9.ETrI0CuFU2rrZzz3NlUatA1HbHijzXejx7bT7o-vn-enJrT8T32S3zK-mMvpATADiue-bFh9xA4X0j3fbKRUQ-Y2fBh8_F-xyr2SnUhIhZdNojn5IQB0IBRtv0TOtlvDcUoaV-0MAmSpfMM2NtC9upuk0PqBWbdXHcQIShUzsLx66dPtsd04ibEESordsonmaU06tHOzj_6THR6vX49sRVDhPklc2PHsn_69yO_FsRiKiVNsMOZFwWBk-IPDjSGrs38d_THdU4QNw8VyYgo4ZZaLMz-nV-DF4pV7cmLFhCCCxTx3Pg5ZLf7lwQe0DrefjFEMQrc204dm2Upqe1zKkg; apt.uid=AP-KDZIABJIM4XD-2-1637133532918-71872512.0.2.43379340-0649-47dd-8672-b875353fc0a5; AMCV_9E1005A551ED61CA0A490D45%40AdobeOrg=-637568504%7CMCIDTS%7C18949%7CMCMID%7C74547229694644194331499154627669938736%7CMCAAMLH-1637740569%7C12%7CMCAAMB-1637740569%7CRKhpRz8krg2tLO6pguXWp5olkAcUniQYPHaMWWgdJ3xzPWQmdj0y%7CMCOPTOUT-1637142969s%7CNONE%7CMCAID%7CNONE%7CvVersion%7C5.1.1%7CMCCIDH%7C458569641; s_ppv=[%22inside.corp.adobe.com/search.html%22%2C81%2C0%2C2249%2C1680%2C939%2C1680%2C1050%2C2%2C%22P%22]; s_nr=1637136038094-Repeat; s_sq=amc.global.prod%252Camc.cm.prod%3D%2526c.%2526a.%2526activitymap.%2526page%253Dhttps%25253A%25252F%25252Fmy.stage.cloudmanager.adobe.com%25252Flanding.html%2526link%253DClose%2526region%253Ddialog-test%2526.activitymap%2526.a%2526.c' \
  --compressed`

**Comment by udit0802** [comment]
Response : 
`<!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Description</b> The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).</p><hr class="line" /><h3>Apache Tomcat/9.0.37</h3></body></html>`

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
