### ISSUE TITLE
[Question]page.goto: net::ERR_ABORTED at https://playwright.dev/docs/next/intro

### ISSUE THREAD

**Issue by Lakshmi-Yaswanth** [microsoft/playwright#9251]
Description:

Have using two Urls.
Firstly have navigate to 1 url example ' https://github.com/microsoft/playwright/releases' and have done some in this page.
after i want to navigate to another URL. I am getting this error.
Is there any way to overcome his.

**Comment by aslushnikov** [comment]
@Lakshmi-Yaswanth something's wrong with your script; please re-submit following the issue template. Most importantly, show us your code so that we can repro this locally!
