### ISSUE TITLE
[Feature] allow  waitForSelector to work in same pattern like other actions

### ISSUE THREAD

**Issue by Amrkamel1** [microsoft/playwright#9276]
similarly, as we can define the element and use it like below 

```
    get username() {return this.page.locator('#username')}
    async loginWith(user, pass) {
        await this.username.type(user)
        return this;
    }
```

it would be good to follow the same structure when using waitForSelect , the current implementation accepts only string which means you will need to define some elements as just string 

```
    async waitForErrorMsg() {
        await this.username.waitForSelector()
        return this;
    }
```

**Comment by pavelfeldman** [comment]
It is already implemented, locator.waitFor() will release as a part of 1.16.

**Comment by mxschmitt** [comment]
Closing see #8577
