### ISSUE TITLE
[BUG] Downloading fails if 'downloadsPath' gets set

### ISSUE THREAD

**Issue by Osiris-Team** [microsoft/playwright#9279]
### Context:

- Playwright Version: [v1.15.1]
- Operating System: [Windows 10]
- Node.js version: [v16.10.0.]
- Browser: [Chromium]
### Code Snippet
My aim is downloading a file directly from an url.
For that I goto about:blank and append a new <a> download button to click on.
Like shown in the code below:
```js
const playwright = require('playwright');
const browser = await playwright['chromium'].launchPersistentContext('D:/Coding/JAVA/Headless-Browser/headless-browser/user-data', {
  acceptDownloads: true,
  headless: true,
  javaScriptEnabled: true,
  downloadsPath: 'D:/Coding/JAVA/Headless-Browser/headless-browser/user-data/downloads-temp',
  devtools: false
});
const page = await browser.newPage();

try {
  await page.goto('about:blank');
  var event = page.waitForEvent('download');
  console.log('preparing download');
  await page.evaluate(`var myCUSTel = document.createElement('a');myCUSTel.innerHTML = 'Download';myCUSTel.setAttribute('href', 'https://file-examples-com.github.io/uploads/2017/02/zip_2MB.zip');myCUSTel.setAttribute('id', 'myCUSTel');document.getElementsByTagName('body')[0].appendChild(myCUSTel);`);
  await page.click('id=myCUSTel');
  var download = await event;
  console.log(event);
  var downloadError = await download.failure();
  if (downloadError != null) throw new Error(downloadError);
  var result = await download.path();
  console.log('Downloaded successfully to:'+result);
} catch (e) {
  console.error('CAUGHT JS-EXCEPTION: ' + e.name + '\n' + 'MESSAGE: ' + e.message + '\n' + 'LINE: ' + e.lineNumber + '\n' + 'STACK: ' + e.stack + '\n');
}
```
### Updates
- The download only fails when 'downloadsPath' in `...launchPersistentContext(...)` gets set.
Otherwise the code above works fine.

**Comment by JoelEinbinder** [comment]
`page.click(id=myCUSTel);`
This line does not have quotes around it, so either it doesn't work or you didnt copy paste the actual code you are using here,.

you are missinng `await` for your `page.evaluate`, as well as your `page.click`. The link you are creating also has no text contnent, which makes it have 0 width and it might not be clickable.

Additionally, when clicking the link you created manually, it doesn't cause a download. Instead it navigates to the video.

**Comment by Osiris-Team** [comment]
@JoelEinbinder thank you very much! Seems like there were multiple issues. I'll try to fix them and I'll close this as soon as it works.

**Comment by Osiris-Team** [comment]
@JoelEinbinder fixed all issues mentioned by you (updated the original code), at least now I get some results even though
its the timout error:
```error
CAUGHT JS-EXCEPTION: TimeoutError
MESSAGE: Timeout while waiting for event "download"
=========================== logs ===========================
waiting for event "download"
============================================================
LINE: undefined
STACK: TimeoutError: Timeout while waiting for event "download"
=========================== logs ===========================
waiting for event "download"
============================================================
    at D:\Coding\JAVA\Headless-Browser\node_modules\playwright\lib\client\waiter.js:92:13
    at async Waiter.waitForPromise (D:\Coding\JAVA\Headless-Browser\node_modules\playwright\lib\client\waiter.js:107:22)
    at async Page._waitForEvent (D:\Coding\JAVA\Headless-Browser\node_modules\playwright\lib\client\page.js:472:20)
    at async Promise.all (index 1)
    at async REPL12:2:26
    at async node:repl:609:28
```

**Comment by Osiris-Team** [comment]
Just updated once more and layed everything out as much as possible.
Seems like the download gets cancelled now:
```error
java.lang.RuntimeException: com.osiris.headlessbrowser.exceptions.NodeJsCodeException: Error during JavaScript code execution! Details: 
CAUGHT JS-EXCEPTION: Error
MESSAGE: canceled
LINE: undefined
STACK: Error: canceled
    at REPL12:10:32
    at async node:repl:609:28
```

**Comment by Osiris-Team** [comment]
This is what happens in headless=false:
![image](https://user-images.githubusercontent.com/59899645/136382677-3dfda11b-c808-4983-a131-7baa15323efd.png)
It also fails when pressing the Download link manually.

**Comment by Osiris-Team** [comment]
> Closing per last comment.

The issue still exists. As I said before I updated the first comment with all the details you need to reproduce the error.
