### ISSUE TITLE
[BUG] Enable GitHub reporter in default configs and internal tests.

### ISSUE THREAD

**Issue by sidharthv96** [microsoft/playwright#9281]
Next step would be probably to automatically add it as a reporter in the default configuration if the `GITHUB_ACTION` environment variable is set + activate it on our configs so we can dogfood it.

_Originally posted by @mxschmitt in https://github.com/microsoft/playwright/issues/9191#issuecomment-933268500_

Relates: #9147

**Comment by sidharthv96** [comment]
Should we just add github in here in addition to `dot` if the env var is present?
https://github.com/microsoft/playwright/blob/e674d873a3671f608887b2568ea6fc00d23a6b5b/src/test/cli.ts#L29

**Comment by mxschmitt** [comment]
Yeah I think:
- defaultReporter -> defaultReporters
- Keep dot reporter how it is
- Add GitHub Action reporter if the env var is set.

This is then for projects which don't have a config. In our scenario we need to add it manually to the configs `tests/config`.

**Comment by sidharthv96** [comment]
I think we forgot to add GitHub to https://github.com/microsoft/playwright/blob/b126a5685b0e047b19bbf54ec7bc753cba1efa8d/utils/generate_types/overrides-test.d.ts as github isn't listed as an option in https://github.com/microsoft/playwright/blob/19715300b35662be0d4dcf89b89b54b9a9d265c8/types/test.d.ts#L23-L30

Is that the proper procedure to add to the types?

**Comment by JoelEinbinder** [comment]
> I think we forgot to add GitHub to https://github.com/microsoft/playwright/blob/b126a5685b0e047b19bbf54ec7bc753cba1efa8d/utils/generate_types/overrides-test.d.ts as github isn't listed as an option in
> 
> https://github.com/microsoft/playwright/blob/19715300b35662be0d4dcf89b89b54b9a9d265c8/types/test.d.ts#L23-L30
> 
> Is that the proper procedure to add to the types?

These are the types for users. Is there are reason someone manually specifies the github reporter in their config? I figured it would just be automatically turned on by checking for the environment variable.

**Comment by sidharthv96** [comment]
@JoelEinbinder we could push GitHub in here based on an both `GITHUB_ACTION` and `PW_DISABLE_GITHUB_ANNOTATION`(?) env variables so it will be available regardless of the user config or cli flags. https://github.com/microsoft/playwright/blob/be30f9f1c44e59f7dd6ccf86b22d4d0b478d1dc4/src/test/runner.ts#L67-L88

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
