### ISSUE TITLE
[Question]How do i click a button in a typeform

### ISSUE THREAD

**Issue by Lenethisssss** [microsoft/playwright#9295]
I used playwright for some code and it was realy efficient but i need just to click in this submit button on this typeform to finish my bot but it dosent work i used xpath css selector and everything but i dont know how to do it

**Comment by JoelEinbinder** [comment]
You can use [codgen](https://playwright.dev/docs/cli/#generate-code) to help generate selectors and code to click buttons. Without a specific problem in playwright there isn't anything actionable for us here. Good luck!
