### ISSUE TITLE
[Question]: How to scroll a dropdown in a scroll window till a particular text or element is found?

### ISSUE THREAD

**Issue by shiv-jirwankar** [microsoft/playwright#9305]
I want to scroll a dropdown till a particular text or element is found. How can we achieve this via Playwright?

**Comment by JoelEinbinder** [comment]
If your element is in the DOM and you just want to scroll to it, you don't have to do anything special. Playwright automatically scrolls elements into view before clicking them. So just use a [`locator`](https://playwright.dev/docs/api/class-page#page-locator) with a text selector or any other selector that finds your element.

If the element is not in the DOM until you scroll to it, things get more complicated:

You can use a combination of [`mouse.wheel`](https://playwright.dev/docs/api/class-mouse#mouse-wheel) and [`page.waitForSelctor`](https://playwright.dev/docs/api/class-page#page-wait-for-selector).

Run the waitForSelector command without awaiting it, then periodically send mouse wheels into the page and check if waitForSelector has resolved.

This becomes a complicated scenario, so unfortunately I can't provide any more help than this.
