### ISSUE TITLE
[Question] How to automate toggle button in playwright

### ISSUE THREAD

**Issue by Lakshmi-Yaswanth** [microsoft/playwright#9306]
```
Iam using this url:"https://mdbootstrap.com/docs/b4/jquery/forms/switch/";
Iam using the locator.click()  in automating the toggle button. This click() was not working in while using toggle button.
Example:
const ele=page.locator("#checkBox");
await ele.click();
```
-----------------------------------------------------------------------------------------------------------------------------------------
error: locator was hidden

**Comment by JoelEinbinder** [comment]
Sounds like you are clicking the wrong element. You can use [codegen](https://playwright.dev/docs/cli#generate-code) to help pick the correct selector and write the code. Good luck!
