### ISSUE TITLE
[Question] is video.saveAs guaranteed to write the file to disk?

### ISSUE THREAD

**Issue by worldomonation** [microsoft/playwright#9324]
Hi 👋 

I have a question about the `video.saveAs` method.

When called at the end of a script to save a video with a custom name, one would call something like this:

```
await page.close();

await page.video().saveAs( <path_on_disk> ); 
```

The [documentation](https://playwright.dev/docs/api/class-video) for the video class mentions once for `video.path()` that '...video is guaranteed to be writtten...'. 

Would this guarantee also apply to other other methods in the video class, such as `video.saveAs()`?

Thanks!

**Comment by mxschmitt** [comment]
Do you mean if `saveAs` will resolve once it's fully written to the disk? `saveAs` will wait until the page has closed and the video got written fully to the disk.

(I probably don't understand your question)

**Comment by yury-s** [comment]
> My question was more around whether there exists guarantee that `page.video.saveAs` will always write the full contents of the recorded video to the disk at the provided path.

If the method returns without errors the full video is guaranteed to be written to the file. Exceptions may be triggered by various factors, e.g. not enough space on the disk, or the context gets closed for whatever reason etc.
