### ISSUE TITLE
[BUG] --grep option doesn't work at all from CLI

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#9338]
**Context:**
- Playwright Version: 1.15.2
- Operating System: Windows
- Node.js version: 14.6.1
- Browser: Chromium
- IDE: Webstorm

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
 test('Verify Max Allowed Exchanges stored in Series level @run', async ({page}) => {
        let seriesName = "FC Barcelona 2030";
        let maxAllowedExchanges = "11";
        let maxAllowedExchangesOriginal: string;
```

**Describe the bug**

The grep option with a @ tag - doesn't work. I try to run with the '@run' tag - and it doesn't work. 
I'm getting the following:
![image](https://user-images.githubusercontent.com/52656401/136172647-cae4cdf9-6e1c-444f-a49a-c8a7f51d80a1.png)

**Comment by AlexKomanov** [comment]
My mistake. I forgot the 'only' option on one of the tests.

**Comment by pjcalvo** [comment]
> My mistake. I forgot the 'only' option on one of the tests.

Hahahahaha I just had this same issue. But when I run `--list` then it was showing all the tests, and also the CI flag ignores the `.only` flag. How dumb we are..
