### ISSUE TITLE
[Question]: pre-download browser zip due to network problem

### ISSUE THREAD

**Issue by DullJZ** [microsoft/playwright#9340]
### Your question

Due to network problem, I need to pre-download the browser. Where can I get the latest version of Chromium and where I should put the zip file?

**Comment by DullJZ** [comment]
According to the docs, I found `%USERPROFILE%\AppData\Local\ms-playwright` in windows, where there includes the browser files. I copied these to another computer at the same dir, and they can run properly. Did I do right?

**Comment by mxschmitt** [comment]
If its same platform/architecture yes. But in general it should work to download the browsers on your end - even if it takes a few minutes. Each browser is between 50-100MB.

**Comment by JoelEinbinder** [comment]
Yep, you can skip the browser downloads as well on the same docs page that max linked you to: https://playwright.dev/python/docs/browsers/#skip-browser-downloads
