### ISSUE TITLE
[BUG] fixed but it's not - Unknown file extension ".ts"

### ISSUE THREAD

**Issue by alvipeo** [microsoft/playwright#9344]
**Context:**
- Playwright Version: 1.15.2
- Operating System: Win 10 x64
- Node.js version: 14.17.6
- Browser: -
- Extra: part of my angular project

**Describe the bug**

I've had Playwright tests for a while in my project. And they used to work. I repaved my machine, everything works, angular project builds and runs. But when I try to run my tests with `npx playwright test` I get this error:

>Using config at [project_path]\playwright.config.ts
TypeError [ERR_UNKNOWN_FILE_EXTENSION] [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for [project_path]\e2e\src\sign-up.spec.ts
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
    at Loader.getFormat (internal/modules/esm/loader.js:105:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at Loader.import (internal/modules/esm/loader.js:177:17)
    at Loader._requireOrImport ([project_path]\node_modules\@playwright\test\lib\test\loader.js:214:52)
    at Loader.loadTestFile ([project_path]\node_modules\@playwright\test\lib\test\loader.js:130:7)
    at Runner._run ([project_path]\node_modules\@playwright\test\lib\test\runner.js:219:40) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

I understand I may miss something but this really gives me any clue. I saw there are some closed related issues but they seemed to be resolved. So what's wrong here?

**Comment by badsyntax** [comment]
I have the same problem. Although my main project has `"type": "commonjs",` my project is consuming packages that specify `"type": "module",` and I _think_ that's why this is failing.

**Comment by JoelEinbinder** [comment]
From the stack trace, it looks like we are loading this module as esm, but we don't support our automatic typescript transpilation for esm modules. You can work around this by manually compiling your tests with typescript: https://playwright.dev/docs/test-typescript#manually-compile-tests-with-typescript. Or as badsyntax says, change your package.json to have `"type": "commonjs"`.

We should have at least a better error message here.

**Comment by badsyntax** [comment]
Here's a very simple repo of the problem: https://github.com/badsyntax/playright-test-repo

I will attempt to manually compile the test to workaround this.

@JoelEinbinder why don't you support automatic typescript transpilation for esm modules?

**Comment by ubersl0th** [comment]
When manually compiling my tests follwing the guide in the  [docs](https://playwright.dev/docs/test-typescript).
I get the following error: 
```
Error [ERR_REQUIRE_ESM]: require() of ES Module .../node_modules/node-fetch/src/index.js from .../tests/utils/blob.js not supported.
Instead change the require of index.js in .../tests/utils/blob.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (.../tests/utils/blob.js:8:38)
    at Object.<anonymous> (.../tests/utils/emailPool.js:4:16)
    at Object.<anonymous> (.../tests/account/account.test.js:5:21)
    at async Loader._requireOrImport (.../node_modules/@playwright/test/lib/loader.js:217:52)
    at async Loader.loadTestFile (.../node_modules/@playwright/test/lib/loader.js:133:7)
    at async Runner._run (.../node_modules/@playwright/test/lib/runner.js:246:40) {
  code: 'ERR_REQUIRE_ESM'
}
```

So the compiler converts imports to requires and it seems like playwright doesn't like that? Is the documentation wrong or is my config wrong?

```json
{
  "compilerOptions": {
    "module": "CommonJS",
    "target": "ESNext",
    "moduleResolution": "Node",
    "sourceMap": true,
    "outDir": "../tests",
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowJs": true
  }
}
```
I''m also using `type: "commonjs"` in my package.json (have also tries "module", same results).
Is there something I'm missing?

**Comment by JoelEinbinder** [comment]
> @JoelEinbinder why don't you support automatic typescript transpilation for esm modules? (And I agree the error message can definitely be improved here.)
> 
We use `pirates` to replace require. But that doesn't work for imports. Instead there are custom import loaders, but they require a command line argument being passed into node and have very different semantics.

**Comment by badsyntax** [comment]
Nice to see experimental ESM support (without a compile step): https://github.com/microsoft/playwright/releases/tag/v1.18.0-rc1
