### ISSUE TITLE
[Question] How to assert a number or string?

### ISSUE THREAD

**Issue by TimeInvestor** [microsoft/playwright#9352]
Example:
```typescript
    const locator = page.locator('span.lastestValue');
    const str = await locator.innerText();
    await expect(str).toContainText('substring');
```
What I got:
`Error: toContainText can be only used with Locator object`

In general, how do we assert a number, string, or something not Locator object in Playwright?

**Comment by ltsuda** [comment]
Are you using Playwright@Test runner or only Playwright's Library?

If using Playwright@Test, you could try the following:
```js
const locator = page.locator('span.lastestValue');
await expect(locator).toContainText('substring', { useInnerText: true });  
// if you want to use innerText instead of textContent as shown in https://playwright.dev/docs/test-assertions#expectlocatortohavetextexpected-options
```

Or with either Playwright@Test runner or only the library:

```js
const locator = page.locator('span.lastestValue');
const str = await locator.innerText();
expect(str).toBe('substring');
// or
expect(str).toContain('substring');

//number example
expect(1+1).toBe(2)
```

Also, I'm not sure but all Jest expects should also work [Expect](https://jestjs.io/docs/expect).

I hope this helps.

**Comment by TimeInvestor** [comment]
`expect(str).toContain('substring')` is not supported in Playwright as it throws `Error: toContainText can be only used with Locator object`

**Comment by mxschmitt** [comment]
@TimeInvestor I tried the following which is working for me: `expect("abaaa").toContain('aba')`.

Is this the same way you are using it?

**Comment by yury-s** [comment]
Closing per last comment.
