### ISSUE TITLE
[BUG] inconsistent/broken behavior with waitForNavigation and redirects

### ISSUE THREAD

**Issue by keevie** [microsoft/playwright#9369]
**Context:**
- Playwright Version: 1.15.2
- Operating System: Docker mcr.microsoft.com/playwright:v1.15.2-focal
- Node.js version: 14.17.3
- Browser: Firefox, Chrome

After version 1.15, waitForNavigation seems to behave differently and break some of our tests. It seems to be related to redirects and form submissions -- after submitting a form and getting redirected, firefox seems to crash sometimes.

I made this minimal (ish) reproduction repository [here](https://github.com/keevie/playwright-waitForNavigation-repro): there are four cases as far as I can tell, each of them different and weird.

1. Firefox, no wait for navigation after redirect: playwright does not wait, and the test to see if we ended up on the right page fails.
2. Chrome, no wait for navigation after redirect: all tests pass.
3. Firefox, wait for navigation after redirect: run is flaky, about half the time we crash because the page gets closed "page.goto: Target page, context or browser has been closed"
4. Chrome, wait for navigation after redirect: waitForNavigation hangs forever and times out.

**Comment by keevie** [comment]
I suspect this is somehow related https://github.com/microsoft/playwright/issues/9418

**Comment by aslushnikov** [comment]
> I suspect this is somehow related #9418

I checked and it doesn't seem to be related. I spent some time looking into this, but no clue so far

**Comment by keevie** [comment]
Thank you so much for looking into this! Have you been able to reproduce the trouble? I'm spending some time on this again today trying to get our tests to work with 1.16.3

**Comment by keevie** [comment]
Okay I think I have narrowed this down further -- the problem seems to be more about tracing, and less about the waitForNavigation and redirects. I opened a new issue here with a new, simpler repro case. https://github.com/microsoft/playwright/issues/10259

**Comment by aslushnikov** [comment]
> Have you been able to reproduce the trouble? 

Oh yes, I did repro this!

> I opened a new issue here with a new, simpler repro case. #10259

Oh awesome! Let's move the discussion over there then
