### ISSUE TITLE
[BUG] test.fail does not work properly with tests that timeout

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#9373]
**Context:**
- Playwright Version: 1.15.2, ToT

**Code Snippet**

```javascript
import { test, expect } from '@playwright/test';

test('fail', async ({ page }) => {
  test.fail();

  expect(1).toBe(2);
});

test('fail (hanging test)', async ({ page }) => {
  test.fail();

  await new Promise(() => {});
});

test('fixme', async ({ page }) => {
  test.fixme();

  expect(1).toBe(2);
});
```

Output:

```
$ npm run test:e2e -- --project="Desktop Chrome"

> foo@1.0.0 test:e2e
> playwright test "--project=Desktop Chrome"

Using config at …/foo/playwright.config.ts

Running 3 tests using 1 worker

  ✘  [Desktop Chrome] › example.spec.ts:3:1 › fail (531ms)
  ✘  [Desktop Chrome] › example.spec.ts:9:1 › fail (hanging test) (30s)
  ✘  [Desktop Chrome] › example.spec.ts:9:1 › fail (hanging test) (30s)
  ✘  [Desktop Chrome] › example.spec.ts:9:1 › fail (hanging test) (30s)
  -  [Desktop Chrome] › example.spec.ts:15:1 › fixme


  1) [Desktop Chrome] › example.spec.ts:9:1 › fail (hanging test) ==================================

    Timeout of 30000ms exceeded.

    Retry #1 ---------------------------------------------------------------------------------------

    Timeout of 30000ms exceeded.

    attachment #1: trace (application/zip) ---------------------------------------------------------
    e2e/test-results/example-fail-hanging-test--Desktop-Chrome-retry1/trace.zip
    Usage:

        npx playwright show-trace e2e/test-results/example-fail-hanging-test--Desktop-Chrome-retry1/trace.zip

    ------------------------------------------------------------------------------------------------

    Retry #2 ---------------------------------------------------------------------------------------

    Timeout of 30000ms exceeded.

  Slow test: [Desktop Chrome] › example.spec.ts (2m)

  1 failed
    [Desktop Chrome] › example.spec.ts:9:1 › fail (hanging test) ===================================
  1 skipped
  1 passed (2m)
```

**Describe the bug**

I'd expect (pardon the pun), `fail (hanging test)` to pass (like `fail`) test.

In https://github.com/microsoft/playwright/pull/9349, I had to change the `fail` to a `fixme` to get around this bug. In that example, for some browsers, the tests pass, but others the test times out which I assumed should be "expected" by the test.fail.

**Comment by rwoll** [comment]
> @rwoll A side question which I really want to know: how do you config the `--project=Desktop Chrome` option and make the console log look like `[Desktop Chrome] › example.spec.ts:3:1 › ...`?

@TimeInvestor This config is coming from `create-playwright`. You can checkout the setup by looking at the playwright config and package.json generated via:

```
$ mkdir example && cd example
$ npm init playwright
```

**Comment by TimeInvestor** [comment]
> > @rwoll A side question which I really want to know: how do you config the `--project=Desktop Chrome` option and make the console log look like `[Desktop Chrome] › example.spec.ts:3:1 › ...`?
> 
> @TimeInvestor This config is coming from `create-playwright`. You can checkout the setup by looking at the playwright config and package.json generated via:
> 
> ```
> $ mkdir example && cd example
> $ npm init playwright
> ```

Thanks.
