### ISSUE TITLE
[Feature]Running Cucumber Tests using Playwright Test Runner

### ISSUE THREAD

**Issue by jithinjosejacob** [microsoft/playwright#9409]
This is for a feature request to run cucumber tests inside Playwright Test Runner.

Similar functionality in Cypress- https://www.npmjs.com/package/cypress-cucumber-preprocessor

BDD Format makes it easy to understand tests, so most of the companies prefers BDD.

Currently we can only use either cucumber with playwright or playwright test runner with playwright

This makes it difficult to handle configuration like screenshots, videos, tracing, reports from a single config file if we use Cucumber and Playwright

**Comment by yury-s** [comment]
Similar to cypress-cucumber-preprocessor it can be implemented as a separate package. Closing this bug as there are no plans to support this as part of core playwright.

**Comment by 1996phani** [comment]
Even our team has a case for running Cucumber Tests using Playwright Test Runner. or does Playwright has any plan to add their own BDD implementation using playwright test runner? That would be great if we have so.
