### ISSUE TITLE
[Feature] Test metadata

### ISSUE THREAD

**Issue by MindaugasMateika** [microsoft/playwright#9417]
Something like this maybe:
```
test('some test', async ({ page }) => {
  test.meta({param1: 'value1', param2: 'value2'})
  // ...
})
```
In my use case, it would be useful to add TMS link/id, user's username (users in tests are created on-demand).

I've looked into documentation and GH issues and it seems there's no such feature or request now.

**Comment by rwoll** [comment]
See `testInfo.attachments`: https://playwright.dev/docs/api/class-testinfo#test-info-attachments

Does this work for your use case?

**Comment by yury-s** [comment]
Would `test.info` and its `test.info.attachments` work for you if it accessed current testInfo?

**Comment by Mictim** [comment]
> Would `test.info` and its `test.info.attachments` work for you if it accessed current testInfo?

Is this approach already implemented?
If it is not, It would be nice to have it.

**Comment by rwoll** [comment]
> > Would `test.info` and its `test.info.attachments` work for you if it accessed current testInfo?
> 
> 
> 
> Is this approach already implemented?
> 
> If it is not, It would be nice to have it.

Not yet, and I don't think there are immediate plans to support accessing `info` directly off `test` due to some larger design and implementation considerations that would lock the runner into: https://github.com/microsoft/playwright/pull/10121#issuecomment-965866736

For now, access is via `testInfo` which you'll have to plumb through to any helpers.

cc: @dgozman

**Comment by awarecan** [comment]
I like `testProject.metadata`, can we have similar `testInfo.metadata`?

**Comment by dgozman** [comment]
Depending on the type of metadata - heavy attachment or light-weight annotation - there are currently two separate APIs. Many reporters show annotations inline and provide links to attachments.

- Attachment.
  ```js
  // Obtain an image, for example a screenshot
  const image = await page.screenshot();
  // Attach the image.
  await test.info().attach('my-image', { body: image, contentType: 'image/png' });
  ```

- Annotation. There is a room for making this a bit nicer, but no specific plans as of today.
  ```js
  // Add a light-weight annotation.
  test.info().annotations.push({ type: 'issue', description: 'https://github.com/microsoft/playwright/issues/9417' });
  ```
