### ISSUE TITLE
[Question] Can I get distinct list of exists tags on my PW project?

### ISSUE THREAD

**Issue by AndreyMelnichenko** [microsoft/playwright#9427]
Hi Playwright Team!

Could you please help, is there any commands to get distinct list of exists tags on my PW project at PW v1.15.1?
Similar with 
`playwright test --list `

**Comment by yury-s** [comment]
What do you mean by "distinct list of exists tags" ?

**Comment by yury-s** [comment]
There is no such command (I assume your are talking about [test tags](https://playwright.dev/docs/test-annotations#tag-tests).
