### ISSUE TITLE
[BUG] Firefox does not start in this linux docker container

### ISSUE THREAD

**Issue by bpasero** [microsoft/playwright#945]
**Context:**
- Playwright Version: 0.10.0
- Operating System: Linux
- Extra: Docker

We are using the following build configuration: https://github.com/microsoft/vscode-linux-build-agent/blob/master/x64/Dockerfile

Using Firefox in Playwright results in:

```
XPCOMGlueLoad error for file /__w/1/s/node_modules/playwright-core/.local-firefox/linux-1021/firefox/libxul.so: 

/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /__w/1/s/node_modules/playwright-core/.local-firefox/linux-1021/firefox/libxul.so) 

Couldn't load XPCOM. 

(node:5179) UnhandledPromiseRejectionWarning: Error: Failed to launch browser!
```

**Comment by larrywax** [comment]
I have encountered the same problem, you need to use a newer base image with a version of `glibc` >= 2.27. 
`node:buster` is fine

**Comment by arjun27** [comment]
Hey @bpasero, Firefox support requires Ubuntu 18+ at this point ([libc6 versions on Debian](https://packages.debian.org/search?keywords=libc6)). Can that be changed in your config? Closing this as a min requirement, can re-open if that doesn't work for you.
