### ISSUE TITLE
[Feature] add support for `async` iterator to `page.evaluateHandle`

### ISSUE THREAD

**Issue by mindplay-dk** [microsoft/playwright#9461]
I'm writing a program that runs in the browser and continuously returns a stream of results.

The idiomatic way to do this in modern JavaScript, is to use an async generator.

There is no obvious way to use async generators, or other iterators - here is an examples and my current solution:

```ts
import { chromium, JSHandle, Page } from "playwright";

const browser = await chromium.launch();
const context = await browser.newContext();
const page = await context.newPage();

const sequenceIterator = await page.evaluateHandle(() => {
  async function* generateSequence(start: number, end: number) {
    for (let i = start; i <= end; i++) {
      await new Promise(resolve => setTimeout(resolve, 200));

      yield i;
    }
  }

  return generateSequence(1, 4);
});

async function* evaluateIterator<T>($iterator: JSHandle<AsyncIterator<T>>) {
  while (true) {
    const { value, done } = await $iterator.evaluate(iterator => iterator.next());

    if (done) break;

    yield value;
  }
}

for await (const value of evaluateIterator(sequenceIterator)) {
  console.log(value);
}

await page.close();
await context.close();
await browser.close();
```

Because the iterator is behind a `JSHandle`, you can't simply `for await` over the handle itself - to get a working async iterator from a *handle* to an async iterator, you have to manually `await` the return-values from each call to the iterator's `next` method, and check the return-values.

It took me a few hours to figure this out - I think it would be worth adding this to the framework, making it easy for others?

My suggestion would be to make `JSHandle` itself an *iterable*. (not an iterat*or*.)

That is, make it implement the `AsyncIterable` generic interface, and in the implementation of the `[Symbol.asyncIterator]()` method, make it do essentially what I'm doing in my `evaluateIterator` helper function above.

This would make it completely natural and simple to working with handles to iterators - reducing my example to:

```ts
const sequenceIterator = await page.evaluateHandle(() => {
  async function* generateSequence(start: number, end: number) {
    for (let i = start; i <= end; i++) {
      await new Promise(resolve => setTimeout(resolve, 200));

      yield i;
    }
  }

  return generateSequence(1, 4);
});

for await (const value of sequenceIterator) {
  console.log(value);
}
```

(Note that, due to the async nature of handles, we can probably only make this work with async iterables, and not with synchronous iterables? Unless perhaps there is some way to wrap a synchronous iterable in an asynchronous iteratable - I guess this might be tricky in terms of type-hinting, not sure.)

What do you think?

**Comment by mindplay-dk** [comment]
The extra complexity would be 5 lines of code, plus some types that would be difficult for most people to figure out.

`JSHandle` didn't strictly need to support Promises either - but the nature of pretty much everything that happens inside the browser environment is asynchronous, so it seems only natural to support these things.

I don't like adding complexity to anything - but this was quite difficult to figure out, and I think this would help the next person pass this hurdle very easily and intuitively. Promises "just work" - it would be great if iterators also "just worked" without having to delve into inner workings of async iterators. 🙂

**Comment by simwai** [comment]
I would like to see this too. Good idea.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
