### ISSUE TITLE
[Feature] global beforeEach/beforeAll hooks

### ISSUE THREAD

**Issue by Tomsk666** [microsoft/playwright#9468]
Instead of having the same test.beforeEach hook defined in every file, how do I only define the beforeEach hook in a single file (say hooks.js) at a global level, so then each file can use that hook?
In other words define my hooks in a single file once, but hooks are then used by all of my tests in all my spec files?
Thanks

**Comment by yury-s** [comment]
Similarly to [test fixture](https://playwright.dev/docs/next/test-fixtures#test-fixtures) you can do it in a separate file and then import `test` from that file to your tests:

```ts
// testWithBeforeEach.ts
import { test } from '@playwright/test'

test.beforeEach(() => {
    console.log('beforeEach');
})

export default test
```

```ts
// mytest-1.spec.ts
import { test } from './testWithBeforeEach'

test('should work 1', async ({ page }) => {
})
```

```ts
// mytest2.spec.ts
import { test } from './testWithBeforeEach'

test('should work 2', async ({ page }) => {
})
```

**Comment by Tomsk666** [comment]
Brilliant, thanks @yury-s  that's fixed it, all working.

**Comment by Tomsk666** [comment]
Thanks @yury-s I'll try some of these options out & see how I get on.
Maybe we could add it as a feature request, as many other frameworks like Mocha, Cucumber, Cypress have global hooks.
It'd be great just to put all the hooks in one file say called hooks.js, then in the Playwright config be able to have a parameter like globalHooks: './hooks.js' that would then mean all tests would use the global before/afterEach. Even beeter would be that if you then defined a local beforeEach in a test file, then that would have precendece over the global, so you had both options.
As you can tell I'm not a deveoper so no idea how hard this would be to implement.
Anyway thanks for your help, really enjoying & impressed with Playwright.

**Comment by F3n67u** [comment]
I will support theh global hook feature. global hook is easier to use than the fixture pattern.

**Comment by cunhabruno** [comment]
@yury-s that would be great to have this feature, I have tried using a `beforeAll` in a separate file as you recommended but if the test fails the retry will not call this `beforeAll` because the retry is only for the current spec file. The same problem happened adding in a Playwright fixture

**Comment by DamayantiRathore** [comment]
Waiting for any update on this feature request 💯

**Comment by saurabh4888** [comment]
@yury-s Any plan to implement this feature...it would be great to have global hooks for easier handling

**Comment by lifeart** [comment]
Up

**Comment by skozin-tns** [comment]
Is there a plan to implement this feature? It would be super helpful

**Comment by liranelisha** [comment]
this is really needed

**Comment by Krisell** [comment]
We had some trouble implementing a global beforeEach, using the initial suggestion here. It only ran before some early tests (but not once per worker, perhaps once per core regardless of worker-setting?).

However it looks like we have now found a solution based on the ideas here:

``` ts
import { test as base } from '@playwright/test'

export const test = base.extend({
  page: async ({ baseURL, page }, use) => {
    // We have a few cases where we need our app to know it's running in Playwright. 
    // This is inspired by Cypress that auto-injects window.Cypress.
    await page.addInitScript(() => { 
      (window as any).Playwright = true 
    })

    // Here we can enable logging of all requests, which is useful to see sometimes.
    // We also block some unnecessary third-party requests which speeds up the tests.
    await page.route('**/*', route => { 
      ...
```

And in our tests we import `test` from the file above instead of from `'@playwright/test'`. This is of course easy to forget, so a configurable way to do the same thing would be even better.

**Comment by uncvrd** [comment]
Have to agree with @Krisell here. For some reason, my auto fixture for beforeEach only runs one time, instead on each test _unless_ I run the suite in debug mode...not sure why that makes a difference but it does.

Here's my example:

```
const seedTest = base.extend<{ dbSeed: void }>({
  dbSeed: [async ({  }, use) => {

    execSync("npx prisma db seed");

    await use();

  }, { auto: true, scope: "test" }]
})
```

Where I have two tests here using the extended fixture:

```
seedTest.describe("Links", () => {

  seedTest.beforeEach(async ({ page }) => {

    await page.goto("/workspaces/links");

  })

  seedTest("creates a track link setting and sets as default", async ({ page }) => {
    
    // test code
    
  })

  seedTest("deletes a track link setting", async ({ page }) => {

   // test code

  })

})
```

Which results in my `dbSeed` command only running **once** unless I run the tests in debug mode, then it runs each time 🤔

**Comment by sbousamra** [comment]
Any updates on this? Would love this feature

**Comment by taramk** [comment]
+1 for this

**Comment by anhskrttt** [comment]
+1

**Comment by JanMosigItemis** [comment]
+1

**Comment by iburahim786** [comment]
[yury-s](https://github.com/yury-s) This is a highly recommended feature for all tests, Please add in the feature quickly. UPVOTES (1000)

**Comment by fmagaldea** [comment]
This feature would help a lot, hope it will be implemented soon.

**Comment by BaneVredniMrav** [comment]
+1

**Comment by Studigrad** [comment]
+1

**Comment by samlader** [comment]
+1

**Comment by JohnnyChiang** [comment]
+1

**Comment by antebudimir** [comment]
> Following [this](https://playwrightsolutions.com/how-do-you-set-hooks-before-or-after-each-spec-globally-in-playwright-test/), I was able to get essentially the equivalent of a beforeEach and afterEach for each test case (even with just 1 worker), so thought I'd post it here for others. Hope it helps!

I've expanded on this to be able to intercept multiple api calls for different pages, e.g. this is my homepage-setup.ts:
`
import { test as base, expect } from '@playwright/test';
import { mockFilterCategories } from '@mocks/handlers';
import { API_FILTER_CATEGORIES, CONTENT_TYPE_JSON, STATUS_OK } from '@constants';

interface MockConfig {
  url: string | RegExp;
  response: {
    status: number;
    contentType: string;
    body: Record<string, unknown> | unknown[];
  };
}

const MOCKED_ROUTES: MockConfig[] = [
  {
    url: `**/${API_FILTER_CATEGORIES}`,
    response: {
      status: STATUS_OK,
      contentType: CONTENT_TYPE_JSON,
      body: mockFilterCategories,
    },
  },
];

const test = base.extend({
  page: async ({ page }, use) => {
    for (const mockConfig of MOCKED_ROUTES) {
      await page.route(mockConfig.url, (route) => {
        route.fulfill({
          status: mockConfig.response.status,
          contentType: mockConfig.response.contentType,
          body: JSON.stringify(mockConfig.response.body),
        });
      });
    }

    await use(page);

    for (const mockConfig of MOCKED_ROUTES) {
      await page.unroute(mockConfig.url);
    }
  },
});

export { expect, test };
`

**Comment by antebudimir** [comment]
> Following [this](https://playwrightsolutions.com/how-do-you-set-hooks-before-or-after-each-spec-globally-in-playwright-test/), I was able to get essentially the equivalent of a beforeEach and afterEach for each test case (even with just 1 worker), so thought I'd post it here for others. Hope it helps!

I've expanded on this to be able to intercept multiple api calls for different pages, e.g. this is my homepage-setup.ts:
```
import { test as base, expect } from '@playwright/test';
import { mockFilterCategories } from '@mocks/handlers';
import { API_FILTER_CATEGORIES, CONTENT_TYPE_JSON, STATUS_OK } from '@constants';

interface MockConfig {
  url: string | RegExp;
  response: {
    status: number;
    contentType: string;
    body: Record<string, unknown> | unknown[];
  };
}

const MOCKED_ROUTES: MockConfig[] = [
  {
    url: `**/${API_FILTER_CATEGORIES}`,
    response: {
      status: STATUS_OK,
      contentType: CONTENT_TYPE_JSON,
      body: mockFilterCategories,
    },
  },
];

const test = base.extend({
  page: async ({ page }, use) => {
    for (const mockConfig of MOCKED_ROUTES) {
      await page.route(mockConfig.url, (route) => {
        route.fulfill({
          status: mockConfig.response.status,
          contentType: mockConfig.response.contentType,
          body: JSON.stringify(mockConfig.response.body),
        });
      });
    }

    await use(page);

    for (const mockConfig of MOCKED_ROUTES) {
      await page.unroute(mockConfig.url);
    }
  },
});

export { expect, test };
```

**Comment by terrymun** [comment]
Thanks @Krisell, we ran into an issue where we want to disable JS-based animations on our app and your solution of introducing a global flag worked :) 

With regards to this:

> And in our tests we import `test` from the file above instead of from `'@playwright/test'`. This is of course easy to forget, so a configurable way to do the same thing would be even better.

...our solution is simply to setup an eslint `no-restricted-import` rule to ensure that users do not import `test` from `@playwright/test` by accident:

```ts
{
  files: ['**/*.e2e.ts'],
  rules: {
    'no-restricted-imports': [
      'error',
      {
        paths: [
            name: '@playwright/test',
            importNames: ['test'],
            message: 'Please import `test` from fixtures.ts instead',
          },
        ],
      },
    ],
  },
},
```

**Comment by Krisell** [comment]
> ...our solution is simply to setup an eslint `no-restricted-import` rule to ensure that users do not import `test` from `@playwright/test` by accident:

That is brilliant, thanks! It looks like the default import can also be used as the `test` function, so I added `'default'` to the restricted import names as well.

**Comment by caseyjhol** [comment]
@yury-s I'm a little confused - how does https://github.com/microsoft/playwright/commit/acd2a4ddade8b38eec5e967e31493104ca26d25e solve the `beforeAll` problem if you only have 1 worker? It still only runs once per worker, even if you have multiple specs.

**Comment by silverwind** [comment]
These fixture-based solution seem impractival  because  they require changing every test file to change the `test`. I would appreciate a solution that does not requre to alter every test.

**Comment by terrymun** [comment]
@silverwind I might be missing something but I am not seeing an issue here. I don't think it's that difficult to replace the `test` command? You can have an eslint rule set up to throw an error whenever it's imported from the wrong source, and then do a project-wide search and replace.

**Comment by silverwind** [comment]
Sure, it's not a hard refactor, but it's still a necessary code change that could be avoided if only there were an better API. For example in Jest, one can have global beforeEach/afterEach defined in a setup file, which is ideal imho:

https://stackoverflow.com/a/50302253/808699

**Comment by Narretz** [comment]
Coming from Cypress to playwright, it's painful to see how many convenience functions like this are missing, especially since it has many other convenience functions that Cypress doesn't have.
