### ISSUE TITLE
[Feature] Add ability of taking screenshot after test.step is finished

### ISSUE THREAD

**Issue by tymfear** [microsoft/playwright#9481]
Would great to have a way of tacking screenshot when the `test.step` function is finished, so that it is visible on Allure report.
Maybe some optional parameter, or maybe some step object passed to the callback that have screenshot function, like
```javascript
test.step('do stuff',() => {
  step.screenshot('some name here')
}, {screenshot: true});
```
or
```javascript
test.step('do stuff', step => {
  step.screenshot('some name here')
});
```

**Comment by TimeInvestor** [comment]
This will be a very helpful feature.
I'd like to see it gets implemented as well.

**Comment by 07701937922** [comment]
![image](https://user-images.githubusercontent.com/92496510/137250141-b659b72f-26aa-48da-86cb-69176a38d113.jpeg)

**Comment by tymfear** [comment]
Actually I figured it out.
You can use [testInfo](https://playwright.dev/docs/api/class-testinfo#test-info-attachments) object to do that.
Kind of
```typescript
test.step('do stuff' => {
  const path = testInfo.outputPath('screenshot.png');
  await page.screenshot({ path });
  testInfo.attachments.push({ name: 'step name', path, contentType: 'image/png' });
});
```

**Comment by ani-im** [comment]
Do we have any updates for this feature? Or deadlines?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
