### ISSUE TITLE
[Question] Is there any prebuilt image to record videos of tests?

### ISSUE THREAD

**Issue by orihomie** [microsoft/playwright#9500]
With preinstalled virtual displays, codecs, etc.

**Comment by yury-s** [comment]
You are running the browser in [headful mode](https://github.com/orihomie/jest-playwright-no-video/blob/0071a81e598e73c88abe3ed26c533010be1519be/jest.e2e.config.js#L16-L18) while docker doesn't have X server, run with `headelss: false` and you want need neither X server nor xvfb. If jest cannot record videos in headless mode please file a bug in their repo.

**Comment by orihomie** [comment]
That's just my mistake, if you change it, you still wont see any recorded video's and NO, that is not jest's problem, jest is just a runner for launching tests.
