### ISSUE TITLE
[BUG] Error: Cannot find parent object browser-context to create handle

### ISSUE THREAD

**Issue by mhils** [microsoft/playwright#9509]
I'm running into a tricky-to-debug error on some playwright 1.15.1 Firefox instances running on Ubuntu 20.04:

1. `browser.newPage` fails with `Error: browserContext.newPage: Target page, context or browser has been closed`
2. I'm restarting the browser instance (attempting `.close()` and then `.launchPersistentContext`)
3. My entire program to crash with this error:
```
/root/node_modules/playwright/lib/client/connection.js:239
    if (!parent) throw new Error(`Cannot find parent object ${parentGuid} to create ${guid}`);
                 ^

Error: Cannot find parent object browser-context@b4f4e2cd68047fb07dc6c921f97ff268 to create handle@af6d39c5764141f3f461b54387ab4910
    at Connection._createRemoteObject (/root/node_modules/playwright/lib/client/connection.js:239:24)
    at Connection.dispatch (/root/node_modules/playwright/lib/client/connection.js:180:12)
    at Immediate.<anonymous> (/root/node_modules/playwright/lib/inprocess.js:45:83)
    at processImmediate (node:internal/timers:464:21)
```

Note that 1) and 2) happen relatively often but intermittedly, I don't have a good repro unfortunately. Sometimes the machine recovers just fine after restart.

Do you folks have any input on what would be the best way to debug this further?

**Comment by yury-s** [comment]
It only reproduces in Firefox, right?

**Comment by mhils** [comment]
I haven't seen any more crashes after updating to `1.16.0-next-alpha-oct-18-2021`, so I suspect that #9563 did the trick for this issue as well. I'll close here, which hopefully doesn't jinx it. 😄
