### ISSUE TITLE
[Feature] Aggregate test pass/failure ratio when using `repeatEach`

### ISSUE THREAD

**Issue by joeljeske** [microsoft/playwright#9541]
Using `repeatEach` is good way to see if you have flaky tests. Currently, the log output seems to all be interleaved together making it difficult to spot if some tests are more commonly failing then others. 

It would be helpful if all the tests were printed out and aggregated together. The following stats seems like they would be useful for most people when they use `repeatEach`

* Pass/Fail ratio of all the runs for that given test
* Min/Max/Average time of each test run

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
