### ISSUE TITLE
[Feature] Expose Rawer V8 coverage information

### ISSUE THREAD

**Issue by lukeapage** [microsoft/playwright#955]
see also this issue from puppeteer: https://github.com/puppeteer/puppeteer/issues/2136

I've been trying to get puppeteer-to-instanbul to work with playwright - and I see the puppeteer and playwright implementations are the same - but I'm not getting very good information back - playwright destroys function call information, collapses the ranges and doesn't record call counts - which makes the underlying library v8-to-istanbul (which is used afaik by the node teams and as an experimental feature in jest) not viable.

**Comment by pavelfeldman** [comment]
Sounds good, we should expose raw V8 snapshot in CrCoverage.
