### ISSUE TITLE
[Feature] Show the beforeAll, beforeEach, afterAll and afterEach steps in trace-viewer

### ISSUE THREAD

**Issue by ryanrosello-og** [microsoft/playwright#9550]
It would be really nice if the trace viewer showed the steps undertaken in the beforeAll, beforeEach, afterAll, afterEach for each test rather just showing the test results.

#trace-viewer
Playwright v1.15

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/8682
