### ISSUE TITLE
[Feature] Show UTC timestamps for each entry in the Actions/Log in the Trace-Viewer

### ISSUE THREAD

**Issue by ryanrosello-og** [microsoft/playwright#9551]
Howdy, It would be really good to see UTC timestamps for each action undertaken and possibly in the LOG sections too.
Also, if possible - try and show the times as per the users timezone

#trace-viewer
Playwright v1.15

**Comment by yury-s** [comment]
Is current combination of action duration + timeline strip not sufficient? adding timestamps would add a lot of noise to the UI but it's unclear what advantages it give compare to the current timeline.

**Comment by ryanrosello-og** [comment]
Good point, at the very least it would be good to know the start / end times of the execution.  We currently run tests frequently and attach multiple trace.zip files, we need context as when the test run started
