### ISSUE TITLE
[Feature] Provide an ability to open VSCode directly from Source tab in the trace-viewer

### ISSUE THREAD

**Issue by ryanrosello-og** [microsoft/playwright#9553]
It would be great if we could somehow click a link from the Source tab in any of the Actions in the trace-viewer.  Clicking this link can either open the Spec file directly or it could open the file and automatically go to the line of code you are interested in.

**Example**:

![image](https://user-images.githubusercontent.com/50574915/137550326-483b1b27-238d-4c52-951f-656bdb98ef92.png)

Things to consider:
- need a path to where vscode exists?
- should we support any other code editor?

#trace-viewer
Playwright v1.15

**Comment by mxschmitt** [comment]
I
Reference: https://github.com/microsoft/vscode/issues/4883#issuecomment-270141535

For example: `vscode://file//Users/max/development/try-playwright/worker-javascript/Dockerfile:21`

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
