### ISSUE TITLE
[Feature] Provide an ability for Playwright to configure the file names of the generate trace-viewer files to match the name of the test

### ISSUE THREAD

**Issue by ryanrosello-og** [microsoft/playwright#9569]
Would it be possible to always use the test name as the file name of the trace.zip file?

Currently we upload numerous `trace.zip` files as build artefacts in our CI but when we download these files from the build server, we have no easy way of distinguishing which `trace.zip` belongs to which test?  It would be nice if we had a way to configure Playwright to generate the trace zip files names to match the actual test it ran against.

![2021-10-17_14-57-05](https://user-images.githubusercontent.com/50574915/137612389-a68c5f7a-a7e0-4b11-abaf-f716aaa01d10.png)

#trace-viewer #ux
Playwright 1.15

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
