### ISSUE TITLE
[Feature] Chains for Visibility and Nth

### ISSUE THREAD

**Issue by xuanzhaopeng** [microsoft/playwright#9573]
Given I have following html

```
<div>
                <div class="item" style="display: none">Hidden data0</div>
	       <div class="item">visible data1</div>
                <div class="item" style="display: none">Hidden data1</div>
	        <div class="item">visible data2</div>
</div>
```

When I wanna get 1st visible element
Then I should call `page.locator('.item >> visible=true >> nth=0')`
When I wanna get 2nd visible element
Then I should call `page.locator('.item >> visible=true >> nth=1')`

---- 

Currently the `nth=0` or `nth=1` doesn't work, it always return the 1st visible data

maybe there is some workaround but I haven't aware?

**Comment by xuanzhaopeng** [comment]
Or maybe you could point where  is this implementation, maybe we can have a look and improve it by another PR

**Comment by yury-s** [comment]
It's a bug, the following code

```js
  const locator = page.locator('.item >> visible=true').nth(1);
  console.log(await locator.textContent());
```

throws `locator.textContent: Error: strict mode violation: ".item >> visible=true >> nth=1" resolved to 2 elements:`
