### ISSUE TITLE
[BUG] Unknown scheme for .initialize after upgrade .net

### ISSUE THREAD

**Issue by nl-dave** [microsoft/playwright#9592]
**Context:**
- Playwright Version: 1.15.4 / 1.14.1
- Operating System: Windows
- Node.js version: 6.14.14
- Browser: All
- Extra: none

**Code Snippet**

```c#
class Program
    {
        static void Main(string[] args)
        {
            getPlaywright().GetAwaiter().GetResult();
        }
        static async Task getPlaywright()
        {
            await Playwright.CreateAsync();
        }
    }
```

**Describe the bug**

We've been using playwright 1.14.1 successfully for a while now. We recently went to upgrade the project to 1.15.4 and started getting "Unknown scheme for .initialize" on Playwright.CreateAsync(). We re-ran the npm and npx commands to reinstall playwright and still had the same issue. I created a blank project as seen above on 1.15.4 and saw the same issue. After rolling back to 1.14.1 everything worked as expected. .net c#

What did I miss in upgrading (or starting fresh) on 1.15.4?

**Comment by pavelfeldman** [comment]
What is your .net version? Is there a project you could share?
