### ISSUE TITLE
[BUG] `.click()` fails due to Chrome automation infobar

### ISSUE THREAD

**Issue by mhils** [microsoft/playwright#9615]
### Problem Description

In short, clicking elements at the bottom of the page fails silently when Chromium is launched with a persistent context. The click is not registered on the page.

`repro.js`
```javascript
const {chromium} = require("playwright");

(async () => {
    console.log("method", process.env["TMP_INSTANCE"] ? "launch" : "launchPersistentContext", "headless", !!process.env["HEADLESS"]);

    const opts = {headless: !!process.env["HEADLESS"], locale: "de-DE"};

    let browser;
    if (!!process.env["TMP_INSTANCE"])
        browser = await chromium.launch(opts);
    else
        browser = await chromium.launchPersistentContext("./tmpprofile", opts);

    const page = await browser.newPage();

    // visit azonline.de, click on "options" in the cookie dialog, and then wait for the cookie settings to appear.
    await page.goto('https://www.azonline.de/', {waitUntil: "networkidle"});
    await page.frame({url: /privacy-mgmt.com/}).click("button[title=Optionen]");
    await page.waitForSelector("iframe[src*=privacy-manager]", {timeout: 5000});
    await browser.close();
    console.log("ok");
})();
```

```
node .\repro.js
method launchPersistentContext headless false
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

page.waitForSelector: Timeout 5000ms exceeded.
=========================== logs ===========================
waiting for selector "iframe[src*=privacy-manager]" to be visible
============================================================
    at C:\Users\user\git\cookies\analysis\next\runner\repro.js:17:16 {
  name: 'TimeoutError'
}
```

This only affects _headed_ instances started with _launchPersistentContext_. Any other configuration (_headless_ or _launch_) passes:
```
> $env:TMP_INSTANCE=1
> node .\repro.js
method launchPersistentContext headless true
ok
```

I suspect this is related to the "this browser is being controlled by automated test software" infobar  (highlighted yellow below), which is only displayed in in persistent profile instances. This moves the button I'd like to press slightly out of the screen:

| `TMP_INSTANCE=1` | `TMP_INSTANCE=` |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1019198/137920529-61dc197a-9c65-4903-85d2-5695dea95366.png) | ![image](https://user-images.githubusercontent.com/1019198/137921121-78b0073d-1e8c-4b23-9301-fa082d529f04.png) |

For reference, here are `pw:api` and `pw:protocol` logs: https://gist.github.com/mhils/12774102c21fd4ba04ee6e6c69b0962c. I couldn't spot anything interesting, playwright thinks it clicked successfully. I'm not deep enough into the codebase to determine if this is a playwright or a Chromium bug.

**Context:**
- Playwright Version: 1.16.0-next-alpha-oct-18-2021
- Operating System: Windows

**Comment by pavelfeldman** [comment]
I landed a temporary workaround for this one, so things should work for you. But there is a deeper problem with the way Chrome manages the input routing for Out-of-process iframes. Instead of respecting the viewports, it gets confused by the browser windows.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
