### ISSUE TITLE
[Feature] html-reporter allow setting a baseUrl

### ISSUE THREAD

**Issue by Mischi** [microsoft/playwright#9652]
Hi,

while testing the new html reporter (which is awesome!) i noticed, that if i open the report on my build server and navigate, it navigates to the root url. It would be great if i could specify the baseUrl in playwright.config and the baseUrl being used and respected in the index.html of html report.

For example, i host the html report under the following url
`https://jenkins.some.domain/job/project/job/integration-tests/job/main/52/artifact/playwright-report/index.html` but if i open a test report, i navigate to  `https://jenkins.some.domain/?testId=77b5ea7de5776228bda2cfbba9c99d7a401573e1-c1f1f2547f3f625c59e05737314909f7ad4719c1`

In my config i would love to do:
```
['html', { baseUrl: `https://jenkins.some.domain/job/project/job/integration-tests/job/main/${process.env.BUILD_NUMBER}/artifact/playwright-report/index.html`}]
```

Thanks!

**Comment by pavelfeldman** [comment]
@Mischi yes, that's why I kept this issue open! I'll follow up in a separate change! It'll probably get into 1.16.1 in a week. 1.16 is about to go live.
