### ISSUE TITLE
[Question] Activate GPU rendering for Firefox Headless

### ISSUE THREAD

**Issue by herecy** [microsoft/playwright#9679]
It seems GPU rendering is not active when running Firefox in headless mode.
Is there any way to activate it?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
