### ISSUE TITLE
[Feature] allow multiple filters in --grep with -g tag1 -g tag2

### ISSUE THREAD

**Issue by ychaudhari** [microsoft/playwright#9682]
We have multiple tags in our test suites that we want to combine and run together in one CD stage. It would be great if we have an ability to provide multiple parameters like `-g tag1 -g tag2 -g tag3` in playwright/test CLI. 

Currently there are some issues in using `-g tag1|tag2` as discussed in this thread: 
https://playwright.slack.com/archives/C01AG7QGW2F/p1634755054418000

**Comment by pavelfeldman** [comment]
There are no issues with -g tag1|tag2, you just need to escape it if you use Windows cdm as discussed in that thread.

`-g tag1^|tag2`

**Comment by ychaudhari** [comment]
@pavelfeldman aha cool... thanks for that. Happy to close this
I'll comment on #9667 because that fix didn't work for me for some reason :(

**Comment by ffluk3** [comment]
@pavelfeldman Please forgive if this is discussed in the Slack thread, but I think there is still a valid use case to have the multiple grep/grepInvert tags. For example:

```json
{
  "scripts": {
    "e2e": "playwright --grep-invert \"@wip\""
  }
}
```

However, if I wanted to omit another tag on the fly, I wouldn't be able to run `npm run e2e -- --grep-invert @flaky`. Is there a recommended way to approach this use case?
