### ISSUE TITLE
[Question] How to wait for some element state ?

### ISSUE THREAD

**Issue by Amrkamel1** [microsoft/playwright#9686]
How to wait for an element to be enabled/appear/disappear ?

**Comment by caribou-code** [comment]
`waitForElementState` supported a state called `stable`. The definition of stable in the docs is:

```
Element is considered stable when it has maintained the same bounding box for at least two consecutive animation frames.
```

That's perfect, but the method only works on element handles, which are discouraged in favour of locators. `waitFor` on a locator doesn't support `stable` as an option, so it's not clear what the solution is here...
