### ISSUE TITLE
[monorepo]: updating package version is HARD

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#9689]
## Context

After the migration to a monorepo, it's hard to update package version.

As of today, what needs to be done:
1. Update version in `//package.json`
2. Run `npm run lint-packages`. This will propagate version to sub-packages
3. Update version from old to new one in `//package-lock.json` and `//packages/create-playwright/package-lock.json`. I usually use `sed` for this, for BSD sed it looks like this:
    ```bash
    $ sed -i '' -e 's/1.16.0-next/1.16.0/g' package-lock.json
    $ sed -i '' -e 's/1.16.0-next/1.16.0/g' packages/create-playwright/package-lock.json
    ```

The last part is especially tricky. Without doing so, the `npm install` call just fails.

**Comment by aslushnikov** [comment]
Unfortunately, `npm i` doesn't work - it crashes with some error :(

**Comment by mxschmitt** [comment]
Closing for now since we have a workaround
