### ISSUE TITLE
[Feature] html report: show full file source

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#9691]
- When I open test, I'd love to have an editor with the source of the test, scrolled to the test beginning
- When I click on the test steps, i'd love the editor to scroll and highlight the place where this step is

![image](https://user-images.githubusercontent.com/746130/138360611-9e523091-b639-44ce-b9ae-6b27a7b77a60.png)

**Comment by pavelfeldman** [comment]
Let's wait for a user request.
