### ISSUE TITLE
[BUG] Reuse authentication state does not work with electronApplication. 

### ISSUE THREAD

**Issue by calcaide** [microsoft/playwright#9694]
**Context:**
- Playwright Version: 1.15.0
- Operating System: Mac with M1 chip.
- Node.js version: v14.17.1
- Browser: electronApplication (chromium)

**Code Snippet**

```javascript
const { test, expect } = require('@playwright/test');
const { _electron: electron } = require('playwright');

let electronApp = null;

test.beforeEach(async () => {
  electronApp = await electron.launch({
    executablePath: executablePath,
    env: {
      NODE_ENV: 'test',
    },
  });
});

test.only('Load auth state', async () => {
    const appWindow = await electronApp.firstWindow(); // The window that contains the app.
    const context = await electronApp.context();
    // Persist authentication state
    await context.storageState('authState.json');
});
```

**The bug**

Hi there

I am adding end to end tests to an electron app. First thing I wanted to test is to share authentication state between tests, so I just need to log in once.
On the documentation, I found an excellent guide showing how to do it [link here](https://playwright.dev/docs/auth#reuse-authentication-state).
Tried to reproduce that using `electronApplication` class to get the context, but once I try `context.storageState('pathTojsonFile')` I receive next error:
`browserContext.storageState: Protocol error (Storage.getCookies): Browser context management is not supported.`

I understand `electronApplication` is under experimental support and perhaps the way of persisting and loading state might differ. If `context.storageState` is not the way to go in this use case, can you please provide a way to persist and load `localStorage` state?

P.S: Playwright is awesome, thanks for such a nice library.

**Comment by mattd233** [comment]
Hi, can you please give a more detailed example? 
This is what I have:
saving:
```javascript
const localStorage = await page.localStorage;
  await page.evaluate((context) => {
    localStorage.setItem('auth-state', context);
  }, localStorage);
  await page.reload();
```
reading:
```javascript
const localStorage = await page.evaluate(() => {
  return Object.keys(localStorage).map((name) => ({ name, value: localStorage.getItem(name) }));
});
```
but I can't seem to read anything from this localStorage, did I do something wrong here?

**Comment by GP-QA** [comment]
We also have the same issue in our E2E test project.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by nicollbryla** [comment]
Hi @mattd233 did you manage to solve this issue? If yes, do you remember what was wrong in you code?
