### ISSUE TITLE
[BUG] Hangs trying to access an Electron <webview>

### ISSUE THREAD

**Issue by andersk** [microsoft/playwright#9695]
**Context:**
- Playwright Version: 1.16.0
- Operating System: Linux
- Node.js version: 14.18.0
- Browser: Electron 15.2.0

**Code Snippet**

```js
// index.js
const { app, BrowserWindow } = require("electron");

app.whenReady().then(() => {
  const win = new BrowserWindow({ webPreferences: { webviewTag: true } });
  win.loadFile("index.html");
});
app.on("window-all-closed", () => {
  app.quit();
});
```

```html
<!-- index.html -->
<title>Test app</title>
<webview src="https://playwright.dev"></webview>
```

```js
// test.js
const { _electron } = require("playwright-core");

(async () => {
  const app = await _electron.launch({ args: ["."] });
  const win = await app.firstWindow();
  await win.waitForLoadState();
  for (const [i, frame] of win.frames().entries()) {
    await frame.waitForLoadState();
    console.log("frame", i, "url =", frame.url());
    console.log("frame", i, "title =", await frame.title());
  }
  app.close();
})();
```

**Describe the bug**

When I ask for the title of `win.frames()[1]`, which should be the `<webview>`, Playwright just hangs forever.

```console
$ npm i electron playwright-core
$ node test.js 
frame 0 url = file:///home/anders/zulip/test/playwright-electron-test/index.html
frame 0 title = Test app
frame 1 url = about:blank
[…hangs…]
^C
$ DEBUG=pw:api node test.js 
  pw:api => electron.launch started +0ms
  pw:api <= electron.launch succeeded +387ms
  pw:api => electronApplication.firstWindow started +1ms
  pw:api <= electronApplication.firstWindow succeeded +0ms
  pw:api => page.waitForLoadState started +0ms
  pw:api   navigated to "about:blank" +6ms
  pw:api   "domcontentloaded" event fired +3ms
  pw:api   "domcontentloaded" event fired +1ms
  pw:api   "load" event fired +3ms
  pw:api <= page.waitForLoadState succeeded +0ms
frame 0 url = file:///home/anders/zulip/test/playwright-electron-test/index.html
  pw:api => frame.title started +2ms
  pw:api   "load" event fired +0ms
  pw:api <= frame.title succeeded +16ms
frame 0 title = Test app
frame 1 url = about:blank
  pw:api => frame.title started +0ms
  pw:api   "domcontentloaded" event fired +350ms
  pw:api   "load" event fired +47ms
  pw:api   "networkidle" event fired +79ms
[…hangs…]
```

Other operations like `await frame.content()` and `await frame.$("body")` similarly hang.

**Comment by andersk** [comment]
I found as a workaround that I’m able to get the `Page` object for the `<webview>` using `app.waitForEvent("window")`. It’s not quite fully functional though: #9729.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by andersk** [comment]
This is still broken with current Playwright 1.27.1 and Electron 21.2.0. Thanks for reopening.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
