### ISSUE TITLE
[Feature] Visual Comparison Of Two Image Buffers

### ISSUE THREAD

**Issue by jjeff** [microsoft/playwright#9696]
Looking at the [the Visual Comparisons documentation](https://playwright.dev/docs/test-snapshots/), the way to match (or differentiate) two screenshots, is to use [`.toMatchSnapshot()`](https://jestjs.io/docs/expect#tomatchsnapshotpropertymatchers-hint), similar to the following example:

```TS
test('make sure two screenshots match', async ({page}) => {
  const screenshot1: Buffer = await page.screenshot()
  const screenshot2: Buffer = await page.screenshot()
  expect(screenshot1).toMatchSnapshot(screenshot2) // <-- typescript syntax error for `screenshot2`
})
```

However, while `expect()` is perfectly happy to handle a Buffer argument, `.toMatchScreenshot()` is not happy. It seems to want the path to an image file - the 'name' argument (a string).

Is there a way to compare two screenshots without writing a file to disk? Am I missing something? 

There should be a way to do a visual comparison of two images as Buffers.

**Comment by aslushnikov** [comment]
> Is there a way to compare two screenshots without writing a file to disk? Am I missing something?

@jjeff There's none so far. Why is the following not good-enough for you?

```js
test('make sure two screenshots match', async ({page}) => {
  // compare first and second page.screenshot() to the same image.png
  expect(await page.screenshot()).toMatchSnapshot('image.png');
  expect(await page.screenshot()).toMatchSnapshot('image.png');
})
```

> There should be a way to do a visual comparison of two images as Buffers.

Do you expect to see an image diff of such a comparison in the HTML report?

**Comment by jjeff** [comment]
> @jjeff There's none so far. Why is the following not good-enough for you?

It's actually more about comparing difference rather than equality. I want to take a screenshot (into a buffer), then perform some action, then take another screenshot (into a buffer), and compare them to ensure that the page *changed*. So I'm not comparing to a stored "perfect" image, instead I'm doing a much more general "make sure the page changed" comparison.

> > There should be a way to do a visual comparison of two images as Buffers.
> 
> Do you expect to see an image diff of such a comparison in the HTML report?

I do not need to see an image diff. I just need to know that it did change. Image diffs are nice, but not necessary for my purposes.

**Comment by aslushnikov** [comment]
@jjeff I see. In this case, how about using either `expect(buf1).not.toEqual(buf2)` or `expect(buf1.equals(buf2)).toBe(false)`: 

```js
test('enable dark-mode', async ({page}) => {
  const screenshot1: Buffer = await page.screenshot()
  await selectMenuItem('dark-mode')
  const screenshot2: Buffer = await page.screenshot()
  expect(screenshot1).not.toEqual(screenshot2);
  // alternatively:
  // expect(screenshot1.equals(screenshot2)).toBe(false);
})
```

**Comment by aslushnikov** [comment]
Looks like the discussion has staled, so closing this. Feel free to re-file if this is still relevant!

**Comment by davidglezz** [comment]
Please reopen.

My use case is to compare 2 images without having to save it to disk and display the results as with `.toMatchSnapshot()`.

I would like to suggest the matcher `.toMatchScreenshot(pathOrBuffer: Buffer | string)` or `.toMatchImage(...)`

```
test('make sure two screenshots match', async ({page}) => {
  const screenshot1: Buffer = await page.screenshot()
  const screenshot2: Buffer = await page.screenshot()
  expect(screenshot1).toEqual(screenshot2)
})
```
Current result:
<img width="560" alt="image" src="https://user-images.githubusercontent.com/194784/156944858-719e2793-149c-4f3e-ac4a-0ca290cef063.png">

Desired result:
<img width="593" alt="image" src="https://user-images.githubusercontent.com/194784/156946859-8cae4278-b3a7-4daa-993f-7b2f4ddc5aca.png">

**Comment by adamculpepper** [comment]
I'm trying to do a similar thing where I have 500+ sites with each having a dev and prod version pairing and a image buffer feeling like the best solution here instead of a golden image, considering the golden image concept is comparing against an image that shouldn't have changed instead of two websites that shouldn't be different. If I were to jam my use-case into the golden image concept, I would have to make the prod site be the golden image, compare against what's on dev and then have to manage when to --update-snapshot triggers when a deployment goes out. I just need to be able to say are these two websites identical? No? Then show me the diffs between the two. CC: @aslushnikov

**Comment by adamculpepper** [comment]
Follow-up to my previous comment; this code needs a bit of polish, but works for what I'm needing to do:

```
testSites.forEach((site, index) => {
    test(`Test ${index}: Comparing ${site[0]} to ${site[1]}`, async ({context}, testInfo) => {
        const page1 = await context.newPage();
        await page1.goto(site[0]);
        await page1.waitForLoadState('domcontentloaded');
        const snap1: Buffer = await page1.screenshot({
            fullPage: true,
            path: `${testInfo.snapshotDir}/1/1-${testInfo.project.name}-${testInfo.snapshotSuffix}.png`,
        });

        const page2 = await context.newPage();
        await page2.goto(site[1]);
        await page2.waitForLoadState('domcontentloaded');
        await page2.screenshot({
            fullPage: true,
            path: `${testInfo.snapshotDir}/2/2-${testInfo.project.name}-${testInfo.snapshotSuffix}.png`,
        });

        expect(snap1).toMatchSnapshot(['2', '2.png']);

        await context.close();
    });
});
```

**Comment by oleksiisedun** [comment]
@aslushnikov please reopen this issue.

**Comment by EgorBodnar** [comment]
After the release of the feature #11319, it would be possible to do so and render the form for image comparison same like Allure 2.0 has.
