### ISSUE TITLE
[Question] How to avoid opening of the HTML report?

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#9702]
Hi folks!
I have a question.
The HTML report opens automatically after a test was finished.
![2021-10-22_10h09_55](https://user-images.githubusercontent.com/52656401/138413440-db9605f1-31b5-4e50-a327-09c5965d3163.png)
 
![image](https://user-images.githubusercontent.com/52656401/138413593-13dc0663-09e2-4444-ac37-14ba4cf0b8ce.png)

Is any option to avoid it? In the case of the CI run, it can create a problem if ut opens in automatically way.

**Comment by mxschmitt** [comment]
This got implemented in https://github.com/microsoft/playwright/pull/9889

**Comment by apotrebin** [comment]
```
// playwright.config.ts
import { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  reporter: [ ['html', { open: 'never' }] ],
};
export default config;
```

**Comment by odinho** [comment]
Would be nice to have it on the command line as well, or might that already be possible?

**Comment by debuglevel** [comment]
> Would be nice to have it on the command line as well, or might that already be possible?

bash and many other shells: `$ PWTEST_SKIP_TEST_OUTPUT=1 npx playwright test` :)
PowerShell: `$env:PWTEST_SKIP_TEST_OUTPUT=1; npx playwright test` (although this does not quite the same as you had to unset it afterwards)

**Comment by styurenkov-b2broker** [comment]
will this this work?
I need a report on second test only
`PWTEST_SKIP_TEST_OUTPUT=1 npx playwright test && npx playwright test`

**Comment by serefarikan** [comment]
is `PWTEST_SKIP_TEST_OUTPUT=1` still supposed to work? It is not stopping the test report from being served if any of the tests fail. This is under Ubuntu 20.04 using bash, with `PWTEST_SKIP_TEST_OUTPUT=1 yarn playwright test`. [This more recent issue](https://github.com/microsoft/playwright/issues/11773) suggest `CI=1` should be used. Can someone confirm this env var is still supposed to work?

**Comment by satyak-trellix** [comment]
> is `PWTEST_SKIP_TEST_OUTPUT=1` still supposed to work? It is not stopping the test report from being served if any of the tests fail. This is under Ubuntu 20.04 using bash, with `PWTEST_SKIP_TEST_OUTPUT=1 yarn playwright test`. [This more recent issue](https://github.com/microsoft/playwright/issues/11773) suggest `CI=1` should be used. Can someone confirm this env var is still supposed to work?

Facing the same issue.

**Comment by mxschmitt** [comment]
@satyak-trellix I updated my old comment, I think we changed the env while we made this option public: https://github.com/microsoft/playwright/issues/9702#issuecomment-949442700
