### ISSUE TITLE
[BUG] Move Windows Channel installation over to Node.js instead of PowerShell

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#9720]
PowerShell requires execution policy to be configured.

> Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass

is not
digitally signed. You cannot run this script on the current system. For more information about running scripts and
setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnauthorizedAccess
Failed to install browsers

**Comment by kokushkin** [comment]
Facing the same issue. It seems I can't override group polices to run the script. But what's the reason of not signing the scripts?
