### ISSUE TITLE
[BUG] Trace Viewer - error printed to the console after the PWA closed

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#9738]
**Context:**
- Playwright Version: 1.16.1
- Operating System: Windows
- Node.js version: 14.6.1
- Browser: Chrome
- Extra: WebStorm IDE

**Describe the bug**
Sometimes, after closing the PWA trace viewer - the errors are printed to the console.

Example of the error:
`ERROR: The process with PID 18076 (child process of PID 26008) could not be terminated.`

![image](https://user-images.githubusercontent.com/52656401/138584518-63331f7e-2fc1-4099-b78d-21937deb3eb0.png)

**Comment by pavelfeldman** [comment]
It does not repro for me, let's collect feedback
