### ISSUE TITLE
[BUG] wrong datetime in pdf

### ISSUE THREAD

**Issue by 28development** [microsoft/playwright#9739]
I have a NextJs application in which I calculate dates depending on inputs in my frontend. That calculation works fine so far, the calculations work. Further I have an api route (serverless function) which runs puppeteer to generate a pdf from an existing url inside my application.

This is how I create my pdf:
```

import chromium from "chrome-aws-lambda"
import playwright from "playwright-core"
import { serialize } from '../../lib/utils'

export default async function generatePdf(req, res) {
    try {
        const browser = await playwright.chromium.launch({
            timezoneId: 'Europe/London',
            args: [...chromium.args, '--font-render-hinting=none'],
            // this is the path on a mac, chromium is installed via command line using brew install --cask chromium
            executablePath: process.env.NODE_ENV !== "development" ? await chromium.executablePath : '/usr/local/bin/chromium',
            headless: process.env.NODE_ENV !== "development" ? chromium.headless : true,
            locale: `de-DE`
        });
        const page = await browser.newPage();
        const pdfUrl = process.env.NODE_ENV !== "development"
            ? "https://myapp.vercel.app/pdf"
            : "http://localhost:3000/pdf";

        console.log("Goto url to generate pdf: " + pdfUrl + '?' + serialize(req.body))
        console.log("The timezone: " + Intl.DateTimeFormat().resolvedOptions().timeZone)

        await page.goto(pdfUrl + '?' + serialize(req.body), {
            waitUntil: "load",
        })
        const pdf = await page.pdf({
            path: "/tmp/mypdf.pdf",
            printBackground: true,
            format: "a4",
        });
        await browser.close();

        return res.status(200).json({ pdf })
    } catch (error) {
        return res.status(error.statusCode || 500).json({ error: error.message });
    }
}
```

The pdf which I create is always one day off, the calculation functions are the same.

For instance this date:

```
const start = '2022-02-05T23:00:00.000Z'

const a = new Date(start).toLocaleDateString("de-DE", {
  year: "numeric",
  month: "2-digit",
  day: "2-digit",
})
```
returns this in my frontend correctly:
`'06.02.2022'`

But inside the pdf creation it returns
`'05.02.2022'`

Is there any way to fix this, I am currently really struggling hard to manage this issue.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
