### ISSUE TITLE
[Feature] Allow "safari" channel

### ISSUE THREAD

**Issue by A-ZC-Lau** [microsoft/playwright#9740]
So, I'm having a situation with a media player (or codec, not sure how to check what is the issue), which doesn't work with chromium nor webkit. 

It does however, work with Google Chrome (`channel: "chrome"`), but there doesn't seem to be a similar option to choose for webkit e.g. (`channel: "safari"`).

It would be great if we could have this option as well, even if it's only for MacOS (which I use).

**Comment by mxschmitt** [comment]
It's not possible to use Safari since Playwright is based on a slightly modified version of WebKit to allow the automation of it.

Do you have a repro for you website / codec which is not working with our WebKit? We can maybe enable it!

**Comment by A-ZC-Lau** [comment]
@mxschmitt Unfortunately not, since this is an internal tool used by the company.

The thing is that it also fails on chromium, but not chrome (with the `channel` property) nor firefox.

What's happening is that, there is a video player (using a m3u8 file) that, when clicked on, doesn't seems to initiate the api request to get the actual video files (.ts files). 

There's are no errors in the console either.

**Comment by mxschmitt** [comment]
Without a repro or more information about the codec / video format its hard to figure out which codec is missing.

**Comment by namwebdev** [comment]
Hi @mxschmitt , I'm also facing an issue where Playwright cannot load the player using an m3u8 file. You can check the player at this link: http://webtm.jv-it.com.vn/j-stream/eq_player/4.4.1/demo_eqplayer/normal_player.html. 

I have observed that Playwright does not support it, and we need you to confirm this issue.

Hope to receive a prompt response from you.
