### ISSUE TITLE
[Feature] Maximize the trace-viewer window by default

### ISSUE THREAD

**Issue by ryanrosello-og** [microsoft/playwright#9743]
Minor quibble, but would it be possible to always open the trace-viewer maximize (full window) when results are opened?

#trace-viewer
Playwright v1.15

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
