### ISSUE TITLE
[Question] Error: Protocol error (Target.getBrowserContexts): Target closed

### ISSUE THREAD

**Issue by xgirma** [microsoft/playwright#975]
**Context:**
- Playwright Version: [0.10.0]
- Operating System: [Linux ]
- Extra: [CI GitHub Action]

```text
     Error: Protocol error (Target.getBrowserContexts): Target closed.
18
      at /home/runner/work/playwright-commonjs-mocha-chai/playwright-commonjs-mocha-chai/node_modules/playwright-core/lib/chromium/crConnection.js:121:63
19
      at new Promise (<anonymous>)
20
      at CRSession.send (node_modules/playwright-core/lib/chromium/crConnection.js:120:16)
21
      at Function.connect (node_modules/playwright-core/lib/chromium/crBrowser.js:48:68)
22
      at async Chromium.launch (node_modules/playwright-core/lib/server/chromium.js:45:25)
23
      at async Context.fn (spec/sandbox.spec.js:11:9)
```

**Describe the bug**

Running playwrights test in GitHub Action CI throwing the `Error: Protocol error (Target.getBrowserContexts): Target closed`. error.

In locally both headless and headed works. I only get the error when I run these tests in GitHub Action CI.

TEST: 

Example 1: https://github.com/e2e-boilerplates/playwright-commonjs-cucumber-chai/blob/master/features/support/steps.js

Example 2: https://github.com/e2e-boilerplates/playwright-commonjs-mocha-chai/blob/master/spec/sandbox.spec.js

ERROR:

Example 1: https://github.com/e2e-boilerplates/playwright-commonjs-cucumber-chai/runs/442648685?check_suite_focus=true

Example 2: https://github.com/e2e-boilerplates/playwright-commonjs-mocha-chai/runs/442700778?check_suite_focus=true

**Comment by arjun27** [comment]
Thanks for sharing this @xgirma. It looks like the browser is having trouble getting launched in the GH Actions environment. To debug this, you can use `dumpio: true` in the `launch({ dumpio: true })` method as args.

This typically happens when the environment does not have the system dependencies. You can also refer to [this working example for GH Actions](https://github.com/arjun27/playwright-github-actions).

**Comment by xgirma** [comment]
Thanks, adding missing packages makes it work. 

https://github.com/e2e-boilerplates/playwright-commonjs-mocha-chai/blob/master/.github/workflows/nodejs.yml

https://github.com/e2e-boilerplates/playwright-commonjs-cucumber-chai/runs/444881868?check_suite_focus=true
