### ISSUE TITLE
[Bug]: Page.screenshot hangs when main resource does not finish

### ISSUE THREAD

**Issue by nexcode** [microsoft/playwright#9757]
**Context:**
- Playwright Version: > 1.14.1
- Operating System: Linux
- Node.js version: 16.12.0
- Browser: Chromium

```
page.screenshot: Timeout 60000ms exceeded.
    at async (webpack://botagent/src/commands/screen.ts:11:52)
    at run (webpack://botagent/src/worker/pool.ts:24:28)
    at handler (webpack://botagent/src/worker/executor.ts:33:21)
    at async (webpack://botagent/src/router/router.ts:26:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
})();
```
All releases after 1.14.1 have this bug. I don't change anything in the software, but when updating to new release, the number of these errors becomes about 50%

**Comment by sohaib17** [comment]
In my case screenshot API is timing out most of the time on pages where request is aborted because of timeout.

For cases like these I tried with CDP `Page.captureScreenshot` as well but CDP call never returns.

Seems to be because of https://bugs.chromium.org/p/chromium/issues/detail?id=1121612

**Comment by nexcode** [comment]
Yes, it can explain this behavior. But in theory, if goto is interrupted by timeout or throws an error, my code will not reach the screenshot, but will return an error or timeout from goto.

**Comment by nexcode** [comment]
Does this bug occur precisely if there was an error loading the main document (html) or also when loading any resource by the browser?

**Comment by sohaib17** [comment]
Might be that `goto` completes fine and then JS in page redirects and starts a new connection.

This snippet reproduces the issue at my end (Python 3.8, CentOS 8):
```
import asyncio
from playwright.async_api import async_playwright, Error


async def coroutine():
    async with async_playwright() as playwright:
        binary = playwright.chromium
        browser = await binary.launch(headless=True)
        page = await browser.new_page()
        try:
            await page.goto("https://blockchain.tinithral.com/LUNO-verify/")
        except Error:
            await page.evaluate('() => window.stop()')
        await page.screenshot(path='/tmp/test_shot.png', full_page=False)
        await browser.close()


asyncio.run(coroutine())
```
