### ISSUE TITLE
Memory and performance tests for our browsers

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright#977]
We should create standard benchmark to test memory usage, startup time, and cpu usage among all of our browsers and platforms. This will help us catch memory leaks, upstream performance regressions, and just in general have a better sense of how the browsers are doing.

As of right now I know our WebKit for Windows leaks memory. I'll continue to update this issue with more findings.

**Comment by aslushnikov** [comment]
> As of right now I know our WebKit for Windows leaks memory.

As of v1.0.0, I believe this is fixed. I know there are no plans as of today to pursue this goal, so I'd close this for now.

**Comment by VikramTiwari** [comment]
Just piggybacking on this idea. I think this would be really helpful when folks are planning to provision VM instances for tests. If there are benchmarks, it helps understand how much time will be spent in the setup and thus can be the deciding factor between running tests in serial vs creating a new container for each test suite.

**Comment by barakplasma** [comment]
for what it's worth, when I run chromium via playwright in a 512mb limited docker container, it can't make a screenshot within 30 seconds. So I added a linux swap file of 4GB to the docker host, and that solved the issue for me (makes screenshots with no issue.)
