### ISSUE TITLE
[BUG] WebKit does not always crash gracefully

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright#978]
Sometimes when WebKit crashes, it emits a nice 'error' event on the page saying that it crashed. But if the crash happens as the page is being constructed, it can go down a bad path.

This will dispose of the session when the `Target.targetDestroyed` event comes in. If `_wkPage` has not been constructed yet, nobody will read the `crashed` boolean to check if the page has crashed.
https://github.com/microsoft/playwright/blob/251ad38824070ca9328af18d951a19e21f6e1510/src/webkit/wkPageProxy.ts#L172

Then later, in `_initalizeSession` we catch the errors that come with trying to initialize on a blank page:
https://github.com/microsoft/playwright/blob/251ad38824070ca9328af18d951a19e21f6e1510/src/webkit/wkPage.ts#L100

On the next line, we see that the session is disposed, and swallow the error.

This means we return a seemingly working page, but without a main frame! The page will fail with the first call that touches the main frame, with an error like `cannot read .goto of undefined`, or whatever method was called first on the main frame.

**Comment by dgozman** [comment]
I think this has been fixed a while ago.
