### ISSUE TITLE
[BUG] Missing blur and focus events

### ISSUE THREAD

**Issue by alexdima** [microsoft/playwright#979]
**Context:**
- Playwright Version: 0.10.0
- Operating System: macOS 10.15.3

I'm investigating a flaky test for VS Code (https://github.com/microsoft/vscode/issues/90470). Through logging, I have noticed that the root cause of the flaky test is that `blur` and `focus` events are not delivered to DOM nodes in Chromium.

Basically, in that test something like the following happens:
* `textArea1.focus()`
* `document.activeElement === textArea1` (`true`)
* `textArea2.focus()`
* `document.activeElement === textArea2` (`true`)

But no `blur` event is delivered to `textArea1`, `document.activeElement` changes without notifying the old focused element that it got blurred. I can try creating a simple repro if you want, just let me know.

What is interesting is that if I click in the page and interact with it, it's like all those events were queued up and then they all fire.

**Comment by pavelfeldman** [comment]
:wave: Alex

I could only repro this in the headful mode and sent out a fix.

**Comment by alexdima** [comment]
Thank you for the very quick turnaround! :heart:
