### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection. ReferenceError: URL is not defined

### ISSUE THREAD

**Issue by samiujan** [microsoft/playwright#980]
**Context:**
- Playwright Version: "playwright": "0.10.0",
- Operating System: Windows 10
- Extra: Running from commandline (cmd) and not WSL

**Code Snippet**

**Summary: Even though all 3 screenshots are created successfully from the demo, there is a large block of errors in the commandline output**

I am using the basic example:

```const playwright = require('playwright');

(async () => {
  for (const browserType of ['chromium', 'firefox', 'webkit']) {
    const browser = await playwright[browserType].launch();
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto('http://whatsmyuseragent.org/');
    await page.screenshot({ path: `example-${browserType}.png` });
    await browser.close();
  }
})();
```
Steps: 
1. I put the code above in a file "run.js"
2. Ran "npm init" to create a package .json
3. Ran "npm i playwright --save"
4. Ran "node run.js"

All 3 screenshots are created successfully but the commandline output a lot of errors

**Describe the bug**

The following error message is replicated dozens of times
```
(node:5608) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 25)
(node:5608) UnhandledPromiseRejectionWarning: ReferenceError: URL is not defined
    at stripFragmentFromUrl (C:\playwrite\node_modules\playwright-core\lib\network.js:63:20)
    at new Request (C:\playwrite\node_modules\playwright-core\lib\network.js:82:21)
    at new InterceptableRequest (C:\playwrite\node_modules\playwright-core\lib\firefox\ffNetworkManager.js:134:24)
    at FFNetworkManager._onRequestWillBeSent (C:\playwrite\node_modules\playwright-core\lib\firefox\ffNetworkManager.js:51:25)
    at emitOne (events.js:116:13)
    at FFSession.emit (events.js:211:7)
    at Promise.resolve.then (C:\playwrite\node_modules\playwright-core\lib\firefox\ffConnection.js:162:47)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by pavelfeldman** [comment]
What is your Node version?

**Comment by samiujan** [comment]
Sorry for not pointing it out - Node version is **v8.11.1**

I also tried it out on the latest node (12.16) and it's not throwing any errors so I think this issue can be closed

**Comment by chris-fran** [comment]
Does this mean Node 8 is not supported?

**Comment by mxschmitt** [comment]
> Does this mean Node 8 is not supported?

The minimum Node.js version is 10.15.0.

https://github.com/microsoft/playwright/blob/c43de22193680b79fe38966c7c9efced3a06aa39/package.json#L6-L8
