### ISSUE TITLE
[BUG] Enable tracing in Firefox make the browser suddenly close when minimized

### ISSUE THREAD

**Issue by henrydzung** [microsoft/playwright#9808]
**Context:**
- Playwright Version: 1.16.1
- Operating System: Windows
- Node.js version: 14.17.2
- Browser: Firefox

**Describe the bug**

```shell
npx playwright ff --save-trace trace.zip
```

If I enable tracing in Firefox, when I minimize the browser, the browser will suddenly be closed . 

(I also experienced Firefox sometimes suddenly closed when testing with error messages like in #8934, #8655, #8536. If I disable tracing, Firefox won't intermittently crashes anymore. Don't know if that is the cause or not.)

**Comment by yury-s** [comment]
Should be fixed with the recent roll.
