### ISSUE TITLE
[Feature] Ability to skip/or close the page opened by `browser.launch`

### ISSUE THREAD

**Issue by jperl** [microsoft/playwright#981]
Version: https://github.com/microsoft/playwright/commit/d367a2ed3a2d583e5e82d27ac1f53caddd8aa943  (current master)

When running this script it opens two pages (and I think two contexts)

- one after `chromium.launch`
- the other after `context.newPage`

```
const { chromium, devices } = require("playwright");
const iPhone = devices["iPhone 6"];

(async () => {
  const browser = await chromium.launch({ headless: false });
  const context = await browser.newContext({
    viewport: iPhone.viewport,
    userAgent: iPhone.userAgent
  });
  const page = await context.newPage();
})();
```

I would like to close the page opened by `chromium.launch`, or skip opening it in the first place. Since it is confusing to have a blank page that is not in use (https://github.com/qawolf/qawolf/issues/395).

![example-small](https://user-images.githubusercontent.com/1136652/74447218-06af0780-4e47-11ea-91d2-2523c29c52e5.gif)

**Comment by pavelfeldman** [comment]
Thanks for the report. We are going to get there, but it'll take some time. In order to implement it we need to introduce a new mode in all the browsers that does not open the default profile on browser startup.

**Comment by pavelfeldman** [comment]
Should be fixed by now in Chromium and WebKit. Still has an extra tab in FF, but that is probably Ok for now.

**Comment by DavertMik** [comment]
Yeah, extra tab is less annoying than extra window.
Anyway, when this fixes will be available, in 0.12?

**Comment by jperl** [comment]
@DavertMik It's merged, so you can get it now by installing playwright@next

**Comment by FrankLaterza** [comment]
Will this ever be implemented in FF?

**Comment by suchcodemuchwow** [comment]
This issue still exist in 1.17.1 @pavelfeldman

**Comment by honzajde** [comment]
Still exists - two windows with Firefox.

**Comment by jiahaoyu6666** [comment]
If you don't add the configs in `jest-playwright-config.js` with this:
```
module.exports = {
    browsers: [ 'chromium', 'firefox' ],
    launchOptions: {
        headless: false,
    },
    contextOptions: {
        acceptDownloads: true,
    },
};
```
and only open the browser with `chromium.launch` or `firefox.launch`, then you won't have the extra browser window issue.
Other wise I still have that issue for both browser: chromium and firefox.

**Comment by zhaojc** [comment]
Still exists - two windows with Chrome. 1.28.1

**Comment by opr** [comment]
I'm still seeing this with Chromium Version 112.0.5615.29 (Developer Build) (arm64) one window opens and stays blank, the other is behind it and runs my tests.

**Comment by Segvr** [comment]
> I'm still seeing this with Chromium Version 112.0.5615.29 (Developer Build) (arm64) one window opens and stays blank, the other is behind it and runs my tests.

same problem with firefox, chromium

**Comment by aminaodzak** [comment]
It's weird this got closed, even issues still persists. Any thoughts? @pavelfeldman

**Comment by LazzyBird** [comment]
The issue still persists for all built-in browsers, one browser window is opened with the expected URL, and immediately the new blank one so thus all tests are false-failed.

**Comment by poojakatte** [comment]
yes this issue still exists, m new to playwright, any solution?

**Comment by jasonribble** [comment]
I believe this issue is still around.

**Comment by roman-smolnyk** [comment]
In python I fix it like this:
```python
browser = playwright.firefox.launch()
page = browser.new_page()
browser.pages[0].close()
````

**Comment by erayyagiz** [comment]
I'm also facing this issue, additionally, when one suite execution is completed, another suite cannot go to the URL even though they can be running as a single properly.

**Comment by AzamanRPM** [comment]
not sure why pavelfeldman is not responding to peoples comment!! lol

**Comment by dagodoglito** [comment]
Hello all, Any update on the fix for this issue?thanks

**Comment by derolk** [comment]
This is still an issue on Java Playwright version:
``
        <dependency>
            <groupId>com.microsoft.playwright</groupId>
            <artifactId>playwright</artifactId>
            <version>1.47.0</version>
        </dependency>
``

**Comment by vBuravlev** [comment]
Hello! 
If you try to use the browser to create a new context, an empty window will appear. This is quite annoying. I haven't found a better solution than closing all the contexts when receiving a browser, and then passing it on to fixtures and tests. Here's an example of how it works:

```
export const test = baseTest.extend<BaseFixtures>({
  customBrowser: async ({ browser }, use) => {
    await Promise.all(browser.contexts().map(context => context.close()));
    await use(browser);
    await browser.close();
  }
});
```

At least the empty window doesn't bother me anymore in tests and reports.

**Comment by AzamanRPM** [comment]
`export async function initializePage(browser: Browser, storageStatePath: string) {
  const context = await createBrowserContext(browser, storageStatePath);
  const page = await context.newPage();
  await page.goto('/',{ waitUntil: 'domcontentloaded', timeout: 5000 })"`

"initializePage" Function fixed my issue
