### ISSUE TITLE
[BUG][Webkit] WebKit does not work with macOS Monterey

### ISSUE THREAD

**Issue by StephaneColson** [microsoft/playwright#9811]
**Context:**
- Playwright Version: 1.16.1
- Operating System: MacOS Monterey 12.0.1
- Node.js: 14.18.0
- Browser: Webkit

**Code Snippet**

```javascript
const myContext = await browser.newContext();
```

**Describe the bug**

Since latest upgrade of MacOS (Monterey 12.0.1) all my tests fail with webkit browser (headless or not).
The fail is detected when instantiating `browser.newContext()` with the following error: `browser.newContext: Target closed`

![CleanShot 2021-10-27 at 09 37 53@2x](https://user-images.githubusercontent.com/1481595/139021226-e02f76bb-63d7-47af-b564-24e5b1803b2a.jpg)

This is only with webkit, everything was ok before the MacOS upgrade, and everything is ok with Firefox and Chromium.

**Comment by KnightJW1913** [comment]
> This is fixed on tip-of-tree Playwright with webkit build 1566; we might cherry pick this to 1.16.3 so keeping this open

Will this be cherry picked to 1.16.3 after all?

**Comment by aslushnikov** [comment]
> Will this be cherry picked to 1.16.3 after all?

@KnightJW1913 We do not cherry pick new browsers to patch releases unless that's an emergency that affects a significant amount of users.

1.17 is scheduled in a few weeks; would using @next version work for you meanwhile?

**Comment by KnightJW1913** [comment]
> > Will this be cherry picked to 1.16.3 after all?
> 
> @KnightJW1913 We do not cherry pick new browsers to patch releases unless that's an emergency that affects a significant amount of users.
> 
> 1.17 is scheduled in a few weeks; would using @next version work for you meanwhile?

I installed 1.17.0-next-1635521587000 but it's a no go for me due to the webkit version it uses. :(

**Comment by aslushnikov** [comment]
> I installed 1.17.0-next-1635521587000 but it's a no go for me due to the webkit version it uses. :(

@KnightJW1913 what's the issue with the version?

**Comment by mxschmitt** [comment]
Closing since its fixed on our master branch. We'll release it with 1.17 or you can try it today via `npm i @playwright/test@next`.

**Comment by alexeyraspopov** [comment]
@mxschmitt, using `v1.16.3-1636114012000` which is now tagged as `next` doesn't resolve the issue: I'm still seeing the same failure. Node.js v16.13, Monterey 12.0.

**Comment by alexeyraspopov** [comment]
To clarify: I also installed `playwright-webkit@1.16.3-1636114012000`.

**Comment by mxschmitt** [comment]
Please install `npm i @playwright/test@1.17.0-next-alpha-nov-5-2021.`

(Background: with our current release changes which we cherry-pick to the previous release gets released and tagged under @next tag. This gets fixed with the next release and thats the reason why you are getting a 1.16.3-* version and not a 1.17.0* version)

**Comment by alexeyraspopov** [comment]
@mxschmitt thanks, it works now! 🎉
