### ISSUE TITLE
[Feature] Add optional "message" param for waitForTimeout method

### ISSUE THREAD

**Issue by KramskoiSergei** [microsoft/playwright#9813]
Of course i understand that constant delays are an absolute evil, but some times we are using waitForTimeout() method. And also, when u use this method, you want to let another persons to understand why are you do this. So u do something like that:

```
// we should explicit wait because of that or that
await page.waitForTimeout(2* 1000);
```

or
```
const REASEON_OF_WAIT = 2 * 1000;
await page.waitForTimeout(REASEON_OF_WAIT);
```

Right now it has such signature:
`  waitForTimeout(timeout: number): Promise<void>;`

We can add optional "message" param fir waitForTimeout signature:
`  waitForTimeout(timeout: number, message?: string): Promise<void>;`

And we will be able to do something like:
```
await page.waitForTimeout(2* 1000, 'we should explicit wait because of that or that');
```

P.S. Also perhaps should rename "timeout" in signature to "millis", it will help for persons who forget in which units timeout set and go to js doc to understand it.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
