### ISSUE TITLE
[Feature] Enhancements to HTML reporter

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#9825]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

- Currently, in HTML report to navigate between different tests, I have to use browser back button to go back to the list of tests every time. Instead is there a possibility to add a left panel navigation which contains the list of tests and on the right panel you see the test details?
- Sort the test under a test file by project name by default. For example - All Chrome tests are listed first followed by Webkit, etc. Something along these lines
- Filter option to filter tests by project name, test status, etc.
- UI enhancements to distinguish whether I am on first run or retry run in the test detail page. See the screenshot below
![Screen Shot 2021-10-27 at 9 46 31 AM](https://user-images.githubusercontent.com/22205721/139111351-6115961e-4490-4165-9efd-0fad11f50843.png)

**Update:**
One more enhancement: Open Trace file from HTML report in a new tab. Currently, if I open the trace file and click through different steps in the trace file, I have to press browser back multiple times to go back to the test list again.

**Comment by pavelfeldman** [comment]
> Currently, in HTML report to navigate between different tests, I have to use browser back button to go back to the list of tests every time. Instead is there a possibility to add a left panel navigation which contains the list of tests and on the right panel you see the test details?

I enabled `Ctrl+Click` so that you could open test results in new tabs, let's see how helpful that is.

> Sort the test under a test file by project name by default. For example - All Chrome tests are listed first followed by Webkit, etc. Something along these lines

You can now click on project label to filter by project, click All and you are back to all results.

> Filter option to filter tests by project name, test status, etc.

Done

> UI enhancements to distinguish whether I am on first run or retry run in the test detail page. See the screenshot below

Done
