### ISSUE TITLE
[BUG] EACCESS errors in Docker.focal with latest tag when installing npm dependencies

### ISSUE THREAD

**Issue by GeorgDangl** [microsoft/playwright#9830]
**Context:**
- Playwright Version: 1.16.0 (likely, might be with other versions, too)
- Operating System: Ubuntu in official Playwright Docker image
- Node.js version: The one in the Docker image
- Browser: Electron (but the issue happens before any Browser is launched)
- Extra: **This is an issue with the official Playwright Docker Image**

**Code Snippet**

I'm using Playwright to run E2E tests for an Electron app. It's basically the script below, which does just an `npm ci` and then runs a custom npm script to run the tests.

```bash
docker run -v LocalDevDir:/app/src --rm `
                        --privileged `
                        mcr.microsoft.com/playwright:focal `
                        sh -c "cd /app/src/ && `        										
                        npm ci --no-progress && `
                        xvfb-run --auto-servernum npm run e2e:docker"
```

**Describe the bug**

There seems to be a permissions issue when restoring npm scripts in the latest Dockerfile.focal. Essentially, during npm package installation for an Electron app, I get the following output (shortened to the relevant parts):

```
> electron-builder install-app-deps && npm run copyTinyMceSkins

  • electron-builder  version=22.13.1
  • loaded configuration  file=/app/src/electron-builder.json
┌───────────────────────────────────────────────────┐
│       electron-builder update check failed        │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘
glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}
```

as well as:

```
> npm run electron:serve-tsc && ng build --base-href ./ "-c" "dockere2e"

glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}
```

The `EACCES` error seems to happen for every invocation of either an npm postinstall script or any other `npm run` command.

There seems to be a problem where anything below `/root/` inside the Docker container can not be accessed, even though I run with the default _root_ user. Additionally, setting the permissions like `chown -R $USER:$(id -gn $USER) /root/.config` seems to work inside the container, but does not have any effect.

It's hard for me to pinpoint the problem to a specific version, since I unfortunately just have two data points:
* It worked with the version available at October 20th, 2021, 7:12 AM UTC
* It did not work with the version available at October 26th, 21:42 UTC

I've resolved it, for now, by fixing the Dockerfile to `mcr.microsoft.com/playwright:v1.13.1-focal`, but I would suspect it's something that was introduced with `v1.16.0`.

However, there's one more curious part to this: The problem seems to only appear when the Docker host is running on Ubuntu (tested with 18.04), on my local Windows development machine it runs just fine.

The script itself uses a `tmpfs` folder for `node_modules`, but the error happens both with and without using `tmpfs` (and the error message indicates a permissions issue in a non-tmpfs folder).

**Comment by mxschmitt** [comment]
Closing since this is not an error coming from Playwright, more a warning coming from the NPM CLI.

**Comment by GeorgDangl** [comment]
> Closing since this is not an error coming from Playwright, more a warning coming from the NPM CLI.

I think that's fine, but I wanted to add that it's not just a warning, this actually caused my build to fail. More precisely, Angular applications failed during compilation.

Will wait for new versions then😀

**Comment by tjoskar** [comment]
For anyone else facing this: my issue was that we were running docker on Linux and mounted our test files. The owner of the mounted folder is `noneuser` if starting the container on Linux and `root` if started on Mac. And since npm run [change the user](https://docs.npmjs.com/cli/v8/using-npm/scripts#user) to the folder owner if running as root, the npm script has no longer access to `/root` and the error above are emitted.

My (ugly) solution is to give all users read/write access to `/root` in the container (`chmod --recursive 777 /root`).
