### ISSUE TITLE
[Question] Why in CI there is no line with summary info about tests and workers?

### ISSUE THREAD

**Issue by krutoo** [microsoft/playwright#9847]
Hi, first of all thanks for great testing framework

In my project i use Playwright in GitLab CI with recommender Docker image mcr.microsoft.com/playwright:focal

I ran my tests by npm-script:
```json
{
  "scripts": {
    "test:e2e": "playwright test" 
  }
}
```

Locally after run my tests i have summary info line in terminal like:
```bash
# ...
Running 105 tests using 2 workers
# ...
```

But i don't have this line in CI job log

What i am doing wrong or how can i turn it info on in CI jobs?

**Comment by krutoo** [comment]
> I guess you'd like to see this line on CI?

@dgozman Yes, would be very helpful

**Comment by mhatvan** [comment]
I will +1 this one, right now I am unsure if my tests got stuck or they just take a while ;)
