### ISSUE TITLE
[BUG] Massive traces (700MB+)

### ISSUE THREAD

**Issue by dorian-marchal** [microsoft/playwright#9851]
**Context:**
- Playwright Version: 1.16.2
- Operating System: Ubuntu 20.04
- Node.js version: 14.18.1
- Browser: Chromium
- Extra: for a ~3min test run that timeout.

**Describe the bug**

When end to end testing an internal app, Playwright (with Chromium) seems to screenshot every frame (i.e. 60/sec), producing very large traces with more than 10k 80kB screenshots for a ~3min test run (i.e. >700MB).

With webkit, traces are still very big (>350MB) but it only seems to capture ~30 screenshots/sec.

Unfortunately, I could not reproduce this issue on other websites that I could share with you. Could you please give me some pointers so I can help you resolve this issue?

Here is my `playwright.config.js`:
```js
{
  globalSetup: require.resolve("./global-setup"),
  timeout: 3 * 60 * 1000,
  use: {
    headless: true,
    viewport: { width: 1280, height: 720 },
    baseURL: process.env.E2E_BASE_URL,
    ignoreHTTPSErrors: true,
    screenshot: "only-on-failure",
    trace: "retain-on-failure",
    browserName: "chromium",
  },
}
```

**Comment by dgozman** [comment]
Fixed by #9893.
