### ISSUE TITLE
[BUG] `npx playwright install chrome` command fails in installing

### ISSUE THREAD

**Issue by archlichking** [microsoft/playwright#9858]
**Context:**
- Playwright Version: [1.16.2]
- Operating System: [mcr.microsoft.com/playwright:v1.16.2-focal]
- Node.js version: [14]
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [we use @playwright/test@1.16.2]

Our docker image is based on `mcr.microsoft.com/playwright:v1.16.2-focal`. Our test suite runs in chrome, we'll need to install chrome browser in the container via

```bash
RUN npx playwright install chrome
```

This command stops working since 1.16, it throws out following error in building image

```bash
#23 10.62 
#23 10.62 2021-10-28 18:13:51 (9.65 MB/s) - 'google-chrome-stable_current_amd64.deb' saved [89046612/89046612]
#23 10.62 
#23 10.62 + sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
#23 10.63 sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
#23 10.63 Failed to install browsers
#23 10.63 Error: Failed to install chrome
```

**Comment by aslushnikov** [comment]
@archlichking some of [the mitigations](https://github.com/microsoft/playwright/issues/9858#issuecomment-954311179) might be implemented in future, but no ETA.

For this particular issue, the suggested workaround should work, and there's nothing nice we can do on our side – so closing this bug.

If something's still broken, please reach out (via a new issue) - we'll be happy to take a look!
