### ISSUE TITLE
[Feature] docker: make `pwuser` sudo password-less

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#9869]
### Proposal

Make `pwuser` user in docker container to have passwordless sudo

### Context 

As of v1.16, our docker containers have both `root` and `pwuser` users.

`pwuser` requires password for `sudo`, so it can't install packages. This might deal issues wrt to the recent NPM v7+ permission changes - see https://github.com/microsoft/playwright/issues/9858#issuecomment-954311179

### PRO's

- `root` user gets custom treatment in Linux, e.g. NPM v7+ resets permissions to the `CWD`-owner.
Running as user with passwordless sudo makes for a smooth automation experience.

### CON's

- passwordless sudo is considered to be insecure practice, though I wonder how much this applies to actual throw-away docker containers

---

Please chime in with your opinions. Upvote if you like the change, downvote + voice concerns if you don't like it.

**Comment by dwt** [comment]
Considering that the pwuser is explicitly added to secure usage of the docker image when crawling the web via playwright, it seems rather counter intuitive to allow escape to root user without a password.

See: https://playwright.dev/docs/docker#crawling-and-scraping

**Comment by aslushnikov** [comment]
We decided against it

**Comment by oytunerdd** [comment]
So can it be the reason why I can't copy the report files to another destination. I get seamlessly EACCES error
