### ISSUE TITLE
[BUG] tracing.stopChunk: Must start tracing before stopping

### ISSUE THREAD

**Issue by rombat** [microsoft/playwright#9879]
**Context:**
- Playwright Version: "@playwright/test": "^1.16.2"
- Operating System: Windows 10
- Node.js version: v14.17.4
- Browser: all

**Code Snippet**

```shell
  2) [chromium] › payment-flow.spec.js:152:1 › delete project ======================================

    tracing.stopChunk: Must start tracing before stopping
```

```shell
 4) [firefox] › payment-flow.spec.js:152:1 › delete project =======================================

    tracing.stopChunk: Must start tracing before stopping
```

```shell
  6) [webkit] › payment-flow.spec.js:152:1 › delete project ========================================

    tracing.stopChunk: Target page, context or browser has been closed
```

**Describe the bug**
Tracing does not work. I'm not doing anything special, it just fails after running some failed tests before.
It does not even start to actually run the test on which the error is thrown, except for the beforeEach part (this test is supposed to be skipped). The error message is different on webkit.
=> I don't have any trace available after running the tests

**Comment by AM1988** [comment]
@dgozman 

I see the same issue with the below code snippet

````
import { test, expect } from '@playwright/test';
test.beforeEach(async ({page}) => {
  await page.goto('https://playwright.dev/');
  await page.waitForTimeout(20000);

})
test('landing visual testing', async ({ page }) => {
  expect(await page.screenshot()).toMatchSnapshot('landing.png');
})
````

in console

```
tracing.stopChunk: Tracing is already stopping

    repo\playwright_demo\node_modules\@playwright\test\lib\index.js:433:48
```

in HTML report

![image](https://user-images.githubusercontent.com/19313323/140300175-592ab359-0a95-4cb3-a784-e4c43c3c40b4.png)

**Comment by mxschmitt** [comment]
I tried to reproduce, but was unfortunately not able to. How do you invoke Playwright Test? Can you reproduce it all the times?

**Comment by AM1988** [comment]
Yes, I can reproduce this all the time.

```
 "scripts": {
    "test:e2e": "playwright test --reporter=html --update-snapshots"
  }
```

and just run
`npm run test:e2e`

Seems it is somehow related to PW setting timeout: 30 * 1000 == 30 sec, and in test, I set wait to 20 sec + page loading.
Maybe try to play with timeout here

`await page.waitForTimeout(20000);`

**Comment by mxschmitt** [comment]
Thanks! I was able to repro it, maybe 1/10 times. (waitForTimeout(2500), pw-config-timeout: 5000, trace: 'on')
