### ISSUE TITLE
[Feature] Automagically Run xvfb-run if no DISPLAY set and head full

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#9888]
In slack, it's fairly common to see folks get the DISPLAY error in CI/CD, so it might be friendlier to auto detect this and automatically wrap the browser launch in xvfb-run internally in Playwright so it's transparent for the user.

Since our setup has a mix of headful and headless projects, we just always wrap our test launches with xvfb-run so we don't have to have conditional logic dealing with each of the different projects. If playwright auto detected the need for xvfb-run wrap, we wouldn't need waste calling it AND we wouldn't have to remember to add xvfb-run wrap when we add new CI/CD workflows.

**Comment by mxschmitt** [comment]
Relates https://github.com/microsoft/playwright/issues/6037
