### ISSUE TITLE
[Feature] Support iframe selection by id attribute

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#9891]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

Currently, `page.frame` can only be selected by `name` attribute. Could it be extended to select using `id` as well?
Ref: https://playwright.dev/docs/api/class-page#page-frame

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/7982
