### ISSUE TITLE
[Question] page.type Can the speed of typing be reduced?

### ISSUE THREAD

**Issue by fasatrix** [microsoft/playwright#9894]
Hi,
I have an input box tthat accepts credit cards number. The input box seems to not catch up well with page.type ifact not all digits are correctly inputted and I endup with an incomplete/wrong sequence which will invalidate the credit card number. If I type every single digit individually or it works well however it is not ideal. I am wondering is there a way to reduce the speed of typing the sequence? Thanks

**Comment by vsravuri** [comment]
https://playwright.dev/docs/api/class-page#page-type

```javascript
await page.type('#mytextarea', 'Hello'); // Types instantly
await page.type('#mytextarea', 'World', {delay: 100}); // Types slower, like a user
```

**Comment by fasatrix** [comment]
> https://playwright.dev/docs/api/class-page#page-type
> 
> ```js
> await page.type('#mytextarea', 'Hello'); // Types instantly
> await page.type('#mytextarea', 'World', {delay: 100}); // Types slower, like a user
> ```

Wondeful thanks!
