### ISSUE TITLE
[Feature] Ability to add mask when comparing snapshot images

### ISSUE THREAD

**Issue by mwhebert** [microsoft/playwright#9899]
It would be nice to be able to also specify a mask image which could block out certain parts of the screen when doing the compare.  For example let's say my page always displays a date somewhere on the screen.  An image would always see that date as a difference in the image.  If I could also specify a 'mask' (an image that was overlayed on top when doing the compare) then I could block out that part of the image so the compare would match since that area would be the same (or ignored).

We also have tables on our page for example where we 'dynamically' create names of objects during each test run.  Between test runs the names change so we would want to also block out part of a table just to show another example use case.

**Comment by aslushnikov** [comment]
@mwhebert would a set of elements to blackout satisfy your needs?

Something like this:
```js
await page.screenshot({
  blackout: [
    page.locator('.my-date-element'),
  ],
});
```

**Comment by mwhebert** [comment]
@aslushnikov - Yes I think that would work!  May have to add some classes as marked but that would solve the issue.

**Comment by aslushnikov** [comment]
Awesome, merging this in https://github.com/microsoft/playwright/issues/10162 then
