### ISSUE TITLE
[Question] Html-reporter shows path to specs instead title

### ISSUE THREAD

**Issue by AndreyMelnichenko** [microsoft/playwright#9904]
**Description:**
I've expect that html-reporter would display spec description on reporter main page instead path to spec file

![image](https://user-images.githubusercontent.com/30802024/139575781-5abe05d1-c45d-488c-b7ce-0eb1ef0fde8e.png)

but in spec code

![image](https://user-images.githubusercontent.com/30802024/139575829-e111b662-4efa-4b66-a93e-15a40fff587b.png)

**Comment by pavelfeldman** [comment]
There can be several describe blocks in one file, so we can't put first description there. But we can make sure test title starts with the suite description.
