### ISSUE TITLE
how can dynamically change 'testDir' value based on an API response

### ISSUE THREAD

**Issue by playwright2021** [microsoft/playwright#9912]
Hi All,
We want to selectively execute the test group(different directory) per an API response, For example have directories like below:
src>
  a-ui-tests>
  b-ui-tests>
  c-ui-tests>
  If API response return like
  {
  test_a_ui:false,
  test_b_ui:true,
  test_c_ui:,true
  }
  then just selectively run test cases under `b-ui-test` and `c-ui-tests`, how can we achieve this?
  thanks ahead.

**Comment by mxschmitt** [comment]
Where do you plan to or do already the API request in?

Depending on your setup, I'd recommend to call Playwright Test multiple times and leverage the `--project` parameter, where you can specify the project. You then can create multiple projects which select different directories, see here: https://playwright.dev/docs/test-advanced#projects

Also depending on your scale, leveraging GitHub Actions matrix, might make sense.

e.g. 

```ts
import { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  timeout: 20000,
  projects: [
    {
      name: 'foo',
      testDir: './foo'
    },
    {
      name: 'bar',
      testDir: './bar',
    },
  ]
};
export default config;
```

`npx playwright test --project=bar`

**Comment by mxschmitt** [comment]
Closing since it's stale.

**Comment by playwright2021** [comment]
great thank, it works for a single project. How about want to run selectively for multiple projects?
npx playwright test --project=bar, foo?

**Comment by mxschmitt** [comment]
You can select multiple projects by using comma, they will then run in parallel. Is this what you mean with at the same time?

**Comment by playwright2021** [comment]
Is that a way I can dynamically change projects configuration after playwright.config.ts is loaded?
static projects looks like:
projects:[
  {
    name: 'appA',
    testDir: './base-ui/appA'
  },
  {
    name: 'appB',
    testDir: './base-ui/appB'
  },
  {
    name: 'appC',
    testDir: './base-ui/appC'
  }
  ]
  
  In global-setup.ts,  we need to config the projects based on an API response, find which application is installed and available for testing. For example, sometimes appA & appB are installed and testable, sometimes maybe only appC testable.
