### ISSUE TITLE
[Question]: Storing authentication state after first test in Page object model

### ISSUE THREAD

**Issue by jithinjosejacob** [microsoft/playwright#9917]
I am planning to resuse authentication state after my first test in the future tests.

I ma following page object model as suggested by max in below link.

During the test run ,I am unable to access test context to store the authentication state.

Is there any way I can do it in the test.

Note: option available globally to reuse it across all tests won't work, as my cookies have an expiration. So I want to login on test 1, save that authentication state and use it for login for test2, test3 and soon.

Page object model followed

https://github.com/microsoft/playwright/issues/7144#issuecomment-862192977

**Comment by mxschmitt** [comment]
if you want to re-use the authentication across a test file, we recommend this: https://playwright.dev/docs/test-retries#reuse-single-page-between-tests

If this doesn't work for you, then you'd have to go with a more complex setup, usually we recommend not depending on other tests and use a login either by the UI (browser automation via Playwright) or API (login via our request API) instead. This makes them independent from each other.

We also have a detailed page about authentication with different approaches: https://playwright.dev/docs/test-auth

**Comment by mxschmitt** [comment]
Closing since its answered.
