### ISSUE TITLE
Be good to have a HTML report that can be shared

### ISSUE THREAD

**Issue by Phonesis** [microsoft/playwright#9920]
Great with with the new HTML report in 1.16

It currently must get served locally to be viewable in a browser. This is fine but it would be good to also have the ability to save it for offline viewing / sharing with people via an attachment in email etc. 

Perhaps a --publish param or something could be used to achieve this? Particularly useful for CI as artifact to download as test evidence.

**Comment by mxschmitt** [comment]
What kind of publishing do you have in mind? Usually to upload it somewhere e.g. S3/Azure Blob Storage/ftp/sftp you do it directly inside your CI pipeline. For example as a GitHub Action step.

Then you have a link which you can share.

**Comment by Phonesis** [comment]
Was thinking something bit more old school - a directory of files / html that can be downloaded perhaps as a zip and then opened in a browser locally (no need for hosting). Or even a means to save as PDF...

**Comment by AlexKomanov** [comment]
Can be a good one. Stand-alone or - a pdf file.

**Comment by Phonesis** [comment]
Either works for me!

**Comment by kenhosr** [comment]
The HTML report can open trace view, which is very nice. Ideally we can open the standalone HTML version which also include the trace view and screenshots, directly from CI/CD build artifacts, so people do not need to open another URL(which we may need to add authentication to enable access control)

**Comment by mxschmitt** [comment]
The HTML report is now self contained. Let us know if something is missing in the next release (1.17).
