### ISSUE TITLE
[BUG] isVisible returns true when an element is completely overlapped by another element

### ISSUE THREAD

**Issue by devzerker** [microsoft/playwright#9923]
**Context:**
- Playwright Version: 1.16.2
- Operating System: Windows 10
- Node.js version: v14.18.1
- Browser: Chromium

```javascript
import { test, expect } from '@playwright/test';

test('overflow test', async ({ page }) => {
    await page.goto('https://devzerker.github.io/isvisible-repro/');
    const smallBox = page.locator('#small-box');
    const isVisible = await smallBox.isVisible(); // should be false
    expect(isVisible).toBeFalsy();
});
```

**Describe the bug**

Here is an [example ](https://devzerker.github.io/isvisible-repro/) of the div #small-box is completely overlapped by another div #big-box. The #small-box div is actually not visible, but playwright thinks differently

**Comment by mxschmitt** [comment]
This is our current definition of visible elements: https://playwright.dev/docs/actionability#visible

If you have any suggestions, let us know then we can create a feature request out of it.

**Comment by devzerker** [comment]
> This is our current definition of visible elements: https://playwright.dev/docs/actionability#visible
> 
> If you have any suggestions, let us know then we can create a feature request out of it.

Is there any workaround to check if an element is visible for humans?

**Comment by mxschmitt** [comment]
You can use:

```js
const smallBox = page.locator('#small-box');
await smallBox.click({ trial: true });
```

which will only perform the actionability checks and skips the click. It will fail when the element is not clickable. Would this work for your use-case?

**Comment by devzerker** [comment]
Looks weird, but ok, that works. Any plans to extend isVisible API for a more convenient/intuitive way?

**Comment by mxschmitt** [comment]
There are currently no plans for extending the isVisible API. Closing as won't fix.

**Comment by fmalvisi** [comment]
Greetings mxschmitt, 
your solution does not seem to work in case the div is not visible for example because it is drawn outside the height of the parent (with overflow: hidden), you can still real-click and trial-click the div.

I do not understand why you chose this definition for visible elements as it is completely insufficient for testing purposes.

**Comment by kingbeazer** [comment]
I have found a solution to this.  It is possible to test for a click at a specific Position within the element.  So you can test that all corners of the element are clickable.  As long as you can find out the size of the element.  I defined a locator called "smallBox".
await smallBox.ClickAsync(new LocatorClickOptions { Position = new Position() { X = 1, Y = 49 } }); - This would pass
await smallBox.ClickAsync(new LocatorClickOptions { Position = new Position() { X = 1, Y = 1 } }); - This would fail.

**Comment by acsbendi** [comment]
I agree with what's been said here previously, the current definition of `isVisible` is not useful in every scenario. 

I suggest reopening this issue, and I also have a concrete suggestion, somewhat similar to @kingbeazer's, which I could contribute as a fix: 
```typescript
element.evaluate((el) => {
    const rect = el.getBoundingClientRect()

    const isPointVisible = (x: number, y: number) => {
      const elementAtPoint = document.elementFromPoint(x, y)

      return el.contains(elementAtPoint) || elementAtPoint === el
    }

    const pointsToCheck = [
      // top-left corner
      {x: rect.left + 1, y: rect.top + 1},
      // top-right corner
      {x: rect.right - 1, y: rect.top + 1},
      // bottom-left corner
      {x: rect.left + 1, y: rect.bottom - 1},
      // bottom-right corner
      {x: rect.right - 1, y: rect.bottom - 1},
      // center
      {x: rect.left + (rect.width / 2), y: rect.top + (rect.height / 2)}
    ]

    return pointsToCheck.every((point) => isPointVisible(point.x, point.y))
})
```
This returns whether the element is visible (not overlapped) in certain concrete points and overall, returns true if it's visible in every point. The returned boolean value could be included in the definition of `isVisible`. The list of points to check could be extended further.

What do you think @mxschmitt @fmalvisi @devzerker?

**Comment by acsbendi** [comment]
@mxschmitt @fmalvisi @devzerker I have now opened a [new issue](https://github.com/microsoft/playwright/issues/34778) to track this as a feature request, which is probably the appropriate type considering that the current implementation of `isVisible` matches its definition (even if it is lacking).

**Comment by VGervasio** [comment]
What about using `toBeInViewPort()` (https://playwright.dev/docs/next/api/class-locatorassertions#locator-assertions-to-be-in-viewport) ?

**Comment by badsyntax** [comment]
> You can use:
> 
> const smallBox = page.locator('#small-box');
> await smallBox.click({ trial: true });
> which will only perform the actionability checks and skips the click. It will fail when the element is not clickable. Would this work for your use-case?

This appears to work fine for me:

```ts
// Confirm the button is NOT clickable
expect(async () => {
  await page.getByTestId('some-button').click({
    trial: true,
  });
}).not.toPass();
```

**Comment by Vampire2008** [comment]
Using `locator.click()` is not good workaround.
I have expandable lists on page. I need to check that only one expanded and all other not and not visible. They hided by `overflow` because of using animations.
Using `locator.click()` to check that 20 elements is not visisble takes very long time (with retries in `click`).
Any other solutions?

**Comment by Vovencia** [comment]
I implemented the check like this:

```typescript
async function isHidden(element: Locator): Promise<boolean> {
	if (!(await element.isVisible())) {
		return true;
	}

	return element.evaluate((el) => {
		let depth = 0;

		do {
			const bound = el.getBoundingClientRect();

			const styles = window.getComputedStyle(el);

			if (bound.width === 0 || bound.height === 0) {
				if (depth === 0) {
					return true;
				}
				if (styles.overflowX === "hidden" || styles.overflowY === "hidden") {
					return true;
				}
			}
			if (styles.visibility === "hidden") {
				return true;
			}
			if (styles.opacity === "0") {
				return true;
			}

			depth++;
		} while (el = el.parentElement);

		return false;
	}, []);
}
```
