### ISSUE TITLE
[Feature] pass browser args to playwright codegen cli

### ISSUE THREAD

**Issue by lavcraft** [microsoft/playwright#9928]
Hello, i can't find a way to do this:

```shell
npx playwright codegen --load-storage=session-admin.json --use-file-for-fake-video-capture --use-fake-device-for-media-stream
```

This flags is required for pass scenario and generate test. But can't find in documentation (tried add to `playwright.config.ts`, but not any effect)

Could explain how to add custom launch flags to cli command?

**Comment by mxschmitt** [comment]
Since this is not a common setup, we recommend for that to use `page.pause()`: https://playwright.dev/docs/cli#codegen-with-custom-setup

**Comment by lavcraft** [comment]
@mxschmitt thanks. Looks useful. But if i could pass args to codegen command, i have been happy to use it by more native way, because codegen is rare command in my case, use it to generate boilerplate tests

**Comment by mxschmitt** [comment]
Passing additional args to the browser is not a very common use-case. For that we recommend the custom setup with the Playwright inspector. 

Closing by that.

**Comment by shanshanzhu** [comment]
Sorry to bump up this old thread. My use case is in a remote dev flow, which is to start the `playwright codegen` in a remote server (no monitor), and proxy to use my local monitor to do the codegen step.

I'm trying to see if I can pass `remote-debugging-port` or `remote-debugging-address` to chromium but came across this old post.

For  `https://playwright.dev/docs/cli#codegen-with-custom-setup`
Do you mean this link? The previous link is not working
https://playwright.dev/docs/codegen#record-using-custom-setup

The example is not straightforward and I think it won't work for my purpose. How can I pass this `page.pause()` code before even starting `playwright codegen`? Could you help? @mxschmitt 

```If you would like to use codegen in some non-standard setup (for example, use [browserContext.route()](https://playwright.dev/docs/api/class-browsercontext#browser-context-route)), it is possible to call [page.pause()](https://playwright.dev/docs/api/class-page#page-pause) that will open a separate window with codegen controls.

const { chromium } = require('@playwright/test');

(async () => {
  // Make sure to run headed.
  const browser = await chromium.launch({ headless: false });

  // Setup context however you like.
  const context = await browser.newContext({ /* pass any options */ });
  await context.route('**/*', route => route.continue());

  // Pause the page, and start recording manually.
  const page = await context.newPage();
  await page.pause();
})();```

> Since this is not a common setup, we recommend for that to use `page.pause()`: https://playwright.dev/docs/cli#codegen-with-custom-setup
> 
> So in your case you create a small JS file, where you launch the browser, the storage and then call page.pause. See here: https://playwright.dev/docs/library
