### ISSUE TITLE
[BUG] - DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.

### ISSUE THREAD

**Issue by softleo-llc** [microsoft/playwright#9934]
**Context:**
- Playwright Version: 1.12.3
- Operating System: Windows
- Node.js version: 12 or above
- Browser: Chromium, Firefox
- Extra: [any specific details about your environment]

Getting below error while writing cookies:
 **DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.**

**Code Snippet**

`   const browserContext = page.context();
    const sessionStorage = JSON.stringify(values);
    process.env.SESSION_STORAGE = sessionStorage;

    await browserContext.addInitScript((storage: string) => {
      const entries = JSON.parse(storage);

      Object.keys(entries).forEach(key => {
        window.sessionStorage.setItem(key, entries[key]);
      });
    }, sessionStorage);
`

If we use sessionStorage, it is not working and getting above error. 

If we replace sessionStorage with localstorage, it is working fine in firefox but not working in chromium. Below is the error:

    DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

**Comment by mxschmitt** [comment]
Browsers are usually when creating a new page are on the about:blank page. There special security rules (e.g. CSP) apply which does not allow setting localStorage values. You need to check for the origin before setting values, see here: https://playwright.dev/docs/auth#session-storage

```ts
await context.addInitScript(storage => {
  if (window.location.hostname === 'example.com') {
    const entries = JSON.parse(storage);
    for (const [key, value] of Object.entries(entries)) {
      window.sessionStorage.setItem(key, entries[key]);
    }
  }
}, sessionStorage);
```
