### ISSUE TITLE
[Feature] implement `await expect(page).toHaveScreenshot()`

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#9938]
introduce a web-first assertion for Visual regression testing.

Today:

```js
expect(await page.screenshot()).toMatchSnapshot('foo.png');
```

After this:

```js
await expect(page).toHaveScreenshot('foo.png');
```

`toHaveScreenshot` should auto-retry screenshot until golden is reached.

`toHaveScreenshot` should also have:
- [x] hide field cursor
- [x] support locators
- ~disalbe css animations~ — https://github.com/microsoft/playwright/issues/11912
- ~mask out certain parts of screen? e.g. with selector~ — https://github.com/microsoft/playwright/issues/11913

**Comment by aslushnikov** [comment]
A summary of the VC with Dmitry regarding `toHaveScreenshot()` retries.

## Main thought

We would love `toHaveScreenshot()` to do retires and **wait** for the page to have the screenshot that's saved.

## Challenge: how to generate initial screenshots?

- **Manually**: it would be handy to have a 📸 button in codegen. When I see with my eyes that things are nice on the page, I take a snapshot, and it's saved to the right place!
- **Automatically**: auto-update 1000s of screenshots when website changes. How to wait for proper signal?
    - good idea: fighting progress animations: wait until screenshots stop changing
    - controversial idea: wait for network idle
    - not-so-good idea: wait for 1 additional second?!

---

Convenient code pointer for implementing retries:

https://github.com/microsoft/playwright/blob/d0a4480cf733d15d7d2662734f4d5376577fb481/src/test/matchers/toMatchText.ts#L65-L77

**Comment by p01** [comment]
The method name, `toHaveScreenshot(path)`, is pretty confusing. What does is it mean for a page to have a screenshot ?
The previous syntax is clear: 
```typescript
expect(await page.screenshot()).toMatchSnapshot('foo.png');` 
```
If you want to sprinkle some sugar on top, make the `.screenshot()` call implicit using this syntax:
```typescript
await expect(page).toMatchSnapshot('foo.png');
```
Where the `toMatchSnapshot(path)` method would do all the heavy lifting of waiting for the page to be stable, taking the screenshot and matching it against the snapshot.

As for how to automatically wait to take the screenshots, what I have done with great result is to force CSS animation and transition duration to a `0.001ms`, wait for networkIdle, and check that there are no pending Promises and setTimeout or setInterval ( triggered less than 2-3 seconds in the future, as anything longer is usually related to telemetry push ).

**Comment by aslushnikov** [comment]
> If you want to sprinkle some sugar on top, make the .screenshot() call implicit using this syntax:

@p01 changing `toMatchSnapshot` semantics would be a breaking change for the existing clients that we cannot afford.
So it'll stay unchanged for some time as a legacy solution.

> The method name, toHaveScreenshot(path), is pretty confusing.

We're open to suggestions!

**Comment by p01** [comment]
> changing `toMatchSnapshot` semantics would be a breaking change for the existing clients that we cannot afford.
So it'll stay unchanged for some time as a legacy solution.

Maybe I am missing something, because I don't think that adding `| Page` to the type of the `received` argument* of `toMatchSnapshot` and taking a screenshot if `received` is a Page is a breaking change. Existing tests will keep working. Also I see some other matchers that take a Page as received/second argument.

*: Changing `received: Buffer | string` to `received: Buffer | string | Page`

https://github.com/microsoft/playwright/blob/6881db681741320196df2f7c15f8c9194b0e6cb8/packages/playwright-test/src/matchers/toMatchSnapshot.ts#L29

**Comment by aslushnikov** [comment]
> Maybe I am missing something, because I don't think that adding | Page to the type of the received argument* of toMatchSnapshot

@p01 These kind of changes aren't breaking. The idea behind `toHaveScreenshot` method is to introduce auto-retries and change default threshold algorithm, which all would be breaking changes for `toMatchSnapshot`

**Comment by p01** [comment]
From a Playwright user perspective, I would much rather see these new capabilities introduced behind new options properties on the `screenshot()` or `toMatchSnapshot()` method just as you do in #11870 than get a new method that does something very similar to these two, but with different options, AND that might experience significant changes throughout the Playwright releases.

**Comment by aslushnikov** [comment]
Yes, most of the screenshot goodies are landed as part of `page.screenshot()` and friends. I filed separate bugs for [animation disabling](https://github.com/microsoft/playwright/issues/11912) and [blacking out elements](https://github.com/microsoft/playwright/issues/11913), feel free to follow these.

This issue is about web-first assertion flavor of `toMatchScreenshot` we consider adding; we're not fully convinced yet it's needed, but it sounds promising.

**Comment by 0xIslamTaha** [comment]
@aslushnikov This is exactly the feature that I would like to have. I used to implement the same logic to VST work in cypress. For the first-time screenshot, I would suggest setting a fixed waiting time as an option only if the image doesn't exist.

**Comment by aslushnikov** [comment]
> For the first-time screenshot, I would suggest setting a fixed waiting time as an option only if the image doesn't exist.

@0xIslamTaha So far we're leaning towards a "three consecutive screenshots are the same" heuristic to re-generate a first-time screenshot. Would this work in your scenarios?

**Comment by aslushnikov** [comment]
> Interesting idea, is the time period btwn each snapshot gonna be configurable?

@0xIslamTaha Time is a sloppy thing when it comes to CI so we generally try to avoid it. We can guarantee there's at least one animation frame between screenshots; this way we should be able to rule out some js-based animations to complete.

> I afraid that, in slow charts, all the three shots would be wrong

That's true; time might not solve this reliably though. Is there any request that triggers chart rendering? If there's one, it could be awaited with `await page.waitForEvent('request', request => { /** predicate **/ })` to make sure things are rendered.
This will also help later on with re-generating new screenshots once the page layout / styling changes.

**Comment by 0xIslamTaha** [comment]
@aslushnikov sounds good. It would be appreciated if this feature come with the 1.20 release 🚀

**Comment by 0xIslamTaha** [comment]
@aslushnikov here is an example of the chart that I would like to verify visually. The network is ideal while the graph is still rendering.

![Peek 2022-02-16 18-51](https://user-images.githubusercontent.com/17981089/154318040-27e4e685-aef4-4b80-a72b-23680411e509.gif)

**Comment by mariaceo** [comment]
> @aslushnikov here is an example of the chart that I would like to verify visually. The network is ideal while the graph is still rendering.
> 
> ![Peek 2022-02-16 18-51](https://user-images.githubusercontent.com/17981089/154318040-27e4e685-aef4-4b80-a72b-23680411e509.gif)
@0xIslamTaha, did you solve this now after the release?

**Comment by 0xIslamTaha** [comment]
@mariaceo The only thing I had to do is set a fixed waiting time. This solution is bad but there is no other option till the team release this PR
https://github.com/microsoft/playwright/issues/9938

**Comment by aslushnikov** [comment]
toHaveScreenshot is now scheduled for 1.21 that'll happen in April
