### ISSUE TITLE
[BUG] Cannot use page fixture in beforeAll

### ISSUE THREAD

**Issue by ZebraFlesh** [microsoft/playwright#9948]
**Context:**
- Playwright Version: 1.16
- Operating System: Mac
- Node.js version: 14.18.1
- Browser: Chromium

**Code Snippet**

```javascript
const { test, expect } = require('@playwright/test');

test.beforeAll(async ({ page }) => {
  await page.setExtraHTTPHeaders({
    'Secret-1': process.env['SECRET-1'],
    'Secret-2': process.env['SECRET-2'],
  });
});
```

**Describe the bug**

The docs for `test.beforeAll` [tell me](https://playwright.dev/docs/api/class-test#test-before-all) that the first parameter is a hookFunction of type `<function(Fixtures, TestInfo)> `. The docs for Fixtures [tell me](https://playwright.dev/docs/api/class-fixtures) that I should be able to access a `fixtures.page` object. However, using the above code generates the error:

```
Error: "context" and "page" fixtures are not supported in beforeAll. Use browser.newContext() instead.
```

Clearly these docs are wrong.

**Comment by mxschmitt** [comment]
Playwright provides context isolation. This means that for every test an isolated context is created, so in beforeAll there is no context yet, and by that no page. If you want to have your code working, then you need to put it into the beforeEach so it gets executed before every test on the page instance or you use as mentioned newContext and keep track of the context yourself, see here: https://playwright.dev/docs/test-retries#reuse-single-page-between-tests

**Comment by ZebraFlesh** [comment]
Thanks, I understand that. This is a documentation issue. (Or maybe a code issue, since the typing is incorrect?)

**Comment by mxschmitt** [comment]
Closing since we updated the docs and mention worker fixtures now.

**Comment by dman777** [comment]
> Playwright provides context isolation. This means that for every test an isolated context is created

On one hand, this is makes sense. But on the other hand, this does not feel correct. E2E is a test from a users point of view. The test should be written as how the user would use it. In many cases, this means re-using the same page.
