### ISSUE TITLE
 [Question] How to stop Playwright to close the browser after the test is finished?

### ISSUE THREAD

**Issue by directcuteo** [microsoft/playwright#9960]
Hi.
Is there a way to stop the popup browser instance to close after the test is finished?

Thank you!

**Comment by mxschmitt** [comment]
Do you mean you mean instead of creating new windows for each test you want to have the same window and page to get used over and over again?

**Comment by directcuteo** [comment]
Yes, something similar. Or triggering tests from the UI

**Comment by mxschmitt** [comment]
This is not yet possible but we are exploring this field. I changed it to a feature request.

**Comment by mxschmitt** [comment]
@directcuteo actually I was wrong, you can do it today, see here: https://playwright.dev/docs/test-retries/#reuse-single-page-between-tests

Let us know if that works for you!

**Comment by pavelfeldman** [comment]
Sorry, this is still unclear, could you describe your scenario?

**Comment by mxschmitt** [comment]
Closing since stale.

**Comment by iamzapata** [comment]
Looking for something similar. What is the best way to write new tests? I come from using cypress and writing new tests is really convenient because the test runner stays open and you can make changes and confirm the output right away.

**Comment by wanderleihuttel** [comment]
This would be interesting.
