### ISSUE TITLE
HTML Reporter 'open: "never"' Option Not Implemented

### ISSUE THREAD

**Issue by nate-buck** [microsoft/playwright#9973]
**Context:**
- Playwright Version: 1.16.3
- Operating System: Windows 10 Pro
- Node.js version: 14.7.6
- Browser: Chromium
- Extra: n/a

**Code Snippet**
From local config:
`reporter: process.env.CI ? [["github"], ["html", { outputFolder: "test-results/reports" }]] : [["list"], ["html", { outputFolder: "test-results/reports", open: "never" }]]`

_From the [repo](https://github.com/microsoft/playwright/blob/master/packages/playwright-test/src/reporters/html.ts) line 139:
`const shouldOpen = this._open === 'always' || (!ok && this._open === 'on-failure');`

**Describe the bug**
Having the 'never' open option has no impact. After a failed test, the results page is opened regardless of the setting.

**Comment by mxschmitt** [comment]
This was recently added. If you want to try out today you can install the next channel: `npm install @playwright/test@next` or wait for 1.17 in a few weeks.

**Comment by nate-buck** [comment]
Thanks for the quick response. The HTML reporter is a great feature and I am so happy it has been added. I will wait for 1.17 since this poses no blocker to our integration. Thanks again.
