### ISSUE TITLE
[REGRESSION] Change docker from 1.15.x to 1.16.x that all screenshots need to be updated

### ISSUE THREAD

**Issue by xuanzhaopeng** [microsoft/playwright#9975]
### Context:
we have some screenshot comparing,  once we upgrade docker image from **v1.15.1 to v1.16.3** and **use 1.16.1 playwright library**, the html screenshots are different,  so we have to update all screenshots.  Pls notice we are using same version of Chromium for both v1.15.1 & 1.16.3 docker image:
```typescript
 browserVersion:  mozilla/5.0 (x11; linux x86_64) applewebkit/537.36 (khtml, like gecko) 
headlesschrome/97.0.4666.0 safari/537.36
```

is it expected? 

### Some investigation:
I use v1.15.1 docker image + playwright 1.16.3  + headless chromium 97.0.4666.0 => No changes of screenshot, test pass
I use v1.16.3 docker image + playwright 1.16.3 + headless chromium 97.0.4666.0 => Screenshot has been changed, tests are failed

### Screenshot comparing:
<img width="769" alt="Screenshot 2021-11-02 at 16 57 45" src="https://user-images.githubusercontent.com/5563244/139893502-e8f69c48-183d-44dd-b7de-b91dc41cad82.png">

**Comment by xuanzhaopeng** [comment]
I think the issue is coming from here: https://github.com/microsoft/playwright/pull/9599/files

**Comment by aslushnikov** [comment]
@xuanzhaopeng in docker 1.16.3, we no longer run XVFB / VNC. They are installed but are not used.

In the screenshots you submitted, it looks like fonts did change. Could it be the case? Can you share a simple repro so that I can play with it?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
