### ISSUE TITLE
[BUG] frame.fill() writing 3 times instead of once? 

### ISSUE THREAD

**Issue by wingardl** [microsoft/playwright#9981]
#### Context:

Playwright Version: 1.12
Operating System: Windows
Node.js version: 14.17.0
Browser: Chromium

#### Code Snippet
`frame.fill('tr[aria-rowindex="1"] td[role="rowheader"] #WACViewPanel_EditingElement', 'stuff');`

#### Describe the bug

This fills my selected element 3 times, instead of once.

Looking at the documentation, it seems like `frame.fill(selector, value)` is expected to write to the first element matching the selector once - is that guaranteed? 
 
I am currently using playwright (v 1.12.0) to test writing to a table in a Word Web document. The first cell (at position 1,1 using 1-index) is a special case requiring a different selector. For other cells in the table, the following writes 'stuff' in that cell once:
 
`await frame.fill('tr[aria-rowindex="2"] td:nth-child(4) .TableCellContent .OutlineElement #WACViewPanel_EditingElement', 'stuff');` 
 
However, when I try to write to the cell at 1,1 using the code under 'Code Snippet' 'stuff' is written to the cell 3 times.

**Comment by JoelEinbinder** [comment]
`fill` is definitely only supposed to fill once. If I understand correctly the value of your `#WACViewPanel_EditingElement` element is `stuffstuffstuff`?

1. Can you provide some code that I can use to reproduce the problem?
2. Verbose api logs will help figure out what fill is doing: https://playwright.dev/docs/debug#verbose-api-logs
3. Playwright v1.12 is a bit old now. Does this still occur with v1.16?

**Comment by wingardl** [comment]
Yes that's right, the value of the element is `stuffstuffstuff`. I'll check if this still occurs with v1.16 and update this thread. 

Here is a larger section of code that is being run. Before this I run a setup that passes the frame from [this page](https://1drv.ms/w/s!Ar1Yd2q8DWm3gdsINklmtNddVV3w2g?e=Ryjvue) to this function:

```
export async function addTable(frame, c: number, r: number, content = DEFAULT_CONTENT): Promise<any> {
  //make sure that the table dimensions are valid
  if (r < 1 || r > 100 || c < 1 || c > 63) return;

  await frame.click('button[role="tab"]:has-text("Insert")');
  // Click [aria-label="Table"]
  await frame.click('[aria-label="Table"]');
  //if table is 10x8 or smaller, use the grid table display
  if (c <= 10 && r <= 8) {
    await frame.click(`[aria-label="${c}x${r} Table"]`);
  } else {
    // Click [aria-label="Insert Table..."]
    await frame.click('[aria-label="Insert Table..."]');
    await frame.click('#TableSizeDialogColumnSpinner');
    await frame.fill('#TableSizeDialogColumnSpinner', c);
    await frame.click('#TableSizeDialogRowSpinner');
    await frame.fill('#TableSizeDialogRowSpinner', r);
    await frame.click('text=OK');
  }

  //writes in cell (1,1) 3 times
  await frame.click('tr[aria-rowindex="1"] td[role="rowheader"]');
  await frame.fill('tr[aria-rowindex="1"] td[role="rowheader"] #WACViewPanel_EditingElement', 'stuff'); 
}
```

**Comment by wingardl** [comment]
Just tried to repro after setting DEBUG env var and the problem is gone... Ran again from another terminal without the DEBUG var to confirm. It's now correctly writing to the table cell once so I'll mark this as closed
