### ISSUE TITLE
[Feature] Allow custom options when making screenshots with Playwright Test (e.g. fullscreen)

### ISSUE THREAD

**Issue by garciallorente-fer** [microsoft/playwright#9983]
Automatic Screenshots appear in the test output directory, typically test-results, but they are not FullPage.

You don't have the same options as in `page.screenshot([options])` , like "FullPage", which will be really useful to see some screenshot errors that otherwise you can't see (full page = full screenshot information)
```
import { PlaywrightTestConfig } from '@playwright/test';
const config: PlaywrightTestConfig = {
  use: {
    screenshot: 'only-on-failure',
  },
};
export default config;
```

**Comment by bamanczak** [comment]
In my case the failure screenshot that is not full-page, does not give the team much debug info, thus I would love this feature to be implemented.

**Comment by murraymichal** [comment]
hey! do you consider this doable in near future?

**Comment by tymfear** [comment]
So this collects feedbacks for 3 months already. Is there a way to push this forward?

**Comment by bamanczak** [comment]
I'm watching this issue, with high expectations, whenever I see a notification about it. 
In my project, we manage to live without it, but from time to time it's really annoying to not have a full page screenshot.

**Comment by garciallorente-fer** [comment]
Any updates regarding this? I would like to add to the Feature Request, the possibility to see the URL at the moment of the taken screenshot, as that would add even more visibility to the screenshot error, with a full page view and the URL of that page

**Comment by refactoreric** [comment]
None of my business really, but if you cannot wait for this feature it might be worth implementing it yourself (or one of your colleagues) and submitting it as a PR, in open source spirit. I think this is one of the easier enhancement requests.
