### ISSUE TITLE
[Feature] Provide the ability to log into the trace

### ISSUE THREAD

**Issue by MartinP-Autopilot** [microsoft/playwright#9996]
Is there a way to get the equivalent of console.log functionality for the trace (e.g. page.log)?  We have a few console.log but they obviously appear in the console and you can't determine when they occurred in relation to steps in the trace.

**Comment by mxschmitt** [comment]
Looks like a duplicate of https://github.com/microsoft/playwright/issues/8682 to me.

Or do you want to add custom steps inside your tests to the trace report?

**Comment by pavelfeldman** [comment]
Looks separate to me. Did you look at the Console tab in the trace viewer? Does it not contain the information you are looking for?

**Comment by mxschmitt** [comment]
Closing since stale.
